### ISSUE TITLE
Codice Errore EF008

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#10]
Nella fase di subentro , provata in ambiente di test , abbiamo una lista di errori su tutte le convivenze,  codice EF008 (Intestatario della scheda famiglia/convivenza assente). Questo tipo di errore non lo troviamo nell’elenco degli errori ANPR scaricato dal sito. Ci chiediamo se è un errore bloccante. Spesso il capo della convivenza non risiede nel comune

**Comment by gcarbonin** [comment]
Stiamo aggiornando la lista dei controlli. L'errore non bloccante deriva dal fatto che le informazioni relative all'intestatario della famiglia o al responsabile della convivenza non sono stati trasmessi oppure la famiglia/convivenza è stata trasmessa in modo errato.
Per una ulteriore analisi occorrono un paio di casi specifici (identificativo ANPR del soggetto)
