### ISSUE TITLE
[5008] mutazione liste di leva ed elettorali

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#100]
Pisa, ambiente di test, ID operazione ANPR 453947

Buongiorno,
se eseguiamo tramite il servizio 5008 una mutazione di tipo 05, la mutazione apparentemente va a buon fine (esito 0000) ma dalla Web-App non si vedono i dati variati né la registrazione dell'operazione.
Potete controllare i file allegati per segnalarci se ci sono dei dati errati?
Grazie.
Luca Bonini A.P.Systems
[5008-mutazione05.zip](https://github.com/italia/anpr/files/906174/5008-mutazione05.zip)

**Comment by gcarbonin** [comment]
Stiamo verificando

**Comment by gcarbonin** [comment]
I valori ammessi sono P S N. Allineiamo la documentazione, Puo' riprovare con un nuovo caso.

**Comment by gcarbonin** [comment]
Ha effettuato la prova? Può darmi un riscontro?

**Comment by LucaBonini64** [comment]
Buongiorno, abbiamo effettuato la prova sull'individuo con codice fiscale BLGFNC91B14G702J e la mutazione viene eseguita correttamente con esito positivo, però dopo aver fatto la modifica dalla WebApp i dati delle liste non sono più visibili, cioè è scomparso tutto il TAG delle liste e si vede solo il TAG dei dati della ricerca.

**Comment by gcarbonin** [comment]
Il problema dovrebbe essere risolto. Può darmi un riscontro?
