### ISSUE TITLE
Formato interni indirizzi

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1000]
Ci segnalano dei problemi a Pesaro sugli interni degli indirizzi numerici con spazi non significativi davanti.
Da tipoDato.xsd risulta che lo spazio e' consentito in questo campo.
Gli spazi sono presenti per consentire l'ordinamento corretto degli interni numerici.

Si chiede se questo dato e' gestito da parte vostra, allo stesso modo sia in subentro che nei vari servizi? 

Esempio di dato passato in subentro:
<interno1>  7</interno1>

Grazie
Carla Musian

**Comment by CarlaMusian** [comment]
Ripeto l'esempio che non si leggeva

  <interno1>  7</interno1>

**Comment by CarlaMusian** [comment]
Non riesco a riportarlo. E' il tag interno1 che ha 2 spazi e poi il numero 7  e la chiusura tag interno1
Scusate

**Comment by mttfranci** [comment]
Ci potreste fornire un id anpr o comunale di un soggetto tramesso in subentro?
Voi vorreste il dato in ANPR così come trasmesso il 10 Dicembre con il subentro?
Grazie in anticipo.

**Comment by MichelePauluzzi** [comment]
Con il subentro gli interni sono usciti con gli spazi davanti, e sono tutt'ora con gli spazi davanti.
Al momento in cui vengono effettuati dei cambi di abitazione o iscrizioni, nella comunicazione gli indirizzi hanno gli spazi davanti agli interni, ma ANPR li cancella, risultando in un indirizzo diverso per quanto riguarda noi.
Operazione di cambio di abitazione 38671323
Operazione che il programma manda fuori con la rettifica dell'indirizzo che va male in quanto per ANPR gli spazi non vengono considerati 38671370

**Comment by mttfranci** [comment]
In ANPR, gli spazi in testa e coda alle stringhe non vengono considerati significativi (vale a dire che ai fini dei confronti il valore va considerato uguale).
Anche i gestionali dovrebbero comportarsi allo stesso modo.
Gli ambienti di test comuni e presubentro servono anche per individuare tali comportamenti e adeguarsi prima del passaggio in produzione.
Per maggiore coerenza, stiamo valutando di uniformare l'acquisizione in fase di subentro a quella dei web service.
Cordiali saluti

Assistenza ANPR
