### ISSUE TITLE
[5005] Iscrizione da Comune Subentrato - Errore 999

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1001]
ambiente di PRODUZIONE - comune di BRUGHERIO (MB)

idSoggettoANPR 29931484 
idOperazioneComune 2018002069 (ws 5005)
il web-service ritorna l'errore "999 - E - Operazione non effettuabile"

probabilmente il soggetto in ANPR a qualche campo o carattere che da problemi (anche se la consultazione va a buon fine...)
comunque, non capendo dal messaggio le cause dell'errore, abbiamo bisogno che ci indichiate voi cosa blocca l'operazione...

grazie 
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, dovremmo aver trovato il problema, potete riprovare cortesemente?

**Comment by AMonopoliADS** [comment]
abbiamo inviato con successo la comunicazione.
per situazioni analoghe, il problema è stato risolto anche per il futuro?

grazie.

**Comment by mttfranci** [comment]
Questa tipologia di problema dovrebbe essere risolto in generale con la correzione appena rilasciata (4.1.21) 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

Saluti

Assistenza ANPR
