### ISSUE TITLE
anomalia cambio di indirizzo con soggetto 23180218

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1002]
Il soggetto 23180218 appartenente alla famiglia 12196412 si è trasferito in questo comune (108009) in "VIA PADANIA 3".
Nel registrare la mutazione anagrafica col nostro gestionale (APKAPPA), il sistema ANPR dà il seguente errore:
"ERRORE DA ANPR: 
EF008 - Intestatario della scheda famiglia/convivenza assente"

I riferimenti di questa segnalazione sono:
Andrea Paltrinieri
tel. 0392201060
e-mail paltrinieri.andrea@biassono.org

**Comment by frmariani** [comment]
nel servizio che avete utilizzato, trattiamo i cambi di residenza dell'intera famiglia, pertanto non è necessario inviare l'elenco dei soggetti appartenenti alla stessa; qualora fossero inviati, deve essere presente almeno l'intestatario della famiglia.
Nel vostro caso, essendo presente il soggetto idanpr 23180218 nell'elenco soggetti, unico componente della famiglia, il codice legame deve essere necessariamente 1 - Intestatario  e non 3 "figlio/figlia"

**Comment by frmariani** [comment]
soggetto correttamente trasferito
