### ISSUE TITLE
Problema su Carta Identità emessa da Consolato

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1003]
Comune di Modena - Ambiente di produzione

Buongiorno,
il soggetto AIRE con idANPR 19209240 è nato negli anni '50 a Pordenone, allora compreso nella provincia di Udine con codice ISTAT 30109, e in ANPR viene visualizzato correttamente. 
Nel 1968, alla creazione della provincia di Pordenone, i comuni della provincia di Udine sono stati rinumerati, e il codice 30109 assegnato a Sedegliano. 
Il consolato di Monaco di Baviera ha rilasciato al soggetto una carta d' identità sbagliata in cui risulta nato a Sedegliano ed ora insiste per un nostro intervento per "correggere" il dato, che però a noi risulta già a posto. 
Il sistema di rilascio C.I. dei Consolati non legge ANPR? C' è qualche azione che possiamo fare perchè il Consolato "veda" il comune giusto?

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera,
a seguito di verifiche con il Ministero Affari Esteri risulta che effettivamente il problema è del loro applicativo. Potete rispondere al Consolato di scrivere all’indirizzo anagrafe@esteri.it così che gli possono indicare un modo per stampare una nuova carta corretta.

N. Capozzi
