### ISSUE TITLE
Certificazione - rimborso stampati

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1004]
Buongiorno, un nostro cliente, comune subentrato in ambiente di produzione, chiede se è possibile aggiungere nella stampa dei certificati emessi da ANPR, oltre all'importo del diritto di segreteria, anche un importo relativo al rimborso stampati.

Grazie per l'attenzione.
Siscom S.P.A.

**Comment by rvinzani** [comment]
Attualmente non è previsto un campo apposito dove aggiungere questo importo.
E' comunque possibile utilizzare le annotazioni a tale scopo
