### ISSUE TITLE
Risoluzione disallineamento codice fiscale aire

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1007]
Ambiente produzione. id cittadino 42228250
In agenzia entrate residente in Italia nel comune 041013.
In anpr residente aire del comune 041013.

L'impressione è che non sia gestito il caso in quanto manca un indirizzo italiano da aggiornare in AE.

Segnalo inoltre che lo stesso cittadino al subentro presentava un errore EA048 "Codice fiscale formalmente errato", quando in realtà in AE c'è con lo stesso cf.

Marco Migliori
PAL Informatica

**Comment by ncapozzi** [comment]
Buonasera, 
il codice fiscale non è validato. E' necessario accedere alla web app, Utilità e notifiche, Risoluzione disallineamenti con Agenzia Entrate, cercare il cittadino e confermare i dati di AE. Come indirizzo viene comunque preso quello estero risultante al comune (rif. pag. 16 del documento VALIDAZIONE DEL CODICE FISCALE E DEI DATI ANAGRAFICI E RISOLUZIONE DISALLINEAMENTI CON L’AGENZIA DELLE ENTRATE).
N. Capozzi
