### ISSUE TITLE
Esito AE: Richiesta incongruente - nessun campo variato (Codice 14)

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1009]
Comune di Modena - ambiente di produzione

Buongiorno,
si deve reiscrivere per ricomparsa il soggetto con idANPR 19249730 cancellato per irreperibilità, ma viene restituito l' errore :
" idSchedaSoggettoANPR 19249730 non presente o dati anagrafici incongruenti" 
in quanto su AE ha comune di nascita SERRAMAZZONI (denominazione attuale) invece di MONFESTINO IN SERRAMAZZONI (denominazione corretta alla nascita). Per poter allineare il dato si annulla temporaneamente la cancellazione e si tenta di usare il tasto "CONFERMA ANPR" nella funzione di Risoluzione disallineamenti, ottenendo però questo messaggio:
"Esito AE: Richiesta incongruente - nessun campo variato (Codice 14)"
che impedisce di portare a termine l' operazione (è consentito solo annullarla). 
Come possiamo procedere?

Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Gent.le Sig.ra Fiorini, il soggetto inviato in subentro ha come comune di nascita indicato 
Monfestino in Serra Mazzoni. Per questo motivo, la reiscrizione con la denominazione 
Monfestino in Serramazzoni genera un errore. Saluti
