### ISSUE TITLE
[Test 6001] Richiesta certificati con IdSchedaSoggettoComune

### ISSUE THREAD

**Issue by DomenicoGallo** [italia/anpr#101]
Salve, 
richiedendo qualsiasi certificato,nelle generalità del Soggetto Intestatario, è possibile determinare il cittadino solo utilizzando l'IdSchedaSoggettoComune, senza passare Nome e Cognome? (IdOperazione 3021, Ambiente di test, Comune di Cittanova)

Cordiali Saluti
Domenico Gallo
KIBERNETES SRL.

**Comment by gcarbonin** [comment]
No occorre indicare anche cognome e nome
