### ISSUE TITLE
[5008] completamento dati con variazione generalità

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1011]
Ambiente di produzione, comune di Lecce

in fase di iscrizione preliminare (id operazione ANPR 39720265) è stato inserito in ANPR con il servizio 1002 il soggetto ID ANPR 42956500.
All'atto del completamento dati ci si rende conto di aver sbagliato il cognome (si è inserito uno spazio in più dove non c'era).
Viene quindi corretto il dato localmente e si tenta di comunicarlo ad ANPR con la mutazione di completamento 5008 di tipo 20 (id ANPR 39734617).

Riceviamo però in risposta  l'errore EAM91 "Richiesta incongruente - soggetto NON marcato ANPR".

Cosa significa ?
Come dobbiamo comportarci ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by rvinzani** [comment]
Salve, può correggere l'errore utilizzando la funzione di risoluzione anomalie presente in Utilità e Notifiche dell'applicazione Web. Confermi i dati AE se sono corretti. I dati della residenza saranno comunque presi per buoni quelli di ANPR
