### ISSUE TITLE
immigrazione di italiana nata in jugoslavia

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#1012]
Salve,
in ambiente di prodzione stiamo cercando di immigrare da comune non subentrato una persona italiana nata in jugoslavia (1984) , 
non riesco ad inserire i dati che vengono forniti dall'altro comune:
nata a Dubrovnik (jugoslavia).
La jugoslavia non è codificata, il CF della nazione di nascita è Z118, se provo a codificare la nazione attuale (Croazia) il codice fiscale non viene accettato per come calcolato da AT.
Anche procedendo come per i subentri, mettendo nazione NON codificata abbiamo questa risposta:
AEE95 - Operazione non effettuabile

grazie per l'aiuto
Ale

**Comment by frmariani** [comment]
Nel caso di luogo di nascita non più valido, come appunto la Yugoslavia, l'iter da seguire è proprio quello di utilizzare una particolare codifica nel codice stato; 
se può essere utile le invio un esempio corrispondente al suo caso, altrimenti mi  indichi per favore l'idanpr o l'idoperazionecomune ;

<luogoNascita>
                <localita>
                    <descrizioneLocalita>Dubrovnik</descrizioneLocalita>
                    <descrizioneStato>Yugoslavia</descrizioneStato>
                    <codiceStato>998</codiceStato>
                </localita>
            </luogoNascita>

**Comment by ComuneSegrate** [comment]
Salve anche noi abbiamo lo stesso problema, cittadina italiana nata a Kemerovo (URSS) da iscrivere in ANPR; abbiamo inserito il luogo di nascita Kemerovo dovendo mettere per forza come,Stato di nascita "non classificabile" ,come codice istat "998" e con il codice Belfiore Z135 (come da suo codice fiscale). Riusciamo ad inviare l'iscrizione solo se mettiamo, nella Gestione Codice Fiscale, "iscrizione senza validazione", che poi non ci farà emettere la CIE. In alternativa, se la iscriviamo come nata nella città attuale ci viene modificato il codice fiscale in Z154. Come possiamo risolvere il problema?
Grazie per la collaborazione.

**Comment by frmariani** [comment]
per favore l'idoperazionecomune o idanpr, grazie.

**Comment by frmariani** [comment]
per l'operazione del comune di Segrate, l'oggetto "luogo di nascita"  dovrà contenere le seguenti informazioni:
descrizioneLocalita  Kemerovo    
descrizioneStato  URSS  (al posto di NON ATTRIBUIBILE)
codiceStato   998   
eliminazione dell'informazione sulla provinciaContea

**Comment by ale-magna** [comment]
idanpr 40089226
ho bypassato il problema allineando il CF in un secondo momento, mi dica se la persona con idScheda 44435242 è corretta,
grazie

**Comment by frmariani** [comment]
ci potrebbero essere dei problemi per il cittadino: nei certificati e nei documenti avrà la seguente dicitura nel luogo di nascita
nato il .......in Dubrovnik Iugoslavia (NON attribuibile)
al posto di 
nato il .... in Dubrovnik  (Yugoslavia)
