### ISSUE TITLE
Ambiente Presubentro errore AEE97

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1017]
ambiente presubentro comune di Cividale del Friuli
Da diversi giorni non riusciamo a procedere con i test di iscrizione da comune non subentrato.
riceviamo l'errore AEE97

**Comment by frmariani** [comment]
Stiamo provvedendo alla risoluzione del problema, grazie per la segnalazione.

**Comment by frmariani** [comment]
il problema è stato risolto, potete riprovare
