### ISSUE TITLE
[3002] Internal error (from server)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1018]
ambiente di PRODUZIONE - comune di FIORANO MODENESE

abbiamo svariati soggetti AIRE, per i quali il tentativo di consultazione via web-service ritorna l'errore
```
<env:Fault>
  <faultcode>env:Server</faultcode>
  <faultstring>Internal Error (from server)</faultstring>
</env:Fault>
```

vedere ad esempio idSoggettoANPR 35768445
(rif. idOperazioneComune 2018300664)

cosa blocca la restituzione dei dati?
se necessario possiamo fornire anche altri casi...

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Nel caso segnalato è presente il carattere "º" nell'indirizzo che non è più ammesso
LAS ESPUELAS 2074-Bº BAJO LA VINA.
Ci potete dire per favore se gli altri casi riscontrati hanno lo stesso problema?

Grazie
N. Capozzi

**Comment by AMonopoliADS** [comment]
presumiblmente si.
come facciamo a sanare la situazione per consentire l'interrogazione dei dati?
grazie

**Comment by ncapozzi** [comment]
Buonasera,
le fornirò ulteriori chiarimenti per email. Eventualmente può contattarmi telefonicamente al numero indicato
N. Capozzi
