### ISSUE TITLE
(5001) Internal server error

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1019]
Segnalo un internal server error in risposta ad una richiesta 5001

idOperazioneComune JD77451
codMittente 027038
codDestinatario ANPR01
operazioneRichiesta 5001

Grazie. Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Il campo note indirizzo contiene caratteri non più supportati. La risposta pertanto non viene validata. 
A breve effettueremo, in accordo con comuni e software house, la bonifica dei caratteri non più ammessi

**Comment by Raffive** [comment]
Buonasera, 
siamo ancora in attesa di chiudere la pratica del 02 ottobre 2018.
Grazie
Raffaella Comune di Spinea

**Comment by rvinzani** [comment]
Chiudo la issue con riferimento alla #1060 . In caso di problemi o ulteriori richieste è possibile aprire un'altra issue facendo riferimento a questa stessa
