### ISSUE TITLE
[1010] - Elementi ListeControllo

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#102]
Pisa, ambiente di test.

Buongiorno, nel servizio 1010 è previsto come dato obbligatorio la presenza dell'oggetto ListeControlli nel formato Nome e Valore. 
Da nessuna parte, però, abbiamo trovato indicazioni di quali siano questi controlli e i valori che possono assumere, potete comunicarceli?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
E' una lista prevista per successivi utilizzi. E' sufficiente indicare nella richiesta <datiControllo/>
