### ISSUE TITLE
codiceLegame mancante

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1021]
Mutazione di residenza con trasferimento da comune subentrato.
Il soggetto nel comune di precedente residenza è iscritto in convivenza anagrafica.
E' privo di codiceLegame.
Questa mancanza causa un problema alla logica del gestionale locale.
Dalla lettura della documentazione io capisco che codiceLegame è dato obbligatorio, oppure ci sono eccezioni?
Vorrei capire la cosa per decidere un eventuale ritocco alla logica del gestionale locale.
idANPR del soggetto 16882804
Grazie.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
il codice legame è un dato obbligatorio.
per favore potete verificare l'idanpr del soggetto ? negli ambienti esposti non è presente

**Comment by bfilipazzi** [comment]
Mi correggo, l'idAnpr del soggetto è 30192975
Filipazzi - Maggioli

**Comment by frmariani** [comment]
il soggetto risulta correttamente membro della convivenza;
per favore l'idanpr dell'operazione fallita, grazie.

**Comment by frmariani** [comment]
avete risolto il problema ?
