### ISSUE TITLE
Aggiornamento CIE su ANPR Cod ISTAT 12042 in PRODUZIONE

### ISSUE THREAD

**Issue by FulvioDeda** [italia/anpr#1023]
Salve 
l'ente in oggetto é subentrato il 19 dic 2018. In questi giorni ha emesso CIE , ma di queste non vi é traccia da consultazione Individuo ANPR. Potete verificare?
Grazie

Ente Cod ISTAT 12042 in PRODUZIONE

Dedagroup Public Services

**Comment by rvinzani** [comment]
Stiamo verificando. Vi faremo sapere quanto prima

**Comment by rvinzani** [comment]
Le informazioni sono state acquisite in ANPR. Chiudiamo la issue. In caso di ulteriori problemi potete aprirne un'altra.
