### ISSUE TITLE
[5001] dubbio su due pratiche concomitanti

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1024]
Ambiente di produzione id famiglia 24059923.
Il soggetto id 42253048 ha dichiarato un cambio indirizzo il 23/11 (prima del subentro)
Gli altri tre soggetti presenti, hanno dichiarato immigrazione dall'estero il 26/11 (prima del subentro).
Nel subentro non abbiamo aperto i procedimenti in corso.

Stanno caricando gli accertamenti (in questo caso solo dei 3 immigrati dall'estero) e ci va in errore l'operazione ANPR 41639610, come EN237, La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata.
Non mi è chiarissimo il messaggio, lo attribuisco alle date differenti sui vari soggetti.

Ora questa operazione che abbiamo inviato è inutile in quanto dall'accertamento l'indirizzo corrisponde a quanto dichiarato, e ad ANPR non risulta alcun procedimento in corso, per cui potevamo anche non inviarla.
Premesso che è un caso raro mi sono però chiesto: qualora dall'accertamento parziale che stanno caricando gli operatori (il primo che hanno davanti non necessariamente in ordine), l'indirizzo accertato fosse differente, con che date avremmo dovuto inviare l'operazione 5001 di questa eventuale rettifica?

**Comment by MarcoMigliori** [comment]
Correggo quanto scritto nel messaggio originale: l'indirizzo accertato è differente da quello dichiarato. Non siamo riusciti a inserire l'operazione.

**Comment by rvinzani** [comment]
La data decorrenza della famiglia registrata in ANPR al subentro è 26/11/2018. Se si vuole effettuare un ripristino ante subentro (5001 tipo mutazione 8) è necessario impostare una data antecedente al 23/11. Nell'operazione effettuata invece è stata impostata come data quella del 26/11, quindi successiva alla prima dichiarata

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti è possibile aprirne una nuova facendo riferimento a questa stessa. Saluti
