### ISSUE TITLE
Cittadinanze coniugi di vedovi

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1025]
Ci siamo accorti che nella registrazione dei dati di coniugi deceduti a suo tempo, non e' possibile inserire
la cittadinanza che questi avevano al decesso se riguarda stati che attualmente non esistono; per esempio vedovi di persone di cittadinanza yugoslava deceduti quando esisteva questo stato.

Non e' corretto che il comune debba modificare la cittadinanza esatta di questi individui. Con il subentro
del comune di Verona non ci e' possibile completare i dati di una decina di Aire che sono in questa situazione.
La stessa cosa si puo' presentare per i genitori, in generale per individui collegati non piu' in vita.

Mentre per lo stato estero e' possibile passare il codice 998 con la descrizione dello stato non piu'
esistente, analoga possibilita' non e' prevista per le cittadinanze.

Grazie
Carla Musian

**Comment by ncapozzi** [comment]
Buonasera, il codice 998 non è ammesso per le cittadinanze in quanto sono richieste solo quelle valide all'attualità e non il dato storico. La cittadinanza del coniuge non è un dato obbligatorio, neanche in caso di completamento AIRE.

N. Capozzi
