### ISSUE TITLE
[1001] bambino iscritto nella famiglia del padre

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1026]
Ambiente produzione. Id operazione 42829653.
Padre (id 41794922) e madre (id 41794216) entrambi residenti, in famiglie diverse.
Nel compilare l'xml dell'iscrizione per nascita, indichiamo la famiglia di destinazione id anpr 23839340, corrispondente alla madre. Leggendo meglio la documentazione questo ramo sembra però ignorato.
Nella sezione  datiControllo, viene indicato filiazione=1, corrispondente a famiglia dei genitori. In questo campo avremmo dovuto indicare 3, corrispondente a madre.
Tuttavia mi chiedo perchè ANPR ha iscritto il bambino nella famiglia del padre, quando le indicazioni presenti nelle varie circolari/documentazioni sono di iscriverlo nella famiglia della madre. Ritengo che quando indicato 1, dovrebbe utilizzare la famiglia della madre per l'attribuzione della famiglia. Al limite solo qualora la madre non sia residente/individuabile, utilizzerà quella del padre.
In questa operazione, entrambi padre e madre sono stati individuati dall'id, e quindi ANPR a mio avviso poteva e doveva utilizzare l'id famiglia della madre.

**Comment by ncapozzi** [comment]
Buonasera,
la bambina cui si riferisce l'operazione di iscrizione 42829653 risulta correttamente associata in ANPR alla famiglia 23839340 il cui intestatario è la mamma. Pur essendo stato indicato 1 in attribuzioneFamiglia invece di 3, il sistema ha associato la bambina alla famiglia della madre da voi indicata.

N. Capozzi

**Comment by MarcoMigliori** [comment]
Non l'avevo precisato ma successivamente alla segnalazione, ho corretto l'assegnazione in questo modo:

- annullamento operazione di iscrizione, senza annullare codice fiscale

- rimandata operazione di iscrizione, cambiando il valore in datiControllo come famiglia madre, e chiedendo di validare il CF
