### ISSUE TITLE
Problemi ripristino posizione anagrafica

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1027]
Abbiamo problemi ad effettuare il ripristino posizione anagrafica. L'errore è il seguente:
ERRORE DA ANPR EN343 - La data di decorrenza della cancellazione per ripristino posizione anagrafica deve essere uguale alla data di iscrizione 21-01-2002 
cod. ind. ANPR 18922977

**Comment by azabatta** [comment]
Buongiorno, 
stiamo effettuando le opportune verifiche.

**Comment by Finalmentesubentrati** [comment]
Ho bisogno di concludere la pratica in tempi brevi. Grazie

**Comment by azabatta** [comment]
Buonasera, 
la modifica è stata trasferita in ambiente di esercizio. E' possibile riprovare, resto in attesa di un cortese cenno di riscontro.
Grazie

**Comment by Finalmentesubentrati** [comment]
Ok risolto
