### ISSUE TITLE
Problemi ripristino posizione anagrafica

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1028]
Abbiamo problemi ad effettuare un ripristino posizione anagrafica. L'errore è il seguente:
ERRORE DA ANPR EN343 - La data di decorrenza della cancellazione per ripristino posizione anagrafica deve essere uguale alla data di iscrizione 21-01-2002 
cod. ind. ANPR 18922977

**Comment by azabatta** [comment]
Buongiorno, 
si tratta dello stesso cittadino segnalato nella  della issue #1027?

**Comment by Finalmentesubentrati** [comment]
Ho necessità di concludere la partica in tempi brevi

**Comment by azabatta** [comment]
Buonasera, 
è stata apportata una correttiva che è pronta per il rilascio.
La informo appena sarà trasferita in ambiente di esercizio

**Comment by Finalmentesubentrati** [comment]
Ok. risolto
