### ISSUE TITLE
[5008] completamento dati divorziato, con coniuge residente in altro comune ANPR e dati non identici

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1029]
Ambiente produzione, id operazione 38050131.
Si sta registrando la definizione della pratica di iscrizione dell'id 37467343. 
Riceviamo l'errore EN272 "Alla data 02-04-2007 il soggetto (nome del coniuge id 30423931) risulta gia' coniugato o unito civilmente con un altro soggetto"
Tale soggetto, risulta divorziato da cittadina ora residente a Milano, altro comune ANPR. A Milano la cittadina, risulta divorziata da senzaCognome senzaNome. 
Il nostro Comune nel caricare i dati, ha inserito le generalità complete dell'ex coniuge , i dati di divorzio, ma non quelli di matrimonio.
Presumo che l'errore venga ricevuto perchè ANPR riconosce che il coniuge è residente in ANPR. Non so se il controllo è eseguito bene o meno, dato che nell'altro comune il dato non è presente. E'corretto che dia errore?

PS: ho successivamente rimandato l'operazione in errore, lasciando solo COGNOME e NOME del coniuge. Esito positivo.

**Comment by asqueglia** [comment]
Buongiorno, ci scusiamo per il ritardo nella risposta.
All'atto del subentro del comune di Milano, il soggetto idAnpr= 30423931 è stato trasmesso con un matrimonio senza data, senza data divorzio e con coniuge senza cognome e senza nome.
Di fatto questo matrimonio blocca l'operazione che avete tentato di fare sul soggetto coniuge con idAnpr=37467343 di vostra competenza;  trasmettendo, infatti, tutti i dati del coniuge, il servizio di perfezionamento pratica, tenta di effettuare una riconciliazione dei coniugi; la riconciliazione non va a buon fine essendo il matrimonio del primo soggetto (di Milano), privo di informazioni.
Per sanare la situazione e rendere possibile l'operazione desiderata (inserimento matrimonio con riconciliazione coniugi), è necessario revocare il matrimonio senza dati trasmesso da Milano tramite la scheda del soggetto con idAnpr= 30423931.
Al momento non è stata ancora rilasciata negli ambienti esposti la funzionalità di revoca; lo sarà a breve. E' comunque possibile inviare una PEC con la richiesta di revoca in modo da consentirci di poter procedere d'ufficio.
L'operazione che avete successivamente effettuato sul soggetto di vostra competenza è andata a buon fine in quando è stato richiesto di inserire il divorzio senza rconciliare i due coniugi, per cui se consultate il vostro cittadino risulta correttamente divorziato in data 02-APR-07, mentre se viene consultata la cittadina di Milano, non risultano i dati del matrimonio e del divorzio.
