### ISSUE TITLE
[5008] tipoMutazione '20': msg. "Soggetto non presente in Agenzia Entrate"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#103]
buongiorno.

il caso specifico che si sta testando è quello di un soggetto iscritto in via preliminare con delle generalità che, dopo gli accertamenti, vengono modificate (di solito capita per gli stranieri).

il procedimento che si è eseguito è il seguente:
- ws 1002 x iscrizione preliminare
- ws 5008 (tipoMutazione '01') per modifica generalità
- ws 5008 (tipoMutazione '20') per completamento dati in fase di iscrizione definitva.
su due prove fatte per due soggetti diversi, in fase di mutazione otteniamo questo errore:
EAV91 - E - Soggetto non presente in Agenzia Entrate

si faccia riferimento a queste due comunicazioni:
idOperazione: 2017000215 - DPPRE - comune di Faenza (l'errore scatta in sede di prima mutazione '01')
idOperazione: 2017000249 - DPPRE - comune di Faenza (l'errore scatta in sede di seconda mutazione '20')

grazie.
Alessandro Monopoli ADS

p.s. abbiamo un ticket aperto (#66) per un problema sulla ri-assegnazione del codice fiscale successivamente a cambio nome in ambiente di test (dptest). siamo in attesa di riscontro per procedere con nuovi test.
le problematiche potrebbero essere collegate...
grazie

**Comment by gcarbonin** [comment]
In realtà abbiamo visto che la posizione è stata trasmessa con il pre-subentro, successivamente cancellata e poi nuovamente iscritta. occorre considerare che quando si inviano i dati di pre-subentro, le informazioni vengono incrociate con l'archivio di produzione dell'Agenzia delle Entrate e  risultano quindi validate; quando si eseguono i test, l'archivio di AE con il quale si scambiano le informazioni, per evidenti motivi, è un archivio di test che contiene pochissimi codici fiscali. Quindi nei servizi occorre:
impostare a 3 il campo gestioneCf (vuol dire di proseguire con la registrazione anche in presenza di un errorre bloccante di AE) oppure in fase di iscrizione, chiede l'attribuzione (senza indicare il CF nella richiesta).  Per il caso in esame, suggeriamo di procedere con gestioneCF = 3

**Comment by AMonopoliADS** [comment]
il problema è che questa modalità non ci permette di eseguire dei test realmente preparatori al subentro definitivo, costringendoci a bypassare dei controlli in questo ambiente che invece in produzione dovranno essere gestiti in qualche modo... 
se non ci sono alternative ne prendiamo atto.
unico suggerimento/richiesta che provo a formulare: in considerazione del fatto che l'archivio AE è un archivio di test, con pochi codici fiscale, perchè non modificare la tipologia di messaggio in modo che sia un WARNING invece che un ERRORE bloccante? ovviamente dovrebbe essere una modifica da fare solo negli ambienti di test e pre-subentro...

grazie.
Alessandro ADS

**Comment by gcarbonin** [comment]
Quanto proposto rende il test irrealistico. Al contrario, separando le tipologie di test (quelli sul codice fiscale dagli altri intendo) è possibile effettuare un test completo. Se puo' essere utile possiamo integrare il piano di test pubblicato nel portale informativo con un set di prove "dedicate" ai servizi AE

**Comment by AMonopoliADS** [comment]
quanto proposto è perchè il problema si ripercuote su test che non hanno come oggetto il codice fiscale.
pongo un ulteriore esempio per fare capire meglio:
comune di Occhiobello - ambiente dppre
idOperazioneComune 2017000140 - iscrizione 1002 - con gestioneCF = '3'
idOperazioneComune 2017000229 - mutazione '20' x completamento dati - senza gestioneCF

si tratta di un caso dove il soggetto ha già un codice fiscale validato.
in fase di iscrizione si richiede di non validare, ed in fase di mutazione si richiede di non eseguire operazioni sul CF.
la mutazione non viene accettata per "soggetto non presente in ae"

**Comment by gcarbonin** [comment]
Come gia' spiegato, il codice fiscale validato in pre-subentro è un dato da utilizzare esclusivamente ai fini di un'eventuale bonifica dei dati APR e non per eseguire i test. I test dei servizi in pre-subentro deve essere eseguita con gestioneCF = 3; per testare i servizi, occorre chiedere un'attribuzione e poi è possibile procedere con le restanti operazioni.
