### ISSUE TITLE
Matrimoni consolari

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1030]
Si chiede come va registrato in anagrafe ANPR il comune di matrimonio quando questo avviene presso un consolato, come previsto dall'artt.6 e 12 del D.Lgs 3/2/2011 n.71 su "Ordinamento e funzioni degli uffici consolari"

Alcuni casi relativi ad AIRE coniugati in consolati, del comune di Verona risultano di difficile soluzione.
(vedi ID ANPR 43391381)
Grazie
Carla Musian

**Comment by ncapozzi** [comment]
Buonasera, il luogo evento di un matrimonio può essere in alternativa un comune italiano oppure uno stato estero con indicazione della località. Per il soggetto indicato sono stati correttamente indicati lo stato estero BRASILE e la località PORTO ALEGRE in cui è avvenuto il matrimonio come previsto.

N. Capozzi
