### ISSUE TITLE
[5001] blocco per stesso indirizzo in migrazione tra due comuni 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1033]
Ambiente di Produzione, comune di Lurago d'Erba.

Tentiamo di iscrivere nel comune una famiglia monocomponente che proviene da altro comune subentrato.
Utilizziamo per lo scopo il servizio 5001, ma la chiamata ci ritorna l'errore EN388 "La residenza inserita risulta uguale a quella attuale". (id operazione 43283987).

Cosa accade ? 

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, stiamo verificando la vostra segnalazione

**Comment by mttfranci** [comment]
Il caso è abbastanza complesso ed l'analisi è ancora in corso.
Vi facciamo sapere qualcosa appena possibile.

**Comment by mttfranci** [comment]
Dovremmo aver risolto un problema : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
Se volete potete riprovare.

**Comment by busaster** [comment]
Prova eseguita, la chiamata è andata a buon fine.
Problema risolto.
Grazie.
