### ISSUE TITLE
Tabella stati esteri - Saint Martin ovvero Sint Marteen

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1034]
Comune di Villa Cortese
Produzione

Oggi stavo procedendo all'iscrizione di un bambino nato nel 2013 a Saint Martin o Sint Marteen (Antille Olandesi).
Quando iscrivo da Stati che capitano raramente, prima mi documento ed ho scoperto (fonte Wikipedia) che le Antille Olandesi non esistono più dal 10 ottobre 2010 e Sint Marteen è una "nazione costitutiva" nell'ambito del Regno dei Paesi Bassi, infatti nella tabella Stati Esteri di ANPR comparte Sint Marteen.
Però nella stessa tabella non è valorizzato il Codice AT dello Stato di Sint Marteen e la madre mi ha presentato il Certificato di attribuzione del codice fiscale che riporta come Stato Estero di nascita Antille Olandesi che a mio parere è errato.

Chiedo di conoscere il Codice AT di Sint Marteen sperando sia lo stesso delle Soppresse Antille Olandesi.
La nazione di nascita attribuita da AE è corretta?

Mi sono anche accorto che collegandomi a [Link Sister Agenzia Entrate](https://sister.agenziaentrate.gov.it/CitizenArCom/index.jsp) e scaricando il file CSV degli Stati Esteri Attuali è presente Antille Olandesi e manca Sint Marteen. Scusate ma le tabelle non devono essere univoche su ANPR e AE?

Grazie

**Comment by ncapozzi** [comment]
Come anticipato per le vie brevi sono possibili due soluzioni
1 - si mantiene il CF già attribuito da Agenzia Entrate. Si effettua l'iscrizione richiedendo la validazione del CF e indicando 998 come codice dello stato estero di nascita e ANTILLE OLANDESI nella località
2 - si richiede un nuovo CF. Si effettua l'iscrizione richiedendo l'attribuzione del CF e indicando come codice dello stato estero di nascita quello sovrano su Saint Martin e Saint Martin nella località.

N. Capozzi

**Comment by cvignati** [comment]
@ncapozzi Buongiorno, la madre ci ha dichiarato di voler procedere all'iscrizione con località di nascita Saint Martin e Stato Estero Francia attribuendo, quindi, un nuovo CF.

Avendo un codice fiscale già attribuito qual'è la procedura per collegare il nuovo CF al vecchio?

Grazie

**Comment by ncapozzi** [comment]
Per effettuare il collegamento tra i CF dovete accedere alla WEB APP, utilità e notifiche, Risoluzione disallineamenti con Agenzia Entrate come indicato al documento seguente par. 4.1 https://www.anpr.interno.it/portale/documents/20182/239162/Risoluzione+disallineamenti+con+l%27Agenzia+delle+Entrate+14_12_2018.pdf/1d147877-f688-4d91-85bd-1885ff4938cd

In caso abbiate problemi ci possiamo sentire lunedì telefonicamente.

N. Capozzi

**Comment by cvignati** [comment]
Il cittadino attualmente ha 2 codici fiscali validati da AE e uno solo Marcato ANPR. Io vorrei che i codici fiscali siano collegati e siano confermati i dati, sia anagrafici che CF, della posizione con dati validati da AE e Marcati ANPR.

Grazie

**Comment by cvignati** [comment]
Ritorno, scusate la mia insistenza, a chiedere perché le tabelle dei territori esteri di ANPR e AE non siano le stesse

**Comment by cvignati** [comment]
@ncapozzi 

Ritorno, scusate la mia insistenza, a chiedere perché le tabelle dei territori esteri di ANPR e AE non siano le stesse.
Il cittadino ha codice fiscale con codice catastale Z501 che per la tabella di AE corrisponde alle Antille Olandesi e per la Tabella ANPR corrisponde all'Isola di Aruba.

Addirittura se interrogo il codice fiscale in PuntoFisco come luogo di nascita mi restituisce Antille Olandesi, se lo interrogo in WebApp ANPR -> Consultazione AE come luogo di nascita mi restituisce Isola di Aruba.

Impossibile lavorare in questa maniera, si rischia, come nel caso del mio cittadino, di creare posizioni errate subito in partenza.

Chiedo a Sogei, se possibile, avere un contatto di Agenzia delle Entrate per sviscerare questa problematica delle Tabelle.

Vorrei sottoporre un'altra questione.

Il mio cittadino, attualmente, ha 2 CF validati da AE ma 1 solo anche Marcato ANPR, quest'ultimo con dati anagrafici e CF corretti.
Per unire i CF esiste la funzione di Risoluzione Disallineamenti della WebApp.
Peccato che fleggando il Checkbox "Collega codici" un messaggio avvisa che i dati ANPR (quelli marcati ANPR ) verranno sostituiti con quelli presenti in AE. Vi sembra corretto?
Se una delle 2 posizioni è marcata ANPR, sicuramente questi dati anagrafici saranno quelli corretti, non quelli presenti in AE.

Chiedo un controllo su questa funzionalità di Disallineamento CF, in modo che se venga chiesto il collegamento di 2 CF e uno sia marcato ANPR vengano presi i dati anagrafici di ANPR e sovrascritti a quelli di AE e non il contrario.

Grazie

**Comment by ncapozzi** [comment]
Buonasera, 
il problema sul disallineamento delle dizioni di stati e comuni tra ANPR e Agenzia Entrate è noto e quest’ultima sta procedendo con un intervento sui propri sistemi per acquisire le informazioni della codifica e della dizione da parte del sistema ANPR. 

Per quanto riguarda la Risoluzione disallineamenti con Agenzia Entrate, la posizione marcata indica che i dati su ANPR sono congruenti con AE a parità di CF, non che siano corretti in assoluto.
La funzionalità consente di collegare due CF solo se il dato che deve essere aggiornato è quello di ANPR. In caso contrario il cittadino deve recarsi presso il competente Ufficio di Agenzia Entrate per chiedere il collegamento.

N. Capozzi
