### ISSUE TITLE
Matrimoni consolari #1030

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1035]
Buongiorno,

in merito al quesito in questione ID ANPR  43391381 si fa presente che 
i dati indicateci nella risposta "Per il soggetto indicato sono stati correttamente indicati lo stato estero BRASILE e la località PORTO ALEGRE in cui è avvenuto il matrimonio come previsto" non sono relativi all'evento di matrimonio ma alla nascita del coniuge.
Il matrimonio in questione risulta all' AMBASCIATA D'ITALIA IN BANGKOK (IT)

Carla Musian
Applicativo AscotWeb

**Comment by ncapozzi** [comment]
Buongiorno, mi scuso per la confusione tra luogo di nascita del coniuge e luogo del matrimonio ma ma vale comunque quanto già detto, il luogo evento di un matrimonio può essere in alternativa un comune italiano oppure uno stato estero con indicazione della località. Pertanto per correggere il luogo del matrimonio inviato al subentro
Provincia: IT  Comune: AMBASCIATA D'ITALIA IN BANGKOK
dovete effettuare una mutazione dati del matrimonio indicando lo stato estero e la località

N. Capozzi
