### ISSUE TITLE
[2001] ws - cancellazione per decesso - errore 999

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1036]
Comune di Bolzano Novarese (NO)  -  Ambiente di produzione

In fase di cancellazione per morte di un residente, tramite ws 2001, viene restituito dal sistema il seguente errore bloccante:
Codice Errore 999 : Operazione non effettuabile 
Effettuando un'interrogazione dello stesso soggetto, tramite ws 3002,  viene invece restituito un errore di sistema "Internal error (from server)"
Il soggetto in questione ha il codice anpr 41265848

Potete verificare il motivo di questi errori?

**Comment by mttfranci** [comment]
Salve, era presente un carattere errato nel nome del coniuge che abbiamo corretto.
Dovrebbe essere possibile riprovare.

**Comment by mttfranci** [comment]
In assenza di riscontro chiudiamo la issue. In caso il problema non sia stato risolto vi preghiamo di riaprirla o di aprirne una nuova
