### ISSUE TITLE
Aggiornamento tabella comuni

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1038]
Sono avvenute alcune fusioni di comuni con decorrenza 1 gennaio 2019
Ad esempio per citarne qualcuno:
San Giorgio di Mantova + Bigarello = San Giorgio Bigarello
Tavarnelle Val di Pesa + Barberino Val d'Elsa = Barberino Tavarnelle
Zambana + Nave San Rocco = Terre d'Adige
Quando sarà disponibile l'aggiornamento della tabella dei comuni?
Grazie
Filipazzi - Maggioli

**Comment by FilippoPapi** [comment]
la tabella è stata aggiornata.
Saluti
