### ISSUE TITLE
 [IdFamigliaConvivenzaANPR] Elenco dei nuclei residenti

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1039]
Sarebbe possibile richiedere, tramite un servizio sincrono (tipo il 3002) o asincrono (tipo il 4001), l'elenco degli **IdFamigliaConvivenzaANPR** gestiti dal comune al momento della richiesta, esclusi quelli cessati o cancellati ? Ovvero, l'elenco degli ID dei nuclei residenti nel Comune al momento della richiesta?

Grazie

**Comment by mttfranci** [comment]
Salve, stiamo valutando se è possibile inserire la richiesta nei prossimi interventi.
Saluti
Assistenza ANPR

**Comment by Eduardo1977** [comment]
Buongiorno, ci sono state novità su questa richiesta?
