### ISSUE TITLE
[5008] - errore completamento dati dopo altro evento anagrafico

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#104]
Pisa, ambiente di test, ID operazione ANPR 456529

Buongiorno, abbiamo verificato che il servizio 5008 non ci permette di fare la mutazione di completamento dati dopo aver eseguito una qualsiasi mutazione anagrafica. Purtroppo questa evenienza succede spesso in quanto, prima del matrimonio, il coniuge sposta la residenza nel nuovo comune e immediatamente dopo si sposa.
E' giusto che non possa aggiornare i dati del matrimonio se ho registrato una mutazione di quel tipo dopo l'iscrizione, però tutti gli altri dati (professione, carta d'identità, dati anagrafici...) dovrebbe permettermi di aggiornarli; cioè il sistema dovrebbe controllare per quale tipo di dato è stato fatto l'evento successivo e inibire solo l'aggiornamento del medesimo tipo di dato.
Allego la request e la response, grazie
Luca Bonini A.P.Systems
[5008Pisa_6213.zip](https://github.com/italia/anpr/files/917182/5008Pisa_6213.zip)

**Comment by gcarbonin** [comment]
Ci stiamo lavorandi

**Comment by gcarbonin** [comment]
In ogni caso Sono state effettuate moltissime operazioni sul soggetto:
in data 06/04/2017  è stata effettuata  l’iscrizione per altri motivi  - 1002;
nella stessa data un 5008 – 20  subito annullato con un 50012 e rifatto subito dopo sempre con la stessa data;
il giorno 12/04/2017 effettuata 3 servizi 5008 tipo mutazione 2 (cittadinanza) e nei giorni successivi invia 3 servizi  5001 tipo mutazione 4 (residenza);
a questo punto invia l’ennesimo completamento che viene bloccato a causa delle mutazioni di cittadinanza effettuate in data 12/04/2017.

**Comment by LucaBonini64** [comment]
Abbiamo rifatto sull'individuo MRRSVN76A03E941O semplicemente l'iscrizione, l'unione civile ed il conseguente cambio di parentela per la persona ed il successivo completamento dati a seguito dell'arrivo dell'APR/4 dall'altro comune ottenendo sempre l'errore EN357: Non è possibile effettuare il completamento del soggetto in quanto sono state effettuate altre mutazioni dei dati anagrafici successive.
Come indicato nella issue registrare un matrimonio o un'unione civile subito dopo l'iscrizione sono eventi che nelle città più grandi (la mia preoccupazione per Genova è ancora maggiore di quella per Pisa) accadono con frequenza e che non è possibile evitare in quanto le norme lo consentono.
Allego il file con tutte le request e response, grazie.
[errore_completamento.zip](https://github.com/italia/anpr/files/1000709/errore_completamento.zip)

**Comment by gcarbonin** [comment]
Stiamo modificando progressivamente i servizi per ragionare non sulla data di ultimo aggiornamento della scheda ma sull'ultimo aggiornamento dello stesso tipo (tipo mutazione) presente nella mutazione di completamento

**Comment by gcarbonin** [comment]
Questa attività si è conclusa: la versione attualmente disponibile in tutti gli ambienti lavora considerando gruppi di dati omogenei tra loro (ad esempio, residenza, dati angrafici ecc.) e controlla la data di decorrenza della mutazione rispetto all'ultima data di aggiornamento del gruppo di dati "mutato". In test comuni e pre-subentro c'è la versione che risolve i problema del titolo di studio in fase di emissione della carta di identità (issue 255).
Se ci sono altre segnalazioni, riapriremo la issue.
