### ISSUE TITLE
[5008] modifica data evento matrimonio non recepita

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1040]
Ambiente di Test

Vogliamo correggere la data evento di matrimonio di un soggetto
Chiamiamo il servizio 5008 con tipo mutazione 12 e tutto pare andare a buon fine, nei dati ritornati con la risposta vediamo al data evento modificata. (id operazione ANPR 18865499 ).
Quando però consultiamo la scheda individuale del soggetto troviamo ancora la data evento precedente la modifica.
Potete verificare ?

Grazie
Gianrico Busa 
Maggioli Spa

**Comment by busaster** [comment]
Buongiorno
ci sono novità in merito a questa issue ?
Grazie

**Comment by asqueglia** [comment]
Chiudiamo l'issue assicurando che il problema  relativo alla consultazione dei dati del matrimonio è stato a suo tempo risolto.
