### ISSUE TITLE
Codici fiscali errati 

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1042]
Ambiente di produzione.
Non ci siamo accorti al subentro di avere alcuni codici fiscali anomali sugli aire e sono stati inviati dei valori con uno spazio all'interno (del codice fiscale).
Esempio id 38095852, 38095923, 38095853, 38095859,38095861.
Questa anomalia ora ci impedisce di operare le cancellazioni che nel frattempo sono pervenute per alcuni di questi individui. 
Impedisce anche la consultazione 3002 per id. Ma impedisce anche la consultazione 3002 a un qualsiasi altro Comune, che ricerchi per cognome e nome identico alle persone che presentano il problema.
Il comune di Macherio mi riferisce di aver già spedito  la pec a Sogei, per chiedere la variazione. Suppongo sia quello il canale corretto da utilizzare in questi casi. 
Potete confermarmelo e verificare per favore di averla ricevuta?

**Comment by cmigliardi** [comment]
Buongiorno, 
al quale casella di pec avete inviato la richiesta ? grazie (me la potete girare?)

**Comment by cmigliardi** [comment]
I cf soggetti sono Aire e nessuno di essi ha mai avuto un CF attribuito da AE. Se non ho la PEC non so quale tipo di variazione  richiede il comune di Macherio. grazie

**Comment by MarcoMigliori** [comment]
Ho già scritto al Comune indicando dove inviare l'email, grazie.

**Comment by cmigliardi** [comment]
Ho ricevuto la email  dal comune di Macherio.   Richiede di inserire cf calcolati localmente.  A seguire la mia risposta:    
Buongiorno, 
per i soggetti interessati AE non ha mai emesso un CF
quindi non possiamo attribuire cf calcolati localmente.  
cordiali saluti
Dott.ssa Migliardi

**Comment by cmigliardi** [comment]
Ciò che è possibile effettuare è  rimuovere il CF inviato con uno spazio all’interno. 
cordiali saluti
Dott.ssa Migliardi

**Comment by cmigliardi** [comment]
attendo indicazioni dal comune che ancora non ha mi ha detto come intende procedere -

**Comment by cmigliardi** [comment]
Buongiorno
nell'invio dei dati di subentro del Comune di Macherio, per i seguenti cittadini aire, è stato erroneamente trasmesso un codice fiscale errato e inesistente in Agenzia Entrate. Se ne richiede la rimozione. Allego elenco individui con il problema
Cordiali Saluti
L’Ufficiale d’Anagrafe del.
Nicolini Pierluigi

ricevuta tale email - chiudo  la issue  ed apro un task per effettuare l'intervento puntuale di rimozione del cf errato e non attribuito da AE.
