### ISSUE TITLE
Errore: Il campo note contiene dei caratteri non validi

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1043]
Buongiorno,
Il Comune di Ragusa per il cittadino IdANPR 41964758 non riesce a fare nessuna mutazione perchè viene restituito l'errore "Il campo note contiene caratteri non validi".
Consultando il Cittadino non si rilevano caratteri "particolari" nelle varie schede presenti.

L'errore è di tipo generico e incomprensibile.

Vista l'urgenza, (si tratta di inserire un rinnovo di permesso di soggiorno), si chiede di conoscere quale sia il campo valorizzato erroneamente e come poter effettuare la relativa rettifica.

Grazie
Giovanni Durante
Kibernetes

**Comment by gdurante72** [comment]
Aggiungo che lo stesso problema si presenta per il Cittadino IdANPR: 41992449

**Comment by gdurante72** [comment]
Adesso funziona.
In casi simili dovete per forza intervenire voi? 
E' possibile capire quale campo genera l'errore?
E possibile intervenire direttamente tramite web-app o ws? e se si come?

Grazie

**Comment by frmariani** [comment]
nel vostro caso c'è stato un piccolo problema che abbiamo risolto proprio ieri;
di solito l'errore si presenta soltanto dalla web app quando da subentro vengono inviate delle informazioni con caratteri non ammessi nei campi note: in questo caso dobbiamo intervenire noi.
