### ISSUE TITLE
[3002] soggetti in convivenza senza legame

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1044]
Ambiente di produzione, comune di Desio

Ricercando con il servizio 3002 la convivenza ID ANPR 16882804 del comune di Milano per alcune persone non viene restituito nel XML di risposta l'attributo "legameSoggetto" (ad es. per i soggetti ID ANPR 29915837 e 29918712 ). Anche consultando uno di questi soggetti da webapp pare che il legame sia mancante.

Però nella issue #1021 si afferma che il codice legame è invece obbligatorio.

La mancanza del dato fa poi fallire alcune logiche del nostro applicativo.
Potete controllare e farci sapere ? 

Grazie

Gianrico Busa
Maggioli Spa

**Comment by azabatta** [comment]
Buongiorno,
stiamo verificando la sua segnalazione.
