### ISSUE TITLE
mancato aggiornamento anagrafe tributaria

### ISSUE THREAD

**Issue by AnnaUrban** [italia/anpr#1045]
Nello scorso mese di giugno abbiamo iscritto una famiglia composta da marito e moglie con un'unica pratica di immigrazione da comune non subentrato.
In data odierna il marito si presenta allo sportello per segnalare che all'anagrafe tributaria la variazione di residenza è stata regolarmente aggiornata per la moglie, mentre lui risulta ancora al precedente indirizzo di residenza. Abbiamo verificato gli archivi ANPR e sembra tutto a posto mentre, effettivamente, in anagrafe tributaria la residenza non è aggiornata. 
Allo sportello dell'Agenzia delle Entrate hanno detto che il comune deve provvedere…. ma non saprei proprio come fare visto che la pratica per noi risulta chiusa regolarmente.
Come possiamo intervenire?

**Comment by rvinzani** [comment]
Potrebbe inviarci gli identificativi ANPR della famiglia o dei soggetti? Grazie

**Comment by AnnaUrban** [comment]
Buongiorno,
il codice ANPR della famiglia è 12729555, mentre il codice del soggetto  la cui variazione non è stata registrata all’agenzia delle entrate è 24353024. Il codice del soggetto presente nella stessa pratica che è stato regolarmente variato all’agenzia delle entrate è 24353025.
Cordiali saluti


[cid:image001.jpg@01D4A8C7.7D594E30]
Anna Urban
Responsabile Servizi Demografici-Informatici-Segreteria
Comune di Serravalle Sesia
tel. 0163459125 int. 3



Da: rvinzani [mailto:notifications@github.com]
Inviato: mercoledì 9 gennaio 2019 18:38
A: italia/anpr <anpr@noreply.github.com>
Cc: AnnaUrban <demografico.serravalle.sesia@reteunitaria.piemonte.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] mancato aggiornamento anagrafe tributaria (#1045)


Potrebbe inviarci gli identificativi ANPR della famiglia o dei soggetti? Grazie

**Comment by AnnaUrban** [comment]
il codice ANPR della famiglia è 12729555, mentre il codice del soggetto  la cui variazione non è stata registrata all’agenzia delle entrate è 24353024. Il codice del soggetto presente nella stessa pratica che è stato regolarmente variato all’agenzia delle entrate è 24353025.

**Comment by rvinzani** [comment]
La variazione di residenza è stata aggiornata in Agenzia Entrate. Saluti.
