### ISSUE TITLE
Comune inesistente alla data di nascita

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1049]
Comune di Villa Cortese 015248
Produzione

Pratica di immigrazione da comune non subentrato (Cotronei).

Il cittadino è nato nel 1930 nel comune di Castelsilano (come da carta di identità e codice fiscale), ma da tabella ANPR il comune di Castelsilano risulta costituito il 28/05/1950 a seguito di richiesta di cambio denominazione da "Casino" a "Castelsilano" (G.U. N. 110 del 13/05/1950).

Come devo procedere per l'iscrizione del cittadino.

**Comment by frmariani** [comment]
In questo caso l'iscrizione per altri motivi deve essere effettuata da WS, con i dati anagrafici a disposizione del Comune: ANPR verificherà la corrispondenza tra il codice catastale presente nel CF (Casino B968) ed il codice catastale corrispondente al luogo di nascita inserito (Castelsilano B968).

Nel caso ci fossero dei problemi mi invii il CF del cittadino alla posta privata:
frmariani@sogei.it

**Comment by cvignati** [comment]
Attendo risposta dalla nostra Software House

**Comment by cvignati** [comment]
@frmariani Comunque sia il CF che la Carta di identità riportano CASTELSILANO.
La denominazione Casino non è presente in nessun documento del cittadino

**Comment by patriziasaggini** [comment]
Il problema è capitato in moltissime altre situazioni, per i Comuni che molto tempo fa hanno avuto cambi di denominazione o di territorio.
La procedura corretta è iscrivere questa persona con la denominazione del Comune di nascita esistente al momento della nascita, che è quello che sarà appunto risultante dal suo atto di nascita originale.
Sul tema c'è anche una [circolare del Ministero dell'Interno dell'Interno - MIACEL del 8/6/1978 n. 8](https://docs.google.com/document/d/1vCtXUTyAniswmievbj49YX0ysdk3sh4CnOC_ABHVq-M/edit), secondo cui l'unico dato che fa fede è il Comune che ha formato l'atto di nascita.
(Quindi il Comune di Casino)

**Comment by cvignati** [comment]
> 
> 
> Il problema è capitato in moltissime altre situazioni, per i Comuni che molto tempo fa hanno avuto cambi di denominazione o di territorio.
> La procedura corretta è iscrivere questa persona con la denominazione del Comune di nascita esistente al momento della nascita, che è quello che sarà appunto risultante dal suo atto di nascita originale.
> Sul tema c'è anche una [circolare del Ministero dell'Interno dell'Interno - MIACEL del 8/6/1978 n. 8](https://docs.google.com/document/d/1vCtXUTyAniswmievbj49YX0ysdk3sh4CnOC_ABHVq-M/edit), secondo cui l'unico dato che fa fede è il Comune che ha formato l'atto di nascita.
> (Quindi il Comune di Casino)

Buongiorno,
se la mia unica possibilità (essendo già comune subentrato in ANPR) è quella di cambiare il comune di nascita al cittadino indicando il comune esistente alla sua nascita (il cittadino ha 89 anni, e dovrò comunicargli il cambio di luogo di nascita), mi chiedo perchè nel subentro in ANPR sia possibile indicare il comune sbagliato.
Se noi comuni già in ANPR siamo obbligati a correggere gli errori fatti da altri, chiedo che non sia permesso il subentro di cittadini con dati non corretti (comune di nascita in primis).

Resto in attesa di una risoluzione, in quanto non mi sembra corretto che ci sia disparità di controlli tra chi subentra e chi è già subentrato.
Ripeto, come si può spiegare ad un cittadino di quasi 90 anni che gli cambio il luogo di nascita.

Grazie

**Comment by frmariani** [comment]
per preservare il CF di cittadini così anziani, interpretiamo il codice catastale presente nel CF con la descrizione del comune inviata nell’oggetto “Comune di nascita” e non emettiamo alcun errore.
 
@cvignati  le ho risposto in privato

**Comment by frmariani** [comment]
La pratica di immigrazione del cittadino nato a Castelsilano è andata a buon fine
