### ISSUE TITLE
ANPR e CIE

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#105]
Buongiorno,
visto il piano di dispiegamento della nuova CIE vorremmo sapere se, quando avverrà l'integrazione del sistema CIE con l'ANPR, avete previsto una notifica per l'aggiornamento della base dati comunale.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
E' previsto l'aggiornamento di ANPR dal sistema CieOnline. Non è prevista la notifica in quanto non sembra siano dati da mantenere a livello locale

**Comment by LucaBonini64** [comment]
Se questa è l'indicazione trasmetteremo ai nostri comuni, però vuol dire che le informative su questi dati (da qualsiasi parte arrivino) dovranno avvenire tramite il sistema centrale. 
Per quanto riguarda i Comuni l'utilità è nel precompilare i form delle dichiarazioni sostitutive di notorietà o delle autentiche che vengono fatte allo sportello, ed in assenza dei dati l'impiegato dovrà riscriversi i dati tutte le volte.
Per il servizio elettorale invece i dati delle carte d'identità servono a eseguire controlli (normalmente a campione) sulle sottoscrizioni elettorali effettuate in occasione della presentazione delle liste.
Cordiali Saluti.

**Comment by gcarbonin** [comment]
Tutti i dati che servono si ottengono da CieOnline o interrogando ANPR....
