### ISSUE TITLE
Campo non ammesso nella denominazione di una convivenza

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1051]
Buongiorno,
il Comune di Marsala ha la convivenza IdANPR 24909201 - IdComune  9933064 (Istat Comune 081011) con un carattere non ammesso nella descrizione e per la precisione  "°".
A causa di tale problema non è possibile inserire il responsabile della convivenza non residente e pertanto non si riescono ad avviare altre mutazione.

Si chiede di eliminare tale carattere e sostituirlo con lo spazio.

Grazie 

Giovanni Durante
Kibernetes

**Comment by gdurante72** [comment]
OK
Attendiamo la bonifica massiva

**Comment by rvinzani** [comment]
OK, chiudo la issue. In caso di problemi è possibile aprirne un'altra che faccia riferimento a questa tessa.
