### ISSUE TITLE
Tabella Comuni non aggiornata in ambiente di test

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1053]
Ho visto che in ambiente di test non è ancora stata aggiornata la tabella dei comuni alla nuova versione dell'8 gennaio. E' possibile disporre di questo aggiornamento? Grazie.
Filipazzi - Maggioli

**Comment by amollicone1982** [comment]
L'aggiornamento in ambiente di test verrà effettuato tra pochi giorni
