### ISSUE TITLE
Errore EN 187 - soggetto già iscritto o deceduto

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1054]
Il Comune di Marsala non riesce a fare una pratica di mutazione di residenza del Cittadino IdANPR 41898663  proveniente dal Comune di Mazara del Vallo.

in fase di conferma preliminare viene restituito l'errore EN 187 - il Soggetto è già iscritto o deceduto, ma il soggetto non è mai stato residente a Marsala e consultando la scheda tramite web-app non risultano procedimenti in corso.

Stessa situazione per il cittadino ID ANPR 41924011 sempre proveniente da Mazara del Vallo

Giovanni Durante
Kibernetes

**Comment by frmariani** [comment]
la mutazione di residenza prevede l'invio del servizio 5005, mentre per i soggetti indicati state inviando il servizio di iscrizione per altri motivi (1002);

**Comment by gdurante72** [comment]
Grazie
