### ISSUE TITLE
ERRORE NELLA CERTIFICAZIONE

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1055]
Non riusciamo a stampare certificato di residenza per il cittadino codice Anpr 43387493.
L'errore è il seguente: 
Il soggetto risulta iscritto anche nel comune di 023091 Con data iscrizione 11/04/2013 (Codice: EN469)

**Comment by rnapoli1983** [comment]
Buongiorno dovremmo aver risolto il problema.

Potete riprovare quando vi è possibile ?

**Comment by Finalmentesubentrati** [comment]
Ora va. Grazie

**Comment by rnapoli1983** [comment]
Chiudo la issue e rimaniamo a disposizione per qualsiasi chiarimento.
