### ISSUE TITLE
[5001] EN416 in ripristino residenza ante subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1057]
Ambiente di produzione, comune di Oristano subentrato il 18/12/18.

Il comune vuole annullare un cambio indirizzo effettuato il 12/11/18 ripristinando la precedente residenza a decorrere dal 28/10/2018,
Per fare questo invochiamo il servizio 5001 con tipoMutazione 6.
Otteniamo però l'errore "L'operazione di ripristino residenza e' consentita soltanto a valle del subentro". (id operazione ANPR 45083054).
Come mai ?

Grazie 

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
C'è stato un problema nel servizio, ma ora la situazione è stata ripristinata.

Potete riprovare per favore ?

**Comment by busaster** [comment]
Riprovato, il problema è stato risolto.
Chiudo
Grazie
