### ISSUE TITLE
Internal error (from server)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1058]
Segnalo che a seguito della richiesta in ambiente di produzione così identificata:

idOperazioneComune JD87949
codMittente 087015
operazioneRichiesta 6001

ANPR ha risposto con "Internal error (from server)"

Comune di Catania

Filipazzi - Maggioli

**Comment by mttfranci** [comment]
E' possibile che il problema sia legato all'aggiornamento software di oggi alle 14.00 annunciato la settimana scorsa #1050 .
Potete riprovare? Se il problema si presenta nuovamente potreste fornirci nuovamente i dati sulla richiesta e l'idsoggetto?
Grazie in anticipo.

**Comment by bfilipazzi** [comment]
Il problema si è verificato prima delle 14:00.
dataOraRichiesta 2019-01-14T11:59:11.000+01:00
idSchedaSoggettoANPR 33960040
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Lato server ANPR l'operazione è stata completata con successo e il certificato è stato emesso con ID operazione ANPR 45103725 e sia la richiesta che la risposta sembrano valide.
Possiamo ripetere l'operazione per verificare che non ci sia stato qualche problema temporaneo sulla rete o sui sistemi perimetrali (ma in questo caso verrebbe emesso un secondo certificato).
Alternativamente potete ottenere la risposta del servizio di certificazione tramite il servizio di gestione richieste 3003, per singola richiesta con id operazione 45103725.

Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
In assenza di riscontro chiudiamo la issue. In caso il problema non sia stato risolto vi preghiamo di riaprirla o di aprirne una nuova
