### ISSUE TITLE
Luogo estero con stato ITALIA

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1059]
-Ambiente di produzione
Comune di Montalcino

idOperazioneANPR 45027944
operazioneRichiesta 3002

Il comune di Montalcino consulta i dati di un soggetto per avviare una mutazione di residenza dal comune di attuale abitazione. L'XML di risposta contiene i seguenti dati nella sezione del matrimonio:

luogoEvento
descrizioneLocalita SAN GIOVANNI D'ASSO
descrizioneStato ITALIA
codiceStato 100

San Giovanni d'Asso è stato un comune della provincia di Siena dal 1877 al 2016, e in questo caso è codificato come una città estera con stato Italia.
Questa forma inattesa di registrazione del dato blocca il gestionale e il comune di Montalcino non ha strumenti per bonificare il dato prima di far sua l'anagrafica.
C'è qualche strada percorribile per gestire il caso?

Grazie.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
anche se il comune non è più attivo, il dato doveva essere inviato da subentro con la giusta provincia e codice istat, e non con stato Italia;

Il comune di Mori deve effettuare una mutazione dei dati del matrimonio, pertanto fatemi sapere se devo contattare io il Comune o ci pensate voi.

**Comment by bfilipazzi** [comment]
Forse il vostro intervento diretto potrebbe risultare più "autorevole".
Grazie.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
vi farò sapere

**Comment by frmariani** [comment]
Il comune di Mori effettuerà la modifica necessaria e contatterà il Comune di Montalcino.

**Comment by bfilipazzi** [comment]
Grazie mille.
Filipazzi - Maggioli
