### ISSUE TITLE
Certificati PR

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#106]
Secondo quanto indicato dalla Circolare 12/2016, i soggetti a Protocollo Riservato non dovranno essere subentrati, pertanto i certificati per questi soggetto dovranno essere emessi dal proprio gestionale: questo renderà ben visibile, a terzi, la differenza tra soggetti subentrati, per i quali il certificato viene prodotto da ANPR, ed i soggetti non subentrati, per i quali il certificato sarà prodotto dal gestionale. 
Il Dipartimento della Pubblica Sicurezza del Ministero dell'Interno è consapevole che questa modalità operativa renderà evidente la differenza tra soggetti? 
Grazie 
Giannone, Amprimo, Floramo, Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Non saprei. Non ho informazioni al riguardo come Sogei.
