### ISSUE TITLE
[A001] Iscrizione AIRE: Errore EAA0A

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1061]
ambiente di PRODUZIONE - comune di OCCHIOBELLO (RO)

iscrizione AIRE (ws A001), con idOperazioneComune 2019000244 ritorna questo errore:
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EAA0A</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia/>
  </errore>
</listaErrori>
```

come sbloccare?
grazie.

Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera,
l'errore era dovuto alla presenza di caratteri non più ammessi nell'indirizzo della famiglie alla quale viene associato il bambino.
In vista delle attività di bonifica generale previste per l'11/2 e comunicate con issue 1060, tali caratteri sono stati rimossi per la famiglia indicata al fine di consentire l'iscrizione.  Potete riprovare

N. Capozzi
