### ISSUE TITLE
[3002] Internal Error (from server)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1062]
ambiente di PRODUZIONE - comune di OCCHIOBELLO (RO)

idOperazioneComune 2019300179, delle 16:49 di oggi 14/1

il web service restituisce l'errore:
```
<env:Fault>
  <faultcode>env:Server</faultcode>
  <faultstring>Internal Error (from server)</faultstring>
</env:Fault>
```

Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Nel toponimo estero è presente il carattere '^' che non è ammesso.
E' prevista una bonifica massiva #1060. Se lo ritenete possiamo rimuovere tale carattere.

**Comment by mttfranci** [comment]
In assenza di riscontro chiudiamo la issue. In caso il problema non sia stato risolto vi preghiamo di riaprirla o di aprirne una nuova
