### ISSUE TITLE
Errore dati di subentro

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1063]
Buongiorno,
il Comune di Ragusa per il Cittadino IdANPR 41979876 ha inoltrato in fase di subentro il matrimonio con il cittadino IdANPR 41974013 e la vedovanza che si riferisce ad un altro cittadino con cui si era risposata.

Provando a mutare i dati di matrimonio in rettifica inserendo i riferimenti all'ultimo matrimonio a cui si riferisce la vedovanza viene restituito l'Errore EN289: La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto.

Vorremmo sapere come aggiornare i dati di matrimonio in modo da inserire quelli a cui si riferisce la vedovanza o come eliminare la vedovanza per poter inserire il divorzio del primo matrimonio, il secondo matrimonio e la vedovanza.

Cordiali Saluti
Giovanni Durante
Kibernetes

**Comment by gdurante72** [comment]
Al momento per il cittadino interessato esiste una operazione sospesa ID18121621 per la rettifica dei dati di matrimonio

**Comment by gdurante72** [comment]
Si richiede un sollecito
Ad oggi non si riesce a bloccare il cittadino

Grazie

**Comment by frmariani** [comment]
la riconciliazione post subentro non è andata a buon fine in quanto avete inserito dei dati non corretti (la data morte della moglie), pertanto consiglio le seguenti operazioni nella sequenza riportata:
1) eliminare l'operazione sospesa (Registrazione> Mutazione tutti i dati> Elenco operazioni sospese);
2)riconciliare il matrimonio tra i due soggetti ANPR;
3)acquisire  il divorzio tra i due inserendo anche l'oggetto matrimonio a cui il divorzio si riferisce ;
4)acquisire il secondo matrimonio;
5)acquisire la vedovanza inserendo anche l'oggetto matrimonio a cui la vedovanza si riferisce.

nel caso ci fossero dei problemi potete scrivermi in privato
frmariani@sogei.it
