### ISSUE TITLE
[WEBAPP] Consultazione scheda individuale dopo modifiche 3002

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1064]
Ieri stavo facendo formazione (ambiente presubentro) e ci siamo accorti aprendo la webapp "Consultazione scheda individuale" nel nostro caso di un cancellato, che ora mostra pochissimi pannelli nel "menù" di sinistra, senza la possibilità di vedere "Dati Iscrizione", "Dati Cancellazione", ecc.. 
Immagino per la recente modifica del servizio 3002. Ritengo sia da correggere e per questo motivo ve la segnalo.

**Comment by mttfranci** [comment]
Potreste farci sapere quali criteri di ricerca avete usato?
Se la ricerca era puntuale per un singolo soggetto allora protrebbe essere un bug.
Invece se la consultazione ha restituito più soggetti (ad esempio perchè è stata eseguita una interrogazione per famiglia o per nome e cognome) il risultato è corretto.
La versione 5 di ANPR recentemente pubblicata restituisce solo i dati essenziali quando una ricerca produce più risultati, come indicato nell'avviso #1031.
Come descritto, tale caratteristica è guidata dal parametro codDestintario = ANPR02 tramesso dal client in testata.
Le software house hanno 90 giorni per adeguarsi a tale comportamento (https://github.com/italia/anpr/blob/master/src/change-management/change-management.md).
L'applicazione web, essendo il client nativo di ANPR si è già adeguata alla nuova versione.

**Comment by MarcoMigliori** [comment]
ricerca  per cognome e nome. 
restituisce 3 soggetti (nel mio caso), di cui quello di nostro interesse è cancellato.
clicco sul nostro soggetto e appaiono i suoi dati nella web app, incompleti perchè mancanti tra gli altri di iscrizione e cancellazione.
visto che hanno aperto consultazione scheda individuale, dubito che il risultato sia corretto.

**Comment by mttfranci** [comment]
Come detto, stiamo valutando degli interventi per rendere più fruibile la consultazione.
Ma l'applicazione si comporta in modo coerente a quanto dichiarato nell'avviso #1031.
Per avere i dati completi è possibile eseguire una consultazione specifica per id anpr o codice fiscale.

**Comment by AMonopoliADS** [comment]
penso che il collega @MarcoMigliori intenda rilevare che, in presenza di più soggetti restituiti dalla ricerca, non è possibile riconoscere se i soggetti sono iscritti o cancellati da ANPR.
a mio parere, è tra le cose da ripristinare prima di rendere definitiva la nuova modalità.
grazie.
Alessandro Monopoli ADS

**Comment by ANPRCdMI** [comment]
Buongiorno
mi unisco alle richieste dei colleghi espresse sopra. 
Capiamo che l'intervento è necessario, ma ci sarebbero alcune soluzioni alternative che possono ottenere gli stessi risultati di ottimizzazione,  minimizzando tuttavia gli interventi alle applicazioni già consolidate:
- non gestire la risposta ridotta (sole generalità)  in caso di lettura per numero famiglia (non convivenza , solo famiglia) o codice fiscale  
- eliminare la possibilità di richiedere la "scheda individuale completa", e permettere l'estrazione di un numero massimo di oggetti contemporaneamente
- gestire la lettura per cognome/nome e la relativa risposta ridotta con un servizio diverso dal 3002.
grazie
Raffaella Tremolada
Sistemi Informativi s.r.l.

**Comment by MarcoMigliori** [comment]
Rispondo solo per chiarire la segnalazione, ma ovviamente la decisione se modificare o meno è vostra.
Nel recente avviso ci avete spiegato come funziona la chiamata 3002, e questo è chiaro.

La segnalazione è diretta alla web application, prodotto di Sogei, differente dai web service.
L'operatore che utilizza la web application, ha cliccato su "consultazione scheda individuale" perchè ha bisogno di vedere le informazioni del cittadino.
Se cerca per codice fiscale vede tutto quello che gli serve.
Secondo voi, qualora ricerchi per cognome e nome, dovrebbe fare la ricerca, selezionare il nome giusto dall'elenco degli omonimi, arrivare sulla scheda generalità, copiare l'id anpr oppure il codice fiscale, tornare alla videata di ricerca, incollare il parametro giusto e finalmente vedere i dati che gli servono.
Secondo me la web application una volta mostrato l'elenco degli omonimi, quando l'operatore clicca sul nome che desidera vedere deve fare una ulteriore chiamata 3002 per id trasparente all'operatore e quindi mostrare la videata completa.

Avendo voi modificato la 3002, sui nostri applicativi ci troveremo a dover fare una modifica similare. 
Solo il mio parere perchè mi sembra più pratico modificare un programma, piuttosto che avvisare - quanti? 50mila operatori? - di lavorare nell'altro modo.

Il comune di Milano ha avuto occasione ieri nella riunione di precisare la sua richiesta.
Concordo con @AMonopoliADS nel merito della chiamata ws 3002, ma preferisco aprire una nuova issue perchè questa è solo una segnalazione sulla web application, per me chiusa. A voi la valutazione.

**Comment by mttfranci** [comment]
Per quanto riguarda la fruibilità della web application, come detto, stiamo valutando degli interventi di miglioramento.

Per quanto riguarda le richieste sulla consultazione 3002 abbiamo pubblicato la patch 5.0.1 : https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

Che in sintesi accoglie le seguenti richieste riguardo la nuova versione 5.0/ANPR02

Nella ricerca per codice fiscale e per id famiglia (ma non convivenza) la risposta è sempre completa.
Nella risposta sintetica viene fornita la sezione dei datiCancellazione, se presente (da notare che però non vengono fornite le sezioni dei datiIscrizioni e datiDecesso oltre a tutte le altre non attualmente previste per la risposta sintetica).
Saluti

Assistenza ANPR
