### ISSUE TITLE
[Testata Richiesta] Supporto agli UUIDv4

### ISSUE THREAD

**Issue by marcoalbarelli** [italia/anpr#1065]
Salve, con riferimento alla #814 vorrei sapere se sia nei piani di supportare gli uuidv4, che risolverebbero la questione una volta per tutte

Al momento il campo è marcato come charMax30, mentre uno uuidv4 è lungo 36 (32 omettendo i caratteri `-`)

Poterlo usare sarebbe ottimo non solo per le proprietà anti collisione, ma anche perché molti usano degli uuidv4 come chiavi primarie.

**Comment by mttfranci** [comment]
Stiamo valutando la vostra richiesta.
Saluti
Assistenza ANPR

**Comment by mttfranci** [comment]
Al momento questa proposta non è stata inclusa nella nostra road map.
