### ISSUE TITLE
[Testata Richiesta] Caratteri non validi

### ISSUE THREAD

**Issue by marcoalbarelli** [italia/anpr#1066]
Salve
Ho notato che alcuni campi nella testataRichiesta portano ad un errore se contengono caratteri che sono però validi:
Nello specifico ho notato che quello che mappa su charMax80 porta a errori se contiene 
* `_`
* `@`
* `è`

Sostanzialmente pare che `charMax80` accetti solo un subset dell'ASCII
Ho cercato nella documentazione, ma non ho trovato riscontri. 
È un bug o un comportamento atteso?

**Comment by mttfranci** [comment]
Il tipo charMax80 non è più definitivamente accettato nella testata della richiesta in nessun ambiente dal 5 novembre 2018. Potete fare riferimento agli avvisi #819 e #775 e #617.
La versione correntemente pubblicata degli XSD (https://www.anpr.interno.it/portale/documentazione-tecnica) riporta tutte le regole aggiornate.
Se può esservi di aiuto mettiamo a disposizione anche un esempio di validazione della richiesta/risposta che utilizza tali XSD. Lo potete ottenere dall'ambiente di test comuni, area strumenti di supporto.
Cordiali saluti
Assistenza ANPR

![image](https://user-images.githubusercontent.com/29305782/51250537-f3f1a700-1996-11e9-93fe-949eb02bc5cc.png)
