### ISSUE TITLE
Anomalia soggetto doppio ma in ANPR c'è un unica occorrenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1067]
Ambiente di produzione, comune di Ardea.

Il soggetto id ANPR 40556675 , ora residente a Perugia,  risulta avere l'anomalia "Il soggetto con id anpr 40556675 risulta iscritto anche nel comune di ARDEA (RM) Con data iscrizione 17/03/2006".
Non riusciamo però, né ricercando per CF né ricercando per cognome/nome/data nascita a trovare il soggetto doppio.
Potete aiutarci a capire la situazione ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by rvinzani** [comment]
Il soggetto è stato iscritto prima da Ardea e successivamente annullata l'iscrizione. Poi Ardea ha preso in carico la scheda del soggetto residente a Perugia.
Attualmente quindi il soggetto è presente con una sola scheda aperta in ANPR. La segnalazione verrà rimossa.

**Comment by busaster** [comment]
perfetto grazie
