### ISSUE TITLE
Errore 500 su mutazione di residenza

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1068]
Il Comune di Marsala nel tentativo di fare una mutazione di residenza del Cittadini IdANPR 35411446 residente a Trapani, in fase di conferma preliminare riceve l'errore 500: Errore interno del Server.

Cordiali Saluti

Giovanni Durante
Kibernetes

**Comment by mttfranci** [comment]
Da una prima analisi non troviamo l'operazione.
In questi casi spesso c'è qualche problema nella validazione della richiesta che viene bloccata dai sistemi perimetrali.

In tal senso è sempre utile specificare quante più possivili delle seguenti informazioni : 
- data e ora dell'operazione
- tipo di operazione
- Quanto l'errore è 500 Internal server error, spesso si trova anche la dicitura (from server) o (from client)
- idOperazioneComune
- comune mittente (ci pare di capire Marsala)
- Se disponibile l'id operazione ANPR ottenuta nella risposta (ma non è questo il caso).



Vi consigliamo in prima analisi di provare la validazione della richiesta XML che inviate (c'è un tool di esempio nell'area strumenti di supporto dell'ambiente di test comuni )
![image](https://user-images.githubusercontent.com/29305782/51249908-27cbcd00-1995-11e9-9a15-53539c500981.png)

Se nessuna delle altre verifiche avrà esito positivo potremmo avere necessità di visionare la richiesta completa.
Grazie in anticipo.

**Comment by gdurante72** [comment]
OK
Trovato l'errore, il Comune di provenienza non ha valorizzato la località di nascita

Grazie

**Comment by mttfranci** [comment]
Prego
