### ISSUE TITLE
[1002] operazione non effettuabile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1069]
Ambiente di produzione, comune di Gambellara.

Tentando di iscrivere un soggetto per ripristino posizione precedente ci viene restituito l'errore "AEE97 : Operazione non effettuabile". (id op. ANPR 45568661).
Qual è il motivo ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
potete riprovare per favore ?
