### ISSUE TITLE
Emigrazione PR

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#107]
Quando un soggetto Protocollo Riservato esce dal programma di protezione richiede emigrazione verso il comune di effettiva residenza.
Al fine di preservare ulteriormente la riservatezza della notizia del nuovo comune di iscrizione, su richiesta del Polo Fittizio, si mantengono i soggetti nel protocollo riservato.
Con ANPR come sarà gestita l'iscrizione del soggetto nel nuovo comune? Con iscrizione da comune non subentrato?(finchè ci saranno comuni non subentrati..)
Tutte le richieste di certificazione storica che pervengono, possono essere evase solo previa autorizzazione del Polo Fittizio.
Il Dipartimento della Pubblica Sicurezza del Ministero dell'Interno è a conoscenza di queste modalità operative?

**Comment by gcarbonin** [comment]
Immagino sia una iscrizione da comune non subentrato o una iscrizione per altri motivi, anche se stiamo entrando nell'ambito di disposizioni amministrative che non sta a un tecnico definire. Sulla seconda domanda, vale la risposta precedente.
