### ISSUE TITLE
[5012] rigetto di mutazione residenza e famiglia alterata

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1070]
Ambiente di test, comune di Poggio a Caiano.
Caso analogo ad uno rilevato sul db di produzione di Palma di Montechiaro.

Un soggetto (figlio) esce da una famiglia di 4 persone per formare nel comune di lavoro un nuovo nucleo famigliare con decorrenza 05/01/2019.  (id op. ANPR 18890154)
Dalla stessa famiglia, con decorrenza 06/01/2019 viene cancellata una seconda persona (figlia) per emigrazione in comune non subentrato (id op.  ANPR 18890209)
Il 14/1/19 falliscono gli accertamenti per il cambio di residenza del 5/1 per cui si tenta di rigettare l'operazione con una chiamata al servizio 5012 che però restituisce l'errore "EN077 L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa" (id op. ANPR 18890220).

Annullando la cancellazione si sblocca  la situazione e si riesce ad annullare la mutazione residenza.

Mi pare una procedura difficile da far digerire agli operatori anagrafici, che comporta l'esecuzione di ulteriori chiamate di annullamento col rischio di imbattersi in movimenti non annullabili.

Secondo me si dovrebbe rimuovere il blocco sull'annullamento 5012 in questa situazione.

Grazie

Gianrico Busa
Maggioli Spa

**Comment by rvinzani** [comment]
Ieri abbiamo portato in test comuni/presubentro una versione degli annullamenti che dovrebbe superare questi limiti. Abbiamo eseguiti vari test di verifica ma ci sarebbe molto utile, poichè le casistiche sono tantissime, che riusciste a riprodurre il vostro caso in tale ambiente per verificare che in effetti il problema sia risolto da tale versione. Grazie

**Comment by busaster** [comment]
vi confermo che con la versione attualmente in test il caso oggetto di questa issue viene processato correttamente

**Comment by rvinzani** [comment]
Perfetto! :+1:

**Comment by rvinzani** [comment]
Posso chiudere la issue? La versione dovrebbe a breve andare in produzione

**Comment by busaster** [comment]
direi di sì
grazie
