### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1072]
Comune di Marino - Produzione

Internal error (from server) a seguito della seguente richiesta:

Operazione Richiesta: 5012
idOperazioneComune: JD35073
codMittente: 058057 

Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Salve, l'operazione è andata a buon fine e ha id operazione anpr 13075115.
Purtroppo per la struttura del servizio 5012, nel restituire lo stato attuale del soggetto c'è stato un carattere bloccato dai nostri servizi perimetrali.

Nella lettera è presente il carattere '/' che non è ammesso : 
 <lettera>I/3</lettera>
E' prevista una bonifica massiva #1060. Se lo ritenete possiamo rimuovere tale carattere subito.
