### ISSUE TITLE
Il campo Motivo contiene dei caratteri non validi

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1073]
Non riusciamo a  registrare un divorzio.
 Dalla web app abbiamo l'errore  "Il campo Motivo contiene dei caratteri non validi".
 Codice individuale ANPR 18875542
In un precedente ticket mi era stata evidenziata la presenza dei due punti all'interno del campo censimento, che danno fastidio alla "mutazione tutti i dati" senza illustrami come eliminare questi segni.

**Comment by cmigliardi** [comment]
Buonasera, abbiamo provveduto a rimuovere il carattere ":"   - può riprovare ? grazie

**Comment by Finalmentesubentrati** [comment]
Riprovato ma sempre errore anche perché i due punti nel campo censimento ci sono ancora.

**Comment by cmigliardi** [comment]
i :  sono stati tutti rimossi- questa la stringa -
Motivo compilazione:  Censimento 2011 - Dati Forniti da SGR - Codice Questionario 0720040009793 Tipo W Sezione Censimento 90  
mi puo' inviare la stringa che vede lei? grazie

**Comment by Finalmentesubentrati** [comment]
Mi scusi le avevo fornito un codice anpr dell'individuo errato. Il codice
ANPR dell'individuo è questo

18903882 Pellegrino Maria 21/10/1972

Il giorno ven 18 gen 2019 alle ore 08:59 cmigliardi <
notifications@github.com> ha scritto:

**Comment by cmigliardi** [comment]
abbiamo ripulito dai :  anche questo id soggetto anpr    "  Censimento 2011 - Dati Forniti da SGR - Codice Questionario 0720040021887 Tipo C Sezione Censimento 306   "  può riprovare ? grazie

**Comment by Finalmentesubentrati** [comment]
ok, risolto grazie

Il giorno ven 18 gen 2019 alle ore 09:52 cmigliardi <
notifications@github.com> ha scritto:

**Comment by Finalmentesubentrati** [comment]
Ok risolto. grazie
