### ISSUE TITLE
[5001] da Comune Subentrato: flag Presenza Coabitante

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1074]
ambiente di PRODUZIONE - comune di FAENZA (RA)

la famiglia con idANPR 9406013 viene iscritta a Faenza con provenienza Bagnacavallo.
a Bagnacavallo la famiglia aveva il flag "presenzaFamigliaCoabitante" attivo.

con l'iscrizione a Faenza (ws 5001 - idOperazioneComune 2018029393) è stato comunicato quanto segue:
```
<famigliaConvivenza>
  <idFamigliaConvivenzaANPR>9406013</idFamigliaConvivenzaANPR>
  <dataOrigineFamigliaConvivenza>2018-12-20</dataOrigineFamigliaConvivenza>
  <presenzaFamigliaCoabitante>N</presenzaFamigliaCoabitante>
  <tipoScheda>3</tipoScheda>
</famigliaConvivenza>
```

ma il soggetto ha mantenuto il flag attivo.
potete verificare?

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, per modificare l'attributo presenzaFamigliaCoabitante, è disponibile il servizio di mutazione famiglia/convivenza con tipo mutazione 'motivo famiglia/Specie convivenza'  (servizio 5001 tipo mutazione 3).

**Comment by asqueglia** [comment]
Buongiorno, non sono previste al momento evoluzioni di questo genere. I servizi sono stati pensati e progettati per effettuare operazioni atomiche; l'orchestrazione dei servizi è a carico del gestionale che li invoca. In maniera congruente si comporta anche l'applicazione WEB.

**Comment by AMonopoliADS** [comment]
ho l'impressione che non stiamo guardando la stessa famiglia...
la consultazione sul soggetto (ws 3002 - idOperazioneComune 2019301023 di pochi minuti fa) continua a restituirmi una 'S' nel tag presenzaFamigliaCoabitante. mentre dovrebbe essere 'N'.
l'idANPR della famiglia è 9406013

**Comment by AMonopoliADS** [comment]
ho inviato nuovamente la 5001 di annullamento del flag è adesso è andato a buon fine

**Comment by asqueglia** [comment]
Si esattamente c'è stata un po' di confusione. Il 5001 a cui lei si è riferito prima (ws 5001, con tipoMutazione '3' rif. idOperazioneComune 2019001824), fa riferimento alla famiglia con idANPR 12258926 e come le ho confermato, l'operazione è andata a buon fine e la consultazione ritorna quanto desiderato. La famiglia che ha appena comunicato, invece, con idAnpr 9406013, è stata aggiornata (con coabitazione N) soltanto poco fa alle ore 9:58, quindi dopo la consultazione cui lei si riferisce (ws 3002 - idOperazioneComune 2019301023) effettuata alle ore 9:32

**Comment by asqueglia** [comment]
Comunque sia comunichiamo che abbiamo previsto un intervento per rivedere il servizio di consultazione famiglia/convivenza  e per mostrare nell’elenco operazioni anche quelle effettuate sulla famiglia.

**Comment by AMonopoliADS** [comment]
è sicuramente un buona cosa 
x maggiore trasparenza e immediatezza, l'ideale sarebbe potere vedere le operazioni sulla famiglia sui singoli soggetti collegati.
attendo l'eveluzione.

grazie

**Comment by asqueglia** [comment]
Chiudo l'issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova facendo riferimento a questa stessa
