### ISSUE TITLE
Note rilascio minor version 5.1.0 ANPR

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#1077]
Sono stati aggiornati [Roadmap](https://github.com/italia/anpr/blob/master/src/change-management/roadmap.md) e [Changelog](https://github.com/italia/anpr/blob/master/src/change-management/changelog.md)

WSDL dei servizi 3000 aggiornati : [wsdl3000-dist-5.1.zip](https://github.com/italia/anpr/files/2769664/wsdl3000-dist-5.1.zip)

Ecco una breve sintesi degli interventi rilasciati oggi negli ambienti di test comuni / presubentro (consultare la roadmap per la data prevista di rilascio in produzione)

1) (Requirement) Sezione famiglia risposta 3002 (solo ANPR02)
    + Solo nella interrogazione per famiglia/convivenza con codDestintario ANPR02 viene restituito un blocco esplicito opzionale della famiglia.

2) (Requirement) Avvisi nella risposta del 3002 (solo ANPR02)
    + Solo in caso di chamata con codDestintario ANPR02 viene aggiunta una sezione di anomalie anche in caso di risposta OK del servizio 3002.

Vengono aggiunti due nuovi campi opzionali nella risposta del 3002 che si attivano solo con il codice ANPR02 e sono retrocompatibili secondo le regole concordate : 
- Sezione famiglia separata quando c’è una ricerca per famiglia / convivenza (il 3002 ha il limite di poter fornire i dati della famiglia solo all’interno di un soggetto, questo ha creato problemi anche al momento di gestire ad esempio le convivenze senza soggetti e responsabile da subentro).
- Sezione anomalie generico della risposta (al momento il 3002 prevede di poter restituire anomalie solo all’interno dei soggetto in caso di risposta OK, errori che riguardano tutto l’operazione possono essere restituiti solo qualora la risposta sia KO).

NOTA : trattandosi di campi opzionali aggiunti, entrambe le modifiche sono da considerarsi retrocompatibili.
 
![image](https://user-images.githubusercontent.com/29305782/51333699-99cc1100-1a7e-11e9-867b-212a568b9c61.png)

3) (Requirement) Scarico massivo dei dati di un comune
    + Consente di scaricare i dati di un comune da ANPR al solo scopo di utilizzarli nel caso di cambio gestionale comunale. Tale soluzione provvisoria prevede la generazione di una fornitura di tutti i soggetti di un Comune sotto forma di file compresso, che verrà consegnato al Comune tramite PEC.  

Dettaglio : Al momento la richiesta non è automatizzata ed è prevista solo in casi di cambio fornitore software. L’output dello scarico equivale a quello del servizio di consultazione (3002) ripetuto per tutti i soggetti residenti nel comune al momento della produzione (tra le altre informazioni contenute, nella testata della fornitura è presente il timestamp dell’estrazione).

4) (Requirement) Web - Amministrazione gestione ip
    + Nel menù Amministrazione - gestione dati comune aggiunta la possibilità di inserire, dismettere, riabilitare uno o più indirizzi IP da far abilitare per l'utilizzo dei servizi ANPR

5) (Requirement) Estensione del servizio revoca dato
    + Estensione del servizio revoca dato per i seguenti dati: - Matrimonio / Convivenza / Unione civile - Permesso di soggiorno - Carta di identità - Atto di nascita

6) (Requirement) Superamento vincoli annullamento
    + E' stato reso possibile effettuare annullamenti per ripristino posizione anagrafica anche se la mutazione di residenza non è l’ultima operazione effettuata sul soggetto (ma non vi siano altre mutazioni di residenza) Sono stati eliminati i vincoli sugli annullamenti impediti da operazioni su soggetti collegati (es. coniugi o legami parentela)

**Comment by busaster** [comment]
Provando a fare in ambiente di test una ricerca famiglia/convivenza con il servizio 3002 mi aspettavo di vedere valorizzato il nuovo tag opzionale "datiFamigliaConvivenza" nella risposta, ma non è così.
Id operazione ANPR ricerca famiglia = 19023412
Id operazione ANPR ricerca convivenza = 19023397 (convivenza vuota con responsabile)

Per caso questo nuovo tag viene restituito solo in caso di ricerca di convivenze vuote prive di responsabile ?

**Comment by MoniaPedrazzoli** [comment]
Buongiorno,

WA ambiente di TEST Pisa
data 2019-04-11 13:12:23 , idOperazioneANPR 19129771 (Codice: EN527)

provando la revoca della sezione matrimonio viene restituito l'errore seguente:
L'operazione di revoca e' possibile solo a valle del subentro (Codice: EN505)

La persona è vedova e con il subentro sono state inviate informazioni errate nel matrimonio che vorrei eliminare.  

Potete dirmi se è possibile ottenere questo risultato?

Grazie
Monia Pedrazzoli
APKAPPA
