### ISSUE TITLE
Recupero operazione da webapp con dati errati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1078]
Ambiente di test

Dalla webapp abbiamo modificato le generalità di un soggetto privo di CF validato chiedendo l'attribuzione di un CF. Il soggetto è in ANPR dal subentro.

L'operazione è andata  a buon fine.
Con il servizio 3003 abbiamo poi scaricato XMl dell'operazione per aggiornare la base dati locale (id op 18896243).

Nel XML tornato però è presente anche il tag "dati iscrizione" con all'interno dei valori errati : 
1) manca il subtag motivo di iscrizione
2) il tag dataDefinizionePratica è valorizzato con la data odierna (18/01/2019) 
3) il tag idOperazioneANPR contiene il valore 18896144 che è lID dell'operazione da WEBAPP di modifica

Se cerco il soggetto con il servizio 3002 invece, nei valori di ritorno il tag datiIscrizione contiene le informazioni corrette (id op del 3002 18896258)

Potete verificare ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by cmigliardi** [comment]
stiamo verificando  -

**Comment by cmigliardi** [comment]
se non ci sono altre osservazioni - chiudo la issue
