### ISSUE TITLE
Soggetto subentrato che diventa PR

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#108]
Un soggetto residente in comune subentrato può diventare Protocollo Riservato, entrando nel programma di protezione: come si dovrà gestire l'uscita da ANPR? 
Con cancellazione per comune non subentrato? (finchè ci saranno comuni non subentrati...)
Il Dipartimento della Pubblica Sicurezza del Ministero dell'Interno è a conoscenza di queste modalità operative? 
Giannone, Amprimo, Floramo, Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Vale la risposta al quesito precedente sostituendo a "iscrizione" "cancellazione".
