### ISSUE TITLE
[WS] annullamenti e cancellazioni incrociate

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1080]
Ambiente di test, prova fatta con i comuni di Poggio a Caiano e Gorgonzola

Prendo nel comune di GORGONZOLA una famiglia di due persone TIZIO (id ANPR 9453161), intestatario, e CAIA (id ANPR 9453160) moglie.

In data 15/1 iscrivo a POGGIO per immigrazione da GORGONZOLA CAIA; a GORGONZOLA attendo la notifica di migrazione e la processo aggiornando la base dati locale.

In data 16/1 cancello a GORGONZOLA per emigrazione in non subentrato TIZIO.

In data di oggi (18/1) rigetto a POGGIO la pratica CAIO. Questo comporta un annullamento mutazione 5012 (id ANPR 18896816) e la creazione di una notifica al comune di GORGONZOLA.

Da GORGONZOLa cerco quindi con il 3002  CAIO per aggiornare la base dati locale ma mi accorgo che gli  mancano i dati di famiglia e di legame. 

Come mai ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by fferraguto** [comment]
Salve,
abbiamo provveduto alla correzione di un bug.
Secondo i nostri test la correzione ha sanato il problema.
Abbiamo anche sanato i dati movimentati con le operazioni segnalate per renderli coerenti.

Le chiediamo, se possibile, cortese riscontro sulla situazione attuale ed eventualmente anche l'esito della ripetizione del test.

Cordiali saluti.

**Comment by busaster** [comment]
Ho avuto modo di verificare solo ora la segnalazione, confermo che la ricerca 3002 del soggetto 9453160 ritorna tutte le informazioni
