### ISSUE TITLE
VERONA: SPECIE toponimi errati in subentro

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1083]
Buongiorno,
in fase di subentro del comune di Verona le specie di alcuni toponimi sono state inviate errate: al posto di PIAZZALE e' stato riportato PIAZZA.

I toponimi sono i seguenti (esistono tutti con specie "PIAZZALE")

ARISTIDE STEFANI
BUCCARI
CADORNA
LUDOVICO ANTONIO SCURO
R.GUARDINI
VENTICINQUE APRILE

Le persone coinvolte sono circa 400 (alcune residenti in convivenza). La certificazione viene errata.
1. Si richiede un vostro aggiornamento massivo; eventualmente se e' necessario fornire un tracciato ad hoc, con che campi va riempito o se bastano le informazioni qui fornite.
(Ci risulta che un aggiornamento simile e' stato fatto con il quesito 972 Toponimo errato in subentro).

Non siamo in grado di risolvere il problema con i web service perche' nel nostro applicativo questa correzione comporta solo l'aggiornamento della tabella interna delle vie.
In web app il comune ha provato a fare una mutazione con ripristino residenza ante subentro ma, per una famiglia con piu' componenti e' stata ricoperta la data decorrenza residenza di un individuo con
quella dell'altro (come riportato nella vostra documentazione), e quindi questa strada non e' percorribile.

2. Si richiede che venga aggiustata la data decorrenza residenza del seguente individuo:
- ID ANPR 43496233 data decorrenza residenza esatta: 17/02/1999 (ora risulta 31/12/1960)

Grazie e distinti saluti
Carla Musian
Applicativo Ascot web

Per ulteriori delucidazioni contattare:
dott. Augusto Olivieri
Direzione Servizi ai Cittadini
tel.uff. 0458077813

**Comment by cvignati** [comment]
Salve,
creando il tracciato record ed inviandolo alla PEC indicata in questa Issue
https://github.com/italia/anpr/issues/972
mi hanno sistemato tutto in qualche giorno.

Hanno anche aggiornato i dati di AE automaticamente, anche se c'è voluto qualche giorno in più (circa 10 gg)

**Comment by cmigliardi** [comment]
Buongiorno, 
certo è già capitato che abbiamo predisposto un tracciato e richiesto una pec alla casella di assistenza e a me in copia. Ogni  richiesta deve essere tracciata ed autorizzata, quindi non è sufficiente seguire una issue #972.  Per maggiori info potete scrivermi cmigliardi@sogei.it  - grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
il tracciato richiesto è il seguente:

ID_ANPR_FAMIGLIA;ID_SOGG_ANPR_INT;COGNOME;NOME;SPECIE;TOPONIMO


attendiamo il file .csv 
che dovrete inviare alla casella di pec
assistenza.anpr@pec.sogei.it
e contemporaneamente a me
grazie 
cordiali saluti

**Comment by cmigliardi** [comment]
Attendo la email con il file.

**Comment by cmigliardi** [comment]
mi scuso, ma  mi hanno  appena comunicato un nuovo tracciato per sanare le posizioni del comune di Verona, per correttezza lo condivido sulla issue visto che altri utenti seguivano la risoluzione, questo il tracciato:  

ID_ANPR_FAMIGLIA;ID_COMUNE_FAMIGLIA;TOPONIMO;SPECIE

grazie  attendo il nuovo file .csv
