### ISSUE TITLE
Problema con ANPR02 e servizio 3002

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1084]
Buongiorno,
stavamo eseguendo delle prove in ambiente di Test (ANPR02), abbiamo notato che la ricerca di un individuo con il servizio 3002, per nome, cognome, data di nascita, non è più funzionante.
Funziona solamente la ricerca per codice fiscale, ma nel caso di Aire privi di Codice Fiscale non è più possibile procedere alla ricerca.

Potete verificare?
Grazie

**Comment by rvinzani** [comment]
Mi può per favore indicare l'id dell'operazione (o quello comunale o quello di ANPR). Grazie

**Comment by Amucciarelli74** [comment]
Salve,
se può essere utile, anche noi abbiamo un errore "_Internal Error (from server)_" se ricerchiamo per codice fiscale un cittadino AIRE con il servizio 3002 (ANPR02), mentre la stessa ricerca va a buon fine per un cittadino residente nel comune. Facciamo presente che da web application, la ricerca va invece a buon fine.
Gli id operazione comune sono rispettivamente 0670412019012320 per la ricerca con errore di un AIRE, e 0670412019012318 per la ricerca a buon fine di un residente. 
Il test è stato effettuato in data 23/01/2019 in ambiente PRE_SUB, per il comune di Teramo.
Grazie, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by rvinzani** [comment]
Il caso dell'internal error è dovuto ad un carattere non ammesso (parentesi) nel campo provincia/contea. Avevamo in previsione di fare la bonifica lo scorso 21 gennaio, abbiamo dovuto rimandarlo alla prossima settimana.

**Comment by Amucciarelli74** [comment]
Ok grazie,
immagino che, dato che si tratta di informazioni trasmesse al subentro con il file generato dalla procedura AnagAire, questo non comporti per il momento la necessità di alcuna azione da parte nostra, per cui restiamo in attesa di notizie in merito alla bonifica del campo.

**Comment by rvinzani** [comment]
Sì, infatti. Vi terremo aggiornati.

**Comment by SAlberto** [comment]
> Mi può per favore indicare l'id dell'operazione (o quello comunale o quello di ANPR). Grazie

Buongiorno,
ecco id dell'operazione ANPR (ambiente TEST): 18905310.

Grazie

**Comment by rvinzani** [comment]
Nel caso specifico il soggetto risiede in un comune diverso da quella che ha effettuato l'interrogazione.
Se si vuole effettuare una ricerca a livello nazionale è necessario impostare ricercaNazionale ='1' ed il comuneResidenza non deve essere valorizzato.

**Comment by SAlberto** [comment]
La ringrazio, mi aveva fuorviato il fatto che la ricerca funzionasse, per un comune diverso da quello di interrogazione, non impostando la ricercaNazionale, ma il solo codice fiscale.

Grazie
