### ISSUE TITLE
[3002] ANPR02: Consultazione Famiglia - listaAnomalie

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1087]
buongiorno.

nell'ambito delle modifiche apportate al servizio di consultazione (ws 3002) con la versione 5.1.0, non mi è chiaro in quali casi troveremo valorizzato il gruppo dati listaAnomalie in coda all'xml.

se possibile avere qualche input da parte vostra per eseguire dei test specifici...

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, se il riferimento è alla sezione introdotta per il 3002 nell' issue #1077. Le anomalie in coda alla risposta ok sono state introdotte per poter fornire, qualora necessario, degli avvisi relativi all'intera operazione. Con questo intervento abbiamo deciso di modificare l'interfaccia wsdl del servizio per dare tempo alle software di adottarla, ma gli avvisi che intendiamo restituire non sono stati ancora rilasciati.
Al momento in cui le prime anomalie (in questo caso solo di tipo W, avviso) verranno rilasciata ve lo comunicheremo.
Cordiali saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
confermo, mi riferivo esattamente a questa novità.
attenderemo...

grazie

**Comment by ANPRCdMI** [comment]
Buongiorno
in ambiente d TEST e PRESUB stiamo lavorando ancora con la versione ANPR01, ma da ieri le operazioni ci restituiscono questo errore: javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (uri:"", local:"listaAnomalie"). Expected elements are <{}testataRisposta>
Potete darci indicazioni in merito?
Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by mttfranci** [comment]
@AMonopoliADS abbiamo introdotto il diagnostico EN528 : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
Che notifica quando in caso di interrogazione scheda individuale (ad esempio per nome e cognome) viene restituita la scheda compatta e non quella completa.

**Comment by mttfranci** [comment]
@ANPRCdMI  In effetti la lista doveva comparire solo per il codice ANPR02, a breve adegueremo il comportamento.

Detto questo la situazione rientra in quella già descritta in altre issue come la #1121 per le quali suggeriamo di non applicare la validazione rigorosa della risposta ANPR.

Saluti 

Assistenza ANPR

**Comment by mttfranci** [comment]
@ANPRCdMI Ora il nuovo elenco dovrebbe attivarsi solo indicando la versione ANPR02

**Comment by AMonopoliADS** [comment]
> 
> 
> @AMonopoliADS abbiamo introdotto il diagnostico EN528 :
> https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
> Che notifica quando in caso di interrogazione scheda individuale (ad esempio per nome e cognome) viene restituita la scheda compatta e non quella completa.

il diagnostico EN528, non lo trovo documentato nella tabella degli errori.
a quale situazione dovrebbe corrispondere?
grazie.

**Comment by mttfranci** [comment]
@AMonopoliADS l'elenco era in fase di pubblicazione, ora dovrebbe essere disponibile.
