### ISSUE TITLE
Internal error (3200)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1088]
Comune di Biella - Produzione
Segnalazione di Internal error a seguito della seguente richiesta
idOperazioneComune JD18929
codMittente 096004
operazioneRichiesta 3002

Grazie.
Filipazzi - Maggioli

**Comment by asqueglia** [comment]
Buongiorno, abbiamo apportato una fix al servizio di consultazione. 
Potete riprovare ? grazie

**Comment by bfilipazzi** [comment]
Informo il cliente. Grazie.
Filipazzi
