### ISSUE TITLE
Internal error (3200)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1089]
Comune di Biella - Produzione
Segnalazione di Internal error a seguito della seguente richiesta
idOperazioneComune JD18935
codMittente 096004
operazioneRichiesta 3002

Grazie.
Filipazzi - Maggioli

**Comment by asqueglia** [comment]
Buongiorno, abbiamo apportato una fix al servizio di consultazione. 
Potete riprovare ? grazie
