### ISSUE TITLE
Web App Utilità e notifiche- Monitoraggio operazioni - ordinamento

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#109]
Sarebbe utile che l'elenco delle operazioni fosse ordinato per ID-ANPR e poi per data.

Amprimo, Gillone, Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Avvertiamo quando possibile verificare

**Comment by gcarbonin** [comment]
Può riprovare l'ordinamento per id_anpr decrescente e darmi un riscontro.

**Comment by annamariaGillone** [comment]
Ok ora va bene grazie
