### ISSUE TITLE
ripristino operazione per errata selezione cittadino

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#1090]
Comune di Scandicci - Produzione
il cittadino Id Scheda Sogg Anpr33199123
è stato inserito per errore nella operazione  29534648 che non riusciamo ad annullare perché non è l'ultima operazione sul soggetto o sulla famiglia,
dato che è stato messo  come IS della nuova famiglia (l'altra persona è corretta) come possiamo correggere la posizione (ripristinarlo sulla vecchia residenza), potete annullare le variazioni non in carico al comune di Scandicci?

grazie

**Comment by frmariani** [comment]
la prossima settimana è previsto il rilascio della nuova gestione degli annullamenti;
la revisione  vi permetterà di effettuare il ripristino della posizione anagrafica parziale, superando le ultime operazioni effettuate sulla famiglia di origine;

**Comment by frmariani** [comment]
potete riprovare l'operazione per favore ?

**Comment by frmariani** [comment]
la posizione del cittadino non è ancora stata corretta, posso aiutarvi ?
nel caso potete scrivermi in privato
frmariani@sogei.it

**Comment by frmariani** [comment]
chiudo la issue, in caso di necessità potete riaprirla.
