### ISSUE TITLE
cancellazione CI AY9488639 (errata attribuzione)

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#1091]
Salve,
Comune di Scandicci - produzione
in ANPR risulta erroneamente caricata la carta  CI in oggetto alla persona con id ANPR 35742530,
non riesco a cancellare o annullare l'errata attribuziione in ANPR,
nel frattempo è stata assegnata alla persona giusta 
grazie per l'aiuto

**Comment by rvinzani** [comment]
Salve, può annullare l'operazione con id 40524373 per eliminare l'errata informazione. Mi faccia sapere. Saluti

**Comment by rvinzani** [comment]
Chiudo la issue. Se il problema non fosse risolto la prego di aprirne una nuova facendo riferimento a questa stessa. Saluti
