### ISSUE TITLE
rettifica nome

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#1093]
Buongiorno

al soggetto ID 24063980 non riusciamo a variare il nome. Il soggetto deve invertire il cognome con il nome.
Come da Issue #917, abbiamo provato a variare i dati attraverso due passaggi; con la prima abbiamo variato il cognome  e ha generato un nuovo codice fiscale ma al secondo passaggio (correzione del nome) l'operazione dà esito negativo per problemi con A.E. (Individuate due posizioni in AT non unificabili (Codice: EAM9C) 
Ora ci troviamo il soggetto con cognome corretto e nome errato.
Grazie
Barbara Malavolti

**Comment by rvinzani** [comment]
Salve, deve verificare se il CF già presente in agenzia delle Entrate (corrispondente alle generalità effettive)  è stato attribuito alla stessa persona o se si tratta di un'omocodia. Nel primo caso può può collegare i due CF e contemporaneamente aggiornare i dati anagrafici del soggetto tramite la funzione presente sul sito web di ANPR alla voce Utilità e notifiche-> Risoluzione disallineamenti. Sega quanto presente nel documento allegato al paragrafo 4.1
[Risoluzione disallineamenti con l'Agenzia delle Entrate 18_10_2018.pdf](https://github.com/italia/anpr/files/2802772/Risoluzione.disallineamenti.con.l.Agenzia.delle.Entrate.18_10_2018.pdf)
