### ISSUE TITLE
Errore AEE95 su mutazione luogo nascita

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1094]
Comune di Modena - Ambiente di produzione

Buongiorno,
dobbiamo rettificare il comune di nascita per il soggetto con idANPR 19250745:  in fase di subentro era stato erroneamente indicato Letojanni (comune cessato alla nascita del soggetto) invece di Letojanni Gallodoro, ma la mutazione fallisce con l' errore:

Operazione non effettuabile (Codice: AEE95)

Viste esperienze precedenti supponiamo che il problema sia che Letojanni è cessato; come possiamo sbloccare?

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera,
abbiamo aggiornato il cod. catastale per Letojanni Gallodoro nelle nostre tabelle in quanto era erroneamente indicato E555 (come Letojanni) invece di E556. 
Attualmente il cittadino indicato ha un CF validato e marcato su Agenzie Entrate con comune di nascita Letojanni e E555 nel CF. Se effettuate una variazione del comune di nascita in Letojanni Gallodoro viene ricalcolato il codice fiscale in quanto cambia il cod. catastale. Pertanto è opportuno prima avvisare il cittadino.
N. Capozzi
