### ISSUE TITLE
[5008] Completamento dati di stato civile

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#1095]
Buongiorno,

avrei bisogno di aiuto per gestire la situazione seguente:

Comune di STAZZANO
Ambiente di PRODUZIONE

Il 24/12/2018 viene iscritta una persona per immigrazione da comune non subentrato [1002] con stato civile 4 (divorziato/a), dati di divorzio assenti e dati di matrimonio presenti (cognome e nome coniuge, data e luogo di matrimonio).
idSchedaSoggettoANPR 45301409
idOperazioneANPR 42231538 (OK)

Il 25/01/2019 inviando il completamento dati [5008] sono stati integrati i dati di divorzio e l’atto di matrimonio ed è stata modificata la data di matrimonio. L’esito del servizio è negativo.
idOperazioneANPR 47318206 (KO)

```xml
<codiceErroreAnomalia>EN369</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione richiesta non possibile. Non e' presente alcun matrimonio per il soggetto … (45301409) corrispondente ai dati inseriti.</testoErroreAnomalia>
```
Facendo alcune prove in ambiente di PRE-SUBENTRO il motivo sembra essere la modifica della data di matrimonio tra l'iscrizione e il completamento ma ho notato che, a parità di situazione, in assenza dei dati di divorzio il completamento viene accettato e la data di matrimonio risulta correttamente aggiornata.
idSchedaSoggettoANPR 111595234
idOperazioneANPR 9867521 ISCRIZIONE (OK)
idOperazioneANPR 9867530 COMPLETAMENTO (OK)

Potete darmi qualche suggerimento per procedere con l'integrazione dei dati nell'ambiente di PRODUZIONE? Se possibile vorremmo evitare di modificare la data di matrimonio per poi correggerla successivamente.
Grazie

Monia Pedrazzoli
APKAPPA

**Comment by frmariani** [comment]
Il servizio di completamento viene utilizzato per definire l'iscrizione di un cittadino, completando, appunto, i dati precedentemente acquisiti; confermo che non è possibile inserire nel servizio di completamento,  la modifica della data del matrimonio ed il divorzio dello stesso; nel vostro caso, le operazioni da eseguire devono essere necessariamente due, a voi la scelta se eseguire quelle nel punto 1 o quelle nel punto 2:
1) modificare la data del matrimonio in fase di completamento e acquisire i dati del divorzio con la successiva operazione di mutazione dei dati;
2) lasciare la data errata del matrimonio acquisendo i dati del divorzio in fase di completamento e modificare la data del matrimonio nella successiva operazione di mutazione dei dati.

**Comment by MoniaPedrazzoli** [comment]
Grazie, abbiamo risolto seguendo l'opzione 2).
Ritenete possibile in futuro rivedere il controllo per consentire di modificare contestualmente le informazioni relative a divorzio e matrimonio?

**Comment by frmariani** [comment]
è prevista qualche implementazione in merito alla gestione dei matrimoni, ma è prematuro parlarne nello specifico.
