### ISSUE TITLE
[2003] strano errore EN344

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1097]
Ambiente di Test, comune di Poggio a Caiano

Ho iscritto con il servizio 1002 due soggetti provenienti da comune non subentrato, Intestatario e moglie (id operazioni ANPR rispettivamente 18918935 e 18918936) con decorrenza 15/01/2019.

Con decorrenza odierna 28/01/2019 causa accertamenti falli la pratica viene rigettata e voglio cancellare per ripristino posizione precedente i due soggetti.
La prima cancellazione (ID ANPR 18918938) per il soggetto intestatario è andata a buon fine, mentre la seconda (ID ANPR 18918939) è fallita con l'errore "EN344 : Sono presenti mutazioni del soggetti con data successiva all'iscrizione".

Non c'è però stata nessuna variazione tra l'iscrizione ed il tentativo di cancellazione.

Potete verificare ?

Grazie 

Gianrico Busa
Maggioli S.p.a

**Comment by asqueglia** [comment]
Buongiorno stiamo analizzando la situazione. Le faremo sapere appena possibile

**Comment by asqueglia** [comment]
Buongiorno, avvisiamo che la fix è stata rilasciata in ambiente di test. E' ora possibile riprovare. Grazie

**Comment by busaster** [comment]
Confermo che ora le operazioni si sono concluse positivamente.
Grazie
