### ISSUE TITLE
2001 - legameSoggetto - dataDecorrenza

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1098]
Comune di Manerbio - Ambiente di test
idOperazioneANPR = 18921607
L'evento di morte è avvenuto il 26/01/2019 ed è stato registrato in anagrafe il 29/01/2019
Nella richiesta di cancellazione 2001 ci sono i seguenti dati:
testataRichiesta - dataDecorrenza 29/01/2019
dataEvento = 26/01/2019
legameSoggetto - dataDecorrenza 26/01/2019
Ho il dubbio che la decorrenza del legame soggetto (riferita alla moglie) debba coincidere con la decorrenza della testata invece che con la data dell'evento.
Potete darmi una conferma ? Grazie
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buongiorno,
il quesito è più di carattere amministrativo che tecnico in quanto, in caso di decesso di un intestatario, impatta sulla data di decorrenza dei nuovi legami di parentela della famiglia.
Il sistema accetta ambedue le date.
Suppongo che se l’informazione viene inviata nella comunicazione di decesso (tali dati sono opzionali nel ws 2001) il comune abbia avuto notizia in merito al nuovo intestatario contestualmente all’evento di  decesso.

**Comment by bfilipazzi** [comment]
Sarò più preciso.
La morte è avvenuta il 26/01, l'anagrafe ne ha notizia il 29/01 e nello stesso giorno 29/01 ha notizia anche dei nuovi legami.
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buonasera, 
mi sono espressa in modo non chiaro: intendevo dire che è il comune che sa quali sono le date di decorrenza corrette.
Venendo al  caso specifico di una variazione delle relazioni di parentela comunicata in un ws 2001 il  sistema utilizza sempre come data decorrenza la data decorrenza dell’operazione.
Nella consultazione scheda della cittadina che è diventata intestataria della famiglia viene riportata come data di decorrenza del legame il 29.01.2019.

**Comment by bfilipazzi** [comment]
Grazie
Filipazzi
