### ISSUE TITLE
Codice errore EN306

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#11]
Sempre Nella fase di subentro , provata in ambiente di test, ci troviamo molte segnalazione sui matrimoni: EN306 Presenza del coniuge e assenza del matrimonio. Anche questo errore non lo troviamo nell’elenco degli errori ANPR. E’ un errore bloccante? Nel comune abbiamo tante situazioni di questo tipo: Abbiamo notato che una mutazione di residenza si riesce a fare come anche la certificazione, esclusa ovviamente quella del matrimonio che non e’ completa.

**Comment by gcarbonin** [comment]
L'errore non è bloccante
Stiamo aggiornando l'elenco degli errori
