### ISSUE TITLE
WebApp - mutazione residenza e iscrizione per altri motivi - consultazione soggetti

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#110]
Buongiorno,
in data 12/04/2017 tramite web app abbiamo effettuato le seguenti operazioni:
IDANPR: 456371 – MUTAZIONE RESIDENZA – Richieste completate con esito positivo e warning
IDANPR: 456369 – ISCRIZIONE PER ALTRI MOTIVI – Completata con esito positivo
Tentando di interrogare i due soggetti delle pratiche tramite la funzione “CONSULTAZIONE SCHEDA INDIVIDUALE” con cognome e nome o con il codice fiscale riceviamo sempre il messaggio: “EN122 La richiesta effettuata non produce alcun risultato”
Andando nella funzione: HOME - UTILITÀ E NOTIFICHE - OPERAZIONI SOSPESE troviamo il soggetto IDANPR: 456369 ma non è possibile eseguire alcuna azione.
Le domande sono:
1)  come possiamo visualizzare i soggetti di queste due operazioni?
2) è possibile cancellare i due soggetti? Se si come?
Grazie
Team Sipo Comune di Milano

**Comment by gcarbonin** [comment]
Può riprovare; con i dati inviati ( mi sembra oggi ) del subentro, tutti scartati, il comune non risultava "subentrato".

**Comment by gcarbonin** [comment]
Non avevo visto l'altra domanda: i soggetti spariscono annullando le due operazioni
