### ISSUE TITLE
Comune di Alessandria - Mutazione Tutti i Dati - Rettifica cognome in minuscolo

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1102]
Per il cittadino id anpr n. 35184228 il cognome del padre risulta erroneamente indicato con la prima lettera maiuscola anziché minuscola.

Abbiamo quindi provveduto tramite l'operazione numero 48073598 Mutazione Tutti i Dati in Rettifica a modificarne l'iniziale del cognome del padre da maiuscola a minuscolo, ma nonostante all'interno del file XML dell'operazione il dato risulti correttamente in minuscolo la modifica non viene percepita.

Interrogando nuovamente il cittadino l'iniziale del cognome del padre si visualizza ancora in maiuscolo.

A disposizione per chiarimenti rimaniamo in attesa di un Vs. gentile riscontro.

Grazie

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato l'operazione da voi inviata e comunichiamo che è un nostro errore. Grazie per la segnalazione. Aggiungeremo l'intervento nei prossimi rilasci. Intanto, se ritenete necessario ed urgente, possiamo effettuare l'intervento da centro a seguito di vostra richiesta tramite PEC.
