### ISSUE TITLE
Tabella stati territori Istat

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1103]
Buongiorno,
L'Istat ha pubblicato la tabella degli Stati e territori esteri al 31/12/2018.
https://www.istat.it/it/archivio/6747

Facendo un confronto con i codici Istat riportati sulla tabella ANPR 02 Stati esteri si trovano delle differenze sulle codifiche Istat ultime che riguardano essenzialmente territori ed il codice 997.
Si chiede se la tabella di ANPR verra' allineata a quella Istat.
Inoltre si chiede con che codifica ANPR salva il codice stato N(3) nei propri archivi: e' l'ID della tabella stati 02? 
Questo per capire come l'eventuale allineamento della codifica Istat nella tabella 2 di ANPR e' "trasparente" rispetto a quanto presente nei vostri archivi.

Grazie
Carla Musian
Applicativo Ascotweb

**Comment by ncapozzi** [comment]
Buonasera, 
la tabella degli stati ANPR segue la codifica ISTAT per quanto riguarda gli stati mentre per i territori si utilizza una codifica interna, derivata dalle tabelle di AnagAire;  la stessa considerazione vale per il codice 997.

N. Capozzi
