### ISSUE TITLE
[6001] Dubbio su Tabella 14 (Lingue)

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1104]
Buongiorno,
volevo segnalarvi che l'excel della tabella 14, quella delle lingue, 
contiene la lingua slovena con codice "SL", mentre sul pattern si trova con codice "SI".

```
<xs:simpleType name="tipoLinguaCertificato">
		<xs:restriction base="xs:string">
			<xs:length value="2"/>
			<xs:pattern value="IT|DE|FR|SI"/>
		</xs:restriction>
</xs:simpleType>
```

**Comment by rnapoli1983** [comment]
Buongiorno, in merito a quanto segnalato, è corretto quanto riportato negli xsd in quanto facciamo riferimento ai codici  ISO 3166-1 - alpha2.

Provvediamo alla correzione nella tabella 14.

Grazie per la segnalazione.

Buona giornata.

**Comment by SAlberto** [comment]
Grazie, buona giornata

**Comment by mttfranci** [comment]
Differentemente da quanto inizialmente prospettato, negli ambienti di test / presubentro verrà da ora accettato il solo codice "SL" così come previsto dalla tabella 14.
A breve verranno anche ripubblicati i wsdl che comunque anticipiamo qui. 
[wsdl6001-5.1.1.zip](https://github.com/italia/anpr/files/2829045/wsdl6001-5.1.1.zip)
A breve l'intervento verrà rilasciato anche in produzione.
