### ISSUE TITLE
[WEBAPP] Elenco soggetti presenti in altro comune

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1105]
Abbiamo subentrato in ambiente di test il comune di Manerbio.
Nell'elenco anomalie troviamo "Soggetti presenti in altro comune con data più recente : 16".
Il numero però non è un link quindi non riusciamo a scaricare l'elenco dei soggetti.
Come possiamo recuperarlo ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by cmigliardi** [comment]
Per download elenchi anomalie e soggetti/famiglie subentrati è necessario accedere dalla WEB  APP, Utilità e notifiche, Download e selezionare uno dei tipi file disponibili.

In particolare per download elenco duplicati tra comuni diversi  è necessario selezionare le due voci

POSIZIONI DUPLICATE COMUNI DIVERSI CON DATA Più RECENTE

POSIZIONI DUPLICATE COMUNI DIVERSI CON DATA Più REMOTA

Basta cliccare sul tasto Conferma, non è necessario impostare altri criteri di ricerca.

Per ciascuna posizione duplicata è necessario contattare l’altro comune in cui il cittadino risulta iscritto e verificare chi dei due lo deve cancellare dal proprio gestionale. Si tenga presente tuttavia che la base dati si riferisce ad un ambiente di prova e pertanto tali duplicazioni potrebbero non essere presenti in ambiente reale.

**Comment by busaster** [comment]
Trovato, ci serviva per fare dei tests su cancellazioni per DOPPIA ISCRIZIONE.
Grazie
