### ISSUE TITLE
Carta d'identità rilasciata da Ambasciata D'Italia a L'Aja

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1106]
Ambiente di produzione
Codice Operazione ANPR: 48375402

Si tratta di una carta d'identità rilasciata dall'Ambasciata d'Italia a L'Aja, codice consolato 2420100.
Controllando sulle tabelle di riferimento il codice consolato risulta inserito tra quelli esistenti, ma quando il Comune prova ad inviare la comunicazione ad ANPR viene restituito l'errore "Codice consolato di rilascio carta di identita' 2420100 inesistente sulla tabella di riferimento".

Come è possibile intervenire per inviare questa carta d'identità?
Ringraziando in anticipo
Cordiali saluti

**Comment by ncapozzi** [comment]
Buongiorno,
in realtà il problema è relativo alla descrizione del consolato e non al codice. Nel campo <descrizioneConsolato>L'AJA - AMBASCIATA D'ITALIA</descrizioneConsolato> deve essere indicata la sede come da tabella <descrizioneConsolato>L'AJA</descrizioneConsolato>

N. Capozzi
