### ISSUE TITLE
Comune di Basiliano ambiente presubentro 3002

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1107]
Ambiente pre subentro comune di Basiliano.
idoperazioneComune = 85. 
Operazione richiesta 3002.
codDestinatario ANPR01.

Richiediamo i dati di una persona con idANPR del soggetto (<idSchedaSoggettoANPR>100943292)
Viene restituito un elenco di omonimi, ma la persona residente nel comune di Basiliano nella risposta ha un <idSchedaSoggettoANPR>79386032, che non corrisponde ad alcun soggetto.

potete verificare?

grazie

**Comment by INSIEL1** [comment]
in realtà la richiesta dati nostra è partita con questa testata e per una persona diversa con idANPR =100943292
<testataRichiesta>
    <idOperazioneComune>85</idOperazioneComune>
    <codMittente>030009</codMittente>
    <codDestinatario>ANPR01</codDestinatario>
    <operazioneRichiesta>3002</operazioneRichiesta>
    <dataOraRichiesta>2019-02-01T12:50:38Z</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>PRE_SUB</tipoInvio>
    <nomeApplicativo>ASCOTWEB</nomeApplicativo>
    <versioneApplicativo>18.04.0000</versioneApplicativo>
    <fornitoreApplicativo>ASCOTWEBFVG</fornitoreApplicativo>
  </testataRichiesta>
la data richiesta è del 1/02/2019.
la risposta che riceviamo contiene i dati di una persona diversa idANPR =79386032 e ha data del 6/11/2018.
<testataRisposta>
      <idOperazioneComune>85</idOperazioneComune>
      <codMittente>030009</codMittente>
      <codDestinatario>ANPR01</codDestinatario>
      <operazioneRichiesta>3002</operazioneRichiesta>
      <dataOraRichiesta>2018-11-06T10:56:49Z</dataOraRichiesta>
      <idOperazioneANPR>8719079</idOperazioneANPR>
      <esitoOperazione
Preciso che il comune ha effettuato 2 presubentri. Quando viene rifatto il presubnetro noi azzeriamo i contatori di idOperazioneComune. Ho l'impressione che venga restituita una risposta che fa riferimento a comunicazioni del primo presubentro (nel caso l'idOperazioneComune sia uguale). L'idANPR restituito non è presente in ANPR e neanche presso la banca datai comunale.

Ripeteremo l'operazione.

**Comment by cmigliardi** [comment]
Mi scusi ma dalla request che le ho rintracciato - la data richiesta è del "2018-11-06T10:56:49Z"  come la data  riferimento scheda 2018-11-06    e non del 1 /02/2019

**Comment by cmigliardi** [comment]
la request inviata adesso - ha lo stesso id op. 85 - quindi il sistema attiva il meccanismo di retry - si chiude   come richiesto da parte vostra  via email
