### ISSUE TITLE
Certificazione di Stato Civile /Stato Libero

### ISSUE THREAD

**Issue by giuflavio83** [italia/anpr#1108]
Il mio comune è da qualche mese subentrato in ANPR,
ho riscontrato che sia per la certificazione di “stato libero” che per quella di “stato civile” in caso di persona nubile/celibe viene certificato sempre DI STATO LIBERO.

Chiedo se questa configurazione è corretta o c’è qualcosa che mi sfugge, perché prevedere due diversi certificati se la certificazione è sempre la stessa?

Grazie

**Comment by rvinzani** [comment]
Queste sono le indicazioni ricevute dal Ministero dell'Interno
