### ISSUE TITLE
[5008] Revoca/Annullo Carta di Identità

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1109]
Buongiorno,

Ambiente effettivo
Operazione ANPR: 48621369
Operazione ANPR: 48636164

Due comuni da questa mattina ci segnalano l'impossibilità di effettuare CIE in quanto non è stata revocata la carta precedente, con l'operazione 48621369 un comune, con 48636164 l'altro, effettivamente hanno comunicato tale revoca senza errori di ritorno, quindi crediamo sia andata a buon fine.

Potete verificare?
Grazie

**Comment by rvinzani** [comment]
La revoca sarà a breve estesa in ambiente di produzione. In ogni caso è possibile impostare la data di scadenza della carta di identità ad una data antecedente alla data di rilascio della CIE. Le due operazioni inviate sono andate a buon fine. Attendiamo di sapere se la CIE sia stata emessa
