### ISSUE TITLE
WA - Certificato Stato di famiglia su più pagine

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#111]
Data test 14/04/2017 - Ambiente test presubentro
In data 01/02/2016 abbiamo segnalato tramite file excel inviato da CsiPiemonte la seguente anomalia a seguito di test sul nostro applicativo integrato con Web-service: Famiglie con più di tre componenti: sulla prima pagina del certificato sarebbe meglio stampare solo i primi 3 componenti, con dicitura "SEGUE", sulla seconda pagina "CONTINUA" per omogeneità dei componenti della famiglia. Tale segnalazione è stata da voi indicata come Change.
Oggi abbiamo ripetuto questo test tramite Web Application (Data test 06/04/2017 – Ambiente presubentro (dppre) ) e questa modifica non è stata ancora effettuata.
es famiglia di 4 componenti  VLLVIO65S15L219H.  Nella seconda pagina compare solo "Riscossi Euro 0,56 per diritti di segreteria " e il QR Code. 
 Amprimo, Gillone, Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Non tutte le modifiche richieste vengono eseguite; si valuta in base anche alla complessità tecnica. I certificati così come vengono prodotti attualmente sono utilizzati anche in ambiente di esercizio e sono stati approvati dal Ministero dell'interno.
