### ISSUE TITLE
[5013] Revoca Carta di Identità

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1110]
con sorpresa anche i nostri clienti stanno verificando blocchi in fase di emissione CIE, a motivo di carte di identità ancora valide, presenti in ANPR.
è un caso che capitino tutti oggi? oppure è sempre stato così...?

in ogni caso:
al momento abbiamo tentato di sbloccare la situazione forzando una data scadenza del documento cartaceo, antecedente l'emissione della CIE.
avremmo tentato anche la revoca del documento (come previsto dalla v5.1.0 di ANPR) ma la tabella 48 non è ancora aggiornata con i nuovi codici realitivi a carta di identità e atto di nascita (che ho visto dalla web-app).

quale deve essere la corretta modalità di intervento in questi casi?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Oggi è presente in ambiente di produzione un servizio che, in caso di soggetti presenti in ANPR, restituisce al sistema CIEOnLine la presenza di carta di identità cartacea che, se in corso di validità, impedisce l'emissione della CIE. Il servizio di revoca sarà a breve disponibile in ambiente di produzione ed è previsto per eliminare delle informazioni inserite erroneamente. E' possibile comunque effettuare una mutazione tutti i dati, mutazione Carta di identità e impostare la data di scadenza ad una data antecedente alla data di rilascio della CIE. Tale operazione può farla esclusivamente il comune di residenza del soggetto.

**Comment by SAlberto** [comment]
scusate l'intromissione,
volevo solamente avvisare che procedendo con una 5013 per la revoca della carta d'identità si va ad eliminare il dato della Carta, credo sia più giusto procedere con una 5008 inserendo la data di annullo

**Comment by rvinzani** [comment]
Corretto.

**Comment by LucaBonini64** [comment]
Buongiorno, vi segnalo che i nostri clienti ci stanno comunicando che l'impossibilità di rilasciare la carta d'identità viene segnalata anche quando la carta è nei 180 giorni precedenti alla scadenza, quindi quando è liberamente rinnovabile senza nessun bisogno di revoca o annullamento.

**Comment by rvinzani** [comment]
Questa non è l'indicazione che ci ha dato il Ministero dell'Interno. La carta di identità può essere emessa 3 mesi prima a patto che venga annullata la precedente in modo che non siano presenti due differenti documenti entrambi incorso di validità.

**Comment by AMonopoliADS** [comment]
sto provando in ambiente di TEST la mutazione della scheda per valorizzare la dataAnnullamento di una carta di identità.
apparentemente sembra tutto ok (nel senso che la comunciazione 5008 viene accettata), ma in consultazione la dataAnnullamento non viene restituita.

rif. idOperazioneComune 2019000071 (ws 5008, tipoMutazione '3' x modifica dataAnnullamento)
rif. idOperazioneComune 2019300413 (ws 3002, post-mutazione dataAnnullamento)
ambiente di TEST - comune di FAENZA

grazie

**Comment by cvignati** [comment]
> 
> 
> Questa non è l'indicazione che ci ha dato il Ministero dell'Interno. La carta di identità può essere emessa 3 mesi prima a patto che venga annullata la precedente in modo che non siano presenti due differenti documenti entrambi incorso di validità.

Buongiorno,
può, cortesemente, indicarmi il riferimento normativo nel quale si specifica che il rilascio è possibile 90 giorni prima e non 180.

Grazie

**Comment by bfilipazzi** [comment]
Non ci sono due documenti in corso di validità, perché il nuovo documento è consegnato dietro ritiro del precedente. 
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Ho erroneamente scritto 3 piuttosto che 6. 
Credo che il controllo sia stato per il momento eliminato.
In ogni caso volevo precisare che il servizio richiamato da CIEOnLine per richiedere i dati del soggetto, in caso di presenza dello stesso in ANPR, restituisce una serie di informazioni tra le quali, permesso di soggiorno, carta di identità etc. Su questi dati il sistema CieOnLine applica dei controlli secondo specifiche ricevute dal Ministero.

**Comment by cvignati** [comment]
> 
> 
> Ho erroneamente scritto 3 piuttosto che 6.
> Credo che il controllo sia stato per il momento eliminato.
> In ogni caso volevo precisare che il servizio richiamato da CIEOnLine per richiedere i dati del soggetto, in caso di presenza dello stesso in ANPR, restituisce una serie di informazioni tra le quali, permesso di soggiorno, carta di identità etc. Su questi dati il sistema CieOnLine applica dei controlli secondo specifiche ricevute dal Ministero.

Perfetto.
Confermo che non ho più riscontrato il problema.

Ho verificato l'introduzione di questi aggiornamenti, penso per i comuni in ANPR:
- Aggiunta del Codice Istat del comune dopo gli estremi dell'atto di nascita
- Compilazione di Nome e Cognome dei genitori per i minorenni
- Compilazione del comune estero di nascita
- QRCode sulla ricevuta del rilascio che permette di verificare l'autenticità della ricevuta attraverso la app Ve.Do

**Comment by AMonopoliADS** [comment]
> 
> 
> sto provando in ambiente di TEST la mutazione della scheda per valorizzare la dataAnnullamento di una carta di identità.
> apparentemente sembra tutto ok (nel senso che la comunciazione 5008 viene accettata), ma in consultazione la dataAnnullamento non viene restituita.
> 
> rif. idOperazioneComune 2019000071 (ws 5008, tipoMutazione '3' x modifica dataAnnullamento)
> rif. idOperazioneComune 2019300413 (ws 3002, post-mutazione dataAnnullamento)
> ambiente di TEST - comune di FAENZA
> 
> grazie

rinnovo la richiesta di verificare questa segnalazione.
tra i vari contributi, non vorrei fosse stata persa di vista...
grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue facendo riferimento a questa stessa
