### ISSUE TITLE
ANOMALIA RILASCIO CIE

### ISSUE THREAD

**Issue by ComuneSegrate** [italia/anpr#1112]
Buongiorno, oggi oltre alla problematica sui rinnovi (prima della scadenza) delle Carte d'identità cartacee abbiamo avuto problemi sui cittadini "iscritti 2 volte" in ANPR. Mi spiego meglio, quando siamo migrati in ANPR abbiamo avuto alcuni problemi su cittadini iscritti nel ns. Comune da Milano che non aveva provveduto alla cancellazione in ANPR e noi, dopo la migrazione  li avevamo portati dentro il sistema. 
Il tutto dava come risultato una "doppia iscrizione" con le 2 residenze attive  che non ci rendeva possibile il rilascio delle certificazioni e della Carta d'identità al cittadino.
Milano sta provvedendo piano piano a sanare queste anomalie e questa mattina ci siamo accorti che su alcuni cittadini, nel frattempo cancellati da Milano, restano attivi comunque due record: uno come cancellati da Milano e uno come iscritti da noi (sono stati migrati in automatico perchè già residenti da noi durante il ns. passaggio in ANPR).
Provando ad inserire il codice fiscale per iniziare l'acquisizione dati CIE il sistema cieonline ci blocca dandoci questo errore: "ATTENZIONE: la richiesta effettuata non produce alcun risultato. La invitiamo a verificare sul sistema ANPR la scheda anagrafica del cittadino richiedente la CIE e a riprovare dopo aver sanato eventuali anomalie. Se il problema persiste la invitimo a contattare il servizio di assistenza ANPR e a fornire i dettagli dell'errore"

Qualcuno di voi ha già avuto questo problema?

**Comment by rvinzani** [comment]
Può per favore inviarci dei casi di esempio per poter fare un'indagine? Grazie

**Comment by rvinzani** [comment]
Potete riprovare?

**Comment by ComuneSegrate** [comment]
Ora inserendo il codice fiscale in cieonline, per procedere ad una nuova acquisizione ci da un messaggio di errore: ATTENZIONE - si è verificato un errore nella creazione della richiesta.
In ANPR è rimasto tutto uguale
grazie.

**Comment by rvinzani** [comment]
Il problema mi è stato riferito fosse nel sistema CieOnLine e sarà corretto con un aggiornamento di domattina. Attendo vostra conferma

**Comment by rvinzani** [comment]
Chiudo la issue. Se il problema non fosse risolto potete riaprirne un'altra facendo riferimento a questa stessa
