### ISSUE TITLE
Tabella di riferimento dei comuni problema IDPROVINCIA

### ISSUE THREAD

**Issue by MtwStark** [italia/anpr#1114]
Salve,
mi sono imbattuto in una strana situazione nella codifica del campo **IDPROVINCIA** sulla tabella di riferimento dei comuni, in pratica sembra esserci un disallineamento con la tabella di decodifica dell'ISTAT dei [Codici di Provincia e Regione](https://www.istat.it/storage/codici-unita-amministrative/Codici-statistici-e-denominazioni-delle-ripartizioni-sovracomunali.zip) (reperibile alla  [pagina](https://www.istat.it/it/archivio/6789))

Ho notato che la tabella comuni fa riferimento al codice IDPROVINCIA=111 per diversi comuni della provincia di Latina,  ma secondo la tabella ISTAT, Latina dovrebbe essere 059.
Il codice IDPROVINCIA=111 dovrebbe essere invece “Sud Sardegna”.
Per contro vengono identificati (sempre sulla tabella comuni) con IDPROVINCIA=112 i comuni della provincia “Sud Sardegna”, ma nella tabella ISTAT il codice provincia 112 non esiste.

Mi sono perso un aggiornamento?

Grazie

**Comment by MassimoSchiappa** [comment]
Salve,
nella tabella di riferimento dei comuni è riportato nel campo IDPROVINCIA un identificativo interno di ANPR per le province che coincide solo parzialmente con una traduzione numerica del codice Istat per le province, e quindi non deve essere utilizzato come codice istat delle province. Per l'identificazione della provincia dovrebbe invece essere utilizzato il campo SIGLAPROVINCIA della tabella di riferimento dei comuni, che corrisponde al campo "Sigla automobilistica" delle tabelle Istat da lei citate.
Saluti
