### ISSUE TITLE
Certificazione indirizzo comprendente scala esterna

### ISSUE THREAD

**Issue by Codroipo2018** [italia/anpr#1115]
Certificazione indirizzo comprendente scala esterna
Buongiorno, siamo un comune in fase di presubentro ad ANPR. Abbiamo provato a stampare un certificato di residenza di una persona, ad esempio residente in "Via Piave 7 scala A interno 5".
Nel certificato l'indirizzo appare nel seguente modo: "Via Piave 7 interno 5".
Verificato i dati inseriti in ANPR, l'indirizzo risulta correttamente indicato nella scheda individuale e nei campi giusti.
Qual è il modo per fare uscire in stampa l'indirizzo corretto?
Grazie in anticipo per la risposta, cordiali saluti.

**Comment by cmigliardi** [comment]
Non ho ricevuto indicazioni, ad ogni modo, è stata rilasciata una versione in test comuni / presubentro  che riporta il dato della scala esterna. (la scala veniva già riportata) -  dateci un ritorno -  grazie

**Comment by Codroipo2018** [comment]
buongiorno.
prego scusarmi, Ho purtroppo subito un inciddente che mi ha costretto dopo gli accertamenti al pronto soccorso ad assentarmi per alcuni giorni dall'ufficio. Farò al mio rientro alcune verifiche e vi farò sapere. Grazie per la collaborazione.

Da: cmigliardi [notifications@github.com]
Inviato: mercoledì 6 febbraio 2019 15.00
A: italia/anpr
Cc: Chiariello Raffaele - Codroipo; Author
Oggetto: Re: [italia/anpr] Certificazione indirizzo comprendente scala esterna (#1115)


Non ho ricevuto indicazioni, ad ogni modo, è stata rilasciata una versione in test comuni / presubentro che riporta il dato della scala esterna. (la scala veniva già riportata) - dateci un ritorno - grazie

**Comment by Codroipo2018** [comment]
[cid:image001.png@01D1432C.1D6D2810]


[cid:image002.png@01D1432C.1D6D2810]



Buongiorno,
Sono rientrato in ufficio dopo una forzata assenza e ho verificato.
Effettivamente il problema è risolto.
Grazie.
Cordiali saluti
Raffaele Chiariello
Ufficio Servizio Demografici
Tel 0432 824537 Fax 0432 824582
raffaele.chiariello@comune.codroipo.ud.it<mailto:raffaele.chiariello@comune.codroipo.ud.it>
Piazza G. Garibaldi, 81 - 33033 - Cittï¿½ di Codroipo (UD)
comune.codroipo@certgov.fvg.it<mailto:comune.codroipo@certgov.fvg.it>
http://www.comune.codroipo.ud.it/




[cid:image003.png@01D1432C.1D6D2810]

Comune di Codroipo (UD) - Informativa sulla privacy D.Lgs 196/2003 Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario proibita.La sicurezza e la correttezza dei messaggi di posta elettronica non possono essere garantite.
Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci e distruggerlo.
Grazie.






Da: cmigliardi <notifications@github.com>
Inviato: mercoledì 6 febbraio 2019 15:00
A: italia/anpr <anpr@noreply.github.com>
Cc: Chiariello Raffaele - Codroipo <raffaele.chiariello@comune.codroipo.ud.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] Certificazione indirizzo comprendente scala esterna (#1115)


Non ho ricevuto indicazioni, ad ogni modo, è stata rilasciata una versione in test comuni / presubentro che riporta il dato della scala esterna. (la scala veniva già riportata) - dateci un ritorno - grazie
