### ISSUE TITLE
Problemi iscrizione scheda 41250292

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1116]
Buon pomeriggio.
Non riesco ad effettuare un'iscrizione per altri motivi nel Comune 108009 con decorrenza 30/10/2018 della scheda 41250292 all'interno della convivenza 9084582.
Il numero dell'applicativo comunale della scheda soggetto è 25201 .

Rimango in attesa di un vostro riscontro.

I miei riferimenti sono i seguenti:
Andrea Paltrinieri
e-mail: paltrinieri.andrea@biassono.org
tel. 039-2201060

cordiali saluti

Andrea Paltrinieri

**Comment by frmariani** [comment]
il soggetto con idanpr=41250292 è stato cancellato per doppia iscrizione dal comune di Carate Brianza, pertanto questo idanpr non può più essere riutilizzato.
l'iscrizione deve essere effettuata senza idanpr

**Comment by paltrinan** [comment]
Ho provato a fare l'iscrizione con il gestionale comunale.
Viene fuori l'errore:
ERRORE DA ANPR: 
EN187 - il Soggetto GRZFNC34A63A470U, GRAZIOLI, FRANCA, 23/01/1934, 020002 e' gia' iscritto o deceduto

**Comment by frmariani** [comment]
nell'xml della richiesta è presente ancora l'idanpr del soggetto: dovete eliminarlo

**Comment by paltrinan** [comment]
Ho fatto una nuova prova col nostro sistema; è uscito un nuovo errore
ERRORE DA ANPR: 
EN188 - Soggetto GRZFNC34A63A470U, GRAZIOLI, FRANCA, 23/01/1934, 020002 gia' presente su ANPR

**Comment by paltrinan** [comment]
Se mi collego sul Vs. portale, chiedo se potete darmi assistenza telefonica - 039-2201060

**Comment by paltrinan** [comment]
sto tentando di fare l'iscrizione da webapp del Ministero dell'Interno. La webapp mi chiede, da indicare obbligatoriamente, il convivente di fatto - ma in realtà la signora non ha il convivente di fatto. Cosa posso fare?

**Comment by paltrinan** [comment]
ho lasciato l'operazione in sospeso all'interno del sistema - il mio codice è PLTNDR81H26M052M

adesso finisce il mio turno di lavoro

Chiedo se potete gentilmente darmi un riscontro cioè dirmi cosa c'è di sbagliato nell'inserimento dell'operazione dalla vs. webapp.

Per quanto riguarda, invece, il nostro applicativo interno, sistemerò la cosa disabilitando temporaneamente l'integrazione con ANPR.

cordiali saluti.

Andrea Paltrinieri

**Comment by frmariani** [comment]
C'è stata un po' di confusione nell'iscrizione del cittadino:
1) iscrizione nel comune di Biassono;
2) subentro nel comune di Carate Brianza;
3) cancellazione per doppia iscrizione dal Comune di Carate Brianza;
4) Annullamento dell'iscrizione dal Comune di Biassono.

Effettueremo una piccola modifica che vi permetta la re-iscrizione del cittadino con l'idanpr 41250292
Avviseremo quando sarà possibile riprovare.

**Comment by frmariani** [comment]
Potete riprovare l'iscrizione con l'idanpr 41250292

**Comment by paltrinan** [comment]
Problema risolto :-)

Grazie mille per l'assistenza ricevuta

Buon lavoro

Andrea Paltrinieri
