### ISSUE TITLE
[WEBAPP] Esito AE: Operazione non effettuabile (Codice 95)

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1120]
Buongiorno,
in ambiente di presubentro stiamo riscontrando problemi con la validazione dei codici fiscali via WebApp. Infatti il tentativo di risolvere i disallineamenti con AE restituisce l'errore in oggetto. Abbiamo provato più volte sia con lo stesso soggetto che con soggetti diversi, ma la situazione rimane invariata.
Potete verificare?
Grazie. 

Chiara Leanza
Wave Informatica per il Comune di Torino

**Comment by frmariani** [comment]
potete riprovare per favore ?
nel caso il problema si ripresentasse, per favore indicate qualche riferimento all'operazione.

grazie.

**Comment by chiaralea** [comment]
Non vi possiamo fornire id operazioni in quanto stiamo operando da WEBAPP tramite la funzione RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE. Quindi non effettuiamo operazioni se prima non riusciamo a validare il codice fiscale. Attualmente il sistema riporta il messaggio "Esito AE: Codice Fiscale non trovato (Codice 90)" per ogni soggetto consultato. Il messaggio è cambiato, ma il problema persiste.

**Comment by frmariani** [comment]
il problema adesso è di tutt'altra natura: il CF non è presente in AE
