### ISSUE TITLE
Servizio 3002 - Unmarshalling Error

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#1121]
Buongiorno

alla richiesta di consultazione dati di un cittadino, viene restituito il seguente errore:
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (uri:"", local:"dataAnnullamento"). Expected elements are <{}interdizioneEspatrio>,<{}comuneRilascio>,<{}dataRilascio>,<{}cartaceaElettronica>,<{}dataScadenza>,<{}consolatoRilascio>,<{}numero> 

Qui di seguito i dati per la ricerca del messaggio:
<idOperazioneComune>20190206111044391565</idOperazioneComune>
<OperazioneANPR>49247650</idOperazioneANPR>

C'è un disallineamento nel tag <cartaIdentita> ma l'xsd risulta allineato con il tracciato xls. 
Potreste aiutarci a capire dove sta l'errore?

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by mttfranci** [comment]
Dal messaggio sembrerebbe trattarsi di una validazione locale del gestionale comunale.
Questa situazione è stata trattata nella issue #925.

Ci rendiamo conto che gestire l'interoperabilità tra i diversi software house che interagiscono il sistema ANPR presenta diverse criticità per tutti gli attori coinvolti.

A tal, in accordo con il Team Digitale, sono state pubblicate delle linee guida sulla gestione delle modifiche al software : 
https://github.com/italia/anpr/blob/master/src/change-management/change-management.md
Nell'ambito di tali linee guida l'aggiunta di un campo opzionale è considerato una modifica retrocompatibile (come in questo caso la dataAnnullamento per la carta di indentità).

Siamo a disposizione per ogni ulteriore chiarimento.
Cordiali saluti

Assistenza ANPR
