### ISSUE TITLE
Ripristino posizione precedente

### ISSUE THREAD

**Issue by LETSIM22** [italia/anpr#1122]
ambiente di PRODUZIONE - comune di FANO (PU)

Identificativo scheda attribuito da ANPR: 42376925

si tenta di iscrivere per "ripristino posizione precedente" un soggetto che alla data del subentro era emigrato, e che oggi deve essere ripristinato a motivo degli accertamenti negativi nell'altro comune PESARO comune già Subentrato.

Il Comune di Pesaro ha cancellato il soggetto per altri motivi indicando come descrizione "ripristino posizione anagrafica"

in qualità di "ripristinato" il soggetto dovrebbe acquisire queste informazioni:
data iscrizione: 31.02.2007
data di appartenenza alla famiglia: 01.08.2008
data di ultima residenza: 13.02.2007

Non momento in cui tento la registrazione per Iscrizione per altri motivi e cerco la persona 
il programma non mi permette di selezionare il soggetto

![image](https://user-images.githubusercontent.com/47383691/52336083-3d686b80-2a04-11e9-87c3-f7972056c8f6.png)

grazie.
Simoncini

**Comment by asqueglia** [comment]
Buongiorno, comunichiamo che sul sito WEB ANPR  al momento non è stata prevista, per i sevizi di iscrizione, la possibilità di precaricare i dati delle generalità a partire da una ricerca di un soggetto ‘cancellato’; al momento per ripristinare un soggetto, è necessario inserire ex novo tutti i dati compreso l’idANPR assegnato al soggetto all'atto della prima iscrizione in ANPR.

**Comment by MarcoMigliori** [comment]
Abbiamo inserito il soggetto.
