### ISSUE TITLE
Ripristino posizione anagrafica - annullamento cambio di residenza da comune subentrato a comune non subentrato

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1123]
Buon giorno,
stiamo testando, in ambiente PRE_SUB, l'operazione anagrafica in oggetto, in particolare nel caso in cui, successivamente al cambio di residenza, il comune di immigrazione subentri e si proceda di seguito al ripristino della posizione anagrafica del cittadino per "accertamenti negativi".
Per simulare l'operazione, abbiamo effettuato l'emigrazione di un cittadino da Teramo (subentrato) a Loreto Aprutino (non ancora subentrato), utilizzando il ws 2003 (id operazione comune 0670412019020524), con decorrenza 02/02/2019. 
Successivamente, in data 05/05/2019, abbiamo fatto subentrare il comune di Loreto Aprutino, che quindi ha iscritto di nuovo il cittadino in ANPR con il file di subentro. 
Il comune di Loreto Aprutino ha in seguito cancellato il soggetto immigrato, sempre con il ws 2003, per "ripristino posizione precedente", indicando il _motivoCancellazione_ '12' (id operazione comune 068021201902065). 
Tutte queste operazioni sono andate a buon fine, ma a questo punto ci saremmo aspettati, secondo quanto specificato nel capitolo 12.1.2, la ricezione da parte del comune di emigrazione (Teramo) della notifica N014, a seguito di cui poi avrebbe dovuto provvedere a reiscrivere l'individuo in ANPR utilizzando il ws 1002 per "ripristino posizione precedente", indicando il _motivoIscrizione_ '10'.
Specifichiamo che il comune di Teramo ottiene le notifiche effettuando un'interrogazione con ws 3003 e _operazioneRichiesta_ N014, ma la notifica non è stata ricevuta, nè si trova nella WA nella sezione 'Utilità e notifiche'.
Si tratta di un caso simile a quanto riportato nella issue #823 , in cui c'è stato un problema da parte di ANPR nella generazione della notifica; potete dirci se si è verificata la stessa situazione, oppure se c'è stato qualche errore da parte nostra nelle operazioni effettuate?
Il test è stato effettuato nelle date 05-06/02/2019, come detto in ambiente PRE_SUB.
Grazie, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by fferraguto** [comment]
Salve,
occorre indicare il comune di destinazione nell'operazione di cancellazione per ripristino (così come avete fatto per la prima cancellazione per migrazione verso comune non subentrato).
Per testare il funzionamento e l'invio della notifica suggerirei di annullare l'operazione di cancellazione per ripristino e ripeterla con l'indicazione richiesta.
Cordiali saluti.
