### ISSUE TITLE
CANCELLAZIONE PER DOPPIA ISCRIZIONE - SOGGETTI PRESENTI IN FASE DI MIGRAZIONE E NON CANCELLATI DAL PRECEDENTE COMUNE

### ISSUE THREAD

**Issue by ComuneSegrate** [italia/anpr#1124]
Buon giorno,
siamo migrati il 12/12/18 - in parecchi casi cittadini iscritti da noi in data antecedente alla nostra migrazione e provenienti da Comuni in ANPR che per vari motivi non avevano ancora provveduto alla loro cancellazione, sono stati cancellati dal comune di precedente iscrizione causa doppia cancellazione. Questa è la soluzione che la nostra software house ci ha detto di adottare, che ho anche trovato suggerita nel forum e che tutti i Comuni con cui abbiamo avuto a che fare hanno tranquillamente eseguito. Ora mi trovo in difficoltà con un Comune che sostiene di non poter fare la cancellazione per doppia iscrizione di un cittadino immigrato da noi il 6/12/18 e come tale importato in ANPR in fase di migrazione il 12/12/18 e duplicato in quanto non ancora cancellato dal comune di provenienza (devo ammettere che per colpa nostra, nell'attività congestionata del pre subentro, abbiamo mancato di inviare l'APR4 al comune per la cancellazione). Ora però a seguito di richiesta e disponibili alla trasmissione anche se tardiva dell'APR4, il Comune di precedente residenza si rifiuta di cancellare il cittadino per doppia iscrizione, ma sostiene che sia necessario da parte nostra chiedere all'assistenza SOGEI l'unificazione dei due profili. Personalmente, ritengo formalmente non corretto unificare i due soggetti in quanto il cittadino non è passato da un comune all'altro all'interno di ANPR ma è uscito, anche se per pochi giorni da ANPR, dal 6/12 all'11/12 (quando è passato da un comune migrato a uno non migrato) ed è rientrato in ANPR il 12/12 come nostro cittadino, generando correttamente un nuovo codice. Se può essere utile per una verifica, i codici ANPR di riferimento dei soggetti sono 23274528 e 42822222. Resto in attesa di indicazioni sul corretto comportamento in questi casi.
Grazie
Clara Bossi
Responsabile Sezione Servizi Demografici e al Cittadino
Comune di Segrate

**Comment by rvinzani** [comment]
Gent.le Sig.ra Bossi, la procedura che lei ha indicato è corretta ed è a carico del comune che avrebbe comunque dovuto cancellare il suo cittadino prima poi per emigrazione. I casi come il vostro ne abbiamo avuti tanti e tutti hanno seguito lo stesso iter. Nel caso però non riuscisse a venirne a capo cancelli lei il suo cittadino per doppia iscrizione ed esegua una mutazione in data 6/12/2018 prendendo in carico il cittadino dell'altro comune.

**Comment by ComuneSegrate** [comment]
Grazie per la conferma, proverò comunque a riportare la sua risposta al Comune sperando di convincerlo a fare quanto deve.
