### ISSUE TITLE
[A001] Internal server error ma operazione completata ???

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1126]
Ambiente di produzione comune di Bergamo.

Iscrivo per Nascita AIRE un soggetto ( id operazione ANPR 49363670)
La richiesta ci ritorna un errore di servizio (Internal server error) ma in ANPR iscrive il soggetto.
Questo è un grave problema perché ci impedisce di allineare la base dati locale in seguito alla chiamata al servizio. E' già capitato un paio di volte in giornata.
Potete indagare per favore ?

Grazie
Gianrico Busa 
Maggioli Spa

**Comment by asqueglia** [comment]
Buongiorno, l'iscrizione in famiglia esistente trasmessa ha causato un errore di validazione della risposta; la famiglia esistente infatti presenta l'attributo provinciaContea = (SELANGOR) contenente caratteri non validi.  Al momento, essendo comunque andata a buon fine l'iscrizione, potete provvedere allo scarico della risposta indicata per aggiornare i sistemi locali. Alternativamente potete annullare l'operazione di iscrizione (che non ha comportato alcuna richiesta CF ad AE perché è stata trasmessa con gestione CF =3 senza richiesta validazione) e richiedere la bonifica del dato non valido, prima di risottomettere l' iscrizione.

Con l'occasione comunichiamo che il giorno 11/02 è prevista una bonifica massiva di tutti i caratteri non validi pervenuti da subentro, compreso il vostro caso, che risolveranno i problemi di questa natura.
