### ISSUE TITLE
[3002] Consultazione: vedovanza\luogoEvento\codiceIstat

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#113]
buongiorno.

il servizio di consultazione non ritorna il codiceIstat del luogo di vedovanza.
un caso come esempio:
idSchedaSoggettoANPR: 5618492 - dppre - comune di Occhiobello

nel file di subentro il dato è stato passato così:
```xml
<vedovanza>
<datiMorteconiuge>
<dataEvento>2010-10-25</dataEvento>
<luogoEvento>
<comune>
<nomeComune>CENTO</nomeComune>
<codiceIstat>038004</codiceIstat>
<siglaProvinciaIstat> FE</siglaProvinciaIstat>
</comune>
</luogoEvento>
```

mentre, in fase di consultazione, la risposta è così:
```xml
<vedovanza>
<datiMorteconiuge>
<dataEvento> 2010-10-25+02:00</dataEvento>
<luogoEvento>
<comune>
<nomeComune>CENTO</nomeComune>
<siglaProvinciaIstat> FE</siglaProvinciaIstat>
</comune>
</luogoEvento>
```

Alessandro Monopoli ADS

**Comment by ccontavalli** [comment]
Ho intanto modificato il messaggio per racchiudere l'XML tra:\`\`\`xml  e la chiusura \`\`\`, in modo che venisse formattato correttamente.

**Comment by gcarbonin** [comment]
Per motivi di natura prestazionale questi dati dei soggetti collegati alla scheda principale non vengono conservati in forma codificata
