### ISSUE TITLE
[5008] ws - rettifica comune di nascita per errore

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1130]
Comune di Bosia (CN) - subentrato

Per errore è stato modificato il comune di nascita ad un cittadino (con relativa attribuzione di codice fiscale errato). Da comune nascita BOSIA (corretto)  a comune nascita CORTEMILIA (errato).
Andando a rettificare nuovamente il comune per riportarlo al dato corretto, viene segnalato il seguente errore: "EN332 - Comune/provincia di nascita BOSIA (CN) inesistente o non valido alla data di nascita". 
In effetti in base alle tabelle ANPR dei comuni, il comune di BOSIA non esisteva alla data di nascita del cittadino, ma il cittadino è sempre stato registrato con questo comune di nascita e anche all'agenzia delle entrate risultava nato a BOSIA. L'estratto di nascita dice che il cittadino è nato a BOSIA.
Come possiamo riportarlo al dato originale?
Abbiamo anche provato ad effettuare l'annullamento dell'operazione di mutazione tramite WA ma risponde che non è possibile annullare una mutazione di dati anagrafici.

Il codice ANPR del cittadino è 23503265

In passato era già successo un problema simile con un altro comune e in seguito ad un vs intervento era stato possibile rettificare il dato.

**Comment by frmariani** [comment]
nell'xml del servizio 5008, deve essere inserito il nuovo  CF nelle "Generalità per ricerca" ed il vecchio CF nelle "Generalità da modificare"; in questo modo verranno invertiti i CF sia in ANPR che in Agenzia delle Entrate;
vi ricordo che l'operazione NON può essere effettuata dalla WEB APP di ANPR

**Comment by siscomanpr** [comment]
Grazie, il problema è risolto.
