### ISSUE TITLE
[5012] Annullamento parziale di scissione all'interno del comune

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1133]
Ambiente di TEST - Comune 004215
Sto provando ad effettuare degli annullamenti parziali sui cambi di residenza all'interno del comune.
- Famiglia composta da 5 individui.
- Effettuo una scissione con creazione di nuova famiglia di 4 componenti tra cui l'intestatario scheda che diventa intestatario anche nella nuova famiglia (Id.Operazione ANPR 18951109).
- Al termine del cambio imposto con la chiamata 5001 la parentela di intestatario scheda all'unico componente rimasto (Id.Operazione ANPR 18951111).
- Dopo gli accertamenti devo annullare il cambio a 2 dei 4 individui tra cui l'intestatario scheda.
- Effettuo la chiamata 5012 per l'intestatario scheda che viene effettuata correttamente (Id.Operazione ANPR 18951123) con l'indicazione della lista controllo per l'annullo parziale:
```
    <listaControlli>
      <controllo>
        <codice>RA</codice>
        <valore>1</valore>
      </controllo>
      <controllo>
        <codice>RP</codice>
        <valore>1</valore>
      </controllo>
    </listaControlli>
```
- Quando provo a effettuare la medesima chiamata per il secondo individuo (Id.Operazione ANPR 18951148) ottengo l'errore: 
```
      <errore>
        <codiceErroreAnomalia>999</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
      </errore>
```
Potete verificare a cosa sia dovuto il problema?
Ringrazio anticipatamente

**Comment by SAlberto** [comment]
Buongiorno,
ho fatto un'altra prova senza coinvolgere gli intestatari scheda ma riscontro lo stesso problema
[5005] Scissione di 4 individui effettuata correttamente - Id.Operazione ANPR 18952327
[5012] Annullamento per il primo individuo effettuato correttamente - Id.Operazione ANPR 18952348
[5012] Annullamento per il secondo individuo fallito con errore 999 - Id.Operazione ANPR 18952350

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando la vostra segnalazione.

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato l'anomalia, potreste riprovare?

**Comment by SAlberto** [comment]
Buongiorno, l'operazione è stata eseguita in modo corretto.
La ringrazio
