### ISSUE TITLE
Errore 999 Rimpatrio famiglia AIRE

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1135]
Buongiorno,
il comune di Agrigento deve far rimpatriare una famiglia aire (già iscritta presso la sua AIRE) nel suo comune.
Per far questo viene inviata una richiesta d'operazione 5001 tipo 5.
 In fase di conferma preliminare della richiesta viene restituito l'errore 999 "Operazione non effettuabile"

allego contenuto file xml:

<Richiesta5001 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://sogei.it/ANPR/5000mutazione">
  <testataRichiesta xmlns="">
    <idOperazioneComune>9768</idOperazioneComune>
    <codMittente>084001</codMittente>
    <codDestinatario>ANPR01</codDestinatario>
    <operazioneRichiesta>5001</operazioneRichiesta>
    <dataOraRichiesta>2019-02-08T10:25:00.0000213+01:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <protocolloComune>132</protocolloComune>
    <dataProtocolloComune>2019-02-06</dataProtocolloComune>
    <tipoInvio>PROD</tipoInvio>
    <dataDecorrenza>2019-02-06</dataDecorrenza>
    <nomeApplicativo>PEDemografici</nomeApplicativo>
    <versioneApplicativo>4.0</versioneApplicativo>
    <fornitoreApplicativo>Kibernetes</fornitoreApplicativo>
  </testataRichiesta>
  <famigliaConvivenza xmlns="">
    <idFamigliaConvivenzaComune>
      <idFamigliaConvivenzaComuneIstat>084001</idFamigliaConvivenzaComuneIstat>
      <idFamigliaConvivenza>FE0003704</idFamigliaConvivenza>
    </idFamigliaConvivenzaComune>
    <tipoScheda>5</tipoScheda>
  </famigliaConvivenza>
  <residenzaFamigliaConvivenza xmlns="">
    <tipoIndirizzo>1</tipoIndirizzo>
    <indirizzo>
      <cap>92100</cap>
      <comune>
        <nomeComune>AGRIGENTO</nomeComune>
        <codiceIstat>084001</codiceIstat>
        <siglaProvinciaIstat>AG</siglaProvinciaIstat>
      </comune>
      <frazione>VILLAGGIO PERUZZO</frazione>
      <toponimo>
        <specie>Via</specie>
        <codToponimo>1</codToponimo>
        <denominazioneToponimo>GELA</denominazioneToponimo>
        <toponimoFonte>2</toponimoFonte>
      </toponimo>
      <numeroCivico>
        <civicoFonte>2</civicoFonte>
        <numero>25</numero>
        <civicoInterno />
      </numeroCivico>
    </indirizzo>
    <dataDecorrenzaResidenza>2019-02-06</dataDecorrenzaResidenza>
  </residenzaFamigliaConvivenza>
  <datiDelProcedimento xmlns="">
    <numeroPraticaComune>2019-806</numeroPraticaComune>
  </datiDelProcedimento>
  <datiControllo xmlns="">
    <tipoMutazione>5</tipoMutazione>
    <tipoScheda>1</tipoScheda>
  </datiControllo>
</Richiesta5001>

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato e riscontrato un problema sulla mutazione residenza nel caso in cui viene trasmessa la famiglia con il solo identificativo comunale. 
Provvediamo subito alla risoluzione del problema. 
Intanto per consentirvi di portare a termine la pratica, vi suggeriamo di ripetere l'operazione trasmettendo per la famiglia anche l'identificativo ANPR (ossia  26184241).
Grazie per la segnalazione.

**Comment by gdurante72** [comment]
Grazie
