### ISSUE TITLE
Piano di 3 o 4 caratteri

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1136]
Ambiente di test
La richiesta id 18952963 (5001 di tipo 4) ha variato l'indirizzo di residenza della famiglia coinvolta assegnando all'attributo "piano" del numeroCivico il valore "1234".
ANPR ha recepito la richiesta.
Mi risulta che l'attributo del Piano ammetta al massimo 3 caratteri.
Osservo un comportamento che non so come interpretare da parte della WA che in modifica del dato presenta nella form il valore "1234" ma sullo stesso campo ha un controllo che accetta in input 3 caratteri.
Filipazzi - Maggioli

**Comment by amollicone1982** [comment]
Il campo piano è di 5 caratteri. Effettivamente sulla WA c'e' un controllo che ne fa inserire massimo 3.
Risolveremo subito

**Comment by bfilipazzi** [comment]
Nel file Specifiche di interfaccia 14012019.rar c'è il file numeroCivico.xlsx in cui il Piano è definito max 3.
Nel file SPECIFICHE_DI_INTERFACCIA_XSD_23112018.rar il Piano è definito max 5.
Mi son fatto ingannare dal file Excel.
Posso concludere che sia il file di Excel che il controllo della WA siano afflitti da un refuso e che il piano in realtà è max 5?
Grazie

**Comment by amollicone1982** [comment]
Si esattamente
