### ISSUE TITLE
Ricomparsa da irreperibilità [AEE95 operazione non effettuabile]

### ISSUE THREAD

**Issue by DemResana** [italia/anpr#1137]
Comune di Resana - ambiente di test - id operazione 14001650

Buongiorno

come da titolo dovrei iscrivere un cittadino per ricomparsa da irreperibilità. Il predetto cittadino era precedentemete residente nel Comune di Cassola (VI) (Comune subentrato in ANPR), ma era stato cancellato per irreperibilità dallo stesso Comune prima del subentro per cui non è presente in ANPR.
Ho provato ad iscriverlo via Web App con "Iscrizione per altri motivi - ricomparsa da irreperibilità" ottenedo l'errore AEE95. Il cittadino entra in un nucleo già esistente.

Come devo procedere.

Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera,
l'id operazione 14001650 non è presente in ambiente di test. Se il caso è tuttora senza soluzione le chiedo cortesemente di riprovare ed inviarmi il nuovo id operazione.
Grazie
N. Capozzi

**Comment by ncapozzi** [comment]
Non avendo più ricevuto alcun riscontro si chiude la issue
