### ISSUE TITLE
Errore 999 su mutazione famiglia

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1138]
Comune di Modena - Ambiente di produzione

Buongiorno,
tentando di registrare una mutazione famiglia per correggere il rapporto di parentela (da moglie a madre) del soggetto con idANPR 19261251 abbiamo l' errore:

Operazione non effettuabile (Codice: 999)

La mutazione dovrebbe avere decorrenza 22/10/2018 , data in cui il soggetto si è trasferito nella famiglia attuale.  

Grazie, saluti
Sonia Fiorini

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato e il caso. L'errore è dovuto ad una mutazione composizione scheda trasmessa il giorno 26-01-2019 in cui è stato erroneamente indicato per il soggetto MRBFNC39H46A772N un codice legame incongruente (ossia valido per la convivenza e non per la famiglia):
> 
<legameSoggetto>
     <tipoLegame>4</tipoLegame>
      <dataDecorrenza>2018-10-22+02:00</dataDecorrenza>
      <codiceLegame>2</codiceLegame>
      <progressivoComponente>18</progressivoComponente>
</legameSoggetto>
> 
Abbiamo già provveduto all'implementazione di un controllo bloccante che eviti quanto consentito; rilasceremo la fix a breve. Al momento per permettervi di concludere la pratica abbiamo sanato d'ufficio la situazione. Restiamo in attesa di una vostra verifica.

**Comment by sfmodena** [comment]
Buongiorno, siamo riusciti ad effettuare la mutazione, grazie. Chiudo la issue.
Sonia Fiorini
