### ISSUE TITLE
Rigetto parziale di migrazione di famiglia

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1139]
Ambiente di Test
Comune 100004

Migrazione di famiglia di 3 persone con servizio 5001 (id operazione ANPR 18949328).
A seguito dell'accertamento si deve rigettare parzialmente la migrazione perché 2 persone risultano residenti all'indirizzo e la terza no.
Riceviamo la risposta "EN351 : L'evento da annullare e' una mutazione famiglia/convivenza: non e' possibile specificare il parametro ripristino parziale 'RP'" (id operazione ANPR 18949766).

Cosa abbiamo sbagliato? Grazie
Filipazzi - Maggioli

**Comment by frmariani** [comment]
Come dettagliato nella risposta, al momento non è possibile il rigetto parziale del cambio di residenza di un'intera famiglia; il cittadino deve essere cancellato per ripristino posizione precedente.

**Comment by bfilipazzi** [comment]
Il comune di provenienza riceve una notifica?
Grazie.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
Si, riceve la notifica

**Comment by bfilipazzi** [comment]
Grazie
