### ISSUE TITLE
[WS 6001] - Certificazione Storica

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#114]
Nella certificazione storica ANPR, non è prevista la possibilità d'integrazione di eventi precedenti la data di subentro - eventi registrati nella banca dati comunale - con quelli presenti in ANPR dal subentro in poi.
Una soluzione potrebbe essere quella di prevedere un servizio di certificazione storica lato ANPR attraverso il quale il comune invia anche i dati storici non presenti in ANPR in un formato standard (codificato con xsd) che permette poi al sistema attraverso un merge di produrre un certificato ufficiale ANPR...

**Comment by gcarbonin** [comment]
Attualmente è possibile consegnare alla persona due certificati storici oppure un unico certificato PRODOTTO DAL SW ANAGRAFICO DEL COMUNE, ottenuto utilizzando : per la parte "ante subentro" , i dati del comune; per la parte successiva, i dati che ANPR rende disponibili in formato xml con il servizio 6001. La soluzione prospettata era gia' stata esaminata (e scartata) dal Ministero dell'Interno a fronte di una richiesta trasmessa dal comune
