### ISSUE TITLE
[5001] Internal server error ma operazione completata ???

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1140]
Ambiente di produzione, comune di Piacenza

lo stesso problema "internal server error" descritto nella issue #1126 accade nel comune di Piacenza tentando di perfezionare una mutazione di residenza (id ANPR 50122202).

E' per noi indispensabile che arrivi una risposta di operazione completata al fine di proseguire nell'applicazione locale con l'iter della pratica migratoria.

Cosa causa l'errore ? Potete provvedere a sistemarlo ?

Grazie

Gianrico Busa 
Maggioli Spa

**Comment by busaster** [comment]
Aggiungo che lo stesso problema nello stesso comune si presenta per l'operazione ID ANPR 45070891

**Comment by mttfranci** [comment]
Salve, le situazioni da voi descritte in effetti rientrano tutte nella casistica della issue #1126.

Per l'operazione 50122202, note indirizzo "UE:1266-§ISOLATO 90'"
Per l'operazione 45070891, note indirizzo "UE:3471-§ISOLATO 153"
Per l'operazione 45512518, note indirizzo "UE:6105-§ISOLATO 478'"

Nel primo pomeriggio avverrà la bonifica massiva #1128 che dovrebbe sanare il problema per il futuro.
