### ISSUE TITLE
[3002] Soggetto Già Unito Civilmente: motivoScioglimento '99'

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1141]
ambiente di PRODUZIONE - comune di PORTO MANTOVANO (MN)
idSoggettoANPR 35340119

il soggetto risulta con stato civile '8'
nei dati di scioglimento il web-service risponde con un motivoScioglimento '99' non presente nella tabella di riferimento (tabella 43)

segnalo per le verifiche del caso e gli eventuali aggiornamenti necessari.

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
al subentro, nel motivo scioglimento dell'unione civile, è stato inserito il valore errato '01' (anziche' 1), pertanto segnaliamo l'anomalia con il valore 99 "motivo scioglimento unione errato";
lo stato civile 8 "Stato libero a seguito di scioglimento dell'unione civile" è coerente con i dati presenti.

**Comment by AMonopoliADS** [comment]
ok. grazie.

non avevamo notato che il dato non fosse stato accettato al subentro.
probabilmente abbiamo seguito la logica di altre codifiche che pur avendo valori tabellari da '1' a 'n', vengono accettati solo con l'aggiunta dello zero (es. tabella 47)

immagino quindi che il codice '99' vada considerato - potenzialmente - come valore di ritorno di tutte le codifiche inviate erroneamente... e che quindi non prevedete aggiornamento delle tabelle di riferimento.

grazie.

**Comment by frmariani** [comment]
esattamente
