### ISSUE TITLE
Risposta5008 - Dati Consultabili

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1142]
Buongiorno,

Abbiamo effettuato alcune prove di mutazioni dati di un soggetto, in ambiente di TEST.
Un esempio è quello di modificare l'attributo del soggetto 'senza fissa dimora'.
Cercando di monitorare la lista degli operazioni eseguiti, questa mutazione non contiene nella Riposta5008 il valore del campo senzaFissaDimora <senzaFissaDimora>.
Domanda:  è possibile restituire nella Risposta5008 la lista dei cambiamenti fatti nella Richiesta5008, contenendo ogni campo con il suo valore(includendo i valori tipoMutazione), oppure avere la possibilita di consultare qual'è stata la Richiesta5008 fatta (per consultare i motivi di mutazione con i campi presenti)?
Nel caso di richieste Iscrizine e cancellazione le risposte rispettive contengono il blocco con datiIscrizione/datiCancellazione specificando il motivoIscrizione/motivoCancellazione. 
Esiste qualche modo di ottenere un simile informazione anche per le richieste di mutazione?

Grazie in anticipo,
Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by rvinzani** [comment]
Salve, stiamo rivedendo le risposte dei servizi al fine di ottimizzare il sistema. Prenderemo in esame la vostra richiesta.

**Comment by rvinzani** [comment]
Nella risposta sono presenti le informazioni relativi alla richiesta che l'ha generata (id comune, tipo richiesta etc.) e dai quali è possibile risalire ai dati modificati

**Comment by AlbanaCelepija** [comment]
Si, la risposta contiene la lista dei dati modificati tramite la richiesta.
Ma nel caso di mutazione "senza fissa dimora"  il blocco con i dati non risulta presente .
Esempio di richiesta:
>  
     <generalitaDaModificare>
		<generalita>
		    <codiceFiscale>
                        <codFiscale>xxxxxxxxxxxx</codFiscale>
                        <validitaCF>9</validitaCF>
                    </codiceFiscale>
                    <cognome>TodayCognome</cognome>
                    <nome>TodayNome</nome>
                    <sesso>F</sesso>
                    <dataNascita>2018-12-29</dataNascita>
                    <luogoNascita>
                        <comune>
                            <nomeComune>xxxxx</nomeComune>
                            <codiceIstat>xxxx</codiceIstat>
                            <siglaProvinciaIstat>xx</siglaProvinciaIstat>
                        </comune>
                    </luogoNascita>
                    <idSchedaSoggettoANPR>8413407</idSchedaSoggettoANPR>
		</generalita>
		<attributiSoggetto>
			<senzaFissaDimora>S</senzaFissaDimora>
			<soggettoCertificabile>2</soggettoCertificabile>
		</attributiSoggetto>
	</generalitaDaModificare>
        <datiControllo>
	        <tipoMutazione>01</tipoMutazione>
		<gestioneCF>3</gestioneCF>
	    </datiControllo>
La scheda viene aggiornata correttamente con il nuovo valore del senzaFissaDimora,
ma nella risposta5008 non viene riportato il tag  'attributiSoggetto' con i nuovi valori, quindi non si riesce a capire che cos'è stato modificato.
La risposta5008:
>

	<generalitaAttuali>
	    <codiceFiscale>
		<codFiscale>xxxxxxxxx</codFiscale>
		<validitaCF>9</validitaCF>
	    </codiceFiscale>
	    <cognome>TodayCognome</cognome>
	    <nome>TodayNome</nome>
	    <sesso>F</sesso>
	    <dataNascita>2018-12-29+01:00</dataNascita>
	    <luogoNascita>
		<comune>
		    <nomeComune>xxxxxxxxxx</nomeComune>
		    <codiceIstat>xxxxxxxxx</codiceIstat>
		    <siglaProvinciaIstat>xx</siglaProvinciaIstat>
		</comune>
	    </luogoNascita>
	    <idSchedaSoggettoANPR>8413407</idSchedaSoggettoANPR>
	</generalitaAttuali>

**Comment by rvinzani** [comment]
Nell'intervento previsto atto ad ottimizzare i servizi le risposte riporteranno solo l'esito della mutazione. Per recuperare le modifiche richieste è necessario quindi utilizzare la richiesta a cui si risale dai dati della testata della risposta.

**Comment by AlbanaCelepija** [comment]
Vi ringrazio per la risposta.
Esiste un servizio da parte di ANPR che restituisce la richiesta che è stata fatta fornendo l'idoperazioneANPR?
Dalla documentazione tecnica si può capire che utilizzando l'operazione 3003 si possono ottenere i dati di dettaglio di una o più richieste, ma nella risposta3003 si trova la risposta dell' operazione che stai cercando non la richiesta.
Essendo un Ente diverso dal comune non siamo in possesso delle richieste che sono state fatte, pur sapendo l'idoperazioneANPR che si può ottenere dalla testata della risposta.

**Comment by rvinzani** [comment]
Per il momento non è previsto che ANPR fornisca dati per scopi diversi dal recupero delle risposte non consumate e per richieste effettuate dallo stesso soggetto. Chiudo la issue. In caso di necessità di ulteriori chiarimenti si prega di aprire un'altra issue facendo riferimento a questa stessa.
