### ISSUE TITLE
Discrepanza tra cognome coniuge e cognome cittadino

### ISSUE THREAD

**Issue by MarcellaM** [italia/anpr#1143]
Buongiorno dal Comune di Alessandria,

vorrei sottoporvi la seguente casistica.

Il cittadino residente in Alessandria identificativo scheda attribuito da ANPR: 34412703 risulta correttamente coniugato con il cittadino, sempre residente in Alessandria, identificativo scheda attribuito da ANPR: 43311694.

Se consulto il cittadino ID 43311694 il suo cognome è correttamente composto da due elementi, mentre se consulto i dati di matrimonio della cittadina 34412703 il cognome e nome del coniuge risultano errati ovvero il secondo elemento del cognome risulta nel campo nome.

Potete verificare?

Grazie

**Comment by frmariani** [comment]
il matrimonio dei cittadini, non risulta "riconciliato", pertanto i dati anagrafici dei coniugi vengono riportati nella consultazione così come sono stati acquisiti;
la riconciliazione è fallita proprio perchè i dati del coniuge non sono stati inviati correttamente;
per effettuare la riconciliazione, per prima cosa devono essere corretti i dati del coniuge del soggetto 34412703, con una successiva operazione di mutazione dei dati del matrimonio, si potrà effettuare la riconciliazione indicando l'idanpr del coniuge o il suo CF.
per essere seguita nelle operazioni, può inviarmi un recapito telefonico

**Comment by frmariani** [comment]
ho verificato che la riconciliazione è stata effettuata. chiudo la issue
