### ISSUE TITLE
Richiesta chiarimenti su subentro, miei residenti assegnati ad altro comune anpr

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1145]
Il comune 036019 subentra il 4 febbraio in ambiente produzione.
Dall'elenco degli ID ANPR assegnati ad ogni cittadino residente o aire, vedo in maniera empirica ordinandoli, che 117 soggetti erano già presenti in ANPR, perchè il numero dell'ID è basso. A un certo punto invece l'ID ad ogni riga fa un +1 e quindi intuisco che si tratta di nuovi soggetti per ANPR.

Nell'elenco webapp POSIZIONI DUPLICATE COMUNI DIVERSI CON DATA Più RECENTE, abbiamo 4 persone.
L'altro elenco webapp POSIZIONI DUPLICATE COMUNI DIVERSI CON DATA Più REMOTA è vuoto.
I due elenchi non sono quindi di aiuto per capire questi 117 casi.

Quindi 117 soggetti dovrebbero rientrare credo, in queste casistiche:

1. soggetto già presente in ANPR come cancellato da altro comune alla data del mio subentro. non mi comporta problemi e saranno la grande maggioranza dei casi probabilmente.

1. soggetto iscritto in ANPR in un altro comune.Ll'altro comune ha indicato una  data decorrenza residenza più vecchia della mia .  esempio cittadino 19245310  residente nel comune 036019 con data decorrenza residenza 02-01-2017. nel nostro comune file di subentro, indichiamo data decorrenza residenza 19-01-2019.

1. il contrario, ovvero nel nostro comune risulta residente con data decorrenza più vecchia di quella presente in altro comune ANPR. esempio cittadino 46315715 già residente nel comune 036013, con data decorrenza residenza 02-02-2019. nel nostro file di subentro ha data decorrenza residenza 15-11-2007.

Nel caso 2 e 3 riportati come esempio, ANPR ha deciso automaticamente cosa fare senza creare duplicati.

Nel caso 2, vedo il soggetto residente nel comune che stiamo subentrando.
Ignoro se viene generata una notifica di mutazione di residenza per il comune 036023. Me lo potete chiarire?

Nel caso 3, vedo il soggetto residente nell'altro comune.
In questo caso non ho nessun riscontro da ANPR che questo cittadino non è stato riconosciuto come mio residente. Anzi figura negli esiti con l'id assegnato, ma manca una colonna che mi informi che non è stato riconosciuto come mio residente.

E' vero che la gran parte di questi casi vengono risolti tramite gli APR4 che stanno "girando" tra i comuni. Però mi sembra strano avere un elenco di residenti apparentemente positivo, quando qualcuno in realtà non risulta mio residente. Ignorando se avete già ragionato su questa problematica, vi segnalo questi esempi.

**Comment by cmigliardi** [comment]
Buongiorno,  riguardo ai 117 soggetti si tratti di schede riconciliate (quindi Anpr utilizza l'ID anpr già attribuito per questo è "più basso" come da Lei riscontrato). Per i 4 soggetti duplicati, dovete sentire i comuni che non hanno ancora effettuato la cancellazione. (Dovranno effettuare una cancellazione per doppia iscrizione).    
caso 2 - il soggetto (se lo interroga dal sito web di anpr) è entrato  con due subentri di due diversi comuni poi però il primo comune ha effettuato correttamente la cancellazione. poi ci risultano due rettifiche delle date che ha fatto il secondo comune. (al momento è a Fiorano Modenese )  
caso 3  - attualmente è residente a Maranello proveniente da Maranello - è stata fatta una mutazione di residenza in data    5 febbraio - con decorrenza 2 febbraio.   (la notifica che viene inviata è N010.)

**Comment by MarcoMigliori** [comment]
chiarito telefonicamente
