### ISSUE TITLE
[102] 999 Operazione non effettuabile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1146]
Ambiente di Test, comune di Poggio a Caiano

tentando di iscrivere un soggetto in convivenza con il servizio 1002 si ottiene l'errore in oggetto.
ID operazione ANPR : 18970519

Qual è la causa ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by asqueglia** [comment]
Buongiorno, è stata rilasciata proprio ieri una fix sul servizio di iscrizione che risolve il problema segnalato. Potete riprovare ?

**Comment by busaster** [comment]
Confermo che dopo l'aggiornamento la chiamata è andata buon fine.
Grazie
