### ISSUE TITLE
Errata esposizione data di nascita coniuge

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1147]
Buongiorno,
Il cittadino con codice ID ANPR 35287791, del comune di Roccapalumba, risulta essere coniugato con un cittadino nato il 01/06/1975 (non presente in ANPR). Malgrado il dato sia stato inserito correttamente, richiamando i dati di matrimonio del cittadino viene visualizzata come data di nascita del coniuge 31/05/1975.
Provando ad effettuare la rettifica dei dati di matrimonio la data di nascita del coniuge viene visualizzata correttamente ovvero 01/06/1975 e confermando i dati, la consultazione risulta sempre errata (31/05/1975).

Giovanni Durante
Kibernetes

**Comment by frmariani** [comment]
abbiamo avuto un problema con il time zone della data di nascita di soggetti non in ANPR, come nel caso del coniuge del soggetto;
il problema è stato risolto, potete riprovare.
Grazie per la segnalazione.

**Comment by gdurante72** [comment]
verificato ed il problema non si ripresenta

Grazie
