### ISSUE TITLE
cognomi/Nomi e caratteri non validi

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1148]
Nel file tipodato.xsd i campo "cognome" e "nome" del tipoGeneralita sono di classe "alfabeticoNomiCognomi".
Questa classe estende la "alfanumericobase" la quale tra i caratteri ammessi ha anche caratteri numerici.

Ho fatto alcune prove.
Da webapp se tento di inserire dei numeri nei campi cognome e nome vengo fermato dall'interfaccia con un errore del tipo "Il campo Cognome in Generalita contiene dei caratteri non validi"-
Da servizio 1002 se provo ad usare caratteri numerici il servizio va in errore " Internal Error (from client)".

Potete dirmi con precisione quali sono i caratteri ammessi per i campi cognome/nome ed adeguare gli XSD di conseguenza ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, i numeri non sono accettati.
Il problema è stato corretto a gennaio con la release 4.1.24, legata alla issue #1036.
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
Stiamo aggiornando anche i wsdl pubblicati sul portale.

**Comment by mttfranci** [comment]
Anche gli XSD pubblicati sul portale ANPR dovrebbero essere aggiornati.
Saluti

Assistenza ANPR
