### ISSUE TITLE
Messaggio "Comune non competente"

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1149]
Ambiente di Produzione
IdOperazione ANPR: 51159151

ANPR, ritorna, per l'operazione con l'ID segnalato sopra, il messaggio EN074 "Incongruenza dati anagrafici: il codice ISTAT del comune competente per il soggetto non coincide con quello specificato nella richiesta".
Abbiamo controllato sul file xml contenente la richiesta e nel campo "CodMittente" si vede effettivamente il codice Istat del Comune coinvolto, così come, entrando su ANPR, la persona all'interno della richiesta risulta essere residente nel Comune.

A cosa è dovuto questo messaggio?
Ringraziando in anticipo per la disponibilità.

Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera,
potete riprovare ad eseguire l'operazione per favore?
N. Capozzi
