### ISSUE TITLE
Visualizzazione componenti nucleo familiare

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#115]
Dopo aver ricercato un nominativo tramite la Web App e aver utilizzato il comando "Elenco componenti" della pagina riguardante "Famiglia/convivenza", abbiamo notato che il nome dell'intestatario scheda viene replicato 2 volte, e che la seconda volta viene gli viene attribuita la qualifica di "Tutore"; ciò succede anche se la persona è l'unico componente della famiglia.
(ES: Identificativo scheda attribuito da ANPR: 2511796)

Come mai? E' corretto che sia così?
Questa visualizzazione potrebbe creare confusione, soprattutto se utilizzata da soggetti esterni

Grazie,
Patrizia Saggini - Comune di Anzola dell'Emilia

**Comment by gcarbonin** [comment]
Non posso verificare in quanto l'identificativo indicato non sembra corretto.  Ho provato ad interrogare un  altro identificativo (4368118)  ed ho verificato che si tratta di un errore nella costruzione del file di subentro: la stessa persona è stata indicata nei dati della famiglia anche come tutore. E' quindi normale che sia presente due volte.
