### ISSUE TITLE
Disallineamento tra AE e ANPR per luogo di nascita

### ISSUE THREAD

**Issue by DemograficiDianomarina** [italia/anpr#1150]
Un nominativo(ID SOGG ANPR 37953804) è migrato ad ANPR con il luogo di nascita (descrizione) sbagliata per l'anno in cui è nato (ROBURENT anzichè ROBURENTO) a seguito del rilascio della CIE (dove è uscito in automatico il comune giusto ROBURENTO) ci siamo ritrovati in ANPR (senza aver noi fatto alcuna mutazione di dati) il comune giusto ROBURENTO. Il codice fiscale a seguito di ciò non è cambiato ed interrogando il SIATEL risulta sempre nato a ROBURENT (denominazione sbagliata per l'anno di nascita).  Dalla web app nella voce "risoluzione disallineamenti AE......" non mi trova disallineamenti e non mi permette di fare nulla; idem dal SIATEL a seguito del subentro in ANPR è inibita ogni modifica. La locale Agenzia delle Entrate manda il cittadino da noi comunicando che essendo subentrato in ANPR solo il comune può provvedere a sanare la situazione..sapete indicarci come possiamo risolvere. Grazie

**Comment by rvinzani** [comment]
Salve, il comune è censito nelle tabelle di ANPR e di Agenzia Entrate con lo stesso codice catastale e le due differenti denominazioni.
Però, mentre ANPR utilizza la denominazione corrispondente rispetto alla data di nascita, Agenzia Entrate non gestisce lo storico. 

![image](https://user-images.githubusercontent.com/26482893/52967070-300a9400-33a9-11e9-92d3-58679716b02d.png)
Dalla tabellina si evince che il 5/2/1942 (data di nascita del soggetto) la corretta denominazione è ROBURENTO. 
Per il momento non c'è possibilità di sanare la situazione anche se Agenzia Entrate sta predisponendo un intervento a tale scopo

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa,
