### ISSUE TITLE
[5001] data decorrenza non congruente

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1152]
Ambiente di produzione, comune di Portogruaro

cerchiamo di spostare nel nostro comune una famiglia monocomponente proveniente da altro comune subentrato.
Per farlo usiamo il servizio 5001.
Veniamo però bloccati dall'errore "EN237 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata"
ID ANPR : 46387979
Le date ci sembrano però coerenti, infatti prima della chiamata il soggetto risulta residente nell' altro comune dal 26/04/2018 e noi usiamo come decorrenza 15/12/2018.
Qual è la causa del blocco ?

Grazie
Gianrico Busa 
Maggioli Spa

**Comment by frmariani** [comment]
Avrei bisogno di parlare con Lei, può inviarmi un riferimento telefonico ?

**Comment by busaster** [comment]
se mi lascia il suo indirizzo email glielo mando

**Comment by frmariani** [comment]
frmariani@sogei.it

**Comment by frmariani** [comment]
il malfunzionamento è dovuto ad un problema tecnico che abbiamo prontamente rimosso, potete riprovare  l'operazione

**Comment by busaster** [comment]
Abbiamo provato la mutazione dal cliente e si è conclusa con esito positivo.
Grazie
