### ISSUE TITLE
Morte del primo coniuge antecedente alla data del secondo matrimonio

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1153]
Produzione - Comune di Catania (087015)
idOperazioneANPR 51427238
I dati anagrafici della richiesta contengono i dati di due coniugi del soggetto, il precedente coniuge deceduto e l'attuale coniuge vivente.
Non abbiamo capito perché la richiesta è respinta con l'errore "EN315 La data di morte @ e' inferiore alla data del matrimonio @".
Grazie.
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buonasera, 
in generale con i ws di ANPR le sezioni “matrimonio” e “vedovanza”  (o “annullamento cessazione matrimonio”) comunicate con una sola richiesta devono essere congruenti tra loro ossia  riferite allo stesso matrimonio.
Nel caso segnalato, con l’iscrizione è  possibile trasmettere i dati del matrimonio e della vedovanza del primo matrimonio oppure, posto che ANPR non gestisce i dati storici, solo i dati del secondo matrimonio. Utilizzando la prima soluzione i dati del secondo matrimonio possono essere comunicati  successivamente con una mutazione tutti i dati (ws 5008 – codice mutazione 12).

**Comment by bfilipazzi** [comment]
Grazie
