### ISSUE TITLE
ANOMALIA RILASCIO CIE (già aperta con issue #1112)

### ISSUE THREAD

**Issue by ComuneSegrate** [italia/anpr#1154]
Buongiorno, mi scuso se non ho potuto fornire un riscontro più veloce in merito alla issue #1112; purtroppo il cittadino in questione non risulta presente nel sistema cieonline, il risultato della ricerca, dopo aver digitato il suo codice fiscale, è la seguente: la ricerca non ha prodotto risultati.
La ricerca è stata fatta in data odierna.

Grazie.
Mario Ubbiali

**Comment by rvinzani** [comment]
Avete verificato di inserire come dati di residenza il comune di Segrate e non ad esempio il comune di nascita o di rilascio della CIE?

**Comment by ComuneSegrate** [comment]
Oggi ho riprovato personalmente e ho trovato il cittadino, era già presente il dato sul Comune di residenza ho messo solo il codice fiscale. Ora è tutto ok.

Grazie per la collaborazione
Mario Ubbiali
