### ISSUE TITLE
Internal error (from server) - 6001

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1155]
La chiamata al servizio 6001 con id comunale idOperazioneComune JD122840 e codice mittente codMittente 075052 ottiene in risposta l'errore "Internal Error (from server)".
Potete aiutarci a capire la causa?
Grazie.
Filipazzi - Maggioli.

**Comment by mttfranci** [comment]
Salve, stiamo verificando il problema.

**Comment by mttfranci** [comment]
Dovrebbe essere possibile riprovare.
Saluti
Assistenza ANPR

**Comment by bfilipazzi** [comment]
Informo il cliente. Grazie.

**Comment by bfilipazzi** [comment]
Il cliente riferisce che è risolto.
Grazie.
