### ISSUE TITLE
ERRORE MUTAZIONE DA COMUNE DI MILANO

### ISSUE THREAD

**Issue by COMUNEPOGLIANO1** [italia/anpr#1156]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.
COMUNE DI POGLIANO MILANESE
Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:
-<con:Richiesta3002 xmlns:con="http://sogei.it/ANPR/3000consultazione" xmlns:n="http://sogei.it/ANPR/3000consultazione" xmlns:risp="http://sogei.it/ANPR/rispostaComune" xmlns:anpr="http://sogei.it/ANPR/vocabolario3000consultazione" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sogei.it/ANPR/3000consultazione C:\Users\Desktop\xsdnew\wsdl3000\3000consultazione.xsd">
- <testataRichiesta>
  <idOperazioneComune>1108993</idOperazioneComune> 
  <codMittente>015176</codMittente> 
  <codDestinatario>ANPR01</codDestinatario> 
  <operazioneRichiesta>3002</operazioneRichiesta> 
  <dataOraRichiesta>2019-02-16T21:18:26.1343259</dataOraRichiesta> 
  <tipoOperazione>C</tipoOperazione> 
  <tipoInvio>PROD</tipoInvio> 
  <nomeApplicativo>CIVILIANEXT</nomeApplicativo> 
  <versioneApplicativo>1.0</versioneApplicativo> 
  <fornitoreApplicativo>DEDAGROUP</fornitoreApplicativo> 
  </testataRichiesta>
- <criteriRicerca>
  <tipoScheda>2</tipoScheda> 
  <identificativoANPR>16579289</identificativoANPR> 
  </criteriRicerca>
- <datiRichiesta>
  <schedaAnagraficaRichiesta>1</schedaAnagraficaRichiesta> 
  <dataRiferimentoRichiesta>2019-02-16</dataRiferimentoRichiesta> 
  <datiAnagraficiRichiesti>1</datiAnagraficiRichiesti> 
  </datiRichiesta>
  </con:Richiesta3002>
```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by mttfranci** [comment]
Salve, il testo della issue sembra non essere stato completamente personalizzato rispetto al template.
Potreste cortesemente rimuovere le parti non utili e fornire qualche altro dettaglio?
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
In assenza di riscontro chiudiamo la issue. In caso il problema non sia stato risolto vi preghiamo di riaprirla o di aprirne una nuova
