### ISSUE TITLE
WEBAPP PRESUB - CONSULTAZIONE AE : Esito AE: Operazione non effettuabile (Codice 95)

### ISSUE THREAD

**Issue by FulvioDeda** [italia/anpr#1157]
Per il comune di Valenza cod istat 6177 nella WEBAPP di PRESUBENTRO i consultazione AE inserendo cf del sindaco ho questo errore. Potete verificare?
Grazie

**Comment by FulvioDeda** [comment]
ho provato anche a fare una Mutazione tutti i dati , ma oltre all'errore precedente mi da quest'altro:
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-02-19 10:48:32 , idOperazioneANPR 9976229 (Codice: EN527)

**Comment by cmigliardi** [comment]
Buonasera,  in ambiente di pre-subentro se dall'area consultazione - scegliete consultazione AE - e digitate il cf del sindaco (a parte che non riesco a vedere l'errore che prendete)  anticipo che AE non ha dietro l'intero archivio quindi è possibile che non si trovi il cf.  se vuole può inviarmi più dettagli al mio indirizzo di posta    cmigliardi@sogei.it   - grazie
