### ISSUE TITLE
Indirizzi con sistema metrico

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1158]
Abbiamo verificato che al momento del subentro diverse famiglie residenti agli indirizzi extraurbani (strade provinciali e statali) hanno perso il numero civico (sistema metrico).
Abbiamo più volte sollecitato la nostra software house, ma pare che loro non siano in grado di risolvere il problema.
Chiedevo se fosse possibile estrarre da Anpr l'elenco delle famiglie interessate in formato csv sul quale eventualmente inserire un colonna da popolare con il civico, da far successivamente recepire da ANPR?
Grazie.

**Comment by cmigliardi** [comment]
Buongiorno, 
ci può inviare uno o due casi specifici così da poter analizzare il dettaglio? grazie 
se vuole può inviarmi una email    cmigliardi@sogei.it

**Comment by Finalmentesubentrati** [comment]
1) GRGMHL66E04A225Q

Identificativo scheda attribuito da ANPR: 18866675

2) DRNDTL77H51A225I ANPR - Consultazione

Identificativo scheda attribuito dal Comune: 34483

Il giorno mer 20 feb 2019 alle ore 10:26 cmigliardi <
notifications@github.com> ha scritto:

**Comment by cmigliardi** [comment]
Mi scusi, ma Le debbo ricordare di non rendere visibili dati di cittadini - per questo l'avevo invitata ad inviarmi una email. - per il resto stiamo verificando  -

**Comment by cmigliardi** [comment]
poiché siamo in contatto vi email   - come in accordi - chiudo la issue
