### ISSUE TITLE
[3002] Ricerca Nazionale a 0

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1159]
Ambiente di Test
ID Operazione ANPR: 18989683

Buongiorno,
eseguendo delle ricerche di prova su una persona che sappiamo essere duplicata (in due comuni diversi, il nostro e un altro), mettendo ricercaNazionale a 0 e specificando il ComuneResidenza (il nostro), ci vengono lo stesso restituite entrambe le anagrafiche.

Potete verificare?
Grazie

**Comment by mttfranci** [comment]
Salve, al momento il servizio è stato tarato per restituire comunque l'elenco dei soggetti quando viene fatta una ricerca per identificativo ANPR o codice fiscale (come è il caso della vostra operazione).
Questo avviene anche per fornire supporto nella risoluzione di casi anomali (Nel caso specifico c'è una doppia iscrizione che andrebbe sanata).
Detto questo, github ha anche lo scopo di recepire suggerimenti, voi ritenete sia preferibile comunque rimuovere il risultato se non residente nel comune indicato?
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Buongiorno,
il consiglio che crediamo di poter dare è di restituire quando indicato il comuneResidenza (e ricercaNazionale 0) solamente i residenti di tale comune, indipendentemente dai filtri di ricerca indicati.
Qualora si ritenesse necessario ottenere tutte le persone, come nel caso della risoluzione di casi anomali/individui duplicati, crediamo sia sufficiente indicare ricercaNazionale a 1.

**Comment by bfilipazzi** [comment]
Concordo col suggerimento di SAlberto

**Comment by mttfranci** [comment]
Il comportamento verrà modificato, appena disponibile ve lo notificheremo.

**Comment by mttfranci** [comment]
Salve, dovreste poter riprovare.
Adesso il risultato dovrebbe essere comunque filtrato se specificato il comune di residenza.

**Comment by mttfranci** [comment]
Grazie del riscontro.
Saluti
