### ISSUE TITLE
[Test subentro] Dati da inserire nel file APR

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#116]
Buongiorno,
in attesa che ci vengano inviate le credenziali per accedere all'ambiente di test, stiamo preparando i dati del comune di Bistagno (AL) da inserire nel file APR per il subentro in ANPR. 
A tal proposito avrei bisogno di capire se i dati (schede) da inviare sono solo quelli relativi ai "residenti vivi", escludendo quindi tutti i cittadini deceduti, emigrati, aire, irreperibili, temporanei.
Grazie.

Bistagno (AL)
Codice ISTAT: 006017

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Buongiorno. Le credenziali vengono trasmesse ai comuni con circa due mesi di anticipo rispetto alla data indicata per l'avvio dei test, che, nel caso specifico, e' ottobre 2017. Il comune per altro ha indicato come fornitore del SW anagrafico una società che ha gia' eseguito molti test del subentro e le sue domande mi sembrano strane. In ogni caso occorre inviare tutte le schede dei residenti nel comune non cancellate alla data del subentro,
