### ISSUE TITLE
Cittadino nato in SERBIA da rettificare in nato in JUGOSLAVIA

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1160]
Comune di AOSTA produzione

Buongiorno,

la questura ci richiede di rettificare il luogo di nascita del cittadino Id Scheda Sogg Anpr43794103 da SERBIA a JUGOSLAVIA.

Con una operazione di Mutazione Tutti i dati inseriamo quindi come comune di nascita JUGOSLAVIA legato alla nazione NON ATTRIBUIBILE codice 998 e codice fiscale Z118.

Abbiamo l'anomalia

1 Errore Anpr Cod: AEE95 - Operazione non effettuabile

Come possiamo procedere?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
JUGOSLAVIA deve essere riportato nel campo <descrizioneStato>, nella località indicate la città
Inoltre il campo codiceFiscale nelle generalità da modificare non deve essere valorizzato. Il cittadino interessato dovrebbe essere informato che, cambiando il codice catastale dello stato di nascita, Agenzia Entrate gli attribuirà un nuovo CF collegato al precedente.

N. Capozzi

**Comment by RBiasi** [comment]
Il codice istat sarà 998 corretto?

**Comment by ncapozzi** [comment]
Corretto
                    descrizioneLocalita = es. BELGRADO
                     descrizioneStato = JUGOSLAVIA
                     codiceStato = 998

**Comment by RBiasi** [comment]
Anche a seguito modifiche riscontriamo la stessa anomalia. 

Le invio il file xml via mail grazie
