### ISSUE TITLE
Sommario prossima minor version 5.3-RC

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#1161]
Forniamo qualche dettaglio sui principali interventi che saranno contenuti nella versione 5.3 di ANPR, già annunciata nella roadmap [https://github.com/italia/anpr/blob/master/src/change-management/roadmap.md]

(Requirement) Refactor servizio di consultazione/estrazione
•	I servizi 3003 e 3007 vengono spostati nella famiglia 4000. Il servizio 3005 nella famiglia 7000.

I servizi 3003 e 3007 potranno continuare ad essere usati per quanto riguarda le richieste singole.
Le richieste multiple invece dovranno essere inoltrate tramite un nuovo servizio :

**_4005 – Richieste_asincrone_**

![image](https://user-images.githubusercontent.com/29305782/53184600-a1428500-35fd-11e9-9777-aae1ded58207.png)

**Richiesta servizio 4005**

Questo servizio permetterà di veicolare sia la richiesta di elaborazione che la verifica stato della stessa tramite i due elementi alternativi :
-	Elaborazione
-	verificaStato

![image](https://user-images.githubusercontent.com/29305782/53184639-b0c1ce00-35fd-11e9-9250-c3bb0f9cb9b5.png)

Nel caso della richiesta elaborazione sarà possibile specificare il livello di dettaglio che si desidera : 
-	ID = Solo ID delle operazioni (in modo simile al 3007)
-	RICHIESTA = ID e richiesta
-	RISPOSTA = ID e risposta (in modo simile al 3003)
-	TUTTO = ID, richiesta e risposta (Per le notifiche il comportamento sarà uguale alla modalità RISPOSTA in quanto le notifiche non hanno sia richiesta che risposta)

UPDATE 14.05.2019 - In caso di richiesta relativa a notifiche (statoLavorazione = 7,8,9 e/o operazioneRichiesta N***), il comportamento sarà equivalente alla modalità risposta anche qualora venga indicato il livello di dettaglio "TUTTO" ( #1313 )

**Risposta servizio 4005**

La risposta avrà, come di consueto, una sezione per l’esito positivo e una per l’esito negativo.

![image](https://user-images.githubusercontent.com/29305782/53184685-c3d49e00-35fd-11e9-9240-4e97081c3310.png)

La sezione più significativa della risposta è l’elenco risposte : 

![image](https://user-images.githubusercontent.com/29305782/53184719-d058f680-35fd-11e9-8181-e720e8e96180.png)

In base al dettaglio richiesto verranno popolate la sezione della richiesta e risposta (e i relativi formati, in generale compresso). 

Per quanto riguarda il servizio 3005, al momento del passaggio definitivo alla versione ANPR02, ne terminerà il supporto e dovrà essere usato esclusivamente il servizio 7002.

[UPDATE 18.03.2019 - Vedere il messaggio con le nuove informazioni sul servizio]

**Comment by Eduardo1977** [comment]
Buongiorno, non mi è chiaro cosa si intende con "I servizi 3003 e 3007 potranno continuare ad essere usati per quanto riguarda le richieste singole". Significa, ad esempio, che il 3003 non potrà più essere utilizzato per ricercare un certo tipo di operazioni (1001, 1002, ...) avvenute in un dato intervallo di tempo ? Cioè il 3003 e 3007 non potranno essere usati se la risposta prevede più risultati da restituire? Grazie

**Comment by ANPRCdMI** [comment]
Buongiorno
in merito all'argomento esposto, vorremmo chiedere alcuni chiarimenti.
Al momento le nostre elaborazioni, sincrone, prevedono l'esecuzione del servizio 3007 e alla risposta l'esecuzione dei servizi 3003 per ogni notifica ricevuta.
Se abbiamo capito bene, con la nuova release, dovremo chiamare un 4005 di richiesta (ex 3007) e successivamente un 4005 di verificaStato: la domanda è:  dopo quanto tempo può essere lanciato il secondo servizio 4005 di verifica? 
Altra domanda: quando saranno disponibili la documentazione e wsdl/xsd del nuovo servizio? 
Grazie 
Raffaella
S.I. per Comune di Milano

**Comment by mttfranci** [comment]
Il comportamento previsto è quello che avete descritto.
La documentazione sarà integrata dopo aver terminato di analizzare i vostri commenti, presumibilmente nel corso della prossima settimana.
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Buongiorno,
mi associo alla domanda di @ANPRCdMI, quando verranno rilasciati i wsdl e xsd del servizio 4005?

Ringrazio anticipatamente

**Comment by mttfranci** [comment]
Salve.
Dopo una serie di verifiche ecco la definizione del servizio 4005. 
[wsdl4000-5.3-RC.zip](https://github.com/italia/anpr/files/2957496/wsdl4000-5.3-RC.zip)

Rispetto alla prima versione pubblicata è stata fatta qualche modifica ad alcuni tipi di richiesta e risposta : 

![richiesta](https://user-images.githubusercontent.com/29305782/54212814-b0717000-44e3-11e9-9e16-8266cac6161e.jpg)

![risposta](https://user-images.githubusercontent.com/29305782/54212831-b7987e00-44e3-11e9-8132-90db867e8a8e.jpg)

Inoltre nel 3003/3007 per la ricerca con dati soggetti verrà aggiunta anche la possibilità di effettuare la ricerca per idSchedaSoggettoANPR

**Comment by mttfranci** [comment]
Salve, ci scusiamo per il ritardo nella risposta.
Il servizio 4005 sarà disponibile da domani mattina in test comuni e presubentro.
Nel corso della settimana verrà reso disponibile anche in produzione.

Il comportamento dei servizi 3003/3005/3007 cambierà solo invocandoli con il codDestintario ANPR02 (in tal caso verrà restituito il codice EN379 se si provano a usare le funzionalità deprecate nella nuova versione).
Per tutto il periodo di supporto alla versione ANPR01 sarà possibile utilizzarli nella precedente modalità.
Come descritto nel documento del [Change management](https://github.com/italia/anpr/blob/master/src/change-management/change-management.md) la versione ANPR01 sarà supportata in ogni ambiente per 3 mesi dal rilascio della versione 5.3.0 di questa settimana.

I WSDL sono stati aggiornati, in attesa di pubblicarli sul portale di ANPR eccoli : 
[wsdl4000-5.3-RC1.zip](https://github.com/italia/anpr/files/2979087/wsdl4000-5.3-RC1.zip)

Sono state apportate alcune modifiche alla definizione di richiesta e risposta.

Ecco la nuova Richiesta del 4005 : 
![image](https://user-images.githubusercontent.com/29305782/54544642-5a4b7380-49a0-11e9-9f36-79a50432824f.png)

In particolare la sezione per richiedere una nuova elaborazione : 
![image](https://user-images.githubusercontent.com/29305782/54544713-78b16f00-49a0-11e9-9fdb-20f5b2670e22.png)

E la Risposta del 4005 : 
![image](https://user-images.githubusercontent.com/29305782/54544762-9088f300-49a0-11e9-8221-317bff7de459.png)

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Salve.
Il nuovo servizio 4005 è disponibile anche in ambiente di produzione dal 21 Marzo.
In base agli accordi presi con il processo di Change Management, da oggi partano i 3 mesi di supporto alle precedenti modalità (ANRR01).
Quindi la data ultima per adeguarsi alle variazioni considerate non retro compatibili introdotte con la versione 5.X sono : 
19 Giugno 2019 - Ambienti di test / presubentro
26 Giugno 2019 - Ambiente di produzione

Potete fare riferimento alle issue #1031,  #1077, #1079. #1087 per alcune informazioni sulle altre implementazioni.

Siamo a disposizione per ogni ulteriore chiarimento.
Cordiali saluti

Assistenza ANPR

**Comment by busaster** [comment]
Domanda : nel tipo dato tipoVerificaStato4005 è definito anche il campo obbligatorio progressivo.
Qual è il suo significato ? Come lo dobbiamo gestire ?

**Comment by mttfranci** [comment]
Salve,
Serve a gestire eventuali forniture divise in più parti.
Va inizialmente valorizzato a "1", poi nella risposta, qualora l'elaborazione sia terminata, avrete il totale delle porzioni porzioni di risposta.
In generale non ci aspettiamo che la risposta venga spezzata, ma abbiamo deciso di prevedere l'interfaccia in modo flessibile.

**Comment by busaster** [comment]
Sarebbe possibile nell'oggetto tipoRicercaElenchiRichieste avere anche la possibilità di filtrare le sole operazioni fatte via webApp ? Basterebbe probabilmente un filtro su "id operazione comune da.. a.." che andrei ad impostare con 0.

**Comment by mttfranci** [comment]
E' stata aggiunta nell'ultima versione (5.3.5) la possibilità di interrogare per id soggetto anpr le richieste per soggetto 3003/3007 (come anticipato nella issue #1234).
E' possibile usare questi WSDL :
[wsdl3000-5.3-RC1.zip](https://github.com/italia/anpr/files/3068019/wsdl3000-5.3-RC1.zip)

**Comment by busaster** [comment]
ok, è utile ma in altro contesto. La mia richiesta è dettata dall'esigenza di  verificare a fine giornata quali operazioni sono state eseguite con la webapp e non con i WS per proporre agli operatori automaticamente un elenco di allineamenti che dovrà fare nella base dati locale.

**Comment by mttfranci** [comment]
Certo, stiamo valutando tale richiesta. il messaggio precedente era una nota indipendente dalla vostra domanda.
Saluti

Assistenza ANPR

> ok, è utile ma in altro contesto. La mia richiesta è dettata dall'esigenza di verificare a fine giornata quali operazioni sono state eseguite con la webapp e non con i WS per proporre agli operatori automaticamente un elenco di allineamenti che dovrà fare nella base dati locale.

**Comment by busaster** [comment]
scusate, non avevo inteso.
Grazie
