### ISSUE TITLE
[3002] ANPR02 e ricerca con filtro comune

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1162]
Ambiente di test, comune di Poggio a Caiano

Ho volutamente fatto una ricerca 3002 per un cittadino esistente per codice fiscale usando come filtro su comune residenza un comune non esistente.
Mi aspettavo un errore ma la ricerca invece ha ritornato i dati del cittadino.
ID ANPR operazione = 9990746

**Comment by busaster** [comment]
se invece se faccio la stessa ricerca a usando come  filtro un comune esistente che non è quello di residenza del cittadino mi viene restituito l'errore 3 come mi aspettavo

**Comment by mttfranci** [comment]
Abbiamo risposto ad un quesito simile nella issue #1159 .
Stiamo valutando di modificare questo comportamento, se volete potete condividere le vostre opinioni sempre nella issue #1159.
Saluti

Assistenza ANPR
