### ISSUE TITLE
Cancellazione individuo

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1163]
Abbiamo necessità di eliminare dalla web app (come se non fosse mai stato residente) tutti gli eventi riferiti ad un cittadino.
E' possibile?

**Comment by frmariani** [comment]
dipende dagli eventi; se invia l'idanpr del soggetto, potrò essere più precisa

**Comment by Finalmentesubentrati** [comment]
43365697

Il giorno ven 22 feb 2019 alle ore 14:01 frmariani <notifications@github.com>
ha scritto:

**Comment by frmariani** [comment]
la situazione del cittadino è piuttosto confusa: è stato iscritto e cancellato più volte e sono state effettuate diverse operazioni sulla scheda; comunque credo che nulla osti all'annullamento delle ultime operazioni sul soggetto.

**Comment by Finalmentesubentrati** [comment]
Risolto. chiudo il ticket
