### ISSUE TITLE
[1014] listaSoggettiVariati e ANPR02 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1165]
Ambiente di test, comune di Poggio a Caiano

in contesto ANPR02 la chiamata al 1014 per chiudere un procedimento restituisce una risposta con una lista di soggetti veriati composta da un unico elemento vuoto (ID ANPR =19003223 ) del tipo
```
<listaSoggettiVariati>
 <datiSoggetto/>
 </listaSoggettiVariati>
```

Penso che sarebbe meglio se non ritornasse proprio questo oggetto

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Stia valutando la vostra richiesta.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Salve, abbiamo apportato la modifica e dovrebbe essere possibile riprovare in ambiente di test e presubentro.

**Comment by busaster** [comment]
la modifica ha reso nullo anche l'oggetto "anomalie" nella risposta alla richiesta 1014 di apertura procedimento. Questo pur essendo formalmente corretto fa andare in errore logiche consolidate del nostro applicativo. per evitare che posa accadere anche ad altri probabilmente è meglio lasciar stare la modifica e la mia richiesta iniziale , per miglior retro-compatibilità.
Potete ripristinare il comportamento precedente ?
Grazie

**Comment by mttfranci** [comment]
Abbiamo ripristinato solo la sezione anomalie.
Va bene così?

**Comment by busaster** [comment]
sì, così funziona anche con lo stile di  chiamata precedente.
grazie
