### ISSUE TITLE
[5012] - annullamento mutazione di residenza

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1167]
Comune di Luserna San Giovanni (TO) - Ambiente di produzione

Il comune ci segnala che in fase di annullamento pratica di iscrizione da comune subentrato per il soggetto con Codice ANPR: 40235125, vengono restituiti i seguenti errori:

> 999 - Operazione non effettuabile
> EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-02-26 14:59:51 , idOperazioneANPR 53547347

L'operazione che viene rifiutata è una 5012 che va ad annullare una 5001, per trasferimento di residenza.
Potete dirci da cosa è dovuto questo errore?
Il comune ha urgenza di annullare l'iscrizione perché il cittadino entro una settimana richiederà la residenza in un altro comune non subentrato.

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando il problema. Le faremo sapere appena possibile

**Comment by asqueglia** [comment]
L'errore è dovuto ad  una anomalia causata dal servizio di mutazione residenza con patente e autoveicoli (5001); l'anomalia è stata già risolta e rilasciata negli ambienti di test. A breve la fix verrà riportata anche in ambente di produzione. Per il caso specifico abbiamo provveduto con una bonifica da centro in modo da consentirvi di effettuare l'operazione di annullamento. Potete riprovare. restiamo in attesa di un vostro riscontro.

**Comment by siscomanpr** [comment]
Grazie, adesso l'annullamento è andato a buon fine.
