### ISSUE TITLE
Problemi pratica di immigrazione

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1169]
Non riusciamo ad iscrivere un cittadino straniero, già precedentemente cancellato da ANPR. Dalla web app abbiamo verificato che appaiono diverse iscrizioni e cancellazioni tutte in sata 26/02/2019.
L'ID operazione ANPR è 53637684.

**Comment by frmariani** [comment]
il cittadino è stato iscritto nel Comune di Altamura nel 2018 e cancellato per trasferimento all'estero nello stesso anno; ieri, sempre il Comune di Altamura,  ha effettuato per 5 volte consecutive l'iscrizione e la cancellazione del soggetto; di fatto, ad oggi il soggetto risulta cancellato, pertanto l'operazione di mutazione di residenza che il Comune di Altamura sta cercando di effettuare, non può andare a buon fine: deve essere utilizzato il servizio di iscrizione per altri motivi con l'indicazione dell'idanpr precedentemente assegnato.
Posso chiedere come mai state effettuando queste operazioni ?
Se può essere utile scrivetemi in privato un contatto telefonico:  frmariani@sogei.it

**Comment by frmariani** [comment]
come da accordi intercorsi, chiudo la issue in quanto il problema risiede nel gestionale.
