### ISSUE TITLE
[Test subentro] Atto originale/trascritto - Dati da inserire nel file APR

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#117]
Buongiorno,
in merito agli eventi (nascita, matrimonio, divorzio, ... ) che prevedono i dati relativi al corrispondente atto (anno, parte, serie, numero, volume, data formazione), quali sono i dati da inserire nel file APR, nel caso in cui siano disponibili sia i dati dell'atto originale che quelli dell'atto trascritto?
Grazie 

Bistagno (AL)
Codice ISTAT: 006017

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Atto originale
