### ISSUE TITLE
[5005 / 5012] Ripristino di Cambio Abitazione - dataDecorrenzaResidenza

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1170]
ambiete di PRODUZIONE - comune di FAENZA

idSoggettoANPR 19135898

con idOperazioneComune 2018026981 (ws 5005) e dataDecorrenza 20-11-2018 è stato inviato un cambio di abitazione del soggetto di cui sopra.
la dataDecorrenzaResidenza precedente a questa mutazione era 18-06-2015.

oggi, con idOperazione 2019007066 (ws 5012) si è tentato l'annullamento della mutazione di cui sopra.
la richiesta è andata a buon fine.
la situazione di residenza è tornata la precedente, ma interrogando l'anagrafica del soggetto la dataDecorrenzaResidenza è sempre 20-11-2018 (mentre ci aspettavamo di ritrovare 18-06-2015).

per maggiore completezza segnalo che il ripristino è stata tentato in una prima istanza con un ulteriore ws 5005, poi annullato anch'esso con successo.

come mai questa situazione?
e come ripristinare la data del 18-06-2015?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
stiamo verificando l'anomalia

**Comment by frmariani** [comment]
c'è stato un problema che abbiamo risolto.
la data di decorrenza della residenza del cittadino è stata ripristinata,  fatemi sapere se ravvisate altre incongruenze.
