### ISSUE TITLE
Rettifica specie indirizzo di residenza

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1172]
Buongiorno,
il Comune di Agrigento (084001) deve rettificare la specie per un indirizzo in cui sono residenti diversi nuclei familiari.
Tutti i residenti in Via Teti devo risultare residenti in Vicolo Teti.

Non trattandosi di una mutazione (non deve cambiare la data di residenza) ma di una rettifica, come occorre comportarsi?

Si veda per esempio la famiglia IdANPR 26202040

Giovanni Durante
Kibernetes

**Comment by frmariani** [comment]
non è ancora stata rilasciata in ambiente di produzione la rettifica dell'indirizzo a causa di errore materiale;
Come da accordi telefonici, seguiremo il Comune nei casi di aggiornamenti urgenti.
