### ISSUE TITLE
[5012] impossibile annullare una 5008 di tipo 20

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1175]
Ambiente di produzione, comune di Schio.

il comune deve rigettare una pratica di iscrizione da estero di un cittadino.
Per questo cittadino sono state effettuate due chiamate ad ANPR : una chiamata al servizio 1002 conculsa con successo (id operazione ANPR 35080556) ed una chiamata al servizio 5008 con tipo mutazione 20 con la quale si è aggiornato lo stato civile (id operazione ANPR 35549334).

Dobbiamo dunque annullarle entrambe, ma quando tentiamo la chiamata al 5012  otteniamo l'errore EN234 : Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione. (id operazione ANPR 53996684)

Come si può sbloccare la situazione ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buonasera,
abbiamo una situazione molto simile: si deve annullare per rigetto l' immigrazione dall' estero del soggetto con idANPR 31179280, ma l' esistenza della mutazione non annullabile con id operazione 13356736 impedisce sia di annullare l' iscrizione sia di cancellare il soggetto dalla decorrenza dell' immigrazione.
Come possiamo agire?

Grazie, saluti
Sonia Fiorini

**Comment by asqueglia** [comment]
Buongiorno, nel caso segnalato da @busaster nella mutazione di perfezionamento scheda indicata (tipo mutazione 20), è stata richiesta una mutazione dati anagrafici che ha comportato il cambio nome del soggetto da XXXX YYYYY a XXXX-YYYYY su Agenzia delle Entrate. Nel caso segnalato da @sfmodena invece, la mutazione dati anagrafici richiesta ha comportato per il soggetto la modifica del CF da un CF alfanumerico non validato ad un CF numerico validato e marcato da Agenzia delle Entrate. 
In generale in ANPR non è possibile annullare una mutazione dati anagrafici che ha comportato un colloquio con Agenzia Entrate, come nel vostro caso. 
Per sanare la situazione , potete utilizzare il servizio di cancellazione indicando come motivo di cancellazione ripristino anagrafica.

**Comment by sfmodena** [comment]
Buonasera,
il collega dell' Anagrafe che segue il caso ha tentato la cancellazione come suggerito ma è stato bloccato dall' errore EN240 perchè si aspettava di poter indicare come decorrenza la stessa data dell' iscrizione (riuscendo quindi effettivamente ad annullarla) e non una successiva alla mutazione bloccante. E' possibile o è previsto che in futuro si possa fare? 

Grazie, saluti
Sonia Fiorini

**Comment by asqueglia** [comment]
Buongiorno, 
no non è previsto che si possa fare in quanto l'annullamento comporterebbe uno storno di un CF emesso da AE non previsto da Agenzia Entrate. La cancellazione deve essere fatta con decorrenza almeno pari all'ultimo aggiornamento subito dal soggetto. Ciò non ha alcuna ripercussione su una futura re-iscrizione in ANPR del soggetto, che potrà essere fatta a qualsiasi data decorrenza si ritiene opportuno.
Un saluto

**Comment by asqueglia** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
