### ISSUE TITLE
[1002] Errore AAE97

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1176]
idOperazioneANPR 54121787
Ambiente di Produzione

Buongiorno,
ad un comune in ambiente di produzione in fase di iscrizione è uscita il seguente errore: AAE97
Non capiamo dove possa essere il problema.

Potete verificare?
Grazie

**Comment by azabatta** [comment]
Buongiorno,
stiamo verificando la segnalazione.

**Comment by azabatta** [comment]
Dalle verifiche effettuate risulta esserci stato un problema temporaneo nel colloquio con Agenzia Entrate.
E' possibile chiedere al comune di riprovare? 
Restiamo in attesa di un cortese riscontro

**Comment by SAlberto** [comment]
Buongiorno,
questo caso specifico sembra si sia risolto ma il messaggio AEE97 continua a presentarsi soventemente anche da altri Comuni al momento dell'inserimento di una nuova iscrizione per nascita.
Porto l'esempio dell'ID Operazione 57168425 di oggi.
Qual è la causa di questi messaggi?
E' possibile trovare una soluzione definitiva?

Grazie in anticipo.

**Comment by azabatta** [comment]
Il problema è di colloquio tra ANPR ed Agenzia Entrate: si sono verificate delle interruzioni. Stiamo lavorando per ripristinare la continuità dei servizi.

**Comment by SAlberto** [comment]
Buongiorno,
ci sono delle novità sull'errore in oggetto?
Continuiamo a ricevere segnalazioni da vari Comuni che lo riscontrano.
Per farvi un esempio:
ID Operazione ANPR: 73943654

Si tratta di un'iscrizione da un Comune non subentrato che non si riesce a portare avanti a causa di un errore AEE97. Il Comune interessato da questo caso ha provato a contattare l'assistenza ANPR che ha risposto che la soluzione è inserirlo manualmente dal portale o contattare la software house per farsi risolvere il problema.

Ringraziando in anticipo per la risposta.
Cordiali saluti

**Comment by azabatta** [comment]
Buongiorno,
stiamo verificando la segnalazione.

**Comment by SAlberto** [comment]
Buongiorno,
in attesa di una risposta per l'ID Operazione ANPR segnalato in precedenza, mi permetto di segnalare anche quest'altro ID Operazione, sempre legato ad un errore AEE97 di un comune in produzione.

ID Operazione ANPR: 75908229

Concludo dicendo che il Comune ha già contattato l'assistenza di primo livello che ha "liquidato" la questione asserendo che il problema era del gestionale che non comunica con AE e ANPR. Non è la prima volta che l'assistenza di primo livello, di fronte ad un errore AEE97, dà una risposta simile.
Senza creare un clima di "caccia alle streghe", sarebbe davvero utile capire la causa scatenante di queste segnalazioni, senza cercare di scaricare la palla a qualcun altro. Se il problema è legato al gestionale e alle comunicazioni che mandiamo, sarebbe utile capire dove sia l'errore e cosa possiamo fare per far sì che non si verifichi più, visto che, come detto in precedenza, è un messaggio abbastanza diffuso.

Restando in attesa di una risposta vi porgo Cordiali saluti.

**Comment by azabatta** [comment]
Buonasera, 
l'errore  relativo all'ID precedente è stato individuato e corretto, la correttiva è in fase di test. Contiamo di  estenderla al più presto in esercizio ed in ogni caso stiamo verificando se anche il secondo ID rientra nella stessa casistica.
Buona serata

**Comment by azabatta** [comment]
Buonasera, 
l'intervento è stato rilasciato, è possibile riprovare.
Restiamo in attesa di un cortese riscontro sulla risoluzione  del problema.
Grazie
