### ISSUE TITLE
[A006] EN238 in scissione AIRE

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1178]
Ambiente di produzione, comune di Villafranca di Verona.

Con una chiamata A006 si tenta di trasferire in una nuova famiglia estera ad un nuovo indirizzo un soggetto.
L'operazione però fallisce con l'errore "EN238 La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata" (id operazione ANPR 54174255).

la cosa strana però è che questa operazione ha decorrenza 30/11/2018 e la residenza del soggetto da variare prima della chiamata ha decorrenza 20/11/2018, che quindi sembrerebbe coerente con la richiesta.

Potete aiutarci a trovare il problema ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
Abbiamo riscontrato un piccolo problema già risolto, potete riprovare per favore ?

**Comment by frmariani** [comment]
ho verificato che il trasferimento è stato effettuato, chiudo la issue
