### ISSUE TITLE
WebApp - Mutazione dati coniuge straniero emigrato all'estero

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#118]
Data test 19/04/2017 - Ambiente test (dptest)
Abbiamo emigrato all'estero il soggetto straniero LMKKLD74E09Z336G coniugato.  
Nel caso di coniuge residente (es BLLHMH87L46Z336Q ) non è  possibile modificare il cognome del coniuge emigrato.

Grazie

 Amprimo, Floramo, Gillone- Comune di Torino

**Comment by gcarbonin** [comment]
La domanda è collegata ad un'altra simile di ieri. Quando i coniugi sono entrambi residenti, le due schede sono collegate tra di loro; con l'emigrazione del coniuge la scheda viene archiviata e quindi non è più modificabile; per altro se fosse consentita la variazione del cognome sulla scheda del coniuge che rimane residente si avrebbe una incongruenza (un certificato della moglie riporterebbe un dato diverso da quello che si otterrebbe interrogando la scheda del marito migrato). Operativamente,  si dovrebbe annullare la cancellazione, modificare la scheda del marito, ritrasmettere la mutazione. Penso che la situazione vada esaminata da un punto di vista amministrativo. Pongo la questione al Ministero dell'Interno

**Comment by gcarbonin** [comment]
A parte il chiarimento, la modifica è possibile intervenendo sulla scheda della persona che rimane residente nel comune e modificando i dati del coniuge migrato
