### ISSUE TITLE
tessera sanitaria: anagrafe asl non acquisisce dato allineato anpr-ae

### ISSUE THREAD

**Issue by anagbitonto** [italia/anpr#1180]
Comune di Bitonto - subentrato il 12/12/2018
Cittadino residente con indirizzo di residenza (variato in seguito a pratica di cambio indirizzo antecedente al subentro e andata a buon fine) allineato in Anpr e Agenzia delle Entrate segnala che nel database della Asl, che dovrebbe pescare i dati da Agenzia delle Entrate, compare con il vecchio indirizzo di residenza.
Quale procedura è attivabile per risolvere l'anomalia, dal momento che, interpellati i call center di SistemaTS e ANPR, oltre che direttamente Agenzia delle Entrate, nessuno ha saputo dare indicazioni in merito?

**Comment by FilippoPapi** [comment]
da come è descritto il problema sembra che l'anomalia risieda sul sistema della Asl su cui non possiamo dare supporto.
cordiali Saluti
