### ISSUE TITLE
Sovrapposizione tra due soggetti omocodici in AE

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1181]
Comune di Modena - Ambiente di produzione

Buonasera,
al subentro abbiamo iscritto il soggetto con idANPR 19261469 che all' epoca aveva un codice fiscale numerico in quanto in attesa di risoluzione dell' omocodia con altra persona; non abbiamo fatto su di lui nessuna operazione successiva, ma in ANPR lo troviamo con codice fiscale alfanumerico (non omocodice) e in AE sembra sia stato sovrapposto all' altro soggetto presente con gli stessi dati (residente prima ad Enna poi a Santa Ninfa, entrambi non subentrati; in INA-SAIA pare che Santa Ninfa lo abbia cancellato a luglio 2018). Ora tra l' altro il cittadino ci presenta un passaporto con nuove generalità e dovremmo modificargli la data di nascita; come possiamo "staccarlo" dalla posizione del cittadino di Enna, dato che si tratta di persone diverse?

Grazie , saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Al subentro, se viene inviato un codice numerico provvisorio, nella fase di validazione dei codici fiscali da parte di Agenzia delle Entrate, se al CF provvisorio è stato già attribuito un definitivo, ANPR,  sostituisce il cf numerico con il definitivo. In AE come in ANPR il cittadino è allineato, marcato e residente a Modena. Se ritiene mi scriva pure personalmente per darmi maggiori indicazioni sull'altra posizione che invece dovrebbe risiedere a Modena.

**Comment by rvinzani** [comment]
Inviate modalità operative sulla casella di posta personale. Chiudo la issue. Nel caso fosse necessario può aprirne un'altra facendo riferimento a questa setessa
