### ISSUE TITLE
Come fare un annullamento rettifiche 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1182]
Ambiente di produzione, comune di Roncoferraro.

Si vuole annullare una iscrizione per altri motivi (id operazione ANPR 52452187), ma per il soggetto è stata fatta successivamente una rettifica dei dati iscrizione (id operazione ANPR 54378007 ) per cui l'annullamento iscrizione va in errore "EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione " (id operazione ANPR 54526815).

E' effettivamente la rettifica a bloccare l'annullamento dell'iscrizione ?
E se sì, come possiamo annullare la rettifica ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by ncapozzi** [comment]
Buongiorno,
è la rettifica a bloccare l'annullamento dell'iscrizione ma purtroppo ancora non è possibile annullare tale tipologia di operazione. E' già previsto un intervento in tal senso.
Per il momento il comune può effettuare una cancellazione per altri motivi.

N. Capozzi
