### ISSUE TITLE
[4001/3005] Richiesta eventoAnagrafico=1

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1183]
Buongiorno,
stamattina ho richiesto tramite il servizio 4001 i dati relativi agli eventi 'iscrizione' del Comune di Bistagno (AL) dal 25/01/2019 al 15/02/2019. Nei dati che mi restituisce il servizio 3005 tramite IdOperazioneANPR [54649228] non capisco perchè compare il soggetto con codice fiscale SLLNN..... Che operazione è stata fatta su questo soggeto che giustifichi la sua presenza in questa estrazione?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, 
stiamo verificando l'operazione richiesta. Da una prima analisi sembra che venga riportato erroneamente il soggetto SLLNN... come effetto dell'iscrizione del soggetto CHPGR.., di cui è coniuge, trasmessa nel periodo richiesto. Le faremo sapere appena possibile se è prevista una fix al riguardo. Ringraziamo per la segnalazione.

**Comment by asqueglia** [comment]
Buongiorno, comunichiamo che a breve non è previsto alcun intervento sul servizio indicato. 
Terremo comunque in conto la vostra segnalazione, per meglio approfondirla, nei prossimi piani di lavoro.
Chiudiamo la issue.
