### ISSUE TITLE
[1001] Nato occasionalmente  all'estero

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#1184]
ambiente di PRODUZIONE - comune di CASTEL GUELFO DI BOLOGNA
Nato occasionalmente all'estero da genitori residenti in Italia ed iscritti in APR.
Il comune iscrive i genitori per immigrazione da altro comune con decorrenza ottobre 2018;
a dicembre 2018 trascrive l'atto di nascita suddetto e passa la nascita in anagrafe con decorrenza agosto 2018. 
La comunicazione di iscrizione non produce errori.
Risultato:
ID Soggetto ANPR 47524274 iscritto con decorrenza agosto 2018 
in nucleo con data istituzione  ottobre 2018 (ID Famiglia ANPR 19983767)

Lo storico della famiglia risulta pertanto con date non coerenti.

grazie.
Christian Olivato ADS

**Comment by rvinzani** [comment]
Buongiorno, dovreste annullare l'iscrizione per nascita e ripetere la stessa operazione impostando la data decorrenza appartenenza alla famiglia e la data decorrenza residenza al 23/10/2018

**Comment by COlivatoADS** [comment]
Buongiorno, ma questo non corrisponderebbe alla situazione anagrafica reale.  L'osservazione era relativa al fatto che quell'iscrizione non sarebbe dovuta passare. Il soggetto deve risultare iscritto dalla nascita.

**Comment by MarcoMigliori** [comment]
Scusate l'intromissione, solo per un dubbio: se la famiglia immigra a ottobre 2018, il nato all'estero a agosto 2018 ha titolo a essere iscritto per nascita? Personalmente credo di no, perchè i genitori non erano residenti alla data della nascita. Ovviamente il mio parere non fa testo, ma mi sembra un caso particolare, perchè il nato non può essere credo iscritto prima della data iscrizione della madre. 
In merito all'argomento, Filipazzi aveva già riportato sul forum la scansione di un notiziario Anusca con l'interpretazione (istat) della decorrenza del nato occasionale estero:
https://github.com/italia/anpr/issues/343#issuecomment-337947455

**Comment by COlivatoADS** [comment]
Convengo si tratti di caso particolare;  più correttamente il nato occasionale doveva essere iscritto dal comune di precedente residenza e quindi cancellato per emigrazione per il comune nel quale si erano nel frattempo trasferiti i genitori.  Come scrivevo l'osservazione era che l'invio di una iscrizione con decorrenza nascita in una famiglia istituita con decorrenza successiva, non dovrebbe essere accettata.
