### ISSUE TITLE
[5008] Errore EC168 su comune registrazione atto di nascita

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1187]
ambiente di PRODUZIONE - comune di IMOLA (BO)

idOperazioneComune 201907859
idSoggettoANPR 27247119

la situazione è la stessa segnalata su altro caso (ma su atto di matrimonio) con issue #981 
atto di nascita senza dataFormazioneAtto
soggetto nato a ottobre 1970, in comune ri-numerato nel febbraio 1970.
il codice ISTAT dell'atto di nascita è coerente con la data di nascita, ma sembra che il sistema controlli la coerenza rispetto al gennaio, mese in cui il codice ISTAT era diverso.

potete verificare?
grazie.

Alessandro Monopoli ADS

**Comment by frmariani** [comment]
in effetti la situazione è la stessa; abbiamo allineato la modifica anche all'atto di nascita.

Potete riprovare.

**Comment by AMonopoliADS** [comment]
grazie Francesca.
abbiamo inviato la comunicazione con successo

**Comment by frmariani** [comment]
Perfetto.
