### ISSUE TITLE
Errore EAM95 in fase di Mutazione dati (Rettifica) 

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1188]
Ambiente di Produzione
Villa Cortese

Buongiorno,
abbiamo proceduto alla mutazione di residenza di 2 cittadini già iscritti in ANPR nei 2 comuni precedenti.
In seguito alla mutazione ci siamo resi conto che entrambi i comuni precedenti hanno iscritto in ANPR i cittadini con dati anagrafici errati.
Per un cittadino hanno invertito le lettere del nome, per l'altro hanno messo parte del cognome nel nome.
Nel primo caso il CF non cambia, mentre per il secondo sì.

Purtroppo detti cittadini sono registrati in AE doppi, sia con l'anagrafica corretta (Ministero Interno - Questura) e, ovviamente, con quella errata da ANPR.

Indico le 2 operazione ANPR e chiedo come poter risolvere.
- Informazioni sull'operazione da fornire in caso di assistenza : data 2019-03-08 12:36:25 , 
idOperazioneANPR 55775190
- Informazioni sull'operazione da fornire in caso di assistenza : data 2019-03-08 12:33:10 , idOperazioneANPR 55773710

Grazie

**Comment by asqueglia** [comment]
Buongiorno,
con riferimento all'operazione 55775190 si riporta di seguito la procedura necessaria da seguire è la risoluzione disallineamenti con collegamento dei due CF afferenti alla stessa persona.

Per effettuare tale collegamento, dal sito web di ANPR, sezione “Utilità e notifiche”, selezionare la funzionalità “Risoluzione disallineamenti con Agenzia Entrate:
-	campo  “codice fiscale” riportare il codice presente in ANPR 
-	spuntare “includi validati”
-	eliminare la spunta da  “coincidenti”
-	campo “codice fiscale AE” indicare il CF corretto del soggetto
-	cliccare su “CERCA”
Il sistema riporta  sulla pagina successiva i dati anagrafici di ANPR, selezionare la riga (simbolo lente a fine riga). Il sistema  visualizza due sezioni affiancate:  una con i dati di AE l’altra con i dati di ANPR.
Sotto i dati di AE spuntare “Collega codice fiscale” e cliccare su “CONFERMA”:  il sistema chiede un’ulteriore conferma (i dati di ANPR saranno ricoperti con quelli di AE) ed  al termine invia un messaggio con l’esito dell’operazione.
Con tale operazione oltre a collegare i due codici fiscali, i dati del cittadino in ANPR sono sostituiti con quelli presenti in Agenzia Entrate. 
Il buon esito dell’operazione si può verificare effettuando le consultazioni dalla sezione “Consultazione ed estrazione” : “Consultazione scheda individuale”  per i dati di ANPR - “Consultazione AE” per i dati di Agenzia Entrate  (in coda alla consultazione ci sarà il CF precedente che è stato collegato).
Si riporta di seguito il link al documentale di ANPR dove è possibile scaricare la guida “APPENDICE VALIDAZIONE DEL CODICE FISCALE E DEI DATI ANAGRAFICI E RISOLUZIONE DEI DISALLINEAMENTI CON L’AGENZIA DELLE ENTRATE”:

https://www.anpr.interno.it/portale/documentazione-tecnica

Con riferimento, invece, all'operazione 55773710, dovreste sempre dalla risoluzione disallineamenti AE indicare il CF presente in ANPR , selezionare 'coincidenti' e provvedere a Confermare i dati di AE.

**Comment by cvignati** [comment]
La cosa è più problematica.
Per il soggeto relativo all'operazione 55775190 ho fatto la procedura di risoluzione dei disallineamenti ed è andato tutto a buon fine. Il problema è che mi sono accorto che è sbagliato anche il nome, mancante di una M. Correggendolo cambia il CF, come devo comportarmi?
Invece per il soggetto dell'operazione 55773710 l'anagrafica corretta riporta un codice fiscale numerico e non alfanumerico, in quanto attribuito dalla questura. Come posso risolvere?

Grazie

**Comment by asqueglia** [comment]
Per quanto riguarda l'operazione 55775190 qualora si renda necessario modificare uno o più dei 5 dati anagrafici che concorrono al calcolo del codice fiscale, è necessario effettuare una mutazione dati anagrafici dal proprio gestionale con richiesta validazione CF, senza trasmettere il nuovo CF da voi calcolato.
Agenzia delle Entrate stabilisce se assegnare o meno un nuovo CF e nel caso in cui ne venga attribuito uno nuovo lo restituisce nella risposta dopo averlo collegato al precedente.
Per quanto riguarda l'operazione 55773710 confermiamo che al momento ANPR è allineato con quanto registrato in AE con CF alfanumerico. Se si tratta di un soggetto rifugiato a cui è stato assegnato un CF numerico, al riguardo è in corso una analisi in quanto non è ancora implementato il flusso.

**Comment by cvignati** [comment]
Buongiorno,
per quanto riguarda l'operazione 55775190 contatto la nostra software house in quanto, dalle prove da me eseguite, non è possibile inviare una mutazione senza indicare il CF.

Per quanto riguarda l'operazione 55773710 i dati che vede allineati sono quelli errati (secondo elemento del nome CHIZEKIE, ma l'elemento corretto è CHIKEZIE) e confermo che è nello status di Rifugiato e che l'anagrafica corretta è associata ad un CF numerico.

Grazie

**Comment by cvignati** [comment]
Mi conferma che attualmente non posso fare nulla?

**Comment by asqueglia** [comment]
Buongiorno, come detto, per entrambe le operazioni se i dati anagrafici non sono corretti è necessario trasmettere una variazione dati anagrafici dal proprio gestionale (o dal sito web ANPR) con richiesta validazione CF, senza trasmettere il nuovo CF; sarà AE che restituirà in risposta eventualmente il nuovo CF generato.
Per quanto riguarda i CF numerici precedentemente emessi dalla questura, se si desidera collegarli è necessario che il cittadino si rechi personalmente agli sportelli di Agenzia delle entrate per richiedere il collegamento in quanto ANPR non può farlo. Si tenga comunque presente che se per una persona viene emesso un CF alfanumerico (validato su ANPR e marcato su AE), il CF numerico (precedentemente emesso) sarà sempre al più un CF collegato secondario .

**Comment by cvignati** [comment]
Sistemato tutto attraverso WebApp ANPR.

Grazie
