### ISSUE TITLE
WebApp Mutazione dati straniero nato a Torino emigrato all'estero

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#119]
Data test 19/04/2017 - Ambiente test (dptest)
Soggetto straniero nato a Torino WLNSLL17D50L219O ( ID 459917 ISCRIZIONE PER NASCITA ), successivamente emigrato all'estero (ID 459923 CANCELLAZIONE ALTRI MOTIVI ). Il sistema non permette di modificare i dati del soggetto, ma essendo nato a Torino dovrebbe essere possibile. 
Grazie
Amprimo, Floramo, Gillone- Comune di Torino

**Comment by gcarbonin** [comment]
I dati delle schede archiviate non sono modificabili.

**Comment by annamariaGillone** [comment]
La risposta è chiara, tuttavia almeno nei casi di soggetti emigrati all'estero e nati nel comune dovrebbe essere possibile effettuare la modifica in quanto non dovrebbe creare problemi dovuti alla banca dati condivisa con gli altri comuni.

**Comment by gcarbonin** [comment]
Non è un problema legato alla banca dati ma al fatto che la scheda è archiviata
