### ISSUE TITLE
Errore EF002 in Mutazione residenza APR per rimpatrio Aire da altro comune subentrato

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#1191]
Comune di Cagliari - ambiente di produzione.

Buongiorno,
Nell'operazione con id 56145622 relativo alla mutazione residenza APR per rimpatrio a Cagliari di cittadino iscritto all'AIRE di Milano, ci viene restituito il seguente errore:
"EF002 - Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata"

come possiamo risolvere?

Grazie 
Andrea Demeglio

**Comment by frmariani** [comment]
trattandosi di una famiglia AIRE che rientra in Italia, nell'oggetto famigliaConvivenza deve essere indicato tiposcheda=5 (famiglia Aire) e non tiposcheda=3 (famiglia ANPR);
con il buon esito dell'operazione, il sistema modificherà la tipologia della famiglia

**Comment by andemeglio** [comment]
ok .... inoltro subito la segnalazione alla Softwarehouse

grazie
