### ISSUE TITLE
 errore AEE97

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1192]
Ambiente di produzione
id operazione anpr: 56312382

Da un paio di giorno il comune ci segnala che questa operazione non va a buon fine, sembra esserci un problema di comunicazione con l'agenzia delle entrate.
Potete verificare?

Grazie

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
in mattinata abbiamo avuto diversi errori di questo tipo su più soggetti, ad esempio sulle operazioni di iscrizione (flusso 1002):
data 2019-03-13 13:00:31 , idOperazioneANPR 56755432
data 2019-03-13 12:47:00 , idOperazioneANPR 56748652

Ci sono problemi nel colloquio con AT?

Grazie, saluti
Sonia Fiorini

**Comment by mttfranci** [comment]
Salve, stiamo verificando le vostre segnalazioni.

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
oggi il problema sembra non presentarsi più. Ieri si aveva l' errore AEE97 anche tentando di usare la "Consultazione AE" per un codice fiscale qualsiasi (anche non coinvolto in operazioni di iscrizione o mutazione).
Grazie, saluti
Sonia Fiorini

**Comment by mttfranci** [comment]
Abbiamo rilevato che ci sono stati dei problemi di colloquio con Agenzia entrate nelle fasce orarie delle operazioni da voi indicate.
In generale è possibile riprovare e potete farci sapere se riscontrate ancora difficoltà.
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Buongiorno,
questo caso specifico sembra si sia risolto ma il messaggio AEE97 continua a presentarsi soventemente anche da altri Comuni al momento dell'inserimento di una nuova iscrizione per nascita.
Porto l'esempio dell'ID Operazione 57168425 di oggi.
Qual è la causa di questi messaggi?
E' possibile trovare una soluzione definitiva?

Grazie in anticipo.
