### ISSUE TITLE
EN214 in consultazione 3002

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1194]
Ambiente di produzione, comune di Misterbianco

tentando di consultare il soggetto ID ANPR 43075478 per cui è arrivata la notifica di emigrazione in altro subentrato (CATANIA) otteniamo l'errore : "EN214 Non e' possibile consultare i dati del soggetto: la famiglia cui appartiene e' ancora in fase di registrazione."
Si presenta sia da servizio che da webapp.

Qual è la causa del blocco ?

Grazie

**Comment by frmariani** [comment]
Il Comune di Catania, ha inserito lo stato di "Famiglia Incompleta"  nei dati controllo, pertanto fintanto che lo stato non venga modificato in "Famiglia Completa", questa non potrà essere consultata.
Provo a chiamare il Comune per verificare la veridicità dell'informazione.

**Comment by frmariani** [comment]
riprovate per favore

**Comment by busaster** [comment]
Il problema a Misterbianco persiste

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
inserite come data riferimento scheda 10/12/2018, ma fino a ieri la famiglia risultava incompleta
per favore provate con la data odierna

**Comment by busaster** [comment]
Ok, Abbiamo provveduto ad allineare la base dati locale in seguito alla notifica arrivata da ANPR.
Se però consultiamo in ANPR il soggetto ID 43075478 vediamo un'anomalia del tipo "il soggetto risulta iscritto anche nel comune di MISTERBIANCO)", ma facendo una ricerca in ANPR per CF troviamo un'unica corrispondenza. Come mai ?

**Comment by frmariani** [comment]
l'anomalia risale al subentro, ma può essere ignorata

**Comment by bfilipazzi** [comment]
Purtroppo i messaggi relativi ad anomalie che sono state sanate inducono a pensare che siano ancora presenti. Più di un cliente ritiene un disturbo la visibilità di questi messaggi che portano a svolgere verifiche superflue.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
ci rendiamo conto, infatti stiamo lavorando in tal senso.
