### ISSUE TITLE
Problemi con richieste 7001

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1195]
Buongiorno,

Ambiente di Produzione.
Un Comune ci sta segnalando problemi con le richieste di tipo 7001. 
Sembra che da stamattina il servizio non stia funzionando.
Potete verificare?
Con cordiale urgenza.

**Comment by mttfranci** [comment]
A quanto vediamo oggi sono arrivate molte richieste 7001 da diversi comuni.
Potete comunicarci il comune e possibilmente fornirci una richiesta e risposta del server?
(Il 7001 non contiene dati sensibili quindi potete postare le informazioni anche qui)
Grazie in anticipo
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Buongiorno,
Nell'attesa abbiamo contattato i tecnici del Comune per alcune verifiche e abbiamo riscontrato che il problema era legato al loro server.
La situazione si è risolta.
Grazie comunque per l'attenzione dedicataci.

Cordiali saluti.
