### ISSUE TITLE
[1002] Iscrizione di soggetto cancellato da ANPR - Errore EN185

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1196]
ambeinte di PRODUZIONE - comune di SAN LAZZARO DI SAVENA (BO)

si tenta di iscrivere il soggetto con idANPR 19231544, presente in ANPR come cancellato, quindi si procede con ws 1002.

in ANPR il soggetto risulta nato in CINA con codice 998.

il cliente ha corretto il riferimento al codice dello stato ed ha provato a farlo partire come 314, ma il ws torna errore:
```
<errore>
  <codiceErroreAnomalia>EN185</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>idSchedaSoggettoANPR 19231544 non presente o dati anagrafici incongruenti</testoErroreAnomalia>
</errore>
```
(data 2019-03-14 10:14:51 , idOperazioneANPR 56927912)

allora si è tentato di uniformare il dato di nascita, passando le informazioni così come presenti in ANPR.
ma anche in questo caso, il ws ritorna errore:
```
<errore>
  <codiceErroreAnomalia>EN185</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>idSchedaSoggettoANPR 19231544 non presente o dati anagrafici incongruenti</testoErroreAnomalia>
</errore>
```
(data 2019-03-14 11:49:55 , idOperazioneANPR 56987761)

abbiamo provato a scollegare il soggetto all'idSoggettoANPR del cancellato, e l'operazione è stata accettata... ma il soggetto è stato duplicato (acquisendo idSoggettoANPR 47798418)
quest'ultima situazione mi sembra un'anomalia, considerato che il soggetto con quel codice fiscale è già presente in ANPR... mi sarei aspettato venisse recuperare il vecchio idSoggettoANPR, oppure mi desse errore.

come dobbiamo procedere per eseguire correttamente l'operazione?
grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
per re-iscrivere un soggetto e recuperare il precedente idanpr, i dati anagrafici devono essere perfettamente uguali; sia nel primo che nel secondo tentativo, avete inserito come luogo di nascita Cina Repubblica Popolare  mentre in ANPR il luogo di nascita dell'idanpr 19231544 è CINA con località ZHEJIANG;
l'iscrizione senza idanpr è stata possibile perchè, attualmente,  il controllo viene effettuato sui 5 dati anagrafici, escluso quindi il CF;  stiamo valutando altri controlli meno stringenti ma egualmente efficaci .

**Comment by AMonopoliADS** [comment]
grazie Francesca.

in effetti, quello che ti ho riportato, è stato uno dei vari tentativi che abbiamo fatto.
in un tentativo successivo, dove i dati di nascita erano quelli corretti, il blocco si estendeva alla codifica della cittadinanza e l'abbiamo frainteso come collegato, invece, alla nascita...

per la cittadinanza, infatti, in ANPR erano presenti questi dati
```
<cittadinanza>
  <descrizioneStato>CINA</descrizioneStato>
  <codiceStato>998</codiceStato>
</cittadinanza>
```

in questo caso, a differenza dei dati di nascita, siamo riusciti ad indicare quelli corretti, riferiti alla codifica 314.

questa mattina abbiamo annullato la doppia iscrizione e proceduto ad iscrivere il soggetto con il precedente idSoggetoANPR.

operazioni concluse con successo.

grazie

grazie.
