### ISSUE TITLE
Internal Error - Servizio di test connessione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1197]
Ambiente di test

la chiamata al servizio di test connessione (https://wstest.anpr.interno.it/ANPRTestConn/TestConn) restituisce da stamattina "javax.xml.ws.soap.SOAPFaultException: Internal Error".

Potete verificare ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by busaster** [comment]
Il problema persiste anche oggi, siccome noi usciamo anche in produzione questo servizio vorrei capire se è un malfunzionamento temporaneo o se il servizio è in dismissione.

Grazie

**Comment by busaster** [comment]
Anche oggi il servizio presenta lo stesso problema.
Potete darmi un riscontro ?

Grazie

**Comment by busaster** [comment]
Scusate se insisto ma non vorrei che questo malfunzionamento si ripercuotesse a breve nei sistemi di produzione.
Potete darmi un riscontro ?

**Comment by gife67** [comment]
Cortesemente potete riprovare.

**Comment by busaster** [comment]
Ora funziona grazie.
Quindi si trattava di un malfunzionamento temporaneo ed il servizio verrà mantenuto , giusto ?

**Comment by gife67** [comment]
Si certo il servizio non verrà eliminato. Ci scusiamo per l'inconveniente.
