### ISSUE TITLE
Versione 5.3

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1198]
Buongiorno,
chiedo scusa, se fosse possibile vorremmo sapere quando, in produzione, il servizio 4005 sostituirà il servizio 3003.

Ringrazio anticipatamente.

**Comment by mttfranci** [comment]
Salve, ci scusiamo per il ritardo nella risposta, potete seguire la issue #1161 per ulteriori informazioni.
Saluti

Assistenza ANPR
