### ISSUE TITLE
tipoComuneRichiesta famiglia 4000

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1199]
Buongiorno,
guardando il vocabolario della 4000 (estrazione) ho notato una stranezza nel tipoComuneRichiesta

```
<xs:complexType name="tipoComuneRichiesta">
	 <xs:sequence>
		<xs:element name="errore" type="tpdt:tipoComuneRichiesta"/>
	 </xs:sequence>
</xs:complexType>
```

è corretta la presenza dell'elemento "errore"?
Mi aspettavo una cosa tipo la famiglia 3000

```
	<xs:complexType name="tipoComuneRichiesta">
		<xs:complexContent>
			<xs:extension base="tpdt:tipoComuneRichiesta">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
```

Potete verificare?
Grazie

**Comment by azabatta** [comment]
Buonasera, 
si tratta di un refuso, si può seguire la issue #1161 per ulteriori informazioni.

**Comment by SAlberto** [comment]
Grazie
