### ISSUE TITLE
Validità del codice fiscale in subentro 

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#12]
Sempre nel subentro, abbiamo notato che se passiamo la validità del Codice Fiscale, mettendo 1, in riferimento alla tabella 22 , viene sempre considerato come non validato.

**Comment by gcarbonin** [comment]
Il dato dichiarato dal comune viene ignorato da ANPR, in quanto come sopra descritto, il dato è aggiornato con quanto restituito dall'Agenzia delle Entrate. Se il comune sta eseguendo un test in ambiente di test-comuni, è normale che i soggetti siano non validati in quanto in ambiente di test AE ci sono pochissimi codici fiscali. Questo test va eseguito in ambiente di pre-subentro che collegato (limitatamente alla simulazione del subentro) all'ambiente reale di AE
