### ISSUE TITLE
Subentro "IN ELABORAZIONE" dal 14/04/2017 prot ANPR 1916

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#120]
Buonasera,
protocollo ANPR 1916 , file APR risulta "IN ELABORAZIONE" dal 14/04/2017
come ci dobbiamo comportare?

se si va in "monitoraggio anomalie" e si clicca sul numero, nella sezione "Numero schede individuali con dati errati o incompleti" viene scaricato il file con le anomalie dell'elaborazione del 04/04/2017

Grazie
Team Sipo Comune di Milano

**Comment by gcarbonin** [comment]
La fornitura rimane "in elaborazione" in quanto il file AIRE non e' elaborabile come mi sembra sia stato piu' volte segnalato. La funzione di monitoraggio delle anomalie riguarda le forniture completamente elaborate; per questo trova i dati del 4 aprile.
