### ISSUE TITLE
[WebApp] : ambiente freetest : errore AEE97 in registrazione 

### ISSUE THREAD

**Issue by marcocipri** [italia/anpr#1200]
da quasi tre giorni, nell'ambiente di test e relativamente alla registrazione di un nuovo soggetto,
otteniamo l'errore 

Operazione non effettuabile (Codice: AEE97)
data 2019-03-15 10:36:14 , idOperazioneANPR 2052389 (Codice: EN527)

in particolare tentiamo con

tipo operazione : iscrizione per altri motivi
instanza : instanza di parte

è possibile identificare l'origine del problema/errore?

allego la schermata
<img width="1335" alt="05" src="https://user-images.githubusercontent.com/5989506/54426448-2e1dc180-4718-11e9-9662-0f068fe546bb.png">

**Comment by gife67** [comment]
Stiamo attendendo che la componente sistemistica risolva il problema con il colloquio con Agenzia Entrate.

**Comment by gife67** [comment]
necessita di verifica se è stato risolto
