### ISSUE TITLE
Residenza in tempo reale - richiesta chiarimento

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1201]
Buon giorno,
vorremmo un chiarimento sulla gestione in ANPR dei cosiddetti residenti "provvisori", ossia degli individui per cui l'ente ha avviato una pratica di iscrizione che è in attesa di conferma.
Il comune di Colonnella, subentrato in data 08/03, ha effettuato questa mattina la conferma di una pratica di iscrizione di un individuo avviata prima del subentro (l'individuo era stato quindi trasmesso in ANPR).
Analizzando la documentazione ci è sembrato di capire che non esista un campo con cui sia possibile indicare tale stato dell'iscrizione, per cui nel file di subentro un individuo "provvisorio" viene trasmesso allo stesso modo di un individuo residente. Avviene lo stesso quando si iscrive in ANPR un nuovo individuo per immigrazione.
Tale informazione è importante in quanto va a impattare sulla certificabilità di un individuo che, nel caso sia provvisorio, è "parziale" (campo _AttributiSoggetto.soggettoCertificabile_ = '1') fino alla conferma dell'iscrizione.
Ci siamo accorti che l'individuo, nel file di subentro (e quindi quando era ancora nello stato di residente "provvisorio"), è stato trasmesso con il valore '2' ("certificabilità completa") . 
Chiediamo pertanto:
- se per gli individui residenti "provvisori" non presenti in ANPR sia corretto indicare il valore '1' nel campo _AttributiSoggetto.soggettoCertificabile_  (sia nel file di subentro che nella request di iscrizione) e in seguito, al momento della conferma della pratica di iscrizione, effettuare una mutazione 5008 che va a modificare a '2' il valore; 
- se per gli individui già presenti in ANPR, a seguito di una mutazione di residenza (immigrazione da un comune subentrato), dato che la certificabilità diventa "parziale" fino a quando la pratica non è confermata, va effettuata contestualmente anche una mutazione 5008 modificando a '1' il valore del campo _AttributiSoggetto.soggettoCertificabile_ .

Grazie, cordiali saluti.

Giuseppe Mucciarelli,
TINN srl.

**Comment by bfilipazzi** [comment]
La mutazione di residenza fra comuni subentrati non dovrebbe alterare la certificabilità dei migranti abbassandola da "completa" a "parziale". Il "nuovo" comune dispone già di tutti i dati anagrafici che si trovano in ANPR e non deve attendere che il comune di provenienza glieli confermi.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Per quanto riguarda le iscrizioni aggiungo che l'apertura procedimento limita le certificazioni fintantochè non lo stesso sia chiuso al completamento della pratica. Per quanto riguarda i dati di inviati al subentro di un cittadino "provvisorio", può essere utilizzato il campo soggettoCertificabile

**Comment by Amucciarelli74** [comment]
Buon giorno,
in effetti la correlazione tra procedimento e certificabilità è riportata nella documentazione ai paragrafi 16.1.2 e 16.1.3 e in particolare è scritto che "_nel caso di mutazione di residenza da altro comune, salvo diversa esplicita indicazione da parte del comune, la registrazione del procedimento di mutazione rende tali posizioni parzialmente certificabili (residenza e lo stato di famiglia). La parziale certificabilità cessa automaticamente su indicazione esplicita del comune o quando viene chiuso il procedimento_", e che "_La certificabilità di un soggetto determinata dalla presenza di un procedimento in corso non è collegata all’informazione di certificabilità completa o parziale presente nella scheda del soggetto e che viene dichiarata all’atto dell’iscrizione per ragioni indipendenti dalla presenza di un procedimento in corso._"
Mi conferma quindi che : 
- per le iscrizioni e le mutazioni di residenza il soggetto va comunque dichiarato come certificabile (se lo è) ed è lo stato del procedimento poi a definire le variazioni temporanee della certificabilità;
- in fase di subentro, il cittadino "provvisorio" va trasmesso  con il campo _soggettoCertificabile_ valorizzato a '1' dato che non si riesce altrimenti ad indicarne la temporanea certificabilità parziale, e alla conferma dell'iscrizione deve essere effettuata una mutazione col ws 5008 per modificare il soggetto in certificabile perché in questo caso la pratica è stata istruita prima del subentro e non è stata agganciata ad un procedimento ANPR.
Grazie, 
cordiali saluti.

**Comment by RBiasi** [comment]
Se l'operazione di iscrizione non è conclusa in fase certificazione appare in tutti i casi un messaggio da parte di ANPR.

Il certificato non puo' essere emesso perché' risulta un procedimento aperto per il soggetto intestatario del certificato. Tuttavia potete emettere ugualmente il certificato impostando a 1 il campo   <datiControllo> .<forzaCertificazione>?</forzaCertificazione>

**Comment by rvinzani** [comment]
Sì, è possibile emettere ugualmente il certificato impostando a 1 il campo forzaCertificazione.

**Comment by rvinzani** [comment]
Chiudo la issue. Se necessario ulteriore chiarimento aprire una nuova issue facendo riferimento a questa stessa.
