### ISSUE TITLE
Errore AEE95 su annullamento iscrizione per nascita

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1203]
Comune di Modena - Ambiente di produzione

Buongiorno,
i soggetti con id ANPR 19660231  e 20047652 sono la stessa persona, la cui nascita è stata denunciata due volte con date di nascita diverse e conseguentemente iscritta due volte in Anagrafe , ANPR e Agenzia delle Entrate.  Su decreto del Tribunale ora si deve annullare l' iscrizione per nascita del soggetto con idANPR 19660231 , annullando anche l' attribuzione del codice fiscale. Il tentativo di annullamento origina questo errore:

![image](https://user-images.githubusercontent.com/43783838/54473445-02621080-47d8-11e9-9b94-e0f849a47ce7.png)

Come possiamo superarlo?
Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Come anticipato telefonicamente è possibile annullare un CF per errata richiesta di emissione entro la mezzanotte del giorno stesso. Saluti
