### ISSUE TITLE
[3003 test] Elenco Operazioni - Errore EN122

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1204]
ambiente di TEST - comune di FAENZA (039010)

l'elenco delle operazioni richiesto con ws 3003 (in modalità ANPR02) funziona per alcuni soggetti, mentre per altri (che da web-app presentano operazioni) risponde con l'errore:
EN122 - E - La richiesta effettuata non produce alcun risultato

non capiamo se sia un problema delle nostre chiamate... della nuova versione appena pubblicata...  o di altra natura...

esempi di richieste che NON ritornano risultato:
idOperazioneComune 2019300713
idOperazioneComune 2019300716

esempio di richiesta che ritorna risultato:
idOperazioneComune 2019300710

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, stiamo verificando la vostra segnalazione.
Per aiutarci nell'indagine potreste verificare se la risposta cambia tra l'invocazione con codDestinatario ANPR01 e ANPR02?
Grazie in anticipo.

**Comment by AMonopoliADS** [comment]
In questo momento sono fuori ufficio, ma avevo provato ieri anche in modalità ANPR01 ed il risultato è stato lo stesso...
Comunque domani posso riprovare nuovamente.

**Comment by AMonopoliADS** [comment]
confermo che il servizio risponde EN122 anche con ANPR01.
la differenza è che oggi non produce risultato neanche la richiesta che ieri funzionava (nè con ANPR01 nè con ANPR02).

tentativi con ANPR01:
idOperazioneComune 2019300755
idOperazioneComune 2019300758
idOperazioneComune 2019300761

tentativi con ANPR02
idOperazioneComune 2019300762 (ieri funzionava, oggi no)
idOperazioneComune 2019300768
idOperazioneComune 2019300771

**Comment by mttfranci** [comment]
Grazie del riscontro.
Forse abbiamo individuato l'anomalia.
Abbiamo effettuato una modifica per il ramo ANPR02 in test comuni.
Potete riprovare con questa modalità?
Cortesemente sarebbe utile avere l'id dell'operazione anche in caso di esito positivo.
Grazie in anticipo.

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
adesso le richieste danno un risultato consistente.
idOperazioneComune 2019300774
idOperazioneComune 2019300777
idOperazioneComune 2019300781

e sembrano funzionare anche in modalità ANPR01
idOperazioneComune 2019300785
idOperazioneComune 2019300789
idOperazioneComune 2019300792

**Comment by mttfranci** [comment]
Grazie della collaborazione, si nel frattempo avevamo anche applicato l'intervento al ramo ANPR01.
Siamo a disposizione per ogni ulteriore chiarimento.
Assistenza ANPR.
