### ISSUE TITLE
Esito AE: Variazione non consentita per superamento numero campi variati (Codice 93)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1205]
Buongiorno, comune di Rio Saliceto ambiente di produzione.
Al cittadino id 44599962 è stato creato un nuovo codice fiscale in AE (non dal Comune ma dall'Agenzia), con generalità differenti, creando un nuovo codice fiscale.
Quindi abbiamo la posizione ANPR validata in AE, e il nuovo codice fiscale non collegato al primo.
Nella nuova posizione creata da AE, sono diversi:
- cognome
- nome
- data nascita

L'Agenzia scrive al comune per far collegare i codici fiscali. Procediamo dal menù Utilità della WA come da guida, seguendo la procedura descritta in "4.1 COLLEGAMENTO CODICI FISCALI".
Quando spuntiamo "Collega codici fiscali" e premiamo conferma, riceviamo l'errore:
_Esito AE: Variazione non consentita per superamento numero campi variati (Codice 93)_

Restiamo in attesa per capire come risolvere il problema, grazie.
Marco Migliori
PAL Informatica

**Comment by rvinzani** [comment]
Purtroppo è un caso che non riusciamo a gestire in maniera automatica se non facendo un doppio passaggio che creerebbe un CF intermedio
Ci sentiamo via email per le ulteriori informazioni da inviare alla direzione centrale di AE per il collegamento dei due CF

**Comment by MarcoMigliori** [comment]
Risolto dopo contatto:
1) AE ha modificato e collegato i propri dati
2) in seguito abbiamo rettificato i dati anpr seguendo le indicazioni di sogei, validando il cittadino
