### ISSUE TITLE
Errore EN403, qual'è la causa?

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1206]
Buongiorno, in seguito alla spedizione di una nascita 1001, con richiesta validazione CF all'agenzia entrate ritorna un errore EN403 "L'operazione richiesta all'agenzia delle entrate contiene dati errati  o insufficienti"
ho verificato ma non ho capito cosa c'è che non va bene, il bambino in punto fisco non è caricato.

ID operazione ANPR 56538450 del 12/03/2019 in subentro
Grazie

**Comment by mttfranci** [comment]
Buongiorno, 
in merito alla segnalazione in oggetto si comunica che al momento è in corso un intervento con Agenzia entrate per il quale, in alcuni casi, non è possibile iscrivere soggetti senza specificare il numero civico nella residenza.

Nell’immediato per consentirvi l’operatività consigliamo di procedere all’attribuzione del CF su punto fisco e successivamente effettuare l’iscrizione su ANPR con richiesta validazione del CF emesso da AE.

Cordiali saluti
Assistenza ANPR
