### ISSUE TITLE
Internal error (from server) 3003

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1207]
idOperazioneComune JD27921
codMittente 013165
operazioneRichiesta 3003

La richiesta riceve in risposta Internal Error (from server)
Grazie
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
salve. possiamo chiedere in che ambiente?
grazie in anticipo.
Assistenza ANPR

**Comment by bfilipazzi** [comment]
produzione

**Comment by mttfranci** [comment]
Salve.
Si è trattato di un time out applicativo.
Provando nuovamente l'operazione dovrebbe andare a buon fine.
Stiamo studiando delle ottimizzazioni per ridurre al minimo questo problema.

Inoltre, per aiutarci nell'indagine di queste casistiche, potreste confermarci se si trattava di una richiesta puntuale o faceva parte di qualche schedulazione periodica e in caso con quale frequenza?

Grazie in anticipo.

**Comment by bfilipazzi** [comment]
Si trattava di una richiesta puntuale.
Grazie
