### ISSUE TITLE
Iscrizione cittadino "irreperibile" che dichiara la provenienza da un comune subentrato

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1208]
Buon giorno,
il comune di Colonnella, subentrato in data 08/03/2019, ci ha segnalato il caso di un individuo che si è presentato allo sportello per una pratica di immigrazione ed ha dichiarato di provenire dal comune di Modena (subentrato).
Il cittadino non risulta tuttavia presente in ANPR ed infatti ad un controllo su PuntoFisco risulta cancellato dal comune di Modena per irreperibilità, in data precedente al subentro del comune stesso, quindi non è stato mai iscritto in ANPR.
In questo caso, secondo l'Ufficiale del comune di Colonnella, la prassi "pre-ANPR" prevedeva che il comune iscrivesse comunque il cittadino con una pratica di immigrazione da Modena, e in questo modo il comune di "provenienza" (o di ultima iscrizione in questo caso) venisse a conoscenza del fatto che un cittadino loro residente, dichiarato irreperibile, fosse ricomparso in un altro comune, annotandone la ricomparsa sulla scheda dell'individuo.
Nell'operatività ANPR, è importante che il comune di provenienza sia comunque a conoscenza della ricomparsa di un cittadino dichiarato irreperibile, anche se mai trasmesso in ANPR? Oppure il comune di destinazione può semplicemente iscrivere il cittadino con una pratica di ricomparsa da irreperibilità senza ulteriori azioni?
Grazie, cordiali saluti
Giuseppe Mucciarelli,
TINN srl.

**Comment by rvinzani** [comment]
Per ANPR il cittadino deve essere prima iscritto per ricomparsa in uno dei due comuni. 
Nel caso lo reiscrivesse Modena poi Colonnella potrebbe prenderlo in carico con una mutazione di residenza. 
L'altra possibilità è che lo iscriva direttamente Colonnella per ricomparsa. Saluti
