### ISSUE TITLE
WebApp adeguamento Ripristino Posizione Anagrafica 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#121]
Buongiorno 
quando sarà disponibile in ambiente di test comuni l'adeguamento del sistema alle logiche presenti nel documento MI-04-AN-0D? 
Grazie
Annamaria Gillone

**Comment by gcarbonin** [comment]
Tramite WS sono già disponibili. L'applicazione web la rendiamo disponibile la prossima settimana (a valle del subentro di Cesena). Avvertiamo quando possibile effettuare i test

**Comment by gcarbonin** [comment]
Può riprovare e darmi un riscontro
