### ISSUE TITLE
Certificato Storico di Residenza - Data validità indirizzo

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1210]
Comune di Serravalle Pistoiese - Ambiente di Presubentro

Buongiorno,
il Certificato storico di Residenza per la cittadina Identificativo scheda attribuito da ANPR: 87212520 vengono riportate le seguenti date:

Comune di SERRAVALLE PISTOIESE (PT) dal 03/01/1954 --> data prima iscrizione OK
Indirizzo VIA COMPOSIZIONE N. 2 dal 12/07/2003 --> Data decorrenza appartenenza a Famiglia (?)

E' corretto indicare come data di validità dell'indirizzo di residenza la Data decorrenza appartenenza alla famiglia.

Un cittadino potrebbe aver variato indirizzo senza variare il nucleo famigliare o viceversa.

Se tale data, ovvero data in cui il cittadino abbia variato indirizzo approdando all'attuale indirizzo di residenza, non fosse presente agli interno degli archivi in quanto antecedente alla data di informatizzazione come ci dobbiamo comportare al fine di ottenere poi una certificazione storica corretta e congruente?

Rimaniamo in attesa di un Vs.  gentile riscontro.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by rvinzani** [comment]
C'è una incongruenza sulle date probabilmente dovuto all'invio errato delle informazioni da subentro. E' corretto che un cittadino possa variare residenza senza variare il nucleo famigliare ma, come nel caso presentato, è difficile che possa cambiare famiglia senza cambiare la residenza.

**Comment by RBiasi** [comment]
Grazie Roberta ti ho scritto una mail per avere maggiori dettagli.

**Comment by rvinzani** [comment]
Non ho ricevuto ulteriori richieste. Chiudo la issue. Nel caso fosse necessario ne aprite una nuova con riferimento a questa stessa
