### ISSUE TITLE
Mancato aggiornamento dati matrimonio in WA

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1212]
Buongiorno,
questa mattina presso il comune di Boara Pisani è stata spedita una comunicazione 5008 per aggiornare i dati di matrimonio. L'operazione ID 58580507 si è conclusa correttamente, ma l'aggiornamento non è stato recepito nella WA.
Grazie

**Comment by frmariani** [comment]
Il problema non è sull'ultima operazione effettuata, bensì sulla riconciliazione dei matrimoni post-subentro; abbiamo eliminato l'anomalia, potete riprovare la consultazione.

**Comment by fmbianchi** [comment]
Salve,
abbiamo i seguenti dubbi:
- quando si genera tale situazione?
- come è possibile verificarla? 
- quale soluzione è possibile applicare da parte del comune?
Grazie

**Comment by frmariani** [comment]
Stiamo valutando una revisione dei dati del matrimonio, ma al momento, i dati sono condivisi tra entrambi i coniugi; 
al subentro avete inviato correttamente i dati dei coniugi, ma le date del matrimonio non erano congruenti; questo ha innescato un caso di riconciliazione molto particolare.
Dopo il subentro, avete effettuato (direi lecitamente),  diverse modifiche su un coniuge, e soltanto una sul secondo coniuge; questo, purtroppo, ha messo in evidenza l'errore di cui parlavo della riconciliazione post-subentro, errore che, grazie alla vostra segnalazione, abbiamo prontamente eliminato.
Se aveste effettuato la consultazione per il soggetto idanpr 47498678, anzichè per il soggetto idanpr 47498676, non vi sareste accorti dell'errore.
Per la verifica di future incongruenze, potrebbe essere utile la consultazione per entrambi i coniugi.
La soluzione può essere solo applicativa, ma segnalarci prontamente le incongruenze riscontrate, ci aiuta a rendere sempre più efficiente sistema.
Vi ringraziamo per la collaborazione.
