### ISSUE TITLE
[3002] ricerche alla data ed eventi mancanti

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1214]
Ambiente di test, comune di Poggio a Caiano.

In data 10/12/2018 con l'operazione ID 18804458 è stato mutato il soggetto ID ANPR 18913983 da VEDOVO a CONIUGATO.

Se oggi faccio una ricerca con il 3002 usando come data riferimento 1/1/2018 (quindi precedente alla data del nuovo matrimonio) il soggetto mi viene riportato correttamente come VEDOVO ma con i dati di matrimonio relativi a quello valido dal 10/12/2018.

Potete verificare ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
abbiamo riscontrato un piccolo malfunzionamento, avviseremo quando sarà possibile riprovare

**Comment by frmariani** [comment]
il malfunzionamento è stato rimosso, potete riprovare.
Grazie per la segnalazione.

**Comment by busaster** [comment]
Confermo che ora la ricerca mostra i dati corretti.
Grazie.
