### ISSUE TITLE
ISCRIZIONE ANPR SENZA COGNOME E SUCCESSIVA MUTAZIONE DATI

### ISSUE THREAD

**Issue by Monte052015** [italia/anpr#1216]
1 Errore Anpr Cod: EAM28 - Altri soggetti individuati in AT dai NUOVI dati anagrafici, richiesta di variazione dati non effettuabile - Cognome: XXXX Nome: XXXXX CF: XXXXXXXXXXXXXXX -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-03-22 14:16:15 , idOperazioneANPR 58932452 - Cognome: XXXX Nome: XXXXX CF: ZZZZZZZZZZZZZ -
Questa segnalazione appare su una procedura di Mutazione tutti i dati per un cittadino indiano già iscritto in APR senza cognome e con un codice fiscale che inizia con XXX al quale vanno registrate nuove generalità comprendenti il cognome e assegnato un nuovo codice fiscale

**Comment by rvinzani** [comment]
Salve, in questi casi suggeriamo di cancellare il soggetto per altri motivi indicando nelle note la non correttezza del CF. Si effettua successivamente una nuova iscrizione con richiesta attribuzione omocodice. L'alternativa è di comunicare al cittadino di recarsi presso uno sportello di Agenzia Entrate per farsi rilasciare un omocodice e successivamente modificarlo in ANPR nel momento della risoluzione dell'omocodia

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso ci fossero ulteriori richieste di chiarimento si prega di aprirne un'altra facendo riferimento alla stessa.

**Comment by LORELLAB** [comment]
Come è stato risolto questo caso ne ho uno perfettamente uguale
