### ISSUE TITLE
[5008] conflitto di eventi in unione civile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1217]
Ambiente di test, comune di Poggio a Caiano

Abbiamo un soggetto divorziato senza avere in ANPR i dati di divorzio.
Queste sono le informazioni che il comune aveva all'atto del subentro di test.

Oggi provo ad unirlo civilmente con altro soggetto (id operazione ANPR 19083360) ottenendo pero "EN272 : [...]  risulta gia' coniugato o unito civilmente con un altro soggetto".
Questo è causato dalla mancanza dei dati di divorzio ? 
Non sarebbe possibile spostare il controllo di compatibilità degli eventi sullo stato civile del soggetto ?

Grazie

**Comment by rvinzani** [comment]
Lo stato civile come noto è indipendente dall'acquisizione degli estremi degli atti e deve essere modificato consapevolmente dall'ufficiale di anagrafe.
Sui certificati invece vengono riportati gli estremi degli atti dello stato civile e l'assenza o l'incongruenza degli stessi produrrebbe un'errata certificazione

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso ci fossero ulteriori richieste di chiarimento si prega di aprirne un'altra facendo riferimento alla stessa.
