### ISSUE TITLE
[5008] richiesta di cessazione unione civile che non esegue la cessazione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1218]
Ambiente di test, comune di Poggio a Caiano

Tento di cessare un'unione civile per decesso con l'operazione ID ANPR 19083471.
Par andare tutto a buon fine ma se consulto con il 3002 il soggetto (ID operazione 19083472) nel XML che viene ritornato manca in toto l'informazione sullo scioglimento dell'unione civile, mentre lo stato civile è correttamente GIA' IN UNIONE CIVILE PER DECESSO.

Potete verificare ?

Grazie

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato il problema che riguardava solo la consultazione del dato e non la sua registrazione.
Potete riprovare?
Grazie in anticipo.

Assistenza ANPR

**Comment by busaster** [comment]
Il dato ora è presente.
Grazie.
