### ISSUE TITLE
[4005]

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1219]
Ambiente di Test
Id Operazione ANPR: 19088080

Stiamo testando il nuovo servizio 4005, lo stiamo usando come il vecchio servizio 3003,
nel farlo ci viene restituito il seguente errore:
"Data finale della richiesta  25-03-2019 minore della data iniziale   25-03-2019 o maggiore della data di sistema  25-03-2019"
Potete verificare?

Ne approfitto per chiedervi anche un'altra informazione, nel campo "DettaglioDati" si possono indicare i seguenti valori: ID, RICHIESTA, RISPOSTA, TUTTO.
Se avessi bisogno di ID e RISPOSTA, cosa devo indicare? con quale sintassi?

Ringrazio anticipatamente

**Comment by mttfranci** [comment]
Stiamo verificando la vostra segnalazione.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Salve, c'era un piccolo problema sia nel messaggio diagnostico che mostrava solo la parte dell'anno / mese / giorno. Detto questo, richieste molto vicine all'ora attuale potrebbero fallire in caso di disallineamenti di ora minimi tra client e server.
        <dataOraRichiesta>2019-03-25T09:52:28.838+01:00</dataOraRichiesta>
          <periodoRiferimentoRichieste>
            <dataOraIniziale>2019-03-25T00:00:00.000+01:00</dataOraIniziale>
            <dataOraFinale>2019-03-25T09:52:28.838+01:00</dataOraFinale>
          </periodoRiferimentoRichieste>
In ogni caso potreste  riprovare?
Grazie in anticipo.

**Comment by SAlberto** [comment]
Abbiamo riprovato, non ci ha più dato problemi, 
però eseguendo la seguente operazione:
idOperazioneANPR: 19091706 l'ElencoRisposte è vuoto, ma dal portale vediamo una notifica del 25/03/2019, ci aspettavamo di ritrovarla nella risposta.

Potete verificare?
Grazie

**Comment by mttfranci** [comment]
Salve il servizio è asincrono ora.

La risposta contiene : 
        `<statoRichiesta>0</statoRichiesta>
        <idOperazioneANPR>19091706</idOperazioneANPR>
        <dataDisponibilita>2019-03-27T15:26:44.534+01:00</dataDisponibilita>`

Nell' xsd è indicato che gli stati possibili sono  
		0 - Inserita
		1 - In elaborazione
		2 - Completata con esito positivo
		3 - Completata con esito negativo
		99 - Richiesta terminata con errore

E che la data prevista di disponibilità sarà : 
        <dataDisponibilita>2019-03-27T15:26:44.534+01:00</dataDisponibilita>

Alcune indicazioni di base sul nuovo servizio sono state date anche nella issue #1161

Dovreste interrogare nuovamente il servizio il servizio in modalità verifica, preferibilmente dopo la data di disponibilità. (La fornitura potrebbe essere pronta prima, ma tenete presente che queste sono le prime richieste e stiamo ancora ritoccando alcuni aspetti per velocizzare la produzione e per salvaguardare l'operatività durante il periodo di maggior carico giornaliero).

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
