### ISSUE TITLE
Certificati soggetti AIRE

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#122]
Data test 19/04/2017 - Ambiente test presubentro
Al momento per gli AIRE sono disponibili il certificato di residenza ed il certificato di stato di famiglia. 
E' necessario poter stampare anche i certificati di esistenza in vita, cittadinanza e stato libero per i soggetti AIRE nel caso in cui il soggetto si trovi in Italia ed abbia necessità dei suddetti documenti. 
Grazie 
Amprimo, Gillone, Guarraia - Comune di Torino

**Comment by rvinzani** [comment]
Per le certificazioni rilasciabili agli iscritti AIRE si fa rinvio all'art. 7 L. 27/10/1988, n. 470.

Il certificato di cittadinanza è di competenza dell’ultimo comune di residenza fino alla data di emigrazione, e dell’autorità consolare dopo (art. 16, 9 dPR 572/1993).

Per altre eventuali certificazioni AIRE andrebbe tenuta presente l'ormai lontana circolare ISTAT n. 22/1969 (in parte superata dalla L. 470/1988, ma non per gli aspetti che qui si considerano) che individua la competenza per talune certificazioni sia dell'autorita' consolare nella circoscrizione in cui la persona ha la propria residenza all'estero (art. 7 dPR 200/1967), tra cui quella relativa alla condizione di stato, desumibile dalle risultanze dello schedario di cui all'art. 67 dPR 200/1967.
In definitiva, non ha importanza se una persona iscritta AIRE si trovi in Italia e richieda dei certificati, è importante invece il suo status giuridico (cioè se residente in Italia o all’estero).

**Comment by rvinzani** [comment]
Chiudo la issue in quanto non necessario alcun intervento. In caso di richiesta di ulteriori chiarimenti si prega di aprire un'altra issue facendo riferimento a questa stessa

**Comment by Demografico1975** [comment]
Però in questo chiarimento si fa riferimento a normative ora abrogate che non si applicano più. Inoltre lo stesso DPR 223/1989 all'art. 33 nella nuovo formulazione dice: "...l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, nonché' ogni altra informazione ivi contenuta", che pare quindi comprendere anche i cittadini AIRE.
