### ISSUE TITLE
Codici Istat Comune di Alassio

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1220]
Durante le verifiche sui dati per il pre subentro del comune di Alassio (SV) abbiamo osservato che la tabella 3 archivio comuni contiene due righe del comune di Alassio con altrettanti codici Istat.

Dal 17/03/1861 ALASSIO (GE) - codIstat 010830
Dal 12/01/1927 ALASSIO (SV) - codIstat 009001

Non ho trovato il codice 010830 nelle pubblicazioni Istat.
Lo stesso comune di Alassio non ricorda di aver visto questo codice.
Ci sono numerosi altri casi che sembrano simili, come ad esempio Busto Arsizio (MI) - codIstat 015990.

E' una codifica adottata da Sogei per ANPR oppure non conosco qualcosa?

Grazie.
Filipazzi - Maggioli

**Comment by CarlaMusian** [comment]
Si trovano nel sito Istat:
https://sistat.istat.it/sistat/gestioneComuni.do

Sistema Informativo Storico delle Amministrazioni Territoriali,
facendo Ricerca Libera, Comuni, Storia dei Comuni

Carla Musian

**Comment by bfilipazzi** [comment]
Grazie
