### ISSUE TITLE
[3002] mancanza dei dati di vedovanza in consultazione storica

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1221]
Ambiente di test, comune di Poggio a Caiano

Al soggetto DI ANPR 9453796, vedovo, oggi 25/03/2019  inseriamo un nuovo matrimonio con una chiamata 5008 (id ANPR 19088726).
Se consultiamo la scheda individuale ad oggi col 3002 i dati sono corretti, se però la consultiamo con data riferimento ieri (id ANPR 19088737) viene presentato il corretto stato civile VEDOVA ma non vengono restituiti gli estremi di vedovanza.

Potete verificare ?
Grazie

**Comment by azabatta** [comment]
Buongiorno, 
il problema sulla consultazione storica dei matrimoni  è già stato rilevato: è  stata effettuata una correttiva che  è in fase di test. L'avviseremo appena sarà possibile riprovare negli ambienti di test esposti.
Buona giornata

**Comment by azabatta** [comment]
Buonasera, la modifica è stata trasferita negli ambienti di test esposti. E' possibile riprovare.
Restiamo in attesa di un suo cortese riscontro.

**Comment by busaster** [comment]
Confermo il corretto funzionamento della ricerca storica.
Grazie
