### ISSUE TITLE
[3003] Elenco Operazioni - Errore EN122

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1223]
ambiente di PRODUZIONE - comune di FAENZA (039010)

quanto segnalato in ambiente di TEST con la issue #1204 , sembra verificarsi anche in ambiente di produzione.
esempio idOperazioneComune (ws 3003) 
- 2019303880
- 2019303876
si tratta di soggetti che hanno avuto mutazioni recenti, per i quali la richiesta ritorna l'errore:
EN122 - E - La richiesta effettuata non produce alcun risultato

il cliente sta lavorando con codDestinatario ANPR01, ma abbiamo visto che l'errore si manifesta anche con ANPR02.

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato il problema, potreste riprovare?
Grazie

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
abbiamo riprovato e adesso l'elenco delle operazioni viene restituito dal web-service.

**Comment by mttfranci** [comment]
Perfetto.
Saluti

Assistenza ANPR
