### ISSUE TITLE
Impedire la 5001 in altro comune quando si tratti di convivenza?

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1224]
Buongiorno
Segnalazione di un problema odierno per una vostra valutazione.
Un poliziotto (residente in anpr in convivenza) si sposta in altro comune per costituire una nuova famiglia (non convivenza). Interpretiamo erroneamente i dati e non gestiamo bene il caso, non recependo che faceva parte di una convivenza, ed è stata fatta una 5001 (id operazione anpr 59200152) . Ovviamente correggiamo il nostro errore; annulliamo e rifacciamo l'operazione.

Il problema però mi ha portato a chiedermi : ha senso permettere la 5001 di una convivenza da un comune all'altro ? Ve lo segnalo per questo motivo: se è meglio bloccare questo servizio, oppure può aver senso permetterlo.

**Comment by rvinzani** [comment]
Non abbiamo mai avuto indicazioni dal Ministero di bloccare questo tipo di mutazioni

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso ci fossero ulteriori richieste di chiarimento si prega di aprirne un'altra facendo riferimento alla stessa.
