### ISSUE TITLE
[3003 in ANPR01] mancano operazioni nei risultati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1227]
Ambiente di test, comune di Poggio a Caiano

Facciamo oggi una ricerca delle operazioni N010 con stato lavorazione 7 (Notifiche da prendere in carico) con filtro data dal 26/03/19 al 28/03/19. Non ritorna nessun risultato (id operazione ANPR 19095410).
Questa operazione è quella che eseguiamo da sempre per recuperare le notifiche.
Se però ricerchiamo da webapp tramite "Monitoraggio operazioni" abbiamo due notifiche N010 prodotte il 27/03.
queste notifiche però hanno stato "Completata con esito positivo" il che è una novità.

Potete verificare ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by busaster** [comment]
Aggiungo una informazione : modificando il filtro stato lavorazione nella chiamata 3003 da "7" a "9" (tutte) le due notifiche vengono ritornate con stato lavorazione "8" (fruite) e con il campo "xmlRisposta" vuoto.
Le due notifiche non sono però mai state "processate" in nessun modo da noi.

**Comment by fferraguto** [comment]
Salve,
può riprovare l'operazione per cortesia?
Saluti.

**Comment by busaster** [comment]
il 3003 risponde con errore 998 : servizio non disponibile

**Comment by mttfranci** [comment]
Salve, potreste riprovare di nuovo?

**Comment by busaster** [comment]
Il servizio ora torna una risposta con le 2 notifiche anche con il filtro statoLavorazione = 7.
Però entrambe le notifiche hanno il campo "xmlRisposta" vuoto

**Comment by mttfranci** [comment]
Salve, stavolta dovremmo aver individuato il problema.
Potete provare ancora una volta?
Grazie

**Comment by busaster** [comment]
ok, notifiche trovate e complete del loro xml.
Il problema è limitato all'ambiente di test o può essersi verificato anche in produzione ?

**Comment by mttfranci** [comment]
Grazie per il riscontro.
Il problema sicuramente non è mai stato presente in produzione.
Però potrebbe essere capitato anche in presubentro.
Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Buongiorno,
in ambiente PROD Bistagno (AL) è stata fatta da poco una chiamata (IdOpComune: ServLoc1004727) al ws3003 (ANPR01) per sapere quali sono le operazioni N010 dal 15/03/2019 ad oggi. La risposta (IdOpAnpr: 66958298) non restituisce alcun risultato. 
La stessa richiesta era stata fatta l'altro ieri (08/04/2019) e restituiva 4 risultati (IdOpAnpr: 66322832). 
Posso avere un riscontro? Grazie

**Comment by mttfranci** [comment]
@Eduardo1977 e' stata effettuata una correzione che impattava negativamente sulle performance. (#1227)
Da specifiche per le notifiche vanno indicati gli stati lavorazione 7/8/9 mentre nella vostra richiesta è stato indicato '2'.
In effetti tale valore veniva erroneamente elaborato in precedenza, ma non è un valore valido per le notifiche.

`<statoLavorazione>2</statoLavorazione>
<operazioneRichiesta>N010</operazioneRichiesta>`

Vi invitiamo a indicare uno dei valori previsti nelle richieste ai servizi 3003/3007/4005.

Siamo a disposizione per ogni ulteriore chiarimento.

Assistenza ANPR

**Comment by Eduardo1977** [comment]
@mttfranci ho già provato con 9  e ritrovo le 4 emigrazioni di prima. Grazie per l'aiuto e la disponibilità
