### ISSUE TITLE
Rigetto di un rimpatrio a cavallo del subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1228]
Ambiente di produzione, comune di Bellusco

Il comune aveva in corso una pratica di iscrizione in ANPR per rimpatrio dalla sua AIRE al momento del subentro.
Il soggetto relativo dunque è subentrato in ANPR come residente nel comune (APR).
Oggi a seguito di accertamenti negativi la pratica deve essere rigettata ed il soggetto deve tornare ad essere AIRE.
Questo comporta una modifica della famiglia, della residenza, delle loro decorrenze, della data di iscrizione e del suo motivo, nonché dell'integrazione dal caricamento dei dati propri dell'AIRE che in ANPR oggi non ci sono.
Come si può gestire una simile operazione  ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by ncapozzi** [comment]
Buongiorno,
il Comune dovrebbe effettuare una cancellazione 2003 per Ripristino posizione precedente seguita da una reiscrizione AIRE per altri motivi A002 con indicazione dell'idsoggettoANPR attribuito al subentro alla data di decorrenza effettiva.
N. Capozzi

**Comment by ncapozzi** [comment]
Non avendo ricevuto ulteriori osservazioni si chiude la issue.
N. Capozzi
