### ISSUE TITLE
Ripristino parziale

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#1229]
Ambiente Test

Cancellazione per emigrazione di una famiglia di due persone in comune non subentrato,
A seguito dell'accertamento del comune di migrazione si deve rigettare parzialmente l'emigrazione perché solo 1 persona risulta residenti all'indirizzo.
Provando ad effettuare il ripristino parziale riceviamo la risposta "EN077: L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa.

Come possiamo ovviare al problema.
Grazie.

**Comment by frmariani** [comment]
per poterla aiutare avrei bisogno di qualche informazione sull'operazione;
per favore mi indichi l'identificativo ANPR dell'operazione o del soggetto o della famiglia.
grazie.

**Comment by Antonino09** [comment]
Salve,
l'identificativo ANPR dell'operazione è il seguente 2064218, mentre l'identificativo ANPR  del soggetto è 7413844.

**Comment by frmariani** [comment]
gentilmente verifichi le informazioni inviate:
ho verificato in ambiente di test comuni e pre-subentro ma non trovo ne l'operazione ne l'identificativo del soggetto.
 Per favore mi indichi il Comune.
grazie

**Comment by Antonino09** [comment]
Mi scusi per errore ho indicato Test ma l'ambiente ANPR utilizzato è FREE.

**Comment by frmariani** [comment]
a valle del subentro, i due soggetti, sono stati oggetto di riconciliazione del matrimonio;
per questo motivo, la cancellazione di un coniuge, interessa necessariamente anche l'altro coniuge; 
in questo particolare caso, essendo un ripristino parziale, l'unica operazione possibili è la re-iscrizione del soggetto con indicazione dell' idanpr precedentemente assegnato; 
se il ripristino non fosse stato parziale, le avrei consigliato di annullare prima la cancellazione del secondo coniuge (operazione idanpr 2064216) e poi quella del primo coniuge (operazione idanpr 2064215).
Mi faccia sapere.

**Comment by Antonino09** [comment]
Effettivamente abbiamo verificato che in altri casi il ripristino parziale funziona ad esempio nel caso di una famiglia composta da padre e figlio.
A questo punto mi potrebbe indicare quali possano essere le cause per cui il ripristino parziale non può essere eseguito.

**Comment by frmariani** [comment]
In ANPR siamo soliti indicare come "Ripristino parziale", una "Mutazione di Residenza" che ha coinvolto più componenti di una famiglia e si è conclusa con un  accertamento parzialmente negativo;
in questo caso si può utilizzare l'annullamento dell'operazione di Mutazione di Residenza, indicando che si tratta di "Ripristino posizione anagrafica "  e di "Ripristino parziale".
Nel vostro caso, state effettuando delle operazioni di annullamento di cancellazioni per altri motivi: l'operazione seguirà i controlli previsti per questa tipologia di operazione, che sia parziale o meno è irrilevante.
