### ISSUE TITLE
Web App - Certificazione in esenzione da imposta di bollo

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#123]
Ambiente di test - Data test: 20/04/2017
Abbiamo richiesto la stampa di un certificato di stato di famiglia per il soggetto ID ANPR 1016087 indicando l'esenzione dall'imposta di bollo per "Altro motivo di esenzione".
Il sistema ha prodotto il certificato Protocollo ANPR 461422 sul quale però, accanto all'indicazione "Esente da imposta di bollo" non viene riportato quanto indicato nel campo obbligatorio "Descrizione esenzione bollo". Analogo risultato è stato ottenuto anche nel caso di richiesta di certificato in esenzione sia da bollo che da diritti selezionando "Altro motivo di esenzione" (Protocollo ANPR 461434).
Sarebbe possibile indicare anche tale informazione sul certificato, al pari di quanto viene fatto selezionando un uso codificato nella tabella 39?

Segnalo inoltre che il codice 99 non è stato integrato sulla tabella di decodifica 39.

Grazie,
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Le note del comune non vengono riportate nella stampa su esplicita indicazione del Ministero dell'Interno. Aggiungeremo il codice 99.
