### ISSUE TITLE
[3002] Richiesta Scheda Convivenza - Errore ANPR

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1230]
ambiente di PRODUZIONE - comune di RIVOLI (001219)

x verifiche relative a soggetto interessato da emigrazione, si invia richiesta dell'elenco componenti di una convivenza residente in altro comune con ws 3002 e schedaAnagraficaRichiesta = 4

il web-service va in errore.

ci viene da pensare possa dipendere dalla numerosità dei componenti, xchè non ci sono errori codificati, ma di fatto il ws non ritorna risposta.

l'idOperazioneComune a cui fare riferimento è il 2019303883

potete verificare?

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, 
da una verifica effettuata sull'operazione indicata, comunichiamo che l'operazione di consultazione fatta da gestionale con la vecchia modalità di interrogazione (ANPR01) ha impiegato più di 1 minuto per la restituzione della risposta. La risposta è stata correttamente prodotta da ANPR ma a causa dei tempi di elaborazione alti, la richiesta è andata in timeout.
Potete riprendere la risposta già elaborata, effettuando una consultazione con stesso idOperazioneComune indicato, in modo da sfruttare il meccanismo di retry.  Alternativamente potete utilizzare la consultazione disponibile dal sito web ANPR, che utilizza già il nuovo meccanismo di interrogazione ottimizzato (ANPR02) come da specifiche; a tale riguardo fare riferimento alle issue #1031 , #1050

**Comment by AMonopoliADS** [comment]
grazie del riscontro.
usare il meccanismo di retry può andare bene x il singolo caso, ma non è una strada percorribile lato operatore.
abbiamo visto che la response viene valorizzata senza errori interrogando sul ramo ANPR02 anche tramite web-service.
quindi cerchermo di mettere in linea questa modalità quanto prima.

grazie.
Alessandro
