### ISSUE TITLE
[3003] 998 Servizio non disponibile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1231]
Ambiente di test, comune di Poggio a Caiano
Chiamate in versione ANPR01

Una ricerca operazioni con filtro sul codice fiscale del soggetto restituisce l'errore 998 (id operazione ANPR 19097916).
Ricerche fatte con filtri diversi (es la id ANPR 19097914) funzionano.

Potete verificare ?
Grazie

**Comment by mttfranci** [comment]
Ieri, verso le 11.30, abbiamo rilasciato una patch come coda della risoluzione della issue #1227. 
Potete verificare se avete ancora questo problema? 
Grazie in anticipo
Assistenza ANPR

**Comment by busaster** [comment]
Confermo che la ricerca ora funziona correttamente.
Grazie
