### ISSUE TITLE
4005 : risultati disponibili il giorno dopo

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1232]
In ambiente di test ho eseguito alcune chiamate di prova al servizio 4005.
Ho notato che per tutte le chiamate che ho fatto mi ha ritornato come "dataDisponibilita" esattamente un giorno dall'istante della richiesta.
Mi sembra un tempo piuttosto largo.
Si può fare qualcosa per ridurlo ? 

Grazie

**Comment by mttfranci** [comment]
Salve,
il servizio 4005 e' stato rilasciato di recente e la data di disponibilita' indicata e' stimata in maniera cautelativa.
In generale la fornitura sara' pronta prima del tempo indicato.
Da tenere presente che in base a vari fattori, come il carico generale di sistema e il numero di richieste, le richieste asincrone potrebbero essere rimandate a dopo l'orario di ufficio o alla notte.
Saluti
Assistenza ANPR

**Comment by busaster** [comment]
ritorno su questo argomento. Ho richiesto in data 5/4 l'elenco di tutte le operazioni svolte dalle 17 del 4/4 alle 17 del 5/4. La prima previsione di disponibilità era il 6/4, da allora ad ogni verifica status è andata ad aumentare, arrivando oggi al 10/4. Dobbiamo aspettarci tempistiche così lunghe  ?

**Comment by mttfranci** [comment]
Buongiorno, avete ragione.
In effetti c'era una anomalia nel software di generazione.
A breve introdurremo degli alert che ci permetteranno di intervenire celermente in queste situazioni.
Ma in questa fase le vostre segnalazioni sono particolarmente utili.
Se ci sono problemi con il risultato delle elaborazioni potete segnalarcelo senza problemi.
Saluti

Assistenza ANPR
