### ISSUE TITLE
[A006] Errore 999 Operazione non effettuabile

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#1233]
Salve,

Ambiente di TEST di ROCCABIANCA
data 2019-04-01 17:14:46
idOperazioneANPR 19105162

Provando un trasferimento da AIRE di altro comune subentrato otteniamo sempre l'errore 999, potete aiutarci a capire qual è il problema?

Grazie
Monia Pedrazzoli 
APKAPPA

**Comment by ncapozzi** [comment]
Buonasera,
il servizio A006 va in errore quando nella richiesta è presente idSchedaSoggettoComune. La correzione verrà rilasciata la prossima settimana.
Nel frattempo per riprovare il test basta togliere idSchedaSoggettoComune dalla richiesta.

N. Capozzi
