### ISSUE TITLE
[3003] ricerca per codice fiscale ed errore EN095

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1234]
Ambiente di produzione, comune di Caronno Pertusella.

Il comune deve cancellare con il nostro applicativo un soggetto per doppia iscrizione.
per fare questo il nostro applicativo come prima cosa cerca per codice fiscale.
Da qualche giorno nel caso in cui ANPR trovi più soggetti con lo stesso codice fiscale , il servizio 3002 risponde con un errore "EN095 : La richiesta per dati di un soggetto ha individuato piu' cittadini: restringere i parametri della ricerca" (id operazione ANPR 59663786).  
Questo comportamento non si verificava fino a poco tempo fa e non mi sembra corretto.

Potete verificare ?
Grazie.

**Comment by rvinzani** [comment]
L'identificativo operazione è relativo ad un servizio 3003

**Comment by busaster** [comment]
Chiedo scusa, ho mescolato due segnalazioni....
Modifico di conseguenza questa issue : il servizio in questione è il 3003 che noi usiamo nella circostanza per capire se il soggetto AIRE ha avuto delle operazioni in ANPR dal subentro in avanti, con lo scopo di capire se è utilizzabile il servizio 5008 con tipo mutazione 21.
Il problema rimane lo stesso.

**Comment by rvinzani** [comment]
Il servizio prevede di restituire le operazioni effettuate sui soggetti compresi quelli cancellati. Nel caso specifico sono presenti due schede per lo stesso codice fiscale. E' necessario pertanto inserire nella richiesta l'idANPR

**Comment by busaster** [comment]
ma nelle specifiche excel della 3003 il campo "id anpr" non è previsto come filtro su parametriRicercaSoggetto, o sbaglio ?

**Comment by rvinzani** [comment]
Mi scuso, stiamo effettuando l'intervento per aggiungere il campo ma tale intervento non è stato ancora rilasciato

**Comment by rvinzani** [comment]
Il campo id anpr è stato inserito come parametro di ricerca perciò chiudo l'issue. In caso fossero necessarie ulteriori indicazioni si prega di aprire una nuova issue facendo riferimento a questa stessa
