### ISSUE TITLE
[web-app] Amministrazione - Gestione Dati del Comune - Parametri utilizzati per l'emissione dei certificati

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1235]
richiesta di chiarimenti

nella funzione indicata in oggetto, andiamo normalmente ad attivare il check "Certificati esenti dai diritti di segreteria:" per attivare la gestione "mista" dell'addebito dei diritti di segreteria.
(come indicato nella documentazione, paragrafo 17.1.5.2)

questa mattina - in ambiente di test - ho notato una nuova opzione (che, a onor del vero, non so se sia in effetti nuova perchè non vado abitualmente sulla web-app...): 
"Esenzione diritti per certificati online:"
... della quale però non mi sembra ci siano dettagli nella documentazione.

probabilmente mi sono perso qualche issue al riguardo, ma se possibile vorrei capire in quali casi ha senso attivare questa opzione.

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Si tratta di una impostazione che abbiamo predisposto per la futura gestione del rilascio dei certificati on line. Per adesso non è utilizzato

**Comment by AMonopoliADS** [comment]
grazie Roberta.

a questo riguardo, stiamo tentando di attivare il check per il comune di MALNATE (012096) - ambiente di PRODUZIONE.
una volta attivato il check, alla pressione del bottone "Conferma", compare il messaggio di errore "Deve essere inserito almeno un Ip da Abilitare nella sezione Informazioni Aggiuntive. "
... ed il client non riesce a completare l'operazione...

come possiamo fare?

grazie

**Comment by rvinzani** [comment]
Deve essere inserito l'ip del comune già comunicato al momento del subentro.

**Comment by AMonopoliADS** [comment]
essendo dati già in vostro possesso, non sarebbe possibile popolare questo campo in maniera automatica?

noi intanto avvisiamo il cliente... ma l'operatore probabilmente non conosce questa informazione, gliela daremo noi (recuperandola dalle pratiche del subentro) e faremo fare a lui l'operazione (perchè non abbiamo accesso alla web-app in produzione...)

valutate l'opportunità di semplificare questo procedimento.

grazie mille 
Alessandro

**Comment by rvinzani** [comment]
Sì, ci stiamo lavorando, a breve lo aggiungeremo l'informazione, per adesso passatela voi. Grazie

**Comment by rvinzani** [comment]
Chiudo l'issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
