### ISSUE TITLE
Notifiche N031 - errore EN115

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#1236]
Buongiorno

da alcuni giorni (13/03) l'elaborazione di estrazione dei comuni subentrati (Notifica N031) dà questa tipologia di  errore.
Primo servizio richiamato
servizio 3007 di estrazione notifiche N031 - 
Richiesta : idOperazioneComune 20190402014117706240 - 
Risposta : idOperazioneANPR 61092596 con esito 0000 ha estratto 6 codici operazioni ANPR
Secondo servizio richiamato (e seguenti)
servizio 3003 di estrazione singola operazione N031
Richiesta :  idOperazioneComune 20190402014118278062
Risposta :  idOperazioneANPR 61092598 con esito XXXX codiceErroreAnomalia EN115 - La richiesta  ha individuato un numero di occorrenze troppo elevato: restringere i parametri della ricerca.

In altre giornate, come il 15/03, invece, alla richiesta di servizio 3003, con numero operazione specificato, la risposta ha dato codiceErroreAnomalia EN122 - La richiesta effettuata non produce alcun risultato. 

Potreste aiutarci a capire cosa è successo?
La richiesta riveste carattere di urgenza poiché l'informazione di comune subentrato è fondamentale nella gestione delle residenze.

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando l'operazione effettuata. 
Non appena possibile forniremo una risposta

**Comment by asqueglia** [comment]
Buongiorno, abbiamo apportato una fix in tutti gli ambienti esposti compreso produzione, che risolve il problema segnalato. E' ora possibile riprovare. Grazie per la segnalazione.
Per quanto riguarda il flusso da voi indicato per le estrazioni delle notifiche N031, suggeriamo di utilizzare direttamente il servizio 3003 impostando come criterio di ricerca l'intervallo temporale, anziché utilizzare prima il 3007 per ottenere la lista degli identificativi e poi il 3003 per ogni identificativo.

**Comment by ANPRCdMI** [comment]
Buon pomeriggio
dopo l'installazione della fix, l'elaborazione non restituisce più l'errore EN115, ma perché non va a buon fine, con una segnalazione interna "Could not send message" , in pratica un timeout. 
Vedere idOperazioneComune 20190405011846115958 del 05/04/2019, che conteneva la richiesta di estrazione dei dati del idOperazioneANPR 64403993   

Grazie
Raffaella Tremolada
 S.I. per Comune di Milano

**Comment by mttfranci** [comment]
Salve.
L'idOperazioneComune 20190405011846115958 a noi sembra elaborata correttamente con idOperazioneANPR 65612677 in meno di 0,5 secondi.
Avete modo per verificare che non ci sia stato un time out lato client o qualche altro tipo di errore?
Grazie in anticipo.
Saluti

Assistenza ANPR

**Comment by ANPRCdMI** [comment]
Buon pomeriggio
Errata corrige
Il numero operazione 20190405011846115958 effettivamente è andato a buon fine, si tratta del servizio 3007che ha restituito 7 codici idOperazioneANPR.
L'errore si è verificato sul primo servizio 3003 successivo, con idOperazioneComune 20190405011846631320 per la ricerca dell'ilOperazioneANPR 64403993.
Se vado in Utilità e notifiche per visualizzare l'operazione sopra indicata vedo STATO=Inserita e CONTENUTO=Non disponibile. 
C'è forse qualche errore nel formato del servizio o nei valori passati per la ricerca che non riusciamo ad individuare?         

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by ANPRCdMI** [comment]
Abbiamo rilanciato l'elaborazione di recupero del giorno 04/04/2019 e ha funzionato: il 3007 ha estratto 7 codici idOperazioneANPR e i 3003 relativi sono andati tutti a buon fine. 

Grazie!
Raffaella Tremolada
S.I., per Comune di Milano
