### ISSUE TITLE
[3002 test] Operazione non effettuabile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1237]
ambiente di TEST - comune di FAENZA (039010)

idOperazioneComune 2019301143
il web-service risponde con errore 999 - E - Operazione non effettuabile

apparentemente nessuna cosa strana.
altre richieste con altre generalità vanno a buon fine.
la richiesta con questo nome in particolare va in errore.

grazie.
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
Il problema è risolto. Può riprovare

**Comment by AMonopoliADS** [comment]
problema risolto in generale, anche x l'ambiente di produzione? oppure potrebbe riverificarsi?
la chiamata comunque adesso ritorna la response.

grazie

**Comment by amollicone1982** [comment]
In produzione non puo' verificarsi.
