### ISSUE TITLE
Rettifica indirizzo di pratica a cavallo subentro (EN237 EN239 EN526)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1239]
Ambiente di produzione id cittadino anpr 37742520.
Questo cittadino dichiara residenza a Desenzano (non subentrato) 8 gennaio.
Il 15 gennaio il comune di Vigonza (subentrato) lo cancella, in quanto ha ricevuto apr4 da Desenzano.
1 aprile Desenzano subentra, la pratica (procedimento non aperto in anpr) era rimasta da evadere nell'arretrato.
Nel confermare la pratica, occorre cambiare il civico da 11 a 13, come accertato dal vigile (errore materiale del cittadino).

Non siamo riusciti nell'impresa, con tante prove.
Sembra che ci siano dei controlli che causano sempre un errore comunque correggiamo le date.
Il Comune ci chiede se è possibile evitare di fare una nuova mutazione di residenza con data 1 aprile, e correggere la residenza dal 8 gennaio?

le ultime prove fatte sono gli id operazione anpr :

La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata (Codice: EN237)
Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 01-04-2019 (Codice: EN526)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-02 16:09:22 , idOperazioneANPR 61342965 (Codice: EN527)

La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata (Codice: EN237)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-02 17:13:39 , idOperazioneANPR 61365855 (Codice: EN527)

La data decorrenza della residenza deve essere uguale alla data decorrenza della richiesta (Codice: EN239)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-02 17:15:37 , idOperazioneANPR 61366364 (Codice: EN527)

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
c'è stato un problema di settaggio delle date in fase di subentro.
abbiamo eliminato l'anomalia, potete riprovare  con l'operazione di Rettifica/Integrazione indirizzo.
grazie

**Comment by MarcoMigliori** [comment]
rettificato, grazie
