### ISSUE TITLE
WebApp  Ricerca Avanzata per indirizzo Convivenza

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#124]
Data test 18/04/2017 - Ambiente test (dptest)
Effettuato ricerca indirizzo  "Via Monfalcone 172" dove è presente una convivenza.
Nella videata "Elenco Intestatari/Responsabili" sono visualizzati tutti i soggetti presenti nella convivenza, invece dovrebbe visualizzare i soli Responsabili.
L'elenco è composto da due pagine, se si cerca di visualizzare la seconda pagina compare il messaggio di errore "Ricerca famiglie/convivenze dato un indirizzo - Nessun risultato trovato", riportanto alla videata di ricerca indirizzo anzichè procedere nella visualizzazione della seconda videata.
grazie 
Amprimo, Floramo, Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Può riprovare e darmi riscontro
