### ISSUE TITLE
Tabella 39 - Uso Assegni

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1244]
Un cliente ci scrive: "Devo stampare uno stato di famiglia uso assegni che deve essere rilasciato esente bollo ed esente diritti, ma nell'uso che vado a scegliere dalla tendina (nel gestionale) non c'è questa voce."
Ha contattato l'assistenza ANPR che l'ha invitato a chiederci di aprire una issue.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Se non previsto nelle casistiche indicate tra quelle disponibili è possibile indicare "altro motivo di esenzione" ed indicare nella descrizione il motivo specifico

**Comment by cvignati** [comment]
Scusate ma il Certificato di stato famiglia "uso assegni familiari" non è più previsto.
Deve essere presentata Dichiarazione Sostitutiva di Certificazione in quanto la pratica verrà istruita da INPS che non può ricevere certificati.

**Comment by bfilipazzi** [comment]
Grazie per il riscontro scritto.

**Comment by AMonopoliADS** [comment]
> 
> 
> Se non previsto nelle casistiche indicate tra quelle disponibili è possibile indicare "altro motivo di esenzione" ed indicare nella descrizione il motivo specifico

scusate se mi intrometto nella issue, anche se già chiusa.
ho letto con interesse e volevo segnalare che - per l'esperienza che abbiamo -  l'uso di "altro motivo di esenzione", pur prevedendo la descrizione specifica come dato aggiuntivo nell'xml, non la usa per la stampa del certificato, indicando invece sempre un generico "esente da imposta di bollo".
... a meno che non sia cambiato qualcosa di recente, ma per scrupolo ho voluto riprovare oggi stesso in ambiente di TEST, con lo stesso risultato.

grazie e scusate.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Sì, su indicazioni del Ministero non possiamo riportare sui certificati diciture a testo libero. La descrizione rimane come promemoria per il comune
