### ISSUE TITLE
ws [5008] - perfezionamento iscrizione a cavallo del subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1245]
Buon giorno,
stiamo simulando in ambiente TEST per il comune di Loreto Aprutino, subentrato in produzione in data 01/04, il completamento dei dati di una iscrizione per immigrazione avvenuta in data  28/03. Premettiamo che per riprodurre le situazioni da verificare in questa fase abbiamo effettuato, nella stessa data del subentro in produzione (01/04), un nuovo subentro anche in ambiente di test, con gli stessi file APR e AIRE.
Secondo le indicazioni riportate al capitolo 11.3.4 del documento di specifiche, abbiamo pertanto provato ad effettuare una mutazione 5008 con tipo 20 (id operazione comune 0680212019040312) indicando come data di decorrenza la data di iscrizione (il 28/03), ma otteniamo in risposta l'errore EN389 - "La data decorrenza 28-03-2019 dell'operazione non può essere inferiore alla data decorrenza 01-04-2019 dell'ultima operazione effettuata su dati relativi a generalità del soggetto"; sul soggetto però non è stata effettuata alcuna operazione, al di fuori del subentro avvenuto come detto in data 01/04.
Abbiamo provato quindi ad indicare come data di decorrenza dell'ultima operazione la data di subentro, ma questa volta otteniamo l'errore EN358 - "La data decorrenza del perfezionamento di un'iscrizione deve essere uguale alla data dell'iscrizione stessa 28-03-2019" (id operazione comune 0680212019040317).
Nelle specifiche è scritto che l'operazione deve essere effettuata con data di decorrenza "_uguale a quella dell’iscrizione a meno che non siano state effettuate altre mutazioni con data successiva all’iscrizione_" ma a questo punto i controlli attuali non dovrebbero considerare il subentro come operazione effettuata sul soggetto, altrimenti non vediamo alcun modo per portare a termine la mutazione.
In attesa di riscontro, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Buongiorno, la mutazione di completamento (perfezionamento di tipo 20) , viene utilizzata ai fini del perfezionamento di una iscrizione; il soggetto indicato ha subito un aggiornamento APR, infatti è stato tramesso in subentro con data di iscrizione 28-03-2019 e con data di ultimo aggiornamento APR 01-04-2019. 
In questo caso il perfezionamento non è il tipo di mutazione adatto alla pratica.  Potete lavorare la pratica con una ‘mutazione tutti i dati’ ( servizio 5008) scegliendo le tipologie di mutazione necessarie (anagrafica 01 ecc...) e utilizzando come data di decorrenza dell'operazione la data di ultimo aggiornamento APR comunicata in subentro 01-04-2019.

**Comment by Amucciarelli74** [comment]
Ok,
operando come da voi indicato siamo riusciti a portare a termine l'operazione di mutazione, vero è che da specifiche questa indicazione sinceramente non si recepisce con chiarezza, magari questa e altre situazioni a cavallo del subentro, che comportano una modifica della normale operatività, andrebbero approfondite nella documentazione.
Grazie, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by asqueglia** [comment]
La ringrazio per il suggerimento. Valuteremo come rendere più chiara la documentazione.
