### ISSUE TITLE
Scissione con creazione nuova famiglia

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1246]
Una coppia, residente con i genitori di lui, si è trasferita ad altro indirizzo, creando un nuovo nucleo familiare. Non si riesce a registrare il preliminare l'errore che fornisce ANPR è il seguente:
EF054 - I soggetti devono appartenere alla stessa famiglia 
codice operazione ANPR: 61542621

**Comment by frmariani** [comment]
la cittadina indicata nel cambio di residenza, è stata cancellata dal comune di Bitonto per doppia iscrizione, pertanto, anche se cancellata,  risulta presente nel sistema. 
questo genera un problema nel momento in cui la vostra richiesta viene effettuata con il CF ed i dati anagrafici, senza indicare ne' idcomunale ne' idanpr.
Sicuramente provvederemo ad eliminare l'anomalia, nel frattempo, se fosse urgente effettuare il cambio di residenza, vi consiglio di inserire nella richiesta  l'idanpr valido della cittadina.

**Comment by Finalmentesubentrati** [comment]
Abbiamo effettuato il cambio di residenza però abbiamo ancora problemi nella certificazione

**Comment by frmariani** [comment]
può indicarmi la tipologia del problema ?

**Comment by frmariani** [comment]
chiudo la issue
