### ISSUE TITLE
[A006] Trasferimento da AIRE di altro comune non aggiorna data iscrizione

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#1247]
Buongiorno,

WA ambiente di TEST VILLA MINOZZO
id operazione ANPR 19109778
e
WS ambiente di TEST ROCCABIANCA
id operazione ANPR 19109316

Prove effettuate in data odierna.
In entrambi i casi facendo un'iscrizione all'AIRE per trasferimento dall'AIRE di altro comune subentrato abbiamo notato che la data di iscrizione resta invariata.

Dato che nel caso di iscrizione all'APR per immigrazione da comune subentrato la data di iscrizione viene aggiornata, mi aspettavo che anche il passaggio da AIRE ad AIRE seguisse la stessa logica.

E' corretto il comportamento riscontrato oppure ho sbagliato qualcosa nell'inserimento dati?

Grazie
Monia Pedrazzoli
APKAPPA

**Comment by ncapozzi** [comment]
Buongiorno,
anche se cambia il comune di iscrizione, comunque il cittadino rimane iscritto AIRE e quindi residente all'estero. Addirittura potrebbe non cambiare la residenza effettiva. Per questo motivo la data iscrizione resta invariata. 
N. Capozzi
