### ISSUE TITLE
Variazione comune iscritto AIRE

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1248]
Su comunicazione del Consolato dobbiamo variare il comune di nascita di un cittadino AIRE non presente in Agenzia delle Entrate.
Anpr genera il seguente errore:
EAV91 - Soggetto non presente in Agenzia Entrate.
Come dobbiamo procedere?
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
nel caso di un cittadino AIRE non presente in Agenzia delle Entrate dovete effettuare la modifica senza richieder la validazione del CF (gestioneCF = 3 nella richiesta XML).
Cordiali saluti
Assistenza ANPR
