### ISSUE TITLE
Presenza dati di matrimonio per stato civile ignoto

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#1249]
COMUNE DI PONSACCO
AMBIENTE DI PRODUZIONE

Il comune è subentrato il giorno 27/03. 
Tra i subentrati c'è la persona con id anpr 37836994 che è subentrata con stato civile IGNOTO e priva di alcun dato di matrimonio/divorzio/vedovanza

Oggi la persona ha lo stato civile ignoto ma le sono stati agganciati i dati di matrimonio dove non sono indicati nè  la data di matrimonio nè il coniuge e come dati di annullamento è presente solo il motivo annullamento.
Il comune ha tentato di sganciare i dati di stato civile facendo una variazione di stato civile da 9 a  1: operazione conclusa correttamente ma i dati di matrimonio e divorzio restano agganciati.

Vi chiediamo come poterli cancellare perchè non sono dati noti al comune, non sono stati inseriti dal comune e l'operazione in webapp di eliminazione dati matrimonio non funziona.

Tiziana Testa
Insiel mercato

**Comment by frmariani** [comment]
Come prima informazione, vorrei sottolineare che la modifica dello stato civile non incide assolutamente sui dati degli eventuali legami: matrimonio, divorzio ecc...
la persona da Lei indicata, precedentemente era iscritta nel comune di Empoli, comune già subentrato in ANPR; il comune di Empoli ha correttamente cancellato la persona nel momento dell'emigrazione nel vostro comune ancora non subentrato;  con il vostro subentro, il sistema riconosce il CF già transistato in ANPR e ri-assegna il precedente idanpr alla persona.
Grazie alla sua segnalazione abbiamo riscontrato un'anomalia nella Consultazione della persona, che visualizza erroneamente i dati sul matrimonio precedentemente acquisiti.
l'anomalia sarà sanata all'inizio della prossima settimana.
Grazie

**Comment by frmariani** [comment]
l'anomalia è stata risolta, può gentilmente verificare se i dati vengono visualizzati correttamente ?
grazie.

**Comment by TizianaTesta** [comment]
ho verificato. I dati non sono più visualizzati. Domani chiederò al comune di procedere con la modifica dati che è rimasta in sospeso

**Comment by frmariani** [comment]
grazie
