### ISSUE TITLE
[5008], WebApp e [3002] - Assenza informazioni sulle unioni civili

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#125]
Pisa, Ambiente di Test.

Buongiorno, abbiamo registrato un evento di unione civile tramite il servizio 5008 (ID operazione ANPR: 452730) relativo all'individuo con codice fiscale BRNMRC67H01E514V ed abbiamo ricevuto l'esito positivo. Nella consultazione della WebApp, però non vediamo alcun dato dell'evento di unione civile registrato se non lo stato civile: unito civilmente.
Oggi abbiamo provato a richiamare tutti i dati del medesimo individuo con il servizio 3002  (ID operazione ANPR: 461482) e anche in questa risposta i dati relativi all'unione civile sono completamente assenti.
E' un problema applicativo o nella nostra prima trasmissione (pur dandoci esito positivo) ci sono stati dei problemi che hanno impedito la registrazione dell'evento?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Per ora la mutazione 20 non tratta le unioni civili e le convivenze di fatto (e tutti i dati correlati). per questo tipo di operazioni deve utilizzare tipo mutazione 16 17 18 19. Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
Attualmente si può "completare" tutto, Ha mai riprovato?
