### ISSUE TITLE
Mapping Archivio storico comuni ANPR e Elenco dei comuni italiani ISTAT

### ISSUE THREAD

**Issue by mariaclaudia** [italia/anpr#1251]
Buongiorno,

al fine di creare un dataset arricchito sui comuni italiani vorremmo integrare il dataset "Archivio storico dei comuni (dd-mm-yyyy)" pubblicato quotidianamento sul [portale di ANPR](https://www.anpr.interno.it/portale/) con il dataset "Elenco dei comuni italiani" pubblicato da ISTAT a questo [permalink](https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv).
Facendo alcune prove abbiamo notato che un primo join tra il dataset di ANPR e il dataset di ISTAT sul ANPR.CODISTAT = ISTAT.Codice Comune formato alfanumerico restituisce un numero inferiore di record (nel nostro caso con i dataset aggiornati ad alcune settimane fa 12.135 record) di una join su ANPR.codcatastale= ISTAT.codice_catastale_del_comune (che restituisce 15.580 record.)

Quale è il campo corretto su cui effettuare il mapping tra i due dataset?

Grazie

Maria Claudia Bodino (Team Digitale) e Giorgia Lodi (Agid) @giorgialodi

**Comment by MassimoSchiappa** [comment]
Il criterio di univocità di un record in AMM_COMUNE è dato dalla terna d'informazioni CODISTAT, DATAISTITUZIONE,DATACESSAZIONE: in altre parole il codice istat di un comune è univoco fissato l'istante temporale. L'archivio storico dei comuni di istat, che è la fonte primaria per la storia dei comuni, registra anche cambiamenti che attualmente non sono contemplati in ANPR (ad esempio aggiunta o sottrazione di territorio ad un comune senza variazione di provincia, codistat, codice catastale etc...) e quindi comunque anche con la terna d'informazioni che ho descritto non si avrebbe una corrispondenza completa tra record di istat e record di ANPR (AMM_COMUNE). Peraltro il codice catastale è un'informazione gestita da Agenzia delle Entrate come fonte primaria, ma anche questo è univoco associato all'intervallo temporale (https://sister.agenziaentrate.gov.it/CitizenArCom/index.jsp) .
