### ISSUE TITLE
Impossibilità di certificare stato di famiglia - cod. famiglia 9079998

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1255]
Non riesco ad emettere il certificato di stato di famiglia della famiglia anagrafica identificata con codice 9079998, il sistema ANPR mi dà il seguente errore:
-----------------------------------------------------------
Errore durante la richiesta delle certificazioni ANPR - copia 1: ERRORE DA ANPR: 
EN222 - I certificati di stato di famiglia, stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile 
-----------------------------------------------------------
Come posso sbloccare la situazione?

I miei riferimenti sono:

Paltrinieri Andrea
Comune Biassono
tel. 039-2201060
e-mail paltrinieri.andrea@biassono.org

In attesa di un vostro gentile riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by paltrinan** [comment]
(non era mia intenzione inviare la richiesta in carattere "bold")

**Comment by rnapoli1983** [comment]
Buongiorno,

abbiamo verificato ed effettivamente la famiglia non risulta certificabile.

Per cambiare lo stato occorre fare una mutazione famiglia con tipo mutazione "dati generali".

Cordiali saluti

**Comment by paltrinan** [comment]
nella maschera "dati di controllo", quale voce seleziono?

**Comment by rnapoli1983** [comment]
Buongiorno stiamo parlando di quale operazione ?

**Comment by paltrinan** [comment]
Ho la necessità di rendere nuovamente certificabile la famiglia cod. ANPR num. 9079998.

Eseguo i seguenti passi a sistema:
-registrazione
-tipo operazione: "Mutazione famiglia/convivenza"
-iniziativa: "Operazione d'ufficio"
-ricerca la famiglia o convivenza - identificativo scheda num. "9079998"
-tipo scheda: "Scheda Famiglia"
-premo il tasto "cerca"
-seleziono un componente della famiglia

Nel campo "Dati di controllo", in "Tipo mutazione", quale voce seleziono?

In attesa di un Vs. gentile riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by rnapoli1983** [comment]
La voce da selezionare è "Composizione scheda" (tipoMutazione := 2).

**Comment by paltrinan** [comment]
problema risolto!
Grazie 1000

Andrea Paltrinieri
