### ISSUE TITLE
ws [3001] - Richiesta per errore EN122

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1256]
Buon giorno,
abbiamo effettuato ieri con il comune di Loreto Aprutino, in ambiente di produzione, la registrazione per nascita di un bambino. Come raccomandato dalle specifiche, la nostra procedura effettua preliminarmente l'interrogazione dei dati dei genitori con il ws 3001 in oggetto. Dato che le informazioni in possesso dell'operatore erano complete, abbiamo effettuato la ricerca dei dati di entrambi i genitori, ma abbiamo ottenuto un errore 'EN122' - "_La richiesta effettuata non produce alcun risultato_". 
In seguito abbiamo poi riscontrato che in effetti il padre non è censito in ANPR, in quanto residente in un comune non ancora subentrato, mentre la madre è residente nel comune e regolarmente censita. Dato che si tratta di una situazione che in questa fase potrebbe essere abbastanza comune o comunque non eccezionale, vi chiediamo, sarebbe possibile in prima battuta raffinare il messaggio di errore, in modo da rendere evidente se nessuno dei genitori è censito in ANPR (situazione che l'operatore dovrebbe verificare) oppure come in questo caso, indicare quale dei due genitori non è censito?
Una ulteriore evoluzione, sempre nel caso di un solo genitore censito, non potrebbe essere invece quella di non restituire un errore, bensì di ottenere in risposta un esito OK restituendo l'oggetto "genitore" per la persona censita ANPR e "nil" per quella non censita?
Grazie,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by frmariani** [comment]
prenderemo in considerazione la sua proposta.
grazie

**Comment by frmariani** [comment]
per il momento chiudo la issue, nel caso avrà notizia della modifica del servizio.
Grazie comunque del suggerimento.
