### ISSUE TITLE
ISCRITTI AIRE PRESENTI IN PUNTOFISCO CON DOMICILIO DIVERSO DA QUELLO DEL COMUNE E GENERALITA' DIVERSE

### ISSUE THREAD

**Issue by Codroipo2018** [italia/anpr#1257]
Stiamo correggendo i dati anagrafici avendo effettuato il presubentro. Risultano esserci diversi AIRE iscritti nel ns Comune che in PUNTOFISCO-SIATEL risultano domiciliati in altri Comuni Italiani con generalità diverse dalle nostre. Abbiamo constatato che è necessario rendere uguali le informazioni nostre con quelle di Puntofisco. Se dobbiamo correggere le informazioni presenti in Puntofisco qual è la procedura da seguire? Trasferire il domicilio nel ns Comune o cosa fare? 
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
le variazioni anagrafiche dei cittadini AIRE i comuni possono essere effettuate utilizzando Siatel – PuntoFisco -> Servizi demografici   -> Funzioni on-line -> Variazione dati anagrafici AIRE.
Per aggiornare il comune di competenza del cittadino AIRE è necessario rivolgersi all’ufficio locale delle Entrate.
N. Capozzi

**Comment by Codroipo2018** [comment]
[cid:image001.png@01D1432C.1D6D2810]


[cid:image002.png@01D1432C.1D6D2810]



GRAZIE
Cordiali saluti



Raffaele Chiariello
Ufficio Servizio Demografici
Tel 0432 824537 Fax 0432 824582
raffaele.chiariello@comune.codroipo.ud.it<mailto:raffaele.chiariello@comune.codroipo.ud.it>
Piazza G. Garibaldi, 81 - 33033 - Cittï¿½ di Codroipo (UD)
comune.codroipo@certgov.fvg.it<mailto:comune.codroipo@certgov.fvg.it>
http://www.comune.codroipo.ud.it/




[cid:image003.png@01D1432C.1D6D2810]

Comune di Codroipo (UD) - Informativa sulla privacy D.Lgs 196/2003 Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario proibita.La sicurezza e la correttezza dei messaggi di posta elettronica non possono essere garantite.
Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci e distruggerlo.
Grazie.






Da: ncapozzi <notifications@github.com>
Inviato: giovedì 4 aprile 2019 16:27
A: italia/anpr <anpr@noreply.github.com>
Cc: Chiariello Raffaele - Codroipo <raffaele.chiariello@comune.codroipo.ud.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] ISCRITTI AIRE PRESENTI IN PUNTOFISCO CON DOMICILIO DIVERSO DA QUELLO DEL COMUNE E GENERALITA' DIVERSE (#1257)


Buonasera,
le variazioni anagrafiche dei cittadini AIRE i comuni possono essere effettuate utilizzando Siatel – PuntoFisco -> Servizi demografici -> Funzioni on-line -> Variazione dati anagrafici AIRE.
Per aggiornare il comune di competenza del cittadino AIRE è necessario rivolgersi all’ufficio locale delle Entrate.
N. Capozzi
