### ISSUE TITLE
Rettifica indirizzo AIRE

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1258]
Ho provato in ambiente di test a rettificare l'indirizzo AIRE (richiesta 5001 con tipo 9), con successo in un paio di casi e con problemi in altri.

Ad esempio con l'idOperazioneANPR 19113803 sono intervenuto su una famiglia AIRE con una sola persona che ha decorrenza iscrizione 19/05/2014 e decorrenza residenza 31/07/2017, dati trasmessi al subentro.

La mia prima richiesta aveva decorrenza 31/07/2017 e ha ricevuto in risposta:
Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 19-05-2014 (Codice: EN526)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-04 16:40:52 , idOperazioneANPR 19113803 (Codice: EN527)

Ho ripetuto la richiesta con decorrenza 19/05/2014 ricevendo in risposta:
La data decorrenza della residenza deve essere uguale alla data decorrenza della richiesta (Codice: EN239)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-04 16:44:43 , idOperazioneANPR 19113806 (Codice: EN527)

Mi aiutate a capire se sbaglio io o se il controllo sulle date va migliorato? Grazie.
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Buonasera,
in teoria sarebbe stato corretto effettuare la rettifica in data decorrenza residenza 31/07/2017, ma trattandosi di dati inoltrati con un subentro del 2017 ci sono date non allineate e quindi deve impostare come data decorrenza 19/05/2014 se proprio vuole utilizzare questo caso per il test.

Per quanto riguarda invece l'operazione 19113806 la data decorrenza in testata deve essere = data decorrenza residenza nell'oggetto residenza.

N. Capozzi
