### ISSUE TITLE
[5005] Errore EN237

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1259]
Per il comune di Torino, in ambiente di produzione, si stanno verificando errori nella risposta del servizio 5005. L'operazione, che sia effettuata da Web App o tramite il nostro applicativo, non viene tracciata nell'Elenco operazioni del soggetto consultabile da Web App.
La risposta KO visibile dal nostro orchestratore restituisce l'errore "EN237 La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata"

Abbiamo riprodotto le pratiche in ambiente di presubentro e la risposta del 5005 è positiva, quindi non si riesce a riprodurre l'anomalia.

Di seguito alcuni ID operazione ANPR in ambiente di produzione:
64414452
65436970
64414452

Saluti
Chiara L. per il Comune di Torino

**Comment by rvinzani** [comment]
Le operazioni riportate nell'elenco sono solo quelle andate a buon fine.
Per le casistiche segnalate 
**64414452**: il servizio 5005 richiede una mutazione di residenza al 27/3 quando risulta una precedente mutazione di residenza dello stesso soggetto al 28/3
**65436970** il servizio 5005 richiede una mutazione di residenza al 7/2 quando risulta una mutazione di residenza della famiglia di destinazione al 14/3
**64414452**:il servizio 5005 richiede una mutazione di residenza al 27/3 quando risulta una precedente mutazione di residenza  dello stesso soggetto al 28/3

**Comment by chiaralea** [comment]
Purtroppo non ci risulta ancora chiaro il motivo di questo KO. Il soggetto relativo all'operazione 64414452 ha le seguenti operazioni
5005	WN	2019-04-04 13:26:58.664 - id operazione 65462860
5005	KO	2019-04-04 11:32:19.14 - id operazione 64414452
5005	KO	2019-04-01 13:48:34.151 - id operazione 60988888
5005	KO	2019-04-01 13:42:35.324 - id operazione 60987205

tutte le operazioni KO restituiscono il messaggio di errore sulla data decorrenza residenza (e nell'xml la richiesta aveva come data decorrenza 27/3). Solo l'ultima, in ordine cronologico, risulta andata a buon fine con data decorrenza 28/3. Tra queste operazioni non risultano ulteriori movimenti del soggetto andate a buon fine, quindi com'è possibile che ci sia una mutazione con data decorrenza 28/3 tra quelle inviate con data decorrenza 27/3?

**Comment by rvinzani** [comment]
La convivenza presso la quale è stato inserito ha registrato una mutazione di residenza alla data del 28/3

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
