### ISSUE TITLE
Web App - Utilità e notifiche - Certificati e carte d'identità

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#126]
Abbiamo notato che non esiste un parametro di ricerca per reperire un certificato tramite il suo numero di protocollo. Inoltre, la ricerca tramite i soli campi obbligatori si blocca senza dare risultati.
Si chiede se è possibile migliorare la funzione in modo che, effettuata la ricerca del certficato tramite n. protocollo ANPR, vengano visualizzate le stesse informazioni (compreso il pdf del certificato) esattamente come accade in caso di verifica tramite QR code.
Grazie,

Valentina Bocchino, Pier Dario Brigandì - Comune di Torino
Ambiente test

**Comment by gcarbonin** [comment]
Può riprovare la ricerca tramite i campi obbligatori

**Comment by VBocchinoTO** [comment]
Ho appena fatto una prova, ma (salvo errori miei) mi sembra restituisca esattamente le stesse informazioni di prima.
Grazie.

**Comment by gcarbonin** [comment]
Le informazioni non sono cambiate: per questo c'è il tag evoluzione. La prova si riferisce al fatto che nel primo messaggio aveva segnalato che l'interrogazione per dati obbligatori non funzionava. Limitatamente a questo aspetto, mi sembra sia andata bene.

**Comment by VBocchinoTO** [comment]
Perfetto, la ricerca restituisce il risultato.
Grazie.
