### ISSUE TITLE
[4005 / 7002] Download File - Errore: 998 - Servizio non disponibile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1260]
ambiente di TEST - comune di FAENZA (039010)

stiamo cercando di implementare la richiesta di notifiche secondo le nuove modalità, utilizzando il codDestinatario ANPR02.

con servizio 4005 abbiamo eseguito la richiesta delle notifiche di tipo N031 (idOperazioneComune 2019301176), ed il ws risponde con l'id da utilizzare per il download del file: 19113777

con servizio 7002 tentiamo di scaricare le notifiche, ma il servizio risponde con l'errore:
998 - E - Servizio non disponibile

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno,
Come indicato nella issue #1161, il servizio 4005 viene acceduto con la funzione verificaStato del 4005 stato.
Al momento non è previsto di accedere alle elaborazioni 4005 attraverso il servizio 7002.
E’ stato aggiunto un controllo specifico per il servizio 7002 al fine di evitare l’errore.
Saluti

Assistenza ANPR
