### ISSUE TITLE
Stato civile di codice 99 ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1261]
Ambiente di produzione, comune di Chieri

Abbiamo un'errore applicativo durante il tentativo di migrare un soggetto da altro comune ANPR.
Indagando ci accorgiamo che nel XML di risposta al 3002 il codice ANPR dello stato civile è 99.
Se consultiamo il soggetto da webapp vediamo lo stato civile con il valore "VALORE ERRATO".

Il codice 99 non è presente nelle specifiche ANPR (nella tabella di codifica dello stato civile).

E' un codice nuovo ? A cosa è dovuto ? Com'è possibile che siano subentrati dei soggetti il cui stato civile non rispetta le codifiche di ANPR ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, è possibile avere l'id operazione ANPR del 3002 oppure l'id soggetto ANPR al fine di poter verificare più celermente?
Grazie in anticipo.

**Comment by busaster** [comment]
L'id ANPR del soggetto è 41992457.

**Comment by mttfranci** [comment]
Salve, come anticipato, adesso il 3002 dovrebbe non restituire affatto la sezione dello stato civile se non è stato comunicato un valore valido in fase di subentro.
Potete provare di nuovo l'interrogazione se volte.
Saluti

Assistenza ANPR
