### ISSUE TITLE
[5014] richiestaRettifica101- Errore EN427

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1265]
ambiente di PRODUZIONE - comune di LODI (098031)

si tratta di una posizione un po' pasticciata.
soggetti passati al subentro come singoli componenti di famiglie diverse, che invece devono appartenere alla stessa famiglia.
abbiamo ripristinato la situzione famigliare attraverso ws di mutazione.

abbiamo tentato di aggiornare la data di decorrenza della residenza con servizio 5014, ma l'operazione va a buon fine per lei e non per lui.
nel caso specifico, idOperazioneComune 2019007378 ritorna l'errore:
EN427 - E - Rettifica non permessa: Comune non competente

probabilmente il motivo dell'errore è un altro... o non ne capiamo il significato.
è possibile avere qualche chiarimento in merito?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
La rettifica della data di decorrenza della residenza non è permessa se per il soggetto sono presenti cambi di residenza, come nel suo caso.
sicuramente il controllo è fuorviante,  prenderemo spunto dalla sua segnalazione per renderlo più chiaro

**Comment by AMonopoliADS** [comment]
Messaggio ricevuto.
Anche se penso che, in generale, le mutazioni "per ripristino" (come in questo caso) dovrebbero comportare una tolleranza maggiore su variazioni successive come questa, proprio x il fatto che "ripristinano" in qualche modo una situazione al subentro o ante-subentro...
Comunque avvisiamo il cliente.
Grazie

**Comment by frmariani** [comment]
Stiamo cercando di offrire varie possibilità di correzione del dato inviato con errori: 
la mutazione di residenza ante-subentro  e la rettifica della data di decorrenza della residenza sono due tra le diverse possibilità; 
come ha detto Lei, la situazione è stata un po' pasticciata, nel caso avreste dovuto annullare l'operazione di mutazione ante subentro e ripeterla con la data corretta.
comunque abbiamo reso più chiaro il controllo.
