### ISSUE TITLE
Problema Iscrizione Altri Motivi parziale

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#1266]
Per il comune di Giugliano in Campania, una Iscrizione altri motivi Apr in famiglia nuova di 5 persone
2 finiscono in Anpr:
Id Scheda Sogg Anpr47768255
Id Scheda Sogg Anpr47768256
mentre i 3 figli non risultano in Anpr pur avendo restituito il codice Anpr
Id Scheda Sogg Anpr47768258; Id Operazione Anpr: 56684449; Data Ora Richiesta: 2019-03-13 10:59:17.473
Id Scheda Sogg Anpr47768259; Id Operazione Anpr: 56684479; Data Ora Richiesta: 2019-03-13 10:59:20.087
Id Scheda Sogg Anpr47768260; Id Operazione Anpr: 56684512; Data Ora Richiesta: 2019-03-13 10:59:22.663

Nei log delle operazioni tutti i messaggi 1002 inviati ad ANPR, con esito positivo e non
risultano annullamenti inviati per le operazioni 1002 che hanno iscritto gli individui oggetto della
segnalazione.

**Comment by asqueglia** [comment]
Buongiorno, in data 05-APR-19 per i soggetti 47768258, 47768259, 47768260 è stata trasmessa da vostro gestionale una richiesta di annullamento iscrizione (servizio 1013). Le operazioni di annullamento richieste sono 65645173, 65645184, 65645156.

**Comment by asqueglia** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
