### ISSUE TITLE
Errore in visualizzazione scheda soggetto 18932094

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1267]
Buongiorno.

Quando visualizzo la scheda soggetto 18932094 (cod. famiglia 9081669) 
il sistema della software house del comune visualizza l'errore:

ERRORE DA ANPR: 
EN212 - La famiglia risulta non certificabile (30003) 

ERRORE DA ANPR:  EN212 - La famiglia risulta non certificabile

Ho provato a fare la stessa cosa del ticket #1255 ma non sono riuscito a risolvere il problema.

cosa devo fare?

In attesa di un vostro gentile riscontro, comunico i miei riferimenti:
Andrea Paltrinieri - Comune di Biassono
tel 039-2201060 - e-mail paltrinieri.andrea@biassono.org 

cordiali saluti

Andrea Paltrinieri

**Comment by mttfranci** [comment]
Questa mattina era presente una anomalia, ora sanata, per la quale il il diagnostico 
EN212 - La famiglia risulta non certificabile
Compariva anche in casi per i quali la famiglia in realtà era certificabile.

A parte la situazione di questa mattina, la soluzione proposta nella issue #1255 è corretta.
Potrà capitare di incontrare la anomalia EN212 (o EN222 nel servizio di certificazione).
Ciò avverrà qualora ANPR rilevi uno stato delle relazioni di parentela non congruente nella famiglia.
Ad esempio due coniugi, presenti nella stessa famiglia, di cui uno sia intestatario e l'altro non sia Marito / Moglie.
Potete risolvere l'anomalia con il servizio di mutazione famiglia / convivenza (5001), mutazione relazioni di parentela (2) e fornendo le relazioni di parentela corrette.

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
