### ISSUE TITLE
Certificato storico di residenza con data errata

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1268]
Buongiorno, ambiente di produzione.
La famiglia 26802177 presenta date che non capiamo nel certificato storico.
La situazione della famiglia è 2 genitori, 2 bambini. Residenti a Modena comune anpr, che li cancella con decorrenza 19 gennaio, avendo ricevuto un apr4 da Maranello. Maranello subentra il 4 febbraio. 
Per il genitore id 19245316 il certificato storico di residenza anpr (protocollo 67273946) riporta l'indirizzo di Modena fino al 19/1/2019. corretto. Per Maranello riporta :
_Comune di Maranello dal 24/01/2019
Indirizzo via .....  dal 24/01/2019_
Non stampa il dato decorrenza residenza che vediamo presente nel xml: 19/01/2019

Per il bambino id 46329509 , ora residente a Maranello , abbiamo un corrispondente id 19245312, cancellato da Modena. Ci sono due id per generalità non coincidenti.
Chiedo quindi due certificati storici separati. Su quello di Maranello (protocollo 67272648), esce 
_Comune di Maranello dal 19/01/2019
Indirizzo via .....  dal 24/01/2019_
Quindi differente dal genitore nel riportare la data di iscrizione nel comune. Anche qui la data nell'indirizzo non coincide con la data decorrenza residenza.

**Comment by rvinzani** [comment]
Contattato. In attesa di riscontro

**Comment by MarcoMigliori** [comment]
Sospeso in attesa di verifica lato Sogei. Come promemoria sono in ferie nelle prossime due settimane.

**Comment by rvinzani** [comment]
Il motivo della discrepanza è che al subentro è stata inviata come data di ingresso in famiglia il 24/1.
Per correggere questa data e conseguentemente il certificato possiamo aggiornare noi direttamente la data in ANPR  previa richiesta del comune via pec

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue facendo riferimento a questa stessa
