### ISSUE TITLE
[5008] permesso di soggiorno non salvato su ANPR

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1269]
Abbiamo riscontrato problemi di mancato salvataggio delle informazioni relative al permesso di soggiorno sia in produzione che in ambiente di presubentro.
L'esito della risposta del 5008 è positivo, ma le informazioni non transitano su ANPR.

Caso di produzione:
Id scheda sogg. ANPR: 46855207
Id operazione ANPR 5008: 67538101

Caso di presubentro:
Id scheda sogg. ANPR:  85116700
Id operazione ANPR 5008: 12531948

**Comment by chiaralea** [comment]
(Comune di Torino)

**Comment by AMonopoliADS** [comment]
mi collego a questa issue perchè sembra che la stessa problematica si verifichi al comune di FAENZA (039010), ambiente di PRODUZIONE... sempre aggiornamento di documento di soggiorno.
idOperazioneComune 2019010757, che ritorna con esito positivo ma ANPR non risulta aggiornata 
Alessandro Monopoli ADS

**Comment by StefanoGuidetti** [comment]
Anche per il comune di Desenzano (017067), problema simile,
16/04/2019
Ambiente di produzione  (idOperazioneANPR: 73595069)
Risposta con esito Positivo con relativo permesso di soggiorno riportato correttamente, 
ma interrogando con 3002 (idOperazioneANPR 73595075), 
il permesso di Soggiorno non appare.

17/04/2019
Interrogo il cittadino 3002 (idOperazioneANPR: 73815274) e il permesso di soggiorno
viene riportato correttamente.


Grazie
Stefano di PAL

**Comment by rvinzani** [comment]
Si tratta di un problema nella consultazione effettuata il giorno stesso dell'inserimento del permesso di soggiorno. Il problema sarà eliminato con la versione che sarà pubblicata in produzione domani sera

**Comment by chiaralea** [comment]
Il problema è risolto, grazie.
