### ISSUE TITLE
Indirizzo in Agenzia delle Entrate non aggiornato a seguito mutazione di residenza

### ISSUE THREAD

**Issue by ComuneTerracina** [italia/anpr#1270]
Comune di Terracina:
A seguito di un'operazione di Mutazione di residenza con idanpr 24193919 in Agenzia delle entrate è variato l'indirizzo per 6 dei 7 individui movimentati dall'operazione. 
Uno non ha ricevuto l'aggiornamento e risulta ancora al vecchio indirizzo.
Agenzia delle Entrate dice che è una cosa a cui dobbiamo porre rimedio noi, ma non abbiamo strumenti per farlo. 
L'individuo che necessita l'aggiornamento di Indirizzo ha idAnpr 23894875

Il vecchio indirizzo è Via Guido Reni 0
Quello attuale è Via Guido Reni 25

Grazie

**Comment by rvinzani** [comment]
Il soggetto ha subito una mutazione di residenza prima che il suo CF fosse validato. Finchè i dati di ANPR e di AE non sono allineati non vengono inviate le notifiche. Abbiamo provveduto ad aggiornare comunque l'indirizzo

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue facendo riferimento a questa stessa
