### ISSUE TITLE
[5005] mutazione residenza senza variazione indirizzo

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1271]
Abbiamo due risultati contrastanti su due situazioni all'apparenza identiche.

Con una mutazione di tipo 5005 cerchiamo di trasferire un soggetto di una famiglia di 3 componenti in una nuova famiglia al medesimo indirizzo.

**Caso 1** 
Ambiente di produzione, comune di Sant'Agata de' Goti.
Mutazione ID ANPR 68530100 che fallisce con l'errore  EN388  "La residenza inserita risulta uguale a quella attuale".

**Caso 2**
Ambiente di test, comune di Poggio a Caiano
Mutazione ID ANPR 19132316 che viene completata con successo.

A cosa è dovuta questa differenza di comportamento ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
per il caso in ambiente di produzione,  l'indirizzo presente nell'xml risulta identico a quello già presente per il soggetto;
nel caso riportato in ambiente di test, l'indirizzo presente nell'xml differisce nel numero civico rispetto all'indirizzo presente per il soggetto, pertanto l'operazione va a buon fine

**Comment by busaster** [comment]
Se consulto il soggetto ad oggi lo trovo residente nella famiglia nuova (id ANPR 17122275) all'indirizzo  PIAZZA BUONTALENTI 28  (id operazione ANPR con cui l'ho ricercato 19137710)
Se consulto il soggetto al 10/04 lo trovo nella precedente famiglia (id ANPR 4907654) all'indirizzo PIAZZA BUONTALENTI 28 ( id operazione ANPR con cui l'ho ricercato 19137720)

Non capisco quindi dove sia la differenza.

**Comment by frmariani** [comment]
ha ragione, ma è presente uno spazio nel toponimo;

**Comment by busaster** [comment]
Ok, nella richiesta il toponimo ha degli spazi in coda. 
Ho capito. 
Non credo sia quello però il problema. Ho simulato un altro trasferimento in nuova famiglia allo stesso indirizzo (id ANPR 19137813) dove non ci sono spazi in più nella richiesta, ma lo stesso non ho ricevuto blocchi....

**Comment by frmariani** [comment]
grazie per l'insistenza ... abbiamo scovato un bug sul codice consolato.
appena eliminata l'anomalia, Le chiederò di effettuare un altro test simile.
Grazie.

**Comment by frmariani** [comment]
abbiamo eliminato l'anomalia, nel caso può effettuare un nuovo test.
grazie

**Comment by busaster** [comment]
testato con ID operazione 19147447, mi aspettavo di essere bloccato da un errore ma la mutazione di residenza allo stesso indirizzo in una nuova famiglia è andata a buon fine.
Ho confrontato i frammenti di XML restituiti dal 3002 sul soggetto che si sposta e le differenze sono :
dopo : <specieFonte>2</specieFonte>
prima : non presente
dopo : <codiceCivico>4050</codiceCivico>
dopo                <civicoFonte>2</civicoFonte>

**Comment by ANPRCdMI** [comment]
Buonasera
mi collego a questa segnalazione perché l'errore è il medesimo.
In ambiente di PROD per una scissione allo stesso indirizzo viene data segnalazione di errore  EN388 (idOperazioneANPR 79812705 del 24/04/2019).
In ambiente di PRE-SUB la stessa operazione invece viene completata senza errori (idOperazioneANPR 12571633 del 29/04/2019). 

Vorremmo anche sapere quale delle due operazioni è considerata corretta, poiché è certamente possibile che venga effettuato un cambio residenza allo stesso indirizzo se viene creata una nuova famiglia oppure se c'è scissione con aggregazione ad altra  famiglia residente al medesimo indirizzo. La segnalazione dovrebbe essere un warning e non un errore bloccante.

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by frmariani** [comment]
@busaster l'operazione idanpr 19147447 è andata a buon fine perchè contiene il "Forza Operazione" nei controlli;
@ANPRCdMI nel momento in cui ha effettuato l'operazione in ambiente di pre-subentro, il bug non era ancora stato rimosso;
nel caso di scissione allo stesso indirizzo, basta inserire l'informazione di famiglia coabitante

**Comment by ANPRCdMI** [comment]
Buonasera
purtroppo non abbiamo la gestione puntuale dei numeri interni, cosa che risolverebbe il problema. Tuttavia fornire l'informazione di "famiglia coabitante" non è sempre corretto, perché potrebbe effettivamente trattarsi di famiglia diversa residente in un altro appartamento allo stesso numero civico, quini non "coabitante".  Dobbiamo segnalare al Comune che questa è, al momento, l'unica soluzione per effettuare la mutazione residenza senza variazione indirizzo.

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by frmariani** [comment]
la gestione dell'interno e/o del piano sono informazioni importanti anche per la propagazione delle informazioni agli Enti, quindi sarebbe auspicabile un'implementazione per la loro corretta gestione; nel frattempo, in questi casi particolari e quindi residuali, potrei consigliare di inserire l'interno nel toponimo
