### ISSUE TITLE
Messaggio "EN122 - la richiesta effettuata non produce alcun risultato" per notifiche N010/N014/N015

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#1273]
Buonasera

il Comune ha segnalato che dal 10 aprile (pratiche del 9 aprile) le elaborazioni delle notifiche N010, N014 e N015, hanno dato segnalazione "EN122 - la richiesta effettuata non produce alcun risultato".
Mentre per le notifiche N014 e N015 la segnalazione potrebbe essere corretta, per le notifiche  N010 ci sembra strano perché riceviamo giornalmente 50/60 messaggi.
Potreste gentilmente verificare ?
idOperazioneComune 20190412012643971465
idOperazioneANPR 67423923 

Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by mttfranci** [comment]
Salve, la situazione è la stessa descritta nella issue #1227 : 

E' stata effettuata la correzione di una anomalia che impattava negativamente sulle performance. (#1227)
Da specifiche per le notifiche vanno indicati gli stati lavorazione 7/8/9 mentre nella vostra richiesta è stato indicato '2'.
In effetti tale valore veniva erroneamente elaborato in precedenza, ma non è un valore valido per le notifiche.
<statoLavorazione>2</statoLavorazione> <operazioneRichiesta>N010</operazioneRichiesta>
Vi invitiamo a indicare uno dei valori previsti nelle richieste ai servizi 3003/3007/4005.

Per rendere più agevole il lavoro dei comuni e delle software house abbiamo rilasciato una patch che reintroduce il comportamento parzialmente  del bug #1275

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
