### ISSUE TITLE
[5012] errore EN077 in rigetto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1274]
Ambiente di produzione, comune di Soresina

In data 13/12/2018 un soggetto A esce dalla famiglia FAM di 3 persone per formare un nuovo nucleo. L'operazione si conclude con successo (id ANPR 39292014). 
In data 12/02/2019 un secondo soggetto B esce dalla famiglia FAM con una mutazione di residenza che lo sposta in un altro comune (id ANPR 51529896 fatta dal comune di nuova iscrizione, ANNICO).
In data odierna (13/04/2019) il comune deve rigettare la pratica di cambio residenza del soggetto A ma la richiesta 5012 ad ANPR fallisce con l'errore EN077 (id ANPR 72115045)

Come mai ?
Come possiamo sbloccare il cliente ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
Come da Lei evidenziato, l'operazione da ripristinare è quella con idanpr 39292014, mentre nel 5012 fallito avete inserito idanpr 39292020; inoltre si tratta di un 5005 e non di un 5001.
Riprovi inserendo i dati corretti e mi faccia sapere.

**Comment by busaster** [comment]
Effettivamente nella mia analisi mancava che in data 13/12/2018 contestualmente all'uscita di A dalla famiglia il componente C (la moglie) diventava intestatario con una mutazione 5001 di tipo 2 (la id ANPR 39292020 appunto).

Nel rigetto dell'uscita di A noi tentiamo (a mio parere correttamente) di annullare anche la variazione di relazione di parentela perché altrimenti il rigetto porta ad una situazione di famiglia con due intestatari.

Abbiamo tamponato il problema del cliente non annullando la 39292020 ma facendo una variazione di relazioni di parentela successiva all'annullamento della 39292014.

E' veramente questa l'unica strada percorribile ?

**Comment by frmariani** [comment]
le operazioni effettuate sono state due, pertanto la situazione si può ripristinare con altrettante due operazioni. 
per il momento è l'unica strada percorribile.

**Comment by busaster** [comment]
senza dubbio , la domanda era volta a capire se sarà possibile in futuro far funzionare l'annullo 5012 della variazione di relazioni di parentela nonostante l'operazione successiva

**Comment by frmariani** [comment]
l'annullamento dell'operazione idanpr 39292020, è bloccata dall'operazione di uscita del secondo componente: vuole annullare un'operazione che coinvolge un soggetto che non è più presente all'interno della famiglia, quindi dovremmo annullare parzialmente l'operazione di modifica delle relazioni di parentela.
al momento non sono previste evoluzioni in tal senso.

**Comment by busaster** [comment]
capito. Grazie
