### ISSUE TITLE
[4005] Nuova modalità di acquisizione notifiche

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1277]
buongiorno.

personalmente sto avendo alcune "difficoltà" ad interagire con il nuovo servizio di acquisizione notifiche, che stiamo testando sul ramo ANPR02 da un po' di giorni, e che prossimamente sarà la modalità unica anche in produzione.

parto dal presupposto che il sistema attualmente in uso - a mio parere - era già funzionale al punto giusto:
immediato nella risposta, e - in presenza di dati significativi - con il campo base64 che, una volta decodificato, conteneva già l'xml de leggere ed importare nel gestionale.

la nuova modalità, passante per il servizio 4005, pone le seguenti problematiche:
1. una volta richiesta la lista delle notifiche, la risposta sarà disponibile dopo un periodo apparentemente definito, che però può necessitare di più "verifiche di stato" prima di sapere se ci siano o meno notifiche disponibili... e questo allunga di un po' i tempi di questa gestione, ma se non c'è alternativa ce ne faremo una ragione.
2. una volta disponibili le notifiche, queste ritornano in formato base64, ma, decodificate, non contengono gli xml in chiaro, bensì di file compressi "gz" da decomprire e poi leggere.

ditemi che sto sbagliando qualcosa nell'uso del servizio o nella configurazione della request, perchè a queste condizioni mi sembra che il tutto si sia complicato notevolmente.

vedete ad esempio la richiesta di notifiche N031 eseguita con idOperazioneComune 2019301329 (eseguita il 12/4/2019 ore 20) e la risposta ottenuta con idOperazioneComune 2019301384 (il 15/4/2019 alle ore 7).

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
Scusate la dimenticanza: ambiente di TEST - comune di FAENZA

**Comment by MarcoMigliori** [comment]
Stiamo vivendo più o meno le stesse difficoltà. Il problema principale dal mio punto di vista è l'incertezza dei tempi di risposta.

**Comment by SAlberto** [comment]
Condividiamo appieno le considerazioni fatte da @AMonopoliADS

**Comment by bfilipazzi** [comment]
Siamo tutti sulla stessa barca.

**Comment by mttfranci** [comment]
@AMonopoliADS  @MarcoMigliori  @SAlberto @bfilipazzi Capiamo le vostre preoccupazioni, ma dovete tenere presente che stiamo ancora ottimizzando il processo di generazione.

Per quanto riguarda la compressione gz delle risposte, in questo servizio il formato è dichiarato in un apposito campo. Abbiamo ritenuto opportuno non trasferire i dati restituiti da questo servizio in chiaro, ma comprimerli al fine di ridurre la quantità di dati trasferiti. Da notare che già altri servizi (come il 7001) comprimono gli attachment, quindi non si tratta di una modalità del tutto nuova.

Rispondendo invece alle vostre osservazioni sulla disponibilità della risposta : 
A regime ci aspettiamo che il tempo massimo per l’elaborazione sia di 24 ore. Ma in generale dovrebbe essere notevolmente più rapido, nel caso medio speriamo di portarlo a circa 1 ora.
Inoltre stiamo migliorando l’algoritmo che stima la data di disponibilità della risposta (che in questo momento tende a eseguire previsioni molto pessimistiche).
In tal senso abbiamo appena rilasciato una patch (5.3.7) che abbassa la stima a 1 ora circa.

Pubblicheremo, come sempre, nel [changelog](https://github.com/italia/anpr/blob/master/src/change-management/changelog.md) le modifiche che verranno pubblicate; detto questo l’attuale funzionamento è sufficiente per definire il flusso di gestione di una richiesta 4005, per la quale proviamo a proporvi questa best practice : 

1)	Richiesta in modalità “elaborazione” del 4005, catturando due parametri, l’id dell’elaborazione e la “data di disponibilità”
2)	Primo tentativo di recupero della risposta temporizzato in base alla data stimata di disponibilità del servizio. Se la risposta è pronta il flusso termina, se non è pronta riprovare alla nuova “data di disponibilità” (il servizio di verifica fornirà una nuova stima in caso l’elaborazione non sia pronta).
NOTA: visto che la stima potrebbe essere sempre arrotondata per eccesso, se ritenete potete definire una classe di richieste più urgenti delle altre e, solo per quelle, fare un primo tentativo dopo 30 minuti (qualora la data prevista di disponibilità sia superiore).

@ AMonopoliADS Un’ultima nota sulle operazioni da voi indicate come esempio.
Abbiamo monitorato la situazione e in questi giorni; se la richiesta ha impiegato più di un giorno è sempre dipeso da anomalie che stiamo correggendo e che speriamo non si verifichino più, salvo casi eccezionali, una volta che il servizio sarà rilasciato in produzione.
Nel caso specifico della richiesta 2019301329 il problema era dovuto al fatto che non era stato specificato il livello di dettaglio (vedi note #1161) del servizio. Questo campo non è obbligatorio (dato che il valore dovrebbe essere assunto come quello predefinito, RISPOSTA), ma per un errore del software la richiesta non veniva elaborata.

**Comment by AMonopoliADS** [comment]
> Per quanto riguarda la compressione gz delle risposte, in questo servizio il formato è dichiarato in un apposito campo. Abbiamo ritenuto opportuno non trasferire i dati restituiti da questo servizio in chiaro, ma comprimerli al fine di ridurre la quantità di dati trasferiti. Da notare che già altri servizi (come il 7001) comprimono gli attachment, quindi non si tratta di una modalità del tutto nuova.

la differenza, rispetto al servizio 7001 - dove riconosco che l'uso della compressione gz è più giustificata... - è che lì vengono scaricate intere tabelle più o meno consistenti... ma potenzialmente contenenti anche numerosi record.
in questo caso il file decompresso è un xml di poche righe.
onestamente non ne vedo la reale utilità, neanche al fine di "ridurre la quantità di dati trasferiti"
lato SW è solo un giro in più, un appesantimento e una perdita di tempo (sempre parere personale...)
pertanto vi chiedo di rivedere la questione o, per esempio, di rendere parametrica il formato già a livello di request.

> A regime ci aspettiamo che il tempo massimo per l’elaborazione sia di 24 ore. Ma in generale dovrebbe essere notevolmente più rapido, nel caso medio speriamo di portarlo a circa 1 ora.
> Inoltre stiamo migliorando l’algoritmo che stima la data di disponibilità della risposta (che in questo momento tende a eseguire previsioni molto pessimistiche).
> In tal senso abbiamo appena rilasciato una patch (5.3.7) che abbassa la stima a 1 ora circa.

riguardo le tempistiche, ritengo fondamentale che i tempi siano realmente così brevi come scritto.
ad oggi, gli enti sono abituati (... non tutti, ma soprattutto quelli confinanti territorialmente...) a telefonarsi per chiudere in fretta i procedimenti che li riguardano: uno iscrive, l'altro scarica la notifica e cancella. 
il che da' un valore aggiunto alla condivisione dei dati.

> Nel caso specifico della richiesta 2019301329 il problema era dovuto al fatto che non era stato specificato il livello di dettaglio (vedi note #1161) del servizio. Questo campo non è obbligatorio (dato che il valore dovrebbe essere assunto come quello predefinito, RISPOSTA), ma per un errore del software la richiesta non veniva elaborata.

monitoriamo l'andamento dei prossimi giorni.

grazie.

**Comment by mttfranci** [comment]
> la differenza, rispetto al servizio 7001 - dove riconosco che l'uso della compressione gz è più giustificata... - è che lì vengono scaricate intere tabelle più o meno consistenti... ma potenzialmente contenenti anche numerosi record.
> in questo caso il file decompresso è un xml di poche righe.
> onestamente non ne vedo la reale utilità, neanche al fine di "ridurre la quantità di dati trasferiti"
> lato SW è solo un giro in più, un appesantimento e una perdita di tempo (sempre parere personale...)
> pertanto vi chiedo di rivedere la questione o, per esempio, di rendere parametrica il formato già a livello di request.

@AMonopoliADS 
Riguardo la compressione, dovete considerare che, se facciamo il parallelo con le richieste multiple del 3003, in alcuni casi l'elaborazione potrebbe contenere decine (o addirittura centinaia) di risposte.
A volte questo dipende da un uso improprio del servizio (ad esempio alcuni comuni richiedono tutte le notifiche N031 mai generate quando sarebbe più opportuno richiedere l'elenco dei comuni subentrati con il 7001). Quindi il punto non è ridurre le dimensioni della singola richiesta/risposta, ma quello dell'intera risposta dell'elaborazione.
Inoltre, a breve verranno aggiornate anche le specifiche complete sul portale, ma il client dovrebbe tenere conto che la risposta potrebbe arrivare, attualmente, in due formati alternativi : 
gz – Formato compresso con algoritmo gzip
xml – xml in chiaro

Come vedete dalla struttura del'XSD, il numero di risposte potenzialmente restituite è in molteplicità 0+
![image](https://user-images.githubusercontent.com/29305782/56218887-05198500-6066-11e9-9140-a75f8c7516df.png)

**Comment by AMonopoliADS** [comment]
> il client dovrebbe tenere conto che la risposta potrebbe arrivare, attualmente, in due formati alternativi :
> gz – Formato compresso con algoritmo gzip
> xml – xml in chiaro

cosa condiziona (o condizionerà) il formato della risposta (gz o xml)?

**Comment by mttfranci** [comment]
In generale il formato sarà gz.
Ma è sempre esplicitato.
prendiamo i due campi relativi alla risposta (discorso simile varrà per la richiesta)  : 
contenutoRisposta - il contenuto della risposta
formatoRisposta - vale 'xml' se contenutoRisposta contiene il plain text dell'xml, 'gz' de contenutoRisposta contiene l'xml compresso in formato gzip (deflate).

Il server potrebbe restituire il contenuto in uno dei due formati.
Il client dovrebbe verificare il campo formato* e trattare opportunamente il campo contenuto*

L'idea è che la politica sul formato potrebbe cambiare nel tempo e i client dovrebbero essere predisposti ad entrambi indipendentemente da cosa il server decida per la specifica operazione.
Non ci sembra che l'algoritmo per tale gestione sia particolarmente complesso o comporti eccessive complicazioni.

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
@AMonopoliADS @MarcoMigliori @SAlberto @bfilipazzi Salve, potete darci un riscontro se la situazione dei tempi di disponibilità ora si avvicina di più alle vostre esigenze?
Grazie in anticipo.

**Comment by AMonopoliADS** [comment]
ambiente di TEST - comune di FAENZA (039010)

questo l'ultimo test eseguito questa mattina:

idOperazioneComune 
- 2019300608 (N010) 
- 2019300609 (N014) 
- 2019300610 (N015) 
- 2019300611 (N031)

eseguite le richieste alle ore 8:46, sono state monitorate ogni 5 minuti, e hanno ottenuto risposta alle 9:46 (data/ora dichiarata come dataDisponibilità)
N010 / N031 con risposte consistenti
N014 / N015 con errore EN122 ("La ricerca non produce risultati")

i tempi sono sicuramente accettabili pensando all'esecuzione di job schedulati, verificherei la possibilità di migliorarli affinchè risultino più immediati nel caso di richieste estemporanee.

da test di qualche giorno fa, in presenza di tutte richieste "senza risultato", ho avuto l'impressione che i tempi della response definitiva fossero più veloci, nonostante la dataDisponibilità "a un'ora".

comunque procederemo con ulteriori test

**Comment by mttfranci** [comment]
@AMonopoliADS stiamo lavorando per rendere l'elaborazione il più rapida possibile e la stima sulla disponibilità attendibile.
In generale, sarebbe preferibile che, salvo casi eccezionali in cui la richiesta riveste una urgenza elevata, la prima verifica di una elaborazione avvenga dopo la data di disponibilità restituita al momento della richiesta iniziale (questo a livello di flusso).

**Comment by StefanoGuidetti** [comment]
Rispondo per conto di @MarcoMigliori 

Abbiamo verificato i tempi di risposta del servizio
idOperazioneANPR: 19163382 
dataOraRichiesta: 2019-04-26T15:43:07.115+02:00
dataDisponibilita prevista: 2019-04-26T16:43:10.990+02:00
ricevuta risposta alle: 2019-04-26T16:05:55.115+02:00 

e comunque le risposte sono tutte entro la scadenza prevista,
1h circa o meno.

Farebbe comodo avere nella risposta anche l'ora della disponibilità
ora appare come 00:00
![image](https://user-images.githubusercontent.com/43878804/56816992-e6c13f80-6844-11e9-9abe-f00548c96339.png)
Grazie

**Comment by AMonopoliADS** [comment]
ambiente di TEST - comune di FAENZA (039010)

richiesta notifiche il 02/05/2019 h. 20.00: disponibilità 02/05/2019 h. 21:00
verifica stato il 03/05/2019 h. 7.00: proroga disponibilità al 03/05/2019 h. 8:00
verifica stato il 03/05/2019 h. 10.15:  proroga disponibilità al 03/05/2019 h. 11.15

è possibile verificare?

idANPR delle richieste: 
- 2019301912 (N010)
- 2019301913 (N014)
- 2019301914 (N015)
- 2019301915 (N031)

grazie

**Comment by AMonopoliADS** [comment]
(ho corretto gli id, xchè avevo indicato erroneamente gli idComune al posto di quelli ANPR)

**Comment by mttfranci** [comment]
> ambiente di TEST - comune di FAENZA (039010)
> 
> richiesta notifiche il 02/05/2019 h. 20.00: disponibilità 02/05/2019 h. 21:00
> verifica stato il 03/05/2019 h. 7.00: proroga disponibilità al 03/05/2019 h. 8:00
> verifica stato il 03/05/2019 h. 10.15: proroga disponibilità al 03/05/2019 h. 11.15
> 
> è possibile verificare?
> 
> idANPR delle richieste:
> 
> * 19671179 (N010)
> * 19671177 (N014)
> * 19671175 (N015)
> * 19671173 (N031)
> 
> grazie

Potete verificare? Ora dovrebbe essere elaborate.
Le elaborazioni erano inizialmente fallite e c'era un problema con la coda di recupero.
