### ISSUE TITLE
Logo per certificato

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#1278]
Il mio Comune è inserito per il subentro il 10 giugno prossimo. Stavo tentando di inserire il "logo per certificati" tramite la funzione "Gestione dati del Comune - informazioni aggiuntive" dove viene specificato che il file deve avere "...Altezza:70 Larghezza:70 in formato png, gif, jpeg"... ma l'unità di misura? mm., pixels o che altro?
Grazie

**Comment by MarcoMigliori** [comment]
pixel
