### ISSUE TITLE
Campo gestione CF in 5008

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#1280]
Nel caso di un 5008  inviato tramite WS, il campo gestione CF presente nei dati di controllo, se compilato viene preso in considerazione da ANPR soltanto per una mutazione dei dati di Generalità? 
Quindi è strettamente legato al CF o ha senso anche per altri tipi di mutazione?

**Comment by frmariani** [comment]
E' strettamente legato al CF

**Comment by frmariani** [comment]
per il momento chiudo la issue, nel caso avesse bisogno di altre informazioni potrà riaprirla.
