### ISSUE TITLE
[3003] Elenco Operazioni - esitoOperazione 'XXXX'

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1282]
ambiente di PRODUZIONE - comune di FAENZA (039010)

da ieri, le richieste delle operazioni sul soggetto (ws 3003) ritornano tutte con esitoOperazione XXXX e listaErrori non valorizzata.
come nell'esempio che riporto:
```
<a:Risposta3003 xmlns:a="http://sogei.it/ANPR/3000consultazione">
	<a:rispostaKO>
		<testataRisposta>
			<idOperazioneComune>2019305110</idOperazioneComune>
			<codMittente>039010</codMittente>
			<codDestinatario>ANPR01</codDestinatario>
			<operazioneRichiesta>3003</operazioneRichiesta>
			<dataOraRichiesta>2019-04-16T10:33:31</dataOraRichiesta>
			<idOperazioneANPR>73292621</idOperazioneANPR>
			<esitoOperazione>XXXX</esitoOperazione>
		</testataRisposta>
		<listaErrori/>
	</a:rispostaKO>
</a:Risposta3003>

```
potete verificare?
grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, in effetti abbiamo trovato un problema che dovrebbe essere già stato corretto.
Potete cortesemente riprovare?
Grazie in anticipo.

**Comment by AMonopoliADS** [comment]
il ws adesso risponde correttamente.

**Comment by mttfranci** [comment]
Perfetto grazie
