### ISSUE TITLE
Errore in cancellazione per ripristino posizione precedente

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1283]
Ambiente di produzione, comune di Prato

cerando di cancellare un soggetto per ripristino posizione precedente veniamo bloccati dall'errore "EN240 : La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 22-01-2019" (id operazione ANPR 73373998)

In quella data l'unica operazione effettuata sul soggetto è la 5008 con id ANPR 46517261 che abbiamo già annullato con la mutazione 5012 id anpr 73369699.

Quale altro blocco ci impedisce di portare a buon fine la cancellazione ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by asqueglia** [comment]
Buongiorno, il blocco non dipende dalle mutazioni effettuate sul soggetto che dovete cancellare, ma dipende dalle operazioni effettuate sul soggetto coniuge. Il coniuge è stato iscritto il 22-01-2019 con decorrenza 09-01-2019;  il giorno 18-02-2019 il coniuge è stato cancellato con decorrenza 22-01-2019. 
Stiamo analizzando il caso. Le faremo sapere il prima possibile

**Comment by asqueglia** [comment]
Potete riprovare l'operazione di cancellazione. Restiamo in attesa di un vostro riscontro.
Grazie per la segnalazione

**Comment by busaster** [comment]
Il problema di Prato è stato risolto, la cancellazione ora è andata a buon fine.
Abbiamo però un  problema che sembra lo stesso sempre in produzione ma da un altro cliente (Salò).
ID ANPR della cancellazione per ripristino che fallisce : 78507234
Ci confermate che è lo stesso problema ?
Sarà risolto con un aggiornamento ?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, ci scusiamo per il ritardo nella risposta. La richiesta di annullamento non andata a buon fine si riferisce ad una mutazione matrimonio ed altri dati. Ci confermate che il vostro intento è la cancellazione per ripristino della posizione precedente, ossia la cancellazione dell'operazione 64414423 ? in caso affermativo, potreste indicarci su quali soggetti della famiglia intendete effettuare il ripristino ?

**Comment by busaster** [comment]
Confermiamo che l'operazione di cui si chiede l'annullamento è la 64414423 e che i soggetti da ripristinare sono tutti quelli coinvolti nell'operazione

**Comment by fferraguto** [comment]
Salve,
potreste cortesemente riprovare ad annullare l'operazione con id 64414423?
Grazie.
