### ISSUE TITLE
Rettifica dati di iscrizione - Comune di Iscrizione

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1284]
Buongiorno,
sono a scrivere per un collega di un altro comune.
Ha effettuato l'iscrizione in ANPR da comune non subentrato e detto comune ha risposto che la persona era stata cancellata per altro comune, sempre, non subentrato.
Ha provato, tramite WebApp a rettificare i dati di subentro per correggere il comune di iscrizione, ma riceve errore (Dati di iscrizione non disponibili).
Abbiamo controllato ed i dati di iscrizione sembrano presenti.
Il cittadino ha ID Anpr 44903695, il comune di iscrizione corretto è LATINA (LT) e non MILETO (VV)

Potreste controllare.

Grazie

**Comment by frmariani** [comment]
il cittadino è stato iscritto proveniente da Vibo Valentia;
successivamente è stata effettuata una Rettifica dati iscrizione modificando il cittadino come proveniente da Mileto.
Se vuole scrivermi in privato posso contattare il suo collega e capire meglio la problematica
