### ISSUE TITLE
Risoluzione disallineamento tra AE ed ANPR su soggetto 27679733

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1288]
Buongiorno.
Volevo fare sì che in AE compaia lo stesso indirizzo di residenza riportato in ANPR per il soggetto in oggetto (cod. fiscale CPRSAI00M47F205O).
Quando tento di fare l'operazione dal portale ANPR dalla maschera "RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE" il sito mi chiede 
"Conferma AE : I dati di ANPR verranno sostituiti con quelli presenti in AE. Sei sicuro di voler continuare?"

Che comando devo lanciare per fare l'operazione opposta?

In attesa di un Vs. riscontro porgo cordiali saluti.

dott. Andrea Paltrinieri
Ufficio Anagrafe del Comune di Biassono
e-mail: paltrinieri.andrea@biassono.org
tel. 039-2201060

**Comment by rvinzani** [comment]
Indipendentemente dalla conferma dei dati anagrafici di ANPR o di AE, i dati dell'indirizzo utilizzati per l'aggiornamento dei sistemi sono sempre quelli di ANPR

**Comment by paltrinan** [comment]
ho provato a cercare di risolvere il disallineamento, ma il portale ANPR mi dà come errore "richiesta incogruente"; come faccio a fare sì che il domicilio fiscale diventi uguale alla residenza anagrafica?

**Comment by bmalavolti** [comment]
Buongiorno
anche  per alcuni soggetti del Comune di Faenza abbiamo lo stesso problema.
Con la Risoluzione disallineamenti con AE, viene segnalato l'errore con "Richiesta incongruente"
come si può risolvere? 
i soggetti sono ID anpr 19140943  - 19140941 -19140942 -19660397 
Grazie
BARBARA MALAVOLTI
UFFICIO ANAGRAFE FAENZA
TEL 0546-691645
e-mail barbara.malavolti@romagnafaentina.it

**Comment by rvinzani** [comment]
la residenza dei soggetti risulta ora allineata con Agenzia Entrate.
Chiudo la issue. In caso di richiesta ulteriori informazioni si prega di aprire una nuova issue facendo riferimento a questa stessa.
