### ISSUE TITLE
[5005] - Errore 999 operazione non effettuabile

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1290]
Buongiorno,
in data odierna in ambiente di produzione è stata effettuata una mutazione residenza. Il servizio 5005 è andato in KO con il seguente errore:

            <errore>
                <codiceErroreAnomalia>999</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-19 12:27:07 , idOperazioneANPR 75903083</testoErroreAnomalia>
            </errore>

A cosa è dovuto?
Grazie,
Chiara L. per il Comune di Torino

**Comment by chiaralea** [comment]
(La richiesta è stata fatta dal nostro client, non da Web App)

**Comment by mttfranci** [comment]
Salve, stiamo verificando la vostra segnalazione.
Saluti

Assistenza ANPR

**Comment by chiaralea** [comment]
Buongiorno, ci sono novità a riguardo?

**Comment by chiaralea** [comment]
Buongiorno, il Comune avrebbe bisogno di indicazioni su come operare. Potete cortesemente fornirci un riscontro? Grazie.

**Comment by MassimoSchiappa** [comment]
Salve, stiamo ancora analizzando il caso e in apparenza sembrerebbe legato ad una stretta correlazione temporale con altre operazioni anagrafiche sulla stessa famiglia o individuo (in particolare stiamo verificando l'impatto dell'apertura di un procedimento, 1014). Appena terminata la nostra analisi vi faremo sapere.
Cordiali saluti.

**Comment by MassimoSchiappa** [comment]
Salve, potreste riprovare? Abbiamo fatto delle correzioni che si spera risolvano.
Cordiali saluti.

**Comment by chiaralea** [comment]
Buongiorno,

il comune ha riprovato, ma l'errore restituito è sempre lo stesso.

Cordialmente,
Chiara Leanza

**Comment by mttfranci** [comment]
Salve, ora il problema dovrebbe essere risolto, potreste riprovare?
Grazie in anticipo.

**Comment by chiaralea** [comment]
Buongiorno, il Comune ha riprovato e sono riusciti a completare l'operazione. Possiamo chiedervi quale problema si è verificato nello specifico? 

Grazie, 
Chiara Leanza

**Comment by mttfranci** [comment]
Una informazione di sistema non era stata archiviata correttamente per lo specifico soggetto.
Purtroppo tale informazione non era evidente e abbiamo impiegato molto tempo ad individuare il problema.
