### ISSUE TITLE
Cancellazione doppia iscrizione

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1291]
Abbiamo necessità di cancellare causa doppia iscrizione, un cittadino Aire nel frattempo rimpatriato in altro comune subentrato.
Non riusciamo a cancellarlo poiché al momento del subentro lo abbiamo caricato con un codice fiscale errato. L'errore che fornisce ANPR è il seguente: Incongruenza dati anagrafici: il codice fiscale del soggetto non coincide con quello specificato nella richiesta.
I due idanpr del cittadino sono 18854418 e 46178178

**Comment by ncapozzi** [comment]
Buonasera,
la cancellazione per doppia iscrizione può essere utilizzata solo in presenza di anomalia per doppia iscrizione generata al subentro in presenza di due schede con lo stesso CF. Nel vostro caso l'anomalia non è presente perché le due schede hanno CF diverso e pertanto per eliminare  una delle due dovete effettuare una cancellazione per altri motivi scegliendo una motivazione che non sia "per doppia iscrizione".

N. Capozzi
