### ISSUE TITLE
Prove fallite di rigetto rimpatrio a cavallo del subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1292]
In ambiente di test (comune di Poggio a Caiano) sto provando quanto suggerito nella issue #1228 per rigettare un rimpatrio aperto prima del subentro.
La pratica da rigettare ha decorrenza 24/07/2017, per cui come da specifiche effettuo come prima cosa una cancellazione 2003 per ripristino posizione precedente con tale data come decorrenza cancellazione. Operazione conclusa con successo (id ANPR 19151857)
Eseguo quindi una iscrizione in AIRE per altri motivi con la decorrenza originaria della residenza AIRE del soggetto (20/03/2013) ma vengo fermato dall'errore "EN238 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata" (id ANPR 19151860).

Come mai ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by busaster** [comment]
Buongiorno
Ci sono novità in merito a questa issue ?
Abbiamo anche un cliente con questo problema in produzione.
Grazie

**Comment by rvinzani** [comment]
Abbiamo verificato il problema. Cercheremo di correggerlo il prima possibile

**Comment by rvinzani** [comment]
Il bug è stato risolto e sarà disponibile in ambiente di test dal prossimo mercoledì. 
Chiudo la issue. In caso di problemi o necessità di ulteriori chiarimenti si prega di riaprire una nuova issue facendo riferimento a questa stessa
