### ISSUE TITLE
IMPOSSIBILITA' AGGIORNARE NOME E COGNOME

### ISSUE THREAD

**Issue by maristellae** [italia/anpr#1293]
Salve, , mi risulta impossibile procedere la "Mutazione  dati del nome e cognome di un cittadino straniero che non varia il codice fiscale che è numerico in quanto mi dà i seguenti errori:

1 Errore Anpr Cod: AEE95 - Operazione non effettuabile - Cognome: ....
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-23 12:10:31 , id Operazione ANPR 78342449 - Cognome: .......-
Resto in attesa di istruzioni,  grazie

**Comment by rvinzani** [comment]
non è possibile modificare i dati anagrafici finchè il soggetto ha un CF provvisorio.
I dati possono essere modificati al momento della conversione in CF definitivo o successivamente

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue facendo riferimento a questa stessa
