### ISSUE TITLE
Data e ora disponibilità servizio 4005

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1294]
Buongiorno.
Abbiamo eseguito una richiesta 4005 per richiedere le notifiche N015
ID OPERAZIONE: 12562707

Richiedendo la disponibilità di una N015 ,
(che sulla WA è già presente per il comune di CARTOCETO in presubentro)
mi rimanda la data/ora di disponibilità ogni volta che vado a richiederla
 ad esempio risultava disponibile alle ore 10:02 della giornata di oggi, e andando a richiederla alle ore 10:30 mi risulta disponibile dalle ore 11:19.

Come mai?
GRAZIE

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato il problema.
Potreste riprovare cortesemente?

**Comment by fmbianchi** [comment]
adesso sono state ricevute.
Grazie
