### ISSUE TITLE
[3003] PROD Interrogazione notifiche: manca l'allegato

### ISSUE THREAD

**Issue by StefanoGuidetti** [italia/anpr#1295]
Buongiorno,
alcuni Comuni ci segnalano malfunzionamenti nella ricezione delle notifiche.

Abbiamo scoperto che nella risposta 3003, non è presente l'attachment,
che invece riusciamo ad ottenere da WAPP

Caso di esempio
Ente: Comune di Maranello 
idOperazioneANPR: 79340123
Ambiente: Produzione

Stefano di PAL

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato il problema.
Potreste riprovare cortesemente?

**Comment by StefanoGuidetti** [comment]
Risolto.
Grazie

**Comment by mttfranci** [comment]
Di niente
