### ISSUE TITLE
NON ATTRIBUIBILE - descrizione Stato JUGOSLAVIA

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1296]
Buongiorno a tutt*,
da circa 10 giorni,  la funzione "Mutazione tutti i dati - > Generalità " non consente più di inserire Jugoslavia nella Descrizione Stato. Restituisce l'errore "Operazione non effettuabile (Codice: AEE95)"
Soluzione? Grazie
Anna Maria AIMONE
UPI Torino

**Comment by mttfranci** [comment]
Salve. potreste fornirci qualche id anpr delle operazioni per verificare piu' velocemente?
In generale questa tipologia di errore comunque e' da attribuirsi al colloquio con Agenzia entrate.
grazie in anticipo.

**Comment by UpiTorino** [comment]
idANPR: 34319572

**Comment by UpiTorino** [comment]
idANPR: 28858846

**Comment by mttfranci** [comment]
Stiamo verificando la vostra segnalazione.
Potete in questo casi fornirci un id operazione ANPR (e non del soggetto). Questo renderebbe l'indagine più veloce.
Nel vostro caso specifico dovremmo ad esempio aver individuato la seguente operazione effettuata da web app : 79747046

Da notare che sia da webapp che da gestionale dovreste ottenere il seguente diagnostico quando una operazione non va a buon fine : 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-26 09:27:34 , idOperazioneANPR 79747046.

Fornire il testo di questo diagnostico è di grande utilità in questi casi.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
I diagnostici che iniziano con AE (come il AEE95) riguardano la comunicazione con Agenzia entrate.
Siamo ancora valutando con AE come superare questa situazione.
Vi avviseremo appena avremo avuto riscontro anche noi.
Da notare che per il futuro sarebbe meglio non inviare la descrizione "NON ATTRIBUIBILE" in fase di iscrizione come è avvenuto ad esempio con l'iscrizione per altri motivi del soggetto 34319572 (id operazione ANPR = 20659403)
Saluti

Assistenza ANPR
