### ISSUE TITLE
Doppia iscrizione in ANPR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1298]
Buongiorno,
per una fatalità ci siamo accorti che un cittadino ha 2 posizioni in ANPR, iscritto in 2 comuni differenti.
Noi lo abbiamo iscritto il 07.12.2017 (id ANPR 38137103) e l'altro comune, che è quello di attuale residenza lo ha iscritto 

il 09.02.2019 (id ANPR 47580768).

Il comune di attuale residenza lo ha iscritto prima che subentrasse in ANPR e il cittadino è stato caricato in ANPR in fase di subentro.

In fase di subentro il comune che lo ha iscritto successivamente, non avrebbe dovuto ricevere un avviso che il cittadino era già presente in ANPR come doppia iscrizione?

Interrogando il soggetto da WebApp ho notato la presenza della voce Duplicati in cui viene sognalata anomalia EN471 codice 1
"Il soggetto con id anpr 47580768 risulta iscritto anche nel comune di VILLA CORTESE (MI) Con data iscrizione 07/12/2017"

Chiedo una verifica e come risolvere la doppia iscrizione, in quanto il comune che lo ha attualmente residente è subentrato il 06.03.2019 e noi siamo subentrati il 20.11.2018

Grazie

**Comment by rvinzani** [comment]
I soggetti sono entrati in ANPR in fase di subentro e la presenza di doppia iscrizione è indicata nel file specifico. Il comune che non ha il soggetto residente nel suo comune lo deve cancellare per doppia iscrizione

**Comment by cvignati** [comment]
Fatto.

Grazie
