### ISSUE TITLE
Collegamento CF non riuscito

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1299]
Buongiorno,
ciclicamente si ripresenta il problema del collegamento fra CF numerico e CF alfanumerico marcati ANPR. Da risoluzione Agenzia Entrate non riusciamo ad effettuare il collegamento in quanto non è presente la casella per lo spunto e confermando i dati sostituisce il codice fiscale ma non lo collega.
Esempio:
id anpr 28637058 
Soluzione?
Anna Maria AIMONE
Resp. Uff. Codici Fiscali 
Comune di Torino

**Comment by UpiTorino** [comment]
Altro caso
id anpr 28109797

**Comment by rvinzani** [comment]
Gent.le Annamaria, da ANPR è possibile collegare un CF numerico ad un alfanumerico solo se:
- il CF presente in ANPR è quello numerico, il CF alfanumerico non è validato, i dati anagrafici sono diversi
- a breve anche se il CF presente in ANPR è quello numerico, il CF alfanumerico non è validato, i dati anagrafici sono uguali

Negli altri casi deve operare l'Agenzia delle Entrate

**Comment by UpiTorino** [comment]
Buongiorno,
ho vermanete molta difficoltà a capire la logica dei codici numerci. Temo
che da qui alla mia pensione ti riprorrò la stessa domanda altre volte.
Grazie per la pazienza e buon Primo Maggio

Anna Maria AIMONE

Responsabile

CODICI FISCALI

PROCEDURE INFORMATICHE

Area Servizi Civici

Comune di Torino

annamaria.aimone@comune.torino.it

Servizi.civici@cert.comune.torino.it



INFORMATIVA SULLA PRIVACY

Le informazioni contenute in questo messaggio sono riservate e
confidenziali e per uso esclusivo del destinatario. Ne sono vietati uso,
diffusione o riproduzione. Qualora Lei non fosse la persona a cui il
presente messaggio è destinato, La invitiamo ad eliminarlo (allegati
compresi) senza farne copia, e a non leggerlo, dandocene gentilmente
comunicazione. Qualsivoglia utilizzo non autorizzato del contenuto di
questo messaggio costituisce violazione dell'obbligo di non prendere
cognizione della corrispondenza tra altri soggetti, salvo più grave
illecito, ed espone il responsabile alle relative conseguenze. Per
qualsiasi informazione si prega di contattare il Titolare del Trattamento
dei dati Anna Maria AIMONE alla mail annamaria.aimone@comune.torino.it -
 Rif. RGPD 679/2016





Il giorno mar 30 apr 2019 alle ore 15:03 rvinzani <notifications@github.com>
ha scritto:
