### ISSUE TITLE
Posizioni bloccanti per matrimonio discordante rispetto alla data di nascita

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#13]
Per il subentro, abbiamo verificato che le posizioni  con denominazione del comune di nascita o matrimonio discordante rispetto alla data di nascita o matrimonio (vedi comuni cessati), sono bloccanti in fase di movimentazione con l’applicazione ANPR. Poiché abbiamo migliaia di situazioni di questo tipo, dobbiamo correggere i dati o è possibile utilizzare qualche escamotage, tipo alimentando solo la descrizione località?

**Comment by gcarbonin** [comment]
Sul comune di nascita se il dato dichiarato dal comune consente di risalire al codice catastale presente nel codice fisvale, non si segnala nemmeno l'anomalia. In tutti gli altri casi (comune degli atti di nascita, matrimonio, decesso del coniuge e comune di matrimonio/decesso del coniuge) viene segnalata l'anomalia. Il comune dovrebbe controllare che ciò sia coerente con quanto risulta dallo stato civile. Sono tutti errori non bloccanti.
