### ISSUE TITLE
Certificato di stato di famiglia storico

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#130]
Al momento non risulta ancora presente la certificazione storica di stato di famiglia. E' previsto in un'evoluzione futura? Se non previsto, a seguito del subentro, sarà possibile emettere il certificato utilizzando il template disponibile tramite il gestionale?
Grazie,
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino

**Comment by gcarbonin** [comment]
Come sempre, i certificate che trovate sono stati indicati dai comuni pilota e approvati dal Ministero dell'Interno. Evoluzioni sono possibili: questo certificato in particolare è stato richiesto anche da altri e quindi mi sembrerebbe una lodevole iniziativa la sua implementazione, ma non siamo autonomi (come Sogei) in questo. Segno quindi la richiesta come evolutiva. Sarebbe utile un esempio di certificato attualmente prodotto dal comune di Torino (da oscurare o se non possibile inviare alla mia e-mail). Per quanto riguarda l'utilizzo del gestionale, la soluzione è una strada obbligata per tutto ciò che è avvenuto prima del subentro ma per gli eventi successivi la base dati del comune non è più "certificante".

**Comment by VBocchinoTO** [comment]
Come richiesto, inviamo alcuni esempi di certificati prodotti dal ns. Comune:
- [storico_famiglia_convivenza.pdf](https://github.com/italia/anpr/files/972643/storico_famiglia_convivenza.pdf) viene emesso al soggetto iscritto in una convivenza anagrafica;
- [storico_famiglia_rapporti_parentela.pdf](https://github.com/italia/anpr/files/972644/storico_famiglia_rapporti_parentela.pdf) viene emesso al soggetto iscritto in una famiglia anagrafica quando viene richiesta la "fotografia" ad una certa data (nell'esempio sono riportati anche i rapporti di parentela; normalmente il certificato viene emesso senza, mentre vengono indicati su specifica richiesta);
- [storico_famiglia_con_variazioni.pdf](https://github.com/italia/anpr/files/972645/storico_famiglia_con_variazioni.pdf) viene emesso (al momento ancora manualmente, spesso consultando anche le schede cartacee ante-1989 conservate nei ns. archivi) quando il soggetto chiede una certificazione storica che mostri anche le variazioni successive intervenute sulla scheda di famiglia. Anche in questo caso vale il discorso dell'omissione dei rapporti di parentela, salvo specifica richiesta dell'interessato.  Molti gestionali utilizzano quest'ultima tipologia di certificazione, sicuramente più esaustiva delle precedenti. 

Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
chiusa in quanto lo stesso argomento è trattato nella issue  #607
