### ISSUE TITLE
ANPR02 - cambio di residenza nel comune (5005) 

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1300]
Comune di BERTIOLO ambiente di Presubentro.
id operazione ANPR 12581674
L'operazione va a buon fine in ANPR ma nella risposta fornita il tag datiSoggetto all'interno di listaSoggettiVariati è vuoto.

**Comment by mttfranci** [comment]
Salve, come indicato nell'avviso #1079, con la versione ANPR02 non è più previsto di restituire le sezioni dei dati variati quando non ci sono dati generati da ANPR (id soggetto o famiglia, codice fiscale ecc).
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by INSIEL1** [comment]
in ambiente di presubentro da WEB APP -comune di Codroipo -abbiamo effettuato per prova lo stesso tipo di cambio di residenza nel comune (5005), la persona si sposta in altro indirizzo e in altra  famiglia e la risposta contiene tutti i dati.
idoperazione ANPR = 12581942. Non capiamo la differenza rispetto alla mutazione inviata dal gestionale.

**Comment by mttfranci** [comment]
Salve. Le operazioni da webapp continuano a mantenere la risposta completa perche' altrimenti le notifiche NRIS non potrebbero essere piu' usate.

La differenza e' che da gestionale il client dovrebbe conoscere quali dati ha inviato ed e' superfluo ripeterli. 
Da web app invece le NRIS costituiscono il meccanismo con cui i comuni possono accedere programmaticamente al contenuto dell'operazione.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
