### ISSUE TITLE
[web-service PROD] switch da ANPR01 ad ANPR02

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1301]
buongiorno.

chiedo conferma della data in cui sarà definitivo il passaggio al ramo ANPR02, e non sarà quindi più utilizzabile il codDestinatario ANPR01.

allo stesso tempo, chiedo se con questo switch nell'ambiente di PRODUZIONE saranno operative e definitive anche le variazioni apportate con la v5.3-RC1, relative a:
- gestione notifiche passanti per ws 4005
- consultazione (ws 3003) con possibilità di ricerca per idSoggettoANPR

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Per la fine supporto alla versione ANPR01, confermiamo la data presente nella issue #1161 
19 Giugno 2019 - Ambienti di test / presubentro
26 Giugno 2019 - Ambiente di produzione

Per quanto riguarda i servizi 4005 e l'interrogazione per idsoggeto del 3003 sono già disponibili in produzione, ma se avete qualche problema nell'utilizzo siamo a vostra disposione.

Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
grazie Matteo.
avevo bisogno di un riepilogo sintetico

**Comment by Eduardo1977** [comment]
Buongiorno, sul sito www.anpr.interno.it  il pacchetto completo "Tracciati XSD e WSDL - rar" è del 18 febbraio 2019. Quando verrà pubblicato quello aggiornato? Grazie

**Comment by mttfranci** [comment]
a breve verra' aggiornato.
I wsdl dei servizi 3000 e 4000 erano gia' pubblicati nell'avviso #1161 

https://github.com/italia/anpr/files/3068019/wsdl3000-5.3-RC1.zip
https://github.com/italia/anpr/files/2979087/wsdl4000-5.3-RC1.zip

**Comment by Eduardo1977** [comment]
Grazie

**Comment by mttfranci** [comment]
Prego
