### ISSUE TITLE
[4001] esito negativo 

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1302]
Buongiorno ho provato a fare un estrazione elenco cittadini 

<idSchedaSoggettoANPRDa>117051447</idSchedaSoggettoANPRDa>
<idSchedaSoggettoANPRA>117052448</idSchedaSoggettoANPRA>

sia tramite WS (ANPR02) che WEB APP in tutti e due i casi con esito negativo.

idoperazioneanpr 12582473 (WS)
idoperazioneanpr 12582659 (WA)

CARTOCETO - presubentro

grazie mille

**Comment by azabatta** [comment]
Buonasera, 
la segnalazione è in verifica, avviseremo appena sarà possibile riprovare.

**Comment by azabatta** [comment]
Buongiorno, 
è possibile riprovare. Restiamo in attesa di un cortese riscontro.
Buona giornata

**Comment by fmbianchi** [comment]
Buongiorno, 
abbiamo provato ma ritorna il formato errato dell'attachment 
all'interno dell'xml di ritorno è presente il tag
<formato>.xml</formato> 
quando in realtà la risposta arriva in .gz.

oltre a questo, a differenza delle 4005, qui il formato è indicato con il . mentre nelle altre è senza .
sarebbe il caso di unificare il funzionamento delle due.

**Comment by fmbianchi** [comment]
Buongiorno, abbiamo fatto la prova ma il formato non ritorna in maniera corretta.
all'interno dell'xml di ritorno ci dice che il formato è .xml quando invece l'attachment arriva in .gz.

Oltre a questo, abbiamo notato che nel servizio 4005 nel formato non mettete il . (es. gz, xml) mentre qui l'estensione viene indicata con il . (es. .gz, .xml). sarebbe il caso di uniformare le due cose.

ID_operazione ANPR: 12604137
Comune di Cartoceto 
Presubentro

**Comment by azabatta** [comment]
Buonasera, 
il rilevo adesso  è sul ws 7002?  Il contenuto dell'estrazione corrisponde a quanto richiesto?

**Comment by fmbianchi** [comment]
Sì esatto, ora l'esito è positivo e tornano i dati corretti, è errato il formato dell'attachment

**Comment by azabatta** [comment]
Verifichiamo, grazie per la segnalazione

**Comment by azabatta** [comment]
Buongiorno, 
il ws 7002 consente un download generico di file derivanti da più tipologie di  elaborazioni, il file restituito è sempre compresso ma una volta scompattato può essere un  “.csv” oppure un “.xml”.   Per questo motivo  ci è sembrato più utile informare sul  formato finale del file.

Riguardo alla presenza del punto nel campo “formato” rispetto al ws 4005, posto che ambedue i servizi sono stati già implementati da molti utenti, cambiare adesso potrebbe comportare delle modifiche a software già rilasciato pertanto preferiamo non effettuare modifiche pur ritenendo l’osservazione corretta.

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
