### ISSUE TITLE
Scomparsa di una famiglia in ANPR dopo Mutazione Residenza

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1303]
**Comune di PARMA - ANPR in produzione**

Nella giornata dell'08.03.2019 una famiglia composta da cinque persone effettua una mutazione di residenza nel Comune di Parma da firenze

L'intestatario della pratica è la signora BERTOLINO ANNALISA Id Anpr 32977255 e l'id operazione ANPR è il 55635712.

Insieme all'intestatario si spostano marito e 3 figli rispettivamente con id Anpr 32977254 (marito) e 32977256, 32977279, 32977281 (figli)

La famiglia ha idAnpr 19075638 

Purtroppo però quando cerco con il CF in webapp i componenti della famiglia la ricerca non restituisce nessun risultato, mentre se la faccio in AE ottengo i dati corretti, il CF validato ANPR e l'indirizzo di residenza corretta a Parma

Il marito deve fare urgentemente una CIE per motivi lavorativi ma il sistema restituisce errore e non fà procedere....

Come faccio??

Diego Rossi

**Comment by frmariani** [comment]
Sono stati effettuati degli approfondimenti con il Comune di Firenze.
Ora potete riprovare l'emissione della CIE.
