### ISSUE TITLE
caratteri diacritici in visura scheda e certificazione

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1304]
comune di Bertiolo ambiente PRESUBENTRO- 
idANPR del soggetto 115177367 - la persona ha nel nome 3 caratteri diacritici (lettere dell'alfabeto sloveno)
da Web App : 
1. la visura scheda soggetto non contiene la lettera Č.
2. non si riesce a  ottenere il certificato segnala errore nel nome.

gli stessi problemi si erano presentati lo scorso anno vedi issue 744 ed erano stati risolti.

grazie

**Comment by rvinzani** [comment]
Il problema è stato risolto in ambiente di test comuni e presubentro.
Chiudo pertanto la issue, In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue facendo riferimento a questa stessa
