### ISSUE TITLE
[5008] Rifugiati: Mutazione Generalità e Codice Fiscale

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1305]
buongiorno

mi rifaccio a quanto già discusso riguardo le rettifiche di generalità dei rifugiati politici e la conseguente ri-attribuzione del codice fiscale. 

in particolare faccio riferimento ai temi della issue #917 , per sapere se ci sono state evoluzioni al riguardo... sottolineando le difficoltà che ancora oggi ci segnalano i nostri clienti nell'ambito di queste attività.

di seguito il caso di oggi:

ambiente di PRODUZIONE - comune di COLLE di VAL D'ELSA (052012)

soggetto con idANPR 45444671
il soggetto deve subire la variazione del cognome, nome e data di nascita.
la mutazione unica di questi dati viene rigettata a causa di questo errore:
```
<errore>
  <codiceErroreAnomalia>EAM93</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Variazione non consentita per superamento numero campi variati</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2019003910)

allora si procede con la separazione delle modifiche:
si invia con successo la variazione di cognome e nome (idOperazioneComune 2019003920)
... ma si rimane bloccati poi con l'invio della variazione della data di nascita.
la variazione di quest'ultima, viene rigettata con l'errore:
```
<errore>
  <codiceErroreAnomalia>EAM15</codiceErroreAnomalia>ù
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Soggetto individuato in AT già in trattamento - operazione non effettuabile in data odierna</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2019003921)

vale a dire, che AE sta - probabilmente - assegnando un nuovo CF, e non è possibile fare ulteriori variazioni fino a domani... momento in cui potrò inviare la variazione di data di nascita, e partirà l'attribuzione di un altro codice fiscale?
non ci sono alternative a questo meccanismo?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Il procedimento descritto è corretto. Purtroppo sono politiche indicate da Agenzia Entrate su cui non abbiamo margini di modifica.
Chiudo l'ssue. Nel caso ci fosse necessità di ulteriori chiarimenti si prega di riaprire questa stessa issue o di aprirne un'altra facendo riferimento a questa.
