### ISSUE TITLE
Errore EAM93 - Variazione non consentita per superamento numero campi variati

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1306]
**COMUNE DI PARMA - ANPR in produzione**

Ho un richiedente asilo che è iscritto in anagrafe del comune di Parma con un CF numerico (idAnpr 24573948 ).
Adesso il signore si presenta agli sportelli dichiarando la volontà di cambiare nome, cognome e data di nascita e quindi di conseguenza anche il CF.

Effettua una procedura di mutazione tutti i dati in rettifica ma il sistema mi risponde _"EAM93 - Variazione non consentita per superamento numero campi variati_"

Facendo riferimento alle segnalazioni #1205 #1305 e #917 provo a mutare i dati per singoli passi (cognome -> nome -> data nascita) mantenendo fisso il CF numerico.

Quando invio la pratica il sistema risponde: _"AEE95 - Operazione non effettuabile"_

Avevo fatto una segnalazione telefonica numero 199045711 senza risposta.

Come procedo???

***************************************************************************
Rossi Diego
S.O. Transazione Digitale
Comune di Parma
L.go Torello de Strada, 11/a
43121 Parma
Tel 0521.218100
***************************************************************************

**Comment by frmariani** [comment]
Su direttiva di Agenzia delle Entrate, i CF numerici, quindi in attesa di CF definitivi alfanumerici, non possono essere modificati.
Mi scuso per  la mancata risposta della segnalazione; ho provato a recuperarla ma forse il numero non è corretto.
