### ISSUE TITLE
[5008] tipoMutazione '03': Annullamento Carta Identità

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1307]
ambiente di TEST - comune di FAENZA (039010)

in riferimento alla issue #1110 , continuo a non vedere funzionare la mutazione dei dati della carta di identità, con lo scopo di valorizzare la data di annullamento.

idOperazioneComune 2019000503 (ANPR02)
la comunicazione viene accettata senza errori, ma in ANPR la dataAnnullamento della carta di identità non viene modificata.
interrogando il soggetto (sia con ws 3002 che da web-app) la dataAnnullamento non viene riportata tra i dati della risposta.
 
se è possibile verificare...

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Il bug è stato risolto e sarà disponibile in ambiente di test dal prossimo mercoledì. 
Chiudo la issue. In caso di problemi o necessità di ulteriori chiarimenti si prega di riaprire una nuova issue facendo riferimento a questa stessa
