### ISSUE TITLE
PROCEDIMENTO AMMINISTRATIVO - UTILITA'

### ISSUE THREAD

**Issue by Codroipo2018** [italia/anpr#1308]
AMBIENTE TEST - COMUNE DI CODROIPO
Buongiorno,
siamo in fase di presubentro e stiamo cercando di chiarire alcuni dubbi con relative scelte successive prima di subentrare definitivamente. Vorremmo sapere se l’unico modo per evitare che nei casi in cui una persona si presenti nel ns Comune dichiarando di essere dimorante definitivamente nello stesso, per qual si voglia motivo decida di spostare la stessa in un altro Comune, prima che da noi siano stati conclusi gli accertamenti di effettiva residenza, il secondo Comune possa effettuare la mutazione è l’utilizzo del Procedimento Amministrativo.
Si chiede, inoltre, se fino a che non Avviene la chiusura dello stesso con esito positivo è possibile o meno certificare le persone comprese nello stesso. Facendo prove su WEBAPP abbiamo notato che vengono certificate.
Si chiede, inoltre, di spiegarci gli eventuali ulteriori vantaggi con l’utilizzo del Procedimento Amministrativo.
Altro punto interrogativo riguarda la gestione delle informazioni statistiche legate allo stesso. Abbiamo notato che a procedimento aperto le iscrizioni e le mutazioni vengono conteggiate subito nel d7b e successivamente alla sua chiusura sia con esito positivo sia con esito negativo vengono cancellate dal d7b dove erano state riportate e reinserite in quello della chiusura definitiva del Procedimento. Domanda quante volte l’informazione statistica relativa a tale pratica viene trasmessa all’ISTAT? Due volte, o solo a procedimento chiuso? Nel caso vengano trasmesse due volte c’è un segnale per ISTAT in modo tale da far considerare quella notifica come provvisoria?
Per noi e per un cospicuo gruppo di Comuni con i quali collaboriamo queste domande sono fondamentali per dialogare con i nostri informatici e decidere quando subentrare.
Grazie
Raffaele Chiariello - Comune di Codroipo

**Comment by cmigliardi** [comment]
Buongiorno, 
si risponde nell’ordine ai quesiti posti.

1.	Cambio residenza in presenza di mutazione residenza in corso presso altro comune: sì, l’unica modalità per intercettare tale situazione è l’utilizzo dei procedimenti di ANPR. E’ in corso di implementazione un intervento in base al quale se per un cittadino è presente un procedimento per iscrizione o mutazione residenza non definito, un successivo cambio di residenza presso altro comune sarà inibito.
2.	Certificazione cittadini con procedimenti aperti; sì se il procedimento non definito è  del comune competente sul cittadino. In ogni caso, sotto propria responsabilità,  è possibile utilizzare l’opzione di forzatura emissione certificato.
3.	Utilizzo “gestione procedimenti amministrativi”: le funzionalità rappresentano un ausilio alla lavorazione delle pratiche anagrafiche. Sono disponibili le funzionalità di consultazione utilizzando come criterio di ricerca un identificativo procedimento oppure un cittadino oppure uno specifico evento anagrafico.
Il prospetto riepilogativo mensile elabora gli eventi comunicati alla data della richiesta per cui sono contabilizzati tutti gli eventi con data definizione valorizzata nel mese di riferimento (ossia i singoli eventi sono conteggiati singolarmente solo se hanno la data di definizione che rientra nel periodo oggetto di rilevazione).  
In generale per le elaborazioni statistiche si rappresenta che   ISTAT elabora i dati ricevuti direttamente da ANPR tramite un sistema di notifiche di eventi anagrafici e relativi annullamenti, più altre tipologie di forniture periodiche.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by Codroipo2018** [comment]
[cid:image001.png@01D1432C.1D6D2810]


[cid:image002.png@01D1432C.1D6D2810]



Buonasera dott.ssa Migliardi,
La ringrazio per la risposta alla ISSUE 1308 che mi tocca riaprire, perchè per un numeroso gruppo di Comuni il problema statistico in vista del subentro in ANPR è molto impotrtante e abbiamo bisogno di capire di più e meglio per dialogare poi con I nostri fornitori informatici.
Volevamo essere già subentrati, ma vi sono ancora dei problemi ulteriori, oltre quelli oggetto della ISSUE, che debbono essere risolti nel ns gestionale oltre questo, speriamo che con la risoluizioni di tutti I dubbi si riesca a subentrare al più presto.
Se ha bisogno di chiarimenti in questo periodo sono costantemente in ufficio.
Cordiali saluti e grazie per l’attenzione.
Raffaele Chiariello
Ufficio Servizio Demografici
Tel 0432 824537 Fax 0432 824582
raffaele.chiariello@comune.codroipo.ud.it<mailto:raffaele.chiariello@comune.codroipo.ud.it>
Piazza G. Garibaldi, 81 - 33033 - Cittï¿½ di Codroipo (UD)
comune.codroipo@certgov.fvg.it<mailto:comune.codroipo@certgov.fvg.it>
http://www.comune.codroipo.ud.it/




[cid:image003.png@01D1432C.1D6D2810]

Comune di Codroipo (UD) - Informativa sulla privacy D.Lgs 196/2003 Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario proibita.La sicurezza e la correttezza dei messaggi di posta elettronica non possono essere garantite.
Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci e distruggerlo.
Grazie.






Da: cmigliardi <notifications@github.com>
Inviato: giovedì 9 maggio 2019 11:22
A: italia/anpr <anpr@noreply.github.com>
Cc: Chiariello Raffaele - Codroipo <raffaele.chiariello@comune.codroipo.ud.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] PROCEDIMENTO AMMINISTRATIVO - UTILITA' (#1308)


Closed #1308<https://github.com/italia/anpr/issues/1308>.
