### ISSUE TITLE
Certificabilità di soggetti "non iscrivibili"

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#131]
Attualmente ANPR gestisce tra gli attributi del soggetto la condizione di "non iscrivibilità" considerandolo come un blocco di certificabilità.
In realtà, la condizione di non iscrivibilità non dovrebbe avere alcun impatto sulla certificabilità del soggetto, ma piuttosto sulla sua iscrivibilità/possibilità di mutare residenza sul registro anagrafico. (Test eseguito in ambiente test, il 12/4/2017, soggetto ID ANPR 980769, codice errore Il certificato non può essere emesso in quanto il soggetto risulta non iscrivibile (Codice: EN047)).
Ad esempio, un soggetto non iscrivibile nel comune X ma attualmente regolarmente residente nel Comune Y, salvo questioni di altra natura (ovvero veri e propri blocchi di certificabilità), dovrebbe essere certificabile nel comune Y.
L'informazione riportata in anagrafe dovrebbe riguardare invece il fatto che il comune X non può istruire una mutazione di residenza per quel soggetto se egli è già in ANPR o non può iscriverlo se arriva da un comune non subentrato o dall'estero.
Grazie,
Gruppo di lavoro ANPR - Comune di Torino

**Comment by rvinzani** [comment]
Chiudo la issue in quanto già è stato evidenziato che l'informazione di non iscrivibilità è fuori ambito ANPR. In caso fossero necessari ulteriori chiarimenti si prega di riaprire la issue facendo riferimento a questa stessa
