### ISSUE TITLE
[1001] operazione non effettuabile AEE97

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1310]
Ambiente produzione

codiceErroreAnomalia : AEE97
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-07 09:39:55 , idOperazioneANPR 84034428

abbiamo ricevuto almeno 4 segnalazioni come questa stamattina da clienti diversi a seguito di richiesta di iscrizione per nascita aire.
Possiamo avere qualche dettaglio sul problema ?
Grazie - saluti.
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Errata corrige, non si tratta di nascite AIRE ma di residenti.
Scusate.
Filipazzi - Maggioli

**Comment by siscomanpr** [comment]
Anche noi abbiamo ricevuto delle segnalazioni in merito.

Siscom SPA

**Comment by ncapozzi** [comment]
Buongiorno,
ieri mattina abbiamo avuto un problema nelle chiamate ai servizi di Agenzia delle Entrate che è stato risolto.
I comuni interessati possono ripetere le operazioni che hanno avuto codiceErroreAnomalia : AEE97

N. Capozzi
