### ISSUE TITLE
[2011] Annullamento Cancellazione - Errore CN148

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1311]
ambiente di PRODUZIONE - comune di MERCATO SARACENO (040020)

caso strano di soggetto che in ANPR risulta cancellato dal nostro comune (idSoggettoANPR 18637765)
stiamo tentando di annullare la comunicazione di cancellazione (ws 2003) che è l'ultima che lo riguarda, e la comunicazioni di annullamento (ws 2011) segnala il seguente errore:
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>CN148</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>L'OPERAZIONE CHE SI CERCA DI ANNULLARE E' RELATIVA A SOGGETTI NON DI COMPETENZA DEL COMUNE</testoErroreAnomalia>
  </errore>
  <errore>
    <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-10 16:31:18 , idOperazioneANPR 85903761</testoErroreAnomalia>
  </errore>
</listaErrori>
```
è possibile avere qualche chiarimento?

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, stiamo verificando la vostra segnalazione. dovrebbe trattarsi di una anomalia che abbiamo individuato e stiamo correggendo.
Vi avviseremo appena sarà possibile riprovare.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Abbiamo rilasciato la correzione.
potreste riprovare?
saluti
Assistenza ANPR
