### ISSUE TITLE
Soggetto nato nella provincia di CATTARO - Governatorato della Dalmazia

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1312]
Comune di Modena - Ambiente di produzione

Buongiorno,
per poter  rilasciare la CIE alla cittadina con idANPR 19230633  dobbiamo risolvere il disallineamento tra il luogo di nascita indicato in ANPR (MELINE ZELENIKA in SERBIA MONTENEGRO) e AE (IUGOSLAVIA).
Dall' atto di nascita risulta che la signora è nata nel 1943 a MELINE con atto formato a Castelnuovo di Cattaro (ora HERCEG NOVI in Montenegro) che all' epoca era territorio italiano facente parte del Governatorato di Dalmazia. Diversamente dalle province dell' Istria (Pola, Fiume, Zara) la provincia di Cattaro sembra non essere stata codificata nè da ISTAT nè dall' Agenzia del Territorio. E' così o la codifica esiste? 
Nel caso non esista, la soluzione più corretta è trattare Castelnuovo di Cattaro come appartenente alla IUGOSLAVIA, dato che all' epoca la SERBIA MONTENEGRO non esisteva? 

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buongiorno,
la codifica ufficiale, anche degli ex comuni non più appartenenti al territorio italiano è quella pubblicata sul portale di https://www.anpr.interno.it/portale/. Se non riesce a ricondurre il luogo di nascita a tale codifica, probabilmente la cosa più corretta è allineare con Agenzia delle Entrate visato che, come da lei stessa evidenziato, all' epoca la SERBIA MONTENEGRO non esisteva.

N. Capozzi

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
non trovando codifiche utilizzabili sul portale abbiamo tentato di allineare la posizione ANPR del soggetto a quella AE con la funzione di risoluzione disallineamenti, che però non ha riportato su ANPR lo stato di nascita corretto. 
Abbiamo poi tentato una mutazione dei dati anagrafici dalla WebApp lasciando lo Stato estero di nascita "NON ATTRIBUIBILE" (come già era) e impostando i valori:
Descrizione stato:  IUGOSLAVIA
Località estera: MELINE
ma otteniamo questo errore:
Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-16 09:36:39 , idOperazioneANPR 87182187 (Codice: EN527)

Come possiamo agire per correggere il dato?

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
La Sig.ra Fiorini è stata contattata telefonicamente e il problema risolto

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
abbiamo un caso analogo relativo al soggetto con idANPR 19266711 che, iscritto come nato in stato NON ATTRIBUIBILE con descrizione SERBIA E MONTENEGRO, deve essere allineato alla posizione presente in AT dove risulta correttamente nato in IUGOSLAVIA. La mutazione dei dati anagrafici fallisce con errore:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-07 09:52:20 , idOperazioneANPR 94004909 (Codice: EN527)

mentre il tentativo di risoluzione del disallineamento non ha nessun effetto.

Abbiamo poi il caso del soggetto con idANPR 21478191 che ha in AT due posizioni scollegate: un CF numerico marcato ANPR e un CF alfanumerico corrispondente alle nuove generalità che dovremmo attribuirgli. Poichè cambiano sia il nome che la data nascita, in qualsiasi modo tentiamo di agire veniamo bloccati o per eccesso di campi modificati (dalla risoluzione disallineamenti) o con l' errore

Operazione non effettuabile (Codice: AEE95)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-07 10:10:33 , idOperazioneANPR 94021888 (Codice: EN527)

se tentiamo di generare un CF intermedio modificando solo il nome o parte della data nascita.
Per cortesia potete aiutarci? 

Grazie, cordiali saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
La Sig.ra Fiorini è stata contattata telefonicamente e il problema risolto

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
dobbiamo modificare il luogo di nascita del soggetto con idANPR 19323596 da SERBIA MONTENEGRO a FIUME (FU) con conseguente modifica del codice fiscale, ma veniamo bloccati dall' errore:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-20 10:00:53 , idOperazioneANPR 97198102 (Codice: EN527)

In AT il soggetto ha una sola posizione validata e marcata ANPR, dove però il luogo di nascita è IUGOSLAVIA e temo che questo ci impedisca di proseguire (come già visto nei casi precedenti di questa issue). Per cortesia potete aiutarci a sbloccare?

Grazie, cordiali saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera,
abbiamo segnalato il problema ai nostri colleghi di Agenzia Entrate.
Per il futuro le chiedo cortesemente di aprire una nuova issue per ogni problema che vuole segnalare.
Grazie
N. Capozzi

**Comment by ncapozzi** [comment]
Buongiorno,
può riprovare ad eseguire l'operazione per favore?
N. Capozzi

**Comment by sfmodena** [comment]
Buongiorno,
l' operazione ha avuto esito positivo, grazie per la rapidità.
Cordiali saluti
Sonia Fiorini
