### ISSUE TITLE
[4005] errore acquisizione notifiche ANPR02

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1313]
buongiorno,
il problema che vi segnalo è relativo ad una richiesta di ricezione notifiche di cancellazione.
abbiamo fatto delle prove nel comune di Cartoceto in PRESUBENTRO e ci ritornano correttamente N file .gz che poi dezippiamo per andare a prendere l'xml al loro interno. funziona tutto correttamente.

abbiamo fatto poi la stessa prova in modalità SUBENTRO e ci sono dei problemi:
la comunicazione va a buon fine, i file .gz ritornano correttamente, ma al loro interno c'è un xml sempre vuoto.

visto che ci occupiamo noi della trasformazione da file gz a xml, abbiamo fatto un ulteriore prova mantenendo il file originale gz e aprendolo con winrar, ma abbiamo lo stesso esito con un file xml vuoto al suo interno:

Comune di Cartoceto
modalità Subentro

dettaglio file xml Richiesta4005

`<verificaStato>
<idOperazioneANPR>86134006</idOperazioneANPR>
<progressivo>1</progressivo>
</verificaStato>`

**Comment by mttfranci** [comment]
Salve, dovremmo aver trovato e corretto il problema.
Inoltre abbiamo rigenerato le richieste già inviate.
Potete verificare se ora il contenuto è corretto?
Grazie in anticipo.

**Comment by fmbianchi** [comment]
salve,
abbiamo fatto diverse prove qui in sede.
Per le richieste che avete rigenerato il problema non si è più ripresentato, abbiamo ricevuto i filx gz con all'interno gli xml pieni.
Siamo andati successivamente a fare delle nuove richieste ed in questo caso invece l'errore si è ripresentato

id operazione anpr: 86400936

**Comment by mttfranci** [comment]
Si avevamo fatto una esecuzione ad hoc senza allineare la schedulazione, ci scusiamo.
Le future generazione dovrebbe avere esito positivo.
Da notare che è stata eseguita una ulteriore correzione.
Per le notifiche veniva popolato sia il campo contenutoRichiesta che contenutoRisposta (il che era una ridondanza dato che sono uguali).
Ora viene popolato solo il campo contenutoRisposta anche in caso si specifichi TUTTO.
