### ISSUE TITLE
Problema annullamento di mutazione residenza comune subentrato

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1314]
Salve siamo impossibilitati ad effettuare l'annullamento per l'individuo con IdAnpr35083490 dell'operazione con id Anpr 48386380, ricevendo l'errore :
OPERAZIONE GIA' ANNULLATA DALL'OPERAZIONE 84571383; Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-08 17:27:13 , idOperazioneANPR 84632133;

**Comment by asqueglia** [comment]
Buongiorno, l'operazione da voi indicata, fornita nell'errore ricevuto 84632133, è una richiesta di annullamento (5012) di una mutazione famiglia/convivenza di tipo altri recapiti con idOperazione 48386393. Tale operazione risulta, in effetti, essere già stata annullata in data 2019-05-08 alle 13:52 con l'operazione 84571383 andata a buon fine. Credo abbiate erroneamente trasmesso come operazione da annullare la 48386393 anziché la 48386380.

**Comment by asqueglia** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
