### ISSUE TITLE
AGGIORNAMENTI INPS

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1315]
Buongiorno,
con frequenza ormai settimanale, gli operatori INPS inviano al nostro ufficio cittadini che hanno avuto reiscrizioni da IRREPERIBILITA' e per i quali non risulta essere pervenuta ai loro uffici comunicazione in tal senso. E' un problema solo del nostro comune?
In questi casi provvediamo a effettuare variazione da portale ma ci è sorto il dubbio possa trattarsi un problema di corretto invio della mutazione. 
Esempio:
ID  44899206
ID  47890913 

Grazie
Anna Maria AIMONE
UPI - Codici fiscali
Comune di Torino

**Comment by bfilipazzi** [comment]
Anche il comune di Catania ci ha segnalato lo stesso problema.
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buongiorno, 
non c'è nessun problema sugli invii delle mutazioni in ANPR. In attesa che il flusso di comunicazioni tra INPS ed ANPR entri a regime completo per questa casistica si riporta quanto segue.

I Comuni, se in possesso di PIN, possono comunicare le variazioni a INPS utilizzando la procedura VARCO, ovvero inviando una PEC alla sede INPS  che ha in carico il soggetto (ultima sede di competenza o nuova sede di competenza in caso di re-iscrizioni).
Qualora un Comune voglia annullare una cancellazione per irreperibilità, può inviare una mail alla casella istituzionale arca.assistenza@inps.it, indicando il codice fiscale del soggetto e chiedendo di annullare la cancellazione trasmessa per errore.

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
