### ISSUE TITLE
Specifiche "documentali" dei certificati ANPR

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#1316]
Buongiorno, ho provato a tirare su la "vecchia" ma ancora issue (#287) che avevo trovato cercando informazioni su qualcosa di simile e dopo aver aperto, per ora senza esito, una discussione su forum.italia.it sul tema degli aspetti diplomatico-documentali dei certificati prodotti da ANPR. La ripropongo come nuova issue. Per premesse e considerazioni hce spiegano il motivo della richeista rimando alla issue gia' aperta. Qui ripropongo solo i "quesiti".

Dove posso trovare informazioni certe su aspetti quali:
- cosa conserva ANPR sul suo sistema?
- l’hash presente nell’URL del qr-code a quale oggetto digitale si riferisce?
- l’originale informatico, come file, è in qualche modo legato alle credenziali di accesso degli operatori d’anagrafe e ai vari certificati/smartcard che utilizzano per accedere ad ANPR?
- a garanzia di integrità e immodificabilità del documento-certificato in che modo sono state implementate nel sistema le previsioni dell’art. 3 del dpcm 13/11/2014 (regole tecniche sul documento informatico) con particolare riferimento, ma non solo, al comma 6?

Queste informazioni sono necessari per approcciare il tema della validità dei certifiati prodotti tramite ANPR, che è senz'altro un ambito in cui applicare a proposito i concetti elaborati dalla diplomatica del documento contemporaneo.

_Originally posted by @franthemanIT in https://github.com/italia/anpr/issues/287#issuecomment-492111846_

**Comment by marcocipri** [comment]
Buongiorno franthemanIT,
stiamo provvedendo a raccogliere tutte le evidenze normative per darti una risposta esaustiva.
Dato che le domande sono articolate e sicuramente non banali, potrebbe volerci un po più di tempo del solito ma abbiamo preso in carico la tua richiesta.
Contiamo di tornare presto con una risposta.

Saluti.

**Comment by marcocipri** [comment]
Buongiorno,
di seguito i commenti ai punti sollevati.
Restiamo a disposizione per eventuali dettagli.
 
> Dove posso trovare informazioni certe su aspetti quali:
> cosa conserva ANPR sul suo sistema?

**attualmente ANPR sui suoi sistemi conserva una copia non certificata del documento informatico non firmato digitalmente**  
 

> l’hash presente nell’URL del qr-code a quale oggetto digitale si riferisce?

**al documento documento informatico non firmato digitalmente**

 

> l’originale informatico, come file, è in qualche modo legato alle credenziali di accesso degli operatori d’anagrafe e ai vari certificati/smartcard che utilizzano per accedere ad ANPR?


**L'accesso al sistema da parte dell'operatore di anagrafe è permessa solo a valle dell'autenticazione tramite certificati di postazione e smart card.
Esclusivamente dopo l'autenticazione all'operatore è permesso effettuare una richiesta e ricevere la trasmissione del documento informatico non firmato digitalmente.
La trasmissione viene tracciata sul sistema di ANPR mantenendo l'identificazione dell'operatore.**
 

> a garanzia di integrità e immodificabilità del documento-certificato in che modo sono state implementate nel sistema le previsioni dell’art. 3 del dpcm 13/11/2014 (regole tecniche sul documento informatico) con particolare riferimento, ma non solo, al comma 6?

**Non è stato ancora implementato il meccanismo che garantisce  l'integrità e immodificabilità del documento custodito sul sistema ANPR. Questo significa che, al momento, la validità legale della copia analogica del documento viene garantita dalla firma autografa dell'operatore che la rilascia. 
Sono in fase di definizione le specifiche tecniche per il rilascio dei certificati in modalità online, come documento informatico.**
