### ISSUE TITLE
Rilascio certificazioni in esenzione bollo

### ISSUE THREAD

**Issue by ComuneLivigno** [italia/anpr#1318]
Scrivo per avere delucidazioni su alcune esenzioni dell’imposta di bollo sui certificati anagrafici.
Giungono presso i nostri uffici richieste da parte di studi legali, per il rilascio di certificazioni anagrafiche in esenzione del bollo ai sensi della circolare 24/E dell’Agenzia delle entrate. 
Non risulta inoltre la possibilità di rilascio in esenzione per come previsto dall’Art. 80 del Regolamento CE n. 883/2004.
SOGEI ha risposto alla nostra richiesta indicando la possibilità di inserire altre esenzioni.

**Comment by rvinzani** [comment]
E' possibile indicare come motivo di esenzione "altro" ed una descrizione libera del motivo che però non verrà riportata sul certificato

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova facendo riferimento a questa stessa
