### ISSUE TITLE
 kossovari

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#1319]
Buongiorno, 
capita solo a me?
 che per i cittadini stranieri nati in ex jugoslavia (ora Kosovo) la questura  è obbligata a storicizzare su base anno  lo stato di nascita, e quindi nel caso specifico inserendo lo stato di jugoslavia con conseguente cambio di codice fiscale che risulta presente in WA (agenzia delle entrate). In ANPR risulta correttamente il precedente CF ma blocca il rilascio CIE...
Il cittadino, ci chiede di cambiare il CF ..... qualcuno mi illumina?
A mio parere si continua a far proliferare pozizioni diverse che partono da due CF assegnati alla stessa persona.
Ma il CF non doveva essere IL NUMERO IDENTIFICATIVO unico e irripetibile?
Sentita la questura, la collega, tra il disperato e l'ansioso, mi dice che c'è una precisa direttiva del Ministero.
Grazie
Raffaella
Comune di Spinea
0415071155

**Comment by rvinzani** [comment]
I due codici fiscali non sono collegati tra di loro? Possiamo avere un idANPR con un caso specifico per effettuare un'analisi mirata? Grazie

**Comment by Raffive** [comment]
certo!
per cortesia mi date una mail devo inviarvi delle copie..
Grazie

**Comment by rvinzani** [comment]
Gent.le Raffaella, ho ricevuto le sue informazioni. Ho ai colleghi che lavorano per Agenzia Entrate se possono fornire qualche delucidazione,

**Comment by Raffive** [comment]
Grazie!
conto anche su una soluzione.
Raffaella

**Comment by rvinzani** [comment]
Come da email inviata non sono riuscita ad avere ulteriori informazioni. Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti la prego di aprire un'altra issue facendo riferimento a questa
