### ISSUE TITLE
Condizioni di "non iscrivibilità/non emigrabilità"

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#132]
Il soggetto ID ANPR 924877 (ambiente di test) ha un blocco di certificabilità "non iscrivibile" ma non è presente alcun elenco di comuni presso cui non possa emigrare. 
Eseguendo la cancellazione verso un comune non subentrato, il sistema lascia procedere (Id operazione 456078) con alert "Attenzione:Errore con descrizione non disponibile (Codice: EN112)". 
Come indicato nell'issue #131 sarebbe più corretto gestire la condizione come un attributo diverso dal concetto di certificabilità.
Nel caso specifico, dal momento che il soggetto è già iscritto, il termine "non iscrivibilità" sembra essere fuorviante. Sembrerebbe più corretto che il Comune di iscrizione potesse gestire l'attributo come concetto di "non emigrabilità" verso uno o più Comuni per un periodo definito di tempo.
Per fare ciò sarebbe quindi necessario collegare all'attributo "non emigrabilità" una tabella contenente i Comuni verso i quali non può essere effettuata una mutazione di residenza/cancellazione che specifichi anche le date di inizio/fine provvedimento.
Tale attributo dovrebbe conseguentemente inibire le mutazioni richieste dal Comune "bloccato" e le cancellazioni verso il Comune "bloccato", nel caso di non subentrato.

Inoltre, nel caso di soggetti non iscritti in ANPR  (solitamente perchè cancellati), dovrebbe poter essere gestita, sempre con collegamento ad una tabella di Comuni inibiti, la "non iscrivibilità".

Per cercare di spiegare meglio la casistica, proviamo ad esporre 3 situazioni tipo:
1- soggetto "non iscrivibile": la Questura segnala che ad alcuni soggetti è stato notificato provvedimento di rimpatrio con Foglio di Via Ordinario (F.V.O.) con divieto di ritornare 
nel Comune X per anni 3. La comunicazione viene inviata anche all'ufficio Anagrafe nel caso in cui i cittadini chiedano nuovamente l'iscrizione anagrafica nel Comune prima del termine del provvedimento.
2- soggetto "non emigrabile": la Questura segnala al comune X e al comune Y che un certo cittadino non può richiedere iscrizione a Y; quindi X non può cancellarlo per Y. Questo caso potrebbe essere risolto tramite un blocco di "non iscrivibilità" a Y se entrambi i Comuni sono subentrati; se invece solo uno dei due Comuni è subentrato, nello specifico X, sarebbe necessario tracciare che X non può cancellarlo se è Y a farne richiesta (se invece lo chiede un altro Comune non ci sono impedimenti).
3 - soggetto "non emigrabile": la Questura segnala che un certo cittadino ha obbligo di soggiorno per un anno ad un indirizzo nel comune X. Comunica quindi che nel caso in cui arrivasse richiesta di cancellazione per altro Comune non bisogna procedere.

Attualmente il ns. Comune opera con queste modalità:
1 - inserisce pratica di "non iscrivibilità" che impedisce di istruire una pratica di iscrizione anagrafica per il soggetto;
2 e 3 - inserisce pratica di "non emigrabilità" che impedisce di istruire una pratica di cancellazione anagrafica per emigrazione, gestendo anche una tabella collegata di Comuni verso cui non può essere effettutata la cancellazione, oltre alle date di inizio e fine validità del provvedimento.

Fintanto che il Comune utilizza i WS, bloccando quindi a monte le funzioni, per l'iscrizione in ANPR (caso 1) non si pongono grossi problemi (si porrebbero invece in caso di utilizzo esclusivo della WA).
Nei casi 2 e 3 in cui, se l'altro Comune è subentrato, senza la corretta informazione e conseguente blocco della registrazione, potrebbe mutare la residenza del soggetto. Il Comune di precedente residenza ne verrebbe a conoscenza soltanto a posteriori tramite notifica, con difficoltà per entrambi i Comuni nel sanare la situazione.

Dal momento che nei grandi Comuni la fattispecie riguarda un numero considerevole di soggetti, chiediamo se possa essere ipotizzabile una gestione anche tramite WS.

Grazie, 
il gruppo di lavoro del Comune di Torino

**Comment by gcarbonin** [comment]
Come detto nella risposta precedente stiamo analizzando le implementazioni che riguarderanno sia la WA che i WS
