### ISSUE TITLE
[4005] Richieste in sospeso da molti giorni

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1320]
Ambiente di test, comune di Manerbio

vediamo in sospeso molte richieste fatte tra il 2 ed il 3 di maggio che non risultano ancora pronte :

**DATA               ID ANPR**
02/05/2019	19670679
02/05/2019	19670809
02/05/2019	19670907
02/05/2019	19671028
02/05/2019	19671118
02/05/2019	19671172
02/05/2019	19671235
02/05/2019	19671291
02/05/2019	19671348
03/05/2019	19671924
03/05/2019	19672006
03/05/2019	19672184
03/05/2019	19672329
03/05/2019	19672451
03/05/2019	19672602
03/05/2019	19672702
03/05/2019	19672869
03/05/2019	19673119
03/05/2019	19673251
03/05/2019	19673326
03/05/2019	19673422
03/05/2019	19673492
03/05/2019	19673571
03/05/2019	19673643
03/05/2019	19673716

Potete verificare ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Le richieste ora dovrebbero essere tutte elaborate.
Abbiamo anche perfezionato i sistemi di monitoraggio e recupero, quindi speriamo queste situazioni non si verifichino più.
Saluti

Assistenza ANPR

**Comment by busaster** [comment]
Perfetto
Grazie
