### ISSUE TITLE
Rettifica indirizzo AIRE

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1322]
Ambiente di test
Intendo rettificare l'indirizzo al soggetto AIRE con IdANPR 18913901
Verifico la decorrenza della residenza e con l'operazione ID 19702283 ottengo in risposta: dataDecorrenzaResidenza 2018-06-15+02:00.
Invio la richiesta di rettifica con questi estremi: data 2019-05-14 16:52:23 , idOperazioneANPR 19702284 specificando la decorrenza del 2018-06-15 e ottengo un rifiuto con l'errore EN526 che dice: Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 13-06-2018.
Direi che c'è una contraddizione, come possiamo risolvere? Grazie
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buonasera, 
la discordanza nasce dal fatto che in subentro sono state indicate due differenti date di decorrenza residenza: 
- 13.06.2018 per la famiglia
- 15.06.2018 per il cittadino.
La rettifica indirizzo effettua il confronto tra le date indicate nella richiesta  e la data decorrenza della famiglia.
Per allineare le date si potrebbe rettificare la data decorrenza residenza del cittadino con il ws 5014 portandola al 13.06.2018 e poi  ripetere la rettifica indirizzo utilizzando quest'ultima data.

**Comment by bfilipazzi** [comment]
Non sono d'accordo, forse non ho capito.
Non vedo due decorrenze di residenza (per la famiglia e per la persona), ma una decorrenza di residenza e una decorrenza della famiglia, a prima vista in questo caso può essere un pasticcio nei dati ad averle fornite diverse di due giorni, ma non c'è un motivo anagrafico per cui debbano necessariamente essere uguali.
La decorrenza della famiglia è la data in cui la famiglia ha avuto origine, perché dovrebbe coincidere con la decorrenza della residenza? la prima è immutabile la seconda varia in base ai cambi di abitazione.
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Presento un altro esempio simile al precedente.

La consultazione 3200 con idOperazioneANPR 19719367 mi dice che il soggetto AIRE con id 18913930 ha i seguenti dati:
dataDecorrenzaResidenza 2007-12-03
dataOrigineFamigliaConvivenza 1990-07-01

Eseguo la richiesta 5001 di rettifica dell'indirizzo con idOperazioneANPR 19719369 che ha dataDecorrenza 2007-12-03

e ottengo in risposta l'errore EN256
Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 01-07-1990

Ripeto quanto osservato in precedenza: la data testata da ANPR 01-07-1990 non è la decorrenza della residenza bensì è la data in cui la famiglia ha avuto origine. La famiglia abita all'indirizzo attuale che si vuol rettificare dal 2007-12-03.
Questo comportamento di ANPR impedisce la rettifica dell'indirizzo.

Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buonasera, 
la problematica non riguarda la  rettifica indirizzo ma il subentro. La criticità segnalata può presentarsi per i  cittadini AIRE entrati in ANPR con il subentro. 
Poiché il set di dati AIRE in subentro è molto più limitato rispetto a quello degli APR e non sempre  le date previste sono valorizzate,  in alcuni casi è necessario fare delle assunzioni.
Stiamo apportando un correttivo alla procedura del subentro: se lo desidera può effettuare una richiesta di cancellazione del subentro del comune in trattamento e ripeterlo.
Si resta in attesa di un cortese riscontro.     
Buonasera

**Comment by bfilipazzi** [comment]
Nel file di subentro le date del soggetto in esame sono valorizzate.
La data di iscrizione aire è il 01/07/1990 e la data di aggiornamento indirizzo il 03/12/2007.
Queste date sono le stesse che si vedono sulla WA.
Continuo a non capire il problema-

La proposta di ripetizione del subentro aire mi ha sconcertato, dovremmo ripeterlo per 580 clienti subentrati? E le variazioni intercorse nel frattempo?

Filipazzi - Maggioli

**Comment by azabatta** [comment]
Mi riferivo ovviamente al solo ambiente di TEST  nel quale sta provando il nuovo codice mutazione.
Per i prossimi subentri  il problema non si presenterà più.
Stiamo analizzando i dati dei comuni già subentrati per le valutazioni del caso.

**Comment by bfilipazzi** [comment]
Bene, il chiarimento è confortante.
Sarà interessante conoscere gli sviluppi.
Grazie

Filipazzi  - Maggioli

**Comment by azabatta** [comment]
Buongiorno, 
è stata realizzata una procedura che riallinea la data di interesse  sui dati delle famiglie non movimentate dopo il subentro.
Al momento il riallineamento è stato effettuato in ambiente di  TEST_COMUNI.
E' possibile riprovare: attendiamo un cortese riscontro sulla risoluzione dei due casi  segnalati.
Grazie

**Comment by bfilipazzi** [comment]
Ho riprovato oggi, entrambi i casi sono andati a buon fine.
Grazie.
Filipazzi - Maggioli
