### ISSUE TITLE
Subentro: suddivisione componenti stessa famiglia AIRE

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1323]
Salve,
presso il comune di Villa d'Adda subentrato il 10/05/2019 abbiamo riscontrato che i componenti di una stessa famiglia AIRE sono stati suddivisi nell'applicativo in due famiglie differenti.
Mi riferisco ai cittadini 59358019, 59358059, 59358070 facenti parte dello stesso nucleo familiare nel comune, ma in ANPR compongono due famiglie differenti: 59358019 iscritto nella 35341672 mentre gli altri due nella 35341724. 
Controllando il file di subentro per gli AIRE non vedo nulla di anomalo in merito al numero foglio famiglia in quanto è identico per tutti e tre i cittadini. 
Chiedo delucidazioni in merito, 
Grazie

**Comment by mttfranci** [comment]
Salve, abbiamo verificato che per il secondo e terzo soggetto da voi indicato, è stato inviato un comune iscrizione AIRE diverso, ecco un estratto della righe 208 e 209 relative ai soggetti 59358059 e 59358070 : 
03**000000**20120703
In generale il comune di iscrizione AIRE dovrebbe essere sempre il comune che sta effettuato il subentro.
Ma questa anomalia ha portato ad aprire una seconda famiglia per 59358059 e 59358070.

Se volete possiamo eccezionalmente associare tutti e tre i soggetti alla prima famiglia (dato che non si tratta di modificare attributi di nessuno dei soggetti).

Vi suggeriamo di verificare la procedura con cui viene prodotta la fornitura AIRE e di validarla anche con il software ANAGAIRE prima dell'invio.

Cordiali saluti

Assistenza ANPR

**Comment by fmbianchi** [comment]
Perfetto effettueremo ulteriori controlli presso il comune per capire se hanno validato il file prima del subentro in ANPR.
Nel frattempo vi ringrazio

**Comment by mttfranci** [comment]
Prego, solo non siamo sicuri di aver capito se la situazione della famiglia la sanerete voi con il comune, oppure lo facciamo noi in questo nel modo proposto?
Saluti
Assistenza ANPR

**Comment by fmbianchi** [comment]
Salve, 
abbiamo controllato presso il comune e la situazione è effettivamente quella descritta da voi.
Se fosse possibile sistemare la situazione sarebbe ottimo, abbiamo trovato anche un'altra casistica analoga: cittadino 59358057 risulta distaccato dal nucleo dell'intestatario scheda 59357860.
Grazie

**Comment by mttfranci** [comment]
Perfetto, allora i primi tre soggetti ora sono nella famiglia 35341672, mentre gli altri sono nella famiglia 35341660.
Saluti assistenza ANPR.
