### ISSUE TITLE
[5001] migrazione in altro comune e famiglia coabitante

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1324]
Ambiente di test, comune di Poggio a Caiano

la famiglia ID ANPR 16887584  coabitava con la famiglia ID ANPR 16887584.

In data 15/05/19  il comune di Manerbio esegue una mutazione famiglia con cui la famiglia 16887584 trasferisce la sua residenza (id operazione ANPR 19703836).

Nonostante nella richiesta sia specificato 
`<presenzaFamigliaCoabitante>N</presenzaFamigliaCoabitante>`
se consulto la scheda di famiglia vedo che lo status di "con coabitante" è rimasto.

Secondo me ANPR deve impostarlo a "NO" nel caso di mutazione di famiglia che si sposta in altro comune ANPR, 

Gianrico Busa
Maggioli Spa

**Comment by AMonopoliADS** [comment]
Condivido.
Problematica già posta con issue #1074... registrata, al tempo, con label "evoluzione"
Grazie

**Comment by asqueglia** [comment]
Buongiorno, come riportato nella issue indicata da @AMonopoliADS  #1074 , per modificare l'attributo presenzaFamigliaCoabitante, è disponibile il servizio di mutazione famiglia/convivenza con tipo mutazione 'motivo famiglia/Specie convivenza' (servizio 5001 tipo mutazione 3). Non sono state previste al momento evoluzioni ai servizi di mutazione residenza. L'evoluzione con cui è stata etichettata la issue indicata si riferisce al servizio di consultazione famiglia/convivenza, per mostrare nell’elenco operazioni anche quelle effettuate sulla famiglia. L'intervento rientra nel piano dei lavori in corso, ne verrà data comunicazione secondo le consuete modalità di rilascio (changeLog, roadMap ecc.).

**Comment by busaster** [comment]
Capisco, a me pare una mancanza, considerando il fatto che il comune che iscrive non ha idea che l'iscrivendo formasse una coabitazione nel comune di provenienza.

**Comment by rvinzani** [comment]
Intervengo per ribadire quanto già espresso nella precedente issue  #1074. Il servizio di mutazione residenza famiglia/convivenza prevede che vengano modificati i soli dati della residenza che pertanto viene acquisita dal comune di destinazione con tutti gli attributi assegnati dal precedente comune. Lo stesso servizio può essere richiamato per modificare tali informazioni (tra i quali il numero scheda comunale) e in tale ambito è possibile aggiornare anche l'attributo di famiglia coabitante

**Comment by busaster** [comment]
Ne prendo atto, rimango dell'idea che la chiusura automatica delle coabitazioni contestualmente alla variazione di residenza  faciliterebbe il lavoro degli operatori .

**Comment by rvinzani** [comment]
Gli operatori non vengono aggravati in quanto credo sia già previsto la modifica del numero di scheda comunale e contestualmente il servizio può essere invocato per modificare il flag di famiglia coabitante senza ulteriore lavoro per l'operatore

**Comment by asqueglia** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
