### ISSUE TITLE
Errore EN72 - impossibile confermare iscrizione anagrafica

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1325]
Buongiorno,
il Comune di Ragusa non riesce a confermare una pratica di re-iscrizione da immigrazione dall'estero in quanto viene restituito il seguente messaggio d'errore:
ANPR segnala il seguente errore:
EN272 Alla data 02-06-2006 il soggetto idANPR 41969999 risulta gia' coniugato o unito civilmente con un altro soggetto
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-15 15:01:36 , idOperazioneANPR 87057890

Facendo un analisi dei dati presenti in ANPR l'unica anomalia che non si riesce a correggere è nel doppio spazio tra i nomi del coniuge.
Entrambe i coniugi sono collegati in modo corretto (tramite IDANPR) ma essendo stati entrambi precedentemente cancellati non si riesce ad effettuare nessuna rettifica.

Resto in attesa di un Vostro riscontro

Giovanni Durante
Kibernetes

**Comment by frmariani** [comment]
Si tratta di un refuso dovuto ad un'anomalia eliminata da tempo, adesso potete riprovare l'operazione.
La issue viene chiusa, nel caso,  si prega di aprirne un'altra facendo riferimento a questa stessa.
