### ISSUE TITLE
[3002] ANPR02: ricerca non funziona per cognome e nome

### ISSUE THREAD

**Issue by StefanoGuidetti** [italia/anpr#1326]
Buonasera,
abbiamo un problema nella ricerca soggetti, indipendentemente dall'ente a cui si è collegati

Se ricerchiamo un soggetto per cognome e nome riceviamo
"La richiesta effettuata non produce alcun risultato" 
[idOperazioneANPR>19705206, ente 036028]

se lo cerchiamo per codiceFiscale risulta presente negli archivi.
[idOperazioneANPR>19705210, ente 036028]

La stessa cosa succede anche su WAPP

Grazie
Stefano di PAL

**Comment by mttfranci** [comment]
Salve, in che ambiente state effettuando questa prova?

**Comment by StefanoGuidetti** [comment]
Ambiente di Test

**Comment by mttfranci** [comment]
Salve.
Il problema non è generalizzato e riguarda specificatamente alcuni casi presenti in test comuni e presubentro.
In generale la ricerca per nome e cognome è funzionante.
Il problema è causato da una errata gestione di una situazione che in produzione non dovrebbe capitare
In sostanza in ambiente di test e presubentro è possibile effettuare la cancellazione dell'intero subentro per un comune. Tale cancellazione ha lasciato una situazione non pulita per un soggetto con nome e cognome uguale a quello che avete cercato ma in un altro comune.
Trattandosi di un problema legato più all'ambiente di test che al software non lo consideriamo un bug.
Vi consigliamo di usare un altro soggetto per i vostri test.
In ogni caso cercheremo di sanare queste situazioni ed evitare che si ripetano per il futuro.
Saluti

Assistenza ANPR

**Comment by StefanoGuidetti** [comment]
Tutto chiaro.
Grazie
Stefano di PAL
