### ISSUE TITLE
EVENTO NASCITA PER TRASCRIZIONE ATTO DALL'ESTERO

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1327]
Non riusciamo ad iscrivere in Anpr un cittadino, a seguito di trascrizione di atto di nascita.
L'errore è il seguente:
ERRORE DA ANPR: 
EAA67 - Errore formale 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-15 17:15:25 , idOperazioneANPR 87090867

**Comment by rvinzani** [comment]
La descrizione della località contiene un apice ('S-GRAVENHAGE) che non è accettato dai servizi di Agenzia Entrate

**Comment by rvinzani** [comment]
Chiudo l'issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova facendo riferimento a questa stessa
