### ISSUE TITLE
[anpr.interno.it - Documentazione tecnica] SPECIFICHE DI INTERFACCIA 14052019

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1331]
Volevo segnalare che nella certella "Consultazioni" (SPECIFICHE DI INTERFACCIA 14052019\Specifiche_excel_14_05_2019) non vedo più il file relativo al servizio 3002. Si può avere l'ultima versione aggiornata? Grazie

**Comment by ncapozzi** [comment]
Il file xls relativo al servizio 3002 è stato reinserito nelle SPECIFICHE DI INTERFACCIA.

Cordiali saluti
N. Capozzi
