### ISSUE TITLE
PROCEDIMENTO AMMINISTRATIVO E PROBLEMATICHE STATISTICHE

### ISSUE THREAD

**Issue by Codroipo2018** [italia/anpr#1332]
AMBIENTE PRESUBENTRO - CODROIPO

Buongiorno,
riprendo la ISSUE 1308 in quanto abbiamo bisogno di ulteriori chiarimenti vista la Circolare ISTAT prot. 1836510 del 21.12.2018 con oggetto: Rilevazioni demografiche e sanitarie per l’anno 2019 – Attività di produzione statistica demografica degli Uffici Comunali e degli Uffici territoriali del Governo. Tale circolare ribadisce quanto già da ISTAT comunicato negli anni precedenti ai Comuni, ovvero questi sono tenuti a continuare ad inviare le stesse informazioni statistiche e, a partire dal secondo mese del  loro subentro in ANPR sono invitati a modificare tipologia di invio, cioè effettuando l’inoltro dei dati tramite ANPR. I Comuni per motivi inerenti la  gestione delle proprie attività hanno interesse ad essere certi che i dati statistici inviati ad ISTAT tramite ANPR siano uguali a quelli da loro detenuti, questo per non contravvenire alla normativa statistica. Il nostro è un Comune che ha collaborato in varie sperimentazioni con ISTAT e sentendo il parere di alcuni funzionari ISTAT esperti nel settore statistiche demografiche è emerso che in ogni caso i dati da loro attesi sono quelli di sempre. Non vi sono variazioni, intendono elaborare loro con prodotti informatici propri i microdati pervenute con le notifiche da voi inviate. A questo proposito si chiede:
1)	 Quando si effettua una operazione in ANPR collegata alla gestione procedimenti la relativa notifica ad ISTAT viene inviata:
a)	Solo in fase di apertura del procedimento; 
b)	Solo in fase di chiusura del procedimento;
c)	Sia in fase di apertura sia in fase di chiusura del procedimento (con rischio di doppio conteggio); in tal caso ISTAT è in grado di verificare a distanza di mesi che si tratta della stessa comunicazione?
I Comuni non subentrati conteggiano l’operazione 1 sola volta. (In questo caso parliamo delle pratiche di iscrizione per immigrazione che non vengono conteggiate al momento dell’iscrizione preliminare ma solo a quello dell’iscrizione definitiva).
Di conseguenza anche per chi utilizza la gestione procedimenti la comunicazione andrebbe inviata una sola volta e visto che l’esito del procedimento (anche se negativo) fa comunque chiudere la pratica si potrebbe per una questione di omogeinità con chi non usa il Procedimento la prima data.
2)	Nell’ambiente di test abbiamo provato manualmente ad effettuare delle MUTAZIONI TUTTI I DATI       comprese quelle con iniziativa  RETTIFICA. Abbiamo provato la Variazione di sesso delle persone  sia come Istanza di parte (quelle effettive) sia con Iniziativa RETTIFICA. In quanto in alcuni casi bisogna provvedere a correggere vecchi errori materiali di attribuzione sesso alla persona. Sono operazioni che non comportano variazioni nel totale complessivo della Popolazione ma lo comportano invece per quello che riguarda sia i Maschi sia le Femmine. Ho notato che pur indicando la data definizione pratica in entrambi i casi queste variazioni o rettifiche non venivano conteggiate nel d7b di competenza, cosa che invece deve avvenire calcolandole ai punti 5.3 e 6.3. Uno dei controlli che a fine anno ISTAT fa è quello di controllare se il totale della popolazione calcolato con suddivisione MF è identico o meno a quello derivante dalle persone iscritte prima in APR e ora anche in ANPR. 
Domanda: viene inviata ad ISTAT una comunicazione in caso di Variazione o rettifica del sesso indicando il tipo di modifica avvenuta?
3)	Analogo problema esiste per  le variazioni Anagrafiche relative al mutamento di cittadinanza (Acquisto cittadinanza italiana) o alla rettifica della stessa (correzione per errore fatto precedentemente). Abbiamo appena ricevuto da ISTAT ROMA – Dipartimento per la raccolta dati e per lo sviluppo di tecnologie per la produzione e la diffusione dell’informazione statistica, una segnalazione di errore per il mese di febbraio relativa ai dati inseriti nel modello D7b rispetto alle persone effettivamente inserite negli APR4. Tale errore in realtà non esiste perché non è prevista la compilazione dei modelli APR4 (al momento) nei casi in cui vi siano rettifiche di sesso o di correzione cittadinanza come avvenuto in questo mese e al tempo stesso bisogna fare in modo che il totale statistico sia uguale a quello reale degli iscritti in ANPR o per i Comuni non subentrati in APR. Per quanto riguarda questa tematica va segnalato che è in costante crescita il fenomeno di persone provenienti dall’estero (soprattutto Sud America) che inizialmente dopo essere stati iscritti come residenti stranieri nel corso del tempo al termine di tutti gli accertamenti del caso si vedono riconoscere la cittadinanza italiana dalla nascita, determinando il problema statistico di cui sopra. 
4)	Altra cosa notata è che se nelle operazioni (nascite, mutazioni residenza sia immigrati sia emigrati, morti, ecc.) effettuate non compare la data definizione pratica, queste non vengono conteggiate nel d7b utile ai Comuni per raffrontare la loro situazione nel gestionale con quella di ANPR, si potrebbe assegnare tale data di default inserendo quella del momento nel quale il dato viene registrato effettivamente in ANPR, anche nei casi in cui l’operazione avvenga tramite webservice? Ciò, in quanto, mi pare di aver capito che nella notifica al posto della data definizione pratica viene inserito la data in cui l’operazione è stata effettuata. Ad esempio nei nuovi modelli cartacei APR4 al posto di:”data definizione pratica” è ora riportata: “data comunicazione pratica”. Al tempo stesso si potrebbe mettere a disposizione dei Comuni, come già fatto per le LAC, un file copia di quanto trasmesso ad ISTAT.
Grazie per l’attenzione.
Cordiali saluti.
       						Raffaele Chiariello

**Comment by azabatta** [comment]
Buonasera, 
tutte le tipologie di eventi anagrafici inviati dal comune sono notificate ad ISTAT,  incluse le mutazioni di scheda individuale dei cittadini, con le stesse informazioni presenti nelle comunicazioni. Oltre alla notifica degli eventi anagrafici ISTAT riceve poi delle  forniture specifiche relative alla popolazione anagrafica (esempio LAC) oppure riferite a particolari situazioni anagrafiche.  L’Istituto quindi raccoglie tutti gli elementi per effettuare in autonomia le proprie elaborazioni (noi non forniamo degli elaborati). Questo consentirà al completo dispiegamento di ANPR di ottenere un “censimento permanente” della popolazione. 
Qualunque servizio di ANPR consente di indicare la data di definizione anche se non si tratta di un dato obbligatorio. E’ possibile quindi impostare la stessa data di decorrenza dell’operazione come data definizione sia invocando il servizio dal gestionale che utilizzando il sito web di ANPR. Se tale data non è presente non viene riportato nulla  nella notifica ad ISTAT. 
L’elaborazione degli eventi di mutazioni di dati rilevanti ai fini statistici (es. sesso, cittadinanza), comunicate dopo le iscrizioni,  non è prevista. Cercheremo di effettuare delle verifiche ISTAT al fine di capire se è necessario trattarli  o meno.
Per  quanto riguarda le LAC si rappresenta che sono elaborate e fornite solo ad ISTAT e non ai comuni.

Comunicazioni relative alle tipologie di dati notificati, alle modalità ed alla frequenza degli invii non sono di nostra competenza, ossia non siamo autorizzati a diffondere informazioni relative agli accordi tra ISTAT e Ministero dell’Interno.

Come previsto dal DPCM istitutivo di ANPR,  i DB locali devono essere aggiornati solo dopo l’esito positivo degli aggiornamenti in ANPR. Inoltre i gestionali devono effettuare gli opportuni allineamenti dei DB locali sulla base delle notifiche inviate da ANPR. Di conseguenza non c’è motivo di ritenere che i dati locali siano differenti da quanto presente in ANPR. 

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.

**Comment by Codroipo2018** [comment]
[cid:image001.png@01D1432C.1D6D2810]


[cid:image002.png@01D1432C.1D6D2810]



Buonasera,
Si ringrazia per la risposta.
Cordiali saluti
Raffaele Chiariello
Ufficio Servizio Demografici
Tel 0432 824537 Fax 0432 824582
raffaele.chiariello@comune.codroipo.ud.it<mailto:raffaele.chiariello@comune.codroipo.ud.it>
Piazza G. Garibaldi, 81 - 33033 - Cittï¿½ di Codroipo (UD)
comune.codroipo@certgov.fvg.it<mailto:comune.codroipo@certgov.fvg.it>
http://www.comune.codroipo.ud.it/




[cid:image003.png@01D1432C.1D6D2810]

Comune di Codroipo (UD) - Informativa sulla privacy D.Lgs 196/2003 Le informazioni contenute nella comunicazione che precede possono essere riservate e sono, comunque, destinate esclusivamente alla persona o all'ente sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario proibita.La sicurezza e la correttezza dei messaggi di posta elettronica non possono essere garantite.
Se avete ricevuto questo messaggio per errore, Vi preghiamo di contattarci e distruggerlo.
Grazie.






Da: azabatta <notifications@github.com>
Inviato: lunedì 20 maggio 2019 16:33
A: italia/anpr <anpr@noreply.github.com>
Cc: Chiariello Raffaele - Codroipo <raffaele.chiariello@comune.codroipo.ud.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] PROCEDIMENTO AMMINISTRATIVO E PROBLEMATICHE STATISTICHE (#1332)


Closed #1332<https://github.com/italia/anpr/issues/1332>.
