### ISSUE TITLE
[A001] errore 999 operazione non effettuabile

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1333]
Buongiorno, iscrivendo un aire per nascita ritorna errore 999 , ID OPERAZIONE 87990882 data 20/05/2019 ore 09:10:21
come risolvere?

Comune di VO'
ambiente produzione

**Comment by mttfranci** [comment]
Buongiorno, in effetti c'è un carattere nel cap estero, acquisito in fase di subentro, che non permette di portare a termine l'iscrizione (dipende dal fatto che in questo caso la residenza della famiglia di attribuzione viene riportata nella risposta). Abbiamo deciso di accettare anche il carattere '.', avviseremo appena sarà possibile riprovare.
Saluti.

Assistenza ANPR

**Comment by mttfranci** [comment]
Il problema dovrebbe essere risolto con la pubblicazione della patch [5.4.3](https://github.com/italia/anpr/blob/master/src/change-management/changelog.md)
