### ISSUE TITLE
5001 Rettifica/integrazione indirizzo (EN526 data decorrenza residenza)

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1334]
Facendo una comunicazione 5001 di tipo 9
Rettifica / Integrazione indirizzo, mi torna 

**errore**
EN526 Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 29-08-2005

Ma andando a vedere dentro l'xml la data decorrenza residenza è proprio quella che deve essere

ENTE: PRODUZIONE
COMUNE: COLLI AL METAURO

Informazioni sull'operazione da fornire in caso di assistenza : 
data 2019-05-20 10:28:00 , 
idOperazioneANPR 88061567

**Comment by asqueglia** [comment]
Buongiorno, il problema dovrebbe essere il timezone con cui avete trasmesso la data.
Nello specifico nella richiesta è stata trasmessa come data decorrenza 2005-08-29+01:00. Potete provare a trasmettere la richiesta impostando la data decorrenza senza timezone ossia 2005-08-29 ?

**Comment by fmbianchi** [comment]
DATA DECORRENZA o DATA DECORRENZA RESIDENZA?

perchè DATA DECORRENZA fà parte della testata 
e risulterebbe difficille differenziare questa testata dalle altre?

**Comment by asqueglia** [comment]
Sia la data decorrenza in testata che la data decorrenza residenza sono state trasmesse con timezone come 2005-08-29+01:00. Potreste ritrasmetterle senza timezone ?

**Comment by fmbianchi** [comment]
senza timezone su entrambe le date funziona.

Ma questo và fatto sempre e per tutti i servizi?
o solo per il 5001 con tipologia mutazione 9.
Dato che le altre comunicazioni sembrano andare a buon fine.

**Comment by asqueglia** [comment]
Buongiorno, in tutti i servizi dove vengono effettuati controlli di uguaglianza sulle date, il timezone, se trasmesso, viene preso in considerazione.

**Comment by asqueglia** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
