### ISSUE TITLE
[3002] Tipo di specie convivenza con VALORE ERRATO

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1335]
Ambiente di produzione, comune di Nocera Inferiore

Abbiamo un'errore applicativo durante il tentativo di processare uan notifica di migrazione in altro comune ANPR.
Indagando ci accorgiamo che nel XML di risposta al 3002 il codice ANPR della specie convivenza è 99.
Se consultiamo il soggetto da webapp vediamo il valore "VALORE ERRATO". (id operazione ANPR 88069761)

Il codice 99 non è presente nelle specifiche ANPR (nella tabella di codifica dei tipi di specie convivenza).

Immagino sia come per la issue #1262 , chiedo se possibile di adeguare il comportamento anche in questa situazione e non ritornare il dato dove errato.

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, ora il valore non dovrebbe comparire quando non valido.

**Comment by busaster** [comment]
Confermo il funzionamento della modifica.
Grazie
