### ISSUE TITLE
Notifiche non ricevute

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1336]
Ambiente di test
Comune di Manerbio 017103

Consulto sulla WA la pagina delle notifiche alle 10:40 del 21/05/2019.
Le notifiche di mutazione di residenza più recenti sono del 17/05/2019.
Ieri 20/05/2019 sono avvenuti almeno 3 movimenti migratori da Manerbio con destinazione Darfo Boario Terme:
1) richiesta A006 id Operazione ANPR 19716734 20/05/2015 ore 15:34;
2) richiesta A006 id Operazione ANPR 19716758 20/05/2019 ore 15:42;
3) richiesta 5001 id Operazione ANPR 19716841 20/05/2019 ore 15:57.

Perché non vedo le notifiche?
Grazie.

Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Stamattina 22/05/2019 ho eseguito un ulteriore movimento migratorio da Manerbio a Darfo Boario Terme, si tratta di una richiesta 5005 con id Operazione ANPR 19720599.
Vedo la notifica nella WA del comune di Manerbio.
Continuano a mancare le 3 segnalate in apertura di questa issue.
Filipazzi - Maggioli

**Comment by fferraguto** [comment]
Salve,
le notifiche non erano state generate per un problema di sistema, sono state rigenerate e dovreste rilevarle.
Saluti.
