### ISSUE TITLE
Reiscrizione in altro comune di straniero nato a Torino

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#134]
Straniero nato a Torino emigrato all'estero che si re-iscrive in un altro comune italiano: la norma prevede che sia trasmesso il modello APR4 al comune di nascita per conferma dati. 
Su ANPR come funzionerà? 
Grazie
Amprimo, Floramo, Guarraia

**Comment by gcarbonin** [comment]
Di quale norma si tratta? Se non è stata modificata, funzionerà allo stesso modo.

**Comment by annamariaGillone** [comment]
La norma di riferimento per la scheda individuale è l'art. 20 DPR 223/1989.
Il facsimile dell'AP5 è a pag. 106 delle avvertenze Istat.

gruppo Anpr - Torino

**Comment by gcarbonin** [comment]
L'art. 20 è stato modificato ma non si fa nessun riferimento all'adempimento in questione. Giro il quesito al Ministero dell'Interno.

**Comment by gcarbonin** [comment]
Da un confronto con il Ministero dell'Interno, se la persona è già transitata in ANPR (prima di emigrare all'estero è stata residente in un comune subentrato), i dati sono già presenti e consultabili. In caso contrario i comuni seguiranno le attuali regole
