### ISSUE TITLE
PROBLEMATICHE STATISTICHE

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1340]
Buongiorno,

mi riallaccio alla risposta al quesito #1332 relativo alle statistiche Istat e a quello che a suo tempo avevo rivolto sulla data perfezionamento pratica #1086 indicato come evoluzione, con il quale chiedevo come si poteva comunincare ad ANPR la chiusura del procedimento,cioe' la data di perfezionamento pratica senza la gestione dei procedimenti.

Devo segnalare che, pur a seguito di numerosi quesiti qui rivolti sull'argomento "statistico" e quindi di "date statistiche", non e' ancora chiaro cosa e come va inviato ad ANPR tramite i web service per ottenere delle statistiche mensili corrette.

Il problema di fondo e' che ANPR ha introdotto il ripristino dell'iscrizione APR mentre fino ad ora esisteva per Istat solo il ripristino della cancellazione APR mentre quello dell'iscrizione era un'annullamento che incideva sulle statistiche con pochissimi casi perche' l'iscrizione veniva conteggiata per l'Istat soltanto dopo l'accertamento.

Fino ad oggi formalmente non c'e' stata nessuna comunicazione sul fatto che s' intenda modificare qualcosa sulla compilazione dei modelli D7B rispetto alle ultime indicazioni in merito cioe' a quanto stabilito dalla circ. Istat n.21 del 31/07/2012
"Modalità tecniche relative all’invio all’Istat dei modelli APR.4 tramite Istatel e al riporto del movimento di iscrizione e cancellazione anagrafica nei modelli statistici di calcolo della popolazione a seguito delle innovazioni normative introdotte dal D.L. n. 5 del 2012 convertito in legge n. 35 del 2012" e non e' detto neanche che verra' mai fatta qualche comunicazione ai comuni visto che le statistiche con ANPR sono "passate" ad Istat e quindi non c'e' piu' bisogno di chiarire ai comuni come farle.

Cerco di spiegare i dubbi che ancora permangono con un esempio:

semplifichiamo al massimo facendo finta che tutta l'Italia sia composta soltanto da 2 comuni, A e B ed entrambi siano passati ad ANPR.  Inoltre sempre per esempio, alla fine del 2018 in anagrafe ANPR il comune A ha 50 abitanti ed altrettanto il comune B; ammettiamo inoltre che alla fine dell'anno tutti i procedimenti di iscrizione/cancellazione APR risultino consolidati quindi senza accertamenti ancora da effettuare e che la statistica annuale sia corretta ed allineata con l'anagrafe. Entrambi i comuni non gestiscono i procedimenti anagrafici con ANPR.
In sintesi:

Totale popolazione anagrafica a fine 2018 comune A: 50
Totale popolazione anagrafica a fine 2018 comune B: 50
                                                                                 ---
Totale popolazione anagrafica complessivo Italia:      100 

Totale popolazione statistica a fine 2018 comune A: 50                      P2/P3
Totale popolazione statistica a fine 2018 comune B: 50
                                                                               ---
Totale popolazione stat.Istat a fine 2018 Italia:       100 

Per il 2019 ammettiamo che ci sia un'unica variazione e che un persona  a fine gennaio muti residenza spostandosi dal comune A al comune B con registrazione preliminare in ANPR in gennaio e accertamento e quindi consolidamento della pratica effettuato nel mese di febbraio 2019, quindi data perfezionamento pratica di febbraio 2019.
A fine gennaio nell'anagrafe ANPR risulteranno 49 persone nel comune A e 51 in B.
Se facciamo la statistica D7B in base alle regole attualmente in vigore (vedi sopra circ.21/2012 pag.2) nell'applicativo locale succede che:
il Comune di iscrizione: conteggia l’evento nel mese della data di definizione della pratica (pertanto non quella di prima iscrizione) 
D.7.B punto 5.1 - Iscritti provenienti da altro comune, 
e quindi il comune B nel D7B di 01/2019 non conteggia nulla e rimane a 50 e 
il Comune di cancellazione: conteggia l’evento nel mese della data di cancellazione da APR.D.7.B punto 6.1 – Cancellati per altro comune. e quindi il comune A
a fine gennaio ha nella statistica mensile D7B 49 persone perche' fa -1 per la cancellazione APR.
Dal punto di vista statistico complessivamente in gennaio c'e' solo una cancellazione APR (-1 per mutazione residenza del comune B).
In sintesi:

Totale popolazione anagrafica a fine 01/2019 comune A: 49
Totale popolazione anagrafica a fine 01/2019 comune B: 51
                                                                                      ---
Totale popolazione anagrafica complessivo Italia:           100 

Totale popolazione statistica a fine 01/2019 comune A: 49
Totale popolazione statistica a fine 01/2019 comune B: 50
                                                                                    ---
                                                                                     99

Quindi al 31/01/2019 la popolazione statistica del comune B si discosta da quella anagrafica per 1 unita' e la stessa cosa vale per il totale complessivo.
Il risultato Italia si riallinea a fine febbraio perche' nel D7B di febbraio verra' conteggiata la persona in piu' del comune A perche' la data definizione pratica e' di febbraio. Quindi a fine febbraio avremo:
Totale popolazione anagrafica a fine 02/2019 comune A: 49
Totale popolazione anagrafica a fine 02/2019 comune B: 51
                                                                                      ---
Totale popolazione anagrafica complessivo Italia:           100 

Totale popolazione statistica a fine 02/2019 comune A: 49
Totale popolazione statistica a fine 02/2019 comune B: 51
                                                                                     ---
                                                                                   100

Cosa succede con le statistiche con la nuova gestione ANPR tramite web service?
L'unica operazione che viene effettuata e' in gennaio ed e' la mutazione di residenza che nel momento in cui si comunica ad ANPR non ha ancora la data di perfezionamento pratica perche' quest'ultima avviene in febbraio e pero' in febbraio non esiste un'altra comunicazione da inviare ad ANPR per aggiornare la mutazione con la data di perfezionamento della pratica. 

Quindi in gennaio c'e' questa "iscrizione preliminare" alla quale nel xml per ANPR o non si mette la data di perfezionamento o si mette quella di registrazione della mutazione e' cioe' quella dell'art.5/2012.
Cosa riceve Istat?
nel mese di gennaio ricevera' una notifica con l'operazione effettuata. In teoria se e' presente la data perfezionamento pratica dovrebbe conteggiare il movimento in gennaio, se non c'e' non dovrebbe conteggiare nulla. Questo in base alle regole che si presume siano ancora in vigore. Poi non si sa se ANPR nella notifica all'Istat passa questa data di perfezionamento; non si sa se Istat invece, in mancanza di quella data prende in considerazione altre date come quella dell'operazione.
In ogni caso non c'e' modo, passando per ANPR, di mandare ad Istat in febbraio un'altra notifica dicendogli che il procedimento si e' chiuso in febbraio e quindi quel movimento non andava conteggiato in gennaio ma in febbraio (vedi quesito #1086).

Altrimenti si potrebbe pensare, visto che ANPR ha introdotto il ripristino (che mancava dal punto di vista statistico), dell'iscrizione, che quest'ultima si conteggia subito cioe' nell'esempio si conteggia gia' in gennaio come se fosse definitiva e poi eventualmente in febbraio si fa un ripristino con sottrazione di una unita' nella statistica se l'accertamento va male e quindi la persona ritornerebbe in carico al comune A.
  
Conteggiando gli eventi al "preliminare" i D7B diventerebbero (sempre con accertamento positivo in febbraio):

Totale popolazione anagrafica a fine 01/2019 comune A: 49
Totale popolazione anagrafica a fine 01/2019 comune B: 51
                                                                                      ---
Totale popolazione anagrafica complessivo Italia:           100 

Totale popolazione statistica a fine 01/2019 comune A: 49
Totale popolazione statistica a fine 01/2019 comune B: 51
                                                                                     ---
                                                                                   100

Per febbraio non ci sarebbe nessuna variazione rispetto a gennaio.
Se invece l'accertamento di febbraio fosse negativo ci dovrebbe essere una notifica all'Istat di ripristino con "cancellazione per altri motivi nel D7B" in febbraio e quindi un'operazione di -1 statistica per il comune B e +1 per il comune A e si tornerebbe a A=50 e B=50 di popolazione.

La domanda che ci si pone quindi e': come verranno fatte le statistiche con ANPR? C'e' questo nuovo modo di procedere che supera la Circ.Istat citata sopra?
Se c'e', vale solo per i comuni subentrati? Ma sarebbe valido che qualcuno subentrato  fa le statistiche in una maniera e chi non subentrato in altro modo?
Oppure, le statistiche verranno fatte in questo modo nuovo solo quando tutti i comuni saranno subentrati che avrebbe anche piu' senso perche' ogni persona sarebbe sempre statisticamente "in carico" ad un comune cosi' come avviene anagraficamente?

Anche gestendo i procedimenti ANPR non sembra che cambi molto perche', vengono mandate ad Istat le notifiche quando viene chiuso un procedimento?

L'argomento e' di interesse dei comuni poiche' questi pubblicano anche altre statistiche non Istat su attributi non presenti in ANPR (esempio residenti per circoscrizione, per parrocchia.. oppure anche statistiche pubblicate a livello regionale) che devono dare come totale a fine anno/fine mese sempre il totale della popolazione statistica indicata negli esempi sopra e per ottenerlo nell'applicativo locale bisogna conoscere come e' stato ottenuto il totale mensile/annuale dall'Istat; cioe' le statistiche Istat e quelle locali comunali diverse devono "viaggiare" in parallelo per ottenere gli stessi risultati.

Si chiede di chiarire la problematica.
Ringrazio

Carla Musian
Applicativo Ascotweb

**Comment by rvinzani** [comment]
Come già chiarito dalla mia collega azabatta (#1332), ANPR fornisce ad Istat tutte le tipologie di eventi anagrafici inviati dal comune, incluse le mutazioni di scheda individuale dei cittadini, cambi di residenza, iscrizioni e cancellazioni inviando laddove presente la data di definizione della pratica e le ulteriori informazioni presenti nelle comunicazioni. Istat poi utilizza tali informazioni per calcoli statistici secondo algoritmi a noi non noti che, se di vostro interesse, devono essere richiesti direttamente ad Istat. Il comune è tenuto ad inviare le precedenti comunicazioni ad Istat solo il mese successivo al subentro passato il quale è sollevato da tale incombenza.

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
