### ISSUE TITLE
Impossibile rettifcare la data di iscrizione e la data di residenza

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1341]
Buongiorno dal comune di Scandicci non riusciamo a rettificare la data di residenza ed iscrizione all'interno del ns. comune del cittadino id anpr n. 32986241.

La data deve variare da 02/11/2018 a 20/08/2018.

Errore Anpr Cod: EN415 - Data decorrenza residenza 20-08-2018 minore della data di prima iscrizione del soggetto

Abbiamo la stessa anomalia anche procedendo da webapp.

Quale risulta essere la data di prima iscrizione?

Come di può procedere a rettificarla?

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by frmariani** [comment]
la data di iscrizione può essere modificata soltanto a valle del subentro.
Nel vostro caso,  l'unica soluzione è l'annullamento dell'operazione di Iscrizione per altri motivi (idanpr 36272603); successivamente potrete effettuare una nuova operazione di iscrizione per altri motivi con la corretta data di decorrenza dell'operazione.
