### ISSUE TITLE
Subentro in produzione con ANPR02

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1342]
Buongiorno
Un chiarimento in vista della prossima cessazione della modalità ANPR01.
Inviando il subentro in qualsiasi ambiente, dalla web application, non ho a video la modalità di caricamento (ANPR01 o ANPR02).
Non cambia niente quindi in fase di subentro, perchè non ci sono differenze per il processo di subentro tra ANPR01 e ANPR02? Oppure in questo momento carica il subentro come modalità ANPR01, e prossimamente cambia il processo di caricamento?
Lo chiedo pensando ai prossimi subentri e alla necessità o meno, di prevedere una fase di test.

**Comment by mttfranci** [comment]
Salve,
In breve per quanto riguarda il subentro non cambia niente.

Più in dettaglio il cambio di codice ANPRXX è legato ad un cambio di Major Version del sistema ANPR, come da [Change Management](https://github.com/italia/anpr/blob/master/src/change-management/change-management.md).
Non è però detto che tutte le componenti di ANPR siano influenzate dalla nuova versione. Ad esempio il passaggio da ANPR00 (versione 3) ad ANPR01 (versione 4) ha avuto un impatto anche sul subentro. Invece la versione 5 (ANPR02) non necessità di nessun aggiornamento lato subentro.
Ad esempio invece nella prossima Major Version  (che è stata annunciata solo nella roadmap) è previsto di deprecare il servizio S001 di subentro (avviso #1289). Vale a dire che l'upload dei file di subentro potrà avvenire solo da webapp (ma sarà l'unico impatto, da tenere presente che il servizio S001 ad oggi non è mai stato usato in ambiente di produzione).
