### ISSUE TITLE
[1002] Operazione non effettuabile

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1343]
Buongiorno,
gli operatori hanno iscritto un soggetto da comune non subentrato. Effettuando l'operazione dal nostro applicativo, il servizio 1002 risponde con il seguente errore 
```<errore>
                <codiceErroreAnomalia>999</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-16 11:48:44 , idOperazioneANPR 87274813</testoErroreAnomalia>
            </errore>
```

L'operatore ha effettuato l'iscrizione via Web App ed è andata a buon fine. 
Possiamo sapere cosa si è verificato durante l'iscrizione tramite il nostro applicativo?

Grazie, cordialmente
Chiara Leanza per il Comune di Torino

**Comment by mttfranci** [comment]
Salve, come da voi rilevato anche nella issue #1328, in data 16 Maggio c'è stato un problema generalizzato. Probabilmente la vostra operazione non aveva alcuni errore e se ripetuta sarebbe andata a buon fine anche da gestionale.
Non abbiamo risposto alla issue #1328 perchè è stata chiusa poco dopo da voi (in quanto il problema è stato rilevato e risolto celermente).
