### ISSUE TITLE
Certificato ANPR di matrimonio

### ISSUE THREAD

**Issue by muzzarellicesena** [italia/anpr#1345]
Buongiorno, segnalo che dal Comune di Cesena e' stata effettuata una mutazione tutti i dati di matrimonio (5008) per un cittadino straniero con data evento composta da SOLO ANNO. Abbiamo notato che nel certificato ANPR di matrimonio viene stampata la data 01/01/2018, inoltre tale data viene ritornata nello stesso formato anche nel servizio di consultazione (3002).
Dall'XML inviatovi via mail si evince che il nostro software nei dati di matrimonio ha inviato i seguenti campi:
dataEvento 2018-01-01
senzaGiornoMese 1
Distinti saluti.
Fabrizio Muzzarelli

**Comment by amollicone1982** [comment]
Potete darci almeno un identificativo operazione e ambiente

Grazie

**Comment by amollicone1982** [comment]
Comunque sulle date evento non è pevista la gestione della data composta da SOLO ANNO. Tale gestione è prevista solo per data nascita e data morte
