### ISSUE TITLE
Ripristino iscrizione, ma residenza nel comune attuale

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1346]
Ambiente produzione comune Carre'.

Il comune subentra definitivamente in data 06-02-2019 ed il 26-03-2019 ripristina parzialmente una pratica di iscrizione del 07-01-2019 per il cittadino 39441969 con esito positivo. 
Un mese dopo il cliente ricercando il cittadino vede che in WA risulta cancellato, ma i dati di Residenza non si sono aggiornati.

Per risolvere la situazione viene creata, in data 26-04-2019, un'iscrizione per altri motivi (id 79922696) anche questa ripristinata (id 79923167) con le stesse date della pratica originale, tuttavia non è cambiato nulla: cittadino con cancellazione e Residenza a CARRE' invece di SCHIO comune subentrato.

Vorremmo sapere come mai si è creata questa situazione e come risolvere la problematica visto che il comune di SCHIO non riesce ad iscriverlo.

Grazie.

**Comment by asqueglia** [comment]
Buongiorno,
il comune di Carrè ha correttamente effettuato la cancellazione per ripristino del soggetto (idOperazione 79923167); il comune di Schio ha ricevuto una notifica N014 in data 26-APR-19 che riporta l’identificativo ANPR del cittadino (idSoggetto = 39441969) da utilizzare in fase di nuova iscrizione; l’operazione che il comune di Schio dovrebbe effettuare è una iscrizione altri motivi.
 
Il capitolo 12 delle specifiche di interfaccia, RIPRISTINO POSIZIONE ANAGRAFICA, tratta l’argomento specificando il comportamento da adottare per qualsiasi circostanza.
Nella fattispecie indicata, a seguito di esito negativo dell’accertamento, se la residenza originaria del soggetto è in altro comune, sia che esso sia subentrato che non, è necessario effettuare una cancellazione del soggetto per ripristino posizione anagrafica (servizio “2003 – CancellazioneAltriMotivi”); il comune d’origine, se nel frattempo è subentrato, riceve una notifica N014 (che riporta l’identificativo ANPR del cittadino da utilizzare in fase di nuova iscrizione) e completa il ripristino utilizzando il servizio “1002- IscrizionePerAltriMotivi” con motivo iscrizione “Ripristino posizione precedente” (codice 10); se, invece,  il comune d’origine continua a non essere subentrato, deve inviare a suo carico la comunicazione 4 sul sistema INA-SAIA.
 
Se invece, la residenza originaria del soggetto è nello stesso comune, allora sempre nel caso di accertamento negativo post subentro, è necessario utilizzare la mutazione residenza ante sub (codice 6) come specificato nel paragrafo 12.1.5 ANNULLAMENTO DI UN CAMBIO DI RESIDENZA ALL’INTERNO DELLO STESSO COMUNE.

**Comment by fmbianchi** [comment]
Abbiamo contatto il comune di Carrè che avviserà Schio per effettuare l'iscrizione del cittadino con le specifiche segnalate.
Grazie.
