### ISSUE TITLE
Mancata notifica migrazione in altro comune

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1347]
Ambiente di produzione, comune di Villafranca di Verona

è giunta al comune la notizia che il suo cittadino ID ANPR 42172037 è' migrato a Mantova in data 19/5/2019. Mantova è un comune subentrato.
Non è però stata prodotta alcuna notifica per questo evento.

Altro caso :  il suo cittadino id ANPR 42170365 AIRe è passato nell'aire di altro comune ANPR il 21/5 , ma nessuna notifica è stata prodotta.

In sostanza dal 17/5 ad oggi al comune non è arrivata più alcuna notifica.

Potete indagare per favore ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by fferraguto** [comment]
Salve,
abbiamo provveduto a resettare alcune notifiche andate in errore negli ultimi giorni, tra le quali quella per il soggetto 42172037.
Per il cittadino 42170365 invece non ci risultano operazioni effettuate a parte quella di subentro, dunque non abbiamo notifiche da generare.
Cordiali saluti.
