### ISSUE TITLE
pratica iscrizione anagrafica ID SOGGETTO ANPR 59392077

### ISSUE THREAD

**Issue by rogenoanpr** [italia/anpr#1348]
Buongiorno,
in data 13.05.2019 ho creato una pratica di iscrizione anagrafica n. 33 con ID- 86280382 , con decorrenza 11.05.2019, sbagliando il nome del comune di iscrizione.
Ho effettuato una operazione di rettifica dati subentro  in data 13.05.2019 con ID-86312445, pensando di correggere il Comune di iscrizione. 
 Come da accordi con la nostra software:
- abbiamo effettuato una cancellazione per altri motivi, pratica n.27 in data 25.05.2019 ID - 89714745;
- abbiamo creato una nuova iscrizione per immigrazione con il Comune di iscrizione corretto, pratica n.36 senza ID - IN QUANTO LA PROCEDURA HA DATO UN ERRORE : " data decorrenza 11.05.2019 minore della data decorrenza 13.05.2019 dell'ultimo stato dell'individuo ID individuo    4424331".
Si chiede cortesemente di MODIFICARE DATI DI RETTIFICA DATI SUBENTRO, DECORRENZA DA 13.05.2019 A 11.05.2019, per procedere all'iscrizione corretta.
grazie.

.

**Comment by rvinzani** [comment]
Non è possibile sbagliare il comune di iscrizione in quanto è possibile iscrivere cittadini solo nel proprio comune. L'operazione di rettifica consente di correggere esclusivamente il motivo di iscrizione ed eventualmente il comune di provenienza.

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue facendo riferimento a questa stessa
