### ISSUE TITLE
[5008] - Richiesta chiarimenti per risposta EN413

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1349]
Buongiorno,
un operatore del Comune di Torino, in ambiente di produzione, ha provato ad effettuare una mutazione quando il soggetto non era ancora di competenza di Torino. L'errore restituito, però, risulta il seguente:

```
            <errore>
                <codiceErroreAnomalia>EN413</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Il soggetto risulta cancellato</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-04-20 10:59:17 , idOperazioneANPR 76504531</testoErroreAnomalia>
            </errore>
```
Possiamo chiedervi il motivo di questa risposta? Ci aspettavamo un KO, ma non questa motivazione.

Grazie, cordialmente
Chiara Leanza per il Comune di Torino

**Comment by asqueglia** [comment]
Buongiorno, stiamo valutando la segnalazione per rendere più dettagliati gli esiti restituiti. Le faremo sapere quanto prima.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo valutato la segnalazione e provvederemo a rendere gli esiti restituiti più dettagliati. La fix sarà rilasciata con la patch 5.4.4, prima negli ambienti di test e successivamente in produzione;  gli aggiornamenti saranno consultabili nel changelog.

**Comment by chiaralea** [comment]
Vi ringraziamo per la collaborazione, provvederemo ad avvisare gli operatori.
Cordialmente,
Chiara Leanza per il Comune di Torino
