### ISSUE TITLE
Nuovo Sindaco

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1350]
La tornata elettorale di ieri porterà una grande quantità di nuovi Sindaci.
E' possibile avere una descrizione sintetica dei passaggi da compiere con la WA per registrare il "cambio di Sindaco"?
Grazie.
Filipazzi - Maggioli

**Comment by cmigliardi** [comment]
L’ALS ha un ruolo fondamentale perché deve gestire i profili/utente nonché le SC ad essi associate.

In particolare a valle delle Elezioni di domenica 26, laddove si è verificato un cambio del Sindaco, l’ALS ha facoltà di gestire tale situazione.

Se l’utenza è già stata censita, può attribuire il profilo di «Sindaco o Commissario».

Se invece si tratta di registrare una nuova utenza, da «Gestione  Utenze» prima occorre  eliminare la scheda del Sindaco uscente (il sistema provvederà automaticamente a disabilitare la SC) e poi inserire i dati del nuovo Sindaco richiedendo la Smart Card.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
