### ISSUE TITLE
Mancata notifica migrazione in altro comune [rif issue 1347]

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1351]
continuo la discussione della issue #1347 che è stata chiusa prima che potessi rispondere.

La notifica del soggetto id ANPR 42172037 è ora correttamente presente.
Per l'altro soggetto invece ci era stato comunicato un errato id ANPR, il soggetto cui realmente manca la notifica di trasferimento nell'AIRE di altro comune subentrato è il 42170369.

Potete verificare ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by fferraguto** [comment]
Salve,
abbiamo provveduto alla generazione della notifica.
Dovreste trovarla.
Saluti.

**Comment by busaster** [comment]
Grazie.
A cosa sono dovute queste mancate notifiche ? Il problema comincia a preoccupare noi e in nostri clienti

**Comment by fferraguto** [comment]
In questi casi si è verificato un problema di sistema che ha determinato lo scarto delle notifiche.
Stiamo ottimizzando il processo per un recupero più rapido delle notifiche.
A presto.
