### ISSUE TITLE
pratica di iscrizione anagrafica ID soggetto ANPR 59392077

### ISSUE THREAD

**Issue by rogenoanpr** [italia/anpr#1352]
Buongiorno,
in data 13.05.2019 ho creato una pratica di iscrizione anagrafica n. 33 con ID- 86280382 , con decorrenza 11.05.2019, sbagliando il nome del comune di PROVENIENZA.
Ho effettuato una operazione di rettifica dati subentro in data 13.05.2019 con ID-86312445, pensando di correggere il Comune di PROVENIENZA.
Come da accordi con la nostra software:

abbiamo effettuato una cancellazione per altri motivi, pratica n.27 in data 25.05.2019 ID - 89714745;
abbiamo creato una nuova iscrizione per immigrazione con il Comune di PROVENIENZA corretto, pratica n.36 senza ID - IN QUANTO LA PROCEDURA HA DATO UN ERRORE : " data decorrenza 11.05.2019 minore della data decorrenza 13.05.2019 dell'ultimo stato dell'individuo ID individuo 4424331".
Si chiede cortesemente di MODIFICARE DATI DI RETTIFICA DATI SUBENTRO, DECORRENZA DA 13.05.2019 A 11.05.2019, per procedere all'iscrizione corretta.
grazie.

..

**Comment by frmariani** [comment]
Buongiorno,
come premessa vorrei sottolineare che noi non possiamo in alcun modo modificare i dati presenti in ANPR, pertanto la sua richiesta di modifica dei dati, non potrà essere presa in considerazione; Le assicuro comunque, che farò del mio meglio per aiutarla a risolvere il problema. 
La rettifica effettuata il 13/05/2019, ha effettivamente modificato il Comune di provenienza: da Monguzzo a Merone, pertanto la successiva cancellazione del cittadino poteva essere evitata;
Credo che la re-iscrizione del soggetto venga bloccata dal vostro gestionale, infatti non trovo nessuna iscrizione con errori da parte del vostro comune; 
per favore riprovi e appunti i codici di errore rilevati; all'interno dell'errore EN527 troverà l'idanpr dell'operazione fallita.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
