### ISSUE TITLE
[5008] Mutazione Lista Elettorale - Errore: EN074

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1353]
ambiente di PRODUZIONE - comune di CARLOFORTE (111010)

inviamo comunicazione 5008 per mutazione della listaElettorale.
il ws risponde con questo errore:
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN074</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Incongruenza dati anagrafici: il codice ISTAT del comune competente per il soggetto non coincide con quello specificato nella richiesta</testoErroreAnomalia>
  </errore>
  <errore>
    <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-28 09:57:57 , idOperazioneANPR 90377004</testoErroreAnomalia>
  </errore>
</listaErrori>
```

è già capitato in passato che il messaggio relativo comune di competenza fosse un'anomalia o comunque non congruente rispetto al reale problema che blocca la comunicazione.
immagino anche in questo caso

come sbloccare?
grazie

Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Buonasera,
abbiamo ravvisato una piccola anomalia nell'operazione di annullamento dell'operazione di modifica della residenza; a questo punto riteniamo che il problema sia risolto definitivamente.
Per favore riprovi l'operazione di mutazione lista elettorale e mi faccia sapere.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by AMonopoliADS** [comment]
abbiamo provato questa mattina, e confermo che la mutazione è andata a buon fine.
grazie
