### ISSUE TITLE
Tabella comuni italiani: data istituzione provincia di Trento

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1354]
Buongiorno,

ci e' stato segnalato che nella tabella ANPR dei comuni italiani come data d'istituzione della provincia di Trento, nella costruzione dei periodi storici dei comuni di questa provincia, viene indicata la data 04/02/1923 mentre risulta da fonte Istat il 14/02/1923 coerentemente con l'entrata in vigore della Gazzetta Ufficiale n.24 del 30/01/1923.
Si fa riferimento al Regio decreto n.93 del 21/01/1923 presente in questa gazzetta.

Si veda come esempio il comune di Spormaggiore per il quale vengono riportati i seguenti periodi:
16/10/1920	04/02/1923	802477	I924	SPORMAGGIORE
05/02/1923	29/10/1928	022180	I924	SPORMAGGIORE
30/10/1928	06/02/1930	022180	I924	SPORMAGGIORE
07/02/1930	08/07/1947	022180	I924	SPOR
09/07/1947	31/12/9999	022180	I924	SPORMAGGIORE

Il primo periodo risulterebbe invece chiuso il 13/02/1923 ed il secondo aperto il 14/02/1923.
Si chiede un chiarimento
Distinti saluti e grazie

Carla Musian
Applicativo Ascotweb

**Comment by MassimoSchiappa** [comment]
Salve,
l'archivio storico dei comuni istat online conferma quanto da voi indicato. Poiché però  l'indicazione corrente delle date in questione nella tabella comuni di ANPR proviene anch'essa da Istat, chiederemo ad Istat la conferma del dato pubblicato online e in caso di conferma provvederemo alla correzione. In tutti i casi segnaleremo in questa sede l'esito della verifica e l'eventuale conseguente azione intrapresa.
Cordiali saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
Istat ha confermato il dato pubblicato online e di conseguenza appena possibile provvederemo alle correzioni relative.
Cordiali saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
nella prossima tabella dei comuni ANPR che verrà pubblicata, i dati indicati saranno corretti.
La issue viene pertanto chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa.
Cordiali saluti.
