### ISSUE TITLE
Errore EAV51 - EN527  - inscrizione apr cittadino straniero

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1355]
Salve,
abbiamo provato a inscrivaere un cittadino stradniero (proveniente dall'egitto) in anpr.
Quendo viene effettuata l'iscrizione in anpr il sistema produce i seguenti errori.
In effetti facendo un controllo in AE il soggetto sembra avere due codici fiscali associati, tuttavia, visto che si tratta di una nuova iscrizione di un soggetto proveniente dall'estero la consultazione in ANPR non produce alcun risultato.

I codici di errire riportati all'atto dell'iscrizione sono i seguenti:

Errore	EAV51	Più codici fiscali individuati in AT 	
Errore	EN527	Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-28 10:09:32

Riuscireste a fornirci assistenza?
Grazie
Comune Nichelino
Rosario Salone

**Comment by asqueglia** [comment]
Buongiorno, potrebbe gentilmente indicarci l'idOperazione contenuta nel messaggio di errore EN527 per consentirci le verifiche del caso ? grazie mille

**Comment by asqueglia** [comment]
Se l'operazione a cui vi riferite è la 90384716 (la data e l'ora indicata corrispondono), abbiamo verificato che state tentando di iscrivere un soggetto con un CF esistente in AE ma con dati anagrafici differenti. Nello specifico il cognome da voi indicato contiene una lettera in più. Se consultate su punto fisco il CF che avete trasmesso potete verificare. Per iscrivere un soggetto richiedendo la validazione del CF ad AE è necessario comunicare gli stessi dati anagrafici registrati in AE; successivamente è possibile procedere ad una risoluzione disallineamenti nel caso in cui sia necessario effettuare una mutazione anagrafica (ad esempio del cognome) eventualmente con collegamento CF.

**Comment by Nichelino** [comment]
Sì era corretto.
Chiedo un ulteriore cosa.
Abbiamo iscritto in ANPR il soggetto con gli stessi dati anagrafici presenti in AE.
Abbiamo provato a fare una mutazione tutti i dati con cambio del cognome del soggetto (quello corretto è quello nostro che abbiamo estratto dal passaporto)

Il cambio di cognome genera un nuovo codice fiscale per la cittadina in questo caso , nel dettaglio dell'operazione di mutazione, è necessario fare una "richiesta di attribuzione CF" o "Nessuna operazione"?

Grazie

**Comment by asqueglia** [comment]
Qualora si renda necessario modificare uno o più dei 5 dati anagrafici che concorrono al calcolo del codice fiscale, è necessario effettuare una mutazione dati anagrafici dal proprio gestionale con richiesta validazione CF senza trasmettere il CF.

Agenzia delle Entrate stabilisce se assegnare o meno un nuovo CF e nel caso in cui ne venga attribuito uno nuovo lo restituisce nella risposta dopo averlo collegato al precedente.

Per la risoluzione delle anomalie riscontrate sul CF si rimanda al documento seguente (cap. 4)

•	Appendice - Validazione del codice fiscale e dei dati anagrafici e risoluzione disallineamenti con l’Agenzia delle Entrate - pdf 

disponibile al link https://www.anpr.interno.it/portale/documentazione-tecnica

Nel caso specifico, dovreste provare a trasmettere una richiesta di variazione anagrafica (servizio 5008 tipo mutazione 1) senza trasmettere il CF e con richiesta validazione (gestioneCF =0 oppure assente).

Dal sito WEB ANPR, area ‘Registrazione’, menu ‘Mutazione tutti i dati’, tipo mutazione ‘dati anagrafici’. 
Nella gestione CF lasciare vuoto, rimuovere il CF  prima di confermare l’operazione.
Il sistema provvederà ad aggiornare ANPR, allineerà AE e renderà valido e marcato il CF.

**Comment by Nichelino** [comment]
Grazie e chiudo il ticket
