### ISSUE TITLE
[6001-presubentro] Anteprima anche con Emissione=2 

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1356]
Vorrei segnalare un comportamento anomalo del servizio 6001 in ambiente di pre-subentro (Bistagno AL). Anche se viene richiesto il certificato (emissione=2) il sistema rilascia sempre il pdf con la scritta FAC-SIMILE dell'anteprima. Se potete controllare l'ultima richiesta corrisponde a IdOperazioneANPR=12886160 (ma ce ne sono anche altre nei minuti precedenti). 
Grazie

**Comment by rnapoli1983** [comment]
Buongiorno in realtà non è un comportamento anomalo.

Mi spiego.

E' stato deciso che negli ambienti, non di PRODUZIONE, un certificato anagrafico emesso debba riportare il watermark "FAC-SIMILE" per renderlo non assimilabile ad un certificato anagrafico ufficiale emesso da ANPR con il rischio di utilizzi impropri.

Nella modalità "ANTEPRIMA", implementata nel servizio dal valore emissione=3, il watermark presenta il testo "ANTEPRIMA".

Rimango a disposizione per ulteriori chiarimenti.

Cordiali saluti

**Comment by Eduardo1977** [comment]
Ho verificato le due modalità "FAC-SIMILE"/"ANTEPRIMA".  Ora capisco e sono d'accordo con la modifica che avete deciso. Grazie. Buon lavoro
