### ISSUE TITLE
Download dati ANPR del comune

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1357]
Venerdì 24/05 il comune con codice istat 050010 ha chiesto con web app lo scarico dei dati ANPR da produzione.
Ha chiesto successivamente informazioni sullo stato della richiesta all'assistenza ANPR, gli hanno detto che è pronta e che può scaricarla con il servizio 7002, o in alternativa chiedere di riceverla nella PEC.
Vorrei dei chiarimenti per favore sul procedimento di richiesta / notifica / scarico.
Si può scaricare il file dalla WA? ho cercato ma senza risultati.
Esiste una documentazione?

C'è un aspetto che merita particolare attenzione, quando il comune chiede lo scarico si trova in uno dei due scenari previsti: 1) ha perduto i dati locali oppure 2) cambia fornitore. Si trova quindi in una condizione di emergenza o di eccezionalità che richiede interventi straordinari che comportano: fermo del sistema, sospensione del servizio al pubblico, organizzazione delle attività interne all'ente e del supporto della sw house.
La pianificazione di queste cose richiede di conoscere per tempo la data di disponibilità del file di scarico, evito di descrivere i disguidi conseguenti ad un ritardo perché sono facilmente immaginabili.
Sottolineo la necessità di pianificare l'intervento e quindi di conoscere la data e l'ora in cui lo scarico sarà disponibile.
C'è già una logica su cui fare affidamento? si potrebbe definire che lo scarico sia disponibile 24 ore dopo la richiesta, oppure 48 o altro intervallo che si riterrà conveniente; la data e l'ora di scarico del file potrebbero essere un parametro della richiesta; come si vuole, basta che Sogei scelga un metodo che dia al comune la certezza temporale del percorso.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
La funzionalità è nella fase di tuning finale.
La richiesta da voi inserita è stata elaborata ed era disponibile circa 14 ore dopo.
In generale ci aspettiamo che le richieste per comuni fino a 200.000 abitanti siano pronti entro 24 ore.
Quelle per comuni più grandi entro 48 ore.
Il file sarà a breve scaricabile anche dal sito web di ANPR
Chiudo la issue. Nel caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue facendo riferimento a questa stessa
