### ISSUE TITLE
EC031 Il codice dello stato estero di nascita 253 non è congruente con la descrizione REPUBBLICA DI MACEDONIA DEL NORD

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#1358]
Buonasera,
sono Arianna Nozzoli del Comune di Prato passato in ANPR a dicembre 2018. Abbiamo necessità di variare lo stato civile di un cittadino AIRE  a seguito di matrimonio con una cittadina nata nella Repubblica di Macedonia del Nord. Il programma ci risponde con l'errore nel titolo. La Repubblica di Macedonia ha cambiato nome in Repubblica di Macedonia del Nord. Nelle nostre tabelle abbiamo cessato il vecchio stato e inserito il nuovo con gli stessi codici del vecchio. IdOperazioneANPR 91872729
Grazie
Arianna Nozzoli

**Comment by ncapozzi** [comment]
Buonasera,
al momento l'archivio stati esteri di ANPR non prevede lo storico e pertanto non abbiamo ancora recepito la modifica della denominazione della REPUBBLICA DI MACEDONIA. Nell'attesa degli interventi che dovremo prevedere dovete ancora attenervi alla tabella pubblicata.
N. Capozzi

**Comment by ncapozzi** [comment]
Buongiorno,
la tabella degli stati esteri è stata aggiornata come da avviso #1790
