### ISSUE TITLE
[5008] tipoMutazione '03': Annullamento Carta Identità

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1359]
rif. issue #1307 

ho l'impressione che il problema non sia stato risolto.
ambiente di TEST - comune di FAENZA (039010) - idOperazioneComune 2019200070

la comunicazione 5008 va a buon fine ma in interrogazione (ws3002) la dataAnnullamento non risulta valorizzata

**Comment by rvinzani** [comment]
L'annullamento della carta di identità allo stato attuale è previsto solo dalla web app di ANPR. In effetti era presente il problema che impostando la data di annullamento dalla Web App questa non era visibile nell'interrogazione. Questo è stato l'intervento.  Non avevo compreso il problema. L'annullamento della CIE poi non può essere effettuato poichè tale informazioni ci pervengono direttamente dal sistema CIE on Line.
Si chiude la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue facendo riferimento a questa.
