### ISSUE TITLE
WebApp Registrazione Iscrizione per nascita Atto di nascita obbligatorio 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#136]
Il pannello Atto di nascita deve essere obbligatorio per evitare che l'inserimento non venga effettuato. (es RCCTNA17D60L219J )

Grazie

**Comment by gcarbonin** [comment]
Lo era. L'obbligatorieta' è stata eliminata in quanto ci sono casi di cittadini italiani in cui l'atto di nascita non esiste al momento dell'iscrizione

**Comment by annamariaGillone** [comment]
L'atto di nascita non deve essere obbligatorio nel caso di iscrizione per altri motivi: il cittadino può non essere a conoscenza del proprio atto di nascita.
Nel caso di iscrizione per nascita, invece, non è possibile effettuare una registrazione per nascita senza avere redatto il relativo atto.

**Comment by gcarbonin** [comment]
Per gli italiani nati all'estero si; c'è un anno di tempo.

**Comment by annamariaGillone** [comment]
Può essere obbligatorio almeno per i neonati italiani nati in Italia? Tenuto conto che sono il maggior numero dei casi?

**Comment by gcarbonin** [comment]
Manteniamo come miglioramento
