### ISSUE TITLE
[5012] Errore EN077 per annullare 5005

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1360]
Buongiorno,
in ambiente di produzione vorremmo annullare una mutazione di residenza relativa ad un soggetto che raggiunge una famiglia.
Sono state annullate tutte le operazioni successive al 5005, ma al momento dell'annullamento di questo, il sistema restituisce il seguente errore: 
```
<listaErrori>
            <errore>
                <codiceErroreAnomalia>EN077</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-23 11:16:49 , idOperazioneANPR 89152271</testoErroreAnomalia>
            </errore>
        </listaErrori>
```
Abbiamo effettuato dei controlli sia tramite la WebApp sia tramite i nostri sistemi e non riusciamo ad intercettare l'operazione che sta dando problemi. Di seguito vi riportiamo una breve ricostruzione dei servizi che sono partiti con i relativi ID (partendo dal basso):
```
5012	KO	2019-05-23 11:29:00.162	89161820  ----> ultimo tentativo dell'utente
5012	KO	2019-05-23 11:21:51.926	89156206  ----> secondo tentativo dell'utente
5012	KO	2019-05-23 11:16:48.964	89152271  ----> dovrebbe annullare 5005
5012	OK	2019-05-23 11:16:47.912	89152259  ----> annulla 5001
5012	OK	2019-05-23 11:16:46.993	89152248  ----> annulla 5008
5008	OK	2019-05-17 10:10:03.907	87569720
5001	OK	2019-05-17 10:09:57.919	87568955
5005	OK	2019-05-17 10:09:55.728	87568926	
```
Abbiamo anche controllato che non ci fossero operazioni in sospeso per i due soggetti, ma non ne abbiamo trovate.

Vi forniamo infine gli ID ANPR dei soggetti
Soggetto che effettua il raggiungimento: 23556835
Soggetto che viene raggiunto: 28408472

Cordialmente,
Chiara Leanza per il Comune di Torino

**Comment by fferraguto** [comment]
Buongiorno,
l'operazione che dovrebbe bloccare l'annullamento è quella con ID ANPR 87629097 che ha variato la residenza della famiglia di provenienza del soggetto segnalato (ID SOGGETTO ANPR 23556835).
Nel caso si volesse procedere all'annullamento di questo ulteriore cambio di residenza, sarà necessario 
annullare altre operazioni sui soggetti facenti parte della famiglia di provenienza (operazioni di modifica dell'identificativo comunale)
In sintesi, per ottenere il risultato desiderato dovrebbe essere sufficiente annullare nell'ordine le operazioni:
87629233 - 5008
87629224 - 5008
87629097 - 5001
87568926 - 5005
Fatemi sapere se va tutto bene.
A presto

**Comment by chiaralea** [comment]
Buongiorno,

il comune ha riprovato ed ora effettivamente è riuscito a revocare l'intera pratica.
Vi ringraziamo per l'indagine.

Cordialmente,
Chiara Leanza per il Comune di Torino
