### ISSUE TITLE
[7002] Documentazione/Specifiche

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1361]
Buongiorno,
vorrei chiedere, gentilmente, se esistono documenti/specifiche che spiegano più in dettaglio il funzionamento del nuovo servizio di download 7002. In particolare, i wsdl/xsd sono gli stessi del 7001 che si trovano nel pacchetto "SPECIFICHE_DI_INTERFACCIA_XSD_03052019" ?  E quale sarebbe il namespace da inserire nel messaggio soap "<ns2:Richiesta7002 xmlns= ???"  
Grazie

**Comment by mttfranci** [comment]
Salve,
In sintesi il servizio 7001 inizialmente conteneva una sola operazione (la 7001 scarico tabelle appunto).
Poi abbiamo deciso di aggiungere le operazione :
7002 - download file
7003 - elenco versioni

Per non modificare endpoint e namespsace dei client già implementati per l'operazione 7001 la nomenclatura ha mantenuto 7001 per : 
endpoint : https://${URL_AMBIENTE}/ANPR7001ServizioScaricoTabelle/AnprService7001
namepsace : http://sogei.it/ANPR/7001AnprService

Questo è stato fatto per fare in modo che chi non aveva necessità di usare i nuovi servizi poteva semplicemente ignorarli e continuare ad usare l'operazione 7001 nella vecchia maniera.

Quindi potete tranquillamente assumere che il wsdl, endpoint e url del 7001 siano in realtà quelli di tutta la famiglia 700X.

Ci rendiamo conto che questo può creare un pò di confusione, ma abbiamo preferito privilegiare la retrocompatibilità dei servizi (come sempre facciamo quando possibile).

Siamo a disposizione per qualsiasi chiarimento.

Cordiali saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Effettivamente, l'unica spiegazione era quella di mantenere la retrocompatibilità. Grazie per i chiarimenti. Buona giornata

**Comment by mttfranci** [comment]
Prego.
Buona giornata anche a voi.

**Comment by Eduardo1977** [comment]
Gentilmente, la request dovrebbe essere così?
  
&lt;ns2:Richiesta7001 xmlns:ns2="http://sogei.it/ANPR/7001AnprService"&gt;
&lt;testataRichiesta&gt;
...
&lt;operazioneRichiesta&gt;7002&lt;/operazioneRichiesta&gt;
...
&lt;/testataRichiesta&gt;
&lt;datiRichiesta&gt;
&lt;identificativoFile&gt;.....&lt;/identificativoFile&gt;
&lt;/datiRichiesta&gt;
&lt;/ns2:Richiesta7001&gt;

**Comment by mttfranci** [comment]
Salve, il nome dell'elemento base della richiesta è Richiesta7002  : 

Ecco una richiesta di esempio : 

`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:Richiesta7002 xmlns:ns2="http://sogei.it/ANPR/7001scaricoTabelle">
      <testataRichiesta>
        <idOperazioneComune>0</idOperazioneComune>
        <codMittente>999999</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>7002</operazioneRichiesta>
        <dataOraRichiesta>2019-04-26T10:10:49.0900476</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>TEST</tipoInvio>
      </testataRichiesta>
      <datiRichiesta>
        <idOperazioneANPR>1234</idOperazioneANPR>
      </datiRichiesta>
    </ns2:Richiesta7002>
  </soapenv:Body>
</soapenv:Envelope>`

Saluti

Assistenza ANPR
