### ISSUE TITLE
Comuni in provincia di Latina

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1362]
I comuni in provincia di Latina presentano record validi per pochi giorni e non rispondenti alla storia dei cambiamenti: ad ed esempio per Latina i record con ID 22784 e 22785 sembrano un controsenso perché rappresentando Littoria in provincia di Latina (idprovincia=59) quando Littoria e Latina sono lo stesso comune e capoluogo di provincia. Questa variazioni non sono presenti nei dati ISTAT.

ID | DATAISTITUZIONE | DATACESSAZIONE | DENOMINAZIONE_IT | IDPROVINCIA | SIGLAPROVINCIA
---|-----------------|----------------|------------------|-------------|---------------
16244 | 06/11/1932 | 25/10/1934 | LITTORIA | 58 | RM
22784 | 26/10/1934 | 17/12/1934 | LITTORIA | 59 | LT
13098 | 18/12/1934 | 01/05/1935 | LITTORIA | 111 | LT
16245 | 02/05/1935 | 08/04/1945 | LITTORIA | 111 | LT
22785 | 09/04/1945 | 23/04/1945 | LITTORIA | 59 | LT
4850 | 24/04/1945 | 31/12/9999 | LATINA | 59 | LT

**Comment by MassimoSchiappa** [comment]
Salve, 
in effetti nel sito online dello storico dei comuni di ISTAT(sistat) per Latina/Littoria compaiono una serie di cambiamenti che non causano una mutazione dei dati identificativi di rilievo per ANPR del comune (acquisizioni di territorio senza variazione del codice catastale, della provincia, del codice ISTAT). Inoltre e in particolare i record da lei indicati contengono anche il palese errore da lei segnalato.  Appena possibile provvederemo a correggere.
Grazie della segnalazione.
Cordiali saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
entro la fine della prossima settimana sarà disponibile in ambiente di produzione la correzione dei dati indicati. La issue viene pertanto chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa.
Cordiali saluti.
