### ISSUE TITLE
Provincia errata di alcuni comuni

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1363]
Nella tabella sottostante riporto i valori corretti di provincia/regione per alcuni comuni, come risulta dai dati ISTAT.

ID | IDREGIONE | IDPROVINCIA | SIGLAPROVINCIA
---|-----------|-------------|---------------
632 | 02 | 7 | AO
15631 | 02 | 7 | AO
15636 | 02 | 7 | AO
15532 | 02 | 7 | AO
15226 | 02 | 7 | AO
16627 | 02 | 7 | AO
16426 | 02 | 7 | AO
19219 | 02 | 7 | AO
21305 | 02 | 7 | AO
18054 | 02 | 7 | AO
19054 | 02 | 7 | AO
20405 | 02 | 7 | AO
20422 | 02 | 7 | AO
18862 | 02 | 7 | AO
20690 | 02 | 7 | AO
20886 | 02 | 7 | AO
10804 | 02 | 7 | AO
17314 | 04 | 22 | TN
21653 | 04 | 22 | TN
19319 | 04 | 22 | TN
21836 | 04 | 22 | TN
 8984 | 15 | 61 | CE
10977 | 15 | 61 | CE
16341 | 15 | 63 | NA
21407 | 15 | 63 | NA
 2620 | 16 | 75 | LE
 3665 | 12 | 58 | RM
20988 | 20 | 95 | OR

**Comment by MassimoSchiappa** [comment]
Salve,
grazie della segnalazione, provvederemo alla correzione appena possibile.
Cordiali saluti.

**Comment by dedabob** [comment]
Grazie per aver preso in carico la segnalazione. Avrei identificato altri possibili errori di provincia:

ID | IDREGIONE | IDPROVINCIA | SIGLAPROVINCIA
---|-----------|-------------|---------------
17582 | 04 | 22 | TN
21667 | 04 | 22 | TN
21707 | 04 | 22 | TN
4527  | 04 | 22 | TN
21731 | 04 | 22 | TN
21732 | 04 | 22 | TN
21800 | 04 | 22 | TN
3470  | 04 | 22 | TN
15513 | 12 | 58 | RM
20266 | 12 | 58 | RM
8074  | 15 | 61 | CE

**Comment by MassimoSchiappa** [comment]
Salve,
grazie a voi per la segnalazione, entro la fine della prossima settimana sarà disponibile in ambiente di produzione la correzione. La issue viene pertanto chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa.
Cordiali saluti.
