### ISSUE TITLE
Prove fallite di rigetto rimpatrio a cavallo del subentro, il problema persiste

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1364]
continuo la discussione della issue #1292 che è stata chiusa.
Siamo in Ambiente di test.

Il test di oggi è questo : la persone ID ANPR 9457098 è subentrata come APR ma la pratica di rimpatrio era ancora in accertamento. Dopo il subentro l'accertamento fallisce e si deve rigettare le pratica.
Come da istruzioni si è proceduto alla cancellazione per ripristino posizione precedente (ID op ANPR 19741672) che è terminata con successo.
Poi si è tentato di iscrivere in ANPR in AIRE con il servizio A002 con le date di decorrenza reali della residenza AIRE del soggetto ma l'operazione (ID ANPR 19741673) ha dato errore EN237 come il test fatto con la issue 1292.

Il problema dunque non mi sembra risolto come affermato..

Gianrico Busa
Maggioli Spa

**Comment by rvinzani** [comment]
Potete riprovare per favore?

**Comment by busaster** [comment]
analizzando il soggetto campione abbiamo visto che c'era una discrepanza tra la data di residenza cui lo si voleva re-iscrivere e la data di decorrenza istituzione della famiglia in cui andava iscritto, discrepanza creata da altri vecchi test. Abbiamo dunque provato con altro soggetto pulito e la procedura si è conclusa con successo.

Grazie
