### ISSUE TITLE
EN069 - EN527 Problema con cambio nome cittadino  

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1365]
Salve
abbiamo il seguente problema.
Dobbiamo mutare il nome di un nostro residente ma il sistema ci da il seguente errore:

1 Errore Anpr Cod: EN069 - Incongruenza dati anagrafici: il cognome del soggetto non coincide con quello specificato nella richiesta 
 2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-05-30 14:13:33 , idOperazioneANPR 92173363 

Prima di questa operazione dato che i dati tra anpr e AE erano disallineati abbiamo allineato questo soggetto confermando il dato di AE, poi, dato che il nome in AE era errato (il dato differisce rispetto alla realtà di un semplice apice) abbiamo provato a inviare una "mutazione tutti i dati" -> mutazione di nome.
Quando abbiamo provato a confermare il nome di sopra l'applicativo ha dato gli errori di sopra.

Riuscite a darci una mano?

Grazie

**Comment by asqueglia** [comment]
Buongiorno, in merito alla segnalazione in oggetto si comunica che in generale qualora si renda necessario validare un CF oppure modificare uno o più dei 5 dati anagrafici che concorrono al calcolo del codice fiscale, è necessario effettuare una mutazione dati anagrafici dal proprio gestionale con richiesta validazione CF senza trasmettere il CF.

Agenzia delle Entrate stabilisce se assegnare o meno un nuovo CF e nel caso in cui ne venga attribuito uno nuovo lo restituisce nella risposta dopo averlo collegato al precedente.

Per la risoluzione delle anomalie riscontrate sul CF si rimanda al documento seguente (cap. 4)

•	Appendice - Validazione del codice fiscale e dei dati anagrafici e risoluzione disallineamenti con l’Agenzia delle Entrate - pdf 

disponibile al link https://www.anpr.interno.it/portale/documentazione-tecnica

Nel caso specifico, avete trasmesso in generalità per ricerca il cognome già modificato (senza l'accento) anziché quello esistente, da ciò l'errore; probabilmente il gestionale compone male la richiesta. 
Dovreste provare a trasmettere la richiesta di variazione anagrafica (servizio 5008 tipo mutazione 1) impostando i dati esistenti nella sezione di ricerca soggetto e quelli modificati nella sezione di modifica, senza trasmettere il CF e con richiesta validazione (gestioneCF =0 oppure assente).

Se il vostro gestionale non lo consente, potete utilizzare il sito WEB ANPR, area ‘Registrazione’, menu ‘Mutazione tutti i dati’, tipo mutazione ‘dati anagrafici’. 
Nella gestione CF lasciare vuoto, rimuovere il CF e modificare il cognome  prima di confermare l’operazione.
Il sistema provvederà ad aggiornare ANPR, allineerà AE e renderà valido e marcato il CF.

**Comment by Nichelino** [comment]
Abbiamo fatto da app anpr. Funzionato, grazie
