### ISSUE TITLE
[4005] Dubbi sul funzionamento

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1366]
Buongiorno,
Ambiente di TEST,
sto provando la chiamata 4005, ho effettuato la Richiesta, ottenendo come id operazione anpr da usare poi per la verifica: 19741160.
Successivamente dopo la prima data disponibilità ho effettuato una verifica stato (codice comune 25595, comune: 004215), ma continua ad arrivarmi il seguente messaggio di errore "La ricerca non produce risultati", la risposta ha id_operazione anpr 19741957.

Potete verificare cosa stia sbagliando? 
Ringrazio anticipatamente.

**Comment by mttfranci** [comment]
In questo caso il messaggio si riferisce al fatto che la richiesta è stata elaborata e non sono state trovate notifiche nel periodo elaborato.

          <statoLavorazione>9</statoLavorazione>
          <periodoRiferimentoRichieste>
            <dataOraIniziale>2019-05-30T00:00:00.000+02:00</dataOraIniziale>
            <dataOraFinale>2019-05-31T08:51:43.436+02:00</dataOraFinale>
          </periodoRiferimentoRichieste>

Provate a chiuedere, ad esempio questo periodo : 

          <statoLavorazione>9</statoLavorazione>
          <periodoRiferimentoRichieste>
            <dataOraIniziale>2019-05-06T00:00:00.000+02:00</dataOraIniziale>
            <dataOraFinale>2019-05-08T00:00:00.000+02:00</dataOraFinale>
          </periodoRiferimentoRichieste>

Siamo a disposizione per ogni ulteriore chiarimento.

Assistenza ANPR
