### ISSUE TITLE
[4005] continuazione issue 1366

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1367]
Continuazione issue #1366  

Scusate ho ancora un dubbio.
Ma quindi per capire l'assenza di notifiche nel periodo richiesto, non devo basarmi su un particolare Stato, ma sul ritorno con errore EN122 (La ricerca non produce risultati)?

Grazie

**Comment by SAlberto** [comment]
Aggiungo ancora una cosa, ho provato come consigliato nell'issue #1366 a interrogare il sistema nel periodo tra il 2019-05-06 e il 2019-05-08.
Richiesta id_comune=25602 (comune 004215), ottengo come risposta due errori:
"Servizio non disponibile" e "Operazione non effettuabile"

**Comment by mttfranci** [comment]
Esatto.
Eventualmente valuteremo se introdurre un altro messaggio per chiarire quando ad esempio sia stata richiesta una operazione non esistente.
Ma il codice EN122 indica effettivamente che la richiesta è elaborata ma per i critieri non sono state trovate operazioni / notifiche.

Saluti

Assistenza ANPR

> Continuazione issue #1366
> 
> Scusate ho ancora un dubbio.
> Ma quindi per capire l'assenza di notifiche nel periodo richiesto, non devo basarmi su un particolare Stato, ma sul ritorno con errore EN122 (La ricerca non produce risultati)?
> 
> Grazie

**Comment by mttfranci** [comment]
In che ambiente?
In generale se la avete disponibile è per noi più comodo avere l'id operazione anpr restituita nella risposta.

> Aggiungo ancora una cosa, ho provato come consigliato nell'issue #1366 a interrogare il sistema nel periodo tra il 2019-05-06 e il 2019-05-08.
> Richiesta id_comune=25602 (comune 004215), ottengo come risposta due errori:
> "Servizio non disponibile" e "Operazione non effettuabile"

**Comment by SAlberto** [comment]
id operazione anpr è tornato '0' purtroppo.
Ambiente Di test, richiesta id_comune=25602 (comune 004215)

**Comment by mttfranci** [comment]
Potreste darci la risposta completa che ottenete dal server.

Apparentemente noi vediamo in uscita ( `<idOperazioneANPR>19742745</idOperazioneANPR>` ): 

`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
      <ns2:rispostaKO>
        <testataRisposta>
          <idOperazioneComune>25602</idOperazioneComune>
          <codMittente>004215</codMittente>
          <codDestinatario>ANPR02</codDestinatario>
          <operazioneRichiesta>4005</operazioneRichiesta>
          <dataOraRichiesta>2019-06-03T09:14:18.407+02:00</dataOraRichiesta>
          <idOperazioneANPR>19742745</idOperazioneANPR>
          <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
          <errore>
            <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>La ricerca non produce risultati</testoErroreAnomalia>
          </errore>
        </listaErrori>
      </ns2:rispostaKO>
    </ns2:Risposta4005>
  </soapenv:Body>
</soapenv:Envelope>`

**Comment by SAlberto** [comment]
> Potreste darci la risposta completa che ottenete dal server.
> 
> Apparentemente noi vediamo in uscita ( `<idOperazioneANPR>19742745</idOperazioneANPR>` ):
> 
> `<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> <soapenv:Header/> <soapenv:Body> <ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione"> <ns2:rispostaKO> <testataRisposta> <idOperazioneComune>25602</idOperazioneComune> <codMittente>004215</codMittente> <codDestinatario>ANPR02</codDestinatario> <operazioneRichiesta>4005</operazioneRichiesta> <dataOraRichiesta>2019-06-03T09:14:18.407+02:00</dataOraRichiesta> <idOperazioneANPR>19742745</idOperazioneANPR> <esitoOperazione>XXXX</esitoOperazione> </testataRisposta> <listaErrori> <errore> <codiceErroreAnomalia>EN122</codiceErroreAnomalia> <tipoErroreAnomalia>E</tipoErroreAnomalia> <testoErroreAnomalia>La ricerca non produce risultati</testoErroreAnomalia> </errore> </listaErrori> </ns2:rispostaKO> </ns2:Risposta4005> </soapenv:Body> </soapenv:Envelope>`

Ora funziona, non so cosa stessi sbagliando, se ricapitasse vi invio la risposta completa.

Grazie

**Comment by mttfranci** [comment]
Ok, noi non abbiamo trovato errori e l'operazione originaria è stata anche elaborata in meno di un secondo. Forse c'è stato un problema di comunicazione di qualche tipo. Se avete altri problemi fateci sapere.

Saluti

Assistenza ANPR
