### ISSUE TITLE
[A002] - Iscrizione AIRE di soggetto irreperibile

### ISSUE THREAD

**Issue by SilVio-G** [italia/anpr#1369]
Ambiente di PRESUBENTRO, Comune di Torino

Effettuando una iscrizione AIRE di un soggetto AIRE Irreperibile (idOperazioneANPR 12911701) riscontriamo sempre l'errore "EAA0A - Errore di sistema"
Potreste darci indicazioni aggiuntive su che tipo di errore si tratta?

Grazie

**Comment by ncapozzi** [comment]
Buonasera,
sembrerebbe un problema di colloquio con i servizi di Agenzia delle Entrate. Potete riprovare per favore?
N. Capozzi

**Comment by SilVio-G** [comment]
Buongiorno,
purtroppo non è stato possibile utilizzare lo stesso soggetto.
Ho effettuato il test con un altro soggetto e il risultato è stato lo stesso.

Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-04 12:41:35 , idOperazioneANPR 12915014

**Comment by ncapozzi** [comment]
Buonasera,
Potete riprovare nuovamente per favore?
N. Capozzi

**Comment by SilVio-G** [comment]
Buongiorno,
ho provato una serie di casi e non si è più verificato il problema.
Ultimo caso provato: <idOperazioneANPR>12935887

Che intervento avete effettuato?

Grazie
Silvio Guala

**Comment by ncapozzi** [comment]
Buongiorno,
c'era un problema tecnico sui servizi del sistema di Agenzia delle Entrate richiamati da ANPR che i nostri colleghi hanno risolto.
N. Capozzi
