### ISSUE TITLE
Nuova tabella codici di errore

### ISSUE THREAD

**Issue by mstagnoli** [italia/anpr#137]
Comune di Codogno - verifica esiti subentro - ambiente di pre-subentro
Buongiorno,
analizzando esiti del subentro del Comune di Codogno abbiamo rilevato l'errore ES127 - La data di decorrenza residenza 2003-06-30 risulta inferiore alla data di prima iscrizione: 2007-03-07, ma non è presente nella tabella degli errori pubblicata fino a oggi. Ho cercato di scaricare la tabella dal sito anpr.interno.it (https://www.anpr.interno.it/portale/webdav/guest/document_library/Specifiche/errori_anpr_20170427.xlsx) ma ritorna l'errore The requested URL /portale/webdav/guest/document_library/Specifiche/errori_anpr_20170427.xlsx was not found on this server.
Ho bisogno di sapere severità dell'errore e note per il subentro (da rimuovere o meno)
Grazie in anticipo per la collaborazione

Monica Stagnoli
A.P. Systems

**Comment by gcarbonin** [comment]
Salve Non trova il file perché era in corso di aggiornamento. L'errore ancora non e' presente (aggiorneremo nei prossimi giorni); e' un'anomalia in quanto è stato indicato che la residenza del soggetto (che dovrebbe essere quella attuale e quindi l'ultima) decorre dal 20 giugno del 2003 mentre la persona e' iscritta per la prima volta nel comune il 7 marzo del 2007.

**Comment by gcarbonin** [comment]
Aggiungo una precisazione: se l'anomalia fosse bloccante, l'intera fornitura sarebbe stata scartata

**Comment by mstagnoli** [comment]
Grazie mille per le precisazioni. Può solo psecificarmi se tale anomalia deve essere rimossa prima del subentro? La ringrazio anticipatamente per il suuporto

**Comment by gcarbonin** [comment]
Le date indicate nel subentro (prima iscrizione decorrenza residenza ultimo aggiornamento della scheda) fanno da guida per le successive variazioni e sono riportate nelle certificazioni. Sarebbe quindi necessario impostarle correttamente.
