### ISSUE TITLE
EAA71 - Errore formale- ISCRIZIONE AIRE A SEGUITO DI TRASCRIZIONE ATTO NASCITA

### ISSUE THREAD

**Issue by MarcellaM** [italia/anpr#1370]
Impossibilitata ad inviare l'operazione con idAnpr 92996378 e id Operazione Comune 1873075 per un'iscrizione per nascita Aire nel nucleo dell'individuo con Identificativo scheda attribuito da ANPR: 34356827 , ricevendo l'errore: Anpr Cod: EAA71 - Errore formale.
Marcella Molinari
Comune di Alessandria

**Comment by ncapozzi** [comment]
Buongiorno,
il bambino viene associato ad una famiglia con residenza avente toponimo numerico = 508. Agenzia delle Entrate non accetta il toponimo numerico ma alfanumerico.
Prima dell'iscrizione, è necessario pertanto effettuare una mutazione famiglia 5001 con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO. 
N. Capozzi
