### ISSUE TITLE
Convenzione ANPR - altre PA

### ISSUE THREAD

**Issue by lellomaverick** [italia/anpr#1371]
Buongiorno,
scrivo per conto di un'agenzia regionale che ha la necessità di stipulare una convenzione con ANPR per poi interrogare i dati in sola lettura, mediante uso di web service. Sul sito di ANPR è specificato che la documentazione tecnica non è ancora disponibile, ma non ho trovato uno schema di convenzione da usare per portarsi avanti con il lavoro dal punto di vista amministrativo.
E' possibile ricevere la documentazione necessaria o se ci sono degli esempi da poter modificare?
@cmigliardi @rvinzani potreste aiutarmi?

Grazie

**Comment by marcocipri** [comment]
Buongiorno,
attualmente il percorso di "stipula delle convenzioni" non è implementato.
Vista la natura dei dati depositati in ANPR la questione è delicata ed è per questo che 
l'adesione alle convenzioni e le sue modalità  è un tema attualmente oggetto di discussione, sia per le norme legate alla privacy che per quelle  legate alle competenze territoriali.
A conclusione di questi colloqui verrà definito ed implementato un sistema centralizzato che risolverà la distribuzione delle adesioni.
Ci rendiamo conto dell'importanza della circolarità dei dati e stiamo accelerando per completare di questo percorso.

**Comment by mpiraz** [comment]
Grazie. Come sistema delle Camere di Commercio abbiamo necessità di beneficiare al più presto del collegamento con ANPR per una serie di verifiche sui dati relativi al Registro delle imprese (dove ad esempio ora gli imprenditori devono denunciare il cambio di residenza quando sarebbe possibile automatizzarlo). Inoltre è di fondamentale importanza disporre del collegamento per la gestione delle sanzioni amministrative. Siamo già tutti dotati di CNS e Spid e spero che questo agevoli la possibilità di disporre al più presto degli schemi di convenzione. E' possibile avere una stima dei tempi per l'attivazione del collegamento ANPR/Altre PP.AA. ? In alternativa dovremo richiedere ai singoli comuni (come in passato). Grazie
