### ISSUE TITLE
Impossibile ripristinare un cittadino

### ISSUE THREAD

**Issue by gdurante72** [italia/anpr#1372]
Buongiorno,
il Comune di Agrigento deve ripristinare la residenza del cittadino ID ANPR 45203125, precedentemente cancellato per il Comune di Bologna che non ha confermato l'iscrizione. 
Tramite le indicazioni fornite dall'operatore (ticket 20157260), il comune avrebbe dovuto effettuare la  re-iscrizione tramite la funzione della web-app "iscrizione per altri motivi".
Avendo provato ad eseguire le indicazioni fornite, l'operazione risulta impossibile in quanto richiamato il cittadino interessato, sia tramite ID ANPR che tramite il codice fiscale, questo non risulta selezionabile:
viene visualizzata la riga con i dati del cittadino, come comune di residenza BOLOGNA ed il campo cancellato valorizzato a SI ma, non viene resa disponibile l'icona della lente d'ingrandimento che consente di selezionare il cittadino per proseguire l'operazione voluta.

Si richiede pertanto come poter sbloccare l'operazione per consentire il ripristino della residenza da parte del Comune di Agrigento.

Saluti
Giovanni Durante
Kibernetes

**Comment by frmariani** [comment]
Nel ticket indicato, si suggerisce di inserire l'idanpr del cittadino all'interno della sezione "Generalità" del soggetto, mentre voi lo inserite nella sezione "Ricerca per identificativo della persona".
al momento, non è ancora disponibile la modalità più veloce di re-iscrizione del soggetto recuperando i dati precedentemente acquisiti, pertanto  per re-iscrivere un cittadino, si deve seguire il seguente percorso:
dalla web app di ANPR
Registrazione>Tipo di operazione: Iscrizione per altri motivi>Iniziativa: Operazione di parte/operazione d'ufficio> CONFERMA > nelle Generalità, inserire tutti i dati del cittadino compreso l'idanpr precedentemente assegnato.

**Comment by gdurante72** [comment]
Problema risolto
Grazie
