### ISSUE TITLE
HONG KONG

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1373]
Buongiorno,
nel nostro comune è iscritto cittadino britannico nato a HONG KONG.
Al momento dell'iscrizione aveva esibito documentazione come HONG KONG - REPUBBLICA POPOLARE CINESE, ora esibisce passaporto britannico come nato a HONG KONG senza riferimento allo stato.
Tenuto conto che Agenzia Entrate riconosce Hong Kong come Stato e rilascia codice fiscale con Z221, su ANPR va gestito come NON ATTRIBUIBILE e descrizione Stato HONG Kong?
Grazie
Anna Maria AIMONE
UPI - Codici fiscali
Comune di Torino

**Comment by ncapozzi** [comment]
Buonasera,
è corretto. Per codice fiscale con  Z221, su ANPR dovete indicare NON ATTRIBUIBILE e descrizione Stato HONG Kong.
N. Capozzi
