### ISSUE TITLE
[INFO] wsdl e xsd Vari Ambienti

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1374]
Buonasera,
volevo chiedere una semplice informazione,
è possibile reperire da qualche parte i WSDL e gli XSD in uso nei vari ambienti?
Ho notato che per il test e il pre-subentro i wsdl e xsd vengono linkati volta per volta nelle varie issues, il che non risulta comodissimo per seguire i tutti i rilasci.

Ringrazio anticipatamente.

**Comment by mttfranci** [comment]
Nel percorso wsdl di questo repository (italia/anpr) verranno pubblicati i WSDL disponibili divisi per ambiente : 

[Branch master per l'ambiente di Produzione](https://github.com/italia/anpr/tree/master/wsdl)

[Branch develop per gli ambienti di Test e Presubentro](https://github.com/italia/anpr/tree/develop/wsdl) 

NOTA: In questo modo e' possibile verificare velocmente le versioni dell'interfaccia rilasciata nei vari 
ambienti e confrontarle in modo semplice anche con i vari client disponibili per GIT.   

Ad oggi tutti gli ambienti sono allineati alla versione pubblicata sul portale (5.4.3)

Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Grazie per la tempestiva soluzione, è davvero molto utile

**Comment by mttfranci** [comment]
Prego.
