### ISSUE TITLE
Nuovo Sindaco - precedente era ALS e ALP

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1375]
Buongiorno,
per il Comune di Bistagno (AL) ci era stato indicato di nominare il Sindaco come ALS e ALP, dato che in piccoli comuni come questo non esiste un CED o una figura interna per svolgere queste funzioni. Cosa occorre fare adesso che è stato nominato un nuovo Sindaco? Grazie @ #1350

**Comment by cmigliardi** [comment]
Buonasera, 
cortesemente mi può contattare la signora Garbarino? ha già i miei riferimenti così al telefono posso dare tutte le indicazioni del caso.  grazie

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by Eduardo1977** [comment]
Buonasera,
ho avvisato la signora Garbarino, credo che la contatterà domani. Grazie

**Comment by cmigliardi** [comment]
va bene.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
