### ISSUE TITLE
Revoca matrimonio 

### ISSUE THREAD

**Issue by AnagrafeSavona** [italia/anpr#1377]
Buongiorno.
Abbiamo ricevuto dal Tribunale un Decreto di annullamento di alcuni matrimoni.
Esempio id cittadino anpr 59315779
Questo cittadino in precedenza era divorziato. Quindi in ANPR risulta ora coniugato dal 2015 secondo matrimonio. 
La nostra soluzione sarebbe quella di revocare il matrimonio ora registrato, e annullato dal Tribunale. Con successiva registrazione caricheremmo il precedente matrimonio, e quindi il precedente divorzio.

Nel fare da web application la registrazione "Eliminazione dati" indicando a video
- data decorrenza 15.10.2018 (precedente al subentro), data sentenza
- tipo scheda “soggetto”
- tipo revoca “matrimonio”
- motivo revoca “revoca”

ci da subito errore “Sezione matrimonio non presente” e ci impedisce di proseguire.
Restiamo in attesa di chiarimenti.

**Comment by asqueglia** [comment]
Buongiorno, confermiamo che il soggetto indicato 59315779, presenta in ANPR un matrimonio in data 2015 registrato da subentro; dovrebbe essere consentito revocarlo con la funzione Eliminazione dati. Potete riprovare inserendo come data decorrenza la data del subentro anziché una precedente ?

**Comment by AnagrafeSavona** [comment]
Grazie, abbiamo fatto come da voi suggerito, e l'operazione è andata a buon fine.

**Comment by asqueglia** [comment]
Perfetto chiudiamo la issue.
