### ISSUE TITLE
[5008] errore in rettifica dati di decesso

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1378]
Ambiente di produzione, comune di Gubbio

con id operazione ANPR 94218631 è stata eseguita una chiamata di tipo 22 per rettificare i dati di decesso di un soggetto.

ANPR ha risposto con un errore EN389 con questa descrizione :
```
La data decorrenza 08-06-2019 dell'operazione non puo' essere inferiore alla data decorrenza ORA-06533: Subscript beyond count
 ORA-06512: at "ANPR.CONTROLLI", line 503
 dell'ultima operazione effettuata sui dati relativi a @
```

Cosa significa ? 

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, sembrerebbe che effettivamente ci sia una combinazione di dati non coerenti che viene gestita male dal sistema.
Per aiutarci a ricostruire la situazione , potete confermarci che il soggetto 30878863 (sui cui state provando ad eseguire la mutazione) sia stato acquisito in fase di subentro e poi ne sia stato registrato il decesso pochi giorni fa con operazione 89417519 e data del decesso nel 2000?
Quindi si tratta di un caso che non doveva proprio essere inviato in fase di subentro giusto?
Grazie in anticipo.

Assistenza ANPR

**Comment by busaster** [comment]
Confermiamo che il soggetto è quello e che è stato caricato come residente al subentro.
Confermiamo anche che il soggetto è stato cancellato per morte, ma l'operatrice ha inserito una data errata  (21/5/2000 invece di 21/05/2019). 
L'operazione oggetto di questa issue era volta a sistemare questa data al valore corretto

**Comment by mttfranci** [comment]
Sicuramente c'è un problema da parte nostra nella gestione del messaggio di errore.
Intanto una piccola premessa, purtroppo in fase di subentro per non bloccare i subentri vengono accettati anche dati che in alcuni casi sono incongruenti tra di loro.
E' il caso del soggetto in questione che risulta iscritto dal 1924 mentre la residenza in cui si trova si è originata nel 2004.
Aver registrato il decesso con data decorrenza 2000 ha creato uno stato incongruente che causa questo messaggio di errore.

Avete modo di provare ad annullare il decesso e ripeterlo con la data corretta?

**Comment by busaster** [comment]
A me pare perfettamente lecito che un soggetto sia iscritto dal 1924 ma che la sua attuale residenza sia valida dal 2004.

**Comment by mttfranci** [comment]
Si in generale è vero, e quando questo avviene a seguito dall'operatività che si sussegue nel tempo non ci sono problemi. Purtroppo in fase di subentro riceviamo una istantanea senza storia.
Il soggetto ha data decorrenza residenza nel 2004.
Risultando adesso cancellato nel 2000, nel 2004 non aveva una residenza valida (a tutti gli effetti è come se fosse stato iscritto nel comune dal 1924 al 2000).
In fase di mutazione della scheda viene verificato che abbia una residenza valida (serve anche a verificare che il comune sia competente, fatto non scontato in ambito ANPR).

Pensate di poter provare la strada alternativa proposta attraverso la combinazione annullamento / ripetizione del 2001?

**Comment by busaster** [comment]
abbiamo provveduto come suggerito.
Grazie
