### ISSUE TITLE
Web App - Istituzione convivenza di fatto

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#138]
Ambiente di test – Data test:27/4/2017
Con operazione ID ANPR n.477425 abbiamo costituito una convivenza di fatto tra i soggetti ID ANPR 927157 e 934352, ipotizzando come “data costituzione convivenza” il giorno 27/04/2017. Il report riporta effettivamente tutti i dati inseriti e il messaggio aveva confermato l'esito OK.
Tuttavia, consultando la scheda dei soggetti, nella sezione “Convivenza di fatto” la data non viene riportata.
Anche tentando una nuova mutazione dati, rieseguita con operazione n. 477433 e reimpostando la data, il dato non è visualizzato sulla consultazione. 

A tendere, è previsto che venga introdotto il certificato di convivenza di fatto?

Grazie, 
Valentina Bocchino - Comune di Torino

**Comment by VBocchinoTO** [comment]
Ad integrazione, ho testato un'altra creazione di convivenza di fatto con operazione n. 477963: in questo caso ho compilato tutti i campi presenti nella sezione "Dati costituzione convivenza" ma, con riferimento alle date, in Consultazione vengono riportate solo: 
-Data costituzione convivenza: 15/04/2017 (avevo indicato 28/04/2017, mentre 15/04/2017 era la data stipula)
-Data notifica: 21/04/2017 
Inoltre non ho potuto allegare il pdf del contratto perchè restituiva il messaggio "Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi". Evitando l'upload, invece, la mutazione è avvenuta con le anomalie di cui sopra.
Grazie, 
Valentina Bocchino

**Comment by gcarbonin** [comment]
Manca una data nell'attuale versione: avvertiamo quando possibile riprovare
L'allegato al momento non è "allegabile".
Esiste un certificato di contratto di convivenza; dobbiamo inserire il link per scegliere questo tipo di certificato; avvertiamo quando possibile stampare il certificato

**Comment by gcarbonin** [comment]
Può riprovare la data e il certificato
