### ISSUE TITLE
CAMBIO SESSO

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#1380]
Buongiorno, devo registrare un cambio sesso di persona residente.
il codice errore che mi dà è:

EAM91</codiceErroreAnomalia>
<testoErroreAnomalia>Richiesta incongruente - soggetto NON marcato ANPR</testoErroreAnomalia>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>

<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-10 13:03:30 , idOperazioneANPR 94545853</testoErroreAnomalia

Dovrei rilasciare la carta d'identità.
Ringrazio in anticipo per una pronta risposta.
Raffaella
Spinea

**Comment by mttfranci** [comment]
Nel caso specifico, dovreste provare a trasmettere una richiesta di variazione anagrafica (servizio 5008 tipo mutazione 1) senza trasmettere il CF e con richiesta validazione (gestioneCF =0 oppure assente).
 
Dal sito WEB ANPR, area ‘Registrazione’, menu ‘Mutazione tutti i dati’, tipo mutazione ‘dati anagrafici’. 
Nella gestione CF lasciare vuoto, rimuovere il CF  prima di confermare l’operazione.
Il sistema provvederà ad aggiornare ANPR, allineerà AE e renderà valido e marcato il CF.

Ecco un esempio : 

`<generalitaDaModificare>
        <generalita xmlns:ns4="http://sogei.it/ANPR/vocabolario5000mutazione" xsi:type="ns4:tipoGeneralita">
          <cognome>COGNOME</cognome>
          <nome>NOME</nome>
          <sesso>F</sesso>
          <dataNascita>1970-01-01</dataNascita>
          <luogoNascita>
            <comune>
              <nomeComune>VENEZIA</nomeComune>
              <codiceIstat>027042</codiceIstat>
              <siglaProvinciaIstat>VE</siglaProvinciaIstat>
            </comune>
          </luogoNascita>
          <idSchedaSoggettoComune>
            <idSchedaSoggettoComuneIstat>123456</idSchedaSoggettoComuneIstat>
            <idSchedaSoggetto>1234</idSchedaSoggetto>
          </idSchedaSoggettoComune>
          <idSchedaSoggettoANPR>12345678</idSchedaSoggettoANPR>
        </generalita>`

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
