### ISSUE TITLE
Interno del civico in certificazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1381]
Il Comune di Brescia mi fa presente che la numerazione interna degli edifici della città comincia da 1 per ogni piano.
Il risultato in certificazione sarebbe ambiguo visto che ANPR certifica l'interno ma non il piano.
Per ovviare al problema vengono in mente due possibilità:
1) rendere opzionale l'output dell'interno nei certificati così da poterlo omettere;
2) aggiungere l'output del piano.
La prima soluzione è preferita.
Si veda anche #1171.
Grazie.

Filipazzi - Maggioli

**Comment by patriziasaggini** [comment]
In base a quanto previsto dal Regolamento Anagrafico e dalla guida elaborata da ISTAT, la numerazione interna non deve essere attribuita per piano, ma consecutivamente tra tutti i piani dell’edificio, in senso orario o antiorario a seconda della struttura delle scale. 
Il documento è disponibile a questo link https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/FabbricatiTerreni/Portale+per+i+Comuni/Servizi+portale+dei+comuni/toponomastica/Informativa+Istat/Istruzioni+ordinamento+ecografico.pdf 

Pertanto il piano non è un elemento costitutivo della numerazione interna.

**Comment by bfilipazzi** [comment]
La situazione esposta è un dato di fatto inerente una popolazione di 190.000 abitanti probabilmente consolidata da decenni, credo che al di là della teoria si debba cercare una soluzione informatica.
E' un problema simile a quello della stampa della frazione già risolto.
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Le istruzioni contenute nel documento Istat citato in questa discussione dicono a pagina 54: "Si fa presente che gli accessi interni e i numeri interni non devono essere registrati nell’indirizzario ma in apposita lista della numerazione interna. ".

Mi fanno osservare che se gli interni sono esclusi dall'indirizzario significa che non costituiscono un elemento dell'indirizzo, e questo fa sorgere il dubbio che sia opportuno stamparli negli indirizzi dei certificati anagrafici. 
Resta il problema del Comune sopra citato che ha bisogno di una soluzione urgente.

Grazie.
Filipazzi - Maggioli.

**Comment by patriziasaggini** [comment]
Purtroppo il documento non tiene conto di ANPR  e dà solo i criteri di gestione e di attribuzione della numerazione;
a mio parere il numero interno è un dato di ANPR, e nessuna norma vieta che sia compreso nella certificazione (le esclusioni sono descritte appositamente nel DPR 223/1989).
Forse l'inserimento del n. interno nel certificato potrebbe essere una scelta del Comune, eventualmente con un parametro da inserire nella certificazione di ANPR.

Riguardo al tema del Comune di Brescia, di cui posso capire la situazione specifica, mi limito solo a fare presente che una banca dati nazionale serve anche a correggere delle situazioni pregresse e indicare una modalità di gestione univoca.

**Comment by AMonopoliADS** [comment]
mi associo alla richiesta di parametrizzare la stampa dell'interno nei certificati in base alla scelta dell'ente.

anche noi abbiamo un cliente con una esigenza analoga e che ha posto la questione per altri canali già da qualche mese ormai.
considerata l'assenza di riscontri, il tema è diventato piuttosto urgente anche per noi.

grazie.
Alessandro Monopoli ADS

**Comment by marcocipri** [comment]
Buongiorno,
abbiamo preso in carico lo sviluppo di questa funzionalità.
Cerchiamo di pubblicarla il prima possibile.
