### ISSUE TITLE
Servizio 1013: invio tagliando motorizzazione vecchio indirizzo

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1382]
Ambiente produzione Comune di Scandiano.

Il 17-04-2019 il comune iscrive con operazione 73778103 la cittadina 32806631 proveniente da Bibbiano, già subentrato; successivamente effettua una 1013 di annullamento, operazione 73882860, e poco dopo effettua nuovamente l'iscrizione, 73890760.
Oggi la cittadina contatta il comune perché le è arrivato il tagliando dalla motorizzazione  con il vecchio indirizzo. Il comune chiama la motorizzazione per avere informazioni, la quale gli risponde che dipende dal servizio 1013.
Abbiamo controllato il servizio, ma non vediamo nulla di anomalo; potete dirci da cosa dipende la problematica.

Grazie

**Comment by azabatta** [comment]
Buonasera, 
tutti e tre gli eventi anagrafici sono stati notificati a MCTC nello stesso ordine in cui sono stati inviati in ANPR: 
-	Evento di mutazione residenza 3778103
-	Evento di annullamento mutazione residenza 73882860
-	Evento di mutazione residenza  73890760

Non abbiamo visibilità delle elaborazioni effettuate a fronte di tali notifiche.

Si riporta di seguito una modalità operativa che il comune può seguire nei casi in cui ci sia un problema con MCTC (es. cittadini con la sola iscrizione preliminare nel sistema INA-SAIA, ossia senza iscrizione definitiva,  e successivo subentro in ANPR con il nuovo indirizzo): 
-	utilizzare il servizio  “Mutazione tutti i dati”  (ws 5008) 
-	nei dati di controllo indicare come sezione da modificare la sezione “Autoveicoli”  (codice mutazione 08)
-	confermare o aggiornare  i dati patente/autoveicoli  (almeno uno dei due deve essere impostato a  “SI”).

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
