### ISSUE TITLE
Domande di varia natura allineamenti ANPR-AE

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1385]
Buongiorno 
volevamo sistemare le anomalie presenti su anpr post subentro in particolare quelle inerenti agli allineamenti ANPR-AE.

Volevamo per cui sapere come sistemare le seguenti tipologie di errore

1 - soggetti non presenti in AE e presenti in ANPR - E' possibile, visto che gli individui hanno codice fiscale inserire quei soggetti non presenti ma residenti in AE? In questo caso qual'è la procedura migliore per l'inserimento degli stessi? Occorre rivolgersi ad AE per fare ciò?

2 - Problemi su residenze - Spesso l'AE ha il dato di iscrizione discordante o residenziale discordante con quello di ANPR, che dal nostro punto di vista rappresenta quello corretto. E' possibile abiliatare la conferma del dato di ANPR invece che soltanto quello di AE così da allineare anche numeri civici, vie, date, ecc ecc? 

Grazie

**Comment by azabatta** [comment]
Buonasera, si risponde di seguito  in maniera generica con riferimento alle situazioni più ricorrenti, casi specifici vanno esaminati in dettaglio rivolgendosi al numero verde Sogei 800863116. 

1)	Se un cittadino ha un codice fiscale  e non è presente in AE significa che il CF è stato calcolato ma non assegnato da AE e pertanto non risulterà validato.  AE è l’unico ente che attribuisce un CF e ne garantisce l’autenticità, solo i CF che riportano la dicitura “Validato: SI” sono emessi da AE.
Per risolvere casi particolari di cittadini con CF calcolato (ad esempio i cittadini iscritti all’AIRE a volte non hanno un CF assegnato da AE)  è possibile utilizzare la funzionalità di “Mutazione tutti i dati”, richiesta di mutazione dei dati anagrafici/codice fiscale” (senza indicare il CF eventualmente calcolato) e richiedere l’attribuzione del CF. Con questa operazione AE restituisce il CF assegnato ed il dato è riportato in ANPR. 

2)	Se il dato anagrafico è discordante presumibilmente il cittadino non  ha il CF validato e non risulta “marcato” in AE (ossia AE non è a conoscenza del fatto che il cittadino è iscritto in un comune ANPR). In tal caso con la funzionalità  “Risoluzione disallineamenti con Agenzia Entrate” – sezione “Utilità e notifiche “ del sito web di ANPR,  è possibile confermare i dati di ANPR. L’operazione comporterà l’aggiornamento dei dati di AE. Utilizzando tale funzionalità AE riceverà anche l’indirizzo di ANPR.
Se il cittadino ha CF validato/marcato dovrebbe avere lo stesso indirizzo in AE acquisito con: 
-	Subentro
-	Iscrizione
-	Mutazione residenza
Questi tre eventi comportano l’allineamento (subentro) o la notifica (iscrizione, mutazione residenza) dell’indirizzo in AE. Se tale allineamento non si è verificato è necessario aprire una segnalazione al numero verde Sogei 800863116.


Si riporta di seguito il link al documentale di ANPR dove è possibile scaricare la guida "APPENDICE VALIDAZIONE DEL CODICE FISCALE E DEI DATI ANAGRAFICI E RISOLUZIONE DEI DISALLINEAMENTI CON L'AGENZIA DELLE ENTRATE":

https://www.anpr.interno.it/portale/documentazione-tecnica

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
