### ISSUE TITLE
Notifica N000notificheINPS in scarico 4005

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1386]
Ambiente di produzione, comune di Bollate

E' arrivato l'esito di una richiesta 4005 (si tratta della id anpr 93799200) che però manda in errore l'unmarshalling  degli XML in Java, in quanto contiene una notifica N031 ma con un namespace diverso da quello delle specifiche (parla di INPS...) .
In allegato XML che riceviamo.

Da dove arriva questa notifica ?
Io non credo debba essere presente nel nostro scarico.

Grazie

[notifica_inaspettata.xml.zip](https://github.com/italia/anpr/files/3286135/notifica_inaspettata.xml.zip)

**Comment by mttfranci** [comment]
Salve, in effetti c'era un bug nella generazione notifiche quando non veniva specificato il tipo di notifica.
Abbiamo rigenerato singolarmente l'operazione e le prossime generazioni dovrebbero essere corrette.
Saluti

Assistenza ANPR
