### ISSUE TITLE
Problemi con risoluzione CF AE 

### ISSUE THREAD

**Issue by ComuneVelletri** [italia/anpr#1387]
Id Scheda Sogg Anpr59396618 
per errore è stato inserita la data di nascita con anno 1918 e stesso mese e giorno.
In AE l'anagrafica è corretta, ma è impossibile effettuare il disallineamento in quanto si riceve

Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12) 

Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12) 

si richiede sblocco urgente affinché possa poi avvisare la mia software house per allineare i dati del Comune

**Comment by rvinzani** [comment]
Effettuate ora una mutazione tutti i dati, tipo mutazione 1 -dati anagrafici e CF. Impostate a 0/null  il campo gestione codice fiscale, modificate la data di nascita e confermate l'operazione.
Chiudo la issue. In caso fosse necessario apritene una nuova facendo riferimento a questa stessa
