### ISSUE TITLE
[5008] Errore EN146 - variazione stato civile per cittadino AIRE

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1388]
Ambiente produzione Comune di Fonzaso

Cittadina AIRE 49280425, 
in data 14/06/2019 è stata comunicata la variazione di stato civile da "coniugata" a "vedova", id operazione 95755127, anpr risponde con l'errore:
EN146 - Se codice fiscale assente può essere richiesta solo un attribuzione di CF o omocodice
Ma trattandosi di un cittadino aire il codice fiscale non dovrebbe essere preso in considerazione.
Abbiamo controllato il servizio, ma non vediamo nulla di anomalo; potete dirci da cosa dipende la problematica.

Grazie

**Comment by ncapozzi** [comment]
Buonasera,
quando un cittadino non è in possesso del CF e non lo deve avere dovete impostare espressamente nei dati di controllo "Iscrizione/Modifica senza validazione CF" (gestioneCF = 3)
N. Capozzi
