### ISSUE TITLE
Mancata ricezione notifica di emigrazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1389]
Ambiente di Produzione
Comune di Casale Monferrato
La persona con idANPR 27874030 è emigrata da Casale Monferrato a Milano il 29/04/2019.
Casale Monferrato non trova la notifica, nemmeno nella WA.
Grazie.
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Questa mia segnalazione è forse sfuggita?
Grazie.
Filipazzi - Maggioli

**Comment by fferraguto** [comment]
Salve,
la notifica risulta correttamente generata sui nostri sistemi in data 15/05/2019
Potreste cortesemente comunicarci un identificativo di operazione per la quale vi sareste aspettati di trovarla?
Grazie.

**Comment by bfilipazzi** [comment]
Il cliente non l'ha trovata nella WA in data 14 giugno, giorno in cui ho aperto la segnalazione.
Vedo oggi che è stata generata il 15 maggio per cui deve essere sfuggita o, più probabilmente, tenuto conto che la decorrenza è del 29 aprile il cliente non si è spinto a cercarla fino a metà maggio.
Grazie. 
Filipazzi - Maggioli
