### ISSUE TITLE
ANPR: Ripristino posizione anagrafica

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#139]
Buongiorno,
relativamente al documento MI-04-AN-0D per il ripristino della posizione anagrafica, volevamo sapere se le indicazioni contenute in tale proposta sono operative o sono ancora solo una proposta.
Nel caso in cui siano operative non abbiamo trovato le notifiche N014 e N015 in esso citate.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Stiamo eseguendo i test. la avvertiamo quando può riprovare

**Comment by gcarbonin** [comment]
Può eseguire i test
