### ISSUE TITLE
[5008] Errore AEE95 mutazione luogo nascita

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1390]
Ambiente produzione Comune di Riva del Garda.

Salve 
Variando il luogo nascita del cittadino idANPR 46291477, 
ANPR risponde:
"Errore AEE95 - Operazione non effettuabile"
id operazione ANPR 66522066
Abbiamo controllato il servizio, ma non vediamo nulla di anomalo; potete dirci da cosa dipende la problematica.

Grazie

**Comment by lorbia** [comment]
In verifica presso AE.

**Comment by lorbia** [comment]
Verificato allineamento con AE. 
E' possibile effettuare nuovamente la stessa mutazione che adesso non dovrebbe dare alcun problema.
Saluti.
