### ISSUE TITLE
[4005/3003] Estrazione CF inseriti tramite WebApp

### ISSUE THREAD

**Issue by RaffaelloZago** [italia/anpr#1392]
Buongiorno,

vorrei cortesemente una conferma su quali servizi devono essere utilizzati per avere tutti i CF che sono stati gestiti tramite Webapp ad una certa data.

Se non erro, dovrei utilizzare il servizio **4005** per effettuare una prenotazione inserendo il periodo richiesto e richiamare successivamente lo stesso servizio con il codice prenotazione per ottenere gli Id Operazione Anpr. Con tali codici posso utilizzare il servizio **3003** mettendo come operazione richiesta ‘**NRIS**’.

E’ corretto ?

Grazie.

_Raffaello Zago
Comune di Bologna_

**Comment by azabatta** [comment]
Buonasera, 
la richiesta di una lista di operazioni può essere effettuata solo tramite il ws 4005. Una volta elaborata la richiesta, lo stesso ws può essere utilizzato per il download.
Per avere informazioni relative agli eventi anagrafici comunicati tramite la web app di ANPR deve essere specificato come valore del campo “operazioneRichiesta” il codice ‘NRIS’ ed in aggiunta un periodo di riferimento.
Nella richiesta è possibile specificare se si desiderano in risposta solo gli identificativi delle operazioni richieste, gli identificativi e gli xml delle risposte, gli identificativi e gli xml delle richieste,  oppure tutto (identificativi, richieste e risposte) valorizzando opportunamente il parametro “dettaglioDati”.

Il ws 3003 è utilizzabile solo per richieste singole relative ad un identificativo specifico oppure con riferimento agli eventi che hanno riguardato un determinato cittadino presente in ANPR. 

Per un maggior dettaglio si rinvia alla documentazione di riferimento reperibile sul documentale di ANPR (https://www.anpr.interno.it/portale/documentazione-tecnica). La documentazione in formato excel è disponibile alla voce:  Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica, nella cartella relativa alle “Estrazioni”. La documentazione WSDL/XSD è disponibile alla voce Tracciati XSD e WSDL, famiglia di servizi “wsdl4000”.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
