### ISSUE TITLE
Iscrizione AIRE - errore su scioglimento unione civile

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1394]
Buon giorno,
il comune di Colonnella sta eseguendo in ambiente di produzione una iscrizione AIRE per espatrio, utilizzando il ws A002, di un individuo con stato civile 8 ("_Stato libero a seguito di scioglimento dell'unione_"). Tra i dati dell'unione civile abbiamo pertanto caricato anche lo scioglimento, indicando il motivo '3' e gli estremi della sentenza di scioglimento, ma otteniamo in risposta l'errore 'EN301' : '_Se sulla richiesta XML e' presente scioglimentoUnione, deve essere presente anche attoUnione_'; da specifiche però i blocchi 'Sentenza' e 'DatiEvento' sono da inserire in alternativa esclusiva e come detto abbiamo caricato i dati completi della sentenza.
Potete verificare se si tratta di un refuso, o nel caso segnalarci se si tratta di un nostro errore nella request?
L'operazione è stata riprodotta in ambiente PRE_SUB oggi 18/06/2019, con Id operazione comune 0670192019061844, il comune come detto è Colonnella.
Grazie, cordiali saluti.
Giuseppe Mucciarelli
TINN srl.

**Comment by ncapozzi** [comment]
Buongiorno,
l'attoUnione cui si riferisce il msg è quello di costituzione dell'unione civile che volete sciogliere, è presente nel tipoUnioneCivile. Potete riprovare?

**Comment by ncapozzi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
