### ISSUE TITLE
Dati obbligatori unione civile - richiesta chiarimenti issue #1394

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1395]
Salve, 
in riferimento all'issue #1394  in oggetto, confermiamo che la registrazione dell'iscrizione AIRE è andata a buon fine dopo l'inserimento delle informazioni dell'atto di costituzione dell'unione civile. Si fa presente però che da specifiche (vedi _unioneCivile.xlsx_) il blocco _AttoUnione_ è indicato come non obbligatorio per il tipo _tipoUnioneCivile_; deve essere quindi considerato obbligatorio solo in caso scioglimento dell'unione civile e quindi di popolamento di _scioglimentoUnione_, oppure va inserito sempre?
Grazie,
cordiali saluti

**Comment by ncapozzi** [comment]
Non va inserito sempre., ma se il dato è conosciuto conviene inserirlo
N. Capozzi
