### ISSUE TITLE
Data e ora disponibilità servizio 4005 - verificaStato 

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1396]
Salve,
Abbiamo eseguito una richiesta 4005 in modalità elaborazione di richieste 5008.
Ambiente Test - Id Sede:  888120
IdOperazioneANPR: 2132045
Se proviamo a fare verificaStato prima della data disponibilità, questo valore è sempre uguale, invece dopo la dataDisponibilità il valore viene rimandato con un ora.
(un simile comportamento nel issue #1294)

Grazie in anticipo,
Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by gife67** [comment]
Buonasera,
cortesemente potete verificare se ora risulta elaborato.
Grazie

**Comment by AlbanaCelepija** [comment]
Si,adesso risulta elaborato.
Grazie
