### ISSUE TITLE
[INFO] Scarico file Richiesta e Risposta

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1397]
Buongiorno,
avremmo la necessità di poter scaricare, dato un certo Id_OperazioneAnpr, il file di richiesta e la relativa risposta.
E' possibile farlo?
Come ci suggerite di procedere e con quali servizi?

Ringrazio anticipatamente,
Saluti.

**Comment by mttfranci** [comment]
Potete usare il servizio 4005.

Fate anche riferimento alla documentazione sul portale ANPR, alla [nota sul 4005](https://github.com/italia/anpr/blob/note_ws/src/note/ws/4000/nota_4005_richieste_asincrone.md) e alla issue #1161.

Saluti 

Assistenza ANPR

**Comment by SAlberto** [comment]
Il servizio 4005 non soddisfa la nostra esigenza, in quanto asincrono, ci servirebbe avere subito la risposta.
Abbiamo visto che con la 3003 (richiesta singola) passando l'id_operazioneANPR riusciamo ad ottenere l'xml di risposta in modo sincrono, esiste un qualcosa per avere in modo sincrono anche la richiesta?

Grazie

**Comment by mttfranci** [comment]
no. solo il servizio 4005 restituisce anche la richiesta.
