### ISSUE TITLE
EN237 - EN395 - EN507 - EN527 - Su iscrizione apr

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1398]
Buongiorno,
allora in fase di subentro in anpr era sfuggita un'immigrazione nel nostro comune di una cittadina.

Non avendo avuto modo di inviarla abbiamo provata ad inviarla qualche giorno fa.

Abbiamo provato a inviare la variazione in data 3/1/2019 (data di decorrenza esatta) ma ha dato un errore allora abbiamo inviato l'immigrazione con data di decorrenza 7/6/2019 e chiaramente l'ha presa.
Abbiamo poi annullato tale variazione dato che la nostra necessità è di fare in modo che la data di residenza, secondo le attauali disposizioni di legge, sia associabile al 3/1/2019.

Come possiamo riuscire a fare ciò?

Vi invio i codici degli errori e le operazioni id anpr associate.

Saluti

Errore | EN237 | La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata | Id Famiglia/Convivenza ANPR: 26593359 Id Famiglia/Convivenza Comune:

Errore | EN395 | per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza | Id Famiglia/Convivenza ANPR: 26593359 Id Famiglia/Convivenza Comune:

Errore | EN507 | La  data decorrenza della nuova residenza non puo' essere antecedente alla  decorrenza residenza dei soggetti appartenenti alla famiglia | Id Famiglia/Convivenza ANPR: 26593359 Id Famiglia/Convivenza Comune:

Errore | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-20 10:08:32 , idOperazioneANPR 97204599

**Comment by rvinzani** [comment]
Salve, mi serve di conoscere l'idANPR del soggetto in questione e un suo recapito nel caso fosse necessario contattarlo. Se vuole mi indichi il suo indirizzo di email

**Comment by Nichelino** [comment]
Salve sarebbe più semplice per voi con il codice fiscale (che vi permetterbbe di vedere la storia delle variazioni)

In ogni caso potete far riferimento a questo id 97204599 2019-06-20 10:08:32 oppure vuole i precedenti?

In ogni caso le lascio il recapito telefonico dell'ufficio  011/6819541
e l'indirizzo mail rosario.salone@comune.nichelino.to.it

**Comment by rvinzani** [comment]
Esiste una mutazione di residenza effettuata da Torino al 22/01/2019. 
Chiudo la issue. In caso di necessità aprirne una nuova facendo riferimento a questa stessa.

**Comment by Nichelino** [comment]
Salve abbiamo fatto una mutazione al 23/01/2019 che è andata a buon fine.
Saluti

**Comment by Nichelino** [comment]
Chiudo il ticket
