### ISSUE TITLE
[3003] Elenco Operazioni: comunicazioni 5014

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1399]
ambiente di PRODUZIONE - comune di CORSICO (015093)

soggetto con idANPR 43904186

stamattina sono state inviate - con successo - 3 comunicazioni del tipo 5014
nell'ordine:
idOperazioneComune 2019010292 - ws 5014 x rettifica dataIngressoFamiglia
idOperazioneComune 2019010293 - ws 5014 x rettifica dataPrimaIscrizioneComune
idOperazioneComune 2019010297 - ws 5014 x rettifica datiIscrizione

richiedendo l'elenco operazioni eseguite sul soggetto (ws 3003 - idOperazioneComune 2019306761), di tutte le comunicazioni di cui sopra compare solo ultima

potete verificare?

grazie.
Alessandro Monopoli ADS

**Comment by fferraguto** [comment]
Salve,
non ci risultano operazioni con identificativo comunale 2019306761, potreste cortesemente verificare l'id segnalato?
Grazie.

**Comment by AMonopoliADS** [comment]
l'idOperazioneComune è corretto.
si tratta di comunicazione 3003, con questa request:
```
<tnsb:Richiesta3003 xmlns:tns="http://sogei.it/ANPR/tipoDato" xmlns:tnsa="http://sogei.it/ANPR/vocabolario3000consultazione" xmlns:tnsb="http://sogei.it/ANPR/3000consultazione" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<testataRichiesta>
<idOperazioneComune>2019306761</idOperazioneComune>
<codMittente>015093</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>3003</operazioneRichiesta>
<dataOraRichiesta>2019-06-20T11:33:30</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<tipoInvio>PROD</tipoInvio>
<nomeApplicativo>DE4GSD</nomeApplicativo>
<versioneApplicativo>V4.5.3 - V7.0.b del 03 05 2019</versioneApplicativo>
<fornitoreApplicativo>ADS - Gruppo Finmatica - Bologna</fornitoreApplicativo>
</testataRichiesta>
<parametriRicercaSoggetto>
<datiSoggetto>
<idSchedaSoggettoANPR>43904186</idSchedaSoggettoANPR>
</datiSoggetto>
</parametriRicercaSoggetto>
</tnsb:Richiesta3003>
```

**Comment by amollicone1982** [comment]
Può riprovare l'operazione adesso

**Comment by AMonopoliADS** [comment]
adesso l'elenco operazioni risponde con tutte le 5014 che sono state inviate.
grazie
