### ISSUE TITLE
Errore EAV02 su mutazione tutti i dati

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#14]
Per fare delle rettifiche, ad esempio sui dati anagrafici, abbiamo provato a usare il servizio “mutazione tutti i dati”, rettifica, flaggando la parte relativa alle generalità della persona. Una volta arrivati in fondo e confermata la modifica, dopo aver fatto salva e chiudi ci compare la scritta: errore formale codice  EAV02. Questo su qualsiasi soggetto.

**Comment by gcarbonin** [comment]
E' un errore segnalato dall'Agenzia delle Entrate.  Il problema può essere risolto esaminando un caso specifico (fornire nella richiesta l'ambiente nel quale si esegue il test e l'identificativo operazione ANPR)

**Comment by VBocchinoTO** [comment]
Abbiamo simulato un'iscrizione per altri motivi aprendo il procedimento amministrativo n. 3019 con ID operazione 432264. Abbiamo scelto ingresso in famiglia nuova e indicato che non è richiesta alcuna operazione in Agenzia Entrate. Tuttavia, pur avendo compilato tutti i campi obbligatori (e anche di più), il sistema continua a restituire l'errore formale EAV02 al momento del salvataggio.
Al momento, l'operazione è sospesa con ID 941.
Quale potrebbe essere il problema?

Data del test : 8/3/2017

Ambiente TEST -  TORINO

**Comment by gcarbonin** [comment]
Può riprovare con la stessa richiesta delle 14.23.
Preciserei soltanto che quando si specifica "<gestioneCF>0</gestioneCF>"  non si intende "ignora il codice fiscale": è precisato a pag 180 delle specifiche ANPR.
Quando si vuole procedere anche in  presenza di errori  bloccanti segnalati dall'Agenzia, come avviene di frequente in ambiente di test-comuni dove ci sono pochi codici fiscali, occorre specificare "<gestioneCF>3</gestioneCF>"

**Comment by gcarbonin** [comment]
Una precisazione: l'errore EAV02 era dovuto ad una configurazione non ai dati trasmessi dal comune
