### ISSUE TITLE
Web App - Certificabilità di interdetto

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#140]
Tentando l'emissione di un certificato (in ambiente di test) relativo al soggetto ID ANPR 980929, interdetto sottoposto a tutela, non è consentita l'emissione del certificato con codice errore EN047.
Esattamente come evidenziato nel caso di soggetto non iscrivibile (#132 e #131), sarebbe più corretto gestire la condizione come un attributo diverso dal concetto di certificabilità in quanto la presenza di interdizione/inabilitazione/amministrazione di sostegno/tutela impatta sulla capacità del soggetto interessato di rendere dichiarazioni. Dovrebbe quindi essere un'informazione a supporto dell'ufficiale d'anagrafe in fase di accoglimento dell'istanza senza inibire le mutazioni.
Nel caso sia già stata valutata l'evoluzione del sistema in tal senso, chiediamo se è stata ipotizzata una gestione anche tramite WS e con quali tempistiche.
Grazie, 
Valentina Bocchino - Comune di Torino

**Comment by rvinzani** [comment]
Chiudo la issue in quanto è già stato evidenziato che l'informazione di interdizione è fuori ambito ANPR. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che facci riferimento a questa stessa
