### ISSUE TITLE
[4005] risposta 5008 in richiesta notifiche 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1400]
Ambiente di produzione, comune di Gorgonzola.

Abbiamo chiamato il servizio 4005 per avere tutte le notifiche da prendere in carico in un periodo usando il filtro "stato lavorazione" con valore 9 (id operazione ANPR 97178860).
L'elenco di risposta però contiene anche risposte a delle operazioni di tipo 5008, che non ci aspettavamo e che fanno fallire il nostro processo di gestione notifiche.

Come mai sono presenti tali operazioni ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
forse si tratta di una operazione da web app?

in tal caso avete anche le nris.

**Comment by busaster** [comment]
E' effettivamente una operazione da webapp. 
Alle NRIS non avevo pensato, molto probabilmente si tratta di quelle.
Grazie.
