### ISSUE TITLE
Codice ISTAT di alcuni comuni errato

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1401]
Alcuni comuni che appartenevano alla provincia di Trento prima di passare a quella di Bolzano hanno un codice ISTAT diverso da quello presente in SISTAT. Riporto il codice corretto:

ID    | CODISTAT
------|---------
12292 | 022980
21822 | 022627
21825 | 022490
21848 | 022951
21887 | 022970
21895 | 022973
21900 | 022980
21990 | 022448
22279 | 022465
22415 | 022649
22418 | 022650
22423 | 022652
22428 | 022660

**Comment by FilippoPapi** [comment]
Grazie della segnalazione verificheremo con Istat

**Comment by MassimoSchiappa** [comment]
Abbiamo richiesto conferma ad Istat, e appena ricevuta la risposta provvederemo eventualmente ad aggiornare la tabella dei comuni.
Grazie e saluti.
