### ISSUE TITLE
Data cessazione/istituzione di alcuni comuni non coerente

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1402]
La data di cessazione/istituzione di alcuni comuni non è coerente con quella degli altri comuni coinvolti dallo stesso provvedimento. Riporto le correzioni per allineare agli altri comuni con stesso provvedimento.

#### RD del 21 gennaio 1923, n. 93
ID    | DATACESSAZIONE
------|---------------
5007  | 13/02/1923
15355 | 13/02/1923
17838 | 13/02/1923

ID    | DATAISTUTUZIONE
------|----------------
3099  | 14/02/1923
16247 | 14/02/1923
17839 | 14/02/1923

#### RD 6 dicembre 1923, n. 2769
ID   | DATACESSAZIONE
-----|---------------
3558 | 21/12/1923
3559 | 21/12/1923
6580 | 21/12/1923
9174 | 21/12/1923

ID     | DATAISTUTUZIONE
-------|----------------
20611  | 22/12/1923

**Comment by FilippoPapi** [comment]
Grazie della segnalazione verificheremo con Istat

**Comment by mttfranci** [comment]
Correggeremo le date appena possibile, ma che alcune date da loro indicate non corrispondono a quanto pubblicato da Istat sul sito dello storico dei comuni.

**Comment by dedabob** [comment]
Le date ISTAT in alcuni casi non sono corrette (segnalazione #1185), però eventuali correzioni dovrebbero essere applicate a tutti i comuni coinvolti dallo stesso provedimento.

Per il RD del 21 gennaio 1923, n. 93 la coerenza si era persa con l'aggiornamento del 04/06/2019.

Per il RD 6 dicembre 1923, n. 2769 la coerenza si era persa presumibilmente con l'aggiornamento del 17/06/2016.
