### ISSUE TITLE
[5012] annullamento mutazione residenza - EN077

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1403]
Ambiente di produzione , comune di Monsummano Terme.

In data 1/4/19 il soggetto ID ANPR 43289033 cambia indirizzo uscendo da una famgilia di due componenti in cui era PADRE andando a formare nuova famiglia.
Viene esegita una operazione 5005 che si completa con successo (ID ANPR 60834496).
La pratica rimane in accertamento.

In data 12/06/2019 l'altro componente della famiglia (id ANPR 43287090) migra in altro comune subentrato.

Oggi 21/06/2019 la pratica del primo soggetto deve essere rigettata in quanto gli accertamenti sono falliti.

La richiesta di annullamento (ID ANPR 97434374) però va in errore : 

 EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

Come mai ?

Busa Gianrico
Maggioli Spa

**Comment by frmariani** [comment]
La mutazione di residenza che vuole annullare, dovrebbe ricollocare il cittadino in una famiglia che in quel Comune non esiste più, essendosi spostato anche il secondo ed ultimo componente della famiglia stessa;
ad oggi, l'annullamento dell'operazione idanpr 60834496 non è un'operazione effettuabile;

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
