### ISSUE TITLE
Denominazioni precedenti di alcuni comuni

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1404]
Alcune denominazioni precedenti discordano dai dati ISTAT. Riporto le correzioni alle discordanze identificate:

ID | DENOMINAZIONE_IT | DENOMTRASLITTERATA
------|------------------|-------------------
12988 | TUORO | TUORO
15528 | CARAMANICO | CARAMANICO
17996 | MATHI | MATHI
5478 | MATI | MATI
18087 | TERRANOVA PAUSANIA | TERRANOVA PAUSANIA
18094 | OLGIATE MOLGORA | OLGIATE MOLGORA
15632 | CAMPITELLO | CAMPITELLO
22707 | CAMPITELLO | CAMPITELLO
19498 | MERCATO SAN SEVERINO | MERCATO SAN SEVERINO
22068 | CHALLANT SAINT ANSELME | CHALLANT SAINT ANSELME
22066 | CHALLANT SAINT ANSELME | CHALLANT SAINT ANSELME
22067 | CHALLANT SAINT ANSELME | CHALLANT SAINT ANSELME
22071 | CHALLANT SAINT VICTOR  | CHALLANT SAINT VICTOR
22069 | CHALLANT SAINT VICTOR  | CHALLANT SAINT VICTOR
22070 | CHALLANT SAINT VICTOR  | CHALLANT SAINT VICTOR

Inoltre nelle denominazioni del comune di **Aveligna** (ID 21847 e 21848) risultano spazi alla fine.

**Comment by MassimoSchiappa** [comment]
Salve,
stiamo provvedendo a verificare quanto segnalato ed eventualmente verrà di conseguenza aggiornata la tabella anpr dei comuni.
Cordiali saluti.
