### ISSUE TITLE
3 notifiche N015 per stesso cittadino

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1407]
Buongiorno
Abbiamo una stranezza nel ripristino, notifiche N015, dove ne abbiamo ricevute tre al comune di Savona per lo stesso soggetto id cittadino 59323371. le tre notifiche sono consecutive: id operazione anpr 97360318, 97360319, 97360320.
Controllando da WA, l'altro Comune sembra aver fatto una sola operazione:
id operazione anpr di "annulla mutazione" 97359265.
Lo segnaliamo perchè ci da qualche problema, il moltiplicarsi di notifiche.

**Comment by fferraguto** [comment]
Salve,
la correzione sarà resa disponibile in produzione entro oggi.
Cordiali saluti.
