### ISSUE TITLE
Ambienti ANPR: chiarimenti su nuove modalità di accesso per Software House

### ISSUE THREAD

**Issue by antonioluberto** [italia/anpr#1408]
Buongiorno.
Con riferimento alla comunicazione “Nuove Modalità di Accesso agli ambienti di Pre-subentro e Test-Comuni #1368 (https://github.com/italia/anpr/issues/1368), si richiedono i chiarimenti di cui ai successivi punti a), b), c); il tutto con l’obiettivo di definire con certezza le modalità secondo le quali la Software House, che eroghi soluzione applicativa in cloud,  possa gestire nei termini di legge le proprie attività di sviluppo e supporto ai Comuni (si veda anche https://github.com/italia/anpr/issues/35 ).

A far data dal 15 luglio 2019 :
a) l’accesso all’area di Pre-Subentro potrà avvenire solo da pc - "interno" al dominio comunale - sul quale risulti installato specifico certificato di postazione e solo mediante utenza nominale opportunamente abilitata dal Responsabile della Sicurezza del Comune? È da intendere per “interno” il posizionamento fisico e non telematico della postazione? Se ne deduce che nessun accesso all’area di Pre-Subentro potrà avvenire dalla sede della Software House e l’analisi di eventuali anomalie rilevate dall’ Ente potranno essere condotte solo mediante collegamento da remoto in teleassistenza su postazione comunale e solo mediante utenza associata a specifico utente comunale.
b) la Software House potrà accedere all’ area di test dalla propria sede, ma solo se il Responsabile della Sicurezza del Comune avrà abilitato una specifica utenza collegata ad utente comunale già censito? In alternativa  tale utenza si può ipotizzare che venga intestata ad un dipendente della Software House medesima? 
c) la creazione dell’ambiente di test prevede sempre il conferimento del solo 10% delle anagrafiche complessivamente presenti negli archivi APR/AIRE del Comune? Gli stessi dati sono conferiti comunque in chiaro?

Ringraziando sin d'ora per le indicazioni che vorrete fornirci, porgo cordiali saluti.

Antonio Luberto
Information systems analyst
Dedagroup Public Services
T 0461 997144 | M 348 1501304 | VoIP 900144
Dedagroup Public Services Srl – Sede di Trento, Loc. Palazzine 120/f
www.dedagroup.it

**Comment by INSIEL1** [comment]
aggiungo una domanda:l'ambiente di test è integrato con equivalente ambiente di test di Agenzia entrate? 

Rita Klingendrath (INSIEL)

**Comment by siscomanpr** [comment]
In riferimento a quanto indicato in “Nuove Modalità di Accesso agli ambienti di Pre-subentro e Test-Comuni" #1368 dove dice:"..in ambiente di Pre-subentro saranno cancellati i dati dei comuni già subentrati da più di tre mesi e i dati dei comuni non ancora subentrati il cui ultimo pre-subentro è stato effettuato da più di 6 mesi.", per i comuni che sono pianificati per subentrare dal 15 luglio 2019 in avanti e che hanno effettuato il presubentro da più di 6 mesi, sarà necessario effettuare un nuovo presubentro?

**Comment by rvinzani** [comment]
a)	All’ambiente di presubentro possono accedere solo dipendenti del comune da postazioni del comune
b)	Sì, il responsabile della sicurezza può abilitare anche un soggetto che non faccia parte del comune ma sia un tecnico della casa software
c)	In ambiente di test è possibile inviare 1 solo file APR ed uno AIRE indipendentemente dalla numerosità della popolazione del comune. I dati non devono essere reali ma di test

**Comment by rvinzani** [comment]
> per i comuni che sono pianificati per subentrare dal 15 luglio 2019 in avanti e che hanno effettuato il presubentro da più di 6 mesi, sarà necessario effettuare un nuovo presubentro
Sarebbe consigliabile

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue facendo riferimento a questa stessa
