### ISSUE TITLE
ws 4005 / 7001  - Zip File Vuoto

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1409]
Salve,
Stiamo effetuando dei test di invocazione del servizio 4005-VerificaStato per ricevere l'xml degli operazioni anagrafici. La risposta si riceve correttamente, pero codificando lo stream in un archivio .zip e successivamente estraendone il contenuto della richiesta ci risulta di essere vuoto.
Abbiamo provato anche il servizio 7001 siccome la logica dovrebbe essere la stessa per quanto riguarda la compressione gz delle risposte, ma riscontriamo lo stesso problema.

Facendo riferimento al'issue #840, abbiamo utilizzato lo stesso codice_di_esempio.
Ambiente Test - Id Sede: 888120
IdOperazioneANPR : 2137182

Grazie in anticipo,
Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Salve, l'operazione cui fate riferimento (un 7001 per cui viene richiesta la tabella dello stato civile), sembra essere stata elaborata correttamente.

Non contenendo il 7001 informazioni sensibili, ci permettiamo di riportare per intero il suo contenuto :

[Richiesta e risposta operazione 2137182](https://github.com/italia/anpr/files/3326559/7001_operazione_anpr_2137182.zip)

In particolare ecco [Lo zip dell'allegato base 64](https://github.com/italia/anpr/files/3326563/base64.zip)

Il funzionamento del 4005 non è identico al 7001.
Infatti il 4005 potrebbe avere per ogni richiesta/risposta un file in chiaro o un archivio (ma in generale sarà un archivio gzip). 
L'argomento è stato trattato anche nella issue #1277.

Se non riuscite a risolvere il problema potete postarci il contenuto per intero della risposta del 7001? (meglio evitare in generale di postare le risposte del 4005 che potrebbero contenere informazioni sensibili).

Siamo a disposizione per ogni ulteriore chiarimento
Saluti

Assistenza ANPR

**Comment by AlbanaCelepija** [comment]
Salve, 
Si, il 4005 potrebbe avere un file in chiaro o un archivio, intendevo l'assomiglianza con 7001 nel caso di un archivio. Riporto il contenuto del 7001 che riceviamo:
> 

      <?xml version="1.0" encoding="UTF-8"?>
      <soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Body>
		<ns2:Risposta7001
			xmlns:ns2="http://sogei.it/ANPR/7001scaricoTabelle">
			<ns2:RispostaMultipla7001>
				<testataRisposta>
					<idOperazioneComune>op9128</idOperazioneComune>
					<codMittente>888120</codMittente>
					<codDestinatario>ANPR02</codDestinatario>
					<operazioneRichiesta>7001</operazioneRichiesta>
					<dataOraRichiesta>2019-06-25T10:00:00.543+02:00</dataOraRichiesta>
					<dataDecorrenza>2019-06-25+02:00</dataDecorrenza>
					<idOperazioneANPR>2137182</idOperazioneANPR>
					<esitoOperazione>0000</esitoOperazione>
				</testataRisposta>
				<datiDettaglioRisposta>
					<idTabella>001</idTabella>
					<xmlFile>
						<xop:Include href="cid:e16204591e8d46b8824cf347195f141f5662f79e5fb4b7b6@apache.org"
							xmlns:xop="http://www.w3.org/2004/08/xop/include"/>
						</xmlFile>
					</datiDettaglioRisposta>
				</ns2:RispostaMultipla7001>
			</ns2:Risposta7001>
		</soapenv:Body>
	</soapenv:Envelope>
       --MIMEBoundary_016204591e8d46b8824cf347195f141f5662f79e5fb4b7b6
      Content-Type: application/octet-stream
      Content-Transfer-Encoding: binary
      Content-ID: <e16204591e8d46b8824cf347195f141f5662f79e5fb4b7b6@apache.org>

**Comment by mttfranci** [comment]
Salve,
A noi la risposta sembra generata correttamente.
Che tecnologia usate per il client?
Supporta MTOM e XOP per i contenuti binari?
Saluti

Assistenza ANPR

**Comment by AlbanaCelepija** [comment]
Salve,
Usiamo il client esempio di anpr: https://github.com/italia/anpr-client-example.
Forse anche per quello bisogna impostare qualche parametro per supportare MTOM e XOP, provvederemo a abilitare mtom.
 
Grazie per l'assistenza,
Saluti
