### ISSUE TITLE
Web app - Gestione notifiche

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#141]
Data test: 02/05/2017 - Ambiente di test
Effettuando la ricerca delle "notifiche mutazioni di residenza" da "monitoraggio operazioni" viene visualizzato un elenco di 26 notifiche con contenuto "disponibile". Tuttavia, cliccando, viene fornito il seguente messaggio di errore: "This page contains the following errors: error on line 1 at column 1: Document is empty. Below is a rendering of the page up to the first error."

Cliccando invece su "Notifiche" il messaggio è "Nessuna notifica da ricevere."

Dal momento che, ad oggi, non abbiamo recepito nell'ambiente di test del ns. gestionale alcuna di queste notifiche, quale funzione possiamo capire quali sè più corretto utilizzare per individuare quali notifiche e quindi quali soggetti sono ancora da trattare?
Grazie,
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Può riprovare

**Comment by VBocchinoTO** [comment]
Ora la ricerca "notifica mutazione di residenza" funziona correttamente, mentre continua ad essere indicato "nessuna notifica da ricevere" in "notifiche"
Credo quindi che il tag "futuro" sia legato a questa attività.
Grazie.

**Comment by gcarbonin** [comment]
Effettuando la consultazione delle notifiche da Monitoraggio operazioni, la notifica passa allo stato di "ricevuta" e quindi non è più da ricevere. Se ha fatto per prima questa operazione, diciamo che le funzioni "funzionano" correttamente. In caso contrario devo approfondire. Il tag Futuro di riferisce ad una diversa estrazione di tipo asincrono che consenta a chi usa la WA di effettuare una sorta di quadratura delle notifiche

**Comment by VBocchinoTO** [comment]
Corretto: effettivamente ho eseguito le consultazioni prima in Monitoraggio operazioni e poi in Notifiche.
Pongo un'altra domanda: se accedessi a Notifiche visualizzando l'elenco delle notifiche da ricevere, tutte le notifiche diventerebbero "ricevute"? Conseguentemente, ad un secondo accesso dello stesso o di un altro utente l'elenco risulterebbe vuoto?
La motivazione di questa domanda deriva dal fatto  che il Comune di Torino opererà esclusivamente con la Web App per la consultazione delle notifiche. Dato che più di un operatore utilizzerà la funzione, sarebbe utile che la singola notifica passasse in stato "ricevuta" dopo essere stata effettivamente aperta  e non soltanto visualizzata nell'elenco (salvo l'estrazione già "in cantiere" abbia proprio questo scopo).
Grazie.

**Comment by gcarbonin** [comment]
Mi sembra che da "Notifiche" l'elenco renda la notifica "letta", come per altro tramite WS si considera la notifica recapitata e non elaborata dal sistema chiamante. Direi di comprendere bene come pensate di utilizzare le notifiche e poi capire come intervenire.
