### ISSUE TITLE
[6001] Probelmi con certificazione on line senza diritti di segreteria

### ISSUE THREAD

**Issue by slastrucci** [italia/anpr#1411]
Buongiorno, 
da qualche giorno il nostro portale di certificazione on-line ha cominciato a dare il seguente errore nella produzione di alcuni certificati :  
**EN209 - Importo diritti segreteria deve essere maggiore di 0,00 euro**

Guardando i log e le segnalazioni dei cittadini sembra che il problema sia iniziato intorno alle 14:50 di mercoledì 26 giugno.

La cosa strana è che non ci risultano modifiche al software e/o alla configurazione nè da parte nostra nè da parte di Maggioli.

Abbiamo confrontato l'xml di chiamata ad ANPR di due casi simili, uno prodotto il giorno prima quando tutto funzionava correttamente e uno dopo che è comparso l'errore.  In entrambi casi la parte dei diritti è identica.
C'è stato qualche intervento da parte vostra?

Allego gli xml anonimizzati dei suddetti casi.

Grazie.

Lastrucci Stefano

[casi.zip](https://github.com/italia/anpr/files/3338312/casi.zip)

**Comment by rnapoli1983** [comment]
Buonasera,

in realtà ci siamo accorti di un piccolo malfunzionamento ed a breve rilasceremo una versione che dovrebbe risolvere il problema.

Sarà nostra premura comunicarvi quando riprovare.

Cordiali saluti.

**Comment by mttfranci** [comment]
Salve, dovreste poter riprovare, ma prima probabilmente sarà necessario salvare nuovamente le preferenze dei certificati nell'area di amministrazione del comune.
Saluti

Assistenza ANPR

**Comment by slastrucci** [comment]
Ora sembra funzionare correttamente.

Grazie.

Lastrucci Stefano

**Comment by Eduardo1977** [comment]
Buongiorno, i certificati richiesti online se esenti da diritti di segreteria (così come impostato nei parametri da webApp) riportano la dicitura "Riscossi Euro 0,00 per diritti di segreteria". E' corretto oppure  dovrebbe comparire "Esente da diritti di segreteria" ? Grazie

**Comment by rnapoli1983** [comment]
Buongiorno ad oggi il testo "Esente da diritti di segreteria" viene apposto esclusivamente per motivi di esenzione espliciti molto spesso subordinati anche alle esenzioni del bollo.

Cordiali saluti

**Comment by Eduardo1977** [comment]
Vorrei segnalare che il problema "EN209 - Importo diritti segreteria deve essere maggiore di 0,00 euro" forse si verifica ancora se il tipoEmissione=3 per l'anteprima. Potreste verificare gentilmente?

**Comment by rnapoli1983** [comment]
Buonasera,

potreste fornirci l'idOperazioneANPR ?

Grazie mille

**Comment by Eduardo1977** [comment]
Buongiorno, eccone due 100473833, 100470427
Grazie

**Comment by rnapoli1983** [comment]
Buongiorno.

Facciamo un'analisi delle richieste e le faccio sapere.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buonasera, 
effettivamente abbiamo riscontrato un errore che è stato risolto, quindi può riprovare.

Comunque visto il contesto del problema credo sia utile comunicarle quanto segue.

Il campo "emissione" è impiegato per poter emettere un certificato sia in modalità on-line (emissione=2) sia in modalità anteprima (emissione=3) questo significa che non esiste una modalità specifica di anteprima per i certificati online.

Quindi per permettere l'emissione di un'anteprima di certificato on-line esente da diritti di segreteria l'unico modo è che siano presenti entrambe le esenzioni dei diritti di segreteria sia on-line che non.

Questo perché la modalità anteprima è stata realizzata con la finalità di verificare principalmente la correttezza del dato anagrafico prima dell'effettiva emissione di certificato.

Rimango a disposizione.

Cordiali saluti
