### ISSUE TITLE
[3002] ricerca non restituisce il documento di soggiorno

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1413]
Ambiente di produzione, comune di Brescia

Il soggetto ID ANPR 61849048 è subentrato con il comune.
Al subentro sono stati passati i dati del documento di soggiorno.
Effettuando però una ricerca 3002 questi dati non vengono ritornati nella risposta (id ANPR 99313778).

Come mai ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, il permesso di soggiorno per il soggetto in questione è stato effettivamente trasmesso in fase di subentro ma non aveva il numero : 

  `<permessoSoggiorno>
    <tipoSoggiorno>4</tipoSoggiorno>
    <noteSoggiorno>Titolare del diritto ****************************</noteSoggiorno>
    <dataRilascio>2011-09-28</dataRilascio>
    <comune>
      <nomeComune>BRESCIA</nomeComune>
      <codiceIstat>017029</codiceIstat>
      <siglaProvinciaIstat>BS</siglaProvinciaIstat>
    </comune>
  </permessoSoggiorno>`

I permessi di soggiorno senza numero non vengono caricati in fase di subentro.
Abbiamo inserito in [Roadmap](https://github.com/italia/anpr/blob/master/src/change-management/roadmap.md) per la versione 5.5 di verificare l'obbligatorietà del permesso di soggiorno da XSD.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Ci scusiamo per la precedente risposta.
Il numero del permesso in effetti non è obbligatorio, la modifica agli XSD non verrà effettuata.
Come detto nella issue #1414 la situazione di Brescia è stata recuperata.

Saluti

Assistenza ANPR
