### ISSUE TITLE
Permessi di soggiorno senza numero non caricati al subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1414]
continuo con alcune domande sulla #1413 

1) nelle anomalie restituite dopo il subentro sono segnalate queste casistiche ? Qua è il codice dell'anomalia ?
2) In quale documentazione è specificato che i documenti di soggiorno senza numero vengono scartati al subentro ?

Grazie

**Comment by mttfranci** [comment]
Salve, ci scusiamo per aver risposto in modo affrettato.
In effetti c'era un errore per il quale alcuni permessi di soggiorno non sono stati caricati.
I permessi senza numero sono ammessi. 
Dovremmo aver recuperato i permessi del comune di Brescia (ci risulta un totale di 1983 permessi recuperati)
, incluso quello del soggetto di esempio che ci avevate fornito nella issue #1413.
Ecco l'elenco completo degli idsoggetto coinvolti : 
[permessi_brescia.zip](https://github.com/italia/anpr/files/3344526/permessi_brescia.zip)

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR.
