### ISSUE TITLE
[1002] EN185 in re-iscrizione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1415]
Ambiente di produzione, comune di Bertinoro

Il comune deve iscrivere il soggetto ID ANPR 18584923.
Questo soggetto era stato iscritto nel 2016 in ANRP a Cesena, poi era stato cancellato da ANPR per emigrazione verso non subentrato e tuttora è cancellato da ANPR.
La richiesta di iscrizione (ID ANPR 99898607) però ci risponde "idSchedaSoggettoANPR 18584923 non presente o dati anagrafici incongruenti".

Come mai ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
Abbiamo riscontrato un bug già risolto, disponibile in ambiente di produzione a partire da mercoledì 3/07/2109;
nel caso fosse urgente la re-iscrizione del cittadino, nel Comune di nascita dovrà inserire Forlì  anzichè Forli'.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
