### ISSUE TITLE
[1002] EF056 in iscrizione (rigetto espatrio a cavallo del subentro)

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1416]
Ambiente di produzione, comune di Canicattì.

Il comune aveva aperto una pratica di espatrio per un suo cittadino prima del subentro.
Il cittadino dunque è subentrato come AIRE.
ora, dopo il subentro, la pratica deve essere rigettata ed il cittadino tornare in APR.

Abbiamo dunque come prima cosa cancellato per altri motivi il soggetto (ID operazione 99327988) con successo.
Abbiamo successivamente tentato di iscriverlo (id ANPR 99328008) nella famiglia in cui si trovava precedentemente con la relativa decorrenza, ma otteniamo l'errore EF056 "La data decorrenza appartenenza alla famiglia deve essere uguale alla data decorrenza dell'operazione".
Ma questo non è possibile ottenerlo perché il soggetto deve risiedere nella famiglia in cui lo iscriviamo dalla data legale in cui vi si trovava prima dell'espatrio.

Noto inoltre che abbiamo già eseguito in altri casi simili le operazioni sopra descritte con successo.

Potete verificare per favore ed aiutarci a risolvere il problema ?

Grazie

Gianrico Busa 
Maggioli Spa

**Comment by frmariani** [comment]
ho verificato che sul cittadino sono state effettuate diverse operazioni di cancellazione e annullamento della cancellazione:  al momento il soggetto NON risulta cancellato;
comunque l'errore dell'operazione 99328008 è dovuto al fatto che viene inserita una data di decorrenza dell'operazione diversa dalla data di decorrenza dell'appartenenza alla famiglia: dovrebbe inserire come data di decorrenza dell'operazione  19/09/2012

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
