### ISSUE TITLE
scollegamento codici fiscali

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#1417]
Buongiorno, 
si ha la necessità di scollegare 2 codici fiscali appartenenti ad una stessa scheda all'Agenzia delle entrate.

L'ufficio territoriale di competenza  non ha potuto procedere in quanto viene segnalato il seguente messaggio: "Attenzione!  Scollegamento non effettuabile  - entrambi i codici fiscali appartengono a soggetti ANPR".

E' un'operazione che spetta al comune di residenza subentrato in ANPR? e se si come si deve procedere?

Rimango in attesa di un vostro cortese riscontro
Cordiali saluti
Andrea Demeglio
Comune di Cagliari

**Comment by azabatta** [comment]
Buongiorno, 
in ANPR non è prevista l'operazione di "scollegamento" di due codici fiscali. 
La segnalazione, con tutta la documentazione disponibile,  deve essere sottoposta all’attenzione della Direzione Centrale Archivio Anagrafico che effettuerà la necessaria istruttoria.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
