### ISSUE TITLE
[7001] idTabella 45 - Scarico comuni subentrati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1418]
Buongiorno,
oggi in data 01/07/2019 abbiamo riscontrato differenze all'interno del tracciato CSV dei comuni subentrati (idTabella 45) tra il TEST e la PRODUZIONE.
Nel tracciato in TEST abbiamo notato l'aggiunta del campo ID e la modifica dell'intestazione di un altro.
Verrà modificato anche in PRODUZIONE? Se si quando?

Questa modifica in TEST è stata preannunciata in qualche modo?
Perchè consultando la documentazione tecnica (tabella di riferimento 45) aggiornata in data 01/07/2019, la struttura del tracciato è identica a quella attuale in PRODUZIONE.

Ringrazio anticipatamente.

**Comment by mttfranci** [comment]
Salve,
Si tratta di una anomalia introdotta nel corso di alcune ottimizzazioni che abbiamo già corretto.
Se volete potete riprovare e verificare se ora il contenuto del file 7001 vi risulta corretto.
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Abbiamo riprovato, ora la struttura del tracciato in Test è analoga alla Produzione, c'è ancora una piccola differenza, i campi dei record sono delimitatati dal doppio apice (").

ESEMPIO:
-Produzione
024121;M194;ZOVENCEDO;24;05;VI;08-02-2019;

-Test
"024121";"M194";"ZOVENCEDO";"24";"05";"VI";"19-10-2018"

E' corretto ci siano questi apici oppure sono parte dell'anomalia da voi citata?


Grazie per la collaborazione.

**Comment by mttfranci** [comment]
Salve, 
Sono state aggiornate le API con cui generiamo i CSV da scaricare con il servizio 7001.
Ovviamente il cambio di struttura quando abbiamo aggiunto l'ID è stata una svista.
Invece l'aggiunta dei separatori è stata una scelta per rendere più stabile il contenuto (ci sono alcune tabelle per cui questo è particolarmente utile).
In generale tutte le API più diffuse per la lettura dei CSV possono interpretare correttamente i CSV sia con i doppi apici separatori che senza.
Se lasciare i doppi apici vi crea qualche problema possiamo anche governare la libreria per aggiungerli solo laddove necessario.
Se invece non vi crea problemi lasciamo tutto così (visto che il i file è aderente al formato CSV in entrambi i modi).
In caso questa versione del 7001 dovrebbe andare in produzione il 15 Luglio con il rilascio della minor version 5.5.
Saluti

Assistenza ANPR

**Comment by SAlberto** [comment]
Non ci creano problemi gli apici, lasciateli pure, modifichiamo la lettura del CSV.

**Comment by mttfranci** [comment]
Ok, ma come detto  l'aggiunta della colonna "id" era una anomalia, la tabella 45 rimane così come era prima, solo con gli APICI.
In produzione il 15 Luglio l'unica differenza che avrete sarà la presenza degli apici.
Saluti

Assistenza ANPR
