### ISSUE TITLE
Notifiche non scaricate

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1419]
Ambiente di test - Comune di Manerbio BS
Nella WA si vedono due notifiche di migrazione in altro comune (numeri 19830226 e 19830230).
Le migrazioni sono avvenute ieri 01/07/2019 alle ore 20:30 circa.
Abbiamo eseguito ripetute richieste di scarico al servizio 4005, riceviamo la risposta che le notifiche saranno disponibili entro un'ora.
Questo comportamento va avanti ormai da 15 ore.
Grazie.
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Salve, potreste sempre indicare almeno una id operazione anpr per queste segnalazioni?
Da tenere presente che, mentre in produzione cerchiamo di mantenere dei livelli di prestazioni accettabili, gli  ambiente di test / presubentro sono pur sempre sistemi di sviluppo dove i tempi non sono garantiti.
Saluti

Assistenza ANPR.

**Comment by bfilipazzi** [comment]
Ecco gli ID del 4005
<idOperazioneANPR>19833110
<idOperazioneANPR>19833331
<idOperazioneANPR>19833411
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Ok abbiamo trovato il problema è dovremmo averlo risolto.
Potrebbe esserci ancora qualche rallentamento fino a domani ma contiamo che entro qualche ora tutto torni alla normalità.
Saluti

Assistenza ANPR
