### ISSUE TITLE
Mutazione tutti i dati  - generalità

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#142]
Si vuole inserire segno diacritico sul cognome di un soggetto subentrato, ma la funzione non prevede l'icona della tastiera su campi che possono essere variati 
Amprimo Floramo Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Il tastierino è previsto. In quale funzione non lo ha trovato?

**Comment by UpiTorino** [comment]
Ora nella Mutazione Dati Generali è presente, però modificando una "A" nel campo cognome e una "O" nel campo del nome il sistema segnala "Variazione non consentita per superamento numero campi variati (Codice: EAM93)". CF SHHHHYM80S09Z336Z

**Comment by gcarbonin** [comment]
E' un errore restituito dall'Agenzia delle Entrate che accetta la variazione contemporanea di tre dei 5 dati che concorrono alla formazione del codice fiscale. Nell'operazione che ho visto è stato variato sia il nome che il cognome. Provate a variare solo 1 dei due. Approfondisco con AE

**Comment by gcarbonin** [comment]
L'Agenzia delle Entrate ha modificato il proprio SW. E' possibile riprovare. Mi faccia avere un riscontro

**Comment by UpiTorino** [comment]
Sono stati modificati il campo cognome (modificata "I") e campo nome (modificata "O").
Risposta: "Il campo Cognome in Generalit� contiene dei caratteri non validi"
Modificato solo il cognome Risposta: Richiesta incongruente - soggetto NON marcato ANPR (Codice: EAM91)

**Comment by gcarbonin** [comment]
Il soggetto è sempre lo stesso?

**Comment by UpiTorino** [comment]
no l'ho cambiato, ora è PCRRRT99M12Z100H

**Comment by gcarbonin** [comment]
Sul primo errore probabilmente è stato indicato un valore non previsto: i caratteri diacritici ammessi sono solo quelli del "decreto Brunetta": non ho modo di verificare,  Per il secondo problema  nella mutazione non è stato specificato nulla sul codice fiscale che cambiando le generalita' cambia. Riesegua l'operazione con Operazione sul codice fiscale = 3.

**Comment by UpiTorino** [comment]
Avevo modificato una "I" presente nella tastiera visualizzata.
Poichè nella tabella Gestione Codice Fiscale non c'è una numerazione per i valori riportati ho testato tutti i valori con questi risultati :
- "Iscrizione/modifica senza validazione CF"
R:.Attenzione! Sono stati modificati i dati anagrafici del soggetto senza validazione di Agenzia Entrate. 
(Codice: EN230)
- "Nessuna operazione" 
R.: Richiesta incongruente - soggetto NON marcato ANPR (Codice: EAM91)
- "Richiesta Attribuzione"
R.:Per richiesta attribuzione CF o omocodice, il codice fiscale non deve essere valorizzato (Codice: EN125)
- "Richiesta omocodice" 
R.: Operazione correttamente eseguita
Test eseguito su CF: DBLBGI60P20Z315Z, ora ho modificato una "A" nel cognome

**Comment by gcarbonin** [comment]
Ho cercato di ricostruire la situazione in quanto le segnalazioni di AE sono sempre legate ad una specifica configurazione dei dati: ricordiamo che pre-subentro è un ambiente di test che utilizza la base dati AE reale per la validazione al momento del subentro, una base dati di test per i servizi. Nel caso specifico la persona è validata AE da subentro ma probabilmente non è presente nella base dati di test o, anche se lo fosse, non avrebbe una informazione essenziale per l'Agenzia "soggetto marcato ANPR".
Di seguito i dettagli per ciascun caso di test: 
1) id operazione = 490914 - mutazione di generalita' con Iscrizione/modifica senza validazione CF; va male perché questa possibilità per i "validati AE" è, al momento, bloccata per evitare che una operazione del comune introduca un disallineamento; stiamo modificando questa impostazione;
2)  id operazione = 490926 - come sopra; questo codice fiscale non c'è in ambiente di test o comunque non è marcato da AE come soggetto ANPR; ANPR ha trasmesso comunque ad AE una richiesta di variazione (il cognome è diversi) che diventa incongruente in quanto AE accetta questa variazione soltanto per i soggetti "marcati ANPR"; 
3)  id operazione = 490929 - quando si chiede l'attribuzione del codice fiscale, la persona non deve avere un CF; in questo caso il cf è presente in ANPR;
4) id operazione = 490945; è andata bene perche' in realtà non ci sono variazioni nei dati anagrafici e quindi AE non viene richiamata.

Per eseguire questo tipo di test:
1) effettuare una iscrizione ex-novo chiedendo l'attribuzione del CF;
2) attendere 2 giorni che sono necessari ad AE per allineare la propria base dati (in esercizio il termine è di un giorno);
3) modificare le generalità;.

Comprendo che è una situazione complicata ma si sta lavorando molto con il team per migliorare questa integrazione con AE

**Comment by gcarbonin** [comment]
E' stata aggiornata la documentazione. Attendiamo ritorni
