### ISSUE TITLE
[5008] Variazione identificativo scheda soggetto comune - Errore EN389

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1420]
Buongiorno,
nel comune di Collegno, ambiente di produzione, si è verificato il seguente caso:
Un individuo aveva un blocco di certificazione impostato. Il comune riceve dal consolato la comunicazione di iscrizione all'AIRE con decorrenza 14-06-2019.
L'utente procede in prima istanza a togliere il blocco di certificazione eseguendo una comunicazione 5008 in data corrente (25-06-2019).
Successivamente procede a iscrivere all'AIRE l'individuo in oggetto con la decorrenza fornita dal consolato (14-06-2019). Quando tenta di aggiornare con la 5008 l'Identificativo Scheda Soggetto Comune (IdOperazioneANPR 98633868) ottiene l'errore: 
EN389 - La data decorrenza 14-06-2019 dell'operazione non puo' essere inferiore alla data decorrenza 25-06-2019 dell'ultima operazione effettuata sui dati relativi a generalita'.

In effetti l'individuo ha avuto il blocco di certificazione fino alla data del 25-06-2019, ed è altrettanto vero che l'iscrizione AIRE ha la data del 14-06-2019 perchè indicata dal consolato.

Qual'è la corretta procedura da eseguire in questi casi?
In attesa di un cortese riscontro
Saluti

**Comment by ncapozzi** [comment]
Buonasera,
il messaggio di errore si riferisce al fatto che esiste già una mutazione tutti i dati (WS 5008) con data decorrenza 25-06-2019 e quindi non è possibile effettuare una nuova mutazione dello stesso tipo con data decorrenza precedente a questa. La modifica dell'identificativo soggetto attribuito dal comune ad una data >= 25-06-2019 non altera la data di trasferimento all'estero.

N. Capozzi
