### ISSUE TITLE
Problema su soggetto nato in IUGOSLAVIA

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1421]
Comune di Modena - Ambiente di produzione

Buongiorno,
il soggetto con idANPR 19375639 è nato nel 1950 in IUGOSLAVIA; in AE il dato è corretto e il CF validato, in ANPR lo stato di nascita è NON ATTRIBUIBILE con descrizione SERBIA MONTENEGRO. Come già successo in casi precedenti (vedi issue #1312) non riusciamo in nessun modo ad effettuare la mutazione per allineare ANPR, per cortesia potete aiutarci?

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera.
Avete provato ad effettuare la mutazione dello stato estero di nascita da SERBIA MONTENEGRO a IUGOSLAVIA? Agenzia delle Entrate ha fatto di recente degli aggiornamenti.
Ha un id operazione che possiamo controllare?

**Comment by sfmodena** [comment]
Buongiorno,
abbiamo provato la mutazione sia ieri sia oggi, ottenendo sempre questo errore:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-04 08:28:34 , idOperazioneANPR 100868476 (Codice: EN527)

Saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Contattata la Sig.ra Fiorini, il CF è stato aggiornato e validato su Agenzia Entrate.
