### ISSUE TITLE
Rilevazione anomalie subentro definitivo

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1422]
Ambiente produzione comune Mediglia.

Il comune è subentrato ieri e controllando le anomalie ha notato che il file contiene delle informazioni errate, a volte anche duplicate, non coerenti con le informazioni presenti nelle schede del cittadino e nella WA.

Riporto alcune casistiche:
1. cittadino 23316345 nel file troviamo gli errori EC081 e EC042, in cui si fa riferimento al comune di PASSO DI RIGANO (PA), ma l'evento e la registrazione dell'atto di matrimonio è avvenuto a PALERMO dato che è stato inviato con il subentro e presente nella WA, di conseguenza non ne capiamo la provenienza,
2. cittadino 25183646 situazione analoga alla precedente, gli errori fanno riferimento al comune di ERCOLANO (NA), ma risulta sposato e con atto iscritto a RESINA (NA),
3. cittadino 19174328 nel file excel troviamo più di una riga per lo stesso errore EN306, il quale risulta triplicato e due di questi record  fanno riferimento ad un "Progressivo APR/AIRE soggetto" che non è presente nel comune e che non è stato inviato con il file si subentro.  In merito alla questione per il cittadino 23316345 troviamo addirittura 12 record. Come mai si sono duplicate le anomalie? Da dove vengono presi i progressivi soggetti anomali?

Grazie

**Comment by mttfranci** [comment]
Salve,
In effetti abbiamo individuato l’anomalia, che si può presentarsi talvolta, in particolare nei casi un soggetto sia stato cancellato da ANPR e poi viene re-iscritto dal subentro.
Le segnalazioni in più comunque non costituiscono nessun blocco all'operatività.
Contiamo di correggere il software entro una settimana, pertanto a partire dai subentro dell’11 luglio non dovrebbero più capitare anomalie  duplicate,

Siamo a disposizione per ogni ulteriore chiarimento.

Grazie della segnalazione
Assistenza ANPR

**Comment by mttfranci** [comment]
Abbiamo appena rilasciato la correzione della generazione delle anomalie.
Saluti

Assistenza ANPR
