### ISSUE TITLE
Blocco certificazione ANPR su cancellato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1423]
Ambiente di produzione, id cittadino anpr 60730963.
Il Comune ha inserito un blocco di certificazione completa (id anpr operazione 98804130). per notizia ricevuta da altro ufficio di decesso avvenuto all'estero tanti anni fa.
In seguito cancellato per irreperibilità  (id operazione 98817554).

Oggi sta provando il certificato storico di residenza, e non esce, nemmeno forzandolo.
Però il Comune non è nemmeno abilitato a togliere il blocco di certificazione: cercandolo dalla mutazione dati WA per id anpr, risponde "Non sono stati trovati soggetti corrispondenti ai criteri di ricerca". Immagino in quanto cancellato.
Però dovremo produrre un certificato storico, qualora venisse richiesto.
E' possibile valutare la risoluzione di questo blocco? Se non possibile ora, valutatela come evoluzione.

**Comment by rvinzani** [comment]
Salve, nella WA è visibile in consultazione ma con i dati di cancellazione impostati. Non è però possibile aggiornare la sua posizione in quanto archiviata. Se il problema è urgente il comune può annullare la cancellazione per decesso, eliminare il blocco e acquisire nuovamente la cancellazione per decesso. Questo facendo attenzione alle date. 
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa stessa.
