### ISSUE TITLE
Il campo Motivo contiene dei caratteri non validi 

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1425]
Devo aggiornare sulla web app lo stato civile di un cittadino. Usando la funzione Registrazione<<Mutazione tutti i dati mi appare l'errore  "Il campo Motivo contiene dei caratteri non validi"
Identificativo scheda attribuito da ANPR: 18911260

**Comment by Finalmentesubentrati** [comment]
Stesso problema abbiamo con il cittadino Identificativo scheda attribuito da ANPR: 18911689

**Comment by paoloand** [comment]
Un tipo di carattere non valido potrebbe essere "/" o "\", controlla se compaiono

**Comment by mttfranci** [comment]
Salve, in effetti era la validazione della webapp ad essere troppo stringente.
Potreste riprovare?

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by Finalmentesubentrati** [comment]
Ok perfetto. Può chiudere la issue
