### ISSUE TITLE
Servizio KO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1426]
Buongiorno,
da questa mattina stiamo riscontrando dei problemi con la WA. 
Anpr è molto lento e non si riescono ad emettere CIE in quanto il sistema espone messaggio " Attenzione, si è verificato un errore nella creazione richiesta; servizio ANPR momentaneamente non disponibile. Si prega di riprovare più tardi".
E' impossibile anche eseguire delle risoluzioni con Agenzia Entrate.
Potreste verificare?
Grazie per la disponibilità
UpiTorino

**Comment by RENZO63** [comment]
Anche da noi e' impossibile rilasciare le cie
Dal momento che anche la tabaccheria di zona non riesce ad emettere le marche da bollo presumo sia un problema dell'agenzia delle entrate.
Anpr invece funziona (lentamente) per quanto riguarda emissione certificati ed altro...

**Comment by rvinzani** [comment]
I problemi di rallentamento dell'applicazione web di ANPR sono rientrati. 
Chiudiamo pertanto la issue.
In caso di ulteriori problemi si prega di aprirne un'altra facendo riferimento a questa stessa
