### ISSUE TITLE
Lentezza nelle risposte dei servizi in produzione

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1427]
Buongiorno,
gli operatori del Comune di Torino stanno riscontrando difficoltà nell'effettuare le operazioni in quanto i tempi di risposta di ANPR sono molto lunghi, infatti le chiamate ai servizi rispondono con tempi oltre i 5 secondi. 

```<dataOraRichiesta>2019-07-05T09:27:37.637+02:00</dataOraRichiesta>
            <dataDecorrenza>2019-07-05</dataDecorrenza>
            <idOperazioneANPR>101262999</idOperazioneANPR>

 <dataOraRichiesta>2019-07-05T09:27:36.921+02:00</dataOraRichiesta>
            <dataDecorrenza>2019-07-05</dataDecorrenza>
```

Gli operatori hanno provato ad effettuare anche consultazioni e mutazioni tramite WebApp e riscontrano lo stesso problema.

Potete effettuare dei controlli? 

Grazie, cordiali saluti
Chiara Leanza per il Comune di Torino

**Comment by rvinzani** [comment]
I problemi di rallentamento dell'applicazione web di ANPR sono rientrati. 
Chiudiamo pertanto la issue.
In caso di ulteriori problemi si prega di aprirne un'altra facendo riferimento a questa stessa
