### ISSUE TITLE
Validazione Massiva Codici Fiscali

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1428]
Buongiorno,
avendo un comune in fase di subentro avente il 30% dei CF non validati (di persone residenti) volevamo sapere come possibile allinearli massivamente.
In passato si utilizzava la funzione di allineamento tramite Siatel che a quanto riferito dal comune, è stato disabilitato.
Grazie

Marco Sala
Pa Digitale Spa

**Comment by rvinzani** [comment]
Salve, non è prevista una validazione massiva. La percentuale riscontrata è complessiva AIRE e APR? Altrimenti sembra un po' elevata...

**Comment by paoloand** [comment]
@rvinzani scusate se mi intrometto, ma ho riscontrato il seguente problema, sperando  che la risoluzione possa essere d'aiuto a tutti noi operatori;
  Un soggetto è stato registrato in ANPR con sesso sbagliato, femmina al posto di maschio, richiedendo di conseguenza l'attribuzione di un codice fiscale in AT. Il codice fiscale di tale soggetto in realta' gia' esisteva in AT in maniera corretta con sesso maschile. Quindi esistono 2 codici fiscali in AT per lo stesso soggetto, uno esatto e l'altro scorretto in quanto risulta di sesso femminile. Andando a modificare in ANPR il sesso mi da il seguente errore: "codici fiscali in AT non unificabili" .
Letta la guida dei disallineamenti con AT, paragrafo 4.1 ma pare non funzionare.

**Comment by MarcoSalaPad** [comment]
@rvinzani Buongiorno, il 30% è complessivo. Se dovessimo fare una valutazione dei soli APR la percentuale si abbasserebbe a circa il 20% dell'intera popolazione. Dato che non esiste una validazione massiva, come può operare un Comune da oltre 20 mila abitanti avente una percentuale di codici fiscali non validati per cittadini residenti oltre i 5000 soggetti?

Grazie
Marco Sala
Pa Digitale Spa

**Comment by rvinzani** [comment]
@paoloand  ti prego di rivolgerti per queste problematiche al servizio di assistenza
@MarcoSalaPad Il 20% mi sembra un percentuale già abbastanza alta. Avete verificato che non ci siano errori nell'estrazione dei dati anagrafici (es. errata conversione dei comuni/stati esteri di nascita)? Mi può indicare il comune in questione per fare una verifica?

**Comment by rvinzani** [comment]
Chiudo la issue, in caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
