### ISSUE TITLE
CODICI FISCALI IN AT NON UNIFICABILI

### ISSUE THREAD

**Issue by paoloand** [italia/anpr#1429]
Comune subentrato: Pomigliano d'arco, Ufficio anagrafe.
Salve, un soggetto è stato registrato in ANPR con sesso sbagliato, femmina al posto di maschio, richiedendo di conseguenza l'attribuzione di un codice fiscale in AT. Il codice fiscale di tale soggetto in realta' gia' esisteva in AT in maniera corretta con sesso maschile. Quindi esistono 2 codici fiscali in AT per lo stesso soggetto, uno esatto e l'altro scorretto in quanto risulta di sesso femminile. Andando a modificare in ANPR il sesso mi da il seguente errore: "codici fiscali in AT non unificabili" .
Letta la guida dei disallineamenti con AT, paragrafo 4.1 ma pare non funzionare.

**Comment by azabatta** [comment]
Buonasera, 
con la mutazione dati anagrafici il sistema  rileva che, sulla base dei nuovi dati anagrafici, esiste già una posizione in Agenzia Entrate. 
E' necessario pertanto procedere con l'unificazione dei due codici fiscali.
Quale è il codice di errore restituito dalla funzionalità di collegamento dei codici fiscali?

**Comment by paoloand** [comment]
L'errore che da il gestionale al momento della mutazione dati è: codice errore EAM9C, individuate due posizioni in AT non unificabili. L'ID ANPR del soggetto è 62261951.
L'errore che proviene dallo strumento "disallineamento con ae" in utilità e notifiche nella web app, è il medesimo, ovvero "indivuate due posizioni in AT non unificabili".

**Comment by azabatta** [comment]
Se l'errore è lo stesso inviato dalla mutazione, non sono stati impostati correttamente tutti i parametri richiesti dalla "Risoluzione disallineamenti AE" per il caso specifico del collegamento di due CF.
E' opportuno  seguire l'esecuzione dell'operazione in linea.  
In quale fascia oraria è disponibile per un contatto telefonico?

**Comment by paoloand** [comment]
Lunedì al venerdì dalle 9 alle 14, martedì e giovedì anche dalle 16 alle 19.
Recapito 0815217145
Pec:servdemografici.pomiglianodarco@asmepec.it
Il referente di tali recapiti è la dottoressa Gelsomina Romano. 
Domani mattina va benissimo per il contatto telefonico.
Siccome non sarò in ufficio però, posso lasciare un suo riferimento riferimento nominativo in modo da avvertire il collega. 
La ringrazio per la disponibilità.

**Comment by paoloand** [comment]
@azabatta com'è andata? Se il problema è stato risolto puoi anche chiudere la issue

**Comment by azabatta** [comment]
Il collegamento era già stato effettuato correttamente prima del mio intervento.
Buona giornata

**Comment by paoloand** [comment]
@azabatta ringrazio comunque sentitamente per la vostra professionalità, celerità e cordialità.
