### ISSUE TITLE
Allineamento ANPR / AE - Iscrizioni / Annullamenti: Problemi di interpretazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1431]
ambiente di PRODUZIONE - comune di IMOLA (037032)

riporto le perplessità che ci manifesta il cliente nell'ambito dell'allineamento dei dati tra ANPR e AE.

idSoggettoANPR 53165445

si tratta di soggetto cancellato per irreperibilità da Imola il 24/10/2018, quindi non presente al subentro e non presente in ANPR.
viene iscritto con ws 1002 con decorrenza 05/04/2019 e poi cancellato per Ripristino Posizione Precedente con ws 2003.

Su ANPR la posizione è corretta mentre il dato non lo è su Agenzia Entrate: 
lo stato di "IRREPERIBILE" risulta con una data validità che va dal 24/10/2018 e arriva al 05/04/2019, pertanto sembra che il soggetto sia oggi residente a Imola.

se potete verificare, e farci sapere se c'è un problema e come eventualmente sistemare.

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116
