### ISSUE TITLE
[5008] Mutazione '03': Carta di Identità - non viene aggiornata

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1432]
ambiente di PRODUZIONE - comune di IMOLA (037032)

soggetto a cui è stata rilasciata CIE, poi annullata... a cui è stata alla fine rilasciato un documento cartaceo (idSoggettoANPR 38182649)

su ANPR risulta la CIE emessa il 04/06/2019 annullata il 07/06/2019.
si tenta di inviare la comunicazione di aggiornamento di altra carta di identità (ws 5008 con idOperazione 2019019326): la comunicazione viene accettata senza errori o anomalie, ma ANPR non viene aggiornata.

potete verificare?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
L'emissione e la revoca/annullamento della CIE viene registrata in ANPR tramite servizi che inviano le informazioni direttamente dal sito CieOnLine ma l'annullamento non risulta presente. Nel sito web è possibile richiedere tutti i documenti e risultano presenti due carte di identità.  Abbiamo chiesto informazioni ad IPZS

**Comment by rvinzani** [comment]
In ANPR ora sembra essere annullata
![image](https://user-images.githubusercontent.com/26482893/61129512-dcfac000-a4b4-11e9-9733-8b1852847dc4.png)

**Comment by MassimoSchiappa** [comment]
Salve,
il bug è stato risolto e la risoluzione verrà applicata appena possibile negli ambienti di test e in seguito in produzione.
Saluti.
