### ISSUE TITLE
CODICE ISTAT - CONTURSI / CONTURSI TERME

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1434]
Buongiorno,
abbiamo rilevato che il comune di Contursi divenuto nel 1974 Contursi Terme ha mantenuto lo stesso codice ISTAT 065046. In altre tabelle (Difesa, Sanità Regione Basilicata ad esempio) per lo stesso periodo viene indicato il codice ISTAT 065512.
Cortesemente. è possibile chiarire quale sia il codice corretto per il periodo 1861-1974?
Grazie
Anna Maria AIMONE
Comune di Torino
Responsabile
CODICI FISCALI
UPI

**Comment by MassimoSchiappa** [comment]
Salve,
in generale il codice Istat cambia solo quando avviene un cambio nella provincia di appartenenza e/o nella numerazione istat del comune nella provincia di appartenenza e non in corrispondenza di un cambio di denominazione. 
Invece Istat assegna alle denominazioni dei comuni non più in uso un codice denominazione (vedi https://www.istat.it/storage/codici-unita-amministrative/Elenco-denominazioni-precedenti.zip ) e nel caso particolare il codice 065512 è stato assegnato alla denominazione 'Contursi' non più in uso. 
Il codice denominazione **non è un codice identificativo del comune (codice istat del comune)**: nel caso specifico il comune ha sempre conservato il suo codice istat originale '065046' (vedere sito ufficiale di Istat https://sistat.istat.it cercando il comune per codice '065046').
Cordiali saluti.
