### ISSUE TITLE
[1002] Iscrizione con provenienza da territori esteri

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1435]
Buongiorno,
stiamo provando in ambiente di TEST a fare un'iscrizione con provenienza da un territorio estero (es. ISOLA DI ARUBA) ma otteniamo l'errore EC182 - Stato estero di provenienza  603 inesistente sulla tabella di riferimento.
Come deve essere impostato il tag provenienza? l'id operazione ANPR è il 19860369
Ringrazio anticipatamente
Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
dovete impostare codice e descrizione dello stato sovrano
232 - PAESI BASSI. Nella località lasciate ISOLA DI ARUBA

N. Capozzi
