### ISSUE TITLE
[A002] Errore di congruenza

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1436]
Buongiorno,
in data 11/06, in ambiente di produzione, il Comune di Torino ha provato ad effettuare un'iscrizione all'AIRE di due soggetti irreperibili tramite il nostro sw anagrafico. La risposta del servizio A002 è la seguente

```            
<errore>
   <codiceErroreAnomalia>EAV92</codiceErroreAnomalia>
   <tipoErroreAnomalia>E</tipoErroreAnomalia>
   <testoErroreAnomalia>Errore di congruenza</testoErroreAnomalia>
</errore>
<errore>
   <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
   <tipoErroreAnomalia>E</tipoErroreAnomalia>
   <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-06-11 10:51:31 , idOperazioneANPR 94769657</testoErroreAnomalia>
</errore>
```
L'operazione è stata rieseguita da WebApp ed è transitata correttamente: idOperazioneANPR 94784052
Confrontando gli xml abbiamo notato che nell'xml della WebApp è presente un controllo in più:
```
<controllo> 
   <codice>RE</codice> 
   <valore>1</valore> 
</controllo> 
```
Non abbiamo trovato traccia di questo controllo nella documentazione ufficiale. Avremmo quindi bisogno di chiarimenti sul perchè di questo errore ed infine sul controllo con codice RE del quale non riusciamo a trovare documentazione.

Grazie, cordialmente
Chiara Leanza per il Comune di Torino

**Comment by ncapozzi** [comment]
Buongiorno,
il rpoblema era dovuto al fatto che avete effettuato in sequenza una cancellazione (94767128) e una reiscrizione AIRE. Il primo tentativo è andato in errore perché Agenzia Entrate non aveva ancora elaborato la notifica della cancellazione e pertanto il CF risultava ancora marcato.

N. Capozzi
