### ISSUE TITLE
Ambienti ANPR: indicazioni debug applicazioni per Software House

### ISSUE THREAD

**Issue by antonioluberto** [italia/anpr#1438]
Con riferimento al quesito https://github.com/italia/anpr/issues/1408, un ultimo chiarimento: 
per l'analisi di errori (eventualmente bloccanti) che il Comune dovesse riscontrare in ambiente di Pre-Subentro (ovvero di Produzione) è sostenibile l'ipotesi per la quale la Software House esegua il debug delle proprie applicazioni:
a) attivando il collegamento remoto su postazione comunale che temporaneamente ospiti l'ambiente di sviluppo
b) eseguendo, fornendone piena evidenza all'Ente, l'invocazione dei servizi ANPR secondo:
- le credenziali (utenza, codice fiscale) corrispondenti a specifico utente comunale
- il certificato di postazione corrispondente al client di cui al punto a)

?

Ringraziando sin d'ora per le indicazioni che vorrete fornirci, porgo cordiali saluti.

Antonio Luberto
Information systems analyst
Dedagroup Public Services
T 0461 997144 | M 348 1501304 | VoIP 900144
Dedagroup Public Services Srl – Sede di Trento, Loc. Palazzine 120/f
www.dedagroup.it

**Comment by rvinzani** [comment]
Buonasera, gli ambienti di produzione e presubentro sono dal 15 luglio accessibili ai soli utenti comunali. Per risolvere eventuali problemi di produzione l'indicazione è quella di riprodurre il caso in ambiente di test dove è possibile accedere con un utenza nominale anche dalla software house.
Chiudo la issue. In caso di richiesta di ulteriori chiarimenti aprirne un'altra facendo riferimento a questa stessa.
