### ISSUE TITLE
EC030 Stato estero di nascita 999 inesistente sulla tabella di riferimento

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1439]
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-09 10:25:43 , idOperazioneANPR 102732895

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
