### ISSUE TITLE
cittadino marcato ANPR - indirizzo non allineato

### ISSUE THREAD

**Issue by diegomediglia** [italia/anpr#1440]
buongiorno!
un cittadino è presente, all'atto del subentro, in 3 comuni (2 oltre il mio) con medesimo codice fiscale; nei due comuni di precedente residenza aveva il cognome con una lettera diversa rispetto a quello con cui fu iscritto in questo comune.
I due comuni interessati hanno proceduto alla cancellazione, per doppia iscrizione, dello stesso (dal comune X al comune Y con la decorrenza corretta; e poi dal comune Y a questo comune); io ho perfezionato iscrizione anagrafica e poi corretto il cognome del cittadino come da mie risultanze.
Quindi, in ANPR ci sono tre posizione riferite al medesimo CF (24016050, 29933760 e 62111930) di cui due chiuse (con il vecchio cognome).
Il mio problema è che il cittadino, in AdE, risulta Marcato ANPR con il cognome giusto (corretto da me) ma indirizzo ancora del comune di provenienza e non capisco come possa sistemarlo visto che in ANPR è tutto corretto!
grazie mille, cordiali saluti

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
