### ISSUE TITLE
dati genitori su CIE

### ISSUE THREAD

**Issue by ComuneSegrate** [italia/anpr#1442]
Buongiorno, da alcuni giorni il collegamento CIE/ANPR non ci riporta la maternità e la paternità su alcune CIE. Questo problema non si verifica su tutti i minori; abbiamo contattato l'assistenza CIE che ci ha fatto effettuare alcune prove, vi riporto un paio di codici per farvi fare delle verifiche:

codice individuo: 42803343 non vengono importati i dati dei genitori in tutte e 3 le postazioni CIE
codice individuo: 60780325 vengono importati i dati dei genitori in tutte e 3 le postazioni CIE

L'assistenza CIE ha riferito che il problema del mancato inserimento, essendo esteso in tutte le postazioni CIE, dipende da SOGEI.
I minori a cui stiamo caricando a mano i nominativi dei genitori sono parecchi e questo ci espone a possibili errori.
Come è possibile risolvere il problema?
Grazie in anticipo!
Mario Ubbiali - Comune di Segrate (subentrati a dicembre 2018)

**Comment by rvinzani** [comment]
Verifichiamo con il Poligrafico questa segnalazione

**Comment by rvinzani** [comment]
In data successiva alle prove effettuate dal comune per l'emissione della CIE ai minori è stata rilasciata dal poligrafico una nuova versione che dovrebbe risolvere il problema.
Chiudo pertanto la issue. Se necessari ulteriori chiarimenti è possibile aprirne una nuova che faccia riferimento a questa stessa.
