### ISSUE TITLE
Emissione di CIE a soggetto errato

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#1443]
Buongiorno,
Sono Nozzoli Arianna del CED del Comune di Prato in ANPR di produzione.
Ho due casi simili:
CASO 1) E' stata emessa una carta CIE al marito con la foto della moglie perchè in realtà la CIE andava fatta alla moglie. L'impegato si è accorto dell'errore quando i cittadini erano già usciti dall'ufficio. Quindi li ha richiamati e 3 giorni dopo ha annullato la CIE sia sul nostro gestionale (sicraweb) che sul portale del ministero CIE online. Questa operazione riporta come valida la carta cartacea che il marito ha ancora. Sul nostro gestionale infatti vedo a lui associata come carta valida la cartacea. In ANPR vedo che nei documenti ha la CIE con data di annullamento e la cartacea la vedo nello storico. Questo mi comporta un disallineamento di dati sicraweb/ANPR che non riesco a risolvere
CASO 2) A differenza del caso 1 è stata emessa per errore una CIE ad un soggetto che non si è mai presentato allo sportello. E' stata annullata nel portale di ministero CIE online dopo diversi giorni dall'emissione. Vorrei eliminare del tutto l'informazione su ANPR perchè il soggetto non ha mai avuto in mano quella CIE. 
Grazie
Arianna Nozzoli
Tecnico Informatico 
Comune di Prato

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
