### ISSUE TITLE
[A002] Richiesta chiarimenti controllo con codice RE

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1444]
Nella issue #1436 stavamo chiedendo anche chiarimenti sul codice RE presente nella lista controlli. Forse vi è sfuggito.

Attendiamo delucidazioni, grazie.
Chiara Leanza per il comune di Torino

**Comment by ncapozzi** [comment]
Buongiorno,
è un controllo ad uso esclusivo della web app e per questo motivo non è documentato.
N. Capozzi
