### ISSUE TITLE
[2003] errore 999

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1446]
Ambiente di produzione, comune di Bergamo

Tentando di eseguire una cancellazione con servizio 2003 otteniamo l'errore "999 operazione non effettuabile" (id operazione ANPR 103088153)

Cosa significa ?
Qual è il problema ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by fferraguto** [comment]
La correttiva sarà disponibile da lunedì prossimo.
Saluti
