### ISSUE TITLE
[5008] errore 999

### ISSUE THREAD

**Issue by StefanoGuidetti** [italia/anpr#1447]
Buonasera
il cliente, ha eseguito una mutazione 5008
che ha dato esito negativo, con tutti i problemi del caso

```
          <idOperazioneComune>25849</idOperazioneComune>
          <codMittente>044066</codMittente>
          <codDestinatario>ANPR02</codDestinatario>
          <operazioneRichiesta>5008</operazioneRichiesta>
          <dataOraRichiesta>2019-07-11T10:26:52.191+02:00</dataOraRichiesta>
```
```
          <errore>
            <codiceErroreAnomalia>999</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
          </errore>
          <errore>
            <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-11 10:26:52 , mittente 044066 , idOperazioneComune 25849</testoErroreAnomalia>
          </errore>
```

eseguita nuovamente l'operazione ha avuto esito 0000
idOperazioneANPR ->  103214574

non riusciamo a capire il motivo.

Resto in attesa di chiarimenti
Grazie
Stefano di PAL

**Comment by mttfranci** [comment]
C’è stato un problema temporaneo nel software, abbiamo già preso rilasciato una piccola patch per cercare di limitare il problema e rendere più semplice la diagnosi in futuro. 

Tale patch è in test / presubentro (5.5.1) e lunedì dovrebbe essere trasferita in ambiente di produzione.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
