### ISSUE TITLE
Iscrizione da comune non subentrato (già cancellato in precedenza da ANPR)

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1448]
Buongiorno, un nostro cliente ha un problema in una pratica di iscrizione da comune non subentrato.
Questo soggetto però, era precedentemente iscritto in un comune subentrato in ANPR, quindi ha già acquisito nel sistema l'id ANPR.
Successivamente è stato cancellato dal comune subentrato per un comune non subentrato.
Ora deve essere nuovamente iscritto in un nuovo comune già subentrato in ANPR: dal nostro gestionale abbiamo recuperato i dati da ANPR ed effettuato tutte le normali operazioni per effettuare l'iscrizione. 
Al momento della chiusura della pratica però si è presentata l'anomalia "idSchedaSoggettoANPR non è presente o dati anagrafici incongruenti".
Dopo alcune prove su questo soggetto, abbiamo riprodotto su ambiente di test la stessa situazione ed è andata a buon fine.

I dati delle richieste sono questi:
Richiesta andata a buon fine su ambiente di test:
IDOperazioneComune: 12730
idSchedaSoggettoANPR: 26035260

Richiesta non andata a buon fine in produzione:
IDOperazioneComune: 4107
idSchedaSoggettoANPR: 27288919

Potete fare una verifica su quest'ultima trasmissione e darci indicazioni in merito?
Grazie
Marco Sala
Pa Digitale Spa

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
