### ISSUE TITLE
Scarico ANPR per motivata richiesta - Procedimenti

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1449]
In caso di perdita dei dati locali vengono perduti anche gli identificativi dei procedimenti che sono aperti in ANPR al momento del crash.
E' possibile ottenere insieme al file di scarico anche un elenco dei procedimenti aperti?
Grazie
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Al momento non è previsto di includere anche i dati dei provvedimenti nello scarico.
Sottoporremo al Ministero la vostra richiesta.
Siamo a disposizione per ogni ulteriore chiarimento.

Cordiali saluti

Assistenza ANPR
