### ISSUE TITLE
Web App - Cancellazione da schedario popolazione temporanea

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#145]
Ambiente di test - data test 03/05/2017
Tentando di effettuare la cancellazione di un soggetto iscritto nello schedario della popolazione temporanea, è stata restituito il messaggio di conferma conclusione operazione ed è stato prodotto il pdf riepilogativo che include la conferma della cancellazione. Tuttavia, rieseguendo la ricerca del soggetto, continua a risultare iscritto. 
Grazie,
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Ricontrollando i casi registrati con l’id di Torino nella tabella dei Residenti Temporanei, risulta che solo per il soggetto avente  cf BCCVNT81M54B885E risulta:

•	 una registrazione nello schedario dei residenti temporanei
•	 una mutazione del tab Residenza e il permesso di Soggiorno

ma non risulta alcuna Cancellazione.
Abbiamo con un altro caso:
•	registrato un soggetto nello schedario 
•	lo abbiamo cancellato dallo schedario
•	lo abbiamo interrogato di nuovo e risulta cancellato. 

Possiamo fare una verifica utilizzando anche l'assistenza remota.
Mi dovrebbe contattare telefonicamente

**Comment by VBocchinoTO** [comment]
Ho rieseguito il test sul soggetto BCCVNT81M54B885E ed ora la cancellazione risulta correttamente eseguita anche dalla consultazione. Grazie.
