### ISSUE TITLE
Dati genitori su CIE - Riapertura issue #1442

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1450]
Buongiorno,
mi riallaccio alla issue [#1442](https://github.com/italia/anpr/issues/1442) aperta dal comune di Segrate in quanto ancora oggi l'inserimento dei genitori non funziona.
Nelle news della postazione CIE alla data del 30 giugno è indicato un aggiornamento che dice anche che è stata effettuata un'ottimizzazione nella valorizzazione dei genitori per il rolascio della CIE ai minori. Sarà una concomitanza, ma da questo aggiornamento i genitori non vengono più compilati automaticamente.

Attendo aggiornamenti

Grazie

**Comment by rvinzani** [comment]
Per i problemi sulla CIE potete rivolgervi al servizio di assistenza dedicato
cie.comuni@interno.it
Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
