### ISSUE TITLE
Problema accesso a sito da tutti i pc del cliente

### ISSUE THREAD

**Issue by xavehoo** [italia/anpr#1451]
Salve,
un nostro cliente (un comune) ha un problema di accesso al sito da tutti i pc; la richiesta va in timeout.
Se però, invece di digitare https://dp.anpr.interno.it/com , viene digitato https://dp2.anpr.interno.it/com , viene richiesto correttamente di selezionare il certificato, ed in seguito di inserire il pin; fatto ciò, il server però risponde con un errore (XML), dove è specificato che "_postazione certificate does not seem to carry a valid cn name_" (sia da una postazione che su un'altra avviene la medesima situazione).
Avete suggerimenti su quale potrebbe essere il problema?
Grazie

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
