### ISSUE TITLE
Errore EF001

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1453]
Non riusciamo a fare l'evento di iscrizione preliminare per un cittadino cinese. 
ERRORE DA ANPR: 
EF001 - Identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-12 12:46:16 , idOperazioneANPR 103487995 
Comune di Altamura

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
