### ISSUE TITLE
Disallineamento comune nascita su AE

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1454]
Comune di Modena - Ambiente di Produzione

Buongiorno,
abbiamo iscritto il soggetto con idANPR 53162752 con comune di nascita SERRAMAZZONI  come indicato dal comune di provenienza; abbiamo poi dovuto rettificare il luogo di nascita poichè nel 1945 la denominazione corretta era MONFESTINO IN SERRAMAZZONI. 
Abbiamo usato la risoluzione disallineamenti per aggiornare anche AE ed apparentemente ha funzionato, ma consultando Puntofisco il soggetto risulta ancora nato a SERRAMAZZONI, e come lui anche altri nelle sue stesse condizioni. Stranamente se si consulta AE dalla funzione interna ad ANPR il luogo nascita viene visualizzato correttamente.
Come mai AE non mostra la denominazione storica corretta?

Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Gent.le Sig.ra Fiorini, lo scorso 15 giugno è stato effettuato un intervento sui servizi di AE per acquisire sui loro sistemi, oltre al codice catastale anche la denominazione presente in ANPR che a volte differisce a parità di codice. Questo modifica della dizione del comune non è da subito evidente in punto fisco. Nel caso il cittadino la volesse modificare anche sul suo tesserino sanitario e su tutti i sistemi di AE deve farne esplicita richiesta ad Agenzia Entrate.
L'interrogazione invece utilizzata dalla web app mostra la denominazione allineata ad ANPR.
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti è possibile riaprirne una nuova che faccia riferimento a questa stessa
