### ISSUE TITLE
[1002] EN185 in re-iscrizione

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1455]
Buongiorno al comune di BORGORICCO (produzione) c'è un problema simile a #1415 in pratica segnala EN185 per la scheda  43259893, ma non riusciamo a capire cosa sia incongruente.
ID Operazione ANPR 103483581.

secondo me c'è anche stata un'errata gestione del ripristino dal comune di Milano perché il soggetto è emigrato a marzo da Borgoricco a Milano (entrambi subentrati) a Giugno Milano rigettando l'iscrizione avrebbe dovuto fare un annullamento 5012 invece ha fatto una 2003 per ripristino posizione, quindi al Comune di Borgoricco è arrivata una notifica N014 invece che N015, per questo adesso lo stiamo re-iscrivendo con una 1002.

Saluti
Riccardo

**Comment by rvinzani** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
