### ISSUE TITLE
Da oggi 15/07: messaggio ambiguo su caricamento file di subentro in ambiente di pre-subentro

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1457]
Stamane, tentando di caricare il file di subentro nell'ambiente di pre-subentro, si ha questo messaggio:

"Gentile utente, 
ti informiamo che stai inoltrando il "file di subentro" in ambiente di PRE_SUBENTRO che è l'ambiente di prova per verificare le eventuali anomalie."

E fin qui è un avviso chiaro; ma poi il messaggio prosegue così:

"Prima di procedere ti chiediamo di verificare che il subentro sia programmato per la giornata odierna infatti dopo l'invio del file non SARA' POSSIBILE ANNULLARE IL SUBENTRO.
Se intendi confermare il pre-subentro nella BANCA DATI NAZIONALE ANPR, procedi con l'invio del file cliccando il tasto CONFERMA."

Essendo un caricamento in ambiente di pre-subentro, perché si invita a verificare che il subentro definitivo sia programmato per la giornata odierna?

I Comuni ci stanno chiamando disorientati dal messaggio: possiamo indicare di rispondere CONFERMA senza problemi?

Grazie

**Comment by mttfranci** [comment]
Salve, grazie della segnalazione, si tratta di un refuso che è già stato corretto.
Confermiamo che è sempre possibile annullare il presubentro.
Solo in ambiente di produzione il subentro non è reversibile.

Adesso il messaggio si ferma con : 
"Gentile utente,
ti informiamo che stai inoltrando il "file di subentro" in ambiente di PRE_SUBENTRO che è l'ambiente di prova per verificare le eventuali anomalie."

Saluti

Assistenza ANPR
