### ISSUE TITLE
Comuni cessati per costituzione nuova provincia

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1458]
Per i comuni cessati per la costituzione di una nuova provincia, in SISTAT sono presenti due record: uno per il cambio di provincia e uno per la cessazione, entrambe con data di inizio e fine uguale. Ad esempio:

Codice ISTAT|Inizio|Fine|Denominazione
-|-|-|-
010877|12/01/1927|12/01/1927|Finalborgo
009813|12/01/1927|12/01/1927|Finalborgo

In ANPR i record relativi ai cambi di provincia sono stati scartati con l'eccezione di _Salcano_ e _San Pietro di Gorizia_:

ID|DATAISTITUZIONE|DATACESSAZIONE|CODISTAT|DENOMINAZIONE_IT
-|-|-|-|-
20402|08/02/1923|10/01/1927|030907|SALCANO
22989|11/01/1927|11/01/1927|031807|SALCANO
8800|27/04/1923|10/01/1927|030914|SAN PIETRO DI GORIZIA
22990|11/01/1927|11/01/1927|031808|SAN PIETRO DI GORIZIA

Esiste una motivazione per aver mantenuto questi due o si tratta di un refuso?

L'elenco completo dei comuni che hanno questa situazione in SISTAT è:

Codice ISTAT|Denominazione
-|-
009813|Finalborgo
009814|Finale Marina
009815|Finale Pia
018816|Cantonale
031804|Lucinico
031805|Piedimonte del Calvario
031807|Salcano
031808|San Pietro di Gorizia
031809|Sant'Andrea di Gorizia
055031|Stroncone
055804|Cesi
055805|Collescipoli
055806|Collestatte
055809|Papigno
055810|Piediluco
055814|Torre Orsina
068801|Castellammare Adriatico
088801|Ragusa Ibla
702802|Occisla-Clanzo

**Comment by MassimoSchiappa** [comment]
Salve,
in generale se cambia il codice istat di un comune, ANPR deve avere in tabella i record corrispondenti al periodo precedente e a quello seguente il cambio, quindi probabilmente, nel merito della sua domanda, alcuni record sarebbero assenti e quelli presenti invece è corretto che ci siano. Provvederemo ad una verifica puntuale e all'eventuale aggiornamento della tabella dei comuni. 
Grazie per la segnalazione.
