### ISSUE TITLE
Comuni con doppia denominazione Italiano/Sloveno

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1459]
Con [Decreto del Presidente della Regione 18 dicembre 2008, n. 0346/Pres](https://bur.regione.fvg.it/newbur/visionaBUR?bnum=2009/01/14/2) è stata aggiunta la denominazione in Sloveno ai comuni di _Doberdò del Lago_, _Duino Aurisina_, _Monrupino_, _San Floriano del Collio_, _Savogna d'Isonzo_ e _Sgonico_. In SISTAT questo cambio è stato storicizzato mentre in ANPR non è stato fatto e si è applicata la doppia denominazione in modo retroattivo. Ad esempio:

ID|DATAISTITUZIONE|DATACESSAZIONE|CODISTAT|DENOMINAZIONE_IT|ALTRADENOMINAZIONE
-|-|-|-|-|-
16576|05/01/1921|07/02/1923|801064|DOBERDÒ|
16577|08/02/1923|26/04/1923|032818|DOBERDÒ|
16578|27/04/1923|15/09/1947|032818|DOBERDÒ DEL LAGO|
16579|16/09/1947|09/01/1948|032818|DOBERDÒ DEL LAGO|
16580|10/01/1948|14/02/1951|031003|DOBERDÒ DEL LAGO|DOBERDOB
3576|15/02/1951|31/12/9999|031003|DOBERDÒ DEL LAGO|DOBERDOB

Qual è stata la motivazione per questa scelta discorde da quella di ISTAT?

**Comment by MassimoSchiappa** [comment]
Salve, si tratta di un errore materiale, provvederemo a correggere e alla prossima pubblicazione della tabella dei comuni.
Grazie per la segnalazione.
