### ISSUE TITLE
[5008] - Mutazione 19 - errore su scioglimento unione civile

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#146]
Pisa, 04/05/2017, ambiente di test, ID operazione ANPR 480735

Buongiorno,
nell'ambiente di test di Pisa abbiamo registrato lo scioglimento di un'unione civile per accordo (motivo 1) inviato ad ANPR tramite il servizio 5008 con tipo mutazione 19.
L'evento non viene registrato e ci perviene l'errore EN278: E' necessario specificare i dati obbligatori per lo scioglimento: motivo scioglimento, sentenza o atto. 
Nell'xml però ci sembra che ci sia tutto quanto richiesto dalla documentazione, cioè i dati dell'unione, il motivo di scioglimento e l'atto di scioglimento. Potete verificare come mai otteniamo questa risposta?
Allego alla presente il file xml inviato e la risposta, grazie.
Luca Bonini A.P.Systems
[5008_pisa9732.zip](https://github.com/italia/anpr/files/976107/5008_pisa9732.zip)

**Comment by gcarbonin** [comment]
Come già anticipato, stiamo lavorando per spostare il controllo della congruenza delle date sulla singola mutazione e non sulla scheda. Nella attuale versione, in modo coerente alle specifiche, il sistema accetta una data non minore escludendo emissione della carta di identità, mutazione degli altri dati e variazione di residenza nel comune, Avvertiamo quando possibile riprovare.
