### ISSUE TITLE
Errore inserimento comune di provenienza

### ISSUE THREAD

**Issue by paoloand** [italia/anpr#1460]
Comune di pomigliano, subentrato. 
Buonasera, a seguito di un procedimento di iscrizione anagrafica è stato inserito erroneamente  il comune di provenienza sbagliato. È possibile correggere tale errore in webapp impostando il corretto comune di provenienza? Si precisa che il comune di provenienza corretto non è subentrato.

**Comment by FilippoPapi** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
