### ISSUE TITLE
Problema comune precedente di iscrizione aire

### ISSUE THREAD

**Issue by paoloand** [italia/anpr#1461]
Buonasera durante il procedimento di iscrizione anagrafica per rimpatrio Aire, è stato erroneamente inserito come comune di precedente iscrizione aire un diverso comune. Tale operazione è sanabile oppure è necessario annullare la pratica di iscrizione e rifarla da capo?
 Cordiali saluti

**Comment by FilippoPapi** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116
