### ISSUE TITLE
Estrazione elenchi cittadini - EN148

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1463]
Comune 017065 - Ambiente di test
Con la WA accedo a Consultazione ed Estrazione / Estrazione Elenchi Cittadini
Nella sezione Ulteriori Criteri di Selezione imposto il valore "Apertura Procedimento Amministrativo" nel campo "Stato Istruttoria", nella sezione Dati Richiesti accendo la spunta su "Generalità" e premo Conferma.
Ottengo in risposta: EN148 L'id operazione client/comune deve essere diverso da 0.
Sbaglio io ad operare oppure c'è dell'altro?

Grazie - saluti.
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Dovremmo avere individuato il problema.
Potreste riprovare?

Saluti

Assistenza ANPR

**Comment by bfilipazzi** [comment]
Ho riprovato, la WA mi ha invitato a valorizzare la data di riferimento, cosa che ho fatto, il risultato è questo: EN177 La selezione per stato istruttoria non e' attiva.
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Il comportamento appare corretto.
L'estrazione con tale parametro in effetti è disabilitata.
