### ISSUE TITLE
Download dati ANPR del comune - Tempi di scarico

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1464]
Nella issue #1357 si legge che la funzionalità di scarico dei dati del comune è nella fase di tuning, e che si prevede una risposta entro 24 h sotto i 200.000 abitanti.
La fase di tuning è terminata?
L'8 luglio alle 12:00 un comune con 130.000 abitanti ha chiesto lo scarico (da produzione) e ha ottenuto il file l'11 luglio alle 17:30, 77 ore dopo.
Grazie - saluti.
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Salve, nel caso specifico c'e' stato un errore che non è stato rilevato subito e ha causato il ritardo.
Il bug che ha causato tale errore è stato risolto e speriamo che il problema non capiti in futuro.
Il tuning della procedura di scarico massivo dovrebbe essere terminato.

Ricordiamo che tale procedura andrebbe però attivata solo in casi eccezionali.
Nel caso capiti nuovamente che abbiate necessità di tale operazione e non si completi entro 24h vi suggeriamo di aprire una issue.

Saluti

Assistenza ANPR
