### ISSUE TITLE
Certificazione EN209

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1466]
Ambiente produzione. Comune Desenzano del Garda.
Da ieri gli segnala per un certificato anpr, l'errore:
_Importo diritti segreteria deve essere maggiore di 0,00 euro (Codice: EN209)_
nelle impostazioni di amministrazione wa, hanno spuntato "Certificati esenti dai diritti di segreteria".
Provato anche dalla wa, e da errore con importo diritti segreteria 0,00
Mi sembra un errore, potete controllare anche voi?

PS: abbiamo spuntato ora anche "Esenzione diritti per certificati online", che in precedenza (da aprile) non era spuntato, e riusciamo a fare l'emissione, ma anche qui non sono convinto sia corretto.

**Comment by rnapoli1983** [comment]
Buongiorno abbiamo controllato a sistema le richieste da voi effettuate e sono richieste di anteprima di certificato.

C'è una issue specifica (#1411) che descrive la logica di questa modalità.

Cordiali saluti.

**Comment by MarcoMigliori** [comment]
Ok grazie.
