### ISSUE TITLE
Lillianes e Fontainemore

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1468]
Con [Delibera 21 marzo 1946, n. 34](http://www.consiglio.vda.it/app/oggettidelconsiglio/dettaglio?pk_documento=25094) venne ricostituito il comune di _Fontainemore_ per distacco dal comune di _Lilliana_ che riassunse la denominazione frances _Lillianes_. Le date seguenti non risultano quindi coerenti:

ID | DATAISTITUZIONE | DATACESSAZIONE | DENOMINAZIONE_ID
-|-|-|-
22139|24/01/1929|24/03/1946|LILLIANA
3971|10/03/1946|31/12/9999|FONTAINEMORE
4970|25/03/1946|31/12/9999|LILLIANES

In ISTAT le date sono coerenti (10/03/1946) mentre in ANPR sono state modificate perdendo la coerenza.

**Comment by MassimoSchiappa** [comment]
Salve,
procederemo appena possibile alla correzione.
Grazie per la segnalazione.
