### ISSUE TITLE
Rhemes Notre Dame e Rhemes Saint Georges

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1469]
Con [Delibera 7 marzo 1946, n. 24](http://www.consiglio.vda.it/app/oggettidelconsiglio/dettaglio?pk_documento=25084) venne ricostituito il comune di _Rhemes Notre Dame_ per distacco dal comune di _Rhemes_ che riassunse la denominazione _Rhemes Saint Georges_. Le date seguenti non risultano quindi coerenti:

ID | DATAISTITUZIONE | DATACESSAZIONE | DENOMINAZIONE_ID
-|-|-|-
22210|30/01/1946|25/03/1946|RHEMES
22212|10/03/1946|01/01/1977|RHEMES NOTRE DAME
22215|10/03/1946|01/01/1977|RHEMES SAINT GEORGES

In ISTAT le date sono coerenti (10/03/1946) mentre in ANPR sono state modificate perdendo la coerenza.

**Comment by MassimoSchiappa** [comment]
Salve,
appena possibile provvederemo alla correzione della tabella dei comuni.
Grazie per la segnalazione.
