### ISSUE TITLE
Iscrizione di più soggetti, ripristino parziale ai controlli amministrativi

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#147]
Buongiorno
Se ho fatto una iscrizione di una famiglia composta da più persone, e all'atto dei controlli amministrativi emerge che uno dei componenti della pratica non risulta residente all'indirizzo, è corretto gestire l'evento tramite l'annullamento?
Potrei aver fatto l'iscrizione con 1002 o 5001 o 5005 a seconda delle casistiche,  quindi annullerei con 1013 o 5012 il solo soggetto assente (ripristino parziale). Il dubbio è  nella correttezza del procedimento. dal punto di vista tecnico raggiungo il risultato dalle prove fatte.

**Comment by rvinzani** [comment]
In caso di iscrizione (1002/A002) si deve procedere con la cancellazione per ripristino (2003 –motivo cancellazione = 10)
Per le mutazioni di residenza (5005/5001) si deve procedere con l'annullamento della mutazione (5012)eventualmente parziale, cioè di uno solo dei soggetti mutati (solo se si è utilizzato il servizio 5005)
