### ISSUE TITLE
Impossibile accedere alla WebApp di presubentro

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1471]
Buongiorno,
dal 15 luglio non è più possibile accedere alla WebApp di presubentro. Abbiamo provato l'accesso tramite due link:
https://webpre.anpr.interno.it/ANPRWEB/
https://dppre2.anpr.interno.it/com

Il primo chiede username e password, cosa che non ci aspettavamo di trovare dopo le modifiche da voi introdotte.
Il secondo chiede il certificato digitale della smart card di produzione e conseguentemente il pin. Dopo averli inseriti, però, compare il seguente messaggio:

> Si e' verificato un errore durante la fase di autenticazione
> 
> Si è verificato un errore di comunicazione nella fase di autenticazione
> Possibili ritardi nell'inserimento delle credenziali
> 
> E' possibile riprovare selezionando il link portal home page

Siamo sicuri che gli utenti che hanno provato ad accedere siano abilitati in quanto il Comune di Torino ci ha esplicitato i nominativi abilitati tramite console. 

Rimaniamo in attesa di un vostro cortese riscontro.
Cordiali saluti
Chiara Leanza per il Comune di Torino

**Comment by rvinzani** [comment]
Buonasera, il link corretto è
https://dppre.anpr.interno.it/com
bisogna assicurarsi che sulla postazione sia installato un certificato di postazione di produzione, che siano installati i driver per la smart card e che sia presente un lettore ed una smart card inserita

**Comment by chiaralea** [comment]
Adesso funziona, grazie mille.

Buona serata,
Chiara Leanza
