### ISSUE TITLE
Interrogazione dati ANPR

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1472]
Buongiorno, 
volevo chiedervi informazioni in merito all'interrogazione dei dati ANPR.

Noi abbiamo una serie di clienti che, all'interno della nostra soluzione software, hanno attivo il modulo  dei servizi sociali piuttosto che i servizi a domanda individuale (ecc ecc) ma non hanno attivo il modulo dei servizi demografici.

Questi clienti sono già subentrati in ANPR e quindi gestiscono l'anagrafe con un'altra software house: quello che vorrei sapere è se è fattibile attivare, per questi clienti, anche il nostro modulo di anagrafe (solo per le interrogazioni) ed utilizzare gli stessi certificati di postazione che il cliente già utilizza per il collegamento ANPR con il modulo demografico dell'altra software house.

Parliamo solo di interrogazione dei dati, per la gestione ovviamente tutto rimane con la software house che ha in gestione completa il modulo demografico sul cliente.

Grazie per le informazioni.

**Comment by gife67** [comment]
Buonasera,
la gestione dei moduli software è qualcosa di relativo ai gestionali comunali di cui noi non abbiamo assolutamente visibilità, quindi rischierei di fornirle delle informazioni errate. Per quanto riguarda l'utilizzo dei certificati di postazione questi sono specifici per Comune, infatti riportano il codice ISTAT dello stesso. Quindi se il Comune è subentrato, è autorizzato ad accedere alla piattaforma completa dei WS, indipendentemente dal client utilizzato e di conseguenza dal modulo software che state utilizzando, l'importante che venga opportunamente composta la cornice di sicurezza prevista per instaurare il colloquio con i WS. Ovviamente è opportuno che rendiate consapevole il Comune della soluzione mista che state adottando e dell'uso dei certificati di postazione che eventualmente utilizzerete e che sono sotto responsabilità delle persone nominate come ALP e ALS dal Sindaco.
Spero di essere stato chiaro e di aver risposto ai suoi quesiti.
Cordiali Saluti
