### ISSUE TITLE
Subentro in ambiente di test sempre in elaborazione

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#1474]
Subentro in ambiente di test Sala Bolognese

Buongiorno,
ieri abbiamo subentrato in ambiente di test il comune di Sala Bolognese.
Nonostante ci sia arrivata la mail di operazione terminata con successo(n. protocollo 19893611), la ricerca di un APR ci segnala l'errore EN122 La richiesta effettuata non produce alcun risultato. La ricerca  Aire funziona correttamente.

Nella sezione esiti subentro lo stato risulta sempre in elaborazione nonostante sia presente la risposta con gli ID ANPR.

Potete dirci che sta succedendo?

Grazie mille
Tiziana Testa
Insiel Mercato

**Comment by FilippoPapi** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.

**Comment by mccalv** [comment]
@FilippoPapi @TizianaTesta potreste fornire indicazioni sulla natura dell'errore? Grazie

**Comment by TizianaTesta** [comment]
La situazione è che nella web app di test, sezione Esiti del subentro, l'elaborazione del file APR risulta in elaborazione, è arrivata la mail che conferma la correttezza del subentro, gli ID ANPR  sono disponibili però effettuando delle ricerche non trova nessuna persona. Errore EN122 La richiesta effettuata non produce alcun risultato. Per gli Aire, lo stato dell'elaborazione è Elaborato e le persone vengono trovate in fase di ricerca.  Stamattina ho chiamato il numero verde che però non ha saputo darmi alcuna risposta. Abbiamo subentrato anche il comune di Ponsacco sempre in ambiente di test senza problemi.

**Comment by amollicone1982** [comment]
Si è verificato un problema tecnico che è stato risolto. potete procedere con le consultazioni

**Comment by TizianaTesta** [comment]
Adesso funziona grazie mille
