### ISSUE TITLE
[A006] Cambio indirizzo, azzera id scheda soggetto comune

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1475]
Ambiente di produzione, id anpr 59263357, cittadino aire.
Con operazione A006 id anpr 1046586 + operazione 5001 id anpr 104659060 , abbiamo cambiato l'indirizzo al cittadino costituendo una nuova famiglia.  
Adesso ci troviamo consultando la scheda soggetto attuale, senza il ramo  **idSchedaSoggettoComune** .
Quel ramo era da noi stato modificato in precedenza, impostando l'attributo idSchedaSoggetto, alla matricola del nostro applicativo, in luogo del numero di iscrizione aire.
Se consulto la scheda cittadino al 1 luglio, data precedente alla operazione, vedo infatti i campi presenti.

Non riesco a capire se si tratta di una anomalia, o se dovevamo comportarci diversamente in qualche passaggio di parametri,

**Comment by frmariani** [comment]
il bug è stato risolto, ed è già disponibile in ambiente di produzione.
La issue viene pertanto chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa”
