### ISSUE TITLE
EAA71 - Errore formale- ISCRIZIONE AIRE A SEGUITO DI TRASCRIZIONE ATTO NASCITA 

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1476]
Buongiorno il comune di TRASACCO - produzione - ha l'errore in oggetto, ho trovato #1370 dipende dalla descrizione del toponimo <denominazione>CALLE 122</denominazione>?

Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-23 11:12:13 , idOperazioneANPR 106331664
Grazie mille
Riccardo

**Comment by ncapozzi** [comment]
Buongiorno,
come nel caso precedente, il bambino viene associato ad una famiglia registrata in ANPR con residenza avente toponimo numerico = 46. Agenzia delle Entrate non accetta il toponimo numerico ma alfanumerico.
Prima dell'iscrizione, è necessario pertanto effettuare una mutazione famiglia 5001 con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO.
N. Capozzi
