### ISSUE TITLE
[4005] Ricerca stato notifiche non funziona

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1477]
Ambiente di produzione, comune di Spresiano

Il comune ha in sospeso una lunga serie di operazioni di richiesta scarico operazioni.
Le più vecchie sono del 7 luglio.

Se oggi facciamo una richiesta 4005 di verifica stato su qualunque di esse ci viene risposto che saranno pronte in una data nel passato (vedi ad es l'operazione di verifica status ID ANPR 105452398)

Temo che ci sia qualcosa di bloccato nelle vostre tabelle.

Potete verificare ?

Grazie

**Comment by StefanoGuidetti** [comment]
Buongiorno,
anche noi abbiamo ricevuto segnalazioni simili 
Comune di San Benedetto
![image](https://user-images.githubusercontent.com/43878804/61775088-85374f80-adf8-11e9-9b4f-90b6f673cd79.png)

E in di test 
![image](https://user-images.githubusercontent.com/43878804/61774497-43f27000-adf7-11e9-9d85-dafd4e4a19b0.png)

Grazie

**Comment by mttfranci** [comment]
Salve dovremmo aver trovato il problema. Potreste riprovare?
Grazie in anticipo

**Comment by StefanoGuidetti** [comment]
Testato.
Funziona.
Grazie

**Comment by mttfranci** [comment]
Prego, ci scusiamo per i disservizio.

**Comment by busaster** [comment]
Confermo anch'io che ora funziona
