### ISSUE TITLE
Errore EN077 su cancellazione operazione da webapp

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1478]
Comune di Parma - PRODUZIONE

A causa di un malfunzionamento del programma di gestione dell'anagrafe abbiamo la necessita di eliminare l'operazione di iscrizione numero 93481669 datata 05.06.2019 legata al soggetto con id ANPR 59952457

Quando tentiamo di eliminarla però il sistema risponde 
**_"L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-12 15:50:25 , idOperazioneANPR 103534474 (Codice: EN527)"_**

Sinceramente non riesco a trovare il modo di eliminare l'operazione indicata (103534474) perché non compare per quel soggetto 

Saluti

Rossi Diego
Comune di Parma

**Comment by rvinzani** [comment]
Il soggetto risulta coniugato con un altro soggetto ANPR. L'annullamento dell'iscrizione in tal caso creerebbe delle incongruenze sul matrimonio. Potreste cancellare il soggetto per altri motivi e questo consentirebbe di lasciare in essere il matrimonio.
Sarebbe utile avere maggiori informazioni sulla necessità di eliminare il soggetto ed è per questo che vi chiediamo di rivolgervi all'assistenza ANPR (800863116) per casi specifici come questo.

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
