### ISSUE TITLE
Ambiente TEST FREE - Inserimento dati fittizi

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1479]
Buongiorno,
sto cercando di popolare l'ambiente di TEST FREE con almeno una famiglia (fittizia) di due persone, ma finora senza successo.
Se cerco di registrare un cittadino direttamente dalla sezione "Registrazione" bisogna prima cercarlo ma, ovviamente, non esiste.
Se cerco di caricare un file APR di subentro ("888180_SUBAPR_1_1_1.gz" creato ad hoc con i dati fittizi di due persone) non fa nulla e non mostra neanche nessun messaggio di errore.
Potrei avere un aiuto gentilmente? Se potete inserirli voi direttamente uno o due soggetti fittizi vi sarei molto grato.

Mi è stato assegnato il seguente comune fittizio con Codice ISTAT: 888180

Grazie

**Comment by mttfranci** [comment]
Salve, abbiamo in effetti trovato un problema nella configurazione del comune fittizio 888180.
Potreste riprovare avendo cura prima di censire la pec per la ricezione dell'esito del subentro dall'area amministrativa del comune?
Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Salve, grazie per l'aiuto. Ho appena compilato il form nella sezione "Amministrazione" con i dati richiesti. L'invio del file SUBAPR è avvenuto con successo. Aspetto per vedere il risultato. Saluti

**Comment by mttfranci** [comment]
Salve, abbiamo verificato il vostro invio.
Abbiamo visto il vostro invio.
Purtroppo il solo file APR da solo porta al completamento dell'elaborazione.
E' necessario trasmettere anche la fornitura AIRE, anche senza soggetti.

Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Salve, il vostro subentro fittizio è terminato e i dati dei due soggetti trasmessi sono correttamente consultabili.
Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Si grazie, ho appena controllato. Saluti

**Comment by Eduardo1977** [comment]
Buongiorno, esiste un modo da webapp (tramite i servizi di Registrazione) per inserire un soggetto con dati fittizi ?  Qualsiasi operazione di iscrizione richiede di dover cercare un soggetto già esistente ...
Grazie

**Comment by Eduardo1977** [comment]
Ho risolto grazie, l'inserimento funziona. Non stavo capendo io. Scusate
