### ISSUE TITLE
Risposta ANPR:codice errore 999

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#148]
Buongiorno,
in ambiente di TEST per il Comune di Bologna,
abbiamo fatto tramite web-services la richiesta di cancellazione per morte di un soggetto residente precedentemente caricato tramite il file subentro, l'applicazione ci risponde con codice errore 999 Operazione non effettuabile, di seguito l'xml di risposta:
<?xml version="1.0" encoding="UTF-8"?>
-<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
-<soapenv:Body>
-<b:Risposta2001 xmlns:a="http://sogei.it/ANPR/rispostaComune" xmlns:b="http://sogei.it/ANPR/2000cancellazione">
-<b:rispostaKO>
-<testataRisposta>
<idOperazioneComune>20170508152650555474555474F73B</idOperazioneComune>
<codMittente>037006</codMittente>
<codDestinatario>ANPR00</codDestinatario>
<operazioneRichiesta>2001</operazioneRichiesta>
<dataOraRichiesta>2017-05-08T15:26:50</dataOraRichiesta>
<protocolloComune>0</protocolloComune>
<idOperazioneANPR>482714</idOperazioneANPR>
<esitoOperazione>XXXX</esitoOperazione>
</testataRisposta>
-<listaErrori>
-<errore>
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
</listaErrori>
</b:rispostaKO>
</b:Risposta2001>
</soapenv:Body>
</soapenv:Envelope>

Non riusciamo a capire il tipo di errore.

Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by fugerit79** [comment]
Salve, potreste riprovare e darci un riscontro?
Saluti

Matteo

**Comment by ANPRCDBO** [comment]
Salve ,ora ci risponde cosi':<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><b:Risposta2001 xmlns:b="http://sogei.it/ANPR/2000cancellazione" xmlns:a="http://sogei.it/ANPR/rispostaComune"><b:rispostaKO><testataRisposta><idOperazioneComune>20170508171015646840646840F71A</idOperazioneComune><codMittente>037006</codMittente><codDestinatario>ANPR00</codDestinatario><operazioneRichiesta>2001</operazioneRichiesta><dataOraRichiesta>2017-05-08T17:10:15</dataOraRichiesta><protocolloComune>0</protocolloComune><idOperazioneANPR>482858</idOperazioneANPR><esitoOperazione>XXXX</esitoOperazione></testataRisposta><listaErrori><errore><codiceErroreAnomalia>EHR97</codiceErroreAnomalia><tipoErroreAnomalia>E</tipoErroreAnomalia><testoErroreAnomalia>Data decorrenza obbligatoria per i servizi di registrazione</testoErroreAnomalia></errore><errore><codiceErroreAnomalia>EC111</codiceErroreAnomalia><tipoErroreAnomalia>W</tipoErroreAnomalia><testoErroreAnomalia>Data di registrazione dell'atto non indicata - impossibile verificare la validita' del comune di  registrazione atto di morte per la presenza di piu' occorrenze</testoErroreAnomalia></errore></listaErrori></b:rispostaKO></b:Risposta2001></soapenv:Body></soapenv:Envelope>-----Matteo <notifications@github.com> ha scritto: -----Per: italia/anpr <anpr@noreply.github.com>Da: Matteo <notifications@github.com>Data: 08/05/2017 05.06PMCc: ANPRCDBO <SipoBologna@comune.bologna.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/anpr] Risposta ANPR:codice errore 999 (#148)Salve, potreste riprovare e darci un riscontro?
Saluti
Matteo

**Comment by fugerit79** [comment]
Salve.
Per completare l'operazione e superare l'errore EHR97 dovrebbe bastare impostare la data decorrenza nella testata richiesta (Eventualmente anche alla data odierna).
Il secondo messaggio (EC111) è solo una segnalazione e può essere ignorato. Se volete evitare anche tale messaggio dovrebbe essere sufficiente impostare il codice istat del comune nell'elemento <comune> del <luogoEvento>.
Saluti

Matteo
