### ISSUE TITLE
Modifica luogo di nascita a persona deceduta

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1480]
COMUNE di PARMA - PRODUZIONE

Buongiorno,

ho la necessità di modificare il luogo di nascita del soggetto IdANPR 24440760 deceduto 28/07/2018 in quanto gli eredi richiedono della documentazione.

Questo comporta anche la modifca del CF in AE

Naturalmente da webapp non è più possibile..... come posso operare??

Saluti

Rossi Diego

**Comment by rvinzani** [comment]
E' possibile annullare l'operazione di decesso, effettuare una mutazione dati anagrafici ed acquisire nuovamente il decesso. Fare attenzione alle date di decorrenza dell'operazione che siano congruenti fra loro e rispetto agli eventi.
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti è possibile riaprire un'altra issue facendo riferimento a questa stessa
