### ISSUE TITLE
 Inserimento pratica con errore data decorrenza 15/06/2019 00:00:00 minore della data decorrenza 17/06/2019 00:00:00 dell'ultimo stato dell'individuo - CambioAggregazione

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#1481]
Buongiorno,
invio segnalazione per rinserire una pratica di immigrazione da Comune non subentrato, la pratica era stata annullata perchè era stata inserita una decorrenza errata (17/06 invece di 15/06), tramite webapp dell'ANPR sono riuscito ad annullarla, ma quando provo a inserire nuovamente la pratica dal nostro programma per l'ANPR mi dà il seguente errore quando provo ad inviare la pratica:

data decorrenza 15/06/2019 00:00:00 minore della data decorrenza 17/06/2019 00:00:00 dell'ultimo stato dell'individuo - CambioAggregazione - CF(CF persona) - ID Individuo (ID individuo)

Dopo la segnalazione alla nostra ditta che si occupa dei programmi, mi hanno consigliato di fare questa segnalazione, perchè il problema è di SOGEI, e di segnalare nel testo che:
E' sata fatta iscrizione altri motivi con id operazione ANPR 96263748 in data 17/06/2019 poi annullata a causa di errore nell’indicare la data decorrenza.
Successivamente è stata fatta una Rettifica Dati Subentro con ID ANPR 97979750 sempre in data 17/06/2019.
Ora vorremmo riproporre la prima iscrizione con la data decorrenza giusta al 15/06/2019 ma veniamo bloccati dalla precedente Rettifica che non risulta annullabile.
Come posso fare per procedere all'iscrizione della persona? Grazie

**Comment by frmariani** [comment]
Per favore dovrebbe indicare l'idanpr  dell'operazione di iscrizione che viene bloccata.

Grazie.

**Comment by marcoLave** [comment]
Non ho nessun  ID Operazione ANPR in quanto la pratica non riesce ad andare in ANPR in quanto si blocca durante quando viene fatto l'invio..

**Comment by frmariani** [comment]
Allora il problema è sul suo gestionale e non in ANPR;
per il soggetto indicato tutte le operazioni sono state annullate pertanto nulla osta alla sua re-iscrizione.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
