### ISSUE TITLE
[4005] errore 999 in verifica status

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1482]
Ambiente di test. comune di Poggio a Caiano

Le richieste 4005 di tipo verifica status richieste danno errore 999 - Operazione non effettuabile (es ID ANPR 19907848, 19907849. 19907850)

Potete indagare ? 

Grazie

**Comment by mttfranci** [comment]
Grazie mille della segnalazione.
Alcune richieste erano state create in modo formalmente errato, ma ora sono state rigenerate.
Il problema in test comuni dovrebbe essere risolto ed era lo stesso segnalato nella issue #1483.
Potrebbe esserci qualche caso simile in presubentro, ma stiamo provvedendo.
In produzione il problema non dovrebbe mai essersi verificato.
Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
