### ISSUE TITLE
[4005] verifica stato

### ISSUE THREAD

**Issue by StefanoGuidetti** [italia/anpr#1483]
Stamane, 
poco dopo aver risolto questa segnalazione #1477 sulle notifiche
Il servizio 4005 ora va in errore quando richiediamo lo stato di elaborazione 
sia in ambiente di produzione che di test

es. risposta ANPR Ambiente di test
![image](https://user-images.githubusercontent.com/43878804/61793451-7912b880-ae1f-11e9-845c-cff03129fbff.png)

**Comment by mttfranci** [comment]
In effetti abbiamo individuato il problema in test comuni.
Ci confermate che avete lo stesso problema anche in produzione? Potreste fornirci una richiesta?
Grazie in anticipo.

**Comment by StefanoGuidetti** [comment]
Ho richiesto altre verifiche,
sembra non ci siano problemi sull'ambiente di produzione
E' stata una falsa segnalazione

Scusate.

**Comment by mttfranci** [comment]
Grazie mille della risposta.
Alcune richieste erano state create in modo formalmente errato, ma ora sono state rigenerate.
Il problema in test comuni dovrebbe essere risolto ed era lo stesso segnalato nella issue #1482.
Potrebbe esserci qualche caso simile in presubentro, ma stiamo provvedendo.
In produzione il problema non dovrebbe mai essersi verificato.
Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
