### ISSUE TITLE
Rettifica data di iscrizione cittadino AIRE

### ISSUE THREAD

**Issue by PieroniAlb** [italia/anpr#1484]
Buongiorno,

abbiamo la necessità di rettificare la data di iscrizione del cittadino AIRE Id ANPR 61375772 da 04/02/2018 a 04/02/2019 come procedere?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
dovete annullare la mutazione AIRE 107088504 ed eseguire una RETTIFICA dati subentro, altre date. La data iscrizione è tra quelle rettificabili dopo il subentro se non sono già state fatte altre operazioni successive.

N. Capozzi
