### ISSUE TITLE
[Test subentro] File APR con una sola famiglia di tre persone

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#149]
Buongiorno, 
la settimana scorsa ho effettuato un test di invio file APR con una sola famiglia di tre persone.
Lo STATO dell'INVIO risulta 'INSERITO OK', mentre lo STATO dell'ESITO è ancora adesso 'IN ELABORAZIONE'.
Inoltre, se nella sezione 'CONSULTAZIONE e ESTRAZIONE' provo a cercare i dati dei 3 cittadini inviati nel file, il sistema non restituisce nessun risultato. Potrei avere dei chiarimenti ?

Inoltre, stavo controllando la sezione 'Richiesta cancellazione subentro' e premendo il bottone è partita, senza alcun avviso di conferma, la richiesta di cancellazione, che ora risulta 'in corso'. 
Questa operazione era comunque in programma, perchè volevo cancellare i dati del suddetto test e provare ad inviare il file APR contenente tutti i dati dei cittadini residenti. 
Però ripeto mi sarei aspettato un avviso di conferma. Starò più attento d'ora in avanti. 
Grazie

**Comment by gcarbonin** [comment]
L'elaborazione del subentro richiede che siano inviati i dati APR ma anche quelli AIRE altrimenti il processo di ferma.
Le cancellazioni avvengono di notte in quanto la loro esecuzione mentre altri eseguono i test introduce inconsistenze nella base dati.
