### ISSUE TITLE
richiesta di attribuzione  da c.f. numerico marcato ANPR ad alfanumerico 

### ISSUE THREAD

**Issue by sfabrizi** [italia/anpr#1494]
Buongiorno,
sono Fabrizi Simonetta dell'anagrafe del comune di Terni
Noi abbiamo in ANPR 57 posizioni marcate  con c.f. numerico.
Abbiamo la necessità di attribuire  a tutte le  persone presenti  in ANPR con codice fiscale numerico il codice fiscale alfanumerico e di variare le generalità alle suddette persone, ove necessario,  per rendere loro fruibili i servizi sul territorio:  conseguimento patente guida, contratto di lavoro , motivi sanitari ecc….
Abbiamo provato, inutilmente,  ad effettuare l'attribuzione tramite web app ed anche tramite gestionale.  i cittadini si sono recati all'agenzia delle entrate territoriale che però non procede poiché il codice numerico è marcato ANPR.
Un ID di una operazione provata è questo IdOpANPR 106509341
chiediamo la Vostra collaborazione.
inviamo i nostri contatti:
Funzionario: Maria teresa,chieruzzi  tel  0744/549265
Simonetta Fabrizi 0744/549255

**Comment by rvinzani** [comment]
Il codice fiscale alfanumerico non può essere attribuito da ANPR perchè è prerogativa di Agenzia delle entrate o della questura. Il definitivo viene assegnato a seguito di regolarizzazione del cittadino ed una volta assegnato è possibile modificare i dati in ANPR collegando le due posizioni.
Nel caso da voi evidenziato il codice fiscale non esiste ed è per questo che non risulta possibile modificarlo in ANPR.
In caso sia necessaria un'ulteriore indagine sulle singole casistiche si prega di rivolgersi all'assistenza ANPR al numero 800863116
