### ISSUE TITLE
Annullamento A006 con successive integrazioni indirizzo

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1495]
Ente produzione comune Martinsicuro.

In data 11/07/2019 il comune iscrive il cittadino 59765946 residente all'AIRE, nei giorni successivi effettua delle 5001 di integrazione indirizzo, alcune ripetute erroneamente; ieri il comune si rende conto che la data di decorrenza residenza non è corretta, 02/07/2019 invece di 14/06/2019.
Volevamo sapere se era possibile annullare direttamente la A006 oppure era prima necessario agire sulle 5001 che il cliente ha creato.
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
è necessario prima annullare tutte le mutazioni 5001 eseguite dopo la mutazione AIRE in quanto relative all'indirizzo.

Qualora il comune abbia bisogno di assistenza diretta per eseguire le operazioni necessarie deve aprire un ticket al numero 800863116 indicando nominativo e recapito della persona di riferimento.

Grazie
N. Capozzi
