### ISSUE TITLE
[3003] filtro idOperazioneComune non funziona

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1497]
Ambiente di test, comune di Poggio a Caiano.

Tra le richieste inviate esiste sicuramente quella con id operazione comune "JD1035041", ha  id ANPR 19915517.
Se però la ricerco con il servizio 3003 usando come filtro "id operazione comune" questo mi restituisce l'errore "EN122 La richiesta effettuata non produce alcun risultato" (id ANPR 19919074).

Ho provato anche con il filtro "idOperazioneANPR" ottenendo lo stesso risultato.

Sto usando il servizio in modo corretto ? Ci sono delle limitazioni che non ricordo ?

Grazie

**Comment by mttfranci** [comment]
L'operazione JD1035041 per Poggio a Caiano in test è una consultazione 3002.

Potreste provare, ad esempio, ad interrogare una operazione di registrazione?

Le consultazioni (300X) e le estrazioni (400X) non vengono restituite dai servizi 3003/3007 che servono principalmente per ottenere operazioni di registrazione e notifiche (vale a dire le operazioni che hanno un impatto sulla vita anagrafica dei soggetti).

Questo per due motivi : 
- Le consultazioni / estrazioni sono operazioni ripetibili dato che non modificano i dati
- A volte questo tipo di operazioni possono diventare molto pesanti in termini di dimensione della risposta, oltretutto potremmo avere il paradosso, ad esempio, di interrogare con un 3003 un altro 3003.

Saluti

Assistenza ANPR

**Comment by busaster** [comment]
Capisco.
cerco di illustrare il nostro scopo : capire se il db locale è un restore da un backup, verificando se esistono in ANPR operazioni che invece mancano nel log che teniamo nella base dati locale.
Questo test non può basarsi su una richiesta di scarico asincrona perché il suo fallimento deve bloccare le operazioni e invitare il cliente a contattarci.
Abbiamo quindi pensato di utilizzare il servizio 3003.

Diciamo che il top sarebbe quello di avere un servizio per capire qual è l'ultimo id operazione comune che abbiamo usato, indipendentemente dal tipo di servizio chiamato.

**Comment by mttfranci** [comment]
Capiamo l'esigenza.

Vediamo una criticità nel fatto che non sia scontato capire quale sia l'ultimo id generato ora che sono alfanumerici (alcune software house pare usino anche degli ID non sequenziali ( ad esempio #1065 ).
O a voi servirebbe il più recente ID comunale recepito da ANPR per un comune?

**Comment by busaster** [comment]
Il più recente ID comunale recepito da ANPR per un determinato comune sarebbe esattamente quello che ci serve, a prescindere dalla sequenzialità o meno di tale numero

**Comment by busaster** [comment]
In realtà studiando meglio il caso la nostra esigenza sarebbe conoscere il più recente ID comunale recepito da ANPR dato come filtro il comune di lavoro (codMittente) ed il nome dell'applicativo (nomeApplicativo) presenti nella testata della richiesta. Forse basterebbe aggiungere un particolare filtro nel servizio 3003 o anche nel 3007
