### ISSUE TITLE
esito AE 24 - risoluzione CF

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1498]
Ambiente di produzione, id cittadino anpr 59285260.
Il comune è subentrato a maggio, il cittadino è stato cancellato per irreperibilità il 19 giugno dopo l'iter previsto. Ricompare oggi.

Questo cittadino era in possesso di un CF omocodice assegnato da AE (finiva per Z3P6O) .  Potete verificare il CF consultando la scheda alla data del 1 giugno. Con questo vecchio codice fiscale, se consultate AE da anpr ottenete 4 codici collegati:
1) l'attuale con generalità  diverse da quelle anagrafiche
2) il cf omocodice che abbiamo inserito in ANPR. 
3) un cf numerico provvisorio
4) un cf identico al 2, ma non omocodice che finisce per Z336C

Ricompare oggi e lo abbiamo registrato con questo codice presenta anche al 1 giugno in ANPR.
Ci siamo poi accorti che in AE era stato assegnato un nuovo cf completamente diverso (quello citato qui sopra al punto 1).

Facciamo presente che il cittadino è diventato italiano nel 2016, e che ha quindi generalità diverse da quelle attualmente presenti in Agenzia Entrate.
Tentando di risolvere disallineamento, ci dava l'errore:
Esito AE: Codice fiscale formalmente errato (Codice 24)
che abbiamo ipotizzato fosse dovuto al cf anomalo presente in anpr, in quanto omocodice. 

Abbiamo rettificato solo ANPR con operazione 3 da non registrare in AE, portando il cf presente in ANPR al 4° codice di quelli presenti in AE.
Quindi abbiamo eseguito il disallineamento, confermando dati ANPR, l'esito è stato:

- esito AE: codice fiscale numerico attribuito per omocodia (codice 10)

- esito ANPR: mutazione dei dati del soggetoto eseguito correttamente. nuovo codice fiscale attribuito : (segue numero)

- esito AE: operazione non effettuabile (codice 95)

Consultando in questo momento, abbiamo un cf numerico in ANPR non validato e nessuna apparente variazione in AE.
Il Comune si chiede come avrebbe dovuto comportarsi e come possiamo correggerlo.

**Comment by rvinzani** [comment]
Quello che il comune avrebbe dovuto fare è di collegare i due CF con la funzione di risoluzione disallineamenti con Agenzia Entrate.
Nell'attuale situazione la cosa si è troppo complicata per riuscire a gestirla da ANPR
E' necessario quindi scrivere alla casella
entrate.archivioanagrafico@agenziaentrate.it 
chiedendo di annullare l'ultimo Cf numerico attribuito e collegare le due posizioni.
Successivamente il comune dovrà rivolgersi all'assistenza ANPR (800863116) per sistemare la situazione in ANPR
