### ISSUE TITLE
[Test subentro] Dati Aire

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#150]
Buongiorno,
siccome le istruzioni per l'installazione di AnagAire 6.0.2 avvisano che _deve essere eseguita su una **postazione certificata** **diversa** da quella dove è installata la versione AnagAire 6.0.1 (o precedente) attualmente utilizzata_, avrei un problema visto che il comune ha una sola postazione.
Quindi, vorrei chiedere se posso installare AnagAire 6.0.2 sulla mia postazione in azienda che però non è certificata. E nel caso, posso chiedere a voi il certificato o devo farlo recuperare dal funzionario dell'anagrafe?
Grazie

Bistagno (AL)
Codice ISTAT: 006017

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Chiarito telefocamente
