### ISSUE TITLE
[5001] rimpatrio bloccato per tipo famiglia incoerente

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1500]
Ambiente di produzione, comune di Palma di Montechiaro

Con l'operazione 5001 di ID ANPR 94762736 abbiamo fatto rimpatriare una famiglia AIRE.
Successviamente per altri motivi questa operazione è stata annullata (ID ANPR annullamento 101867249).
Quest'ultimo annullamento ha però lasciato in ANPR la famiglia di id 18376082 con il tipo 3 (famiglia ANPR) invece del precedente tipo 5 (famiglia AIRE).
A causa di questo il tentativo di fare un'ulteriore rimaptrio con una 5001 fallisce con l'errore "EF002 Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata" (id opeazione ANPR 108235624).

Il tipo famiglia non è modificabile nemmeno da webapp.
Potete modificarlo voi ?

Grazie

**Comment by fferraguto** [comment]
Salve,
sulla famiglia segnalata è stata effettuata una mutazione di tipo 5001-3 (id anpr 94762761) successiva alla mutazione di residenza.
Dovrebbe essere sufficiente annullare quest'operazione per ripristinare la situazione corretta.
Resto in attesa di riscontro.

**Comment by busaster** [comment]
Grazie per il supporto, annullando l'operazione abbiamo sbloccato la situazione.
