### ISSUE TITLE
Ambiente FREE - Errore java.security.cert.CertPathValidatorException: validity

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1501]
Buongiorno,
la settimana scorsa avevo configurato il client java (https://github.com/italia/anpr-client-example) per funzionare in ambiente di test FREE. Funzionava fino a venerdi. Da stamattina si verifica la seguente eccezione: "javax.xml.ws.soap.SOAPFaultException: Problem writing SAAJ model to stream: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed". Ha a che fare con il certificato SSL? Quale dovrei usare? Grazie

**Comment by gife67** [comment]
Buongiorno,
ieri è scaduto il certificato SSL dell'endpoint dei WS per l'ambiente di FreeTest.
Stiamo provvedendo alla sostituzione, appena effettuata il client riprenderà a funzionare senza che debba fare alcun intervento.
Ci scusiamo per il disagio.
Cordiali saluti.

**Comment by Eduardo1977** [comment]
Grazie, come sempre, per il riscontro. 
Cordiali saluti

**Comment by Eduardo1977** [comment]
Buongiorno, ho ancora qualche problema ad accedere ai servizi dell'ambiente FREE. E' stato risolto il problema del certificato SSL ? Grazie
