### ISSUE TITLE
Famiglia - Identificativo scheda attribuito dal comune errato

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1502]
Buongiorno,
il soggetto id anpr 28901944, ha richiesto iscrizione nel Comune di Milano (mut. fam/conv id 87730893), il quale, a seguito di accertamenti negativi ha eseguito annullamento mutazione famiglia/convivenza (id oper. 94916020) per ripristino del soggetto come residente nel Comune di Torino. 
Nonostante ci sia un annullamento di operazione, nella parte relativa alla famiglia - identificativo scheda attribuito dal comune - il soggetto presenta l'identificativo famiglia del comune di Milano con relativo codice istat 015146.
Purtroppo è un dato che non è possibile modificare neanche utilizzando la funzione mutazione famiglia/convivenza.
Stessa cosa è capitata con il soggetto ID 32342459.
Si tratta di un'anomalia? 
Grazie
UpiTorino

**Comment by fferraguto** [comment]
Salve,
per quanto riguarda il soggetto 28901944, vi chiediamo di darci conferma che la situazione risulti corretta. 
Per quanto riguarda il soggetto 32342459, ci risulta residente nel comune di Torino, non è corretto?

**Comment by UpiTorino** [comment]
Buongiorno,
per quanto riguarda il soggetto  28901944, confermo che ora la situazione è corretta.
Per quanto riguarda il soggetto 32342459 spiego meglio ciò che è avvenuto: il soggetto si è trasferito a Settimo Torinese e, successivamente, ha richiesto iscrizione nel comune di Torino. Purtroppo, a causa di un errore dell'operatore, abbiamo dovuto annullare le mutazioni fam/conv riportando il soggetto temporaneamente come residente del Comune di Settimo Torinese, in quel momento il soggetto era residente di Settimo Torinese ma con l'identificativo scheda attribuito dal comune (fam) avente codice istat di Torino 001272 e n. famiglia di Torino.
Avendo poi dovuto rieseguire le operazioni, il dato si è allineato in quanto effettivamente il soggetto è residente di Torino.
Saluti
UpiTorino

**Comment by fferraguto** [comment]
Va bene, allora la situazione è corretta al momento.

**Comment by UpiTorino** [comment]
Buongiorno,
il problema continua a ripresentarsi. 
Il soggetto con id 28239111 deve raggiungere il soggetto 28510975 nella famiglia 15841768 ma il cambio non è transitato a causa dell'errore EF007 "Intestatario scheda famiglia/convivenza già presente".
Successivamente 28510975 fa una mutazione residenza (scomposizione creazione famiglia nuova), ma annullando la mutazioni di quest'ultimo per poter eseguire correttamente i cambi indirizzo l'identificativo scheda attribuito dal comune non si è aggiornato, è rimasto quello relativo all'ultima famiglia creata.
Grazie.
Saluti.
UpiTorino

**Comment by fferraguto** [comment]
Salve,
relativamente a "...Successivamente 28510975 fa una mutazione residenza (scomposizione creazione famiglia nuova), ma annullando la mutazioni di quest'ultimo...", fate riferimento all'operazione ANPR con id 111178850 che ha spostato il soggetto 28510975 nella famiglia con id ANPR 38792660?
E' questa che avete provato ad annullare? Perchè non risulta annullata.
Eventualmente potreste segnalarci l'operazione di annullamento effettuata?
Grazie.
