### ISSUE TITLE
[EAM9F] posizioni multiple in AT non unificabili

### ISSUE THREAD

**Issue by nakis** [italia/anpr#1503]
Scrivo per conto dell'anagrafe del Comune di Prato che deve variare le generalità del soggetto con ID ANPR 41320940. Quando vanno a fare la variazione ricalcolando ovviamente il codice fiscale ottengono l'errore **EAM9F: individuate due posizioni in AT non unificabili** (idOperazioneANPR 106815756). Se provano specificando l'azione di omocodia invece della validazione del codice fiscale ottengono l'errore **EN491: se il codice fiscale è esistente, non è possibile richiedere una nuova attribuzione** (idOperazione 106827732).
La risoluzione disallineamenti da portale ANPR restituisce di nuovo un errore 9F. La persona sembra essere presente sugli archivi di Agenzia delle Entrate molte volte con diverse generalità e vari codici fiscali.
Ho tralasciato i dettagli identificativi della persona, li invio tramite email.
Come possiamo completare la variazione di generalità?

**Comment by asqueglia** [comment]
Ci sembra che la sua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio.
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci sta leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo le chiediamo, per questa segnalazione, di avvalersi del servizio di assistenza ANPR  al numero 800863116.
