### ISSUE TITLE
Modifica Data Decorrenza Iscrizione

### ISSUE THREAD

**Issue by ceddesenzano** [italia/anpr#1504]
Comune di Desenzano del Garda - Produzione
Abbiamo effettuato una iscrizione in ANPR per nascita con data 11.07.2019  numero identificativo scheda: 64508667 
Ci siamo accorti che la data di nascita era errata e attraverso la mutazione scheda abbiamo cambiato la data di nascita in 10.07.2019
Ma la data di decorrenza della residenza e la data di decorrenza di appartenenza alla famiglia è rimasta 11.07.2019
Abbiamo tentato di variare tale data, con rettifica dati, dall'11 al 10 ma ci segnala il seguente errore:
Data decorrenza residenza 10-07-2019 minore della data di prima iscrizione del soggetto (Codice: EN415)
Come possiamo correggere?

**Comment by azabatta** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
