### ISSUE TITLE
Errata chiusura procedimento amministrativo

### ISSUE THREAD

**Issue by MarcellaM** [italia/anpr#1505]
Buongiorno, a causa di un errato inserimento i colleghi hanno ritenuto di dover annullare la pratica di iscrizione per altri motivi con provenienza da Comune non subentrato ID ANPR 96871044. 
Non riuscendo ad annullarla dal nostro gestionale, hanno provveduto tramite Webapp.
Ora il nominativo (SZMPCS98A68Z335O) non risulta presente in ANPR ma è rimasto iscritto come residente in banca dati di servizio; situazione che non permette più alcun tipo di operazione.
E' possibile ripristinare la posizione del soggetto con c.fisc.: SZMPCS98A68Z335O  prima della chiusura istruttoria con esito negativo e riaprire quindi il procedimento amministrativo per poi procedere alle dovute rettifiche?
Grazie
Marcella Molinari

**Comment by azabatta** [comment]
Ci sembra che la tua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo ti chiediamo, per questa segnalazione,  di avvalerti del servizio di assistenza ANPR al numero 800863116.
