### ISSUE TITLE
mancato aggiornamento dati pur a seguito di invio mutazione

### ISSUE THREAD

**Issue by ComuneSegrate** [italia/anpr#1506]
Dopo mutazione matrimonio con ID operazione ANPR 101837098 il dato del matrimonio non è visibile in interrogazione individuo. Il nuovo dato del secondo matrimonio non risulta aggiornato.

**Comment by asqueglia** [comment]
Abbiamo analizzato il caso. 
Come premessa comunichiamo che il matrimonio in ANPR viene gestito come informazione unica e condivisa tra due soggetti, per garantire che i dati siano coerenti. 
Abbiamo notato che sono state trasmesse due diverse comunicazioni di matrimonio, una da vostro gestionale e un'altra dal comune di competenza dell'atro coniuge PESCHIERA BORROMEO. Il vostro comune ha correttamente inviato il matrimonio con tutti i dati del coniuge collegando i due soggetti. PESCHIERA BORROMEO, non avrebbe dovuto far nulla in quanto il proprio soggetto aveva già tutti i dati del matrimonio come da voi registrati.  
PESCHIERA BORROMEO, invece, ha scollegato i coniugi 'eliminando' di fatto le informazioni da voi inserite. Ecco perché  non ritrovate più i dati del secondo matrimonio.
Consigliamo di inserire nuovamente il matrimonio con i dati completi del coniuge ricollegando i soggetti.
Comunque sia la sua richiesta ha un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci sta leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo le chiediamo, per questi tipi di segnalazione,  di avvalersi del servizio di assistenza ANPR al numero 800863116.
