### ISSUE TITLE
ERRORE eam28

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#1507]
Questo il mio problema, da Comune subentrato:
In seguito a decreto di cittadinanza una signora ha assunto un nuovo cognome XX e quindi le generalità sono state modificate in tal senso.
La stessa signora Ha richiesto il ritorno al cognome originario YY  .La  Prefettura ha emesso il decreto ed ora alla sig. ra occorre riattribuire le generalità originarie YY.
Cercando di rimodificare il cognome Anpr risponde
1 Errore Anpr Cod: EAM28 - Altri soggetti individuati in AT dai NUOVI dati anagrafici, richiesta di variazione dati non effettuabile - 
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-19 12:24:48 , idOperazioneANPR 105619711 - 
Probabilmente il cognome originario YY e relativo codice fiscale , al quale vuole tornare,  era una risoluzione di omocodia infatti la parte finale è Z13UY
La mia software house ha risposto di non riuscire a risolvere il problema e di rivolgerci al numero di assistenza ANPR , questi ultimi hanno risposto di chiedere alla mail entrate. archivioanagrafico@agenzia entrate.it, che mi ha risposto:"per risolvere il caso segnalato, è necessario che codesto Comune si rivolga ad un qualsiasi Ufficio Territoriale dell’Agenzia delle Entrate; l’Ufficio Territoriale in questione avrà cura di attivarsi e, dopo aver effettuato le opportune verifiche, metterà in piedi l’omocodia come da Comunicazione di Servizio e chiederà a questo Ufficio la risoluzione del caso".
Chiamata quindi l'agenzia Territoriale mi è stato risposto che loro non possono fare niente in quanto siamo stati noi a collegare i due codici fiscali e quindi dobbiamo SCOLLEGARLI e ricollegarli......
Intanto la cittadina mi assilla giustamente in quanto ha delle problematiche in corso da risolvere con urgenza  e con i suo nuovo cognome
Non so piu' cosa fare come si fa a scollegare due codici???

**Comment by frmariani** [comment]
in ANPR non è prevista l'operazione di "scollegamento" di due codici fiscali.
Consiglio di inviare la documentazione disponibile all’attenzione della Direzione Centrale Archivio Anagrafico per le opportune indagini.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
