### ISSUE TITLE
Modifica data decorrenza residenza inviata con il subentro

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1508]
Produzione comune Villamarzana

Il comune fa subentrare il 10/07/2019 la cittadina 62599450 inserendo come data decorrenza residenza il 03/07/2019. Ricevendo risposta dal comune di cancellazione con parecchio ritardo è costretta a modificare la definizione della pratica al 18/07/2019, ora la cliente vorrebbe modificare il dato anche in ANPR.
Esiste un servizio in WA per consentire al comune di variare tale dato?
Grazie

**Comment by frmariani** [comment]
La data di Decorrenza della Residenza può essere modificata con il servizio di Rettifica Dati Subentro. 

Nel caso siano necessarie indicazioni sul caso specifico, potete avvalervi del servizio di assistenza ANPR al numero 800863116.
