### ISSUE TITLE
Problema cambio stato civile da vedova a divorziata ed inserimento divorzio

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#1509]
Buongiorno,
si segnala un problema nella modifica dello stato civile della persona nostra residente, in quanto momentaneamente dal suo stato civile risulta vedova (decorrenza in data 19/06/2019) ma successivamente (25/07/2019) ci è pervenuto da un altro Comune la variazione anagrafica della persona suddetta per cessazione effetti civili del matrimonio (decorrenza 24/01/2018).
Ho provato da Webapp  a cambiare lo Stato Civile ed inserire i dati della cessazione del matrimonio ma mi restituisce sempre l'errore:
"La data della vedovanza deve essere maggiore della data di nascita e minore o uguale della data di decorrenza dell'operazione (Codice: ES011)"
"Informazioni sull'operazione da fornire in caso di assistenza : data 2019-08-01 13:14:26 , idOperazioneANPR 109407767 (Codice: EN527)"
In attesa di cortese riscontro si porgono i migliori saluti.

Laveglia Marco

**Comment by frmariani** [comment]
i coniugi ci risultano entrambi appartenenti al vostro Comune; non essendo pervenuta l'informazione del divorzio, il decesso di un coniuge, ha inserito automaticamente i dati della vedovanza nella scheda del coniuge superstite; chiaramente,  a questo punto,  non è possibile inserire anche i dati del divorzio per lo stesso matrimonio;
consiglio di annullare l'operazione di decesso, acquisire i dati della cessazione del matrimonio e successivamente effettuare di nuovo l'operazione di decesso.

Nel caso di ulteriori indicazione sulla segnalazione, si prega di chiamare l'assistenza ANPR al numero 800863116.
