### ISSUE TITLE
Data cessazione comuni italiani ceduti ad altri stati esteri

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#151]
Circolare ministeriale n. 25 del 17/10/2012 e “Direttiva del Presidente del Consiglio dei Ministri 5 luglio 2012”.

La circolare sopra citata indica le date di cessione dei territori relativi ai comuni ceduti dall'Italia ad altri Stati. L'allegato A elenca i comuni italiani validi fino al 15/09/1947. L'allegato B elenca i comuni validi fino al 03/04/1977.  
Nella tabella dei comuni pubblicata sul sito dell'ANPR, per i comuni di cui all'allegato B viene riportata come data di cessazione la data indicata nell'allegato A: 15/09/1947. 

Sempre nella circolare sopra citata, la sigla di ZARA indicata è ZA mentre nella tabella storica dei comuni di ANPR risulta essere ZR (sigla presente nella tabella delle provincie dell'ANAGAIRE). 
La sigla come provincia italiana (utilizzata anche nelle targhe) è sempre stata ZA.

**Comment by gcarbonin** [comment]
Abbiamo segnalato il problema a ISTAT che farà sapere. Per quanto riguarda la sigla di Zara sono entrambe valide. Nell'archivio ANPR è stato inserito. Se questo rappresenta un problema faremo in modo di accettarle entrambe.

**Comment by gcarbonin** [comment]
Abbiamo allineato l'archivio alla direttiva. Nel primo pomeriggio sarà pubblicata la nuova tabella su www.anpr.interno.it.
