### ISSUE TITLE
Famiglia non certificabile cod. 9079622

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1510]
La famiglia cod. 9079622 non è certificabile. Ho provato a modificare i rapporti di parentela tramite il portale ANPR l'errore di certificazione sussiste.
Chiedo se potete dare un'occhiata alla famiglia 9079622.

I miei riferimenti, per qualsiasi comunicazione relativa alla presente, sono:
Andrea Paltrinieri
Ufficiale d'Anagrafe del Comune di Biassono
tel. 039-2201060
e-mail: paltrinieri.andrea@biassono.org 

In attesa di un vostro riscontro, porgo cordiali saluti.

**Comment by azabatta** [comment]
Ci sembra che la sua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci sta leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo le chiediamo, per questa segnalazione,  di avvalersi del servizio di assistenza ANPR al numero 800863116.
