### ISSUE TITLE
Certificato richiesto da Enti - caratteri ammessi nel nome dell'Ente

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1511]
Buongiorno,
facendo seguito a una segnalazione del comune di Scurcola Marsicana (ambiente di produzione) abbiamo verificato che nel caso di certificati richiesti da enti, andando ad inserire come da specifiche (vedi issue #950 ), nel campo che contiene gli estremi del documento, l'ente di appartenenza, alcuni caratteri di uso comune come l'apice non sono accettati (ad esempio se il nome dell'ente contiene L'Aquila), pertanto il sistema non valida la request e restituisce un errore.
Abbiamo verificato infatti che il campo _estDocRiconoscimento_  da xsd accetta caratteri di tipo _tipoEstDocRiconoscimento_ il cui pattern è [0-9a-zA-Z. ].
Anche se tale informazione non è poi riportata nel certificato, chiediamo se è possibile estendere il pattern inserendo anche questo carattere (ed eventualmente ad altri che riterrete opportuni), in modo da evitare l'errore in fase di stampa di tali certificati.
Grazie,
cordiali saluti.

**Comment by asqueglia** [comment]
Stiamo valutando la sua richiesta. le faremo sapere appena possibile

**Comment by asqueglia** [comment]
Comunichiamo che il pattern verrà esteso come da vostra richiesta. L' aggiornamento verrà pubblicato nel changeLog con riferimento alla presente Issue.
