### ISSUE TITLE
errore EAM28 in mutazione generalita'

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#1512]
Si deve procedere alla mutazione delle generalità del soggetto idANPR 39090880 per correggere il nominativo invertendo il cognome col nome.

in AE sono presenti molteplici schede con gli stessi dati (alcuni con codice fiscale omocodice risolto, molti con codice fiscale numerico compreso quello associato alla persona in questione, attribuito con rilascio del nuovo permesso di soggiorno coi dati anagrafici corretti).

Qualsiasi soluzione provata (mutazione dati (con o senza validazione del cf), ricalcolando il codice fiscale o inserendo il codice fiscale numerico associato al permesso di soggiorno, risoluzione disallineamenti con AE), ha restituito errore per operazione non effettuabile per  presenza di altri soggetti in AT coi NUOVI dati anagrafici.

ultima operazione: idOperazioneANPR 109822015
                               Errore Anpr Cod: EAM28 - Altri soggetti individuati in AT dai NUOVI dati 
                               anagrafici, richiesta di variazione dati non effettuabile 

Come è possibile risolvere il problema?

grazie
Andrea Demeglio
Comune di Cagliari

**Comment by FilippoPapi** [comment]
Ci sembra che la sua richiesta abbia un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio.
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci sta leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo le chiediamo, per questa segnalazione, di avvalersi del servizio di assistenza ANPR al numero 800863116.
