### ISSUE TITLE
[5008] variazione di matrimonio non recepita

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1513]
Ambiente di produzione, comune di Godega di Sant'Urbano

Con id operazione ANPR 110109304 vien eseguita una mutazione 5008 di tipo 12 su un soggetto per modificare i dati di matrimonio.
ANPR restituisce un esito positivo all'operazione ,ma ad una consultazione del soggetto i dati di matrimonio non sono cambiati.
Il comune ha provato ad eseguire l'operazione da webapp ottenendo lo stesso comportamento, ovvero una risposta positiva all'esito dell'operazione ma nessuna variazione sui dati del soggetto.

Potete aiutarci a capire cosa succede ?
Grazie

**Comment by asqueglia** [comment]
Buongiorno, la situazione da voi descritta è stata generata da una anomalia di sistema, presente nel servizio di mutazione matrimonio all'atto del primo collegamento dei coniugi, da voi trasmessa il 23-OTT-18. Detta anomalia è stata risolta circa un paio di mesi fa. Siamo intervenuti da centro per sanare la vostra situazione. Adesso se consultate una qualsiasi delle schede dei coniugi vedrete i dati corretti del matrimonio come da voi trasmessi con le successive mutazioni.
