### ISSUE TITLE
Allineamento CF in WEBAPP

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1514]
**Diego Rossi - Comune di Parma**

Buongiorno,

in questi giorni ci sono capitati due casi di soggetti di origine indiana che, partendo dalla situazione di Cognome assente e Nome valorizzato, hanno la necessità di modificare nome e cognome con conseguente aggiornamento di CF

Per entrambi la risoluzione allineamenti della WebApp inserendo il CF vecchio e quello nuovo mi restituisce l'errore:

> _Esito ANPR: La richiesta non risulta valida secondo i nuovi XSD [cvc-complex-type.2.4.a: Invalid content was found starting with element 'nome'. One of '{cognome, senzaCognome}' is expected.] (Codice: EN489)
> Esito ANPR: La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)
> Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2019-08-05 09:15:19 , Token 1564989319661 (Codice: EN527)_
> 

i due casi sono:

1. 
> Cognome: <>
> Nome: SATENDERJEET KAUR
> Nata il: 05/10/1986
> CF: XXXSND86R45Z222T

Vorrebbe essere modificato in:

> Cognome: KAUR
> Nome: SATENDERJEET 
> Nata il: 05/10/1986
> CF: KRASND86R45Z2N2D (codice fiscale omocodice)

2. 
> Cognome: <>
> Nome: JAPNOOR SINGH
> Nata il: 11/12/2014  
> CF: XXXJNR14T11Z222T

Vorrebbe essere modificato in:

> Cognome: SINGH
> Nome: JAPNOOR 
> Nata il: 11/12/2014
> CF: SNGJNR14T11Z222M

come faccio???

Saluti

**Comment by azabatta** [comment]
Facendo seguito a quanto verificato per le vie brevi, si riepilogano  di seguito le regole generali da adottare in situazioni analoghe:  

-	in presenza di codici fiscali già collegati in Agenzia Entrate  si utilizza il servizio di “Mutazione tutti i dati”  (ws 5008) – tipo mutazione “dati anagrafici/codice fiscale” (codice 01)  al fine di aggiornare la posizione con i dati più recenti del cittadino 

-	il collegamento di un codice fiscale con altro codice fiscale base di omocodia non può essere effettuato tramite le funzionalità di ANPR ma bisogna rivolgersi ad Agenzia Entrate fornendo la documentazione di supporto alla richiesta di collegamento.

Saluti
