### ISSUE TITLE
[1001] iscrizione in nuova famiglia non funziona

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1515]
Ambiente di produzione, comune di Carmagnola

Il comune vuole iscrivere per nascita in una nuova famiglia un bambino che non è stato riconosciuto dai genitori.
Per fare questo abbiamo eseguito la chiamata al servizio 1001 di id ANPR 109817995, la quale  però restituisce uno strano errore "EF001 Identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata".

Come mai ?

**Comment by frmariani** [comment]
La famiglia a cui fate riferimento nel servizio 1001, è stata creata il 5/08/2019 alle 14:36, pertanto nel momento dell'iscrizione del bambino (02/08/2019)  la famiglia non esisteva (come cita correttamente la descrizione dell'errore);
Vi ricordo che per richieste di assistenza su casistiche particolari dovete avvalervi del servizio di assistenza ANPR al numero 800863116.
Il sistema di Issue Tracking basato Github, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale.
