### ISSUE TITLE
[1001] continua da #1515

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1516]
vedi issue #1515  

Credo che il problema non sia stato capito.
Nel momento in cui noi chiediamo via WS la creazione di una nuova famiglia, passiamo il nostro primo id comunale disponibile.
E' chiaro che il 5 agosto, 3 giorni dopo l'iscrizione che non funziona, quel ID comunale viene assegnato ad un'altra famiglia , per cui esiste nel vostro archivio ma non è più relativo al nostro problema iniziale.

Il problema è : come mai quella iscrizione per nascita non ha creato la famiglia nuova come ci aspettavamo ?

Grazie.

**Comment by frmariani** [comment]
perchè da regolamento anagrafico un bambino deve appartenere ad una famiglia o una  convivenza esistente

**Comment by frmariani** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
