### ISSUE TITLE
[1001] Problema con una iscrizione per nascita

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1517]
Buongiorno,
in ambiente di produzione stiamo provando a fare un'iscrizione per nascita tramite il servizio 1001.
Il padre è emigrato in un comune non subentrato mentre la madre è residente nel comune. 
Mandiamo come numero di famiglia quello della madre visto che il bambino andrà con lei, ma la risposta è la seguente:
"EN134: Identificativo Famiglia non valido o di competenza di altro comune"...
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-08-07 09:51:02 , idOperazioneANPR 110872278

Potete verificare?

Ringrazio anticipatamente

**Comment by frmariani** [comment]
nel servizio di iscrizione per nascita, l'informazione della famiglia di appartenenza del bambino viene specificata nei dati di controllo - attribuzione famiglia ; 

la sua richiesta di assistenza richiede scambi di informazioni e di dettaglio pertanto deve avvalersi del servizio di assistenza ANPR raggiungibile al numero 800863116. 
Il sistema di Issue Tracking basato Github, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
