### ISSUE TITLE
CIE emessa senza segno separatore (bara, trattino ecc....) nel civico

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#1519]
Buongiorno,
sono Arianna Nozzoli dal comune di Prato in ANPR di produzione.

Abbiamo questo problema nell'emissione delle CIE da quando siamo passati a ANPR. 
Ci siamo accorti che il dato del numero civico non viene passato da ANPR nel modo corretto al momento dell'emissione della CIE. 

Faccio un esempio:
Interrogo un cittadino che ha come indirizzo in anagrafe locale:

<Tipo>VIA</Tipo>
<Indirizzo>TRAVERSA DELLE FONTANELLE</Indirizzo>
<NumCiv>17/2</NumCiv>

Dal programma del ministero di emissione CIE torna:

"Tipo": "VIA",
"Indirizzo": "TRAVERSA DELLE FONTANELLE",
"NumCiv": "N. 17 2",

Questo comporta la consegna della CIE al civico 172 invece che 17/2 con i conseguenti problemi.

Ancora di più quando il civico è:

<NumCiv>17/2/4</NumCiv>

"NumCiv": "N. 17 2 4",

Ho interpellato l'ISTITUTO POLIGRAFICO E ZECCA DELLO STATO che mi risponde:

 _.....con il subentro in ANPR, al momento dell'interrogazione su CIEOnline, il dato che viene estratto proviene da ANPR...._ 

Potete verificare i tracciati record e dirmi chi è che non mette il separatore nel civico?

Grazie

Arianna Nozzoli

**Comment by mttfranci** [comment]
Salve, ad una prima verifica sembra che il tracciato restituito per questa tipologia di indirizzo venga correttamente restituita secondo il tracciato concordato, che per la residenza è lo stesso usato dai gestionali comunali : 

               `<toponimo>
                  <specie>VIA</specie>
                  <denominazioneToponimo>TRAVERSA DELLE FONTANELLE</denominazioneToponimo>
                  <toponimoFonte>2</toponimoFonte>
                </toponimo>
                <numeroCivico>
                  <numero>17</numero>
                  <lettera>2</lettera>
                  <civicoInterno>
                    <interno1>2</interno1>
                    <piano>T</piano>
                  </civicoInterno>
                </numeroCivico>`

Per una ulteriore verifica più approfondita, potete fornirci l'id soggetto anpr di un soggetto su cui avete avuto questo problema, possibilmente nei passati 3 giorni? Grazie in anticipo.

Assistenza ANPR

**Comment by mttfranci** [comment]
Dalle ulteriori verifiche effettuate tutti i dati sembrano essere trasmessi in campi sepratati, come previsto dal tracciato.
Abbiamo inoltrato richiesta di verifica agli uffici competenti.
Saluti

Assistenza ANPR

**Comment by anozzoli** [comment]
Postazione messa a disposizione dal Ministero. Quindi se i campi sono passati separati il problema della mancanza delle barre ritorna all'ISTITUTO POLIGRAFICO E ZECCA DELLO STATO. grazie
