### ISSUE TITLE
esenzione diritti di segreteria su certificati

### ISSUE THREAD

**Issue by AnnaUrban** [italia/anpr#152]
Il comune di Serravalle Sesia, comune di cui sono dipendente quale responsabile dei servizi demografici, ha adottato una delibera di Giunta con la quale è stata deliberata l'abolizione dei diritti di segreteria sui certificati rilasciati dall'ufficio anagrafe. Da giorni sto operando in ambiente di pre-subentro e, tra le varie simulazioni, ho provato a richiedere l'emissione di certificati sia in bollo che in carta libera: a parte alcuni casi specifici di esenzione, il programma richiede sempre l'inserimento dei diritti in quanto il campo è indicato come obbligatorio. Sarebbe opportuno prevedere un flag da inserire nella pagina dell'Amministrazione per indicare che il comune non richiede i diritti.

**Comment by gcarbonin** [comment]
Stiamo eseguendo l'intervento richiesto Avvertiamo quando possibile riprovare

**Comment by AnnaUrban** [comment]
Siamo subentrati da 2 giorni in ANPR ambiente di produzione e oggi abbiamo dovuto emettere 2 certificati uno dei quali in carta legale. Sul certificato emesso risultano registrati € 0,52 di diritti che, però, non abbiamo riscosso in quanto il nostro Comune li ha aboliti come già avevo segnalato. Come devo comportarmi in questi casi? Continuo ad emettere i certificati dalla piattaforma ANPR sapendo che c'è questa incongruenza o certifico ancora dalla banca dati del comune in attesa che si trovi una soluzione a tale fattispecie?

**Comment by gcarbonin** [comment]
I certificati possono essere emessi solo da ANPR. Stiamo già testando la soluzione che metteremo in produzione a inizio della prossima settimana.

**Comment by gcarbonin** [comment]
Può provare in ambiente di test-comuni o pre-subentro. occorre indicare che in comune non incassa i diritti (tramite la WA,  funzione AMMINISTRAZIONE, selezione su Certificati esenti dai diritti di segreteria). Completata questa operazione è possibile emettere i certificati indicando 0 come importo dei diritti riscossi.

**Comment by gcarbonin** [comment]
Chiudo per assenza di riscontri dal comune. La modifica è disponibile
