### ISSUE TITLE
Modifica Decorrenza Iscrizione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1521]
ambiente di PRODUZIONE - comune di POGGIBONSI (052022)

idSoggettoANPR 37965681

il soggetto è stato iscritto a Poggibonsi, per mutazione da comune subentrato, con data decorrenza sbagliata (3/8/2019 invece di 1/8/2019).
proprio la variazione che ha prodotto il cambio di residenza, peraltro, è stata eseguita tramite web-app, per cui presumo che non basti annullare le comunicazioni successive per intervenire in qualche modo su quella data tramite web-service...

il cliente ha preso contatti con l'assistenza per tentare la rettifica direttamente da portale e gli è stato risposto di contattare la software house.

come dovremmo procedere per sanare questa posizione.

grazie
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Cerchiamo di prestare sempre la massima attenzione all'assistenza, quindi, gentilmente ci dia almeno il numero del ticket in questione;   
Per il suo problema, può provare con l'operazione di Rettifica della data di decorrenza della residenza, ma potrò essere più precisa in un contatto diretto;
potete chiamare l'assistenza ANPR al numero 800863116 indicando il mio nome per l'assistenza di secondo livello - Francesca Mariani

**Comment by AMonopoliADS** [comment]
grazie Francesca
non siamo in possesso del ticket, abbiamo comunque comunicato al cliente di contattarvi nuovamente 
Alessandro
