### ISSUE TITLE
Eliminazione pratica Cancellazione per irreperibilità

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#1522]
**Comune di Parma - PRODUZIONE**

Buongiorno,

premetto di aver già contattato il numero verde 800863116 e di aver ottenuto, in modo molto sgarbato, la seguente risposta _"Noi siamo informatici e non dobbiamo fornire assistenza su procedure" .... usare Github"_

Bene....
Ho la pratica IdANPR **12858088 del 24/07/2018** riguardante la cancellazione per irreperibilità dei seguenti soggetti:

1. KAUR | AKWINDER | F | KRAKND67A42Z222S | 02/01/1967 | 
2. SINGH | KULJINDER | M | SNGKJN92S25F104S | 25/11/1992 |   
3. SINGH | MANPRIT KAUR | F | SNGMPR91T43L738N | 03/12/1991 |
4. KAUR | SURJIT | F | KRASJT35E43Z222R | 03/05/1935 | 

La settimana scorsa arriva all'ufficio AIRE una comunicazione del consolato di Zurigo che informa della necessità di iscrizione in AIRE dei 4 soggetti **datata maggio 2018** 

Di conseguenza procediamo all'annullamento della pratica 12858088 con data decorrenza 24/07/2018 ma il sistema risponde:

> 1 Errore Anpr Cod: EN077 - L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa - -
> 2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-08-12 09:45:45 , idOperazioneANPR 111981843 - -

Il motivo, credo, sia dovuto al fatto che la persona rimasta nella famiglia dopo la cancellazione con pratica 12858088 tale **SINGH ATINDER PAL - SNGTDR89B12Z222Y - 12/02/1989** ha effettuato un cambio di residenza nel comune di **CORNIGLIO (subentrato ANPR) datato 01/08/2019 con operazione IdAnpr 109893258** e, quindi, il sistema cerca di mettere i 4 soggetti in una famiglia che non esiste più.

E' questo il blocco??? Ricordo che però per un caso simile (immigrato da TORINO a PARMA, eliminato successivamente per accertamenti negativi ma a TORINO la famiglia non esisteva più) il sistema era stato corretto per ricreare la famiglia di origine...... mi sbaglio??

Come dobbiamo comportarci?

Saluti

Diego Rossi

**Comment by frmariani** [comment]
ribadisco che per noi l'assistenza ai Comuni è un'attività prioritaria, quindi mi scuso  per l'accaduto ma chiedo gentilmente, per la prossima volta,  di appuntare il codice operatore fornito all'inizio della telefonata; 
come giustamente intuito, la famiglia è ormai chiusa essendo uscito l'ultimo componente della stessa; ad oggi, in questi casi, l'annullamento dell'operazione di cancellazione non è possibile.
Potete effettuare una re-iscrizione indicando l'idanpr precedentemente assegnato ai cittadini. 
come da accordi per le vie brevi, in caso di ulteriori problemi potete contattarmi via mail.
