### ISSUE TITLE
Cessazione convivenza di fatto per iscrizione AIRE

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1523]
Comune di Modena - Ambiente di produzione

Buongiorno,
dovremmo cessare la convivenza di fatto di due soggetti a causa della loro iscrizione in AIRE;  i motivi di cessazione presenti nella tabella non consentono di gestire questa casistica, peraltro imposta dalla Circolare del Ministero dell’Interno del 6 febbraio 2017, n.231:

'La disciplina introdotta dalla Legge 76/2016 in materia di Convivenze di Fatto si applica per "espressa previsione di legge" solo a cittadini italiani o stranieri, residenti in Italia e non ne prevede l' applicazione ai cittadini iscritti in AIRE'.

E' previsto che la tabella dei motivi di cessazione venga aggiornata? 

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
Può usare "Chiusura d'ufficio per cancellazione del soggetto"; di fatto, sta cancellando i cittadini in ANPR e li sta iscrivendo in AIRE.

Comunque, a questo proposito,  sentiremo il Ministero dell'Interno.

**Comment by sfmodena** [comment]
Buongiorno,
ho tentato di utilizzare la motivazione "Chiusura d'ufficio per cancellazione del soggetto" ma mi viene restituito questo errore:

Incongruenza dati anagrafici: la scheda soggetto del comune non coincide con quella specificata nella richiesta (xxxx yyy) (Codice: EN073)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-08-13 08:51:35 , idOperazioneANPR 112258192 (Codice: EN527)

Non riesco a capire dove sia l' incongruenza, in consultazione i dati della convivenza di fatto sembrano corretti; per cortesia potete darmi qualche indicazione su come individuare l' errore?

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
abbiamo riscontrato un piccolo malfunzionamento, potete riprovare per favore ?

**Comment by sfmodena** [comment]
Buongiorno,
siamo riusciti a portare a termine l' operazione. L' unica stranezza è che durante l' inserimento della mutazione di "risoluzione convivenza" per poter proseguire abbiamo dovuto reinserire alcuni dati nella sezione "convivenza di fatto", in particolare l' altro soggetto appartenente alla convivenza e il comune dell' evento.  Ora comunque sembra tutto regolare.
Grazie per la collaborazione, saluti
