### ISSUE TITLE
[Webapp 2003] nuovo is con data decorrenza sbagliata?

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1524]
Ambiente di produzione, id cittadino 59289245.
Per un problema che non riuscivo a identificare sul nostro applicativo, abbiamo fatto l'operazione di cancellazione per trasferimento in comune non subentrato dalla webapp. Il nostro problema l'ho identificato, qui scrivo per un dato che mi sembra sbagliato nella operazione fatta dalla webapp.

Il cittadino è in famiglia con la moglie id 59289289.
nella cancellazione con decorrenza 5/8/2019 viene quindi incluso il ramo per identificare la moglie come nuovo IS, ma la webapp scrive come data decorrenza del legame IS della moglie 12/12/2011, invece della data decorrenza di cancellazione del marito.
l'operazione webapp è la id 112283998.

**Comment by frmariani** [comment]
Da web app, nella consultazione della famiglia di appartenenza di un cittadino, troviamo le seguenti tre date:
Data di origine della Famiglia/Convivenza - data in cui si è creata la famiglia;
Data decorrenza appartenenza - la data da cui quello specifico cittadino appartiene alla famiglia in questione;
Data di decorrenza legame - data in cui il cittadino ha acquisito quello specifico ruolo all'interno della famiglia.
Nel suo caso non ravviso nessuna incongruenza.
Le ribadisco che per casi di assistenza specifica deve contattare l'assistenza ANPR al numero verde 800863116;

**Comment by MarcoMigliori** [comment]
> Data di decorrenza legame - data in cui il cittadino ha acquisito quello specifico ruolo all'interno della famiglia.

Il senso della mia segnalazione non è sul caso specifico, ma sulla webapp.
Ho fatto una cancellazione altri motivi indicando decorrenza cancellazione 5/8/2019 per il marito, e indicando nel succedersi di videate la moglie come is, senza che il programma richieda alcuna data di decorrenza per la moglie. correttamente a mio avviso perchè vale la stessa del marito.

controllando dalla consultazione, il xml dell'operazione inviata dalla webapp, con sorpresa ho visto :
```
<dataDecorrenzaCancellazione>2019-08-05</dataDecorrenzaCancellazione>
...
<elencoSoggetti>
...
<legameSoggetto>
<tipoLegame>3</tipoLegame>
<dataDecorrenza>2011-12-12</dataDecorrenza>
<codiceLegame>1</codiceLegame>
```

Io vedo una incongruenza tra le due date. O almeno quando noi inviamo la stessa operazione da ws, indichiamo la data di cancellazione come data di cambio rel.par. per la moglie.
Chiarita la mia segnalazione, per me si può chiudere. Era solo per darvi il modo di verificare.

**Comment by frmariani** [comment]
omette una parte di xml
                <legameSoggetto>
                     <tipoLegame>3</tipoLegame>
                     <dataDecorrenza>2011-12-12+01:00</dataDecorrenza>
                     <codiceLegame>1</codiceLegame>
                     <progressivoComponente>1</progressivoComponente>
                     "<dataDecorrenzaLegame>2019-08-05+02:00</dataDecorrenzaLegame>"
                  </legameSoggetto>

**Comment by frmariani** [comment]
omette una parte dell'oggetto legame soggetto

               `<legameSoggetto>
                     <tipoLegame>3</tipoLegame>
                     <dataDecorrenza>2011-12-12+01:00</dataDecorrenza>
                     <codiceLegame>1</codiceLegame>
                     <progressivoComponente>1</progressivoComponente>
                     **<dataDecorrenzaLegame>2019-08-05+02:00</dataDecorrenzaLegame>**
                  </legameSoggetto>`

**Comment by frmariani** [comment]
**<dataDecorrenzaLegame>2019-08-05+02:00</dataDecorrenzaLegame>**

**Comment by MarcoMigliori** [comment]
nel xml scaricato da consultazione ANPR non la vedo. ma meglio così, scusatemi per la segnalazione.
io vedo questo:

```
<legameSoggetto>
<tipoLegame>3</tipoLegame>
<dataDecorrenza>2011-12-12</dataDecorrenza>
<codiceLegame>1</codiceLegame>
<progressivoComponente>1</progressivoComponente>
</legameSoggetto>

```
