### ISSUE TITLE
Richiesta annullamento id operazione ANPR n. 12732600

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1525]
In produzione Comune di Cesena codice istat 040007.

Annullando l’operazione di Mutazione Residenza APR id operazione ANPR n. 12732600 con data decorrenza 20/07/2018 riceviamo l’anomalia L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa.

Nell’operazione Id Anpr n. 12732600 muta residenza e famiglia il cittadino Id Anpr numero 18586988.

A seguito di tale operazione muta relazione di parentela anche il cittadino 18586989 con Id operazione ANPR n. 12732607 con la stessa data di decorrenza dell’operazione 12732600.

In seguito, il cittadino 18586989 viene cancellato per altri motivi con Id Operazione 13009159 con decorrenza 19/07/2018.

Richiediamo l’annullamento dell’operazione 12732600 senza dover annullare la cancellazione Id Operazione 13009159.

Attendiamo gentile riscontro.

Grazie

**Comment by frmariani** [comment]
Nulla osta all'annullamento della mutazione di residenza, anche in presenza di operazioni successive;
tra le tante indicazioni fornite, manca l'identificativo dell'operazione fallita, ma effettuando una ricerca tra le vostre operazioni, ci sembra che il tentativo di annullamento sia sull'operazione di composizione scheda e non sull'annullamento della mutazione di residenza.

Questi casi necessitano spesso di contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per favore contattate il servizio di assistenza ANPR al numero 800863116.

**Comment by RBiasi** [comment]
Buongiorno,

la ringrazio abbiamo inviato una mail all'indirizzo Segnalazioni ANPR <segnalazioni-anpr@teamdigitale.governo.it> è corretto?
