### ISSUE TITLE
Rettifica data iscrizione famiglie AIRE registrate prima del subentro

### ISSUE THREAD

**Issue by francesca1971** [italia/anpr#1526]
Buongiorno, in seguito a D.L. 22/2019 
dovremmo cambiare la data di decorrenza espatrio e quindi iscrizione AIRE di due famiglie.
L’operazione di espatrio è stata registrata sul nostro applicativo prima del subentro.
Ora, subentrati, non abbiamo trovato fra le varie operazioni  ANPR quella che potrebbe cambiare la data di decorrenza.
E’ corretto annullarne l’iscrizione e reinserire l’espatrio ex novo?
Famiglia AIRE identif anpr 36889569 decorrenza dal 26/6/2019 al 26/03/2019
Famiglia AIRE identif anpr 36889568 decorrenza dal 02/05/2019 al 18/04/2019.
Grazie
Francesca – Ufficiale d’Anagrafe
Comune di Castegnato

**Comment by frmariani** [comment]
I cittadini sono stati aggiunti in ANPR con il subentro e non con un'operazione di Iscrizione, pertanto l'annullamento dell'operazione non è possibile;
in questi casi però, si può utilizzare l'operazione di "Rettifica"  dati subentro: la rettifica sarà possibile per ciascun componente della famiglia e soltanto se non sono state effettuate operazioni dopo il subentro.
Dalla web app di ANPR deve seguire il seguente percorso:
Registrazione > Rettifiche > Dati Controllo: Rettifica dati subentro > Altre date

Se fosse necessario un chiarimento sul caso specifico, contatti il servizio di assistenza ANPR al numero 800863116.
