### ISSUE TITLE
[5008] Errore AEE95 Operazione non effettuabile

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1527]
Buongiorno,
in ambiente di produzione, per il servizio in oggetto, è stato restituito il seguente errore

```
        <listaErrori>
            <errore>
                <codiceErroreAnomalia>AEE95</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-07-11 13:48:26 , idOperazioneANPR 103155132</testoErroreAnomalia>
            </errore>
        </listaErrori>
```
Possiamo avere chiarimenti in merito?

Grazie, cordialmente
Chiara Leanza per il Comune di Torino

**Comment by frmariani** [comment]
non è chiara l'operazione che si tenta di effettuare: modifica dello stato civile o del luogo di nascita;

il codice stato 998 viene utilizzato per indicare uno Stato estero di nascita non più valido; se inserito, nella descrizione, si deve indicare lo Stato estero di nascita non più attuale:  inserire "NON ATTRIBUIBILE" nella descrizione non è corretto ; 

Per un contatto telefonico si avvalga del servizio di assistenza ANPR al numero 800863116.
