### ISSUE TITLE
Interrogazione Cartellino Elettronico CIE da ANPR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1530]
Buongiorno,
chiedo la possibilità di richiedere la consultaione del cartellino elettronico CIE direttamente da ANPR.
Visto che le 2 banche dati sono del Ministero dell'Interno non è possibile prevedere questa funzionalità?

Grazie
Comune di Villa Cortese

**Comment by mttfranci** [comment]
Salve,
Valuteremo con il Ministero la vostra richiesta.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Al momento la richiesta sembra essere esterna al perimetro del progetto ANPR.
Saluti

Assistenza ANPR
