### ISSUE TITLE
posizioni in AT non unificabili

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1531]
Buongiorno,

ambiente di Produzione
idOperazioneANPR: 114367938

cercando di effettuare la rettifica della data di nascita di un individuo il sistema restituisce il seguente errore:
"Individuate due posizioni in AT non unificabili"

Abbiamo provato dal portale a verificare con l'utility per la risoluzione dei disallineamenti con l'AE, ma l'individuo ha gli stessi dati sia in ANPR che in AE.
Provando comunque ad unificarli esce il seguente errore (è un errore ma compare in verde, credo sia un'anomalia):
"Esito AE: Richiesta incongruente - soggetto validato in Agenzia Entrate (Codice 92)"

In questi giorni sta succedendo a diversi comuni di avere problemi con queste posizioni non unificabili e non poter far nulla da portale per risolvere.

Potete verificare? Grazie

Cordiali saluti.

**Comment by azabatta** [comment]
Buongiorno, 
la funzionalità “Risoluzione disallineamenti con Agenzia Entrate“  è stata utilizzata per effettuare il collegamento tra le due posizioni segnalate dal sistema come non unificate?
Ossia  nella richiesta sono stati valorizzati ambedue i codici fiscali (quello presente in ANPR e quello risultante dalla variazione dei dati anagrafici)  ed è stata spuntata l'opzione "collega codice fiscale"?

**Comment by SAlberto** [comment]
Il 23 agosto 2019 l'opzione "collega codice fiscale" non era presente.
E poi comparsa il 27 agosto
