### ISSUE TITLE
Caricamento file subentro in portale di presubentro: "Salvataggio del file in ATMOS fallita"

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1532]
A partire da questa mattina, tentando di caricare i file APR o AIRE nei portali di presubentro, in alcuni Comuni (Petrizzi, Castelseprio, Crognaleto) appare l'errore in oggetto.

**Comment by mttfranci** [comment]
Stiamo verificando la situazione.

**Comment by mttfranci** [comment]
Dovremmo aver individuato la causa, potreste riprovare?
Grazie in anticipo.

**Comment by fmbianchi** [comment]
Confermo che la questione è stata risolta: oggi i caricamenti negli stessi Comuni avvengono con successo.
Saluti e grazie

**Comment by mttfranci** [comment]
Perfetto, grazie del riscontro.
