### ISSUE TITLE
 EC073  - codSpecie:  è inesistente sulla tabella di riferimento

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1533]
Dopo aver inviato il file di pre-subentro per tutti i cittadini viene segnalato l'errore EC073, probabilmente un errore nella formattazione del tag Residenza; si riporta di seguito come lo abbiamo formattato :

<residenza>
             <tipoIndirizzo>1</tipoIndirizzo>
             <indirizzo>
                 <cap>20867</cap>
                 <comune>
                     <nomeComune>CAPONAGO</nomeComune>
                     <codiceIstat>108052</codiceIstat>
                     <siglaProvinciaIstat>MB</siglaProvinciaIstat>
                 </comune>
                 <toponimo>
                     <specie>VIA</specie>
                     <specieFonte>1</specieFonte>
                     <denominazioneToponimo>DONATELLO</denominazioneToponimo>
                 </toponimo>
                 <numeroCivico>
                     <civicoFonte>2</civicoFonte>
                     <numero>22</numero>
                     <lettera>A</lettera>
                     <esponente1>23</esponente1>
                 </numeroCivico>
             </indirizzo>
            <dataDecorrenzaResidenza>1969-10-28</dataDecorrenzaResidenza>
         </residenza>

Dov'è l'errore ?

**Comment by GabriellaBallabio** [comment]
![formatoIndirizzo](https://user-images.githubusercontent.com/54433203/63690796-df6b6c00-c80d-11e9-9d47-fbdc037186f3.png)

**Comment by amollicone1982** [comment]
L'errore sta nel fatto che dichiarate specieFonte=1 e inserite il campo specie per il quale speciefonte deve essere 2. 

Riassumendo:
specieFonte=1 -> inserire campo codSpecie che è ricavato dalla tabella 4
specieFonte=2 o null -> inserire campo descrittivo specie
