### ISSUE TITLE
ES128  -  La data di prima iscrizione non risulta valorizzata

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1534]
COMUNE : CAPONAGO (MB)
FORNITORE : SCAP SISTEMI
AMBIENTE : PRE-SUBENTRO

L'errore riguarda tutti i cittadini.

Di seguito le date impostate nel tag soggetto

dataNascita : 1940-09-28
dataUltimo Aggiornamento :  2019-06-25
dataDecorrenza Residenza : 1940-09-28
dataDecorrenza Famiglia :1940-09-28

Dove indichiamo la data di prima iscrizione ?

**Comment by amollicone1982** [comment]
Va indicata come ultimo campo (<dataPrimaIscrizioneComune>) all'interno del tag generalitaSubIscr come indicato nella documentazione.
