### ISSUE TITLE
AGGIORNAMENTO DELLE BASI DATI LOCALI DEL COMUNE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1535]
Considerato un Ente che decide di utilizzare la Web Application (WA) di ANPR per le registrazioni anagrafiche, al fine dipoter tenere aggiornare la base dati locale per l'utilizzo dei dati anagrafici per la gestione elettorale oppure tributaria, la software house fornitrice dovrà mettere a disposizione un WS che consenta di acquisire localmente i dati delle operazioni effettuate. Parliamo quindi di "ACQUISIZIONE TRAMITE ENDPOINT" .

La domanda è : quindi per ogni tipo di operazione (iscrizione, decesso, emigrazione, etc.) im comune riceverà una notifica ?
Nel tag "contenuto" convertito in Base64 è contenuta la struttura xml con i dati del cittadino ?

**Comment by fferraguto** [comment]
Salve,
è possibile attivare un endpoint, nel qual caso ricevereste una notifica NRIS per ogni operazione effettuata (contiene la risposta all'operazione).
Tuttavia la modalità di aggiornamento delle banche dati locali consigliata è quella che passa attraverso l'utilizzo del servizio 4005. Questo consente l'interrogazione delle notifiche per intervallo temporale e restituisce la notifica compressa in un file GZip codificato in base64.
Si rimanda all'issue https://github.com/italia/anpr/issues/1277 per ulteriori dettagli sulla politica di orchestrazione del servizio.
A presto.

**Comment by GabriellaBallabio** [comment]
Quindi come software house dobbiamo realizzare un WS con due metodi :
RichiestaN000 e RispostaN000 è corretto ? 
Entrambi i metodi verranno invocati da ANPR ?
La notifica NRIS che riceviamo cosa contiene ? solo l'id operazione oppure anche il file xml con i dati del cittadino da aggiornare in base64 ?
