### ISSUE TITLE
Id operazione ANPR: 28131233

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1536]
Salve in merito alla richiesta in oggetto.
L'altro giorno ci siamo accorti che questo cittadino non era presente in ANPR.
Per cui abbiamo provveduto a un "iscrizione altri motivi"

Per cui abbiamo completato l'iscrizione.
Tuttavia la stessa me la da in sospeso.

Tra l'altro il cittadino sembrerebbe iscritto.
Per cui o ho sbagliato qualcosa (magari facendo due operazioni sullo stesso cittadino e una lasciandola incompleta)
Oppure la stessa è rimasta in sospeso perché mancano dei dati.

Nel caso in cui fosse la seconda possibilità notavo che pur avendo mantenuto il cittadino "celibe" se non inserisco i dati del matrimonio non mi permette di andare avanti riuscireste a effettuare un controllo?

Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
mi può contattare per avere maggiori dettagli e verificare la scheda anagrafica ? 
grazie 
Cecilia Migliardi
cmigliardi@sogei.it

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
ho richiesto un contatto diretto -
