### ISSUE TITLE
[1002] Re-Iscrizione di soggetto già subentrato: Codice Fiscale variato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1537]
ambiente di PRODUZIONE - comune di FAENZA (039010)

idSoggettoANPR 19184678

il soggetto è stato iscritto per immigrazione (ws 1002) nel 2017, con codice fiscale numerico.
nel marzo 2019 è emigrato verso comune NON subentrato (ws 2003), sempre con CF numerico.
oggi ritorna, e nel frattempo gli è stato assegnato un codice fiscale alfanumerico, e la situazione è la seguente:
- in AE ha un codice fiscale alfanumerico
- in ANPR ha ancora il codice fiscale numerico

indipendentemente dal codice che si tenta di passare con l'iscrizione (abbiamo tentato sia col numerico che con l'alfanumerico) l'operazione viene bloccata a causa di errori di tipo EAxxx.
l'iscrizione è andata a buon fine attivando il GestioneCF '3' (nessuna validazione), ma adesso in ANPR il soggetto non ha più il codice fiscale e sembra non si riesca a variare con mutazioni successive... (secondo le vostre indicazione, procederemo con l'annullamento dell'iscrizione e ripartiremo).

questo che si porta come esempio è un caso specifico che se volete potete verificare partendo dall'idSoggettoANPR, ma ce ne sono altri similiari in attesa di essere passati.

non si vuole entrare nel merito del singolo caso, ma vorremmo avere le indicazioni precise da eseguire per allineare situazioni come queste, ovvero, quali informazioni indicare a livello "CF per ricerca", "CF" e "GestioneCF" per ottenere il risultato atteso.

grazie.

Alessandro Monopoli ADS

**Comment by azabatta** [comment]
Buonasera, 
l'identificativo operazione ANPR  del ws 5008 utilizzato per inserire il codice fiscale corretto è 115551524?
Se non fosse più disponibile è possibile riprovare l'allineamento e comunicare il relativo identificativo operazione ANPR?
Grazie

**Comment by AMonopoliADS** [comment]
la comunicazione con idANPR 115551524 è stato l'ultimo tentativo di aggiornamento del codice fiscale, con le seguenti caratteristiche:
- generalitaPerRicerca.codiceFiscale: il CF numerico
- generalitaDaModificare.codiceFiscale: il CF alfanumerico
e ritorna l'errore:
```
<errore>
  <codiceErroreAnomalia>ES102</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Codice fiscale 99999999999 non presente o scheda archiviata</testoErroreAnomalia>
</errore>
```

questa mattina ho fatto un altro tentativo - che è andato a buon fine - con l'idANPR 115983157
la comunicazione aveva le seguenti caratteristiche:
- generalitaPerRicerca.codiceFiscale: non valorizzato
- generalitaDaModificare.codiceFiscale: il CF alfanumerico
- gestioneCF: 0
ANPR è stato aggiornato con il CF alfanumerico, che risulta validato

la situazione è stata quindi gestita, tra vari tentativi, con questi passaggi:
- iscrizione con ws1002, senza indicazione di codiceFiscale e gestioneCF '3'
- mutazione con ws 5008, con la sola indicazione di generalitaDaModificare.codiceFiscale e gestioneCF '0'

mi chiedo se sia l'unico percorso da seguire, oppure se ci siano altre strade che permettano all'operatore di utilizzare i dati gia presenti nell'anagrafe locale e nell'ANPR (nel caso specifico, il codice fiscale).

grazie

**Comment by azabatta** [comment]
Buongiorno, 
sì, per questa casistica l'unica soluzione possibile è quella individuata.
Nei casi in cui un CF è diventato "collegato" il suo utilizzo è inibito da Agenzia Entrate in quanto non più attuale.
La richiesta di mutazione comprensiva del precedente CF non andava a buon fine in quanto la posizione corrente del cittadino in ANPR era priva di codice fiscale (da qui l'errore ES102).

**Comment by AMonopoliADS** [comment]
ok. diremo al cliente di seguire queste indicazioni.
grazie
