### ISSUE TITLE
Ambiente FREE

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#1539]
Salve,
l'ambiente FREE che noi utilizziamo per fare i test è oramai non funzionante da circa 30 giorni, come si evince da issues [1501](https://github.com/italia/anpr/issues/1501)
Quando verrà ripristinato tale ambiente, dato che al momento siamo impossibilitati a fare qualsiasi tipo di test.
Grazie

**Comment by mttfranci** [comment]
Salve,
Dovremmo aver risolto l'anomalia.
Potreste riprovare?
Grazie in anticipo.

**Comment by Eduardo1977** [comment]
Buongiorno, ho appena utilizzato i servizi 3002 e 6001 con successo. Grazie

**Comment by Antonino09** [comment]
Salve, anch'io ho provato ad utilizzare i servizi 6001 e 1001 funzionano correttamente .
Grazie
