### ISSUE TITLE
Indirizzo PEC

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#154]
Buongiorno

siamo il gruppo di lavoro del Comune di Milano e stiamo effettuando le prove del Subentro. Avremmo da porre una richiesta organizzativa.
La comunicazione dell'esito delle elaborazioni viene spedita all'indirizzo di posta PEC indicato a suo tempo. Il problema è che il Comune di Milano riceve giornalmente centinaia di mail, e ora che la mail viene smistata al Settore corretto e poi arriva a noi, passano diversi giorni.
Avremmo quindi la necessità che scriveste anche all'indirizzo mail del nostro gruppo di lavoro, in modo da ricevere i risultati in tempo reale.
Questo è il nostro indirizzo: Sipo.IBM@comune.milano.it

Grazie
Raffaella Tremolada
Sistemi Informativi srl

**Comment by gcarbonin** [comment]
Per modificare la casella di destinazione potete utilizzare la funzione di amministrazione disponibile nella WA (in alto a destra della home page).
