### ISSUE TITLE
[A006] errore EN237 non comprensibile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1540]
Ambiente di produzione, comune di Fornovo di Taro

Tentando di espatriare un cittadino dall'APR del comune con il servizio in oggetto otteniamo l'errore "EN237 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata" (id operazione ANPR 115695661).
Non riusciamo però a capire la causa, dato che in ANPR il cittadino ha come decorrenza residenza  una data del 2001 mentre la mutazione A006 viene richiesta con decorrenza 15/01/2016

Qual è la causa del blocco ?

Grazie

**Comment by azabatta** [comment]
Buonasera, 
la famiglia di destinazione del cittadino ha data origine e data decorrenza residenza 27/09/2018.

Per  rispettare le date effettive degli eventi anagrafici si potrebbero annullare le due mutazioni effettuate sulla persona già presente nella famiglia di destinazione, completare la mutazione AIRE per il soggetto in questione con creazione nuova famiglia in data 15.01.2016  ed aggregare poi la persona iscritta all'AIRE il 27.09.2018 alla famiglia così creata.

**Comment by busaster** [comment]
In realtà la nostra mutazione viene fatta chiedendo la creazione di una nuova famiglia AIRE (nella richiesta abbiamo <attribuzioneFamigliaAIRE>2</attribuzioneFamigliaAIRE>)

**Comment by azabatta** [comment]
Il controllo è  sicuramente  impreciso tuttavia evita una duplicazione dell’identificativo comunale della famiglia, per il caso specifico basta quindi utilizzare un nuovo identificativo.

**Comment by busaster** [comment]
In effetti il problema è che la famiglia AIRE con i dati 

`<idFamigliaConvivenzaComune>      <idFamigliaConvivenzaComuneIstat>034017</idFamigliaConvivenzaComuneIstat>
      <idFamigliaConvivenza>FE0004981</idFamigliaConvivenza>
    </idFamigliaConvivenzaComune>`

già esisteva in ANPR ma non nella base dati locale.
Abbiamo risolto sistemando gli identificativi.

grazie
