### ISSUE TITLE
[4001/7002] EN122 La richiesta effettuata non produce alcun risultato

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1541]
Buongiorno effettuando una richiesta 4001 idOperazioneANPR 13827437
la successiva 7002 di richiesta risultati idOperazioneANPR 13827646
torna l'errore in oggetto ma non ne comprendo il motivo.

CARTOCETO - PRE SUBENTRO
Grazie mille
Riccardo

**Comment by mttfranci** [comment]
Dovreste poter interrogare adesso.
Da notare che le elaborazioni asincrone possono impiegare fino a 24 ore in alcuni casi.
Saluti

Assistenza ANPR
