### ISSUE TITLE
Quindi come software house dobbiamo realizzare un WS con due metodi :

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1543]
Quindi come software house dobbiamo realizzare un WS con due metodi :
RichiestaN000 e RispostaN000 è corretto ? 
Entrambi i metodi verranno invocati da ANPR ?
La notifica NRIS che riceviamo cosa contiene ? solo l'id operazione oppure anche il file xml con i dati del cittadino da aggiornare in base64 ?

_Originally posted by @GabriellaBallabio in https://github.com/italia/anpr/issues/1535#issuecomment-526180927_

**Comment by fferraguto** [comment]
Salve,
nel descrittore del servizio (wsdl):
	<wsdl:portType name="AnprPortTypeN000">  
		<wsdl:operation name="inoltroNotificaANPR">
			<wsdl:input message="tns:RichiestaN000"></wsdl:input>
			<wsdl:output message="tns:RispostaN000"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>

il nome dell'operation (metodo) da implementare è "inoltroNotificaANPR" che riceve in input un messaggio di tipo RichiestaN000 e deve rispondere con un messaggio di tipo RispostaN000.

Quindi ANPR chiamerà il servizio "inoltroNotificaANPR" passando come input una RichiestaN000 che, come da specifica, è composta da una testata e da un contenuto in base64 che contiene esattamente la risposta all'operazione cui la notifica si riferisce. Le risposte alle operazioni seguono ovviamente le specifiche dei servizi.

Ovviamente il servizio di accoglienza delle notifiche prevede la realizzazione dell'infrastruttura di sicurezza necessaria.

A presto

**Comment by GabriellaBallabio** [comment]
"da un contenuto in base64 che contiene esattamente la risposta all'operazione cui la notifica si riferisce" la notifica contiene un xml con i dati relativi al tipo di operazione eseguita dall'operatore del comune ? Per esempio nel caso di "ISCRIZIONE" il file XML (passato in base64) risponderà a file XSD : 1000iscrizione.xsd ?

**Comment by fferraguto** [comment]
Ad esempio, nel caso di iscrizione per nascita, si riceverà una Risposta1001, la cui definizione si trova nel file 1000iscrizione.xsd:

		<wsdl:operation name="iscrizione_nascita">    
			<wsdl:input   message="tns:Richiesta1001"/>    
			<wsdl:output  message="tns:Risposta1001" />  
		</wsdl:operation>

**Comment by GabriellaBallabio** [comment]
Dove posso trovare la documentazione necessaria da fornire ai sistemisti del comune per la realizzazione dell'infrastruttura di sicurezza necessaria ?
E' possibile conoscere l'indirizzo IP oppure il gruppo di indirizzi IP dai quali verrà invocato il metodo del WS per il recapito delle notifiche ?

**Comment by fferraguto** [comment]
Si trova sul sito dell'ANPR:
https://www.anpr.interno.it/portale/home
se guardate la guida, all'interno trovate il link alla documentazione tecnica (è il secondo link "documentazione tecnica") che per brevità riporto di seguito:
[](https://www.anpr.interno.it/portale/documents/20182/239162/MI-14-AN-01+SPECIFICHE+DI+INTERFACCIA+WS_24_05_2018.pdf/f82140c7-7a24-4db1-a152-f318ae1dd19a)

Le parti di interesse sono il capitolo 6 ed in particolare il paragrafo 6.2.
