### ISSUE TITLE
[2001] Soggetto Deceduto in Giorno Imprecisato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1544]
ambiente di TEST- comune di FAENZA (039010)

abbiamo il caso di un soggetto deceduto in giorno non precisato.

in ambiente di TEST abbiamo simulato l'evento sul soggetto con idANPR 27257326, passando il flag datiDecesso.senzaGiorno valorizzato a '1' (ws 2001)

a livello di consultazione (verificando l'xml della response del ws 3002) vediamo  che il flag è stato acquisito da ANPR, ma:
- nella consultazione su web-app la data di decesso viene visualizzata per intero, senza annotazioni relative al "senzaGiorno"
- nella certificazione (anagrafica di morte) la data di decesso viene indicata per intero, senza annotazioni relative al "senzaGiorno".

ci sfugge qualcosa? oppure il flag non è gestito correttamente lato ANPR?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
potete riprovare la consultazione per favore ?

**Comment by AMonopoliADS** [comment]
nella consultazione adesso viene barrato il giorno e compare il check "solo mese anno"

**Comment by frmariani** [comment]
La issue viene chiusa, in caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.

**Comment by AMonopoliADS** [comment]
l'aggiornamento non è stato esteso alla certificazione, dove invece continua a comparire la data in chiaro.
forse meglio riaprire la segnalazione?
inoltre vorrei sapere se la modifica è già stata propagata anche all'ambiente di produzione
grazie

**Comment by frmariani** [comment]
stiamo provvedendo alla modifica sulla certificazione;
la precedente modifica è già stata propagata in ambiente di produzione.

**Comment by frmariani** [comment]
modifica effettuata in tutti gli ambienti;
potete riprovare

**Comment by AMonopoliADS** [comment]
da verifiche effettuate risulta corretta sia la consultazione che la certificazione (sia in TEST che in PROD)
grazie
