### ISSUE TITLE
[5001] - Rettifica tipo scheda famiglia

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#1545]
In ambiente di subentro, per errore materiale, a seguito di una iscrizione in ANPR, è stata creata una famiglia con **TipoScheda = 3** laddove in realtà si tratta di una Convivenza (**TipoScheda = 4**).  C'è un sistema, anche tramite WebApp, per poter "rettificare" questo dato, senza dover annullare l'iscrizione del soggetto? 
Aggiungo che l'errore non è stato evidente perché il sistema consente di poter specificare anche, per il TipoScheda = 3, dati che sono specifici delle Convivenze come il nome e il tipo.
L'Id Anpr della famiglia è 15536074.

Grazie.

Alessio Tropeano
Datagraph srl

**Comment by azabatta** [comment]
Buongiorno, 
la rettifica di questi dati non è prevista. Non è necessario annullare la mutazione con cui il cittadino ha cambiato comune di residenza,  l'evento che ha generato l'errore è successivo:  id operazione ANPR 84707575 - 5001 mutazione famiglia convivenza  - codice mutazione 3 (sono presenti anche operazioni successive).

**Comment by azabatta** [comment]
La issue viene chiusa. Nel caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa.
Se il comune desidera essere seguito in maniera puntuale può aprire una segnalazione al numero verde 800863116.
