### ISSUE TITLE
[5008] annullamento dati dell'atto di nascita

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1546]
ambiente di PRODUZIONE - comune di VALEGGIO SUL MINCIO (023089)

immigra da comune subentrato, soggetto (idANPR 46426102) con questo gruppo di dati riguardanti l'atto di nascita:
```
<attoNascita>
  <comuneRegistrazione>
    <nomeComune>Assente</nomeComune>
    <siglaProvinciaIstat>--</siglaProvinciaIstat>
  </comuneRegistrazione>
  <anno>1954</anno>
  <parte>0</parte>
  <numeroAtto>00000</numeroAtto>
</attoNascita>
```

a parte rilevare l'inconsistenza dei dati che mi aspetterei non venissero inviati in fase di subentro, segnalo che il cliente vorrebbe procedere alla "pulizia" dei dati.

la comunicazione con ws 5008 e tipoMutazione '15' va in errore perchè il sistema si aspetta il tag attoNascita, che però in questo caso - con lo scopo di ripulirlo - non viene indicato.

in che modo risolvere?

grazie.
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
A tale scopo è possibile usare il servizio di 5013 (Revoca dato) indicando come tipoRevoca 11(revoca atto di nascita) o la funzione eliminazione dati da app web presente sotto Registrazione

**Comment by AMonopoliADS** [comment]
grazie Angelo.

a onor del vero avevo immaginato che la revoca potesse essere la soluzione, ma proprio stamattina - prima di scrivervi - ho scaricato dal portale ANPR la tabella 48 - tipi revoca, che però censisce solo 10 codici (ultimo il codice '10' - carta di identita)

proviamo come mi hai indicato.

grazie

**Comment by amollicone1982** [comment]
Ha ragione, procederemo con l'aggiornamento della tabella 48

**Comment by AMonopoliADS** [comment]
data 2019-08-30 11:53:58 , idOperazioneANPR 116467454

la comunicazione di revoca dell'atto di nascita si blocca con questo errore:
<errore>
  <codiceErroreAnomalia>EN505</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>L'operazione di revoca e' possibile solo a valle del subentro</testoErroreAnomalia>
</errore>

**Comment by amollicone1982** [comment]
Mi scusi, non avevo verificato che non veniva da subentro. In questi casi è permessa la sola modifica dell'atto.

**Comment by AMonopoliADS** [comment]
Non ho i dati sotto mano, ma direi che si tratti di soggetto nato all'estero senza atto di nascita trascritto.
I dati presenti sono da eliminare, non da sostituire.

Chiedo:
Perché questo blocco della revoca collegato al subentro? La revoca di paternità e maternità, ad esempio, che abbiamo già effettuato anche in passato, non è soggetta allo stesso blocco...

Come fare per risolvere?
Grazie

**Comment by amollicone1982** [comment]
Se ci invia una pec a Assistenza.anpr@pec.sogei.it con la richiesta di cancellazione del dato la facciamo immediatamente

**Comment by AMonopoliADS** [comment]
Direi che se ne riparli lunedì, lasciamo che la richiesta la faccia il cliente.
Grazie
