### ISSUE TITLE
Scarico per motivata richiesta vuoto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1547]
Ambiente di test, comune di Poggio a Caiano

ho ieri richiesto tramite la webapp lo scarico XML dei dati con la funzione "Download dati ANPR del comune".
Oggi la richiesta risulta completata ma se vado a scaricare il file tramite "Utilità e notifiche->download file" mi viene ritornato un file che non contiene alcun soggetto

[export_100004.xml.zip](https://github.com/italia/anpr/files/3559137/export_100004.xml.zip)

**Comment by mttfranci** [comment]
La richiesta è stata rigenerata.
Ora dovrebbe essere a posto.
Saluti

Assistenza ANPR
