### ISSUE TITLE
desecretazione scheda

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1548]
Ente produzione comune Levico Terme.

Il comune doveva iscrivere un cittadino a cui è stata desecretata la scheda.
Al momento non siamo a conoscenza di un servizio ad hoc per questa situazione, per cui abbiamo provveduto a fare un'iscrizione per altri motivi.
E' il procedimento corretto? O esiste già un servizio specifico?

Grazie mille

**Comment by rvinzani** [comment]
Buongiorno, non esiste ancora una procedura ad hoc per la gestione dei soggetti sotto protezione. In ogni caso, se il soggetto non è stato conferito in ANPR al subentro, l'iscrizione è la giusta modalità. Ovviamente evitando di inserire dati di provenienza o altre informazioni di dettaglio.
