### ISSUE TITLE
ERRORE VARIAZIONE GENERALITA' (EN527)

### ISSUE THREAD

**Issue by iessicatoro** [italia/anpr#1549]
Il sistema riporta errori nella modifica delle generalità di un cittadino straniero.
Operazione non effettuabile (Codice: AEE95)
Informazioni sull'operazione da fornire 
data 2019-08-29 08:35:11  IdOperazioneANPR 115974178 (Codice: EN527)

Num. Ind. ANPR : 30084301   
Famiglia ANPR numero 16636639

 Iessica Toro 
 Comune di Piacenza       
 U.O. Sistemi Informativi 
 Via Beverora 57 - 29121 Piacenza
 T. 0523.492544 | iessica.toro@comune.piacenza.it

**Comment by frmariani** [comment]
l'operazione indicata contiene la modifica delle generalità di un cittadino con l'indicazione del nuovo codice fiscale calcolato dal gestionale ma inesistente in Agenzia delle Entrate;
in questi casi è necessario effettuare la mutazione dei dati lasciando che sia Agenzia delle Entrate ad emettere il nuovo CF del cittadino.

Il sistema di Issue Tracking basato Github, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per richieste su casistiche particolari che richiedono scambi di informazioni e di dettaglio, dovete  avvalervi del servizio di assistenza ANPR al numero 800863116.
