### ISSUE TITLE
ANOMALIE SUBENTRO - ERRORI EN306 e EC004

### ISSUE THREAD

**Issue by mstagnoli** [italia/anpr#155]
Ambiente di PRE-SUBENTRO Comune di Corbetta
Buongiorno, nelle anomalie di subentro di alcune schede individuali abbiamo rilevato  i seguenti codici di errore EN306 e EC004.
Abbiamo analizzato i dati dei soggetti inviati, ma non siamo in grado di capire quali dati influiscono sul risultato.
Un esempio è il codice individuo (codice APR del comune) è 34992, che prenseta entrambe le anomalie.
Rimaniamo in attesa del vostro riscontro e a disposizione per ulteriori informazioni.

**Comment by gcarbonin** [comment]
Il secondo è risolto intervenendo sul caricamento dei dati.
