### ISSUE TITLE
DECORRENZE RESIDENZE AIRE - DOPO DECRETO BREXIT - COMUNE DI FOIANO DELLA CHIANA (AR)

### ISSUE THREAD

**Issue by 0510180112930006** [italia/anpr#1550]
Buon pomeriggio,
vorremmo sapere come sistemare le decorrenze delle variazioni di residenza dei cittadini italiani residenti all'estero (AIRE), a seguito dell'entrata in vigore del Decreto così detto Brexit.

Restando in attesa di un riscontro, porgiamo Distinti Saluti.

Vorraso.

**Comment by ncapozzi** [comment]
Buongiorno, dipende dai casi.
1 - il cittadino è stato trasmesso con il subentro AIRE. E' possibile modificare la data di iscrizione AIRE utilizzando il WS 5014 - Rettifiche 

2 - il cittadino è stato iscritto come AIRE in ANPR utilizzando i WS A001 o A002 di iscrizione all'AIRE. E' necessario annullare l'iscrizione ed eseguirla nuovamente

3 - il cittadino è stato trasferito dall'Italia all'estero utilizzando il WS A006 di mutazione dati AIRE. E' necessario annullare la mutazione ed eseguirla nuovamente

Le medesime operazioni possono anche essere eseguite utilizzando l'applicazione WEB di ANPR.

Si fa presente che in tutti i casi, se sono state eseguite successive operazioni è necessario annullarle a ritroso.

Per una assistenza operativa diretta su casi specifici, si suggerisce di contattare il numero verde 800863116 fornendo il riferimento di una persona del Comune ed una fascia oraria di reperibilità.

N. Capozzi

**Comment by 0510180112930006** [comment]
Buon pomeriggio,

nello specifico sono cittadini italiani iscritti all'Aire DOPO il subentro in ANPR e gli errori sono nelle decorrenze delle residenza AIRE:

- 1 CONSOLI GIULIA nata il 03/06/1989 nel comune di CASTIGLION FIORENTINO (AR), data protocollo del Cons01 il 04-04-2019 e decorrenza iscrizione in ANPR è 10-04-2019 (che è la data del nostro protocollo), in mancanza dell'indicazione da parte del Consolato della data 'della domanda' è corretta?;

- 2 EL BOUKA ADIL nato il 30/07/1985 nel comune di KHOURIBGA (Marocco), nucleo familiare composta da 4 persone, decorrenza 26-03-2019 data della 'domanda' indicata nel Cons01 21-10-2018, 

Cons01 pervenuto il 11-06-2019 - ANPR non consente la rettifica e questo è il messaggio: 1 Errore Anpr Cod: EN532 - Rettifica non permessa in quanto il soggetto ha effettuato un cambio di residenza - Cognome: EL BOUKA Nome: ADIL CF: 

- 3 GUERRERO EMELY nata il 21/10/2016 nel comune di MINDEN(Germania), iscritta AIRE per nascita, ma in ANPR ha la data di registrazione in anagrafe 27-07-2019 e non quella corretta cioè di registrazione dell'atto di nascita il 10-07-2019.

Come possiamo procedere per correggere queste decorrenze?

 

Distinti Saluti.

 

 

 

Da: ncapozzi [mailto:notifications@github.com] 
Inviato: lunedì 2 settembre 2019 12:41
A: italia/anpr
Cc: 0510180112930006; Author
Oggetto: Re: [italia/anpr] DECORRENZE RESIDENZE AIRE - DOPO DECRETO BREXIT - COMUNE DI FOIANO DELLA CHIANA (AR) (#1550)

 

Buongiorno, dipende dai casi.
1 - il cittadino è stato trasmesso con il subentro AIRE. E' possibile modificare la data di iscrizione AIRE utilizzando il WS 5014 - Rettifiche

2 - il cittadino è stato iscritto come AIRE in ANPR utilizzando i WS A001 o A002 di iscrizione all'AIRE. E' necessario annullare l'iscrizione ed eseguirla nuovamente

3 - il cittadino è stato trasferito dall'Italia all'estero utilizzando il WS A006 di mutazione dati AIRE. E' necessario annullare la mutazione ed eseguirla nuovamente

Le medesime operazioni possono anche essere eseguite utilizzando l'applicazione WEB di ANPR.

Si fa presente che in tutti i casi, se sono state eseguite successive operazioni è necessario annullarle a ritroso.

Per una assistenza operativa diretta su casi specifici, si suggerisce di contattare il numero verde 800863116 fornendo il riferimento di una persona del Comune ed una fascia oraria di reperibilità.

N. Capozzi

**Comment by 0510180112930006** [comment]
Da: Loredana Vorraso [mailto:lvorraso@comune.foiano.ar.it] 
Inviato: lunedì 9 settembre 2019 14:58
A: 'cnsd.assistenzatecnica@interno.it'
Oggetto: I: Problematiche tecniche nell'accesso all'area riservata ANPR

 

Buongiorno,

con la presente comunichiamo che non riusciamo ad entrare sull'area di ANPR
con la smart card del Sindaco e la sua password.

abbiamo provato ad accedere sia con Google chrome  che con Mozzilla FireFox.

 

Nello specifico vorremmo notizie sul contributo (se è stato erogato o meno)
richiesto nella stessa giornata del subentro di questo comune:

- Comune di FOIANO DELLA CHIANA (AR) - subentrato il 04-03-2019.

 

Restiamo in attesa di un riscontro e porgiamo Distinti saluti.

 

L'UFFICIO ANAGRAFE
