### ISSUE TITLE
ERRORE ACCESSO ALL'AMBIENTE DI PRE-SUBENTRO

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1551]
DATA : 02.09.2019
AMBIENTE : pre-subentro [https://dppre.anpr.interno.it/combas]

DESCRIZIONE ERRORE : 
Accedendo al link https://dppre.anpr.interno.it/combas compare il pannello che consente di selezionare il Certificato , dopo di che compare la scheda che consente di indicare Esername e Password. Digitando le credenziali utilizzate e funzionanti fino ai primi di agosto la pagina viene ricaricata cancellando il contenuto delle richieste Username e Password senza segnalare alcun errore. Di fatto però non si riesce ad accedere all'ambiente di pre-subentro per caricare i file.

Estratto da un'altra issue 
 "Si comunica che le operazioni sono concluse pertanto sarà possibile da adesso accedere all'ambiente di presubentro 
solo utilizzando le credenziali dell'ambiente di produzione (certificati e smart card)."

Non è chiara questa frase srembrerebbe che accedendo al pre-subentro debba chiedere il certificato e il pun della smart card ... ma ciò non accade ...

Abbiamo aperto 5 diverse richieste di assistenza ad ANPR (800863116) la scorsa settimana ed abbiamo ottenuto 5 risposte differenti e nessuna risolutiva.

Potete aiutarci ?

COMUNE : Caponago (MB) 
OPERATORE DEL COMUNE : Varisco M.Giuseppina
SOFTWARE HOUSE : SCAP Sistemi
TECNICO : Ballabio Gabriella

**Comment by Leonforte** [comment]
Ambiente Pre-Subentro
per accedere alla WebApp 
occorre installare il certificato di postazione di produzione  
ed utilizzare una Smart Card attiva  
la url è:  
https://dppre.anpr.interno.it/com
(non si può utilizzare https://dppre.anpr.interno.it/combas perché si accede solo con la Smart Card)


Buongiorno,  
comunichiamo che il 15 luglio 2019 sono state aggiornate le politiche di sicurezza per l’accesso agli ambienti di Pre-Subentro e Test-Comuni. 
 
Per l’accesso all’ambiente di PRE-SUBENTRO, a partire dalla data sopra indicata,  non è più possibile accedere con  le credenziali generiche ma soltanto con gli stessi dispositivi di sicurezza (smart card, certificati di postazione e credenziali) dell’ambiente di produzione a disposizione degli operatori del Comune. RICORDIAMO che tali dispositivi di sicurezza non possono essere ceduti a terzi.  
 
Per l’accesso all’ambiente di TEST COMUNI  è previsto l’accesso con credenziali nominali (e non più generiche) previo censimento da parte degli Amministratori Locali di Sicurezza dei Comuni, sulla console di test, degli utenti che dovranno accedere all’ambiente di TEST. Per tale ambiente, al fine di consentire ai comuni di effettuare il censimento degli utenti è stato stabilito che le credenziali generiche rilasciate sino alla data del 15/07/2019  potranno essere utilizzate sino al 15 settembre 2019 (dopo questa data saranno cancellate). 
 
Tali politiche di sicurezza sono adottate in ottemperanza all’avviso pubblicato il 25 giugno 2019 sul sito ANPR disponibile al seguente link https://www.anpr.interno.it/portale/documents/20182/209665/Avviso+nuove+modalit%C3%A0+accesso.pdf/5a7eead9-9aba-4999-9189-6d5afeca4beb
 
 
Di seguito si riportano le indicazioni principali e le relative Issue di dettaglio.   
 
Ambiente Pre-Subentro
per accedere alla WebApp 
occorre installare il certificato di postazione di produzione  
ed utilizzare una Smart Card attiva  
la url è:  
https://dppre.anpr.interno.it/com
(non si può utilizzare https://dppre.anpr.interno.it/combas perché si accede solo con la Smart Card)
 
se invece il Comune utilizza Web Services 
occorre installare  il certificato di postazione di produzione  (es.   001156-PC-001.p12) 
ed utilizzare una utenza censita  in ambiente di Produzione. 
 
 
Ambiente Test-Comuni   
per accedere alla WebApp 
si utilizza sempre  il certificato di postazione  di test   (es.  001156-CO-0000.p12) inviato alla PEC del Comune
ed una utenza nominale (codice fiscale e password)
la url è la stessa cioè:
https://dptest.anpr.interno.it/combas
tuttavia – per dar modo all’ALS di ciascun Comune di censire tutti gli utenti - fino al 15 settembre è possibile usare ancora  l’utenza generica. (es.   TESTCOMUNI001156 e la relativa password) 
 
In particolare, tutti gli ALS censiti in ambiente di Produzione, sono stati migrati in ambiente di Test-Comuni, in modo da consentire l’accesso alla WebApp di Test-Comuni e dalla Console di Sicurezza censire tutte le utenze che poi riceveranno una email con la password assegnata dal sistema. 
 
 
Ambiente Produzione
la “Console di Sicurezza” è stata opportunamente modificata per gestire la scelta dell’ambiente di operatività di ogni singolo utente.  
In particolare nella pagina che riporta il “Profilo Utente” è stata inserita un’apposita sezione «Ambiente di destinazione» dove l’ALS può indicare se l’utenza potrà accedere all’ambiente di Produzione e/o a quello di Pre-Subentro: 
(si riporta la sezione a titolo di esempio)
 
Ricordiamo che per accedere alla WebApp 
occorre installare il certificato di postazione di produzione  (es.   001156-PC-001.p12) 
ed utilizzare una Smart Card attiva  
la url è:  
https://dp.anpr.interno.it/com
 
se invece il Comune utilizza Web Services 
occorre installare  il certificato di postazione di produzione  (es.   001156-PC-001.p12) 
ed utilizzare una utenza censita  in ambiente di Produzione. 
 
 
 
 
Le principali Issue dove si parla dell’argomento sono: 
 
https://github.com/italia/anpr/issues/1410
https://github.com/italia/anpr/issues/1424
https://github.com/italia/anpr/issues/1161
https://github.com/italia/anpr/issues/1301
 
 
Cordiali saluti
Assistenza ANPR
