### ISSUE TITLE
DOVE SI TROVA LA CONSOLE DI SICUREZZA IN PRODUZIONE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1552]
DATA : 02.09.2019
AMBIENTE : produzione [https://dp.anpr.interno.it/combas]

Estratto da un'altra issue 
"E' disponibile inoltre, in produzione, la nuova versione della **console di sicurezza** per richiedere, per ogni operatore, l'accesso ad entrambi gli ambienti (produzione e presubentro) o ad uno solo dei due"

RICHIESTA 
Non riusciamo nel portale di produzione la console di sicurezza, è visibile solo per alcuni operatori ? 

COMUNE : Caponago (MB)
OPERATORE DEL COMUNE : Varisco M.Giuseppina
SOFTWARE HOUSE : SCAP Sistemi
TECNICO : Ballabio Gabriella

**Comment by Leonforte** [comment]
Come indicato nella documentazione allegata e disponibile al link www.anpr.interno.it l'accesso alla console di sicurezza è consentito esclusivamente agli utenti con profilo ALS (Amministratore Locale della Sicurezza)

Cordiali saluti

Assistenza ANPR
[Avviso nuove modalità accesso.pdf](https://github.com/italia/anpr/files/3565206/Avviso.nuove.modalita.accesso.pdf)
