### ISSUE TITLE
Risoluzione disallineamenti con Agenzia delle entrate [CODICE 12] Soggetto non individuato in AT. ESITO AE : codice fiscale non variato

### ISSUE THREAD

**Issue by annalisam-nu** [italia/anpr#1553]
--- TESTO DA ELIMINARE ---

Per l'individuo con idAnpr 65447636 non è possibile effettuare una mutazione tutti i dati per rettificare il sesso inviato errato con la pratica di iscrizione per una validazione di agenzia delle entrate.
Consultando infatti l'individuo in Agenzia delle Entrate, attualmente l'anagrafica che mostra è quella che vorremmo inviare con la Mutazione tutti i dati.
Il codice fiscale che inviamo è già presente come collegato in AT.
Provando ad effettuare una risoluzione disallineamenti Ae, riceviamo errore:
Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12).

In pratica è come se Agenzia delle entrate avesse risolto il disallineamento, ma non avesse ribaltato l'anagrafica sull'individuo in anpr.

Non è possibile annullare la pratica di iscrizione per nascita in quanto esiste un'operazione di mutazione scheda successiva non annullabile.
Si chiede quale procedura si deve seguire per risolvere il problema in ANPR, o se il disallineamento deve essere risolto dalla SOGEI. 

ANNALISA MULAS
UFFICIO ANAGRAFE - COMUNE DI NUORO
VIA DANTE 44 - 08100 NUORO
tel 0784/216717 - 0784/216724
email: anagrafe@comune.nuoro.it

**Comment by azabatta** [comment]
Il sistema di Issue Tracking basato Github, dove ci sta leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.

La  sua richiesta ha  carattere di assistenza su una casistica particolare. Abbiamo verificato che correttamente è stato aperto un ticket al servizio di assistenza ANPR: sarà ricontattata in merito a tale segnalazione.
