### ISSUE TITLE
Corsi on line dedicati all’utilizzo della piattaforma Web di ANPR

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1554]
COMUNE : CAPONAGO
OPERATORE : VARISCO GIUSEPPINA
RICHIESTA  :  Non avendo potuto partecipare ai corsi di luglio, è possibile sapere se e quando saranno organizzati altri corsi on line dedicati all'utilizzo della WA

**Comment by frmariani** [comment]
Sono previsti dei corsi sull'utilizzo dell web app di ANPR  nei mesi di Ottobre o Novembre;
le date saranno comunicate tramite avviso sia su questa piattaforma che nel portale di ANPR al seguente indirizzo:
www.anpr.interno.it
