### ISSUE TITLE
URGENTE - annullamento mutazione residenza su persona sbagliata

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#1555]
Salve,
dal comune di Scandicci, per errore materiale, è stata fatta una pratica con id operazione 29534648, prendendo 2 persone da un comune subentrato, ad una verifica si è scoperto di aver preso una persona diversa dalla dichiarante. L'operatore cercando di correggere ha fatto una mutazione residenza sulla persona giusta (id 33199159) e poi preso dal comune originario la persona corretta dichiarante (id 33199097). Adesso non si riesce più a riportare la prima persona  con id 33199123 (quella sbagliata) sul comune originario, chiedo di sapere la corretta procedura per riportare l' id 33199123 nel comune originario (non devono risultare variazioni)
si prega di contattale l'ufficio per risolvere al più presto il problema
0557591343
grazie

**Comment by frmariani** [comment]
in questi casi si deve effettuare il ripristino parziale dell'operazione di mutazione di residenza;
Vista l'urgenza il Comune è stato contattato ed il problema risolto, ma ricordiamo che per casi specifici deve essere contattata l'assistenza ANPR al numero verde 800863116
