### ISSUE TITLE
InoltroNotificaANPR - Esempi di xml inviati nella RichiestaN000

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1556]
COMUNE : CAPONAGO (MB)
OPERATORE : Ballabio Gabriella
SOFTWARE HOUSE : SCAP Sistemi srl

E' possibile ricevere, per ciascuna tipologia di notifica, proveniente da ANPR, un esempio di file XML presente in "contenuto" , in modo da accelerare le operazioni di sviluppo ?

**Comment by fferraguto** [comment]
Salve, 
le allego una risposta di un 5005, nella quale sono stati oscurati i dati sensibili:
[5005.zip](https://github.com/italia/anpr/files/3579878/5005.zip)

Consideri che tutte le risposte si somigliano, in particolare risultano importanti la listaSoggettiVariati e la listaAnomalie.

A presto.
