### ISSUE TITLE
Movimento e calcolo popolazione residente 

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#1557]
-Dopo la stampa del pdf relativo al mese di maggio 2019 non viene piu' prodotta alcuna statistica riguardante i mesi successivi (da giugno in poi). Infatti viene prodotto un pdf con la sola testata e nessun dato (non dati a 0 ma proprio un foglio bianco).
A cosa e' dovuto? come e' possibile ottenere i dati richiesti?

Comune di Valdilana - cod. istat  096088
Grazie in anticipo

**Comment by rvinzani** [comment]
La produzione del prospetto mensile non è contestuale alla richiesta ma viene elaborata con un leggero sfasamento temporale.
Effettuare una prima richiesta selezionando come tipo richiesta  “Elaborazione prospetto” (è obbligatorio indicare mese ed anno di riferimento).
Attendere (in generale l’elaborazione avviene entro una decina di minuti)  e ripetere la richiesta selezionando “Stampa prospetto”. 
Chiudo la issue. Nel caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa stessa

**Comment by rvinzani** [comment]
Da un'ulteriore verifica abbiamo riscontrato esserci un errore nel servizio. Provvederemo a rimuovere il malfunzionamento e ve ne daremo notizia

**Comment by rvinzani** [comment]
Il bug è stato corretto. Potete riprovare. Chiudo la issue. Nel caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa stessa
