### ISSUE TITLE
[4001/7002] EN122 La richiesta effettuata non produce alcun risultato 

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1558]
Buongiorno abbiamo sempre il problema di #1541.
alla chiusura della precedente issue sono tornati correttamente i dati, ma le successive richieste sempre EN122

4001 idOperazioneANPR 13839759
7002 idOperazioneANPR 13845084
CARTOCETO - PRE SUBENTRO
Grazie mille
Riccardo

**Comment by fmbianchi** [comment]
aggiungo che lo stesso problema c'è al Comune di ANTEGNATE in produzione
4001 idOperazioneANPR>112569799
7002 idOperazioneANPR>117184536
saluti 
Riccardo

**Comment by asqueglia** [comment]
Buongiorno stiamo analizzando il caso

**Comment by asqueglia** [comment]
Abbiamo verificato che a causa di problemi tecnici che si sono verificati ad agosto, sono state elaborate con ritardo alcune richieste asincrone. Adesso dovreste poter interrogare e ricevere i risultati.
Un saluto
