### ISSUE TITLE
WEB-SERVICE: RETTIFICA DATI DI MATERNITA'

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#156]
[5008-26]   'Comune di Venezia, ambiente di Pre-subentro, 16/05/2017' ---

Tentata rettifica dei dati di maternita', codice op. ANPR 174930 Completata con esito positivo e warning; in realtà non aggiorna i dati pur se contenuti nell'XML dell'operazione

**Comment by gcarbonin** [comment]
Nella mutazione è stato indicato come tipo mutazione 10 che significa aggiornamento dei dati della parternità non della maternità
