### ISSUE TITLE
[web-service] certificate not trusted (from client)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1560]
ambiente di PRE-SUB - comune di BORGOSATOLLO (017021)

le chiamate ai web-service in pre-subentro ci ritornano questo errore:
```
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <env:Fault>
      <faultcode>env:Client</faultcode>
      <faultstring>certificate not trusted (from client)</faultstring>
    </env:Fault>
  </env:Body>
</env:Envelope>
```

lato client sembrano correttamente configurati sia i certificati server che quello di postazione 017-CO-0000.p12

riuscite a verificare cosa blocca gli invii o a darci qualche input aggiuntivo?
esempio idOperazioneComune 2019300011

grazie.
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
Ci potreste dire da quale ip provenite?
