### ISSUE TITLE
[webapp] famiglia non trovata in mutazione residenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1562]
Ambiente di produzione, comune di Barlassina

Dobbiamo con la webapp spostare il soggetto ID ANPR 27740343 nella famiglia del soggetto ID ANPR  27740466 con decorrenza 4/7/2018.
Iniziamo dunque una procedura di mutazione residenza specificando di voler entrare in famiglia esistente.
Nella scheda famiglia andiamo poi a premere il bottone "cerca" per recuperarla, ma ci viene restituito il messaggio "Non sono stati trovati soggetti corrispondenti ai criteri di ricerca" usando le generalità di qualsiasi componente..
Anche cercando per ID ANPR famiglia (2014000135) otteniamo la stessa risposta

Come mai ?
Come possiamo procedere ?

Grazie

**Comment by frmariani** [comment]
i cittadini sono tutti Aire, quindi nel caso di modifica dell'indirizzo all'estero, la corretta operazione da eseguire è la Mutazione dati Aire;  l'identificativo della famiglia indicato non è quello ANPR ma si riferisce alla numerazione APR;
il Comune è stato contattato e seguito nell'operazione.
Il problema è stato risolto.
