### ISSUE TITLE
Matrice matriceservizirispostaunica

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1563]
Nel documento MI-14-AN-01 SPECIFICHE DI INTERFACCIA WS_14_05_2019 si fa sempre riferimento a matriceservizirispostaunica

"La risposta è comune a tutti i servizi di registrazione (vedi file rispostacomune);
sono valorizzati gli oggetti di interesse per l’operazione; _si veda al tal proposito la_
matrice **matriceservizirispostaunica**"

Ma dove la si vede ? nella documentazione non c'è

**Comment by rvinzani** [comment]
La matrice è possibile trovarla sul sito di ANPR www.anpr.interno.it alla voce
◦Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica  (aggiornato al 17 maggio 2019)
Il link è 
https://www.anpr.interno.it/portale/documents/20182/239162/SPECIFICHE+DI+INTERFACCIA+17052019.rar/9c076bb3-a919-4695-a227-5406121a9d26
Il file matriceservizirispostaunica.xlsx è presente all'interno del file compresso
Chiudo la issue. Nel caso ci siano ulteriori richieste informazioni si chiede di aprirne una nuova che faccia riferimento a questa stessa
