### ISSUE TITLE
Problemi accesso WEBAPP ANPR

### ISSUE THREAD

**Issue by ComuneLivigno** [italia/anpr#1564]
Buongiorno,
sia dalle macchine Windows 7 che dalle macchine windows 10 non riusciamo ad accedere alla WEBAPP ANPR https://dp.anpr.interno.it/com 
le macchine hanno installato il certificato di postazione ed il certificato utente con data di scadenza al 2024 quindi validi ma non riusciamo ad accedere ne con Chrome ne con IE

errore Chrome
Impossibile raggiungere il sito
La pagina web all'indirizzo https://dp2.anpr.interno.it/com potrebbe essere temporaneamente non disponibile oppure è stata permanentemente spostata a un nuovo indirizzo web.
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

errore IE
con attivo solamente TLS v.1.2 errore
Impossibile connettersi in modo sicuro alla pagina
La causa potrebbe essere che il sito utilizza impostazioni di sicurezza TLS obsolete o non sicure. in tal caso, provare a contattare il proprietario del sito Web.
Le impostazioni di sicurezza TLS non sono impostate sui valori predefiniti. Anche questa potrebbe essere la causa di questo errore.

con attivo TLS v.1.0 TLS 1.1 TLS 1.0 errore

•Verifica che l'indirizzo Web https://dp2.anpr.interno.it sia corretto.
•Cerca la pagina con il tuo motore di ricerca.
•Aggiorna la pagina tra alcuni minuti.

grazie

**Comment by Leonforte** [comment]
Buogiorno, vi suggeriamo di procedere seguendo le indicazioi in allegato ed effentuando le relative verifiche del caso.

**Comment by Leonforte** [comment]
[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/3582975/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)

**Comment by sergiogedda** [comment]
se puo' essere utile…
https://ca.arubapec.it/downloads/IDP_6.44.10_Windows.zip
Eseguite il file setup presente in questo zip….  dopo non dovreste aver problemi
