### ISSUE TITLE
Verifica Modifiche Tracciato Dataset ANPR_archivio_comuni.csv

### ISSUE THREAD

**Issue by mariaclaudia** [italia/anpr#1566]
Buongiorno,

il dataset "ANPR_archivio_comuni.csv" pubblicato sul portale in data 2 settembre 2019 sembra utilizzare un nuovo tracciato.
Alcune procedure automatiche che utilizzano il dataset in oggetto falliscono poichè il tracciato risulta essere differente.
Nell'intestazione sono presenti delle nuove denominazioni (in grassetto):

- "ID",
- "DATAISTITUZIONE",
- "DATACESSAZIONE",
- "CODISTAT",
- "CODCATASTALE",
- "DENOMINAZIONE_IT",
- "DENOMTRASLITTERATA",
- **"NVL(AC.ALTRADENOMINAZIONE,'')",**
- **"NVL(AC.ALTRADENOMTRASLITTERATA,'')",**
- "IDPROVINCIA",
- "IDPROVINCIAISTAT",
- "IDREGIONE",
- **"NVL(AC.IDPREFETTURA,'')",**
- "STATO",
- "SIGLAPROVINCIA",
- **"NVL(AC.FONTE,'')",**
- "DATAULTIMOAGG",
- **"NVL(AC.COD_DENOM,'')"**

Si tratta di una versione temporanea oppure di una versione definitiva?
Qual è il significato del prefisso "NVL"?
La presenza, nel nome delle colonne di questi campi, di alcuni caratteri speciali come " e , è voluto oppure si tratta di una svista momentanea?

A disposizione e grazie in anticipo per il supporto.

Maria Claudia Bodino (Team per la Trasformazione Digitale - Presidenza del Consiglio dei Ministri)

cc @giorgialodi, @mccalv @axcarlin

**Comment by mariaclaudia** [comment]
Nella colonna della pagina 
https://www.anpr.interno.it/portale/tabelle-di-riferimento viene indicato "“Vedi Aggiornamenti.xls”".

Dove si trova il file indicato? 

Grazie
<img width="822" alt="Screenshot 2019-09-05 at 16 36 25" src="https://user-images.githubusercontent.com/1733135/64351977-882e7e00-cffb-11e9-9279-9fcc653b7b87.png">

**Comment by axcarlin** [comment]
Occorre che i dataset utilizzati per le aggregazioni in PDND siano sottoposti a monitoraggio e procedura di pubblicazione che coinvolga il Team. Senza questo potremo avere grossi problemi non solo ora ma soprattutto in futuro.
ANPR Archivio Storico Comuni potrebbe al limite essere classificato come DataSet Controllato come anche ISTAT IPA

cc @mccalv

**Comment by ncapozzi** [comment]
Buongiorno,
l'intestazione è stata ripristinata nella precedente versione concordata.

Scusate per l'errore.

N. Capozzi

**Comment by mariaclaudia** [comment]
Buongiorno, 
grazie mille per il rapidissimo riscontro.

Maria Claudia Bodino
