### ISSUE TITLE
ws 1002 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1568]
come devo comportarmi per far rientrare un cittadino AIRE 
ho provato con ws1002 tipo iscrizione 6 ma mi viene segnalato che la persona è già in ANPR.
Sto lavorando in ambiente di TEST.
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
nel caso di rimpatrio di un cittadino italiano dall’estero il servizio prevede due differenti casi:
 Il cittadino non è registrato in ANPR (è iscritto presso un comune non ancora subentrato)
 Il cittadino è registrato in ANPR (è iscritto presso un comune già subentrato)
Nel 1° caso si effettuerà una vera e propria iscrizione richiamando il WS 1002 con la registrazione della sua scheda e l’attribuzione del codice identificativo ANPR.
Nel 2° caso invece, quando il soggetto sia già presente in ANPR, dovrà essere richiamato il servizio di mutazione 5005 se il rimpatrio riguarda uno o più soggetti AIRE del nucleo familiare, il servizio 5001 per rimpatrio dell' intero nucleo familiare AIRE .

N. Capozzi

**Comment by rinonasti** [comment]
ok grazie
