### ISSUE TITLE
Revoca cie

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1569]
Abbiamo emesso per errore una Cie ad un cittadino al posto di un altro (causa omonimia e data di nascita simile). Successivamente, dal portale Cie, si è provveduto ad interdirla con motivazione revoca: "errore di emissione". Ora sulla web app, richiamando il cittadino nella sezione documenti, appare ancora la Cie emesse anche se con la dicitura "annullata".  La Cie appare anche nella stampa scheda individuale (tra l'altro qui senza nessuna traccia del suo annullamento).
Al suo posto invece dovrebbero esserci gli estremi della carta in corso di validità ed in possesso al cittadino. Come è possibile ripristinare la situazione?
Grazie
Comune di Altamura

**Comment by rvinzani** [comment]
E' possibile avere gli estremi del cittadino? Es. l'idANPR.

**Comment by Finalmentesubentrati** [comment]
18888749

**Comment by rvinzani** [comment]
La carta di identità cartacea è visibile nei documenti storici. Verificheremo le modaità di estrazione delle informazioni

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
