### ISSUE TITLE
Presunto problema scarico notifiche

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1570]
Buongiorno,
ambiente di produzione:
in data 11/08/2019 a 6 richieste di scarico notifiche è stato assegnato lo stesso id_operazioneAnpr.

L'id_operzioneAnpr è 111872820.

Le richieste invece erano le seguenti:
- dal 10-08-2019 00:00:00 al 11-08-2019 07:55:19
- dal 11-08-2019 00:00:00 al 11-08-2019 12:55:19
- dal 11-08-2019 00:00:00 al 12-08-2019 07:55:18
- dal 13-06-2019 00:00:00 al 16-06-2019 00:00:00
- dal 12-08-2019 00:00:00 al 12-08-2019 13:45:53
- dal 12-08-2019 00:00:00 al 13-08-2019 07:55:17

il sistema avrebbe dovuto assegnare 6 id diversi, potete verificare cosa sia successo?

Grazie

**Comment by SAlberto** [comment]
Buongiorno, ci sono novità in merito?

Grazie

**Comment by fferraguto** [comment]
Salve,
per l'operazione ANPR segnalata (id 111872820) è stato specificato l'id operazione comune 24438.
Potreste dirci che id operazione del comune avete fornito per le sei operazioni?
Potreste aver attivato il meccanismo di retry qualora aveste fornito lo stesso id.
A presto.
