### ISSUE TITLE
codice ISO 3166-1 alpha-3 "Russia"

### ISSUE THREAD

**Issue by panric** [italia/anpr#1573]
Buongiorno, sono un privato cittadino, il Comune di Milano ha effettuato un'iscrizione anagrafica di una cittadina russa con atto di nascita riportante stato di nascita "Russia" con il codice a tre lettere "RSU".
Chiedendo  se non fosse un errore (RSU invece che RUS) mi è stato risposto che è un nuovo codice identificativo per stato estero "Russia". Però non trovo questo codice in nessuna tabella di riferimento ufficiale. Qualcuno sa darmi una spiegazione?

**Comment by ncapozzi** [comment]
Buongiorno,
il codice ISO dovrebbe essere RUS per FEDERAZIONE RUSSA.

La tabella è pubblicata al link https://www.anpr.interno.it/portale/tabelle-di-riferimento

N. CapoI
