### ISSUE TITLE
Modifica cognome e cf

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#1575]
Comune di Ghemme - Ambiente di produzione

Buongiorno,
dobbiamo modificare il cognome del soggetto con id ANPR 23261076 da MYRONOVA a CHERNYSH  con conseguente modifica del codice fiscale (nuova attribuzione effettuata da AE in risoluzione di omocodice )MA veniamo bloccati dall' errore:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-09-09 15:10:44 , idOperazioneANPR 97198102 (Codice: EN527)

In AE il soggetto ha una sola posizione CHRRYN71B55Z1PUK marcata ANPR e collegata ai precedenti codici fiscali 
IN anpr ha la posizione con cf MYRRYN71B55Z138F Validato AE

Per cortesia potete aiutarci a sbloccare?

I codici fiscali in questione sono il vecchio MYRRYN71B55Z138F ed il nuovo CHRRYN71B55Z1PUK

Grazie, cordiali saluti
Maura Barbavara

**Comment by azabatta** [comment]
Correttamente per la segnalazione era stato aperto un ticket al servizio di assistenza che è stato  lavorato per la soluzione di questo caso particolare.
