### ISSUE TITLE
RIF ISSUE 1557 - MOVIMENTO E CALCOLO POPOLAZIONE

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#1576]
COMUNE DI VALDILANA  096088

Ho provato nella giornata di ieri e poi stamattina a richiedere l'elaborazione dei prospetti mensili di giugno, luglio e agosto (operazioni di oggi: 119077519 - 119077802 - 119078003 quelle di ieri non le ho annotate) ma alla successiva stampa i modelli risultano vuoti.
Credo che i problemi non si siano del tutto risolti.
Potete verificare per favore?
Renzo Preto

**Comment by rvinzani** [comment]
Potete per favore riprovare ora?

**Comment by RENZO63** [comment]
Ho lanciato le richieste giu-lug-ago e finora ho ricevuto solo giugno.
Domani mattina verifico luglio e agosto e faccio sapere
grazie 1000 per la collaborazione

**Comment by RENZO63** [comment]
Ho verificato e questa mattina i prospetti erano disponibili ed elaborati.
Il tempo di estrazione e' insolitamente lungo rispetto al passato ma l'importante e' che il tutto funzioni.
Grazie
