### ISSUE TITLE
Codice catastale Olgiate Molgora/Calco

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1578]
Con la segnalazione #1404 è stata corretta la denominazione per il record con ID 18094 da _OLGIATE CALCO_ a _OLGIATE MOLGORA_. In questo caso il cambio di denominazione comportava anche un cambio di codice catastale, come indicato in tabella.

ID|DATAISTITUZIONE|DATACESSAZIONE|DENOMINAZIONE_IT|CODCATASTALE
-|-|-|-|-
6572|23/02/1863|16/06/1927|OLGIATE MOLGORA|G026
18094|17/06/1927|20/02/1928|OLGIATE MOLGORA|~G027~G026
18095|21/02/1928|12/09/1953|OLGIATE CALCO|G027
18209|13/09/1953|15/04/1992|OLGIATE MOLGORA|G026
6571|16/04/1992|31/12/9999|OLGIATE MOLGORA|G026

**Comment by MassimoSchiappa** [comment]
Grazie per la segnalazione, 
provvederemo alla correzione.
Cordiali saluti.
