### ISSUE TITLE
Denominazione precedente Challand-Saint-Victor

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#1579]
La denominazione per il record con ID 22069, indicata nella segnalazione #1404, non sembra applicata correttamente (Challant è il nome del comune costituito per fusione di questo e Challand-Saint-Anselme). Riporto la storia completa del comune evidenziando la correzione.

ID|DATAISTITUZIONE|DATACESSAZIONE|DENOMINAZIONE_IT|SIGLAPROVINCIA|CODCATASTALE
-|-|-|-|-|-
22071|17/03/1861|11/01/1927|CHALLANT SAINT VICTOR|TO|C594
22069|12/01/1927|15/06/1928|~CHALLANT~CHALLANT SAINT VICTOR|AO|C594
22070|27/09/1946|01/01/1977|CHALLANT SAINT VICTOR|AO|C594
2804|02/01/1977|31/12/9999|CHALLAND-SAINT-VICTOR|AO|C594

**Comment by MassimoSchiappa** [comment]
Salve,
grazie per la segnalazione. 
Provvederemo alla correzione.
Saluti.
