### ISSUE TITLE
[6001] Ambiente FREE annotazioni

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1580]
Buongiorno, 
ho fatto vari tentativi da WebApp in ambiente FREE per cercare di inserire nelle annotazioni del certificato il simbolo € ma restituisce errore (carattere non valido). Potreste allineare?
Grazie

**Comment by gife67** [comment]
Vi ringraziamo per la segnalazione verificheremo e nel caso abiliteremo l'utilizzo di questo carattere speciale nella prossima versione.

**Comment by Eduardo1977** [comment]
Grazie per il riscontro.

**Comment by gife67** [comment]
Buonasera,
Ieri abbiamo pubblicato una fix che dovrebbe aver risolto il problema.
Cordiali Saluti
