### ISSUE TITLE
ANPR - POPOLAMENTO IN TEST  

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1581]
Buongiorno, 
Comune di Caserta
abbiamo inviato i due file (AIRE-ANPR) il primo risulta elaborato e consente anche le consultazioni mentre il secondo è sempre nella fase "in elaborazione". Quale può essere il motivo
Grazie

**Comment by amollicone1982** [comment]
Il subentro risulta terminato alle 10:52 come da mail inviata a postacertificata@comune.caserta.it

**Comment by rinonasti** [comment]
si adesso risulta "elaborato" ma continuo a non vedere i dati inviati (vedo solo AIRE). La operazione di popolamento l'ho effettuata varie volte (per pulizia dopo test vari)  ed è sempre andata a buon fine.
