### ISSUE TITLE
Metodo InoltroNotificaANPR

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1582]
Presupponendo che le notifiche che ANPR invia al comune tramite invocazione del WS esposto dall'ente stesso, metodo "InoltroNotificaANPR" abbiano tutte le medesima struttura del tipo di seguito indicato :

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RichiestaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">
      <testataNotifica>
        **

> <tipoNotifica>N031</tipoNotifica>

**
        <codMittente>999999</codMittente>
        <codDestinatario>888888</codDestinatario>
        <dataOraRichiesta>2018-11-07T17:18:46.904+01:00</dataOraRichiesta>
        <idOperazioneANPR>999999</idOperazioneANPR>
      </testataNotifica>
   <contenuto>xxxxxxx (xml codificato in base64)</contenuto>
    </ns2:RichiestaN000>
  </soapenv:Body>
</soapenv:Envelope>

E' possibile avere un elenco di tutti i valori che può assumere il tag tipoNotifica sulla base dei diversi tipi di eventi esposti in "matriceservizirispostaunica" ?

**Comment by fferraguto** [comment]
Salve,
il tipo notifica è NRIS. <tipoNotifica>NRIS</tipoNotifica>
Il <contenuto> della notifica è la risposta all'operazione effettuata (nella fattispecie la risposta ad un'operazione di tipo 1001), codificata in base64.
All'interno del contenuto, i dati relativi all'operazione 1001, ma più in generali quelli dell'operazione effettuata, li trovate nella testataRisposta.
La testata risposta dei servizi è del seguente tipo:

	<xs:complexType name="tipoDatoTestataRisposta">
		<xs:sequence>
			<xs:element name="idOperazioneComune" 	type="tipoIdOperazioneComune"   				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Identificativo univoco attribuito all'operazione. Normalmente è attribuito dal comune; per il WEB è attribuito da ANPR.
</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="codMittente" 			type="tipoCodMittente" 					minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>codice dell'ANPR</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="codDestinatario" 		type="tipoCodDestinatario" 					minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Il codice ISTAT del comune a cui inviare la risposta.</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="operazioneRichiesta" 	type="tipoOperazioneRichiesta"	minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Codice dell'operazione richiesta (es. 1001,5005)</xs:documentation>
				</xs:annotation></xs:element>			
			<xs:element name="dataOraRichiesta" 	type="xs:dateTime"      		minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>La data e l‟ora in cui si invia la comunicazione anagrafica ad ANPR.
</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="protocolloComune" 	type="tipoProtocolloComune" 	minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>La data e l‟ora in cui si invia la comunicazione anagrafica ad ANPR.</xs:documentation>
				</xs:annotation></xs:element>				
			<xs:element name="dataProtocolloComune" type="xs:date" 					minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Data di protocollazione della pratica da parte dell'ufficio Anagrafe.</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="dataDecorrenza" 		type="xs:date" 					minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Data di inizio validità dell’operazione di registrazione.Obbligatorio solo per i servizi di registrazione.</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="idOperazioneANPR" 	type="tipoIdOperazioneANPR" 			minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Identificativo univoco attribuito all'operazione da ANPR.</xs:documentation>
				</xs:annotation></xs:element>
			<xs:element name="esitoOperazione" 		type="charMax4" 				minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Codice che indica se l’operazione è terminata con successo oppure con segnalazioni o errori.
2 = richiesta completata con esito positivo                                            
3 = richiesta completata con esito negativo    
4 = richiesta annullata                                              
6 = richiesta completata con esito positivo ma con warnings
</xs:documentation>
				</xs:annotation></xs:element>
			
		</xs:sequence>		
	</xs:complexType>


Spero di aver chiarito meglio i vostri dubbi.
A presto.
