### ISSUE TITLE
ERRORE EF044

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1585]
Non riusciamo a registrare una mutazione di indirizzo per una famiglia già residente nel nostro comune. L'errore è il seguente:
ERRORE DA ANPR: 
EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-09-12 12:06:56 , idOperazioneANPR 119984844

**Comment by frmariani** [comment]
per un cittadino della lista, avete inserito un identificativo APR non corretto o almeno diverso da quanto  precedentemente inviato ad ANPR;

Vi ricordo che per le richieste di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio dovete avvalervi del servizio di assistenza ANPR al numero 800863116.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa

**Comment by eleonora1991** [comment]
Non riusciamo a registrare una mutazione di indirizzo per una famiglia già residente nel nostro comune. L'errore è il seguente:
ERRORE DA ANPR:
EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-09-12 12:06:56 , idOperazioneANPR 119984844
