### ISSUE TITLE
Errore Warning Pre-subentro : EC075 - Comune di registrazione dell'atto di nascita:ARIENZO(CE) non esistente alla data

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1586]
COMUNE : CAPONAGO (MB)
OPERATORE : Varisco Maria Giuseppina

Per alcuni soggetti viene indicato l'errore : Comune di registrazione dell'atto di nascita non esistente alla data. Per esempio il comune di ARIENZO (CE)  alla data del 21.01.1945 non esisteva o si chiamava in altro modo. 
Per questi casi cosa deve fare l'ente per eliminare il Warning ? Se volesse bonificare il dato prima del  subentro come si deve comportare ?

**Comment by cmigliardi** [comment]
Il Ministero ha sempre dato indicazione di "non arrecare danno ai cittadini". Detto questo:  per i cittadini che possono fornire l’atto di nascita, ai fini della validità dei Comuni di registrazione dell’atto occorre far riferimento alla data di formazione dell’atto o, in sua assenza, all’anno dell’atto. 
Si suggerisce di mantenere il Comune che ha effettivamente registrato l’atto di nascita.  Si tratta infatti di una anomalia e non di errore.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
