### ISSUE TITLE
Errore Warning Pre-subentro : EN306 - Presenza del coniuge e assenza del matrimonio

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1587]
COMUNE : CAPONAGO (MB)
OPERATORE : Varisco Maria Giuseppina

Per tutta una serie di soggetti viene evidenziato l'errore : Presenza del coniuge e assenza del matrimonio
Sono casi in cui il cittadino è immigrato con stato civile vedovo con l'indicazione del nome coniuge ma in assenza di atto di matrimonio in quanto non disponibile.

Come si deve comportare l'operatore per bonificare il warning ?

**Comment by cmigliardi** [comment]
Buongiorno, si tratta di una anomalia che non blocca  il subentro. In assenza di atto di matrimonio -  come scrive -  non può far nulla.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
