### ISSUE TITLE
Errore Warning Pre-subentro : EC030 - Stato estero di nascita non esistente

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1588]
COMUNE : CAPONAGO (MB)
OPERATORE : Varisco Maria Giuseppina

Per un cittadino nato ad Hong Kong segnala l'errore  Stato estero di nascita non esistente , nel codice fiscale è presente il codice belfiore Z221 che non esiste. Nwell'atto di nascita è presente Hong Kong. Che stato deve indicare l'operatore Repubblica Popolare Cinese ?

**Comment by cmigliardi** [comment]
E'  possibile indicare, ove necessario, la denominazione di uno stato cessato (Jugoslavia, URSS, etc.)  indicando come codice stato 998.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
