### ISSUE TITLE
Chiarimento su supporto toponomastica

### ISSUE THREAD

**Issue by ccontavalli** [italia/anpr#159]
Toponomastica: ad oggi ANPR non prevede l’interazione verso l’ Archivio Nazionale dei Numeri Civici delle Strade Urbane (ANNCSU); per questa ragione, i Comuni che eseguano il Subentro in ANPR nella condizione attuale potranno:
* eseguire i controlli sull’esistenza degli indirizzi solo su base dati locale
* aggiornare l’elenco dei civici disponibili solo su base dati locale

Serve chiarire:
* i tempi per l’integrazione tra ANPR ed ANNSCU
* le modalità con cui il Comune dovrà eseguire la bonifica sugli indirizzi eventualmente erronei presenti in ANPR

**Comment by luca-teamdigitale** [comment]
Duplicate of #231
