### ISSUE TITLE
[Webapp] Scarico per motivata richiesta vuoto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1590]
Ambiente di test, comune di Poggio a Caiano

In giornata ho chiesto tramite la webapp il download dei dati ANPR del comune.
La richiesta (di identificativo 20141965) è stata recepita e completata con successo.
Quando provo a scaricare il file (di protocollo ANPR 12050255) mi viene ritornato un XML di 628 bytes con solo l'intestazione senza nessun dato. 

Potete verificare ? 

Grazie

PS : Lo stesso problema era capitato un paio di settimane fa, poi dopo vostro intervento quello scarico è risultato completo.

**Comment by gife67** [comment]
Buongiorno,
abbiamo provveduto a elaborare nuovamente la richiesta.
Attendiamo un vs riscontro.
Cordiali Saluti

**Comment by busaster** [comment]
Ok, il file ora risulta completo.
Potreste per favore dare un'occhiata allo stesso problema che ci è capitato in produzione su altro cliente (issue #1591) ?

Grazie
