### ISSUE TITLE
[webapp] Scarico per motivata richiesta vuoto anche in produzione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1591]
Ambiente di produzione, comune di Cittanova

la scorsa settimana tramite la webapp abbiamo chiesto lo scarico per motivata richiesta dei dati del comune (richiesta 120007893)
Ad oggi risulta pronto ma quando vado a cliccare sul link "protocollo ANPR" dall'interfaccia di "download file" mi viene scaricato un /zip contenente un XML con la sola intestazione privo di qualunque dato (protocollo ANPR 41603858).

Come mai ? Potete risolvere ?

Grazie

**Comment by gife67** [comment]
Buonasera,
dovrebbe essere elaborato stanotte, quindi domani mattina se cortesemente può verificare e darci conferma.
Grazie

**Comment by busaster** [comment]
Il file ora risulta completo, grazie.

**Comment by gife67** [comment]
Perfetto.
Cordiali Saluti
