### ISSUE TITLE
WS 1002 ricomparsa da irreperibilità

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1592]
Comune di Caserta - TEST
buongiorno,
quale è la procedura da seguire per il seguente caso:
1) individuo presente in ANPR viene cancellato per irreperibilità:
2) successivamente deve essere re-iscritto per ricomparsa da irreperibilità.
Se non è presente in ANPR ho utilizzato motivo iscrizione 5 
Grazie

**Comment by frmariani** [comment]
le due procedure descritte sono corrette; 
per completezza: nel caso di re-iscrizione, deve essere indicato l'identificativo ANPR precedentemente assegnato.

**Comment by frmariani** [comment]
La issue viene chiusa;  nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
