### ISSUE TITLE
Gestione utenze - modifica dei profili

### ISSUE THREAD

**Issue by sergiogedda** [italia/anpr#1593]
Buonasera, 
stiamo seguendo il subentro di un Comune in ANPR.
Smart Card le hanno già attivati, i certificati li han tutti scaricati… insomma tutte le operazioni son state, correttamente, effettuate. 
Per scrupolo siamo entrati a verificare il corretto inserimento delle utenze/profili, ma entrando con qualsiasi psw i profili hanno solamente un record "blank" e non si possono modificare.
Non è un problema "grave" eo bloccante perché si denota, dalle funzioni "accese", che i profili son correttamente caricati, ma se dovessimo fare un "cambio"? Non si possono "resettare" i profili eo farlo a quello del sindaco in modo che, entrando, possa correggere tutti gli altri?

Gedda Sergio tecnico Halley Informatica
Comune di Torre Canavese

**Comment by cmigliardi** [comment]
Buonasera, cortesemente mi può inviare  i nominativi  da verificare ?  grazie    a seguire  la mia email   cmigliardi@sogei.it

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
