### ISSUE TITLE
[4005] Verifica Stato - errore 999

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1594]
Salve,
Abbiamo eseguito una richiesta 4005 in modalità elaborazione di richieste 5008.
Ambiente Test - Id Sede: 888183
IdOperazioneANPR: 2207620 
Quando richiediamo lo stato di elaborazione il servizio 4005 restituisce errore 999 - Operazione non effettuabile. 
Ripetiamo le richieste anche con altri paramteri di elaborazione ma si ripete lo stesso errore.
Una issue simile potrebbe essere : #1483

Grazie in anticipo,
Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by gife67** [comment]
Buonasera, mi scuso per il ritardo nel contattarla.
Se cortesemente può riprovare ad inoltrare una nuova richiesta dello stesso tipo, il problema non dovrebbe ripresentarsi. Per la richiesta in oggetto stiamo completando delle verifiche, ma se comunque può riprovare ad interrogarne l'esito ed a fornirmi un riscontro sull'errore ricevuto.
Grazie mille
Giuseppe

**Comment by AlbanaCelepija** [comment]
Buongiorno,
Abbiamo riprovato a inoltrare una nuova richiesta 'Elaborazione' con un'altro periodo di riferimento, e poi una richiesta di 'Verifica'. Prima della data disponibilità il servizio riporta una risposta che contiene la data della disponibilità. Invece dopo la data della disponibilità riceviamo un' altro errore: 'EN122 : La richiesta effettuata non produce alcun risultato'.
Per la richiesta in oggetto riceviamo sempre lo stesso errore.

**Comment by gife67** [comment]
Se mi indica il riferimento della richiesta effettuata le fornisco maggiori dettagli. 
Comunque dal comportamento che mi ha descritto, riceve la data di disponibilità quando la sua richiesta è in fase di elaborazione, l'errore è relativo al post elaborazione dove si indica che i filtri impostati nella richiesta originaria non hanno permesso di trovare alcuna informazione. Provi ad inoltrare una richiesta con dei filtri che sicuramente estraggano delle operazioni.

**Comment by AlbanaCelepija** [comment]
Si, avete ragione, i filtri non trovano operazioni. 
Abbiamo riprovato e adesso funziona perfettamente, non riceviamo piu' l'errore 999.
Grazie mille della risposta.

**Comment by gife67** [comment]
Ottimo, se per voi non è un problema considero chiusa questa issue, nel caso abbiate altri problemi potete riaprirne una nuova.
Grazie

**Comment by AlbanaCelepija** [comment]
Ok, va bene.
