### ISSUE TITLE
WS1001 - nascita

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1595]
Comune di caserta - TEST
buonasera,
caso:
nascita-  il padre non è residente nel comune ne si conosce il codice fiscale.
il nato ha il cognome del padre
la madre è residente ed iscritta regolarmente in ANPR 
come ci si deve comportare

**Comment by frmariani** [comment]
Nell'iscrizione per nascita, il bambino deve appartenere ad una famiglia o convivenza esistente, pertanto,  nel suo caso, verrà iscritto nella famiglia della madre;
si potrà indicare l'informazione che il bambino acquisirà il cognome del padre anche se questi non è presente in ANPR;
nel suo esempio, sarà facoltativo acquisire i dati conosciuti della paternità (quindi senza il codice fiscale), ma sarà obbligatorio, acquisire i dati della maternità.

**Comment by rinonasti** [comment]
ho provato a non indicare i dati della paternità ma viene fuori :
 <errore>
                        <codiceErroreAnomalia>ES036</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Indicare i dati relativi alla paternita' quando filiazione e'  1=dei genitori&#13;
 o 2=del padre</testoErroreAnomalia>

**Comment by frmariani** [comment]
infatti nel suo esempio le avevo indicato di inserire l'appartenenza del bambino nella famiglia della madre

**Comment by frmariani** [comment]
per chiarezza
nei dati di controllo devono essere acquisiti i seguenti dati:
obbligatoriamente deve essere indicata la famiglia di appartenenza del bambino: famiglia del padre o della madre o dei genitori o altra famiglia o convivenza (dato obbligatorio);
da chi è riconosciuto il bambino:  dal padre o dalla madre o dai genitori o non riconosciuto (dato facoltativo);
il cognome che assume il bambino : del padre o della madre o entrambi o altro (dato facoltativo)

**Comment by rinonasti** [comment]
tutto OK verificato.
Grazie
