### ISSUE TITLE
[webapp] cittadino mancante in scarico per motivata richiesta

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1596]
In riferimento alla issue #1590 , abbiamo trovato un cittadino che, pur risultando presente in ANPR come  residente nel comune (con la webapp lo troviamo) non è presente nello scarico del 16/9.
Il cittadino ha ID ANPR 9458552.

Potete verificare ?
Grazie.

**Comment by azabatta** [comment]
Buongiorno,
il soggetto non è stato estratto per un disallineamento presente sul cittadino in ambiente di TEST_COMUNI  che ha comportato lo scarto in fase di elaborazione dello scarico. La posizione si è disallineata a causa di un errore in una procedura di annullamento effettuata nell’aprile  2018 (errore successivamente rimosso). 
Abbiamo verificato i dati del cittadino in ambiente di PRODUZIONE:  la posizione è corretta.

**Comment by busaster** [comment]
ok grazie
