### ISSUE TITLE
Errore "utente non abilitato 7"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1597]
Buon giorno,
al comune di Porto San Giorgio, ambiente di produzione, per un determinato operatore, si verifica l'errore in oggetto su tutte le principali operazioni (iscrizioni, mutazioni e cancellazioni) che tenta di eseguire in ANPR. L'errore ci sembra strano in quanto l'operatore risulta abilitato a tutte le operazioni sulla console di amministrazione.
Si tratta di una anomalia nella configurazione effettuata dall'ente o c'è un problema particolare per quell'operatore?
Grazie, cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by cmigliardi** [comment]
Buonasera, cortesemente mi può indicare il nome dell'operatore ?  mi invii i dati alla email   cmigliardi@sogei.it - grazie

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
