### ISSUE TITLE
WS 1002 ricomparsa da irreperibilità  issue  #1592

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1598]
quale deve essere il motivo di iscrizione quando è già presente in ANPR?

**Comment by frmariani** [comment]
motivo 5 Ricomparsa da Irreperibilità

**Comment by frmariani** [comment]
La issue viene chiusa, nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
