### ISSUE TITLE
Variazione dati cittadino cancallato per irreperibilità

### ISSUE THREAD

**Issue by AnnaUrban** [italia/anpr#1599]
Comune di Serravalle Sesia - ambiente di produzione
Un cittadino italiano è stato cancellato per irreperibilità nel mese di ottobre 2018. A giugno del 2018 era stata pronunciata una sentenza di scioglimento del suo matrimonio, passata in giudicato a gennaio 2019 e trasmessa ieri (17 settembre 2019) dal Tribunale al nostro comune. Oggi abbiamo provveduto all'annotazione sull'atto di matrimonio e agli adempimenti conseguenti. Tuttavia, poiché l'interessato è stato cancellato per irreperibilità, non riusciamo a registrare l'evento sulla sua scheda anagrafica. Il dubbio è il seguente: qualora l'interessato ricompaia in altro comune, l'iscrizione in quel comune avverrebbe 'prelevando' i dati direttamente da ANPR e gli stessi non sarebbero corretti in quanto mancherebbe la registrazione del divorzio. Lo dobbiamo annotare solo sul nostro database senza aggiornare il dato ANPR? L'eventuale Comune di nuova iscrizione si porrà il problema e ci chiederà comunque una conferma dei dati? Magari mi preoccupo per nulla, ma il dubbio rimane…

**Comment by frmariani** [comment]
Nel momento della re-iscrizione il nuovo Comune dovrà necessariamente chiedere conferma della correttezza dei dati al cittadino, pertanto le informazioni saranno adeguatamente aggiornate.

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
come successo a Serravalle di Sesia anche a noi capita di dover rettificare dati (ad esempio: atti di nascita, cittadinanze o stati esteri di nascita) su posizioni di cittadini cancellati per irreperibilità, emigrazione in comune non subentrato o decesso. Al momento l' unico modo è annullare la cancellazione, eseguire la mutazione e reinserire la cancellazione, rischiando così di commettere errori o che qualcuno possa consultare il soggetto e trovarlo iscritto mentre dovrebbe essere cancellato (cosa particolarmente spiacevole per i deceduti). E' ipotizzabile che venga resa disponibile una funzione di rettifica dati su soggetti cancellati?
Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
L'annullamento di un'operazione dovrebbe essere un'eccezione e non una prassi;  al momento, nella re-iscrizione del cittadino, viene controllata soltanto la correttezza dei dati anagrafici, gli altri dati devono essere re-inseriti; comunque stiamo per rilasciare un intervento che permetterà di recuperare i dati precedentemente acquisiti dando la possibilità di modificarli, aggiornarli o eliminarli.
Sicuramente i dati di un cittadino cancellato non potranno essere modificati.

**Comment by frmariani** [comment]
La issue viene chiusa, nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
