### ISSUE TITLE
ERRORE IN MUTAZIONE TUTTI I DATI (RETTIFICA)

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#16]
Ho cercato di eseguire la Mutazione di tutti i dati(RETTIFICA) per la persona con questo identificativo ANPR 2873575  , ma mi compare subito questo messaggio bloccante:
LOCALITA' IL CAMPO COMUNE E' OBBLIGATORIO
PER LA PERSONA NON ERANO STATE SEGNALATE ANOMALIE.
Questo errore lo riscontriamo anche su altre persone, sempre per mutazione di tutti i dati (RETTIFICA). Non siamo riusciti a portare a termine una rettifica , come ad esempio  una rettifica di data di nascita

DATA
02/03/2017

PUO' DIPENDERE DAL FATTO CHE IL CF NON SIA STATO VALIDATO IN QUANTO L'AMBIENTE DI TEST DELL'AGENZIA DELLE ENTRATE HA UNA CASISTICA RIDOTTA?

01/03/2017 Data del test

### Ambiente
X [x] test
- [x] pre subentro
- [x] subentro

**Comment by gcarbonin** [comment]
Salve. Possiamo provare ad effettuare una ricerca ma i dati indicati non ci permettono di rispondere puntualmente: occorre infatti individuare la richiesta. Non penso che il problema sia legato all'ambiente di test dell'Agenzia delle Entrate, quanto piuttosto ai dati indicati nella richiesta. Dobbiamo quindi esaminare i dati trasmessi.
E' sufficiente che ci indichi l'ambiente nel quale ha eseguito il test e l'identificativo assegnato da ANPR all'operazione (lo trova nel file di risposta).

**Comment by ANPRCDBO** [comment]
Salve, l'identificativo ANPR che vedo nel file di risposta, nell'elenco operazioni e' 423706,nell'ambiente di TESTCordiali SalutiElena Di MartinoTeam SipoComune Bologna -----gcarbonin <notifications@github.com> ha scritto: -----Per: italia/anpr <anpr@noreply.github.com>Da: gcarbonin <notifications@github.com>Data: 02/03/2017 09.36PMCc: ANPRCDBO <SipoBologna@comune.bologna.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/anpr] ERRORE IN MUTAZIONE TUTTI I DATI (RETTIFICA) (#16)Salve. Possiamo provare ad effettuare una ricerca ma i dati indicati non ci permettono di rispondere puntualmente: occorre infatti individuare la richiesta. Non penso che il problema sia legato all'ambiente di test dell'Agenzia delle Entrate, quanto piuttosto ai dati indicati nella richiesta. Dobbiamo quindi esaminare i dati trasmessi.
E' sufficiente che ci indichi l'ambiente nel quale ha eseguito il test e l'identificativo assegnato da ANPR all'operazione (lo trova nel file di risposta).

**Comment by gcarbonin** [comment]
Quel numero identifica l'invio del subentro. Ci deve contattare telefonicamente: ha scritto una mia collega.

**Comment by gcarbonin** [comment]
Il comune è stato contattato: la segnalazione proviene dal sistema gestionale e non dal WS di mutazione.
