### ISSUE TITLE
WS2003 - cancellazione soggetto

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1600]
COMUNE DI CASERTA - TEST WS
Buongiorno,
è possibile cancellare un soggetto da una famiglia con servizio  2003 e successivamente
modificare la composizione dei componenti il nucleo?

**Comment by azabatta** [comment]
Buonasera, 
sì è possibile: si utilizza il servizio 5001 - mutazione famiglia/convivenza - tipo mutazione "composizione scheda" (codice 2) e si comunicano le nuove relazioni di parentela

**Comment by azabatta** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
