### ISSUE TITLE
Richiesta di supporto per accesso al portale di Pre Subentro

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1601]
Buongiorno,
in data odierna (19/09/2019) stiamo provando ad effettuare il PRE SUBENTRO del comune 004089.
Siamo purtroppo bloccati all'accesso del portale https://dppre.anpr.interno.it/combas.

Abbiamo fatto svariate prove: con e senza smart card inserita, con il codice fiscale e password del sindaco e con codice fiscale password di altri utenti, abbiamo anche provato con la vecchia utenza COMUNETEST004089, ma nulla sembra funzionare.

Il comune ha già contattato la vostra assistenza telefonica poco fa, ma senza riuscire a risolvere il problema.

Potete darci una mano?
Ringrazio anticipatamente

**Comment by cmigliardi** [comment]
Buongiorno,  
comunichiamo che il 15 luglio 2019 sono state aggiornate le politiche di sicurezza per l’accesso agli ambienti di Pre-Subentro e Test-Comuni. 
 
Per l’accesso all’ambiente di PRE-SUBENTRO, a partire dalla data sopra indicata,  non è più possibile accedere con  le credenziali generiche ma soltanto con gli stessi dispositivi di sicurezza (smart card, certificati di postazione e credenziali) dell’ambiente di produzione a disposizione degli operatori del Comune. RICORDIAMO che tali dispositivi di sicurezza non possono essere ceduti a terzi.  
 
Per l’accesso all’ambiente di TEST COMUNI  è previsto l’accesso con credenziali nominali (e non più generiche) previo censimento da parte degli Amministratori Locali di Sicurezza dei Comuni, sulla console di test, degli utenti che dovranno accedere all’ambiente di TEST. Per tale ambiente, al fine di consentire ai comuni di effettuare il censimento degli utenti è stato stabilito che le credenziali generiche rilasciate sino alla data del 15/07/2019  potranno essere utilizzate sino al 15 settembre 2019 (dopo questa data saranno cancellate). – proroga al 15 ottobre 

 
Tali politiche di sicurezza sono adottate in ottemperanza all’avviso pubblicato il 25 giugno 2019 sul sito ANPR disponibile al seguente link https://www.anpr.interno.it/portale/documents/20182/209665/Avviso+nuove+modalit%C3%A0+accesso.pdf/5a7eead9-9aba-4999-9189-6d5afeca4beb
 
 
Di seguito si riportano le indicazioni principali e le relative Issue di dettaglio.   
 
Ambiente Pre-Subentro
per accedere alla WebApp 
occorre installare il certificato di postazione di produzione  (es.   001156-PC-001.p12) 
ed utilizzare una Smart Card attiva  
la url è:  
https://dppre.anpr.interno.it/com
(non si può utilizzare https://dppre.anpr.interno.it/combas perché si accede solo con la Smart Card)
 
se invece il Comune utilizza Web Services 
occorre installare  il certificato di postazione di produzione  (es.   001156-PC-001.p12) 
ed utilizzare una utenza censita  in ambiente di Produzione. 

 
Le principali Issue dove si parla dell’argomento sono: 
 
https://github.com/italia/anpr/issues/1410
https://github.com/italia/anpr/issues/1424
https://github.com/italia/anpr/issues/1161
https://github.com/italia/anpr/issues/1301

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
