### ISSUE TITLE
Dubbio su certificazione paternità/maternità

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1602]
Ci è successo una contestazione per cui abbiamo fatto una simulazione in ambiente di test.
Ci sembra che qualora sia presente id padre e madre oltre al cognome padre e madre, ANPR certfichi (in consultazione o in stampa scheda individuale) non il cognome nome trasmesso, ma quello attuale dell'id collegato.

Nell'ambiente di test abbiamo simulato la nascita del cittadino id 27563463, da madre ucraina con cognome ROLANDO. Sulla bambina appena nata, è indicato quindi nata da madre ROLANDO ... 

La madre id 16435387, successivamente cambia comune; poi divorzia; e quindi cambia generalità tornando al cognome da nubile.  nell'esempio GOIKO.

Se a questo punto vado a fare consultazione della bambina id 27563463, vedo non più maternità ROLANDO ... ma GOIKO ...
Chiedo se situazioni di questo tipo sono state valutate, per cui il comportamento corretto previsto è quello che vedo ora.

Marco Migliori
PAL Informatica

**Comment by rvinzani** [comment]
Nel caso si identifichino persone collegate ad una scheda principale (perchè individuate con CF o idANPR) come genitori, coniugi o uniti civilmente, ANPR mette in comunicazione le schede tramite un link. La variazione anagrafica delle singole schede è quindi indipendente dalla scheda collegata

**Comment by MarcoMigliori** [comment]
La domanda nell'esempio posto, è se è corretto per ANPR che il comune A di  iscrizione della bambina, veda cambiata la scheda individuale della stessa, sezione maternità, senza nessun intervento e probabilmente senza nessuna comunicazione. Sul db locale vedrebbero ancora maternità ROLANDO.

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fosse necessario ulteriore chiarimento si prega di aprire altra issue che faccia riferimento a questa stessa
