### ISSUE TITLE
Omissione veicolo pratica di residenza

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#1603]
Dalla web app Mutazione tutti i dati abbiamo provveduto ad inserire il flag nella casella veicoli poiché un cittadino, in occasione di un cambio di residenza, aveva omesso di comunicarci di essere proprietario di un auto.
Con questa operazione parte la comunicazione telematica alla motorizzazione per la successiva spedizione del tagliando di aggiornamento dell'indirizzo?
Nel caso in cui, invece, ad essere omessa fosse stata la patente qual è la procedura, considerato che nella mutazione tutti i dati non vi è la casella riferita alla patente?
Grazie.
Comune di Altamura

**Comment by azabatta** [comment]
Buonasera, 
sì, si conferma che con la comunicazione indicata parte una notifica da ANPR verso MCTC. La notifica riporta l'ultimo indirizzo presente a sistema per il cittadino e viene poi elaborata dai sistemi di MCTC.
Analoga comunicazione parte in caso di modifica dell'informazione relativa alla patente. 
Sulla web app per modificare l’informazione si utilizzano le stesse modalità: si spunta sempre la casella “Autoveicoli” della sezione “dati di controllo”. 
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa.
