### ISSUE TITLE
Consegna certificati postazione e seconda parte PIN

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1604]
COMUNE DI CASERTA - 061022
Buongiorno,
Abbiamo ricevuto, nel mese di luglio, dalla Prefettura le smart card con la prima parte di PIN PUK e PASSWORD.
Ad oggi non è pervenuta alcuna mail per certificati di postazione e altra parte delle credenziali,
ma solo i lettori di smart card.
Come mai?
Grazie

**Comment by cmigliardi** [comment]
Finché il Sindaco o l' APL  non attivano le altre SC  - il  sistema Anpr non  invia la seconda parte di pin e  puk - 
il certificato di postazione è stato inviato   il venerdì 14 giugno 2019 03:31
Al sindaco:     MARINO CARLO.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
