### ISSUE TITLE
Permalink archivio comuni non funzionante

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1605]
Vedi issue #1252 
Se navighiamo alla URL
[https://www.anpr.interno.it/portale/anpr-archivio-comuni](url) , citata nel commento [](https://github.com/italia/anpr/issues/1252#issuecomment-513258080,) otteniamo l'errore allegato. Potete verificare ?
Grazie

![permalink](https://user-images.githubusercontent.com/1733338/65254500-b1233880-dafc-11e9-967d-5fb07b607eb1.png)

**Comment by ncapozzi** [comment]
Buongiorno,
stiamo verificando.
N. Capozzi

**Comment by ncapozzi** [comment]
E' stato ripristinato il permalink https://www.anpr.interno.it/portale/anpr-archivio-comuni.csv nel formato richiesto il 23 luglio nella issue di riferimento.

Potete verificare per favore?
N. Capozzi

**Comment by bfilipazzi** [comment]
Funziona, grazie.
Filipazzi - Maggioli
