### ISSUE TITLE
Consegna certificati postazione e seconda parte PIN #1604 #1606

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1607]
Buongiorno,
IL SINDACO DI CASERTA 061022 - CARLO MARINO

**Comment by cmigliardi** [comment]
inviata di nuovo la email con la seconda parte di pin e puk al sindaco

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
