### ISSUE TITLE
Consegna certificati postazione e seconda parte PIN #1604 #1606 #1607

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1608]
COMUNE DI CASERTA 
Buongiorno
Grazie per la gentilissima collaborazione e pazienza.
Ma il certificato di postazione?

**Comment by cmigliardi** [comment]
inviato di nuovo sempre al sindaco - come prevede la norma

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
