### ISSUE TITLE
[3002] Nome composto con più spazi

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1610]
Ambiente di produzione, comune di Schio

cercando con il WS in oggetto la persona ID ANPR 39417438 otteniamo un risultato in cui il nome è composto da due parole separate da un doppio spazio (id operazione 122977548).
Consultando lo stesso cittadino con la webapp sembra che lo spazio sia uno solo.

Come mai ?

**Comment by mttfranci** [comment]
Salve, in realtà si tratta solo della visualizzazione dell' html.
Se aprite il sorgente della pagina vedrete che gli spazi sono due, ma l'html collassa spazi multipli se non si usa esplicitamente l'entity  `&nbsp;`.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
