### ISSUE TITLE
Anomalie da subentro

### ISSUE THREAD

**Issue by chiaralea** [italia/anpr#1611]
Buongiorno,

vorremmo sapere se è previsto, in eventuali evoluzioni, la possibilità di sanare definitivamente le anomalie di subentro, come ad esempio l'errore EN306. 
Il Comune di Torino, in ambiente di produzione, ha immigrato un soggetto che presentava questa anomalia (ID ANPR 64812021). Prima di immigrarlo, però, è stato chiesto al comune di provenienza del soggetto di sanare la situazione. Il cittadino ora risulta con coniuge e matrimonio presenti, quindi ci stiamo chiedendo quale sia il vero motivo di portarsi dietro un'anomalia che è ormai sanata.

Grazie,
Chiara Leanza per il Comune di Torino

**Comment by cmigliardi** [comment]
Buongiorno, EN306   Presenza del coniuge e assenza del matrimonio  resta come anomalia da subentro - nella storia della scheda anagrafica - ma una volta sanata  non crea problemi.

**Comment by cmigliardi** [comment]
al momento non ci sono evoluzioni in tal senso. 

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
