### ISSUE TITLE
Errore su revoca dati matrimonio

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1612]
Comune di Modena - Ambiente di produzione

Buongiorno,
dobbiamo eliminare il matrimonio dal soggetto con idAnpr 19366527; abbiamo tentato da webapp con la funzione "Eliminazione dati" indicando a video:
data decorrenza = oggi
tipo scheda = “soggetto”
tipo revoca = “matrimonio”
ma qualsiasi motivo revoca utilizziamo ci viene restituito l' errore “Sezione matrimonio non presente” e non riusciamo a  proseguire.
Ci sembra lo stesso caso risolto positivamente per il Comune di Savona nella issue #1377; per cortesia potete indicarci come agire?

Grazie, saluti
Sonia Fiorini

**Comment by azabatta** [comment]
Buongiorno, 
la funzionalità di eliminazione dei dati può essere utilizzata solo per i dati comunicati in fase di subentro.
Per la cittadina in trattamento in subentro i dati del matrimonio non erano presenti (si può verificare con una consultazione della cittadina alla data del subentro del comune) e questo spiega la segnalazione di errore restituita dal sistema. I dati ad oggi sono presenti e risultano comunicati ieri con una mutazione dati scheda (idOperazione ANPR 123799154). In questo caso i dati possono essere eliminati con un annullamento di tale mutazione dati scheda. Se la soluzione non fosse chiara si suggerisce di aprire una segnalazione al numero verde 800863116.
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti di carattere generale si prega di aprirne un'altra facendo riferimento a questa stessa.
