### ISSUE TITLE
cessazione unione civile per decesso del coniuge U.C.

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1613]
Ambiente di test Codroipo (030027)
id operazione 23959- con l'operazione viene iscritta una persona vedova di U.C. .
vengono inviati i dati di unione civile e i dati della cessazione della stessa.
Sul portale risulta pero' che il luogo dell'evento di unione civile è SUTRIO mentre l'evento dell'unione civile è Trieste. 
Sutrio è il comune di decesso del coniuge (e quindi il luogo dell'evento di cessazione di U.C.).
potete verificare?

**Comment by azabatta** [comment]
Buonasera, 
l’errore è stato corretto, è possibile riprovare (per utilizzare la stessa richiesta annullare l’iscrizione e reinviarla).
Si rappresenta che per l’unione civile è previsto l’inserimento del solo luogo dell’unione. 
L’errore  che era presente era quello di acquisire il luogo dello scioglimento e non quello dell’unione.
La issue viene  chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa”
