### ISSUE TITLE
Ripristino iscrizione in comune fuso

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#1614]
Tiziana Testa
Gpi Spa (Insiel Mercato)

Comune di Amblar Don  -  ambiente di produzione

Buongiorno,
il comune sta cercando di fare un'iscrizione (1002) per una persona da ripristinare attraverso i web services.
La persona è residente nel comune dal 2010 mentre il comune si è fuso nel 2015.
Se inviamo una comunicazione con la descrizione attuale del comune la risposta che otteniamo è: Comune/provincia di residenza inesistente o non valido alla data di decorrenza residenza
(id operazione 124023591)

Se inviamo la comunicazione con la denominazione storica l'errore è:
Il comune di residenza deve coincidere con il comune di competenza (id. operazione 124569885).

Non riusciamo a completare l'operazione.
Cosa dobbiamo fare?

Grazie
Tiziana Testa

**Comment by rvinzani** [comment]
Si tratta di un caso particolare. ANPR non gestisce attualmente iscrizioni in comuni non validi alla data attuale.
Quello che può fare è un'iscrizione alla data di istituzione del nuovo comune.

**Comment by rvinzani** [comment]
chiudo la issue. In caso fosse necessario ulteriore chiarimento si prega di aprire una nuova issue che faccia riferimento a questa stessa
