### ISSUE TITLE
Chirimenti Richiesta1002 - TAG Residenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1615]
Buongiorno
avrei la necessità di ricevere chiarimenti in merito al fatto che il tag Residenza nella richiesta 1002 è definito nell'XSD come maxOccurs="unbounded", la residenza di un cittadino può essere più di una ?

**Comment by mttfranci** [comment]
Salve, ovviamente può esserci una sola residenza.

Però, in base alla tabella di decodifica 25, è possibile trasmettere anche, per esempio, domicilio abituale o eletto.


ID | DESCRIZIONE
1 | Residenza
2 | Dimora abituale
3 | Domicilio eletto

![image](https://user-images.githubusercontent.com/29305782/65697836-eccd7d80-e07b-11e9-8959-886d91482e25.png)
