### ISSUE TITLE
Chiarimenti su tabella 4  ANPR - specie toponimo

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#1616]
Il Comune di Ancona sta per effettuare un pre-subentro in ANPR e ci siamo accorti che nella tabella 4 di ANPR - specie toponimo non sono presenti i DUG BANCHINA e SCALO presenti nel nostro stradario di ANNCSU. Abbiamo contattato l'ISTAT che ci ha confermato che i toponimi con BANCHINA e SCALO sono validi. Pertanto vi chiediamo se è possibile fare un'integrazione della suddetta tabella o in alternativa come possiamo risolvere il problema dal momento che l'ISTAT ci ha già certificato nel 2014 il nostro stradario comunale. Grazie e saluti.

**Comment by rvinzani** [comment]
Per la tabella 4 facciamo riferimento a quanto comunicato da Istat.
[note_stradario_10_02_2015[1].pdf](https://github.com/italia/anpr/files/3663300/note_stradario_10_02_2015.1.pdf)
In ogni caso proveremo a chiedere ad Istat

**Comment by FERRETTI-LAURA** [comment]
Vi trasmetto quanto ci ha risposto già l'STAT nella persona di "Francesco Di Pede" <dipede@istat.it>
in merito a quanto da noi richiesto come chiarimento:

Buongiorno,

Sono state riconosciute a uso locale le seguenti DUG che troverete disponibili nella lavorazione dello stradario:

ACCESSO
BANCHINA
SCALE
SCALO
SCALONE

**Comment by rvinzani** [comment]
Stiamo facendo anche noi una verifica con i nostri riferimenti Istat.

**Comment by rvinzani** [comment]
Confermo che le DUG citate possono essere utilizzate solo localmente.
Non possiamo dunque inserirle nella tabella nazionale (Tabella 4)
E' però possibile utilizzare tali DUG inviando ai servizi di ANPR nel campo SpecieFonte il valore 2 e inserendo nel campo specie la descrizione della DUG locale
Chiudo la issue. Nel caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
