### ISSUE TITLE
Richiesta certificato da parte di avvocato

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1618]
Buongiorno,
un avvocato si è presentato allo sportello di un comune subentrato richedendo un certificato di residenza (uso notifica atti giudiziari) di un cittadino in ANPR, che al momento della richiesta, non era più "residente" in quel comune, ma in un altro sempre subentrato.
Gli è stato risposto di andare nel comune di attuale "residenza" per avere il certificato in quanto non è l'interessato.
Se non è un loro "residente", loro rilasciano il certificato, solo all'interessato.
E' un "comportamento" corretto?
Anche a noi è capitato, ma abbiamo emesso il certificato tranquillamente.

Grazie

**Comment by cvignati** [comment]
Commenti?

**Comment by cvignati** [comment]
Nessuna risposta??

**Comment by FilippoPapi** [comment]
abbiamo inoltrato il quesito al Ministero. siamo in attesa di risposta

**Comment by FilippoPapi** [comment]
Buonasera
di seguito la risposta del Ministero al quesito posto.

L’art. 33, del D.P.R. n. 223/1989 prevede che, fatti salvi i divieti di comunicazione di dati stabiliti da speciali disposizioni di legge e quanto previsto dal successivo articolo 35, l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, nonché ogni altra informazione ivi contenuta.
Al rilascio possono provvedere anche gli ufficiali d'anagrafe di comuni diversi da quello in cui risiede la persona cui i certificati si riferiscono (la disposizione si applica solo ai comuni subentrati).
