### ISSUE TITLE
invocazione servizi da server

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1619]
per effettuare le invocazioni dei web services dal server del comune
il parametro **_ID_OPERATORE_** deve essere il codice fiscale dell'operatore censito in ANPR?
il parametro **_org.apache.ws.security.crypto.merlin.keystore.file_** è la posizione del certificato del server?
ed il parametro **_PATH_KEYSTORE_POSTAZIONE_** è la posizione del certificato del server? quindi lo stesso del parametro precedente?

**Comment by gife67** [comment]
Buonasera,
confermo che il parametro ID_OPERATORE deve indicare il CF di un operatore censito in ANPR, con le apposite funzioni di sicurezza messe a disposizione.
Confermo che i due parametri indicati devono contenere entrambi lo stesso valore, indicante il path del certificato di postazione/server.

**Comment by carminepat** [comment]
Grazie, gentilissimo,
Buon lavoro, Carmine

**Comment by gife67** [comment]
Buon lavoro e buona serata.
Giuseppe
