### ISSUE TITLE
[1010] Iscrizione scheda convivenza

### ISSUE THREAD

**Issue by FStefano** [italia/anpr#1620]
Buongiorno

Ambiente di test Potenza Picena

Da web App abbiamo registrato una nuova scheda convivenza (id op ANPR 20178690).
Tra i dati del responsabile abbiamo indicato solo COGNOME e NOME. 
Al termine dell'operazione abbiamo notato che come responsabile era stata agganciata una persona residente in altro comune che noi non abbiamo indicato (ANPR ID 10655840).

Replicando il caso anche da WS e inviando solo COGNOME e NOME del responsabile otteniamo lo stesso problema (id op ANPR 20176036  e ANPR ID Responsabile 19368563 che non abbiamo indicato).

Stefano Ferrari
PAL Informatica

**Comment by rvinzani** [comment]
Il problema è stato individuato e verrà risolto in produzione a partire dal prossimo mercoledì 9/10
Chiudo la issue. Nel caso fossero necessari ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
