### ISSUE TITLE
ANPR - Gestione residenti con protocollo riservato

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#1621]
Il Comune di Ancona si sta preparando al pre-subentro in ANPR e vorremmo sapere come vengono gestiti in ANPR i residenti con protocollo riservato. Grazie e saluti.

**Comment by rvinzani** [comment]
L'indicazione del Ministero è di non conferirli in ANPR al subentro. Per la successiva gestione è previsto un intervento attualmente in verifica da parte del Ministero dell'Interno
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
