### ISSUE TITLE
Aggiornamento della carta di circolazione

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#1622]
Buongiorno,
in relazione alla issue:

https://github.com/italia/anpr/issues/931

Si richiede se è possibile integrare il servizio 5001 di MutazioneFamiglia-Convivenza con tipoMutazione uguale a 7/8/9 in modo da poter confermare/modificare il possesso di veicoli e patenti per i componenti la pratica con un’unica operazione così come fatto con il tipoMutazione 5 ’Residenza scheda con patente e autoveicoli’ al fine di consentire l’invio del tagliando di aggiornamento della carta di circolazione da parte della Motorizzazione a seguito di una modifica dell’indirizzo di residenza dei cittadini componenti la pratica.

L’esigenza è quella di evitare la registrazione di operazioni di Mutazione tutti i dati per i singoli componenti la pratica.

Cordiali saluti.

**Comment by rvinzani** [comment]
La comunicazione alla MCTC viene invita anche per i tipi 8 e 9 laddove sia già presente l'informazione del possesso autoveicoli. Per il momento non si prevedono ulteriori evoluzioni .
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa

**Comment by AMonopoliADS** [comment]
adesso mi sembra che il messaggio sia stato modificato con l'aggiunta della data che blocca la variazione.
la cosa strana è che non non ha accetta la data 15/07/2019, pur indicando questa stessa nel messaggio
idOperazioneComune 2019019686
```
		<listaErrori>
			<errore>
				<codiceErroreAnomalia>EN240</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 15-07-2019</testoErroreAnomalia>
			</errore>
			<errore>
				<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-10-01 16:49:56 , idOperazioneANPR 133661434</testoErroreAnomalia>
			</errore>
		</listaErrori>
```

l'invio con decorrenza 30/09/2019 è andato bene, ma vorrei capire se il blocco sul 15/07 fa parte del bug o se c'è una ragione reale.
grazie
