### ISSUE TITLE
Emissione CIE : modalità di pagamento

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1623]
COMUNE : CAPONAGO
OPERATORE : VARISCO M.GIUSEPPINA

Quando si emette un CI con il sistema CIE esiste la possibilità di indicare la modalità di pagamento : POS, CONTANTI .. etc, questo dato come può essere trasferito all'anagrafe locale?

**Comment by FilippoPapi** [comment]
buonasera 
mi dispiace ma questa chat è relativa solo ad ANPR. per problematiche legate alla CIE potete rivolgervi al sistema di assistenza CIE.
cordiali saluti
