### ISSUE TITLE
[2003] Ripristino Posizione Anagrafica - Errore EN240

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1624]
ambiente di PRODUZIONE - comune di FAENZA (039010)

idSoggettoANPR 64366820

soggetto iscritto con ws 1002, deve essere cancellato per ripristino posizione precedente (ws 2003).
dopo un primo momento in cui il tentativo di cancellazione segnalava la presenza di variazioni più recenti, si è deciso di annullare tutte le comunicazioni inviate successivamente all'iscrizione.
nonostante questo la comunicazione di cancellazione continua a ritornare con errore:
```
		<listaErrori>
			<errore>
				<codiceErroreAnomalia>EN240</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto</testoErroreAnomalia>
			</errore>
			<errore>
				<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-09-30 16:06:17 , idOperazioneANPR 133087239</testoErroreAnomalia>
			</errore>
		</listaErrori>
```

abbiamo controllato anche la posizione della madre (idSoggettoANPR 19146062), intestatario nel nucleo dal quale deve essere cancellato il soggetto.
abbiamo annullato anche una sua mutazione, pensando che potesse in qualche modo condizionare il ws 2003. ma l'errore persiste.

potete aiutarci a capire cosa blocca la cancellazione?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
E' possibile cancellare un soggetto indicando come decorrenza dell'operazione una data maggiore o uguale all'ultima operazione effettuata sul soggetto ma la data di cancellazione può essere antecedente. 
<ns2:Richiesta2003 xmlns:ns2="http://sogei.it/ANPR/2000cancellazione">
			<testataRichiesta>
				<idOperazioneComune>2019019661</idOperazioneComune>
				<codMittente>039010</codMittente>
				<codDestinatario>ANPR02</codDestinatario>
				<operazioneRichiesta>2003</operazioneRichiesta>
				<dataOraRichiesta>2019-09-30T16:06:16</dataOraRichiesta>
				<tipoOperazione>C</tipoOperazione>
				<protocolloComune>683-2019</protocolloComune>
				<dataProtocolloComune>2019-09-27</dataProtocolloComune>
				<tipoInvio>PROD</tipoInvio>
				<dataDecorrenza>**2019-07-15**</dataDecorrenza>
				<dataDefinizionePratica>2019-09-27</dataDefinizionePratica>
				<nomeApplicativo>DE4GSD</nomeApplicativo>
				<versioneApplicativo>V4.5.3 - V7.0.b del 03 05 2019</versioneApplicativo>
				<fornitoreApplicativo>ADS - Gruppo Finmatica - Bologna</fornitoreApplicativo>
			</testataRichiesta>
			<datiCancellazione>
				<motivoCancellazione>12</motivoCancellazione>
				<dataDecorrenzaCancellazione>**2019-07-15**</dataDecorrenzaCancellazione>
			</datiCancellazione>

Chiudo la issue. Nel caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
