### ISSUE TITLE
Esigenza particolare su numerazione civica (palazzi)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1627]
Buongiorno
Abbiamo un comune che per ragioni storiche risalenti a decenni fa, ha diversi edifici
sul territorio comunale senza numerazione civica, ma con un "nome palazzo".
La situazione riguarda alcune migliaia di residenti, non è quindi un fatto minore.

esempio di civico:

specie=VIALE
toponimo=GIACOMO MANCINI
civico (assente o 0)
lettera=COOP. PIANO DEGLI SVEVI

Ho i seguenti problemi:
1) La denominazione del palazzo anche abbreviata supera la lunghezza massima ammessa dal campo lettera.
2) se il civico è 0 gli altri campi come lettera e/o esponente1, vengono omessi dalla certificazione anpr.

Fatemi sapere quale soluzione è meglio adottare per il subentro.

**Comment by rvinzani** [comment]
Mi sono consultata con i colleghi per cercare di trovare una soluzione poichè attualmente non è previsto questa tipologia di indirizzi. Direi di utilizzare uno dei due campi per inviare l'informazione ad ANPR al subentro poi verificheremo come inserirla sui certificati senza che questo abbia impatto sulla logica di stampa delle informazioni relative all'indirizzo per gli altri comuni

**Comment by MarcoMigliori** [comment]
Se non ci sono state modifiche recenti, ricordo che lettera è di lunghezza massima 10, mentre esponente1 mi sembra di 80. Vista la vostra risposta mi orienterei quindi su esponente1. Non è ancora stato fatto il presubentro, cercherò di organizzarlo in questo modo.
