### ISSUE TITLE
[5013] Revoca dati matrimonio - errore EN394

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1628]
Buon giorno,
stiamo testando la revoca dei dati del matrimonio in ambiente Test Comuni (comune di Pianella, subentrato) utilizzando il ws in oggetto, ma otteniamo in risposta l'errore _EN394_ - 'Per il tipo revoca 6 e' obbligatorio specificare il set di dati GENERALITA_PER_RICERCA'.
Abbiamo verificato che il set _generalitaPerRicerca_ è però presente nella request generata, come da specifiche, all'interno del blocco _schedaSoggetto_, per cui non capiamo come procedere per completare la revoca del dato.
L'operazione è stata effettuata oggi 01/10/2019, id operazione comune 0680302019100131.
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by frmariani** [comment]
I servizi di revoca possono essere utilizzati soltanto a valle del subentro, pertanto non è necessario inviare i dati specifici da revocare (nel vostro caso i dati del matrimonio);
il controllo è sicuramente fuorviante e ci stiamo apprestando a modificarlo, comunque ripetete l'operazione eliminando i dati del matrimonio dall'xml

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo provato ad operare come indicato, ossia non inserendo i dati del matrimonio all'interno del blocco _schedaSoggetto_, ma abbiamo ottenuto in risposta l'errore 999 - 'Operazione non effettuabile'.
Per verifica abbiamo tentato di eseguire una revoca dati anche da web application, sullo stesso soggetto, e l'operazione è andata a buon fine, quindi immaginiamo che ci sia ancora qualche inesattezza nella request che generiamo.
Per consentirvi un riscontro abbiamo ripetuto l'operazione su un altro soggetto (id operazione comune 0680302019100423) sempre col medesimo messaggio di errore.
Il test è stato effettuato sempre in ambiente di test comuni con il comune di Pianella.
Grazie,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by frmariani** [comment]
per favore inserisca l'idanpr del soggetto e riprovi, grazie

**Comment by Amucciarelli74** [comment]
Ok, 
inserendo il campo nel blocco _generalitaPerRicerca_ l'operazione è andata a buon fine, chiediamo però se si tratti di un funzionamento particolare legato alle operazioni di revoca, dato che da specifiche il campo _idSchedaSoggettoAnpr_ nelle generalità per ricerca è obbligatorio solo nel caso di assenza sia del codice fiscale che dell'id scheda soggetto comune (come indicato nel file generalita.xlsx).
Chiediamo inoltre conferma che i dati specifici da revocare non vadano inseriti neanche per le altre tipologie di revoca (unione civile, convivenza di fatto ecc.).
Grazie per il riscontro,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by frmariani** [comment]
le specifiche sono corrette, si tratta di un malfunzionamento che stiamo correggendo; nel frattempo volevo aiutarla a concludere il test; 
miglioreremo anche la descrizione dell'errore in modo che sia chiaro il riferimento a non inserire i dati specifici della tipologia di revoca.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.
