### ISSUE TITLE
ERRORE invio Operazione ' Mutazione tutti i dati'  Stato civile - CAIRO

### ISSUE THREAD

**Issue by FulvioDeda** [italia/anpr#1629]
Salve,
siamo DEDAGROUP SRL per il comune di CAIRO MONTENOTTE (SV) 
Codice Istat | 009015
-- | --

ID ANPR CELIBE 40809840
ID ANPR DIVORZIATO 40809838

in ambiente di produzione il cliente sta cercando di inviare una pratica di 'MUTAZIONE TUTTI I DATI' - STATO CIVILE per unire in matrimonio i due residenti suddetti, ma il sistema va in errore:

Errore | EN272 | Alla data 21-09-2019 il soggetto XXXXXX risulta gia' coniugato o unito civilmente con un altro soggetto
-- | -- | --

Errore | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2019-09-30 15:22:23 , idOperazioneANPR 133068278
-- | -- | --

Rimaniamo in attesa di un gentile ritorno

Grazie

Un saluto

**Comment by frmariani** [comment]
E' stato rilevato un piccolo malfunzionamento che abbiamo  prontamente rimosso;

per favore ripetete l'operazione.

**Comment by frmariani** [comment]
La issue viene . In caso di ulteriori problemi si prega di riaprire una nuova issue facendo riferimento a questa stessa.
