### ISSUE TITLE
Chiarire gestione dati AIRE e certificazione

### ISSUE THREAD

**Issue by ccontavalli** [italia/anpr#163]
AIRE: ll dato di riferimento è quello di AIRE?

Se sì, i Comuni sono comunque tenuti a mantenere tutti i servizi e i certificati attualmente erogati anche in mancanza dei campi necessari che si possano perdere nel passaggio da AIRE in ANPR (es. certificato di parentela)?

I dati dei cittadini AIRE che subentrano in ANPR provengono dall’AIRE CENTRALE ministeriale, popolata dai comuni informatizzati tramite apposito tracciato (ANAGAIRE) messo a disposizione dal ministero. I dati presenti non sono completi rispetto ai dati conservati nelle anagrafi comunali:
sono assenti i dati di paternità e maternità (presenti nel modello CONS/01- circolare MIACEL n.12 del 26 giugno 1990),
i coniugi non risultano collegati pur in presenza dei dati di matrimonio,
la data iscrizione Aire parte dal 01.07.1990 (intesa come data di istituzione dell’AIRE CENTRALE), mentre nelle anagrafi comunali la data di prima iscrizione all’AIRE può essere antecedente a tale data in quanto i comuni gestivano, a scopo elettorale, l’archivio dell’Anagrafe speciale degli italiani residenti all’estero già prima di questa data; l’iscrizione avveniva su domanda esplicita del cittadino. Nella già citata circolare Miacel n.12 del 26 giugno 1990 veniva precisato che, per questi cittadini la data decorrenza dell’iscrizione all’AIRE rimaneva quella della precedente iscrizione all’AIRE comunale. In ANPR come traccia della prima iscrizione e’ presente solo l’anno di prima emigrazione all’estero.
Nella certificazione lo stato di famiglia non contiene l’indicazione delle relazioni di parentela presenti nella composizione delle famiglie AIRE. 

I dati dei familiari stranieri che vengono annotati nei fogli famiglia aire in quanto in attesa di acquisto della cittadinanza, sono assenti (modello CONS/02 – circolare MIACEL n. 2 del 7 febbraio 1992); questo significa che saranno gestiti esclusivamente dalle anagrafi locali (si chiede conferma).

**Comment by luca-teamdigitale** [comment]
Duplicate of #244
