### ISSUE TITLE
Parametri servizio di revoca

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1630]
Riprendo l'argomento della #1625 per chiedere dove posso trovare la documentazione che descrive i parametri della chiamata al servizio di revoca.
Grazie.
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Buongiorno,
la documentazione è disponibile nel portale https://www.anpr.interno.it/portale/documentazione-tecnica ◦Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica. Nella cartella MUTAZIONI trova 5013-RevocaDato.xlsx mentre nella cartella OGGETTI trova testataRichiesta.xlsx dove sono riportate le informazioni indicate ieri. 
Può anche consultare il documento ◦Specifiche di interfaccia dei servizi di ANPR per i comuni – documento generale al par. 11.3.7 RETTIFICHE (ID 5014-RETTIFICHE) 

N. Capozzi
