### ISSUE TITLE
gestione scala esterna anpr

### ISSUE THREAD

**Issue by DemograficiBov** [italia/anpr#1632]
Buongiorno 
è il Comune di Bovezzo, subentrato in data 05/07/2018, non riusciamo a far visualizzare il campo scala esterna in agenzia dell'entrate con tutti i problemi che ne conseguono a livello di identificazione corretta dell'indirizzo della scala condominiale.
In fase di subentro era stato utilizzato il campo scala esterna, dall'aggiornamento di febbraio 2019 abbiamo notato che adesso per esempio chi vive in Via Rossi 2/B interno 1 scala 7, in agenzia delle entrate risulta Via Rossi N 2 B INT 1 7, per cui crea confusione in quanto non compare la dicitura scala.
Vorremmo sapere come ovviare a questa problematica e come sistemare i cittadini già subentrati. (per i quali non viene visualizzato nemmeno il campo scala esterna). La nostra softwarehouse in merito ADS non ci sa fornire una risposta, scaricando il problema su agenzia delle entrate.

**Comment by rvinzani** [comment]
Salve, il problema dipende dalla tipologia e dal numero di informazioni relative all'indirizzo, concordati con Agenzia Entrate ed inviati a tale ente al momento del subentro. Tale accordo sembra però non coprire tutte le esigenze poiché molti comuni, come il Vostro, rilevano l'assenza di alcune informazioni ritenute importanti. L'Agenzia delle Entrate per tale motivo ha deciso di mettere in campo una revisione delle informazioni relative all'indirizzo da acquisire da ANPR e quindi dal comune al momento del subentro ed anche di recuperare nel tempo le informazioni mancanti relative ai comuni già subentrati. Non so però darvi i tempi in cui questo processo avverrà. 
La vostra software house non è quindi responsabile.
Chiudo la issue. Nel caso fossero necessari ulteriori informazioni si prega di aprire una nuova issue e di far riferimento a questa stessa
