### ISSUE TITLE
[WEBAPP] errore SP000 in revoca dato WEBAPP

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1633]
Riprendo quanto segnalato nella #1625 
L'operazione che stiamo provando è una REVOCA da WEBAPP , quindi non facciamo nessuna chiamata a servizio.
la domanda è nella WEBAPP dove dobbiamo specificare i parametri che ci sono stati indicati nella issue collegata ? 

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
avete selezionato Iniziativa = Rettifica dalla WEB APP, potete selezionare una delle altre due iniziative proposte.

N. Capozzi

**Comment by busaster** [comment]
Ok grazie, segnalo che per gli altri casi in cui la "rettifica" non è corretta la drop down non la presenta nemmeno,ad esempio nelle iscrizioni.
Probabilmente lo stesso andrebbe fatto per "eliminazione dati"

**Comment by ncapozzi** [comment]
OK provvederemo appena possibile
