### ISSUE TITLE
[1002] Iscrizione di soggetto cancellato ANPR: decorrenze incoerenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1634]
ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA (037054)

idSoggettoANPR 71201349
idSoggettoANPR 71201350

originariamente i due soggetti (non presenti in ANPR) sono stati iscritti a San Lazzaro con decorrenza 23/9.
nel frattempo il comune di provenienza è subentrato, e trovandosi i soggetti ancora residenti, li ha cancellati da ANPR per DOPPIA ISCRIZIONE (ma con decorrenza 1/10, presumibilmente la data dell'operazione).

per evitare la duplicazione delle anagrafiche, San Lazzaro ha voluto annullare l'iscrizione originaria per procedere con un nuovo ws 1002 collegato ai soggetti popolati con il subentro (i due soggetti presenti in anpr come cancellati per doppia iscrizione).

ciò che si vuole segnalare è che il sistema ha permesso di iscrivere i soggetti con una decorrenza antecedente alla data di cancellazione che i soggetti avevano in ANPR.
(iscritti a San Lazzaro con decorrenza 23/9, precedentemente cancellati per doppia iscrizione con decorrenza 1/10).

è corretto così? oppure il sistema avrebbe dovuto bloccare l'operazione?
si pensava di annullare tutto, chiedere all'altro comune di cancellare con la decorrenza giusta e poi iscrivere nuovamente con ws 1002... ci sono altre soluzioni?

grazie 
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Se l'iscrizione è per ripristino la data di cancellazione del comune di destinazione è alla data del trasferimento del soggetto nel suo comune, ma la data di iscrizione nel comune di provenienza è alla data originaria. Si tratta comunque di casistiche particolari che si generano dalla situazione transitoria dei comuni in ANPR.

**Comment by AMonopoliADS** [comment]
non si tratta di iscrizione per ripristino.
i soggetti sono immigrati regolarmente per "immigrazione da comune non subentrato".
poi il comune di provenienza è subentrato prima che li cancellasse per "emigrazione", quindi non potendoli cancellare da ANPR x emigrazione, li ha cancellati per "doppia iscrizione", ma con decorrenza sbagliata (successiva al reale trasferimento).
si voleva evidenziare che nel tentativo di rifare la pratica collegandola si soggetti popolati con il subentro (poi cancellati per doppia iscrizione), il sistema accetta di iscrivere con una data antecedente quella di cancellazione, il cliente si aspettava un blocco.
solo questo, tenetelo presente.
grazie

**Comment by rvinzani** [comment]
Grazie della segnalazione. Ne terremo conto
