### ISSUE TITLE
[6001] Ancora errore EN087 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1635]
Ambiente di produzione, comune di BREMBATE DI SOPRA

Tentando di rilasciare un certificato per un soggetto con il servizio 6001 otteniamo "EN087 La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti" (id operazione ANPR 133924728).
Consultando i dati del soggetto non abbiamo rilevato anomalie.
Sembra molto simile alla #1518 

Potete verificare ?

Grazie

**Comment by mttfranci** [comment]
Salve c'era un problema sui dati dello specifico soggetto coinvolto.
(la situazione è simile a quella della issue #1518 e non è un problema generalizzato).
Potete riprovare per favore?
