### ISSUE TITLE
[PROD] Anagrafica Doppia

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1636]
ambiente di PRODUZIONE - comune di FAENZA (039010)

si chiede un vostro contributo per capire una situazione anomala che è stata evidenziata dal cliente.

il comune di FERRARA ha iscritto per provenienza da FAENZA il cittadino in questione.
il giro che è stato eseguito sembra essere quello tipico della mutazione tra comuni subentrati, ed infatti a Faenza è arrivata la notifica N010 per cancellare dall'anagrafe locale.

la cosa anomala è che consultando l'ANPR risultano due soggetti con stesse generalità, entrambi iscritti e residenti in comuni diversi:
- uno a Faenza con idSoggettoANPR 37149899
- uno a Ferrara con idSoggettoANPR 37149895

considerando come più aggiornata la posizione del comune di Ferrara, il cliente tenta di cancellare il soggetto con id 37149899, per doppia iscrizione, ottenendo in risposta questo errore
```
                <listaErrori>
			<errore>
				<codiceErroreAnomalia>EN509</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>Il soggetto non puo' essere cancellato per doppia iscrizione perche' non risultano due o piu' posizioni in ANPR</testoErroreAnomalia>
			</errore>
			<errore>
				<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-10-03 15:00:29 , idOperazioneANPR 134702072</testoErroreAnomalia>
			</errore>
		</listaErrori>
```

attendiamo un vostro parere sulla questione.
grazie
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
aggiungo un elemento utile.
presumibilmente le due anagrafiche sono state create da Faenza in data 08/11/2018, in occasione dell'iscrizione con ws 1002.

vedo l'invio dell'idOperazioneComune 2018025855 che è andato in errore forse per un timeout.
a seguire una ripetizione della setssa comunicazione con idOperazioneComune 2018025856 che invece è andato a buon fine.

presumo che, lato ANPR, siano andate a buon fine entrambe le comunicazioni.
bisognerebbe capire come mai la seconda comunicazione non è andata in errore, e come risolvere l'attuale duplicazione.

grazie

**Comment by rvinzani** [comment]
Si è trattato in effetti dell'invio di due richieste identiche a distanza di pochissimo tempo che il sistema ha processato in parallelo.  Il caso è la prima volta che si verifica.
Se la doppia richiesta è partita dalla stessa postazione come credo sia, potrebbe essere utile non consentire di inviare una nuova richiesta fino alla risposta di esito della prima

**Comment by AMonopoliADS** [comment]
come cancellare quindi il soggetto replicato, considerato che il tentativo di ws2003 per "doppia iscrizione" ritorna l'errore segnalato?
grazie

**Comment by rvinzani** [comment]
E' necessario cancellarlo per altri motivi inserendo magari come nota l'errota iscrizione.
E' però necessario riallineare il soggetto di Ferrara in quanto la cancellazione toglie la marcatura del soggetto in AE. Per questo è possibile procedere con la Risoluzione disallineamenti con AE
