### ISSUE TITLE
Annullamento iscrizione precedente al Subentro con ritorno all'Aire del Comune

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1637]
Buongiorno,
Ambiente di Produzione.
Codice ANPR dell'individuo: 70946900

In data 03/06/2019, prima del suo Subentro, un nostro Comune ha immigrato nell'anagrafe dei Residenti un cittadino, per rimpatrio dalla propria AIRE.
Eseguiti gli accertamenti del caso, tale cittadino non risulta essere residente nel Comune in questione, che nel frattempo è subentrato e si trova a dover ripristinare la situazione di questo loro cittadino.

Nello specifico le operazioni da seguire sarebbero l'annullamento dell'iscrizione in anagrafe del 03/06/2019 e la relativa correzione dei suoi dati in modo che risulti essere iscritto all'Aire del Comune, senza interruzioni, dalla data del 26/06/2017.

Il Comune ha già contattato l'assistenza telefonica che non ha potuto fornire soluzioni in merito al caso specifico, rimandando eventuali soluzioni a questo forum.
Quali indicazioni possiamo dare al Comune per risolvere la situazione?
Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera,
il comune di precedente iscrizione AIRE è subentrato?

**Comment by SAlberto** [comment]
Buongiorno,
il Comune di precedente iscrizione AIRE del soggetto è il Comune stesso, che all'epoca dell'iscrizione in APR non era ancora subentrato.

Saluti

**Comment by ncapozzi** [comment]
Il comune deve eseguire una cancellazione per altri motivi, presumo con data decorrenza = data del presunto reimpatrio e una iscrizione AIRE per altri motivi alla data di iscrizione originale. 

Per problemi che come questo richiederebbero una assistenza telefonica per comprenderne meglio gli aspetti  e magari anche verifiche sul sistema ANPR, le suggerisco di non utilizzare GitHub ma di contattare il nostro call center al numero 800863116.

Saluti

N. Capozzi

**Comment by SAlberto** [comment]
Innanzitutto grazie per la soluzione, abbiamo contattato il Comune e siamo riusciti a sanare la situazione.

Sono d'accordo nel non usare Git-Hub per problemi come questo, infatti, come le ho scritto all'apertura di questa Issue, il Comune ha già contattato il call center al numero 800863116, ma è stato invitato a rivolgersi alla Software House in modo che vi contattasse tramite issue sul portale Git-Hub.

Saluti
