### ISSUE TITLE
Statistiche Istat - ISPAT - Trentino post-subentro ANPR

### ISSUE THREAD

**Issue by marcnic** [italia/anpr#1638]
La Provincia Autonoma di Trento, tramite I.S.P.A.T., richiede ai comuni Trentini la produzione delle Statistiche Istat anche per i mesi successivi al subentro in ANPR.

Anche nell'ultima circolare Istat Prot.n.1836510/18 del 21/12/2018, che allego per comodità, si ribadisce che: 
"Come indicato nelle circolari Istat degli anni precedenti, allorché un Comune sarà transitato in ANPR, a partire dal mese successivo a quello del subentro non dovrà più inviare all’Istat i dati relativi alle suddette rilevazioni di fonte anagrafica."

I comuni trentini possono sospendere, come tutti gli altri Enti sul territorio nazionale, la produzione delle statistiche mensili di fonte anagrafica dal mese successivo al subentro in ANPR ovvero mantengono obblighi specifici verso l’Ufficio di Statistica Provinciale?

Grazie,
Marco

[circolare_Istat_statistiche_2019.pdf](https://github.com/italia/anpr/files/3686419/circolare_Istat_statistiche_2019.pdf)

**Comment by marcnic** [comment]
Sollecito gentile riscontro.

Buon lavoro,
Marco

**Comment by FilippoPapi** [comment]
Buonasera
ANPR fornisce all'ISTAT le informazioni di fonte anagrafica per la produzione delle statistiche. i Comuni una volta subentrati in ANPR possono sospendere  la produzione delle statistiche mensili di fonte anagrafica dal mese successivo al subentro in ANPR. non so se i comuni Trentini forniscono all'ISTAT ulteriori informazioni oltre quelle anagrafiche.
buona serata
