### ISSUE TITLE
Quale attività di bonifica devono effettuare i comuni sui propri dati

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#164]
Chiarire quali attività di bonifica i Comuni dovranno effettuare sui propri dati che, altrimenti, impedirebbero il corretto funzionamento dei servizi.

**Comment by ccontavalli** [comment]
Abbiamo documentazione in bozza a questo indirizzo:
https://github.com/italia/anpr-doc-subentro

Siamo in fase di verifica e revisione con gli enti coinvolti.

**Comment by gcarbonin** [comment]
E' stato pubblicato pubblicato il documento che illustra le attività da svolgere disponibile a questo link https://www.anpr.interno.it/portale/documents/20182/209665/Attivit%C3%A0+di+bonifica+propedeutiche+al+subentro+in+ANPR+6+febbraio.pdf/f3a84870-e4cd-4394-b728-4666c905ed4a
