### ISSUE TITLE
Impossibile emettere certificato di stato famiglia

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1640]
Comune di Villa Cortese - Produzione

Oggi abbiamo provato ad emettere un Certificato di Residenza e Stato Famiglia al cittadino con Id ANPR 38141340 ma da errore "_01 - Residenza: I certificati di stato di famiglia, stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile_"

Poi ho notato che il cittadino presenta l'errore _EN212 - Relazioni di parentela incongruenti per la famiglia, verificarle prima di emettere certificati di stato di famiglia_

A questo punto ho controllato le relazioni di parentela e sono corrette;
sono 3 componenti:
1-Intestatario Scheda
2-Convivente (con vincoli di adozione o affettivi)
3-Convivente (con vincoli di adozione o affettivi)

In seguito mi sono accorto che, al subentro, l'intestatario (Id ANPR 38141340) era stato popolato con stato civile coniugato, collegato alla "moglie" (Id ANPR 38138063) che era stata popolata con Stato Civile Non Classificabile.

Ho proceduto alla rettifica della Stato civile dell'Intestatario (Id ANPR 38141340) in Non classificabile in quanto non ha mai presentato nessuna certificazione comprovante il matrimonio.

Pensavo di aver risolto, invece mi presenta sempre lo stesso errore in certificazione.

Chiedo una vostra verifica

Grazie
Claudio Vignati

**Comment by rnapoli1983** [comment]
Buonasera,
cercheremo di analizzare al più presto il caso.
Nel mentre, potreste indicarci anche l'idOperazioneANPR dell'operazione riguardante l'ultima richiesta di certificato anagrafico ?
Grazie mille.
Cordiali saluti

**Comment by rnapoli1983** [comment]
Buonasera,
siamo riusciti ad analizzare comunque il caso.
L'intestatario della scheda famiglia risulta avere un matrimonio attivo con uno dei soggetti con grado parentela "Convivente (con vincoli di adozione o affettivi)".
Se viene eseguita una mutazione, su di esso, cambiando il grado parentela in "Marito / Moglie" successivamente anche l'emissione del certificato non avrà problemi.
Questo perchè la certificabilità famiglia non riguarda esclusivamente il soggetto intestatario del certificato anagrafico ma tutta la famiglia a cui appartiene.
Rimango a disposizione.
Cordiali saluti

**Comment by cvignati** [comment]
Buonasera,
come scritto in precedenza, l'intestatario scheda, in subentro è stato erroneamente caricato come coniugato.
Ho eseguito una mutazione x mettire come stato civile Non Classificabile in quanto nn ha mai prodotto certificati attestanti il proprio stato civile.

Per quanto riguarda la relazione di parentela, lui è sempre stato intestatario scheda, se mettessi Marito, la famiglia nn avrebbe più un Intestatario.

L'id Operazione riguardante il certificato dove posso reperirla?
Grazie

**Comment by rnapoli1983** [comment]
Buongiorno,
L'IdOperazioneANPR è presente nelle risposte dei servizi. 
Comunque il problema attualmente non è sullo stato civile del soggetto intestatario della scheda famiglia, ma bensì sul matrimonio che risulta avere. 
Se non ci fosse stato tale matrimonio attivo la famiglia, così come da lei descritta precedentemente:
1-Intestatario Scheda
2-Convivente (con vincoli di adozione o affettivi)
3-Convivente (con vincoli di adozione o affettivi)
sarebbe risultata certificabile.
A questo punto occorre eliminare il matrimonio caricato erroneamente al subentro.  
Per farlo, da ANPRWEB, Registrazione --> poi nella tendina selezionare "Eliminazione dati" --> nella schermata successiva a "tipo revoca" selezionare matrimonio.
Le ricordo poi che se ha urgenza di produrre il certificato può rendere l'errore attualmente bloccante, warning con il campo "forza certificazione".
Rimango a disposizione.
Cordiali saluti.

**Comment by cvignati** [comment]
Risolto facendo la procedura di elimina dati matrimonio da WebApp.

Grazie.
