### ISSUE TITLE
Tag: <Interno1> dimensione massima

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1641]
Buongiorno,
in seguito alla issue #1617 si sono generate situazioni simili.
Cittadini residenti in indirizzi con interni composti da 5 cifre.
Fino a questo momento i dati passati ad ANPR sono stati tagliati a 4 cifre per permettere il caricamento dei dati stessi.
In indirizzi con interni che superano le 4 cifre, come è consigliabile agire?
Valutando gli altri tag come <interno2> non mi sembrano corretti poiché nel certificato non vengono stampati insieme.

 In attesa di riscontro la ringrazio, cordiali saluti.

**Comment by mttfranci** [comment]
Sarebbe stato preferibile senza dubbio confrontarci su queste casistiche prima del subentro, ma per poter valutare meglio come procedere potreste fornirci alcune informazioni?

1.       Gli interni troncati sono stati trasmessi anche in fase di subentro?
2.       Quale è il numero di residenze per le quali il troncamento è avvenuto?

Grazie in anticipo.

**Comment by fmbianchi** [comment]
Si, gli interni troncati sono stati trasmessi anche in fase di subentro.
Facendo una verifica nei nostri comuni più grandi le residenze con interni troncati sono circa 1200.

In attesa di riscontro la ringrazio, cordiali saluti.

**Comment by rvinzani** [comment]
Chiudo la issue in quanto la richiesta è stata verificata con il comune e non più necessaria. In caso siano necessarie ulteriori informazioni si prega di riaprire la issue facendo riferimento a questa stessa
