### ISSUE TITLE
Gestione Smartcard assegnata ad altro comune

### ISSUE THREAD

**Issue by sicmunso** [italia/anpr#1642]
Comune di Sondrio - Produzione

Buongiorno,
una collega dell'anagrafe dispone di una smartcard rilasciata al comune di Ponte in Valtellina.
Questa sc non è mai stata attivata dato che quando la collega lavorava a Ponte il comune non aveva ancora effettuato le operazioni di subentro.
Poco tempo fa, l'operatrice del comune di Ponte ha prima bloccato e poi revocato la sc.
Ora noi non abbiamo modo di gestire la sc per rendere operativa la collega e non possiamo chiedere una nuova sc (ci abbiamo provato) perché esiste ancora la precedente.
Come possiamo riattivare ed associare al Comune di Sondrio la smartcard o ottenerne una nuova?
Grazie
Luca Di Mauro

**Comment by Leonforte** [comment]
Buongiorno,
dalle verifiche effettuate non risultano situazioni anomale per entrambi i comuni.
Le smart card risultano tutte attive, anche quella dell'unica utenza (Cinzia B.) abilitata su entambi i comuni.
Con la SC richiesta e attivata dal comune di Ponte l'utente puo accedere anche per il comune di Sondrio. 
Saluti

**Comment by sicmunso** [comment]
Salve,
l'ultima comunicazione avuta col comune di Ponte dava lo stato della carta "bloccata" mentre lo stato del certificato era "revoca in lavorazione".
In ogni caso se provo ad assegnare all'ambiente di destinazione "Produzione" l'utente in questione mi viene restituito l'errore "Errore CAST Assegnazione ruoli"

Chiedo inoltre come posso gestire la sc della collega dato che non ne ho visibilità?
La collega non lavora (e non lavorerà più) presso il comune di Ponte... qualora serva il reinvio di codici o il blocco della sc dovremmo appoggiarci al comune di Ponte. Non è possibile assegnarci la sc così da averne il pieno controllo?
Grazie

**Comment by Leonforte** [comment]
Ora può riprovare l'assegnazione dell'autorizzazione agli ambienti.
L'utente è stato modificato (sbloccato) da Ponte il 26 settembre , e attualmente risulta attivo così come la smart card. In tale circostanza è sempre il comune che ha censito l'utente e richiesto quindi la SC a gestirla. Se Ponte ci chiede trasferirlo a voi possiamo effettuare la mdifica d'ufficio.
La gestione deglia ambienti e dei profili è comunque indipendente per entrambi i comuni.

**Comment by sicmunso** [comment]
Ora l'assegnazione è avvenuta
Grazie per il prezioso supporto
Buona giornata
