### ISSUE TITLE
Errore invio 'Mutazione Residenza AIRE' - CONEGLIANO

### ISSUE THREAD

**Issue by FulvioDeda** [italia/anpr#1648]
Salve,
siamo DEDAGROUP SRL per il comune di CONEGLIANO
Codice Istat | 026021
-- | --

in ambiente di produzione il cliente sta cercando di inviare una pratica di 'MUTAZIONE RESIDENZA aire -Residenza Verso estero con data decorrenza 26/03/2019 ma il sistema va in errore con questo messaggio:

data decorrenza 26/03/2019 00:00:00 minore della data decorrenza 16/07/2019 00:00:00 dell'ultimo stato dell'individuo - CambioAggregazione - XXXXXXXXXXXXXXX - ID Individuo 2325787

 in quanto bloccati dalla pratica di CANCELLAZIONE ALTRI MOTIVI (id anpr 104384871) dell' I.s. della famiglia (in data successiva, 16/07/2019)  emigrato A  SAN TEODORO, COMUNE CHE é SUCCESSIVAMENTE SUBENTRATO IN ANPR.

Si richiede lo sblocco della situazione.

**Comment by ncapozzi** [comment]
Buongiorno,
potete indicare l'id operazione della mutazione di residenza che va in errore?


N. Capozzi

**Comment by MarcoMigliori** [comment]
Buongiorno, scusate l'intervento: stavo per aprire un'altra issue su un caso simulato in ambiente di test (personalmente non mi è ancora capitato in produzione). Il tema è quello descritto da Dedagroup: se rispecchio la modifica di legge inserendo data iscrizione Aire **retroattiva**, può succedere raramente, che ci sia un movimento con data **successiva**, che provoca il problema segnalato sopra.
Ne posso cambiare il solo valore di dataDecorrenza mettendolo a oggi, e impostando invece 26/3/2019 negli altri campi come la decorrenza della residenza, perchè questo mi porta agli errori: EF024 e EF056, impedendo la registrazione.

E' quindi un caso non frequente, che potrebbe succedere in produzione a qualunque Comune.

**Comment by ncapozzi** [comment]
Buonasera,
 i casi devono essere valutati singolarmente. Avevo chiesto a Dedagroup di indicare l'id operazione della mutazione di residenza che va in errore per effettuare una verifica ma non ho ancora ricevuto una risposta. Faccio presente che l'ID Individuo 2325787 in produzione non esiste.

Anche MarcoMigliori se lo ritiene può indicarmi un caso specifico.

In generale per una assistenza operativa diretta su casi specifici che richiedono per esempio verifiche su DB o replica del caso in test suggerisco di contattare il numero verde 800863116 fornendo il riferimento di una persona ed una fascia oraria di reperibilità.

**Comment by ncapozzi** [comment]
Buongiorno,
non avendo più ricevuto ulteriori riscontri si chiude la issue.

N. Capozzi
