### ISSUE TITLE
Rettifica indirizzo AIRE - Errore materiale di battitura

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1649]
Villa Cortese - Produzione

Buongiorno,
sono a chiedere se sia possibile rettificare l'indirizzo estero di un cittadino AIRE in quanto, per un mero errore di battitura, è stato inserito un indirizzo errato.
Il cittadino ha id ANPR 38135906.

Grazie
Claudio

**Comment by ncapozzi** [comment]
Buongiorno,
per correggere l'errore è necessario effettuare una rettifica indirizzo su ANPR richiamando il servizio di Mutazione famiglia/convivenza (5001) con tipomutazione = 9 rettifica integrazione indirizzo alla data di decorrenza della residenza della famiglia confermando i dati già presenti. 

N. Capozzi
