### ISSUE TITLE
Certificati Storici

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#165]
Certificati storici: si chiede al Ministero di chiarire se verranno emessi in ANPR o dai Comuni in locale e inoltre se si prevede in futuro di emettere un documento unico nei casi previsti (es. stato famiglia alla data del decesso - o residenza storico) che comprenda sia lo storico su ANPR che quello nell'applicativo locale (e se si devono esigere i diritti con 2 bolli). Sempre con riferimento alla certificazione storica si chiede di chiarire quale data di subentro andrà considerata per un soggetto che subisce più subentri esempio:
Soggetto subentrato in ANPR nell'Ottobre 2016 con il comune di Bagnacavallo
Cancellato da Bagnacavallo a Dicembre 2016 per emigrazione nel Comune di Lavagna
Nuovamente subentrato con il comune di Lavagna a Marzo 2017

**Comment by psaggini** [comment]
Il quesito era già stato posto un po' di tempo fa, ma con risposta negativa https://github.com/italia/anpr/issues/114 
Concordo con l'esigenza di riprendere a mano il tema, confidando in una soluzione più "agile" per tutti, Comune e cittadino.

**Comment by gcarbonin** [comment]
Premesso che ANPR può certificare quando ha registrato al suo interno, il servizio 6001 è stato realizzato sin dalle prime specifiche (correva l'anno 2014) per poter essere richiamato in due modalità:

- richiesta di certificato; in questo caso si ottiene il PDF;
- richiesta dati del certificato; in questo caso si ottiene un xml con i dati previsti per il certificato richiesto.

Questa seconda modalità copre due esigenze:

- comuni che rilasciano certificati via Internet muniti di contrassegno digitale e intendono mantenere il questo  servizio; estraggono i dati da ANPR e li stampano autonomamente con l'attuale SW in uso, contrassegno compreso;
- certificazioni storiche relative a periodi a cavallo del subentro; il sw comunale estrae i dati storici registrati nella propria base dati (che essendo riferiti al periodo ante-subentro sono gli unici certificabili) e li aggiunge a quelli ottenuti da ANPR. Il certificato prodotto è unico, come l'eventuale bollo dovuto.

I certificati storici prodotti da ANPR, per altro, al momento sono soltanto 2:

- storico cittadinanza che riporta "è cittadino italiano dal"; se i dati conferiti in anpr (o successivamente movimentati) riportano questa data, questo certificato è esaustivo e non richiede integrazioni utilizzando i dati locali;
- storico residenza che riporta la residenza ad una certa data;  se la data è ante subentro, il certificato è prodotto soltanto utilizzando i dati locali; se la data è successiva al subentro, dipende dalle varie situazioni. Con la modalità sopra descritta, è possibile integrare i dati del comune (cambi di domicilio intervenuti tra la data di prima iscrizione e decorrenza della residenza conferita in ANPR)  e dati ANPR  .

Questa funzionalità non è stata utilizzata (e quindi testata) da nessun fornitore. Siamo a disposizione per iniziare questa attività.

**Comment by psaggini** [comment]
Perfetto, noi e la nostra Ditta siamo disponibili per testare la nuova funzionalità; la documentazione è già disponibile?

**Comment by gcarbonin** [comment]
Si in quanto la funzionalità è disponibile da sempre. Dobbiamo pianificare un test congiunto.

**Comment by psaggini** [comment]
Bene, ci sentiamo la prossima settimana con uno scambio di mail e proposta di date.

**Comment by gcarbonin** [comment]
il test è stato eseguito con successo
