### ISSUE TITLE
Richiesta modalità operative di estrazione operazioni effettuate.su webapp ANPR

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#1650]
Buongiorno.
Il Comune di Bologna vorrebbe effettuare un'estrazione di tutte le operazioni effettuate su webapp ANPR per data in modo da estrapolare i codici fiscali movimentati.
Potete cortesemente indicarci la modalità più corretta per effettuare tale operazione utilizzando i servizi messi a disposizione agli enti?
Grazie mille e saluti

**Comment by rvinzani** [comment]
Per verificare i soggetti movimenti con la web app è necessario scaricare le notifiche di tipo “NRIS” con il ws 4005.
I parametri da specificare per scaricare tali notifiche (oltre a quelli obbligatori del ws )  sono: 
-          statoLavorazione = 9 (tutte le notifiche)
-          operazioneRichiesta = ‘NRIS’
-          periodoRiferimentoRichieste: 
                  dataOraIniziale
                  dataOraFinale
N.B. il periodo di riferimento deve essere settato in maniera molto accurata al fine di evitare richieste molto pesanti che causano rallentamenti del  sistema:  incrementare sempre  la dataOraIniziale in modo da evitare sovrapposizioni con la dataOraFinale della richiesta precedente. 
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue e di far riferimento a questa stessa.
