### ISSUE TITLE
Postazione certificate does not seem to carry a valid CN name (from client)

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1651]
Salve, buongiorno
sto effettuando alcuni test con i web services in ambiente di pre-subentro e ricevo il seguente errore: "Postazione certificate does not seem to carry a valid CN name (from client)"
Riepilogo i vari passaggi che ho effettuato:

- scaricato il certificato server (quello di tipo: XXXXXX-CO-9999.p12)
- invocato l'endpoint: https://wspre.anpr.interno.it/ANPR5000ServiziMutazione/AnprService5000
- verificata la richiesta con il tool che risulta essere valida e ben formata

l'errore nel dettaglio risulta essere il seguente: 
ERROR Op5008Handler:44 - Exception nell'invio richiesta
javax.xml.ws.soap.SOAPFaultException: Aborting...Postazione certificate does not seem to carry a valid CN name (from client)

Qualcuno sa darmi indicazioni sull'errore o eventualmente sto sbagliando qualcosa nella configurazione?

**Comment by rvinzani** [comment]
Sono state unificate le modalità di accesso per i due ambienti di produzione e presubentro per cui, è necessario utilizzare certificati e smart card dell'ambiente di produzione. Per quale comune state operando?

**Comment by carminepat** [comment]
Grazie della risposta innanzitutto. Si, abbiamo seguito la documentazione ed abbiamo quindi utilizzato anche per il presubentro il certificato di produzione wsprod.crt
Stiamo operando per il comune di Satriano di Lucania (076083)
