### ISSUE TITLE
Comune di Contessa Entellina - Non esiste alcun piano subentro

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/anpr#1652]
Buongiorno, 
Siamo in procinto di effettuare l'upload dei file di subentro del Comune di Contessa Entellina (082033).
Il portale di produzione riporta una segnalazione relativa alla mancata comunicazione data subentro in dashboard (Ti informiamo che non risulta acquisita una data prevista di subentro il comune. Per poter procedere al subentro è necessario che il vostro fornitore software comunichi sulla dashboard del Team digitale la data prevista per il subentro).
In realtà la data subentro è configurata in Dash (da 08/10/2019 a 02/11/2019 - Data preferita 08/10/2019).
Potreste fornirci supporto in merito?
Grazie

**Comment by rvinzani** [comment]
Il comune è stato abilitato al subentro.
Chiudo la issue.
In caso siano necessari altri chiarimenti si prega di aprire una nuova issue facendo riferimento a questa stessa
