### ISSUE TITLE
Comune di Ottati (065086) - Verifica abilitazione IP Provenienza

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/anpr#1654]
Buongiorno,
Per il comune di Ottati riceviamo da ieri in risposta la segnalazione di mancata risposta dall'host collegato 217.175.52.225:443, solita nel caso in cui non sia stato dichiarato l'ip pubblico di provenienza. Ieri è stato fatto il subentro e la codifica del nuovo ip pubblico di provenienza, che risulta da portale configurato correttamente (*). E' possibile effettuare una verifica? (IP Pubblico 94.101.53.68)

**Comment by Leonforte** [comment]
Le confermo la corretta abilitazione dell'IP 94.101.53.68 con data inserimento 08-10-2019 11:22:23, saluti

**Comment by Arionlinesrl** [comment]
Buongiorno, purtroppo l'errore in interrogazione del ws permane: "
Errore in consumo servizio 7001:Nessun endpoint in ascolto su https://ws.anpr.interno.it/ANPR7001ServizioScaricoTabelle/AnprService7001 in grado di accettare il messaggio. Ciò è spesso causato da un'azione SOAP o un indirizzo non corretto. Per ulteriori dettagli, vedere InnerException, se presente. - System.Net.WebException: Impossibile effettuare la connessione al server remoto. ---> System.Net.Sockets.SocketException: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato 217.175.52.225:443
   in System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)". Ottengo la stessa risposta anche effettuando interrogazioni. Potreste verificare? Grazie
