### ISSUE TITLE
Espatrio in AIRE di altro comune

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1655]
Abbiamo osservato che ANPR gestisce migrazioni di residenti in un comune verso l'AIRE di un altro comune. E' cosa voluta?
Lo chiedo perché nell'allegata guida AIRE del ministero dell'interno, in fondo a pagina 4 si legge che la comunicazione consolare è destinata "all'ultimo comune di residenza del cittadino", il quale se vuole l'iscrizione nell'AIRE di altro comune deve procedere con "nuova domanda dell’interessato", come si legge a pagina 5.
In altre parole: la guida esclude il caso in cui Tizio residente nel comune A possa passare direttamente nell'AIRE del comune B, cosa che ANPR ammette.
Grazie.
Filipazzi - Maggioli
[_Guida_Ministeriale_Aire_2010.pdf](https://github.com/italia/anpr/files/3706684/_Guida_Ministeriale_Aire_2010.pdf)

**Comment by ncapozzi** [comment]
Buongiorno,
nel servizio di mutazione AIRE è stato inserito un controllo tale che se il cittadino è residente (tipo scheda = 1) , il comune che sta eseguendo la mutazione AIRE deve essere lo stesso proprietario della scheda.

N. Capozzi
