### ISSUE TITLE
Rettifica dati cittadinanza

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1656]
Villa Cortese - Produzione

Buongiorno,
sono a segnalare, secondo me, un bug relativo al Tipo Operazione: Mutazione tutti i dati - Iniziativa: Rettifica della cittadinanza in WebApp ANPR.
Essendo una rettifica dovrei poter modificare i dati che ho già inserito, nel mio caso, nel Campo Note dovrei aggiungere il comune di stesura dell'atto di cittadinanza, ma non me lo permette, dovrei cliccare sulla X rossa per eliminare il dato presente ed inserirne un nuovo.

Allego PrintScreen

Grazie

![Cittadinanza_ANPR](https://user-images.githubusercontent.com/44975005/66476753-a96d0900-ea96-11e9-86e6-fd6f5dcf9e06.jpg)

**Comment by ncapozzi** [comment]
Buonasera,
la form è stata pensata solo per inserire o cancellare i dati di una cittadinanza visto che sono solo 3. Sinceramente non sembra un grosso onere anche nel caso che si sia sbagliato uno solo dei tre dati. Tuttavia possiamo pensare anche di modificare l'impostazione in sviluppi futuri.

N. Capozzi
