### ISSUE TITLE
Dati emissione CIE non vengono automaticamente registrati in ANPR

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#1657]
Dalle giornata di lunedi' 7 ottobre 19 ho rilevato che tutte le carte CIE emesse non risultano registrate du ANPR (verificando il web).
Ho dovuto quindi controllare i dati di tutti i cittadini che hanno avuto la carta in questi giorni e procedere a aggiungere i dati ad uno ad uno.
E' un problema solo mio? Altri colleghi hanno riscontrato qualcosa di analogo?
Fatemi sapere, grazie
Renzo - Comune di Valdilana (BI)  096088

**Comment by cvignati** [comment]
Villa Cortese 015248 - Produzione

Abbiamo controllato anche noi e siamo nella stessa situazione. CIE emesse dal 7 ottobre non sono registrate in ANPR.

Claudio

**Comment by RENZO63** [comment]
Credo che sia necessario un intervento urgente per risolvere il problema.
Se e' generalizzato e tutte le cie emesse in Italia sono "sfuggite" ad ANPR mi sembra cosa grave.

**Comment by LORELLAB** [comment]
Ghemme 003073-Produzione
Effettivamente dal 7/10 le CIE non sono state registrate in ANPR...

**Comment by rvinzani** [comment]
Sappiamo che c'è stato un aggiornamento dei sistemi CIE e anche noi abbiamo verificato l'assenza di comunicazioni di emissione e annullamento CIE verso ANPR. Siamo in contatto però con il poligrafico per verificare come recuperare prima possibile le mancate comunicazioni.
