### ISSUE TITLE
Rettifica dati cittadinanza

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1659]
Villa Cortese 015248 - Produzione

Mi riallaccio alla mia segnalazione https://github.com/italia/anpr/issues/1656#issue-504583811 chiusa ieri in quanto sono entrato per rettificare i dati inseriti, ma mi compare questo errore:
La data decorrenza 11-09-2019 dell'operazione non puo' essere inferiore alla data decorrenza 08-10-2019 dell'ultima operazione effettuata sui dati relativi a cittadinanza ALBANIA (Codice: EN389)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-10-10 15:26:48 , idOperazioneANPR 137482077 (Codice: EN527)

Come risolvo?

Grazie
Claudio

**Comment by ncapozzi** [comment]
Buongiorno,
nel campo dataDecorrenza in testataRichiesta è necessario impostare una data >= 08-10-2019, data dell'ultima operazione effettuata sui dati relativi a cittadinanza.

N. Capozzi
