### ISSUE TITLE
Gestione delle variazioni di toponomastica

### ISSUE THREAD

**Issue by ccontavalli** [italia/anpr#166]
Allo stato attuale non esiste la possibilità di effettuare operazioni di variazione della toponomastica né da WA né dal gestionale comunale tramite WS.

L’assenza di questa integrazione non consente ai comuni di comunicare in ANPR le variazioni conseguenti ad operazioni di ristrutturazione della toponomastica, es. ri-assegnazione dei numeri civici alle  vie, modifiche alla denominazione di vie.. ,ecc., ovvero tutte quelle operazioni che vengono normalmente effettuate  in un comune dall’ufficio toponomastica e che comportano anagraficamente una variazione dell’indirizzo del cittadino senza che questo abbia avuto un effettivo cambio di abitazione. Nello storico degli indirizzi, in questi casi, deve risultare che la variazione è dovuta ad una ristrutturazione di dati toponomastici da parte del comune e non per un effettivo spostamento del cittadino. In ANPR attualmente si possono comunicare queste variazioni solo come cambi di abitazione; in questo modo, anche storicamente, risulterà che il cittadino ha cambiato casa.

**Comment by mccalv** [comment]
Al momento stiamo discutendo ed una proposta di Sogei è in fase di valutazione.

**Comment by luca-teamdigitale** [comment]
Duplicate of #231
