### ISSUE TITLE
Cambio cognome cittadino comunitario #1572

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#1660]
Faccio seguito alla precedente segnalazione #1572.
Il suggerimento di richiedere la variazione del cognome all'Agenzia delle Entrate ha avuto esito positivo; infatti stamattina ho ricevuto dalla mail entrate.archivioanagrafico@agenziaentrate.it  la conferma del fatto che hanno proceduto all'attribuzione del nuovo codice fiscale al signor "NUOVO COGNOME" collegando il codice fiscale omocodice precedente. 
Nella mail si legge inoltre "Adesso codesto Comune può procedere con l'ulteriore lavorazione e aggiornare anche la banca dati ANPR".
Tramite l'applicativo Sicraweb provvedo quindi ad aggiornare il cognome ma il messaggio di errore è il seguente
TESTO DEL MESSAGGIO: Operazione ID ANPR = 137491374 , ID Locale = JD92587 
Persone Coinvolte : VECCHIO COGNOME G. 05/11/1994, NUOVO COGNOME G. 05/11/1994 
Il servizio ANPR ha risposto con errori 
Codice	Testo
EAM12	Soggetto non individuato in AT - Codice fiscale NON variato
EN527	Informazioni sull'operazione da fornire in caso di assistenza : data 2019-10-10 15:40:42 , idOperazioneANPR 137491374

**Comment by frmariani** [comment]
la richiesta richiede scambi di informazioni e di dettaglio; il Comune è stato contattato e la problematica è stata risolta.
