### ISSUE TITLE
iscrizione AIRE in ANPR: modifica motivo di iscrizione

### ISSUE THREAD

**Issue by AriTi29** [italia/anpr#1661]
Ho trascritto l'atto di cittadinanza e poi l'atto di nascita di un Aire.
Il motivo di iscrizione Aire è per acquisto cittadinanza, ma per errore mi si è iscritto per nascita.
C'è modo di modificare il motivo di iscrizione da per "nascita" in "per acquisto cittadinanza"?
Ho provato da webapp come Modifica dati iscrizione Aire, ma mi riporta poi in descrizione del soggetto:
"Iscritta in ANPR per ALTRI MOTIVI : errore nel motivo di iscrizione." 

Grazie per la preziosa collaborazione

**Comment by ncapozzi** [comment]
Buongiorno,
potrebbe indicare l'idoperazione ANPR per favore?

**Comment by AriTi29** [comment]
136989460

**Comment by ncapozzi** [comment]
Buonasera,
nella mutazione dati AIRE non è previsto il motivo "Acquisizione della cittadinanza italiana, se residente all'estero" perché si suppone che trattandosi già di un cittadino AIRE la cittadinanza Italiana già la possegga al momento dell'iscrizione. Può tuttavia utilizzare il motivo di iscrizione Altro indicando nel campo note "Acquisizione della cittadinanza italiana, se residente all'estero". 

N. Capozzi
