### ISSUE TITLE
Cambio parentela Storico

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1664]
Buongiorno,
Ambiente di Produzione
idOperazioneANPR 137994048

Il Comune in questione si è accorto oggi di non aver cambiato le parentele di una famiglia in seguito al matrimonio di due dei componenti della stessa avvenuto il 27/08/2016.
Ha quindi provato dal portale di ANPR a correggere la composizione familiare, impostando la parentela "Moglie" sul soggetto con ID 27683241.
La procedura restituisce il seguente errore: 
"La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto. (Codice: EN447)" .
Da ulteriori verifiche risulta che tutti e tre i componenti della famiglia in questione siano entrati nella famiglia in date precedenti a quella impostata come data decorrenza del cambio di parentela.
Come possiamo procedere con questa correzione?
Saluti

**Comment by frmariani** [comment]
Buongiorno, 
abbiamo riscontrato un comportamento anomalo per il controllo EN447 che abbiamo rimosso;
per favore riprovate l'operazione.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa
