### ISSUE TITLE
ambiente di test nuove credenziali 15 ottobre

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1666]
in ambiente di test abbiamo riportato i dati dei comuni di Codroipo e Maniago non ancora subentrati.
per questi comuni quale è la modalità di richiesta delle nuove credenziali ?

Inoltre è possibile portare in ambiente di test i dati di 2 comuni già subentrati in produzione? e in questo caso è piu' semplice il reperimento delle nuove credenziali?
grazie

**Comment by rvinzani** [comment]
E' possibile riportare in ambiente di test dati relativi a comuni subentrati o meno poichè si tratta di un ambiente dove effettuare i test di integrazione del gestionale con i servizi di ANPR. In ogni caso è necessario definire delle utenze nominali. 
Tali utenze devono essere censite dall'ALS dell'ambiente di produzione, accedendo però alla console di test comuni.
L'utenza sarà costituita da un CF reale e da una password che arriverà all'indirizzo indicato nella fase di censimento dell'utenza.
Chiudo la issue. Nel caso fossero necessarie ulteriori informazioni si prega di aprirne una nuova che faccia riferimento a questa stessa
