### ISSUE TITLE
Conflitto installazione SC con CRS regione Lombardia

### ISSUE THREAD

**Issue by eleb2018** [italia/anpr#1668]
Buon giorno,
sempre più spesso riscontriamo problemi nell'installazione della Sc su Client dove è già installato Driver Crs Regione Lombardia (sembra che ci sia un conflitto tra i 2 driver)
Seguendo istruzioni della Guida Rapida per i Comuni, l'installazione della SC viene portata a termine senza alcun problema evidente
In fase di accesso alla WebApp di Sogei, viene riconosciuto il cert di postazione, viene riconosciuta la Sc, ma la videata che viene proposta a video per inerire il pin è quella relativa alla CRS - inserito il pin corretto, l'accesso non viene effettuato visualizzando il msg: 
"Impossibile raggiungere il sito
La pagina web all’indirizzo https://dp2.anpr.interno.it/com potrebbe essere temporaneamente non disponibile oppure è stata permanentemente spostata a un nuovo indirizzo web
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED   "

avete qualche suggerimento? grazie - Elena Bertani -

**Comment by Leonforte** [comment]
Buongiorno,
stiamo effettuando dei test per verificare il tipo di conflitto e come risolverlo.
Può essere un prima indicazione il fatto che con la CIE abbiamo risolto utilizzando due browser diversi senza installare i driver dei lettori che distribuiamo noi. Appena possibile Le faremo avere qualche informazine aggiuntiva, saluti

**Comment by francydiga** [comment]
Buongiorno, ho anch'io lo stesso problema.
Posso ricevere supporto dando ulteriori informazioni mancanti nell'apertura della issue precedente?
