### ISSUE TITLE
Data anagrafica di decorrenza e registrazione

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#167]
Analizzare la gestione della data anagrafica di decorrenza e registrazione (serve per lo storico e per l'Istat) - per ora ne è gestita sola una;

**Comment by mccalv** [comment]
Si gestiscono entrambe le date. Sono in corso modifiche per spostare il controllo sulla cronologia delle operazioni (al momento sulla scheda individuale a meno di carta di identità altri dati e residenza) sul tipo di mutazione: non si accetta una mutazione dello stesso tipo con data antecedente ad una già inviata. 
In allegato una proposta fatta da Sogei per l'utilizzo delle data in ANPR
[utilizzo delle date in ANPR rev 16 maggio.pdf](https://github.com/italia/anpr/files/1004756/utilizzo.delle.date.in.ANPR.rev.16.maggio.pdf)

**Comment by CarlaMusian** [comment]
In merito a questo problema segnalo che in tutte le circolari Istat la data decorrenza (giuridica) ha significato di data evento (vedi ad esempio Circ. n. 39 del 2015 3.2 Rilevazioni Istat Posas e Istat Strasa secondo capoverso).
Nel documento citato sopra sull'utilizzo delle date in ANPR, si intende invece che la data di decorrenza coincide con quella della dichiarazione anagrafica o registrazione in ANPR.
Ora e' opportuno chiarire questo aspetto,  che, al di la' delle problematiche statistiche ,  potrebbe portare a differenze sul trattamento delle date dei web service da parte delle varie software house e di conseguenza sulla sequenza complessiva degli eventi in ANPR e sulla certificazione storica di ANPR.

Riporto anche quanto presente in:
"Rilevazioni demografiche e sanitarie - Istruzioni per la compilazione dei modelli statistici" Ed.2011
pagina 9 sulla popolazione anagrafica:
"È opportuno ricordare che la popolazione viene calcolata sulla base dei flussi riportati secondo la data di
definizione della pratica di iscrizione o cancellazione anagrafica e non secondo la data di evento o di decorrenza giuridica dell’iscrizione /cancellazione. Pertanto, nel calcolo delle schede anagrafiche deve essere seguito analogo criterio, altrimenti le divergenze di numero possono essere attribuite a sfasamenti temporali tra data di definizione e data di decorrenza".

Carla Musian - Insiel Mercato

**Comment by gcarbonin** [comment]
La data di definizione della pratica e' un'altra cosa ancora. Viene acquisita così come è ed utilizzata quando si comunicano i dati all'ISTAT ma non ha nessun riflesso sulla data di decorrenza: nei trasferimenti di residenza, la data di decorrenza è la data della dichiarazione mentre la data di definizione pratica è quella di chiusura dell'accertamento amministrativo.

**Comment by CarlaMusian** [comment]
E nelle comunicazioni provenienti dallo Stato Civile?

**Comment by gcarbonin** [comment]
Data nella quale la comunicazione perviene all'ufficio anagrafe. Diverso poi è la data "a partire dalla quale l'informazione è efficace": trasmetto nel 2017  un matrimonio avvenuto nel 2005; la data di registrazione sarà 2017 ma la persona nel certificato sarà coniugata dal 2005.
