### ISSUE TITLE
[A006] PROD: anomalia axis2...

### ISSUE THREAD

**Issue by StefanoGuidetti** [italia/anpr#1670]
Buongiorno
con una mutazione AIRE via WS A006 riceviamo il seguente errore "axis2ns22731:Server"

dati chiamata
```
      <idOperazioneComune>99852</idOperazioneComune>
      <codMittente>043043</codMittente>
      <codDestinatario>ANPR02</codDestinatario>
      <operazioneRichiesta>A006</operazioneRichiesta>
      <dataOraRichiesta>2019-10-14T13:58:12.286+02:00</dataOraRichiesta>
      <tipoInvio>PROD</tipoInvio>
```

risposta ricevuta
```
      <faultcode>axis2ns22731:Server</faultcode>
      <faultstring>Internal Error</faultstring>
      <detail/>
```

Resto in attesa
Grazie
Stefano by PAL

**Comment by mttfranci** [comment]
Il problema è capitato solo su questa operazione, in modo sporadico, oppure generalizzato?
Abbiamo aggiunto delle trace, potreste riprovare?
Grazie in anticipo per la collaborazione.
Saluti

Assistenza ANPR

**Comment by StefanoGuidetti** [comment]
Un problema simile, in realtà, è successo anche il giorno precedente
sempre con lo stesso comune e tipo operazione.
L'errore è apparso durante l'iscrizione di 2 soggetti all'estero della stessa famiglia
e riceviamo l'errore sempre con il secondo soggetto.

ecco i dati errati di una chiamata precedente
che poi è stata eseguita in un secondo momento è andata a buon fine

```
      <codMittente>043043</codMittente>
      <idOperazioneComune>99852</idOperazioneComune>
      <codDestinatario>ANPR02</codDestinatario>
      <operazioneRichiesta>A006</operazioneRichiesta>
      <dataOraRichiesta>2019-10-14T13:58:12.286+02:00</dataOraRichiesta>
      <tipoInvio>PROD</tipoInvio>
```

risposta
```
      <faultcode>axis2ns22731:Server</faultcode>
      <faultstring>Internal Error</faultstring>
      <detail/>
```

Infine un altro errore similare
l'avevo segnalato con questa issue
[https://github.com/italia/anpr/issues/1665](url)

**Comment by mttfranci** [comment]
Grazie delle informazioni, ma avete provato e vi è capitato ancora dopo la nostra prima risposta? (15 ottobre alle 18 circa?)
Come detto abbiamo effettuato qualche piccolo tuning.

**Comment by mttfranci** [comment]
Non ci risultano altri casi dopo l'aggiornamento, in assenza di riscontro chiudiamo la issue.
Saluti

Assistenza ANPR

**Comment by StefanoGuidetti** [comment]
No, non ho altre segnalazioni in merito
e purtroppo, nemmeno informazioni sulle tempistiche.
Stefano
