### ISSUE TITLE
Non devono essere trasmesse con il subentro le schede archiviate.

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1671]
Buongiorno
un dubbio dell'ultimo minuto ... il comune di caponago deve subentrare oggi ... 

Nella documentazione tecnica è presente la frase :

"Non devono essere trasmesse con il subentro le schede archiviate." significa che non devono essere inviate le schede anagrafiche relative a Deceduti, Emigrati e Irreperibili Permanenti ?
Se "SI", nel caso si dovesse emettere un certificato di Emigrazione o di Irreperibilità come ci si deve comportare ?

In attesa di cortese riscontro.

**Comment by ncapozzi** [comment]
Buongiorno,

Come indicato nel documento SPECIFICHE DI INTERFACCIA DEI SERVIZI DI ANPR PER I COMUNI MI-14-AN-01 a PAG. 173 i dati da trasmettere con il subentro riguardano:
 le schede individuali, famiglia e convivenza attive alla data del subentro;
 le schede individuali, famiglia e convivenza archiviate alla data del subentro, ma per le quali il comune ha aperto e non completato alla stessa data un procedimento o un’istruttoria.


Pertanto tutte le altre schede archiviate per qualunque motivo non devono essere trasmesse. Di conseguenza le certificazioni relative a dati storici antecedenti al subentro sono demandate al gestionale del comune.

N. Capozzi
