### ISSUE TITLE
1002 errore EN185 + EN190

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1672]
Buongiorno per il comune di CASTENEDOLO in ambiente produzione
per un cittadino cancellato da anpr si invia una iscrizione 1002 
indicando ID ANPR 41723329 ma la comunicazione torna con errore EN185
provando a rimandare la comunicazione stavolta senza indicazione dell'ID ANRP
torna con errore EN190, 

gli id operazione sono
idOperazioneANPR 139410332 per errore EN185
idOperazioneANPR 139410440 per errore EN190

è la seconda volta che ci capita in pochi giorni non capisco il problema.

Grazie mille
Riccardo

**Comment by frmariani** [comment]
In caso di re-iscrizione, il sistema confronta le generalità inserite con quelle precedentemente acquisite per l'identificativo ANPR indicato: i dati anagrafici dovranno essere necessariamente congruenti tra loro;
nel vostro caso, il luogo di nascita differisce dalla precedente iscrizione;

Nel caso fosse necessaria ulteriore assistenza sul caso specifico, invii un contatto diretto dove posso raggiungerla o chiami il numero verde 800863116

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.
