### ISSUE TITLE
AIRE Iscrizione oggetto risposta comune IdFamigliaConvivenzaComune non presente

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#1673]
Buongiorno,
Avendo inviato comunicazione di iscrizione AIRE del tipo A001 e A002, con costituzione di una nuova famiglia, pur ricevendo l'esito positivo delle operazioni, di tipo Risposta_Comune, nell'elemento FamigliaConvivenza non risulta presente l'elemento IdFamigliaConvivenzaComune , necessario per effettuare un immediata e corretta associazione tra la scheda famiglia comune con IdFamigliaConvivenzaAnpr.

Restiamo in attesa di una vostra comunicazione in merito.

**Comment by mttfranci** [comment]
Potete indicarci un ID operazione anpr da verificare?

In generale comunque, come indicato nella Issue #1079 , adesso vengono restituiti solo i dati non trasmessi dal comune nella richiesta. L'ID comunale e' un dato che dovrebbe essere noto al gestionale dato che lo ha trasmesso.

Saluti

Aassistenza ANPR
