### ISSUE TITLE
Certificazione - Frazione NULL

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1675]
Ho prodotto stamattina alcuni certificati di residenza in ambiente di test e in tutti i casi ho riscontrato la presenza della dicitura "Frazione: null" nei dati dell'indirizzo.

Esempio Protocollo ANPR 20246571

Risulta iscritto all’indirizzo:
VIA ROMA - Frazione: null

Provato con parametro "Stampa della frazione nell'indirizzo di residenza" sia acceso che spento.

Filipazzi  - Maggioli

**Comment by mttfranci** [comment]
Salve, dovremmo aver trovato l'anomalia, potreste riprovare?
Grazie in anticipo.

Assistenza ANPR

**Comment by bfilipazzi** [comment]
Confermo, risolto.
Filipazzi - Maggioli
