### ISSUE TITLE
Carta d'identità cartacea per Non Residenti

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1677]
Buongiorno,

vi scrivo in merito all'emissione di carte d'identità per cittadini non residenti, 
Se questa operazione di rilascio per non residenti viene fatta tramite il rilascio di una CIE, i dati vengono poi recepiti e aggiornati nel sistema ANPR.
Se però la carta d'identità che viene rilasciata è cartacea, al momento dell'invio della trasmissione ad ANPR viene restituito il messaggio di errore: OPERAZIONE NON AMMESSA: COMUNE NON COMPETENTE.
In questo modo non vengono aggiornati nella webapp.
l'operazione fatta su ambiente di test ha come idANPR 20237404

Grazie

**Comment by ncapozzi** [comment]
Buonasera,
anche se la carta di identità cartacea è stata emessa da un comune diverso da quello di residenza, solo il comune di residenza può riportare gli estremi del documento sulla scheda ANPR del cittadino.

N. Capozzi
