### ISSUE TITLE
[7002] EN122 La richiesta effettuata non produce alcun risultato

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1679]
Buongiorno effettuando una richiesta 7002, idOperazioneANPR 139789996,
torna l'errore in oggetto ma non ne comprendo il motivo.

OFFANENGO - SUBENTRATO
Grazie mille
Cristian

**Comment by azabatta** [comment]
Buonasera, 
l'elaborazione  è terminata con un  errore, stiamo verificando il motivo.

**Comment by azabatta** [comment]
Buonasera, 
c'è stato un problema durante l'elaborazione della richiesta, è stata schedulata nuovamente ed è terminata correttamente.
