### ISSUE TITLE
Rilascio CIE da parte del consolato

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1680]
Buongiorno,
in data 16/10/2019 è stata rilasciata la circolare con le procedure che i consolati ed i comuni devono seguire per rilasciare CIE a cittadini AIRE.
Nello specifico la circolare parla di una **Notifica ANPR** che arriva al comune di iscrizione AIRE dal consolato nel caso in cui il soggetto richiedente la CIE abbia comunicato uno o più dati anagrafici errati, sulla circolare viene spiegato come visualizzarle questa notifica tramite WEB APP.
È possibile gestire questa notifica anche tramite WEB SERVICE?

Altra domanda, se i dati forniti al consolato dal cittadino AIRE sono esatti e la CIE viene emessa correttamente, come verrà informato il comune di iscrizione AIRE di questo evento?

ringrazio anticipatamente.

**Comment by ncapozzi** [comment]
Buonasera,
la eventuale richiesta di allineamento trasmessa dal Consolato e visibile e gestibile solo tramite apposita funzione presente nella web APP con le modalità descritte nella Circolare.

Attualmente il comune può visualizzare gli estremi della CIE rilasciata dal Consolato solo andando in consultazione sulla scheda del cittadino AIRE come del resto avviene  per la CIE rilasciata per un cittadino APR da un comune diverso da quello di residenza. Stiamo comunque prevedendo un sistema di notifiche al comune per entrambe le casistiche.

N. Capozzi

**Comment by SAlberto** [comment]
Buonasera,
grazie per la risposta.

E' già possibile sapere le tempistiche con cui verranno rilasciate queste nuove notifiche?
Dove pubblicherete le specifiche di questo nuovo sistema di notifiche? Sarà pubblicato su questo portale o sulla documentazione tecnica di ANPR  (https://www.anpr.interno.it/portale/documentazione-tecnica) ? 

Ringrazio anticipatamente.

**Comment by ncapozzi** [comment]
Non è ancora stata stabilita una pianificazione. Normalmente viene data notizia dei nuovi rilasci sia su questo portale che su https://www.anpr.interno.it/portale/documentazione-tecnica

N. Capozzi
