### ISSUE TITLE
Errore iscrizione persona omonima con persona iscritta in anpr e con c.f. non allineato

### ISSUE THREAD

**Issue by MMaurizio** [italia/anpr#1681]
COMUNE DI CALCERANICA AL LAGO
Buongiorno, 
Non riesco lato web application a procedere all'iscrizione anagrafica in convivenza di persona omonima a persona iscritta in anpr  id  69140303 del Comune di Pistoia.

La persona che devo iscrivere proviene da Comune non subentrato in ANPR e ha codice fiscale validato uguale al soggetto id 69140303.  Si chiede se sia possibile attribuire  all'id 69140303 codice fiscale omocode diverso a quello attribuito alla persona che devo iscrivere.
Grazie
M.MARTINELLI

**Comment by rvinzani** [comment]
E' possibile iscrivere in ANPR un soggetto che abbia i dati anagrafici uguali ad un altro soggetto già presente in ANPR solo se si richiede l'attribuzione di un omocodice, senza ovviamente indicare il codice fiscale

**Comment by MMaurizio** [comment]
Per precisione il tentativo di iscrizione anagrafica è avvenuto tramite Web Service per un soggetto con codice fiscale allineato proveniente da comune non subentrato in  ANPR. Errore EN068. L'errore è giustificato come precisato perchè è presente in ANPR persona quasi omonima con due prenomi anziché uno iscritta   in ANPR con codice fiscale non allineato  medesimo a quello in possesso della persona che debbo iscrivere.  Il Comune ove è residente il soggetto non allineato può con la procedura correzione disallineamenti in Web App  attribuire al soggetto id  69140303 un codice fiscale omocodice?  In alternativa lo potete risolvere voi di SOGEI?

**Comment by MMaurizio** [comment]
Il post può essere chiuso perchè risolto dal Comune ove iscritto il soggetto id 69140303
