### ISSUE TITLE
Errore collegamento AE

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#1682]
Buongiorno

questa mattina riceviamo dalla nostra applicazione numerosi alert per "errore non previsto in fase di esecuzione del servizio 'SE1002V1' - Read timeout"  
Abbiamo visto che ci sono problemi anche con il collegamento AE da webapp "Esito AE: Operazione non effettuabile (Codice 97)"
Questa situazione sta causando notevoli disagi agli sportelli: è possibile avere informazioni in merito, soprattutto le previsioni di soluzione del problema, giusto per avere un'idea di come procedere? 

Grazie
Raffaella Tremolada
Sistemi Informativi per Comune di Milano

**Comment by sfmodena** [comment]
Comune di Modena - Produzione

Buongiorno,
stiamo rilevando gli stessi problemi, in particolare sul collegamento con AE.

Sonia Fiorini

**Comment by cvignati** [comment]
Comune di Villa Cortese - Produzione

Buongiorno,
anche noi stesso problema

Claudio Vignati

**Comment by cvignati** [comment]
> 
> 
> Comune di Villa Cortese - Produzione
> 
> Buongiorno,
> anche noi stesso problema
> 
> Claudio Vignati

Ora la mia comunicazione è andata a buon fine. E' un'attribuzione CF per nascita

**Comment by ANPRCDBO** [comment]
Comune d Bologna,
Noi problemi di timed out nelle conferme delle IMMI ed esecuzione del  servizio 5008 
Elena Di Martino
per il Comune di Bologna

**Comment by rvinzani** [comment]
Il problema è stato risolto.
Nel caso fossero necessarie ulteriori verifiche si prega di riaprire una nuova issue che faccia riferimento a questa stessa
