### ISSUE TITLE
Errore aggiornamento dati divorzio

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1683]
Comune di Modena - Ambiente di produzione

Buongiorno,
abbiamo inserito la cessazione di matrimonio con divorzio da tribunale estero per due nostri residenti, una italiana e uno straniero, il quale si è immediatamente risposato; ora 
stiamo tentando di aggiornare lo stato civile e l' atto di divorzio trascritto della cittadina italiana ma otteniamo l'errore:

Operazione richiesta non possibile. Non e' presente alcun matrimonio per il soggetto XXXXX XXXX (19342072) corrispondente ai dati inseriti. (Codice: EN369)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-10-21 09:50:23 , idOperazioneANPR 141207319 (Codice: EN527)

E' dovuto al nuovo matrimonio già inserito per l' ex-coniuge? E se è così, come possiamo aggiornare i dati della cittadina italiana?

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
consultando il soggetto idanpr 19342072, ho verificato che i dati che si tenta di inserire/modificare con l'operazione idanpr 141207319 sono già presenti in ANPR;
se ho capito bene, l'informazione attuale del soggetto idanpr 19342072, corrisponde ad un'informazione pregressa per il soggetto idanpr 19258333 che nel frattempo si è risposato ed ha come dati attuali un nuovo matrimonio;
ANPR presenta la situazione attuale dei soggetti, per una consultazione storica deve inserire la data di riferimento.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.
