### ISSUE TITLE
Problema accesso a https://dp.anpr.interno.it/com

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1685]
Salve stiamo provando da giorni aconnetterci a https://dp.anpr.interno.it/com ma il messaggio dato da tutti i browser è il seguente:

Impossibile connettersi in modo sicuro alla pagina

La causa potrebbe essere che il sito utilizza impostazioni di sicurezza TLS obsolete o non sicure. In tal caso, provare a contattare il proprietario del sito Web.

Abbiamo provato a seguire le guide sui https://github.com/italia/anpr/issues/1186

Ed è tutto così come descritto dalla guida
Abbiamo anche fatto le prove con diversi browser.
Saluti

Saluti

**Comment by Nichelino** [comment]
Risolto. Chiudo

**Comment by legnanosicol** [comment]
Buongiorno, leggo che avete chiuso il problema. 
Posso chiedere come avete risolto? 
Noi abbiamo sempre lo stesso problema pur applicando tutta la procedura passo passo.
Grazie
