### ISSUE TITLE
Errore aggiornamento dati divorzio (segue issue #1683)

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1686]
Comune di modena - Ambiente di produzione

Buongiorno,
faccio riferimento alla precedente issue #1683: il nostro problema non è la consultazione di dati pregressi ma l' aggiornamento dello stato civile (al momento errato) e soprattutto dell' atto di divorzio sull' ex-coniuge italiana (idANPR 19342072) in modo che i dati siano visibili sulla sua posizione attuale.
A parte il caso specifico però, vorremmo capire come comportarci in casi analoghi che si potrebbero presentare quando, a fronte di un divorzio tra un cittadino straniero ed un italiano, si verifica questa situazione:
- il cittadino straniero che deve risposarsi presenta un nulla osta relativo al divorzio decretato da un Tribunale estero e la nostra Anagrafe deve registrarlo per consentire il successivo matrimonio;
- diverso tempo dopo (spesso passano mesi) la sentenza del Tribunale estero viene trascritta dal nostro Stato civile e i dati dell' atto devono essere riversati in anagrafe e in ANPR per il cittadino italiano, che dovrebbe risultare divorziato soltanto dopo questo adempimento. Al momento questo non sembra possibile, almeno visto l' errore restituito.

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
da quello che mi risulta, l'operazione idanpr 141207319, oltre a modificare lo stato civile, tenta di inviare un'informazione già presente in ANPR (ed è per questo che l'operazione fallisce);
lo stato civile del soggetto idanpr 19342072 deve essere coerente con le informazioni presenti in ANPR: nel suo caso, il soggetto risulta già divorziato, quindi, lo stato civile  può essere modificato.

Potrei non aver colto l'esigenza, nel caso mi scriva il suo numero e la richiamerò:
frmariani@sogei.it
