### ISSUE TITLE
Gestione codice fiscale provvisorio

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1687]
Buongiorno,

nel documento "Specifiche di interfaccia dei servizi di ANPR per i comuni – documento generale (aggiornato al 24 giugno 2019)" a pag.65, nella sezione *11. Struttura del Corpo dei messaggi per i servizi di registrazione* ho letto la seguente specifica:
"L’Agenzia delle Entrate ,nel caso in cui rilevi una omocodia, assegna al neonato/a un codice fiscale numerico (c.d. codice fiscale provvisorio), mentre il codice fiscale definitivo perverrà successivamente dall’Agenzia e sarà notificato al comune tramite apposito servizio."

Non è chiaro quale sia il servizio di cui si sta parlando: sarebbe possibile avere qualche informazione in merito?
Grazie

Marco Sala
Pa Digitale Spa

**Comment by rvinzani** [comment]
Il servizio non è ancora disponibile. Per il momento la comunicazione viene veicolata tramite i canali di assistenza.
