### ISSUE TITLE
Luogo di nascita eccezionale senza indicazione di comune o di stato

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#1688]
Un cliente incontra difficoltà nell'immigrazione di una persona da comune subentrato perché sia il comune italiano che lo stato estero di nascita sono nulli, l'unico dato del luogo di nascita presente è una stringa contenuta nel luogo eccezionale.
La persona è così identificata: idSchedaSoggettoANPR 70672503.
In AE ha un'indicazione appropriata del luogo di nascita, che nella fattispecie è INDIA.
L'ufficio di anagrafe del comune di provenienza si rifiuta di intervenire.
Dobbiamo adeguare il gestionale a situazioni come questa?
Grazie.
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Buongiorno,
che tipo di difficoltà riscontrano? Stanno eseguendo una mutazione di residenza che va in errore? In caso affermativo si può avere l'id dell'operazione?

Faccio comunque presente che mancando lo stato estero di nascita nella scheda ANPR, il codice fiscale non è validato.

N. Capozzi

**Comment by bfilipazzi** [comment]
Il comune di immigrazione dovrebbe registrare la 5001 per acquisire la persona e successivamente una 5008 per integrare il luogo di nascita.
Il gestionale si aspetta uno fra comune italiano o stato estero di nascita, allo stesso modo in cui ANPR pretende in alternativa uno dei due dati. La mutazione non va in errore perché il gestionale in mancanza del dato non arriva alla richiesta di mutazione. 
Dovrei rimuovere dal gestionale il blocco che impedisce la 5001 in mancanza del luogo di  nascita, mi chiedo se la richiesta andrebbe a buon fine o in errore.
Grazie
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Il WS 5001 non effettua il controllo sul luogo di nascita, quindi se lo togliete dal gestionale dovreste riuscire ad effettuare la mutazione di residenza.

Attendo riscontro.
N. Capozzi

**Comment by ncapozzi** [comment]
Buonasera,
non avendo più ricevuto riscontri si chiude la issue.

N. Capozzi
