### ISSUE TITLE
Nuove modalità accesso ambiente test RIF #1674 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1690]
Comune CASERTA -061022
ha provato con il suo codice fiscale e la password ricevuta insieme alla SC (prima parte e seconda via mail)
il certificato proposto dal browser è 061022-CO-0000
non funziona (credenziali errate o certificato non valido)

_Originally posted by @rinonasti in https://github.com/italia/anpr/issues/1674#issuecomment-544877226_

**Comment by Leonforte** [comment]
Il certificato 061022-CO-0000 è il certificato utilizzato per l'ambeinte di test.
L'accesso agli ambienti di esercizio e presubentro deve essere fatto con smart card e non con utenza (CF) e password. Per l'amebiente di esercizio in generale suggeriamo di seguire le istruzioni in allegato.

[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.docx](https://github.com/italia/anpr/files/3761827/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.docx)

**Comment by Leonforte** [comment]
Invece per l'amebite di test va bene il certificato che state utilizzando ma l'accesso può essere effettuato esclusivamente dall'ALS di esercizio con le credenziali di esercizio, con quale utente tentate di accedere ?

**Comment by rinonasti** [comment]
IL CODICE FISCALE DI ALS (posso scriverlo?)

**Comment by Leonforte** [comment]
Potete riprovare adesso che tracciamo cosa succede ?

**Comment by rinonasti** [comment]
OK GRAZIE LO FACCIO FARE DOMATTINA - OGGI ALS ASSENTE - 
POI VI INVIO ORA DELL'EVENTO

**Comment by rinonasti** [comment]
buongiorno
a riprovato alle 12.10 accesso ok 
ma quando accede alla sezione sicurezza, per iscrivere utente software house (io), (https://webtest.anpr.interno.it/ANPRConsole/welcome.xhtml) presenta una pagina bianca.

**Comment by Leonforte** [comment]
Buongiorno, c'è stato un breve disservizio, potete riprovare ? grazie

**Comment by rinonasti** [comment]
OK funziona 
Grazie

**Comment by Leonforte** [comment]
perfetto, saluti
