### ISSUE TITLE
Diritti di segreteria per emissione Certificati

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1691]
Il Comune di Caponago, da poco subentrato con modalita' WA, chiede se esiste una notifica che è possibile ottere da ANPR contenente l'elenco dei diritti incassati dall'Ente a fronte dell'emissione dei certificati con la WA stessa.
Si resta in attesa di gentile riscontro.

**Comment by rvinzani** [comment]
E' possibile interrogare le notifiche di tipo NRIS contenenti i servizi di certificazione invocati contenenti le informazioni sui diritti di segreteria. Inoltre nella WA, alla voce utilità e notifiche è possibile richiedere un riepilogo contabile per C.I. e certificati, per range temporale

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siao necessarie maggiori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
