### ISSUE TITLE
REQUISITI TECNICI PER UTILIZZO WS ANPR PER AGGIORNAMENTO DATI DA ANAGRAFE LOCALE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1692]
E' possibile ricevere la documentazione tecnica riepilogativa di tutto ciò che occorre ad un ente che intende utilizzare il proprio sistema gestionale integrato con i WS di ANPR ?

Grazie

**Comment by rvinzani** [comment]
Potete trovare tutta la documentazone sul sito www.anpr.interno.it
