### ISSUE TITLE
LEGGIUNO-SANGIANO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1693]
Buongiorno,
si presenta un problema relativo al soggetto ID ANPR 28080433, nata nel 1930 nel comune di LEGGIUNO-SANGIANO (catastale E511). In Agenzia Entrate risulta solo il comune di LEGGIUNO (E510) e pertanto sia la mutazione generalità sia la risoluzione disallineamenti restituisce errore AEE96.
La signora richiede CIE che non si riesce a emettere per disallineamento.
Come possiamo gestirla?
Anna Maria AIMONE
UPI - TORINO

**Comment by rvinzani** [comment]
Le tabelle ANPR non riportavano per il comune di Leggiuno-Sangiano il corretto codice catastale E511. Tale codifica è stata sistemata ed adesso è possibile allineare la posizione. 
Chiudo la issue. Nel caso sia necessario ulteriore supporto si prega di aprire una nuova issue che faccia riferimento a questa stessa.
