### ISSUE TITLE
[5008] Rettifica dati coniuge - Errore EN272

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1695]
Buongiorno,
Ambiente di produzione -  data 2019-10-23 17:55:59 - idOperazioneANPR 142668009

In fase di iscrizione l'utente ha scaricato tramite la chiamata 3002 (A) i dati presenti in ANPR. Controllandoli ha notato che il coniuge sull'evento di matrimonio aveva
- codFiscale
- cognome e nome
- sesso
- luogo di nascita

e NON aveva
- dataNascita
- idSchedaSoggettoANPR

quindi l'operatore ha effettuato la ricerca 3002 (B) per il coniuge e ha selezionato l'anagrafica corretta.

Inviando la 5008 noi mandiamo:
- codFiscale *
- cognome e nome *
- sesso *
- dataNascita **
- idSchedaSoggettoANPR **

\* dato corrispondente a quello scaricato con la 3002(A)
** dato scaricato con la 3002(B)

ANPR ha restituito l'errore 
```
<codiceErroreAnomalia>EN272</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Alla data 30-05-2003 il soggetto ... risulta gia' coniugato o unito civilmente con un altro soggetto</testoErroreAnomalia>
```

Sembra che il sistema non riesca a riconoscere il coniuge pur avendo sia il codice fiscale che l'idSchedaSoggettoANPR, l'unico dato mancante è il luogo di nascita che non ci sembra fondamentale per identificare un soggetto.

Potete cortesemente verificare?

**Comment by asqueglia** [comment]
Buongiorno, effettuando le consultazioni per i due soggetti coinvolti, la situazione è attualmente corretta. I due coniugi sono stati correttamente collegati, con l'operazione 142764602 effettuata ieri 24-10-2019 alle 8:53 sul soggetto che aveva una situazione da subentro coerente. 
Il motivo per cui l'operazione da voi indicata non è andata a buon fine, è che è stata effettuata sull'altro coniuge che da subentro è stato inviato con un matrimonio senza data e senza dati del coniuge creando una situazione incongruente su ANPR. 
Sebbene adesso la situazione sia coerente come potete constatare dalle consultazioni, provvediamo comunque ad eliminare il dato errato e incongruente trasmesso da subentro che, subito a valle del subentro,  avreste dovuto eliminare con la funzionalità di revoca.

**Comment by asqueglia** [comment]
buongiorno comunichiamo che il dato errato inviato da subentro è stato sanato da centro.
Chiudo la issue. Nel caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
