### ISSUE TITLE
[7002] Download File - Errore EN122

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1696]
ambiente di PRODUZIONE - comune di FIORANO MODENESE (036013)

abbiamo tentato la richiesta di elenchi anagrafici (ws 4001), a cui sono stati assegnati i seguenti idANPR:
143326061
143334571
143350656

alla richiesta di download dei file (ws 7002), la risposta è sempre
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
  </errore>
</listaErrori>
```

potete verificare?
grazie.
Alessandro Monopoli ADS

**Comment by azangari** [comment]
Buongiorno, 
ci potrebbe fornire l'IDANPR del 7002?

**Comment by azangari** [comment]
Abbiamo verificato che le richieste 7002 sono pervenute prima dell'effettiva elaborazione della richiesta.
Potete riprovare adesso?
Grazie

**Comment by AMonopoliADS** [comment]
adesso la risposta è consistente.
faccio notare che quando la richiesta girava su servizio 3005, la richiesta di download "prematura" veniva segnalata con questo messaggio:
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN099</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La risposta all'elaborazione richiesta non e' ancora disponibile</testoErroreAnomalia>
  </errore>
</listaErrori>
```
oggi, l'utilizzo dell'errore EN122 mi sembra fuorviante.

altra cosa, con una response contenente questo tag:
`<formato>.xml</formato>`
mi sarei aspettato di scaricare un file .xml
invece la response contiene un file compresso.
ma al momento non abbiamo approfondito molto il servizio, x cui potrebbe anche essere normale così...

Alessandro Monopoli ADS
