### ISSUE TITLE
ERRORE ACCESSO ALL'AMBIENTE DI PRE-SUBENTRO E PRODUZIONE

### ISSUE THREAD

**Issue by buggerru** [italia/anpr#1697]
Buongiorno, ho problemi di accesso all'ambiente di produzione  e pre-subentro ANPR. Quando inserisco l'indirizzo https://dp.anpr.interno.it/com, mi chiede il PIN della smart card (inserisco quella del Sindaco), successivamente mi chiede il certificato da usare e seleziono il certificato 111006-PC-0001. Successivamente mi compare l'errore "impossibile visualizzare la pagina" e nello specifico "Codice di errore: SSL_ERROR_DECRYPT_ERROR_ALERT "

SO: Windows 10
Browser usati: internet explorer, chrome, firefox.

**Non sono mai riuscito ad accedere all'ambiente di produzione.** Non riesco ad accedere nemmeno a https://dppre.anpr.interno.it/com

Dopo insistenti solleciti ancora non ho l'accesso all'ambiente di produzione e pertanto non mi è consentito effettuare il subentro.

Vi chiedo di provvedere con urgenza

Comune di Buggerru

**Comment by buggerru** [comment]
Vi chiederei anche di permettermi di accedere alla modalità TEST con username (cf e psw del Sindaco) per avere abilitata la sezione "Sicurezza"

**Comment by Leonforte** [comment]
Che lettori di SC sta usando ?

**Comment by buggerru** [comment]
minilector bit4id (forniti dal ministero).

ps: può controllare l'utenza in ambiente test per accedere con user e psw? forse devo settare da li la figura di ALS per accedere in ambiente di produzione/pre-subentro

**Comment by buggerru** [comment]
s/n del lettore: 38U-0081491
p/n del lettore: B4ID-110004514

**Comment by Leonforte** [comment]
I lettori sono ok, le suggerisco di effettuare delle verifiche seguendo le istruzioni in allegato.
[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/3771636/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)
Per quanto riguarda l'accesso all'ambiente di test occorre nominare prima l'ALS di produzione che sarà automaticamente abilitato all'ambiente di test e che potra poi censire nello stesso ambiente anche altri utenti.

**Comment by buggerru** [comment]
Tutta la configurazione è stata fatta.

Come nominare l'ALS a questo punto? Perchè il censimento delle postazioni sull'area privata dei servizi demografici è stato già fatto e non posso farlo in nessun modo.

**Comment by Leonforte** [comment]
Nelle more della risoluzione del problema lo possiamo fare noi se mi indica quale utente dei due presenti

**Comment by buggerru** [comment]
CPPLRA79M42E281I (è il cf del Sindaco)

Vi ringrazio.

**Comment by buggerru** [comment]
Per ulteriore completezza chiedo che l'utente sopra indicato sia abilitato a tutte le funzioni in ambiente di produzione, in attesa di assegnare nuove risorse per l'ufficio demografico.

Grazie

**Comment by Leonforte** [comment]
Abbiamo eseguito l'aggiornamento, potete verficare ?

**Comment by buggerru** [comment]
Confermo di essere riuscito ad entrare con username e psw del sindaco.

Non riesco però ad entrare negli ambienti di produzione e pre-subentro usando il certificato 111006-PC-001

**Comment by buggerru** [comment]
Nonostante sia riuscito ad entrare in modalità TEST-SVILUPPO con username e password, ho ancora problemi ad entrare in ambiente PRE-SUBENTRO e SUBENTRO attraverso l'autenticazione con smart card (del Sindaco).

Allego l'errore che fornisce sia chrome che firefox.

PS: stamattina ho ricevuto nuovamente il certificato di postazione (penso sia lo stesso dato che ha la stessa password)

![problema](https://user-images.githubusercontent.com/56994886/67928722-07839c80-fbbc-11e9-830e-dae424a2eb1e.PNG)

**Comment by buggerru** [comment]
![problema2](https://user-images.githubusercontent.com/56994886/67929467-b674a800-fbbd-11e9-8f96-4485f3388ca8.png)

**Comment by Leonforte** [comment]
premesso che il link corretto è https://dp.anpr.interno.it/com (che poi reindirizza su dp2) provi ad accedere su https://dp.anpr.interno.it/combas per verificare se il certificato sia ok, Se appare la pagina di login è ok

**Comment by buggerru** [comment]
A quanto mi dice lei parrebbe il certificato il problema. In allegato l'errore
![problema3](https://user-images.githubusercontent.com/56994886/67937989-e6787700-fbce-11e9-96cf-a51143f6df87.png)

**Comment by Leonforte** [comment]
Abbiamo inviato il certificato 2 all'indirizzo : DEMOGRAFICI@COMUNE.BUGGERRU.CI.IT

**Comment by buggerru** [comment]
vi ringrazio per l'assistenza. Ora sono riuscito ad entrare nell'ambiente di subentro (produzione). 

Potete chiudere l'issue! 

Grazie e buon lavoro.
