### ISSUE TITLE
Emissione CIE di soggetto minorenne con dati incompleti dei genitori

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1698]
Buongiorno. Non sono sicuro che sia di vostra competenza, ma immagino che sia coinvolta anche ANPR quindi lo segnalo.
Al Comune di Savona hanno cercato di rilasciare una CIE a un minorenne che sul dato del cognome padre, non aveva nulla.

Nel processo di emissione CIeonline hanno ricevuto questo errore:
[personalData.parentsOrLegalGuardian[0].lastname cannot be null.]

Siccome i dati dei genitori non erano previsti nel vecchio tracciato SAD, presumiamo che la CIE abbia reperito i dati da ANPR.

L'errore è poco comprensibile per l'operatore.

**Comment by rvinzani** [comment]
Buongiorno, ha ragione, la segnalazione non proviene da ANPR anche se i dati provengono da ANPR.
I dati dei genitori non sono sempre presenti

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
