### ISSUE TITLE
EC007: Comune/provincia di nascita inesistente alla data di nascita

### ISSUE THREAD

**Issue by marcello65** [italia/anpr#1699]
Qual'è l'esatta procedura per risolvere questo tipo di anomalia? Il Comune contattato (Albano Laziale che ha fissato il subentro in data 18.11 p.v.) chiede qual'è l'esatta procedura da adottare per gestire questa anomalia.   
Grazie per chi vorrà rispondermi. 

Marcello

**Comment by rvinzani** [comment]
Le indicazioni del Ministero sono che il luogo di nascita da indicare, indipendentemente dalla validità sulla tabella ANPR, è quello presente sull'atto di nascita. Questo è valido ancora di più se il cittadino possiede già un codice fiscale validato. Nel caso in cui la denominazione sull'atto di nascita sia differente e sia necessario un aggiornamento è necessario che tale aggiornamento avvenga alla presenza del cittadino interessato.
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
