### ISSUE TITLE
[PRE-SUBENTRO]  Certificazione

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#170]
Buongiorno,
il subentro APR/AIRE in ambiente di test e pre-subentro è avvenuto con successo.
Però se in ambiente di pre-subentro provo ad eseguire una qualsiasi certificazione il sistema restituisce l'errore **"La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti (Codice: EN087) "**, mentre in ambiente di test riesco a completare l'operazione senza problemi.
Il motivo dipende dal fatto che in ambiente di pre-subentro il sistema segnala alcune anomalie che potrebbero determinare un errato funzionamento dei servizi ?
Quindi finchè non vengono risolte tutte le anomalie il sistema non consente di completare nessuna operazione di certificazione?
Grazie

Bistagno (AL)
Codice ISTAT: 006017

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Assolutamente no. Ho guardato una richiesta a caso di certificazione: riportava tutti i dati previsti nelle generalità della stessa persona, compreso l'identificativo ANPR che nei due ambienti è diverso. Le basi dati infatti sono completamente distinte, anche in considerazione del diverso "uso" che dovrebbero avere i due ambienti. Il sistema sulla base di quanto indicato nella richiesta cerca per identificativo più gli altri parametri e confronta quanto ottenuto con quello che è indicato nella richiesta, dando priorità al codice fiscale.  Nel caso specifico, la ricerca è avvenuta per CF + nome + cognome + comune di nascita, che viene considerato come parametro aggiuntivo in quanto non necessario. Il risultato che si ottiene nei due ambienti è una persona con ID ANPR diversi. I test effettuati in un ambiente non devono essere ripetuti nell'altro ambiente con gli stessi parametri.

**Comment by Eduardo1977** [comment]
La ringrazio, anzitutto, per la risposta ma credo di non aver capito o di aver esposto male il problema.
In ambiente di PRESUBENTRO ho provato a emettere la certificazione per alcuni cittadini senza riuscirci.  
Vado in "HOME - CERTIFICAZIONE- EMISSIONE", cerco il cittadino per codice fiscale e il sistema trova e mi propone la scheda individuale che seleziono per procedere. Fin qui tutto bene e accedo alla pagina da cui scegliere il tipo di certificato. Una volta selezionato il certificato (ad es. 'stato di famiglia' ) procedo con "SALVA e CHIUDI", ma il sistema mi blocca e visualizza l'errore:
"La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti (Codice: EN087)".
Vorrei capire cosa dovrei fare per completare l'operazione con successo.

**Comment by gcarbonin** [comment]
Ho verificato puntualmente i dati e c'era un problema di caricamento del comune di nascita. se riprova ora funziona.

**Comment by Eduardo1977** [comment]
Si, adesso non ho più problemi. Grazie
