### ISSUE TITLE
Mancata trasmissione di cittadino residente col subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1703]
Salve,
vi segnaliamo il seguente caso verificatosi nel comune di San Teodoro (subentrato). Il suddetto comune prima del subentro aveva in archivio un cittadino duplicato e per errore ha eliminato il record con stato "residente"; successivamente il comune è subentrato e tale individuo non è stato pertanto trasmesso in ANPR. Il comune si è poi accorto dell'errore e trovandosi nella condizione di dover emettere dei certificati, ha forzato nell'archivio locale la modifica dello stato dell'individuo da "non residente" a "residente" provocando così un disallineamento con ANPR. L'individuo era stato iscritto nell'anagrafe comunale con una pratica di immigrazione nel 2004, quindi l'unico modo per provvedere alla sua iscrizione in ANPR ci è sembrato quello di utilizzare il ws 1002 - iscrizione per altri motivi indicando _idMotivoIscrizione_ = 9 e nel campo _note_ "Iscrizione per mancata trasmissione da subentro". Abbiamo provato quindi la trasmissione indicando la data effettiva di inizio residenza (28/06/2004) ma il problema è che il comune di San Teodoro in questo intervallo ha cambiato il codice Istat, per cui se inseriamo nel blocco _Residenza_ il codice Istat attuale 90092 otteniamo l'errore "_comune inesistente o non valido alla data di decorrenza residenza_" (id operazione comune 0900922019102889), mentre se inseriamo il codice Istat 091076, valido alla data di decorrenza residenza, otteniamo l'errore "_il comune di residenza deve coincidere col comune di competenza_" (id operazione comune 09009220191028141) in quanto in testata nel codice mittente inseriamo sempre il codice Istat attuale 90092.
Come dobbiamo procedere in questo caso per iscrivere il cittadino in ANPR?
Le operazioni sono state eseguite in ambiente di produzione in data 28/10/2019.
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by azabatta** [comment]
Buonasera, 
la problematica è già stata risolta per le mutazioni: abbiamo esteso lo stesso meccanismo alle iscrizioni. La richiesta corretta è quella con il comune attualizzato (090092). E'possibile riprovare, si resta in attesa di un cortese riscontro.

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo appena riprovato l'operazione con il cliente, inserendo nel blocco _Residenza_ il comune attualizzato (codice istat 090092) come da voi indicato, ma otteniamo ancora l'errore "comune inesistente o non valido alla data di decorrenza residenza".
L'Id operazione comune è 09009220191030121.
In attesa di riscontro,
cordiali saluti.

**Comment by azabatta** [comment]
La richiesta è corretta, abbiamo avuto noi un problema nell'estensione della modifica.
E' possibile riprovare
grazie
