### ISSUE TITLE
[3002] Errore EN214 (continia issue #1702)

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1704]
Continuo il discorso aperto con la issue #1702 in quanto non mi convince quanto detto.

L'operazione che noi tentiamo di fare è una ricerca 3002 di una scheda individuale, perché mai se la famiglia fosse chiusa ANPR dovrebbe rispondermi con  "Non e' possibile consultare i dati del soggetto: la famiglia cui appartiene e' ancora in fase di registrazione" ?

Facciamo continuamente ricerche di tipo 3002 su famiglie cancellate (ad esempio nel db di test di Poggio a Caiano il soggetto ID ANPR 24884167, cancellato per migrazione verso non subentrato, apparteneva ad una famiglia monocomponente estinta alla sua migrazione ma il servizio 3002 permette di consultare tranquillamente la sua scheda individuale, vedi operazione ANPR 22566802).

Potete chiarirmi meglio la causa del blocco segnalato nella #1702 ?

Grazie

**Comment by amollicone1982** [comment]
Il blocco è stato eliminato. Si trattava di una famiglia con uno stato dei legami parentela incogruente e per questo c'era il blocco

**Comment by busaster** [comment]
Il problema persiste (vedi id operazione ANPR 148002545)

**Comment by amollicone1982** [comment]
Riprova adesso. Il problema è risolto
