### ISSUE TITLE
[test 4001] Estrazione Elenchi - Errore EN179

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1705]
ambiente di TEST - comune di FAENZA (039010)

stiamo cercando di testare il servizio di richiesta elenchi (ws 4001) e download file (ws 7002)
ma le richieste di elenchi vengono bloccate da questo messaggio:
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN179</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Richiesta non effettuabile: e' presente una richiesta dello stesso tipo non ancora lavorata</testoErroreAnomalia>
  </errore>
</listaErrori>
```
(esempio idOperazioneComune 2019400764)

è possibile capire cosa blocca la richiesta o sbloccare direttamente la situazione per procedere con nuovi test?

grazie.
Alessandro Monopoli ADS

**Comment by gife67** [comment]
Buongiorno,
se viene effettuata una richiesta 4001 ed è in corso di elaborazione non è possibile inoltrarne di nuove finchè quella in corso non risulta elaborata, questa è la causa dell'EN179.
Attualmente non ci risultano richieste in elaborazione quindi se provate ad inoltrarne una nuova richiesta, questa dovrebbe essere accettata.
Se cortesemente potete riprovare e darmi conferma, indicando gli identificativi della richiesta sia quello comunale (idOperazioneComune) che quello restituito da ANPR (idOperazioneANPR)
Grazie

**Comment by AMonopoliADS** [comment]
infatti la cosa strana era l'errore in assenza di precedenti richieste.

confermo comunque che adesso la richiesta è stata accettata
idOperazioneComune 2019400778 
idANPR 22568206

grazie

**Comment by gife67** [comment]
Esaminando le richieste effettuate oggi in TestComuni, per il Comune di Faenza, mi risulta che quella che ha preso la segnalazione era quella con IdOperazioneComune 2019400773 sottomessa alle 11:25, mentre c'era in corso la 2019400772 che è stata elaborata alle 11:32.
Chiudo la Issue ed in caso di ulteriori problemi potete riaprine una nuova collegata a questa.
Grazie per la collaborazione.
