### ISSUE TITLE
[test 7002] Download File - EN122

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1706]
in rifiermento al test di cui alla issue #1705 sono state fatte 3 richieste tutte andate a buon fine.
nel tentativo di eseguire il download del file (ws 7002) tutte le richieste ritornano l'errore EN122
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
  </errore>
</listaErrori>
```

per situazione analoga in ambiente di produzione (rif. issue #1696 ) sembra che il messaggio possa indicare lo stato non ancora elaborato della richiesta.
come capire se in effetti l'elaborazione è ancora in corso, oppure è già terminata ed in effetti "non produce alcun risultato"?

queste le richieste di download che abbiamo eseguito:
idOperazioneComune 2019400820 - idOperazioneANPR 22568404
idOperazioneComune 2019400821 - idOperazioneANPR 22568618
idOperazioneComune 2019400822 - idOperazioneANPR 22568638

grazie.

**Comment by AMonopoliADS** [comment]
da test eseguiti anche questa mattina, mi sono accorto che le richieste effettuate ieri sono partite con un codMittente diverso da quello abilitato in ambiente di test.
è normale che il sistema abbia accettato la richiesta senza segnalare la non-competenza del mittente?

altro punto: con il codMittente corretto sono andate a buon fine sia la richiesta di estrazione che il download, ma sottolineo nuovamente che l'errore EN122 che compare in attesa dell'elaborazione è fuorviante. andrebbe cambiato con altro messaggio che indica lo stato di attesa.

grazie.

**Comment by mttfranci** [comment]
1) Il cod mittente viene usato come filtro sulla richiesta, quindi se si interroga una operazione relativa ad un altro comune il risultato corretto è che non viene trovata nessuna elaborazione (questo anche per non fornire informazioni sulle operazioni di altri comuni). La situazione è diversa da quella, ad esempio della mutazione scheda, dove tutti i comuni hanno l'autorità per interrogare tutti i soggetti e quindi diamo l'indicazione se il comune è competente o meno (dato che stiamo fornendo una informazione che sarebbe normalmente accessibile dagli operatori).

2. Sull'indicare lo stato di attesa in caso l'elaborazione non sia terminata stiamo valutando la proposta. (ma sempre nel caso il cod mittente sia quello corretto).


Le operazioni che avete indicato sono dei 7002 o altri tipi di operazioni?
Sono state effettuate in ambiente di test comuni e con quale cod mittente?
idOperazioneComune 2019400820 - idOperazioneANPR 22568404
idOperazioneComune 2019400821 - idOperazioneANPR 22568618
idOperazioneComune 2019400822 - idOperazioneANPR 22568638
