### ISSUE TITLE
Variazione di residenza - errore "Operazione non effettuabile"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1708]
Salve,
stiamo cercando di effettuare per il comune di Massafra (subentrato), in ambiente di produzione, una variazione di indirizzo da parte di un individuo, che esce da una convivenza e va a costituire una nuova famiglia residente nel comune, ad un indirizzo differente, di cui è l'unico componente.
Per effettuare l'operazione abbiamo utilizzato il ws 5005, indicando nel blocco _generalitaSchedaFamiglia_ la nuova famiglia, nel blocco  _ResidenzaFamiglia_ la nuova residenza ed impostando di conseguenza gli altri campi nei vari blocchi, ma otteniamo in risposta l'errore in oggetto. La request ci sembra corretta per cui non riusciamo a capire come procedere per la registrazione della mutazione.
L'id operazione comune è 07301520191031291, l'operazione è stata effettuata in data 31/10/2019 come detto in ambiente di esercizio.
In attesa di riscontro, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by rvinzani** [comment]
Stiamo verificando, potreste nel frattempo riprovare ad effettuare l'operazione impostando nella richiesta l'idANPR del soggetto? (72401231)
