### ISSUE TITLE
Consultazione : data protocollo Comune tramite Web-App

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#171]
Salve,
abbiamo fatto una prova di cancellazione per morte con il servizio 2001 tramite Web-Services , in ambiente di TEST per il Comune Di Bologna, passando anche la data protocollo comune e il numero del protocollo comune. Consultando il soggetto tramite la WEB-APP, la data protocollo comune e il numero protocollo non lo vediamo. Tali dati sono consultabili da qualche parte?
Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna

**Comment by gcarbonin** [comment]
la data del protocollo ed il numero riguardano l'operazione e non la persona. Consulti Elenco operazioni sul soggetto (è una delle sezioni della consultazione della scheda individuale) oppure in Utilità e notifiche, monitoraggio operazioni è possibile effettuare una ricerca anche per identificativo operazione comune. Tramite Ws è possibile effettuare ricerche per protocollo.
