### ISSUE TITLE
[6002] Internal Error

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1710]
Ambiente di produzione, comune di Este.

Nel tentativo di produrre un certificato di residenza storico per un cittadino residente in altro comune ANPR con il servizio in oggetto otteniamo un errore SOAP "Internal error (from server)".
L'identificativo comunale dell'operazione è JD22872 con codMittente 028037.
Potete aiutarci a capire la causa del problema ?

Grazie

**Comment by gife67** [comment]
Buongiorno,
cortesemente se potete ripetere la richiesta, perchè per il Comune indicato non vedo richieste con quella tipologia di errore, esaminando dal 25.10.2019 ad oggi.
Grazie

**Comment by gife67** [comment]
Buongiorno,
non avendo avuto riscontro, chiudo questa issue. Nel caso dovesse avere bisogno, può aprirne un altra collegata a questa.
Cordiali Saluti
