### ISSUE TITLE
Errore definizione data di decorrenza residenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1711]
Buongiorno
il Comune di Caponago (MB) da poco subentrato ha riscontrato una difformita' nella data di decorrenza residenza per diversi soggetti , chiedono se è possibile un'aggiornamento massivo di tale data.
Grazie

**Comment by rvinzani** [comment]
Per questo tipo di aggiornamenti consigliamo di utilizzare il servizio 5014 chiamato ricorsivamente per tutti i soggetti per cui è necessario aggiornare la data

**Comment by rvinzani** [comment]
chiudo la issue. In caso fosse necessario è possibile aprire un'altra issue che faccia riferimento a questa stessa
