### ISSUE TITLE
Cambio modalita' operativa aggiornamento dati anagrafici da WA a Software Gestionale + WS Anpr

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1712]
Buongiorno
il Comune di Caponago (MB) da poco subentrato avendo scelto di utilizzare come modalità operativa la WA vorrebbe tornare ad utilizzare il proprio software gestionale per l'aggiornamento dei dati anagrafici dei cittadini ed utilizzare i WS esposti da ANPR per il passaggio delle informazioni.
Come devono procedere ? Serve un'autorizzazione particolare ? Devono richiedere la modifica di qualche configurazione ?

**Comment by Leonforte** [comment]
No, non serve alcuna autorizzazione, occorre solo censire il prorpio indirizzo IP pubblico tramite accesso alla web app di ANPR in ambiente di produzione ( https://dp.anpr.interno.it/com).
selezionando in alto a destra la voce “Amministrazione”  e scegliendo la funzionalità  “Dati Aggiuntivi” nella quale è presente la sezione dedicata all’inserimento/aggiornamento degli indirizzi IP. Saluti
