### ISSUE TITLE
Test di utilizzo WS Anpr

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1713]
Buongiorno
esiste un ambiente di test (come per esempio https://webfree.anpr.interno.it/) dove testare l'utilizzo dei WS di Anpr e le relative risposte ?
I test devono essere effettuatri sulle macchine di sviluppo e non direttamente dal Cliente.

**Comment by Leonforte** [comment]
Esiste lo speculare per i ws al link wsfree.anpr.interno.it le cui credenziali sono gestite dal team digitale. Può scrivere all'iundirizzo segnalazioni-anpr@teamdigitale.governo.it
E' inoltre disponibile un ambiente di test espsoto ai comuni al link https://wstest.anpr.interno.it le cui credenziali di accesso sono invece gestite dall'ammnistratore locale della sicurezza dell'ambiente ANPR di esercizio.
Si suggerisce di consultare la documentazione pubblicata sul portale www.anpr.intrno.it, saluti

**Comment by GabriellaBallabio** [comment]
Buongiorno
abbiamo consultato la documentazione tecnica sul portale www.anpr.interno.it, ma relativamente all'ambiente di test dei WS non abbiamo trovato nulla.
