### ISSUE TITLE
[4005] Elaborazione - manca idOperazioneANPR

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1714]
Buongiorno,
Provando a eseguire alcune richieste 4005 di tipo elaborazione abbiamo riscontrato un comportamento diverso da quanto previsto per questo servizio.
La risposta della richiesta di elaborazione invece che contenere  idOperazioneANPR dell' estrazione che verrà usata per fare poi un'altra chiamata 4005 di verifica stato, contiene un errore EN122 - La richiesta effettuata non produce alcun risultato.
La richiesta : 
>
<?xml version="1.0" encoding="UTF-8"?><ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
    <testataRichiesta>
        <idOperazioneComune>5008SYNC12562120</idOperazioneComune>
        <codMittente>888183</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4005</operazioneRichiesta>
        <dataOraRichiesta>2019-11-04T10:30:31.726+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>FREE</tipoInvio>
        <dataDecorrenza>2019-11-04+01:00</dataDecorrenza>
    </testataRichiesta>
    <elaborazione>
        <dettaglioDati>TUTTO</dettaglioDati>
        <ricercaElenchiRichieste>
            <statoLavorazione>2</statoLavorazione>
            <operazioneRichiesta>5008</operazioneRichiesta>
            <periodoRiferimentoRichieste>
                <dataOraIniziale>2019-11-04T10:00:00.000+01:00</dataOraIniziale>
                <dataOraFinale>2019-11-04T10:30:25.928+01:00</dataOraFinale>
            </periodoRiferimentoRichieste>
        </ricercaElenchiRichieste>
    </elaborazione>
</ns2:Richiesta4005>

La risposta:
>
<?xml version="1.0" encoding="UTF-8"?><ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
    <ns2:rispostaKO>
        <testataRisposta>
            <idOperazioneComune>5008SYNC12562120</idOperazioneComune>
            <codMittente>888183</codMittente>
            <codDestinatario>ANPR02</codDestinatario>
            <operazioneRichiesta>4005</operazioneRichiesta>
            <dataOraRichiesta>2019-11-04T10:30:23.848+01:00</dataOraRichiesta>
            <dataDecorrenza>2019-11-04+01:00</dataDecorrenza>
            <idOperazioneANPR>2252977</idOperazioneANPR>
            <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
            <errore>
                <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
            </errore>
        </listaErrori>
    </ns2:rispostaKO>
</ns2:Risposta4005>

Il primo problema è che il servizio 4005 in questo caso ha restituito una risposta sincrona invece che asincrona (quindi non è possibile fare un'altra richiesta 4005 di verifica stato non sapendo l'idOperazioneANPR).
Il secondo problema riguarda il fatto che per il periodo di riferimento specificato in realta esisteva un operazione 5008.

Potete cortesemente indicarci quale potrebbe essere il motivo di questo comportamento?

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Salve, è possibile che abbiate inviato una richiesta di elaborazione e una di verifica stato con lo stesso id operazione comune ? 5008SYNC12562120

A noi risulta che la richiesta di tale operazione non sia quella da va indicata ma bensi  :

```
    <ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
      <testataRichiesta>
        <idOperazioneComune>5008SYNC12562120</idOperazioneComune>
        <codMittente>888183</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4005</operazioneRichiesta>
        <dataOraRichiesta>2019-11-04T10:30:23.848+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>FREE</tipoInvio>
        <dataDecorrenza>2019-11-04+01:00</dataDecorrenza>
      </testataRichiesta>
      <verificaStato>
        <idOperazioneANPR>2252903</idOperazioneANPR>
        <progressivo>1</progressivo>
      </verificaStato>
    </ns2:Richiesta4005>
```

Va tenuto presente che se viene usata la stessa operazione comune, si attiva un meccanismo di retry per il quale viene restituita la stessa risposta della precedente operazione e non una nuova operazione (a partà di operazioneRichiesta e codMittente).

**Comment by AlbanaCelepija** [comment]
Salve, 

Potrebbe essere questo il motivo, perche questo comportamento capitava solo per alcuni casi specifici.
Grazie mille della risposta.

**Comment by mttfranci** [comment]
Prego.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
