### ISSUE TITLE
Errore annullamento mutazione famiglia residenza 

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1715]
Buon giorno,
il comune di  Colonnella (subentrato) ha necessità di procedere ad un annullamento di una mutazione famiglia residenza effettuata con decorrenza 10/10/2019 (ws 5001, id operazione anpr 137183200), cui è seguita nella stessa data una mutazione scheda (ws 5008, id operazione anpr 137185991). 
Come da specifiche abbiamo provveduto in prima battuta ad annullare la mutazione scheda e l'operazione è andata a buon fine (ws 5012, id operazione anpr 148153085), successivamente abbiamo quindi provato ad annullare la mutazione famiglia residenza ma otteniamo in risposta il messaggio che l'operazione da annullare non è l'ultima per l'individuo/famiglia.
La famiglia dell'individuo è però composta al momento solamente dal soggetto stesso, quindi il messaggio non ci sembra congruente dato che l'unica operazione successiva alla mutazione famiglia è stata annullata con successo. Abbiamo provato l'annullamento anche dalla web application (id operazione anpr 148215377) ma con lo stesso esito.
L'operazione è stata effettuata in data 04/11/2019 in ambiente di produzione, come detto per il comune di Colonnella.
In attesa di riscontro,
cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by frmariani** [comment]
In questo caso, l'operazione non può essere annullata perchè nella famiglia è transitato anche un altro cittadino la cui iscrizione è stata cancellata anzichè essere annullata; 

di seguito la cronologia delle operazioni che sarebbe stato corretto effettuare:
ws 5001 soggetto 1;
ws 5008 soggetto 1;
ws 1002 soggetto 2;
ws 1013 soggetto 2; 
ws 5012 soggetto 1 (non è necessario annullare le operazioni di mutazione scheda sul soggetto).

A questo punto, per sistemare la situazione dovreste eseguire le seguenti operazioni:
annullare la cancellazione del soggetto 2 (ws 2013 idoperazione 148207493) ;
annullare l'iscrizione del soggetto 2 (ws 1013 idoperazione 143750628);
annullare l'operazione di Mutazione Famiglia/Convivenza del soggetto 1  (ws 5012 idoperazione 137183200).

Riprovate e datemi ritorni sull'esito.

**Comment by frmariani** [comment]
la issue viene chiusa, in caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.

**Comment by Amucciarelli74** [comment]
Buona sera,
confermo il buon esito dell'operazione seguendo le istruzioni da voi fornite.
Grazie, cordiali saluti.
Giuseppe Mucciarelli, TINN srl
