### ISSUE TITLE
Mutazione tutti i dati - evento matrimonio

### ISSUE THREAD

**Issue by comuneditenno** [italia/anpr#1716]
Buon giorno,
  sono un dipendente del Comune di Tenno subentrato in anpr, per un nominativo X il precedente Comune ci segnala che per errori durante il subentro i dati di matrimonio e divorzio sono errati. Con la ditta che segue il nostro software siamo riusciti a sistemare i dati del divorzio ma quando andiamo a cercare di modificare i dati del precedente matrimonio otteniamo i messaggi di errore che allego.
Abbiamo inoltre verificato tramite Webapp che per il nominativo X non vi erano precedenti coppie di fatto.
Ringrazio per la cortese attenzione.
Saluti
Roberto
![errore matrimonio](https://user-images.githubusercontent.com/57358171/68127482-48f6ad80-ff16-11e9-85d3-a744f7d07f43.png)

**Comment by frmariani** [comment]
in caso di dati errati al subentro, si consiglia di utilizzare la funzione "Eliminazione dati" presente nei servizi di registrazione della web app di ANPR;
come comunicato per le vie brevi, abbiamo eliminato il record inconsistente inviato da subentro, pertanto adesso dovreste essere in grado di effettuare l'operazione  richiesta.
