### ISSUE TITLE
GESTIONE AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1717]
Buongiorno
un comune subentrato che utilizza il prorpio software gestionale per la gestione anagrafica, per i cittadini AIRE deve continuare ad utilizzare il software di ANAGAire ?

**Comment by ncapozzi** [comment]
Buongiorno,
il comune subentrato in ANPR non deve più utilizzare AnagAire per la gestione dei soggetti AIRE ma i servizi di ANPR o in alternativa le funzionalità disponibili nell'applicazione WEB. Per ulteriori informazioni è disponibile il documento https://www.anpr.interno.it/portale/documents/20182/26001/MI-14-AN-01+SPECIFICHE+DI+INTERFACCIA+WS.pdf/9567d58b-43ba-48e0-81a8-47c40daa5ecd

N. Capozzi
