### ISSUE TITLE
Errore su comunicazione 5008 per correzione Stato Civile

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1718]
Buongiorno,
Ambiente di produzione

Il Comune in questione, con l'operazione ID 148614004 sta cercando di correggere lo stato civile della persona interessata da nubile a coniugata. Viene però restituito, come errore, che si sta cercando di variare i dati anagrafici del soggetto senza richiesta di validazione da parte dell'Agenzia delle Entrate.
In un primo momento abbiamo verificato le generalità presenti nella richiesta e le "Generalità da ricercare" erano uguali alle "Generalità da modificare". 
Siamo quindi andati a controllare le generalità della persona anche su Agenzia dell Entrate e la persona in questione risulta avere, come stato di nascita, URSS, mentre su ANPR risulta avere, come stato di nascita NON ATTRIBUIBILE.

Di conseguenza, per sanare la situazione, abbiamo cercato, con l'operazione 148627048 di correggere la descrizione dello Stato di nascita su ANPR per allinearla a quella di Agenzia delle Entrate, ma otteniamo come ritorno "Operazione non effettuabile".
Come dobbiamo procedere per risolvere la situazione?

Ringraziando anticipatamente.
Saluti

**Comment by ncapozzi** [comment]
Buonasera,
potete riprovare per favore a reinviare l'ultima richiesta per favore?

N. Capozzi

**Comment by SAlberto** [comment]
Buongiorno,
abbiamo riprovato le operazioni con il Comune in Questione e sono state inviate correttamente.
Grazie per la collaborazione.

Saluti
