### ISSUE TITLE
[INFO] wsdl e xsd

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1719]
Buongiorno,
i wsdl e gli xsd riportati in queste pagine:

- https://github.com/italia/anpr/tree/master/wsdl
- https://github.com/italia/anpr/tree/develop/wsdl

sono gli ultimi?
perchè stando alla data di ultimo commit sono vecchi di 5 mesi

Ringrazio anticipatamente

**Comment by mttfranci** [comment]
Salve, mancava solo l'ultimo aggiornamento della provincia contea (versione 5.6.4) ma ora dovrebbe essere tutto allineato.
Saluti

Assistenza ANPR
