### ISSUE TITLE
[1014] classificazione errore EN393

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1720]
Buongiorno l'errore EN393 nella documentazione tecnica (elenco segnalazioni ANPR operazione anagrafiche.XLSX) è classificato come Errore, mentre nella risposta risulta Warning
esempio idOperazioneANPR 105271729 mittente 026065 produzione.

Dal messaggio dell'errore sembra sia corretto che sia W quindi mi chiedevo se è corretto considerarlo W?
grazie mille
Riccardo

**Comment by rvinzani** [comment]
Grazie della segnalazione. Abbiamo aggiornato la documentazione
