### ISSUE TITLE
[5008]  da wa, correzione dati matrimonio, perdita dati sul coniuge

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1721]
Buongiorno.
Ambiente di test, stiamo simulando alcune operazioni tramite wa.
I cittadini interessati sono l'id 16426605 moglie, e l'id 16435860 marito.
Nella scheda del matrimonio i due coniugi non sono referenziati: sono presenti solo cognome e nome del coniuge.

Con mutazione dati, operazione 22585857 fatta sul marito, referenziamo nella scheda del matrimonio, il coniuge con l'id anpr. 
Interrogando la moglie, vediamo che anche lei ha la scheda del matrimonio aggiornata e il coniuge referenziato. Anche sulla moglie risulta in consultazione "elenco operazioni" la stessa operazione del marito.

A questo punto abbiamo fatto una nuova mutazione dati sul marito, la 22585927, togliendo i dati della moglie: ovvero dalla wa abbiamo cliccato su ripulisci e ricaricato i dati, indicando solo cognome e nome della moglie, senza ricercarla.
Consultando il marito vediamo i dati ovviamente aggiornati.

L'anomalia ci sembra sulla moglie, che ora:
- non ha più i dati di matrimonio
- non risulta alcuna operazione registrata nel "elenco operazioni"

Siccome è successo anche in produzione di dover rettificare dei dati, a volte anche per risolvere dei blocchi sul coniuge, potete controllare la casistica?
Tra l'altro questa situazione si può verificare anche con i coniugi residenti in comuni diversi.

Marco Migliori

**Comment by frmariani** [comment]
i coniugi condividono le informazioni sul matrimonio e le operazioni effettuate sono cronologicamente sequenziali e significative;
l'operazione idanpr 22585927 ha eliminato la riconciliazione effettuata con l'operazione idanpr 22585857, pertanto, ad oggi, è corretto che la moglie non abbia l'informazione del matrimonio;
se consultiamo la cittadina al 14/12/2018, risulterà sposata con un soggetto extra-anpr, al 01/11/2019 risulterà sposata con il soggetto idanpr 16435860, mentre al 02/11/2019 non risulta sposata.
Le operazioni effettuate sono utilizzate proprio per conoscere la storia anagrafica del cittadino alla data.

**Comment by MarcoMigliori** [comment]
Grazie della spiegazione. Prendo atto della risposta.
