### ISSUE TITLE
Errore EN243 durante l'inserimento di un divorzio

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1722]
Buongiorno,
ambiente di produzione.

Il Comune sta cercando di inserire, con l'operazione ID 148955009 un divorzio tra una loro residente e un soggetto che invece non lo è. Abbiamo anche già preventivamente controllato i dati del matrimonio corrispondente ed è caricato tutto correttamente.
Come risposta all'operazione di cui sopra il Comune riceve i seguenti messaggi:
EN243 - I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto
e
EHR96 - Sezione annullamento matrimonio valorizzata: riportare almeno le generalita' del coniuge nella sezione matrimonio

Come dobbiamo procedere in questo caso?
Ringraziando anticipatamente per la risposta.
Cordiali saluti.

**Comment by frmariani** [comment]
nell'operazione idanpr 148955009 la data di separazione ( 27/05/2006 ) è minore della data del matrimonio (22/06/2006)

**Comment by SAlberto** [comment]
Buongiorno,
abbiamo segnalato la cosa al Comune che ha provveduto a correggere i dati. 

Grazie per la collaborazione.
Saluti,
