### ISSUE TITLE
Problema con Cittadina cambio cognome

### ISSUE THREAD

**Issue by Nichelino** [italia/anpr#1723]
Salve, abbiamo un problema con una cittadina alla quale è stato effettuato un cambio di cognome.
Il sistma tuttavia, nel momento della variazione di cognome, restituisce i seguenti errori:

Errore | EN230 | Attenzione! Sono stati modificati i dati anagrafici del soggetto senza validazione di Agenzia Entrate. 
-- | -- | -- | --
Errore | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-06 09:19:45 , idOperazioneANPR 149143326

Abbiamo provato a risolvere il problema tramite portale ANPR - risoluzione disallineamenti con esito negativo.
Il soggetto risulta già validato dall'A.E. sebbene l'errore precedente indichi il contrario.
Attendiamo vostro riscontro.
Saluti

**Comment by rvinzani** [comment]
L'errore ritornato indica che si sta chiedendo una mutazione dei dati anagrafici e nel dato di controllo gestioneCF è presente 3-modifica senza validazione AE
Questo non è possibile se il CF è validato.
E' quindi necessario effettuare una nuova mutazione dati anagrafici impostando il campo gestioneCF=0

**Comment by Nichelino** [comment]
Salve abbiamo effettuato l'operazione come da voi indicato, ma il sistema restituisce il seguente errore:
"1 Errore Anpr Cod: EN230 - Attenzione! Sono stati modificati i dati anagrafici del soggetto senza validazione di Agenzia Entrate. - Cognome: XXXX Nome: yyyy CF: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-07 15:09:45 , idOperazioneANPR 150126018 - Cognome: xxxxx Nome: yyyy CF: "
Restiamo in attesa di un vostro riscontro.
Grazie. Saluti

**Comment by rvinzani** [comment]
Purtroppo è sempre impostato non correttamente il dato di controllo gestioneCF

<datiControllo>
				<tipoMutazione>01</tipoMutazione>
				<tipoMutazione>14</tipoMutazione>
				**<gestioneCF>3</gestioneCF>**
			</datiControllo>
		</ns2:Richiesta5008>

**Comment by rvinzani** [comment]
<datiControllo>
				<tipoMutazione>01</tipoMutazione>
				<tipoMutazione>14</tipoMutazione>
				<gestioneCF>3</gestioneCF>
			</datiControllo>
		</ns2:Richiesta5008>

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
