### ISSUE TITLE
[4005] stato lavorazione ignorato

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1724]
Buongiorno ho notato che nella richiesta notifiche (sicuramente N010 non ho controllato le altre) se viene specificato statoLavorazione=7 (Notifiche da   prendere in carico) vengono comunque restituite tutte quelle che rientrano nell'intervallo di date indicate.
riporto id operazioni in **produzione** comune **063049**
**148791255** dataOraRichiesta>2019-11-05T11:49:59
```
<ricercaElenchiRichieste>
                    <statoLavorazione>7</statoLavorazione>
                    <operazioneRichiesta>N010</operazioneRichiesta>
                    <periodoRiferimentoRichieste>
                        <dataOraIniziale>2019-10-29T00:00:00</dataOraIniziale>
                        <dataOraFinale>2019-11-05T11:49:59</dataOraFinale>
                    </periodoRiferimentoRichieste>
</ricercaElenchiRichieste>
```
VERIFICA STATO
idOperazioneANPR>**148886455** dataOraRichiesta>2019-11-05T13:20:28
torna la notifica idOperazioneANPR>144904548
successiva richiesta di notifiche
idOperazioneANPR>**148912641** dataOraRichiesta>2019-11-05T14:08:30
```
<ricercaElenchiRichieste>
                    <statoLavorazione>7</statoLavorazione>
                    <operazioneRichiesta>N010</operazioneRichiesta>
                    <periodoRiferimentoRichieste>
                        <dataOraIniziale>2019-10-29T00:00:00</dataOraIniziale>
                        <dataOraFinale>2019-11-05T14:08:30</dataOraFinale>
                    </periodoRiferimentoRichieste>
</ricercaElenchiRichieste>
```
VERIFICA STATO
idOperazioneANPR>**148942652** dataOraRichiesta>2019-11-05T15:11:14
torna nuovamente la notifica idOperazioneANPR>144904548

Abbiamo interpretato male il funzionamento del tag statoLavorazione?

Grazie mille
Riccardo

**Comment by fferraguto** [comment]
Salve,
le notifiche vengono considerate "lavorate" solo se ricevute dal comune tramite endpoint.Il 4005 non comporta la variazione di stato delle notifiche.
Cordiali saluti.

**Comment by fmbianchi** [comment]
Grazie
buona giornata
