### ISSUE TITLE
[4005] Verifica Stato Notifiche - Sembra bloccato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1725]
ambiente di PRODUZIONE - comune di FIORANO MODENESE (036-013)

sono state richieste le notifiche degli ultimi 10 giorni.
idOperazioneANPR assegnati alle richieste di notifica:
N031 - 149497302
N015 - 149497298
N014 - 149497295
N010 - 149497289

sarebbero dovute essere disponibili il 6/11/2019 alle 15.52, ma da quell'ora la verifica di stato sposta la disponibilità sempre avanti di un'ora ad ogni nuova richiesta...

è possibile che sia bloccato qualcosa?
potete verificare e sbloccare nel caso?

grazie.
Alessandro Monopoli ADS

**Comment by fferraguto** [comment]
Salve,
i risultati possono essere resi disponibili fino a 24h dopo la richiesta.
Avete per caso verificato la disponibilità successivamente?
A presto

**Comment by AMonopoliADS** [comment]
> Avete per caso verificato la disponibilità successivamente?
abbiamo visto che, il giorno dopo, la response è stata restituita.

> i risultati possono essere resi disponibili fino a 24h dopo la richiesta.
preciso che a volte capita - come in questo caso - che la richiesta delle notifiche rivesta carattered i urgenza.
dai primi scambi avuti con SOGEI riguardo questa "nuova" modalità asincrona di acquisizione delle notifiche, tale necessità era emersa, ed era venuto fuori che - proprio in caso di necessità - si potesse richiedere la verfica di stato anche prima dell'ora prevista dalla disponibilità.
abbiamo sperato che questo potesse essere uno dei casi fortunati in cui la risposta sarebbe arrivata anche in anticipo, ma così non è stato.
mi auguro che la tendenza sia comunque quella di restiture le notifica prima possibile, e che si verifichi sempre meno il rischio di spostamento alle 24 ore.

grazie comunque per il riscontro.
