### ISSUE TITLE
[4005] Verifica Stato - data disponibilità rimandata

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1726]
Salve,
Abbiamo eseguito alcune richieste 4005 in modalità elaborazione di richieste 5008.
Ambiente Test - Id Sede: 888183
IdOperazioneComune: ELB1001SYNCQW3S421
idOperazioneANPR: 2273128

Se proviamo a fare verificaStato prima della data disponibilità, questo valore è sempre uguale, invece dopo la dataDisponibilità il valore viene rimandato con un ora.
IdOperazioneComune di verifica stato: VRF1001SYNCQW3S4232
(un simile comportamento nel issue #1396)

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by AlbanaCelepija** [comment]
Abbiamo ripetuto di nuovo la richiesta facendo un test manuale e continua a rimandare la data della disponibilità:
idOperazioneAnpr del elaborazione: 2275740
idOperazioneComune della richiesta di verifica: TestVeriFFFFTR3W13554378
La risposta:
>
<a:Risposta4005 xmlns:a="http://sogei.it/ANPR/4000estrazione">
            <a:RispostaMultipla4005>
                <testataRisposta>
                    <idOperazioneComune>TestVeriFFFFTR3W13554378</idOperazioneComune>
                    <codMittente>888183</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>4005</operazioneRichiesta>
                    <dataOraRichiesta>2019-11-07T09:50:00</dataOraRichiesta>
                    <idOperazioneANPR>2276166</idOperazioneANPR>
                    <esitoOperazione>0000</esitoOperazione>
                </testataRisposta>
                <statoRichiesta>1</statoRichiesta>
                <idOperazioneANPR>2275740</idOperazioneANPR>
                <dataDisponibilita>2019-11-07T10:54:21.831+01:00</dataDisponibilita>
            </a:RispostaMultipla4005>
        </a:Risposta4005>

**Comment by mttfranci** [comment]
C'era stato un errore nell'elaborazione.
Potreste riprovare?

Assistenza ANPR

**Comment by AlbanaCelepija** [comment]
Abbiamo riprovato per questo operazione e la data non viene rimandata più e riceviamo la risposta giusta. 
Pero riprovando per altre nuove richieste si ripete la stessa cosa:
IdOperazioneComune : ELB1001SYNC215732219000681
IdOperazioneANPR da verificare lo stato:  2277387
Data disponibilità rimandata a 2019-11-08 17:43:47 quando la prima elaborazione era: 2019-11-08 16:15:00

**Comment by mttfranci** [comment]
In questi giorni ci sono dei problemi sporadici in ambiente di test che stiamo analizzando.
Vi suggeriamo di sottomettere nuovamente l'elaborazione.
L'ambiente di produzione non è soggetto al problema.
Saluti

Assistenza ANPR
