### ISSUE TITLE
[6001] Altro errore EN087

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1727]
Ambiente di produzione, comune di ACI CASTELLO

Tentando di rilasciare un certificato per un soggetto con il servizio 6001 otteniamo "EN087 La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti" (id operazione ANPR 149497538).
Consultando i dati del soggetto non abbiamo rilevato anomalie.
Sembra molto simile alla #1635

Potete verificare ?

Grazie

**Comment by mttfranci** [comment]
Si avete ragione, la casistica è la stessa.
Potete riprovare?
Grazie in anticipo.

Assistenza ANPR
