### ISSUE TITLE
[5001] rimpatrio da altra AIRE con errori

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1728]
Ambiente di produzione, comune di Sestri Levante

Il comune sta tentando di iscrivere nella propria anagrafe un cittadino attualmente presente nell'AIRE di LA SPEZIA, comune subentrato.
L'operazione 5001 però va in errore (id op anpr 149987634) poiché a quanto pare attualmente il soggetto, in ANPR, ha ERRONEAMENTE il tipo famiglia impostato a 3 (=famiglia APR) invece di 5 (=famiglia AIRE). 
Il comune iscrivente non può fare nulla.

Potete correggere voi la situazione ?

Grazie

**Comment by ncapozzi** [comment]
Buonasera,
potete ripetere l'operazione per favore?

N. Capozzi

**Comment by busaster** [comment]
problema risolto
Grazie
