### ISSUE TITLE
Errore "Salvataggio del file in ATMOS fallita" in ambiente pre-subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1730]
Salve,
alcuni nostri clienti (i comuni di Silvi e Sulmona) stanno avendo problemi nel caricamento del file APR  in ambiente di pre-subentro, si tratta della stessa problematica segnalata nella issue #1707 per l'ambiente di test, appare il messaggio di errore in oggetto e il file non viene caricato.
Il problema era stato indicato da voi come risolto, forse per il pre-subentro ci sono ancora dei problemi o in qualche modo si sono riproposti?
In attesa di riscontro,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by vix-db** [comment]
Salve,
stesso identico problema su ambiente di pre-subentro per il comune di Valva (SA).
Visto che dovremmo subentrare definitivamente il giorno martedi 12 p.v. vi preghiamo di risolvere il problema in modo da poter effettuare l'ultimo invio in presubentro per scongiurare eventuali problemi il giorno di quello definitivo.

Vittorio Nesta
Comune di Valva (SA)

**Comment by FilippoPapi** [comment]
salve
oggi abbiamo avuto dei problemi nell'ambiente di presubentro. sono stati risolti potete riprovare
