### ISSUE TITLE
Problema abilitazione indirizzo IP - comune di TRIEI

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1732]
Buon giorno,
il comune di TRIEI (subentrato in data 29/10/2019) ha problemi con la connessione ai servizi ANPR dalla nostra procedura. L'indirizzo IP comunicato dall'ente in fase di configurazione risulta al momento non abilitato sulla console di sicurezza, manca infatti l'asterisco (ma nei giorni scorsi era presente), e il comune non riesce ad effettuare il neanche i test di connessione. 
Per avere i dati da verificare potete contattare il nostro referente presso l'ente (Giovanni Corgiolu) all'indirizzo email g.corgiolu@ollsys.net.
Grazie, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by cmigliardi** [comment]
Buonasera, 
per il comune di TREIE ho avuto diversi scambi di email con Corgiolu e abbiamo verificato la situazione, io stessa ho confermato via email che l'indirizzo IP 82.85.145.91 è correttamente abilitato  verso i servizi di Anpr. Quindi i problemi di connessione non sono dovuti ad una mancata abilitazione. Il fatto che non sia visibile l'asterisco è solo un problema di visualizzazione.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
