### ISSUE TITLE
Errore: EN469 Il soggetto risulta iscritto anche nel comune...

### ISSUE THREAD

**Issue by Charge71** [italia/anpr#1733]
Salve, sto cercando di ottenere un certificato di residenza dal comune di Ciampino e ricevo il seguente errore:

`Errore nel collegamento con il server Operazione ID = JD24213
Il servizio ANPR ha risposto con errori

Codice	Testo
EN469	Il soggetto risulta iscritto anche nel comune di 065098 Con data iscrizione 18/01/1975`

Potete controllare?
Grazie.

**Comment by frmariani** [comment]
come evidenziato in fase di subentro con l'anomalia EN471, il soggetto risulta duplicato, cioè iscritto anche in un altro Comune;
nel Vostro caso, il cittadino risulta iscritto anche nel Comune di Pollica (SA), pertanto dovete contattare l'altro Comune e verificare dove il cittadino risiede effettivamente;
il Comune che ha impropriamente in carico il cittadino, deve effettuare una "Cancellazione per altri motivi" con motivo cancellazione "Doppia iscrizione".

**Comment by Charge71** [comment]
Grazie per la risposta. La persona in questione in realtà risiede da anni a Ciampino, pertanto contatteremo il comune di Pollica per verificare.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.
