### ISSUE TITLE
Errore "Salvataggio del file in ATMOS fallita" - Ambiente pre-subentro

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1734]
Buongiorno,
su un nostro cliente stiamo avendo un problema sul caricamento del file APR in ambiente di pre-subentro.
Si tratta della stessa problematica segnalata nella issue #1730 proprio nell'ambiente di pre-subentro, che era stato indicato da voi come risolto.

E' possibile verificare la situazione?
Grazie
Marco Sala
Pa Digitale Spa

**Comment by FilippoPapi** [comment]
in questi giorni abbiamo problemi nel sistema di accoglienza in presubenrtro.
i Problemi sono temporanei. potete riprovare
