### ISSUE TITLE
[2003] Cancellazione bloccata da operazione sospesa

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1735]
Ambiente di produzione, comune di Bergamo

Dobbiamo cancellare un cittadino per altri motivi con il servizio 2003 ma otteniamo l'errore "EN203 Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto". (id operazione ANPR 151169860)
Non sappiamo però quale sia questa operazione.

Potete aiutarci a recuperarla ?

Sarebbe molto utile in questi casi avere nel messaggio d'errore un riferimento più preciso all'operazione sospesa che blocca (es tipo operazione e data operazione) per facilitare il suo recupero da interfaccia.

**Comment by frmariani** [comment]
l'operazione sospesa, si riferisce ad un'operazione di Mutazione tutti i dati effettuata e NON conclusa con la web app di ANPR; 
proprio per questo motivo,  l'eliminazione o la conclusione dell'operazione sospesa  è possibile soltanto dalla web app di ANPR al seguente percorso:
Servizi di Registrazione> Tipo di operazione : Mutazione tutti i dati > Iniziativa: operazione d'ufficio > selezionare "ELENCO OPERAZIONI SOSPESE" , quindi eliminare o concludere l'operazione relativa al CF in questione.

**Comment by frmariani** [comment]
La issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova facendo riferimento a questa stessa.
