### ISSUE TITLE
Eliminazione dato permesso di soggiorno

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1736]
Buongiorno,

volevamo segnalare che per alcuni soggetti in possesso di permesso di soggiorno e successivamente divenuti cittadini italiani non riusciamo ad eliminare il dato del permesso tramite la funzione "eliminazione dati", nonostante si inserisca come motivazione "altro" e nelle note si specifichi "acquisto cittadinanza italiana".
L'errore segnalato dal sistema è il seguente: "L'operazione di revoca è possibile solo a valle del subentro".
A titolo esemplificativo indichiamo l'id di un soggetto per il quale riscontriamo questo problema: 28775118.
Non essendo corretto che per i cittadini italiani compaia il permesso di soggiorno è possibile risolvere il problema?
Inoltre, questo disallineamento crea ai cittadini un problema per la certificazione dal portale TorinoFacile.

Grazie.
UPI Torino

**Comment by rvinzani** [comment]
Il dato del permesso di soggiorno rimane come dato pregresso. Tale informazione sebbene presente non è più significativa e non incide sulla certificazione. Non deve essere pertanto necessariamente rimossa
