### ISSUE TITLE
URGENTE - Errore "Salvataggio del file in ATMOS fallita" - Ambiente pre-subentro 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#1737]
Buongiorno,
su un nostro cliente (Vignola) stiamo avendo un problema sul caricamento del file APR in ambiente di pre-subentro.
Si tratta della stessa problematica segnalata nella issue #1730 proprio nell'ambiente di pre-subentro, che era stato indicato da voi come risolto.

E' possibile verificare urgentemente la situazione? abbiamo altri appuntamenti a breve  (San Giovanni in Persiceto)
Grazie

Cinzia Girelli
Gruppo GPI Spa

**Comment by FilippoPapi** [comment]
potete riprovare

**Comment by CGIRELLI-HUB** [comment]
Non funziona nuovamente ieri sera non abbiamo avuto modo di provare ma ora
è di nuovo impossibile caricare i file di subentro.

E' urgentissimo

Grazie
Cordiali saluti


       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 11 nov 2019 alle ore 16:49 FilippoPapi <
notifications@github.com> ha scritto:
