### ISSUE TITLE
Iscrizione scheda convivenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1738]
Buongiorno
volevamo capire con un esempio quando esattamente si verifica questo evento ... quando avviene un evento di unione civile ?
Quando due più persone vanno a vivere nella stessa casa ?

**Comment by rvinzani** [comment]
Per convivenza si intende la presenza nella stesso domicilio di soggetti legati tra di loro con vincoli non affettivi. Una convivenza può essere una casa di cura, una caserma, un carcere.
