### ISSUE TITLE
Errore "Salvataggio del file in ATMOS fallita" - Ambiente TEST

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1739]
Buongiorno,
su un nostro cliente (comune di Calolziocorte) sta avendo problemi sul caricamento del file APR e AIRE in ambiente di test.

E' possibile verificare la situazione anche per ambiente di test?
Grazie
Marco Sala
Pa Digitale Spa

**Comment by FilippoPapi** [comment]
il problema è saltuario. riprovate
