### ISSUE TITLE
Web App - Certificato anagrafico di morte o di cancellazione anagrafica

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#174]
Ambiente di test: 19/5/2017

Ho cercato di emettere un certificato anagrafico di morte al soggetto deceduto ID ANPR 929574, ma il sistema mi dice che "Il certificato richiesto non puo' essere emesso in quanto il soggetto richiedente risulta deceduto (Codice: EN170)".
Richiedendo il certificato di cancellazione anagrafica, la risposta è "Il certificato non puo' essere emesso in quanto il soggetto e' deceduto (Codice: EN228)".
Cordiali saluti. 
Valentina Bocchino
Comune di Torino

**Comment by gcarbonin** [comment]
Il primo errore deriva dal fatto che nella WA intestatario e richiedente sono di default la stessa persona; è ovvio che un certificato di decesso non può essere richiesto dal deceduto. E' sufficiente cambiare il richiedente.
Il secondo errore deriva dal fatto che è stato richiesto un certificato di cancellazione anagrafica di un soggetto deceduto, cosa non permessa.

**Comment by VBocchinoTO** [comment]
Grazie, correggendo il richiedente funziona regolarmente!
