### ISSUE TITLE
Salvataggio del file in ATMOS fallita - in ambiente test e presubentro 

### ISSUE THREAD

**Issue by Franzo001** [italia/anpr#1740]
Buonasera,
dal giorno 7/11/2019, non si riesce a completare  le operazioni di registrazione del file di subentro sia per gli APR che per gli AIRE e sia in ambiente test che di presubentro, il sistema restituisce sempre il messaggio in oggetto, anche ripetendo più volte l'invio, con diversi comuni.  Abbiamo programmato il subentro per i comuni di Castellucchio (MN) e Bardolino (VR) per il giorno 15/11, ma volevamo eseguire un ultimo invio per un'ultimo controllo, siamo sicuri che non si riscontro lo stesso problema anche in ambiente di produzione (subentro)?
Grazie e buon lavoro.
Francesco 
Ica Systems Verona.

**Comment by FilippoPapi** [comment]
il problema è saltuario. riprovate
