### ISSUE TITLE
WS2003 - ANOMALIA (autorizzazione

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1741]
Buonasera,
COMUNE DI CASERTA - 061022
in fase di test con servizio WS2003 si presenta il seguente errore:
<errore>
                        <codiceErroreAnomalia>EN493</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione </testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-11 18:29:43 , mittente 061022 , idOperazioneComune 2019200300007</testoErroreAnomalia>

**Comment by mttfranci** [comment]
Nel caso specifico il messaggio viene restituito perchè il soggetto che provate a cancellare non esiste (abbiamo verificato che non esiste in test un soggetto con il codice fiscale inviato, nè con la combinazione nome / cognome inviata).
Il messaggio di errore sui servizi di registrazione è volutamente scritto in modo da non dare indicazioni sul fatto che l'operazione non possa essere compiuta per mancanza di autorizzazione o per assenza del soggetto.
Saluti

Assistenza ANPR.

**Comment by rinonasti** [comment]
OK grazie
