### ISSUE TITLE
URGENTE - Errore "Salvataggio del file in ATMOS fallita" - Ambiente pre-subentro

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#1742]
Come già segnalato su #1734 (chiuso) il problema in oggetto persiste, abbiamo urgenza di fare il test di presubentro per il Comune di San Giovanni in Persiceto.

Grazie 
Cordiali saluti

Cinzia Girelli 
Gruppo GPI SPA
3346216774

**Comment by FilippoPapi** [comment]
il problema è saltuario. riprovate
