### ISSUE TITLE
[WA] Rettifica dati iscrizione non disponibile

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1743]
Ambiente di produzione. id cittadino 64737812.
Tentiamo dalla WA la registrazione della "rettifica - dati di iscrizione".
Ci blocca nella 1°videata appena scelto dalla combo, "dati di iscrizione" con il seguente errore:

_Tipo rettifica non consentito, dati iscrizione non disponibili_

Abbiamo provato 2-3 nomi ci sembra lo segnali sempre. E' cambiato qualcosa?

**Comment by frmariani** [comment]
i dati dell'iscrizione (motivo e provenienza), possono essere rettificati soltanto dal Comune che ha iscritto il cittadino in ANPR;
per il cittadino in questione è stato effettuato un cambio di residenza, pertanto i dati dell'iscrizione non possono essere modificati.
verificate  se anche per gli altri cittadini sono presenti delle modifiche di residenza.

**Comment by MarcoMigliori** [comment]
Grazie, giro la risposta al Comune.
