### ISSUE TITLE
Errore "Salvataggio del file in ATMOS fallita" - Ambienti Vari

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1744]
Buongiorno,

ho visto che le issues #1734 e #1739 sono state chiuse con la stessa risposta più o meno, che il problema è saltuario e di riprovare.
Noi con i nostri clienti stiamo però provando ininterrottamente da ieri mattina e il risultato è sempre lo stesso errore.
Questo ci sta bloccando le attività.

Non è possibile fare qualcosa in merito?
Grazie
Marco Sala
Pa Digitale S.p.a.

**Comment by CGIRELLI-HUB** [comment]
Mi accodo in merito allo stesso argomento poichè anche noi stiamo dando un disservizio ai nostri clienti. Non mi pare una soluzione quella di riprovare in maniera random. L'ambiente o funziona o non funziona. Vi preghiamo di fornire una risoluzione che non sia per tentativi. 

Grazie 
Cordiali saluti 

Cinzia Girelli
Gruppo Gpi S.p.a.

**Comment by mccalv** [comment]
Salve concordo con il punto, teniamo questa issue aperta in attesa di risoluzione definitiva del problema (confermo che avviene su base casuale, ma comunque instabile).

**Comment by edoardodona-1** [comment]
Buongiorno. Mi associo al thread . Oggi pm da ns. Cliente Borgo San Giovanni . Ripetuti tentativi di upload su sito presubentro ma abbiamo sempre ricevuto "Salvataggio del file in ATMOS fallita" . 
Da quanto leggo sopra sembrerebbe che si consiglia di provare e riprovare.... Noi stiamo fornendo un servizio ai nostri clienti ... sarebbe bello che funzionasse sempre anche perche , dal momento che da un po' di mesi a questa parte l' upoload va fatto a casa del cliente con smart card oltre che certificato, la cosa diventa onerosa per piu' persone ed e' anche brutto mostrare al cliente il problema. 
Grazie 
Edoardo  Dona' <Edoardo.Dona@datamanagementitalia.it>

**Comment by Franzo001** [comment]
Anche noi ci associamo al thread, in quanto la risposta di chiusura alla nostra segnalazione #1740, non ha portato soluzione. Inoltre facciamo presente che per i comuni che avevano già eseguito l'invio dei dati in pre subentro e la successiva richiesta di cancellazione per eseguire il nuovo invio, la funzione della cancellazione non elimina tutti i file presenti e consultabili alla voce "monitoraggio anomalie", al punto  "Numero schede individuali con dati errati o incompleti", seppur riportando nella colonna "Situazione Attuale"  0, lo stesso è sottolineato e permette il download del file delle anomalie riferita alle precedente fornitura, come se il comando di cancellazione si  fosse interrotto, tale comportamento è stato riscontrato nei 6 comuni che stiamo portando al subentro.
Francesco Russo
Ica Systems Verona

**Comment by RBiasi** [comment]
Buongiorno anche noi abbiamo lo stesso problema. Dovrebbe essere corretto per stasera alle 18:00 giusto?

Grazie
Roberta Biasi
Dedagroup Public Services

**Comment by vix-db** [comment]
Buongiorno,
tutt'ora ancora non riusciamo ad inviare in presubentro a causa del problema in oggetto.

**Comment by CGIRELLI-HUB** [comment]
Provato poco fa funziona non segnala più l'errore in oggetto

**Comment by Franzo001** [comment]
Confermo, inviato per 4 comuni.
Francesco Russo
Ica Systems Verona
