### ISSUE TITLE
Cancellazione per comune subentrato? 

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1745]
Buongiorno,

abbiamo ricevuto dal Comune di Napoli richiesta di cancellazione di nucleo famigliare per immigrazione nel loro comune.

Tuttavia, ricercando i cittadini in ANPR questi risultano ancora residenti nel nostro comune e non duplicati.

Come procedere?

Cancelliamo i cittadini per altri motivi?

Attendiamo gentile riscontro 

Grazie

**Comment by frmariani** [comment]
Il Comune di Napoli, essendo subentrato, deve effettuare la mutazione di residenza dell'intera famiglia senza richiedervi la cancellazione dei cittadini;
gentilmente mi indichi l'idanpr di un componente della famiglia, sarà mia cura contattare il Comune di Napoli;

**Comment by RBiasi** [comment]
Si tratta dei cittadini:
Id scheda attribuito da ANPR 74868444
Id scheda attribuito da ANPR 74868445
Id scheda attribuito da ANPR 74868442

facenti tutti e tre parte del nucleo famigliare 42499567.

Grazie

**Comment by frmariani** [comment]
Grazie.
