### ISSUE TITLE
Spostare <Interno1> in <nui>

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#1747]
Ci siamo accorti che in fase di subentro c'e' stata un'imprecisione nella mappatura dei campi del DB locale verso i campi previsti da ANPR. 
In particolare abbiamo trasmesso come <interno1> ciò che in realtà è <nui>.

Almeno un mese fa abbiamo aperto una richiesta via call center telefonico (richeista n. 20617792) per risolvere il problema, ma a parte una chiamata interlocutoria non abbiamo avuto riscontro.

L'imprecisione, oltre a pregiudicare la correttezza semantica dei dati trasmessi, ha anche implicazioni pratiche fastidiose: per esempio, enti come Agenzia delle entrate prelevano indirizzi non corrispondenti alla realtà ecografica e le comunicazioni che inviano ai cittadini non sono recapitate dal servizio postale e restituite al mittente per indirizzo inesistente.

Soluzione inevitabile è correggere il dato presente in ANPR, spostando ciò che è in <interno1> in <nui>, con l'accortezza di non sovrascrivere i pochi record che, a richiesta, sono stati modificati manualmente dagli ufficiali d'anagrafe. 

Restiamo in attesa di un riscontro, grazie

**Comment by amollicone1982** [comment]
In tali casi è necessario effettuare una rettifica indirizzo su ANPR richiamando il servizio di Mutazione famiglia/convivenza (5001) con tipomutazione = 9 rettifica integrazione indirizzo alla data di decorrenza della residenza della famiglia.

**Comment by franthemanIT** [comment]
prendo nota.
specifico pero' che non si tratta di UNA famiglia, ma di tutta la popolazione residente, c'e' stato proprio un misundestanding in fase di mappatura.

**Comment by amollicone1982** [comment]
Si infatti nel 5001 specifica solo la famiglia

**Comment by AMonopoliADS** [comment]
salve.
non vorrei si creasse un malinteso riguardo questa segnalazione.

pertanto aggiunto, per completezza, che la questione dell'INTERNO da spostare nel NUI è aperta (tramite contatti mail) già dal mese di marzo, ed è andata avanti tutti questi mesi senza arrivare ad una soluzione definitiva.
dopo tutti questi mesi, il suggerimento di operare via web-service è un po' una novità! soprattutto per il fatto che, come segnala il cliente, il "problema" non è di una singola famiglia, ma - per essere un po' più precisi - di circa 22000 famiglie in anagrafe. 

se pensate che questa sia la soluzione migliore, possiamo anche mettere in piedi un sistema di invio massivo di 22000 comunicazioni di tipo 5001 (che, probabilmente, genereranno storico lato ANPR?)... ma mi domando (e se lo chiede anche il cliente): non c'è proprio nessuna altra soluzione che potete proporre per sistemare il dato direttamente negli archivi di ANPR?

grazie.
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
L'aggiornamento tramite web-service è necessario affinché sia permesso l'allinemaento dell'indirizzo con tutti gli enti interessati.

**Comment by franthemanIT** [comment]
Buongiorno,
ringrazio intanto per le tempestive indicazioni, anche se probabilmente l’issue è stata dichiarata chiusa con eccessiva precipitazione.

Ricapitolando, ci è stato indicato di provvedere in autonomia alla correzione dell’errore di migrazione utilizzando il servizio 5001 con tipoMutamento 9, indicando come dataDecorrenza quella “di decorrenza della residenza della famiglia”.

Segnaliamo intanto che per il tipoMutamento 9 non siamo stati in grado di reperire documentazione, ma abbiamo solo rilevato che il tipo 9 è stato aggiunto in tabella 46 a marzo 2019.

Per il Comune di Rivoli è prioritaria la correttezza del dato presente nella banca dati nazionale, da cui discende naturalmente l’allineamento degli altri enti che ne estraggono dati.

E' chiaro che l''errore vada corretto, anzi, è passato fin troppo tempo. E' altrettanto chiaro che, qualunque sia la strada che si seguirà, l'intervento massivo sul registro vada documentato per garantire la correttezza giuridica e documentale del registro d’anagrafe. 

Il Comune ha quindi necessità di capire con certezza quali effetti abbia sul documento-registro operare una correzione complessiva via servizio 5001 degli indirizzi di tutte le 22000 famiglie residenti. Risulterà una migrazione interna di massa? Sembrerà che ci sia stata una revisione totale dell'onomastica e della numerazione? La famiglia risulterà aver cambiato indirizzo/residenza? Cosa comparirà sui certificati storici? L'indirizzo rettificato oblitererà quello mal composto? I due indirizzi coesisteranno, uno come variante dell'altro?

Elenco per punti gli aspetti da chiarire. 

1. Nella documentazione il servizio 5001 "offre la possibilità di modificare una scheda famiglia o convivenza, di modificarne l’intestatario/responsabile, di variare il motivo di costituzione o la specie, di variarne la composizione e la residenza, di comunicare il ripristino di un indirizzo antecedente al subentro, di variare l’indirizzo di residenza in Italia in seguito ad una revisione dell’onomastica stradale effettuata dal comune. Tali cambiamenti non implicano una variazione del numero dei componenti della scheda famiglia o convivenza, solo una nuova attribuzione di intestatario/responsabile e nel caso l’aggiornamento del rapporto rispetto ad essi" .
Le casistiche di uso del servizio fanno quindi tutte riferimento a un accadimento reale nella vita della famiglia (incluso che il comune cambi nome alle strade). Non si fa riferimento alla “rettifica” contenuta nella descrizione sintetica del tipoMutamento 9.
**Nel nostro caso si tratta della necessità di correggere un errore materiale** commesso in fase di compilazione del registro.
Richiesta 1.A) Ci serve **conferma che il tipo 9 è pensato espressamente per correggere errori materiali** di compilazione del registro d’anagrafe e non crea una reale mutazione nella famiglia, visto che in questo caso non muta niente ma si corregge solo un indirizzo scritto male;
Richiesta 1.B) Si producono effetti sulla storia della famiglia? Se sì, quali?

2. In assenza di documentazione, Alessandro Monopoli, che ha commentato questa issue poco sopra per la software house ADS che ci fornisce l’applicativo d’anagrafe, ha effettuato alcune prove in ambiente di test per sciogliere alcuni dubbi relativi alla data di decorrenza dell’indirizzo, visto che i componenti della famiglia possono essere entrati nella famiglia in date diverse (per matrimonio, per nascita ecc.). Ecco la sua relazione:
“In generale, il servizio 5001 si aspetta come dataDecorrenza una data coerente con tutte quelle dei soggetti presenti nella famiglia, per cui non è possibile indicare una data antecedente alla più recente tra tutte quelle dei componenti del nucleo. Ho provato anche tipoMutazione '4' e '7' che sono "rettifica indirizzo" e "revisione onomastica".
Nel caso di una famiglia con:
- I.S. (intestatario scheda/ capo famiglia) residente dal 2016;
- moglie entrata nel 2017;
- figlio nato nel 2018,
la comunicazione **con tipo 4 o 7** va a buon fine con dataDecorrenza >= 2018, e **l'operazione produce l'aggiornamento di tutte le date decorrenza, allineandole a quella comunicata**.
**Il tipoMutazione '9' è l'unico che fa eccezione** rispetto a questo ragionamento.
La comunicazione va a buon fine solo indicando come dataDecorrenza la minore (cioè la più antica/meno recente) tra tutte quelle dei componenti del nucleo.
Il tipoMutazione 9 non produce aggiornamento della dataDecorrenza, ma solo degli elementi dell'indirizzo.”
RICHIESTA 2) Si chiede **conferma che come dataDecorrenza si debba indicare la data meno recente** fra quelle di decorrenza della residenza dei componenti della famiglia.

3. Gestione dello storico. Il servizio 5001 sembra consentire di intervenire solo sugli indirizzi attuali e non sullo storico degli indirizzi (dal momento di subentro a oggi). **Per modificare lo storico di indirizzi non più attuali ci sembra necessario un intervento di chi gestisce il database di ANPR.**
RICHIESTA 3) **Come si può pensare di correggere il dato storico?**


Ribadiamo come, in assenza di documentazione riguardo la modalità di intervento suggerita, sia fondamentale conoscere con esattezza gli effetti sul piano documentale e giuridico delle comunicazioni inviate.

Grazie per l’attenzione.

**Comment by amollicone1982** [comment]
Premessa: fino a qualche tempo fa la rettifica massiva di indirizzi era permessa tramite l'invio di un file csv contenente tutte le informazioni da rettificare. Tale soluzione è stata abbandonata da quando abbiamo collegato gli enti al sistema anpr.

punto 1: il servizio 5001 tipo mutazione 9 è stato pensato proprio per errori materiali al subentro

punto 2:  il servizio 5001 tipo mutazione 9 fa eccezione e confermo che si aspetta come dataDecorrenza la minore delle date decorrenza residenza dei soggetti appartenenti alla famiglia

punto 3: lo storico degli indirizzi non può essere modificato in quanto ha prodotto una notifica verso gli enti che non effettuano rettifiche su indirizzi storici

In ogni caso la rettifica dell'indirizzo oblitererà quello mal composto e non camparirà nello storico delle residenze. 

Relativamente alla mancanza di documentazione tsale servizio si invoca come un qualsiasi 5001 dove è obbligatoria la famiglia/convivenza ed è opzionale l'elenco dei soggetti.

Spero di aver risposto in modo chiaro e siamo a disposizione per ulteriori chiarimenti
