### ISSUE TITLE
Salvataggio del file in ATMOS fallita

### ISSUE THREAD

**Issue by raf-db** [italia/anpr#1748]
Errore nell'invio dei di presubrentro sia AIRE che APR per il comune di Bisaccia

**Comment by SAlberto** [comment]
Mi associo per il presubentro del comune di Palagonia, stesso problema

**Comment by busaster** [comment]
Anche noi, stesso problema da ieri per il comune di Rozzano

**Comment by vix-db** [comment]
Stesso problema per il Comune di Castelnuovo di Conza (SA).
La situazione sta diventando insostenibile...

**Comment by FilippoPapi** [comment]
il problema è risolto
