### ISSUE TITLE
Comune di Saponara Città Metropolitana di Messina -Errore caricamento file presubentro ANPR e da giorno 7 novembre che cerchiamo invano di caricare il file di presubentro "ERRORE Salvataggio del file in ATMOS fallita" abbiamo aperto numerose segnalazioni tramite il n. verde ma nessuno ci ha contattati abbiamo ripetutamente provato a caricare il file ogni giorno in diverse ore ma il problema persiste e continuiamo a rimanere bloccati si prega di darci soluzione a stretto visto che non abbiamo avuto notizie ne da sogei ne da anpr e i nostri tcnici dovranno essere pagati per queste giornate infruttuose

### ISSUE THREAD

**Issue by Saponara083** [italia/anpr#1750]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by FilippoPapi** [comment]
il problema è risolto potete riprovare
