### ISSUE TITLE
revoca dati matrimonio-ambiente test-WEB APP

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1751]
WEB APP - ambiente di test comune di Codroipo.
stiamo provando a revocare i dati di matrimonio per idanpr 26603553.
il cittadino non ha avuto variazioni  dopo il subentro.
Riceviamo l'errore Sezione dati matrimonio assente.
potete indicarci la modalità corretta per effettuare la revoca di questo dato? 
come tipo revoca abbiamo messo 6 - matrimonio e come motivo errore materiale
grazie.

**Comment by frmariani** [comment]
in ambiente di test per il Comune di Codroipo, non mi risulta l'errore da lei menzionato;
mi risulta come errore EN505 - l'operazione di revoca è possibile solo a valle del subentro.
per favore indichi l'idANPR dell'operazione fallita.
grazie

**Comment by INSIEL1** [comment]
'Sezione matrimonio non presente' è l'errore che esce dal portale dell'ambiente di test quando vado a fare la conferma dell'operazione.  da WEB APP l'operazione è fallita non ho un idanpr di operazione da inviarle.

**Comment by frmariani** [comment]
la procedura indicata è corretta;
per favore mi invii lo screenshot dell'errore ed un eventuale numero di telefono dove raggiungerla
frmariani@sogei.it
