### ISSUE TITLE
ws 5008 - Errore: Individuate due posizioni in AT non unificabili

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1753]
Comune di Domodossola - Ambiente di produzione

Il comune di Domodossola deve provvedere ad un cambio di Cognome/Nome di un residente. 
E' stata effettuata la mutazione tramite il ws 5008 ma viene restituito l'errore "Individuate due posizioni in AT non unificabili". Abbiamo tentato di allineare e collegare i C.F. tramite la solita funzione da Risoluzione disallineamenti dalla WA di ANPR. Sia mettendo la spunta su collega CF che non mettendola l’errore è il medesimo.
Alla conferma del collegamento dei 2 C.F. (come da immagine 1 allegata) il sistema da errore 95 Operazione non effettuabile.
Abbiamo allora fatto una consultazione su AE dei 2 codici fiscali che si intendeva collegare e da come si vede nel pdf 3 allegato, il codice fiscale MHMHSN82A01Z34RL è collegato ad un codice fiscale (MHMHSN82A01Z345Q) di un altro soggetto (pdf n.4) che non c’entra nulla con il nostro residente in questione.

Abbiamo già contattato l'agenzia delle entrate all'indirizzo email `entrate.archivioanagrafico@agenziaentrate.it` i quali ci hanno risposto di contattare prima il call center di Sogei e di farsi aprire un ticket, e loro ci hanno detto di scrivere qui.

Restiamo in attesa di un riscontro in merito.

Grazie
Mauro Maccagno
Siscom SPA

Allegati:
![1-MHMHSN82A01Z34RL](https://user-images.githubusercontent.com/28776141/68778246-332e6a00-0633-11ea-9949-d6f3fa1e6294.JPG)
[2-BDLHSN82A01Z345G.PDF](https://github.com/italia/anpr/files/3841969/2-BDLHSN82A01Z345G.PDF)
[3-MHMHSN82A01Z34RL.PDF](https://github.com/italia/anpr/files/3841971/3-MHMHSN82A01Z34RL.PDF)
[4-MHMHSN82A01Z345Q.PDF](https://github.com/italia/anpr/files/3841972/4-MHMHSN82A01Z345Q.PDF)

**Comment by frmariani** [comment]
Il CF MHMHSN82A01Z34RL , validato e marcato ANPR, è un omocodice, pertanto può essere trattato  soltanto dall'Agenzia delle Entrate;
ho provveduto ad aprire il ticket richiesto dalla Direzione Centrale di AE: ticket 20739544
scrivetemi appena AE avrà provveduto alla dovuta modifica
frmariani@sogei.it

**Comment by siscomanpr** [comment]
ok, grazie, comunichiamo ad AE il numero del ticket.
