### ISSUE TITLE
Salvataggio del file in ATMOS fallita

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1754]
Facendo riferimento alle issue #1744, #1748 
Il problema persiste anche questa mattina, non sembra capitare su base casuale, ma sistematicamente ad ogni tentativo, come a noi a moltissimi altri comuni e software house.
Cortesemente potreste fornirci una spiegazione da dare ai comuni che cominciano a risentire di questo disservizio?

Ringrazio anticipatamente

**Comment by FilippoPapi** [comment]
il problema è risolto
