### ISSUE TITLE
PRESUBENTRO ANCORA SALVATAGGIO IN ATMOS FALLITA

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#1755]
Buongiorno.
Nonostante rassicurazioni da Vs operatore numero verde che la cosa sarebbe stata risolta per 18 di ieri , ancora adesso l' upload NON funziona .  
Ho effettuato diversi tentativi poiche' mi dite che l' errore e' casuale , ma nonostante le 10 prove fatte ,continuo ad avere sempre errore .
Edoardo  Dona' <Edoardo.Dona@datamanagementitalia.it> 
338 59 09 376 
per comune di Borgo San Giovanni (prov. Lodi) che deve necessariamente subentrare martedi' prox. 
Saluti e Grazie

**Comment by FilippoPapi** [comment]
il problema è risolto
