### ISSUE TITLE
Domicilio digitale

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1756]
Buongiorno,
negli XSD del flusso 500x sono previsti i tag relativi al domicilio digitale. Sono già gestiti in ANPR o sono in previsione sviluppi futuri?
Se sono già gestiti, sono visibili anche da webapp? In caso affermativo, in quale sezione?
Grazie,
cordiali saluti.

**Comment by rvinzani** [comment]
Sono previsti i tag per sviluppi futuri. Non abbiamo ancora indicazioni dal Ministero
