### ISSUE TITLE
[Subentro 28/11/2019] Impossibile aggiungere nuovo Sindaco a seguito cancellazione precedente

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1758]
Buongiorno,
l'Ufficio Anagrafe di Romentino (NO) chiede, gentilmente, supporto per poter aggiungere una nuova utenza da assegnare al Sindaco attuale, soprattutto in vista del subentro in ANPR fissato per il 28/11/2019. In particolare, la webApp non consente di aggiungere un nuovo utente, dopo che il precedente Sindaco è stato cancellato. Aggiungo, inoltre, che il numero di utenti censiti inizialmente era pari a cinque, e che nel frattempo è stata cancellata anche un'altra utenza di un dipendente non più in servizio. In totale ora risultano 3 utenze attive. 

Servizi Locali SPA
Comune di Romentino (NO) 003131

**Comment by Leonforte** [comment]
Buongiorno,
l'unico utente presente aveva un problema sul profilo che è stato risolto ed è quindi ora autonomo nell'inserimento del nuovo utente Sindaco. Saluti

**Comment by Eduardo1977** [comment]
Grazie gentilissimo

**Comment by Eduardo1977** [comment]
Buongiorno, confermo che è stato appena inserito il nuovo sindaco e la pratica risulta in lavorazione.
Grazie per l'aiuto

**Comment by Eduardo1977** [comment]
Buongiorno, chiedo, gentilmente, se non risulta comunicata la data di subentro come indicano i messaggi nella WebApp, oppure se c'è qualche disallineamento:

![immagine](https://user-images.githubusercontent.com/27421449/69336082-5c1bb400-0c5e-11ea-980f-a29318fca751.png)

**Comment by Leonforte** [comment]
E' programmato per il 28.11. Il subentro è abilitato il giorno antecedente il suebntro. Forse il messaggio è fuorviante.

**Comment by Eduardo1977** [comment]
Si grazie. un po troppo direi
