### ISSUE TITLE
Registrazione dato Senza Fissa Dimora tramite servizi 5001 e 5005

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1759]
Buongiorno,

attraverso i servizi 5001 e 5005 è possibile aggiornare il dato riguardante lo stato di senza fissa dimora.

Il dato è acquisito dalla sportello al momento della dichiarazione di residenza del cittadino, è quindi logico inserirlo già in queste operazioni.

Rimaniamo in attesa di un gentile riscontro.

Roberta Biasi

Dedagroup

**Comment by frmariani** [comment]
Con il solo servizio 5005, è possibile inserire l'indirizzo di un cittadino senza fissa dimora, ma lo status di di cittadino "senza fissa dimora" si attribuisce con il servizio 5008 (Mutazione scheda) tipo mutazione 1 (Dati anagrafici/Codice fiscale).

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
