### ISSUE TITLE
[4005] formatoRichiesta mancante 

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1760]
Salve,
Abbiamo notato che nella risposta di una verifica stato 4005 associata ad una richiesta che aveva specificato il parametro 
> 

    <dettaglioDati>TUTTO</dettaglioDati>

risulta presente solo il campo formatoRisposta e non quello di formatoRichiesta.
Questo significa che basta controllare il valore di formatoRisposta perche anche la richiesta avrà lo stesso formato?
esempio: 
>
    <idOperazioneComune>1002SYNC1256630</idOperazioneComune>

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Buongiorno, il problema dovrebbe essere stato individuato e risolto per le future elaborazioni.
Saluti

Assistenza ANPR
