### ISSUE TITLE
Rettifica data iscrizione nel comune, decorrenza residenza e ingresso in famiglia per cittadino iscritto per nascita

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1761]
Rettifica data iscrizione nel comune, decorrenza residenza e ingresso in famiglia per cittadino iscritto per nascita

Da webapp utilizzando l'operazione Rettifche di tipo rettifica dati subentro non riusciamo a rettificare le date in oggetto per il cittadino Id scheda attribuito da ANPR 65322374 .

Il cittadino è stato erroneamente iscritto con data decorrenza 06/08/2019 mentre la corretta data decorrenza sia della residenza sia dell'iscrizione in Anpr sia dell'ingresso in famiglia corrisponde alla data di nascita 12/07/2019.

Attendiamo gentile riscontro

Roberta Biasi

Dedagroup

**Comment by frmariani** [comment]
Il cittadino è stato aggiunto in ANPR con un'operazione di Iscrizione per nascita, quindi non è possibile utilizzare le funzioni di Rettifica dati subentro (utilizzabile appunto solo per i cittadini aggiunti in ANPR con il file di subentro);
con la funzione Rettifica dati iscrizione è possibile rettificare soltanto il motivo iscrizione e la provenienza.
Nel vostro caso dovete annullare l'operazione di Iscrizione per nascita ed rifarla con le date corrette

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
