### ISSUE TITLE
Aggiornamento campo Tipo Elettore in ANPR

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#1763]
Si richiede a tutti i comuni subentrati di aggiornare tempestivamente il campo “**Tipo elettore**” con riferimento ai soggetti residenti all’estero in quanto l’assenza di tale informazione non consente l’inserimento di tali soggetti nell’**elenco elettori**. Il mancato inserimento dei soggetti a causa della mancata valorizzazione del campo “tipo elettore” comporta per i Comuni lo svolgimento di un ulteriore adempimento che consiste nella predisposizione degli elenchi aggiuntivi con conseguente aggravio di lavoro”.   Particolare rilievo assume anche la correttezza del dato relativo all’indirizzo estero, fondamentale ai fini del recapito del certificato elettorale ai medesimi elettori. 
Si ricorda alle case software che la funzionalità di aggiornamento della posizione elettorale deve essere assicurata dai gestionali.
Si allega ad ogni buon conto una piccola guida per poter effettuare l'operazione di aggiornamento dal sito web di ANPR 
[Aggiornamento campo Tipo Elettore in ANPR.pdf](https://github.com/italia/anpr/files/3850667/Aggiornamento.campo.Tipo.Elettore.in.ANPR.pdf)

**Comment by Eduardo1977** [comment]
Buongiorno, potete indicare qual'è il modo più corretto per estrarre da WebApp l'elenco di tutti i soggetti residenti all’estero? Grazie

**Comment by INSIEL1** [comment]
e' previsto un aggiornamento massivo tramite file? non ho trovato specifiche in merito. grazie

**Comment by rvinzani** [comment]
@Eduardo1977 Dalla WebApp è possibile richiedere un elenco ad esempio per i soggetti risiedenti all'estero e con un età compresa tra 18 e 100 anni

**Comment by rvinzani** [comment]
@INSIEL1 no, non è previsto

**Comment by AMonopoliADS** [comment]
ci fanno notare che l'elenco "Soggetti con tipo elettore non valorizzato" evidenzia tutti i soggetti iscritti per motivo "iscrizione aire per nascita", che sono ancora minorenni oppure iscritti di recente, in attesa di revisione elettorale.
considerato che il servizio 'A001' non prevede la comunicazione del flag "elettore" (immagino, perchè si presume che sia sempre 'N'), si può evitare che vengano estratti come anomalie?
(magari assegnando la 'N' di default o quantomeno escludendo i minorenni dal controllo?)

grazie.
Alessandro Monopoli ADS

**Comment by Amucciarelli74** [comment]
Abbiamo verificato a campione sui comuni subentrati nostri clienti, che con il popolamento dell'AIRE il campo “Tipo elettore” è stato correttamente movimentato per i soggetti residenti all'estero.
Immaginiamo pertanto che la problematica da voi sollevata riguardi i cittadini AIRE iscritti o cancellati dopo il subentro del comune, in quanto al momento dell'iscrizione il cittadino non è ancora un elettore (lo diventerà alla prima revisione utile).
Chiediamo pertanto se è corretto aggiornare tale campo in fase di revisione, dinamica o semestrale, delle liste elettorali.

Grazie,
Giuseppe Mucciarelli, TINN srl.

**Comment by ncapozzi** [comment]
Buongiorno,
il problema principale ai fini dell'elaborazione dell’elenco unico sono i cittadini maggiorenni per i quali il Tipo elettore non è valorizzato in ANPR e pertanto non è possibile sapere se sono ancora ELETTORI oppure NO oppure hanno PERSO IL DIRITTO DI VOTO. 

Per un aggiornamento massivo è possibile richiamare il WS 5008 con tipo mutazione = 5 Liste e il campo ELETTORE = S, N o P.

Per i soggetti minorenni nell'elaborazione dell'elenco unico il tipo elettore sarà valorizzato automaticamente a N.

N. Capozzi

**Comment by ncapozzi** [comment]
Buongiorno,

si specifica che per i soggetti minorenni nell'elaborazione dell'elenco unico il tipo elettore sarà valorizzato automaticamente a N solo se non valorizzato.

N. Capozzi
