### ISSUE TITLE
Problemi accesso WebApp con smart card sindaco

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1764]
Comune di Massiola (VB)

Il comune in oggetto subentrerà nelle prossime settimane e li stiamo seguendo nell'attivazione delle smart card. 
In seguito all'installazione del driver della smart card, cercando di aprire la WA di anpr, dopo la selezione del certificato di postazione, appare l'errore in allegato
![errore portale](https://user-images.githubusercontent.com/28776141/68938504-d059e180-079e-11ea-810b-ef792688b8ce.PNG)

I certificati risultano correttamente installati come si può vedere da questi altri allegati:
![certificato utenti](https://user-images.githubusercontent.com/28776141/68938569-e9629280-079e-11ea-84c1-017daf95dd90.PNG)
![certificato 1](https://user-images.githubusercontent.com/28776141/68938570-e9629280-079e-11ea-87a2-c37410d1a8c3.PNG)
![certificato postazione](https://user-images.githubusercontent.com/28776141/68938573-e9629280-079e-11ea-8d6f-dd35781f78df.PNG)

Il certificato di postazione è attivo e funzionante visto che il test di connessione tramite ws funziona correttamente. Sembra essere un problema di smart card.
Abbiamo provato su più postazioni e l'errore è lo stesso.

Restiamo in attesa di un riscontro in merito. Grazie.

SISCOM SPA

**Comment by Leonforte** [comment]
Salve, potrebbe essere il certificato contenuto nella SC.
Avete due scelte :
1) provate ad accedere con la SC dell'amministratore di primo livello che risulta attiva
2) Entrate con utente e password
Nel caso fosse la SC occorrerà da gestione smart card richiederne una nuona, saluti

**Comment by siscomanpr** [comment]
La smart card dell'operatore PLTMRS65P43G062O funziona senza errori per l'accesso alla web app, ma non ci fa abilitare i profili essendo un semplice operatore.
L'accesso con Utente e Password lo tenteremo lunedì se è l'unica altra soluzione, anche se avevo capito che sull'ambiente di produzione questo tipo di accesso fosse stato disattivato.
Per richiedere una nuova sc per il sindaco come dobbiamo procedere?

**Comment by Leonforte** [comment]
I profili dell'operatore su indicato sono stati aggiornati da centro anche per il subentro ed è stata richiesta una nuova smart card per il Sindaco, saluti
