### ISSUE TITLE
CAMBIO CODICE FISCALE E DATA DI NASCITA 

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1765]
cittadino in anpr con c.f. numerico data di nascita xx/xx/xxx devo modificare con  c.f. alfanumerico con data di nascita xx/yy/xxxx mi da errore ...come faccio
--idOperazioneANPR 153739384 (Codice: EN527)
grazie

**Comment by ncapozzi** [comment]
Buonasera,
i dati anagrafici di un codice fiscale numerico provvisorio non possono essere modificati. E' necessario attendere che Agenzia delle Entrate attribuisca il CF alfanumerico definitivo.

N. Capozzi

**Comment by filippo1961** [comment]
Buongiorno,
quello che chiedo è che il cittadino ha caricato nell'anagrafe tributaria (agenzia delle entrate) due posizioni con uguali dati anagrafici, una con un c.f. numerico ed una con c.f. alfanumerico, in ANPR con c.f. numerico, di conseguenza dovrei variare ed unificare in ANPR il c.f. da numerico in alfanumerico.
Grazie

**Comment by ncapozzi** [comment]
Buongiorno, 
può comunicarmi per favore un recapito relefonico?

**Comment by filippo1961** [comment]
0923993382






Comune di Marsala 
Ufficio Anagrafe 
L'ufficiale d'anagrafe 
Filippo Asaro 
Tel: 0923993382
email: asaro.filippo@comune.marsala.tp.it 
email: protocollogenerale@comune.marsala.tp.it 
pec: protocollo@pec.comune.marsala.tp.it    

_______________________________________________________________________________________________________________________________________________________________________________ 

Le informazioni contenute nella presente e-mail ed eventualmente negli allegati possono essere confidenziali e sono comunque riservate al destinatario della stessa. La loro comunicazione, diffusione, copiatura da parte di terzi e' proibita. Se avete ricevuto questa comunicazione per errore, Vi preghiamo di informare immediatamente il mittente del messaggio e di distruggere il messaggio. Si avvertono i destinatari che tutti i messaggi di posta provenienti dal dominio @comune.marsala.tp.it hanno natura aziendale e non personale e pertanto potranno essere conosciuti dall'azienda. 

This transmission is intended for the use of the addressee only and is confidential and may be the subject of privilege and exempt for disclosure. Any extraction, distribution, copying or use of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone and then return the original message and attachments to us at the above address. 




Da: "ncapozzi" notifications@github.com
A: "italia/anpr" anpr@noreply.github.com
Cc: "filippo1961" asaro.filippo@comune.marsala.tp.it,"Author" author@noreply.github.com
Data: Mon, 18 Nov 2019 01:34:10 -0800
Oggetto: Re: [italia/anpr] CAMBIO CODICE FISCALE E DATA DI NASCITA  (#1765)


Buongiorno,


può comunicarmi per favore un recapito relefonico?
