### ISSUE TITLE
[1013] Annullamento comunicazione 1002 - Errore EN077

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1766]
ambiente di PRODUZIONE - comune di BAGHERIA (082006)

tentiamo di annullare l'iscrizione con idOperazioneComune 2019017625 (ws 1002), ma il sistema risponde con errore
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN077</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa</testoErroreAnomalia>
  </errore>
  <errore>
    <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-18 15:38:15 , idOperazioneANPR 154706226</testoErroreAnomalia>
  </errore>
</listaErrori>
```

non capiamo quali altre operazioni bloccano l'annullamento.
grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, abbiamo individuato il problema che dovrebbe essere corretto dalla prossima patch, la cui data prevista di disponibilità è il 28 Novembre 2019.
Saluti
Assistenza ANPR
