### ISSUE TITLE
impossibile modificare decorrenza iscrizione

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#1767]
Comune subentrato ANPR dal 10.06.2019. Iscrizione di famiglia AIRE a seguito di registrazione dei relativi atti di nascita e matrimonio. Per errore l'IS (e solo lui) ha una data di decorrenza iscrizione errata. Sul gestionale Halley tale dato è stato corretto. Il dato continua ad essere erroneo in ANPR. Contattata Halley mi riferiscono che deve provvedere Sogei in quanto il dato non è da loro accessibile. Contattata SOGEI mi dicono che deve provvedere Halley. Ricontattati entrambi sembra invece che si debba cancellare e reiscrivere l'intera famiglia... ma cancellandola e reiscrivendola dal gestionale il problema si ripresenta. Mi sembra francamente assurdo che la data di decorrenza dell'iscrizione sia un dato immodificabile su ANPR, anche con la funzione "mutazione dati AIRE". Ci sono altre soluzioni?

**Comment by rvinzani** [comment]
Per aggiornare la data di iscrizione è necessario annullare l'operazione ed effettuarla nuovamente con i dati corretti.  Può fornire maggiori indicazioni (es idOperazioneANPR) della reiscrizione che ha generato lo stesso problema?

**Comment by fcastellani81** [comment]
Buongiorno,
stesso problema per altro Comune:
ho necesstità di annullare le due operazioni presenti in un cittadino nel quale vi è la data di iscrizione AIRE errata:
operazione 149751278 - iscrizione per altri motivi aire del 7/11/2019
operazione 149755638  aire mutazione del 7/11/2019
Provando ad annullare la mutazione aire mi segnala il seguente errore:
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077)
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-19 10:07:23 , idOperazioneANPR 155000517 (Codice: EN527)

Mi potete indicare quali sono le operazioni successive? Nella stessa famiglia sono stati iscritti nella stessa data altre due persone: si tratta della loro iscrizione?
In caso affermativo vi chiedo quali operazioni è necessario annullare. Grazie

**Comment by rvinzani** [comment]
Potete per favore provare ad annullare nuovamente le due operazioni (mutazione AIRE 149755638 ed iscrizione AIRE 149751278)

**Comment by rvinzani** [comment]
Chiudo la issue. In caso il problema non fosse ancora risolto si prega di aprire una nuova issue che faccia riferimento a questa stessa
