### ISSUE TITLE
Convivenze

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1769]
Buongiorno
vorremmo ricevere chiarimenti in merito alle convivenze :

Per noi esistono due tipi di convivenze le convivenze affettive e quelle non affettive. Le convivenze di fatto in quale fattispecie rientrano ?

Abbiamo il tag famiglia, il tag convivenza ed il il tag convivenzaDiFatto, potete chiarire ?

Grazie

**Comment by frmariani** [comment]
Per "conviventi di fatto" si intendono due persone maggiorenni unite stabilmente da legami affettivi;
in questo caso dovrete utilizzare il tag "convivenzaDiFatto" per indicare i dati della convivenza affettiva, quindi dati anagrafici del convivente ed i riferimenti del contratto di stipila.

Un cittadino deve far parte di una Famiglia o appartenere ad una Convivenza (comunità religiosa ecc..): nel primo caso utilizzerete il tag Famiglia, nel secondo caso utilizzerete il tag Convivenza.

**Comment by GabriellaBallabio** [comment]
Quindi nel caso di 
- una persona CONIUGATA creo solo il tag "famiglia"
- una persona MEMBRO DI UNA CONVIVENZA (religiosa) creo solo il tag "convivenza"
- una persona CONVIVENTE (con legami affettivi) creo solo il tag "convivenzaDiFatto" oppure sia il tag "famiglia" che "convivenzaDiFatto" ???

**Comment by frmariani** [comment]
Cercherò di essere più chiara, ma nel caso mi lasci un recapito telefonico dove poterla raggiungere per le vie brevi.
lo stato civile prescinde dall'appartenenza ad una famiglia/convivenza:
un soggetto con stato civile "coniugata", può appartenere ad una famiglia o ad una convivenza (le carceri sono piene di persone coniugate);
la convivenza di fatto è come il matrimonio o l'unione civile, è il rapporto giuridico tra due persone;

Il Regolamento Anagrafico, prevede che un cittadino debba appartenere necessariamente ad una famiglia o ad una convivenza: in quest'ultimo caso non parliamo di convivenza di fatto ma di comunità religiose, caritas, carceri ecc... 

Quindi, per rispondere alle sue domande...
una persona CONIUGATA creo solo il tag "famiglia"
RISP
una persona coniugata (stato civile) può appartenere ad una famiglia o ad una convivenza

una persona MEMBRO DI UNA CONVIVENZA (religiosa) creo solo il tag "convivenza"
RISP 
SI, perchè "Membro della convivenza" è un grado di parentela proprio della convivenza e non uno stato civile come nel caso precedente;

una persona CONVIVENTE (con legami affettivi) creo solo il tag "convivenzaDiFatto" oppure sia il tag "famiglia" che "convivenzaDiFatto" ???
RISP
anche in questo caso "Convivente con legami affettivi" è un grado di parentela proprio della famiglia, quindi deve essere presente il tag famiglia ma non necessariamente il tag "convivenzaDiFatto" (due persone possono convivere senza aver stipulato un contratto di convivenza)

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
