### ISSUE TITLE
UTILITA' - NOTIFICHE WEBAPP

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1770]
Buongiorno,
COMUNE DI CASERTA - 061022
Abbiamo provato sulla webapp, con credenziali e smart-card operatore, in ambiente PROD per verificare eventuali notifiche da parte di consolati (come da circolare) ma l'area non è accessibile. Mentre e' accessibile in ambiente TEST.

**Comment by fferraguto** [comment]
Salve,
probabilmente è sufficiente che l’amministratore locale della sicurezza (ALS) effettui l'abilitazione alla funzionalità desiderata.

**Comment by rinonasti** [comment]
L'accesso è stato fatto proprio dall'ALS

**Comment by fferraguto** [comment]
L'ALS dovrebbe entrare nella console di sicurezza ed abilitare alla funzionalità di Utilità e Notifiche la persona desiderata.
E' questo che non riuscite a fare?

**Comment by rinonasti** [comment]
domani faccio riprovare e saprò essere più preciso.
Grazie

**Comment by rinonasti** [comment]
ALS non riesce a gestire i profili in modifica errore: 
"Per proseguire è necessario selezionare almeno un profilo" 
nell'elenco a tendina non compare alcun profilo.
Questo anche sul suo profilo.

**Comment by rinonasti** [comment]
Gestire Utenze.
sulla sua utenza compare tipo "operatore" e non ALS
