### ISSUE TITLE
Eliminazione dati - revoca paternità/maternità

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1771]
Buongiorno,
sto testando in ambiente di Test il servizio di revoca (5013).
Riscontro che, per quanto riguarda la revoca dei dati della paternità o maternità, ho un risultato differente rispetto alla revoca di altri dati esempio:
Se revoco la paternità con decorrenza 19/11/2019, rimuove il dato a decorrere dal giorno richiesto ma lo presenta consultando la scheda in data precedente.
Quindi non capisco perché la revoca della paternità/maternità non sembra rimuovere completamente i dati, a differenza delle altre revoche.

Maggioli Informatica

**Comment by frmariani** [comment]
Rispetto alle altre, l'operazione di revoca della paternità e della maternità, può essere effettuata sia per errore materiale effettuato in fase di subentro che per effettiva revoca della podestà genitoriale: in quest'ultimo caso, la data da cui decorre la perdita della podestà genitoriale risulta un elemento fondamentale da tracciare.
