### ISSUE TITLE
[4005] Elaborazione bloccata

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1772]
Salve,

Facendo riferimento all' issue #1726, abbiamo riprovato mote volte a sottomettere nuovamente l'elaborazione, ma il servizio sembra bloccato e non riporta la lista delle operazioni eseguite nel periodo di riferimento.
La richiesta rimane da una settimana in elaborazione e non riusciamo a capire se si tratta di qualche sbaglio nei parametri che abbiamo messo oppure l'ambiente di test non è simile a quello di produzione.
La domanda che poniamo in questo caso sarebbe questa:
Esiste un ambiente di Test-Comuni (https://wstest.anpr.interno.it) per un comune che ha gia fatto il subentro?
Tenendo presente il fatto che l'ambiente Test di un comune fittizio non funziona non sappiamo come testare le funzionalità del servizio 4005 Verifica Stato.

Saluti,

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Salve, ora la situazione dovrebbe essere ripristina anche nell'ambiente che state usando con il comune fittizio.
L'ambiente di test comuni esiste, ma solo i comuni vi hanno accesso. 
Le software house devono rivolgersi ad un comune loro cliente per ottenere in caso la possibilità di utilizzarlo.
Saluti

Assistenza ANPR

**Comment by AlbanaCelepija** [comment]
Grazie del riscontro,
vedo che qualcosa è cambiato nell'ambiente del  comune fittizio, quindi la data disponibilità non viene rimandata, rimane sempre la prima che il sistema ha generato, però non riceviamo le operazioni.
Anche se stiamo facendo la verifica in un orario che ha il valora più grande della data disponibilità, la lista delle operazioni non è presente.
