### ISSUE TITLE
[subentro] Indirizzo con solo Toponimo (senza Specie)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1773]
caso di cliente in attesa di subentro in produzione.

alcune famiglie risiedono in indirizzi che hanno la seguente struttura:
"nome della frazione" + "toponimo" (in genere località o case sparse)

non essendo il campo "specie" obbligatorio, il cliente ha chiesto di popolare l'ANPR (al momento in pre-subentro) con il solo toponimo - quindi senza specie - per dare continuità al formato dell'indirizzo in sede di certificazione.

tutte le posizioni così popolate (in pre-subentro) ritornarno l'anomalia:
EN524 | Nell'indirizzo principale relativo alla famiglia non sono presenti ne' la descrizione della specie ne' il codiceSpecie

si chiede se questa anomalia in qualche modo possa compromettere la gestione delle schede interessate oppure se possiamo assecondare la richiesta del cliente senza problemi.

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
La richiesta del cliente deriva dal fatto che l'indirizzo non prevede la presenza della specie o perchè questa è presente all'interno del toponimo? In questo secondo caso sarebbe consigliabile normalizzare l'indirizzo come prevede il tracciato di ANPR

**Comment by AMonopoliADS** [comment]
scusate l'attesa, ma stiamo facendo delle valutazioni direttamente con il cliente.
per rispondere alla tua domanda, Roberta, ci sono entrambe le situazioni:
1. indirizzo con frazione e toponimo (senza specie)
2. indirizzo con frazione, specie e toponimo (specie contenuta nel toponimo)
per il primo caso, non vedo altre soluzioni al non passare la specie.
per il secondo caso, il cliente sta valutando di spostare l'indicazione delle frazione nel campo specifico, e dividere di conseguenza specie e toponimo, ma chiediamo:
a fronte di un indirizzo di questo tipo 
LOCALITA' PALAZZINA N.14 - Frazione: ANTISCIANA
che cosa arriverà all'agenzia delle entrate?
grazie

**Comment by rvinzani** [comment]
Come già risposto nella issue #1776 
Agenzia delle Entrate attualmente, al momento del subentro, acquisisce da ANPR le informazioni relative all'indirizzo concatenandole in uno o più stringhe. Sappiamo però che è in atto un intervento per acquisire le informazioni anche al momento del subentro in modalità normalizzata cioè differenziando i singoli campi. E' previsto inoltre un recupero degli indirizzi acquisiti con la precedente modalità

**Comment by AMonopoliADS** [comment]
come nella issue #1776 , anche in passato il tema è stato affrontato con particolare attenzione agli elementi del civico.
in questo caso ci interessa sapere come verrà gestito il campo "frazione" (che a livello di tracciati è un tag a sè all'interno dell'indirizzo) e se anche gli enti collegati (AE e MCTC) lo useranno come elemento aggiuntivo dell'indirizzo nell'invio delle comunicazioni.
il cliente subentrerà il 17/12 e considerato che fino ad oggi ha indicato la frazione all'interno del toponimo vorremmo avere garanzia - sempre che deciderà di usare il campo "frazione" - che questa informazione venga usata allo stesso modo anche dagli altri enti.

grazie

**Comment by rvinzani** [comment]
Il tracciato fornito agli Enti, relativamente all'indirizzo è lo stesso utilizzato dai servizi di ANPR.  Non possiamo però dare noi indicazioni sull'utilizzo delle singole informazioni da parte di altri enti.
