### ISSUE TITLE
PROBLEMI CON ANNULLAMENTE RESIDENZA PER ACCERTAMETNO NEGATIVO

### ISSUE THREAD

**Issue by giuannitre** [italia/anpr#1774]
Buongiorno, sono Giovanni Trento dell'Anagrafe del Comune di Parabiago (Mi).
Ho un problema che non so risolvere con una notifica di annullamento residenza per accertamento negativo da parte del Comune di  Milano.
Prima che arrivasse la notifica la famiglia di appartenenza è ulteriormente cambiata e mi da 
errori in allegato.
Come devo comportarmi?

[Errore bergantino.pdf](https://github.com/italia/anpr/files/3873546/Errore.bergantino.pdf)

**Comment by rvinzani** [comment]
Gent.le Sig.Trento, per problemi specifici come quello da lei riportato si deve rivolgere alla sua casa software se l'operazione viene effettuata tramite il suo gestionale ed al servizio di assistenza ANPR (800863116) se sta operando tramite web application.
