### ISSUE TITLE
S2003 data decorrenza cancellazione

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1775]
Buongiorno 
avrei bisogno di sapere cosa deve contenere il tag <dataDecorrenzaCancellazione> nel caso di pratiche di cancellazione per:
 - mancato rinnovo dimora abituale 
 - rinnovo permesso di soggiorno.

Da passati controlli questo tag doveva contenere la data dell'ultima iscrizione nel comune del cittadino.
Ad oggi questa impostazione è ancora valida?
Nonostante le comunicazioni non generino errori ci sono clienti che segnalano il fatto che mettere come data di cancellazione quella dell'ultima iscrizione nel comune non è corretto.
Grazie

**Comment by rvinzani** [comment]
Tecnicamente il servizio verifica che, per congruità delle informazioni, la data decorrenza dell'operazione di cancellazione non sia precedente ad una qualsiasi modifica effettuata sul soggetto. La data di cancellazione vera e propria invece è svincolata da tale principio e può essere impostata dal comune secondo le regole anagrafiche

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
