### ISSUE TITLE
Rettifica indirizzo di residenza : numero civico barrato interno

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1776]
Buongiorno
per il comune di caponago da poco subentrato nel tag relativo al numero civico per indicare via roma 16/3 int. 1 abbiamo inviato il seguente tag

<numeroCivico>
                     <civicoFonte>2</civicoFonte>
                     <numero>16</numero>
                     <lettera>3</lettera>
                     <esponente1>1</esponente1>
                 </numeroCivico>

Ora certificando da WA compare nell'indirizzo via roma 16 1 3. Come mai ? A cosa è dovuta l'anomalia ? 
Questo per tutti i cittadini ... come possiamo fare per modificare massivamente il dato ?
Evento MUTAZIONE 5014?
Leggendo la documentazione sembrerebbe di no ... allora quale metodo possiamo usare ?

**Comment by rvinzani** [comment]
Per correggere massivamente gli indirizzi è necessario utilizzare il servizio 5001 tipo mutazione 9. Tale servizio può essere richiamato ricorsivamente per tutte le famiglie che presentano l'errore. Può inviarci un numero di famiglia che presenta questo problema?

**Comment by GabriellaBallabio** [comment]
Buongiorno
il comune di caponago sostiene che ANPR ha inviato a Agenzia Entrate / Cassetto fiscale il dato del civico non corretto. Ma ANPR invia i dati di tutti i cittadini del comune all'agenzia delle entrate ? E' possibile che abbia invertito barrato e interno ?

Scausate ma l'ente chiede risposte.

**Comment by rvinzani** [comment]
Rinnovo la richiesta di avere un numero di famiglia di esempio che abbia presentato questo problema. Grazie

**Comment by GabriellaBallabio** [comment]
Scusi il ritardo ..

BONISSI ROSSELLA BNSRSL73B41F704Q risiede in Via C.A. DALLA CHIESA 16/3 INT 1, dicono che in ANPR compare 16 1 3.

Riporto il tag del file di subentro :

<numeroCivico>
                     <civicoFonte>2</civicoFonte>
                     <numero>16</numero>
                     <lettera>3</lettera>
                     <esponente1>1</esponente1>
                 </numeroCivico>

Restiamo in attesa di gentile riscontro.
Cordiali Saluti

**Comment by rvinzani** [comment]
In ANPR sono stati inviate le seguenti informazioni
numero: 16
lettera: 3
esponente1: 1 
forse dovevano essere popolati in tal modo:
numero: 16/3
interno1 = 1

**Comment by GabriellaBallabio** [comment]
Nel tag numero non è possibile inserire il carattere / ... non passa la validazione, la tipologia è numero al massimo di 20 cifre.
Ad ogni modo i dati in ANPR sono corretti, la certificazione è corretta, i dati sono errati nel cassetto fiscale, ripropongo la domando del precedente issue :
**"il comune di caponago sostiene che ANPR ha inviato a Agenzia Entrate / Cassetto fiscale il dato del civico non corretto. Ma ANPR invia i dati di tutti i cittadini del comune all'agenzia delle entrate ? E' possibile che abbia invertito barrato e interno ?"**

Resto in attesa di gentile riscontro.

**Comment by rvinzani** [comment]
Agenzia delle Entrate attualmente, al momento del subentro, acquisisce da ANPR le informazioni relative al civico accorpandole in un unico tracciato. Sappiamo però che è in atto un intervento per acquisire le informazioni anche al momento del subentro in modalità normalizzata cioè differenziando i singoli campi. E' previsto inoltre un recupero delle posizioni acquisite con la precedente modalità.  In tal modo le informazioni in AE verranno presenteae come inviate ad ANPR divisi in 
numero: 16
lettera: 3
esponente1: 1
