### ISSUE TITLE
[1002] EN185 + EN332 dati incongruenti e comune/provincia non valido

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1777]
Buongiorno, il comune di CASINA VALSASSINA - PRODUZIONE
tentando di iscrivere un soggetto cancellato ha prima errore EN185 per dati discordanti (ID OPERAZIONE 156420213) da un controllo mi sembra sia la provincia di nascita in ANPR LC ma alla data era CO.

provando quindi ad inviare con comune di nascita LC torna errore EN332 che il comune non è valido alla nascita (ID OPERAZIONE 156893636) 

ci è sfuggito qualche altro dato oppure il dato discordante è proprio il comune di nascita, in caso come si deve inviare?

grazie mille
Riccardo

**Comment by frmariani** [comment]
Il cittadino è stato precedentemente iscritto in ANPR con quanto contenuto nell'atto di nascita, quindi con una provincia non valida alla data di nascita;
il Codice Fiscale è stato anche  validato da Agenzia delle Entrate;
A questo punto, la re-iscrizione del cittadino deve contenere tutti i dati anagrafici congruenti alla precedente iscrizione, compreso il codice fiscale;
Il secondo tentativo fallisce semplicemente perchè avete omesso il Codice Fiscale.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
