### ISSUE TITLE
REVOCA DATO tipo 6 Matrimonio

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#1778]
Ambiente test comune di Codroipo.
stiamo testando dal gestionale la revoca dei dati matrimonio. riceviamo l'errore EN394-

Per il   tipo revoca 6 e' obbligatorio specificare il set di dati generalità per ricerca.

la comunicazione inviata è la n. 22690235

cosa sbagliamo?

**Comment by frmariani** [comment]
Dovete eliminare i dati del matrimonio nella richiesta;

Ci scusiamo per la descrizione fuorviante, la modificheremo al più presto.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
