### ISSUE TITLE
Web App - Titoli di soggiorno

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#178]
Ambiente di test - Data test 22/5/2017
Abbiamo notato che in caso di registrazione non viene effettuato alcun controllo di coerenza tra cittadinanza del soggetto interessato e titolo di soggiorno: ad esempio viene accettato l'inserimento di un permesso di soggiorno ad un cittadino italiano o comunitario, mentre la compilazione della sezione non è obbligatoria nel caso di cittadino straniero. Potrebbe essere molto utile creare questo tipo di legame per evitare qualsivoglia tipo di errore.
Lo stesso tipo di controllo sarebbe utile anche nella funzione di iscrizione nello schedario della popolazione temporanea.
Grazie,
Valentina Bocchino
Comune di Torino

**Comment by gcarbonin** [comment]
Mi sembra di ricordare che nei primi tempi questi controlli ci fossero poi siano stati tolti in quanto i dati sono pochi e molto vari. Ad esempio i comunitari non hanno un permesso di soggiorno ma qualche comune rilascia loro un altro documento (con pazienza posso cercare nelle mail di quasi due anni fa per essere più precisa), l'italiano potrebbe essere "divenuto italiano" da poco e avere il permesso di soggiorno come unico documento valido o il comune potrebbe ritenere utile acquisirlo comunque anche se non più necessario. Per lo straniero stiamo vedendo di mettere qualche controllo che mai potrà essere bloccante perché sicuramente uscirà una "normina" che deroga al principio generale.
