### ISSUE TITLE
Problema disallineamento con AE - Soggetto non rettificabile per errata indicazione del comune (codice 21)

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1780]
Buon giorno,
il comune di Alanno (subentrato) sta cercando di risolvere un disallineamento AE - ANPR di un cittadino nato negli Stati Uniti d'America; selezionando 'Conferma ANPR', ottiene però l'errore in oggetto ed in effetti nei dati mostrati a video, sia lato AE che ANPR, i campi Provincia di nascita e Comune di nascita (peraltro ininfluenti in questo caso ai fini del calcolo del CF) risultano vuoti. Ad una interrogazione ANPR tra l'altro la località estera di nascita del soggetto risulta correttamente valorizzata, per cui il cliente non sa come procedere per risolvere il disallineamento.
In attesa di riscontro, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by ncapozzi** [comment]
Buonasera,
potrebbe indicare l'idsoggettoANPR per le verifiche del caso?
Grazie
N. Capozzi

**Comment by Amucciarelli74** [comment]
Buon giorno,
l'id ANPR del soggetto é 77525077 (si tratta di un soggetto AIRE).
Grazie, restiamo in attesa di riscontro.
Cordiali saluti.

**Comment by ncapozzi** [comment]
Buongiorno,
devono effettuare una mutazione tutti i dati 5008 togliendo la virgola dalla descrizioneLocalita di nascita = SOMERVILLE, MA. Noto anche che il CF registrato sulla scheda ANPR è il collegato di un altro CF in Agenzia Entrate corrispondente ad un cognome diverso. Credo sia meglio se mi indicate un riferimento del Comune con cui parlare direttamente. Grazie

**Comment by Amucciarelli74** [comment]
Potete contattare il sig. Antonio Di Girolamo, referente del comune di Alanno, al numero 0858573101.
Grazie, 
cordiali saluti.

**Comment by ncapozzi** [comment]
E' stata fornita assistenza al Comune per aggiornare cognome e codice fiscale dall'applicazione WEB. Per future problematiche che richiedono di contattare il Comune si richiede cortesemente di far aprire direttamente al Comune un ticket al numero verde 800863116.

N. Capozzi

**Comment by Amucciarelli74** [comment]
Riporteremo al cliente la vostra comunicazione, in realtà vi abbiamo segnalato noi l'errore proprio perché dal numero verde hanno detto al referente del comune che per risolvere il problema la software house avrebbe dovuto contattarvi qui su Github. ..
Grazie comunque per il cortese riscontro,
cordiali saluti.
