### ISSUE TITLE
[webapp] errata dataRichiesta in XML operazione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1781]
In ambiente di test ho eseguito una iscrizione per altri motivi da WEBAPP alle 12:29 PM (mezzogiorno e 29).
L'operazione è andata a buon fine.
Quando però ne scarico XML sia con il servizio 4005 sia se lo consulto da webapp->monitoraggio operazioni il campo dataRichiesta vale 2019-11-22T00:29:00.000 , ovvero mezzanotte e 29.
Id operazione ANPR 22690863

**Comment by mttfranci** [comment]
Salve, l'operazione è registrata sui nostri sistemi all'ora da voi indicata (12.30 circa).
La data richiesta della testata, come tutte le altre date della testata è un valore che viene preso dal cliente senza manipolazioni (Vale a dire che serve solo come riferimento per i gestionali, al pare dell' id operazione comune).
Possibile che la configurazione della postazione sia all'origine dell'anomalia?
Saluti
Assistenza ANPR

**Comment by busaster** [comment]
la postazione ha la data correttamente sincronizzata via NTP

**Comment by mttfranci** [comment]
In input alla operazione anpr 22690863, come richiesta noi vediamo la data ora impostata 
alla mezzanotte. Quindi a noi risulta sia stata inviata così. Voi non avete il payload di quella operazione?


```
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:Richiesta1002 xmlns:ns2="http://sogei.it/ANPR/1000iscrizione">
      <testataRichiesta>
        <idOperazioneComune>0</idOperazioneComune>
        <codMittente>100004</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>1002</operazioneRichiesta>
        <dataOraRichiesta>2019-11-22T00:29:00.000</dataOraRichiesta>
```

**Comment by busaster** [comment]
purtroppo no
