### ISSUE TITLE
[4005] Operazioni Mancanti

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1782]
Salve,

Continuazione issue #1772.
Vediamo che qualcosa è cambiato nell'ambiente del comune fittizio, quindi la data disponibilità non viene rimandata, rimane sempre la prima che il sistema ha generato, però non riceviamo le operazioni.
Anche se stiamo facendo la verifica in un orario che ha il valore più grande della data disponibilità, la lista delle operazioni non è presente.

Quindi adesso il comportamento è uguale all' issue #1477.

Saluti

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Salve, 
Non avendo in questo caso `i` riferimento delle operazioni specifiche possiamo solo ipotizzare che si presenti una situazione simile a quella descritta nella issue #1714 
Vale a dire che venga usato lo stesso id operazione comune (potete verificare se l'id operazione ANPR della risposta cambia? Se non cambia non si tratta di una nuova risposta, ma del meccanismo per il quale a fronte di id operazione comune uguale viene restituita la sessa risposta).

Se la situazione non rientra nella casistica descritta, potreste postare la richiesta e la risposta (non dovrebbero esserci problemi dato che non ci sono dati sensibili).

**Comment by AlbanaCelepija** [comment]
Salve,
Esempi di richieste/risposte del flusso che usa il servizio 4005:

1.1) La richiesta di Elaborazione:
>

    <ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
    <testataRichiesta>
        <idOperazioneComune>ELB1001SYNC215748422001271</idOperazioneComune>
        <codMittente>888183</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4005</operazioneRichiesta>
        <dataOraRichiesta>2019-11-27T09:10:00.127+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>FREE</tipoInvio>
        <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
    </testataRichiesta>
    <elaborazione>
        <dettaglioDati>TUTTO</dettaglioDati>
        <ricercaElenchiRichieste>
            <statoLavorazione>2</statoLavorazione>
            <operazioneRichiesta>1001</operazioneRichiesta>
            <periodoRiferimentoRichieste>
                <dataOraIniziale>2019-11-01T07:00:00.000+01:00</dataOraIniziale>
                <dataOraFinale>2019-11-27T09:10:00.102+01:00</dataOraFinale>
            </periodoRiferimentoRichieste>
        </ricercaElenchiRichieste>
    </elaborazione>
   </ns2:Richiesta4005>
 
1.2) La risposta di elaborazione: 

>
    <ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
      <ns2:RispostaMultipla4005>
        <testataRisposta>
            <idOperazioneComune>ELB1001SYNC215748422001271</idOperazioneComune>
            <codMittente>888183</codMittente>
            <codDestinatario>ANPR02</codDestinatario>
            <operazioneRichiesta>4005</operazioneRichiesta>
            <dataOraRichiesta>2019-11-27T09:10:00.127+01:00</dataOraRichiesta>
            <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
            <idOperazioneANPR>2305884</idOperazioneANPR>
            <esitoOperazione>0000</esitoOperazione>
        </testataRisposta>
        <statoRichiesta>0</statoRichiesta>
        <idOperazioneANPR>2305884</idOperazioneANPR>
        <dataDisponibilita>2019-11-27T10:10:03.261+01:00</dataDisponibilita>
     </ns2:RispostaMultipla4005>
     </ns2:Risposta4005>

La data disponibilità in questo caso è : **2019-11-27T10:10:03.261+01:00**
L'id operazione ANPR della risposta è: **2305884**

2.1) La richiesta della prima verifica stato:
>

    <ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
      <testataRichiesta>
        <idOperazioneComune>VRF1001SYNC2157484640686416</idOperazioneComune>
        <codMittente>888183</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4005</operazioneRichiesta>
        <dataOraRichiesta>2019-11-27T10:20:06.864+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>FREE</tipoInvio>
        <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
      </testataRichiesta>
      <verificaStato>
        <idOperazioneANPR>2305884</idOperazioneANPR>
        <progressivo>1</progressivo>
      </verificaStato>
     </ns2:Richiesta4005>

2.2) La risposta della prima verifica stato:

>
      <ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
       <ns2:RispostaMultipla4005>
        <testataRisposta>
            <idOperazioneComune>VRF1001SYNC2157484640686416</idOperazioneComune>
            <codMittente>888183</codMittente>
            <codDestinatario>ANPR02</codDestinatario>
            <operazioneRichiesta>4005</operazioneRichiesta>
            <dataOraRichiesta>2019-11-27T10:20:06.864+01:00</dataOraRichiesta>
            <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
            <idOperazioneANPR>2306201</idOperazioneANPR>
            <esitoOperazione>0000</esitoOperazione>
        </testataRisposta>
        <statoRichiesta>1</statoRichiesta>
        <idOperazioneANPR>2305884</idOperazioneANPR>
        <dataDisponibilita>2019-11-27T09:10:14.000+01:00</dataDisponibilita>
       </ns2:RispostaMultipla4005>
   </ns2:Risposta4005>

La data disponibilità in questo caso è : **2019-11-27T09:10:14.000+01:00** (invece che 10:10 che ha restituito la risposta di elaborazione)
L'id operazione ANPR della risposta è: **2306201** , l'id operazione ANPR dell' elaborazione rimane la stessa: "**2305884**"

3.1) La seconda richiesta di verifica stato: 
>
      <ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
        <testataRichiesta>
        <idOperazioneComune>VRF1001SYNC2157484700780518</idOperazioneComune>
        <codMittente>888183</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4005</operazioneRichiesta>
        <dataOraRichiesta>2019-11-27T10:30:07.805+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>FREE</tipoInvio>
        <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
    </testataRichiesta>
    <verificaStato>
        <idOperazioneANPR>2305884</idOperazioneANPR>
        <progressivo>1</progressivo>
         </verificaStato>
    </ns2:Richiesta4005>

3.2) La risposta della seconda richiesta di verifica stato:
>
     <ns2:Risposta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
    <ns2:RispostaMultipla4005>
        <testataRisposta>
            <idOperazioneComune>VRF1001SYNC2157484700780518</idOperazioneComune>
            <codMittente>888183</codMittente>
            <codDestinatario>ANPR02</codDestinatario>
            <operazioneRichiesta>4005</operazioneRichiesta>
            <dataOraRichiesta>2019-11-27T10:30:07.805+01:00</dataOraRichiesta>
            <dataDecorrenza>2019-11-27+01:00</dataDecorrenza>
            <idOperazioneANPR>2306305</idOperazioneANPR>
            <esitoOperazione>0000</esitoOperazione>
        </testataRisposta>
        <statoRichiesta>1</statoRichiesta>
        <idOperazioneANPR>2305884</idOperazioneANPR>
        <dataDisponibilita>2019-11-27T09:10:14.000+01:00</dataDisponibilita>
      </ns2:RispostaMultipla4005>
     </ns2:Risposta4005>

La data disponibilità in questo caso è : **2019-11-27T09:10:14.000+01:00** , e non cambia più per tutte le verifiche successive.
L'id operazione ANPR della risposta cambia: **2306305**,  l'id operazione ANPR dell' elaborazione rimane la stessa: "**2305884**".

I valori delle idOperazioneComune non sono gli stetti, e anche le idOperazioneANPR delle risposte di verifica cambiano.
Questo è solo un esempio, ma da due mesi circa tutte le verifiche sono bloccate.
Mi viene il dubbio che forse dobbiamo fare le verifiche successive usando la nuova idOperazioneANPR  assegnata all' ultima verificha (nella testataRisposta), ma credo che in questo caso la risposta della verifica dovrebbe riportare anche nel body il nuovo valore.

Ringraziamo della vostra assistenza .

**Comment by mttfranci** [comment]
Salve, si avete fatto tutto corretto in effetti.
Dovremmo aver trovato e corretto il problema.
Potreste riprovare per cortesia?
Saluti

Assistenza ANPR

**Comment by AlbanaCelepija** [comment]
Salve,
adesso le richieste di verifiche stato contengono le operazioni.
Grazie
