### ISSUE TITLE
Comune di Brentonico TN - Mancata elaborazione file di subentro in ambiente di TEST COMUNI (SVILUPPO)

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1783]
Buona sera,

nel corso di questa mattina sono stati caricati i file di subentro sull’ambiente di test (sviluppo) del comune di Brentonico 022025

I file risultano ancora in stato IN ELABORAZIONE.

Potete verificare?

Grazie
Roberta Biasi
Dedagroup Public Services

**Comment by mttfranci** [comment]
Salve, al momento è presente un problema sull'elaborazione delle forniture da parte di Agenzia delle entrate.
Comunque il comune risulta subentrato e, a parte le operazioni che coinvolgono Agenzia delle entrate (che non sono dipendenti da ANPR) potete operare.

Saluti

Assistenza ANPR
