### ISSUE TITLE
Cancellazione eventi anagrafici famiglia 16616795 con decorrenza 29/10/2019

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#1784]
Buongiorno.
Il nostro ufficio anagrafe (cod. istat 108009) necessita di annullare tutti gli eventi anagrafici ccon decorrenza 29/10/2019 per la famiglia con codice 16616795, cioè relativamente a tutti i componenti:
30056729
68969516
68969517
68969518
68969515

Rimango in attesa di un vostro gentile riscontro.
I miei riferimenti sono:
Paltrinieri Andrea
Ufficiale d'Anagrafe del Comune di Biassono
e-mail: paltrinieri.andrea@biassono.org
tel. 039-2201060

cordiali saluti.
Andrea Paltrinieri

**Comment by frmariani** [comment]
contattato l'utente e risolta la problematica per il Comune di Biassono;
lasciati i riferimenti nel caso fosse necessaria l'assistenza per il Comune di Villasanta.
