### ISSUE TITLE
[4005] risposta non ancora pronta

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1785]
Ambiente di produzione, comune di Cadebosco

Abbiamo richiesto lo scarico delle operazioni effettuate dal 15/11 ad oggi alle 10:40.
Allo stato attuale lo scarico non è ancora pronto (id operazione ANPR 157757294).
Queste operazioni ci sono necessarie per il completamento dell'avvio del comune, che stiamo convertendo da precedente fornitore.

Avete una stima di quando potranno essere pronte ?
Ed in linea generale, che tempistiche ci dobbiamo aspettare per questo tipo di scarico ?

**Comment by mttfranci** [comment]
Salve, abbiamo verificato che la richiesta era pronta alle 18.00.
Come sapete ANPR solitamente cerca di generare queste elaborazioni in circa un'ora ma in caso di carico elevato (in particolare in orario di ufficio), può essere privilegiata la normale operatività.
In ogni caso in ambiente di produzione non ci risulta il tempo trascorso tra la richiesta e la generazione abbia mai superato le 12 ore, laddove il tempo limite previsto dai nostri livelli di servizio è di 24 ore.
Saluti

Assistenza ANPR
