### ISSUE TITLE
Lettori di Smart Card non vengono "letti\sentiti" dal sistema

### ISSUE THREAD

**Issue by sergiogedda** [italia/anpr#1787]
Ciao, su due clienti, tra l'altro postazioni nelle quali ero già entrato giorni fa… non riesco piu' ad entrare in webapp… 
il sistema legge correttamente il certificato
legge il cod. fiscale della smart card (quindi "sente" la smart card inserita)
ma al posto della richiesta pin mi viene restituito un messaggio d'errore:

Inserire la smart card

La smart card rilevata non è quella necessaria per l'operazione corrente. È possibile che la smart card in uso non disponga dei driver richiesti o di un certificato necessario

Gia rimosso i certificati…
Cambiato varie porte usb 
Reinstallato IDP Protector

**Comment by Leonforte** [comment]
Suggeriamo di effettuare le verifche del caso seguente le allegate istruzioni utilizzando i lettori forniti dal Ministero, saluti
[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/3896345/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)
