### ISSUE TITLE
[2009] Utente non abilitato in estinzione convivenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1788]
Ambiente di produzione, comune di San Giuliano Terme

Con una chiamata al servizio 2009 il comune tenta di estinguere una convivenza ma riceve l'errore "Utente non abilitato 5". L'id operazione ANPR ritornato è "0" , il codice di errore XXXX.

Informazioni sull'operazione da fornire in caso di assistenza : data 2019-11-26 15:50:47 , mittente 050031 , idOperazioneComune JD191126155149846

Riprovando la stessa operazione con lo stesso utente da WebApp è andata a buon fine.
Qual è la causa dell'errore nel servizio ?

Grazie

**Comment by frmariani** [comment]
Immagino che abbiate già controllato che l'utente sia abilitato;
per favore potete inviarci le prime tre lettere del CF che effettua l'operazione ?

**Comment by busaster** [comment]
le prime lettere del CF sono RMG

**Comment by frmariani** [comment]
I CF non ha l'abilitazione necessaria alla cancellazione delle convivenze;
deve avere il profilo di "Operatore Comunale Supervisore"

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
