### ISSUE TITLE
UTILITA' - NOTIFICHE WEBAPP #1770

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1789]
Faccio seguito alla issue #1770 per avere info in merito.
Grazie

**Comment by ncapozzi** [comment]
L'ALS può riprovare ad assegnare il profilo di Utilità e notifiche. Nel caso in cui il problema dovesse persistere l'ALS può contattare direttamente il nostro numero verde fornendo un recapito telefonico e la fascia oraria di reperibilità.

N. Caapozzi
