### ISSUE TITLE
Problematica Individuo con doppio codice fiscale in AE che non riesce ad ottenere la CIE

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1791]
Buongiorno,
giro la comunicazione di Fucecchio che non riesce a risolvere in ANPR la situazione di un individuo che ha bisogno del rilascio della CIE:

La signora identificata in ANPR con il n. 75158206 è iscritta nella nostra anagrafe con un codice fiscale validato che corrisponde alle generalità attualmente inserite in anagrafe.
Con queste generalità la posizione è subentrata in ANPR  il 6 novembre 2019.
Il 14 novembre la signora chiede la variazione del suo nome e cognome così come riportati nel nuovo passaporto.
Da una ricerca su punto fisco risultano due diversi codici fiscali riferiti alla signora non collegati tra di loro: uno con le vecchie generalità e uno con le nuove generalità.
Prima di procedere alla variazione delle generalità su ascotweb, abbiamo ritenuto di dover collegare i due codici fiscali. 
Abbiamo scritto all'agenzia delle entrate chiedendo di effettuare il collegamento tra i due codici fiscali, ma ci hanno risposto che non riuscivano a collegarli.
Andando in ANPR - utilità e notifiche - risoluzione disallineamenti con Agenzia delle entrate, abbiamo inserito come criterio di ricerca: sul primo campo il codice fiscale con i dati vecchi, sul secondo campo il codice fiscale con i dati nuovo, biffato "includi validati".  dopo aver aperto la posizione con la lente di ingrandimento il sistema propone a sx i dati dell'agenzia delle entrate corrispondenti alle nuove esatte generalità e a dx i dati di anpr con le vecchie generalità.  se si prova a cliccare sul tasto di sx "conferma AE" il sistema fornisce due messaggi di errore:
esito ANPR: individuate due posizioni in AT non unificabili (codice EAM9C)
esito ANPR: informazioni sull'operazione da fornire in caso di assistenza: data 2019-11-22 13:24:31, idOperazioneANPR 157137090 

Ringrazio
Carla Musian
Applicativo Ascotweb

Per
Comune Fucecchio
Dott.ssa Candida Brutti
Tel. 0571 268290
Responsabile Servizi Demografici

**Comment by frmariani** [comment]
Nell'ultima pagina descritta, poco sopra il tasto "Conferma AE", troverà un check "Collega codici fiscali": biffando il check,  visualizzerà un solo tasto "Conferma"; selezionandolo,  i codici fiscali saranno collegati e i dati anagrafici di Agenzia delle Entrate ricopriranno quelli presenti in ANPR.

**Comment by CarlaMusian** [comment]
Buongiorno,
il problema non e' ancora risolto.
L'utente segnala che:
"è esattamente quello che ho fatto ed è la manovra che che produce l'errore
nella descrizione qui sotto avevo dimenticato di dire che avevo biffato "collega codici fiscali"
come possiamo uscire da questa situazione? "

Si chiede di contattare direttamente il comune di Fucecchio.
Grazie
Carla Musian

**Comment by frmariani** [comment]
Ho contattato il Comune ed abbiamo risolto il problema: non è stata la selezione del collegamento codici fiscali  a produrre l'errore, ma soltanto un giustificato dubbio del Comune nel confermare l'aggiornamento dell'operazione.
