### ISSUE TITLE
Cancellazione cittadino non eseguita

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#1792]
id anpr cittadino: 45678591

Il cittadino viene iscritto nel Comune di Solofra (AV) proveniente dal Comune di Serino (AV).
Non ci è possibile prendere in carico il cittadino finché il comune di provenienza non effettua la cancellazione. E' corretto?
Da portale ANPR risulta ancora residente a Serino (AV): vedi allegato.
Dal comune di Serino riferiscono di aver cancellato il cittadino. Come possiamo risolvere?

**Comment by frmariani** [comment]
In ANPR il cittadino risulta giustamente in carico al Comune di Serino, perchè se il cambio di residenza interessa due comuni subentrati, il comune di immigrazione (Solofra)  deve effettuare una mutazione di residenza del cittadino;
Il comune di Serino dovrà soltanto aggiornare il gestionale con la notifica del cambio di residenza avvenuto.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
