### ISSUE TITLE
Problemi iscrizione APR: I soggetti devono appartenere alla stessa famiglia dichiarata

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#1793]
Errore EF044 durante iscrizione APR di un soggetto cancellato da ANPR per destinazione Solofra (AV).

id cittadino: 71069462
idOperazioneANPR 160053680 data 2019-11-28 17:59:04

**Comment by frmariani** [comment]
non mi è chiara la richiesta...
all'idoperazioneanpr indicata corrisponde un servizio di modifica delle relazioni di parentela....
cosa si intende per "iscrizione APR di un soggetto cancellato da ANPR" ? lei parla per il Comune di Solofra ? ho avuto il dubbio anche per la issue #1792 
Ha verificato quanto evidenziato dall'errore EF044 ? i cittadini presenti nell'elenco, non appartengono alla stessa famiglia.
la sua richiesta necessita di uno scambio di informazioni che sarebbe meglio approfondire con contatti telefonici o via email diretti.
Il sistema di Issue Tracking basato Github, dove ci stai leggendo, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Per questo motivo che Le chiediamo di avvalersi del servizio di assistenza ANPR al numero 800863116.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.

**Comment by vix-db** [comment]
Mi scuso per la poca chiarezza:
nello storico dei movimenti effettuati per iscrivere il cittadino con id anpr 71069462 (provenienza San Michele di Serino) ci siamo accorti che la comunicazione ANPR (codice servizio 5005) è andata in errore mostrando la stringa seguente:

EN527 W Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-02 16:53:52 , idOperazioneANPR 161654517 

Soltanto dopo abbiamo riscontrato l'errore indicato nel primo post (errore nella modifica della relazione di parentela...ovvia conseguenza).

Si richiede pertanto aiuto nel terminare l'iscrizione nel Comune di Solofra del cittadino in oggetto (correttamente marcato come cancellato su ANPR da San Michele di Serino con destinazione Solofra). 
Non riusciamo a portare a termine la mutazione di residenza sul portale ANPR.

**Comment by frmariani** [comment]
Il cittadino idanpr 71069462 risulta residente nel Comune di Solofra; 
per favore mi lasci un recapito telefonico in modo che possa spiegarmi meglio la natura del problema
