### ISSUE TITLE
Client di TEST per invocazione WS ANPR

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1794]
Buongiorno
esiste un client di test liberamente scaricabile da utilizzare per eseguire i test di invocazione dei WS di ANPR ?

Oppure esiste una documentazione tecnica dettagliata per la realizzazione di tale client in .NET ?

Grazie

**Comment by gife67** [comment]
Buongiorno,
esiste un repository su GitHub (https://github.com/italia/anpr-client-example/) dove può reperire i sorgenti in Java del client, l'abbiamo messo a disposizione solo in questo linguaggio a titolo di esempio.
