### ISSUE TITLE
Dati diversi tra Consultazione AE WebApp ANPR e PuntoFisco

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1795]
Comune di Villa Cortese - Produzione

Buongiorno,
una collega di un altro comune, anch'esso subentrato, mi ha fatto notare che per alcuni suoi cittadini, marcati ANPR e validati AE, i dati restituiti da Consultazione AE WebApp ANPR e PuntoFisco sono discrepanti, nel particolare, il luogo di nascita (in Consultazione AE WebApp è GAVERINA mentre in PuntoFisco GAVERINA TERME).
Detto questo, come mai questa discrepanza? Qual'è il dato corretto Consultazione AE WebApp o PuntoFisco?
In PuntoFisco mi permette di stampare un certificato con dati errati, possibile?

Grazie
Claudio

**Comment by rvinzani** [comment]
Dallo scorso giugno Agenzia Entrate ha effettuato un intervento per recepire da ANPR oltre al codice catastale anche la denominazione. Infatti spesso, a fronte di un codice catastale sono presenti più denominazioni.
Perchè questa modifica sia evidente su Puntofisco e sul codice fiscale, il cittadino deve farne richiesta ad Agenzia Entrate, mentre l'interrogazione da ANPR mostra il dato già modificato.
Sul sito www.anpr.inerno.it è stato pubblicato per tale motivo un annuncio di cui riporto il riferimento
[https://www.anpr.interno.it/portale/documents/20182/209665/Comunicazione+Agenzia+Entrate.pdf/5c0b4804-7856-4e9d-9039-03a043b2892c]
