### ISSUE TITLE
[Subentro] Errore WebApp con smart card sindaco

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#1796]
Buongiorno,
il Comune di CASAMASSIMA (BA) chiede, gentilmente, supporto per risolvere un problema che si sta verificando con la smart card del Sindaco sulla webApp (tutti gli ambienti). 
Sono state fatte varie prove, tra cui reinstallazione driver, cambio pc, ...
L'errore è il seguente:  ERR_BAD_SSL_CLIENT_AUTH_CERT
Abbiamo provato a cercare in altre issue ma non abbiamo trovato niente relativo a questo errore. Potreste darci qualche indicazione? Se preferite fornirci supporto telefonicamente posso inviarvi un recapito tramite mail. 
Il Comune sta valutando di effettuare il subentro ma ovviamente bisogna risolvere prima questo problema. 
Grazie

Comune di Casamassima (BA)

**Comment by rvinzani** [comment]
Per richieste di assistenza specifiche si prega di contattare il nostro numero verde 800863116. Grazie

**Comment by Eduardo1977** [comment]
E' stata fatta una richiesta più di un mese fa ( ticket  20762762) ma non c'è stata ancora risposta. Come scritto sopra, il Comune vorrebbe effettuare il subentro ma con questi tempi di attesa come dovrebbe fare?

**Comment by Eduardo1977** [comment]
In ogni caso, non ho capito perchè ha già chiuso la issue visto che il problema non è risolto. Qualcuno potrebbe aver avuto lo stesso problema e magari potrebbe rispondere per dare qualche indicazione. Serve a questo no?

**Comment by Eduardo1977** [comment]
Chiedo, gentilmente, @rvinzani se il problema potrebbe dipendere dal fatto che occorre abilitare un range di IP presso i vostri sistemi. Non potendo accedere alla WebApp per farlo autonomamente da "Amministrazione", come si può procedere? Grazie
