### ISSUE TITLE
Problema allineamento codice fiscale tramite web app

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1797]
Comune di Domodossola (VB) - Ambiente di produzione

Permane il problema esposto in questa issue già chiusa: [https://github.com/italia/anpr/issues/1753](https://github.com/italia/anpr/issues/1753).
Il comune ha contattato l'agenzia delle entrate (in seguito al ticket aperto con loro) che sono intervenuti sul soggetto registrato in ANPR con il C.F. MHMHSN82A01Z34RL e adesso dalla "consultazione AE" risulta marcato ANPR.
Il soggetto in questione deve subire un cambio di COGNOME e NOME su ANPR, e il nuovo C.F. dovrà essere BDLHSN82A01Z345G. Questo nuovo C.F. è già presente su AE con il nuovo cognome/nome, e da una "consultazione AE" risulta anche marcato ANPR (vedi allegato4). 
Abbiamo tentato di effettuare sia una mutazione dal gestionale tramite ws servizio 5008, sia tramite la web app dalla funzione di risoluzione disallineamenti, ma l'errore è sempre lo stesso: Soggetto non individuato in AT. Sempre tramite la web app/risoluzione disallineamenti, sono stati fatti vari tentativi, sia con la spunta "collega CF" che senza la spunta. 
Allego i vari tentativi fatti in caso vi possano essere d'aiuto.
Potete verificare che problema c'è ancora su questa persona?
![allegato1](https://user-images.githubusercontent.com/28776141/70039259-ebf42300-15b9-11ea-9894-8a90343c2e81.JPG)
![allegato2](https://user-images.githubusercontent.com/28776141/70039260-ebf42300-15b9-11ea-9e74-04c993308bc9.JPG)
![allegato3](https://user-images.githubusercontent.com/28776141/70039262-ebf42300-15b9-11ea-84bf-11a43ce13051.JPG)
[allegato4.pdf](https://github.com/italia/anpr/files/3915896/allegato4.pdf)
[allegato5.pdf](https://github.com/italia/anpr/files/3915897/allegato5.pdf)

**Comment by rvinzani** [comment]
Per i problemi specifici è bene utilizzare il servizio di assistenza ANPR al numero 800863116 anche per evitare di condividere dati e informazioni anagrafiche. La prego quindi di farmi avere un suo indirizzo di email al quale rispondere. Grazie.

**Comment by siscomanpr** [comment]
OK, grazie. Può contattarci all'indirizzo selene@siscom.eu
