### ISSUE TITLE
aggiornamento data decorrenza errata appartenenza famiglia

### ISSUE THREAD

**Issue by elvira1969** [italia/anpr#1798]
causa ripristino indirizzo/scissione anagrafica precedente al subentro, il cittadino con codice  73358608 ha una data decorrenza errata, dobbiamo inserire la data corretta di appartenza famiglia 08.10.2019.
Dato che non si riesce a modificare nemmeno da webapp, chiediamo la modifica d'ufficio,
comune di Montelabbate

**Comment by amollicone1982** [comment]
Aggiornamento eseguito
