### ISSUE TITLE
Richiesta chiarimenti AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1799]
Se un cittadino iscritto all'AIRE del Comune A si iscrive all'AIRE del Comune B che tipo di variazione deve essere inviata ad ANPR ?

1. il comune A invia un'operazione A006 - Mutazione [comune di riferimento] 
2. il comune B invia un'operazione A002 - Iscrizione per altri motivi [Trasferimento dall' A.I.R.E. di un altro comune]

è corretto ?

**Comment by ncapozzi** [comment]
Buongiorno,
se i due comuni interessati sono entrambi subentrati in ANPR:
1. il comune B invia un 5001 se tutta la famiglia AIRE cambia il comune di iscrizione
2. il comune B invia un A006 se un singolo soggetto cambia comune di iscrizione e crea una nuova famiglia AIRE oppure si aggiunge ad una famiglia AIRE già iscritta nel Comune B. Se più di un soggetto della famiglia di partenza si trasferisce nel comune B ma non tutti, è necessario richiamare A006 per ciascuno degli interessati

Se il comune A non è subentrato e il comune B si, il comune B invia un'operazione A002 - Iscrizione per altri motivi AIRE

Se il comune A è subentrato e il comune B no,  comune A invia una cancellazione 2003 - Cancellazione per altri motivi


N. Capozzi

**Comment by GabriellaBallabio** [comment]
Come può un operatore sapere se un comune è subentrato oppure no? L'nagrafe locale può invocare qualche metodo per consultare lo stat del subentro di un ente ?

**Comment by ncapozzi** [comment]
Può invocare il servizio 7001 che restituisce in output il contenuto delle tabelle di decodifica inclusa la tabella 45 Comuni subentrati
