### ISSUE TITLE
[5008] - mutazione Unione Civile mancato cambio stato civile

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#180]
Pisa, ambiente di Test, ID operazione ANPR 496100 e 496101

Buongiorno, abbiamo registrato un unione civile tra persone dello stesso sesso con il tipo di mutazione 18, trasmettendo nel contempo il nuovo stato civile (unito civilmente, codice 6) .
Le registrazione dell'unione civile avviene correttamente anche se viene indicato un warning sullo stato civile dell'altro unito ma, nei dati di ANPR non viene aggiornato lo stato civile del soggetto che rimane Celibe/Nubile.
Allego request e response, grazie.
Luca Bonini A.P.Systems
[5008-unione_civile.zip](https://github.com/italia/anpr/files/1018878/5008-unione_civile.zip)

**Comment by gcarbonin** [comment]
Per modificare lo stato civile, non è sufficiente mettere l'oggetto; occorre indicare anche il corrispondente tipo mutazione.
