### ISSUE TITLE
[5001] Mutazione famiglia/residente da CONVIVENZA a FAMIGLIA anagrafica

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1800]
Salve.
Sto eseguendo un cambio abitazione interno ad un comune con una 
comunicazione 5001 Mutazione famiglia/residente
per un cittadino che era in convivenza (unico componente)
e và a costituire una nuova famiglia ANAGRAFICA (sempre unico componente).

Mi ritorna errore
EF001
Identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata.

Questo è strano dato che invio non il codice ANPR della famiglia ma il codice famiglia del comune.

Ho provato a cercare anche in WA il codice identificativo della famiglia che indico nella comunicazione e mi dice che non è presente.

Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-03 11:25:04 , idOperazioneANPR 162040417

Potete effettuare un controllo e dirmi cosa non và?
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
è possibile avere un riferimento telefonico oppure un indirizzo email per una assistenza diretta?

Grazie
N. Capozzi

**Comment by fmbianchi** [comment]
non ho un diretto quindi sarebbe più facile se la contattassi io.

**Comment by ncapozzi** [comment]
Se non ha un diretto può inviare un indirizzo email oppure contattare direttamente il nostro numero verde 800863116.

Grazie
N. Capozzi
