### ISSUE TITLE
 Errore in RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#1801]
Il comune di Verona segnala il seguente problema:

Per l'individuo IDANPR 43606400 non riesce a risolvere l'allineamento con AE.
La cittadina russa e' nata nel 1984 in Unione Sovietica come risulta dal passaporto ed e' subentrata
in ANPR con un codice fiscale dello stato Z135.
In AE ha invece un codice fiscale della federazione russa Z154.
In web app Risoluzione disallineamenti AE, conferma dati ANPR segnala il seguente errore:

"Soggetto non rettificabile per errata indicazione del comune (codice 21)"

L'individuo in questione e' subentrato con il seguente luogo di nascita:

<luogoNascita>
 <localita>
  <descrizioneLocalita>UNIONE SOVIETICA</descrizioneLocalita> 
  <descrizioneStato>UNIONE SOVIETICA</descrizioneStato> 
  <codiceStato>998</codiceStato> 
 </localita>
</luogoNascita>

in quanto sul passaporto risulta soltanto Unione sovietica senza l'indicazione di alcuna localita'
e lo stato estero non e' presente nella tabella degli stati di ANPR e quindi passa in ANPR con
codice 998.

Grazie

Carla Musian
Applicativo Ascotweb

Eventualmente contattare il comune di Verona
Augusto Olivieri
0458077813

**Comment by ncapozzi** [comment]
Buongiorno,

il Sig. Olivieri sarà contattato nel più breve tempo possibile.
In generale per problematiche che come nel caso sopra esposto richiedono un contatto diretto con il Comune, si suggerisce di far contattare direttamente al Comune il numero verde 800863116.

Grazie
N. Capozzi

**Comment by mprovada** [comment]
Buongiorno Sig. Olivieri,

Ho la stessa situazione come quella che ha discritto qui sopra.
è riuscito a trovare una soluzione? POtrebbe condividere sua esperienza, per favore?
Grazie!
Marina Provada

**Comment by ncapozzi** [comment]
Buonasera,
come precedentemente indicato, per problematiche che come nel caso sopra esposto richiedono un contatto diretto con il Comune, si suggerisce di far contattare direttamente al Comune il numero verde 800863116. Non è detto che il caso sia lo stesso anche se lo potrebbe sembrare.

N. Capozzi
