### ISSUE TITLE
Perdita cittadinanza italiana

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1802]
Buongiorno
tra i motivi di Cancellazione APR è presente la perdita di cittadinanza italiana, ma quindi se un individuo perde la cittadinanza deve essere cancellato dall'APR?

**Comment by rvinzani** [comment]
La perdita di cittadinanza implica che il cittadino per risiedere in Italia abbia bisogno di un permesso di soggiorno. Potrebbe essere quindi cancellato in attesa del permesso di soggiorno.
