### ISSUE TITLE
[1002] chiarimento codici per lista dati controllo

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1804]
Buongiorno volevo un chiarimento circa i possibili controlli che si possono inserire nel servizio 1002.

nella documentazione (SPECIFICHE DI INTERFACCIA DEI SERVIZI DI ANPR PER I COMUNI) ho trovato solo il codice "FI", 
ma registrando una 1002 da WA, selezionando la check "comuni non validi alla data", consultando l'XML ho notato il codice "RE"

mi chiedevo è un codice ad uso esclusivo della WA oppure è possibile usarlo anche tramite WS, inoltre c'è un documento che elenca tutti i codici controllo utilizzabili (anche per gli altri servizi) oltre a "SPECIFICHE DI INTERFACCIA DEI SERVIZI DI ANPR PER I COMUNI"?

Grazie 
Riccardo

**Comment by amollicone1982** [comment]
RE è un codice esclusivo della webapp. Non esiste un documento con tutti i codici ma questi sono specificati nella documentazione del singolo servizio
