### ISSUE TITLE
Errore 2  invio notifiche di test pre-subentro

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1806]
Buonasera,
qualcuno mi può dare informazioni su come configurare  il servizio di ricezione delle notifiche da parte di ANPR in ambiente di pre-subentro, in quanto pur avendo creato il servizio e pubblicato provando a contattarlo con la funzione "Invia Notifica di test " dall'ambiente di pre-subentro ottengo sempre lo stesso esito "2 - Errore nell'invio della notifica di test". Il comune per cui stiamo effettuando la configurazione è 076083 Satriano di Lucania

**Comment by fferraguto** [comment]
Salve,
come endpoint ci risulta impostato un link che termina con "services.wsdl", sembra dunque che sia il puntamento al wsdl e non al servizio. potreste verificare la correttezza? Grazie.

**Comment by carminepat** [comment]
Salve, tra i vari test che abbiamo effettuato (abbiamo specificato anche il link al servizio) alla fine abbiamo lasciato il link a "services.wsdl" (che tra l'altro dall'ambiente di test risponde correttamente). Pur cambiando il link, però, non cambia l'esito. Riceviamo SEMPRE un generico errore 2, vorremmo maggiori informazioni eventualmente sulla configurazione e/o sull'errore. Grazie

**Comment by carminepat** [comment]
è possibile avere delucidazioni/indicazioni riguardo a questo ticket, sono giorni che non ricevo risposta e per noi tale problema ha una certa rilevanza ed urgenza, grazie

**Comment by fferraguto** [comment]
Salve,
abbiamo effettuato le nostre verifiche, potreste cortesemente riprovare l'invio?

**Comment by carminepat** [comment]
Grazie, adesso riceviamo l'invocazione, buona giornata e buon lavoro
Carmine Paternoster
