### ISSUE TITLE
[5005] Blocco per operazioni sospese che non risultano

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1808]
Ambiente di produzione, comune di Caldonazzo

Devo iscrivere per migrazione da altro subentrato due persone che appartengono ad una famiglia di 6.
Quando chiamo il servizio 5005 di mutazione residenza ottengo però l'errore "EN203 Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto". (ID operazione ANPR 165461464).

Controllando da WebApp non ci risultano operazioni sospese sui cittadini coinvolti.

Qual è il probema ?

Grazie

**Comment by rvinzani** [comment]
Non risultano operazioni sospese per i soggetti indicati. Chiudo la issue. Se il problema persiste vi prego di aprirne una nuova che faccia riferimento a questa
