### ISSUE TITLE
Certificati di Postazione

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#1809]
Comune di Taormina - 083097
Il comune, da noi di recente acquisito, aveva già effettuato un censimento utenti in precedenza, quando risultava ancora in carico il precedente Sindaco.
E' già in possesso di certificati e smart-card che però sembrano risultare non più validi.
Ora, la modifica del Sindaco dovrebbe già essere stata effettuata.
E' possibile verificare la validità dei certificati già consegnati per attuare le modifiche /abilitazioni utenti?
Probabilmente non sono mai state attivate dopo la consegna.

Grazie
Christian O. ADS

**Comment by Leonforte** [comment]
I certificati di postazione, che risultano tutti e 10 attivi, non hanno nessuna correlazione con le utenze che risultano anch'esse tutte attive e con smart card attiva, tranne una che è ancora da attivare.
Per il subentro potete utilizzare la sc dell'ammnistratore di primo livello ed il primo certificato di postazione. Abbiamo provveduto al reinvio del necessario all'indirizzo : servizi.informatici@comune.taormina.me.it
Per la configurazione delle postazioni potete far riferimento al documento allegato, buon lavoro, saluti

[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/3940226/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)
