### ISSUE TITLE
Definizione di eventi dopo il subentro

### ISSUE THREAD

**Issue by moniapellizzari** [italia/anpr#181]
Si chiede come saranno gestiti gli eventi che vengono definiti dopo la data di subentro ma che hanno una data evento precedente a quella di subentro.
Esempio: cittadino straniero residente nel comune, deceduto all'estero nel mese di novembre 2016, presubentro del comune avvenuto nel mese di maggio, viene portato l'atto di morte al comune per la cancellazione il 22/05/2017. 
Mettendo come data evento il 30/11/2017 e data definizione il 22/05/2017 il sistema dà errore perchè la data di morte quindi di evento è precedente alla data di subentro (come data di riferimento abbiamo il 18/05/2017, che corrisponde al nostro ultimo pre-subentro).
Come possiamo fare?

Monia Pellizzari
0516502105
Comune di Anzola dell'Emilia (BO)

**Comment by gcarbonin** [comment]
Mi può indicare l'operazione che ha restituito un errore?

**Comment by gcarbonin** [comment]
Abbiamo fatto una prova; se si mette come data di decorrenza il 30-11-2016 (2017 non passerebbe perché è data futura) ovviamente ANPR blocca l'operazione. In questo caso si deve indicare data decorrenza e data definizione  22-5-2017: in quella data, infatti, l'informazione confluisce in ANPR, in quanto fino alla comunicazione di decesso la scheda era aperta. In ogni caso,  richiedendo un certificato storico di residenza al 22-5-2017, ANPR restituirà un errore in quanto la persona a quella data era già deceduta.

**Comment by CarlaMusian** [comment]
Questo problema ritorna su quanto gia' segnalato in precedenza con "Data anagrafica di decorrenza e registrazione #167" perche' non e' chiaro se la data decorrenza da riportare in ANPR va intesa come "decorrenza in ANPR" dell'informazione e come impostare le date richieste in ANPR.

**Comment by gcarbonin** [comment]
Ha visto il documento dove abbiamo cercato di descrivere l'uso delle date? Quando c'è una dichiarazione anagrafica, la data di decorrenza è la data della dichiarazione; anche la mutazione di completamento che si trasmette alla ricezione dell'APR4 ha la stessa data di decorrenza, a patto che nel frattempo non siano state eseguite altre mutazioni; al momento il sistema accetta come "altre mutazioni" la carta di identità e la variazione di domicilio nel comune, ma stiamo lavorando per accettare qualsiasi mutazione che riguardi dati diversi da quelli movimentati con l'APR4. Per gli eventi che derivano da comunicazioni dello stato civile, la data è quella "nella quale l'ufficio anagrafe è venuto a conoscenza del fatto" . Nelle certificazioni si tiene conto della data dell'evento a prescindere dalla sua data di registrazione.
