### ISSUE TITLE
Errore annullamento fusione famiglia a cavallo del subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1810]
Buon giorno,
esponiamo il caso segnalato da alcuni nostri comuni subentrati, che hanno la necessità di annullare una fusione tra due famiglie avvenuta a cavallo del subentro; ad esempio la famiglia 1, composta da IS e figlia, si è fusa con la famiglia 2 prima del subentro, pertanto i componenti sono stati trasmessi nella famiglia 2 al relativo indirizzo, con i nuovi rapporti di parentela. 
Per annullare la fusione e il relativo cambio di indirizzo della famiglia 1, abbiamo seguito quanto esposto nella issue #967, con la differenza che trattandosi appunto di una fusione abbiamo richiamato il servizio 5005 invece del 5001, con i dati del precedente indirizzo e tipoMutazione 6 (Ripristino residenza ante subentro).  
Anche in questo caso, come per la issue citata, un componente è residente al vecchio indirizzo dal 24/08/2011, mentre l'altro è stato iscritto nel comune in data 25/06/2018, pertanto chiamando il ws 5005 come sopra descritto otteniamo l'errore "Data decorrenza residenza minore della data di prima iscrizione del soggetto", probabilmente riferito al secondo componente. 
Dato che per il ws 5001 avete successivamente modificato la funzionalità in modo da consentire la comunicazione della data decorrenza ante subentro effettiva, può essere che lo stesso intervento debba essere effettuato anche per il ws 5005? Oppure c'è qualche errore nella request?  
La prova è stata riprodotta in ambiente di test comuni - Pianella, con ID operazione comune 0680302019121028, in data 10/12/2019.
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by azabatta** [comment]
E’ stato aperto un intervento per la gestione della casistica segnalata.  La informeremo appena la modifica  sarà conclusa.
Buona giornata

**Comment by Amucciarelli74** [comment]
Buon giorno,
vi chiedo scusa ma il comune di Teramo ha in sospeso un caso riguardante questa problematica e ci ha chiesto di sollecitare cortesemente l'intervento o quanto meno di conoscere una tempistica per il rilascio, potete darci qualche notizia?
Grazie, 
cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by azabatta** [comment]
Buonasera, 
l'intervento è in fase di realizzazione. Cercheremo di velocizzare le fasi di testing e rilascio in ambiente di produzione entro il prossimo sabato.

**Comment by lorbia** [comment]
Buongiorno,
l'intervento è stato rilasciato in ambiente di produzione.
Saluti,
Lorenzo Bianchi

**Comment by lorbia** [comment]
Per qualsiasi ulteriore chiarimento potete chiamare il numero verde di assistenza.
Saluti.
