### ISSUE TITLE
CITTADINO CON DUE CODICI FISCALI ALL'AGENZIA DELLE ENTRATE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1811]
Cittadini in anagrafe e agenzia delle entrate con i seguenti dati corretti:
Mbye Kebba nato il 31.08.1986 cf MBYKBB86M31Z343N.
Altra posizione in agenzia delle entrate con dati errati:
Kebba Mbye nato il 01.01.1988 cf KBBMBY88A01Z343G.
Di conseguenza di devono collegare i due cf per poterli allineare sia in anpr che in AT.
Filippo Asaro
0923993382 - asaro.filippo@comune.marsala.tp.it

**Comment by rvinzani** [comment]
Fornite indicazioni alla email indicata
