### ISSUE TITLE
PROBLEMI CON IL RIPRISTINO DI POSIZIONI ANAGRAFICHE

### ISSUE THREAD

**Issue by Davide20860** [italia/anpr#1812]
Con operazione n. 166199921 (forzata da voi) ci avete permesso il ripristino della posizione del cittadino con CF HSSRSB87T20Z236M riportandolo come residente a Milano.
Questa operazione ha però riportato tutta la sua famiglia come residente a Villasanta ma, siccome erano stati iscritti come provenienti dal Pakistan il ripristino della loro posizione era la cancellazione da ANPR.
Abbiamo tentato di fare noi la cancellazione, ma otteniamo l'errore che l'iscrizione è già stata annullata con operazione n. 166199921, ma questo non corrisponde al vero in quanto risultano ancora residenti a Villasanta.
I CF dei componenti della famiglia sono:
BBIQSA87S48Z236B
RSBKNZ07R53Z236B
BBIMYM09T57Z236G
RHMBDL13H26Z236H
Si chiede intervento per la cancellazione dei suddetti soggetti, in quanto devono poi essere iscritti come provenienti dal Pakistan in altro Comune (Biassono, dove è stato iscritto il soggetto HSSRSB87T20Z236M da Milano)

Per precisazioni: 
Davide Tagliabue - Comune di Villasanta (MB)
davide.tagliabue@comune.villasanta.mb.it
3204319893

**Comment by rvinzani** [comment]
Essendo un problema di assistenza specifico le verrà risposto tramite il servizio di assistenza con il numero di ticket 20841207
