### ISSUE TITLE
Errore EC148 - Comune/provincia di nascita genitore inesistente.

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#1813]
COMUNE DI CAGLIARI 

Buongiorno, 
nella registrazione di iscrizione di un cittadino da comune non subentrato viene segnalato l'errore riportato in oggetto.

Nel caso specifico, alla madre, inscritta in ANPR e residente nel nostro comune,  è stato lasciato (come indicato anche del Ministero per non creare problemi ai cittadini con CF validato)  il  comune di nascita TURRI (CA), che nel 1945 (anno di nascita) era frazione di TUILI.

Per permettere l'invio dell''operazione in ANPR è stato riportato solo il  nominativo della madre senza associare l'id ANPR.

E' possibile associare comunque l'id ANPR dei genitori se presenti in ANPR? Sarebbe utile nel caso servisse dover estrarre i figli richiamando il CF di un genitore.

Grazie, 
Andrea Demeglio

**Comment by ncapozzi** [comment]
Buongiorno,
si potete associare l'idsoggettoANPR dei genitori se presenti in ANPR. Potete indicare l'id operazione che va in errore per consentirci di verificare?

Grazie

N. Capozzi

**Comment by andemeglio** [comment]
salve,
l'id operazione è la n. 166755329 ma come detto in precedenza ho già inviato inviato l'operazione mettendo il nominativo della madre senza associare l'id ANPR.

Facendo una mutazione dati (tipo richiesta 5008) mi ha consentito di fare l'associazione che con mi ha permesso di fare con l'iscrizione (tipo richiesta 1002).


Andrea Demeglio

**Comment by ncapozzi** [comment]
Perfetto.

Saluti
N. Capozzi
