### ISSUE TITLE
modifica data decorrenza ripristino anagrafico

### ISSUE THREAD

**Issue by leopaul76** [italia/anpr#1814]
Ambiente di produzione  - Comune di Valenza (AL)

A seguito di ripristino da un Comune in fase di subentro chiedo di modificare la decorrenza di iscrizione anagrafica per ripristino dal 06-07-2019 alla data corretta del 04-07-2019 relativamente al cittadino avente ID Anper 47840940 e ID famiglia 27616212.
Non riusciamo a farlo in autonomia ne attraverso il nostro gestionale Civila Next ne tramite Web App ministeriale.
Grazie e saluti.
Comune di Valenza
per info 0131949210

**Comment by frmariani** [comment]
l'operazione di "Iscrizione per altri motivi" idanpr 113015443 deve essere annullata e rieseguita con la data corretta.

**Comment by leopaul76** [comment]
Il problema è proprio la data, nel senso che se nell'operazione di "Iscrizione per altri motivi" metto la decorrenza esatta del 04/07/2019 l'operazione non va a buon fine in quanto compare l'errore "data decorrenza 04/07/2019 00:00:00 minore della data decorrenza 06/07/2019 00:00:00 dell'ultimo stato dell'individuo - IscrizioneAprAccertamento-", mentre se inserisco la data del 06/07/2019 l'operazione va a buon fine ma chiaramente con data non corretta; oltretutto lo stesso identico problema è ricapitato ieri con un altro ripristino di un comune a cavallo di subentro.

**Comment by frmariani** [comment]
interrogando il cittadino non risulta l'annullamento della precedente "Iscrizione per altri motivi" come Le avevo suggerito;
credo che Lei stia operando dal suo gestionale perchè non trovo riscontro nell'errore che riporta, in questo caso deve contattare la sua casa software;
in caso contrario, gentilmente mi indichi l'idanpr dell'operazione fallita presente nell'errore EN527

**Comment by frmariani** [comment]
ho verificato che ora avete effettuato l'annullamento della precedente iscrizione ed avete rieseguito l'operazione con la data corretta come suggerito;
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
