### ISSUE TITLE
EN272 - Mutazione dati matrimonio.

### ISSUE THREAD

**Issue by alikerberos** [italia/anpr#1815]
Buongiorno,

sto cercando di rettificare i dati di matrimonio mancanti o errati in due schede ANPR.

Il programma utilizzato è "HALLEY Informatica"

Quando invio la richiesta di mutazione il sistema risponde con i seguenti errori:

<codiceErroreAnomalia>EN272</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Alla data 29-08-1970 il soggetto XXX risulta gia' coniugato o unito civilmente con un altro soggetto</testoErroreAnomalia>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-11 13:58:55 , idOperazioneANPR 167162826</testoErroreAnomalia>

Lo stesso accade tendando di aggiornare la posizione del coniuge.

Al momento ho tentato le seguenti soluzioni:

1 - Inserire la mutazione direttamente dalla WAPP: il risultato non cambia
2 - Inserire una richiesta di Eliminazione dati (Matrimonio) direttamente dalla WAPP:

errori:

Tipo operazione non ammesso per il servizio (Codice: SP000) 
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-11 13:52:21 , Token 1576068741276 (Codice: EN527)

Attendo con trepidazione una vostra risposta.

Cordiali saluti, Nicola Pepe (Comune di Cerro Maggiore)

**Comment by frmariani** [comment]
Al momento del subentro, per entrambi i cittadini, sono stati inseriti erroneamente sia il nome che il cognome nel campo del cognome;
per questo motivo, la prima operazione da effettuare è la modifica dei dati del coniuge per entrambi i cittadini;
successivamente, si potrà effettuare la riconciliazione dei dati del matrimonio su un solo coniuge: il sistema visualizzerà le informazioni corrette per entrambi.
Le soluzioni che ha tentato non sono corrette per i seguenti motivi:
1) se l'operazione che viene effettuata sulla web app è la stessa  che viene effettuata sul gestionale, il risultato sarà lo stesso;
2) i dati del matrimonio possono essere eliminati soltanto a valle del subentro: nel vostro caso, sui coniugi sono state effettuate 5 operazioni diverse, tra cui anche una rettifica dell'indirizzo.
3) nel campo iniziativa, non deve scegliere "Rettifica", in caso di operazione di "Mutazione tutti i dati"

Se vuole può indicarmi un recapito dove raggiungerla
frmariani@sogei.it

**Comment by alikerberos** [comment]
Grazie per il veloce riscontro,

ho proceduto come indicato:

1 Mutazione di tutti i dati: solo il cognome nome del coniuge. Risultato: correttamente riallineati i due coniugi utilizzando ID ANPR. Tutti i dati dei coniugi adesso corrispondono esattamente.

Grazie per l'assistenza.

Cordiali saluti, Nicola Pepe.
