### ISSUE TITLE
MECEDONIA DEL NORD - 1 Errore Anpr Cod: EC031

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1816]
Buongiorno,

utilizzando come luogo nascita la nazione recentemente inserita nelle tabelle ministeriali con codice ISTAT 253 abbiamo l'errore:

1 Errore Anpr Cod: EC031 - Il codice dello stato estero di nascita 253 non e' congruente con la descrizione MECEDONIA DEL NORD - 

Possibile che vi sia un errore di battitura nella denominazione della nazione nelle Vs. tabelle?

Attendo gentile riscontro.

Grazie

Roberta Biasi
Dedagroup Public Services

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare per favore?
N. Capozzi

**Comment by ncapozzi** [comment]
Non avendo ricevuto risposta né tanto meno altre segnalazioni analoghe da parte di altri comuni, si chiude la issue.

N. Capozzi
