### ISSUE TITLE
[4005] - problema scarico notifiche

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1817]
Comune di Castagneto Po (TO) - Ambiente di Produzione

Per il comune in oggetto non vengono scaricate alcune notifiche apparentemente già disponibili da diversi giorni.
Questi sono gli ID delle operazioni ANPR che risultano sulle notifiche da web app:
166014486
157838305
154327917
Potete verificare se c'è qualche problema?

Siscom SPA

**Comment by fferraguto** [comment]
Salve,
relativamente alle operazioni segnalate, ci sembra che le notifiche N010 correlate siano state restituite almeno a seguito della richiesta contraddistinta da id ANPR 167467811 effettuata oggi.
Se non avete risolto, potreste comunicarci quale operazione vi ha dato il problema?
Cordiali saluti.
