### ISSUE TITLE
[3002] filtro cognome,nome e carta identità non funzionante

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1818]
In ambiente di test abbiamo fatto una ricerca usando i tre crtieri in oggetto.
Ci aspettavamo un cittadino invece il risultato ne contiene 4, di cui 3 omonimi ma chiaramente con differenti carte di identità. (id operazione anpr 22802323)
Stesso risultato applicando il medesimo filtro da webapp.

Se invece filtriamo solo per numero carta il risultato è un unico cittadino.

Mi pare ci sia un'anomalia nell'uso combinato dei filtri generalità e carta identità.

**Comment by azabatta** [comment]
Sarà effettuato un intervento per raffinare la modalità di ricerca combinata indicata. La informeremo quando sarà possibile riprovare.

**Comment by azabatta** [comment]
Buongiorno, 
l'implementazione è stata realizzata. La modifica è disponibile in ambiente di PRODUZIONE.
Buon lavoro
