### ISSUE TITLE
Luogo di nascita per soggetti stranieri

### ISSUE THREAD

**Issue by moniapellizzari** [italia/anpr#182]
Si è constatato che il sistema ANPR non contiene l'informazione sul comune di nascita dei cittadini nati all'estero (che siano anche stranieri o italiani naturalizzati) nè nel sistema di consultazione nè nei certificati, ma compare solo lo stato.
Per quale motivo non viene recepito questo dato sul comune di nascita dai dati che il comune trasmette?

Monia Pellizzari 
Comune di Anzola dell'Emilia

**Comment by gcarbonin** [comment]
Il luogo di nascita è indicato nella località e viene riportato, Se indica un identificativo ANPR possiamo fare qualche verifica.

**Comment by moniapellizzari** [comment]
Si conferma che oggi il sistema recepisce anche il comune di nascita, la scorsa settimana avevamo fatto la prova con un rumeno e ci risultava solo Romania e non Bucarest, nella prova odierna invece risultano presenti entrambi.
Grazie per la collaborazione.
