### ISSUE TITLE
Iscrizione x Ripristino Posizione Precedente

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1821]
Per il ripristino della posizione precedente il tag PROVENIENZA  va compilato (supponendo che il cittadino da ripristinare non sia stato residente dalla nascita ma immigrato) ?

**Comment by frmariani** [comment]
Sono decisioni di pertinenza del Comune.
tecnicamente il dato non è obbligatorio, ma se acquisito, il Comune di provenienza non deve essere subentrato.
