### ISSUE TITLE
2001 - Cancellazione per morte accertata

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1822]
In caso di decesso di un soggetto oltre al servizio 2001 è necessario anche invocare il servizio 5001 - Richiesta di mutazione famiglia ed il servizio 5008 - Richiesta di mutazione dati generali stato civile.

Oppure tutte le nuove informazioni in merito alla composizione della famiglia, alla vedovanza del coniuge ed al suo nuovo stato civile, ed al nuovo IS vengono recuperate dal tag ElencoSoggettiFamiglia ?

**Comment by ncapozzi** [comment]
Buongiorno,
il WS 2001 inserisce automaticamente i dati della vedovanza sulla scheda del coniuge superstite se le due schede sono collegate su ANPR. Tuttavia lo stato civile deve essere modificato separatamente richiamando il WS 5008.

Se il deceduto era l'intestatario della famiglia, è possibile ridefinire i legami dei componenti rimasti direttamente nel WS 2001.

N. Capozzi

**Comment by GabriellaBallabio** [comment]
Il Comune di Caponago si trova nella situazione che il cittadino Bianchi/Mario (INTESTATARIO SCHEDA) è deceduto.
Invochiamo il servizio 2001 Cancellazione per morte accertata, i dati di vedovanza sul coniuge vengono automaticamente aggiornati. 
Lo stato civile della moglie da CG a VD lo modifichiamo con 5008.
GIUSTO ?
Il componente NUOVO IS lo comunichiamo direttamente con ws 2001 ?

**Comment by ncapozzi** [comment]
Esatto

**Comment by GabriellaBallabio** [comment]
Un ultimo chiarimento, i dati di vedovanza vengono automaticamente aggiornati sul coniuge, solo se indico il tag elencoSoggettiFamiglia. Oppure anche in sua assenza ?
Il tag elencoSoggettiFamiglia NON è obbligatorio nel caso in cui il deceduto NON sia l'intestatario scheda.

**Comment by ncapozzi** [comment]
Come già detto, i dati della vedovanza vengono aggiornati automaticamente sulla scheda del coniuge superstite se le due schede sono collegate su ANPR. 
elencoSoggettiFamiglia serve per ridefinire i legami dei componenti rimasti in caso di decesso dell'intestatario
