### ISSUE TITLE
Emigrazione di un cittadino AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1823]
Quale servizio è necessrio invocare per l'emigrazione all'estero di un cittadino AIRE ? il 2003 ?

**Comment by ncapozzi** [comment]
Buongiorno,
il servizio da invocare dipende dai casi:
se il cittadino è residente in un comune subentrato richiamare A006
se il cittadino non è presente in ANPR richiamare A001 o A002 a seconda del motivo di iscrizione
se il cittadino è in ANPR ma si iscrive all'AIRE di un comune non subentrato richiamare 2003

N. Capozzi

**Comment by GabriellaBallabio** [comment]
La situazione è la seguente :

Il comune di Caponago (SUBENTRATO) ha come cittadino iscritto all'AIRE Bianchi/Mario . Bianchi Mario ieri è emigrato definitivamente in un comune estero PARIGI. Quindi NON è più un cittadino AIRE del comune di Caponago, quale servizio è necessario invocare ?

**Comment by ncapozzi** [comment]
Sinceramente non capisco bene quale sia esattamente il problema.
Se il Sig. Bianchi/Mario è un cittadino italiano iscritto all'AIRE (Anagrafe degli Italiani Residenti all'Estero) del Comune di Caponago vuol dire che risiede all'estero, immagino a Parigi. 
Se non è più iscritto all'AIRE vuol dire o che è tornato in Italia, e quindi occorre effettuare una mutazione di residenza, oppure che si è reso irreperibile e quindi va cancellato.
