### ISSUE TITLE
WS 1002 - Iscrizione - trasferimento di residenza da altro comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1824]
Non è chiaro come procedere nei due diversi casi 

- trasferimento di residenza da altro comune NON subentrato
- trasferimento di residenza da altro comune SUBENTRATO

Quali servizi debbono essere invocati ?

**Comment by azabatta** [comment]
Buonasera, 
si elencano di seguito le casistiche che possono presentarsi: 

-	provenienza da comune non subentrato: si utilizza il servizio 1002  “Iscrizione per altri motivi” (è previsto uno specifico motivo di iscrizione  “Immigrazione da comune non subentrato”);

-	provenienza da comune subentrato -  cambio di residenza di un intero nucleo familiare: si utilizza il servizio 5001  “Mutazione famiglia- convivenza”;  

-	Provenienza da comune subentrato -  cambio di residenza di uno o di alcuni tra i componenti di una famiglia: si utilizza il servizio 5005 “Mutazione residenza”. 


La documentazione tecnica e istruzioni operative di riferimento sono presenti sul documentale di ANPR www.anpr.interno.it  –  sezione “Documentazione tecnica”.
