### ISSUE TITLE
s5001 - errore - "utente non abilitato 7"

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1825]
Buon giorno
scrivo per segnalare questo errore di cui non trovo codifiche nei manuali o in github.

Vari comuni ci stanno segnalando l'errore "Utente non abilitato 7" in risposta ad un servizio 5001 per variazione parentela a seguito di un matrimonio.
Può capitare infatti che uno dei due coniugi prima del matrimonio sia convivente e poi cambi in marito/moglie, quindi inviamo consecutivamente prima una 5001 per le variazioni parentela della famiglia poi le 5008 necessarie per aggiornare lo stato civile e aggiungere il matirmonio.

In questi casi la risposta torna senza id operazione anpr con errore:

```
<errore>
<codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Utente non abilitato 7</testoErroreAnomalia>
</errore>
<errore>
```

Un esempio è il comune di Limena con idOperazioneComune 20191204164228941

Cordiali Saluti

**Comment by rvinzani** [comment]
Salve,
dovreste verificare quale id è presente all'interno dell'asserzione SAML (id-utente) . Nel messaggio XML questa informazione non compare. Nel caso inviatecelo per verifica
