### ISSUE TITLE
Certificato ANPR scade il 25/01/2020

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1826]
Ho notato che il certificato esposto dalla connessione SSL di ws.anpr.interno.it scadrà il 25/01/2020.
Per schedulare l'aggiornamento dei clienti volevamo sapere quando è previsto l'aggiornamento con un nuovo certificato.

Grazie

**Comment by Leonforte** [comment]
Buongiorno,
il certificato sarà sostituito verso la metà di gennaio, Se preferite trustare lo specifico certificato, per i client non è un problema, potete  continuare a trustare sia il vecchio che il nuovo una volta che ve lo forniremo,  credo ci sia tutto il tempo per gestire la sostituzione.
Comunque vi consigliamo di trustare quello della CA Postazione ANPR, proprio per evitare questi problemi, infatti nelle versioni del client pubblicate su GitHub e su ANPR, il certstore (cacerts) esegue il trust del certificato della CA di emissione e non quello puntuale dell’endpoint,

**Comment by busaster** [comment]
d'accordo, il certificato da trustare è quello rpesente al link  "Certificato CA ANPR produzione "  nella pagina di documentazione tecnica, corretto ?

**Comment by Leonforte** [comment]
Si, corretto. Lo zip contiene sia quello di postazione che quello utenti.
