### ISSUE TITLE
Invocazione servizio 7001 - ambiente FREE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1827]
Buongiorno
cercando di invocare il ws 7001 dall'ambiente FREE con l'xml allegato otteniamo la risposta allegata.
Potete esserci di aiuto per cortesia ?
Grazie
[EsitoWS_Richiesta7001_20191216103438.txt](https://github.com/italia/anpr/files/3967193/EsitoWS_Richiesta7001_20191216103438.txt)
[Richiesta7001_xml.txt](https://github.com/italia/anpr/files/3967194/Richiesta7001_xml.txt)

**Comment by gife67** [comment]
Buongiorno,
potrebbe esserci un leggero disallineamento dell'ora sul vostro PC/server da cui partono le richieste. Dovrebbe verificare se la data e ora presente nell'elemento "Timestamp" del messaggio completo della richiesta sia congruente con l'ora effettiva. Siccome i token di sicurezza hanno una validità di 5 minuti, indicata dal Timestamp, potrebbe verificarsi il problema che le ho indicato.
Attendo un suo riscontro.
