### ISSUE TITLE
[6001] Certificato di Residenza AIRE - Indirizzo duplicato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1828]
ambiente di PRODUZIONE  - comune di FIORANO MODENESE (036013)

ci segnalano una situazione strana nella certificazione di residenza per tutti i componenti di una famiglia AIRE (idFamigliaANPR 20304725)
l'indirizzo, nel certificato, viene stampato due volte.
(ad esempio idOperazioneComune 2019600921)

potete verificare per capire come mai?

grazie.

Alessandro Monopoli ADS

**Comment by rnapoli1983** [comment]
Buongiorno,

grazie per la segnalazione.

Facciamo una verifica e vi facciamo sapere al più presto.

Cordiali saluti.

**Comment by rnapoli1983** [comment]
Buongiorno,

abbiamo pubblicato una nuova versione del servizio di certificazione anagrafica che dovrebbe risolvere il problema da voi segnalato.

Attendo un vostro riscontro e rimango a disposizione.

Cordiali saluti
