### ISSUE TITLE
Collegamento tra codici fiscali alfanumerico e numerico

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1829]
Buongiorno,
con la presente siamo a chiedere se c'è la possibilità di procedere al collegamento tra codice fiscale numerico e codice fiscale alfanumerico di cittadini già residenti in comune subentrato in Anpr. 
Il caso tipico è quello del richiedente asilo al quale è già stato attribuito un codice fiscale alfanumerico, correttamente presente in Anpr e Agenzia delle Entrate, ma che è anche in possesso di codice numerico slegato e presente in Agenzia delle Entrate. La webapp, utilizzando la funzione "Risoluzione disallineamenti con AE" restituisce la dicitura "Codici fiscali non collegabili" (screenshot in allegato). I cittadini in questa situazione, tra le altre cose, non possono fare la carta elettronica.
Grazie per l'attenzione,
cordiali saluti.
![disall](https://user-images.githubusercontent.com/57749903/70975573-7fdde880-20aa-11ea-805f-036a6540b8a0.PNG)

**Comment by rvinzani** [comment]
Potrebbe indicarmi il comune di residenza del cittadino in questione?

**Comment by katiavacchi** [comment]
Comune di Ravenna, grazie.

**Comment by katiavacchi** [comment]
Gent.le dott.ssa Vinzani,
le chiedo se può scriverci quanto ci siamo dette al telefono per una migliore gestione dell'informazione ricevuta. Grazie mille.

**Comment by rvinzani** [comment]
E' possibile collegare un codice fiscale numerico assegnato ad un cittadino in attesa di permesso di soggiorno ad uno definitivo alfanumerico se in ANPR è presente il CF numerico. Se invece in ANPR è già presente il CF alfanumerico definitivo il collegamento può farlo l'ufficio territoriale di Agenzia Entrate che può operare sul numerico non marcato per collegarlo all'alfanumerico marcato
