### ISSUE TITLE
Caso: Cancellazione per Morte 

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#183]
Salve,
in ambiente di TEST, per il Comune di Bologna, abbiamo cancellato un residente con il servizio 2001, operazione ANPR 498257. 
Se interroghiamo il coniuge superstite, soggetto anche lui residente nel Comune, non ci troviamo i dati di vedovanza .
Per quanto riportato nelle specifiche tecniche paragrafo 11.2.1, invece: Si  precisa  che  se  il  deceduto  risulta  coniugato  con  un  soggetto  ANPR,  per  tale soggetto verranno impostati i dati della vedovanza.

E' corretta l'operazione eseguita?

**Comment by gcarbonin** [comment]
Il coniuge è presente in ANPR ma quando avete trasmesso i dati della scheda del soggetto ora deceduto non è stato indicato l'identificativo del comune del coniuge, che viene utilizzato in questa fase per collegare tra loro le posizioni. cerco di spiegare: A è spostato con B entrambi residenti nello stesso comune. Con il subentro si acquisiscono le due schede separatamente; alla fine si cerca di abbinare i coniugi utilizzando l'identificativo scheda del comune, dato quasi sempre presente. Se i due coniugi si abbinano tra loro, vale quanto indicato nelle specifiche; in caso contrario (come per i soggetto in questione) occorre trasmettere la vedovanza sulla scheda del coniuge superstite in quanto non collegata alla precedente. Se ha bisogno di maggiori chiarimenti ci possiamo sentire
