### ISSUE TITLE
certificato di stato libero AIRE

### ISSUE THREAD

**Issue by Demografico1975** [italia/anpr#1830]
In ANPR non è possibile rilasciare la certificazione di stato libero per i cittadini AIRE, però in realtà il certificato di stato libero è rilasciabile unicamente dal Comune di iscrizione AIRE, pertanto bisognerebbe inserirla.
Infatti in base al D.Lgs. n. 71/2011, testo normativo sull'ordinamento e le funzioni consolari, che ha abrogato il D.P.R. 200/1967, il Consolato rilascia unicamente: - la certificazione d'iscrizione nello schedario consolare; - i certificati di cittadinanza; - le certificazioni di esistenza in vita.

**Comment by ncapozzi** [comment]
Buongiorno,
per quanto riguarda l'emissione dei certificati per i cittadini AIRE si fa riferimento all'approfondimento normativo richiesto nella issue #122 

N. Capozzi

**Comment by Demografico1975** [comment]
Però in questo chiarimento si fa riferimento a normative ora abrogate che non si applicano più. Inoltre lo stesso DPR 223/1989 all'art. 33 nella nuovo formulazione dice: "...l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, nonché' ogni altra informazione ivi contenuta", che pare quindi comprendere anche i cittadini AIRE.

**Comment by ncapozzi** [comment]
Allora proveremo a chiedere un ulteriore chiarimento al Ministero dell'Interno.

**Comment by AndreaAnt81** [comment]
Mi associo alle considerazioni esposte da Demografico1975, la mancanza di tale certificato in ANPR è una grave lacuna. Il combinato disposto dell'art. 1 e dell'art. 33 del Regolamento anagrafico lasciano pochi dubbi, è l'ufficiale d'anagrafe che deve rilasciare tale certificato, poiché si tratta di un iscritto in ANPR e perché tale dato è detenuto (oltre che registrato) dall'ufficiale d'anagrafe. Da ultimo, banalmente, perché i consolati non rilasciano tale certificazione. 

Andrea Antognoni

**Comment by FilippoPapi** [comment]
Buongiorno, per questo tipo di chiarimenti normativi è opportuno rivolgersi direttamente a:
Direzione centrale per i Servizi demografici, Dipartimento per gli Affari interni e territoriali,      Ministero dell’Interno
Cordiali saluti
gianfilippo papi
