### ISSUE TITLE
Consultazioni ANPR da parte di enti 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1832]
Sarebbe possibile per un concessionario di riscossione tributi parificato ad agenzia delle entrate (Maggioli Tributi SPA nel nsotro caso) richiedere della credenziali per accedere in lettura all'archivio ANPR ? 
E se sì, che strada bisogna seguire ?

Grazie

**Comment by azabatta** [comment]
Buonasera, 
per accedere ai dati di ANPR è necessario sottoscrivere un accordo di fruizione con il Ministero dell’Interno – Direzione Centrale Servizi Demografici. 

E’ in fase di realizzazione una piattaforma che automatizzerà tale flusso di sottoscrizione; le modalità ed i dati cui sarà possibile accedere, in funzione dell’ente/PA richiedente, saranno oggetto di valutazione da parte del Garante per la protezione dei dati personali.
La disponibilità dell’applicazione sarà resa nota sul sito pubblico di ANPR www.anpr.interno.it.
