### ISSUE TITLE
[webapp] Errore in risoluzione disallineamenti con AE

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1835]
Ambiente di produzione, comune di Scarperia e San Piero

Un cittadino straniero residente risulta avere in ANPR un certo cognome ed un certo codice fiscale. La sua posizione AE contiene invece dati più aggiornati (diverso cognome  e diverso CF), probabilmente il cittadino si è rivolto per motivi suoi ad AE.
Vogliamo allineare la situazione ANPR in modo che riporti i dati corretti presenti in AE. 
Tentando di fare questo dall'apposito strumento presente in WEB APP otteniamo però l'errore 

`Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)`

con l'indicazione ulteriore 

`Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-17 10:58:56 , idOperazioneANPR 170440774 (Codice: EN527)`

L'assistenza telefonica ANPR ha indicato al comune che si tratta di una situazione di omocodice e che la software house (noi) avrebbe dovuto aprire una issue su github.

Issue aperta, ora chiedo : come deve procedere il comune per sbloccare la situazione ?

Grazie

**Comment by rvinzani** [comment]
Domani chiamerò il comune per risolvere il problema. L'indicazione data dall'assistenza telefonica non è corretta in quanto questi casi specifici vengono risolti nell'ambito dell'assistenza telefonica e non su github dove vengono riportate problematiche di carattere generale.
