### ISSUE TITLE
Chirimenti idOperazioneComune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1836]
Pare ci sia un'incongruenza tra l'XSD 7001scaricoTabelle e il file xls testataRichiesta

l'xsd riporta :

<xs:simpleType name="tipoIdOperazioneComune">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-zA-Z])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>	

TIPO STRINGA DI CARATTERI.

L'xls riporta  : 

idOperazioneComune 
FORMATO : AN 
LUNGHEZZA : max 30 
DESCRIZIONE :  Identificativo   univoco attribuito all'operazione 
OBBLIGATORIO : 
REGOLE/CONDIZIONI : Numerico   crescente 

Come dobbiamo considerarlo STRINGA oppure NUMERICO?

**Comment by mttfranci** [comment]
Salve, sicuramente è la documentazione che va aggiornata.
Il dominio dell' id operazione comune è sempre lo stesso per tutti i servizi (da tipoDati.xsd) : 
	<xs:simpleType name="tipoIdOperazioneComune">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-zA-Z])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>	

Solo come nota storica, inizialmente doveva essere un numerico crescente, ma circa un anno fa lo abbiamo resto alfanumerico, proprio su istanza delle software house #814 .

Saluti

Assistenza ANPR
