### ISSUE TITLE
AIRE Elenchi Anomalie - Soggetti con tipo (e)lettore non valorizzato.

### ISSUE THREAD

**Issue by PepeNicola** [italia/anpr#1838]
Buongiorno,

per l'adempimento delle attività di verifica e aggiornamento dei nuovi elettori AIRE si chiede:

1 Qual è il Tipo File da selezionare nella sezione "Download file" che contenga la posizione Elettorale dei residenti AIRE?
2 Qual è la procedura da seguire per attivare l'elaborazione degli elenchi AIRE? Attualmente nella sezione "Download file" nessuno dei report "AIRE" è disponibile.

Grazie.

**Comment by ncapozzi** [comment]
Buongiorno,
Il Tipo file da selezionare per scaricare l'elenco dei cittadini AIRE con tipo elettore non valorizzato è "AIRE Elenchi Anomalie - Soggetti con tipo elettore non valorizzato".

Se per il vostro Comune non è disponibile alcun report vuol dire che non sono state riscontrate anomalie da verificare.

Per assistenza telefonica diretta si suggerisce di contattare il numero verde 800863116 e fornire un recapito telefonico e una fascia oraria di reperibilità.

N. Capozzi
