### ISSUE TITLE
Nato nel 1990 risulta coniugato nel 1983

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#1839]
Nel corso delle verifiche conseguenti al censimento si è controllata la scheda anagrafica di un cittadino che non ha avuto movimentazioni anagrafiche dal 2011, data dell'ultima variazione di indirizzo. E' nato nel 1990 e, mentre in anagrafe risulta correttamente celibe, in ANPR risulterebbe coniugato dal 1983, sette anni prima della nascita, con i dati di matrimonio della madre e la stessa indicata come coniuge. 
Il padre - e vero coniuge della madre del suddetto - risulta residente in altro Comune, mentre la madre risulta residente in questo Comune ma ad altro indirizzo.
Verosimilmente il problema si è prodotto in sede di passaggio ad ANPR, anche se risulta quanto meno inverosimile che il sistema accetti una data di matrimonio anteriore alla nascita.

**Comment by MarcoZoagli1** [comment]
Neppure è possibile porre rimedio dalla webapp di ANPR tramite la funzione Registrazione - Annullamento dati in quanto a fine operazioni viene visualizzato il seguente errore:

Tipo operazione non ammesso per il servizio (Codice: SP000) 


Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-18 10:19:58 , Token 1576660798751 (Codice: EN527)

**Comment by MarcoZoagli1** [comment]
Per risolvere il problema si tenterà di fare una fittizia variazione di stato civile da "coniugato" a "non conosciuto" e successivamente "celibe" tramite il gestionale Halley. Si segnala comunque tale disfunzione e la possibilità del verificarsi di ulteriori casi simili.

**Comment by MarcoZoagli1** [comment]
Con la variazione fittizia il problema non è risolto in quanto in ANPR permane lo stato civile di coniugato.

**Comment by MarcoZoagli1** [comment]
Aggiungo ancora che nella scheda individuale ANPR alla voce Generalità è indicato come celibe ma nei dati matrimonio risulta invece quanto sopra detto....

**Comment by frmariani** [comment]
In fase di subentro, abbiamo cercato di limitare gli errori bloccanti proprio per facilitare il passaggio in ANPR dei Comuni;
abbiamo anche reso disponibili delle funzionalità  che possono essere utilizzate in caso di errata comunicazione in fase di subentro;
nei servizi di Registrazione della web app di ANPR, è presente il tipo operazione "Eliminazione dati" da utilizzare esclusivamente  a valle del subentro.
Per risolvere il vostro caso procedete come segue:
annullate l'operazione di mutazione dello stato civile  e successivamente utilizzate l'operazione di eliminazione dei dati per i dati del matrimonio erroneamente inviati con il file di subentro.
Nel caso fosse necessario,  inviate l'idanpr del soggetto e sarò più precisa sulle operazioni da annullare oppure inviate una mail o un telefono dove raggiungervi per le vie brevi.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
