### ISSUE TITLE
ws [3001] - Errore nella ricerca di paternità e maternità

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#184]
Buon giorno,
nell'ambito dei test di iscrizione per nascita di un individuo in ANPR, stiamo testando anche il servizio 3001, che consente di recuperare in ANPR le informazioni su paternità e maternità dell'individuo.
Abbiamo generato una request "valida", settando i campi della sezione "datiControlli" in modo da effettuare una ricerca di entrambi i genitori mediante i codici fiscali comunicati nei blocchi "paternità" e "maternità". Entrambi i soggetti sono presenti in ANPR, ma otteniamo in risposta un errore, tra l'altro non specificato (il codice anomalia è XXXX e il testo dell'anomalia è vuoto). 
Secondo le indicazioni, inviamo i tracciati con la request e la response all'indirizzo email "segnalazioni-anpr@teamdigitale.governo.it".
Il test è stato effettuato in data 25/05/2017, in ambiente di test, per il comune pilota Teramo, con id operazione comune 1485.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
il problema è risolto. Se specifica nella richiesta l'id operazione comune o l'id operazione anpr, di norma non deve inviarci richiesta e risposta. Se serve la chiediamo noi.
