### ISSUE TITLE
Errore EN345 in rilascio certificato

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1840]
Comune di Modena - Ambiente di Produzione

Buongiorno, 
abbiamo tentato di rilasciare un certificato di residenza ad un soggetto iscritto in ANPR e residente in comune diverso da Modena con la modalità di esenzione da bollo:

_PROCESSUALE (certificati da produrre nel procedimento) - art. 18 DPR 30.5.2002, n. 115 e Circ. Agenzia delle entrate, 14.8.2002, n. 70/E;_ 

ma veniamo sempre bloccati da questo errore:

_La PA estera indicata non prevede esenzione da bollo (Codice: EN345)_

nonostante la richiesta sia stata fatta indicando **PA Estera =NO**. L' operazione è stata tentata più volte senza successo (idANpr dell' ultimo tentativo: 171260004).
Potete per cortesia spegarci perchè viene segnalato questo errore?

Grazie, saluti
Sonia Fiorini

**Comment by rnapoli1983** [comment]
Buonasera,

analizzando la richiesta da voi effettuata risulta che nei dati di controllo è stata indicata PA estera relativa al rilascio per cause giudiziarie:

 <datiControllo>
        <cognomeUffAnagrafe>....</cognomeUffAnagrafe>
        <nomeUffAnagrafe>....</nomeUffAnagrafe>
        <tipoRichiedente>1</tipoRichiedente>
        <tipoRichiesta>1</tipoRichiesta>
        <paEstera>3</paEstera>
        <emissione>1</emissione>
        <bollo>0</bollo>
        <bolloVirtuale>0</bolloVirtuale>
        <diritti>25</diritti>
        <esenzioneBollo>3</esenzioneBollo>
        <forzaCertificazione>1</forzaCertificazione>
      </datiControllo>

Questa tipologia di PA non può essere esente da bollo.

Se state operando dal vostro gestionale è probabile ci sia un errore tale che anche indicando, come da voi descritto, PA Estera=NO venga poi elaborata la richiesta con indicata una PA.

Rimango a disposizione per chiarimenti.

Cordiali saluti

**Comment by sfmodena** [comment]
Buongiorno,
alcuni dei tentativi sono stati fatti dal nostro applicativo quindi è possibile che il parametro "PA estera" sia impostato diversamente da quanto appare, però almeno in un caso l' operazione
è stata sicuramente fatta da WebApp con il parametro impostato a NO (abbiamo lo screenshot fatto dall' operatore).  Emettendo lo stesso certificato con tipo esenzione "PPAA  -  SCAMBIO DI ATTI E DOCUMENTI FRA PP.AA. - art. 16, tabella allegato B) DPR 642/1972" invece non ci sono problemi, non riusciamo a capire la differenza.

Grazie, saluti
Sonia Fiorini

**Comment by rnapoli1983** [comment]
Buongiorno,

per quanto riguarda la PA  sostanzialmente, se si opera da webApp e viene settata a "NO", nella richiesta in datiControllo non viene creato il tag:

<paEstera></paEstera>

stessa cosa deve essere garantita dal vostro gestionale quando invoca il nostro servizio di certificazione anagrafica.

Poi ci sono delle regole normative,  a noi comunicate, per cui alcune PA non possono essere esenti da bollo.

Sperando di aver inteso la domanda, rimango a disposizione per ulteriori chiarimenti.

Cordiali saluti.
