### ISSUE TITLE
[1014] chiarimento data decorrenza

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1841]
Buonasera, vorrei un chiarimento circa la valorizzazione della data di decorrenza per i servizi 1014.

ipotizzando una iscrizione per altri motivi con decorrenza 18/12/2019

verrebbero generate una 1014 e una 1002 entrambe con decorrenza 18/12/2019

successivamente ci si accorge che la decorrenza non è il 18/12/2019 ma il 17/12/2019
si annulla la 1002 con una 1013
nuovo invio 1002 con decorrenza 17/12/2019

alla definizione dell'iscrizione l'invio della 1014 per chiusura procedimento con decorrenza 17/12/2019 da errore EN443 segnalando che la decorrenza è inferiore all'ultima operazione registrata.

A questo punto mi chiedo come è corretto operare?
- inviare le 1014 con decorrenza sempre = al giorno di invio
- modificare/annullare la 1014 di apertura procedimento (nel caso come?)

Grazie mille 
Riccardo

**Comment by ncapozzi** [comment]
Buonasera,
può provare a modificare la data del procedimento aperto al 18/12/2019 dall'applicazione web di ANPR andando in Registrazione, Gestione procedimento amministrativo.

N. Capozzi

**Comment by ncapozzi** [comment]
Buongiorno, non avendo ricevuto ulteriori riscontri si chiude la issue.
