### ISSUE TITLE
Cancellazione per emigrazione ARUBA

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1843]
**Ambiente di Produzione - Comune di Bussolengo**

Buongiorno,
stiamo facendo una cancellazione (**2003**) di un cittadino straniero (**idAnpr 64290207**) per il territorio estero di ARUBA (Cod. 603)
Riceviamo: 
<idOperazioneANPR>**idOperazioneANPR: 173148821**</idOperazioneANPR>
**errore: EC175 -  Stato estero di destinazione 603 inesistente sulla tabella di riferimento.**
ARUBA è un territorio e non una Stato, ma comunque dovrebbe essere possibile cancellare per estero con quella destinazione, giusto?

**Comment by ncapozzi** [comment]
Buonasera,
per la Provenienza/Destinazione sono stati previsti solo gli Stati esteri, faremo una verifica per accettare eventualmente anche i territori.

N. Capozzi

**Comment by ncapozzi** [comment]
Buonasera,
nell'oggetto Provenienza/Destinazione è ora possibile indicare sia uno stato che un territorio.

N. Capozzi
