### ISSUE TITLE
Problema storico residenza ANPR

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#1844]
Buongiorno,
scrivo per avere informazioni su come procedere su un procedimento anagrafico:
Un persona è emigrata dal Comune di Serravalle Pistoiese nel Comune di Pistoia in data 12/08/2019, in quella data il Comune di Pistoia non ancora subentrata in ANPR.
In data 15/11/19 viene comunicato l’annullamento dell’iscrizione anagrafica e il relativo ripristino, a questa data il Comune di Pistoia era subentrato in ANPR. Il Comune di Serravalle Pistoiese quindi doveva procedere all’iscrizione per altri motivi del soggetto, purtoppo ci sono stati dei problemi relativi alla convivenza e quindi non siamo riusciti a fare la pratica prima dei primi di Dicembre. 
Quando stavamo facendo l’iscrizione ci siamo accorti che la persona aveva richiesto nuovamente l’iscrizione al Comune di Pistoia dalla data del 29/11/19 e quindi risultava e risulta ancora iscritto nel Comune di Pistoia.
Il problema è che questa persona in ANPR ha un “vuoto” di residenza  dal 12/08/2019 al 29/11/2019 in cui non risulta essere stato residente in nessun Comune.
Come è possibile procedere? In quanto in caso di richiesta di certificato di residenza storico, verrebbero riportati dei dati non veritieri.
Cordiali saluti

**Comment by rvinzani** [comment]
Puoi darmi l'idANPR della persona?

**Comment by marcoLave** [comment]
idANPR: 48916467

**Comment by rvinzani** [comment]
Il comune di Pistoia può annullare l'iscrizione che ha decorrenza 29/11/2019 e il comune di Serravalle può effettuare la reiscrizione alla data corretta. Successivamente Pistoia effettua una mutazione di residenza alla data del 29/11

**Comment by marcoLave** [comment]
Ma se l'altro comune non volesse annullar, e in quanto dicono che per loro l'iscrizione risulta essere avvenuta correttamente, è un procedimento che deve essere effettuato o è solo consigliabile da fare?

**Comment by rvinzani** [comment]
Il suggerimento è per sanare in ANPR una situazione creata probabilmente per un ritardo nelle operazioni. I comuni dovrebbero essere consapevoli che per non creare problemi al cittadino i dati in ANPR devono risultare corretti ed effettuare le operazioni necessarie perchè questo avvenga.
