### ISSUE TITLE
RIFERIMENTO ISSUE #1839

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#1845]
L'Issue in oggetto non ha risolto il problema. Il soggetto (ID ANPR VNDSLV90B21H183O) risulta iscritto in Anagrafe come celibe. In ANPR risulta pure celibe ma sono presenti i dati del matrimonio (celebrato 7 anni prima della sua nascita e con i dati riferiti a sua madre, peraltro residente ad altro indirizzo). Come soluzione con l'issue 1839 veniva suggerito quanto segue: "In fase di subentro, abbiamo cercato di limitare gli errori bloccanti proprio per facilitare il passaggio in ANPR dei Comuni;
abbiamo anche reso disponibili delle funzionalità che possono essere utilizzate in caso di errata comunicazione in fase di subentro;
nei servizi di Registrazione della web app di ANPR, è presente il tipo operazione "Eliminazione dati" da utilizzare esclusivamente a valle del subentro.
Per risolvere il vostro caso procedete come segue:
annullate l'operazione di mutazione dello stato civile e successivamente utilizzate l'operazione di eliminazione dei dati per i dati del matrimonio erroneamente inviati con il file di subentro.
Nel caso fosse necessario, inviate l'idanpr del soggetto e sarò più precisa sulle operazioni da annullare oppure inviate una mail o un telefono dove raggiungervi per le vie brevi."
Non è possibile seguire tale indicazione in quanto in ANPR NON è presente alcuna mutazione di stato civile che si possa annullare, e se si tenta sempre in ANPR di eliminare i dati del matrimonio mediante la funzione "eliminazione dati" viene visualizzato quanto segue:

Tipo operazione non ammesso per il servizio (Codice: SP000) 

Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-21 07:59:55 , Token 1576911595122 (Codice: EN527) 

Si chiede come procedere. Recapiti: tel 01852505222 mail marco.raso@comune.zoagli.ge.it

**Comment by MarcoZoagli1** [comment]
rettifica l'ID ANPR è 203820

**Comment by frmariani** [comment]
Se non ci sono operazioni riferite al soggetto dovete soltanto eliminare i dati inviati erroneamente con il subentro come esposto nella precedente issue.
Come tipo di iniziativa non dovete utilizzare Rettifica ma, operazione d'ufficio o di parte.

**Comment by MarcoZoagli1** [comment]
Procedendo come indicato viene visualizzato il seguente errore:

Operazione non effettuabile (Codice: 999) 


Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-27 08:12:15 , idOperazioneANPR 175747980 (Codice: EN527)

**Comment by MarcoZoagli1** [comment]
Il problema è stato risolto in autonomia dall'ufficio. Grazie.
