### ISSUE TITLE
[1002] Errore in iscrizione per ripristino posizione precedente

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1846]
Ambiente di produzione, comune di Rozzano

Il comune subentrato il 9/12/2019  tenta oggi di reiscrivere un soggetto che aveva cancellato per emigazione a Milano il 16/08/2019.
La re-iscrizione però non va a buon fine con l'errore "EN237 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata".

Qual è il motivo di questo blocco ?

Grazie

**Comment by mttfranci** [comment]
Salve, potreste fornici l'id dell'operazione ANPR?
(Come sempre è utile indicare il testo del messaggio EN527, solitamente fornito dal sistema ANPR in caso di blocco su una operazione di registrazione anagrafica).
Saluti

Assistenza ANPR

**Comment by busaster** [comment]
id operazione ANPR 170709356

**Comment by mttfranci** [comment]
Salve, il problema è che come data decorrenza della residenza viene indicata 2019-08-16, ma la residenza di questa convivenza ha avuto inizio il 2019-12-06.
Pertanto non è possibile indicare una data precedente.
