### ISSUE TITLE
rettifica data di iscrizione all'aire

### ISSUE THREAD

**Issue by ComuneVelletri** [italia/anpr#1847]
il cittadino avente codice ANPR 40407945, deve avere la variazione della data di iscrizione all'AIRE in quanto non è 05/10/2015 ma bensì 01/07/2015.
si chiedono istruzioni per procedere a tale rettifica
Comune di Velletri
ufficio anagrafe
tel. 06/96158264

**Comment by mttfranci** [comment]
Per i problemi specifici dei comuni è bene utilizzare il servizio di assistenza ANPR al numero 800863116 anche per evitare di condividere dati e informazioni anagrafiche.
In caso si siano già effettuati tentativi è utile indicarne l'esito (in particolare l'id operazione ANPR se disponibile).
Saluti
Assistenza ANPR
