### ISSUE TITLE
5008 variazione stato civile mancato aggiornamento stato civile coniuge 

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1848]
Buongiorno,

in data 23/07/2019 con ID operazione numero 106277533 viene registrato per il cittadino Id Scheda 61402435 il matrimonio con la cittadina 61400198, l'operazione di Mutazione Tutti Dati da esito positivo.

Tuttavia ora interrogando la cittadina 61402435 lo stato civile risulta ancota Celibe/Nubile e non risultano presenti i dati di matrimonio.

I dati del cittadino 106277533  risultano invece correttamente variati.

Potete verificare e procedere con la bonifica?

Grazie

Roberta Biasi
Dedagroup Public Services

**Comment by frmariani** [comment]
Con l'operazione idanpr 106277533 sono stati modificati i dati del matrimonio e lo stato civile del soggetto idanpr 61402435; nell'operazione, avete correttamente utilizzato gli idanpr di entrambi i coniugi, pertanto il matrimonio risulta "riconciliato" e quindi presente nella consultazione di entrambi i coniugi; 
l'unica operazione che dovete ancora effettuare è la modifica dello stato civile del soggetto idanpr 61400198.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
