### ISSUE TITLE
[5001] rettifica indirizzo

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1849]
Comune di Cercenasco (TO) - Ambiente di produzione.

Il comune deve fare una rettifica dell'indirizzo di una famiglia, abbiamo utilizzato il servizio 5001 indicando come tipo mutazione 9.
Il sistema restituisce il seguente errore bloccante:
Codice errore EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 15-04-1930
Informazioni sull'operazione da fornire in caso di assistenza : data 2019-12-30 11:24:34 , idOperazioneANPR 177018725

La famiglia in questione attualmente è composta da un solo componente. In precedenza era presente anche la madre (poi defunta). La madre come data di nascita e di decorrenza indirizzo aveva 15-04-1930.  
Perché ANPR richiede come data di decorrenza quella del 1930 se adesso sui dati dell'unico componente rimasto la data di decorrenza di residenza è giustamente quella del 30/07/1953?

**Comment by frmariani** [comment]
L'operazione di rettifica dell'indirizzo può essere utilizzata rispettando alcuni controlli piuttosto stringenti: la famiglia non deve avere modificato la residenza e la data dell'operazione deve essere la stessa in cui alla famiglia è stato attribuito quell'indirizzo;
visto che il decesso della signora è stato registrato ieri, posso consigliare di procedere nel seguente modo:
1) annullare l'operazione di decesso (idanpr 176821702);
2)rettificare l'indirizzo alla data corretta (15/04/1930);
3)inserire di nuovo il decesso della signora.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, aprite un'altra issue facendo riferimento a questa
