### ISSUE TITLE
[6001] richiesta certificato da richiedente diverso

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#185]
Corbetta, ambiente di Pre-subentro,

Buongiorno, se proviamo a richiedere un certificato (in questo caso residenza ma anche altri) di un soggetto residente indicando come richiedente un altro cittadino residente il sistema ci restituisce l'errore: EN294 - Il soggetto associato al documento in ANPR non coincide con il richiedente. Come mai visto?
Non abbiamo un ID operazione, allego quindi request e response.
Grazie.
Luca Bonini A.P.Systems
[richiestacertificato_darichiedente.zip](https://github.com/italia/anpr/files/1029565/richiestacertificato_darichiedente.zip)

**Comment by gcarbonin** [comment]
Il documento di riconoscimento del richiedente riportato nella richiesta coincide con quello registrato in ANPR; nella richiesta è stata indicata una data di scadenza diversa da quella conosciuta. Il concetto è: se ANPR non conosce il documento, lo accetta e basta; se lo conosce i dati devono essere coerenti.
Basta cambiare il documento o mettere la data corretta.
