### ISSUE TITLE
[1002] Errore in iscrizione per ripristino posizione precedente [continua da #1846]

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1850]
continuo la #1846 che è stata chiusa.

In data 6/12/2019 la convivenza in cui il soggetto deve essere re-iscritto ha subito una variazione di indirizzo. In questo caso dunque come dovremo comportarci per portare a termine la re-iscrizione ?

**Comment by mttfranci** [comment]
Salve, la data decorrenza minima che potete indicare è quella dell'ultimo cambio di residenza.
L'iscrizione per altri motivi non consente di inserire date non congruenti.
In questo caso in ANPR niente è noto su tale convivenza prima del 6 Dicembre.
Saluti

Assistenza ANPR
