### ISSUE TITLE
ALLINEAMENTO CODICE FISCALE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1851]
CITTADINO ATTRIBUITO CON IDENTIFICATIVO ALLA SCHEDA DA ANPR N.44116031 E ATTRIBUITO ALLA SCHEDA DAL COMUNE DI MARSALA  N.1021389. IL CITTADINO FIGURA IN ANPR CON C.F. N. 00452316847, ALL'AGENZIA DELLE ENTRATE FIGURA SIA CON C.F. 00452316847 CHE CON C.F. CORRETTO N. HDJWSL63B62Z352B-
SI CHIEDE DI ALLINEARE I CODICI FISCALI DAI NUMERICI A QUELLO CORRETTO ALFANUMERICO.
Grazie.
Tel.0923993382
email: asaro.filippo@comune.marsala.tp.it

**Comment by frmariani** [comment]
contattato l'utente ed effettuata la modifica del CF alfanumerico in ANPR
