### ISSUE TITLE
ws [A006] - errore su espatrio per incongruenza decorrenza residenza

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1852]
Buon giorno,
il comune di Porto San Giorgio (subentrato) non riesce a procedere con la registrazione di un espatrio da parte di un cittadino (id scheda soggetto ANPR 67186057), che va a creare una nuova famiglia AIRE all'estero con data origine e decorrenza residenza 22/02/2019.
Invocando il servizio in oggetto si ottiene l'errore EN237 : "La data di decorrenza della nuova residenza non può essere antecedente a quella già registrata"; il cittadino risulta però attualmente residente a Porto San Giorgio con decorrenza 23/11/2006 per cui non riusciamo a comprendere l'errore che blocca l'operazione, anche perché nella request è stata indicata la creazione di una nuova famiglia attribuendo il valore '2' nel campo _attribuzioneFamigliaAIRE_.
L'id operazione comune è 1090332020010288, eseguita in data 02/01/2020 come detto in ambiente di produzione nel comune di Porto San Giorgio.
In attesa di riscontro,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by ncapozzi** [comment]
Buongiorno,
il problema deriva dal fatto che avete indicato un id famiglia FE0001134 che è già presente in ANPR con data decorrenza residenza 02/08/2019 . Se il cittadino crea una nuova famiglia AIRE dovete indicare un id nuovo oppure non indicare affatto un id famiglia comune.

N. Capozzi
