### ISSUE TITLE
invicazion WS 2003 - cancellazione x trasferimento di residenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1853]
Buongiorno
una conferma : 

un cittadino italiano residente in comune subentrato trasferisce la propria residenza in altro comune subentrato, si invocano i ws 5001 oppure 5005

un cittadino italiano residente in comune subentrato trasferisce la propria residenza in comune italiano NON subentrato, si invoca ws 2003 con motivo 

3 | Trasferimento di residenza in comune non   subentrato

quanto sopra esposto è corretto ?

**Comment by rvinzani** [comment]
Sì, corretto
