### ISSUE TITLE
Cancellazione di un cittadino italiano residente in un comune subentrato per trasferimento di residenza all’estero. (iscrizione AIRE)

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1854]
Buongiorno
non mi è chiaro quale WS è necessario invocare al verificarsi dell'evento indicato in oggetto.

Se un comune subentrato deve cancellazione di un cittadino italiano residente per trasferimento di residenza all’estero. (iscrizione AIRE) deve utilizzare la cancellazione dall'APR (WS 2003 con motivo 8= Trasferimento di residenza (iscrizione AIRE) ) ?

oppure 

WS A002 con quale motivo ?

C01 Espatrio e/o residenza all' estero
C06 Espatrio

**Comment by ncapozzi** [comment]
Buongiorno,
confermo quanto le ho già indicato nella issue #1823 

N. Capozzi

**Comment by GabriellaBallabio** [comment]
Buongiorno
per cortesia partiamo da zero ... 

Comune di Caponago (Subentrato)
Cittadino Bianchi Mario (cittadino Italiano) iscritto in APR del comune di Caponago
emigra a PARIGI, quindi è necessario iscriverlo nell'AIRE del Comune di Caponago , in ANPR NON è PRESENTE.

Quale WS si utilizza ? 
WS 2003 X cancellazione dall'APR x altri motivi con motivo 8= Trasferimento di residenza (iscrizione AIRE) ) ?

oppure

WS A002 con quale motivo ?

C01 Espatrio e/o residenza all' estero
C06 Espatrio

Resto in attesa di gentile riscontro.

**Comment by ncapozzi** [comment]
Buonasera,
se il cittadino non è mai stato registrato in ANPR mi sembra evidente che non può essere cancellato con un 2003.

E se non è in ANPR come residente in un comune italiano non è neanche possibile che stia espatriando.

Le ripropongo le casistiche già descritte nella issue 1823

il servizio da invocare dipende dai casi:
se il cittadino è residente in un comune subentrato richiamare A006
se il cittadino non è presente in ANPR richiamare A001 o A002 a seconda del motivo di iscrizione
se il cittadino è in ANPR ma si iscrive all'AIRE di un comune non subentrato richiamare 2003
N. Capozzi

**Comment by GabriellaBallabio** [comment]
mi scusi ma come può un cittadino essere residente nel comune di caponago e non essere in ANPR, caponago ha già fatto il subentro.
Non ci sono diversi casi, ne esiste uno solo :

cittadino residente in caponago comune subentrato
presente in ANPR perchè caponago è subentrato
emigra all'estero

quale ws utilizzo ?

**Comment by ncapozzi** [comment]
Buonasera,
veramente è lei che tre ore fa mi ha evidenziato che il cittadino "...in ANPR NON è PRESENTE….". 
Se invece il cittadino è residente in un comune subentrato si deve richiamare A006 come ho già più volte indicato.

N. Capozzi

**Comment by GabriellaBallabio** [comment]
**ma il servizio A006 non è una richiesta mutazione AIRE ?**
<xs:element name="RichiestaA006">
    <xs:complexType>
      <xs:sequence>
        <xs:annotation>
          <xs:documentation>
            Richiesta mutazione AIRE

**il servizio A002 quando si utilizza ?**
 <xs:element name="RichiestaA002">
    <xs:complexType>
      <xs:sequence>
        <xs:annotation>
          <xs:documentation>
            Richiesta di iscrizione per altri motivi AIRE

**quindi il WS 2003 X cancellazione dall'APR x altri motivi con motivo 8= Trasferimento di residenza (iscrizione AIRE)  NON SI USA MAI ?**
