### ISSUE TITLE
Aggiornamento consolati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1855]
Buongiorno,
volevo informarvi che l'aggiornamento de "L'Ambasciata d'Italia in Astana" in "Ambasciata d'Italia in Nur-Sultan" del 2 gennaio presente sulla Tabella di decodifica n°41, manca sulla tabella n°24.

**Comment by ncapozzi** [comment]
Buongiorno,
il file è stato aggiornato. Grazie per la segnalazione.

N. Capozzi
