### ISSUE TITLE
WS 7001- scarico comuni subentrati

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1856]
Buongiorno
volevamo sapere come leggere il file associato alla risposta 7001 (tabella 45).

Il seguente codice :+1: 
risposta7001.getRispostaMultipla7001().getDatiDettaglioRisposta().getXmlFile().get(0)
va bene ?

**Comment by mttfranci** [comment]
Salve, 

Il codice da voi usato dovrebbe andare bene, tenete presente che il risultato è però compresso.

Nella issue #840 il collega @rnapoli1983 ha pubblicato un codice di esempio per la lettura del risultato del 7001 che riportiamo qui : 

```
try{
	ByteArrayInputStream bin=new ByteArrayInputStream(risposta7001.getRispostaMultipla7001().getDatiDettaglioRisposta().getXmlFile().get(0));
	ZipInputStream zis=new ZipInputStream(bin);
	ZipEntry entry;
	while ((entry = zis.getNextEntry()) != null) {
		System.out.println("Unzipping: " + entry.getName());
		int size;
		byte[] buffer = new byte[2048];
		FileOutputStream fos = new FileOutputStream(entry.getName());
		BufferedOutputStream bos = new BufferedOutputStream(fos);
		while ((size = zis.read(buffer, 0, buffer.length)) != -1) {
			bos.write(buffer, 0, size);
		}
		bos.flush();
		bos.close();
	}
	zis.close();	
	bin.close();
}catch(Exception e){
	e.printStackTrace();
}
```

Saluti

Assistenza ANPR
