### ISSUE TITLE
IMMIGRAZIONE SINGOLO CITTADINO DA COMUNE SUBENTRATO

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1857]
COMUNE DI CAPONAGO (MB)

Buongiorno
abbiamo oggi per la prima volta eseguito l'invocazione del WS 5005 - mutazione residenza 

per un cittadino residente in un comune subentrato (PADERNO FRANCIACORTA) che va a vivere nel Comune di Caponago.

L'esito riporta diversi errori che non comprendiamo , alleghiamo file esito

[EsitoWS_Richiesta5005.txt](https://github.com/italia/anpr/files/4034683/EsitoWS_Richiesta5005.txt)

Di seguito Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-08 10:59:03 , idOperazioneANPR 181359727

Restiamo in attesa di gentile riscontro.

**Comment by frmariani** [comment]
Il servizio 5005 Mutazione di Residenza deve essere inviato per il solo cittadino che cambia la residenza e deve essere richiamato con l'identificativo che il sistema ANPR conosce (quindi non con il vostro identificativo comunale sconosciuto ad ANPR);
Colgo l'occasione per ricordarle che il sistema di Issue Tracking basato Github, ha l’obiettivo di condividere problemi tecnici, chiarimenti normativi, esigenze e proposte di interesse generale, quindi ogni comunicazione ha visibilità pubblica.
Ci sembra che le sue richieste abbiano  un carattere di assistenza su casistiche particolari che richiedono scambi di informazioni e di dettaglio. 
Questi casi necessitano spesso di contatti telefonici o via email diretti.
Per questo motivo Le chiediamo  di avvalersi del servizio di assistenza ANPR al numero 800863116.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
