### ISSUE TITLE
CODICE FISCALE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1858]
Cittadino Identificativo scheda attribuito dal Comune 1016140 - Identificativo scheda attribuito da ANPR 44116862 - in ANPR CON I SEGUENTI DATTI ERRATI c.f. CMRDMA95A01Z32VN - nato il 01/01/1995. In agenzia delle entrate risultano due posizioni una con i suddetti dati errati ed una con i seguenti dati corretti c.f.CMRDMA79T31Z329O nato il 31/12/1979. di conseguenza occorre allineare il dato corretto in ANPR. Grazie
tel.0923993382
email: asaro.filippo@comune.marsala.tp.it

**Comment by rvinzani** [comment]
E' possibile collegare le due posizioni dalla web app di ANPR e aggiornare i dati del soggetto.
Può seguire le istruzioni riportate al paragrafo 4.1 del documento che allego
[Risoluzione disallineamenti con l'Agenzia delle Entrate 11_02_2019.pdf](https://github.com/italia/anpr/files/4035056/Risoluzione.disallineamenti.con.l.Agenzia.delle.Entrate.11_02_2019.pdf)
