### ISSUE TITLE
ws [1001] - Errore iscrizione per nascita

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#186]
Buon giorno,
facendo seguito alla vostra risposta di risoluzione del problema relativo alla consultazione di paternità e maternità (bug #184), abbiamo effettuato una richiesta di iscrizione per nascita, utilizzando anche i suddetti dati, e per testare il collegamento con AE abbiamo richiesto l'attribuzione del codice fiscale per il nuovo nato (campo gestioneCF = 1), ma a seguito di una request valida, otteniamo in risposta un errore con codice 999 e descrizione 'Operazione non effettuabile'. Abbiamo ripetuto l'operazione, stavolta senza richiedere operazioni sul codice fiscale (campo gestioneCF non indicato), ma otteniamo di nuovo lo stesso errore. Gli id operazione comune sono rispettivamente 1505 e 1507.

A margine di questa segnalazione, riportiamo una incongruenza nella documentazione per quello che riguarda il Legame soggetto, in quanto nel file xsd '1000iscrizione.xsd'  il gruppo di informazioni è indicato come non obbligatorio, e nel file '1001-IscrizioneNascita.xlsx' è specificato che è obbligatorio solo nel caso di attribuzione famiglia = convivenza/istituto; se tale blocco viene omesso, il servizio però risponde con un errore bloccante EF006 (vedi id operazione comune 1509).

Il test è stato effettuato in data 26/05/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by Amucciarelli74** [comment]
Errata corrige: l'id operazione comune dell'iscrizione nascita con richiesta di attribuzione del codice fiscale è 1504 e non 1505.

**Comment by gcarbonin** [comment]
stavamo gia' analizzando queste due operazioni

**Comment by Amucciarelli74** [comment]
Buon giorno, avete qualche notizia in merito alle segnalazioni in oggetto? Abbiamo ripetuto le prove di iscrizione per nascita, ma otteniamo ancora lo stesso errore con codice 999 e descrizione 'Operazione non effettuabile'.
Se volete effettuare un controllo anche su questi ultimi test, gli id operazione comune sono rispettivamente 1662 (iscrizione con richiesta di attribuzione del codice fiscale) e 1659 (iscrizione con comunicazione del codice fiscale, nessuna operazione richiesta).
Il test è stato effettuato in data 01/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Risolto (altra issue collegata)
