### ISSUE TITLE
[3002] problemi con ricerca individui esterni al comune

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1860]
Id operazione ANPR: 16390004

Buongiorno,
un comune che seguiamo. a seguito del subentro effettuato in data odierna, facendo delle prove di ricerca, ottiene esito negativo per le ricerche nazionali, riesce solo ad ottenere i dati dei propri cittadini.

Potete verificare?
Grazie

**Comment by SAlberto** [comment]
Dovremmo aver risolto, erroneamente puntava all'ambiente di PRE-SUBENTRO

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
