### ISSUE TITLE
Annullamento Iscrizione Altri motivi a seguito di errata Decorrenza pratica

### ISSUE THREAD

**Issue by LauraOnofrio** [italia/anpr#1861]
Buongiorno,

sono Laura Onofrio del comune di Locate di Triulzi subentrato in marzo 2019.
Ho eseguito un'iscrizione altri motivi ed erroneamente indicato la data decorrenza iscrizione al 23/01/2019 al posto di 23/12/2019.
Pensando di fare correttamente ho operato una rettifica dati subentro indicando come data quella corretta.
In realtà non è stata recepita la modifica che mi aspettavo.

Ora mi è impossibile procedere all'annullamento dell'iscrizione a causa di questa rettifica dati subentro che è vincolante per l'annullamento. Ho provato ad annullare la rettifica dati subentro ma mi è impossibile.

I riferimenti delle operazioni sono i seguenti:

ID OPERAZIONE ANPR 178468851 ISCRIZIONE ALTRI MOTIVI
ID OPERAZIONE ANPR 178470751 RETTIFICA DATI (errata)
ID OPERAZIONE ANPR 181828430 RETTIFICA DATI (errata)

Chiedo come poter risolvere la situazione o se potete fare qualcosa per sbloccare le rettifiche errate.

**Comment by rvinzani** [comment]
Potete annullare tutte le operazioni riportate. Attendo esito delle vostre operazioni

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti potete aprirne una nuova facendo riferimento a questa
