### ISSUE TITLE
CODICE FISCALE non unificabili

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1862]
Buon giorno, ripeto il quesito relativo a "CODICE FISCALE #1858"- Cittadino Identificativo scheda attribuito dal Comune 1016140 - Identificativo scheda attribuito da ANPR 44116862 - in ANPR CON I SEGUENTI DATTI ERRATI c.f. CMRDMA95A01Z32VN - nato il 01/01/1995. In agenzia delle entrate risultano due posizioni una con i suddetti dati errati ed una con i seguenti dati corretti c.f.CMRDMA79T31Z329O nato il 31/12/1979. di conseguenza occorre allineare il dato corretto in ANPR. In seguito alle Sue indicazioni quando procedo al collegamento dei due codici fiscali mi da il seguente esito: **Esito AE: Operazione non effettuabile (Codice 95)**, lo stesso quando precedo da registrazione su mutamento di tutti i dati mi ritorna con : Individuate due posizioni in AT non unificabili (Codice: EAM9C)...grazie
Tel. 0923993382
email: asaro.filippo@comune.marsala.tp.it

**Comment by rvinzani** [comment]
Gent.le Sig. Asaro, vista la natura del problema le ho attribuito un numero di ticket 20931921 con cui sarà contattato per risolvere la problematica. Saluti
