### ISSUE TITLE
Richiesta referenti Comune di Napoli per la gestione dei casi di duplicazione

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#1863]
Sono dei servizi demografici del Comune di Valsamoggia.
Chiedo se sia possibile avere il recapito di un referente del Comune di Napoli che gestisca i casi di duplicazione.
La mia richiesta è motivata dal fatto che, con decorrenza 09/08/2019, ho iscritto in anagrafe una persona per immigrazione dal comune di Napoli, subentrato in ANPR il 21/09/2019.
La cancellazione del comune di Napoli è datata 23/09/2019 (apr4 cartaceo), ovviamente con decorrenza 09/08/2019, e questo ha generato la duplicazione.
L'urgenza della gestione dell'anomalia viene dal fatto che la persona è emigrata nel comune di Monterenzio il 12/12/2019 ed io non riesco a procedere alla conseguente cancellazione.
Il 12 dicembre stesso ho inviato una pec all'indirizzo anagrafe.emigrazione@pec.comune.napoli.it (consegnata ma non accettata) e non riesco ad ottenere un contatto telefonico

**Comment by rvinzani** [comment]
Inoltrato ad uno dei nostri riferimenti del comune di Napoli
