### ISSUE TITLE
Accesso ai dati anagrafici del Cittadino tramite CIE-CNS-SPID

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#1864]
Buongiorno,
abbiamo provato ad accedere tramite Spid alla procedura  dei servizi ANPR dedicata ai cittadini, ma non è andata a buon fine (sia attraverso Mozilla che internet explorer, sia da pc dell'ufficio che direttamente da casa propria). Il sito rimane in attesa per minuti senza esito positivo.
Contrariamente, con accesso tramite cellulare, il risultato è positivo.
Che soluzioni si possono adottare ? 
grazie
Barbara Malavolti Comune di Faenza

**Comment by cirospat** [comment]
ciao @bmalavolti 
anche a me è successa la stessa esperienza dall'ufficio (rete con firewall aziendale, quindi).
Però da smartphone con SPID mi fa accedere alla visura tranquillamente. 
Devo verificare da casa.

**Comment by rnapoli1983** [comment]
Buongiorno,

innanzitutto grazie per le vostre segnalazioni che sono sempre preziose al fine di migliorare il servizio.

Da quanto descritto il tutto potrebbe dipendere dal/i provider SPID che gestiscono l'autenticazione.

Vorrei chiedervi, se possibile, di indicarci:
- che provider di SPID state utilizzando;
- alcuni screen-shot per visualizzare dove è stato riscontrato precisamente il periodo di attesa 
  prolungato nella fase di autenticazione;

Rimango a disposizione.

Grazie mille

Cordiali saluti

**Comment by cirospat** [comment]
Io ho constatato che appeno clicco entra su SPID e seleziono uno o altro
operatore si blocca la pagina e dopo alcuni secondi da un messaggio di
errore.
Per ora sono mobile e non posso incollare screenshot in quanto da mobile
funziona correttamente l'accesso alla visura.



[Scusa la brevità, rispondo da mobile]
Ciro Spataro
cirospat@gmail.com
cirospat.readthedocs.io

Il ven 10 gen 2020, 14:58 rnapoli1983 <notifications@github.com> ha scritto:

**Comment by patriziasaggini** [comment]
Buongiorno,
anch'io ho avuto lo stesso problema, in particolare dal PC dell'ufficio;
da casa con PC, con tablet e smartphone nessun problema

Questa è la schermata di errore che appare dopo la scelta del provider 
(io ho provato sia con Poste e sia con Lepida, l'esito è sempre quello)

![image](https://user-images.githubusercontent.com/42801194/72159830-861b6800-33bd-11ea-8120-e5df9de37537.png)

Io sono a Bologna, Ciro è a Palermo, tenderei ad escludere blocchi di rete....

**Comment by rnapoli1983** [comment]
OK.

Analizziamo il contenuto dei post che comunque è già utile per una prima analisi e vi facciamo sapere.

Grazie mille.

Cordiali saluti

**Comment by cirospat** [comment]
solo per un dettaglio:
da casa ho fatto accesso e funziona perfettamente, come da mobile.
Solo dall'ufficio non mi permette di fare accesso.

**Comment by bmalavolti** [comment]
Ho riprovato anch'io da casa da Mac con Safari e funziona regolarmente . il nostro provider è Lepida e la schermata è comunque identica alla Dr.ssa Saggini
Grazie 
Barbara Malavolti

**Comment by rnapoli1983** [comment]
Buongiorno,

stiamo analizzando quanto descritto.

Comunque dalle ulteriori precisazioni fatte e dagli esiti positivi riscontrati da altri dispositivi, sembra che il problema si legato a quella postazione ed è relativo alla fase di autenticazione col provider SPID.

**Comment by cvignati** [comment]
Buongiorno,
io ho provato adesso in ufficio con SO win 7 ed ho utilizzato sia Firefox 72.0.1 che Chrome 79.0.3945.117 e funziona con praticamente tutti i Provider SPID

**Comment by patriziasaggini** [comment]
Se può essere utile, ho riprovato anche ora, e dopo aver scelto l'IDP dalla tendina ricevo lo stesso errore;
sembra che sia un problema comune a tutti i provider di SPID (questa volta ho scelto SIELTE)

Riallego lo screenshot
![image](https://user-images.githubusercontent.com/42801194/72254498-8194c080-3604-11ea-92ad-44ddb5c1fea9.png)

**Comment by rnapoli1983** [comment]
Al momento le consiglio, se possibile, di provare con un altro browser, oppure utilizzare un'altra postazione.

Tipicamente il messaggio "ERR_CONNECTION_CLOSED"  indica che la disconnessione imprevista è iniziata da server web od un server proxy, che elaborano la richiesta tramite il browser utilizzato.

Purtroppo anche noi non abbiamo evidenzia al momento di malfunzionamenti simili.

Tuttavia questa prova, come le altre effettuate, può essere indice del fatto che il problema sia la postazione da dove sta tentando l'autenticazione verso SPID.

Rimango a disposizione.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

per avere altri spunti di analisi, chiederei a chi di voi ha avuto problemi dalla postazione di:

- provare ad accedere a tutti i provider di SPID, anche senza avere le credenziali, e notare se si riesce 
  a visualizzare la login o si ha sistematicamente l'errore  "ERR_CONNECTION_CLOSED";

- provare ad accedere a SPID di Agenzia Entrate dal link: 
  https://telematici.agenziaentrate.gov.it/Main/index.jsp
  e vedere se si riesce ad accedere:
  
![image](https://user-images.githubusercontent.com/30468060/72353232-ff7bc900-36e3-11ea-8b4f-053e7a9620d8.png)

 Attendo un vostro riscontro.

 Grazie mille.

**Comment by cirospat** [comment]
> * provare, dalla postazione che non funziona, ad accedere a SPID di Agenzia Entrate dal link:
>   https://telematici.agenziaentrate.gov.it/Main/index.jsp
> 
> ![image](https://user-images.githubusercontent.com/30468060/72353232-ff7bc900-36e3-11ea-8b4f-053e7a9620d8.png)
> 
> Attendo un vostro riscontro.
> Grazie mille.

fatto e accedo tranquillamente dall'ufficio

**Comment by patriziasaggini** [comment]
Ho appena provato ad accedere al servizio di Agenzia delle Entrate, senza nessun tipo di problema (Idp LEPIDA ID).

Per quanto riguarda l'accesso alle visure di ANPR il risultato è sempre lo stesso, anche scegliendo qualsiasi tipo di provider il risultato non cambia, la schermata di errore è sempre quella.

**Comment by rnapoli1983** [comment]
Grazie mille per le prove effettuate.

Ora abbiamo sicuramente un indizio valido su cui indagare.

Sarà mia premura aggiornarvi sulla soluzione del problema.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

vi aggiorno.

Possiamo fare un'ultima prova che è la seguente.

Chiederei, se possibile,  a @patriziasaggini  di collegarsi a:
https://ping.eu/  
e comunicarci l'ip visualizzato (ip pubblico con il quale si esce su internet) così che possiamo tracciarlo sui nostri apparati e monitorare la richiesta che viene fatta per l'accesso alla VisuraCittadino con SPID e vedere se ci sono opportuni errori.

Il sospetto purtroppo è che il problema possa dipendere a questo punto esclusivamente (come scritto nei post precedenti) da apparti proxy o firewall presenti nelle configurazioni di rete delle vostre postazioni e che per qualche motivo blocchino il tentativo di connessione verso la URL indicata nei screen-shots da voi inviati.

Attendo un vostro riscontro.

Cordiali saluti

**Comment by cirospat** [comment]
@rnapoli1983 
faccio l'esperimento pure io così hai dati in più (tanto ho lo stesso problema di @patriziasaggini).
IP visualizzato: 93.63.41.193

**Comment by rnapoli1983** [comment]
Assolutamente si.

Intanto comunico l'ip ai miei colleghi responsabili del monitorin e le scrivo quando può provare.

Altra domanda è se voi siete su rete SPC.

**Comment by cirospat** [comment]
> Altra domanda è se voi siete su rete SPC.

Si confermo da Palermo (comune).

**Comment by rnapoli1983** [comment]
Può provare quando vuole.

Faccia più di una prova.

Grazie mille

**Comment by rnapoli1983** [comment]
Ci comunichi quando ha fatto il test così controlliamo

**Comment by patriziasaggini** [comment]
@rnapoli1983 
Il mio indirizzo IP è 195.62.168.36
la rete è dedicata solo alle PA dell'Emilia Romagna ed è gestita da Lepida.

Fatemi sapere quando posso fare una prova
Grazie!

**Comment by rnapoli1983** [comment]
@patriziasaggini  può provare

**Comment by patriziasaggini** [comment]
Ho appena riprovato, risultato identico a prima.

Se comunque riusciamo ad utilizzare i servizi dell'Agenzia delle Entrate, non dovrebbe essere la stessa cosa per ANPR?

Grazie!

**Comment by rnapoli1983** [comment]
Buonasera,

I servizi esposti sono diversi sia nelle URL che nei meccanismi di sicurezza.

Abbiamo appena analizzato i log dei nostri apparati di sicurezza, e nè le richieste di @patriziasaggini  e nè le richieste di @cirospat ci risultano arrivate.

Questo significa che non riuscite a raggiungere l'endpoint  spid.anpr.interno.it (risolto con ip: 217.175.52.183).

Il problema quindi è relativo alla rete delle vostre postazioni di lavoro.

Rimango a disposizione.

Cordiali saluti

**Comment by cirospat** [comment]
> Questo significa che non riuscite a raggiungere l'endpoint spid.anpr.interno.it (risolto con ip: 217.175.52.183).

@rnapoli1983  confermo pienamente che non riesco a raggiungerlo dall'ufficio.
Vuol dire che le visure ANPR le farò da casa.
Grazie del lavoro svolto e del tempo dedicato.
Saluti cordiali

**Comment by rnapoli1983** [comment]
@cirospat di nulla si figuri è un nostro dovere.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

quando reputate concluso l'argomento vi chiederei di chiudere la issue.

Cordiali saluti

**Comment by cirospat** [comment]
> quando reputate concluso l'argomento vi chiederei di chiudere la issue.

si credo che a questo punto, abbiamo analizzato il problema, e quindi possiamo chiudere l'issue.
Grazie ancora e saluti

**Comment by cirospat** [comment]
> > quando reputate concluso l'argomento vi chiederei di chiudere la issue.
> 
> si credo che a questo punto, abbiamo analizzato il problema, e quindi possiamo chiudere l'issue.
> Grazie ancora e saluti

non mi da il tasto di "`close issue`". Non so perchè.

**Comment by rnapoli1983** [comment]
Attendevo il parere di @patriziasaggini .

Facciamo così la chiudo se poi voi ritenute opportuno possiamo aprirla di nuovo oppure crearne un'altra che fa riferimento a questa.

Cordiali saluti

**Comment by iessicatoro** [comment]
Salve, le inoltro il tracert: 


gp@nb09401:~$ traceroute [ callto:217.175.52.183 | 217.175.52.183 ] 
traceroute to [ callto:217.175.52.183%20%28217 | 217.175.52.183 (217 ] . [ callto:175.52.183%29,%2030 | 175.52.183), 30 ] hops max, 60 byte packets 
1 _gateway [ callto:%28172.16.5.1%29%201.364 | (172.16.5.1)  1.364 ] ms 1.316 ms 1.288 ms 
[ callto:2%20192.168.120.2%20%28192 | 2  192.168.120.2 (192 ] . [ callto:168.120.2%29%201.044 | 168.120.2)  1.044 ] ms * * 
3 * * * 
[ callto:4%20195.62.178.66%20%28195 | 4  195.62.178.66 (195 ] . [ callto:62.178.66%29%202.564 | 62.178.66)  2.564 ] ms 3.321 ms 2.178 ms 
5 mip-13.lepida.it [ callto:%28195.62.188.118%29%204.812 | (195.62.188.118)  4.812 ] ms 4.463 ms 4.240 ms 
6 omega.lepida.it [ callto:%28195.62.188.117%29%2024 | (195.62.188.117)  24 ] .538 ms 23.779 ms 19.750 ms 
[ callto:7%20172.18.250.19%20%28172 | 7  172.18.250.19 (172 ] . [ callto:18.250.19%29%208.828 | 18.250.19)  8.828 ] ms 9.264 ms 11.653 ms 
[ callto:8%20185.182.141.92%20%28185 | 8  185.182.141.92 (185 ] . [ callto:182.141.92%29%208.691 | 182.141.92)  8.691 ] ms 9.058 ms 8.889 ms 
[ callto:9%20185.182.141.100 | 9  185.182.141.100 ] [ callto:%28185.182.141.100%29%20118 | (185.182.141.100)  118 ] .584 ms 118.325 ms 117.309 ms 
[ callto:10%20185.182.141.101 | 10  185.182.141.101 ] [ callto:%28185.182.141.101%29%2019 | (185.182.141.101)  19 ] .260 ms 19.255 ms 20.406 ms 
[ callto:11%2010.0.2.169%20%2810.0.2 | 11  10.0.2.169 (10.0.2 ] . [ callto:169%29%2019.832 | 169)  19.832 ] ms 20.095 ms 19.768 ms 
[ callto:12%2010.0.2.169%20%2810.0.2 | 12  10.0.2.169 (10.0.2 ] . [ callto:169%29%2020.090 | 169)  20.090 ] ms 21.719 ms 19.855 ms 
[ callto:13%2010.0.2.178%20%2810.0.2 | 13  10.0.2.178 (10.0.2 ] . [ callto:178%29%2019.785 | 178)  19.785 ] ms 19.708 ms 19.627 ms 
14 * * * 
15 * * * 
16 * * * 
17 * * * 
18 * * * 
19 * * * 
20 * * * 
21 * * * 
22 * * * 
23 * * * 
24 * * * 
25 * * * 
26 * * * 
27 * * * 
28 * * * 
29 * * * 
30 * * * 
gp@nb09401:~$ 


********************************************************************************* 
Iessica Toro 
Comune di Piacenza 
Sistemi Informativi 
Via Beverora 57 - 29121 Piacenza 
Tel. 0523.492544 
********************************************************************************** 


Da: "rnapoli1983" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Inviato: Giovedì, 16 gennaio 2020 11:45:21 
Oggetto: Re: [italia/anpr] Accesso ai dati anagrafici del Cittadino tramite CIE-CNS-SPID (#1864) 



Attendevo il parere di [ https://github.com/patriziasaggini | @patriziasaggini ] . 

Facciamo così la chiudo se poi voi ritenute opportuno possiamo aprirla di nuovo oppure crearne un'altra che fa riferimento a questa. 

Cordiali saluti

**Comment by LORELLAB** [comment]
Con SPID sono entrata tranquilamente mentre per entrare con la CIE bisogna installare qualcosa? Sembra mi chieda un certificato.. Vorrei saperlo per rispondere a domanda dei miei residenti Grazie.

**Comment by rnapoli1983** [comment]
Buonasera,

a questo link:

https://www.cartaidentita.interno.gov.it/identificazione-digitale/software-cie/

può trovare tutto il software necessario.

Il riferimento principale per questa tematica e tutte le info o eventuali problematiche è l'IPZS (Istituto Poligrafico Della Zecca dello Stato). 

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

visto l'apertura della issue #1883, questa la chiudo d'ufficio.

Cordiali saluti.
