### ISSUE TITLE
[5008] Rettifica dati di Matrimonio: aggiornamento errato del Coniuge

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1865]
ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA (037-054)

capita una cosa un po' strana.

soggetto che ha subìto l'aggiornamento dei dati di vedovanza a causa del decesso del coniuge.
il comune si accorge di un'anomalia da subentro nel comune di matrimonio e procede con una comunicazione di rettifica dei dati di matrimonio (tipoMutazione 12) prima di aggiornare lo stato civile.
la comunicazione viene accettata ed il comune di matrimonio viene corretto, ma adesso il soggetto risulta coniugato con sè stesso (nonostante i dati di matrimonio della comunicazione siano corretti)

il soggetto in questione ha idANPR 19037687
la comunicazione che ha generato la variazione (ws 5008) ha idOperazioneComune 2020000158

potete verificare per capire cosa sia successo?

grazie
Alessandro Monopoli ADS

**Comment by fferraguto** [comment]
Salve,
potreste cortesemente verificare se la situazione è stata corretta?
Grazie.

**Comment by AMonopoliADS** [comment]
la situazione è stata corretta e siamo riusciti a completare l'aggiornamento da coniugato a vedovo.
cosa ha scatenato l'errato aggiornamento del coniuge?
giusto per capire se si può riverificare il problema

grazie

**Comment by fferraguto** [comment]
Salve,
è stato un errore nel processo di mutazione 12.
Lo stiamo correggendo.
A presto.
