### ISSUE TITLE
Convenzioni per le consultazioni anagrafiche da parte delle PA

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1866]
Villa Cortese - Produzione

Buongiorno,
riallacciandomi alle [Issue 632](https://github.com/italia/anpr/issues/632) relativa alle convenzioni tra Ministero dell'Interno e altri Ministeri per la consultazione del db ANPR da parte ad esempio di Carabinieri, Polizia di Stato, GdF, etc, volevo sapere se fossero state stipulate altri convenzioni oltre a quelle già presenti 18 mesi fa con Agenzia delle Entrate, Motorizzazione, INPS e ISTAT.

Grazie

**Comment by FilippoPapi** [comment]
buongiorno,
ad oggi non sono state stipulate ulteriori convenzioni. E' in corso di predisposizione un'applicazione per gestire le richieste di convenzione.
saluti
