### ISSUE TITLE
errore su mutazione/famiglia convivenza

### ISSUE THREAD

**Issue by leopaul76** [italia/anpr#1867]
Ambiente di produzione - Comune di Valenza (AL)

Buongiorno,  
non riesco a mutare la residenza ad un cittadino di un comune subentrato (Novi Ligure) avente ID 35148672, al termine dell'operazione il sistema riferisce il seguente errore: 
Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto (Codice: EN203)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-10 13:49:56 , idOperazioneANPR 184052250 (Codice: EN527)
Contattato telefonicamente il Novi Ligure afferma di non avere operazioni in sospeso per il soggetto da mutare.
Resto in attesa di Vs. riscontro.
Grazie e saluti.
Comune di Valenza
per info 0131949210

**Comment by azabatta** [comment]
Buonasera, 
per il cittadino in trattamento è presente un’operazione di “Mutazione tutti i dati” in sospeso  inserita in data 08/01/2020.
Per eliminarla seguire i passaggi di seguito riportati: 
•	accedere alla web app di ANPR
•	selezionare la sezione Registrazione
•	selezionare il tipo operazione “Mutazione tutti i dati”
•	selezionare l'iniziativa: operazione d'ufficio
•	selezionare il bottone "ELENCO OPERAZIONI SOSPESE" : il sistema propone una griglia con le 
         operazioni  che risultano sospese
•	individuare quella di interesse (se presenti più occorrenze) e cliccare sul tasto “Elimina”.

Se l'utente del comune desidera essere seguito in linea può contattare il numero verde 800863116.
Saluti
