### ISSUE TITLE
Id famiglia atrribuito dal comune non modificabile

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1868]
Buongiorno,

dobbiamo aprire un'irreperibilità per il soggetto con id 28682840, ma è presente un disallineamento che non siamo in grado di sanare.
In data 02/09/2019 il comune di Milano aveva eseguito una mutazione famiglia/convivenza che è stata successivamente annullata in data 07/11/2019; tuttavia al soggetto è rimasto l'id famiglia atrribuito dal comune di Milano (2122350) con relativo codice istat (015146) e non riusciamo a modificarlo, in quanto il campo istat non è editabile (abbiamo utilizzato la funzione "mutazione famiglia/convivenza" tipo  operazione --> "motivo famiglia/specie convivenza").
Potreste cortesemente intervenire voi?

Grazie.

Cordialità.

UPI Torino

**Comment by frmariani** [comment]
Potete verificare adesso per favore ?

**Comment by UpiTorino** [comment]
Adesso risulta essere corretto.
Grazie mille e buona giornata.

UPI Torino
