### ISSUE TITLE
Invocazione WS 5001 - errore EN493

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1870]
ambiente di PRODUZIONE - comune di CAPONAGO

Questa mattina invocando il servizio 5001, per immigrazione da comune subentrato di un'intera famiglia, il ws risponde errore EN493 L'utente non dispone dei privilegi per eseguire l' operazione

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 09:55:27 , mittente 108052 , idOperazioneComune 2020011509530

Si resta in attesa di gentile riscontro.

**Comment by mttfranci** [comment]
Salve, possibile che l'idOperazioneComune fosse 20200115095305 e non 2020011509530?

Sui sistemi abbiamo trovato solo questa operazione : 
idEvento assente EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 09:55:27 , mittente 108052 , idOperazioneComune 20200115095305 

Inoltre nella testata compare come data operazione del client il 13 pur essendo una operazione del 15 : 

```
<idOperazioneComune>20200115095305</idOperazioneComune>
<codMittente>108052</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>5001</operazioneRichiesta>
<dataOraRichiesta>2020-01-13T13:29:00+01:00</dataOraRichiesta>
```

**Comment by GabriellaBallabio** [comment]
Buongiorno, scusi ma abbiamo fatto diverse prove l'ultima è la seguente :

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 09:55:27 , mittente 108052 , idOperazioneComune 20200115095305


                <testataRisposta>
                    <idOperazioneComune>20200115095305</idOperazioneComune>
                    <codMittente>108052</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>5001</operazioneRichiesta>
                    <dataOraRichiesta>2020-01-13T13:29:00+01:00</dataOraRichiesta>
                    <protocolloComune>305</protocolloComune>
                    <dataProtocolloComune>2020-01-13</dataProtocolloComune>
                    <dataDecorrenza>2020-01-13</dataDecorrenza>
                    <idOperazioneANPR>0</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN493</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione </testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 09:55:27 , mittente 108052 , idOperazioneComune 20200115095305</testoErroreAnomalia>
                    </errore>
                </listaErrori>

**Comment by mttfranci** [comment]
Salve, il diagnostico restituito dipende da un controllo di sicurezza mirato alla gestione dei soggetti sotto protezione e in preadozione.

Ad ogni modo il problema è che nella richiesta non è stata fornito alcun dato identificativo della famiglia : 

```
    <famigliaConvivenza>
        <famigliaAire>N</famigliaAire>
        <tipoScheda>3<</tipoScheda>
    </famigliaConvivenza>
```

Saluti

Assistenza ANPR

```
<ns3:it.sogei.anpr._5000mutazione.Richiesta5001` xmlns:ns2="http://sogei.it/ANPR/5000mutazione" xmlns:ns3="info.source4code.jaxb.model">
    <testataRichiesta>
        <idOperazioneComune>20200115095305</idOperazioneComune>
        <codMittente>108052</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>5001</operazioneRichiesta>
        <dataOraRichiesta>2020-01-13T13:29:00+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <protocolloComune>305</protocolloComune>
        <dataProtocolloComune>2020-01-13</dataProtocolloComune>
        <tipoInvio>PROD</tipoInvio>
        <dataDecorrenza>2020-01-13</dataDecorrenza>
        <dataDefinizionePratica>2020-01-13</dataDefinizionePratica>
        <nomeApplicativo>SERDEM</nomeApplicativo>
        <versioneApplicativo>NOV2019</versioneApplicativo>
        <fornitoreApplicativo>SCAP SISTEMI</fornitoreApplicativo>
    </testataRichiesta>
    <famigliaConvivenza>
        <famigliaAire>N</famigliaAire>
        <tipoScheda>3<</tipoScheda>
    </famigliaConvivenza>
```
