### ISSUE TITLE
Ricerca dati anagrafici soggetti residenti in altro comune subentrato

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1871]
ambiente di PRODUZIONE - COMUNE DI CAPONAGO

Utilizzando il WS 3002 per ricercare i dati anagrafici di un individuo residente in altro comune subentrato (CAVENAGO DI BRIANZA)  il WS ritorna l'errore EN122 La richiesta effettuata non produce alcun risultato.
Nei criteri di ricerca è stato specificato il codice fiscale come criterio di ricerca. In ricercaNazionale è stato specificato il valore 1.

**Comment by GabriellaBallabio** [comment]
Allego i file di richiesta e di risposta :
[Richiesta3002.txt](https://github.com/italia/anpr/files/4071947/Richiesta3002.txt)
[EsitoWS_Richiesta3002.txt](https://github.com/italia/anpr/files/4071948/EsitoWS_Richiesta3002.txt)

**Comment by mttfranci** [comment]
Che client avete usato per eseguire l'interrogazione? Nella richiesta arrivata ai nostri sistemi non compare il parametro ricercaNazionale. Questo può accadere se il client usato non lo gestisce (Prendendo come riferimento la nostra implementazione di esempio, se gli oggetti JAXB che modellano la richiesta sono stati generati con una versione dei WSDL che non usano quel campo).
In tali casi anche se in un sorgente XML un elemento compare, potrebbe essere ignorato in fase di marshalling.
Il vostro caso potrebbe ricadere in questa situazione?
Saluti

Assistenza ANPR

**Comment by GabriellaBallabio** [comment]
Facendo riferimento all'issue #1794 - Client di TEST per invocazione WS ANPR

Abbiamo scaricato dal repository su GitHub (https://github.com/italia/anpr-client-example/)  i sorgenti in Java del client che avete messo a disposizione.
Non saprei dire che versione WSDL utilizzano questi sorgenti. Come posso individuare la versione di WSDL ? Forse potete saperlo Voi?

**Comment by amollicone1982** [comment]
Il client di test, come specificato nella issue, è solo un client di esempio fatto con una versione dei wsdl sicuramente non aggiornata. Basta scaricare la nuova versione dei wsdl e xsd da https://www.anpr.interno.it/portale/documentazione-tecnica (Tracciati XSD e WSDL), copiarli nel path 
src/main/resorces/wsdl del client e rifare il build.

**Comment by GabriellaBallabio** [comment]
Buongiorno
abbiamo scaricato la nuova versione dei wsdl e xsd  e li abbiamo copiati nel path
src/main/resorces/wsdl del client e rifatto il build , ma non abbiamo risolto sembra che il client non consideri il parametro della ricercaNazionale, potete indicarci in quale src viene gestito ? così che lo si possa modificare ? Grazie
