### ISSUE TITLE
[5008] Dubbi su errori di ritorno

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1872]
Buongiorno,

ambiente di produzione
id Operazione ANPR: 186130294
Operazione 5008

Con questa operazione stavamo cercando di aggiornare i dati del matrimonio precedente al divorzio, ma otteniamo diversi errori nella risposta.
A cosa dovuti?
Come possiamo risolvere?

Ringrazio anticipatamente.

**Comment by rvinzani** [comment]
L'unico errore bloccante è  EN413 - Il soggetto risulta cancellato (MASSIMO BOETTI)
Nella mutazione dati del matrimonio, nell'inserire i dati del coniuge non deve essere indicato l'idANPR perchè si riferisce ad una scheda cancellata
