### ISSUE TITLE
Errore Eliminazione Mutazione Residenza per accertamento negativo

### ISSUE THREAD

**Issue by FulvioDeda** [italia/anpr#1873]
Salve, per conto del comune di PORTOMAGGIORE (FE)

in PRODUZIONE
il cliente sta cercando di annullare il procedimento id ANPR 152868768,
il sistema risponde che esiste un'operazione successiva ( Mutazione famiglia id ANPR 167862505) da Eliminare.
Però quando si tenta di cancellare quest'ultima il sistema risponde:
'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie
movimentate dall'operazione stessa; Informazioni sull'operazione da fornire
in caso di assistenza : data 2020-01-10 08:05:35 , idOperazioneANPR
183336506

Vorremmo sapere come risolvere

Grazie mille in anticipo

**Comment by frmariani** [comment]
non sono riuscita a trovare l'operazione fallita dell'annullamento dell'operazione idanpr 152868768 ;
per favore mandate l'annullamento dell'operazione idanpr 152868768 per ripristino posizione precedente ed inviate l'idanpr dell'operazione fallita

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
