### ISSUE TITLE
EN203 - Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto

### ISSUE THREAD

**Issue by carla967** [italia/anpr#1874]
CASATENOVO AMBIENTE PRODUZIONE 15/01/2020

In data odierna stiamo tentando di iscrivere dall'AIRE di Roncello (comune subentrato) 4 individui, ma riceviamo il seguente errore:
ERRORE DA ANPR:
EN203 - Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 12:13:08 , idOperazioneANPR 186813220

Abbiamo richiesto al Comune di Roncello di verificare le operazioni in sospeso e ci comunicano che hanno sistemato tutto ma l'errore persiste.

Su indicazione del vostro servizio di assistenza abbiamo inserito questa segnalazione.
Potete aiutarci?

Ringrazio 

Carla Aprile Apkappa s.r.l.

**Comment by rvinzani** [comment]
Esiste un'operazione sospesa dal comune di Roncello per il soggetto con idANPR 64155334. Il comune di Roncello deve selezionare sulla web app di ANPR come tipo operazione Mutazione tutti i dati, operazione d'ufficio e premere il tasto Operazioni sospese e selezionare la voce eliminare sulla riga relativa al soggetto che le ho indicato
