### ISSUE TITLE
[4005][N010] Cambio residenza

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1876]
Salve,

esiste un modo per simulare un cambio di residenza tra due comuni subentrati in un ambiente di free test?
Quello che vogliamo fare è poter  interrogare da ANPR con il servizio 4005 le notifiche ricevute di tipo N010 che corrispondono a un' operazione 5005 effettuato da un altro comune di destinazione.

Saluti

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by mttfranci** [comment]
Per effettuare questo tipo di test vi suggeriamo di richiedere una seconda utenza relativo ad un altro comune fittizio per effettuare le operazioni che richiedono una interazione tra due comuni
 
Saluti 
Assistenza ANPR
