### ISSUE TITLE
IMPOSSIBILITA' ISCRIZIONE AIRE CON DECORRENZA PRECEDENTE CANCELLAZIONE IRREPERIBILITA'

### ISSUE THREAD

**Issue by AnagrafeCornaredo** [italia/anpr#1877]
Buongiorno, si chiede cortesemente di ripristinare la posizione codice anpr 72463994 prima della cancellazione per irreperibilità (8/1/2020) in quanto è pervenuta dal Consolato italiano la richiesta di iscrizione AIRE con decorrenza 17/12/2019 e non si riesce a procedere.
Grazie
Comune di Cornaredo - Silvia 02/93263224

**Comment by ncapozzi** [comment]
Fornita assistenza telefonica per annullamento della cancellazione e la mutazione dati AIRE da applicazione WEB.

N. Capozzi
