### ISSUE TITLE
ANNULLARE ISCRIZIONE DALLA NASCITA IN APR

### ISSUE THREAD

**Issue by AnagrafeCornaredo** [italia/anpr#1878]
E' necessario annullare iscrizione in APR dalla nascita presso il padre  e procedere all'iscrizione per nascita all'AIRE presso la madre di 84870487, non si riesce e il codice errore e': AEE95 Operazione non effettuabile EN527 idOperazioneANPR 186569770.
Grazie
CORNAREDO - Silvia 02/93263224

**Comment by rvinzani** [comment]
E' possibile annullare l'iscrizione ma non revocare l'emissione del CF che può essere effettuata solo entro la mezzanotte del giorno stesso dell'emissione. Dovreste quindi effettuare nuovamente l'annullamento dell'iscrizione per nascita senza annullamento del codice fiscale
