### ISSUE TITLE
[5008] Integrazione dati AIRE (matrimonio) - Errore EN272

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1879]
Buongiorno,
per il Comune di Torino avremmo necessità di integrare i dati di Matrimonio di un soggetto AIRE che al subentro aveva indicato solo il cognome del coniuge.
Abbiamo effettuato una prova in **PRESUBENTRO** e il riferimento del soggetto su cui effettuare la mutazione di rettifica  è ID ANPR 60179348.
Questa prova è utile per poi realizzare una soluzione massiva per tutti i soggetti nella stessa condizione.

Effettuando la mutazione tramite web app e scegliendo il coniuge (ID 60178880) si hanno i seguenti errori:
Alla data 04-09-1993 il soggetto XXXX YYYY risulta gia' coniugato o unito civilmente con un altro soggetto (Codice: EN272)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-15 11:02:07 , idOperazioneANPR 16412015 (Codice: EN527)  

Come è possibile procedere per aggiornare correttamente i dati del matrimonio (coniuge compreso)?
La nostra necessità è quella di aggiornare massivamente tutti i soggetti AIRE nella stessa condizione.

Grazie,
Silvio Guala

**Comment by ncapozzi** [comment]
Buonasera,
nella sezione matrimonio del file AIRE trasmesso al subentro è possibile indicare solo il cognome del coniuge e pertanto quando il coniuge viene registrato in ANPR il cognome è quello trasmesso mentre risulta "Senza nome". Se i coniugi sono entrambi in ANPR il problema vale per tutti e due.

Per trasmettere i dati del matrimonio completi con il 5008 è necessario procedere in due step:
1 - prima trasmettere un 5008, per es. della moglie, indicando nella sezione coniuge i dati del marito senza CF e idsoggetto ANPR
2 - trasmettere quindi i dati completi del marito, indicando nella sezione coniuge i dati completi della moglie incluso CF e idsoggettoANPR. A questo punto le schede vengono "riconciliate"

Per quanto sopra esposto non è possibile effettuare un aggiornamento massivo che oltre tutto non è richiesto dalla norma.
Qualora il Comune debba movimentare una scheda AIRE successivamente al subentro può procedere al completamento puntuale dei dati. 

Si fa presente che è prevista una revisione generale della gestione matrimonio che però è tuttora da pianificare.

Qualora abbiate bisogno di ulteriori chiarimenti credo sia più semplice sentirci telefonicamente. Potente in questo caso indicare un recapito telefonico.

N. Capozzi

**Comment by CSI-Piemonte-Demografia** [comment]
Grazie mille per la precisazione (anche telefonica), procederemo come descritto.
