### ISSUE TITLE
WS 6001 - Certificato di residenza - SUBENTRO

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#188]
In ambiente di subentro, dopo aver aperto un procedimento di iscrizione Anagrafica per altri motivi e avere inviato con successo la registrazione di prima iscrizione, in attesa di definizione della pratica, a fronte di una richiesta di certificato di residenza il sistema ANPR risponde con il seguente errore:

Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato

Come mai?
Grazie

Patrizia Saggini
Comune di Anzola dell'Emilia

**Comment by gcarbonin** [comment]
Si controlla che non ci siano procedimenti aperti per i soggetto prima di emettere un certificato. E' possibile ottenere comunque il certificato indicando 1 nel campo forzaCertificazione del WS di richiesta
