### ISSUE TITLE
[5008] Dubbi su errori di ritorno (2)

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1880]
Buongiorno,
@rvinzani 
in riferimento alle issue #1872 
il discorso del Coniuge cancellato vale anche per Paternità e Maternità?

Grazie

**Comment by SAlberto** [comment]
E' veramente necessario che esista questo controllo? 
L'IdANPR che noi mandiamo è riconducibile a un individuo cancellato, ma comunque presente nel vostro archivio

**Comment by rvinzani** [comment]
E' sufficiente non inviare l'idANPR tra i dati del soggetto

**Comment by SAlberto** [comment]
Grazie
