### ISSUE TITLE
[Risoluzione dis. con AE] Errore EN527

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1881]
Operazione eseguita da PORTALE ANPR
IdOperazioneANPR: 185659280
Codice errore: EN527
Tipo di operazione: Risoluzione disallineamenti con Agenzia Entrate

Il comune ha chiamato il vostro numero verde, ma gli è stato detto di avvisare la software house e aprire una issue qui.

Potete verificare il problema impedisce l'unificazione?

Grazie

**Comment by frmariani** [comment]
per unificare due CF si deve selezionare l'apposito flag "Collega codici fiscali"

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
