### ISSUE TITLE
[5008] - Posizione professionale - richiesta informazioni

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1882]
Buongiorno,

volevamo chiedervi un chiarimento sulle posizioni professionali A e B contemplate nella tabella 9 delle professioni. Il comune di Torino, ambiente di **produzione**, ha rettificato di recente la posizione professionale del soggetto (id soggetto 40893394). Nell'operazione (id 186638923) è stato passato `<posizioneProfessionale>A</posizioneProfessionale>` , ma sulla scheda soggetto consultabile dalla WebApp non è presente la relativa transcodifica "Dirigente o impiegato".

Grazie.
Chiara Leanza

**Comment by mttfranci** [comment]
Salve, potreste riprovare la consultazione?
Saluti

Assistenza ANPR

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno,

la consultazione è andata a buon fine, infatti la posizione professionale ora risulta Dirigente o impiegato. 
Vi ringraziamo per la celerità.

Cordialmente,
Chiara Leanza
