### ISSUE TITLE
Accesso ai dati anagrafici del Cittadino tramite CIE-CNS-SPID (#1864)

### ISSUE THREAD

**Issue by iessicatoro** [italia/anpr#1883]
Buongiorno,
sono Iessica Toro e vi scrivo dal comune di Piacenza.
Ho fatto effettuare alcune prove per il problema #1864 e vi inoltro il tracert effettuato dai tecnici:

gp@nb09401:~$ traceroute 217.175.52.183
traceroute to 217.175.52.183 (217.175.52.183), 30 hops max, 60 byte packets
 1  _gateway (172.16.5.1)  1.364 ms  1.316 ms  1.288 ms
 2  192.168.120.2 (192.168.120.2)  1.044 ms * *
 3  * * *
 4  195.62.178.66 (195.62.178.66)  2.564 ms  3.321 ms  2.178 ms
 5  mip-13.lepida.it (195.62.188.118)  4.812 ms  4.463 ms  4.240 ms
 6  omega.lepida.it (195.62.188.117)  24.538 ms  23.779 ms  19.750 ms
 7  172.18.250.19 (172.18.250.19)  8.828 ms  9.264 ms  11.653 ms
 8  185.182.141.92 (185.182.141.92)  8.691 ms  9.058 ms  8.889 ms
 9  185.182.141.100 (185.182.141.100)  118.584 ms  118.325 ms  117.309 ms
10  185.182.141.101 (185.182.141.101)  19.260 ms  19.255 ms  20.406 ms
11  10.0.2.169 (10.0.2.169)  19.832 ms  20.095 ms  19.768 ms
12  10.0.2.169 (10.0.2.169)  20.090 ms  21.719 ms  19.855 ms
13  10.0.2.178 (10.0.2.178)  19.785 ms  19.708 ms  19.627 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
gp@nb09401:~$

**Comment by iessicatoro** [comment]
Si, scusi non l'ho precisato ma stavo seguendovi e nel contempo ho testato anch'io

**Comment by LORELLAB** [comment]
Con SPID sono entrata tranquilamente mentre per entrare con la CIE bisogna installare qualcosa? Sembra mi chieda un certificato.. Vorrei saperlo per rispondere a domanda dei miei residenti Grazie.

**Comment by iessicatoro** [comment]
Buongiorno,
dopo aver aperto un ticket a Lepida in quando dal trace risultava che il problema fosse fermo appunto dopo Lepida, ci hanno risposto che il provider del servizio  informa che il sito è raggiungibile soltanto da indirizzi pubblici non SPC nonostante questo servizio sia esposto come indirizzo SPC. Il sito pertanto è raggiungibile solo da Internet 
Sembra che questa sia un'anomalia nota......

**Comment by patriziasaggini** [comment]
Grazie @iessicatoro per la verifica con Lepida!

A questo punto si tratta di capire se l'accesso ai servizi di ANPR può essere modificato, in analogia a quanto succede per l'Agenzia delle Entrate, i cui servizi sono raggiungibili da qualunque tipo di rete.....

**Comment by iessicatoro** [comment]
Buongiorno Patrizia, esattamente!

**Comment by rnapoli1983** [comment]
Buonasera,

credo possa essere utile la seguente analisi.

Quando parliamo dei servizi ANPR è necessario declinare le tipologie utente a cui sono destinati al fine di comprendere il motivo per cui alcuni di essi sono doppiamente esposti sia su SPC che Internet ed altri no.

Il servizio di Visura del Cittadino, per la visualizzazione dei propri dati anagrafici, è un servizio appunto per il cittadino. Per tale motivo lo SPID dedicato (spid.anpr.interno.it) è esposto solo su Internet per utenti non appartenenti a PA. Infatti le prove da voi eseguite con dispositivi propri (smartphone, pc domestici, tablet ecc.) hanno tutte dato esito positivo.

I servizi ANPR per i comuni e le altre PA coinvolte hanno doppia esposizione (SPC e Internet) per soddisfare le esigenze delle PA stesse e sono finalizzati esclusivamente ad utenti appartenenti ad esse.

Rimango a disposizione.

Cordiali saluti

**Comment by patriziasaggini** [comment]
Grazie del riscontro!
Però non capisco la differenza con la visura catastale, che è sempre una consultazione di dati, che invece funziona da qualsiasi dispositivo;
è come se in quel caso i dipendenti dell'Agenzia delle Entrate non potessero avere accesso al servizio....
Perchè?

**Comment by rnapoli1983** [comment]
L'accesso a SPID di AE, a differenza di quello ANPR, è esposto sia su SPC che su Internet.

Quindi funziona da tutti i dispositivi sia quelli su rete SPC (come il pc dell'ufficio di una PA) sia sullo Smartphone di sua proprietà agganciato a Internet.

Spero di essere stato chiaro.

Rimango comunque a disposizione

Cordiali saluti

**Comment by patriziasaggini** [comment]
L’aspetto tecnico mi è chiaro, volevo chiedere se è possibile fare in modo che anche le visure ANPR siano accessibili dalle reti pubbliche, così come avviene per le visure catastali. 

Grazie!

**Comment by rnapoli1983** [comment]
Buongiorno,

non posso darle alcun tipo di risposta in merito nè affermativa nè negativa perchè la scelta di questo tipo di configurazioni credo che soddisfi esigenze normative e di privacy a me trasparenti.

Comunque se la visura ANPR fosse accessibile da reti pubbliche non sarebbe più un servizio esclusivo per i cittadini.

Cordiali saluti.

**Comment by FilippoPapi** [comment]
buongiorno a tutti
la visura del cittadino nasce per dare la possibilità ai cittadini di consultare i propri dati anagrafici, non nasce per consentire l'accesso alle pubbliche amministrazioni ai dati dei cittadini. Per poter accedere a ANPR le pubbliche amministrazioni dovranno stipulare con il Ministero dell'Interno degli appositi accordi di fruizione. A quel punto potranno accedere, con le modalità che saranno previste, ai dati di ANPR. Ad oggi la visura, essendo appunto un servizio per i cittadin,i è esposta solo si internet.
Cordiali Saluti
