### ISSUE TITLE
cittadino ancora residente nonostante cancellazione completata con esito positivo

### ISSUE THREAD

**Issue by leopaul76** [italia/anpr#1884]
Buongiorno,
in data 24-10-2019 con operazione id anpr 143059379 completata positivamente si provvedeva alla cancellazione per altri motivi (comune non subentrato) del soggetto avente id 47850581.
In data odierna ci comunica il comune di cancellazione (Carugate) nel frattempo subentrato che il cittadino risulta iscritto anche a Valenza oltre che da loro e ci chiedono una cancellazione per doppia iscrizione che risulta impossibile fare.
Resto in attesa di Vs. riscontro.
Grazie e cordiali saluti.
Comune di Valenza
per info 0131949210

**Comment by frmariani** [comment]
l'operazione idanpr 143059379, completata positivamente, è stata annullata lo stesso giorno con l'operazione idanpr  143172943 (operazione comune 3278630), pertanto nulla osta alla cancellazione per doppia iscrizione.

**Comment by leopaul76** [comment]
l'operazione che risulta annullata idanpr 143172943 faceva riferimento all'operazione idanpr 121642912 (sempre riferita allo stesso soggetto) che era un cambio di residenza del 13.09.2019 interno al Comune di Valenza a cui gli accertamenti della polizia locale hanno dato esito negativo;
L'operazione idanpr 143059379 non è stata annullata, d'altro canto non riesco in nessun modo a cancellare per doppia iscrizione il soggetto.
Resto in attesa di Vs. riscontro.
Grazie e cordiali saluti.
Comune di Valenza
per info 0131949210

**Comment by frmariani** [comment]
abbiamo sanato l'anomalia
