### ISSUE TITLE
ws 5008 - Modifica dati anagrafici con ricalcolo del CF: errore "Operazione non effettuabile"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1887]
Buon giorno,
il comune di Civita D'Antino ci ha segnalato la seguente problematica, deve modificare i dati anagrafici (nome e cognome) dell'individuo con id ANPR 64835992, in modo che questo comporti un ricalcolo del codice fiscale (il cf attuale è presente in AE ed è marcato ANPR).
Invocando il ws 5008, si ottiene però in risposta l'errore "Operazione non effettuabile", che in altre occasioni abbiamo riscontrato essere generato dall'interazione di ANPR coi servizi AE e che non ci dà indicazioni più precise su eventuali errori nei dati o nella procedura.
L'id operazione comune è 0660342020011734, per mezzo dell'ente vi chiediamo di interessarvi del problema con cortese sollecitudine in quanto trattasi di cittadino straniero in attesa di rilascio della carta di identità, necessaria per consentirgli la permanenza nel nostro paese.
Grazie, cordiali saluti
Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
Il cittadino è già in possesso di un CF omocodice per cui i servizi di Agenzia Entrate resi disponibili ad ANPR non possono trattarlo.
