### ISSUE TITLE
EN122 dopo 5005

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1888]
Buonasera ci è capitata una cosa molto strana per due cittadini.

comune NAPOLI in presubentro 
ricercato cittadino residente a CARTOCETO con idOperazioneANPR>16416994
trovato e trasferito nei residenti di NAPOLI con 5005 positiva idOperazioneANPR>16417131
alla successiva 3002 per il soggetto IDANPR 148450101 idOperazioneANPR>16417466
si ha EN122
anche la ricerca per cognome nome e data nascita idOperazioneANPR>16417481
sempre EN122

stessa situazione per il soggetto IDANPR 148450106
cercato con 3002 idOperazioneANPR>16417506 tramite cognome nome e data nascita
trasferito a NAPOLI con 5005 positiva idOperazioneANPR>16417530
le successive ricerche 3002 danno esito negativo.

cosa possiamo controllare?
grazie
Riccardo

**Comment by frmariani** [comment]
in ambiente di pre-subentro, il Comune di Napoli non risulta subentrato, pertanto alcune funzionalità non sono permesse; tra queste c'è la consultazione.

**Comment by fmbianchi** [comment]
perfetto, grazie mille
