### ISSUE TITLE
[2001] msg. Comune di registrazione atto non esistente

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1889]
ambiente di PRODUZIONE - comune di CARLOFORTE (111010)

il cliente sta registrando oggi una morte avvenuta in altro comune nel 2015 ed iscritta a suo tempo nei registri di stato civile dello stesso anno.
la comunicazione 2001 va in errore, segnalando che il comune di registrazione dell'atto (CARBONIA - CI) è inesistente, ma alla data del decesso ci risulta presente anche nelle tabelle di ANPR.

la comunicazione cui ci riferiamo e quella con idOperazioneComune 2020000078

potete verificare come mai va in errore?

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare ad eseguire l'operazione per favore?

**Comment by AMonopoliADS** [comment]
fatto.
adesso la comunicazione è andata a buon fine.
grazie.
