### ISSUE TITLE
[5008] cambio luogo nascita medesimo codice istat

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#189]
Corbetta, Produzione, ID operazione ANPR 577565

Abbiamo fatto una variazione di luogo di nascita per un soggetto che era erroneamente registrato con la descrizione più recente e non con quella vigente alla data della nascita.
Premesso che all'AE era già registrato con il comune corretto, la variazione 5008 in ANPR da errore indicando: EAM94: Richiesta incongruente - nessun campo variato; mentre nella request viene passato il nome del comune di nascita corretto (Piedimonte d'Alife) con il medesimo codice istat del comune attualmente in ANPR (Piedimonte Matese).
Grazie

**Comment by gcarbonin** [comment]
Dovrebbe riprovare e darmi conferma della soluzione del problema

**Comment by LucaBonini64** [comment]
Confermo la soluzione del problema
