### ISSUE TITLE
[5008] Mutazione Dati Anagrafici

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1890]
Salve,

abbiamo un caso specifico in cui ci serve sapere quale dei campi di generalità è stato modificato, per esempio nome/cognome/sesso/codiceFiscale/dataNascita/luogoNascita.
Nella documentazione di ANPR (Tabella36- Tipi di Mutazione) si precisa il valore 1 per tutti i Dati Anagrafici e Codice Fiscale.
La nostra domanda sarebbe questa: Si potrebbe specificare quale dei campi della generalità si è modificato?

Saluti

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by rvinzani** [comment]
Può darmi l'idANPR o la sua casella di posta per sentirci direttamente?

**Comment by AlbanaCelepija** [comment]
L'ambiente che stiamo utilizzando per il momento è un free test (888183), la mail è acelepija@fbk.eu.

**Comment by rvinzani** [comment]
Non è previsto dai servizi. E' possibile effettuare un'interrogazione alla data precedente la mutazione per verificare la modifica effettuata
