### ISSUE TITLE
cambio nome e cognome - errore ANPR

### ISSUE THREAD

**Issue by iessicatoro** [italia/anpr#1892]
Si chiede di cambiare il cognome e nome di una persona (id. ANPR : 27438278) avente un codice fiscale collegato al suo originario - In sostanza quando si tenta la variazione dati anagrafici individuali viene restituito errore:  id operazione ANPR 189721550.

**Comment by ncapozzi** [comment]
Come anticipato per le vie brevi, il cf calcolato per la ragazza a partire dai dati trasmessi dal Comune risulta collegato in Agenzia delle Entrate a quello del fratello.
Se tale collegamento, come sembra, è stato fatto erroneamente occorre richiedere alla Direzione Centrale Archivio Anagrafico lo scollegamento tra le due posizioni. A seguire è necessario richiedere nuovamente la variazione, effettuando la risoluzione disallineamenti con la richiesta di collegamento tra il vecchio e il nuovo codice fiscale della ragazza.
