### ISSUE TITLE
[3002] errore EN122 - La richiesta effettuata non produce alcun risultato

### ISSUE THREAD

**Issue by AlbanaCelepija** [italia/anpr#1893]
Salve,

Ambiente free test : 888183
Non riusciamo più a effettuare richieste 3002 perchè riceviamo l'errore:
"La richiesta effettuata non produce alcun risultato".
La stessa cosa anche dal WebApplication, anche se alcune ore fa funzionava correttamente.

Saluti

Albana Celepija
SmartCommunity Lab
Fondazione Bruno Kessler, Trento

**Comment by gife67** [comment]
Buonasera,
cortesemente se mi indica gli IDOperazioneANPR delle richieste effettuate, in modo da poter verificare puntualmente.
Grazie

**Comment by AlbanaCelepija** [comment]
Buongiorno,
alcuni IdOperazioneANPR:

2361859
2361849
2361848
2361847
2361846
2362404 (eseguita oggi)

**Comment by gife67** [comment]
Quelle operazioni hanno effettuato una ricerca sui seguenti idsoggetto:

32817946:  non esiste per cui la ricerca ha esito negativo
37413408: ha data inizio validità di famiglia convivenza il giorno stesso dell’interrogazione ma con hh.mi.ss valorizzati. Questa anomalia porta a non estrarre il dato il giorno stesso dell’interrogazione, se viene ripetuta oggi andrà a buon fine
37413406: ha data inizio validità di famiglia convivenza il giorno stesso dell’interrogazione ma con hh.mi.ss valorizzati. Questa anomalia porta a non estrarre il dato il giorno stesso dell’interrogazione, se viene ripetuta oggi andrà a buon fine
37413417: ha data inizio validità di generalità soggetto il giorno stesso dell’interrogazione ma con hh.mi.ss valorizzati. Questa anomalia porta a non estrarre il dato il giorno stesso dell’interrogazione, se viene ripetuta oggi andrà a buon fine 

In ultima analisi a parte il primo caso per cui il soggetto non esiste, gli altri dipendono da un’anomalia nella valorizzazione della data di inizio validità.

**Comment by AlbanaCelepija** [comment]
Mi sembra un po' strano.
**37413408**: questo cittadino è stato inserito il giorno  `**<dataOraRichiesta>2019-12-18T15:15:00.000</dataOraRichiesta>**` tramite l'operazione con **IdOperazioneANPR : 2333666**.
Per di più durante tutti questi giorni abbiamo ripetuto più o meno le stesse operazioni di interrogazione senza avere problemi.
Comunque è strano che anche dal Web non funzionavano le ricerche.
Per quanto riguarda i WS forse il problema è dovuto al fatto che usiamo la data di riferimento del giorno in cui  è successo l'operazione:

>   
         <datiRichiesta>
		<schedaAnagraficaRichiesta>1</schedaAnagraficaRichiesta>
		<dataRiferimentoRichiesta>2019-12-18+01:00</dataRiferimentoRichiesta>
		<datiAnagraficiRichiesti>1</datiAnagraficiRichiesti>
	     </datiRichiesta>

Quindi dobbiamo mettere il valore della data un giorno dopo l'evento?

Abbiamo appena fatto un'altra prova utilizzando il 3002 ma risulta la stessa cosa:
idOperazioneANPR: 2362639. Forse sbagliamo qualcosa nei parametri della richiesta?

Grazie

**Comment by mttfranci** [comment]
Salve, stiamo indagando la questione, se interrogato il soggetto 37413408 con dara riferimento richiesta ad oggi lo trovate invece?

**Comment by AlbanaCelepija** [comment]
Si, lo troviamo. (idOperazioneComune: 3f0f0v2fTST1AAS)
Da quanto riesco a capire facendo diverse chiamate, non funzionano le richieste
con data riferimento < 2020-01-20 (esempio: idOperazioneAnpr: 2370376).
invece quelle con data riferimento dopo il 20 gennaio funzionano. (esempio: idOperazioneAnpr: 2370383 con data riferimento: 2020-01-21)

**Comment by mttfranci** [comment]
Si in effetti il problema è causato da una errata gestione di una rettifica avvenuta da applicazione web (id operazione ANPR 2361727, rettifica data decorrenza residenza).
Da lunedì il problema non dovrebbe più ripresentarsi per le future operazioni.
Trattandosi di un ambiente di test le posizione incoerenti come quella segnalata non verranno sanate.
