### ISSUE TITLE
Errore inserimento data di cancellazione per comune non subentrato

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#1894]
Buongiorno,
sono a chiedere come poter modificare la data di decorrenza di una cancellazione anagrafica di un cittadino emigrato in un comune non subentrato.
E' stata indicata una data errata con l'operazione Cancellazione per altri motivi Apr.
E' possibile intervenire da WebApp?

Grazie

**Comment by azabatta** [comment]
Buongiorno, 
la data di cancellazione non può essere rettificata: è necessario annullare la comunicazione di "Cancellazione per altri motivi"  e ritrasmetterla nuovamente con la data corretta. Ambedue le operazioni possono essere eseguite sia dal gestionale comunale che dalla web app di ANPR.
Per essere seguiti sulla web app di ANPR  aprire una segnalazione al numero verde Sogei 800863116.
