### ISSUE TITLE
[5001] Variazione Legame di Parentela - Errore EN447

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1895]
ambiente di PRODUZIONE - comune di IMOLA (037032)

si invia la variazione di rapporto di parentela da Convivente a Nuora, in seguito all'aggiornamento dei dati di matrimonio.
la comunicazione ritorna con errore 
EN447 - E - La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.
(EN527 - E - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-21 09:19:30 , idOperazioneANPR 190056389)

i dati riportati sono in linea che le posizioni anagrafiche e la situazione è similare ad altre andate a buon fine

potete verificare?

grazie 
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, abbiamo verificato la posizione del soggetto in ANPR e le operazioni inviate. 
Abbiamo verificato che la comunicazione del matrimonio da voi menzionato, è stata effettuata in data 20-GEN-2020 con decorrenza 20-GEN-2020; la variazione del rapporto di parentela, invece, comunicata con l'operazione da voi indicata, riporta come data decorrenza il 2018-03-03. 
Sicuramente il controllo bloccante ricevuto non è corretto, ma volevamo chiedere conferma sulla correttezza o meno della data di decorrenza trasmessa per la variazione parentela.

**Comment by AMonopoliADS** [comment]
grazie del riscontro.

avevamo memoria che la dataDecorrenza della comunicazione - nel caso specifico del ws 5001 - condizionasse la dataDecorrenza del legame di parentela, ma così non è stato.
abbiamo impostato come decorrenza sempre 20/01/2020 e la comunicazione è andata a buon fine.

valutate ovviamente di cambiare il messaggio di errore che in questo caso era del tutto fuorviante.

grazie.

**Comment by asqueglia** [comment]
Certamente. grazie mille per la segnalazione.
