### ISSUE TITLE
5001 - aggiornamento codice famiglia comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1896]
Comune di Caponago (MB) 

Dopo aver effettuato l'invocazione del WS 5001 per immigrazione intera famiglia proveniente da comune subentrato, in ANPR non vengono valorizzati i codici matricola comune ed il codice famiglia comune.
L'assistenza ha comunicato che per aggiornare i codici matricola è necessario invocare WS 5008 mentre per il codice famiglia " è necessario richiamare il servizio mutazione famiglia convivenza(5501) tipo mutazione 3- Dati generali famiglia convivenza" il servizio 5501 non esiste abbiamo utilizzato il 5001 che però restituisce : EF001 - Identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata.

Di seguito i riferimenti dell'operazione :+1: 
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-21 09:02:59 , idOperazioneANPR 190030831

Nel file XML indichiamo sia idFamigliaConvivenzaANPR che idFamigliaConvivenzaComune e di seguito tutti i soggettiFamiglia.

Potete cortesemente indicarci il motivo dell'anomalia ? Grazie

**Comment by rvinzani** [comment]
Il tipo mutazione nella operazione indicata è 4 e non 3 come suggerito
