### ISSUE TITLE
Corretta compilazione dati di cessazione matrimonio per divorzio DL 132/2014

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1897]
Buongiorno,

Comune di Storo produzione.

Vorremmo sapere quale sia la corretta compilazione dei dati in caso di cessazione matrimonio per "divorzio breve" DL 132/2014.

Abbiamo infatti notato che in caso si compili oltre ai campi data e data validità anche il campo data formazione atto nella certificazione di stato civile il cittadino risulterà divorziato dalla data di formazione atto anziché dalla data di validità.

Rimaniamo in attesa di un gentile riscontro.

Grazie

Roberta Biasi
Consulente Applicativo - Area Demografici 
Dedagroup Public Sector & Utilities

**Comment by asqueglia** [comment]
Buongiorno,
al momento in ANPR viene consentita l'acquisizione sia di una sentenza di divorzio che di un atto di cessazione matrimonio, ma viene utilizzata la data di formazione dell'atto di cessazione come data di cessazione del matrimonio, dando di fatto priorità all'atto rispetto alla sentenza.
Abbiamo già chiesto un chiarimento riguardo il trattamento delle varie casistiche normativamente vigenti; sicuramente la sua richiesta sarà oggetto di una prossima evoluzione. 
Grazie per la segnalazione
