### ISSUE TITLE
Profilo utente sindaco

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1898]
Buongiorno,
un nostro comune, avrebbe la necessità che l'utente Sindaco possa anch'esso operare in ANPR.
Provando ad assegnargli i "poteri" da operatore, una volta confermato è sparito il flag dalla voce "Sindaco o Commissario".
Ed una volta fatto ciò non è stato più possibile riassegnargli il profilo di Sindaco se non tramite assistenza con voi.

Quello che vogliamo chiedere è: c'è un modo per cui un utente abbia i flag sia sul profilo sindaco che sui profili da operatore?

Ringrazio anticipatamente.

**Comment by Leonforte** [comment]
Si certamente, che comune è ?

**Comment by SAlberto** [comment]
Istat del comune: 001090

Grazie

**Comment by Leonforte** [comment]
I profili sono stati assegnati senza problemi, buon lavoro, saluti
