### ISSUE TITLE
STATO CIVILE NON DOCUMENTATO nei Certificati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1899]
Buongiorno,
ci è stato fatto notare, da un comune che seguiamo, che nei vari certificati che espongono lo stato civile dell'individuo, se questi ha lo STATO CIVILE NON DOCUMENTATO a S, nei certificati quest'informazione viene omessa.

Potete verificare?
Grazie

**Comment by rvinzani** [comment]
I servizi di ANPR prevedono che sia possibile indicare lo stato civile del cittadino (coniugato, divorziato, unito) in assenza degli estremi dell'atto di stato civile (non documentato). In tal caso il certificato non viene emesso
