### ISSUE TITLE
Elaborazione interrotta FILE DI SUBENTRO APR - Comune Bologna

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#19]
Salve,
abbiamo fatto una prova di upload del file di subentro, nell' ambiente di TEST, tramite la WEB-APP, invio del file di SUBENTRO.
Il file AIRE e' anadato in elaborazione , il file APR e' andato INSERITO OK, dopo un po' di tempo l'elaborazione e' stata interrotta con esito KO, ma senza nessuna descrizione e resoconto.
Al comune e' arrivata la PEC che l'elaborazione e' stata interrotta a causa dell'errore ES092 - sono presenti alcuni soggetti   senza scheda famiglia/convivenza associata.
Nella WEB-APP non troviamo nessun resoconto e nessun file.
E' possibile sapere quali sono i soggetti che hanno questo errore?
Tale errore quindi non permette il caricamento anche degli altri soggetti senza errore?

DATA 08/03/2017

Ambiente : TEST

Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by gcarbonin** [comment]
L'errore è bloccante in quanto se si inviano i dati dei soggetti senza i dati della famiglia/convivenza di appartenenza manca un dato essenziale dell'anagrafe costituito dalla RESIDENZA. Questo errore è stato modificato di recente (in precedenza era un'anomalia)  in quanto si è verificato con un comune, determinando  una serie di squadrature con l'Agenzia delle Entrate.
Dal momento che la normativa non prevede un subentro parziale, o tutti i dati sono corretti o tutti vengono scartati.
Lei giustamente  ci fa notare che sarebbe utile l'elenco di queste posizioni. Provvediamo ad aggiornare l'elenco degli errori; avvertiamo noi quando può riprovare.
Gina Carbonin

**Comment by gcarbonin** [comment]
Abbiamo effettuato la modifica. Può inviare nuovamente i file; gli elenchi degli errori e delle anomalie  saranno disponibili nella web application (area subentro - esiti).

**Comment by ANPRCDBO** [comment]
Si' grazie, ora compaiono gli errori anche nel file scartato
