### ISSUE TITLE
ws [5012] - Annullamento mutazione indirizzo

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#190]
In ambiente di Test, volevo annullare una Mutazione indirizzo (servizio 5001) registrata il 25/05/2017. Ho chiamato il servizio 5012 ma, pur essendo il file xml inviato formalmente corretto, il servizio risponde "Internal Error". Come posso verificare l'errore.
Papini Riccardo Infor

**Comment by gcarbonin** [comment]
Nei log non troviamo traccia di questa operazione e quindi poco possiamo verificare. In questa situazione è la richiesta soap che non è formattata correttamente. Provi a prendere il body della richiesta, predisporlo per l'invio tramite il client che trova in ambiente di test comuni - strumenti di supporto e a confrontare la sua richiesta con quella creata dal client

**Comment by gcarbonin** [comment]
Il problema si è risolto?

**Comment by rpapini** [comment]
Nei giorni scorsi ero in contatto con Roberta Vinzani  e con Zabatta 
Anna, il problema non era nei dati chiamati ma nel servizio. Ora è risolto.

Saluti

Papini Riccardo


Il 09/06/2017 11:28, gcarbonin ha scritto:

**Comment by gcarbonin** [comment]
grazie
