### ISSUE TITLE
WS 5008 - Matrimonio - Chiarimento Tecnico

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1900]
Buongiorno
il WS 5008 invocato per passare ad ANPR i dati di matrimonio di un cittadino residente (e già resente in ANPR) ed i dati del coniuge residente (e già presente in ANPR) , riporta gli stessi dati di matrimonio anche sul coniuge e quindi resta solo da modificare lo stato civile del coniuge ? 
Oppure il WS deve essere invocato sia per il cittadino che per il coniuge ?

Ci confermate che quando invochiamo il WS 2001 per decesso di un cittadino residente automaticamente il WS si occupoa di riportare i dati dell'evento di decesso come vedovanza sul coniuge ?

**Comment by azabatta** [comment]
Buonasera, 
sì,  confermiamo che  la  comunicazione dei dati relativi al “matrimonio” (ws 5008) aggiorna in automatico anche la sezione “matrimonio” sulla scheda individuale del coniuge collegato (ossia presente in ANPR) e che per quest’ultimo è necessario solo aggiornare lo stato civile. 
Lo stesso meccanismo di aggiornamento automatico è previsto anche per la  comunicazione dei dati relativi ad  “unione civile” e “convivenza di fatto” (ws 5008).
Anche quanto indicato per il decesso (ws 2001) è corretto: in automatico si aggiorna la sezione “vedovanza” del coniuge collegato (o la sezione “scioglimento unione” dell’unito civilmente oppure “risoluzione convivenza” del convivente di fatto).
