### ISSUE TITLE
Stato civile non documentato

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1901]
In riferimento alla issue #1899 

come scritto nella issue citata in ambiente di produzione per il certificato DI STATO DI FAMIGLIA E DI STATO CIVILE esce lo stato civile dell'individuo anche se è NON DOCUMENTATO.

Abbiamo riprodotto la casistica anche in ambiente di test, potete verificarlo il numero di protocollo del certificato emesso è 23671537.
Nello specifico il soggetto con stato civile non documentato è il secondo (figlio).

Potere verificare? Grazie

**Comment by rvinzani** [comment]
Il certificato che non viene emesso è quello di stato civile che richiede la presenza degli estremi dell'atto relativo allo stato stesso. Il fatto che il soggetto invece sia coniugato/divorziato è uno dato che l'ufficiale di anagrafe indica sotto la sua responsabilità nonostante non inserisca documentazione (es. matrimonio contratto all'estero e non trascritto). Questo viene riportato sui certificati.

**Comment by SAlberto** [comment]
Nel certificato con numero di protocollo 23671537 il soggetto in analisi non è il primo, ma il secondo, che non è ne coniugato ne divorziato, ma è CELIBE.
Questo individuo e sì CELIBE, ma il suo stato civile NON è documentato, questa informazione di mancanza di documenti deve uscire sul certificato.

**Comment by rvinzani** [comment]
Le informazioni da riportare sui certificati sono state concordate con il Ministero dell'interno e con i referenti ANUSCA

**Comment by SAlberto** [comment]
Riferiremo al comune

Grazie
