### ISSUE TITLE
il file tipoDato.xsd presente in tutte le cartelle wsld/xsd di tutti i WS è comune per tutti i servizi oppure ogni servizio ha il suo tipoDato.xsd ?

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1902]
il file tipoDato.xsd presente in tutte le cartelle wsld/xsd di tutti i WS è comune per tutti i servizi oppure ogni servizio ha il suo tipoDato.xsd ?

_Originally posted by @GabriellaBallabio in https://github.com/italia/anpr/issues/1871#issuecomment-576747073_

**Comment by gife67** [comment]
Buongiorno,
il tipoDato.xsd è a fattor comune per tutti i servizi.
