### ISSUE TITLE
TipoLegameSoggetto - datadecorrenza [La data a partire dalla quale il soggetto appartiene alla famiglia/convivenza]

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1904]
COMUNE DI CAPONAGO

Buongiorno
il Comune di Caponago per alcuni cittadini NON possiede le informazioni utili alla valorizzazione dell'informazione dataDecorrenza nel tag TipoLegameSoggetto.
Avendo cambiato diversi gestionali che non gestivano l'informazione NON sono in grado di risalire alla data di decorrenza corretta. Come è possibile procedere visto che per i WSè un dato obbligatorio ?

**Comment by rvinzani** [comment]
Potreste utilizzare la data di appartenenza alla famiglia se è un dato di cui disponete

**Comment by GabriellaBallabio** [comment]
La datadecorrenza da indicare nel tag TipoLegameSoggetto è proprio la data a partire dalla quale il soggetto appartiene alla famiglia/convivenza ... e il comune non la possiede ... per quale motivo è obbligatoria ... il quali situazioni viene utilizzata ? Nei certificati non compare ...

**Comment by rvinzani** [comment]
In realtà è possibile appartenere ad una famiglia e modificare il legame di parentela successivamente, ad esempio in seguito a matrimonio o in seguito a cambio di intestatario scheda famiglia. Se non si possiede neppure la data di decorrenza appartenenza si suggerisce di indicare la data di decorrenza della residenza. Tale informazione viene stampata sul certificato di stato di famiglia con rapporti di parentela

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
