### ISSUE TITLE
Codici errore duplicati ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1906]
Ambiente di TEST.

Abbiamo notato che il codice d'errore EN148 viene utilizzato in situazioni anche molto differenti.
Ad esempio

1. "OPERAZIONE GIA' ANNULLATA DALL'OPERAZIONE XXXXX" in caso di tentativo di annullamento di una richiesta già annullata (vedi ad es. operazione id anpr 23669645).
2. "La differenza tra la data iniziale e finale non puo' essere superiore a 31 giorni" in caso di estrazione 4005 con un filtro date troppo ampio (vedi ad es. operazione id anpr 23689584).

Il codice di errore di cui al punto 1 una volta era CN148 (vedi ad es. la richiesta ID ANPR 19741520).

Come mai ?

**Comment by asqueglia** [comment]
Buongiorno,
in realtà il CN148 a cui si fa riferimento, relativamente alla richiesta con id19741520, è lo stesso errore EN148.  ANPR, internamente al sistema, utilizza i codici di errore CNXXX, mentre in risposta restituisce gli esiti ENXXX; a causa di un bug, successivamente risolto, prima veniva restituito il codice di errore anziché l'esito. 
In generale l'errore EN148 viene utilizzato per bloccare operazioni non consentite, in situazioni generiche, restituendo un messaggio di errore specifico per l'operazione erroneamente richiesta.

**Comment by busaster** [comment]
Grazie, tutto chiaro adesso
