### ISSUE TITLE
[4005] Operazione sconosciuta in risultati scarico

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1907]
Ambiente di produzione, comune di Caravaggio

Chiediamo con il servizio 4005 lo scarico di tutte le operazioni eseguite nel periodo 10/01/2020 - 24/01/2020. L'operazione viene svolta e viene ritornato lo scarico (id ANPR scarico 194205234).
All'interno del XML però è presente una operazione che non trovo in documentazione, priva di XML di richiesta e risposta, classificata con tipoOperazione 8046 :
```
<elencoRisposte>
  <idOperazioneANPR>184439012</idOperazioneANPR>
  <statoLavorazione>2</statoLavorazione>
  <tipoOperazione>8046</tipoOperazione>
</elencoRisposte>
```
Che cos'è questa operazione ? Coma mai viene ritornata nello scarico ?

**Comment by mttfranci** [comment]
Salve, potete ignorare la richiesta 8046.
Si tratta di tipo operazione attribuito internamente da ANPR ad una operazione di sistema che provvederemo a escludere tra i risultati restituiti.
Saluti

Assistenza ANPR
