### ISSUE TITLE
Interrogazione dati ANPR

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#1908]
Buongiorno,

riprendo una mia domanda (issues #1472) in merito alla possibilità di interrogare i dati in ANPR con un altro software rispetto al software che ha in gestione l'anagrafe del comune.
Lo scenario sarebbe il seguente: il comune ha il software A come gestore dell'anagrafe comunale e nelle impostazioni della webapp è presente l'indirizzo IP di collegamento (ovvero quello dichiarato nel censimento delle postazioni).
Lo stesso comune utilizza il software B per altri moduli comunali quali, ad esempio, tributi, servizi sociali, servizi a domanda....che avrebbero la necessità di fare delle interrogazioni (solo ed esclusivamente quelle) direttamente in ANPR.
La nostra richiesta è di capire se per questo cliente (ma non è solo uno che ci ha fatto questa richiesta), gestito dal software A per l'anagrafe, fosse possibile, dopo il censimento da parte del responsabile della sicurezza di utenti in sola visione ovviamente, che un secondo software possa accedere autonomamente (con i nostri programmi sviluppati per i nostri clienti che gestiscono l'anagrafe con il nostro software) alla webapp tramite WS ed effettuare le interrogazioni direttamente sulla banca dati nazionale.

In questo caso ci sarebbero 2 software diversi che lavorerebbero sull'anagrafe per un solo comune, ma vorrei sapere se è una soluzione fattibile o meno.

Vi ringrazio per il supporto.
Marco Sala
Pa Digitale Spa

**Comment by MarcoSalaPad** [comment]
Buongiorno,

ci sono novità in merito a questa richiesta?
Grazie

Marco Sala
Pa Digitale Spa

**Comment by FilippoPapi** [comment]
buongiorno,
la possibilità di accedere a ANPR non è legata al software mediante cui si accede bensì alla legittimità dell'accesso dell'utente. Il DPCM194 prevede che a ANPR possono accedere esclusivamente gli Ufficiali di Anagrafe.
saluti
