### ISSUE TITLE
Modifica codice fiscale omocodice

### ISSUE THREAD

**Issue by Copiano** [italia/anpr#1909]
Buongiorno, mi trovo un cittadino che in ANPR ha un codice fiscale numerico catalogato come codice fiscale provvisorio per omocodia.
Interrogando dalla webapp la funzionalità  di "Consultazione AE" vedo che il soggetto in questione, in realtà, nell'archivio appunto dall'Agenzia Entrate, ha un normale (e corretto) codice fiscale alfanumerico.

Provando ad accedere alla funzionalità della webapp di "Risoluzione disallineamenti con Agenzia Entrate", non riesco a sovrascrivere i dati di ANPR con quelli di AE, proprio perché, provando a farlo, mi esce il messaggio "Codice fiscale provvisorio per omocodia"

Come posso sistemare l'attuale codice fiscale di ANPR rendendolo uguale a quello dell'agenzia delle entrate?

Grazie
Ufficio Anagrafe comune di Copiano (PV)

**Comment by ncapozzi** [comment]
Buongiorno,
il CF alfanumerico e quello numerico sono collegati in Agenzia delle Entrate?

**Comment by Copiano** [comment]
Da quello che vedo sulla webapp pare di no: non trovo da nessuna parte l'informazione che questi due codici siano legati alla stessa persona

**Comment by Copiano** [comment]
Nella pagina di risoluzione disallineamenti con agenzia delle entrate, se includo i CF validati, dico che i due CF sono coincidenti e nell'unico campo testuale indico il CF numerico, il programma mi fa entrare nella pagina di allineamento, dove però vedo che anche in agenzia entrate il codice fiscale è identico a quello di anpr.
Se invece dalla webapp cerco in consultazione ed estrazione --> consultazione AE ed indico il codice alfanumerico che mi aspetto di dover assegnare al mio soggetto, in effetti trovo che esso è prestente.

Questo probabilmente significa che in agenzia entrate ci sono due anagrafiche per il medesimo soggetto: il mio (con codic numerico) e quello con codice alfanumerico: è possibile unificarle tenendo attiva quella con codice alfanumerico? Se sì, poi potrei fare l'operazione di risoluzione disallineamenti portando anche in anpr il codice alfanumerico

**Comment by ncapozzi** [comment]
Non avendo i codici non posso verificare, comunque immagino che il CF alfanumerico sia quello da cui è partita l'omocodia in corso di risoluzione da parte di Agenzia delle Entrate.

Non potete modificare un cf numerico provvisorio con le funzioni di ANPR, per eventuali modifiche è necessario scrivere a entrate.archivioanagrafico@agenziaentrate.it

Le suggerisco per problematiche analoghe, che possono richiedere verifiche sulla base dati di ANPR e su Agenzia delle Entrate,  di non utilizzare GitHub ma di contattare il n. verde 800863116

N. Capozzi
