### ISSUE TITLE
Comuni, codice istat xxx5xx o xxx6xx

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#191]
Buongiorno
Nell'ultima versione della tabella comuni anpr, sono stati eliminati molti "codici di ridenominazione", come ad esempio LONATO che riportava prima 017566, e ora riporta 017092 (codice attuale).
Rimangono però un centinaio di codici simili, a titolo di esempio VELATE (CO) codice istat 013640.
Questo messaggio solo per conferma che anche queste codifiche verranno cambiate nelle prossime settimane.
Grazie in anticipo
Marco Migliori

**Comment by gcarbonin** [comment]
I codici non sono stati eliminati ma spostati in una colonna aggiuntiva, sostituedoli con il codice istat effettivo. I codici in questione sono quelli che hanno codice provincia seguito da un progressivo che varia da 500 a 620. il codice che ha indicato lei (013640) non rientra in questa casistica ed è un codice istat effettivo
