### ISSUE TITLE
Immigrazioni intrecciate tra comuni

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#1910]
Buongiorno,
sono Nozzoli del CED del Comune di Prato. Chiedo se è possibile attivare il blocco di "gestione procedimenti". Mi spiego. In data 27/12 il soggetto XXXX ha chiesto la residenza al comune di Prato. Abbiamo fatto l'iscrizione preliminare e disposto l'accertamento. Il 30/12 lo stesso soggetto XXXX si reca al comune limitrofo Montemurlo e chiede la residenza. Montemurlo lo prende da noi in ANPR e lo iscrive. Arriva l'accertamento negativo del Comune di Prato. Il cittadino non è più in carico a noi e siamo impossibilitati a fare qualsiasi operazione. Visto che deve risultare che a Prato mai ha abitato l'unica soluzione che ci viene prospettata è chiamare Montemurlo e fargli annullare la loro immigrazione poi rigettare noi la pratica e far rifare a Montemurlo l'immigrazione. Ci sembra una gestione alquanto complicata che implica anche manovre non del tutto coerenti con le norme. Se la "gestione procedimenti" che viene mandata all'inizio della procedura di immigrazione avesse la funzione di lockare il soggetto tutto questo non sarebbe successo inquanto montemurlo avrebbe ricevuto il messaggio che il soggetto XXXX era in iscrizione preliminare a Prato.

**Comment by rvinzani** [comment]
A breve verrà portata in produzione la gestione del controllo che impedisce il cambio di residenza in caso di presenza di procedimento ancora aperto.

**Comment by anozzoli** [comment]
Grazie della risposta. Solo per "breve" cosa si intende? Una settimana, un mese, sei mesi? Grazie

**Comment by rvinzani** [comment]
Da domani il controllo sarà presente in ambiente di produzione
