### ISSUE TITLE
MANCATO INVIO ANPR BAMBINA NATA A GENNAIO PERCHE' CF PADRE ERRATO

### ISSUE THREAD

**Issue by AnagrafeCornaredo** [italia/anpr#1911]
Come risolvere questo problema: dopo aver trascritto l'atto di nascita della neonata, non si riesce a caricare in ANPR in quanto il messaggio è "EN070 Incongruenza dati anagrafici: il codice fiscale del soggetto non coincide con quello specificato nella richiesta[Padre] - EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2020-01-29 09:38:27 , idOperazioneANPR 195385730".
Grazie
Comune di Cornaredo
Tel 02/93263224

**Comment by ncapozzi** [comment]
Buongiorno,
nella iscrizione per nascita 1001 è stato indicato per il padre un CF non valido. Come si può verificare facendo accesso alla Consultazione su Agenzia delle Entrate disponibile nella web app oppure da PuntoFisco, tale CF è base per la risoluzione di una omocodia ma il padre è registrato in ANPR con un CF diverso che è quello con cui AE ha risolto l'omocodia.

Per problematiche specifiche di questo tipo, che richiedono accesso alla base dati e in molti casi un contatto telefonico, si suggerisce di contattare il numero verde 800863116.

N. Capozzi
