### ISSUE TITLE
Convenzione INPS ANPR

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1912]
Buongiorno,
il comune di Ascoli Piceno riceve dalla direzione provinciale INPS di Ascoli Piceno richiesta tramite PEC di invio delle variazioni di:

- decesso;
- variazioni anagrafiche;
- celebrazione di matrimonio;

A norma dell'art. 23 del R.D. 24 aprile 1927, dell'art. 115 del R.D.L. 25 novembre 1865 e art. 11 della Legge 5 maggio 1952.

Potete confermarmi che INPS è ente promotore del progetto ANPR e che tra INPS ed ANPR sia aperta convenzione per cui non deve essere più onere dell'amministrazione comunale l'invio delle variazioni anagrafiche all'ufficio INPS provinciale?

Grazie 

Buona giornata.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by azabatta** [comment]
Buonasera,
si conferma che è attivo il flusso di comunicazione di eventi anagrafici da ANPR verso INPS.
Si suggerisce di verificare con l’Istituto stesso se sussistono o meno eventuali ulteriori adempimenti da parte dei comuni.  
Saluti
