### ISSUE TITLE
[5008] Chiarimento su errore a seguito di modifica Comune di nascita

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1913]
Oggi, cercando di inviare una mutazione 5008 per cambiare il Comune di Nascita del cittadino idAnpr 66282607 del Comune di Cantalupo in Sabina, la comunicazione con idAnprOperazione 195790980 ritorna l'errore: "EN335 - Comune/provincia nascita CANTALUPO IN SABINA (RI) inesistente".
In effetti, al 16/02/1928 il Comune non esisteva (in quanto era all'epoca assorbito in quello di Aspra Sabina); ma ci saremmo aspettati un errore del tipo EC007.

Al contrario, in altre occasioni (es.: stessa tipologia di mutazione per il Comune di Liveri, passato dalla provincia di CE a quella di NA nel 1927 per il cittadino idAnpr 76559035), con le medesime circostanze (invio al 1920 come Comune di nascita Liveri NA invece che CE), non c'è stato né errore EN335 né EC007. Per questa operazione disponiamo del solo idOperazioneComune: 20191230172945017.

Federico

**Comment by rvinzani** [comment]
Può mandarmi un suo contatto?

**Comment by fmbianchi** [comment]
halleynt@halley.it, c.a. Federico Brancaleoni

**Comment by rvinzani** [comment]
L'errore EN335 viene restituito in seguito al controllo di coerenza del comune rispetto alla data di nascita quando il CF non è validato e si richiede nell'operazione di non validare i dati con AE
Il cittadino co idANPR 76559035 ha invece un CF validato e l'operazione dOperazioneComune: 20191230172945017 è una mutazione dell'atto di nascita e non dei dati anagrafici.
Comunque in generale, in presenza di un CF già assegnato e validato, i controlli di ANPR sul comune di nascita rispettano la coerenza con quanto riportato nel codice catastale del CF.
In caso di CF non validato e di richiesta di non validazione di AE, i controlli sono più stringenti
