### ISSUE TITLE
Servizi ANPR KO (timeout)

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1914]
Buongiorno,
segnaliamo che dalle 15.22, ambiente di **produzione,** i servizi ANPR hanno esito negativo. Non possiamo darvi id operazioni ANPR causa timeout. Potreste verificare?

Grazie, Chiara Leanza
per il Comune di Torino

**Comment by fmbianchi** [comment]
Confermiamo: stessa cosa ad Albano Laziale, Colli al Metauro, Cartoceto, Comuni da noi serviti.
Halley Informatica

**Comment by gife67** [comment]
Buongiorno,
ci scusiamo per il disagio, ma ci sono stati problemi sull'infrastruttura dalle 15:22 alle 15:42 circa.
Ora è perfettamente funzionante.

**Comment by CSI-Piemonte-Demografia** [comment]
Vi ringraziamo per il cortese riscontro. 
Buona serata
