### ISSUE TITLE
Chiarimento su Puegnago sul/del Garda

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#1915]
Buongiorno, 
nel file aggiornato dell'archivio dei comuni è stata modificata la descrizione del comune di PUEGNAGO SUL GARDA in PUEGNAGO DEL GARDA.

E' possibile saper il riferimento normativo usato?
Quando a suo tempo mi ero occupato della problematica, non avevo trovato nessun riferimento normativo a supporto della denominazione con "DEL" anzi, avevo trovato questa interessate lettera a BresicaOggi (https://www.bresciaoggi.it/home/spazio-lettori/lettere/puegnago-%C3%A8-sul-garda-non-del-1.3947143)

Grazie,
Tiziano

**Comment by MassimoSchiappa** [comment]
Salve,
ci scusiamo per il grande ritardo con cui rispondiamo alla vostra segnalazione e domanda di chiarimento. 
Il sindaco di Puegnago del Garda ha inviato ad Istat la documentazione che attesta che la denominazione "Puegnago sul Garda" era stata riportata in gazzetta ufficiale per un errore materiale e che successivamente, nel 1969, il comune aveva fatto domanda di variazione del nome, il consiglio provinciale di Brescia l’aveva approvato nell’anno seguente e un decreto del presidente della Repubblica dell’anno ancora seguente aveva approvato la variazione.
Cordiali saluti.

**Comment by Tiz68** [comment]
Buongiorno,
effettivamente quando mi ero occupato del problema non avevo trovato questo riferimento [DECRETO DEL PRESIDENTE DELLA REPUBBLICA 28 aprile 1971, n. 455 ](https://www.gazzettaufficiale.it/atto/serie_generale/caricaDettaglioAtto/originario;jsessionid=NDbhP8Eo2YuRCi4rfuEXxA__.ntc-as3-guri2a?atto.dataPubblicazioneGazzetta=1971-07-22&atto.codiceRedazionale=071U0455&elenco30giorni=false) , che oggi invece ho trovato molto rapidamente e che non lascia spazio ad interpretazioni.

Grazie,
Tiziano
