### ISSUE TITLE
[N010] Verifica Stato Notifiche

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1916]
ambiente di PRODUZIONE - comune di CORSICO (015093)

è stata richiesta la notifica mutazioni (N010) x due giorni del 2019.
(idOperazioneANPR 196203914)

la prima disponibilità che è stata segnalata era delle ore 10:00.
dalle ore 10:00, ad ogni richiesta di verifica, la disponibilità è sempre un'ora dopo.

è già successo.

chiarito che la disponibilità delle notifiche può arrivare anche alle 24 ore dalla richiesta, potreste accertarvi che non ci siano altri motivi di blocco?

grazie.

Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
la situazione si è sbloccata.
non so se siate intervenuti voi, ma alle 11.15 abbiamo ottenuto la response, nonostante l'ultima disponibilità indicata fosse successiva.

grazie

**Comment by fcastellani81** [comment]
Buongiorno,
si segnala il medesimo caso. 
è stata richiesta la notifica mutazioni (N010) dal 30/01/2020 ad oggi.
(idOperazioneANPR 200622004)
la prima disponibilità l'abbiamo avuta alle ore 12.00 e via via ci slitta sempre di un'ora in avanti ad ogni richiesta.
Cortesemente, potreste verificare?
grazie
