### ISSUE TITLE
Impossibile effettuare una cancellazione

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1917]
Ambiente di Produzione
Comune di Orbassano

Buongiorno,
tentando di cancellare un soggetto IDANPR 71607541, abbiamo il seguente errore:
"EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto"
 (idOperazioneANPR 197595404).
Facendo una verifica notiamo che l'unico procedimento è quello riferito alla cancellazione appena aperta.
Tornerebbe molto utile ci fosse l'identificativo ANPR del/dei procedimento/i nel messaggio di errore

Grazie

**Comment by rvinzani** [comment]
Abbiamo eliminato il controllo in caso di cancellazione.
Tale controllo invece rimarrà se fosse richiesto un cambio di residenza e ci fosse un procedimento aperto dal comune di provenienza.
Riprovate e fateci sapere

**Comment by busaster** [comment]
La cancellazione ora è ok.
Purtroppo non funziona più in iscrizione, poiché noi prima apriamo il procedimento, poi eseguiamo l'iscrizione e pare che questa si blocchi in conseguenza del nostro procedimento ma non deve.
es. ID operazione ANPR 199044482, comune di Venaria Reale

**Comment by rvinzani** [comment]
Il controllo scatta non per il procedimento correttamente aperto dal comune di Venaria Reale, ma per un precedente procedimento aperto dal comune di Torino e non ancora chiuso

**Comment by busaster** [comment]
A maggior ragione diventa fondamentale per eseguire una diagnosi senza dover contattare voi che nel messaggio ci sia un riferimento al procedimento che blocca, almeno il numero ANPR del procedimento, ancor meglio se anche il comune che lo ha aperto

**Comment by ncapozzi** [comment]
Buonasera,
il messaggio di errore del controllo EN531 è stato modificato indicando il comune che ha aperto il procedimento è il relativo idANPR
