### ISSUE TITLE
Blocco in produzione : Certificato revocato ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1918]
Ambiente di produzione, comune di Salerno

da questa mattina tutte le chiamate a servizio ANPR restituiscono il seguente errore 

`javax.xml.ws.soap.SOAPFaultException: certificate revoked (from client)`

Il comune è bloccato. Quale può essere la causa ?

**Comment by Leonforte** [comment]
Buongiorno, 
il giorno 31-01-2020 alle ore 12:24:10 dalla console di sicurezza è stato cancellato il certificato server 065116-CO-99999 
C'è un valido motivo o è stato fatto per errore ?

**Comment by Leonforte** [comment]
Il certificato è stato ripristinato, potete riprovare ?

**Comment by busaster** [comment]
Devo dire che come prima cosa abbiamo guardato in webapp lo stato dei certificati ed  9999 risultava attivo.
Abbiamo risolto usando un certificato di postazione libero invece del 9999.

**Comment by busaster** [comment]
Si può risalire all'operatore che ha cancellato il certificato il giorno 31-01-2020 alle ore 12:24:10 ?

**Comment by Leonforte** [comment]
Si, l'informazione è presente ma ovviamente è di comptenza del comune.

**Comment by busaster** [comment]
ok grazie, nel caso il cliente dovesse richiederlo vi farò contattare
