### ISSUE TITLE
Annullamento pratica iscrizione con successivo cambio generalità

### ISSUE THREAD

**Issue by MarcellaM** [italia/anpr#1919]
Buongiorno,

sono Marcella Molinari Ufficiale d'anagrafe del Comune di Alessandria.
Il sig. con ID ANPR 40530147 all'iscrizione si chiamava in un altro modo.
Successivamente alla registrazione della pratica di Mutazione residenza (Id ANPR: 155550971) ho, con identica decorrenza, registrato la variazione del nome (id ANPR: 156776170)
Dovendo annullare il procedimento di Mutazione residenza suddetto (a seguito di accertamento negativo) restituisce l'errore ' Esiste un operazione successiva per i soggetti movimentati: Id operazione ANPR 156776170'.
Ho provato ad annullare l'ultima operazione ( Id operazione ANPR 156776170) ma essendo una variazione di dati anagrafici il sistema mi blocca.

Potete intervenire voi?
Come posso annullare la pratica di Mutazione Residenza?

**Comment by frmariani** [comment]
l'operazione di annullamento della mutazione di residenza, deve essere annullata per "Ripristino posizione anagrafica": in questo caso non è necessario annullare le operazioni anagrafiche successive; per favore mi può indicare l'idanpr dell'operazione di annullamento fallita ?

**Comment by MarcellaM** [comment]
Per annullare un mutazione, come indicato dalla software house, seguo le varie fasi del procedimento (risposta vigili - osservazioni del cittadino - ecc.); nel caso in cui l'accertamento vigili sia negativo indico ko, poi se il cittadino non presenta osservazioni inserisco ancora esito ko e a quel punto il programma mi propone il pulsante di annullamento. 

Utilizzando questa procedura non ho possibilità di scelta di motivazione annullamento. 
Le allego screen del dettaglio delle operazioni relative alla pratica di mutazione. 

Ringrazio e saluto cordialmente 

Comune di Alessandria 
Istr. Amm.vo 
Marcella Molinari 
0131 515194 


Da: "frmariani" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "MarcellaM" <marcella.molinari@comune.alessandria.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 4 febbraio 2020 17:04:33 
Oggetto: Re: [italia/anpr] Annullamento pratica iscrizione con successivo cambio generalità (#1919) 



l'operazione di annullamento della mutazione di residenza, deve essere annullata per "Ripristino posizione anagrafica": in questo caso non è necessario annullare le operazioni anagrafiche successive; per favore mi può indicare l'idanpr dell'operazione di annullamento fallita ?

**Comment by frmariani** [comment]
non sono riuscita a raggiungerla telefonicamente;
non ravviso problemi nell'operazione di mutazioni della residenza ma sulle operazioni di annullamento che non risultano sul soggetto, almeno nel mese di Febbraio.
Dovrebbe contattare la sua software house e farsi spiegare cosa avviene con il pulsante di annullamento.

**Comment by MarcellaM** [comment]
La ringrazio, ho scritto alla software house, rimango in attesa di delucidazioni. 
La software house ha sempre sostenuto che non sia possibile annullare una pratica se sono state fatte variazioni succesive e mi aveva suggerito, essendo la variazione di generalità non annullabile, di contattare voi. 

Mi riservo quindi di ricontattarla nel caso in cui non riesca a risolvere la situazione o siano necessari ulteriori chiarimenti. 

Marcella Molinari 


Da: "frmariani" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "MarcellaM" <marcella.molinari@comune.alessandria.it>, "Author" <author@noreply.github.com> 
Inviato: Mercoledì, 5 febbraio 2020 14:53:25 
Oggetto: Re: [italia/anpr] Annullamento pratica iscrizione con successivo cambio generalità (#1919) 



non sono riuscita a raggiungerla telefonicamente; 
non ravviso problemi nell'operazione di mutazioni della residenza ma sulle operazioni di annullamento che non risultano sul soggetto, almeno nel mese di Febbraio. 
Dovrebbe contattare la sua software house e farsi spiegare cosa avviene con il pulsante di annullamento.

**Comment by frmariani** [comment]
confermo che la variazione di generalità non è annullabile; in questo caso però, è necessario annullare un'operazione che non impatta sui dati anagrafici, quindi, con la corretta causale, l'operazione di mutazione di residenza può essere annullata anche se precedente alla variazione dei dati anagrafici.
La issue viene chiusa. Nel caso avesse necessità di essere seguita per effettuare l'operazione da web app o per ulteriori chiarimenti sull'argomento, apra una nuova issue facendo riferimento a questa stessa.
