### ISSUE TITLE
ws - msg. "rejected by policy. (from client)"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#192]
[3002_rivoli.txt](https://github.com/italia/anpr/files/1038573/3002_rivoli.txt)

salve
provando ad invocare il servizio 3002 (comune di Rivoli - ambiente di pre-subentrol), riceviamo questa risposta:
`<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>`

in allegato l'xml utilizzato per eseguire la richiesta.

grazie.

Alessandro Monopoli
ADS

**Comment by gcarbonin** [comment]
Sembra un problema di mancata verifica della firma al momento dell'acquisizione da parte dei nostri apparati di sicurezza, come se il messaggio fosse stato alterato dopo l'apposizione della firma, anche soltanto per formattarlo. Consiglio di predisporre il messaggio utilizzando il client che trovata in ambiente di test-comuni - strumenti di supporto e a confrontare quanto ottenuto on la richiesta allegata.

**Comment by gcarbonin** [comment]
Il problema si è risolto?

**Comment by AMonopoliADS** [comment]
salve. no, al momento il problema non è ancora risolto.
a parità di condizioni (certificati di postazione compresi) gli invii da un'altra macchina vanno a buon fine.
stiamo valutando se dal cliente possano incidere attività dell'antivirus o del firewall, che però in questo specifico caso è gestito da un ente esterno con il quale stiamo cercando di prendere contatti

**Comment by gcarbonin** [comment]
Ok quindi è un problema lato comune
