### ISSUE TITLE
WS 5005 - Cambio Via Singolo con destinazione famiglia esistente

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1920]
Comune di Caponago 

Abbiamo invocato WS5005 con tipo mutazione 2 (Tabella 47 - mutazione di residenza) , per cambio via di un singolo cittadino da una famiglia esistente ad un altra esistente sempre nello stesso comune.

Restituisce sempre messaggio di errore. alleghiamo i due test.

primo test, idOperazioneANPR 200089735
secondo test, idOperazioneANPR 200093520
(Editato per rimuovere i riferimenti a data sensibili)

Non si capisce qual'è il problema, potete aiutarci. Il comune ha effettuato un evento di scissione/riunione

**Comment by mttfranci** [comment]
Salve,

Ci siamo permessi di editare la issue per eliminare i dati dei soggetti (per il futuro sono sufficienti gli idOperazioneANPR  al fine per noi di ottenere tutte le informazioni).

In entrambi i test avete indicato, nel dati controllo, tipo scheda 2, ovvero nuova famiglia.

`<datiControllo>`
        `<tipoMutazione>02</tipoMutazione>`
        `<tipoScheda>2</tipoScheda>`
`</datiControllo>`

Che nel 5005 indica famiglia nuova (pertanto il soggetto doveva essere indicato come intestatario della famiglia, oppure andava indicato tipoScheda 1).

![image](https://user-images.githubusercontent.com/29305782/73759693-9af4dc80-476c-11ea-9884-a122942fa3ea.png)

Potete verificare le specifiche su come comporre la richiesta sul portale ANPR : 
https://www.anpr.interno.it/portale/documentazione-tecnica
Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica 

Saluti

Assistenza ANPR

**Comment by GabriellaBallabio** [comment]
WS5005 per cambio via singolo cittadino con riunione con famiglia esistente.
Abbiamo apportato la modifica indicata, l'ente erroneamente aveva indicato "nuova famiglia" in quanto il cittadino cambiando via entra a far parte di un'altra famiglia (esistente). Purtroppo però non riusciamo a fare la variazione, 

1 mettendo nel xml l'indirizzo di residenza della famiglia il ws ritorna errore dicendo che l'indirizzo è uguale
2 non si può mettere l'indirizzo sul soggetto

Il codice della nuova famiglia quando va indicato ?
