### ISSUE TITLE
Problema su rettifica stato nascita

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#1921]
Comune di Modena - Ambiente di produzione

Buongiorno,
stiamo cercando di rettificare in SERBIA lo stato di nascita di un soggetto che in ANPR ha SERBIA MONTENEGRO e in AE IUGOSLAVIA; la rettifica fallisce con questo errore:

EAM12:  Soggetto non individuato in AT -  Codice fiscale NON variato
EN527: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-03 10:25:42 , idOperazioneANPR 198596121

Si tratta di caso analogo a quello già trattato nella issue #1421 (ed in altre precedenti), anche tentando di riversare il dato di AE su ANPR dalla risoluzione disallineamenti si ottiene un messaggio di operazione andata a buon fine ma non viene modificato nulla. 
Per cortesia potete aiutarci a sbloccare il caso? 
Inoltre, dato che il problema si ripete con una certa frequenza, non sarebbe possibile far funzionare il riversamento dati da AE su ANPR nella risoluzione disallineamenti?

Grazie, saluti
Sonia Fiorini

**Comment by sfmodena** [comment]
Buongiorno,
ci sono novità? Il cittadino deve fare la CIE e ci sollecita.

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Fornita assistenza telefonica per la mutazione dello stato estero di nascita da web app.

N. Capozzi
