### ISSUE TITLE
[N010] Verifica Stato Notifiche

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#1922]
Riferimento issue chiusa #1916 
Ambiente di produzione - Comune di Santa Giustina in Colle
Buongiorno,
si segnala il medesimo caso.
è stata richiesta la notifica mutazioni (N010) dal 30/01/2020 ad oggi.
(idOperazioneANPR 200622004)
la prima disponibilità l'abbiamo avuta alle ore 12.00 e via via ci slitta sempre di un'ora in avanti ad ogni richiesta.
Cortesemente, potreste verificare?
grazie

**Comment by mttfranci** [comment]
Salve, nel caso specifico, ci risulta che la richiesta sia stata inoltrata alle : 
2020-02-05 11:00:03
Ed elaborata alle : 
2020-02-06 00:22:16

In generale il sistema cerca di evadere più velocemente possibile tutte le richieste 4005, ma come già scritto in altre issue (es. #1785 e #1277), il tempo massimo previsto è di 24 ore.

Saluti, 
Assistenza ANPR.
