### ISSUE TITLE
cie per iscritti aire di comune in anpr

### ISSUE THREAD

**Issue by dkwo** [italia/anpr#1923]
E' possibile, per un cittadino iscritto all'AIRE di un comune che sia gia' migrato all'ANPR, richiedere la CIE presso tale comune? E presso qualsiasi altro comune gia' migrato all'ANPR?

**Comment by ncapozzi** [comment]
Buongiorno,
il comune non può emettere la CIE per i cittadini AIRE ma solo la carta di identità cartacea. L'emissione CIE per i cittadini AIRE è possibile al momento solo per i Consolati pilota di Nizza, Vienna e Atene e sarà estesa nei prossimi mesi agli altri Consolati dell'Unione Europea, Svizzera, Monaco Principato, San Marino, Norvegia, Città del Vaticano, Liechtenstein, Andorra, Islanda.

N. Capozzi

**Comment by dkwo** [comment]
> il comune non può emettere la CIE per i cittadini AIRE

Quale e' l'ostruzione?

**Comment by ncapozzi** [comment]
Buongiorno,
il DECRETO 23 dicembre 2015 art. 4 assegna al Consolato la competenza per il rilascio CIE  al
cittadino italiano residente all'estero ed iscritto in ANPR. Tuttavia è già stata prevista la possibilità di estendere anche ai comuni il rilascio della CIE ai cittadini AIRE una volta completata l'estensione agli Uffici Consolari.

N. Capozzi
