### ISSUE TITLE
Anomalia Rettifica paternità e maternità

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1924]
Ambiente di TEST

Buongiorno,
stavamo effettuando alcune prove sulla rettifica della paternità/maternità.
Il problema è il seguente, abbiamo indicato alcune lettere del nome in minuscolo abbiamo fatto il cambio ed è andato a buon fine (idOperazioneANPR 23719952).
Cercando di ripristinare il nome, mettendolo tutto in maiuscolo, facciamo la trasmissione verso ANPR il quale non ci da alcun errore, però poi dal portale il nome è rimasto minuscolo(idOperazioneANPR 23719974).

In poche parole l'operazione 23719952 è andata bene, mentre la seconda 23719974 no.
Sono identiche nella forma e per entrambe non riceviamo errori.

Potete verificare?

Grazie

**Comment by rvinzani** [comment]
Ringrazio per la segnalazione. Verificheremo l'errore.
Nel caso si presentasse in produzione è possibile eliminare i dati di paternità ed acquisirli nuovamente
