### ISSUE TITLE
Certificazione conto terzi non possibile per EN169

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1925]
Buongiorno,

abbiamo riscontrato l'impossibilità di emettere un certificato di stato di famiglia e stato civile per conto terzi a causa dell'errore EN169 "il certificato non può essere emesso perché il richiedente deve essere maggiorenne e appartenente alla stessa famiglia anagrafica dell'intestatario".
I soggetti in questione sono id 28737794 (intestatario) e id  28274760 (delegato).

Inizialmente credevamo che ciò si verificasse perché il soggetto delegato era già stato presente all'interno della famiglia anagrafica dell'intestatario; tuttavia, abbiamo verificato che l'errore si ripresenta anche per soggetti che non hanno mai fatto parte della stessa famiglia anagrafica. 

E' possibile sanare la situazione?
Gli utenti dovrebbero avere la possibilità di certificare per conto terzi qualora siano in regola con i documenti e non siano presenti disallineamenti.

Grazie e buona giornata.

Cordiali saluti.
UPI Torino

**Comment by rvinzani** [comment]
L'errore si verifica richiedendo un certificato di stato di famiglia con relazioni di parentela.
Nel caso segnalato il soggetto delegato non appartiene alla stessa famiglia per questo si verifica l'errore. In realtà per quella famiglia il certificato può essere richiesto solo dall'intestatario in quanto l'altro componente è minorenne
