### ISSUE TITLE
Problema invocando WSCIE2

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#1926]
Buongiorno
Comune Caserta ambiente TEST
invocando il servizio CIE2 evidenzia sempre :
<codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Utente non abilitato 5</testoErroreAnomalia>

**Comment by rvinzani** [comment]
E' possibile avere un suo contatto, anche email? Grazie

**Comment by rinonasti** [comment]
rino.nasti@itsystems.ce.it

**Comment by rinonasti** [comment]
ho provato invocando il servizio 3002 con ricercanazionale=1 (SI)
ma con <idOperazioneANPR>23722967
la richiesta non produce risultato
i dati si riferiscono ad un cittadino residente in un comune subentrato

**Comment by rinonasti** [comment]
id anpr 23722967

**Comment by mttfranci** [comment]
Salve, il codice fiscale del soggetto che avete cercato non sembra essere presente nella banca dati di test comuni ANPR.

Forse potete provare con alcuni di questi soggetti (con il parametro id : 
28465724
28357512
28330857
28330852
27519340
27454493
27432311

Ad esempio : 
      <criteriRicerca>
        <idSchedaSoggettoANPR>27432311</idSchedaSoggettoANPR>
      </criteriRicerca>

Saluti

Assistenza ANPR

**Comment by rinonasti** [comment]
ok grazie proverò.
Il comune potrà interrogare su base dati nazionale (dati reali) solo al pre-subentro?

**Comment by mttfranci** [comment]
In generale potrà cercare solo i soggetti presenti, anche in presubentro non è detto ci siano tutti i soggetti (anzi in generale non ci saranno perchè i comuni sono incoraggiati a cancellare i presubentri dopo il subentro in produzione).
Saluti

Assistenza ANPR
