### ISSUE TITLE
[5001] tipoMutazione '9' - Aggiornamento Residenza AE

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1927]
ambiente di PRODUZIONE - comune di REGGELLO (048035)

con la comunicazione con idANPR 193338841 è stata inviata la 'Rettifica/Integrazione indirizzo' (tipoMutazione '9') per la famiglia con idANPR 24125295.

la decorrenza della comunicazione che è stata indicata è 19/11/2011, ovvero - come previsto per questo tipo di comunicazione - la data di decorrenza più vecchia per tutti i soggetti presenti nel nucleo.
negli archivi ANPR, tutti i componenti del nucleo hanno subito - come previsto - la variazione dell'indirizzo, ma NON la variazione della propria data di decorrenza di residneza.
diversamente in AE, sembra che la data decorrenza sia stata modificata.

nel caso specifico: il soggetto con idANPR 74139594, in ANPR risulta con dataDecorrenzaResidenza 22/10/2019, mentre in AE risulta residente all'indirizzo dal 19/11/2011.

potere verificare per capire come mai sia stata aggiornata la decorrenza in AE?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Abbiamo riscontrato un bug nella notifica ad AE in caso di rettifica dell'indirizzo; il bug è stato rimosso e 
l'aggiornamento sarà disponibile in ambiente di produzione lunedì  17/02/2020.
Grazie per la segnalazione.
