### ISSUE TITLE
[WebApp] problema su comune trascrizione unione civile

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#1928]
Ci siamo accorti per caso in produzione e in test, che caricando da WA l'atto di unione civile, la combo della provincia, viene valorizzata con LITTORIA al posto di LATINA, anche per date recenti.

![image](https://user-images.githubusercontent.com/26630945/74015024-24382900-4990-11ea-8b7f-5a7b2e3aab31.png)

**Comment by rvinzani** [comment]
Per aiutarci nel replicare il problema potreste fornirci qualche informazione sul caso in cui l’operazione si è presentata? : 
-	Il tipo di operazione (Iscrizione, Mutazione)
-	Nel caso l’operazione fosse su un soggetto (es mutazione tutti i dati), l’id soggetto anpr del soggetto in questione
-	Ogni altra informazione utile a replicare il problema

**Comment by MarcoMigliori** [comment]
In produzione non ricordo il cittadino su cui si è presentato il problema.

In ambiente di test uso cittadino id 22090757.
- Mutazione tutti i dati
- scelgo generalità e unione civile come dati da modificare
- in generalità metto unito civilmente
- in unione civile mi invento nome e cognome dell'altro, nella sezione "Dati della persona unita civilmente";
poi metto l'evento esempio 02.02.2020 e un comune italiano della provincia di Latina; infine nella sezione atto se metto date di formazione atto recenti, mi mette come provincia LITTORIA come da videata qua sopra

**Comment by rvinzani** [comment]
Il problema segnalato è stato risolto in tutti gli ambienti di ANPR. 
Chiudo pertanto la issue. In caso di ulteriore segnalazione si prega di aprire una nuova issue che faccia riferimento a questa stessa
