### ISSUE TITLE
Soggetto non presente con ID di subentro

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1929]
Buongiorno,
in fase di subentro abbiamo riversato in anpr il soggetto con ID 28683565.
Il soggetto è successivamente emigrato in altro comune ma in data 06.02.2020 chiede nuovamente iscrizione a Torino.
Abbiamo riscontrato diversi problemi in fase di iscrizione in quanto, il gestionale ha più volte annullato la pratica, che non è mai riuscita ad avere esito positivo.
Dopo svariati controlli ed opportune verifiche, abbiamo notato che la scheda con ID 28683565 non è più presente in anpr ma, il soggetto, è presente con altra scheda ID 77438870.
Potrebbe essere frutto di un trattamento dati? In tal caso, potrebbe essere previsto un servizio di notifica che permetta al Comune di verificare e sanare la posizione?
Cordiali Saluti
Floramo S.

**Comment by rvinzani** [comment]
Non risultano in ambiente di produzione soggetti con tali id assegnato, ne' si tratta di un trattamento dati

**Comment by UpiTorino** [comment]
Buongiorno,
infatti il dubbio nasce proprio dal fatto che l'ID 28683565 non è presente in ambiente di produzione ma era stato attribuito al soggetto avente ora ID 77438870 in fase di subentro del comune di Torino.
Cordiali Saluti
Floramo S.

**Comment by rvinzani** [comment]
l’idANPR 28683565, da voi cancellato per emigrazione,  è stato riassegnato al soggetto al momento del subentro in ANPR del nuovo comune di residenza.
Quest’ultimo ha effettuato un errore nell’invio del file che ci ha costretto a stornare manualmente il suo subentro.  In questa operazione si è perso il legame con il precedente idANPR (assegnato al subentro di Torino) e ne è stato generato uno nuovo (77438870).

**Comment by UpiTorino** [comment]
Va bene, grazie!
In questi casi, sarebbe possibile ricevere una notifica o una segnalazione in modo da poter allineare le due banche dati (comunale e nazionale)?
Grazie
Cordiali Saluti
Floramo S.

**Comment by rvinzani** [comment]
Come ho spiegato si è trattato di un'operazione di emergenza. Non sono casi che si presentano normalmente.
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti vi prego di aprire una nuova issue che faccia riferimento a questa stessa
