### ISSUE TITLE
WS 5005 - cambio residenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1930]
COMUNE DI CAPONAGO
Invocazione WS5005 x cambio di via singolo cittadino con riunione in famiglia esistente :

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-07 11:17:53 , mittente 108052 , idOperazioneComune 20200207111504

Restituisce l'errore EN493 - L'utente non dispone dei privilegi per eseguire l' operazione , di cosa si tratta ?

**Comment by frmariani** [comment]
Per favore controlli il dato inserito nell'oggetto idFamigliaConvivenzaComune:  ci risultano due famiglie con gli stessi dati identificati del comune.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
