### ISSUE TITLE
Scenari d'uso WS

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#1931]
Salve, mi riallaccio all'issue [#1908](https://github.com/italia/anpr/issues/1908#issue-555666778) e mi unisco alla domanda, di sicuro interesse anche per i comuni.

Nel caso particolare, oggetto dell'interesse è valutare la conformità di scenari d'uso dei WS di ANPR ulteriori rispetto a quelli descritti nel documento "specifiche di interfaccia", au punti 6.1.2 (con interazione umana)  e 6.1.4 (senza interazione umana).

Faccio un esempio di scenario, pregando di cogliere gli aspetti generali di interazione con i WS di ANPR e non focalizzarsi su aspetti specifici di dettaglio.
La necessità primaria è valutare la conformità complessiva alle specifiche di ANPR e alle condizioni per il suo uso.

Agenti di polizia locale in servizio su strada sono dotati di un dispositivo mobile (tablet) con app/webapp che si collega a un server comunale S per svolgere varie funzioni, fra le quali interrogazioni di ANPR.
L'interrogazione di ANPR parte dal server S che poi si occupa di distribuire la risposta ai client su strada.
DOMANDE;
* Gli agenti possono essere censtiti come utenti del comune in ANPR e quindi l'asserzione SAML ontiene il loro identificativo?
* Cosa si trasmette come ID postazione? Ogni tablet è una postazione o si considera il server S come postazione?  
* Serve un'ulteriore appID per il server S?
* Il server S utiliza per la firma dell'asserzione SAML la chiave privata dello stesso certificato di autenticazione rilascaito al Comune per il software d'anagrafe?
* Ci sono prescrizioni di sicurezza specifiche di ANPR per come il server S interagisce coi client su strada oppure questa è tutta una questione interna al perimetro del sistema informativo comunale?
* Ci sono ulteriori adempimenti "giuridici" relativi alla gestione di dati provenienti da ANPR da implementare nell'applicazione servita dal server S?

Ipotizzando altri due SCENARI AGGIUNTIVI simili a quello descritto:
* Applicazione web per la gestione dei tributi o delle notifihe che, come funzione aggiuntiva, esegue interrogazioni di ANPR.
* Protocollo informatico, per individuare correttamente i corrispondenti delle comunicazioni in partenza e in arrivo.
Ci sono aspetti aggiuntivi da considerare in questi ulteriori scenari?

**Comment by FilippoPapi** [comment]
buongiorno,
la possibilità di accedere a ANPR non è legata al software mediante cui si accede bensì alla legittimità dell'accesso dell'utente. Il DPCM194 prevede che a ANPR possono accedere esclusivamente gli Ufficiali di Anagrafe.
saluti

**Comment by franthemanIT** [comment]
Grazie.
Ho scorso attentamente il dpcm indicato, senza pero' essere stato in grado di trovare la disposizione che indica. Puo' darmi un riferimento piu' puntuale?
