### ISSUE TITLE
[5005] EN388 - La residenza inserita risulta uguale a quella attuale

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1932]
Buongiorno.
Stiamo effettuando dei test per capire con quale tipologia di mutazione residenza viene restituito l'errore: **EN388 - La residenza inserita risulta uguale a quella attuale**

Effettuando diverse prove sembra che effettuando mutazione residenza 
in cui aggiungo 
` <interno1>A</interno1> `

la mutazione residenza và a buon fine.
Mentre se passo da 
` <interno1>A</interno1>`
 a 
 `<interno1>B</interno1>`

mi viene restituito errore 
EN388 - La residenza inserita risulta uguale a quella attuale

Avrei bisogno di avere chiarimenti in merito.
GRAZIE.

**Comment by rvinzani** [comment]
Potete per favore restituirci l'IDANPR delle operazioni andate o meno a buon fine?

**Comment by fmbianchi** [comment]
5005 accettata su stesso indirizzo con aggiunta interno A
```
<idOperazioneComune>20200210092632662</idOperazioneComune>
<dataOraRichiesta>2020-02-10T09:26:32</dataOraRichiesta>
<tipoInvio>PRE_SUB</tipoInvio>
<civicoInterno>
<interno1>A</interno1>
</civicoInterno>

```
5005 rifiutata su stesso indirizzo da interno A ad interno B
```
<idOperazioneComune>20200210092923834</idOperazioneComune>
<dataOraRichiesta>2020-02-10T09:29:23</dataOraRichiesta>
<tipoInvio>PRE_SUB</tipoInvio>
<civicoInterno>
<interno1>B</interno1>
</civicoInterno>

```

**Comment by rvinzani** [comment]
Il problema segnalato è stato risolto in tutti gli ambienti di ANPR. 
Chiudo pertanto la issue. In caso di ulteriore segnalazione si prega di aprire una nuova issue che faccia riferimento a questa stessa
