### ISSUE TITLE
[5005] Iscrizione da Comune Subentrato - Errore EN237

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1933]
ambiente di PRODUZIONE - comune di CASTEL GUELFO DI BOLOGNA (037016)

idOperazioneComune 2020000177
idSoggettoANPR 27961986

soggetto già iscritto con ws 5005, poi annullato con ws 5012 e nuovamente da iscrivere con ws 5005.
quest'ultimo tentativo di mutazione va in errore con questo messaggio:
EN237 - E - La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata

nel comune di attuale iscrizione ANPR, le date di riferimento sono tutte antecedenti alla decorrenza dell'iscrizione.

potete indicarci cosa blocca l'iscrizione?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
la famiglia in cui il cittadino si sta spostando è stata creata il 31/01/2020, mentre la data di decorrenza dell'operazione fallita risulta 30/01/2020

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
