### ISSUE TITLE
Certificato Contestuale (stato di famiglia + residenza + contratto di convivenza)

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1934]
Ambiente di Test
Comune di Gorgonzola

facendo un certificato contestuale (stato di famiglia + residenza + contratto di convivenza),
ricevo un errore 
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
"Operazione non effettuabile"
Id. Operazione 23725198
(gli stessi certificati, selezionati singolarmente, funzionano senza problemi)

**Comment by rnapoli1983** [comment]
Buonasera,

siamo a conoscenza del problema e già lo abbiamo risolto.

Uscirà prossimamente una versione del servizio di certificazione anagrafica con la fix relativa a questo bug.

Cordiali saluti
