### ISSUE TITLE
ws [A006] - problema decorrenza espatrio

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1935]
Buon giorno,
il comune di Scurcola Marsicana (subentrato) ci ha esposto il seguente problema, ha iniziato una pratica di espatrio con istanza di persona legittima in data 30/12/2018, senza definirla perché sostengono che la legge dice che poi dovrà essere confermata tramite il consolato entro un certo periodo.
Il comune è successivamente subentrato in ANPR in data 25/07/2019 e si trova oggi a dover definire la pratica, dovendo però indicare come decorrenza la data del 2018 pena la perdita da parte del cittadino di alcuni diritti (che a dire il vero non ci ha ben specificato).
A questo punto la registrazione dell'evento di espatrio col WS in oggetto, definendo la pratica con tale decorrenza, genera un errore a causa della decorrenza antecedente all'ultimo movimento fatto in ANPR (in questo caso il subentro).
Come possiamo procedere in questa situazione? Possiamo considerare il caso di un espatrio precedente al subentro come una iscrizione AIRE per altri motivi (trasferimento residenza all'estero) e quindi utilizzare il ws A002 indicando la decorrenza specificata dal comune?
Oppure l'ente deve attivarsi col numero verde per risolvere il problema esaminando direttamente i dati e la situazione del cittadino?
L'individuo in questione ha id ANPR 64795157, l'id operazione comune è 06609620200210114.
In attesa di riscontro,
cordiali saluti.
Giuseppe Mucciarelli,
TINN srl

**Comment by rvinzani** [comment]
E' possibile, tramite la funzione di rettifica date, aggiornare, solo dopo il subentro, la data di decorrenza della residenza, la data di ultimo aggiornamento della scheda, la data di iscrizione nel comune e la data di ingresso in famiglia
