### ISSUE TITLE
Problematica Gestione CF Validato AE non consultabile da specifica funzione WebApp

### ISSUE THREAD

**Issue by giuannitre** [italia/anpr#1936]
Buongiorno,

sono Giovanni Trento del Comune di Parabiago.
Devo modificare le generalità di un cittadino Egiziano CF in ANPR (HMDMMD85A06Z336D) Presente in ANPR e con Stato CF Validato AE.
Al tentativo di operare la mutazione mi viene restituito errore di 
"Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)"

Ho quindi verificato la situazione tramite la WebApp e il CF risulta "Validato AE" ma alla consultazione dalla specifica funzionalità (Consultazione AE) viene restituito il messaggio "Esito AE: Codice Fiscale non trovato (Codice 90)".

Chiedo di verificare l'anomalia.

Cordiali saluti,

Giovannni Trento

**Comment by rvinzani** [comment]
Il codice fiscale risulta richiesto tramite operazione di mutazione tutti i dati (con richiesta attribuzione CF). Probabilmente ne è stata richiesta l'eliminazione direttamente ad Agenzia Entrate
