### ISSUE TITLE
Notifiche non ancora soddisfatte

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1938]
Comune di Prato
Ambiente di produzione

Buongiorno,
segnalo che le richieste di tipo 4005 avviate ieri pomeriggio dal Comune in oggetto
non sono ancora state soddisfatte. 
E' possibile avere riscontri? 
Grazie

**Comment by mttfranci** [comment]
Salve, ad una prima Analisi non risultano richiesta 4005 inserite nella giornata del 10 Febbraio 2020 ancora in coda per essere elaborate.
Potete fornirci alcuni casi concreti (id delle elaborazione) per poter meglio verificare?

Ricordiamo inoltre che il sistema cerca di evadere più velocemente possibile tutte le richieste 4005, ma come già scritto in altre issue (es. #1785 e #1277), il tempo massimo previsto è di 24 ore.

Saluti

Assistenza ANPR

**Comment by c-giacomini** [comment]
gli ID ANPR delle richieste più vecchie sono:
204240981
204240984
204240987
204267394

Grazie

**Comment by mttfranci** [comment]
Salve, ci risulta che le richieste indicate siano di oggi dopo la mezzanotte.
Ora sembrano essere tutte elaborate.
Saluti

Assistenza ANPR
