### ISSUE TITLE
[5008] Anomalia su mutazione scheda - atto di nascita

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1939]
Comune di Torino - Ambiente di produzione

Buongiorno,
è stata fatta per un soggetto del Comune di Torino una mutazione scheda 5008 per integrare i dati dell'atto di nascita (tipo mutazione 20).
Il sistema ha recepito la richiesta (id 204431894) completata con esito positivo e warning ma i dati conferiti non sono stati recepiti da ANPR.
Ci si aspettava o di vedere i dati inviati (seppure con warning) oppure un errore sulla richiesta.

Potete verificare e darci riscontro?

Grazie,
Silvio Guala

**Comment by rvinzani** [comment]
Da una verifica fatta su ANPR mi sembra che i darti presenti nella richiesta di mutazione siano quelli presenti su ANPR. Quali sarebbero le incongruenze?

**Comment by CSI-Piemonte-Demografia** [comment]
I dati sono stati aggiornati dagli operatori del comune per necessità, con una mutazione effettuata da web app (id operazione 204458148). Prima di questa operazione, erano stati inviati i dati relativi all'atto di nascita con la mutazione avente id operazione 204431894, ma questi non sono stati aggiornati. Potremmo sapere il motivo?

Grazie.
Chiara Leanza

**Comment by rvinzani** [comment]
Mi risulta che le operazioni effettuate sull'atto di nascita : 204431894 (11/02/2020 09:06) e 204458148 ( 11/02/2020 09:17:41) abbiano dato origine ad un atto di nascita con le stesse caratteristiche 
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
