### ISSUE TITLE
Mancato recapito tessere sanitarie in comune fuso subentrato in ANPR

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#1940]
Il comune di Valsamoggia è nato l’1/01/2014 per fusione dei comuni di Bazzano, Castello di Serravalle, Crespellano, Monteveglio e Savigno.
La denominazione degli ex comuni è stata mantenuta come frazione, anche per gestire il problema delle aree di circolazione aventi la stessa denominazione, considerato che Poste Italiane non ha concesso il mantenimento dei vecchi codici di avviamento postale; quindi il cap 40053, che era quello di Bazzano, è andato a costituire il cap di tutto il comune di Valsamoggia (40056 di Crespellano, 40050 di Castello di Serravalle – Monteveglio e 40060 Savigno sono stati soppressi).
Nei primi mesi del 2014 abbiamo fatto un’operazione massiva di allineamento dei codici fiscali dei residenti e l’Agenzia delle Entrate aveva regolarmente recepito l’indicazione della frazione.
Succede poi che il 10/07/2018 il comune di Valsamoggia subentra in ANPR e, nonostante i tecnici della nostra software house (Maggioli) abbiano verificato che il dato riferito alla frazione fosse stato regolarmente trattato, la sua indicazione è sparita dal dato relativo al domicilio fiscale dell'Agenzia delle Entrate.
Ci stiamo rendendo conto, in seguito a numerosissime segnalazioni dei cittadini, che questo ha un impatto fortissimo sulle operazioni di recapito della tessera sanitaria.
Infatti, con la collega che si occupa della gestione delle anagrafiche della nostra Asl di riferimento, abbiamo simulato una richiesta di duplicato ed il risultato del nostro esempio è il seguente:
- persona residente al seguente indirizzo anpr
Via Borghetto 6 CRESPELLANO
40053 VALSAMOGGIA BO
- la visura del domicilio fiscale di Punto Fisco  è
Via Borghetto 6
40053 VALSAMOGGIA BO
- l’indirizzo di recapito della nuova tessera sanitaria viene generato nel seguente modo
BAZZANO VIA BORGHETTO BAZZANO 6
40053 VALSAMOGGIA BO
Quindi sembrerebbe che il sistema di invio delle tessere sanitarie associ automaticamente la frazione Bazzano al cap 40053.
Inizialmente abbiamo pensato che il problema si presentasse solamente per i residenti in via la cui denominazione compariva in più di una frazione, ma ora ci stiamo rendendo conto che è generalizzato: Via Borghetto, per intenderci, esiste solo a Crespellano, ma la tessera sanitaria non è stata comunque recapitata.
Vorrei quindi capire se esiste la possibilità di risolvere il problema in forma massiva, considerato il fatto che ormai stiamo ricevendo più segnalazioni al giorno.

**Comment by rvinzani** [comment]
E' previsto un intervento sui sistemi di Agenzia Entrate per allineare i dati relativi alla residenza ad ANPR (#1944 )
