### ISSUE TITLE
Notifiche su operazioni a cavallo del subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1942]
Buon giorno, 
vi segnaliamo il seguente caso, un cittadino ha effettuato una immigrazione con decorrenza 04/11/2019, dal comune di Cepagatti al comune di Villa Santa Lucia negli Abruzzi, all'epoca ancora non subentrati. Il comune di immigrazione è poi subentrato in data 04/12/2019 e quindi ha iscritto il cittadino col subentro. Nel frattempo anche il comune di emigrazione è subentrato, in data 03/12/2019.
Il comune di immigrazione però in data 10/02/2020 ha rigettato l'iscrizione del cittadino, effettuando una cancellazione per ripristino posizione precedente con decorrenza dal 04/11/2019. Dato che il comune di emigrazione è subentrato, ci saremmo aspettati una notifica N014 con cui avrebbe dovuto provvedere al ripristino della iscrizione ma ad oggi non è stata ancora ricevuta, né sulla WebApp né tramite WS (il comune ha infatti appreso del rigetto tramite una pratica cartacea ricevuta dal comune di immigrazione).
Operando come da documentazione abbiamo comunque creato una pratica di iscrizione per ripristino posizione (ws 1002 - motivo iscrizione 10) e l'iscrizione è andata a buon fine, vi chiediamo però, la mancata generazione della notifica è un errore contingente del sistema, oppure il fatto che alla data di decorrenza del ripristino il comune di emigrazione non fosse subentrato ha causato la mancata generazione della stessa?
Anche in questo caso infatti senza notifiche il comune non avrebbe modo di sapere del ripristino della posizione, a meno di non ricevere una pratica cartacea.
In attesa di riscontro,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by frmariani** [comment]
La notifica non è stata generata perchè non è stato inserito il Comune di destinazione nell'operazione di Cancellazione per ripristino posizione precedente;
in questo caso, al sistema manca l'informazione necessaria per l'invio della notifica N014.

**Comment by Amucciarelli74** [comment]
Ok perfetto,
quindi in ogni caso il comune di Cepagatti, come ci attendevamo, avrebbe dovuto ricevere una notifica dal comune di Villa Santa Lucia al momento della cancellazione.
Grazie per il risconto,
cordiali saluti.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
