### ISSUE TITLE
Richiesta cancellazione da altro Comune subentrato

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#1945]
Buongiorno,
Abbiamo ricevuto in data 01.02.2020 dal Comune di San Donato Milanese (MI), comune subentrato, richiesta di cancellazione di un cittadino per immigrazione con una decorrenza 15.06.2018.
Ricercando il cittadino in ANPR risulta ancora iscritto nel nostro comune con ID 19158299 e non risulta duplicato.
Si precisa che lo stesso cittadino era stato ripristinato sempre con notifica del Comune di San Donato Milanese (MI) in data 22.02.2019.
Come devo procedere?
Attendiamo riscontro e ringraziamo per la collaborazione

**Comment by frmariani** [comment]
La richiesta di cancellazione di un cittadino da un Comune subentrato non è corretta, perchè in questo caso deve essere effettuata una mutazione di residenza.
Ho contattato il Comune e abbiamo risolto la situazione; riceverà la notifica da parte del sistema ANPR per eliminare il cittadino dalla vostra base dati locale.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
