### ISSUE TITLE
5001 rimpatrio intera famiglia AIRE in APR dello stesso comune, errore EF001

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1946]
Salve, vi contattiamo per l'ambiente di pre-subentro del comune di Potenza (codice istat: 076063).
Abbiamo un problema in fase di trasferimento intera famiglia AIRE in APR dello stesso comune (quindi rimpatrio da aire intero nucleo famigliare) .  
IDoperazioneANPR: 16538800 La mutazione è andata a buon fine ma in ANPR l'identificativo scheda famiglia attribuito dal comune risulta essere 0 (zero) ed il codice istat invece opportunamente avvalorato (076063). Nella nostra richiesta di mutazione 5001 non abbiamo inviato l'identificativo scheda famiglia attribuito dal comune per non incorrere in un errore "EF001", così come accade per l'operazione successiva con IDoperazioneANPR: 16539028, nella quale abbiamo inviato il codice della nuova famiglia residente da noi attribuitogli.
Noi abbiamo necessità di assegnare un codice alla nuova famiglia creata in APR a partire dal reimpatrio della famiglia aire, ma purtroppo ci è impossibile, visto il comportamento dell'invocazione del servizio come descritto sopra: se non lo inviamo l'operazione va a buon fine, ma il codice zero non ci permette di identificare la famiglia, se invece lo inviamo, l'operazione fallisce con l'errore EF001. Come facciamo a fare la mutazione e contemporaneamente ad assegnare il codice famiglia, senza incorrere in errori?

Grazie, buona giornata

**Comment by frmariani** [comment]
Nel servizio 5001 non è possibile la scelta multipla delle mutazioni, pertanto dovete prevedere più operazioni: Mutazione di residenza (WS 5001 tipo mutazione 4)   e successivamente Mutazione Motivo Famiglia/ Specie Convivenza (WS 5001 tipo mutazione 3) con la quale potrete inserire il vostro identificativo comunale alla famiglia; 
Naturalmente l'operazione idanpr 16539028 è fallita perchè il sistema ANPR non conosce quell'identificativo inserito in fase di mutazione di residenza.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.

**Comment by carminepat** [comment]
Perfetto, provvederemo ad implementare le chiamate al servizio in sequenza, come da voi indicato. Grazie, buon lavoro
