### ISSUE TITLE
ws 2001 - errore comune di registrazione atto di morte

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#1947]
Buon giorno,
il comune di Cepagatti sta tentando di registrare il decesso di un individuo (id scheda soggetto ANPR 79785045) indicando come comune di registrazione evento TOCCO DA CASAURIA, ma ottiene in risposta l'errore "comune/provincia di registrazione atto di morte TOCCO DA CASAURIA (PE) inesistente". 
Abbiamo controllato la request ma il nome del comune, la provincia di registrazione dell'atto e il codice Istat comunicato (68042) ci sembrano coerenti con l'archivio corrente dei comuni, per cui non riusciamo a capire come procedere con la registrazione del decesso.
L'id operazione comune è 06801120200217241.
In attesa di riscontro, cordiali saluti.
Giuseppe Mucciarelli, TINN srl

**Comment by rvinzani** [comment]
Nella richiesta 2001, per la denominazione del comune (di morte e di registrazione dell'atto) sono presenti due spazi dopo TOCCO
TOCCO  DA CASAURIA
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
