### ISSUE TITLE
servizio di notifica non funziona in ambiente di pre-subentro

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1948]
Vi segnalo che per il servizio di notifiche del comune di Matera (cod istat: 077014) configurato alla stessa maniera sia in pre-subentro sia in ambiente di produzione. In ambiente di produzione riesco ad invocare con successo il servizio di notifica, in ambiente di pre-subentro fallisce l'invocazione, con ESITO: 2 ERRORE: Errore nell'invio della notifica di test

**Comment by gife67** [comment]
Buongiorno,
in ambiente di Presubentro occorre configurare il certificato utilizzato per cryptare le notifiche. Per i vostri test preferite che vi inviamo le notifiche con il certificato 077014-CO-9999 relativo all'ambiente di Test o di Produzione? Di prassi vi dovrei configurare quello di produzione, per il fatto che ora il sistema di sicurezza dell'ambiente di Presubentro è equiparato all'ambiente di Produzione,  ma se preferite vi posso configurare quello di test, anche se ho verificato che l'endpoint specificato è lo stesso per i 2 ambienti. Attendo le vostre indicazioni.

**Comment by gife67** [comment]
Ho provveduto a configurare il certificato di Produzione, quindi le notifiche che vi inviamo sono crittografate con il relativo certificato. Potete riprovare il test quando volete.

**Comment by carminepat** [comment]
Perfetto, il test è andato a buon fine anche nell'ambiente di pre-subentro. Quando passeremo in ambiente di produzione, riavvieremo il nostro servizio di ascolto, facendolo puntare alla banca dati di produzione e registreremo le notifiche in produzione (in APR locale). Ma se attiviamo il servizio di notifica su altri comuni, abbiamo bisogno di aprirvi un ticket o stiamo saltando noi qualche passaggio?

**Comment by gife67** [comment]
Per l'ambiente di presubentro mi dovreste comunicare i codici istat dei Comuni che sono attestati al vostro endpoint, perchè devo configurarvi i certificati. Mentre per l'ambiente di Produzione non è necessario fare nulla, se non indicare il corretto endpoint nell'apposita sezione dei dati del Comune, che per il Comune di Matera avevate già correttamente impostato.

**Comment by carminepat** [comment]
Ok, grazie mille per la chiarezza e disponibilità. Buona giornata e buon lavoro

**Comment by gife67** [comment]
Buona giornata a voi
