### ISSUE TITLE
Duplice iscrizione Aire 

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#1949]
Buongiorno,
nell'emettere certificazione anagrafica di questa cittadina aire con ID 19150189 , ci siamo accorti che la medesima risulta essere ancora iscritta come AIRE anche in altro comune italiano subentrato (CARONIA-ME) con ID 78894900.
Il comune competente all'iscrizione è il nostro in quanto ultimo comune di residenza prima dell'espatrio. Il comune di Caronia è stato sollecitato negli anni scorsi (dal 2004) a provvedere alla cancellazione per doppia iscrizione aire senza mai avere seguito.
Come possiamo procedere ulteriormente?
grazie infinite

**Comment by rvinzani** [comment]
Abbiamo contattato il comune di Caronia che però richiede una comunicazione da parte del cittadino o del consolato per effettuare la cancellazione. Comunque la persona con cui abbiamo parlato ha preso nota della segnalazione
