### ISSUE TITLE
[5008] - WS - Mutazione di cittadinanza

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#195]
31/05/2017 - Comune di Anzola dell'Emilia - Datagraph - Ambiente di Subentro.
Inviando una richiesta di Mutazione di Cittadinanza per acquisto cittadinanza italiana a seguito della registrazione in Anagrafe di un Atto di Stato Civile di Cittadinanza, ottengo l'errore bloccante:

```xml
    <errore>
        <codiceErroreAnomalia>EHR84</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Data di definizione della pratica 27-05-2017 minore della data di decorrenza dell'operazione richiesta</testoErroreAnomalia>
      </errore>
```
Nel nostro applicativo, la data di definizione della pratica, nel caso di trasferimento di atti da Stato Civile è appunto la data di stesura dell'atto. L'atto di cittadinanza è l'unico caso in cui la decorrenza (data giuridica dell'acquisto di cittadinanza) è superiore (di un giorno) alla data di stesura dell'atto (nostra definizione della pratica). 
Come si può risolvere?

Grazie.

Alessio Tropeano

p.s.   <idOperazioneANPR>579176</idOperazioneANPR>

**Comment by gcarbonin** [comment]
Il controllo di congruenza tra data decorrenza e data di definizione pratica è un controllo che riguarda la registrazione anagrafica (è la definizione della pratica di mutazione e non della cittadinanza), in questo senso la seconda non può essere minore della prima; per altro sono date di tipo generale e non relative ad un singolo evento e una modifica del controllo solo per la cittadinanza non è possibile, anche in considerazione del fatto che la scelta di impostare in questo modo la data di definizione della pratica è una scelta implementativa e non un obbligo derivante da una disposizione normativa o amministrativa. Si tratta in ogni caso di un dato facoltativo (non previsto sulla scheda anagrafica)  che potete omettere di trasmettere. Qualora il comune ritenesse indispensabile questa informazione ( che compare solo nelle interrogazioni), dobbiamo intervenire sul servizio prevedendo , a questo punto, gli estremi dell'atto e la data di formazione.
