### ISSUE TITLE
[5008] Anomalia su mutazione scheda - atto di nascita

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1950]
Comune di Torino - Ambiente di produzione

Buongiorno,
con riferimento alla issue https://github.com/italia/anpr/issues/1939 abbiamo visto che non sembra essere così come descritto nell'ultimo commento (https://github.com/italia/anpr/issues/1939#issuecomment-586383124).
In particolare le due operazioni a cui si fa riferimento nella risposta non sono esattamente identiche in quanto la seconda è stata eseguita perchè l'atto di nascita non era visibile in fase di consultazione e la data di decorrenza è 11/02/2020. 
Nella prima operazione invece la data decorrenza era 24/04/2019.

Provando a fare una consultazione per data decorrenza 25/04/2019 non si vede la sezione Atto di Nascita prova del fatto che la prima operazione, seppure terminata con esito positivo e warning, non ha recepito tutte le modifiche richieste.

Potete verificare il caso?

grazie,
Silvio Guala

**Comment by rvinzani** [comment]
La consultazione alla data è rispetto alla data in cui è stata effettuata l'operazione che è per tutti e due gli aggiornamenti quella del 11/02/2020. Vi prego quindi di segnalare un eventuale caso simile al momento in cui si verifica prima di effettuare una nuova operazione.
