### ISSUE TITLE
[5008] Mutazione Cognome - Errore EAM95

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1951]
ambiente di PRODUZIONE - comune di GUASTALLA (035024)

soggetto straniero con idANPR 23387461 deve registrare la variazione di cognome in seguito a divorzio.
l'invio della comunicazione ritorna questo errore:
EAM95 - E - Variazione non consentita, soggetto registrato in AT ANPR di altro comune
EN527 - E - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-14 08:18:31 , idOperazioneANPR 206881754

il cliente ha verificato che il codice fiscale che, presumibilmente, dovrebbe acquisire il soggetto non risulta nè in AT nè in ANPR.

è stato contattato il n.ro verde, ma è stato risposto al cliente di rivolgersi alla software house.
a questo punto chiediamo anche qui come identificare le cause del blocco.

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Potete riprovare ora?

**Comment by AMonopoliADS** [comment]
ripetuto l'invio, l'operazione è andata a buon fine.
grazie
