### ISSUE TITLE
Significato acronimo CODAT tabella stati esteri

### ISSUE THREAD

**Issue by giorgialodi** [italia/anpr#1953]
Gentilissimi,

potete indicare il significato per esteso della colonna CODAT all'interno della tabella stati esteri? 
E' il codice catastale per paesi esteri da usare nella formazione del nostro codice fiscale?

Potrebbe essere utile aggiungere  la legenda per la tabella stati esteri così come è stato fatto tempo fa per la tabella archivio storico dei comuni. 

Grazie per le risposte che vorrete darmi (cc @mccalv)
Giorgia

**Comment by MassimoSchiappa** [comment]
Salve,
il CODAT è il codice assegnato agli stati esteri dall'Anagrafe Tributaria per la formazione del codice fiscale. 
Grazie per il suggerimento relativo alla legenda per la tabella degli stati esteri, cercheremo di accoglierlo e metterlo in pratica appena possibile.
Saluti.

**Comment by MassimoSchiappa** [comment]
Saluti.
