### ISSUE TITLE
[5005] L'operazione di ripristino residenza e' consentita soltanto a valle del subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1954]
Ambiente di produzione, comune di Acireale.

Tentiamo di chiamare il servizio in oggetto per seguire una mutazione ti tipo 6 (Ripristino residenza ante subentro), ma veniamo bloccati dall'errore "EN416 : L'operazione di ripristino residenza e' consentita soltanto a valle del subentro". ID operazione ANPR 209082786

Come mai questo blocco ?

**Comment by frmariani** [comment]
Come cita l'errore, l'operazione di Ripristino residenza ante subentro può essere effettuata soltanto a valle del subentro;
nel vostro caso, il 20 Gennaio 2020, con l'idoperazioneanpr 189159651, è stata effettuata una rettifica/integrazione indirizzo, pertanto l'operazione di ripristino non è consentita.
Nel caso fosse necessario, eliminate l'operazione idanpr 189159651 e procedete con l'operazione di Ripristino residenza ante subentro

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
