### ISSUE TITLE
Cambio cognome cittadino comunitario con omocodia

### ISSUE THREAD

**Issue by FrancescoPipitone** [italia/anpr#1955]
Una cittadina rumena ha chiesto di variare il proprio cognome in quanto, a seguito di divorzio, ha riacquistato quello da nubile. Ho già trovato un caso simile (segnalazioni #1572 #1660) e ho già richiesto il cambio di generalità e l'attribuzione del nuovo codice fiscale a entrate.archivioanagrafico@agenziaentrate.it come suggerito nella segnalazione. 
Il nuovo CF è stato assegnato il 14/02/2020, ma non riesco ad allineare Anpr con AE, sia dal mio applicativo che dalla webapp. 
Questo è il messaggio d'errore:
Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-18 14:12:09 , idOperazioneANPR 209429604 (Codice: EN527)

La segnalazione #1660 è stata chiusa con un vostro intervento diretto. 
Chiedo indicazioni su come risolvere il problema.
Grazie

**Comment by rvinzani** [comment]
Le abbiamo assegnato il ticket 21127409. La chiameremo quanto prima
