### ISSUE TITLE
[Subentro] errata visualizzazione caratteri accentati URGENTE

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1956]
Ambiente di produzione, comune di Trento

oggi 28/02/2020, all'atto del subentro, abbiamo inviato nel tag "ufficioMunicipio" dei testi contenenti tra l'altro delle lettere accentate. (es "Trento-Città"). Il file XML di subentro contiene i valori corretti che abbiamo estratto ed ha superato i controlli di validazione.

A subentro terminato, le consultazioni sia da webapp che da web-service non ritornano il valore corretto bensì "1 - Trento-Citt��". Porto ad esempio il cittadino ID ANPR 86656660

Come mai ? Potete risolvere con urgenza ? 

Grazie

**Comment by mttfranci** [comment]
Salve, stiamo verificando quale sia l'origine della situazione, ma se ci date conferma che per voi va bene, possiamo procedere a sanare la situazione correggendo tutti i record coinvolti in : 
"1 - Trento-Città"

Abbiamo anche verificato che, almeno per il campo ufficioMunicipio, non dovrebbero esserci altre casistiche con caratteri accentati non corretti.

Saluti

Assistenza ANPR

**Comment by busaster** [comment]
D'accordo, procedere con la correzione massiva.

**Comment by mttfranci** [comment]
Ok, dovremmo aver sanato la situazione.
Saluti

Assistenza ANPR
