### ISSUE TITLE
[5001] tipoMutazione '2' / Aggiornamento MCTC - Chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1957]
succede che, a fronte di una comunicazione 5001 con tipoMutazione '2' (composizione scheda), inviata per aggiornare i legami di parentela in seguito ad emigrazione AIRE dell'intestatario, il nuovo intestatario  si vede recapitare le etichette dalla MCTC per aggiornare patente e carta di circolazione.

il cittadino in questione si reca in comune e chiede come mai gli siano arrivate le etichette pur non avendo cambiato indirizzo.

il cliente vorrebbe sapere se è normale che la MCTC si attivi in questo senso anche in assenza di cambio di indirizzo.

per verificare, potete prendere questi riferimenti:
ambiernte di PRODUZIONE
comune di VIGARANO MAINARDA (038022)
idOperazioneComune 2019003452

grazie.
Alessandro Monopoli ADS

**Comment by azabatta** [comment]
Buonasera, 
la  “Mutazione famiglia/convivenza”  -  tipo mutazione “composizione scheda “ (ws 5001 – codice 2) rientra tra gli eventi per i quali è prevista la notifica da ANPR verso  MCTC.  Le verifiche che possiamo effettuare in ANPR arrivano fino  al corretto invio delle notifiche.
I dettagli implementativi delle elaborazioni effettuate sui dati notificati possono esser verificati solo  con MCTC stessa.
Buona serata
