### ISSUE TITLE
chiarimento iscrizione di un cittadino non presente in anpr

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1958]
Buongiorno, in fase di test in ambiente di pre-subentro abbiamo cercato di far immigrare nel nostro comune un cittadino proveniente da un comune già subentrato. Purtroppo il cittadino non è presente in ANPR. Come procediamo in questi casi?

**Comment by frmariani** [comment]
non capisco bene la domanda: afferma che il cittadino proviene da un comune già subentrato però non è in ANPR... se il cittadino proviene da un comune già subentrato, deve essere presente in ANPR;
se il cittadino era presente in ANPR, quindi in un Comune subentrato, e poi è stato cancellato (ad esempio per irreperibilità), questi deve essere re-iscritto (WS 1002) indicando obbligatoriamente l'idanpr precedentemente assegnato.
Potrei essere più chiara se mi indicasse l'idanpr del cittadino che state cercando di immigrare nel vostro comune o l'idanpr dell'operazione fallita.

**Comment by carminepat** [comment]
Il cittadino proviene da altro comune subentrato ma non è presente in ANPR. Non ho alcun idAnpr per questa persona

**Comment by frmariani** [comment]
ma è una domanda retorica o possiede dei dati anagrafici reali ?
ha provato ad effettuare una consultazione ?
mi sembrava di aver capito che stesse effettuando un test;  mi spighi meglio questo test o mi scriva un recapito telefonico così ne parliamo
frmariani@sogei.it

**Comment by carminepat** [comment]
Risolto, considerando che l'altro comune avrà sicuramente fatto un pre-subentro parziale e quindi la persona considerata potrebbe non essere presente nell'ambiente di pre-subentro
