### ISSUE TITLE
Registrazione del domicilio digitale

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1959]
Buongiorno,
un cittadino ci chiede di registrare il suo indirizzo PEC, "al fine di poter usufruire dei servizi del così detto domicilio digitale, come da "anagrafe nazionale della popolazione residente". Come è possibile registrare tale dato in  Anpr?
Grazie e buon lavoro.

**Comment by rvinzani** [comment]
Non è ancora possibile registrare un indirizzo di PEC in ANPR. Attendiamo indicazioni dal Ministero dell'Interno.
