### ISSUE TITLE
[5008] Registrazione Matrimonio - assenza dati su WebApp

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#196]
Corbetta, Ambiente Produzione, ID Operazione ANPR 581614

Con l'operazione ANPR indicata è stato registrato con successo il matrimonio all'estero delle persone interessate, però nella WebApp non viene visualizzato il dato relativo all'atto di matrimonio anche se presente nella request e nella response.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
E' un problema nostro di visualizzazione. Se esegue ora l'interrogazione l'atto è presente.

**Comment by gcarbonin** [comment]
Il problema si è risolto?

**Comment by LucaBonini64** [comment]
Confermo che il problema si è risolto.
