### ISSUE TITLE
Consultazione cittadino in web app AE

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1960]
In fase di consultazione di cittadini nella web app nell'area "consultazione" --> "Consultazione AE" ricercando numerosi codici fiscali riceviamo il seguente errore: "Esito AE: Operazione non effettuabile (Codice 97)"

**Comment by frmariani** [comment]
per favore l'idanpr di un cittadino la cui consultazione è andata in errore

**Comment by carminepat** [comment]
L'id di un cittadino con cui ricevo questo errore: 220049321

**Comment by frmariani** [comment]
Lei sta operando in ambiente di pre-subentro (per favore lo specifichi sempre), dove non sono presenti i codici fiscali in Agenzia delle Entrate.

**Comment by carminepat** [comment]
Ok, perfetto, ha ragione, avevo omesso questa informazione
