### ISSUE TITLE
WS 5008 - Modifica idSchedaSoggettoComune 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1961]
COMUNE DI CAPONAGO

Invocazione WS5008 per cambio idSchedaSoggettoComune, idOperazioneANPR 210049572.

Dovendo modificare idSchedaSoggettoComune , invochiamo WS5008 con Tipo Mutazione = 07 , restituisce errore ES107 Indicare i dati relativi al titolo di studio, condizione professionale, ecc.  per tipoMutazione = 7.

Il tipo di mutazione non è corretto per poter modificare idSchedaSoggettoComune ?

**Comment by rvinzani** [comment]
Dovete utilizzare il tipo mutazione 1 perchè è un dato che fa parte delle generalità del soggetto
