### ISSUE TITLE
Iscrizione AIRE per espatrio

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1962]
Comune di Mantova, ambiente di produzione,
tentando di registrare in AIRE il soggetto con IdAnpr 18914009 riceviamo l'errore 
EN237 "La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata"   idOperazioneANPR 210070900

non ci risultano date che vanno in contrasto con la nuova decorrenza residenza, potete verificare?
Grazie

**Comment by frmariani** [comment]
c'è un po' di confusione:
l'idoperazioneANPR 210070900 non si riferisce al soggetto idanpr 18914009 ma al soggetto idanpr 34250370;
si richiede lo spostamento in una nuova famiglia (AttribuzioneFamigliaAire=2) ma nello stesso tempo si indica una famiglia Aire istituita il 06/02/2020 (motivo dell'errore).

**Comment by c-giacomini** [comment]
grazie
