### ISSUE TITLE
errori subentro

### ISSUE THREAD

**Issue by siacarini** [italia/anpr#1964]
Errore 1 - In fase di subentro in anpr, negli archivi era presente, per errore, una persona con due anagrafiche uguale. Come si può cancellare un scheda senza mantenere nessuno storico?
Errore 2 - In fase di subentro in anpr, un bambino è stato inserito in una famiglia diversa da quella corretta, facendo la modifica dal gestionale non corregge i dati in anpr, cosa fare?

**Comment by rvinzani** [comment]
Errore 1 - Deve cancellare la scheda richiamando il servizio : 2003 - cancellazione per altri motivi - motivo cancellazione "doppia iscrizione"
Errore 2 - deve cancellare il soggetto ed iscriverlo nuovamente (indicando l'idANPR già assegnato) alla stessa data di iscrizione inviata al momento del subentro
