### ISSUE TITLE
Modifica nome, cognome e codice fiscale

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1965]
Buongiorno, scrivo a seguito di risposta ricevuta al Ticket 20885084.
Abbiamo proceduto nella webapp con i passi indicati ma la mutazione non va a buon fine.
Si allegano screenshot (con i dati personali oscurati)  dei vari passaggi e gli errori finali.

[errore in anpr.docx](https://github.com/italia/anpr/files/4230220/errore.in.anpr.docx)

Grazie per l'attenzione,
cordiali saluti.

**Comment by rvinzani** [comment]
Ho provato a chiamarla senza successo.
Ho bisogno di maggiori informazioni

**Comment by katiavacchi** [comment]
Ok,  ci sono. Tengo il telefono a portata. 0544 482272

**Comment by rvinzani** [comment]
Problema risolto
