### ISSUE TITLE
[5012] - Errore EN234

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1966]
Comune di Torino - Ambiente di PRODUZIONE

Buongiorno,
si sta tentando di annullare l'operazione 198992606 (servizio 5008), ma il sistema restituisce l'errore 

```
<errore>
                <codiceErroreAnomalia>EN234</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione.</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-20 15:16:27 , idOperazioneANPR 211255553</testoErroreAnomalia>
```
Non riusciamo a capire quale sia il dato modificato che sta impedendo l'annullamento della mutazione 5008. Effettuando una visura del soggetto su Web App pre e post iscrizione a Torino non notiamo differenze.

Potreste aiutarci ad identificare il problema?

Grazie,
Chiara Leanza

**Comment by asqueglia** [comment]
Buongiorno, da una verifica effettuata sui nostri sistemi, abbiamo riscontrato che in data 20-2-2020 alle ore 14:54 avete effettuato l'annullamento della mutazione anagrafica indicata con esito positivo. Se provate a  consultare il soggetto potete voi stessi verificare nell'elenco operazioni, l' operazione di annullamento 211235375 andata a buon fine. 
Per problemi specifici, come quello da voi indicato, è bene utilizzare il servizio di assistenza ANPR al numero 800863116 anche per evitare di condividere dati e informazioni anagrafiche.

**Comment by CSI-Piemonte-Demografia** [comment]
L'operazione 211235375 ha annullato l'operazione 198993966 e non la 198992606 che è quella che stiamo cercando di annullare sia lato applicativo sia lato WebApp.
Inoltre quali dati anagrafici avrei condiviso? Ci sono moltre altre segnalazioni come questa su github e non ho inserito nessun riferimento relativo al soggetto.

**Comment by asqueglia** [comment]
Si ha ragione ho confuso l'id dell'operazione annullata correttamente con quella indicata; mi scusi per il disguido. 
L'annullamento non è stato consentito per un problema sul nome comune nascita del soggetto che risultava diverso rispetto a quello trasmesso dal comune precedente, abbiamo sanato da centro il problema. Potete riprovare ?

**Comment by CSI-Piemonte-Demografia** [comment]
Il Comune ha riprovato e la pratica è stata revocata correttamente. 

La ringrazio per la collaborazione.
Chiara Leanza
