### ISSUE TITLE
[1002] EN531 procedimento aperto

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1967]
Buongiorno per il comune di Colli al Metauro ambiente produzione
inviando una 1002 segnala EN531 per un procedimento aperto
idOperazioneANPR 211662158

abbiamo cercato i procedimenti della persona ma ne risulta solo uno 
Numero procedimento assegnato da ANPR: 22082277
correttamente chiuso a novembre 2019.

cosa possiamo controllare?

grazie mille
Riccardo

**Comment by frmariani** [comment]
Per il cittadino risultano due procedimenti ancora aperti dal Comune di Senigallia;
cercherò di contattare il comune e Le farò sapere.

**Comment by frmariani** [comment]
può riprovare l'operazione

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
