### ISSUE TITLE
Annullamento mutazione residenza antecedente mutazione scheda

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#1968]
Buongiorno,
si chiede la corretta procedura per risolvere il seguente quesito:
Cittadino A immigra da comune subentrato e, quindi, in ANPR viene registrata una Mutazione di Residenza (oppure di Famiglia) nella fase di iscrizione preliminare. Durante la fase di accertamenti, al cittadino A viene effettuata una Mutazione Scheda (che può essere, ad esempio, l'aggiornamento dell'iscrizione delle liste elettorali, oppure la correzione dell'atto di nascita..). 
Successivamente alla Mutazione Scheda, gli accertamenti sono negativi e la Mutazione di Residenza è da annullare: attualmente non è possibile annullare la Mutazione di Residenza in quanto vi è una Mutazione Scheda con data decorrenza successiva.
Che io sappia, l'unico modo per risolvere la cosa è "andare a ritroso", annullando prima la Mutazione Scheda e successivamente la Mutazione di Residenza. Però con questa operazione perderei in ANPR un dato corretto (effettuato con la Mutazione Scheda).
Resto a disposizione per ogni ulteriore chiarimento
grazie

**Comment by rvinzani** [comment]
E' possibile annullare una mutazione di residenza (specificando per ripristino posizione anagrafica) anche in presenza di ulteriori mutazioni (non di residenza). Se avesse riscontrato difficoltà nell'effettuare tale operazione dovrebbe indicarci l'idOperazione ANPR per poter analizzare il problema
