### ISSUE TITLE
iscrizione per immigrazione da stato estero

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1969]
Buongiorno,
in ambiente di pre-subentro del comune di Potenza (cod-istat: 076063),
stiamo effettuando un'iscrizione dall'estero (ws 1002) specificando l'attribuzione di un nuovo codicefiscale (<gestioneCF>1</gestioneCF>) (idOperazioneANPR: 16583329) otteniamo un errore con codice: "AEE95 operazione non effettuabile". Che errore stiamo commettendo? Come dovremmo effettuare l'invocazione in questi casi?

**Comment by frmariani** [comment]
E' un disservizio di Agenzia delle Entrate determinato dagli aggiornamenti pianificati per il we come da issue  #1944

**Comment by carminepat** [comment]
ma quindi la nostra richiesta è ben formata?

**Comment by frmariani** [comment]
mi sembra di si

**Comment by carminepat** [comment]
ok, grazie, quindi riproveremo al termine della manutenzione (#1944)
