### ISSUE TITLE
ws [3003] - Consultazione notifiche avvenuto subentro comuni

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#197]
Stiamo effettuando dei test per acquisire l'avvenuto subentro di un comune. 
Il caso di utilizzo, come da documentazione, è la determinazione del servizio da richiamare in occasione dei trasferimenti di residenza nella fase "ibrida"; lo scenario è quello di "acquisizione da parte del comune che non espone il ws", che pertanto prevede l'utilizzo del ws 3003, specificando nella request "N031" come codice servizio del tipo di notifica da consultare; 
Negli ultimi test effettuati (ad es. l'id operazione comune 1673), otteniamo nella response una sola occorrenza del blocco "elencoRisposte", con il campo "xmlRisposta" che contiene il file xml relativo alla notifica di subentro del comune di Montalto Pavese; nei test effettuati nei giorni precedenti, però, abbiamo ottenuto nella response un numero elevato di elementi, tant'è vero che (in accordo alla documentazione) era necessario indicare nella request un periodo temporale limitato, per non causare l'errore "EN115 - La richiesta  ha individuato un numero di occorrenze troppo elevato: restringere i parametri della ricerca".
Questa situazione presumibilmente si verificherà nella fase "ibrida", quando i comuni subentrati raggiungeranno l'ordine delle centinaia. 
L'acquisizione dell'avvenuto subentro di un determinato comune in questo scenario, se abbiamo inteso la logica di utilizzo, può risultare particolarmente laboriosa, in quanto può richiedere un numero non determinabile di chiamate al ws, indicando "a ritroso" intervalli temporali diversi, fino all'individuazione del comune di interesse, o al raggiungimento della data di inizio subentri.
Non sarebbe possibile, da parte vostra, modificare il ws 3003 in modo, ad esempio, da inserire nella request un campo in cui indicare il comune da ricercare, e da restituire nella response il blocco "elencoRisposte" solo in caso di avvenuto subentro del comune? 
Il test è stato effettuato in data 01/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Stiamo valutando di modificare il servizio 7001 aggiungendo un valore (elenco comuni subentrati dal).
