### ISSUE TITLE
EC036 codice cittadinanza 998 inesistente

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#1970]
Buongiorno, il Comune di PAULLO in PRODUZIONE vuole aggiornare i dati del coniuge di una cittadina AIRE, il problema è che non sa la cittadinanza del coniuge quindi inviando la mutazione 5008 ha l'errore in oggetto.

id operazione 211934993

come risolvere?
Grazie mille
Riccardo

**Comment by rvinzani** [comment]
E' possibile aggiornare i dati del coniuge senza indicare necessariamente i dati della cittadinanza ma qualora fossero presenti non è possibile indicare nella descrizione dello stato NON ATTRIBUIBILE. E' invece possibile, qualora lo stato non fosse presente nella tabella stati di ANPR indicare il codice 998 e la descrizione dello stato.
Si chiude la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
