### ISSUE TITLE
[5005] da Convivenza a Convivenza - Errore EN237

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#1971]
ambiente di PRODUZIONE - comune di FAENZA (039010)

comunicazione di tipo 5005 (idOperazioneComune 2020002457) 
con cui si tenta di spostare 8 soggetti dalla convivenza con idFamigliaANPR 10183110 alla convivenza con idFagmigliaANPR 47993927

il web-service ritorna questi errori:
```
<errore>
  <codiceErroreAnomalia>EN237</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata</testoErroreAnomalia>
</errore>
<errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-02-21 11:23:54 , idOperazioneANPR 211834008</testoErroreAnomalia>
</errore>
```

non si capisce cosa blocchi la variazione, xchè non ci risultano operazioni successive al 17/2/2020 (data di decorrenza dello spostamento) in nessuno dei componenti interessati (compresi i soggetti rimanenti nella vecchia famiglia).

potete aiutarci a capire?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
La nuova convivenza è stata costituita il 18 Febbraio 2020, quindi non possono essere aggiunti dei membri in data antecedente

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
