### ISSUE TITLE
Collegamento codici fiscali con 4 campi da variare

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1972]
Buongiorno,
dobbiamo collegare due codici fiscali poiché la persona interessata ha variato nome, cognome e data di nascita. Ha già il codice fiscale corrispondente ai nuovi dati, rilasciato dalla Questura e già presente in AE.
Il collegamento però non riesce perché  i campi da modificare risultano 4 (nome, cognome, data di nascita e codice fiscale). L'errore da webapp è il seguente: "Esito AE: Variazione non consentita per superamento numero campi variati (Codice 93)".
Come possiamo procedere?
Grazie.
[etiopia.pdf](https://github.com/italia/anpr/files/4235905/etiopia.pdf)

**Comment by frmariani** [comment]
Deve scrivere alla Direzione Centrale di Agenzia delle Entrate allegando la documentazione in suo possesso che giustifichi il collegamento ed indicando il seguente  numero di Ticket dell'Assistenza ANPR (rilasciato appositamente per il suo caso) :  21143730
entrate.archivioanagrafico@agenziaentrate.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
