### ISSUE TITLE
Ripristino residenza

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1974]
Il comune di Domodossola deve ripristinare la residenza di un cittadino, ma viene restituito l'errore bloccante: EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto
data 2020-02-24 09:31:29 , idOperazioneANPR 212604686

**Comment by frmariani** [comment]
per il cittadino risulta un procedimento aperto del comune di Reggio di Calabria;

**Comment by siscomanpr** [comment]
Segnaliamo al comune di Domodossola di mettersi in contatto con il comune di Reggio di Calabria per la chiusura del procedimento e poter procedere con il ripristino della residenza.

**Comment by frmariani** [comment]
in questo caso, per il ripristino della residenza del cittadino, il comune di Reggio di Calabria non avrebbe dovuto cancellare il cittadino ma annullare l'operazione di mutazione di residenza per "Ripristino posizione anagrafica": in questo modo il cittadino sarebbe tornato automaticamente residente nel comune di Domodossola.
