### ISSUE TITLE
[5008] - Anomalia su mutazione scheda - atto di nascita

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#1975]
Comune di Torino - Ambiente di PRODUZIONE

Buongiorno,
in riferimento alle issue chiuse #1939 e #1950 abbiamo un altro caso analogo. 
Soggetto 64797023
Operazione 213697933
Sono stati inviati i dati relativi all'atto di nascita del soggetto con tipo mutazione 20 e la risposta è stata positiva con WN. Per quale motivo i dati non sono stati aggiornati? Le altre mutazioni hanno aggiornato i dati, infatti solo l'atto di nascita risulta non presente.

Grazie, cordialmente
Chiara Leanza

**Comment by frmariani** [comment]
Le operazioni con id 213697933 e 213697934 di completamento relative al soggetto 64797023 sono state invocate alla stessa ora, minuti e secondi, senza verificare  che la prima fosse finita e con quale esito; 
Si ribadisce che l’orchestramento delle operazioni su uno stesso soggetto spetta all’applicativo comunale.

**Comment by CSI-Piemonte-Demografia** [comment]
Ok vi ringraziamo per la verifica.

Buon lavoro,
Chiara Leanza
