### ISSUE TITLE
Da codice fiscale numerico ad alfanumerico

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#1976]
Buongiorno,
abbiamo iscritto in anagrafe una cittadina albanese con codice fiscale numerico. Successivamente abbiamo provato ad attribuirle l'alfanumerico d'ufficio ma la webapp ANPR restituisce l'errore allegato.
Come possiamo procedere?
[errorenumerico.pdf](https://github.com/italia/anpr/files/4250837/errorenumerico.pdf)

Grazie per l'attenzione,
cordiali saluti.

**Comment by rvinzani** [comment]
L'alfanumerico che avete cercato di inserire al posto del provvisorio non sembra essere presente in Agenzia Entrate. In ogni caso, avete anche indicato nella gestione del codice fiscale - inserisci/modifica senza la validazione di AE. Questa operazione non può essere effettuata per soggetti già validati. Nel campo gestione codice fiscale non dovete inserire nessun valore

**Comment by katiavacchi** [comment]
Buongiorno,
anche seguendo le sue istruzioni (e lasciando il campo bianco) non riusciamo ad attribuire l'alfanumerico. Il problema nasce perchè la Questura gli ha impropriamente attribuito un numerico e l'Agenzia delle entrate non gli assegna l'alfanumerico rimandando il cittadino a noi.
Grazie e cordiali saluti.

**Comment by rvinzani** [comment]
Purtroppo ANPR non dispone delle funzioni per attribuire un CF definitivo
