### ISSUE TITLE
OPERAZIONI DI ALTRI COMUNI

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1977]
Buongiorno,
fino ad un paio di settimane fa circa, era possibile in consultazione - elenco operazioni, visualizzare sui singoli soggetti, anche le operazioni effettuate da altri comuni.
Ad oggi non sono più presenti.
E' possibile fare in modo che vengano visualizzate nuovamente? Era molto utile per capire come risolvere eventuali problemi sulle schede.
Cordiali Saluti
Floramo S.
UpiTorino

**Comment by frmariani** [comment]
non ci risulta che sia mai stato possibile visualizzare le operazioni effettuate da altri comuni sui singoli soggetti; 
mi dispiace ma non possiamo prendere in considerazione la richiesta.

**Comment by UpiTorino** [comment]
Buongiorno,
allego una stampa delle operazioni del soggetto ID ANPR 35595091, effettuata in data 23.12.2019.
Il soggetto si iscrive a Torino provenendo da comune subentrato Beinasco il 20.12.2019 (mutazione residenza id operazione 173428558); come è riportato nella stampa, è presente anche l'operazione ID 112100421 - mutazione fam/conv - eseguita in data 12.08.2019 dal comune di precedente iscrizione ma leggibile anche dal comune di Torino.
 
[Operazioni beinasco.docx](https://github.com/italia/anpr/files/4254988/Operazioni.beinasco.docx)

Floramo S.
UpiTorino

**Comment by frmariani** [comment]
le operazioni sono visibili perchè il cittadino è un vostro residente; oggi non vedete più l'operazione 112100421 ?

**Comment by UpiTorino** [comment]
Ora non è più leggibile nonostante il cittadino sia nostro residente.

**Comment by frmariani** [comment]
per favore l'idoperazione della consultazione del cittadino in cui si evinca che non è più presente l'operazione.
grazie

**Comment by UpiTorino** [comment]
ID OPERAZIONE 215171445

**Comment by frmariani** [comment]
purtroppo non basta l'idoperazione, dovresti allegare l'elenco

**Comment by UpiTorino** [comment]
Allego il file con l'elenco
[Operazioni.docx](https://github.com/italia/anpr/files/4256047/Operazioni.docx)

**Comment by frmariani** [comment]
la seconda richiesta, viene effettuata a livello comunale e non nazionale;
riprova per favore ad effettuare la ricerca del cittadino a livello nazionale

**Comment by UpiTorino** [comment]
Anche effettuando la ricerca a livello nazionale la situazione è la medesima.

[Operazioni naz.docx](https://github.com/italia/anpr/files/4256208/Operazioni.naz.docx)

**Comment by frmariani** [comment]
per favore puoi effettuare la consultazione di un altro cittadino e verificare se hai lo stesso problema ?

**Comment by frmariani** [comment]
Ritengo che il numero delle operazioni effettuate sul cittadino abbiano compromesso la corretta visualizzazione delle operazioni eseguite.
la issue viene chiusa, nel caso possiamo continuare la conversazione privatamente
