### ISSUE TITLE
Correzione data iscrizione AIRE

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1978]
Buongiorno,
ambiente di produzione.

Il Comune in questione ha iscritto all'Aire, per acquisizione cittadinanza, l'individuo con ID ANPR 86080363. In un primo momento l'iscrizione è stata fatta alla data del 06/02/2020 (data della trascrizione dell'atto di nascita) ma dopo ulteriori verifiche da parte del Comune si è reso necessario correggere questa data e anticiparla alla data del 23/04/2014 (data presente sul decreto).

L'operazione con cui è stata tentata questa correzione ha id operazione 205433877, ma restituisce come errore: 
"Data decorrenza residenza 23-04-2014 minore della data di prima iscrizione del soggetto"

Il Comune ha quindi contattato l'assistenza di primo livello che ha risposto che non si occupano di questi casi e che deve essere la software house, su questo canale, ad aprire specifica issue per la risoluzione del problema.

Come deve procedere il Comune per la correzione di questa data?
Ringraziando anticipatamente 
Saluti

**Comment by frmariani** [comment]
Il cittadino è stato aggiunto in ANPR con un'iscrizione per altri motivi AIRE, pertanto la data di decorrenza della residenza e la data di iscrizione nel comune sono uguali e non rettificabili: la rettifica delle date, è possibile soltanto nel caso di cittadino aggiunto in ANPR con il subentro del comune;
nel vostro caso, l'unica azione possibile è l'annullamento delle operazioni nel seguente ordine:
idoperazione anpr 207171392  Mutazione scheda;
idoperazione anpr 201893092 Iscrizione per altri motivi AIRE.
soltanto dopo potrete effettuare una nuova Iscrizione per altri motivi Aire con le date corrette.

**Comment by frmariani** [comment]
Stiamo cercando di fornire un servizio di assistenza ANPR sempre più veloce ed efficace;
in questi casi il call center di primo livello avrebbe dovuto passare la chiamata al personale specialistico per una pronta risoluzione della problematica;
gentilmente,  fornite il giorno e l'ora (approssimativamente) in cui il Comune ha contattato il nostro numero verde: sarà nostra cura specificare meglio ai nostri colleghi la problematica in questione.

**Comment by SAlberto** [comment]
Buongiorno,
grazie per la tempestiva risposta.
Abbiamo agito come da voi indicato e la persona in questione risulta adesso essere iscritta correttamente. 
Purtroppo casi come questo, in cui un Comune sbaglia la data di iscrizione di un soggetto loro residente sono numerosi: sarebbe possibile implementare una soluzione più veloce per questa casistica?

Riguardo alla vostra domanda, Il Comune ci dice aver chiamato questa mattina 26/02 intorno alle 09.40 - 09.45. 

Grazie,
   Saluti

**Comment by frmariani** [comment]
non è possibile implementare una soluzione più veloce perchè la coerenza delle date è una condizione imprescindibile nel sistema ANPR; 
Nel sistema ANPR si preferisce sempre annullare un'operazione non corretta che modificare il dato con la possibile incongruenza delle date.
grazie anche per la segnalazione del call center.
