### ISSUE TITLE
[5008] - WS - Disconoscimento paternità

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#198]
01/06/2017 - Comune di Anzola dell'Emilia - Datagraph - Ambiente di Subentro.
Abbiamo un caso di disconoscimento di paternità per cui i dati di paternità associati al cittadino vanno cancellati perché non più validi. Inviando una Mutazione di paternità con Cognome e Nome vuoti, prevedibilmente, il sistema ANPR risponde con errore:

>     <errore>
>         <codiceErroreAnomalia>ES044</codiceErroreAnomalia>
>         <tipoErroreAnomalia>E</tipoErroreAnomalia>
>         <testoErroreAnomalia>Indicare almeno il cognome o il nome del genitore</testoErroreAnomalia>
>       </errore>

Come bisogna procedere? Sottolineo che si tratta di un caso reale.

Grazie.

Alessio Tropeano

**Comment by gcarbonin** [comment]
Questa operazione non è tra quelle previste attualmente. procediamo immediatamente con l'evoluzione.

**Comment by psaggini** [comment]
Buongiorno,
quali tempi prevedete per il rilascio?

Grazie e a presto
Patrizia Saggini

**Comment by gcarbonin** [comment]
Le ultime specifiche pubblicate contengono il servizio da utilizzare in caso di disconoscimento (5013 Revoca dato). Da lunedì è possibile iniziare i test. Attendiamo il vostro riscontro.

**Comment by psaggini** [comment]
Grazie delle info, possiamo procedere con i test a partire dal 25/7; vi terremo aggiornati sui risultati.

**Comment by gcarbonin** [comment]
I test si sono conclusi La nuova versione sarà disponibile anche in ambiente di produzione da prossimo martedì 8 agosto
