### ISSUE TITLE
EN531 Procedimento aperto

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#1980]
Buongiorno Sono Nozzoli del CED Comune di Prato in ambiente di produzione.
Inviando una immigrazione riceviamo l'errore EN531 per procecimento aperto
idOperazione ANPR 207218297
Non abbiano noi procedimenti aperti per questo soggetto. 
E' il nuovo errore di blocco quando un'altro comune ha in carico il soggetto?
Possiamo noi in autonomia trovare il comune che ha dei procedimenti aperti a carico del cittadino?
Grazie mille
Arianna  nozzoli

**Comment by rvinzani** [comment]
Di solito è il comune di provenienza che ha un procedimento aperto a carico del cittadino;
il procedimento dovrebbe essere chiuso con la definizione positiva o negativa della pratica di immigrazione, ma purtroppo non sempre viene effettuata la corretta procedura.
Il comune di Cerro Maggiore deve chiudere un procedimento ancora aperto a carico del cittadino:
procedimento idanpr 23354439 (numero comunale del procedimento 10576) aperto il 12/02/2020;

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
