### ISSUE TITLE
EN071 la data di nascita del soggetto estratto non è congruente con quello passato come parametro di ricerca

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#1981]
Salve vi segnalo che mentre sto effettuando la consultazione di un cittadino (identificativo scheda anpr: 213720556), con ws 3002 (comune codice istat: 076063) in ambiente di pre-subentro (idOperazioneANPR=16605891) otteniamo un errore EN071: "la data di nascita del soggetto estratto non è congruente con quello passato come parametro di ricerca". Perchè riceviamo questo errore? Consultando la web-app e l'xml che noi costruiamo per la richiesta della consultazione la data di nascita a noi risulta uguale

**Comment by frmariani** [comment]
nell'xml dovreste eliminare il timezone nella data di nascita; procedete e fatemi sapere

**Comment by carminepat** [comment]
Grazie, provvediamo ad eliminare questa informazione dal formato della data nell'xml sia di subentro, che della richiasta
