### ISSUE TITLE
Problemi con codice fiscale (errore bloccante in fase di iscrizione aire)

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1982]
Buongiorno,
ambiente di produzione.

Un Comune che seguiamo sta tentando di iscrivere un suo residente (ID_ANPR 85356357) all'Aire ma la persona non viene trovata in ANPR con il codice fiscale comunicato in fase di subentro (che era anche confermato dall'Agenzia delle Entrate).
Se cerchiamo la persona dal portale per cognome e nome questa risulta residente nel Comune stesso ma con codice fiscale differente.
Sull'individuo il Comune non ha fatto operazioni successive al subentro, né da web service né da portale (come si vede anche dall’elenco operazioni sul portale) e non ha ricevuto comunicazioni riguardanti la modifica del codice fiscale.
Il Comune deve procedere velocemente all'iscrizione all'aire del cittadino per farlo votare all'estero per il Referendum del 29/03/2020 ma, prima di rettificare il codice fiscale, vuole sapere perché il Codice fiscale è cambiato.

Ringraziando anticipatamente
Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
il CF trasmesso al subentro è la base di un caso di omocodia con un altro cittadino, risolto da Agenzia delle Entrate. Quando vengono validati su Agenzia delle Entrate i CF al subentro, in casi come questo il CF viene aggiornato con quello che risolve l'omocodia. Tale CF è quello visualizzato in ANPR.

N. Capozzi
