### ISSUE TITLE
FUnzione attribuzione omocodice

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1984]
Buongiorno,
sino alla scorsa settimana la funzione "richiesta attribuzione omocodice" sembrava non avere efficacia al fine dell'effettiva attribuzione.
E' cambiato qualcosa con l'aggiornamento di Agenzia Entrate dello scorso fine settimana od occorre continuare a inoltrare richiesta a 
entrate.archivioanagrafico@agenziaentrate.it
allegando idonea documentazione a supporto?
Grazie
Anna Maria AIMONE
Responsabile UPI - CODICI FISCALI 
Comune di TORINO

**Comment by rvinzani** [comment]
Il servizio di agenzia entrate per l'attribuzione di un omocodice può essere richiesto in fase di iscrizione di un soggetto o in fase di mutazione dei dati anagrafici. Se tale mutazione dà origine ad un CF già presente, è possibile in tale sede, verificato che si tratta di due soggetti differenti, richiedere l'attribuzione di un codice fiscale omocodice. Per tutte le altre casistiche è necessario che il cittadino (o il comune per il cittadino) si rivolga all'**Agenzia Entrate territoriale**  che a sua volta invierà la pratica alla Direzione centrale per la risoluzione dell'omocodia.
L'utilizzo della casella entrate.archivioanagrafico@agenziaentrate.it è raccomandato in alcuni casi che non possono essere risolti da ANPR o dall'ufficio territoriale come ad esempio la mutazione di più di tre dati anagrafici, il collegamento di due CF che differiscano di più di tre dati, lo scollegamento di due CF effettuato per errore, la mutazione di un CF marcato omocodice
