### ISSUE TITLE
Problemi con codice fiscale (errore bloccante in fase di iscrizione aire) - parte 2

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1985]
#1982 
Buongiorno, 
in riferimento alla issue citata: al Comune non è arrivata nessuna comunicazione sull'allineamento del codice fiscale.
Dove possono trovare un elenco per controllare situazioni di questo genere?
Grazie mille.

**Comment by ncapozzi** [comment]
Il Comune non riceve una notifica ma il caso è tra quelli segnalati nell'elenco anomalie da subentro 017009CFDiversoAssenteDatiDiversiCollegatiOmocodici20200121.csv
