### ISSUE TITLE
Richiesta riapertura procedimento su webapp

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#1987]
Buongiorno,

in data 18/02/2020, tramite la funzione "Gestione procedimento/istruttoria", è stato erroneamente chiuso il procedimento B202000026362 (identificativo procedimento assegnato dal comune) / 23277615 (identificativo procedimento assegnato da ANPR) per il soggetto con id 61041424.
Si richiede di riaprire il procedimento altrimenti non saremo in grado di definire la pratica su gestionale.
Ho anche provato ad aprire la segnalazione tramite call center ma la collaboratrice non ha ben compreso la richiesta, indicandomi di procedere da "Utilità e Notifiche" e "Operazioni sospese".
Il procedimento che si richiede di riaprire è relativo ad una mutazione residenza (voce non ricompresa nell'elenco delle operazioni sospese dalla funzione utilità).
Grazie.
Coridali saluti.

Falciglia C. (UpiTorino)

**Comment by rvinzani** [comment]
Attualmente non è possibile riaprire un procedimento già chiuso

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno,
possiamo sapere il motivo per il quale non è più possibile questo trattamento dati? 
In questo modo gli operatori non sono in grado di definire o di revocare delle pratiche di immigrazione. Infatti la nostra procedura, in fase de definizione pratica, invia la chiusura del procedimento come da prassi. Avendo già chiuso il procedimento da WebApp questo risponde KO con il motivo che il 1014 è già stato chiuso. 
Grazie,
Chiara Leanza

**Comment by rvinzani** [comment]
Non è mai stato possibile. Se si è trattato di un errore dovete scrivere alla nostra casella PEC chiedendo la riapertura del procedimento

**Comment by CSI-Piemonte-Demografia** [comment]
Ah ok perfetto, grazie mille.

Chiara Leanza

**Comment by rvinzani** [comment]
Il procedimento è stato riaperto.
Seganalo comunque che la chiusura del procedimento determina l'impostazione della data di perfezionamento dell'operazione. Tale data viene utilizzata come riferimento nella produzione dei prospetti mensili. Riaprendo il procedimento la data di perfezionamento è stata eliminata e se verrà chiuso ad una data diversa questo potrebbe creare un disallineamento nel prospetto già prodotto
