### ISSUE TITLE
Mutazione dati anagrafici che impedisce annullamento residenza

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#1988]
Buongiorno,
ambiente di produzione.

Il Comune ha iscritto tra i suoi residenti l'anagrafica con ID ANPR 45969208, proveniente da un Comune già subentrato.
In seguito ad accertamenti si rende necessario annullare questa iscrizione e riportare il soggetto nel Comune di precedente iscrizione, operazione che attualmente viene impedita dalla presenza di una  mutazione dati anagrafici successiva alla mutazione di residenza e che il sistema non ci permette di cancellare.
Tentando dal portale di annullare questa comunicazione, con l'operazione 218296701 ci viene restituito come come errore: 
"Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione. (Codice: EN234)"

Il Comune ha già contattato l'assistenza telefonica che ha riferito al Comune di chiedere a noi di scrivere su questo forum.
Come possiamo procedere all'annullamento della mutazione di residenza in modo da riportare l'anagrafica nel precedente comune di iscrizione?
Ringraziando anticipatamente,
cordiali saluti

**Comment by rvinzani** [comment]
E' possibile effettuare un annullamento per ripristino posizione anagrafica dell'operazione di mutazione di residenza senza necessariamente dover annullare le operazioni successive. Attendiamo informazioni sull'esito

**Comment by SAlberto** [comment]
Buongiorno,
grazie per la risposta.
Oggi pomeriggio il Comune è chiuso. Tenteremo l'operazione di annullamento domani mattina e vi daremo aggiornamenti.

Cordiali saluti

**Comment by SAlberto** [comment]
Buongiorno,
siamo riusciti a ripristinare la situazione così come da voi suggerito.

Grazie per l'aiuto.
Saluti
