### ISSUE TITLE
ANNULLAMENTO MUTAZIONE

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#1989]
Persona con ID ANPR: 30195987
A seguito di accertamenti negativi si è proceduto al ripristino della precedente posizione anagrafica. 
Operando tramite la ns. sw house (Halley informatica) non è stato possibile aggiornare ANPR (viene segnalato l'errore: 
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa
Si è quindi provato direttamente dalla web app ANPR ad annullare tutte le mutazioni, e per ultima quella dell'iscrizione anagrafica,idOperazioneANPR 218702899 e anche qui con lo stesso esito:
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077) 
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-02 14:06:42 .
Si ripete che le operazioni-mutazioni precedenti sono già state tutte annullate....
Si chiede come procedere.
Grazie!

**Comment by ncapozzi** [comment]
Buonasera,
nella stessa famiglia del soggetto interessato il 20/11/2019 è stato iscritto anche il soggetto con id ANPR 77167170 successivamente cancellato con la stessa data di decorrenza. Sembrerebbe che in realtà l'iscrizione dovesse essere annullata. Se è così è necessario prima procedere all'annullamento della cancellazione, poi dell'iscrizione dell'id ANPR 77167170, ed infine annullare la mutazione famiglia/convivenza id 155661272

N. Capozzi
