### ISSUE TITLE
Tabella 43 - cessazione unione civile convivenza

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#199]
Buongiorno,
nella tabella 43 (cessazione unione civile convivenza) non troviamo una codifica da utilizzare nel caso la convivenza di fatto venga sciolta a seguito degli accertamenti negativi da parte dell'ente sia legati alla richiesta di residenza che alla richiesta di creazione della convivenza di fatto.
Eventualmente potremmo fare l'annullamento dell'operazione di creazione, però rischiamo di non poterla eseguire a seguito di altre operazioni avvenute successivamente alla creazione della convivenza di fatto.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Ho posto il quesito al Ministero dell'Interno.

**Comment by gcarbonin** [comment]
chiusa in quanto lo stesso argomento è trattato nella issue #710
