### ISSUE TITLE
Richiesta chiarimento Mutazione Residenza APR

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#1991]
Buongiorno dal Comune di Ortona,

il comune di PRATOLA PELIGNA (AQ) ci richiede la cancellazione da ANPR delle cittadine codice individuo ANPR 74862272 e 74862266

Essendo le due cittadini presenti in ANPR una sola volta correttamente residenti in Ortona abbiamo indicato a Pratola Peligna di effettuare un'operazione di Mutazione Residenza.

Tuttavia il comune ci risponde di essere impossibilitato, potete verificare con loro se sono necessarie operazioni da parte nostra?

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by rvinzani** [comment]
Abbiamo dato indicazioni al comune sulle modalità di operare su ANPR. Voi dovete solo attendere la notifica di mutazione di residenza per poter cancellare i soggetti localmente
