### ISSUE TITLE
[6001] identificare un residente per test certificazioni

### ISSUE THREAD

**Issue by nardil** [italia/anpr#1992]
Buongiorno,

stiamo provando i servizi di certificazione in ambiente di **test-comuni** (**Novara, 003106**), ma non riusciamo ad individuare un residente in anagrafica tra quelli che dovrebbero essere stati concordati al tempo dell'accreditamento.
Abbiamo provato tramite la console sia a cercare a campione tramite codice fiscale che ad estrarre l'elenco dei cittadini, ma nel primo caso riscontriamo l'errore di cittadino non trovato, mentre nel secondo l'operazione non termina (avviata ieri e ad oggi nessuna risposta).

Come possiamo procedere?

**Comment by ncapozzi** [comment]
Buonasera,
in test-comuni non risulta essere presente alcun cittadino per il Comune di Novara, ne risultano prove di subentro.

Potete provare ad inviare i file di subentro in test-comuni.

N. Capozzi
