### ISSUE TITLE
Rettifica campo Tipo Famiglia AIRE

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#1994]
Comune di Cumiana (TO) - Ambiente di produzione

Buongiorno, il comune di Cumiana ci segnala un'anomalia su una famiglia AIRE.
La famiglia in questione ha il codice ANPR 42801661 ed è intestata al soggetto con codice ANPR 75508617.
Il problema è che i soggetti sono correttamente indicati come Soggetto AIRE : SI
Invece la famiglia è indicata come Famiglia AIRE: NO
La cosa strana è che al momento del subentro del comune di Cumiana avvenuto a novembre 2019, questi cittadini erano già AIRE per cui sono stati popolati tramite li solito file generato tramite AnagAire e a detta dell'impiegato comunale non sono state più movimentate.
L'anomalia è stata rilevata perché un altro comune sta cercando di iscrivere queste persone ma l'operazione viene bloccata a causa di questa anomlia.
Tramite la web app non siamo riusciti a modificare questo campo. 
Che soluzione possiamo adottare per risolvere il problema?

**Comment by ncapozzi** [comment]
Buonasera,
sulla famiglia interessata erano state eseguite due mutazioni 5001
199874635 per rimpatrio, annullata da 202552365
199874703 da annullare
Provate ad annullare la seconda, poi verifichiamo di nuovo.

N. Capozzi

**Comment by siscomanpr** [comment]
Abbiamo verificato ma le operazioni di cui mi ha scritto non sono visibili sul cittadino.
Vediamo altre 2 mutazioni che sono delle variazioni di stato civile (matrimonio e divorzio). Allego screenshot.
![Cattura](https://user-images.githubusercontent.com/28776141/75969903-e5828980-5ecf-11ea-92ad-355ebb971272.PNG)

**Comment by ncapozzi** [comment]
Quella annullata è visibile in consultazione (la form riportata non mi sembra completa), mentre quella da annullare è un 5001 con tipo operazione = 3 - DATI GENERALI FAMIGLIA CONVIVENZA. Non è prevista la visualizzazione nell'elenco operazioni per questa tipologia.

**Comment by siscomanpr** [comment]
L'elenco che ho allegato è completo. Non sono visibili altre operazioni. 
Proveremo ad annullare allora l'operazione 199874703 anche se non visibile e farò sapere.

**Comment by ncapozzi** [comment]
Da ulteriori verifiche risulta che le operazioni 199874635 per rimpatrio, annullata da 202552365 e 199874703 da annullare, sono state eseguite dal Comune di Voghera diverso da quello di attuale iscrizione AIRE che è Cumiana. Per questo non vedete le prime due. Probabilmente non vi farà neanche annullare 199874703 ma sarà necessario contattare Voghera perché proceda in tal senso

**Comment by siscomanpr** [comment]
Riferisco, grazie per il supporto.
