### ISSUE TITLE
[1002] errore in iscrizione per ricomparsa

### ISSUE THREAD

**Issue by busaster** [italia/anpr#1995]
Ambiente di produzione, comune di Cittanova

Tentando di iscrivere un cittadino per ricomparsa veniamo fermati dall'errore "EN185 : idSchedaSoggettoANPR 19893255 non presente o dati anagrafici incongruenti" (id operazione ANPR 220235580).
Il cittadino con tale ID esiste, non riusciamo a capire però quale sia l'eventuale dato anagrafico incongruente.

Potete aiutarci ?

**Comment by rvinzani** [comment]
Potreste provare a indicare nella località di nascita il codice 998 e come denominazione ALGERIA?

**Comment by busaster** [comment]
Chiedo ai colleghi di provare, in attesa dell'esito le faccio una domanda: come mai suggerisce  questa soluzione, pur essendo 8a quanto risulta da una estrazione 3002) il luogo di nascita già valorizzato nella posizione ANPR con dati sotto riprotati ?
```
<descrizioneLocalita>OULED MOUSSA</descrizioneLocalita>
<descrizioneStato>ALGERIA</descrizioneStato>
<codiceStato>401</codiceStato>
```

**Comment by busaster** [comment]
Nel frattempo la prova da lei suggerita ha dato esito negativo (ID operazione ANPR 220558177)

**Comment by rvinzani** [comment]
Può provare per favore inserendo il codice stato 401? Mi faccia sapere

**Comment by rvinzani** [comment]
Chiudo la issue. In caso il problema non fosse risolto vi prego di riaprirne una nuova che faccia riferimento a questa
