### ISSUE TITLE
Gestione AIRE - Comune subentrato

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#1997]
Buongiorno
un chiarimento ... La cancellazione dall’AIRE per rimpatrio dall’estero e/o residenza in Italia deve essere trattato come mutazione della residenza già previsto per i soggetti residenti in Italia, quindi 5001 (intera fam) e 5005 (singolo cittadino) ?

**Comment by rvinzani** [comment]
Sì, se il soggetto è già presente in ANPR come AIRE è corretto utilizzare i servizi di mutazione residenza 5005 e 5001

**Comment by GabriellaBallabio** [comment]
Dovendo iscrivere all'AIRE un cittadino residente in comune subentrato, già presente in ANPR, utilizziamo il servizio A006, con tipo mutazione 1=Modifica della residenza dall'Italia all’estero. Se l'iscrizione comporta la creazione di una nuova famiglia AIRE il tag <idFamigliaConvivenzaComune> come deve essere valorizzato ?

1. con il codice della nuova famiaglia AIRE
2. con il codice della famiglia APR e successivamente si invoca il servizio per la modifica del codice famiglia ?
