### ISSUE TITLE
EN531 Operazione non consentita: per il soggetto esiste un procedimento aperto

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#1998]
Cittadina proveniente dal comune di Petruro Irpino, al momento di confermare il procedimento di mutazione di residenza compare il seguente errore: ANPR segnala il seguente errore:
EN531 Operazione non consentita: per il soggetto esiste un procedimento aperto 
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-05 08:47:52 , idOperazioneANPR 220531336
EN395 per il tipo di mutazione 2 saranno modificati soltanto i dati relativi a residenza e autoveicoli.
Comunico l'Identificativo scheda attribuito da ANPR: 87058889.
Grazie.
Per qualsiasi comunicazione: tel. 0923993382 - 334

**Comment by frmariani** [comment]
Per completare l'operazione, il comune di Petruro Irpino deve chiudere il procedimento idanpr 22115537 (id comunale del procedimento 335).

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
