### ISSUE TITLE
Carta identità cartacea mancante in ANPR

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#1999]
Buongiorno,
ci stanno arrivando segnalazioni da più comuni che non si vedono più le carte d'identità cartacee,
riporto e esempi del Comune di CASTELLARANO (RE):
idANPR: 32266746  ---> mutazione anpr del 05/10/2019 id operazione 135385333
IdANPR: 32258587 ---> mutazione anpr del 29/01/2020 id operazione 195586584
grazie

**Comment by ATropeano** [comment]
Buonasera, altri comuni, segnalano che non sono più visibili anche i dati delle carte elettroniche rilasciate prima prima di febbraio 2019.
Grazie.
Alessio Tropeano

**Comment by rvinzani** [comment]
Buongiorno, si è trattato di un problema nel servizio di consultazione ora ripristinato. Non chiudo la issue in attesa di vostra verifica

**Comment by c-giacomini** [comment]
Buongiorno,
ho verificato i casi segnalati e ora sembrano a posto.
Grazie
