### ISSUE TITLE
Validità del codici fiscali esterni (Z135 - Z118)

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#2]
I nostri anagrafisti ci informano che tuttora l’agenzia delle entrate rilascia codici fiscali relativi a stati esteri cessati ( es. Yugoslavia ed Unione Sovietica) senza verificare i dati per il calcolo con l’anagrafe. Le tabelle degli stati esteri di ANPR  non contemplano questi stati. 
Sono ritenuti validi per ANPR i codici fiscali con codice catastale di questi stati ( Z135 e Z118)?

**Comment by gcarbonin** [comment]
Per i controlli di validità del codice fiscale, ANPR si basa esclusivamente su AE
