### ISSUE TITLE
Errore EAV02 non segnalato nelle tabelle di errore

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#20]
### Descrizione del comportamento
Errore EAV02 non è segnalato nelle tabelle di errore su https://www.anpr.interno.it/portale/documentazione-tecnica
e su https://italia.github.io/anpr/error/error_errori_agenzia_entrate.html.html (generata in automatico dalle prime)

### Data del test
9 Marzo 2017

### Ambiente
- [x] test
- [x] pre subentro
- [x] subentro

**Comment by gcarbonin** [comment]
i codici di errore sono stati rivisti; questo in particolare indica un errore di comunicazione tra ANPR e AE e non deve essere restiuito al comune. Sostituito da AEE97.
