### ISSUE TITLE
Certificazione da Web APP in ambiente di PreSubentro

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#200]
Test di certificazione da WebAPP, esito:

“Codice esenzioneDiritti 1 inesistente sulla tabella di riferimento (Codice: EC071)” 

selezionando nel campo “Esenzione bollo/diritti di segreteria” 

il valore “SCAMBIO DI ATTI E DOCUMENTI FRA PP.AA. - art. 16 …...” 

Test effettuato a fronte del fatto che non si riesce a certificare nemmeno da Web Service

**Comment by gcarbonin** [comment]
L'esenzione del diritto di segreteria segue di pari passo quello di esenzione del bollo. Indicando Scambio di atti... l'esenzione dei diritti è automatica.  
Soltanto quando si seleziona Altro motivo di esenzione (99 se si utilizzano i WS), è possibile specificare se il certificato è esente da diritti di segreteria (valore 1 nell'apposito campo se si utilizzano i WS).
Questa modalità è stata modificata nel corso del 2017 (pag. 127 delle specifiche)

**Comment by gcarbonin** [comment]
Può riprovare

**Comment by gcarbonin** [comment]
Il problema si è risolto?

**Comment by Chissodaniela** [comment]
Gentilissima dott.ssa
 Sono in atto degli interventi sistemistici per cui la prova riusciremo a farla lunedì prossimo.
 La ringrazio.
 Daniela Chisso

 Inviato dal mio dispositivo Huawei

 -------- Messaggio originale --------
 Oggetto: Re: [italia/anpr] Certificazione da Web APP in ambiente di PreSubentro (#200)
 Da: gcarbonin 
 A: italia/anpr 
 CC: Chissodaniela  ,Author 

Il problema si è risolto?

**Comment by Chissodaniela** [comment]
Gent.ma dott.ssa, abbiamo riprovato e la certificazione in questione ora e' andata a buon fine.
Grazie

**Comment by gcarbonin** [comment]
grazie
