### ISSUE TITLE
Informazioni su cancellazione per posizione duplicata su ANPR

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2000]
Salve,
abbiamo riscontrato una posizione duplicata su ANPR riguardo un nostro cittadino:

![screenshot-anpr](https://user-images.githubusercontent.com/47904600/75974779-a9ebbd80-5ed7-11ea-985c-388756a9e944.png)

La procedura corretta è quella di cancellazione per doppia iscrizione o quale?
Grazie

**Comment by rvinzani** [comment]
Sì, la procedura è quella di cancellazione per doppia iscrizione della posizione non corretta. Saluti
