### ISSUE TITLE
certificazione non consentita in caso di procedimento aperto

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2001]
In fase di trasferimento da comune subentrato a comune subentrato (mutazione 5001/5005) non risulta possibile effettuare la certificazione parziale (simile al caso aperto nel ticket #1937 con la differenza che nel ticket citato i comuni non sono entrambi subentrati). In ambiente di pre-subentro abbiamo:

1.  registrato il procedimento di mutazione 1014
2.  abbiamo aggiornato la residenza 5001/5005
3.  aggiornato le banche dati locali
4.  attivati i controlli amministrativi
5.  e poi registrato l'avvio dei controlli amministrativi col servizio 1014 con stato del procedimento amministrativo "Apertura istruttoria". 

E' normale non poter effettuare la certificazione parziale o sbagliamo noi qualcosa?

**Comment by frmariani** [comment]
la certificazione parziale in caso di procedimento in corso di istruttoria è in corso di evoluzione (vedi ticket #1937 ), pertanto al momento non è possibile produrre i certificati in caso di procedimento aperto.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
