### ISSUE TITLE
Correzione sui componenti di una famiglia ANPR

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2002]
Salve,
Comune di Bisaccia (AV).
Avremmo necessità di correggere la famiglia ANPR 44732084 in quanto il gestionale utilizzato presso il nostro comune vi ha aggregato dentro circa 500 cittadini utilizzando come criterio il fatto che avessero tutti FE0000000.

Qual è la procedura corretta per scorporare tale famiglia ANPR ?

**Comment by rvinzani** [comment]
Purtroppo l'unico modo è quello di effettuare delle mutazioni di residenza dei cittadini verso la famiglia e la residenza effettiva. Il servizio di mutazione 5005 consente di modificare la residenza di più cittadini contemporaneamente solo se provenienti da una stessa famiglia (come nel vostro caso) e che si spostano nella stessa famiglia di destinazione

**Comment by vix-db** [comment]
Volendo effettuare tale operazione da portale ANPR (lato utente) sotto il menù "Registrazione" qual è la funzione corretta da utilizzare? 
Grazie.

**Comment by rvinzani** [comment]
Registrazione->Mutazione residenza tipo mutazione - residenza
