### ISSUE TITLE
Integrare un secondo applicativo

### ISSUE THREAD

**Issue by nardil** [italia/anpr#2003]
Salve, 
per un comune abbiamo necessita' di attivare un secondo applicativo per il dialogo con ANPR che realizza operazioni di sola consultazione. In questo scenario e' possibile richiedere un secondo certificato server per il comune? Eventualmente con quale procedura?
Grazie

**Comment by Leonforte** [comment]
buongiorno, potete creare attraverso la console di sicurezza (gestione postazioni) un nuovo certificato ed utilizzare quello, saluti

**Comment by nardil** [comment]
Grazie, 

quindi contestualizzando le indicazioni della specifica:

![Schermata da 2020-03-06 12-22-55](https://user-images.githubusercontent.com/12340738/76079606-49c34d00-5fa5-11ea-9816-9cdbb5e4fa86.png)

il certificato del server comune puo' essere a sua volta un certificato di postazione, corretto?

Approfitto anche per chiedere se avete suggerimenti sulle policy di partizionamento dell'`idOperazioneComune` tra i diversi applicativi per evitare conflitti.

**Comment by Leonforte** [comment]
Buongiorno., certo, il certificato del server comune puo' essere a sua volta un certificato di postazione.
Per quanto riguarda l'idOperazioneComune lo stesso deve essere univoco.
Ad ogni buon fine vi ricordo che l'accesso all'ANPR è consentito al momento esclusivamente a personale del comune, quindi l'utilizzo del nuovo gestionale (anche se sotto la Vs responsabilità) deve rientrare in questo contesto. Vi segnalo inoltre che il Viminale sta predisponendo un portale per l'accesso da parte di entri esterni. Buon alvoro, saluti

**Comment by nardil** [comment]
Grazie
