### ISSUE TITLE
[5008] Perfezionamento Iscrizione - Errore EN389 non comprensibile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2004]
ambiente di PRODUZIONE - comune di CORSICO (015093)

si invia comunicazione 5008 di perfezionamento iscrizione (idOperazionComune 2020002567)
la comunicazione va in errore con questi messaggi:
```
<errore>
  <codiceErroreAnomalia>EN389</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data decorrenza 06-03-2020 dell'operazione non puo' essere inferiore alla data decorrenza errore da GET_CARTA_IDENTITA esito:999 dell'ultima operazione effettuata sui dati relativi a @</testoErroreAnomalia>
</errore>
<errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-06 10:42:49 , idOperazioneANPR 221562083</testoErroreAnomalia>
</errore>
```
a parte la difficoltà di comprensione del messaggio, faccio notare che la data decorrenza della comunicazione è quella di oggi.

potete verificare?
grazie

Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Potete per favore provare nuovamente ad effettuare l'operazione?

**Comment by rvinzani** [comment]
Chiudo la issue. In caso il problema non fosse risolto vi prego di riaprirne una nuova che faccia riferimento a questa
