### ISSUE TITLE
Codici ISTAT non coerenti con SISTAT

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2005]
Dopo gli ultimi aggiornamenti del SISTAT sono presenti incoerenze sui codici ISTAT. Riporto nella tabella sottostante quelli riscontrati.

ID|DATAISTITUZIONE|DATACESSAZIONE|DENOMINAZIONE_IT|CODISTAT
-|-|-|-|-
9017|17/03/1861|14/06/1928|SANT'ANTONIO RUINAS|~095048~092108
19589|12/01/1951|19/08/1974|SANT'ANTONIO RUINAS|~095048~092108
16651|17/03/1861|27/10/1937|ELMAS|~092108~092885
18490|17/03/1861|11/05/1928|QUARTUCCIU|~092105~092884

**Comment by MassimoSchiappa** [comment]
Salve,
grazie per la segnalazione, dopo una verifica puntuale procederemo al relativo aggiornamento.
Cordiali saluti.
