### ISSUE TITLE
DOMICILIO FISCALE IN AE SOVRASCRITTO DA ANPR

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2006]
Un nostro Cliente (subentrato in ANPR il 14/01/2020) ci segnala quanto segue: 
"per un cittadino che esercita attività economica (nella fattispecie studio associato di ingegneri) la migrazione in ANPR ha provocato, in completo automatismo, la sovrascrittura del Domicilio Fiscale in Agenzia delle Entrate, sostituendo il domicilio fiscale dichiarato con la residenza registrata in ANPR, senza alcuna volontà da parte del cittadino.
Il nostro timore è che tale ipotesi si sia ripetuta per X cittadini senza la consapevolezza né nostra né dei contribuenti. Il domicilio fiscale, per chi esercita attività economiche, capita che sia spesso diverso dalla dimora abituale, potendosi trattare della propria sede d’impresa o del proprio studio professionale o del proprio commercialista.
Sbagliato sarebbe sovrascrivere tale domicilio con l’attuale residenza.
Il timore non riguarda solo l’operazione di subentro ANPR, ma si estende ad ogni caso di future mutazioni anagrafiche nei casi in cui il domicilio fiscale sia diverso dalla residenza. Esso verrà, erroneamente, sovrascritto con la nuova residenza?"

Come sw house abbiamo visto che il domicilio digitale tramite registrazione della pec in Anpr non è ancora attivo, e questa modifica dovrebbe sostituirsi al domicilio fiscale di AE, in attesa che venga resa attiva non crediamo sia corretto sovrascrivere i dati in AE. 

Grazie 
Cordiali saluti

Cinzia Girelli
Gruppo GPI SpA

**Comment by rvinzani** [comment]
Riporto quanto presente AA9/12
_RESIDENZA ANAGRAFICA: si ricorda che a norma delI’art. 58 del D.P.R. n. 600/1973 le persone fisiche
residenti nello Stato hanno il domicilio fiscale nel comune nella cui anagrafe sono iscritte....
....Qualora il domicilio fiscale del contribuente sia stato stabilito dall’Amministrazione finanziaria, d’autorità
o su richiesta del contribuente stesso, a norma dell’art. 59 del D.P.R. n. 600/1973, in un comune
diverso dalla residenza anagrafica, il provvedimento dell’Amministrazione ha effetto dal periodo d’imposta
successivo a quello in cui è stato notificato._

Quest'ultimo caso è gestito dai servizi di Agenzia Entrate richiamati da ANPR
