### ISSUE TITLE
Problema visualizzazione dati carta d'identità del soggetto 18939200

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2007]
In fase di visualizzazione della scheda soggetto num. 18939200 dovrebbe essere visualizzata la carta d'identità AZ0144529, mentre ANPR visualizza ancora la num. AR5726340.

L'effettivo storico delle carte d'identità del soggetto è il seguente: 
I.Numero AR5726340 rilasciata il 09/08/2010 a MONZA (Valida per l'espatrio) scade il 08/08/2020 
II.Numero CA31019EI rilasciata il 17/06/2019 a BIASSONO (Valida per l'espatrio) scade il 19/05/2030 
III.Numero AZ0144529 rilasciata il 03/03/2020 a ORIO AL SERIO (Valida per l'espatrio) scade il 19/05/2030

I miei riferimenti sono i seguenti:
Andrea Paltrinieri - Ufficiale d'Anagrafe del Comune di Biassono
tel. 0392201060
paltrinieri.andrea@biassono.org

In attesa di un Vs. gentile riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by rvinzani** [comment]
La consultazione adesso mostra la CI corretta. Mi faccia sapere

**Comment by paltrinan** [comment]
adesso è a posto!
Grazie mille per l'assistenza ricevuta
Buona giornata
Andrea Paltrinieri
