### ISSUE TITLE
archivio comuni aggiornato al 05-03-2020: codice catastale di CAPRANICA

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2009]
Nell'ultimo aggiornamento dell'archivio dei comuni reso disponibile (aggiornato al 05-03-2020), l'unica variazione riguarda il comune di CAPRANICA per il cui periodo storico dal 1871-01-15 al 1927-01-11 il codice catastale passa da B688 a B687 (riga con ID=15674).

Mi permetto di chiedervi conferma di questa variazione.
Se confermata il codice B687 non permetterebbe più di individuare univocamente il comune ad una certa data,  in quanto nel periodo tra il 1872 e il 1927 risulterebbero due comuni con lo stesso codice catastale

Riporto porzione di interesse del file:

15674,**"1871-01-15","1927-01-11",**"058828",**"B687"**,"CAPRANICA",...
...
15675,**"1872-09-02","1929-06-15"**,"058019",**"B687"**,"CAPRANICA PRENESTINA",...

Grazie,
Tiziano

**Comment by ncapozzi** [comment]
Buongiorno,
abbiamo chiesto una verifica a ISTAT.

N. Capozzi

**Comment by Tiz68** [comment]
Buongiorno,
ho visto che nell'archivio dei comuni rilasciato oggi è stato corretto il problema ed eliminata l'ambiguità.
Mi sembra di aver identificato un'altra situazione ambigua, ma visto che riguarda un altro comune, meglio chiudere questa issue e aprirne una nuova.

Grazie,
Tiziano
