### ISSUE TITLE
Certificazione da WebApp

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#201]
......  **L'esenzione del diritto di segreteria segue di pari passo quello di esenzione del bollo. Indicando Scambio di atti... l'esenzione dei diritti è automatica.**
 
.... questo è quello che avevamo selezionato su Web App e ha prodotto la segnalazione inviata precedentemente. Quindi ci conferma che doveva produrre il certificato!!!!

**Comment by gcarbonin** [comment]
#200
