### ISSUE TITLE
Mancato recapito tessere sanitarie in comune fuso subentrato in ANPR #1940

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2011]
Alcuni giorni dopo la segnalazione in oggetto ho letto l'avviso con il quale si comunicava che nelle giornate del 22 e 23 febbraio i sistemi di Agenzia Entrate che colloquiano con ANPR sarebbero stati aggiornati per adeguare ad ANPR le banche dati contenenti le informazioni relative all’indirizzo di residenza, al fine di soddisfare i nuovi criteri che saranno adottati per comporre l’indirizzo di recapito delle comunicazioni fiscali ai cittadini.
Veniva anche precisato che successivamente era previsto un progressivo riallineamento degli indirizzi dei soggetti residenti nei comuni già subentrati in ANPR e allineati all’Agenzia Entrate, per il trasferimento delle eventuali informazioni di residenza mancanti in Agenzia Entrate.
Poichè ad oggi nulla risulta variato per il comune di Valsamoggia rispetto al problema che era stato segnalato e che continua a persistere, chiedo se sia possibile sapere, anche indicativamente, entro quanto tempo si potrà giungere ad una soluzione

**Comment by rvinzani** [comment]
Abbiamo anticipato il recupero degli indirizzi del vostro comune al 12 marzo vista la vostra urgenza

**Comment by rvinzani** [comment]
L'aggiornamento programmato per il 12 marzo è stato spostato per alcuni problemi tecnici

**Comment by rvinzani** [comment]
L'aggiornamento è stato effettuato
