### ISSUE TITLE
Gestione AIRE - Comune subentrato con riferimento issue #1997

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2012]
Dovendo iscrivere all'AIRE un cittadino residente in comune subentrato, già presente in ANPR, utilizziamo il servizio A006, con tipo mutazione 1=Modifica della residenza dall'Italia all’estero. Se l'iscrizione comporta la creazione di una nuova famiglia AIRE il tag come deve essere valorizzato ?

   - con il codice della nuova famiaglia AIRE
   - con il codice della famiglia APR e successivamente si invoca il servizio per la modifica del codice famiglia ?

**Comment by rvinzani** [comment]
Nell'emigrazione di un cittadino dall'Italia all'estero (AIRE) è possibile indicare il codice della nuova famiglia AIRE. ANPR assegnerà inoltre un nuovo identificativo famiglia

**Comment by rvinzani** [comment]
chiudo la issue. Nel caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
