### ISSUE TITLE
Iscrizione di un soggetto precedentemente cancellato da ANPR

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2013]
Salve,
Comune di Montoro (AV).

Non riusciamo ad iscrivere il cittadino ID 69879079 cancellato da ANPR dal comune di provenienza per il nostro comune quando non eravamo ancora subentrati.

Errore: tutti i soggetti devono appartenere alla stessa famiglia dichiarata.

Qual è la procedura corretta per iscrivere il soggetto nella nostra APR?

**Comment by rvinzani** [comment]
Dovete effettuare una nuova iscrizione inserendo nuovamente tutte le informazioni del soggetto ed anche il precedente idANPR 69879079

**Comment by vix-db** [comment]
Ok, quindi iscrizione ex novo... l'unica differenza è che il cittadino avrà ID ANPR originario?
Deduco quindi che nel form di iscrizione avrò il modo di specificare ID 69879079.
Devo specificare una modalità di iscrizione specifica?

**Comment by rvinzani** [comment]
No, l'iscrizione è quella solita per altri motivi, è solamente necessario indicare il precedente ID previsto nel campo nella form

**Comment by vix-db** [comment]
Salve,
provando ad effettuare l'iscrizione come da lei indicato otteniamo il seguente errore:

Operazione non consentita: per il soggetto esiste un procedimento aperto (Codice: EN531)

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-16 13:02:52 , idOperazioneANPR 225473540 (Codice: EN527)

Di quale procedimento si tratta?
Abbiamo anche notato che il comune di precedente iscrizione aveva immesso un codice fiscale errato (tipo femminile) che ovviamente abbiamo dovuto indicare anche noi in fase di re-iscrizione.

**Comment by rvinzani** [comment]
Esiste un procedimento aperto dal comune di Napoli n. 1222685. Dovete contattare il comune per chiedere se possono chiuderlo o hanno ancora indagini in corso. Allego la guida per la chiusura dall'applicazione web di ANPR.
Vi prego anche di riaprire una nuova issue nel caso fosse necessario un ulteriore chiarimento su una issue già chiusa
[Chiusura Procedimento.pdf](https://github.com/italia/anpr/files/4338346/Chiusura.Procedimento.pdf)
