### ISSUE TITLE
archivio comuni: codice catastale di FILAGO

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2014]
Buongiorno, 
a partire dall'aggiornamento dell'archivio dei comuni del 04/11/2019, è stato modificato il codice catastale di FILAGO esistito dal 1861 al 1928.

Estratto dell'archivio pre 04/11/2019:

11225,"1861-03-17","1928-01-26","016828","**ND**","FILAGO","FILAGO",...

Estratto dell'archivio post 04/11/2019:

11225,"1861-03-17","1928-01-26","016828","**D588**","FILAGO","FILAGO",...

La conseguenza di questa variazione è che il codice catastale D588 tra il 1861 e il 1928 risulta associato a due comuni:

11225,"**1861-03-17**","**1928-01-26**","016828","**D588**","FILAGO","FILAGO", ...

3886,"**1861-03-17**","**1928-01-25**","016098","**D588**","MARNE","MARNE", ...
20305,"1928-01-26","1958-09-09","016098","**D588**","MARNE","MARNE",...
3885,"1958-09-10","9999-12-31","016098","**D588**","FILAGO","FILAGO", ...

Chiedo una conferma della correttezza di questi dati.

Grazie,
Tiziano

**Comment by MassimoSchiappa** [comment]
Salve,
come lei correttamente evidenzia, sembra esserci un'incongruenza sul dato del codice catastale, le confermo comunque che i due comuni di Marne e Filago sono esistiti entrambi per uno stesso periodo, e che poi sono confluiti nel comune di Marne, che in seguito a sua volta ha cambiato denominazione in Filago. Chiederemo conferma ad Agenzia delle Entrate ed eventualmente provvederemo a modificare i dati se fosse necessario, attualmente però possiamo solo confermare quei dati.

**Comment by MassimoSchiappa** [comment]
Salve,
da AE non abbiamo avuto indicazioni diverse da quanto già presente in banca dati ...
Cordiali saluti.
