### ISSUE TITLE
EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto

### ISSUE THREAD

**Issue by muzzarellicesena** [italia/anpr#2015]
Buongiorno,
scrivo dal comune di Cesena per segnalare il seguente errore che si verifica andando ad iscrivere un cittadino residente in ANPR nel comune di Ravenna.

EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto

EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-10 08:54:16 , idOperazioneANPR 222958617

Abbiamo già contattato il comune di Ravenna per informarli di chiudere il procedimento, ma la risposta è stata che non vi è alcun procedimento in corso per il cittadino in questione.

Certi di una vostra risposta
Cordiali saluti
Comune di Cesena

**Comment by rvinzani** [comment]
Abbiamo inviato email al comune di Ravenna con il numero del procedimento aperto (IMMITANN201901060) e istruzioni per chiuderlo da web app ANPR
