### ISSUE TITLE
Salorno sulla strada del vino

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2016]
Con L.R. 19 settembre 2019 n. 5 il comune di _SALORNO/SALURN_ ha assunto la denominazione _SALORNO SULLA STRADA DEL VINO/SALURN AN DER WEINSTRAßE_. Il cambiamento è già presente nei dati SISTAT.

**Comment by MassimoSchiappa** [comment]
Grazie per la segnalazione,
verificheremo al più presto quanto da lei indicato ed eventualmente provvederemo a modificare la base dati di conseguenza.
Cordiali saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
abbiamo provveduto all'aggiornamento dell'informazione che ci ha segnalato.
Grazie di nuovo e cordiali saluti.
