### ISSUE TITLE
EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto

### ISSUE THREAD

**Issue by muzzarellicesena** [italia/anpr#2017]
Buongiorno,
come per la issue #2015 (riprovata oggi ma ancora bloccata dal comune di Ravenna) segnaliamo altre 2 re-iscrizioni da irreperibilità dal comune di Villa Rosa (Enna).
Abbiamo già contattato il comune ma ci ha risposto che non vi è alcun procedimento aperto per i cittadini in questione.

1)
EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-12 16:27:47 , idOperazioneANPR 224520804
EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto

2)
EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-12 16:34:29 , idOperazioneANPR 224526316
EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto

Certi di una vostra risposta
Cordiali saluti
Comune di Cesena

**Comment by rvinzani** [comment]
Abbiamo sollecitato la chiusura da parte di Ravenna ed inviato email al comune di Villarosa con il numero di procedimento da chiudere e le istruzioni
