### ISSUE TITLE
operazione effettuata con successo non presente in elenco operazioni del cittadino

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2018]
Salve, buongiorno
per il comune di Matera (cod-istat 077014), in ambiente di pre-subentro abbiamo effettuato un invocazione 5008 per il soggetto con id: 223210269 ed abbiamo ricevuto una risposta con esito positivo (idoperazione: 16653679) ma nell'elenco operazioni del cittadino non compare nessuna operazione

**Comment by frmariani** [comment]
l'operazione idanpr 16653679 è riferita al cittadino idanpr 222484322;
per il cittadino idanpr 223210269 non sono state effettuate operazioni

**Comment by carminepat** [comment]
Perfetto, grazie, procediamo con le nostre verifiche
