### ISSUE TITLE
Operazioni di rettifica e notifiche NRIS

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2019]
In ambiente di test tramite webapp abbiamo rettificato il comune di provenienza nei dati di iscrizione di un cittadino (id operazione 24677566).

Abbiamo poi tramite WS richiesto le notifiche NRIS ma nella risposta non è presente l'operazione sopra descritta (ID richiesta operazioni 24677601, ID risposta completata 24677641)

Come mai ?

**Comment by azabatta** [comment]
Buongiorno,
abbiamo apportato una correttiva. La notifica è stata prodotta (idOperazioneANPR 24709702). E' possibile riprovare la richiesta di estrazione delle NRIS utilizzando come data di riferimento la data di oggi 20.03.2020. 
Buon lavoro
