### ISSUE TITLE
Web App: Errore in mutazione dati generali / stato civile

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#202]
Buongiorno,
nella Web App dell' ambiente di test , quando cerchiamo di registrare una vedovanza con mutazione dati generali/stato civile per matricola ANPR:4119842, dopo aver ricercato la persona , nel momento in cui compare la schermata per indicare i dati che si vogliono modificare, compare il messaggio:
"il campo serie contiene dei caratteri non validi"
Se consultiamo la persona , non troviamo errori di questo tipo nella videata degli errori.

Grazie
Elena Di Martino
Sistemi Informativi srl

**Comment by gcarbonin** [comment]
questo errore non viene segnalato. Nella serie dell'atto di matrimonio è presente il valore C/01; il carattere "/" non è ammesso. Come descritto nelle specifiche. i caratteri ammessi sono quelli dell'alfabeto inglese e i numeri. Nel cognome e nel nome si accettano anche i segni diacritici (da decreto Brunetta) nonché il punto, la virgola, l'apice e il trattino.

**Comment by ANPRCDBO** [comment]
Ci sono anche altri errori che non vengono segnalati, in modo che possiamo fare dei controlli su tutti?

**Comment by gcarbonin** [comment]
Non mi risulta.  Sappiamo che questi controlli sono effettuati di norma localmente e sui campi principali (nome cognome indirizzo estremi dei documenti ecc.) è il sw di subentro che effettua la conversione dei caratteri speciali a spazio. Sulla serie dell'atto ci manca la conversione .
