### ISSUE TITLE
[A002] Errore in data decorrenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2021]
Ambiente di Test, comune di Poggio a Caiano.
Tentiamo di iscrivere in aire uni cittadino ma riceviamo l'errore "EN237 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata" (id operazione ANPR 24698362).

Non capiamo però il senso dell'errore visto che il cittadino in ANPR non c'è.

Qual è la causa ?

**Comment by ncapozzi** [comment]
Buonasera,
probabilmente il problema deriva dal fatto che nel comune esiste già una famiglia con identificativo 'FE0000002' alla quale fa riferimento il controllo. Potete provare ad inserire un identificativo diverso?

**Comment by busaster** [comment]
Grazie, non ci avevo fatto caso.

**Comment by ncapozzi** [comment]
Prego, saluti

N. Capozzi
