### ISSUE TITLE
Annullamento operazioni ANPR

### ISSUE THREAD

**Issue by anagrafecarenno** [italia/anpr#2022]
Buongiorno, ho l'esigenza di annullare fisicamente l'operazione anpr avente id 225795001, cui però sono succedute le operazioni anpr id 226231990, 226232198, 226232349

L'operazione 225795001 la annullerò attraverso il mio software gestionale, ma le successive sono state fatte direttamente da webapp e non so come annullarle.

Potete suggerirmi i click necessari per effettuare l'annullamento delle successive tre?

Grazie
Eliana Botti
Ufficiale di Anagrafe Comune di Carenno

**Comment by ncapozzi** [comment]
Buongiorno,
seguendo le istruzioni fornite telefonicamente ha correttamente annullato le operazioni indicate.
Ora può rieseguire l'iscrizione AIRE per altri motivi con la data di decorrenza corretta.
N. Capozzi
