### ISSUE TITLE
Errore mutazione tutti i dati

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2023]
Comune di Altivole
-ambiente di produzione-
il soggetto con ID 37727677 ha erroneamente un doppio spazio tra i 2 nomI, tentando di fare una mutazione per eliminare lo spazio (modifica senza validazione CF ) -->  ho errore EN230
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
è stata fornita assistenza telefonica all'utente per la risoluzione del problema segnalato.

N. Capozzi
