### ISSUE TITLE
Problema ricerca procedimento amministrativo

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2024]
Comune di Modena - Ambiente di produzione

Buongiorno,
il Comune di Nonantola deve immigrare il soggetto con idANPR 19260528 (ora residente a Modena, sul quale non ci risultano pratiche in corso) ma ottiene questo errore:
"Operazione non consentita: per il soggetto esiste un procedimento aperto
Informazioni sull'operazione da fornire in caso di assistenza : data
2020-03-12 11:47:16 , idOperazioneANPR 224332142"

Nonantola ha aperto il ticket 21231119 e la risposta è stata:

_"Modena ha un procedimento aperto sulla scheda soggetto. Quindi è necessario contattare Modena
Quindi Modena deve sbloccare il procedimento amministrativo dalla webapp ANPR (sito subentro) tramite la funzione REGISTRAZIONE-Gestione Procedimento Istruttoria e cercare il procedimento tramite il cf del soggetto"_

Purtroppo noi non riusciamo a trovare il numero del procedimento nè interrogando il soggetto nè cercando il procedimento dalla funzione "Consultazione procedimento amministrativo". Nel primo caso dopo un' attesa abbastanza lunga otteniamo il messaggio:
"Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi"
nel secondo caso invece abbiamo
"Errore di sistema".

Per cortesia potete aiutarci a recuperare il procedimento in modo da chiuderlo e consentire a Nonantola di terminare l' iscrizione?

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera,
abbiamo verificato che in realtà i procedimenti amministrativi aperti dal Comune di Modena per il soggetto interessato dovevano risultare tutti chiusi. Potete contattare il Comune di Nonantola e chiedere di riprovare la mutazione di residenza per favore?

N. Capozzi

**Comment by sfmodena** [comment]
Buongiorno,
la mutazione è andata a buon fine ed il soggetto ora risiede a Nonantola, chiudo la issue.
Grazie per la collaborazione, cordiali saluti.

Sonia Fiorini
