### ISSUE TITLE
[NRIS] Rettifiche e XML richiesta

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2025]
Ho proseguito le prove iniziate con la #2019. Ora le notifiche NRIS in conseguenza di rettifica iscrizione arrivano, però pur specificando nel filtro 4005 "<dettaglioDati>TUTTO</dettaglioDati>" viene ritornata la sola risposta (id operazione richiesta scarico 24714453, id operazione scarico 24714486)

**Comment by azabatta** [comment]
Buonasera,
le notifiche di tipo  NRIS, a prescindere dall’evento cui sono collegate,  sono generate con la sola sezione della risposta restituita da ANPR a fronte dell’evento anagrafico comunicato tramite web app (di qui il nome: “RIS” sta per risposta) . 
Questo meccanismo è previsto in generale per tutte le notifiche che per definizione hanno una sola sezione. 
La possibilità di  scaricare richiesta e/o  risposta è possibile solo per gli eventi anagrafici.

**Comment by busaster** [comment]
Però con la sola risposta non è possibile collegare il movimento alla persona cui è stata fatta la correzione e quindi aggiornare la base dati locale.

**Comment by azabatta** [comment]
In effetti il problema sussiste solo per il ws 5014 che ha una risposta molto scarna, per gli altri ws la risposta riporta sempre le generalità del soggetto o della famiglia oggetto di trattamento.
Al momento l’unica possibilità è invocare nuovamente il ws 4005 utilizzando l’idOperazioneANPR contenuto nella NRIS.

**Comment by busaster** [comment]
Esattamente. Purtroppo nel flusso applicativo non è pensabile affidarsi ad una nuova chiamata asincrona. 
Nel caso delle sole notifiche NRIS suppongo che XML della richiesta esista, non sarebbe possibile modificare il 4005 affinché la ritorni nella risposta ? Risolverebbe un bel po' di problemi.

**Comment by azabatta** [comment]
Buongiorno,  purtroppo la modifica richiesta, pur essendo semplice,  ha un forte impatto su tutto il sistema delle notifiche di  ANPR. Impone di  rivedere sia i ws interessati ma anche  elaborazioni asincrone, procedure  per l’accesso ai dati etc.
Stiamo valutando altre soluzioni meno invasive.

**Comment by azabatta** [comment]
Buongiorno, 
abbiamo individuato una soluzione  relativa la solo ws 5014 posto che   è l’unico servizio che nella response non referenzia il soggetto o la famiglia trattata.
La response    è stata ampliata  con l’aggiunta dell’identificativo ANPR del soggetto e della  rettifica effettuata. La modifica non ha comportato adeguamento dei tracciati ma solo l’utilizzo di un element opzionale  già presente "tipoRispostaRettifica". 
Ci auguriamo che questo adeguamento sia sufficiente per le vostre  esigenze di aggiornamento dei database comunali. 
Saluti

**Comment by azabatta** [comment]
Buongiorno,
l'implementazione è disponibile negli ambienti di test_comuni e presubentro.
Buon lavoro
