### ISSUE TITLE
[1002] Famiglia non certificabile ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2026]
Ambiente di test
Ho iscritto due cittadini per immigrazione da non subentrato che formano una nuova famiglia (id operazione ANPR 24731154 e 24731155), la prima con FI=1 la seconda con FI=0,   per poi completare anche i loro dati con chiamate 5008 (24731168 e 24731169).
Nessuna anomalia sulla famiglia viene segnalata nelle risposte.

Consultando però la scheda individuale mi compare l'anomalia "Relazioni di parentela incongruenti per la famiglia,                      verificarle prima di emettere certificati di stato di                      famiglia".

Se provo a fare un certificato di stato famiglia vengo bloccato dall'errore "EN222 : I certificati di stato di famiglia,  stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile".

Come mai ? La seconda iscrizione con FI=0 non avrebbe dovuto completare la famiglia ?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
la segnalazione deriva dal fatto che la famiglia risulta composta dall'intestatario e dalla moglie ma sulle relative schede mancano i dati del matrimonio. Non basta l'indicazione dello stato civile.
Può provare ad aggiungere il matrimonio e rifare il certificato?

**Comment by busaster** [comment]
Il motivo era quello, non ricordavo questo controllo ed essendo anagrafiche inventate di prova non ho caricato tutti i dati necessari.
Grazie
