### ISSUE TITLE
Ambienti ANPR: indicazioni su accesso ad area di (Pre)Subentro ANPR

### ISSUE THREAD

**Issue by antonioluberto** [italia/anpr#2027]
Buongiorno.
La presente per richiedere se sono ancora valide le indicazioni per le quali l’accesso all’area di Pre-Subentro (e Subentro) ANPR possa avvenire solo da pc  "interno" al dominio comunale (e sul quale risulti installato specifico certificato di postazione) secondo quanto indicatoci nella https://github.com/italia/anpr/issues/1408
ovvero se siano intervenute modifiche a riguardo?

Ringraziando sin d'ora per l'indicazione che vorrete fornirci, porgo cordiali saluti.

Antonio Luberto

**Comment by FilippoPapi** [comment]
buongiorno le indicazioni riportate nella issue  #1408 sono sempre valide
un Saluto
Gianfilippo papi
