### ISSUE TITLE
EN222 su vedovo risposato

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#2028]
Arianna Nozzoli CED Comune di Prato in produzione
Buongiorno,
non riusciamo ad emettere un certificato di stato di famiglia perchè riceviamo l'errore EN222 'famiglia non certificabile' idOperazioneANPR 215535992. Le parentele sono tutte esatte. L'unica cosa particolare è che questo cittadino ha la vedovanza registrata e il successivo matrimonio. Grazie

**Comment by ncapozzi** [comment]
Buonasera, come da accordi telefonici la richiamerò martedì prossimo per verificare i dati del cittadino. Nel frattempo la informo che è comunque possibile produrre il certificato forzando la stampa.

N. Capozzi

**Comment by ncapozzi** [comment]
Il problema nasce dal fatto che al subentro per il cittadino  è stato erroneamente trasmessa la vedovanza dal primo matrimonio con i dati del matrimonio attuale. Avrebbe dovuto essere trasmesso il solo matrimonio attuale. Il caso può essere risolto con la revoca dati matrimonio che però è possibile solo se dopo il subentro non sono state eseguite altre operazioni. Se sono state eseguite altre operazioni, queste devono essere annullate prima di eseguire la revoca.

N. Capozzi
