### ISSUE TITLE
A006 - 999 - Operazione non effettuabile

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2029]
Comune di Torino
Ambiente PRESUBENTRO

Buonasera,
abbiamo effettuato due tentativi di cambio indirizzo AIRE, ma falliscono entrambi con l'errore in oggetto.

Id scheda soggetto ANPR: 60206800
E - 999 - Operazione non effettuabile
E - EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-26 16:42:13 , idOperazioneANPR 16862650

Id scheda soggetto ANPR: 60221757
E - 999 - Operazione non effettuabile
E - EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-03-26 16:56:59 , idOperazioneANPR 16862713

Non essendo la descrizione dell'errore esaustiva non riusciamo a capire quale sia esattamente l'errore.

Grazie,
Chiara Leanza

**Comment by mttfranci** [comment]
Salve, ci scusiamo, c'è stato un disservizio di qualche minuto legato al rilascio di ieri della [Patch 5.6.16](https://github.com/italia/anpr/blob/master/src/change-management/changelog.md), ma era già tutto risolto poco dopo, potreste riprovare? Grazie

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno,

abbiamo provato e funziona, vi ringraziamo per la sollecita risposta.

Buon lavoro,
Chiara Leanza

**Comment by mttfranci** [comment]
Di nulla, buon giornata.
