### ISSUE TITLE
Errore Registrazione vedovanza 5008 tramite Web Services

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#203]
Buongiorno, 
in ambiente di test del comune di Bologna, quando cerchiamo di registriamo la vedovanza , ci prendiamo in riposta: <?xml version="1.0" encoding="UTF-8"?>
-<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
-<env:Body>
-<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Internal Error (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>
L'xml di richiesta ci risulta valido secondo gli xsd.
Allego l'xml , dove sono stati cancellati i dati sensibili con XXXX.
Cordiali Saluti
Elena Di Martino
Sistemi Informativi Srl

-<ns2:Richiesta5008 xmlns:ns3="http://sogei.it/ANPR/rispostaComune" xmlns:ns2="http://sogei.it/ANPR/5000mutazione">

-<testataRichiesta>

<idOperazioneComune>20170606163244554214554214F73B</idOperazioneComune>

<codMittente>037006</codMittente>

<codDestinatario>ANPR00</codDestinatario>

<operazioneRichiesta>5008</operazioneRichiesta>

<dataOraRichiesta>2017-06-06T16:32:44</dataOraRichiesta>

<tipoOperazione>C</tipoOperazione>

<protocolloComune>01APRVAR 2017000383</protocolloComune>

<dataProtocolloComune>2017-06-06</dataProtocolloComune>

<tipoInvio>TEST</tipoInvio>

<dataDecorrenza>2017-05-31</dataDecorrenza>

<nomeApplicativo>SIPO</nomeApplicativo>

<versioneApplicativo>1997-2015</versioneApplicativo>

<fornitoreApplicativo>SISTEMI INFORMATIVI</fornitoreApplicativo>

</testataRichiesta>

-<generalitaPerRicerca>

-<codiceFiscale>

<codFiscale>XXXXXXXXX</codFiscale>

</codiceFiscale>

<cognome>XXXXXXXX</cognome>

<nome>XXXXXX</nome>

</generalitaPerRicerca>

-<generalitaDaModificare>

-<generalita>

-<codiceFiscale>

<codFiscale>XXXXXXXXX</codFiscale>

</codiceFiscale>

<cognome>XXXXXXXX</cognome>

<nome>XXXXX</nome>

<sesso>F</sesso>

<dataNascita>1993-03-21</dataNascita>

-<luogoNascita>

-<localita>

<descrizioneLocalita>Lima</descrizioneLocalita>

<descrizioneStato>PERU'</descrizioneStato>

<codiceStato>615</codiceStato>

</localita>

</luogoNascita>

</generalita>

</generalitaDaModificare>

-<statoCivile>

<statoCivile>3</statoCivile>

</statoCivile>

-<vedovanza>

-<datiMorteconiuge>

<dataEvento>2017-05-31</dataEvento>

-<luogoEvento>

-<comune>

<nomeComune>Bologna</nomeComune>

<codiceIstat>037006</codiceIstat>

<siglaProvinciaIstat>BO</siglaProvinciaIstat>

</comune>

</luogoEvento>

-<attoEvento>

-<comuneRegistrazione>

<nomeComune>Bologna</nomeComune>

<codiceIstat>037006</codiceIstat>

<siglaProvinciaIstat>BO</siglaProvinciaIstat>

</comuneRegistrazione>

<anno>2017</anno>

<parte>1</parte>

<numeroAtto>99</numeroAtto>

</attoEvento>

</datiMorteconiuge>

</vedovanza>

-<datiControllo>

<tipoMutazione>01</tipoMutazione>

<tipoMutazione>13</tipoMutazione>

<gestioneCF>3</gestioneCF>

</datiControllo>

</ns2:Richiesta5008>

**Comment by ANPRCDBO** [comment]
[1496759573830_CoAn_Request.gz](https://github.com/italia/anpr/files/1057182/1496759573830_CoAn_Request.gz)

**Comment by gcarbonin** [comment]
Dai log rileviamo questo:

..... operation mutazione_famiglia_convivenza does not match SOAP operation as required by WS-I BP1.0/1.1 R2744 or R2745: **received (Richiesta5008) required (Richiesta5001).** 

sembrerebbe che il comune stia indicando come soapAction il servizio 5005 ma in realtà sta sottomettendo una richiesta per il servizio 5008.

Se non riuscite ad individuare il problema che è lato client dobbiamo organizzare una prova da eseguire congiuntamente

**Comment by gcarbonin** [comment]
Il problema si è risolto?

**Comment by ANPRCDBO** [comment]
Dai nostri controlli non risuciamo a capire dove sta il problema.
Potete dirci in quale tag si evince che stiamo chiamando il servizio 5005, invece del servizio 5008?

**Comment by gcarbonin** [comment]
Non è nella richiesta ma nel vostro client che non vediamo

**Comment by ANPRCDBO** [comment]
Salve,
riusciamo stamattina a fare la prova congiunta che ci suggerivate?
Questi i miei riferimenti:

Grazie
Cordiali Saluti
Elena Di Martino

Sistemi Informativi Srl/an IBM Company
Cell: 3351234683

**Comment by gcarbonin** [comment]
La contatterà un mio collega. Le anticipo che abbiamo fatto questa prova (andata bene): abbiamo inviato la vostra richiesta (esclusa la parte soap) tramite soapui nel nostro ambiente di validazione e ha funzionato. Quale URL utilizzate per l'invio?

**Comment by ANPRCDBO** [comment]
Questa sono i paremetri con cui facciamo il colloquio, indirizzo, metodo e l'xml che viene generato:
Address: https://wstest.anpr.interno.it/ANPR5000ServiziMutazione/AnprService5000
Encoding: UTF-8
Http-Method: POST
Content-Type: text/xml
Headers: {Accept=[*/*], SOAPAction=[""]}
Payload: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soap:mustUnderstand="1"><wsu:Timestamp wsu:Id="TS-34dfb9d4-0001-4455-862a-baf578eb0b6a"><wsu:Created>2017-06-06T12:49:24.065Z</wsu:Created><wsu:Expires>2017-06-06T12:54:24.065Z</wsu:Expires></wsu:Timestamp><wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="X509-690169d4-af3c-4e0c-97d6-eac5ec953395">MIIE6zCCAtOgAwIBAgIIUdcEr/LJDqgwDQYJKoZIhvcNAQELBQAwWjEbMBkGA1UEAwwSQ0EgUG9zdGF6aW9uaSBTdmlsMQ0wCwYDVQQLDARBTlBSMR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbCdJbnRlcm5vMQswCQYDVQQGEwJJVDAeFw0xNjA4MDMwMDI3MjlaFw0yMjA4MDQwMDI3MjlaMIGZMRcwFQYDVQQDDA4wMzcwMDYtQ08tMDAwMDEdMBsGA1UECwwUUG9zdGF6aW9uaSBkaSBsYXZvcm8xMTAvBgNVBAsMKEFuYWdyYWZlIE5hemlvbmFsZSBQb3BvbGF6aW9uZSBSZXNpZGVudGUxHzAdBgNVBAoMFk1pbmlzdGVybyBkZWxsJ0ludGVybm8xCzAJBgNVBAYTAklUMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjbh0OARcFRS2r31mgD2+2N+GFhUpGYi5bP9sxLRi/CFqXku5S6IDBsvxPIqexeDzedqV7Ga2wvBdhDqq8UgNkxB8e4Dk2GrE7v+pJxD+maw4iqCfCPBM96DRMJ11C5GeA9cZhhdGN6iuDYmcq0+J9OyyZMikm9KzTNJoXmQnpIp4zoWxi7Vjb+hhsMFUiLcqQbKfSvGWkLgjZ10pQLFbaD1S8kviZC2kaVWq3oT4midTUQmi49wdA68OePY0MbDpBLE/kE+LEIFMHNvES8eCJ8jsRdVT/wMfyzYXnBtcZ6OLL4DCQ7wM0stSq2Ss1XTI9g24U/f0ZpXpYZ4vK4jbQwIDAQABo3UwczAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFAYLn8qh15mt1CLus4uxFJPIV5t+MBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBTl+1em0+MKh0gZHlfc0TgUrloXRTAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAIMWlIsON1EEiMNbtTk5x2S94cRksV0XraHNlJYxnSRA5Tu0/nacUbkXMJ9Wcp18WUo55ycWYSuJdUihqOks054ciplSZL13PwozvXCbpBimtM04B08H51eSJ+pnsdrRw0sU2oVXdrnkXkU+RZrELkxRKfUneivTrVPCMIzSJ+FvpVHc423SxhPCijl1ETRGJU2/7RnHXtOmfzFAcmW47CcAYKi/hS9JHKqYg+0Sq0fQalAeCp0/rmH8bqccmBdTp3+T0BbMZQrJiEyhA+cRc4HiqpRi3fNGVctijCVczz2SB4ZUj4B8BXMYD5wJFtg3y+vHU9FnuJqmTtAwqUzTSMlG/UgYXk1btbvmXw568Iw7/CtzdGxL/KQqzn9cxpU5Z9nAsdmpVBX4fDj7MxIGvG1x1pZieGSyBskNSFXbpitrY+fuxyqyDFXtnUCqO4W48YsMg7gUn9Om3/LTCMiud9CTSu7+NZp4DJitRIoZnrAYtkB7jit9T5a3XocisMcga5WVRCrYOjYiNn2Q1Wp4Q+7fBe1zHPnvcM0zMXUCqD//OJJVO0k8g6kYzthLRav2VHjoUfXYUkoLCO+I7uMAT+7Oi4JpEXRl1e3iMFq7vogqRi6l/JoKu8ja+XWV470yaH+Spu4kja15ihRW5Rotg4+V3KOpZwKnY2vfrJRB/KSu</wsse:BinarySecurityToken><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="SIG-d66d785c-4e93-4424-9ecd-35f1025e6da9"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#TS-34dfb9d4-0001-4455-862a-baf578eb0b6a"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="wsse soap"/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>LnZS0umdpD2aadOoUnq+MFCM5Ag=</ds:DigestValue></ds:Reference><ds:Reference URI="#_71d833f6-e900-485c-8143-a2c9bd41fd17"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList=""/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>wvxWglqWUq0y24g8dSBOJooYeic=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>YhxzByt+ig6zg1Hg4kS+IPHeymOTjfaex+6Mq+ayHfdKI2O8WoKQ0mhEkcD+J3Ir13yKZ2ikZeP+z/Rl9eS+meivRlI55XG+rNhOzqGohF6Jml8Ncp82k+qurbxc6ygpoZcFZbnad2A6Xyy0p3BhMVGbR0lOsoYN/ghzM75CPNJNScAvwdNYvY7vFySNjwy49zCgkvzt3JkJAZ7CKAsE4Y4OxYjD7Fbs/BqehD/cHd4iJ+qJYA7xPGiA+i1T5Fh/AfKHQYc8XMIltcKs+Qgn8Qjwh5jkkV55iQK9TV3TSJuXxiph+h+ghB4sYoD4FgoV6xTjFFt+ko/XrYHSiaHnNQ==</ds:SignatureValue><ds:KeyInfo Id="KI-7836db2a-bee2-4d54-aeed-ad1c0873580b"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="STR-438cc8f1-aee0-407b-8e73-058344bb1ff9"><wsse:Reference URI="#X509-690169d4-af3c-4e0c-97d6-eac5ec953395" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></ds:KeyInfo></ds:Signature></wsse:Security></SOAP-ENV:Header><soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="_71d833f6-e900-485c-8143-a2c9bd41fd17"><ns2:Richiesta5008 xmlns:ns2="http://sogei.it/ANPR/5000mutazione" xmlns:ns3="http://sogei.it/ANPR/rispostaComune"><testataRichiesta><idOperazioneComune>20170606144850497857497857F73B</idOperazioneComune><codMittente>037006</codMittente><codDestinatario>ANPR00</codDestinatario><operazioneRichiesta>5008</operazioneRichiesta><dataOraRichiesta>2017-06-06T14:48:50</dataOraRichiesta><tipoOperazione>C</tipoOperazione><protocolloComune>01APRVAR  2017000374</protocolloComune><dataProtocolloComune>2017-06-06</dataProtocolloComune><tipoInvio>TEST</tipoInvio><dataDecorrenza>2017-05-31</dataDecorrenza><nomeApplicativo>SIPO</nomeApplicativo><versioneApplicativo>1997-2015</versioneApplicativo><fornitoreApplicativo>SISTEMI INFORMATIVI</fornitoreApplicativo></testataRichiesta><generalitaPerRicerca><codiceFiscale><codFiscale>RMRMLZ93C61Z611P</codFiscale></codiceFiscale><cognome>RAMIREZ REMON</cognome><nome>MARIA LUZ</nome></generalitaPerRicerca><generalitaDaModificare><generalita><codiceFiscale><codFiscale>RMRMLZ93C61Z611P</codFiscale></codiceFiscale><cognome>RAMIREZ REMON</cognome><nome>MARIA LUZ</nome></generalita></generalitaDaModificare><statoCivile><statoCivile>3</statoCivile></statoCivile><vedovanza><datiMorteconiuge><dataEvento>2017-05-31</dataEvento><luogoEvento><comune><nomeComune>Bologna</nomeComune><codiceIstat>037006</codiceIstat><siglaProvinciaIstat>BO</siglaProvinciaIstat></comune></luogoEvento><attoEvento><comuneRegistrazione><nomeComune>Bologna</nomeComune><codiceIstat>037006</codiceIstat><siglaProvinciaIstat>BO</siglaProvinciaIstat></comuneRegistrazione><anno>2017</anno><parte>1</parte><numeroAtto>33</numeroAtto></attoEvento></datiMorteconiuge></vedovanza><datiControllo><tipoMutazione>1</tipoMutazione><tipoMutazione>13</tipoMutazione><gestioneCF>3</gestioneCF></datiControllo></ns2:Richiesta5008></soap:Body></soap:Envelope>

**Comment by gcarbonin** [comment]
Risolto
