### ISSUE TITLE
Cambio Indirizzo Intera Famigla - La residenza inserita risulta uguale a quella attuale (Errore EN388).

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#2030]
Buonasera,

abbiamo alcuni nostri clienti che, per via della gestione interna del loro viario, non gestiscono gli indirizzi fino all'interno, ma si fermano al civico e bis.
Quando si trovano a dover fare una variazione d'indirizzo per tutta la famiglia, e viene modificato solo l'unità abitativa ma non civico e bis, non è possibile effettuare questa variazione perchè inviando i dati in ANPR viene poi restituito l'errore EN388 - La residenza inserita risulta uguale a quella attuale.

Per le scissioni e aggregazioni, utilizzando il servizio 5005, abbiamo da tempo inserito la specifica FO=S e quindi in caso di indirizzo di provenienza e destinazione non abbiamo nessun problema.
Per la variazione d'indirizzo dell'intera famiglia invece, viene utilizzato il servizio 5001 e verificando i dati richiesti non è presente nessun campo per forzare questo invio.

Se però il cliente accede alla webapp, può effettuare senza alcun problema una variazione d'indirizzo per tutta la famiglia mantenendo l'indirizzo di destinazione uguale a quello di provenienza. 
Quindi se dalla webapp c'è la possibilità di farlo, dovrebbe essere possibile farlo anche tramite web services ma ci servirebbero indicazioni di come deve essere compilato il flusso dati.
Se invece è corretto che dal flusso dati questa operazione non sia consentita, non dovrebbe esserlo nemmeno dalla webapp.

Rimango in attesa di vostre indicazioni per capire se è necessaria una nostra modifica software o se i controlli presenti sui tracciati sono corretti e va verificato perchè sulla webapp è possibile effettuare questa modifica.

Grazie
Marco Sala

**Comment by rvinzani** [comment]
Che campo utilizzate per inserire l'unità abitativa?

**Comment by MarcoSalaPad** [comment]
Noi utilizziamo la mutazione 5001 ed abbiamo inserito nel campo tipo mutazione il valore 4 (Residenza Scheda). 
Inoltre abbiamo anche fatto una prova valorizzando il flag per famiglia coabitante
<presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante>
ed il risultato è sempre stato l'errore EN388.

Nella casistica esposta, come ci dobbiamo comportare?
Grazie

**Comment by rvinzani** [comment]
Dovreste utilizzare il tipo mutazione 9 - rettifica, integrazione indirizzo
