### ISSUE TITLE
Cambio indirizzo intera famiglia - Collegato a #2030

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#2031]
Buongiorno,

abbiamo fatto alcune prove con le indicazioni da voi fornite nella issues #2030 ma purtroppo l'operazione non va a buon fine.
DI seguito l'id dell'operazione, con data e ora di esecuzione:
2020-03-31 ore 10:33:47, idOperazioneANPR 24742799

Rimaniamo in attesa di istruzioni su come gestire la casistica spiegata nella issues originale.
Grazie

Marco Sala

**Comment by rvinzani** [comment]
Essendo una rettifica di un indirizzo e non  una mutazione di residenza è necessario indicare come data di decorrenza residenza la data dell'ultima residenza

**Comment by MarcoSalaPad** [comment]
Allora la causale di rettifica che ci avete indicato non è la soluzione corretta. Qui siamo nella casistiche di un cittadino che oggi chiede una variazione d'indirizzo all'interno dello stesso numero civico (perchè come spiegato nella precedente issues non vengono gestiti altri esponenti oltre al bis nella banca dati): il motivo è che probabilmente cambia il piano o semplicemente l'interno ma si vuole tenere traccia che alla data di oggi ci sia stata una mutazione di residenza.
Sulla webapp, se mi collego e faccio questo tipo di operazione, questa viene recepita con la data corretta e non con quella dell'ultima residenza: chiediamo quindi come va gestito il tracciato 5001 per una mutazione di residenza dove l'indirizzo è identico (per il tracciato 5005 ad esempio c'è il tag che permette la forzatura FO=S).
Grazie

**Comment by rvinzani** [comment]
Credo che questa situazione non sia prevista da ANPR. Ovvero, è previsto un cambio di residenza di una parte della famiglia allo stesso indirizzo perchè è previsto avere due nuclei familiari conviventi. Questo si ottiene con l'utilizzo del 5005 come ha giustamente detto. Ma non è prevista una mutazione di residenza di tutta la famiglia allo stesso indirizzo, neppure forzando l'operazione. L'unica possibilità è di aggiungere il dato o modificare uno dei dati previsti dal tracciato

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
