### ISSUE TITLE
Ambiente (Pre)Subentro ANPR - Indisponibilità dettaglio anomalie sui codici fiscali

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2033]
Comune di Ancona - A seguito dell'ultimo pre-subentro avvenuto in data 3-4-2020 il monitoraggio anomalie non mi consente di scaricare il file delle anomalie sui codici fiscali, anche se visualizza n. 8 errori. E' la prima volta che mi succede, negli altri pre-subentri sono sempre riuscita a scaricarlo regolarmente. Attendo vostre indicazioni. Grazie e saluti.

**Comment by amollicone1982** [comment]
Adesso sono disponibili
