### ISSUE TITLE
Ripristino decorrenza residenza 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2034]
COMUNE DI UMBERTIDE subentrato il 02/04/2020

Sul soggetto con ID ANPR 88365348 abbiamo ripristinato un cambio residenza ai dati del subentro poichè vi era una pratica di cambio abitazione con decorrenza errata. Nel fare tale operazione da Web app che andata a buon fine con ID OPERAZIONE nr 232444006 è stata inserita una data decorrenza errata anzichè 24/09/1979 è stata inserita 01/04/2020.

Ora la web app non permette di rettificare ulteriormente tale decorrenza. E' possibile forzarla in qualche maniera per permettere la registrazione corretta del successivo cambio abitazione in data 30/03/2020?

Grazie
Cinzia Girelli
GPI SPA

**Comment by ncapozzi** [comment]
Buonasera,
l'operazione 232444006 è una mutazione di residenza. Se la data di decorrenza è sbagliata occorre annullare l'operazione e rifarla alla data corretta.
Se invece dovete rettificare la data decorrenza trasmessa al subentro, dopo l'annullamento dovete effettuare la rettifica della data residenza trasmessa,
Se avete bisogno di ulteriori chiarimenti per favore indicate un recapito telefonico.

N. Capozzi

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, grazie ho effettuato l'annullo e poi la rettifica della data di residenza. La web app però non permette di cambiare la data di origine della convivenza in famiglia ID famiglia anpr = 49298586 che è rimasta 01/04/2020. 

Poichè dobbiamo iscrivere altre due persone su tale scheda famiglia con decorrenza residenza 30/03/2020 possiamo farlo senza problemi?

Il mio nr è 3346216774

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SPA

**Comment by ncapozzi** [comment]
La rettifica della data origine famiglia/convivenza trasmessa al subentro non è prevista. Le altre due persone sono state comunque correttamente iscritte in ANPR.

N. Capozzi
