### ISSUE TITLE
Persona Deceduta con coniuge sbagliato

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#2035]
Buongiorno,
scrivo per un chiarimento, abbiamo una persona deceduta, con relativo passaggio in ANPR dell'eliminazione per morte accertata, successivamente è arrivata la moglie a chiedere un estratto e da lì è stato notato che il nominativo della moglie era sbagliato. Adesso si vorrebbe risolvere in ANPR questo errore ma purtroppo appena provo a modificare il matrimonio mi dice:
Operazione non consentita su un soggetto deceduto

Provando a modificare invece alla moglie il matrimonio ci dà il seguente errore:
Alla data ******* il soggetto L****** A****** risulta gia' coniugato o unito civilmente con un altro soggetto (Codice: EN272)

Ho pesato che l'unica soluzione sia annullare il decesso, correggere il matrimonio e poi ricancellare per decesso. Questo è il procedimento giusto? Oppure c'è un metodo più veloce?
In attesa di cortese riscontro si porgono i migliori saluti.

**Comment by ncapozzi** [comment]
Buongiorno,
la soluzione di annullare il decesso, correggere il matrimonio e poi ricancellare per decesso sembrerebbe quella corretta ma se vuole indicare l'idsoggetto ANPR del cittadino cancellato prima facciamo una verifica sui dati.
N. Capozzi

**Comment by marcoLave** [comment]
L' ID del soggetto deceduto è 48919626
l'ID della moglie è 48919627

**Comment by ncapozzi** [comment]
Le confermo la soluzione che lei stesso ha individuato.
Resto in attesa di riscontro. Grazie

**Comment by ncapozzi** [comment]
Buongiorno.
Abbiamo verificato che le operazioni sono state correttamente effettuate. Pertanto si chiude la issue.

N. Capozzi
