### ISSUE TITLE
Rilascio certificato

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2036]
Buongiorno, in fase di rilascio di un certificato per un mio soggetto residente, viene restituito l'errore 
EN084 - La ricerca per cognome ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti

Accedendo alla webapp, ho notato che al soggetto in questione erano associati altri due codici fiscali: uno numerico e l'altro "canonico", ma quest'ultimo appartenente anche ad un altro soggetto anpr, per cui ritengo che questa associazione di codici fiscali vada cancellata

E' possibile chiedervi di effettuare questa disassociazione?
Grazie
Comune di Castelleone
Alessandra Bassani

**Comment by rvinzani** [comment]
Senza l'indicazione del soggetto è difficile dare una risposta al problema. In ogni caso, ha provato ad indicare, invece di solo cognome e nome anche l'idANPR o il codice fiscale per restringere la ricerca?

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega ri aprire una nuova issue che faccia riferimento a questa
