### ISSUE TITLE
 EN289 - La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#2037]
Comune di Velletri - produzione
per la persona con id ANPR 56171832, iscritta il 12-04-2019 in AIRE, con una operazione mutazione tutti i dati, si sta tentando di aggiornare lo stato civile a coniugato il 15/06/2013 , a seguito di trascrizione dall'estero del matrimonio, il legame soggetto ha data 12-04-2019 e la data della priatica di mutazione 17-03-2020 , come posso risolvere l'errore bloccante? 
grazie

**Comment by asqueglia** [comment]
Buongiorno, da una prima analisi risulta che il soggetto indicato presenta un matrimonio registrato con data 31/05/1960 e con cessazione registrata con data 17/03/2020. Tali informazioni risultano essere state aggiornate, l'ultima volta, con una operazione di mutazione trasmessa il 02-APR-20 e con data decorrenza 12-APR-19. 
Se il vostro intento è inserire un ulteriore matrimonio del soggetto con data 12-04-2019, non è al momento consentito in quanto il precedente matrimonio risulta cessato in  data 17/03/2020, per cui si avrebbe una poligamia che al momento non è gestita dal sistema ANPR.
Abbiamo riportato l'analisi della situazione attuale non avendo a disposizione l'idoperazione con cui avete ricevuto l'errore indicato nella issue; se lo avete potete gentilmente comunicarlo in modo che sia per noi più semplice l'analisi e per poter confermare quanto scritto.

**Comment by ale-magna** [comment]
Salve,
l'ultimo idOperazioneANPR 233711543 che ha scatenato il problema.
il nostro intento è ricostruire gli stati civili della persona che è stata iscritta in aire da irreperibilità,
coniugato 31/05/1960
divorziato  23/11/2010
coniugato 15/06/2013 (questo è l'informazione che non riusciamo ad inserire)
grazie
--

**Comment by asqueglia** [comment]
Possiamo confermare che il problema dipende dal fatto che il divorzio del soggetto indicato risulta registrato con data 17/03/2020 (coincidente con la data formazione dell'atto di cessazione trasmesso). Nel caso in cui sia errata questa data dovreste procedere ad una nuova mutazione dei dati del divorzio e trasmettere la data corretta di cessazione 23/11/2010, come indicato, prima di procedere alla registrazione del nuovo matrimonio. Ribadiamo infatti che il sistema ANPR non supporta le poligamie, pertanto un nuovo matrimonio del soggetto non può essere acquisito se la data risulta inferiore al divorzio.


Il Ministero dell’Interno è al corrente del problema; si consiglia la registrazione soltanto sul proprio gestionale.

**Comment by asqueglia** [comment]
Chiudiamo pertanto la issue.
In caso di ulteriori problemi si prega di aprirne un'altra facendo riferimento a questa stessa.
