### ISSUE TITLE
[webapp] scarico per motivata richiesta fallito

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2039]
Ambiente di test
abbiamo chiesto in data 11/3 e 13/3 gli scarichi per motivata richiesta tramite la funzione "Download dati ANPR del comune" del menù "Amministrazione". Dopo qualche giorno sono passati nello stato "COMPLETATA CON ESITO NEGATIVO". 
Come mai ? Avremmo bisogno dello scarico per alcuni tests di coerenza.

Grazie

**Comment by mttfranci** [comment]
La Versione 5.7.0 (2020-03-31) dovrebbe risolvere il problema, ma non avevamo rielaborato le richieste fallite in precedenza (trattandosi di operazioni onerose).

Dalle date indicate, ci sembra che le richieste dovrebbero essere quelle con id 24666580 e 24671662? Corretto?

Ora dovrebbero essere entrambe elaborate. Potete verificare?
Grazie

**Comment by busaster** [comment]
Grazie. Le richieste risultano ora elaborate, però se provo a scaricare il file da "Utilità e notifiche ->download file" ottengo l'errore "Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi". Riproverò fra una mezz'ora.

**Comment by mttfranci** [comment]
@busaster ci risulta che in effetti c'era un problema temporaneo che ora dovrebbe essere stato superato. potete riprovare?

**Comment by busaster** [comment]
Scarico acquisito correttamente. Grazie

**Comment by mttfranci** [comment]
Prego, buon lavoro
