### ISSUE TITLE
Riutilizzo codici ANPR

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#204]
Corbetta, Ambiente di produzione.

Buongiorno, abbiamo registrato una iscrizione da comune non subentrato di 3 persone, successivamente per una di queste persone è stato eseguito il ripristino in quanto non residente nel comune di provenienza e questa persona dovrà quindi essere nuovamente iscritta come iscrizione dall'estero con un'altra pratica.
La domanda è: per questa persona si può/deve recuperare il codice ANPR dato nella prima iscrizione ma successivamente annullata oppure quel codice non ha importanza e ne verrà assegnato un altro?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
E' utile mantenere lo stesso ID che deve essere indicato nella nuova iscrizione
