### ISSUE TITLE
Errore EN531

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2040]
Comune di Modena - Ambiente di produzione

Buongiorno,
dobbiamo iscrivere il soggetto con idANPR 81698357 proveniente da Torino ma abbiamo questo errore:

codiceErroreAnomalia: EN531
tipoErroreAnomalia: E
testoErroreAnomalia: Operazione non consentita: per il soggetto esiste un procedimento aperto 
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-11 10:23:54 , idOperazioneANPR 234498434
codiceErroreAnomalia: EN395

Abbiamo contattato più volte Torino senza esito, per cortesia potete aiutarci a sbloccare?
Sarebbe inoltre possibile visualizzare tutti i procedimenti aperti sul soggetto e non solo quelli del proprio comune? Questo consentirebbe di essere più precisi nella richiesta di chiusura fatta agli altri enti.

Grazie, saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buongiorno,
stiamo provando a contattare Torino. Vi facciamo sapere.

N. Capozzi

**Comment by ncapozzi** [comment]
Come comunicato per le vie brevi, il Comune di Torino è stato informato della necessità di chiudere il Procedimento Amministrativo.

Stiamo già procedendo con la modifica del controllo EN531 in modo che nel messaggio di errore vengano restituiti l'id del procedimento e il Comune di riferimento.

N. Capozzi
