### ISSUE TITLE
[5008] Mutazione Dati

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#2041]
Ambiente di Pre-Subentro
Comune di Tresignana

Buongiorno,
diversi soggetti risultano nati / coniugati / .. a Tresigallo con data evento antecedente
al 26/12/1961, data di istituzione ufficiale dello stesso.
Il dato è stato così registrato negli archivi di Stato Civile sulla base di disposizioni dell'epoca documentate da circolare prefettizia datata 18/12/1962. 
Ai fini del subentro il tutto non è bloccante ma lo sarà, a subentro avvenuto, nel caso di mutazione dati su tali soggetti.
Si veda ad esempio IdOperazioneANPR 16948691.
Come dovrà trattare tali casi l'Ente?

Grazie
ChristianO ADS

**Comment by ncapozzi** [comment]
Buonasera,
potete riprovare ad eseguire la mutazione tutti i dati 5008 in pre-subentro. Le segnalazioni ricevute dovrebbero essere solo warning del tipo "Comune non valido alla data", quindi non bloccanti.

Per quanto riguarda la validazione del CF per i cittadini che nell'atto di nascita risultano nati a Tresigallo (FE) prima dell'istituzione del comune stesso, si suggerisce di attenersi strettamente a quanto riportato nel documento https://www.anpr.interno.it/portale/documents/20182/239162/Risoluzione+disallineamenti+con+l%27Agenzia+delle+Entrate+11_02_2019.pdf/2e4e13c2-c606-43c9-82cb-f2362200db4e?version=1.0

Si resta in attesa di riscontro

N. Capozzi

**Comment by ncapozzi** [comment]
Per quanto riguarda l'attività di bonifica propedeutica al subentro con particolare riferimento alle anomalie riscontrate sul luogo di nascita si rimanda anche alla seguente Circolare del Ministero dell'Interno
https://dait.interno.gov.it/servizi-demografici/circolari/circolare-n15-del-2-gennaio-2020

**Comment by ncapozzi** [comment]
Non avendo ricevuto ulteriori commenti si chiude la issue.

Saluti
N. Capozzi
