### ISSUE TITLE
en531 - Operazione non consentita: per il soggetto esiste un procedimento aperto

### ISSUE THREAD

**Issue by Leo-Scandicci** [italia/anpr#2043]
Comune di Scandicci,
per una mutazione residenza di una cittadina dal comune di Lastra a Signa, ho l'errore in oggetto ,
all'altro comune , contattato da me, non risultano procedimenti aperti,
come possiamo procedere?
idanpr del cittadino: 40699199
danpr del cittadino2: 37834178
errore nell'operazione:
Errore | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-15 10:00:38 , idOperazioneANPR 235585623  
Errore | EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto
per favore inviare risposta anche a uffdemog@comune.scandicci.fi.it
grazie
Leonardo Carpini

**Comment by ncapozzi** [comment]
Buongiorno,
effettivamente risulta un procedimento aperto per cittadino2 dal Comune di Lastra e Signa. Potete contattarli voi oppure fornire un riferimento di Lastra e Signa?

Grazie
N. Capozzi

**Comment by Leo-Scandicci** [comment]
Ho spidito a Lastra a Signa la Vostra risposta però sarebbe gradito se le contattate anche Voi al 055/8743219 Marco CINI oppure all'email "anagrafe" anagrafe@comune.lastra-a-signa.fi.it
Grazie

----- Messaggio originale -----

Da: "ncapozzi" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "Leo-Scandicci" <l.carpini@comune.scandicci.fi.it>, "Author" <author@noreply.github.com> 
Inviato: Mercoledì, 15 aprile 2020 12:26:07 
Oggetto: Re: [italia/anpr] en531 - Operazione non consentita: per il soggetto esiste un procedimento aperto (#2043) 



Buongiorno, 
effettivamente risulta un procedimento aperto per cittadino2 dal Comune di Lastra e Signa. Potete contattarli voi oppure fornire un riferimento di Lastra e Signa? 
Grazie 
N. Capozzi

**Comment by ncapozzi** [comment]
Lastra a Signa ha chiuso il procedimento. Potete provare nuovamente la mutazione di residenza per favore?

**Comment by Leo-Scandicci** [comment]
conclusione pratica erfettamente riuscita 
Grazie 

----- Messaggio originale -----

Da: "ncapozzi" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "Leo-Scandicci" <l.carpini@comune.scandicci.fi.it>, "Author" <author@noreply.github.com> 
Inviato: Mercoledì, 15 aprile 2020 13:14:58 
Oggetto: Re: [italia/anpr] en531 - Operazione non consentita: per il soggetto esiste un procedimento aperto (#2043) 





Lastra a Signa ha chiuso il procedimento. Potete provare nuovamente la mutazione di residenza per favore?

**Comment by ncapozzi** [comment]
Perfetto

Saluti
