### ISSUE TITLE
Come sbloccare una smartcard Anpr

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2044]
Buongiorno,
come è possibile sbloccare la smartcard per accedere ad Anpr, smartcard che risulta bloccata per errata digitazione del PIN?

Grazie,
cordiali saluti.

**Comment by Leonforte** [comment]
Buongiorno, 
occorre utilizzare l'applicazione IDProtect Monitor e il PUK (metà presente nella lettera di accompagno alla smart card e l'altra metà nella mail di attivazione.
Le allego la procedura, saluti
[Procedura sblocco PIN.pdf](https://github.com/italia/anpr/files/4485814/Procedura.sblocco.PIN.pdf)

**Comment by Eduardo1977** [comment]
Buongiorno, chiedo scusa, avrei bisogno di supporto per lo stesso problema al Comune di Bistagno (AL) cod. 006017.
In questo caso, però è stato smarrito il PUK (non troviamo la lettera di accompagno alla smart card). 
Accedendo tramite ALS nella gestione smartCard abbiamo effettuato "invia pin/puk", ma sulla mail è arrivata solo la seconda metà. La prima parte verrà recapitata successivamente?
La smartCard interessata è quella della Dott.ssa Garbarino.
Riferimenti:
anagrafe@comune.bistagno.al.it
0144 79 106   int.1

Grazie

**Comment by Leonforte** [comment]
Quanto richiesto è stato invito all'indirizzo anagrafe@comune.bistagno.al.it ,  buon lavoro, saluti

**Comment by Eduardo1977** [comment]
Grazie, gentilissimi. Farò controllare. Saluti
