### ISSUE TITLE
[1001] ES043 in iscrizione per nascita

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2045]
Ambiente di produzione, comune di Scarperia e San Piero
Iscrizione per nascita con il servizio 1001 di soggetto che entra come nipote in una famiglia in cui è presente anche la madre. madre che è specificata nella richiesta di iscrizione.

Al salvataggio otteniamo l'errore in oggetto "ES043 : Indicare i dati relativi alla maternita' quando attribuzioneFamiglia e' 1=dei genitori o 3=della madre" (id operazione ANPR 236241365)

Come mai ?

**Comment by ncapozzi** [comment]
Buongiorno,
sembrerebbe che il problema nasca dal fatto che la mamma è senza cognome e noi lo richiediamo obbligatoriamente nel caso di iscrizione per nascita. Potete per favore verificare che effettivamente la mamma non ha il cognome?

N. Capozzi

**Comment by busaster** [comment]
Confermo che la madre è senza cognome

**Comment by busaster** [comment]
Il comune è bloccato e ha necessità di effettuare l'iscrizione. Quando pensate sarà disponibile la correzione del problema ?

**Comment by ncapozzi** [comment]
Buongiorno,
è stato verificato che a seguito del rilascio della patch 5,7,2 il bambino è stato correttamente registrato in ANPR.

N. Capozzi
