### ISSUE TITLE
Rettifica dati matrimonio (rettifica marito e moglie) errore EN572 e  EN272

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#2046]
Buongiorno,
scrivo in merito ad una modifica che devo effettuare in quanto due soggetti non risultano coniugati insieme. 
Gli errori riportati sono i seguenti:
Alla data 25-10-1971 il soggetto ********** risulta gia' coniugato o unito civilmente con un altro soggetto (Codice: EN272)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-20 10:45:49 , idOperazioneANPR 237514384 (Codice: EN527)

Ho notato che quando effettuo la variazione mi dice che non risulta il Comune di matrimonio e ho dovuto inserirlo nuovamente. Quando vado ad interrogarlo in consultazione però il Comune del Matrimonio risulta.
ID anpr: 48911900
ID anpr: 48911902
In attesa di cortese riscontro si porgono i migliori saluti.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato la situazione. All'atto del subentro sono stati inviati per entrambi i soggetti i matrimoni con relativi coniugi con codice fiscale numerico (forse provvisorio) ma comunque differente da quello che al momento hanno i soggetti. Inoltre il soggetto

**Comment by MMaurizio** [comment]
Buonasera, stesso problema "id operazione anpr 372909240". Sentito il Comune di Firenze che per primo ha variato la mutazione dello stato civile sul soggetto idanpr 32937765 spiegando che forse è stata inserito un nuovo soggetto anzichè ricercare il coniuge iscritto alla mia aire. Impossibilità di concludere l'operazione con apertura warning rosso con codice EN572 ed EN 272  con la quale si avverte che lo sposo è già coniugato con altra persona ma uguali generalità. E' corretto richiedere Firenze di mutare il coniuge collegando il soggetto con le stesse generalità ma iscritto all'aire del mio Comune? Quali alternative?
Ringrazio per la collaborazione e le indicazioni utili per la soluzione.
Cordiali saluti
