### ISSUE TITLE
mutazione matrimonio

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2049]
Dovremmo effettuare una mutazione di matrimonio di  un cittadino [esempio idanpr: 88272344 del comune cod. istat 076063] che in "generalità stato civile"  risulta divorziato ma nel riepilogo delle movimentazioni ha solo i dati del matrimonio e non i dati della cessazione/annullamento dello stesso. 
Attualmente la persona dovrebbe risposarsi, ma il messaggio che riceviamo è che alla data del matrimonio la persona risulta essere sposata con un altro soggetto. Come procedere in casi come questo?

**Comment by rvinzani** [comment]
I dati relativi allo stato civile e quelli relativi ai documenti e gli estremi che attestano questo stato hanno gestioni diverse e sono indipendenti tra di loro. Non è possibile acquisire i dati di un secondo matrimonio se non ho acquisito i dati del suo divorzio/annullamento, questo nonostante lo stato civile risulti correttamente "divorziato". E' quindi necessario acquisire i dati del divorzio (estremi sentenza / atto stato civile) e poi acquisire i dati del nuovo matrimonio. Le date devono essere ovviamente coerenti tra di loro

**Comment by carminepat** [comment]
Come risolviamo nel caso in cui il cittadino non ha ne sentenza ne atto (il cittadino non sa dove reperire i dati o altro) come si procede?

**Comment by rvinzani** [comment]
Ho dato la soluzione tecnica. In pratica credo che il cittadino dovrebbe rivolgersi al comune dove è registrato il suo matrimonio ed il suo divorzio o se straniero al consolato...

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprirne un'altra che faccia riferimento a questa
