### ISSUE TITLE
Rigetto di mutazione di residenza con provenienza modificata

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2050]
Ambiente di test.

In un altro comune subentrato esiste una famiglia composta da 4 elementi che chiamiamo A,B,C,D.
Nel nostro comune apriamo una pratica di iscrizione per il soggetto A e lo iscriviamo con una mutazione 5005 ( id ANPR 24783915).  
Successivamente con un'altra pratica ed un diverso indirizzo di destinazione iscriviamo i soggetto B,C,D con una mutazione 5001 (id ANPR 24783935).
Fallisce però l'accertamento della pratica del soggetto A e la dobbiamo rigettare. Il servizio 5012 va in errore  "EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa". 
Questo effettivamente ha senso perché la famiglia in cui lo vorremmo ripristinare si è nel frattempo spostata.
Abbiamo quindi perfezionato il rigetto con una "cancellazione per ripristino posizione precedente" che ha funzionato (id ANPR 24784355), però il comune di provenienza non ha mai ricevuto una notifica per poter re-iscrivere il soggetto.

Abbiamo seguito la strada corretta ?

**Comment by frmariani** [comment]
Avete seguito la strada corretta, ma non è previsto l'invio di una notifica nel caso di cancellazione per altri motivi anche se per ripristino posizione precedente; la comunicazione in questi casi è diretta tra i Comuni.
E' in fase di studio la possibilità di annullare una mutazione di residenza per accertamento negativo anche nel caso in cui non sia più disponibile la famiglia d'origine.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
