### ISSUE TITLE
[6001] Firma certificati rilasciati dal Portale

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#2051]
Buongiorno,
Il comune di Rho intende rilasciare dei certificati dal portale cittadino, questi certificati vengono richiesti tramite il servizio 6001 e successivamente firmati e timbrati digitalmente.
Il certificato viene richiesto indicando nei dati di controllo il valore 2 come emissione e nel servizio viene indicato correttamente nei campi cognomeUffAnagrafe e nomeUffAnagrafe il nome del firmatario del certificato che corrisponde con il possessore della firma digitale, cioè il responsabile dei servizi demografici.
Il problema è che il certificato da ANPR viene restituito con l'indicazione che il firmatario è il Sindaco del Comune e questo differisce dalla firma digitale che viene apposta invece sul certificato. E' possibile configurare lato WebApp il firmatario del certificato Internet o come si può risolvere il problema?

**Comment by Eduardo1977** [comment]
Buongiorno,
a tal proposito vorrei chiedere se è corretto che nel certificato emesso online (servizio 6001) venga riportato "Il Sindaco del Comune di ..." anche se si tratta di Commissario Prefettizio (come correttamente impostatato nella sezione "Amministrazione" relativa ai dati del Sindaco/Commissario tramite il controllo radiobutton).
Grazie

Comune di Grumo Appula

**Comment by rvinzani** [comment]
La richiesta al servizio 6001 per “**emissione on line**” è stato previsto per un futuro utilizzo che prevede l’apposizione del sigillo del Ministero dell’Interno (soggetto giuridico), in quanto è direttamente il sistema ANPR ad emettere il certificato.
Il suo attuale utilizzo non consente la sostituzione di tale sigillo con la firma digitale dell’Ufficiale di anagrafe. Tale tipologia di certificato è quindi rilasciabile senza però alcuna apposizione di firme digitali dell’ufficiale di anagrafe.

Per il rilascio attuale di certificati on line dal portale del comune, in attesa della soluzione definitiva sopra esposta, si consiglia di richiedere il tipo emissione 1 (da sportello) in cui la firma autografa dell’ufficiale di anagrafe che veicola la richiesta ad ANPR può essere sostituita, temporaneamente, con quella digitale, in quanto si configura come una “**richiesta on line**”, che verrà espletata in backoffice dall’ufficiale di anagrafe, il quale vi apporrà la sua firma digitale personale, rendendo disponibile il certificato al cittadino direttamente sul portale.

**Comment by LucaBonini64** [comment]
La ringrazio per la risposta, però se viene indicato il tipo emissione=1 abbiamo il problema dei diritti di segreteria che diventano obbligatori per alcuni motivi di esenzione, mentre moltissimi comuni hanno deliberato di non richiedere diritti di segreteria per i certificati emessi dal Portale.
Esiste un modo anche con il tipo emissione=1 di poter impostare a 0 i diritti di segreteria?

**Comment by rvinzani** [comment]
Nell'applicazione Web , in amministrazione, gestione dati del comune, potete impostare, come parametri  per l'emissione dei certificati l'esenzione dei diritti di segreteria. Questo consente, di indicarli laddove necessario
