### ISSUE TITLE
Rettifica famiglia post subentro 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2052]
Buongiorno, 
per il soggetto con IDANPR 79457953 ID ANPR FAMIGLIA 49298954 subentrato in data 02/04/2020 con iscrizione art5 preliminare, oggi dopo accertamento dei vigili il comune segnala che il soggetto non è da iscrivere nella suddetta famiglia ma dovrebbe costituire una nuova famiglia. Com'è possibile rettificare tale iscrizione? Dal menù rettifiche dati di subentro non è possibile agire sulla scheda famiglia. 
Ringrazio e resto a disposizione per ulteriori informazioni. 

Cinzia Girelli
GPI SPA
Cell 3346216774

**Comment by frmariani** [comment]
Lo spostamento da una famiglia all'altra è possibile soltanto con il cambio di residenza; nel vostro caso, il cittadino è stato aggiunto in ANPR con il subentro del comune, pertanto, oltre al cambio di residenza,  l'unica operazione possibile è la cancellazione per altri motivi e la re-iscrizione in una nuova famiglia.

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, abbiamo fatto la Cancellazione per altri motivi da Web app
tutto ok, ma riprovando a reiscriverlo con iscrizione per altri motivi dopo
aver richiamato il soggetto non c'è la possibilità di procedere. Il
soggetto ora risulta cancellato.

Come lo reiscriviamo?

Grazie
Cordiali saluti

       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 27 apr 2020 alle ore 11:59 frmariani <notifications@github.com>
ha scritto:

**Comment by frmariani** [comment]
non dovete richiamare il soggetto, ma inserire tutti i dati come se fosse una nuova iscrizione; nella pagina d'inserimento dei dati anagrafici, dovete indicare anche l'idanpr del soggetto precedentemente assegnato dal sistema

**Comment by CGIRELLI-HUB** [comment]
Ok grazie, domani mattina proveremo e le saprò dire se tutto andrà a posto
così da chiudere il ticket.
Grazie ancora per la celere risposta.

Cordiali saluti


       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 27 apr 2020 alle ore 14:37 frmariani <notifications@github.com>
ha scritto:

**Comment by CGIRELLI-HUB** [comment]
Buonasera abbiamo effettuato l'iscrizione, l'unica cosa che non siamo
riusciti a fare è l'inserimento dell' ID famiglia del comune.
Per il resto anche nel gestionale gli ID ANPR del soggetto e della nuova
famiglia creata in Web App sono allineati.

Grazie
Cordiali saluti

       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 27 apr 2020 alle ore 14:37 frmariani <notifications@github.com>
ha scritto:

**Comment by frmariani** [comment]
per la modifica dell'identificativo comunale della famiglia dalla web app, potete utilizzare la seguente procedura:
dai servizi di Registrazione>Mutazione Famiglia/Convivenza>Tipo mutazione:Motivo Famiglia/Specie Convivenza

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
