### ISSUE TITLE
Errore EN403 in allineamento dati AE -> ANPR

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#2053]
Arianna Nozzoli Comune di Prato in produzione

Andando su webapp ANPR a fare "Risoluzione disallineamenti con agenzia entrate" riceviamo l'errore EN403 codice operazione 240356568. Il cittadino ha l'anomalia da subentro EC030 come possiamo risolvere? Grazie

**Comment by ncapozzi** [comment]
Buongiorno, può indicare un recapito telefonico per favore?

**Comment by ncapozzi** [comment]
E' stato contattato l'utente e fornita l'assistenza richiesta per l'aggiornamento luogo di nascita.

Per problematiche puntuali che richiedono un contatto telefonico si suggerisce di aprire un ticket attraverso il numero verde dedicato.

Grazie

N. Capozzi
