### ISSUE TITLE
ws [A006] - errore data decorrenza residenza

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2054]
Buon giorno, 
il comune di Massafra si è trovato a dover annullare delle pratiche di iscrizione AIRE a causa della data di decorrenza errata inserita in un primo momento; successivamente le pratiche sono state ricreate con la corretta data di decorrenza e trasmesse in ANPR.
Il comune però ci segnala un errore che non consente la trasmissione di una di queste pratiche, si tratta di quella riguardante l'individuo con ID ANPR 72400824, che dopo l'annullamento di una prima pratica di espatrio risulta adesso nuovamente residente a Massafra con decorrenza 12/12/2017. 
Il comune pertanto ha creato una nuova pratica (id operazione comune 07301520200428196) con cui comunica l'espatrio del cittadino a KIRCHHEIM UNTER TECK (Germania) con decorrenza 24/02/2020, utilizzando il WS in oggetto, ma in risposta ottiene l'errore "La data di decorrenza della residenza non può essere antecedente a quella già registrata". Il cittadino però non ha altre operazioni registrate all'infuori della pratica "originale" di espatrio e della relativa operazione di annullamento, andata a buon fine dato che il soggetto risulta attualmente residente a Massafra, per cui non riusciamo a capire quale sia l'errore e come procedere con la registrazione.
L'operazione è stata effettuata oggi 28/04/2020.
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by ncapozzi** [comment]
Buonasera,
il problema deriva dal fatto che nella richiesta è indicato che il cittadino viene attribuito ad una NUOVA famiglia AIRE (attribuzioneFamigliaAIRE>2)  ma la famiglia FE0000943 è già presente in ANPR per il vostro comune (id 48495530).
Verificate quale dei due dati deve essere modificato, l'identificativo FE0000943 oppure attribuzioneFamigliaAIRE (deve essere 1 = già esistente?)


N. Capozzi

N. Capozzi
