### ISSUE TITLE
[A00*] e [1014] - Internal Server Error

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2055]
Comune di Torino - Ambiente di PRODUZIONE

Buonasera,
dal 23 aprile abbiamo riscontrato 11 servizi KO per SoapFault Internal Server Error. Possiamo chiedervi una verifica a riguardo? 

Non avendo avuto in risposta l'id operazione anpr, possiamo fornirvi il servizio e l'orario di invio della richiesta. 
Ve ne indichiamo 1 per ogni tipologia di servizio:

A002 - <dataOraRichiesta>2020-04-28T14:08:11.259+02:00</dataOraRichiesta>
A006 - <dataOraRichiesta>2020-04-28T08:56:28.855+02:00</dataOraRichiesta>
A001 - <dataOraRichiesta>2020-04-27T15:01:44.723+02:00</dataOraRichiesta>
1014 - <dataOraRichiesta>2020-04-27T12:59:15.620+02:00</dataOraRichiesta>

Rimaniamo a disposizione nel caso in cui vi servissero più informazioni.

Cordialmente,
Chiara Leanza

**Comment by gife67** [comment]
Buonasera,
stiamo indagando su un eventuale problema della famiglia di servizi A000, che si verifica saltuariamente. Se cortesemente potete effettuare nuovamente le stesse transazioni che vi sono andate male, anche con lo stesso IdOperazioneComune se preferite, perchè con molta probabilità avranno esito positivo. Comunque dal primo pomeriggio abbiamo ripubblicato il servizio, quindi vi chiediamo cortesemente di darci riscontro di eventuali problemi di questo tipo. Per il 1014 ci occorre ulteriore tempo per verificare.
Grazie mille per la collaborazione.

**Comment by gife67** [comment]
Per quanto riguarda il 1014 dovrebbe essere conseguenza di un problema momentaneo sull'infrastruttura di rete. Quindi ripetendo la stessa identica operazione, a meno di altre tipologie di problema, questa andrà sicuramente a buon fine.
Attendo un vostro riscontro su entrambi i tipi di problematica.
Grazie mille per la collaborazione.
Cordiali saluti
Giuseppe Ferraro

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno,
purtroppo al momento non possiamo fare il reinvio dei servizi da noi citati precedentemente, ma possiamo monitorare la situazione. Vi forniremo un riscontro come da voi richiesto.
Vi ringraziamo per le verifiche svolte.
Cordialmente,
Chiara Leanza

**Comment by gife67** [comment]
Buongiorno,
per il momento chiudo questa issue e nel caso fosse necessario potete riaprirne una nuova collegandovi a questa.
Grazie mille per collaborazione,
Buona giornata
