### ISSUE TITLE
Problemi con date su cambio parentela

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#2056]
Buongiorno,
ambiente di produzione.
Id Operazione ANPR: 241360926

In data 28/04/2020 la persona oggetto della Comunicazione di cui sopra si aggrega ad un'altra famiglia, creata nello stesso giorno, da un altro soggetto. 
Il Comune non riesce a rettificare le parentele in quanto viene restituito come errore: 
"La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.".
Verificando le varie comunicazioni e i dati dal portale ANPR, tutte le date relative ai due soggetti e alla famiglia sembrano essere coerenti, come possiamo gestire la cosa?
Ringraziandovi anticipatamente.
Saluti

**Comment by frmariani** [comment]
c'è stato un piccolo problema prontamente risolto; potete riprovare l'operazione per favore ?

**Comment by SAlberto** [comment]
Buongiorno, 
tutte le segnalazioni per errori simili a quello segnalato sono state risolte.
Grazie per la collaborazione.
Buona giornata.
