### ISSUE TITLE
Emissione di certificati su moduli standard multilingue

### ISSUE THREAD

**Issue by malcesinec** [italia/anpr#2057]
Buongiorno,
si chiede se possibile emettere direttamente dal sistema i certificati redatti sui moduli standard multilingue di cui al Regolamento (UE) n. 2016/1191 senza doverli ogni volta compilare manualmente.
Esempio: emissione certificato di matrimonio in lingua per cittadini della Repubblica Ceca.
Stiamo provando l'ambiente test in quanto ancora in pre-subentro.
Uffici demografici - Comune di Malcesine

**Comment by malcesinec** [comment]
The original message was received at Thu, 06 May 2021 15:32:52 +0200

  ----- The following addresses had permanent fatal errors -----
***@***.***>

  ----- Transcript of session follows -----
<<< 554 5.7.1 Message cannot be accepted, spam rejection

**Comment by vlavorini** [comment]
Buongiorno,

   vedo che questo issue è chiuso da tempo, ma il certificato di nascita che ho provato a scaricare NON rispetta lo standard plurilingue.

Sbaglio qualcosa io?

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Emissione di certificati su moduli standard multilingue (#2057)" inviata il
02/06/2022 07:11:42.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by malcesinec** [comment]
The original message was received at Thu, 02 Jun 2022 10:06:38 +0200

  ----- The following addresses had permanent fatal errors -----
***@***.***>

  ----- Transcript of session follows -----
<<< 554 5.7.1 Message cannot be accepted, spam rejection

**Comment by FilippoPapi** [comment]
salve i certificati anpr sono multilingue (tedesco e sloveno) solo per i cittadini residenti nei comuni in cui vige la doppia lingua
un saluto

**Comment by malcesinec** [comment]
The original message was received at Mon, 06 Jun 2022 14:34:35 +0200

  ----- The following addresses had permanent fatal errors -----
***@***.***>

  ----- Transcript of session follows -----
<<< 554 5.7.1 Message cannot be accepted, spam rejection

**Comment by malcesinec** [comment]
The original message was received at Thu, 02 Jun 2022 07:13:38 +0200

  ----- The following addresses had permanent fatal errors -----
***@***.***>

  ----- Transcript of session follows -----
<<< 554 5.7.1 Message cannot be accepted, spam rejection
