### ISSUE TITLE
web-service - msg. "Rejected by policy. (from client)"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2058]
ambiente di PRODUZIONE - comune di BAGHERIA (082006)

un operatore che accede senza problemi alla web-app, non riesce ad utilizzare i web-service a causa di questi errori:
29/04/2020 15:43:38 - [http-apr-0.0.0.0-8085-exec-7] - [anpr] [ERROR] ERRORE ANPR
javax.xml.ws.soap.SOAPFaultException: Rejected by policy. (from client)

l'ultimo tentativo che è stato eseguito (ws 3002) aveva come idOperazioneComune 2020305409

potete verificare se c'è qualche problema nella configurazione di questo utente in particolare?
altri utenti riescono a lavorare correttamente anche via web-service.

se avete bisogno di maggiori informazioni, sono reperibile alla mia mail personale

grazie
Alessandro Monopoli ADS

**Comment by gife67** [comment]
Buonasera,
l'utenza che sta avendo il problema presenta una lettera errata nel suo CF. Dovreste verificare  l'utenza utilizzata nell'accesso ai WS. Nella 4a lettera del CF c'è lettera M scambiata con la N.
Questo è sicuramente il problema.

**Comment by AMonopoliADS** [comment]
ok. grazie Giuseppe.

ho verificato che in effetti mettendo la 'N' al posto della 'M' le chiamate al ws vanno a buon fine.
però a questo punto la questione diventa che il codice fiscale autorizzato non è corretto rispetto alle generalità dell'operatore, che invece, nel suo codice fiscale ufficiale ha una 'M'.

magari non è un problema e quindi possiamo anche lasciare così.
diversamente attendiamo le indicazioni per mettere in cliente in condizioni di correggere questa anomalia.

grazie.
Alessandro

**Comment by gife67** [comment]
Buongiorno,
nella fase di censimento iniziale il CF non è verificato, quindi come in questo caso è stata creata l’utenza e la smart card con quello errato.
Nulla osta all'accesso sia web che ws con il CF errato, così come è possibile tramite console inserire un nuovo utente con CF corretto richiedendo una nuova smart card.
Cordialmente,
Giuseppe
