### ISSUE TITLE
ANPR accesso WebAPPlication in sola consultazione ANPR per Procure della Repubblica (Tribunali) o altri Enti per motivi istituzionali.

### ISSUE THREAD

**Issue by cedmottadilivenza** [italia/anpr#2059]
Buongiorno ,
abbiamo la Procura della Repubblica presso il Tribunale che ci chiede con urgenza di poter effettuare visure anagrafiche, siamo in ANPR dal 2018,
chiedo se si conosce se ANPR ha un canale accesso in sola consultazione ad altre PA per funzioni istituzionali o di ordine pubblico via WebAPPlication, come fa per i comuni?
Eventualmente , queste istituzioni a chi dovrebbero richiedere la Smartcard ANPR (per accesso in WebApplication ) per abilitare i loro operatori ?
Le colleghe dell'anagrafe del Comune di mi dicono che accedono in consultazione via WebApp a tutti i 6000 comuni già presenti in ANPR.

Forse alla Prefettura ?
Qualcuno ha riscontro qualche riscontro reale ?

Grazie in anticipo.

**Comment by FilippoPapi** [comment]
Buonasera, per poter accedere ad ANPR le PA devono stipulare un accordo di fruizione con il Ministero dell'Interno. nei prossimi mesi sarà resa disponibile una piattaforma per la gestione di questi accordi.
cordiali Saluti
