### ISSUE TITLE
ws [7001] - scarico tabelle

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#206]
Buon giorno,
facendo seguito alla vostra risposta in merito al problema relativo all'acquisizione dell'avvenuto subentro di un comune (bug #197), stiamo effettuando dei test di invocazione del servizio in oggetto, che come da specifiche dovrebbe restituire nella response un file in formato csv con la tabella richiesta. In particolare, nell'ultimo test effettuato (id operazione comune 1839), abbiamo richiesto la tabella con codice 30 'STATO PROCEDIMENTO AMMINISTRATIVO'. 
Non riusciamo però a leggere correttamente il file attachment restituito nella response, pur operando nello stesso modo in cui, ad esempio, otteniamo correttamente i file in formato pdf restituiti dal ws 6001 (certificazione), o i file in formato xml restituiti dal ws 3003 (consultazione notifiche), salvando lo stream dell'attachment in un file con l'estensione attesa senza bisogno di decodifiche di sorta.
Vi chiediamo pertanto, per lo stream di tale attachment è necessaria una decodifica, per ottenere il file nel formato atteso? O si tratta di un problema dovuto al fatto che il servizio in oggetto è in manutenzione/evoluzione? In ogni caso, inviamo in allegato il file.dat dell'attachment scaricato da soapUI.
Il test è stato effettuato in data 09/06/2017, in ambiente di test, per il comune pilota Teramo.
[attachment_7001_tabella30.zip](https://github.com/italia/anpr/files/1063980/attachment_7001_tabella30.zip)

Giuseppe Mucciarelli, TINN srl.

**Comment by mttfranci** [comment]
L'attachment restituito dal servizio 7001 è uno zip che a sua volta contiene il csv.

Ecco un esempio in java di lettura del contenuto : 

if(risposta7001!=null){
                    if(risposta7001.getRispostaMultipla7001().getDatiDettaglioRisposta().getXmlFile()!=null){
                           try{
                                  ByteArrayInputStream bin=new ByteArrayInputStream(risposta7001.getRispostaMultipla7001().getDatiDettaglioRisposta().getXmlFile().get(0));
                                  ZipInputStream zis=new ZipInputStream(bin);
                                  ZipEntry entry;
                                  while ((entry = zis.getNextEntry()) != null) {
                                        System.out.println("Unzipping: " + entry.getName());
                                        int size;
                                        byte[] buffer = new byte[2048];
                                        FileOutputStream fos = new FileOutputStream(entry.getName());
                                        BufferedOutputStream bos = new BufferedOutputStream(fos);
                                        while ((size = zis.read(buffer, 0, buffer.length)) != -1) {
                                          bos.write(buffer, 0, size);
                                        }
                                        bos.flush();
                                        bos.close();
                                      }
                                      zis.close();
                                      bin.close();
                           }catch(Exception e){
                                  e.printStackTrace();
                           }   
                   
                    }
             }

-----------------
Assistenza Sogei

**Comment by Amucciarelli74** [comment]
Ok, codificando lo stream in un archivio .zip e successivamente estraendone il contenuto in un file .csv,
siamo riusciti ad ottenere il file nel formato atteso.
Facciamo presente che la nostra difficoltà era dovuta al fatto che tale nota operativa non è presente nelle specifiche; nel file 7001Response.xlsx è indicato nella descrizione che il servizio restituisce un "File csv (separatore ";") prodotto relativo alla tabella richiesta", e non uno zip come invece da voi correttamente comunicato.
Il test è stato effettuato in data 12/06/2017, in ambiente di test, per il comune pilota Teramo.
Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Precisiamo meglio nelle specifiche
