### ISSUE TITLE
errore 527

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#2060]
Richiedendo l'attribuzione del C.F. tramite il gestionale per un soggetto iscritto AIRE, viene restituito esito negativo. Qui il testo dell'XML:
<?xml version="1.0" encoding="UTF-8"?>

-<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">

-<soapenv:Body>

-<b:Risposta5008 xmlns:a="http://sogei.it/ANPR/rispostaComune" xmlns:b="http://sogei.it/ANPR/5000mutazione">

-<b:rispostaKO>

-<testataRisposta>

<idOperazioneComune>20200430084946030</idOperazioneComune>

<codMittente>010067</codMittente>

<codDestinatario>ANPR02</codDestinatario>

<operazioneRichiesta>5008</operazioneRichiesta>

<dataOraRichiesta>2020-04-30T08:49:46</dataOraRichiesta>

<protocolloComune>0</protocolloComune>

<dataDecorrenza>2019-06-10</dataDecorrenza>

<idOperazioneANPR>241823768</idOperazioneANPR>

<esitoOperazione>XXXX</esitoOperazione>

</testataRisposta>

-<listaErrori>

-<errore>

<codiceErroreAnomalia>AEE96</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>

</errore>

-<errore>

<codiceErroreAnomalia>EN527</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-30 08:50:06 , idOperazioneANPR 241823768</testoErroreAnomalia>

</errore>

</listaErrori>

</b:rispostaKO>

</b:Risposta5008>

</soapenv:Body>

</soapenv:Envelope>
Si chiede come procedere. Grazie.

**Comment by MarcoZoagli1** [comment]
in aggiunta al precedente, altro soggetto anche questo AIRE con codice errore diverso, vedi xml:
<?xml version="1.0" encoding="UTF-8"?>

-<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">


-<soapenv:Body>


-<b:Risposta5008 xmlns:a="http://sogei.it/ANPR/rispostaComune" xmlns:b="http://sogei.it/ANPR/5000mutazione">


-<b:rispostaKO>


-<testataRisposta>

<idOperazioneComune>20200430121851086</idOperazioneComune>

<codMittente>010067</codMittente>

<codDestinatario>ANPR02</codDestinatario>

<operazioneRichiesta>5008</operazioneRichiesta>

<dataOraRichiesta>2020-04-30T12:18:51</dataOraRichiesta>

<protocolloComune>0</protocolloComune>

<dataDecorrenza>2019-06-10</dataDecorrenza>

<idOperazioneANPR>242017361</idOperazioneANPR>

<esitoOperazione>XXXX</esitoOperazione>

</testataRisposta>


-<listaErrori>


-<errore>

<codiceErroreAnomalia>AEE96</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>

</errore>


-<errore>

<codiceErroreAnomalia>EN527</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-30 12:19:15 , idOperazioneANPR 242017361</testoErroreAnomalia>

</errore>

</listaErrori>

</b:rispostaKO>

</b:Risposta5008>

</soapenv:Body>

</soapenv:Envelope>

**Comment by ncapozzi** [comment]
Buongiorno,
l'operazione 241823768 va in errore l'attribuzione del codice fiscale perché il toponimo numerico non è ammesso. Per la famiglia AIRE di appartenenza TOPONIMO = 23. E' necessario quindi effettuare, prima dell'iscrizione, una mutazione famiglia/convivenza 5001 con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO e indicare un toponimo alfanumerico

**Comment by ncapozzi** [comment]
L'operazione 242017361 è una ripetizione della precedente

**Comment by ncapozzi** [comment]
Buongiorno,
abbiamo verificato che per il cittadino è stato attribuito il CF pertanto si chiude la issue.

N. Capozzi
