### ISSUE TITLE
[5008] : errore EN389

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2061]
Ambiente di produzione, comune di Castiglione delle Stiviere

L'esecuzione di una mutazione altri dati 5008 con decorrenza 22/05/2019 per un soggetto restituisce l'errore "EN389 La data decorrenza 22-05-2019 dell'operazione non puo' essere inferiore alla data decorrenza 31-07-2019 dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto".
ID operazione ANPR 241834976.

Controllando però non riusciamo a rilevare alcuna operazione per il soggetto in data 31/7/2019.
Come mai ? Come possiamo procedere ?

Grazie

**Comment by frmariani** [comment]
In fase di subentro, avete inviato come data ultimo aggiornamento del soggetto, 31/07/2019, pertanto questa è la data da cui possono decorrere tutte le operazioni successive sul soggetto; le uniche operazioni possibili con una data antecedente sono le modifiche della residenza, dove il controllo è demandato alla data di decorrenza della residenza (Mutazione Aire effettuata in data 22/05/2019); 
allo stato attuale, per portare a buon fine l'operazione di mutazione dati, dovete inserire come data di decorrenza dell'operazione 31/07/2019;
In alternativa, dovete eseguire le seguenti operazioni nell'ordine:
1) annullare la mutazione Aire;
2) rettificare la data di ultimo aggiornamento da subentro in 22/05/2019;
3) effettuare la mutazione Aire con data 22/05/2019;
4) effettuare la mutazione dati con data 22/05/2019

**Comment by frmariani** [comment]
abbiamo verificato che l'operazione di mutazione dei dati è stata effettuata correttamente con data decorrenza 05/05/2020, pertanto la issue viene chiusa.
