### ISSUE TITLE
Errore EN447 - La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.

### ISSUE THREAD

**Issue by MattiaMaccio** [italia/anpr#2062]
Ambiente di Produzione ANPR.
Buongiorno,
In questi ultimi giorni stiamo rilevando una casististica relativa alle variazioni di parentela, per il quale provvedo a farvi un'esempio:

Si è proceduto con l'iscrivere un'individuo in ANPR in data 29.04.2020 e nella stessa medesima data il comune ha tentato di eseguire un cambio di parentela con il servizio 5001.
Ci viene restituito il seguente messaggio di errore:

idOperazioneANPR: 241570290
ERRORE EN447 - La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-04-29 13:14:12 , idOperazioneANPR 241570290

Abbiamo verificato le decorrenze e la data di decorrenza della variazione di parentela coincide con la decorrenza di iscrizione dell'individuo presso il comune.

Potreste verificare e darci qualche suggerimento?
Grazie Mille!

**Comment by frmariani** [comment]
abbiamo avuto un problema nei giorni precedenti che abbiamo prontamente risolto; potete effettuare oggi l'operazione per favore ?

**Comment by MattiaMaccio** [comment]
Buongiorno, a breve riproveremo e vi terrò aggiornati.
Piuttosto, stamane ci è stato restituito il medesimo messaggio con un'individuo che dall'APR si iscrive all'AIRE come da comunicazione dell'ufficio consolare.
La casistica è la stessa: si tenta di eseguire il cambio di parentela alla data di emigrazione dell'intestatario che si iscrive all'AIRE del comune (decorrenza: 2018-11-28 - come indicato nel modello cons01) per alcuni componenti del nucleo. La decorrenza del foglio famiglia APR è congruente con le varie decorrenze passate per i soggetti facenti parte di quel foglio famiglia. L'ID operazione ANPR è la seguente: 243173814.
Potreste cortesemente verificare?
Grazie

**Comment by frmariani** [comment]
forse non ho capito bene il problema, ma la famiglia indicata nell'operazione non risulta come famiglia Aire; state tentando di modificare delle relazioni di parentela ad una data incongruente con le operazioni effettuate precedentemente nella famiglia;
forse è meglio sentirci, mi invii un recapito telefonico alla mail indicata
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
