### ISSUE TITLE
ESITI SUBENTRO

### ISSUE THREAD

**Issue by adrianosicilia** [italia/anpr#2063]
ho caricato i file anpr e anpraire per iniziare i test, ma dopo dopo quasi 15 gg lo stato 
di "IN ELABORAZIONE" non cambia e non vedo nessuna riposta.
Quando dura questa fase?
 1000 posizioni in anpr        (Prot. 6002464 del 17/04/2020)    
 2900 posizioni in anpraire   (Prot. 6002463 del 17/04/2020)

**Comment by amollicone1982** [comment]
Mi può dire a quale comune fa riferimento?

**Comment by adrianosicilia** [comment]
Sto cercando di caricare i dati del comune di rende cs 078102-PC-0000 in ambiente free 888198-CO-0000 per poter provare le varie procedure dei webservice, in quanto siamo in ritardo nel configurare l'ambiente reale nel comune.

**Comment by amollicone1982** [comment]
Salve, puo' riprovare con l'invio dei file. Abbiamo avuto un problema sul nostro sistema di test

**Comment by amollicone1982** [comment]
Esiti restituiti. ha preso i seguenti errori ES092, EC053, EC032
di cui potrà trovare il dettaglio nella sezione esiti
Stanotte verrà eseguita la cancellazione del subentro caricato e domani potrà rinviare i file con le correzioni
