### ISSUE TITLE
ERRORE EN531

### ISSUE THREAD

**Issue by RAPO1964** [italia/anpr#2065]
COMUNE DI TORGIANO
MAURO RAPETTI

AMBIENTE DI PRODUZIONE
 MUTAZIONE CON PROVENIENZA DAL COMUNE DI RAVENNA (SUBENTRATO)

<dataOraRichiesta>2020-05-05T12:06:44.8421734+02:00</dataOraRichiesta>
      <protocolloComune>0</protocolloComune>
      <dataDecorrenza>2020-05-05</dataDecorrenza>
      <idOperazioneANPR>243689059</idOperazioneANPR>
      <esitoOperazione>XXXX</esitoOperazione>
    </testataRisposta>
    <listaErrori xmlns="">
      <errore>
        <codiceErroreAnomalia>EN531</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune RAVENNA (RA) con numero pratica ANPR: 23445690</testoErroreAnomalia>
      </errore>
      <errore>
        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-05-05 12:06:46 , idOperazioneANPR 243689059</testoErroreAnomalia>
      </errore>
      <errore>
        <codiceErroreAnomalia>EN395</codiceErroreAnomalia>
        <tipoErroreAnomalia>W</tipoErroreAnomalia>
        <testoErroreAnomalia>per il tipo di mutazione 2 saranno modificati soltanto i dati relativi a residenza e autoveicoli  </testoErroreAnomalia>
      </errore>
    </listaErrori>
  </rispostaKO>
</Risposta5005>

**Comment by rvinzani** [comment]
Salve, dovete contattare il comune di Ravenna per chiedere la chiusura del procedimento che è ancora aperto nel loro comune.
Chiudo la issue. In caso fossero necessari ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
