### ISSUE TITLE
[A001 / A002] Cittadinanza: Data Validità

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2066]
ambiente di TEST - comune di FAENZA (039010)

i servizi di iscrizione AIRE (A001 / A002) non prevedono l'indicazione del tag "cittadinanza" presumendo, giustamente, che il soggetto sia italiano.
succede però che viene assegnata in automatico la data di validità della cittadinanza, facendola corrispondere alla decorrenza dell'iscrizione aire.
questo potrebbe non essere vero, xchè la validità della cittadinanza potrebbe anche essere antecedente.

è previsto che tale informazione (la data validità della cittadinanza...) venga inviata contestualemente all'iscrizione?
due comunicazioni come esempio:
ws A001: idOperazioneComune 2020000387
ws A002: idOperazioneComune 2020000378

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buongiorno,
nel caso da lei descritto dopo l'iscrizione potete trasmettere una mutazione 5008 con tipo 2 - Cittadinanza con data decorrenza = a quella di iscrizione o successiva (es. 06/05/2020) e data validità della cittadinanza italiana corretta (es. 01/01/2020)

N. Capozzi

**Comment by AMonopoliADS** [comment]
si. questo l'avevamo intuito facendo delle prove.
ma diventa una modalità di lavoro che aumenta solo la necessità di procedimenti lato gestionale, il che non è pratico, considerato che l'informazione è conosciuta da subito.
non a caso la richiesta era se ci fosse in previsione di inviare il dato contestualmente all'iscrizione.
comunque grazie.
se possibile tenetene conto per eventuali evolutive.

**Comment by ncapozzi** [comment]
Scusate, in realtà l'oggetto altraCittadinanza già accetta anche ITALIA. Quindi se non lo trasmettete prende di default quella italiana alla data di decorrenza in testata mentre se la trasmettete voi prende la data di inizio validità trasmessa. Fate questa prova e fatemi sapere.

**Comment by AMonopoliADS** [comment]
il tag lascia intendere che si stia passando una nazionalità diversa da quella italiana, ma abbiamo provato come suggerito e con questo meccanismo viena aggiornata la dataValidita della cittadinanza principale del soggetto.

facciamo qualche altra prova, ma dire che così può andare.

grazie.
