### ISSUE TITLE
[A006] errore EN238

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2068]
Salve,
Comune di S.Angelo dei Lombardi (AV)
un soggetto (79431281) APR del nostro comune e stato iscritto in AIRE con una data decorrenza errata (31-01-2020 invece di 04-06-2019).
Nel modificare la data decorrenza otteniamo l'errore in allegato. Come dobbiamo procedere? 

![esito](https://user-images.githubusercontent.com/47904600/81157644-78e74200-8f87-11ea-94e4-b84ff582e692.png)

**Comment by ncapozzi** [comment]
Buongiorno,
le date di decorrenza delle operazioni eseguite in generale non possono essere modificate. Dovete annullare l'operazione ed eseguirla nuovamente alla data corretta. Fanno eccezione le date trasmesse al subentro che possono essere modificate con il servizio di Rettifica 5014 purché non siano presenti operazioni  successive (se presenti, prima devono essere annullate).

N. Capozzi
