### ISSUE TITLE
Problemi in presubentro

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2069]
Buongiorno
negli ultimi giorni in diversi comuni in fase di presubentro, riscontriamo non operatività nelle chiamate anpr.
allego un esempio da un comune nella giornata di ieri.
abbiamo inviato una 3002 di cui do i parametri fondamentali:

```
    <testataRichiesta>
      <idOperazioneComune>13</idOperazioneComune>
      <codMittente>016246</codMittente>
      <codDestinatario>ANPR02</codDestinatario>
      <operazioneRichiesta>3002</operazioneRichiesta>
      <dataOraRichiesta>2020-05-07T12:44:58.127+02:00</dataOraRichiesta>
      <tipoOperazione>C</tipoOperazione>
      <tipoInvio>PRE_SUB</tipoInvio>
      <dataDecorrenza>2020-05-07</dataDecorrenza>
```

e come risposta abbiamo ricevuto un file vuoto, con solo:

`<?xml version="1.0"?>
`

Questo in diverse installazioni. Abbiamo provato a guardare il problema, ma senza trovare motivo. Potete verificare per favore?

**Comment by mttfranci** [comment]
Salve.
Non abbiamo trovato traccia dell'operazione segnalata.
Potreste fornirci qualche altra informazione?
- Avete riscontrato il problema solo sui 3002 o anche su altri servizi?
- E' possibile avere la richiesta inviata e risposta ricevuta complete del vostro software? (meglio se di oggi)
- Continuate a riscontrare la casistica?
- Con che frequenza riscontrate il problema?
- Dite che il problema riguarda diversi comuni ma non tutti quelli in presubentro?
- Vediamo che nello stesso giorno dell'operazione indicata, un 3002 da web per lo stesso comune è andata a buon fine ( id operazione anpr 17020802), riscontrate qualche differenza con i 3002 richiamati da gestionale?
- Ogni altra informazione utile che avete a disposizione?

Grazie in anticipo.

**Comment by MarcoMigliori** [comment]
Buongiorno, per punti:
- Abbiamo provato solo la 3002 perchè se non funziona quello, presumiamo non funzioni nulla.
- Inviato una mail  all'indirizzo  Specifiche.anpr@sogei.it
- provato anche oggi, stesso risultato
- frequenza problema: ad ogni tentativo
- il problema riguarda almeno 3 comuni, ma un quarto sempre in presubentro funziona (parlo di quelli provati). su questi 3 comuni non siamo mai riusciti a fare una richiesta 3002 positiva
- abbiamo provato a cercare l'operazione anpr da voi indicata sulla wa, senza riuscirci. ma forse le 3002 non si possono vedere da wa  Utilità e notifiche -->monitoraggio operazioni .

**Comment by MarcoMigliori** [comment]
Rettifico: email non più utilizzabile. Me ne può indicare una?

**Comment by MarcoMigliori** [comment]
Sembra che abbiamo trovato il problema, nostro. Facciamo qualche altra prova e poi chiudo.

**Comment by mttfranci** [comment]
Ah perfetto, meglio così, fateci sapere.
Grazie

**Comment by MarcoMigliori** [comment]
Risolto grazie, scusate il disturbo.
