### ISSUE TITLE
[5008] tipo mutazione 16 - errore in creazione convivenze di fatto

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#207]
Pisa, Ambiente di Test, ID operazione ANPR: 516446, 516447 e 516448.

Buongiorno, abbiamo registrato una creazione di nuova famiglia per due individui che provenivano da due famiglie differenti e costituito una nuova convivenza di fatto. Le prime due operazioni sono state eseguite correttamente ma quando abbiamo provato a creare una convivenza di fatto tra le due persone ha segnalato l'errore: EN253 - I soggetti che costituiscono una convivenza di fatto devono appartenere alla stessa famiglia, ma con le precedenti operazioni i soggetti sono stati appunto inseriti nella stessa famiglia.
Allego request e response di tutte le operazioni, grazie.
Luca Bonini A.P.Systems

[creazione_convivenzadifatto.zip](https://github.com/italia/anpr/files/1064206/creazione_convivenzadifatto.zip)

**Comment by gcarbonin** [comment]
Le mutazioni di residenza (id operazione anpr 516446 e id operazione anpr 516447) riferite ai due soggetti, sono state annullate alle 11:31 ; il 5008 tipo mutazione 16 (convivenza di fatto id operazione anpr 516448) è stata effettuata alle 11:32 dopo l’annullamento delle operazioni, pertanto i soggetti risultano abitare in due famiglie diverse e precisamente:
il soggetto 1476089 appartiene alla famiglia 622631
il soggetto 1543457 appartiene alla famiglia 658463

**Comment by LucaBonini64** [comment]
Buongiorno dottoressa, ha chiuso la issue 207 indicandoci che i movimenti erano stati annullati prima della creazione della convivenza di fatto ma non è così.
Adesso le mutazioni di residenza (id operazione anpr 516446 e id operazione anpr 516447) riferite ai due soggetti risultano annullate, ma tale annullamento è stato fatto a seguito dell’errore sulla creazione della convivenza di fatto che ha generato il rollback delle operazioni precedenti ripristinando la situazione precedente, le operazioni si sono succedute con la seguente cronologia:
17920_5005 -> scissione/aggregazione.
17921_5005 -> scissione/aggregazione.
17922_5008 -> convivenza di fatto (errore).
17923_5012 -> annullamento 17920_5005 
17924_5012 -> annullamento 17921_5005
Le invio nuovamente i request e le response, comprensive anche dell’annullamento successivo.
[convfatto.zip](https://github.com/italia/anpr/files/1068265/convfatto.zip)
Cordiali Saluti

**Comment by gcarbonin** [comment]
Ha ragione; non avevamo controllato bene la sequenza. Il problema dell'errore del 5008 è dovuto al fatto che avete indicato l'identificativo ANPR del soggetto nel campo che contiene l'identificativo del comune e quindi non va a buon fine il collegamento con la famiglia. Miglioriamo il messaggio di errore

**Comment by LucaBonini64** [comment]
Ha ragione anche lei, non ci siamo accorti del refuso, noi provvediamo a correggere il nostro errore.

**Comment by gcarbonin** [comment]
Il messaggio di errore non può essere modificato.
