### ISSUE TITLE
Territori palestinesi

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2070]
Buongiorno,
dobbiamo procedere all'iscrizione anagrafica di un cittadino che era stato cancellato da noi nel 2018.
Il soggetto cancellato in ANPR risulta nato a TOULKAREM, stato estero CIRCOSCRIZIONE AUTONOMA). Ora dobbiamo iscriverlo con lo stato estero TERRITORI DELL'AUTONOMIA PALESTINESE (che è la nuova dicitura) ma NON riusciamo a procedere. 
Come è possibile riprenderlo modificando lo stato estero di nascita?

Grazie,
cordiali saluti.

**Comment by ncapozzi** [comment]
Buongiorno,
potrebbe indicare per favore l'idoperazione di iscrizione che va in errore?
N. Capozzi

**Comment by katiavacchi** [comment]
idoperazione da fornire in caso di assistenza 248747478 (si allega screenshot)
[erroreterritoripalestinesi.pdf](https://github.com/italia/anpr/files/4632878/erroreterritoripalestinesi.pdf)

**Comment by ncapozzi** [comment]
Prima fate la reiscrizione con CIRCOSCRIZIONE AUTONOMA, come sulla scheda cancellata, senza richiedere la validazione del CF (gestioneCF =3). Poi effettuate una mutazione 5008 del luogo di nascita in  TERRITORI DELL'AUTONOMIA PALESTINESE con gestioneCF = 0 oppure una risoluzione disallineamenti dalla web app confermando i dati di AE.
Se avete bisogno di assistenza telefonica diretta per favore indicate un recapito.

**Comment by katiavacchi** [comment]
Ci dà un altro errore. Appena lo replichiamo le invio copia.
Grazie.

**Comment by ncapozzi** [comment]
Per favore idoperazioneANPR

**Comment by katiavacchi** [comment]
Siamo riusciti a procedere. Grazie mille per la collaborazione.
Saluti.
