### ISSUE TITLE
[5012] Annullamento Emigrazione AIRE - A006

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2072]
ambiente di PRODUZIONE - comune di LODI (098031)

i due soggetti con idANPR 43933450 e 43933451 sono emigrati all'estero con ws A006 del 2019
oggi dobbiamo annullare l'iscrizione per correggere la data di decorrenza.

anche annullando le comunicazione nell'ordine corretto abbiamo sempre l'errore
EN077 - E - L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

le comunicazioni di annullamento che interessano i due soggetti sono:
idOperazioneComune 2020004986 (x il soggetto iscritto x secondo)
idOperazioneComune 2020004985 (x il soggetto iscritto x primo) 

si capisce l'errore nel tentativo di annullare le comunicazioni nell'ordine sbagliato... ma non quello eseguendo gli annullamenti nell'ordine giusto...

potete verificare per piacere?

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera,
dopo la mutazione AIRE è stata effettuata la mutazione 208859023 (WS 5001) come potete voi stessi verificare facendo accesso all'applicazione web, consultazione e estrazione, e una volta entrati nella scheda del cittadino selezionando elenco operazioni.
Prima dovete annullare la 5001.

Inoltre per idsoggetto 43933451  le mutazioni AIRE presenti sono due

**Comment by AMonopoliADS** [comment]
il problema allora è che il ws 3003 di richiesta dell'elenco operazioni restituisce solo le comunicazioni A006 x entrambi:
idOperazioneComune 2020307323 su idSoggettoANPR 43933451
idOperazioneComune 2020307321 su idSoggettoANPR 43933450
se potete verificare anche voi il comportamento del ws... grazie

**Comment by ncapozzi** [comment]
Buongiorno,
fino alla pubblicazione della versione 5.8 neanche la web app visualizzava le mutazioni 5001 di tipo 1 e 3. E' stata effettuata una modifica ad hoc ma mentre quella sulla web app è già stata rilasciata, quella sul 3003 lo sarà nei prossimi giorni.
N. Capozzi

**Comment by ncapozzi** [comment]
Specifico che  il nuovo 3003/3007 è inserito nella versione 5.9.0 e che entrambi gli interventi sono comunicati nel changelog
