### ISSUE TITLE
Aggiornamento xsd ws3003/ws3007 - note rilascio minor version 5.8.0 / 5.9.0

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#2073]
Sono stati pubblicati sul sito www.anpr.it gli aggiornamenti relativi ai tracciati dei servizi 3003 e 3007.
Per il dettagli è possibile consultare la pagina:
https://www.anpr.interno.it/portale/documentazione-tecnica

**Comment by mttfranci** [comment]
Le versioni 5.8 e 5.9 contengono un intervento che modifica leggermente il comportamento dell'elenco operazioni.
In particolare, è disponibile un nuovo elenco operazioni che contiene tutte le precedenti e alcune aggiuntive che influenzano il soggetto ma non gli erano legate in modo diretto. Ne sono un esempio le mutazioni famiglia (5001) con mutazione motivo costituzione.
Tali operazioni potevano portare ad un blocco in fase di annullamento ma non comparivano nell'elenco delle operazioni del soggetto.
 
Nella minor version 5.8 (già in produzione) tale intervento è stato anticipato nella web app dove il nuovo elenco operazioni della consultazione sostituisce il precedente.
 
Nella minor version 5.9 (che sarà in produzione a fine mese) tale comportamento è stato esteso al 3003/3007, nella ricerca operazioni del soggetto.
Nei webservice però il precedente comportamento è stato mantenuto come comportamento di default.

Si può accedere al nuovo elenco con un nuovo parametro di input :

**dettaglioElenco**

Ecco un esempio di utilizzo : 

```

<parametriRicercaSoggetto>
	<datiSoggetto>
		<idSchedaSoggettoANPR>123456789</idSchedaSoggettoANPR>
	</datiSoggetto>
	<!--
	Valori possibili :
		1 o non indicato - elenco classico
		2 - elenco esteso
	-->
	<dettaglioElenco>1</dettaglioElenco>
</parametriRicercaSoggetto>

```

Si ricorda inoltre che le correttive / nuove funzionalità vengono pubblicate : 
[Changelog](https://github.com/italia/anpr/blob/master/src/change-management/changelog.md)
[Roadmap](https://github.com/italia/anpr/blob/master/src/change-management/roadmap.md)
[Versione attuale in ogni ambiente](https://github.com/italia/anpr/blob/master/src/change-management/version.md)

Come descritto nel document di [change management](https://github.com/italia/anpr/blob/master/src/change-management/change-management.md) :

**Comment by mttfranci** [comment]
E'stata pubblicata una nuova versione dei WSDL : 
https://www.anpr.interno.it/portale/documentazione-tecnica
Che rimuovono una limitazione del tipoDataAnagrafica.

**Comment by AMonopoliADS** [comment]
> 
> 
> E'stata pubblicata una nuova versione dei WSDL :
> https://www.anpr.interno.it/portale/documentazione-tecnica
> Che rimuovono una limitazione del tipoDataAnagrafica.

faccio presente che sullo stesso url della documentazione tecnica i link Changelog e Roadmap puntano ancora a documenti del 2018

**Comment by rvinzani** [comment]
Grazie della segnalazione. Abbiamo rimosso i riferimenti al Changelog e alla Radmap dal documentale ANPR che invece vengono aggiornati su questa piattaforma
