### ISSUE TITLE
[6001] Famiglia non certificabile

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#2075]
Comune di Cossano Belbo - Ambiente di produzione.

In fase di rilascio di certificato di stato di famiglia per il soggetto GGUDRD38S04Z613F, viene restituito l'errore : EN222 - I certificati di stato di famiglia,  stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile
La famiglia è composta da IS, moglie, e 2 suoceri appena iscritti per rimpatrio dall'aire di un altro comune italiano. 
Da cosa è dovuto questo errore bloccante?

Saluti
Siscom SPA

**Comment by rvinzani** [comment]
Il soggetto con idANPR 23375292, risulta intestatario della scheda e il soggetto con idANPR 23375811ha con l'intestatario la relazione di parentela di moglie mentre le schede dei singoli soggetti non risultano tra di loro collegate. E' necessario effettuare una mutazione dati del matrimonio ed aggiungere sul coniuge il CF o l'idanpr

**Comment by siscomanpr** [comment]
Grazie, provvediamo alla correzione e se abbiamo ancora problemi facciamo sapere.

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa  stessa
