### ISSUE TITLE
Errore EN046 Solo stato di famiglia e residenza

### ISSUE THREAD

**Issue by CarloBettoni** [italia/anpr#2077]
Perché mi dà errore EN046 cercando di fare un certificato contestuale di Stato di Famiglia, Residenza e Stato Libero. 
Lo posso capire per un cittadino straniero ma per un italiano celibe mi pare strano.

**Comment by rnapoli1983** [comment]
Buonasera,

semplicemente il soggetto risulta parzialmente certificabile.

In questo stato di certificabilità del soggetto, possono essere richiesti esclusivamente certificati di residenza e di stato di famiglia.

Nulla vieta comunque di forzare la certificazione ed ottenere altri certificati anagrafici per il soggetto con relativo warning che di fatto lascia la scelta all'ufficiale di anagrafe se rilasciare tali certificazioni oppure no.

Se si ritiene che tale stato di certificabilità debba poter essere modificato può fare una mutazione dati anagrafici.

Rimango a disposizione.

Cordiali saluti
