### ISSUE TITLE
ERRORE DATA INGRESSO FAMIGLIA PER MUTAZIONI FAMIGLIA

### ISSUE THREAD

**Issue by RobertaLillo74** [italia/anpr#2078]
Buongiorno,
quando si effettua una mutazione da comune subentrato di un intero nucleo famiglia, mediante operazione di Mutazione Residenza Apr, la data costituzione famiglia (dato ANPR <dataOrigineFamigliaConvivenza>) e soprattutto le date di ingresso in famiglia dei componenti (dato ANPR <dataDecorrenzaLegame>) non vengono valorizzate con la data decorrenza dell'operazione (come avviene nel caso di famiglia nuova) ma restano valorizzate con le date originarie (quelle del comune di provenienza) e non c'è modo di modificarle nemmeno da webApp.
Attendo in merito un vostro riscontro.
Grazie per la Vostra collaborazione.

**Comment by frmariani** [comment]
La data di costituzione della famiglia e la data di ingresso dei componenti, non devono essere modificate se il nucleo familiare si sposta in toto come nel vostro caso; voi non state creando un nuovo nucleo familiare, state semplicemente spostando nel vostro comune una famiglia già creata e composta precedentemente; la data di decorrenza della residenza sarà sicuramente modificata e sarà uguale alla data di decorrenza dell'operazione. Potete sicuramente modificare l'identificativo comunale con il servizio di Mutazione Famiglia/Convivenza tipo di mutazione Motivo famiglia/Specie convivenza.
Nel caso fosse necessario un contatto diretto mi scriva al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
