### ISSUE TITLE
[5008] Mutazione Lista di Leva - Errore "EN470"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2079]
ambiente di PRODUZIONE - comune di LODI (098031)

idSoggettoANPR 43931505

si tenta di inviare con ws 5008 la mutazione della lista di leva (idOperazioneComune 2020005224)
il servizio risponde con errore bloccante
EN470 - E - Il soggetto risulta duplicato all'interno dello stesso comune

ricercando con ws 3002 sia tramite codice fiscale che tramite cognome / nome / data nascita, la consultazione risponde un solo soggetti, con anomalia similare da subentro (EN472)

non capiamo cosa blocca l'operazione.

grazie
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare ad eseguire l'operazione per favore?

**Comment by AMonopoliADS** [comment]
adesso la comunicazione è stata inviata con successo.
