### ISSUE TITLE
errore di connessione ad ANPR dopo cambio pc

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2081]
Buongiorno, un nostro cliente dopo il cambio del pc (attuale sistema operativo W10) non si collega più ad ANPR dall'applicativo gestionale. Abbiamo effettuato tutte le verifiche di configurazione del nostro applicativo e rilevato che sono corrette, inoltre l'utente è amministratore, abbiamo disabilitato firewall e antivirus, reinstallato certificato di postazione, (sulla WEBAPP accede con smart card senza problemi) abbiamo effettuato anche prove su più utenti del comune e solo con questo computer non si riesce ad accedere.  L'errore segnalato quando si fa una banale interrogazione è il seguente. 

ERRORE   >ASGS004   Errore durante l'impostazione del provider di firma pkcs7, non è stato   possibile impostare il provider con i seguenti parametri
signatureAlgo   =sha256WithRSAEncryption,providerName =SunMSCAPI,keystoreAlias   =015237,keystorePassowrd =null
nota:   salvataggio log effettuato.

Vi chiediamo se avete già avuto altri casi simili e se avete una risoluzione.
Restiamo a disposizione per ulteriori informazioni se necessarie

Cordiali saluti

Cinzia Girelli
GPI SPA
3346216774

**Comment by gife67** [comment]
Buongiorno,
la diagnostica che riportate è sicuramente relativa al vostro gestionale, in fase di preparazione della cornice di sicurezza necessaria alla corretta invocazione dei servizi ANPR. Quello che posso dedurre dalla vostra diagnostica è che mi sembra errato l'alias del certificato di postazione utilizzato, dal momento che nel keystore è nel formato 015237-PC-xxxx dove xxxx indica il numero di postazione. 
Cortesemente se potete verificare.

**Comment by CGIRELLI-HUB** [comment]
La ringrazio ma abbiamo riscontrato stesso errore anche su altra postazione
dove il formato key store nel messaggio di errore viene riportato nel
formato corretto.


Faremo ulteriori indagini nel corso della settimana prossima.



Cordiali saluti









*Cinzia Girelli*



*HR – HD DEPLOY E PIATTAFORMA*

C. +39 334 6216774 | T. +39 0461 381515 int. 07576

*Gruppo GPI*

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.



























*Da:* Giuseppe F. [mailto:notifications@github.com]
*Inviato:* venerdì 22 maggio 2020 09:52
*A:* italia/anpr
*Cc:* CGIRELLI-HUB; Author
*Oggetto:* Re: [italia/anpr] errore di connessione ad ANPR dopo cambio pc
(#2081)



Buongiorno,
la diagnostica che riportate è sicuramente relativa al vostro gestionale,
in fase di preparazione della cornice di sicurezza necessaria alla corretta
invocazione dei servizi ANPR. Quello che posso dedurre dalla vostra
diagnostica è che mi sembra errato l'alias del certificato di postazione
utilizzato, dal momento che nel keystore è nel formato 015237-PC-xxxx dove
xxxx indica il numero di postazione.
Cortesemente se potete verificare.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/italia/anpr/issues/2081#issuecomment-632551847>, or
unsubscribe

**Comment by gife67** [comment]
Per il momento chiudo questa issue, 
in caso dovesse avere ulteriori problemi, può tranquillamente aprirne una nuova, referenziando questa.
Buona serata,
Giuseppe
