### ISSUE TITLE
Annullamento iscrizione anagrafica bloccata

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2082]
Buongiorno,
dobbiamo annullare l'iscrizione anagrafica di due soggetti per errata data di decorrenza che da 30 ottobre 2019 deve essere 17 ottobre 2019.
Il problema è che per uno dei due, in data 25 novembre 2019, è stato corretto (per errore materiale nell'inserimento) il nome aggiungendo una vocale che non incideva sul codice fiscale  (id operazione ANPR 157884356). 
Per procedere con l'annullamento dell'ISCRIZIONE dobbiamo prima annullare tutte le successive operazioni eseguite MA l'annullamento della variazione di nome dà errore (in allegato). Ci propone di fare una nuova mutazione ma a quel punto riusciremo poi ad annullare tutte le mutazioni fino ad arrivare ad annullare l'iscrizione?
Grazie per l'attenzione.

![errore nome](https://user-images.githubusercontent.com/57749903/82648586-2446f680-9c18-11ea-83c0-9bb71771a769.JPG)

**Comment by ncapozzi** [comment]
Buonasera,
il msg di errore vi propone di fare una nuova mutazione nell'ipotesi che uno dei 5 dati anagrafici sia da rettificare Questo perché le mutazioni di dati anagrafici che comportano anche l'aggiornamento di Agenzia delle Entrate non possono essere annullate. 
Pertanto per questo soggetto non riuscirete ad annullare tutte le mutazioni fino ad arrivare ad annullare l'iscrizione ma dovete cancellare il soggetto per altri motivi e riscriverlo alla data corretta indicando nelle generalità l'idsoggetto ANPR della scheda cancellata.

N. Capozzi

**Comment by ncapozzi** [comment]
Buonasera,
non avendo più ricevuto alcun riscontro si chiude la issue.

N. Capozzi
