### ISSUE TITLE
Inserimento divorzio su deceduto

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2083]
Comune di Modena - Ambiente di Produzione

Buongiorno,
nei giorni scorsi il nostro Stato Civile ha annotato e quindi reso effettiva una sentenza di divorzio del 2013 relativa a due nostri residenti. Il marito (idANPR 19259860) è deceduto nel 2019; vorremmo riuscire ad annullare la vedovanza della moglie (idANPR 19373346) per registrare il divorzio ma sembra impossibile senza annullare il decesso. C' è un modo per evitarlo?

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
mi dispiace ma non c'è possibilità; con il decesso del coniuge viene acquisita contemporaneamente anche la vedovanza del coniuge superstite, quindi  per registrare il divorzio si deve annullare temporaneamente il decesso.

**Comment by sfmodena** [comment]
Grazie della risposta, chiudo la issue.

Saluti
Sonia Fiorini
