### ISSUE TITLE
Rilascio certificati anagrafici per PEC - richiesta chiarimenti

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#2084]
Buongiorno,
il Comune di Cagliari, per venire incontro ai cittadini ed evitare le file agli sportelli, vorrebbe incentivare il rilascio dei certificati (oltre che online con accesso tramite spid al portale), anche con invio per PEC.

Finora il cittadino che non poteva o voleva recarsi allo sportello o collegarsi al portale per il rilascio del certificato online, faceva richiesta per corrispondenza inviando una busta preaffrancata, il contrassegno dell’imposta di bollo e i contanti per i diritti di segreteria.

L’intenzione dell’amministrazione è quella di rendere più celere il servizio nel modo seguente:
il cittadino fa richiesta via PEC del certificato e indica il numero identificativo del contrassegno dell’imposta di bollo in suo possesso che provvederà lui stesso ad applicare al certificato;
l’ufficiale d’anagrafe emetterà il certificato riportando gli estremi del contrassegno della marca da bollo indicati dal cittadino nella richiesta ed invia il certificato via PEC.

Si chiede, anche in considerazione di quanto riportato per i certificati online nelle issue #287,  #1316 e  #646, se, in base a quanto stabilito dal CAD e dalla circolare 62/2013 dell’AGID, sia possibile:
1) emettere il certificato da inviare senza PEC senza la firma (autografa o digitale) dell’ufficiale
    d’anagrafe?
    In caso affermativo occorre inerire la dicitura “firma omessa ai sensi dell’art.3 del D.Lgs. 39/93”? e 
    se  si è possibile prevededre la stapa in automatico da Anpr?
    
2) è possibile gestire la forma di pagamento dell’imposta di bollo come sopra riportata 
   permettendo l’inerimento  del codice identificativo del contrassegno nella frase relativa 
   all’assolvimento dell’imposta di bollo?

Grazie 
Andrea Demeglio
Comune di Cagliari

**Comment by FilippoPapi** [comment]
buonasera,
purtroppo non siamo in grado di rispondere alla sua domanda.
questo tipo di quesiti vanno rivolti alla Ministero dell'Interno,, Dipartimento per gli Affari interni e territoriali, Direzione centrale per i Servizi demografici
cordiali Saluti
