### ISSUE TITLE
Rif.to ISSUE #2081 Errore di connessione ANPR

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2085]
Buongiorno, in riferimento alla Issue #2081 di alcuni giorni fa, vi segnalo che stamattina abbiamo fatto varie prove ed abbiamo riscontrato che il problema si verifica solo da un pc (sostituito da poco) e ribadiamo che prima della sostituzione non vi erano problemi. Pertanto, rileviamo che deve esserci qualche impostazione a livello di Sistema operativo Windows che va in conflitto con il perimetro di riconoscimento dell'utente. L'errore è sempre lo stesso:

ERRORE   >ASGS004   Errore durante l'impostazione del provider di firma pkcs7, non è stato   possibile impostare il provider con i seguenti parametri signatureAlgo   =sha256WithRSAEncryption,providerName =SunMSCAPI,keystoreAlias   =015237,keystorePassowrd =null nota:   salvataggio log effettuato.

Se aveste bisogno di contattare direttamente il comune il riferimento è ANTONELLA ZACCHETTI 0295080853 - COMUNE DI VIGNATE 

Grazie 

Cinzia Girelli
 
HR – HD DEPLOY E PIATTAFORMA
C. +39 334 6216774 | T. +39 0461 381515 int. 07576
Gruppo GPI

**Comment by FilippoPapi** [comment]
buonasera
come già detto la diagnostica che riportate è sicuramente relativa al vostro gestionale. purtroppo non siamo in grado di fornire assistenza sui gestionali.
cordiali saluti
