### ISSUE TITLE
D.L. 19 maggio 2020, n. 34 - Richiesta Informazioni

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2086]
alcuni clienti ci chiedono se e come ANPR renderà disponibili le comunicazioni ai Comuni, secondo quanto disposto dal D.L. in oggetto (di cui allego un estratto)

grazie.
Alessandro Monopoli ADS

D.L. 19 maggio 2020, n. 34 recante "Misure urgenti in materia di salute, sostegno al lavoro e all'economia, nonché di politiche sociali connesse all'emergenza epidemiologica da COVID-19", cd. decreto Rilancio, pubblicato in G.U. n. 128 del 19 maggio 2020, S.O. n. 21, l'art. 12 che testualmente recita:

"Art. 12 Accelerazione dell'acquisizione delle informazioni relative alle nascite e ai decessi 
...
art. 3. Il Sistema Tessera Sanitaria rende immediatamente disponibili, senza registrarli, i dati di cui al comma 1:
a) all'Anagrafe Nazionale della Popolazione Residente (ANPR), per le finalità di cui all'articolo 62, comma 6, lettera c) del decreto legislativo 7 marzo 2005, n. 82, recante Codice dell'amministrazione digitale;
b) tramite Posta elettronica certificata (PEC), ai Comuni non ancora collegati alla ANPR;
c) all'ISTAT.

**Comment by FilippoPapi** [comment]
buonasera
così come previsto dal D:L: citato, ci sarà un decreto del Ministero dell'Economia che stabilirà i flussi
cordiali saluti
