### ISSUE TITLE
[Test di connessione] Connection timed out

### ISSUE THREAD

**Issue by fmbianchi** [italia/anpr#2087]
Ambiente di subentro
Comune di Brunello

Durante il test di connesione il comune riceve errore "Connection timed out" come se l'IP non fosse censito.

Errore: "2020-05-26 12:40:43 WARN  PhaseInterceptorChain:449 - Interceptor for {http://sogei.it/ANPR/TestConn}TestConn#{http://sogei.it/ANPR/TestConn}testConnessione has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Connection timed out: connect"

<idOperazioneComune>20200526123418894</idOperazioneComune>
<codMittente>012023</codMittente>

In attesa di riscontro 
cordiali saluti

**Comment by cmigliardi** [comment]
Buongiorno,  cortesemente ci può indicare l' IP  dal quale effettuate il collegamento verso i servizi di anpr ? grazie

**Comment by cmigliardi** [comment]
poiché non ho ricevuto indicazioni, Le lascio il mio indirizzo cmigliardi@sogei.it   - chiudo la issue  e attendo info tramite email  -
