### ISSUE TITLE
[1002] Re-iscrizione di cancellato per ripristino

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#209]
Pisa, ambiente di Test, ID operazione ANPR 519630

Buongiorno, come indicato nella precedente #204 abbiamo cancellato un cittadino a seguito di accertamenti negativi, poi lo abbiamo reiscritto e comunicato nell'iscrizione l'idsoggettoANPR precedentemente inviato ma ci viene restituito l'errore EN185 idSchedaSoggettoANPR6300913 non presente o dati anagrafici incongruenti.
Abbiamo provato a controllare ma i dati anagrafici ci sembrano identici, cambiano solo i dati di famiglia e indirizzo perché viene riscritto in altra famiglia.
Potete per cortesia verificare perché ci viene restituito questo errore?
Allego request e response, grazie.
Luca Bonini A.P.Systems
[reimmi_ripri.zip](https://github.com/italia/anpr/files/1070652/reimmi_ripri.zip)

**Comment by gcarbonin** [comment]
Non è stata effettuata una cancellazione per ripristino della posizione anagrafica ma un annullamento della iscrizione. Questa operazione non consente di recuperare l'id anpr.
