### ISSUE TITLE
Mutazione dati Divorzio - Errore EHR31 e EHR90

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2091]
Buongiorno,
ambiente di produzione.
Si inoltro l'errore riguardante l'invio di una mutazione dei dati di cessazione matrimonio a seguito di atto registrato davanti all'ufficiale dello stato civile. In questo specifico caso, vi sono due atti: il primo, registrato in data 09/01/2020 ed il secondo, la conferma dell'accordo, registrato in data 13/02/2020.

EHR31 La data di validita' della sentenza 09-01-2020 risulta inferiore a quella di emissione 13-02-2020
EHR90 Data sentenza 13-02-2020  maggiore della data di decorrenza dell'operazione richiesta
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2020-05-27 10:22:55 , idOperazioneANPR 256610605

Resto in attesa di gradito riscontro
Saluti

**Comment by frmariani** [comment]
Non è possibile inserire i dati di due atti come se fosse uno solo atto; dovete decidere se acquisire i dati dell'uno o dell'altro perchè le date non sono compatibili tra di loro;

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
