### ISSUE TITLE
STESSO CODICE FISCALE ERRONEAMENTE ATTRIBUITO A DUE PERSONE DIVERSE

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2092]
In data 08/10/2016 la Questura attribuiva il codice fiscale alfanumerico ad un cittadino straniero che di seguito indicherò come CITTADINO 1.
In data 07/06/2018 un’altra Questura “collegava” quello stesso codice fiscale ad un altro cittadino straniero, avente le stesse identiche generalità, che di seguito indicherò come CITTADINO 2.
In data 30/08/2019 CITTADINO 2 è stato iscritto in ANPR per immigrazione dall’estero, presente nell’APR dello scrivente comune di Valsamoggia.
In data 09/12/2019 CITTADINO 1 richiedeva l’iscrizione nell’APR del Comune di Corigliano-Rossano, non subentrato in ANPR, con provenienza dall’estero.
Poiché il sistema INA-SAIA ha evidenziato l’anomalia, abbiamo avuto contatti con il comune di Corigliano-Rossano e, sembrando trattarsi della stessa persona, abbiamo invece cancellato da ANPR per emigrazione a Corigliano-Rossano il CITTADINO 2.
L’11/03/2020 il “vero” CITTADINO 2 ha richiesto la residenza nel Comune di Malalbergo (subentrato in ANPR), che l’ha dovuto iscrivere per immigrazione da Corigliano-Rossano.
L’esistenza del problema è emerso nel momento in cui il CITTADINO 1 ha richiesto il rilascio della CIE a Corigliano-Rossano.
Ho chiesto alle Questura interessate, sulla base dei fotosegnalamenti, di confermare che si tratti effettivamente di due persone diverse e così è stato.
Al momento, d’accordo con i colleghi degli altri comuni coinvolti, abbiamo agito in modo tale che, attualmente, la situazione anagrafica è la seguente
CITTADINO 1 (che deve mantenere quel codice fiscale)
Iscritto nel comune di Corigliano-Rossano dal 09/12/2019 per immigrazione dall’estero.
Il comune di residenza, non essendo subentrato in ANPR, ha semplicemente cambiato la provenienza
CITTADINO 2 (al quale deve essere assegnato un nuovo codice fiscale)
Iscritto in ANPR per immigrazione dall’estero dal 30/08/2019 presente nell’APR di Valsamoggia.
Il Comune di Malalbergo ha annullato l’iscrizione anagrafica.
Il Comune di Valsamoggia ha annullato l’emigrazione a Corigliano-Rossano
Vorrei pertanto sapere come posso fare perché l’Agenzia delle Entrate rilasci un nuovo codice fiscale (anche numerico, in attesa della soluzione dell’omocodia) al mio residente. Questo gli consentirebbe di chiedere nuovamente l’iscrizione anagrafica a Malalbergo, dove effettivamente dimora,  ed al Comune di Corigliano-Rossano di rilasciare la CIE alla persona là residente

**Comment by rvinzani** [comment]
Le informazioni sono state fornite telefonicamente.
