### ISSUE TITLE
URGENTE: Allineamento codice fiscale errato

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2093]
Buongiorno per il comune di Umbertide questa mattina è stata effettuata una operazione dal menù Risoluzione disallineamenti con AE per il soggetto con ID ANPR nr 88372535 - i dati indicati da Web app coincidevano con stesso luogo di nascita e l'utente del comune ha confermato i suoi con CF GBLMRA42L10I981Q, invece la web app ha assegnato e validato il CF che risultava collegato ovvero il GBLMRA42L10L117I che non è quello che ha in mano il soggetto;  il codice fiscale corretto è GBLMRA42L10I981Q. Com'è possibile ripristinare la situazione iniziale? Vi è una incongruenza sul comune di nascita che alla data dell'evento doveva essere TERNI ma sui documenti agli atti del comune risulta STRONCONE e deve restare questo. Vi prego cortese urgenza poichè ora in AE risulta validato un CF non corretto per il soggetto. 
Resto a disposizione per ulteriori chiarimenti se necessari
Grazie 
Cordiali saluti

Cinzia Girelli
GPI SPA
3346216774

**Comment by rvinzani** [comment]
Fornite indicazioni telefoniche
