### ISSUE TITLE
[6001] Certificazione on-line in bollo

### ISSUE THREAD

**Issue by slastrucci** [italia/anpr#2095]
Buongiorno a tutti,
vista l'emergenza sanitaria in corso il Comune di Prato vorrebbe riattivare per i cittadini la possibilità di ottenere on-line certificati in bollo. Questa possibilità era presente sul nostro portale prima del subentro in ANPR ma è stata interrotta a causa dell'assenza sul certificato di un dicitura che indica espressamente la necessità di apporre la marca da bollo cartaceo (come indicato da Carbonin).

Secondo la nostra interpretazione l'apposizione del bollo deve essere fatta tramite l'utilizzo di una marca "fisica" che ne impedisca la duplicazione. Altre soluzioni come il bollo virtuale o l'indicazione del numero di serie e la data di emissione renderebbe il certificato facilmente duplicabile, agevolando in questo modo l'evasione del bollo nelle eventuali copie (es. stampe multiple dello stesso pdf).

La necessità di apporre una marca da bollo però dovrebbe essere evidente, servirebbe quindi una dizione che lo indica esplicitamente, e se possibile, anche un riquadro prestampato con scritto ad esempio "Apporre bollo da 16€".

Abbiamo scartato l'ipotesi di apporre noi quello che manca direttamente sul pdf prodotto da ANPR perchè, in questo modo, potrebbe non risultare autentico agli occhi di chi effettua la verifica tramete il QR-code.

Sono stati fatti passi avanti in questo senso sul servizio 6001 di certificazione?
E' possibile tramite qualche parametro di certificazione pilotare l'aggiunta di una dizione che riguarda l'apposizione del bollo?

Grazie.

Lastrucci Stefano

**Comment by FilippoPapi** [comment]
buongiorno,
la situazione ad oggi non è cambiata. molto probabilmente ne prossimi mesi ci sarà la possibilità di emettere i certificati direttamente dal sito di ANPR.
Cordiali Saluti
