### ISSUE TITLE
Famiglia non certificabile

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2096]
Buon pomeriggio.
Non riusciamo ad emettere il certificato di stato di famiglia per la famiglia con codice 9083878.
I miei riferimenti sono i seguenti:

Paltrinieri Andrea -
Ufficiale d'Anagrafe del Comune di Biassono (108009)
e-mail: anagrafe@biassono.org
tel. 039-2201060

In attesa di un Vs. riscontro, porgo distinti saluti.

Andrea Paltrinieri

**Comment by ncapozzi** [comment]
Buongiorno,
il problema nasce dal fatto che al subentro per idsoggetto 18937982 è stato trasmesso il matrimonio attuale associato alla cessazione con data antecedente (sembrerebbe quindi la cessazione di un precedente matrimonio che non avrebbe dovuto essere trasmessa).
Se è così, è necessario eliminare i dati del matrimonio con relativa cessazione, ma prima di poter fare questo è necessario annullare le due mutazioni famiglia/convivenza 258265156 e 258270517 effettuate dopo il subentro partendo dall'ultima eseguita.
Ho provato a contattarla poco fa al numero sopra indicato ma non risponde nessuno. Se ha bisogno di assistenza telefonica per eseguire le operazioni mi indichi per favore quando posso trovarla. Grazie

N. Capozzi

**Comment by paltrinan** [comment]
Problema risolto!
Ringrazio per l'assistenza ricevuta

Buona giornata
Andrea Paltrinieri
