### ISSUE TITLE
Risoluzione disallineamenti con Agenzia Entrate

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2097]
Buongiorno,
a quasi due anni da subentro, confesso di avere ancora molti, troppi dubbi sul corretto utilizzo della funzione Risoluzione disallineamenti con Agenzia Entrate e questo determina spesso un utilizzo non corretto e la necessità di richiedere intervento ad Agenzia Entrate (Archivio) per risolvere.
Mi chiedo spesso se è solo un mio limite o se anche colleghi di altri comuni manifestano lo stesso problema.
E' ipotizzabile Webinar specifico per l'argomento?
Grazie e buon fine settimana.

Anna Maria AIMONE
UPI Torino

**Comment by frmariani** [comment]
Buongiorno Anna Maria, 
sicuramente prenderemo in considerazione il tuo suggerimento, anche se 
tendiamo a farvi affrontare in autonomia le casistiche standard, cioè quelle che affrontiamo durante i webinar dei corsi di Formazione ANPR, dove dedico molto tempo proprio ai test sulla risoluzione dei disallineamenti con AE. Le casistiche possono essere sempre nuove e diverse, quindi non sarebbe esaustivo neanche un webinar dedicato; inoltre, per i casi particolari preferiamo supportarvi con la nostra assistenza, in modo da non complicare ulteriormente la problematica del cittadino con operazioni superflue e talvolta errate.
Sicuramente anche altri colleghi manifestano il tuo stesso disagio, ma a volte, l'argomento è di grande complessità.
