### ISSUE TITLE
TESTCONN, Accesso area amministrativa 

### ISSUE THREAD

**Issue by adrianosicilia** [italia/anpr#2098]
Premesso che chiedo informazioni relative al comune di Rende, CS, e sono Adriano Sicilia e mi sto occupando della procedura di migrazione APR a ANPR, con i test effettuati in ambiente webfree (https://dpfree.anpr.interno.it/combas) ,  sembra che tutto funzioni bene, quando invece provo l'ambiente di test ufficiale (https://dptest.anpr.interno.it/combas), usando il certificato di postazione ottenuto in passato, con l'utente "COMUNETEST078102", riportato nei dati del certificato, ottengo un errore di sicurezza e non accedo al sito, so che l'accesso deve avvenire invece con cf e pw, ma i gestori dell'area privata del sito (https://areaprivata.anpr.interno.it/sitoCNSD/security/logon.jsp) non riescono a definire gli utenti con i relativi cf, in quanto (mi riferiscono) che le smart card ricevute non risultano attivate, (tranne quella del sindaco), potete verificare quando riportato ed eventualmente chiarirmi le idee su come procedere per superare questo inconveniente, grazie.

**Comment by Leonforte** [comment]
Per l’accesso all’ambiente di TEST COMUNI  è previsto l’accesso con credenziali nominali (e non più generiche) previo censimento da parte degli Amministratori Locali di Sicurezza dei Comuni (dell’ambiente di esercizio), sulla console di sicurezza di test, degli utenti che dovranno accedere all’ambiente di TEST. 
 
Tali politiche di sicurezza sono adottate in ottemperanza all’avviso pubblicato il 25 giugno 2019 sul sito ANPR disponibile al seguente link https://www.anpr.interno.it/portale/documents/20182/209665/Avviso+nuove+modalit%C3%A0+accesso.pdf/5a7eead9-9aba-4999-9189-6d5afeca4beb


Per accedere alla WebApp di test si utilizza sempre  il certificato di postazione  di test   (es.  001156-CO-0000.p12) inviato alla PEC del Comune
ed l’utenza nominale (codice fiscale e password) dell’ALS (Amministratore Locale della Sicurezza) dell’ambiente di produzione.
In particolare, tutti gli ALS censiti in ambiente di produzione, sono stati registrati anche in ambiente di Test-Comuni, in modo da consentire l’accesso alla WebApp di Test-Comuni e operare dalla Console di Sicurezza per censire tutte le utenze nominali che dovranno operare in questo ambiente.
L’utenza, una volta registrata,  riceverà una email (all’indirizzo specificato all’atto stesso del censimento) con la password assegnata dal sistema. 

La url di accesso è rimasta invariata :

https://dptest.anpr.interno.it/combas

Le consiglio quindi di eseguire le operazioni propedeutiche come da allegato, buon lavoro, saluti
[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/4710310/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)

**Comment by adrianosicilia** [comment]
quanto suggerito è stato già fatto il problema è che il comune con la cad del sindaco non riesce ad entrare  sul portale per definire il responsabile
ottenendo questo errore

**
Il sito non può fornire una connessione protettadp.anpr.interno.it non ha accettato il certificato di accesso oppure non ne è stato fornito uno.
Prova a contattare l'amministratore di sistema.
ERR_BAD_SSL_CLIENT_AUTH_CERT
**
le prove sono state fatte con diversi browse e tutti vedono correttamente il certificato di postazione, che il certificato (sindaco) presente nella smart

**Comment by Leonforte** [comment]
Mi scusi ma questo è un problema conpletamente diverso da quello segnalato inizialmente.
La prego quindi di voler specificare in modo dettaglio in quale ambiente sta tentando di entrare, con quali credenziali e con quale certificato di postazione e se s itratta di applicazione web o di accesso ai web services. La ringrazio, buon lavoro, saluti

**Comment by adrianosicilia** [comment]
cerco di spiegare meglio quanto scritto nel primo messaggio:
1. con i test effettuati in ambiente webfree (https://dpfree.anpr.interno.it/combas) , tutto funziona bene sia come webapp che webservice;
2. nell'ambiente di test ufficiale (https://dptest.anpr.interno.it/combas), usando il certificato "078102-CO-0000.p12" e utente "COMUNETEST078102" non si entra  (webaccess/webservice) e viene sollevato il seguente errore:
**
_Si e' verificato un errore durante la fase di autenticazione
Le credenziali o, i certificati utilizzati non sono stati riconosciuti come validi_
**
e veniamo invitati a definire il responsabile ALS;
3. nell'ambiente di subentro (dp.anpr.interno.it) dove dovremmo definire  il responsabile ALS, con la card del sindaco ed il certificato di postazione ("078102-CO-0000.p12") installato invece otteniamo 
_**
Il sito non può fornire una connessione protetta non ha accettato il certificato di accesso oppure non ne è stato fornito uno.
Prova a contattare l'amministratore di sistema.
ERR_BAD_SSL_CLIENT_AUTH_CERT
**_
spero di essere stato chiaro a descrivere la problematica, e grazie ancora per la collaborazione

**Comment by Leonforte** [comment]
Riguardo al punto 3 La invito nuovamente a prendere visione della documentazione inviata e in generale quella presente al link www.anpr.interno.it.
Il certificati di postazione per l'accesso all'ambiente di produzione dp.anpr.interno.it sono diversi da quelli utilizzati in ambeinte di test, e perl'accesso alla web app da una postazione client è utilizzato generalmente quello marcato come 078102-PC-nnnn (es. 078102-PC-0001) messo a disposizione al Sindaco al momento del rilascio della smart card da parte della Prefettura di competenza. Fermo restando che è consentito anche l'utilizzo di quello server 078102-CO-9999. Medisima cosa per i servizi. Il certificato 078102-CO-0000 deve essere utilizzato esclusivamente per l'ambiente di test. Buon lavoro, saluti

**Comment by adrianosicilia** [comment]
Grazie ai suggerimenti siamo riusciti a fare qualche passo in avanti, 
1: richiesto il certificato per la postazione 078102-PC-0001 e con la smart card del sindaco abbiamo nominato il responsabile ASL e altri utenti, e tutto ok;
2: con le credenziali dell'ASL entriamo in ambiente Subentro e Pre-Subentro con il certificato 078102-CO-9999.p12;
3: cosa strana ma con le credenziali dell'ASL cf e pw non si accede in ambiente di Test con il certificato 078102-CO-0000.p12 e quindi non riusciamo a nominare l'utente abilitato ai test sulla piattaforma;
Cosa bisogna fare per entrare in ambiente di test?

**Comment by Leonforte** [comment]
ci sono stati dei problemi generali nell'ambiente di test comuni, potete riprovare

**Comment by adrianosicilia** [comment]
Buongiorno, continuo a ricevere questo errore:
"Si e' verificato un errore durante la fase di autenticazione
Le credenziali o, i certificati utilizzati non sono stati riconosciuti
come validi"
sia con certificato 078102-CO-9999.p12 che 078102-CO-0000.p12
grazie per la pazienza che mi state dedicando.

**Comment by Leonforte** [comment]
Buonasera, abbiamo reimpostato la pwd che è stata rinviata a f.acri@comune.rende.cs.it
e verificato l'accesso con pwd al link https://dptest.anpr.interno.it/combas con certificato 078102-CO-0000.p12 che risulta ok.
