### ISSUE TITLE
[4001] errore EN179, non trovo operazione precedente

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2099]
Buongiorno, 
per il comune di COLLI AL METAURO - PRODUZIONE, inviando una 4001 (idOperazioneANPR 260076506) torna errore EN179 (Richiesta non effettuabile: e' presente una richiesta dello stesso tipo non ancora lavorata)
solo che non riesco a trovare la richiesta precedente, forse bloccata.
Ho cercato dal portale in "monitoraggio operazioni" ma non ho trovato niente, dal gestionale ho rintracciato queste 2 ma non sono sicuro sia una di queste
 240846103
 260096911

 grazie mille
 Riccardo

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
potete riprovare per favore ?

**Comment by ricantonelli** [comment]
ora funziona correttamente.
grazie mille
