### ISSUE TITLE
Esito AE: Codice Fiscale non trovato (Codice 90)

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2100]
Comune di Montoro (AV)

cittadino Nigeriano: id 87028259, cf BNYJHN90R01Z335X

il codice fiscale del cittadino non risulta validato e la funzionalità "risoluzione disallineamento con Agenzia Entrate" restituisce la stringa in oggetto quando si effettua la ricerca tramite CF.

Cosa dobbiamo fare?
Grazie.

**Comment by frmariani** [comment]
il Codice Fiscale segnalato è stato calcolato dal vostro gestionale ma non è mai stato emesso dall'Agenzia delle Entrate ed è questo il motivo dell'errore; effettuate la mutazione dei dati anagrafici richiedendo l'attribuzione del codice fiscale. nel caso potete scrivermi in privato
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
