### ISSUE TITLE
Permesso di Soggiorno - RICHIESTA DOCUMENTI STORICI

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2103]
Buongiorno,
Ambiente di produzione. Sono state inviate due Mutazioni di tutti i dati per aggiornamento dei permessi di soggiorno, una per il cittadino 67254921 e una per il cittadino 67254922. 
Per il primo cittadino, IdOperazione 261800652, il nuovo permesso di soggiorno è stato correttamente caricato ma facendo la Richiesta Documenti Storici, non è più possibile visualizzare il permesso rilasciato dal precedente comune (comunque visibile nell'operazione ID 261701141).
Per il secondo cittadino, invece, IdOperazione 261834009, il nuovo permesso di soggiorno è stato correttamente registrato e andando nella Richiesta Documenti Storici è visibile anche il precedente permesso (visibile inoltre nell'idOperazione 261701162).
Perchè un cittadino sì e l'altro no? Forse perchè, banalmente, il precedente permesso aveva lo stesso numero?
resto in attesa di cortese riscontro
Saluti

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
abbia contattato il Comune per avere alcune informazioni circa il permesso di soggiorno permanente; come aveva giustamente notato, per una strana casualità allo stesso cittadino risulta un permesso di soggiorno rinnovato con la stessa numerazione, ed è per questo motivo che non viene visualizzato in consultazione. Stimo già apportando le modifiche del caso.

**Comment by frmariani** [comment]
il bug è stato risolto e sarà disponibile in ambiente di produzione a partire da mercoledì 17 Giugno 2020. La issue viene pertanto chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova  facendo riferimento a questa stessa.
