### ISSUE TITLE
Richiesta annullamento operazione num. 263626650

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2104]
Buongiorno.
Volevo annullare l'operazione num. 263626650 sul soggetto cod. 18938472.
Quali passi devo eseguire a sistema?

I miei riferimenti sono:
Andrea Paltrinieri - Ufficiale d'Anagrafe del Comune di BIASSONO (108009)
e-mail: paltrinieri.andrea@biassono.org
tel. 039/2201060

In attesa di un Vs. riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by ncapozzi** [comment]
Fornita assistenza telefonica per annullamento mutazione tutti i dati da web app.
