### ISSUE TITLE
Problema con cancellazione per decesso APR

### ISSUE THREAD

**Issue by DemograficiDianomarina** [italia/anpr#2105]
E' stata inserita una cancellazione per decesso APR imputando il luogo di decesso "VENTIMIGLIA" ora in interrogazione soggetto appare "morto accertato...TORINO" anche se nella scheda relativa al decesso c'è in effetti VENTIMIGLIA.
ID ANPR DEL SOGGETTO: 28163755

[problema ANPR.pdf](https://github.com/italia/anpr/files/4751800/problema.ANPR.pdf)

**Comment by frmariani** [comment]
interrogando il soggetto dalla web app di ANPR, il cittadino risulta deceduto a Ventimiglia; forse i dati che ha inviato con il pdf sono stati estrapolati dal suo gestionale, pertanto dovrebbe contattare la sua casa software.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
