### ISSUE TITLE
ELIMINAZIONE PERMESSO DI SOGGIORNO CITTADINO DIVENTATO ITALIANO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2106]
Buongiorno,
il soggetto con ID ANPR 76756444 ha chiesto iscrizione con decorrenza 02.06.2020 nel nostro comune con provenienza Belvedere Marittimo.
E' un cittadino italiano dal 18.12.2019 purtroppo però su anpr è ancora presente il dato relativo al permesso di soggiorno.
Il comune di provenienza è subentrato il 16.10.2018, il permesso di soggiorno presente in anpr è stato rilasciato il 12.11.2019, immaginiamo dunque che sia stato inserito attraverso una mutazione tutti i dati.
Purtroppo non ci è possibile eliminare il dato relativo al permesso di soggiorno in quanto il sistema espone msg "EN505- l'operzione di revoca è possibile solo a valle del subentro".
Quando si presentano dei casi analoghi nel ns comune, annulliamo la mutazione con cui è stato inserito o modificato il permesso di soggiorno e, successivamente, eseguiamo eliminazione dati per eliminare il permesso di soggiorno - con motivazione acquisto cittadinanza italiana.
C'è una soluzione per eliminare il dato senza dover annullare tutte le mutazioni del ns comune e la mutazione del comune di Belvedere Marittimo?
Sarebbe possibile prevedere l'eliminazione di tale dato anche non a valle del subentro?

Grazie
Cordiali Saluti
UpiTorino

**Comment by ncapozzi** [comment]
Buonasera,
il cittadino è stato iscritto in ANPR con una iscrizione per altri motivi e non con un subentro quindi la revoca non sarebbe consentita in ogni caso. Posso chiedere per quale motivo è necessario cancellare il permesso di soggiorno visto che andando in consultazione si vede chiaramente che è scaduto il 12/02/2020?

N. Capozzi

**Comment by UpiTorino** [comment]
Buongiorno,
purtroppo non è più possibile vedere le operazioni fatte sul soggetto da altri comuni, dunque abbiamo fatto supposizioni con i dati in nostro possesso.
Per quanto riguarda la richiesta di cancellazione del permesso deriva dal fatto che potrebbe essere un dato fuorviante in quanto potrebbe generare confusione; un cittadino italiano, che abbia anche già ottenuto una CIE con la cittadinanza italiana, non ha più titolo ad avere il permesso di soggiorno. 
Per quanto riguarda il comune di Torino, nello specifico, questi disallineamenti creati dalla presenza del permesso di soggiorno per un cittadino italiano, inibiscono la certificazione attraverso il portale TorinoFacile.

Cordiali Saluti
UpiTorino

**Comment by ncapozzi** [comment]
Buongiorno,
in un caso precedente analogo al vostro abbiamo avuto la conferma dal Ministero dell'Interno che il permesso di soggiorno rimane agli atti e non c'è nessun motivo di cancellarlo. Inoltre in ANPR non c'è nessun blocco della certificazione per la presenza del permesso di soggiorno, che oltretutto nel vostro caso è già scaduto. Pertanto sembrerebbe più un problema del portale TorinoFacile.

N. Capozzi
