### ISSUE TITLE
[3002] Consultazione Soggetto: doppio tag "Residenza"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2107]
ambiente di PRODUZIONE - comune di SABBIONETA (020054)

idSoggettoANPR 75775478

il web-service di consultazione ritorna due tag di tipo "Residenza" collegati al soggetto:
- uno corrisponde all'attuale residenza a Sabbioneta
- uno corrisponde alla residenza nel comune di provenienza (PIADENA DRIZZONA)

(idOperazioneComune 2020300457)

forse è la prima volta che ci succede... è normale come situazione?

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera,
la situazione è dovuta ad un bug. La correzione sarà disponibile in ambiente di produzione a partire dal 17 giugno prossimo.

N. Capozzi
