### ISSUE TITLE
Annullamenti mutazioni famiglia bloccati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2109]
Ambiente di produzione, comune di Pesaro

Dobbiamo annullare due mutazioni famiglia 5001 che hanno alterato l'indirizzo di due convivenze. Si tratta delle operazioni ID ANPR 254637418 e 254667738. 
Tentando di farlo da webapp veniamo fermati da "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077)" (Informazioni sull'operazione da fornire in caso di assistenza : data 2020-06-09 16:51:28 , idOperazioneANPR 263946815 (Codice: EN527))

Potete aiutarci a capire quali sono le operazioni bloccanti ? 

Grazie

**Comment by frmariani** [comment]
prima di eliminare l'operazione idanpr 254637418 dovrete eliminare l'operazione idanpr 261137840; prima di eliminare l'operazione idanpr 254667738 dovrete eliminare l'operazione idanpr   260063793.
Fatemi sapere.

**Comment by busaster** [comment]
Per il caso della 254637418 non riusciamo a risolvere : l'operazione 261137840 non la troviamo nell'elenco utilità->notifiche->monitoraggio operazioni,  per cui non sappiamo di che tipo è e di quale cittadino si tratta, non riuscendo quindi ad annullarla da webapp.

Per il caso della 254667738 invece abbiamo risolto annullando prima la 260063793.

**Comment by frmariani** [comment]
l'operazione idanpr 261137840 è una mutazione di residenza (ws 5005) per il soggetto idanpr 42359988

**Comment by busaster** [comment]
Purtroppo il soggetto non è più residente a Pesaro e on è possibile annullare quella mutazione.

**Comment by frmariani** [comment]
se vuole possiamo sentirci per cercare una soluzione alternativa.

nel caso mi scriva il suo contatto telefonico al seguente indirizzo frmariani@sogei.it

**Comment by frmariani** [comment]
siamo in contatto telefonico per la risoluzione del problema.
