### ISSUE TITLE
ws [7001] - tabella comuni subentrati

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#211]
Buon giorno,
secondo le indicazioni fornite nell'issue #210 , abbiamo tentato di scaricare la tabella dei comuni subentrati, ma a fronte di una request valida, generata con IdTabella = '045' (id operazione comune 1881), otteniamo nella response un errore 999 - Operazione non effettuabile. Riusciamo invece a scaricare le altre tabelle, disponibili in formato zip e successivamente estratte secondo le vostre indicazioni (vedi bug #206).
Il test è stato effettuato in data 14/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Puo' riprovare

**Comment by Amucciarelli74** [comment]
Ora funziona, grazie.
Il test è stato effettuato in data 14/06/2017 (id operazione comune 1888, 1891), in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.
