### ISSUE TITLE
Annullamenti in autotutela

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#2110]
Buongiorno,

avremmo bisogno di informazioni in merito agli annullamenti in autotutela.
Un nostro cliente ha cancellato un cittadino per mancata dichiarazione dimora abituale a Febbraio.  Successivamente, ad Aprile il comune ha dovuto annullare la cancellazione fatta a febbraio in autotutela.
Come dovrebbe essere la gestione corretta da utilizzare in questi casi? Devono essere annullati gli invii fatti a febbraio e ripristinato il cittadino oppure è necessario fare una iscrizione per altri motivi ad aprile con decorrenza febbraio in quanto con l'annullamento in autotutela è come se la cancellazione non fosse mai avvenuta?
Avremmo necessità di capire come avete strutturato la gestione di questi casi.

Grazie
Marco Sala

**Comment by frmariani** [comment]
Buongiorno, di solito lasciamo che siano i Comuni ad utilizzare le operazioni come ritengono più opportuno e secondo le esigenze amministrative del caso. Le operazioni di annullamento nel sistema ANPR non hanno delle motivazioni, pertanto gli "annullamenti per autotutela" non esistono; per quanto riguarda le operazioni di cancellazione, immagino che il suo cliente, a Febbraio abbia cancellato il cittadino con motivazione " Mancato rinnovo dimora abituale/permesso di soggiorno" oppure "Altro" specificando il motivo della cancellazione nelle note annesse. Annullando l'operazione di cancellazione, il Comune non avrà più evidenza dell'operazione di cancellazione stessa, pertanto il cittadino risulterà residente nel Comune in maniera continuativa; cancellando il cittadino e re-iscrivendolo (la sua seconda ipotesi se ho capito bene), rimarrà la traccia delle operazioni effettuate anche se le date daranno al cittadino una continuità della residenza nel comune. Nel caso volesse un chiarimento telefonico, può inviarmi il suo recapito al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
