### ISSUE TITLE
errata denominazione in tabella comuni ANPR - comune di PERDERZANO (TN) 

### ISSUE THREAD

**Issue by eleb2018** [italia/anpr#2111]
Il comune di Villa Lagarina (Tn) ci ha fatto notare che nella tabella comuni di ANPR il comune di PEDERSANO (TN) è riportato con descrizione errata: PEDERZANO anzichè PEDERSANO
CODISTAT 802338 - CODCATASTALE G049 - PEDERZANO 
CODISTAT 022883 - CODCATASTALE G049 - PEDERZANO 
Potete aggiornare la tabella?
Grazie e buon lavoro
Elena Bertani

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.

**Comment by MassimoSchiappa** [comment]
Salve,
la fonte primaria per i dati relativi ai comuni è Istat, che attualmente riporta esattamente la stessa denominazione che è mostrata in ANPR per il comune in questione. Se avete della documentazione ufficiale che dimostra l'errore, allora potete scrivere a Istat (ambienteterritorio@postacert.istat.it ), per chiedere la rettifica dei dati, La rettifica di ANPR andrà di conseguenza.
Cordiali Saluti.
