### ISSUE TITLE
[3007] Consultazione notifiche

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2112]
Buongiorno. Abbiamo la necessità di consultare le notifiche di un comune, fino ad ora abbiamo pubblicato sempre il server in ascolto e le notifiche ci venivano inviate. Adesso abbiamo la necessità di invocare noi un servizio per scaricare le notifiche. Considerando che il servizio 3007, risulta essere deprecato, visto che ci risponde in ambiente di presubentro con: "Funzionalita' non supportata Modalita' di interrogazione non piu' supportata a partire da ANPR02". Possiamo leggere le notifiche con un altro servizio?

**Comment by mttfranci** [comment]
Salve, il servizi 3003/3007 sono ancora attivi solo per le richieste puntuali. per le richieste con intervalli temporali sono stati sostituiti dal servizio asincrono 4005 : 

https://github.com/italia/anpr/issues/1161

Siamo a disponibili per ogni ulteriore chiarimento.
