### ISSUE TITLE
Ambiente di Test non disponibile

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2115]
Buongiorno,
segnalo che da venerdì non riusciamo più ad accedere all'ambiente di Test,
dopo la login abbiamo il messaggio _"Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi"_.
Chiedo quando potrà essere ripristinato il servizio.
Grazie

MAGGIOLI INFORMATICA

**Comment by Eduardo1977** [comment]
Buongiorno, anche noi riscontriamo lo stesso problema. Chiediamo, gentilmente, che venga ripristinato il prima possibile. Grazie

**Comment by FilippoPapi** [comment]
l'ambiente è stato ripristinato
saluti
