### ISSUE TITLE
[3002] Ricerca ad una data passata ritorna i dati odierni 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2116]
Ambiente di produzione.

Vogliamo ottenere parte della scheda individuale del soggetto ID ANPR 19553463 alla data 2018-11-29, per cui effettuiamo una chiamata al servizio 3002 (id operazione ANPR 266563092).
Nel valore di ritorno però ci viene riportata la residenza valida ad oggi (data decorrenza residenza 2020-05-20). 
Noto che il soggetto in quella data è migrato nel nostro comune con provenienza altro comune subentrato.
Il certificato di residenza storico riporta le residenze corrette.

Come mai ?

**Comment by frmariani** [comment]
Abbiamo verificato che c'è stato un piccolo problema nella visualizzazione dei dati del soggetto.
Abbiamo eliminato l'anomalia;  potete riprovare la consultazione per favore ?

**Comment by busaster** [comment]
Confermo che ora la ricerca ritorna il dato atteso. 
Grazie
