### ISSUE TITLE
[EN531] Operazione non consentita: per il soggetto esiste un procedimento aperto

### ISSUE THREAD

**Issue by DavideSalvi80** [italia/anpr#2117]
Buongiorno, scrivo per conto del Comune di Reggio Calabria e nella fattispecie per evidenziare la seguente problematica: non è possibile provvedere alla definizione di una pratica di cambio di residenza in quanto ANPR ritorna il messaggio di errore "[EN531] Operazione non consentita: per il soggetto esiste un procedimento aperto".
Di seguito i riferimenti alla pratica:

CodiceErroreAnomalia: EN531
tipoErroreAnomalia: E
testoErroreAnomalia: Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune BEE (VB) con numero pratica ANPR: 22027019
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-06-11 16:09:44 , idOperazioneANPR 265627566
-------------
Sentendo il Comune ed il numero verde 800863116, in merito alla soluzione della problematica  si fa riferimento ad un portale SOGEI che consenta l'annullamento del procedimento rimasto appeso.
Si attende cortese riscontro in merito.

**Comment by frmariani** [comment]
Il Comune di Reggio Calabria non può definire la pratica del cambio di residenza perchè il Comune di provenienza, BEE, non ha ancora chiuso il procedimento amministrativo aperto in fase d'iscrizione del cittadino nel suo comune. Immagino che il portale Sogei a cui fa riferimento sia la web app di ANPR dove, il comune di BEE, potrà chiudere il procedimento segnalato nell'errore.
Il comune di Reggio Calabria dovrà contattare il Comune di provenienza e segnalare la problematica emersa  fornendo il numero del procedimento per facilitare l'operazione di chiusura (numero procedimento amministrativo 22027019). Nel caso fosse necessaria assistenza durante l'operazione, il Comune di BEE potrà contattare il numero verde 800863116.

**Comment by DavideSalvi80** [comment]
Grazie per la pronta risposta. Siamo un Comune subentrato nel dicembre 2019 ed utilizziamo quotidianamente sia l'applicativo connesso in modalità WS con ANPR che la web app  per la risoluzione di alcuni disallineamenti, pertanto ci sembrava al quanto strana la risposta del Comune di BEE.
