### ISSUE TITLE
Modificare dati permesso di soggiorno

### ISSUE THREAD

**Issue by ComuneRoccastrada** [italia/anpr#2119]
Buongiorno, sono Sonia Masini del comune di Roccastrada (GR).

Ho necessità di modificare i dati di un permesso di soggiorno che ha l'anno di emissione errato. Quando però cerco di accedere alla pagina di variazione dei dati del soggetto, in alto mi esce la scritta "Permesso di soggiorno Data rilascio non è valida oppure il formato non e' gg/mm/aaaa"

Quale punto di menù della webapp devo utilizzare per poter effettuare la rettifica dell'anno di emissione?

Grazie mille
Sonia Masini
Ufficiale di Anagrafe
Comune di Roccastrada

**Comment by ncapozzi** [comment]
Buongiorno,
può indicare l'idsoggetto ANPR per favore?

**Comment by ComuneRoccastrada** [comment]
ID:88516296 DATA ESATTA RILASCIO PERMESSO DI SOGGIORNO 15.04.2016

**Comment by ncapozzi** [comment]
Il comune è stato contattato telefonicamente ed è stata fornita assistenza per l'aggiornamento data rilascio del permesso di soggiorno.

N. Capozzi
