### ISSUE TITLE
Cittadino doppio in consultazione famiglia

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#212]
Id anpr 1245763, se vado in consultazione scheda > famiglia > elenco componenti, vedo la madre doppia, una volta come IS e una volta come tutore. 
Il cittadino non è nostro, è di un altro comune, non ho quindi idea se sia stato inviato due volte in subentro o sia una casistica strana dovuta ai vari test.

**Comment by gcarbonin** [comment]
Nel subentro la persona è stata inserita sia come intestatario che come tutore
