### ISSUE TITLE
Mutazione Residenza AIRE cittadino straniero?

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2120]
Nel comune ente gestore codice Istat 044007 è residente in APR un nucleo composto da 6 cittadini, di questi 6 cittadini 5 risultano essere di cittadinanza ITALIANA uno di cittadinanza BRASILIANA.

Il comune riceve dal consolato richiesta di iscrizione AIRE ed erroneamente invia un operazione di Mutazione Residenza AIRE ( id operazione comune 5442175) anche per il cittadino straniero (Id Scheda Sogg Anpr 61421388).

Il cittadino straniero non solo viene iscritto in AIRE, ma con data decorrenza uguale alla data decorrenza dell'operazione di Mutazione Residenza AIRE acquista cittadinanza ITALIANA.

Potete verificare?

E' necessario prevedere un blocco nella Mutazione Residenza AIRE per i cittadini con cittadinanza <> da ITALIANA.

**Comment by ncapozzi** [comment]
Buongiorno,
non è richiesto che al momento dell'iscrizione AIRE venga espressamente indicata la cittadinanza italiana per il cittadino in quanto implicita nell'iscrizione AIRE. Presupponendo che il Comune sia certo che il cittadino che sta iscrivendo all'AIRE sia cittadino italiano, si inserisce di default tale cittadinanza. In caso di errore, il comune può sempre annullare l'operazione.

N. Capozzi

**Comment by RBiasi** [comment]
Buongiorno,

annullando l'operazione di Mutazione Residenza AIRE la cittadinanza non torna straniera, ma rimane impostata a ITALIANA.

**Comment by ncapozzi** [comment]
Buongiorno,
l'annullamento della residenza estera non prevede anche quello della cittadinanza. Il comune può effettuare una mutazione 5008 con tipo = 2 oppure eseguire analoga operazione da web app
