### ISSUE TITLE
RICHIESTA DI CERTIFICATO PER UN AMBIENTE DI TEST https://anpr-test.bobuild.com/request

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#2121]
Salve. 
Se non vado errato l' 8/6/2020 ci siamo registrati presso  https://anpr-test.bobuild.com/request 
usando la mail dell' ufficio ( edoardo.dona@datamanagementitalia.it).
Ad oggi non ho ricevuto nulla. 
Manca qualcosa ? 
Che tempi ci sono ?
Si riceve un certificato di tipo ....0000.p12 e login e pwd ? 
Dobbiamo fornirvi dei requisiti particolari ? 

GRAZIE 
Edoardo Dona' 
Datamanagemente Italia SPA

**Comment by Leonforte** [comment]
Salve, il sito in questione dove avete richiesto le credenziali è gestito dal team digitale ANPR, potete inoltrare la richiesta a segnalazioni-anpr@teamdigitale.governo.it, buon lavoro
