### ISSUE TITLE
chiarimento disponibilità risposta operazioni asincrone max 24h

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2122]
Buonasera,
è chiaro che le elaborazioni asincrone vengono elaborate entro le 24 ore, ma capita a volte che queste non superate le 24 ore non sono disponibili es. #2099. 
Mi chiedevo passate le 24 ore le richieste non elaborate possono comunque essere disponibili oppure sono "perse"?
nel caso in cui passate le 24 ore senza risposta non sarebbe possibile bloccarle e quindi tornare una risposta differente da una nuova data disponibilità e rendere possibile nuove operazioni altrimenti bloccate (#2099)?

grazie mille
Riccardo

**Comment by mttfranci** [comment]
Salve, al momento non sappiamo di richieste asincrone "perse".
Potete fornirci una o più id operazioni di richieste che vi risultano affette da questo problema?
In generale riscontrate questo problema su quale tipologia di operazioni? (es. 4005)?
Grazie in anticipo.

**Comment by ricantonelli** [comment]
Salve, si il problema si verifica principalmente per le 4005.

un esempio 
richiedendo i risultati oggi per l'operazione 16721696  
<dataOraRichiesta>2020-06-18T10:37:25</dataOraRichiesta>
<idOperazioneANPR>17270811</idOperazioneANPR> 

ho disponibilità 2020-03-11T12:24:09

comune 041010 - presubentro

**Comment by ricantonelli** [comment]
Buongiorno, 
un altro esempio è l'operazione 151580086 per il comune 018153 in SUBENTRO
che con idOperazioneANPR 273300915 
risponde dataDisponibilita 2019-11-12T00:58:18.000

**Comment by mttfranci** [comment]
Salve, allora abbiamo verificato, in effetti il messaggio è errato.
In sostanza la fornitura è stata elaborata in data 2019-11-12T00:58:18.000.
Ma le forniture prodotte sono disponibili solo per circa 3 mesi.
Dopo tale termine se necessario ne va richiesta nuovamente la produzione.
Provvederemo a rendere il messaggio più chiaro.
Siamo a disposizione per ogni ulteriore chiarimento.

Assistenza ANPR.

**Comment by ricantonelli** [comment]
ok grazie 
buona giornata
