### ISSUE TITLE
WS 3002 - Servizio non disponibile

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2123]
Buonasera, da circa un'ora le chiamate del portale online ai servizi ANPR restituiscono "Servizio non disponibile". 
Potreste effettuare qualche controllo su idoperazionecomune: SmartANPR1004696 ?
Grazie

Comune di Altamura

**Comment by mttfranci** [comment]
Salve potreste riprovare? ora dovrebbe essere tutto a posto.

**Comment by Eduardo1977** [comment]
faccio subito. grazie mille

**Comment by Eduardo1977** [comment]
Tutto OK. Grazie ancora. Potete controllare con IdOperazioneComune: SmartANPR1004705
Buona serata
