### ISSUE TITLE
Errore variazione comune di nascita in stato non esistente

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2124]
Salve buongiorno,
dovremmo effettuare una variazione del comune di nascita di un cittadino in ambiente di produzione per il comune di Matera (cod. istat: 077014). Siccome il cittadino ha il codice fiscale tra le mani che finisce con Z118 (SERBIA E MONTENEGRO - stato non più attivo) noi facciamo una variazione del comune di nascita variando sia il comune di nascita sia il codice fiscale in modo che corrispondano entrambi al codice Z118 e quindi al codice fiscale rilasciato, che il cittadino possiede fisicamente e che abbiamo visionato. Purtroppo durante la variazione, riceviamo una serie di errori (data 2020-06-17 13:18:08 , idOperazioneANPR 270181764) come possiamo procedere?

**Comment by ncapozzi** [comment]
Buongiorno,
il CF del cittadino e il nuovo CF che il comune sta cercando di assegnare non sono collegati in Agenzia delle Entrate, se effettivamente corrispondono allo stesso cittadino è necessario procedere al loro collegamento come indicato al par. 4.1 del documento  “APPENDICE VALIDAZIONE DEL CODICE FISCALE E DEI DATI ANAGRAFICI E RISOLUZIONE DEI DISALLINEAMENTI CON L’AGENZIA DELLE ENTRATE” disponibile al link https://www.anpr.interno.it/portale/documentazione-tecnica

N. Capozzi

**Comment by ncapozzi** [comment]
Facciamo presente anche che il nuovo CF che avete indicato nel 5008 corrisponde ad un cittadino nato in Iugoslavia quindi facendo il collegamento suggerito in ANPR risulterebbe il nuovo CF con Iugoslavia.

In generale suggeriamo di segnalare questo tipo di  problematiche al numero verde di assistenza in modo da poter contattare telefonicamente il comune per tutti i chiarimenti necessari.
