### ISSUE TITLE
[6001] Certificazione bloccata da anomalia al subentro

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2125]
ambiente di PRODUZIONE - comune di RUBIERA (035036)

idSoggettoANPR 38716466

in consultazione il soggetto presenta un'anomalia da subentro del tipo
EC075 - 1 - Comune di registrazione dell'atto di nascita:POZZILLI(IS) non esistente alla data

non è chiaro se dipenda da questo, ma eseguendo richieste di certificazione (residenza o stato di famiglia), il servizio risponde con errore bloccante:
EN087 - E - La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti

idOperazioneComune 2020600512 (x stato di famiglia)
idOperazioneComune 2020600513 (x certificato di residenza)

potete verificare e aiutarci a capire?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Non c'è nessun problema sulla scheda del cittadino in quanto anche se segnalato è previsto che il soggetto possa risultare nato in un comune non valido alla data o abbia un'incongruenza sulla provincia. Il problema è nella richiesta del certificato dove, tra i dati anagrafici è riportato come comune di nascita Pozzilli(CB). Questo crea l'incongruenza.

**Comment by AMonopoliADS** [comment]
ok. ho visto.
in effetti partiva il luogo di nascita coerente con la data di nascita, ma non coerente con la posizione ANPR, seppure anomala.
abbiamo risolto.

grazie
