### ISSUE TITLE
[1002] Errore EN531 in iscrizione per ricomparsa

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2126]
Ambiente di produzione, comune di Monopoli

perfezionando una pratica di iscrizione per ricomparsa da altro comune di un cittadino attualmente con posizione ANPR di cancellato otteniamo l'errore : "EN531 : Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune @ con numero pratica ANPR: @".
Id operazione ANPR 272316151.

Qual è il comune che ha aperto il procedimento ? Nel messaggio non c'è...

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
idprocedimento 25063879 del comune di Putignano di precedente residenza.
Stiamo verificando il motivo per il quale le informazioni non vengono restituite nel msg di errore.

**Comment by ncapozzi** [comment]
Buonasera,
il problema era già noto ed è stato risolto con il rilascio della versione 5.10.5 avvenuto venerdì sera.
N. Capozzi
