### ISSUE TITLE
Segnalazione Doppia posisine in ANPR con posizione già cancellata per doppia iscrizione.

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#2127]
Comune di Cagliari

Buongiorno,
una cittadina, nostra residente ci segnala che accedendo al portale ANPR non le viene consentito di fare una visura perché ci sono 2 posizioni censite in ANPR col suo codice fiscale e le viene detto di contattare il comune di residenza.

Dalle verifiche fatte, la cittadina, attualente nostra residente, risulta effettivamente con 2 posizioni in ANPR, ma una delle due è già stata cancellata per doppia iscrizione dal comune di precedente residenza che è subentrato gli stessi giorni in cui la cittadina richieddeva l'iscrizione in questo comune.
Si segnala inoltre che all'INPS risulta l'iscrizione nel nostro comune e una successiva cancellazione  per irreperibilità su segnalazione del comune di precedente residenza (che ovviamente si riferisce alla cancellazione per doppia iscrizione).

E' normale che venga segnalata l'anomalia in ANPR nonostante una scheda sia stata già cancellata per doppia iscrizione?
Potete verificare come mai all'INPS la cancellazione per doppia iscrizione viene gestita come cancellazione per irreeribilità?

Si rimane in attessa di un vostro risconrtro e a disposizione per qualunque ulteriore chiarimento o dettaglio..

Cordiali Saluti
Andrea Demeglio
Comune di Cagliari

**Comment by ncapozzi** [comment]
Buonasera,
per effettuare delle verifiche è necessario avere almeno l'idsoggetto ANPR del cittadino interessato. In generale è bene segnalare il problema al nostro numero verde e non su github se si tratta di un caso specifico per il quale è necessario comunicare dati anagrafici al fine di procedere alle verifiche necessarie.

**Comment by ncapozzi** [comment]
Buongiorno,
gli unici controlli che possiamo fare sono sulla correttezza dei dati inviati ad INPS e sul corretto invio delle notifiche.  Tutti gli eventi anagrafici relativi ai due diversi identificativi soggetto sono stati regolarmente notificati ad INPS. Non siamo a conoscenza delle elaborazioni interne fatte dall’Istituito sui dati inviati. E' necessario pertanto  rivolgersi all’Istituto per le opportune verifiche rappresentando che dai controlli effettuati da  Sogei le relative comunicazioni risultano tutte correttamente inviate da ANPR ad INPS.

Per quanto riguarda l'errore ricevuto dalla cittadina sulla visura anagrafica stiamo provvedendo a correggere l'anomalia

**Comment by ncapozzi** [comment]
Buongiorno,

l'errore ricevuto dalla cittadina sulla visura anagrafica è stato corretto. Potete dirle di riprovare

N. Capozzi

**Comment by andemeglio** [comment]
Buongiorno e Grazie 

A. Demeglio
