### ISSUE TITLE
Comune di Ancona - Richiesta chiarimenti su funzione "Richieste di allineamento dati trasmesse dai consolati"

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2128]
Buongiorno, sono l'ALS del Comune di Ancona che è in fase di pre-subentro. Ci è arrivata una notifica in ambiente di produzione riguardo alla richiesta di allineamento dati trasmessi dai consolati per il rilascio delle carte di identità elettroniche ai cittadini AIRE. Pur avendo abilitato tutti i miei operatori con smart card alla voce di menù "operatore comunale servizi di utilità" nessuno di loro riesce ad accedere alla funzione di utilità nell'ambiente di produzione e neanche io che ho tutte le funzioni abilitate. Dipende forse dal fatto che siamo ancora in pre-subentro? Attendo un vostro riscontro in merito. Grazie e saluti. Ferretti Laura

**Comment by ncapozzi** [comment]
Buongiorno,
al momento la funzionalità è abilitata solo per i comuni subentrati. Stiamo procedendo per estendere l'abilitazione anche ai non subentrati.

**Comment by ncapozzi** [comment]
Buongiorno,
l'aggiornamento è stato effettuato. Ora potete accedere alla web app, utilità e notifiche, Richieste di allineamento dati trasmesse dai consolati

N. Capozzi
