### ISSUE TITLE
ISCRIZIONE CITTADINO AIRE RESIDENTE IN ALTRO COMUNE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2129]
DAL CONSOLATO ARRIVA UN CONS. CON L'INDICAZIONE DI ISCRIZIONE ALL'AIRE DEL CITTADINO ID. SCHEDA ANPR 70465304 - ID. ATTRIBUITO ALLA SCHEDA DAL COMUNE DI PETROSINO  9006 - DAL COMUNE DI PETROSINO DOVE RISULTA RESIDENTE AL COMUNE DI MARSALA PER ISCRIVERLO ALL'AIRE - DALLA WEBAPP VADO SU REGISTRAZIONE - POI SU ISCRIZIONE PER ALTRI MOTIVI (AIRE) ALLA FINE MI DA QUESTO MESSAGGIO : il Soggetto MTSGPP03P21E974T, MOTISI, GIUSEPPE, 21/09/2003, 081011 e' gia' iscritto o deceduto Codice: EN187.
Premetto che Il soggetto è stato  iscritto all'aire nell'anagrafe locale di Marsala scollegandolo da ANPR, di conseguenza risulta in ANPR residente a Petrosino, nell'anagrafe locale iscritto all'aire. Domanda: devo procedere dalla webapp scollegando l'anagrafe locale?
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-06-24 08:56:14 , idOperazioneANPR 275359854 Codice: EN527
Filippo Asaro
0923993382
asaro.filippo@comune.marsala.tp.it

**Comment by ncapozzi** [comment]
Buongiorno,
per trasferire all'estero un cittadino residente in Italia, anche in un comune diverso, e già presente in ANPR non deve utilizzare l'iscrizione AIRE ma la mutazione dati AIRE WS A006 che può essere richiamata sia dal gestionale che dalla web app.

N. Capozzi

**Comment by ncapozzi** [comment]
Si raccomanda di non indicare nelle issue i dato in chiaro dei cittadini interessati.
