### ISSUE TITLE
[5001] Errore in mutazione parentela

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#213]
Pisa, Ambiente di test

Buongiorno, abbiamo reiscritto un individuo già precedentemente in ANPR, l'immigrazione con il servizio 1002 è andata a buon fine ed il soggetto è stato iscritto in ANPR.
Successivamente abbiamo fatto una variazione di parentela per il medesimo soggetto e ci ha dato errore: EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata. Verificato che il soggetto abita da solo in una famiglia ed è stato passato unicamente lui nella request non riusciamo a spiegarci l'errore.
Allego request e response di iscrizione e mutazione, grazie.
Luca Bonini A.P.Systems
[famigliediverse.zip](https://github.com/italia/anpr/files/1075277/famigliediverse.zip)

**Comment by gcarbonin** [comment]
Stiamo ricercando di riprodurre il problema senza successo. facendo le stesse operazioni la re-iscrizione va a buon fine. Proseguiamo con i test.

**Comment by gcarbonin** [comment]
Abbiamo necessità di fare una prova congiunta. Ci sentiamo lunedì

**Comment by gcarbonin** [comment]
Risolto con un caso simile (cognome e nome non coincidevano)
