### ISSUE TITLE
Errore Iscrizione APR (procedimento aperto su altro comune)

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2130]
Comune di Montoro (AV)
Non riusciamo ad iscrivere il cittadino id: 80078860
data: 2020-06-24 11:45:38 idOperazioneANPR: 275629038

Esiste un procedimento aperto dal Comune di Sesto San Giovanni. Come possiamo risolvere?

**Comment by ncapozzi** [comment]
Buongiorno,

è necessario contattare il Comune di Sesto San Giovanni e chiedere la chiusura del procedimento il cui id ANPR è indicato nel messaggio di errore.

N. Capozzi
