### ISSUE TITLE
Errore registrazione matrimonio

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2131]
Buongiorno,
avrei la necessità di registrare in anagrafe il matrimonio di una cittadina straniera (codice anpr 91081302) coniugata con un cittadino italiano (codice anpr 19156651) residente in questo comune, di cui il loro atto è già stato trascritto in Italia è già inviato in ANPR per il marito.
Siccome la data di nascita della cittadina straniera è stata inviata in modo errato nel momento della registrazione dell'atto di matrimonio ora mi trovo in difficoltà quando devo inviare in Anpr il matrimonio per lei. Nello specifico mi sono usciti queste tipologie di errore:

**E | EN272** | Alla data 13-11-2019 il soggetto XXXXX risulta gia' coniugato o unito civilmente con un altro soggetto
-- | -- | --
**E | EN527** | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-06-24 11:27:41 , idOperazioneANPR 275598045

Ringrazio per la collaborazione. Cordiali saluti

**Comment by frmariani** [comment]
ci sono una serie di errori da evidenziare:
l'idOperazioneANPR 275598045 è un'iscrizione anagrafica, che non può essere effettuata per una cittadina già presente in ANPR; l'errore nella registrazione dell'atto di matrimonio del marito non è stato sulla data di nascita della signora, ma sul codice fiscale, pertanto dovrete effettuare la seguente  operazione:
dalla web app di ANPR, dai servizi di Registrazione effettuate una Mutazione tutti i dati sul marito, codice anpr 19156651; modificate correttamente la data dell'operazione e nel dati di controllo selezionate  "Matrimonio"; nei dati del coniuge, inserite il codice fiscale corretto della signora e confermate la pagina; il salva e chiudi aggiornerà i dati del matrimonio per entrambi i coniugi.
nel caso non fosse chiaro il procedimento, inviate un contatto telefonico al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
