### ISSUE TITLE
Mutazione Residenza APR per cittadino privo di CF

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2132]
Buongiorno,

l'ente codice ISTAT 044007 lamenta difficoltà nell'effettuare una mutazione di Residenza APR per il cittadino Id ANPR 82070588.

Il cittadino è al momento AIRE del comune 058104 e risulta subentrato senza Codice Fiscale.

E' corretto? Il codice fiscale non è dato obbligatorio?

Dobbiamo prevedere anche questa possibile mancanza di Codice fiscale? Per tutti i cittadino o solamente per i cittadini AIRE è possibile non sia compilato il Codice Fiscale?

Attendo Vs. gentile riscontro.

Grazie

**Comment by rvinzani** [comment]
Per i cittadini AIRE è da prevedere che questi non siano in possesso di un codice fiscale ovvero che lo abbiano ma non validato perchè semplicemente calcolato dal gestionale. In teoria anche i cittadini residenti potrebbero non avere un CF o non averlo validato anche se tali casi sono da sanare. In questi casi le iscrizioni o le mutazioni dei dati anagrafici possono essere effettuate impostando e 3 la gestione del CF (non richiesta validazione). Le operazioni di cambio di residenza, cancellazioni o le mutazioni di dati diversi dai dati anagrafici non richiamano i servizi di validazione/variazione di agenzia entrate, quindi non sono  condizionati dalla presenza o dalla validità del CF
