### ISSUE TITLE
[6001] - Errore EN043  - Sono presenti piu' soggetti

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2133]
Buongiorno, il portale online del Comune di Altamura riceve l'errore EN043  "Sono presenti piu' soggetti corrispondenti ai dati anagrafici inseriti" dal servizio WS6001, quando l'intestatario del certificato è "MN...MR...98". Eppure nella request tra i dati del "soggettoIntestatario" vengono passati "codiceFiscale", "cognome", "nome", "idSchedaSoggettoANPR". Non funziona neanche se si utilizza "forzaCertificazione". Vi fornisco gli "idOperazioneComune" (ServLoc1118023, ServLoc1118025) degli ultimi due tentativi fatti poco fa con e senza "forzaCertificazione". Grazie

**Comment by Eduardo1977** [comment]
Buongiorno, se può essere d'aiuto aggiungo che anche il servizio 3002 tramite consultazione con codice fiscale  "MN...MR...98" restituisce effettivamente due soggetti con "idSchedaSoggettoANPR" diverso.  E' una situazione che può sanare l'ufficio anagrafe? Grazie

**Comment by ncapozzi** [comment]
Buonasera,

per effettuare una verifica occorre l'idoperazione anpr oppure l'idsoggetto ANPR. In ogni caso i due comuni interessati alla duplicazione, accertato che si tratta dello stesso cittadino, devono stabilire chi dei due deve effettuare la cancellazione per doppia iscrizione (WS 2003)

**Comment by Eduardo1977** [comment]
Buonasera, grazie per il chiarimento. Gli IdOperazioneANPR comunque sono: 276164598, 276183396.
