### ISSUE TITLE
[WebApp] Iscrizione di nato in comune non valido alla data

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2134]
Buongiorno
A fini di test, ho simulato dalla web application ambiente test, l'iscrizione altri motivi di persona dove nel luogo di nascita, utilizzo la nuova funzione "Comuni non validi alla data". Come data di nascita indicata 03/03/1963. L'iscrizione non va a buon fine con questi errori. Visto lo scopo della videata, non mi spiego gli errori.

Comune/provincia di nascita ERCOLANO (NA) inesistente o non valido alla data di nascita (Codice: EN332)

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-06-25 11:04:11 , idOperazioneANPR 26669716 (Codice: EN527)

**Comment by ncapozzi** [comment]
Buongiorno,
il comune di nascita non valido alla data di nascita è ammesso solo se il cittadino è già in possesso di un CF indicato nella richiesta di iscrizione e già attribuito da Agenzia delle Entrate per quel particolare comune. In tutti gli altri casi il comune indicato deve essere valido alla data di nascita

N. Capozzi
