### ISSUE TITLE
Certificato di stato libero per cittadini stranieri

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2136]
Buongiorno,

un comune ci richiede se sia corretto produrre il certificato di stato libero anche per cittadini stranieri con stato civile celibe/nubile.

In alternativa ci richiede di poter variare lo stato civile di questo cittadino straniero da celibe/nubile a non classificabile.

Grazie

**Comment by rvinzani** [comment]
Dal punto di vista tecnico rispondo sì ad entrambi i quesiti. Se poi la richiesta è di tipo normativo è consigliabile rivolgersi al Ministero
