### ISSUE TITLE
IMPOSSIBILITA' UTILIZZO ELENCO CITTADINI IN FORMATO .GZ

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2138]
In data odierna abbiamo richiesto l'estrazione di un elenco di cittadini al quale è stato attribuito l'identificativo 277028303. Ci è stato restituito il file 037061_Elenchi_Fri Jun 26 11_30_15 CEST 2020.gz
Al tentativo di aprirlo con ZIP, il messaggio di errore che compare è il seguente: 
Impossibile aprire il file 037061_Elenchi_Fri Jun 26 11_30_15 CEST 2020 come archivio.
Il nostro servizio informatico, interpellato in proposito, ci ha spiegato che i files in formato .gz non sono utilizzabili dal nostro sistema windows. Si chiede quindi se sia possibile ricevere i files in formato .zip .7z .rar o similari

**Comment by fcastellani81** [comment]
Ho avuto lo stesso problema. Aprendo però il file con un editor di testo il file è visibile (ma non risulta correttamente formattato a livello xml). Per aprirlo correttamente come file xml è necessario, almeno secondo la mia esperienza, apporre un tag all'inizio del contenuto del file (es. <file>) ed un tag alla fine del contenuto del file (es. </file>)

**Comment by mttfranci** [comment]
@iolandacavallin  Le forniture elenchi di cittadini non sono compresse. Potete aprirle direttamente con un editor (al netto di questo è possibile aprire i file gzip anche su windows, personalmente apro senza problemi i file GZ da linea di comando, con 7zip e con winrar).

Ad ogni modo il file è un file XML valido, visto che non comporta problemi di privacy ne riporto il contenuto : 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:rispostaKO xmlns:ns2="http://sogei.it/ANPR/3000consultazione">
    <testataRisposta>
        <idOperazioneComune>0</idOperazioneComune>
        <codMittente>11191</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>4001</operazioneRichiesta>
        <dataOraRichiesta></dataOraRichiesta>
        <idOperazioneANPR>277028303</idOperazioneANPR>
        <esitoOperazione>XXXX</esitoOperazione>
    </testataRisposta>
    <listaErrori>
        <errore>
            <codiceErroreAnomalia>EN115</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>La richiesta  ha individuato un numero di occorrenze troppo elevato: restringere i parametri della ricerca</testoErroreAnomalia>
        </errore>
    </listaErrori>
</ns2:rispostaKO>
```

**Comment by mttfranci** [comment]
@fcastellani81 è sempre il caso di fornire l'identificativo come fatto da @iolandacavallin altrimenti non è possibile effettuare ulteriori verifiche.

**Comment by fcastellani81** [comment]
@mttfranci ha ragione, me ne scuso:  id 263171460, file 028080_Elenchi_Mon Jun 08 16_47_24 CEST 2020.gz
Confermo che il file è eseguibile con un normale editor di testo. Se si prova a rinominare l'estensione da .gz a .xml e aprire il file con un edito xml (io uso xml notepad) l'errore è il seguente: "error loading  028080_Elenchi_Mon Jun 08 16_47_24 CEST 2020.xml Elementi radice multipli. Riga 156 posizione 2".

**Comment by mttfranci** [comment]
@fcastellani81 allora è normale, l'output del servizio non è un unico XML , ma bensì accorda l'equivalente delle risposte del servizio di consultazione (3002) per i soggetti richiesti. Andrebbero prima divisi nei soggetti inclusi tra i tag 
Risposta3002_OK (i singoli soggetti dovrebbero essere 3002 validi)
