### ISSUE TITLE
CONTRIBUTO NON ANCORA RICEVUTO

### ISSUE THREAD

**Issue by Valmorea** [italia/anpr#2139]
Comune di Valmorea (CO), subentrato giugno 2019, la richiesta di contributo risulta evasa ma a tutt'oggi l'ufficio ragioneria non ha ricevuto il contributo

**Comment by rvinzani** [comment]
Per conoscere lo stato di avanzamento del pagamento deve scrivere alla casella contributi_comuni_anpr@funzionepubblica.it

**Comment by vix-db** [comment]
Comune di Lioni (AV) e Cervinara (AV)
subentrati rispettivamente il 11/10/2019 e il 25/10/2019.
Sono mesi che ci vediamo rispondere da contributi_comune_anpr@funzionepubblica.it sempre la stessa cosa.
E' alquanto frustrante e ridicolo, ma dopo un anno ancora non si vede l'ombra di 1 euro... e non diamo la colpa al COVID (che è iniziato a febbraio 2020)...

![Screenshot from 2020-12-11 14-02-01](https://user-images.githubusercontent.com/47904600/101906745-bfee8300-3bb9-11eb-9eff-9a6f61a2659d.png)
