### ISSUE TITLE
Gestione della doppia cittadinanza

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#214]
Buongiorno,
abbiamo verificato che nel file di subentro NON è gestita la doppia cittadinanza; per cui le persone vengono trasferite con un solo dato, mentre ANPR contiene invece più campi.

Quindi, i dati della doppia cittadinanza dovrebbero essere inseriti manualmente DOPO il subentro; stiamo approfondendo la possibilità di utilizzare una funzione automatica, ma sarebbe comunque necessario che il dato fosse già compreso nel file di presubentro e subentro, in modo da evitare discordanze o caricamenti di dati successivi.

Grazie
Patrizia Saggini
Comune di Anzola dell'Emilia (BO)

**Comment by gcarbonin** [comment]
E' gestita . L'indicazione della modifica si trova a questo link https://www.anpr.interno.it/portale/documents/20182/26001/aggiornamenti_22_05_2017.xlsx/a5a53994-5c1f-4fae-b934-8236fd92369d; in ambiente di test comuni e pre-subentro mettiamo sempre un avviso sulla modifica delle specifiche. Possiamo sentirci per il recupero. Per ora non sviluppate nulla.
