### ISSUE TITLE
ANNULLAMENTO CANCELLAZIONE PER DOPPIA ISCRIZIONE EFFETTUATA ERRONEAMENTE

### ISSUE THREAD

**Issue by beatricelulli** [italia/anpr#2140]
Buongiorno,
con la presente segnalo il seguente problema:
A seguito di segnalazione ANPR il Comune di Frosinone ha erroneamente cancellato per doppia iscrizione il cittadino con id 19981794 -->( IdAnpr del cancellato erroneamente per altri motivi).
Il cittadino da cancellare per doppia iscrizione era in realtà di competenza del Comune di Martina Franca con id. 33492727.

E' possibile annullare la cancellazione effettuata in modo da riportare in popolazione il cittadino nostro residente e richiedere al Comune di Martina Franca la cancellazione per doppia iscrizione?
Salvo errore, il sistema non ci consene questa operazione e non sappiamo come poter riportare in popolazione il cittadino anche considerando che la decorrenza dell'iscrizione sarebbe gennaio del 2009.
Grazie

DOTT.SSA BEATRICE LULLI
COMUNE DI FROSINONE
FUNZIONARIO SERVIZI DEMOGRAFICI

**Comment by frmariani** [comment]
dovete annullare la cancellazione effettuata, avete già provato ? nel caso mi può indicare l'idanpr dell'operazione ?

**Comment by beatricelulli** [comment]
1 Errore Anpr Cod: 999 - Operazione non effettuabile - -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-01 17:55:02 , mittente 060038 , idOperazioneComune 6469538 - -

**Comment by frmariani** [comment]
potete riprovare per favore ?

**Comment by beatricelulli** [comment]
1 Errore Anpr Cod: 999 - Operazione non effettuabile - -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-02 10:09:01 , mittente 060038 , idOperazioneComune 6475433 - -

**Comment by frmariani** [comment]
grazie, stiamo verificando

**Comment by beatricelulli** [comment]
Ancora nessun aggiornamento?

**Comment by frmariani** [comment]
Mi scuso per il ritardo della risposta ma c'è un bug che stiamo cercando di risolvere;
al massimo entro domani avrò notizie più certe.

**Comment by frmariani** [comment]
alcune date incongruenti hanno impedito l'annullamento dell'operazione di cancellazione.
come da accordi per le vie brevi con entrambi i comuni, il cittadino verrà cancellato dal comune di Martina Franca e re-iscritto dal comune di Frosinone.
Chiudo la issue ma rimango a disposizione per qualsiasi tipo di supporto.
