### ISSUE TITLE
[6001] Tipi certificato per soggetto

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2142]
Buongiorno, esiste un modo (o un servizio) che dato un soggetto (cf o idAnpr) fornisce tutti i tipi di certificato che è possibile richiedere per quel soggetto, escludendo tutti gli altri di Tabella 13?  
Grazie

**Comment by mttfranci** [comment]
Salve, al momento non esiste un servizio di questo tipo.
Ma valuteremo se sia il caso di introdurlo.
Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Buongiorno, grazie per la risposta. Resto in attesa di riscontro. Saluti

**Comment by Eduardo1977** [comment]
Tra l'altro si eviterebbero tante inutili chiamate al servizio 6001 per richieste di certificati che (giustamente) non possono essere emessi.
