### ISSUE TITLE
[web-service] msg. "Security processing failed" - URGENTE

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2143]
ambiente di PRODUZIONE - comune di CASTELNUOVO DI GARFAGNANA (046009)

il comune è appena subentrato in produzione.
con lo switch di passaggio da pre-sub a prod, non funzionano i web-service.
le impostazioni lato-client sembrano corrette.
potete verificare se tracciate qualcosa lato server?

es. idOperazioneComune 2020300011 (ws 3002)

grazie
Alessandro Monopoli ADS

**Comment by gife67** [comment]
Buonasera,
non ci risultano pervenute richieste sull'endpoint dei servizi di Produzione per il Comune 046009.
Vi consiglio di verificare se gli IP richiesti da abilitare per l'accesso al sistema di Produzione siano corretti e che l'endpoint che state puntando sia https://ws.anpr.interno.it

**Comment by AMonopoliADS** [comment]
ok. 
l'endpoint è corretto. verifichiamo gli ip abilitati.

grazie

**Comment by AMonopoliADS** [comment]
abbiamo trovato un errore nella definizione del certificato di postazione, ed era quello che faceva scattare l'errore lato client.
adesso le chiamate vanno in timeout, come se l'endpoint fosse irraggiungibile.
attendiamo riscontri dall'ente per assicurarci che non ci siano restrizioni in uscita.
non so se volete comunque fare qualche verifica anche voi, x vedere, anche con le prove più recenti se è arrivato qualcosa lato-server.

grazie

**Comment by gife67** [comment]
Buonasera,
abbiamo provveduto ad abilitare il vostro IP sui nostri firewall, dal momento che risultava disabilitato nonostante la vostra richiesta.
Se cortesemente potete riprovare ora.
Grazie

**Comment by AMonopoliADS** [comment]
il web-service adesso è funzionante.
grazie per l'intervento

**Comment by gife67** [comment]
Ottimo. 
Buona serata
