### ISSUE TITLE
Upload foto su sito prenotazioni-cie

### ISSUE THREAD

**Issue by dkwo** [italia/anpr#2144]
E’ possibile fare l’upload della foto su https://www.prenotazionicie.interno.gov.it/cittadino invece di portarla a scannerizzare in comune? se si', in che formati e con che vincoli? se no, perche' no?

E’ possibile per un consolato/ambasciata usare tale sito per gestire prenotazioni?

**Comment by FilippoPapi** [comment]
buongiorno
mi dispiace ma questo canale è riservato a problematiche relativa ad ANPR.
saluti

**Comment by dkwo** [comment]
Ok, dove posso riportare la mia problematica?
