### ISSUE TITLE
Problemi di collegamento ai Servizi ANPR

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2145]
Buongiorno,

abbiamo bisogno di sapere se ci sono problemi in produzione. Dalle 8 di questa mattina i servizi ANPR vanno in timeout.

Grazie, cordialmente
Chiara Leanza
per il Comune di Torino

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di Produzione

Buongiorno,
stiamo registrando lo stesso problema sia sulla produzione che tentando di accedere all' ambiente di test. Anche il rilascio CIE è bloccato, per cortesia potete verificare?

Grazie, saluti
Sonia Fiorini

**Comment by SAlberto** [comment]
Stesso problema, riscontrato questa mattina nei comuni Borgo San Dalmazzo, Mondovì e Collegno

**Comment by Maga63** [comment]
Stesso problema anche a Milano.

**Comment by iessicatoro** [comment]
Confermo problemi anche a Piacenza 

********************************************************************************* 
Iessica Toro 
Comune di Piacenza 
Sistemi Informativi 
Via Beverora 57 - 29121 Piacenza 
Tel. 0523.492544 
********************************************************************************** 


Da: "SAlberto" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Inviato: Lunedì, 6 luglio 2020 9:22:13 
Oggetto: Re: [italia/anpr] Problemi di collegamento ai Servizi ANPR (#2145) 





Stesso problema, riscontrato questa mattina nei comuni Borgo San Dalmazzo, Mondovì e Collegno

**Comment by edoardodona-1** [comment]
Stesso problema Ravenna ! Potete fornire una stima di quando aggiusterete ? GRAZIE

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno a tutti,

a noi (comune di Torino) il problema di timeout sembrerebbe rientrato. Qualcuno potrebbe darmi riscontro?

Grazie, cordialmente
Chiara Leanza

**Comment by sfmodena** [comment]
Buongiorno,
anche a Modena il funzionamento di webapp e ws sembra ripristinato.

Saluti
Sonia Fiorini

**Comment by CSI-Piemonte-Demografia** [comment]
Grazie mille per il riscontro. 
Lascio aperto il thread in attesa di una risposta da parte di SOGEI.

**Comment by edoardodona-1** [comment]
ok anche ravenna . Grazie !

**Comment by Maga63** [comment]
Milano ok. Grazie.

**Comment by FilippoPapi** [comment]
Buongiorno
Il problema è risolto. Stiamo ancora indagando sulle cause ma da una prima analisi non sembra un problema imputabile ad ANPR. Probabilmente è stato un problema sulla rete geografica di qualche provider, che sembrerebbe aver risolto.
