### ISSUE TITLE
Problemi di connessione ai WS ANPR - errore 12002

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2147]
Buon giorno
il comune di Teramo ci segnala di avere di nuovo problemi con la connessione ai servizi ANPR, ottenendo l'errore in oggetto ad ogni tentativo di invocazione. Il comune ha avuto lo stesso problema nella mattinata di ieri, più o meno fino alle 11 (come segnalato da altri comuni nella issue #2145), poi la situazione sembrava essersi risolta, al momento invece non riescono ad operare in ambiente di esercizio e sono di fatto bloccati.
In attesa di riscontro,
cordiali saluti

Giuseppe Mucciarelli, TINN srl

**Comment by gife67** [comment]
Buonasera,
i problemi di ieri erano relativi ad un provider di rete geografica, gestore dell'infrastruttura di rete di molti Comuni.
Per quanto riguarda i problemi odierni, che state riscontrando non evidenziamo nessun malfunzionamento al nostro interno e non ci risultano altri Comuni che hanno problemi, come si è verificato ieri. Vi chiedo cortesemente di verificare l'infrastruttura di rete specifica del Comune di Teramo. Ho verificato che comunque nelle ultime ore c'è operatività sui servizi da parte delle postazioni PC-0005, PC-0007, PC-0001. Se ci fornite maggiori dettagli sull'errore che state riscontrando, possiamo fornirvi maggiori indicazioni.
Cordiali saluti
Giuseppe Ferraro

**Comment by Amucciarelli74** [comment]
Buonasera,
abbiamo ricontattato il comune e i problemi effettivamente sembrano non presentarsi più dalla fine della mattinata, non abbiamo purtroppo altre informazioni rispetto a quanto segnalato nella issue oltre all'errore che ci ha comunicato il cliente con il relativo codice 12002, se non che probabilmente si è verificato nell'invocazione del WS di scarico notifiche 4005.
Se si dovesse ripresentare la problematica, vedremo di effettuare una verifica più puntuale in modo da fornirvi informazioni più dettagliate, per il momento vi ringraziamo per il cortese riscontro.
Cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by gife67** [comment]
Ottimo,
ho verificato gli accessi sull'endpoint dei servizi e per il Comune non c'è state nessuna richiesta oggi se non a partire dalle 12:17.
Le confermo che c'è stata operatività normale per tutto il giorno per tutti i Comuni, quindi sicuramente è stato un problema di connettività del Comune specifico.
Cordiali saluti e Buona serata.
Giuseppe Ferraro
