### ISSUE TITLE
Doppio Id ANPR stessa persona

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2148]
Buongiorno,
ho la necessità di registrare la mutazione anagrafica di questa persona iscritta nell'Anagrafe Nazionale della Popolazione Residente con due ID ANPR ed attualmente residente ad Opera (MI):

1) **19153267** |   | XXXXXXXX |   | CASTELLEONE 			(CR) | CANCELLATOTrasferimento 			di residenza in comune non subentrato ;

2) **83384343** |   | XXXXXXXX |   | OPERA 			(MI)

La persona identificata con il primo Id ANPR (19153267) è emigrata ad Opera in data precedente al subentro di quest'ultimo avvenuto il 18.12.2019, inoltre si fa presente che la provincia corretta della persona dovrebbe essere CZ e non VV come indicato nel codice di Anpr ( 83384343).

Come procedo alla registrazione della mutazione anagrafica?

Grazie infinite

**Comment by rvinzani** [comment]
Può procedere effettuando la mutazione di residenza del soggetto residente ad Opera. Una volta effettuata la mutazione di residenza, è possibile correggere la provincia di nascita se errata

**Comment by ACastelleone** [comment]
Buongiorno,
e per unire i due ID di Anpr?
Grazie

**Comment by rvinzani** [comment]
Non devono essere uniti i due ID
