### ISSUE TITLE
Errore materiale su mio indirizzo di residenza

### ISSUE THREAD

**Issue by giovannibonvento921** [italia/anpr#2149]
Salve,
Volevo segnalare un errore materiale al mio indirizzo di residenza che il comune di Scicli (RG) ha commesso e che apparentemente non riescono a risolvere. Attualmente il mio indirizzo di residenza è il seguente:

ALTRO S.P. 40 SCICLI-SAMPIERI N. XXXXX

Bisognerebbe eliminare la scritta Altro all'inizio, visto che mi crea problemi su tutti i fronti. Sono infatti residente semplicemente sulla strada provinciale 40 (SP40 SCICLI-SAMPIERI) al numero civico correttamente indicato in anagrafe e che qui ho censurato per privacy. Il mio nome e cognome sono quelli del mio nome utente. C'è modo di contattare il comune di Scicli e far correggere l'errore? Ho già inviato numerose pec ma mi dicono di non riuscire a eliminare la scritta "altro" all'inizio. 
Giovanni

**Comment by frmariani** [comment]
questa mattina ho contattato il Comune ed è stato rettificato l'indirizzo

**Comment by giovannibonvento921** [comment]
Salve,
Ho ricontrollato la visura e finalmente "altro" è stato sostituito con "strada" ma stavolta viene fuori un "KM 53" che è totalmente errato (la strada provinciale non è lunga 53 km). Andrebbe eliminata quella voce.

**Comment by frmariani** [comment]
io ho indicato semplicemente la modalità di rettifica dell'indirizzo, naturalmente lascio all'Ufficiale d'Anagrafe l'inserimento del dato corretto.
per favore mi scriva l'indirizzo corretto alla seguente mail
frmariani@sogei.it

**Comment by frmariani** [comment]
la rettifica è stata effettuata, per favore controlli la correttezza dell'indirizzo

**Comment by giovannibonvento921** [comment]
Perfetto, finalmente è tutto ok. Grazie mille e buon lavoro.
Saluti,
Giovanni Bonvento
