### ISSUE TITLE
Servizio ricezione notifiche off-line

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2150]
Salve, buongiorno
su alcuni nostri comuni per diversi giorni non è stato raggiungibile il servizio di ricezione notifiche. Appena riavviato il servizio abbiamo continuato a ricevere le notifiche giorno per giorno senza però mai ricevere le notifiche precedenti. Cosa bisogna fare per ricevere le notifiche in coda mai ricevute? Ad es. le notifiche del comune di Potenza (cod. istat 076063)

**Comment by gife67** [comment]
Buongiorno,
se ci fornite l'elenco dei Comuni che hanno avuto un problema con l'endpoint, provvediamo a rinviarvi tutte le notifiche che hanno avuto un problema nella fase di invio. 
Grazie mille

**Comment by gife67** [comment]
Intanto abbiamo sbloccato ed inviato tutte le notifiche di Potenza.
Attendiamo la lista dei Comuni.
Grazie

**Comment by carminepat** [comment]
Grazie, per Potenza la situazione è ok. Gli altri comuni sono:
- DURAZZANO (cod istat: 062028)
- BONEA (cod istat: 062009)
- MATERA (cod istat: 077014)
- SATRIANO (cod istat: 076083)
- VIGGIANELLO (cod istat: 076097)

**Comment by gife67** [comment]
Buongiorno,
abbiamo provveduto a rinviare le notifiche per tutti i Comuni.
I comuni Durazzano, Satriano e Viggianello sono OK, mentre per i Comuni di Bonea e Matera i loro endpoint non sono disponibili, quindi anche il nuovo rinvio è andato KO. Vi prego di verificare.
Grazie mille

**Comment by gife67** [comment]
Buongiorno,
non avendo avuto più un riscontro chiudo la issue, nel caso potete aprirne una nuova per il supporto.
Cordiali saluti
