### ISSUE TITLE
RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2151]
Cittadino con due posizioni all'agenzia delle entrate, una esatta con c.f. MGSYGL87T31Z329C l'altra errata anche in ANPR con c.f. MGSYGL96B10Z329O. Dovendo procedere alla risoluzione del disallineamento cliccando su CONFERMA AE, mi da il seguente messaggio: 
I campi da variare sono: la data di nascita da 10/02/1996 a 31/12/1987 e il c.f. da MGSYGL96B10Z329O a MGSYGL87T31Z329C.
Esito ANPR: Variazione non consentita per superamento numero campi variati (Codice: EAM93)
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-08 08:48:03 , idOperazioneANPR 284737413 (Codice: EN527)
Grazie 
Filippo asaro
tel. 0923 993 382

**Comment by frmariani** [comment]
l'utente è stato contattato ed il problema risolto
