### ISSUE TITLE
Errore invocazione servizio 4005

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2153]
Durante l'invocazione del servizio per la lettura delle notifiche, il 4005 ricevo una risposta KO (codiceErroreAnomalia="XXXX", tipoErroreAnomalia="E", testoErroreAnomalia="Utente non abilitato 5"). Stiamo effettuando le richieste in ambiente di PRE-SUBENTRO a Potenza (codIstat: 076063). Potreste darmi ulteriori dettagli su questo errore??

**Comment by mttfranci** [comment]
Salve, l'utenza che avete usato dispone delle abilitazioni necessarie?
Potreste confermarci :
* orario dell'operazione
* idoperazionecomune
* codice postazione usato
* non indicate il cf dell'utente perchè su github non possiamo rirportare dati sensibili.
Va bene anche se eseguite una nuova operazione oggi.

**Comment by carminepat** [comment]
Salve, abbiamo ri-effettuato il test oggi pomeriggio con lo stesso esito segnalato in precedenza. Le allego di seguito le indicazioni che mi ha richiesto:
idOperazioneComune: 142191
codIstatMittente: 076063
operazioneRichiesta: 4005
dataOraRichiesta: 2020-07-13T12:00:14.287
tipoInvio: PRE_SUB
postazione: 9999

**Comment by mttfranci** [comment]
Salve, l'utente reale che avete usato per il collegamento non è abilitato per la funzione delle notifiche.
Non possiamo indicare quale sia l'utenza per motivi di privacy.
Ma dovreste usarne una abilitata oppure far abilitare questa dall' ALS.
Saluti
