### ISSUE TITLE
Esito AE: Soggetto non rettificabile perche' in lavorazione per risoluzione omocodia (Codice 96)

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2154]
Buongiorno,

richiediamo assistenza per collegare doppia posizione, una in AE una in ANPR, della cittadina Id scheda attribuito da ANPR 91469858.

La cittadina risulta avere in AE il CF MLTBMK64H47Z157U ed in ANPR  MLTBMK64H47Z158W

Potete provvedere mantenendo come corretti i dati attualmente in ANPR compreso il CF e collegando il CF MLTBMK64H47Z157U  presente in AE?

Grazie

**Comment by frmariani** [comment]
noi possiamo soltanto aiutare nella risoluzione delle problematiche, ma non possiamo in alcun modo operare sui dati dei cittadini;
per il collegamento che richiede, deve scrivere alla Direzione Centrale di Agenzia delle Entrate
entrate.archivioanagrafico@agenziaentrate.it
inviando eventuale documentazione del caso in suo possesso. 
Per rispettare la privacy dei cittadini, sarebbe preferibile utilizzare l'identificativo anpr al posto del CF.
Grazie.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
