### ISSUE TITLE
Domicilio digitale

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2155]
La sig.ra cod. 18938110 chiede aggiornare il proprio domicilio digitale con il suo indirizzo p.e.c.
Si può fare attualmente questa operazione sul portale ministeriale ANPR? Se sì, come si fa?

I miei riferimenti sono:
dott. Andrea Paltrinieri
Ufficiale d'Anagrafe del Comune Biassono (108009)
tel. 039-2201060
e-mail paltrinieri.andrea@biassono.org

In attesa di un Vs. riscontro, porgo distinti saluti.

Andrea Paltrinieri

**Comment by rvinzani** [comment]
ANPR non ha ancora la possibilità di acquisire il domicilio digitale di un cittadino
