### ISSUE TITLE
[3002] ws - riconoscere comune iscrizione AIRE

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#216]
Per i cittadini AIRE da popolamento iniziale è presente il blocco DatiIscrizione dove è presente il comune italiano in cui è iscritta la persona.
Facendo un'iscrizione di un AIRE per altri motivi e poi andandola a interrogare, questi dati non risultano presenti.
Come si può individuare il comune di iscrizione AIRE interrogando un soggetto in ANPR iscritto successivamente al subentro?

**Comment by gcarbonin** [comment]
In generale per la consultazione da WEB il comune di iscrizione è riportato nella sezione dati Iscrizione, sia nel caso di soggetto iscritto da subentro che da WS A002.
Ci dovrebbe indicare un identificativo della persona in modo che possiamo controllare

**Comment by siscomanpr** [comment]
Provando a interrogare le stesse persone di ieri sembra che adesso il nodo dei dati Iscrizione venga restituito correttamente. 
Grazie.

**Comment by siscomanpr** [comment]
Sempre in merito a questa tematica, in ambiente di test abbiamo effettuato una mutazione di residenza (non AIRE) tra 2 comuni subentrati di alcuni componenti di una famiglia per poi fare un'annullamento di mutazione parziale. Consultando una di queste persone (in particolare quella con codice ANPR 1252884 di cui però non ho annullato l'iscrizione) nella sezione Dati Iscrizione non risulta il comune di appartenenza. Non risulta neanche che è stato iscritto da comune subentrato come invece vedo su altre persone. E' vero che è possibile capirlo dalla sezione della residenza, ma se fosse un AIRE, li ci sarebbero i dati di residenza estera. 
Allego lo screenshot dei datiIscrizione.
![datiiscrizione](https://user-images.githubusercontent.com/28776141/27393986-04163084-56ab-11e7-8c3a-ef743d6eb3c4.JPG)

**Comment by gcarbonin** [comment]
Può riprovare con un caso simile e darmi conferma?

**Comment by siscomanpr** [comment]
Riprovando un caso simile il problema non si è ripresentato.
Intanto il soggetto di cui scrivevo ieri con codice ANPR 1252884 adesso è completo dei dati di iscrizione senza senza aver apportato variazioni sulla persona.

![datiiscrizione2](https://user-images.githubusercontent.com/28776141/27434777-250c0f84-575a-11e7-81e8-72f9a0fd7a00.JPG)
