### ISSUE TITLE
L'OPERAZIONE DA ANNULLARE NON E' L'ULTIMA SUL SOGGETTO O SULLA FAMIGLIA

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2161]
Buongiorno,
dovremmo revocare una pratica di iscrizione relativa al soggetto con id anpr 35598010, purtroppo il gestionale non permette annullare l'operazione MUTAZIONE RESIDENZA 203115566 riportando codice di errore "EN-077 L'operazione non è l'ultima da annullare per il soggetto o la famiglia...", in elenco operazioni però non ci sono altre mutazioni da annullare, pensiamo dunque possa essere stata effettuata qualche modifica nella famiglia di provenienza dell'altro comune ma, non visualizzando le operazioni, non ne abbiamo la certezza. Potreste indicarci quale operazione blocca il gestionale?
Riporto il codice 284067012 da segnalare all'assistenza.

Segnalo inoltre che si è presentata una situazione analoga per id anpr 83391817; in questo caso però è stata contattata l'assistenza, la quale ha operato in anpr annullando tutte le mutazioni ma, purtroppo, questo ha creato divresi problemi per cui non si riesce comunque a revocare la pratica ssu gestionale. Dal momento che i sistemi sono collegati e colloquiano tra loro, per evitare queste sitazioni di "stallo", sarebbe possibile operare insieme, contemporaneamente? Per esempio, l'operatore anpr potrebbe eliminare solo l'operazione che blocca il gestionale e, il comune, potrebbe revocare la pratica da gestionale (annullando dunque l'operazione su anpr).

Cordiali Saluti
UpiTorino
Floramo S.

**Comment by frmariani** [comment]
Buongiorno Silvia, l'operazione che impedisce l'annullamento del cambio di residenza, è un'operazione effettuata dal vostro comune sulla famiglia precedente del cittadino dopo la sua uscita, pertanto non è visibile nell'elenco delle sue operazioni.
In questi casi è preferibile effettuare un'indagine anche nella famiglia in cui il cittadino deve tornare: idoperazione da annullare 255683172.
Per quanto riguarda la situazione analoga, forse i nostri operatori vi hanno aiutato ad intercettare le operazioni da annullare, senza operare direttamente perchè noi non possiamo effettuare operazioni per vostro conto.  
Attendo riscontro sull'annullamento dell'operazione di Mutazione della residenza.

**Comment by frmariani** [comment]
Buongiorno Silvia, l'operazione che impedisce l'annullamento del cambio di residenza, è un'operazione effettuata dal vostro comune sulla famiglia precedente del cittadino dopo la sua uscita, pertanto non è visibile nell'elenco delle sue operazioni.
In questi casi è preferibile effettuare un'indagine anche nella famiglia in cui il cittadino deve tornare : idoperazione da annullare 255683172.
Per quanto riguarda la situazione analoga, forse i nostri operatori vi hanno aiutato ad intercettare le operazioni da annullare, senza operare direttamente perchè noi non possiamo effettuare operazioni per vostro conto.
Attendo riscontro sull'annullamento dell'operazione di Mutazione della residenza.

**Comment by UpiTorino** [comment]
Buongiorno Francesca,
per il soggetto in questione, abbiamo effettuato un'iscrizione, non un cambio di indirizzo, per cui la famiglia di provenienza, ed in cui dovrebbe tornare a seguito di revoca, è di appartenenza del Comune di Beinasco. 
Per quanto riguarda la situazione analoga, purtroppo non era un mio caso dunque non so nello specifico come abbiano operato.
Grazie
Buona giornata
Floramo S.

**Comment by frmariani** [comment]
Facciamo chiarezza, ma eventualmente ci sentiamo per telefono:
il cittadino subentra nel comune di Beinasco con altri due componenti della famiglia;
il cittadino si sposta da solo nel vostro comune;
gli altri due componenti della famiglia si spostano a loro volta nel vostro comune con l'operazione 255683153;
se l'intento è quello di riportare il cittadino nel comune di Beinasco, dovete effettuare una cancellazione per altri motivi, perchè la famiglia dove dovrebbe tornare si è spostata, altrimenti dovete annullare anche il trasferimento degli altri componenti

**Comment by frmariani** [comment]
il problema è stato chiarito anche per le vie brevi.
La issue viene chiusa
