### ISSUE TITLE
[5012] L'operazione da annullare non è l'ultima

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2163]
Ambiente di produzione, comune di Bagno a Ripoli.

Tentando di annullare la mutazione 181262673 con il servizio in oggetto otteniamo l'errore "EN077 L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa.". ID anpr operazione annullamento è 292826534.

Non riusciamo a capire quale sia la mutazione bloccante.Potete aiutaci ?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
sono bloccanti ai fini dell'annullamento della mutazione di residenza indicata le operazioni eseguite sulla cittadina id 86276871 iscritta nella medesima famiglia dopo la mutazione e poi cancellata. Dovreste provare ad annullare queste operazioni oppure fornire un riferimento del Comune che proviamo a contattarli noi.

N. Capozzi
