### ISSUE TITLE
Ambiente di test non raggiungibile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2165]
Buongiorno

stamattina non risultano raggiungibili né l'ambiente di test WS (wstest.anpr.interno.it) né la webapp di test (dptest.anpr.interno.it).
Potete controllare ? 

Grazie

**Comment by busaster** [comment]
Il problema permane tutt'ora, ci crea difficoltà con le operazioni di collaudo e sviluppo. 
CI sono novità ?
Grazie.

**Comment by MarcoSalaPad** [comment]
Buongiorno,
confermo che anche noi stiamo riscontrando gli stessi problemi di collegamento agli ambienti di test.
Si potrebbe avere un aggiornamento in merito?

Grazie
Pa Digitale Spa

**Comment by mttfranci** [comment]
Ci scusiamo,
Abbiamo un problema tecnico, stiamo lavorando per ripristinare il sistema il prima possibile.
Vi avvisiamo appena abbiamo novità.
Saluti

**Comment by mttfranci** [comment]
Salve. il disservizio dovrebbe essere rientrato. potete confermarcelo?
saluti

Assistenza ANPR

**Comment by MarcoSalaPad** [comment]
Buongiorno, confermo che ho fatto un test poco fa e gli ambienti hanno ripreso a funzionare.
Grazie
Marco

**Comment by busaster** [comment]
Confermo anch'io che stamattina il problema è risolto.
Grazie
