### ISSUE TITLE
EAM93 - Variazione non consentita per superamento numero campi variati

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2166]
Buongiorno

provando a rettificare i dati anagrafici di un cittadino si riceve il seguente errore:

EAM93 | Variazione non consentita per superamento numero campi variati

EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-22 12:28:20 , idOperazioneANPR 294411272

Provando a restringere il numero di campi da modificare l'errore cambiia

EAM95 | Variazione non consentita, soggetto registrato in AT ANPR di altro comune

EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-20 12:56:04 , idOperazioneANPR 292661884

Cordiali saluti

Della Strada Dante
Comune di Cesena

**Comment by frmariani** [comment]
Il Comune non può modificare in autonomia, più di 3 dati anagrafici di un cittadino; nel caso fosse necessario,  il Comune dovrà inviare una mail alla Direzione Centrale di Agenzia delle Entrate allegando tutta la documentazione a supporto della modifica.
Di seguito la corretta procedura da seguire:
dopo aver appurato su Punto Fisco che le nuove generalità del cittadino non siano presenti, dovrà aprire un ticket al nostro numero verde 800863116 e successivamente scrivere al seguente indirizzo 
entrate.archivioanagrafico@agenziaentrate.it 
indicando nell'oggetto il numero del ticket aperto ed allegando la dovuta documentazione.

Nel caso invece in cui le indagini su Punto Fisco portassero alla presenza di un Codice Fiscale già emesso da Agenzia delle Entrate, dopo aver verificato che si tratti dello stesso cittadino, potrà effettuare il collegamento dei due codici fiscali con la funzione Risoluzione Disallineamenti con AE presente nella web app di ANPR.
Nel caso avesse necessità di ulteriore supporto può chiamare il numero verde o scrivermi al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
