### ISSUE TITLE
non è possibile registrare la smart card

### ISSUE THREAD

**Issue by buggerru** [italia/anpr#2167]
Buongiorno, la Prefettura mi ha consegnato la smart card per l'accesso in ANPR. Da pannello quando vado a registrare la smart card, mi esce l'errore "**Errore CAST Attivazione Smart Card**"

Lo stato della smart card è "Consegnata dalla prefettura".

Grazie

**Comment by buggerru** [comment]
In aggiunta, quando vado in GESTIONE UTENTE e carico la mia utenza, esce "Errore Generico del server"

**Comment by Leonforte** [comment]
Buongiorno, il problema è stato risolto, potete quindi procedere alla attivazione della smart card
