### ISSUE TITLE
CONVENZIONE CON FIT TABACCAI PER RILASCIO CERTIFICATI ANPR

### ISSUE THREAD

**Issue by campagna2** [italia/anpr#2168]
Buongiorno,
il Comune di Imperia ha stipulato una convenzione con la FIT Federazione Italiana Tabaccai / Novares SpA per consentire il rilascio dei certificati anagrafici Anpr da parte dei tabaccai sul territorio comunale; a tal fine, ci sono state richieste le seguenti informazioni:

 

• Codice fiscale dell’operatore comunale, già autorizzato presso la console di sicurezza ANPR, che figurerà nelle richieste ad ANPR

• Certificato di postazione, rilasciato da ANPR tramite la console di sicurezza, e relativa password di cifratura.

• Codice della postazione (solitamente coincide con l’alias del certificato, eg 003106- PC-0022)

• Codice istat del comune (solitamente incluso nell’alias del certificato, eg 003106)

• Codice fiscale dell’operatore autorizzato dal comune alle operazioni che si prevede di utilizzare

Vorrei sapere come procedere, sia a livello di sicurezza, sia a livello tecnico, soprattutto in riferimento al primo e all'ultimo punto.

Grazie.
Annamaria Campagna
Comune di Imperia

**Comment by FilippoPapi** [comment]
buongiorno
potete far riferimento alla nota del Ministero dell'Interno del 21 maggio 2020 "Nota utilizzo Servizi ANPR" pubblicata sul sito di ANPR.
cordiali Saluti
