### ISSUE TITLE
[Webapp] Risoluzione disallineamenti che coinvolge cf omocodice e validato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2169]
Buongiorno
In ambiente di produzione abbiamo avuto un caso anaologo alla issue #1753 , per coinvolgimento di un cf omocodice.
L'id del cittadino anpr è 76010297. In ANPR è presente con cf validato (e omocodice). cf numero 1.
Acquisisce ora la cittadinanza italiana, e in ragione di questo, occorre modificare le generalità.
Però le nuove generalità sono già presenti in AE, come cf indipendente, non collegato all'altro. cf numero 2.

Leggendo la issue precedente, il Comune ha scritto a AE, illustrando il caso.
AE ha risposto che ha collegato cf 2 al cf 1, in quanto presenta già le nuove generalità corrette.

A questo punto il Comune verifica con la consultazione AE che i due cf sono effettivamente collegati.
Prova da webapp, risoluzione disallineamenti, cercando per i due cf presenti i ANPR e AE a effettuare l'operazione in questo modo: 
- non spunta collegare codici fiscali (sono già collegati)
- preme il pulsante CONFERMA AE, in quanto i dati corretti sono quelli presenti in AE.

Riceve l'errore:

Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-23 12:38:54 , idOperazioneANPR 295215015 (Codice: EN527)

Come si può procedere?

**Comment by frmariani** [comment]
se ho capito bene la problematica, il CF corretto è il collegato, quindi il CF2;
in questo caso deve effettuare quella che in gergo chiamiamo "inversione di link", cioè il collegato deve diventare il principale.
La modifica può essere effettuata tramite l'operazione di mutazione tutti i dati presente nei servizi di registrazione.
Ricerca il cittadino con il cf presente in ANPR (CF1) e poi nelle generalità inserisce il CF2 con le generalità corrispondenti;
il tasto Conferma e Salva e chiudi terminerà l'operazione.

**Comment by MarcoMigliori** [comment]
Abbiamo provato, ricevendo mi sembra lo stesso errore. Se vuole verificare i dati ecco l'esito:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-24 09:18:25 , idOperazioneANPR 295750772 (Codice: EN527)

**Comment by frmariani** [comment]
riprovi per favore

**Comment by MarcoMigliori** [comment]
Riprovato, abbiamo ottenuto esito:

Operazione correttamente eseguita
Attenzione:Richiesta incongruente - soggetto validato (Codice: EAV92)

Abbiamo fatto consultazione ANPR, e il cf è ora corretto, validato e corrispondente con cf e generalità corrette. grazie.
