### ISSUE TITLE
[5008] - mutazione 20 ulteriore blocco

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#217]
Corbetta, Ambiente di Produzione, Id Operazione ANPR 630334

Buongiorno, abbiamo ancora problemi con i WS 5008, il sig. Pelo Edmond è stato iscritto con una pratica mentre i figli avevano una provenienza diversa e sono stati iscritti con un'altra pratica nella stessa famiglia del padre. Avendo fatto delle variazioni di parentela per i figli non ci permette di fare il completamento dati (mutazione 20) per il padre.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Non c'e soltanto  il cambio di relazione di parentela dei figli, ma anche un 5001 tipo mutazione 2 (composizione scheda) con il quale è stato modificato il possesso della patente da S a N (operazione idanpr 609879) con una data di decorrenza diversa; per questo non è più possibile il completamento nella data di iscrizione
