### ISSUE TITLE
Errore AEE95 - Operazione non effettuabile (Iscrizione dall'estero)

### ISSUE THREAD

**Issue by malcesinec** [italia/anpr#2170]
Comune di Malcesine (VR) - Subentrato in ANPR 

La presente per segnalare l'errore AEE95 che riguarda una pratica da noi inserita relativa a un cittadino che ha richiesto l'iscrizione con provenienza dall'estero.
La pratica è stata inserita in data odierna (23/07/2020)  e l'errore risulta a seguito di tentativo di invio pratica.
Il cittadino è già in possesso del codice fiscale.

Uffici demografici
Comune di Malcesine (VR)

**Comment by frmariani** [comment]
i dati anagrafici inseriti nell'operazione di iscrizione, non sono congruenti con quelli presenti in Agenzia delle Entrate

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.

**Comment by malcesinec** [comment]
The original message was received at Mon, 27 Jul 2020 16:45:27 +0200

  ----- The following addresses had permanent fatal errors -----
<giuliani.alessia@comunemalcesine.it>

  ----- Transcript of session follows -----
<<< 554 5.7.1 Message cannot be accepted, spam rejection
