### ISSUE TITLE
Firma certificati ANPR ai sensi del decreto legge 16/07/2020 n. 76

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#2171]
Buongiorno,
in relazione a quanto richiesto e indicato nei ticket #2084, #1316 e #287 vi chiedo se il contenuto dell'articolo 30 del decreto legge 16 luglio 2020, n. 76, nella misura in cui modifica l'art. 35 del DPR 223/89 sostituendo la firma dell'ufficiale d'anagrafe con il sigillo elettronico qualificato ai sensi del regolamento UE, permette sin da ora di ritenere valide le certificazioni anche senza l'apposizione di firme autografe o digitali sui certificati emessi.
Si chiede anche se il Qr-Code attualmente apposto da ANPR soddisfi già il requisito del sigillo elettronico qualificato o se tale sigillo sarà apposto esclusivamente sulle certificazioni rilasciate da ANPR con modalità telematica.
Grazie.

**Comment by FilippoPapi** [comment]
buongiorno
 il Qr-Code attualmente apposto da ANPR non soddisfa già il requisito del sigillo elettronico qualificato.
Per quanto riguarda il sigillo le modalità con le quali sarà apposto sono attualmente in fase di studio.
nel momento in cui saranno prese le decisioni sarà comunicato a tutto
cordiali saluti
