### ISSUE TITLE
SoapFault: Connection timed out

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2172]
Salve, vi contatto perchè nelle invocazioni dal comune di Fisciano (cod istat: 065052) in ambiente di produzione nell'utilizzo dei web services ricevo spesso un errore di tipo: SoapFault: Connection timed out. Abbiamo controllato l'ip del server configurato nella web-app ed abbiamo apportato delle modifiche al "tool-testconn" alla classe RequestHandler del package: it.interno.anpr.security.message, aggiungendo al metodo setClient il codice seguente

```
  HTTPConduit http = (HTTPConduit) client.getConduit();
  HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
  httpClientPolicy.setConnectionTimeout(180000);
  httpClientPolicy.setReceiveTimeout(180000);
  http.setClient(httpClientPolicy);
        //
  ((BindingProvider) wsPort).getRequestContext().put("com.Sun.xml.ws.connect.timeout", 180000);
  ((BindingProvider) wsPort).getRequestContext().put("com.Sun.xml.ws.request.timeout", 180000);
```
Purtroppo il problema non è risolto e continuiamo a ricevere lo stesso errore

**Comment by gife67** [comment]
Buongiorno,
ho notato che avete un attività continua anche nelle ore notturne verso i servizi di consultazione, mutazione, effettuati sempre dallo stesso operatore NTL.......... Questa non dovrebbe essere una modalità di lavoro normale, in quanto le richieste verso i servizi dovrebbero essere contestuali al lavoro di ogni specifico operatore. Se state effettuando degli aggiornamenti massivi dovreste comunicarcelo, anche per capire con quale frequenza e concorrenza li state effettuando.
Avete verificato se il problema sul timeout lo ricevete per tutti i servizi o su delle richieste particolari?

**Comment by carminepat** [comment]
Buongiorno,
quello che noi scheduliamo nel tempo è la richiesta di nuove notifiche (che vengono effettuate più volte algiorno), la comunicazione del rilascio di nuove carte di identità cartacee e l'allineamento delle variazioni elettorali che facciamo con l'utenza del responsabile dei servizi (una volta al giorno/notte). Tutte le altre operazioni sono contestuali all'interazione dell'utenza con il software. Per quanto riguarda il "timeout" mi sento di dire che non avviene in maniera puntuale ma avviene in alcuni casi per le invocazioni 3002 (spesso), 3004, 4005

**Comment by gife67** [comment]
Cortesemente se può fornirci dei riferimenti temporali in cui avete riscontrato dei timeout e se possibile il servizio su cui l'avete riscontrato ci sarebbe d'aiuto per effettuare delle verifiche puntuali.
Grazie mille

**Comment by carminepat** [comment]
Buongiorno, abbiamo effettuato una chiamata al servizio 3002 oggi 29/07/2020 alle 10:43 (circa) terminata con un time-out

**Comment by gife67** [comment]
Buongiorno,
ho verificato che prima e dopo l'orario da lei indicato, il Comune ha effettuato alle 10:03:05 un 3002 che ha impiegato 265msec ed alle 11:25:52 un 1001 che ha impiegato 1150msec. Sul nostro endpoint dei servizi non è arrivato nulla alle 10:43. Provo a verificare se c'è traccia di qualche richiesta sui firewall perimetrali dal vostro IP, vi chiedo cortesemente di verificare anche dal lato vostro se ci sono problematiche di rete, che non permettono la raggiungibilità della nostra infrastruttura.
Grazie

**Comment by gife67** [comment]
Ho provveduto a verificare sui firewall perimetrali e questa è la situazione allineata con quanto dettagliato sopra
![dettaglio_fw](https://user-images.githubusercontent.com/26840080/88813056-be975d80-d1b8-11ea-9a88-3d0f8f63b186.jpg)
A questo punto dovreste verificare al vostro interno eventuali problemi di rete.
Grazie

**Comment by carminepat** [comment]
Analizzando l'infrastruttura di rete del comune, ci siamo resi conto che le comunicazioni escono attraverso due indirizzi ip diversi (secondo regole configurate dal gestore, che non conosciamo). Configureremo nella web app l'ip di cui siamo venuti a conoscenza non presente nella configurazione, sperando che questa iniziativa sia risolutiva. Le darò un feedback, nei prossimi giorni, nel frattempo colgo l'occasione per ringraziarla di tutte le info che ci ha fornito che ci sono state veramente d'aiuto. Grazie, buona serata

**Comment by gife67** [comment]
perfetto, sicuramente quella è la causa del problema.
Buona serata

**Comment by gife67** [comment]
Buongiorno,
non avendo avuto un riscontro provvedo a chiudere la issue, nel caso il problema non fosse risolto potete riaprirne una nuova collegata a questa.
Cordiali saluti
Giuseppe
