### ISSUE TITLE
Sigillo elettronico su certificati rilasciati in modalità telematica

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#2173]
Salve, il recente dl 16 luglio 2020 n. 76 dispone, all'art. 30, che ANPR, per i certificati richiesti in modalità telematica (immagino quando si invoca il servizio 6001 con tag emissione=2, ma è irrilevante) emette "documenti digitali muniti di sigillo elettronico qualificato". Si tratta fra l'altro di una feature gia' preannunciata su queste pagine (es.: issue 2051).

La funzione è già attiva? Sono richieste azioni da parte delle anagrafi comunali

EDIT: mi scuso, questione gia' affrontata con issue 2171

EDIT 2: visto che la modalità per apporre il sigillo e' in fase di studio, invito a valutare con attenzione gli aspetti di diplomatica del certificato come documento informatico. Per esempio: l'originale del documento quale è? E' il PDF messo a disposizione per il download (che ha tanto di numero di protocollo e QR-code per la verifica dopo l'eventuale stampa o dissociazione dalla firma/sigillo) oppure questo va considerato copia di un documento, anche in altro formato, custodito sul DB di ANPR per un certo periodo?

**Comment by FilippoPapi** [comment]
buongiorno
le sue domande fanno appunto parte degli approfondimenti in corso
Cordiali saluti
