### ISSUE TITLE
[5008] PER AGGIORNAMENTO POSIZIONE ELETTORALE    

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2174]
Buongiorno
nell'invio della comunicazione 5008 per l'aggiornamento della posizione elettorale non viene aggiornato il comune di votazione del cittadino.

 Il comune di Mesero -produzione- dopo aver inviato diverse comunicazioni nota nella WA che i dati del comune non sono aggiornati.
 Ad esempio per la comunicazione
 idOperazioneANPR 296033617
 nel comune di votazione risulta ancora il vecchio comune di residenza.

 La documentazione riguardo alla 5008 indica che in caso di omissione del tag <Comune> viene in automatico preso il comune di residenza, ma non è così.
 Vanno quindi sempre inviati i dati del comune di votazione?

grazie

**Comment by azabatta** [comment]
Buonasera, 
si conferma che per aggiornare il comune di votazione è necessario specificarne i dati nella richiesta ws 5008.
Il commento che si trova nella documentazione excel dell'oggetto "listaElettorale" è riferito alle procedure di subentro in ANPR: se il campo elettore è valorizzato ed il comune di votazione è assente, il sisteme assume come comune di votazione quello di residenza.
Provvederemo a dettagliare meglio la documentazione.
Grazie per la segnalazione
