### ISSUE TITLE
[3002] Criteri ricerca

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2175]
Buongiorno, in ambiente FREE sto provando a fare ricerche passando : codice fiscale, cognome, nome e data di nascita. La request relativa ai "Criteri ricerca" che viene inviata è questa:
&lt;criteriRicerca&gt; 
&lt;codiceFiscale&gt;xxxxxxxxxxxxxxx&lt;/codiceFiscale&gt; 
&lt;cognome&gt;xxxxxxx&lt;/cognome&gt; 
&lt;nome&gt;xxxxxxxxxx&lt;/nome&gt; 
&lt;dataNascita&gt;1986-08-23&lt;/dataNascita&gt; 
&lt;/criteriRicerca&gt;
Se provo a passare una "data di nascita" non congruente, il servizio risponde comunque inviando i dati relativi al soggetto con codice fiscale passato. Il dubbio è che il parametro di ricerca "dataNascita" venga ignorato perchè non viene passato correttamente. Potreste indicarmi dov'è l'errore oppure farmi un esempio di una request corretta? Grazie

**Comment by Eduardo1977** [comment]
Buongiorno, aggiungo quest'altro tentativo di ricerca in ambiente FREE IdOperazioneANPR=2520437.
Nei criteri di ricerca è stato messo "codiceFiscale", "tipoScheda", "identificativoANPR" sapendo che il soggetto relativo al "codiceFiscale" non sta nella famiglia relativa a "identificativoANPR". Il servizio (IdOperazioneANPR=2520437) ha restituito tutti i soggetti appartenenti alla famiglia. Il risultato che mi aspettavo era l'insieme vuoto. Dove sbaglio? Grazie

**Comment by Eduardo1977** [comment]
Sto utilizzando il documento "Specifiche_excel_13_05_2020" che non sia aggiornato?

**Comment by mttfranci** [comment]
Per l'operazione ANPR 2520437 noi troviamo come richiesta : 

      <criteriRicerca>
        <codiceFiscale>XXXXXXXXXXXX</codiceFiscale>
        <tipoScheda>1</tipoScheda>
        <identificativoANPR>29817943</identificativoANPR>
      </criteriRicerca>

Relativi all'operazione comune 

        <idOperazioneComune>SmartAnprDev1005844</idOperazioneComune>
        <codMittente>888180</codMittente>


Possibile abbiate usato lo stesso id operazione comune due volte e quindi vi abbia restituitl a risposta di una precedente interrogazione?

Potente confermarci la richiesta completa? (sempre nascontendo solo eventuali dati sensibili).


Saluti

**Comment by Eduardo1977** [comment]
Il sistema genera in maniera incrementale l'idOperazioneComune, che di fatto è stato usato una sola volta. 
La request completa è la seguente: 
&lt;ns2:Richiesta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione"&gt; 
&lt;testataRichiesta&gt; 
&lt;idOperazioneComune&gt;SmartAnprDev1005844&lt;/idOperazioneComune&gt; 
&lt;codMittente&gt;888180&lt;/codMittente&gt; 
&lt;codDestinatario&gt;ANPR02&lt;/codDestinatario&gt; 
&lt;operazioneRichiesta&gt;3002&lt;/operazioneRichiesta&gt; 
&lt;dataOraRichiesta&gt;2020-07-29T13:14:54.738+02:00&lt;/dataOraRichiesta&gt; 
&lt;tipoOperazione&gt;C&lt;/tipoOperazione&gt; 
&lt;tipoInvio&gt;FREE&lt;/tipoInvio&gt; 
&lt;dataDecorrenza&gt;2020-07-29&lt;/dataDecorrenza&gt; 
&lt;nomeApplicativo&gt;SmartANPR&lt;/nomeApplicativo&gt; 
&lt;versioneApplicativo&gt;1.2&lt;/versioneApplicativo&gt; 
&lt;fornitoreApplicativo&gt;Servizi Locali S.p.A.&lt;/fornitoreApplicativo&gt; 
&lt;/testataRichiesta&gt; 
&lt;criteriRicerca&gt; 
&lt;codiceFiscale&gt;BRTSMXXXXXXXXXXF&lt;/codiceFiscale&gt; 
&lt;tipoScheda&gt;1&lt;/tipoScheda&gt; 
&lt;identificativoANPR&gt;29817943&lt;/identificativoANPR&gt; 
&lt;/criteriRicerca&gt; 
&lt;datiRichiesta&gt; 
&lt;schedaAnagraficaRichiesta&gt;1&lt;/schedaAnagraficaRichiesta&gt; 
&lt;dataRiferimentoRichiesta&gt;2020-07-29T13:14:24&lt;/dataRiferimentoRichiesta&gt; 
&lt;datiAnagraficiRichiesti&gt;1&lt;/datiAnagraficiRichiesti&gt; 
&lt;ricercaNazionale&gt;1&lt;/ricercaNazionale&gt; 
&lt;/datiRichiesta&gt; 
&lt;/ns2:Richiesta3002&gt;

La risposta invece come sapete contiene tutti i soggetti appartenenti alla famiglia "29817943". 
La risposta corretta non doveva contenere nessun soggetto perchè "BRTSMXXXXXXXXXXF" non sta nella famiglia "29817943".

Ringrazio per il riscontro

**Comment by mttfranci** [comment]
Ok, ora ho capito la questione.

1) Per la ricerca per data di nascita riuscite a fornire un id operazione?

2) Per l'operazione 2520437  al momento il servizio funziona con una gerarchia dei criteri.
I parametri della ricerca per famiglia e per soggetto sono valutati separatamente.

Se vengono passati i criteri della ricerca per famiglia : 
<tipoScheda>1</tipoScheda>
<identificativoANPR>29817943</identificativoANPR>
Si attiva la sola ricerca per  famiglia e vengono ignorati i criteri di ricerca per soggetto.

Se invece non vengono trovati i parametri di ricerca per famiglia viene eseguita l'interrogazione per soggetto.

Valuteremo se dare una segnalazione in questi casi, ma sul servizio di consultazione dobbiamo stare attenti ad evitare problemi ad altri gestionali che magari ora fanno affidamento su un comportamento consolidato.

Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Buongiorno, risolta/chiarita la casistica che ha come criteri 'codice fiscale' + 'famiglia', resta quella che ha invece contemporaneamente come parametri 'codice fiscale', 'cognome', 'nome', 'data nascita'. Ho da poco effettuato in FREE una ricerca che volutamente ha il valore di 'data nascita' sbagliato (il giorno). La risposta del servizo ha  IdOperazioneANPR=2524678 e contiene la scheda anagrafica completa, quando invece mi sarei aspettato un messaggio di errore come quando è sbagliato il 'cognome' o 'il nome' (i.e. codiceErroreAnomalia=EN068 - il nome del soggetto estratto non è congruente con quello passato come parametro di ricerca). A meno che anche in questo caso non sia applicata una gerarchia di criteri, che "ignorano" il valore di 'dataNascita' in presenza di 'codice fiscale', 'cognome', 'nome' esatti , faccio presente che non sono del tutto sicuro che il criterio 'dataNascita' passato nella request sia esatta (va passato nel nodo 'dataNascita' oppure nel nodo 'dataEvento' annidato nel nodo 'datiNascita' ?). In ogni caso sarebbe utile avere una documentazione aggiornata e dettagliata sul servizio 3002, in modo da poterlo utilizzare con le varie casistiche di ricerca, per evitare di incappare in comportamenti non attesi.  Ringrazio come sempre per la cortesia e la disponibilità. Resto in attesa di riscontro. Saluti

**Comment by Eduardo1977** [comment]
Aggiungo anche che facendo la ricerca senza 'codice fiscale' ma utilizzando solo 'cognome', 'nome', e 'data nascita' per trovare tutti i "Rossi Mario" nati il "03/08/1970" (ce ne sarebbe solo 1), il servizio restituisce tutti i "Rossi Mario" (3 risultati) ignorando il criterio per data di nascita, che aumenta i miei dubbi sul fatto che la request sia corretta. L'operazione è appena stata effettuata, IdOperazioneANPR=2524809

**Comment by mttfranci** [comment]
Allora a noi non risulta che in nessuna delle richieste che avete inviato (almeno quelle per le quali avete fornito l'id operazione anpr) la data di nascita sia stata impostata.

Ad ogni modo noto ora che noto ora che il modo in cui avete indicato l'XML per la data di nascita è diverso da come indicato nelle specifiche.
In particolare la data di nascita deve essere inviata tramite l'elemento annidato datiNascita.dataEvento.

Ecco lo stralcio delle specifiche : 

![image](https://user-images.githubusercontent.com/29305782/89261653-b4e57e00-d62e-11ea-9fc3-e3dd82a76843.png)

E della rappresentazione del WSDL : 

![image](https://user-images.githubusercontent.com/29305782/89261723-d8102d80-d62e-11ea-9348-18dfb08d570e.png)

Dato che i nostri sistemi perimetrali bloccano le richieste con elementi non validi, temo che il vostro client non abbia affatto inviato la data di nascita così come indicata nel primo esempio : 

<criteriRicerca>
<codiceFiscale>xxxxxxxxxxxxxxx</codiceFiscale>
<cognome>xxxxxxx</cognome>
<nome>xxxxxxxxxx</nome>
<dataNascita>1986-08-23</dataNascita>
</criteriRicerca>

Potete verificare? (forse il marshaller del vostro client lo ha ignorato perchè elemento non presente nell'XSD).

Siamo a disposizione per qualsiasi ulteriore chiarimento

**Comment by Eduardo1977** [comment]
Buongiorno, precedentemente avevo già provato anche tramite l'elemento annidato datiNascita.dataEvento. In ogni caso, ho appena rifatto una prova. Nei criteri di ricerca la data di nascita è volutamente sbagliata ma viene restituita la scheda del soggetto che corrisponde al cognome e nome passati. La risposta corrisponde a IdOperazioneANPR=2525351,  a fronte della seguente request:
&lt;ns2:Richiesta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione"&gt; 
&lt;testataRichiesta&gt; 
&lt;idOperazioneComune&gt;SmartAnprDev1006073&lt;/idOperazioneComune&gt; 
&lt;codMittente&gt;888180&lt;/codMittente&gt; 
&lt;codDestinatario&gt;ANPR02&lt;/codDestinatario&gt; 
&lt;operazioneRichiesta&gt;3002&lt;/operazioneRichiesta&gt; 
&lt;dataOraRichiesta&gt;2020-08-04T08:58:17.607+02:00&lt;/dataOraRichiesta&gt; 
&lt;tipoOperazione&gt;C&lt;/tipoOperazione&gt; 
&lt;tipoInvio&gt;FREE&lt;/tipoInvio&gt; 
&lt;dataDecorrenza&gt;2020-08-04&lt;/dataDecorrenza&gt; 
&lt;nomeApplicativo&gt;SmartANPR&lt;/nomeApplicativo&gt; 
&lt;versioneApplicativo&gt;1.2&lt;/versioneApplicativo&gt; 
&lt;fornitoreApplicativo&gt;Servizi Locali S.p.A.&lt;/fornitoreApplicativo&gt; 
&lt;/testataRichiesta&gt; 
&lt;criteriRicerca&gt; 
&lt;cognome&gt;B**T*N*&lt;/cognome&gt; 
&lt;nome&gt;S***N* FREE&lt;/nome&gt; 
&lt;datiNascita&gt; 
&lt;dataEvento&gt;1976-08-28&lt;/dataEvento&gt; 
&lt;/datiNascita&gt; 
&lt;/criteriRicerca&gt; 
&lt;datiRichiesta&gt; 
&lt;schedaAnagraficaRichiesta&gt;1&lt;/schedaAnagraficaRichiesta&gt; 
&lt;dataRiferimentoRichiesta&gt;2020-08-04T08:58:17&lt;/dataRiferimentoRichiesta&gt; 
&lt;datiAnagraficiRichiesti&gt;1&lt;/datiAnagraficiRichiesti&gt; 
&lt;ricercaNazionale&gt;1&lt;/ricercaNazionale&gt; 
&lt;/datiRichiesta&gt; 
&lt;/ns2:Richiesta3002&gt;

**Comment by Eduardo1977** [comment]
Forse, l'elemento annidato non è "datiNascita.dataEvento" ma  "**datiNascita.dataNascita**", come leggo ora nel file "tipoDato.xsd"

**Comment by Eduardo1977** [comment]
Non funziona neanche con l'elemento annidato  "**datiNascita.dataNascita**".  Continua a restituire la scheda del soggetto relativa a 'cognome' e 'nome' nonostante la data di nascita sbagliata. IdOperazioneANPR=2525364

**Comment by mttfranci** [comment]
Buongiorno, l'unico formato corretto è il seguente : 

```
     <datiNascita>
        <dataEvento>YYYY-MM-DD</dataEvento>
      </datiNascita>      
```
Nè nell'operazione 2525364 nè negli altri casi è arrivata alcuna data di nascita fino ai nostri sistemi.
Il formato nell'elemento XSD è sicuramente 
datiNascita.dataEvento

Dove avete trovato "datiNascita.dataNascita" ?
Grazie in anticipo.

**Comment by Eduardo1977** [comment]
Buongiorno, scusate il notevole ritardo con cui rispondo. Volevo solo comunicarvi che il problema era stato risolto grazie al vostro riscontro. L'errore stava nel fatto che i tag della data di nascita venivano inclusi all'interno di "criteriRicerca". Grazie ancora.
