### ISSUE TITLE
Iscrizione di un soggetto precedentemente cancellato da ANPR

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2177]
Salve,
comune di Montoro (AV)
Stiamo tentando di iscrivere nella APR comunale il cittadino con ID 80078860
cancellato per altri motivi da ANPR da parte del comune di Sesto San Giovanni (MI) nonostante il comune di destinazione (Montoro) fosse subentrato in ANPR.

Il soggetto ora risulta cancellato.
Nel completare la procedura di iscrizione per altri motivi ci viene mostrato il seguente errore alla fine della procedura:

Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune SESTO SAN GIOVANNI (MI) con numero pratica ANPR: 26022614

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-30 12:28:43 , idOperazioneANPR 300153485

Come possiamo risolvere?

**Comment by frmariani** [comment]
Sono in contatto con il comune di Sesto San Giovanni per annullare l'operazione di cancellazione per altri motivi in modo che possiate effettuare la corretta operazione di mutazione della residenza del soggetto.

**Comment by frmariani** [comment]
il comune ha annullato la cancellazione per altri motivi ed ha chiuso il procedimento amministrativo; potete modificare la residenza del cittadino

**Comment by frmariani** [comment]
ho appurato che la residenza è stata modificata. chiudo la issue
