### ISSUE TITLE
Doppi spazi in nome, generalità non modificabili nonostante cf validato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2178]
Buongiorno
Il Comune di Sassuolo, sta cercando di cambiare il cognome del cittadino id 75351653. Il cambio del cognome comporta cf nuovo, non presente in AE. Il cittadino ha CF validato. Sembra quindi la situazione più semplice, però continuano a ricevere nei vari tentativi l'errore   EAM12 Soggetto non individuato in AT - Codice fiscale NON variato.

Alla fine ci accorgiamo che nonostante sia validato, nel campo nome ha due nomi, separati da uno spazio in AE, e separati da due spazi in ANPR. 

Pensiamo quindi di fare una mutazione in due tempi: di togliere uno spazio tra i nomi, da ANPR. E il giorno dopo di modificare il cognome. 

Proviamo da webapp a togliere uno spazio tra i nomi, senza modificare il cognome ma riceviamo l'errore:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-30 16:00:38 , idOperazioneANPR 300363741 (Codice: EN527)

A cosa è dovuto?

**Comment by frmariani** [comment]
è stata effettuata la contemporanea modifica del cognome e dell'eliminazione dello spazio ? in questo caso gentilmente mi indichi l'idanpr dell'operazione, altrimenti esegua l'operazione come indicato e mi faccia sapere.

**Comment by MarcoMigliori** [comment]
Abbiamo riprovato con esito:

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-31 10:19:16 , idOperazioneANPR 300853631 (Codice: EN527)

**Comment by frmariani** [comment]
riprovi ora per favore

**Comment by MarcoMigliori** [comment]
Abbiamo riprovato come indicato con cambio di cognome e eliminazione spazio. Ora l'esito è:

Soggetto non presente in Agenzia Entrate (Codice: EAV91)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-07-31 10:43:07 , idOperazioneANPR 300894329 (Codice: EN527)

**Comment by frmariani** [comment]
state indicando erroneamente il nuovo CF

**Comment by frmariani** [comment]
ho contattato le colleghe di Agenzia delle Entrate: con l'allineamento effettuato questa mattina per la sola validazione dei dati anagrafici, è stato aggiornato l'indirizzo nei loro sistemi, pertanto per effettuare una nuova modifica si devono attendere 24H.
Come da accordi per le vie brevi, può ripetere l'operazione di modifica del cognome domani mattina e tracciarne l'esito in questo spazio.

**Comment by MarcoMigliori** [comment]
Stamattina la 5008 di modifica del cognome ha funzionato regolarmente. Grazie.
