### ISSUE TITLE
operazione in sospeso per disallineamento CF in AE

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2179]
Per il comune di Potenza (cod. istat 076063) è stato registrato un bambino in anagrafe per nascita, contemporaneamente il padre aveva provveduto ad iscriverlo presso l'agenzia delle entrate. In anagrafe hanno commesso un errore di battitura della data di nascita e quindi è stato calcolato il CF per il mese, specificato, mentre in AT gli è stato attribuito quello "giusto". Adesso non riusciamo ad effettuare una variazione anagrafica (idoperazione: 301072690 del 2020-07-31 12:31:45)  e neppure dalla web app, dal menu: Utilità e Notifiche --> Risoluzione disallineamenti con Agenzia Entrate riusciamo ad allineare i rispettivi CF perchè riceviamo una segnalazione con il seguente messaggio: "Soggetto non trovato per i criteri indicati o già validato o esiste un'operazione in sospeso per il soggetto" (idanpr cittadino: 88267706)

**Comment by rvinzani** [comment]
E' necessario collegare i due CF utilizzando la funzione Risoluzione disallineamenti co Agenzia Entrate. Doverte inserire il CF errato, spuntare includi validati, togliere la spunta dal check coincidenti e inserire il CF corretto e premere il tasto cerca. Selezionare l'elemanta della lista e nella pagina successiva spuntare il check collega CF (sulla sinistra sotto il luogo di nascita) e premere conferma. Questa operazione aggiornerà ANPR con i dati corretti e collegherà i due codici fiscali

**Comment by carminepat** [comment]
Abbiamo seguito le istruzioni da voi indicate ma nella funzione di utilità, spuntando il check "collega codici fiscali" scompare il pulsante sottostante: "CONFERMA AE" di cui noi abbiamo necessità per approvare i dati che ci vengono proposti dall'agenzia delle entrate, in modo da correggere il nostro errore di battitura della data di nascita e disequivocare i CF. Come procediamo?

**Comment by rvinzani** [comment]
Procedete pure con il conferma. L'operazione che ne deriva sostituisce i dati in ANPR con i dati presenti in AE e collega i due codici fiscali
