### ISSUE TITLE
Comune risulta inadempiente nel ritiro delle Smart Card

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2181]
Si segnala che il Comune di Balvano (cod istat: 076008), il cui subentro è previsto per il giorno 03/09/2020, sulla Dashboard ANPR risulta inadempiente nel ritiro delle Smart Card, pur avendole regolarmente ritirate.
La prefettura di competenza ha comunicato di aver regolarmente attivato sul sistema le smart card, e sulla piattaforma ANPR risultano attive entrambe le smart card ritirate.
Si chiede gentilmente di provvedere a risolvere il problema, ovvero ricevere indicazioni sulle modalità di risoluzione.
Cordialità.

**Comment by Leonforte** [comment]
Buongiorno,
l'indicazione della dashboard circa il ritiro delle sc non comporta alcun problema per le operazioni di subentro. Ciò premesso l'indicazione errata è stata dovuta alla assenza del profilo di Sindaco (ASC) tra gli utenti, che ora è stato assegnato d'ufficio. Nel pomeriggio l'indicazione sulla dashboard sarà aggiornata, saluti
