### ISSUE TITLE
Comune di Riano - seconda parte password - pin - puk

### ISSUE THREAD

**Issue by Rianoanagrafe** [italia/anpr#2182]
Salve,
dalla prefettura abbiamo ricevuto le smart card e la prima parte di passwor pin e puk,
attivando gli utenti e le smart card con l'utenza del sindaco non è arrivata a nessuno la mail di conferma,
dal portale è consentito il reinvio di pin e puk, ma non della password, dato che siamo in procinto di popolare il presubentro chiediamo la possibilità di poter avere anche la seconda parte della password,
grazie 
Giuseppina Napoleone
Comune di Riano (RM)

**Comment by Leonforte** [comment]
buongiorno, le mail con la pwd sono state reinviate. ricordo comunque che l'accesso all'ambiente di presubentro deve essere effettuato nelle stesse modalità dell'ambiente di produzione, quindi con la smart card. buon lavoro, saluti
