### ISSUE TITLE
Rettifica numero foglio famiglia AIRE

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2184]
Buongiorno,

vorremmo sapere se e come è possibile rettificare un numero foglio di famiglia AIRE caricato in Mutazione residenza AIRE erroneamente.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by frmariani** [comment]
se per "numero foglio di famiglia AIRE" intende l'identificativo scheda attribuito dal Comune , si può procedere con il servizio di Mutazione famiglia/convivenza tipo mutazione Motivo famiglia/Specie convivenza;

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
