### ISSUE TITLE
L'operazione da annullare non è l'ultima

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2185]
COMUNE DI MISTERBIANCO
Ambiente di Produzione

Buongiorno,
tentando di annullare la mutazione  idOperazione ANPR 264218902 con il servizio in oggetto otteniamo l'errore "EN077 L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa.". ID anpr operazione annullamento è 304722792

non riusciamo a capire quale sia la mutazione bloccante.Potete aiutaci ?
Grazie

**Comment by frmariani** [comment]
il comune di Catania, dopo la mutazione di residenza del vostro cittadino, ha effettuata la rettifica dell'indirizzo della famiglia di provenienza, pertanto non è più possibile annullare la vostra operazione. 
Nel caso, il comune di Catania dovrebbe annullare la sua operazione di rettifica ed effettuarla nuovamente dopo l'annullamento della vostra operazione.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
