### ISSUE TITLE
 EN243 I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2186]
COMUNE DI ISCHIA
Ambiente di Produzione

Buongiorno. Stiamo cercando di allineare una cessazione di matrimonio di aire (id operazione anpr 305523913).  Riceviamo l'errore : EN243 I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto." nonostante i dati del coniuge corrispondano.  Come possiamo procedere per allineare i dati?
Grazie

**Comment by azabatta** [comment]
Salve, 
l'incongruenza rilevata dal sistema è con i dati dell'evento matrimonio (il testo dell'errore è fuoriviante). A fronte di una data matrimione 07.05.2016 è stata indicata come data della sentenza di cessazione 07.11.2008. La richiesta inviata è corretta basta rettificare la data della sentenza.
Buona serata

**Comment by azabatta** [comment]
Buonasera, 
nella richieesta di mutazazione dati scheda pervenuta in data odierna (id operazione ANPR) la data della sentenza di cessazione continua ad essere minore della data dell'evento di matrimonio pertanto l'operazione non va a buon fine. 
Se si desidera essere seguiti nella trasmissione dei dati a sistema contattare il servizio di assistenza 800863116.
