### ISSUE TITLE
Notifiche mutazione di residenza in ritardo

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2187]
COMUNE DI CHIUSI
Ambiente di produzione

Buongiorno,
vorrei segnalare un ritardo di avvenuta notifica di cancellazione, riporto un esempio pratico:
1 soggetto fa una mutazione di residenza  dal comune di CHIUSI al comune di  RADICOFANI
con data di decorrenza **01/08/2020**, fino a qui tutto ok.
Notiamo pero' che la NOTIFICA MUTAZIONE DI RESIDENZA  (nr. 304592923) 
è stata elaborata dopo 4 giorni ( il **05/08/2020**).
Questo intervallo di tempo a nostro avviso è troppo elevato, in questo caso non ha permesso al comune di precedente iscrizione CHIUSI, di cancellare l'elettore con la revisione dinamica straordinaria prima tornata.

Potete verificare e darci un riscontro?

Grazie

**Comment by azabatta** [comment]
Buonasera, 
in linea generale le notifiche sono prodotte subito dopo l'acquisizione a sistema dell'evento anagrafico.
Nello specifico la notifica in questione  è stata prodotta 7 minuti dopo l'inserimento dell'evento di mutazione da parte del comune di nuova residenza.
Buona serata
