### ISSUE TITLE
ALLINEAMENTO CODICI FISCALI

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2188]
CONFERMA DATI AGENZIA DELLE ENTRATE
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-08-07 09:41:51 , idOperazioneANPR 306697263 (Codice: EN527)
Esito ANPR: Variazione non consentita per superamento numero campi variati (Codice: EAM93)
telefono 0923993382

**Comment by frmariani** [comment]
quando i campi da variare sono più di tre, non è possibile effettuare le modifiche con le funzionalità presenti nel sistema ANPR; in questi casi deve scrivere alla Direzione Centrale dell'Agenzia delle Entrate al seguente indirizzo
entrate.archivioanagrafico@agenziaentrate.it
allegando la documentazione in suo possesso che giustifichi le modifiche richieste

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
