### ISSUE TITLE
Allineamento codice fiscale soggetto residente in altro comune per AT

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2189]
Dopo il subentro per il comune di San Mauro Forte (MT) (cod istat: 077026) ci viene segnalato dal monitoraggio anomalie di bonificare un soggetto con CF diverso tra ANPR ed AT. Cercando dalla funzione presente in utilità il soggetto con CF non coincidente, effettuiamo le dovute verifiche e selezioniamo di mantenere il soggetto con i dati opportuni, purtroppo l'operazione non va a buon fine perchè in AT il soggetto risulta residente in altro comune. Come risolviamo?

**Comment by frmariani** [comment]
per favore l'idanpr del soggetto

**Comment by carminepat** [comment]
L'id anpr del soggetto è 91937082

**Comment by frmariani** [comment]
il problema non è la residenza; in ANPR è presente un CF collegato rispetto al principale presente in AT.
La differenza sta nella data di nascita, qual'è quella corretta ?

**Comment by carminepat** [comment]
I dati corretti sono quelli presenti in anpr con data di nascita 18/04/1938

**Comment by frmariani** [comment]
in questo caso deve effettuare quello che in gergo si chiama "inversione di link"; deve effettuare una mutazione dei dati anagrafici inserendo il CF corretto e la data di nascita corretta

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
