### ISSUE TITLE
Stati esteri cessati  non esistenti nella tabella Anpr

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#219]
Salve,
scrivo per il Comune di Bologna, riguardo chiarimento su stati esteri cessati non esistenti nella tabella ANPR.
Per tutti quei casi dove tuttora l’agenzia delle entrate rilascia codici fiscali relativi a stati esteri cessati ( es. Yugoslavia ed Unione Sovietica) senza verificare i dati per il calcolo con l’anagrafe e le tabelle degli stati esteri di ANPR non contemplano questi stati, passando nel subentro  in ANPR  la codifica  dello stato 998 con la descrizione dello stato, tali persone entrano in Anpr?  Se entrano in ANPR si possono certificare e fare movimenti anagrafici oppure vengono bloccati?

Cordiali Saluti
Grazie
Cordiali Saluti
Elena Di Martino

**Comment by gcarbonin** [comment]
L'Agenzia delle Entrate non considera il codice ISTAT; quindi l'utilizzo del codice 998 non pregiudica nessuna operazione. Rimangono valide le regole generali: i dati come stato di nascita o cittadinanza di uno straniero residente in ITALIA si desumono da documenti validi. Oggi un documento valido che riporti "cittadino jugoslavo" non può esistere. Quindi occorrerà adeguare quanto registrato in anagrafe, ma non per l'utilizzo del codice 998.

**Comment by RBiasi** [comment]
Buongiorno,
Comune di Castiglion Fiorentino pre subentro 
i casi di cittadini nati in YUGOSLAVIA che abbiamo sono italiani ed iscritti AIRE che operazioni non saranno effettuabili su questi cittadini?

Grazie

**Comment by gcarbonin** [comment]
Le normali operazioni.

**Comment by RBiasi** [comment]
tutte le operazioni non saranno effettuabili finchè non si corregge il luogo di nascita?

**Comment by gcarbonin** [comment]
Sul luogo di nascita ci sono le tolleranze. Quello che è obbligatorio modificare è la cittadinanza ma trattandosi di iscritti AIRE quella è necessariamente italiana. Vediamo poi facendo qualche prova se occorre modificare qualche controllo
