### ISSUE TITLE
RIPRISTINO POSIZIONE PRESENTE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2190]
IN SEGUITO A RIPRISTINO POSIZIONE ANAGRAFICA UN CITTADINO RISULTA REGOLARMENTE RESIDENTE NELL'ANAGRAFE LOCALE, IN ANPR COME SOGGETTOCANCELLATO.
IN DATI DI CANCELLAZIONE FIGURA RIPRISTINO POSIZIONE PRECEDENTE. NON RIESCO A TRASFERIRLO NEL MIO COMUNEIN ANPR.
GRAZIE
0923993382

**Comment by frmariani** [comment]
fornite indicazioni per le vie brevi. mi faccia sapere l'esito dell'operazione

**Comment by filippo1961** [comment]
Grazie tutto risolto

**Comment by filippo1961** [comment]
grazie tutto risolto






Comune di Marsala 
Ufficio Anagrafe 
L'ufficiale d'anagrafe 
Filippo Asaro 
Tel: 0923993382
email: asaro.filippo@comune.marsala.tp.it 
email: protocollogenerale@comune.marsala.tp.it 
pec: protocollo@pec.comune.marsala.tp.it    

_______________________________________________________________________________________________________________________________________________________________________________ 

Le informazioni contenute nella presente e-mail ed eventualmente negli allegati possono essere confidenziali e sono comunque riservate al destinatario della stessa. La loro comunicazione, diffusione, copiatura da parte di terzi e' proibita. Se avete ricevuto questa comunicazione per errore, Vi preghiamo di informare immediatamente il mittente del messaggio e di distruggere il messaggio. Si avvertono i destinatari che tutti i messaggi di posta provenienti dal dominio @comune.marsala.tp.it hanno natura aziendale e non personale e pertanto potranno essere conosciuti dall'azienda. 

This transmission is intended for the use of the addressee only and is confidential and may be the subject of privilege and exempt for disclosure. Any extraction, distribution, copying or use of this communication is strictly prohibited. If you have received this communication in error, please notify us by telephone and then return the original message and attachments to us at the above address. 





Da: "frmariani" notifications@github.com
A: "italia/anpr" anpr@noreply.github.com
Cc: "filippo1961" asaro.filippo@comune.marsala.tp.it,"Author" author@noreply.github.com
Data: Fri, 07 Aug 2020 03:45:38 -0700
Oggetto: Re: [italia/anpr] RIPRISTINO POSIZIONE PRESENTE (#2190)



fornite indicazioni per le vie brevi. mi faccia sapere l'esito dell'operazione
