### ISSUE TITLE
Rettifica indirizzo di residenza fam. 9079438

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2191]
Buongiorno.

Abbiamo la necessità di rettificare l'indirizzo di residenza della famiglia anagrafica con codice 9079438 fin dal suo subentro, cioè con decorrenza dal 02/03/2013.

La modifica di indirizzo da effettuare è da VIA AMPELIO PESSINA n. 7 a VIA AMPELIO PESSINA n. 7 esponente TER.

Lascio i miei recapiti:

Paltrinieri Andrea
Ufficiale d'Anagrafe del Comune di Biassono (cod. 108009)
tel. 039-2201060
e-mail: anagrafe@biassono.org

Distinti saluti.

Andrea Paltrinieri

**Comment by frmariani** [comment]
per rettificare l'indirizzo della famiglia può utilizzare il servizio Mutazione Famiglia/Convivenza tipo di mutazione Rettifica/Integrazione indirizzo; attenzione però la data di decorrenza della famiglia risulta 02/05/2013, ed è questa la data di decorrenza dell'operazione che deve utilizzare.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
