### ISSUE TITLE
Variazione CAP

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2192]
Comune di Villa Cortese 015248
Produzione

Buongiorno,
Poste Italiane il 25 maggio ha cambiato il CAP del nostro comune da 20020 a 20035. Il vecchio CAP sarà ancora utilizzabile fino a maggio 2021.
Ho già letto la [Issue 799](https://github.com/italia/anpr/issues/799) che trattava dello stesso argomento.
Chiedo se sia possibile prevedere anche per il nostro comune l'aggiornamento automatico.

Grazie
Claudio Vignati

**Comment by ncapozzi** [comment]
Buongiorno,
in realtà in nessun caso pregresso è stato predisposto da parte nostra un aggiornamento automatico massivo del campo CAP.
Per la modifica di tale campo è possibile utilizzare il WS 5001 - Mutazione famiglia/convivenza con tipo = 9 - RETTIFICA/INTEGRAZIONE INDIRIZZO che lascia invariata la data di decorrenza della residenza dei cittadini interessati.  Naturalmente il WS 5001 deve essere richiamato per ogni famiglia.

N. Capozzi
