### ISSUE TITLE
Cancellazione atto di cessazione matrimonio errato

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2193]
Buongiorno,
abbiamo questo problema: abbiamo sistemato lo stato civile di una nostra residente che è DIVORZIATA. Al momento dell'inserimento era stato definito come stato civile VEDOVA, poichè l'ex marito è deceduto (ma al momento del decesso era, appunto, già EX).
Ora in Anpr lo stato civile è corretto e sono presenti gli estremi del divorzio ma non riusciamo a cancellare l'atto di cessazione del matrimonio che si riferisce all'atto di morte dell'ex coniuge. Anche sbiancando i campi, segnala operazione eseguita con successo ma non li cancella. Come possiamo procedere?
Grazie,
cordiali saluti.

**Comment by frmariani** [comment]
per eliminare un dato inviato con il subentro deve utilizzare il servizio di Eliminazione Dati, tenendo presente che eliminerà sia i dati del matrimonio che quelli della vedovanza; se invece il dato è stato acquisito con un'operazione, questa deve essere annullata.

Se mi indica l'idanpr della cittadina potrò essere più precisa nella corretta operazione da effettuare.

**Comment by katiavacchi** [comment]
Ok grazie: Id Anpr 21150439

**Comment by frmariani** [comment]
purtroppo devono essere eliminate tutte le operazioni effettuate, compreso il decesso dell'ex coniuge; successivamente si dovrà inserire la cessazione del matrimonio e poi di nuovo il decesso del soggetto.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
