### ISSUE TITLE
[5008 da WebApp] Correzione nome convivente di fatto

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2194]
Buongiorno
Il Comune di Savona ha fatto alcune correzioni sulle convivenze di fatto tra cui una sull'id cittadino  59297060 che ha avuto esito positivo, ma che continua a mostrare il dato errato.

L'operazione è stata eseguita 3 volte, di cui l'ultima è l'id operazione 306179595 che include il nome del convivente di fatto reale, il cui codice fiscale inizia per SMRM. Se consulto la risposta sembra tutto positivo.
Se passo alla consultazione scheda individuale, nel tab "Convivenza di fatto" continuo a vedere il nome dell'ex coniuge, precedente alla correzione, il cui codice fiscale inizia per  TNNM.

Non capiamo perchè.

Nota: l'unica stranezza è che l'ex coniuge è legato per codice fiscale. E l'ex coniuge nel 2019, è stato cancellato per irreperibilità. Nell'elenco operazioni del cittadino 59297060, vedo infatti l'operazione 102533589, che è relativa all'ex coniuge.

**Comment by frmariani** [comment]
purtroppo con il subentro sono stati inviati dei dati non corretti per il cittadino in questione che hanno generato la discordanza dei dati nella consultazione; 
abbiamo eliminato l'anomalia, riprovate la consultazione

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
