### ISSUE TITLE
data decesso/ data registrazione decesso in anagrafe/ cancellazione da anagrafe/certificazione residenza storica INCONGRUENZA?

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#2195]
Buongiorno,
cittadino muore il 17/07/2020 
il decesso viene "materialmente" registrato in anagrafe il 21/07/2020
il sistema registra la cancellazione in anagrafe DAL 21/07/2020
richiesta di certificato di residenza storico: il sistema mi consente di certificare fino al 20/07/2020 con la seguente dicitura:
residente in via... dal XXX al 17/07/2020 (data del decesso).
sulla testata del certificato : certificato storico di residenza alla data del 20/07/2020
Chiedo di valutare l'opportunità di mantenere la **corrispondenza** tra la data del decesso (giuridica) e la data di cancellazione dall'anagrafe, indipendentemente da quando materialmente si inserisce nel data base il decesso.
Grazie dell'attenzione
Raffaella
Venezia
0412746575
![STORICO](https://user-images.githubusercontent.com/56832730/90113936-51f09700-dd52-11ea-97cc-90702848d7cc.JPG)
![STORICO 1](https://user-images.githubusercontent.com/56832730/90113975-5cab2c00-dd52-11ea-95db-64747cf4545b.JPG)

**Comment by frmariani** [comment]
come esposto per le vie brevi, i certificati ANPR tengono conto della data da cui decorre l'informazione acquisita (data di decorrenza dell'operazione), anche per non contrastare eventuali certificati emessi  successivamente all'evento (17/07/2020) ma prima dell'inserimento dell'informazione (21/07/2020);  mi rendo conto dell'esigenza espressa ma per eventuali sviluppi sul caso, sarebbe meglio rivolgersi al Ministero dell'Interno.
