### ISSUE TITLE
[5008] non riesce completamento pratica tipomutazione 20 per problemi sulle date

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2196]
Buongiorno. Il Comune A ha tentato di iscrivere in data 27 luglio un soggetto, ma si è trovato un procedimento in corso. Hanno contattato il Comune B che in data 30 luglio ha chiuso il procedimento (non so come) e in stessa data quindi il Comune A iscrive il cittadino.

Oggi alla definizione positiva della pratica di residenza il Comune A dopo vari tentativi riceve l'errore

EN389 La data decorrenza 27-07-2020 dell'operazione non puo' essere inferiore alla data decorrenza 30-07-2020 dell'ultima operazione effettuata sui dati relativi a stato civile

EN527  Informazioni sull'operazione da fornire in caso di assistenza : data 2020-08-13 11:15:57 , idOperazioneANPR 310756188

Le date visibili in ANPR sembrano però tutte a posto. Può darsi che il Comune B abbia chiuso il procedimento indicando la data del 30 luglio invece che quella vera, e che questo ci causi il problema?

**Comment by frmariani** [comment]
Come suggerito dall'errore, in data 30 Luglio sono state effettuate due modifiche sul soggetto, lo stato civile e l'inserimento del cittadino nella lista elettorale (operazioni effettuate dall'altro comune); nel completamento, tra le altre informazioni,  è presente quella sullo stato civile, ed è questo che blocca l'operazione ad una data antecedente all'ultima operazione effettuata sulla stessa tipologia di dati.
Ripetete l'operazione di completamento alla data desiderata eliminando dall'operazione di completamento l'informazione sullo stato civile.

**Comment by MarcoMigliori** [comment]
eseguito, grazie
