### ISSUE TITLE
Mutazione residenza di persone provenienti da famiglie diverse dello stesso comune

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2197]
Buon giorno,
facendo riferimento a un caso segnalatoci più volte dai nostri clienti e già trattato nelle issue #327 e #486, abbiamo simulato in ambiente di test (comune di Colonnella) la seguente situazione.
Due cittadini vanno a costituire nel comune di destinazione una nuova famiglia:
Cittadino 1: proveniente dal comune X (subentrato), unico componente della famiglia di origine, diventa intestatario scheda 
                   nella nuova famiglia;
Cittadino 2: proveniente dal comune X (subentrato), proveniente da una famiglia diversa da quella del cittadino 1, diventa 
                   convivente (o altro rapporto di parentela) nella nuova famiglia.
Seguendo le indicazioni, in questo caso è necessario chiamare l'opportuno servizio di mutazione due volte (una per ogni famiglia di origine), in particolare:
Cittadino 1: è stato chiamato il WS 5001, dato che la mutazione al momento della chiamata interessa l'intera famiglia, 
                   comportando una variazione dell'indirizzo della stessa senza variazione del numero dei componenti;
Cittadino 2: è stato chiamato il WS 5005, in quanto al momento della chiamata entra a far parte di una famiglia esistente 
                    (quella del cittadino 1).
Operando in questo modo siamo riusciti a completare l'operazione, l'unica cosa è che in questo modo non si rappresenta correttamente il fatto che i due individui vanno a costituire nel comune di destinazione una nuova famiglia, dato che in ANPR di fatto avremo una famiglia esistente che cambia residenza, di cui va a far parte il cittadino 2 (o altri). Non è possibile infatti chiamare il WS 5005 per il cittadino 1, in quanto ANPR restituisce il messaggio di errore che per trasferire tutti i componenti di una famiglia, è necessario chiamare il WS 5001. 
Esiste un altro modo per effettuare l'operazione in ANPR, in modo che risulti anche lì il fatto che i cittadini vanno a costituire di fatto una nuova famiglia? Oppure sarebbe corretto modificare la data di origine della famiglia  di destinazione (in questo caso quella del cittadino 1), indicando la data di decorrenza della pratica?
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by frmariani** [comment]
se ho capito bene la richiesta, basterebbe spostare prima il cittadino 2 in modo che vada a costituire una nuova famiglia; in questo modo, il trasferimento del cittadino 1, sarà sempre un 5005  in quanto trasferimento in una famiglia esistente.
Terza operazione, se necessaria, modifica delle relazioni di parentela: intestatario cittadino 1 e convivente cittadino 2.
In questo modo è stata costituita una nuova famiglia con la data corretta.

**Comment by Amucciarelli74** [comment]
Sì, infatti in un primo momento avevamo provato a trasferire prima il cittadino 2 creando una nuova famiglia, ma nella pratica di iscrizione compilata dall'ente risulta convivente (o comunque non intestatario scheda) e ANPR non consentiva di creare una famiglia indicandolo col suo reale rapporto di parentela, in quanto obbliga ad indicare un intestatario della nuova famiglia.
In questo modo sarebbe pertanto necessario indicare il cittadino 2 con un rapporto di parentela "provvisorio" da intestatario scheda e dopo il trasferimento del cittadino 1, da fare anche questo indicando un rapporto "provvisorio", riassegnare con una successiva mutazione i corretti rapporti di parentela. 
Non vi nascondo che si tratta di una operazione piuttosto "macchinosa", oltretutto con la necessità di effettuare delle chiamate supplementari ai servizi, per una situazione che come ho detto i nostri clienti ci riferiscono non essere inusuale. 
Non si potrebbe pensare ad una evoluzione del WS 5001, consentendo magari con opportuni flag anche la creazione di una nuova famiglia per casi come questo?
Grazie comunque per il cortese riscontro, per il momento andremo ad operare nella maniera da voi indicata.
Cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by frmariani** [comment]
terremo presente la vostra richiesta nel caso di eventuali futuri sviluppi
