### ISSUE TITLE
Fanciullo abbandonato - Richiesta urgente

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2199]
Buongiorno,
dobbiamo iscrivere un "fanciullo abbandonato" come intestatario scheda ma iscrivendolo per nascita il flusso verso Anpr si blocca. Come possiamo fare? Potremmo usare "iscrizione per altri motivi"?

La richiesta è urgente.

Grazie.

**Comment by frmariani** [comment]
certamente

**Comment by katiavacchi** [comment]
grazie!
