### ISSUE TITLE
Paternità/Maternità - altriDati

### ISSUE THREAD

**Issue by AGrossiVE** [italia/anpr#220]
Abbiamo osservato che dopo l'invio in ambiente WS di un'iscrizione per nascita, completo dei dati di paternità e/o maternità, non risultano presenti nella WebApp i dati relativi alla sezione "altriDati" di paternità e maternità pur essendo presenti nel file xml trasmesso.

Di seguito alcuni esempi di id comunicazione anpr 210076 oppure 210120

**Comment by gcarbonin** [comment]
E' consentito in iscrizione inserire gli Altri dati dei genitori; per visualizzarli occorre interrogare la scheda dei genitori non quella del figlio.
