### ISSUE TITLE
ERRORE DA ANPR: EC168

### ISSUE THREAD

**Issue by rruggero01** [italia/anpr#2200]
cittadino nato a cremona il 14/08/1937. denominazione corretta cremona ed uniti.

esito dell'evento:
ERRORE DA ANPR:
EC168 - Codice ISTAT del comune di registrazione atto di nascita 019508 incongruente con quello presente sulla tabella di riferimento
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-08-14 16:12:41 , idOperazioneANPR 311712738

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
ERRORE DA ANPR: EC168 (#2200)" inviata il 14/08/2020 16:20:33.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by ncapozzi** [comment]
Buongiorno,
il codice 019508 non è un cod. ISTAT ma un codice denominazione utilizzato per la storicizzazione nei vecchi ambienti INA-SAIA e AIRE. Il cod. ISTAT di CREMONA ED UNITI è comunque 019036 come può verificare sulla tabella pubblicata sul portale WWW.ANPR.INTERNO.IT

N. Capozzi

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
ERRORE DA ANPR: EC168 (#2200)" inviata il 17/08/2020 12:47:07.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
