### ISSUE TITLE
Variazioni denominazioni traslitterate

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2201]
Buongiorno, 
con l'aggiornamento dell'archivio dei comuni del 4 agosto sono state modificate le denominazioni traslitterate di alcuni comuni per le quali è stato rimosso l'apice.

Anche con riferimento a  #770, mi chiedo se siano cambiate le regole di traslitterazione o se si tratti di una svista.

Grazie,
Tiziano

**Comment by ncapozzi** [comment]
Buongiorno,

non sono state cambiate le regole generali di traslitterazione ma è stata corretta la traslitterazione delle denominazioni di alcuni comuni come inidcato negli aggiornamenti. Le traslitterazioni corrette sono:
PRÉ SAINT DIDIER --> PRE SAINT DIDIER
ANTEY SAINT ANDRÉ --> ANTEY SAINT ANDRE
MALÉ --> MALE
ARVIÉ --> ARVIE
PRÉ-SAINT-DIDIER --> PRE-SAINT-DIDIER
GRESSONEY-LA-TRINITÉ --> GRESSONEY-LA-TRINITE
ANTEY-SAINT-ANDRÉ --> ANTEY-SAINT-ANDRE

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Variazioni denominazioni traslitterate (#2201)" inviata il 17/08/2020
14:10:01.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Variazioni denominazioni traslitterate (#2201)" inviata il 17/08/2020
11:07:06.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
