### ISSUE TITLE
[test connessione] connection reset

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2202]
Buongiorno il comune di Monte Grimano Terme - produzione - ha cambiato ISP quindi hanno un nuovo indirizzo IP

dalla web application è stato correttamente abilitato il nuovo IP

ma nonostante risulta con *, il collegamento con ANPR non avviene.

potreste controllare che l'ip sia correttamente memorizzato?

grazie mille
Riccardo

**Comment by cmigliardi** [comment]
Buongiorno, cortesemente potrebbe  inviarci l'ip pubblico e statico?  così  chiedo verifica. grazie

**Comment by cmigliardi** [comment]
Purtroppo non avendo  ricevuto le informazioni richieste   non ho potuto effettuare i controlli.   La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa -

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[test connessione] connection reset (#2202)" inviata il 17/08/2020 15:39:31
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
[test connessione] connection reset (#2202)" inviata il 17/08/2020 12:59:42
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[test connessione] connection reset (#2202)" inviata il 17/08/2020 13:02:49
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 31/08/2020




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[test connessione] connection reset (#2202)" inviata il 17/08/2020 15:39:30
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
