### ISSUE TITLE
Annullamento Cancallazione per doppia iscrizione impossibile.

### ISSUE THREAD

**Issue by MaddaloniAnagrafe** [italia/anpr#2203]
Buongiorno, 

sono Giovanni Pascariello del comune di Maddaloni.
Subito dopo il subentro avvenuto in data 29/03/2020 ho proceduto alla cancellazione per doppia iscrizione di un soggetto.
Dopo una verifica si è scoperto che lo stesso andava cancellato dall'altro comune sempre subentrato e non dal mio.
Ora il soggetto è presente in due individui in consultazione ANPR. Uno Residente nell'altro comune e uno eliminato per doppia iscrizione da parte nostra.

Ora volendo annullare la pratica di cancellazione per altri motivi (doppia iscrizione) viene restituito il seguente errore:

1 Errore Anpr Cod: 999 - Operazione non effettuabile - -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-08-18 13:26:26 , mittente 061048 , idOperazioneComune 7146266 - -

Attendo istruzioni sul da farsi in quanto il soggetto andrebbe ripristinato nel mio comune come se non fosse mai stato cancellato.

Saluti,

Giovanni

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare ad eseguire l'operazione per favore?

**Comment by MaddaloniAnagrafe** [comment]
Ripristino effettuato con successo.

Cordialità


________________________________
Da: ncapozzi <notifications@github.com>
Inviato: mercoledì 19 agosto 2020 09:55
A: italia/anpr
Cc: anagrafe; Author
Oggetto: Re: [italia/anpr] Annullamento Cancallazione per doppia iscrizione impossibile. (#2203)


Buongiorno,
potete riprovare ad eseguire l'operazione per favore?
