### ISSUE TITLE
Cancellazione per altri motivi, doppia iscrizione.

### ISSUE THREAD

**Issue by AnagrafeTerrasini** [italia/anpr#2204]
Buongiorno sono Rosangela Badalamenti, ufficiale d'anagrafe del comune di Terrasini (PA),
devo fare una cancellazione per doppia iscrizione con decorrenza anagrafica del cittadino id
scheda soggetto anpr 84986206, iscritto regolarmente anche nel comune di CARINI con id scheda soggetto anpr 74971240.

All'invio il sistema risponde con il seguente errore:
Cod: EN509 - Il soggetto non puo' essere cancellato per doppia iscrizione perche' non risultano due o piu' posizioni in ANPR.

L'iscirizone corretta è quella del Comune di Carini, abbiamo urgenza visto che la cittadina in questione vorrebbe tornare iscritta nel nostro comune ad un nuovo indirizzo.

In attesa di cortese riscontro auguro una buona giornata,
Rosangela

**Comment by frmariani** [comment]
i comuni sono stati contattati e sono state effettuate le corrette operazioni salvaguardando la giusta storicità delle residenze.
rimango in attesa di conoscere l'esito dell'ultimo passaggio di residenza da parte del comune di Terrasini.

**Comment by frmariani** [comment]
Cambio di residenza effettuato.
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
