### ISSUE TITLE
Utilizzo di ID Protect su ambienti virtuali

### ISSUE THREAD

**Issue by Maga63** [italia/anpr#2205]
Buongiorno volevo saper se vi sono problemi ad utilizzare il driver di idprotect su macchine virtuali per l'utilizzo della Web App. Stiamo sostituendo i vecchi pc con thin client che poi utilizzano sessioni virtuali Citrix.

Grazie

**Comment by rnapoli1983** [comment]
Buongiorno,

secondo noi non dovrebbero esserci particolari problemi. 

E' anche vero che è la prima volta che ci viene posta una domanda sull'argomento che non abbiamo quindi mai approfondito se non con qualche test locale.

Il consiglio è di provare e di segnalarci eventuali problematiche inerenti.

Rimango a disposizione.

Cordiali saluti

**Comment by Maga63** [comment]
Buongiorno, abbiamo aggiornato la versione di ID Protect alla  6.47 rispetto alla 6.44 e ora sembra funzionare.
In precedenza non vedeva la smart card quando si inseriva nel lettore.

Nel caso vi aggiorniamo.
Grazie ancora.

Cordiali saluti.
