### ISSUE TITLE
Tabella 39 - Esenzione bollo revisione delle descrizioni

### ISSUE THREAD

**Issue by deligios** [italia/anpr#2207]
-  Per semplificare la UI nella descrizione dei motivi di esenzione potrebbe essere utile separare la descrizione dai riferimenti normativi che la giustificano
-  Sarebbe bene citare le norme in modo omogeneo (<tiponorma> gg-mm-aaaa, n. <numero>, art. <articolo>) secondo gli standard adottati da [www.normattiva.it](https://www.normattiva.it/static/faq.html#faq20)
-  All'id n. 5 Interdizione,   inabilitazione, amministrazione di sostegno (certificati da produrre nel   procedimento) viene citata una circolare del Ministero della giustizia del 05 febbraio 2007, si tratta invece di una [nota del medesimo ministero del 01-02-2007](https://www.giustizia.it/giustizia/it/mg_1_8_1.page?contentId=SDC31680): 

Allego tabella MS Excel rivista secondo i criteri proposti
[tabella_39_esenzione_bollo.xlsx](https://github.com/italia/anpr/files/5102452/tabella_39_esenzione_bollo.xlsx)

**Comment by rnapoli1983** [comment]
Buongiorno,

purtroppo su quanto proposto non abbiamo autonomia decisionale.

A livello tecnico è sicuramente fattibile ma necessitiamo dell'approvazione del Ministero specialmente su temi riguardanti materia normativa.

In più le anticipo che sulla tematica delle esenzioni bollo è stata prevista, in accordo col Ministero dell'Interno, anche una revisione dei motivi con  l'Agenzia delle Entrate.

Rimango a disposizione.

Buona giornata.

Cordiali saluti
