### ISSUE TITLE
Richiesta funzionamento aggiornamento posizione elettorale per cittadino cancellato

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2209]
Nel caso in cui un cittadino venga cancellato dall'anagrafe (per emigrazione o per decesso)
 come deve avvenire l'aggiornamento della posizione elettorale?
 E' necessario inviare una comunicazione apposita? In caso affermativo quale?

Grazie mille

**Comment by rvinzani** [comment]
Attualmente ANPR non è collegato al sistema elettorale. La comunicazione dovrà quindi avvenire all'interno del Comune
