### ISSUE TITLE
servizio 1001 - paternità/maternità senza cognome o senza nome

### ISSUE THREAD

**Issue by AGrossiVE** [italia/anpr#221]
Vi abbiamo inviato in data 19/06/2017 una iscrizione per nascita (id 209957) nella quale veniva indicata la paternità con solo il NOME e la maternità con solo il COGNOME.  Nella comunicazione abbiamo opportunamente impostato i flags senza cognome/nome

-<paternita>
-<generalita>
<senzaCognome>1</senzaCognome>
<nome>NOME</nome>
</generalita>
</paternita>
-<maternita>
-<generalita>
<cognome>COGNOME</cognome>
<senzaNome>1</senzaNome>
</generalita>
</maternita>

 a seguito di questa comunicazione abbiamo ricevuto l'errore EN140 - Dati genitori insufficienti

Successivamente abbiamo inviato un'altra comunicazione per nascita con cognome e nome di paternità e maternità completi ed è andata a buon fine (209967).

A questo punto abbiamo inviato una comunicazione di  MUTAZIONE SCHEDA (210000) impostando paternità senza cognome e maternità senza nome. L'operazione è stata correttamente eseguita.

Come mai nel servizio 1001 non siamo riusciti a portare a termine l'operazione sopra descritta?

**Comment by gcarbonin** [comment]
Si tratta di un errore avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
E' possibile riprovare. Attendiamo un riscontro

**Comment by AGrossiVE** [comment]
Buongiorno, abbiamo riprovato in data odierna il caso sopra descritto (1001) e l'ìoperazione è andata a buon fine (id operazione ANPR 235775)
