### ISSUE TITLE
abilitazione ip

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2210]
Buongiorno, 
in riferimento alla issue #2208 
potreste controllare l'IP 46.44.232.16 per il Comune di Aquino

grazie mille
Riccardo

**Comment by cmigliardi** [comment]
certamente

**Comment by cmigliardi** [comment]
l' ip  è presente  -  per il comune di Aquino

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
