### ISSUE TITLE
chiarimento su attribuzione CF per soggetti AIRE

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2211]
Buongiorno, inizialmente per i servizi A001 e A002 richiedevamo sempre l'attribuzione del CF, in seguito a richieste dei Comuni abbiamo tolto l'attribuzione del CF all'iscrizione all'AIRE esclusi i casi di nascita in Italia.

Questa cosa comporta che, un cittadino iscritto all'AIRE, si presenta al consolato di NIZZA per il rilascio della CIE e il documento non è rilasciabile perché non in possesso del CF validato.

A questo punto mi chiedo dovremmo attribuire SEMPRE il CF ai cittadini AIRE?

grazie mille
Riccardo

**Comment by rvinzani** [comment]
E' possibile richiedere l'attribuzione anche richiamando il servizio di mutazione tutti i dati(5008). E' necessario nel caso sia presente un CF calcolato dal gestionale (non validato) eliminarlo e impostare il campo gestioneCF = 1
