### ISSUE TITLE
A006 - trafserimento residenza all'estero cittadino residente comune di caponago

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2212]
COMUNE DI CAPONAGO
REFERENTE : GIUSEPPINA VARISCO

Cittadino residente, trasferimento di residenza all'estero, il ws restitutisce sempre l'errore EF056- La data decorrenza appartenenza alla famiglia  deve essere uguale alla data decorrenza dell'operazione

Non è chiaro dove debbono essere indicate le date richieste.

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-08-26 11:08:20 , idOperazioneANPR 318570830

[RichiestaA006.LOG](https://github.com/italia/anpr/files/5129922/RichiestaA006.LOG)
[EsitoWS_RichiestaA006.LOG](https://github.com/italia/anpr/files/5129923/EsitoWS_RichiestaA006.LOG)

**Comment by amollicone1982** [comment]
la data decorrenza nella testata della richiesta
                       <dataDecorrenza>2020-08-09</dataDecorrenza>
deve essere uguale alla data decorrenza nella sezione legameSoggeto
                       <legameSoggetto>
				<tipoLegame>5</tipoLegame>
				<dataDecorrenza>1980-06-03</dataDecorrenza>
				<codiceLegame>1</codiceLegame>
			</legameSoggetto>
