### ISSUE TITLE
Mutazione residenza - creazione nuova famiglia composta da persone provenienti da famiglie diverse

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2213]
Buon giorno,
implementando la soluzione da voi proposta per un caso particolare di questo problema, esposto nella issue #2197, ci si è posto il dubbio della soluzione da adottare nel caso citato nella issue #486, ossia una situazione in cui due persone, provenienti da famiglie diverse (dello stesso comune), di cui sono l'unico componente, vanno a comporre una nuova famiglia in cui uno dei due è intestatario e l'altro ad esempio convivente.
In questo caso, quale che sia l'ordine di trasferimento dei cittadini, sembra necessario invocare inizialmente il ws 5001 in quanto in ogni caso la modifica di residenza riguarda la famiglia intera; per l'altro cittadino si può poi utilizzare il ws 5005 in quanto trasferimento in una famiglia esistente. In questo modo però non si va a creare una nuova famiglia in anpr come in realtà avviene.
Qual è il modo corretto di operare in questo caso?
Grazie, cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by rvinzani** [comment]
Il procedimento citato è corretto ed in effetti la mutazione 5001 consente il cambio di residenza lasciando al soggetto il numero identificativo famiglia originario. Non vedo particolari limitazioni in tale principio. Inoltre il numero comunale della famiglia può essere modificato.

**Comment by Amucciarelli74** [comment]
Ok, a questo punto vi domando, lo stesso procedimento può essere utilizzato anche nel caso della issue #2197, ossia quando solo uno dei due cittadini è l'unico componente della famiglia di origine e diventa intestatario di quella "nuova"? Dato che si può lasciare alla "nuova" famiglia l'identificativo anpr originario (creando un nuovo numero comunale), in questo modo si eviterebbero le operazioni "fittizie" indicate nella issue per generare una nuova famiglia anpr con un nuovo identificativo.
Grazie, cordiali saluti.

**Comment by rvinzani** [comment]
Sì può utilizzare lo stesso procedimento ma la data origine famiglia rimane quella originaria

**Comment by Amucciarelli74** [comment]
ok, del resto anche da Web app è una informazione che non viene visualizzata, a differenza della data di decorrenza residenza che invece in questo caso viene modificata.
Grazie,
cordiali saluti.
