### ISSUE TITLE
Iscrizione per ricomparsa cittadino croato nato in Bosnia-Erzegovina con codice fiscale Jugoslavia

### ISSUE THREAD

**Issue by SFACCHINELLI** [italia/anpr#2214]
COMUNE DI CALDONAZZO (TN)
non riesco ad iscrivere per ricomparsa un cittadino croato nato in Bosnia-Erzegovina con codice fiscale Jugoslavia.
Si chiede come intervenire per la modifica del codice fiscale con lo stato di nascita Bosnia-Erzegovina, codice belfiore Z153.
Non riusciamo a passare senza validazione la pratica con il codice fiscale Z153 che consentirebbe poi di intervenire nella webapp per risolvere il doppio codice fiscale.
Per cortesia contattatemi al nr. 0461 723 123 int 2 (dalle 08.30 alle 12.30) o mail ufficio.demografico@comune.caldonazzo.tn.it.
Grazie in anticipo, saluti
Sara Facchinelli

**Comment by rvinzani** [comment]
Come da contatto telefonico le confermo che è necessario iscrivere il cittadino indicando come stato di nascita iugoslavia (come presente in Agenzia Entrate). Successivamente effettuerà una mutazione tutti i dati modificando il luogo di nascita. Questo determinerà l'attribuzione di un nuovo CF
