### ISSUE TITLE
Errore in fase di iscrizione

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2215]
Villa Cortese 015248 - Produzione

Buongiorno,
sto procedendo all'iscrizione di un cittadino da un altro comune subentrato.
Detto cittadino è stato già mio residente in ANPR, ma cancellato da me per doppia iscrizione.

Ora quando effettuo la mutazione mi da errore EF054 - EN527 - ES101

L'operazione ANPR è la 322729056

Grazie

**Comment by rvinzani** [comment]
Se deve trasferire la residenza del soggetto da Legnano a Volla Cortese deve indicare come identificativo ANPR della persona il 47580768. Nella richiesta invece è stato indicato l'identificativo 38137103, che si riferisce al soggetto che avete cancellato precedentemente voi per doppia iscrizione.
