### ISSUE TITLE
ISCRIZIONE SOGGETTO CANCELLATO ALTRO COMUNE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2216]
Chiedo cortesemente la procedura per iscrivere soggetto cancellato altro comune
 idOperazioneANPR 323157701 (Codice: EN527)
Filippo Asaro
0923993382
asaro.filippo@comune.marsala.tp.it

**Comment by rvinzani** [comment]
Deve essere effettuata un'iscrizione per altri motivi inserendo l'identificativo ANPR

**Comment by filippo1961** [comment]
Purtroppo non va a buon fine..se può ricontattarmi
0923993382
Grazie

**Comment by filippo1961** [comment]
Grazie tutto risolto
