### ISSUE TITLE
[webapp] Scarico comune per motivata richiesta e convivenze

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2217]
Buongiorno
Sto controllando per la prima volta questo scarico in ambiente di test.
Se interpreto bene si tratta di una 3002 di tutti i residenti attivi.
Quindi la fotografia della situazione attuale, da cui posso determinare le famiglie presenti nel comune, ma non avere certezza se esistono convivenze attive in ANPR su quel comune (senza residenti attualmente).
Si possono ricavare in altro modo da webapp, l'elenco delle convivenze attualmente esistenti in ANPR?

**Comment by mttfranci** [comment]
E’ previsto di restituire i dati dei soli soggetto, quindi i dati di famiglie e convivenze vengono restituiti solo se includono residenti.
Eventualmente è possibile iscrivere nuovamente una convivenza in un momento successivo, se e quando avrà nuovamente residenti.

**Comment by MarcoMigliori** [comment]
Ok, resterà quindi la vecchia convivenza aperta, e ne verrà aperta un'altra (se necessario)
