### ISSUE TITLE
[WEB APP] Famiglia/Convivenza - Il campo Famiglia/Convivenza è obbligatorio

### ISSUE THREAD

**Issue by jorpis** [italia/anpr#2218]
Buongiorno, tramite la suite di test stò tentando di iscrivere un cittadino con il servizio "ISCRIZIONE PER NASCITA" volevo registrare un'utenza, per poi sviluppare un servizio di emissione certificati. Non riesco a terminare la registrazione, attualmente sono arrivato alla scheda di Famiglia/convivenza , dove ho la maschera totalmente disabilitata e continuo ad avere il messaggio 
Famiglia/Convivenza - Il campo Famiglia/Convivenza è obbligatorio.
Sarebbe possibile caricare un cittadino random in modo tale da poter poi svilupparci i servizi di richiesta certificati che vogliamo elaborare ?

Giorgio

**Comment by jorpis** [comment]
ID dell'operazione sospesa 42001542

**Comment by rvinzani** [comment]
L'iscrizione per nascita presuppone che il bambino debba esser necessariamente associato ad una famiglia/convivenza esistente in ANPR tramite la scelta di uno dei componenti della stessa. Per caricare un cittadino per fare dei test sui certificati potete utilizzare l'iscrizione per altri motivi che prevede anche l'apertura contestuale di una nuova famiglia. Altrimenti per poter utilizzare il servizio di iscrizione per nascita dovete necessariamente caricare un membro della famiglia e successivamente il bambino associandolo alla famiglia creata in precedenza.

**Comment by jorpis** [comment]
Salve, tentando l'iscrizione per altri motivi ora ottengo questo errore:

La richiesta non risulta valida secondo i nuovi XSD [Campo:'idSchedaSoggettoComuneIstat',tipo:'tipoCodiceIstatComune'.] (Codice: EN489)
La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-07 09:30:00 , Token 1599463800053 (Codice: EN527)

**Comment by rvinzani** [comment]
Si tratta probabilmente dell'assenza di un campo obbligatorio o dell'errato formalismo di un campo. Per questo tipo di errori deve fare riferimento alle specifiche xsd

**Comment by jorpis** [comment]
Mi sembra strano, i campi obbligatori mi vengono puntualmente richiesti dall'interfaccia web.
Come posso dall'xsd sapere a quale campo (dell'interfaccia web di test) fa riferimento l'errore ? Sinceramente non ho capito.

Stò provando un ulteriore inserimento ponendo attenzione a valorizzare correttamente tutti i campi, ho specificato nelle generalità che sono un cittadino celibe/nubile, e ora sono bloccato in questo modo:

Dati del coniuge - Compilare solo uno dei seguenti campi cognome/senza cognome
Dati del coniuge - Compilare solo uno dei seguenti campi nome/senza nome
Dati del coniuge - Il campo Sesso è obbligatorio

**Comment by rvinzani** [comment]
Mi scusi non avevo capito che stesse operando dall'interfaccia web di ANPR. Se il set di informazioni (come quelle del matrimonio) non devono essere acquisite, non deve entrare nella pagina relativa e dare conferma ma semplicemente riempire le sezioni indicate a sinistra con un asterisco rosso

**Comment by jorpis** [comment]
Le assicuro che non ci entro volontariamente, è la procedura guidata, ora ho provato a saltare queste schede cliccando su Completa Operazione, e in effetti non mi vengono più richiesti, ma mi viene segnalato questo errore : 
Operazione non effettuabile (Codice: AEE96)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-07 11:10:26 , idOperazioneANPR 2553188 (Codice: EN527)

**Comment by jorpis** [comment]
La ringrazio per l'aiuto

**Comment by rvinzani** [comment]
Di nulla. :)

**Comment by jorpis** [comment]
si scusi, la ringrazio per l'aiuto, ma ho questo problema (come scritto sopra)

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-07 11:10:26 , idOperazioneANPR 2553188 (Codice: EN527)

**Comment by jorpis** [comment]
Operazione non effettuabile (Codice: AEE96)

**Comment by rvinzani** [comment]
In ambiente di test per l'iscrizione di un cittadino per altri motivi è necessario o richiedere l'attribuzione di un CF o iscrivere un cittadino senza la validazione del CF. Questo perchè ANPR di test è agganciato ad un archivio di agenzia entrate che non contiene i CF reali ed inserendo un CF esistente viene tornato un errore perchè non trovato
