### ISSUE TITLE
[WEB APP] Iscrizione manuale

### ISSUE THREAD

**Issue by jorpis** [italia/anpr#2219]
Buongiorno, mi ricollego al ticket #2218, chiuso credo per errore. Riassumendo registrando un cittadino dall'interfaccia web della suite di test abbiamo questo errore:

Operazione, e in effetti non mi vengono più richiesti, ma mi viene segnalato questo errore :
Operazione non effettuabile (Codice: AEE96)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-07 11:10:26 , idOperazioneANPR 2553188 (Codice: EN527)

**Comment by rvinzani** [comment]
Come le avevo risposto nella issue #2218 : In ambiente di test per l'iscrizione di un cittadino per altri motivi è necessario o richiedere l'attribuzione di un CF o iscrivere un cittadino senza la validazione del CF. Questo perchè ANPR di test è agganciato ad un archivio di agenzia entrate che non contiene i CF reali ed inserendo un CF esistente viene tornato un errore perchè non trovato
