### ISSUE TITLE
ws [1002] - Integrazione dei ws ANPR con AE

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#222]
Buon giorno,
continuiamo ad avere problemi con i test di integrazione dei ws di ANPR con i servizi cooperativi di AE in ambiente di test. Come già riscontrato nelle problematiche segnalate nell'issue #186 per quello che riguarda il ws 1001 (iscrizioni per nascita), anche per l'iscrizione in ANPR di individui provenienti da comuni non subentrati otteniamo degli errori, se richiediamo operazioni di verifica sul codice fiscale. In particolare, nell'iscrizione per immigrazione da comune non subentrato di un individuo non presente nell'ambiente di test ANPR (id operazione comune 2067), abbiamo indicato il codice fiscale nelle generalità ed assegnato al campo gestioneCF il valore 0, con cui ANPR dovrebbe richiedere ad AE una verifica di congruenza del codice fiscale (casi di iscrizioni di soggetti già in possesso di un CF). Otteniamo però nella response un errore con codice AEE96 (Operazione non effettuabile). L'unico modo per riuscire a iscrivere un individuo, come anche nelle iscrizioni per nascita, è quello di assegnare al campo gestioneCF il valore 3 (id operazione comune 2069). In questo modo l'operazione va a buon fine, anche se con il warning EN141 (Soggetto non validato) e difatti il soggetto risulta non validato.
C'è un errore nelle nostre request? abbiamo interpretato male le specifiche? o dipende dall'ambiente di test AE?

Il test è stato effettuato in data 23/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
Gent.le Sig. Mucciarelli,
in ambiente di test di Agenzia delle Entrate sono presenti solo alcuni codici fiscali caricati a partire dall'ambiente di produzione. E' quindi improbabile che possa effettuare la validazione di un codice fiscale seppure realmente esistente. E' necessario quindi richiedere l'attribuzione in fase di iscrizione per inserirlo nell'ambiente di test. Nel caso però da lei segnalato l'errore AEE96 era dovuto ad un temporaneo malfunzionamento poiché il messaggio corretto sarebbe stato: soggetto non presente in AE. La prego quindi di riprovare appena le sia possibile. Saluti
Roberta Vinzani

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo effettuato un nuovo test di iscrizione di un individuo proveniente da comune non subentrato, utilizzando il ws 1002; seguendo le vostre indicazioni, abbiamo richiesto l'attribuzione del codice fiscale (gestioneCF = 1, codice fiscale non indicato), ma otteniamo ugualmente l'errore AEE96. L'id operazione comune è 2089. 
Abbiamo inoltre riprovato a chiedere l'attribuzione del codice fiscale, con le medesime assegnazioni, effettuando una iscrizione per nascita con il ws 1001, ma otteniamo lo stesso errore AEE96. L'id operazione comune è 2085.

Il test è stato effettuato in data 26/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
E' necessario indicare nella residenza la descrizione del toponimo. Questo è un dato necessario per la richiesta di attribuzione del codice fiscale.  Implementeremo un controllo in ANPR per evitare l'errore.

**Comment by Amucciarelli74** [comment]
Ok, 
l'obbligatorietà in realtà è indicata nel file excel delle specifiche "toponimo.xlsx", ma non nella sezione 'toponimo' della 'Richiesta1002' dell'xsd "1000iscrizione.xsd", ragion per cui le varie request sono risultate sempre valide, e non è stato possibile individuare la ragione per cui le operazioni non andassero a buon fine.
Seguendo l'indicazione di indicare la descrizione del toponimo, abbiamo effettuato con successo l'iscrizione, mediante il ws 1002, di un cittadino non residente, proveniente da comune non subentrato, richiedendo l'attribuzione del codice fiscale. 
Di seguito, supponendo che l'errore nella registrazione per nascita fosse generato dalla medesima situazione, abbiamo effettuato l'iscrizione per nascita di un nuovo individuo, chiedendo l'attribuzione del codice fiscale, mediante il ws 1001, con l'accorgimento che la famiglia di destinazione avesse indicata la descrizione del toponimo, e in questo modo l'operazione è andata a buon fine. 
Infine, abbiamo effettuato l'iscrizione, mediante il ws 1002, di un cittadino non residente, proveniente da comune non subentrato (precedentemente inserito e poi cancellato, quindi con codice fiscale presente nell'archivio di test di AE), indicando il codice fiscale e richiedendo ad AE una verifica di congruenza, ed anche quest'ultima operazione è andata a buon fine.
Chiediamo conferma che in quest'ultimo caso, la corretta valorizzazione di gestioneCF sia 0, indicando il codice fiscale di cui si richiede la verifica di congruenza.

Il test è stato effettuato in data 27/06/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
Confermo che la valorizzazione a 0 (o nessuna valorizzazione) di gestioneCF sia corretta in caso di verifica congruenza dei dati anagrafici e codice fiscale. In realtà il dato di controllo gestioneCF  non deve essere valorizzato ed inserito nelle richieste che prevedano il trattamento dei dati anagrafici (in iscrizione o mutazione degli stessi) a meno che non si voglia richiedere l'attribuzione di un codice fiscale o ci sia qualche motivo ostativo che non consenta la validazione da parte di Agenzia delle entrate. Quest'ultima eventualità è però da utilizzare come estrema ratio e da evitare laddove sia possibile
