### ISSUE TITLE
Gestione postazione ANPR "virtuale"

### ISSUE THREAD

**Issue by antonioluberto** [italia/anpr#2220]
Buongiorno,
di seguito vi riportiamo una richiesta di chiarimento ai fini dell’erogazione di alcuni servizi ai cittadini dipendenti dalla banca data ANPR.

Premessa: si fa qui riferimento alla documentazione MI-14-AN-01 SPECIFICHE DI INTERFACCIA WS.pdf, dove si identifica che l’accesso ad ANPR, attraverso i Web Services, debba avvenire riportando sempre nella richiesta telematica, il dato corrispondente al certificato identificativo della postazione, memorizzato all’interno della stessa, emesso dalla Certification Authority. Nella issue https://github.com/italia/anpr/issues/35, con un commento datato 4 gennaio 2018, si indica come sia in carico al Comune l’identificazione di qualsiasi postazione dalla quale venga effettuato accesso ad ANPR; tale postazione viene indicata come interna al proprio dominio informatico e che può eventualmente anche essere di tipo _virtuale_. 

Ad ulteriore chiarimento ed a fugare qualsiasi dubbio, proprio ai fini di poter consentire l’erogazione agli Enti di servizi ANPR ai cittadini, la domanda è così articolata:
a)	una postazione virtuale (VM) di proprietà dell’ente, che può, per esempio, essere acquistata presso uno dei provider di servizi IaaS e PaaS di mercato (esempio: Microsoft, Aruba, ecc.), 
b)	della quale VM l’ente ne gestisca l’operativa in esclusiva sia ai fini del controllo che dell’amministrazione, 
c)	su cui l’ente installa il certificato di postazione di un proprio operatore comunale, 
d)	VM su cui eventualmente i fornitori esterni possano operare solamente in forma assistita e presidiata dall’ente stesso (teleassistenza)

Tutto ciò indicato, fa sì che tale postazione virtuale sia idonea allo scopo di accedere, tramite il gateway ufficiale dell’ente, ai servizi esposti da ANPR per l’erogazione dei servizi di certificazione online?

L’odierna necessità di chiarimento viene scaturita dal fatto che sono state pubblicizzare diverse soluzioni presenti sul mercato e la questione della collocazione fisica o virtuale della postazione con a bordo il certificato a nostro avviso poteva essere oggetto di discussione nell’interpretazione del termine “dominio” nelle varie connotazioni di dominio inteso come controllo, dominio telematico, dominio del perimetro fisico dell’ente.

Ringraziando sin d’ora per le indicazioni che vorrete fornirci, porgiamo cordiali saluti.

**Comment by antonioluberto** [comment]
[MI-14-AN-01 SPECIFICHE DI INTERFACCIA WS.pdf](https://github.com/italia/anpr/files/5188220/MI-14-AN-01.SPECIFICHE.DI.INTERFACCIA.WS.pdf)

**Comment by gife67** [comment]
Buongiorno,
l’accesso all’ANPR è consentito solo ed esclusivamente da postazioni che risiedono nell’ambito del Comune, ma più che altro cosa fondamentale esclusivamente da Operatori Comunali con la qualifica di Ufficiali di Anagrafe. Quello che sta indicando lei è un accesso non consentito in quanto non tanto per un problema di utilizzo del certificato di postazione ma in quanto si sta utilizzando un utenza di un operatore comunale con il profilo autorizzativo che ne permette l’emissione di certificati, senza che sia lui ad effettuare realmente le operazioni. La cornice di sicurezza prevista per l’accesso ai servizi prevede una SAML Assertion in cui l’IDP del Comune afferma in modo inconfutabile che ha autenticato l’operatore che sta effettuando le operazioni anagrafiche. Chi e tramite quale componente software opererebbe sulla postazione virtuale? Sono sicuro che comprenda che questa modalità presenta delle criticità di sicurezza ed apre la strada ad accessi ad ANPR che sono fuori il controllo anche del Comune stesso, il quale è tenuto a tenere un registro completo delle sue postazioni e di chi ci opera giornalmente.
Cordiali saluti

**Comment by gife67** [comment]
Buongiorno,
provvedo a chiudere questa issue, nel caso ci fossero altri quesiti a riguardo potete aprire una nuova issue collegata a questa.
Cordiali saluti
Giuseppe Ferraro
