### ISSUE TITLE
[3002] Consultazione Soggetto: doppio tag "Residenza" - collegato a #2107

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2221]
Buongiorno, come per issue #2107 consultando un cittadino ritornano 2 tag residenza

idOperazioneANPR 326937617
comune di SAN FELICE CIRCEO - produzione

è la stessa casistica non risolta oppure è una questione diversa?

grazie mille
Riccardo

**Comment by ncapozzi** [comment]
Buonasera,
potete riprovare per favore?

**Comment by ricantonelli** [comment]
Buongiorno abbiamo provato tutto ok.
grazie
