### ISSUE TITLE
Matrimonio celebrato prima dell'iscrizione in anagrafe

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2222]
Villa Cortese 015218 - Produzione

Buongiorno,
abbiamo iscritto in anagrafe una cittadina il 25.08.2020 con stato civile nubile.
Oggi ci arriva da trascrivere il matrimonio dal comune di celebrazione in quanto lo sposo era già nostro residente ma il matrimonio è stato celebrato il 30.07.2020.
Quando cerco di passare la variazione di stato civile mi da errore.
1 Errore Anpr Cod: EN389 - La data decorrenza 30-07-2020 dell'operazione non puo' essere inferiore alla data decorrenza 25-08-2020 dell'ultima operazione effettuata sui dati relativi a prima iscrizione nel comune corrente
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-08 17:27:41 , idOperazioneANPR 327325690

Grazie

**Comment by frmariani** [comment]
non è possibile acquisire un'informazione su un cittadino con una data di decorrenza minore della data d'iscrizione nel comune; 
le prospetto due possibili soluzioni:
1) annulla la mutazione di residenza ed il comune di provenienza effettua la modifica del matrimonio e dello stato civile sulla cittadina alla data corretta; successivamente effettuerete di nuovo la mutazione di residenza al 25/08/2020;
2) effettuate un'operazione di "Mutazione tutti i dati" con data di decorrenza dell'operazione 25/08/2020 (data di iscrizione della cittadina nel vostro comune) acquisendo contestualmente i dati del matrimonio e dello stato civile: la data dell'evento all'interno della sezione matrimonio sarà  30/07/2020.
Nel caso fosse necessario, può inviarmi un contatto telefonico dove raggiungerla al seguente indirizzo
frmariani@sogei.it

**Comment by cvignati** [comment]
Buongiorno,
ho optato per la seconda soluzione ed è tutto a posto.

Grazie mille
