### ISSUE TITLE
[4005] PROD - incongruenza ricezione notifiche per un soggetto

### ISSUE THREAD

**Issue by SilviaRivi** [italia/anpr#2223]
Ambiente di Produzione.

E' stata effettuata la richiesta delle notifiche N010 e N015 
tramite WS 4005, ma su un soggetto abbiamo riscontrato un anomalia  
in quanto è arrivata una doppia N015.

Sono arrivate 4 notifiche (2 N010 e 2 N015) però tramite WebApp 
il soggetto risulta iscritto nel comune che ha generato le notifiche, 
però essendo arrivata 2 volte la N015 ovviamente per noi risulta Attivo.

Ecco le notifiche arrivate
IdNotifica=**325911990**  Data Decorrenza =07-09-2020 Tipo  Notifica=**N010**
IdNotifica=**326258685**  Data Decorrenza=07-09-2020 Tipo   Notifica=**N015**
IdNotifica= **326266946**  Data Decorrenza=07-09-2020 Tipo  Notifica=**N015**
IdNotifica=**326299840**  Data Decorrenza=03-09-2020 Tipo   Notifica=**N010**

Come mai è stata generata la notifica N015 2 volte?

In attesa di riscontro
Saluti

**Comment by lorbia** [comment]
La N015 è una  “NOTIFICA RIPRISTINO POSIZIONE ANAGRAFICA” che nel caso citato segue una N010 "NOTIFICA MUTAZIONE DI RESIDENZA".
Le due N015 non sono riferite allo stesso evento anagrafico per cui non si tratta della stessa notifica generata 2 volte ma di due notifiche dello stesso tipo generate in sequenza e riferite a due eventi differenti.
La sequenza delle 4 notifiche segnalate è:
              operazione_anagrafica                                notifica_generata
1)	5005 (ID=325906315)                                    N010 (ID=325911990)
2)	5012 (ID=326253735)                                    N015 (ID=326258685)
3)	5012 (ID=326263995)                                    N015 (ID=326266946)
4)	5005 (ID=326296639)                                    N010 (ID=326299840)
Il 5012 del punto 2 si riferisce al 5005 del punto 1 ma quello del punto 3 si riferisce al 5005 ID=326263250.
Riguardo all'invio delle notifiche segnalo che il comune non risulta avere un endpoint attivo.
Saluti
LB

**Comment by lorbia** [comment]
In caso di altri problemi di questo tipo aprite una nuova issue collegata.
Grazie, saluti.
LB
