### ISSUE TITLE
Duplice iscrizione nel comune di VALSAMOGGIA e nel comune di NAPOLI

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2225]
La persona con Num. Ind. ANPR  27931076 é stata iscritta nell’APR/ANPR del comune di Valsamoggia il 17/07/2015 per ricomparsa, in quanto era stata cancellata dal comune di Rolo in data 24/04/2013 per irreperibilità al censimento. In realtà lo stesso era iscritto dal 22/05/2014 nell’APR del comune di Napoli (non conosco il motivo di iscrizione), il cui subentro in ANPR il 21/09/2019 ha generato la duplicazione. 
Visti quindi i dati contenuti in ANPR e nell’allegato all’apr4 del comune di Rolo, mi sembra che le vicende anagraﬁche  della persona di che trattasi debbano risultare nel seguente modo 
12/06/2010: iscritto nell’APR del Comune di Rolo per immigrazione dalla Repubblica Popolare Cinese 
24/04/2013: cancellato dall’APR del Comune di Rolo per irreperibilità al censimento 
22/05/2014: iscritto nell’APR del Comune di Napoli per ricomparsa dal Comune di Rolo
17/07/2015: cancellato dall’APR/ANPR del Comune di Napoli per doppia iscrizione con destinazione Comune di Valsamoggia 17/07/2015: iscrizione nell’APR/ANPR del Comune di Valsamoggia per immigrazione dal Comune di Napoli 
In data 11/03/2020 ho inviato una comunicazione in tal senso ai comuni coinvolti ma, a tutt’oggi, la duplicazione non risulta risolta. 
Vi chiederei la cortesia di contattare il colleghi competenti del Comune di Napoli in quanto la persona ha necessità di ottenere il rilascio di certificazione

**Comment by frmariani** [comment]
il Comune di Napoli è stato contattato e la duplicazione risolta.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
