### ISSUE TITLE
[webapp] risoluzione disallineamenti, collegamento cf con 3 campi variati

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2226]
Buongiorno, ci capita un caso simile alla #2166 .

nel nostro caso abbiamo individuato la presenza in AE di un codice fiscale con le nuove generalità del cittadino id 43654241.
Quindi apriamo la risoluzione disallineamenti, per collegare il codice fiscale ANPR (validato) al codice AE.

Nella videata della risoluzione appare nella colonna di sinistra il nuovo codice fiscale ******92T31Z329R (le prime 6 lettere sono uguali al cf di  ANPR) presente in AE, non marcato ANPR

Nella colonna di destra il vecchio codice fiscale presente in AE+ANPR: validato AE.

Premiamo "collega" e poi conferma il 10 settembre alle ore 15:10 grossomodo.
Otteniamo errore, Esito AE: Variazione non consentita per superamento numero campi variati (Codice 93)

i campi diversi sono 3:
- cognome
- nome
- data di nascita

Però nella #2166 era indicata questa strada. Potete verificare?

**Comment by frmariani** [comment]
sicuramente nella issue citata mi sono espressa male e chiedo scusa;
In questi particolari casi, anche per il collegamento tra i CF,  è necessario un intervento da parte della Direzione Centrale di Agenzia delle Entrate, pertanto dovrete seguire lo stesso iter descritto nella issue #2166

**Comment by MarcoMigliori** [comment]
Ok, informato il Comune
