### ISSUE TITLE
inserimento stato estero nascita ANGUILLA

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2227]
Buongiorno,
dobbiamo inserire comune e stato nascita di un coniuge. Lo stato è ANGUILLA, comune Anguilla
Lo stato è presente sulla tabella di decodifica (CODISO3166_1_ALPHA3 = AIA; COD MAE e CODMIN = 502;CODICE CATASTALE Z529) ma non compare sulla tabella di Mutazione tutti i dati; dovrebbe essere ricompreso fra Angola e Antigua ma non viene visualizzato. Trattandosi di dipendenza della Gran Bretagna, va gestito come NON ATTRIBUILE?
Grazie

Anna Maria AIMONE
UPI - TORINO

**Comment by ncapozzi** [comment]
Buonasera,

ANGUILLA é un TERRITORIO e non uno strano sovrano pertanto non può essere indicato in ANPR come territorio di nascita (NASCITA = N nella tabella da voi citata). Il motivo è che lo stato estero sovrano su quel territorio è quello che rilascia eventualmente il passaporto.

Il problema in generale si risolve indicando come stato di nascita lo stato sovrano (es. REGNO UNITO) e come località di nascita il territorio (es. ANGUILLA). 

Se però il cittadino ha già un CF attribuito da Agenzia delle Entrate per Z529 - ANGUILLA, allora potete anche procedere come da voi stessi suggerito: 999 -ANGUILLA.

N. Capozzi

**Comment by ncapozzi** [comment]
Buonasera,

ANGUILLA é un TERRITORIO e non uno strano sovrano pertanto non può essere indicato in ANPR come territorio di nascita (NASCITA = N nella tabella da voi citata). Il motivo è che lo stato estero sovrano su quel territorio è quello che rilascia eventualmente il passaporto.

Il problema in generale si risolve indicando come stato di nascita lo stato sovrano (es. REGNO UNITO) e come località di nascita il territorio (es. ANGUILLA). 

Se però il cittadino ha già un CF attribuito da Agenzia delle Entrate per Z529 - ANGUILLA, allora potete anche procedere come da voi stessi suggerito: 999 -ANGUILLA.

N. Capozzi

**Comment by ncapozzi** [comment]
Buonasera,

ANGUILLA é un TERRITORIO e non uno strano sovrano pertanto non può essere indicato in ANPR come territorio di nascita (NASCITA = N nella tabella da voi citata). Il motivo è che lo stato estero sovrano su quel territorio è quello che rilascia eventualmente il passaporto.

Il problema in generale si risolve indicando come stato di nascita lo stato sovrano (es. REGNO UNITO) e come località di nascita il territorio (es. ANGUILLA). 

Se però il cittadino ha già un CF attribuito da Agenzia delle Entrate per Z529 - ANGUILLA, allora potete anche procedere come da voi stessi suggerito: 999 -ANGUILLA.

N. Capozzi
