### ISSUE TITLE
Gestione pratiche in contemporanea

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#2228]
Buonasera,
vi scrivo in merito ad una situazione che ci è capitato di gestire su un nostro cliente, in fase di due pratiche che si sono "accavallate" tra loro nello stesso periodo.
Provo a riassumere: nel comune A esiste una famiglia composta da 4 componenti.
Viene aperta una variazione d'indirizzo nello stesso comune per scissione di famiglia, ed in questa variazione 2 componenti della famiglia richiedono il cambio indirizzo.
La pratica viene aperta e inviata senza problemi ad ANPR, e viene lasciata aperta per il periodo relativo alla fase di accertamento.
In questa fase di accertamento, i due componenti che erano rimasti nella famiglia originale fanno una richiesta di residenza nel comune B.
Noi riusciamo ad istituire la pratica ma al momento dell'invio in ANPR, abbiamo questi errori (questo non è il caso reale, abbiamo riprodotto la situazione su ambienti di test):

EN531 : Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune CASTELLEONE (CR) con numero pratica ANPR: 29005663
EN527 : Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-10 12:38:59 , idOperazioneANPR 29960496

Il cliente, per permettere al comune B di istituire la pratica di iscrizione, ha velocizzato i tempi di accertamento della variazione d'indirizzo e, una volta resa definitiva, è stato possibile per il comune B proseguire con l'iter di iscrizione.

Volevo chiedere se la soluzione che è stata applicata dal nostro cliente è l'unica percorribile o avete altri suggerimenti in merito.

Grazie
Marco Sala
Pa Digitale Spa

**Comment by frmariani** [comment]
come descritto nell'errore, esiste un procedimento amministrativo ancora aperto sui soggetti intestatari dell'operazione;
da quello che ho potuto verificare dal test effettuato, anche per l'operazione di modifica delle relazioni di parentela successiva al cambio di residenza dei primi due soggetti, è stato utilizzato il procedimento amministrativo numero 29005663, pertanto finchè non viene chiuso, nessuna modifica della residenza è possibile sui soggetti "marcati" dal procedimento.
Se il procedimento amministrativo non fosse stato utilizzato nella modifica delle relazioni di parentela (idoperazioneAnpr 29960460), il cambio di residenza nel comune B dei due soggetti che erano rimasti nella famiglia, sarebbe stato effettuato senza problemi.
Dovreste verificare se la situazione riprodotta sia identica a quella reale; in caso contrario, gentilmente indicate l'identificativo ANPR della famiglia o di uno dei soggetti.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
