### ISSUE TITLE
Duplice iscrizione nel comune di VALSAMOGGIA e nel comune di NAPOLI (#2225)

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2229]
Vorrei solo precisare che la decorrenza della cancellazione per duplice iscrizione da parte del comune di Napoli del soggetto con identificativo ANPR 69632307 dovrebbe risultare 17/07/2015 e non 17/01/2015.
Dalla stessa data del 17/07/2015 risulta iscritto nel comune di Valsamoggia per immigrazione dal Comune di Napoli.

**Comment by frmariani** [comment]
siamo in contatto con il comune di Napoli per correggere la data dei cancellazione. grazie per la segnalazione
