### ISSUE TITLE
[5008] Validazione Codice Fiscale successiva all'iscrizione

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#223]
Corbetta, Ambiente di produzione.

Buongiorno, dopo il subentro è stato iscritta in anagrafe una persona (codice fiscale RIUGPP84P10E514H) inserendo come modalità di trasmissione 'senza validazione codice fiscale' e l'evento è andato a buon fine. Successivamente dopo aver eseguito alcune verifiche è stata eseguita la validazione del codice fiscale tramite il ws 5008 che ha funzionato correttamente ed infatti la persona risulta con il codice fiscale validato dall'AE, però controllando i dati dello stesso su Punto Fisco ci siamo resi conto che la persona in oggetto non ha cambiato la residenza, quindi risulta per AE ancora residente in altro comune anche se iscritto in ANPR nel comune di Corbetta. Le operazioni sono sempre andate a buon fine, come si è realizzato tale disallineamento e come possiamo porvi rimedio?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Il problema dipende da come attualmente funzionano i servizi cooperativi dell’Agenzia delle Entrate che accettano le variazioni solo se le posizioni sono validate da AE al momento del subentro o dell’iscrizione. Questa modalità è in corso di revisione da parte dell’Agenzia.
Per recuperare la situazione, daremo indicazioni.

**Comment by LucaBonini64** [comment]
Quindi (sempre Comune di Corbetta) se un cittadino ha dei dati anagrafici differenti con l'agenzia delle Entrate (GIAN CARLO e GIANCARLO) ed attualmente non riescono ad iscriverlo per tale differenza, il comune può procedere con l'iscrizione senza validazione e sanare successivamente tale situazione confermando il dato anagrafico, è corretto?

**Comment by gcarbonin** [comment]
Premesso che occorre in ogni caso una verifica per controllare quali siano i dati corretti (quelli di iscrizione o quelli dell'Agenzia), assumendo che quelli validi siano quelli di iscrizione, ci sono due modi per procedere:

- si effettua l'iscrizione con i dati dell'Agenzia senza specificare nulla nel campo gestioneCf e  successivamente si esegue una mutazione con i dati corretti; con il primo passaggio AE marca il soggetto ANPR e con il secondo rettifica i propri dati (con eventuale attribuzione di un nuovo CF);
- si effettua l'iscrizione con gestioneCF = 3 e successivamente con la funzione di Risoluzione dei disallineamenti della WA (area Utilità e notifiche) si confermano i dati del comune. 

Per verificare se possiamo recuperare il primo caso che avete segnalato in questo modo, occorre che qualcuno del comune ci contatti.
