### ISSUE TITLE
controllo su ip Comune

### ISSUE THREAD

**Issue by ricantonelli** [italia/anpr#2230]
Buongiorno vorrei sapere se i seguenti ip sono correttamente censiti per il Comune di Ausonia

 88.49.244.169
 88.49.244.168

 Grazie
Riccardo

**Comment by cmigliardi** [comment]
chiedo verifica e le faccio sapere -

**Comment by cmigliardi** [comment]
dai controlli risulta  abilitato   solo il .168  - mi dica se le occorre anche il .169 - grazie

**Comment by ricantonelli** [comment]
Si grazie servirebbe anche il .169.
comunque tutti e due controllando in WebApp risultano con *, qual'è la discriminante?
grazie mille

**Comment by cmigliardi** [comment]
ok allora inoltro la richiesta di abilitazione anche per    IP  .169

**Comment by cmigliardi** [comment]
l' ip è stato abilitato -

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
