### ISSUE TITLE
Inscrizione APR di persona in tutela

### ISSUE THREAD

**Issue by ritabortolan** [italia/anpr#2231]
Buongiorno, 

Sono Rita del Comune di Chiampo.
Un cittadino proveniente da un comune subentrato mi ha chiesto la residenza nel mio comune.
La persona però è sotto tutela per tanto non dovrebbe essere visibile in ANPR.

Aggiungo che la persona è sotto tutela dei servizi sociali dopo il subentro del comune di attuale competenza.
Come posso agire in questo caso?

Saluti, 

Rita Bortolan 
Comune di Chiampo (VI)

**Comment by rvinzani** [comment]
Come comunicato telefonicamente è possibile attribuire al soggetto la non certificabilità in modo che altri comuni non possano emettere certificati
