### ISSUE TITLE
errata residenza all'Agenzia delle Entrate di nuovo residente

### ISSUE THREAD

**Issue by leopaul76** [italia/anpr#2233]
Buongiorno,
in data 09-09-2020 con operazione id anpr 328037379 completata positivamente si provvedeva alla mutazione di residenza dal Comune di Palermo del soggetto avente id 76056560.
Il soggetto, tuttavia, risulta ad oggi avere per l'agenzia delle entrate residenza nel Comune di Monreale (non ancora subentrato) che interpellato dallo scrivente conferma di non avere nella propria anagrafe il soggetto id 76056560.
In che modo posso allineare/correggere il dato errato della residenza presente all'ADE?
Resto in attesa di Vs. riscontro.
Grazie e cordiali saluti.
Comune di Valenza
per info 0131949210

**Comment by frmariani** [comment]
il soggetto con idanpr 76056560 non risulta marcato, pertanto l' Agenzia delle Entrate non ha recepito il cambio di residenza.

Per risolvere il problema, basta effettuare un allineamento dei dati con la funzione Risoluzione Disallineamenti AE presente nella web app di ANPR

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
