### ISSUE TITLE
controllo Indirizzi ip Comune

### ISSUE THREAD

**Issue by SilviaRivi** [italia/anpr#2234]
Buongiorno vorrei sapere se i seguenti Indirizzi ip sono correttamente censiti per il Comune di Corridonia

78.134.63.111
185.53.192.161
185.53.192.172
212.124.191.230
83.211.10.79

Perché abbiamo provato ad effettuare un test ma la risposta è 
.. fallito: Connessione scaduta.

In attesa di risposta

Grazie
Silvia Rivi

**Comment by cmigliardi** [comment]
chiedo verifica e le faccio sapere -

**Comment by cmigliardi** [comment]
gli ip non sono abilitati . chiedo li avete inseriti in ambiente di produzione - area amministrazione della web app   nella sezione informazioni aggiuntive ?    fatemi sapere  -  intanto  mi predispongo per chiedere le abilitazioni

**Comment by cmigliardi** [comment]
le chiedo inoltre come mai 5 IP  per un comune  di 15.000  abitanti ?

**Comment by SilviaRivi** [comment]
Si gli ip sono stati inseriti in ambiente di produzione nella web app

**Comment by cmigliardi** [comment]
le chiedo inoltre come mai 5 IP per un comune di 15.000 abitanti ? grazie

**Comment by SilviaRivi** [comment]
Per quello che riguarda gli indirizzi ip non hanno una connessione molto stabile adsl quindi hanno deciso di fare questa scelta.

**Comment by cmigliardi** [comment]
bene grazie chiedo  abilitazione

**Comment by cmigliardi** [comment]
gli  ip sono tutti assegnati a linee del comune ?

**Comment by SilviaRivi** [comment]
Si confermo

**Comment by cmigliardi** [comment]
gli ip   sono stati abilitati verso  servizi di anpr - cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
