### ISSUE TITLE
Annullamento Mutazione Residenza

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2235]
Buongiorno,
ambiente di Produzione. Tentativo di annullamento mutazione residenza (id 306991558) per il cittadino 43363195. Alla conclusione, esce il messaggio OPERAZIONE GIA' ANNULLATA DALL'OPERAZIONE 336178642 (Codice: EN148) - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-22 12:40:03 , idOperazioneANPR 336182155 (Codice: EN527).
Si precisa che l'operazione 336178642 è andata a buon fine e riferiva ad un altro cittadino (43363198) che faceva parte della stessa mutazione.

Resto in attesa di gradito riscontro.
Grazie
Saluti

**Comment by frmariani** [comment]
l'operazione di annullamento idanpr 336178642, elimina l'intera operazione di mutazione di residenza idanpr 306991558, quindi influisce su entrambi i soggetti ;
nel caso, avreste dovuto indicare che si stava effettuando un annullamento parziale dell'operazione:
1) inserendo nell'elenco dei soggetti il solo di cui si intende ripristinare la residenza;
2) indicando nella lista controlli dell'xml codice= RP e  valore= 1

**Comment by fcastellani81** [comment]
Nella segnalazione di stamattina non ho precisato che ho eseguito entrambe le operazioni di Annullamento Mutazione direttamente da WebAPP.
La prima, (id 336178642) andata a buon fine la seconda (id 306991558) con errore sopra riportato. Ora il secondo cittadino 43363195 risulta ancora mio residente, cosa che in realtà non lo è.
Come posso risolvere?
grazie

**Comment by frmariani** [comment]
purtroppo l'operazione di revoca sul cittadino 43363195 ha creato qualche problema; stiamo valutando come procedere.
gentilmente mi invii un recapito telefonico al seguente indirizzo di posta
frmariani@sogei.it

**Comment by fcastellani81** [comment]
Ho inviato la mail con il recapito telefonico. Eventualmente, è possibile (immagino da parte vostra) eliminare l'operazione di revoca? Così da effettuare l'annullamento della mutazione di residenza autonomamente.
Grazie

**Comment by frmariani** [comment]
purtroppo l'operazione di annullamento della mutazione di residenza è già stato effettuato, ma ha influito soltanto sul cittadino non oggetto di revoca; stiamo ancora valutando quale sia la soluzione migliore.

**Comment by frmariani** [comment]
domani mattina saneremo la situazione annullando l'operazione di mutazione della residenza anche per il soggetto 43363195; sarà mia cura avvisarvi appena l'operazione di ripristino sarà completata.

**Comment by frmariani** [comment]
abbiamo completato l'operazione di ripristino, potete verificare per favore ?

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
