### ISSUE TITLE
Errore inserimento dati atto di nascita

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2236]
Villa Cortese - 015248

Buongiorno,
ho erroneamento inserito i dati dell'atto di nascita di una neo cittadina, ma devo eliminarli.
Come posso procedere?

Ho provato con Elimina dati ma ho ricevuto questo errore:
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-22 17:21:30 , idOperazioneANPR 336400609

Grazie
Vignati

**Comment by frmariani** [comment]
dovrebbe annullare l'operazione con cui li ha inseriti, la mutazione scheda idanpr 336268381

**Comment by cvignati** [comment]
Grazie. tutto sistemato
