### ISSUE TITLE
Cambio di comune di nascita

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2238]
Buongiorno,
oggi ci siamo accorti che alcuni nostri cittadini hanno "subito" il cambio del comune di nascita in maniera automatica.
Al subentro abbiamo proceduto caricandoli con il comune "sbagliato" in quanto non esistente alla data di nascita.
Abbiamo proceduto in questa maniera in quanto detti cittadini erano già ottantenni e non ci sembrava giusto variare il comune di nascita.
In particolare a tutti i nostri cittadini nati a Novafeltria prima del 1941 è stato variato il comune di nascita in Mercatino Marecchia.
Invece ad altri cittadini nati in altri comuni non esistenti alla nascita non è stato variato nulla.

In più ai cittadini a cui è stato variato in ANPR il comune di nascita in Mercatino Marecchia, in AE risulta ancora Novafeltria.

Ecco alcuni ID ANPR di detti cittadini:
38140212
38139883
38138181
38141264
38138085

Ecco quelli a cui non è stato variato:
38137349
38138042

Grazie
Vignati

**Comment by rvinzani** [comment]
Al subentro è stato indicato come comune di nascita Mercatino Marecchia e non è stato quindi modificato
Successivamente non è stata fatta alcuna modifica.
 ANPR non rettifica al subentro i comuni di nascita, si limita ad una validazione tramite codice catastale presente nel codice fiscale.

**Comment by rvinzani** [comment]
Chiuso la issue. In caso sia necessari ulteriori chiarimenti si prega di aprire una nuova issue collegata a questa stessa

**Comment by cvignati** [comment]
buongiorno
