### ISSUE TITLE
Nomi traslitterati in download tabella comuni

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2239]
Buongiorno
Non mi ero accorto di una issue precedente a cui mi ricollego: #2201 

La denominazione traslitterata è importante per noi per la corretta operatività.

Ora vedendo le modifiche di agosto, e la risposta alla issue citata, mi viene il dubbio che sia stata fatta una correzione parziale.

Ovvero la riga id 4519 con  É   è traslitterata E

4519,"1977-01-02","9999-12-31","007032","E167","GRESSONEY-LA-TRINITÉ","GRESSONEY-LA-TRINITE"

Mentre la riga id 22117    con  È   è traslitterata E'

22117,"1861-03-17","1927-01-11","001903","E167","GRESSONEY LA TRINITÈ","GRESSONEY LA TRINITE'"

Analogo comportamento di traslitterazione con apice trovo sulla  Ò

4589,"1861-03-17","9999-12-31","083035","E233","GUALTIERI SICAMINÒ","GUALTIERI SICAMINO'"

Idem su À

5241,"1876-07-15","9999-12-31","078071","E835","MAIERÀ","MAIERA'"

Idem su Ù 

6214,"1861-03-17","9999-12-31","018100","F701","MONTÙ BECCARIA","MONTU' BECCARIA"

Potete controllare per favore se trattasi di refuso da correggere?

**Comment by ncapozzi** [comment]
Buonasera,
abbiamo verificato di avere applicato correttamente la traslitterazione prevista dal decreto Brunetta.
Come ulteriore informazione possiamo dire che:
-	le stesse lettere sono codificate diversamente se sono in mezzo ad una parola rispetto a quando sono  alla fine della parola;
-	La è e la é sono codificate diversamente

N. Capozzi

**Comment by MarcoMigliori** [comment]
Vero, mi ero dimenticato dell'ultima pagina dell'allegato. Scusate l'errore.
