### ISSUE TITLE
[5001] Relazione Parentela da Convivente a Moglie

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#224]
Buongiorno.

La situazione che si va a testare è quella della variazione di relazione di parentela conseguente al matrimonio:
- lo sposo risulta già Intestatario Scheda.
- la sposa subisce la variazione di relazione da "Convivente" a "Moglie".

Si sta utilizzando il servizio 5001.

Ragionevolmente (come negli altri casi di variazioni di relazioni inviate con servizio 5001) viene inviata solo la posizione del soggetto variato: il web-service risponde con l'errore:
"intestatario della scheda famiglia/convivente assente"
(Comune di Medicina - PRE_SUB - idOperazione 2017000356)

Abbiamo aggiunto alla lista elencoSoggettiFamiglia anche l'intestatario scheda, e l'operazione è andata a buon fine
(Comune di Medicina - PRE_SUB - idOperazione 2017000363)

ci chiediamo perchè sia necessario indicare i dati dell'intestatario scheda che NON ha subito alcuna variazione nella sua posizione all'interno della famiglia.
... oppure abbiamo sbagliato il servizio da invocare?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Viene richiesto di specificare comunque l'intestatario anche se non modificato.
