### ISSUE TITLE
Iscrizione AIRE da ricomparsa: codiceErroreAnomalia: EN527

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2241]
Buongiorno,
stiamo procedendo all'iscrizione AIRE per ricomparsa di una famiglia composta da 4 persone, cancellate per irreperibilità dopo il subentro di questo Comune in ANPR. Tre dei componenti sono nati in Macedonia e la loro scheda ANPR riporta come luogo di nascita Ex Repubblica Jugoslava di Macedonia. Quando quindi procediamo al riversamento dei dati in ANPR l'errore che il sistema ci rimanda è il seguente:

idSchedaSoggettoANPR 19843945 non presente o dati anagrafici incongruenti
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-09-29 09:13:30 , idOperazioneANPR 340306507

Abbiamo fatto diversi tentativi ma temiamo che il problema sia riconducibile al luogo di nascita, non possiamo tuttavia intervenire manualmente su ANPR in quanto le i cittadini sono stati cancellati.
Come dobbiamo procedere quindi per finalizzare l'iscrizione dei cittadini in oggetto?
Rimaniamo in attesa di un cortese riscontro.
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
quando effettuate una reiscrizione i dati anagrafici che trasmettete devono essere gli stessi della scheda cancellata. Successivamente li potete modificare se necessario.

Nella scheda cancellata lo stato di nascita era EX REPUBBLICA JUGOSLAVA DI MACEDONIA mentre nell'operazione 340306507 è indicato solo MACEDONIA. Nella WEB APP di ANPR è possibile visualizzare anche le schede cancellate per verificare la congruenza con i dati anagrafici che si stanno ritrasmettendo.

N. Capozzi

**Comment by katiavacchi** [comment]
Chiedo scusa dato che il ticket è stato chiuso, ma chi sta seguendo la pratica mi ha risposto solo ora con la seguente osservazione: "abbiamo verificato che i dati del luogo di nascita/matrimonio fosse congruente con quello presente nelle schede cancellate, abbiamo provato a lanciare il flusso ANPR sia con controllo dei dati in AE sia senza validazione del codice fiscale ma il sistema rimanda sempre l'errore
idSchedaSoggettoANPR 19843945 non presente o dati anagrafici incongruenti"

**Comment by ncapozzi** [comment]
Buongiorno,
potete indicare l'idanpr dell'ultima operazione eseguita?

**Comment by katiavacchi** [comment]
codiceErroreAnomalia: EN185
tipoErroreAnomalia: E
testoErroreAnomalia: idSchedaSoggettoANPR 19843945 non presente o dati anagrafici incongruenti
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-10-01 11:23:53 , idOperazioneANPR 342202983

**Comment by ncapozzi** [comment]
Buongiorno,

confermo quanto precedentemente indicato, quando effettuate una reiscrizione i dati anagrafici che trasmettete devono essere gli stessi della scheda cancellata. Successivamente li potete modificare se necessario.

Nella scheda cancellata lo stato di nascita era EX REPUBBLICA JUGOSLAVA DI MACEDONIA mentre nell'operazione 342202983, come nella precedente, è indicato solo MACEDONIA. 
<luogoNascita>
<localita>
<descrizioneLocalita>GOSTIVAR</descrizioneLocalita>
<descrizioneStato>MACEDONIA</descrizioneStato>
<codiceStato>998</codiceStato>
</localita>
</luogoNascita>
