### ISSUE TITLE
Variazione CAP

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2242]
Villa Cortese 015248

Buongiorno,
all'undici di agosto ho aggiornato massivamente tramite la software house il CAP del nostro cumune.
E' possibile che la motorizzazione abbia inviato i tagliandi dei libretti di circolazione per questa variazione?

Grazie
Vignati

**Comment by azabatta** [comment]
Buonasera, dipende dal tipo di mutazione utilizzata per comunicare l'aggiornamento. Se la casisita fa parte di quelle previste come di interesse per MCTC è possibile che siano state notificate. 
Possiamo avere qualche identificativo operazione oppure qualche identificativo Soggetto ANPR interessato dall'adeguamento?
Grazie

**Comment by cvignati** [comment]
Buongiorno,
id operazione ANPR 309576774, id soggetto ANPR 38140931

**Comment by azabatta** [comment]
Sì, si conferma che la tipologia di mutazione utilizzata "mutazione famiglia/convivenza  - tipo mutazione "rettifica/integrazione indirizzo" (ws 5001 - codice mutazione 9)  è tra gli eventi per i quali è prevista la notifica a MCTC.

**Comment by busaster** [comment]
Mi intrometto nella discussione per evidenziare una cosa : nei casi in cui l'interno comune cambi CAP ci è stato indicato di usare la mutazione da lei indicata per tutte le famiglie e convivenze.
Dobbiamo quindi aspettarci che ad ogni cittadino con veicolo arrivi il tagliandino ?

**Comment by cvignati** [comment]
Purtroppo ho questo sospetto. Ma vi saprò dire.

**Comment by azabatta** [comment]
Sicuramente l'evento è notificato da ANPR a MCTC che è interessata a tutti i cambiamenti  relativi agli indirizzi.
Le elaborazioni che portano poi all'emissione di un nuovo tagliando esulano dal perimetro di ANPR: si tratta di procedure interne di MCTC.

**Comment by azabatta** [comment]
La issue viene chiusa. Se si desidera fornire un riscontro sarà sufficiente riaprirla.
Buona serata

**Comment by RBiasi** [comment]
La scelta del servizio utilizzato deriva dalla issue https://github.com/italia/anpr/issues/2192

**Comment by azabatta** [comment]
Buonasera, 
la scelta effettuata è corretta. Ho chiesto indicazioni sul codice mutazione utilizzato solo per controllare che l'evento fosse tra quelli per i quali è prevista la notifica verso MCTC.
Spero di aver interpretato bene la sua osservazione.

**Comment by cvignati** [comment]
@azabatta chiedo la riapertura

Buongiorno,
oltre ad arrivare i tagliandi di aggiornamento (arrivato anche a me), alcuni cittadini ci informano che le assicurazioni chiedono il certificato di residenza in quanto risulta discrepante con quello presente nel DB Ania.

Come ne usciamo?

Grazie
Vignati

**Comment by azabatta** [comment]
Buongiorno, la segnalazione va inoltrata a MCTC. 
L'invio della notifica non comporta in automatico l'invio di un nuovo tagliando. E' Motorizzazione che lo decide in base ad elaborazioni interne successive alla ricezione della notifica.
