### ISSUE TITLE
Modifica stato civile dopo evento Matrimonio

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2243]
COMUNE DI CAPONAGO

Inviato ad ANPR Evento Matrimonio : OK

Inviato 5008 per mutazione stato civile : tag statocivile = 2 / tipomutazione = 7 (dati generici) , mi chiede obbligatoriamente titolo di studio e condizione professionale che non sono stati modificati.

Qual'è il problema?

**Comment by frmariani** [comment]
per la modifica dello stato civile deve utilizzare il tipo mutazione=1; se utilizza il tipo mutazione =7 deve modificare il titolo di studio e la condizione professionale

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
