### ISSUE TITLE
Pubblicazione CSV province italiane

### ISSUE THREAD

**Issue by lscorcia** [italia/anpr#2244]
Buongiorno, 
nella mia PA stiamo cercando di standardizzare l'elenco storico dei comuni italiani utilizzando il file `src/archivi/ANPR_archivio_comuni.csv` . Sarebbe molto utile poter avere, in aggiunta a questo elenco, anche quello dei record delle province a cui fa riferimento il campo `IDPROVINCIA`. 

In larga parte siamo riusciti a ricostruire la tabella in questione tramite la sigla provincia e i dati ISTAT, tuttavia sto avendo difficoltà per quanto riguarda la provincia di Latina. Dal file dei comuni, alcuni record (es. Aprilia) sono associati all'`IDPROVINCIA` 111 che non riesco a rintracciare in alcuna altra fonte dati, nemmeno ISTAT. Immagino si tratti di una precedente denominazione ormai cessata, ma se poteste uploadarne l'elenco autoritativo sarebbe tutto più semplice.

**Comment by lorbia** [comment]
Salve purtroppo non è prevista la pubblicazione delle decodifiche del sistema anpr eccetto quelle disponibili sul sito istituzionale.
Saluti.
