### ISSUE TITLE
Codice fiscale Omocodice

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2245]
Buongiorno,
in ambiente di subentro, operazione di Iscrizione per nascita (id Operazione 164538872) il Comune ha chiesto erroneamente la Gestione Omocodia per il codice fiscale (anzichè Richiesta Attribuzione).
Preciso che l'operazione effettuata risale a molto tempo addietro (06/12/2019 con decorrenza 22/11/2019) e, normalmente, un codice fiscale può essere revocato entro le 24 ore.
L'ufficio AE territoriale locale ci ha risposto che non ha competenza. 
Come si può correggere l'anomalia?

Ho notato su altri git (#1909) di contattare l'indirizzo mail entrate.archivioanagrafico@agenziaentrate.it . Può essere d'aiuto?

Grazie
Cordiali Saluti

**Comment by frmariani** [comment]
Da quello che ho potuto verificare, il CF alfanumerico, era stato emesso dall'Agenzia delle Entrate prima della vostra richiesta di omocodia, pertanto vi è bastato effettuare una mutazione dei dati anagrafici  per correggere la situazione del cittadino in ANPR;
certamente dovete scrivere alla mail indicata specificando che il cittadino è presente in ANPR con il CF corretto e che l'omocodia è stata richiesta per errore.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
