### ISSUE TITLE
Richiesta Urgente ripristino certificato Server 059032-CO-9999

### ISSUE THREAD

**Issue by PSperlonga** [italia/anpr#2246]
Salve, richiedo il ripristino del certificato server per il Comune di Terracina come da oggetto cancellato per errore. 
Attualmente dalla console viene comunque visualizzato come Attivo. 
Grazie

**Comment by Leonforte** [comment]
Buongiorno, è possibile effettuare il download del p12 dalla console con il tastino a dx, buon lavoro, saluti

**Comment by PSperlonga** [comment]
Il certificato è scaricabile, ma nell'invocare i servizi Anpr si riceve ancora:
certificate revoked (from client)

C'è un tempo da attendere o va sostituito quello precedentemente installato?

Grazie

**Comment by Leonforte** [comment]
no, ma lo avete disattiva e riattivato ? riprovate ora

**Comment by PSperlonga** [comment]
Provato, abbiamo anche scaricato e inviato il certificato alla nostra Software house che lo ha sostituito nei loro sistemi.
tutt'ora quando dall'applicativo effettuiamo anche una semplice consultazione Anpr riceviamo certificate revoked (from client)

E' possibile per voi effettuare una verifica rispetto la chiamata che arriva dall'applicativo? 

Grazie

**Comment by Leonforte** [comment]
Il certificato è stato verificato e non non presenta problemi di accesso, credo sia un problema locale.
