### ISSUE TITLE
Operazione che ha variato la decorrenza di residenza ? 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2247]
Ambietne di produzione, comune di San Vito Dei Normanni

Per il soggetto ID ANPR 86155240 la ricerca con servizio 3002 ritorna una data decorrenza residenza pari a 24/11/2019.
Non riuciamo però a capire con quale operazione questa data sia stata impostata, visto che da webapp vediamo solo il suo inserimento per subentro ed una successiva mutazione famiglia con decorrenza 8/4/2019
Potete aiutarci ?

Grazie

**Comment by frmariani** [comment]
il dato è pervenuto con il subentro del soggetto;
successivamente sono state effettuate due operazioni di rettifica/integrazione indirizzo sulla famiglia: questa tipologia di operazione lascia inalterate le date di decorrenza della residenza di tutti i componenti.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
