### ISSUE TITLE
Modifica denominazione comune in tabella Comuni

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2248]
Buongiorno,

il Comune di Villa Lagarina (TN) ci comunica l'errata denominazione in tabella comuni del comune di 

ID	DATAISTITUZIONE	DATACESSAZIONE	CODISTAT	CODCATASTALE	DENOMINAZIONE_IT
19285	16/10/1920	13/02/1923	802338	G409	PEDERZANO
21699	14/02/1923	20/02/1929	22883	G409	PEDERZANO

La corretta denominazione è PEDERSANO 

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by MassimoSchiappa** [comment]
Salve,
per i dati identificativi dei comuni ANPR attinge a due fonti primarie: 
- per la denominazione, il codice istat, la provincia, le variazioni a quanto pubblicato da Istat e ad oggi accessibile tramite sito web sistat, 
- per il codice catastale ad Agenzia delle Entrate.
Questo premesso, potete verificare che Istat riporta la denominazione indicata in ANPR e peraltro sul sito sistat in corrispondenza della nota che accompagna l'indicazione della data di estinzione del comune (R.D. N. 86  10/01/1929 ) è allegato un documento che riporta la dizione Pederzano (https://sistat.istat.it/sistat/sistat_pdf/3994.pdf).
Cordiali saluti.
