### ISSUE TITLE
Tabelle di riferimento - Stato estero Z118 - Iugoslavia

### ISSUE THREAD

**Issue by lscorcia** [italia/anpr#2249]
Buongiorno, vi segnalo che l'elenco degli stati esteri presente all'indirizzo https://www.anpr.interno.it/portale/documents/20182/50186/tabella_2_statiesteri.xlsx/3fa0ecb9-eb59-4360-afd3-22a72e2a6992 non contiene lo stato estero Z118 - IUGOSLAVIA, cessato ma ancora ampiamente presente nei codici fiscali.

**Comment by ncapozzi** [comment]
Buonasera,
la tabella degli stati esteri di ANPR prevede solo gli stati esteri tuttora attivi. Tuttavia è possibile indicare, ove necessario, la denominazione di uno stato cessato (Jugoslavia, URSS, etc.)  utilizzando come codice stato 998.

N. Capozzi
