### ISSUE TITLE
[5001] Variazione Rapporti di Parentela

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#225]
salve.

l'aggiornamento di rapporto di parantela eseguito con servizio 5001, non produce aggiornamento della "data decorrenza appartenza".

si considerino questi due casi:
1. modifica rapporto di parentela successiva al matrimonio (Conivente che diventa Moglie):
il rapporto di parentela è stato modificato, ma la decorrenza di appartenenza è rimasta quella dell'iscrizione
(idOperazione 2017001008 - ambiente di TEST - Comune di Faenza)

2. famiglia con idANPR 3556616 (ambiente di TEST - Comune di Faenza)
i 3 componenti, sono stati iscritti per IMMIGRAZIONE con decorrenza 01/01/2016.
successivamente, con decorrenza 01/06/2017, sono stati modificati i rapporti di parentela (rif. idOperazione 2017001070 - ambiente di TEST - Comune di Faenza).
l'operazione è andata a buon fine, i rapporti di parentela sono stati modificati, ma la "data decorrenza appartenenza" è rimasta 01/01/2016.

da dove si capisce "da quando" quel componente ha "quel rapporto di parentela" all'interno della famiglia?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
La data di decorrenza del legame di parentela è ora gestita
