### ISSUE TITLE
[5005] - Errore 999 operazione non effettuabile 

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2251]
Salve, 
in data odierna in produzione Comune di Giugliano, abbiamo ricevuto un KO su una mutazione di residenza. 

 ```
<idOperazioneANPR>345046267</idOperazioneANPR>
          <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
          <errore>
            <codiceErroreAnomalia>999</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
          </errore>
          <errore>
            <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-10-06 09:56:20 , idOperazioneANPR 345046267</testoErroreAnomalia>
          </errore>
        </listaErrori>
      </b:rispostaKO>
    </b:Risposta5005>
  </soapenv:Body>
</soapenv:Envelope>

```
E' possibile verificare a cosa è dovuto?

Grazie

**Comment by mrabuano** [comment]
Salve, ci sono novità in merito a questa problematica? L'ente ha necessità di inviare la Mutazione di residenza in tempi brevi

**Comment by asqueglia** [comment]
Buongiorno,
scusate per il ritardo nella risposta. Analizziamo la problematica e le facciamo sapere nel più breve tempo possibile.
grazie

**Comment by asqueglia** [comment]
Dall'analisi del problema abbiamo riscontrato una incongruenza dati sul matrimonio del soggetto causata dal subentro. Abbiamo sanato d'ufficio il dato incongruente. Potete riprovare.
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
Buona giornata
