### ISSUE TITLE
Riapertura Issue 2238 - Cambio di comune di nascita

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2252]
[Issue 2238](https://github.com/italia/anpr/issues/2238)

Buongiorno,
in fase di subentro è stato preso solo il codice istat del comune di nascita, che non è cambiato in quanto Novafeltria ha lo stesso codice istat di Mercatino Marecchia. Io avevo dedotto che in fase di subentro veniva lasciato il comune di nascita, anche se sbagliato, che avevamo in banca dati.
Da un controllo puntuale ho constatato che, al subentro, al cittadino è stato assegnato il comune corrispondente al codice istat esistente alla sua data di nascita.
Io ho 16 cittadini a cui è stato cambiato il comune di nascita, rispetto a quello che ho in banca dati locale.
Questi cittadini, però, in AE, hanno la denominazione sbagliata (es. in ANPR Marcatino Marecchia - In AE Novafeltria) che non va bene. Entrambre le banche dati devono essere allineate. Come dobbiamo comportarci?

Questi cittadini sono in possesso documenti di identità discrepanti dalle risultanze anagrafiche di ANPR. Dobbiamo convocarli per rifare i documenti?

Grazie
Vignati

**Comment by rvinzani** [comment]
Agenzia delle Entrate fino a qualche tempo fa acquisiva solo il codice catastale/istat ed attualizzava la denominazione. E' stato fatto successivamente un intervento per recepire da ANPR anche la denominazione. Tale denominazione però, perchè sia allineata con ANPR ed essere riportata sui documenti, deve essere fatta richiesta esplicita all'Agenzia delle Entrate

**Comment by cvignati** [comment]
Ma la richiesta ad AE deve essere fatta dal cittadino?

**Comment by rvinzani** [comment]
Sì, dal cittadino
