### ISSUE TITLE
Rimpatrio Aire di altro Comune

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2253]
Buonasera,
nell'iscrivere nell'anagrafe comunale un cittadino AIRE del Comune di Tortoreto, l'Anpr restituisce l'errore allegato.
Quale potrebbe essere il problema?
Grazie
Katia
![errorebloccante](https://user-images.githubusercontent.com/57749903/95204765-d3a9f180-07e4-11eb-88c6-2ac020cb39a8.png)

**Comment by ncapozzi** [comment]
Buonasera,
l'ultima richiesta AIRE trasmessa ad ANPR risulta essere del 24/09/2020. Gli errori evidenziati sembrano restituiti dal gestionale più che da ANPR. Si tratta della consultazione della famiglia AIRE alla quale dovete associare il soggetto? Avete provato a sentire la casa software? Potete inviare almeno l'idoperazione comune per effettuare ulteriori verifiche? 
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
non avendo ricevuto ulteriori riscontri si chiude la issue.

N. Capozzi
