### ISSUE TITLE
Problema invocazione servizi WS

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2254]
COMUNE DI CAPONAGO

Buongiorno
volevamo segnalare un'anomalia che accade sempre e solo durante il pomeriggio : al momento dell'invocazione di un qualsiasi servizio esposto dai vostri WS, viene restituito l'errore che segue
<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <env:Fault>
            <faultcode>env:Client</faultcode>
            <faultstring>Internal Error (from client)</faultstring>
        </env:Fault>
    </env:Body>
</env:Envelope>

anche oggi provando con una richiesta 3002 che alleghiamo restituisce sempre lo stesso errore impedendo così l'utilizzo dei servizi.

Alleghiamo la richiesta e restiamo in attesa di gentile riscontro.
[Richiesta3002.txt](https://github.com/italia/anpr/files/5334403/Richiesta3002.txt)

**Comment by mttfranci** [comment]
Salve, prima di procedere con ulteriori verifiche, avete verificato che al momento delle invocazioni l'orario del client che chiama il servizio sia corretto? Una delle cause più frequenti quando si ottiene questo errore sistematicamente è il rifiuto del token di autenticazione in quanto l'orario del client e del server si discosta eccessivamente.

Inoltre vi succede con tutti i servizi? e in quali fasce orarie?
Grazie in anticipo.

**Comment by GabriellaBallabio** [comment]
Buongiorno, abbiamo verificato gli orari e sono corretti.
L'anomalia sembra presentarsi dopo le 14:00 e sicuramente utilizzando il servizio 3002. 
Restiamo in attesa di gentile riscontro. Grazie

**Comment by mttfranci** [comment]
Salve.
Errore sembra essere la data riferimento richiesta  :
<dataRiferimentoRichiesta>2020-10-06+16:01</dataRiferimentoRichiesta>

Forse state passando l'orario come time zone? (nel formato della data il carattere + indica la time zone non l'ora).
Per la data di riferimento richiesta viene considerata solo la szione YYYY-MM-DD quindi forse vi conviene provare con : 

<dataRiferimentoRichiesta>2020-10-06</dataRiferimentoRichiesta>

Senza ulteriori informazioni.
