### ISSUE TITLE
Modifica Gradi di parentela del coniuge di un cittadino deceduto

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2255]
COMUNE DI CAPONAGO

Buongiorno
a fronte del decesso di un cittadino, la cui variazione è stata inviata ad ANPR tramite invocazione di apposito metodo del WS, abbiamo appurato che sul coniuge a parte i dati di vedovanza non vengono aggiornati nè stato civile (VD) nè grado di parentela (IS)
Per quanto riguarda lo stato civile con 5008 abbiamo modificato lo stato civile del coniuge successivamente , per il grado di paremntela quale servizio dobbiamo invocare ?

**Comment by ncapozzi** [comment]
Buonasera,
per la modifica del grado di parentela dovete invocare il WS 5001 mutazione famiglia/convivenza con tipo = 2 COMPOSIZIONE SCHEDA

N. Capozzi
