### ISSUE TITLE
ANPR - Gestione residenti con protocollo riservato

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2256]
Buongiorno,
Vorrei porre un quesito in merito alla gestione dei soggetti sottoposti a protocollo riservato:

Il nostro applicativo ha una gestione ad hoc per questa tipologia di soggetti tale per cui all'atto del subentro in ANPR non vengono inviati e continuano ad essere gestiti solo nel DB locale.

Al momento della fuoriuscita di un tutelato dal programma speciale di protezione la circolare 924/2020 del Ministero dell'Interno (che penso sia arrivata solo ai Comuni interessati) indica che il Comune del "polo fittizio" faccia subentrare il nominativo interessato in ANPR al fine di permettere al comune ove lo stesso ha deciso di fissare la nuova residenza,  il movimento migratorio.

Abbiamo qualche dubbio su questa modalità di intervento.

Non sarebbe più corretto che sia direttamente il comune di nuova residenza ad iscriverlo in ANPR per altri motivi ?
In questo modo, la nuova iscrizione garantisce che la persona sia scollegata dalla precedente.

Grazie

**Comment by rvinzani** [comment]
Per quale comune lavora?

**Comment by c-giacomini** [comment]
Io lavoro per Maggioli Informatica, ma i comuni che ci chiedono indicazioni su come gestire nel migliore dei modi questi casi sono Perugia e L’Aquila.

Grazie

**Comment by rvinzani** [comment]
Mi può per favore dare un contatto telefonico? G

**Comment by rvinzani** [comment]
Il soggetto che si presenta per richiedere la residenza nel comune dove ha deciso di fissarla deve comunque dichiarare da quale comune provenga.  Credo sia corretto quindi che il comune polo li inserisca prima in ANPR.
Chiudo la issue. In caso fossero necessarie ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
