### ISSUE TITLE
annullamento iscrizione per altri motivi

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2257]
Buongiorno,
ambiente di produzione. Si vuole procedere all'annullamento dell'iscrizione per altri motivi (comune non subentrato) con id 255422935 ma non risulta possibile effettuare tale richiesta, in quanto succesivamente all'iscrizione, in data 28/07/2020 è stata effettauta una mutazione scheda (aggiornamento dati elettorali con id 298103543. Ho risolto, ovviamente, richiedendo prima l'annullamento della mutazione e successivamente l'annullamento dell'iscrizione per altri motivi.
A mio avviso, però, la logica non è corretta in quanto il cittadino è ancora iscritto alle liste elettorali del comune. 
Se fosse stata una mutazione di residenza o di famiglia (anzichè iscrizione per altri motivi) il comportamento era analogo?
grazie

Buona giornata

**Comment by ncapozzi** [comment]
Buonasera,
per annullare l'iscrizione in ANPR di un cittadino, operazione che di fatto elimina i dati del cittadino, deve annullare prima qualunque operazione successiva.

La stessa cosa non è vera per l'annullamento delle operazioni di mutazione di residenza o famiglia/convivenza che lasciano comunque attiva la scheda del cittadino in ANPR.
