### ISSUE TITLE
Presubentro di comune già subentrato

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2258]
Buongiorno,

la presente per richiedere se sia possibile ripopolare l'ambiente di Presubentro di un ente già Subentrato.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by ncapozzi** [comment]
Buonasera,

si potete ripopolare l'ambiente di pre-subentro anche se subentrati. Prima dovete richiedere la cancellazione dell'ultimo pre-subentro trasmesso per il comune e attendere il giorno successivo.

N. Capozzi
