### ISSUE TITLE
FILE PRE-SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2259]
Buongiorno,
COMUNE DI CASERTA 061022

abbiamo dei casi in cui nei dati di matrimonio è presente solo il cognome e nome del coniuge che non è, ovviamente, residente,
viene accettato?
il tool di subentro non evidenzia errori
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
le confermo che non è obbligatorio indicare i dati completi del coniuge.

N. Capozzi
