### ISSUE TITLE
Certificato di stato di famiglia con relazioni di parentela per un minore

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#226]
Buongiorno,
abbiamo verificato che se si richiede un certificato intestato a un minore ma con un richiedente maggiorenne viene segnalato un errore, che sembrerebbe dipendere da questo vincolo:
"Il certificato non puo' essere emesso perche' il richiedente deve essere maggiorenne ed appartenente alla stessa famiglia anagrafica dell'intestatario"

In realtà l'art. 33 comma 1 del DPR 223/1989 prevede che:
1. Fatti salvi i divieti di comunicazione di dati, stabiliti da speciali disposizioni di legge, e quanto previsto dall'articolo 35, l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, nonché ogni altra informazione ivi contenuta.
 
Quindi è corretto che il richiedente sia sempre maggiorenne, e l'intestatario possa essere minorenne, ma il richiedente NON debba necessariamente appartenere al nucleo familiare dell'intestatario.

Potete procedere ad una modifica?

Grazie e a presto
Patrizia Saggini - Comune di Anzola dell'Emilia (BO)

**Comment by gcarbonin** [comment]
Il certificato di stato di famiglia con relazioni di parentela può essere richiesto SOLO da un soggetto appartenente alla stessa famiglia, a prescindere dal fatto che l'intestatario della famiglia sia o meno maggiorenne, su  indicazione del Ministero dell'Interni. Suggerisco, pertanto, di chiarire questo aspetto con lo stesso Ministero e, a valle di questa verifica, non ci saranno problemi ad eseguire tutte le verifiche del caso.

**Comment by mccalv** [comment]
Abbiamo verificato e mediato questa richiesta con il Ministero.

Si conferma la segnalazione bloccante quando una persona estranea al nucleo famigliare richiede un certificato di stato di famiglia con relazione di parentela.


**Il comune avrà, in ogni caso, la possibilità di “eseguire” l’operazione se ravvisa la necessità di produrre comunque questo certificato.**

A tal fine sarà necessario indicare il valore 1 nel campo forzaCertificazione, se si utilizzano i WS o specificare “Si” nel campo “Stampa certificato anche in presenza di segnalazioni:” se si utilizza la WA.

Verrà notificato attraverso questo canale quando sarà attivo negli ambienti di test-comuni e pre-subentro.
