### ISSUE TITLE
EMISSIONE DEI CERTIFICATI ANAGRAFICI ANPR (6001-RICHIESTACERTIFICATI)

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2260]
COMUNE DI CAPONAGO

Buongiorno
volevamo sapere se un Comune Subentrato è OBBLIGATO, per l'emissione dei certificati anagrafici,  ad utilizzare la funzione di emissione certificati presente nella WA di ANPR (in alternativa il servizio 6001) oppure se può continuare ad utilizzare la stampa dei certificati presente nel software dell'anagrafe locale.

Restiamo in attesa di gentile riscontro.

**Comment by rvinzani** [comment]
Buongiorno, l'unico certificato che può essere emesso dal software gestionale è quello storico in quanto ANPR conserva la storia delle residenze dal momento del subentro in poi. Tale certificato può essere prodotto richiamando il certificato storico delle residenze di ANPR (6001) e integrando le informazioni con quelle del proprio archivio locale
