### ISSUE TITLE
stessa persona con ID ANPR diverso

### ISSUE THREAD

**Issue by MMaurizio** [italia/anpr#2261]
Errore EAV50 - EN527

Buongiorno Comune di Calceranica al Lago. Stiamo iscrivendo una persona per immigrazione da Pergine Valsugana id anpr 74605681 (con codice fiscale non allineato ..... Z329T). Risolto web app allineamento codice fiscale (con variazione codice fiscale omocode .... Z32VI) ora la stessa persona è presente in ANPR con altro id 38249185 cancellata da Borgo Valsugana a Pergine Valsugana. Si tratta della stessa persona e non riusciamo a concludere la pratica.

**Comment by MMaurizio** [comment]
Id operazione anpr 346973997

**Comment by frmariani** [comment]
l'operazione segnalata, indica che state tentando di modificare i dati del cittadino idanpr 38249185, cancellato dal sistema ANPR dal Comune di Borgo Valsugana; come mai tentate questa operazione ?  il cittadino con idanpr 74605681 risulta residente nel vostro comune con il CF corretto. 

dalle indagini effettuate non ravviso alcun problema, ma forse non ho inquadrato correttamente il problema.

Di seguito il risultato delle mie indagini:
il cittadino con idanpr 38249185 subentra con il comune di Borgo Valsugana con un CF risolto da omocodia;
il 7/12/2018 viene cancellato per emigrazione in comune non subentrato, Peregrine Valsugana; 
il comune di Peregrine Valsugana subentra in ANPR il 30/10/2019 ma purtroppo, per il cittadino in questione,  non inserisce il CF risolto da omocodia, pertanto il sistema ANPR gli assegna un altro idanpr, il 74605681 ;
il vostro comune effettua la mutazione di residenza del cittadino con idanpr 74605681  il 7/10/2020;
in data odierna, effettuate una modifica dei dati anagrafici riportando giustamente il CF risolto dall'omocodia.

Mi rendo conto che la consultazione per CF mostra la duplicazione dello stesso, ma come avete giustamente notato, il cittadino con idanpr 38249185 risulta cancellato.

**Comment by MMaurizio** [comment]
Si ha inteso correttamente dott.ssa Mariani. Per fortuna sono riuscito a concludere correttamente l'iscrizione anagrafica, annullando web service la pratica precedente che era collegata alla persona cancellata a Borgo Valsugana. Ho quindi rifatto la pratica richiamando il soggetto residente a Pergine Valsugana (con il codice fiscale e il luogo di nascita  corretto come quello di Borgo Valsugana) e la pratica è andata a buon fine. Confermo e concordo che ora la consultazione mostra la duplicazione dello stesso ma id 38249185 risulta cancellato e quindi poco importa. La ringrazio della sua tempestiva collaborazione.

**Comment by frmariani** [comment]
a volte i gestionali impongono delle operazioni non necessarie nel sistema ANPR;
nel suo caso, sono aumentate le operazioni sul cittadino ma la situazione è rimasta la stessa: avete in carico il cittadino con idanpr 74605681  e CF risolto da omocodia.
