### ISSUE TITLE
Controllo lunghezza campo ESPONENTE1 

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2262]
Buonasera, abbiamo fatto il presubentro del comune citato nella issue #1627 . 
Il campo ESPONENTE1 che abbiamo utilizzato in questo caso, risulta di lunghezza massima 80 caratteri.
Tuttavia ci siamo accorti che apparentemente ne memorizza/mostra 20.

Sull'ID cittadino 235261649, abbiamo inviato in questo campo la stringa
"PAL FALBO E LA NEVE A"
mentre vediamo 
"PAL FALBO E LA NEVE"

Qualora utilizziamo la web app per fare una simulazione di mutazione residenza e cerchiamo di inserire nel campo esponente1 del browser
"PAL FALBO E LA NEVE A"
non ci sta, viene troncato.

Per le esigenze della issue citata era stato individuato questo campo, perchè serve una stringa lunga. 20 caratteri non bastano. Fateci sapere, grazie.

**Comment by amollicone1982** [comment]
Le è stata data una indicazione sbagliata nella precedente issue. Il campo esponente1 è di 20 caratteri e per tale motivo viene troncato.  Per tale casistica sarebbe ideale usare il campo frazione che è di 80 caratteri.
Probabilmente il collega si è confuso.
