### ISSUE TITLE
Modifica certificati per stampa indirizzo con civico 0 e esponente1 compilato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2263]
Buonasera, come anticipato nella issue #1627 , abbiamo fatto il presubentro di questo Comune.
Un esempio di cittadino con indirizzo di tipo "palazzo", è l'id 235261649.

Nella issue precedente avete scritto:
_Direi di utilizzare uno dei due campi per inviare l'informazione ad ANPR al subentro poi verificheremo come inserirla sui certificati senza che questo abbia impatto sulla logica di stampa delle informazioni relative all'indirizzo per gli altri comuni._

Vi apro quindi questa segnalazione, perchè possiate valutare come modificare la stampa dell'indirizzo in questo caso. Resto in attesa, grazie.

**Comment by rvinzani** [comment]
Non è facile modificare il criterio di stampa dei certificati senza incorrere nel problema di scombinare la situazione per altri comuni.
Se posso permettermi di suggerire una soluzione indicherei nel campo numerocivico PAL o PALAZZO e nel campo esponente1 la dicitura già presente (rispettando la lunghezza di 20 caratteri

**Comment by rvinzani** [comment]
Come da accordi chiudo la issue. In caso di necessità di maggiori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
