### ISSUE TITLE
[5005] errore in invio cambio indirizzo con campo esponente1 compilato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2264]
Buonasera, nel fare le prove di mutazione dei dati del comune citato nella issue #1627 , troviamo degli errori che non riusciamo a spiegarci.

Un esempio è il test fatto dal nostro programma, inviando prima una 1014 (positiva), una 5005 con questo errore:

```
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-10-08 17:18:04 , idOperazioneANPR 20348018
```

Abbiamo provato a confrontare l'xml con una prova fatta dalla web application, ma non riusciamo a capire il problema. Potete verificare?

**Comment by rvinzani** [comment]
L'errore è dato dal fatto che nell'esponente1 è stato inserito un campo di 21 caratteri che per il momento è invece impostato a 20 sul DB: "PAL FALBO E LA NEVE B"

**Comment by rvinzani** [comment]
Come da accordi chiudo la issue. In caso di necessità di maggiori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
