### ISSUE TITLE
Definizione XSD campo esponente1

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2265]
In riferimento alla #2262 faccio presente che sugli XSD da sempre il campo esponente1 mi risulta di lunghezza 80. Probabilmente avete 20 sul database, mi sembra di intuire dalla risposta. Il codice dovrebbe essere questo:

```
    <xs:simpleType name="tipoEsponente1">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-zA-Z\- ])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="80"/>
		</xs:restriction>    
	</xs:simpleType>	
```

Se mi confermate che è di lunghezza 20, non ho una soluzione per la issue #1627 .

**Comment by amollicone1982** [comment]
E' sicuramente un evoluzione in corso. Lo si capisce dal fatto che nella documentazione tecnica 
Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica
presente all'indirizzo https://www.anpr.interno.it/portale/documentazione-tecnica il campo è di 20 caratteri.
Per tale motivo consiglio il campo frazione che è di 80 caratteri
