### ISSUE TITLE
Download SafeDive

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2266]
Salve,
ho seguito la guida "Configurazione della postazione per laccesso al sistema web ANPR e operazioni propedeutiche al subentro v.2.pdf" ma non riesco proprio a trovare sul portale anpr.interno.it il link per scaricare il file SafeDive3.4.1_setup.zip

**Comment by cmigliardi** [comment]
Buongiorno, 
trovate le indicazioni al punto 5 della guida all'anpr  - che trovate nella home page el sito anpr

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by vix-db** [comment]
Le sto dicendo che ho letto la guida e l'indicazione a cui si riferisce è estremamente vaga: la mia domanda è DOVE trovare tale link senza fare la ricerca del famoso ago nel pagliaio.

**Comment by cmigliardi** [comment]
punto 5 della guida all' anpr 
ATTENZIONE: per l’utilizzo delle l’utilizzo delle smart card inviate da maggio 2020 scaricare i driver ai seguenti link:
◦Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro
◦SafeDive3.4.1_setup
◦Dike-Gosign-installer-win32
◦IDP_6.47.04_ITA
 
e far riferimento al documento:
◦Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro

**Comment by vix-db** [comment]
![safedive](https://user-images.githubusercontent.com/47904600/95573602-ff6ae880-0a2b-11eb-8d7c-6f783dce8892.PNG)

**Comment by cmigliardi** [comment]
sarà un refuso ....    le assicuro  che trova tutto al punto 5 della guida 
punto 5 della guida all' anpr
 ATTENZIONE: per l’utilizzo delle l’utilizzo delle smart card inviate da maggio 2020 scaricare i driver ai seguenti link:
◦Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro
◦SafeDive3.4.1_setup
◦Dike-Gosign-installer-win32
◦IDP_6.47.04_ITA

e far riferimento al documento:
◦Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro

**Comment by vix-db** [comment]
Ok, facevamo riferimento a due guide diverse.
Ho trovato il link nella guida generale, la ringrazio.

**Comment by cmigliardi** [comment]
perfetto . La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
