### ISSUE TITLE
Emissione certificati anagrafici con software gestionale anagrafe locale Rif. issue #2260

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2267]
Buongiorno con rifemento all'issue #2260
volevamo ricevere chiarimenti in merito al fatto che è necessario emettere i certificati anagrafici per i cittadini residenti SOLO con i servizi di ANPR.

Perchè non possiamo emettere i certificati anagrafici con il nostro software di anagrafe locale ? i dati di ANPR sono inviati e tenuti aggiornati dall'anagrafe locale ! Visto che è l'ufficiale d'anagrafe che firma i certificati emessi, è lui che garantisce se i dati dell'anagrafe locale sono corretti.

Restiamo in attesa di chiarimenti.

**Comment by rvinzani** [comment]
Perchè questo è indicato nel DPCM 194/2014 che istituisce l'ANPR

**Comment by GabriellaBallabio** [comment]
Certo il DPCM l'abbiamo letto però non troviamo "l'obbligatorietà" può fornirci ulteriori indicazioni per cortesia ?

**Comment by rvinzani** [comment]
Per questo è necessario che il comune si rivolga al Ministero dell'Interno in quanto l'indicazione non è di tipo tecnico

**Comment by rvinzani** [comment]
chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa
