### ISSUE TITLE
[5001] Rettificare la data di decorrenza dell'indirizzo

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#2268]
Buongiorno,
qual'è la corretta procedura per rettificare la dataDecorrenzaResidenza in caso di inserimento errato?

Ringrazio anticipatamente

**Comment by frmariani** [comment]
La data di decorrenza della residenza può essere rettificata soltanto se il cittadino è stato aggiunto in ANPR con il subentro del comune e se il cittadino non ha effettuato dei successivi cambi di residenza; la rettifica sarà possibile anche in presenza di operazioni successive al subentro, ma la data sarà modificata soltanto se minore della data di ultimo aggiornamento APR.
Dalla web app di ANPR
Tipo di operazione: Rettifiche
Iniziativa: a scelta
si ricerca il cittadino oggetto di rettifica
Dati di controllo> Tipo di rettifica: Rettifica dati subentro; al tasto CONFERMA, il sistema riporterà l'attuale data di decorrenza della residenza, ma il campo editabile ne permetterà la modifica; la conferma della pagina ed il "Salva e chiudi" successivo, concluderanno l'operazione.

**Comment by SAlberto** [comment]
Va bene per gli eventi prima del subentro.

In realtà il caso che mi interessava era:
L'individuo ha dichiarato un cambio di indirizzo interno al comune ma l'operatore ha erroneamente indicato la data corrente mentre la decorrenza corretta era di 5 giorni prima.

Come faccio a rettificare la data?
Ringrazio anticipatamente

**Comment by frmariani** [comment]
deve annullare l'operazione e ripeterla con la data corretta

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
