### ISSUE TITLE
[5005] Cambio indirizzo con falso esito positivo

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2269]
Comune di Torino - Ambiente di produzione

Buongiorno,
è stato effettuato un cambio di indirizzo per tre soggetti. Due soggetti su tre sono stati allineati su ANPR, mentre il terzo non è stato allineato (ID Soggetto 28761538). 
Abbiamo controllato e la chiamata è partita correttamente e ha restituito esito positivo con warning (ID Operazione 336604096).
Potremmo sapere il motivo per cui non è stato aggiornato l'indirizzo di questo soggetto?

Inoltre, cosa ancora più strana, gli operatori comunali hanno annullato via WebApp i 5008 partiti successivamente per il soggetto e, al loro annullamento, l'indirizzo si è aggiornato correttamente sulla scheda del cittadino. Per quale motivo un 5008 dovrebbe incidere sull'indirizzo?

Grazie, cordialmente
Chiara Leanza

**Comment by rvinzani** [comment]
Le operazione risultano tutte correttamente registrate e coerenti con le date inserite. Gli annullamenti delle operazioni di mutazione tutti i dati sono indipendenti dalla mutazione di residenza. Non risulta quindi nessuna incongruità 
Chiudo la issue. Nel caso fosse necessario un ulteriore chiarimento si prega di aprire una nuova issue che faccia riferimento a questa stessa

**Comment by CSI-Piemonte-Demografia** [comment]
Non riteniamo soddisfacente questa risposta in quanto tre persone hanno visto questo comportamento anomalo di ANPR.
La prossima volta, perchè sicuramente ricapiterà (questa non era la prima) eviteremo di annullare i 5008 e riporremo lo stesso quesito.

**Comment by rvinzani** [comment]
Sicuramente sarà più semplice verificare il caso prima che  effettuiate altre operazioni. Saluti, Roberta Vinzani
