### ISSUE TITLE
Indicazione del comune di Atto di nascita

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#227]
Corbetta, ambiente di Produzione

Buongiorno, avremmo bisogno di sapere cosa comporta indicare nel comune dell'atto di nascita non il comune valido all'epoca della registrazione ma il comune valido attualmente. Cioè se una persona è nata a Nicastro nel 1950 è possibile inserire come luogo di nascita Nicastro (valido alla data) e come comune di atto di nascita originale Lamezia Terme, quale depositario dei registri che furono di Nicastro, senza creare problemi alla procedura?

Grazie.

**Comment by gcarbonin** [comment]
Ricordando che si dovrebbe riportare in anagrafe quello che risulta nello stato civile (chi ha formato l'atto di nascita? quale è il luogo di nascita indicato nell'atto?), si deve poi vedere l'operazione che il comune vorrebbe fare. In genere per eventi "vecchi" al momento ci sono le stesse tolleranze previste in subentro; in particolare sul comune di nascita se quanto indicato dal comune è collegato al codice catastale del codice fiscale, l'operazione termina senza errori (non viene segnalata nemmeno l'anomalia).
Sugli eventi "nuovi" (iscrizione per nascita, cancellazione per decesso ecc.) non ci sono tolleranze.
