### ISSUE TITLE
Modifica anno di matrimonio cittadini anpr residenti

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2270]
Buongiorno,
la presente per chiedere come procedere alla modifica dell'anno di matrimonio di due cittadini residenti in questo comune e precisamente da 2011 a 2001 in quanto dalla tentata rettifica in Anpr da Mutazione tutti i dati ed operazione d'ufficio mi ritorna questa notifica di errore:

- IdOperazione ANPR 350901201 (Codice: EN527) 

Ringrazio per la collaborazione e porgo cordiali saluti

**Comment by frmariani** [comment]
Gentilmente mi invii un recapito telefonico alla seguente mail
frmariani@sogei.it

**Comment by ACastelleone** [comment]
0374 356318
Grazie

**Comment by frmariani** [comment]
il problema è stato risolto per le vie brevi;
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
