### ISSUE TITLE
Errore invocazione servizio 3003 - consultazione delle notifiche predisposte per il comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2273]
COMUNE DI CAPONAGO

Provando ad accedere al servizio 3003 per scaricare tutte le operazioni di competenza del comune otteniamo il seguente errore 
<codiceErroreAnomalia>EN379</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Funzionalita' non supportata Modalita' di interrogazione non piu' supportata a partire da ANPR02</testoErroreAnomalia>

Quale servizio alternativo dobbiamo invocare per conoscere le variazioni che l'ente deve effettuare ?

**Comment by azabatta** [comment]
Buongiorno,
il servizio di interesse è il "4005 – Richieste_asincrone". Per avere una prima descrizione delle modalità di funzionamento è possibile consultare la issue #1161.
Le specifiche tecniche sono pubblicate sul portale di ANPR.
