### ISSUE TITLE
Formato date rilascio/scadenza permesso di soggiorno

### ISSUE THREAD

**Issue by herasimau** [italia/anpr#2275]
Le date rilascio/scadenza del permesso di soggiorno non sono in formato leggibile da utenti normali.

<img width="895" alt="Screenshot 2020-10-17 at 17 11 26" src="https://user-images.githubusercontent.com/14974515/96346484-5b70e500-109c-11eb-8aac-55b56f51e0c0.png">

**Comment by mttfranci** [comment]
Buongiorno, stiamo parlando della Visura anagrafica del cittadino giusto?
(Chiedo conferma perchè è preferibile circostanziare sempre se la segnalazione riguarda l'interfaccia per gli ufficiali di anagrafe o quella per i cittadini).
Grazie in anticipo.

**Comment by mttfranci** [comment]
Salve, ora la formattazione dovrebbe essere corretta, potete verificare? Grazie in anticipo.
