### ISSUE TITLE
PROBLEMI COL CONGO

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#2276]
Devo modificare lo stato civile di una cittadina congolese, ma il sistema mi segnala l'errore EC031- IL CODICE DELLO STATO ESTERO DI NASCITA NON E CONGRUENTE CON LA DESCRIZIONE REPUBBLICA DEL CONGO. 
ID OPERAZIONE 354582377 
Potete suggerirmi una soluzione Grazie

**Comment by ncapozzi** [comment]
Buonasera,
come indicato nel msg di errore, Il codice dello stato estero di nascita 418 non è congruente con la descrizione REPUBBLICA DEL CONGO, Consultando la tabella degli stati esteri pubblicata sul portale di ANPR al link https://www.anpr.interno.it/portale/tabelle-di-riferimento potete verificare che il codice 418 corrisponde  a CONGO mentre la REPUBBLICA DEMOCRATICA DEL CONGO ha codice 463.
Lo stato REPUBBLICA DEL CONGO non è presente nella tabella.

N. Capozzi
