### ISSUE TITLE
DIVERGENZA CAP ANPR DA QUELLO RIPORTATO NELL'ARCHIVIO DELL'AGENZIA DELLE ENTRATE #2240

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2277]
Ad oggi il problema non risulta essere stato risolto

**Comment by rvinzani** [comment]
Gent.le Sig.ra Cavallin, ho inoltrato la sua segnalazione alle colleghe di Agenzia Entrate che a loro volta inoltreranno la segnalazione a Postel per la corretta gestione della casistica con il prodotto per la normalizzazione dell'indirizzo. Appena mi rispondono la contatterò sulla sua casella di email. Saluti Roberta Vinzani
