### ISSUE TITLE
Regno d'Italia in Etiopia

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2279]
Buongiorno,
si presenta persona nata nel 1941 a Decameré, con atto trascritto in altro comune italiana e senza l'indicazione dello Stato (legge n. 54 del 15/2/1989 e nota n. 15/1999 del Ministero dell'Interno). IN Agenzia Entrate è presente ora come nato in Etiopia, CF colelgato come nato in Eritrea. Il cittadino insiste per avere documento con Decamerè - Eritrea.
Nel 1935, Eritrea ed Etiopia vengono "conquistate" e divengono Regno d'Italia; a seguito del Trattato di Parigi: 
- l'Eritrea resta sotto controllo britannico e nel 1952 l'Onu la dichiara federata all'impero etiope;
- l'Impero d'Etiopia ritorna ufficialmente indipendente, anche se i territori sotto amministrazione britannica, come la regione dell'Ogaden, vengono ceduti solamente nel 1954.
Tenuto conto che per la ex-Iugoslavia è stata fatta la scelta di gestire i comuni (ante 1947/1977) come italiani e con la relativa provincia, come dovremmo gestire la fattispecie?
Grazie
Anna Maria AIMONE
UPI - Torino

**Comment by ncapozzi** [comment]
Buongiorno,
le ho inviato una email con il mio recapito telefonico per ulteriori chiarimenti in merito al problema segnalato.

N. Capozzi

**Comment by ncapozzi** [comment]
Confermo che è possibile modificare lo stato esteri di nascita da ETIOPIA a ERITREA in modo da ripristinare il CF corrispondente, quello con Z368, come principale su Agenzia Entrate e in ANPR. L'altro CF del cittadino, quello dell'Etiopia con Z315, diventerà automaticamente il secondario,

N. Capozzi
