### ISSUE TITLE
Certificato di cittadinanza per stranieri

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#228]
Apriamo questa issue per tracciare l'evoluzione di ANPR al fine di supportare il certificato di residenza per cittadini stranieri nelle prossime release

**Comment by bfilipazzi** [comment]
Suppongo si tratti del "Certificato di CITTADINANZA per Stranieri", infatti ANPR già produce il "Certificato di RESIDENZA per Stranieri"

**Comment by mccalv** [comment]
Mi scuso ho corretto nel titolo. @bfilipazzi sarebbe utile se volessi indicare in quali casi é richiesto

**Comment by bfilipazzi** [comment]
Riguardo ai casi preferisco non intromettermi, non è il mio ruolo e gli ufficiali d'anagrafe che ho sentito esprimono pareri discordanti e lascio a loro l'argomento

**Comment by mccalv** [comment]
Abbiamo verificato e mediato questa richiesta con il Ministero.

Si conferma la segnalazione bloccante quando si richiede un certificato di cittadinanza di un cittadino straniero. 
**Il comune avrà, in ogni caso, la possibilità di “eseguire” l’operazione se ravvisa la necessità di produrre comunque questo certificato.** 
A tal fine sarà necessario  indicare il valore 1 nel campo forzaCertificazione, se si utilizzano i WS  o specificare “Si” nel campo “Stampa certificato anche in presenza di segnalazioni:” se si utilizza la WA. 

Verrà notificato attraverso questo canale quando sarà attivo negli ambienti di test-comuni e pre-subentro.

**Comment by psaggini** [comment]
Se può essere utile alla discussione, il certificati di cittadinanza - sia per italiani che per stranieri - viene sicuramente richiesto per l'iscrizione di bambini e adulti alle squadre di calcio che partecipano ai campionati di vario livello, e sono espressamente richiesti dal regolamento della FIGC.

Rimane sempre il principio che può essere certificato qualsiasi dato che sia presente in anagrafe, perchè l'iscrizione della persona da parte dell'ufficiale del Comune avviene sulla base di documenti ufficiali presentati.

**Comment by gcarbonin** [comment]
La modifica che consente di produrre il certificato è disponibile anche in ambiente di produzione
