### ISSUE TITLE
[5012] Annullamento non possibile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2280]
Ambiente di produzione, comune di Battipaglia

tentando di annullare il movimento ID ANPR 289457802 con l'operazione ID 356115324 riceviamo l'errore "EN077 L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa."

Qual è l'operazione che blocca ? 

Grazie

PS :  L'ho già chiesto in altre issues, ma insisto sul fatto che  avere  questa informazione nel messaggio di errore velocizzerebbe di molto le operazioni di assistenza.

**Comment by frmariani** [comment]
E' in corso di lavorazione l'aggiornamento del messaggio con l'idoperazione che ostacola l'annullamento;
l'operazione che si tenta di annullare è stata superata da un'altra modifica della residenza, idoperazione 356185047; vi ricordo che le operazioni effettuate dal comune sono visualizzabili attraverso la consultazione del soggetto, nella sezione "Elenco operazioni".

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
