### ISSUE TITLE
OPERAZIONI SOSPESE - ISCRIZIONE NASCITA AIRE

### ISSUE THREAD

**Issue by DemResana** [italia/anpr#2281]
Buongiorno,

In "Utilità e notifiche / Operazioni sospese" risulta un'operazione sospesa di "Iscrizione nascita AIRE".
Qual'è la procedura per eliminarla?
In "Registrazione", selezionando il servizio "Iscrizione per nascita (AIRE)", l'operazione di cui sopra non compare diversamente da quanto accade con il servizio "Mutazione di tutti i dati".

ID operazione: 36121991
Ambiente: produzione
Comune di Resana
L.Canevese

Cordiali saluti

**Comment by rvinzani** [comment]
E' possibile che l'operazione sospesa sia stata effettuata da un altro suo collega quindi non visibile con la sua utenza.

**Comment by DemResana** [comment]
No, confermo di essere stato io ad effettuare l'operazione.

Nella colonna ID OPERATORE compare il mio codice fiscale.


L.Canevese
Uffici Demografici


________________________________
COMUNE DI RESANA - NOTA DI RISERVATEZZA: Le informazioni contenute in questo messaggio di posta elettronica sono di natura confidenziale qualsiasi pubblicazione, utilizzo o diffusione anche parziale dello stesso non pu? essere effettuata senza la nostra autorizzazione e potrebbe costituire un illecito penale ai sensi della vigente normativa sulla Protezione dei Dati Personali. Qualora non siate i destinatari di questa email Vi preghiamo cortesemente di cancellarla dal Vostro sistema dopo aver notificato al mittente l'errore commesso.

**Comment by rvinzani** [comment]
Può darmi l'idANPR del soggetto?

**Comment by DemResana** [comment]
89646856

L.Canevese
Uffici Demografici


________________________________
COMUNE DI RESANA - NOTA DI RISERVATEZZA: Le informazioni contenute in questo messaggio di posta elettronica sono di natura confidenziale qualsiasi pubblicazione, utilizzo o diffusione anche parziale dello stesso non pu? essere effettuata senza la nostra autorizzazione e potrebbe costituire un illecito penale ai sensi della vigente normativa sulla Protezione dei Dati Personali. Qualora non siate i destinatari di questa email Vi preghiamo cortesemente di cancellarla dal Vostro sistema dopo aver notificato al mittente l'errore commesso.

**Comment by rvinzani** [comment]
Come da contatto telefonico chiudo la issue. Si tratta di un errore in visualizzazione ma è stato verificato che non è presente nessuna operazione sospesa
