### ISSUE TITLE
ISCRIZIONE PRELIMINARE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2282]
Buonasera,
quale servizio e quale codice motivo di iscrizione utilizzare per la iscrizione preliminare da comune non subentrato.

Comune di CASERTA 061022

**Comment by rvinzani** [comment]
1002 - iscrizione per altri motivi. Motivo : immigrazione da comune non subentrato.

**Comment by rinonasti** [comment]
Grazie,
poi quando l'immigrazione è definitiva (dopo accertamenti) ?
o se è negativa?
