### ISSUE TITLE
[5005] Errore EN493 - L'utente non dispone dei privilegi per eseguire l' operazione

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2283]
Salve, 
su ambiente di produzione Giugliano l'Ente ha ricevuto il seguente errore a seguito dell'invio di una mutazione di residenza. 

     <errore>
            <codiceErroreAnomalia>EN493</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione </testoErroreAnomalia>
          </errore>
          <errore>
            <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-10-21 12:44:53 , mittente 063034 , idOperazioneComune 8049834</testoErroreAnomalia>
          </errore>

L'operatore ha i permessi corretti configurati nella WebApp e non ha avuto problemi ad inviare altri Mutazioni di residenza

**Comment by gife67** [comment]
Buongiorno,
cortesemente potete fornirci l'utenza utilizzata.
Grazie mille

**Comment by mrabuano** [comment]
Salve,
ho inviato il CF dell'operatore in mail
Buona serata

**Comment by gife67** [comment]
Buongiorno,
il problema specifico è relativo al fatto che nella richiesta sono stati forniti degli idsoggetto non esistenti, quindi vi prego di verificarne l'esistenza. La diagnostica di questo caso particolare verrà rivista.

**Comment by mrabuano** [comment]
Ok,grazie e buona giornata
