### ISSUE TITLE
[6001] Anagrafico di morte soggetto Aire

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2284]
Ho simulato con la WebApp un caso analogo alla #1544 (data morte imprecisata), ma su un soggetto aire. Id cittadino 16421153, ambiente test.
La certificazione lato WebApp, non mi mostra come disponibile il certificato "Anagrafico di Morte".
Se provo a eseguirlo da ws, ottengo l'errore
_Il certificato non puo' essere emesso in quanto il soggetto e' iscritto all'AIRE_

Apparentemente si tratta di un limite voluto. E indipendente dal mio test sulla data imprecisata, ma proprio relativo ai morti aire. Mi sfugge al momento il motivo, visto che anagrafico di nascita e matrimonio risultano disponibili, quindi chiedevo conferma che non è prevista la certificazione anagrafica di morte per soggetto aire. E nemmeno un generico certificato di cancellazione da ANPR, in questo caso. Non sono riuscito a certificare la data di cancellazione, o lo storico di residenza aire, in nessun modo.

**Comment by ncapozzi** [comment]
Buongiorno,
la normativa di riferimento per l'emissione dei certificati relativi a cittadini AIRE in ANPR è riportata nella issue #122 . Per ulteriori chiarimenti normativi è opportuno rivolgersi direttamente alla Direzione centrale per i Servizi demografici, Dipartimento per gli Affari interni e territoriali, Ministero dell’Interno.

N. Capozzi
