### ISSUE TITLE
Invio dati cumulativi

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2285]
Buongiorno,
E' previsto l'invio di mutazioni cumulative (es. carte di identità emesse nel giorno)  ?
Grazie

COMUNE CASERTA 061022

**Comment by frmariani** [comment]
Un sistema integrato, permette l'aggiornamento automatico nel sistema ANPR delle carte d'identità elettroniche emesse dal Poligrafo;
Per il resto, se ho ben interpretato la richiesta, tutte le mutazioni devono pervenire distinte per soggetto e per tipologia di servizio;
Il servizio di Mutazione dei dati (WS 5008), permette mutazioni cumulative nella stessa operazione per singolo soggetto.

**Comment by rinonasti** [comment]
grazie quindi non é più necessario l'invio delle mutazioni carte di identità ? 
WS5008 tipo mutazione 03

**Comment by frmariani** [comment]
la carta d'identità cartacea si gestisce con il WS 5008 tipo mutazione 3

**Comment by rinonasti** [comment]
Grazie,
E' previsto un sistema integrato simile per i permessi di soggiorno?
visto che sono emessi da un Ente esterno al comune

**Comment by frmariani** [comment]
No, al momento l'aggiornamento dei dati del Permesso di Soggiorno è demandato al Comune

**Comment by rinonasti** [comment]
ok grazie.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
