### ISSUE TITLE
ANPR - Gestione residenti con protocollo riservato - aggiornamento situazione

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2287]
Facendo riferimento ad una precedente issue #1621 volevo sapere se ci sono state implementazioni in ANPR in merito alla gestione dei residenti con protocollo riservato visto che siamo in procinto di passare in ambiente di produzione. Grazie e saluti.
Ferretti Laura

**Comment by FilippoPapi** [comment]
le indicazione sono sempre quelle della issue #1621  non appena avremo nuove indicazioni le comunicheremo 
buona serata

**Comment by FilippoPapi** [comment]
le indicazione sono sempre quelle della issue #1621  non appena avremo nuove indicazioni le comunicheremo 
buona serata
