### ISSUE TITLE
Aggiornamento dati per la Motorizzazione

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2289]
Buongiorno,
per le mutazioni anagrafiche tra Comuni subentrati, con quale flusso (5001, 5008, ecc) parte la comunicazione dell'aggiornamento dei dati per la Motorizzazione?
Grazie e buon lavoro,
cordiali saluti.

**Comment by azabatta** [comment]
Buongiorno, 
le mutazioni  che comportano invio di una comunicazione verso MCTC sono quelle che trattano gli indirizzi di residenza  (ws 5001- ws 5005 - ws A006:  codici mutazione che impattano sull'indirizzo di un cittadino che ha la sezione patente/autoveicoli valorizzata) e quelle che comportano aggiornamento della sezione dati "patente/autoveicoli" (ws 5008).
