### ISSUE TITLE
Mutazione della scheda per "mero errore materiale”

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#229]
Apro questa issue per segnalare la possibilità di mutazione di una scheda anagrafica che non comporti una variazione dello storico delle operazioni anagrafiche, ma serva solo a rettificare un mero errore materiale (refuso, erronea trascrizione del nome)

**Comment by gcarbonin** [comment]
E' stata prevista la possibilità di rettifica di alcune informazioni che sono "interne" ad ANPR e non hanno impatti esterni (ad esempio, alcune date, motivo iscrizione, ecc.). Queste variazioni sono comunque storicizzate ma non sono visibili interrogando la scheda o stampando un certificato. Non è possibile "rendere invisibili"  quelle operazioni che hanno  già prodotto effetti all'esterno: ad esempio, l'iscrizione di un neonato con dati sbagliati ha determinato l'attribuzione di un codice fiscale; la correzione del dato errato determina una variazione su Agenzia delle Entrate che viene storicizzata sia da ANPR che dall'Agenzia. Ricordo inoltre che un dato storico è visibile esclusivamente interrogando la scheda ad una data passata: in altri termini, se modifico un cognome da ROSSI a RASSI il 4 ottobre 2018, da quel momento in poi si vedrà sempre RASSI, salvo nel caso in cui si interroghi la scheda ad una data antecedente al 4 ottobre 2018.
