### ISSUE TITLE
Luogo di nascita: Gaza

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2290]
Buongiorno,
abbiamo il caso di un cittadino nato a Gaza (nel 1949) la cui posizione è la seguente: in AE risulta nato in "Territorio di Gaza", in Anpr risulta nato in "Circoscrizione autonoma". Il codice fiscale in entrambi i casi contiene come riferimento al luogo di nascita Z218. 
Nel file degli stati esteri abbiamo visto che esiste solo "Territori dell'autonomia palestinese" con riferimento Z161.
Come è meglio procedere? Possiamo lasciare Z218, facendo prevalere i dati di AE?

Grazie per l'attenzione,
cordiali saluti.

**Comment by ncapozzi** [comment]
Buongiorno,

possiamo avere per favore l'idsoggetto ANPR?

**Comment by katiavacchi** [comment]
19806576

**Comment by ncapozzi** [comment]
Che luogo di nascita è riportato sui documenti del cittadino?

**Comment by katiavacchi** [comment]
non siamo in possesso del passaporto. abbiamo una trascrizione di atto di nascita del 1992, con luogo di nascita "Gaza"

**Comment by ncapozzi** [comment]
Allora in prima battuta confermate i dati di Agenzia delle Entrate dalla web app, utilità e notifiche, risoluzione disallineamenti con AE.
Qualora il cittadino invece volesse "Territori dell'autonomia palestinese" , successivamente alla validazione dell'attuale CF effettuate una modifica dello stato estero di nascita facendo prima presente che questo comporterà l'attribuzione di un nuovo CF che sarà collegato all'attuale.
Saluti
N. Capozzi
