### ISSUE TITLE
C.I. da inserire non possibilie

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2291]
Buongiorno
soggetto ID ANPR 89036879 si è iscritto nel ns comune con un documento emesso dal Comune di Mappano il 13.4.2013.
Nella tabella dei comuni il comune presenta dt inizio 18.4.2018.
Contattato il contact center mi ha consigliato di sentire il comune di Mappano, che ha confermato che sono stati comune una prima volta per soli 28 gg nel 2013 e poi dal 2018.
Come posso inserire il documento al cittadino?
Grazie
Cordiali saluti
Ufficio Procedure Informatiche

**Comment by MassimoSchiappa** [comment]
Salve,
per il comune di Mappano, e per tutti i comuni in generale, ANPR si attiene a quanto riportato dalla fonte primaria dell'informazione sui comuni, cioè ISTAT. Le posso confermare che su ISTAT risulta che il 25/01/2013 è stato emesso il provvedimento L.R. N. 1 di costituzione del comune , ma che solo dal 18/04/2017 tale provvedimento ha acquisito validità amministrativa. Peraltro la data di inizio nella tabella dei comuni in ANPR è esattamente quella riportata come data inizio validità amministrativa da Istat e non, come da lei indicato, il 18/04/2018.
Per inserire in ANPR un dato diverso da quello attualmente presente relativamente al comune di Mappano è necessario che Istat ci dia comunicazione in questo senso. Quindi il comune dovrebbe scrivere ad Istat (ambienteterritorio@postacert.istat.it ) chiedendo la rettifica o l'integrazione dei dati in suo possesso sulla base di una documentazione allegata. Il sito pubblico di Istat su cui trovare queste informazioni è https://sistat.istat.it.
Cordiali saluti.
