### ISSUE TITLE
Unica famiglia anagrafica ma due ID scheda famiglia

### ISSUE THREAD

**Issue by kaccia** [italia/anpr#2292]
Dopo aver iscritto in ANPR un cittadino (IS) e i suoi due figli, per iscrizione da Comune non subentrato, mi sono accorto che ho saltato la prima lettera nel cognome dell cittadino (ARIN anzichè MARIN), generando la famiglia ID 52388510
Ho pertanto cancellato il cittadino "inesistente" (ID 92391182) su ANPR e iscritto nuovamente il cittadino con il giusto cognome (ID 94383210).
Purtroppo però tale operazione mi ha generato anche una nuova famiglia ID 54355471 con il risultato che adesso ho, su ANPR, allo stesso indirizzo due famiglie anagrafiche ma in realtà i componenti appartengono alla stessa.
Mi ritrovo pertanto la famiglia ID 52388510 senza IS, e la famiglia ID 54355471 senza figli.
La soluzione, TEORICA, sarebbe rettificare l' ID famiglia del cittadino ID 94383210, da ID 54355471 a ID 52388510, ma non so come fare e l'assistenza ANPR mi ha detto che loro non fanno assistenza in questi casi in quanto non compare errore alcuno! 
aiutooooo

**Comment by frmariani** [comment]
Non è possibile effettuare l'operazione che chiede, ma è possibile sistemare la situazione.
Invece di cancellare la cittadina, avrebbe dovuto annullare la sua iscrizione e rieseguirla con i dati corretti.

Ora può annullare l'operazione di iscrizione per altri motivi della cittadina (idoperazione anpr 333440321);
poi deve rieseguire l'Iscrizione per altri motivi della cittadina nella famiglia esistente idanpr 52388510.
Nel caso avesse bisogno di aiuto nell'eseguire le operazione, può inviarmi il suo recapito al seguente indirizzo 
frmariani@sogei.it

**Comment by kaccia** [comment]
> Invece di cancellare la cittadina, avrebbe dovuto annullare la sua iscrizione e rieseguirla con i dati corretti.

Si, infatti me lo aveva detto anche l'HALLEY. mentre il servizio assistenza ANPR, ieri pomeriggio mi ha semplicemene risposto che non essendoci un codice di errore non era un problema loro! :((

> Ora può annullare l'operazione di iscrizione per altri motivi della cittadina (idoperazione anpr 333440321);
> poi deve rieseguire l'Iscrizione per altri motivi della cittadina nella famiglia esistente idanpr 52388510.
> Nel caso avesse bisogno di aiuto nell'eseguire le operazione, può inviarmi il suo recapito al seguente indirizzo
> [frmariani@sogei.it](mailto:frmariani@sogei.it)
GRAZIE 1000 per il supporto, provo e faccio sapere

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
