### ISSUE TITLE
Modifica stato Irreperibilità

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2293]
COMUNE DI CAPONAGO (MB)

Varisco Maria Giuseppina

Quale metodo del WS ANPR deve essere invocato per modificare la stato di irreperibilità di un cittadino da TEMPORANEO A PERMANENTE ?

Grazie

**Comment by rvinzani** [comment]
In ANPR se un cittadino è irreperibile viene cancellato per irreperibilità. Tale stato rimane tale fintanto che non venga iscritto nuovamente.
