### ISSUE TITLE
Operazione in sospeso non esistente

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2294]
Buongiorno,
ambiente di produzione. Si sta effettuando una CANCELLAZIONE PER ALTRI MOTIVI, ma l'errore è il seguente:
EN203 Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2020-10-29 11:51:59 , idOperazioneANPR 361825850

Per entrambe i cittadini coinvolti nel procedimento, non esiste alcuna operazione sospesa.
Si precisa inoltre che uno due cittadini è già stato cancellato da un altro comune per doppia iscrizione.
Resto in attesa di un gradito riscontro
Cordiali Saluti

**Comment by frmariani** [comment]
per il cittadino idanpr 27755862 esiste un'operazione sospesa che deve essere eliminata con la seguente procedura:
Registrazione>Tipo di operazione: Mutazione tutti i dati>Iniziativa:operazione d'ufficio
Selezionando il link OPERAZIONI SOSPESE potrà eliminare l'operazione presente per il cittadino in questione.
Le ricordo che Lei visualizza soltanto le sue operazioni sospese, pertanto qualora non dovessero risultare sospensioni a suo carico , dovrà indagare tra i suoi colleghi

**Comment by frmariani** [comment]
ho verificato che l'operazione sospesa è stata eliminata. chiudo la issue
