### ISSUE TITLE
Data di nascita: solo anno

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2295]
Buonasera,
per un cittadino dobbiamo modificare la data di nascita che attualmente risulta "SOLO ANNO" e invece deve diventare completa.
Abbiamo fatto la modifica da webapp ma ci restituisce l'errore che allego.
[MOUMEN (1).pdf](https://github.com/italia/anpr/files/5459694/MOUMEN.1.pdf)
Come possiamo procedere?

Cordiali saluti

**Comment by frmariani** [comment]
Riprovi l'operazione per favore

**Comment by katiavacchi** [comment]
perfetto grazie, operazione riuscita.
