### ISSUE TITLE
[Webapp] risoluzione disallineamenti su cf collegato 

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2296]
Buongiorno. Problematica quasi identica al #2169 
Id cittadino 43654241.
In ANPR ha codice fiscale validato (CF1).
Deve cambiare le generalità: cognome; giorno; mese; anno di nascita.
Il nuovo codice fiscale (CF2) esiste già in AE, come cf indipendente.

Il Comune scrive a agenzia entrate che collega il CF1 a CF2, con le generalità esatte.

Ricevuta la risposta da Agenzia entrate, il Comune non riesce a cambiare le generalità ne da risoluzione disallineamenti, ne da mutazione.

**Comment by frmariani** [comment]
Per favore ripeta l'operazione di Mutazione

**Comment by MarcoMigliori** [comment]
Il Comune ha provveduto alla mutazione.
E' riuscita, con codice fiscale validato in ANPR. In AE risultava ancora "non marcato ANPR".
Hanno quindi fatto Risoluzione disallineamenti, che ha impostato come "marcato ANPR" il codice fiscale in AE.
