### ISSUE TITLE
[4005] scarico non ancora pronto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2297]
In ambiente di produzione abbiamo chiesto, per il comune di Bologna, lo scarico delle operazioni dal 6/6/2020 al 6/7/2020.
La richiesta, di ID ANPR 361520566, è stata eseguita ieri mattina alle 8:41
Al momento, dopo più di 24 ore, non risulta ancora pronta.
Come mai ?

**Comment by mttfranci** [comment]
Salve,  in effetti c'è stato un ritardo su quell'elaborazione, ma ci risulta che sia stata correttamente completata alle oggi 2020-10-30 14:12:32.
Potete verifcare?

**Comment by busaster** [comment]
I dati sono arrivato, grazie.
