### ISSUE TITLE
PREDISPOSIZIONE FILE PRE E SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2299]
COMNE DI CASERTA 061022
Buongiorno
"dimensione inferiore ai 15 MB"
si riferisce  alla dimensione del file .gz o a quello non compresso di partenza.
Grazie

**Comment by mttfranci** [comment]
Buongiorno, Il limite si riferisce al file dopo la compressione. Il file contenuto può avere anche dimensioni maggiori.
Saluti
