### ISSUE TITLE
AIRE –Attività di verifica dei dati Circolare Ministero Interno 12/2020

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2300]
Buongiorno,
ambiente di produzione, si presenta la casistica segnalata nell'allegato tecnico "AIRE Elenchi Anomalie -Soggetti con luogo nascita uguale alla denominazione di uno stato estero valido". Nella fattispecie, il cittadino 38745746 (e così altri cittadini AIRE iscritti), risultano nati nel Comune di LUSSEMBURGO, che corrisponde ovviamente alla stessa denominazione dello stato estero di nascita (LUSSEMBURGO).
Questi casi generano scarto, oppure l'elenco è da soprassedere?

Resto in attesa di gradito riscontro
Cordiali Saluti

**Comment by ncapozzi** [comment]
Buonasera,

la segnalazione "Soggetti con luogo nascita uguale alla denominazione di uno stato estero valido" non genera scarto ma deve essere verificata quando lo stato estero di nascita non è indicato ma è indicata la sola località = ad uno stato estero valido. 
Quando invece sono valorizzati sia lo stato estero che la località e sono uguali, in realtà la località dovrebbe contenere la città di nascita se conosciuta e non lo stato estero. In casi particolari di stati piccoli come il LUSSEMBURGO potete ignorare la segnalazione.

N. Capozzi

N. Capozzi
