### ISSUE TITLE
Acquisizione Scheda Anagrafica Cittadino in formato PDF

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2301]
COMUNE DI CAPONAGO
Varisco Maria Giuseppina

Buongiorno
volevo sapere se esiste un metodo del WS di ANPR per acquisire la scheda di un cittadino residente/non residente direttamente in formato PDF.

Resto in attesa di gentile riscontro.

Saluti

**Comment by rvinzani** [comment]
Buongiorno, no, la scheda di un cittadino in formato PDF è possibile stamparla solo dal sito web di ANPR

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni è possibile aprire una nuova issue che faccia riferimento a questa stessa
