### ISSUE TITLE
Estrazione elenchi anagrafici - operazione in lavorazione

### ISSUE THREAD

**Issue by DemResana** [italia/anpr#2302]
Comune di Resana - ambiente produzione

recentemente ho effettuato diverse estrazioni di elenchi cittadini.
In data 30/10/2020 ho richiesto una estrazione cittadini per codice comune, ultime tre cifre del protocollo ANPR 185.
Da allora non sono più riuscito a fare altre estrazioni perchè quest'ultima operazione risulta tuttora in lavorazione.

Cordiali saluti

Livio C.

**Comment by mttfranci** [comment]
Potete fornirci il protocollo completo per favore?

**Comment by DemResana** [comment]
No, purtroppo non l'ho segnato e non riesco a visualizzarlo.

Livio C.
Uffici Demografici

________________________________
COMUNE DI RESANA - NOTA DI RISERVATEZZA: Le informazioni contenute in questo messaggio di posta elettronica sono di natura confidenziale qualsiasi pubblicazione, utilizzo o diffusione anche parziale dello stesso non pu? essere effettuata senza la nostra autorizzazione e potrebbe costituire un illecito penale ai sensi della vigente normativa sulla Protezione dei Dati Personali. Qualora non siate i destinatari di questa email Vi preghiamo cortesemente di cancellarla dal Vostro sistema dopo aver notificato al mittente l'errore commesso.

**Comment by mttfranci** [comment]
Salve, si in effetti l'elaborazione, che dovrebbe essere la 362784185, ha avuto un problema.
Ora dovrebbe essere terminata con successo.
Potete riprovare?
Grazie in anticipo.

**Comment by DemResana** [comment]
Si confermo che l'elaborazione 362784185 è terminata con successo ed è ora possibile procedere ad altre estrazioni dati.

Cordiali saluti

Livio C.

Uffici Demografici
Comune di Resana - Provincia di Treviso

________________________________
COMUNE DI RESANA - NOTA DI RISERVATEZZA: Le informazioni contenute in questo messaggio di posta elettronica sono di natura confidenziale qualsiasi pubblicazione, utilizzo o diffusione anche parziale dello stesso non può essere effettuata senza la nostra autorizzazione e potrebbe costituire un illecito penale ai sensi della vigente normativa sulla Protezione dei Dati Personali. Qualora non siate i destinatari di questa email Vi preghiamo cortesemente di cancellarla dal Vostro sistema dopo aver notificato al mittente l'errore commesso.
