### ISSUE TITLE
procedura per sostituire l'ASL precedentemente nominato.

### ISSUE THREAD

**Issue by leopaul76** [italia/anpr#2303]
Buonasera,
qual'è la procedura da utilizzare per sostituire l'attuale Amministratore Locale della Sicurezza (ALS) assegnando tale ruolo ad un altro operatore comunale già inserito e attivo che attualmente ricopre il ruolo di Amministratore Locale della Postazione (ALP).
Resto in attesa di Vs. riscontro.
Grazie e cordiali saluti.
Comune di Valenza
per info 0131949210

**Comment by cmigliardi** [comment]
Buongiorno, 
l' ALS  del comune può  modificare in modo opportuno il profilo di tutti gli utenti censiti - quindi può cambiare anche quello del collega che ha già il profilo di ALP.  Tale profilo si può cambiare accedendo con la smart card alla web app di Anpr .  area Sicurezza - gestione utenti -

**Comment by leopaul76** [comment]
Buongiorno, grazie della risposta, tuttavia necessito di una specifica. 
Quando l'ALS entra nella gestione utenze e seleziona l'utente da modificare nella scheda "modifica utente/Visualizza" i profili disponibili sono quelli dell'allegato alla presente; quale occorre selezionare per far diventare l'utente selezionato nuovo Amministratore Locale della Sicurezza (ALS)?
![profili disponibili](https://user-images.githubusercontent.com/51747399/98088258-85d6e680-1e81-11eb-8f2d-480269f46b48.jpg)

**Comment by cmigliardi** [comment]
l
a chiamo

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
