### ISSUE TITLE
ISCRIZIONE NUOVO UTENTE E RICHIESTA SMART CARD

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2304]
Buonasera,
COMUNE DI CASERTA 061022

Abbiamo la necessità di inserire una nuova utenza e richiedere la relativa smart card.
nell'effettuare le operazioni previste viene sempre mostrare l'errore di scegliere un profilo ma nel campo relativo non si apre il menu a tendina per la scelta.
Le operazioni vengono eseguite da ALS
Grazie

**Comment by cmigliardi** [comment]
Buongiorno,  per poter  censire un nuovo utente - occorre accedere  alla web app di ANPR e lo può fare   solo chi ha il ruolo di ALS  cioè  Amministratore  Locale della sicurezza -  ma dalle verifiche  nessun utente censito per il vostro comune ha questo profilo.  Questo è il motivo per il quale non si apre il menu a tendina.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
