### ISSUE TITLE
Procedimento aperto comune di origine

### ISSUE THREAD

**Issue by anagrafemaiori** [italia/anpr#2305]
Salve,
al fine di iscrivere una famiglia nella nostra Apr, riceviamo un errore:

1 Errore Anpr Cod: EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune TAVIANO (LE) con numero pratica ANPR: 30045779 - Id Famiglia/Convivenza ANPR: 43024523 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-04 09:44:37 , idOperazioneANPR 365605731 - Id Famiglia/Convivenza ANPR: 43024523 Id Famiglia/Convivenza Comune: -

Contattato il Comune di Taviano ci hanno detto che non esiste un procedimento aperto 

Come possiamo sbloccare la situazione?

Grazie

**Comment by frmariani** [comment]
sono in attesa di una risposta dal comune di Taviano; Le farò sapere quanto prima

**Comment by frmariani** [comment]
riprovi per favore, il procedimento dovrebbe essere chiuso

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
