### ISSUE TITLE
Invocazione Servizio 6001 Certificazione

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2306]
COMUNE DI CAPONAGO

Buongiorno
quando emettiamo un certificato con la WA di ANPR, una delle richieste che dobbiamo valorizzare è : PAGAMENTO BOLLO, che può assumere i seguenti valori :: Assolto in maniera virtuale, Contrassegno, Altro.
Volevamo sapere quale parametro nel Servizio 6001 è necessario utilizzare per passare questo valore.
Grazie

**Comment by rnapoli1983** [comment]
Buonasera,

nel servizio 6001 il corrispettivo parametro per indicare i possibili valori è il campo "bolloVirtuale" presente nell'oggetto "datiControllo" (esempio) :

![image](https://user-images.githubusercontent.com/30468060/98129548-89865f80-1eb9-11eb-97c0-87d024c06884.png)

Rimango a disposizione.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

non so se avete risolto il problema segnalato.

Chiudo la issue, nel caso potete riaprila quando volete e vi risponderemo il più presto possibile.

Grazie mille.

Cordiali saluti.
