### ISSUE TITLE
PRE-SUBENTRO  VALIDAZIONE CODICE FISCALE 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2307]
Buongiorno,
COMUNE DI CASERTA 061022
Inviati file pre-subentro e prelevati file con errori.
Abbiamo consultato una serie di schede anagrafiche, non presenti negli errori,  risultano tutti con indicazione "CODICE FISCALE NON VALIDATO"
Motivo?
Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
cortesemente mi può scrivere   cmigliardi@sogei.it   o inviarmi un recapito così possiamo  sentirci? e vedere i dettagli? La ringrazio

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
