### ISSUE TITLE
Descrizione ente nella intestazione dei Certificati - "Città di " in luogo di "Comune di"

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2308]
Come già richiesto per il comune di Frosinone con al ISSUE
https://github.com/italia/anpr/issues/516

Il comune di Tortona si fregia del titolo di "Città" ed utilizza questa dizione anche nella intestazione dei documenti prodotti, certificati anagrafici compresi. 

Grazie

**Comment by rnapoli1983** [comment]
Buongiorno,

potreste riprovare ad emettere un certificato anche modalità "anteprima" e vedere se il testo che appare è quello desiderato ?

Attendo un vostro riscontro.

Grazie mille.

Cordiali saluti

**Comment by rnapoli1983** [comment]
Buongiorno,

non so se avete risolto il problema segnalato.

Chiudo la issue, nel caso potete riaprila quando volete e vi risponderemo il più presto possibile.

Grazie mille.

Cordiali saluti.
