### ISSUE TITLE
[5012] L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2309]
Salve, Siracusa ambiente di produzione

Nel tentativo di annullare da applicativo una mutazione dati id Anpr 299009354 si riceve 

L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa; Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-04 13:04:09 , idOperazioneANPR 365934894; 

Non abbiamo riscontrato operazioni successive da annullare nè sull'individuo nè sui membri della famiglia.

**Comment by frmariani** [comment]
Dovreste eliminare l'operazione idanpr 317153009 con cui è stato acquisita l'informazione del matrimonio per entrambi i coniugi

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
