### ISSUE TITLE
Sedime "Lungo Dora"

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2310]
Buongiorno
nel ns comune è presente il sedime "Lungo Dora" staccato, mentre in ANPR è presente "LungoDora" attaccato: al fine di evitare disallineamenti con la Toponomastica locale è possibile inserire la voce "Lungo Dora" staccata?
Grazie
Cordiali saluti
Ufficio Procedure Informatiche

**Comment by MassimoSchiappa** [comment]
Salve,
immagino si tratti di denominazioni di vie di Torino, corretto? 
Attualmente ANPR assume per la toponomastica dei comuni le indicazioni inviate dai comuni stessi nel contesto degli indirizzi specificati per le residenze.
Cordiali saluti.

**Comment by UpiTorino** [comment]
Buongiorno
riprendo questa segnalazione per far presente che in sede di subentro fu inviata la descrizione "Lungo Dora" staccato.
E' possibile che qualche altro comune che possiede "Lungo Dora" l'avesse nella forma  "LungoDora" attaccato, per cui è stato modificato?
Grazie
Cordiali saluti
