### ISSUE TITLE
Invocazione Servizio A006 per mutazione residenza estera - errore

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2312]
COMUNE DI CAPONAGO
Varisco maria Giuseppina

Abbiamo invocato il servizio A006 per modificare l'indirizzo di residenza estera di un cittadino AIRE (GATTI ALESSANDRO MARIO)
di fatto è stata modificata solo la data di decorrenza della residenza, ma non i dati relativi all'indirizzo.
Non riusciamo a capire quale sia il problema, visto che non viene restituito alcun errore si allega il file richiesta ed il file esito.

Resto in attesa di gentile riscontro.
Saluti

[RichiestaA006.txt](https://github.com/italia/anpr/files/5489109/RichiestaA006.txt)
[EsitoWS_RichiestaA006.txt](https://github.com/italia/anpr/files/5489110/EsitoWS_RichiestaA006.txt)

**Comment by ncapozzi** [comment]
Buongiorno,
per modificare l'indirizzo (italiano o estero) di una intera famiglia che si sposta si deve utilizzare il WS 5001 mutazione famiglia/convivenza con tipo mutazione 4 - RESIDENZA SCHEDA anche se la famiglia è composta da un solo cittadino.

A006 deve essere utilizzato per spostare un cittadino da una famiglia ad un'altra già esistente oppure in una nuova famiglia. Nel vostro caso il servizio avrebbe dovuto restituire un errore. Verificheremo come mai questo non è avvenuto.

Due suggerimenti
- nelle richieste identificate sempre i cittadini e le famiglie con gli idANPR (nell'esempio in oggetto sono presenti solo quelli comunali che in ANPR sono meno significativi)
- non indicare mai i dati dei cittadini nelle ISSUES e non allegare le richieste. E' sufficiente indicare l'idANPR dell'operazione per la quale richiedete assistenza e l'idsoggettoANPR

Grazie
N. Capozzi
