### ISSUE TITLE
[4005] tag idOperazioneANPR in elencoRisposte con valore anomalo

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2313]
In ambiente di test abbiamo eseguita da webapp una mutazione altri dati (id ANPR 31309996).
Abbiamo poi usato il servizio 4005 per scaricarla in locale.
Nell'elenco delle risposte negli esiti della 4005 (id operazione ANPR 31310333) troviamo la modifica da webapp ma nel tag   **idOperazioneANPR** del relativo blocco **elencoRisposte** è presente il valore 31310004 mentre ci aspettavamo 31309996.

Come mai ?

**Comment by mttfranci** [comment]
Salve, perchè voi avete richiesto le NRIS.
La NRIS con id 31310004 è relativa all'operazione 5008 con id 31309996.
Le NRIS sono operazioni separate anche se contengono la risposta di una operazione ANPR.
Siamo a disposizione per qualsiasi ulteriore chiarimento.
Saluti

Assistenza ANPR

**Comment by busaster** [comment]
Ok ora mi è chiaro. Grazie
