### ISSUE TITLE
Richiesta Smart Card

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2314]
Comune di Mirabella Eclano (AV)

Dovremmo richiedere nuove Smart Card perché le precedenti sono andate smarrite (tutte, compresa quella del Sindaco).
Come procediamo?

Grazie.

**Comment by vix-db** [comment]
Appena inviata.
Grazie!

**Comment by vix-db** [comment]
Per la seconda metà del PIN del Sindaco bisogna inviare una mail a segnalazioni-anpr@teamdigitale.governo.it?

**Comment by Leonforte** [comment]
Salve, abbiamo già risposto alla segnalazione pervenuta al team con il testo in calce. 

In relazione alla segnalazione in calce si informa che la seconda metà delle credenziali sarà rinviata all’indirizzo mail fornito all’atto di censimento unitamente al primo certificato di postazione :

sindaco@comune.mirabellaeclano.av.it

Cordiali saluti
Assistenza ANPR
