### ISSUE TITLE
Riferimento Issue #2312 - per cambio residenza aire

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2315]
Buongiorno
abbiamo invocato come suggerito il servizio 5001 :: ecco l'errore

<errore>
                        <codiceErroreAnomalia>EF002</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata</testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-06 09:25:53 , idOperazioneANPR 367300909</testoErroreAnomalia>
                    </errore>

restiamo in attesa di gentile riscontro.
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
nell'oggetto famiglia del 5001 è indicato TipoScheda = 3 che indica una famiglia residente in Italia, per le famiglie AIRE è necessario indicare 5.
