### ISSUE TITLE
Correzione data di morte

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2316]
Comune di S.Angelo dei Lombardi (AV)

E' stato registrato su ANPR un decesso (idOperazione 364451466) del cittadino 79432265 con un errore nella data di decesso.
Qual è la procedura corretta per annullare/correggere il dato?

Grazie.

**Comment by azabatta** [comment]
Buongiorno, 
è possibile rettificare la data decesso con la funzionalità di "Mutazione tutti i dati"  (ws 5008) - tipo mutazione "rettifica dati decesso"  (codice 22).
Per segnalazioni di tipo procedurale si suggerisce di avvalersi del servizio di assistenza ANPR al numero 800863116.
