### ISSUE TITLE
SPECIFICHE_DI_INTERFACCIA_XSD

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2317]
Buongiorno, l'ultima versione degli XSD e WSDL è quella del 19/05/2020 pubblicata nella pagina "https://www.anpr.interno.it/portale/documentazione-tecnica"   (SPECIFICHE_DI_INTERFACCIA_XSD_19052020.rar) ? Grazie

**Comment by mttfranci** [comment]
Salve.
Si esatto.
L'ultima versione è quella indicata.
Saluti

**Comment by Eduardo1977** [comment]
Grazie per il riscontro.
Buona serata

**Comment by mttfranci** [comment]
Prego. Buona giornata.
