### ISSUE TITLE
Invocazione servizio 6001 : risposta

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2318]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
invocando il servizio 6001 Certificazione otteniamo in risposta un file XML con il seguente tag

<file>
-<certificatoPdf>

<xop:Include href="cid:e058069683c6e422a78c1add8b17062f604cacd881d3659e@apache.org" xmlns:xop="http://www.w3.org/2004/08/xop/include"/>

</certificatoPdf>
</file>

La documentazione tecnica non indica com'è possibile leggere/scaricare questo file pdf. E' possibile avere delle indicazioni in merito ? 

Grazie

**Comment by rnapoli1983** [comment]
Buongiorno,

l'oggetto, da voi descritto, che viene restituito dal servizio 6001 di certificazione anagrafica è il file pdf, del certificato stesso prodotto, sotto forma di array di byte.

Per leggerlo/scaricarlo, dall'oggetto response del servizio, potete fare una cosa simile alla seguente:

![image](https://user-images.githubusercontent.com/30468060/98529281-b651c280-227d-11eb-9162-3a852e058f1d.png)

![image](https://user-images.githubusercontent.com/30468060/98529333-c5d10b80-227d-11eb-84e0-5227d62ecb92.png)

Non è stato documentato in quanto le operazioni di lettura e download di un array di byte sono realizzabili secondo i metodi standard.

Rimango a disposizione.

Cordiali saluti.

**Comment by GabriellaBallabio** [comment]
Scusi 
ma otteniamo come risposta il file xml allegato 
[CL SPORTELLO EsitoWS_Richiesta6001.txt](https://github.com/italia/anpr/files/5510788/CL.SPORTELLO.EsitoWS_Richiesta6001.txt)

Dal questo fino ad arrivare alle sue function .... è questo pil pezzo che ci manca ...

**Comment by rnapoli1983** [comment]
Buongiorno,

nel client che, immagino abbiate implementato per fare la chiamata al servizio 6001, in risposta avete un oggetto che è Risposta6001 e che contiene tutti i dati dell'xml che avete inviato.

Glie esempi di codice inviati, come uno dei modi per leggere/scaricare il file, vanno applicati a questo oggetto di risposta.

**Comment by rnapoli1983** [comment]
Buongiorno,

non so se avete risolto il problema segnalato.

Chiudo la issue, nel caso potete riaprila quando volete e vi risponderemo il più presto possibile.

Grazie mille.

Cordiali saluti.

**Comment by GabriellaBallabio** [comment]
Buongiorno
purtroppo non abbiamo ancora risolto.

la risposta che noi otteniamo è contenuta nel file value.txt allegato. Abbiamo isolato i byte del certificato (certifbyte.txt allegato) ma quando convertiamo otteniamo un file pdf vuoto/bianco (mio.pdf allegato)

Noi sviluppiamo in vb.net , di seguito il codice che utilizziamo

Dim bdata As Byte() = File.ReadAllBytes("value.txt")
 Dim oWrite As System.IO.StreamWriter
        oWrite = File.CreateText("mio.pdf")
        oWrite.WriteLine(base64Decoded)
        oWrite.Close()

[mio.pdf](https://github.com/italia/anpr/files/5535756/mio.pdf)

[certifbyte.txt](https://github.com/italia/anpr/files/5535751/certifbyte.txt)

[value.txt](https://github.com/italia/anpr/files/5535738/value.txt)

Se poteste esserci utili vi saremmo grati.

**Comment by rnapoli1983** [comment]
Buongiorno,

purtroppo non possiamo entrare nel merito delle singole implementazioni client delle singole sw house anche perchè per noi non sarebbe possibile.

Quello che non mi convince, dal fragment di codice mostrato, è che essendo il file finale un pdf il passaggio con file .txt non credo sia corretto.

Nel nostro codice noi prendiamo direttamente il byte array dall'oggetto di Risposta del servizio e lo reindirizziamo sull'HttpResponse.

Comunque anche per il linguaggio vb.net, in rete si trovano molti esempi standard di come effettuare queste operazioni.

Rimango a disposizione.

Cordiali saluti
