### ISSUE TITLE
Estrazione elenchi anagrafici-formato identificativo comunale

### ISSUE THREAD

**Issue by DemResana** [italia/anpr#2319]
Comune di Resana

Procedendo all'estrazione di un elenco cittadini con parametri "Identificativo comune Da: 3" - "Identificativo comune A: 3307", protocollo ANPR 356546284, il sistema ha restituito solo gli identificativi comunali che iniziano per 3 (3, da 30 a 39, da 300 a 399, da 3000 a 3307) omettendo tutti gli altri identificativi.
Si chiede quale sia il formato corretto da inserire nel campo "Identificativo comune" per ottenere tutti gli identificativi compresi nell'intervallo.
Sempre nella predetta estrazione era anche stato inserito il parametro "solo residenti in Italia", ma il sistema ha incluso anche alcuni AIRE.

Cordiali saluti

Livio C. - Uffici Demografici

**Comment by mttfranci** [comment]
Salve, l'identificativo comunale (a differenza dell'identificativo ANPR) è una stringa, pertento ordinamento e intervalli seguono le regole delle stringhe.
Quindi il funzionamento appare corretto.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
