### ISSUE TITLE
Riferimento issue #2309

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2320]
Salve, 
abbiamo verificato che non esiste nessuna operazione per l'individuo di competenza del Comune di Siracusa con idAnpr 317153009
Pertanto non riusciamo ancora ad annullare l'operazione con id Anpr 299009354

Il Comune ha urgenza di annullare questa operazione, per poter poi annullare la 299005930 e poi poter chiudere negativamente il procedimento della 294297615 e permettere l'iscrizione dell'individuo ad un altro comune

Grazie

**Comment by frmariani** [comment]
Anche se i coniugi vivono in due comuni diversi, condividono le informazioni sul matrimonio; non è possibile annullare le vostre operazioni idanpr 299009354 e 299005930 se prima il comune di Floridia non annulla l'operazione idanpr 317153009 effettuata successivamente sullo stesso matrimonio.
L'alternativa potrebbe essere quella di cancellare il cittadino; 
se vuole può scrivermi in privato un recapito telefonico dove posso raggiungerla
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
