### ISSUE TITLE
Entra con CIE non funziona

### ISSUE THREAD

**Issue by ocampana** [italia/anpr#2321]
Volevo segnalare, sperando che sia il posto giusto, che nel sito https://www.anpr.interno.it/portale/a-cittadini non funziona il bottone "Entra con CIE".

Il messaggio di errore è

```xml
<env:Envelope>
  <env:Body>
    <env:Fault>
      <faultcode>env:Client</faultcode>
      <faultstring>Rejected by policy. (from client)</faultstring>
    </env:Fault>
    </env:Body>
</env:Envelope>
```

**Comment by gife67** [comment]
Buongiorno,
Il servizio è funzionante, probabilmente ha dei problemi con il driver del lettore di CIE, che è diverso da un normale lettore di smartcard, in quanto deve supportare il protocollo RFID. L'errore riscontrato è dovuto al fatto che non viene trasferito il certificato presente sulla CIE. Quando si sta utilizzando il driver corretto, prima dell'accesso al sito dovrebbe compararle una finestra in cui le viene richiesto il PIN della CIE, sicuramente a lei questa finestra non le è stata presentata, sintomo che c'è qualcosa che non va nell'installazione del lettore o dei driver della CIE.
Provi a verificare se riesce a collegarsi a qualche altro sito che permette l'accesso CIE, in modo da aver un ulteriore riscontro sulla problematica.
Attendo un suo riscontro.
Cordiali saluti

**Comment by ocampana** [comment]
Essendo la mia carta d'identità una CIE 3.0 pensavo di usare lo smartphone con la modalità di autenticazione ibrida pc con telefonino (vedasi pagina 9 di https://www.cartaidentita.interno.gov.it/CIE3.0-ManualeSP.pdf ).

Il login con questo scenario mi funziona dal PC sul sito dell'inps.

**Comment by gife67** [comment]
Questo modalità di accesso è stata attivata ancora prima che venisse implementata la soluzione oggetto del documento allegato.
Attualmente la modalità di accesso CIE è equiparata a quella di una CNS, quindi viene implementata direttamente una mutual authentication con il certificato a bordo della CIE verso il portale ANPR senza il coinvolgimento di un IDP. Attualmente l'unica possibilità è quella da desktop, utilizzando i driver CSP pubblicati su GitHub e con un lettore RFID. Stiamo lavorando per permettere l'accesso secondo le modalità previste sul manuale CIE 3.0.
Mi dispiace.

**Comment by gife67** [comment]
Buonasera,
chiudo questa issue, per qualsiasi altra informazione rimango a disposizione, nel caso avesse bisogno può aprirne una nuova collegandola a questa.
