### ISSUE TITLE
[5001] Cambio indirizzo con falso esito positivo - Rif. #2269

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2322]
Comune di Torino - Ambiente di produzione

Buongiorno,
è capitato lo stesso identico problema della issue #2269 , con la differenza che il servizio di partenza è un 5001 anziché un 5005.
E' stato effettuato un cambio di indirizzo per tre soggetti, ma per il soggetto avente ID ANPR 28680772 non è stata aggiornata la scheda Residenza nonostante il 5001(id 368516629) abbia dato esito positivo. La volta scorsa l'assistenza telefonica aveva consigliato agli operatori comunali di annullare i 5008 partiti successivamente al 5005 ed effettivamente la scheda si era aggiornata.
Per questa casistica le mutazioni 368516660 e 368517210 non sono state annullate volutamente per sottoporvi la questione. 
Rimaniamo in attesa di cortese riscontro.

Chiara Leanza
per il Comune di Torino

**Comment by UpiTorino** [comment]
Buon pomeriggio,
segnalo analoga situazione per il soggetto con id anpr 28783077.
Domani annullerò le mutazioni scheda con id 336248055 ed id 336248128, in quanto l'errata visualizzazione, inibisce un servizio di certificazione (TorinoFacile).
Cordiali saluti
Floramo S.
UpiTorino

**Comment by rvinzani** [comment]
Il problema del disallineamento si è generato precedentemente la mutazione famiglia/convivenza in quanto sono state effettuate due operazioni (mutazione tutti i dati/cambio di residenza) pervenute al sistema ANPR simultaneamente.
Come già indicato in precedenza, i servizi ANPR relativi lo stesso soggetto devono essere richiamati in sequenza attendendo l’esito di ogni servizio

**Comment by CSI-Piemonte-Demografia** [comment]
Le nostre chiamate sono asincrone, quindi non attendiamo la prima risposta per inviare la richiesta successiva. Non c'è proprio alcun modo per sanare questo problema di visualizzazione su ANPR?

**Comment by rvinzani** [comment]
Purtroppo non è un problema di visualizzazione. La chiamata simultanea di due servizi sulla stessa scheda anagrafica comporta una inconsistenza negli archivi. L'architettura prevede la gestione parallela dei servizi ovviamente ma non sulla stessa scheda anagrafica anche perchè l'esito di una chiamata a servizio è determinante per la chiamata successiva

**Comment by CSI-Piemonte-Demografia** [comment]
Capisco. A questo punto, però, ci saremmo aspettati un KO dal servizio, non un OK. Abbiamo parlato di problemi di visualizzazione in quanto è stata proprio l'assistenza telefonica a farlo presente.

**Comment by rvinzani** [comment]
Non è un problema di visualizzazione. Purtroppo già in passato abbiamo è stato fatto presente questo problema nell'architettura del vostro gestionale. Il KO prevederebbe che queste situazioni fossero gestite ma ciò non è possibile.

**Comment by CSI-Piemonte-Demografia** [comment]
La ringrazio molto per il tempo dedicato alla richiesta. Valuteremo con il Comune il da farsi.
Buona giornata
