### ISSUE TITLE
immigrazione con CF attribuito da AE

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2323]
Salve,
per il comune di Baragiano (PZ) (cod istat: 076010) stiamo perfezionando una pratica di immigrazione dall'estero per una cittadina il cui codice fiscale è già stato attribuito precedentemente da AE (il C.F. termina con ...Z135C. La persona è nata il: 18/06/1989). Durante l'invio in ANPR riceviamo un errore per il nome dello stato di nascita non congruente con la descrizione RUSSIA. L'id operazione è: 369108243 effettuata alle: 15:48:45 del 2020-11-09. Possiamo avere indicazioni per la risoluzione di tale problema

**Comment by ncapozzi** [comment]
Buonasera,
il CF indicato nella richiesta è errato in quanto termina con Z145C invece di Z135C. Inoltre la cittadina è registrata su Agenzia delle Entrate come nata in URSS. Non essendo l'URSS censito nella tabella stati di ANPR che non ha lo storico, lo stato di nascita deve essere indicato bella richiesta 1002 utilizzando il codice 998 non attribuibile.
<descrizioneStato>URSS</descrizioneStato>
<codiceStato>998</codiceStato>
Infine per richiedere la validazione del CF contestualmente all'iscrizione nei dati di controllo dovete impostare gestioneCF = 0 (avete trasmesso 3 che salta la validazione CF)

**Comment by carminepat** [comment]
Abbiamo proceduto all'invio con il codice 998 e siamo riusciti a superare quella validazione. Attualmente comunque, per questa stessa pratica ci dice che il coniuge risulta coniugato con un'altra persona alla data. idoperazione: 369423853 (verificando il coniuge dalla WEBAPP risulta essere coniugato con la persona che stiamo inviando)
Come possiamo risolvere?

**Comment by ncapozzi** [comment]
Buongiorno,
la Sig.ra che state iscrivendo è nata il 1989-06-18. Sulla scheda del marito che è già in ANPR invece la coniuge è nata il 18/06/1986. Suggerisco di correggere la data di nascita del coniuge nella scheda matrimonio del marito prima di iscrivere la moglie
