### ISSUE TITLE
[5008]  Conferma Immigrazione

### ISSUE THREAD

**Issue by CaligiuriAn** [italia/anpr#2324]
Buonasera,
al comune di Cropalati durante la conferma di una pratica di Immigrazione (45 giorni) mi restituisce la seguente anomalia:

_"La data decorrenza 05-03-2020 dell'operazione non puo' essere inferiore alla data decorrenza errore da GET_CARTA_IDENTITA esito:999 dell'ultima operazione effettuata sui dati relativi a @"_

Grazie, cordiali saluti
Caligiuri Antonio (IFM Calabria)

**Comment by frmariani** [comment]
Per favore ripetete l'operazione. Grazie

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
