### ISSUE TITLE
Tabella 15 Motivo Cancellazione 8 Trasferimento di residenza (iscrizione AIRE)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2326]
Buongiorno
Un paio di anni fa si era stabilito nella issue #498 di eliminare questo motivo. Non so se ci sono altri interventi che mi sono sfuggiti.
Lo trovo tuttora presente nelle tabelle. Qualora sia presente solo per compatibilità con registrazioni già fatte, si può aggiungere "Deprecato" sulla tabella o nota simile?
Viceversa qualora fosse presente perchè necessario, vi chiederei di esplicitare in quali casi va usato. Grazie in anticipo.

**Comment by ncapozzi** [comment]
Buonasera,
il motivo 8 in effetti è presente solo per compatibilità con registrazioni già fatte. Pertanto, se non ci sono obiezioni, pensiamo di aggiornarlo aggiungendo la notazione "Obsoleto" sulla tabella della basedati di ANPR e di eliminarlo completamente dalla tabella 15 in formato xls pubblicata su www.anpr.interno.it

**Comment by ncapozzi** [comment]
Buonasera,
non essendoci state obiezioni, il motivo 8 è stato eliminato completamente dalla tabella 15 in formato xls pubblicata su www.anpr.interno.it.

N. Capozzi
