### ISSUE TITLE
Gestione Anagrafe Temporanea 

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#2328]
Buongiorno,

volevo chiedere se ad oggi ci fossero novità in merito alla gestione dei dati dell'anagrafe temporanea tramite web services o se la funzionalità è sempre e solo disponibile dalla WebApp.

Grazie
Marco Sala

**Comment by rvinzani** [comment]
Buon pomeriggio, nessuna novità per il momento

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
