### ISSUE TITLE
MANCATO ACCESSO CON SMART CARD NUOVE

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2329]
Buongiorno, apro questo ticket per il nostro Cliente COMUNE DI NOVELLA Referente Sig.ra LORENZA ANSELMI 0463 463113 - int. 2
Hanno ricevuto le nuove smart card in agosto, ma nonostante le varie prove di installazione del nuovo sw SAFEDRIVE come da specifiche in rete, non si riesce a fare l'accesso in web app.
Abbiamo provato su due pc diversi, con stesse caratteristiche W10, e anche configurando firefox (sempre seguendo le vostre specifiche) non si riesce ad accedere, vengono letti i certificati ma poi il browser (chrome e firefox) segnala il seguente errore:

ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

Il nostro cliente ha anche aperto un ticket al nr verde 800863116 ed è il nr 21255194 del 09/11/2020 - è possibile contattarli con urgenza ? Sarebbero pronti a fare il PRESUBENTRO in ANPR. 

Grazie 
Cordiali saluti 

Cinzia Girelli
 HR – HD DEPLOY E PIATTAFORMA C. +39 3346216774 | T. +39 0461 381 515 int. 7576 Gruppo GPI I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599 
 www.gpi.it

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, mi ricollego a questo ticket ancora aperto, nel frattempo siamo riusciti a risolvere poichè vi era un pin errato. Ieri abbiamo fatto il subentro, oggi il comune riaccedendo con stessa smart card e browser Firefox non riesce a collegarsi. 
Il browser Firefox si è aggiornato alla versione 84, digitando l'indirizzo chiede il PIN inserendolo si blocca. 
Questo succede anche con smart card del commissario con cui volevano fare la richiesta di contributo. Inoltre firefox si blocca e non risponde più.  
Controllando i certificati dalle opzioni internet sono presenti i CF nella cartella Altri Utenti. Domanda: si possono corrompere le smart card durante l'utilizzo? questo problema indica una qualche anomalia sulla smart card stessa? 

Ultimamente con i nostri clienti del Trentino rileviamo numerosi problemi legati alle smart card nuove.

**Comment by Leonforte** [comment]
Buongionro, è imporobabile che le sc si corrompano durante l'utilizzo. Se è passato l'aggiornamento su firefox sarebbe utile installare nuovamente safedive o dike go sign, sempre che le sc siano quelle nuove, saluti

**Comment by CGIRELLI-HUB** [comment]
Si certo le sc sono quelle nuove. Proveremo così grazie

**Comment by CGIRELLI-HUB** [comment]
Buongiorno,
questa mattina ho provato a reinstallare il safedrive ma non è cambiato
nulla. Le Smart Card attive del comune sono quelle nuove. L'utente non
riesce più ad accedere.
Abbiamo quindi provato con un altro pc, siamo entrati con Google Chrome al
1° tentativo il pin è stato richiesto su maschera di ACS CCID USB Reader e
quindi non ha dato l'accesso, al 2° tentativo ha mostrato la maschera di
inserimento PIN di SAFEDRIVE e quindi siamo entrati. Questa prova l'abbiamo
fatta con smart card del sindaco. Quindi abbiamo provato con smart card
della responsabile LORENZA ANSELMI e di nuovo non rileva il SAFEDRIVE legge
i certificati ma chiede il PIN di nuovo su ACS CCID USB Reader. Abbiamo
riprovato con smart card del sindaco e non c'è stato più modo di rientrare.

Ora, questo è un comportamento assai strano. Inoltre con Firefox continua a
persistere un problema di crash del sw anche da questa macchina, dopo la
configurazione inserendo una delle due tessere si pianta tutto e non è
possibile accedere nonostante la configurazione a nostro avviso corretta.

Vi prego di sentire l'utente per eventuali ulteriori indicazioni:  LORENZA
ANSELMI 0463-432113 int. 2

Grazie

Cordiali saluti


       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno mer 23 dic 2020 alle ore 12:18 Leonforte <notifications@github.com>
ha scritto:

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, su un pc ho risolto togliendo il modulo asepkcs.dll nonostante
il browser firefox era aggiornato alla versione 85.
Funziona solo con il modulo bit4xpki.dll

Grazie

       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 11 gen 2021 alle ore 11:16 Leonforte <notifications@github.com>
ha scritto:
