### ISSUE TITLE
Incongruenza dati tra response Servizio 3002 e stampa scheda cittadino da WA

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2331]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
si presenta un'incongruenza tra i dati che otteniamo con il servizio 3002 e la stampa della scheda che esegue la WA di ANPR.
Abbiamo effettuato una ricerca cittadino 

<operazioneRichiesta>3002</operazioneRichiesta>
<dataOraRichiesta>2020-11-03T11:00:00+01:00</dataOraRichiesta>
<idOperazioneANPR>364668798</idOperazioneANPR>

ottenendo

-<legameSoggetto>
<tipoLegame>5</tipoLegame>   (3=famiglia;4=convivemza;**5=famigliaAIRE**)
<dataDecorrenza>2020-01-31+01:00</dataDecorrenza>
<codiceLegame>3</codiceLegame> (tabella 6 Legame - Scheda convivenza o tabella 05 relazione di parentela ) [FG]
</legameSoggetto>

Se effettuiamo la stampa della scheda da WA di ANPR risulta 

**Legame di parentela con l’intestatario della scheda famiglia Altro**

Potete verificare la causa ? Sarebbe spiacevole il verificarsi di questa anomalia per altri dati la cui importanza potrebbe essere differente.

Restiamo in attesa. Grazie

**Comment by rvinzani** [comment]
Potete indicarci l'id dell'operazione o l'idanpr del soggetto? State parlando dell'ambiente di produzione

**Comment by GabriellaBallabio** [comment]
Ambiente di produzione comune di caponago (MB)

dataOraRichiesta 2020-11-03T11:00:00+01:00
idOperazioneANPR 364668798

idSchedaSoggettoANPR 86271008

**Comment by GabriellaBallabio** [comment]
Ad integrazione dell'issue  #2331 abbiamo rilavato un'altra incongruenza 

operazioneRichiesta 3002
dataOraRichiesta 2020-11-13T09:10:00+01:00
idOperazioneANPR 372316715

Invocando il WS 3002 per il cittadino residente a CAPONAGO ed unito civilmente, ottineamo una risposta senza i dati dell'unione civile e senza i dti dell'unito che fa parte dell'unione, mentre se stampiamo la scheda individuale dalla WA di ANPR i dati sono prresenti.

idSchedaSoggettoANPR 72839538

**Comment by rvinzani** [comment]
E- sufficiente inserire nella richiesta 3002 il tipo di richiesta 1 che prevede tutti i dat

**Comment by GabriellaBallabio** [comment]
Mi scusi ma il tipo richiesta = 1 è già indicato ... allego xml richiesta 
[Richiesta3002.txt](https://github.com/italia/anpr/files/5537104/Richiesta3002.txt)

**Comment by rvinzani** [comment]
Deve inserire  solo tipo di richiesta 1 e basta oppure la lista delle sezioni. In particolare la sezione da indicare credo sia la 32.

**Comment by GabriellaBallabio** [comment]
Buongiorno
lei mi scrive "E- sufficiente inserire nella richiesta 3002 il tipo di richiesta 1 che prevede tutti i dati" , in realtà non è cosi' se inserisco solo il tipo richiesta il ws risponde 
codiceErroreAnomalia EN052
tipoErroreAnomaliaE
testoErroreAnomaliaOccorre specificare i dati da interrogare

Allego richiesta e risposta
[Richiesta3002.txt](https://github.com/italia/anpr/files/5547172/Richiesta3002.txt)
[EsitoWS_Richiesta3002.txt](https://github.com/italia/anpr/files/5547175/EsitoWS_Richiesta3002.txt)

Aggiungerò tutte le sezioni.
Grazie

**Comment by rvinzani** [comment]
Di seguito la richiesta corretta
--	<soapenv:Body>
--		<ns2:Richiesta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione">
--			<testataRichiesta>
--				<idOperazioneComune>0</idOperazioneComune>
--				<codMittente>999999</codMittente>
--				<codDestinatario>ANPR00</codDestinatario>
--				<operazioneRichiesta>3002</operazioneRichiesta>
--				<dataOraRichiesta>2016-10-30T12:46:44.125+01:00</dataOraRichiesta>
--				<tipoOperazione>C</tipoOperazione>
--				<tipoInvio>TEST</tipoInvio>
--			</testataRichiesta>
--			<criteriRicerca>
--				<codiceFiscale>AAABBB10X10H501X</codiceFiscale>
--			</criteriRicerca>
--			<datiRichiesta>
--				<schedaAnagraficaRichiesta>1</schedaAnagraficaRichiesta>
--				<dataRiferimentoRichiesta>2016-10-30+01:00</dataRiferimentoRichiesta>
--				<datiAnagraficiRichiesti>1</datiAnagraficiRichiesti>
--			</datiRichiesta>
--		</ns2:Richiesta3002>
--	</soapenv:Body>
--</soapenv:Envelope>

**Comment by rvinzani** [comment]
La visura e stata adeguata
