### ISSUE TITLE
Problema iscrizione famiglia proveniente da altro comune subentrato 

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2332]
Comune di Modena - Ambiente Produzione

Buongiorno,
la nostra Anagrafe ha iscritto una famiglia di 5 persone proveniente da altro comune subentrato accorgendosi successivamente che mancava una bambina, nata nell' altro comune ma da esso non iscritta perchè trattata erroneamente come nascita all' estero. Dopo che lo Stato Civile dell' altro comune ha rettificato l' atto avremmo dovuto annullare la mutazione che trasferiva la residenza della famiglia per consentire all' altro comune l' iscrizione della bambina e ripetere l' operazione con tutti e 6 i componenti, nel frattempo però la pratica è scaduta e l' altro ente non ci ha ancora assicurato di riuscire a compiere le operazioni in breve tempo. 
In un caso come questo è consigliabile fare noi l' iscrizione della bambina per poter terminare il procedimento già scaduto o è necessario attendere l' altro comune, che potrebbe avere tempi di risposta molto lunghi? Nella seconda ipotesi, esistono o si prevedono in futuro canali per velocizzare questo tipo di interazione?

Grazie, cordiali saluti
Sonia Fiorini

**Comment by frmariani** [comment]
Mi rendo conto che il caso è residuale, visto che si tratta di una rettifica dell'atto di nascita, ma al momento ANPR non prevede queste particolari casistiche; l'unica operazione possibile è l'annullamento del cambio di residenza della famiglia e la successiva iscrizione per nascita della bambina; il vostro comune potrà poi ripetere l'operazione di mutazione di residenza dell'intera famiglia rispettando la congruità delle date.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
