### ISSUE TITLE
CODICE ISTAT COMUNE DI PANNONE - RONZO CHIENIS

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2333]
Buongiorno, ci siamo accorti che il codice ISTAT 22135 in tabella ANPR dei comuni è stato abbinato a due codici Belfiore diversi, di seguito estratto della tabella dei comuni ANPR. 

802407 | 16/10/1920 | 13/02/1923 | G313 | PANNONE | PANNONE
22135   | 14/02/1923 | 13/01/1924 | G313 | PANNONE | PANNONE | 
22135   | 14/01/1924 | 31/08/1971 | G313 | PANNONE | PANNONE | 
22135   | 01/09/1971 |                    | M303 | RONZO-CHIENIS | RONZO-CHIENIS | 

ANPR non considera il codice istat 022509 di PANNONE come un codice valido e al presubentro indica anomalia di Codice variazione. Sull'elenco ISTAT delle denominazioni precedenti dei comuni
[Elenco-denominazioni-precedenti.zip](https://github.com/italia/anpr/files/5530226/Elenco-denominazioni-precedenti.zip)
 risulta questo codice ISTAT 022509 abbinato a Pannone.  Si allega file scaricato dal sito  https://www.istat.it/it/archivio/6789

Al momento abbiamo forzato lo storico su tale codice 022509 poichè non è possibile gestire due codici istat uguali con Belfiore diversi. 

Potete verificare la correttezza della tabella dei comuni ANPR? 

Grazie 
Cordiali saluti

Cinzia Girelli
 HR – HD DEPLOY E PIATTAFORMA C. +39 3346216774 | T. +39 0461 381 515 int. 7576 Gruppo GPI I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599 
 www.gpi.it

**Comment by ncapozzi** [comment]
Buongiorno,
i codici con quarto carattere 5 sono codici denominazione creati da ISTAT per mantenere lo storico dei comuni nei vecchi ambienti INA-SAIA e AIRE. In ANPR dovete riportare il cod. ISTAT valido alla data di nascita del cittadino (in accordo con la tabella 3 pubblicata al link https://www.anpr.interno.it/portale/tabelle-di-riferimento) a meno che non abbia già un CF attribuito per un comune valido in un periodo diverso. Non è un problema per ANPR avere due codici istat uguali con Belfiore diversi.
N. Capozzi

**Comment by CGIRELLI-HUB** [comment]
Grazie
Buon lavoro
       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno gio 12 nov 2020 alle ore 16:15 ncapozzi <notifications@github.com>
ha scritto:
