### ISSUE TITLE
PROBLEMA CON ISCRIZIONE NASCITA - 1001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2334]
COMUNE CASERTA 061022
Buongiorno,
abbiamo inviato in ambiente di PRE-SUBENTRO una nascita servizio 1001
viene restituito errore:
<idOperazioneANPR>20532103</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN144</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Soggetti padre/madre non in ANPR</testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-13 10:49:31 , idOperazioneANPR 20532103</testoErroreAnomalia>
                    </errore> 

abbiamo verificato che sia il padre che la madre sono presenti in ANPR stesso ambiente

**Comment by ncapozzi** [comment]
Buongiorno,
il bambino viene associato alla famiglia dei genitori attribuzioneFamiglia =1 ma i genitori non stanno nella stessa famiglia. In particolare il cittadino indicato come padre sta in una famiglia diversa da quella indicata nella richiesta.
