### ISSUE TITLE
[1002] errore in iscrizione per ricomparsa 

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2336]
Comune di Modena - Ambiente Produzione

Buonasera,
stiamo cercando di reiscrivere un soggetto cancellato per irreperibilità ma ci viene ritornato l' errore:

codiceErroreAnomalia: EN185
tipoErroreAnomalia: E
testoErroreAnomalia: idSchedaSoggettoANPR 19369262 non presente o dati anagrafici incongruenti
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-12 16:27:59 , idOperazioneANPR 371923587

sia tentando dal nostro applicativo sia provando a farlo da webapp. Non riusciamo a capire quali siano i dati anagrafici che causano il problema, a nostro avviso cognome, nome, stato di nascita, data di nascita e sesso non sono variati. Per cortesia potete aiutarci ad individuare il problema?

Grazie, cordiali saluti
Sonia Fiorini

**Comment by frmariani** [comment]
per favore può ripetere l'operazione ? grazie

**Comment by frmariani** [comment]
il soggetto risulta re-iscritto, pertanto la issue viene chiusa
