### ISSUE TITLE
Errore en 272 ed en 572 variazione stato civile 

### ISSUE THREAD

**Issue by MMaurizio** [italia/anpr#2337]
-Buonasera, errore nell"id operazione anpr 372909240".  Impossibilità di concludere l'operazione con apertura warning rosso con codice EN572 ed EN 272 con la quale si avverte che lo sposo è già coniugato con altra persona ma uguali generalità. Sentito il Comune di Firenze che per primo ha variato la mutazione dello stato civile sul soggetto idanpr 32937765 spiegando a loro che forse è stata inserito un nuovo soggetto anzichè ricercare il coniuge iscritto alla mia aire. Deve mutare i dati del coniuge il Comune di Firenze o vi sono alternative?
Ringrazio per la collaborazione e le indicazioni utili per la soluzione.
Cordiali saluti

**Comment by MMaurizio** [comment]
Si può chiedere il post in quanto risolto grazie alla  preziosa collaborazione del Comune di Firenze.
Cordiali Saluti
M.Maurizio

**Comment by frmariani** [comment]
ok grazie dell'informazione
