### ISSUE TITLE
CODICE FISCALE NASCITA - WS1001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2338]
COMUNE CASERTA 061022
buonasera,
è possibile utilizzare, in ambiente di PRE-SUBENTRO 
gestioneCF = 1
ovvero attribuzione,  o è riservato in ambiente di PRODUZIONE
Grazie

**Comment by frmariani** [comment]
può utilizzarlo tranquillamente

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
