### ISSUE TITLE
ISCRIZIONE PER NASCITA - PRE SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2339]
COMUNE CASERTA 061022
AMBIENTE PRE-SUBENTRO
La madre è presente nello stesso ambiente, consultata scheda con WS3002 idOperazioneANPR = 20539199
<listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN143</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Soggetto madre non in ANPR</testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-15 18:56:02 , idOperazioneANPR 20539192</testoErroreAnomalia>
                    </errore>
                </listaErrori>

**Comment by frmariani** [comment]
Il codice fiscale della madre è duplicato in ambiente di pre subentro;  sicuramente il diagnostico non è calzante, ma non avendo indicato l'idanpr del soggetto madre, il sistema non può identificare univocamente la maternità da attribuire al bambino.

**Comment by rinonasti** [comment]
ok grazie

**Comment by rinonasti** [comment]
il codice fiscale duplicato è presente in altro comune?

**Comment by frmariani** [comment]
si, la duplicazione è presente anche nel WS 3002 che avete indicato idoperazioneanpr 20539199

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
