### ISSUE TITLE
ERRORE EN064 - FILE PRE-SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2340]
Comune Caserta 061022
Buongiorno,
Quesito su errore en064
Grado parentela utilizzabile solo con il file di subentro? 
Se no mi hanno posto il quesito di quale/i utilizzare.
Grazie

**Comment by rvinzani** [comment]
Provo a rispondere anche se mi servono alcune altre informazioni per essere piu precisa.
Alcune relazioni di parentela come figliastro, nipotastro etc. non sono pi\ utilizzabili nei servizi di ANPR perche obsoleti. Viene data segnalazione al momento del subentro sebbene non siano errori bloccanti

**Comment by rinonasti** [comment]
sono, utilizzati i codici 14 19 80

**Comment by rvinzani** [comment]
Confermo quindi quanto detto 
14 | Figliastro / Figliastra
19 | Fratellastro / Sorellastra
80 | Adottato
