### ISSUE TITLE
Informazioni su "Richieste di allineamento dati trasmesse dai consolati"

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2341]
Buongiorno
In riferimento al problema #2128, vorremmo sapere se è tali notifiche sono disponibili per la richiesta/scarico anche tramite WS, e le eventuali modalità.

Grazie mille
Riccardo

**Comment by ncapozzi** [comment]
Buongiorno,
non è previsto lo scarico dell'elenco tramite WS. Tenete presente che al momento parliamo di un numero di richieste molto limitato, soprattutto nel caso di piccoli comuni.

Per le istruzioni operative si rimanda alla circolare n. 11 del 2019 
https://www.anpr.interno.it/portale/emissione-cie-da-parte-delle-sedi-consolari?p_p_id=56_INSTANCE_2OiLBml1fpLJ&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1
