### ISSUE TITLE
Rettifica grado di parentela

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2342]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
abbiamo la necessità di modificare il grado di parentela e la matricola comune di alcuni cittadini. Quale servizio dobbiamo invocare ?

**Comment by frmariani** [comment]
Per modificare il grado di parentela dovrete invocare il WS 5001 tipo mutazione 2; per la modifica dell'identificativo comunale del singolo cittadino, dovrete invocare il WS 5008 tipo mutazione 1

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
