### ISSUE TITLE
[1002] msg. "Internal Error (from client)"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2343]
ambiente di PRODUZIONE - comune di SAN BENEDETTO PO (020055)

la comunicazione con idOperazioneComune 2020002288 produce errore in oggetto.
la validazione dell'xml non da errori formali.

potete verificare se è arrivato qualcosa sul server?

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno.
L'errore "Internal Error (from client)" indica che la richiesta è stata bloccata dai sistemi perimetrali perchè viola qualche regola, ad esempio : 
- violazione di qualche validazione XSD
- token di autenticazione non generati correttamenti (ad esempio per orario del client eccessivamente diverso dal server)

Cortesemente potete darci l'orario indicativo della richiesta, e almeno il tipo di operazione? (1002, 5008 ecc)

Possiamo intanto anticiparvi che vediamo due tipi di errori transiati dal comune indicato ieri, entrambi relativi a validazione XSD : 

/ANPR1000ServiziIscrizione/AnprService1000: cvc-simple-type 1: element descrizioneLocalita value 'GOBINDPURA PLOT KANGTHALI, HARYANA#012' is not a valid instance of type {http://sogei.it/ANPR/tipoDato}alfanumericoslash120char

/ANPR5000ServiziMutazione/AnprService5000: cvc-particle 3.1: in element {http://sogei.it/ANPR/5000mutazione}Richiesta5008 with anonymous type, found &lt;/ns2:Richiesta5008> (in namespace http://sogei.it/ANPR/5000mutazione), but next item should be testataRichiesta

Grazie in anticipo.

**Comment by AMonopoliADS** [comment]
buongiorno Matteo, grazie del riscontro.

come indicato nell'oggetto, la comunicazione è di tipo 1002.
ho ripetuto anche questa mattina la verifica dell'xml rispetto all'xsd, ed il controllo passa la validazione.
anche la generazione del token non dovrebbe essere il problema perchè l'errore scatta unicamente con questa comunicazione, gli altri invii vanno a buon fine.

L'errore sul campo "descrizioneLocalita" era stato intercettato ed infatti adesso quello stesso tag contiene la descrizione "GOBINDPURA PLOT KANGTHALI HARYANA"

ho appena tentato la ripetizione dell'invio con idOperazioneComune 2020002290
`<dataOraRichiesta>2020-11-19T08:45:49</dataOraRichiesta>`

grazie

**Comment by mttfranci** [comment]
Sui nostri sistemi perimetrali contiamo a vedere lo stesso errore sul campo indicato : 
/ANPR1000ServiziIscrizione/AnprService1000: cvc-simple-type 1: element descrizioneLocalita value 'GOBINDPURA PLOT KANGTHALI HARYANA#012' is not a valid instance of type {http://sogei.it/ANPR/tipoDato}alfanumericoslash120char

Potete verificare nuovamente il dato? Forse la validazione che effettua il nostro sistema è più stringente.

**Comment by AMonopoliADS** [comment]
svelato il mistero.
si trattava di un carattere che l'editor non visualizzava, e che veniva perso nel trasferimento dell'xml per la validazione.
abbiamo risolto.

grazie

**Comment by mttfranci** [comment]
Di niente 
Buon proseguimento.
