### ISSUE TITLE
Annullamento divorzio straniero

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2344]
Nel mese di gennaio 2018 sono subentrati due cittadini stranieri da divorziati (id 19819765 e id 19819754), uno dei due inoltre, in data 30/07/2020 quindi successivamente al divorzio, ha effettuato un cambio di indirizzo.
Con sentenza del tribunale di Ravenna è stato chiesto l'annullo della sentenza di divorzio straniero dei due cittadini. Come si può procedere non essendoci un evento in anpr da annullare?

Grazie e buon lavoro.

**Comment by rvinzani** [comment]
Dovreste annullare il cambio di indirizzo e poi procedere con l-eliminazione dati del matrimonio in modo da poterli inserire correttamente. Poi effettuate nuovamente il cambio di indirizzo

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
