### ISSUE TITLE
Errore bloccante n 29099388: necessità di iscrizione urgente

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2345]
Buongiorno,
nell'immigrare un cittadino con provenienza da Torino (dove la pratica di iscrizione era stata revocata con ripristino irreperibile nel Comune di Segrate), in Anpr risulta un procedimento aperto (n 29099388) che non permette a questo Comune di iscrivere la persona. Abbiamo contattato più volte con pec e telefonate varie ma il Comune di Torino continua solo a inviarci l'Apr e non chiude il procedimento aperto. La persona per motivi sanitari ha necessità urgentissima della nostra iscrizione. 
Potete sbloccare voi la posizione del cittadino?
Grazie,
cordiali saluti.

**Comment by frmariani** [comment]
siamo riusciti a contattare il comune di Torino ed il procedimento è stato chiuso, riprovate per favore

**Comment by katiavacchi** [comment]
grazie!
