### ISSUE TITLE
AnagAIRE v. 6.0.3

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2346]
Buongiorno,
Sto effettuando il presubentro per il Comune di Arsago Seprio (VA), codice istat 012005 e sto scaricando la versione 6.0.3 di AnagAIRE per effettuare il file dei cittadini AIRE.
Installando la nuova versione, compare il seguente errore
![immagine](https://user-images.githubusercontent.com/46593834/99789875-8f1fae80-2b23-11eb-87a6-690eb1207f56.png)
ho provato ad effettuare l'installazione su pc diversi, ma l'errore è lo stesso..
Come posso fare per fare il file in assenza di AnagAIRE?

Resto in attesa di un gradito riscontro
Cordiali Saluti

**Comment by Leonforte** [comment]
Salve, il pacchetto vcredist_x86.exe è disponibile per il download al link 
https://CStorS.sogei.it/invitations?share=6a8ca1fec4c6c1cd23f5

**Comment by fcastellani81** [comment]
Grazie! Direi che funziona!
La issue può essere chiusa

**Comment by Leonforte** [comment]
Perfetto, Microsoft già dallo scorso anno ha bloccato il download perchè considera il pacchetto non più supportato. Buon lavoro, saluti
