### ISSUE TITLE
AIRE Elenchi Anomalie - Soggetti con luogo nascita uguale alla denominazione di uno stato estero valido

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2347]
Salve,
Comune di S.Angelo dei Lombardi (AV)
Inerentemente all'elenco anomalie AIRE indicato in oggetto abbiamo corretto i dati relativi al luogo di nascita per i cittadini:
79428766
79429021
e verificato che compaiano sulla scheda individuale sul portale ANPR.
Tuttavia effettuando di nuovo il download del file anomalie tali cittadini risultano ancora presenti con i dati non aggiornati.
Come dovremmo procedere?

**Comment by ncapozzi** [comment]
Buonasera,
quando si corregge un'anomalia l'elenco pubblicato non viene automaticamente aggiornato in quanto l'elaborazione è una tantum. Non dovete fare altro.

N. Capozzi
