### ISSUE TITLE
[3002] dati futuri in ricerca alla data

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2348]
La ricerca fatta tramite il servizio 3002 del soggetto ID ANPR 41800010 con riferimento 11/06/2020 ritorna i dati di residenza validi al 12/06/2020. (operazione ANPR ricerca 378313149)

Com'è possibile ?

**Comment by frmariani** [comment]
Chiedo scusa ma non mi sembra che ci siano differenze nei dati di residenza del soggetto tra l'11 /06/2020 ed il 12/06/2020; mi può aiutare con qualche altra indicazione per favore ?

**Comment by busaster** [comment]
La data di decorrenza di riferimento della richiesta è 11/06/2020 mentre il campo "dataDecorrenzaResidenza" è 12/06/2020, mi aspettavo di ritrovare un valore inferiore o al più uguale al 11/06/2020

**Comment by frmariani** [comment]
il giorno 18/11/2020, è stata effettuata una Rettifica/Integrazione indirizzo dell'intera famiglia. Come mai avete avuto necessità di Rettificare l'indirizzo se di fatto non è stato modificato nulla ?

**Comment by busaster** [comment]
Se mi indica id operazione ANPR verifico, in ogni caso il mio dubbio sulle date rimane.

**Comment by frmariani** [comment]
idoperazioneanpr 376597867; l'operazione di rettifica dell'indirizzo viene effettuata a livello di famiglia ed il problema emerge soltanto a livello di consultazione dei soggetti aggiunti nella famiglia successivamente alla data di creazione della stessa.
Se la rettifica non è necessaria, ne consiglio l'annullamento: in questo modo sarà possibile una corretta consultazione dei dati di ciascun componente. Ci tengo a precisare che la certificazione non risente di questa particolarità

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
