### ISSUE TITLE
Certificazione ANPR in timbro digitale da portale servizi online

### ISSUE THREAD

**Issue by Arionlinesrl** [italia/anpr#2349]
Buonasera,
stiamo attivando un servizio di emissione dei certificati anagrafici timbrati digitalmente in comuni già subentrati in ANPR.
Il certificato timbrato digitalmente risulta emesso dal sindaco, ufficiale d’anagrafe a tutti gli effetti.
Inizialmente eravamo indirizzati verso la limitazione della possibilità di richiesta di certificati per se e i propri familiari, ma poi, analizzando il regolamento anagrafico aggiornato al 2019, l’art. 33 recita:

Art. 33
Certificati anagrafici.
1. Fatti salvi i divieti di comunicazione di dati, stabiliti da speciali disposizioni di legge, e quanto previsto dall’articolo 35, l’ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell’anagrafe nazionale della popolazione residente, nonché ogni altra informazione ivi contenuta.
2. Al rilascio di cui al comma 1 provvedono anche gli ufficiali d’anagrafe di comuni diversi da quello in cui risiede la persona cui i certificati si riferiscono.

Quindi, alla luce di ciò, è corretto che un cittadino possa ottenere tramite portale dei servizi al cittadino, un certificato anagrafico di una terza persona, anche non residente nel proprio comune, ma comunque residente in un comune subentrato in ANPR?
O ci sono delle restrizioni che devono essere applicate?
Grazie,
Mariano Carta

**Comment by FilippoPapi** [comment]
buonasera
è un quesito che dovete rivolgere al Ministero dell'Interno
saluti
