### ISSUE TITLE
PROBLEMA SERVIZIO A006

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2350]
Buonasera,
COMUNE DI CASERTA 061022 - PRE-SUBENTRO
abbiamo inviato dati con il servizio A006
viene fuori il seguente errore:

<codiceErroreAnomalia>EC034</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Codice consolato di residenza 2310103 incongruente con la descrizione</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-21 18:40:42 , idOperazioneANPR 20578288

Grazie

**Comment by rinonasti** [comment]
OK risolto problema esposto precedentemente (descrizione errata deve essere indicata la località)
adesso l'errore e'
- <errore>
  <codiceErroreAnomalia>EN073</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Incongruenza dati anagrafici: la scheda soggetto del comune non coincide con quella specificata nella richiesta</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-21 19:07:08 , idOperazioneANPR 20578307</testoErroreAnomalia> 
  </errore>
Grazie

**Comment by rinonasti** [comment]
Anche : Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-22 12:30:53 ,idOperazioneANPR 20579772

**Comment by rinonasti** [comment]
Risolto anche questo (deve essere indicato id ANPR del soggetto).
ma:
<testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-22 13:10:30 , mittente 061022 , idOperazioneComune 2020A00600017

**Comment by ncapozzi** [comment]
Buongiorno,
nell'errore EN527 ANPR restituisce l'id numerico ANPR dell'operazione.
Sembrerebbe un messaggio fi errore restituito dal gestionale. L'id 2020A00600017 non è presente in pre-subentro

**Comment by rinonasti** [comment]
questo e' la risposta completa
codiceErroreAnomalia>EN493</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione </testoErroreAnomalia>
                    </errore>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-22 13:10:30 , mittente 061022 , idOperazioneComune 2020A00600017</testoErroreAnomalia>
                    </errore>

**Comment by ncapozzi** [comment]
Buongiorno,
può indicare per favore un recapito telefonico al quale possiamo contattarla?

**Comment by ncapozzi** [comment]
Dovrebbe far verificare il profilo utente della persona che ha eseguito l'operazione oppure farci avere il CF della persona che ha eseguito l'operazione senza indicarlo nella issue. Per questo abbiamo chiesto un recapito telefonico

**Comment by rinonasti** [comment]
3355885312

Inviato da iPhone
Rino Nasti
Phone 3355885312

**Comment by rinonasti** [comment]
Ho riprovato funziona. devono essere indicati tutti i dati relativi ad ANPR individuo e famiglia altrimenti viene fuori l'errore dell'utente non abilitato.
