### ISSUE TITLE
Codice stato estero non presente in tabella di riferimento stati esteri ANPR

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2351]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
abbiamo la necessità di aggiornare alcune informazioni di un cittadino nato a MOSTAR che all'epoca della nascita era in JUGOSLAVIA codice stato 224.
ANPR restituisce errore dicendo che il Codice stato estero non presente in tabella di riferimento stati esteri ANPR.

Cosa dobbiamo fare ?

**Comment by ncapozzi** [comment]
Buongiorno,
per tutti quei cittadini nati in stati esteri cessati è necessario utilizzare la codifica dello stato 998 con la descrizione dello stato come indicato nell'appendice due del documento "Attività di bonifica propedeutiche al subentro" disponibile sulla home page del sito https://www.anpr.interno.it/portale/home

N. Capozzi
