### ISSUE TITLE
[N015] ora disponibilità

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2352]
Buongiorno
richiedendo le notifiche per l'operazione 378314584 per il Comune di Sant'Anatolia di Narco in PRODUZIONE
l'ora disponibilità viene sempre spostata in avanti di 1 ora.

abbiamo notato il problema con diversi comuni per richieste fatte settimana scorsa sembra solo per questa tipologia di notifiche.
Ci sono stati problemi?

grazie
Riccardo

**Comment by mttfranci** [comment]
Salve, c'era stato un problema nella sottomissione della richiesta che abbiamo rielaborato. Ora dovrebbe essere pronta. Abbiamo anche fatto una verifica su quelle che erano nella stessa situazione. Potete verificare se il caso specifico è stato risolto e se ne avete altre ancora incomplete? (Nella maggior parte dei casi le richieste vengono completate in un'ora... ma se questo non avviene al momento il sistema riprova dopo u'ora... ecco perchè l'orario continuava a spostarsi).
Saluti

**Comment by Hdemografici** [comment]
Buongiorno, confermo che ora la situazione si è bloccata
grazie
