### ISSUE TITLE
[N010] comune di Parcines/Partschins

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2354]
Buongiorno,
il comune di Gessate ha ricevuto N010 dal comune di Parcines/Partschins cod. 021062 (BZ), poichè nella lista dei comuni subentrati trovo il comune inserito con la denominazione Parcines è corretto ricevere la notifica da Parcines/Partschins?
idOperazioneANPR: 374517948

Grazie
Federico

**Comment by rvinzani** [comment]
Il servizio di notifica prevede che alla denominazione corrente venga aggiunta la denominazione presente nella colonna altradenominazione della tabella comuni

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa

**Comment by Hdemografici** [comment]
Perfetto, grazie dell'informazione.
