### ISSUE TITLE
Soggetto non individuato in AT - Codice fiscale NON variato

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2355]
Salve,

Comune AOSTA Produzione

In Anpr esiste un individuo id 43784829 con un CF collegato, quindi non l'attuale, ma il precedente secondo quanto verificato in AE. 

Si tenta di effettuare una Mutazione dati con gestione codice fiscale 0  variando il Nome e il CF nel tentativo di passare da quello precedente a quello attuale ed allineare la situazione di ANPR a quella di AE. 

Il risultato è l'errore:
1 Errore Anpr Cod: EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato 
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-23 16:14:53 , idOperazioneANPR 380008575 

Tentando la risoluzione disallineamenti con AE, confrontando le anagrafiche di ANPR e quelle di AE e scegliendo il Conferma AE si ottiene lo stesso errore. 

Spuntando Collega Codici Fiscali si ottiene :
Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12) 

Pur effettuando una prova ed inserendo il controllo sul CF nella mutazione tutti i dati con iscrizione senza validazione non è possibile procedere

Come è possibile allineare i dati Anpr a quelli di AE ?

**Comment by frmariani** [comment]
In questi casi dobbiamo intervenire noi con la "svalidazione" del soggetto nel sistema ANPR; ripeta l'operazione di Mutazione dei dati anagrafici con gestione codice fiscale =0  e mi faccia sapere

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
