### ISSUE TITLE
Accesso non possibilie in ANPR

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2356]
Buongiorno
l'accesso ad ANPR segnala
"La connessione non è privata
Gli utenti malintenzionati potrebbero provare a carpire le tue informazioni da web.anpr.interno.it (ad esempio, password, messaggi o carte di credito). Ulteriori informazioni
NET::ERR_CERT_DATE_INVALID

Contribuisci a migliorare la sicurezza sul Web per tutti inviando a Google gli URL di alcune pagine visitate, informazioni limitate sul sistema e alcuni contenuti delle pagine. Norme sulla privacy"
Potete darci indicazioni?
Grazie
Cordiali saluti
Comune di Torino

**Comment by Leonforte** [comment]
Salve, stiamo risolvendo il problema, a breve dovrebbe tornare accessibile. Buona giornata
