### ISSUE TITLE
PRE-SUBENTRO : Errori legame di parentela

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2357]
COMUNE DI PANTIGLIATE

Ferrari Nadia

Stiamo procedendo al pre-subentro/subentro ... ottieniamo diversi errori riguardo i legami di parentela 
- FIGLIASTRO/A
- SORELLASTRA
- FRATELLASTRO
- MATRIGNA
- PATRIGNO

quale diverso grado di parentela dobbiamo indicare ? 

1. Altro Parente

2. Convivente (con   vincoli di adozione o affettivi) 

o cos'altro ?

**Comment by rvinzani** [comment]
Non abbiamo avuto indicazioni su una eventuale rimappatura dei vecchi legami di parentela con quelli attuali.
Credo che 
FIGLIASTRO/A sia traducibile come FIGLIO se adottato o come convivente 
SORELLASTRA  ** SORELLA
FRATELLASTRO ** FRATELLO
MATRIGNA ** CONVIVENTE
PATRIGNO ** CONVIVENTE
anche in questi ultimi casi dipende se ADOTTATO

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
