### ISSUE TITLE
Riferimento issue #2344

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2358]
Buongiorno,
con riferimento al ticket #2344 aggiungiamo che per il cambio di indirizzo provvederemo ad annullarlo, ma vi chiediamo di indicarci quale è la procedura per annullare il divorzio essendo i 2 cittadini subentrati già divorziati. 

Grazie.

**Comment by rvinzani** [comment]
E possibile eliminare tutte le informazioni relative al matrimonio a valle del subentro se inviate in maniera errata con la funzione di elimina dati

**Comment by rvinzani** [comment]
Chiudo la issue. In caso siano necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
