### ISSUE TITLE
[EN148] La richiesta non è più disponibile, se necessario inserirla nuovamente

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#2359]
Buongiorno a tutti.

Stiamo avviando diversi comuni in ambiente di subentro ufficiale e non riusciamo a far funzionare correttamente le richieste asincrone di verifica delle notifiche

Stiamo utilizzando il WS4005 come specificato utilizzando un range di date non superiore ai 30 giorni e ricevendo correttamente un id operazione anpr e la relativa data di disponibilità

Tentando di verificare lo stato dell'id operazione ricevuto otteniamo sempre l'errore riportato nell'oggetto

Nello specifico si tratta del Comune di Borgomaro in ambiente PROD, subentrato il 05/11/2020 e le notifiche che stiamo cercando di ottenere sono le N010 per mutazione di indirizzo da altri comuni (ricevendo l'idOperazioneANPR 377970198)

Siamo sicuro di avere delle notifiche in quanto su webapp sono presenti

Cosa dobbiamo verificare ?

Grazie

Daniel Carenzo
C&C Sistemi Srl

**Comment by DanielCarenzo** [comment]
ad integrazione di quanto richiesto aggiungo gli xml utilizzati

chiamata 1:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
	<testataRichiesta>
		<idOperazioneComune>CV200</idOperazioneComune>
		<codMittente>008010</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>4005</operazioneRichiesta>
		<dataOraRichiesta>2020-11-25T16:20:05.354+01:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>PROD</tipoInvio>
		<nomeApplicativo>CIVES</nomeApplicativo>
		<versioneApplicativo>20B.11X</versioneApplicativo>
		<fornitoreApplicativo>CeC SISTEMI SRL</fornitoreApplicativo>
	</testataRichiesta>
	<elaborazione>
		<comuneRichiesta>
			<nomeComune>BORGOMARO</nomeComune>
			<codiceIstat>008010</codiceIstat>
			<siglaProvinciaIstat>IM</siglaProvinciaIstat>
		</comuneRichiesta>
		<dettaglioDati>RISPOSTA</dettaglioDati>
		<ricercaElenchiRichieste>
			<statoLavorazione>9</statoLavorazione>
			<operazioneRichiesta>N010</operazioneRichiesta>
			<periodoRiferimentoRichieste>
				<dataOraIniziale>2020-11-10T06:00:00.000+01:00</dataOraIniziale>
				<dataOraFinale>2020-11-20T06:00:00.000+01:00</dataOraFinale>
			</periodoRiferimentoRichieste>
		</ricercaElenchiRichieste>
	</elaborazione>
</ns2:Richiesta4005>

risposta 1:

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta4005 xmlns:a="http://sogei.it/ANPR/4000estrazione">
            <a:RispostaMultipla4005>
                <testataRisposta>
                    <idOperazioneComune>CV200</idOperazioneComune>
                    <codMittente>008010</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>4005</operazioneRichiesta>
                    <dataOraRichiesta>2020-11-25T16:20:05.354+01:00</dataOraRichiesta>
                    <idOperazioneANPR>382083283</idOperazioneANPR>
                    <esitoOperazione>0000</esitoOperazione>
                </testataRisposta>
                <statoRichiesta>0</statoRichiesta>
                <idOperazioneANPR>382083283</idOperazioneANPR>
                <dataDisponibilita>2020-11-25T17:20:09.901+01:00</dataDisponibilita>
            </a:RispostaMultipla4005>
        </a:Risposta4005>
    </soapenv:Body>
</soapenv:Envelope>

chiamata 2:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Richiesta4005 xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
	<testataRichiesta>
		<idOperazioneComune>CV204</idOperazioneComune>
		<codMittente>008010</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>4005</operazioneRichiesta>
		<dataOraRichiesta>2020-11-25T17:24:54.309+01:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>PROD</tipoInvio>
		<nomeApplicativo>CIVES</nomeApplicativo>
		<versioneApplicativo>20B.11X</versioneApplicativo>
		<fornitoreApplicativo>CeC SISTEMI SRL</fornitoreApplicativo>
	</testataRichiesta>
	<verificaStato>
		<idOperazioneANPR>382083283</idOperazioneANPR>
		<progressivo>1</progressivo>
	</verificaStato>
</ns2:Richiesta4005>

risposta 2:

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta4005 xmlns:a="http://sogei.it/ANPR/4000estrazione">
            <a:rispostaKO>
                <testataRisposta>
                    <idOperazioneComune>CV204</idOperazioneComune>
                    <codMittente>008010</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>4005</operazioneRichiesta>
                    <dataOraRichiesta>2020-11-25T17:24:54.309+01:00</dataOraRichiesta>
                    <idOperazioneANPR>382129604</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN148</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>La richiesta non e' piu' disponibile, se necessario inserirla nuovamente.</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:rispostaKO>
        </a:Risposta4005>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by mttfranci** [comment]
Salve, nel caso specifico delle richieste 377970198 e 382083283 c'è stato un problema di elaborazione che dovrebbe essere stato risolto.
Potete riprovare? Se avete altre richieste che presentano problemi fateci sapere.

**Comment by DanielCarenzo** [comment]
> Salve, nel caso specifico delle richieste 377970198 e 382083283 c'è stato un problema di elaborazione che dovrebbe essere stato risolto.
> Potete riprovare? Se avete altre richieste che presentano problemi fateci sapere.

Abbiamo provato e ora funziona correttamente

Proveremo anche sugli altri clienti per verificare se la procedura funziona

Grazie

**Comment by DanielCarenzo** [comment]
Abbiamo provato a fare una nuova richiesta sempre al comune di Borgomaro ma ha dato nuovamente l'errore

L'ID Anpr ricevuto è il seguente **382911172**
Era disponibile alle 15:31 e lo abbiamo verificato alle 15:47, non so se può dipendere da una verifica troppo ravvicinata

Provando a chiedere la verifica di altri ID più vecchi riceviamo comunque lo stesso errore

**Comment by mttfranci** [comment]
Salve. si ieffetti c'è stato un problema anche su questa richiesta.
Stiamo indagando e cercando una soluzione definitiva per rendere più solida la generazione.
Se incontrate ancora il problema fateci sapere.
Saluti

**Comment by DanielCarenzo** [comment]
Abbiamo provato con un altro comune ma l'errore persiste
L'ID Anpr è il **382449469**

Il problema è che abbiamo effettuato il subentro di 20 comuni e ne abbiamo in programma altrettanti nelle prossime settimane
Dobbiamo capire come sistemare la cosa

Attendo riscontro

Grazie

**Comment by mttfranci** [comment]
la richiesta dovrebbe a breve andare a posto. Stiamo predisponendo dei meccanismi più efficienti di recovery delle richieste fallite.

**Comment by DanielCarenzo** [comment]
abbiamo fatto diverse prove sui vari enti che abbiamo attivato negli ultimi mesi e le notifiche ora funzionano correttamente
la issue si può considerare chiusa positivamente

**Comment by mttfranci** [comment]
Perfetto, grazie del feedback
