### ISSUE TITLE
Transazione FALLITA - javax.xml.ws.soap.SOAPFaultException: Internal Error per servizio 5012

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#236]
Buongiorno, siamo del Comune di Bologna e lavoriamo in ambiente di TEST.

A seguito di un richiamo del servizio 5001 abbiamo provato ad annullare operazione con il servizio 5012.
Ci restituite un Internal Error, ma l'xml ci sembra corretto.
Ci potreste aiutare?

ID operazione comune 20170713104544013321013321F73B
In allegato l'xml
[WS5012.zip](https://github.com/italia/anpr/files/1151993/WS5012.zip)

**Comment by gcarbonin** [comment]
Il file xml allegato è del 5001 e non del 5012.

**Comment by ANPRCDBO** [comment]
Buongiorno, ma da cosa si deduce che e' il 5001?
Nel tipo operazione  vedo <operazioneRichiesta>5012</operazioneRichiesta>,  e contiene il dato operazione da annullare:<operazioneRichiesta>5001</operazioneRichiesta>  che e' relativa all' operazione mutazione famiglia che si vuole annullare

**Comment by gcarbonin** [comment]
Ha ragione. Mi può dire l'errore esatto che riceve? Inoltre sarebbe utile se potesse ripetere ora l'operazione

**Comment by ANPRCDBO** [comment]
Salve, errore che riceviamo: Internal Error. Abbiamo ripetuto l'operazione. In allegato l'xml di richiesta e di risposta
[5012.zip](https://github.com/italia/anpr/files/1155920/5012.zip)

**Comment by gcarbonin** [comment]
Il problema di è risolto?

**Comment by ANPRCDBO** [comment]
Grazie alle indicazioni sui vostri lo abbiamo corretto il nostro client.
Problema risolto.

**Comment by gcarbonin** [comment]
Grazie
