### ISSUE TITLE
Errore formato EsitoRisposta3002

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2360]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Invocando il servizio 3002 per consultazione scheda anagrafica cittadino da Anagrafe Locale, viene restituito un esito che non riusciamo ad aprire con un browser (abbiamo provato con diversi browser) di seguito l'operazione

<testataRisposta>
                    <idOperazioneComune>20201125084251</idOperazioneComune>
                    <codMittente>108052</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>3002</operazioneRichiesta>
                    <dataOraRichiesta>2020-11-25T08:42:00+01:00</dataOraRichiesta>
                    <idOperazioneANPR>381376026</idOperazioneANPR>
                    <esitoOperazione>0000</esitoOperazione>
                </testataRisposta>

ed allegato l'errore :
![ImmagineErrore](https://user-images.githubusercontent.com/54433203/100200475-f613dd80-2efe-11eb-9b73-0a2f73df61f0.gif)

Potete intervenire ?

**Comment by ncapozzi** [comment]
Buongiorno,

se il cittadino interessato è idsoggettoANPR 72830050, non ci sono problemi nella consultazione 3002. In generale nessuna consultazione 3002 effettuata questa mattina dal vostro comune è andata in errore.
Sembrerebbe quindi più un problema del vostro gestionale, suggeriamo quindi di contattare la vostra casa software.

N. Capozzi

**Comment by GabriellaBallabio** [comment]
Buongiorno
forse non mi sono spiegata, no ho detto che la consultazione è andata in errore ... ho ottenuto il file di risposta ...
Questo file che contiene i dati del cittadino  NON LO LEGGO CON IL GESTIONALE !!!! Bensì con un normale browser (firefox , IE, CHROME) Allego il file di risposta così potrà provare ad aprirlo (con un semplice doppio click) anche lei e verificare l'anomalia.

NB Il file allegato è stato ridenominato aggiungendo l'estensione (.txt) che va rimossa prima di aprirlo.

Grazie
[EsitoWS_Richiesta3002.xml.txt](https://github.com/italia/anpr/files/5596167/EsitoWS_Richiesta3002.xml.txt)

**Comment by ncapozzi** [comment]
Senza rimuovere l'estensione txt il file può essere aperto con blocco note. Noi riusciamo anche ad aprirlo attraverso brower. Comunque non si tratta di un problema ANPR. Le rinnovo per questo il suggerimento di contattare la casa software in quanto lei ottiene l'xml di risposta del 3002 per il tramite di una consultazione effettuata con il suo gestionale facendo presente che probabilmente il problema è collegato al fatto che il cittadino è nato in un comune che termina con "ù". 

Per eventuali richieste future di assistenza la informo che i dati anagrafici dei cittadini non dovrebbero essere esposti nelle issue. Per questo motivo di solito vengono indicati l'idoperazioneANPR e l'idsoggetto e basta.

**Comment by GabriellaBallabio** [comment]
mi dice con quale browser aprite la risposta ? Noi li abbiamo provati tutti

**Comment by ncapozzi** [comment]
Microsoft Edge

**Comment by GabriellaBallabio** [comment]
Buongiorno
abbiamo provato anche con EDGE ed il file non si apre. 

Allego screenshot dell'errore.

![ErroreAperturaFileConEDGE](https://user-images.githubusercontent.com/54433203/100328847-435e8080-2fcd-11eb-943a-5305c1fdeb82.png)

Come possiamo aprire il file ? non mi dica blocco note perchè in questo modo perdiamo la possibilità di scorrere gli alberi.

Grazie
