### ISSUE TITLE
Soggetti coniugati residenti in due comuni diversi da associare

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2362]
Buongiorno.
Scrivo per chiedervi come associare due soggetti residenti in due comuni diversi che risultano coniugati.
I soggetti sono i seguenti:
LNTNMR60S65H168B - cod. 59862827
RTNGPP56M06H168Z - cod. 96516124 (-> iscritto per la prima volta in ANPR ieri, per ricomparsa da irreperibilità).

I miei riferimenti sono:
Paltrinieri Andrea
Ufficiale d'Anagrafe del Comune di Biassono (cod. 108009)
tel. 039-2201060
e-mail anagrafe@biassono.org

In attesa di un Vs. riscontro porgo distinti saluti.

Andrea Paltrinieri

**Comment by frmariani** [comment]
come comunicato per le vie brevi, per  la "riconciliazione",  basta effettuare la ricerca del coniuge con codice fiscale o idanpr
