### ISSUE TITLE
URGENTE SPORTELLI - ACCESSO ANPR NON CONSENTITO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2364]
Buongiorno,
da circa 20 minuti non è consentito l'accesso ANPR sia da Web App sia da CIEL (ANPR non disponibile)
Cortesemente è possibile verificare e avere tempistiche di massima per iil riavvio?
Grazie

UPI Torino

**Comment by gife67** [comment]
Buongiorno,
ci sono stati dei problemi dalle 09:25 alle 09:45 circa.
Ci scusiamo per il disagio.
