### ISSUE TITLE
MONITORAGGIO OPERAZIONI - NOTIFICA MUTAZIONE DI RESIDENZA

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2365]
COMUNE DI CAPONAGO (MB)

Buongiorno
quale Servizio è necessario invocare per ottenere lo stesso l'elenco delle Notifiche per Mutazione di residenza che si ottiene utilizzando la WA come da immagini allegate ?

![Immagine](https://user-images.githubusercontent.com/54433203/100437555-33b06c00-30a1-11eb-92e3-257b0c049f86.png)
![Immagine1](https://user-images.githubusercontent.com/54433203/100437564-37dc8980-30a1-11eb-9fe7-2e3899cb4f8a.png)

**Comment by rvinzani** [comment]
Per scaricare le notifiche si utilizza il servizio 4005.
Chiudo la issue . In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
