### ISSUE TITLE
PROBLEMA MUTAZIONE RESIDENZA NUCLEO - WS5001 - PRESUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2366]
Buonasera COMUNE DI CASERTA 061022
gli errori evidenziati dipendono tutti dal fatto che manca data decorrenza residenza precedente

<codiceErroreAnomalia>EN237</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN424</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>La residenza del soggetto con ID ANPR 240009532 non puo' essere variata in quanto non e' impostata la data decorrenza residenza del soggetto</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-27 15:42:15 , idOperazioneANPR 20620047</testoErroreAnomalia> 
  </errore>

**Comment by frmariani** [comment]
In questo caso potrà impostare la Data di decorrenza della residenza non pervenuta con il pre subentro del comune, seguendo le seguenti istruzioni:
Registrazione > Rettifiche > Rettifica dati subentro

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
