### ISSUE TITLE
Errore Anpr Cod: EN248 - Soggetto gia' presente su ANPR

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2367]
Comune di San Michele all'Adige Produzione

In AE la persona ha due codici fiscale uno con comune di nascita KOSOVO e un altro IUGOSLAVA.
Il comune è riuscito ad iscrivere la persona con il CF corrtto (KOSOVO), ma da webapp in un secondo momento ha sbagliato a confermare da risoluzione disaliamento e ora in ANPR c'è il codice fiscale sbagliato e come collegato quello corretto.

Non si riesce più a mutare le generalità in quanto da il seguente errore: 

Errore Anpr Cod: EN248 - Soggetto gia' presente su ANPR con CF XXXXXXXX- Cognome: XXXX Nome: XXXXX CF: XXXXXXXXX-

Il codice fiscale indicato nell'errore è quello che si trova come collegato a quello attuale e finisce con la lettera "G"
Ricercando la persona con quest'ultimo non da alcun risultato quindi non si tratta di una doppia iscrizione in ANPR.
 
Si richiede la possibilità di inviare una mutazione tutti i dati al fine di allineare la situazione 

Id Soggetto ANPR: 95998193

**Comment by frmariani** [comment]
Per favore l'idanpr dell'operazione fallita; comunque, se i codici fiscali sono collegati ed è corretto il collegato, basta effettuare l'operazione di "inversione di link"; dai servizi di registrazione, effettuare una mutazione dei dati inserendo il CF ed i dati corretti nelle generalità di modifica.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
