### ISSUE TITLE
Eliminazione Dati: Matrimonio

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2368]
Sant'Angelo dei Lombardi (AV)

Cittadino 79432342

Tentativo di eliminazione matrimonio. Motivo revoca: errore materiale.

La web application restituisce il seguente errore:

Tipo operazione non ammesso per il servizio (Codice: SP000)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-01 12:14:05 , Token 1606821245983 (Codice: EN527)

**Comment by frmariani** [comment]
Nell'iniziativa avete selezionato erroneamente "Rettifica"; dovete scegliere tra "Istanza di parte" o "Operazione d'Ufficio"

**Comment by vix-db** [comment]
Risolto usando "Operazione d'Ufficio", grazie!
Ma a questo punto la domanda sorge spontanea: "Rettifica" quando si deve usare?

**Comment by frmariani** [comment]
al momento non si deve usare

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
