### ISSUE TITLE
Registra smart card: errore

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2369]
Comune di Adro.
Hanno chiesto una nuova smart card, ritirata dalla prefettura.
L'ALS va sulla Web App > sicurezza > gestione smart card > registra > ricerca
La smart card di COL...... risulta CONSEGNATA DALLA PREFETTURA
La sceglie e preme registra, ottenendo l'errore "Errore CAST Attivazione Smart Card".

**Comment by Leonforte** [comment]
Buonasera, la problematica è stata risolta, potete procedere alla regitrazione della carta.
