### ISSUE TITLE
Attribuzione C.F. neonato in ufficio A.E.

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#237]
Riferimento: idOperazioneANPR 716913
Segnalo questa richiesta di iscrizione per nascita.
Neonato di cui si chiede l'iscrizione per nascita, AE risponde alla richiesta di attribuzione del C.F. con "EAA30 - Codice fiscale individuato in AT con dati anagrafici diversi o indirizzo diverso".
Era già accaduto in marzo in altro comune ANPR, che i genitori si fossero recati in un ufficio dell'AE a chiedere l'attribuzione del C.F. del bambino. Io avevo inteso che si sarebbe introdotto un blocco atto ad impedire l'attribuzione del C.F. da parte degli uffici di AE per soggetti con residenza in comuni subentrati. Evidentemente avevo capito male oppure non si è introdotto il blocco. Nel caso in esame il bimbo è stato iscritto in AE con indirizzo di residenza improprio, nella fattispecie padre e madre hanno residenze diverse nello stesso comune ANPR e hanno dichiarato per il bimbo l'indirizzo paterno ad AE, l'anagrafe ha poi iscritto il bambino all'indirizzo della madre, come prevede la norma.

**Comment by bfilipazzi** [comment]
Ho scordato di dichiararmi in coda al messaggio precedente:

**Comment by gcarbonin** [comment]
Buongiorno. Il messaggio restituito dall'Agenzia delle Entrate indica che la persona alla quale è stato richiesto di attribuire un codice fiscale già lo possiede con un indirizzo diverso. Verificato che si tratta della stessa persona, è sufficiente ripetere l'iscrizione senza chiedere l'attribuzione del codice fiscale, che deve essere indicato nella richiesta, omettendo di valorizzare il campo gestioneCF o valorizzandolo a zero.
Nel caso in cui il comune dovesse riscontrare che NON si tratta della stessa persona, dovrà effettuare l'iscrizione senza indicare il codice fiscale e specificando il valore 2 nel campo gestioneCF: in questo modo si conferma che si tratta di un omocodice.

**Comment by bfilipazzi** [comment]
Quanto lei mi spiega è chiaro. Non è chiaro perché l'ufficio territoriale di AE abbia rilasciato il C.F. ad un soggetto da iscrivere in comune subentrato in ANPR. La prima volta che questo è accaduto, a marzo 2017, avevo capito che non si sarebbe ripetuta la circostanza.

**Comment by gcarbonin** [comment]
I codici fiscali possono essere rilasciati da AE e dagli uffici immigrazione; nel primo caso ci sono circostanze oggettive che suggeriscono di lasciare questa possibilità "attiva": se guardiamo i tempi di formazione dell'atto di nascita e di comunicazione all'ufficio anagrafe, da normativa arriviamo anche a 23 giorno; i genitori hanno necessità di scegliere il pediatra subito, operazione che si può fare soltanto se il bambino possiede un codice fiscale. E' comune in corso l'emanazione di un decreto che ha l'obiettivo quello di risolvere questo problema. Nel secondo caso, è noto che per rilasciare un permesso di soggiorno la persona deve avere un codice fiscale.
