### ISSUE TITLE
Data Validità Cittadinanza - AIRE

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2370]
Buongiorno,
Ambiente di Produzione. Aono a chiedere informazioni in merito all'ISCRIZIONE ALTRI MOTIVI AIRE - WS A002 in quanto abbiamo verificato che un cittadino iscritto AIRE è stata inserita automaticamente la Data Validità nel tag Cittadinanza uguale alla data di iscrizione AIRE. Come esempio, posso indicare il cittadino 95146383 IDOperazione 365537711. Preciso, inoltre, che il cittadino in oggetto risulta essere di cittadinanza italiana da PRIMA dell'iscrizione AIRE. Ovviamente questa data incide sulla stampa del Certificato Storico di Cittadinanza, riportando una data non vera rispetto alla situazione del cittadino.
Come da tracciato ANPR, la Data Validità non è un campo obbligatorio (infatti nell'IDOperazione citata non è stato inviato).
Nella issue #2066 la soluzione proposta è quella di effettuare una 5008 con tipo=2 ma, come da immagine sottostante
![immagine](https://user-images.githubusercontent.com/46593834/100760422-0988e200-33f2-11eb-9840-787c2b8b4a45.png)
non risulta possibile. La issue #2066 è riferita ad Ambiente di TEST.
Resto in attesa di un gradito riscontro
Cordiali Saluti

**Comment by ncapozzi** [comment]
Buonasera,
potete provare ad effettuare la 5008 con tipo=2 dal gestionale?

**Comment by fcastellani81** [comment]
Buonasera,
prima di effettuarla dal gestionale, gradirei provarla direttamente su WebAPP però, come indicato, non risulta possibile.
Inoltre, sono a richiedere il motivo per il quale venga attribuita una data "casuale" (visto la non obbligatorietà prevista dai tracciati) anzichè lasciare libero il campo Data Validità.
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
l'iscrizione AIRE assume di default che il cittadino abbia cittadinanza italiana, anche perché diversamente non potrebbe essere iscritto all'AIRE. Se non espressamente indicata tale cittadinanza , la si assume di default con data di inizio validità = data decorrenza iscrizione come era stato indicato nella issue #2066 cui le stesso fa riferimento.

**Comment by ncapozzi** [comment]
Consentiremo dall'applicazione di eliminare e reinserire ad una data diversa la cittadinanza ITALIA come già avviene per gli altri stati.

**Comment by ncapozzi** [comment]
Buonasera,
la modifica è stata rilasciata in produzione
