### ISSUE TITLE
Ticket #2344 e  #2358: problemi con eliminazione divorzio

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2371]
Buongiorno, facciamo seguito ai ticket #2344 e  #2358: abbiamo eliminato il cambio di indirizzo e dobbiamo procedere con l'eliminazione del divorzio, ma in eliminazione dati c'è solo la voce "matrimonio non "divorzio". Se clicchiamo su "matrimonio" eliminiamo solo i dati del divorzio o anche quelli del matrimonio? E se elimino questi ultimi, posso poi inserirli nuovamente? e da che data?
Se possibile vi chiederei di contattarmi. Vi lascio il mio interno, mi trovate questa mattina fino alle 12:00 circa 0544/482275.
Grazie
L'Ufficiale d'Anagrafe
Federica Dell'Anno

**Comment by rvinzani** [comment]
Con l'operazione eliminazione dati del matrimonio eliminate tutto ma poi potete inserire nuovamente i dati del solo matrimonio. Mi faccia sapere se è chiaro o se sia necessario contatto telefonico
