### ISSUE TITLE
Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune MILANO (MI)

### ISSUE THREAD

**Issue by anagrafemaiori** [italia/anpr#2372]
Salve, ,
in ambiente di produzione Maiori, nel tentativo di inviare una mutazione di residenza otteniamo l'errore che esiste un procedimento aperto nel Comune di Milano
Errore | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2020-11-30 11:22:53 , idOperazioneANPR 385485051
Errore | EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune MILANO (MI) con numero pratica ANPR: 23420842

Provato e riprovato a contattare Milano, ma senza avere mai risposta. 

E' possibile fare qualcosa considerato che il cittadino ha urgenza di essere iscritto nel nostro Comune?

**Comment by frmariani** [comment]
ho sollecitato il comune di Milano, Le farò sapere appena possibile. 
Continuate anche voi a sollecitare via PEC

**Comment by frmariani** [comment]
Milano ha chiuso il procedimento, potete ripetere l'operazione di mutazione di residenza

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
