### ISSUE TITLE
[4001] EN479 chiarimento

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2374]
Buongiorno 
per il comune di FENEGRÒ inviando una 4001 id operazione comune 20201116092532684 in produzione
specificando `<comuneRichiesta>
<nomeComune>FENEGRO'</nomeComune>
<codiceIstat>013100</codiceIstat>
<siglaProvinciaIstat>CO</siglaProvinciaIstat>
</comuneRichiesta>`
torna in errore "Comune della richiesta errato:  i dati indicati sono incongruenti"
risolto modificando il nome comune mettendo la lettera accentata "Ò"

facendo delle prove inviando una 1002 con luogo nascita la descrizione che non veniva accetta
`<luogoNascita>
<comune>
<nomeComune>FENEGRO'</nomeComune>
<codiceIstat>013100</codiceIstat>
<siglaProvinciaIstat>CO</siglaProvinciaIstat>
</comune>
</luogoNascita>`

in presubentro id operazione anpr 20645156 comune 041010

non mi è chiaro perché la stessa denominazione in un caso viene accettata e nell'altro no

Grazie mille
Riccardo

**Comment by rvinzani** [comment]
Il 1002 utilizza per la verifica anche la dizione traslitterata.
