### ISSUE TITLE
Errore Anpr Cod: EN469 - Il soggetto risulta iscritto anche nel comune di CITTADUCALE Con data iscrizione 05-04-2004

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2376]
COMUNE DI TERRASINI PRODUZIONE 

Il comune sta cercando di fare una mutazione convivenza famiglia APR per cambiare indirizzo alla persona.
All'invio della pratica in ANPR l'errore è il seguente: 

1 Errore Anpr Cod: EN469 - Il soggetto risulta iscritto anche nel comune di CITTADUCALE Con data iscrizione 05-04-2004 - Id Famiglia/Convivenza ANPR: 47081784 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-04 12:48:58 , idOperazioneANPR 389404702 - Id Famiglia/Convivenza ANPR: 47081784 Id Famiglia/Convivenza Comune: -
3 Errore Anpr Cod: EN395 - per il tipo di mutazione 7 saranno modificati soltanto i dati relativi a revisone onomastica - Id Famiglia/Convivenza ANPR: 47081784 Id Famiglia/Convivenza Comune: -

Sembrerebbe che il comune di CITTADUCALE abbia iscritto la stessa persona, ma facendo una ricerca in ANPR risulta iscritto solo una persona con comune di competenza TERRASINI.

ID SOGGETTO ANPR: 84990702

**Comment by frmariani** [comment]
Ci sono diverse precisazioni da fare:
1) l'operazione che state effettuando NON è il cambio di residenza di una persona ma una Revisione Onomastica dell'intera famiglia;
2) come da anomalia segnalata in fase di subentro, il soggetto idanpr 84990622 risulta iscritto come cittadino Aire anche nel comune di Cittaducale; dovete mettervi in contatto con l'altro comune e verificare dove risieda effettivamente il cittadino; nel caso, o voi o l'altro comune dovrete effettuare una "cancellazione per doppia iscrizione"; 
3) La doppia iscrizione in fase di consultazione è riscontrabile tramite l'operazione di Consultazione "Nazionale " utilizzando il codice fiscale del cittadino

**Comment by jonnyfx95** [comment]
Grazie mille.
Il problema sicuramente è dovuta alla doppia iscrizione del soggetto 84990622 che un componente della scheda di famiglia.
Conattterò il Cittaducale è farò cancellare il nominativo per doppia iscrizione.

La segnalazione può essere chiusa.

Jonathan
