### ISSUE TITLE
Impossibile annullare l'operazione di MUTAZIONE FAMIGLIA CONVIVENZA

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2377]
Ambiente di Produzione Codice Istat Comune 015077.

1. Il giorno 23-06-2020 con Id Operazione 274446257 iscriviamo in anagrafe il cittadino per mutazione di residenza da altro Comune subentrato. (intero nucleo con unico componente I.S.)

2. Sempre il giorno 23-06-2020 con Id Operazione 274491983 si aggrega un altro cittadino al nuovo nucleo famigliare costituitosi questa volta per Iscrizione Altri Motivi APR.

3. Il giorno 27-11-2020 a seguito di accertamento negativo da parte dei Vigili si deve procedere con l'annullamento ex-tunc di entrambe le operazioni.

4. Il giorno 27-11-2020 il cittadino soggetto dell'Id Operazione 274491983 viene quindi cancellato con un'operazione di tipo  2003 Cancellazione a seguito di ripristino di posizione precedente con Id Operazione 383377065.

5. Annullando ora l'Id Operazione 274446257 di Mutazione Residenza APR da altro Comune Subentrato abbiamo l'anomalia.

L'OPERAZIONE DA ANNULLARE NON E' L'ULTIMA SUL SOGGETTO O SULLA FAMIGLIA.

Potete darci indicazioni?

Rimango in attesa di un Vs. gentile riscontro.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by rvinzani** [comment]
Avreste dovuto annullare l'operazione di iscrizione. Provate ad annullare la cancellazione e l'iscrizione e poi ad annullare nuovamente la mutazione di residenza. Attendo un vostro riscontro

**Comment by RBiasi** [comment]
Buongiorno Roberta,

quindi è errata la logica da noi adottata per cui a seguito di esito accertamento negativo da parte dei vigili di iscrizione altri motivi apr scateniamo il servizio 2003?

Mi chiedo allora quando si usi il servizio 2003 Cancellazione a seguito di ripristino di posizione precedente?

Senza contare che annullando l'operazione di iscrizione altri motivi il cittadino non è più visibile in ANPR mentre con il 2003 rimane traccia dell'annullamento per cancellazione a seguito di ripristino posizione precedente.

Attendo gentile riscontro.

Grazie

**Comment by rvinzani** [comment]
E' necessario utilizzarla in questo caso specifico allo scopo di annullare l'operazione di mutazione residenza effettuata sulla famiglia di destinazione.

**Comment by RBiasi** [comment]
Scusami Roberta, ho delle difficoltà a capire possiamo sentirci?

**Comment by rvinzani** [comment]
Certo, se sei d'accordo chiudo la issue . Ti chiamo appena possibile

**Comment by rvinzani** [comment]
Come da accordi aspetto vostra chiamata. Intanto chiudo la issue
