### ISSUE TITLE
MATRIMONIO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2378]
Buonasera,
Nel caso di comunicazione del matrimonio (WS5008) mutazione 12 come è possibile modificare contestualmente 
-  lo stato civile (da CEL/NUB a CGT)
- il legame tra i componenti
- la costituzione di un nuovo nucleo familiare

**Comment by rinonasti** [comment]
COMUNE CE 061022 PRE-SUBENTRO
ho modificato l' invio indicando anche tipo mutazione 01 indicando anche stato civili ma vengono chiesti anche tutti i campi non modificati. Perche'
<codiceErroreAnomalia>EN139</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Inserire tutti i dati anagrafici anche quelli non modificati</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-05 16:08:13 , idOperazioneANPR 20675763</testoErroreAnomalia> 
GRAZIE

**Comment by frmariani** [comment]
Con il WS 5008 tipo mutazione 1, oltre allo stato civile, si possono modificare anche i dati anagrafici del cittadino, pertanto anche se non modificati,  devono essere indicati all'interno dell'xml di richiesta;
Per quanto riguarda la prima richiesta, non è possibile modificare contestualmente tutti i dati elencati; con il WS 5008 tipo mutazione 1 e 12 si può modificare lo stato civile del cittadino oggetto dell'operazione ed il matrimonio per entrambi i coniugi (soltanto se il coniuge è già presente in ANPR  e se viene individuato con idanpr o codice fiscale); successivamente si dovrà modificare lo stato civile dell'altro coniuge e con il WS 5001 tipo mutazione 2 si potrà modificare il legame di parentela; la costituzione della nuova famiglia sarà regolata dai cambi di residenza  se necessari.

A titolo di esempio, di seguito le operazioni da effettuare nel caso in cui il cittadino A, intestatario della famiglia, si sposi con il cittadino B, entrambi presenti in ANPR già conviventi:
Cittadino A intestatario della famiglia: WS 5008 tipo mutazione 1 per modificare lo stato civile e tipo mutazione 12 per inviare i dati del matrimonio indicando come coniuge l'idanpr o il CF del cittadino B;
Cittadino B : WS 5008 tipo mutazione 1 per modificare lo stato civile;
WS 5001 tipo mutazione 2 codice legame=2 per il cittadino B

**Comment by rinonasti** [comment]
ok grazie
