### ISSUE TITLE
[7001] ws - download tabelle decodifica

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#238]
Comune di Serravalle Sesia
Ambiente di Produzione

Da alcuni giorni il comune di Serravalle Sesia non riesce ad effettuare il download delle tabelle di decodifica causa un errore "Internal Error". 
Chiamando lo stesso servizio da ambiente di test di altri comuni, le tabelle vengono scaricate regolarmente.
Allego la richiesta e la risposta:
[serravalle.zip](https://github.com/italia/anpr/files/1152779/serravalle.zip)

**Comment by gcarbonin** [comment]
Può riprovare?

**Comment by siscomanpr** [comment]
Grazie, ora funziona.
