### ISSUE TITLE
PROBLEMA WS5001 - 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2380]
Buonasera,
COMUNE 061022
<listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EF038</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Quando si richiede la mutazione del tutore, occorre indicare i dati previsti in tal caso</testoErroreAnomalia>
                    </errore>
                    <errore>
                        <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-07 17:12:51 , idOperazioneANPR 20680189</testoErroreAnomalia>
                    </errore>

POTETE INDICARMI CORTESEMENTE QUALI
IL CASO E' LA SOSTITUZIONE DEL IS NEL NUCLEO PER DECESSO IS PRECEDENTE

Grazie

**Comment by frmariani** [comment]
l'operazione indicata corrisponde ad un WS 5001 tipo mutazione 1, utile per la modifica del Tutore della famiglia o Responsabile della convivenza;  nel vostro caso dovete utilizzare il WS 5001 tipo mutazione 2 utile per la modifica della composizione scheda famiglia

**Comment by rinonasti** [comment]
ok grazie
