### ISSUE TITLE
Errore Anpr Cod: EN248 - Soggetto gia' presente su ANPR #2367

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2382]
Riapro la segnalazione in riferimento a quella in oggetto.

La mutazione tutti dati con operazione sul codice fiscale da il seguente errore: 

1 Errore Anpr Cod: EN248 - Soggetto gia' presente su ANPR con CF XXXXXXXXX- Cognome: XXXXXX Nome: XXXXXCF: XXXXXXX-
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-10 12:19:38 , idOperazioneANPR 398829325 - Cognome: XXXXX Nome: VALDRIN CF: XXXXXXXXX-

**Comment by frmariani** [comment]
In quella che chiamiamo "inversione di link", devono essere indicati entrambi i codici fiscali: nelle "generalità per ricerca" deve essere indicato il CF presente in ANPR e nelle "generalità da modificare" deve essere indicato il cf da invertire.
