### ISSUE TITLE
Errore EN237

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2383]
In fase di invio di operazione di Mutazione di Residenza APR  IdOperazioneANPR 399707388 abbiamo l'errore EN237.

data 2020-12-11 09:53:35 IdOperazioneANPR 399707388

Non rileviamo operazioni successive al 13-10-2020 su entrambe gli enti.

Potete indicarci quale sia l'operazione che blocca?

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by frmariani** [comment]
C'è stata una revisione dell'indirizzo post accertamento il 2/11/2020 nella famiglia di immigrazione

**Comment by RBiasi** [comment]
Ringrazio per la risposta dobbiamo indicare al comune di annullare la rettifica di indirizzo?

In questi casi sarebbe la cosa corretta sarebbe non far scattare il controllo trattandosi proprio di una revisione post accertamento.

Attendo gentile riscontro.

Grazie 

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by frmariani** [comment]
L'operazione di revisione post accertamento precisa un indirizzo precedentemente dichiarato e sarà presente nello storico delle residenze del cittadino con il relativo articolo che ha autorizzato la modifica; questo è il motivo per cui deve seguire gli stessi controlli del cambio di residenza canonico

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
