### ISSUE TITLE
Certificato residenza e/o Residenza storica alla data di iscrizione di cittadino senza cognome

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2384]
Buongiorno,
ufficio Legale ci richiede certificato di residenza di soggetto ID ANPR 91981734 che risulta essere senza cognome (con flag inserito). 
La richiesta restituisce errore: 
La richiesta non risulta valida secondo i nuovi XSD [cvc-complex-type.2.4.a: Invalid content was found starting with element 'nome'. One of '{cognome, senzaCognome}' is expected.] (Codice: EN489)
La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)
Cortesemente, come dobbiamo procedere?
Grazie

UPI Torino

**Comment by rvinzani** [comment]
State operando dalla web app o dal gestionale?

**Comment by rvinzani** [comment]
Come da comunicazioni intercorse chiudo la issue per risoluzione del problema
