### ISSUE TITLE
1001 - filiazione 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2385]
Buonasera comune Caserta 061022
con operazione: data 2020-12-11 16:03:23 , idOperazioneANPR 20702269
abbiamo inserito cognome e nome padre
da errore: <codiceErroreAnomalia>EN144</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Soggetti padre/madre non in ANPR</testoErroreAnomalia>

togliendo il cognome e nome del padre:

<codiceErroreAnomalia>ES036</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Indicare i dati relativi alla paternita' quando filiazione e' 1=dei genitori o 2=del padre</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-11 16:20:27 , idOperazioneANPR 20702307</testoErroreAnomalia> 

Grazie

**Comment by frmariani** [comment]
nell'operazione idanpr 20702307, è indicato che il bambino è iscritto nella famiglia dei genitori, quindi entrambi i genitori devono essere presenti in ANPR; indicate la paternità così come avete indicato la maternità

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
