### ISSUE TITLE
[6001] Famiglia non certificabile

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2386]
Si presenta il cittadino id 91815432, per richiedere certificato di residenza e stato di famiglia.
Da ANPR ricevono l'errore "I certificati di stato di famiglia,  stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile"

I famigliari nella scheda "Errori/Anomalie da subentro" hanno l'errore EN212 "Relazioni di parentela incongruenti per la famiglia, verificarle prima di emettere certificati di stato di famiglia". 
Sono però subentrati in altro comune, e il 24.11.2020 si sono spostati nel'attuale Comune. Avendo cambiato comune di residenza, le relazione di parentela sono state modificate e appaiono corrette.
E' normale che rimanga l'errore? Come fare per azzerarlo?

**Comment by mttfranci** [comment]
Salve, 
La segnalazione non dipende dal subentro del precedente comune ma dal fatto che il soggetto  : 
91815432 è intestatario della famiglia, un altro soggetto delle stessa famiglia è indicata come meglio, ma per il soggetto 91815432  non è registrata la sezione del matrimonio (e ovviamente neanche per ma moglie).
E' possibile sanare la situazione registrando il matrimonio tra i due soggetto o forzare la certificazione.
Siamo a disposizione per ogni ulteriore chiarimento,

**Comment by MarcoMigliori** [comment]
Grazie, il comune ha verificato che con la forzatura il certificato esce.
