### ISSUE TITLE
Codifica comune BARCE

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#2389]
Buongiorno,
abbiamo necessità di inserire l'atto di nascita di un cittadino nato il 01/04/1940 a Barce: il Comune di Barce, attualmente in Libia, nel 1940 era italiano infatti abbiamo un atto in parte prima serie A fatto allo Stato Civile del Comune di Barce.
ANPR non l'accetta. Come possiamo fare?
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
il Comune di Barce non risulta presente nell'archivio storico ISTAT al quale fa riferimento ANPR.

Potete indicare in alternativa il nome del comune che ha trascritto l'atto?

N. Capozzi

**Comment by anozzoli** [comment]
Buongiorno, la riposta è no. Se posssibile Le vorrei mandare privatamente copia del documento da registrare.

**Comment by ncapozzi** [comment]
Può scrivere a assistenza.anpr@pec.sogei.it. 
--

**Comment by ncapozzi** [comment]
Buonasera,
avete trasmesso l'email? Se si, da quale casella?

**Comment by ncapozzi** [comment]
Non avendo ricevuto ulteriori riscontri si chiude la issue

**Comment by anozzoli** [comment]
Buongiorno dottoressa Capozzi, come da sua indicazione in data 17/12/2020 ho inviato email all'indirizzo assistenza.anpr@pec.sogei.it con la mia email a.nozzoli@comune.prato.it ma non ho mai avuto risposta. Attendo notizie. Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
le confermo che non abbiamo ricevuto l'email, probabilmente perché è stata trasmessa da un casella di posta PEL a una PEC

**Comment by anozzoli** [comment]
abbiamo rimandato l'email con l'indirizzo PEC anagrafestatocivile.prato@postacert.toscana.it

**Comment by ncapozzi** [comment]
Ricevuta ped, verifichiamo con ISTAT e Agenzia delle Entrate

**Comment by ncapozzi** [comment]
Buongiorno,
abbiamo risposto al quesito via pec

N. Capozzi
