### ISSUE TITLE
Variazione di eventi storici

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#239]
Buongiorno ,
chiediamo cortesemente dei chiarimenti in caso di rettifiche  di eventi storici.
Per esempio, supponiamo di registrare la morte di un residente e la relativa vedovanza del coniuge superstite. Quest'ultimo nel tempo contrae secondo matrimonio. Se si palesa la necessita' di rettificare la data del decesso e relativa vedovanza ci pare di aver capito che non possiamo agire sui dati vedovanza perchè il coniuge superstite ha avuto un ulteriore operazione dopo la vedovanza, parimenti non possiamo modificare la data di decesso del residente perchè soggetto cancellato da ANPR. Come possiamo agire su questi casi di rettifiche sui dati storici?

Cordiali Saluti
Team Sipo
Comune di Bologna

**Comment by gcarbonin** [comment]
Tecnicamente si annulla la cancellazione per decesso e la si trasmette nuovamente con la data corretta.; questo sistema anche i dati della vedovanza del coniuge superstire.
Da un punto di vista "normativo" ad una domanda analoga posta in altri contesti, il Ministero dell'Interno ha risposto che una scheda archiviata non è modificabile.
