### ISSUE TITLE
SECONDA PARTE PIN

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2390]
Buongiorno,
COMUNE CASERTA 061022

Iscritto nuovo utente e richiesta smart card.
Ricevuta quest'ultima dalla Prefettura ma non ha avuto mail con la seconda parte delle credenziali:
CODICE FISCALE
NNL........F839.

**Comment by Leonforte** [comment]
La smart card deve essere attiva dall'amministratore locale della sicurezza, si suggerisce di prendere visione della documentazione in allegato al capitolo 10. Cordiali saluti.

[Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro v.3.pdf](https://github.com/italia/anpr/files/5695967/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.v.3.pdf)
