### ISSUE TITLE
[7002] EN122 anomalo

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2391]
Buongiorno da ieri sera ci sono dei problemi, non tornano i dati di cittadini correttamente presenti

idOperazioneANPR>20713316
PRESUBENTRO comune 041010

ho provato la consultazione del cittadino con ID ANPR 148452153 e la 3002 ritorna tutto correttamente
idOperazioneANPR>20713324

Forse lo stesso problema c'è in PRODUZIONE (ma non ho potuto ancora verificare)
per il comune di GRUMELLO DEL MONTE richiedendo le risposte dell'operazione 402698479 (id della 4001)

**Comment by amollicone1982** [comment]
I problemi sono stati risolti e i file elaborati di nuovo
