### ISSUE TITLE
Errore EN237 - II Segnalazione

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2392]
Buongiorno,

con riferimento alla ISSUE sotto, mi scuso, ma non ho ricevuto risposta al mio quesito: dobbiamo indicare al comune di annullare la rettifica di indirizzo?

https://github.com/italia/anpr/issues/2383

La data di decorrenza della residenza del cittadino deve essere quella in cui egli rende la dichiarazione all'ufficio anagrafe, non possiamo certo cambiarla per dei controlli di validazione (che è mia opinione non dovrebbero esistere).

Attendo gentile riscontro.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
