### ISSUE TITLE
PIANO E DATA SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2393]
Buonasera,
COMUNE DI CASERTA 061022
Su stato subentro del portale ANPR risulta:
Ti informiamo che non risulta acquisita una data prevista di subentro il comune. Per poter procedere al subentro è necessario che il vostro fornitore software comunichi sulla dashboard del Team digitale la data prevista per il subentro.
Non esiste alcun piano di subentro.

E' stato inserito e questo è quello scaricato in csv:

id_comune,codice_istat,nome_comune,prima_data_subentro,ultima_data_subentro,data_subentro_preferita
--
1479,061022,CASERTA,10/12/2020,31/12/2020,22/12/2020

Come mai viene riportata l'anomalia?
Grazie

**Comment by cmigliardi** [comment]
Buonasera, per il subentro di Caserta  avete indicato  il 22-12-2020   e oggi  è  15-12-2020 . molto semplicemente  fino a quella data non è possibile effettuare il subentro.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
