### ISSUE TITLE
MONITORAGGIO OPERAZIONI - NOTIFICA MUTAZIONE DI RESIDENZA CON RIFERIMENTO ISSUE (#2365)

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2394]
COMUNE DI CAPONAGO

Buongiorno
durante l'invocazione del servizio 4500 ottieniamo come response un errore, si allegano i file chiamata e risposta.
[Richiesta4005.txt](https://github.com/italia/anpr/files/5701159/Richiesta4005.txt)
[message_in.txt](https://github.com/italia/anpr/files/5701160/message_in.txt)
[message_out.txt](https://github.com/italia/anpr/files/5701161/message_out.txt)

Potete per cortesia verificare quale anomalia si verifica e fornirci indicazioni in merito ?

Grazie

**Comment by GabriellaBallabio** [comment]
Buongiorno
con riferimento alle Issue #2365 e #2394 non abbiamo ancora ricevuto riscontro pur essendo passati ormai 18 giorni. 
Potete cortesemente fornirci supporto ?
Grazie

**Comment by rvinzani** [comment]
Salve, i file allegati a cosa si riferiscono? qual'è esattamente il messaggio inviato ad ANPR?

**Comment by GabriellaBallabio** [comment]
Viene invocato il metodo 4005 con il file xml Richiesta4005.xml (abbiamo allegato Richiesta4005.txt il file in formato xml non possiamo inviarvelo)

il file message_in.txt è la risposta di ANPR

**Comment by gife67** [comment]
Buona sera,
si evidenzia sia sul messaggio che state inoltrando (message_out.txt) e sia dalla risposta ricevuta (message_in.txt), che nella cornice di sicurezza prevista per invocare i servizi ANPR, manca la componente di Signature relativa al Timestamp ed al body del messaggio, mentre è presente solo la SAML assertion. Cortesemente dovreste verificare. 
Se avete implementato il client dai sorgenti di esempio, dovreste aggiungere la policy nel file cxf.xml, potrebbe essere quello il problema.
Giuseppe

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
