### ISSUE TITLE
PIANO SUBENTRO RIF. #2393

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2395]
OK grazie.
E' per questo motivo che viene evidenziato  nella WA (subentro) che non esiste un piano di subentro?

Bisogna attendere una conferma a mezzo pec o il giorno stabilito sui procede con il subentro?

**Comment by cmigliardi** [comment]
non deve attendere  conferme  - se sulla  dashboard è registrata  va bene così- solo  che  il  subentro  si può effettuare  solo il girono che avete stabilito

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
