### ISSUE TITLE
idOperazioneANPR 404037951 (Codice: EN527)

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2396]
Richiesta assistenza per 

Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-16 14:25:53 , idOperazioneANPR 404037951 (Codice: EN527)

Trattasi di cittadino attualmente in ANPR Id scheda attribuito da ANPR 95998193 nato JUGOSLAVIA per cui dobbiamo rettificare luogo di nascita e CF attribuendo il corretto luogo di nascita KOSOVO.

In AE il cittadino risulta in possesso di CF JUGOSLAVIA con collegato CF KOSOVO.

Attendiamo gentile riscontro.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by ncapozzi** [comment]
Buongiorno,
nella richiesta 5008 è stato impostato gestioneCF = 3 senza validazione del CF mentre avrebbe dovuto essere gestioneCF = 0 per la validazione del CF.
Faccio presente che cambiando  lo stato estero di nascita da Jugoslavia Z118 a Kosovo Z160, Agenzia Entrate effettuando la validazione attribuirà un nuovo CF al cittadino collegandolo all'attuale.
N. Capozzi
