### ISSUE TITLE
Modifica decorrenza emigrazione

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2397]
Buongiorno,
da un controllo anagrafico ci siamo accorti che la cittadina ID 19156773 e il minore ID 19156778 sono stati cancellati nel 2019 da Anpr per emigrazione in altro comune non subentrato con una decorrenza non corretta.
Avremmo quindi la necessità di modificarla da 27.09.2019 a **23.07.2019**.
Ieri ho tentato di correggerla riaprendo la pratica, ma non ci sono riuscita in quanto tra le due decorrenze e precisamente in data 25.09.2019, si era provveduto a rettificare il suo stato civile e il suo cognome.
Come si può procedere quindi a rettificare la data di decorrenza di emigrazione?
Grazie per la collaborazione
Uff. Anagrafe

**Comment by ncapozzi** [comment]
Buongiorno,
in ANPR può annullare le cancellazioni e rieseguirle con la data di decorrenza corretta. 
Per quanto riguarda la gestione della pratica, che non è di pertinenza di ANPR, le suggerisco di contattare la sua casa software.

N. Capozzi

**Comment by ACastelleone** [comment]
Buongiorno, avevo già provato a cancellare il soggetto con la decorrenza corretta, tuttavia nel momento dell'invio della notifica al sistema di anpr esce questa dicitura: "Rilevata presenza di un'operazione di registrazione già effettuata con decorrenza ANPR del 25.09.2019 per il cittadino cod....". 
Il 25.09.2019 è la data di decorrenza delle rettifiche dello stato civile e del cognome. 
Grazie infinite 

----- Il 17-dic-20, alle 12:52, ncapozzi <notifications@github.com> ha scritto:

**Comment by ncapozzi** [comment]
Buongiorno,
il messaggio di errore da lei segnalato non è tra  restituiti da ANPR ma probabilmente è dovuto ad un controllo effettuato dal suo gestionale. Posso solo suggerirle nuovamente di contattare la sua casa software.

**Comment by ACastelleone** [comment]
Buongiorno, per cortesia, per risolvere la problematica, mi puoi indicare la procedura corretta per modificare la decorrenza della cancellazione direttamente nella Webapp? Grazie 

----- Il 18-dic-20, alle 11:28, ncapozzi <notifications@github.com> ha scritto:

**Comment by ncapozzi** [comment]
Buongiorno,
se mi indica un recapito telefonico glielo spiego a voce.

**Comment by ACastelleone** [comment]
tel 0374 356318 
grazie 

----- Il 29-dic-20, alle 14:14, ncapozzi <notifications@github.com> ha scritto:
