### ISSUE TITLE
EMIGRAZIONE COMUNE SUBENTRATO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2398]
Buongiorno,

la cancellazione avviene nel momento in cui il comune di arrivo effettua la mutazione di residenza
WS5001 o WS5005 ?
il comune di partenza non deve effettuare alcuna operazione?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
nel cambio di residenza tra comuni subentrati il comune di partenza non deve effettuare alcuna operazione. Il comune di arrivo deve effettuare un 5001 se si sposta tutta la famiglia. Deve invece essere effettuato un 5005 se uno o più componenti della famiglia, ma non tutti si spostano per costituire una nuova famiglia, oppure se i cittadini che si spostano si trasferiscono in una famiglia già esistente nel comune di arrivo.

N. Capozzi
