### ISSUE TITLE
WS5005 - IMMIGRAZIONE DA COMUNE SUBENTRATO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2399]
Buonasera,
COMUNE DI CASERTA 061022
Nella risposta al servizio WS5005 - cambio di residenza da comune subentrato - non viene riportato id ANPR del cittadino.
Es. operazione ANPR 20724948

**Comment by azabatta** [comment]
Buonasera, 
la risposta di ANPR è funzione delle modalità di colloquio utilizzate.
Se si utilizzano i ws la risposta è sintetica, se è stato assegnato un nuovo identificativo riportano la relativa sezione (es. mutazione residenza con attribuzione nuova famiglia riporta la sezione famigliaConvivenza)
Se si utilizza la web app la risposta è estesa per consentire ai gestionali di lavorare correttamente le notifiche di tipo NRIS.
Per maggiori dettagli si consiglia di consultare la issue 1079 (https://github.com/italia/anpr/issues/1079).
Per il futuro, quando si specificano degli identificativi (operazione, soggetto etc.) si chiede cortesemente di indicare l’ambiente di riferimento.
