### ISSUE TITLE
[5001] Anomalia legata al procedimento aperto per Iscrizione

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#24]
Nel contesto della gestione delle pratiche di iscrizione:

1)	Apro un procedimento per iscrizione (1014)
2)	Invio l’iscrizione per altri motivi (1002)
3)	Invio eventuali Mutazioni (ad e.:  un 5008 per completamento dati atto di Nascita, oppure un 5001 per modifica indirizzo (completamento dei dati del civico, ad esempio, dopo sopralluogo vigili urbani)).
4)	Chiudo il procedimento aperto in precedenza (1014)

Nella fase 3, 
se nella Mutazione inviata **includo il riferimento al procedimento aperto in precedenza**, ho l’anomalia:
```
        <codiceErroreAnomalia>EN114</codiceErroreAnomalia>
        <tipoErroreAnomalia>W</tipoErroreAnomalia>
        <testoErroreAnomalia>Il procedimento indicato non è congruente con il servizio</testoErroreAnomalia>
```

se nella Mutazione inviata **non includo il riferimento al procedimento aperto**, solo nel caso del servizio 5001 (e probabilmente anche nel 5005),  ho l’anomalia:
```
      <anomalie>
        <codiceErroreAnomalia>EN111</codiceErroreAnomalia>
        <tipoErroreAnomalia>W</tipoErroreAnomalia>
        <testoErroreAnomalia>Indicare il procedimento collegato al servizio</testoErroreAnomalia>
      </anomalie>
```

**Comment by gcarbonin** [comment]
La segnalazione di anomalia sarà eliminata
