### ISSUE TITLE
Nuovi rapporti di parentela

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#240]
Buongiorno, in ambiente di TEST per il Comune di Bologna:
ID operazione comune
20170712163824056679056679F73B
ID operazione ANPR :
543279

Abbiamo cancellato per morte il soggetto con C.F. SHKSLZ86M15Z249Y, data evento 18/06/2017.
Contestualmente abbiamo indicato i nuovi rapporti di parentela della famiglia con ID Comune: 706034
Tale famiglia è costituita dal 21/07/2011 ed i suoi componenti dopo il decesso del soggetto sopra indicato sono:
C.F. KHTNPI88R61Z249N a partire dal 25/09/2013
C.F. TNSTMH14T49A944E a partire dal 09/12/2014

Nell'oggetto "legamesoggetto" NON abbiamo indicato le reali ed invariate date di decorrenza dell'appartenza alla famiglia, ma PER ERRORE la data dell'ultimo cambio di indirizzo 06/10/2015.

Accedendo con WA abbiamo riscontrato il cambio dei rapporti di parentela e la permanenza, GIUSTAMENTE, delle date ORIGINARIA dell'appartenenza a famiglia.

L'esito dell'operazione è OK senza anomalie legate alla del tag .
Alcune domande.

    Poichè la data di decorrenza è obbligatoria, quando richiediamo le variazioni di parentela possiamo NON PREOCCUPARCI del valore della del tag ?
    Se invece vogliamo rettificare la data di appartenenza a famiglia di un soggetto , WS 5001, la data che indicheremo verrà utilizzata dal WS per aggiornare il dato in ANPR?

Cordiali Saluti
Team Sipo
Comune Bologna

**Comment by gcarbonin** [comment]
Attualmente : la data di appartenenza della persona ad una famiglia prima si aggiorna solo con l'iscrizione o una mutazione di residenza con costituzione di nuova famiglia; la data di decorrenza del legame si aggiorna solo con il 5001.
Manca la seconda data nel subentro (intervento di prossima realizzazione).
Queste date non sono rettificabili se non annullando l'operazione e ritrasmettendola correttamente.
