### ISSUE TITLE
WS5008 - MUTAZIONE DATI ANAGRAFICI

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2400]
Nel caso di variazione di dati rilevanti ai fini del codice fiscale questo viene ricalcolato da AE e inviato nella risposta?
Grazie

**Comment by azabatta** [comment]
Buongiorno, 
sì, a fronte di una richiesta di mutazione di dati anagrafici Agenzia Entrate restituisce il nuovo codice fiscale che risulterà già collegato con il precedente. La mutazione comporta in automatico l'aggiornamento del codice fiscale in ANPR.
Il campo "gestioneCF" della sezione "datiControllo" si valorizza con la richiesta di validazione (zero):  sulla base dei nuovi dati anagrafici Agenzia Entrate stabilisce se la mutazione comporta o meno l'attribuzione di un nuovo codice fiscale.

**Comment by rinonasti** [comment]
nella documentazione:
gestioneCF

0=nessuna   azione     1=richiesta attribuzione     2=richiesta omcodice     3=forza mutazione senza controllo CF

sembrerebbe = 1

**Comment by azabatta** [comment]
1 è richiesta attribuzione (si utilizza quando il cittadino non un CF attribuito da Agenzia Entrate), mentre con 0  il sistema effettua comunque una validazione del CF in Agenzia Entrate, il discorso vale in generale anche per gli altri servizi che prevedono   "gestioneCF".
La titolarità del CF è di Agenzia Entrate che valuta se, a fronte di una variazione dati anagrafici,  scaturisce un nuovo CF o meno.
