### ISSUE TITLE
Certificazione Online Sindaco

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2401]
Buongiorno,
affinchè risulti il Cognome e nome del Sindaco del Comune nell'emissione dei certificati online, è necessario impostare il profilo Sindaco con le seguenti modalità, giusto?
![immagine](https://user-images.githubusercontent.com/46593834/102604152-10b72c00-4124-11eb-8ca3-3309f126283a.png)
Ho notato, però, che ora il Tipo Utente dell'utente Sindaco non è più, appunto, SINDACO ma Operatore.

Esiste un'altra soluzione a riguardo oppure non è un problema avere il Sindaco come Tipo Utente Operatore?
Resto in attesa di cortese riscontro
Cordiali Saluti

**Comment by Leonforte** [comment]
Buongiorno, non c'è alcuna relazione tra il profilo del sindaco e la firma in calce ai certificati emessi on line, la quale è personalizzabile attraverso l'apposita sezione della web app Amministrazione - Gestione Dati del Comune - Parametri utilizzati per l'emissione dei certificati online, come mostrato nella sottostante figura. Se non compilata i certificati sono emessi automaticamente a nome del sindaco.

![immagine](https://user-images.githubusercontent.com/26482932/102772369-aa324800-4387-11eb-968f-4d2fffe21824.png)

**Comment by fcastellani81** [comment]
Buongiorno,
grazie per la risposta. L'immagine riportata mi permette di personalizzare il Titolo del responsabile con un campo testuale, giusto? (es. Responabile Ufficio Servizi Demografici, ecc..) ma il nome e cognome sotto riportato è del codice fiscale di un utente abilitato alla certificazione, giusto? Il profilo Sindaco, normalmente, è abilitato solamente con il flag Sindaco/commissario e non ha possibilità di certificazione (almeno da quanto ho potuto verificare invocando il ws della certificazione con il cf del Sindaco).
Quindi, non è un problema se ho flaggato entrambe i profili?
grazie
Buona giornata

**Comment by Leonforte** [comment]
Tutto giusto, buona giornata

**Comment by fcastellani81** [comment]
perfetto!
grazie
Buona giornata
