### ISSUE TITLE
Modifica dataDecorrenza

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#2402]
Salve,
avremmo la necessità di modificare la data a partire dalla quale il soggetto appartiene alla famiglia/convivenza ante-subentro. 
Con quale comunicazione e con quale motivo è possibile effettuare tale variazione.
Grazie

**Comment by gianpaol** [comment]
[https://www.anpr.interno.it/portale/documents/20182/260132/Gestione_scheda_soggetto.pdf/dd8c6418-69e0-4e02-a61e-28764f0632d9](url) Nel pdf di cui ho messo il link dalla pagina 65 è illustrato il procedimento di rettifica delle date. Non sono molto esperto ma credo che questo pdf faccia proprio al caso tuo.

**Comment by frmariani** [comment]
L'operazione da effettuare è proprio quella di Rettifica indicata nel post precedente; naturalmente la data dovrà essere congruente ad altre date riferite al cittadino; se vuole indicarmi l'idanpr  del cittadino e la data corretta potrò essere più precisa

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
