### ISSUE TITLE
Procedimento aperto comune di MILANO

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2403]
COMUNE DI CINISELLO BALSAMO PRODUZIONE

Buongiorno, 

Il comune di Cinisello balsamo non riesce ad iscrivere una persona tramite mutazione residenza APR in quanto risulta che il comune di MILANO per questo soggetto ha ancora aperto un procedimento.
Il comune ha provato a contattare più e più volte MILANO per fargli chiudere il procedimento, ma non hanno ricevuto alcuna risposta.

E' possibile provvedere alla chiusura da parte vostra?

1 Errore Anpr Cod: EN531 - Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune MILANO (MI) con numero pratica ANPR: 26129241 - Id Famiglia/Convivenza ANPR: 50813662 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-21 11:55:34 , idOperazioneANPR 407658025 - Id Famiglia/Convivenza ANPR: 50813662 Id Famiglia/Convivenza Comune: -
3 Errore Anpr Cod: EN395 - per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza - Id Famiglia/Convivenza ANPR: 50813662 Id Famiglia/Convivenza Comune: -

ID ANPR:  91197869

**Comment by frmariani** [comment]
mi dispiace ma non possiamo operare in alcun modo; cercherò di sollecitare il comune di Milano alla chiusura del procedimento;
Le farò sapere appena possibile

**Comment by frmariani** [comment]
mi dispiace, ma nonostante i solleciti inviati in questi giorni, il Comune di Milano non ha ancora effettuato la chiusura del procedimento amministrativo in carico al cittadino; cercate di sollecitare anche voi tramite PEC del Comune.
Le farò sapere appena possibile

**Comment by frmariani** [comment]
il procedimento è stato chiuso e la residenza modificata, pertanto la issue viene chiusa
