### ISSUE TITLE
Mancato accesso in WEBAPP ANPR con NUOVE SMART CARD - GARNIGA TERME

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2404]
Buongiorno, apro questa segnalazione per conto del comune di GARNIGA TERME Subentrato in ANPR il 16/12/2020. 
Non riesce a fare l'accesso con la nuova smart card del sindaco/commissario e quindi richiedere il contributo. 
Il pc è stato correttamente configurato secondo le specifiche in rete, abbiamo installato il Safe drive e provato con tutti i browser (Ie, Chrome, Firefox (aggiornando anche IDP).  Il subentro è stato fatto con smart card di tipo vecchio. 
Viene riconosciuto il certificato di postazione ma inserendo il pin ERR BAD SSL CLIENT AUTH CERT

Abbiamo quindi fatto una verifica sul pin/puk dal sw Dike e non permette il cambio/reset del pin poichè segnala PUK errato. 
Abbiamo verificato quindi i nr. di serie della smart card e quello indicato sulle lettere riportanti i codici, rileviamo solo una differenza relativa al nr della smart card che riporta in più il codice 12071, per cui vi chiediamo se identifica il lotto di produzione o meno delle smart card. 

Nr serie smart card: 0220911207100000008623
Nr serie smart card su lettera cartacea Pin/Puk e su lettera via mail con 2° parte dei codici: 0220910000008623

Poichè abbiamo anche altri comuni che segnalano le stesse problematiche, vi chiediamo se possibile avere indicazioni in merito ad un eventuale lotto di smart card "corrotte" in maniera da fornire indicazioni più precise ai clienti ed evitare numerose chiamate al nr verde.  

Per un eventuale contatto di seguito i recapiti del Comune: 

Ufficio anagrafe: MONICA COLOMBO (presente al mattino fino al giorno 23/12) al nr 0461-842295

In calce i miei riferimenti.

Grazie 
Cordiali saluti

Cinzia Girelli
 HR – HD DEPLOY E PIATTAFORMA C. +39 3346216774 | T. +39 0461 381 515 int. 7576 Gruppo GPI I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599 
 www.gpi.it

**Comment by Leonforte** [comment]
Buongiorno, probabilmente la carta prodotta è corrotta e quindi non utilizzabile. E' stata effettuata una richiesta d'ufficio per una nuova emissione. La nuova carta sarà disponibile presso la Prefettura di competenza nell'arco di pochi giorni. Si ricorda inoltre che la richiesta del contributo è stata prorogata al 31/12/2021. Buon lavoro, saluti

**Comment by CGIRELLI-HUB** [comment]
E' possibile cortesemente capire come rilevare la corruzione delle smart
card?
Grazie

       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: info@gpi.it. L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno lun 21 dic 2020 alle ore 14:16 Leonforte <notifications@github.com>
ha scritto:

**Comment by Leonforte** [comment]
L'errore generico è relativo al PIN e PUK errati, nella maggiornaza dei casi abbiamo già provveduto al riproduzione de lotti corrotti e al conseguente invio presso le Prefetture, unitamente ad una nota informativa. Cordiali saluti
