### ISSUE TITLE
Mancato accesso in WEBAPP ANPR con NUOVE SMART CARD - TERRAGNOLO

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2405]
Buongiorno, apro questo ticket per conto del nostro cliente COMUNE DI TERRAGNOLO subentrato in ANPR in giugno, che ha ancora problemi con l'accesso in webapp con le nuove smart card del sindaco.

Questa di seguito riportata è la 3° smart card che inviate e nonostante la corretta configurazione della postazione (provato da tutti i browser e configurati come da vostre specifiche) non viene riconosciuta da nessun browser. Ho visto un caso dove indicate che se il certificato della smart card si vede in Altri Utenti delle Opzioni Internet è possibile che la smart card sia corrotta.  In questo caso è così.  
Poichè abbiamo saputo da altri clienti di un lotto di smart card corrotte vi chiediamo se possibile identificarle anche dal nr. serie o solo dal modo in cui si installa sulle opzioni internet. 

Nr di serie ultima smart card ricevuta: 022193120710000009419 
Le lettere con Pin e Puk riportano lo stesso nr mancante del codice 12071 presente sulla smart card fisica. 

Riferimento del comune: GABRIELLA MATTUZZI Tel. 0464/396122 - int. 1 Presente al mattino (eccetto i giorni 28 e 29 dicembre) 
I miei in calce. Segue ticket per il comune di Vicenza.

Grazie 
Cordiali saluti 

Cinzia Girelli
 HR – HD DEPLOY E PIATTAFORMA C. +39 3346216774 | T. +39 0461 381 515 int. 7576 Gruppo GPI I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599 
 www.gpi.it

**Comment by Leonforte** [comment]
Buongiorno, probabilmente la carta prodotta è corrotta e quindi non utilizzabile. E' stata effettuata una richiesta d'ufficio per una nuova emissione. La nuova carta sarà disponibile presso la Prefettura di competenza nell'arco di pochi giorni. Si ricorda inoltre che la richiesta del contributo è stata prorogata al 31/12/2021. Buon lavoro, saluti
