### ISSUE TITLE
Mancato accesso in WEBAPP ANPR con NUOVE SMART CARD - VICENZA 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2406]
Buongiorno apro questo ticket per conto del Comune di Vicenza che nonostante i ripetuti solleciti al nr verde non ha ancora ottenuto risposte.  Ticket n. 22091236 il 16.12.2020 

Il problema è il mancato accesso con le seguenti nuove smart card. 
Nonostante l'installazione e configurazione seguendo le vostre specifiche il problema è lo stesso per tutte le smart card: il PUK e il PIN (ricavati dalla mail e dalla lettera) risultano errati.

Codice comune: 024116
S/N 1207100000009182
S/N 1207100000009183
S/N 1207100000009184

Si prega di fornire quanto prima una risposta in merito. 

Riferimenti ced del Comune:  ps@comune.vicenza.it - 0444 - 221202
Riferimento responsabile anagrafe: Daniela Agostini 0444-221203

Grazie 
Cordiali saluti 

Cinzia Girelli
 HR – HD DEPLOY E PIATTAFORMA C. +39 3346216774 | T. +39 0461 381 515 int. 7576 Gruppo GPI I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599 
 www.gpi.it

**Comment by Leonforte** [comment]
Buongiorno, probabilmente le carte prodotte sono corrotte e quindi non utilizzabili. E' stata effettuata una richiesta d'ufficio per una nuova emissione. Le nuove carta saranno disponibili presso la Prefettura di competenza nell'arco di pochi giorni. Si ricorda inoltre che la richiesta del contributo è stata prorogata al 31/12/2021. Buon lavoro, saluti
