### ISSUE TITLE
INTERDIZIONE CARTA IDENTITA' NON RETTIFICATA

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2407]
Buongiorno,
per errore materiale al soggetto ID 28552332 è stata erroneamente inserita INTERDIZIONE ESPATRIO SI anzichè NO.
La Mutazione Tutti i dati restituisce "Operazione correttamente eseguita" ma rileggendo il soggetto successivamente l'indicatore resta a Interdizione SI
Restiamo in attesa di Vostre indicazioni, grazie
A.Maria Aimone
UPI Torino

**Comment by frmariani** [comment]
Con la mutazione dei dati possono essere modificati i dati della carta d'identità cartacea; per la modifica dei dati della CIE dovete utilizzare i servizi di CieOnLine

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
