### ISSUE TITLE
WS5001 - CAMBIO RESIDENZA 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2408]
Buonasera,
COMUNE CASERTA-061022
ambiente PRE
mutazione famiglia - immigrazione intero nucleo da comune subentrato

codiceErroreAnomalia>EN493</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-22 15:59:08 , mittente 061022 , idOperazioneComune 2020500100059</testoErroreAnomalia>

**Comment by rvinzani** [comment]
La risposta è analoga a quella data per la issue #2422
Chiudo la issue. in caso sia necessario ulteriore chiarimento si prega di aprirne una nuova che faccia riferimento a questa stessa
