### ISSUE TITLE
DATI SBAGLIATI PRESUBENTRO - ERRONEA ISCRIZIONE AIRE

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2409]
Un cittadino viene iscritto erroneamente all'AIRE (caso di omonimia) nel mese di settembre 2020. Egli è residente dal 2016 sempre allo stesso indirizzo nello stesso Comune. Il 09/11/2020 avviene il subentro ed ovviamente egli viene iscritto in ANPR come soggetto AIRE. Ora com'è possibile ovviare a questo errore mantenendo lo storico di residenza, cioè residente dal 2016 al vecchio indirizzo? C'è un modo per modificare l'indirizzo di residenza e la data di decorrenza della stessa a causa di errori materiali commessi prima del subentro?

**Comment by ncapozzi** [comment]
Buongiorno,
nel caso da lei descritto dovete cancellare il cittadino AIRE e reiscriverlo come residente con la data di decorrenza corretta impostando nelle generalità lo stesso idsoggettoANPR della scheda cancellata.
Se deve essere modificata la sola data decorrenza residenza trasmessa al subentro può utilizzare il servizio di rettifica.
Se deve essere corretto un indirizzo errato (ma senza modificare la tipologia residente o AIRE) può utilizzare la mutazione famiglia/convivenza con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO.

N. Capozzi
