### ISSUE TITLE
Disallineamenti codici fiscali

### ISSUE THREAD

**Issue by FrancescoPipitone** [italia/anpr#2410]
COMUNE DI ANZOLA DELL'EMILIA (BO) PRODUZIONE
Buongiorno. Cittadino id anpr 91306860 immigrato dal comune di Bologna titolare di C.F. numerico, presente in siatel con altro C.F. alfanumerico collegato a C.F. numerico diverso da quello attuale. Non riusciamo ad aggiornare i dati in siatel (marcare c.f. numerico) con la nuova residenza e nemmeno a collegare i codici fiscali dalla web app che ci propone la conferma dei dati AE e non quelli di ANPR quanto proviamo a risolvere il disallineamento.

**Comment by frmariani** [comment]
Ho provato a contattarla senza successo presso il comune, nel caso cortesemente invii un recapito al seguente indirizzo 
frmariani@sogei. it

Le riassumo le operazioni da effettuare: 
allineamento del cf numerico presente in ANPR;
collegamento dello stesso al cf alfanumerico corretto presente in AE

**Comment by frmariani** [comment]
Le operazioni consigliate sono state effettuate correttamente
