### ISSUE TITLE
ERRORE ISCRIZIONE AIRE - Data decorrenza antecedente ad ultima modifica

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#2411]
Buongiorno,
si ha un progblema per un cittadino emigrato in BRASILE per l'iscrizione AIRE. Nella famiglia erano iscritti due fratelli, uno è emigrato in brasile il 02/05/2020, in questi giorni è arrivato CONS01 del fratello con la data della domanda di iscrizione 06/04/2020.
Appena si prova ad inviare dà l'errore che è impossibile effettuare la mutazione in quanto esiste una mutazione in data 02/05/2020.
Identificativo scheda attribuito da ANPR: 68803246
Abbiamo provato inserirlo con decorrenza 02/05/2020 e successivamente effettuare la mutazione dei dati subentro ma non effettua la modifica, quindi abbiamo annullato tutto.
Come è possibile effetturale l'inserimento?
 L'unica idea era di eliminare  L'ID OPERAZIONE ANPR: 244703659 e poi successivamente rinserirla, ma non credo sia possibile dover effettuare sempre questi annullamenti in quanto questi casi sono frequenti.
Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera,
non solo deve essere annullata l'operazione 244703659 con la quale fratello2 è diventato intestatario della famiglia residente dopo l'emigrazione di fratello1 ma, se fratello1 è emigrato il 02/05/2020, fratello2 non può essere associato alla famiglia AIRE di fratello1 ad una data di decorrenza precedente il 02/05/2020. Dovete pertanto annullare anche la mutazione AIRE con cui è stato trasferito all'estero fratello1, effettuare la mutazione AIRE per fratello2 al 06/04/2020 ed infine ritrasferire all'estero fratello1 02/05/2020 nella famiglia di fratello2.

In alternativa, senza annullare l'operazione 244703659 e la mutazione AIRE di fratello1, se lo ritenete corretto potreste effettuare la mutazione AIRE per fratello2 in nuova famiglia e successivamente effettuare una mutazione AIRE di fratello1 nella nuova famiglia di fratello2 al 02/05/2020. 

N. Capozzi
