### ISSUE TITLE
RISOLUZIONE OMOCODIA

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#2412]
Buongiorno
al soggetto ID ANPR 64553906, ad agosto 2020 sono state rettificate le seguenti generalità: cognome, nome e data di nascita (giorno mese ed anno). Le rettifiche sono state fatte in più volte e sono stati generati più codici fiscali alfanumerici, tutti collegati fra loro. Ora il soggetto si è presentato all'Ufficio dell'Agenzia delle Entrate di Faenza lamentando che ha problemi con il cf perchè dalla posizione risulta essere stato residente nel Comune di Montichiari (dove non è mai stato).
Quando abbiamo rettificato le generalità la procedura non ha mai chiesto o segnalato l'omocodia.
Abbiamo provato da web app a richiedere l'omocodia (registrazione dati - gestione codice fiscale: richiesta omocodice, ma viene segnalato il seguente errore:
se il codice fiscale e' esistente, non e' possibile richiedere una nuova attribuzione/omocodia; (Codice: EN491)
Informazioni sull'operazione da fornire in caso di assistenza : data 2020-12-24 09:33:16 , idOperazioneANPR 410460097 (Codice: EN527)
Come possiamo risolvere la questione?
grazie
Barbara Malavolti

**Comment by frmariani** [comment]
Avete effettuato delle verifiche ? le modifiche ai dati anagrafici quindi sono state effettuate sul cittadino sbagliato ? 
gentilmente mi invii un telefono dove posso raggiungerla
frmariani@sogei.it

**Comment by frmariani** [comment]
Stiamo risolvendo la issue per le vie brevi
