### ISSUE TITLE
DOMICILIO DIGITALE ANPR

### ISSUE THREAD

**Issue by campagna2** [italia/anpr#2413]
Buongiorno,
poiché continuiamo a ricevere richieste di inserimento di domicilio digitale dai cittadini, ci sono novità in merito alla possibilità di segnalare il domicilio digitale in Anpr?
Grazie.

Annamaria Campagna
Comune di Imperia

**Comment by FilippoPapi** [comment]
buongiorno,
ad oggi i domicili digitali vengono acquisiti da AGID, nel corso del 2021 confluiranno in ANPR.
cordiali saluti
