### ISSUE TITLE
URGENTE - RISOLUZIONE DISALLINEAMENTO CF IN AE FALLITA

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2415]
Buongiorno, per il Comune di RUMO subentrato oggi 29/12/2020 è stata generata l'anomalia EAA40 sul soggetto avente ID ANPR: 104777188 - con CF BLLRLD39D08M156J -  Da Web App in Risoluzione disallineamenti con AE è stato scelto di confermare i dati del Comune poichè erano gli stessi presenti in AE ma questa operazione di fatto ha assegnato e validato il precedente CF BLLRLD39D08M157L cambiando anche il luogo di nascita. 
Il problema è il luogo di nascita che nel 1939 non era ZELBIO ma ZELBIO VALESIO, ma l'atto di nascita del soggetto riporta ZELBIO ed era già stato rettificato una volta in passato da AE che aveva riconosciuto il comune di ZELBIO e validato il CF. 
Vi chiedo se potete rettificare il  CF di tale soggetto in quello precedente BLLRLD39D08M156J onde evitare disguidi col soggetto vista l'età. Grazie 

Resto a disposizione per ulteriori informazioni.
Cordiali saluti

Cinzia Girelli
GPI SPA  +39 3346216774
www.gpi.it

**Comment by ncapozzi** [comment]
Buongiorno,
per invertire nuovamente il CF principale con il secondario è necessario effettuare la modifica del comune di nascita da ZELBIO VELESO a ZELBIO

**Comment by CGIRELLI-HUB** [comment]
Grazie ma funziona anche se il comune non è valido alla data di nascita?


Il Gio 31 Dic 2020, 13:14 ncapozzi <notifications@github.com> ha scritto:

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, stamattina abbiamo provato l'operazione suggerita ma non è riuscita completamente poichè non varia il CF.  Ha variato il Comune ma non il codice fiscale. Provando a cambiare codice fiscale segnala errore che non è possibile poichè validato. 
Potete contattare voi l'utente in maniera da seguirlo nelle operazioni? Contatto del comune: Fausto Garbato 0463530113 presente tutti i giorni meno il lunedì - dalle 08:30 alle 12:00 e dalle 14:00 alle 17:30 - Al mattino preferibile mercoledì. 
Grazie 
Cordiali Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
potete scrivere a entrate.archivioanagrafico@agenziaentrate.it chiedendo l'aggiornamento necessario.
N. Capozzi
