### ISSUE TITLE
[5001] Errore EN184 su convivenza vuota

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2416]
Comune di Trento, ambiente di produzione.

Con una mutazione 5001 tentiamo di assegnare un indirizzo ad una convivenza che in ANPR non ha componenti, solamente il responsabile. Il sistema ci risponde con l'errore  EN148 "Errore nel reperimento dati famiglia convivenza durante la residenza famiglia convivenza" (id operazione ANPR 414929201).

Non riusciamo a capire quale sia la causa del problema né come risolverlo, potete aiutarci ?

Grazie

**Comment by azabatta** [comment]
Buongiorno, 
la convivenza è stata comunicata in subentro priva dell'indirizzo per cui la mutazione  residenza non trovando il precedente indirizzo da storicizzare risponde con un errore. Manca anche la data di apertura della scheda.
Si suggerisce di  inserire ex-novo la convivenza, con le date storiche corrette,  e di archiviare quella  priva dell'indirizzo.

**Comment by busaster** [comment]
Grazie, indicheremo al comune di procedere come indicato.
