### ISSUE TITLE
Operazione non effettuabile

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2417]
COMUNE DI ZIANO PIACENTINO
-Ambiente di Produzione-
Buongiorno,
sembra che qualsiasi operazione di validazione o attribuzione sul CF venga rifiutata,
otteniamo sempre l'errore **AEE97 - Operazione non Effettuabile**

**Comment by Hdemografici** [comment]
Buongiorno
stessa  situazione per il comune di SERAVEZZA - PRODUZIONE
idOperazioneANPR 416472642

**Comment by lupor0x** [comment]
Buongiorno,

stessa situazione per altri Comuni che seguiamo, OPERAZIONE NON EFFETTUABILE nemmeno consultando il CF sul portale ANPR in Consultazione AE.

**Comment by raffaella30174** [comment]
Anche noi abbiamo lo stesso problema, ho chiamato il numero verde di Sogei, non hanno ricevuto comunicazioni di disservizio.
Restiamo in attesa?
Grazie
Raffaella Comune di venezia

**Comment by sfmodena** [comment]
Buongiorno,
stesso problema anche a Modena.

Grazie, saluti
Sonia Fiorini

**Comment by FilippoPapi** [comment]
buongiorno il problema è stato rimosso, la situazione è stata quindi ripristinata
