### ISSUE TITLE
WS5001 - CAMBIO RESIDENZA RIF #2408

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2418]
Buonasera,
è  possibile avere la diagnosi del problema posto con la issue   #2408 

Grazie per la fattiva collaborazione

**Comment by rvinzani** [comment]
La risposta è analoga a quella data per la issue #2422 
Chiudo la issue. in caso sia necessario ulteriore chiarimento si prega di aprirne una nuova che faccia riferimento a questa stessa
