### ISSUE TITLE
Dati vedovanza eliminati a seguito di mutazione matrimonio

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2419]
Buongiorno,
abbiamo notato che, sui soggetti in cui è inserita la vedovanza, a seguito di mutazione matrimonio (in cui magari vengono integrati o modificati alcuni dati del coniuge e/o dell'evento)  il sistema elimina tutti i dati presenti nella vedovanza lasciando solo la data evento.
Esempio:
Il soggetto con id anpr  72449742, aveva sia la data che il luogo evento per quanto riguarda la sezione vedovanza e, dopo aver effettuato una mutazione tutti i dati - matrimonio,  il sistema ha eliminato la parte relativa al luogo evento vedovanza.

Cordiali saluti
Floramo S.
UpiTorino

**Comment by frmariani** [comment]
al subentro, sono stati inviati i dati del matrimonio del cittadino idanpr 72449742, vedovo del cittadino X morto a ... il ...; 
ogni volta che vengono modificati i dati del coniuge, cosiddetto "extra anpr" il sistema assegna un nuovo identificativo al soggetto, perdendo di fatto i dati precedentemente inviati;
successivamente al subentro, il luogo del decesso del coniuge "extra anpr" fa parte dei dati della vedovanza, pertanto se le modifiche al dati del coniuge sono terminate, potete effettuare una mutazione dei dati della vedovanza ed inserire il luogo del decesso del coniuge defunto

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
