### ISSUE TITLE
Errori nel file di subentro di AnagAire

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#242]
Corbetta, ambiente di Produzione.

Buongiorno, risolvendo delle anomalie con l'agenzia delle entrate sui codici fiscali abbiamo riscontrato delle anomalie prima non segnalate su alcuni individui Aire:
- Nel file di subentro creato da AnagAire per i nati in Italia è stato compilato sia il campo Comune/Provincia che il campo località (riferito a località eccezionale);
- Nella residenza è stato compilato il campo presso con valori ritenuti non validi (nella fattispecie il carattere '/').
La presenze di queste anomalie non consente al comune di effettuare movimentazioni sui soggetti come si vede dal documento in allegato.
Vorremmo eliminare la località di nascita ma non ci è possibile perché nella nostra base dati non c'è mai stata ed è presente solo il comune italiano mentre possiamo ritrasmettere il campo presso senza '/', anche se facciamo presente che nella documentazione il campo è indicato come 'string' e non è indicato un range di valori che escluda il carattere '/'.
Infine si suggerisce anche di adeguare i controlli sul file di subentro da AnagAire in quanto non ha segnalato nessuna di queste casistiche che poi si sono rilevate bloccanti.
Grazie.
Luca Bonini
[segnalazioni soggetti aire.pdf](https://github.com/italia/anpr/files/1165196/segnalazioni.soggetti.aire.pdf)

**Comment by gcarbonin** [comment]
Buongiorno.  Il problema che mi sembra necessario risolvere è quello della località che difficilmente può essere inventata da AnagAire.
Se questa informazione non deve essere presente in ANPR, occorre eliminarla.
Serve una richiesta del comune al Ministero dell'Interno e possiamo poi intervenire noi.
Il campo presso lo sistemiamo.
Le specifiche di ANPR sono composte da vari documenti che vanno letti congiuntamente; molti controlli non possono essere messi negli xsd per evitare problemi di natura gestionale.
Nel documento di specifiche per i campi definiti come "AN" si dice che possono contenere soltanto numeri e lettere, quelli Dia1 e Dia2 che possono contenere soltanto numeri lettere e alcuni caratteri speciali (punto, virgola, trattino, apice). Stiamo mettendo noi istruzioni di conversione (da carattere speciale a spazio).
