### ISSUE TITLE
WS5005 - L'utente non dispone dei privilegi

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#2421]
Buongiorno

effettuando un trasferimento di famiglia ad altra famiglia, è stato restituito questo errore:
Errore N.:  1 di  2 Codice: EN493  Tipo: E                                    
**L'utente non dispone dei privilegi per eseguire l' operazione**                 
Errore N.:  2 di  2 Codice: EN527  Tipo: E                                    
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-01-07
13:23:38 , mittente 015146 , idOperazioneComune 20210107132337356152       

Abbiamo verificato la struttura del messaggio e i dati trasmessi, ma non siamo riusciti a risalire al problema; ieri sono state aperte più di 60 pratiche di cambio indirizzo, e solo questa ha dato errore.

Sarebbe possibile avere qualche indicazione su quali potrebbero essere le cause di questa segnalazione, così da mettere dei controlli a monte per evitare di bloccare l'operatività agli sportelli?

Ringraziando per la collaborazione saluto cordialmente

_Raffaella Tremolada_
Sistemi Informativi srl  per Comune di Milano

**Comment by rvinzani** [comment]
Salve, sembrerebbe che il codice fiscale del soggetto che state provando a modificare non esista in ANPR
Provate a consultarlo con un 3002 e lo potrete verificare.
In generale l'errore EN493 viene restituito se c'è qualche dato incongruente o non si dispone delle autorizzazioni per agire sul soggetto.
Se ne parla anche nelle issue #1574 e #1433
Saluti
Assistenza ANPR

**Comment by rvinzani** [comment]
Chiudo la issue. in caso sia necessario ulteriore chiarimento si prega di aprirne una nuova che faccia riferimento a questa stessa
