### ISSUE TITLE
WS5008 - Vedovanza

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2422]
Buongiorno
COMUNE CASERTA - PRE-SUBENTRO
<testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-01-12 12:47:44 , mittente 061022 , idOperazioneComune 2021500800020</testoErroreAnomalia> 

Grazie

**Comment by mttfranci** [comment]
Salve, sembrerebbe che il codice fiscale del soggetto che state provando a modificare non esista in presubentro.
Provate a consultarlo con un 3002 e lo potrete verificare.

In generale l'errore EN493 viene restituito se c'è qualche dato incongruente o non si dispone delle autorizzazioni per agire sul soggetto.

Se ne parla anche nelle issue #1574 e #1433

Saluti

Assistenza ANPR

**Comment by rinonasti** [comment]
OK Grazie
