### ISSUE TITLE
Controllo ip abilitato/censito per il Comune

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2423]
Buongiorno,
in riferimento alla issue #2230 
vorrei sapere se il seguenti ip è correttamente censito per il Comune di Stroncone.
5.253.215.17
Controllando in WebApp risulta con *.

Grazie
Federico

**Comment by cmigliardi** [comment]
buonasera, chiedo verifica e le faccio sapere a breve

**Comment by cmigliardi** [comment]
ip non presente - chiedo abilitazione

**Comment by cmigliardi** [comment]
ip  abilitato

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
