### ISSUE TITLE
[5005] Errore in trasferimento da convivenza a famiglia

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2424]
Ambiente di produzione, comune di Brindisi

con una chiamata al servizio 5005 si tenta di trasferire in una nuova famiglia anagrafica un soggetto attualmente iscritto in convivenza.
 La convivenza ha un unico componente (lui) e ha lo stesso indirizzo della famiglia di destinazione.
La chiamata ritorna l'errore "Per trasferire tutti i componenti di una famiglia in una nuova utilizzare il servizio di mutazione residenza famiglia" (id operazione ANPR 423124179)

Qual è il problema ?
Grazie

**Comment by frmariani** [comment]
il cittadino indicato nel servizio risulta residente nella famiglia idanpr 53181676 e non in una convivenza;

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
