### ISSUE TITLE
[5005] L'operazione da annullare non è l'ultima per il soggetto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2425]
Ambiente di produzione, comune di Albenga.

Dobbiamo annullare 3 mutazioni di residenza (ID operazioni 337625633, 337625763, 337625899) di soggetti presenti nella medesima famiglia.
Non vanno a buon fine  con l'errore "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077)" sia da WS che da webapp.

Non riusciamo a capire quale sia l'operazione che blocca.

Ci potete aiutare ? 
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
ci sono due mutazioni famiglia/convivenza 339340854 e 363822844 effettuate sulla famiglia di partenza id 23590213 che sono state effettuate dopo le tre mutazioni di residenza che volete annullare 337625633, 337625763, 337625899.
