### ISSUE TITLE
Errore [5005] - Annullo mutazione residenza

### ISSUE THREAD

**Issue by averrando** [italia/anpr#2426]
Comune di Albenga

Errore In annullo di  1 mutazione di residenza (ID operazione 350023135) di un soggetto da solo nel nucleo famigliare.
L'annullo non va a buon fine con l'errore "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa (Codice: EN077)" sia da WS che da webapp.

Verificando in webapp non riusciamo a capire qual'è l'operazione che blocca l'annullo
Riuscite a verificare di quale operazioni si tratta?
Grazie

**Comment by frmariani** [comment]
L'operazione di mutazione della residenza non può essere annullata perchè la famiglia d'origine si è spostata con un'operazione successiva, pertanto il cittadino non può tornare al precedente indirizzo

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
