### ISSUE TITLE
MONITORAGGIO OPERAZIONI - NOTIFICA MUTAZIONE DI RESIDENZA CON RIFERIMENTO ISSUE (#2365) (#2394)

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2427]
Buongiorno, scrivo con riferimento alla issue #2394

Riassumendo: abbiamo inserito nel client java di esempio la chiamata al servizio 4005, inserendo i relativi WSDL aggiornati

come si vede dai file di richiesta e risposta visibili in #2394 abbiamo un errore

Abbiamo controllato il file cxf.xml ma mi pare che le varie policy siano per famiglia e quindi la 4005 venga, come avviene per le altre chiamate, esempio 4001,4002,4003 e 4004 , "coperta" dalla policy 4000, giusto?

il file cxf dovrebbe essere rivisto per la chiamata 4005? Ci potrebbe essere qualche altra configurazione da controllare?

[cxf.xml.txt](https://github.com/italia/anpr/files/5816185/cxf.xml.txt)

<jaxws:client name="{http://sogei.it/ANPR/4000AnprService}AnprServicePort4000" createdFromAPI="true">
        
        <jaxws:properties>
            <entry key="ws-security.callback-handler" value="client.ClientKeystorePasswordCallback"/>        

        </jaxws:properties>

        
        
        <jaxws:outInterceptors>
            <ref bean="SAML_Request"/>
        </jaxws:outInterceptors>
    </jaxws:client>

**Comment by gife67** [comment]
Buongiorno,
nel file cxf.xml va inserita la definizione della famiglia, mentre la policy va aggiunta dentro il WSDL del servizio e va riportata per ogni operation. Vi riporto sotto un esempio: 

	<wsdl:binding name="AnprBinding4000" type="tns:AnprPortType4000">    
		<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>    
		<wsdl:operation name="estrazione_dati_cittadini">      
			<wsdlsoap:operation soapAction=""/>      
			<wsdl:input>        
				<wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="policy-X509v3.xml"/> 
				<wsdlsoap:body use="literal"/>      
			</wsdl:input>      
			<wsdl:output>        
				<wsdlsoap:body use="literal"/>      
			</wsdl:output>   
		</wsdl:operation>

**Comment by gife67** [comment]
Buongiorno,
chiudo la Issue, in caso di ulteriori problemi potete riaprirne un'altra collegandola a questa.
Cordiali saluti
