### ISSUE TITLE
ANPR molto lento

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2429]
Buongiorno, 
da una decina di minuti riscontriamo una particolare lentezza di ANPR.
Cordiali saluti
Floramo S.
UpiTorino

**Comment by uimartinsicuro** [comment]
Buongiorno,
confermo che abbiamo la stessa problematica.
Cordiali saluti.
Marco D. B.
Comune di Martinsicuro (TE)

**Comment by FilippoPapi** [comment]
confermo che ci sono stati rallentamenti nel sistema che sono stati risolti intorno alle 11,37
buona giornata
filippo Papi
