### ISSUE TITLE
[5001] Iscrizione per rimpatrio dall'AIRE di altro subentrato

### ISSUE THREAD

**Issue by busaster** [italia/anpr#243]
Buongiorno

ambiente di Produzione, comune di Chiavari.
Un cittadino già presente in ANPR come AIRE gestito dal comune di Lavagna chiede la residenza a Chiavari.
Il soggetto è in famiglia da solo per cui componiamo una  richiesta 5001 per trasferimento intera famiglia (ID ANPR 728699).
Ci viene però risposto con l'errore "**EN236**" "Scheda famiglia AIRE di competenza di altro comune. Utilizzare il servizio A006 per modificare anche il comune di iscrizione". 

A quel punto abbiamo fatto delle prove in ambiente di test di altro cliente (Poggio a Caiano) per vedere come usare il servizio A006 per modificare il solo comune di competenza AIRE. 
Veniamo però bloccati da un errore **EF007** "Intestatario di famiglia già presente", come se la mutazione volesse alterare la struttura della famiglia (ID ANPR 200791).

A questo punto chiedo come possiamo procedere. Non sarebbe possibile alleggerire il controllo EN236 in modo che con una singola chiamata al 5001 possiamo perfezionare il trasferimento ?

**Comment by gcarbonin** [comment]
Occorre utilizzare  un A006 per il nuovo comune di iscrizione indicando in alternativa

<attribuzioneFamigliaAIRE> = 0 Nuova famiglia, se il soggetto fa famiglia AIRE a se

<attribuzioneFamigliaAIRE>= 1 Famiglia esistente, se il soggetto si associa ad una famiglia AIRE già registrata nel nuovo comune

L’utilizzo del 5001 per le famiglie AIRE è previsto solo nel caso di trasferimento estero -> estero all’interno dello stesso comune

**Comment by busaster** [comment]
Supponendo quindi che l'intera famiglia AIRE del soggetto rimpatri dall'AIRE del comune A verso il comune B (entrambi subentrati) si  dovrà comunque generare una nuova famiglia ANPR ? Io avevo inteso che si dovesse mantenere la stessa famiglia ANPR in questo tipo di movimenti.

**Comment by gcarbonin** [comment]
Al momento per le famiglie AIRE non funziona così.

**Comment by busaster** [comment]
Sto provando ad implementare i rimpatri come da lei indicato in ambiente di test (Poggio a Caiano)
Ho iniziato con un rimpatrio dall'AIRE del comune di lavoro di una intera famiglia
Nel servizio A006 non è però possibile specificare la "residenza in italia" ma solo la "residenza estera", se per prova in tale tag specifico l'indirizzo (italiano di Poggio a Caiano) di destinazione ottengo l'errore ""ES027 :  La descrizione della localita' e' obbligatoria per la residenza estera" (operazione ID ANPR 549422). 
Come mi devo comportare ?

**Comment by busaster** [comment]
Volevo puntualizzare meglio riassumendo tutte le mie prove.
1- I rimpatri dall'AIRE del comune di lavoro NON funzionano con il servizio A006 ma funzionano perfettamente usando i servizi 5001 e 5005. (vedi IDS ANPR 549431,549451,549472). Vista la sua affermazione riguardo al 5001 le chiedo : quelle da me eseguite sono operazioni lecite ?
2- I rimpatri da AIRE di altro comune NON subentrato vengono gestite con il servizio 1002 e non presentano problemi.
3- I rimpatri da AIRE di altro comune SUBENTRATO NON funzionano con il servizio A006 (errore ES027 : La descrizione della localita' e' obbligatoria per la residenza estera) ma nemmeno con il 5001/5005. Come posso agire ?

**Comment by gcarbonin** [comment]
Provo a riepilogare:
1) Iscrizione di un soggetto  Aire (A002) con successivo rimpatrio nello stesso comune o altro comune  subentrato > 5001 e 5005;
2) Rimpatrio di un soggetto in comune subentrato > 1002

Il servizio A006 deve essere utilizzato per :

1) Modifica della residenza dall'Italia all’estero (tipo mutazione 1)
2)Modifica residenza, abitazione o indirizzo all’estero  (tipo mutazione 2)
3)Modifica del comune AIRE di iscrizione (tipo mutazione 3)
4) Dati generali iscrizione (tipo mutazione 4)

**Comment by busaster** [comment]
D'accordo.
Abbiamo però sperimentato che il 5001 nel caso "rimpatrio in altro subentrato" non funziona, come sottolineavo nel post iniziale di questa discussione.
Il problema si è presentato nell'ambiente di produzione del comune di Chiavari.
Veniamo bloccato dall'errore "EN236 : Scheda famiglia AIRE di competenza di altro comune. Utilizzare il servizio A006 per modificare anche il comune di iscrizione" (ID op. ANPR 728699).
Tentando di fare quanto suggerito dal messaggio di errore veniamo bloccati da un altro errore "EF007 Intestatario di famiglia già presente", come se la mutazione volesse alterare la struttura della famiglia 

Come possiamo procedere ?

**Comment by gcarbonin** [comment]
Il caso è una famiglia AIRE di Chiavari che rientra in Italia o famiglia AIRE di Chiavari che cambia il comune di iscrizione aire?

**Comment by busaster** [comment]
Famiglia AIRE di Lavagna che rimpatria a Chiavari

**Comment by gcarbonin** [comment]
Dobbiamo modificare il controllo. Domani le facciamo sapere. E' corretto il 5001 comunque

**Comment by gcarbonin** [comment]
Il problema è stato risolto ha avuto modo di riprovare?

**Comment by busaster** [comment]
in test abbiamo verificato che il servizio 5001 fa quanto desiderato.In produzione avremo la controprova fra qualche giorno quando aggiorneremo il cliente ma non credo ci saranno problemi.Ing. Gianrico BusaSviluppo Software Settore DemograficiDivisione InformaticaTel +39 030 9949011 - Fax +39 030 941833www.maggioli.it/informatica-----gcarbonin <notifications@github.com> ha scritto: -----A: italia/anpr <anpr@noreply.github.com>Da: gcarbonin <notifications@github.com>Data: 04/08/2017 10.52PMCc: Gianrico Busa <gianrico.busa@maggioli.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/anpr] [5001] Iscrizione per rimpatrio dall'AIRE di altro subentrato (#243)Il problema è stato risolto ha avuto modo di riprovare?
