### ISSUE TITLE
Utente invio dati da WS

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2430]
Buonasera,
il codice fiscale presente nella ID_OPERATORE   del  Keystore.properties può essere un utente senza smart card ?
Grazie

**Comment by Leonforte** [comment]
se parla dell'asserzione SAML la risposta è si, per i servizi non serve che l'operatore abbia la smart card, ma deve ovviamente essere registrato ed autorizzato all'utilizzo del servizio che si richiama, buon lavoro, saluti

**Comment by rinonasti** [comment]
ok grazie
