### ISSUE TITLE
archivio comuni aggiornato al 15-01-2021

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2432]
Buongiorno,
mi permetto di segnalare alcuni errori sull'ultimo archivio dei comuni pubblicato:

1) la riga 3985 contiene 2 record (ID=15771 e ID=398), inoltre per entrambi i record i valori di DATAULTIMOAGG non sono corretti;
2) la riga 7592 (ID=4519) risulta troncata (nella versione precedente conteneva i dati del comune GRESSONEY-LA-TRINITE;
3) la riga 19342 (l'ultima riga) è completamente fuori standard.

Cordiali saluti,
Tiziano Pavan

**Comment by MassimoSchiappa** [comment]
Salve,
grazie mille per la segnalazione, provvederemo immediatamente a ristabilire la correttezza del file e a modificare il processo di generazione dell'archivio pubblicato in modo da eliminare il rischio che si ripeta nuovamente.
Cordiali saluti.
