### ISSUE TITLE
Rallentamenti ANPR

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2433]
Buongiorno,
da circa 10 minuti riscontriamo rallentamenti nel sistema ANPR che creano problemi con la comunicazione del gestionale ma soprattutto con le emissioni CIE.
Cordiali Saluti
Floramo S.
UpiTorino

**Comment by sfmodena** [comment]
Buongiorno, 
anche a Modena stessi problemi, l' emissione CIE ora è bloccata.

Grazie, cordiali saluti
Sonia Fiorini

**Comment by FilippoPapi** [comment]
buongiorno
confermo la presenza dei rallentamenti stiamo facendo le verifiche

**Comment by enricososo** [comment]
Vicenza, bloccati

**Comment by CSI-Piemonte-Demografia** [comment]
Buongiorno,

potete darci riscontro non appena il problema sarà rientrato? E' molto importante.

Grazie, 
Chiara Leanza per il Comune di Torino

**Comment by FilippoPapi** [comment]
Buongiorno,
il problema è stato risolto i sistemi sono nuovamente disponibili
cordiali saluti
