### ISSUE TITLE
domicilio digitale Pec

### ISSUE THREAD

**Issue by micanova** [italia/anpr#2434]
Buongiorno,
vorrei suggerire di consentire la dichiarazione del proprio domicilio digitale PEC su Anpr, possibilmente attraverso autenticazione remota spid o cie (senza dover andare in Comune quindi).
grazie

**Comment by micanova** [comment]
Buongiorno,
vorrei suggerire di consentire la dichiarazione del proprio domicilio digitale PEC su Anpr, possibilmente attraverso autenticazione remota spid o cie (senza dover andare in Comune quindi).
grazie

**Comment by FilippoPapi** [comment]
attualmente i domicilio digitale sull'INAD che è previsto che conferirà i dati all'ANPR al completamento della stessa. si sta anche analizzando la possibilità delle successive acquisizioni/gestioni del domicilio digitale dal nuovo sito di ANPR.
saluti
