### ISSUE TITLE
Errore CIE: Sistema ANPR momentaneamente non disponibile

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2436]
Comune di Modena - Ambiente Produzione

Buongiorno,
anche oggi l' emissione CIE è bloccata a causa di problemi nella comunicazione con ANPR, ci viene segnalato l' errore indicato nell' oggetto della issue.  Per cortesia potete verificare?

Grazie, saluti
Sonia Fiorini

**Comment by ANPRCdMI** [comment]
Buongiorno
confermiamo che sono bloccati tutti i collegamenti con ANPR, non solo l'emissione delle CIE.
Rimaniamo in attesa di un cortese riscontro

Grazie
Saluti
Raffaella Tremolada 
S.I. per Comune di Milano

**Comment by UpiTorino** [comment]
Buongiorno,
anche a Torino riscontriamo gli stessi problemi.

Cordiali Saluti
Floramo S.
UpiTorino

**Comment by rvinzani** [comment]
I servizi sono di nuovo attivi. Chiudiamo la issue. Nel caso ci fossero ulteriori problemi si prega di aprire una nuova issue che faccia riferimento a questa
