### ISSUE TITLE
Allineamento CF impossibile operazione in sospeso

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2438]
Salve,
per il comune di Baragiano (PZ cod istat: 076010) abbiamo il soggetto con identificativo anpr: 104042766 che ha in ANPR un codicefiscale errato, essendo stata inviata una data di nascita errata. Abbiamo provato ad effettuare una mutazione del soggetto ma ci dice che va allineato il codice fiscale. Quando invece proviamo ad effettuare l'allineamento del CF in AE (dalla sezione utilità/disallineamenti della web-app) ci dice che ci sono operazioni in sospeso, per cui non riusciamo a portare a termine nessuna delle due operazioni, siamo bloccati

**Comment by frmariani** [comment]
il cittadino con l'identificativo indicato risulta validato e marcato; mi può indicare l'id dell'operazione fallita per favore ?

**Comment by carminepat** [comment]
l'id operazione della mutazione che stiamo tentando di fare è  432436079

**Comment by carminepat** [comment]
Abbiamo provato ad effettuare una nuova mutazione, con il flag "richiesta attribuzione codice fiscale" ma fallisce anche questa: (id operazione 432464127). Ci dice: "Se il codice fiscale è esistente, non è possibile richiedere una nuova attribuzione; (Codice: EN491)"
Il problema è che in fase di iscrizione era errata la data di nascita e di conseguenza il CF. Attualmente abbiamo il CF corretto tra le mani, perchè dobbiamo rilasciare la CIE al cittadino, ma non riusciamo a mettergli il CF corretto. Per questioni di privacy non le incollo qui di seguito il codice fiscale completo ma essendo il cittadino nato in data: 06/01/2000 il CF dovrebbe essere ------00A06Z222D

**Comment by frmariani** [comment]
Se il CF corretto già esiste in Agenzia delle Entrate, l'operazione da eseguire è il collegamento dei due codici fiscali, così come suggerito dalla descrizione dell'errore nell'operazione idanpr 432436079.
L'operazione deve essere effettuata dalla web app con la funzione Risoluzioni disallineamenti con AE

Se volete assistenza inviate un recapito alla mia casella di posta 
frmariani@sogei.it

**Comment by carminepat** [comment]
riallineati i dati dall'area utilità/disallineamenti AE, Grazie mille del supporto, gentilissimi
