### ISSUE TITLE
Chiarimento su "Ripristino cambio abitazione" casi particolari

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2439]
Buongiorno
Avrei bisogno di un chiarimento su come debba essere gestito in ANPR il caso:
- la famiglia è composta da più di un componente;
- almeno un componente si stacca per cambio abitazione su altra famiglia (nuova o no)
- i restanti componenti in data successiva effettuano un cambio abitazione;
- successivamente viene ripristinato il cambio abitazione del componente che si è staccato, in ANPR l'annullamento del cambio abitazione (s5012) riporta il componente nella famiglia precedente ma all'indirizzo nuovo.

Il ripristino dovrebbe rimettere il componente all'indirizzo originale su una famiglia nuova, o sulla famiglia originale a prescindere da eventuali mutazioni di indirizzo?
Casi simili si potrebbero avere con ripristini su famiglie con emigrazione o estinzione per decesso per cui risulterebbe complicato ripristinare il cittadino sulla famiglia originale.

Saluti
Federico_B

**Comment by frmariani** [comment]
l'ultimo punto del suo elenco non è corretto: se nel frattempo la famiglia di origine si è spostata o è stata chiusa, l'annullamento per ripristino non va a buon fine; in questi casi si deve effettuare la cancellazione per altri motivi

**Comment by Hdemografici** [comment]
Facevo riferimento ad un cambio di abitazione interno al comune. 
Che sappia io normativamente il soggetto dovrebbe tornare all'indirizzo originale e solo successivamente si potrà avviare un procedimento di cancellazione per irreperibilità, non cancellare immediatamente.

**Comment by frmariani** [comment]
Stiamo lavorando in questo senso, ma al momento se la famiglia d'origine si è spostata il cittadino deve essere cancellato e nel caso re-iscritto al domicilio precedente; attenzione alle date di cancellazione e re-iscrizione

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
