### ISSUE TITLE
Integrazione dei dati AIRE

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#244]
Apro questa issue per tracciare la modifica evolutiva necessaria in ANPR per integrare i dati AIRE forniti al momento del subentro.

**Comment by gcarbonin** [comment]
I dati AIRE forniti al momento del subentro sono quelli previsti dal DPCM 194 2014 e gestiti dall'attuale pacchetto AnagAIRE.
Per la loro integrazione sono possibili due modalità:

- upload di un file (tramite Web Application) che contiene i dati aggiuntivi (file csv con la struttura dati allegata),
- integrazione "dinamica" quando la persona viene movimentata in ANPR; per essere più precisi se il comune deve comunicare il decesso del coniuge, avrà cura di comunicare anche i dati del coniuge stesso.

Per chiarezza, preciso che la seconda modalità è già operativa mentre la prima deve essere implementata.

**Comment by Insiel** [comment]
è possibile verificare la struttura dei dati AIRE del file csv proposto per l'upload ?

**Comment by gcarbonin** [comment]
[CompletamentoDatiAIRE.xlsx](https://github.com/italia/anpr/files/1259540/CompletamentoDatiAIRE.xlsx)

**Comment by niclup** [comment]
Il tracciato non prevede ancora la possibilità di aggiungere i dati del matrimonio nel caso di cittadini vedovi/divorziati. E' verificato che la mancanza di queste informazioni (data in particolare), comporta successivi problemi  nell'utilizzo dei servizi.

**Comment by gcarbonin** [comment]
i dati ci sono. Alleghiamo una nuova versione in quanto la dicitura di alcuni campi era imprecisa

**Comment by bfilipazzi** [comment]
I dati integrativi richiesti sono Paternità, Maternità, Coniuge, Parte di Unione civile, Convivente di  Fatto.
Osservo che le convivenze di fatto sono incompatibili con la condizione di residenza all'estero, per questa ragione suggerisco di trascurarle perché i campi sarebbero tutti nulli.
Abbiamo già la struttura XML per trasmettere questa tipologia di informazioni per le persone residenti nel comune, è una struttura collaudata per il cui popolamento le sw house hanno sviluppato le logiche applicative, propongo di utlizzare un file XML con i tag paternita, maternita, matrimonio, vedovanza, separazioneAnnullamentoCessazioneMatrimonio, cartaIdentita, unioneCivile, identici a quelli del file di subentro degli APR. Ho aggiunto la carta di identità.
Se fosse possibile fornire i dati come ho proposto avremmo anche una logica unica, senza la complicazione di gestire la data di inizio e fine validità del coniuge o dell'unito civilmente presenti nella bozza csv e mancanti nella struttura di subentro APR.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Le convivenze di fatto riguardano anche gli italiani residenti all'estero; so che su questo punto ci sono divergenze con il Ministero dell'Interno ma non possiamo che seguire le loro indicazioni. Riguardo al formato del file (csv o xml) per Sogei è indifferente; sentiamo anche gli altri

**Comment by LucaBonini64** [comment]
Concordo con l'utilizzo della struttura XML utilizzata per le persone residenti, mi sembra la cosa più logica e più semplice da implementare per tutti.
Luca Bonini A.P.Systems

**Comment by INSIEL1** [comment]
anche per noi (insiel) la struttura XML puo' andar bene.
abbiamo una perplessità sulla registrazione di convivenze di fatto per gli AIRE: chi effettua l'accertamento della coabitazione?

**Comment by gcarbonin** [comment]
Il consolato penso. C'è un problema in ogni caso in quanto la famiglia reale non è la famiglia AIRE: i due conviventi, infatti, potrebbero appartenere a comuni AIRE diversi.

**Comment by ATropeano** [comment]
Ci sarebbero altri dati che si potrebbero integrare per gli Aire iscritti in ANPR al momento del subentro,
dati più o meno importanti, che quando presenti, noi inviamo nelle iscrizioni AIRE post-subentro:

**AltriDati\condizioneProfessionale
AltriDati\condizioneNonProfessionale
AltriDati\titoloStudio
Autoveicoli\possessoAutoveicoli
Autoveicoli\possessoPatente
CartaIdentita
ListaElettorale	
ListaLeva
Cittadinanza\dataValidita
Censimento**

Chiederei che in questa importazione venisse anche prevista la possibilità di poter inviare l'ID Scheda Soggetto Comune proprio dell'applicativo demografico comunale (tipicamente una sequenza numerica)
che andrebbe a sovrascrivere in ANPR quello caricato dall'esportazione xml fatta da AnagAire (del tipo E2010-0000033).

Alessio Tropeano Datagraph s.r.l.

**Comment by gcarbonin** [comment]
Alcuni di questi dati sono presenti. Ho una domanda: questi dati da integrare sono dati storici (cioè sono nella base dati del comune in quanto la persona prima di iscriversi all'AIRE risiedeva nel comune e quindi sono dati della scheda anagrafica archiviata) o sono modificati dal comune perché il diretto interessato chiede le variazioni o perché il comune li riceve dal consolato)

**Comment by bfilipazzi** [comment]
Autoveicoli\possessoAutoveicoli
Autoveicoli\possessoPatente
Censimento
Riguardo a questi tre dati non credo che l'interessato o il consolato trasmettano variazioni al comune, sono dati storici, di cui i primi due francamente mi paiono trascurabili per un residente all'estero e il terzo è riferito ad un censimento avvenuto prima dell'espatrio. Mi domando anche perché il possesso di veicoli e patente sia trattato come dato anagrafico, non solo per gli AIRE, ma anche per i residenti. Io non vedo questi dati nell'allegato B del DPCM 194 / 2014, ma forse mi sfugge qualcosa.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Possesso di veicoli e di patente sono dati di servizio che vengono acquisiti esclusivamente per comunicare a MTC la variazione, non sono attributi della scheda individuale; per questo motivo non sono nell'allegato B. Non penso possano interessare persone già iscritte all'AIRE.

**Comment by bfilipazzi** [comment]
Se possibile propongo di fare chiarezza su dati veicoli e dati patente, che come gcarbonin conferma non sono dati della scheda perché il DPCM non li prevede. Pur essendo informazioni variabili nel tempo l'anagrafe non ne è informata (salvo che in occasione di pratiche migratorie) e la loro consultazione porta a leggere notizie non affidabili. Mio figlio ha la patente da 8 anni ma, non avendo avuto migrazioni nel periodo risulterebbe in ANPR "senza patente". Queste due notizie dovrebbero servire solo per le ragioni sopra esposte e perciò propongo di toglierle dalla scheda della persona, intendo dalla "Visura anagrafica", dalla risposta al servizio di consultazione e anche dal flusso di subentro. (per tutti, non solo per gli AIRE).
Filipazzi - Maggioli

**Comment by ANPRCDBO** [comment]
Volevamo segnalare che, nel tracciato ANAGAIRE, l'indirizzo è di 60 caratteri, mentre noi abbiamo piu' di 200 casi in cui l'indirizzo risulta maggiore di 60 caratteri. 
Per  quanto riguarda, poi, gli atti di stato civile, abbiamo la parte , la serie e la frazione.  Nel tracciato ANAGAIRE, invece, ci sono solo parte e serie di lunghezza 1.
Team Sipo
Comune Bologna

**Comment by gcarbonin** [comment]
Questi casi li avete già segnalati e per quanto abbiamo visto si tratta di indirizzi "non normalizzati" (ad esempio, insieme al toponimo c'è anche presso). In ogni caso per questi si può prevedere una elaborazione ad hoc per sistemarli, una volta passati in produzione; con la prossima formazione dell'elenco unico elettori potreste sistemare questi dati: possiamo vedere di incrociarli con quelli degli schedari consolari che fanno fede per la spedizione dei plichi a domicilio degli elettori. Se possibile, ci invii (non con questa modalità ma sulla posta Sogei) un estratto dei dati AIRE di queste persone con indirizzo lungo e possiamo intanto verificare con i dati MAECI.
Per quanto riguarda gli estremi degli atti, con l'integrazione dei dati AIRE la cosa si dovrebbe sistemare.

**Comment by annamariaGillone** [comment]
Buongiorno
in riferimento a quanto riportato ci potete confermare che sarà possibile utilizzare per il subentro degli AIRE lo stesso tracciato attualmente utilizzato per il subentro degli APR? se sì da quando?
Grazie mille
Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Assolutamente no. Il tracciato che si utilizza è quello attuale; si sta ipotizzando una successiva integrazione dei dati per le persone che vengono movimentate in anpr.

**Comment by RBiasi** [comment]
Buongiorno,
al momento causa la presenza di dati parziali del coniuge di cittadino AIRE abbiamo operazioni di Mutazioni Tutti i dati bloccate in quanto in applicativo l'anagrafica è completa, dobbiamo procedere prima da webapp integrando i dati. 
Avremmo urgenza di capire se tali dati verranno integrati in ANPR.
Grazie

**Comment by gcarbonin** [comment]
E' in corso di realizzazione

**Comment by gcarbonin** [comment]
Da domani sarà disponibile in ambiente di test comuni e pre-subentro l'integrazione puntuale dei dati AIRE
