### ISSUE TITLE
[4005] Errore scarico notifiche EC021

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#2440]
Ambiente di produzione
idOperazioneANPR: 432585310
codMittente: 001022

Buongiorno,
da questa mattina diversi comuni che seguiamo ci stanno segnalando problemi con lo scarico delle notifiche.
Dal messaggio di errore deduciamo che il problema è legato al campo <statoLavorazione>.
Noi questo campo lo abbiamo sempre valorizzato a 9, ovvero "tutte le notifiche", e fino a ieri sera ha sempre funzionato.

Potete verificare cosa sia cambiato?
Come possiamo risolvere il problema?

Ringrazio anticipatamente.

**Comment by SAlberto** [comment]
Ci sono novità?

**Comment by lorbia** [comment]
Salve stiamo verificando il problema.

**Comment by lorbia** [comment]
Potete riprovare e non dovreste più riscontrare il problema.
