### ISSUE TITLE
Anagrafica di unione Civile per cittadino AIRE

### ISSUE THREAD

**Issue by Maga63** [italia/anpr#2441]
Buongiorno, tentando di emettere un certificato anagrafico di Unione Civile di un cittadino AIRE si riceve il messaggio:
"Il certificato di Anagrafico di unione civile non puo' essere emesso perche' il soggetto risulta essere iscritto all'AIRE alla data 15-01-2021 (Codice: EN417)"

Volevo sapere se è possibile certificare o meno l'unione civile visto che il certificato viene comunque visualizzato tra quelli disponibili per gli AIRE.

Grazie

![image](https://user-images.githubusercontent.com/44897978/105499347-a153cf80-5cc1-11eb-8571-cb9ed72acab6.png)

**Comment by ncapozzi** [comment]
Buonasera,
i certificati di Matrimonio, Unione civile e Contratto di convivenza possono essere emessi dal Comune solo relativamente al periodo che precede l’espatrio.
Per le certificazioni rilasciabili agli iscritti AIRE si fa rinvio all'art. 7 L. 27/10/1988, n. 470.

N. Capozzi
