### ISSUE TITLE
Iscrizione / certificazione cittadini britannici

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2442]
Buongiorno,
alla luce della circolare del 30/12/2020, il passaggio da UE a  Extra UE dei cittadini britannici comporterà dei cambiamenti rispetto ai controlli che dovrebbero essere posti in essere (obbligo dell'inserimento/presenza del Permesso di soggiorno ad esempio)?
Grazie

UPI Torino

**Comment by ncapozzi** [comment]
Buonasera,
ANPR non prevede controlli distinti per cittadini UE, Extra UE o residenti. In particolare il Permesso di soggiorno non è mai obbligatorio.
Per ulteriori approfondimenti di carattere amministrativo le suggeriamo di contattare il Ministero dell'Interno.

N. Capozzi
