### ISSUE TITLE
[4001] errore EC025

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2443]
Salve
al Comune di CARTOCETO in presubentro - idOperazioneANPR 20843227
facendo una estrazione dei cittadini per un intevallo id ANPR 
con datiAnagraficiRichiesti=1 (codice presente nella tabella 16)

torna errore EC025 (Codice datiAnagraficiRichiesti non valido)

stessa cosa che mettendo  datiAnagraficiRichiesti=1 idOperazioneANPR>20843237

**Comment by rvinzani** [comment]
Buongiorno, state chiedendo un range di identificativi troppo elevato

**Comment by Hdemografici** [comment]
Buongiorno 
grazie
quanto è il limite massimo? prima era 2000

**Comment by rvinzani** [comment]
Sempre lo stesso

**Comment by Hdemografici** [comment]
qualcosa non mi torna
sempre per CARTOCETO in PRESUBENTRO
idOperazioneANPR 20847588
con 
`<idSchedaSoggettoANPRDa>148444139</idSchedaSoggettoANPRDa>
<idSchedaSoggettoANPRA>148444388</idSchedaSoggettoANPRA>`

da sempre errore EC025 sono 249 schede

**Comment by rvinzani** [comment]
Potete riprovare? Attendo verifica

**Comment by Hdemografici** [comment]
Perfetto sembra tutto risolto, lo stesso problema c'era in produzione e anche li è risolto.

grazie
Saluti
