### ISSUE TITLE
[5001] errore 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2444]
Comune di Cesenatico, produzione.

Il tentativo di eseguire una mutazione famiglia 5001 di tipo rettifica indirizzo restituisce l'errore EN526 : Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 04-07-2017. (id operazione ANPR 432947657).

Consultando però la scheda del soggetto esso risulta residente dal 15/12/2017, data che usiamo come decorrenza nelle nostra richiesta di variazione.

Quale può essere il problema ?
Grazie

**Comment by frmariani** [comment]
L'operazione di rettifica dell'indirizzo di una famiglia, si deve utilizzare per rettificare un dato acquisito erroneamente in fase di creazione della famiglia o in fase di subentro; la data della rettifica dovrà necessariamente essere uguale alla data di creazione della famiglia, anche se l'unico cittadino attualmente presente nella stessa, ha una data di decorrenza della residenza diversa (perchè inserito successivamente); nel vostro caso, la famiglia è stata creata il 4/07/2017 così come specificato nell'errore, pertanto questa è la data che deve essere indicata nell'utilizzo del servizio specifico.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
