### ISSUE TITLE
caratteri non validi in dati atto di nascita

### ISSUE THREAD

**Issue by walteramato** [italia/anpr#2445]
Salve,
sono Walter Amato della software house APKAPPA e scrivo per conto del COMUNE DI BEDIZZOLE (BS).

Provando a fare da webapp una "mutazione tutti i dati", subito dopo aver selezionato il nominativo, compare il messaggio bloccante:
"Il campo Ufficio/Municipio contiene dei caratteri non validi" 
senza alcun codice d'errore.

Ambiente: Produzione
id individuale ANPR del cittadino: 75672645
data ultima prova: 22/01/2021

Per piacere riuscite a sistemare?

Grazie

**Comment by frmariani** [comment]
Nell'atto di nascita è presente un carattere non ammesso nel campo Ufficio/Municipio;
dovreste inviare un WS 5008 tipo mutazione 15 ed eliminare il carattere /

**Comment by walteramato** [comment]
ok grazie
