### ISSUE TITLE
Ho smarrito la prima parte del puk e della password e ho la smart card bloccata: come faccio a recuperarli e sbloccarla?

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#2446]

**Comment by Leonforte** [comment]
Buongiorno, dalle verifiche effettuate la carta risulta essere stata bloccata dal comune di Gatteo che ha oltretutto cancellato anche la sua utenza. Provvederemo in giornata ad associare la carta all'attuale comune di Montelabbate al fine di consentire all’Amministratore Locale della Sicurezza di procedere alla richiesta di una nuova carta attraverso la console di sicurezza dalla web app ANPR 
Gestione Smart Card  
Ricerca Smartcard 
Ricerca
Selezionare l’utente con la lente a dx e premere il tasto Richiedi Nuova SmartCard.

Buona lavoro, saluti

**Comment by cristinapezzolesi** [comment]
Penso che la mia smart card fosse già stata collegata al nuovo comune di Montelabbate, perché funzionava regolarmente finché non ho inserito male la password per tre volte e si è bloccata. Quindi, non trovando più la prima parte del mio puk, non è possibile ottenere la ristampa o il reinvio della prima parte del puk? Posso solo chiedere una nuova smart card? E la vecchia card rimarrà collegata ancora a me ma bloccata? Grazie

**Comment by Leonforte** [comment]
la prima parte dei codici è stata inviata all'indirizzo : c.pezzolesi@montelabbate.net
Per lo sblocco Le suggeriamo di seguire le indicazioni in allegato, buon lavoro, saluti
[Procedura sblocco PIN.pdf](https://github.com/italia/anpr/files/5973486/Procedura.sblocco.PIN.pdf)

**Comment by cristinapezzolesi** [comment]
> la prima parte dei codici è stata inviata all'indirizzo : c.pezzolesi@montelabbate.net
> 
> Per lo sblocco Le suggeriamo di seguire le indicazioni in allegato, buon lavoro, saluti
> 
> [Procedura sblocco PIN.pdf](https://github.com/italia/anpr/files/5973486/Procedura.sblocco.PIN.pdf)
> 
> 

Grazie! Sono riuscita a sbloccarla.
