### ISSUE TITLE
Mancata ricezione notifiche su ambiente di presubentro.

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2449]
Buongiorno,

la presente per segnalarVi la mancata ricezione delle notifiche sul nostro endpoint collegato all'ambiente di presubentro del Comune codice 040007.

L'indirizzo del ns. endpoint:

next-we-uat-anpr-notifications-app.azurewebsites.net/ServizioNotifica.svc

Le notifiche venivano correttamente ricevute fino alla scorsa settimana.

Attendiamo gentile riscontro.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by lorbia** [comment]
Salve in ambiente di presubentro all'endpoint segnalato mi risultano tre notifiche N031 ed una N010 inviate con esito positivo in data odierna 25/01/2021 l'ultima delle quali alle 16.46

**Comment by lorbia** [comment]
Segnalo anche oggi una notifica 031 inviata con esito positivo.
