### ISSUE TITLE
WS3007 - ERRORE EN148

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2450]
Buongiorno Comune CASERTA 061022 ambiente PRESUBENTRO
errore EN148
idOperazioneANPR 20850490
Valore errato di tipoInvio PRE
Si potrebbe avere una diagnostica più esplicativa.
Grazie

**Comment by amollicone1982** [comment]
Nel campo tipoInvio della sezione testataRichiesta deve essere inserito il valore PRE_SUB per l'ambiente di PRESUBENTRO
