### ISSUE TITLE
Annullamento matrimonio su divorziati

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2451]
I 2 cittadini hanno id 104570251 e 104576521. Oggi risultano divorziati, con sentenza del 2018 già registrata.

Sposati nel 2006 in chiesa.
Divorzio civile del 2018 già trascritto.
Ora chiedono l'annullamento del matrimonio alle autorità ecclesiastiche.
La Corte di Appello nel 2021 conferma  una Delibazione di sentenza ecclesiastica che decreta l'annullamento del matrimonio. 

Oggi il Comune deve quindi trascrivere la nuova sentenza sull'atto di Stato Civile. 
In termini anagrafici dovrà poi modificare lo stato civile di entrambi da "divorziato" a "celibe".

Il dubbio è sulla registrazione dei dati della cessazione matrimonio.
E' corretto procedere prima a una revoca del divorzio preesistente, per poi indicare i nuovi dati di cessazione del matrimonio? O semplicemente si tratta di mutazione dati, indicando il nuovo stato civile, e i nuovi dati di cessazione matrimonio?

Il Comune lo chiede per assicurarsi di tenere un comportamento uniforme di registrazione, in quanto caso veramente insolito.

**Comment by frmariani** [comment]
Va bene la seconda ipotesi esposta.
Deve indicare "nullità" nel Tipo Cessazione e "Sacra Rota" nel Tipo Tribunale; naturalmente il nuovo stato civile.

**Comment by MarcoMigliori** [comment]
Grazie, riferisco.
