### ISSUE TITLE
Nascita AIRE (Soggetto non presente in AE)

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2452]
Comune di S.Angelo dei Lombardi (AV)

Otteniamo il seguente errore tentando di iscrivere un AIRE per nascita:
EAV91: Soggetto non presente in Agenzia Entrate

riferimento operazione: data 2021-01-26 11:28:01 , idOperazioneANPR 435361293

**Comment by ncapozzi** [comment]
Buongiorno,
il CF indicato dalla richiesta non è stato attribuito da Agenzia Entrate ma solo calcolato dal gestionale. Verificate su PuntoFisco/Siatel se il cittadino ha un CF diverso facendo accesso per dati anagrafici. 
In caso contrario, se al cittadino deve essere attribuito un CF, lo dovete togliere dalla richiesta e impostare gstioneCF = 1 per l'attribuzione. Se invece non deve avere un CF in AE impostate gestioneCF = 3 per saltare la validazione.

N. Capozzi
