### ISSUE TITLE
VARIAZIONI DI NASCITA

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2453]
COMUNE DI CAPONAGO

Rif. : VARISCO M.GIUSEPPINA

Invocanto l'evento di Nascita 1001 ANPR risponde ::

-<listaErrori>

-<errore>

<codiceErroreAnomalia>EN144</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Soggetti padre/madre non in ANPR</testoErroreAnomalia>

</errore>

-<errore>

<codiceErroreAnomalia>EN527</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-01-26 16:09:27 , idOperazioneANPR 435800043</testoErroreAnomalia>

</errore>

</listaErrori>

Sia il padre che la madre sono presenti in ANPR. Qual'è il problema?

**Comment by rvinzani** [comment]
E' sbagliato l'identificativo comunale della madre
