### ISSUE TITLE
MUTAZIONE DI RESIDENZA - Stesso indirizzo Appartamento diffrente

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2454]
COMUNE DI CAPONAGO

Rif. VARISCO M.GIUSEPPINA

Buongiorno
la famiglia oggetto della mutazione di residenza, di fatto non cambia indirizzo ma solo appartamento nell'ambito dello stesso condominio. ANPR non mi accetta la mutazione e restituisce l'esito di seguito riportato.
Cosa significa ? cher in questo caso non devo inviare la variazione ad ANPR ?

-<errore>

<codiceErroreAnomalia>EN388</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>La residenza inserita risulta uguale a quella attuale</testoErroreAnomalia>

</errore>

-<errore>

<codiceErroreAnomalia>EN527</codiceErroreAnomalia>

<tipoErroreAnomalia>E</tipoErroreAnomalia>

<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-01-26 16:11:21 , idOperazioneANPR 435803369</testoErroreAnomalia>

</errore>

-<errore>

<codiceErroreAnomalia>EN395</codiceErroreAnomalia>

<tipoErroreAnomalia>W</tipoErroreAnomalia>

<testoErroreAnomalia>per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza </testoErroreAnomalia>

</errore>

**Comment by frmariani** [comment]
Per effettuare una mutazione di Residenza nello stesso indirizzo, è necessario "Forzare l'operazione";
nei dati di controllo dell'xml deve essere presente la seguente informazione
               <controllo>
                  <codice>FO</codice>
                  <valore>S</valore>
               </controllo>

**Comment by GabriellaBallabio** [comment]
Grazie, con le sue indicazioni la comunicazione si è conclusa con esito positivo.
