### ISSUE TITLE
[5014] richiestaRettifica101 - Errore EN420

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2455]
buongiorno.

alcuni clienti che ci segnalano che fino a pochi giorni fa riuscivano ad inviare comunicazione della tipologia in oggetto (5014 - rettifica data residenza), comunicando una dataResidenza successiva alla dataUltimoAggiornamento.

oggi, nella stessa condizione il web-service ritorna errore di questo tipo:
EN420 - E - Rettifica non permessa - data decorrenza residenza XX-XX-XXXX maggiore della data ultimo aggiornamento APR XX-XX-XXXX

ci confermate se è una novità dell'ultima versione e quali siano esattamente i nuovi controlli eseguiti?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Non ci sono stati aggiornamenti in merito alla Rettifica della data di decorrenza della residenza; il controllo EN420 è sempre stato attivo; gentilmente mi riporti un esempio di operazione di rettifica effettuata senza emissione dell'errore e con la data di decorrenza della residenza maggiore della data di ultimo aggiornamento; mi sarebbe molto utile per eventuali indagini del caso. Grazie

**Comment by AMonopoliADS** [comment]
ambiente di PRODUZIONE - comune di IMOLA (037032)

idOperazioneComune 2021000713

**Comment by frmariani** [comment]
la data di ultimo aggiornamento del soggetto idanpr 38222200 risulta 18/01/2021 mentre la data di decorrenza della residenza è stata rettificata in 15/01/2021

**Comment by AMonopoliADS** [comment]
questa situazione riapre un'annosa questione che ho già posto altre volte, relativa al fatto che dai web-service non è possibile consultare la dataUltimoAggiornamento del soggetto.

in ogni caso, immagino che il 18/01/2021 sia la dataUltimoAggiornamento, aggiornata con le comunicazioni di quel giorno.

al momento dell'invio della 5014 presumo che la dataUltimoAggiornamento fosse più vecchia, coerente con il subentro avvenuto nel 2018 (data dalla quale il soggetto non ha avuto variazioni).

giusto x capire.
grazie

**Comment by frmariani** [comment]
la cittadina è subentrata senza data della decorrenza valorizzata, pertanto prima del successivo cambio di residenza doveva essere sanata la situazione; poteva comunque essere inserita una data di decorrenza della residenza coerente con la precedente data di ultimo aggiornamento; comunque il comune può visualizzare la data di ultimo aggiornamento dalla web app, con la funzione di rettifica "altre date".

**Comment by AMonopoliADS** [comment]
il comune tenta di fare quanto più possibile via web-service per velocizzare il proprio lavoro. pensare che debba andare su web-app anche per visualizzare solo una data è un passaggio che allunga solo i tempi del proprio lavoro.
basterebbe che questa data venisse restituita con la response del servizio di consultazione 3002 (rinnovo la richiesta)

per tornare al caso specifico, arrivo a queste conclusioni
1. l'errore EN420 rileva un'incongruenza tra le date presenti nella comunicazione che si sta inviando
(mentre mi aspettavo che la nuova dataResidenza venisse messa a confronto con la dataUltimoAggiornamento che il soggetto ha già in ANPR al momento dell'invio)
2. alla luce di questo, ravviso un errore nel testo del messaggio che a questo punto vi segnalo perchè penso sia da correggere o gestire. 
mi spiego meglio: la comunicazione 5014, all'interno della quale la dataDecorrenza e la dataDefinizione sono identiche,
produce una segnalazione come questa:
EN420  - Rettifica non permessa - data decorrenza residenza 26-01-2021 maggiore della data ultimo aggiornamento APR 26-01-2021
... il 26-01-2021 (data ultimo aggionamento) non è maggiore del 26-01-2021 (data deocrennza residenza)
(rif. idOperazioneComune 2021002016, sempre comune di Imola)

grazie dei riscontri.
Alessandro

**Comment by frmariani** [comment]
Le operazioni di rettifica sono state realizzate per casi residuali e specifici e non devono essere utilizzate come normale routine di lavoro dell'ufficio.
Non mi è chiaro il punto 1, ma specifico meglio: il sistema confronta la data di ultimo aggiornamento presente per il soggetto con la data di decorrenza presente nella richiesta;
l'operazione indicata nel punto 2 ci risulta  andata a buon fine: data ultimo aggiornamento 31/12/1998, data di decorrenza della residenza 31/12/1998.
Se fosse necessario  può contattarmi per le vie brevi.
