### ISSUE TITLE
WS3007 - ERRORE EN379 RIF.  #2450

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2456]
Ok modificato :

<idOperazioneANPR>20858199</idOperazioneANPR>
                    
                        <codiceErroreAnomalia>EN379</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Funzionalita' non supportata Modalita' di interrogazione non piu' supportata a partire da ANPR02

quale è l'impostazione corretta?
GRAZIE

**Comment by amollicone1982** [comment]
Il 3007 può essere usato solo per interrogazioni puntuali. Se si richiedono interrogazioni per range è necessario usare il 4005 che è asincrono

**Comment by rinonasti** [comment]
Ok Grazie 
Potrei avere un esempio di interrogazione usando ws3007. Grato per la fattiva collaborazione

**Comment by amollicone1982** [comment]
<testataRichiesta>
				<idOperazioneComune>2021300700003</idOperazioneComune>
				<codMittente>061022</codMittente>
				<codDestinatario>ANPR02</codDestinatario>
				<operazioneRichiesta>3007</operazioneRichiesta>
				<dataOraRichiesta>2021-01-28T09:52:43</dataOraRichiesta>
				<tipoOperazione>C</tipoOperazione>
				<protocolloComune>202130070003</protocolloComune>
				<dataProtocolloComune>2021-01-28</dataProtocolloComune>
				<tipoInvio>PRE_SUB</tipoInvio>
				<dataDecorrenza>2021-01-28</dataDecorrenza>
				<nomeApplicativo>SERDEMO</nomeApplicativo>
				<versioneApplicativo>1.00</versioneApplicativo>
				<fornitoreApplicativo>I.T. SYSTEMS</fornitoreApplicativo>
			</testataRichiesta>
			<comuneRichiesta>
				<nomeComune>CASERTA</nomeComune>
				<codiceIstat>061022</codiceIstat>
				<siglaProvinciaIstat>CE</siglaProvinciaIstat>
			</comuneRichiesta>
			<ricercaSingolaRichiesta>
				<idOperazioneANPR>xxxxx</idOperazioneANPR>
			</ricercaSingolaRichiesta>

Interrogazione con ricercaElenchiRichieste puo' essere fatta tramite 4005. Allego link alla documentazione
https://www.anpr.interno.it/portale/documentazione-tecnica
