### ISSUE TITLE
Comune nascita Motorizzazione

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2457]
Buongiorno,
alcuni cittadini ci hanno contattato in quanto "parrebbe" che Motorizzazione Civile non rinnovi loro la patente in quanto in ANPR  il comune di nascita riporta la provincia storicamente non corretta
Esempio pratico: persona nata a Ivrea nel 1942 (dal 1927 al 1945 provincia di AOSTA, antecedentemente al 1927 e successivamente al 1945 provincia TORINO - stesso codice catastale E379)
ANPR - INPS - ASL - AGENZIA ENTRATE riportano provincia Torino (gestita come comune non valido alla data)
Tenuto conto della fatica che ha comportato trovare una soluzione che potesse accontentare i cittadini e l'allineamento dei dati fra banche dati, mi chiedo se:
- vi risulta che per MOtorizzazione sia bloccante l'emissione del rinnovo patente
- - nel caso lo fosse, non sia possibile trovare un accordo fra enti al fine di applicare anche da parte di UCO la stessa regola di ANPR e AE
Grazie

UPI Torino

**Comment by UpiTorino** [comment]
caso pratico:  idANPR: 28291560 

Upi Torino

**Comment by azabatta** [comment]
Buonasera, 
per il cittadino indicato in ANPR non è stata effettuata alcuna movimentazione che comporta invio di una notifica a MCTC.   E' presente solo il subentro e nessun altro evento.
E' possibile avere l'idsoggettoANPR di un cittadino, con patente e/o autoveicoli, per il quale è stata comunicata una variazione di residenza?

**Comment by azabatta** [comment]
La issue viene chiusa. Quando saranno disponibili i dati di una posizione di interesse da analizzare,  si prega di aprire una nuova issue che faccia riferimento a questa. Buona serata
