### ISSUE TITLE
residente in ANPR senza CF non riusciamo a fare Mutazione residenza

### ISSUE THREAD

**Issue by AngelaSarteano** [italia/anpr#2458]
Buongiorno,

l'ente codice ISTAT 052031 lamenta difficoltà nell'effettuare una mutazione di Residenza APR per il cittadino Id ANPR-100839058

Il cittadino è al momento residente nel comune 058091 e risulta subentrato senza Codice Fiscale e senza comune di nascita, il comune di nascita eccezionale risulta errato secondo la documentazione presentata con la pratica (il comune di nascita corretto alla data di nascita è Taglio di Po' (RO)

E' corretto? Il codice fiscale non è dato obbligatorio per chi subentra?

la persona indicata ha bisogno dell'iscrizione per l'assegnazione del medico presso la asl, il CF è presente in puntofisco,

Attendo Vs. gentile riscontro.

Grazie
Angela Nardi 
Comune di Sarteano
3474496480

**Comment by frmariani** [comment]
Il codice fiscale non è un dato obbligatorio, ma certamente sarebbe auspicabile che fosse presente;  
dovreste contattare il comune di provenienza e sollecitarlo nella correzione dei dati, ma se il cittadino ha necessità di spostare la residenza con urgenza, consiglio di effettuare l'immigrazione e poi effettuare le modifiche del caso, quindi inserimento del cf  e modifica del luogo di nascita con contestuale validazione del CF; 
posso provare ad intercedere con il comune di Roma ma non garantisco di riuscire

**Comment by frmariani** [comment]
ho contattato il comune di Roma; devono verificare il comune di nascita presente sull'atto perchè alla data di nascita del cittadino il comune valido era Taglio di Porto Viro; verificando in Agenzia delle Entrate infatti, il cittadino ha due codici fiscali collegati.
chiudo la issue e la contatterò al numero di rifermento appena possibile
