### ISSUE TITLE
Iscrizione APR: anomalia EF001

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2459]
Comune di S.Angelo dei Lombardi,

stiamo tentando di iscrivere su nuova famiglia APR il cittadino 59193412 dal Comune di Tortolì (NU)

ma riceviamo l'errore in oggetto:
Identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata

nonostante la famiglia di arrivo sia di nuova costituzione.

data 2021-01-28 16:42:21 , idOperazioneANPR 437963536

**Comment by frmariani** [comment]
l'identificativo locale della famiglia, deve essere modificato con una successiva operazione; per effettuare il cambio di residenza del cittadino attualmente residente in un altro comune, dovete utilizzare dei dati noti al sistema ANPR, quindi l'idanpr della famiglia che si vuole sostare nel proprio comune.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
