### ISSUE TITLE
riapertura issue #242

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#246]
Corbetta, ambiente di produzione.

Nella chiusura della chiamata in oggetto avete indicato che il campo località di nascita era presente perché inserita in AnagAire e questo è vero, però nel tracciato di esportazione di AnagAire da nessuna parte è indicato che il campo codice è mutuamente esclusivo con il campo località di nascita, vedi infatti su http://servizidemografici.interno.it/anagaire-tracciato-record è indicato semplicemente:
COMUNE NASCITA TESTO (06). 
LUOGO NASCITA TESTO (38). 
Il campo non è neanche indicato come luogo eccezionale di nascita, come viene da voi trattato nel programma di estrazione dei dati da AnagAire per la creazione del file di subentro, quindi a nostro avviso l'attuale situazione dev'essere sanata per i comuni subentrati e successivamente o si correggono le specifiche dei tracciati record di AnagAire o il programma di esportazione del file di subentro deve gestire la mutua esclusività tra i campi.
Cordiali Saluti.
Luca Bonini

**Comment by gcarbonin** [comment]
Codice e luogo di nascita di AnagAire non sono mutuamente esclusivi. Sono stati valorizzati dal comune (anche per i nati in Italia) e sono stati acquisiti in ANPR come località di nascita. Nessuno degli altri comuni subentrati ha sollevato questo problema. Quindi, come già detto, se occorre eliminare questo dato per un comune in particolare occorre una richiesta del comune al Ministero dell'Interno e l'invio tramite PEC dei dati corretti (csv con tracciato da concordare).

**Comment by LucaBonini64** [comment]
Infatti in AnagAire non sono mutuamente esclusivi e non da alcun problema la presenza della descrizione della località di nascita anche se il comune è italiano. E' in ANPR che la presenza di entrambe le indicazioni diventa invece un errore bloccante e non viene neanche segnalato in fase di acquisizione del file di subentro.

**Comment by gcarbonin** [comment]
Direttamente alla mia e-mail mi dia qualche esempio di operazione andata male

**Comment by LucaBonini64** [comment]
Verificato unitamente a Sogei che il problema segnalato era dovuto al controllo e non ai dati.
