### ISSUE TITLE
[6001] Errore EN087 Emissione certificato

### ISSUE THREAD

**Issue by averrando** [italia/anpr#2461]
Ambiente di produzione Comune di VENTIMIGLIA

Tentando di rilasciare un certificato per un soggetto con il servizio 6001 otteniamo "EN087 La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti" (id operazione ANPR 438456614).
Il soggetto non presenta anomalie

Potete verificare ?

Grazie

**Comment by rvinzani** [comment]
Il soggetto è stato scritto in ANPR con il codice istat 030129 sempre relativo ad Udine ma non valido alla data di nascita del soggetto stesso (in realtà avrebbe dovuto essere 030176).
Per fare il certificato è sufficiente non passare il luogo di nascita o indicare il codistat 030129
