### ISSUE TITLE
Rettifica dati subentro per autotutela

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2462]
Comune di Modena - Ambiente di produzione

Buongiorno,
il nostro Comune ha riscontrato l' esistenza di un soggetto iscritto sia a Modena fin dal subentro (con idANPR 19340764) che a Napoli (con idANPR 69463208). Dopo le opportune verifiche Napoli ha cancellato il proprio soggetto per duplice iscrizione; ora noi dovremmo agire in autotutela per modificare i dati di iscrizione della cittadina, nel 2013 inserita come arrivata dall' estero ma ora da far provenire da Napoli. 
Abbiamo tentato la rettifica dei dati subentro ma non è consentito agire sulla provenienza, cosa che in passato ci sembrava possibile. Per cortesia potete indicarci come procedere?

Grazie, cordiali saluti
Sonia Fiorini

**Comment by frmariani** [comment]
L'ultima operazione di rettifica non andata a buon fine per il comune di Monza risale al 30/11/2020;
Gentilmente mi può indicare l'idoperazione ANPR  fallita ?
grazie

**Comment by sfmodena** [comment]
Buongiorno,
purtroppo non riusciamo a riprodurre l' errore perchè nel frattempo il soggetto è emigrato in altro Comune, stavamo cercando di sanare la posizione finchè era di nostra competenza. A questo punto chiudo la issue, ma sarebbe comunque interessante sapere come dovremmo muoverci in casi analoghi.

Grazie, saluti
Sonia Fiorini
