### ISSUE TITLE
Invio tagliandi per cambio residenza - chiarimento su Circolare MIT protocollo_27972_del_09-10-2020 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2463]
Buongiorno,

a fronte della circolare presente al seguente link: https://www.mit.gov.it/sites/default/files/media/normativa/2020-10/circolare_protocollo_27972_del_09-10-2020.pdf  
dove si indica che 
"in tema di trasferimento di residenza dell’intestatario di un veicolo, l’aggiornamento della carta di
circolazione (oggi Documento Unico), tramite il rilascio di un tagliando adesivo che il cittadino
aveva l’obbligo di applicare sul documento di circolazione, è stato sostituito dall’obbligo di
richiedere unicamente l’aggiornamento dei dati contenuti nell’Archivio Nazionale Veicoli
(ANV). Pertanto, la variazione di residenza viene ora registrata esclusivamente nell’ANV senza
rilascio al cittadino di qualsivoglia attestazione."
chiediamo se le comunicazioni di mutazione di residenza/abitazione di ANPR vengono recepite da tale archivio e quindi non genereranno più l'invio dei tagliandi. 
Grazie 

Cordiali saluti
Cinzia Girelli
GPI SPA
3346216774

**Comment by azabatta** [comment]
Buonasera,
a fronte della circolare  indicata, non ci sono state variazioni nel flusso di colloquio tra ANPR e MCTC. Come prima ANPR continua ad inoltrare a MCTC gli eventi anagrafici per i quali è prevista la notifica.
In ANPR possiamo controllare se l’evento è stato notificato con successo o meno. Le elaborazioni successive sono interne all’Amministrazione per cui una richiesta sugli aggiornamenti eseguiti deve essere indirizzata a MCTC.
Buona serata
