### ISSUE TITLE
ANPR NOK

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2464]
Buongiorno
siamo fermi?
Cordiali saluti
Ufficio Procedure Informatiche

**Comment by sfmodena** [comment]
Comune di Modena

Anche noi siamo bloccati, per cortesia potete verificare?

Cordiali saluti
Sonia Fiorini

**Comment by INSIEL1** [comment]
anche il comune di UDINE

**Comment by PAOLAPP** [comment]
anche il Comune di Venezia

**Comment by edoardodona-1** [comment]
RAVENNA.  Come tutti siamo bloccati, per cortesia potete verificare?
Cordiali saluti Dona'

**Comment by Hdemografici** [comment]
La situazione è comune anche ai nostri clienti

**Comment by RBiasi** [comment]
Confermo che anche i nostri clienti sono fermi.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by mgminelli** [comment]
Buongiorno, 

Confermo la segnalazione anche per Milano, registriamo problemi ad accedere ai webservice da nostra infrastruttura di interoperabilità ed API manager.
A disposizione per eventuali test.


Minelli Marco Giuseppe
Direzione Sistemi Informativi e Agenda Digitale
Direzione di Progetto Interoperabilità
Unità Gestione Architettura di Interoperabilità

**Comment by CGIRELLI-HUB** [comment]
Confermo che anche i nostri clienti sono fermi o quasi. Da Webapp si procede a scatti non si riesce a lavorare. 
Potete farci sapere? Il vostro nr verde ha indicato al comune di Vicenza che non ci sono problemi sulla webapp. 
Grazie 
Cordiali saluti 
Cinzia Girelli
Gpi spa
3346216774

**Comment by fcastellani81** [comment]
Buongiorno,
segnalo che anche i nostri clienti procedono "a scatti" e il più delle volte non riescono a lavorare correttamente. Da webapp l'attività di eventuale consultazione è molto lenta.
Grazie
Cordiali Saluti

**Comment by FilippoPapi** [comment]
la situazione è stata ripristinata
