### ISSUE TITLE
Smart Card sconosciute

### ISSUE THREAD

**Issue by UFFIC** [italia/anpr#2467]
Buongiorno,
scriviamo dal Comune di Amatrice (RI) per fare presente quanto segue:
nel mese di ottobre 2020 abbiamo ritirato le Smart Card in Prefettura ma non hanno mai funzionato. Inserite nel lettore appare "carta sconosciuta".
I lettori non sono mai stasti spediti, li abbiamo presi in prestito da un Comune limitrofo subentrato.
Abbiamo avuto ticket aperti per settimane con il numero verde, non hanno mai richiamato o, se lo hanno fatto, non hanno insistito più di tanto.
A questo si aggiunge il problema che non si riesce ad entrare in ANPR per inviare i files di pre-subentro (credo che non siano mai stati inviati), una volta inserite le pw abbiamo la comunicazione " **si e' verificato un errore durante la fase di autenticazione/
Si è verificato un errore di comunicazione nella fase di autenticazione. Possibili ritardi nell'inserimento delle credenziali."**

In attesa di riscontro si porgono distinti saluti.

Per l'Ufficio
MARIA LAURA PORRO
GIACOMINI CRISTINA
 --- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by cmigliardi** [comment]
buonasera,    cortesemente  potete  darmi maggiori  dettagli?  oppure potete  fornirmi un indirizzo di posta o un recapito per contattarvi?   grazie   Cecilia  Migliardi

**Comment by cmigliardi** [comment]
mi può  scrivere a    cmigliardi@sogei.it

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
