### ISSUE TITLE
[5001] rettifica in errore per coerenza date

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2469]
Ambiente di produzione, comune di Treviglio.

La mutazione famiglia di tipo rettifica indirizzo ID ANPR 444760168 restituisce l'errore 
EN526 : Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 13-11-2018

Non riusciamo a capire dove sia la data 13/11/2018 che suggerisce la risposta alla richiesta, la consultazione con servizio 3002 di ciascun componente riporta sia come data decorrenza residenza che come data origine famiglia che come data decorrenza legame il 13/10/2018, data che noi usiamo nella richiesta.

Qual è il problema ?
Grazie

**Comment by frmariani** [comment]
I soggetti della famiglia sono stati inviati due volte al subentro, quindi in effetti abbiamo riscontrato qualche problema;
riprovi per favore e mi faccia sapere

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
