### ISSUE TITLE
Inserimento annullamento matrimonio impossibile

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2470]
In riferimento alla #2451 , il Comune è riuscito a registrare l'operazione su un soggetto.
L'altro soggetto coinvolto dall'annullamento matrimonio, è nel frattempo in una convivenza di fatto.
Il Comune riceve quindi il seguente errore:

Alla data 06-02-2020 il soggetto 104576521 risulta gia' coniugato o unito civilmente con un altro soggetto (Codice: EN272)
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-04 11:32:49 , idOperazioneANPR 445470812 (Codice: EN527)

**Comment by frmariani** [comment]
In effetti abbiamo rilevato un bug prontamente eliminato; riprovi per favore e mi faccia sapere

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
