### ISSUE TITLE
Gestione notifiche mutazioni residenze non arrivate

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#2471]
Buongiorno,
Ci siamo accorti dai riscontri con l'ufficio elettorale che alcune notifiche di settembre di mutazione residenza da Anpr non erano arrivate al nostro gestionale e quindi non erano state lavorate. Come mai? Sulla web app di Anpr le ho trovate ma mi chiedo come mai sia accaduto e come faccio a sapere se si sia verificato anche nei mesi precedenti. La visualizzazione delle notifiche sulla web app non è molto comoda: come posso fare un salvataggio o un export di tutte le notifiche mutazione residenza dell'anno 2020 dalla web app per poi confrontarle con quelle arrivate e lavorate sul nostro gestionale? Grazie.

**Comment by rvinzani** [comment]
Se le notifiche sono visibili sulla web app è possibile che non siano transitate sul vostro gestionale. E' comunque possibile scaricarle con il servizio 4005 che è lo stesso usato dai gestionali per il recupero delle stesse
