### ISSUE TITLE
Comune di Ancona - Errore EN212 a seguito di cancellazione per decesso

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2472]
Abbiamo effettuato la cancellazione per decesso di un nostro residente ID ANPR 107220305 ed a seguito della cancellazione il sistema ha rilevato l'errore EN212 - Relazioni di parentela incongruenti per la famiglia, verificarle prima di emettere certificati di stato di famiglia, ma il soggetto era l'unico elemento del nucleo familiare. Si richiedono delucidazioni in merito al suddetto errore. Grazie e saluti.

**Comment by frmariani** [comment]
L'errore emesso per l'operazione di decesso del soggetto è un warning:  EN225 - Aggiornare la famiglia del soggetto cancellato indicando un nuovo intestatario ed eventualmente i relativi rapporti di parentela;
è un alert generico che nel vostro caso non deve essere preso in considerazione.
Non ho evidenza dell'errore bloccante che segnalate neanche in fase di certificazione, quindi gentilmente fornite l'idanpr dell'operazione fallita. grazie

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
