### ISSUE TITLE
Comunicazione 7002 (a seguito richiesta 4001) non produce risposta

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2473]
In data 03.02.2021 è stata eseguita una comunicazione 4001 con ID 444192504, alla data odierna del 05.02.2021 le comunicazioni 7002 restituiscono errore EN122 "Richiesta 444192504 ancora in elaborazione" (id operazione comune 39241, tipo invio PROD, codice Istat comune 003066, id operazione ANPR 446525571) .
Chiedo sblocco richiesta comunicazione 4001, diversamente non posso ottenere risposta con comunicazione 7002 e non posso neanche eliminarla perchè impedirebbe di generare una nuova richiesta producendo errore.

QUESTO PROBLEMA INSISTE ANCHE SU ALTRI COMUNI PER comunicazioni 4001 inviate con esito POSITIVO il 03.02.2021.

**Comment by tuchino1969** [comment]
**[RETTIFICA QUESITO]**
In data 03.02.2021 è stata eseguita una comunicazione 4001 con ID 444192504, alla data odierna del 05.02.2021 le comunicazioni 7002 restituiscono errore EN122 "Richiesta 444192504 ancora in elaborazione" (id operazione comune 39241, tipo invio PROD, codice Istat comune 003066, id operazione ANPR 446525571,)
> Chiedo sblocco richiesta comunicazione 4001, diversamente non posso ottenere risposta con comunicazione 7002 e non posso neanche eliminarla perchè impedirebe di generare una nuova richiesta producendo errore.

**Comment by amollicone1982** [comment]
Id richiesta 444192504 elaborata
