### ISSUE TITLE
Flag "Iscrizione famiglia conclusa" su procedura "Mutazione Dati AIRE"

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2474]
Salve,
sul portale web stiamo effettuando lo scorporo di alcuni componenti di una famiglia AIRE (2 su 5) in una famiglia AIRE distinta tramite "Mutazione Dati AIRE" / "Rettifica".

Avremmo un dubbio sul flag **Iscrizione famiglia conclusa** presente in allegato.
Dovrebbe servire a non ripetere la medesima procedura per tutti e tre i componenti? Oppure a cos'altro?

![Completa Iscrizione Famiglia](https://user-images.githubusercontent.com/47904600/107048310-18f92280-67c9-11eb-9d4a-ce5a798c631f.png)

**Comment by ncapozzi** [comment]
Buongiorno,
serve ad indicare quando la famiglia è completa ai fini della certificabilità

N. Capozzi

**Comment by vix-db** [comment]
Se al completamento dell'ultimo componente non indichiamo quindi "Iscrizione famiglia conclusa: SI" cosa è necesario fare affinché sia completa ai fini della certificabilità?

**Comment by ncapozzi** [comment]
Potete effettuare una mutazione famiglia/convivenza con tipo = 3 DATI GENERALI FAMIGLIA CONVIVENZA impostando nella lista controlli Nome =   FI | Valore = 0 famiglia completa
