### ISSUE TITLE
CIE per cittadino AIRE residente in altro comune

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2475]
Comune di Montoro (AV)

abbiamo problemi ad emettere una CIE per un cittadino AIRE (id: 73967748) residente in altro comune subentrato (CASSANO ALL'IONIO)

idOperazione: 42333319449279595

**Comment by rvinzani** [comment]
Buongiorno, attualmente la CIE per i cittadini AIRE è possibile richiederla solamente dai consolati di alcuni paesi europei
