### ISSUE TITLE
[5001] Errori in rettifica indirizzi

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2476]
Ambiente di produzioni, comune di Marcaria

Stiamo effettuando delle rettifiche indirizzo per sistemare lo stradario.
Alcune richieste 5001 sono andate in errore ma non capiamo perché:  

1. operazione ID ANPR 448024024 con errore "EN526 :Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 01-01-1999" : noi inviamo la richiesta con data 6/7/2011 che risulta esser la data decorrenza della residenza attuale anche secondo il servizio 3002, non capiamo come mai non funzioni.
2. operazione ID ANPR 447972026 con errore "EN526 Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 01-01-1999" : noi inviamo la richiesta con data 22/06/2010 che risulta esser la data decorrenza della residenza attuale anche secondo il servizio 3002, non capiamo come mai non funzioni.
3. operazione ID ANPR 243556598 con errore "EN526 Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 07-08-2015" : noi inviamo la richiesta con data 5/1/2019 che risulta esser la data decorrenza della residenza attuale anche secondo il servizio 3002, non capiamo come mai non funzioni.
4. operazione ID ANPR 447906539 con errore "EN526 : Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 06-07-2019" : noi inviamo la richiesta con data 23/10/2019 che risulta esser la data decorrenza della residenza attuale anche secondo il servizio 3002, non capiamo come mai non funzioni.

Grazie

**Comment by amollicone1982** [comment]
La rettifica deve essere fatta alla data corrispondente alla minore delle date decorrenza residenza dei soggetti della famiglia.
Nel caso dell'operazione 11194265 la famiglia ha tre soggetti di cui la minore è 01-01-1999
