### ISSUE TITLE
Variazione di Decesso  WS2001

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2477]
COMUNE DI CAPONAGO

Varisco M.Giuseppina

Buongiorno
ho la necessità di effettuare una variazione di decesso, il vostro sistema (sia WS che WA) mi restituisce il seguente errore :
EN240 La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 08-02-2021.

Di seguito le informazioni presenti nell'esito che restituisce il ws

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-08 08:27:05 , idOperazioneANPR 447660554

Resto in attesa di gentile riscontro.
Grazie

**Comment by frmariani** [comment]
Il giorno 08/07/2021 è stata effettuata un'operazione sul cittadino, pertanto non è possibile utilizzare una data antecedente per il decesso; annullate l'operazione di mutazione idanpr 447657797 e riprovate la cancellazione per decesso con la data necessaria.

**Comment by frmariani** [comment]
ho verificato che avete seguito la procedura consigliata ed il cittadino è stato correttamente cancellato per decesso.
La issue viene chiusa.
