### ISSUE TITLE
Omocodia e impossibilità alla variazione dei dati

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2478]
Buongiorno,
illustriamo il seguente problema a cui cerchiamo soluzione da più di un anno.
In ANPR c'erano due persone differenti con stesso codice fiscale, una residente a Ravenna e una a San Vittore Olona. A queste persone era necessario variare i dati anagrafici ma l'ANPR non ha permesso ai Comuni di poter operare.
Il Comune di Ravenna ha proceduto a richiedere un OMOCODICE attraverso ANPR e il Comune di San Vittore Olona ha cancellato per doppia iscrizione il suo residente. Ad oggi, quindi, in ANPR risulta iscritto solo il nostro residente a cui però non riusciamo a variare i dati di nascita perché "soggetto individuato in AT è in lavorazione per risoluzione omocodia":
Id operazione ANPR 448372627
Codice errore anomalia EN396.

Restiamo in attesa di riscontro e, ringraziando, porgiamo cordiali saluti.

**Comment by rvinzani** [comment]
Per il problema è stato aperto il ticket 22229207 con cui vi daremo assistenza.
Chiudo pertanto questa issue
