### ISSUE TITLE
 Errore Anpr Cod: AEE95 - Operazione non effettuabile

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2479]
COMUNE DI BREMBATE PRODUZIONE

Il comune sta provando a mutare le generalità del seguente soggetto: 81624750
All'invio riporta il seguente errore: 

1 Errore Anpr Cod: AEE95 - Operazione non effettuabile - Cognome: XXXXX Nome: XXXXXXX CF: XXXXXXX -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-09 11:16:47 , idOperazioneANPR 449056491 - Cognome: XXXXXX Nome: XXXXXXX CF: XXXXXX

Il CF è attuale è validato e marcato ANPR.

**Comment by frmariani** [comment]
Nella richiesta di mutazione dei dati inserite un codice fiscale inesistente; forse è stato calcolato dal gestionale ?

**Comment by jonnyfx95** [comment]
Il cf calcolato dall'applicativo non è esistente, l'ente vuole mutare cognome e nome all'individuo 
Viene utilizzata; "Nessuna operazione" in quanto il CF presente in ANPR è validato e marcato.
L'XML di invio riporta giustamento questo:
 
`<gestioneCF>0</gestioneCF>`

**Comment by frmariani** [comment]
gestioneCF riporta giustamente l'indicazione della validazione, ma dovete eliminare il cf calcolato da gestionale inserito nell'oggetto generalitaDaModificare

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
