### ISSUE TITLE
Visura anagrafica in ANPR

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#248]
Come segnalato da alcuni utenti, apro questa issue per tracciare la modifica ed implementazione.

Il DPR n. 126 del 2015 ha aggiunto il comma 5 all'art. 35 del DPR n. 223/89 (Reg. anag.). Tale "nuova" normativa introduce anche in anagrafe la "visura" così come disciplinata dagli articoli 7, 8, 9 e 10 del CAD, espressamente richiamati dal citato comma 5 dell'art. 35.

Ciò significa che il richiedente ha diritto di ottenere tutte le informazioni presenti in ANPR, con le modalità della "visura" e NON del certificato, relative però SOLO a se stesso. In pratica, a fronte di ogni certificato, la web app dovrà consentire il rilascio di una "visura" contenente gli stessi dati ma senza la dichiarazione "certificativa" dell'ufficiale d'anagrafe. Inoltre, la visura serve anche per confermare le richieste di verifica delle autocertificazioni, alle quali NON si può rispondere con un certificato! 
Mi risulta che la Web app non preveda questa possibilità (forse esiste solo la visura corrispondente ai dati individuali analoga al certificato di residenza).

**Comment by gcarbonin** [comment]
Iniziamo a stampare i dati della scheda individuale dalla Web App che riporta tutti i dati del soggetto. vediamo se va bene o se sono necessarie modifiche/integrazioni. Faccio presente che questa stampa inizialmente si chiamava "Visura anagrafica"; in sede di collaudo è stata rinominata in Stampa della scheda individuale, Si ottiene dalla consultazione dei dati della persona.

**Comment by Eduardo1977** [comment]
Buongiorno, è possibile richiedere il pdf della "visura relativa alla scheda individuale completa" tramite web service, così come si ottiene dalla webApp? Non sono riuscito a capire se avviene tramite qualche richiesta particolare al ws3002. Grazie

**Comment by gcarbonin** [comment]
Questa funzionalità non è attualmente prevista; utilizzando il servizio 3002 è possibile realizzarla autonomamente.

**Comment by Eduardo1977** [comment]
Buongiorno, a distanza di qualche mese vorrei chiedere nuovamente se tramite qualche web service (3002, 6001, ...) è stata implementata (o almeno prevista) la funzionalità che restituisce in formato PDF la visura relativa alla "scheda individuale completa"
