### ISSUE TITLE
RETTIFICA DATI FAMIGLIA COMUNICATI CON IL SUBENTRO

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2480]
ID FAMIGLIA 54941182
Bisogna modificare alcune date erronee comunicate con il subentro ed i gradi di parentela.
1. Risulta errata la data di costituzione della famiglia
2. Risulta errata la data di ingresso in famiglia dell'I.S. ID ANPR 95430863
3. Risulta non aggiornato al nuovo I.S. il legame di parentela dell'id ANPR 95430865 da nipote a figlio/figlia e la data del legame di parentela (21/04/2014 invece che 18/09/2012)
4. Risulta non aggiornato al nuovo I.S. il legame di parentela dell'id ANPR 95430862 da figlio/figlia a moglie/marito e la data del legame di parentela (21/04/2014 invece che 04/01/2002)
Comune di Castellammare di Stabia
Conza Gianpaolo

**Comment by frmariani** [comment]
Le posso dare delle indicazioni generali, ma per assistenza sulle operazioni è necessario un contatto per le vie brevi;
la data di costituzione della famiglia non è rettificabile; per la rettifica della data al punto 2 dovete prima annullare tutte le operazioni effettuate sul soggetto (vi ricordo che la variazione dei dati anagrafici di soggetti validati non è annullabile);  per il punto 3 e 4 dovete utilizzare la mutazione Famiglia/convivenza tipo mutazione Composizione scheda (WS 5001 tipo mutazione 2) indicando opportunamente la data di decorrenza dell'operazione

**Comment by gianpaol** [comment]
In realtà mi serviva solo una conferma di quello che già sospettavo... Si è spiegata benissimo. Quindi tutte le date riguardanti le costituzioni delle famiglie se caricate errate al momento del subentro non possono essere modificate. Il problema è che molte famiglie caricate dal Comune di Castellammare in ANPR hanno una simile situazione. Non c'è proprio nessun modo per ovviare a questa problematica?

**Comment by frmariani** [comment]
Mi dispiace ma non c'è possibilità di modifica; posso dirle però che non è una data significativa;

**Comment by gianpaol** [comment]
grazie mille

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
