### ISSUE TITLE
Errore Anpr Cod: EF062 - Sono presenti piu' famiglie con lo stesso Identificativo scheda attribuito dal comune. Indicare solo l'identificativo attribuito da ANPR alla scheda famiglia

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2481]
COMUNE DI PARMA PRODUZIONE:

Il comune sta cercando di fare una mutazione residenza AIRE - Cambio di indirizzo e aggiunto in famiglia già esiste.
All'invio ripota il seguente errore: 

> 1 Errore Anpr Cod: EF062 - Sono presenti piu' famiglie con lo stesso Identificativo scheda attribuito dal comune. Indicare solo l'identificativo attribuito da ANPR alla scheda famiglia - Cognome: XXXXX Nome: XXXX CF: -
> 2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-08 16:54:19 , idOperazioneANPR 448478551 - Cognome: XXXX Nome: XXXXX CF: XXXX

ID ANPR del soggetto che sta affettuando la mutazione: 24553590
ID ANPR del I.S in cui il soggetto si sta spostando: 24553591

Interrogando il soggetto: 24553591 per ID attribuioto dal comune (FE019995)  viene riportato il seguente errore: 

> EN533 Identificativo comunale famiglia non univoco: usare id anpr della famiglia

Non riuscimo a capire come trovare la famiglia duplicata in ANPR in modo da poterla bonificare.
Ho provato a richiedere un'estrazione di tutti i cittadini AIRE del comune, ma sembra che il file generato da ANPR sia corretto (peso 1 kb) ID RICHIESTA ESTRAZIONE: 448516005

E' possibile avere gli id Anpr degli individui con codice famiglia duplicati?

**Comment by ncapozzi** [comment]
Buongiorno,
in generale non dovreste utilizzare l'identificativo famiglia comunale ma solo quello ANPR in tutte le operazioni che vengono trasmesse ad ANPR.
Comunque nello specifico le due famiglie che hanno lo stesso idcomunale FE019995 sono 53200311 e 53202484

N. Capozzi
