### ISSUE TITLE
Comune di Ulzio / Oulx

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2482]
Buonasera,
abbiamo immigrato nel Comune di Ravenna dal Comune di Oulx un cittadino nato in tale Comune.
Da copia integrale dell'atto di nascita la denominazione esatta del Comune quando tale cittadino è nato era ULZIO, come da verifica nella vostra tabella. Abbiamo quindi caricato il dato esatto ma non si aggiorna il Comune in Agenzia delle Entrate che, contattata, riferisce che nell'elenco dei Comuni in "Applicazioni anagrafiche" il Comune di Ulzio NON risulta in elenco (esiste solo OULX). Abbiamo provato a modificare il dato in AE dalla webapp ma non si può fare (vedasi allegato).

![Cattura](https://user-images.githubusercontent.com/57749903/107374261-af8a5400-6ae7-11eb-95d7-cd7a46c5e6b2.JPG)

Come possiamo avere la denominazione esatta anche in AE? 

Cordiali saluti.

**Comment by rvinzani** [comment]
A parità di codice catastale l'Agenzia delle Entrate visualizza la denominazione più recente.
Per rendere visibile la denominazione storica il cittadino deve recarsi in Agenzia Entrate e farne esplicita richiesta.
Chiudo la issue. In caso fossero necessarie ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
