### ISSUE TITLE
ANPR-CLIENT

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2483]
Buonasera,
Per conto COMUNE DI CASERTA 061022 
Nel tool testconn manca la invocazione al servizio WS4005 
quali sono i file java , xml , xsd da inserire e/o modificare

Grazie per la fattiva collaborazione

**Comment by gife67** [comment]
Buonasera,
premetto che i sorgenti del client sono forniti a titolo di esempio per agevolare l'integrazione con i servizi ANPR, non forniamo l'aggiornamento a tutti i servizi che man mano vengono resi disponibili sulla piattaforma ANPR, anche perchè non c'è l'obbligo di utilizzare questo client di esempio e c'è la liberta di personalizzarlo e migliorarlo come si vuole.

Comunque i passi principali sono facilmente deducibili analizzando il codice fornito:
- aggiornare i file WSDL/XSD in src/main/resources/wsdl. Aggiungere nel file .wsdl in corrispondenza dell'operation 4005 la policy così come fatto in ogni operation, aggiungendo all'input questa riga:
				<wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="policy-X509v3.xml"/> 
- Creazione delle classe Op4005Handler, prendendo come esempio le classi delle altre operation
- Aggiunta elementi dell'operation 4005 alla classe WSTypeHandler
- Aggiunta gestione operation 4005 alla classe DispatchHandler

Spero di averla aiutata.
Cordiali saluti.
Giuseppe
