### ISSUE TITLE
[3002] informazioni su tag residenza

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2484]
Buongiorno
collegandomi a #1615 vorrei sapere quali tipologie di indirizzo (tabella 25) possono tornare contemporaneamente in una consultazione 3002?

immagino che per un cittadino residente possa tornare uno con tipo indirizzo =1 (residenza) e 1 con indirizzo=2 (dimora abituale)
ma non uno con tipo indizizzo=4 (residenza estera)

i tipi 1, 4, 10 e 11 sono esclusivi?

grazie mille
Riccardo

**Comment by ncapozzi** [comment]
Si conferma che i tipi 1, 4, 10 e 11 sono esclusivi

Saluti
N. Capozzi
