### ISSUE TITLE
SMART CARD SINDACO 

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2485]
Salve,
dalla prefettura di Trapani in data 04/02/2021 abbiamo ricevuto le smart card del nuovo Sindaco di Marsala con la prima parte di password pin e puk.
Alla data odierna, il Sindaco non ha ancora ricevuto l’email con la seconda parte della password pin e puk.
grazie.
Comune di Marsala
Filippo Asaro
0923993382

**Comment by Leonforte** [comment]
Buongiorno, la seconda metà delle credenziali è stata inviata a sindaco@comune.marsala.tp.it
Buon lavoro, saluti
