### ISSUE TITLE
CONVIVENZA DI FATTO

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2486]
E' possibile cessare una convivenza di fatto in ANPR? Se sì, in che modo?

**Comment by frmariani** [comment]
Per la cessazione della convivenza si deve utilizzare l'operazione Mutazione tutti i dati, tipo di mutazione Risoluzione convivenza (WS 5008 TipoMutazione 17)

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
