### ISSUE TITLE
Intervento sistemi Agenzia Entrate

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#2488]
Il giorno **17 febbraio**, a partire dalle ore **17 fino alle 20**, verrà effettuato un intervento di manutenzione sui sistemi dell'Agenzia delle Entrate. Non potranno pertanto essere inviati file in ambiente di subentro e presubentro nel periodo indicato
Anche i servizi di ANPR che prevedono la chiamata ai servizi di Agenzia delle Entrate (es. variazione dati anagrafici, validazione codice fiscale ) non saranno disponibili

**Comment by sfmodena** [comment]
Da: "rvinzani" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Inviato: Giovedì, 11 febbraio 2021 9:50:29 
Oggetto: [italia/anpr] Intervento sistemi Agenzia Entrate (#2488) 





Il giorno 17 febbraio , a partire dalle ore 17 fino alle 20 , verrà effettuato un intervento di manutenzione sui sistemi dell'Agenzia delle Entrate. Non potranno pertanto essere inviati file in ambiente di subentro e presubentro nel periodo indicato 
Anche i servizi di ANPR che prevedono la chiamata ai servizi di Agenzia delle Entrate (es. variazione dati anagrafici, validazione codice fiscale ) non saranno disponibili
