### ISSUE TITLE
Tabella Comuni

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#249]
Buongiorno.
La tabella Comuni, aggiornata al 14.7.2017, non riporta i comuni della Sardegna riorganizzati nelle nuove province istituite dal 1.1.2017 (es. OLBIA dalla provincia di Olbia Tempio passa alla provincia di Sassari).
Abbiamo già iscritto parecchi soggetti provenienti da comuni sardi, quindi, aggiornato il ns gestionale, ma sarebbe auspicabile che la tabella dei comuni di ANPR fosse dettagliatamente aggiornata, vista l'importanza che riveste a livello nazionale.
Grazie
Saluti
Ufficio Procedure Informatiche

**Comment by gcarbonin** [comment]
L'aggiornamento della tabella per tener conto delle variazioni territoriali della Sardegna sarà effettuato a fine settembre, in contemporanea con Agenzia delle Entrate, MCT e INPS.

**Comment by UpiTorino** [comment]
ok grazie!
