### ISSUE TITLE
Cancellazione per Ripristino Posizione Precedente che non ha avuto effetto

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#2490]
Buongiorno,
scrivo per conto del comune di Terracina per segnalare la seguente anomalia:
Con data decorrenza 02/03/2020 è stato iscritto nel comune il cittadino con Id = 91419126, idOperazione = 284458081.
Con data decorrenza 29/10/2020 è stata inviata una Cancellazione Altri motivi con motivo ripristino Posizione precedente, idOperazione = 362051806.
Pur avendo ottenuto risposta positiva all'invio dell'operazione di cancellazione, il cittadino risulta ancora residente...come è possibile?
Ho provato inoltre da WebApp ad annullare l'operazione di cancellazione (con l'intento di annullare a cascata tutte le operazioni per tale individuo) ma quando ricerco l'individuo (sia per CF e sia per Id) appare il messaggio:
"Non Sono stati trovati soggetti corrispondenti ai criteri di ricerca"
In consultazione invece lo stesso individuo è consultabile tranquillamente.

Saluti
Assistenza Tecnica per il Comune di Terracina

**Comment by rvinzani** [comment]
Il soggetto è stato iscritto nel comune di Terracina proveniente dall'India.
Per ripristinare la posizione anagrafica è sufficiente cancellare la posizione in ANPR. Il soggetto rimarrà in ANPR con stato cancellato

**Comment by acarcea** [comment]
Non ho ben capito la soluzione proposta visto che un'operazione di cancellazione altri motivi è già stata correttamente inviata (idop = 362051806) ma non ha avuto alcun effetto.
Dovrei quindi fare una nuova operazione di cancellazione Altri Motivi con stesso motivo della precedente inviata senza effetto (motivo ripristino posizione precedente)?

Saluti
Assistenza Tecnica per il Comune di Terracina

**Comment by rvinzani** [comment]
Sì, perchè ha fatto degli annullamenti successivi.
Effettui nuovamente la cancellazione

**Comment by acarcea** [comment]
Buongiorno,
chiamo dal Comune di Terracina...
stavo provando a fare, da webApp, la cancellazione suggerita per l'individuo con id = 91419126 ma nella pagina "Dati Dell'operazione" al click su Conferma non si riesce ad andare avanti in quanto appare l'errore: 
"Dati dell'operazione - Il campo Tipo invio è obbligatorio"
"Il campo Ruolo soggetto è obbligatorio"
Stranamente il campo Ruolo Soggetto appare in bianco e non valorizzabile in alcun modo. Quasta anomalia è presente solo per questo cittadino.
Si prega di risolvere l'anomalia su questo individuo al fine di riuscire a sbloccare la situazione
In caso di necessità posso essere contattata al numero 3381258990 oppure alla mail mariagrazia.tomao@comune.terracina.lt.it
Maria Grazia Tomao

**Comment by rvinzani** [comment]
Chiudo la issue come da comunicazione intercors

**Comment by katiki04** [comment]
Ciao, ho inviato una richiesta per il cambio di residenza tramite il portale anpr in ottobre dal non c'è alcun aggiornamento e anche il comitato corrispondente non lo sa, quindi voglio eliminare quella pratica. potresti per favore far sapere come posso eliminare questa domanda.
