### ISSUE TITLE
[5008] Cambio nominativo e CF: errore AEE95 Operazione non effettuabile

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#2491]
COMUNE DI VILLA MINOZZO - AMBIENTE DI TEST

Buongiorno, sto facendo alcune prove di cambio cognome e nome con contestuale modifica del CF ma ottengo sempre l'errore in oggetto, sia indicando il nuovo CF nelle generalitaDaModificare che non indicandolo. 
Il soggetto è allineato AE e marcato ANPR. 
Il tag gestioneCF non è indicato pertanto equivale a 0 (Validazione).

Es.
id. soggetto ANPR 20824147  
id. operazioni ANPR 32671550 e 32671552

Potete aiutarmi a capire il problema?
Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by frmariani** [comment]
non è possibile effettuare delle prove in ambiente di test con un codice fiscale reale e subentrato in ANPR; 
per i test si consiglia di creare dei codici fiscali fittizi

**Comment by MoniaPedrazzoli** [comment]
Ho ripetuto la prova con un altro soggetto di fantasia, inserito ex novo (validato e marcato), ma ottengo lo stesso risultato.

Es.
id. soggetto ANPR 32937194
id. operazioni ANPR 32674313 e 32674327

**Comment by frmariani** [comment]
potete riprovare per favore ?

**Comment by MoniaPedrazzoli** [comment]
Ha funzionato, grazie.
