### ISSUE TITLE
[web-service] Errore "connect timed out"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2492]
ambientre di PRODUZIONE - comune di CARNATE (015049)

buongiorno

il cliente segnala che a giorni alterni non funziona il collegamento con ANPR.
il log del client tracciano come errore un problema di timeout.

il cliente ci conferma che non sono state eseguite attività sull'infrastruttura e che l'ip 217.175.52.225:443 non è bloccato dal firewall.
il fatto che a giorni alterni il sistema funziona, ci fa dedurre che l'ip pubblico della macchina chiamante sia censito correttamente tra quelli autorizzati.

potete verificare lato server se c'è qualche problema nei flussi che arrivano da questo ente?

grazie.
Alessandro Monopoli ADS

**Comment by gife67** [comment]
Buongiorno, 
non risulta che il Comune abbia il Codice Istat 015049, ma il 108016. Esaminando le richieste effettuate dal Comune nei giorni scorsi, ci risultano tutte pervenute dall'indirizzo IP 109.168.43.157, l'unico che è stato richiesto di abilitare. Nei giorni scorsi ed oggi non ci sono stati problemi di connettività con la piattaforma ANPR e risultano invocazioni effettuate dal Comune, tutte hanno ricevuto una risposta con tempi inferiori ad 1sec. Il problema non è di abilitazione e va sicuramente ricercato all'interno dell'infrastruttura di rete del Comune e/o del suo provider. 
Cordiali saluti

**Comment by AMonopoliADS** [comment]
Grazie del riscontro Giuseppe.

chiedo scusa per l'errore nel codice comune, distrattamente ho indicato il codice precedente il cambio di provincia.
aggiorniamo il cliente con queste sue indicazioni.

buona giornata
Alessandro

**Comment by gife67** [comment]
Provvedo a chiudere questa issue, nel caso dovreste aver bisogno di ulteriori chiarimenti, potete aprirne una nuova collegandola a questa.
Buona giornata
Giuseppe
