### ISSUE TITLE
IMMIGRAZIONE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2493]
Buongiorno,
Comune CASERTA 061022 (PRE_SUB)
QUESITO:
E' inviata in automatico, al Comune di provenienza, una notifica quando il Comune di arrivo invia la transazione ?
WS5001 intero nucleo - WS5005 di uno o più componenti. 
Grazie

**Comment by rvinzani** [comment]
E' inviata in automatico a fronte del servizio 5001 tipo mutazione 4,5,6,7,8,9  e del servizio 5005  una notifica per ogni componente

**Comment by rvinzani** [comment]
chiudo la issue. In caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa stessa
