### ISSUE TITLE
[5001] Rettifica n errore

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2494]
Ambiente di produzione, comune di Vigonza

operazione ID ANPR 452437330 con errore "EN526 :Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 04-04-2011" : noi inviamo la richiesta con data 07/10/2011 che risulta esser la data decorrenza della residenza attuale anche secondo il servizio 3002, per entrambi i componenti, non capiamo come mai non funzioni.

**Comment by frmariani** [comment]
L'operazione di Rettifica della residenza, essendo appunto una rettifica retroattiva, deve tener conto di tutti i  componenti della famiglia che sono stati presenti in quell'indirizzo, anche se oggi non sono più presenti.
il cittadino idanpr 37737706 è stato presente a quell'indirizzo dal 4/04/2011 fino al 5/01/2019, ecco il motivo dell'errore

**Comment by busaster** [comment]
A questo punto sono a chiedere una miglioria: visto che risulta molto difficile recuperare una data decorrenza visti i molti casi che si presentano e visto che in caso di rettifica è ANPR in caso di data incoerente ad indicarmi la data corretta, non potrebbe il servizio usare forzatamente la data che ANPR reputa corretta inviando nella risposta un warning che informa l'utente che è stata usata una data differente da quella inserita nell'input ?

**Comment by frmariani** [comment]
mi dispiace ma l'automatismo nei casi di rettifica dei dati non è mai consigliabile; l'Ufficiale d'Anagrafe deve avere piena consapevolezza dell'operazione che si appresta ad effettuare.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
