### ISSUE TITLE
NOTIFICHE - WS4005

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2495]
Comune 061022
invocando il servizio WS4005
 
id operazione comune 2021400500014
errore 999 Operazione non effettuabile  con  N000
mentre con N010 Servizio non attivo o non disponibile

Grazie

**Comment by amollicone1982** [comment]
Ci può indicare l'idoperazione? con id operazione comunale non trovo l'operazione

**Comment by rinonasti** [comment]
OK grazie risolto.
Il formato della risposta di ws4005 è solo gz?

**Comment by amollicone1982** [comment]
si
