### ISSUE TITLE
Sistema di numerazione metrica negli indirizzi

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2497]
COMUNE DI CALUSCO D'ADDA
Ambiente di produzione

Buongiorno,
il comune in oggetto utilizza per gli accessi del proprio territorio un sistema di numerazione "metrica"
riporto un esempio inventato:
**ROSSI MARIO Residente in VIA ROMA metrico 29**
stampando un certificato di residenza notiamo che viene convertito in **Km 0.029**.

Il comune ci segnala che la certificazione dovrebbe riportare i metri 29 e non Km 0.029
Ci sono delle ragioni particolari per cui viene convertito in chilometri?

Grazie

**Comment by rvinzani** [comment]
Il layout dei certificati ed il loro contenuto è stato condiviso con il Ministero dell'Interno e con i comuni che hanno partecipato alla sperimentazione di ANPR

**Comment by rvinzani** [comment]
chiudiamo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
