### ISSUE TITLE
Attribuzione omocodice

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2498]
Buongiorno,
cortesemente, è possibile avere preciso riferimento per quanto concerne la richiesta di omocodice?
Dalle note riportate sia dal documento relativo a Risoluzione disallineamenti con Agenzia Entrate avevo inteso che occorresse:
- verificare la documentazione in nostro possesso, acquessendo anche dal citttadino informazioni relativi agli spostamenti sul territorio nazionale
- preso atto che trattasi di soggetti diversi, procedere con la richiesta di attribuzione Omocodice da Mutazione Tutti i dati
- scrivere a entrate.archivioanagrafico@agenziaentrate.it allegando tutta la documentaizone in nostro possesso a completamento della procedura
Sino a qualche mese orsono non abbiamo avuto problemi, ora però un operatore (sempre lo stesso) ci restituisce email:

** **_Buongiorno,
in relazione alla richiesta in oggetto  si prega di inviare tutta la documentazione all’Ufficio dell’Agenzia competente per territorio il quale, dopo aver effettuato le dovute verifiche , si occuperà di istruire la pratica ed effettuare le necessarie operazioni.
Al seguente link tutti i riferimenti:
https://www.agenziaentrate.gov.it/portale/uffici12/-/uffici/uffici_INSTANCE_mi0d0mGReCpq/dettaglioufficio/T7D_** **

Posso avere conferma che trattasi di prassi corretta e pertanto NON dobbiamo più scrivere ad Archivio ma passare attraverso gli uffici Territoriali?
Grazie

Anna Maria AIMONE
UPI Torino

**Comment by rvinzani** [comment]
La richiesta di omocodia può essere effettuata o tramite ANPR o rivolgendosi all'ufficio territoriale dell'Agenzia delle Entrate. La Direzione Centrale provvederà successivamente a verificare la pratica ed emettere i due codici fiscali omocodici che dovranno sostituire il provvisorio e la base

**Comment by rvinzani** [comment]
Chiudo la issue. Rimaniamo a disposizione per ogni ulteriore chiarimento
