### ISSUE TITLE
UPLOAD del File AIRE in ANPR TEST

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#25]
Salve,
abbiamo riscontrato che quando facciamo l'upload del File AIRE i del COMUNE di BOLOGNA, in Ambiente di TEST di ANPR,  nel subentro, su alcuni pc , ci da'  questo errore : Il formato del file decompresso non è XML valido. Da un pc di un collega lo stesso file viene caricato senza problemi.
Ci sono caratteristiche particolari del computer  per poter effettuare l'upload?

Grazie
Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

 
L' errore in realta' e' : Il formato del file decompresso non è TXT valido

**Comment by gcarbonin** [comment]
Chiuso per assenza di riscontro da parte del comune
