### ISSUE TITLE
Fusione di due Comuni

### ISSUE THREAD

**Issue by PaDigitaleSpa** [italia/anpr#250]
Al referendum consultivo del prossimo 22 Ottobre, gli elettori di due Amministrazioni Lombarde saranno chiamati a esprimersi anche sulla possibile fusione dei loro Comuni di residenza. 
Nel caso vincessero i Sì entro la fine dell'anno di due Comuni ne rimarrebbe solo uno. 

Le attività anagrafiche in carico agli uffici per gestire una fusione sono molte. 
Tra queste si ricorda:
- Ridenominazione delle vie aventi stessa denominazione (qualora nei due comuni fossero presenti vie con medesima descrizione) 
- Cambi di residenza d'ufficio (a seguito del cambio toponomastica sopraccitato)
- Attribuzione di nuovi codici di famiglia nel caso fossero presenti gli stessi numeri famiglia attribuiti dai due precedenti Comuni
- Rinumerazione del codice individuale nel caso fossero presenti gli stessi numeri individuali attribuiti dai due precedenti Comuni
ecc...

Come verrebbe gestita in ANPR una fusione nel caso solo uno dei due Comuni fosse subentrato?
E nel caso fossero entrambi subentrati, come sarebbero gestite le casistiche sopradescritte?
Grazie

Licari - Pa Digitale Spa

**Comment by gcarbonin** [comment]
Nel caso in cui uno soltanto dei due comuni fosse subentrato, occorrerà prevedere il subentro urgente anche del secondo.
Per le variazioni della toponomastica, è allo studio una soluzione (vedi il forum).
Gli identificativi di ANPR (famiglia e persone) non devono essere modificati; sarebbe utile che i SW gestionali iniziassero a lavorare con questi identificativi proprio perché non si modificano. In ogni caso l'attribuzione dei nuovi identificativi comunali è a carico del comune. Prevediamo soltanto che il nuovo comune (risultante dalla fusione) possa aggiornare ANPR (in modo massivo) per acquisire i nuovi valori.

**Comment by gcarbonin** [comment]
Mi può dare un riscontro?

**Comment by PaDigitaleSpa** [comment]
Il processo di subentro del primo Comune è avviato da diversi mesi ed il passaggio definitivo in Anpr è programmato prima del Referendum del mese di ottobre.
Se la consultazione elettorale del 22/10 si esprimerà favorevolmente alla fusione dei due Comuni, come suggerito, si procederà ad un subentro urgente anche del secondo Comune fiduciosi che nel frattempo le specifiche per le variazioni della toponomastica, oggi in fase di studio, siano state realizzate.

**Comment by bfilipazzi** [comment]
La fusione comporta una variazione delle anagrafiche in ANPR? penso a un intervento che modifica il loro comune di appartenenza a decorrere dal giorno di istituzione del nuovo ente. Dalla risposta dipendono le iniziative che dovremo prendere nei db locali per disporre della stessa informazione.
Filipazzi - Maggioli

**Comment by patriziasaggini** [comment]
Il TU 267/2000 (art. 16) prevede che "Nei comuni istituiti mediante fusione di due o piu' comuni contigui lo statuto comunale puo' prevedere l'istituzione di municipi nei territori delle comunita' di origine o di alcune di esse."
Quindi, dopo la fusione dovrà essere obbligatoriamente gestito il dato del "Municipio" di appartenenza (se previsto dallo Statuto); ciò è utile anche per gestire i casi di denominazioni uguali di vie, che potranno anche non essere cambiate, ma essere associate allo specifico Municipio.
