### ISSUE TITLE
ALLINEAMENTO CODICE FISCALE

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2500]
Buon giorno
Segnalo quanto segue: 
1° Codice fiscale da variare/collegare presente sia in A.E. che in ANPR = DLLMDA96A01ZP43E
2° Codice fiscale ESATTO presente solo in A.E. = DLLMDA84B05Z343Q
Bisogna collegare I DUE CODICI FISCASCALI confermando i dati dell'agenzia delle entrate.
Errori risposta:
Esito ANPR: Variazione non consentita per superamento numero campi variati (Codice: EAM93) 
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-16 12:52:59 , idOperazioneANPR 455469391 (Codice: EN527) 
Cordiali saluti
Filippo Asaro
0923993382

**Comment by frmariani** [comment]
Come comunicato per le vie brevi, in questo caso il collegamento dei codici fiscali deve essere effettuato dalla Direzione Centrale di Agenzia delle Entrate dopo la verifica della documentazione pervenuta.
Gentilmente cerchiamo di non indicare CF in chiaro, grazie.
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
