### ISSUE TITLE
IMMIGRAZIONE RIF  #2493

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2501]
OK esauriente. Quesito che mi è stato posto:
A seguito delle movimentazioni viste con  issue #2493 Il comune di emigrazione riceve una notifica N010 per provvedere alla cancellazione (non più PEC).
Nel caso dovesse verificare una emigrazione errata il comune di immigrazione provvede ad annullare la residenza e ripristinare  la precedente.
CORRETTO?

**Comment by rvinzani** [comment]
Corretto, riceve la notifica N015 di ripristino

**Comment by rinonasti** [comment]
Perfetto Grazie
Chiedo troppo avere una notifica N010 e una N015 sull'area di pre-subentro per verificare quando il servizio 4005 le richiama e li manda in "PASTO" al software applicativo.

**Comment by rvinzani** [comment]
inviati via email due esempi. chiudo la issue
