### ISSUE TITLE
Tempi rilascio password smart card sindaco

### ISSUE THREAD

**Issue by imergemd** [italia/anpr#2502]
In seguito al ricevimento della nuova smart card del Sindaco e nonostante numerosi solleciti a partire dal 05/02/2021 presso il centro di assistenza, la e-mail con la seconda parte di PIN/PUK non è ancora arrivata. Come è possibile seguire l'iter della richiesta per individuare e risolvere il problema?
Grazie.

Mauro Dorici x Comune di Lallio

**Comment by Leonforte** [comment]
La seconda parte delle credenziali è stata inviata a : sara.peruzzini@comune.lallio.bg.it

Buon lavoro, saluti

**Comment by imergemd** [comment]
Grazie!
