### ISSUE TITLE
metadati su aggiornamento popolazione per comune

### ISSUE THREAD

**Issue by napo** [italia/anpr#2503]
Guardando il file json che si raggiunge qui
https://dashboard.anpr.it/api/dashboard/data.json
per ciascun comune riportato nella sezione geojson si hanno la proprietà _popolazione_ e _popolazione_aire_.
Non trovo la data dell'ultimo aggiornamento: fanno riferimento al censimento nazionale ISTAT? A quello comunale con cadenza ogni X? O si può assumere che fa riferimento al valore _last_update_ presente nell'ultima riga del json ed espresso in timestamp?
Grazie

**Comment by amollicone1982** [comment]
Per i comuni subentrati i valori sono presi da ANPR e sono aggiornati alla datalast_update. Per i comuni non subentrati si fa riferimento al censimento ISTAT

**Comment by napo** [comment]
censimento ISTAT a che data?
Quella che trovo su https://demo.istat.it ?
Grazie
