### ISSUE TITLE
[ EN493 ] Codice errore in richiesta al wsdl 6001

### ISSUE THREAD

**Issue by matteo-mulas** [italia/anpr#2504]
Buongiorno. Stiamo cercando di richiamare in ambiente di test il wsdl 6001servizioCertificazione per recuperare i certificati anagrafici. Otteniamo l'errore EN493 con indicazione "La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione  sul soggetto/famiglia" per ogni tipo di certificato. 

Potete controllare se c'è qualcosa di sbagliato nella busta soap di richiesta?
Restiamo in attesa di un cortese riscontro.

Ecco un esempio di richiesta.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soap:mustUnderstand="1">
            <wsu:Timestamp wsu:Id="TS-7371bb52-bc7d-4345-8fdb-1e35ff779d0f">
                <wsu:Created>2021-02-18T08:22:49.985Z</wsu:Created>
                <wsu:Expires>2021-02-18T08:27:49.985Z</wsu:Expires>
            </wsu:Timestamp>
            <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="_1ef8dc90-9e6b-4a65-b766-221dca777b8e" IssueInstant="2021-02-18T08:22:49.878Z" Version="2.0" xsi:type="saml2:AssertionType">
                <saml2:Issuer>XS</saml2:Issuer>
                <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                    <ds:SignedInfo>
                        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                        <ds:Reference URI="#_1ef8dc90-9e6b-4a65-b766-221dca777b8e">
                            <ds:Transforms>
                                <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                                <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                                    <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xsd"/>
                                </ds:Transform>
                            </ds:Transforms>
                            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                            <ds:DigestValue>qne7Ed6U+jUTDXKT+TUR+THY6XY=</ds:DigestValue>
                        </ds:Reference>
                    </ds:SignedInfo>
                    <ds:SignatureValue>Z3w9NxDXl3amQKDxdbwOy7u2M8PT2g8EFXVOUEtUlCePmEgbdFsJhw2MTBMIypCpWzlG5ezrOTPvZA8NhuOOMACH3i4+gnE+30Ba8eaOZEAwdrKi9eHjkNOm4N2BXReA0OGbI9juplxbTUVMM0YaLfX7coO435us5xu0cOKPiH4JQGoHMfsgJhTLHTEiv20KAXZNMcddP25E1NbRGx+377T38RstPX4b4+SLt3BcHJGgAqeCAj8/5Lit/M/uq7/J6PMyoTsK3fPKYchveAAYkTxvxFDVZWntEQdnU6jrqZydwa7wR98zMJ0F4du1GuVaFC3ZgFqX7yBd91AZ3hKRWA==</ds:SignatureValue>
                    <ds:KeyInfo>
                        <ds:X509Data>
                            <ds:X509Certificate>MIIE6zCCAtOgAwIBAgIIFIyGSJ9S7SgwDQYJKoZIhvcNAQELBQAwWjEbMBkGA1UEAwwSQ0EgUG9z
dGF6aW9uaSBTdmlsMQ0wCwYDVQQLDARBTlBSMR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbCdJbnRl
cm5vMQswCQYDVQQGEwJJVDAeFw0xOTAzMjAwOTE3MzdaFw0yNTAzMjAwOTE3MzdaMIGZMRcwFQYD
VQQDDA44ODgyMzEtQ08tMDAwMDEdMBsGA1UECwwUUG9zdGF6aW9uaSBkaSBsYXZvcm8xMTAvBgNV
BAsMKEFuYWdyYWZlIE5hemlvbmFsZSBQb3BvbGF6aW9uZSBSZXNpZGVudGUxHzAdBgNVBAoMFk1p
bmlzdGVybyBkZWxsJ0ludGVybm8xCzAJBgNVBAYTAklUMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAuekYNM+ciMh/dud8wfV2zxx9lb1BN+ZwtxhSbR9IS2n/JJ7hxelz2a5moVvaMGMB
Ryaimixrzyh5ni5UwI1E/JCdQ+eyytztyLMKxaVA2vNgDQIgrc0SIGTvPlV6lXpVhmCdTSShN1uq
zuC4ELCEY07BGoHhfN2iwey9wWoPcfLmPKXRgP/ulcfVIxWzDxw3uYJr5Mgx+tqkznA39o3LWkAZ
1+HUH6N0uAbfYO4zfVC4pXhT0Dy402GjzlZbzwP5NpamAbPIOw/5yCPWqMb14LlgYBr8ev7yde44
lMBHtSFoZ6c+ny2nd6wnwRxMsPtx5HuO4N1XvPCli4CtvQXSnwIDAQABo3UwczAMBgNVHRMBAf8E
AjAAMB8GA1UdIwQYMBaAFAYLn8qh15mt1CLus4uxFJPIV5t+MBMGA1UdJQQMMAoGCCsGAQUFBwMC
MB0GA1UdDgQWBBTKfzl/k9E2es0fa2SSnsRzNQGZ5jAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcN
AQELBQADggIBADU+oRL2D7hhuUVkxuWcRsUdLGBwrL3ZJyKqiiVD2vTMy3KFQh83Qyrp5vUv32Tt
VmAS1S/0bbCoAEk00Vv5iqAMPUIyWKkWogMXqIRSvRZW9Ahlh6Ub2f0WTzaxiBNCviUX9marAicl
FH1jj/94PO6z62xAc73A+mK6tMEkUxreVhuVQ2EXDEUbD5LHo4622d/kbDukCnTge1jBHuV/ICSn
6DF5jYtDTbmdquCI4mEV1UP/otUZfFAUcweQM4OuzdS85Suc7e9Lx60ovpXgV5MWOVd/hepaShwt
Ym/6wRsbmUGBhwF540ql3m5DOn38yFgnTKwHNe5NwLnJbwrHJStKokxIaOzS+Al4oY50LoD2ADrN
TiLvOLD9Wj/FXzXXto2aoEUpSGwDxd1//KF0dC639nWFO0qliBaj492bDD2vVPWX8Rusm/KoBYzt
SupsOQ4/X2aqscvEqL9i5jULswJ178TPkwPURPrSWaNKYqfWZiZ5Y2CPITGdEX8jlBsOOpSHwUR3
x8TmkgrNzuusGbd3mtXmabBX/GifK7RYWV4LrOuA1WPjGSCjQZMiW7gG8n0IO7QubS+Adergliqv
tmuYqmgWT7JQpmxhBbh1LIz5qaf0bcsAf8RhRnXwODo319QB8CnLdO/k6H4wVFebDj1p3Bo7fHms
DgmxCq1vAY1Q</ds:X509Certificate>
                        </ds:X509Data>
                    </ds:KeyInfo>
                </ds:Signature>
                <saml2:Subject>
                    <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">USERSFREETEST231</saml2:NameID>
                    <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                        <saml2:SubjectConfirmationData NotBefore="2021-02-18T08:22:48.518Z" NotOnOrAfter="2021-02-18T08:27:48.518Z"/>
                    </saml2:SubjectConfirmation>
                </saml2:Subject>
                <saml2:Conditions NotBefore="2021-02-18T08:22:49.886Z" NotOnOrAfter="2021-02-18T08:27:49.886Z"/>
                <saml2:AuthnStatement AuthnInstant="2021-02-18T08:22:48.518Z" SessionNotOnOrAfter="2021-02-18T08:27:48.518Z">
                    <saml2:SubjectLocality Address="192.168.177.12"/>
                    <saml2:AuthnContext>
                        <saml2:AuthnContextClassRef/>
                    </saml2:AuthnContext>
                </saml2:AuthnStatement>
                <saml2:AttributeStatement>
                    <saml2:Attribute Name="IdSede" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
                        <saml2:AttributeValue xsi:type="xsd:string">888231</saml2:AttributeValue>
                    </saml2:Attribute>
                    <saml2:Attribute Name="IdPostazione" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
                        <saml2:AttributeValue xsi:type="xsd:string">888231-CO-0000</saml2:AttributeValue>
                    </saml2:Attribute>
                    <saml2:Attribute Name="IdPostazioneFirmato" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
                        <saml2:AttributeValue xsi:type="xsd:string">MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwGggCSABA44ODgyMzEtQ08tMDAwMAAAAAAAAKCAMIIE6zCCAtOgAwIBAgIIFIyGSJ9S7SgwDQYJKoZIhvcNAQELBQAwWjEbMBkGA1UEAwwSQ0EgUG9zdGF6aW9uaSBTdmlsMQ0wCwYDVQQLDARBTlBSMR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbCdJbnRlcm5vMQswCQYDVQQGEwJJVDAeFw0xOTAzMjAwOTE3MzdaFw0yNTAzMjAwOTE3MzdaMIGZMRcwFQYDVQQDDA44ODgyMzEtQ08tMDAwMDEdMBsGA1UECwwUUG9zdGF6aW9uaSBkaSBsYXZvcm8xMTAvBgNVBAsMKEFuYWdyYWZlIE5hemlvbmFsZSBQb3BvbGF6aW9uZSBSZXNpZGVudGUxHzAdBgNVBAoMFk1pbmlzdGVybyBkZWxsJ0ludGVybm8xCzAJBgNVBAYTAklUMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuekYNM+ciMh/dud8wfV2zxx9lb1BN+ZwtxhSbR9IS2n/JJ7hxelz2a5moVvaMGMBRyaimixrzyh5ni5UwI1E/JCdQ+eyytztyLMKxaVA2vNgDQIgrc0SIGTvPlV6lXpVhmCdTSShN1uqzuC4ELCEY07BGoHhfN2iwey9wWoPcfLmPKXRgP/ulcfVIxWzDxw3uYJr5Mgx+tqkznA39o3LWkAZ1+HUH6N0uAbfYO4zfVC4pXhT0Dy402GjzlZbzwP5NpamAbPIOw/5yCPWqMb14LlgYBr8ev7yde44lMBHtSFoZ6c+ny2nd6wnwRxMsPtx5HuO4N1XvPCli4CtvQXSnwIDAQABo3UwczAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFAYLn8qh15mt1CLus4uxFJPIV5t+MBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBTKfzl/k9E2es0fa2SSnsRzNQGZ5jAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBADU+oRL2D7hhuUVkxuWcRsUdLGBwrL3ZJyKqiiVD2vTMy3KFQh83Qyrp5vUv32TtVmAS1S/0bbCoAEk00Vv5iqAMPUIyWKkWogMXqIRSvRZW9Ahlh6Ub2f0WTzaxiBNCviUX9marAiclFH1jj/94PO6z62xAc73A+mK6tMEkUxreVhuVQ2EXDEUbD5LHo4622d/kbDukCnTge1jBHuV/ICSn6DF5jYtDTbmdquCI4mEV1UP/otUZfFAUcweQM4OuzdS85Suc7e9Lx60ovpXgV5MWOVd/hepaShwtYm/6wRsbmUGBhwF540ql3m5DOn38yFgnTKwHNe5NwLnJbwrHJStKokxIaOzS+Al4oY50LoD2ADrNTiLvOLD9Wj/FXzXXto2aoEUpSGwDxd1//KF0dC639nWFO0qliBaj492bDD2vVPWX8Rusm/KoBYztSupsOQ4/X2aqscvEqL9i5jULswJ178TPkwPURPrSWaNKYqfWZiZ5Y2CPITGdEX8jlBsOOpSHwUR3x8TmkgrNzuusGbd3mtXmabBX/GifK7RYWV4LrOuA1WPjGSCjQZMiW7gG8n0IO7QubS+AdergliqvtmuYqmgWT7JQpmxhBbh1LIz5qaf0bcsAf8RhRnXwODo319QB8CnLdO/k6H4wVFebDj1p3Bo7fHmsDgmxCq1vAY1QAAAxggIsMIICKAIBATBmMFoxGzAZBgNVBAMMEkNBIFBvc3RhemlvbmkgU3ZpbDENMAsGA1UECwwEQU5QUjEfMB0GA1UECgwWTWluaXN0ZXJvIGRlbGwnSW50ZXJubzELMAkGA1UEBhMCSVQCCBSMhkifUu0oMA0GCWCGSAFlAwQCAQUAoIGYMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIxMDIxODA4MjI0OFowLQYJKoZIhvcNAQk0MSAwHjANBglghkgBZQMEAgEFAKENBgkqhkiG9w0BAQsFADAvBgkqhkiG9w0BCQQxIgQgzYIHMdeYL4kpOz8yfBNeL0vAVivJtwlg7MrZJU/o3zUwDQYJKoZIhvcNAQELBQAEggEAZv5fsarBFZGS/LEYM4M81bxKiguLNQ7Zj/Pei2vP4N4cIc/EtMw0CejKGc53voq48XqYSkfkZPggZVr/4sTp0PXZZsM50zPCV8Oop2kMXsGPXUDX/md3LkXXaiGxZAAZbXXOEM0T5m51N7+nFjBNmBvoxbRxacntw8CvpZMIFxlYdFiXwcXIGmLPLCeQeQBMSKvkXDONbmBf1aQyyKAFjdBC9CFdCL9bRfS0tI2Ems1P9L16UWDqPrWFMNQXJ2cM0evMs4gea5Y01fqPLNgThrgKLjo8I8FEwo/QqbBuWs9FgLvi8cybmPowSeHQ32FuqW93/Xx5jTKHVjeRvcbDAAAAAAAAAA==</saml2:AttributeValue>
                    </saml2:Attribute>
                    <saml2:Attribute Name="IdApplicazione" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
                        <saml2:AttributeValue xsi:type="xsd:string">12345</saml2:AttributeValue>
                    </saml2:Attribute>
                </saml2:AttributeStatement>
            </saml2:Assertion>
            <wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="X509-d6bfb594-dea5-41a8-9f82-d2121ea94ddd">MIIE6zCCAtOgAwIBAgIIFIyGSJ9S7SgwDQYJKoZIhvcNAQELBQAwWjEbMBkGA1UEAwwSQ0EgUG9zdGF6aW9uaSBTdmlsMQ0wCwYDVQQLDARBTlBSMR8wHQYDVQQKDBZNaW5pc3Rlcm8gZGVsbCdJbnRlcm5vMQswCQYDVQQGEwJJVDAeFw0xOTAzMjAwOTE3MzdaFw0yNTAzMjAwOTE3MzdaMIGZMRcwFQYDVQQDDA44ODgyMzEtQ08tMDAwMDEdMBsGA1UECwwUUG9zdGF6aW9uaSBkaSBsYXZvcm8xMTAvBgNVBAsMKEFuYWdyYWZlIE5hemlvbmFsZSBQb3BvbGF6aW9uZSBSZXNpZGVudGUxHzAdBgNVBAoMFk1pbmlzdGVybyBkZWxsJ0ludGVybm8xCzAJBgNVBAYTAklUMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuekYNM+ciMh/dud8wfV2zxx9lb1BN+ZwtxhSbR9IS2n/JJ7hxelz2a5moVvaMGMBRyaimixrzyh5ni5UwI1E/JCdQ+eyytztyLMKxaVA2vNgDQIgrc0SIGTvPlV6lXpVhmCdTSShN1uqzuC4ELCEY07BGoHhfN2iwey9wWoPcfLmPKXRgP/ulcfVIxWzDxw3uYJr5Mgx+tqkznA39o3LWkAZ1+HUH6N0uAbfYO4zfVC4pXhT0Dy402GjzlZbzwP5NpamAbPIOw/5yCPWqMb14LlgYBr8ev7yde44lMBHtSFoZ6c+ny2nd6wnwRxMsPtx5HuO4N1XvPCli4CtvQXSnwIDAQABo3UwczAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFAYLn8qh15mt1CLus4uxFJPIV5t+MBMGA1UdJQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBTKfzl/k9E2es0fa2SSnsRzNQGZ5jAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBADU+oRL2D7hhuUVkxuWcRsUdLGBwrL3ZJyKqiiVD2vTMy3KFQh83Qyrp5vUv32TtVmAS1S/0bbCoAEk00Vv5iqAMPUIyWKkWogMXqIRSvRZW9Ahlh6Ub2f0WTzaxiBNCviUX9marAiclFH1jj/94PO6z62xAc73A+mK6tMEkUxreVhuVQ2EXDEUbD5LHo4622d/kbDukCnTge1jBHuV/ICSn6DF5jYtDTbmdquCI4mEV1UP/otUZfFAUcweQM4OuzdS85Suc7e9Lx60ovpXgV5MWOVd/hepaShwtYm/6wRsbmUGBhwF540ql3m5DOn38yFgnTKwHNe5NwLnJbwrHJStKokxIaOzS+Al4oY50LoD2ADrNTiLvOLD9Wj/FXzXXto2aoEUpSGwDxd1//KF0dC639nWFO0qliBaj492bDD2vVPWX8Rusm/KoBYztSupsOQ4/X2aqscvEqL9i5jULswJ178TPkwPURPrSWaNKYqfWZiZ5Y2CPITGdEX8jlBsOOpSHwUR3x8TmkgrNzuusGbd3mtXmabBX/GifK7RYWV4LrOuA1WPjGSCjQZMiW7gG8n0IO7QubS+AdergliqvtmuYqmgWT7JQpmxhBbh1LIz5qaf0bcsAf8RhRnXwODo319QB8CnLdO/k6H4wVFebDj1p3Bo7fHmsDgmxCq1vAY1Q</wsse:BinarySecurityToken>
            <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="SIG-fb23cee1-e2d6-4e70-81d2-784121f432b0">
                <ds:SignedInfo>
                    <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/>
                    </ds:CanonicalizationMethod>
                    <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                    <ds:Reference URI="#TS-7371bb52-bc7d-4345-8fdb-1e35ff779d0f">
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="wsse soap"/>
                            </ds:Transform>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                        <ds:DigestValue>jqAfCjsJ5TD2MJHlZXZXv/UIGrY=</ds:DigestValue>
                    </ds:Reference>
                    <ds:Reference URI="#_ec449818-1695-47ec-a5e0-955c29de8797">
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                        <ds:DigestValue>6ZeieoDGAeKdALsDXfA9T1ytu6w=</ds:DigestValue>
                    </ds:Reference>
                </ds:SignedInfo>
                <ds:SignatureValue>cOaD8FBodNn2GBwO5PgShj0b+JIdBDOMH1z5jephdH5HqDrq1bkfM5nmHeprs318XgdvVlKTVbfQHS6AVBlLJKgYAoI48tP8CKfgetYHlBB2zyx58DAo6IDbw1c7hyNIlutkvzBctz+aNsswtUXXRpNEiIOvb7H/uQe2eVF9o9QJCHwacMG57X9dfUqf7txyM2Lqzgk/Q7h6p0bnUFxvgJF+HCB+g2EROA1NcAUOPkdt+9j5SUaAeDRLrinsIqn+kNbajdrepU5YVxcfzqGL/b/k2v14D03J8zs2U6mAwIrC3aO4kt/mjuQFSPnMBZ0Ia+SWanRSs/0qSOmrb9dZHA==</ds:SignatureValue>
                <ds:KeyInfo Id="KI-6f90fcc9-52df-4ee2-a9ac-0fd05a5bc058">
                    <wsse:SecurityTokenReference wsu:Id="STR-27976c07-c63a-420f-ae52-2ad9b606bb73">
                        <wsse:Reference URI="#X509-d6bfb594-dea5-41a8-9f82-d2121ea94ddd" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>
                    </wsse:SecurityTokenReference>
                </ds:KeyInfo>
            </ds:Signature>
        </wsse:Security>
    </soap:Header>
    <soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="_ec449818-1695-47ec-a5e0-955c29de8797">
        <ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
            <testataRichiesta>
                <idOperazioneComune>9999992</idOperazioneComune>
                <codMittente>888231</codMittente>
                <codDestinatario>ANPR00</codDestinatario>
                <operazioneRichiesta>6001</operazioneRichiesta>
                <dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
                <tipoOperazione>C</tipoOperazione>
                <tipoInvio>FREE</tipoInvio>
                <dataDefinizionePratica>2018-05-29</dataDefinizionePratica>
            </testataRichiesta>
            <listaTipiCertificati>
                <tipoCertificato>5</tipoCertificato>
            </listaTipiCertificati>
            <soggettoIntestatario>
                <generalita>
                    <codiceFiscale>
                        <codFiscale>XXXXXXXXXXXXXXX</codFiscale>
                    </codiceFiscale>
                    <cognome>MULAS</cognome>
                    <nome>MATTEO</nome>
                </generalita>
            </soggettoIntestatario>
            <datiControllo>
                <cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
                <nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
                <tipoRichiedente>1</tipoRichiedente>
                <tipoRichiesta>1</tipoRichiesta>
                <paEstera>0</paEstera>
                <emissione>1</emissione>
                <bollo>2</bollo>
                <diritti>2</diritti>
            </datiControllo>
        </ns2:Richiesta6001>
    </soap:Body>
</soap:Envelope>

**Comment by mttfranci** [comment]
Buongiorno, il codice EN493 è una risposta applicativa, quindi la richiesta è ben formata.
In questo caso il problema sembrerebbe essere solo (come dice una delle opzioni del diagnostico) che il soggetto intestatario (MATTEO MULAS) non è presente in questo ambiate.
Dovreste provare con un soggetto esistente.
(In generale se da una consultazione non trovate un soggetto non potete neanche emettere un certificato).
Saluti
