### ISSUE TITLE
RIPRISTINO POSIZIONE ANAGRAFICA ANTE SUBENTRO

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2505]
Famiglia composta da 3 persone emigra dal Comune di Castellammare di Stabia in un Comune B subentrato prima del nostro subentro. Il Comune B procede all'scrizione per altri motivi.  Dopo il nostro subentro c'è l'accertamento negativo e quindi la richiesta di ripristino della posizione anagrafica precedente da parte del Comune B che ha effettuato la cancellazione per altri motivi. A noi arriva notifica N014 per solo due dei tre componenti regolarmente riportati dal Comune B nell'APR4 di richiesta di cancellazione. Effettuando una consultazione in ANPR sia ricercando per nome cognome e data di nascita che per cf solo due dei tre soggetti risultano in ANPR in stato cancellato, l'altro soggetto pare non sia mai stato iscritto. 
Per ovviare al ripristino bisogna procedere all'iscrizione per altri motivi dei due soggetti facendo riferimento al vecchio id. Come motivazione si indica la n.10 (Ripristino posizione precedente) della tabella di riferimento n.7 "Motivi di iscrizione in Anagrafe"? Oppure la n.3 essendo gli stessi immigrati da un Comune ancora oggi non subentrato?
E per il soggetto che erroneamente non è mai stato iscritto in ANPR bisogna procedere all'iscrizione indicando come motivazione la n.10 oppure la n. 1 (essendo lo stesso iscritto nella nostra anagrafe per nascita prima del nostro subentro)?
Conza Gianpaolo
Comune di Castellammare di Stabia
Ambiente Produzione

**Comment by frmariani** [comment]
Mi scusi ma non mi è chiara la domanda; mi sembrava di aver capito che il comune B fosse subentrato, poi però nella domanda mi chiede se la motivazione corretta sia "Ripristino posizione precedente" o "Immigrazione da comune non subentrato" 
_Oppure la n.3 essendo gli stessi immigrati da un Comune ancora oggi non subentrato?_

Gentilmente mi indichi gli idanpr dei soggetti così potrò essere più chiara; 
nel caso mi invii anche un suo recapito telefonico al seguente indirizzo
frmariani@sogei.it

**Comment by gianpaol** [comment]
Ha capito bene, il comune B è subentrato però io mi riferivo al fatto che i due cittadini nel 2019 erano immigrati da un comune C che ancora oggi non è subentrato. Pertanto mi chiedevo se dovessi indicare come motivo d'iscrizione il nr. 3 o il nr. 10. Per quanto riguarda l'altro cittadino, che non è mai stato iscritto, devo procedere ad un'iscrizione per nascita o facendo riferimento alla  motivazione nr.10? oppure l'altro Comune B deve ovviare alla mancata iscrizione oggi per allora?
id anpr 92308057; id anpr 92308062

**Comment by frmariani** [comment]
Mi scusi ma le sue domande mi sembrano più amministrative che tecniche; comunque, considerando che il comune B avrebbe dovuto annullare le iscrizioni, direi  che Lei li debba iscrivere per Immigrazione da comune NON subentrato; in merito al cittadino mai iscritto, credo che Lei possa procedere con un'iscrizione per nascita o iscrizione per altri motivi.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
