### ISSUE TITLE
WS5001 - CAMBIO DOMICILIO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2506]
Comune Caserta 061022
Buonasera,
Nel caso di comunicazione di cambio di domicilio di un intero nucleo come vanno indicati, nel caso fossero variati,  il possesso di patente e veicoli per singolo componente?
Grazie

**Comment by azabatta** [comment]
Buonasera, 
per la fattispecie indicata  (ws 5001) è possibile utilizzare  il codice mutazione 5 che prevede la comunicazione della sezione "autovecioli" per ogni componente del nucleo familiare.

**Comment by rinonasti** [comment]
se indico mutazione 5 autoveicoli/patente vanno indicate per tutti o per solo quelli di cui si dispone l'informazione?

**Comment by azabatta** [comment]
Solo per quelli per cui si dispone delle informazioni (o per i quali è necessario aggiornarle), la sezione "autoveicoli" è opzionale.
