### ISSUE TITLE
[5001] convivenze vuote e cambio di indirizzo

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2507]
Ambiente di produzione, comune di Gonzaga.

Nella realtà esiste una convivenza vuota, con indirizzo VIA FERRANTE GONZAGA 26, nelal quale il responsabile non abita, risiedendo infatti in altra famiglia in VIA FERRANTE GONZAGA 24.
Il comune oggi deve iscrivere un soggetto in tale convivenza.
Cercandola in ANPR con il servizio 3002 ci viene restituito un oggetto "datiFamigliaConvivenza" privo del tag residenza, mentre tra i soggetti ritornati c'è il responsabile nella cui residenza si trova l'indirizzo della convivenza.
Il nostro software interpreta questo dato come "convivenza priva di indirizzo" e cerca di valorizzarlo con la chiamata 5001 ID ANPR 461843116 che però va in errore "EN388 La residenza inserita risulta uguale a quella attuale".

La domanda è: quanto restituito dal 3002 sulla convivenza è corretto ? Non dovremmo avere l'indirizzo della convivenza VIA FERRANTE GONZAGA 26 nel tag datiFamigliaConvivenza->residenza e invece l'indirizzo di residenza del responsabile  VIA FERRANTE GONZAGA 24 nel relativo oggetto datiSoggetto->residenza ?

**Comment by rvinzani** [comment]
Ho fatto una consultazione che allego e mi sembra che nell'indirizzo ci sia via Gonzaga 26

**Comment by rvinzani** [comment]
[21563619.txt](https://github.com/italia/anpr/files/6023041/21563619.txt)

**Comment by busaster** [comment]
MI verrebbe da interpretare il tag "residenza" come la residenza del soggetto è cui è collegato (il responsabile), cosa che non è in quanto il responsabile risiede altrove.
MI chiedevo se questo fosse corretto e invece non fosse più corretto trovare la residenza in un tag "datiFamigliaConvivenza"->"residenza"

**Comment by rvinzani** [comment]
E' stata fatta una scelta ormai tempo fa a cui tutti si sono adeguati e cambiarla sebbene condivisibile, comporterebbe probabilmente maggiori disagi. Chiudo la issue. In caso fossero necessarie maggiori informazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
