### ISSUE TITLE
Operazione sospesa per il soggetto

### ISSUE THREAD

**Issue by COMUNESANGIOVANNIVALDARNO** [italia/anpr#2508]
Comune di San Giovanni Valdarno (AR) - Anagrafe - Ambiente produzione

Non riusciamo a registrare una mutazione di residenza verso il ns. Comune, poiché viene segnalata l'esistenza di un'operazione sospesa in relazione alla persona interessata (presumiamo del Comune che ha attualmente in carico il soggetto).

idSchedaSoggettoANPR: 90181364

Vi saremmo grati se riusciste ad individuare l'operazione ed a risolverla insieme al Comune competente a riguardo.

Cordiali saluti, Mancini.

**Comment by ncapozzi** [comment]
Buonasera,
domani mattina contatteremo l'altro comune interessato

**Comment by ncapozzi** [comment]
Buongiorno,
il comune attualmente competente ha cancellato l'operazione sospesa. Potete procedere con il cambio di residenza.

N. Capozzi
