### ISSUE TITLE
Procedimento aperto comune di MILANO

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2509]
Buongiorno,
Comune di Martellago, ambiente di produzione.
Ticket già aperto con Assistenza Sogei n.  22348327
Segnalazione del tutto simile alla issue #2403 
EN531 Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune MILANO (MI) con numero pratica ANPR: 6099251

Il Comune di Martellago ha già inoltrato 4 PEC al Comune al Milano, senza aver riscontro.
Cortesemente, è possibile da parte vostra sollecitare il Comune?

Si segnala, inoltre, che il Comune di Martellago ha ricevuto una mail con n. ticket (21122495) e riferimenti errati

Resto in attesa di un gradito riscontro
Cordiali Saluti

**Comment by rvinzani** [comment]
Abbiamo inviato email al comune di Milano con le istruzioni per la chiusura del procedimento.
Per quanto riguarda il ticket 21122495, mi sembra sia stata indicata una data apertura procedimento inesatta ma che comunque non è rilevante ai fini della segnalazione. Nel caso non fosse così vi prego di aprire una nuova issue che faccia riferimento a questa
