### ISSUE TITLE
POSIZIONI DUPLICATE

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#2510]
COMUNE DI VALDILANA - BIELLA - 096088

Dalla scheda ANOMALIE nella webapp apprendo di avere n. 6 posizioni duplicati con altri Comuni.
In effetti 2 posizioni le ho trovate casualmente nel tentativo di emettere due certificazioni che mi sono state richieste dai cittadini.
Per questi ho contattato l'altro comune interessato e spero di poter risolvere la cosa contando sulla collaborazione dei colleghi.
Ho provato pero' a richiedere la stampa delle posizioni dupliicate (sia precedenti che successive) ma ottengo la risposta "nessun file presente", risposta sicuramente non esatta dal momento che non vengono riportate nemmeno le due posizioni certamente duplicate  cod. anpr  19026323/94972915  e 19026324/94959621
Mi potete spiegare dove trovo le altre 4 posizioni?
Ringrazio in anticipo

**Comment by frmariani** [comment]
Purtroppo il vostro file delle posizioni duplicate non è più disponibile;
Comunque delle 6 posizioni  sono rimaste soltanto quelle indicate da Lei; le altre posizione sono state  sanate dagli altri comuni.
Ci scusiamo per il disagio e mi faccia sapere se sono sufficienti le indicazioni riportate

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
