### ISSUE TITLE
Codificazione per Taiwan

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2511]
gentilissimi,
abbiamo avuto una segnalazione dalla rappresentanza consolare italiana a Taiwan circa la codificazione dei luoghi di nascita che riportano le nostre certificazioni, in particolare le città di TAIWAN sono da noi codificate con
la sigla internazionale CN, il codice catastale Z217 e la denominazione Stato TAIWAN

il consolato invece dice che il codice CN è errato perché fa riferimento a Cina Popolare o Repubblica Popolare di Cina, mentre Taiwan fa parte di Repubblica di Cina –Taiwan

Tuttavia non abbiamo trovato tra le tabelle di decodifica ANPR né in quelle ISTAT una codifica alternativa per Taiwan, che risulti corretta ma che non faccia riferimento alla Repubblica Popolare Cinese (RP) cosa che comporterebbe una mutazione del codice catastale e quindi una modifica del codice fiscale di tutti i nati a Taiwan.

rimaniamo in attesa di riscontro

cordiali saluti

Emma Di Emidio - 0544 485503

**Comment by ncapozzi** [comment]
Buonasera,
la tabella degli stati esteri utilizzata da ANPR non include il codice di due lettere cui lei fa riferimento ma il codice ISO da tre che è diverso così come è diverso il cod. catastale che appare nei codici fiscali
REPUBBLICA POPOLARE CINESE	CHN	Z210
TAIWAN	TWN	Z217

https://www.anpr.interno.it/portale/tabelle-di-riferimento

N. Capozzi
