### ISSUE TITLE
Accesso ANPR cittadini da altro sito

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2512]
Una richiesta dei Comuni, credo non semplice. Nel portale delComune, il cittadino si autentica con SPID, per i servizi online. Si vorrebbe inserire un link (dal sito del Comune) verso il [sito ANPR riservato al cittadino](https://web.anpr.interno.it/InterrogazioneCittadinoANPR/#!/), che permetta di entrare a verificare i propri dati e richiedere autocertificazione, senza che venga richiesto nuovamente l'accesso SPID dal sito www.anpr.interno.it.

**Comment by FilippoPapi** [comment]
buongiorno purtroppo non è difficile ma è impossibile il token spid può essere speso una sola volta quindi non c'è modo di non farli autenticare nuovamente
