### ISSUE TITLE
WS2001 - DECESSO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2513]
Buonasera,
Comune CASERTA 061022
INVIANDO I DATI RELATIVI AL DECESSO VIENE CAMBIATO AUTOMATICAMENTE LO STATO CIVILE AL CONIUGE?

**Comment by frmariani** [comment]
Lo stato civile NON  viene aggiornato; se i coniugi sono "Riconciliati", quindi riconosciti con gli identificativi ANPR, vengono inseriti i dati della Vedovanza al coniuge superstite.

**Comment by rinonasti** [comment]
i dati del coniuge devono essere comunicati nella sezione "ELENCOSOGGETTIFAMIGLIA" del WS2001  ?
altrimenti questo non avviene?

**Comment by frmariani** [comment]
No, non serve inserire alcun dato; sarà il sistema che aggiornerà i dati della vedovanza del coniuge superstite con i dati del decesso del coniuge ma, ripeto, soltanto se il matrimonio risulterà "riconciliato", cioè i coniugi devono essere riconosciuti nel matrimonio con gli identificativi ANPR

**Comment by rinonasti** [comment]
ok grazie

**Comment by rinonasti** [comment]
La modifica dello stato civile del coniuge non avviene in automatico anche per il matrimonio WS5008 ?

**Comment by frmariani** [comment]
No, in questo caso deve essere effettuata l'operazione di mutazione dello stato civile
