### ISSUE TITLE
DATA DECORRENZA FAM/CONV.

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2515]
Buongiorno
COMUNE CASERTA - PRE
Dalla web app non è possibile modificare, dati subentro, la data di decorrenza della famiglia ?
Lo si può fare solo inviando WS5001 indicando solo i dati della famiglia con la nuova data e tipo mutazione 3 ?

**Comment by frmariani** [comment]
cosa intende per data di decorrenza della famiglia ? se intende la data di origine della famiglia, mi dispiace ma non è modificabile.
con il WS 5001 tipo mutazione 3 si modifica il motivo famiglia o la specie convivenza.

**Comment by rinonasti** [comment]
Si intendo data origine della famiglia. Ogni qualvolta viene inviata nelle transazioni WS , dove richiesto, prevale quest'ultima rispetto a quella inviata al subentro?
Quale è la operazione per modificarla definitivamente.
Grazie

**Comment by frmariani** [comment]
ripeto che non può essere modificata ma non è una data determinate

**Comment by rinonasti** [comment]
ok grazie
