### ISSUE TITLE
Accesso SmartCard Sindaco

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2516]
Buongiorno,
Comune di Ariano nel Polesine. Ambiente di produzione.  Entrambe le smarcard sono state emesse dopo maggio 2020.
Due nuove smartcard con istallato driver SafeDive.
Eseguita anche la procedura di attivazione smart card, come descritto nel manuale https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf
La smartcard dell'operatore : 0290020000008897 funziona correttamente.
La smarcard del Sindaco 0290020000008118 restitiusce il seguente errore:
"Connessione sicura non riuscita
Si è verificato un errore durante la connessione a dp2.anpr.interno.it. Un modulo PKCS #11 ha restituito il valore CKR_FUNCTION_FAILED: questo significa che la funzione richiesta non è stata completata. Un nuovo tentativo potrebbe avere esito positivo.
Codice di errore: SEC_ERROR_PKCS11_FUNCTION_FAILED"

Lascio i recapiti dell'ufficio al numero 042671131 (int.2) (lun-sab dalle 9-13) mail: anagrafe@comune.arianonelpolesine.ro.it

Resto in attesa di un gradito riscontro
Cordiali Saluti

**Comment by Leonforte** [comment]
Buongiorno, il test è stato effettuato sullo stesso pc ?

**Comment by fcastellani81** [comment]
Buongiorno, assolutamente sì. E' stato usato anche lo stesso browser (Firefox, con Chrome nè una nè l'altra smartcard funzionava).
grazie

**Comment by Leonforte** [comment]
Ok, abbiamo richiesto una nuova carta che sarà disponibile la prossima settimana presso la Prefettura di competenza, probabilmente il certificato a bordo è corrotto, buon lavoro, saluti

**Comment by fcastellani81** [comment]
Ok, grazie!
Sarà nostra cura configurare la nuova smartcard non appena sarà disponibile. In caso di necessità, farò riferimento a questa issue.

Saluti
