### ISSUE TITLE
Riferimento #2482 Comune di Ulzio / Oulx 

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2517]
Buongiorno,
con riferimento al ticket #2482 Comune di Ulzio / Oulxs abbiamo contattato l'Agenzia delle Entrate la quale però ci comunica di non riuscire a cambiare la denominazione come da voi indicato. I dati sono pertanto ancora disallineati, in ANPR è Ulzio e in AE è Oulx. E' possibile l'allineamento?

Riportiamo di seguito la risposta parziale di AE:

"VISUALIZZAZIONE DIZIONI ALTERNATIVE

Comune o stato estero: OULX      Provincia: TO      Codice catastale: G196

Dizioni trovate : 6
Dizione Provincia Tipo Data istituzione  Data soppressione  
 OULX   TO    0   - Dizione ufficiale  01/01/1001    
 ULZIO   TO    1   - Dizione alternativa / frazione  01/01/1001    
 BEAULARD   TO    2   - Dizione alternativa / frazione  01/01/1984    
 CASTELLO   TO    2   - Dizione alternativa / frazione  01/01/1001    
 GAD   TO    2   - Dizione alternativa / frazione  01/01/1001    
 SAVOULX   TO    2   - Dizione alternativa / frazione  01/01/1984    "

Cordiali saluti,
**Claudia Benedetti  0544 485501 - cbenedetti@comune.ra.it**

**Comment by rvinzani** [comment]
Chiuso come da accordi
