### ISSUE TITLE
Riferimento #2478 Omocodia e impossibilità alla variazione dei dati 

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2518]
ticket 22229207

Abbiamo contattato l'Agenzia delle Entrate che ci suggerisce di chiedere l'annullo del nostro omocodice, perchè non arriverà mai quello definitivo. Chiedendo l'annullo, ritorna l'alfanumerico identico a quello dell'altra persona la quale è stata cancellata per doppia iscrizione. A quel punto, riesco a variare i dati anagrafici in ANPR sul  mio residente pur essendoci in Agenzia delle Entrate due codici fiscali uguali, che si riferiscono a due persone diverse (il nostro e quello di San Vittore Olona)? Inoltre, la Questura ha già assegnato un codice fiscale alfanumerico con i nuovi dati alla persona residente a Ravenna (a cui noi dobbiamo ancora variare i dati in Anagrafe).

Per chiarimenti Claudia Benedetti - 0544 485501 - cbenedetti@comune.ra.it

Grazie,
cordiali saluti.

**Comment by rvinzani** [comment]
Informazione fornita da contatto telefonico. Chiudo la issue rimanendo a disposizione per eventuali chiarimenti
