### ISSUE TITLE
[5005] Problema con data di decorrenza - Errore EF055 o EN389

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#2519]
Ambiente di produzione
idOperazioneANpr: 462521287
Comune: 004089

Otteniamo l'errore EF055 - La data decorrenzaResidenza deve essere uguale alla data decorrenza dell'operazione

Nella data di decorrenza della testata abbiamo messo la data di registrazione, mentre nelle altre due abbiamo messo la data di decorrenza.

Nella documentazione dell'oggetto "TestataRichiesta" per la data dataDecorrenza la definizione è la seguente: "Data di inizio validità dell’operazione di registrazione".
Nella documentazione dell'oggetto "LegameSoggetto" per la data di dataDecorrenza la definizione è la seguente: "La data a partire dalla quale il soggetto appartiene alla famiglia/convivenza".
Nella documentazione dell'oggetto "Residenza" per la data dataDecorrenzaResidenza non ha nessuna definizione e ha come regola che deve essere minore o uguale alla data di richiesta del servizio.

Avevamo provato a mettere la data decorrenza nel campo TestataRichiesta \ dataDecorrenza ma avevamo avuto problemi sugli eventi di stato civile. 

Es. Un individuo immigra da comune non subentrato, successivamente riceviamo dal comune di provenienza i dati del matrimonio/divorzio la cui decorrenza è sicuramente prima dell'iscrizione dell'individuo in ANPR. Se metto la data di decorrenza nel campo TestataRichiesta \ dataDecorrenza ottengo l'errore che la data decorrenza non può essere antecedente la data di iscrizione in ANPR.

Otteniamo l'errore EN389
La data decorrenza 01-01-1995 dell'operazione non puo' essere inferiore alla data decorrenza 20-02-2021 dell'ultima operazione effettuata sui dati relativi a prima iscrizione nel comune corrente.

Alla luce dell'errore riscontrato, abbiamo interpretato male la documentazione?

**Comment by frmariani** [comment]
Come Lei ha ricordato, nella data di decorrenza dell'operazione, deve essere inserita la _Data di inizio validità dell’operazione di registrazione_  quindi nel suo caso 19/02/2021 ovvero la data da cui sarà valida la comunicazione di cambio della residenza della cittadina; questa data sarà uguale alla data di decorrenza del legame con la famiglia dove la cittadina si sta trasferendo e sarà uguale anche alla data da cui decorrerà la nuova residenza della cittadina. 
Per gli eventi di stato civile, sarà possibile inserire una data di decorrenza dell'operazione successiva, data che equivale alla data in cui avete ricevuto la comunicazione dell'evento da un altro comune, ma sarà possibile inserire la corretta data dell'evento stesso che sarà sicuramente antecedente alla data della comunicazione.
Chiarisco meglio con un esempio:
la cittadina in questione sposta la residenza nel vostro comune il giorno 19/02/2021, pertanto invierete la comunicazione con le tre date coerenti tra di loro;
il giorno 20/02/2021 ricevete comunicazione di trascrizione del matrimonio della cittadina avvenuto il 10/02/2021: invierete al sistema ANPR una comunicazione con data decorrenza 20/02/2021 dell'evento matrimonio avvenuto in data 10/02/2021.
Spero di aver chiarito

**Comment by SAlberto** [comment]
Quindi se ho capito bene, se la decorrenza è antecedente l'iscrizione o un'altra variazione dello stesso tipo 
nella dataDecorrenza di testataRichiesta
non devo mettere la data decorrenza ma la data di registrazione. E' corretto? 

Sono un po' perplesso ma se me lo conferma procedo...

**Comment by frmariani** [comment]
Purtroppo con i termini rischiamo fraintendimenti, mi faccia il caso specifico con le date per favore

**Comment by SAlberto** [comment]
Se il matrimonio viene celebrato il 10/02/2021 e l'individuo alla data è già residente nel comune quando lo registro (ipotizziamo il 20/02/2021) devo inviare
<testataRichiesta><dataDecorrenza>2021-02-10</dataDecorrenza>
<datiMatrimonio><dataEvento>2021-02-10</dataEvento>

Se l'individuo invece è immigrato il 19/02/2021 da comune NON subentrato e il 20/02/2021 ricevo i dati del matrimonio devo inviare
<testataRichiesta><dataDecorrenza>2021-02-20</dataDecorrenza>
<datiMatrimonio><dataEvento>2021-02-10</dataEvento>

Dove il 20/02/2021 è la data in cui registro i dati. E' corretto?

**Comment by frmariani** [comment]
Non vedo differenze nei due casi (attenzione alle date del primo caso):
nel primo caso, il cittadino è residente dal 20/02/2021 e la comunicazione del matrimonio celebrato il 10/02/2021 è arrivata il 20/02/2021
<testataRichiesta><dataDecorrenza>**2021-02-20**</dataDecorrenza>
<datiMatrimonio><dataEvento>**2021-02-10**</dataEvento>

nel secondo caso, il cittadino è residente dal 19/02/2021 e la comunicazione del matrimonio celebrato il 10/02/2021 è arrivata il 20/02/2021
<testataRichiesta><dataDecorrenza>**2021-02-20**</dataDecorrenza>
<datiMatrimonio><dataEvento>**2021-02-10**</dataEvento>

**Comment by SAlberto** [comment]
Il cittadino del primo esempio non è stato iscritto il 20/02/2021 in anagrafe, ipotizziamo che fosse già residente dal 2019. 
Il 20/02/2021 registro l'evento di matrimonio in anagrafe. 

Nella `<testataRichiesta><dataDecorrenza>` che data devo mettere? 
La data dell'evento (10/02/2021) o la data di registrazione (20/02/2021)?

**Comment by SAlberto** [comment]
Sono riuscito a far funzionare le diverse chiamate.
La ringrazio per il chiarimento
