### ISSUE TITLE
ERRORE EN075 - MATRIMONIO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2520]
Buonasera
Comune CASERTA - PRE
potreste indicarmi il problema 
Incongruenza dati anagrafici: il genere del soggetto non coincide con quello specificato nella richiesta
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-02-25 17:09:20 , idOperazioneANPR 20953187
Grazie

**Comment by rvinzani** [comment]
Credo che abbiate sbagliato gli IdANPR del soggetto principale: è stato inserito lo stesso id della moglie. Chiudo la issue, in caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova che faccia riferimento a questa
