### ISSUE TITLE
[1001] persona duplicata con stesso codice comune

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2521]
Buongiorno il comune di CERNOBBIO in PRODUZIONE con idOperazioneComune 20210224122713260 codMittente 013065
ha iscritto per nascita un bambino con idSchedaSoggettoComuneIstat 013065 e idSchedaSoggetto 20523
pochi minuti dopo con idOperazioneComune 20210224123147948 codMittente 013065 ha inviato una nuova 1001 per lo stesso bambino ma con un comune di nascita diverso ma stesso idSchedaSoggettoComuneIstat 013065 e idSchedaSoggetto 20523 con esito positivo "duplicando" la scheda.
l'errore è stato inviare una seconda 1001 in seguito alla correzione del comune di nascita però non c'è nessun controllo sul idSchedaSoggetto già presente, controllo che c'è inviando un'altra 1001 con stesso codice fiscale.

sarebbe possibile aggiungere un controllo nelle iscrizioni sulla presenza già di soggetti con stesso idSchedaSoggettoComuneIstat e idSchedaSoggetto?

grazie mille
Riccardo

**Comment by rvinzani** [comment]
Non facciamo nessun controllo sul numero assegnato dal comune. Tale numero infatti avrebbe dovuto essere utilizzato solo al momento del subentro per rimappare gli idANPR e poi non più utilizzato. La nostra raccomandazione è quindi quella di utilizzare l'identificativo univoco nazionale

**Comment by Hdemografici** [comment]
In presenza dell'ID ANPR inviamo sempre e solo quello, in questo caso però è una nascita quindi l'ID ANPR ancora non è stato assegnato.
nelle note del file oggetti\generalita.xslx riporta che idSchedaSoggettoComune
"Se non   presente né il codice fiscale né idSvhesaSoggettoANPR, è obbligatorio"

con l'occasione segnalo che nelle note ci sono 2 errori di battitura, proprio nelle note dei due tag idSchedaSoggettoComune (idSvhesaSoggettoANPR) e idSchedaSoggettoANPR (idSchesaSoggettoComune)

**Comment by rvinzani** [comment]
L'indicazione del codice comunale non è soggetta a controlli da parte di ANPR. Eventuali controlli che vengono demandati al comune. Grazie delle segnalazioni, provvederemo a correggerle. Chiudo la issue. nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
