### ISSUE TITLE
smart cart ANPR - smarrimento PIN E  PUK

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#2522]
Buongiorno

causa smarrimento, chiedo come si deve procedere a richiedere sia il PIN (completo) che il PUK della smart card ANPR.
Una collega ha inviato mail al seguente indirizzo: anpr.password@interno.it, circa un mese fa, ma ha ricevuto solo la seconda parte del PIN.
Grazie
Barbara Malavolti

**Comment by Leonforte** [comment]
Salve, dovrebbe cortesemente comunicarci il seriale della carta ed comune di appartenenza, grazie

**Comment by bmalavolti** [comment]
Comune di Castel Bolognese . numero seriale 0390060149470009

**Comment by Leonforte** [comment]
Buongiorno, quanto richiesto è stato inviato a giuseppina.utili@romagnafaentina.it
