### ISSUE TITLE
Attribuzione CF a cittadino con CF numerico

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2523]
La presente per richiederVi quale sia la corretta procedura da seguire per attribuire corretto CF alfanumerico al cittadino straniero con precedente CF temporaneo numerico.

Effettuando un'operazione di Mutazione Tutti i Dati - Tipo operazione: Operazione d'ufficio e Gestione Codice Fiscale: Richiesta attribuzione nelle response che riceviamo da ANPR viene riportato sempre il CF numerico anziché l'alfanumerico.

Id operazione ANPR di esempio: 465940506

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by rvinzani** [comment]
E' possibile attribuire un CF alfanumerico ad uno **numerico provvisorio** ( NON PER OMOCODIA) in caso di mutazione dati anagrafici del soggetto. Se l'operazione di mutazione dati va a buon fine viene emesso un CF alfanumerico associato ai nuovi dati anagrafici e collegato al numerico. Rimangono ovviamente le precedenti regole per cui non è possibile modificare più di tre dati e non è possibile effettuare la modifica se è già presente un CF con stessi dati anagrafici

**Comment by rvinzani** [comment]
chiudo la issue. Nel caso siano necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
