### ISSUE TITLE
controllo ip comune

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2524]
Buongiorno potreste controllare se l'IP 82.62.65.116 è correttamente censito per il comune di ERBUSCO?

Grazie mille

**Comment by cmigliardi** [comment]
Buongiorno 
chiedo verifica  e le faccio sapere

**Comment by cmigliardi** [comment]
l' ip  non risulta abilitato - Le chiedo avete  censito  in web app  di Produzione area Amministrazione  sezione informazioni aggiuntive l' ip ?   grazie

**Comment by cmigliardi** [comment]
mi puo' far sapere per favore ? grazie

**Comment by cmigliardi** [comment]
buongiorno,   cortesemente avrei necessità delle informazioni richieste.  
 Grazie per la collaborazione .

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
