### ISSUE TITLE
Comune di Ancona - AIRE duplicato a seguito di subentro

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2525]
A seguito del nostro subentro abbiamo un AIRE con ID ANPR 107211248 duplicato con il comune di MERGO che però abbiamo appurato non essere la stessa persona, quindi si tratta di un caso di omocodia. Essendo subentrati noi in un secondo momento rispetto al comune di MERGO vi chiediamo qual è la modalità più corretta di procedere, ovvero dobbiamo richiedere la svalidazione del nostro codice fiscale associato al nostro cittadino AIRE o dobbiamo richiedere il rilascio di un omocodice (che in tal caso comporterebbe il cambio di codice fiscale per entrambi i cittadini)? Facciamo presente che il nostro cittadino AIRE non ha mai fatto richiesta di codice fiscale e che il tutto si è generato a seguito del subentro. Attendiamo un vostro riscontro in merito. Grazie e saluti.

**Comment by rvinzani** [comment]
Se il cittadino non ha mai fatto richiesta di codice fiscale e non ne ha bisogno credo che sia sufficiente eliminarlo.
Mi può lasciare un recapito per contattarla telefonicamente?
