### ISSUE TITLE
Richiesta informazioni convenzione per emissione certificati

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2526]
Buongiorno,
la Federazione italiana tabaccai ci chiede con una certa insistenza di sottoscrivere una convenzione per il servizio di estrazione e stampa di certificati anagrafici presso gli esercizi associati.

L'estrazione avviene utilizzando un apparato (denominato NOVABOX) fornito dalla ditta Novares con la seguente specifica "Nessuna interazione o collegamento con i serve comunali ma solo con ANPR". L'apparato è autoinstallante.

Secondo voi, possiamo procedere (come hanno già fatto altri Comuni) oppure dobbiamo aspettare un'autorizzazione dal Ministero dell'Interno?

Alleghiamo le slide di presentazione del sistema e la bozza di convenzione.
[NovaCERTIFICA 30, il tuo certificato anche sotto casa, Comune di RAVENNA.zip](https://github.com/italia/anpr/files/6060741/NovaCERTIFICA.30.il.tuo.certificato.anche.sotto.casa.Comune.di.RAVENNA.zip)

Grazie per l'attenzione.,
cordiali saluti.

**Comment by FilippoPapi** [comment]
buongiorno 
enti diversi dai comuni per poter accedere ad ANPR devono  stipulare un accordo con il Ministero dell'Interno
cordiali saluti
