### ISSUE TITLE
controllo ip comune Erbusco

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2527]
Buongiorno mi scusi per la mancata risposta ad issue #2524, abbiamo fatto altri controlli con il comune, 
L'ip è correttamente censito in WA riportando anche l'asterisco, è stato provato anche a togliere e rimettere l'IP senza esito, il collegamento verso ANPR è bloccato.

L'ip da censire è 82.62.65.116.

grazie mille

**Comment by cmigliardi** [comment]
la ringrazio  molto - provvedo a chiedere  l'abilitazione e poi  le faccio sapere

**Comment by cmigliardi** [comment]
L' ip   è stato abilitato    cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
