### ISSUE TITLE
Invocazione WS 4005 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2528]
Comune di Caponago

Varisco Maria Giuseppina

Oggi per la prima volta abbiamo invocato il WS4005 per scaricare le notifiche di nostra competenza, per il periodo dal 01.01.2021 al 02.03.2021, l'esito 

<errore>
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>

Alleghiamo risposta

**Comment by GabriellaBallabio** [comment]
Potete cortesemente indicarci il motivo dell'esito ?

[message_in.txt](https://github.com/italia/anpr/files/6067504/message_in.txt)

Restiamo in attesa di gentile riscontro.

**Comment by lorbia** [comment]
Salve potreste allegare anche la richiesta ?

Grazie.

Saluti.

**Comment by GabriellaBallabio** [comment]
Di seguito i file richiesti

[message_out.txt](https://github.com/italia/anpr/files/6069796/message_out.txt)
[Richiesta4005.txt](https://github.com/italia/anpr/files/6069797/Richiesta4005.txt)

**Comment by mttfranci** [comment]
Salve sembrerebbe che avete utilizzato più volte nella giornata odierna l' idOperazioneComune = 20201211104317.
Vi ricordiamo che ogni idOperazioneComune può essere usata una sola volta.
In generale se riusata non verrà eseguita una nuova operazione ma restituito l'esito della precedente.
L'invocazione dove avete preso errore è stato un errore momentaneo del sistema.

**Vi consigliamo di rieseguire l'operazione con un idOperazioneComune univoco per il comune in questione e se avete ancora problemi ricontattateci.**
Saluti

Assistenza ANPR

**Comment by GabriellaBallabio** [comment]
Buongiorno
abbiamo riprovato questa mattina e ora funziona, restituisce l'esito allegato 
[message_in.txt](https://github.com/italia/anpr/files/6074302/message_in.txt)

<statoRichiesta>0</statoRichiesta>
                <idOperazioneANPR>469598203</idOperazioneANPR>
                <dataDisponibilita>2021-03-03T09:28:23.475+01:00</dataDisponibilita>

Mi aspettavo di ricevere come esito un file con l'elenco delle notifiche in formato xml. Cosa devo fare ? Invocare nuovamente il WS4005 con l'idOperazioneANPR ?

**Comment by lorbia** [comment]
Salve per i dettagli operativi dell'utilizzo del servizio è possibile fare riferimento alla issue:
https://github.com/italia/anpr/issues/1161
