### ISSUE TITLE
Identificazione vie in Anpr

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2529]
Gentilissimi,

vorremmo sapere se in ANPR ogni singola via viene identificata con un codice ed in tal caso qual è la sua l'origine ( codice via comunale? codice via ANNCSU? Codice generato da ANPR?)

Grazie.

Caterina Manoni - caterinamanoni@comune.ravenna.it
Tel. 0544/482005

**Comment by rvinzani** [comment]
Nel tracciato dell'indirizzo è possibile indicare il codice del comune o il codice ANNCSU in previsione dell'integrazione dei due sistemi. Il parametro fonte può essere utilizzato per definire se il codice è comunale o dell'archivio nazionale.
