### ISSUE TITLE
CARATTERE "/" NELLE LOCALITA' E INDIRIZZO ESTERO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#253]
Buongiorno
sul sito di ANPR selezionati: Documentazione Tecnica, Approfondisci, nel paragrafo
 "Di seguito la documentazione di riferimento aggiornata al 12 luglio 2017; con le seguenti modifiche riassunte nel presente documento - xls:", selezionato "presente documento - xls": è riportato il file Aggiornamenti: a riga 72 Servizio/Oggetto Residenza Estera, Tipo Modifica "Non è più ammesso il carattere "/" per località e indirizzo estero":
Non è corretta questa modifica in quanto molte dichiarazioni Consolari relative ad iscrizioni all'Aire di italiani riportano il comune di residenza all'estero con la barra, come ad es. i comuni del Brasile incui dopo la denominazione è presente la sigla dello stato es Caratinga/MG.

Inoltre in moltissimi indirizzi esteri è presente la "/" nei nn. civici ma anche nell'indirizzo: es C/MESA Y LOPEZ 35/6.
Eseguito un test di "Mutazione Dati Aire, Modifica residenza, abitazione o indirizzo all'estero", su soggetto con luogo residenza e indirizzo che contiene "/" sia nella città che nel civico e il sistema blocca l'esecuzione con i  msg:
"Il campo 'Residenza - Toponimo' contiene caratteri non validi" 
Il campo 'Residenza - Località/Città' contiene caratteri non validi"
Questo significa che se tutti i soggetti presenti in AnagAire dovranno essere bonificati prima di essere conferiti in ANPR si affronterà un'enorme quantità di lavoro.

Faccio presente inoltre che, in fase di immigrazione di straniero dall'estero moltissimi passaporti indicano il luogo di nascita con "/" e inserire un carattere diverso dalla "/" es "-" significa inserire dei dati in modo difforme dal documento originale.
Grazie
Cordiali saluti
Ufficio Procedure

**Comment by gcarbonin** [comment]
Il carattere "/" viene automaticamente convertito in spazio al momento del subentro.

**Comment by UpiTorino** [comment]
Buongiorno!
scusi se mi permetto: ma la descrizione di un indirizzo cambia se ci sono "/" piuttosto che spazi... E' proprio l'unica soluzine possibile?
Cordiali saluti
Stefania Amprimo
  ----- Original Message -----

**Comment by gcarbonin** [comment]
Purtroppo queste limitazioni sono necessarie per motivi di sicurezza: i caratteri c.d. speciali salvo qualcuno che è ammesso (punto virgola trattino apice) possono essere utilizzati in modo "fraudolento".  Faccio presente che già  attualmente nell'AIRE centrale questi caratteri vengono eliminati e sostituiti da spazio quando, ad esempio, si forma l'elenco unico degli elettori.

**Comment by luca-teamdigitale** [comment]
Se alcuni caratteri possono essere potenzialmente pericolosi, ANPR deve al suo interno adottare un sistema di escaping/encoding per trattarli in modo adeguato. Non deve di certo trasformarli rendendo l'indirizzo invalido.

**Comment by gcarbonin** [comment]
L'indirizzo è valido

**Comment by luca-teamdigitale** [comment]
Queste trasformazioni modificano l'indirizzo originale ed introducono differenze non necessarie rispetto ai database authoritative delle altre nazioni. Per cortesia utilizziamo le pratiche di escaping/encoding anziche` di trasformazione per trattare i caratteri speciali. Il risultato dal punto di vista della sicurezza e` il medesimo, e si evitano incongruenze che complicano la vita agli utenti finali e ad integrazioni future.

**Comment by gvarisco** [comment]
+1, pienamente d'accordo con @luca-teamdigitale.

**Comment by mccalv** [comment]
La issue è stata classificata come bug, quindi il carattere accettato nelle prossime release.

**Comment by busaster** [comment]
Buongiorno
ho scaricato oggi i nuovi XSD (datati 11/10/2017) ma il tipo dati "alfanumerico120char" non contempla ancora come valido lo slash "/".
Questo tipo dato è ancora usato per :
	- descrizioneLocalita in tipoLocalita
	- descrizioneStato in tipoLocalita 
	- descrizioneConsolato in tipoConsolato
	- descrizioneStato in tipoAltraCittadinanza
	- descrizioneStato in tipoCittadinanza
	- descrizioneLocalita in tipoComune
	- denominazione in tipoToponimoEstero
	- descrizioneLocalita in tipoDatoLocalitaEstera
	- descrizioneStato in tipoDatoLocalitaEstera
In quale prossima release sarà accettato nuovamente il carattere slash ?
Grazie

**Comment by gcarbonin** [comment]
Il carattere in questione sarà accettato soltanto nel toponimo estero e nella località estera (non nello stato). E' un intervento che inizieremo la prossima settimana in modo graduale collegandolo ad altri interventi in corso sui WS.

**Comment by bfilipazzi** [comment]
Avevamo immaginato, leggendo i commenti di mccalv (luglio) e di gcarbonin (ottobre), un intervento entro il 2017 e non abbiamo introdotto un controllo sul dato nel gestionale. Il problema si presenta frequentemente, l'ultima volta ieri a SPINEA (VE) per un indirizzo Indonesiano che contiene "BB/16". Filipazzi - Maggioli

**Comment by AMonopoliADS** [comment]
mi associo. siamo nella medesima situazione.
ieri due casi a FAENZA.
giusto per capire in maniera definitiva le prospettive che ci sono al riguardo.
grazie
Alessandro Monopoli ADS

**Comment by mccalv** [comment]
testabile da domani #582

**Comment by busaster** [comment]
sono disponibili i nuovi XSD in cui il carattere in questione è accettato per il tipo "tipoToponimoEstero" (oggi 
 di tipo alfanumerico120char) ?

**Comment by busaster** [comment]
intanto vi confermo che disabilitando la validazione XSD, una iscrizione AIRE per altri motivi con indirizzo contenente il carattere '/' è andata a buon fine. Immagino che prima del passaggio in produzione arrivino anche gli XSD aggiornati.

**Comment by gcarbonin** [comment]
Questo intervento è stato completato.
