### ISSUE TITLE
ATTIVAZIONE SMART CARD ANPR (NEW GENERATION)

### ISSUE THREAD

**Issue by AndreaBruni** [italia/anpr#2530]
Buongiorno,

sono alle prese da qualche giorno con l'attivazione di una nuova smart card ANPR del comune di MARCIGNAGO (PV) che seguo come sistemista.

Ho applicato attentamente le istruzioni contenute nella guida dell'8 giugno 2020 senza ottenere risultati utili.

Con Gosign ho verificato che il PIN fosse corretto.

Ho tentato l'attivazione della smart card mediante software ATTIVAZIONE SOGEI come riportato dalla guida

https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf

ma mi è ritornato il messaggio "Errore nell'inizializzazione del dispositivo di firma" 

Pertanto dal software SAFEDIVE non risultano dispositivi di firma disponibili.

Non saprei sinceramente come procedere.
Ringrazio anticipatamente e saluto cordialmente.

Andrea

**Comment by Leonforte** [comment]
Buonasera, è probabile che il certificato a bordo della carta sia corrotto, occorre quindi procedere con la riemissione del dispositivo che potrà essere effettuata in autonomia dall'amministratore locale della sicurezza del comune (attualmente non è presente e quindi dovrà essere assegnato ad un operatore o anche al Sindaco l'opportuno profilo di ALS dal Sindaco stesso). Le utenze e tutte e tre le carte risultano comunque attualmente attive. Buon lavoro, saluti

**Comment by AndreaBruni** [comment]
Buonasera,
sarà mia cura procedere quanto prima a mettere in pratica consigli e suggerimenti e a ragguagliarvi sull'esito dell'operazione.
Ringrazio per la celerità nella risposta e nella disponibilità e saluto cordialmente.

Andrea Bruni
