### ISSUE TITLE
Rettifica dati di subentro - residenza

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2531]
Buongiorno, il comune di Rovigo subentrato il 24/02/2021 ha alcuni soggetti che sono entrati in ANPR con dati errati: 

1) pratica di cambio abitazione per i seguenti soggetti: 
ID ANPR: 110258331 (IS)- 110258338 (MG)- 47891665 (FG)  sono stati erroneamente inseriti tutti nel medesimo indirizzo, e medesima famiglia con ID ANPR: 65262811, invece doveva essere iscritto solo il soggetto FG con ID 47891665 mentre l' IS e la MG dovevano restare nel precedente indirizzo. 
Abbiamo provato a correggere il dato da WS con una mutazione di residenza 5005 ma non ha funzionato. Quindi abbiamo eliminato la mutazione nr 465956328 da Webapp ieri e provato a vedere se potevamo modificare i dati di residenza con il menù delle rettifiche dati di subentro ma vediamo che non è ancora possibile.  Volevamo evitare di cancellare tutto e dover reinserire in webapp tutti i componenti con nuove iscrizioni. C'è altra soluzione? 

2) pratica di immigrazione da comune subentrato:
ID ANPR: 98588379 il soggetto è stato iscritto in famiglia esistente ma invece doveva essere iscritto in una nuova famiglia. 
Anche per questo caso il dato è passato in ANPR con l'xml di subentro, si deve procedere anche qui con la cancellazione da ANPR e la reiscrizione? 

Nel caso di cancellazione ci potete indicare quali sono i servizi corretti da utilizzare in web app? 

Nel caso sia necessario sentire il comune vi lascio di seguito il riferimento: 
SIMONE BUSATO cell. 3482496235

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SpA
3346216774

**Comment by CGIRELLI-HUB** [comment]
Buongiorno il comune sollecita una risposta in merito poichè devono immigrare una persona nel nucleo famigliare del IS.  E' possibile definire entro oggi? 

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SpA
3346216774

**Comment by frmariani** [comment]
ho tentato il contatto telefonico ieri ma senza successo.
per il primo caso va bene il servizio WS 5005 tipo mutazione 6 ma dovete inserire l'oggetto residenzaFamiglia in modo da indicare al sistema l'indirizzo ante subentro sconosciuto ad ANPR;
per il secondo caso ci sono un paio di strade percorribili ma forse la più corretta è la cancellazione per altri motivi alla stessa data di iscrizione nel comune.
Comunque tenterò di nuovo il contatto telefonico per essere più chiara.

**Comment by CGIRELLI-HUB** [comment]
Se non riesce a mettersi in contatto col comune potete contattare me Cinzia Girelli GPI SPA 3346216774 
Grazie 
Cordiali saluti

**Comment by frmariani** [comment]
grazie ma sono riuscita a parlare con il comune; nel caso ci fossero ulteriori problemi ci sentiamo per le vie brevi.
