### ISSUE TITLE
Indirizzo anpr.interno.it non sicuro

### ISSUE THREAD

**Issue by YacineBoussoufa** [italia/anpr#2532]
Buongiorno,
volevo segnalare che accedendo al sito dell'ANPR da [anpr.interno.it](https://anpr.interno.it), google segnala il sito come "non sicuro" a causa dell'errore "_NET::ERR_CERT_COMMON_NAME_INVALID_", accedendo invece da [www.anpr.interno.it](https://www.anpr.interno.it) il sito risulta sicuro.

**Comment by gife67** [comment]
Buongiorno,
i principali browser, per agevolare la navigazione permettono di omettere il www iniziale ed in base alle impostazioni di sicurezza permettono di cambiare i controlli sul matching dei nomi DNS con il DN dei certificati SSL/TLS installati sui siti. Ad esempio io uso Chrome ultima versione e sia che referenzio anpr.interno.it che www.anpr.interno.it, mi rindirizza sullo stesso sito e ricevendo il certificato server intestato a www.anpr.interno.it lo rende valido per entrambi le interrogazioni. Di solito accettando la segnalazione questa non verrà più riproposta e alla presentazione dell'home page del sito questo in entrambi i casi sarà riconosciuto come attendibile. Inoltre esaminando il certificato, cliccando sull'icona a forma di lucchetto, potrà verificare che il certificato è valido in tutte le sue componenti ed è intestato al sito ufficiale di ANPR (www.anpr.interno.it) ed emesso da una CA pubblica riconosciuta. Il portale di ANPR inoltre è esposto con l'ultima versione del protocollo TLS 1.2 a garanzia di una maggiore sicurezza.
Cordiali saluti
