### ISSUE TITLE
Eliminazione atto di nascita errato

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2533]
Comune di Modena - Ambiente produzione

Buongiorno,
durante l' iscrizione del soggetto con idANPR 42991397 (proveniente da altro comune subentrato) è stato inserito per errore un atto di nascita errato che ora dovrebbe essere rimosso. Non riusciamo però nè da webapp nè da applicativo, in quanto viene sempre restituito l' errore:

codiceErroreAnomalia: EN409
tipoErroreAnomalia: E
testoErroreAnomalia: Per tipo mutazione = 15 inserire l'oggetto Atto di Nascita 
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E
testoErroreAnomalia: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-05 10:34:31 , idOperazioneANPR 471961418
codiceErroreAnomalia: EN396
tipoErroreAnomalia: W
testoErroreAnomalia: I dati non coerenti con il tipo di mutazione richiesto non verranno acquisiti

nè si può usare la revoca in quanto i dati non provengono da subentro. Per cortesia potete indicarci come agire in questo caso?

Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Purtroppo è possibile modificarlo sostituendo i dati ma non eliminarlo.

**Comment by sfmodena** [comment]
Buongiorno,
nella issue #1546 del 2019 che trattava un caso identico (soggetto privo di atto al quale era stato inserito per errore) si diceva che inviando la richiesta via PEC ad   Assistenza.anpr@pec.sogei.it   il dato sarebbe stato eliminato. Se questa strada non è più percorribile significa che al cittadino rimarrà impostato un atto che non ha mai avuto e che potrebbe comparire su una certificazione, e che se ci chiedesse (giustamente) di toglierlo non saremmo in grado di farlo. Credo che sarebbe utile avere a disposizione un tipo di rettifica che consenta di risolvere situazioni simili.

Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Purtroppo non possiamo accogliere tutte le richieste puntuali arrivati al numero attuale di comuni. Prenderemo in considerazione la possibilità di rimuovere il dato attualmente possibile solo successivamente al subentro. Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire un a nuova issue che faccia riferimento a questa
