### ISSUE TITLE
SEBENTRO - DATA 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2534]
Buongiorno:
Ho ricevuto questa mail dal Team ANPR:
Gentile team I.T. Systems,
Secondo il piano di subentro da voi in precedenza fornito, l'integrazione del Comune di CASERTA in ANPR dovrebbe avvenire in data 15-03-2021.
Vi raccomandiamo di proseguire con le Vostre attività di integrazione e nel caso aggiornare il medesimo piano visitando la Dashboard ANPR.

MA DAL PIANO INVIATO LA DATA E' 10/03/2021  - NO 15/03/2021  (QUEST'ULTIMA E' LA DATA FINALE DELL'INTERVALLO).
VI CHIEDO, CORTESEMENTE, NOTIZIE IN MERITO.
GRAZIE

**Comment by cmigliardi** [comment]
Buongiorno,    le email  non le invia  sogei  ma  il dipartimento per la trasformazione digitale.   si rivolga a loro . grazie  cordiali salut

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
