### ISSUE TITLE
Problema driver nuove smartcard

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2535]
Comune di Modena - Ambiente produzione

Buongiorno,
stiamo rilevando due problemi legati all' installazione e all' uso del driver SafeDive  per le smartcard nuovo modello, in particolare:
1)  sui PC Windows10 con lettore OmniKey l' installazione di SafeDive non segnala errori, ma nella cartella "C:\Program Files (x86)\STMicroelectronics\SafeDive 3" troviamo soltanto due files per la disinstallazione:
unins000.dat
unins000.exe
è corretto? 
Su queste postazioni Chrome non consente l' accesso alla Webapp ANPR perchè sembra non leggere la smartcard; l' unico modo di accedere è configurare il dispositivo di sicurezza su Firefox (versione precedente alla 75)  associandogli il file "C:\Windows\System32\stPKCS11.dll". 

2) Su una postazione dove era funzionante la nuova smartcard configurata su Firefox è stato installato il software per la firma digitale remota ArubaSign, da quel momento i tentativi di accesso ad ANPR falliscono con errore: SSL_ERROR_HANDSHAKE_FAILURE_ALERT
dopo aver richiesto 3 volte il PIN.  In Firefox, alla voce "Opzioni - Privacy e sicurezza - Certificati- Certificati personali" la smartcard però è visibile, come se venisse letta correttamente.

Per cortesia potete darci qualche indicazione, in particolare sulla correttezza dell' installazione di SafeDive e sull' esistenza di incompatibilità tra SafeDive e ArubaSign?

Grazie, saluti
Sonia Fiorini

**Comment by Leonforte** [comment]
Buongiorno, Safe Dive è un driver silente che non ha interfaccia di controllo, ed installa le dll necessarie (la stPKCS11.dll appunto) nel sistema, quindi la risposta al punto 1 è si, è corretto. Aggiungo che l'accesso con firefox è attualmente il più collaudato utlizzando il suddetto modulo. Per quanto riguarda il secondo punto le suggersco di provare ad installare il software DikeGoSign ultima versione che dovrebbe consentire anche le operazioni di firma di ArubaSign, buon lavoro, saluti

**Comment by papinifrancesco** [comment]
"A me inoltre servirebbe che funzionasse anche su linux, anche lì lo stesso problema. è possibile parlare direttamente con lo sviluppatore per capire qual è la sua configurazione software?"

Idem, sto ammattendo su Fedora 35 (ma prima anche sulla 33) e non sto riuscendo a farla funzionare a dovere: viene vista, viene chiesto il PIN, ma poi quando un server chiede il client certificate la risposta arriva (visto da Wireshark) ma arriva VUOTA.... Su Windows 10 invece 5' d'installazione e pronto, quindi la CNS funziona.

**Comment by Leonforte** [comment]
Buongiorno, purtroppo non abbiamo un riscontro diretto di eventuali malfunzionamenti su Fedora, ma ha già consultato questo Git ?

https://github.com/marcogiannini/Dike-GoSign-installer-per-fedora

**Comment by papinifrancesco** [comment]
Problema risolto almeno per Firefox.

Riavviato Firefox in "Troubleshoot Mode" (niente estensioni)
Unload di p11-kit-proxy
Load di SafeDive2020/outerlibs/libstpkcs11.so

Tutto funzionante e quindi nel mio caso era l'estensione SAML-tracer di Firefox a causare il malfunzionamento.

**Comment by Alberthubs97** [comment]
Buonasera, io ho un problema con una carta ts cns ST2021 della Regione Toscana. Inserendo la carta cns nel lettore smartcard nessun problema, SafeDive2020 e Bit4id leggono tutti i dati, inoltre accedo tranquillamente all’INPS, portali della regione Toscana, fascicolo sanitario ecc…

Tuttavia quando tento di fare la richiesta dello spid tramite cns, non c’è niente da fare: non funziona!
Ho provato su diversi siti di provider (infocert, namirial, posteid), ho provato da diversi browser, su 3 pc diversi che hanno 3 sistemi operativi diversi (win 7, 10, 11) ma non ho ottenuto risultati. Quando sui siti dei provider arriva il momento di fare l’autenticazione, mi viene richiesto il pin, il certificato viene visualizzato ma subito dopo mi viene restituito il messaggio “Autenticazione falllita”.
Ho chiamato anche la regione toscana, pensando che fosse un problema della tessera ma mi hanno confermato che è attiva e funzionante, inoltre mi hanno detto che il problema potrebbe dipendere dal fatto che i provider non abbiano aggiornato i propri certificati… (non so se sia attendibile questa motivazione). Ho provato anche a chiamare varie volte i provider senza risultato.

Se qualcuno ha qualche suggerimento gliene sarei grato!
Grazie

**Comment by papinifrancesco** [comment]
Ciao, purtroppo ST 2021 non è di Regione Toscana ma di ST Microelectronics di Marcianise.
Quindi Regione Toscana non è, purtroppo, il gestore di questa carta e la risposta che ti hanno dato è plausibile: di inserimenti di CA emittenti a scopo di trust ne so qualcosina, fidati. ;-)
Io non ho provato ad ottenere un'identità SPID con la nuova ST 2021: le ho già tutte.... fatte però con la vecchia CNS che funzionava benissimo.
Altra cosa: le macchine che hai provato erano "vanilla"? Nel senso che una prova che ti chiederei di fare (mi interessa) è quella di farti magari una VM Windows 10 nuova nuova e riprovare con quella: lo farei io ma come ho detto sopra ho già ogni SPID possibile.
Non vorrei che tu avessi provato con macchine che avevano già a bordo precedenti software di gestione della CNS precedente e che questi ultimi possano confliggere con il nuovo.

**Comment by Alberthubs97** [comment]
Ciao, Grazie mille della risposta.
Appena riesco cercherò di farlo e ti aggiorno.

Il giorno gio 27 gen 2022 alle ore 19:03 Francesco Papini <
***@***.***> ha scritto:

**Comment by papinifrancesco** [comment]
Aggiornamento: ho appena fatto SpidItalia (incredibile, mi mancava!) con la ST 2021 su Fedora 35 con Firefox.
