### ISSUE TITLE
WSA001 - Errore EN237

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2536]
COMUNE CASERTA - PRE
EN237
La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata
EN527
data 2021-03-05 13:06:03 , idOperazioneANPR 20972690

**Comment by ncapozzi** [comment]
Buongiorno,
la dataDecorrenza 2020-06-17 dell'iscrizione A001 non può essere antecedente alla data di decorrenza 16/12/2020 della residenza della famiglia alla quale il nuovo iscritto AIRE viene associato.

N. Capozzi
