### ISSUE TITLE
Problema di dialogo tra ANPR e software gestionale

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2537]
Buongiorno,
invio mail per collega di un comune limitrofo.
Premetto che detto comune è subentrato il 03/12/2018 e non ha mai avuto problemi a inviare i dati in ANPR tramite WS del gestionale.
A dicembre hanno cambiato connettività e, di conseguenza anche IP Pubblico e il passaggio di dati ad ANPR ha smesso di funzionare.
La collega ha già interpellato la Software House, il Provider Internet e la società di consulenza informatica che gestisce l'assistenza dell'ente, ma non riescono a venire a capo del problema.
Vorrei sapere se esista un modo per testare il collegamento ad ANPR? L'indirizzo Ip pubblico deve essere inserito in webApp ANPR -> Amministrazione -> Info aggiuntive? Mi sembra che l'abbia già fatto ma senza risultato.
Il cambio di IP potrebbe essere il problema? Quali sono le verifiche che deve mettere in atto per capire se ci sia un problema di comunicazione con ANPR?

Grazie

**Comment by Leonforte** [comment]
Buongiorno, per le verifiche del caso ci occorre il nuovo indirizzo e il comune in questione, grazie

**Comment by cvignati** [comment]
Il comune è Dairago
L'indirizzo Ip ricavato da www.whatsmyip.org è 109.234.60.58. Questo indirizzo è stato inserito dalla collega venerdì 5 marzo in webApp ANPR -> Amministrazione -> Info aggiuntive ma oggi è "sparito"
Il Provider Internet ha detto alla collega di inserire l'ip 109.234.60.59 che attalmente in webApp ANPR -> Amministrazione -> Info aggiuntive è presente con l'asterisco.

Spero possa essere risolta la problematica in quanto sta lavorando in "Doppio" (Gestionale e WebApp ANPR) da 2 mesi.

Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
pe favore può dirmi da quale ip  instaurate il colloquio con anpr ?  con uno  o con due  ?  e perché  lavorate il doppio? 
grazie in anticipo per le info che ci fornirete

**Comment by cvignati** [comment]
> 
> 
> Buongiorno,
> pe favore può dirmi da quale ip instaurate il colloquio con anpr ? con uno o con due ? e perché lavorate il doppio?
> grazie in anticipo per le info che ci fornirete

Buongiorno,
l'indirizzo IP è solo 1 e dovrebbe essere 109.234.60.59

Lavora in doppio in quanto non funziona la comunicazione con i WS dal suo gestionale ad ANPR e deve collegarsi alla WebApp e inserire le variazioni fatte nel gestionale anche lì.

Grazie

**Comment by cmigliardi** [comment]
chiedo verifica - grazie

**Comment by cvignati** [comment]
Grazie a lei

**Comment by cmigliardi** [comment]
l' ip  109.234.60.59  risulta abilitato

**Comment by cmigliardi** [comment]
è stato abilitato il 2 marzo 2021  alle 9:21

**Comment by cmigliardi** [comment]
è stato abilitato il 2 marzo 2021  alle 9:21

**Comment by cvignati** [comment]
Ok ma c'è modo di testare se la comunicazione funziona?

**Comment by cmigliardi** [comment]
puo' fare un test di connettività

**Comment by cvignati** [comment]
Esiste un link di test?

**Comment by cmigliardi** [comment]
trova tutta la documentazione della  Documentazione tecnica -  www.anpr.interno.it

**Comment by cvignati** [comment]
Grazie.

Questo? https://ws.anpr.interno.it/ANPRTestConn/TestConn

**Comment by cmigliardi** [comment]
esattamente

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
