### ISSUE TITLE
[5001] Cambio di indirizzo d'ufficio per revisione onomastica

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#2538]
Buongiorno, volevo chiedere una conferma.
Se invio una comunicazione 5001 con tipoMutazione = 7 (Revisione onomastica stradale e dei numeri civici) la comunicazione viene inviata alla motorizzazione?
Modifico sia la via che il civico.

In attesa di una conferma
Ringrazio anticipatamente

**Comment by SAlberto** [comment]
La variazione che devo fare deve essere inviata a MCTC.
Una via è stata divisa in diverse nuove vie e i numeri civici sono stati riassegnati.
Come mi consiglia di procedere?

**Comment by SAlberto** [comment]
Il tipo mutazione 9 non posso usarlo in quanto richiede che la decorrenza sia uguale alla precedente. 
I cambi di indirizzo che devono essere inseriti hanno una loro decorrenza e devono essere inviati alla motorizzazione.
Inoltre, essendo dei cambi di indirizzo d'ufficio per revisione onomastica, dovrebbero riportare sui certificati di residenza i riferimenti agli articoli del regolamento anagrafico che lei ha citato.

Il comune sta aspettando dalla prefettura l'autorizzazione a procedere che dovrebbe arrivare fra qualche giorno, quindi prima di dover inserire i cambi di indirizzo c'è ancora un po' di tempo.
Sarebbe possibile prevedere qualcosa per forzare l'invio alla motorizzazione mantenendo il tipoMutazione corretto? Ad esempio un controllo da aggiungere alla listaControlli.

**Comment by azabatta** [comment]
Il problema non è di carattere tecnico ma di regole scritte di colloquio tra le parti. Non possiamo inviare a MCTC una tipologia di informazione che la momento non è prevista e che non si aspetta.

**Comment by SAlberto** [comment]
Ho capito, la ringrazio. Chiederò all'ufficiale di Anagrafe come intende procedere.
Buona giornata
