### ISSUE TITLE
SUBENTRO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2539]
Buonasera,
COMUNE CASERTA
1) i file possono essere inviati a qualsiasi ora purché sia il giorno pianificato (anche in ore notturne) ?  
2) quanto tempo intercorre. presumibilmente, tra l'invio dei dati e la ricezione della PEC di conferma?

Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
una volta  prenotato il subentro in produzione potete  inviare a qualsiasi orario 
se avete necessità di un monitoraggio fatecelo sapere che ci organizziamo - 
dall'invio dei dati alla pec  non so darle un intervallo temporale preciso - dipende  da diversi fattori:   numerosità  dei record,  temoi di elaborazione di ANPR -  tempi di elaborazione di  agenzia entrate  
siamo  a disposizione per un monitoraggio - se vuole mi scriva privatamente e  ci  organizziamo  al nostro interno per seguire i log di elaborazione del comune di Caserta. 
cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
