### ISSUE TITLE
Creazione Processi e Convenzioni per il Change Management

### ISSUE THREAD

**Issue by luca-teamdigitale** [italia/anpr#254]
Questa issue serve al tracciamento della evoluzione di ANPR con l'introduzione di processi e convenzioni per gestire i cambiamenti software.

Una prima proposta è in discussione qui:

https://forum.italia.it/t/proposta-di-processi-e-convenzioni-per-il-change-management/873

**Comment by luca-teamdigitale** [comment]
Dopo una fase di consultazione abbiamo considerato la proposta come una buona base di partenza e abbiamo iniziato a lavorare con SOGEI all'implementazione.

Per ulteriori dettagli si veda https://forum.italia.it/t/proposta-di-processi-e-convenzioni-per-il-change-management/873/2 .

**Comment by gcarbonin** [comment]
L'implementazione è stata completata

**Comment by mccalv** [comment]
Aggiungo che abbiamo messo on line una pagina anche con change log e roadmap e l'elenco delle versioni negli ambienti 
http://anpr.readthedocs.io/en/latest/change-management/index.html
Lascio aperto la issue per ulteriori commenti
