### ISSUE TITLE
Sistema di numerazione metrica negli indirizzi

### ISSUE THREAD

**Issue by danilomarini** [italia/anpr#2540]
Comune di Calusco d'Adda
Ambiente di produzione

Buongiorno, 
in riferimento al ticket https://github.com/italia/anpr/issues/2497 nel quale si evidenzia l'anomalia sulla numerazione metrica che  viene stampata come kilometrica, si rimarca che il Comune di Calusco d'Adda lamenta altresì il fatto che anche le CIE non utilizza in modo adeguato la sopracitata numerazione.
Interpellata l'assistenza CIE, questa risponde in un primo messaggio che 

" [...] a seguito di collegamento da remoto si è visto che ANPR restituisce il dato in km e così viene recepito da CIEOnline.
Pertato l'operatore dovrà necessaria intervenire manualmente per la trasformazione del dato in mt."

Interpellata l'assistenza CIE una seconda volta viene risposto che 

"[...] EFFETTUATO VERIFICA E VERIFICATA INCONGRUENZA TRA I DATI DEL GESTIONALE E QUELLI RIPORTATI IN CIEONLINE.
L' UTENTE MI COMUNICA CHE ALLA BASE L ' ANPR NON TIENE CONTO DEL NUOVO SISTEMA METRICO PER I CIVICI [...]"

Ci sono insomma incongruenze che causano confusione tra ANPR (che gestisce il dato in metri ma lo stampa come chilometrico) ed il portale CIE (che recepisce il dato in chilometri pur provenendo da un dato in metri).
Il Comune segnala infatti che alcuni cittadini hanno ora in mano CIE con il dato di residenza espresso in metri ma il certificato di residenza riporta il dato in kilometri.

E' possibile rendere omogeneo il dato?

**Comment by rvinzani** [comment]
In ANPR è recepito in metri e convertito in Km sui certificati secondo quanto concordato con Il Ministero, ma il dato rimane comunque corretto- Faremo comunque una verifica con i gestori delle CIE. Ringrazio per la segnalazione
