### ISSUE TITLE
Caratteri diacritici nella denominazioneToponimo (Dia1)

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#2543]
Buongiorno,

un comune della provincia di Bolzano ci ha segnalato che l'Astat e l'Istat di Roma gli hanno fatto presente che nel campo della dizione italiana del toponimo eventuali caratteri diacritici vanno traslitterati nelle lettere dell'alfabeto della lingua italiana questo per allineare i toponimi a quelli presenti in ANNCSU dove non sono previsti l'utilizzo di caratteri speciali nella denominazione - vedi: https://www.agenziaentrate.gov.it/portale/documents/20143/266134/Informativa+Istat_Istruzioni+ordinamento+ecografico.pdf/c7cd141f-4acb-cf5a-42b3-04ade2c69474  
a pagina 25

Questo differisce da quando riportato nelle vostre specifiche di interfaccia  tipoDato.xsd  dove per la denominazioneToponimo sono accettati anche caratteri speciali.

esempio:  
A Terlano hanno la via che si chiama
Via Hörtmoos

ANPR prevede la translitterazione di questi indirizzi verso ANNCSU o altri Enti?

Grazie e distinti saluti

Carla Musian
Applicativo Ascotweb
GPI

**Comment by rvinzani** [comment]
Attualmente ANPR non ha collegamenti con la toponomastica ANNCSU. Il formato e i caratteri del toponimo sono stati decisi in accordo con il Ministero dell'Interno. Il dato viene trasferito traslitterato quando inviato  ad Agenzia Entrate e agli altri enti collegati

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
