### ISSUE TITLE
[3002] scheda completa mancante di INDIRIZZO

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2544]
Ambiente di produzione, comune di Castellana grotte.
Facendo una ricerca cittadino di tipo "dati completi "con il servizio in oggetto non ci viene restituito il tag residenza nel XML di risposta (id operazione ANPR 477225800).
Nemmeno nella webapp risulta il dato.

Sul soggetto è stata eseguita oggi una mutazione residenza in cui è stato indicato il nuovo indirizzo nel comune di lavoro (id operazione ANPR 477160488)

Cosa è successo ? come mai non vediamo l'indirizzo ?

Grazie

**Comment by rvinzani** [comment]
Il problema è sorto quando è stato effettuato un 5005 inserendo come comune residenza CASTELLANA invece di CASTELLANA GROTTE (comune attuale). Possiamo aggiornare l’indirizzo con la denominazione corretta?

**Comment by rvinzani** [comment]
Chiudo la issue non avendo ricevuto risposta. Nel caso si prega di aprire una nuova issue che faccia riferimento a questa
