### ISSUE TITLE
Problema Certificati online

### ISSUE THREAD

**Issue by AndreaM326** [italia/anpr#2545]
Salve,
Sto attivando il servizio DemograficiOnline, per un comune subentrato in ANPR, attraverso la WebApp ho già impostato la firma per il certificato online.
Unico problema è la cattiva gestione degli apici nel Certificato generato, infatti nel titolo del responsabile che emette il certificato non riesco a visualizzarli. Infatti invece di visualizzare L'Ufficiale d'Anagrafe visualizzo "LUfficiale DAnagrafe".

**Comment by rvinzani** [comment]
Il problema è stato risolto. Può riprovare
