### ISSUE TITLE
[5012] Annullamento mutazione inefficace

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2546]
Ambiente di produzione, comune di Riccione

in data 01/02/2021 è stata effettuata una mutazione residenza per un cittadino che immigra da altro subentrato (id operazione ANPR 440522709).
In data 15/02/2021 la pratica è stata rigettata è l'operazione annullata con una chiamata 5012 (id ANPR 453830394) completata con successo.

Nonostante questo, il soggetto in ANPR risulta iscritto ancora nel comune di Riccione e non nel comune di provenienza.

Come mai ?

**Comment by ncapozzi** [comment]
Buonasera,
453830394 ha annullato 440522709 ma subito dopo è stata trasmessa una nuova mutazione di residenza 453854347 che ha riportato di nuovo il cittadino nello stesso indirizzo di 440522709.
Potete verificare voi stessi facendo accesso in consultazione ed estrazione alla scheda del cittadino e poi selezionando elenco operazioni.

N. Capozzi

**Comment by busaster** [comment]
Grazie, abbiamo risolto
