### ISSUE TITLE
[5008] Vedovanza: errore per ComuneRegistrazioneAttoNascita rinumerato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2547]
ambiente di PRODUZIONE - comune di PORTO MANTOVANO (020045)

comunicazione per aggiornamento della vedovanza: idOperazioneComune 2021001134
il soggetto interessato è nato nel 1942 a COLLE D'ANCHISE (CB), quando il comune aveva codifica 070-036
(oggi, e dal 1970, il comune ha codice 037-020)

la comunicazione va in errore con il messaggio:
EC168 - E - Codice ISTAT del comune di registrazione atto di nascita 070036 incongruente con quello presente sulla tabella di riferimento

ma i dati che vengono comunicati sembrano coerente con il frammento storico del comune
```
	<attoNascita>
		<comuneRegistrazione>
			<nomeComune>COLLE D'ANCHISE</nomeComune>
			<codiceIstat>070036</codiceIstat>
			<siglaProvinciaIstat>CB</siglaProvinciaIstat>
		</comuneRegistrazione>
		<anno>1942</anno>
		<parte>1</parte>
		<numeroAtto>25</numeroAtto>
	</attoNascita>
```

potete verificare cosa non va?

grazie
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Il codice Istat 070036 relativo a Colle D'Anchise è valido dal 24/04/1946 al 02/03/1970 quindi non sembra congruente con l'anno dell'atto 1942

**Comment by AMonopoliADS** [comment]
grazie del riscontro Roberta.
mi fai notare che c'è un salto temporale nella storia del comune dal 1928 al 1946.

come suggerisci di procedere, considerato che per il cliente questo tizio è nato a COLLE D'ANCHISE nel 1942?

**Comment by rvinzani** [comment]
Forse il comune è a conoscenza di quale sia la denominazione del comune e il codice istat nel 1942
