### ISSUE TITLE
Errore date scheda familiare ANPR

### ISSUE THREAD

**Issue by cromum** [italia/anpr#2548]
Salve a tutti. scrivo qui perché non so a chi rivolgermi.

Nella mia scheda familiare ANPR (n. 34729343) TUTTE le date sono errate.

sono tutte anticipate di un giorno: le date di nascita mia, di mia moglie e di suo figlio e la data di matrimonio.

Mi sono rivolto all’anagrafe del comune di residenza ma dicono che a loro le date risultano quelle corrette e che non possono intervenire (infatti se richiedo un certificato online le date sono corrette).

Il problema è sulla scheda ANPR ed evidentemente si tratta di un bug (lo stesso tipo di errore applicato a tutte le date).

Inoltre deve esserci un collegamento con il fatto che la nuova app MyInfocert che sostituisce la precedente Infocert, ora riporta lo stesso errore: la mia data di nascita è anticipata di un giorno.

spero che questa sia la piattaforma giusta per segnalare questo errore.

Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
le chiedo se ha  più provato a consultare la visura dopo  il  12 Gennaio?   grazie

**Comment by cromum** [comment]
Buongiorno.
Non avevo provato dopo quella data. Grazie!

di fatti le date di nascita ora sono corrette.

restano errate solo le date di scadenza della carta di identità e quella del matrimonio.

**Comment by cmigliardi** [comment]
Buongiorno, per favore potrebbe riprovare a controllare le date ?  Ora dovrebbero essere corrette -  grazie  in anticipo .

**Comment by cromum** [comment]
Perfetto. Grazie!

**Comment by cmigliardi** [comment]
grazie a lei per la segnalazione

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
