### ISSUE TITLE
certificato TLS wstest.anpr.interno.it scaduto

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#2549]
Buongiorno, ho provato a scaricare il certificato estest.anpr.interno.it per predisporre un ambiente di test per un nostro cliente ma e' scaduto il 31/10/2019. Potete generarne uno nuovo o indicarmi dove scaricare quello aggiornato.
Grazie.

Andrea Galli 
Municipia spa

**Comment by Leonforte** [comment]
Salve, ci scusiamo per l'inconveniente, abbiamo aggiornato il file relativo al certificato. Può effettuare il download dal sito https://dptest.anpr.interno.it/combas nella sezione Strumenti di supporto, buon lavoro saluti
