### ISSUE TITLE
[5008] - blocco pratiche del comune per sovrapposizione eventi

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#255]
Corbetta, Ambiente di Produzione.

Buongiorno, permane il problema già più volte segnalato di segnalazione di errore nella mutazione 20 a seguito di eventi intervenuti tra la prima registrazione anagrafica ai sensi del D.L. sulla residenza in tempo reale e la conferma dei dati del soggetto.
Attualmente il comune di Corbetta ha 6 pratiche ferme, per le quali non riesce a fare la conferma dati e definire quindi la pratica di residenza, così suddivise:
2 casi in cui l'iscritto si è coniugato prima che pervenisse la conferma dati dal comune di provenienza (ID operazioni ANPR 779389 e 779526);
2 casi in cui l'iscritta ha chiesto ed ottenuto il rilascio della carta d'identità sempre prima di fare la mutazione 20 (ID operazioni ANPR 779577 e 779599);
1 caso in cui all'iscritto è stato variato il luogo di nascita a seguito di errore materiale nell'iscrizione anagrafica (ID operazione ANPR 779553);
1 caso in cui all'iscritta viene segnalata una variazione di generalità di cui però non si trova traccia neanche sulla WebApp di ANPR (ID operazione ANPR 779679).

Il comune ci chiede urgentemente come poter procedere per risolvere queste casistiche, grazie.

Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Contatteremo il comune per spiegare come procedere
Id 779577 779526 il matrimonio è una informazione comune ai due coniugi se entrambi presenti in ANPR
id 779588 e 779599 il rilascio della carta di identità non crea problemi; è stata effettuata contestualmente una mutazione degli altri dati della persona  (titolo di studio condizione professionale ecc.)
id 779553 e 779679 da subentro è stata indicata come data di ultima variazione della scheda 26 maggio; quindi le variazioni non possono decorrere da una data antecedente.

**Comment by LucaBonini64** [comment]
Mi scusi ma non condivido le risposte:
Il matrimonio è un'informazione comune, va bene, ma se uno dei due coniugi ha variato la residenza prima di sposarsi devo comunque poter aggiornare i suoi dati;
Nel rilascio della carta d'identità è normale aggiornare anche i dati relativi alla condizione professionale perché è un informazione presente sulla carta d'identità cartacea che è ancora quella più diffusa sul territorio nazionale, idem per il titolo di studio perché quando un cittadino dichiara come professione ingegnere e il titolo di studio risulta licenza elementare, viene fatta fare anche la variazione del titolo stesso;
Nei dati di subentro è prevista la data di ultima variazione e viene passata la data dell'ultimo evento anagrafico fatto dal cittadino ma non può essere usata in maniera così bloccante perché la tipologia di evento è estremamente variegata e nessuno può sapere se il cittadino ha fatto degli eventi con una decorrenza precedente.

**Comment by gcarbonin** [comment]
#104
