### ISSUE TITLE
Riga del file ANPR Archivio comuni errata per ADERNO'

### ISSUE THREAD

**Issue by crendsist** [italia/anpr#2550]
Buongiorno,
all'indirizzo

https://www.anpr.interno.it/portale/tabelle-di-riferimento

il file nella tabella accessibile alla riga

03 | ANPR Archivio comuni | Istat-Agenzia delle Entrate-Ministero | 8 marzo 2021 

presenta la linea apparentemente erronea nel formato csv

`"17704","1861-03-17","1929-08-22","087006","A056","ADERNҢ,"ADERNO'","","","87","087","19","","C","CT","","2016-06-17","087500"`

**Comment by cmigliardi** [comment]
verifichiamo - grazie

**Comment by cmigliardi** [comment]
abbiamo  aggiornato il file  .  ora chiediamo la  nuova pubblicazione sul sito anpr -  grazie  per la segnalazione  -

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
