### ISSUE TITLE
Portale servizi al cittadino su ANPR - Comune di Ancona

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2551]
Con il DL Semplificazioni (Art. 30 DL 76/2020) è previsto che “La certificazione dei dati anagrafici in modalità telematica è assicurata dal Ministero dell’Interno tramite l’ANPR mediante l’emissione di documenti digitali muniti di sigillo elettronico qualificato, ai sensi del Regolamento (UE) n. 910/2014 del Parlamento europeo e del Consiglio, del 23 luglio 2014.” Vorrei sapere se ci sono novità sulla realizzazione di questo portale al cittadino e quali sono eventualmente le tempistiche. Grazie e saluti. Ferretti Laura

**Comment by FilippoPapi** [comment]
buongiorno,
la realizzazione è in dirittura d'arrivo, siamo in attesa dell'emanazione di un apposito decreto da parte del Ministero dell'Interno
saluti
