### ISSUE TITLE
ERRORE EN085 A SEGUITO DI CAMBIO COGNOME

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2552]
Per l'ID 95422677 è stato effettuato il cambio cognome dal gestionale locale. Adesso però andando a provare l'emissione di uno storico di residenza ad una data antecedente all'operazione viene restituito l'errore indicato nel titolo. L'operazione doveva essere effettuata con decorrenza dalla nascita del soggetto oppure l'errore sarebbe stato restituito in ogni caso? 
AMBIENTE DI PRODUZIONE
COMUNE DI CASTELLAMMARE DI STABIA
CONZA GIANPAOLO

**Comment by rvinzani** [comment]
Ci può indicare l'identificativo dell'operazione che ha restituito l'errore?

**Comment by gianpaol** [comment]
Non saprei dove reperirlo. L'emissione dello storico di residenza produce un errore bloccante che riporta il codice errore EN 085, non viene data nessun'altra indicazione circa l'id operazione come avviene per altri errori. Di seguito l'immagine dell'errore:
![Immagine](https://user-images.githubusercontent.com/76410238/111308816-718acd80-865b-11eb-8620-aa962d6ba81a.png)

**Comment by lorbia** [comment]
Salve, l'errore è causato dal fatto che la richiesta viene fatta ad una data antecedente la mutazione anagrafica riportando i dati successivi alla stessa; in questa casistica specifica il sistema rileva un'incongruenza tra i dati anagrafici.

Esempio:
Il 05/03/2021 Andrea Bianchi diventa Andrea Rossi.
Richiedo il certificato alla data del 01/03/2021 con dati anagrafici Andrea Rossi, ma a quella data il soggetto era ancora Andrea Bianchi per cui i dati anagrafici dell'intestatario del certificato risultano incongruenti.

Suggeriamo di richiedere lo storico di residenza alla data corrente.

Saluti.

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
