### ISSUE TITLE
Impossibile inviare comunicazione 4001

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2553]
Comune di ROVITO

Comunicazione 4001 restituisce errore EN179 "Richiesta non efettuabile: e' presente una richiesta dello stesso tipo (ma nel programma non ce ne sono, n.d.r.) non ancora lavorata".
Potete provvedere o far provvedere a sbloccare questa situazione?
Si veda xml di richiesta e di risposta (in formato .txt per poterli allegare):
Ringrazio e auguro buona giornata.
[risposta.txt](https://github.com/italia/anpr/files/6140274/risposta.txt)
[richiesta.txt](https://github.com/italia/anpr/files/6140275/richiesta.txt)

**Comment by amollicone1982** [comment]
Situazione sbloccata
