### ISSUE TITLE
WSA001 - Errore data decorrenza appartenenza famiglia 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2554]
Buongiorno
COMUNE CASERTA 061022 - PRODUZIONE
nella data di appartenenza al nucleo abbiamo  inserito la data di nascita

La data decorrenza appartenenza alla famiglia  deve essere uguale alla data decorrenza dell'operazione
 ma evidenzia errore  EN527     
Operazione ANPR:              
data 2021-03-15 10:49:50 , idOperazioneANPR 480208797
Quali date vanno indicate?
Grazie

**Comment by rvinzani** [comment]
Dovete modificare la data decorrenza dell'operazione inserendo la data di nascita

**Comment by rinonasti** [comment]
fatto ma stesso risultato

a data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata
EN527
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-16 13:54:22 , idOperazioneANPR 481544857

**Comment by rvinzani** [comment]
La data di apertura della famiglia però risale al 04/12/2020, è quindi non possibile che il soggetto risieda nella famiglia in una data antecedente a questa

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa
