### ISSUE TITLE
WSA006 - mutazione residenza estera 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2555]
COMUNE DI CASERTA - PRODUZIONE
Potreste cortesemente darci indicazioni in merito:
Grazie

<codiceErroreAnomalia>EF007</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Intestatario della scheda famiglia/convivenza gia' presente</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-15 12:18:46 , idOperazioneANPR 480375789</testoErroreAnomalia> 
  </errore>

**Comment by ncapozzi** [comment]
Buonasera,
state spostando  il cittadino in una famiglia AIRE che già esiste e nella quale già è presente un intestatario. Quindi il legame di parentela del cittadino che state spostando non può essere 1 - intestatario. Dovete indicare il legame con l'intestatario.

N. Capozzi
