### ISSUE TITLE
[3002] tag residenza doppio 

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2557]
Buonasera in riferimento a #2484 per il comune di GHEDI in PRODUZIONE idOperazioneANPR 480313898 
sono tornati 2 tag residenza uno con indirizzo di tipo 1 e l'altro con tipo indirizzo 10, mi aspettavo solo il primo tag relativo all'indirizzo nel comune di residenza.

il problema c'è solo per questo componente della famiglia.

**Comment by Hdemografici** [comment]
aggiungo anche che il secondo tag residenza con tipo indirizzo 10 è riferito al comune precedente

**Comment by ncapozzi** [comment]
Buonasera,
stiamo verificando.

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare

**Comment by Hdemografici** [comment]
tutto bene
grazie
