### ISSUE TITLE
WSA006 - mutazione residenza estera RIF #2555

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2558]
Dobbiamo modificare la residenza estera dei soggetti della famiglia aire (ovviamente già esistente)
Abbiamo usato il servizio A006 con tipo mutazione 2.
Dove sbagliamo?
Grazie sempre per la fattiva collaborazione

**Comment by ncapozzi** [comment]
Se tutta la famiglia AIRE cambia l'indirizzo dovete utilizzare il WS 5001 con le stesse modalità di un cambio di residenza dell'intera famiglia in Italia.
