### ISSUE TITLE
Registrazione vedovanza 

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#256]
Buongiorno, siamo del comune di Bologna e stiamo lavorando in TEST sul C.F. BBISLM56A41Z236W

Via WS non riusciamo a registrare la vedovanza e riceviamo l'errore bloccante 999 "Operazione non effettuabile". (allego richiesta e vostra risposta)

Anche con la WA non riusciamo a registrare la vedovanza perchè ci segnala che il formato della data di scadenza del permesso di soggiorno non è valida.
Nel file di caricamento vi avevamo passato come data di scadenza 9999-12-31 che per noi vuol dire "permesso di soggiorno illimitatao". 
Abbiamo provato ad eseguire una mutazione per rettifica dei soli dati del permesso di soggiorno, ma senza successo.

Esiste un range per le date?
Perchè una posizione non movimentabile NON viene segnalata fra le anomalie in fase di caricamento dei dati?

Grazie mille
[file xml.zip](https://github.com/italia/anpr/files/1193688/file.xml.zip)

**Comment by ANPRCDBO** [comment]
Abbiamo provato a registrazione della vedovanza di un'altra cittadina C.F. BRBTRS82M70D122P.

Da WS riporta lo stesso errore descritto precedentemente.
Da WA ci viene restituito il seguente messaggio bloccante: "Soggetto non presente in Agenzia delle Entrate."

Dopo vari tentativi da WA ci siamo riusciti , indicando nei dati di controllo che non sarebbe mutato il CF del soggetto.

Non comprendiamo questo lfunzionamento in quanto il tag GestioneCF non è obbligatorio.


Cosa vuol dire?

**Comment by ANPRCDBO** [comment]
P.S.  Allego l'xml di questa ultima prova

**Comment by gcarbonin** [comment]
L'utilizzo del tag gestioneCF è precisato nel paragrafo 15 delle specifiche generali ANPR. la mancata indicazione del TAG (o la sua valorizzazione  a zero) per codici fiscali non validati e/o in presenza di variazioni dei dati anagrafici dell'intestatario della scheda comporta la verifica COMUNQUE la verifica con AE dell'intestatario della scheda. L'ambiente di test (o di pre-subentro), come spiegato nel paragrafo sopra citato, è collegato ad un ambiente di test di AE e quindi il diagnostico in questione è "normale". Consigliamo di eseguire i test dei WS con gestioneCF = 3 o chiedendo l'attribuzione.

**Comment by gcarbonin** [comment]
Può darci un riscontro?

**Comment by gcarbonin** [comment]
A parte i problemi legati a gestioneCF, vedovanza e permesso di soggiorno (da WA perché da WS non abbiamo segnalazione di problemi) dovrebbe essere tutto a posto

**Comment by ANPRCDBO** [comment]
Quando abbiamo inserito l'issue avevamo già usato il valore 3 del tag GestioneCF.  pROPRIO PER QUESTA RAGIONE L'AVEVAMO APERTA.
Adogni modo il giorno dopo tutti i casi segnalati e non solo sono andati a buon fine e questo senza modificare nulla nella richiesta.

Ora il servizio ha ripreso a funzionare come prima.

Grazie
probabilmente c'erano degli aggiornamenti in corso.

**Comment by gcarbonin** [comment]
Grazie a lei
