### ISSUE TITLE
WSA006 - mutazione residenza estera RIF #2555 #2558

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2560]
Se invece è un singolo componente il servizio da utilizzare è il 5001 ?
grazie

**Comment by rinonasti** [comment]
scusi il 5005

**Comment by ncapozzi** [comment]
No se è un singolo componente che si stacca dalla famiglia AIRE di partenza per creare una nuova famiglia AIRE o inserirsi in un'altra famiglia già esistente dovete utilizzare A006
