### ISSUE TITLE
Territorio estero GERUSALEMME

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2561]
Buongiorno,

la presente per richiede se sia possibile indicare come Territorio estero AIRE il territorio GERUSALEMME o se GERUSALEMME sia un territorio al momento NON come territorio dell'indirizzo AIRE.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by ncapozzi** [comment]
Buongiorno,
GERUSALEMME è censito nella tabella stati di ANPR con il codice 325 e può essere utilizzato per indicare la residenza estera. Non può essere utilizzato come stato estero di nascita.

N. Capozzi
