### ISSUE TITLE
ERRORE - Immigrazione da altro comune subentrato

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2562]
Buonasera COMUNE DI CASERTA

ES101 Identificativo soggetto attribuito da ANPR non presente o scheda archiviata     
EF054 I soggetti devono appartenere alla stessa famiglia
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-16 16:55:03 , idOperazioneANPR 481767656

potete cortesemente darci un help

**Comment by ncapozzi** [comment]
Buongiorno,
il soggetto che state cercando di spostare è cancellato in ANPR. Verificate se dovete effettuare un reiscrizione indicando l'idsoggettoANPR della scheda cancellata nelle generalità

N. Capozzi
