### ISSUE TITLE
ISTAT non corretto - TRIVENTO (CB)

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2563]
Buongiorno,
e stata richiesta CIE per una cittadina nata a TRIVENTO (CB) il 6/12/1970 e a seguito di questo è emerso che il codice ISTAT associato al periodo storico è afferente al periodo storico precedente e in contrasto con quanto riportato dalla tabella comuni
TRIVENTO (CB): dal 1861 al 2/3/1970 ISTAT 070131
TRIVENTO (CB): dal 3/3/1970 ISTAT 070081
Impostando la richiesta di emissione nel campo luogo nascita il dato che compare è TRIVENTO 070131
La collega ha ovviato forzando il dato. E' possibile effettuare verifica?
ID ANPR 107199143 

UPI Torino

**Comment by lorbia** [comment]
Salve la posizione anagrafica della cittadina in ANPR è congruente sia per il dato corrente che per lo storico.
L'emissione della CIE attiene ANPR solo per la parte di estrazione dei dati anagrafici e per la verifica dello stato del codice fiscale validato ed allineato con AE.
Tutto il resto del processo è in carico al Poligrafico Zecca dello Stato per cui suggeriamo di rivolgersi a loro per il problema riscontrato d'incongruenza del comune di nascita.
Saluti.

**Comment by lorbia** [comment]
Chiudo questa isseu, per qualsiasi ulteriore dubbio su questo argomento è possibile aprirne una nuova citando questa.

Saluti.
