### ISSUE TITLE
[4001] - Errore EN179

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2564]
Buonasera,
inserendo una richiesta per servizio 4001 rientra subito l'errore EN179 sebbene non ci siano operazioni in sospeso.
Comune di Lucera
Halley Informatica
Arditi Alessandro

Risposta
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta4001 xmlns:a="http://sogei.it/ANPR/4000estrazione">
            <a:rispostaKO>
                <testataRisposta>
                    <idOperazioneComune>20210317145729327</idOperazioneComune>
                    <codMittente>071028</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>4001</operazioneRichiesta>
                    <dataOraRichiesta>2021-03-17T14:57:29</dataOraRichiesta>
                    <idOperazioneANPR>482689289</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN179</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Richiesta non effettuabile: e' presente una richiesta dello stesso tipo non ancora lavorata &#13;
</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:rispostaKO>
        </a:Risposta4001>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by amollicone1982** [comment]
4001 sbloccato
