### ISSUE TITLE
ERRORE E003

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2565]
Comune CASERTA - PROD
quale è il significato di questo errore? 
è riferito al singolo operatore?

Grazie

**Comment by mttfranci** [comment]
Si tratta di una consultazione 3002?
Dovrebbe essere relativoad una ricerca per la quale sono stati trovati troppo soggetti e sarebbe opportuno restringere con criteri più restrittivi.
Se ci fate avere un ID operazione ANPR verifichiamo.
Saluti.

**Comment by rinonasti** [comment]
ok grazie una ricerca su webapp con solo cognome e nome 
risolto
