### ISSUE TITLE
MODIFICA COGNOME SOGGETTO DECEDUTO

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#2566]
Soggetto: Identificativo scheda attribuito da ANPR: 44137500 - Identificativo scheda attribuito dal Comune: 56174
In seguito a decesso risulta una discordanza relativa al cognome, pertanto occorre rettificarlo 
da VAN LEE[N]WARDEN 
  a VAN LEE[U]WARDEN
Grazie
Filippo Asaro
0923 993382

**Comment by rvinzani** [comment]
Si può procedere con l'annullamento della cancellazione (op. n. 238953344), modificare anagrafici (ad una data decorrenza antecedente al decesso) e poi effettuare nuovamente la cancellazione per decesso
