### ISSUE TITLE
[5012] annullamento in errore

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2567]
Ambiente di produzione, comune di Bologna

Tentando di annullare la mutazione 5005 di ID ANPR 360340952 abbiamo il solito errore "EN077 L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa" (id operazione annullamento 484426083)

Abbiamo annullato tutte le altre operazioni che risultavano per il soggetto nella webapp ma l'errore persiste.
Qual è l'operazione che blocca ? 

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
c'è un mutazione famiglia/convivenza idoperazione 469072910 effettuata sulla famiglia id 48221008 alla quale il cittadino deve ritornare.

N. Capozzi
