### ISSUE TITLE
[7002] Comune di SENALE (comune soppresso e ricostituito in SENALE-SAN FELICE) - cod. catastale e data di cessazione - tabelle di decodifica

### ISSUE THREAD

**Issue by LetiziaDev** [italia/anpr#2568]
Non sono un utente dei comuni, sto solo cercando di validare i dati che ho scaricato dall'ultima versione della tabella dei comuni (12/03/2021) almeno per le unità successive al 1950. Ho cercato da diverse fonti ma in nessuna viene specificato esattamente il codice catastale del soppresso comune di Senale (BZ). Il comune costituito dalla fusione di Senale e San Felice sembra aver ripreso il codice I603 proprio da SENALE. Nella tabella di decodifica però appare come ND anche per la riga che termina il 18/09/1974, data di soppressione e ricostituzione.
A tal proposito la sequenza forse dovrebbe terminare il 17/09/1974 e ricominciare il 18/09 in Senale-San Felice con lo stesso codice catastale (San Felice aveva il codice H837 e anch'esso a mio parere dovrebbe terminare il 17/09 e non il 18/09/1974).
Come si fa a chiedere la correzione? Grazie

**Comment by LetiziaDev** [comment]
Mi permetto di segnalare anche il presumibile errore nella datacessazione del soppresso comune di Filago (ID riga 11225) con codice catastale D588, dovrebbe essere 25/01/1928 e non 26/01/1928 data in cui confluisce nel comune di Marne fino al cambio denominazione Marne --> Filago (10/09/1958)

**Comment by lorbia** [comment]
Salve la gestione della classificazione dei comuni è responsabilità dell'Istat. Chiunque ritenga di aver riscontrato degli errori e voglia segnalarli può scrivere alla casella ambienteterritorio@postacert.istat.it, della Direzione Centrale per le statistiche ambientali e territoriali. Nel caso fossero recepite, sarà poi cura dell'ente comunicarci le conseguenti modifiche.
Saluti.

**Comment by LetiziaDev** [comment]
Salve, a quanto mi risulta l'Istat non si occupa dei codici catastali, che restano di competenza Agenzia delle Entrate. E' possibile avere un contatto per segnalare l'anomalia?
Inoltre, per quanto riguarda le date di chiusura, l'Istat rilascia file in cui la data di cessazione corrisponde con la data di costituzione del nuovo periodo, mentre nel file messo a disposizione in ANPR di norma non vi è questa sovrapposizione.
Si prega quindi di verificare sia la correttezza di Senale (ID 22632), sia di Filago (ID riga 11225), le uniche due che generano una sovrapposizione di date.
Grazie

**Comment by lorbia** [comment]
Per quel che riguarda il codice catastale è possibile contattare la direzione centrale Archivio anagrafico dell'Agenzia delle Entrate.
Per il dubbio sulle date di cessazione come detto è possibile scrivere alla casella ambienteterritorio@postacert.istat.it.
Saluti.
