### ISSUE TITLE
Seconda parte password smart card

### ISSUE THREAD

**Issue by LatiniM** [italia/anpr#2569]
Salve,
dalla prefettura abbiamo ricevuto le smart card e la prima parte di password, pin e puk,
Nell'email di attivazione della card abbiamo ricevuto solamente la seconda parte del pin e puk. Si richiede la seconda parte della password che permette anche l'attivazione dell'ambiente di Test per la nostra software house che segue il nostro gestionale.
Il codice seriale della smart card è il seguente: 0420480175160007.
L'indirizzo email per l'invio della password è questo: scale@comune.sirolo.an.it
Grazie

Latini Monica
Comune di Sirolo

**Comment by Leonforte** [comment]
Ricordando che l'accesso alla web app ANPR è consentito esclusivamente tramite smart card, informiamo che quanto richiesto è stato inviato a scale@comune.sirolo.an.it
Buon lavoro,  saluti
