### ISSUE TITLE
Aggiornamento carta di circolazione - Problema nell'indicazione del numero civico

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#257]
Buongiorno,
pochi giorni fa un cittadino ci ha portato la comunicazione che gli è stata inviata dalla Motorizzazione a seguito del cambio di residenza, segnalandoci che il numero civico è stato indicato in modo errato:
l'indirizzo esatto in anagrafe e ANPR è 
VIA D. ALIGHIERI n. 4 int. 3

mentre nella comunicazione i due numeri sono stati uniti, indicando quindi l'indirizzo - errato - di  VIA D. ALIGHIERI n. 43
(la comunicazione con il nominativo della persona è già stata inviata per mail)

Potete verificare cosa succede nella comunicazione tra ANPR e MOTORIZZAZIONE?
Segnaliamo anche che prima del subentro i dati dell'interno NON veniva trattato nelle comunicazioni MIT, tanto che nel caso di cambio di residenza all'interno di uno stesso stabile (quindi con n. civico invariato) la variazione NON veniva inviata dal Comune.

Se i dati non vengono recepiti correttamente dalla MOTORIZZAZIONE potrebbe essere che tutte le comunicazioni inviate fino ad ora (dopo il subentro) non sono corrette?

Aspettiamo vostre indicazioni in merito
Grazie e a presto
Patrizia Saggini
Monia Pellizzari

**Comment by rvinzani** [comment]
Abbiamo verificato che la notifica inviata da ANPR a Motorizzazione riportava correttamente l’indirizzo.
Abbiamo quindi avvisato i nostri riferimenti di Motorizzazione dell’errore che ci hanno assicurato che lo hanno rimosso e provveduto a far ripartire il processo per la stampa e l'invio del nuovo tagliando all'utente.

**Comment by luca-teamdigitale** [comment]
Grazie mille.

Potete per cortesia chiedere ai vostri riferimenti in Motorizzazione qualche informazione sulla causa dell'errore, e che accorgimenti hanno intenzione di attuare affinche` errori simili non si ripetano in futuro?

**Comment by psaggini** [comment]
Grazie delle info!
Forse bisognerebbe chiedere alla Motorizzazione di controllare se lo stesso errore si è verificato anche nel periodo immediatamente successivo al subentro (possono esserci altri tagliandi sbagliati già inviati, di cui i cittadini non si sono accorti dell'errata indicazione).

**Comment by luca-teamdigitale** [comment]
Un chiarimento nei confronti del mio commento https://github.com/italia/anpr/issues/257#issuecomment-319938627 onde evitare che scaturiscano dubbi: Ho chiesto un favore, consapevole che la richiesta esuli dalle mansioni previste nell'ambito di ANPR. Se in alternativa volete girarmi in privato i vostri riferimenti in Motorizzazione sono ben contento di controllare in prima persona.

**Comment by luca-teamdigitale** [comment]
Motorizzazione ci ha risposto. Quoto dalla loro mail:

è stato diagnosticato il problema sw che provocava un’errata registrazione del numero civico nei casi in cui veniva trasmesso seguito da un numero di scala o di interno.  Ciò spiegava l’errore segnalato dal comune di  Anzola nell’Emilia.

Nella stessa giornata l’anomalia è stata rimossa e sono stati estratti i dati degli altri cittadini coinvolti dal malfunzionamento.  Per ciascuno di essi è stata rielaborata la notifica di variazione di residenza inviata dal comune e generato il tagliando con l’indirizzo corretto da apporre sulla carta di circolazione.
 
In caso di mancato ricevimento del nuovo tagliando, i cittadini interessati possono contattare il nostro call center al n. 800232323 per verificare l’avvenuta spedizione ed eventualmente richiedere una ristampa.
