### ISSUE TITLE
Seconda parte password 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2570]
Buongiorno,
COMUNE DI CASERTA 061022
Un operatore (NNLNNL.....) ha ricevuto con la smart card la prima parte di PIN PUK e PASSWORD 
nella mail ha ricevuto solo seconda parte PIN seconda parte PUK ma NON LA SECONDA PARTE DELLA PASSWORD.
Oggi, dopo segnalazione ha ricevuto nuovamente la stessa mail con la mancanza della seconda parte della password per l'accesso alla webapp con codice fiscale.
Grazie

**Comment by Leonforte** [comment]
Ricordando che l'accesso alla web app ANPR è consentito esclusivamente tramite smart card, informiamo che quanto richiesto è stato inviato a antonella.ianniello@comune.caserta.it
Buon lavoro, saluti
