### ISSUE TITLE
validazione codice fiscale

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2571]
Comune di Caserta
buongiorno
con quale procedura si cambia validità codice fiscale da 9 a 1
Grazie

**Comment by azabatta** [comment]
Buonasera, 
l’aggiornamento indicato comporta che ANPR verifichi la validità del codice fiscale e dei relativi dati anagrafici in Agenzia Entrate.
Si effettua tramite il servizio di “Mutazione dati scheda” (ws 5008) codice mutazione 1  (dati anagrafici/codice fiscale) valorizzando 0 nel campo gestioneCF della sezione “dati di controllo”.
