### ISSUE TITLE
certificazioni e visure da Anpr richieste da privati

### ISSUE THREAD

**Issue by Barby0109** [italia/anpr#2573]
Buongiorno,
visto l'avviso di febbraio su portale Anpr riguardante il fatto che stanno per essere adottate le convenzioni per accesso in Anpr da parte di altre Pa, per noi sarebbe urgente sapere anche:
verrà attivata contestualmente anche la possibilità di certificazioni richieste direttamente su portale Anpr dal singolo cittadino, per se stesso e la propria famiglia,(come previsto dai decreti del 2020, in attesa di Dpcm)   e  soprattutto è possibile sapere se  questa possibilità sarà consentita anche  a terzi privati (notai; avvocati; banche aziende) che necessitano di certificati o di verifiche su autocertificazioni a loro presentate dai cittadini (soprattutto se vogliamo che prenda piede l'uso dell'autocertificazione prevista anche verso i privati dal decreto semplificazione)? 
Vista emergenza Covid e in generale per sgravare gli uffici abbiamo urgenza di attivare un servizio di certificazione Online offertoci da softwarehouse esterna per il servizio di certificati ai privati (con dati desunti da Anpr, muniti di timbro digitale, accesso con Spid e CIE). Ma se gli adeguamenti che state implementando in Anpr sono già indirizzati anche ai privati il nostro servizio sarebbe di fatto superato. 
Grazie, saluti.
Barbara

**Comment by FilippoPapi** [comment]
buongiorno
si è previsto che venga attivata la possibilità di certificazioni richieste direttamente su portale Anpr dal singolo cittadino, per se stesso e la propria famiglia, e probabilmente anche per terzi. ma tutto ciò è subordinato all'emissione di un apposito decreto da parte del Ministero dell'Interno. pertanto non vi posso dare una tempistica.
cordiali saluti
