### ISSUE TITLE
Eliminazione permesso di soggiorno

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2574]
Salve, 
il Comune di Montalto Dora non riesce con l'eliminazione dati a bonificare delle situazioni che si sono protratte con il tempo di errati inserimenti dati nelle pratiche di iscrizione. 
Hanno oltre 30 posizioni da sanare con individui a cui hanno registrato un titolo di soggiorno "Altro titolo di soggiorno" e che nel corso del tempo sono stati interessati da diverse operazioni in Anpr. 
Non potendo annullare tutto quello che hanno a ritroso, hanno tentato di ricorrere al servizio di Eliminazione dati ma ricevendo la validazione :
L'operazione di revoca e' possibile solo a valle del subentro (Codice: EN505)
C'è qualcosa che possono tentare dalla WebApp o qualche via alternativa al fine di eliminare i permessi di soggiorno inseriti erroneamente? 

Grazie e buon lavoro

**Comment by rvinzani** [comment]
Come anche da voi verificato è possibile eliminare i permessi di soggiorno inviati al subentro se non sono state effettuate ulteriori operazioni. I dati inseriti erroneamente possono solo essere modificati

**Comment by mrabuano** [comment]
L'Ente vuole eliminare i dati inseriti erroneamente. 
Provando a modificare non è possibile impostarli a null in quanto scatta la validazione sui campi obbligatori. 

Come può eliminare questi dati dalle 30 anagrafiche?

**Comment by rvinzani** [comment]
Non è possibile eliminare i dati se non dopo il subentro prima di aver effettuato ulteriori operazioni. In alternativa si possono annullare le operazioni successive al subentro e eliminare i dati. Chiudo la issue. Se fossero necessarie ulteriori informazioni può riaprire una nuova issue che faccia riferimento a questa
