### ISSUE TITLE
ISCRIZIONE PER RICOMPARSA DA IRREPERIBLILITA'

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2576]
Buonasera COMUNE CASERTA 061022 - PROD
Dobbiamo iscrivere un soggetto che in altro comune subentrato risulta cancellato per irreperibilità.
Otteniamo il seguente errore utilizzando il WS1002 motivo iscrizione 5
EN185 idSchedaSoggettoANPR 000000076784415 non presente o dati anagrafici incongruenti
data 2021-03-22 14:55:47 , idOperazioneANPR 486646981

se utilizziamo motivo iscrizione 9 invece:
EN190 Soggetto XXXXXXXXXXXXXXXX, YYYYYY, ZZZZZZ,  28/05/1980, 76784415 cancellato in ANPR, per riscriverlo indicare idSchedaSoggettoANPR @ nella richiesta</testoErroreAnomalia>
EN527 data 2021-03-22 14:54:08 , idOperazioneANPR 486644730
Quale procedura occorre utilizzare
Grazie

**Comment by rvinzani** [comment]
Abbiamo aperto il ticket 22502293 con il quale risponderemo. Vi preghiamo per le volte successive di utilizzare per questo tipo di problematiche il servizio di assistenza ANPR al n. 800863116
