### ISSUE TITLE
[Errore Anpr Cod: EN469 - Il soggetto risulta iscritto anche nel comune] Variazioni resposabile convivenza

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2577]
Comune di Montepulciano PRODUZIONE

Per il soggetto in questione è stata fatta una mutazione di residenza con provenienza da ROMA in data 14.03.2021, la quale è andata a buon fine.
In un secondo momento il comune sta provando a cambiare il resposabile della convivenza, ma riporta il seguente errore:

1 Errore Anpr Cod: EN469 - Il soggetto risulta iscritto anche nel comune di ROMA Con data iscrizione 08-03-2019 - Cognome: XXXXX Nome: XXXXXX CF: XXXXXXXXX Validità CF: Validato -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-15 10:25:31 , idOperazioneANPR 480163490 - Cognome: XXXXXXX Nome: XXXX CF: XXXXXX Validità CF: Validato -
3 Errore Anpr Cod: EN395 - per il tipo di mutazione 1 saranno modificati soltanto i dati relativi a tutore/responsabile - Cognome: XXXX Nome: XXXXX CF: XXXXXXXX Validità CF: Validato -

ID ANPR SOGGETTO:  100317370
ID ANPR CONVIVENZA: 15246815

**Comment by FilippoPapi** [comment]
buonasera
github è una comunità di discussione, per affrontare problemi specifici come questo vi  preghiamo di utilizzare il servizio di assistenza ANPR al n. 800863116
cordiali saluti
