### ISSUE TITLE
Residenza Temporanea

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2578]
Buongiorno,
abbiamo visto che in ANPR compare la voce "Residenza temporanea". Come si utilizza tale sezione? Come Comune di Ravenna, per esempio, non abbiamo un flusso che invii i dati dei nostri temporanei.

In attesa di riscontro,
ringraziamo per l'attenzione e porgiamo cordiali saluti.

**Comment by rvinzani** [comment]
La gestione dei temporanei è per il momento prevista solo dalla web App di ANPR, non sono quindi previsti dei web services di integrazione con il gestionale. Nell'applicazione web è possibile inserire/cancellare residenti temporanei nel vostro comune che risiedono stabilmente in altri comuni

**Comment by katiavacchi** [comment]
Ci sono istruzioni in merito, cioè su come procedere per l'inserimento?
Grazie.

**Comment by rvinzani** [comment]
Sulla pagina della funzione c'è un punto interrogativo che rimanda ad una pagina di istruzioni. Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
