### ISSUE TITLE
Comune di Ancona- Aggiornamento carte di identità rilasciate dai consolati

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2579]
Abbiamo rilevato che le carte di identità rilasciate dai consolati non vengono aggiornate automaticamente in ANPR come invece succede con il rilascio tramite il sistema CIE ON LINE. Sarà possibile fare un'integrazione anche fra questi sistemi o in alternativa fornire al Comune una notifica in ANPR per l'aggiornamento dei dati? Ferretti Laura

**Comment by ncapozzi** [comment]
Buonasera,
siamo in attesa di ricevere dal Poligrafico le comunicazioni di emissione/annullamento CIE rilasciate dai Consolati per poterle visualizzare in ANPR come quelle dei Comuni.
Il Poligrafico sta già lavorando in questo senso.

N. Capozzi
