### ISSUE TITLE
Aggiornamento comuni sardi - problema comunicazione donazione organi

### ISSUE THREAD

**Issue by moniapellizzari** [italia/anpr#258]
Buongiorno, 
vorremmo segnalare un problema rispetto i Comuni della Sardegna, ovvero facendo controlli su un cittadino che doveva rifare la carta d’identità, abbiamo verificato che il soggetto è nato a San Gavino Monreale che secondo la tabella ANPR è attualmente in provincia di Medio-Campidano mentre contattando il Centro trapianti di Roma ci hanno confermato che hanno già adeguato la tabella comuni con le nuove province sarde quindi San Gavino Monreale per loro è in provincia di “Sud Sardegna” cod. istat 111062, come tanti altri comuni sardi.
Pertanto per quanto concerne il rilascio di carta d’identità con donazione organi, si verificano discordanze che non permettono l’invio della comunicazione al centro trapianti.
Si chiedono delucidazioni in merito.
Cordiali saluti.
Monia Pellizzari
Comune di Anzola dell’Emilia

**Comment by gcarbonin** [comment]
Salve. Come già detto a fronte di domande simili, l'adeguamento delle tabelle non può essere effettuato autonomamente da ANPR senza che almeno Agenzia delle Entrate abbia adeguato le proprie: non si riuscirebbe ad attribuire nemmeno un codice fiscale. L'intervento è previsto per fine settembre.
