### ISSUE TITLE
Consultazione da webapp diversa da WS3002

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2580]
Buonasera
COMUNE DI CASERTA - PROD
Da webapp consultiamo un cittadino di altro comune subentrato (ricerca nazionale SI) ma la ricerca non produce alcun risultato errore EN122.
Mentre, se la stessa ricerca viene fatta attraverso il servizio  3002 riporta correttamente  la scheda anagrafica del cittadino.
Come è possibile ?
Grazie

**Comment by rvinzani** [comment]
Poichè per questo tipo di segnalazione ci occorrono i dati relativi al soggetto le risponderò via email. Chiudo la issue.
