### ISSUE TITLE
Rettifica tipo famiglia

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2581]
Salve, 
il comune di Silvi ci ha esposto il seguente problema, in pratica si sono accorti che due famiglie sono state trasmesse in ANPR, nel file di subentro, con una errata tipologia, in quanto si tratta in realtà di due convivenze.
Si trovano pertanto in questo momento con la necessità di "rettificare" la tipologia di queste due famiglie.
Abbiamo fatto un tentativo "esplorativo" sulla Web App di effettuare una mutazione famiglia/convivenza ma come immaginavamo, non abbiamo trovato nessun modo per modificare la tipologia da famiglia in convivenza.
Vi chiediamo, esiste una modalità operativa per effettuare questa operazione, con i WS o dalla Web App, tenendo anche conto delle varie decorrenze che devono restare quelle delle famiglie originali? Oppure il comune deve contattarvi per consentirvi di risolvere l'operazione intervenendo in qualche modo direttamente sui dati?
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
Gent.le sig. Mucciarelli, non è previsto questo tipo di modifica. Le due convivenze se non presenti devono essere create con apposito servizio e successivamente può modificare la residenza delle persone in questione in tali convivenze.

**Comment by Amucciarelli74** [comment]
Va bene, la ringrazio, contatteremo il cliente e provvederemo con loro ad effettuare le operazioni da voi indicate.
Vi riporteremo eventuali osservazioni del cliente sullo stato dei dati a variazioni effettuate, e nel caso ci confronteremo di nuovo.
Grazie del cortese riscontro,
cordiali saluti.
Giuseppe Mucciarelli, TINN srl.
