### ISSUE TITLE
Cambio tipo utente/operatore

### ISSUE THREAD

**Issue by slastrucci** [italia/anpr#2582]
Buongiorno,

vorrei sapere come poter modificare il tipo utente ad alcuni colleghi già abilitati ad ANPR.
In questo momento sono l'unico amministratore locale della sicurezza (ALS) ma vorrei nominarne almeno un altro nei casi in cui sono assente.

Graie.

Lastrucci Stefano

**Comment by Leonforte** [comment]
Salve, è possibile agire dalla console di sicurezza della web app ANPR nella sezione gestione utenti. Una volta all'interno della sezione, utlizzando la voce Modifica/Visualizza del menù di sx e premendo il tasto ricerca è possibile avere la lista di tutti gli utenti del comune. Selezionando successivamente la lente a dx dell'utente prescelto e premendo il tasto Avanti è possibile accedere alla funzionalità di modifica dei profili. Può far riferimento al capitolo 9 della guida che allego, buon lavoro, saluti
[Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro v.3.pdf](https://github.com/italia/anpr/files/6204765/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.v.3.pdf)

**Comment by slastrucci** [comment]
Ho provato a seguire le istruzioni riportate nel capitolo 9 del manuale ma il dettaglio dell'utente è diverso da quello indicato nella guida. Facendo parte di un comune già  subentrato ormai da diversi anni non vedo i questi profili:
- Ammnistratore locale della Postazione (ALP)
- Ammnistratore locale della Sicurezza (ALS)
- Sindaco o Commissario (ASC)

A loro posto vedo le voci:
- Operatore Privilegiato con Smart card
- Operatore Comunale di Consultazione
- Operatore Comunale di Estrazione
- Operatore Comunale di Certificazione
- Operatore Comunale di Cancellazione
- Operatore Comunale di Mutazione
- Operatore Comunale di Annullamento
- Operatore Comunale di Iscrizione
- Operatore Carta di Identità
- Operatore Comunale Servizi di Utilità
- Operatore Comunale di Subentro
- Operatore Comunale Servizi di Amministrazione
- Operatore Comuale Supervisore
- Sindaco o Commissario

Anche assegnando tutti i permessi l'utente rimane di tipo "operatore".

Come posso fare a nominare altri ALS?
