### ISSUE TITLE
Certificazione non corretta

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2584]
Buongiorno
per i soggetti che risiedono ad un indirizzo con interno "secondario" la certificazione non è viene emessa correttamente: non viene riportata la lettera presente nel campo secondario.
Es.: id soggetto 28115764 indirizzo Via Tommaso Grossi, 14 sec B; id soggetto 28262732 Via Saluzzo 91 sec E.
Cordiali saluti
Ufficio Procedure Informatiche

**Comment by rvinzani** [comment]
In accordo con il Ministero dell'interno è stato deciso che non tutti gli innumerevoli dati presenti nell'indirizzo vengano riportati sulla certificazione.

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessarie maggiori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
