### ISSUE TITLE
Correzione: data di nascita e CF

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#2585]
Comune di Montoro (AV)

Sitamo tentando senza successo di correggere data di nascita (e di conseguenza CF) del cittadino 87037723

Data corretta: 22-11-1999
Data errata e attualmente presente su ANPR: 22-07-1995

La questione è colplicata dal fatto che il cittadino risulta iscritto anche nel comune di BARI Con data iscrizione 28-03-2017 (Codice: EN471)

**Comment by azabatta** [comment]
Buonasera
github è una comunità di discussione, per la richiesta  è stato aperto ticket 22552723 con il quale risponderemo. Cortesemente per problematiche di questo tipo vi preghiamo in futuro di utilizzare il  servizio di assistenza ANPR al numero verde 800863116.
Cordiali saluti
