### ISSUE TITLE
Soggetto non individuato in AT - Codice fiscale NON variato  (Codice 12)

### ISSUE THREAD

**Issue by Rianoanagrafe** [italia/anpr#2586]
Comune RIANO Produzione

In Anpr esiste un individuo id 109172043 con un CF collegato, quindi non l'attuale, ma il precedente secondo quanto verificato e  corretto con AE.

Si tenta di effettuare una Mutazione dati variando il Cognome e il CF nel tentativo di passare da quello precedente a quello attuale ed allineare la situazione di ANPR a quella di AE.

Il risultato è l'errore:
 1 Errore Anpr Cod: EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12) 
 2 Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-29 11:35:29 , idOperazioneANPR 494078283 (Codice: EN527) 

Tentando la risoluzione disallineamenti con AE, confrontando le anagrafiche di ANPR e quelle di AE e scegliendo il Conferma AE si ottiene lo stesso errore.

Spuntando Collega Codici Fiscali si ottiene :
 Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12)

Pur effettuando una prova ed inserendo il controllo sul CF nella mutazione tutti i dati con iscrizione senza validazione non è possibile procedere

Come è possibile allineare i dati Anpr a quelli di AE ?
cordiali saluti
Giuseppina Napoleone
Ufficiale di Anagrafe comune di Riano (RM)
06901373350
06901373208

**Comment by azabatta** [comment]
Buongiorno,
github è una comunità di discussione, per la richiesta è stato aperto ticket 22560260 con il quale risponderemo. Cortesemente per problematiche di questo tipo vi preghiamo in futuro di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
Cordiali saluti
