### ISSUE TITLE
Notifiche non prodotte in test

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2588]
Ambiente di test

Ieri pomeriggio verso le 16:25 ho iscritto nel comune Manerbio due cittadini provenienti dal comune di Poggio a Caiano con i servizi 5001 e 5005 ( operazioni 35669016 e 35669034).

Ho poi eseguito nella webapp di Poggio a Caiano due modifiche altri dati (operazioni 35669140 e 35669137).

Stamane ho richiesto su Poggio a Caiano con il servizio 4005 (operazioni 36667324, 36667326, 36667323, 36667325) le notifiche prodotte negli ultimi due giorni ma non ritorna nulla, né le N010 di emigrazione né le NRIS relative alle operazioni fatte da webapp .
Da webapp inoltre non risulta alcuna notifica prodotta per il comune di Poggio successiva al 17/3.

Potete verificare ?

Grazie

**Comment by lorbia** [comment]
Chiudo questa issue per eventuali altri problemi di questo tipo è possibile aprirne una nuova citando questa.
