### ISSUE TITLE
[1002] iscrizione con domicilio digitale

### ISSUE THREAD

**Issue by busaster** [italia/anpr#259]
Salve,
in ambiente di produzione (comune di Nardò) siamo stati bloccati durante l'iscrizione di un soggetto **dall'errore EHR89 : I dati relativi al domicilio digitale al momento non possono essere indicati**

Non sarebbe meglio trasformare questo errore in un avviso non bloccante ?

In tal modo il gestionale rimarrebbe compatibile con i domicili digitali quando saranno gestiti.

**Comment by gcarbonin** [comment]
Non ci sono regole definite al momento per la gestione del domicilio digitale. Per questo motivo questa informazione non può essere accettata. Per altro questo errore è sempre stato bloccante.
