### ISSUE TITLE
SERVIZIO WSA001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2590]
Buonasera, COMUNE DI CASERTA - PROD
Abbiamo inviato una iscrizione per nascita AIRE (WSA001) viene fuori il seguente  errore:

errore EAA30 - Codice fiscale individuato in AT con dati anagrafici diversi o indirizzo diverso
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-30 17:18:20 , idOperazioneANPR 495615894
Potreste, cortesemente verificare e darci un aiuto.

Domanda per il servizio WSA006 in assenza del codice fiscale questo viene calcolato da AT ?
Grazie per la fattiva collaborazione.

**Comment by rvinzani** [comment]
Chiudo la issue. Nel caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
