### ISSUE TITLE
WS5005 - Immigrazione da comune subentrato

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2591]
Buongiorno COMUNE DI CASERTA - PROD
Inviamo una immigrazione da comune subentrato utilizzando il servizio ws5005, per ogni singola persona,  non conoscendo se nel comune di provenienza resta ancora qualche individuo.

EN220 Per trasferire tutti i componenti di una famiglia in una nuova utilizzare il servizio di mutazione residenza 
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-03-31 12:35:11 , idOperazioneANPR 496357862   
Perché evidenzia questo tipo di errore?
Grazie

**Comment by rvinzani** [comment]
Il soggetto costituisce da solo un nucleo familiare. E' necessario quindi utilizzare la mutazione 5001-famiglia convivenza.
Si utilizza il 5005 quando parte dei soggetti di una famiglia si trasferiscono in una nuova famiglia o si associano ad una esistente o se l'intero nucleo si associa ad una famiglia esistente

**Comment by rinonasti** [comment]
OK
Ma tempo addietro utilizzando ws5001 per un singolo che si spostava creando una nuova famiglia a Caserta si portò con se tutti i componenti, anche quelli che dovevano restare nell'altro comune.

**Comment by rvinzani** [comment]
Infatti, ma nel caso segnalato il soggetto è l'unico componente della famiglia

**Comment by rinonasti** [comment]
ok grazie
