### ISSUE TITLE
Cambio formato Archivio Comuni

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2593]
Buongiorno,
nell'ultimo archivio dei comuni pubblicato (aggiornamento 30 marzo 2021) ci sono alcune difformità rispetto al formato precedentemente utilizzato:

1) il separatore è il punto e virgola ";" anzichè la virgola "," 
2) i campi numerici (ID, IDPROVINCIA) sono scritti come stringhe, quindi tra doppi apici
3) i campi vuoti sono indicati con ben 6 doppi apici

Si tratta di un errore o questo sarà il nuovo formato che verrà usato per tutte le prossime pubblicazioni?

Grazie,
Tiziano Pavan

**Comment by lorbia** [comment]
Salve il formato corretto resta quello con la virgola "," come separatore.
E' già stata pubblicata la versione corretta.
Chiudo questa issue, per problemi analoghi è possibile aprirne una nuova facendo riferimento a questa.
Grazie.
