### ISSUE TITLE
Cambio formato Archivio Comuni (2)

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2596]
Buongiorno,
rispetto a quanto riportato in #2593, il nuovo file pubblicato risolve i problemi segnalati al punto 1 e al punto 3 ma non quello al punto 2.
I campi ID e IDPROVINCIA continuano ad essere presenti nel file csv come campi stringa (quindi tra doppi apici) contrariamente alle precedenti pubblicazioni nelle quali comparivano come campi numerici.

Cordiali saluti,
Tiziano Pavan

**Comment by lorbia** [comment]
E' disponibile il file aggiornato che risolve anche il punto 2.
Grazie della segnalazione.
Saluti.
