### ISSUE TITLE
A006 - Mutazioni dati AIRE - residenza

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2597]
Buonasera,
Intendiamo modificare i dati di residenza estera :
EF007 Intestatario della scheda famiglia/convivenza gia' presente
EN527
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-04-02 17:17:08 , idOperazioneANPR 498598220
Grazie

**Comment by azabatta** [comment]
Buonasera,
il servizio da utilizzare quando si sposta tutta la famiglia (anche se composta da un solo componente come in questo caso) è  il ws 5001 come per i residenti in Italia.
Il ws A006 si utilizza se il soggetto AIRE cambia residenza ed entra a far parte di una famiglia AIRE già esistente oppure se un componente di una  famiglia AIRE si stacca per  creare una nuova famiglia.
