### ISSUE TITLE
ISCRIZIONE PER NASCITA - WS1001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2598]
Buonasera,
COMUNE DI CASERTA - PROD
Nel caso in cui la madre non sia residente in Italia e se ne conosce il cognome e nome come va indicato affinché non dia errore
"EN143 - SOGGETTO MADRE NON IN ANPR"

data 2021-04-06 18:44:42 , idOperazioneANPR 500616554

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
nella richiesta avete indicato attribuzioneFamiglia=3 cioè quella della madre. In questo caso la madre deve stare in ANPR e quindi dovreste indicare anche CF e idsoggettoANPR come avete fatto per il padre.
Se invece la madre non è in ANPR allora non potete indicare attribuzioneFamiglia= 3

N. Capozzi
