### ISSUE TITLE
ISCRIZIONE DA COMUNE NON SUBENTRATO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2599]
Buongiorno,
COMUNE DI CASERTA - PROD
Dobbiamo iscrivere un cittadino proveniente da comune non subentrato.
Questa persona non risulta in AE 
Come dobbiamo comportarci ?
Grazie

**Comment by rvinzani** [comment]
Potete iscriverla richiedendo il codice fiscale. Consiglio comunque di fare ulteriori indagini e di richiedere i documenti alla persona riportanti i dati anagrafici soprattutto se si tratta di stranieri perchè, ad eccezione di alcuni AIRE, tutti i i cittadini, anche rifugiati, richiedenti asilo etc. sono in genere provvisti di codice fiscale, magari numerico provvisorio. Chiudo la issue. In caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa
