### ISSUE TITLE
Utilità - Residenza temporanea

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#26]
Tramite la funzione "Residenza temporanea", in data 20/2, ho effettuato un'iscrizione nel registro di un certo soggetto e il sistema ha risposto "Operazione correttamente eseguita", ma nel file stampato non è riportato alcun ID operazione nè ID soggetto. 
Effettuando la ricerca del soggetto dalla stessa funzione, il sistema risponde "Non sono stati trovati soggetti corrispondenti ai criteri di ricerca".
Ho ripetuto l'iscrizione dello stesso soggetto in data odierna (13/3), reinserendo esattamente gli stessi dati (incluso CF) e il sistema ha consentito nuovamente l'iscrizione, riproponendo un file senza alcun ID.
Il soggetto continua a non essere reperibile in Consultazione.
Segnalo inoltre che il tasto EXPORT CSV non produce alcun risultato.
Sto sbagliando qualcosa? Grazie!

**Comment by VBocchinoTO** [comment]
Ho dimenticato di dire che ho utilizzato l'ambiente di test.
Valentina Bocchino - Città di Torino
Scusate!

**Comment by gcarbonin** [comment]
C'era un errore che è stato risolto. Può riprovare. Attendo il suo riscontro

**Comment by VBocchinoTO** [comment]
Ho riprovato e ora:
- il pulsante EXPORT CSV funziona correttamente;
- in fase di ricerca di soggetto residente in comune non subentrato, la ricerca va a buon fine soltanto utilizzando come chiave il Codice Fiscale. Tentando la ricerca con Cognome e Nome restituisce esclusivamente tutti i soggetti che hanno un ID ANPR. 
Non so se questo comportamento è voluto o meno, ma potrebbe sembrare fuorviante.

**Comment by gcarbonin** [comment]
Una ricerca per cognome e nome di soggetti che non hanno un id-anpr restituisce una lista molto lunga che potrebbe essere fuorviante: si estraggono ad esempio tutti i coniugi o tutti i genitori per i quali spesso c'è soltanto un cognome e nome.. Il codice fiscale al contrario consente di restituire un elenco "più attendibile".
