### ISSUE TITLE
[5001] errore su cambio parentela

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#260]
Corbetta, ambiente di produzione.

Buongiorno, abbiamo un problema su una famiglia per cui cerchiamo di cambiare un rapporto di parentela da convivente a marito e riceviamo l'errore: EF008 - Intestatario della scheda famiglia/convivenza assente. Abbiamo verificato anche in ANPR e l'intestatario è presente. ID OPERAZIONE ANPR 811655.

Grazie.

**Comment by cmigliardi** [comment]
Se vengono inviati tutti i soggetti componenti della famiglia (anche quelli per cui non varia il rapporto di parentela) il diagnostico non scatta.

**Comment by LucaBonini64** [comment]
Cosa vuol dire? che nel 5001 bisogna passare sempre tutti i componenti della famiglia anche se non cambiano relazione di parentela? Mi sembra pericoloso perché questa falsa variazione mi diventa ultima operazione per la scheda e mi blocca altre possibili variazioni..

**Comment by cmigliardi** [comment]
Una variazione sul grado di parentela blocca  solo successive variazione sul grado di parentela, non sull’intera scheda. (non viene bloccata la scheda del soggetto per mutazioni future 5008)

**Comment by LucaBonini64** [comment]
Mi scusi dottoressa Migliardi ma temo che stia focalizzando l'attenzione su un problema sbagliato:
1 ) nel servizio 5001 non è previsto dalle specifiche che si passino sempre tutti i componenti compresi quelli che non cambiano parentela, quindi non è accettabile la risposta "Se vengono inviati tutti i soggetti componenti della famiglia (anche quelli per cui non varia il rapporto di parentela) il diagnostico non scatta" perché sarebbe una soluzione tampone solo per questi caso.
2) mutazioni di parentela ne facciamo ogni giorno senza problemi, quindi presumo che questa famiglia abbia delle particolarità che dovreste verificare, ad esempio l'intestatario scheda (che non viene rilevato)contiene nel cognome la particella nobiliare minuscola (d'ALBA), potrebbe questo causarvi dei problemi?
3) Le variazioni successive che mi preoccupano non sono per il 5008 ma altre mutazioni all'interno della famiglia, esempio: Orazio chiede la residenza nella famiglia di Clarabella e Paperina (IS), io trasmetto il 5001 con tutte le persone così salta il diagnostico, domani mi arriva da un altro comune con decorrenza 3 giorni fa l'emigrazione o la mutazione di Paperina; quando vado a gestire le parentele per mettere Clarabella come IS a 3 giorni prima non mi da errore per il 5001 di Orazio?
Cordiali Saluti

**Comment by gcarbonin** [comment]
Mi scuso per alcune risposte:
1) problema iniziale (variazione della relazione di parentela): occorre inviare comunque l'intestatario. Questo per i necessari riscontri da parte di ANPR
2) Famiglia Orazio Clarabella e Paperina. A parte il diagnostico che "salta o non salta", Clarabella chiede oggi uno stato di famiglia e lo richiede dopo tre giorni e lo trova diverso. Cosa raccontiamo a Clarabella del tutto ignara delle operazioni "ora per allora" che sembrano una prassi corrente? 
Anche per questo problema (famiglia Disney)  chiederemo un chiarimento formale al Ministero prima di ulteriori interventi

**Comment by gcarbonin** [comment]
Sono stati modificati i controlli sulle operazioni che riguardano il nucleo famigliare. E' possibile riprovare con la nuova versione?
