### ISSUE TITLE
Compilazione sentenza in caso di Nullità

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2600]
nei casi di nullità di matrimonio (tipo 4 - annullamento della Sacra Rota) nell'oggetto Sentenza devono essere riportati gli estremi della sentenza del tribunale ecclesiastico o gli estremi della successiva deliberazione della Corte di Appello?

**Comment by rvinzani** [comment]
Credo sia una tipologia di domanda non tanto tecnica quanto normativa. Consigliamo di porre il quesito al Ministero dell'Interno o ai consulenti ANUSCA esperti in materia. Chiudo le issue. Nel caso fossero necessarie ulteriori precisazioni si prega di aprire una nuova issue che faccia riferimento a questa stessa
