### ISSUE TITLE
Adozioni in casi particolari art.44 L.184/1983

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2601]
Da più comuni ci è arrivata la richiesta di come gestire in ANPR le adozioni in casi particolari art.44 L.184/1983 (non legittimante).
La normativa prevede che i dati relativi alla paternità/maternità biologica devono rimanere (a differenza dell'adozione legittimante) e i dati relativi alla paternità/maternità adottiva dovrebbero essere gestiti in aggiunta ai genitori biologici.
Attualmente in ANPR sono visualizzabili solo i genitori biologici, c’è modo di gestire anche le informazioni relative ai genitori adottanti?

**Comment by rvinzani** [comment]
Attualmente non c'è questa possibilità. Faremo un approfondimento per verificare che siano informazioni anagrafiche e non solo di stato civile
