### ISSUE TITLE
Errore Anpr Cod: EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2602]
Salve,

TERRACINA PRODUZIONE

l'individuo id 60781309 è presente in Anpr con un CF che in AE risulta essere un suo collegato.

Sia con una mutazione tutti i dati, sia con lo strumento di risoluzione disallineamenti AE non è possibile invertirli, in quanto si ottiene:

Errore Anpr Cod: EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato

in un precedente analogo siete intervenuti con la "svalidazione" del soggetto in ANPR

E' possibile richiederlo anche per questo caso o va contattata l'assistenza? 

E' previsto in futuro un rilascio che renda autonoma questa "svalidazione" ?

Lascio l'EN527

Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-04-12 12:33:11 , idOperazioneANPR 505013779

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
potete procedere con la mutazione tutti i dati aggiornando il CF e i dati anagrafici come richiesto. 

N. Capozzi

**Comment by mrabuano** [comment]
Buongiorno,
confermo che la mutazione è stata inviata con successo. 

Grazie
