### ISSUE TITLE
Problema webservices ambiente test Arezzo

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#2603]
Buongiorno, ho un problema con l'ambiente di test del comune di Arezzo.

L'utenza del responsabile della sicurezza non era stata creata "automaticamente" in tale ambiente e non si riusciva ad accedere tramite web app, e' stata creata a seguito di segnalazione aperta con l'help desk. 
Adesso si riesce ad accedere tramite web app ma tramite webservices non funziona il colloquio ottenedo il seguente errore: 
****javax.xml.ws.soap.SOAPFaultException: Rejected by policy. (from client)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:161)
	at com.sun.proxy.$Proxy86.interrogazioneCittadinoFamigliaConvivenza(Unknown Source)
Caused by: org.apache.cxf.binding.soap.SoapFault: Rejected by policy. (from client)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:86)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:52)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:41)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)****

Vi chiedo se per caso, visto anche la mancata attivazione dell'utenza, ci siano da fare altre sistemazioni sull'ambiente di test per Arezzo.
Abbiamo inoltre provato, sempre tramite web app, a creare un nuovo utente in test ma non si riesce ad attribuire il profilo ottenendo la segnalazione di errore  "Errore durante l'elaborazione della richiesta".
E' stata aperta segnalazione tramite numero verde da 15 giorni senza risposta.
Grazie.
Andrea Galli

**Comment by cmigliardi** [comment]
Buonasera,    cortesemente mi può  inviare il numero del TT  che avete  aperto?  così  possiamo verificare e sollecitare ?  grazie  per la collaborazione

**Comment by cmigliardi** [comment]
Solitamente “rejected by policy (client)” significa che viene bloccato dal data power  
Nel caso specifico sui log dp di test comuni vedo due richieste tra le 15.30 e le 15.45 che sembrano avere un errore sul certificato : 

Apr 13 15:31:22 ANPR_error [0x80000001][ANPR_error][error] wsgw(ANPR_WSP_SOA): trans(482282879)[error][151.41.55.151] gtid(fa4f83f360759d2a1cbf0d7f): URL=https://192.168.89.238:6443/ANPR3000ServiziConsultazione/AnprService3000,IP=151.41.55.151,IPP=,IDP=052032-PC-0001,IDA=jEnte,IDS=051002,IDE=,CF=LSINCL70E11A390K,MSG=PKCS#7 argument error: malformed DER encoded PKCS#7 object
Apr 13 15:44:26 ANPR_error [0x80000001][ANPR_error][error] wsgw(ANPR_WSP_SOA): trans(482352943)[error][151.41.55.151] gtid(fa4f83f36075a03a1cc01f2f): URL=https://192.168.89.238:6443/ANPR3000ServiziConsultazione/AnprService3000,IP=151.41.55.151,IPP=,IDP=051002-CO-0000,IDA=jEnte,IDS=051002,IDE=,CF=LSINCL70E11A390K,MSG=Rejected by policy.

**Comment by cmigliardi** [comment]
Consiglio di  inviarmi   il messaggio completo della richiesta, comprensivo di tutta la cornice di sicurezza, in modo che possiamo verificare meglio quale possa essere il problema.  alla  mia  email  grazie

**Comment by cmigliardi** [comment]
questo l' errore che rileva    il data power       malformed DER encoded PKCS#7   se può essere di ausilio

**Comment by cmigliardi** [comment]
Consiglio di inviarmi il messaggio completo della richiesta, comprensivo di tutta la cornice di sicurezza, in modo che possiamo verificare meglio quale possa essere il problema. alla mia email grazie -

**Comment by cmigliardi** [comment]
Consiglio di inviarmi il messaggio completo della richiesta, comprensivo di tutta la cornice di sicurezza, in modo che possiamo verificare meglio quale possa essere il problema. alla mia email grazie -

non ho ancora ricevuto nulla . chiudo la issue  - attendo alla mia email   il messaggio  completo   -  cmigliardi

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
