### ISSUE TITLE
Impossibilità collegamento codici fiscali

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2605]
Il 17/03/2021 abbiamo iscritto, con provenienza da altro comune subentrato, la persona con codice identificativo ANPR  45981933 in possesso di codice fiscale alfanumerico validato.
La collega dell'ASL competente, alla quale l'interessata si è rivolta per l'emissione di una nuova tessera sanitaria, mi ha chiesto di procedere al collegamento di due codici fiscali numerici che sappiamo per certo da ricondursi sempre alla medesima.
Di questi due codici fiscali uno risulta fra l'altro validato ANPR dal comune di precedente residenza, così come lo era il codice alfanumerico.
Comunque in entrambi i casi, quando tento di procedere al collegamento, il messaggio di errore che compare è sempre "codici fiscali non collegabili".
D'altro canto l'ASL mi dice di non poter richiedere la nuova tessera in presenza di quella che appare come un'omocodia non risolta.
Potete darmi qualche indicazione su come procedere?

**Comment by rvinzani** [comment]
Da ANPR è possibile collegare codici fiscali numerici ad alfanumerici solo se in ANPR è presente il numerico e deve essere sostituito con l'alfanumerico. Viceversa è necessario rivolgersi all'ufficio Territoriale dell'Agenzia entrate o alla direzione centrale se il numerico fosse marcato. chiudo la issue. nel caso fossero necessari ulteriori chiarimenti o fosse necessario supporto specifico si prega di rivolgersi al nostro servizio di assistenza al n. 800863116
