### ISSUE TITLE
[6001] Errore EN181 - Verifica su idOperazioneANPR

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2606]
Buongiorno, per conto del Comune di Somma Lombardo vi chiedo gentilmente una verifica su idOperazioneANPR 507155277 (di un'ora fa), relativa ad una richiesta di certificato. 
La risposta restituisce "codiceErroreAnomalia" EN181 : "Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato". Avremmo bisogno di capire se effettivamente c'è un procedimento aperto o qualche altro problema sul soggetto con codice fiscale "CR.............00Y". 
Grazie. Cordiali saluti

**Comment by ncapozzi** [comment]
Buongiorno,
risulta aperto il procedimento 25569777, n. pratica del Comune di Somma Lombardo R20200000000064

N. Capozzi
