### ISSUE TITLE
Errore EN248  in Mutazione tutti i dati

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#2607]
Buongiorno
Il comune di CONEGLIANO (subentro), segnala quanto segue.

Per il soggetto con id ANPR 95045148, riceve l'errore EN248 eseguendo una
mutazione tutti dati sull'oggetto generalità.
Si tratta di ex irreperibile del comune reperito all'AIRE,  per il quale in forza di
 comunicazione consolare, occorre procedere con l'aggiunta di un secondo elemento onomastico (MARCELA).
L'attuale CF è validato presso AE, ma le nuove generalità danno origine ad un novo CF.

Le nuove generalità ed il nuovo CF coincidono
con quelle di una posizione (id ANPR 94322698) cancellata per altri motivi dal comune di
SAN MARTINO DI FINITA che non aveva titolo a registralo quale AIRE.
Il CF non è validato presso AE.

Cosa può fare l'ente per effettuare questa modifica?
L'operazione è del 06/04/2021

G. Trisolini

**Comment by rvinzani** [comment]
Dovreste collegare i due codici fiscali utilizzando la funzione presente in utilità e notifiche. Se vi occorre supporto per effettuare questa operazione chiamate pure il nostro servizio di assistenza al n. 800863116. Chiudo pertanto la issue

**Comment by CIVILIANEXT001** [comment]
Buongiorno
La soluzione suggerita non è percorribile. 
I 2 CF non sono entrambi presenti in AE.
Quello con id ANPR 95045148 é presente in AE, ma è da rettificare in quello
corrispondente ad id ANPR 94322698 che non è presente in AE e che in ANPR risulta cancellato da altro comune

Cordiali saluti
G. Trisolini
