### ISSUE TITLE
fiel excel archivio comuni

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2608]
Buongiorno, in seguito al restyling del portale ANPR, non trovo più il file con l'elenco dei comuni subentrati, con i seguenti dati
"Comune | Numero abitanti | Data subentro | Provincia | Regione | Prefettura | Codice Istat | Codice  catastale"
che prima era disponibile direttamente da https://www.anpr.interno.it, è stato spostato o rimosso?
nel caso sia rimosso è possibile ripristinarlo?

ho controllato nella sezione "export" ma ci sono altri tracciati (https://www.anpr.interno.it/AnprStatsWeb/export.html)

provando questo link (https://www.anpr.interno.it/wp-content/uploads/2021/04/Tabella_45) da errore pagina non trovata 404

Grazie mille
Riccardo

**Comment by mttfranci** [comment]
Buongiorno, abbiamo appena pubblicato un avviso #2609.
Saluti

**Comment by Hdemografici** [comment]
Grazie ho controllato la tabella 45 , ma il tracciato è diverso da quello che c'era prima in home page, 

Prima era cosi
Comune           | Numero abitanti | Data subentro | Provincia | Regione | Prefettura | Codice Istat | Codice  catastale
ABANO TERME | 20.325                | 19/12/2018     | PADOVA | VENETO | PADOVA  | 028001          | A001

in questa tabella invece
CODISTAT | CODCATASTALE | DENOMINAZIONE_IT | IDPROVINCIA | IDREGIONE | IDPREFETTURA | DATASUBENTRO
039002      | A547                  | BAGNACAVALLO        | 39                    | 08               | RA                    | 21/10/2016

**Comment by cmigliardi** [comment]
la tabella 45  è sempre la  stessa  -  lo scarico  dei comuni in anpr    lo trovate   in area  Progetto - stato di avanzamento - export dei dati  -

**Comment by Hdemografici** [comment]
si la tabella 45 è uguale a prima, dicevo che è diversa dal file xls che c'era prima in home page, stesso discorso per l'elenco in "export dei dati" che ha solo queste informazioni
Regione | Provincia | Comune
ABRUZZO | CHIETI | ALTINO

comunque i controlli che mi servivano riesco a farli dalla tabella 45

buona giornata e grazie
