### ISSUE TITLE
Nuovo sito www.anpr.interno.it - tabelle di decodifica / comuni subentrati

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#2609]
Buon giorno, oggi è andata in linea la nuova versione del sito di ANPR.

Il punto di accesso al sito di ANPR è : 
https://www.anpr.interno.it/
le tabelle  le trovate  nella fascia   IL PROGETTO   -   area   Strumenti di lavoro -  tabelle di decodifica ( in  azzurro)   
l’elenco dei comuni subentrati  ( excel)   in   Stato di avanzamento  -  export dei dati

Siamo a disposizione per qualsiasi chiarimento.

Saluti

Assistenza ANPR

**Comment by ncapozzi** [comment]
L'archivio storico dei comuni è pubblicato nella pagina
Ti trovi in •  Home •  Il progetto •  Strumenti di lavoro •  Archivio storico dei comuni 
oppure
Ti trovi in: Home > Il progetto > Strumenti di lavoro >Tabelle di decodifica
