### ISSUE TITLE
Inserimento Permessi di soggiorno data antecedente al subentro 

### ISSUE THREAD

**Issue by moniapellizzari** [italia/anpr#261]
Buongiorno, sono venuti nei nostri uffici cittadini a consegnarci permessi di soggiorno rinnovati già da qualche mese quindi con data antecedente al subentro. 
Abbiamo tentato l'inserimento in ANPR ma il sistema non li accetta proprio perchè la data del documento risulta antecedente al subentro.
Si chiede come poter ovviare al problema.
Cordiali saluti.
Monia Pellizzari
Comune di Anzola dell'Emilia

**Comment by mttfranci** [comment]
Buongiorno, avete modo di fornirci l'identificativo di una operazione su cui avete avuto questo problema o dei dati che ci aiutino ad identificare l'operazione stesse (data, tipo, tipo mutazione, soggetto). Grazie?

**Comment by moniapellizzari** [comment]
Buongiorno, in mattinata abbiamo fatto ulteriori tentativi di invio del permesso, e pur essendo presente il messaggio di errore di data antecedente, abbiamo verificato che il permesso del 10 marzo 2017 è stato recepito in ANPR pertanto dobbiamo prima verificare con la nostra software house il tipo di problematica e messaggistica. Vi aggiorneremo il prima possibile. 
Cordiali saluti. 
Monia Pellizzari 
Comune di Anzola dell'Emilia 

Monia Pellizzari 
Servizio Urp e Demografici 
Comune di Anzola dell'Emilia 
tel. 051/6502105 
fax. 051/731598 
www.comune.anzoladellemilia.bo.it 
https://www.facebook.com/comuneanzolaemilia 


Da: "Matteo" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "moniapellizzari" <monia.pellizzari@comune.anzoladellemilia.bo.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 8 agosto 2017 13:26:39 
Oggetto: Re: [italia/anpr] Inserimento Permessi di soggiorno data antecedente al subentro (#261) 



Buongiorno, avete modo di fornirci l'identificativo di una operazione su cui avete avuto questo problema o dei dati che ci aiutino ad identificare l'operazione stesse (data, tipo, tipo mutazione, soggetto). Grazie?

**Comment by mttfranci** [comment]
Va bene. 
Rimaniamo in attesa.
Saluti.

**Comment by moniapellizzari** [comment]
Buongiorno, abbiamo verificato con la software house che si tratta di un problema legato alla messaggistica del nostro software ma che verrà risolta a breve pertanto non dovrebbero esserci ulteriori difficoltà, nel caso si presentassero altre problematiche vi informeremo. 
Grazie per la collaborazione, cordiali saluti. 

Monia Pellizzari 
Servizio Urp e Demografici 
Comune di Anzola dell'Emilia 
tel. 051/6502105 
fax. 051/731598 
www.comune.anzoladellemilia.bo.it 
https://www.facebook.com/comuneanzolaemilia 


Da: "Monia Pellizzari" <monia.pellizzari@comune.anzoladellemilia.bo.it> 
A: "italia/anpr" <reply@reply.github.com> 
Cc: "italia/anpr" <anpr@noreply.github.com>, "Author" <author@noreply.github.com> 
Inviato: Mercoledì, 9 agosto 2017 13:23:12 
Oggetto: Re: [italia/anpr] Inserimento Permessi di soggiorno data antecedente al subentro (#261) 

Buongiorno, in mattinata abbiamo fatto ulteriori tentativi di invio del permesso, e pur essendo presente il messaggio di errore di data antecedente, abbiamo verificato che il permesso del 10 marzo 2017 è stato recepito in ANPR pertanto dobbiamo prima verificare con la nostra software house il tipo di problematica e messaggistica. Vi aggiorneremo il prima possibile. 
Cordiali saluti. 
Monia Pellizzari 
Comune di Anzola dell'Emilia 

Monia Pellizzari 
Servizio Urp e Demografici 
Comune di Anzola dell'Emilia 
tel. 051/6502105 
fax. 051/731598 
www.comune.anzoladellemilia.bo.it 
https://www.facebook.com/comuneanzolaemilia 


Da: "Matteo" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "moniapellizzari" <monia.pellizzari@comune.anzoladellemilia.bo.it>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 8 agosto 2017 13:26:39 
Oggetto: Re: [italia/anpr] Inserimento Permessi di soggiorno data antecedente al subentro (#261) 



Buongiorno, avete modo di fornirci l'identificativo di una operazione su cui avete avuto questo problema o dei dati che ci aiutino ad identificare l'operazione stesse (data, tipo, tipo mutazione, soggetto). Grazie?

**Comment by mttfranci** [comment]
Perfetto. Siamo a disposizione per qualsiasi altra necessità.
