### ISSUE TITLE
3000consultazione - Rejected by policy

### ISSUE THREAD

**Issue by johnatandante** [italia/anpr#2610]
Salve,
stiamo tentando di invocare il servizio 3000 di consultazione con una chiamata al web service 

[wsfree.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000](https://wsfree.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000)

ma il server risponde con un messaggio di "Rejected by policy"

```xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>
```

Il path è corretto?
Gli header sono corretti?

Riuscite ad aiutarmi?

Allego l'xml della richiesta
[Richiesta3002.txt](https://github.com/italia/anpr/files/6318993/Richiesta3002.txt)

**Comment by johnatandante** [comment]
@FilippoPapi @mttfranci novità?

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando la vostra richiesta.

Intanto una verifica che potete fare voi è l'allineamento dell'orario del client usato (un problema che capita abbastanza spesso è che il client abbia un orario eccessivamente diverso da quello del server).

**Comment by johnatandante** [comment]
Grazie della risposta.Il server ragiona in UTC? Stiamo usando lo stesso algoritmo per la costruzione del <soap:Header> sul servizio 6001 non abbiamo problem. Dante  From: MatteoSent: Tuesday, April 20, 2021 7:57 AMTo: italia/anprCc: Dante Del Favero; AuthorSubject: Re: [italia/anpr] 3000consultazione - Rejected by policy (#2610) Buongiorno, stiamo verificando la vostra richiesta.Intanto una verifica che potete fare voi è l'allineamento dell'orario del client usato (un problema che capita abbastanza spesso è che il client abbia un orario eccessivamente diverso da quello del server).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mttfranci** [comment]
Con l'operation 3002 non avete mai avuto una risposta valida dal server?

**Comment by johnatandante** [comment]
@mttfranci  grazie, intanto correggo questa svista e vi faccio sapere

**Comment by johnatandante** [comment]
Riprovato ora da 195.14.103.3

```xml
<saml2:Subject>
                    <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">USERSFREETEST237</saml2:NameID>
                    <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                        <saml2:SubjectConfirmationData NotBefore="2021-04-20T13:33:38.829Z" NotOnOrAfter="2021-04-20T14:35:38.829Z"/>
                    </saml2:SubjectConfirmation>
                </saml2:Subject>
```

In allegato la request
[myrequest.xml.txt](https://github.com/italia/anpr/files/6343166/myrequest.xml.txt)

**Comment by johnatandante** [comment]
@mttfranci ho provato a giocare con i parametri legati al periodo di validità dei token di autenticazione, di sessione e di Timestamp.
Li ho volutamente sincronizzati a -2h dalla data Italiana e questo ha funzionato!

Evidentemente, come ho chiesto, il server risponde con orario UTC+0

```xml
<wsu:Timestamp wsu:Id="TS-dddfe297-ba9d-4d9e-ba92-af820f2b312a">
                <wsu:Created>2021-04-20T13:00:28.101Z</wsu:Created>
                <wsu:Expires>2021-04-20T17:02:28.101Z</wsu:Expires>
            </wsu:Timestamp>
```
e 
```xml
                <saml2:Subject>
                    <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">USERSFREETEST237</saml2:NameID>
                    <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                        <saml2:SubjectConfirmationData NotBefore="2021-04-20T13:00:28.101Z" NotOnOrAfter="2021-04-20T17:02:28.101Z"/>
                    </saml2:SubjectConfirmation>
                </saml2:Subject>
                <saml2:Conditions NotBefore="2021-04-20T13:00:28.101Z" NotOnOrAfter="2021-04-20T17:02:28.101Z"/>
                <saml2:AuthnStatement AuthnInstant="2021-04-20T13:00:28.101Z" SessionNotOnOrAfter="2021-04-20T17:02:28.101Z">
                    <saml2:SubjectLocality Address="192.168.1.1"/>
                    <saml2:AuthnContext>
                        <saml2:AuthnContextClassRef/>
                    </saml2:AuthnContext>
                </saml2:AuthnStatement>
```

E' possibile avere un riferimento su questi dettagli tecnici?

**Comment by johnatandante** [comment]
@mttfranci chiudo l'issue.
Riuscite comunque a darmi indicazione di dove poter trovare documentazione tecnica di questo tipo? Sapendo che l'ora del server, e quindi i servizi di autenticazione/validazione token di sicurezza erano espressi in UTC+0, avrei evitato di aprire una issue

**Comment by mttfranci** [comment]
@johnatandante ok, verifichiamo se va integrata la documentazione.
Saluti

**Comment by gife67** [comment]
Buona sera,
questi sono standard e convenzioni utilizzate nelle SAML assertion. Il formato delle date è in Zulu Time che corrisponde all'UTC+0.
Le consiglio di consultare i dettagli dello standard delle SAML Assertion 2.0.
Cordiali saluti

**Comment by johnatandante** [comment]
@gife67 grazie delle informazioni.
Trovavo comunque curioso il fatto che la stessa finestra oraria era permessa per il servizio 6001, mentre per quello 3000 no.

Grazie della pazienza e buon lavoro.
