### ISSUE TITLE
WS5008 MODIFICA COGNOME 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2611]
Buonasera,
COMUNE DI CASERTA - PROD
Inviando una transazione con WS5008 per cambio cognome e quindi richiesta di attribuzione nuovo codice fiscale, dopo verifica su AE della inesistenza. 
EN491 Se il codice fiscale è esistente, non è possibile richiedere una nuova attribuzione; 
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2021-04-15 19:32:59 , idOperazioneANPR 508491201
Grazie

**Comment by azabatta** [comment]
Buongiorno,
github è una comunità di discussione e non deve essere utilizzato per richieste di assistenza. Cortesemente per problematiche di questo tipo vi preghiamo di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
Cordiali saluti
