### ISSUE TITLE
Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12)

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2612]
Buongiorno,

Per il soggetto id scheda anpr 31350206, non riusciamo a variare il nome, data nascita e CF, ne con mutazione tutti i dati e ne con la risoluzione CF confermando i dati AE.

I dati giusti sono quelli presenti in AE

Errore
Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12)

Ricordo che in passato avevate svalidato voi il CF, è possibile risolvere gentilmente il problema?

Grazie
Cordiali saluti
Dante Della Strada
Comune di Cesena

**Comment by frmariani** [comment]
Il codice fiscale è stato svalidato, potete procedere con l'operazione di mutazione dei dati
