### ISSUE TITLE
nuovo sito - tabella di decodifica dei comuni

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2613]
Prima dell'aggiornamento del sito la tabella 3 (archivio comuni) era un CSV.
Dopo l'aggiornamento è un excel con una sola colonna per riga e la cella contiene la riga CSV.
Questo nuovo formato non risulta pratico da usare.

**Comment by cmigliardi** [comment]
l'archivio dei comuni in anpr   ora si trova in area  Stati di   avnzamento -  export dei dati  e  si puo'  optare  o per il foglio Excel  o per il csv

**Comment by dedabob** [comment]
La tabella in stati di avanzamento non ha lo stesso contenuto di _Strumenti di lavoro_ > _Tabelle di decodifica_ > _Archivio Comuni_

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
se invece si riferisce all'archivio storico dei comuni  lo trova  nel nuovo portale  ANPR  a:      Ti trovi in: HomeIl progettoStrumenti di lavoroArchivio storico dei comuni

**Comment by cmigliardi** [comment]
scusi  -  le ho risposto    se invece si riferisce all'archivio storico dei comuni lo trova nel nuovo portale ANPR a: Ti trovi in: HomeIl progettoStrumenti di lavoroArchivio storico dei comuni

**Comment by cmigliardi** [comment]
se invece si riferisce all'archivio storico dei comuni lo trova nel nuovo portale ANPR a: Ti trovi in:  home  il progetto    Strumenti di lavoro     Archivio storico dei comuni  - trova il file  csv

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
