### ISSUE TITLE
nuovo sito - tabella di decodifica dei comuni

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2614]
Nella versione precedente del sito la tabella _Strumenti di lavoro_ > _Tabelle di decodifica_ > _Archivio Comuni_ era un CSV.
Dopo l'aggiornamento è un excel con una sola colonna per riga e la cella contiene la riga CSV.
Questo nuovo formato non risulta pratico da usare.

La tabella in _Strumenti di lavoro_ > _Archivio storico dei comuni_ sembra la conversione in CSV del precedente Excel e quindi ha una colonna per riga il cui contenuto è a sua volta una riga in formato CSV.

La precedente segnalazione #2613 è stata chiusa senza nemmeno aver letto il mio commento che chiariva di quale tabella si trattasse..

**Comment by cmigliardi** [comment]
se invece si riferisce all'archivio storico dei comuni lo trova nel nuovo portale ANPR a: Ti trovi in: home il progetto Strumenti di lavoro Archivio storico dei comuni - trova il file csv

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
