### ISSUE TITLE
CONVIVENZE DI FATTO

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2615]
#710 
> 
> 
> Ambasciator non porta pena...Ho già scritto al Ministero chiedendo una causale in più di cessazione per le convivenze (oltre al decesso).
> Personalmente ritengo iniqua la cessazione per cambio di residenza di uno dei due: una persona può essere costretta a cambiare residenza, ad esempio, per motivi di lavoro. Per quale motivo dovrebbe perdere i benefici che derivano da questa legge?

Si è poi saputo più niente dal Ministero? Ho notato che è stata aggiunta la causale "Chiusura d'ufficio per cancellazione del soggetto". E' questa la dicitura prevista per la casistica oggetto di discussione (fine della coabitazione)?
Colgo l'occasione per far notare che la tabella 43 non è stata aggiornata con la nuova motivazione.

**Comment by rvinzani** [comment]
Non abbiamo avuto nessun riscontro dal Ministero. Non ci risulta che sia stata aggiunta la causale indicata

**Comment by gianpaol** [comment]
Come si può vedere dallo screenshot di seguito riportato questa ulteriore motivazione a cui si fa riferimento nella issue #710  è stata aggiunta ed è presente in ANPR. Pertanto andrebbe aggiornata la tabella 43 e andrebbe chiarito se effettivamente la stessa si riferisce alla fine della coabitazione o ad altro. Nella issue #1523 viene fatto ulteriore riferimento a questo chiarimento da parte del ministero dell'interno e viene suggerito di usare la motivazione predetta per il trasferimento dei due conviventi di fatto all'estero. Di fatto non è chiaro in quale caso debba usarsi e se la fine della coabitazione (semplicemente per trasferimento in altro comune) sia motivo di risoluzione della convivenza.

![ALLEGATI](https://user-images.githubusercontent.com/76410238/116699832-5c2cf100-a9c6-11eb-92b3-43f114a9b0b9.png)

**Comment by rvinzani** [comment]
Aggiorneremo la tabella. Grazie della segnalazione. Chiudo la issue. Nel caso fossero necessari ulteriori chiarimenti si prega di aprire una nuova issue che facci riferimento a questa
