### ISSUE TITLE
[6001] - Operazione non consentita per la tipologia di dati richiesta

### ISSUE THREAD

**Issue by matteomulas** [italia/anpr#2616]
Buongiorno. 
Stiamo tentando di recuperare un certificato attraverso il servizio 6001.
Il soggetto è stato creato tramite web application.
Utilizzandola riusciamo ad ottenere e scaricare il certificato mentre richiamando il servizio la chiamata va a buon fine ma ci viene restituito il seguente errore: "EN174: Operazione non consentita per la tipologia di dati richiesta". 

Vorremmo sapere se c'è qualche errore nella richiesta.

**Richiesta.**
<?xml version="1.0" encoding="UTF-8"?>
<ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
	<testataRichiesta>
		<idOperazioneComune>000001</idOperazioneComune>
		<codMittente>888231</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>6001</operazioneRichiesta>
		<dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>FREE</tipoInvio>
		<dataDefinizionePratica>2021-04-14</dataDefinizionePratica>
	</testataRichiesta>
	<listaTipiCertificati>
		<tipoCertificato>1</tipoCertificato>
	</listaTipiCertificati>
	<soggettoIntestatario>
		<generalita>
			<cognome>PITZALIS</cognome>
			<nome>ROBERTA</nome>
		</generalita>
	</soggettoIntestatario>
	<datiControllo>
		<cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
		<nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
		<tipoRichiedente>2</tipoRichiedente>
		<tipoRichiesta>1</tipoRichiesta>
		<paEstera>0</paEstera>
		<emissione>3</emissione>
		<bollo>0</bollo>
		<bolloVirtuale>2</bolloVirtuale>
		<diritti>0</diritti>
	</datiControllo>
</ns2:Richiesta6001>

**Risposta.**
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta6001 xmlns:a="http://sogei.it/ANPR/6001certificazione">
            <a:Risposta6001KO>
                <testataRisposta>
                    <idOperazioneComune>000001</idOperazioneComune>
                    <codMittente>888231</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>6001</operazioneRichiesta>
                    <dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
                    <idOperazioneANPR>7028377</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN174</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Operazione non consentita per la tipologia di dati richiesta&#13;
</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:Risposta6001KO>
        </a:Risposta6001>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by matteomulas** [comment]
Richiesta.
<?xml version="1.0" encoding="UTF-8"?>
<ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
	<testataRichiesta>
		<idOperazioneComune>000001</idOperazioneComune>
		<codMittente>888231</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>6001</operazioneRichiesta>
		<dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>FREE</tipoInvio>
		<dataDefinizionePratica>2021-04-14</dataDefinizionePratica>
	</testataRichiesta>
	<listaTipiCertificati>
		<tipoCertificato>1</tipoCertificato>
	</listaTipiCertificati>
	<soggettoIntestatario>
		<generalita>
			<cognome>PITZALIS</cognome>
			<nome>ROBERTA</nome>
		</generalita>
	</soggettoIntestatario>
	<datiControllo>
		<cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
		<nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
		<tipoRichiedente>2</tipoRichiedente>
		<tipoRichiesta>1</tipoRichiesta>
		<paEstera>0</paEstera>
		<emissione>3</emissione>
		<bollo>0</bollo>
		<bolloVirtuale>2</bolloVirtuale>
		<diritti>0</diritti>
	</datiControllo>
</ns2:Richiesta6001>


Messaggio di Risposta:
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta6001 xmlns:a="http://sogei.it/ANPR/6001certificazione">
            <a:Risposta6001KO>
                <testataRisposta>
                    <idOperazioneComune>000001</idOperazioneComune>
                    <codMittente>888231</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>6001</operazioneRichiesta>
                    <dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
                    <idOperazioneANPR>7028377</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN174</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Operazione non consentita per la tipologia di dati richiesta&#13;
</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:Risposta6001KO>
        </a:Risposta6001>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by matteomulas** [comment]
Richiesta.
`<?xml version="1.0" encoding="UTF-8"?>
<ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
	<testataRichiesta>
		<idOperazioneComune>000001</idOperazioneComune>
		<codMittente>888231</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>6001</operazioneRichiesta>
		<dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>FREE</tipoInvio>
		<dataDefinizionePratica>2021-04-14</dataDefinizionePratica>
	</testataRichiesta>
	<listaTipiCertificati>
		<tipoCertificato>1</tipoCertificato>
	</listaTipiCertificati>
	<soggettoIntestatario>
		<generalita>
			<cognome>PITZALIS</cognome>
			<nome>ROBERTA</nome>
		</generalita>
	</soggettoIntestatario>
	<datiControllo>
		<cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
		<nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
		<tipoRichiedente>2</tipoRichiedente>
		<tipoRichiesta>1</tipoRichiesta>
		<paEstera>0</paEstera>
		<emissione>3</emissione>
		<bollo>0</bollo>
		<bolloVirtuale>2</bolloVirtuale>
		<diritti>0</diritti>
	</datiControllo>
</ns2:Richiesta6001>`

Risposta
`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta6001 xmlns:a="http://sogei.it/ANPR/6001certificazione">
            <a:Risposta6001KO>
                <testataRisposta>
                    <idOperazioneComune>000001</idOperazioneComune>
                    <codMittente>888231</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>6001</operazioneRichiesta>
                    <dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
                    <idOperazioneANPR>7028377</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN174</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Operazione non consentita per la tipologia di dati richiesta&#13;
</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:Risposta6001KO>
        </a:Risposta6001>
    </soapenv:Body>
</soapenv:Envelope>`

**Comment by mttfranci** [comment]
Salve.
Avete indicato tipoRichiesta = 2 (Dati certificati)
Tale tipologia richiesta è disponibile solo per lo storico di cittadinanza (6) e lo storico di residenza (9).
Saluti

**Comment by matteomulas** [comment]
Buongiorno. 

La nostra richiesta contiente un tipoRichiesta = 1 ( emissione certificato) 

Richiesta.
`<?xml version="1.0" encoding="UTF-8"?> <ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione"> <testataRichiesta> <idOperazioneComune>000001</idOperazioneComune> <codMittente>888231</codMittente> <codDestinatario>ANPR02</codDestinatario> <operazioneRichiesta>6001</operazioneRichiesta> <dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta> <tipoOperazione>C</tipoOperazione> <tipoInvio>FREE</tipoInvio> <dataDefinizionePratica>2021-04-14</dataDefinizionePratica> </testataRichiesta> <listaTipiCertificati> <tipoCertificato>1</tipoCertificato> </listaTipiCertificati> <soggettoIntestatario> <generalita> <cognome>PITZALIS</cognome> <nome>ROBERTA</nome> </generalita> </soggettoIntestatario> <datiControllo> <cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe> <nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe> <tipoRichiedente>2</tipoRichiedente> **<tipoRichiesta>1</tipoRichiesta>** <paEstera>0</paEstera> <emissione>3</emissione> <bollo>0</bollo> <bolloVirtuale>2</bolloVirtuale> <diritti>0</diritti> </datiControllo> </ns2:Richiesta6001>`

Anche impostando tipoRichiesta=2 , emissione=1 (come da documentazione) e richiedendo i certificato 6 e 9 otteniamo la stessa risposta.

Richiesta
`<?xml version="1.0" encoding="UTF-8"?>
<ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
	<testataRichiesta>
		<idOperazioneComune>000001</idOperazioneComune>
		<codMittente>888231</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>6001</operazioneRichiesta>
		<dataOraRichiesta>2021-02-17T10:20:11.543+02:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>FREE</tipoInvio>
		<dataDefinizionePratica>2021-04-14</dataDefinizionePratica>
	</testataRichiesta>
	<listaTipiCertificati>
		<tipoCertificato>6</tipoCertificato>
		<tipoCertificato>9</tipoCertificato>
	</listaTipiCertificati>
	<soggettoIntestatario>
		<generalita>
			<cognome>PITZALIS</cognome>
			<nome>ROBERTA</nome>
		</generalita>
	</soggettoIntestatario>
	<datiControllo>
		<cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
		<nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
		<tipoRichiedente>2</tipoRichiedente>
		<tipoRichiesta>2</tipoRichiesta>
		<paEstera>0</paEstera>
		<emissione>1</emissione>
		<bollo>0</bollo>
		<bolloVirtuale>2</bolloVirtuale>
		<diritti>0</diritti>
	</datiControllo>
</ns2:Richiesta6001>`


Saluti,
MM

**Comment by mttfranci** [comment]
Salve, noi abbiamo verificato la richiesta : 7028377 arrivata sui nostri sistemi e aveva tipoRichiesta = 2.
Se non modificate l'id tipo operazione (che sembra essere indicato a 000001) non viene eseguita una nuova richiesta, ma viene restituita la risposta originaria, indipendentemente dai valori che passate.

Potrebbe essere questo il problema.
Potete riprovare con un idOperazioneComune che non avete mai usato per questo comune?

Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenteza ANPR

**Comment by matteomulas** [comment]
Il problema era dovuto all'idOperazioneComune. 

Provando la chiamata con un idOperazioneComune  univoco otteniamo una risposta positiva e il certificato richiesto.

Grazie.
Saluti.
