### ISSUE TITLE
CSV Archivio storico comuni ANPR utilizzo: errori nel file

### ISSUE THREAD

**Issue by aborruso** [italia/anpr#2617]
Buongiorno @ncapozzi ,
ho appena guardato il CSV in oggetto, a partire dal nuovo permalink che mi ha indicato [qui](https://github.com/italia/anpr/issues/1252#issuecomment-822325864) (grazie), e ho notato che è pieno di `"` in più

Le prime righe sono ad esempio così

```
"",""IDREGIONE"",""IDPREFETTURA"",""STATO"",""SIGLAPROVINCIA"",""FONTE"",""DATAULTIMOAGG"",""COD_DENOM"""
"12560,""1866-11-19"",""1924-11-13"",""028001"",""A001"",""ABANO"",""ABANO"","""","""",""28"",""028"",""05"","""",""C"",""PD"","""",""2016-06-17"",""028500"""
"1,""1924-11-14"",""9999-12-31"",""028001"",""A001"",""ABANO TERME"",""ABANO TERME"","""","""",""28"",""028"",""05"",""PD"",""A"",""PD"","""",""2016-06-17"","""""
"3,""1864-04-01"",""1928-12-05"",""001801"",""A003"",""ABBADIA ALPINA"",""ABBADIA ALPINA"","""","""",""1"",""001"",""01"","""",""C"",""TO"","""",""2017-11-11"","""""
```

Grazie

**Comment by jenkin** [comment]
Libreoffice Calc per esempio non riesci ad aprirlo, direi che NON è un csv ben formato.

![Screenshot_20210419_125223](https://user-images.githubusercontent.com/426495/115225357-4722a900-a10e-11eb-9979-82dfb54a13fe.png)

**Comment by aborruso** [comment]
Sembra esserci anche qualche problema di encoding.

Ad esempio a riga 19310

![image](https://user-images.githubusercontent.com/30607/115227405-b6999800-a110-11eb-8405-f071b48d379e.png)

**Comment by jenkin** [comment]
Il vecchio file era in `latin-1` (iso-8859-1) se non sbaglio...

**Comment by aborruso** [comment]
@jenkin di inferencing mi dava UTF-8. Provo.

Nella pagina dove è pubblicato il CSV, va inserita nota di encoding

**Comment by aborruso** [comment]
@jenkin migliora, ma non risolve

![image](https://user-images.githubusercontent.com/30607/115228327-e8f7c500-a111-11eb-8259-a8b7697360f5.png)

**Comment by aborruso** [comment]
Sotto una pipeline per normalizzarlo.

Qui l'output che adesso è leggibile < https://gist.githubusercontent.com/aborruso/f6595e1c4767e4a416cdc867fa47dcc8/raw/c4ee2e9d6d05c26757291022e67eaf6fb878bc68/ANPR_archivio_comuni.csv>

```bash
# scarica file
curl -kLs "https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv" >tmp.csv
# imposta encoding
iconv -f ISO-8859-15 -t UTF-8 tmp.csv>ANPR_archivio_comuni.csv
# cambia il ritorno a capo
dos2unix ANPR_archivio_comuni.csv
# rimuovi doppie virgole in più e carattere scorrettamente interpretato, che sembra essere una doppia virgola
<ANPR_archivio_comuni.csv sed -r 's/^"//;s/"$//;s/""/"/g;s/¢/"/g' >tmp.csv
# rinomina
mv tmp.csv ANPR_archivio_comuni.csv
# riporta i ritorni a capo in stile dos
unix2dos ANPR_archivio_comuni.csv
```

**Comment by aborruso** [comment]
Aggiungo un'ultima nota: ancora meglio, se si rimuovessero tutte le `"` non necessarie.

Qui un esempio https://gist.github.com/aborruso/5ba0531123095cff7545c744c26d01ca

**Comment by ncapozzi** [comment]
Buongiorno,
il file è stato ripubblicato nel formato corretto.
Ringraziamo per la pazienza e la collaborazione.
N. Capozzi

**Comment by aborruso** [comment]
Buongiorno @ncapozzi ho appena scaricato il file da

```
https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv
```

e riscontro le stesse problematicità sulle `"`. Avete cambiato URL?

Grazie

```
"ID,""DATAISTITUZIONE"",""DATACESSAZIONE"",""CODISTAT"",""CODCATASTALE"",""DENOMINAZIONE_IT"",""DENOMTRASLITTERATA"",""ALTRADENOMINAZIONE"",""ALTRADENOMTRASLITTERATA"",""IDPROVINCIA"",""IDPROVINCIAISTAT"",""IDREGIONE"",""IDPREFETTURA"",""STATO"",""SIGLAPROVINCIA"",""FONTE"",""DATAULTIMOAGG"",""COD_DENOM"""
"12560,""1866-11-19"",""1924-11-13"",""028001"",""A001"",""ABANO"",""ABANO"","""","""",""28"",""028"",""05"","""",""C"",""PD"","""",""2016-06-17"",""028500"""
"1,""1924-11-14"",""9999-12-31"",""028001"",""A001"",""ABANO TERME"",""ABANO TERME"","""","""",""28"",""028"",""05"",""PD"",""A"",""PD"","""",""2016-06-17"","""""
"3,""1864-04-01"",""1928-12-05"",""001801"",""A003"",""ABBADIA ALPINA"",""ABBADIA ALPINA"","""","""",""1"",""001"",""01"","""",""C"",""TO"","""",""2017-11-11"","""""
"5,""1861-03-17"",""1992-04-15"",""015001"",""A004"",""ABBADIA CERRETO"",""ABBADIA CERRETO"","""","""",""15"",""015"",""03"","""",""C"",""MI"","""",""2016-06-17"","""""
```

**Comment by jenkin** [comment]
Confermo, mi pare che [non sia cambiato nulla](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv)... un problema di cache? È possibile anche avere l'informazione _esplicita_ della codifica di caratteri usata? Grazie

**Comment by ncapozzi** [comment]
Scusate purtroppo il file corretto è stato pubblicato al link https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni-1.csv
Vi avviseremo appena ripristinato https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv

**Comment by aborruso** [comment]
dott @ncapozzi ne approfitto per una domanda: questo file dove è visibile nel nuovo sito?

Se non lo è ancora è certamente da inserire, perché di grande interesse.
Se è conosciuto solo qui, rischia di diventare invisibile.

Grazie

**Comment by ncapozzi** [comment]
Ti trovi in •  Home •  Il progetto •  Strumenti di lavoro •  Archivio storico dei comuni 
oppure
Ti trovi in: Home > Il progetto > Strumenti di lavoro >Tabelle di decodifica

**Comment by aborruso** [comment]
Grazie dott. @ncapozzi , pagina trovata https://www.anpr.interno.it/il-progetto/strumenti-di-lavoro/archivio-storico-dei-comuni/

Un'ultima cosa rilevante: qual è l'encoding? Sembra che adesso sia UTF-8.

Non è un'informazione che risiede nel file, quindi andrebbe inserita come brevissima nota nella pagina.

Saluti

**Comment by ncapozzi** [comment]
E' stato ripristinato https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv

**Comment by ncapozzi** [comment]
Quale encoding precedente le risulta?

**Comment by aborruso** [comment]
> Quale encoding precedente le risulta?

Se non sbaglio era iso-8859-1

**Comment by ncapozzi** [comment]
A me risulta che sia sempre stato UTF8

**Comment by aborruso** [comment]
Grazie @ncapozzi 

A seguire il tipo di nota che a mio avviso andrebbe inserito.

Grazie

![image](https://user-images.githubusercontent.com/30607/115425104-998fc280-a1ff-11eb-818f-8d18a1b35b11.png)
