### ISSUE TITLE
ERRORE EN420 - OPERAZIONE RETTIFICHE 5014

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2618]
Rettifica non permessa - data decorrenza residenza 25-06-2015 maggiore della data ultimo aggiornamento APR 29/01/1983 (Codice: EN420) 
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-04-19 12:51:18 , idOperazioneANPR 510673743 (Codice: EN527)
ID ANPR 95370349 Il cittadino è stato caricato con una data di residenza errata coincidente con la data di prima iscrizione e non con la data di ultima residenza avendo il cittadino effettuato diversi spostamenti nell'ambito dello stesso comune.
Si è proceduto ad una rettifica della data di decorrenza residenza, ma la stessa non è possibile poiché vengono segnalati gli errori sopra riportati.
L'unica operazione effettuata sul cittadino è il subentro, potrebbe essere quello il motivo?
COMUNE DI CASTELLAMMARE DI STABIA
CONZA GIANPAOLO

**Comment by frmariani** [comment]
Le date devono essere coerenti tra di loro e nel Suo caso non lo sono.
Github è una comunità di discussione e non deve essere utilizzato per richieste di assistenza. Cortesemente per problematiche di questo tipo vi preghiamo di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
Saluti
