### ISSUE TITLE
Anomalia archivio dei comuni

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2619]
Buongiorno,
con la ristrutturazione del sito, il file con l'archivio dei comuni ha cambiato formato.
Dato che il problema è già stato segnalato con due issue #2613 e #2614 ma non sembra sia stato compreso, cerco di esporre il problema.
Nell'attuale file una riga è così indicata:
"12560,""1866-11-19"",""1924-11-13"",""028001"",""A001"",""ABANO"",""ABANO"","""","""",""28"",""028"",""05"","""",""C"",""PD"","""",""2016-06-17"",""028500"""
mentre nelle versioni precedente la stessa informazione era riportata in questo modo:
12560,"1866-11-19","1924-11-13","028001","A001","ABANO","ABANO","","",28,"028","05","","C","PD","","2016-06-17","028500"

1) In pratica la riga risulta un'unica stringa (è il contenuto dai doppi apici più esterni) e quindi i doppi apici al suo interno vengono raddoppiati.

2) Anche supponendo di rimuovere i doppi apici agli estremi e raggruppare le coppie di doppi apici si nota chiaramente che il campo ID_PROVINICIA è passato da una rappresentazione intera ad una rappresentazione a stringa problema già segnalato e poi risolto con la issue #2596

Grazie,
Tiziano Pavan

**Comment by ncapozzi** [comment]
Buongiorno,
il file è stato ripubblicato nel formato corretto.
Ringraziamo per la pazienza e la collaborazione.
N. Capozzi
