### ISSUE TITLE
Cancelazione per altri motivi WS 2003

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#262]
Buongiorno, siamo del comune di Bologna. In ambiente di TEST abbiamo richiamato il WS 2003 per 
il C.F. NGDJNR64B42Z306Y
La risposta con id ANPR 562254 ha avuto esito negativo.

Se interroghiamo il soggeto con la WS viene visualizzato
Succesivamente abbiamo anche provato  a richiamare per lo stesso soggetto il WS 2001.
In questo caso non abbiamo avuto problemi e siamo anche riusciti ad eseguire l'annullamento del 2001.

COSA VUOL DIRE L'ERRORE NEL 2003?

P.S. Alleghiamo xmo inviato

Grazie
[WS2003.zip](https://github.com/italia/anpr/files/1209033/WS2003.zip)

**Comment by gcarbonin** [comment]
L'apparente anomalia di comportamento del servizio 2003 è dovuta alla mancata indicazione dell'identificativo ANPR del soggetto, l'unico che in prospettiva è quello da ritenere valido. In ogni caso, siamo intervenuti per migliorare i criteri di ricerca e potete riprovare.
