### ISSUE TITLE
Rif. #2067 - Errore EN248 in Mutazione tutti i dati 

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#2620]
Buongiorno
La soluzione suggerita non è percorribile.
I 2 CF non sono entrambi presenti in AE.
Quello con id ANPR 95045148 é presente in AE, ma è da rettificare in quello
corrispondente ad id ANPR 94322698 che non è presente in AE e che in ANPR risulta cancellato da altro comune

Come dobbiamo gestire questo caso?

Cordiali saluti
G. Trisolini

**Comment by rvinzani** [comment]
Le risponderemo con il ticket di assistenza 22653101. Chiudo pertanto questa issue. Saluti

**Comment by rvinzani** [comment]
Può per favore inviare una sue email o un suo recapito telefonico poichè non riesco a contattare nessuno del comune di Conegliano

**Comment by CIVILIANEXT001** [comment]
Buonasera..
Nella scorsa settimana il comune aveva contattato il numero verde dell'assistenza tecnica che ha richiesto l'id operazione per poter dare supporto.
A tal fine, nel pomeriggio di venerdì 30/04, il comune ha riprovato a trasmettere la richiesta che è andata a buon fine.
Io ho questo recapito del comune : Telefono: 0438413222
