### ISSUE TITLE
la famiglia risulta non ancora iscritta completamente 

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#2622]
Giugliano in Campania Produzione.
Salve,
per gli individui nella famiglia con IdAnprFam = 24835302 l'emissione di certificati di Stato di Famiglia fallisce con il seguente messaggio: 
"I certificati di stato di famiglia, stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perchè la famiglia risulta non ancora iscritta completamente "
I componenti di tale famiglia sono stati iscritti tutti da subentro a meno del componente con idAnpr = 59355729 che è stato iscritto tramite operazione con Id = 84878047.
Alla consultazione degli individui di tale famiglia viene restituita la seguente Anomalia:
"Anomalia  EN213  La famiglia di appartenenza del cittadino risulta incompleta"
Abbiamo notato che nella famiglia l'individuo con idAnpr = 59355729 non aveva valorizzato il progressivo per cui, pensando che potesse essere questo il problema è stata fatta un'operazione di Mutazione/famiglia Convivenza Apr-->Composizione Scheda attribuendo il progressivo mancante (Idop = 512298518)...tale operazione non è stata comunque risolutiva del problema.
L'ente ha urgenza di emettere il certificato per cui si richiede come poter risolvere il problema.

Assistenza Tecnica del comune di Giugliano in Campania

**Comment by ncapozzi** [comment]
Buonasera,
per rendere la famiglia completa è necessario effettuare una mutazione famiglia/convivenza richiamando il WS 5001 con tipo mutazione = 3 inserendo nella lista controlli FI = 1. La stessa operazione può essere eseguita anche dall'applicazione WEB di ANPR.
Con l'occasione si ricorda che github è una comunità di discussione e non deve essere utilizzato per richieste di assistenza. Cortesemente per problematiche di questo tipo vi preghiamo di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
Grazie
N. Capozzi
