### ISSUE TITLE
Certificati anagrafici

### ISSUE THREAD

**Issue by carlo-prodigys** [italia/anpr#2623]
Buongiorno,

alcuni comuni mi segnalano che il nome dei certificati dovrebbe essere differente da quello reperibile nella documentazione:
https://docs.italia.it/italia/anpr/anpr/it/stabile/tab/tab_tipo_di_certificato.html

"Stato di famiglia" dovrebbe essere "di Stato di famiglia e residenza"
"di Stato di famiglia e di stato civile" e "di Stato di famiglia, residenza e di stato civile"

Sono corrette le indicazioni del comune poichè è presente anceh la residenza delle certificazioni?

Carlo

**Comment by rvinzani** [comment]
I nomi dei certificati sono stati concordati con il Ministero dell'Interno. Eventuali richieste di modifica quindi andrebbero indirizzate a quest'ultimo.

**Comment by carlo-prodigys** [comment]
perfetto grazie
