### ISSUE TITLE
[403] Login fallito: non sono stati recuperati i dati dell'utente

### ISSUE THREAD

**Issue by Sklaer79** [italia/anpr#2624]
Accedendo tramite SPID viene mi restituito il seguente errore:
"Login fallito: non sono stati recuperati i dati dell'utente [403]"

**Comment by FilippoPapi** [comment]
mi scusi dove sta accedendo?

**Comment by Sklaer79** [comment]
https://www.anpr.interno.it/ -> "Accesso con SPID" -> Seleziono "PosteID" -> Autorizzo tramite QR code -> Viene richiesta l'autorizzazione di condividere il codice fiscale -> Confermo -> si apre la pagina: https://sc.anpr.interno.it/serviziCittadino/open/errorPage  con l'errore: "Login fallito: non sono stati recuperati i dati dell'utente [403]"

**Comment by gife67** [comment]
Buongiorno,
cortesemente se ci fornisce il suo CF parziale (prime 7 lettere e ultima lettera) verifichiamo quale possa essere il problema.
Grazie

**Comment by Sklaer79** [comment]
FNGNDR7*A

**Comment by gife67** [comment]
Cortesemente potete riprovare l'accesso... in caso di esito positivo potete chiudere la issue.
Grazie mille

**Comment by Sklaer79** [comment]
Risolto, grazie
