### ISSUE TITLE
[7002] assenza tag specie in toponimo

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2626]
Buongiorno 
comune CARTOCETO in PRESUBENTRO
mi sono accorto che c'è una differenza di ritorno dati nelle consultazioni 3002 e 4001/7002
all'interno del tag toponimo delle 7002 non è valorizzato il tag <specie> come invece avviene regolarmente per la 3002
esempio consultando il cittadino idSchedaSoggettoANPR 254749290 idOperazioneANPR 23409017
`<toponimo>  <specie>VIA</specie>  <specieFonte>1</specieFonte>
                                    <denominazioneToponimo>S. ANNA</denominazioneToponimo>
                                    <toponimoFonte>2</toponimoFonte>
                                </toponimo>`
mentre lo stesso cittadino ritornato nella 7002 idOperazioneANPR 23408971
`<toponimo>
                        <specieFonte>1</specieFonte>
                        <denominazioneToponimo>S. ANNA</denominazioneToponimo>
                        <toponimoFonte>2</toponimoFonte>
                    </toponimo>`
il problema non è solo con questo cittadino ma praticamente tutti

**Comment by mttfranci** [comment]
Buongiorno, dovremmo aver individuato e corretto l'anomalia, potete riprovare? (5.13.2)
Siamoa a disposizione per ogni chiarmento.
Saluti

Assistenza ANPR

**Comment by Hdemografici** [comment]
Buongiorno, confermo che, in presubentro ,ora il tag specie viene restituito
la modifica è disponibile già anche in ambiente PRODUZIONE?

grazie

**Comment by mttfranci** [comment]
Salve, si è disponibile in tutit gli ambienti.
Saluti

Assistenza ANPR

**Comment by Hdemografici** [comment]
perfetto grazie mille
buona giornata
