### ISSUE TITLE
NUOVO SITO ANPR NON TROVATO FILE AGGIORNAMENTI.XLS

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2627]
Buongiorno, in riferimento alla tabella 

03 ANPR Archivio comuni – csv | Istat-Agenzia delle Entrate-Ministero | 6 aprile 2021 | “Vedi Aggiornamenti.xls”

Non riesco più a trovare il file “Vedi Aggiornamenti.xls”

Ho provato a cercarlo con la funzione di ricerca in vari modi ma non restituisce risultati nella precedente versione del sito invece veniva trovato. 

Potete indicarmi dove reperirlo? Grazie 

Cordiali saluti

Cinzia Girelli
GPI Spa
Mobile Phone: +39 3346216774
Mail cinzia.girelli@gpi.it

**Comment by ncapozzi** [comment]
Buongiorno
https://www.anpr.interno.it/il-progetto/strumenti-di-lavoro/documentazione-tecnica/
