### ISSUE TITLE
Rilascio certificati anagrafici ANPR on line

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2628]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
volevo avere informazioni in merito alle modalità operative per l'attivazione del servizio ANPR per il rilascio dei certificati anagrafici on line da mettere a disposizione dei cittadini sul nostro sito.
Potete fornirmi i riferimenti di un Comune per il quale è già stato attivato il servizio di rilascio on line di ANPR ? Per i diritti di segreteria ed il bollo virtuale come funziona ?

Resto in attesa di gentile riscontro,.

**Comment by GabriellaBallabio** [comment]
Non avendo ancora ricevuto risposta , vi chiedo la cortesia di fornirmi almeno un link dal quale scaricare una documentazione che possa essermi utile.

Grazie

**Comment by rvinzani** [comment]
Gent.le Sig.ra Varisco,
a breve verrà reso disponibile il rilascio del certificati on line direttamente dal sito di ANPR accedendo con l'identità digitale. Tali certificati presentano oltre al QRCode anche il sigillo elettronico del Ministero dell'interno.
Alcuni comuni già rilasciano certificazioni on line richiamando il servizio 6001 in modalità on line (trova le indicazioni sulle specifiche WSDL_XSD) ed impostando sul sito web, alla voce Amministrazione->Gestione comune, l'esenzione dei diritti di segreteria per i certificati on line. A nostra conoscenza i comuni che già adottano questa modalità sono ad es. Roma e Milano
