### ISSUE TITLE
Impossibile accedere con SPID e CNS

### ISSUE THREAD

**Issue by dpole** [italia/anpr#2629]
Accedendo con SPID, dopo l'autenticazione e il consenso alla condivisione del codice fiscale ottengo: 
<img width="610" alt="Screenshot 2021-04-24 at 08 55 41" src="https://user-images.githubusercontent.com/4341327/115950464-b6681680-a4db-11eb-9eb0-16f77d0a111d.png">

Mentre cliccando sull'accesso con CNS ottengo
<img width="546" alt="Screenshot 2021-04-24 at 08 56 10" src="https://user-images.githubusercontent.com/4341327/115950490-d26bb800-a4db-11eb-8160-20e3bd252ad7.png">

Colgo l'occasione per i migliori in bocca al lupo per il progetto, grazie per il vostro lavoro.

**Comment by FilippoPapi** [comment]
buongiorno
Github è un forum di discussione e non un punto di assistenza vi prego quindi in futuro di non utilizzare questo canale.

comunque le indico di seguito le possibili cause per le quali non riesce ad accedere:
•	Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR  (puoi verificarlo facilmente utilizzando la funzione  “A che punto è il tuo comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune)
•	se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE)  per maggiori informazioni.

relativamente invece al messaggio di errore per l'accesso con CNS, così come riportato nel sito subito prima del bottone di accesso, deve, prima di cliccare sul pulsante “Entra con CNS”, installare il lettore ed inserire la carta.
buon fine settimana
