### ISSUE TITLE
Pre-Subentro - Anomalie "comune atto non valido alla data"

### ISSUE THREAD

**Issue by busaster** [italia/anpr#263]
Un altro nostro cliente ha effettuato in questi giorni il presubentro.
Stiamo analizzando con lui le anomalie ritornate.
Ne troviamo molte di tipo "EC075 : Comune dell'atto di nascita:XXXX non esistente alla data" oppure  "EC081 : Comune dell'atto di matrimonio:XXXX non esistente alla data".
Il cliente li vorrebbe sistemare.
Ci chiediamo quale sia la data di  riferimento di cui si parla.
Preciso che nel subentro non viene mai popolato il campo "data formazione atto" in quanto non presente nei nostri archivi.

**Comment by gcarbonin** [comment]
La data di riferimento è quella dell'atto. In ogni caso NON E' RICHIESTA NESSUNA SISTEMAZIONE DI QUESTO TIPO DI ANOMALIE. Dovrebbe uscire una nota del Ministero dell'Interno che ufficializza questo modus operandi.

**Comment by luca-teamdigitale** [comment]
Aggiungo un paio di informazioni ulteriori:

Come dice giustamente @gcarbonin i due tipi di errori riportati vengono considerati "non bloccanti". Un errore "non bloccante" non deve essere necessariamente bonificato prima del passaggio ad ANPR, e` a discrezione del Comune decidere quando effettuarne la bonifica.

Per quanto riguarda la descrizione degli errori stessi, su http://docs.anpr.it potete trovare una sezione che descrive gli errori e suggerisce cosa fare ( in particolare: http://anpr.readthedocs.io/en/latest/subentro/tabella_anomalie.html ). Qualora i suggerimenti non fossero chiari vi preghiamo di segnalarcelo e cercheremo di migliorarli assieme.

Grazie.
