### ISSUE TITLE
annullamento di matrimonio e variazione di stato civile

### ISSUE THREAD

**Issue by giu-dot** [italia/anpr#2630]
Buongiorno,
vorrei segnalare questo problema, ho trascritto una sentenza di delibazione della corte di appello per il riconoscimento della declaratoria di nullità di un matrimonio, nella sentenza non ho la ratifica della sacra rota, è stata resa esecutiva dal Tribunale Ecclesiastico, successivamente la Segnatura Apostolica ha emesso il decreto di esecutività.
Ho provato ad inserire i dati nel programma Anpr ma sono bloccata in quanto il programma mi fa scegliere come tribunale: Sacra Rota, Tribunale civile italiano, Tribunale Estero, Non conosciuto.
La scelta ricadrebbe su "non conosciuto" dato che "Tribunale Ecclesiastico" non è selezionabile, ne tanto meno "Corte d'Appello".
Inoltre inserendo  "non conosciuto" che date vanno inserite nei campi 
"data" e "data validità"?

**Comment by frmariani** [comment]
L'elenco de tribunali presenti nella tendina a scelta è stata concordata con il Ministero dell'Interno, quindi la richiesta di eventuali nuovi inserimenti andrebbe indirizzata a loro.
Il campo obbligatorio "Autorità" è un testo libero, quindi all'interno potrebbe specificare la casistica di cui necessita;
le date sono entrambe obbligatorie e non dipendono dalla tipologia di Tribunale scelto.
Si ricordi che la variazione dello stato civile non è automatica.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
In alternativa può contattare il numero verde 800863116
