### ISSUE TITLE
Problema con SC operatore trasferito da altro comune

### ISSUE THREAD

**Issue by AndreaBruni** [italia/anpr#2631]
Buongiorno,

sono in difficoltà con la SC di un operatore trasferitosi dal comune di Zibido San Giacomo (MI) al comune di Casorate Primo (PV).

Da un paio di mesi attendo che la situazione si sblocchi (vedi immagine in allegato gentilmente inviatami dal collega del comune di Zibido San Giacomo) ma invano.

Per il Comune di Zibido San Giacomo l'utente risulta (ovviamente) inattivo e la SC "bloccata" con stato certificato "revoca in lavorazione"

L'utente per il Comune di Casorate Primo risulta attivo ma la SC risulta "bloccata".

Sia il sottoscritto che i colleghi del comune di Casorate abbiamo provato a contattare il call center ma finora senza risultati apprezzabili.

Sinceramente non so più che pesci pigliare.

Ringrazio anticipatamente per la cortesia e la disponibilità e saluto cordialmente.

Andrea Bruni
CED esterno - A.d.S. Comune di Casorate Primo (PV)
![Utente_bloccato_screenshot](https://user-images.githubusercontent.com/79931693/116050494-d46a7e00-a677-11eb-9b06-776690ea7a20.png)

**Comment by Leonforte** [comment]
Buongiorno, la smart card è un dispostivi personale e non è legata al comune dove l'utente lavora, quindi può essere utilizzata per tutti quei comuni dove lo stesso è abilitato. Le suggerisco de effettuare le seguenti operazioni :
1)Sblocco della carta dell'utente da parte del comune di Zibido
2)Cacellazione dell'utente da parte del comune di Casorate (ora non possibile perchè la carta risulta bloccata da un altro comune)
3)Reinserimento dell'utente da parte di Casorate (in tal modo Casorate acquisisce anche la gestione della carta)
4)Cancellazione dell'utente da parte di Zibido che non avendo più in gestione la carta è libero di cancellare l'utenza.

Buon lavoro, saluti
