### ISSUE TITLE
[5008] : errore EN389 a seguito di correzione data decorrenza per altro errore EN389

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2633]
Buonasera
a seguito di una comunicazione 5008 (tipo mutazione diverso da 1) torna l'errore EN389 con
<< La data decorrenza XX-XX-XXXX dell'operazione non puo' essere inferiore alla data decorrenza YY-YY-YYYY dell'ultima operazione effettuata sui dati relativi a prima iscrizione nel comune corrente >>

Se correggo la comunicazione 5008 precedente inserendo la data decorrenza "YY-YY-YYYY" proposta nell'errore torna di nuovo errore EN389 con data differente:

<< La data decorrenza YY-YY-YYYY dell'operazione non puo' essere inferiore alla data decorrenza ZZ-ZZ-ZZZZ dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto >>

ESEMPIO Comune di Sessa Aurunca - idOperazioniANPR 516800487 e seguente correzione 516816279

Sarebbe possibile ricevere in risposta con il primo errore EN389 direttamente la data più recente?

**Comment by frmariani** [comment]
Anche se la codifica dell'errore è la stessa, con la prima risposta di errore che ha ricevuto, vi abbiamo segnalato la presenza di una data di decorrenza dell'operazione antecedente alla data di iscrizione;
La successiva risposta di errore invece, prende in considerazione le diverse tipologie di mutazione presenti nel servizio e controlla che la data di decorrenza dell'operazione non sia antecedente alla data dell’ultima mutazione effettuata sulle diverse tipologie di mutazioni presenti ed esponendo nella descrizione dell'errore la più recente.

**Comment by Hdemografici** [comment]
Non si discute il significato di quanto segnalato dagli errori EN389, sono chiari, chiedevo solo se fosse possibile ricevere in risposta direttamente l'errore con data più recente, risparmierebbe una comunicazione a chi utilizza il servizio e i relativi controlli a voi, magari verificando prima la presenza di operazioni sui dati del cittadino e poi la presenza di operazioni sui dati iscrizione.

**Comment by frmariani** [comment]
al momento il servizio non prende in considerazione operazioni con data di decorrenza minore della data iscrizione del soggetto.

**Comment by Hdemografici** [comment]
Ripeto, i messaggi in risposta alla comunicazione sono chiari:
1) non è possibile mettere una data decorrenza inferiore alla data decorrenza dell'ultima operazione effettuata sui dati relativi a prima iscrizione nel comune corrente;
2) non è possibile mettere una data decorrenza inferiore alla data decorrenza dell'ultima operazione effettuata sui dati del soggetto;
3) la data decorrenza inviata con la 5008 è sbagliata, in genere si cerca di inviare il servizio con una data decorrenza il più possibile fedele allo storico del cittadino, ma ci possono essere delle anomalie negli storici.

Sto dicendo che dopo aver ricevuto in risposta l'errore EN389 utilizzo la data indicata nell'errore per correggere la data decorrenza del servizio 5008 e reinviarlo. Nei casi come quello segnalato costringe il comune all'invio di 3 servizi 5008 per ogni cittadino.
1) richiesta s5008  con data errata precedente all'iscrizione
2) risposta anpr KO con EN389 con controllo su dati iscrizione
3) richiesta s5008  con data presa da EN389
4) risposta anpr KO con EN389 con controllo su dati cittadino
5) richiesta s5008 con data presa da EN389
6) risposta anpr OK (forse)

Si chiede se è possibile ricevere in risposta alle comunicazioni 5008 l'errore EN389 con i riferimenti al dato più recente o quanto meno forse dovreste prima controllare le operazioni sul cittadino (forse più frequenti rispetto alle operazioni di iscrizione)

**Comment by frmariani** [comment]
I nostri sistemi dovrebbero essere allineati, quindi mi chiedo come mai ci viene inviato un WS 5008 con la data di decorrenza dell'operazione minore della data iscrizione del cittadino nel Comune; come mai il Comune non conosce una data che ci ha precedentemente inviato ? 
Le ripeto , il sistema ANPR non lavora servizi con la data di decorrenza dell'operazione antecedente alla data di iscrizione;
la successiva risposta considera le diverse tipologie di mutazione presenti nel servizio e controlla che la data di decorrenza dell'operazione non sia antecedente alla data dell’ultima mutazione effettuata **sulle diverse tipologie di mutazioni presenti** esponendo nella descrizione dell'errore la più recente: come vede la sua richiesta è già presente nel nostro sistema, ma non possiamo accettare che un Comune non conosca la data di iscrizione di un proprio cittadino.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
