### ISSUE TITLE
SBLOCCO SMART CARD (NUOVA GENERAZIONE)

### ISSUE THREAD

**Issue by eferrarias2** [italia/anpr#2634]
Buongiorno,
abbiamo dei problemi ad utilizzare una SmartCard (nuovo modello) per l'accesso ANPR di un operatore del Comune di Adria (RO) in quanto viene segnalato che il PIN della carta è bloccato, ma le procedure di sblocco descritte nella vostra documentazione tecnica non funzionano in quanto la card sembra non essere riconosciuta.
Premetto che l'installazione della postazione (lettore SC + certificati) è stata eseguita correttamente seguendo i passaggi elencati nelle vostre guide e a riprova ne è il fatto che utilizzando altra SC (anch'essa di nuova generazione) di un altro operatore, l'accesso ad ANPR avviene correttamente. Inserendo invece la SC che ci da problemi otteniamo che 

IDProtect non identifica la Smart Card
![immagine](https://user-images.githubusercontent.com/83007674/116201575-ed3b6800-a739-11eb-9e4f-ef94a96dcd76.png)

e tentando di eseguire lo sblocco utilizzando GoSign Dekstop (versione più recente disponibile) ed inserendo il PUK e riconfermando il PIN originale che è stato consegnato all'operatore
![immagine](https://user-images.githubusercontent.com/83007674/116201894-4905f100-a73a-11eb-826c-840bfc140760.png)

lo sblocco non funziona
![immagine](https://user-images.githubusercontent.com/83007674/116202052-75217200-a73a-11eb-8c07-7f70ee5f5c2d.png)

Abbiamo già da tempo segnalato il problema al Contact Center ANPR 800863116 ma nonostante sia passato ormai un mese non siamo mai stati ricontattati. Chiedo cortesemente se potete ricontattarmi preferibilmente domani mattina in quanto sarò presente direttamente sulla postazione dell'operatore comunale per il quale si verifica il problema. I miei contatti telefonici sono al 348-4400897 e 0425-420185. 
Se può esservi utile il numero della SC è 1207100000008615, mentre il contatto telefonico dell'utente proprietario presso il Comune di Adria è 0426-941240.
Rimango in fiduciosa attesa di un vostro riscontro, grazie.

Ermanno

**Comment by Leonforte** [comment]
Buongiorno, il software da utilizzare è DikeGoSign, IDProtect Monitor serve esclusivamente per le carte modello Aruba.
Le suggerisco di fare un ultimo tentativo seguendo le istruzioni presenti al link :

https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf

Se non riuscite a sbloccarla procederemo con la richiesta di una nuova carta. Buon lavoro, saluti

**Comment by eferrarias2** [comment]
Innanzitutto grazie per il sollecito riscontro,
domani mattina sarò fisicamente presso il Comune di Adria così con l'operatore comunale coinvolto potremo eseguire il tentativo che mi ha suggerito poi aggiornerò il post con l'esito. 
Un saluto.

**Comment by eferrarias2** [comment]
Buongiorno,
ho seguito la procedura che mi ha indicato per l'ativazione della carta
![immagine](https://user-images.githubusercontent.com/83007674/116390314-32d16100-a81e-11eb-87db-5b7dd03602ab.png)

però tentando poi nuovament l'accesso ad ANPR viene visualizzato il consueto errore:
![immagine](https://user-images.githubusercontent.com/83007674/116390628-8c399000-a81e-11eb-8210-9593b774e392.png)

a questo punto come procedere ?

**Comment by Leonforte** [comment]
Buongiorno, mi dispiace ma come anticipato occorre richiedere una nuova carta, operazione che potete effettuare in autonomia, buon lavoro, saluti

**Comment by eferrarias2** [comment]
Buongiorno, grazie della risposta, procederemo alla richiesta di una nuova carta come indicato.
Cordiali saluti.
