### ISSUE TITLE
Cessazione e distruzione smartcard operatori non in servizio

### ISSUE THREAD

**Issue by cedgravina01** [italia/anpr#2636]
Salve, sono l'Amministratore Locale della Sicurezza per il Comune di Gravina di Catania, dovrei cessare dall'accesso ad ANPR di alcuni operatori non più in servizio presso il nostro ente e distruggere le smartcard operatore rilasciate a suo tempo attraverso la Prefettura. Non riesco a trovare nella Web App nessuna funzionalità in tal senso, ne una documentazione su come procedere. Quale è la procedura corretta per procedere?
Grazie

**Comment by Leonforte** [comment]
Buongiorno, la smart card è un dispositivo personale e può essere utilizzato per qualsiasi comuni su cui l'utente è abilitato.  Se gli utenti in questione andranno a lavorare presso altri comuni le suggerisco di lasciare attiva la carta ed attendere che il nuovo comune registri l'utente e prenda quindi in carico la gestione della carta. A valle di ciò potrà procedere con la cancellazione dell'utente dal menù Gestione Utenti della console. Se invece il lavoro dei colleghi cessa per altri motivi può procedere direttamente alla cancellazione dell'utenza sempre dal menù Gestione Utenze. Buon lavoro, saluti

**Comment by cedgravina01** [comment]
> Buongiorno, la smart card è un dispositivo personale e può essere utilizzato per qualsiasi comuni su cui l'utente è abilitato. Se gli utenti in questione andranno a lavorare presso altri comuni le suggerisco di lasciare attiva la carta ed attendere che il nuovo comune registri l'utente e prenda quindi in carico la gestione della carta. A valle di ciò potrà procedere con la cancellazione dell'utente dal menù Gestione Utenti della console. Se invece il lavoro dei colleghi cessa per altri motivi può procedere direttamente alla cancellazione dell'utenza sempre dal menù Gestione Utenze. Buon lavoro, saluti

grazie per le indicazioni. In effetti si tratta di utenti che sono andati in pensione. tuttavia per alcune di queste utenze nella web app nel menu gestione utenti non mi viene data la possibilità di cancellarla, probabilmente perché si tratta di utenze caricate al censimento iniziale al momento dell'avvio del progetto o perché hanno delle smart card attive. come posso procedere per eliminare queste utenze? Le smart card posso distruggerle semplicemente oppure è necessario redigere un verbale e inviarlo a sogei?

**Comment by Leonforte** [comment]
Per poter cancellare l'utenza la carta deve essere attiva, quindi se sono ancora nello stato "Consegnata dalla Prefettura" non troverà il tasto cancella nella gestione utenti. Può comunque procedere all'attivazione della carta e poi alla cancellazione dell'utenza, che di fatto disattiva la carta e revoca il certificato contenuto a bordo. 
Gestione Utenti
Tato Ricerca
Selezionare la lente a dx dell'utente desiderato
Tasto Avanti
Tasto Cancella
