### ISSUE TITLE
SMARTCARD NUOVA GENERAZIONE ATTIVA MA ERRORE ACCESSO- PIN/PUK BLOCCATO

### ISSUE THREAD

**Issue by COMUNEDIRUDIANO** [italia/anpr#2637]
Buongiorno,
da tempo, anche con il supporto del nostro tecnico, stiamo cercando di attivare la Smartcard di nuova generazione n°017167 1207100000008602. Pur seguendo le istruzioni e i passaggi indicati all'atto dell'accesso compare il messaggio di errore: 
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED
Ieri il tecnico è riuscito a risolvere parzialmente il problema e ad arrivare alla schermata di inserimento PIN, ma compare la scritta PIN BLOCCATO. Seguendo la procedura indicata per lo sblocco PIN, compare la scritta PIN/PUK ERRATO. Specifico che sono stati utilizzati i Pin/Puk rilasciati al momento del ritiro della carta. Dopo diversi tentativi, ora compare il messaggio PUK bloccato.  Nella Webapp la Smartcard risulta tuttora attiva.
Chiediamo quindi come ci dobbiamo comportare.
Contatti:
030 7060700/ 728
anagrafe@comune.rudiano.bs.it

orari:
dal lun. al ven. 8:30-12:30
sab. 8:00 - 12:00

**Comment by Leonforte** [comment]
Se il PUK è bloccatto occorre richiedere una nuova carta dal menù Gestione Smartcard della console, buon lavoro, saluti
