### ISSUE TITLE
[6001] Richiesta certificato in formato PDF/A

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2638]
Buongiorno,
è possibile interrogare il servizio 6001 in modo che restituisca il certificato in formato PDF/A ?
Grazie
Cordiali saluti

**Comment by mttfranci** [comment]
Buongiorno.

No il servizio non lo provede.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by Eduardo1977** [comment]
Grazie, per la risposta.
Saluti
