### ISSUE TITLE
ACQUSITO CITTADINANZA DALLA NASCITA - errore data decorrenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2640]
COMUNE DI CAPONAGO

VARISCO MARIA GIUSEPPINA

Buongiorno
devo effettuare una variazione per acquisto cittadinanza "DALLA NASCITA" , il WS mi restituisce errore :

La data decorrenza 11-08-1986 dell'operazione non puo' essere inferiore alla data decorrenza 04-03-2021 dell'ultima operazione effettuata sui dati relativi a prima iscrizione nel comune corrente

ecco i riferimenti dell'operazione : data 2021-04-30 09:18:13 , idOperazioneANPR 520354047

Resto in attesa di gentile riscontro

Saluti

**Comment by frmariani** [comment]
La data di decorrenza dell'operazione non può essere minore della data di iscrizione del cittadino nel Comune; la data di validità della cittadinanza può essere inserita nella sezione "Cittadinanza".
Le ricordo che Github è una comunità di discussione; per problemi specifici come questo vi preghiamo di utilizzare il servizio di assistenza ANPR al numero 800863116
