### ISSUE TITLE
RETTIFICA/REGISTRAZIONE DATI DI MATRIMONIO E DIVORZIO PRECEDENTI AD UNA CONVIVENZA DI FATTO 

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2641]
Buongiorno,
In passato abbiamo registrato la residenza dell'individuo id anpr = 42368952, tale individuo alla data della residenza aveva una convivenza di fatto in data 31/10/2017 e la decorrenza del legame alla data 23/08/2017, adesso abbiamo necessità di aggiornare dei dati precedenti/mancanti di stato civile, ma all'invio della mutazione tutti i dati sia in operazione d'ufficio che in rettifica il sistema risponde il seguente errore:

La data evento del matrimonio da inserire è => 14/06/2014

La data evento del divorzio è => (atto)  26/02/2016

La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto (Codice: EN289)

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-03 12:02:22 , idOperazioneANPR 522579815 (Codice: EN527) 

C'è un qualche modo di sbloccare la mutazione tutti i dati?

Certo di di una vostra risposta porgo cordiali saluti
Della Strada Dante - Comune di cesena

**Comment by frmariani** [comment]
Con il subentro, il Comune invia ad ANPR i dati del cittadino al momento del subentro, senza inviare i dati storici;
se c'è una necessità particolare, dovete indicare come tipo di mutazione "Cessazione del matrimonio" (WS 5008 tipo mutazione 14) indicando contestualmente sia i dati minimi del matrimonio (nome, cognome, sesso del coniuge e data dell'evento matrimonio) che i dati della cessazione stessa.
Se dovesse avere problemi nell'esecuzione dell'operazione vi preghiamo di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
Saluti

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
