### ISSUE TITLE
Esenzione dei diritti di segreteria - Il sistema è momentaneamente non disponibile

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2642]
Salve,
Campodarsego produzione
Nel tentare di impostare nella WebApllication l'esenzione dei diritti di segreteria nei parametri utilizzati per l'emissione dei certificati , si riscontra l'errore come da oggetto. 

Tale anomalia si verifica anche in altri ambienti di produzione da questa mattina a tuttora. 

In ambiente di presubentro la modifica viene recepita senza problemi

**Comment by asqueglia** [comment]
Buongiorno, stiamo analizzando il problema. Vi faremo sapere non appena possibile.

**Comment by asqueglia** [comment]
Buongiorno, potete gentilmente riprovare e darci conferma della risoluzione del problema ?

**Comment by mrabuano** [comment]
Confermo che il problema è stato risolto
Grazie

**Comment by asqueglia** [comment]
Perfetto buona giornata.
