### ISSUE TITLE
pratica bloccata al comune di Ortucchio - immigrazione da Scandicci

### ISSUE THREAD

**Issue by BEAscandicci** [italia/anpr#2644]
ci comunica il comune di ORTUCCHIO
Piazza Alfredo Zampa, 5
67050 Ortucchio AQ
P.I./C.F. 00212110662
Tel. 0863/839117
Fax. 0863/830208
E-mail: ufficioanagrafe@comunediortucchio.it
PEC: comunediortucchioaq@pec.it

che per la chiusura della pratica di iscrizione anagrafica
n. 10 avviata in data 14-04-2021  per la persona con id ANPR 60117527 risulta esistente un procedimento in
corso nel Comune di Scandicci.
Dalla consultazione dell'elaborazione risultano i seguenti errori:
- EN 531 E Operazione non consentita: Per il soggetto esiste un
procedimento aperto dal Comune di Scandicci (FI) con pratica ANPR:
36195116, 36194974.
- EN 527 E Informazioni da fornire in caso di assistenza: ID operazione
ANPR 507997459.

non siamo riusciti a trovare l'operazione che blocca tale pratica, la persona che comunque ha iscritto la persona suindicata è attualmente in pensione,
si chiede di poter sbloccare la situazione e/o comunicare al comune di Ortucchio come si può risolvere,
grazie in anticipo

Chiara Narduzzi 
Comune di Scandicci
c.narduzzi@comune.scandicci.fi.it
0557591233

**Comment by rvinzani** [comment]
Il messaggio indica che esiste un procedimento aperto dal comune di Scandicci. probabilmente si tratta di una pratica chiusa nel vostro gestionale ma rimasta aperta in ANPR. Chiunque del comune sia abilitato ad accedere ad ANPR può chiudere la pratica seguendo le istruzioni del documento che allego:
[Chiusura Procedimento.pdf](https://github.com/italia/anpr/files/6421219/Chiusura.Procedimento.pdf)
