### ISSUE TITLE
WEB APP Risoluzione disallineamenti Consolato - errore AEE96

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2645]
Buongiorno, per il Comune di Vigevano subentrato il 24/03/21.

Hanno ricevuto comunicazione dal consolato con la richiesta di verifica e allineamento del seguente soggetto:
IDANPR 111050339 è un AIRE che ha un CF assegnato dal gestionale ma non presente in AT 
Da WEBAPP stamattina abbiamo provato ad eliminare il disallineamento confermando i dati del CONSOLATO e/o del COMUNE, giustamente ci chiede se vogliamo attribuire il CF al soggetto ma alla risposta affermativa la WEBAPP restitusce il seguente errore: AEE96 Operazione non effettuabile. 

Poichè il comune nei giorni precedenti ha fatto numerose prove tutte andate in negativo dal gestionale, vi chiediamo se possibile eliminare eventuali comunicazioni in sospeso (abbiamo provato a cercarle in WEBAPP ma non ne risultano) e se è questo o altro motivo che non permette l'assegnazione del CF. 

Si resta a disposizione per ulteriori chiarimenti se necessari 

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SPA
C. +39 3346216774

**Comment by ncapozzi** [comment]
Buonasera,
è necessario preventivamente effettuare una mutazione famiglia/convivenza con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO e data di decorrenza = alla data di decorrenza dell'attuale residenza del cittadino per rimuovere il carattere "-" all'inizio del toponimo  <denominazione>- VIA BOSCIORINA</denominazione>.

N. Capozzi
