### ISSUE TITLE
[RICHIESTA INFORMAZIONI] Richiesta informazione configurazione ambiente di produzione

### ISSUE THREAD

**Issue by johnatandante** [italia/anpr#2646]
Salve a tutti,
in base alla documentazione reperibile al sito

- [Linee Guida - Innovazione.gov.it](https://innovazione.gov.it/dipartimento/focus/linee-guida-onboarding-anpr/#i-passi-operativi)

è previsto un censimento delle postazioni di lavoro per i comuni subentranti o già subentranti.
Questo censimento vale anche per i server da cui vengono effettuate le chiamata ai servizi di ANPR?

Nell'attuale sistema in uso dei comuni non è prevista una sezione come descritta nel documento [Guida operativa per il censimento degli utenti e delle postazioni e delle successive attività di consegna delle smart card] (https://assets.innovazione.gov.it/1615554178-guida-operativa-censimento-utenti-e-postazioni-v-30-01-19.pdf)

**Comment by Leonforte** [comment]
Buongiorno, non è previsto un censimento specifico per le postazioni di lavoro, ovvero all'atto del censimiento degli utenti effettuato prima del subentro e come descritto nel documento guida-operativa-censimento-utenti-e-postazioni-v-30-01-19.pdf, vengono create le utenze inserite nel censimento e diversi certificati di postazione sulla base del numero di postazioni dedicate al sistema anagrafico del comune indicate nella scheda di monitoraggio dal comune stesso ( circolare 29 luglio 2016, n. 13). Tra questi certificati ne è presente uno (prodotto di default) denominato [istat comune]-CO-9999 che è dedicato alle apparecchiature server. Altri certificati [[istat comune]-PC-[progressivo] possono comunque essere richiesti dall'amministratore locale delle postazioni ALP attraverso l'utilizzo della console di sicurezza nella web app ANPR.  Resta comunque responsabilità dell'ALP, come da normativa, la tenuta di un registro riportante l'associazione tra il certificato e la postazione dove lo stesso rsulta installato. Buon lavoro, saluti

**Comment by johnatandante** [comment]
Grazie, rispetto alla documentazione precedente, ho trovato l'area che ci servica nella sezione Amministrazione> Gestione Dati Del Comune dove c'è un'area "Informazioni aggiuntive" con i server abilitati
