### ISSUE TITLE
[Documentazione] Disallineamento documentazione

### ISSUE THREAD

**Issue by johnatandante** [italia/anpr#2647]
Nella particolare specie segnalo che:

- la documentazione è totalmente disallineata con il documento [Configura la tua postazione (PDF)](https://assets.innovazione.gov.it/1615554169-configurazione-della-postazione-per-l-accesso-al-sistema-web-anpr-e-operazioni-propedeutiche-al-subentro-v-3.pdf)
- non c'è nessun riferimento che collega la sezione [Strumenti di lavoro](https://www.anpr.interno.it/il-progetto/strumenti-di-lavoro/) alla guida di configurazione delle postazioni ANPR

E' possibile avere un punto coerente per la documentazione?

**Comment by Leonforte** [comment]
Di seguito i documenti di riferimento
[Guida operativa censimento utenti e postazioni V. 30.01.19.pdf](https://github.com/italia/anpr/files/6427866/Guida.operativa.censimento.utenti.e.postazioni.V.30.01.19.pdf)
[Configurazione della postazione per l'accesso al sistema web ANPR e operazioni propedeutiche al subentro v.3.pdf](https://github.com/italia/anpr/files/6427868/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.v.3.pdf)

**Comment by johnatandante** [comment]
Grazie
