### ISSUE TITLE
CAMBIO DATA DI NASCITA - OPERAZIONE NON EFFETTUABILE Codice: AEE95

### ISSUE THREAD

**Issue by carla967** [italia/anpr#2648]
COMUNE DI IVREA (TO) - OPERAZIONI TENTATE DA WEBAPP
L'individuo 28637842 è in possesso in un omocodice; il comune deve modificare la data di nascita ed il nuovo codice che verrebbe generato non è presente in AE.
Tuttavia non riusciamo ad effettuare la modifica con la generazione del nuovo CF in quanto otteniamo sempre lo stesso errore riportato in oggetto.
Come possiamo procedere?

**Comment by frmariani** [comment]
Un codice fiscale risolto da omocodia non può essere modificato con le operazioni disponibili nel sistema ANPR; deve scrivere alla Direzione Centrale di Agenzia delle Entrate allegando la documentazione del caso a supporto.
Per ulteriori delucidazioni in merito chiamate l'assistenza ANPR al numero verde 800863116
