### ISSUE TITLE
[4001] Errore richiesta estrazione dati anagrafici

### ISSUE THREAD

**Issue by AlessandraB19** [italia/anpr#2652]
Vorremmo estrarre i dati anagrafici, quindi utilizzare il WS 4001, in base al codice fiscale inviato in input. Noi siamo un'azienda che lavora per conto di alcuni comuni già subentrati e vorrei capire se e come poter testare il WS di nostro interesse. Ho provato ad effettuare alcuni test ma ricevo un errore legato alla validità del certificato in nostro possesso che in effetti è quello valido per l'ambiente di free test di ANPR. Posso avere ulteriori informazioni su come procedere nel nostro specifico caso? Grazie.

**Comment by gife67** [comment]
Chiudo la issue, per ulteriori chiarimenti potete riaprirne una nuova.
Buona giornata
