### ISSUE TITLE
[italia/anpr] [6001]  Internal Error ( From server ) 

### ISSUE THREAD

**Issue by matteo-mulas** [italia/anpr#2653]
Salve, 

stiamo provando a scaricare dall'ambiente di test (codice mittente 888231)  un certificato attraverso il ws6001. 

Riceviamo la risposta:
`<?xml version='1.0' ?>
<env:Envelope xmlns:env='http://www.w3.org/2003/05/soap-envelope'>
    <env:Body>
        <env:Fault>
            <env:Code>
                <env:Value>
                    env:Receiver
                </env:Value>
            </env:Code>
            <env:Reason>
                <env:Text xml:lang="en-US">
                    Internal Error (from server)
                </env:Text>
            </env:Reason>
        </env:Fault>
    </env:Body>
</env:Envelope>`

La richiesta si trova nel seguente allegato  [request.txt](https://github.com/italia/anpr/files/6442017/request.txt)

Restiamo in attesa di un cortese riscontro.

Saluti.

**Comment by gife67** [comment]
Buongiorno,
cortesemente potete riprovare la richiesta.

**Comment by gife67** [comment]
Immagino che nelle trace che avete riportato avete troncato voi volutamente le parti relative le signature ed i certificati, perchè se sono le esatte trace del messaggio che inviate il problema è sicuramente questo.
Ci risultano delle interrogazioni effettuate con successo verso il servizio 6001, il 20.04.2021 con le stesse credenziali. State provando da un altra postazione con una versione differente del client rispetto a quella che ha avuto esito positivo? 
Comunque se mi inviate il vostro indirizzo IP con cui vi presentate su internet, proviamo ad abilitare delle trace di dettaglio per verificare quale sia l'elemento non conforme.

**Comment by matteo-mulas** [comment]
Buongiorno. 
Si confermiamo che abbiamo troncato le parti relative ai certificati e alle signature. Se vi servono possiamo mandarvi il file completo attraverso un email personale. 

Le interrogazioni effettuate con successo sono state eseguite attraverso il vostro client java. 
Mentre ora stiamo provando con un nuovo applicativo scritto in nodejs. 
L'IP utilizzato 93.64.184.138 

Attendiamo un vostro riscontro.
Saluti.

**Comment by gife67** [comment]
Buongiorno,
cortesemente se potete riprovare a mandare qualche richiesta in modo che possiamo tracciare le vostre richieste e verificare il problema.
Grazie

**Comment by matteo-mulas** [comment]
Buongiorno. Abbiamo appena effettuato tre nuove richieste.

**Comment by gife67** [comment]
Questa è la trace delle vostre richieste con il relativo errore:

Wed May 12 2021 11:06:48 [0x80e00384][ws-proxy][debug] source-https(ANPR_WSP_fsh): tid(770810239)[93.64.184.138]: WS-Proxy ANPR_WSP_SOA operation emissioneCertificato does not match SOAP operation as required by WS-I BP1.0/1.1 R2744 or R2745: received (Richiesta6001) required (Richiesta6001). Received protocol 'http://schemas.xmlsoap.org/wsdl/soap12/', required protocol 'http://schemas.xmlsoap.org/wsdl/soap/'. Received SOAPAction ((null)) required SOAPAction (). SOAPAction policy is lax.

C'è qualche problema di conformità sul protocollo SOAP. Vi consiglio di prendere la trace di un messaggio ok, fatto con il client java e di verificare le differenze con il messaggio che state producendo con nodejs, verificando i vari namespace.
Un altra prova che potreste fare è quella di utilizzare:
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope"
al posto di:
xmlns:soap="http://www.w3.org/2003/05/soap-envelope"

Attendiamo le vostre verifiche

**Comment by matteo-mulas** [comment]
Buongiorno. 

Abbiamo riprovato a eseguire la chiamata verso il servizio cambiando il namespace come da voi suggerito. 
La risposta è "Internal error ( from Client)".

Alleghiamo la richiesta [request.txt](https://github.com/italia/anpr/files/6520951/request.txt)
Se avete bisogno vi inviamo i dati completi senza oscurare le signature e i certificati. 

Restiamo in attesa di un cortese riscontro. 
Saluti.

**Comment by gife67** [comment]
Buongiorno,
l'errore riscontrato adesso è il seguente ed è relativo a problemi di schema validation:
https://192.168.89.238:56443/ANPR6001ServizioCertificazione/AnprService6001: cvc-elt 4.1: element {urn:oasis:names:tc:SAML:2.0:assertion}AttributeValue xsi:type value xs:string is not a valid name

Questo è dovuto al fatto che il namespace xs non è definito e dovrebbe essere xsd:string. 
Provate ad impostare secondo le indicazioni.
Saluti
