### ISSUE TITLE
Problema iscrizione individuo gia' presente in ANPR

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#2654]
Buongiorno,
Il comune di Treviso deve iscrivere il soggetto ID ANPR 88501805.
Questo soggetto era stato iscritto nel 2004 in ANPR a SAN BIAGIO DI CALLALTA (TV), 
poi era stato cancellato da ANPR per IRREPERIBILITÀ il 29/04/2020 ed tuttora è cancellato da ANPR.
La richiesta di iscrizione (ID ANPR 522825600) però ci risponde "idSchedaSoggettoANPR 88501805 
non presente o dati anagrafici incongruenti".

Come si deve procedere, visto che nella stessa famiglia viene iscritta, con la stessa pratica 
anche il soggetto ID ANPR 88501856, ma questi non ha dato nessun problema?

Si ringrazia
Carla Musian
applicativo Ascotweb
GPI

**Comment by rvinzani** [comment]
Può ora precedere con la reiscrizione. Chiudo pertanto la issue. Se avesse ancora problemi può riaprire una nuova issue che faccia riferimento a questa
