### ISSUE TITLE
ERRORE DATA DECORRENZA MODIFICA GENERALITÀ' SBAGLIATA

### ISSUE THREAD

**Issue by Pellet1285** [italia/anpr#2655]
Buongiorno, avendo modificato le generalità di una persona ( in particolare nome e cognome), è stata sbagliata la data di decorrenza di tale modifica.
E' possibile modificare tale decorrenza? in quanto ciò da problemi all'INPS per la gestione di una domanda fatta dal cittadino.

Grazie

tel 0815217121

**Comment by Pellet1285** [comment]
Buongiorno, ci sono aggiornamenti in merito? Grazie

**Comment by rvinzani** [comment]
Chiudo la issue in quanto il problema si sta risolvendo tramite contatto diretto
