### ISSUE TITLE
Nuova carta operatore WEBAPP. Mancato riconoscimento certificato.

### ISSUE THREAD

**Issue by AndreaBruni** [italia/anpr#2656]
Buongiorno,

Seguendo le ultime istruzioni disponibili su

https://github.com/italia/anpr/files/5276068/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.v.2.pdf

ho provveduto a installare presso il Comune di Battuda (PV) i nuovi driver (Infocert SafeDive 3.4.1) per abilitare la nuova carta (vedi immagini allegate) dell'operatore Sara Rossi.

I certificati non vengono riconosciuti nemmeno da Gosign (installato per scrupolo e verifica).

Le carte del Sindaco (Luigi Santagostini) e del collega (Aldo Scarioni), che sono di vecchio tipo, funzionano perfettamente.

A questo punto non saprei cosa fare....

Ringrazio anticipatamente e saluto cordialmente

Andrea Bruni (CED esterno)

Il comune opera in regime di 
![IMG_20210507_115505](https://user-images.githubusercontent.com/79931693/117647004-baa75b80-b18c-11eb-8c22-b37dd2a0462c.jpg)
![IMG_20210507_115513](https://user-images.githubusercontent.com/79931693/117647007-bb3ff200-b18c-11eb-9ebc-01b863612142.jpg)

**Comment by Leonforte** [comment]
Buongiorno, cosa intende per 
"I certificati non vengono riconosciuti nemmeno da Gosign (installato per scrupolo e verifica) "  ?
C'è un problema con il pin o il Dike non legge proprio la carta ?
Le suggerisco di provare con le istruzioni presenti al link :

https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf

Buon lavoro, saluti

**Comment by AndreaBruni** [comment]
Buongiorno,

ahimé non legge proprio la carta.
Provo con le nuove istruzioni e poi la aggiorno.
Per ora grazie!
Un cordiale saluto.

**Comment by AndreaBruni** [comment]
Buongiorno,

purtroppo il software di attivazione di Infocamere rileva che la carta risulta già attivata. 
Pertanto siamo al punto di prima: PIN corretto ma sia Dike che tantomeno il portale https://dp.anpr.interno.it/com rilevano la carta e il relativo certificato.

Sono in panne!!!

In attesa di riscontro, saluto cordialmente.

**Comment by Leonforte** [comment]
Buongiorno, abbiamo richiesto una nuova carta che sarà disponibile a breve presso la Prefettura di competenza, buon lavoro, saluti
