### ISSUE TITLE
INSERIMENTO PRECEDENTE DENOMINAZIONE COMUNE

### ISSUE THREAD

**Issue by Annalisaf** [italia/anpr#2658]
Buongiorno,
sono Annalisa Franceschetti Responsabile Anagrafe del Comune di Corridonia.
Al fine di caricare atti di stato civile abbiamo la necessità che all'attuale denominazione del nostro Comune - CORRIDONIA, oltre a PAUSULA (deonominazione dal 18/03/1861 al 24/10/1931), sia anche collegata la denominazione precedente AL 18/03/1861 di MONTOLMO.

E' possibile?
Cordiali saluti
Annalisa Franceschetti

**Comment by rvinzani** [comment]
Gent.le Sig.ra Fraschetti, faremo le verifiche con Istat e le faremo sapere

**Comment by rvinzani** [comment]
Gent.le Sig.ra Fraschetti, la tabella dei comuni di ANPR è ad uso dell'Anagrafe attualmente non dello stato civile ed è per tale motivo che la storicità del comune si ferma ad una certa data. Credo che lo stato civile sia gestito attualmente dal suo gestionale locale che può in ogni caso aggiungere la denominazione storica del vostro comune. Chiudo le issue. Se ritiene che siano necessari ulteriori chiarimenti la prego di aprire una nuova issue che faccia riferimento a questa
