### ISSUE TITLE
AEE97 - Operazione non Effettuabile

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2659]
-ANPR - Ambiente di Produzione-
Buongiorno,
sembra che qualsiasi operazione di validazione o attribuzione sul CF venga rifiutata,
otteniamo sempre l'errore AEE97 - Operazione non Effettuabile

Grazie

**Comment by siscomanpr** [comment]
Buongiorno, 
anche alcuni nostri clienti segnalano lo stesso problema.

**Comment by cmigliardi** [comment]
salve l' errore AEE97 è stato risolto . potete  riprovare ?  grazie

**Comment by cmigliardi** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa.
