### ISSUE TITLE
[6001] - Errore bloccante su rilascio Stato di Famiglia

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#266]
Corbetta, ambiente di produzione.

Buongiorno per l'individuo MHMRHD65A07Z236K non riusciamo ad ottenere la certificazione di Stato di Famiglia a causa dell'errore: EN222 - Il certificati di stato di famiglia con rapporti di parentela non puo' essere emesso fiche' non si rivedono i rapporti di parentela con l'intestatario. (ID operazione ANPR 866338).
Non capiamo cosa significa ne come possiamo risolvere questo errore dato che i rapporti di parentela sono tutti presenti e congruenti.
Anche il forzare la certificazione non produce alcun esito e il cittadino avrebbe urgenza di avere il proprio stato di famiglia, grazie.

**Comment by fugerit79** [comment]
Buonasera.
La famiglia risulta non certificabile. Ne stiamo analizzando la causa. In ogni caso questa situazione è sanabile con un 5001 inserendo nella lista controlli il codice “FC” valorizzato a “S”
Saluti

Matteo Franci

**Comment by mttfranci** [comment]
Buonasera.
La famiglia risulta non certificabile. Ne stiamo analizzando la causa. In ogni caso questa situazione è sanabile con un 5001 inserendo nella lista controlli il codice “FC” valorizzato a “S”
Saluti

Matteo Franci

**Comment by LucaBonini64** [comment]
Buongiorno,
La ringrazio ma quanto indicato non è di alcun aiuto perché non possiamo 'lanciare un 5001 inserendo in lista controlli il parametro FC valorizzato a S'.
Noi sviluppiamo programmi di back-office per i Servizi Demografici e questi programmi richiamano i WS solo secondo le specifiche che avete documentato. Nelle liste dei Controlli avete inserito degli oggetti e sappiamo che possono avere un nome ed un valore ma ci sono sconosciuti i nomi, i valori e la modalità di utilizzo degli stessi e quindi non è stato previsto l'inserimento a libero piacimento da un utente comunale, pertanto la prego di rendere la famiglia certificabile per poter procedere con il rilascio dello stato di famiglia. Grazie.
Luca Bonini

**Comment by gcarbonin** [comment]
I campi necessari per questo tipo di operazione sono previsti da tempo e documentati ulteriormente con l'ultima versione delle specifiche; in caso di dubbi siamo a disposizione per qualsiasi chiarimento.
Come è facile comprendere, la richiesta di "modifica manuale" non può essere evasa in quanto si tratta di una base dati di produzione; quanto meno la richiesta dovrebbe provenire dal comune ed essere indirizzata al Ministero dell'Interno.
Il comune può effettuare la variazione autonomamente utilizzando l'applicazione WEB (mutazione famiglia/convivenza). In caso di problemi, siamo a disposizione per guidarlo nell'operazione.
