### ISSUE TITLE
Smarrimento Prima parte del PIN e del PUK

### ISSUE THREAD

**Issue by FraAld** [italia/anpr#2660]
Buongiorno

causa smarrimento, richiedo la prima parte del  PIN e del  PUK della smart card ANPR 
Numero  seriale  036021  1207100000011779
Comune di Medolla (MO)

**Comment by Leonforte** [comment]
Buon pomeriggio, quanto richiesto è stato inviato all'indirizzo mail fornito all'atto del censimento.
Le ricordo che, in caso di eventuali problemi con il PIN, si porebbe rendere necessario eseguire le istruzioni indicate al link : 

https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf

Buon lavoro, saluti
