### ISSUE TITLE
[servizio 6001] [errore EN208] Certificati, importo bollo deve essere maggiore 0,0

### ISSUE THREAD

**Issue by carminepat** [italia/anpr#2661]
Salve, buongiorno
vi contatto per una segnalazione che ricevo durante l'invocazione del servizio 6001 per il rilascio di un qualsiasi certificato. Se seleziono e quindi invio durante la chiamata del servizio un motivo di esenzione per il bollo, inviando quindi il bollo a 0 (zero) mi segnala un errore con codice: EN208 "Importo bollo deve essere maggiore di 0.0 euro". Tutto questo dopo aver configurato nell'area amministrazione della web app ANPR la possibilità di rilasciare certificati con bollo esente. Cod.istat comune: 065157, idOperazioneANPR: 530318901

**Comment by mttfranci** [comment]
Salve, dall'amministrazione comune della web app, potete solo consentire l'abolizione dei diritti di segreteria.
Al momento il bollo può avere valore '0' solo in presenza di un motivo di esenzione di bollo.

La vostra richiesta è di questo tipo : 

```
      <datiControllo>
        <cognomeUffAnagrafe>S.p.A.</cognomeUffAnagrafe>
        <nomeUffAnagrafe>Publisys</nomeUffAnagrafe>
        <tipoRichiedente>2</tipoRichiedente>
        <tipoRichiesta>1</tipoRichiesta>
        <paEstera>0</paEstera>
        <emissione>3</emissione>
        <bollo>0</bollo>
        <bolloVirtuale>0</bolloVirtuale>
        <diritti>0</diritti>
      </datiControllo>
```

Ma è prevista che il bollo abbia un valore, oppure sia impostata una esenzione di bollo, ad esempio : 

`<esenzioneBollo>2</esenzioneBollo>`

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR
