### ISSUE TITLE
Data di nascita non completa

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2663]
Buongiorno,
abbiamo il caso di un cittadino marocchino con data di nascita senza giorno e senza mese (xx/xx/1977).
Il cieonline  non permette l'emissione della carta elettronica (allego errore).

Con cittadini in questa situazione quindi possiamo emettere solo una cartacea?

Grazie,
cordiali saluti.
[doc07106920210513072058.pdf](https://github.com/italia/anpr/files/6470905/doc07106920210513072058.pdf)

**Comment by rvinzani** [comment]
Buongiorno, avete inserito il cittadino indicando correttamente il flag senzaGiorno/senzaMese? Mi può indicare l'idANPR?

**Comment by rvinzani** [comment]
Non avendo ricevuto risposta chiudo la issue. Nel caso fosse necessario un ulteriore chiarimento si prega di aprire una nuova issue che faccia riferimento a questa stessa

**Comment by katiavacchi** [comment]
Buongiorno,
chiedo scusa per il ritardo: l'idANPR del cittadino è 19753414.
Grazie.
