### ISSUE TITLE
Collegamento codici fiscali con 4 campi da variare #1972

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2664]
Buongiorno,
faccio riferimento a un ticket aperto a febbraio 2020 relativo alla modifica dei data anagrafici di una cittadina straniera per la quale non ci era possibile procedere perché i cambi da variare erano almeno 4 (numero ticket dell'assistenza Anpr 21143730).
Come da voi suggerito abbiamo scritto a entrate.archivioanagrafico@agenziaentrate.it per fare collegare i codici fiscali.
Ora l'Agenzia delle Entrate ci ha comunicato di averlo fatto. Da webapp abbiamo quindi provato ad allineare i dati Anpr con quelli di AE (in Agenzia delle Entrate infatti la posizione è corretta) MA non è possibile. Allego errore.

Come possiamo procedere?

Grazie,
cordiali saluti
Katia Vacchi
![Cattura](https://user-images.githubusercontent.com/57749903/118093308-8cfd2500-b3cd-11eb-8cd3-e5e30678b870.JPG)

**Comment by frmariani** [comment]
Abbiamo effettuato l'operazione di "svalidazione" del codice fiscale in modo da permettervi la modifica.

**Comment by frmariani** [comment]
ho verificato che l'operazione di modifica è stata eseguita correttamente pertanto chiudo la issue
