### ISSUE TITLE
Annullamento di iscrizione anagrafica da parte di un comune di precedente residenza

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2665]
In data 06/11/2018 abbiamo abbiamo iscritto nel Comune di Valsamoggia con provenienza dal Comune di Budrio la famiglia ID ANPR 19634293 costituita dalle persone con identificativo 34319036 (IS) e 34319037 (figlio). La collega ed io ci siamo casualmente accorte che in realtà Budrio aveva respinto la pratica di residenza ma la mutazione aveva avuto effetto solo nell'applicativo locale e non in ANPR. Da Budrio è stato aperto al vostro call center il ticket n. 22768933 ed abbiamo già ricevuto la risposta via mail.
In sostanza io devo annullare progressivamente le operazioni effettuate sul soggetto 34319036, partendo dalla più recente, fino a far sì che in ANPR risultino nuovamente residenti a Budrio che, a quel punto, potrà annullare le sue mutazioni e consentire a me di iscriverli nuovamente.
Tuttavia vorrei precisare che attualmente la famiglia è composta da altre 6 persone, oltre alle due iniziali, iscritte con 5 procedimenti diversi, per provenienza da estero, altri motivi e nascita, oltre che immigrazione da un comune terzo.
Andando ad annullare l'iscrizione dell'intestatario scheda che per primo è stato iscritto (ammesso che mi venga consentito senza dover prima annullare tutte le mutazioni delle altre 6 persone) vorrei ricevere rassicurazione sul fatto che la soluzione prospettata sia corretta.

**Comment by frmariani** [comment]
Credo che sia necessario un contatto diretto; ho aperto il ticket 22776643 a suo nome e la contatterò domani mattina.
