### ISSUE TITLE
Allineamento dati AIRE su richiesta consolare ante subentro

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2666]
Buongiorno per il comune di Vigevano subentrato il 24/03/2021 non riusciamo a risolvere un caso di allineamento richiesto dal consolato prima del subentro e mai gestito dal comune. 

Soggetto ANPR ID111050577
Richiesta consolato nr 446647307 del 05/02/2021 

Siamo riusciti ad attribuire il CF in maniera da aprire il dettaglio della richiesta (senza non permetteva nemmeno di visualizzare il dettaglio) ma provando ad attribuire il CF il sistema segnala errore "ES004 Deve essere impostato almeno 1 tra nome e cognome e almeno un identificativo tra codice fiscale, identificativo soggetto attribuito dal comune, identificativo soggetto attribuito da ANPR" immaginiamo perchè la richiesta consolare è sprovvista di ID ANPR poichè antecedente al subentro. E' possibile forzare l'Id del soggetto su tale richiesta consolare? Oppure debbono chiedere al consolato di rifarla?

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SPA
Cell. 3346216774

**Comment by ncapozzi** [comment]
Buonasera,
potete dire al Comune di riprovare. Faccio presente che il CF presente sui dati del cittadino in ANPR non esiste su Agenzia delle Entrate e quindi nel momento in cui si confermano i dati di ANPR su richieste consolati verrà visualizzato un msg che richiede l'attribuzione del CF.
Nel caso in cui il Comune avesse ancora dei problemi indicate per favore un loro riferimento con recapito al quale ricontattarli.
Grazie

**Comment by CGIRELLI-HUB** [comment]
Buonasera, grazie risolto tutto si sapevamo di dover attribuire il Cf
poichè non risultava in agenzia ed era proprio in questa fase che dava
errore.
Ora il comune non ha altre richieste in sospeso da consolato e li abbiamo
sensibilizzati affinchè controllino le notifiche in webapp per le richieste
consolari.

Cordiali saluti
       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: ***@***.*** L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno gio 13 mag 2021 alle ore 15:50 ncapozzi ***@***.***>
ha scritto:

**Comment by ncapozzi** [comment]
Perfetto grazie
