### ISSUE TITLE
WS - A006 modifica residenza estera

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2667]
Buongiorno,
COMUNE CASERTA 061022 - PROD
Con id operazione ANPR 531557117 abbiamo inviato una modifica dei dati relativi all'indirizzo di residenza estero del soggetto AIRE.
Dopo tale operazione, però, consultando la sua scheda anagrafica non risulta alcuna variazione.
Abbiamo utilizzato tipo mutazione 2 come indicato nella documentazione.
Grazie

**Comment by rinonasti** [comment]
Chiedo scusa il ws richiamato è 5001

**Comment by ncapozzi** [comment]
Buonasera,
l'operazione indicata è una mutazione famiglia/convivenza (ws 5001) con tipo = 2 COMPOSIZIONE SCHEDA. Questo tipo di mutazione deve essere utilizzata per modificare i legami di parentela dei componenti la famiglia con l'intestatario. Per modificare la residenza della medesima famiglia anagrafica deve essere richiamato il medesimo WS 5001 ma con tipo = 4 RESIDENZA SCHEDA.

**Comment by rinonasti** [comment]
MODIFICATO :
codiceErroreAnomalia>EF041</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Per la mutazione richiesta e' obbligatorio specificare i dati della residenza</testoErroreAnomalia> 
  </errore>
- <errore>
  <codiceErroreAnomalia>EN527</codiceErroreAnomalia> 
  <tipoErroreAnomalia>E</tipoErroreAnomalia> 
  <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-13 17:31:33 , idOperazioneANPR 531772370

**Comment by ncapozzi** [comment]
Come indica il messaggio di errore, nella richiesta 5001 trasmessa non sono riportati i dati della nuova residenza
