### ISSUE TITLE
RESIDENZA TEMPORANEA 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2668]
Buongiorno,
COMUNE CASERTA 061022 - PROD
Dove possiamo reperire documentazione circa la funzione WEBAPP "Residenza Temporanea".
ES. Vengono comunicate alla ASL ?
      la data di scadenza è calcolata?
      non ha alcun effetto sulla residenza effettiva? 

Grazie

**Comment by rvinzani** [comment]
Buongiorno, per la gestione dei temporanei, disponibile solo da web app può selezionare la lente in alto a destra per consultare la guida on lene. Tali residenze non vengono comunicate alle ASL, non è calcolata la data di scadenza e non ha nessun effetto sulla residenza effettiva
