### ISSUE TITLE
STATO ESTERO URSS

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2669]
buongiorno, per il comune di SAPPADA subentrato il 14/05/2021.
il soggetto con IDANPR 154285963 è subentrato in ANPR con località di nascita KURSK - STATO ESTERO 998 NON ATTRIBUIBILE 
Il cf presente in AE e in Anagrafe riporta correttamente il codice catastale dell'URSS, ed è stato validato dopo il subentro in Webapp con la funzione Risoluzione disallineamenti con AE. Oggi abbiamo provato da webapp ad inserire la descrizione corretta dello stato tramite una Mutazione di tutti i dati sul luogo di nascita abbiamo provato ad inserire i seguenti dati:
Località: KURSK - Descrizione stato: URSS - cod. stato NON ATTRIBUIBILE - l'operazione non è andata a buon fine segnala: AEE95 Operazione non effettuabile - Id operazione 534805275 - 
Come possiamo risolvere? Grazie.
Cordiali saluti

Cinzia Girelli
GPI SPA
Cell. 3346216774

**Comment by ncapozzi** [comment]
Buonasera,
potete provare ad eseguire nuovamente l'operazione per favore?

**Comment by CGIRELLI-HUB** [comment]
potremo riprovare domani poichè il cliente è assente oggi.
grazie
cordiali saluti
       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: ***@***.*** L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno mar 18 mag 2021 alle ore 18:11 ncapozzi ***@***.***>
ha scritto:

**Comment by ncapozzi** [comment]
Non avendo più ricevuto altri riscontri si chiude la issue

**Comment by CGIRELLI-HUB** [comment]
Mi scusi tanto ma per assenza del cliente abbiamo dovuto rimandare la risoluzione. Ad ogni modo è andato a buon fine 
Grazie - Cordiali saluti
