### ISSUE TITLE
Certificato di residenza e cittadinanza per AIRE

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#267]
Poggio a Caiano (PO) - ambiente di produzione

Il procedimento di iscrizione elettorale per compimento della maggior età durante la revisione semestrale delle liste prevede l'inserimento nel fascicolo personale degli elettori del certificato di cittadinanza italiana. Per comodità viene prodotto cumulativamente con quello di residenza costituendo un certificato di residenza e cittadinanza.
E' prassi di produrre il certificato anche per gli AIRE, come da disposizioni ministeriali impartite con Circolare Ministero dell'interno - Dip. affari interni e territoriali 6/3/2003 n. 10 prot.200300810/15600/7503.
Abbiamo constatato che ANPR non soddisfa la richiesta di rilascio del documento "in quanto il soggetto è iscritto all'AIRE".
Allego il testo della circolare.
[CircMinInt 10 del 2003.txt](https://github.com/italia/anpr/files/1231376/CircMinInt.10.del.2003.txt)

Bruno Filipazzi

**Comment by mttfranci** [comment]
Buonasera.
Al momento c'è un intervento sui certificati per i soggetti AIRE in corso, avviseremo non appena sarà disponibile nei vari ambienti.
Saluti

Matteo Franci

**Comment by gcarbonin** [comment]
I certificati ora vengono prodotti
