### ISSUE TITLE
DATA DI ISCRIZIONE ANPR

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2671]
Soggetto residente per nascita nel nostro Comune emigra in un altro Comune nel 2005. Poi fa rientro nel nostro Comune nel 2017.
Al momento del subentro sono stati caricati i seguenti dati:
decorrenza residenza XX/XX/2017
Data iscrizione : data di nascita
Motivo di iscrizione: Immigrazione (da comune non subentrato)
Per data di iscrizione cosa si intende? La data di reiscrizione (2017) o la data di prima iscrizione (che coincide con la data di nascita)?
Si dovrebbe procedere ad una rettifica facendo figurare quale delle due date?
CONZA GIANPAOLO
COMUNE DI CASTELLAMMARE DI STABIA
AMBIENTE PRODUZIONE

**Comment by rvinzani** [comment]
Per data iscrizione si intende la data di ingresso nel comune che può coincidere con la data decorrenza della residenza se il soggetto non ha più cambiato indirizzo

**Comment by gianpaol** [comment]
la data di primo ingresso o di ultimo ingresso? il soggetto è entrato per nascita, emigrato e poi ritornato.  In data iscrizione quale data dovrebbe figurare? presumo la data di reiscrizione...

**Comment by rvinzani** [comment]
Sì, esatto

**Comment by gianpaol** [comment]
La ringrazio molto
