### ISSUE TITLE
Accesso WebApp carta sindaco

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2672]
La smartcard del sindaco è del vecchio modello. È stato installato il certificato di postazione pc-0001-p12 ma, nonostante in apparenza la configurazione del certificato e del lettore siano corretti, dopo aver selezionato il certificato di postazione la pagina gira dp2 e non compare il riquadro con il CF dell'intestatario della scheda. La scheda pare attiva perché utilizzando IDprotect Manager viene rilevata correttamente e l'inserimento del PIN si concludo con esito positivo. È possibile che il certificato sia corretto.
La segnalazione viene aperta per il comune di Lungro (CS). È possibile prendere contatto direttamente con il comune oppure, fosse il certificato corrotto, reinviare sempre al comune quello nuovo.
Saluti

**Comment by Leonforte** [comment]
Buongiorno,
abbiamo verificato e il certificato di postazione che state utilizzando risulta purtroppo corrotto. Ne stiamo generando un altro che appena disponibile sarà inviato via mail. Ci scusiamo per l'inconveniente, buona giornata

**Comment by Leonforte** [comment]
Il secondo certificato di postazione è stato inviato a : anagrafe.lungro@tiscali.it 

Buon lavoro, saluti
