### ISSUE TITLE
Numero Cittadini in ANPR

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2674]
Solo per curiosità: il conteggio pubblicato sul sito www.anpr.interno.it attualmente di 64.165.774 non conteggerà solamente i residenti. Conta anche aire o cancellati o entrambi?

**Comment by FilippoPapi** [comment]
buongiorno,
il numero è comprensivo degli AIRE e di tutti i soggetti presenti nella banca dati, se naviga il sito e arriva nello stato di avanzamento trova delle statistiche di dettaglio
saluti
