### ISSUE TITLE
[6001Certificazione] Ambiente di PROD Comune di Sacile - Chiamata SOAP rejected by policy 

### ISSUE THREAD

**Issue by johnatandante** [italia/anpr#2675]
Salve a tutti, 
stiamo installando il nuovo servizio per il Comune di Sacile (codice istat **093037**) relativo alla consultazione dei certificati ANPR che sfrutta le chiamate SOAP verso il vostro endpoint 

Abbiamo testato con successo la fase l'ambiente di test, ma con la configurazione dell'ambiente di produzione, ovvero con l'indicazione dell'IP pubblico della macchina **54.220.58.211**, configurato anche su piattaforma web del comune di Sacile, ed utilizzanto il certificato server del comune **093037-CO-9999**.p12 non riusciamo a concludere positivamente la chiamata.
La response termina con

```xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>
```

Come per l'ambiente di test abbiamo impostato i vari timestamp a UTC, per cui gli orari delle chiamate vanno dalle ore **2021-05-25T14:40:41.001** alle ore **2021-05-25T15:10:41.001** ora italiana (GMT+2)

Riuscite ad aiutarci ad identificare l'anomalia?

**Comment by Leonforte** [comment]
Buongiorno, stiamo verificando l'abilitazione dell'indirizzo, ma servirebbe sapere anche il CF relativo all'utenza inserita nell'asserzione, grazie

**Comment by johnatandante** [comment]
Salve,
grazie per la pronta risposta.

Stiamo ricercando questa utenza
```xml
...
<codiceFiscale>
        <codFiscale>GSPLRT76M24G888W</codFiscale>
        <!--Optional: <validitaCF>None</validitaCF>-->
        <!--Optional: <dataAttribuzioneValidita>None</dataAttribuzioneValidita>-->
    </codiceFiscale>
...
```

**Comment by johnatandante** [comment]
Tendo a precisare che il nodo __Assertion__ è così valorizzato

```xml
<saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="A_a18606ca-5f99-4f6b-8d16-e8f9f17176a4" IssueInstant="2021-05-25T12:49:41.001Z" Version="2.0">
    <saml2:Issuer>XS</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="SIG-fb6f5c3a-ac7b-4800-9da8-93c0da539063">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference URI="#A_a18606ca-5f99-4f6b-8d16-e8f9f17176a4">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
<InclusiveNamespaces xmlns="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xsd xsi"/>
</ds:Transform>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>Tff7sIXi --- y7ZtUXks+0ac1VU=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>aPbPelegOMBKUxD+2+Ew3p6GKuRtad6IMIZGxHyAVGNZYfXlNt4UbFUlALqB3XRa
--- 
GolURaqZyqOnTXuCqq6wJQ==</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>MIIFDzCCAvegAwIBAgIICFoxA5eUDTgwDQYJKoZIhvcNAQELBQAwfjELMAkGA1UE
---
ASuaPfGfLxDJGD8w/L39624CTUinavaBBOZKj6/XA6YCcaYt1Gzp3tyRmnczsMwP
UdoW</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
    <saml2:Subject>
        <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">**093037-CO-9999**</saml2:NameID>
        <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml2:SubjectConfirmationData NotBefore="2021-05-25T12:48:41.001Z" NotOnOrAfter="2021-05-25T13:04:41.001Z"/>
        </saml2:SubjectConfirmation>
    </saml2:Subject>
    <saml2:Conditions NotBefore="2021-05-25T12:48:41.001Z" NotOnOrAfter="2021-05-25T13:04:41.001Z"/>
    <saml2:AuthnStatement AuthnInstant="2021-05-25T12:48:41.001Z" SessionNotOnOrAfter="2021-05-25T13:04:41.001Z">
        <saml2:SubjectLocality Address="**54.220.58.211**"/>
        <saml2:AuthnContext>
            <saml2:AuthnContextClassRef/>
        </saml2:AuthnContext>
    </saml2:AuthnStatement>
    <saml2:AttributeStatement>
        <saml2:Attribute Name="IdSede" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
            <saml2:AttributeValue xsi:type="xsd:string">**093037**</saml2:AttributeValue>
        </saml2:Attribute>
        <saml2:Attribute Name="IdPostazione" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
            <saml2:AttributeValue xsi:type="xsd:string">**093037-CO-9999**</saml2:AttributeValue>
        </saml2:Attribute>
        <saml2:Attribute Name="IdPostazioneFirmato" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
            <saml2:AttributeValue xsi:type="xsd:string">MIIH/gYJKoZIhvcNAQcCoIIH7zCCB+
---
yoU1bQdDmJoOSfWedle05REJ7UwYA==</saml2:AttributeValue>
        </saml2:Attribute>
        <saml2:Attribute Name="IdApplicazione" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
            <saml2:AttributeValue xsi:type="xsd:string">**1**</saml2:AttributeValue>
        </saml2:Attribute>
    </saml2:AttributeStatement>
</saml2:Assertion>
```

**Comment by Leonforte** [comment]
Ci occorre l'utenza che state utilizzando per l'autenticazione saml, che è sempre un CF ma deve essere utente ANPR. Dovrebbe comparire nel subject tra i dati dell'asserzione prima della richiesta, grazie

**Comment by Leonforte** [comment]
ok, non si era ancora aggiornato git

**Comment by Leonforte** [comment]
Mi sembra abbiate indicato  **093037-CO-9999**  come utente, ma non va bene, deve essere un CF di uno degli utenti di produzione del comune

**Comment by johnatandante** [comment]
Confermo che, utilizzando anche lo stesso codice fiscale che stiamo usando per prova, non è stato possibile concludere correttamente la chiamata

```xml
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>
```


Ora request (UTC):  
IP:  54.220.58.211

da cui i nodi 

```xml
...
<saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">GSPLRT76M24G888W</saml2:NameID>
...
<saml2:SubjectLocality Address="54.220.58.211"/>
...
<dataOraRichiesta>2021-05-25T14:39:55.920Z</dataOraRichiesta>
```

**Comment by Leonforte** [comment]
Corretto. L'utente se è abilitato alla web app (e quindi possiede una smart card) è anche abilitato all'utilizzo dei ws (sempre tenendo conto del profilo), mentre non vale il contrario, cioè se l'utente è censito ma non possiede una smart card non può accedere alla web app ma può utilizzare i ws. In entrambi i casi deve essere comunque utilizzato un certificato di postazione. Suppongo inoltre che, forse per semplificare, avete indicato la url https://ws.anpr.interno.it che non è quella completa per il richiamo del servizio 6001. Spero di aver chiarito, buon lavoro, saluti

**Comment by johnatandante** [comment]
Grazie,
ancora un chiarimento:  possiamo chiedere al comune di abilitare l'utente "GSPLRT76M24G888W" ed usare comunque la "postazione" del server comunale "093037-CO-9999" oppure dobbiamo chiedere di censire una nuova postazione per questo utente?

**Comment by Leonforte** [comment]
Come disposto dal citato DPCM proprio al fine di evitare utilizzi impropri della piattaforma, il censimento e la relativa profilazione degli Ufficiali di Anagrafe, sono di responsabilità del comune ed in particolare delle figure ALS e ALP (Amministratore locale della Sicurezza e Amministratore locale delle Postazioni), buona serata

**Comment by johnatandante** [comment]
La ringrazio.

Buona serata
