### ISSUE TITLE
Invio dati Motorizzazione Civile

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2676]
COMUNE DI CAPONAGO

Maria Giuseppina Varisco

Buongiorno 
vovelo sapere come vengono acquisiti / inviati i dati di cambio via alla Motorizzazione Civile, a seguito di un cambio via di un cittadino residente.

**Comment by azabatta** [comment]
Buonasera, 
in virtù di un accordo con Ministero dell'Interno, una serie di eventi anagrafici inviati dai comuni ad ANPR sono  notificati a MCTC. 
Si tratta degli eventi che comportano un cambio di residenza o di abitazione per i cittadini che hanno almeno un campo tra possesso veicoli e possesso patente valorizzato con "S".  Sono oggetto di notifica anche le rettifiche/integrazioni degli indirizzi e le mutazioni di scheda individuale che impattano sui dati possesso veicoli e possesso patente.
La notifica viene inoltrata a valle dell'acquisizione in ANPR di un evento anagrafico di interesse per MCTC.

**Comment by Jeffrey-cloud** [comment]
> Buonasera,
> in virtù di un accordo con Ministero dell'Interno, una serie di eventi anagrafici inviati dai comuni ad ANPR sono notificati a MCTC.
> Si tratta degli eventi che comportano un cambio di residenza o di abitazione per i cittadini che hanno almeno un campo tra possesso veicoli e possesso patente valorizzato con "S". Sono oggetto di notifica anche le rettifiche/integrazioni degli indirizzi e le mutazioni di scheda individuale che impattano sui dati possesso veicoli e possesso patente.
> La notifica viene inoltrata a valle dell'acquisizione in ANPR di un evento anagrafico di interesse per MCTC.

Salve sapete dopo quanto tempo dall’invio richiesta ANPR la MCTC applica il cambio di residenza e il cittadino può andare a vedere se i dati sono stati recepiti tutti correttamente?

**Comment by azabatta** [comment]
No, dai dati di  ANPR possiamo solo verificare se l'invio della notifica è stato effettuato con esito positivo. Le elaborazioni di MCTC esulano dal perimetro di ANPR.

**Comment by Jeffrey-cloud** [comment]
> No, dai dati di ANPR possiamo solo verificare se l'invio della notifica è stato effettuato con esito positivo. Le elaborazioni di MCTC esulano dal perimetro di ANPR.

La mia domanda nasceva da questo problema:

https://github.com/italia/anpr/issues/2680

Può aiutarmi? La ringrazio in anticipo.
F.

**Comment by Jeffrey-cloud** [comment]
> No, dai dati di ANPR possiamo solo verificare se l'invio della notifica è stato effettuato con esito positivo. Le elaborazioni di MCTC esulano dal perimetro di ANPR.

https://github.com/italia/anpr/issues/1603#issuecomment-533113455

Mi scusi ho notato inoltre questo suo commento (v. sopra). Mi conferma che esiste un solo campo da validare ("autoveicoli") sia per la patente che appunto per veicoli? Quindi il cittadino si ritroverà nella situazione individuale, secondo l'ANPR, la dicitura "soggetto CON patente" e "soggetto CON veicoli" anche se non dispone di questi ultimi poichè entrambe le cose sono sotto un'unica opzione da spuntare (veicoli appunto)?

**Comment by azabatta** [comment]
Buongiorno, 
la  issue #1603  fa riferimento agli autoveicoli  pertanto è stato menzionato solo il campo autoveicoli.
Le informarzaioni sono separate: patente - autoveicoli.  L'aggiornamento anche di una sola tra queste due  informazioni comporta l'invio di una notifica a MCTC. 
Per la issue #2680 leggo che ha già ricevuto risposta.
