### ISSUE TITLE
Soggetto non individuato in AT - Codice fiscale NON variato (Cod: EAM12 ).

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2679]
Buongiorno,

Per il soggetto id scheda anpr 86350206, non riusciamo a variare il nome, il cognome, data di nascita e CF, con mutazione tutti i dati

Errore
Esito AE: Cod: EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato

Da web app con la risoluzione CF confermando i dati in AE si ha il seguente errore:

Esito ANPR: Variazione non consentita per superamento numero campi variati (Codice: EAM93)

Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-26 11:28:51 , idOperazioneANPR 541654023 (Codice: EN527)

I dati corretti sono quelli in AE

In passato avevate svalidato voi il CF
Si chiede gentilmente se è possibile risolvere il problema?
Grazie
Cordiali saluti
Dante della Strada
Comune di Cesena

**Comment by frmariani** [comment]
Gentilmente dovrebbe indicare i dati corretti;
l'identificativo del cittadino idanpr 86350206 non corrisponde a quello presente nell'operazione idanpr 541654023

**Comment by DanteComuneCesena** [comment]
L'identificativo corretto del cittadino idanpr 86108587.

se faccio operazione di mutazione tutti i dati l'errore è:

EAM12 - Soggetto non individuato in AT - Codice fiscale NON variato 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-27 10:15:32 , idOperazioneANPR 542494053

Da web app con la risoluzione CF confermando i dati in AE si ha il seguente errore:

Esito ANPR: Variazione non consentita per superamento numero campi variati (Codice: EAM93)

Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-26 11:28:51 , idOperazioneANPR 541654023 (Codice: EN527)

Si ringrazia e ci si scusa per l'inconveniente.

**Comment by frmariani** [comment]
Il codice fiscale è stato svalidato, potete procedere con l'operazione di mutazione tutti i dati.
