### ISSUE TITLE
Esiti PRE-SUBENTRO

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#268]
Buongiorno,
in data 10/08/2017 è stato effettuato un test di carico in ambiente di PRE-SUBENTRO per circa 550.000 posizioni APR e circa 79.000 AIRE per il Comune di Milano.
L'elaborazione si è conclusa circa 2 ore dopo l'invio dei files e le risposte (dalla 5853 alla 5871) consultabili dalla scheda SUBENTRO E ANOMALIE --> ESITI DEL SUBENTRO e la pec ricevuta dal Comune confermano che l'elaborazione si è conclusa correttamente.

Andando però nella scheda MONITORAGGIO ANOMALIE riscontriamo i seguenti problemi:
1) cliccando la voce "Numero schede individuali con dati errati o incompleti" viene scaricato il report ma con data 04-08-2017 (la data della prova precedente)
2) non è possibile scaricare il report alla voce "Numero schede famiglia/convivenza con dati errati o incompleti" in quanto non ha alcun collegamento.

Grazie
Gruppo SiPO Comune di Milano

**Comment by mttfranci** [comment]
Abbiamo simulato l'accesso all'applicazione web [Home -> Subentro -> Monitoraggio Anomalie] come comune di Milano. Ci sembra sia riportata correttamente la data del 10 Agosto in ambiente di presubentro.
Abbiamo anche verificato che le anomalie scaricabili da tale pagina fanno riferimento al presubentro del 10 Agosto.
Se ci fornite un recapito telefonico possiamo fornirvi ulteriore assistenza.
Saluti

Matteo Franci

![immagine](https://user-images.githubusercontent.com/29305782/29514737-e344692c-8669-11e7-92d3-baa86656fff5.png)

**Comment by gcarbonin** [comment]
E' possibile avere un riscontro?

**Comment by ANPRCdMI** [comment]
Confermiamo quanto segnalato il 18/08 
I nostri riferimenti telefonici sono: 02.884.67008/67009

Grazie
 Gruppo SiPO Comune di Milano

**Comment by gcarbonin** [comment]
Domani mattina vi contattiamo

**Comment by mttfranci** [comment]
Come da contatto telefonico avvenuto il 23 agosto, il report è stato rigenerato correttamente.
