### ISSUE TITLE
Soggetto senza patente per ANPR ma con patente 

### ISSUE THREAD

**Issue by Jeffrey-cloud** [italia/anpr#2680]
Buongiorno chiedo un'informazione: un cittadino si reca in anagrafe per aggiornare i dati contenuti in ANPR, in particolare il titolo di studio recentemente conseguito. Non deve quindi effettuare alcun cambio di residenza o altro, solo aggiornare titolo di studio e professione. Dispone di patente da 8 anni ma nel sistema risulta "SENZA patente" e vorrebbe che fosse inserito il possesso di questa. Può chiedere che venga inserita la patente? Oppure è un dato che serve solo all'invio da parte della MTC dei tagliandi di aggiornamento residenza e che quindi deve rimanere così fino ad un ipotetico cambio di residenza? Noto che anche molti altri hanno la dicitura "senza patente" pur possedendola. All'epoca dell'iscrizione all'anagrafe era minorenne (anno 2000). Grazie mille
Saluti e buona giornata

**Comment by rvinzani** [comment]
E' possibile effettuare una mutazione tutti i dati (servizio 5008) per modificare il possesso di patenti/autoveicoli. Questa mutazione è indipendente dal cambio di residenza e può essere effettuata in qualsiasi momento

**Comment by Jeffrey-cloud** [comment]
> E' possibile effettuare una mutazione tutti i dati (servizio 5008) per modificare il possesso di patenti/autoveicoli. Questa mutazione è indipendente dal cambio di residenza e può essere effettuata in qualsiasi momento

La ringrazio, in questo caso partirebbe comunque la richiesta di aggiornamento alla motorizzazione civile?

**Comment by rvinzani** [comment]
Sì, corretto

**Comment by Jeffrey-cloud** [comment]
> Sì, corretto

Ho capito. E quali esiti potrebbe avere? L'invio di un tagliando recante il medesimo indirizzo?  La ringrazio

**Comment by rvinzani** [comment]
Non c'è nessuna impostazione di default e la scelta è del comune al momento del subentro o dell'iscrizione

**Comment by Jeffrey-cloud** [comment]
> Non c'è nessuna impostazione di default e la scelta è del comune al momento del subentro o dell'iscrizione

Ho capito la ringrazio. Lei mi consiglia di lasciare così o modificare? Non vorrei creare eventuali problemi. Gli altri comuni di norma cosa applicano?

**Comment by rvinzani** [comment]
Le consiglio di impostarlo in modo tale che ad ogni cambio di residenza per il soggetto verranno inviate notifiche a MCTC

**Comment by Jeffrey-cloud** [comment]
> Le consiglio di impostarlo in modo tale che ad ogni cambio di residenza per il soggetto verranno inviate notifiche a MCTC

Mi conferma che la procedura corretta per fare quanto mi ha detto nell’ultimo messaggio è questa: utilizzare il servizio “Mutazione tutti i dati” (ws 5008), nei dati di controllo indicare come sezione da modificare la sezione “Autoveicoli” (codice mutazione 08), confermare o aggiornare i dati patente/autoveicoli (almeno uno dei due deve essere impostato a “SI”, in questo caso “Patente”).

**Comment by rvinzani** [comment]
Sì, corretto

**Comment by Jeffrey-cloud** [comment]
> Sì, corretto

La ringrazio. C’è un modulo da compilare in comune o basta una comunicazione del cittadino (autocertificazione scritta di proprio pugno con fotocopia patente)?

**Comment by Jeffrey-cloud** [comment]
Le volevo inoltre chiedere, se il cittadino volesse poi verificare tali dati dalla motorizzazione dopo quanto tempo dovrebbe andare a partire dalla notifica inviata da ANPR? È una cosa istantanea o deve essere processata da un impiegato loro?

**Comment by rvinzani** [comment]
Non so come facciano i comuni per acquisire l'informazione. Posso dirle però che la notifica a MCTC è immediata

**Comment by Jeffrey-cloud** [comment]
> Non so come facciano i comuni per acquisire l'informazione. Posso dirle però che la notifica a MCTC è immediata

Grazie quindi la MCTC aggiorna i dati istantaneamente e in maniera automatica? 
ANPR comunica solo il dato “residenza” o anche altro del cittadino?

**Comment by Jeffrey-cloud** [comment]
> Non so come facciano i comuni per acquisire l'informazione. Posso dirle però che la notifica a MCTC è immediata

Grazie quindi la MCTC aggiorna i dati istantaneamente e in maniera automatica? 
ANPR comunica solo il dato “residenza” o anche altro del cittadino?

**Comment by rvinzani** [comment]
ANPR comunica solo i dati della residenza e sui tempi di elaborazione di MCTC purtroppo non so dirle

**Comment by Jeffrey-cloud** [comment]
> ANPR comunica solo i dati della residenza e sui tempi di elaborazione di MCTC purtroppo non so dirle

Una piccola nota tecnica: con mutazione tutti i dati cod. 5008 non vanno a modificarsi gli altri campi (es. la professione che risulta vuota per scelta esplicita)? Cambia solo il dato SI su Patente? Non mi chiede di aggiungere altro o modificare?

**Comment by rvinzani** [comment]
Nessuna altra modifica è richiesta

**Comment by Jeffrey-cloud** [comment]
> Nessuna altra modifica è richiesta

Grazie è stato davvero gentile. A titolo informativo personale (mi sembra di capire che lei sia una figura professionale dietro ANPR), i comuni nella stragrande maggioranza mettono “senza patente”? Se si, perché dato che sarebbe un’opzione molto comoda per il cittadino.

**Comment by rvinzani** [comment]
Non saprei, non mi risulta. Buona giornata
