### ISSUE TITLE
Cambio Provincia/Regione Comune di Sassofeltro

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2681]
-Maggioli Informatica-
- Cliente: COMUNE DI SASSOFELTRO (PU) - 

Buongiorno,
è stata approvato il cambio di provincia del Comune di Sassofeltrio dalla provincia di PU alla Provincia di Rimini, quindi cambia sia provincia che regione, la modifica sarà attuativa dal giorno dopo la pubblicazione alla Gazzetta ufficiale (**si pensa tra una settimana / 10 giorni)**.
Vorremmo capire quale sarà il vostro comportamento su ANPR per adeguare la nuova provincia:
**a)** Adeguerete in modo automatico gli indirizzi correnti, sostituendo il comune (PU) con (RN) ?
**b)** Vi aspettate una variazione di indirizzo per ogni singolo residente ?

E' importante per noi capire il metodo perchè nel caso
 **a)** non modifichiamo nulla nel software fino al vostro completamento.
Nel caso 
**b)** dobbiamo predisporre un invio massimo di variazioni su tutti i residenti e capire quale tipo di mutazione famiglia bisognerebbe inviare?

Grazie

**Comment by lorbia** [comment]
Salve il cambio di provincia verrà gestito in automatico dal sistema per cui sarà necessario alcun intervento da parte del Comune.
Saluti.
