### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by diegorl** [italia/anpr#2683]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

![ANPR-Erro](https://user-images.githubusercontent.com/26600316/120000230-fde53500-bfa8-11eb-84c9-3dd67daeac57.png)
> **Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:**
> - Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
> - se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

In contatto con il Comune di Mira (VE), non hanno riscontrato problemi con la scheda anagrafica. Anche la softhouse non ha riscontrato alcun problema.

Cosa devo fare? Il comune ha detto che non sa come aiutarmi.

**Comment by mttfranci** [comment]
Buongiorno.
Potreste fornirci qualche informazione per individuare l'utenza?
Ad esempio le prime 6 lettere del codice fiscale potreebbero essere sufficienti.
Grazie in anticipo.

**Comment by diegorl** [comment]
Buongiorno,

*Diego Ribon de Lima*
Nato in *Brasile*
Codice fiscale: *RBNDGI__________*

Grazie per l'aiuto.

**Comment by mttfranci** [comment]
@diegorl pensiamo di aver individuato l'anomalia e dovrebbe essere possibile provare di nuovo l'accesso.

Saluti

Assistenza ANPR

**Comment by diegorl** [comment]
@mttfranci ora funziona normalmente.
Posso accedere al servizio.

Grazie mille per l'aiuto e l'attenzione!

Cordiali saluti.

**Comment by mttfranci** [comment]
Di niente.
Buon proseguimento.

**Comment by faderfa64** [comment]
Buonasera, mi chiamo Fabrizio Della Rovere, sono residente in Spagna, iscritto all'AIRE del Comune di Remanzacco, C.F. DLL FRZ ho lo stesso problema di Diego, mi potete aiutare?
Grazie

**Comment by diegorl** [comment]
> Buonasera, mi chiamo Fabrizio, sono residente in Spagna, iscritto all'AIRE del Comune di Remanzacco, C.F. DLL FRZ ho lo stesso problema di Diego, mi potete aiutare? Grazie

Buonasera, meglio aprire un nuovo issue, questo mio caso è già stato chiuso.

**Comment by faderfa64** [comment]
Grazie

**Comment by diegorl** [comment]
> Buonasera, meglio aprire un nuovo issue, questo mio caso è già stato chiuso.

Buongiorno, meglio aprire un nuovo issue, questo mio caso è già stato chiuso.

**Comment by diegorl** [comment]
> Buongiorno, Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.
> 
> https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth
> 
> ANPR-Erro
> 
> Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:
> 
> Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune); se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni. In contatto con il Comune di Mira (VE), non hanno riscontrato problemi con la scheda anagrafica. Anche la softhouse non ha riscontrato alcun problema.
> 
> Cosa devo fare? Il comune ha detto che non sa come aiutarmi.
> 
> Codice fiscale: LJZMMM

Buongiorno, meglio aprire un nuovo issue, questo mio caso è già stato chiuso.

**Comment by Rosanna992** [comment]
Buonasera Sono Rosanna,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

![145eb9ee-ad9e-409e-8031-34a7c52978fd](https://user-images.githubusercontent.com/116681163/197871713-8677fa00-364f-4544-9f8f-606d5278737d.jpg)
ANPR-Erro

Purtroppo non è stato possibile accedere al servizio


Codice Fiscale GMBRNN

**Comment by diegorl** [comment]
> Buonasera Sono Rosanna, Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.
> 
> https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth
> 
> ![145eb9ee-ad9e-409e-8031-34a7c52978fd](https://user-images.githubusercontent.com/116681163/197871713-8677fa00-364f-4544-9f8f-606d5278737d.jpg) ANPR-Erro
> 
> Purtroppo non è stato possibile accedere al servizio
> 
> Codice Fiscale GMBRNN


Buonasera,
Questo mio caso è già stato chiuso, meglio aprire un nuovo issue.

**Comment by J-thunder** [comment]
Io ho lo stesso problema: 
Codice Fiscale CPLDLL

**Comment by marcosaof** [comment]
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

Screenshot_1

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Buongiorno,

Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.
In contatto con il Comune, non hanno riscontrato problemi con la scheda anagrafica. Anche la softhouse non ha riscontrato alcun problema.

Cosa devo fare? Il comune ha detto che non sa come aiutarmi.

Codice fiscale
RLNMCS

**Comment by Celeste201** [comment]
Buonasera sono Celeste,
Ho finito di iscrivermi allo SPID e non posso entrare, mi viene questo errore:

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

![SPID](https://github.com/italia/anpr/assets/159938716/e925e50b-26c8-42c1-b28f-faede8fe0500)

Codice fiscale: SLMCS 

Grazie!!

**Comment by rohail2222** [comment]
C.F NJMRHL ho stesso problemi

**Comment by rohail2222** [comment]
> Buongiorno. Potreste fornirci qualche informazione per individuare l'utenza? Ad esempio le prime 6 lettere del codice fiscale potreebbero essere sufficienti. Grazie in anticipo.

C.F NJMRHL ho stesso problemi grazie
