### ISSUE TITLE
[ servizio6001 ] Internal error from client

### ISSUE THREAD

**Issue by matteo-mulas** [italia/anpr#2684]
Buongiorno. 

Stiamo provando a richiamare il servizio 6001 ma otteniamo sempre il seguente errore "Internale Error (From Client)". 

In allegato la richiesta  [request.txt](https://github.com/italia/anpr/files/6561548/request.txt) 

Restiamo in attesa di un cortese riscontro. 

Saluti.

**Comment by Leonforte** [comment]
Buongiorno, qual'è la url dove inviate la rquest ?

**Comment by matteo-mulas** [comment]
Buongiorno. 
La url è https://wsfree.anpr.interno.it/ANPR6001ServizioCertificazione/AnprService6001

**Comment by amollicone1982** [comment]
La richiesta risulta non valida in quanto la listaTipiCertificati deve essere costruita in questo modo:
 <listaTipiCertificati>
         		<tipoCertificato>1</tipoCertificato>
         </listaTipiCertificati>

Inoltre i campi cognome e nome devono essere invertiti di ordine
         <soggettoIntestatario>
            <generalita>
               <cognome>PITZALIS</cognome>
               <nome>ROBERTA</nome>
            </generalita>
         </soggettoIntestatario>
