### ISSUE TITLE
WS5001 - Immigrazione da altro comune subentrato 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2685]
Buongiorno
COMUNE DI CASERTA 061022 - PROD
Abbiano inviato una transazione ws5001 che produce il seguente errore:
EF002 Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata
EN527 Informazioni sull'operazione da fornire in caso di assistenza : data 2021-05-29 12:03:46 , idOperazioneANPR 544341169
Quale è la causa ?.
Grazie

**Comment by frmariani** [comment]
Si tratta di una famiglia AIRE, quindi nel WS 5001,  il tipo scheda deve essere referenziato come tale: tipoScheda=5

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
