### ISSUE TITLE
ANPR momentaneamente non disponibile

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2686]
Buongirono,
si segnala che dalle 8.10 ANPR restituisce errore "Il sistema è momentaneamente non disponibile"

UPI Torino

**Comment by sfmodena** [comment]
Comune di Modena - Ambiente di produzione

Buongiorno,
anche a Modena stesso errore.

Grazie, saluti
Sonia Fiorini

**Comment by Nyarlix** [comment]
Anche a Belluno.

Lorenzo Savoini

**Comment by FilippoPapi** [comment]
buongiorno, il problema è rientrato
saluti
