### ISSUE TITLE
Annullamento Matrimonio

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2687]
Annullamento matrimonio
Errore:  I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto

E' apparso questo errore in due comuni:
- Comune Poggio a Caiano, ambiente produzione - idOperazioneANPR 545232500 data 2021-05-31 12:10:57
- Comune Forlimpopoli, ambiente produzione -    idOperazioneANPR 538042004 data 2021-05-21 12:16:25
Qual'è l'incongruenza che da fastidio?

Grazie

**Comment by frmariani** [comment]
Come specificato nell'errore, i dati del coniuge presenti nel sistema ANPR  non corrispondono a quelli inviati tramite il servizio  di completamento (WS 5008 tipo mutazione 20); 
in fase di re-iscrizione, il cittadino ha "ereditato" i dati del matrimonio inseriti dal comune precedente; in effetti questi particolari dati potrebbero essere superati o non corretti, quindi modificheremo il comportamento del sistema in modo che, in fase di re-iscrizione del soggetto, debbano essere inseriti ex novo e non "ereditati". 
Con l'operazione di consultazione verifichi la correttezza dei dati del coniuge presenti in ANPR; nel caso fosse necessario modificarli, proceda con la mutazione dei dati del matrimonio (WS 5008 tipo mutazione 12).

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
