### ISSUE TITLE
Errore EN179 su richiesta elenchi

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2688]
Buonasera,
inserendo una richiesta per servizio 4001 rientra subito l'errore EN179 sebbene non ci siano operazioni in sospeso.
Comune di Cansano
Halley Informatica
Arditi Alessandro

Risposta

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta4001 xmlns:a="http://sogei.it/ANPR/4000estrazione">
            <a:rispostaKO>
                <testataRisposta>
                    <idOperazioneComune>20210531171117943</idOperazioneComune>
                    <codMittente>067009</codMittente>
                    <codDestinatario>ANPR02</codDestinatario>
                    <operazioneRichiesta>4001</operazioneRichiesta>
                    <dataOraRichiesta>2021-05-31T17:11:17</dataOraRichiesta>
                    <idOperazioneANPR>545557499</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>EN179</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Richiesta non effettuabile: e' presente una richiesta dello stesso tipo non ancora lavorata &#13;
</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:rispostaKO>
        </a:Risposta4001>
    </soapenv:Body>
</soapenv:Envelope>

**Comment by amollicone1982** [comment]
Potete riprovare
