### ISSUE TITLE
Data di nascita non completa #2663 - Integrazione

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2689]
Buongiorno,
mi collego al ticket #2663.
Abbiamo il caso di un cittadino marocchino con data di nascita senza giorno e senza mese (xx/xx/1977).
Il cieonline non permette l'emissione della carta elettronica (allego errore). L'idANPR del cittadino è 19753414.

Grazie,
cordiali saluti.

**Comment by rvinzani** [comment]
Le confermo che CIEonLine non conserte l'emissione della CIE in caso di data di nascita incompleta. Questo dipende dai controlli del sistema CIE e non da ANPR
