### ISSUE TITLE
[ Servzio 6001 ] Hash values do not match. (From client)

### ISSUE THREAD

**Issue by matteo-mulas** [italia/anpr#2690]
Buongiorno.

Stiamo provando a richiamare il servizio 6001 ma otteniamo sempre il seguente errore “Hash values do not match. (From client)”.
La url è https://wsfree.anpr.interno.it/ANPR6001ServizioCertificazione/AnprService6001

Abbiamo inviato la richiesta con i dati sensibili in chiaro all'email segnalazioni-anpr@teamdigitale.governo.it

La richiesta di assistenza si riferisce al ticket #2684.

Restiamo in attesa di un cortese riscontro.

Saluti.

**Comment by amollicone1982** [comment]
Vi sta dicendo che l'hash value presente all'interno della asserzione saml non corrisponde alla richiesta. Sembra come se la richiesta sia stata modificata a mano senza ricalcolare hash value

 <ds:DigestValue>h/0dGrBCodHyocvGywzG1qrpo1I=</ds:DigestValue>
