### ISSUE TITLE
RISOLUZIONE AGENZIA ENTRATE restituisce per tutte le richieste Codice 97

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2691]
Buongiorno,
da stamane all'aperture tutte le operazioni di RISOLUZIONE AGENZIA ENTRATE hanno restituito errore "Esito AE: Operazione non effettuabile (Codice 97)"
Esempi:
idANPR: 137150170
idANPR: 28336733
Grazie

UPI / CODICI FISCALI Torino

**Comment by frmariani** [comment]
Problema temporaneo risolto nella giornata dell'apertura.
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
