### ISSUE TITLE
Collegamento codici fiscali non effettuabile

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2692]
Buongiorno,
a seguito di variazione dei dati anagrafici di un cittadino, è necessario collegare i codici fiscali facendo prevalere AE.

Dalla webapp non ci è possibile procedere. 

Flaggando "collega codici fiscali" restituisce "Esito AE: Operazione non effettuabile (Codice 97)". 

Senza flaggare e cliccando sul pulsante Conferma AE allego l'errore che ci restituisce.

Grazie
Katia Vacchi

![collega cf](https://user-images.githubusercontent.com/57749903/120608639-b6035980-c451-11eb-97eb-be65ffd77e1f.JPG)

**Comment by frmariani** [comment]
per favore ripeta l'operazione di collegamento dei codici fiscali

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
