### ISSUE TITLE
ws1001 -errore AEE97

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2693]
BUONGIORNO,
COMUNE CASERTA 061022 - PROD
Oggi per le operazioni di iscrizioni per nascita WS1001 restituisce

AEE97 Operazione non effettuabile 
quesa è una di queste:
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-06-03 10:50:11 , idOperazioneANPR 547247977
Grazie

**Comment by frmariani** [comment]
Problema temporaneo risolto nella giornata dell'apertura della issue.
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
