### ISSUE TITLE
Certificazione  dei  dati  anagrafici  in  modalita'  telematica e imposta di bollo

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2694]
Buongiorno
Sulla stampa si trovano notizie sull'abolizione del bollo nei certificati, in seguito al decreto legge semplificazioni, del Consiglio dei Ministri del 31 maggio, già pubblicato in G.U. e già in vigore.

Immagino sia ancora presto, ma volevo chiedere se sono previste modifiche, e di quali tipo a fronte di questa modifica normativa, al web service di certificazione, oppure all'elenco dei motivi di esenzione da bollo.

**Comment by fcastellani81** [comment]
Buongiorno,
anche io mi accodo alla richiesta.
Resto in attesa di riscontro

Cordiali Saluti

**Comment by FilippoPapi** [comment]
salve, al momento non sono previste modifiche.
se verranno predisposte modifiche ai servizi saranno comunicate tempestivamente
saluti
