### ISSUE TITLE
[5001] TEST - Errore durante un rimpatrio (Internal Error (from client))

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#2695]
Buongiorno, facendo un rimpatrio di cittadini AIRE (servizio 5001) si verifica il seguente errore: 

ERRORE ANPR: Il server ANPR ha restituito un errore (Internal Error (from client))
The remote server returned an error: (500) Internal Server Error.

AMBIENTE DI TEST - COMUNE DI PISA
ID OPERAZIONE COMUNE 126721
[126721_5001_request.zip](https://github.com/italia/anpr/files/6591489/126721_5001_request.zip)

Potete aiutarci a capire il problema?
Grazie
Monia Pedrazzoli
APKAPPA

**Comment by MoniaPedrazzoli** [comment]
Scusate, mi sono accorta solo ora che c'è un carattere non valido nel campo interno1 ed eliminando quello il servizio viene accettato correttamente.

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, abbiamo riprovato il servizio con altri soggetti ed otteniamo di nuovo l'errore descritto, stavolta non riusciamo a capire il motivo della segnalazione in quanto apparentemente nell'XML non sono presenti errori formali o caratteri non accettati.
[126853_5001_request.zip](https://github.com/italia/anpr/files/6597796/126853_5001_request.zip)
Potete aiutarci?
Grazie

**Comment by amollicone1982** [comment]
La prova è stata fatta lle 8:49?

**Comment by MoniaPedrazzoli** [comment]
Sì la prova è delle 8:49, in effetti non abbiamo ricevuto la response, sembra proprio che la request non abbia superato i controlli...il 5001 delle 9:07 è stato effettuato con la webapp per prova e poi annullato.

**Comment by amollicone1982** [comment]
Quello che vi posso dire che la prova del 5001 delle 08:49 non la vediamo (solo dei 3000 a quell'ora).
Siete sicuri che anche qui  l'errore è: Internal Error (from client)

**Comment by MoniaPedrazzoli** [comment]
[127004_5001_request.zip](https://github.com/italia/anpr/files/6598814/127004_5001_request.zip)
Rifatta proprio ora, stesso risultato...

2021-06-04 15:30:32,972 ERROR [APS.BaseClasses.APSUserControl][78][monia.pedrazzoli]: Anagrafe.ANPR.Model.Exceptions.ANPRException: Il server ANPR ha restituito un errore (Internal Error) ---> Anagrafe.ANPR.Request.ANPRException: Il server ANPR ha restituito un errore (Internal Error) ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at Anagrafe.ANPR.Request.ANPRRequest.GetResponse()

**Comment by amollicone1982** [comment]
L'errore che ci restituite è wrappato dal vostro gestionale, 
l'url che puntate inizia con wstest.anpr.interno.it?

**Comment by MoniaPedrazzoli** [comment]
Faccio verificare meglio questi aspetti, anche se l'ambiente da cui operiamo è quello che utilizziamo quotidianamente per i test e gli altri servizi funzionano regolarmente, quindi penso che la configurazione sia corretta.

**Comment by amollicone1982** [comment]
Se mi date conferma dell'ip di provenienza faccio mettere una trace a livello rete per verificare. Ho visto che nei precedenti giorni avete fatto vari 5001. E' probabile che sia un problema legato all'ip di provenienza o al certificato di postazione

**Comment by amollicone1982** [comment]
se potete diteci con quale certificato ci invocate

**Comment by amollicone1982** [comment]
Ho visto che siete riusciti ad effettuare 5001 con tipoMutazione 5.
Chiedo la segnalazione. Per altre problematiche la potete riaprire specificando quanto richiesto sopra
