### ISSUE TITLE
Incorrect reference digest value (from client)

### ISSUE THREAD

**Issue by matteo-mulas** [italia/anpr#2697]
Buongiorno.

Stiamo provando a richiamare il servizio 6001 ma otteniamo sempre il seguente errore “Incorrect reference digest value (from client)”.
La url è https://wsfree.anpr.interno.it/ANPR6001ServizioCertificazione/AnprService6001

In allegato la richiesta  [request.txt](https://github.com/italia/anpr/files/6609764/request.txt)

Restiamo in attesa di un cortese riscontro.

Saluti.

**Comment by amollicone1982** [comment]
potreste fornirci l'ip dal quale effettuate la chiamata?
P.S.
avete ricontrollato il calcolo dei digest value?

**Comment by matteo-mulas** [comment]
L'ip è 93.64.184.138
Allego file request senza spazi.  [request.txt](https://github.com/italia/anpr/files/6610497/request.txt)

L'errore che ci arriva non cambia. "Incorrect reference digest value (from client)”.

Confermiamo il controllo sul calcolo dei digest.

**Comment by amollicone1982** [comment]
L'errore è chiaro: l’hash della firma non viene validato e quindi la richiesta non è stata firmata correttamente o è stata modificata dopo l’apposizione della stessa.

**Comment by amollicone1982** [comment]
[tool-testconn.zip](https://github.com/italia/anpr/files/6613565/tool-testconn.zip)
[ANPR_Client_guida.pdf](https://github.com/italia/anpr/files/6613567/ANPR_Client_guida.pdf)

In allegato un tool di connessione che genera l'asserzione saml e una guida per usarlo
