### ISSUE TITLE
PROCEDIMENTO APERTO  comune di MILANO

### ISSUE THREAD

**Issue by LORETO2021** [italia/anpr#2698]
COMUNE DI LORETO PRODUZIONE

Buongiorno,

Abbiamo sollecitato con delle Pec il comune di Milano per la chiusura del procedimento che risulta ancora aperto 

NON riusciamo ad iscrivere il soggetto  ID ANPR: 32415004  
che risulta cancellata per ripristino posizione anagrafica, ma risulta ancora il procedimento aperto presso 
il comune di Milano
![image](https://user-images.githubusercontent.com/85558578/121180200-df145780-c860-11eb-836e-b5d2b705467c.png)

**Comment by rvinzani** [comment]
Abbiamo inviato email a Milano per sollecitare la chiusura
