### ISSUE TITLE
VARIAZIONE DI MATRIMONIO p2 sC - anomalia

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2699]
COMUNE DI CAPONAGO

Varisco Maria Giuseppina

Buongiorno
effettuando una varizione di matrimonio 5008, il vostro site,ma restituisce il seguente errore
EN366 E' obbligatorio specificare il sesso del coniuge

Non capisco qual'è il problema il tag del coniuge non viene indicato in quanto non residente.

di seguito i riferimenti dell'operazione :

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-06-09 09:10:05 , idOperazioneANPR 552242573

**Comment by frmariani** [comment]
il tag del coniuge è giustamente presente con il nome e cognome ma senza l'informazione obbligatoria del sesso; anche se il cittadino coniuge non è residente, i dati devono essere acquisiti

**Comment by GabriellaBallabio** [comment]
il tag coniuge uge NON è PRESENTE perchèmi chiede il sesso?

[EsitoWS_Richiesta5008.txt](https://github.com/italia/anpr/files/6624448/EsitoWS_Richiesta5008.txt)
[Richiesta5008.txt](https://github.com/italia/anpr/files/6624449/Richiesta5008.txt)

**Comment by frmariani** [comment]
gli allegati si riferiscono ad altra operazione effettuata correttamente; si tratta di un WS 5008 tipo mutazione 1 dove non è richiesta la presenza del coniuge

**Comment by GabriellaBallabio** [comment]
Non mi sono spiegata bene ....
ho inviato una variazione di stato civile per un soggetto con il file Richiesta5008.xml
all'interno del quale NON HO INDICATO I DATI DEL CONIUGE (può verificarlo le ho mandato il file richiesta)

E' vero che la richiesta è andata a buon fine .... se interrogo ANPR ... però l'esito che mi restituisce il ws riporta ::
EN366 E' obbligatorio specificare il sesso del coniuge

ma il coniuge non l'ho indicato nemmeno con il nominativo, se guarda la richiesta relativa all'operazione

idOperazioneANPR 552242573

forse i file allegato non sono quelli corretti .. ma se fa riferimento all' idOperazioneANPR 552242573 ... riuscirò a spiegare quanto accaduto.

**Comment by frmariani** [comment]
La richiesta relativa all'idOperazioneANPR **552242573** (idoperazionecomune 20210609090933) è un **WS 5008 tipo mutazione 12 (matrimonio)** dove è obbligatorio specificare i dati minimi del coniuge:  nome, cognome e **sesso**;
Non avendo indicato i dati del sesso, l'operazione è fallita facendo scattare il controllo EN366 - E' obbligatorio specificare il sesso del coniuge. 
La richiesta che mi ha allegato, si riferisce all'idoperazioneANPR 552243298 (idoperazionecomune20210609090942), un WS tipo mutazione 1 dove è stato modificato lo stato civile del cittadino; operazione correttamente effettuata.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
