### ISSUE TITLE
Codice errore EN306

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#27]
Salve , mi riferisco a una richiesta gia' fatto riguardo gli errori di popolamento del comune di Bologna In ANPR TEST :   Nella fase di subentro , provata in ambiente di test, ci troviamo molte segnalazione sui matrimoni: EN306 Presenza del coniuge e assenza del matrimonio. 
C'era stato risposto che errore non era bloccante, quando ancora la tabella deglie errori non prevedeva questo codice.
Ora tabella degli errori ANPR , aggiornata al 01/03/0217 c'e' scritto effettivamente:
 EN306 La data del matrimonio e' obbligatoria W (per Il Subentro), ma compare la nota: Da rimuovere prima del subentro.
Significa che non sara' possibile passare i dati solo del coniuge, senza la data del matrimonio?

**Comment by gcarbonin** [comment]
Gli errori W non bloccano l'acquisizione dei dati in fase di subentro. Tuttavia è stata aggiunta la nota "da rimuovere prima del subentro" in tutti i casi in cui l'anomalia potrebbe determinare un errato funzionamento dei servizi se, a valle del subentro, occorre eseguire un'operazione di registrazione sul soggetto o l'impossibilità di emettere un certificato.
