### ISSUE TITLE
nuove smart card

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#2700]
Vedo che ci sono molte issue sui problemi di  attivazione delle nuove  smart card e la possibilità di "coabitazione" con le sco CIE .
Quindi non presenterò un caso, solo una domanda.
Sono arrivate le nuove smart card e l'assistenza ANPR mi ha confermato che non è più rilasciata la seconda parte della psw.
Risultato non possimo operare dalle postazioni CIE (che sono blindate) nella Webapp perchè le due CARD confliggono.
ANPR sta implementando la WEBAPP con le richieste di servizi  trasmesse dai cittadini come ad esempio la rettifica dei dati, prossimamente la dichiarazione di mutazione anagrafica ecc..
Contestualmete si sono potenziati e ampliati i servizi fruibili dal cittadino con SPID e CIE e come conseguenza  sono aumentate le richieste di emissione delle CIE che ci impongono di aprire altri sportelli per soddisfare le domande ma utilizzando personale che è impegnato in attività di back che non riesce ad operare sulla webapp perchè la smart confligge con la sco.
I nostri informatici sono costantemente da noi stolkerati per risolvere il problema ma non hanno ancora una soluzione...
La domanda è:
visto che siete sempre voi (SOGEI) che predisponete le "architetture? infrastutture?" (non conosco i termini tecnici) non potete per cortesia riflettere su questo problema? Magari facendo solo una SMART o SCO lasciando al comune la responsabilità di scegliere se fare una o due abilitazioni? O altra soluzione informatica che ci consenta di lavorare con il personale che abbiamo e SOPRATTUTTO dare un servizio al cittadino?
Grazie per l'attenzione
Raffaella
ve 3669308207

**Comment by Leonforte** [comment]
Come da conversazione telefonica.
A soluzione avvenuta riapriremo il git per le informazioni del caso, a lunedì, buon we

**Comment by Leonforte** [comment]
Buongiorno Raffaella, ecco una breve relazione sul supporto fornito.

Assistenza eseguita dal tecnico del CED su una postazione CIE.
Note: Il pc delle CIE presentava al suo interno un antivirus Mcafee ( che non ha dato alcun problema) e i driver per le vecchia sc Athena (IDP).
Soluzione 1
Metodo utilizzato: Installazione Del Safedive , apertura di ANPR con Explorer/Chrome e del portale CIE con Firefox.

Risultato ottenuto: Con questo metodo ( quello più semplice) il Comune può lasciare aperti entrambi i browser ed avere il controllo su entrambi i portali ( in primis accede ad ANPR con la sco aprendo chrome, e poi con la sc della CIE aprendo Firefox). Il lettore Embedded legge infatti anche tutti i tipi di sc di ANPR.
Procedura: 

1.Installazione di Safedive 3.4.1 da portale Sogei. 
NB: in caso di problemi di installazione chiudere tutti i programmi aperti o eseguire il login di windows come altro utente con privilegi di amministratore.
2.Riavviare la macchina al termine dell’installazione (Chrome ed Explorer infatti non utilizzeranno la libreria corretta del Safedive finchè il computer non verrà riavviato).
3.Dopo il riavvio Explorer/chorme/Edge saranno in grado di utilizzare la libreria corretta per l’accesso ad ANPR in base alla sc inserita (IDP per Athena e Safedive per Infocert).
NB: La selezione di tale libreria per questi browser infatti avverrà in automatico ( l’utente dovrà solo preoccuparsi di inserire il pin).

4. Link ufficiale di accesso alla web app.

Soluzione 2

Metodo. Configurazione di più profili utente mediante Firefox.

Risultato: Questo metodo ci consente l’accesso al portale anche nel caso in cui 2 o più librerie per token crittografati all’interno di Windows vadano in conflitto o non vengano correttamente rilevate all’inserimento, negando di conseguenza l’accesso al portale anche dopo aver digitato il pin corretto. 

Procedura: 
1.Installare Safedive dal portale di Sogei

2. Digitare: FIREFOX.EXE -P dalla shell di comando di Windows ( va bene anche scriverlo su una qualsiasi barra degli indirizzi delle finestre aperte, oppure dalla casella di testo di ricerca di Windows 10).
3.creare Un nuovo profilo ( ad esempio ANPR Infocert)
4.Togliere la spunta dalla voce “ Utilizza il profilo selezionato senza chiedere all’avvio”

5.Selezionare il nuovo profilo creato e cliccare su Avvia Firefox.
NB:Il nuovo profilo appena creato sarà univoco per preferiti, moduli caricati, file temporanei e certificati.
6.Procedere con l’importazione del certificato di postazione .

7.Procedere col caricamento del modulo stpkcs11.dll su c:\windows\system32

8. Accesso al portale tramite link ufficiale

NB: Il metodo dei profili è funzionante sia su Firefox “normale” che su versione ESR.
Va precisato che a differenza del primo metodo in questo caso per correttezza andrebbe chiuso e riaperto Firefox ogni volta che si cambia il profilo di lavoro ( CIE o ANPR).
Infatti anche se firefox consente di avviare più istanze con profili diversi, il funzionamento corretto dei moduli all’interno non è stato testato e pertanto garantito.
