### ISSUE TITLE
Esito AE: Operazione non effettuabile codice 95

### ISSUE THREAD

**Issue by averrando** [italia/anpr#2701]
Comune di Ospedaletti in produzione ANPR

Soggetto con C.F. in Agenzia delle Entrate ( PTRVLY66C09Z154J ) differente da ANPR ( PTRVLY66C09Z135L ). 
Da WebApp tentando di confermare il C.F. ANPR ( PTRVLY66C09Z135L ) si ottiene l'errore Esito AE: Operazione non effettuabile (codice 95).
Ci potete aiutare?
Grazie mille in anticipo

**Comment by rvinzani** [comment]
Risponderemo alla sua richiesta di assistenza facendo riferimento al ticket n. 22908544. La preghiamo, per richieste specifiche di assistenza di rivolgervi al nostro numero 800863116. Chiudo pertanto la issue
