### ISSUE TITLE
annullamento mutazione tutti i dati

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2702]
Buongiorno,
Non riusciamo ad annullare una mutazione di divorzio per il soggetto id anpr 18606194, l'errore è il seguente

L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa; Informazioni sull'operazione da fornire in caso di assistenza : data 2021-06-15 10:16:14 , idOperazioneANPR 557325561;

Il soggetto ha solo questa operazione dopo il subentro, inoltre abbiamo provato anche ad annullare il decesso dell'individuo id anpr 18606190, che nel 2018 risultava nella stessa famiglia, ma l'errore si ripresenta lo stesso.

Certo di un vostro riscontro.
Cordiali saluti 
Della Strada Dante - Comune di Cesena - tel. 0547/356536

**Comment by ncapozzi** [comment]
Buongiorno
l'operazione idOperazioneANPR 557325561 cerca di annullare 553611581 ma dopo 553611581 è stata eseguita 556379571 che è ancora da annullare come potete verificare in consultazione della scheda del cittadino, elenco operazioni

**Comment by DanteComuneCesena** [comment]
Salve, la prima cosa che abbiamo verificato è stata proprio la lista delle operazioni dell'individuo e di tale operazione(556379571 ) non vi è traccia, possibile che faccia riferimento al coniuge id anpr 70728119? nel caso fosse cosi non abbiamo ne visibilità e ne possiamo annullare tale operazione, non essendo un nostro residente ....

Inoltre colgo l'occasione per chiedere se fosse possibile aggiungere nel messaggio di validazione "L'operazione da annullare non è l'ultima per..." anche l'id operazione che blocca, in modo tale da renderci la strada più facile per un eventuale ricostruzione degli eventi in autonomia, magari aggiungendo anche un modo per ricercare tale operazione secca per id.

Di seguito la lista delle operazione del nostro cittadino

524723	SUBENTRO				NA	 	 
553611581	MUTAZIONE SCHEDA	10-06-2021	10-06-2021	10-06-2021	Completata con esito positivo
556687990	MUTAZIONE SCHEDA	14-06-2021	14-06-2021	14-06-2021	Completata con esito positivo
557256921	ANNULLA MUTAZIONE	15-06-2021	14-06-2021		Completata con esito positivo

Saluti
Dante Della Strada

**Comment by ncapozzi** [comment]
Come comunicato per le vie brevi, si conferma che l'operazione 556379571  è stata eseguita dal comune di residenza dell'altro coniuge. Dovete contattare l'altro comune e chiedere l'annullamento dell'operazione.

N. Capozzi
