### ISSUE TITLE
Annullamento iscrizione

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2703]
Buongiorno
COMUNE CASERTA  -061022 PROD
dobbiamo annullare una iscrizione per nascita AIRE id 543535486 - avendo sbagliato il luogo di nascita e ovviamente è stato calcolato un codice fiscale errato. Successivamente vorremmo rinviare la nascita con i dati corretti. 
Non consente l'operazione ERRORE AEE95 
id operazione ANPR 557680194 2021-06-15 13:15:25

**Comment by ncapozzi** [comment]
Buongiorno, 
prima di annullare l'iscrizione AIRE è necessario annullare la mutazione famiglia/convivenza id 557683584 eseguita successivamente. In caso abbiate bisogno di assistenza diretta per eseguire le operazioni per favore indicate un recapito telefonico.

N. Capozzi

**Comment by rinonasti** [comment]
Fatto ma sempre stesso errore 
idOperazioneANPR 558520154
Tel 3355885312
