### ISSUE TITLE
Invio flusso in ANPR non consentito per procedimento aperto

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2704]
Buongiorno,
nel riversare una iscrizione anagrafica per ricomparsa in ANPR ci compare un'anomalia: "operazione non consentita: per il soggetto esiste un procedimento aperto dal Comune di Napoli".

A noi non risulta alcuna operazione in sospeso e al Comune di Napoli neanche.

IdOperazione Anpr: 546331310

Grazie e buon lavoro.

**Comment by rvinzani** [comment]
Abbiamo inviato una email al comune di Napoli
