### ISSUE TITLE
Impossibile nominare nuovi ALS dopo il subentro

### ISSUE THREAD

**Issue by slastrucci** [italia/anpr#2705]
Buongiorno,

avrei la necessità di nominare un ulteriore "Amministratore Locale della Sicurezza" (ALS) ma dopo il subentro non trovo più questa possibilità.
La funzione di "modifica/visualizza" utenti presente nella webapp dopo il subentro mostra solo i diritti specifici per le funzionalità di operatore.

Come posso fare?

**Comment by Leonforte** [comment]
Buongiorno, l'assegnazione del profilo di ALS può essere effettuato esclusivamente dal Sindaco  e dall' Ammnistratore di Primo Livello (profili rispettivamente ASC e APL). Buon lavoro, saluti
