### ISSUE TITLE
Accesso non possibile con nuove smart card Infocert

### ISSUE THREAD

**Issue by ravelment** [italia/anpr#2706]
Buongiorno!
Riscontriamo dei problemi di accesso alla web app di ANPR con le nuove smart card Infocert rilasciate a partire dall'anno scorso.
Dopo aver installato l'applicazione Safedive così come illustrato dalla guida, vediamo che la postazione riconosce e sembra leggere correttamente le smart card. Provando a collegarsi all'indirizzo https://dp.anpr.interno.it/com vengono mostrati in sequenza:
* un pop-up con dati del certificato di postazione;
* un pop-up con dati della smart card (c.f. dell'operatore);
* un pop-up di richiesta del pin della smart card
Inserendo il pin corretto si viene però reindirizzati alla pagina https://dp2.anpr.interno.it/com e il browser Chrome mostra un messaggio di errore "Impossibile raggiungere il sito ... ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED".
Sembra che gli operatori in possesso delle smart card emesse prima di maggio 2020 non abbiano questo problema e non vengano reindirizzati alla pagina https://dp2.anpr.interno.it/com , rimanendo invece su https://dp.anpr.interno.it/com .
Stiamo usando pc con sistema operativo Windows 7, browser Chrome versione 88.0.4324.150 , ambiente di subentro.
Da cosa potrebbe dipendere questo problema? Qualcuno ci sa aiutare?

Federico Linio - Comune di Verona

**Comment by Leonforte** [comment]
Buongiorno, il reindirizzamento verso dp2 è corretto in entrambi i casi. Le suggerisco di fare un primo tentativo utlizzando le informazioni indicate al link 
https://s3.eu-west-1.amazonaws.com/dikeupdate.infocert.it/guida_attivazione.pdf
Alcune carte infocert devono prima essere sbloccate perchè prodotte erroneamente con un blocco di default sul pin.
In seconda opzione, se lo sblocco non dovesse funzionare,  potrebbe provare ad installare applicativo DikeGoSign (si trova su internet) che con Chrome non ha mai presentato problemi, al netto ovviamente della piena funzionalità funzionato della carta. Buon lavoro, saluti

**Comment by ravelment** [comment]
Buongiorno,
grazie per i suggerimenti; purtroppo non sembrano avere portato miglioramenti.
Seguendo le istruzioni in "guida_attivazione.pdf" il relativo sotware, dopo l'inserimento dei codici pin e puk restituisce il messaggio "Il dispositivo di firma è già stato attivato".
Ho installato DikeGoSign e riavviato il pc per sicurezza, prima di riprovare, ma il problema si ripresenta esattamente come prima.
Chiedo: potrebbe trattarsi a questo punto di un blocco attivato dal nostro antivirus e/o firewall? Gli utenti che utilizzano le smart card vecchio modello non riscontrano difficoltà di accesso, ma forse queste nuove seguono un percorso diverso?
Grazie mille

**Comment by Leonforte** [comment]
Buongiorno, a questo punto credo si renda necessario richiedere nuove carte. Dalla console di sicurezza - gestione smart card - ricerca smart card- premere il tasto ricerca- selezionare l'utente con la lentina a dx e successivamente premere il tasto - richiedi nuova card.
Credo saranno disponibili presso la Prefettura di competenza nell'arco della prossima settimana. Buon lavoro, saluti

**Comment by ravelment** [comment]
Aggiornamento su questa issue:
* in una postazione abbiamo verificato che c'erano più versioni del driver SafeDive installate, che probabilmente andavano in conflitto. Disinstallato tutto e reinstallato solo la 3.4.1 --> risolto;
* in un'altra abbiamo risolto utilizzando browser Firefox: pur avendo versione driver corretta, con Chrome non c'è stato verso di farlo funzionare.
Rimane per il momento una postazione in cui il certificato sulla carta non sembra venire letto dal driver SafeDive ma dal "Provider Smart Card Microsoft", e qui l'errore iniziale "ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED" permane. Se riusciamo a risolverlo vi aggiorno.
Grazie per il supporto.

**Comment by cvignati** [comment]
Comune di Villa Cortese,
io ho smartcard del 2018 con scadenza 07.08.2024 ma purtroppo non riesco ad accedere a https://dp.anpr.interno.it/com ho l'errore
La pagina web all'indirizzo https://dp2.anpr.interno.it/com potrebbe essere temporaneamente non disponibile oppure è stata permanentemente spostata a un nuovo indirizzo web.
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

Grazie per il supporto

**Comment by Leonforte** [comment]
@cvignati 
risolto e connesso con successo. CRS Lombardia su Chrome, configurato Firefox per SC Athena.
