### ISSUE TITLE
Comuni subentrati – xlsx

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2707]
Buongiorno,
si segnala che la tabella in oggetto, al link https://www.anpr.interno.it/wp-content/uploads/Tabella_45-Comuni-subentrati.xlsx , ad oggi, restituisce il seguente errore:
![immagine](https://user-images.githubusercontent.com/46593834/122540168-a7f43200-d028-11eb-98d7-656d8098d751.png)

Resto in attesa di un Vostro riscontro
Cordiali Saluti

**Comment by cmigliardi** [comment]
buongiorno - grazie - stiamo verificando

**Comment by cmigliardi** [comment]
può  riprovare e mi fa sapere ?  grazie

**Comment by cmigliardi** [comment]
la redazione ha risolto -  mi può dare conferma ?  - la ringrazio

**Comment by fcastellani81** [comment]
Buongiorno,
sì, confermo. Ora è tutto ok.
Grazie per la celere risposta

Buona giornata
