### ISSUE TITLE
Firma certificazione online - Commissarrio straordinario

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2708]
Buonasera,
per due nostri clienti, entrambi commissariati, nel rilascio della certificazione online non riusciamo a far comparire la dicitura "Il commissario" e sotto cognome e nome del commissario. 
Invocando il certificato come "da internet", questo viene emesso con la dicitura "Il Sindaco del comune di..." e sotto il nome del commissario. 
Se invece spuntiamo il campo "Attiva responsabile certificazione online" ed inseriamo il titolo del responsabile certificazione online "Il commissario" allora il certificato viene emesse con il suddetto titolo ma il firmatario è un nome diverso da quello che inseriamo nella richiesta. Dove viene letto il nome del responsabile della certificazione online?
Anche ponendo il commissario come "Operatore di certificazione" la stampa non risulta come desiderata.
Cordiali saluti
Arditi Alessandro
Halley Informatica

**Comment by rvinzani** [comment]
Nell'area Amministrazione->Gestione dati del comune, sezione  "Parametri utilizzati per l'emissione dei certificati online" mettete la spunta su Attiva responsabile certificazione online e nel campo Titolo responsabile certificazione online (in lingua Italiana): inserite: Il Commissario straordinario. Ovviamente per la firma dovete utilizzare l'utenza del commissario straordinario per la richiesta del servizio di certificazione on line

**Comment by Hdemografici** [comment]
Ho risolto.Grazie mille
