### ISSUE TITLE
Variazione Security Officer

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2709]
Buongiorno,
abbiamo necessità di modificare il Security  Officer e il Responsabile delle CIE (in particolare per attivare nuove SCO e per problemi nell'agenda prenotazioni cie). 
L'assistenza CIE ci ha risposto nel modo seguente: "il cambio del Security officer e del Responsabile del Servizio CIE è da effettuarsi mediante l'accesso all'Area privata del portale http://servizidemografici.interno.it.
 A seguito dei cambi verranno create nuove credenziali per l'accesso al portale DVRAweb e per la gestione dell'Agenda CIE, e dette credenziali verranno inviate l'indirizzo mail associato a ciascuno degli utenti".

Purtroppo non siamo in possesso delle credenziale della precedente SO per accedere a tale area riservata e sempre l'assistenza CIE ci ha indicato di scrivere a anpr.password@interno.it ma non stiamo ottenendo risposta.

Come possiamo procedere?

Grazie  e buon lavoro
Katia

**Comment by katiavacchi** [comment]
Sollecito riscontro perché abbiamo urgenza di attivare nuove sco.

**Comment by Leonforte** [comment]
Buongiorno, il comune in questione ?

**Comment by katiavacchi** [comment]
Comune di Ravenna

**Comment by Leonforte** [comment]
Le credenziali per l'accesso all'area privata del CNSD sono state inviate al responsabile per la sicurezza degli accessi del comune, all'indirizzo : scanosani@comune.ra.it
Buon lavoro, saluti

**Comment by katiavacchi** [comment]
Chiedo scusa ma la responsabile ha già cessato il servizio.  Potete inviarla alla mail di chi la sostituisce?  francescodiscianni@comune.ravenna.it
Buon lavoro a voi!

**Comment by Leonforte** [comment]
Abbiamo effettuato un nuovo invio a francescodiscianni@comune.ravenna.it
Saluti

**Comment by katiavacchi** [comment]
Grazie mille.
