### ISSUE TITLE
Errore indicazione data di decorrenza

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#271]
Corbetta, Ambiente di produzione.

Buongiorno, per l'individuo codice ANPR 18644572, già cancellato da ANPR per emigrazione in comune non subentrato, il comune di emigrazione ha comunicato di aver sbagliato la data di decorrenza dell'emigrazione. 
Abbiamo provato ad annullare l'evento di cancellazione da ANPR per rifare l'evento con la data corretta però tale annullamento non va a buon fine per l'errore: EN077 - L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa. (ID Operazione ANPR 905302)
Vorremmo sapere quale altra operazione blocca l'annullamento e se per queste casistiche non esiste un'altra modalità di modifica del dato senza dover annullare l'evento e rieseguirlo.
Grazie
Luca Bonini APSystems

**Comment by gcarbonin** [comment]
E' stata effettuata una cancellazione riportando l'elenco delle persona della famiglia per sistemare i legami di parentela; dopo la cancellazione è stato trasmesso un 5001 con lo stesso elenco delle persone (mutazione non necessaria); l'id operazione comune è 25104. Al momento l'unica modalità consiste nell'annullare l'operazione; non ci sono funzioni di rettifica del dato soprattutto quando una scheda è archiviata.
