### ISSUE TITLE
PROPOSTA DI MODIFICA FUNZIONAMENTO OPERAZIONE ANNULLAMENTO MUTAZIONE

### ISSUE THREAD

**Issue by gianpaol** [italia/anpr#2710]
Perché con una singola operazione non è possibile annullare molteplici operazioni (ovviamente dello stesso tipo) magari selezionando le stesse direttamente da Elenco Operazioni? Pongo questa problematica poiché, al momento del subentro del nostro Comune, sono state comunicate molte date errate (da correggere con la funzione rettifiche la quale richiede l'assenza di operazioni effettuate) e contestualmente nei primi 3 mesi successivi a tale subentro per un malfunzionamento del nostro gestionale sono state effettuate una settantina di operazioni (automatiche) per un numero più o meno grande di nostri cittadini residenti di tipo 5 MUTAZIONE SCHEDA. Pertanto, capita sovente di imbattersi in cittadini che presentano un errore nella data di iscrizione per i quali non è possibile procedere con la funzione rettifiche in quanto sono presenti poco più di 70 operazioni che rendono difficoltosa la suddetta operazione in quanto costringono l'operatore a dover annullarle tutte una per volta (il tutto richiede dai 40 minuti all'ora di lavoro). 
Per maggiore chiarezza si veda l'esempio del cittadino ID ANPR 95384668 per il quale, prima di effettuare una mutazione di residenza nell'ambito dello stesso Comune, si è dovuto procedere seguendo l'iter precedentemente citato al fine di consentire la rettifica della data di iscrizione erroneamente coincidente con la data di nascita (simile casistica della issue #2671 ).

CONZA GIANPAOLO
COMUNE DI CASTELLAMMARE DI STABIA
AMBIENTE PRODUZIONE

**Comment by rvinzani** [comment]
Gent.le Sig. Conza, l'operazione di annullamento è un'operazione molto delicata in quanto come lei ben sa una stessa operazione potrebbe coinvolgere più persone o più attributi di una stessa scheda quindi da utilizzare con assoluta consapevolezza. Alcune operazioni poi, come quella sulle mutazione dei dati anagrafici non sono annullabili. Ciò detto però il gestionale può facilitare il compito dell'operatore richiamando ricorsivamente il servizio di annullamento reso disponibile da ANPR, ovviamente verificando l'esito di ogni singola chiamata prima di procedere con la successiva
