### ISSUE TITLE
[5008] Inserire tutti i dati anagrafici anche quelli non modificati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2712]
Ambiente di produzione, Comune di Dolo.

Si sta eseguendo una mutazione altri dati (dati anagrafici, permesso di soggiorno, professione) su un soggetto che in ANPR non ha il luogo di nascita. 
Il servizio risponde con EN139: Inserire tutti i dati anagrafici anche quelli non modificati, id operazione ANPR 566278704

Come si può risolvere ?
Grazie

**Comment by frmariani** [comment]
Il luogo di nascita del cittadino risulta inserito erroneamente nel campo "Luogo eccezionale";  nella mutazione inserisca correttamente il luogo di nascita.
Per questo genere di richieste gentilmente chiami il nostro numero verde 800863116

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
