### ISSUE TITLE
[Portale WEB cittadino] - Rettifica Dati 

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2713]
Buongiorno, in merito al servizio di rettifica dati vorrei sapere quale web service deve essere utilizzato (se c'è) per inviare la richiesta di un cittadino al proprio Comune per la correzione di “errori materiali” o di “errate trascrizioni” dei propri dati.
Grazie. Cordiali saluti

**Comment by FilippoPapi** [comment]
buongiorno
attualmente non ci sono web service. saranno realizzati prossimamente
saluti
