### ISSUE TITLE
Posizione Certificabile - Soggetto Non Iscrivibile

### ISSUE THREAD

**Issue by AlbertoMoroni** [italia/anpr#2715]
Volevo sapere gli effetti di questa scelta nella posizione certificabile del soggetto. 
Inibisce la possibilità per gli altri Comuni ANPR di iscrivere il soggetto?

**Comment by rvinzani** [comment]
No, è solo un alert che inserisce il comune in caso di segnalazioni particolari ma che non impedisce la movimentazione del soggetto
