### ISSUE TITLE
ERRATA PROVINCIA DI NASCITA IN PRESENZA DISALLINEAMENTO CON AE

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2716]
Buongiorno per il comune di SAN BARTOLOMEO AL MARE subentrato il giorno 24/06/2021 abbiamo la seguente posizione da sistemare per Disallineamento CF per cui vi chiediamo come meglio operare:
IDANPR 158561184
il comune di nascita corretto è OLGIATE CALCO (COMO) non OLGIATE CALCO (LECCO) è stata sbagliata la provincia di nascita 
Oltre a questo errore c'è un disallineamento anche sul nome il dato corretto è quello del comune/ANPR ovvero: CLELIA LARIA.
Questa operazione cambia il CF attualmente in AE ed il comune ha già avvisato la persona. 
Escludiamo la possibilità di variare il dato con una comunicazione 5008 dal gestionale perchè è presente un disallineamento con AE e ci segnalerebbe errore, pertanto vi chiediamo se possibile da WebAPP mutare questi dati prima di eliminare il disallineamento o se questo deve comunque essere risolto.
Se il disallineamento deve essere comunque risolto mi confermate che l'unica possibilità sarebbe confermare l'attuale dato di AE ed il giorno dopo inviare la comunicazione di rettifica generalità?
Grazie 
Cordiali saluti
Cinzia Girelli
GPI SpA
Cell. 3346216774

**Comment by rvinzani** [comment]
Come comunicato telefonicamente deve prima effettuare una mutazione tutti i dati per allineare ANPR ad Agenzia Entrate.
Poi deve selezionare Utilità e notifiche, risoluzione disallineamento con Agenzia Entrate, inserire il CF corretto (quello che termina con G027P), spuntare includi validati, cerca e sulla pagina successiva conferma i dati di AE.
Il giorno successivo può effettuare la successiva mutazione tutti i dati per aggiungere il secondo nome.
Se il comune avesse problemi nell'effettuare le operazioni può chiamare il nostro numero 800863116
