### ISSUE TITLE
Cancellazione contratto convivenza su schede anagrafiche

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2717]
Buongiorno.
Ho la necessità di cancellare il contratto di convivenza che era stato riportato erroneamente sulle schede anagrafiche cod. 40169525 e 40169526. Come posso fare?

I miei riferimenti sono i seguenti:
Paltrinieri Andrea
Ufficiale d'Anagrafe del Comune di Biassono (cod. istat 108009)
e-mail: paltrinieri.andrea@biassono.org
tel. 039-2201060

Distinti saluti.
Andrea Paltrinieri

**Comment by frmariani** [comment]
Per eliminare l'informazione deve annullare le operazioni che l'hanno determinata e le successive nell'ambito della stessa tipologia di dato; nel suo caso è stata effettuata un'operazione per l'inserimento della convivenza, un'operazione per la risoluzione della convivenza ed un'operazione per l'inserimento del matrimonio.
Dalla consultazione del cittadino, elenco operazioni, può visualizzare gli idanpr delle operazioni da annullare.
Nel caso avesse bisogno di supporto può chiamare il numero verde 800863116

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
