### ISSUE TITLE
[ws 3002] Tipo Cessazione Convivenza di Fatto: Codice '97'

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2718]
ambiente di PRODUZIONE - comune di CORSICO (015093)

idSoggettoANPR 59418664
il servizio di consultazione del soggetto ritorna il valore '97' all'interno del campo "Motivo Risoluzione Convivenza di Fatto"
il codice '97' non è censito all'interno della tabella 43 (tipo cessazione unioneCivile convivenze)

a cosa dovrebbe corrispondere?
se possibile, aggiornate anche il file excel corrispondente.

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
tabella '43', scusate

**Comment by gianpaol** [comment]
Nella issue #2615 faccio riferimento alla stessa problematica. Il codice '97' dovrebbe corrispondere alla motivazione "Chiusura d'ufficio per cancellazione del soggetto". In issue precedenti è stato accennato il suo significato (nella mia issue le cito) ma di fatto non si sa a cosa si riferisca. Mi era stato promesso che sarebbe stata aggiornata la tabella ma vedo che non è stato fatto.

**Comment by ncapozzi** [comment]
Buonasera,
la tabella 43 è stata aggiornata
N. Capozzi
