### ISSUE TITLE
Variazioni delle codifiche delle Tabelle

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#272]
Buongiorno,
abbiamo verificato che avete variato i codici dei valori inseriti nella tabella 43 dove il decesso dell'unito civilmente è passato dal codice 5 al codice 98.
Premesso che tale nuova codifica non è congrua neanche con le specifiche dell'oggetto 'ScioglimentoUnioneCivile' per cui il motivo di scioglimento dev'essere inferiore a 31, si chiede cortesemente di essere informati quando ci sono queste variazioni perché ci comportano variazioni sugli enumeratori all'interno della procedura.
Grazie.

**Comment by gcarbonin** [comment]
Buongiorno. La tabella è stata modificata il giorno 11 maggio, come indicato nell'elenco delle modifiche . E' stata introdotta per uniformità di trattamento con il matrimonio (dove il codice 98 indica il decesso del coniuge).  Aggiorniamo, come da lei evidenziato, il commento dell'oggetto ScioglimentoUnioneCivile precisando che il motivo di scioglimento ESCLUSO IL DECESSO deve essere inferiore a 31.  Per quanto riguarda gli avvisi delle modifiche, li pubblichiamo in ambiente di test-comuni e pre-subentro, di recente anche attraverso una issue.
