### ISSUE TITLE
RETTIFICA/INTEGRAZIONE INDIRIZZO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2720]
Buongiorno,
QUESITO:
Inviando rettifica/integrazione indirizzo di un nucleo WS5001 tipo mutazione 9 produce l'invio dei dati agli altri enti (AE, INPS e MCTC) come avviene per cambio domicilio?
Grazie

**Comment by azabatta** [comment]
Buongiorno, 
sì, si conferma che l'evento anagrafico viene notificato agli  enti indicati.
Saluti
