### ISSUE TITLE
Codice Istat San Vincenzo della Fonte

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2721]
Buongiorno,
dalla verifica della tabella Archivio dei Comuni, San Vincenzo della FOnte (ora Saint-Vincent) risulta avere associato un codice ISTAT non corretto in quanto associato a 007065 (Saint-Vincent) mentre l'Istat corretto risulterebbe essere 007554
E' possibile effettuare verifica?
Grazie

UPI Torino

**Comment by ncapozzi** [comment]
Buongiorno,
il cod. ISTAT corretto è sempre 007065. Il codice 007554 è un codice per cambio denominazione, come tutti quelli con 5 al quarto carattere, attribuito per i vecchi ambienti INA-SAIA e AIRE nei quali il cod. ISTAT doveva essere necessariamente univoco.
Nel file pubblicato trova infatti il codice 007544 nella colonna COD-DENOM di SAN VINCENZO DELLA FONTE

N. Capozzi
