### ISSUE TITLE
WS3002 - CONSULTAZIONE SCHEDA FAMIGLIA

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2722]
Buonasera,
Utilizzando il servizio 3002 per scheda famiglia è possibile, nell' XML di risposta, avere un tag che indichi il numero di componenti presenti nel nucleo stesso?.
Grazie

**Comment by rvinzani** [comment]
Salve, è possibile invocare il servizio 3002 richiedendo i dati della famiglia ed ottenere la lista dei soggetti appartenenti. Non credo quindi che vi sarà un'evoluzione in tal senso visto che l'informazione comunque è prevista.

**Comment by rinonasti** [comment]
Grazie infinite
