### ISSUE TITLE
Attribuzione codice fiscale

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2723]
Buongiorno,
COMUNE DI CASERTA  061022 - PROD
Un cittadino iscritto AIRE in ANPR non ha il codice fiscale.
Su AE è presente ma risulta non iscritto AIRE. Nel tentativo di attribuzione si presenta il seguente errore:
Codice fiscale individuato in AT con dati anagrafici diversi o indirizzo diverso (Codice: EAA30)
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-06-30 10:35:15 , idOperazioneANPR 569969486 (Codice: EN527)
Come si può risolvere?
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
se il cittadino ha già un codice fiscale attribuito da Agenzia delle Entrate non dovete chiedere una nuova attribuzione come avete fatto ma indicare il CF nella mutazione dati richiedendone la validazione.

**Comment by rinonasti** [comment]
FATTO MA:
CF presente ma dati anagrafici non congruenti (Codice: EAV31)
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-01 13:12:57 , idOperazioneANPR 571255926 (Codice: EN527)

QUALE TIPO DI MUTAZIONE PREVEDE LA VALIDAZIONE?
ABBIAMO USATO TUTTI I DATI

**Comment by ncapozzi** [comment]
Il tipo di mutazione è quello giusto ma come dice il msg di errore i dati anagrafici non sono congruenti, in particolare il cognome trasmesso è diverso da quello presente su AE come potete verificare effettuando la Consultazione AE dalla web app o andando su siatel.
E' necessario pertanto in rpimo luogo verificare qual'è il cognome corretto. Se è corretto quello di AE basta cambiare  il cognome nella richiesta trasmessa. Se invece è corretto quello del Comune la mutazione deve essere effettuata senza richiedere la validazione del CF e successivamente deve essere effettuata la risoluzione disallineamenti con AE dalla web app/utilità e notifiche per confermare i dati del comune.

**Comment by rinonasti** [comment]
OK eseguita operazione per cognome valido del comune (WS5008 con attribuzione CF=3) - adesso è presente il codice fiscale in ANPR ma non validato.
Però non troviamo il disallineamento AE

**Comment by rinonasti** [comment]
Scusa risolto.
Grazie per la fattiva e preziosa collaborazione
