### ISSUE TITLE
Carte d'Identita' rilasciate da Consolati soppressi rif.to #833

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2724]
In riferimento alla issue in oggetto chiediamo se ci sono novità, poichè durante il completamento dei dati AIRE (comunicazione 5008) l'anomalia EC100 continua ad essere segnalata. 

Stiamo per pianificare il subentro del comune di Casteltermini che ha 116 posizioni con carta di identità emessa da Consolati attualmente soppressi. Alcune scadute (40) le altre in corso di validità. 

Grazie 
Cordiali saluti

Cinzia Girelli
Gpi Spa
cell. 3346216774

**Comment by ncapozzi** [comment]
Buongiorno,
come anticipato per le vie brevi si conferma l'intervento eseguito nel 2018 sul controllo EC100 per accettare anche i Consolati cessati.
Per il Comune di Casteltermini non sono presenti test eseguiti in pre-subentro.
Per il Comune di Vigevano in produzione sono presenti casi di 5008 per completamento dati AIRE che hanno restituito EC100 ma non perché il Consolato sia cessato. bensì perché il codice indicato effettivamente non è congruente con la descrizione della sede (si veda ad es. id operazione 490023158 490023620).
