### ISSUE TITLE
Iscrizione Altri Motivi di un Irreperibile

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#2725]
Salve,
dobbiamo importare un individuo che in ANPR è cancellato per irreperibilità (cancellato da un altro comune); all'invio della pratica otteniamo l'errore: 
idSchedaSoggettoANPR 131228923 non presente o dati anagrafici incongruenti

Dal 3002 ci siamo accorti che la descrizione stato della località presenta uno spazio alla fine...di seguito il relativo tag nell' xml restituito
<descrizioneStato>BURKINA FASO </descrizioneStato>
Tale anomalia è indicata anche nelle anomalie restituite dal 3002 ovvero: Stato estero di nascita:BURKINA FASO  non esistente

Nel 1002 abbiamo provato ad inviare la descrizione stato sia senza lo spazio finale e sia con lo spazio ma l'esito è sempre lo stesso.
Di seguito gli errori ottenuti dalle due prove effettuate:
- Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-01 09:40:09 , idOperazioneANPR 570860688
- Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-01 12:22:23 , idOperazioneANPR 571176448
Restiamo in attesa di indicazioni per risolvere il problema

Assistenza tecnica Comune di Legnano

**Comment by rvinzani** [comment]
Abbiamo aggiornato lo stato di nascita togliendo lo spazio finale. Potete riprovare l'operazione

**Comment by acarcea** [comment]
l'invio dell'operazione fatto stamattina produce sempre lo stesso errore:
1 Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 131228923 non presente o dati anagrafici incongruenti
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-02 09:29:51 , idOperazioneANPR 571962911

**Comment by rvinzani** [comment]
E' stato indicato nella reiscrizione il nuovo numero identificativo comunale. E' necessario toglierlo

**Comment by acarcea** [comment]
Provato ad inviare il 1002 senza numero identificativo comunale (forzand il funzionamento del sw) ma il problema è lo stesso:
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-02 17:28:12 , idOperazioneANPR 572557683

inoltre è stato fatto un test in ambiente di presubentro replicando la stessa casistica senza rimuovere l'identificativo comunale dell'ente gestore dal 1002 e tutto ha funzionato correttamente. 
Per verifica:
- 3002 prima del 1002:  idOpAnpr = 23853533 del  01-07-2021 12:40
- 1002: IdOpAnpr = 23853535 del 01-07-2021 12:42
- 3002 dopo il 1002: idOpAnpr = 23903443  del 02-07-2021  17:13

Il comportamento ottenuto nel pre-subentro è secondo noi corretto in quanto con il solo 1002 andiamo anche ad aggiornare in nuovo numero identificativo del comune che sta iscrivendo evitando quindi una seconda operazione di mutazione dati per aggiornare il dato.

Restiamo in attesa di ulteriori indicazioni

**Comment by rvinzani** [comment]
Dovrebbe togliere anche il codice stato e il campo provinciaContea in quanto non presenti sulla scheda del soggetto cancellato

**Comment by acarcea** [comment]
Salve,
abbiamo provato ad inviare secondo le indicazioni fornite ma purtroppo ancora senza esito; in dettaglio:
1 prova --> non inviando affatto il tag <codiceStato> l'xml non viene validato; l'errore di validazione è: the content of element 'localita' is incomplete. Expected: codiceStato
2 prova --> inviata operazione senza nuovo numero identificativo comunale, senza provinciaContea e con codiceStato = 409: restituisce sempre l'errore finora ottenuto: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-05 09:09:33 , idOperazioneANPR 573617480
3 prova --> inviando tag <codicestato> vuoto l'xml non viene validato;  l'errore di validazione è: The content of element 'codiceStato' is not valid according to its type definition 'numerico3'

Restiamo ancora in attesa di indicazioni circa la risoluzione del problema

**Comment by rvinzani** [comment]
Può mandarmi un suo recapito e sentirci direttamente? Grazie

**Comment by acarcea** [comment]
Salve, certamente...
cell: 3421207406

**Comment by rvinzani** [comment]
come da accordi chiudo la issue
