### ISSUE TITLE
Utente già esistente cambio Ente

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2726]
Buongiorno,
attualmente l'utente (cf SRFLRI75D48C319W) già in precedenza censito presso il Comune di Subbiano (AR) si trova ad utilizzare la propria smartcard presso la nuova sede di lavoro (Comune di Sinalunga (S)).
Si richiede cortesemente la procedura affinchè lo stesso utente possa accedere alla webapp ANPR dalla nuova sede di lavoro in quanto, tentando di effettuare l'accesso, viene riportato il seguente errore 
![image](https://user-images.githubusercontent.com/46593834/124234582-80b35f80-db14-11eb-86cd-5dda2d8ac51e.png)

Si precisa, inoltre, che la stessa smartcard se verificata tramite driver Athena, riporta correttamente le credenziali dell'utente
![image](https://user-images.githubusercontent.com/46593834/124234815-d0922680-db14-11eb-9489-036b91f5270e.png)

Cortesemente, contattare l'Ufficio Servizi Demografici del Comune di Sinalunga:
tel: 0577/635224 (dal lunedì al venerdì dalle ore 08:30 alle 14:00 e il lunedì e giovedì pomeriggio dalle ore 15:00 alle 18:00)
mail: ilaria.serafini@comune.sinalunga.si.it 

Cordiali Saluti

**Comment by Leonforte** [comment]
Buongiorno, l'utente non è autorizzato all'accesso per il comune di Sinalunga, occorre semplicemente che l'amministratore locale della sicurezza (ALS) del comune di Sinalunga lo inserisca come utente attraverso la console di sicurezza. Questa operazione deve essere effettuata prima che il comune di Subbiano lo cancelli o lo blocchi. Buon lavoro, saluti

**Comment by fcastellani81** [comment]
Risolto, grazie!
Chiudo la issue
