### ISSUE TITLE
MODIFICA DATE 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2727]
Buongiorno,
COMUNE CASERTA 061022 - PROD
Come è possibile modificare la data di decorrenza residenza di un cittadino immigrato da altro comune subentrato?
Ovviamente anche data di ingresso nel nucleo.
Eseguendo da webapp rettifica dati subentro e modificando le date viene fuori errore:
Sono presenti modifiche con data decorrenza successiva al subentro, non e' possibile eseguire la rettifica delle date (Codice: EN475)
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-05 13:22:57 , idOperazioneANPR 574109106 (Codice: EN527)
Come si possono evidenziare queste operazioni successive ed eventualmente eliminarle?
Grazie

**Comment by frmariani** [comment]
Vedo che per il cittadino è stata effettuata una mutazione di residenza dopo il subentro; in questo caso la data non può essere rettificata, deve annullare l'operazione. 
Le operazioni effettuate sono visibili dalla  consultazione del cittadino  > Elenco operazioni

**Comment by rinonasti** [comment]
Si l'operazione di mutazione di residenza è stata fatta dal comune di Caserta (noi) , ma sbagliando data 05/05/2021 invece di 28/06/2021.

**Comment by frmariani** [comment]
Allora deve annullare quell'operazione e rifarla con la data corretta

**Comment by rinonasti** [comment]
Ok grazie fatto andato a buon fine.
Quesito: E' l'unica possibilità per la correzione di date di immigrazione e conseguente ingresso in nucleo?

**Comment by frmariani** [comment]
se la data non corretta proviene da un'operazione successiva al subentro può soltanto annullare l'operazione e rifarla, se la data non corretta proviene dal subentro può rettificare alcune date come stava operando precedentemente, ma non può modificare la data di ingresso nella famiglia.

**Comment by rinonasti** [comment]
OK Grazie per la fattiva collaborazione

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
