### ISSUE TITLE
ANPR non funzionante - TORINO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2729]
Buongiorno,
da circa 20 minuti ANPR risulta non funzionante. ALtri comuni hanno lo stesso problema?
Grazie

UPI Torino

**Comment by fcastellani81** [comment]
Buongiorno,
attualmente non è possibile emettere CIE in quanto il sistema espone messaggio " Attenzione, si è verificato un errore nella creazione richiesta; servizio ANPR momentaneamente non disponibile. Si prega di riprovare più tardi".
Altri Enti lo stesso problema?
Grazie

**Comment by FilippoPapi** [comment]
buon pomeriggio, la situazione è tornata alla normalità alle 15.16
Saluti
