### ISSUE TITLE
Consultazione scheda individuale + elenco componenti

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#273]
Buongiorno, non credo sia già stato segnalato.
Ambiente di test.
Vado in consultazione scheda individuale di soggetto non IS. Esempio id anpr 7794414.
Clicco su Famiglia /Convivenza. Poi Elenco componenti.
Se a questo punto clicco ad esempio su Atto di nascita, sto vedendo i dati del primo componente della famiglia, e non di quello che stavo consultando.

**Comment by gcarbonin** [comment]
I dati "di dettaglio" sono quelli della scheda interrogata all'inizio. L'elnco componenti è stato aggiunto su richiesta di qualche comune per poter vedere i dati della famiglia ma non interviene  sui dati della scheda

**Comment by MarcoMigliori** [comment]
Sarei d'accordo se funzionasse così.

**Comment by gcarbonin** [comment]
??

**Comment by MarcoMigliori** [comment]
Ripeto passo passo.

Consultazione scheda id 7794414 (test)
Vado su atto di nascita. **Il campo Anno è 1990**.
Vado su Famiglia/Convivenza. Quindi su elenco componenti.
A questo punto clicco di nuovo a sinistra su Atto di nascita. **Il campo Anno è ora 1960**, che corrisponde ai dati del 1° componente della famiglia, e non del 3° che stavo interrogando.

**Comment by gcarbonin** [comment]
Ok facciamo le verifiche del caso

**Comment by gcarbonin** [comment]
Può riprovare e darci un riscontro?

**Comment by MarcoMigliori** [comment]
Risolto, grazie.
