### ISSUE TITLE
Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione.

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#2730]
Buongiorno,
si chiede assistenza per il seguente errore:
Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione.; Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-07 10:51:01 , idOperazioneANPR 576138590; 

Ho erroneamente iscritto una persona AIRE per un motivo sbagliato (acquisto cittadinanza invece di nascita). Non posso annullare il procedimento in quanto risulta il procedimento idOperazioneANPR 576138590 fatto successivamente (cambio della data di nascita in quanto inerita erroneamente), che è una rettifica.
Come è possibile procedere?

**Comment by frmariani** [comment]
Per un cittadino Aire è possibile modificare il motivo iscrizione con l'operazione di Mutazione dati Aire, tipo di mutazione "Dati generali iscrizione".
Mi faccia sapere

**Comment by marcoLave** [comment]
Purtroppo non mi permette di modificare i Dati generali d'iscrizione in quanto l'"iscrizione per nascita (AIRE)" è un'operazione diversa da "iscrizione altri motivi (AIRE)" quindi dovrei annullarla e inserirla correttamente perchè nell'iniziativa di iscrizione posso solamente inserire:
-altro
-d'ufficio
-in base a richiesta legittima
-su comunicazione dell'ufficio consolare
-su comunicazione dell'ufficio di stato civile
- su richiesta di un ufficiale di anagrafe
Non è possibile inserire per nascita.

**Comment by frmariani** [comment]
Non possiamo trasformare un'iscrizione per altri motivi AIRE in un'iscrizione per nascita AIRE; non possiamo neanche annullare l'operazione di mutazione dei dati anagrafici.
Nella Mutazione dati Aire può scegliere "Altro" e nelle note inserire "Iscrizione per nascita", al momento non vedo altre soluzioni.
mi scriva un suo recapito telefonico al seguente indirizzo
frmariani@sogei.it
