### ISSUE TITLE
Richieste non processate in ambiente di test

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2731]
Stamattina verso le 9:36 abbiamo effettuato quattro richieste 4005 (id operazioni ANPR 39878765, 39878766, 39878767, 39878769).
Ad ora (11:46) non risultano ancora processate, il che è strano perché solitamente vengono gestite giro di una decina di minuti.
Potete verificare e sbloccare la situazione ?

Grazie

**Comment by amollicone1982** [comment]
4005 elaborati

**Comment by busaster** [comment]
perfetto, grazie mille
