### ISSUE TITLE
TestConnessione SUBENTRO

### ISSUE THREAD

**Issue by adrianosicilia** [italia/anpr#2733]
Buongiorno, sono Adriano Sicilia, per conto del comune di Rende-CS (078102), completata la fase di SUBENTRO, abbiamo ripreso con lo sviluppo dei ws per allineare le banche dati LOCALE e ANPR, effettuando dei test di connessione che in fase di PRE-SUB funzionavano, ora in PRESUBENTRO riceviamo ancora un time-out con risposta negativa 

"
2021-07-09 09:40:40 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):916295DD
2021-07-09 09:41:01 WARN  PhaseInterceptorChain:449 - Interceptor for {http://sogei.it/ANPR/TestConn}TestConn#{http://sogei.it/ANPR/TestConn}testConnessione has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Connection timed out: connect
"

Controllando il file che viene creato in fase di invio da [**tool-testconn-1.3.0.jar
Duplicate of #**] ho notato che l'indirizzo IP prelevato "192.168.56.1" dalla procedura è quello della lan interna della 1° scheda di rete e non quello pubblico 217.59.135.164 attivo sulla 2° scheda di rete. 

"
 <saml2:AuthnStatement AuthnInstant="2021-07-09T07:40:39.904Z" SessionNotOnOrAfter="2021-07-09T07:45:39.904Z">
                    <saml2:SubjectLocality Address="192.168.56.1"/>
                    <saml2:AuthnContext>
                        <saml2:AuthnContextClassRef/>
                    </saml2:AuthnContext>
                </saml2:AuthnStatement>
"
E' gradito qualsiasi suggerimento atto a risolvere il problema.
Cordiali saluti.

_Originally posted by @adrianosicilia in https://github.com/italia/anpr/issues/2632#issuecomment-877017233_

**Comment by amollicone1982** [comment]
Penso che abbiate qualche problema di rete. l'host da risolvere è https://wspre.anpr.interno.it.
Sembrerebbe che stiate traducendo l'host con dns locale invece che con dns pubblico su internet

**Comment by gife67** [comment]
Buongiorno,
ho verificato che in ambiente di presubentro abbiamo ricevuto dalle 09:22 alle 09:37 di Venerdì 09.06.2021 5 richieste verso il servizio di TestConn, dall'IP 217.59.135.165 (e non .164 come avete indicato), dalla postazione 078102-PC-0001 con CF = BLM*****86V, di cui 3 fallite con Soap Fault "Rejected by policy", che sta ad indicare che c'è un problema nella cornice di sicurezza e 2 con le stesse caratteristiche andate bene.
Provo a far mettere una trace per darvi dei dettagli maggiori sul tipo di problema. Se potete inviare ulteriori richieste fra circa 5-10 minuti ed inviarne una ogni minuto, in modo da poter catturare i vostri messaggi.
Per il connection timeout questo sicuramente è dovuto alla vostra infrastruttura che non propaga i messaggi di soapfault in cui è riportato il messaggio "Rejected by policy"
E' normale che nella SAML ci sia il vostro indirizzo interno, poichè le librerie lo prelevano dal server su cui viene preparata la SAML assertion, non ha alcuna influenza sui filtri di accesso, ma ha solo scopo di Audit.

**Comment by gife67** [comment]
Buongiorno, 
oggi ho verificato che ci sono 2 richieste entrambi andate bene dall'IP 82.62.244.165, con lo stesso certificato di postazione e la stessa utenza.

**Comment by adrianosicilia** [comment]
Buongiorno, 
l'IP 82.62.244.165 è quello della mia postazione al di fuori del comune ed il test era in ambiente di presubentro.
per l'indirizzo 217.59.135.164 pubblico ufficiale siamo in attesa che i responsabili de FireWall del comune effettuino le abilitazioni e tal proposito ci hanno chiesto di individuare l'indirizzo e le porte di destinazione che ANPR mette a disposizione in modo da mappare il tutto correttamente.
Personalmente non sono riuscito a rispondere a questo quesito.

Cordiali saluti

**Comment by gife67** [comment]
Buongiorno, 
le riporto gli endpoint dei vari ambienti con relativi indirizzi IP, la porta per tutti è la 443:
TestComuni      wstest.anpr.interno.it   217.175.52.217
Presubentro     wspre.anpr.interno.it    217.175.52.221
Produzione      ws.anpr.interno.it          217.175.52.225

Codiali saluti

**Comment by adrianosicilia** [comment]
Buongiorno,
hanno creato la regola sul firewall ed il test di connessione ha dato esito 200, quindi positivo.
Lunedì proveremo le altre richieste di scambio dati.
Grazie per la collaborazione.
Cordiali Saluti

**Comment by gife67** [comment]
Buongiorno,
visto che la situazione si è sbloccata e sono state individuate le cause del problema, chiudo la issue.
Nel caso aveste bisogno di ulteriore supporto potete aprirne una nuova.
Cordiali saluti
