### ISSUE TITLE
CANCELLAZIONE CITTADINANZA

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2734]
Buongiorno,
COMUNE CASERTA - PROD
In fase di iscrizione (ricomparsa da irreperibilità) di un cittadino sono state attribuite erroneamente  due cittadinanze.
Una di queste deve essere annullata.
Quale servizio consente tale operazione?.
Grazie

**Comment by frmariani** [comment]
Il servizio 5008 tipo mutazione 2;
da web app, Mutazione tutti i dati, tipo mutazione cittadinanza

**Comment by rinonasti** [comment]
Come si cancella una delle due cittadinanze inserite?

**Comment by frmariani** [comment]
da web app Mutazione tutti i dati tipo mutazione cittadinanza ed elimina con la X la cittadinanza non corretta;
da servizio WS 5008 tipo mutazione 2 ed invia la sola cittadinanza corretta.

Spero di essere stata più chiara

**Comment by rinonasti** [comment]
Perfetto grazie infinite
