### ISSUE TITLE
Problema assegnazione smartcard/utente

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2735]
Buongiorno,
operatore (CNTPLA79R44A471K) che cambia luogo di lavoro, dal Comune di Cornuda al Comune di Loria.
nell'atto di attribuire il nuovo utente al Comune di Loria, viene visualizzato il seguente errore
![immagine](https://user-images.githubusercontent.com/46593834/125064515-0739e500-e0b1-11eb-97a8-51f8beba765f.png)

Contatti Ufficio Servizi Demografici - Comune di Loria
tel. 0423 456725
email. paola.conte@comuneloria.it

Si resta in attesa di gradito riscontro
Cordiali Saluti

**Comment by Leonforte** [comment]
Buongiorno, il comune di Cornuda ha eliminato l'utenza, potete cortesemente riprovare ? grazie

**Comment by fcastellani81** [comment]
Buongiorno,
è stata richiesta una nuova smartcard da parte dell'utente.
Grazie
