### ISSUE TITLE
Procedura Rettifica Nome non accettata

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2736]
Buongiorno per il comune di SAN BARTOLOMEO AL MARE subentrato il 24/06/2021, per un soggetto con ID 158562513 è stata utilizzata post subentro la Risoluzione anomalie con AE da WEBAPP poichè vi era il nome di battesimo disallineato con AE e anche lo stato di nascita. E' stato scelto il nome presente in ANPR ovvero ZIYAD MURAD OGLU (In AE era solo ZIYAD) mentre lo stato è stato allineato con AE. Il codice fiscale è stato quindi rettificato --Vecchio: MRDZYD96A05Z253N -- Nuovo MRDZDM96A05Z253N
Ora la posizione è validata in entrambi i sistemi e i due codici risultano collegati in AE.
Oggi però l'ufficiale d'anagrafe ci indica che vuole tornare a chiamarlo ZIYAD, ma provando a fare la rettifica di generalità (dalla data di iscrizione ovvero 11/05/2021) dal WS ci segnala che non è possibile perchè ci sono due operazioni successive e nella fattispecie le seguenti: 57770716 del 08/07/2021 e 580089367 del 12/07/2021. 
Chiediamo quale sia la procedura corretta per ripristinare il nome, senza incorrere in ulteriori errori. 

E' possibile contattare il comune nella persona del Sig. Giancarlo Corbella al nr.  0183 400071 oppure me al nr 3346216774?

Grazie 

Cordiali saluti
Cinzia Girelli
GPI Spa

**Comment by rvinzani** [comment]
Gent.le Sig.ra Girelli, non è possibile effettuare una mutazione di dati ad una data precedente ad un'altra effettuata sulla stessa tipologia di dati. Nella fattispecie la prima data utilizzabile è il 12/07/2021, Non è neppure possibile effettuare un'annullamento della variazione di dati anagrafici. Chiudo la issue pregandola di contattare il nostro servizio di assistenza al n. 800863116 nel caso avesse bisogno di informazioni più dettagliate
