### ISSUE TITLE
Codifica Numeri civici

### ISSUE THREAD

**Issue by raffaelemiranda** [italia/anpr#2737]
Salve, faccio seguito alla corrispondenza pregressa in relazione ai numeri civici che hanno un formato del tipo: numerocivico/numero (ad esempio 43/1, 43/2, 20/86, ecc).
Allo stato attuale sul certificato ANPR compare una codifica del tipo(esempio civico 43/6):
Numero civico:43
Lettera:6

Considerato che un certificato di questo tipo potrebbe comportare una cattiva interpretazione di lettura del civico
si chiede di conoscere se è possibile personalizzare i certificati ANPR facendo uscire il civico corretto e quindi 43/6 (come esempio).
Basti pensare che nel Comune di San Giuseppe Vesuviano ci sono circa 4000 civico con questo formato.
Si resta in attesa di un urgente riscontro in merito anche nella considerazione dell'imminente subentro.
Nell'ipotesi che non fosse possibile si chiede di avere contezza di conoscere se gli altri comuni che sono nelle nostre medesime condizioni hanno lasciato il campo numero (quello dopo la / per intenderci) nel campo lettera o hanno utilizzato qualche altro campo.

**Comment by rvinzani** [comment]
Gent.le Sig. Miranda, non è possibile personalizzare i certificati per ogni singolo comune. Non abbiamo indicazioni su come si siano comportati altri comuni sulla scelta del numero aggiuntivo al civico.

**Comment by raffaelemiranda** [comment]
> Gent.le Sig. Miranda, non è possibile personalizzare i certificati per ogni singolo comune. Non abbiamo indicazioni su come si siano comportati altri comuni sulla scelta del campo da utilizzare per indicare il numero aggiuntivo al civico.
