### ISSUE TITLE
Gent.le Sig. Miranda, non è possibile personalizzare i certificati per ogni singolo comune. Non abbiamo indicazioni su come si siano comportati altri comuni sulla scelta del campo da utilizzare per indicare il numero aggiuntivo al civico.

### ISSUE THREAD

**Issue by raffaelemiranda** [italia/anpr#2738]
Gent.le Sig. Miranda, non è possibile personalizzare i certificati per ogni singolo comune. Non abbiamo indicazioni su come si siano comportati altri comuni sulla scelta del campo da utilizzare per indicare il numero aggiuntivo al civico.

_Originally posted by @rvinzani in https://github.com/italia/anpr/issues/2737#issuecomment-880579653_

**Comment by raffaelemiranda** [comment]
Buongiorno @rvinzani, porgo la domanda in un altro modo. Il numero indicato dopo il simbolo "/" come deve essere passato ad ANPR affinché compaia nel certificato di residenza di ANPR il civico del tipo numerocivico/numero (esempio Via Pippo, 43/6).

**Comment by rvinzani** [comment]
ho verificato, il comune di Nembro utilizza il campo esponente1.
In tal modo il campo è separato dal numero civico da uno slash
