### ISSUE TITLE
MANCATA RICEZIONE NOTIFICHE MUTAZIONE RESIDENZA

### ISSUE THREAD

**Issue by MarcellaM** [italia/anpr#2739]
Buongiorno, l'Ufficio elettorale ha segnalato che alcuni cittadini non sono stati cancellati dall'anagrafe locale, ma in ANPR sono regolarmenti residenti nel nuovo Comune.
Le notifiche di questi soggetti non sono mai arrivate. Chiaramente non mi è possibile sapere quante notifiche non sono andate a buon fine.
Come posso verificare le notifiche mai ricevute e richiedere un nuovo invio?
indico il codice ANPR di alcuni soggetti come esempio : 62657016; 34425621.

Ringrazio e porgo cordiali slauti
Marcella Molinari - Comune di Alessandria

**Comment by amollicone1982** [comment]
Le N010 relative ai due soggetti segnalati risultano correttamente inviate rispettivamente in data 30/11/2020 11:38:04 e in data 27/05/2021 13:54:31. Ce ne sono 63 che invece risultano andate in errore che se volete possiamo rinviare

**Comment by MarcellaM** [comment]
Nonostante risultino correttamente inviate non sono mai pervenute. 
Quale può essere la causa? 

Quelle in errore se potete reinviarle le verifico e se possibile chiedo il reinvio di quelle indicate mai pervenute. 

Grazie 



Città di Alessandria 


Marcella Molinari 

Ufficio Anagrafe-AIRE 
Tel. 0131-515194 
Pec: ***@***.*** 


Avvertenze ai sensi del D.lgs. n. 196/2003 “Codice in materia di protezione dei dati personali” e del Regolamento (UE) 2016/679 “Regolamento Generale sulla Protezione dei Dati” (GDPR): il presente messaggio contiene informazioni attinenti l'attività lavorativa. Le eventuali risposte potranno essere conosciute da altri soggetti nell'ambito dell'organizzazione del mittente. Questo messaggio di posta elettronica ed i suoi allegati sono riservati ed il loro utilizzo è consentito esclusivamente al destinatario del messaggio, per le finalità indicate nel messaggio stesso. Qualora riceveste questo messaggio senza esserne il destinatario, siete invitati cortesemente a darne notizia via e-mail al mittente e a procedere alla distruzione dello stesso cancellandolo dal Vostro sistema. Costituisce comportamento contrario ai dettati del D.Lgs. 196/2003 il trattenere il messaggio stesso, divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, diffonderne comunque il contenuto. 


Da: "amollicone1982" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "MarcellaM" ***@***.***>, "Author" ***@***.***> 
Inviato: Lunedì, 19 luglio 2021 8:36:10 
Oggetto: Re: [italia/anpr] MANCATA RICEZIONE NOTIFICHE MUTAZIONE RESIDENZA (#2739) 





Le N010 relative ai due soggetti segnalati risultano correttamente inviate rispettivamente in data 30/11/2020 11:38:04 e in data 27/05/2021 13:54:31. Ce ne sono 63 che invece risultano andate in errore che se volete possiamo rinviare

**Comment by amollicone1982** [comment]
Per averle segnate come inviate dovremmo aver ricevuto risposta dal vostro endpoint. 
Intanto ho rinviato le 63 indicate ed ho verificato che il vostro endpoint, se sovraccaricato per alcune notifiche, ha risposto in modo negativo in un primo invio e positivo ad un secondo o terzo tentativo.
Mi viene da pensare che un invio di notifiche massivo (in questo caso 63) possa generare problematiche al vostro servizio
