### ISSUE TITLE
Allineamento dati non possibile con codici fiscali già collegati

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2740]
Buongiorno,
a seguito di modifica delle generalità di un cittadino, dobbiamo allineare i dati facendo prevalere su ANPR i dati di AE ma compare il messaggio allegato. Lo stesso se proviamo a fare mutazione dati.
 
I due CF risultano già collegati.

Grazie
cordiali saluti.

![errore allineamento](https://user-images.githubusercontent.com/57749903/125925534-1e7d0fab-084a-4947-bc93-59f77a9cf495.JPG)

**Comment by frmariani** [comment]
IL codice fiscale è stato svalidato, potete ripetere l'operazione di modifica dei dati richiedendo la validazione del CF.

Mi faccia sapere

**Comment by frmariani** [comment]
da verifiche effettuate la situazione non è stata ancora risolta.
Come mai ?

**Comment by katiavacchi** [comment]
risolto, grazie mille.
