### ISSUE TITLE
ANPR Archivio comuni - Nuovo comune di Misiliscemi

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2741]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 7 giugno 2021, segnalo l'istituzione del comune di Misiliscemi (TP) con efficacia dal 20 febbraio 2021:

* **codice ISTAT 081025** come da versione aggiornata del [Codici statistici delle unità amministrative territoriali](https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv).
* **codice amministrativo nazionale M432** come da [risoluzione dell'Agenzia Entrate del 3 marzo 2021](https://www.agenziaentrate.gov.it/portale/documents/20143/3288760/Risoluzione_istituzione+nuovo+comune_Misiliscemi_TP_M432.pdf).

Grazie.

**Comment by ncapozzi** [comment]
Buongiorno
il Comune di MISILISCEMI è stato attivato in ANPR ed è stata aggiornata la tabella Comuni pubblicata sul Portale.
