### ISSUE TITLE
ANPR Archivio comuni - Comune di Tavazzano

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2742]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 7 giugno 2021, segnalo un errore per il comune di Tavazzano.

    23078,"1861-03-17","1869-04-01","15958","L068","TAVAZZANO","TAVAZZANO","","",15,"015","03","","C","MI","I","2021-05-13",""

Manca lo zero iniziale nel codice Istat (015958).

Grazie.

**Comment by ncapozzi** [comment]
Il file è stato corretto e pubblicato.
Grazie per la segnalazione.
N. Capozzi
