### ISSUE TITLE
ANPR Archivio comuni - Comuni soppressi mancanti

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2744]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 7 giugno 2021, segnalo una discrepanza con l'[Elenco comuni soppressi](https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-soppressi.zip) (file compresso) riportato da sito ISTAT.

Nel file ISTAT risultano 492 comuni non presenti nel file ANPR. [File CSV con codici Istat mancanti in ANPR](https://github.com/italia/anpr/files/6840129/codici.Istat.mancanti.ANPR.csv).
Prime righe del file allegato:

    "Codice Comune","Denominazione Comune"
    "001805","Baratonia"
    "001816","Cavoretto"
    "001832","Luserna"
    "001855","Rodoretto"
    "001856","Rollières"

Grazie.

**Comment by m-casanova** [comment]
Il file contiene anche il codice Istat 015958 del comune di Tavazzano, che è [presente in ANPR con codice incompleto](https://github.com/italia/anpr/issues/2742).

**Comment by ncapozzi** [comment]
Buongiorno,
dal momento che al subentro in ANPR i Comuni trasmettono la situazione dell'anagrafe all'attualità e non lo storico è stato ritenuto di non inserire comuni cessati da molto tempo (es. prima del 1900). Avete qualche esigenza particolare per cui li volete inserire?
N. Capozzi

**Comment by m-casanova** [comment]
Le segnalazioni era motivate dalla descrizione su sito ANPR: «L’Archivio storico dei Comuni italiani è stato concordato con ISTAT e riporta per ogni comune tutte le variazioni subite nel tempo.» Pensavo che l'idea fosse quella di avere un file con licenza libera e più completo possibile anche per i dati storici (al momento contiene codici ISTAT che mi sembra non siano reperibili da altre fonti).

**Comment by ncapozzi** [comment]
Confermo che l’Archivio storico dei Comuni italiani utilizzato in ANPR, che è appunto un un file con licenza libera, ha come fonte ISTAT e riporta per ogni comune tutte le variazioni subite nel tempo finalizzate all'utilizzo in ANPR. Nei casi in cui i Comuni ci hanno segnalato l'esigenza di inserire un dato storico mancante ai fini anagrafici, questo è stato inserito.
