### ISSUE TITLE
[EN289] Problema con data Matrimonio

### ISSUE THREAD

**Issue by sgozzi67** [italia/anpr#2745]
Buongiorno, in ANPR mi restituisce l'errore 👍 

EN289
La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto

Il soggetto in questione ha contratto un secondo matrimonio all'estero prima della data del divorzio , il certificato di matrimonio è arrivato oggi a distanza di 6 anni quindi il reato di bigamia  è caduto in prescrizione, ma in ANPR il secondo matrimonio non ce lo lascia inserire.

Come possiamo ovviare a questo problema ? 
Grazie

**Comment by frmariani** [comment]
Nel sistema ANPR non è possibile inserire un secondo matrimonio prima della conclusione del precedente.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
