### ISSUE TITLE
[Service Down] Applicazione in produzione down

### ISSUE THREAD

**Issue by aleskandro** [italia/anpr#2746]
Buongiorno, non sono sicuro che vada segnalato in questo repository. 

Il servizio di produzione è down.

In particolare, il router (openshift?) è up ma non si riesce a raggiungere il web service (route non correttamente configurata o deployment down).

Nonostante il problema pare stare oltre il raggiungimento del router, ho provato:
- 'host header' con e senza il prefisso www 
- dispositivo mobile/desktop
- connessione da due operatori differenti

Segnalazione da **cittadino utente** della piattaforma.

Data del test: **20 Luglio 2021 9.03**

Ambiente di test: **produzione**.

**Comment by aleskandro** [comment]
![Screenshot_20210720-090302](https://user-images.githubusercontent.com/13661032/126278925-1aba9146-b5a9-4dc5-bc49-bd52cbaab1ea.jpg)

**Comment by mttfranci** [comment]
Buongiorno.
Grazie della segnalazione.
Ora il sito dovrebbe essere nuovamente disponibile.
Saluti
