### ISSUE TITLE
Ripristino posizione storica cittadino per provvedimento in autotutela

### ISSUE THREAD

**Issue by ACastelleone** [italia/anpr#2747]
Buongiorno,
avrei la necessità di provvedere ad annullare in autotutela la cancellazione per irreperibilità del soggetto ID19155214  avvenuta in data 27/12/2017, modificando la posizione storica del cittadino come residente e non irreperibile dal 27/12/2017 al 09/10/2018, data di ricomparsa nell'attuale comune di residenza.
Pertanto chiedo come si debba procedere ad effettuare tale ripristino e se inizialmente l'operazione debba essere effettuata dal comune di attuale iscrizione anagrafica oppure se la procedura debba iniziare da questo comune, quale comune di cancellazione per irreperibilità del soggetto.
Si ringrazia per la collaborazione, cordiali saluti

**Comment by frmariani** [comment]
Per riuscire ad annullare la cancellazione per irreperibilità che avete effettuato, dovrebbero essere annullate le molte operazioni effettuate sul cittadino dall'attuale comune di residenza; 
mi scriva in privato al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
stiamo provvedendo alla soluzione con un contatto diretto, pertanto la issue viene chiusa
