### ISSUE TITLE
COMUNE DI NOVELLA Richiesta contributo

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2748]
Buongiorno il comune di Novella con smart card sindaco non riesce ad entrare nella Richiesta di Contributo ANPR il sito segnala: Non è stato possibile reperire i dati del comune. 

Abbiamo controllato i dati sono corretti li abbiamo anche riconfermati e controllato i profili. 

Si prega di contattare il comune al nr. 0463 432113 int 2 Alla c.a. Sig.ra Lorenza Anselmi presente mattino 8:30 - 12:30
e lunedì e mercoledi anche pomeriggio dalle 14:30 alle 17:00 

Grazie 
Cordiali saluti
Cinzia Girelli
GPI SPA

Cell 3346216774

**Comment by mttfranci** [comment]
Salve, abbiamo effettuato alcune verifiche, potreste provare nuovamente?
Saluti

Assistenza ANPR

**Comment by CGIRELLI-HUB** [comment]
Matteo la ringrazio ma l'utente non è disponibile oggi pomeriggio, possiamo
riprovare domattina e le daremo notizia.

Grazie
Cordiali saluti
       Cinzia Girelli

*HR – HD DEPLOY E PIATTAFORMA*

C. +39 3346216774 | T. +39 0461 381 515 int. 7576
Gruppo GPI

I-38123 Trento | Via Ragazzi del ’99, 13 | T. +39 0461 381 515 | F. +39
0461 381 599
www.gpi.it

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi
allegati possono essere riservate e sono destinate esclusivamente al
suindicato destinatario. La diffusione, la distribuzione e/o la copiatura
del presente documento, dei suoi allegati o di sue parti da parte di
qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell’art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto
questo messaggio per errore, vi preghiamo di eliminarlo e di informarci
inviando un'e-mail a: ***@***.*** L’informativa privacy ai sensi dell’art.
13 del GDPR 679/2016 è disponibile sul sito www.gpi.it.
Rispetta l’ambiente. Non stampare questa mail se non è necessario.


Il giorno gio 22 lug 2021 alle ore 14:38 Matteo ***@***.***>
ha scritto:

**Comment by mttfranci** [comment]
Perfetto, ci risentiamo domattina.
Saluti

**Comment by CGIRELLI-HUB** [comment]
Buongiorno,

stamattina siamo riusciti ad inserire la richiesta di contributo per il comune di Novella dalla web app.


Vi ringrazio per aver risolto la problematica che bloccava tale inserimento e auguro una buona giornata


Cordialmente



dott.ssa Martina Schender
DIREZIONE PRODOTTI E SERVIZI
CUSTOMER SUPPORT ASCOT
C. +39 3450351662 | T. +39 040 9227228
Gruppo GPI

________________________________
Da: Cinzia Girelli ***@***.***>
Inviato: giovedì 22 luglio 2021 14.41
A: italia/anpr
Cc: Schender Martina
Oggetto: {Disarmed} Re: [italia/anpr] COMUNE DI NOVELLA Richiesta contributo (#2748)

Matteo la ringrazio ma l'utente non è disponibile oggi pomeriggio, possiamo riprovare domattina e le daremo notizia.

Grazie
Cordiali saluti

Cinzia Girelli

HR - HD DEPLOY E PIATTAFORMA

C. +39 3346216774 | T. +39 0461 381 515 int. 7576

Gruppo GPI

I-38123 Trento | Via Ragazzi del '99, 13 | T. +39 0461 381 515 | F. +39 0461 381 599
www.gpi.it<https://www.gpi.it/>

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi allegati possono essere riservate e sono destinate esclusivamente al suindicato destinatario. La diffusione, la distribuzione e/o la copiatura del presente documento, dei suoi allegati o di sue parti da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell'art. 616 c.p., che ai sensi del GDPR 679/2016. Se avete ricevuto questo messaggio per errore, vi preghiamo di eliminarlo e di informarci inviando un'e-mail a: ***@***.******@***.***>. L'informativa privacy ai sensi dell'art. 13 del GDPR 679/2016 è disponibile sul sito www.gpi.it<https://www.gpi.it/>.
Rispetta l'ambiente. Non stampare questa mail se non è necessario.


Il giorno gio 22 lug 2021 alle ore 14:38 Matteo ***@***.******@***.***>> ha scritto:

Salve, abbiamo effettuato alcune verifiche, potreste provare nuovamente?
Saluti

Assistenza ANPR

-

**Comment by mttfranci** [comment]
Grazie, buona giornata anche a voi.
Saluti

Assistenza ANPR
