### ISSUE TITLE
Piattaforma Accordi di Fruizione

### ISSUE THREAD

**Issue by GianluM67** [italia/anpr#2749]
Un Comune nostro cliente ci chiede se c’è la possibilità di candidarsi per la sperimentazione.
Grazie e saluti.
Stesei - Torino

**Comment by mttfranci** [comment]
Salve.
Al momento la piattaforma è stata aperta solo ad alcuni enti sperimentatori. Al termine del periodo di sperimentazione saranno resi noti i tempi per l’apertura a tutti gli altri enti/PA.
Saluti

Assistenza ANPR
