### ISSUE TITLE
Aggiornamento AnagAire

### ISSUE THREAD

**Issue by gcarbonin** [italia/anpr#275]
E' disponibile in ambiente di test comuni (Home --> strumenti di supporto) una nuova versione di AnagAire che consente l'acquisizione dei dati relativi alle unioni civili; questa versione, inoltre, puo' essere utilizzata sia per il subentro che per l'aggiornamento dell'AIRE centrale da parte dei comuni non subentrati.
In assenza di segnalazioni, sara' pubblicata anche nel sito del Ministero dell'Interno (area privata) entro il prossimo 12 settembre.

**Comment by Eduardo1977** [comment]
Buongiorno,
dopo aver lanciato l'aggiornamento 6.0.3 sul PC dell'ufficio anagrafe di Bistagno (AL), non riusciamo più ad accedere con le credenziali da operatore, mentre quelle di amministratore funzionano. Potremmo avere assistenza gentilmente?

Eduardo Gira

**Comment by gcarbonin** [comment]
Accedere a cosa? Web WS o AnagAire?

**Comment by Eduardo1977** [comment]
AnagAIRE

**Comment by gcarbonin** [comment]
La contatterà una mia collega.

**Comment by Eduardo1977** [comment]
Grazie per il supporto. Dopo l'installazione dell'aggiornamento AnagAire 6.0.3 (scaricato direttamente dall'ambiente di Test) era sufficiente effettuare il RESET PASSWORD da "Admin"

**Comment by Eduardo1977** [comment]
Dovrei fare un nuovo invio APR/AIRE in ambiente di Test. Ho appena generato il file AIRE con la nuova versione AnagAire 6.0.3. Però il nome assegnato al file è "006017_SUBAIRE_2.gz". E' normale che abbia applicato il progressivo? (Mi sarei aspettato "006017_SUBAIRE_1.gz" )
Lo invio lo stesso così com'è?
Grazie

**Comment by gcarbonin** [comment]
e' normale (se si mantiene lo stesso anagaire.mdb) si può inviare
