### ISSUE TITLE
Problema rettifiche dati

### ISSUE THREAD

**Issue by MarialuisaL** [italia/anpr#2750]
Comune Brienza Produzione

L'individuo con idAnpr 155317266 è stato iscritto con una data di decorrenza un motivo errato. 
Il Comune ha effettuato una Rettifica dati id Operazione 587403393 modificano il motivo di iscrizione - Esito OK
Nel successivo tentativo di rettificare la data di iscrizione si riceve l'errore che esiste un'operazione successiva (la rettifica di cui prima) :
1 Errore Anpr Cod: EN475 - Sono presenti modifiche con data decorrenza successiva al subentro, non e' possibile eseguire la rettifica delle date 
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-21 09:54:22 , idOperazioneANPR 588102923

Anche volendo rettificare la data di decorrenza della residenza si ottiene errore che indica che va rettificata prima la data di iscrizione. 
L'Ente ha necessità e l'urgenza di sistemare i dati del cittadino e rifiuta la possibilità di cancellarlo. 

E' possibile escludere il controllo che blocca una seconda rettifica se inviata quella per motivo iscrizione e provenienza ?
O è possibile per l'ente richiedere uno script sui dati dell'individuo?

Grazie

**Comment by frmariani** [comment]
la rettifica della data di iscrizione è possibile soltanto per cittadini aggiunti in ANPR con il subentro; il suo cittadino è stato aggiunto in ANPR con un'operazione di iscrizione per altri motivi pertanto l'operazione di rettifica della data di iscrizione non è possibile.
Avreste dovuto annullare l'intera operazione e rieseguirla correttamente.
Adesso proceda annullando l'operazione di rettifica come se fosse un'operazione di mutazione tutti i dati e poi annulli l'iscrizione per altri motivi.

**Comment by frmariani** [comment]
le operazioni suggerite risultano effettuate, pertanto la issue viene chiusa.
