### ISSUE TITLE
Modifica dimora abituale - errore privilegi

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2751]
COMUNE DI CAPONAGO

Varisco M.Giuseppina

Buongiorno
durante una variazione di dimora abituale compare l'errore :

La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione  sul soggetto/famiglia

di seguito i riferimento dell'operazione 

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-21 15:13:43 , mittente 108052 , idOperazioneComune 20210721151220

Potete indicarci quale anomalia si verifica e come risolvere il rpoblema ?

In attesa di gentile riscontro porgiamo distinti saluti

**Comment by mttfranci** [comment]
Salve, 
sembrerebbe che abbiate invocato un tipo mutazione 02 (residenza).
Mentre la dimora abituale dovea essere un tipo mutazione 03 (vedi tabella 047, https://www.anpr.interno.it/wp-content/uploads/2020/06/tabella_47_tipo_mutazione_residenza_05022018.xlsx)

```
    <datiControllo>
        <tipoMutazione>02</tipoMutazione>
        <tipoScheda>1</tipoScheda>
        <listaControlli>
            <controllo>
                <codice>FO</codice>
                <valore>S</valore>
            </controllo>
        </listaControlli>
    </datiControllo>
```

L'errore sui privilegi mancanti è dovuto al fatto che, per tipo scheda 1 = famiglia esistente è necessario indicare una famiglia, la qual cosa non è stata fatta : 

```
    <generalitaSchedaFamiglia>
        <famigliaAire>N</famigliaAire>
        <tipoScheda>3</tipoScheda>
    </generalitaSchedaFamiglia>
```

Il sistema restituisce il diagnostico sui privilegi anche se non riesce a trovare la famiglia per evitare di dare l'informazione che la famiglia non esiste.

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by GabriellaBallabio** [comment]
Buongiorno
mi scusi ma non sono stata chiara... il soggetto per il quale si è presentata l'anomalia , ha cambiato via di residenza nell'ambito del comune, trasferendosi in una famiglia esistente.
Come devo considerare questa variazione ? come modifica di dimora abituale o cambio di residenza ?

**Comment by mttfranci** [comment]
Si tratta comunque di un Cambio di residenza, per il quale però è necessario indicare l'identificativo famiglia di arriva, dato che non è presente nella richiesta che abbiamo trovato.
Saluti

Assistenza ANPR
