### ISSUE TITLE
ANPR Archivio comuni - Periodi temporali mancanti per alcuni comuni

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2752]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 7 giugno 2021, segnalo la mancanza di righe per intervalli temporali di alcuni comuni.

Nel 1861 erano presenti 7.720 comuni come da [dato Istat](http://seriestoriche.istat.it/fileadmin/documenti/Tavola_2.23.xls), ma nel file ANPR sono presenti solo 5.263 righe con inizio dal 1861-03-17.

Tale differenza risulta solo parzialmente imputabile ai comuni soppressi mancanti [indicati in una precedente segnalazione](https://github.com/italia/anpr/issues/2744). Infatti confrontando i comuni in ordine alfabetico con [una pubblicazione ministeriale del 1861](https://archive.org/details/statistica-amministrativa-1861-2/page/237/mode/2up) si nota che i primi casi mancanti sono:
* Abbadia in provincia di Como (successiva denominazione Abbadia sopra Adda, presente nel file dal 1863-02-23 con codice Istat 013801);
* Abbadia in provincia di Torino (successiva denominazione Abbadia Alpina, presente nel file dal 1864-04-01 con codice Istat 001801);
* Abbadia San Salvatore in provincia di Siena (presente nel file solo dal 1867-07-22 con codice Istat 052001).

Altro esempio evidente è dato dal comune di Milano, che nel file ANPR è presente solo dal 1873-06-23.

Grazie.

**Comment by ncapozzi** [comment]
Buongiorno,
come risposto anche nella #2744, dal momento che al subentro in ANPR i Comuni trasmettono la situazione dell'anagrafe all'attualità e non lo storico è stato ritenuto di non inserire comuni cessati da molto tempo (es. prima del 1900). Avete qualche esigenza particolare per cui li volete inserire?

**Comment by m-casanova** [comment]
Ho lasciato indicazione unica in #2744
