### ISSUE TITLE
Problema su cambio responsabile di convivenza

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2753]
Comune di Modena - Ambiente di produzione

Buongiorno,
stiamo tentando di modificare da webapp il responsabile di una delle nostre convivenze; il nuovo responsabile è residente in altro comune subentrato  e veniamo bloccati con l' errore:

"Soggetto non di competenza del comune"

ma fino ad Aprile 2021 abbiamo inserito senza problemi tutori/responsabili di convivenza non residenti. E' stato aggiunto qualche controllo? Come possiamo bypassare il problema?

Grazie, saluti
Sonia Fiorini

**Comment by mttfranci** [comment]
Buongiorno, riuscite a farci avere l'id operazione ANPR in cui ottenete l'errore.

**Comment by sfmodena** [comment]
Buongiorno,
non ci viene restituito nessun ID operazione, l' errore compare non appena si dà  la conferma sulla form "Dati dell' operazione".

Sonia Fiorini

**Comment by mttfranci** [comment]
Avreste almeno l'identificativo della convivenza?
Grazie in anticipo.

**Comment by sfmodena** [comment]
Ci scusiamo, ora l' operazione da webapp è andata a buon fine. Probabilmente il tentativo precedente era stato eseguito selezionando un dato sbagliato, errore indotto da un malfunzionamento del nostro applicativo.
Chiudo la issue, grazie comunque per l' attenzione.

**Comment by mttfranci** [comment]
Meglio così.
Saluti

Assistenza ANPR
