### ISSUE TITLE
ANPR Archivio comuni - Possibili errori

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2754]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 22 luglio 2021, segnalo apparenti errori.

Per una riga del comune di Finale Marina sono indicati ID_PROVINCIA 99 e IDPROVINCIAISTAT 099 da correggere rispettivamente in 9 e 009

    23042,"1927-01-12","1927-01-12","009814","D601","FINALE MARINA","FINALE MARINA","","",99,"099","07","","C","SV","","2019-07-22",""

Per una riga del comune di Montesano al Piano è indicato ID_PROVINCIA 18 e IDPROVINCIAISTAT 018 ma in provincia di Milano; apparentemente è da correggere la provincia in PV

    23074,"1863-03-30","1871-05-31","018848","F624","MONTESANO AL PIANO","MONTESANO AL PIANO","","",18,"018","03","","C","MI","I","2020-07-01",""

Grazie.

**Comment by ncapozzi** [comment]
Buongiorno
il file corretto  è  stato pubblicato il 30/07/2021.
Grazie per la segnalazione
