### ISSUE TITLE
[4005] scarico notifiche N010 sempre posticipato 

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2755]
Buongiorno,
per il comune 041010 in pre-subentro scaricando l'id operazione ANPR 024004160 l'orario viene sempre posticipato di un ora e non si riescono a scaricare le notifiche.

stesso problema di #2352 
grazie 
Federico

**Comment by mttfranci** [comment]
Salve, adesso l'elaborazione dovrebbe essere terminata.
Saluti

Assistenza ANPR
