### ISSUE TITLE
Soggetto Eliminato senza comune di nascita

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2756]
COMUNE DI CINISELLO BALSAMO PRODUZIONE

Il comone di Cinisello sta cercardo di iscrivere per altri motivi una persona ELIMINATA dal comune di CASALPUSTERLENGO,
Il soggetto in questione ha il campo del comune di nascita nulla e per questo motivo non riusciamo ad iscriverlo.
All'invio riporta il seguente errore: 

```
1 Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 42468812 non presente o dati anagrafici incongruenti - Cognome: HEGAZI Nome: MAMDOUH CF: XXXXXXXX-
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-07-29 10:04:00 , idOperazioneANPR 595350805 - Cognome: HEGAZI Nome: MAMDOUH CF: XXXXXXXXXX -
```

Abbiamo provato a contatttare il comune di attuale compotenza del persona da iscrivere per chiederli l'annullamento, bonifica del dato e succesiva cancellazione, ma ci hanno riferito che la loro Software house preferisce non farlo.

Il comune di nascita corretto è: EGITTO.

**Comment by frmariani** [comment]
Abbiamo inserito d'ufficio il comune di nascita, riprovi l'operazione per favore.

**Comment by jonnyfx95** [comment]
Grazie mille, l'operazione è andata a buon fine.

Saluti, 

Jonathan
