### ISSUE TITLE
Comuni subentrati

### ISSUE THREAD

**Issue by fcastellani81** [italia/anpr#2757]
Buongiorno,
solo una conferma: il file dei Comuni Subentrati presente al link https://www.anpr.interno.it/wp-content/uploads/Tabella_45-Comuni-subentrati.xlsx è aggiornato alla data del 08/07/2021. 
Aprendo il file, invece, risultano comuni subentrati fino alla data di ieri, 28/07/2021.
Probabilmente dovrà essere aggiornata, da parte vostra, la data di aggiornamento, giusto?

Grazie
Cordiali Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
la data è stata aggiornata. Grazie per la segnalazione
