### ISSUE TITLE
ANPR Archivio comuni - encoding

### ISSUE THREAD

**Issue by Tiz68** [italia/anpr#2758]
Buongiorno,
con la ristrutturazione del sito e la modifica del permalink dell'archivio dei comuni, come è stato segnalato in #2617, è stato modificato anche l'encoding del file.

L'encoding del file in questione però non è un semplice UTF8, ma UTF8-BOM.

Dato che  questo tipo di encoding è noto per essere poco gradito all'ambiente Java, posso comunque considerarlo come l'encoding definitivo che verrà usato anche nei prossimi aggiornamenti dell'archivio dei comuni?

Grazie,
Tiziano

**Comment by ncapozzi** [comment]
Buongiorno,
per precisione rispetto alla  #2617 finora abbiamo sempre pubblicato il file UTF8 – BOM e resterà questo salvo eventuali future richieste di modifica.
