### ISSUE TITLE
Certificati on-line - Esenzione Bollo - art. 39 DL 77 del 31.05.2021  

### ISSUE THREAD

**Issue by sburacchi** [italia/anpr#2759]
Buongiorno,
avremmo bisogno di sapere, se possibile, quando sarà applicato ufficialmente in fase operativa da ANPR quanto in oggetto, se già non lo fosse, e con quali caratteristiche tecniche nel produrre il file xml di richiesta.
Cordiali saluti.

**Comment by FilippoPapi** [comment]
buongiorno
siamo in attesa della emanazione di un decreto da parte del Ministero dell'Interno
Cordiali saluti
