### ISSUE TITLE
Certificato di residenza storico, cittadino immigrato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#276]
Buongiorno
cittadino id anpr 5389740 (ambiente test)
l'ho appena iscritto, proveniente da altro comune ANPR.

cerco di emettere un certificato di residenza storico da ANPR alla data 1/8/17 (quando era residente ANPR nell'altro comune).
Ottengo il seguente errore che non riesco a capire:

_La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti (Codice: EN087)_

**Comment by gcarbonin** [comment]
Stiamo verificando.

**Comment by gcarbonin** [comment]
Puo' riprovare e darci un riscontro?

**Comment by MarcoMigliori** [comment]
Risolto, grazie.
