### ISSUE TITLE
Rientro AIRE in Comune differente dal Comune di Iscrizione AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2760]
COMUNE DI CAPONAGO
Varsico M.Giuseppina

Buongiorno
di seguito i riferimneti dell'operazione che non mi consente di effettuare un rientro AIRe di un cittadino iscritto all'AIRE di un altro comune subentrato.

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-08-03 13:56:15 , idOperazioneANPR 600000428

Staimo cercandoi di inviare una richiesta di iscrizione nel nostro comune.... è un erroe ? dobbiamo inviare una richiesta di Mutazione Residenza ?

Si resta in attesa di gentile riscontro.

Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
per il rientro in Italia di un cittadino in un comune diverso da quello di iscrizione AIRE è necessario trasmettere una mutazione dati 5001 con tipo = 4 residenza scheda

**Comment by GabriellaBallabio** [comment]
Abbiamo provato ad inviare evento 5001 con tipo mutazione = 4

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-08-04 14:54:25 , idOperazioneANPR 601224021

ora gli errorei sono differenti 


EF008 Intestatario della scheda famiglia/convivenza assente

EF044 I soggetti devono appartenere alla stessa famiglia dichiarata

Qual'è il problema ?

**Comment by ncapozzi** [comment]
Il cittadino rientra in Italia in una famiglia già residente o per proprio conto?

**Comment by GabriellaBallabio** [comment]
Il cittadino rientra in una famiglia già residente.

**Comment by ncapozzi** [comment]
Allora dovete utilizzare il WS 5005 con rientro in famiglia esistente
