### ISSUE TITLE
Metodo 2001 Cancellazione per decesso

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2761]
Comune di Caponago
Varisco M.Giusppina

Staiamo cercando di inviare una variazione di decesso per la quale ci restitutisce il seguente errore :

La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 07-07-2021

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-08-03 10:58:14 , idOperazioneANPR 599689425

Cosa doabbiamo fare ?

**Comment by frmariani** [comment]
Come avvisa il controllo, ci sono delle operazioni sul soggetto con data di decorrenza 07/07/2021, pertanto la data di decorrenza dell'operazione non può essere antecedente.
La data evento morte invece, potrà certamente essere quella corretta.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
