### ISSUE TITLE
5008 oggetto Matrimonio che non ha effetto sul cittadino

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#2762]
Cardano al Campo - Produzione

Al cittadino con id anpr 86202878 , effettuando un 5008 per variare il coniuge e i dati del matrimonio, atto compreso, nonostante l'esito positivo dell'invio dell'operazione nella response, consultandolo, mantiene i vecchi dati errati. 

Vedasi operazione con id 602199396 (L'ente ne ha registrate diverse, ma il risultato non cambia)

Si è provato con l'eliminazione dati dell'oggetto matrimonio, ma l'operazione di revoca è possibile solo a valle del subentro. 

Come possiamo sistemare i dati del cittadino?

**Comment by frmariani** [comment]
In fase di iscrizione del cittadino avete inviato l'informazione dei dati del matrimonio (anno evento 1985); successivamente, con l'operazione idanpr 221427882, avete inviato l'informazione della vedovanza del cittadino.

Con l'operazione idanpr 503623064, avete inviato l'informazione di un nuovo matrimonio per il cittadino (anno evento 2016): è questa l'informazione non corretta? poteva essere semplicemente annullata solo quella operazione;
adesso, per annullare l'operazione idanpr 503623064, dovrete annullare tutte le operazioni successive effettuate sul matrimonio.
A titolo informativo, le comunico che non possono essere variati contemporaneamente sia i dati del coniuge che quelli del matrimonio (data evento): in questo caso devono essere effettuate due operazioni diverse, una per modificare il coniuge e la successiva per modificare la data del matrimonio.

Per questa tipologia di problematiche può contattare l'assistenza ANPR al numero 800863116

**Comment by mrabuano** [comment]
il Comune ha sistemato i dati del cittadino, grazie

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
5008 oggetto Matrimonio che non ha effetto sul cittadino (#2762)" inviata
il 13/08/2021 12:54:47.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
5008 oggetto Matrimonio che non ha effetto sul cittadino (#2762)" inviata
il 13/08/2021 12:54:46.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
