### ISSUE TITLE
Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 101318475 non presente o dati anagrafici incongruent - Comune di nascita nullo 

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#2764]
COMUNE DI ANCONA PRODUZIONE

Si sta cercando di iscrivere il seguente soggetto per altri motivo con provenienza da ROMA.
Il soggetto attualemte è cancellato a seguito di irreperibilità.

All'invio della pratica viene riportato il seguente errore: 

`
1 Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 101318475 non presente o dati anagrafici incongruenti - Cognome: XXXXXXXX Nome: XXXXX CF: XXXXXXX-
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-08-06 14:43:25 , idOperazioneANPR 603444573 - Cognome: XXXXX Nome: XXXXXX CF: XXXXXXXX-
`

Il comune di nascita risulta essere nullo, mentre nel luogo eccezionale viene riportato BANGLADESH nell'oggetto generalità.
E' possibile inserire d'ufficio il luogo di nascita BANGLADESH e cencelllare quello eccezionale?

**Comment by ncapozzi** [comment]
Buongiorno,
stiamo provando a contattare il Municipio competente del Comune di Roma.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 101318475 non presente o dati
anagrafici incongruent - Comune di nascita nullo  (#2764)" inviata il
09/08/2021 14:57:41.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by ncapozzi** [comment]
Potete indicare per favore un recapito telefonico al quale possiamo contattarvi? Grazie

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 101318475 non presente o dati
anagrafici incongruent - Comune di nascita nullo  (#2764)" inviata il
10/08/2021 14:43:53.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by ncapozzi** [comment]
Buongiorno,
sono stati trasmessi per email i recapiti del Municipio competente.
Vi preghiamo, per richieste ulteriori specifiche di assistenza di rivolgervi al nostro numero verde 800863116.
Grazie

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Errore Anpr Cod: EN185 - idSchedaSoggettoANPR 101318475 non presente o dati
anagrafici incongruent - Comune di nascita nullo  (#2764)" inviata il
11/08/2021 10:24:53.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
