### ISSUE TITLE
Nota Web Service P000 - gestione richieste dei cittadini da Portale ANPR

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#2765]
Buongiorno a tutti.

Dal 24 Giugno 2021 è stato reso disponibile per la maggior parte dei comuni il servizi di "Richiesta rettifica" per i cittadini nell'area autentica del [Portale ANPR](https://www.anpr.interno.it/).

E' in corso di implementazione un nuova famiglia di servizi, denominata P000, che presumibilmente sarà disponibile entro il mese di ottobre.

Ecco il contratto di servizio [aggiornamento 20/09/2021] : 
[wsdlP000-5.14.0.zip](https://github.com/italia/anpr/files/7194207/wsdlP000-5.14.0.zip)

E una breve nota per permettere di cominciare a valutare l'integrazione con i proprio sistemi da parte dei comuni : 
[Nota_gestione_richieste_2021-09-20_003.docx](https://github.com/italia/anpr/files/7194343/Nota_gestione_richieste_2021-09-20_003.docx)  [aggiornamento 20/09/2021]

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Aggiornati [wsdlP000-5.14.0.zip](https://github.com/italia/anpr/files/7194207/wsdlP000-5.14.0.zip)  e [Nota_gestione_richieste_2021-09-20_003.docx](https://github.com/italia/anpr/files/7194343/Nota_gestione_richieste_2021-09-20_003.docx)

**Comment by mttfranci** [comment]
Buonasera, i servizi P000 sono disponibili in ambiente di test comuni all'endpoint : 

https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000

Le tabelle di decodifica aggiuntive per ora vengono anticipare qui e verranno pubblicate sul portale pubblico solo dopo il rilascio in produzione : 

[Tabelle di decodifica](https://github.com/italia/anpr/files/7226180/tabelle_decodifica.zip)

Le stesse tabelle sono disponibili anche tramite il servizio 7001 : 

Tabelle per tutte le richieste : 
51 - formato allegato
52 - tipo allegato
53 - stato richiesta
54 - tipo richiesta
55 - tipo contatto

Tabelle specifiche della rettifica dati  : 
56 - sezione dati agrafici da rettificare
57 - dato anagrafico da rettificare

Ecco anche alcune [richieste di esempio P001, P002, P003](https://github.com/italia/anpr/files/7226209/P000_sample.zip).

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

**Comment by apaolacci** [comment]
Buongiorno,
vista anche la nota #2945 si rende noto che sono disponibili in ambiente di **produzione** i servizi della famiglia P000, 
di seguito l'endpoint:

**https://ws.anpr.interno.it/anpr-wsP000/AnprServiceP000**

Saluti
