### ISSUE TITLE
Smart card in lavorazione da febbraio

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2766]
Buongiorno,
per la operatrice CRSSRN76S69C632E del Comune di Ravenna la smart card ANPR risulta  “IN LAVORAZIONE” da febbraio. Le altre smart richieste nella stessa data, invece, sono già arrivate. E' possibile verificare?

Grazie,
cordiali saluti.
tel. di riferimento 0544 485513

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Smart card in lavorazione da febbraio (#2766)" inviata il 09/08/2021
08:44:10.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by Leonforte** [comment]
Buongiorno, abbiamo provveduto ad una nuova richiesta di emissione della carta che dovrebbe essere disponibile presso la Prefettura di competenza entro una decina di giorni, buon lavoro, saluti
