### ISSUE TITLE
SUGGERIMENTO MODIFICA CERTIFICATI DI STATO CIVILE

### ISSUE THREAD

**Issue by Svitoromano** [italia/anpr#2767]
Buongiorno,
la presente per segnalare che in ANPR i certificati di "stato civile" e "stato libero" ed i cumulativi in cui sono inclusi, in caso di soggetti celibi-nubili riportano entrambi la dicitura "di stato libero".
Ho effettuato tentativi su 3 diversi comuni, con due diversi applicativi (halley e pa digitale), sia generando i certificati tramite il nostro software sia tramite il portale ANPR.
La dicitura è giuridicamente corretta nel caso di "certificato di stato libero" mentre il "certificato di stato civile" dovrebbe riportare diciture quali "celibe", "nubile", "divorziato", "vedovo" ecc.
La distinzione non è di poca importanza in quanto per celebrare un matrimonio religioso i parroci vogliono sapere lo stato civile esatto, e non il generico "libero".
Cordiali saluti

**Comment by mttfranci** [comment]
Salve, in generale le eventuali proposte di modifica ai modelli dei certificati vanno concordate con il Ministero.

Comunque nel caso specifico il certificato di "stato civile" riporta la dicitura "di stato libero" da sola compare solo in caso il soggetto sia celibe/nubile.

Se l'origine dello stato libero è diversa compaiono i dettaglio, ad esempio in caso di divorzio : 

Risulta di stato libero per divorzio da XXXXXXXX il YYYYYYYYY.

![image](https://user-images.githubusercontent.com/29305782/128704907-0082ce02-7531-467f-a528-9529a3d79973.png)

Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
SUGGERIMENTO MODIFICA CERTIFICATI DI STATO CIVILE (#2767)" inviata il
09/08/2021 14:20:07.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
SUGGERIMENTO MODIFICA CERTIFICATI DI STATO CIVILE (#2767)" inviata il
09/08/2021 12:38:40.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
SUGGERIMENTO MODIFICA CERTIFICATI DI STATO CIVILE (#2767)" inviata il
11/08/2021 08:17:59.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
