### ISSUE TITLE
Da capo convivenza a intestario scheda

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2769]
Buongiorno,
stiamo procedendo a una immigrazione dal Comune di Lugo a quello di Ravenna. Il cittadino a Lugo era capo convivenza da noi deve diventare intestatario scheda. Ci restituisce errore bloccante per "identificativo scheda famiglia/convivenza attribuito dal comune non trovato o scheda famiglia archiviata", idOperazioneANPR 598581455.

Grazie per l'attenzione,
cordiali saluti
Katia Vacchi

**Comment by mttfranci** [comment]
Buongiorno, con l'operazione 598581455 state provando a effettuare un cambio residenza intera famiglia. Ma in effetti la famiglia indicata non esiste in ANPR, quindi il diagnostico è corretto.
Inoltre anche se esistesse, non si può mutare la residenza di una convivenza.
Forse dovreste fare un normale cambio residenza individuale (5005).
Saluti

```
      <famigliaConvivenza>
        <idFamigliaConvivenzaComune>
          <idFamigliaConvivenzaComuneIstat>039014</idFamigliaConvivenzaComuneIstat>
          <idFamigliaConvivenza>195937</idFamigliaConvivenza>
        </idFamigliaConvivenzaComune>
        <famigliaAire>N</famigliaAire>
        <dataOrigineFamigliaConvivenza>2021-07-22</dataOrigineFamigliaConvivenza>
        <presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante>
        <tipoScheda>3</tipoScheda>
      </famigliaConvivenza>
```

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Da capo convivenza a intestario scheda (#2769)" inviata il 10/08/2021
09:12:49.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr] Da
capo convivenza a intestario scheda (#2769)" inviata il 10/08/2021 08:03:59
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Da capo convivenza a intestario scheda (#2769)" inviata il 11/08/2021
08:17:26.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
