### ISSUE TITLE
Certificato storico richiesto mentre c'è procedimento in corso

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#277]
Buongiorno
cittadino id anpr 6546211 (ambiente test)

inizio procedimento di residenza oggi, proveniente da altro comune ANPR.
il cittadino mi richiede certificato storico di residenza al 1.8.17
se lo richiedo a ANPR, ottengo:

_Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato (Codice: EN181)_

Tuttavia il procedimento in corso non varia i dati da certificare.

**Comment by gcarbonin** [comment]
Un procedimento aperto blocca l'emissione dei certificati che possono essere emessi comunque utilizzando il campo forzacertificazione.

**Comment by MarcoMigliori** [comment]
Riapro questa segnalazione, perchè si tratta dello stesso caso. Se chiedo oggi il certificato storico di residenza al 1° agosto, e indico di forzare la certificazione, l'errore che ottengo è:
_Il certificato non puo' essere emesso in quanto la data di riferimento risulta precedente a quella di iscrizione APR del soggetto (Codice: EN419)_

Tuttavia se vado in consultazione e indico quella data, sembra residente alla data:
_Identificativo scheda attribuito da ANPR: 6546211
Data di riferimento scheda: 01/08/2017
Residenza
Data decorrenza residenza: 13/12/2016 
Indirizzo in Italia
Provincia: GR  Comune: PITIGLIANO_

Non capisco però dalla consultazione la data di subentro del comune.

**Comment by gcarbonin** [comment]
Il comune di residenza  è subentrato il 3 agosto quindi non si può richiedere uno storico al 1-8

**Comment by MarcoMigliori** [comment]
La residenza l'ho cambiata in data 30.8.2017
Se chiedo il certificato storico di residenza anche in data 28.8.2017, quindi successivo alla data di subentro che mi ha indicato qui sopra, ottengo sempre
_Il certificato non puo' essere emesso in quanto la data di riferimento risulta precedente a quella di iscrizione APR del soggetto (Codice: EN419)_

**Comment by gcarbonin** [comment]
Verifichiamo e facciamo sapere

**Comment by rnapoli1983** [comment]
Ci stiamo lavorando.

**Comment by rnapoli1983** [comment]
Potete riprovare.

**Comment by MarcoMigliori** [comment]
Innanzitutto segnalo che l'argomento risulta CLOSED, vi chiedo gentilmente di riaprirlo su Github, anche se le notifiche le ricevete comunque.

Ho rifatto i test, per capire i risultati ricordo che la Carbonin afferma come il comune originale sia subentrato il 3 agosto, mentre io ho fatto il cambio di residenza in data 30 agosto

Certificato storico residenza chiesto 
1. alla data del 2 agosto, certifica residenza in PITIGLIANO (GR) dal 20/01/2015  - ERRORE -
2. alla data del 29 agosto, certifica residenza in PITIGLIANO (GR) dal 20/01/2015  - OK-
3. alla data del 31 agosto, certifica residenza in entrambi i comuni con la data di inizio, senza indicare per Pitigliano la data di fine  - ERRORE -

L'ultima prova la ritengo un errore perchè il certificato storico è richiesto a una data specifica, quindi non è chiaro riportare lo storico delle residenze pregresse. Inoltre da una precedente risposta della Carbonin, ho inteso che per ora un certificato storico che elenchi tutte le residenze che il cittadino ha avuto nel tempo in ANPR, non è previsto.

**Comment by rnapoli1983** [comment]
Sulla base delle sue segnalazioni, abbiamo effettuato alcune modifiche: alcune risposte, pertanto,  sono superate.

Per comprendere quanto presente nei certificati prodotti ieri, occorre considerare la situazione attuale per il soggetto in esame:

- la prima scheda ANPR è  del comune di PITIGLIANO; la data di prima iscrizione nel comune è pari a 20-01-2015;
- il comune di Pitigliano ha effettuato il subentro in data 29-06-2017;
- in data 30 agosto, il soggetto è stato trasferito al comune di Potenza Picena; la data di prima iscrizione in questo comune è quindi 30-8-2017 e coincide con la la data di decorrenza della nuova residenza.

Tanto premesso:

1)	Chiedendo un  certificato con data di riferimento 02-08-2017, si ottengono i dati del comune di Pitigliano; lo storico di una persona, infatti, decorre dal suo primo ingresso in ANPR;  se la data di riferimento fosse 28-6-2017, ANPR restituirebbe un errore;
2)	Chiedendo un  certificato con data di riferimento 29-08-2017, si ottengono gli stessi dati del punto precedente; 
3)	Chiedendo  il certificato con data di riferimento 31-08-2017, si ottengono i dati di Pitigliano e quelli di Potenza Picena in quanto abbiamo interpretato l’indicazione della data di riferimento non come” la fotografia del soggetto a quella data” ma come “i dati delle residenze del soggetto fino a quella data”.

Se la nostra assunzione non è corretta, possiamo adeguare lo storico di residenza. Sentiamo anche le opinioni degli altri.  Se nello storico di residenza si riporta soltanto la fotografia alla data, quando e come si vedono tutte le residenze di un soggetto?

**Comment by MarcoMigliori** [comment]
Non ho riprovato, ovviamente se il subentro del comune originale è avvenuto il 29 giugno, cambiano le condizioni. A questo proposito vi invito a riflettere sulla opportunità o meno di rendere visibile questo dato, che permette di capire certi risultati.

Dal punto di vista normativo, fatti salvi alcuni divieti, la certificazione è potenzialmente totale:

_Art.33
1. Fatti salvi i divieti di comunicazione di dati, stabiliti da speciali disposizioni di legge, e quanto previsto dall'articolo 35, l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, **nonche' ogni altra informazione ivi contenuta**.

Art.35 
4. Previa motivata richiesta, l'ufficiale di anagrafe rilascia certificati attestanti situazioni anagrafiche pregresse._


Il vostro attuale certificato di residenza riporta la scritta
  CERTIFICA CHE ... ALLA DATA DEL ....
A mio parere deve quindi riportare la fotografia alla data. Anche per comprensione di chi riceve il certificato e lo deve leggere.

Per quanto riguarda la domanda finale, mi rifaccio a una risposta della Carbonin #81, da cui io ho dedotto forse erroneamente, che i certificati previsti sono quelli visibili ora, e non è quindi previsto un ulteriore certificato di tutte le residenze avute dal cittadino nel tempo. 
Questo tipo di certificato noi lo produciamo come credo tutti o quasi gli altri fornitori, ed è richiesto con relativa frequenza.  Ed è normalmente un certificato diverso, dalla "fotografia" ad una certa data. Quindi sempre a mio parere, un certificato in più.

Sono assolutamente d'accordo sull'esigenza di ampliare - e mi riferisco a un WS aggiuntivo - la visibilità delle informazioni, in modo tale da avere la situazione storica ANPR complessiva in termini di iscrizione/cancellazione/residenza. Del cittadino, perchè di questo stiamo parlando ora. Poi esistono anche esigenze sulla famiglia, che complicano lo scenario, e che qui ho ignorato.

**Comment by gcarbonin** [comment]
Sintetizzo le richieste aggiuntive
1) rendere visibile la data di subentro del comune - occorre trovare come e dove metterlo 
2) aggiungere una tipologia di certificato - l'attuale formato va bene per dare tutte le residenze fino ad una certa data. Occorre trovargli un nome 
3) nuova interrogazione storica - identifichiamo i dati e poi lo mettiamo a piano

Provvediamo a modificare l'attuale per fornire la fotografia alla data.

Sulla famiglia è già prevista la produzione di tre certificati storici (issue 130)

**Comment by MarcoMigliori** [comment]
Per il punto 1 "rendere visibile la data di subentro del comune" preciso che l'esigenza che ho riscontrato dai test, è quella di capire da quando i dati sono stati forniti a ANPR, e quindi da quando comincia lo storico ANPR.
Siccome all'aumentare dei comuni, i cittadini cominceranno a cambiare residenza tra comuni ANPR, l'informazione che a mio parere è utile è quella della "data del subentro del cittadino in ANPR". Da qui in poi cambi di residenza e cancellazioni e eventuali nuove reiscrizioni, sono in vostro possesso. Mentre la pirma data sì ce l'avete, ma non è visibile.

**Comment by bfilipazzi** [comment]
La issue 130 presenta tre esempi forniti dal comune di Torino (trascuro il primo perché riconducibile al secondo di cui è un sotto caso), gli altri due certificano la famiglia ad una data e la famiglia con le vicende anagrafiche, cioè le variazioni della sua composizione.
Credo che si possano descrivere rispettivamente "Stato di famiglia alla data" e "Stato di famiglia storico" (o "Stato di famiglia storico con variazioni").

In modo parallelo si certifica storicamente la residenza della persona: con un certificato alla data e un altro che elenca la storia delle residenze; che chiamerei rispettivamente "Residenza alla data" e "Residenza storico" (o "Residenza storico con variazioni").

Il certificato storico di residenza (con variazioni) descrive l'iscrizione anagrafica con relativo indirizzo e successive variazioni dell'indirizzo, fino ad un'eventuale descrizione della cancellazione anagrafica. 
Prima dell'avvento di ANPR il certificato in questione poteva coprire soltanto le vicende relative al comune di rilascio e volendo disporre di informazioni su un periodo più esteso registrato in altri enti è necessario allegargli i certificati prodotti da quegli enti.
ANPR ha gli strumenti per fornire in un documento unico tutte le informazioni di cui dispone, anche se di pertinenza di più comuni; il Ministero ha la competenza per stabilire se e come in questo caso le informazioni vanno rappresentate.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
I certificati sono disponibili in ambiente di test comuni e pre-subentro
