### ISSUE TITLE
Codici territori non corrispondenti

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2770]
Alcuni codici dei territori [Tabella di decodifica 02 - Stati Esteri](https://www.anpr.interno.it/wp-content/uploads/2021/03/tabella_2_statiesteri.xlsx) non corrispondono a quelli presenti nell'[elenco ISTAT delle unità territoriali estere](https://www.istat.it/it/archivio/6747). Riporto in tabella le differenze riscontrate:

ID|DENOMINAZIONE|CODMIN (ANPR)|CODMIN (ISTAT)|CODISTAT (ANPR)|CODISTAT (ISTAT)
-|-|-|-|-|-
86|ISOLE COOK|702|702|702|909
205|CURACAO||620|620|966
206|GIBILTERRA||218|218|910
208|GROENLANDIA||520|520|934
209|GUERNSEY||274|274|940
213|ANGUILLA||502|502|917
214|ARUBA||603|603|926
216|ISOLA DI MAN||228|228|959
217|MONTSERRAT||528|528|964
218|ISOLE PITCAIRN||723|723|972
219|BERMUDA||508|508|908
220|ISOLE CAYMAN||511|511|911
221|NUOVA CALEDONIA||718|718|902
222|ISOLE FAER OER||213|213|924
223|ISOLE FALKLAND||610|610|958
224|ISOLE TURKS E CAICOS||537|537|992
225|ISOLE VERGINI BRITANNICHE||539|539|994
226|ISOLE WALLIS E FUTUNA||734|734|997
227|JERSEY||273|273|925
229|POLINESIA FRANCESE||724|724|920
230|SAINT BARTHELEMY||541|541|906
231|SAINT MARTIN||542|542|904
232|SAINT PIERRE E MIQUELON||535|535|980
233|SANT'ELENA||447|447|983
234|SINT MAARTEN||621|621|928
235|TERRITORI AUSTRALI ED ANTARTICI FRANCESI||806|806|988

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Codici territori non corrispondenti (#2770)" inviata il 10/08/2021 14:37:56
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by ncapozzi** [comment]
Buongiorno,
per gli stati esteri/territori non esiste ancora un archivio storico di riferimento univoco come avviene invece per i Comuni. Questo comporta per es. differenze nella codifica dei Territori dipendenti da uno stato sovrano, come da lei evidenziato, ovvero la mancanza di stati cessati (Jugoslavia, URSS, etc.) . La Tabella di decodifica 02 - Stati Esteri, alla quale dovete attenervi per le comunicazioni in ANPR, è quella già in uso nei sistemi INA-SAIA e AIRE.

**Comment by dedabob** [comment]
Buongiorno,
la issue era relativa ad un problema diverso: la tabella di decodifica 02 nella colonna "codici ISTAT" riporta codici diversi da quelli che ISTAT riporta per i medesimi territori.

**Comment by ncapozzi** [comment]
Buongiorno, il problema è stato chiaramente compreso. Il fatto che per gli stati esteri/territori non esiste ancora un archivio storico di riferimento univoco ha comportato nel tempo che la colonna codice ISTAT della tabella ANPR, che riporta nella maggior parte dei casi lo stesso cod. ISTAT, sia stata utilizzata per i TERRITORI anche per indicare codici diversi da quelli dell'ISTAT. In previsione di una unificazione delle tabelle le confermo che dovete attenervi alla  Tabella di decodifica 02 - Stati Esteri per le comunicazioni in ANPR,

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Codici territori non corrispondenti (#2770)" inviata il 11/08/2021 11:44:12
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Codici territori non corrispondenti (#2770)" inviata il 11/08/2021 12:10:49
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Codici territori non corrispondenti (#2770)" inviata il 11/08/2021 11:44:11
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Codici territori non corrispondenti (#2770)" inviata il 11/08/2021 11:56:13
.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
