### ISSUE TITLE
Sahara Occidentale

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#2771]
L'agenzia delle entrate riporta tra gli stati/territori "Sahara Spagnolo" come soppresso e codice "Z339".
ISTAT invece riporta, per lo stesso codice AT "Z339",  "Sahara Occidentale" come attivo e con codice ISTAT "905".
Nella tabella di decodifica 02 (Stati esteri) non è presente.

Trattandosi di un territorio conteso in attesa di referendum sull'indipendenza dal Marocco, prevale l'indicazione di AE?

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Sahara Occidentale (#2771)" inviata il 10/08/2021 14:55:33.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by ncapozzi** [comment]
Buongiorno,
per gli stati esteri/territori non esiste ancora un archivio storico di riferimento univoco come avviene invece per i Comuni. Nel caso di stati/territori cessati (es. Jugoslavia, URSS o "Sahara Spagnolo" ) è necessario utilizzare il codice 998 indicando la descrizione non presente in tabella.(rif. issue 2351, 2249)

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Sahara Occidentale (#2771)" inviata il 11/08/2021 11:55:25.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Sahara Occidentale (#2771)" inviata il 11/08/2021 11:55:26.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
