### ISSUE TITLE
Accordo di fruizione

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#2773]
Nel tentativo di registrare il mio ente all'area dedicata al perfezionamento degli accordi di fruizione non riesco (e con me colleghi di altri comuni) a indicare l'ente interessato e quindi a proseguire... 
![immagine](https://user-images.githubusercontent.com/50611668/129188210-538c8042-a208-4c9a-a040-d35d0b97cdd1.png)
![immagine](https://user-images.githubusercontent.com/50611668/129189007-57bc00f1-d78e-4660-abcf-b140f6aa52f6.png)

Che per caso l'accordo di fruizione è precluso ai Comuni, che ne trarrebbero giovamento per le attività non strettamente d'anagrafe e per le quali al momento l'accesso ad ANPR tramite le connessioni già in essere è tassativamente proibito?

**Comment by mttfranci** [comment]
Salve.
Come indicato anche in altre issue, ad esempio la #2749, al momento la piattaforma è stata aperta solo ad alcuni enti sperimentatori. Al termine del periodo di sperimentazione saranno resi noti i tempi per l’apertura a tutti gli altri enti/PA.
Saluti

Assistenza ANPR

**Comment by franthemanIT** [comment]
Grazie, suggerirei allora di cambiare la comunicazione nella pagina dedicata agli accordi di fruzione. Del tipo " una ristretta platea di Pubbliche Amministrazioni centrali e locali, GIA' INDIVIDUATA" e magari ribadire il concetto dove si danno indicazioni per l'accreditamento. "Gli enti individuati per la sperimentazione possono.." ecc. ecc.
Ci siamo cascati in diversi :)

**Comment by patriziasaggini** [comment]
Per maggiore trasparenza, sarebbe anche molto utile indicare chi sono i soggetti che partecipano alla sperimentazione, e i tempi di conclusione. 
Grazie!

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accordo di fruizione (#2773)" inviata il 12/08/2021 15:57:25.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accordo di fruizione (#2773)" inviata il 12/08/2021 14:39:57.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Accordo di fruizione (#2773)" inviata il 12/08/2021 13:24:22.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by mttfranci** [comment]
@franthemanIT e @patriziasaggini : 

Grazie dei suggerimenti, li inoltreremo al cliente

Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accordo di fruizione (#2773)" inviata il 13/08/2021 09:30:38.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by franthemanIT** [comment]
@mttfranci grazie.
Visto che verrà interessato "il cliente" (immagino il Ministero dell'interno), gli si puo' fare presente anche che, se la sperimentazione a livello di comuni si fa effettivamente con Milano e Genova, questa risulta davvero poco significativa, visto che si tratta di due comuni decisamene grandi, mentre la rete dei comuni italiani è per la maggior parte costituita da comuni di dimensioni ben minori?
Questi svolgono per forza di cose le medesime funzioni, ma con modalità e strumenti operativi (anche tecnologici) differenti.
Grazie.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accordo di fruizione (#2773)" inviata il 24/08/2021 10:27:40.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
