### ISSUE TITLE
Errore codifica comune di MALE'

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#2774]
Buongiorno, volevo segnalare un'errata codifica del comune di MALE' (TN), nella denominazione traslitterata e' definito come MALE invece che MALE' 
20017,"1920-10-16","1923-02-13","802253","E850","MALÉ","MALE","","",22,"022","04","","C","TN","I","2020-08-04",""
21639,"1923-02-14","1928-09-05","022110","E850","MALÉ","MALE","","",22,"022","04","","C","TN","I","2020-08-04",""
21640,"1928-09-06","1953-01-03","022110","E850","MALÉ","MALE","","",22,"022","04","","C","TN","I","2020-08-04",""
21641,"1953-01-04","1970-08-04","022110","E850","MALÉ","MALE","","",22,"022","04","","C","TN","I","2020-08-04",""
5260,"1970-08-05","9999-12-31","022110","E850","MALÉ","MALE","","",22,"022","04","TN","A","TN","I","2020-08-04",""

Grazie e buon lavoro.

Andrea Galli

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Errore codifica comune di MALE' (#2774)" inviata il 18/08/2021 08:15:00.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by m-casanova** [comment]
Pensando di fare cosa gradita, segnalo anche i casi simili:

ANTEY-SAINT-ANDRÉ

    22017,"1861-03-17","1927-01-11","001874","A305","ANTEY SAINT ANDRÉ","ANTEY SAINT ANDRE","","",1,"001","01","","C","TO","","2020-08-04",""
    22015,"1927-01-12","1939-10-20","007002","A305","ANTEY SAINT ANDRÉ","ANTEY SAINT ANDRE","","",7,"007","02","","C","AO","","2020-08-04","007503"
    22016,"1946-01-30","1977-01-01","007002","A305","ANTEY SAINT ANDRÉ","ANTEY SAINT ANDRE","","",7,"007","02","","C","AO","","2020-08-04","007503"
    329,"1977-01-02","9999-12-31","007002","A305","ANTEY-SAINT-ANDRÉ","ANTEY-SAINT-ANDRE","","",7,"007","02","AO","A","AO","","2020-08-04",""

ARVIÉ

    14012,"1939-10-21","1946-01-29","007005","A452","ARVIÉ","ARVIE","","",7,"007","02","","C","AO","","2020-08-04","007505"

GRESSONEY-LA-TRINITÉ

    4519,"1977-01-02","9999-12-31","007032","E167","GRESSONEY-LA-TRINITÉ","GRESSONEY-LA-TRINITE","","",7,"007","02","AO","A","AO","","2020-08-04",""

PRÉ-SAINT-DIDIER

    22200,"1861-03-17","1927-01-11","001924","H042","PRÉ SAINT DIDIER","PRE SAINT DIDIER","","",1,"001","01","","C","TO","","2020-08-04",""
    22198,"1927-01-12","1939-10-20","007053","H042","PRÉ SAINT DIDIER","PRE SAINT DIDIER","","",7,"007","02","","C","AO","","2020-08-04","007538"
    22199,"1946-01-30","1977-01-01","007053","H042","PRÉ SAINT DIDIER","PRE SAINT DIDIER","","",7,"007","02","","C","AO","","2020-08-04","007538"
    7681,"1977-01-02","9999-12-31","007053","H042","PRÉ-SAINT-DIDIER","PRE-SAINT-DIDIER","","",7,"007","02","AO","A","AO","","2020-08-04",""

**Comment by ncapozzi** [comment]
Buongiorno,
dalle nostre verifiche risulta che la tabella Brunetta, alla quale ANPR fa riferimento per le traslitterazioni, prevede la traslitterazione con E’  solo per parole che terminano con "è" grave, mentre  MALÉ e tutte le altre denominazioni da lei indicate terminano con É acuta quindi è corretta la traslitterazione con E.

**Comment by galliandrea** [comment]
Sinceramente la tabella Brunetta puo' dire che MALE' traslitterata sia MALE ma a logica mi sembra evidente che sia errata la traslitterazione.
