### ISSUE TITLE
Necessità di cambiare indicazione di sesso su scheda anagrafica

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#2775]
Buongiorno.
Stiamo cercando di rettificare il dato del sesso da maschile a femminile della scheda anagrafica num. 18935136.
Siamo partiti, prima di rettificare il sesso, dall'unire i codici fiscali - mediante la funzione "Risoluzione disallineamenti con AE".
I codici fiscali da unire sono SLZGRT05E46F704O e SLZGRT05E06F704K.

L'errore che ci dà il sistema è il seguente: 
Esito ANPR: Soggetto individuato in AT già in trattamento - operazione non effettuabile in data odierna (Codice: EAM15) 
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-08-18 10:56:25 , idOperazioneANPR 612425593 (Codice: EN527)

Come possiamo procedere?

I nostri riferimenti sono:
Paltrinieri Andrea
Ufficiale d'Anagrafe del Comune di BIASSONO (108009)
e-mail: anagrafe@biassono.org
tel. 0392201060

distinti saluti
Andrea Paltrinieri

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Necessità di cambiare indicazione di sesso su scheda anagrafica (#2775)"
inviata il 18/08/2021 11:07:04.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by paltrinan** [comment]
Ho provato a fare nuovamente l'operazione di unificazione dei codici fiscali ma non sono ancora riuscito.
Il numero dell'operazione andata a male è 622269743.
Chiedo se posso essere contattato allo 039-2201060

Distinti saluti

Andrea Paltrinieri

**Comment by paltrinan** [comment]
Chiedo di essere contattato allo 039-2201060 per la risoluzione del problema.

L'Ufficiale d'Anagrafe - Comune di Biassono

Andrea Paltrinieri

**Comment by rvinzani** [comment]
Risolto telefonicamente. Saluti
