### ISSUE TITLE
Smarrimento smart card ANPR

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2776]
Buongiorno,
nell'eventualità di smarrimento di una smart card ANPR, come occorre procedere?
Cordiali saluti.

**Comment by cmigliardi** [comment]
buongiorno 
in caso di smarrimento
occorre che ALS  del comune  richieda immediatamente una nuova  SC - ciò  consente di bloccare  la SC  e chiedere una nuova carta

**Comment by cmigliardi** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Smarrimento smart card ANPR (#2776)" inviata il 18/08/2021 12:41:12.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Smarrimento smart card ANPR (#2776)" inviata il 18/08/2021 12:32:53.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Smarrimento smart card ANPR (#2776)" inviata il 18/08/2021 12:50:08.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
