### ISSUE TITLE
Mutazione residenza - Famiglie coabitanti

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#2777]
Buongiorno.
Avrei bisogno di un chiarimento relativamente ai controlli sulla mutazione residenza in ambiente di PROD.

Il signor Rossi, provenendo da altro comune,  prende la residenza in coabitazione con il signor Bianchi
Quando ancora il procedimento è aperto, il signor Bianchi chiede il trasferimento di residenza in altro comune.
Il comune in cui il signor Bianchi vorrebbe trasferirsi riceve un messaggio di procedimento aperto nel nostro comune.
Il procedimento non riguarda il signor Bianchi, ma il signor Rossi che è in una famiglia coabitante con quella del signor Bianchi.

Questo tipo di segnalazione è prevista o si tratta di qualche altro tipo di problema?

Grazie.
G. Trisolini

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Mutazione residenza - Famiglie coabitanti (#2777)" inviata il 19/08/2021
11:45:52.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by frmariani** [comment]
il procedimento amministrativo è relativo alle persone coinvolte nella specifica operazione di cambio di residenza; due soggetti coabitanti dovrebbero avere due procedimenti amministrativi diversi; se ha un problema in produzione mi segnali il caso per favore così potrò essere più chiara.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
