### ISSUE TITLE
Accesso tramite credenziali

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#2778]
Buongiorno, da stamani i nostri clienti comunicano problemi per accedere alla web app tramite le credenziali.
So' che l'accesso deve avvenire tramite smart card ma spesso succede che debbano accedere utilizzando le credenziali spostandosi in diversi uffici. 
E' un problema temporaneo? 
Andrea Galli

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Accesso tramite credenziali (#2778)" inviata il 19/08/2021 13:31:05.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by FilippoPapi** [comment]
buongiorno
vi confermiamo che l'accesso è consentito solo con smart card

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accesso tramite credenziali (#2778)" inviata il 23/08/2021 11:29:32.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
