### ISSUE TITLE
EAM13 - Soggetto individuato in AT - in lavorazione per risoluzione omocodia - Codice fiscale NON variato 

### ISSUE THREAD

**Issue by anagrafeviterbo** [italia/anpr#2779]
Per il codice ANPR 97163182 non riusciamo a variare data di nascita  e relativo codice fiscale in quanto in precedenza, a seguito di precedente variazione ed erroronea richiesta di omocodice, gli è stato attribuito un omocodice numerico provvisorio (validato da AT e marcato ANPR). Contattata l'Agenzia delle Entrate di Viterbo, ci riferiscono che non possono proseguire a sbloccare la situazione poichè la posizione risulta marcata ANPR.
Si rimane in attesa di cortese urgente riscontro
Rosalba Rubuano - Ufficiale d'Anagrafe Comune Viterbo

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
EAM13 - Soggetto individuato in AT - in lavorazione per risoluzione
omocodia - Codice fiscale NON variato  (#2779)" inviata il 19/08/2021
15:28:46.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by frmariani** [comment]
deve scrivere alla Direzione Centrale dell'Agenzia delle Entrate specificando l'errore effettuato e chiedendo l'annullamento della richiesta di omocodia
entrate.archivioanagrafico@agenziaentrate.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
