### ISSUE TITLE
[6001] forzaCertificazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#278]
buongiorno.

ho letto di questa opzione per ottenere il certificato anche in presenza di blocchi o procedimenti in corso.
trovo in effetti il tag all'interno degli schemi XSD, ma non ne trovo indicazione nei tracciati excel aggiornati al 12-07-2017 e nella documentazione.

quali sono i valori consentiti per questo campo?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
La documentazione (www.anpr.interno.it) è stata aggiornata
