### ISSUE TITLE
Soggetto individuato in AT - in lavorazione per risoluzione omocodia - Codice fiscale NON variato

### ISSUE THREAD

**Issue by anagrafeviterbo** [italia/anpr#2780]
Contatto telefonico Rosalba Rubuano Comune Viterbo 0761/348654

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Soggetto individuato in AT - in lavorazione per risoluzione omocodia -
Codice fiscale NON variato (#2780)" inviata il 19/08/2021 15:31:29.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by rvinzani** [comment]
Come da accordi attendo che risolva i problemi di accesso ad ANPR per ricontattarla
