### ISSUE TITLE
 Errore Anpr Cod: EAV50 - Più codici fiscali individuati in AT

### ISSUE THREAD

**Issue by anagrafeviterbo** [italia/anpr#2781]
Per il codice ANPR 97155266 in data 28/07/2021 abbiamo variato data di nascita e, dato che l'operazione non andava a buone fine ed appariva il messaggio Errore Anpr Cod: EAV50 - Più codici fiscali individuati in AT, abbiamo richiesto per errore omocodice generando un C.F. numerico provvisorio validato AT e marcato ANPR. Anche per questa posizione l'Agenzia delle Entrate di Viterbo ci ha riferito che non può procedere perchè il C.F. omocodice provvisorio è marcato ANPR.
Al fine di risolvere il problema ed attribuire un C,.F. alfanumerico corretto al cittadino, si chiede vostra assistenza
Grazie
Rosalba Rubuano - Ufficiale d'Anagrafe Comune di Viterbo TEl 0761/348654

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Errore Anpr Cod: EAV50 - Più codici fiscali individuati in AT (#2781)"
inviata il 19/08/2021 15:54:24.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by rvinzani** [comment]
Come da accordi attendo che risolva i problemi di accesso ad ANPR per ricontattarla
