### ISSUE TITLE
Accesso Webapp negato con USR/PWD

### ISSUE THREAD

**Issue by dierossi** [italia/anpr#2782]
Buongiorno,

mi potete confermare, per piacere, che da qualche giorno non è più possibile accedere alla webapp attraverso le la usr/pwd ma è obbligatorio utilizzare la Smart card ANPR???

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Accesso Webapp negato con USR/PWD (#2782)" inviata il 20/08/2021 12:59:40.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by FilippoPapi** [comment]
buongiorno
vi confermiamo che l'accesso è consentito solo con smart card.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Accesso Webapp negato con USR/PWD (#2782)" inviata il 23/08/2021 11:29:12.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
