### ISSUE TITLE
MANCATO ACCESSO CON SMART CARD NUOVA

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2783]
Buongiorno, per il Comune di BOSA la referente RITA PROCIDA ha ricevuto la sua nuova smart card circa 1 mese e mezzo fa. Ma nonostante le varie prove eseguite (come da vostre specifiche) non riesce ad entrare da qualsiasi browser segnala: SSL_ERROR_HANDSHAKE_FAILURE_ALERT
S.o. W10 64bit - Provato anche a configurare Firefox (v.91) - La smart card viene letta da Dike ma non dai browser - provato anche a disattivare il firewall ma non c'è modo di fargliela leggere/riconoscere

Contattare la sig.ra PROCIDA RITA al nr 0785368005 orari: 9:00 - 12:00 LUN-MAR-GIOV e 15:00 - 18:00 MERC
Grazie 
Cordiali saluti

Cinzia Girelli
GPI SpA
Cell. 3346216774

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
MANCATO ACCESSO CON SMART CARD NUOVA (#2783)" inviata il 23/08/2021
12:41:29.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by Leonforte** [comment]
Problema risolto con intervento da remoto
