### ISSUE TITLE
ANPR Archivio comuni - Date relative a variazioni di denominazione

### ISSUE THREAD

**Issue by m-casanova** [italia/anpr#2784]
Buongiorno,

in riferimento all'[Archivio storico dei comuni](https://www.anpr.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv) su sito ANPR aggiornato al 30 luglio 2021, pensando di fare cosa gradita, segnalo la presenza di alcune apparenti discrepanze per date relative a variazioni di denominazione, come nei tre casi di seguito.

Per **Baio Dora** è segnalata la variazione dal 16 luglio 1917 ma il [relativo decreto](https://www.gazzettaufficiale.it/eli/id/1917/09/03/017U1325/sg) risulta essere entrato in vigore il 18 settembre 1917.

    11374,"1861-03-17","1917-07-15","001803","A583","BAIO","BAIO","","",1,"001","01","","C","TO","","2016-06-17","001591"
    17976,"1917-07-16","1927-01-11","001803","A583","BAIO DORA","BAIO DORA","","",1,"001","01","","C","TO","","2016-06-17",""

Per **Brenzone sul Garda** la [legge regionale](http://bur.regione.veneto.it/BurvServices/pubblica/stampapdfburv.aspx?num=22&date=21/02/2014) è stata pubblicata il 21 febbraio 2014, perciò dovrebbe essere entrato in vigore 15 giorni dopo.

    1254,"1924-03-24","2014-02-21","023014","B154","BRENZONE","BRENZONE","","",23,"023","05","","C","VR","","2016-06-17","023538"
    1255,"2014-02-22","9999-12-31","023014","B154","BRENZONE SUL GARDA","BRENZONE SUL GARDA","","",23,"023","05","VR","A","VR","","2016-06-17",""

Per **Fubine Monferrato** la data riportata è quella della deliberazione del consiglio regionale, ma la pubblicazione sul [Bollettino ufficiale](http://www.regione.piemonte.it/governo/bollettino/abbonati/2017/10/attach/dcr_del187_pdcr198_.pdf) è del 9 marzo 2017 (apparentemente con entrata in vigore dal 24 marzo).

    4135,"1861-03-17","2017-02-13","006076","D814","FUBINE","FUBINE","","",6,"006","01","AL","C","AL","","2018-08-08","006565"
    22983,"2017-02-14","9999-12-31","006076","D814","FUBINE MONFERRATO","FUBINE MONFERRATO","","",6,"006","01","AL","A","AL","","2017-05-04",""

Grazie.

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr] ANPR
Archivio comuni - Date relative a variazioni di denominazione (#2784)"
inviata il 24/08/2021 08:12:43.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by ncapozzi** [comment]
Buonasera,
la verifica delle date sarà richiesta a ISTAT.

**Comment by ncapozzi** [comment]
Buonasera,
la verifica delle date sarà richiesta a ISTAT.

**Comment by ncapozzi** [comment]
Buonasera,
il file archivio comuni è stato aggiornato secondo quanto indicato da ISTAT.
1) Baio Dora. Decorrenza 18/09/1917.
2) Brenzone sul Garda. Decorrenza 8 marzo 2014. 
3) Fubine Monferrato. Si conferma la data del 14 febbraio 2017, a fronte della certificazione prodotta dal Comune interessato.
