### ISSUE TITLE
MANCATO ACCESSO CON NUOVA SMART CARD 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#2785]
Buongiorno, per il comune di VELO VERONESE non è stato possibile accedere alla Webapp con smart card del Sindaco. E' il primo accesso propedeutico all'abilitazione del ALS e ALP. Comune non ancora subentrato ma pronto a procedere al presubentro. 

Nonostante le prove effettuate come da vostre indicazioni sul sito Anpr, il certificato della smart card non viene letto da nessun Browser (effettuata anche configurazione di Firefox v.91.0.1)
Il dike lo legge ed il test riconosce anche il pin della smart card, mentre sulle opzioni internet a smart card inserita non viene evidenziato il certificato - se si prova ad installare va sul tab Altri utenti - e se si apre il certificato segnala errore nell'inizializzazione del dispositivo di firma, dispositivo di firma non riconosciuto. 

Sulla issue #2772 ho letto che potrebbe essere il certificato a bordo della smart card ad essere corrotto - ho aperto ieri un'altro caso uguale per il comune di Bosa, ho altro ticket dal comune di FIAVE' dove sto attendendo che venga installato il dike per terminare le verifiche ma il comportamento è lo stesso e trattasi di smart card recenti. 
E' possibile che ci sia di nuovo un lotto di smart card difettoso? 

Dati del cliente da contattare per questo ticket da mercoledì 25/08 mattino dalle 09:00 alle 12:00 Grossulle Stefania  045 6518016 
S.o. W10 Pro 64bit  

Si chiede cortese urgenza.

Grazie 
Cordiali saluti

Cinzia Girelli
Gpi Spa
cell. 3346216774

**Comment by CGIRELLI-HUB** [comment]
Buongiorno oggi ho terminato i test col comune di Fiavè stesso problema. Il certificato presente a bordo della smart card non è riconosciuto. Potete contattare anche questo comune? Sig,ra Crosina Morena al nr. 0465-735029 int. 2 tutti i giorni dalle 08;15 alle 12:30 e dalle 14:00 alle 16:30 eccezion fatta per il venerdì chiudono alle 12:00. Grazie - Cordiali saluti

**Comment by Leonforte** [comment]
Problema risolto con intervento da remoto
