### ISSUE TITLE
Collegamento codici fiscali non effettuabile riferimento ticket #2692

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2786]
Buongiorno,
con riferimento al ticket #2692, si comunica che abbiamo provato a procedere ma non riusciamo a fare l'inversione di nome e cognome. Si allega errore. 
Grazie.
![Cattura](https://user-images.githubusercontent.com/57749903/130755735-0540dc48-504f-4e85-8dac-18620b3780a5.JPG)

**Comment by AMonopoliADS** [comment]
Sono fuori dall'ufficio fino a 30/08/2021




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Collegamento codici fiscali non effettuabile riferimento ticket #2692
(#2786)" inviata il 25/08/2021 10:27:12.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by frmariani** [comment]
Non mi sembra che abbia proceduto con il collegamento dei CF ma con una mutazione dei dati anagrafici;
i due CF devono essere collegati quindi proceda con l'operazione che ha descritto nella issue #2692

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
