### ISSUE TITLE
[3002] Scheda duplicata per stesso codice fiscale

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2787]
Buongiorno, per conto del Comune di Caluso vi segnalo un problema sulla scheda anagrafica di un cittadino. Cercando tramite codice fiscale  DLLGMN81.....P vengono restituite due schede associate a due "idSchedaSoggettoANPR" differenti: 78822785 e 45319775. Potreste, gentilmente, verificare e allineare la posizione eventualmente ? Grazie

Uff. Anagrafe
Dott.ssa Eleonora Bassino
Tel. 011-9894936

**Comment by rvinzani** [comment]
Gent.le Dott.ssa Bassino, se il soggetto è residente nel suo comune, deve contattare l'altro comune in cui il soggetto risulta residente e chiedere di cancellarlo per doppia iscrizione. Se il soggetto non è residente nel suo comune dovrà cancellarlo lei per doppia iscrizione

**Comment by Eduardo1977** [comment]
Buongiorno, la cancellazione per doppia iscrizione è già stata effettuata dal comune di provenienza (comune di San Benigno) a suo tempo, con l'assistenza telefonica di Sogei. Come bisogna procedere? Grazie

**Comment by rvinzani** [comment]
Nessun problema allora dovete utilizzare la scheda attualmente aperta. L'altra rimarrà visibile ma non utilizzabile
