### ISSUE TITLE
WS4005 - Download notifiche di mutazione residenza

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2788]
COMUNE DI CAPONAGO
VARISCO M.GIUSEPPINA

Buongiorno
si è verificata un'anomalia nel download delle notifiche di mutazione di residenza del 24.08.21.

Potete verificare il motivo per ilquale la notifica 616641059 non è stata messa a disposizione ? 

In allegato gli screenshot della schermata ANPR ed il nostro LOG di download.

Si resta in attesa di gentile riscontro.

Saluti
![Immagine1](https://user-images.githubusercontent.com/54433203/131462720-7d3b26a5-0502-46f1-b67f-318a9f0a42d2.png)
![Immagine2](https://user-images.githubusercontent.com/54433203/131462725-e9199905-b60c-49c5-b669-a84b5332170c.png)

**Comment by amollicone1982** [comment]
Salve, cosa intende per non messa a disposizione? Cosa accade premendo il pulsante visualizza?
Ho visto che la notifica è stata elaborata il 24/08/2021 alle 11:30

**Comment by GabriellaBallabio** [comment]
Intendiamo che scaricando le notifiche con il WS 4005 , questa notifica non è stata scaricata.

**Comment by amollicone1982** [comment]
Ci potete fornire l'idoperazione anpr del 4005?

**Comment by GabriellaBallabio** [comment]
Gli identificativi delle operazioni sono presenti ed evidenziati nella seconda immagine associata al primo ticket di apertura.

**Comment by amollicone1982** [comment]
nei 4005 è richiesto un intervallo che va da 
2021-08-12T01:01:01+01:00 
a
2021-08-24T01:01:01+01:00 (l'una del mattino del 24 agosto)

La notifica in questione è stata elaborata la mattina del 24 agosto alle 11:30  e per tale motivo non viene trovata
