### ISSUE TITLE
Scarico per motivata richiesta - luogo di nascita discordante

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#2789]
Buongiorno

il 7 luglio abbiamo richiesto lo scarico per motivata richiesta dei dati del comune 041070.

Rileviamo una differenza nel luogo di nascita di diversi cittadini, come ad esempio l'id 70306275, che nel file scaricato risulta:

```
        <dataNascita>1951-08-09+01:00</dataNascita>
        <luogoNascita>
            <comune>
                <nomeComune>TERRE ROVERESCHE</nomeComune>
                <codiceIstat>041070</codiceIstat>
                <siglaProvinciaIstat>PU</siglaProvinciaIstat>
                <descrizioneLocalita>TERRE ROVERESCHE</descrizioneLocalita>
            </comune>
        </luogoNascita>
        <soggettoAIRE>S</soggettoAIRE>
```

mentre in una 3002 su ANPR produzione, oggi vediamo:

```
              <dataNascita>1951-08-09+01:00</dataNascita>
              <luogoNascita>
                <comune>
                  <nomeComune>PIAGGE</nomeComune>
                  <codiceIstat>041046</codiceIstat>
                  <siglaProvinciaIstat>PS</siglaProvinciaIstat>
                </comune>
              </luogoNascita>
              <soggettoAIRE>S</soggettoAIRE>

```

Potete controllare per favore?

PS: il Comune di PIAGGE con altri, ha costituito nel 2017 il nuovo comune di TERRE ROVERESCHE.

**Comment by amollicone1982** [comment]
Questo perchè quando avete fatto lo scarico (il 7 luglio) il soggetto risultava nato a TERRE ROVERESCHE.
In data 24 luglio il comune di nascita è stato cambiato con una mutazione dati anagrafici (id operazione anpr 591110443).
Penso che per gli altri soggetti valga la stessa cosa
