### ISSUE TITLE
Iscirizione per nascita senza cittadinanza (1001)

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2790]
COMUNE DI CAPONAGO
Varisco M.Giuseppina

Buongiorno
stiamo cercando di inviare ad ANPR un'iscirizione per nascita di un bambino che ha una cittadinanza non ancora definita.
Per cui stiamo trasmettendo nel TAG DescrizionStato = Non attribuibile , nel TAG CodiceStato = 998 e nelle note il motivo, il WS restituisce l'errore :

Stato estero cittadinanza 998 inesistente sulla tabella di riferimento

Di seguito i riferimenti dell'operazione

idOperazioneANPR 622716352 2021-09-01 09:02:32

Potete dirci qual'è l'errore, nella documentazione tecnica oeggetto cittadinanza.xlsx dice di mettere 998 in caso di cittadinanza non attribuibile.

Restiamo in attesa di gentile riscontro. Grazie

**Comment by rvinzani** [comment]
Nel caso di iscrizione per nascita potete utilizzare come stato fittizio "APOLIDE" per poi sostituirlo quando al bambino verrà assegnata la cittadinanza

**Comment by GabriellaBallabio** [comment]
Buongiorno
purtroppo non è possibile mettere APOLIDE ad un bambino che non ha ancora acquisito alcuna cittadinanza. APOLIDE è uno stato preciso.
Nella tabella degli stati abbiamo visto che esiste la possibilità di indicare IN CORSO DI DEFINIZIONE. Abbiamo utilizzato questa modalità. Grazie

**Comment by rvinzani** [comment]
Perfetto. Buona giornata
