### ISSUE TITLE
[1002] iscrizione dall'estero - AEE95 Operazione non effettuabile

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#2791]
durante l'iscrizione dall'estero di un nominativo riceviamo questo errore:
<listaErrori>
	<errore>
		<codiceErroreAnomalia>AEE95</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2021-09-01 09:43:52 , idOperazioneANPR 622788520</testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>EC010</codiceErroreAnomalia>
		<tipoErroreAnomalia>W</tipoErroreAnomalia>
		<testoErroreAnomalia>Campo Note stato civile obbligatorio se stato civile = 9 (Non classificabile / ignoto / non documentato)  </testoErroreAnomalia>
	</errore>
</listaErrori>

il cittadino arriva dall'URSS e abbiamo impostato il luogo di nascita in questo modo:
<luogoNascita>
	<localita>
		<descrizioneLocalita>URSS</descrizioneLocalita>
		<descrizioneStato>NON ATTRIBUIBILE</descrizioneStato>
		<codiceStato>998</codiceStato>
	</localita>
</luogoNascita>

può essere questa la causa dell'errore oppure c'è altro?

Grazie

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by ncapozzi** [comment]
Il codice fiscale indicato nella richiesta non esiste su Agenzia delle Entrate. Si suggerisce di verificare su PuntoFisco.
Per ulteriore richiesta di assistenza per cortesia contattare il numero verde 800863116

**Comment by ncapozzi** [comment]
Il codice fiscale indicato nella richiesta non esiste su Agenzia delle Entrate. Si suggerisce di verificare su PuntoFisco.
Per ulteriore richiesta di assistenza per cortesia contattare il numero verde 800863116

**Comment by DanielCarenzo** [comment]
Grazie. procediamo alla verifica del codice fiscale
