### ISSUE TITLE
RIPRISTINO RESIDENZA PRECEDENTE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2793]
Buongiorno
COMUNE DI CASERTA - PROD
E' stato, erroneamente, utilizzato il servizio  5001 per una immigrazione da altro comune subentrato. Tale operazione ha fatto immigrare tutti i componenti del nucleo. Per ripristinare la posizione precedente di un solo componente, riportandolo al comune precedente, è possibile utilizzare il servizio 5005 con tipo mutazione  6 ?? 
O bisogna annullare la mutazione 5001 e rifarla per singolo componente con 5005 ?
Grazie

**Comment by frmariani** [comment]
Purtroppo la sua richiesta non è chiara; il servizio 5005 tipo mutazione 6 viene utilizzato per il Ripristino ante subentro quindi non credo che sia il suo caso visto che parla di servizio 5001 utilizzato erroneamente.
Cerchi di riformulare la domanda eventualmente indicando l'idanpr dell'operazione erroneamente effettuata.

**Comment by rinonasti** [comment]
Ho verificato devo annullare le operazioni effettuate e rifarle correttamente.
Grazie

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
