### ISSUE TITLE
Accordo di fruizione - Sperimentazione, aggiunta Ente locale per la consultazione tramite API

### ISSUE THREAD

**Issue by fl-adisupuglia** [italia/anpr#2794]
Gentilissimi,

rappresento una Agenzia Regionale interessata alla consultazione mediante API

E' possibile unirsi alla sperimentazione in corso ?

Grazie

**Comment by FilippoPapi** [comment]
buongiorno
potete fare richiesta al Ministero dell'Interno, Direzione Centrale Servizi Demografici
