### ISSUE TITLE
[3002] Ricerca soggetto tramite codicefiscale: filtro su schede cancellate

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2795]
Buongiorno, a seguito della risposta fornita per la [issue]#2787 #2787  , chiedo come si possa utilizzare il servizio 3002 utilizzando come criterio di ricerca il "codiceFiscale" evitando che nella risposta compaiano anche le schede cancellate. 
A tal proposito, a titolo di esempio vi fornisco IdOperazioneANPR = 623116612 effettuata qualche ora fa, chiedendo se sia corretto cha la risposta contenga anche la **scheda cancellata** per "doppia iscrizione", dato che si vuole consultare la scheda corrente attualmente valida (dataOraRichiesta=01/09/2021 e dataRiferimentoRichiesta=01/09/2021). 
Comunque, guardando le specifiche del servizio 3002 non vedo filtri del tipo "cancellato"=No. C'è un modo per risolvere il problema modificando la request? 
Grazie, come sempre per la disponibilità.
Cordiali Saluti

Eduardo Gira

**Comment by rvinzani** [comment]
Non è previsto per il momento un aggiornamento della request del 3002.
Potete comunque inserire un filtro nell'elaborazione della risposta escludendo le schede in cui sia presente il tag datiCancellazione.

**Comment by Eduardo1977** [comment]
Si certamente, immaginavo la soluzione fosse quella ma speravo che il controllo si potesse fare a monte.

**Comment by rvinzani** [comment]
Mi dispiace ma questo tipo di aggiornamento non è previsto.
Chiudo la issue. Nel caso avesse necessità di ulteriori chiarimenti ne riapra una nuova con riferimento a questa
