### ISSUE TITLE
Errore: security binding between the client and the server su chiamata ai servizi

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#2796]
dalla giornata di oggi 01-09-2021 (dalle ore 12:00 circa), in modo random, sta capitando sempre più spesso che in risposta ad un'invocazione di un servizio si ottiene l'errore come quello sottoriportato come esempio:
"An error occurred while making the HTTP request to https://ws.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server. "
Non capita solo sul 3000 ma anche sull'invocazione di altri servizi.
Di seguito alcuni idOperazioneComune di esempio su cui si è ottenuto il suddetto errore (ottenendo l'errore non si riceve la response del servizio e quindi non conosciamo l'idAnpr dell'operazione):
- 13269029
​- 13268864
​- 13269201
​- 13270241

Inoltre segnaliamo che sempre nella giornata odierna abbiamo rilevato un significativo incremento del seguente errore:
"The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."
Di seguito alcuni idOperazioneComune di esempio su cui si è ottenuto il suddetto errore (ottenendo l'errore non si riceve la response del servizio e quindi non conosciamo l'idAnpr dell'operazione):
- 13264870
- 13268517
- 13268532

Ovviamente, tali anomalie ci provocano notevoli malfunzionamenti/disallineamenti del nostro sw in particolare sull'aggiornamento della Banca Dati Locale

Laboratorio Dedagroup

**Comment by mttfranci** [comment]
Salve.
Sembrerebbe che le richieste da voi segnalate non arrivino proprio sui nostri sistemi.

Avete verificato che i client siano configurati correttamente e in particolare con che protocollo di sicurezza invocate il servizio?

Se a vostro avviso tutto è configurato correttamente, potresti confermarci che protocollo crittografico usate?
Inoltre per effettuare una ulteriore verifica sui nostri sistemi perimetrali sarebbe opportuno avere, oltre all'id operazione comune, il comune e l'orario della richiesta (il più  preciso possibile)
NB: l'id operazione comune è univoco solo all'interno di un comune, non a livello di sistema, anche per questo è sempre opportuno indicare il comune.

Saluti

Assistenza ANPR

**Comment by acarcea** [comment]
Salve,
rispondo per punti:

- le richieste segnalate arrivano sui vostri sistemi e vengono anche correttamente processate in quanto abbiamo verificato che sulla WebApp nell'elenco operazioni ci sono sia la request sia la response.
- la configurazione del nostro client non è cambiata da tempo immemore; all'epoca fu tutto configurato secondo le specifiche ANPR. Ad ulteriore riprova della corretta configurazione del client, nella giornata in questione, su 20000 richieste solo 400 hanno restituito il problema.
- di seguito gli id operazione - codice mittente - data ora richiesta di esempio:
   13269029 - 063001 - 2021-09-01T14:43:27.7918836
​   13268864 - 063001 - 2021-09-01T14:33:46.4718564
​   13269201 - 074011 - 2021-09-01T14:54:07.5618125
​   13270241 - 075087 - 2021-09-01T16:09:14.8803194

   13264870 - 022167 - 2021-09-01T12:30:19.7790425
   13268517 - 051039 - 2021-09-01T14:14:55.4663266
   13268532 - 074011 - 2021-09-01T14:15:17.8381334

Inoltre segnaliamo un'altra tipologia di errore che stiamo ricevendo:
An error (The request was aborted: The request was canceled.) occurred while transmitting data over the HTTP channel.
di seguito gli id operazione - codice mittente - data ora richiesta di esempio:
   13310158 - 028017 - 2021-09-03T11:58:00.6266632
   13301792 - 063079 - 2021-09-03T09:35:22.1703055
   13300225 - 063034 - 2021-09-03T09:07:44.9007641
per tutti questi errori non si riesce a ricevere la response che invece è presente in WebApp.
In caso di necessità di ulteriori info, potreste fornirci una mail dove poter scrivere direttamente.

Saluti
 
Laboratorio Dedagroup

**Comment by mttfranci** [comment]
Se per le seguenti operazioni trovate la response nella web app : 
13310158 - 028017 - 2021-09-03T11:58:00.6266632
13301792 - 063079 - 2021-09-03T09:35:22.1703055
13300225 - 063034 - 2021-09-03T09:07:44.9007641

Che tipologia di operazione sono (5008, 1002...?)
Allora avete anche l'id operazione anpr?

Grazie in anticipo.

**Comment by mttfranci** [comment]
@acarcea e ancora una informazionie, il problema si presenta ancora o si è fermato dopo le segnalazioni?
Saluti

**Comment by acarcea** [comment]
Salve,
gli id delle operazioni indicate come esempio sono estrapolate dai log delle chiamate ai webservices dove, non ricevendo la response ci è impossibile fornire l'idAnpr dell'operazione.
Inoltre essendo che l'accesso alla webApp lo ha esclusivamente l'ente, non riusciamo a fornire gli l'idAnpr delle operazioni in questione.
Dalle segnalazioni di disallineamento Anpr/Nostra Banca Dati Locale che la nostra assistenza cliente riceve dagli enti abbiamo verificato che, pur non ricevendo la response tramite webservices, i dati su anpr del cittadino risultano processati in base alla request ricevuta.
Le tipologie per le operazioni indicate sono di seguito riportate;

Errore: "An error occurred while making the HTTP request to https://ws.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server. "
13269029 - 063001 - 2021-09-01T14:43:27.7918836 --> A001
 13268864 - 063001 - 2021-09-01T14:33:46.4718564 --> 3002
13269201 - 074011 - 2021-09-01T14:54:07.5618125 --> 1014
13270241 - 075087 - 2021-09-01T16:09:14.8803194 --> 6001

Errore: "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."
13264870 - 022167 - 2021-09-01T12:30:19.7790425 --> 5008
13268517 - 051039 - 2021-09-01T14:14:55.4663266 --> 3002
13268532 - 074011 - 2021-09-01T14:15:17.8381334 --> 2001

Errore: An error (The request was aborted: The request was canceled.) occurred while transmitting data over the HTTP channel.
13310158 - 028017 - 2021-09-03T11:58:00.6266632 --> 5001
13301792 - 063079 - 2021-09-03T09:35:22.1703055 --> 3002
13300225 - 063034 - 2021-09-03T09:07:44.9007641 --> 1014

Fino a venerdi 03-09-2021 Gli errori erano ancora presenti...
Siamo disponibili inoltre a fornire un contatto telefonico/mail diretto con i nostri tecnici qualora lo riteniate utile/necessario

Saluti
Laboratorio Dedagroup

**Comment by mttfranci** [comment]
Salve, Grazie della risposta.
Noi purtroppo abbiamo qualche problema a trovare le vostre operazioni.
Per questo le sto chiedendo quale è l'id operazione ANPR.
Se come dite le modifiche sono presenti nella web app di ANPR, dovreste poterle recuperare dall'elenco operazioni dei soggetti coinvolti e/o dal servizio 3003 ad esempio.
In questo modo sarà possibile verificare se le operazioni che avete inviato sono effettivamente state elaborate.
Grazie in anticipo.

**Comment by acarcea** [comment]
Salve,
di seguito l'idanpr operazioni che siamo riusciti a recuperare 

Errore: An error occurred while making the HTTP request to https://ws.anpr.interno.it/ANPRA000ServiziAire/AnprServiceA000. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server.
idOperazione - idanprOperazione - codice mittente - data ora richiesta - tipoOperazione
13269046 - 623265223 - 063001 - 2021-09-01T14:43:27.7918836 - A001

Errore: "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."
idOperazione - idanprOperazione - codice mittente - data ora richiesta - tipoOperazione
13268901 - 623259457 - 065137 - 2021-09-01T14:35:01.6722377 - 5005
13269038 - 623264854 - 065137 - 2021-09-01T14:43:54.3881589 - 2001
13269110 - 623267773 - 065137 - 2021-09-01T14:48:00.195848 - 2001

Errore: An error (The request was aborted: The request was canceled.) occurred while transmitting data over the HTTP channel.
per questo errore non troviamo operazioni...probabilmente per questa tipologia di errore non viene processato niente. Riportiamo comunque alcuni idoperazione di esempio:
idOperazione - idanprOperazione - codice mittente - data ora richiesta - tipoOperazione
13310158 - ** - 028017 - 2021-09-03T11:58:00.6266632 --> 5001
13301792 - ** - 063079 - 2021-09-03T09:35:22.1703055 --> 3002
13300225 - ** - 063034 - 2021-09-03T09:07:44.9007641 --> 1014

Inoltre per tutte le casistiche di errore risultamo moltissimi 3002 per i quali non abbiamo idAnprOperazione in quanto non viene memorizzata la response.
Restiamo in attesa di chiarimenti per tutte e tre le casistiche di errore rilevate

Saluti
Laboratorio Dedagroup

**Comment by mttfranci** [comment]
Salve, sui nostri sistemi la risposta sembra essere stata restituita correttamente con tempi dell'ordine di 2/3 secondi.
Ne abbiamo verifcato alcune, come la : 
13268901 - 623259457 - 065137 - 2021-09-01T14:35:01.6722377 - 5005
Potreste verificare la vostra infrastruttura di rete?
Grazie in anticipo.
