### ISSUE TITLE
Problemi ai servizi ANPR

### ISSUE THREAD

**Issue by c-giacomini** [italia/anpr#2797]
Buongiorno,
molti clienti questa mattina ci segnalano problemi ai servizi ANPR, avete notizie in merito?

Christian Giacomini
MAGGIOLI INFORMATICA

**Comment by Hdemografici** [comment]
Salve, 
stessa situazione per i nostri clienti

Luciano
HALLEY INFORMATICA

**Comment by iessicatoro** [comment]
Salve, a Piacenza funziona l'emissione delle Cie con ricerca dati in anpr, ma da applicativo Maggioli viene riportato il messaggio:
"Non si possiedono le credenziali di sicurezza per accedere ad ANPR oppure l'ora del server (03/09/2021 12:56:16) è nel futuro
Contattare un amministratore di sistema"
Siamo in blocco con le certificazioni

**Comment by filippo1961** [comment]
Salve,
stessa situazione
Ufficio Anagrafe Comune di Marsala

**Comment by FilippoPapi** [comment]
buongiorno
la problematica è stata risolta, grazie per la segnalazione
cordiali saluti
