### ISSUE TITLE
Esito AE: Codice fiscale formalmente errato (Codice 24)

### ISSUE THREAD

**Issue by COMUNESANGIOVANNIVALDARNO** [italia/anpr#2799]
Comune di San Giovanni Valdarno (AR) - Ambiente produzione.
Non riusciamo ad iscrivere la persona avente IdSchedaSoggettoANPR: 62385976.
Trattasi di soggetto cancellato da altro comune con ValiditaCF: 9 "Dati anagrafici non validati (soggetto non presente in Agenzia Entrate o iscritto senza validazione)".
Vi saremmo grati se poteste intervenire.
Ringraziando, si porgono cordiali saluti.

**Comment by frmariani** [comment]
Il check digit del Codice Fiscale non è corretto, ecco perchè anche nel precedente comune non è mai stato validato;
concluda l'iscrizione senza richiedere la validazione del CF; successivamente utilizzi la ricerca per dati anagrafici su punto fisco in modo che possa recuperare il CF corretto del cittadino ed effettuare la mutazione dei dati anagrafici per sanare la situazione.

**Comment by COMUNESANGIOVANNIVALDARNO** [comment]
Non riesco a fare l'iscrizione per altri motivI (ricomparsa da irreperibilità) senza richiedere la validazione del CF  e contemporaneamente mantenere lo stesso IdSchedaANPR.

**Comment by frmariani** [comment]
Come mai ? il suo gestionale non lo permette ?
mi scriva in privato un contatto telefonico
frmariani@sogei.it

**Comment by frmariani** [comment]
non ho ricevuto nessuna comunicazione ma il CF è stato validato quindi ritengo che siano state sufficienti le indicazioni fornite.
