### ISSUE TITLE
[TestConn] SAML Security Implementation

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#28]
Buongiorno,
**Premessa:** vorrei eseguire in debug l'esempio fornito che effettua il test di connessione con l'asserzione SAML allo scopo di capirne meglio e più velocemente il funzionamento.
Sul mio RAD (Rational Application Developer 9.0) e sul mio Eclipse (MARS.2) non riesco a compilarlo perché il file necessita di un XSD contenuto in una libreria core (org.eclipse.wst.standard.schemas_1.0.502.v201303070140.jar) che contiene un carattere UTF-8 non valido. In effetti con una modifica manuale al JAR funziona, ma non vorrei andare incontro ad altre anomalie non previste.

**La domanda:** Su quale versione di Eclipse è possibile compilare il tutto senza problemi?
Grazie, Saluti!
GiuCal

**Comment by gcarbonin** [comment]
Allego una breve guida all'installazione (che pubblichiamo anche nell'ambiente di test). Mi faccia sapere se il problema è risolto.
Gina C.
[Guida all'installazione (test conn).pdf](https://github.com/italia/anpr/files/844393/Guida.all.installazione.test.conn.pdf)

**Comment by ANPRCdMI** [comment]
Avevo fatto tutto quanto scritto in quel documento, ma vedo che si porta come esempio Eclipse NEON.1, probabilmente con quella versione funzionerà senza l'intoppo descritto. Le farò sapere al più presto. Grazie
Saluti
GiuCal

**Comment by gcarbonin** [comment]
Va bene anche Marven

**Comment by ANPRCdMI** [comment]
Non ho provato altre verisoni di Eclipse, perché richiedono Java 8 e non ho la possibilità di rivoluzionare l'ambiente, il problema si è risolto in RAD 9.0 con lo stratagemma descritto e siamo andati avanti.
Abbiamo concluso transazini positive del servizio TestConn ora stiamo avendo qualche problema a far funzionare un vero servizio applicativo. Lo descriverò in una successiva Issue magari.
Grazie
GiuCal

**Comment by gcarbonin** [comment]
Grazie del riscontro
