### ISSUE TITLE
Aggiornamento massivo dati "listaelettorale"

### ISSUE THREAD

**Issue by niclup** [italia/anpr#280]
Attualmente l'aggiornamento dei dati in oggetto  può avvenire solo mediante il servizio [5008], individuo per individuo. L'utilizzo del servizio comporta una notevole generazione di operazioni ed a seconda dei contesti,  anche una notevole e noiosissima mole di lavoro da parte dell'ente. Non si può pensare ad un aggiornamento massivo delle posizioni degli elettori movimentati per ciascuna revisione, magari mediante un flusso alternativo?

**Comment by gcarbonin** [comment]
Se ho ben capito, quando il servizio elettorale del comune ha completato la revisione delle liste, occorre aggiornare in ANPR i dati relativi alla posizione del soggetto (tipoElettore e comune). Se questo è corretto, è prevista una nuova funzionalità (ancora da pianificare) per consentire l'upload di un file .csv con i seguenti dati:
- idsoggettoANPR
- cognome
- nome
- tipoeletttore.
La stessa cosa vale per le liste di leva.

**Comment by LucaBonini64** [comment]
L'upload di un file .csv è comunque un'operazione manuale, a mio modesto avviso sarebbe meglio un WS tipo quello esistente a cui posso passare massivamente tutti gli IdSoggetti delle persone coinvolte.

**Comment by gcarbonin** [comment]
la soluzione tecnicamente sarebbe analoga a quella del subentro: WS per l'upload del file o uploda tramite WA

**Comment by AMonopoliADS** [comment]
buongiorno.

chiedo se ci sono novità rigaurdo al tema aperto con questa issue.

per evitare l'invio manuale di ogni singola comunicazione (a Faenza, ambiente di produzione, ci sono circa 500 elettori iscritti con la seconda toranta...) stiamo tentando l'invio automatico di tutte le comunicazioni di aggiornamento della sola listaElettorale.
questa operazione, eseguita preventivamente in ambiente di test, dopo l'accettazione delle prime comunicazioni va in errore con questo messaggio:
Rejected by SLM Monitor (from client)
... per poi riprendere correttamente sulle stesse comunicazioni, se ripetute appena dopo.

immagino ci sia un controllo sulla numerosità delle transazioni.

è possibile avere qualche dettaglio in più?
lo scopo, ovviamente, è quello di rendere questa operazione di aggiornamento il meno complicata possibile per l'operatore.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Si accettano al massimo 5 operazioni al secondo dallo stesso comune. Per questo tipo di aggiornamento (liste elettorali leva e toponomastica) stiamo valutando la possibilità di un aggiornamento massimo (invio di un file contenente tutte le posizioni da aggiornare) con restituzione di un file di esito

**Comment by AMonopoliADS** [comment]
le comunicazioni vengono inviate con un ritmo di 1, max 2, al secondo... ma in ambiente di TEST persiste il messaggio "Rejected by SLM Monitor (from client)".
è possibile che dipenda da qualche altra condizione?

grazie

**Comment by Leonforte** [comment]
Salve, potrebbe specificare la frequenza al minuto ?

**Comment by AMonopoliADS** [comment]
ricordo, per non rischiare incomprensioni, che sto parlando dell'ambiente di TEST (comune di Faenza).
la stessa frequenza di invii, provata ieri in ambiente di PRODUZIONE (comune di Medicina) non ha dato problemi.
detto questo, non ho ho una valutazione "al minuto" perchè il problema si manifesta prima.
Le faccio un esempio di quanto appena tracciato nel tentativo di invio di 20 comunicazioni, delle quali 8 sono andate a buon fine e 12 in errore... x ogni comunicazione trova minuti e secondi di invio:
1. INFO  [25-01-2018 12:13:13] Risposta5008 not null
2. INFO  [25-01-2018 12:13:15] Risposta5008 not null
3. INFO  [25-01-2018 12:13:18] Risposta5008 not null
4. INFO  [25-01-2018 12:13:19] Risposta5008 not null
5. INFO  [25-01-2018 12:13:21] Risposta5008 not null
6. INFO  [25-01-2018 12:13:22] Risposta5008 not null
7. INFO  [25-01-2018 12:13:24] Risposta5008 not null
8. INFO  [25-01-2018 12:13:30] Risposta5008 not null
9. ERROR [25-01-2018 12:13:30] ERRORE ANPR - Rejected by SLM Monitor (from client)
10. ERROR [25-01-2018 12:13:31] ERRORE ANPR - Rejected by SLM Monitor (from client)
11. ERROR [25-01-2018 12:13:32] ERRORE ANPR - Rejected by SLM Monitor (from client)
12. ERROR [25-01-2018 12:13:33] ERRORE ANPR - Rejected by SLM Monitor (from client)
13. ERROR [25-01-2018 12:13:34] ERRORE ANPR - Rejected by SLM Monitor (from client)
14. ERROR [25-01-2018 12:13:34] ERRORE ANPR - Rejected by SLM Monitor (from client)
15. ERROR [25-01-2018 12:13:35] ERRORE ANPR - Rejected by SLM Monitor (from client)
16. ERROR [25-01-2018 12:13:36] ERRORE ANPR - Rejected by SLM Monitor (from client)
17. ERROR [25-01-2018 12:13:36] ERRORE ANPR - Rejected by SLM Monitor (from client)
18.  ERROR [25-01-2018 12:13:37] ERRORE ANPR - Rejected by SLM Monitor (from client)
19.  ERROR [25-01-2018 12:13:38] ERRORE ANPR - Rejected by SLM Monitor (from client)
20. ERROR [25-01-2018 12:13:39] ERRORE ANPR - Rejected by SLM Monitor (from client)

**Comment by Leonforte** [comment]
il problema dovrebbe essere risolto, può riprovare ?

**Comment by AMonopoliADS** [comment]
ho riprovato. 
non ho avuto casi (come nel precedente tentativo) di comunicazioni inviate nello stesso secondo, ma per tutte ho ottenuto risposta. 
grazie.

**Comment by busaster** [comment]
MI allaccio a questa discussione per avere un chiarimento. Anch'io mi scontro a volte con un blocco di SLM monitor. Quale può essere una buona regola per non cadere in questo problema ?

**Comment by Leonforte** [comment]
X AMonopoliADS - Ok, monitoriamo la situazione. Se riaccade ci informi, grazie
X busaster - ci dovrebbe specificare in quale ambiente, comunque abbiamo appena effettuato un tuning delle policy di sicurezza alzando il numero massimo di transazioni

**Comment by busaster** [comment]
la mia nota riguarda prove fatte in ambiente di test, in cui eseguo una ventina di chiamate al 3007 consecutive , facendo passare un secondo tra l'una e l'altra

**Comment by Leonforte** [comment]
ha provato recentemente ? le modifiche sono state fatte intorno alle 13.20.

**Comment by busaster** [comment]
oggi no, riproverò nel pomeriggio. 
Grazie
