### ISSUE TITLE
Servizi ANPR non rispondono

### ISSUE THREAD

**Issue by CSI-Piemonte-Demografia** [italia/anpr#2800]
AMBIENTE DI PRODUZIONE
Buongiorno,
da circa 15 minuti riscontriamo problemi di collegamento ai servizi di ANPR. Potete verificare?
Grazie.
Chiara Leanza per il Comune di Torino

**Comment by rinonasti** [comment]
Comune di CASERTA
IDEM

**Comment by FilippoPapi** [comment]
buongiorno
c'è stato un problema generalizzato. la situazione è tornata alla normalità intorno alle 12,50
