### ISSUE TITLE
A006 Iscrizione AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2802]
COMUNE DI CAPONAGO
VARISCO M.GIUSEPPINA

Inviando una richiesta di iscrizione AIRE , compare il seguente errore :+1: 

EN493 La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione  sul soggetto/famiglia

Di seguito le informazioni sull'operazione

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-09-09 10:30:27 , mittente 108052 , idOperazioneComune 20210909102749

Restiamo in attesa di conoscere le modalità per risolvere l'anomalia.
Cordiali Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
non abbiamo ricevuto un A006 con l'idoperazione comune indicato. L'ultimo A006 ricevuto è del 24 agosto. Sembrerebbe pertanto un problema del gestionale.
Per ulteriori richieste di assistenza relative al problema segnalato o più in generale a specifiche operazioni anagrafiche, cortesemente vi preghiamo di utilizzare il servizio di assistenza ANPR al numero verde 800863116.
