### ISSUE TITLE
[elenco operazioni] aggiornamento data definizione 

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2804]
Buongiorno, volevo un chiarimento sull'aggiornamento della data di definizione di una 2003 in elenco operazioni, 
la data si deve aggiornare dopo l'invio della 1014 di chiusura procedimento con la data effettiva di definizione pratica?
deve rimanere com'è stata inviata con la 2003?
si deve aggiornare in altra maniera?

il caso reale del comune 023065 in PRODUZIONE è 
1014 di apertura procedimento idOperazioneComune 20210703080841088
2003 idOperazioneComune 20210703080858948 dataDefinizionePratica 2021-07-03
1014 chiusura procedimento  idOperazioneComune 20210821095432541 dataChiusura 2021-08-21

in elenco operazioni per la cancellazione altri motivi c'è la data inviata con la 2003, quindi 03 luglio, il Comune invece si aspettava che dopo l'invio della chiusura del procedimento si aggiornasse con la data effettiva di chiusura ovvero il 21 agosto, dicono anche di aver sentito la vostra assistenza e che le è stato confermato che il gestionale avrebbe dovuto aggiornare la data.

in che modo è possibile farlo?

Grazie
Riccardo

**Comment by rvinzani** [comment]
La data di chiusura del procedimento non va a modificare la data inviata con il servizio di cancellazione ma viene presa in considerazione nell'invio delle statistiche ad Istat

**Comment by Hdemografici** [comment]
Come immaginavo
grazie 
Riccardo
