### ISSUE TITLE
Informazioni su Accesso WebApp dal 1 ottobre

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2805]
Comune di Villa Cortese

Buongiorno,
domanda forse sciocca: dal 1 ottobre cambierà qualcosa per l'accesso alla webapp? Ci sarà l'accesso ancora tramite SmartCard o SPID?

Grazie
Vignati

**Comment by FilippoPapi** [comment]
perchè dovrebbe cambiare qualcosa dal 1 ottobre?

**Comment by cvignati** [comment]
Per la soppressione dei metodi di autenticazione proprietari alla volta di SPID e CIE

**Comment by FilippoPapi** [comment]
buongiorno
la soppressione dei metodi di autenticazione proprietari alla volta di SPID e CIE riguarda l'accesso ai cittadini ai servizi digitali erogati dalle pubbliche amministrazioni. pertanto l'accesso alla web app di ANPR sarà ancora tramite SmartCard fino a quando non saranno modificate/integrate le regole di sicurezza previste dall'allegato c del DPCM 194/2014
