### ISSUE TITLE
Errore inserimento note in pratica di rettifica

### ISSUE THREAD

**Issue by lbevilacqua** [italia/anpr#2807]
Nell’inserimento di una richiesta di rettifica dati da parte di un cittadino, non è possibile inserire in prima istanza note, oppure il dato della provincia.

Nel mio caso specifico (richiesta 26770106) la provincia relativa al comune di nascita è errata. Per cercare di rettificarla ho inserito nei campi in cui era errata il comune scritto in “Questo Modo” anziché in “QUESTO MODO” come è presente attualmente, sperando che l’operatore capisca la necessità di una verifica dello stesso.

Questo non è avvenuto e la pratica è stata sospesa.

Provando (ora è possibile) ad inserire delle note, la form non viene inviata (e non compare alcun errore)

Dall’inspector riesco a vedere che la POST è fallita con un 400 Bad Request e che nel body della risposta è indicato che il testo inserito è troppo lungo.

Decido di fare un refresh per sicurezza e reinserire la nota: la mia richiesta è passata in stato aperto (più volte, le volte che ho cliccato su invia note) e non mi viene data più la possibilità di inserire le note.

Sto utilizzando la versione del sito in produzione, con accesso tramite CNS, browser Chrome 93 e sistema macOS 11.5.2.

**Comment by mttfranci** [comment]
Salve @lbevilacqua dovremmo aver individuato l'anomalia.
Ora il messaggio di errore sulla lunghezza del campo dovrebbe venir mostrato.
Inoltre la sua richiesta è stata riportato allo stato dove le dovrebbe essere possibile procedere all'integrazione.
Cortesemente può ricontrollare anche gli allegati in quanto c'era un problema su uno dei due ed è stato rimosso?
Siamo a disposizione per ogni ulteriore chiarimento.
Grazie in anticipo.
Saluti

Assistenza ANPR
