### ISSUE TITLE
Servizi al Cittadino - Purtroppo non is stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Spatuzzi** [italia/anpr#2809]
gentile signori,

Non riesco ad accedere al portale ANPR, compare sempre questo messaggio di errore Sono in contatto con il Comune di Pineto (TE), non hanno riscontrato problemi con la scheda anagrafica.  

Prime 6 cifre del codice fiscale: VNSJSS

Vi ringrazio anticipatamente e invio cordiali saluti.
![Screenshot_20210910-130644_Gallery](https://user-images.githubusercontent.com/90516477/132951725-e9e3b1d5-aba4-40b8-a2a1-ee241fb71421.jpg)

**Comment by diegorl** [comment]
Credo sia lo stesso problema che avevo io ed è stato risolto.
https://github.com/italia/anpr/issues/2683

**Comment by mttfranci** [comment]
@Spatuzzi 

Ci sembra di aver individuato la scheda.
Purtroppo in ANPR non sembra essere stato registrato il codice fiscale.
Il legame tra l'accesso SPID/CIE/CNS e la scheda anagrafica avviene, al momento, attraverso il codice fiscale.
Pertanto se tale dato non è presente, ANPR non è in grado di agganciare l'utente che accede alla proprio scheda anagrafica.
Potrebbe verificare con il suo comune se il codice fiscale risulta valido, correttamente registrato sia nel comune che in ANPR (per quanto raro, a volte può capitare anche che la banca dati locale del comune non sia allineata con il sistema centrale di ANPR).
Speriamo di esssere stati di aiuto.
Siamo a disposizione per ogni ulteriore chiarimento.

Saluti

Assistenza ANPR

**Comment by Spatuzzi** [comment]
@mttfranci salve, mi sono messo in contatto con il comune che ha risposto prontamente informandoli che hanno aggiornato la mia scheda anagrafica con il codice fiscale.  ora posso vedere i miei dati personali in ANPR.  grazie!

**Comment by Spatuzzi** [comment]
@diegorl l'assenza del codice fiscale sul mio scheda anagrafica ha generato il problema, ma è già stato risolto.  Grazie!

**Comment by mttfranci** [comment]
Perfetto, ci fa piacere.

Saluti

Assistenza ANPR
