### ISSUE TITLE
[5005] costituzione di nuova famiglia senza variazione di indirizzo

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#281]
salve.

il caso che poniamo è quello di un cambio di nucleo, all'interno dello stesso civico di residenza.
nello specifico può capitare nei casi di costituzione di stati di famiglia separati all'interno della stessa abitazione, oppure nel caso di enti che non gesticono il numero di interno nella definizione degli indirizzi.

a queste condizioni, l'utilizzo del servizio 5005 produce l'errore bloccante:
EN388 - La residenza inserita risulta uguale a quella attuale

come fare per realizzare una variazione di questo tipo?
è necessario utilizzare un altro servizio?

grazie.
Alessandro Monopoli ADS

(es. Ambiente di Test - Comune di Faenza - idOperazioneComune 2017001576)

**Comment by gcarbonin** [comment]
Dobbiamo analizzare il problema in quanto il controllo è necessario per evitare che siano trasmesso più volte la stessa variazione di residenza (cosa avvenuta in un comune già subentrato).
Per il primo caso (diversi nuclei famigliari che abitano nello stesso posto) si dovrebbe utilizzare un 5001 specificando che si tratta di famiglia coabitante.

**Comment by gcarbonin** [comment]
Dobbiamo introdurre un campo nella Listacontrolli del 5005 con il quale il comune chiede di registrare la variazione anche se l'indirizzo è lo stesso. Procediamo?

**Comment by gcarbonin** [comment]
Ci stiamo comunque ragionando ancora

**Comment by AMonopoliADS** [comment]
grazie del riscontro.

ho un dubbio però sull'uso del servizio 5001 per la questione delle famiglie coabitanti.

utilizziamo questo servizio (il 5001) per:
- cambio di indirizzo dell'intero nucleo (quindi senza variazione nelle relazioni dei componenti)
- sistemazione dei rapporti di parentela qualora esca dal nucleo l'intestatario scheda (nel caso la famiglia oggetto della variazione è quella di partenza, non la nuova famiglia costituita dal soggetto che esce, per la quale viene eseguito invece un 5005).

nel caso che abbiamo posto parliamo di componenti che creano una nuova famiglia, quindi partono da un nucleo già presente e ne costituiscono uno nuovo.
usiamo comunque il servizio 5001, indicando il nuovo numero di famiglia ed i componenti del nuovo nucleo di destinazione? 
come facciamo a specificare che si tratta di famiglia coabitante?
(ho provato a ri-controllare l'excel con le specifiche del servizio 5001 senza successo)

riguardo alla possibilità di utlizzare un campo nella listaControlli del servizio 5005, a mio parere è una strada assolutamente percorribile.

grazie.

**Comment by gcarbonin** [comment]
Abbiamo eseguito l'intervento: può riprovare e darmi un riscontro

Se nella mutazione viene indicato il trasferimento in una famiglia esistente ma allo stesso indirizzo di quella attuale, l’operazione viene bloccata e viene restituito un diagnostico (EN388 - La residenza inserita risulta uguale a quella attuale). Tale operazione può comunque procedere, se necessario, impostando nella lista controlli della richiesta i valori:
<listaControlli>
               <controllo>
                  <codice>FO</codice>
                  <valore>S</valore>
               </controllo>
            </listaControlli>

Se invece nella mutazione viene indicato il trasferimento in una nuova famiglia e viene indicato l’attributo
  <presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante>
anche allo stesso indirizzo di quella attuale, l’operazione va a buon fine.

Famigliaoabitante è un attributo gestito dal 5005 e non dal 5001 come da me erroneamente descritto.
Attendo un suo riscontro

**Comment by AMonopoliADS** [comment]
ho proceduto con alcuni test...
- alle condizioni iniziali permane l'errore bloccante... ok
- attivando il check presenzaFamigliaCoabitante, l'operazione va a buon fine
- con presenzaFamigliaCoabitante non attivo, ed il nuovo controllo FO-S, l'operazione va a buon fine.

il certificato storico di residenza viene come mi avevate anticipato: due righe con lo stesso indirizzo e le due date di decorrenza successive (l'iscrizione ed il cambio di abitazione)

segnalo solo che dalle specifiche excel non si capisce che la struttura del blocco listaControlli deve essere questa:
`<listaControlli>
    <controllo>
        <codice>undefined</codice>
        <valore>string</valore>
    </controllo>
</listaControlli>
`
nel foglio di excel il primo campo viene individuato con tag "nome"

grazie.

**Comment by bfilipazzi** [comment]
"Se invece nella mutazione viene indicato il trasferimento in una nuova famiglia e viene indicato l’attributo 
<presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante> 
anche allo stesso indirizzo di quella attuale, l’operazione va a buon fine."
Ma in questo modo per consentire la variazione si introduce un dato falso: l'indicatore di coabitazione.
Filipazzi - Maggioli

**Comment by AMonopoliADS** [comment]
a nostra interpretazione: 
- l'indicatore di coabitazione verrà utilizzato nei casi di reale coabitazione dei nuclei. l'informazione arriva dal gestionale e viene passata al web-service
- il nuovo controllo di forzatura, in tutti i restanti i casi di indirizzo non modificato (come, nell'esempio che si faceva, di comune che non rileva gli interni)

**Comment by bfilipazzi** [comment]
Mi spiego con un esempio: Padre, Madre e Figlio appartengono alla famiglia A, Figlio esce dalla famiglia A ed entra in nuova famiglia B allo stesso indirizzo, senza indicazione di diverso interno perché non gestito dall'ufficio. In questa fattispecie da specifiche si dovrebbe indicare la coabitazione, ma Figlio necessariamente si sposta in altro appartamento dello stesso stabile, perché se restasse in quello della famiglia A non potrebbe fare nuova famiglia, e se va in altro appartamento la coabitazione non c'è.

**Comment by AMonopoliADS** [comment]
in questa fattispecie l'operazione va a buon fine senza intervenire sul flag di coabitazione, ma aggiungendo nel blocco datiControllo questo elemento aggiuntivo:
`<listaControlli>
<controllo>
<codice>FO</codice>
<valore>S</valore>
</listaControlli>
`
che stanno ad indicare "forzatura della mutazione anche in presenza di indirizzo non variato".

**Comment by bfilipazzi** [comment]
Ringrazio per il chiarimento, ma nelle specifiche io leggo la frase che ho riportato 4 post fa.

**Comment by gcarbonin** [comment]
La documentazione non è stata aggiornata; provvederemo a farlo nei prossimi giorni, considerando che l'intervento è stato approvato.
La frase attuale, in ogni caso, indica che il sistema non da errori in presenza di indicazione da parte del comune che si tratta di una famiglia coabitante e, in nessun caso, "invita" ad utilizzare questo campo per bypassare il controllo.

**Comment by bfilipazzi** [comment]
La frase che ho commentato:
<< Se invece nella mutazione viene indicato il trasferimento in una nuova famiglia e viene indicato l’attributo
<presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante>
anche allo stesso indirizzo di quella attuale, l’operazione va a buon fine. >>
è presente nella versione delle specifiche di interfaccia del 5 settembre, ed è segnata come novità.

**Comment by ncapozzi** [comment]
La documentazione è stata aggiornata
