### ISSUE TITLE
Problema Invocazione Servizi Web Anpr

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#2811]
BuonGiorno,
Dal giorno 10 settembre 2021 abbiamo un problema in ambiente di produzione per il nostro cliente: Comune di Castellammare di Stabia 063024.
Qualsiasi invocazione dei servizi web della anpr fallisce con un messaggio di rejected policy.
Abbiamo Controllato i certificati e sono Ok.
Abbiamo controllato l'indirizzo pubblico del server con quello censito nel pannello di amministrazione della web app anpr, e ci siamo accorti che non era presente, lo abbiamo aggiunto (abbiamo salvato correttamente l'operazione )ma kmq continua a non essere visualizzabile nel pannello di amministrazione. 
L'IP pubblico è il seguente : 131.1.244.170
Potreste cortesemente fare una verifica?
Grazie.
Michele Caputo (Publisys S.P.A)

**Comment by Leonforte** [comment]
Buongiorno, il problema dovrebbe essere stato risolto, riprovate e fateci sapere, grazie

**Comment by mcaputo75** [comment]
Problema risolto. Grazie Mille.
