### ISSUE TITLE
Mutazione relazione di parentela contestuale al servizio 5008

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2813]
Buongiorno,

vorrei sapere se poteste valutare la possibilità di variare all'interno del servizio 5008 il dato relativa anche alla relazione di parentela, in modo che non sia necessario in fase di registrazione del dato di matrimonio effettuare due operazioni distinte: 5008 per caricare i dati di matrimonio e 5001 per modificare le relazioni di parentela.

Attendo gentile riscontro.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by rvinzani** [comment]
Mi dispiace Roberta, non è previsto almeno per il momento di modificare i servizi di ANPR se non per nuovi sviluppi o adeguamenti normativi
