### ISSUE TITLE
Certificazione: da bilingue ad italiana

### ISSUE THREAD

**Issue by AndreaAlessio** [italia/anpr#2814]
Sul portale ANPR, dopo aver ottenuto la stampa di un certificato bilingue, premendo il pulsante Altro certificato (rimangono a disposizione i dati dello stesso soggetto richiedente), deselezionando l’opzione Sloveno e scegliendo l’opzione vuota (italiana standard), si ottiene:
 
 
<img width="517" alt="errore_anpr" src="https://user-images.githubusercontent.com/90705781/133277032-a921b2f3-c47d-49b5-aae0-92167eef934e.png">

CODICE: EN489: la richiesta no risulta valida secondo i nuovi XSD (CAMPO/TIPO: 'tipoLinguaCertificato')

Saluti e grazie

**Comment by amollicone1982** [comment]
bug corretto
