### ISSUE TITLE
Collegamento codici fiscali non effettuabile riferimento ticket #2692 #2786

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2815]
buongiorno,

in riferimento alla vostra risposta vorremmo sottoporre alla vostra attenzione la situazione del soggetto che presenta, in Agenzia Entrate più posizioni, non tutte collegate tra loro.
Di conseguenza non è stato possibile eseguire nè la mutazione, nè la risoluzione dei disallineamenti a causa del seguente errore: "Altri soggetti individuati in AT dai NUOVI dati anagrafici, richiesta di variazione dati non effettuabile"

Il soggetto  presenta in Agenzia Entrate ben 3 codici fiscali, due numerici e uno alfanumerico.

Per dati precisi è possibile contattare L'Ufficiale d'Anagrafe Federica Dell'Anno 0544/482275 dalle 8.30 alle 12.30.

Cordiali saluti.

**Comment by frmariani** [comment]
Per problematiche specifiche l'ufficiale d'Anagrafe può contattare l'Assistenza ANPR al numero verde 800863116
