### ISSUE TITLE
Annullamento iscrizione di soggetto con CIE valida

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2816]
Comune di Modena - produzione

Buongiorno,
è stato iscritto con provenienza dall' estero un cittadino al quale è stata poi rilasciata una CIE. Da informazioni acquisite successivamente risulta che lo stesso soggetto è attualmente iscritto in altro Comune con generalità diverse (data e luogo di nascita) e  CF provvisorio; i dati corretti sono quelli in nostro possesso.
I colleghi dell' Anagrafe vorrebbero annullare la nostra iscrizione per poi effettuare la mutazione sul soggetto residente nell' altro Comune e correggere le generalità:  possono farlo senza invalidare la CIE? Una volta modificato il CF del soggetto la carta gli verrà associata automaticamente?

Grazie, cordiali saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Fornite indicazioni telefoniche
