### ISSUE TITLE
Accordo di fruizione - Sottoscrizione da parte di Ente locale per la consultazione tramite WA

### ISSUE THREAD

**Issue by minnellap** [italia/anpr#2819]
Gentilissimi,

sono un dipendente dell'ufficio CED di una Agenzia Regionale della Puglia interessata alla consultazione della ANPR tramite Web Application.

Ho provato ad inserire le mie credenziali (nella Richiesta di Accreditamento) per provare a verificare la presenza del mio Ente di appartenenza ma, nonostante l'Ente risulti correttamente censito nella banca dati dell'IPA, lo stesso non compare tra quelli disponibili per sottoscrivere un accordo di fruizione.

E' necessario fare un passaggio preventivo alla sottoscrizione di un accordo di fruizione oppure l'accesso non è stato ancora aperto a tutti gli Enti della PA?
E' possibile eventualmente sapere quando si prevede di estendere la consultazione della ANPR?

Grazie

**Comment by azabatta** [comment]
Buonasera,
come indicato anche in altre issue, ad esempio #2749 e #2773, al momento la piattaforma è stata aperta solo ad alcuni enti sperimentatori. Al termine del periodo di sperimentazione saranno resi noti i tempi per l’apertura a tutti gli altri enti/PA.
Saluti

Assistenza ANPR
