### ISSUE TITLE
[3003] Funzionamento strano del filtro per data 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#282]
Ambiente di Test (Poggio a Caiano).
Imposto un filtro per la ricerca delle operazioni avvenute in un giorno (per comodità dalle ore 1 alle ore 22:59:59) così :
`<dataOraIniziale>2017-09-06T01:00:00.000Z</dataOraIniziale>`
`<dataOraFinale>2017-09-06T22:59:59.000Z</dataOraFinale>`

La chiamata però va in errore : 
**EHR16** **Data finale della richiesta  07-09-2017 minore della data iniziale   06-09-2017 o maggiore della data di sistema  06-09-2017**

Ma la data finale specificata nel filtro non è 07/09/2017.

Potete verificare ?

**Comment by busaster** [comment]
Credo di aver capito il problema , la data finale essendo "nel futuro" causa l'errore.
Il messaggio mi ha tratto in inganno perché parla errroneamente di 7/09, dovrebbe riportare la data finale.
Mettendo come data finale l'istante di ricerca il problema non si verifica.

**Comment by gcarbonin** [comment]
Stavamo facendo proprio questa verifica. Mettendo data 5 settembre la cosa va a buon fine.
Sistemiamo il diagnostico

**Comment by gcarbonin** [comment]
Abbiamo approfondito e non c'è nulla da cambiare. la notazione 2017-09-06T22:59:59.000Z indica le 22 e 29 del 6 settembre UTC; l'ambiente ANPR ha come orario di riferimento l'ora italiana che attualmente è due ore in più rispetto all'ora UTC; quanto indicato impostando il diagnostico diventa le ore 24 e 59 del 7 settembre.
