### ISSUE TITLE
Rettifica indirizzo di subentro

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#2820]
Durante il tentativo di scissione di una famiglia il comune si è accorto di aver effettuato il subentro di 2 soggetti con civico sbagliato

Abbiamo tentato di utilizzare da webapp la funzionalità di RETTIFICA e DATI SUBENTRO ma permette solo la modifica della data di iscrizione e del toponimo

C'è modo di modificare il civico oppure occorre fare una variazione "vera" per portarli all'indirizzo corretto e poi procedere alla scissione ?

Grazie

**Daniel Carenzo**
_C&C Sistemi SRL_

**Comment by rvinzani** [comment]
Salve, dovete utilizzare il servizio di mutazione famiglia/convivenza e nella sezione tipo mutazione dovete selezionare la voce 
![image](https://user-images.githubusercontent.com/26482893/133806515-1a5390e4-353b-4d71-9a2a-29c37ced8fa3.png)
