### ISSUE TITLE
[1002] Iscrizione Per altri motivi - Cittadini scartati dal subentro

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#2823]
Buongiorno,
Ambiente di pre-subentro.
codiceistat ente  076063.
Sto implementando il servizio 1002 per il mancato caricamento di N cittadini in seguito al subentro. 
Esempio:
il soggetto X è residente dal 01-01-1980 e attualmente vive in una famiglia costituita il 01-01-2000 con data legame parentela dal 01-01-2020.
Il Problema è che mettendo come data decorrenza dell'operazione  01-01-1980 (Che poi dovrebbe essere la data di iscrizione) ottengo il seguente messaggio d'errore:

<errore>
                <codiceErroreAnomalia>EF056</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>La data decorrenza appartenenza alla famiglia  deve essere uguale alla data decorrenza dell'operazione</testoErroreAnomalia>
            </errore>.

Come faccio ad iscrivere il cittadino in anpr con la data di iscrizione corretta?(01-01-1980)

Michele Caputo.
Publisys S.P.A.

**Comment by rvinzani** [comment]
Gent.le Sig. Caputo, dalla data dell'iscrizione fino al 2000 il cittadino apparteneva ad una diversa famiglia? Sicuramente dal 1980 al 2000 deve essere associato ad una famiglia diversa dall'attuale.

**Comment by rvinzani** [comment]
Faccia fare un'indagine al comune per inserire la situazione reale al 1980. Successivamente effettuate una mutazione residenza alla data del 2000. Altrimenti inserite direttamente la data del 2000 e rimandate all'archivio locale la certificazione storica
