### ISSUE TITLE
 A006 Iscrizione AIRE #2802 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2824]
COMUNE DI CAPONAGO
VARISCO M.GIUSEPPINA

Buongiorno con riferimento alla ISSUE #2802 , sono riproporvi la segnalazione , sono giorni che cerco di contattare il numero 800 863 116 senza successo, rimango in attesa per ore ... vi chiedo cortesemente di prendere in cosiderazione questa segnalazione. Allego il file della richiesta A006 che inviamo ad ANPR ed il file che il vostr WS restituisce.

Nella precedente richiesta ci è stato risposto che l'identificativo dell'operazione non era presente nei vostri sistemi, strano in quanto scritto all'interno del file xml della risposta del WS ANPR.

Restiamo in attesa di gentile riscontro.

Salutio
[EsitoWS_RichiestaA006.txt](https://github.com/italia/anpr/files/7204376/EsitoWS_RichiestaA006.txt)
[RichiestaA006.txt](https://github.com/italia/anpr/files/7204377/RichiestaA006.txt)

**Comment by amollicone1982** [comment]
Tale errore sta ad indicare che il soggetto presente nelle generalità del servizio A006 non è presente in ANPR(La ricerca non produce risultati).
Per una verifica effettuate un 3002 (interrogazione) e verificherete che il soggetto non è presente in anpr
