### ISSUE TITLE
Download Notifiche Servizio 6001

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2825]
COMUNE DI CAPONAGO
REF. VARISCO M.GIUSEPPINA

Buongiorno
invocando il servizio 6001 per il download delle notifiche da ANPR , non viene scaricata la seguente notifica :

640040971	21-09-2021	NOTIFICA MUTAZIONE DI RESIDENZA	BERGAMO	Visualizza

Potete cortesemente indicarci il motivo ?

Restiamo in attesa di gentile riscontro.

Saluti

**Comment by amollicone1982** [comment]
Ci date l'id dell'operazione del 4003

**Comment by GabriellaBallabio** [comment]
L'ID dell'operazione 4005 è : 640676584
Grazie

**Comment by amollicone1982** [comment]
Si tratta di un 4005 che chiede tutte le notifiche dall'ora 01:00 del 20 settembre all'ora 01:00 del 21 settembre. La notifica in questione essendo stata elaborata il 21 settembre alle ore 09:30 non viene trovata
