### ISSUE TITLE
[Richieste cittadini - stampa pdf] caratteri Č e Ć

### ISSUE THREAD

**Issue by NBassan** [italia/anpr#2828]
Ambiente di produzione - riferimento richiesta di rettifica numero 25610018

I caratteri Č e Ć - che vengono visualizzati correttamente nell'interfaccia web - richiedendo la stampa pdf dei dati della richiesta vengono visualizzati nel pdf scaricato come #

**Comment by mttfranci** [comment]
Buongiorno @NBassan , dovremmo aver individuato l'anomalia, potrebbe verificare nuovamente il PDF? 
Saluti.
Grazie in anticipo.

**Comment by NBassan** [comment]
Buonasera, confermo che la soluzione implementata ha risolto il problema. Cordiali saluti
