### ISSUE TITLE
[cod.servizio 7002] Richiesta annullamento richiesta id ANPR 648392908

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2829]
Per conto Comune di Albairate.
A seguito di continue richieste cod.servizio 7002 non si ottiene nulla, Si chiede di annullare la richiesta in oggetto. ID ANPR 648392908.
Grazie.

Alberto Fiorentini
Halley Informatica

**Comment by amollicone1982** [comment]
Il 4001 con id 648392908 è in stato Completata con esito negativo. Non so cosa intendiate per annullare
