### ISSUE TITLE
[EAV31] CF presente ma dati anagrafici non congruenti

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#283]
Comune di Cesena ambiente subentro.
Inviando in ANPR l’Iscrizione per Nascita di una cittadina con **Gestione Codice Fiscale = Nessuna Operazione** si ha l’anomalia di Anagrafe Tributaria

**_Anomalia	EAV31	CF presente ma dati anagrafici non congruenti_**

Tale anomalia sta ad indicare che i dati in possesso di AE sono diversi da quelli del comune. Trattandosi di un nascita è probabile che nel frattempo dalla stesura dell’Atto di Stato Civile all'inserimento della variazione in anagrafe il padre della bambina abbia già provveduto a recarsi agli sportelli dell’Agenzia delle Entrate per richiedere il CF necessario per l’attribuzione del pediatra. E’ una casistica di errore molto comune che già affrontavamo in fase di invio delle comunicazioni in INA SAIA. 

Prima del subentro in ANPR si sarebbe proceduto accedendo in Punto Fisco e correggendo i dati da lì si sarebbe poi reinviata la comunicazione INA SAIA, dal momento del subentro la possibilità di variare i dati direttamente nella base dati di AE è stata inibita e le correzioni devono essere fatte direttamente nel sistema Anpr.

Nel documento che si puoi reperire all’indirizzo 

https://www.anpr.interno.it/portale/documents/20182/26001/Risoluzione+disallineamenti+con+lAgenzia+delle+Entrate+12_07_2017.pdf/4e20d751-4d3f-4a53-b23a-65b15686fffc

Per un codice anomalia che pare analogo si indica

Occorre in tal caso utilizzare la funzionalità di “Risoluzione disallineamenti con Agenzia Entrate” confermando i dati di AE oppure quelli di ANPR in funzione dell’esito dell’attività di verifica volta ad individuare quali siano i dati anagrafici corretti.

Questa funzione come descritto permette di confermare quale tra le due anagrafiche, quella presente in ANPR indicata dal Comune, e quella, in questo caso, presente in AE dichiarata dal papà sia quella corretta.

Tuttavia non permettendo l’anomalia EAV31 l’iscrizione in ANPR ricercando il codice fiscale in questione nella webapp si ottiene il messaggio di errore Soggetto non trovato

E’ corretto indicare al comune di procedere con l’invio in ANPR dell’operazione di iscrizione per nascita indicando Gestione Codice Fiscale = Iscrizione senza validazione  e poi procedere con la risoluzione del disallineamento?

**Comment by gcarbonin** [comment]
Va bene la seconda modalità:
1) iscrizione con gestioneCF = 3
2) accesso alla WEB application e Funzione di "risoluzione disallineamenti con Agenzia Entrate" confermando i dati del comune.
