### ISSUE TITLE
Problemi connessione con smart card a nuovo sito

### ISSUE THREAD

**Issue by briviopc** [italia/anpr#2830]
Buongiorno,
abbiamo dei problemi ad accedere al nuovo sito: Https://dp.anpr.interno.it/com.
il problema è riscontrato su diversi pc sia con firefox che con chrome, nonstante sia il lettore che la tessera sono riconosciute dal pc 
con chrome dopo aver dato invio sul sito, esce la richiesta di conferma del certificato di postazione, poi esce una schermata che dice: 
Il sito non può fornire una connessione protetta
dp2.anpr.interno.it non ha accettato il certificato di accesso oppure non ne è stato fornito uno.
•	Prova a contattare l'amministratore di sistema.
ERR_BAD_SSL_CLIENT_AUTH_CERT
e si blocca, non richiede nessun pin.

con firefox dopo invio passa dp2.anpr.interno.it
Connessione sicura non riuscita
Si è verificato un errore durante la connessione a dp2.anpr.interno.it. Il peer SSL non è stato in grado di negoziare un insieme di parametri di sicurezza accettabile.

Codice di errore: SSL_ERROR_HANDSHAKE_FAILURE_ALERT
    La pagina che si sta cercando di visualizzare non può essere mostrata in quanto non è possibile verificare l’autenticità dei dati ricevuti.
    Contattare il responsabile del sito web per informarlo del problema.
e non chiede pin.

ho provato a forzare su firefox il caricamento del modulo di sicurezza pk11, ma in questo caso chiede il pin ma non mostra il certificato di postazione.
in attesa di un Vs riscontro 
cordiali saluti

brivio piercarlo
comune di agrate brianza

**Comment by Leonforte** [comment]
Problema risolto in assistenza remota
