### ISSUE TITLE
Mancanza file C:\Windows\System32\stPKCS11.dll

### ISSUE THREAD

**Issue by TommasoIntini** [italia/anpr#2831]
Ciao a tutti,

apro questa issue in quanto non riesco a trovare la dll specificata nel titolo.
Ho provato ad aggiornare i driver del mio lettore bit4id ma non riesco comunque ad ottenere questa dll.
Durante l'avvio del programma CRS Manager mi esce il seguente avviso: 
Si è verificato un errore durante la fase di diagnostica.
Non è presente il file richiesto: C:\Windows\System32\stPKCS11.dll.

Qualcuno ha qualche idea per risolvere questo problema?
Sapete se solo alcuni lettori mettono a disposizione questa dll oppure mi sono perso qualche pezzo?

Ringrazio in anticipo
Tommaso

**Comment by Leonforte** [comment]
Buongiorno, ha provato ad installare i driver della smart card ? IDProtectMonitor per le carte Aruba o DikeGoSign per quelle Infocert ?
