### ISSUE TITLE
Ripristino codice fiscale precedente

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#2832]
Buongiorno,
per un errore,  dobbiamo ripristinare un codice fiscale che, al momento, risulta collegato a un nuovo codice fiscale.
Ad oggi, in AE e in ANPR c'è lo stesso codice fiscale ma è quello sbagliato (riporta Z255 anzicheè Z152).
Abbiamo provato a fare la modifica da "Mutazione tutti i dati" ma ci restituisce l'errore che allego. Si sottolinea che i dati anagrafici della persona (nome, cognome, data di nascita e luogo di nascita - Kazakhstan - NON sono cambiati).

Grazie, cordiali saluti
Katia
![Cattura](https://user-images.githubusercontent.com/57749903/135041388-4c58084c-20bf-48f3-94d4-b22fa089db40.JPG)

**Comment by frmariani** [comment]
Il codice stato 356 da voi inserito nelle generalità da modificare, si riferisce allo stato attuale Z255;
per inserire come luogo di nascita uno stato storico, dovete inserire il codice stato 998.
nel caso mi invii un recapito telefonico al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
la issue è in risoluzione per le vie brevi pertanto viene chiusa
