### ISSUE TITLE
Problemi connessione ambiente di test

### ISSUE THREAD

**Issue by FStefano** [italia/anpr#2833]
Buongiorno,
si sono verificati problemi di accesso nell'ambiente di test del Comune di Crevalcore provando ad accedere sia con le credenziali di utente e password dell'ALS (https://dptest.anpr.interno.it/combas) , sia con smart card (https://dptest.anpr.interno.it/com).
Tentando di accedere con utente e password otteniamo il seguente errore:

![image](https://user-images.githubusercontent.com/55198772/135061582-0796b119-ef81-4ab6-800c-b589398463bd.png)

Provando ad accedere con smart card (non lo avevamo mai  fatto in passato per l'ambiente di test) otteniamo un errore differente ma il risultato è il medesimo: non si riesce ad accedere.

E' possibile risolvere? esistono altre modalità di accesso? 
Grazie

Stefano Ferrari
Palitalsoft

**Comment by Leonforte** [comment]
Buongiorno, dall'elenco utenti dell'ambiente di produzione non risulta alcun ALS nominato dal Sindaco come da procedura standard. La nomina ad ALS in ambiente di produzione consente la registrazione dello stesso utente ALS in ambiente di test.
Cordiali saluti

**Comment by FStefano** [comment]
Buongiorno,
abbiamo controllato le autorizzazioni ed osservando l'elenco degli utenti sembrava che nessuno fosse effettivamente l'ALS.
Andando nel dettaglio dell'utente però ci siamo accorti che l'autorizzazione risultava già spuntata. Abbiamo, quindi, confermato nuovamente le autorizzazioni per tale utente e ora anche nell'elenco appare come ALS.

![image](https://user-images.githubusercontent.com/55198772/135235826-6a3c9ffa-ede4-4ef8-bf7b-5b94212a171a.png)

![image](https://user-images.githubusercontent.com/55198772/135235868-4ea53930-9d6c-4b9c-8231-32cdcd8bca1c.png)

Dopo di che abbiamo riprovato ad accedere all'ambiente di test con utente e password ottenendo lo stesso errore di autenticazione dei giorni scorsi. Abbiamo ripulito la cache del browser (Google Chrome) e riprovato a fare l'accesso dopo qualche minuto ricadendo di nuovo nello stesso errore.

Ci sono altri controlli/attività che possiamo fare per sbloccare la situazione?

Grazie

**Comment by Leonforte** [comment]
Buongiorno, abbiamo registrato due tentaivi di accesso ieri 29 settembre alle ore 10.37 e 10.40 con password errata.
La password è la stessa comunicata inizialmente per l'ambiente di produzione, la metà presente nella lettera di accompagnamento alla smartcard e la seconda metà inviata via mail al momento dell'attivazione della carta.

**Comment by Leonforte** [comment]
Ad ogni buon fine la seconda metà delle credenziali è stata rinviata a graziella.fanton@comune.crevalcore.bo.it
Buon lavoro, saluti

**Comment by FStefano** [comment]
Ringrazio per l'inoltro della seconda metà delle credenziali. Le abbiamo confrontate con quelle arrivate il 23 ottobre 2019 e risultano identiche.
Abbiamo fatto alcune prove di accesso intorno alle ore 13 invertendo l'ordine di inserimento delle due metà della password, modificando un carattere (per toglierci ogni dubbio su una possibile errata interpretazione del carattere) e almeno un inserimento corretto. Otteniamo sempre lo stesso errrore.

Siamo sicuri di avere inserito anche la prima metà corretta. 
Potrebbe esserci una differenza tra la prima parte della password presente nella lettera di accompagnamento e la password presente nei sistemi?

Le lascio il mio contatto email per ulteriori chiarimenti: s.ferrari@palitalsoft.it

Grazie

**Comment by FStefano** [comment]
Problema risolto. 
Grazie per l'intervento
