### ISSUE TITLE
Certificato per ambiente test

### ISSUE THREAD

**Issue by FStefano** [italia/anpr#2834]
Buongiorno,
dovremmo  eseguire un invio di dati nell'ambiente di test per il Comune di Terre Roveresche ma purtroppo hanno perso il certificato e la relativa password.

Esiste un modo per recuperarli inviandoli direttamente al Comune?

Grazie

Stefano Ferrari
Palitalsoft

**Comment by Leonforte** [comment]
Buongiorno, il certificato è stato iniviato all'indirizzo del Sindaco sindaco@comune.terreroveresche.pu.it
Buon lavoro, saluti
