### ISSUE TITLE
ALLINEAMENTO CODI FISCALE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2835]
Buonasera, COMUNE DI CASERTA (PROD)

Stiamo cercando di variare la data di nascita di un cittadino 
EAM9C - Individuate due posizioni in AT non unificate: procedere con il collegamento dei due codici fiscali se si tratta dello stesso soggetto, o con la richiesta di omocodia se il soggetto e' diverso
 
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-09-30 15:01:41 , idOperazioneANPR 651799684
Cortesemente ci date supporto su come procedere
Grazie

**Comment by frmariani** [comment]
Questo errore vi avvisa che già esiste un codice fiscale contenete i dati anagrafici che state modificando, pertanto l'operazione non può andare a buon fine;
a questo punto dovete effettuare un'indagine per capire se il codice fiscale presente in Agenzia delle Entrate e contenente le nuove generalità appartiene al vostro cittadino o se si tratta di un altro cittadino; 
nel primo caso dovete prima eliminare l'operazione sospesa con l'errore prodotto e poi effettuare il collegamento dei due Codici Fiscali attraverso la funzionalità "Risoluzione disallineamenti con AE"; nel secondo caso dovete richiedere l'omocodia.
In ogni caso potete contattare l'assistenza ANPR al numero 800863116

**Comment by rinonasti** [comment]
Grazie siamo in contatto con il supporto.
