### ISSUE TITLE
ERRORE PRE-SUBENTRO - COMUNE DI PANTIGILIATE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2837]
COMUNE DI PANTIGLIATE

RIF.: CALORI ROBERTA

Buongiorno abbiamo effetuato il pre-subentro e stiamo verificato le diverse segnalazioni di anomalie riscontrate, non bloccanti.

Abbiamo ricevuto un'e-mail da assistenza.anpr@pec.sogei.it che ci inviatava a scaricare un elenco schede duplicate in altri comuni subentrati. 
A seguito dipuntuali verificate ci è stato possibile stabilire che tutte le schede solo relative a cittadini attualmente residenti nel nostro comune e che quindi gli altri comuni non hanno provveduto a cancella i soggetti.

Questa situazione è bloccante rispetto al nostro subentro già fissato per il 14.10 ?

Restiamo in attesa di gentile riscontro.

Saluti

**Comment by amollicone1982** [comment]
Assolutamente non bloccante. si tratta di warning relativi ad eventualui schede duplicate che, quando subentrerete, dovrete analizzare per capire se il soggetto duplicato è presente o meno nel vostro comune.
In presubentro ignorate la segnalazione in quanto i dati dei comuni presubentrati non sono sicuramente allineati.
