### ISSUE TITLE
[Servizio 4001] Richiesta di risposta non ancora non disponibile (codice errore EN122)

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2839]
Ho inviato una richiesta 4001 con ID ANPR richiesta **654516689** alle ore **09.29** di oggi 04.10.2021, alle ore 10.09 non riesco a ottenere esito positivo con servizio 7002 di risposta. Mi sembra che i tempo siano un pò lunghi... Di solito si ottiene la risposta in 15 - 20 minuti. Si allega xml di richiesta e xml di risposta.
Grazie.

Per il Comune di Fontaneto d'Agogna
Alberto Fiorentini - Halley Informatica
[risposta.txt](https://github.com/italia/anpr/files/7276558/risposta.txt)
[richiesta.txt](https://github.com/italia/anpr/files/7276560/richiesta.txt)

**Comment by tuchino1969** [comment]
**AGGIORNAMENTO** del **04-10-2021** ore **11.28**: ANCORA **NESSUNA RISPOSTA DISPONBILE,** si sollecita la risuluzione.

**Comment by tuchino1969** [comment]
**AGGIORNAMENTO** del **04-10-2021** ore **12.26**: ANCORA NESSUNA RISPOSTA DISPONBILE,, permane errore  si sollecita la risoluzione.

**Comment by amollicone1982** [comment]
risposta disponibile
