### ISSUE TITLE
EAV31 CF presente ma dati anagrafici non congruenti

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#284]
Operazione di Iscrizione altri motivi cittadino proveniente da estero il cui Codice Fiscale va in omocodia con un codice fiscale già presente in AT di altro cittadino.

Come comportarsi?

Inviando l'operazione con Gestione Codice Fiscale = Nessuna Operazione si è avuto un messaggio di anomalia che stava ad indicare la presenza di un CF in omocodia (purtroppo non ho il codice di errore specifico).

Si è quindi inviata l'operazione con Gestione Codice Fiscale = Richiesta omocodia ma si è avuto un altro messaggio di errore. (anche qui non ho il codice anomalia specifico)

Alla fine l'ente per sbloccare l'operazione di iscrizione ha proceduto con Gestione Codice Fiscale = Iscrizione senza validazione (completando tra l'altro l'operazione non potendola quindi più annullare).

Ora qualsiasi mutazione dati per il cittadino è bloccata dall'anomalia in oggetto.

CF di riferimento SLMZRL87R25Z249H

**Comment by gcarbonin** [comment]
E' opportuno non indicare dati personale in questo sito.
Ci sentiamo telefonicamente per chiarire la situazione.

**Comment by RBiasi** [comment]
la contatto io?

**Comment by gcarbonin** [comment]
si

**Comment by gcarbonin** [comment]
A seguito del contatto telefonico , è stato appurato che si tratta di persone con permesso di soggiorno valido 6 mesi per richiesta protezione internazionale. In questi casi, gli interessati  fanno domanda direttamente alla polizia di Frontiera o alla Questura che rilasciano  un attestato nominativo, in attesa del permesso di soggiorno per richiesta asilo ( "rilasciabile"  entro 30 giorni").

Dopo avere effettuato gli accertamenti, Il Prefetto stabilisce un luogo di residenza o un’area geografica dove i richiedenti possono muoversi. 
Nelle more, è possibile richiedere l’attribuzione del codice fiscale numerico provvisorio (la nuova procedura è attiva con la comunicazione n. 8 del 26 luglio 2016 dell’Agenzia delle Entrate), anche per poter effettuare l’iscrizione al Servizio Sanitario Nazionale.: il  richiedente, infatti, ha diritto alle prestazioni sanitarie in esenzione alla compartecipazione alla spesa. 

Sono necessarie verifiche e chiarimenti normativi

**Comment by gcarbonin** [comment]
E' possibile verificare se con le nuove funzionalità di risoluzione disallineamento con l'Agenzia delle Entrate questo problema è sanato?
