### ISSUE TITLE
RISOLUZIONE CIRCOLARE 76/2021 ALLINEAMENTO CF CITTADINI NATI IN ISTRIA

### ISSUE THREAD

**Issue by Cingolani** [italia/anpr#2840]
Buongiorno,
sono Luca Cingolani del Comune di Falconara Marittima (AN)
si richiede la procedura corretta da seguire nel caso sotto descritto.
In ANPR è iscritta una nostra residente a cui è stato variato il comune di nascita, prima del subentro, da Dignano d'Istria (Jugoslavia), come da risultanza anagrafica, in Jugoslavia (senza indicazione del Comune di nascita). Dal codice fiscale risulta nata in Jugoslavia.   ID Anpr è 95505632
Dalla verifica effettuata dal ministero con l'emanazione della circolare 76 non è emerso il nominativo tra quelli da variare. Essendo evidente che il caso rientra in quello contemplato dalle disposizioni richiamate si chiede se dobbiamo procedere, previa rettifica del comune di nascita, allo stesso modo indicato dalla circolare, apportando d'ufficio la modifica del codice fiscale anche senza il consenso dell'interessata, alla quale la rettifica del codice fiscale comporterà inevitabili disagi.

**Comment by ncapozzi** [comment]
Buonasera,
la cittadina indicata non è stata riportata nell'elenco delle posizioni anomale in quanto nella situazione attuale risulta genericamente nata in JUGOSLAVIA senza ulteriore indicazione della località di nascita. Se effettivamente la signora è nata a DIGNANO D'ISTRIA la posizione deve essere trattata come da Circolare  ministeriale. Si evidenzia in particolare quanto segue

"Atteso che la modifica del luogo di nascita comporta la variazione del Codice Fiscale, i comuni
interessati dovranno, **preventivamente, informare i cittadini çoinvolti,** quindi aggiornare i dati per
renderli coerenti con la normativa suindicata ed inviarli all'Anagrafe Nazionale3 , con le consuete
procedure.
