### ISSUE TITLE
NUOVE UTENZE - Manuale/guida online

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#2845]
Buongiorno,
c'è un manuale/guida online che descrive le operazioni per attivare una nuova utenza (Sindaci appena eletti) ? 
Al link https://www.anpr.interno.it/il-progetto/strumenti-di-lavoro/guida-ad-anpr/step-5/ si fa riferimento al censimento degli utenti pre-subentro, ci sarebbe una guida specifica per le nuove attivazioni di Comuni già in ANPR da tempo?
Grazie

Cordiali saluti

**Comment by cmigliardi** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori chiarimenti si prega di aprire una nuova issue che faccia riferimento a questa stessa.
