### ISSUE TITLE
Difficoltà ad entrare in ANPR

### ISSUE THREAD

**Issue by carmela2021** [italia/anpr#2849]
Buongiorno, ho difficoltà ad entrare in ANPR
Potete aiutarmi? se vi possono essere utili ecco le prime sei lettere del mio cod.fiscale: CMBCML (nata a REGGIO CALABRIA e residente nel comune di CAMPO CALABRO) 
Quando provo ad entare mi dice cosi': Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

**Comment by mttfranci** [comment]
Salve lei ha provato a verificare con il comune di residenza se ci sono anomalie nella scheda?
In effetti sembra esserci una anomalia nel dato presente su ANPR.
Saluti

**Comment by carmela2021** [comment]
Buongiorno, sono andata qualche giorno fa al comune ho spiegato il tutto ed
hanno aggiornato la scheda in Anpr, perché prima non risultava aggiornata.
Potete aiutarmi voi a risolvere questo problema? Di questa anomalia che
risulta esserci?
Grazie anticipatamente

Il Gio 7 Ott 2021, 18:15 Matteo ***@***.***> ha scritto:

**Comment by mttfranci** [comment]
“In ANPR il soggetto risulta cancellato. In questi casi non è possibile accedere al servizio.
Se secondo il gestionale comunale lei risulta attualmente residente, dovrebbero verificare l’allineamento con ANPR centrale

**Comment by vinbia** [comment]
Buonasera, scrivo in quanto sto provando personalmente e con mia moglie i servizi ANPR.
Mentre per me funziona tutto ok, per mia moglie non si riesce ad accedere.
L'unico motivo di questa malfunzione potrebbe essere un errore nel CF, in quanto agli inizi degli anni 2000  a causa delle indipendenza della Eritrea le Entrate hanno generato per lei un codice fiscale (sono state modificati gli ultimi digit del CF).
Con quel nuovo codice fiscale lei accede a tutti i servizi delle entrate.
Da cittadina, cosa deve fare ed a chi deve rivolgersi per verificare se questo è il problema ?
Grazie

**Comment by ElisaBlangini** [comment]
Ciao. 
Ho lo stesso problema del # 2849. 
Sono nato in Argentina ed elabora lo SPID con i dati del codice fiscale. 
Le prime 6 lettere sono BLNLSE

**Comment by vinbia** [comment]
> Ciao. Ho lo stesso problema del # 2849. Sono nato in Argentina ed elabora lo SPID con i dati del codice fiscale. Le prime 6 lettere sono BLNLSE

Salve Elisa.  Noi abbiamo risolto il problema di mia moglie come segue:
1) abbiamo scritto via PEC al responsabile del nostro municipio di appartenenza, spiegando quanto avvenuto al codice fiscale di mia moglie (cambio paese causa indipendenza), accludendo copia del vecchio CF, del rilascio del nuovo CF dal MEF, copia della tessera sanitaria con il nuovo codice fiscale,
2) in tre giorni avevano corretto il tutto, dovuto a dir loro da una mancata comunicazione tra gli enti
3) siamo riusciti ad entrare nel sistema: funzionava tutto, tranne il fatto che erano spariti gli estremi dell'atto di nascita
4) abbiamo riscritto una altra PEC, agganciandoci alla precedente, allegando un copia di un vecchio certificato di nascita in nostro possesso
5) il responsabile del municipio ci ha contattati per comunicarci che il problema non poteva essere risolto se non attraverso l'interessamento della SOGEI (gestore del sistema ANPR) e che avevano passato alla Sogei il problema
6) dopo una settimana, verificando di giorno in giorno, abbiamo visto finalmente il nostro problema risolto.
Provi a seguire la stessa strada !!

**Comment by miki377** [comment]
Codice fiscale CTLMHL

**Comment by MarioPollio** [comment]
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica

COD.Fisc. 1D643H

Grazie anticipatamente per l'attenzione

**Comment by vinbia** [comment]
Grazie
IL problema è stato risolto dalla anagrafe centrale di roma, era dovuto a riemissione codice fiscale per variazione codice paese

 

 

Da: MarioPollio ***@***.*** 
Inviato: mercoledì 1 giugno 2022 13:58
A: italia/anpr
Cc: vinbia; Comment
Oggetto: Re: [italia/anpr] Difficoltà ad entrare in ANPR (#2849)

 

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica

COD.Fisc. 1D643H

Grazie anticipatamente per l'attenzione

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Difficoltà ad entrare in ANPR (#2849)" inviata il 01/06/2022 13:58:01.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by MarianaCarlana** [comment]
Buon giorno.

Ho il seguente messagio quando provo a fare il acesso: "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica"

Il mio codice fiscale è: CRLMNN

![image](https://user-images.githubusercontent.com/113166885/189291830-54d43c3f-f9fb-43b2-b4df-53381c48405f.png)

Per favore, potreste aiutarmi? @mttfranci @vinbia

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Difficoltà ad entrare in ANPR (#2849)" inviata il 01/06/2022 14:20:17.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by vinbia** [comment]
Continuo a ricevere periodiche mail sul “ticket” da me aperto a suo tempo
Segnalo che il problema è stato risolto !!!
Grazie



 

Da: COlivatoADS ***@***.***> 
Inviato: martedì 11 ottobre 2022 11:14
A: italia/anpr ***@***.***>
Cc: vinbia ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/anpr] Difficoltà ad entrare in ANPR (#2849)

 



Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio "Re: [italia/anpr]
Difficoltà ad entrare in ANPR (#2849)" inviata il 01/06/2022 14:20:17.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by MarianaCarlana** [comment]
Buon giorno! Il problema continua a succedere.
.[image: image.png]

**Comment by vinbia** [comment]
Ho già risposto diverse volte al ripetersi della ricezione di questo messaggio, il problema è risolto !!!!!!

Grazie

 

 

Da: MarianaCarlana ***@***.***> 
Inviato: sabato 15 ottobre 2022 11:13
A: italia/anpr ***@***.***>
Cc: vinbia ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/anpr] Difficoltà ad entrare in ANPR (#2849)

 

Buon giorno! Il problema continua a succedere.
.[image: image.png]

**Comment by MarianaCarlana** [comment]
Signorina, il problema NON é risolto. Non riesco ancora ad accedere al
servizio. E chiaro?
Ecco perché ho inviato lo screenshot.

Grazie.

**Comment by vinbia** [comment]
Ascolti, non so cosa stia accadendo!
Aprii una segnalazione su github in quanto non riuscivo a entrare in ANPR

A seguito di una vs risposta mi era stato chiesto di contattare direttamente il comune

Il comune di residenza mi disse di sentire il comune di registrazione della nascita

Il problema era legato alla mancata associazione del certificato di nascita con il codice fiscale che a causa di una scissione territoriale era stato cambiato dal MEF.
Il dipendente del comune di nascita ha collegato certificato di nascita e nuovo codice fiscale e tutto si è risolto.

Leggo nella risposta “Signorina, il problema NON é risolto. Non riesco ancora ad accedere al
servizio. E chiaro?
Ecco perché ho inviato lo screenshot.”
come se io fossi una persona che sta lavorando al problema !!!  io sono un “cliente”, ho avuto un problema, e per quanto mi riguarda è risolto

Ignorerò tutti i messaggi a seguire sull’argomento

 

Cordialmente

 

 

Da: MarianaCarlana ***@***.***> 
Inviato: sabato 15 ottobre 2022 13:57
A: italia/anpr ***@***.***>
Cc: vinbia ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/anpr] Difficoltà ad entrare in ANPR (#2849)

 

Signorina, il problema NON é risolto. Non riesco ancora ad accedere al
servizio. E chiaro?
Ecco perché ho inviato lo screenshot.

Grazie.
