### ISSUE TITLE
Richiesta aggiornamento dati CIE

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#285]
Buongiorno,

abbiamo verificato che i dati delle CIE emesse dal Comune attraverso il software ministeriale vengono correttamente aggiornati in ANPR, siamo a richiedere la possibilità di avere apposito file csv contenente i dati delle CIE emesse dal Comune dalla data di subentro in modo da allineare la ns. Banca Dati di Servio.

E’ disponibile un servizio di notifica per l’aggiornamento di questo dato?

**Comment by gcarbonin** [comment]
da chiarire telefonicamente le esigenze del comune

**Comment by gcarbonin** [comment]
#232

**Comment by gcarbonin** [comment]
Chiuso e collegato alla issue #405
