### ISSUE TITLE
Anomalia EN531 - idOperazioneANPR 659526638 

### ISSUE THREAD

**Issue by ColognoAlSerio1** [italia/anpr#2854]
Buongiorno,

ci risulta impossibile concludere l'operazione datata 2021-10-08 12:10:29 , idOperazioneANPR 659526638 per anomalia EN531.

Contattato il comune di comune URGNANO (BG) per cui risulta aperta la pratica ANPR: 37094618, ma non riescono a procedere con la definizione del procedimento.

Potete contattare voi il comune?

Grazie mille

Ufficio Anagrafe Comune di Cologno al Serio

**Comment by frmariani** [comment]
il procedimento è stato chiuso, potete procedere con il cambio di residenza
