### ISSUE TITLE
[6001] anomalia in certificazione soggetti residenti

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#2858]
Buongiorno

Il Comune di Vado Ligure si è accorto di una strana anomalia
Stampando un certificato di un soggetto residente e con pratica di immigrazione conclusa con successo viene indicato:
"Visti i dati registrati COMUNE DI QUILIANO"
Allego certificato ripulito dai dati sensibili
![certificato](https://user-images.githubusercontent.com/74978805/137101357-c01ba905-3bfd-4bb2-a30e-04508c65ff89.jpg)

Facendo delle prove sembra che succeda solo con i soggetti prevenienti da questo comune
Mi dicono che l'unica cosa "strana" è che Vado Ligure e Quiliano hanno stesso CAP, ma non so dipende da questo

Attendo riscontro

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by DanielCarenzo** [comment]
> Grazie per la segnalazione, potreste fornirci il protocollo del certificato, l'id operazione anpr dell'invocazione del 6001? Saluti
> 
> Assistenza ANPR

Buongiorno,

l'ID è il seguente: 663960207

**Comment by mttfranci** [comment]
Salve, dovremmo avere idividuato e corretto l'anomalia che si verificava in alcuni casi particolari.
Avete modo di riprovare l'emissione sullo stesso soggetto (anche in anteprima volendo)?

Saluti

Assistenza ANPR
