### ISSUE TITLE
VALIDITA' CERTIFICAZIONE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2859]
COMUNE DI CAPONAGO
MGIUSEPPINA VARISCO

Volevo sapere se è vero che **l'unica banca dati che può certificare ad oggi le posizioni anagrafiche, così come disciplinato dalla legge è ANPR.**
La mia anagrafe locale è allineata con ANPR, in quanto le variazioni vengono gestite PRIMA in Anagrafe Locale e poi inviate ad ANPR tramite WS, è vero che i certtificati che produco con Anagrafe Locale non hanno alcuna validità ? o comunque che il mio comune non può certificare ?
Resto in attesa di riscontro.
Saluti

**Comment by GabriellaBallabio** [comment]
Buongiorno
scusate il disturbo ma dovrei dare una risposta , per pianificare alcune attività ... potete darmi indicazioni in merito alla issue #2859 ?
Grazie

**Comment by FilippoPapi** [comment]
il DPCM 194/2014 prevede che i certificati debbano essere emessi da ANPR
buona serata
