### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by CaioMalassise** [italia/anpr#2860]
Buon giorno! quando provo ad accedere ad anpr con il mio spid, compare il seguente messaggio di errore:

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:
Il tuo comune di residenza (o di iscrizione all'AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione "A che punto è il tuo Comune?" disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

Codice Fiscale:BZMCAI_________
![Screenshot_20211013-205913-063](https://user-images.githubusercontent.com/92491555/137228878-c72fd142-942a-4f12-8f34-654b7be0439a.png)

**Comment by mttfranci** [comment]
Salve, sembrerebbe che al suo codice fiscale non sia associata nessuna scheda in ANPR.
Dovrebbe verificare con il suo comune di residenza (se residente in Italia) o di iscrizione AIRE (se residente all'estero).
Saluti

Assistenza ANPR
