### ISSUE TITLE
Configurazione utente già censito in un altro comune

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2862]
Dovrei aggiungere un utente già censito in un altro comune e quindi già in possesso di una propria smartcard, entrando nella WA con la smartcard del Sindaco (stesso problema se entro con la smartcard dell'ALS), vado ad aggiungere un nuovo utente e mi da errore: **_Errore CAST Inserimento/Registrazione Nuovo Utente_**
Come posso risolvere?

**Comment by Hdemografici** [comment]
Buongiorno, si tratta del comune di Campospinoso (PV)

**Comment by Leonforte** [comment]
Buongiorno, la registrazione dell'utente è stata effettuata d'ufficio, vi suggeriamo di ricontrollare i profili assegnati, buon lavoro, saluti
