### ISSUE TITLE
Certificati on-line rilasciati tramite il portale dei servizi ANPR

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#2866]
Mi collego alla segnalazione  #2759 chiedendo un ulteriore aggiornamento riguardo le tempistiche di rilascio del servizio in oggetto in quanto la richiesta dei cittadini è sempre più pressante e se i tempi di rilascio del servizio dovessero essere troppo lunghi dovremo trovare un'alternativa con la nostra software-house.
Grazie e saluti.

**Comment by FilippoPapi** [comment]
buongiorno
siamo in attesa dell'emanazione del Decreto del Ministero dell'Interno che dovrebbe avvenire nei prossimi giorni
cordiali saluti
