### ISSUE TITLE
 Problemi con endpoint Comunali ambienti di test e presubentro

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2867]
Buongiorno, 

dal giorno 10 ottobre scorzo non riceviamo più sull’endpoint comunali degli ambienti di Test e PreSubentro le notifiche N010, anche il test di inoltro delle notifiche da WebAPP ci restituisce un errore: Errore nell'invio della notifica di test.

Sarebbe possibile una verifica sui Vs. sistemi?

Ringrazio in anticipo e rimango a disposizione per eventuali chiarimenti.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by amollicone1982** [comment]
Può specificarci il comune per cui non le riceve?
