### ISSUE TITLE
Stato estero presente nella località estera di nascita

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#2869]
Buongiorno,
sono Nozzoli Arianna del Comune di Prato in produzione.
Vorrei segnalare questo problema nei dati presenti in ANPR su cittadini di molti comuni. Ci siamo accorti che è stato consentito da ANPR inserire nel campo località estera sia la località che lo stato estero in questo formato "COMUNE -STATO-" ES: MONTREAL -CANADA- . Nel campo dello stato estero di nascita trovo giustamente CANADA. Quando vado ad immigrare nel mio comune un cittadino con i dati inseriti così ho due tipi di problemi. Il primo, meno grave ma che mi procura comunque del lavoro, è che non trovando nelle tabelle dei comuni stranieri MONTREAL -CANADA- lo inserisce come nuovo. Il secondo, molto più impattante, è che al momento dell'emissione della CIE viene scritto MONTREAL -CANADA- (CANADA). Purtroppo i comuni che hanno inserito in modo errato la località estera sono molti. E' possibile fare qualcosa a livello di ANPR?  Si possono intercettare le descrizioni dello stato nel campo località tra "-" e eliminarle quando queste descrizioni corrispondono allo stato indicato nel campo "stato di nascita"? Grazie

**Comment by ncapozzi** [comment]
Buongiorno
in ANPR non abbiamo un archivio delle CITTA’ ESTERE e pertanto il campo LOCALITA estera di nascita è testo libero e non ne viene controllato il contenuto. Non possiamo neanche effettuare un aggiornamento massivo di quanto trasmesso dai Comuni.
Quello che possiamo fare è cogliere l'occasione per precisare a tutti che nel campo LOCALITA ESTERA di nascita o di residenza va indicato il nome di una CITTA’ senza ripetere lo stato di appartenenza visto che esiste già un campo apposito.

N. Capozzi
