### ISSUE TITLE
Notifica al sw locale di CIE emessa in comune subentrato ma non di residenza

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#2872]
Buongiorno,
sono Nozzoli Arianna comune di Prato subentrato.
Ci sono novità sulle notifiche di emissione CIE da parte di altro Comune subentrato verso il Comune di residenza subentrato per il riallineamento della banca dati locale?
Gli enti esterni autorizzati (Polizia, Carabinieri, Guardia di Finanza...) hanno accesso alla banca dati locale. Quindi si capisce bene l'importanza di ricevere queste notifiche.

Grazie

**Comment by Amucciarelli74** [comment]
Buon giorno, 
a seguito di svariate richieste ricevute in questo ultimo periodo dagli enti per l'argomento in oggetto, vi chiediamo cortesemente se sono previste (e in quali tempi) implementazioni di notifiche di emissione CIE per cittadini non residenti nel comune di emissione, diversamente sarà necessario da parte nostra prevedere una modalità di aggiornamento a partire da interrogazioni puntuali sui soggetti o dallo scarico dei dati del comune dal portale.
In attesa di riscontro, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by anozzoli** [comment]
Buongiorno, 
Ci potete dare notizie in merito? Grazie

**Comment by RENZO63** [comment]
Mi sembra strano che a distanza di cosi' tanto tempo non si sia ancora arrivati a capire se verra' o meno implementata una funzione che pare essere abbastanza banale riguardo alla realizzazione tecnica ma indispensabile per la normale attività dell'ufficio anagrafe.
Fateci sapere qualcosa
Grazie

**Comment by RENZO63** [comment]
A distanza di parecchi mesi ripropongo la stessa richiesta segnalando che il fenomeno dei rilasci in altri comuni è ormai diventato molto frequente e che la gestione delle varie comunicazioni sta diventando sempre più problematica.
Mi sembrerebbe utile avere almeno una risposta sulla presa in carico del problema da parte di ANPR
Ringrazio per l'attenzione

**Comment by azabatta** [comment]
Buonasera, 
oltre alle CIE emesse da un comune non competente sul cittadino potrebbero essere di interesse anche le CIE emesse dai consolati? 
Grazie

**Comment by anozzoli** [comment]
Buongiorno,
certo, interessano anche le cie emesse dai consolati. Grazie

**Comment by azabatta** [comment]
Buonasera, 
si comunica che l'intervento è stato completato e rilasciato in ambiente di test_comuni, per i dettagli far riferimento alla issue #5164.
Saluti
