### ISSUE TITLE
Rettifiche non lavorate spid aruba

### ISSUE THREAD

**Issue by gsegatori** [italia/anpr#2875]
Salve,
ho fatto una serie di rettifiche per quanto riguarda il mio nucleo famigliare (dati errati) siamo in 5, tutti con spid, la richiesta di rettifica è stata elaborata il giorno seguente da chi aveva spid con PosteId, mentre invece per chi ha Aruba non sono state elaborate (passati più di 10 giorni) può essere un bug? (Stesso nucleo famigliare e anzi le rettifiche con PosteId sono state effettuate successivamente)

Grazie

**Comment by FilippoPapi** [comment]
no, dipende dall'attività del Comune
cordiali Saluti
