### ISSUE TITLE
COMUNE DI CASERTA ::: servizi al cittadino

### ISSUE THREAD

**Issue by LucianoGRA** [italia/anpr#2877]
Gentili Signori,
 
Mi chiamo Luciano Giovanelli Romano de Ávila e abito in Brasile. Sono descendente in linea retta di un citadino nato in codesto Comune (Matia Romano).
 
Come faccio per sapere se il mio certificato di nascita è già trascritto nel comune?
 
Siamo  persone: mio padre (Matias Antonio Romano de Avila, nato il 17/11/1950), mia madre (Ligia Maria Giovanelli Romano de Avila, nata il 28/09/1958), mia sorella (Melina Romano, nata il 23/03/1984), i miei figli (Gabriel, nato il 06/05/2011 e Isadora, nata il 11/02/2014) ed io (Luciano, nato il 14/07/1980).

Prime 6 cifre del mio codice fiscale: GVNLCN.

Grazie se potete aiutarmi.
 
 
Cordiali saluti.
 
Luciano

**Comment by rinonasti** [comment]
Perché viene citato il comune di CASERTA?

**Comment by LucianoGRA** [comment]
> Perché viene citato il comune di CASERTA?


Perché io ho un problema con la trascrizione dei miei documenti in questo comune. Sto aspettando che il Comune di Caserta trascriva miei atto di nascita e atto di matrimonio.

**Comment by rinonasti** [comment]
Sono il consulente informatico del Comune di Caserta. Comunque ho informato e sollecitato l'ufficio di Stato Civile che mi riferisce "provvederemo agli adempimenti necessari e successivamente trasmetteremo gli atti all'ufficio, AIRE per i successivi passi".
Comunque per ogni altra informazione  riferimento a questa mail antonella.ianniello@comune.caserta.it che è ufficio AIRE che farà da tramite con ufficio di Stato Civile. 
Penso di aver fatto il massimo per  l'help ricevuto.
Cordialità

**Comment by LucianoGRA** [comment]
> Sono il consulente informatico del Comune di Caserta. Comunque ho informato e sollecitato l'ufficio di Stato Civile che mi riferisce "provvederemo agli adempimenti necessari e successivamente trasmetteremo gli atti all'ufficio, AIRE per i successivi passi". Comunque per ogni altra informazione riferimento a questa mail [antonella.ianniello@comune.caserta.it](mailto:antonella.ianniello@comune.caserta.it) che è ufficio AIRE che farà da tramite con ufficio di Stato Civile. Penso di aver fatto il massimo per l'help ricevuto. Cordialità

**Comment by LucianoGRA** [comment]
Amico mio, grazie mille per il tuo aiuto. Ha funzionato davvero e ora è tutto a posto con i miei documenti!
Scriverò questa email.
Grande abbraccio

**Comment by rinonasti** [comment]
Ricambio l'abbraccio con affetto. Era doveroso
