### ISSUE TITLE
Esiti Subentro - Associazione idComune / idANPR

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#288]
salve

in occasione dell'ultima attività di subentro non è andata a buon fine l'associazione degli idANPR con quelli locali.

solo approfondendo abbiamo visto che sono cambiati gli identificativi dei "Tipo Scheda" utilizzati da ANPR:
- da "Aire" a "Scheda Individuale AIRE"
- da "Individuale" a "Scheda Individuale APR"

può sembrare banale, ma questo dettaglio per noi è abbastanza importante in fase di acquisizione degli esiti del subentro.

se prevedete modifiche future al riguardo vi chiederei di segnalarle.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Mi scuso per il disagio ma non avevamo idea che quella costante fosse utilizzata nelle vostre elaborazioni
