### ISSUE TITLE
Soggetto individuato in AT con CF non utilizzabile (Codice: EAM80)

### ISSUE THREAD

**Issue by ColognoAlSerio1** [italia/anpr#2886]
Richiesta assistenza per rettifica Cognome e Codice Fiscale cittadino 
Anomalia: Soggetto individuato in AT con CF non utilizzabile (Codice: EAM80)

Informazioni sull'operazione da fornire in caso di assistenza : data 2021-10-29 12:59:42 , idOperazioneANPR 679755242 (Codice: EN527)

Rimaniamo in attesa di un Vs. gentile riscontro.

Grazie

Comune di Cologno al Serio

**Comment by FilippoPapi** [comment]
buonasera per problemi specifici chiamare il numero: 800863116
