### ISSUE TITLE
Curiosità - Multipla cittadinanza

### ISSUE THREAD

**Issue by enricomiletto** [italia/anpr#2887]
Salve,
sono cittadino di due paesi (uno dei quali è l'Italia) ed accedendo ad ANPR e andando in -> Visura e autocertificazioni -> Cittadinanza mi appare solamente cittadinanza italiana.

La mia domanda è: è il campo per inserire la cittadinanza sulla piattaforma ANPR che permette di inserire un solo stato o è il mio comune di residenza ad aver inserito dati non completi (cioè non aggiunto il secondo paese)?

Grazie

**Comment by mttfranci** [comment]
Salve, la funzionalità della visura dovrebbe mostrare tutte le cittadinanze registrate in ANPR.
E' probabile che nel suo caso sia stata registrata una sola cittadinanza dall'anagrafe del comune.
Saluti

Assistenza ANPR
