### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by ibassocesar** [italia/anpr#2889]
Buongiorno,

Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

![image](https://user-images.githubusercontent.com/93520982/139659118-60ccbfca-4dcb-49a8-b86b-1d4a8c015448.png)

In contatto con il Comune di Castellabate, non hanno riscontrato problemi con la scheda anagrafica. 

Cosa devo fare? 

Grazie

**Comment by mttfranci** [comment]
Salve, per poter effettuare una verifica, potrebbe fornirci le prime 6 lettere del suo codice fiscale?
Grazie in anticipo.

**Comment by ibassocesar** [comment]
Salve.

Le prime 6 lettere del mio codice fiscale: NFNCRG

Grazie

**Comment by mttfranci** [comment]
Salve, sembrerebbe che, analogamente alla issue #2809 , sia presente una anomalia legata al suo codice fiscale.
Nel suo caso il codice fiscale è presente ma non risulta essere correttamente agganciato (validato) con la banca dati di agenzia entrate.
Il legame tra l'accesso SPID/CIE/CNS e la scheda anagrafica avviene, al momento, attraverso il codice fiscale.
Dovrebbe rivolgersi al suo comune per sanare questa situazione sulla sua scheda.
Saluti

Assistenza ANPR

**Comment by fpesar** [comment]
Buon pomeriggio a Voi,
mi permetto di inserirmi nel presente confronto in quanto la problematica di cui in oggetto è esattamente la stessa...mancanza di accesso con la consueta schermata blu di errore accesso.
Prima di dover prender contatto con il mio comune di residenza iscritto ANPR (Anguillara Sabazia - Roma) vorrei sentire il vostro parere.
Il mio codice fiscale è PSRFBA mentre per mia madre, anch'essa residente nel medesimo comune, è BRRSVN.
Spero di non aver sbagliato ad accodare qui il mio caso, altrimenti provvederò ad aprire un nuovo topic.

Grazie e cordiali saluti.
