### ISSUE TITLE
Parte obbligatoria degli atti di unione civile formati nel regisro provvisorio

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#289]
Nella definizione del dato tipoAtto l'attributo della parte è obbligatorio:
<xs:element name="parte"               type="charMax5"     minOccurs="1" maxOccurs="1"/>
Questo non va bene per gli atti di unione civile formati nel 2016 e nei primi due mesi del 2017, cioè gli atti formati durante la gestione provvisoria del registro delle unioni.
La gestione provvisoria aveva un registro senza parti, la gestione definitiva attuale ha una suddivisione in due parti, 1 e 2.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Da verifiche che abbiamo effettuato, per questi casi nella parte occorre indicare "X". Tale valore ovviamente non viene riportato nei certificati. Aggiorniamo la documentazione che sarà visibile con la prossima pubblicazione.

**Comment by bfilipazzi** [comment]
Questa soluzione introduce differenze che risolvono un problema creandone un altro, i comuni tengono moltissimo all'allineamento dei dati fra ANPR e il db locale, così facendo abbiamo una X in ANPR che non ha corrispondenza in comune.

**Comment by gcarbonin** [comment]
Qui non stiamo parlando del contenuto delle basi dati ma di come deve essere riempito un campo quando si effettua la chiamata al servizio.

**Comment by bfilipazzi** [comment]
Immagino che se valorizzo il campo con X questo valore, il medesimo entri nel db di ANPR.

**Comment by bfilipazzi** [comment]
Errata corrige: immagino che se valorizzo il campo con X , il medesimo valore entri nel db di ANPR

**Comment by gcarbonin** [comment]
Due persone se vogliono capirsi devono parlare un linguaggio comune; come poi archiviano i dati nella loro memoria è un problema di diversa natura che in ogni caso esula da questo contesto.
Faccio presente che i comuni in produzione (esclusi probabilmente tre per evidenti motivi) già lavorano così.
Il suggerimento implicito di eliminare l'obbligatorietà del campo non è praticabile.
