### ISSUE TITLE
ANPR molto molto  lento

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2890]
Buongiorno, 
da circa 15 minuti il sistema presenta rallentamenti, le risposte vengono fornite a distanza di minuti.
Potreste verificare?
Cordiali saluti
Floramo S.

**Comment by Pellet1285** [comment]
Anche Pomigliano, sistema non funziona

**Comment by sfmodena** [comment]
Anche a Modena stesso problema.

Cordiali saluti
Sonia Fiorini

**Comment by erikaap** [comment]
direi che ora non funziona proprio...non si riesce ad accedere al portale

**Comment by paoloHV** [comment]
Anche i nostri clienti

**Comment by filippo1961** [comment]
IDEM COMUNE DI MARSALA

**Comment by erikaap** [comment]
al portale si accede...ma lentissimo

**Comment by rinonasti** [comment]
IDEM COMUNE DI CASERTA

**Comment by mgminelli** [comment]
Buongiorno, registriamo rallentamenti importanti anche come Comune di Milano. I rallentamenti sono tali che il nostro api manager sospende gli endpoint per sospetta congestione del backend.

**Comment by Pellet1285** [comment]
timido accenno di ripresa

**Comment by Azambo98** [comment]
Anche al Comune di Villongo anpr risulta non funzionante.

**Comment by rinonasti** [comment]
COMUNE DI CASERTA
Sarebbe opportuno avere informazioni. Grazie

**Comment by erikaap** [comment]
A noi hanno detto che contano di risolvere per le 12.00

**Comment by FilippoPapi** [comment]
salve ci stiamo lavorando vi avviseremo appena risolto

**Comment by FilippoPapi** [comment]
il sistema è ripartito. scusate per il disservizio
cordiali saluti

**Comment by cedgravina01** [comment]
A me purtroppo non risulta! Per un attimo è sembrato che fosse ripartito ma in questo momento continua a non funzionare.

**Comment by LaSalleAnagrafe** [comment]
Confermo che funziona a sprazzi, è stato possibile ricercare un cittadino per l'emissione di un certificato ma poi il certificato va in timeout

**Comment by FilippoPapi** [comment]
avete ragione sono ripartiti i problemi

**Comment by filippo1961** [comment]
Continua a non funzionare

**Comment by rinonasti** [comment]
Tempistica?  - anche  emissione CIE in tilt

**Comment by erikaap** [comment]
adesso sembra funzionare..

**Comment by rinonasti** [comment]
assolutamente NO

**Comment by FilippoPapi** [comment]
adesso dovrebbe funzionare

**Comment by filippo1961** [comment]
ok funziona

**Comment by erikaap** [comment]
si anche a me direi che funziona, grazie

**Comment by mgminelli** [comment]
Anche da Milano confermiamo problema rientrato. Grazie e buona serata.
