### ISSUE TITLE
ANPR rimane nella schermata "Login in corso" e poi effettua redirect a https://www.anpr.interno.it/

### ISSUE THREAD

**Issue by lilpach** [italia/anpr#2892]
Buongiorno, quando effettuo l'accesso tramite SPID, il sito mi porta ad una schermata scura con la dicitura "Login in corso" e dopo alcuni secondi mi riporta a https://www.anpr.interno.it/ senza poter accedere ai servizi. 

Grazie

**Comment by FilippoPapi** [comment]
ha ancora il problema?
