### ISSUE TITLE
COMUNE DI PANTIGLIATE : WS 3002

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2893]
COMUNE DI PANTIGLIATE
Rif. Ferrari Nadia

Buongiorno
siamo subentrati il 28.10.2021, oggi a seguito di invocazione del metodo 3002 , il vostro ws ritorna errore, alleghiamo file :+1: 

Segnaliamo che venerdi abbiamo lavorato regolarmente.

Restiamo in attesa di riscontro.
Grazie

**Comment by GabriellaBallabio** [comment]
[EsitoWS_Richiesta3002_1.txt](https://github.com/italia/anpr/files/7460973/EsitoWS_Richiesta3002_1.txt)
[Richiesta3002.txt](https://github.com/italia/anpr/files/7460975/Richiesta3002.txt)

**Comment by amollicone1982** [comment]
Abbiamo avuto dei problemi in mattinata. Potete riprovare
