### ISSUE TITLE
 Bagnacavallo  - AMBIENTE DI TEST INACCESSIBILE

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#2894]
Dona' Datamanagementitalia per comune di Bagnacavallo  - AMBIENTE DI TEST
Sito : https://dptest.anpr.interno.it/com
cercando di avere accesso a quanto sopra utilizzando il certificato del comune ( per intenderci quello 039002-CO-0000.p12)   si ottiene che il sito risulta irraggiungibile.
Il nostro fine e' entrare sul sito per poi scaricare l'ulteriore certificato di test ( un .crt) da utilizzarsi per  sviluppi . 
L' attuale certificato dei servizi risulta scaduto 30/10/2021.
Potete risolvere il probelma dell' accesso a tale ambiente e / o  fornirlo al comune di Bagnacavallo il necessario per accedere  ?
Rispondere a dellasantinam@unione.labassaromagna.it
 che mi autorizza nonche' mi chiede di aprire segnalazione presso di voi.
GRAZIE 
Edoardo Dona' 
338 59 09 376

**Comment by Leonforte** [comment]
Buon pomeriggio,  il link corretto per l'ambiente di test è https://dptest.anpr.interno.it/combas, e non /com, comunque possiamo inviare il certificato 390002-CO-9999 di test all'ALP del comune, saluti

**Comment by edoardodona-1** [comment]
ok. GRAZIE .
Per favore , si, inviate il 390002-CO-9999 valido al comune a
***@***.***

GRAZIE !

Il giorno mar 2 nov 2021 alle ore 16:53 Leonforte ***@***.***>
ha scritto:

**Comment by Leonforte** [comment]
Abbiamo inviato il certificato, saluti

**Comment by edoardodona-1** [comment]
Buongiorno
andando su  https://dptest.anpr.interno.it/combas e utilizzando il nuovo
certificato installato sul pc (provati sia chrome che ie che firefox e
provandolo anche a casa del cliente) otteniamo che di chide di scegliere il
certificato ma immediatamente dopo appare :
[image: Errore__accesso_con_certificato_nuovo.JPG]
Cosa sbagliamo ?
Grazie
Saluti


Il giorno mar 2 nov 2021 alle ore 16:53 Leonforte ***@***.***>
ha scritto:

**Comment by Leonforte** [comment]
Scusate, non era stato attivato, potete riprovare grazie

**Comment by edoardodona-1** [comment]
Ehm. Grazie
siamo riusciti a entrare ma il .crt che si scarica a fronte di "...Test
Comuni CertificatoX509 (tls) risulta poi scaduto il 30/10/2021 .
c'e' modo di ottenerne uno ancora valido ?
Grazie !!!
[image: una_volta_entrati.JPG]
[image: wstest.crt_comunque_scaduto.JPG]

Il giorno mer 3 nov 2021 alle ore 15:51 Leonforte ***@***.***>
ha scritto:

**Comment by Leonforte** [comment]
Buongiorno, stiamo provvedendo ad aggiornarlo, nelle more lo abbiamo comunque mandato via mail al comune al medesimo indirizzo, saluti

**Comment by edoardodona-1** [comment]
Salve e grazie , intanto,
 ma i colleghi che lo devono utilizzare mi dicono non essere questo .
Quello che gli occorre effettivamente e'  quello che si scarica da :
[image: una_volta_entrati.JPG]
e proprio al suo interno riporterebbe un qualcosa di attinente al
wstest.anpr.interno.it e inoltre e' un .crt.
Ci date info in merito ?
Dona' 338 59 09 376

Il giorno gio 4 nov 2021 alle ore 12:54 Leonforte ***@***.***>
ha scritto:

**Comment by edoardodona-1** [comment]
Salve. 
Esiste la possibilita' di avere riscontro anche alla segnalazione di ieri relativa alla necessita di disporre del crt di cui sopra ?
Se qualcosa risultasse vago potete sempre telefonarmi al 338 59 09 376.
Grazie

**Comment by edoardodona-1** [comment]
Alla ca di Leonforte:
Buongiorno:
Il collega che mi dice che i certificati finora forniti non sono quello che
gli occorre chiederebbe di essere contattato telefonicamente al
345 61 68 796
oggi pm dalle 15 alle 17
o domani dalle 9.30 alle 13 o dalle 15 alle 17 ?
.
Ce la fa ?
Grazie

Il giorno gio 4 nov 2021 alle ore 16:28 edoardo dona ***@***.***>
ha scritto:

**Comment by edoardodona-1** [comment]
RETTIFICA (IL NUMERO DI TEL ERA ERRATO) :
Alla ca di Leonforte:
Buongiorno:
Il collega che mi dice che i certificati finora forniti non sono quello che
gli occorre chiederebbe di essere contattato telefonicamente al
*328 0151072*
oggi pm dalle 15 alle 17
o domani dalle 9.30 alle 13 o dalle 15 alle 17 ?
.
Ce la fa ?
Grazie

Il giorno lun 8 nov 2021 alle ore 12:14 edoardo dona ***@***.***>
ha scritto:
