### ISSUE TITLE
ServiziANPR non disponibili 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2896]
COMUNE DI PANTIGLIATE
Ref. Ferrari Nadia

Buongiorno
continuiamo ad avere problemi nell'invocazione dei WS esposti da ANPR. Alleghiamo response di questa mattina .
[EsitoWS_Richiesta3002.txt](https://github.com/italia/anpr/files/7466006/EsitoWS_Richiesta3002.txt)

Restaimo in attesa di gentile riscontro.
Grazie

**Comment by GabriellaBallabio** [comment]
Buongiorno
scusate il disturbo ma il COMUNE DI PANTIGLIATE sollecita una risposta in merito al malfunzionamento segnalato.

**Comment by FilippoPapi** [comment]
il problema è stato risolto
