### ISSUE TITLE
Errore accesso con spid

### ISSUE THREAD

**Issue by lucapaolo990** [italia/anpr#2897]
Buongiorno, come tanti utenti in precedenza ho lo stesso problema, al momento dell accesso con spid mi dice che non è possibile recuperare la scheda, contattato il comune di residenza mi dicono che è tutto a posto, non so come fare davvero.
Il mio cod fiscale è LPRLCU90B……. Grazie per l’eventuale aiuto!

**Comment by mttfranci** [comment]
Salve, sembrerebbe che, analogamente alla issue #2889, sia presente una anomalia legata al suo codice fiscale.
Nel suo caso il codice fiscale è presente ma non risulta essere correttamente agganciato (validato) con la banca dati di agenzia entrate.
Il legame tra l'accesso SPID/CIE/CNS e la scheda anagrafica avviene, al momento, attraverso il codice fiscale.
Dovrebbe rivolgersi al suo comune per sanare questa situazione sulla sua scheda.
Saluti

Assistenza ANPR
