### ISSUE TITLE
Invertire il codice Fiscale Principale con quello collegato

### ISSUE THREAD

**Issue by montecchio21** [italia/anpr#2898]
Comune di Montecchio Emilio (RE)
per il soggetto identificativo 61443937 
occorre invertire il codice fiscale principale con quello collegato, ma al momento della registrazione mutazione tutti i dati compare il seguente messaggio e non siamo in grado di cambiare 
![image](https://user-images.githubusercontent.com/93645184/140030982-ac380dcd-348e-400a-bbbe-05dddbff91b0.png)
si resta in attesa di un vostro risconto

**Comment by ncapozzi** [comment]
Buongiorno,
per invertire i CF dovete modificare il comune di nascita impostando PARMA (PR) per ottenere l'aggiornamento automatico del CF con quello che termina con G337. 
Se però il cittadino è nato  MONTECHIARUGOLO F473 deve mantenere il CF attuale. Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
