### ISSUE TITLE
Precisazioni in merito alla certificazione online dal 15 novembre 

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2899]
https://github.com/italia/anpr/issues/2888

Buongiorno, facendo riferimento alla Issues sopra riportata, vorrei solo avere una precisazione in merito alla notizia pubblicata sul sito del Ministero.
La notizia parla di "cittadini italiani". Ciò sta a significare che solo i cittadini in possesso di cittadinanza italiana potranno usufruire della certificazione online?

Grazie
Claudio Vignati

**Comment by patriziasaggini** [comment]
Dal punto di vista normativo, la certificazione anagrafica va rilasciata a tutti i residenti iscritti in anagrafe, quindi anche agli stranieri. 
Aspettiamo comunque conferma da parte dei tecnici di Sogei.

**Comment by FilippoPapi** [comment]
all'area riservata del Cittadino potranno accedere tutti coloro che sono muniti di SPID, CIE e CNS e che sono inscritti nell'ANPR.
buona serata
