### ISSUE TITLE
Codifica relazioni di parentela ANPR : 14, 15,  19

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#29]
Salve,
ci riferiamo a quei rapporti di parentela 14, 15, 19 (tabella 5  relazioni_di_parentela), presente sul sito di ANPR della documentazione tecnica:
14 Figliastro / Figliastra, 
15 Patrigno/Matrigna,
19 Fratellastro / Sorellastra
che sono utilizzabili solo per subentro.
Quali codici dobbiamo utilizzare in luogo di questi?

Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by gcarbonin** [comment]
Questi codici non so più utilizzabili in quanto (mi sembra dal 1996) non si possono riportare sui certificati. Occorre utilizzare convivente o, ove ne ricorrano le condizioni, figlio/a - padre/madre - fratello/sorella.
"Ove ne ricorrano le condizioni" deve essere verificato e quindi ho qualche dubbio sulla conversione automatica. Per questa necessità di verifica, si accettano in subentro e quando necessario (con la persona davanti) il comune potrà eseguire la variazione.
Gina C.
