### ISSUE TITLE
Subentro - Documenti: Tipo di Soggiorno "VALORE ERRATO"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#290]
buongiorno

in presenza di documento di soggiorno non individuato tra quelli specifici previsti nella tabella '08', viene indicato il codice '8', corrispondente a 'Altro titolo di soggiorno'.

in fase di consultazione:
- via web-service (ws 3002): il servizio mi ritorna, al posto del codice '8', il codice '99' (non previsto in tabella)
- via web-app: compare la descrizione "VALORE ERRATO"

(es. ambiente PRE-SUB - Comune di Faenza - idSoggettoANPR 18709825)

Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Può riprovare e darci un riscontro?

**Comment by AMonopoliADS** [comment]
il dato che viene ritornato, sia dal web-service che dalla web-app, è coerente con quanto inviato (quindi, vedo '8' e non più '99')
ma nel caso dell'8 la web-app non decodifica il tipo di documento (al contrario degli altri casi dove viene visualizzato 'CARTA', 'PERMESSO', etc...)

**Comment by cmigliardi** [comment]
risolto con il comune in data 18 ottobre 2017

**Comment by AMonopoliADS** [comment]
segnalo solo una cosa: 
la decodifica della tabella 08 è "altro titolo di soggiorno", mentre sulla web-app - a parità di codice - viene visualizzato "altro PERMESSO di soggiorno". 
personalmente ritengo più adeguato il termine generico "titolo"
... in ogni caso suggerisco di uniformare le due diciture.
