### ISSUE TITLE
Cancellazione Aire per doppia Iscrizione

### ISSUE THREAD

**Issue by DanteComuneCesena** [italia/anpr#2900]
Buongiorno,
per un nostro cittadino id ANPR 18544224 già cancellato da questo comune per espatrio all'AIRE, il comune di Reggio Emilia ci segnala che è impossibilitato nel fare operazioni/certificazioni sul loro cittadino id anpr 96984314, in quanto sembrerebbe che ci sia una doppia posizione.

Quindi noi abbiamo annullato la vecchia cancellazione per espatrio e stavamo procedendo ad effettuare una cancellazione per altri motivi AIRE con motivo doppia iscrizione, il sistema restituisce il seguente errore:

Il soggetto non puo' essere cancellato per doppia iscrizione perche' non risultano due o piu' posizioni in ANPR
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-03 11:42:22 , idOperazioneANPR 682720227

In attesa di un vostro gentile riscontro.
Cordiali saluti
Della Strada Dante
Comune di Cesena

**Comment by ncapozzi** [comment]
Il Comune di Cesena è stato contattato per la cancellazione della posizione indicata.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
