### ISSUE TITLE
[5005] - Rimpatrio da AIRE: errore EF054

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#2901]
Buon giorno, 
il comune di Porto San Giorgio sta effettuando il rimpatrio di un soggetto AIRE, unico componente della famiglia, che si aggrega a una famiglia già presente in ANPR (idFamigliaANPR 38947419). 
Il web-service (5005) va in errore con il messaggio EF054  "I soggetti devono appartenere alla stessa famiglia", che non riusciamo ad interpretare in quanto come detto il soggetto che sta rimpatriando è l'unico della pratica oltre che nella famiglia di origine, e l'id della famiglia di destinazione indicato nella request è corretto.
L'Id operazione ANPR indicato nel messaggio di errore è 661406738 (id operazione comune 1090332021110353) e l'operazione come detto è stata effettuata nell'ambiente di PRODUZIONE del comune di Porto San Giorgio in data 03/11/2021.
In attesa di riscontro,
cordiali saluti.

Giuseppe Mucciarelli, TINN srl (Gruppo Maggioli)

**Comment by ncapozzi** [comment]
Buongiorno,
il problema dipende dal fatto che nella richiesta il cognome è composto da una sola parola mentre in ANPR è diviso in due. Per questo motivo il CF non è validato su Agenzia Entrate dove il cognome  è composto da una sola parola
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
