### ISSUE TITLE
Bambino nato morto: come agire

### ISSUE THREAD

**Issue by ParsecSalvatore** [italia/anpr#2902]
Un comune ha inserito in ANPR un bambino nato morto dietro richiesta della madre di avere un codice fiscale per operazioni INPS.
Bisogna ora annullare l'operazione di nascita o inserire una operazione di morte (ma con quali estremi di atto di morte)?

In futuro per un caso simile, si dovrebbe evitare del tutto di inserire la nascita o ci si deve comportare così?

Grazie

**Comment by rvinzani** [comment]
Se il bambino nasce morto lo stato civile forma un atto di nascita che è anche atto di morte e questa casistica non prevede la registrazione in anagrafe. Viceversa se il bambino è nato vivo e poi deceduto si formano entrambi gli atti e si registra in anagrafe. Nel vostro caso se non avete gli estremi dell'atto di morte potete cancellarlo per altri motivi e indicare nelle note il motivo
