### ISSUE TITLE
Sigillo elettronico qualificato sui certificati di ANPR

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#2903]
#2888

Buongiorno,
riferendomi alla issue sopra indicata presumo che i certificati rilasciati dal portale di ANPR saranno dotati di sigillo elettronico qualificato ai sensi dell'art. 62 del D.L.vo 82/2005.
Volevo sapere se a partire dalla stessa data, o successivamente, il sigillo elettronico qualificato sarà inserito in tutti i certificati rilasciati da ANPR compresi quelli che si ottengono normalmente tramite il servizio 6001.
Grazie

Luca Bonini - Apkappa

**Comment by FilippoPapi** [comment]
buonasera, no i certificati con sigillo elettronico qualificato saranno emessi solo dal portale ANPR
saluti
