### ISSUE TITLE
COMUNE DI PANTIGLITE :  ServiziANPR non disponibili Rif. ISSUE #2896 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2904]
Buongiorno
ci è stato detto che il problema è risolto ... ma non è così, anche questa mattina i servizi non funzionano.

Abbiamo fatto dei test 

invocando i servizi all'ENDPOINT https://ws.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000

certificato : 015167-PC-0001 
password : B174938B

la risposta è : Connection timeout

invocando i servizi all'ENDPOINT https://wspre.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000

medesimo certificato e password il servizio RISPONDE CORRETTAMENTE

Potete verificare le chiamate e fornirci cortese riscontro ?

Grazie

**Comment by amollicone1982** [comment]
A noi, per oggi, non risultano chiamate arrivate ai nostri sistemi. Si tratta di un problema di rete.
Potete verificare l'ip che avete risolvendo ws.anpr.interno.it?

**Comment by GabriellaBallabio** [comment]
Buongiorno
in allegato tracert ws.anpr.interno.it, PC in Comune di Pantigliate.
![tracePantigliate](https://user-images.githubusercontent.com/54433203/140698834-0745220c-2b03-4158-947c-6d8256231928.png)

**Comment by amollicone1982** [comment]
ip provenienza?

**Comment by GabriellaBallabio** [comment]
91.81.21.66, il comune ha cambiato ip un anno fa.

Cosa dobbiamo fare per modificare l'ip dichiarato ?

**Comment by amollicone1982** [comment]
nell'area amministrazione(in alto a destra) della web app di produzione. sezione info aggiuntive

**Comment by GabriellaBallabio** [comment]
abbiamo modificato l'indirizzo IP così come indicato , ma ancora non funziona ... ci sono dei tempi tecnici di aggiornamento prima dell'acquisizione nel nuovo IP ?

**Comment by amollicone1982** [comment]
si ci sono dei tempi tecnici per aggionare il firewall

**Comment by amollicone1982** [comment]
a noi non risulta il cambio ip. ricordo che dopo aver aggiunto l'ip bisogna cliccare sul bottone conferma in basso

**Comment by GabriellaBallabio** [comment]
abbiamo rieseguito l'operazione 5 minuti fa ... risulta la richiesta di cambio ip ?

**Comment by amollicone1982** [comment]
non risulta la richiesta. se volete vi facciamo contattare dall'assistenza domani mattina
![Immagine](https://user-images.githubusercontent.com/29304687/140765824-bdf68a13-7937-429b-bab2-46ce590830ec.png)
Dovreste avere un immagine come in allegato e poi cliccare in basso su conferma.

**Comment by GabriellaBallabio** [comment]
Abbiamo riprovare ad impostare l'indirizzo IP in questo m,omento. Vi risulta la richiesta ? In allegato quello che risulta a noi.
![Immagine](https://user-images.githubusercontent.com/54433203/140882277-fb4bcce5-48fe-4523-89a4-3421bb6c6bb2.png)
![Immagine1](https://user-images.githubusercontent.com/54433203/140882285-1e5fda02-e07e-4d42-9aff-b19c04cb54f8.png)

Restiamo in attesa di riscontro.
Grazie

**Comment by amollicone1982** [comment]
si risulta inserito. provate adesso

**Comment by GabriellaBallabio** [comment]
restituisce sempre il medesimo errore .... alleghiamo response chiamata
[ESITO.TXT](https://github.com/italia/anpr/files/7503138/ESITO.TXT)

**Comment by amollicone1982** [comment]
riprovate adesso per favore
