### ISSUE TITLE
GRAVE BLOCCANTE Errore incomprensibile in 4005

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2905]
Ambiente di produzione, comune di Brugherio

Stiamo procedendo all'avvio con il nsotra software del comune in oggetto per passaggio da altro applicativo.
Abbiamo richiesto con il servizio 4005 in data 5/11/2021 tutte le operazioni ANPR nel periodo 17/10/2021 - 5/11/2021 (id ANPR richiesta 685165513).
**Questa operazione la eseguiamo abitualmente per ogni conversione da altro applicativo che abbiamo svolto negli ultimi due anni.**
Questa volta però otteniamo un errore incomprensibile: EN148 Una operazione con lo stesso id operazione comune risulta ancora in elaborazione : JD211108084948.
Abbiamo cercato questo id operazione ma corrisponde alla stessa richiesta 4005 di scarico che va in errore.

Come mai ? Cosa è successo ? Potete sbloccare la situazione ?

Grazie

**Comment by amollicone1982** [comment]
ci risulta un operazione con id anpr 686370051 e idoperazionecomune JD211108084948 finita con esito positivo oggi alle 08:51.
Ci date l'id operazione anpr che vi dà EN148?

**Comment by busaster** [comment]
È proprio quello, il file XML di risposta della id ANPR 686370051 è quello con l'errore EN148. 
Tale richiesta avrebbe dovuto restituirci l'esito dello scarico richiesto con la 4005 di ID ANPR 685165513, che contiene come dicevo nel precedente post tutte le operazioni dal 17/10/21 al 5/11/21

**Comment by amollicone1982** [comment]
Come da mail a Filippo Ferri venerdi alle 19.

Avete  richiesto tutte le operazioni di BRUGHERIO tra il 17 ottobre e oggi.
La richiesta di per se è lecita, ma purtroppo le dimensioni sono eccessive e non può essere scaricata  per limiti prestabiliti  - ecco perché le ho già scritto che tali richieste vanno concordate a prescindere. 
Potete  provare a scaricare un giorno alla volta, ma alla richiesta originaria non possiamo dare seguito

**Comment by mttfranci** [comment]
Salve, la dottoresessa Migliardi aveva già risposto per email a Filippo Ferri il 5 novembre esattamente su questa situazione.
Avete modo di mettervi in contatto tra di voi @busaster ?

Saluti

**Comment by busaster** [comment]
L'email l'ho letta ma quanto afferma non ci quadra. 
Speravo di ottenere un approfondimento ulteriore aprendo una segnalazione qui in github. 
Così non è, useremo altri canali.
Grazie

**Comment by mttfranci** [comment]
Mi perdoni, non era chiaro che comunque la comunicazione per email le era nota.
Noi abbiamo aperto una attività per indagare l'anomalia segnalata, che però potrebbe richiedere un pò di tempo.
Trattandosi di situazione eccezionale (cambio di applicativo), potreste comunque provare il workaround proposto?
(Ovvero lo scarico delle operazioni riducendo l'intervallo di richiesta, magari per singola giornata).
Grazie in anticipo.

Saluti

**Comment by mttfranci** [comment]
Ci siamo accorti venivano inclusi anche i 6001 (servizio certificazione) quando vengono richieste tutte le operazioni. Se per voi va bene possiamo rigenerare la richiesta originaria che dovrebbe essere la 685165513 senza i 6001, a quel punto la risposta dovrebbe avere una dimensione tale da poter essere ottenuta senza problemi.
Va bene?

Assistenza Anpr.

**Comment by busaster** [comment]
Per noi va bene, le 6001 non ci interessano, con che tempi pensate di poter eseguire l'operazione ?
Inoltre chiedo, le 6001 saranno poi escluse anche dalle future richieste 4005 di tipo"tutto"" ?

**Comment by mttfranci** [comment]
Salve, la richiesta 685165513 è stata rigenerata senza 6001 all'interno.
In futuro i 6001 non saranno più inclusi nella risposta del servizio 4005.
Riteniamo che dovessero essere esclusi dall'inizio al pari delle consultazioni.
(Il fatto che fossero inclusi è stato classificato come bug e corretto con la patch 5.13.13).
Fateci sapere se ora riuscite a ottenere l'esito della richiesta 685165513.
Saluti

Assistenza ANPR

**Comment by busaster** [comment]
Richiesta scaricata con successo, grazie per il supporto

**Comment by mttfranci** [comment]
Di niente. Buona serata.
