### ISSUE TITLE
CERTIFICAZIONI ANPR DAL 15 NOVEMBRE ANCHE PER PROFESSIONISTI?

### ISSUE THREAD

**Issue by Pellet1285** [italia/anpr#2906]
Buongiorno, in vista del 15 novembre, data in cui i certificati possono essere scaricati autonomamente con SPID, si chiede se lo stesso valga anche per gli avvocati, investigatori ecc. in quanto gli stessi si trovano soventemente a chiedere certificati relativi a persone oggetto delle loro indagini/ricerche.
Uno Spid intestato non a persona fisica, ma a persona giuridica potrebbe essere condizione sufficiente per l'emissione di tali certificati?
grazie in anticipo per il chiarimento

**Comment by FilippoPapi** [comment]
buongiorno
il certificato potrà essere solo per se stessi o per un appartenente al proprio nucleo familiare
saluti

**Comment by patriziasaggini** [comment]
Rispetto a quanto chiesto dal collega, si fa presente che l'art. 33 del DPR 223/1989 prevede che i certificati di Stato di Famiglia e Residenza possano essere rilasciati a chiunque.
Tutti i servizi online pubblicati dai Comuni hanno seguito questa regola, e per la ricerca della persona per cui richiedere il certificato occorre di norma compilare alcuni campi (a titolo di esempio):
NOME + COGNOME
DATA DI NASCITA
SESSO
CODICE FISCALE 
proprio per evitare ricerche indiscriminate.

La versione più recente del DPR 223/1989 - sempre in relazione ai certificati anagrafici - prevederebbe che tutti i certificati contenuti in ANPR possono essere rilasciati a chiunque, visto che si fa riferimento sempre nell'art. 33 "a tutti i dati ivi contenuti (riferito all'Anagrafe Nazionale)".

Questo passaggio è fondamentale, perchè buona parte dei certificati vengono richiesti non per sè stessi, ma da soggetti "intermediari qualificati", come avvocati e notai (che altrimenti tornerebbero a rivolgersi allo Sportello del Comune).

Avete in programma l'adeguamento del servizio a quanto prevede la normativa?
