### ISSUE TITLE
 ACCORDI DI FRUIZIONE 

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#2907]
Gentili, 
uffici diversi dall'anagrafe del nostro Comune richiedono conferme di dati anagrafici ad altri comuni ma stanno ricevendo rifiuti con indicazione di rivogersi ai nostri uffici.
Non entro nel merito normativo della questione che non vi riguarda, ma vorrei sapere quando si aprirà la possibilità per gli accreditamenti, che a questo punto diventa URGENTE.
Un esempio : https://www.comune.mantova.gov.it/index.php/controlli-autocertificazioni 
Grazie per l'attenzione.
Raffaella Comune di Venezia

**Comment by FilippoPapi** [comment]
è in corso una sperimentazione, non so dirle quando sarà aperta a tutti gli Enti
saluti
