### ISSUE TITLE
Cambio residenza da comune subentrato ad altro comune subentrato

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#291]
A fronte di una reale **Mutazione di indirizzo da un comune subentrato (Chiavari) verso altro comune subentrato (Torgiano**), porto all’attenzione le seguenti problematiche sorte da un confronto tra i dati dell’anagrafe locale e quelli presenti in ANPR:

1)	Sarebbe opportuno per il soggetto trasferitosi cambiare in ANPR il valore dell’attributo  **soggettoCertificabile** da 2=CERTIFICABILITA COMPLETA  ad  1=CERTIFICABILITA PARZIALE (solo residenza e stato di famiglia)  finché la pratica di iscrizione non venga definita, così come si fa per i soggetti di prima iscrizione ANPR?

2)	Il soggetto risulta essere elettore perché evidentemente iscritto nelle liste dell’altro comune. A scanso di equivoci sarebbe meglio visualizzare nel tag **ListaElettorale** del servizio 3002 anche il comune delle liste di iscrizione delle liste elettorali (anche perché questo dato alla prossima revisione muterà). A questo proposito sollecito la preparazione del servizio di comunicazione massivo di tutti gli iscritti nelle liste elettorali a seguito di revisione elettorale e per contro anche quello di “revoca” di iscrizione dalle liste per motivi diversi dal trasferimento di residenza in altro comune - vedi https://github.com/italia/anpr/issues/280)

3)	Anche per i dati del **censimento**, a scanso di equivoci, sarebbe meglio introdurre il comune di riferimento dei dati registrati.

4)	Il soggetto ha dichiarato al comune di trasferimento, di non possedere né **veicoli** né **patenti**, laddove in ANPR risulta avere entrambe. Premesso che la sua affermazione sia vera, occorre che venga anche implementato il relativo servizio di Revoca di questo tipo di dati.

Alessio Tropeano, Datagraph s.r.l.

**Comment by gcarbonin** [comment]
1. E' a carico del comune modificare il campo certificabilità
2. Argomento trattato in altre issue
3. Se si indica "N" nei due campi ANPR accetta la variazione
