### ISSUE TITLE
Mancata iscrizione in applicativo locale di persona iscritta in ANPR

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2910]
La persona con identificativo ANPR 194366764, per un motivo a noi incomprensibile, risulta iscritta in ANPR per nascita ma non nell'applicativo locale. Dietro suggerimento della software house,   si richiedere la cancellazione da ANPR per procedere successivamente ad una nuova iscrizione che risolva l'inconveniente.

**Comment by rvinzani** [comment]
Il soggetto è stato iscritto in ANPR in seguito alla richiesta del gestionale locale n. JD2111021235251493 il 2/11/2021. Se si deve procedere con una nuova iscrizione è possibile annullare l'operazione con ID operazione ANPR n. 660612310 direttamente dalla web app selezionando la funzione registrazione->Annullamento iscrizione
