### ISSUE TITLE
[WEBAPP] Esito AE: Operazione non effettuabile (Codice 95) - Allineamento codice fiscale

### ISSUE THREAD

**Issue by ParsecSalvatore** [italia/anpr#2912]
Comune di San Donato di Lecce, tentando l'allineamento del codice fiscale MLTTMS21R30E506S fra AE e ANPR, il sistema restituisce l'errore

**Esito AE: Operazione non effettuabile (Codice 95)**

**Comment by ncapozzi** [comment]
Buonasera
il problema nasce dal fatto che nel campo LETTERA dell'indirizzo è indicato KM 5,2 e Agenzia Entrate non accetta la virgola in questo campo.

E' necessario effettuare una mutazione famiglia/convivenza con tipo = 9 RETTIFICA/INTEGRAZIONE INDIRIZZO e data decorrenza uguale alla data di decorrenza della residenza attuale per togliere la virgola dal campo LETTERA. Si suggerisce se possibile di spostare KM 5,2 nel campo TOPONIMO.         

Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
