### ISSUE TITLE
Ambiente di TEST - [1001] Errore EN403 L'operazione richiesta all'Agenzia delle Entrate contiene dati errati o insufficienti

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#2913]
Buongiorno,

da ieri in ambiente di test non riusciamo più ad effettuare alcune operazioni che necessitano dell'attribuzione del CF, ad es.

Ambiente di test del comune di Villa Minozzo (da sw gestionale), evento di nascita
data 2021-11-10 10:07:19 , idOperazioneANPR 44757944
EN403 L'operazione richiesta all'Agenzia delle Entrate contiene dati errati o insufficienti

Lo stesso problema si verifica cercando di effettuare lo stesso evento da webapp.

Potete verificare? 
Grazie

Monia Pedrazzoli APKAPPA

**Comment by amollicone1982** [comment]
problema risolto
