### ISSUE TITLE
URGENTE [servizio 4001] - Errore EN179

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2914]
[risposta.txt](https://github.com/italia/anpr/files/7511639/risposta.txt)
[richiesta.txt](https://github.com/italia/anpr/files/7511638/richiesta.txt)
Comune di Candela (FG)

A seguito di richiesta con servizio 4001 errore EN!79: si allega xml di richiesta e xml di risposta (da rinominare in .xml)
SI chiede di sbloccare e/o eliminare le richeste "pendenti" non ancora elaborate per poter effettuare una richiesta 4001 "pulita"

**La presente ha carattere di ESTREMA URGENZA**

Alberto FIORENTINI - Halley Informatica

**Comment by amollicone1982** [comment]
4001 sbloccato
