### ISSUE TITLE
[EAM12] Soggetto non individuato in AT - Codice fiscale NON variato

### ISSUE THREAD

**Issue by maumarc64** [italia/anpr#2918]
Per l' ID ANPR 196379647 (nuovo nato) è stata erroneamente inviata ad ANPR comunicazione con luogo nascita errato con conseguente validazione errata del codice fiscale: lo stesso è stato poi annullato e nuovamente richiesto con i dati corretti direttamente su punto fisco.
Entrando in ANPR modalità web service e cercando di operare l'allineamento ANPR/AE, scegliendo i dati AE, compaiono i messaggi:

Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)

Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-10 13:42:27 , idOperazioneANPR 689288790 (Codice: EN527) 

Come risolvere?
Grazie.

Maurizio Marchese-Anagrafe Comune di Muggiò (MB) subentrato il 31-03-2021

**Comment by frmariani** [comment]
Il codice fiscale presente nel sistema ANPR è stato annullato dall'Agenzia delle Entrate, pertanto l'operazione che state eseguendo non è quella corretta.
Le ho svalidato il codice fiscale in modo che possa effettuare una mutazione dei anagrafici e modificare il precedente con l'attuale richiedendone la validazione.

**Comment by maumarc64** [comment]
Operazione eseguita correttamente, problema risolto.
Grazie infinite.
