### ISSUE TITLE
ISCRIZIONE PER NASCITA

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2919]
COMUNE DI CASERTA 061022 (PROD)
Iscrivendo un cittadino per nascita WS1001 viene fuori il seguente errore:
EN143
Soggetto madre non in ANPR                
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-10 13:51:49 , idOperazioneANPR 689299594

abbiamo controllato i dati di paternità e maternità ambedue presenti in ANPR

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
il cognome della mamma indicato nell'iscrizione è diverso da quello con cui è registrata in ANPR. Si suggerisce pertanto di verificare sulla web app in consultazione/estrazione.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
