### ISSUE TITLE
Tabella comuni - Province Sarde soppresse

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#292]
Segnalo nella tabella dei comuni un mancato aggiornamento dei comuni Sardi già appartenenti alle province istituite con la L.R. 9/2001 e successivamente annullate con la L.R. 2/2016.

A titolo di esempio:
Comune di TALANA nella tabella ANPR è codificato ancora in provincia di Ogliastra, mentre in realtà andrebbe compreso nella provincia di Nuoro.
Comune di OLBIA nella tabella ANPR è codificato in provincia di Olbia Tempio Pausania, mentre in realtà andrebbe compreso in provincia di Sassari.

Filipazzi - Maggioli

**Comment by MarcoMigliori** [comment]
Sullo stesso argomento vedi anche #249 e #258

**Comment by bfilipazzi** [comment]
ok, grazie
