### ISSUE TITLE
AGGIORNAMENTO TIPO ELETTORE - QUESITO TECNICO

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2922]
Buonasera,
il file xml del servizio WS5008 deve avere questa struttura?

<generalitaPerRicerca>
....
</generalitaPerRicerca>
<liste>
  <listaelettorale>
     <elettore>S/N/P</elettore>
  </listaelettorale>
</liste>

si ripete per tutti i soggetti da variare

si chiude con

<datiControllo> 
<tipoMutazione>5</tipoMutazione>
</datiControllo>

Grazie

**Comment by ncapozzi** [comment]
Deve essere trasmesso un WS 5008 per ogni cittadino AIRE maggiorenne che non abbia il TIPO ELETTORE valorizzato o per il quale questo campo deve essere aggiornato. I dati da impostare nel 5008 sono i seguenti.

<listaElettorale>
<elettore>S</elettore> o N o P a seconda dei casi
</listaElettorale>

<datiControllo>
<tipoMutazione>05</tipoMutazione>
