### ISSUE TITLE
Comune di Modena - Errore AEE97 - operazione non effettuabile

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#2923]
Comune di Modena - Produzione

Buongiorno,
stiamo ricevendo l' errore in oggetto su un tentativo di iscrizione; lo stesso si verifica consultando qualsiasi CF dalla "Consultazione AE" della webapp. Ci sono problemi nel colloquio con Agenzia delle Entrate?

Grazie, saluti
Sonia Fiorini

**Comment by paoloHV** [comment]
Anche i nostri clienti me lo segnalano

**Comment by FilippoPapi** [comment]
Buongiorno
confermo che ci sono problemi sui servizi erogati da Agenzia delle entrate

**Comment by FilippoPapi** [comment]
il problema è stato risolto
