### ISSUE TITLE
Errore Codice 97, mancata generazione codice fiscale per nascita

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#2924]
Buongiorno,
la funzione di Consultazione AE e di Risoluzione Disallineamenti restituisce errore "Esito AE: Operazione non effettuabile (Codice 97)" - 
L'iscrizione per nascita non genera codice fiscale.
Buon lavoro

Anna Maria AIMONE
UPI Torino

**Comment by paoloHV** [comment]
Anche i nostri clienti me lo segnalano

**Comment by paoloHV** [comment]
non vanno nemmeno "consultazione AE" da ANPR e tutte le funzioni di risoluzione disallineamenti

**Comment by filippo1961** [comment]
IDEM COMUNE DI MARSALA NON VANNO CONSULTAZIONI AE

**Comment by vpadadem** [comment]
segnalato anche dai nostri clienti, errore AEE97

**Comment by filippo1961** [comment]
IDEM COMUNE DI MARSALA

**Comment by FilippoPapi** [comment]
buongiorno
confermo che ci sono problemi sui servizi erogati da Agenzia delle entrate

**Comment by erikaap** [comment]
previsione dei tempi di risoluzione?

**Comment by erikaap** [comment]
sembra ripartito

**Comment by FilippoPapi** [comment]
confermo il problema è stato risolto
