### ISSUE TITLE
Problemi con endpoint Comunali ambienti di test e presubentro RIF#2867 - RIF#2880

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#2926]
Per l'ambiente di PRESUBENTRO segnaliamo che non riceviamo di nuovo per il Codice comune 040007 le notifiche N10,N014,N015 tramite ENDPOINT, arrivano soltanto le N030 e N031, quindi il nostro servizio è in ascolto.

Nell'elenco delle notifiche prese direttamente dalla WEBAPP le vediamo.

Potreste verificare se sono state inviate le seguenti notifiche:
Numero notifica ANPR
25214327
25214328
25214329
25214330
25214331
25212692
25212693

Inoltre per l'ambiente di TEST Codice comune 015125 la richiesta del cert 015125-CO-9999 ci risulta in lavorazione da più di una settimana, sarebbe possibile sbloccarla?

Rimaniamo in attesa di un gentile riscontro.
Saluti
Laboratorio Dedagroup

**Comment by amollicone1982** [comment]
le notifiche segnalate in presubentro sono tutte N010 che sono state inviate in data 08/11/2021 intorno alle 16 con esito positivo. per il certificato vi faremo sapere a breve

**Comment by LSPAG** [comment]
Provo ad essere più specifico per motivare la nostra segnalazione, perchè c'è qualcosa che non torna, volevamo capire se l'origine del problema stava nel nostro o vostro sistema.

Abbiamo effettuato un altro test questa mattina e il vostro servizio ha inviato subito le notifiche, invece per quanto riguarda le notifiche citate sopra, almeno da quanto ci si risulta, il vostro servizio ha inviato soltanto ieri(7 giorni di differenza fra operazione e notifica) e non come scrive lei in data 08/11, faccio degli esempi:
 
Operazione per cui il vostro sistema ha inviato subito:

Mutazione di residenza id operazione ANPR 25228343 Codice mittente 069058 in data 2021-11-15T09:47:11.0170651
numero notifica 25228348, data 2011-11-15T09:00:17, destinatario 40007
numero notifica 25228349, data 2011-11-15T09:00:18, destinatario 40007

Operazione per cui il vostro sistema non ha inviato subito (motivo per cui è stata fatta segnalazione in data 11/11/2021):

Mutazione di residenza id operazione ANPR 25214325 Codice mittente 069058 in data 2021-11-08T16:18:39.3636362
numero notifica 25214327, data 2021-11-14 03:50:00.433, destinatario 40007
numero notifica 25214331, data 2021-11-14 03:50:01.063, destinatario 40007
numero notifica 25214330, data 2021-11-14 03:50:01.267, destinatario 40007
numero notifica 25214329, data 2021-11-14 03:50:01.630, destinatario 40007
numero notifica 25214328, data 2021-11-14 03:50:01.890, destinatario 40007

Questa anomalia ci risulta in ambiente di presubentro e non in subentro, possibile che essendo un ambiente di test e il servizio si comporti diversamente in modo più blando in base ai giorni, se cosi fosse è inutile che continuiamo a segnalare ce ne faremo una ragione.

Grazie per la collaborazione.

**Comment by amollicone1982** [comment]
mi scusi ma ha ragione, solo due delle 7 notifiche sono state inviate l'8 mentre le altre ieri. Per il resto il suo ragionamento è giusto. Si tratta di un ambiente di test dove le risorse sono limitate dato che quasi tutti i comuni sono subentrati. Per tale motivo, in alcuni casi (carico eccessivo dovuto a piu' comuni che lavorano contemporaneamente), ci puo' essere un rallentamento nella gestione delle notifiche.
Cercheremo di risponderle al più presto alla seconda richiesta
