### ISSUE TITLE
AGGIORNAMENTO TIPO ELETTORE - QUESITO TECNICO #2922

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2927]
Chiedo scusa, nell'avviso si dice "invio massivo"  ed ecco la domanda sulla struttura del file xml nella issue  #2922.

Grazie

**Comment by rinonasti** [comment]
Ho visto che nella domanda #2922 non é stato riportato il testo della struttura :


TESTATA WS5008


generalitaPerRicerca
.....
.....
/generalitaPerRicerca`
liste
  lista elettorale
     elettore>S/N/P /elettore
  /listaelettorale
/liste

**si ripete per ogni elettore da variare**

**si chiude con** 

daticontrollo
  tipomutazione>5 /tipomutazione
/daticontrollo

**Comment by ncapozzi** [comment]
Per massivo si intende che deve essere trasmesso un ciclo di WS 5008, un 5008 per ogni cittadino AIRE maggiorenne che non abbia il TIPO ELETTORE valorizzato o per il quale questo campo deve essere aggiornato. Non c'è ripetizione all'interno del singolo 5008
