### ISSUE TITLE
CERTIFICAZIONE ON-LINE DA PORTALE ANPR (15/11/2021) 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2928]
Buongiorno,
In assenza di informazioni nell'area amministrazione (informazioni certificazione) viene apposta la firma IL SINDACO e il suo nominativo?
Grazie

**Comment by cmigliardi** [comment]
buongiorno,  per favore ci occorrono più informazioni -  ci può  inviare la schermata dei parametri e il comune oggetto dell'analisi ?  i certificati li chiede da sportello o da portale comunale ? grazie

**Comment by cmigliardi** [comment]
se invece  si parla di ciò che leggo nel titolo della richiesta .   certificati online dal portale anpr . Le dico  che i certificati  hanno qrcode  e  sigillo elettronico qualificato del Ministero dell'Interno e non si sono  firme.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
