### ISSUE TITLE
Variazione di causale di iscrizione da comune non subentrato

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#293]
Segnalo un limite riscontrato più di una volta in produzione: l'anagrafe X riceve una istanza di residenza in cui l'interessato dichiara la provenienza dal comune Y, il comune Y (non subentrato) richiesto di cancellare risponde che l'ha già fatto in precedenza per irreperibilità accertata, in tal caso l'anagrafe X deve variare la causale dell'iscrizione anagrafica modificandola da "immigrazione" in "ricomparsa". Questa variazione della causale non è prevista da ANPR.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
L'intervento e' tra quelli previsti.

**Comment by luca-teamdigitale** [comment]
Duplicate of #306

**Comment by RBiasi** [comment]
Comune Parma - Presubentro

Buongiorno siamo a richiedere quando sarà disponibile tale WS che permette la variazione dei dati di iscrizione da comune non subentrato.

Grazie

**Comment by RBiasi** [comment]
Scusa a seguito verifiche rettifico, riesco a modificare tramite WS il motivo di iscrizone mentre variando la data di iscrizione da oggi 16/05/2018 al giorno 14/05/2018 ho l'errore

1 Errore Anpr Cod: EN414 - Rettifica non permessa in quanto la data di decorrenza residenza e' presente e congruente - 

CF anagrafica fittizzia di test LBRNTN80T10F205H

**Comment by frmariani** [comment]
per rettificare la data iscrizione deve utilizzare il servizio 5014 tipo rettifica 103 (altre date);
da una verifica effettuata, la tipologia di rettifica inviata  per l'anagrafica fittizia indicata, è la 101 (data decorrenza residenza): in questo caso,  la data è presente e congruente, pertanto NON modificabile, come indicato nel diagnostico di errore.
