### ISSUE TITLE
[5012] L'operazione da annullare non è l'ultima per il soggetto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2930]
Comune di Montechiarugolo produzione,

tentando di annullare l'operazione ID ANPR 636137457 otteniamo l'errore in oggetto EN077.
ID dell'operazione di annullamento che fallisce è 691633925.
Non riusciamo però a capire quale sia l'operazione che blocca l'annullamento, potete aiutarci ?
Grazie

**Comment by ncapozzi** [comment]
Buonasera
non è possibile fare l'annullamento in quanto nel frattempo è stata effettuata un'altra operazione sulla famiglia di partenza. Pertanto è necessario effettuare
- cancellazione per altri motivi con motivo 12 - Ripristino posizione precedente e data di decorrenza = a quella del cambio di residenza
- reiscrizione del cittadino indicando nelle generalità l'idsoggettoANPR della scheda cancellata
