### ISSUE TITLE
Accreditamento

### ISSUE THREAD

**Issue by FrancescoAcea** [italia/anpr#2931]
Buongiorno, come noto a tutti da oggi è possibile scaricare i certificati digitali, ma io non riesco ad accreditare la mia azienda di pubblici servizi. Il sistema chiede che la stessa venga registrata sull'ipa, ma ci siamo già.  cosa dobbiamo fare?
Grazie

**Comment by FilippoPapi** [comment]
buongiorno
i certificati sono per i Cittadini intesi come persone fisiche e non per le aziende
cordiali salut
