### ISSUE TITLE
Sostituzione codice fiscale in Agenzia Entrate (principale-collegato)

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2932]
Un cittadino è presente in AE con 2 codici fiscali, collegati tra loro. Volendo scambiare il codice fiscale da collegato a principale, pur avendo seguito le istruzioni mostrare nel video al link https://www.youtube.com/watch?v=WNPtxi2mdzE, viene restituito il messaggio EAV40.
Riferimenti
Comune di Colosimi
Dati cittadino:
Iniziali CF: MTUT....
Finale CF attualmente principale ......1G
Finale CF attualmente collegato .......0H
Cordiali saluti

**Comment by frmariani** [comment]
ho potuto verificare che sulla cittadina sono state effettuate molte operazioni sul codice fiscale, quindi nel caso mi indichi la corretta idoperazione anpr fallita.

Comunque, per effettuare un'inversione di link, i dati corrispondenti al collegato che si desidera trasformare in principale, devono essere uguali ai dati presenti in Agenzia delle Entrate.
Da quello che ho potuto verificare, ad esempio nell'operazione idanpr  691412311, non è corretto il luogo di nascita; infatti, con il codice catastale E990 (codice catastale presente nel CF) dovrebbe inserire come comune di nascita Martinaro e non Martinaro Lombardo

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
