### ISSUE TITLE
Problema accesso con SPID

### ISSUE THREAD

**Issue by cs1901** [italia/anpr#2933]
Salve,
non riesco ad accedere al portale tramite SPID, il messaggio di errore è il seguente:

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

Il comune di appartenenza è Pozzuoli e le prime 6 cifre del CF sono: SCSCMN.

Grazie

**Comment by cmigliardi** [comment]
Gentile utente, abbiamo verificato la sua scheda anagrafica e risulta una anomalia che non le consente di accedere al servizio. Sogei non può operare per sanare la situazione ma soltanto il  suo comune di residenza che deve verificare la situazione della sua scheda anagrafica su ANPR  e mettere in atto le azioni necessarie per la risoluzione.

**Comment by ziamary** [comment]
Tentando di accedere, mi dà lo stesso problema.

Comune di appartenenza: Milano
Prime 6 cifre del CF: MRVNMR

**Comment by cmigliardi** [comment]
Gentile utente, abbiamo verificato la sua scheda anagrafica e risulta una anomalia che non le consente di accedere al servizio. Sogei non può operare per sanare la situazione ma soltanto il suo comune di residenza che deve verificare la situazione della sua scheda anagrafica su ANPR e mettere in atto le azioni necessarie per la risoluzione.
 anche in questo caso  occorre che il comune controlli la scheda di    MRVNMR.....  in ANPR - ovviamente noi non possiamo sanare la situazione  ma il suo comune sì. (in generale   il codice fiscale deve essere  validato da Ag Entrate,  la scheda marcata da Ag Entrate, la scheda deve essere unica e non duplicata etc......)

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
