### ISSUE TITLE
NOTIFICHE #2920

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2938]
Buonasera,
Quanto indicato nella precedente issue #2920 si sta ancora verificando.  Arrivano sempre notifiche N015 riguardanti lo stesso nucleo.
Come é possibile interrompere.
Grazie

**Comment by azabatta** [comment]
Buongiorno,
analizzando le comunicazione pervenute in ANPR l'iter di cui alla issue #2920 è stato innescato più volte. E' stato contattato il comune di interesse per una verifica, la famiglia ha effettivamente chiesto il cambio di residenza. Il comune è stato seguito nell'esecuzione dell'operazione, le relative notifiche N010 sono state correttamente generate.
