### ISSUE TITLE
Accordo di fruizione per Enti

### ISSUE THREAD

**Issue by Giorgio852021** [italia/anpr#2939]
Salve,
vorrei sapere se sarà possibile la sottoscrizione dell'accordo di fruizione anche da parte delle banche, in quanto erogatori di servizi pubblici, al fine adempiere alle necessarie attività di adeguata verifica.
in caso la modalità è quella prevista per tutti gli enti/PA? E' già possibile sottoscriverlo, in attesa di piena operatività?
Grazie

**Comment by FilippoPapi** [comment]
per ora la sottoscrizione dell'accordo di fruizione è prevista solo per le pubbliche amministrazioni
cordiali saluti
