### ISSUE TITLE
Incrocio dati di matrimonio

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#294]
I controlli che ANPR esegue incrociando i dati dei coniugi sono causa di difficoltà operativa. Un caso tipico è questo: uno dei coniugi (B) richiede l'iscrizione in ANPR quando l'altro (A) è già presente dal momento del subentro. Nella scheda di A è assai probabile che B sia descritto soltanto con cognome e nome, quando andiamo ad iscrivere B (B.cognome, B.nome, B.data e B.luogo di nascita) indicando A come suo coniuge, ANPR ci risponde che A è coniugato con (B.cognome, B.nome) che è persona diversa da (B.cognome, B.nome, B.data e B.luogo di nascita). 
In caso A fosse un AIRE, per ragioni note da tempo, B sarebbe descritto nella scheda di A con il solo cognome.

**Comment by bfilipazzi** [comment]
Issue 294 aperta da
Filipazzi  - Maggioli

**Comment by gcarbonin** [comment]
1) controlli sul matrimonio. Ci dovrebbe indicare un caso specifico in modo da poter analizzare la situazione
2) AIRE - è previsto un intervento in proposito - vedi issue 244 Attendiamo i vostri commenti sui dati proposti

**Comment by bfilipazzi** [comment]
I controlli che ANPR esegue incrociando i dati dei coniugi sono causa di difficoltà operativa. Il caso tipico è questo: uno dei coniugi (B) richiede l'iscrizione in ANPR quando l'altro (A) è già presente da tempo. Nella scheda di A è assai probabile che B sia descritto soltanto con cognome e nome, quando andiamo ad iscrivere B (B.cognome, B.nome, B.data e B.luogo di nascita) indicando A come suo coniuge, ANPR ci risponde che A è coniugato con (B.cognome, B.nome) che è persona diversa da (B.cognome, B.nome, B.data e B.luogo di nascita).
Per risolvere il problema l’operatore deve interrompere l’acquisizione della pratica, intervenire sulla scheda di A e completare i dati del coniuge B desumendoli dalla dichiarazione su cui sta lavorando; nel caso la dichiarazione di residenza sia arrivata per posta in data precedente l’operatore deve avere l’accortezza di far decorrere il completamento dei dati di B nella scheda di A con validità non successiva, perché se usasse la data odierna – come viene spontaneo di fare – successivamente ANPR solleverebbe un’eccezione.
Si noti che in taluni contesti, tipicamente negli enti grandi, l’operatore di sportello che acquisisce la dichiarazione potrebbe non avere i permessi per modificare i dati delle schede già presenti, è un aspetto in cui non ci siamo ancora imbattuti ma che posso prevedere con certezza.

**Comment by gcarbonin** [comment]
Intendevo un caso reale (identificativo dell'operazione che ha determinato l'errore), in quanto non abbiamo più avuto segnalazioni di questa natura.

**Comment by bfilipazzi** [comment]
Il caso è risolto, AIRE a parte, i miei segnalatori non mi avevano aggiornato. Ho provato da me e osservato che ANPR completa i dati della prima anagrafica (A nell'esempio) in modo trasparente; è corretta la mia deduzione? se lo fosse ritengo importante documentarla così da adeguare i gestionali, e sarebbe necessaria una notifica. Con l'occasione domando se il completamento dei dati avviene anche durante il popolamento di subentro.

**Comment by gcarbonin** [comment]
Al momento del subentro, si cerca di collegare le schede tra loro utilizzando gli identificativi del comune "subentrante"; di più non si può fare in quanto è elevatissimo il rischio di collegare tra loro posizioni che non c'entrano nulla l'una con l'altra. Questo vale sia per i coniugi che per i genitori. Ha avuto modo di verificare se i dati AIRE integrativi sono sufficienti?

**Comment by bfilipazzi** [comment]
La corrispondenza delle situazioni fra ANPR e db locale è di grande importanza. Per garantirla chiedo che ANPR restituisca - a subentro avenuto - un log delle conciliazioni eseguite, allo scopo di replicarle in locale.
Sarebbe molto utile essere informati sulla presenza di altri algoritmi di variazione dei dati svolti dalle logiche di ANPR in fase di subentro.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Possiamo prevedere anche questo, ma faccio presente che questa riconciliane utilizza i dati del comune sulle schede già collegate tra di loro. Mi spiego con un esempio: al momento del subentro, ANPR riceve dal comune la scheda anagrafica del soggetto A che riporta i dati del matrimonio con il soggetto B, nella scheda del soggetto A è riportato l'identificativo del comune del soggetto B oltre al cognome ed il nome. Il soggetto B è residente nello stesso comune e quindi nei dati del subentro ANPR riceve anche la scheda anagrafica del soggetto B, che contiene l'identifiativo comunale del coniuge soggetto A. A fine caricamento, si controllano entrambe le schede del soggetto A e del soggetto B e dal momento che in entrambi i casi è presente l'identificativo del comune di ciascuno dei due soggetti, si collegano le schede tra loro anche in ANPR. Quindi, quale è il collegamento che manca a livello locale?

**Comment by bfilipazzi** [comment]
A livello locale il collegamento si basa sull'id comunale, che non è necessariamente incrociato in tutte le schede dei coniugi e dei genitori, anzi purtroppo è spesso assente. Il gestionale mette a disposizione correttivi automatici per la "riconciliazione", ma sono eseguiti a discrezione del cliente, quindi non in ogni db, e lavorano con una logica che assai probabilmente non è identica a quella di ANPR.
