### ISSUE TITLE
Consultazione Anagrafe Tributaria via Web Service

### ISSUE THREAD

**Issue by GianluM67** [italia/anpr#2941]
Buon pomeriggio.
Per rispondere all'esigenza di un Comune nostro cliente, desideriamo sapere se è già disponibile (o se è previsto che lo sia) un web service ANPR per la consultazione dell'Anagrafe Tributaria.
Grazie.
Gianluca Manzin - Stesei Torino

**Comment by frmariani** [comment]
Non è disponibile un WS di consultazione del CF presso l'Agenzia delle Entrate e non sono previsti aggiornamenti in tal senso

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
