### ISSUE TITLE
[servizio 4001] Assenza di risposta dopo molte ore di attesa

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2942]
Per conto del Comune di USMATE VELATE:

La richiesta 4001 effettuata con ID ANPR richiesta 694537922 del 15.11.2021 ore 14:53:06 a questo istante non ha ancora ottenuto risposta.
Si chiede cortesemente di "sbloccare" questa richiesta: si allegano i files xml (da rinominare) di richiesta e di risposta.
[richiesta.txt](https://github.com/italia/anpr/files/7539834/richiesta.txt)
[risposta.txt](https://github.com/italia/anpr/files/7539837/risposta.txt)

Halley Informatica

**Comment by amollicone1982** [comment]
risultato del 4001 ora è disponibile
