### ISSUE TITLE
Domanda

### ISSUE THREAD

**Issue by valoia2** [italia/anpr#2943]
Salve,
non riesco ad accedere al portale tramite SPID, il messaggio di errore è il seguente:

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

Il mio comune di appartenenza è BARI e le prime 6 cifre del CF sono: LCNVNT.

Grazie

**Comment by cmigliardi** [comment]
buonasera 
Le consiglio di andare al comune di residenza bari  e far controllare la scheda in anpr -  il codice fiscale e se i dati sono in linea  con Ag entrate .

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
