### ISSUE TITLE
Rcihiesta XML richiesta rettifica dati trasmesse dai Cittadini

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#2945]
Buongiorno,
vorremmo sapere se è possibile da wa scaricare file xml della notifica di richiesta rettifica dati trasmesse dai Cittadini e se sì da che voce di menu.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Dedagroup Public Services

**Comment by mttfranci** [comment]
Buongiorno.
No, da web app non è possibile scaricare un file xml della richiesta di rettifica.
Saluti

**Comment by mttfranci** [comment]
Aggiungo che però sono disponibili le specifiche del servizio P000, presente in ambiente di test, per l'integrazione dei gestionali #2765 e che a breve dovrebbe essere rilasciato anche in produzione.

Saluti
