### ISSUE TITLE
Report certificazioni rilasciate da portale ANPR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#2948]
Buongiorno,
è stato o sarà prevista la possibilità di avere un report delle cerificazioni rilasciate online da Portale ANPR?

Grazie
Claudio Vignati

**Comment by mttfranci** [comment]
Salve, non è previsto nessun report.
Saluti

Assistenza ANPR.

**Comment by patriziasaggini** [comment]
E' possibile fare in modo che nella web app ci sia una sezione in cui vengono visualizzati i dati di rilascio per ciascuna tipologia di certificati, per soggetti residenti nel Comune?
