### ISSUE TITLE
Errore nel recupero scheda anagrafica

### ISSUE THREAD

**Issue by gusruju** [italia/anpr#2949]
Salve, cerco di accedere ai Servizi al Cittadino ANPR, ma dopo autenticazione SPID ricevo unicamente una pagina di errore che riporta una serie di messaggi tra cui "se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.".

Il mio comune di residenza è Rivisondoli (AQ) e non figura nella lista di quelli ancora non presenti in ANPR, al Comune non saprebbero come aiutarmi, il mio codice fiscale (RJUGTV**********) è certamente corretto e riconosciuto (lo uso per accesso a innumerevoli servizi online delle Pubbliche Amministrazioni), potete darmi indicazioi su cosa fare per poter accedere ai servizi ANPR?

Grazie

**Comment by cmigliardi** [comment]
gentile RJUGTV.....    come può leggere nel messaggio - le consigliamo di rivolgersi al suo comune di residenza  e di far verificare la scheda in ANPR -  ad esempio occorre controllare se il codice fiscale è validato da agenzia entarte - se la scheda è unica e non duplicata - se è attiva etc .....  tutte operazioni che può fare il suo comune -  noi riportiamo degli esempi perché non possiamo fornire il problema specifico - ma le assicuro che la scheda  va sanata -
