### ISSUE TITLE
5001, 5005 e dati permesso soggiorno 

### ISSUE THREAD

**Issue by niclup** [italia/anpr#295]
I due servizi di cambio residenza consentono l'aggiornamento dei dati patente/veicoli per gli individui trattati,  in verità con un utilizzo un pò artificioso per il 5001.  Ciò che manca del tutto è la possibilità di aggiornare, con i servizi medesimi, i dati del permesso di soggiorno per ogni individuo movimentato di cittadinanza  straniera.

**Comment by gcarbonin** [comment]
Il servizio è  disponibile
