### ISSUE TITLE
Servizi al Cittadino - Non riesco ad accedere al servizio

### ISSUE THREAD

**Issue by Drakan1955** [italia/anpr#2950]
Buongiorno,
quando tento di accedere con SPID (non ho CIE o CNS), appare questo messaggio di errore:

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:
Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

Il mio comune è ROMA, che è sicuramente in ANPR e accedo senza problemi a tutti i servizi (Agenzia Entrate, INPS, Fascicolo Sanitario, ecc) tramite SPID.

Mia moglie riesce ad accedere e a visualizzare i miei dati anagrafici che sono corretti.

Al Comune non riesco a parlare con qualcuno che può aiutarmi.

Ho visto che per casi simili al mio avete chiesto i primi sei caratteri del codice fiscale che sono:
**VTICTN**

Grazie infinite per l'aiuto

Costantino Vita

**Comment by cmigliardi** [comment]
gentile VTICTN  .....  le consigliamo di rivolgersi al suo comune di competenza Roma per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata,    etc ......)    ovviamente noi non possiamo fornire dettagli  ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
