### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by masuccistefano** [italia/anpr#2951]
Salve,
all'accesso tramite SPID ottengo
Il tuo comune di residenza (o di iscrizione all'AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione "A che punto è il tuo Comune?" disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni.

Il mio comune è Napoli (NA), presente in ANPR.

Nella mia scheda SPID è presente il mio codice fiscale, che risulta valido sul sito Agenzia delle Entrate

I primi 6 caratteri del mio codice fiscale sono MSCSFN.

Grazie,
Saluti

**Comment by cmigliardi** [comment]
gentile MSCSFN  ..... le consigliamo di rivolgersi al suo comune di competenza Napoli per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
