### ISSUE TITLE
[ws P001] test su nuovi servizi - richiesta chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#2953]
buongiorno.

il nuovo servizio di gestione delle richieste dei cittadini è, al momento, disponibile solo in ambiente di test.
forse è stato scritto e mi sarà sfuggito, ma mi chiedevo come fare - in ambiente di test, appunto... - ad ottenere delle response consistenti, diverse da:
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EN122</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
	</errore>
</listaErrori>
```

volevo verificare se nella web-app di test (https://dptest.anpr.interno.it/combas) ci fosse qualche nuova possibilità di simulare tali richieste, ma non riesco ad accedere a causa del messaggio
"Si e' verificato un errore durante la fase di autenticazione
E' possibile riprovare ad effettuare il Login dal portale pubblico ANPR"
(blocco che potrebbe dipendere dal mio client a dalla mia rete locale perchè è da un po' di tempo che non vi accedo)

se possibile, gradirei qualche informazione al riguardo.

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
buongiorno. qualche riscontro su questa issue? grazie

**Comment by mttfranci** [comment]
Salve, in settimana è previsto un incontro con le software house per spiegare le modalità con cui sarà possibile effettuare i test.

Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
ambiente di TEST - comune di FAENZA (039010)

richiesta P001 (elenco): eseguita correttamente
richiesta P002 (dettaglio): il sistema mi restituisce questo errore:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Body>
		<soapenv:Fault xmlns:axis2ns9="http://schemas.xmlsoap.org/soap/envelope/">
			<faultcode>axis2ns9:Server</faultcode>
			<faultstring>Internal Error</faultstring>
			<detail/>
		</soapenv:Fault>
	</soapenv:Body>
</soapenv:Envelope>
```
(idOperzioneComune 2022500049)
potete verificare se il problema è nella request oppure se c'è altro che non funziona?

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, si la tabella pubblicata sul portale non era aggiornata.
Ora dovremmo esserci la versione corretta.
Saluti
