### ISSUE TITLE
DATI RESIDENTI RIPORTATI IN ANPR

### ISSUE THREAD

**Issue by Annalisaf** [italia/anpr#2954]
Buongiorno,
vorrei segnalare che nella pagina pubblica di ANPR relativa alle statistiche (https://www.anagrafenazionale.interno.it/AnprStatsWeb/) risultano dati molto strani degli abitanti, che divergono in maniera molto significativa da quelli dell'ISTAT. Eccone qualche esempio (della Regione Marche dove il 100% dei comuni è già passato ad ANPR, ma lo stesso discorso vale anche per le altre aree del Paese - ad esempio in Abruzzo risultano 1.285.256 residenti al 31/12/2020, mentre secondo ANPR ci sono 1.530.902 abitanti):
- Regione Marche: abitanti in ANPR 1.707.140, residenti al 31/12/2020 1.501.406;
- Macerata: abitanti in ANPR 47.695, residenti al 31/12/2020 40.762;
- Corridonia: abitanti in ANPR 17.849, residenti al 31/12/2020 15.020;
- Civitanova Marche: abitanti in ANPR 47.549, residenti al 31/12/2020 41.989.

Vorrei sapere a cosa sono dovute queste divergenze e da quali dati desume il numero di abitanti il sistema di ANPR.
Cordiali saluti
Annalisa Franceschetti

**Comment by cmigliardi** [comment]
Buongiorno, 
scusi il ritardo nella risposta. 
La divergenza tra i numeri è dovuta al fatto che ANPR  conteggiamo sia i vivi che i morti dal momento del subentro in poi, poiché consideriamo tutti i cittadini per i quali è possibile scaricare i certificati (compreso quello di morte). Infatti, i nostri numeri sono sempre più alti rispetto a quelli ISTAT.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
