### ISSUE TITLE
DUPLICE ISCRIZIONE MA CON GENERALITA' DIVERSE - DICHIARAZIONE DI RESIDENZA IN UN TERZO COMUNE

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2955]
Devo procedere all’iscrizione anagrafica in Valsamoggia, con decorrenza 19/10/2021, della persona con identificativo ANPR 95474183, che è stata cancellata il 07/10/2021 dal comune di Serracapriola (FG) per mancato rinnovo della dichiarazione di dimora abituale (l’iscrizione per immigrazione dall’estero risaliva al 23/01/2017).
E’ però emerso  che la persona è contemporaneamente e tutt’ora  iscritta nel comune di Casape (RM), anche qui per immigrazione dall’estero risalente al 12/09/2003, con identificativo ANPR 59517442.
Si  tratta tuttavia di una duplicazione in un certo senso anomala:
A Casape è iscritta con 
Cognome: AAA e Nome: BBB CCC, codice fiscale non allineato in quanto collegato a quello validato da Serracapriola
A Serracapriola è iscritta con
Cognome: AAA BBB e Nome: CCC, codice fiscale allineato
Le generalità corrette sono quelle registrate a Serracapriola  perché coincidenti con quelle riportate nel passaporto e permesso di soggiorno esibiti in allegato alla dichiarazione di residenza in Valsamoggia.
Con le colleghe dei due comuni interessati avevamo ipotizzato di iscrivere la persona per ricomparsa dal comune di Serracapriola, che lascerebbe quindi immutati i suoi dati (avendo già cancellato la persona non crediamo sia possibile rettificare i dati di iscrizione da immigrazione da estero a immigrazione da Casape).
Il problema al quale non riusciamo a trovare soluzione e per il quale chiediamo assistenza è quello della cancellazione da Casape: se si prova a cancellarla per altri motivi,  ANPR risponde con l’errore “SOGGETTO NON PRESENTE IN AT” , essendo il loro un codice fiscale collegato. Ovviamente non possono procedere a correggere le generalità perché l’operazione entra in conflitto con la posizione di Serracapriola.

**Comment by frmariani** [comment]
Per prima cosa devo informarla che l'operazione di cancellazione effettuata dal comune di Casape non rileva l'errore da Lei segnalato, ma inibisce l'operazione in quanto il comune tenta di cancellarlo per doppia iscrizione quando il sistema ANPR non ha mai rilevato tale condizione.
Qual'è la corretta storicità del cittadino ? deve risultare anche il passaggio nel comune di Casape ? 
Per favore mi indichi un recapito telefonico dove raggiungerla al seguente indirizzo
frmariani@sogei.it

**Comment by frmariani** [comment]
Contattato il comune e risolto per le vie brevi.
Il comune di Casape cancellerà la cittadina con motivazione "Altro" inserendo una breve descrizione del problema;
il comune di Valsamoggia iscriverà per ricomparsa la cittadina idanpr 95474183.
