### ISSUE TITLE
NOTIFICHE #2920 #2938

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2958]
Ritengo che il comune non elabori correttamente le operazioni di immigrazione  poiché rilevo lo stesso errore per un altro cittadino
vedi id operazione 687088173 dovrebbe essere N010 ma è N015.
Come possiamo risolvere?
Grazie per la fattiva collaborazione

**Comment by azabatta** [comment]
Buonasera,
cortesemente può verificare l'id operazione indicato? Riguarda sempre il comune di Caserta?
Come evento anagrafico l'id 687088173  non ha correlazione con una notifica di tipo N010 o N015, come id notifica non esiste.

**Comment by rinonasti** [comment]
Buonasera,
chiede scusa id operazione corretto é 686959131

**Comment by azabatta** [comment]
La notifica collegata all'operazione è corretta: si tratta di un ripristino di posizione anagrafica comunicato in data 08.11.2021. La casistica è analoga a quella già verificata per il caso precedente: il ripristino è stata effettuato nell'arco dello stesso minuto in cui è stata inoltrata la richiesta di mutazione residenza per cui il sistema non ha avuto il tempo di generare la N010.
Per questo cittadino è stata nuovamente trasmessa  la mutazione di residenza  che è stata notificata  con N010 dell'11.11.2021  (id operazione 690665755).
