### ISSUE TITLE
[URGENTE] Certificato di matrimonio: coniuge ha tutti i dati `null`

### ISSUE THREAD

**Issue by mtazzari** [italia/anpr#2959]
Problema:

1. si richiede certificato anagrafico di matrimonio.
2. I dati della persona loggata con SPID compaiono correttamente (data di nascita, residenza, etc.) nel certificato, mentre dei dati del coniuge si legge solo il cognome, e tutti gli altri dati sono `null`.

Non fa differenza se nella Scrivania si seleziona "Richiedi un certificato per te stesso" o "Richiedi un certificato per la tua famiglia", il problema persiste.

Spero possiate fare un bugfix al piu' presto, grazie.

Testato il 17 nov 2021, browser Google Chrome 95.0.4638.69 su Mac OS 10.14.6

**Comment by mttfranci** [comment]
Buongiorno.

Ha modo di fornirci il "codice identificativo anpr", presente nella sezione "visura e autocertificazioni", al fine di poter indagare più velocemente?

![image](https://user-images.githubusercontent.com/29305782/142374611-bef1560c-b7be-43ae-944a-5fbef492aa9b.png)

Grazie in anticipo.

**Comment by mttfranci** [comment]
Salve, abbiamo avuto modo di verificare la sua posizione.

Purtroppo i dati sembrano assenti in banca dati, se ritenete si tratti di un errore materiale del comune, potete contattare il comune competente oppure inviare una richiesta di rettifica direttamente dal portale.

Inoltre una domanda, lei effettivamente il valore "null" al posto di alcune sezioni?  Lo chiediamo perchè in una simulazione che abbiamo effettuato, al posto dei campi mancanti viene mostrata una dicitura del tipo (Assente).
Può confermarcelo?

Saluti

Assistenza ANPR

**Comment by mtazzari** [comment]
Salve,

grazie per il controllo.
Vi ho mandato nuova email a ***@***.*** con
allegati i certificati che ottengo.

Riguardo alla dicitura `null` piuttosto che `ASSENTE`, come vedete dai
certificati, il nome e' `null`, mentre gli altri dati sono `ASSENTE`.

Grazie

Marco Tazzari

—
Dr. Marco Tazzari - ***@***.*** -
https://www.ast.cam.ac.uk/people/marco.tazzari
Postdoctoral Research Associate - office H32  phone +44 (0)1223 766691
Institute of Astronomy, University of Cambridge, Madingley Road, Cambridge,
CB3 0HA, UK

**Comment by mttfranci** [comment]
Grazie della risposta.
Confermiamo che per verificare la completezza della scheda dovrebbe consultare il comune competente.
Saluti
