### ISSUE TITLE
Rigetto parziale di pratica di iscrizione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#296]
Nel caso di immigrazione da comune non subentrato di più persone comprese nella stessa pratica, risulta ancora impossibile togliere dal procedimento eventuali soggetti da rigettare, confermando invece gli altri.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
La funzione è disponibile nell'applicazione WEB.

**Comment by mccalv** [comment]
Duplicate of #254

**Comment by mccalv** [comment]
Riapriamo la issue per l'esposizione della funzionalità come WS

**Comment by gcarbonin** [comment]
La funzionalità è disponibile in entrambe le modalità
