### ISSUE TITLE
ANPR servizi al cittadino

### ISSUE THREAD

**Issue by Luckylu13** [italia/anpr#2960]
Buongiorno,
non ho accesso al portale, mi da il seguente errore
![WhatsApp Image 2021-11-18 at 12 04 19](https://user-images.githubusercontent.com/94614463/142411257-d5c1b47d-01ec-4b5a-b61f-923ee8cf6166.jpeg)
Cosa posso fare?

Grazie
Luciano

**Comment by cmigliardi** [comment]
buongiorno cortesemente ci può fornire i primi  6  caratteri del suo codice fiscale ?  altrimenti non sappiamo come indagare . grazie

**Comment by Luckylu13** [comment]
FVLLCN

Grazie

**Comment by cmigliardi** [comment]
gentile FVLLCN ..... le consigliamo di rivolgersi al suo comune di competenza Viterbo per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, che esista un scheda in ANPR etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.    
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by Luckylu13** [comment]
Grazie dell'assistenza e complimenti per la celerità.

Saluti
