### ISSUE TITLE
codice catastale comune  sulla famiglia di altro comune

### ISSUE THREAD

**Issue by CESARERAMADORI** [italia/anpr#2961]
La famiglia 12641318 era emigrata cerso il comune di Imola in due tranche. Successivamente è stata annullata la mutazione da parte del comune di Imola. Attualmente la famiglia risulta residente nel nostro comune ma permane il codice catastale  037032 del comune di Imola invece che il nostro (037057)
Non riesco a mutarlo.
Cordiali slauti
Cesare
051843576

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by frmariani** [comment]
Il comune d'appartenenza viene modificato dal sistema nel momento in cui vengono effettuate le operazioni di trasferimento della residenza o di ripristino della posizione anagrafica.
Stiamo verificando come mai nel vostro caso non sia stato correttamente aggiornato.

**Comment by frmariani** [comment]
l'incongruenza è stata eliminata

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
