### ISSUE TITLE
Rilascio CIE comune diverso da quello di residenza

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#2962]
Buongiorno,
Se un cittadino Residente nel comune X  sottoposto ad un procedimento (interdizione all'espatrio) richiede una CIE al comune Y, il comune Y come fa a sapere che il soggetto in questione non può avere la carta valida per l'espatrio?.
Premetto che il comune Y non richiede il nulla osta al comune X e va a controllare i Dati Su Anpr.
Come Attributi del soggetto esiste solo la certificabilità.
Cosa Devo impostare affinchè ci sia un blocco di interdizione all'espatrio?
Grazie.
Michele Caputo.
Publisys SPA.

**Comment by rvinzani** [comment]
I dati sulla eventuale interdizione all'espatrio non sono dati anagrafici e non sono presenti in ANPR

**Comment by mcaputo75** [comment]
Mi Scusi, se come accade normalmente io vado in un altro comune per fare la carta di identità CIE come fa l'altro comune a sapere se rilasciarla o meno?

**Comment by cvignati** [comment]
Mi scusi, ma se il cittadino del comune X è sottoposto ad una misura interdizione all'espatrio, il problema sussiste solo nel caso che il cittadino nn abbia già una carta di identità, altrimenti se fosse presente, il comune X avrebbe variato la carta di identità in "Non valida per l'espatrio"

**Comment by rvinzani** [comment]
Provi a fare domanda ai consulenti ANUSCA o al Ministero dell'Interno
