### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by faderfa64** [italia/anpr#2963]
Buonasera, mi chiamo Fabrizio, sono residente in Spagna, iscritto all'AIRE del Comune di Remanzacco, C.F. DLL FRZ e sto sperimentando problemi di accesso al portale.
Volevo richiedere online un certificato ma dopo aver inserito il codice OTP (uso Sielteid per spid) e autorizzato Sielte a inviare il CF ricevo un messaggio di errore (Purtroppo non è stato possibile accedere al servizio)
Ho già usato Spid per accedere ad altri servizi, per esempio il sito dell'Agenzia delle entrate, senza problemi.
Uso Windows 10 (Versión 10.0.19043 compilación 19043) e Chrome Versión 96.0.4664.45 (Build oficial) (64 bits)
Mi potete aiutare?
Grazie

**Comment by cmigliardi** [comment]
gentile dllfrz  ..... le consigliamo di rivolgersi al suo comune di competenza  che lo ha iscritto aire  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, 
che la scheda non sia duplicata, che esista in ANPR, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
