### ISSUE TITLE
Errore invocazione WS 1002 - TRASFERIMENTO DI RESIDENZA DA ALTRO COMUNE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2965]
COMUNE DI PANTIGLIATE
Resp. Nadia Ferrari

Buongiorno
questa mattina invocando il WS ANPR metodo1002 TRASFERIMENTO DI RESIDENZA DA ALTRO COMUNE
ci restituisce il seguente errore

Per trasferire tutti i componenti di una famiglia in una nuova utilizzare il servizio di mutazione residenza famiglia

di seguito i riferimenti dell'operazione
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-19 09:10:07 , idOperazioneANPR 699828224

Potete dirci qual'è il problema ?

**Comment by frmariani** [comment]
L'operazione indicata si riferisce ad un WS 5005 (non WS 1002).
Come cita il controllo emesso, per trasferire l'intera famiglia deve essere utilizzato il servizio di mutazione residenza famiglia (WS 5001).
Il WS 5005 può essere utilizzato per l'intera famiglia soltanto se questa si trasferisce in un'altra famiglia già esistente, ma in questo caso, all'interno dell'xml, deve essere indicato tipo scheda =1.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
