### ISSUE TITLE
Client received SOAP Fault from server: Rejected by policy. CARPI

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#2966]
Buongiorno
CARPI, ( ma anche SOLIERA e  CAMPOGALLIANO) DAL 18 ottobre abbiamo molti collegamenti con ANPR con errore:
"Client received SOAP Fault from server: Rejected by policy. (from client) Please see the server log to find more detail regarding exact cause of the failure."
Per esempio stiamo usando  per Carpi 036005-CO-9999.p12 operatore  BRTLRN61E51I128S e una ricerca su anpr e' ok e l' altra rejected.... 
Data e ora del  server sono ok . 
Potete verificare cosa succede a livello server sogei ?
GRAZIE
Dona' 338 59 09 376

**Comment by edoardodona-1** [comment]
Sono contattabile anche Sabato mattina 338 59 09 376 se non riuscite a processare a breve. 
grazie

**Comment by amollicone1982** [comment]
ci dovrebbe indicare con una data e ora in cui con il certificato 036005-C=-9999 ha preso rejected by policy

**Comment by edoardodona-1** [comment]
Buongiorno.
Credo di aver risolto. L' errore era intermittente ( con una media dell'
80% sulle interazioni applicativo demografico verso ANPR) poi spostando l'
appliance dell' applicativo (in cloud) su al altro dataserver Lepida ( da
Ravenna a Ferrara). La cosa sembra essere rientrata. forse un problema di
latency nelle interazioni. Lunedi ricontrollo . se ok potete chiudere il
ticket ... diversamente sara' necessario interagire nuovamente e fornirvi
data e ora al fine di farvi leggere il log del vs server. grazie.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 19 nov 2021 alle ore 17:50 amollicone1982 <
***@***.***> ha scritto:
