### ISSUE TITLE
[Comunicazione 4001] - Errore EN122 su successiva comunicazione 7001

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#2967]
Fiorentini Alberto - Halley Informatica per conto del Comune di CAVALLERMAGGIORE

A seguito di comunicazione 4001 (ID ANPR richiesta 700069062 del 19-11-2021 ore 11:04:47, dopo aver atteso fino ad ora la risposta con esito positivo della comunicazione 7002 produce errore EN122 tipologia E "La richiesta effettuata non produce alcun risultato (si veda immagine errore.jpg allegata).
Si allegano XML di richiesta e risposta della comunicazione 7002, si richiede lo sblocco delle risposte della 4001.
[richiesta.txt](https://github.com/italia/anpr/files/7569727/richiesta.txt)
[rispsota.txt](https://github.com/italia/anpr/files/7569728/rispsota.txt)
![Errore](https://user-images.githubusercontent.com/78594854/142611548-8c78c5f4-7717-4ee4-bded-b0d6d5863158.jpg)

**Comment by amollicone1982** [comment]
risultato adesso è pronto
