### ISSUE TITLE
impossibile accedere al servizio

### ISSUE THREAD

**Issue by peppereg** [italia/anpr#2968]
ciao,
ho provato a fare accesso all'ANPR ma ricevo l' errore credo noto:

![anpr Regano](https://user-images.githubusercontent.com/94685915/142612955-42fa68c2-cf2a-42ac-9bd3-2156ed684c38.PNG)

il mio comune, a domanda, mi ha risposto che non ci sono problemi sulla mia anagrafica.
il mio codice fiscale inizia con RGNTMS.
Potreste darmi supporto?
grazie mille

**Comment by cmigliardi** [comment]
gentile rgn...  ..... le consigliamo di rivolgersi al suo comune di competenza guidonia  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, 
che la scheda non sia duplicata, che esista in ANPR, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
