### ISSUE TITLE
WS3002 - per cittadini con due posizioni

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2969]
Buonasera,
invocando il servizio ws3002 per un cittadino con due posizioni, di cui una cancellata, riporta i dati quest'ultima ovvero quella cancellata.
Sarebbe opportuno avere la scheda anagrafica della posizione attiva magari con l'indicazione della presenza di altra posizione cancellata.
Grazie

**Comment by ncapozzi** [comment]
Buonasera
le due posizioni sono di competenza dello stesso comune oppure di comuni diversi?
In questo secondo caso dovete effettuare la ricerca nazionale (ricercaNazionale = 1 nella richiesta XML)
