### ISSUE TITLE
Problemi con numerazione civica e indicazioni particolari

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#297]
Corbetta, ambiente di produzione.

Buongiorno, vi è stata inviata questa segnalazione:
"Abbiamo riscontrato che l'individuo XXX XXX residente in Via Fogazzaro n. 0 km. 1,750 in ANPR ha l'indirizzo corretto mentre se si stampa un certificato di residenza l'indirizzo che appare è Via Fogazzaro" e la vostra risposta via mail è stata da parte della dott.ssa Vinzani:
"l’anomalia è dovuta al fatto che sia stato inserito il metrico nel campo lettera invece che nel campo metrico. Il civico ed il metrico sono poi in esclusiva (o uno o l’altro)."
Questa risposta però non risponde alla segnalazione perché 'km. 1,750' è stato inserito nel campo lettera e dev'essere considerato da ANPR come lettera e non come metrico, quindi non è alternativo al civico e dev'essere espresso in certificazione come indicato dal Comune.
Poi come chiarimento, noi intendiamo la numerazione civica a numero civico o metrica per tutta la via, cioè non può esistere una via dove una parte dei numeri siano numeri civici e una parte siano indicazioni metriche (è comprensibile la confusione che questo fatto genererebbe) mentre invece dalla mail della dott.ssa Vinzani sembra che in ANPR sia possibile, è così?
In anagrafe sovente sono presenti comunque indicazioni particolari dove la numerazione civica non esiste (residenze in roulotte o altri riferimenti), e questi finiscono sempre in un campo descrittivo come appunto la lettera o esponente1, avete indicazioni differenti per gestire questa casistica?
Grazie.
Luca Bonini

**Comment by gcarbonin** [comment]
Preciso meglio la risposta: ci sono 5 indirizzi del comune di Corbetta che hanno un civico pari a zero; 4 dei 5 indirizzi hanno il "metrico" riportato nel campo lettera.
Civico pari a zero o non valorizzato è interpretato dal SW che stampa i certificati come assenza di civico; questo fa si che tutti gli attributi propri del civico(tra cui la lettera)  non siano riportati.
Se anche eliminassimo il controllo sul civico, il certificato riporterebbe:
N. O Lettera: KM. 1,750.
E' ovvio che dobbiamo adottare delle convenzioni che siano comuni a tutti gli indirizzi.
Sul discorso di vie in parte con numero in parte con metrico, sono in alternativa sul **singolo indirizzo** e non sulla strada: a roma ad esempio, le strade consolari nel tratto urbano hanno un numero civico e da un certo punto in avanti utilizzano il metrico.
Nel caso in esame sarebbe corretto impostare il metrico e non civico = 0.
Per le residenze "strane",  userei interno o isolato che sono sempre riportati in stampa a prescindere da quanto viene indicato come civico o metrico. C'è anche un campo "note indirizzo" che al momento non viene stampato. Qualora si concordasse per questa soluzione (che ovviamente deve essere recepita da tutti) o qualsiasi altra si ritenesse di adottare, provvederemo ad allineare la stampa dei certificati.

**Comment by LucaBonini64** [comment]
A mio avviso il controllo sul civico dovrebbe essere eliminato in maniera che il certificato esca come da lei riportato (già veniva certificato nella stesso modo dal comune) per non avere problemi sul pregresso. Se per voi l'alternativa è sul singolo indirizzo possiamo prevederlo anche dentro l'applicativo per il futuro ma bonificare tutto il pre-esistente non è facilmente risolvibile.
Per quanto riguarda le residenze 'strane' sono d'accordo sul prendere una decisione comune però riguardo le soluzioni proposte le faccio notare che 'note indirizzo' è utilizzabile solo con 'tipo indirizzo'=9 (altro) mentre invece è l'indirizzo di residenza e 'isolato' è invece di soli 20 caratteri, mentre noi gestiamo per le residenze strane 255 caratteri. 
Per fare un esempio più comprensibile del km. 1,750 di Corbetta, soprattutto nel meridione abbiamo numerosi casi di assenza di numero civico e indicazione da certificare: 'Lottizzazione 1234 - impresa Bonini - palazzina A lato nord', con poi anche le indicazioni del 'CivicoInterno', forse la soluzione migliore sarebbe quella di aggiungere un campo descrittivo a livello di numero e metrico.

**Comment by LucaBonini64** [comment]
Buongiorno, visto che la presente chiamata continua ad essere in stato 'Evoluzione' e visto che il cliente ha urgenza di rilasciare il certificato con le indicazioni precedentemente contenute abbiamo provato ad attuare la sua soluzione ed inserire la descrizione 'speciale' nel campo isolato ma tale campo comunque non viene visualizzato nel certificato contrariamente a quanto da lei indicato. Vedi in Ambiente di Test, Comune di Barletta, IdOperazioneANPR 641160.

**Comment by gcarbonin** [comment]
Contattato il comune che non ha sollevato ulteriori problemi
