### ISSUE TITLE
Certificati in lingua straniera

### ISSUE THREAD

**Issue by seolop** [italia/anpr#2971]
Non riesco a trovare la opzione per ottenere i certificati in una seconda lingua , come mi sembra citato nella guida .
Si tratta di una mia svista oppure l' opzione non e' ancora disponibile ?
Grazie
Paolo

**Comment by mttfranci** [comment]
Salve, la seconda lingua è disponibile solo se l'opzione è attiva per il proprio comune di residenza.

Come riportato anche nella guida: 

![image](https://user-images.githubusercontent.com/29305782/142769251-c4a1a6d5-242e-40c8-907f-46a8361eb676.png)

Saluti

Assistenza ANPR
