### ISSUE TITLE
Impossibile mutare data di matrimonio

### ISSUE THREAD

**Issue by ParsecSalvatore** [italia/anpr#2973]
Per il comune di Gravina In Puglia per i coniugi HRNGBR73R13Z614H e MNFNNA72H68Z614G risulta impossibile la mutazione della data di matrimonio. Provando a rettificare la data di matrimonio correttamente in 13/04/2012, e andando a buon fine la suddetta operazione, la data resta comunque quella precedentemente immessa

**Comment by frmariani** [comment]
mi sembra che la situazione sia stata sanata, infatti alla consultazione visualizzo la data del matrimonio corretta.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
