### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by tbuzz89** [italia/anpr#2975]
![Screenshot_20211122-114148~2](https://user-images.githubusercontent.com/94813166/142882830-2d6d05bd-d9b0-47d2-99ab-b198b98fe11f.png)

Non riesco ad accedere al servizio ANPR, ho una credenziale SPID di PostID. Contattato Comune iscrizione AIRE (Schiavon-VI), nessun problema con la mia scheda anagrafica.

Mi chiamo Tiago Cardozo, CRDTGI, i sono do Stato estero.

**Comment by cmigliardi** [comment]
gentile signore  ..... le consigliamo di rivolgersi al suo comune di competenza ( di iscrizione all'aire)   per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
