### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by legentkiller011** [italia/anpr#2976]
ricevo questo messaggio quando provo ad accedere al portale:

-----------
Il tuo comune di residenza (o di iscrizione all'AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione "A che punto è il tuo Comune?" disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);

se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni.

-----------

il mio codice fiscale è giusto.
ho chiesto se c'è un'anomalia nei miei dati e lì, ma tutto sui miei dati è giusto.
il mio comune è ROMA che è in ANPR.

come posso risolvere il problema?

**Comment by cmigliardi** [comment]
cortesemente ci può fornire le prime 6 lettere  del codice fiscale ?   così da poter verificare la situazione ? 
grazie

**Comment by legentkiller011** [comment]
Si:
KHBPRM
Grazie!

**Comment by cmigliardi** [comment]
gentile  le consigliamo di rivolgersi al suo comune di competenza ROMA  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, che esista la scheda,  etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
