### ISSUE TITLE
Errore sulla data di prima iscrizione

### ISSUE THREAD

**Issue by CESARERAMADORI** [italia/anpr#2977]
Avendo visto che il soggetto 44296045 ha una data di prima iscrizione (17/12/2018) non coincidente con quella di nascita (06/12/2018) ( bambina italiana denunciata in Italia che dovrebbe avere per prima data di iscrizione la data di nascita stessa) ho provato con flusso 5014 per rettificare il dato. Il comune di prima iscrizione siamo noi.
Da il solito errore dovuto al fatto che vi sono eventi successivi alla data che si vuole introdurre come data di prima iscrizione (06/12/2018). In effetti la bambina ha appena mutato l'indirizzo di residenza unitamente a tutta la famiglia.
Domandiamo cortesemente come procedere perché appare oneroso annullare tutte le modifiche per poi reinviarle. (Sempre che sia la strada giusta).
Cordiali saluti
Cesare Ramadori

051843576

**Comment by frmariani** [comment]
Purtroppo non c'è modo di modificare la data di un'iscrizione per nascita se non annullando l'operazione stessa.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
