### ISSUE TITLE
annullamento operazione di collegamento CF

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#2978]
si può annullare un'operazione di collegamento codici fiscale eseguita erroneamente? se SI, come?

**Comment by frmariani** [comment]
l'operazione di collegamento non è annullabile con le funzionalità previste dalla web app di ANPR; nel caso può invertire la principalità con l'operazione di mutazione dei dati anagrafici (inversione di link).

Per annullare il collegamento può scrivere alla Direzione Centrale dell'Agenzia delle Entrate 
entrate.archivioanagrafico@agenziaentrate.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
