### ISSUE TITLE
Non e' stato possibile accedere al servizio

### ISSUE THREAD

**Issue by batchius** [italia/anpr#2979]
Buongiorno,
continuo a ricevere il messaggio "purtroppo non e' possibile accedere al servizio"
La mia situzione particolare con cui ho avuto spesso problemi in passato con la PA e; che il codice fiscale fa riferimento ad uno stato estero di nascita non piu' esistente, sostituito da altro stato.
Dato che lo SPID utilizza il codice fiscale, e altri dati, e lo stato di nascita sul mio documento di identita' non e' consistente con quello del mio CF, potrebbe esserci necessita' di riallineare i dati, in qualche modo?

![image](https://user-images.githubusercontent.com/95015916/143395116-6f5993ea-bac1-41de-8350-ebedc1c324a1.png)

**Comment by cmigliardi** [comment]
in ogni caso il comune deve controllare la scheda in ANPR  e confrontarla con i dati su spid che potrà fornire lei . finché i dati non sono congruenti - lei non potrà accedere . in quanto non riconosciuto in modo univoco

**Comment by batchius** [comment]
> buongiorno, cortesemente ci può fornire le prime 6 lettere del suo codice fiscale ? così possiamo fare dei controlli. grazie

BCCDNL

**Comment by cmigliardi** [comment]
si deve rivolgere al suo comune di iscrizione all'aire  per  far controllare la scheda - (fiorano al serio) -  in generale:  la scheda deve avere il CF  validato -  deve essere unica e non duplicata  -

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
