### ISSUE TITLE
Data origine famiglia/convivenza Codice: EF031

### ISSUE THREAD

**Issue by vpadadem** [italia/anpr#2980]
Buongiorno, 
durante la bonifica dell'anomalia ''Codice individuazione comune iscrizione: 0 inesistente sulla tabella di riferimento'' la webapp anpr restituisce l'errore: ''La data a partire dalla quale il soggetto appartiene alla famiglia/convivenza deve essere maggiore o uguale della data origine famiglia/convivenza Codice: EF031'' dov'è possibile rettificare la data di origine famiglia? Grazie

**Comment by rvinzani** [comment]
Per fornire assistenza sulla problematica sono necessarie ulteriori informazioni specifiche. Si prega pertanto di contattare il numero di assistenza ANPR 800863116
