### ISSUE TITLE
WS5001 - Iscrizione nucleo (AIRE) da altro comune subentrato

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2981]
Buongiorno
Comune Caserta 061022 PROD
ERRORE
EF002 Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata                        
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-25 11:54:56 , idOperazioneANPR 706104897

Il soggetto è iscritto in AIRE nell'altro  comune ma è rientrato dall'estero direttamente a Caserta.
L'errore, penso, sia dovuto al fatto che l'ID  famiglia è AIRE.
Come si deve agire per risolvere?
Grazie per la fattiva collaborazione

**Comment by ncapozzi** [comment]
Buonasera
dovete impostare
idFamigliaConvivenzaANPR = 48703883
tipoScheda=5 non 3 perchè la famiglia è ancora AIRE quando trasmettete la richiesta 5001.

**Comment by rinonasti** [comment]
Contestualmente viene modificata in famiglia APR ?
