### ISSUE TITLE
AIRE - ELENCHI ANOMALIE DA CORREGGERE

### ISSUE THREAD

**Issue by ValeriaRoa** [italia/anpr#2984]
Scaricando gli elenchi anomalie riferiti ai cittadini aire da anpr esce fuori un nominativo nella tabella posizioni senza indicazione del comune o dello stato estero di nascita nella tabella excel allegata il campo relativo al territorio non è popolato ma controllando nel gestionale lo stato è presente come è presente anche sulla scheda individuale del soggetto all'interno della web app (Stato URSS) 
sentita la nostra software house la stessa ci dice di lasciare così ...
come dobbiamo procedere?
grazie 

Roà Valeria - Comune di Lequio Tanaro Provincia di Cuneo (Piemonte)

**Comment by ncapozzi** [comment]
Buongiorno
Potete lasciare così
