### ISSUE TITLE
Problema di accesso al portale di ANPR

### ISSUE THREAD

**Issue by fpesar** [italia/anpr#2986]
![120000230-fde53500-bfa8-11eb-84c9-3dd67daeac57](https://user-images.githubusercontent.com/95082681/143595672-dc75c788-9150-40d7-92a8-024fe30c3966.png)
Buon pomeriggio a Voi,
il problema che qui stò evidenziando è quello di diversi altri utenti e quindi desidererei un vostro gentile intervento per conoscere le cause e le modalità di intervento ai fini della risoluzione del problema.
Prima di dover prender contatto con il mio comune di residenza iscritto ANPR (Anguillara Sabazia - Roma) vorrei sentire il vostro parere.
Il mio codice fiscale è PSRFBA mentre per mia madre, anch'essa residente nel medesimo comune, è BRRSVN.

In attesa di un vostro riscontro, ringrazio e porgo cordiali saluti.

**Comment by cmigliardi** [comment]
gentile  le consigliamo di rivolgersi al suo comune di competenza anguillara per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il "codice fiscale validato" da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.   
 
 
 
________________________________________

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by fpesar** [comment]
Grazie, verificherò quanto prima presso il mio comune di residenza, grazie!

Cordiali saluti
