### ISSUE TITLE
Cambio di indirizzo via portale nazionale

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#2989]
Salve, da più parti (prefettura inclusa) si conferma che il cambio di indirizzo potrà essere richiesto direttamente dai cittadini interessati tramite portale ANPR.
Ci sono indicazioni su come verrà implementato il servizio?

In particolare sarebbe utile sapere come l'ufficio d'anagrafe comunale riceverà i dati della domanda di cambio di indirizzo / iscrizione per implementare le corrette procedure informatiche interne, per esempio per esperire i controlli del caso anche in collaborazione con la polizia locale per i sopralluoghi di accertamento.

**Comment by franthemanIT** [comment]
Mi autorispondo: direi con i webservice P000 recentemente pubblicati fra la [documentazione tecnica ANPR](https://www.anagrafenazionale.interno.it/il-progetto/strumenti-di-lavoro/documentazione-tecnica/).

Andando avanti con il pensiero si potrebbe quasi pensare che tutto il procedimento come titolarità sia in capo al Ministero che quindi si fa carico anche degli aspetti documentali. Tradotto: il Comune non si deve preoccupare di protocollare alcunché, ci pensa il Ministero. Il Comune fa solo qualche operazione su ANPR (via WS o via webapp). Attendiamo maggiori dettagli...

**Comment by FilippoPapi** [comment]
salve sarà predisposta una apposita circolare da parte del Ministero
buona giornata
