### ISSUE TITLE
Errore EN077 in annullamento mutazione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#2990]
Comune di Sant'Agata li Battiati produzione,

tentando di annullare l'operazione ID ANPR 661412334 otteniamo l'errore in oggetto EN077.
ID dell'operazione di annullamento che fallisce è 709253212.
Non riusciamo però a capire quale sia l'operazione che blocca l'annullamento, potete aiutarci ?
Grazie

**Comment by rvinzani** [comment]
Dovreste annullare l'operazione con id 702790560, si tratta della cancellazione di un membro della famiglia
