### ISSUE TITLE
Problema accesso ANPR

### ISSUE THREAD

**Issue by MariateresaRega** [italia/anpr#2991]
Buongiorno,
Possiedo sia un’identità spid sia una cns, purtroppo però non riesco ad accedere al servizio.
Ho contattato il comune di residenza e mi dicono che le informazioni della mia anagrafica sono correttamente inserirete.
Anche l’identità spid non riscontra problemi.

Avete soluzioni da consigliarmi?
Di seguito il messaggio d’errore riscontrato.

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.
In contatto con il Comune di Mira (VE), non hanno riscontrato problemi con la scheda anagrafica. Anche la softhouse non ha riscontrato alcun problema.

Cosa devo fare? Il comune ha detto che non sa come aiutarmi.
Grazie.

**Comment by cmigliardi** [comment]
cortesemente ci può dare  le prime 6 lettere  del suo codice fiscale ? grazie

**Comment by MariateresaRega** [comment]
rgzmtr

**Comment by cmigliardi** [comment]
gentile signora  le consigliamo di rivolgersi al suo comune di competenza Bianzano per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
