### ISSUE TITLE
WS1002 -ISCRIZIONE PER ALTRI MOTIVI 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#2992]
Buongiorno,
COMUNE DI CASERTA PROD

EAV31 - CF presente ma dati anagrafici non congruenti
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-11-30 11:36:26 , idOperazioneANPR 710592835

Il soggetto è in AE con nome errato e non replicabile su ANPR 
PAULA - MIHAELA  (spazio prima e dopo il segno -)
come è risolvibile?
Grazie

**Comment by rvinzani** [comment]
Può iscrivere il soggetto utilizzando il campo gestione CF = 3 (senza validazione di Agenzia Entrate). Successivamente dalla web app di ANPR, dal menù Utilità e Notifiche->Risoluzione disallineamenti con Agenzia Entrate, inserisce il CF, preme il tasto Cerca, seleziona il soggetto dalla lente e nella pagina successiva conferma i dati di ANPR

**Comment by rinonasti** [comment]
ok risolto con le Vs. indicazioni.
Grazie
