### ISSUE TITLE
Modifica gradio di parentela unico componente famiglia

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#2996]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Buongiorno
dobbiamo modificare il grado di parentela di un soggetto unico componente di una famiglia.

Il sistema restituisce l'errore allegato.
![cambioGradoParentela](https://user-images.githubusercontent.com/54433203/144215181-1cae7524-895a-41ef-960f-f2b13a722595.png)

Cosa dobbiamo fare ?

**Comment by frmariani** [comment]
nella sezione "Elenco soggetti" dovete inserire la spunta nella colonna "seleziona soggetto"
