### ISSUE TITLE
Doppia iscrizione nel Comune di Napoli ed in quello di Valsamoggia

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#2997]
La persona con Num. Ind. ANPR 66284017 é stata iscritta nell’APR/ANPR del comune di Valsamoggia il 23/08/2019 per immigrazione dal  comune di Napoli, il cui subentro in ANPR il 21/09/2019 ha generato la duplicazione (Num. Ind. ANPR del comune di Napoli é 70079006).
A Napoli era iscritta dall'11/10/1985, quindi direi siano i colleghi di quel comune a doverla cancellare per duplice iscrizione con decorrenza 23/08/2019.
Non riusciamo però a trovare un contatto al quale richiedere di provvedere. Potete darmi qualche indicazione?

**Comment by rvinzani** [comment]
Napoli ha effettuato la cancellazione. Saluti
