### ISSUE TITLE
Impossibilità unificazione codifi fiscali

### ISSUE THREAD

**Issue by maumarc64** [italia/anpr#2999]
Per gli ID ANPR 196387678 e  196372 607 (nuovi nati) è stata inviata ad ANPR comunicazione con luogo nascita errato con conseguenza validazione del codice fiscale: i luoghi di nascita sono stati poi corretti in ANPR modalità web-application, dove viene segnalata la necessità di procedere all'unificazione.

Entrando in ANPR modalità web service e cercando di unificare i codici, compare il messaggio: Soggetto non trovato per i criteri indicati o già validato o esiste un'operazione in sospeso per il soggetto.

Nella web-application, i messaggi sono i seguenti:

Esito AN: Informazioni sull'operazione da fornire in caso di assistenza : 2021-12-01 13:39:09 , idOperazioneANPR 712082705 (Codice: EN527)

Esito AN: Informazioni sull'operazione da fornire in caso di assistenza : 2021-12-01 13:41:52 , idOperazioneANPR 712084957 (Codice: EN527)

Come risolvere?

Grazie.

Maurizio Marchese-Anagrafe Comune di Muggiò (MB) subentrato il 31-03-2021

**Comment by rvinzani** [comment]
Le risponderemo con il ticket assegnatole n. 23539658. La prego per le prossime volte, per problemi specifici, di rivolgersi al nostro servizio di assistenza 800863116.
