### ISSUE TITLE
Errore non bloccante per Stato estero cessato

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#3]
In ambiente di Test siamo riusciti a certificare e movimentare una scheda con stato estero di nascita Cessato (Descrizione :Yugoslavia CodiceIstat=224).  Sappiamo che avremmo dovuto usare in questi casi il codice 998.  L’errore non è bloccante in fase di movimentazione.  E’ così anche per l’ambiente di subentro?

**Comment by gcarbonin** [comment]
Per i controlli di validità del codice fiscale, ANPR si basa esclusivamente su AE

**Comment by gcarbonin** [comment]
Si per tutte le posizioni già iscritte. Per eventi che avvengono dopo il subentro (ad esempio immigrazione dall'estero) si accetteranno soltanto stati  esistenti.
