### ISSUE TITLE
Web- App - Consultazione scheda individuale - Elenco operazioni

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#30]
Data test- 15/03/2017 - Ambiente test (dptest)
Abbiamo effettuato diverse operazioni su un soggetto, alcune sono andate a buon fine e altre hanno dato errore.
Quindi su tale soggetto abbiamo richiamato la Funzionalità Consultazione / consultazione scheda individuale;  in Elenco operazioni nella colonna Esito della Registrazione compare sempre "Completata con Esito positivo" anche per quelle non andate a buon fine. Abbiamo aperto per tutte il file XML presente nella colonna "Esito della risposta" e in quelli errati è correttamente riportato il messaggio di errore (ad esempio .. "EN111- indicare il procedimento collegato")
  
Grazie
Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
L'errore che avete indicato (EN111) è un'anomalia non un errore bloccante e quindi è normale che l'operazione sia presente tra quelle concluse con esito positivo;forse in questo caso sarebbe più corretto mettere "Completata con esito positivo e warning". In ogni caso per il futuro sarebbe utile per noi avere l'identificativo dell'operazione ANPR (presente nell'elenco operazioni) che non vi sembra coerente per poter controllare meglio ed eventualmente intervenire.

**Comment by annamariaGillone** [comment]
Abbiamo riprodotto il caso in oggetto. L'ID operazione è 440808.
Grazie
Annamaria

**Comment by gcarbonin** [comment]
Grazie. Abbiamo individuato il problema. Le prossime operazioni dello stesso tipo riporteranno "Completata con esito positivo e warning".
