### ISSUE TITLE
Cessazione Unione Civile

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#300]
Nella issue 272 si legge che <<il motivo di scioglimento ESCLUSO IL DECESSO deve essere inferiore a 31>> in riferimento allo scioglimento delle unioni civili.
E' un refuso, perché fra i motivi con codice < 31 c'è anche il "4 - Matrimonio", che non è un motivo di scioglimento dell'unione civile.

1	Accordo di scioglimento (anche unilaterale)
2	Convenzione di negoziazione assistita
3	Sentenza
4	Matrimonio
31	Accordo tra le parti
32	Recesso unilaterale
34	Matrimonio/unione civile
98	Decesso del convivente/unito civilmente
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
La documentazione è stata aggionata.
