### ISSUE TITLE
Variazione dati generici - Nominativo

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3000]
COMUNE DI PANTIGLIATE

Rif. Nadia Ferrari

Abbiamo inviato una variazione 5008 per cambio nominativo il WS restituisce l'errore 

La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione  sul soggetto/famiglia

Alleghiamo i file richiesta ed esito.

Restiamo in attesa digentile riscontro.

Saluti
[EsitoWS_Richiesta5008.txt](https://github.com/italia/anpr/files/7640255/EsitoWS_Richiesta5008.txt)
[Richiesta5008.txt](https://github.com/italia/anpr/files/7640256/Richiesta5008.txt)

**Comment by amollicone1982** [comment]
L'errore indica che non troviamo il soggetto in qaunto voi indicate come cognome IEZZI MAIORANO mentre noi sulla base dati abbiamo IEZZI. In generalitaPerRicerca mettete come cognome solo IEZZI e il soggetto sarà trovato
