### ISSUE TITLE
Segnalazione cittadino

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3002]
Buona sera,
un cittadino  ha contattato l'Ufficio AIRE per segnalare:

Buongiorno,
 
Vi scrivo per segnalarvi l’impossibilità di accedere al sito ANPR per vedere i dati di mia madre.
Vi allego la schermata con l’errore dopo avere eseguito l’accesso con lo SPID.

![Anpr](https://user-images.githubusercontent.com/28134762/144458189-a17a031b-e584-4081-acd7-ae244bb5b81d.jpg)

La segnalazioen rimanda il cittadino al Comune; tutte le verifiche effettuate non evidenziano alcun errore o disallineamento. 
Il soggetto è regolarmente presente in ANPR con ID 28399725

Quali altri controlli potremmo effettuare?
Grazie

UPI TORINO

**Comment by cmigliardi** [comment]
Buongiorno, 
dai controlli ci risulta che il  codice fiscale  è  cambiato il 22 novembre ma da SPID arriva quello vecchio BRRMGH......L    e non quello nuovo  che termina  con la lettera  V   -   spero di esser stata  chiara visto che non possiamo esporre dati -

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
