### ISSUE TITLE
Inserimento coabitazione dopo Mutazione APR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3003]
Buongiorno,
sono a chiederere se sia possibile attivare la coabitazione anche dopo avere fatto la Mutazione APR

Grazie
Claudio Vignati

**Comment by frmariani** [comment]
Con l'operazione di Mutazione famiglia/convivenza, tipo mutazione motivo famiglia/specie convivenza (WS 5001 - 3), è possibile inserire l'informazione di "presenza famiglia coabitante"  SI/NO.

**Comment by cvignati** [comment]
> Con l'operazione di Mutazione famiglia/convivenza, tipo mutazione motivo famiglia/specie convivenza (WS 5001 - 3), è possibile inserire l'informazione di "presenza famiglia coabitante" SI/NO.

Perfetto, ma come faccio a collegare le 2 famiglie coabitanti?

**Comment by frmariani** [comment]
cosa intende per "collegare le due famiglie coabitanti" ? l'indirizzo sarà lo stesso immagino, deve solo inserire l'informazione di presenza famiglia coabitante.
mi può portare un esempio così cerco di interpretare meglio la richiesta per favore ?

**Comment by cvignati** [comment]
In ANPR viene sono indicato se una famiglia è coabitante, non vengono collegate le 2 famiglie?

**Comment by frmariani** [comment]
ripeto dovrebbe specificare cosa intende per "collegare le due famiglie".
se le due famiglie hanno lo stesso indirizzo ma due identificativi anpr della famiglia diversi e vorreste che ne avessero uno solo, dovete effettuare il cambio di residenza; se le due famiglie hanno lo stesso indirizzo ma devono mantenere i due identificativi anpr della famiglia diversi, dovete inserire  soltanto l'informazione di famiglia coabitante.
Per essere più chiara ho bisogno del caso specifico.

**Comment by cvignati** [comment]
Le famiglie 21623975 e 21625358 hanno flag famiglia coabitante attiva.
Sono, rispettivamente, la famiglia dell'anziana e la famiglia della badante. Nel mio gestionale, interrogando le famiglie, vedo rispettivamente la famiglia coabitante. Esiste un collegamento tra le 2 famiglie. e' gestito anche in ANPR?

**Comment by frmariani** [comment]
in Anpr è presente soltanto l'informazione di famiglia coabitante senza collegamento tra le famiglie
