### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by alupat** [italia/anpr#3005]
Buongiorno,

non riesco ad entrare in ANPR, 
[https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth](https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth)

in contatto con il Consolato in Brasile, non hanno riscontrato problemi con la scheda anagrafica AIRE.

sono iscrito nella Comune di Castrezatto (BS) é in ANPR dal 04/12/2019.

Alessandro Lupatini
Nato in Brasile
le prime 6 lettere del mio codice fiscale: LPTLSN

Risultato della verifica nello sito dell'agenzia entrate:
La verifica per il codice fiscale LPTLS* ha prodotto il seguente risultato:
CODICE FISCALE VALIDO

Cosa devo fare? Il consolato ha detto che non sa come aiutarmi.

Grazie per l'aiuto.

**Comment by cmigliardi** [comment]
Buongiorno, 
per accedere al portale   la url  è   https://www.anagrafenazionale.interno.it     e puo' accedere  o con cie- cns - spid  - 
inoltre 
gentile signore  le consigliamo di rivolgersi al suo comune di competenza Castrezzato  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
