### ISSUE TITLE
DOPPIA POSIZIONE IN ANPR CON IL COMUNE DI NAPOLI

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#3006]
Buonasera
si segnala che in ANPR esiste una doppia posizione con il Comune di Napoli del soggetto ID  6271576 con data iscrizione 20/03/2017.
Nonostante le richieste di cancellazione inviate  al Comune di Napoli tramite pec in data 15/10/2019, il soggetto risulta ancora con doppia posizione.
Si richiede gentilmente di sollecitare il Comune di Napoli a risolvere il problema, in quanto al cittadino non è stato possibile rilasciare un certificato tramite Anpr.
Grazie
UFFICIO ANAGRAFE FAENZA 
BARBARA MALAVOLTI

**Comment by rvinzani** [comment]
Sollecito inviato. Saluti
