### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by alupat** [italia/anpr#3007]
#3005 

Ho contattato il Comune di Castrezzato (BS) e non hanno riscontrato problemi con la scheda anagrafica. (AIRE)

Alessandro Lupatini
Nato in Brasile
le prime 6 lettere del mio codice fiscale: LPTLSN

potete per favore fare questa verifica?

Grazie per l'aiuto.

**Comment by cmigliardi** [comment]
buonasera 
purtroppo noi non possiamo dirle il motivo esatto - ma le assicuro che nell'elenco delle possibili cause c'è anche il suo caso 
quindi la invito a contattare il comune che DEVE  controllare la scheda  in ANPR e non localmente .

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
