### ISSUE TITLE
Per conto del Comune di CAMERANO - Errore EN122 a seguito di servizio 7002

### ISSUE THREAD

**Issue by tuchino1969** [italia/anpr#3008]
A seguito di richiesta servizio 4001 e successiva richiesta servizio 7002 con id operazione ANPR 718291540 si ottiene errore EN122 tipologia E: si allegano richiesta.xml e risposta.xml del servizio 7002 (in formato .txt).
Si chiede di sbloccare la richiesta.

Grazie.
[richiesta.XML.txt](https://github.com/italia/anpr/files/7683156/richiesta.XML.txt)
[risposta.XML.txt](https://github.com/italia/anpr/files/7683157/risposta.XML.txt)

**Comment by amollicone1982** [comment]
esito pronto
