### ISSUE TITLE
Problema certificato per individuo cancellato per doppia iscrizione. Urgente

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#3009]
Salve, 
Comune di Giugliano produzione
Con l'operazione con id 718362637 è stato richiesto un certificato per un individuo presente in Anpr e residente a Giugliano. 
La risposta ottenuta è : 
<codiceErroreAnomalia>EN469</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Il soggetto risulta iscritto anche nel comune di 063060 Con data iscrizione 20/11/2014</testoErroreAnomalia>

L'individuo per cui si richiede il certificato ha id 87135438 e nella request viene passato l'id corretto. 

L'id dell'anagrafica che viene individuato nella response è 88677009

Da una consultazione di tale individuo risulta correttamente cancellato dall'altro Comune per doppia iscrizione. 

Si richiede lo sblocco per l'id 87135438 e una verifica per gli altri 2 componenti la famiglia che presentano la medesima situazione 

87135437 residente a giugliano 88677008 cancellato in anpr

87135439 residente a giugliano 88677004 cancellato in anpr

La richiesta riveste carattere d'urgenza in quanto i cittadini hanno urgente necessità di un certificato di Residenza e di stato di famiglia

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare per favore a richiedere nuovamente il certificato?

**Comment by mrabuano** [comment]
Salve, riceviamo ancora lo stesso errore. 
la richiesta è stata inviata 1 minuto fa

**Comment by ncapozzi** [comment]
mi può indicare l'idoperazione per favore?

**Comment by ncapozzi** [comment]
Potete riprovare

**Comment by mrabuano** [comment]
Confermo che è stato possibile procedere con la certificazione

Grazie e buona giornata
