### ISSUE TITLE
Servizi al Cittadino - Purtroppo non is stato possibile accedere al servizio ANPR

### ISSUE THREAD

**Issue by ValenPry** [italia/anpr#3011]
Ciao! Qualcuno potrebbe aiutarmi con questo problema? Non riesco a comunicare con il comune di Rosello e sono all'estero

**Il mio codice fiscale è PRYVNT**

Grazie mille in anticipo

![error ANPR -IT](https://user-images.githubusercontent.com/95878449/145454973-a2983d8a-ddb1-4c23-bdeb-349293cdd98e.JPG)

**Comment by cmigliardi** [comment]
gentile signore ..... le consigliamo di rivolgersi al suo comune di competenza Rosello  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
