### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio (una anomalia nei tuoi dati)

### ISSUE THREAD

**Issue by redarrow81** [italia/anpr#3012]
![immagine](https://user-images.githubusercontent.com/60442395/145459007-b205fffe-293e-4fe0-93db-2f217a4ab6de.png)

Salve,
come ho visto fare a diversi altri utenti, segnalo il suddetto problema di accesso ai servizi.
Il mio comune di residenza iscritto ANPR è Camerano (AN).
I codici fiscali con cui non riesco ad accedere iniziano per TCCLSS e TCCMLS.

In attesa di un vostro riscontro, ringrazio e porgo cordiali saluti.

**Comment by cmigliardi** [comment]
gentile signora  le consigliamo di rivolgersi al suo comune di competenza Camerano  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
