### ISSUE TITLE
Cittadino iscritto in Anagrafe Temporanea di altro comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3013]
COMUNE DI PANTIGLIATE
Rif.: Nadia Ferrari

Buongiorno
volevo sapere come possiamo indicare tramite la WA di ANPR che un cittadino residente nel Comune di Pantigiliate è iscritto nell'anagrafe temporanea di un altro comune.

Resto in attesa di gentile riscontro.
Cordili saluti

**Comment by rvinzani** [comment]
ANPR tramite WA (sezione Utilità e notifiche->Residenze temporanee) gestisce l'iscrizione dei soggetti residenti temporaneamente in un archivio dei temporanei. Interrogando il soggetto in tale archivio si avrà l'evidenza della sua residenza effettiva ma non il contrario
