### ISSUE TITLE
ANPR - informazioni per presubentro a seguito di cambio swhouse

### ISSUE THREAD

**Issue by comunedisondrio** [italia/anpr#3014]
Buongiorno,
sono Livio Tirone, dirigente responsabile dei servizi demografici del Comune di Sondrio.

Il comune di Sondrio è subentrato in ANPR nell'ottobre 2018.

Attualmente siamo in fase di cambio di swhouse e per poter fare le prove abbiamo la necessità di fare un nuovo pre-subentro.

Possiamo procedere dalla webapp in pre-subentro cancellando quello presente e facendone uno nuovo?

Ovviamente non opereremo in ambiente di subentro.

In attesa di un riscontro, si porgono cordiali saluti

Livio Tirone
Dirigente servizi Demografici Comune di Sondrio

**Comment by cmigliardi** [comment]
Buongiorno, 
certamente,  potete   procedere dalla webapp in pre-subentro cancellando quello presente e facendone uno nuovo. 
se avrete  necessità  di uno scarico massivo per la nuova casa sw - La  invito ad avvisarci per tempo, inoltre  abbiamo necessità di aggiornare la banca dati, quindi dovrebbe fornirci il nome della nuova casa sw. se non vuole dare queste informazioni su questo canale - può scrivermi alla casella    cmigliardi@sogei.it      RingraziandoLa per la  collaborazione, porgo cordiali saluti   Dott.ssa  Migliardi

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
