### ISSUE TITLE
PROBLEMA ACCESSO ALLA WEBAPP

### ISSUE THREAD

**Issue by Pellet1285** [italia/anpr#3015]
Si richiede assistenza in quanto tentando di accedere alla WEB APP il sistema restituisce il seguente errore: dp2.anpr.interno,it non ha accettato il certificato oppure non è stato fornito uno

**Comment by cmigliardi** [comment]
buongiorno cortesemente ci può fornire un recapito per poterla contattare ?  e anche il nome del comune ? grazie  in anticipo

**Comment by Pellet1285** [comment]
3396775237 comune di Pomigliano d'Arco

**Comment by cmigliardi** [comment]
grazie - la faccio contattare  -

**Comment by cmigliardi** [comment]
mi dicono che avete risolto . bene
la issue viene chiusa.
