### ISSUE TITLE
rettifica dati matrimonio incompleti

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#3016]
Non riesco a rettificare i dati del matrimonio di una residente perché sia nel software che usiamo (Civilia Next) sia sulla web app di ANPR ricevo errori.
Sulla web app devo procedere con mutazione tutti i dati  e poi rettifica o devo prima eliminare i dati del matrimonio e poi mutazione tutti i dati? Chiedo indicazioni precise sulla procedura da seguire. Un messaggio di errore che ricevo dalla web app è "Alla data 21-08-2017 il soggetto xx risulta gia' coniugato o unito civilmente con un altro soggetto (Codice: EN272)
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-12-10 22:10:46 , idOperazioneANPR 720362222 (Codice: EN527)"

**Comment by frmariani** [comment]
l'operazione di modifica dei dati del matrimonio risulta correttamente effettuata.
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
