### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by jusfb** [italia/anpr#3019]
Salve, Matteo, @mttfranci

Potete aiutarmi?
nessuno può risolvere questo problema di accesso ad ANPR (https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth)

Per favore, potete fare una verifica nel mio codice fiscale ?

Julianne Freire de Souza
Nata in Brasile
le prime 6 lettere del mio codice fiscale:  FRRJNN
Comune di Polverara (PD)

Grazie Mille!!

**Comment by mttfranci** [comment]
Buongiorno, dovremmo aver individuato il suo codice fiscale e sembrerebbe che nessuna scheda con i suoi dai sia presente in ANPR, nè come residente nè come AIRE.
Le consigliamo di rivolgerci al comune competente per verificare tale situazione.
Saluti

Assistenza ANPR

**Comment by alexandredebiasi** [comment]
Salve, Matteo, @mttfranci

Anch'io non riesco ad accedere ai Servizi al Cittadino in ANPR. Dopo l'accesso con SPID, viene presentato questo messaggio:

"se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni."

Purtroppo, il Comune non è stato capace di aiutarmi per tale situazione.

Alexandre Debiasi
Nato in Brasile
le prime 6 lettere del mio codice fiscale: PTITSH
Comune di Ala (TN)

Ti ringrazio anticipatamente per l'aiuto.
