### ISSUE TITLE
Difficoltà a usare monitoraggio operazioni WA

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#302]
Ambiente di test, comune di Potenza Picena.
Nell'ambito di test dei risultati restituiti dai web services, sono andato a testare il monitoraggio operazioni della wa, e spesso non mi restituisce risultati.
Esempio il certificato emesso il 19.9 alle ore 12:05:15  idOperazioneANPR 582517, non riesco a estrarlo dal monitoraggio ne con una selezione per data, ne con una selezione per id anpr.

**Comment by gcarbonin** [comment]
Provvediamo a verificare

**Comment by gcarbonin** [comment]
Da lunedì sarà possibile riprovare

**Comment by MarcoMigliori** [comment]
Ho riprovato (per ora solo la voce "certificazione"), ma continuo a non ottenere risultati dai vari tentativi di ricerca.

**Comment by rnapoli1983** [comment]
Potete riprovare.

**Comment by MarcoMigliori** [comment]
Riutilizzo lo stesso thread per una diversa segnalazione.
Problema da WA, da WS si comporta diversamente.
Ambiente di test, loggato come comune 043043.

Eseguo ricerca per "identificativo ANPR da" 4746385 a 4746389, non trovo nulla (mi attendevo il 4746387 che trovo via ws).
Eseguo ricerca per "identificativo COMUNE" da 16114 a (non indico niente).
Mi mostra due righe con id comune 16193 e 16188
