### ISSUE TITLE
Smarrimento seconda parte PIN e PUK

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3021]
Buongiorno

causa smarrimento, richiedo la seconda parte del PIN e del PUK della smart card ANPR
Numero seriale 039014 1207100000032166.
Comune di Ravenna (RA)

**Comment by Leonforte** [comment]
Buongiorno, la seconda parte delle credenziali è stata inviata a katiavacchi@comune.ravenna.it , buon lavoro, saluti
