### ISSUE TITLE
RISOLUZIONE ANOMALIA "TIPO ELETTORE NON CONOSCIUTO" NEL CASO DI UN ELETTORE AIRE

### ISSUE THREAD

**Issue by PoddaManuela** [italia/anpr#3023]
Buongiorno,
Comune di Settimo San Pietro (CA), Manuela Podda. 
Dal portale ANPR su UTILITA' NOTIFICHE - DOWNLOAD - TIPO FILE - ho rilevato anomalia per quanto concerne un elettore AIRE come "Tipo elettore non conosciuto". Come posso risolvere? Il mio numero di telefono è 070/7691218

Ringrazio anticipatamente, 
Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
l'anomalia è stata rilevata all'elaborazione dell'elenco unico del 30/07/2021. Qualora nel frattempo il Tipo elettore sia stato valorizzato per il cittadino in ANPR non deve tenere conto della segnalazione. Se invece il Tipo elettore deve ancora essere aggiornato dovete effettuare una mutazione tutti dati (WS 5008) con tipo mutazione = 5 Liste e il campo ELETTORE = S, N o P (PERSO IL DIRITTO DI VOTO). L'operazione può essere effettuata dal gestionale del Comune se la prevede oppure dalla web app di ANPR.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
