### ISSUE TITLE
Rejected by policy in interazione macchina-macchina - URGENTE

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3024]
Comune di Brembate, ambiente di produzione.

Eseguendo una qualsiasi operazione WS di tipo macchina-macchina (ovvero usando come certificato di postazione il certificato "CO"),  con un qualsiasi utente censito dal comune, il servizio risponde con un errore "Rejected by policy (from client)".
Le interazioni uomo-macchina (usando come certificato di postazione uno dei certificati "PC") invece funzionano correttamente.

@Leonforte @cmigliardi  Potete aiutarci a risolvere il problema, abbiamo un'attività importante bloccata ?

Grazie

**Comment by cmigliardi** [comment]
ci siamo sentiti  con Marini ( verificato ip -  profili utenti etc....)   mi ha scritto   che avete  sostituito il certificato  - aggiungo la risposta di Marini 
Sostituito il certificato del server; ora sembra funzionare tutto correttamente.

**Comment by cmigliardi** [comment]
la issue viene chiusa
