### ISSUE TITLE
Errore in annullamento mutazione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3025]
Comune di Pedrengo produzione,

tentando di annullare l'operazione ID ANPR 658077087 otteniamo l'errore in oggetto EN077.
ID dell'operazione di annullamento che fallisce è 724421636.
Non riusciamo però a capire quale sia l'operazione che blocca l'annullamento, potete aiutarci ?
Grazie

**Comment by ncapozzi** [comment]
Buongiorno
sulla famiglia di partenza id 52379897 sono state eseguite 2 mutazioni 5001 (id 659044627 e 710732739) successivamente al cambio di residenza id 658077087 che volete annullare, come dovreste poter vedere anche voi andando in consultazione sull'intestatario idsoggetto 92384337. 
In generale nel caso di errore EN077 sull'annullamento di un cambio di residenza è opportuno verificare se sono state eseguite nel frattempo mutazioni sulla famiglia di partenza.
Potete provare ad annullare nell'ordine 710732739, 659044627 e 658077087 e poi ripetere i due 5001.
