### ISSUE TITLE
[5008] Mutazione dati da WebApp - Operazione non effettuabile (Codice: 999)

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#3026]
Per il Comune di NASINO (SV) non riusciamo ad attribuire un codice fiscale a soggetto AIRE, direttamente da WebApp
Sia come variazione dati che come rettifica
Il soggetto non esiste in Agenzia delle Entrate e già in altri casi abbiamo utilizzato con successo questa procedura per l'attribuzione del codice fiscale

Questo il messaggio di errore:
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-12-16 10:33:56 , idOperazioneANPR 725035571 (Codice: EN527)

Cosa possiamo verificare?

Grazie

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by ncapozzi** [comment]
Buongiorno
potete riprovare per favore ad eseguire l'operazione?

**Comment by ncapozzi** [comment]
Buongiorno,
non avendo ricevuto ulteriori riscontri si chiude la issue.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
