### ISSUE TITLE
URGENTE PER EMISSIONE C.I. - DISALLINEAMENTO con AE non RISOLVIBILE

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#3029]
Buongiorno per il nostro Cliente, Comune di San Giovanni in Persiceto ci viene segnalato il seguente problema. 

Per il soggetto ID ANPR 78867497 subentrato con Stato Estero SERBIA - MONTENEGRO cod. stato 998 NON ATTRIBUIBILE ma con CF validato da AE riportante il codice catastale Z118 (IUGOSLAVIA) non è stato possibile allineare la posizione con AE poichè da WebApp da  Risoluzione disallineamenti con AE il soggetto si presenta come in allegato con il dato di AE con stato estero IUGOSLAVIA ed il dato ANPR con stato estero SERBIA-MONTENEGRO. Il sistema consente di Confermare il dato di AE ed operando in questa maniera viene data segnalazione di Operazione eseguita CF Allineato (codice 00), ma in realtà il disallineamento 
non scompare e non viene effettuata alcuna mutazione dello stato estero da SERBIA-MONTENEGRO a IUGOSLAVIA. (verificato anche da Consultazione scheda individuale da Webapp). 
Abbiamo provato, a distanza di 24ore dalla sopracitata conferma, alla mutazione di tutti i dati attribuendo lo stato corretto ma l'operazione non va a buon fine segnala errore: Soggetto non individuato in AT - Codice fiscale non variato (codice: EAM12).
Questo errore lo abbiamo rilevato in vari problemi su questa piattaforma ma non abbiamo trovato la relativa soluzione. 

Vi chiediamo di intervenire per sbloccare l'allineamento di tale soggetto ID ANPR 78867497 e della moglie ID ANPR 78867501 da trattare anch'essa per allinearla allo Stato risultante in AT.

Contattare Sig. ra Chiara Zocca al nr 051-6812726 oggi fino alle 15:00 domani dalle 08:30 alle 13:00 
Segnaliamo che l'utente ha già contattato il vostro numero verde ma non sono riusciti a risolvere. 

Vi chiediamo cortesemente di intervenire con urgenza perchè il soggetto deve rinnovare la carta di identità. 

Resto a disposizione per eventuali chiarimenti se necessari. 
Grazie 
Cordiali saluti 

Cinzia Girelli
Cell. 3346216774
GPI Spa

![Disallineamento](https://user-images.githubusercontent.com/57626427/146896831-81a222d7-fede-42cd-aa7d-0da6b4e6a125.JPG)

**Comment by ncapozzi** [comment]
Buongiorno è stata contattata la Sig.ra Zocca per la risoluzione della problematica segnalata.
Si invita a non esporre i dati anagrafici dei cittadini nelle issue nel rispetto delle norme sulla privacy.
Inoltre per ulteriori richieste di assistenza relative ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
