### ISSUE TITLE
Refuso documentazione?

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#303]
Se volete aggiornarlo per la prossima volta, presumo che le righe in grassetto dovrebbero cominciare da 1.
Documento MI-14-AN-01    PAG. 127 DI 192

15.1.1 FUNZIONALITÀ
Come descritto nel paragrafo precedente, i servizi di ANPR integrano in modo
trasparente per il comune un servizio cooperativo di AE che prevede una serie di
operazioni sul codice fiscale:
**4. attribuzione del codice fiscale;
5. annullamento di un codice fiscale in precedenza attribuito;
6. verifica di congruenza del codice fiscale;
7. variazione dei dati anagrafici (che potrebbe dare origine ad un nuovo CF).**
Le operazioni di cui ai **punti 1e 2** sono richieste esclusivamente dal comune; le
restanti sono richiamate automaticamente da ANPR in funzione della
registrazione effettuata dal comune.

**Comment by ncapozzi** [comment]
Il documento è stato corretto
