### ISSUE TITLE
Problema accesso 

### ISSUE THREAD

**Issue by ste-90** [italia/anpr#3030]
Buongiorno, quando provo ad accedere al portale per scaricare un certificato dopo che faccio l'accesso tramite spid ,il sito mi restituisce errore dicendomi sempre "Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:
Il tuo comune di residenza (o di iscrizione all'AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione "A che punto è il tuo Comune?" disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni.". Ho già verificato tramite il mio comune e per loro è tutto ok. Gentilmente potreste verificare voi? Le iniziali del mio codice fiscale sono MRNSFN e comune di residenza Ronchi dei legionari. In attesa di un vostro riscontro, ringrazio.

**Comment by cmigliardi** [comment]
Buongiorno,  gentile Signore  le consigliamo di rivolgersi al suo comune di competenza Ronchi dei legionari  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
