### ISSUE TITLE
Urgente - Mutazione residenza bloccata da doppia iscrizione

### ISSUE THREAD

**Issue by SalsiCesena** [italia/anpr#3032]
Buongiorno,

stiamo provando ad inviare una mutazione di residenza per l'individuo id scheda soggetto anpr => 111016197, id famiglia anpr 65747420 proveniente da Pescara e ci dà il seguente errore:

Il soggetto risulta iscritto anche nel comune di PESCARA Con data iscrizione 26-02-2020
Informazioni sull'operazione da fornire in caso di assistenza : data 2021-12-22 10:57:50 , idOperazioneANPR 730460475

Abbiamo provato a contattare Napoli per richiederne la cancellazione, ma non rispondono.

Potreste intervenire direttamente voi?

La richiesta riveste carattere d'urgenza in quanto la cittadina non ha nessun documento in corso di validità.

Si ringrazia
Salsi Sergio Comune di Cesena
TEL 0547/356252

**Comment by ncapozzi** [comment]
Buongiorno,
la cancellazione per doppia iscrizione deve essere effettuata dal Comune di Napoli. Alla pagina https://www.comune.napoli.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/16831 sono reperibili diversi recapiti telefonici e indirizzi email anche pec.
