### ISSUE TITLE
Attribuzione codice fiscale in assenza permesso di soggiorno

### ISSUE THREAD

**Issue by maumarc64** [italia/anpr#3033]
Per l'ID ANPR 196371634 quest'ufficio ha proceduto all'iscrizione in ANPR con provenienza dall'estero non avvedendosi del fatto che si trattava di un cittadino straniero con in corso pratica di emersione dal lavoro irregolare e come tale ancora in possesso di codice fiscale provvisorio numerico.

E' così partita  comunicazione con codice fiscale calcolato (che dovrebbe corrispondere a quello che verrà assegnato in sede di rilascio del permesso di soggiorno) che risulta validato dall'AE.

Ora il locale ufficio territoriale dell'AE ci chiede di ripristinare la situazione.

Come è possibile procedere?

Grazie.

Maurizio Marchese-Anagrafe Comune di Muggiò (MB) subentrato il 31-03-2021

**Comment by ncapozzi** [comment]
Contattato il Sig. Marchese e fornita informativa richiesta.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
