### ISSUE TITLE
Iscrizione soggetto cancellato per scadenza permesso di soggiorno da altro comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3034]
COMUNE DI PANTIGLIATE
Rif. Ferrari Nadia

Buongiorno
dobbiamo iscrivere nel nostro comune un soggetto cancellato per scadenza permesso di soggiorno da altro comune.
Che tipo di iscrizione dobbiamo prevedere ?

Si resta in attesa di gentile riscontro.

Saluti

**Comment by ncapozzi** [comment]
Buongiorno,
se la scheda cancellata è presente in ANPR dovete effettuare una iscrizione per altri motivi indicando nelle generalità anchel'idsoggettoANPR della scheda cancellata.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
