### ISSUE TITLE
CODICE FISCALE COLLEGATO ERRATO

### ISSUE THREAD

**Issue by COMUNESANGIOVANNIVALDARNO** [italia/anpr#3035]
Ambiente produzione. ID ANPR 214422508, iscritto inizialmente con c.f. errato per errore nei dati anagrafici. Effettuato l'annullamento dell'iscrizione e ripetuta la stessa con i dati corretti. Alla fine il c.f. iniziale (errato) risulta collegato al nuovo (corretto). Ma quel codice fiscale non deve risultare collegato, anzi, non dovrebbe proprio esistere, in quanto non ha niente a che fare con il cittadino, ma è bensì frutto di un errore materiale in fase di iscrizione. Come procedere? Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
la risposta è stata trasmessa a anagrafe@comunesgv.it.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
