### ISSUE TITLE
Stato estero di nascita Hong Kong: Anpr e cie

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3036]
Buongiorno,
una cittadina italiana risulta in Anpr nata a Hong Kong - Repubblica popolare cinese con codice fiscale Z210 mentre in Agenzia delle Entrate è nata a Hong Kong (senza stato estero) con codice fiscale Z221. Come abbiamo letto in una precedente issue (#1373 del 2019), per noi sarebbe possibile modificare lo stato estero di nascita in Hong Kong (come per altro vorrebbe la sig.ra per mantenere il codice fiscale Z221).
Tuttavia, poi, non sarebbe possibile emettere la cie perché nel cieonline lo stato estero di nascita HONG KONG non è previsto.

Come è risolvibile la questione? Solo emettendo una carta cartacea? E' sconsigliabile inserire Hong Kong come stato estero?

Vi ringrazio per l'attenzione,
cordiali saluti.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nella issue di riferimento per codice fiscale con Z221, su ANPR dovete indicare NON ATTRIBUIBILE e descrizione Stato HONG Kong.

Per quanto riguarda l'impossibilità di emettere la carta vi suggeriamo di contattare l'assistenza CIE:
