### ISSUE TITLE
cittadinanza iugoslava

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3037]
Buonasera, da un nostro cliente nella mutazione dati di un soggetto con doppia cittadinanza (italiana e iugoslava) ottengo errore 
EC036 - Stato estero cittadinanza 998 inesistente sulla tabella di riferimento
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2021-12-23 16:58:17 , idOperazioneANPR 732016181
anche se utilizzo per lo stato Iugoslavia il codice 998

	<cittadinanza>
		<descrizioneStato>ITALIA</descrizioneStato>
		<codiceStato>100</codiceStato>
	</cittadinanza>
	<cittadinanza>
		<descrizioneStato>IUGOSLAVIA</descrizioneStato>
		<codiceStato>998</codiceStato>
		<noteStato>Stato non attribuibile</noteStato>
	</cittadinanza>
potete indicarmi dove sbaglio? 
Grazie.
Andrea Galli

**Comment by ncapozzi** [comment]
Buongiorno
il cittadino non può avere ad oggi la cittadinanza in uno stato estero che non esiste più. Per questo motivo per la cittadinanza il cod. 998 non è ammesso, si possono utilizzare solo cod. stato presenti nella tabella pubblicata.
