### ISSUE TITLE
[5005] Impossibile eseguire mutazioni nel medesimo indirizzo

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#304]
Corbetta, ambiente di produzione.

Buongiorno, in data odierna abbiamo dovuto eseguire una scissione aggregazione da una famiglia anagrafica ad una convivenza che si era costituita (ID operazione ANPR 1070664) ma il sistema ANPR ha respinto la richiesta con codice errore: EN388 - La residenza inserita risulta uguale a quella attuale.
Questa tipologia di evento dev'essere permessa perché sono numerosi i casi in cui le persone cambiano l'appartenenza ad un nucleo familiare senza variare l'indirizzo di residenza.
Grazie
Luca Bonini

**Comment by gcarbonin** [comment]
Abbiamo introdotto  una modifica lo scorso 5 settembre (vedi issue 281) per consentire questa operazione. occorre  indicare un campo per forzare l'operazione (par 11.3.2 delle specifiche), pag.84).
