### ISSUE TITLE
IMPOSSIBILE ACCEDERE AD ANPR

### ISSUE THREAD

**Issue by anagrafe** [italia/anpr#3041]
Buongiorno.
Per l'ennesima volta non riesco più ad accedere ad ANPR. Ogni 4-5 settimane il sito non funziona più. Devo sentire la vostra assistenza che mi fa una serie di operazioni su Mozilla e tutto riprende a funzionare. Mi hanno spiegato che si tratta di un problema di aggiornamenti di Mozilla e di nuove SCO. Le SCO vecchie, infatti, funzionano sempre su Chrome, mentre quelle nuove hanno continuamente problemi su Mozilla.
Avrei bisogno, quindi, di ripristinare nuovamente il sito e possibilmente di avere un'assistenza che mi risolva il problema una volta per tutte.
Potete contattarmi all'ufficio anagrafe del Comune di Trinità al numero 017266131 interno 2.
Grazie.

**Comment by cmigliardi** [comment]
buonasera
verrà contattato  dal collega  Daniele

**Comment by cmigliardi** [comment]
Il programma bit4id dopo gli aggiornamenti sostituisce il modulo safedive su firefox.
il problema è stato risolto  .

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
