### ISSUE TITLE
figlio non convivente

### ISSUE THREAD

**Issue by LucaFarina** [italia/anpr#3045]
Nella scheda di un papà, il cui figlio ha la residenza prevalente presso la madre separata, non compare il figlio con il relativo legame di parentela, quindi il papà non riesce a chiedere i certificati per il proprio figlio.
Come si risolve?
(i genitori risiedono in comuni diversi ed entrambi diversi da quello di nascita del figlio)

**Comment by cmigliardi** [comment]
buongiorno, il decreto che regolamenta il servizio prevede che i certificati possono essere richiesti o per sé stesso o per un componente del proprio  nucleo famigliare ( in sostanza le persone devono abitare insieme e  allo stesso indirizzo  )

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
