### ISSUE TITLE
Richiesta ambiente test anpr Comune di VITERBO

### ISSUE THREAD

**Issue by lferrelli** [italia/anpr#3046]
Buongiorno,
mi presento sono Luca Ferrelli, tecnico dei servizi demografici della We-com srl, il nostro nuovo cliente è il Comune di Viterbo
che risulta già subentrato in anpr in data 30/11/2020. La nostra necessità è la seguente: per effettuare formazione sull'utilizzo del nostro gestionale all'area dei servizi demografici Vi richiediamo di metterci a disposizione ambiente TEST pulito e l'assistenza necessaria per popolare l'ambiente di test in modo che si possa far comunicare con il nostro db di prova e si possano effettuare operazioni di trasmissione anpr con finalità di formazione al personale dell'ente.
Richiediamo il Vostro supporto per la configurazione.
Potete scriverci alle mail l.ferrelli@we-com.it oppure b.lamboglia@we-com.it
Potete contattarci ai cellulari Luca Ferrelli 3335487889 Bruno Lamboglia 3891515197

Ringrazio anticipatamente.

Cordiali saluti
Luca Ferrelli

**Comment by Leonforte** [comment]
Utente contattato per le vie brevi.
