### ISSUE TITLE
Cambio Anno di matrimonio di cittadina vedova

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3047]
Buongiono,
la cittadina Id ANPR 38141367 di stato civile Vedova, ha come anno di matrimonio 1965 al posto del corretto 1955.
Ho provato a rettificare il dato da webapp ma non riesco in quanto lei già vedova.
Come posso variare il dato?

Grazie
Claudio Vignati

**Comment by frmariani** [comment]
I coniugi condividono le informazioni sul matrimonio, quindi non è possibile modificare dei dati di un cittadino deceduto.
In questo caso deve prima annullare l'operazione di modifica dello stato civile del coniuge superstite ed il decesso del cittadino; successivamente effettua la modifica dell'anno del matrimonio e poi  esegue di nuovo le due operazioni annullate precedentemente.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario,  si prega di riaprirne una nuova facendo riferimento a questa stessa.
