### ISSUE TITLE
ANPR NON DISPONIBILE

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3049]
Buongiorno,
da circa 10 minuti il sistema espone msg di errore "Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi"
Cordiali saluti
Silvia F.
Upi Torino

**Comment by filippo1961** [comment]
IDEM COMUNE DI MARSALA

**Comment by cmigliardi** [comment]
i sistemi sono di nuovo attivi
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
