### ISSUE TITLE
Rigetto parziale di pratica di immigrazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#305]
Insisto su questo argomento, trattato nella #296 che è stata chiusa. E' un caso relativamente frequente per la cui soluzione il ricorso alla web app pare francamente inadeguato.
Nel caso di immigrazione da comune non subentrato di più persone comprese nella stessa pratica, risulta ancora impossibile togliere dal procedimento eventuali soggetti da rigettare, confermando invece gli altri.
Filipazzi - Maggioli

**Comment by luca-teamdigitale** [comment]
Duplicate of #296
