### ISSUE TITLE
Errore durante l'accesso all'ANPR

### ISSUE THREAD

**Issue by julianoromanzini** [italia/anpr#3050]
Buon giorno,
Ho provato a fare il mio primo accesso al portale e appare questo messaggio di errore.
Mi potete aiutare?
Mi chiamo Juliano Romanzini Pedreira e il mio codice fiscale inizia con RMNJLN.
Il mio comune è Piove di sacco, Padova.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

Grazie,
Juliano

![image](https://user-images.githubusercontent.com/97644934/149246796-c1bbf276-46e0-4074-ad17-96799f5351df.png)

**Comment by cmigliardi** [comment]
gentile signore  le consigliamo di rivolgersi al suo comune di competenza xxxxxxxx per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il "codice fiscale validato"   da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
