### ISSUE TITLE
Mutazione tutti dati da WEBAPP - Errore EAM95

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3051]
Buongiorno.
Ambiente di PRODUZIONE comune di ZANE'

Per il soggetto con id ANPR 43470405 si invai da WebApp una mutazione tutti dati per rettificare il cognome del cittadino e quello del padre.
Si vuole inserire il carattere diacritico Ö al posto della traslitterazione "OE".

Si riceve il seguente errore:
Variazione non consentita, soggetto registrato in AT ANPR di altro comune (Codice: EAM95)
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-13 10:56:22 , idOperazioneANPR 749150111 (Codice: EN527)

Si ringrazia anticipatamente
G. Trisolini

**Comment by rvinzani** [comment]
Stiamo verificando con le colleghe di Agenzia Entrate perchè si tratta di un errore restituito dai loro servizi. Le faremo sapere quanto prima

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
Ci sono aggiornamenti in merito alla segnalazione?

Grazie
G. Trisolini

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
Il comune sollecita e chiede se la situazione sia stata sbloccata da Agenzia Entrate.

Grazie
G. Trisolini

**Comment by rvinzani** [comment]
Mi dispiace, non dipende da noi. Ho inviato la segnalazione ai colleghi di Agenzia Entrate e stiamo attendendo una risposta. Ho fatto anche un sollecito

**Comment by rvinzani** [comment]
Salve, abbiamo avuto la risposta. Sembra il problema fosse legato ad un'anomalia sul codice fiscale. Potete riprovare ora l'operazione?

**Comment by rvinzani** [comment]
Chiudiamo la issue. In caso ci fossero problemi legati a questa vi preghiamo di aprire una nuova issue che faccia riferimento a questa stessa

**Comment by CIVILIANEXT001** [comment]
Risolto grazie
