### ISSUE TITLE
GESTIONE CODICE FISCALE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3053]
COMUNE DI CASERTA PROD
Buongiorno
In ANPR è presente un cittadino (AIRE) con codice fiscale non validato (provenienza anagaire) ma lo stesso non è presente in AE.
Come si può allineare?
Grazie

**Comment by ncapozzi** [comment]
Buonasera
non è obbligatorio che il cittadino AIRE abbia un CF presente in AE, per esempio se è nato e vissuto all'estero e non ha alcun rapporto con Agenzia delle Entrate. Il CF attribuito e validato è obbligatorio solo ai fini del rilascio CIE. 
Se comunque per il cittadino in questione è necessario attribuire il CF dovete effettuare una mutazione tutti i dati WS 5008 con tipo = 1 e gestioneCF = 1. Il campo CF nelle generalità da modificare deve essere lasciato vuoto
