### ISSUE TITLE
Richiesta sblocco di una posizione in Anpr

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3055]
Buongiorno,
non è possibile procedere all'aggiornamento dei dati della persona attraverso la webapp ANPR a causa dell'errore allegato sul Comune della Questura che ha  rilasciato il permesso di soggiorno. Il comune  FERRARA (FE) deve essere modificato in FERRARA FE.
Alleghiamo schermata.

In attesa di riscontro,
porgiamo cordiali saluti
l'ufficiale d'anagrafe
Katia Vacchi
![errore questura](https://user-images.githubusercontent.com/57749903/149505920-bb1687ba-0942-44cf-a82d-6f9df068975c.JPG)

**Comment by rvinzani** [comment]
Salve, dalla web app non riuscite, dovreste effettuare l'operazione dal vostro gestionale di mutazione tutti i dati, scegliere come tipo di mutazione permesso di soggiorno, inviando nuovamente tutti i dati corretti compreso il comune della questura
