### ISSUE TITLE
Mancata iscrizione in ANPR

### ISSUE THREAD

**Issue by LaPam83** [italia/anpr#3056]
Non riusciamo ad accedere all anpr perché non rusltiamo iscritti ne io né mio t e mio figlio. Il comune dice di aver comunicato i dati e che il problema sia della società che se ne occupa. Potete aiutarci a capire qual è il problema? Grazie

**Comment by cmigliardi** [comment]
buonasera,  ci potete dare le prime 6 lettere dei vostri codici fiscali? e il comune di residenza? grazie

**Comment by LaPam83** [comment]
Gbrpml
CRCDNl
CRCMNl
Comune di Tuscania prov Viterbo

**Comment by LaPam83** [comment]
Certamente
Gbrpml
CRCDNl
CRCMNl
Comune Tuscania prov Viterbo

Il ven 14 gen 2022, 17:59 cmigliardi ***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
mi scusi ma non trovo nulla  
GBRPML
CRCDNI
CRCMNI
  ma avete i codici di agenzia delle entrate ? potrebbe aggiungere i due numeri dell'anno di nascita?   grazie

**Comment by cmigliardi** [comment]
forse ho rintracciato CRCDNL   residente a tuscania nato nel 1985  ma in ANPR non esiste la scheda

**Comment by cmigliardi** [comment]
in ogni caso se ha già sentito il comune dica di chiamare il numero verde  di assistenza  800863116 e di chiedere ausilio per sanare le schede anagrafiche

**Comment by LaPam83** [comment]
La ringrazio, infatti il problema è questo, l anagrafe co ha risposto che
il problema è della Sogei e che loro non possono fare nulla. Ma a noi
sembra strano. Possibile che loro non possano accelerare i tempi? Ci vuole
così tanto per creare una scheda?

Il ven 14 gen 2022, 20:00 cmigliardi ***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
mi spiace ma è cura del comune gestire le schede anagrafiche dei proprio residenti.  se vuole può dire al referente comunale di chiamare  il numero verde e chiedere assistenza ANPR

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
