### ISSUE TITLE
Il campo ' - Civico' contiene caratteri non validi

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3058]
Buongiorno
vi contattiamo per il seguente problema.
Un Consolato ci segnala l'impossibilità di emettere CIE per cittadino AIRE con indirizzo che contiene caratteri non validi. 
Abbiamo provato tramite webapp di ANPR a modificare l'indirizzo estero, ma ci viene riproposto l'errore in oggetto. Ciò impedisce di poter lavorare qualsiasi "tipo di operazione" che proviamo ad aprire "mutazione dati aire", "mutazione famiglia" , "mutazione residenza", ecc.
Come possiamo procedere? 
Ringraziamo del supporto. 
Formenti Andrea
mail: formentia@comune.caponago.mb.it
Comune di Caponago (Mb)
tell: 02.959698.247/201

**Comment by AndreaFormenti** [comment]
Buongiorno, abbiamo provato e le allego sotto l'errore che ci genera ANPR. Le date non possiamo modificarle in quanto cambieremmo le decorrenze. Di fatto,quello che dobbiamo fare è una correzione del civico all'intera famiglia che contiene caratteri strani e non una mutazione...

<soapenv:Envelope>
<soapenv:Body>
<b:Risposta5001>
<b:rispostaKO>
<testataRisposta>
<idOperazioneComune>20220119105503</idOperazioneComune>
<codMittente>108052</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>5001</operazioneRichiesta>
<dataOraRichiesta>2022-01-19T10:53:00+01:00</dataOraRichiesta>
<protocolloComune>436</protocolloComune>
<dataProtocolloComune>2022-01-14</dataProtocolloComune>
<dataDecorrenza>2012-02-28</dataDecorrenza>
<idOperazioneANPR>755338750</idOperazioneANPR>
<esitoOperazione>XXXX</esitoOperazione>
</testataRisposta>
<listaErrori>
<errore>
<codiceErroreAnomalia>EN237</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN425</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
La residenza del soggetto con ID ANPR 72xxxx02 non puo' essere variata in quanto la data di decorrenza residenza 14-05-2013 risulta precedente a quella di iscrizione APR del soggetto 14-05-2013
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN507</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
La data decorrenza della nuova residenza non puo' essere antecedente alla decorrenza residenza dei soggetti appartenenti alla famiglia
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN447</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-19 10:56:57 , idOperazioneANPR 755338750
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN395</codiceErroreAnomalia>
<tipoErroreAnomalia>W</tipoErroreAnomalia>
<testoErroreAnomalia>
per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza
</testoErroreAnomalia>
</errore>
</listaErrori>
</b:rispostaKO>
</b:Risposta5001>
</soapenv:Body>
</soapenv:Envelope>

**Comment by rvinzani** [comment]
Infatti la mutazione di residenza per rettifica integrazione deve essere fatta dalla data di ultima residenza
