### ISSUE TITLE
[P001] Primi Test

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3059]
Abbiamo cominciato oggi a provare il servizio in oggetto puntando verso l'ambiente TESTCOMUNI.
Qualunque richiesta restituisce lo stesso errore, EN122.
Una delle richieste replica esattamente quella di esempio fornita.
Ci sono casistiche testabili? Se si quali criteri si devono utilizzare?

idOperazioneANPR delle richieste effettuate:
45919265
45919268
45919276
45919280
45919289 <<<

Grazie
Saluti

**Giuliano Caloni**
_Sistemi Informativi S.r.l._
Comune di Milano

**Comment by mttfranci** [comment]
Salve, in settimana è previsto un incontro con le software house per spiegare le modalità con cui sarà possibile effettuare i test.

Saluti

Assistenza ANPR
