### ISSUE TITLE
Rettifica data di decorrenza della residenza

### ISSUE THREAD

**Issue by gcarbonin** [italia/anpr#306]
A partire dal 21 settembre, sarà disponibile una nuova funzionalità che consente la rettifica della data di decorrenza della residenza comunicata al subentro. Tale funzionalità sarà disponibile in una prima fase in modalità WA e successivamente anche in modalità WS. Nel documento allegato, oltre alla descrizione della nuova funzione,  si riportano  i controlli che sono stati inseriti sulle certificazioni (certificato storico di residenza) e sulle mutazioni di residenza.

[rettifica dati subentro_avviso.docx](https://github.com/italia/anpr/files/1320690/rettifica.dati.subentro_avviso.docx)

**Comment by gcarbonin** [comment]
Nella versione che sarà disponibile nel pomeriggio, è compresa anche la variazione del motivo di iscrizione. aggiorno l'allegato con le note operative
[rettifica dati subentro e dati iscrizione_avviso.docx](https://github.com/italia/anpr/files/1324122/rettifica.dati.subentro.e.dati.iscrizione_avviso.docx)

**Comment by gcarbonin** [comment]
#293

**Comment by AnnaUrban** [comment]
Comune di Serravalle Sesia - ambiente di produzione. Dovrei intervenire per rettificare i dati di immigrazione di un soggetto (immigrato dall'estero e non da Comune italiano) ma non ho trovato la funzione di rettifica indicata nelle Vs. istruzioni. E' già operativa in ambiente di produzione?

**Comment by gcarbonin** [comment]
No aspettiamo i ritorni dei vostri test. Possiamo portare in produzione la prossima settimana

**Comment by AnnaUrban** [comment]
Comune di Serravalle Sesia - ambiente di produzione. Ci sono novità riguardo la rettifica dei dati di immigrazione? Ho sempre ferma una pratica che non riesco a definire relativa ad un cittadino che aveva dichiarato di arrivare da Milano e invece arrivava direttamente dall'estero. Quando si pensa di rendere operativa la funzione anche in ambiente di produzione?

**Comment by bfilipazzi** [comment]
Nel documento allegato al primo post si legge: "Una volta effettuata la rettifica di una o entrambe le date, occorre modificare le attuali funzionalità di certificazione per evitare di stampare sul certificato la residenza rettificata."

**Comment by Raffive** [comment]
Ho lo stesso problema del comune di Serravalle.
E un cittadino furibondo perché non posso certificarlo.
Comune di Spinea
Produzione 
Com

**Comment by gcarbonin** [comment]
Gli aggiornamenti cui fa riferimento questo avviso (rettifica date del subentro e del motivo di iscrizione) sono disponibili in ambiente di esercizio (vedi issue 369)
