### ISSUE TITLE
doppia scheda su ANPR

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#3062]
Abbiamo avuto una richiesta di spiegazioni dall'INPS che consulta la banca dati di ANPR riguardo alla presenza di due schede anagrafiche su ANPR: una è la scheda anagrafica della persona cancellata dal nostro comune per trasferimento nel 2019 (ID ANPR: 73360159) in un comune non subentrato e l'altra è la scheda anagrafica attuale dello stesso comune che è poi subentrato in ANPR nel 2020. Come mai non si sono agganciate le due schede anagrafiche su ANPR? Il cittadino ha questo ID ANPR attuale: 90661491.
La storia di ANPR è corretta, ma è possibile agganciare le due schede in modo da averne solo una completa su ANPR per non creare confusione agli enti terzi che consultano la banca dati di ANPR? L'INPS ha chiamato entrambi i comuni per chiedere di agganciare le due posizioni perché il loro gestionale dà errore per questa posizione anagrafica e di conseguenza non riescono a capire il problema.

**Comment by cristinapezzolesi** [comment]
La ringrazio della spiegazione, però mi sembra che la provincia di nascita sia la stessa (PS) e che sia correttamente storcizzata. Non capisco come mai non si siano agganciate.

**Comment by frmariani** [comment]
Le due schede anagrafiche non si sono agganciate perchè in fase di subentro,  la provincia di nascita del cittadino indicata dal comune di Vallefoglia è stata PU; soltanto successivamente al subentro il comune ha modificato il dato.

**Comment by cristinapezzolesi** [comment]
Ok, grazie mille.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
