### ISSUE TITLE
Errore accesso ANPR con SPID ma non c'e problem con i dati nell'AIRE o dati di codice fiscale

### ISSUE THREAD

**Issue by tonylagreca** [italia/anpr#3063]
Salve,
Sono residente nei Stati Uniti. Ho provato due volte ad accedere ad ANPR. La prima volta il mio SPID ha sbagliato nome, "Antonio" invece di "Antonio Salvatore". 
Durante il tentativo di accesso mi è stato chiesto di fornire i dati. Nota che le date sono in formato americano:
![image](https://user-images.githubusercontent.com/98060108/150230192-5733cb0f-e20c-40d3-8f70-59d13c349139.png)
Ho ricevuto l'errore: https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth
Il primo SPID è stato revocato e ho creato un nuovo con "Antonio Salvatore".
Ho verificato tutti i dati nell'AIRE e nell'Agenzia delle Entrate.
Il mio nuovo SPID funziona bene per accedere all'A.I.R.E e all'Agenzia delle Entrate.
Ma ricevo ancora l'errore: https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth.
Grazie per aiutarmi,
Antonio Salvatore La Greca

**Comment by cmigliardi** [comment]
buongiorno, 
gentile signor la greca antonio salvatore  le consigliamo di rivolgersi al suo comune di competenza campobello di licata 
  per far verificare la sua scheda in ANPR (occorre ad esempio che la scheda abbia il "codice fiscale validato" da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
