### ISSUE TITLE
DOPPIA ISCRIZIONE CON COGNOME LEGGERMENTE DIVERSO

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#3065]
Ho iscritto in data 13/11/2021 un cittadino albanese con provenienza dall'estero (ID ANPR 196408616), ma è emerso in un secondo momento che in realtà il cittadino era stato iscritto il 20/01/2014 nel comune di Lecce con il cognome leggermente diverso (una I finale anziché una J), il comune di nascita diverso e ancora risulta iscritto nel comune di Lecce con quelle generalità e un codice fiscale diverso (id ANPR 43046871). Adesso il cittadino vuole unire le due storie e i due codici fiscali per unificare anche i suoi contributi del lavoro. Come è giusto procedere?  Il cittadino deve chiedere la rettifica del cognome al comune di Lecce? Dopodiché io dovrò annullare la mia iscrizione con provenienza dall'estero e dovrò effettuare una mutazione del cittadino con provenienza da Lecce con decorrenza 13/11/2021? E' possibile salvare la decorrenza della mia iscrizione dal 13/11/2021 anche se la variazione delle generalità sarà effettuata da Lecce dopo quella data? Oppure devo annullare la mia iscrizione dall'estero e prendere le vecchie generalità da Lecce e quindi fare una mutazione di residenza su ANPR con decorrenza 13/11/2021 e poi dovrò rettificare il cognome e il luogo di nascita successivamente? Nel frattempo la sua compagna ha chiesto la residenza nella famiglia del signore in questione con provenienza da altro comune con decorrenza dal 06/12/2021: non ho inserito la pratica della sua convivente per non complicare il tutto, ma quando la inserirò (dopo aver risolto il problema delle generalità) potrò salvarla con decorrenza dal 06/12/2021? Vi chiedo aiuto, perché è abbastanza complicato

**Comment by frmariani** [comment]
Innanzitutto grazie per la chiarezza del caso.
Direi di procedere in questo modo:
per prima cosa Lei deve annullare l'iscrizione del cittadino in modo che il codice fiscale venga "svalidato" e "smarcato";
a questo punto deve decidere se
1) immigrare il cittadino con le vecchie generalità e poi procedere con il collegamento dei due codici fiscali 
2) aspettare che il collegamento lo effettui il comune di Lecce; 
Le consiglierei di procedere in autonomia con il punto 1 facendo bene attenzione all'inserimento delle date di decorrenza; 
nulla osta al successivo trasferimento della compagna con data 6/12/2021 

Spero di essere stata chiara quanto Lei.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
