### ISSUE TITLE
Mutazione famiglia APR - Rettifica indirizzo - Errore

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3067]
Buongiorno,
con decorrenza 12.01.2022 abbiamo effettuato una Mutazione di residenza APR e mi sono accorto oggi che il CAP indicato è sbagliato a causa di un problema del nostro software gestionale.
Siccome è già successo, ho proceduto ad effettuare una Mutazione residenza APR -> Rettifica indirizzo ma va in errore.

Quello che ho riscontrato è che come data di decorrenza non mi propone 12.01.2022 (data di iscrizione nel nostro comune) ma 19.03.2007, probabilmente la data di decorrenza di iscrizione nel comune precedente.
Indico gli estremi dell'operazione:
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-20 18:01:11 , idOperazioneANPR 757636456 (Codice: EN527)

Come posso risolvere?

Grazie
Claudio Vignati

**Comment by ncapozzi** [comment]
Buongiorno,
nel vostro caso l'indirizzo si riferisce ad una convivenza (casa di riposo o simile con id 21625528) pertanto l'eventuale rettifica/integrazione indirizzo riguarda tutti i residenti nella struttura e deve essere effettuata con data di decorrenza = a quella di inizio validità della residenza della struttura stessa che risulta 19.03.2007  in ANPR.
Tenete presente che quando effettuate un cambio di residenza per un cittadino che si trasferisce in una struttura l'indirizzo che gli viene associato non è quello che mandate voi ma quello già presente in ANPR per la struttura.

**Comment by cvignati** [comment]
Perfetto, quindi per aggiornare il CAP a tutti i residenti nella convivenza basta che rettifico l'indirizzo di un membro della convivenza?

**Comment by cvignati** [comment]
Perfetto, quindi procedo alla rettifica indirizzo di un membro la convivenza con data decorrenza 19.03.2007 e verrà aggiornata a tutti i membri, corretto?

Grazie
Claudio Vignati

**Comment by cvignati** [comment]
Va ancora in errore nonostante abbia inserito come data decorrenza 19.03.2007

**Comment by ncapozzi** [comment]
Deve procedere con una mutazione 5001 per la convivenza con tipo = 9 rettifica/integrazione indirizzo con data decorrenza 19.03.2007 così verrà aggiornata a tutti i membri

**Comment by cvignati** [comment]
Ho provato direttamente da Webapp. Come operazione ho scelto Mutazione Famiglia / Convivenza poi Rettifica/integrazione indirizzo. Ho scelto un membro della convivenza ed ho indicato come data decorrenza pratica 19.03.2007 ma mi da errore, il seguente:
La data decorrenza della residenza deve essere uguale alla data decorrenza della richiesta (Codice: EN239)

La data di decorrenza residenza non può essere 19.03.2007 in quanto il cittadino è entrato a far parte di quella convivenza il 12.01.2022

**Comment by ncapozzi** [comment]
Nella sezione residenzaFamigliaConvivenza c'è ancora dataDecorrenzaResidenza = 2022-01-12

**Comment by cvignati** [comment]
> Nella sezione residenzaFamigliaConvivenza c'è ancora dataDecorrenzaResidenza = 2022-01-12

Il cittadino è residente in questa convivenza dal 12.01.2022, è corretta questa data come residenza

**Comment by ncapozzi** [comment]
Non deve considerare la residenza del singolo cittadino ma quella della convivenza se c'è da fare la rettifica di un dato errato nell'indirizzo
