### ISSUE TITLE
ALLINEAMENTO CODICI FISCALI

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#3070]
cambio di generalità STESSO SOGGETTO di un cittadino straniero, cambio del nome e cognome, lo stesso all'agenzia delle entrate risulta avere due codici fiscali, uno con i dati esatti e l'altro con i dati errati. Al momento dell'allineamento RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE compare il seguente messaggio di errore: Esito AE: Operazione non consentita: per i dati anagrafici indicati esiste gia' un codice fiscale provvisorio in attesa di risoluzione omocodia (Codice 96), operando sul gestionale invece  compare : 
Operazione ID ANPR = 758167181, ID locale JD2201210936104325 - Persone coinvolte : YAHYA ANYASS MANAFI 31/01/2000, MANAFI YAHYA ANYASS 31/01/2000 - Il servizio ANPR ha risposto con errori - Codice EAM9C - EN527.
contattando la sogei riferisce che in caso di criticità contattare [l'anpr.]
GRAZIE

**Comment by rvinzani** [comment]
Il codice fiscale MNFYYN00A31Z318G che coincide con i dati modificati del soggetto è già presente n Agenzia delle Entrate e per questo codice fiscale è anche stata richiesta l'emissione di un omocodice.
Dovete verificare con il cittadino e con Agenzia Entrate se si tratta della stessa persona o è un terzo soggetto con gli stessi dati anagrafici
