### ISSUE TITLE
"Purtroppo non è stato possibile accedere al servizio"

### ISSUE THREAD

**Issue by Nico89AP** [italia/anpr#3073]
Buongiorno,

Quando provo ad accedere ottengo questo errore.

Le prime 6 cifre del mio codice fiscale sono: GLRNLS

![image](https://user-images.githubusercontent.com/98169023/150544065-38c2b535-0513-44ae-a457-384b1b08ff56.png)

**Comment by cmigliardi** [comment]
gentile signor Anguilar  le consigliamo di rivolgersi al suo comune di competenza Sersale  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il "codice fiscale validato" da agenzia delle entrate, che la scheda non sia cancellata, 
che la scheda non sia duplicata, che esista in ANPR, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
