### ISSUE TITLE
Accreditamento Ente Gestore Servizi Pubblici

### ISSUE THREAD

**Issue by francescoporti** [italia/anpr#3074]
Buonasera, con la presente sono a chiedere quando verrà data la possibilità anche agli Enti gestori di pubblici servizi di essere accreditati. Ho provato, ma nonostante la mia azienda è iscritta presso l'IPA mi dice di "Censire l’ente presso IPA".
Grazie

**Comment by FilippoPapi** [comment]
l'applicazione è ancora in sperimentazione per alcuni enti determinati.
sarò successivamente comunicata l'apertura ad altri enti
