### ISSUE TITLE
Non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by garconti** [italia/anpr#3077]
Buongiorno,

accedendo al portale "Servizi al cittadino" con credenziali SPID mi appare il seguente messaggio:
"Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni."

Le prime lettere del mio codice fiscale sono RCNGPP.
Grazie.
GA

**Comment by landerover** [comment]
ho lo stesso problema e non riesco ad ottenere il certificato di residenza necessario per richiedere il medico di famiglia. Neanche il mio comune di residenza è in grado di ottenerlo. Cosa si può fare?

**Comment by cmigliardi** [comment]
gentile Sig. Arconti le consigliamo di rivolgersi al suo comune di competenza Roma (ultimo censito per la sua scheda)  per far verificare la sua scheda sia  in ANPR (occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, che la scheda non sia duplicata, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.

**Comment by cmigliardi** [comment]
poiché lei ha diversi  codici fiscali  chieda una verifica anche su questo aspetto


 La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
