### ISSUE TITLE
Non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by landerover** [italia/anpr#3078]
Buongiorno sono una cittadina,
sto avendo seri problemi per la richiesta di un certificato di residenza.
Sono residente in Roma dal 27/10/2019. Sono stata di persona per tentare la risoluzione della problematica presso il Municipio XIII in data 20/01/2022. Mi hanno semplicemente detto che c'era un disallineamento del codice fiscale e che hanno fatto tutto ciò che potevano. Ciononostante tutt'ora non riesco ad ottenere il certificato di residenza.
Su alcune banche dati, come ad esempio la motorizzazione risulta la residenza corretta, su altre quali ad esempio l'agenzia delle entrate sembra sia stata spostata il 1/10/2021 presso il vecchio comune di residenza (Comune di Casagiove).

Mi sto seriamente preoccupando della cosa in quanto nè il Municipio XIII ne il Municipio 1 di Roma sono in grado di risolvere il problema e ho necessità di trasferire il medico a Roma e l'ASL dice che non può procedere senza questo benedetto certificato.

Inoltre usufruisco dell'agevolazione mutuo "acquisto prima casa" e temo sanzioni causate da questo disallineamento.

Cosa posso fare?
Le prime lettere del codice fiscale sono VLRNNA

vi prego di contattarmi...

landero88@gmail.com

**Comment by cmigliardi** [comment]
gentile Signora,  
se è residente a Roma , il vecchio comune di Casagiove l'avrebbe dovuta "cancellare"  visto che ne ha perso la competenza.  Non so se Lei ha possibilità di sentire il suo comune di provenienza per segnalare la cosa, se vuole può dire al comune di chiamare il numero verde 800863116 così potrà ricevere l'ausilio per effettuare l'operazione.   mi auguro di esserle stata di ausilio.  cordiali saluti
