### ISSUE TITLE
ANPR errore nell'iscrizione di un irreperibile

### ISSUE THREAD

**Issue by alerinaldi91** [italia/anpr#3079]
Volendo iscrivere un signore cancellato da qualche mese per irreperibilità, il programma mi segnala questo errore

Stato estero di nascita SERBIA incongruente con il cod. catastale Z118 del CF.

Infatti codice fiscale e carta d'identità combaciano con il codice catastale z118, ma in ANPR il soggetto risulta nato in un altro paese.

Come posso fare?
n. ufficio 017350105 int. 1

**Comment by alerinaldi91** [comment]
> Volendo iscrivere un signore cancellato da qualche mese per irreperibilità, il programma mi segnala questo errore
> 
> Stato estero di nascita SERBIA incongruente con il cod. catastale Z118 del CF.
> 
> Infatti codice fiscale e carta d'identità combaciano con il codice catastale z118, ma in ANPR il soggetto risulta nato in un altro paese.
> 
> Come posso fare? n. ufficio 017350105 int. 1

**Comment by alerinaldi91** [comment]
Volendo iscrivere un signore cancellato da qualche mese per irreperibilità, il programma mi segnala questo errore

Stato estero di nascita SERBIA incongruente con il cod. catastale Z118 del CF.

Infatti codice fiscale e carta d'identità combaciano con il codice catastale z118, ma in ANPR il soggetto risulta nato in un altro paese.

Come posso fare?
n. ufficio 017350105 int. 1

**Comment by ncapozzi** [comment]
Buonasera,
è necessario reiscrivere il soggetto con gli stessi dati della scheda cancellata. Una volta iscritto in ANPR potrà effettuare la mutazione dello stato estero di nascita con validazione del CF.
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
