### ISSUE TITLE
Rettifica data di decorrenza della residenza (#306)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#308]
Il comune di Prato è un buon esempio del problema esposto nella issue #306 (chiusa), ha 193.000 abitanti di cui 103.000 mancanti della data di decorrenza dell'indirizzo di abitazione. Ho discusso con il CED del comune del documento allegato alla #306 e riporto alcune considerazioni condivise.
E' necessario che l'emissione del certificato storico di residenza sia bloccata in mancanza della data dell'indirizzo di residenza, nulla da eccepire, anche oggi l'ufficio ricerca nell'archivio storico (cartaceo) la notizia per poterla certificare.
Si chiede invece se sia inevitabile un blocco anche sul cambio di abitazione nell'ambito del comune, visto che questo introduce una difficoltà operativa che influisce negativamente sul procedimento. Infatti l'operatore che riceve la dichiarazione deve richiedere una ricerca storica nell'archivio per eseguire la rettifica propedeutica alla  registrazione del nuovo indirizzo, questa richiesta non ha una risposta immediata; va considerato che le città, Prato fra queste, ricevono le dichiarazioni anagrafiche anche in uffici periferici i cui operatori non hanno accesso ai locali dell'archivio che solitamente si trova presso l'anagrafe centrale. 
Nel corso del 2016 Prato ha gestito 4.231 pratiche di cambio abitazione nel comune, movimentando 7.261 persone, visto il rapporto fra i numeri citati all'inizio si può stimare che oltre 3.800 persone sarebbero coinvolte in un anno dal trattamento di rettifica della data, una dozzina al giorno. 
Filipazzi - Maggioli

**Comment by mccalv** [comment]
Caro @bfilipazzi valutiamo l'impatto di questa segnalazione. La funzionalità é stata al momento autorizzata in ambiente test e presubentro per cercare di sanare posizioni che bloccano il subentro di comuni importanti come Faenza. 
Vi chiedo di eseguire in ogni caso dei test sulla configurazione attuale in modo da raffinarla in seguito. 
Calvaresi
Team Digitale

**Comment by bfilipazzi** [comment]
128 Data prima iscrizione del soggetto o  data decorrenza residenza o data ultimo aggiornamento assente
-------------------------------------------------------------------------------------------------------
Classificato come warning, non è da correggere prima del subentro.

Forse è un errore troppo generico perché comprende tre problemi, a mio modo di vedere la mancanza della data di iscrizione anagrafica è più rilevante della mancanza della decorrenza dell'indirizzo di residenza, ed è comunque un'altra cosa.
Non conosco i controlli interni di ANPR ma da un punto di vista formale la mancanza della prima compromette il certificato di residenza, la mancanza della seconda inficia solo il certificato di residenza storico, e si fa un certificato di residenza storico ogni 50 certificati di residenza. (Rilevo dal db di un cliente di 200.000 abitanti per l'anno 2016 l'emissione di 3.895 certificati di  residenza e di 80 certificati di residenza storici.)

Si può pensare di distinguere i due casi nella gestione degli errori?

**Comment by luca-teamdigitale** [comment]
Duplicate of #306
