### ISSUE TITLE
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#3080]
MADDALONI PRODUZIONE
Il Comune effettua una MUTAZIONE DI RESIDENZA  ID 716062300 tra i movimentati c'è l'individuo con id 87965687 
Poi registrano 3 mutazioni famiglia per variare la composizione scheda:
ID 716077283
ID 747829172
ID 747848460
Nel mentre il comune di rocca di Papa con decorrenza 14/01/2022 effettua una mutazione di residenza ed iscrive nella sua Apr l'individuo con id 87965687 

Ora hanno necessità di annullare il procedimento sulla 716062300 e quindi ripristinare alla famiglia l'indirizzo precedente
Naturalmente prima provano ad annullare le 3 mutazioni famiglia e nel tentativo di annullare la 747848460 ottengono:

L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa; 
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-24 11:43:25 , idOperazioneANPR 762544228;

Non riescono a mettersi in contatto con Rocca di Papa, in quanto vorrebbero chiedere l'annullamento della propria mutazione di residenza, effettuare gli annullamenti e fargli iscrivere nuovamente l'individuo. 

Cos'altro può fare l'Ente?

**Comment by frmariani** [comment]
State procedendo nel modo corretto;
l'alternativa è la cancellazione per altri motivi dei cittadini con data di cancellazione uguale alla data della mutazione di residenza e con motivazione "Ripristino della posizione precedente"; successivamente però dovrete effettuare una nuova iscrizione per tutti i cittadini in questione perchè il rispristino, in questo caso, non è automatico

**Comment by mrabuano** [comment]
Buongiorno,
l'alternativa non può essere intrapresa, in quanto se si andasse a cancellare gli individui coinvolti dal cambio di domicilio 716062300, si riceverebbe l'errore EN343 , in quanto la data di decorrenza della cancellazione per ripristino posizione anagrafica deve essere uguale alla data di iscrizione. 

Come per i casi di procedimento aperto da altro Comune, non è possibile sollecitare da parte vostra il comune di Rocca di Papa?

**Comment by frmariani** [comment]
La data di decorrenza dell'operazione può tranquillamente essere anche la data odierna; la data di cancellazione invece deve essere quella di iscrizione.

**Comment by mrabuano** [comment]
Da un test effettuato, ho riprodotto in ambiente di test lo stesso caso del Comune di Maddaloni 
inserendo nella cancellazione la data della mutazione di residenza e nella decorrenza pratica quella odierna ottengo:

1 Errore Anpr Cod: EN343 - La data di decorrenza della cancellazione per ripristino posizione anagrafica deve essere uguale alla data di iscrizione 12-10-1939 

Facendo un ulteriore test ed inserendo la data proposta nella data decorrenza cancellazione, poi mi scatta un'altra validazione in cui controlla la data del matrimonio che è successiva a quella della data di cancellazione

**Comment by frmariani** [comment]
gentilmente mi indichi in quale ambiente sta operando e l'idoperazione anpr dell'operazione che va in errore

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
