### ISSUE TITLE
Strano Warning su operazione di Rettifica Scioglimento Unione Civile

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#3082]
Ambiente di Pre-Subentro
Codice mittente 069058
operazione Anpr 27157486
idSchedaSoggettoAnpr 165853547

Salve,
inviando l'operazione di Mutazione tutti i dati in Rettifica per la rettifica dei dati di scioglimento di unione civile otteniamo in risposta i seguenti warning:
EN396: I dati non coerenti con il tipo di mutazione richiesto non verranno acquisiti
EN271: Il soggetto XXXXX (165861449) non presenta uno stato civile congruente
L'operazione aggiorna tutti i dati inviati correttamente, ma non riusciamo a capire la natura dei warning ottenuti.

Inoltre ci siamo accorti che inviando il Luogo Evento,  in consultazione lo stesso non viene stranamente restituito.

Distinti Saluti
Antonio Carcea - Dedagroup

**Comment by frmariani** [comment]
l'id operazione ANPR indicata (27157486) si riferisce alla mutazione di Unione Civile (tipo mutazione 18) e non allo scioglimento di unione civile(tipo mutazione 19); avendo indicato i dati dello scioglimento, il sistema avvisa che non verranno acquisiti perchè incoerenti con la tipologia di mutazione.
il secondo warning si riferisce allo stato civile per la stessa ragione: si stanno inviando i dati dell'unione civile ma il cittadino presenta uno stato civile compatibile con lo scioglimento dell'unione civile.
Per quanto riguarda il luogo evento, non risulta mai inviato se non nell'operazione indicata nella issue che però, ripeto, si riferisce ad un tipo di mutazione non compatibile con i dati inviati.

**Comment by acarcea** [comment]
cambiando il tipo mutazione (tipo mutazione 19) come suggerito, tutto funziona correttamente. 
L'unica anomalia che continuiamo a riscontrare riguarda il luogo dell'evento:
Con l'operazione id ANPR 27159084 viene inviato il luogo dell'evento ma, ad una successiva consultazione 3002 - id operazione ANPR 27159085 - tale luogo non viene restituito.

Distinti Saluti
Antonio carcea - Dedagroup

**Comment by frmariani** [comment]
il luogo dell'evento dell'unione civile è presente così come il luogo dell'atto di scioglimento: a cosa si riferisce ?

**Comment by acarcea** [comment]
Mi riferisco al luogo evento (<LuogoEvento/>) all'interno dell'oggetto Scioglimento unione (<ScioglimentoUnione/>) che viene inviato con il 5008 ma non viene restituito con il 3002

XML del 5008:
<scioglimentoUnione>
   <motivoScioglimento></motivoScioglimento>
   <datiEvento>
      <dataEvento>2022-01-01</dataEvento>
      **<luogoEvento>**
        <comune>
           <nomeComune>XXX</nomeComune>
           <codiceIstat>XXXX</codiceIstat>
           <siglaProvinciaIstat>XX</siglaProvinciaIstat>
        </comune>
      **</luogoEvento>**
      <attoEvento>
         ...
      </attoEvento>
   </datiEvento>
</scioglimentoUnione>

Nel 3002 il luogo evento (<LuogoEvento/>) all'interno dello scioglimento unione (<ScioglimentoUnione/>) non viene restituito;
XML 3002:
<scioglimentoUnione>
   <motivoScioglimento>1</motivoScioglimento>
   <datiEvento>
      <dataEvento>2022-01-01+01:00</dataEvento>
      <attoEvento>
         ...
      </attoEvento>
   </datiEvento>
</scioglimentoUnione>

Distinti Saluti
Antonio Carcea - Dedagroup

**Comment by acarcea** [comment]
Mi riferisco all'oggetto Luogo Evento (nell'XML tag <LuogoEvento/> presente nell'oggetto Scioglimento Unione (nell'XML tag <ScioglimentoUnione>) secondo la mappatura xsd della request 5008 di seguito riportata:
UnioneCivile |
                    |--ScioglimentoUnione |
                                                       |--DatiEvento |
                                                                            | --LuogoEvento

Stessa mappatura è presente nella response 3002 dove però il suddetto oggetto non viene restituito.

vedi request 5008 IdOpAnpr = 27159084
vedi response 3002 idopAnpr = 27159085

Distinti Saluti
Antonio Carcea - Dedagroup

**Comment by frmariani** [comment]
il tipoDatiEvento contiene certamente il luogo dell'evento, ma nel caso di scioglimento unione civile il luogo dell'evento non è un dato necessario pertanto può non essere referenziato.

**Comment by acarcea** [comment]
Ringrazio per il supporto e chiudo la issue
