### ISSUE TITLE
Modifica codice famiglia soggetto con WA

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3083]
COMUNE DI PAìNTIGLIATE
Rif. Nadia Ferrari

Buongiorno
ho la necessità di modificare il codice famiglia comune di un soggetto. In tutte le schede è sempre inibito. Come posso modificare con la WA questo dato ?

**Comment by frmariani** [comment]
Servizi di "Registrazione" 
Tipo operazione: Mutazione famiglia/Convivenza; 
cerca un componente della famiglia
Tipo mutazione: Motivo famiglia/Specie convivenza
Oltre ad inserire il nuovo codice famiglia deve anche scegliere,  tra quelli proposti, il motivo costituzione famiglia.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
