### ISSUE TITLE
Notifiche di emigrazione non ricevute in webapp di TEST

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3084]
Buongiorno, ieri ho effettuato delle iscrizioni nel comune di Villa Minozzo di alcune persone precedentemente iscritte nel comune di Pisa, utilizzando in entrambi i casi i servizi di test. 
Nella webapp del comune di Pisa non vedo ancora le notifiche di emigrazione, potete controllare? Vi inserisco un paio di identificativi operazione ANPR delle iscrizioni: 47701810 47701888

Grazie
Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by amollicone1982** [comment]
notifiche ora disponibili
