### ISSUE TITLE
Mutazione tutti dati (generalità) Errore AEEE95

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3085]
Buongiorno.

Comune di NUORO - PRODUZIONE

Per il cittadino con id ANPR  49201922 e CF validato, si invia dal gestione mutazione tutti dati per variare: luogo estero di nascita, giorno e mese di nascita.

Si riceve l'errore:  AEE95 - Operazione non effettuabile 

EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-25 09:47:04 , idOperazioneANPR 763709677 -  -

In attesa di un vostro sollecito riscontro.
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno,
il comune non può effettuare modifiche anagrafiche su un cf risultante da operazione di risoluzione omocodia. Questa attività compete alla Direzione Centrale Archivio Anagrafico di Agenzia Entrate entrate.archivioanagrafico@agenziaentrate.it, cui il comune dovrebbe segnalare la necessità dell’aggiornamento, magari allegando qualche evidenza a supporto della richiesta.

**Comment by CIVILIANEXT001** [comment]
Grazie
