### ISSUE TITLE
Impossibilità di accedere al servizio ANPR

### ISSUE THREAD

**Issue by mariabruninunes** [italia/anpr#3088]
Ciao
Ogni volta che provo ad accedere al servizio ANPR appare lo stesso messaggio di errore.
Non sembrano esserci problemi con la scheda anagrafica di Roma.
Cosa devo fare?

Maria Fernanda Bruni Nunes
Nata à Esteio, Brasile
C. Fiscale: BRNMFR-------
Residente: Francia
AIRE: Roma
![Capture](https://user-images.githubusercontent.com/98481417/151220373-2268b73e-db9a-4124-a6fa-ae4f936857a8.JPG)

Grazie in anticipo.

**Comment by cmigliardi** [comment]
gentile Signora Bruni - le consigliamo di rivolgersi presso il suo comune di competenza per verificare in ANPR la scheda e non localmente. la scheda deve essere presente in ANPR - non cancellata - con codice fiscale validato da Ag Entrate - se lei è un soggetto iscritto AIRE (anche se non dovesse avere obbligo di codice fiscale se usa spid sta utilizzando un codice fiscale, quindi quel codice deve essere presente nella sua scheda in Anpr)  spero di esserle stata di ausilio - cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
