### ISSUE TITLE
Errata valorizzazione Numero Carta di identita' elettronica

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3089]
Buongiorno,
da un controllo ho constatato che 14 miei cittadini ai quali è stata rilasciata la CIE da gennaio a novembre 2018 è stato valorizzato il numero di carta di identità con 8 caratteri e non 9. Nel dettaglio la CIE, nella parte numerica, inizia con 0 e in ANPR non compare.

Elenco tutti e 14 gli ID Anpr per opportuna verifica.
47548379
38136380
38141032
38136084
38141839
38139254
38141190
38141804
38137176
38136628
38136335
38140552
47560708
47534558

Per sanare l'errore devo procedere con una rettifica di Mutazione tutti i dati?

Chiedo anche a voi, se possibile, una verifica anche su altri comuni in quanto, immagino, che il dato sia caricato in ANPR direttamente dalla postazione di rilascio carta di identità elettronica.

Claudio Vignati

**Comment by rvinzani** [comment]
Queste carte di identità elettroniche non sono state comunicate dal sistema CIEOnLine ma o sono state comunicate al subentro o son state inserite tramite servizio di iscrizione/mutazione. Per sanarle è necessario effettuare una mutazione tutti i dati
