### ISSUE TITLE
[A002] Iscrizione Aire

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#309]
Nell'ambiente di test di Arezzo, sto cercando di inviare un'iscrizione Aire con comune di residenza Parigi, ma il servizio risponde sempre "EC034 - Codice consolato di residenza 2290103 incongruente con la descrizione". Nel file xml viene inviato 
<consolato>
<codiceConsolato>2290103</codiceConsolato>
<descrizioneConsolato>CONSOLATO GENERALE D'ITALIA</descrizioneConsolato>
</consolato>
e nell'elenco dei consolati al 26 giugno 2017, mi sembra che codice e descrizione corrispondono.
Se necessario posso inviare l'xml di richiesta.
Saluti 
Papini Riccardo
Infor S.r.l.

**Comment by gcarbonin** [comment]
C'è un errore nella tabella pubblicata : anziché apice c'è un doppio apice. Sistemiamo e avvertiamo quando riporovare.

**Comment by gcarbonin** [comment]
Da ulteriori verifiche nel campo descrizione consolato occorre indicare come avviene nell'attuale aire centrale la SEDE  e non quanto riportato nella colonna RANGO. occorre quindi trasmettere il dato con 2290103 PARIGI. Pubblichiamo oggi la documentazione aggiornata

**Comment by gcarbonin** [comment]
la documentazione è stata aggiornata in data 22 settembre (vedi questo documento https://www.anpr.interno.it/portale/documents/20182/26001/aggiornamenti_28_09_2017.xlsx/f07cd32d-2e95-4eed-9efa-14fba46e1a44)
