### ISSUE TITLE
Impossibilità ad eliminare i dati della convivenza di fatto

### ISSUE THREAD

**Issue by AnagrafeSavona** [italia/anpr#3091]
Comune di Savona
Soggetto id anpr 59269228
Con la funzione eliminazione dati si è tentato di eliminare i dati della convivenza di fatto caricati Erroneamente durante il il subentro
viene evidenziato il seguente errore
![image](https://user-images.githubusercontent.com/51442684/151514634-82155a69-5927-44fa-ae34-2ca8290bc32f.png)

Francesca Benazzo 
019/8310-254  -  019/8310-286

**Comment by frmariani** [comment]
Come suggerito dal diagnostico di errore, ci sono operazioni effettuate dopo il subentro, pertanto la revoca non è possibile se prima non si procede con l'annullamento delle seguenti operazioni nell'ordine indicato:
inserimento dei dati di cessazione matrimonio;
cancellazione per altri motivi del coniuge;
decesso della convivente di fatto.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
