### ISSUE TITLE
EN527 L'OPERAZIONE CHE SI CERCA DI ANNULLARE E' RELATIVA A SOGGETTI NON DI COMPETENZA DEL COMUNE

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3092]
COMUNE DI CINISELLO BALSAMO PRODUZIONE

Buongiorno, 

Cercando di annullare una mutazione famiglia/convivenza tramite il servizio 5012 restituisce il seguente errore: 

EN527 L'OPERAZIONE CHE SI CERCA DI ANNULLARE E' RELATIVA A SOGGETTI NON DI COMPETENZA DEL COMUNE
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-01-28 10:07:17 , idOperazioneANPR 768155285

Il cittadino presente nella famiglia dove è stata attivata la coabitazione id scheda soggetto ANPR: 59880873 tramite consultazione 3002 è residente nel comune mittente

In attesa di un riscontro, 

Comune di CINISELLO BALSAMO.

**Comment by dgiaccari** [comment]
la famiglia con id ANPR:35632279 del soggetto con id ANPR:59880873 è stata ripristinata correttamente nel comune di Cinisello Balsamo 
cordiali saluti

**Comment by jonnyfx95** [comment]
Confermo che la pratica è partita.

Grazie
