### ISSUE TITLE
ambiente TEST "certificate not trusted (from client)"

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3093]
Buongiorno, provando il collegamento utilizzando il certificato 041010-CO-9999, restituisce l'errore in oggetto.
```
<idOperazioneComune>20220128113744151</idOperazioneComune>
<codMittente>041010</codMittente>
```

il certificato è stato scaricato oggi dall'area dp.anpr ...

come posso risolvere?

Grazie mille

**Comment by Leonforte** [comment]
Buongiorno, il certificato indicato è quello di produzione e non di test. Quello corretto ha come CN 041010-CO-0000,, buon lavoro, saluti

**Comment by Hdemografici** [comment]
Grazie, prendendo quello corretto funziona correttamente
saluti
