### ISSUE TITLE
ambiente test, cittadino "sparito"

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3094]
Buonasera in ambiente TEST per 041069
inserito cittadino idSchedaSoggettoANPR 93099390 con idOperazioneANPR>47717247

ora ricercandolo con idOperazioneANPR 47717312 dice che non è presente

inoltre provando a rifare l'iscrizione con idOperazioneANPR 47717315
segnala che è gia presente idSchedaSoggettoANPR 93099390

non capisco cosa succede.

grazie mille

**Comment by amollicone1982** [comment]
Adesso dovrebbe andare
