### ISSUE TITLE
ENDPOINT - COMUNE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3095]
Buonasera, COMUNE DI CASERTA 061022
In ambiente di test abbiamo inserito l'indirizzo completo di endpoint internet (nostro webservice POST https://www....../ANPR\ci.php
il test presente in strumenti di supporto da errore 2  Errore nell'invio della notifica di test.
Lo stesso errore viene dato anche in assenza dell'indirizzo.   
Grazie

**Comment by rinonasti** [comment]
ovviamente è:
https://www....../ANPR/ci.php

**Comment by gife67** [comment]
Buonasera,
in ambiente di Test Comuni non mi risulta che sia impostato il vostro endpoint per la ricezione delle notifiche, che permette di eseguire il test. 
Per verificare potete entrare nella Web Application di ANPR https://dptest.anpr.interno.it/combas, inserendo le credenziali. Cliccate in altro a destra su **Amministrazione** e poi a sx su **Gestione Dati del Comune** nella sezione **Informazioni aggiuntive**.

![image](https://user-images.githubusercontent.com/26840080/152029560-5070b40c-2360-4941-bd78-4e7c5f7b6d00.png)

Inserite l'endpoint ed assicuratevi che sia indicato internet se esposto su questa rete e SPC se su rete SPC. Assicuratevi che il vostro endpoint sia raggiungibile da chiunque su internet, comunque una volta che lo avete indicato provvederò a fare delle verifiche di raggiungibilità da parte nostra, perchè il più delle volte è questo il problema, perchè di solito occorre che il Comune imposti il firewall per l'accesso. 
Comunque impostate correttamente l'endpoint e poi ditemi a che ora effettuate delle prove in modo che possa verificare gli eventuali problemi che riscontriamo.
Cordiali saluti
Giuseppe

**Comment by rinonasti** [comment]
OK INSERITO - ho lanciato il test ma sempre stesso errore.
Riproverò domattina alle 09.30.
Grazie buona serata

**Comment by gife67** [comment]
Ho verificato il problema. Dobbiamo provvedere a configurare il certificato del Comune per permettere l'esecuzione del test. Provvediamo e vi facciamo sapere quando riprovare.
Buona serata

**Comment by gife67** [comment]
Buongiorno,
cortesemente potete riprovare. Ricordo che il campo **contenuto** delle notifiche è crittografato con la chiave pubblica del certificato 061022-CO-9999. Qualora voleste testare anche il decrypt del contenuto, occorre il kit crittografico che invieremo all'ALP del Comune.
Attendo un vs riscontro sull'esito del Test.
Cordiali saluti

**Comment by rinonasti** [comment]
NO TUTTO COME PRIMA

**Comment by gife67** [comment]
Il problema è diverso. Stiamo indagando e vi facciamo sapere quando riprovare.
Grazie

**Comment by rinonasti** [comment]
Potrei sapere, cortesemente, da quale IP provengono le transazioni?
Grazie

**Comment by gife67** [comment]
da internet con questo IP 217.175.52.159.

**Comment by rinonasti** [comment]
ho trovato traffico proveniente da : 217.175.54.43

**Comment by gife67** [comment]
Buongiorno,
cortesemente potete riprovare.
Grazie

**Comment by rinonasti** [comment]
Fatto ricevuto xml sull endpoint ma 
Notifica di Test inviata all'endpoint:
https://www.itsystems.ce.it/ANPR/ci.php
Esito:
2
Risposta:
Errore nell'invio della notifica di test

**Comment by gife67** [comment]
Dovreste verificare la risposta che ci state inviando, perchè probabilmente non risulta conforme agli XSD del servizio.

**Comment by rinonasti** [comment]
L'endpoint non risponde prende solo in carico il file xml ricevuto per proseguire con la sua elaborazione.

**Comment by gife67** [comment]
Il servizio deve rispondere con un messaggio soap come previsto, altrimenti non abbiamo un riscontro su eventuali esiti che ci fornite, dai quali dobbiamo capire se considerare o meno inoltrata la notifica o eventualmente riprovare ad inviarla. E' quanto previsto nel protocollo di colloquio.

**Comment by rinonasti** [comment]
ok potrei avere un esempio di risposta. Grazie per la fattiva collaborazione

**Comment by gife67** [comment]
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org
/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RispostaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">
      <codiceEsito>1</codiceEsito>
      <esito>Notifica ricevuta con successo</esito>
    </ns2:RispostaN000>
  </soapenv:Body>
</soapenv:Envelope>

Il messaggio del campo **esito** è a libertà vostra, mentre il **codiceEsito** deve rispettare i codic forniti sul servizio.

**Comment by gife67** [comment]
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org
/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RispostaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">
      <codiceEsito>1</codiceEsito>
      <esito>Notifica ricevuta con successo</esito>
    </ns2:RispostaN000>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by gife67** [comment]
scusate ma github me lo trasforma ve lo allego in un file
[rispostaN000.zip](https://github.com/italia/anpr/files/7995137/rispostaN000.zip)
s

**Comment by rinonasti** [comment]
Ricevuto correttamente. Grazie
Appena pronta la risposta rifaremo una prova.
Attendo kit per decript del contenuto (potrei averlo sulla mia mail?)

**Comment by gife67** [comment]
Per il kit lo abbiamo inviato all'ALP del Comune di Caserta che è il responsabile di distribuire lo stesso.

**Comment by rinonasti** [comment]
Mi confermate mail : angela.sc...@comune.caserta.it

**Comment by gife67** [comment]
confermo.

**Comment by rinonasti** [comment]
Buonasera, ho riprovato a rifare test.
Ho ricevuto xml un paio di volte poi non più.

**Comment by gife67** [comment]
Buonasera , cortesemente potete riprovare perchè non vedo invii che hanno ricevuto una risposta corretta nella giornata di oggi. 
Grazie

**Comment by rinonasti** [comment]
Riprovato adesso siamo alla situazione precedente, ovvero abbiamo il file xml ma non ancora predisposto la risposta.
 Appena pronto rifaccio test e riscrivo.

**Comment by rinonasti** [comment]
Cortesemente potrei avere le info su tipo di certificato per https?

**Comment by gife67** [comment]
Vi allego la catena di certificati per firmare il messaggio di notifica, questo è un certificato che potrebbe esservi utile.
Per quanto riguarda l'https non credo che sia necessario, in quanto siete voi ad esporre l'endpoint e non è richiesta una mutual authentication, comunque vi allego il certificato di CA di emissione del certificato del nostro endpoint. Il protocollo che utilizziamo è il TLS 1.2.
[anpr_ws_notifiche_cert_2021.zip](https://github.com/italia/anpr/files/8018167/anpr_ws_notifiche_cert_2021.zip)
[CA.zip](https://github.com/italia/anpr/files/8018294/CA.zip)
.

**Comment by rinonasti** [comment]
Cortesemente può verificare se raggiunge endpoint. Per https mi riferisco a: indicato indirizzo ip e certificato generato da ac locale 

Inviato da iPhone
Rino Nasti
Phone 3355885312

**Comment by rinonasti** [comment]
Buonasera,
configurato endpoint con certificato attendibile.
Può verificare se c'è colloquio?
Grazie

**Comment by gife67** [comment]
Buonasera,
dalle 17:38 abbiamo ricevuto una risposta che vi riporto con un codiceEsito = 3, in cui ci indicate che avete avuto qualche problema. Vi riporto sotto il contenuto della risposta. A parte il codice la comunicazione è OK adesso, perchè siete riusciti ad inviarci una risposta conforme e dovreste averla vista nella TextBox della pagina Web.
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RispostaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">      <codiceEsito>3</codiceEsito>      <esito>Notifica non ricevuta con successo</esito>
    </ns2:RispostaN000>
  </soapenv:Body></soapenv:Envelope>
[

**Comment by gife67** [comment]
Vi allego la response perchè GitHub la altera
[N000_response.zip](https://github.com/italia/anpr/files/8043014/N000_response.zip)
.

**Comment by rinonasti** [comment]
ho riprovato ma non funziona più perche?

**Comment by gife67** [comment]
Stiamo configurando un nodo, che può presentare dei problemi su questo test.
Adesso potete riprovare.

**Comment by gife67** [comment]
Ok, quello allegato all'interno dello zip
[test_N031.zip](https://github.com/italia/anpr/files/8043635/test_N031.zip)
.

**Comment by rinonasti** [comment]
Sembrerebbe tutto OK - confermate?

**Comment by rinonasti** [comment]
potrei avere, cortesemente, l'elenco dei codici esito non li ho trovati in documentazione. Grazie

**Comment by gife67** [comment]
Buongiorno,
oggi non mi risultano test effettuati, quelli di ieri erano OK.
Questi i codiciEsito previsti:
  1 -    OK inoltrata con successo
  5 -    KO XSD contenuto notifica non validato
  6 -    KO Notifica assente
  7 -    KO Servizio Ente

**Comment by rinonasti** [comment]
Buongiorno,
ho effettuato un altro test adesso.
Per mettere il tutto in produzione?

**Comment by gife67** [comment]
Confermo OK, abbiamo ricevuto la risposta con codiceEsito = 1.

**Comment by rinonasti** [comment]
Per mettere il tutto in produzione?

**Comment by gife67** [comment]
Deve dichiarare l'endpoint di produzione nella Web Application ANPR di Produzione... Per decryptare il contenuto delle notifiche di Produzione deve utilizzare il kit crittografico relativo all'ambiente di Produzione che vi potrà fornire l'ALP del Comune, il quale lo potrà prendere dalla Console di sicurezza dell'ambiente di Produzione (061022-CO-9999), il nome è uguale ma il certificato è diverso in quanto emesso dalla CA ANPR di Produzione.

**Comment by rinonasti** [comment]
OK fatto. Effettuato anche test
Quindi da questo momento si riceveranno le notifiche. Rimane ovviamente il fatto che le precedenti (quelle di oggi) vanno richieste con il ws4005/ws3003 come abbiamo fatto fino ad oggi. Il secondo metodo comunque è sempre valido? 
Grazie per la fattiva collaborazione.
Se non è complesso si potrebbero avere quelle di oggi?

**Comment by gife67** [comment]
Si rimane sempre valido.... Lunedì verifico con i colleghi se è possibile rinviarvi le notifiche di oggi....
Provvedo a chiudere questa issue, nel caso di problemi potete riaprirne una nuova collegata a questa.
Cordiali saluti

**Comment by rinonasti** [comment]
Grazie e buona serata.

**Comment by gife67** [comment]
Buongiorno,
abbiamo provveduto a rinviarvi le notifiche di Venerdì e ci risulta che sono state acquisite dal vostro endpoint

**Comment by rinonasti** [comment]
Abbiamo ricevuto le seguenti stamattina 786889904 784911634 787254913 787338565 mentre sabato 785837262

**Comment by rinonasti** [comment]
Domanda : quanto tempo intercorre tra l'operazione di immigrazione da parte del comune MITTENTE alla notifica al comune DESTINATARIO ?
Grazie

**Comment by gife67** [comment]
Il tempo può essere variabile in funzione dell'operatività globale su ANPR, oscilla tra circa 30 minuti a qualche ora.

**Comment by rinonasti** [comment]
Ha riscontrato le notifiche sono queste?

**Comment by gife67** [comment]
confermo
