### ISSUE TITLE
certificato di residenza di terze persone

### ISSUE THREAD

**Issue by rmplei58** [italia/anpr#3096]
Buonasera,
è possibile scaricare i certificati di residenza di terze persone ? cioè non facenti parte della famiglia ?
grazie
Elio Ramponi

**Comment by cmigliardi** [comment]
non è possibile per disposizioni del Garante -  Decreto del 3 novembre 2021 del Ministero

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
