### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio.

### ISSUE THREAD

**Issue by PE919** [italia/anpr#3097]
Buongiorno, non mi è possibile accedere ai servizi in quanto dopo l'accesso con Spid appare come messaggio di errore: "...non è stato possibile individuare in modo univoco la tua scheda anagrafica.."

Il comune è Gaeta (LT) presente in Anpr. Le prime lettere del mio CF sono LSEPNI...

Grazie se qualcuno riesce ad aiutarmi.

**Comment by cmigliardi** [comment]
gentile Eliseo .  le consiglio di rivolgersi al suo comune  - in particolare a quello di provenienza san prisco -  perché in anpr abbiamo 2 schede - quindi gaeta dovrebbe chiedere a sa prisco di cancellare per doppia iscrizione la scheda -

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
