### ISSUE TITLE
Riapertura issue #3096 - certificato di residenza di terze persone

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3098]
Issue [#3096](https://github.com/italia/anpr/issues/3096)

Buongiorno,
sono a sottoporvi il servizio offerto dalla società Servizi Locali Spa a questo [link](https://smartanpr.servizilocalispa.it/portal).

Qualsiasi cittadino presente in ANPR può ottenere un certificato di qualunque cittadino iscritto anch'esso in ANPR conoscendo Cognome, Nome, Data di nascita e Codice Fiscale.

**Comment by cmigliardi** [comment]
non è possibile per disposizioni del Garante - Decreto del 3 novembre 2021 del Ministero

per maggiori informazioni  può rivolgersi  alla Direzione Centrale Servizi Demografici

**Comment by cmigliardi** [comment]
La issue viene chiusa.
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
