### ISSUE TITLE
Upload file subentro APR TEST - "Il formato del file decompresso non è XML valido"

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#31]
Buongiorno,
nel fare l'upload del file APR del Comune di Milano in ambiente di test, dopo aver selezionato il file e scelto "conferma" riceviamo l'errore "Il formato del file decompresso non è XML valido" senza ulteriori dettagli. Il file in questione contiene circa 15.000 persone. Riusciamo invece a caricare un file contenente circa 10.000 senza riscontrare il messaggio in questione.
Grazie
Cordiali saluti
Team SiPo Comune di Milano

**Comment by gcarbonin** [comment]
Il file che contengono errori non vengono salvati e quindi per noi è impossibile ripetere la prova. In ogni caso il tipo di errore segnalato indica che uno o più campi non sono coerenti con il formato previsto nel xsd del subentro o manca qualche campo obbligatorio. E' sufficiente validare il file prima dell'invio con un qualunque tool di mercato.

**Comment by gcarbonin** [comment]
Buongiorno. Abbiamo effettuato la validazione del file; otteniamo questo errore:
Invalid byte 2 of 2-byte UTF-8 sequence.
Analizzando poi i dati abbiamo trovato ad esempio:
<maternita>
<generalita>
<cognome>KRȇEL</cognome>
.....
Sarebbe opportuno non utilizzare github per inviare informazioni delle persone, anche se si tratta di dati di test.
Buona giornata

**Comment by gcarbonin** [comment]
Aggiungo che il file sembra UTF-16.
Riguardo ai caratteri speciali, occorre infine considerare che si accettano soltanto quelli indicati nel c.d. "Decreto Brunetta" (vedi tabella 40 pubblicata nel sito www.anpr.interno.it) nonché trattino, virgola, punto e apice.
