### ISSUE TITLE
[5008] Registrazione Vedovanza

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#310]
Buongiorno,
in ambiente di test del comune di Arezzo, abbiamo registrato una Vedovanza per il soggetto con idSoggettoANPR = 8207501. Il servizio risponde anomalia con codice EN396, registra i dati della vedovanza ma non modifica lo stato civile del soggetto. In definitiva il soggetto ha i dati del vecchio matrimonio, della vedovanza (successiva al matrimonio), ma lo stato civile risulta sempre coniugato.
Ultima cosa il coniuge non è residente in ANPR.
Allego il file xml della richiesta, dove ho tolto il nome e il cognome sia del soggetto che del coniuge.
Saluti
Papini Riccardo
Infor s.r.l.
[6307_Richiesta5008.txt]

**Comment by mccalv** [comment]
Caro Riccardo, grazie della segnalazione!
In attesa della risposta da parte di @gcarbonin e Sogei, ho rimosso i dati della richiesta in quanto contengono dati personali, il tuo caso può essere in ogni caso recuperato con il solo ID operazione. 
Grazie ancora!

**Comment by gcarbonin** [comment]
Lo stato civile non viene modificato automaticamente ma deve essere variato dal comune.
