### ISSUE TITLE
cittadini sparito in ambiente test

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3100]
Buongiorno come per issue #3094 ho aggiunto 2 cittadini per il comune 043054 con idOperazioneANPR 47728595 e 47728601
ma cercandoli non vengono trovati
idOperazioneANPR 47728603 e 47728626.

il problema è dovuto a qualche operazione fatta male che possiamo risolvere da soli?

grazie

**Comment by amollicone1982** [comment]
puo' provare adesso

**Comment by Hdemografici** [comment]
ancora non funziona
idOperazioneANPR 47728952 + 47728963

**Comment by amollicone1982** [comment]
potete riprovare

**Comment by Hdemografici** [comment]
ora tutto ok
grazie
