### ISSUE TITLE
ERRORE : Problema di accesso all'ANPR 

### ISSUE THREAD

**Issue by octme** [italia/anpr#3101]
Le scrivo perché non me è stato possibile accedere ai Servizi al Cittadino nell'ANPR con il mio SPID, il mio codice fiscale inizia con MLLCVG.
Io sono iscritto all'aire nel Comune di Camerota comunque spero  che  voi possiate aiutarmi, 

In allegato c'è il messaggio d'errore che appare nel sistema ANPR quando cerco di accedere. Nell'attesa di una sua gentile risposta,

vi ringrazio anticipatamente e porgo cordiali saluti,

![Errore ANPR](https://user-images.githubusercontent.com/98823207/151978380-521956a0-ea49-46c6-a558-c43d0636374f.jpg)

**Comment by cmigliardi** [comment]
gentile signore le consigliamo di rivolgersi al suo comune di competenza  CAMEROTA  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il "codice fiscale validato da agenzia delle entrate", che la scheda non sia cancellata, 
che la scheda non sia duplicata, che esista in ANPR, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.
