### ISSUE TITLE
[6001] - Errore EN043 - Sono presenti piu' soggetti corrispondenti ai dati anagrafici inseriti  - Matera

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#3102]
Buonasera, vorremmo capire perchè dal WS 6001 riceviamo l'errore **EN043** "Sono presenti piu' soggetti corrispondenti ai dati anagrafici inseriti" . 
Nella REQUEST 6001 tra i dati del "soggettoIntestatario" vengono inseriti "codiceFiscale", "cognome", "nome",  e anche "**idSchedaSoggettoANPR**", pertanto il soggetto dovrebbe essere uno solo.  
La richiesta è delle 16:36 di oggi e **idOperazioneANPR**=772950801

Restiamo in attesa di cortese riscontro.
Grazie

Comune di Matera

**Comment by frmariani** [comment]
nella request del 6001 pervenuto non è presente l'idanpr del soggetto; in precedenza, il codice fiscale è stato duplicato, pertanto il sistema necessita dell'identificativo anpr del cittadino per l'emissione corretta del certificato.

**Comment by Eduardo1977** [comment]
Buongiorno, grazie per il riscontro. Quindi, se nella request pervenuta non c'è l'idANPR del soggetto INTESTATARIO nonostante venga messo in quella generata (img sotto) significa che c'è un errore lato client che taglia l'idANPR. 
Adesso ricontrolliamo le specifiche per la request 6001 ma se già avete qualche indicazione vi ringraziamo anticipatamente.  
![immagine](https://user-images.githubusercontent.com/27421449/152305058-47e11d05-8f9f-4058-b4f6-dce081d65ce6.png)

**Comment by Eduardo1977** [comment]
Una domanda: se ci sono sia il codice fiscale che idSchedaSoggettoANPR , c'è uno che prevale sull'altro? oppure entrambe le informazioni vengono utilizzate? Grazie

**Comment by Eduardo1977** [comment]
Riguardando le specifiche mi sembra che l'idANPR dovrebbe stare dentro al tag "generalita" e non fuori. 
Inoltre, in questo caso toglierei "cognome" e "nome" che sono completamente superflui:
![immagine](https://user-images.githubusercontent.com/27421449/152308901-6359a5cc-35b7-430b-a83d-d548530ba3c1.png)

Così dovrebbe andare meglio? Attendo vostro riscontro sulla domanda precedente (se uno tra cf e idANPR viene ignorato o se vengono utilizati entrambi).
Grazie

**Comment by frmariani** [comment]
dovrebbe esserci sempre un riscontro corretto tra codice fiscale e identificativo ANPR; comunque sono entrambi opzionali, mentre non è corretta l'eliminazione del nome e del cognome.
Credo che sia meglio che utilizziate la documentazione tecnica a vostra disposizione.

**Comment by Eduardo1977** [comment]
Grazie, in effetti riguardando meglio solo per cognome e nome non c'è minOccurs="0" maxOccurs="1". Quindi, vanno sempre specificati

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
