### ISSUE TITLE
[3002] Tag residenza tipo 1 + tipo 10 di altro comune

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3103]
Salve, 
in riferimento a #2557, abbiamo la stessa situazione con soggetto ID 77417284, dove ci tornano un tag indirizzo di tipo 1 corretto ed uno di tipo 10 afferente al precedente comune di residenza.
Dalla W.A. non abbiamo trovato modo di eliminare il dato errato.

grazie
Luciano

**Comment by ncapozzi** [comment]
Buongiorno,
potete riprovare per favore?

**Comment by Hdemografici** [comment]
Buongiorno,
abbiamo verificato e risulta tutto corretto,
grazie.
