### ISSUE TITLE
[3002] "problema" encoding risposta

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3104]
Buongiorno, 
ho notato un'anomalia nella consultazione del cittadino idSchedaSoggettoANPR 42943699 precisamente nel comune di nascita "Ciriè" 
in PRODUZIONE
cercandolo con idOperazioneANPR 729448189 per il comune 041069 la risposta sembra codificata in ANSI
mentre idOperazioneANPR 729431349 per il comune 010016 la risposta sembra in UTF-8

potreste verificare se le due risposte inviate sono effettivamente diverse oppure è un problema di ricezione?

grazie mille

**Comment by mttfranci** [comment]
Salve.
L'encoding in uscita delle due risposte è identico.
Rimaniamo a disposizione.

Saluti

Assistenza ANPR
