### ISSUE TITLE
Rettifica generalità con caratteri minuscoli CF non validato

### ISSUE THREAD

**Issue by siracusaanpr** [italia/anpr#3105]
Siracusa produzione
Abbiamo un cittadino che ha nel cognome dei caratteri minuscoli e il CF che non è marcato ANPR in AE. 
Consultando AE il cognome viene mostrato tutto in maiuscolo.
Tentando di effettuare una risoluzione disallineamenti con CF coincidenti, vedo entrambe le schede con il cognome tutto in maiuscolo, nonostante da una consultazione della scheda individuale in Anpr veda quelli minuscoli.
Per validare il CF dovrei confermare i dati di AE ma il cittadino vuole mantenere i caratteri minuscoli così come presenti nell'atto di nascita. 
Non siamo sicuri se sia possibile validare il CF e poi, nel caso AE restituisca il cognome tutto in maiuscolo, rettificare con una mutazione dati le generalità ottenendo quanto desiderato. 

Resto in attesa di sapere come poter procedere
Grazie

**Comment by cmigliardi** [comment]
Buongiorno, 
Anpr è nata anche per  recepire  proprio i casi di cognomi con le lettere in minuscolo . es le particelle nobiliari de Curtis. 
La norma prevede che in sede di allineamento venga sempre preso il dato in ANPR.  
AE  scrive in maiuscolo semplicemente perché emette i codici fiscali che  sono in maiuscolo.

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
