### ISSUE TITLE
Errore invocazione servizio P002

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3106]
Invocando il servizio P002 per avere il dettaglio di una richiesta pratica cambio di residenza ho l’errore generico “Internal Error”
 
La richiesta è la seguente ma sottolineo che l’invocazione dell’altro servizio P001 che fornisce l’elenco delle richieste funziona bene e che i due tipi di richiesta sono eseguiti nell'ambito della stessa configurazione.
L’end point usato è "https://wspre.anpr.interno.it/anpr-wsP000/AnprServiceP000"
 
<?xml version="1.0" encoding="utf-16"?>
<RichiestaP002 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <testataRichiesta>
    <idOperazioneComune>123251</idOperazioneComune>
    <codMittente>037001</codMittente>
    <codDestinatario>ANPR02</codDestinatario>
    <operazioneRichiesta>P002</operazioneRichiesta>
    <dataOraRichiesta>2022-02-02T12:05:06.2599808+01:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>TEST</tipoInvio>
    <nomeApplicativo>WDAnagrafe</nomeApplicativo>
    <versioneApplicativo>5.01</versioneApplicativo>
    <fornitoreApplicativo>Datagraph S.r.l.</fornitoreApplicativo>
  </testataRichiesta>
  <criteriRicerca>
    <codiceRichiesta>1230094</codiceRichiesta>
  </criteriRicerca>
</RichiestaP002>

**Comment by ATropeano** [comment]
Novità in merito alla suddetta segnalazione? In realtà EndPoint che sto invocando è https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000

**Comment by AMonopoliADS** [comment]
buongiorno.

mi associo alla richiesta di riscontro già fatta anche dal collega Tropeano.
ho già segnalato anche io la stessa anomalia e non siamo gli unici ad avere avviato lo sviluppo dell'integrazione con questi nuovi servizi.
se vogliamo rendere operativi gli enti (in primis gli sperimentatori) nell'uso dei web-service mi sembra abbastanza importante che i riscontri siano un po' più solleciti. 
quanto meno sapere che tempi prevedete per risolvere il problema in modo da potere organizzare nel migliore dei modi l'attività di sviluppo.

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno, in effetti c'era un problema di configurazione sul servizio di dettaglio (P002), dovremmo aver individuato il problema, potreste riprovare? 
Grazie in anticipo.

Assistenza ANPR

**Comment by ATropeano** [comment]
Buonasera. Ho riprovato e l'invocazione del servizio P002 ritorna ancora lo stesso errore, laddove il P001 continua a funzionare.

**Comment by mttfranci** [comment]
@ATropeano avete provato con un nuovo idoperazionecomune? Prima c'era un errore generalizzato sul servizio P002, mentre dalle 11.45 circa vediamo diverse invocazioni che hanno avuto esito positivo da più di un utente.
Potete farci avere in caso i dati identificativi dell'operazione che è andata in errore? (comune e idoperazione comune)
Grazie in anticipo.

**Comment by ATropeano** [comment]
Ho appena riprovato con questa richiesta con un nuovo idOperazioneComune, ma ho lo stesso errore.
```xml
<?xml version="1.0" encoding="utf-16"?>
<RichiestaP002 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <testataRichiesta>
    <idOperazioneComune>123257</idOperazioneComune>
    <codMittente>037001</codMittente>
    <codDestinatario>ANPR02</codDestinatario>
    <operazioneRichiesta>P002</operazioneRichiesta>
    <dataOraRichiesta>2022-02-08T11:36:42.1750017+01:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>TEST</tipoInvio>
    <nomeApplicativo>WDAnagrafe</nomeApplicativo>
    <versioneApplicativo>5.01</versioneApplicativo>
    <fornitoreApplicativo>Datagraph S.r.l.</fornitoreApplicativo>
  </testataRichiesta>
  <criteriRicerca>
    <codiceRichiesta>1230094</codiceRichiesta>
  </criteriRicerca>
</RichiestaP002>

**Comment by mttfranci** [comment]
@ATropeano siete sicuri che questa volta l'errore non sia sul vostro client?
Noi vediamo transitare correttamente la risposta, eccone un estratto : 

```
			<ns2:RispostaOKP002>
				<testataRisposta>
					<idOperazioneComune>123257</idOperazioneComune>
					<codMittente>037001</codMittente>
					<codDestinatario>ANPR02</codDestinatario>
					<operazioneRichiesta>P002</operazioneRichiesta>
					<dataOraRichiesta>2022-02-08T11:36:42.1750017+01:00
					</dataOraRichiesta>
					<idOperazioneANPR>48715145</idOperazioneANPR>
					<esitoOperazione>0000</esitoOperazione>
				</testataRisposta>
				<criteriRicerca>
					<codiceRichiesta>1230094</codiceRichiesta>
				</criteriRicerca>
```

In precedenza in effetti c'era un errore sull'operazione P002, ma ora anche software house ci confermano che ottengono correttamente la risposta (es. issue #2953)

Saluti

**Comment by ATropeano** [comment]
Ho cambiato lo stato della pratica con 1230094 ponendola a 11 - Irrecivibile, quindi ho fatto una nuova pratica di residenza per lo stesso cittadino e ora lo scarico funziona bene con il servizio P002, senza che abbia modificato il mio codice di programma. Forse nella mia prima pratica c'era qualcosa che non andava...

**Comment by mttfranci** [comment]
Va bene.
Grazie del riscontro.
Buona serata
