### ISSUE TITLE
Convivenze di fatto - cessazione per termine coabitazione

### ISSUE THREAD

**Issue by CESARERAMADORI** [italia/anpr#3110]
Ho un problema a cessare la convivenza di fatto di cittadino per emigrazione della convivente di fatto in altro comune.
L'operazione che interessa è la n.° 775351646. Ricevo errore e richieste di indicare il motivo di cessazione del contratto di convivenza che però non è mai stato depositato in anagrafe e, per quel che ne so, non esiste.
Ho indicato come motivazione della cessazione, visto che me lo indicava come dato obbligatorio, la cessazione unilaterale come elemento che almeno analogicamente mi risultava più pertinente essendo l'emigrazione avvenuta per dichiarazione di residenza.
Mi rimangono dubbi sul tutto.
Cordiali saluti
Cesare Ramadori

**Comment by frmariani** [comment]
consultando il cittadino ho notato che ha inserito sia la convivenza che la risoluzione il 3/02/2022 e la cittadina si è spostata il 27/01/2022: come mai ha avuto la necessità di inserire i dati dopo l'emigrazione della cittadina ? i dati richiesti dal sistema ANPR sono obbligatori perchè sanciti dalla legge sulle convivenze: come mai il cittadino non li ha forniti ? l'operazione indicata è andata in errore perchè ha indicato una data di risoluzione inesistente:0001-01-01

**Comment by frmariani** [comment]
La issue viene chiusa; nel caso fosse necessario aprite una nuova issue facendo riferimento a questa
