### ISSUE TITLE
Errore invocazione servizio P001

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#3112]
Buongiorno,
invocando il servizio P001, riceviamo l'errore => Internal Error

di seguito request e response d'esempio:

```xml
<con:RichiestaP001 xmlns:con="http://sogei.it/ANPR/P000sc">
	<testataRichiesta>
		<idOperazioneComune>530720</idOperazioneComune>
		<codMittente>040007</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>P001</operazioneRichiesta>
		<dataOraRichiesta>2022-02-03T16:05:42.6416746</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>TEST</tipoInvio>
		<nomeApplicativo>XXX</nomeApplicativo>
		<versioneApplicativo>1.0</versioneApplicativo>
		<fornitoreApplicativo>XXX</fornitoreApplicativo>
	</testataRichiesta>
	<criteriRicerca>
		<dataIniziale>2022-02-01</dataIniziale>
		<dataFinale>2022-02-03</dataFinale>
		<idTipologia>1</idTipologia>
		<idStatoRichiesta>2</idStatoRichiesta>
	</criteriRicerca>
</con:RichiestaP001>

<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <env:Fault>
      <faultcode>env:Client</faultcode>
      <faultstring>Internal Error</faultstring>
    </env:Fault>
  </env:Body>
</env:Envelope>
```

Cordiali saluti
Laboratorio Dedagroup

**Comment by LSPAG** [comment]
Aggiungo che anche il P002 da lo stesso errore

di seguito request e response d'esempio:

```xml
<con:RichiestaP002 xmlns:con="http://sogei.it/ANPR/P000sc">
	<testataRichiesta>
		<idOperazioneComune>530721</idOperazioneComune>
		<codMittente>040007</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>P002</operazioneRichiesta>
		<dataOraRichiesta>2022-02-03T17:37:15.1361936</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>TEST</tipoInvio>
		<nomeApplicativo>XXX</nomeApplicativo>
		<versioneApplicativo>1.0</versioneApplicativo>
		<fornitoreApplicativo>XXX</fornitoreApplicativo>
	</testataRichiesta>
	<criteriRicerca>
		<codiceRichiesta>1230099</codiceRichiesta>
	</criteriRicerca>
</con:RichiestaP002>

<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <env:Fault>
      <faultcode>env:Client</faultcode>
      <faultstring>Internal Error</faultstring>
    </env:Fault>
  </env:Body>
</env:Envelope>
```

**Comment by apaolacci** [comment]
Non trovando log delle richieste 530720, 530721 in data 03-FEB sul sistema d'ingresso DataPower vi chiediamo di verificare se l'endpoint invocato è quello corretto  _https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000_   (TEST COMUNI) ?

**Comment by LSPAG** [comment]
Buongiorno, confermiamo che l'endpoint invocato è corretto, abbiamo anche validato l'xml request tramite XSD e risulta valido.

**Comment by apaolacci** [comment]
Buongiorno, 
confermate le date d'invocazione 2022-02-03T16:05:42  e  2022-02-03T17:37:15 ed il comune utilizzato codice istat 040007 ? Non troviamo le richieste in ingresso.
E' possibile fare un nuovo test adesso e comunicarci il payload xml di request ?

**Comment by apaolacci** [comment]
Purtroppo non c'è evidenza sul log della request 530924 alla data ora 2022-02-08 17:58:02 
Siete sicuri di raggiungere il nostro server dal vostro client ?

In ambiente di test comuni nella giornata di ieri per il comune 040007 troviamo le seguenti invocazioni:
Feb  8 10:19:14 .../ANPR3000ServiziConsultazione/AnprService3000,IP=52.166...,IPP=,...,IDS=040007,IDE=,CF=LBRNTN77L24...
Feb  8 10:20:16 .../ANPR3000ServiziConsultazione/AnprService3000,IP=52.166...,IPP=,...,IDS=040007,IDE=,CF=LBRNTN77L24...
Feb  8 10:20:38 ../ANPR3000ServiziConsultazione/AnprService3000,IP=52.166...,IPP=,...,IDS=040007,IDE=,CF=LBRNTN77L24F...
Feb  8 10:23:09 .../ANPR3000ServiziConsultazione/AnprService3000,IP=52.166...,IPP=,...,IDS=040007,IDE=,CF=LBRNTN77L24...  

Grazie

**Comment by LSPAG** [comment]
Problema risolto.
Saluti
