### ISSUE TITLE
ANPR Portale: Non posso vedere o scaricare il certificati anagrafico di nascita, di matrimonio o di stato civile, perché?

### ISSUE THREAD

**Issue by thdimatteo** [italia/anpr#3114]
Ciao Buongiorno, 

Non lo so perché non ho l'accesso 5 certificati all'ANPR. E la stessa situazione per la mia figlia. Grazie mille!

Cordiali saluti, 

dimatteo

![Portale](https://user-images.githubusercontent.com/98105653/152530872-a1b957d1-8631-4d48-8cc5-3361c7982951.png)
![figlia](https://user-images.githubusercontent.com/98105653/152530887-cd495348-1f29-4688-8b4b-38b67f5678de.png)
![me](https://user-images.githubusercontent.com/98105653/152530891-4d68700e-7075-4b7a-93d5-44969b899ada.png)

**Comment by cmigliardi** [comment]
gentile Signore per poterle rispondere avrei necessità delle prime 6 lettere del codice fiscale  suo e di sua figlia 
   la ringrazio

**Comment by thdimatteo** [comment]
mio codice fiscale: DMTTHG
il codice fiscale di mia figlia: DMTGRL
Gracizie mille!

**Comment by cmigliardi** [comment]
la ringrazio verifichiamo

**Comment by cmigliardi** [comment]
certificati per gli AIRE 
Se sono entrati in ANPR direttamente come AIRE non hanno un pregresso come residenti per il quale il Comune può emettere il certificato

CERTIFICATI
	) Certificati delle persone iscritte all’AIRE 
•	Iscritti all’AIRE al subentro
•	solo residenza e stato di famiglia;  si può rilasciare comunque nascita se avvenuta in Italia e cittadinanza
•	Iscritti all’AIRE dopo il subentro 
•	Si producono tutti i certificati se l’oggetto della certificazione è antecedente alla data di espatrio; in particolare
•	Nascita
•	Cittadinanza
•	Residenza storico se successiva al subentro
•	Matrimonio/Unione civile  (se  antecedente all’espatrio)
•	Contratto di convivenza (se registrato dal comune prima dell’espatrio

 quindi per la sua storia  - quei tipi non possono essere emessi

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
