### ISSUE TITLE
ANPR Portale: Non posso vedere o scaricare certificati di nascita, di cittadinanza e di stato libero perché?

### ISSUE THREAD

**Issue by ferranteluc6** [italia/anpr#3116]
Buongiorno, non riesco più a visualizzare (quindi a scaricare) i certificati di nascita, cittadinanza e stato libero
fino a 5 giorni fa comparivano e ho scaricato il certificato combinato ma c'era un errore nell'indirizzo di residenza (c'era quella vecchia)
mi sono recata al mio comune, hanno rettificato residenza ma da allora non visualizzo più l'elenco intero ma solo come nell'immagine che vi riporto di seguito

il mio CF è FRRLRZ

<img width="656" alt="problema" src="https://user-images.githubusercontent.com/99169240/152747728-7a2dbfd9-abf4-4c41-bf3c-a1ad826d8adb.png">

**Comment by cmigliardi** [comment]
buongiorno, non so se tratta della persona  che risiede ad Adelfia  ....  avendo  solo 6 lettere del codice fiscale.  
in ogni caso è bene che il comune  controlli ogni sezione della sua scheda in ANPR.   se invece non è lei .... può darmi qualche elemento aggiuntivo?   grazie in anticipo

**Comment by ferranteluc6** [comment]
sì sono io, quindi devo necessariamente recarmi in Comune per risolvere? presso quale ufficio? grazie a Lei

**Comment by cmigliardi** [comment]
ufficio anagrafe - abbiamo controllato ulteriormente e il problema sta nel fatto che sulla sua scheda c'è un procedimento aperto  ( quindi in corso)   numero 164120016  in anpr -  numero del comune :  9620 comune di Adelfia -  in sostanza deve chiedere di far chiudere il procedimento- altrimenti la norma prevede una emissione parziale dei certificati  -

**Comment by ferranteluc6** [comment]
grazie, ora è chiaro

**Comment by cmigliardi** [comment]
di nulla  -  La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
