### ISSUE TITLE
Servizi al cittadino- ANPR- purtroppo non è stato possibile accendere al servizio

### ISSUE THREAD

**Issue by gncurtosi** [italia/anpr#3117]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Il mio comune di iscrizione en Briatico(VV) e sono residente all'estero ([Consolato Generale d'Italia in Buenos Aires-Argentina)
Cosa devo fare? Il comune non sa come aiutarmi.
Le prime lettere 6 di mio codice fiscale sono CRTGRL.

grazie in anticipo

**Comment by cmigliardi** [comment]
gentile Signore  le consigliamo di rivolgersi al suo comune di competenza  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il codice fiscale validato da agenzia delle entrate, che la scheda non sia cancellata, 
che la scheda non sia duplicata, "che esista in ANPR", etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.
