### ISSUE TITLE
Pratica di residenza bloccata da altro Comune interessato per la scissione del nucleo originario

### ISSUE THREAD

**Issue by Cingolani** [italia/anpr#3118]
Buongiorno,
sono Luca Cingolani del Comune di Falconara Marittima (AN).
In data 03/02/2022 abbiamo ricevuto la richiesta di iscrizione presso il nostro Comune con provenienza da Ancona della seguente cittadina di cui si comunicano id ANPR e id ANPR famiglia:

Id ANPR scheda: 107310670 - id ANPR FAMIGLIA: 62286028

L'iscrizione non è andata a buon fine perché risulta ancora aperta presso il Comune di Ancona la pratica N. 161121895. Abbiamo contattato il Comune di Ancona il quale ci ha comunicato che la pratica in questione è una pratica di cambio via del 31/01/2022 relativa al compagno della persona (Id ANPR scheda: 107313852), unico altro componente della famiglia 62286028 da cui si è scisso. Ci hanno comunicato che non appena finiscono gli accertamenti di legge provvederanno a chiudere la pratica.

Vorrei chiedere se sia possibile  in qualche modo sbloccare la pratica in modo da poter iscrivere la cittadina presso il nostro Comune senza dover attendere che sia completata la pratica di Ancona relativa all'altro componente del precedente stato di famiglia (dato che la pratica è del 31 Gennaio potrebbero  volerci fino a 45 giorni).

Eventualmente potete contattarmi, oltre che per mail, anche al seguente recapito telefonico: 0719177631

**Comment by ncapozzi** [comment]
Buonasera
in ANPR al procedimento 161121895 è associata anche al cittadina id 107310670 che voi dovete prendere in carico. Il Comune di Ancona deve togliere la cittadina dal procedimento che riguarda il compagno. Per fare questo devono andare sulla web appa di ANPR, Registrazione, tipo operazione Gestione procedimento + Conferma, Tipo operazione = Elimina soggetto + numero procedimento. 
Per ulteriori richieste di assistenza per questo problema o per altri relativi ad operazioni anagrafiche specifiche che potrebbero richiedere anche un contatto telefonico, si prega di contattare il numero verde 800863116.
