### ISSUE TITLE
CAP errato, problema insolubile?

### ISSUE THREAD

**Issue by GiancarloBongiovanni** [italia/anpr#3119]
Buongiorno,
Il CAP relativo alla mia residenza è **sbagliato in ANPR**.

Ho quindi provveduto a fare richiesta di rettifica dati già due volte, segnalando quale sia il valore corretto per il CAP, ricevendo una prima risposta assurda ("il dato è allineato con quello di ANPR quindi è tutto giusto) e poi questa risposta:

**_Gentile Signore il Cap 00167 corrisponde a via dei Massimi in cui Lei ha la residenza I dati sono quindi corretti Cordiali saluti_**

Questa seconda risposta contiene ben due errori:

1) Non esiste una “Via dei Massimi”, ma solo una “Via Massimi”;
2) il CAP di Via Massimi non è 00167 come sostiene il funzionario del comune ma 00136 (valore che avevo indicato come corretto), come è facile vedere da questa schermata del sito di Poste:

![Massimi_CAP](https://user-images.githubusercontent.com/99187579/152793233-b6532177-eb46-4532-9b93-83f7923ad471.jpg)

La seconda risposta mi ha portato a una considerazione, che forse può essere utile agli sviluppatori e/o manutentori del sistema.

Se il CAP delle vie è ottenuto in ANPR con una query che incrocia i nomi delle vie in ANPR con quelli di Poste per derivare il CAP e se tale query si ferma alla prima occorrenza del nome cercato, allora è chiaro perché a via Massimi (la seconda in ordine alfabetico) è stato associato il CAP di Via Cardinal Massimi (la prima in ordine alfabetico).

Se questo è il caso, allora l’errore di CAP è comune a tutti i residenti nella via, il che significa probabilmente alcune migliaia di persone.

Cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
