### ISSUE TITLE
Migliorare l’interfaccia di ricerca codice di errore integrato con readthedocs

### ISSUE THREAD

**Issue by ruphy** [italia/anpr#312]
Aggiungere alla [documentazione degli codici di errore ANPR]( http://anpr.readthedocs.io/it/latest/tab/tab_elenco_errori_anpr.html) una sistema di ricerca per codice di errore.
Questi codici sono ricercati dalle varie amministrazioni per aiutare a sanitizzare i dati presenti nelle anagrafi locali, prima dell’import in ANPR. È dunque essenziale che la ricerca dell’errore, ed eventualmente di una soluzione proposta, sia facilmente accessibile all’operatore.
I sorgenti della pagina sono disponibili qui: https://github.com/italia/anpr/blob/master/src/tab/tab_elenco_errori_anpr.rst
Non è necessario che la pagina generata abbia lo stesso layout (anzi, sarebbe meglio non lo avesse); l’unico requisito è l’integrazione nel processo di build che ne consenta la pubblicazione su readthedocs.

**Comment by feroda** [comment]
Il primo link nella issue qui sopra non esiste  (http://anpr.readthedocs.io/en/latest/tab/tab_elenco_errori_anpr.html)

**Comment by rasky** [comment]
Fixato, grazie!

**Comment by softekno** [comment]
Abbiamo proposto una soluzione per visionarla il link: https://github.com/TorinoTKN-Team/anpr-error-search è disponibile una demo per il momento ma il dominio è temporaneo e non sappiamo fino a quando durerà.
http://130.162.71.133/
