### ISSUE TITLE
Nome della via corretto, CAP errato - una domanda

### ISSUE THREAD

**Issue by GiancarloBongiovanni** [italia/anpr#3124]
Buongiorno,
scrivo nuovamente qui per avere dal supporto tecnico una risposta chiara (**si/no**) a una domanda molto semplice:

_Può un addetto comunale **che opera dentro il gestionale ANPR** per la correzione di un indirizzo **MODIFICARE SOLO IL CAP** di una via, lasciando inalterato tutto il resto?_

Ora spiego la ragione di questa domanda.

Abito in una via (**Via Massimi, Roma**) che nella mia anagrafica ANPR ha un CAP errato, che è quello di un'altra strada (**Via Cardinal Massimi, Roma**). La situazione corretta sarebbe la seguente:

Via Massimi, Roma **CAP 00136**
Via Cardinal Massimi, Roma **CAP 00167**

Invece nella mia anagrafica ANPR risulta che io abito in **Via Massimi, Roma CAP 00167**, con conseguenze pesanti: la posta istituzionale inviatami (dal Comune, dall'Agenzia entrate, ecc.) mi arriva solo se dall'ufficio postale che la riceve si rendono conto che la devono girare ad un altro ufficio postale. Altrimenti se ne perdono le tracce, come è già successo con una raccomandata del Comune, con la mia tessera sanitaria (TS/CNS, spedita dall'Agenzia delle Entrate) e chissà con cos'altro.

Ho saputo ieri da una conoscente che abita nella mia stessa via il seguente fatto: circa quattro anni fa si è recata all'Anagrafe per registrare la figlia appena nata, e alla richiesta di registrarla come residente in via Massimi CAP 00136 si è sentita rispondere "**_Non esiste una Via Massimi, Roma, con CAP 00136, esiste solo una Via Massimi, Roma, con CAP 00167_**". Ha quindi registrato la figlia alla residenza del compagno, in una via diversa.

Ma da questa riposta è impossibile capire se l'addetto stava operando direttamente dentro il gestionale ANPR oppure in un gestionale ad hoc del Comune di Roma.

Ecco perché faccio la domanda riportata all'inizio:

- se la risposta è si, ossia è possibile nel gestionale ANPR operare la modifica del solo CAP, allora ha un senso insistere col Comune perché operi la correzione;
- ma se la risposta è no, ossia il gestionale ANPR presenta una lista di vie, ciascuna con cablato rigidamente un CAP, allora il problema non può essere risolto dall'addetto comunale ma va scalato e questo spero sia il posto giusto.

Grazie e cordiali saluti

![Via_Massimi_CAP](https://user-images.githubusercontent.com/99187579/153355041-8c6a068b-ff5b-4a6c-8ab9-20fc6fbcac17.jpg)

**Comment by cmigliardi** [comment]
Buongiorno, mi spiace che lei ad oggi non abbia ancora potuto risolvere 
Certo che in Anpr è possibile modificare anche solo il CAP
Anpr nasce proprio per andare incontro ai cittadini e non creare  disagi
cosa posso dirle - dica al comune di chiamare il numero verde sogei 800863116 se ha difficoltà sarei pronti a dare ausilio
il gestionale di ogni comune deve rispettare le regole  dettate dal DPCM
noi come sogei non possiamo operare in alcun modo se non fornendo assistenza.

**Comment by cmigliardi** [comment]
mi scusi se mi permetto ma a quale municipio si rivolge ?

**Comment by GiancarloBongiovanni** [comment]
Non si preoccupi e grazie dell'inetressamento!

Il mio municipio è il XIV, ma io per ora ho fatto solo la richiesta di rettifica direttamente dentro ANPR (pensando fosse la cosa giusta da fare) e la risposta è stata un lapidario:

**_Gentile Signore il Cap 00167 corrisponde a via dei Massimi in cui Lei ha la residenza I dati sono quindi corretti Cordiali saluti_**

Poi ho rifatto la stessa richiesta di rettifica, corredandola della tabella di Poste che ho affisso qui, ma vedo che finora nessun addetto ha ancora preso in carico la segnalazione: probabilmente a questo punto sono considerato un seccatore da scansare...

Il problema di andare di persona allo sportello è che già so che mi troverò di fronte a un "non posso farci nulla" e purtroppo non so come scoprire chi sia una persona o un ufficio (ammesso che ci sia) che potrebbe farsi carico del problema e correggerlo.

Comunque prendo nota del numero verde Sogei e lo passerò al Comune, se riesco a capire a chi comunicarlo.

Grazie ancora e cordiali saluti

**Comment by GiancarloBongiovanni** [comment]
Ho mandato una pec all'indirizzo **_protocollo.municipioroma14@pec.comune.roma.it_** spiegando il problema e sperando di ottenere una qualche risposta. In tal caso la aggiornerò qui.

Cordiali saluti

**Comment by cmigliardi** [comment]
spero possa risolvere presto. altrimenti mi faccia sapere
cordiali saluti

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
ci possiamo sentire? la posso contattare ? le lascio la mia email   cmigliardi@sogei.it

**Comment by cmigliardi** [comment]
conosco la Signora Stillo - è molto preparata - probabilmente con il gestionale non riescono
