### ISSUE TITLE
Variazione non consentita per superamento numero campi variati - Codice EAM93

### ISSUE THREAD

**Issue by Strentini** [italia/anpr#3126]
Buongiorno, mi chiamo Serena e lavoro nel comune di Anzola dell'Emilia.
Ho un problema con un cittadino che ha cambiato generalità (data e luogo di nascita e codice fiscale), l'agenzia delle entrate mi dice di aver unificato i codici fiscali dell'utente ma quando faccio la procedura di unificazione sulla webapp mi restituisce il messaggio in oggetto e le seguenti informazioni da fornire in caso di assistenza: data 2022-01-22, idOperazioneANPR 759437651

Ho provato di nuovo oggi ad inviare la mutazione in anpr e mi esce il messaggio: soggetto non individuato in AT - codice fiscale non variato.
Informazioni sull'operazione data 2022-02-10, idOperazioneANPR 783056787
Come posso risolvere il problema? In che modo posso inviare la mutazione?
Grazie

**Comment by rvinzani** [comment]
Se i due CF sono già collegati deve procedere con una mutazione tutti i dati (non risoluzione disallineamenti) modificando sia il CF che i dati anagrafici (data e luogo di nascita). Attendo un suo riscontro

**Comment by Strentini** [comment]
Problema risolto, grazie
