### ISSUE TITLE
Ambiente di test per richieste di cambio residenza : problemi credenziali

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3128]
Per il soggetto di test FNTGRL91B28M118K del comune di Manerbio non riesco ad inviare la dichiarazione perché giustamente mi chiede di specificare e validare l'indirizzo email; ho impostato allora l'indirizzo email  ma non mi arriva nessuna email per la convalida.
Potete verificare ? 
La stessa procedura ha funzionato invece per l'altro soggetto di test  CNLGDI66D55F139O dell'ambiente di Pietravariano

**Comment by apaolacci** [comment]
Adesso dovrebbe funzionare, potete riprovare?
Grazie

**Comment by busaster** [comment]
Sistemato, grazie
