### ISSUE TITLE
Portale cittadino TEST

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#3129]
Buongiorno,
non riusciamo a validare nel profilo utente l'email inserita, in quanto la mail non arriva, per i seguenti soggetti di test:

CESENA
Codice fiscale                   NRXPLA74R28A509J 

LOCATE DI TRIULZI
Codice fiscale                   RXSNTN70P25F205L

Attendiamo un gentile riscontro

Saluti 
Laboratorio Dedagroup

**Comment by apaolacci** [comment]
Adesso dovrebbe funzionare, potete riprovare?

Grazie,
Saluti

**Comment by LSPAG** [comment]
Funziona grazie.
