### ISSUE TITLE
Errore compilazione Dichiarazione Cambio di Residenza con allegati

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3130]
Buongiorno. Venerdì ho inserito una nuova Dichiarazione di cambio residenza (N. **1240087**) per un nuovo cittadino creato al fine dei TEST dei webservice P000. Dopo avere caricato anche due allegati (non ricordo più se ho cliccato INVIA) la dichiarazione ha assunto lo stato "IN VERIFICA". Dopo di che la dichiarazione è visualizzabile ma non è possibile scaricarne il riepilogo (si ottiene il messaggio "Si è verificato un errore non gestito"). Vi chiedo di fare una verifica. Grazie.

Alessio Tropeano

**Comment by mttfranci** [comment]
Un problema rilevato in ambiente di test-comuni ha impedito di elaborare gli allegati relativi alla pratica 1240087.
Ora dovrebbe essere risolto e ricominciare a funzionare con la scansione antivirus degli allegati ma bisogna inserire una nuova pratica, la 1240087non è più utilizzabile e rimarrà nello stato di "Bozza In Verifica".
Analogamente a quanto avvenuto per la issue #3133
E' possibile riprovare? Grazie.

Saluti,
Assistenza ANPR

**Comment by ATropeano** [comment]
Ho riprovato facendo una nuova pratica (nr. 1240092) con due allegati e questa volta non ci sono stati problemi nel salvataggio e nel successivo scarico dalla web. Invece lato web service non riesco a scaricarla con il servizio P002 ricevendo il solito messaggio di Internal Error nella fase di invocazione. A questo punto credo che dipenda dalla presenza degli allegati. La richiesta inviata è la seguente:

```xml
<?xml version="1.0" encoding="utf-16"?>
<RichiestaP002 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <testataRichiesta>
    <idOperazioneComune>123328</idOperazioneComune>
    <codMittente>037001</codMittente>
    <codDestinatario>ANPR02</codDestinatario>
    <operazioneRichiesta>P002</operazioneRichiesta>
    <dataOraRichiesta>2022-02-14T18:27:02.3291678+01:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>TEST</tipoInvio>
    <nomeApplicativo>WDANAGRAFE</nomeApplicativo>
    <versioneApplicativo>24.0.52.0</versioneApplicativo>
    <fornitoreApplicativo>Datagraph S.r.l.</fornitoreApplicativo>
  </testataRichiesta>
  <criteriRicerca>
    <codiceRichiesta>1240092</codiceRichiesta>
  </criteriRicerca>
</RichiestaP002>
```

**Comment by ATropeano** [comment]
Controllo la mia versione dei wsdl e degli xsd: forse non è completamente aggiornata.

**Comment by spedrini** [comment]
Segnalo anche io lo stesso problema (pratica n.1240095): funziona lo scarico da web app, ma lato web service non riesco a scaricarla con il servizio P002 (l'errore "Internal Error").
Questa pratica è priva di allegati.

**Comment by mttfranci** [comment]
@ATropeano per la vostra richiesta, non ne vediamo nessuna traccia all'orario indicato : 

    <idOperazioneComune>123328</idOperazioneComune>
    <codMittente>037001</codMittente>
    <codDestinatario>ANPR02</codDestinatario>
    <operazioneRichiesta>P002</operazioneRichiesta>
    <dataOraRichiesta>2022-02-14T18:27:02.3291678+01:00</dataOraRichiesta>

**Comment by mttfranci** [comment]
@spedrini potreste fornirci anche voi l'xml della richiesta per effettuare delle verifiche?

**Comment by spedrini** [comment]
Ecco la nostra richiesta:
`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>JD220215145611339</idOperazioneComune>
        <codMittente>061059</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>P002</operazioneRichiesta>
        <dataOraRichiesta>2022-02-15T14:56:01.000+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>TEST</tipoInvio>
        <nomeApplicativo>JDEMOS</nomeApplicativo>
        <versioneApplicativo>1.2.53.0</versioneApplicativo>
        <fornitoreApplicativo>MAGGIOLI S.P.A.</fornitoreApplicativo>
    </testataRichiesta>
    <criteriRicerca>
        <codiceRichiesta>1240095</codiceRichiesta>
    </criteriRicerca>
</ns2:RichiestaP002>
`

**Comment by spedrini** [comment]
Ecco la nostra richiesta:

```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>JD220215145611339</idOperazioneComune>
        <codMittente>061059</codMittente>
        <codDestinatario>ANPR02</codDestinatario>
        <operazioneRichiesta>P002</operazioneRichiesta>
        <dataOraRichiesta>2022-02-15T14:56:01.000+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>TEST</tipoInvio>
        <nomeApplicativo>JDEMOS</nomeApplicativo>
        <versioneApplicativo>1.2.53.0</versioneApplicativo>
        <fornitoreApplicativo>MAGGIOLI S.P.A.</fornitoreApplicativo>
    </testataRichiesta>
    <criteriRicerca>
        <codiceRichiesta>1240095</codiceRichiesta>
    </criteriRicerca>
</ns2:RichiestaP002>

**Comment by mttfranci** [comment]
Abbiamo apportato alcune modifiche, Potreste provare di nuovo?

**Comment by spedrini** [comment]
Salve, ho la richiesta di cambio residenza n.1240786 che si trova nello stato ACCOLTA CON RISERVA (12); invoco il servizio P003 per modificare lo stato e portarlo a SOSPESA IN VERIFICA (10), ma la chiamata mi restituisce il messaggio "Il passaggio di stato richiesto non e' consentito."
Guardando la tabella degli stati richiesta vedo che lo stato 10 ha una nota "Ad uso interno ANPR".
Chiedo: è uno stato che possiamo utilizzare?

**Comment by apaolacci** [comment]
Buonasera,
SOSPESA IN VERIFICA (10) non è uno stato che potete utilizzare ma è uno stato interno in cui può transitare temporanemente la pratica, non può essere impostato dall'operatore d'anagrafe e quindi dal software gestionale. Riporto diagramma stati che può chiarire... presente nella issues #3043 che introduceva il rilascio ws P000

https://github.com/italia/anpr/files/8090740/flusso_stati_pratica_cittadino.pdf
