### ISSUE TITLE
Struttura Dati RispostaP002

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3132]
Chiedo conferma, nel contesto di uso dei Web Service, del fatto che,  a partire dalla RispostaP002, non sia possibile ottenere le seguenti categorie di informazioni in un formato strutturato (appositi Tag) ma esse debbano essere estrapolate dall'allegato PDF di riepilogo dichiarazione di residenza, con tutte le incertezze del caso in particolare per l'indirizzo:

relazione di parentela
titolarità di patente
possesso di autoveicoli 
dati indirizzo
titolo occupazione immobile

Alessio Tropeano
Datagraph srl

**Comment by apaolacci** [comment]
Ciao Alessio,
se abbiamo compreso bene la tua domanda SI è possibile ottenere le informazioni richieste in un formato strutturato dalla risposta del P002.
Nel tracciato XML di risposta del P002 puoi trovare le informazioni richieste con appositi tag, ti riporto un esempio con associato l'elemento xml e la decodifica:

```
<componentiCoinvolti>
	 <componente>
		<idSchedaSoggettoANPR>257461</idSchedaSoggettoANPR>
		<idGradoParentela>23</idGradoParentela>
		<flagPatente>SI</flagPatente>
		<flagVeicoli>NO</flagVeicoli>
		<statoAccettazione>3</statoAccettazione>
	 </componente>
	 <componente>
		<idSchedaSoggettoANPR>257462</idSchedaSoggettoANPR>
		<idGradoParentela>23</idGradoParentela>
		<flagPatente>SI</flagPatente>
		<flagVeicoli>SI</flagVeicoli>
		<statoAccettazione>3</statoAccettazione>
		<dataAccettazione>2022-02-11T17:10:54.000+01:00</dataAccettazione>
	 </componente>
</componentiCoinvolti>
```

relazione di parentela    <idGradoParentela>  --> 23 --> Convivente (con vincoli di adozione o affettivi)
titolarità di patente        <flagPatente> --> SI
possesso di autoveicoli  <flagVeicoli>  --> NO


```
<indirizzo>
 <cap>00123</cap>
 <comune>
	<nomeComune>CESENA</nomeComune>
	<codiceIstat>040007</codiceIstat>
	<siglaProvinciaIstat>FC</siglaProvinciaIstat>
 </comune>
 <toponimo>
	<codSpecie>125</codSpecie>
	<denominazioneToponimo>MAZZINI</denominazioneToponimo>
 </toponimo>
 <numeroCivico>
	<numero>100</numero>
 </numeroCivico>
</indirizzo>
```
dati indirizzo:  PIAZZA MAZZINI 100, cap: 00123, comune CESENA (FC)


```
 <datiImmobile>
           <idTipoOccupazione>1</idTipoOccupazione>
 </datiImmobile>
```

titolo occupazione immobile: <idTipoOccupazione> --> 1 --> PROPRIETARIO (_"Di essere proprietario dell'abitazione contraddistinta dai seguenti estremi catastali..."_)

Saluti.
Assistenza ANPR

**Comment by ATropeano** [comment]
Grazie. Controllo la mia versione dei wsdl e degli xsd: forse non è completamente aggiornata.

**Comment by ATropeano** [comment]
Dopo aver aggiornamento i miei xsd/wsdl vedo tutte le informazioni che mi aspetto. Grazie.
