### ISSUE TITLE
Dichiarazione cambio residenza ANPR (test)

### ISSUE THREAD

**Issue by spedrini** [italia/anpr#3133]
Per il soggetto di test FNTGRL91B28M118K del comune di Manerbio ho inserito una dichiarazione di cambio di residenza verso il comune di Pietravairano. Accedendo alla webapp del comune di Pietravairano però non vedo la dichiarazione alla sezione "Dichiarazioni di cambio residenza trasmesse dai cittadini".
Il numero della dichiarazione è 1230122.
Potete verificare?
Grazie

Serena Pedrini
Maggioli SPA

**Comment by apaolacci** [comment]
Un problema rilevato in ambiente di test-comuni ha impedito di elaborare gli allegati relativi alla pratica 1230122.
Ora dovrebbe essere risolto e ricominciare a funzionare con la scansione antivirus degli allegati ma bisogna inserire una nuova pratica, la 1230122 non è più utilizzabile e rimarrà nello stato di "Bozza In Verifica".
E' possibile riprovare? Grazie.

Saluti,
Assistenza ANPR

**Comment by spedrini** [comment]
Ho inserito una nuova dichiarazione (numero 1240093) e ora la vedo correttamente.
Grazie
