### ISSUE TITLE
[ws P000] richieste e chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3134]
alla luce dei test eseguiti sui servizi P001 / P002 / P003, elenco alcuni dubbi / richieste:

1 
servizio P002 - dettaglio richiesta
nella response del servizio, all'interno del tag "datiDichiarazioneResidenza/indirizzo/toponimo" sono presenti solo i tag "codSpecie" e "denominazioneToponimo".
Considerato che è previsto dagli schemi, farebbe comodo avere anche il campo descrittivo "Specie". 

2
servizio P003 - aggiornamento stato
dalle prove fatte, sembra ci siano alcuni stati che richiedono l'indicazione delle note obbligatoriamente (ad esempio il passaggio in stato "Sospesa")
in assenza delle note il web-service va in errore 
```
      <errore>
        <codiceErroreAnomalia>EN148</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Errore nell'impostazione dello stato/proroga pratica. Esito: 12004</testoErroreAnomalia>
      </errore>
```
questa, di fatto, è solo un'intuizione perchè il messaggio di errore non è particolarmente parlante.
se quanto detto risulta corretto, si chiede di sapere la lista dei codici di idStato che richiedono le note come informazione obbligatoria, e - possibilmente - sarebbe utile anche che il messaggio fosse più specifico.

3
abbiamo tentato di analizzare l'uso degli stati della richiesta per confronto con quanto previsto dalla web-app (e/o dal manuale utente), e a tal riguardo sono emersi questi dubbi:
3.1 la pratica "sospesa" assume lo stato "integrata" quando il cittadino fornisce la documentazione richiesta
l'operatore comunale come viene a conoscenza del passaggio di stato da "sospesa" ad "integrata"? è prevista (o sarà prevista) una notifica? oppure è possibile venire a conoscenza del cambio di stato solo richiedendo l'elenco delle pratiche integrate?
3.2 da web-app l'opzione "irricevibile" permette la scelta del motivo di irricevibilità
da web-service, invece, la modifica di stato in "irricevibile" sembra non richieda neanche l'indicazione delle note. è corretto così?

grazie.
Alessandro Monopoli ADS

**Comment by apaolacci** [comment]
Buongiorno Alessandro,
cerchiamo di rispondere alle tue domande:
1. Al momento nei webservice anpr si è sempre utilizzato l'approccio di restituire l' id del dato e non la sua decodifica. La decodifica si ottiene interrogando il webservice 7001 operation scarica_tabelle  e sono disponibili sul portale pubblico https://www.anagrafenazionale.interno.it/il-progetto/strumenti-di-lavoro/tabelle-decodifica/ 
Inoltre durante la fase di sperimentazione, è emersa l'esigenza del cittadino di poter indicare un valore di specie non compreso nella lista fornita da ISTAT, per cui sarà utilizzato proprio il campo descrittivo "Specie" per contenere il valore indicato come testo libero dal cittadino e il codSpecie valorizzato con la specie selezionata 998 (ALTRO).

2. Cercheremo di rendere il messaggio restituito più specifico in grado di far comprendere la mancanza delle note che sono obbligatorie per alcuni cambi di stato. Nel frattempo aggiorniamo la issue #3043 con documentazione sul diagramma degli stati, riportiamo di seguito gli idStato che richiedono particolari elementi obbligatori in richiesta sono:
```
RETTIFICA DATI (Note obbligatorie)
IRRICEVIBILE (11)
SOSPESA (6)
ANNULLATA (4)
```

```
CAMBIO RESIDENZA  (Note obbligatorie)
IRRICEVIBILE (11)  (Specificando anche un nuovo tag "motivo di irricevibilità" tabella di decodifica 60)
SOSPESA (6)
ANNULLATA (4)
```

La tabelle di decodifica aggiuntiva e necessaria per il "motivo di irricevibilità" verrà comunicata nella issue #3043 e verranno pubblicate sul portale pubblico solo dopo il rilascio in ambiente di produzione.

3.1 Nel caso di passaggio da "sospesa" ad "integrata" non è prevista una notifica via webservice 
3.2 Non è corretto, sarà necessario il prossimo rilascio per sanare il bugfix.
Nel prossimo rilascio, sarà distribuita una nuova versione di wsdl/xsd nella issue #3043,  versione che recepisce le modifiche emerse con i comuni apriprista in questi primi giorni di sperimentazione.
Grazie

Saluti
Assistenza ANPR

**Comment by AMonopoliADS** [comment]
grazie Antonio.

ti confermo, che dove è inevitabile, utilizziamo già le tabelle per le decodifiche... con le difficoltà che ne derivano, xchè nel tempo (per altre tabelle) ci siamo ritrovati nelle schede anagrafiche codici non censiti che ci hanno complicato un po' la gestione del dato.
per questo, vedendo disponibile il campo in chiaro, speravo di poterlo evitare.
capisco comunque le motivazioni che mi hai scritto, per cui procederemo con la decodifica anche in questo caso.
per il resto attendiamo il rilascio delle nuove specifiche.

grazie
Alessandro

**Comment by AMonopoliADS** [comment]
a proposito di codici non censiti, segnalo che nella "tabella 52" (tipi allegato) manca il codice '4' - Permesso di soggiorno
(almeno, credo sia quello... considerato che dalla pratica di soggetto straniero mi arriva l'allegato "permesso di soggiorno" con idTipologia '4')

**Comment by apaolacci** [comment]
corretto Alessandro,
nella tabella di decodifica 52 manca il record Codice: 4	 Descrizione: Permesso di soggiorno
Grazie
Seguirà avviso di rilascio

**Comment by ncapozzi** [comment]
Si rimanda all'avviso #3185 per i prossimi rilasci
