### ISSUE TITLE
Saint-Christophe

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3137]
Buongiorno,
dovendo aggiornare le generalità di una persona nata a Saint Christophe nel 1950 e della figlia nata a Saint-Christophe nel 1980, abbiamo evidenziato che la tabella comuni non riporta le due diverse occorrenze ma unicamente Saint Christophe (AO) e codice Istat 007058
Il 24/5/1946 il comune è stato costituito con la denominazione Saint Christophe (AO) e codice Istat 007543, cambiando denominzaione con L.R. N. 61 del 09/12/1976, con decorrenza 2/1/1977,  in Saint-Christophe e codice Istat 007058.
Cortesemente potete verificare?
Grazie
Anna Maria AIMONE
UPI Torino

**Comment by ncapozzi** [comment]
Buonasera,
i codici con quarto carattere 5 (es. 007543) sono codici denominazione creati da ISTAT per mantenere lo storico dei comuni nei vecchi ambienti INA-SAIA e AIRE. In ANPR dovete riportare il cod. ISTAT valido alla data di nascita del cittadino (in accordo con la tabella 3 pubblicata al link https://www.anpr.interno.it/portale/tabelle-di-riferimento) a meno che non abbia già un CF attribuito per un comune valido in un periodo diverso. Non è un problema per ANPR avere due codici istat uguali con Belfiore diversi.
Questa la situazione sulla tabella e per SAINT CHRISTOPHE che dal 02/01/1977 ha il trattino.
17/03/1861	11/01/1927	001929	H669	SAINT CHRISTOPHE
12/01/1927	21/03/1928	007058	H669	SAINT CHRISTOPHE
15/05/1946	01/01/1977	007058	H669	SAINT CHRISTOPHE
02/01/1977	31/12/9999	007058	H669	SAINT-CHRISTOPHE
