### ISSUE TITLE
Cancellazione dati Cessazione Matrimonio

### ISSUE THREAD

**Issue by czxanpr** [italia/anpr#3138]
Salve,
dovrei cancellare i dati relativi alla Cessazione del Matrimonio di un soggetto che non ha mai avuto un divorzio e deve risultare Coniugato.
Ho provato ad eliminare i dati del matrimonio (perché solo quelli mi fa eliminare) e il soggetto mi risulta senza dati di matrimonio e senza dati di Cessazione Matrimonio..
Quando ho inserito nuovamente i dati di matrimonio mi ha riportato nuovamente i dati di Matrimonio e di Cessazione.

Bianco Filippo
Comune di Catanzaro

**Comment by frmariani** [comment]
I dati del matrimonio devono essere eliminati per entrambi i coniugi visto che sono tecnicamente "riconciliati".
gentilmente per le segnalazioni future indichi sempre l'idanpr dell'operazione da indagare e/o l'idanpr del cittadino. Grazie.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
