### ISSUE TITLE
Utilizzo WSP001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3139]
Buonasera, Inviamo il seguente xml ma la risposta è 
<faultcode>env:Client</faultcode>
<faultstring>Internal Error</faultstring>

quale può essere il problema? Grazie 

<?xml version="1.0"?>
-<p00:RichiestaP001 xmlns:p00="http://sogei.it/ANPR/P000sc">
-<testataRichiesta>
<idOperazioneComune>2022P00100004</idOperazioneComune>
<codMittente>061022</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>P001</operazioneRichiesta>
<dataOraRichiesta>2022-02-16T07:55:57.404Z</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<protocolloComune>2022P0010004</protocolloComune>
<tipoInvio>PROD</tipoInvio>
<dataDecorrenza>2022-02-16</dataDecorrenza>
<nomeApplicativo>SERDEMO</nomeApplicativo>
<versioneApplicativo>1.00</versioneApplicativo>
<fornitoreApplicativo>I.T. SYSTEMS</fornitoreApplicativo>
</testataRichiesta>
-<criteriRicerca>
<dataIniziale>2021-11-01</dataIniziale>
<dataFinale>2021-11-15</dataFinale>
<idTipologia>1</idTipologia>
<idStatoRichiesta>2</idStatoRichiesta>
</criteriRicerca>
</p00:RichiestaP001>

**Comment by rinonasti** [comment]
[20220000001_P001_061022.zip](https://github.com/italia/anpr/files/8082466/20220000001_P001_061022.zip)

**Comment by rinonasti** [comment]
ho allegato file

**Comment by apaolacci** [comment]
Buongiorno,
non troviamo l'invocazione 2022P00100004 in ambiente TEST-COMUNI. Raggiungete l'endpoint correttamente dal client?

Nel frattempo abbiamo provato a simulare la richiesta allegata nel file zip ed è formalmente valida ma in ogni caso restituirebbe un errore perché l'intervallo di ricerca passato in input è superiore ai 7 giorni. 

Allego request/response xml che avreste dovuto ricevere.

[2022P00100004.txt](https://github.com/italia/anpr/files/8087522/2022P00100004.txt)

Saluti
Assistenza ANPR

**Comment by rinonasti** [comment]
E' inviato in PROD endpoint  https://ws.anpr.interno.it/ANPR-WSP000/AnprServiceP000

**Comment by apaolacci** [comment]
Dovrebbe utilizzare l'endpoint di TEST COMUNI  https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000

**Comment by rinonasti** [comment]
fatto stesso errore

**Comment by apaolacci** [comment]
Purtroppo non c'è evidenza sul log della request. Siete sicuri di raggiungere il nostro server dal vostro client?
Non troviamo nessuna chiamata in TEST COMUNI per il comune codIstat=061022 Caserta.

**Comment by rinonasti** [comment]
verifichiamo

**Comment by rinonasti** [comment]
abbiamo provato, non parte transazione, in debug c'è errore;  elenco(Unknown Source)
Ha idea dell'errore
Grazie per la fattiva collaborazione

**Comment by rinonasti** [comment]
Questo e la request preparata 
[dati_inviati.zip](https://github.com/italia/anpr/files/8091295/dati_inviati.zip)

**Comment by rinonasti** [comment]
Buonasera,
Risolto Grazie
Come posso trovare delle transazioni in ambiente TEST (non accetta PROD) 
In ambiente PROD ci sono "rettifiche" come posso scaricarle.

**Comment by rinonasti** [comment]
Buongiorno,
Per ambiente TEST tutto ok abbiamo i due soggetti cittadini su cui operare.
DOMANDA
Vorrei scaricare le richieste di rettifiche in ambiente di produzione

**Comment by rinonasti** [comment]
Altro quesito
In risposta P002 trovo pdf nel formato vedi allegato Pratica1.txt mentre lo aspetto come vedi allegato Pratica.txt
[Pratica1.txt](https://github.com/italia/anpr/files/8108014/Pratica1.txt)
[Pratica.txt](https://github.com/italia/anpr/files/8108015/Pratica.txt)

**Comment by apaolacci** [comment]
Buonasera,
i due file Pratica1.txt e Pratica.txt provengono dallo stesso ambiente di integrazione TEST COMUNI ?

In ambiente di produzione la versione dei ws P000 non contiene le evoluzioni che le software house stanno invece analizzando e testando in ambiente TEST COMUNI e che vengono aggiornati con le modifiche richieste dai tavoli di sperimentazione con i comuni e la risoluzione di bug.

Per scaricare le rettifiche in ambiente di produzione, nella request del P001 va impostato:
- il range temporale che si vuole scaricare  (per il momento limitato a 7gg ma sarà aumentato)
- lo stato in cui trovare le pratiche  (potrà essere anche _vuoto_ ricercando per _ogni stato_)
- la tipologia pratica ad **1** Rettifica Dati

```
		  </testataRichiesta>
		  <criteriRicerca>
		    <dataIniziale>2022-02-14</dataIniziale>
		    <dataFinale>2022-02-18</dataFinale>
		    <idTipologia>**1**</idTipologia>
		    <idStatoRichiesta>2</idStatoRichiesta>
		  </criteriRicerca>
      </p00:RichiestaP001>
```

**Comment by rinonasti** [comment]
Buongiorno,
pratica è nella risposta P002 TEST (Dichiarazione di cambio residenza N. 1230093) se lo rinomino .pdf viene fuori una pagina bianca.
paratica1 non è in  alcuna risposta ma ho preso la pratica da webapp (pdf ) e ho effettuato un encode base64

**Comment by apaolacci** [comment]
Prendiamo in carico la segnalazione e la stiamo indagando.
Vi faremo sapere, grazie.

**Comment by ncapozzi** [comment]
Si rimanda all'avviso #3185 per i prossimi rilasci
