### ISSUE TITLE
Anomalia accesso al anpr

### ISSUE THREAD

**Issue by FABIOCREANGA** [italia/anpr#3140]
Salve, provo ad accedere al servizio anpr per cittadini ma non mi fa entrare. Mi dice che c'è qualche anomalia nei miei dati, da sanare. Il numero della mia tessera sanitaria è  80380001200317999930. Grazie

**Comment by cmigliardi** [comment]
buonasera, cortesemente ci può inviare e prime 6 lettere del suo codice fiscale  per fare i controlli?  - grazie

**Comment by FABIOCREANGA** [comment]
Buonasera le prime 6 lettere del codice fiscale sono crnfrn . Grazie

Il Mer 16 Feb 2022, 19:29 cmigliardi ***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
dunque per il codice fiscale non il quale accede che termina con la lettera  X   - non esiste una scheda in Anpr  -  lei ha anche un altro codice fiscale che termina con la lettera V ma neanche in questo caso la scheda non è in Anpr - le consiglio di  rivolgersi al suo comune di competenza e verificare i dati  per sanare la situazione
