### ISSUE TITLE
COMUNE DI LEQUIO TANARO (CUNEO) CERTIFICABILITA' PARZIALE

### ISSUE THREAD

**Issue by ValeriaRoa** [italia/anpr#3141]
Un comune limitrofo sta procedendo con una mutazione anagrafica  di una ns residente al momento in cui la persona viene richiamata dall' anpr il comune si ritrova il seguente messaggio:
certificabilità parziale solo residenza e stato di famiglia.
come è possibile sistemare?
grazie

**Comment by frmariani** [comment]
Il comune limitrofo non può effettuare una mutazione anagrafica di una vostra residente; dalla tipologia di controllo che indica, immagino che stiano richiedendo dei certificati; in questo caso, per modificare la posizione certificabile del suo cittadino deve effettuare una mutazione dei dati anagrafici e selezionare la corretta tipologia di certificabilità presente nelle generalità.

**Comment by ValeriaRoa** [comment]
la cittadina sta richiedendo la residenza nel comune limitrofo e al momento del caricamento della pratica al comune di nuova residenza esce il messaggio di cui sopra. dobbiamo sistemare noi ?

**Comment by frmariani** [comment]
gentilmente mi indichi l'idanpr della cittadina ed il comune che tenta l'operazione

**Comment by ValeriaRoa** [comment]
il codice anpr della cittadina è 78569205 il comune di nuova residenza è Savigliano (Cn)

**Comment by frmariani** [comment]
la cittadina risulta con la certificabilità parziale, quindi modifichi la posizione certificabile come indicato precedentemente
