### ISSUE TITLE
Scarico tabella relazioni di parentela

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#3143]
Buongiorno, provando a scaricare la tabella in oggetto al seguente link, si riceve errore:

https://www.anagrafenazionale.interno.it/wp-content/uploads/2020/06/tabella_5_relazioni_parentela.xlsx
Errore 404

Pagina non trovata

Saluti
Laboratorio Dedagroup

**Comment by cvignati** [comment]
Sono riuscito a scaricarla aggiornata a questo link: https://www.anagrafenazionale.interno.it/wp-content/uploads/tabella_5_relazioni_parentela.xlsx
