### ISSUE TITLE
Operazione non ammessa: comune non competente

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3144]
COMUNE DI CAPONAGO
Rif. Varisco M.Giuseppina

Buongiorno
abbiamo cercato di eseguire un immigrazione ci ritorna l'errore Operazione non ammessa: comune non competente

Di seguito i riferimenti dell'operazione:
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-02-17 10:23:28 , idOperazioneANPR 791629664

Si resta in attesa di gentile risposta
Saluti

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
