### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza

### ISSUE THREAD

**Issue by Alberova** [italia/anpr#3146]
Buongiorno, 
Scrivo a nome di mio nonno, Rovatti Cesare codice fiscale RVTCSR39.....
Non ha accesso al sito per il motivo del titolo
![Screenshot_20220217-175335_Samsung Internet](https://user-images.githubusercontent.com/99901413/154531345-6aea1b1d-0802-4a35-9318-2cf7daccf217.jpg)
Quello che vedo è dimostrato dall'immagine allegata

**Comment by cmigliardi** [comment]
gentile signor Rovatti  le consigliamo di rivolgersi al suo comune di competenza Milano  per far verificare la sua scheda in ANPR 
(occorre ad esempio che la scheda abbia il "codice fiscale validato" da agenzia delle entrate, che la scheda non sia cancellata, 
che la scheda non sia duplicata, che esista in ANPR, etc ......) ovviamente noi non possiamo fornire dettagli ma le indicazioni sono sufficienti affinché il comune vada a verificare la scheda in ANPR per poi poterla sanare.
