### ISSUE TITLE
Riferimento titolo:  Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza

### ISSUE THREAD

**Issue by Alberova** [italia/anpr#3147]
In riferimento al post https://github.com/italia/anpr/issues/3146#event-6091969058
Vorrei chiedere: che cosa bisogna chiedere? Dal sito del comune è possibile richiedere ciò che ho bisogno? 
Non vedo alcun collegamento sul sito tra comune di Milano e anpr..

**Comment by cmigliardi** [comment]
deve sentire l'anagrafe del comune  e andare a verificare i suoi dati anagrafici . esempio vedo che lei ha due nomi , è così  insomma va verificata tutta la parte dei dati anagrafici .

**Comment by cmigliardi** [comment]
prenda appuntamento con l'anagrafe
