### ISSUE TITLE
Problema attribuzione codice scheda famiglia attribuito da ANPR

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3148]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Buongiorno
a seguito di una scissione di MANCA MATTIA con creazione nuova famiglia (corretto) e successiva immigrazione nella stessa famiglia di CORONA TERESA, è accaduto che entrambi in ANPR hanno il medesimo codice famiglia di anagrafe locale, ma a CORONA TERESA non è stato attribuito il codice scheda famiglia da parte di ANPR.

Come possiamo risolvere ?

Si resta in attesa di cortese riscontro.
Saluti

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
