### ISSUE TITLE
stato civile errore data di morte 

### ISSUE THREAD

**Issue by antoele** [italia/anpr#3149]
buongiorno, nel mese di luglio e' deceduta una nostra residente, erroneamente e' stato scritto sull'atto di morte "maggio" e non luglio.
dopo un paio di giorni e' stato rettificato il tutto, e fatti tutti gli invii anche INA SAIA.
settimana scorsa la fmiglia andando a fare la successione si sono accorti che all'agenzia delle entrate ancora risulta il mese errato.
in ANPR la persona non esiste poiche' il subentro e' avvenuto a novembre 2021.
come possiamo aiutare il cittadino?

**Comment by rvinzani** [comment]
Potete operare da PuntoFisco inserendo le informazioni corrette direttamente sul sistema di Agenzia delle Entrate
