### ISSUE TITLE
EN238 su servizio 5005

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3152]
Annullate inizialmente una serie di mutazioni per i soggetti VNILGU94C11I483V e DLCJSC97A59L086G, non è stato possibile annullare operazione 793317587 per presenza di operazioni successive.
Controllando la posizione anagrafica dei soggetti si fa presente l’anomalia per cui VNILGU94C11I483V risulti residente a Colli al Metauro alla sezione Residenza ma in famiglia con persone residenti a Cartoceto alla sezione Famiglia.
Nel tentativo di risolvere è stato cancellato per altri motivi VNIGRL22B07D488A,ultimo componente aggiunto alla famiglia iniziale e residente a Colli al Metauro ma ora riproponendo servizio 5005 per VNILGU94C11I483V compare errore EN238 su operazione 793712525

L’obiettivo finale è che i tre soggetti siano residenti a Colli al Metauro.

**Comment by dgiaccari** [comment]
abbiamo provveduto ad annullare noi l'operazione 793317587 e a ripristinare la situazione corretta per tutti e 3 i soggetti coinvolti
cordiali saluti
