### ISSUE TITLE
[WS P001] - visualizzazione elenco richieste

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#3153]
Salve,
stiamo effettuando i test delle nuove funzionalità di gestione delle richieste di rettifica dati e variazione di indirizzo ed ho notato che sulla Web App è possibile visualizzare l'elenco completo delle richieste, in un determinato intervallo temporale, a prescindere dallo stato della richiesta, se nel componente di selezione "Stato Richiesta" non si indica alcuno stato ma si "seleziona" la prima delle possibili scelte che è una riga bianca. Personalmente trovo molto utile questa opzione, che consente di visualizzare l'insieme delle pratiche e i loro stati, anche perché può capitare che un operatore non ricordi lo stato di avanzamento di una particolare pratica e deve nel caso effettuare ricerche successive sui vari stati.
Questa opzione non è però di fatto consentita nella modalità Web Services. Se si effettua una richiesta "elenco" utilizzando il WS in oggetto (tipo operazione P001), nella sezione '_criteriRicerca_' è obbligatorio indicare il campo '_idStatoRichiesta_' e tra i valori ammessi sembra non ce ne sia uno che consenta la visualizzazione dell'insieme delle richieste a prescindere dallo stato. Bisogna pertanto indicare un preciso valore che consente la visualizzazione delle pratiche che si trovano in tale stato, ma come detto sarebbe comodo avere anche la possibilità, come nella Web App, di avere una visione d'insieme delle richieste pervenute con il relativo stato di avanzamento.
Sarebbe possibile, ad esempio, inserire nelle tabelle 53 e 58 un valore che consenta la selezione di tutte le richieste pervenute, oppure avere la possibilità di non indicare alcun valore nel campo '_idStatoRichiesta_', in modo da consentire questa opzione anche in modalità Web Services?
Grazie,
cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by ncapozzi** [comment]
Buonasera,
il comportamento di P001 sarà adeguato alla web app per quanto riguarda la selezione per stato di lavorazione

**Comment by ncapozzi** [comment]
Si rimanda all'avviso #3185 per i prossimi rilasci
