### ISSUE TITLE
[ws P002] Dettaglio Richiesta: note operatore

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3154]
utilizzando i web-service di consultazione dei dettagli della pratica (P002), non mi sembra siano visibili le note che l'operatore ha indicato in occasione dell'aggiornamento di stato.

dalla web-app, entrando in consultazione della pratica, si vedono in calce alla pagina nel punto "note precedenti"
da web-service, invece, questa informazione non è visibile.

essendo un'informazione associata alla modifica di stato - se non sono già previste altrove - forse dovrebbero essere inserite nei dettagli della lista "storicoStati"
```
        <storicoStati>
            <!--Element statoRichiesta is optional, maxOccurs=unbounded-->
            <statoRichiesta>
                <idStato>0</idStato>
                <operatore>string</operatore>
                <dataStato>2002-10-10T12:00:00-05:00</dataStato>
            </statoRichiesta>
            <statoRichiesta>
                <idStato>0</idStato>
                <operatore>string</operatore>
                <dataStato>2002-10-10T12:00:00-05:00</dataStato>
            </statoRichiesta>
            <statoRichiesta>
                <idStato>0</idStato>
                <operatore>string</operatore>
                <dataStato>2002-10-10T12:00:00-05:00</dataStato>
            </statoRichiesta>
        </storicoStati>
```

resto in attesa di riscontro.
grazie

Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera,
la fix per la risoluzione del problema è già stata eseguita. Sarà inserita nel prossimo rilascio che includerà anche ulteriori modifiche che sono state richieste. Seguirà avviso di rilascio

**Comment by ncapozzi** [comment]
Si rimanda all'avviso #3185 per i prossimi rilasci
