### ISSUE TITLE
Esponente numero civico

### ISSUE THREAD

**Issue by MMaurizio** [italia/anpr#3155]
Buongiorno, ho constatato che la procedura di variazione residenza, nella parte dell'indirizzo non prevede il form dell'esponente del numero civico, mentre è previsto l'esponente del numero interno.
Come quindi procedere al cambio di residenza in anpr per chi ha l'indirizzo con il civico provvisto di esponente. Esempio 1/A.
Grazie Maurizio

**Comment by ncapozzi** [comment]
Buonasera
ci è già stato richiesto di prevedere che il campo civico possa accettare numeri, lettere, spazio, / e - (es. 8/A, 7-L, 5B). Seguirà avviso di rilascio

**Comment by ncapozzi** [comment]
Si rimanda all'avviso #3185 per i prossimi rilasci
