### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio 

### ISSUE THREAD

**Issue by G-Iolandi** [italia/anpr#3158]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

![120000230-fde53500-bfa8-11eb-84c9-3dd67daeac57](https://user-images.githubusercontent.com/100191876/155088485-49068d96-8cb5-42ec-bda1-3cfcd4ddba93.png)

Cosa si può fare?

**Comment by cmigliardi** [comment]
per favore potrebbe darci le prime 6 lettere del suo codice fiscale ? per verificare ? grazie

**Comment by G-Iolandi** [comment]
Si
LNDGMR

Grazie in anticipo.

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1994 - deve rivolgersi al comune di competenza Roma per verificare la presenza della sua scheda in Anpr

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
