### ISSUE TITLE
Web App - servizio di consultazione

### ISSUE THREAD

**Issue by AGrossiVE** [italia/anpr#316]
Comune di Venezia. Ambiente di Pre-Subentro

Cercando una persona con un cognome del tipo"GGGGGGG' UUUUUUU" il sistema restituisce un messaggio del tipo "Il campo cognome contiene caratteri non validi". La consultazione dei dati della persona è possibile solo ricercandola attraverso il codice fiscale. 

Seguirà invio di email a "segnalazioni-anpr@teamdigitale.governo.it" con la descrizione del caso specifico. 

Grazie

**Comment by gcarbonin** [comment]
#315

**Comment by gcarbonin** [comment]
stiamo verificando

**Comment by azabatta** [comment]
Le due criticità (ricerca cittadino con nome di una lettera e ricerca cittadino con apostrofo nel cognome)  sono state risolte. Per ambedue le casistiche sono state effettuate le prove presso il comune. 
La modifica è disponibile negli ambienti di TEST_COMUNI e PRESUBENTRO. 
Grazie per la segnalazione
