### ISSUE TITLE
errore in annullamento certificato

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#3160]
Buongiorno, 
cercando di annullare il certificato 795562955 ma mi dà errore :

la richiesta non risulta valida secondo i nuovi XSD CODICE ERRORE 489

Come posso risolvere?

grazie
Raffaella 
Comune di Venezia

**Comment by mttfranci** [comment]
E un'altra domanda, in che fase di preciso ottenete l'errore? Nella ricerca del certificato? Oppure ottenete l'elenco dei certificati e l'errore è al momento di annullarlo?
Potreste fornire ogni dettaglio utile sulle operazioni svolte? (anche la modalità di ricerca del certificato? per protocollo, identificativo soggetto, dati anagrafici ecc)

**Comment by raffaella30174** [comment]
Buongiorno, 
si tratta di annullamento da webapp
l'errore è nella ricerca, non lo trova nè con il numero nè con il nome.
il certificato è il  n. 795562955 e con la verifica da qr codelo visualizza e lo riconosce emesso e valido
Facciamo, purtroppo con frequenza, queste operazioni di annullamento e non ci era mai capitato.
Non ho il nominativo della persona o il suo id in questo momento ma se serve integro la risposta domani.
Prima di segnalare abbiamo anche verificato ed è totalmente certificabile in webapp.
Grazie della sempre pronta e fattiva collaborazione
Raffaella Campagnol

**Comment by mttfranci** [comment]
Salve, non è necessario conoscere i dati del soggetto se ci confermate che è l'intestario del certificato (id soggetto 61225587). Però sarebbe utile sapere quali dati anagrafici sono stati inseriti nella ricerca (es. nome e cognome, solo codice fiscale ecc anche senza ripeterli).

**Comment by mttfranci** [comment]
Anche l'indicazione di data e ora a cui è stata eseguita l'operazione sarebbe utile, eventualmente potete anche provare a ripeterla, grazie in anticipo.

**Comment by raffaella30174** [comment]
Buongiorno,
mail di prova

Raffaella Campagnol

Area Servizi al Cittadino e Imprese e Qualità della Vita
Settore Servizi al Cittadino, Protocollo e Archivio Generale
Via Palazzo 8 - 30173 Venezia-Mestre
telefono 041 274 6575
mail: ***@***.***
PEC: ***@***.***
info:  https://www.comune.venezia.it/it/content/anagrafe

________________________________
Da: Matteo ***@***.***>
Inviato: lunedì 28 febbraio 2022 14:22
A: italia/anpr ***@***.***>
Cc: Raffaella Campagnol ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] errore in annullamento certificato (Issue #3160)


Anche l'indicazione di data e ora a cui è stata eseguita l'operazione sarebbe utile, eventualmente potete anche provare a ripeterla, grazie in anticipo.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fanpr%2Fissues%2F3160%23issuecomment-1054252247&e=707df9c2&h=95193ac0&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANRTFWWASO4FCPV5GQMV6KDU5NZKHANCNFSM5PAVIEJQ&e=707df9c2&h=17dbd9f5&f=n&p=y>.
Triage notifications on the go with GitHub Mobile for iOS<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&e=707df9c2&h=0844ee47&f=n&p=y> or Android<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&e=707df9c2&h=5b7735db&f=n&p=y>.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Le informazioni contenute nel presente messaggio ed i relativi allegati sono unicamente per i destinatari indicati e possono essere riservate ai sensi della vigente normativa. Ove non siate i destinatari di questo messaggio, l'eventuale diffusione, distribuzione e/o copiatura dei contenuti dello stesso e' proibita ai sensi della normativa applicabile. Se avete ricevuto questo messaggio per errore, siete pregati di informare il mittente immediatamente dell'accaduto e di cancellare il messaggio. Questo indirizzo di posta elettronica non e' un indirizzo di posta privato e percio' il suo utilizzo e' soggetto a regolamentazione.

**Comment by raffaella30174** [comment]
Buongiorno,
ho riprovato a cancellare il certificato della persona oggi dalle 12.21 in sequenza
richiamando la persona con cf [cid:2b62cf6c-7482-43c7-8778-2fe36ddd40c0]
richiamando la persona con il nome
con id ANPR
con n. scheda attribuito dal comune
per questi tentativi è la risposta è stata: nessun elemento trovato
facendo la richiesta con n. di certificato ANPR 791842742
la risposta è:

[cid:133914c1-59f6-4475-b2a4-46cc8d3f1c13]
Grazie.
Raffaella
Raffaella Campagnol

Area Servizi al Cittadino e Imprese e Qualità della Vita
Settore Servizi al Cittadino, Protocollo e Archivio Generale
Via Palazzo 8 - 30173 Venezia-Mestre
telefono 041 274 6575
mail: ***@***.***
PEC: ***@***.***
info:  https://www.comune.venezia.it/it/content/anagrafe

________________________________
Da: Raffaella Campagnol ***@***.***>
Inviato: martedì 1 marzo 2022 12:27
A: italia/anpr ***@***.***>
Oggetto: R: [italia/anpr] errore in annullamento certificato (Issue #3160)

Buongiorno,
mail di prova

Raffaella Campagnol

Area Servizi al Cittadino e Imprese e Qualità della Vita
Settore Servizi al Cittadino, Protocollo e Archivio Generale
Via Palazzo 8 - 30173 Venezia-Mestre
telefono 041 274 6575
mail: ***@***.***
PEC: ***@***.***
info:  https://www.comune.venezia.it/it/content/anagrafe

________________________________
Da: Matteo ***@***.***>
Inviato: lunedì 28 febbraio 2022 14:22
A: italia/anpr ***@***.***>
Cc: Raffaella Campagnol ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] errore in annullamento certificato (Issue #3160)


Anche l'indicazione di data e ora a cui è stata eseguita l'operazione sarebbe utile, eventualmente potete anche provare a ripeterla, grazie in anticipo.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fanpr%2Fissues%2F3160%23issuecomment-1054252247&e=707df9c2&h=95193ac0&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANRTFWWASO4FCPV5GQMV6KDU5NZKHANCNFSM5PAVIEJQ&e=707df9c2&h=17dbd9f5&f=n&p=y>.
Triage notifications on the go with GitHub Mobile for iOS<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&e=707df9c2&h=0844ee47&f=n&p=y> or Android<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&e=707df9c2&h=5b7735db&f=n&p=y>.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Le informazioni contenute nel presente messaggio ed i relativi allegati sono unicamente per i destinatari indicati e possono essere riservate ai sensi della vigente normativa. Ove non siate i destinatari di questo messaggio, l'eventuale diffusione, distribuzione e/o copiatura dei contenuti dello stesso e' proibita ai sensi della normativa applicabile. Se avete ricevuto questo messaggio per errore, siete pregati di informare il mittente immediatamente dell'accaduto e di cancellare il messaggio. Questo indirizzo di posta elettronica non e' un indirizzo di posta privato e percio' il suo utilizzo e' soggetto a regolamentazione.

**Comment by mttfranci** [comment]
Salve, temo che manchino degli allegati. 
Inoltre non ho capito se è comparso il messaggio 489.

**Comment by raffaella30174** [comment]
Certo mi scusi avevo risposto alla mail.
Allego solo lo screen di errore
![thumbnail_image](https://user-images.githubusercontent.com/56832730/156186162-f91d1ade-15ca-4dce-aba6-bdf887f42b87.png)
![thumbnail_image](https://user-images.githubusercontent.com/56832730/156186213-9a2cd86c-755f-4dec-b8cb-a17edfc74efd.png)

**Comment by mttfranci** [comment]
Salve, stiamo ancora verificando l'anomalia.
Saluti

**Comment by raffaella30174** [comment]
Buongiorno, 
ho lo stesso codice di errore EN489 su altri due certificati:
813819310 del 08/03/2022
791842742 del 17/02/2022
provato ad annullarli oggi  alle 09 e 45
Grazie

**Comment by mttfranci** [comment]
Scusate il ritardo nella risposta.
Cortesemente potreste riprovare?
Grazie in anticipo

**Comment by raffaella30174** [comment]
Buongiorno, 
siamo riusciti ad annullare tutti i certificati
grazie della collaborazione
Raffaella
