### ISSUE TITLE
Rettifica generalità - errore EAM28 

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3161]
Buongiorno
Ambiente di PRODUZIONE comune di TERRACINA.

Inviando WS 5008 per rettifica di generalità si ottiene il seguente errore:
EAM28 - Altri soggetti individuati in AT dai NUOVI dati anagrafici, richiesta di variazione dati non effettuabile - Cognome: XXX  Nome: XXXX CF: <NUOVO CF>-
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-02-18 11:00:26 , idOperazioneANPR 793185398 - Cognome: XXXX  Nome: XXXX CF: <NUOVO CF>-

Consultando AE da WA il vecchio CF risulta marcato ANPR e già collegato a quello derivante dalle nuove generalità.
Come si deve procedere

Ringrazio anticipatamente.
G. Trisolini

**Comment by frmariani** [comment]
Il codice fiscale è stato svalidato; potete riprovare la modifica dei dati

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
E' stato fatto un invio oggi con questo risultato:
 EAV51 - Più codici fiscali individuati in AT - Cognome: XXXX Nome: XXXX CF: YYYY 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-02-24 10:29:36 , idOperazioneANPR 799938337 - Cognome: XXXX Nome: XXXX CF: YYYY-


In attesa di indicazioni, auguro buona giornata

**Comment by frmariani** [comment]
Purtroppo mi sono accorata solo ora che state tentando l'inversione di link verso un codice fiscale omocodice.
In questo caso l'operazione non è possibile con le funzionalità a disposizione del sistema ANPR.
Dovete scrivere alla Direzione centrale dell'Agenzia delle Entrate inviando tutta la documentazione del caso in vostro possesso.
Lascio il codice fiscale svalidato in modo che l'agenzia possa operare in autonomia.
entrate.archivioanagrafico@agenziaentrate.it

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
