### ISSUE TITLE
[P002] Info su "tipoDettaglioP002"

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3162]
Buongiorno,
abbiamo svolto delle prove in ambiente di test, simulando diverse richieste dal portale del cittadino (di test).
In tutte le casistiche la risposta del servizio P002 ha sempre i tag "soggettoInteressato" e "famigliaConvivenza" mancanti.
In quale situazione compaiono?

Grazie

**Comment by apaolacci** [comment]
Salve,
si saranno sempre assenti. E' possibile trascurarli nell'implementazione attuale, non saranno mai restituiti.
I tag "soggettoInteressato" e "famigliaConvivenza" fanno parte di una prima idea di realizzazione delle funzionalità di Rettifica e Cambio Residenza in cui si apriva una richiesta per conto di un soggetto terzo, diverso dal "richiedente" (l'Interessato) o per conto della propria famiglia anpr (la famigliaConvivenza).
