### ISSUE TITLE
Codice fiscale non validato - soggetto non presente in AE

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3163]
Buongiorno,
abbiamo estratto da ANPR un elenco di cittadini con CF non validato. 
Abbiamo verificato essere iscritti AIRE. 
Abbiamo verificato che in Agenzia delle Entrate questi soggetti non sono presenti. 
Qual è la procedura corretta per sistemare la situazione?
Ringrazio fin da subito del vostro gentile riscontro.
Andrea Formenti
Comune di Caponago

**Comment by ncapozzi** [comment]
Buongiorno,
non è obbligatoria l'attribuzione del CF per un cittadino AIRE che per esempio sia nato e vissuto all'estero e non ha alcun rapporto con Agenzia delle Entrate. E' richiesto un CF valido nelle iscrizioni AIRE per espatrio e ai fini del rilascio CIE.
