### ISSUE TITLE
[6001] Errore EN493 "La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione sul soggetto/famiglia"

### ISSUE THREAD

**Issue by Gianluke** [italia/anpr#3165]
Buonasera,
su ambiente di test per il Comune di Bari, richiamando il servizio /ANPR6001ServizioCertificazione/AnprService6001, a seguito della richiesta seguente:

```
<ns2:Richiesta6001
	xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
	<testataRichiesta>
		<idOperazioneComune>1234567890</idOperazioneComune>
		<codMittente>888191</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>6001</operazioneRichiesta>
		<dataOraRichiesta>2022-02-22T17:32:29.849+01:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>FREE</tipoInvio>
	</testataRichiesta>
	<listaTipiCertificati>
		<tipoCertificato>1</tipoCertificato>
	</listaTipiCertificati>
	<soggettoIntestatario>
		<generalita>
			<codiceFiscale>
				<codFiscale>RSSNTN81A05B519S</codFiscale>
			</codiceFiscale>
			<senzaCognome>1</senzaCognome>
			<senzaNome>1</senzaNome>
		</generalita>
	</soggettoIntestatario>
	<datiControllo>
		<tipoRichiedente>3</tipoRichiedente>
		<tipoRichiesta>1</tipoRichiesta>
		<paEstera>0</paEstera>
		<emissione>2</emissione>
		<bollo>0</bollo>
		<bolloVirtuale>1</bolloVirtuale>
		<diritti>0</diritti>
	</datiControllo>
</ns2:Richiesta6001>
```

(omessa busta WS-Security)

otteniamo la response di errore: 

```
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Body>
		<a:Risposta6001
			xmlns:a="http://sogei.it/ANPR/6001certificazione">
			<a:Risposta6001KO>
				<testataRisposta>
					<idOperazioneComune>1234567890</idOperazioneComune>
					<codMittente>888191</codMittente>
					<codDestinatario>ANPR02</codDestinatario>
					<operazioneRichiesta>6001</operazioneRichiesta>
					<dataOraRichiesta>2022-02-22T17:45:17.917+01:00</dataOraRichiesta>
					<idOperazioneANPR>0</idOperazioneANPR>
					<esitoOperazione>XXXX</esitoOperazione>
				</testataRisposta>
				<listaErrori>
					<errore>
						<codiceErroreAnomalia>EN493</codiceErroreAnomalia>
						<tipoErroreAnomalia>E</tipoErroreAnomalia>
						<testoErroreAnomalia>La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione  sul soggetto/famiglia</testoErroreAnomalia>
					</errore>
				</listaErrori>
			</a:Risposta6001KO>
		</a:Risposta6001>
	</soapenv:Body>
</soapenv:Envelope>
```

Da cosa è dovuto questo comportamento, essendo il cittadino registrato su ambiente di test?
Abbiamo notato che anche da applicazione web, se si effettua la ricerca del CF per il comune "FREETESTCCXXXVII " (comune assegnato all'utenza di test da noi utilizzata), non vengono ritornati risultati (codice errore EN122) mentre vengono ritornati se si effettua una ricerca nazionale.

La visura dei dati anagrafici per lo stesso CF  (servizio 3002) ritorna correttamente i dati del cittadino (con o senza il flag ricerca nazionale), sia via applicazione web che tramite Web Service.

I test sono stati effettuati nella giornata odierna dalle ore 18:10 alle ore 18:13.

Grazie.

**Comment by amollicone1982** [comment]
In ambiente test comuni non c'e' nessun soggetto con quel cf (RSSNTN81A05B519S)

**Comment by Gianluke** [comment]
Buongiorno,
chiedo scusa per quanto erroneamente riportato, l'ambiente in questione è quello FREE (https://wsfree.anpr.interno.it), sul quale il soggetto RSSNTN81A05B519S risulta presente ma per il quale non ci risulta possibile generare i certificati anagrafici tramite il WS 6001.

Grazie ancora.

**Comment by amollicone1982** [comment]
In ambiente freetest il soggetto con quel cf ha come cognome rossi e come nome antonio (non senzacognome) e per tale motivo non viene trovato
