### ISSUE TITLE
Inversione principalità codice fiscale

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3166]
Buongiorno,
cittadina nata in Uzbekistan nel 1979 ora è in ANPR e AE con cf principale z259 e collegato il cf z143. Ho provato a fare inversione di principalità ma webapp restituisce il seguente errore: idOperazioneANPR 798205432 (Codice: EN527).
Come posso procedere?
Grazie!

**Comment by rvinzani** [comment]
Non sono riuscita a chiamarla al numero 0544482272. Sa indicarmene uno diverso oppure quando posso provare

**Comment by katiavacchi** [comment]
chiedo scusa. può chiamare allo 0544 482482 (8.30-12.30) e chiedere di me. grazie.

**Comment by rvinzani** [comment]
Da ANPR non è possibile effettuare questa inversione in quanto lo stato di nascita è lo stesso. Se la cittadina vuole ripristinare il precedente CF deve scrivere a entrate.archivioanagrafico@agenziaentrate.it chiedendo l'inversione di link. Poi ci ricontatta una volta avuta risposta positiva da AE per allineare ANPR
