### ISSUE TITLE
P000 Informazioni AIRE

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3167]
Buongiorno,
probabilmente è stato detto nelle varie riunioni, ma ce lo siamo perso.

Abbiamo alcuni dubbi sul portale ANPR per le richieste di cambio residenza:
- permette ai cittadini residenti di fare richieste di passaggio all'AIRE?
- permette a cittadini già iscritti all'AIRE di richiedere il rientro nel comune di iscrizione AIRE o un comune diverso?
- permette ai cittadini già iscritti all'AIRE di cambiare indirizzo sempre rimanendo all'AIRE?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno
per quanto riguarda i cittadini AIRE per il momento il momento il servizio consente solo  di dichiarare il rientro nel comune di iscrizione AIRE o in un comune diverso
