### ISSUE TITLE
P000 Informazioni AIRE .v2

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3168]
In riferimento all'issue #3167 
Grazie per la risposta.

Volevo chiedere, dentro il tag "soggettoRichiedente" sarebbe possibile per voi aggiungere l'informazione "soggettoAIRE" ?
Ci eviterebbe di fare una chiamata 3002 solo per sapere se il soggetto è AIRE

Grazie

**Comment by ncapozzi** [comment]
Buonasera
per quale motivo vi occorre sapere se il soggetto è AIRE?

**Comment by SAlberto** [comment]
Ci servirebbe saperlo perchè se il cittadino è un AIRE prima di aprire la pratica APR4 dobbiamo cancellarlo dall'AIRE.
Certamente possiamo fare una 3002 per saperlo oppure interrogare l'archivio locale, ma sarebbe stato molto più comodo averlo insieme a tutti gli altri dati nella risposta.

**Comment by ncapozzi** [comment]
Perché "cancellare"? In ANPR non si fanno più cancellazioni e iscrizioni per i cambi di residenza ma solo mutazioni, a prescindere che sia da Italia a Italia o dall'estero all'Italia. Per fare la mutazione per reimpatrio con un 5001 o un 5005 non occorre sapere se in partenza il cittadino è AIRE o APR.

**Comment by SAlberto** [comment]
In ANPR no, ma sui vari ambienti locali sì.
Non importa verifichiamo l'informazione sulla base dati del comune
