### ISSUE TITLE
Scioglimento di unione civile

### ISSUE THREAD

**Issue by PAOLAPP** [italia/anpr#317]
Ambiente di PreSubentro - Comune di Venezia

In relazione all’operazione (id ANPR 270984):
<idOperazioneComune>1908</idOperazioneComune><codMittente>027042</codMittente><codDestinatario>ANPR00</codDestinatario><operazioneRichiesta>5008</operazioneRichiesta><dataOraRichiesta>2017-09-20T10:00:14Z</dataOraRichiesta>

Riguardante l’inserimento di uno scioglimento di unione civile con presenti i relativi dati sottostanti 

<datiEvento><dataEvento>2017-09-02</dataEvento><luogoEvento><comune><nomeComune>ALAGNA VALSESIA</nomeComune><codiceIstat>002002</codiceIstat><siglaProvinciaIstat>VC</siglaProvinciaIstat></comune></luogoEvento><attoEvento><comuneRegistrazione><nomeComune>ALAGNA VALSESIA</nomeComune><codiceIstat>002002</codiceIstat><siglaProvinciaIstat>VC</siglaProvinciaIstat></comuneRegistrazione><anno>2017</anno><parte>1</parte><serie>A</serie><numeroAtto>1</numeroAtto><trascritto>0</trascritto></attoEvento></datiEvento>

La data evento non risulta registrata in  ANPR e i dati evento non vengono visualizzati.
L'operazione pero' va a buon fine.

**Comment by gcarbonin** [comment]
I dati sono stati acquisiti. stiamo verificando la consultazione

**Comment by asqueglia** [comment]
E' possibile riprovare . Grazie
