### ISSUE TITLE
Variazione di immigrazione cittadino Cancellato per Irreperibilità da altro comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3170]
COMUNE DI PANTIGLITE
Rif. Nadia Ferrari

Buongiorno
vorrei sapere come dobbiamo procedere per poter iscrivere nel nostro comune un cittadino cancellato per irreperibilità da un altro comune.

Grazie

**Comment by frmariani** [comment]
Dovete iscrivere il cittadino con le consuete modalità avendo l'accortezza di indicare l'idanpr precedentemente assegnato al cittadino dal sistema ANPR

**Comment by GabriellaBallabio** [comment]
Buongiorno 
in realtà il cittadino è stato cancellato per irreperibilità da un comune primo del suo subentro in ANPR, quindi il cittadino non è presente in ANPR.
Stiamo cercando di fare una variazione di iscrizione "per altri motivi" ma non sappiamo cosa mettere nelle informazioni relative al comune di provenienza.

Potete esserci d'aiuto ?

Grazie

**Comment by frmariani** [comment]
in caso di motivo di iscrizione "Ricomparsa (da irreperibilità)", la provenienza non è un dato obbligatorio.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
