### ISSUE TITLE
Configurazione informazioni aggiuntive webapp

### ISSUE THREAD

**Issue by MMaurizio** [italia/anpr#3171]
Buongiorno, Comune di Calceranica al Lago,

Nell'aggiornare  le informazioni generali nella webapp anpr relativamente alla ricezione per mail delle notifiche di rettifica dati comunicati dal cittadino non è possibile salvare le informazioni inserite (mail e modalità di ricezione) in quanto mancante la scheda delle informazioni aggiuntive di almeno un indirizzo ip.

Si chiede se l'ip da inserire sia l'indirizzo pubblico verificabile tramite il portale mio-IP.it.

Si coglie l'occasione per inviare i cordiali saluti e ringraziare dell'assistenza.

MMaurizio

![richiesta ip](https://user-images.githubusercontent.com/44244713/155691093-84d2c04d-ad1d-4e38-9d8a-aa21e766bf46.JPG)

**Comment by Leonforte** [comment]
Salve, 
la sezione della funzionalità “Gestione dati del comune” presente nell’area Amministrazione, di cui avete presentato la schermata, deve essere compilata solo nell’eventualità della presenza presso il comune di un servizio web di ricezione delle notifiche relative a: 
-        variazioni anagrafiche effettuate dal comune utilizzando la web app di ANPR;
-        notifiche di emigrazione in altro comune ed eventuale ripristino posizione anagrafica.

L’abilitazione alla ricezione delle mail delle richieste inviate dal cittadino attraverso il portale dedicato, si effettua compilando l’ultima sezione della funzionalità “Gestione dati del comune”, di seguito indicata:


 
![immagine](https://user-images.githubusercontent.com/26482932/156040331-694f75a5-cfc4-46a8-a3ee-7e2bd3160725.png)

**Comment by MMaurizio** [comment]
Sta di fatto che modificando la configurazione della notifica richieste inviate dal cittadino il sistema non consente il salvataggio della configurazione perché mancante di un indirizzo IP nella sezione informazioni aggiuntive.

**Comment by cmigliardi** [comment]
controlleremo . per ora può tranquillamente riportare l' ip  che già usate per il colloquio con  i servizi verso Anpr

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
