### ISSUE TITLE
Non e possibile accedere (PHLMTN85C)

### ISSUE THREAD

**Issue by Bellevue85** [italia/anpr#3172]
Non riesco ad accedere al sito.  Puoi aiutare? 

 il mio codice fiscale PHLMTN85C....

sono andato al mio comune locale (dove risiedo) ma non sono stati d'aiuto.

![Screenshot_2022-02-25-11-54-09-696_com android chrome](https://user-images.githubusercontent.com/100414977/155705442-a7461678-4220-48b7-8365-a7c298858457.jpg)

**Comment by cmigliardi** [comment]
gentile Sig Phelan  le consiglio di rivolgersi al suo comune di competenza - a noi risulta Roma -  e di far controllare la scheda in Anpr se è presente  -  - per accedere  occorre che la scheda sia presente e che il codice fiscale sia validato  -

**Comment by cmigliardi** [comment]
la issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
