### ISSUE TITLE
Application is not available - errore accesso tramite SPID

### ISSUE THREAD

**Issue by xojoc** [italia/anpr#3173]
Buongiorno,
partendo da https://www.anagrafenazionale.interno.it/ ho selezionato "Accedi ai Servizi al Cittadino". Ho scelto l'opzione SPID come login e Poste come provider. Dopo l'autorizzazione vengo reindirizzato a https://sc.anpr.interno.it/serviziCittadino/home, che però mi da il seguente errore:

![errore anpr](https://user-images.githubusercontent.com/10280969/155714617-d7f535e4-18fd-4148-a99d-009cafc14d2c.png)

Sto sbagliando qualcosa?

Grazie

**Comment by cmigliardi** [comment]
se cortesemente ci può dare le prime 6 lettere del codice fiscale . cerchiamo di capire il motivo  - grazie

**Comment by LSPAG** [comment]
Buonasera, anche noi abbiamo lo stesso problema con entrambi i cf di test. Di seguito le prime 6 lettere dei due cf:
NRXPLA
RXSNTN

**Comment by GitGium** [comment]
Buonasera,

stesso errore qui:
MCHGRM
MCHBSL

**Comment by cmigliardi** [comment]
scusate ma vi riferite ai cf  per i test o siete cittadini?

**Comment by LSPAG** [comment]
Test, ci scusi...

**Comment by GitGium** [comment]
Cittadini*

*ho appena notato di aver inserito un typo sul primo CF, li riporto qui:
MCHGMR
MCHBSL

**Comment by cmigliardi** [comment]
allora  cortesemente  scrivetelo nelle richieste  - giro al collega

**Comment by xojoc** [comment]
Cittadino straniero, prime 6 cifre CF: CJCLND

**Comment by cmigliardi** [comment]
gentile sig. COJOCARU le consigliamo di verificare con il comune di competenza Roma - la situazione della sua scheda anagrafica 
 suggerisco  di controllare i dati anagrafici visto che lei ha 2 nomi

**Comment by Domy81** [comment]
Stesso errore anche a me, accesso con SPID PosteID già avvenuto in passato (poco dopo l'attivazione del servizio) senza problemi.
Cittadino italiano, prime 6 cifre cod.fisc.
CSNDNC

**Comment by afxgroup** [comment]
idem qui.. 
PLMNDR.. ma dubito che centri il codice fiscale..

**Comment by Domy81** [comment]
Sì infatti, poco fa ho trovato su forum.italia.it che segnalano esserci un problema alla piattaforma!

**Comment by maintux** [comment]
Stesso errore, probabilmente non è legato alla singola utenza. Ad ogni modo le 6 lettere del mio codice fiscale `MNAMSM`

**Comment by Domy81** [comment]
Sì, già da ieri sera sul tardi si era sistemato! 👍

**Comment by xojoc** [comment]
Funziona, grazie

**Comment by cmigliardi** [comment]
grazie per il riscontro.
