### ISSUE TITLE
Application is not available

### ISSUE THREAD

**Issue by dany81091** [italia/anpr#3174]
Salve,
provando ad accedere ai "Servizi al Cittadino" tramite SPID dopo l'autenticazione vengo rediretto alla seguente pagina di errore:

![image](https://user-images.githubusercontent.com/100428534/155741204-44f2615c-9501-4e32-849c-abc0ae033d3a.png)

Rimango in attesa di un cortese riscontro.

Grazie

**Comment by FilippoPapi** [comment]
buonasera vi confermo che c'è un problema nel sistema.
stiamo lavorando per ripristinare il sito
