### ISSUE TITLE
Certificati mancanti nella sezione richiedi un certificato del portale ANPR

### ISSUE THREAD

**Issue by Giorgio1990** [italia/anpr#3176]
Buonasera,

ho trovato navigando online questo luogo in cui segnalare un problema che sto riscontrando per generare dal sito ANPR e del comune di Milano il certificato di cittadinanza. Mi scuso in anticipo se non è il luogo adatto poiché sono un privato cittadino 

(Codice identificativo ANPR: 68061991)

non riesco a richiedere il certificato di cittadinanza tramite il servizio online del comune di Milano e il sito ANPR a causa del seguente errore che visualizzo nel sito del comune di Milano "Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato". Nel portale ANPR invece posso scaricare solo il certificato di residenza e di stato di famiglia. Penso che dipenda dal fatto che 4 mesi fa ho effettuato la variazione della residenza portandola nel comune di Milano. Un anno fa ho scaricato lo stesso certificato dal sito del mio comune di provenienza.
Ho urgenza di ottenere tale documento in quanto è stato richiesto dal datore di lavoro come documento necessario per l'assunzione.
Il call center del comune di Milano non riesce a gestire il problema e mi ha invitato a recarmi fisicamente all'anagrafe. Purtroppo al momento sono fuori Milano e, vista l'urgenza, vi chiedo il favore di aiutarmi se possibile a sbloccare la situazione presso il comune o sul portale anpr.

Rimango in attesa di un vostro gentile riscontro.

Grazie,

Cordiali saluti

**Comment by meryblu89** [comment]
Buongiorno,
anche io ho il medesimo problema. Il Comune contattato mi ha riferito di non poter intervenire.
Grazie

**Comment by Giorgio1990** [comment]
> Buongiorno, anche io ho il medesimo problema. Il Comune contattato mi ha riferito di non poter intervenire. Grazie

Buongiorno,

come è possibile che il comune non può intervenire? a chi dobbiamo rivolgerci?

**Comment by cmigliardi** [comment]
buongiorno, cortesemente mi può fornire le prime 6 lettere del codice fiscale ?  così possiamo controllare . grazie 
in ogni caso il comune di competenza ha piena operatività sulla scheda per sanarla.

**Comment by meryblu89** [comment]
> buongiorno, cortesemente mi può fornire le prime 6 lettere del codice fiscale ? così possiamo controllare . grazie in ogni caso il comune di competenza ha piena operatività sulla scheda per sanarla.

Buongiorno, 
CPTMRA

**Comment by Giorgio1990** [comment]
> buongiorno, cortesemente mi può fornire le prime 6 lettere del codice fiscale ? così possiamo controllare . grazie in ogni caso il comune di competenza ha piena operatività sulla scheda per sanarla.

Buongiorno, grazie per la risposta. Le prime 6 lettere del codice fiscale sono PDRGRG
Codice identificativo ANPR: 68061991

Rimango in attesa di un vostro gentile riscontro.

**Comment by cmigliardi** [comment]
gentile Signora il comune  Darfo Boario Terme deve controllare la scheda in ANPR e verificare il dato:  certificabilità e assegnare un valore corretto a seconda della sua situazione

**Comment by Giorgio1990** [comment]
Buongiorno @cmigliardi,

gentilmente può verificare anche il mio CF?

grazie

**Comment by cmigliardi** [comment]
gentile Padrut nel suo caso invece c'è un procedimento aperto da parte del comune di Milano -  la invito a rivolgersi al comune

**Comment by cmigliardi** [comment]
gentile giorgio 1990 .   se mi invia e prime 6 lettere del codice fiscale, controllo  - grazie

**Comment by Giorgio1990** [comment]
@cmigliardi il Codice fiscale: PDRGRG

non potete intercedere voi con il comune? entrare in contatto con il comune di Milano risulta molto complesso.
Mi scuso per l'insistenza

**Comment by cmigliardi** [comment]
no mi spiace noi non possiamo intervenire -  non siamo autorizzati.   - se il comune ci chiama ovvio forniamo assistenza

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
