### ISSUE TITLE
Errore EN527 iscrizione nascita Aire

### ISSUE THREAD

**Issue by averrando** [italia/anpr#3178]
Comune di Ventimiglia produzione,

tentando di effettuare una iscrizione per Nascita AIRE ID OPERAZIONE ANPR 800307299 otteniamo l'errore in oggetto EN527.
Non riusciamo a capire qual'è il dato che blocca l'iscrizione, potete aiutarci ?
Grazie

**Comment by frmariani** [comment]
Purtroppo Agenzia delle Entrate non accetta l'apostrofo inserito nella località di nascita 'S-GRAVENHAGE: sarebbe possibile eliminarlo ?

**Comment by averrando** [comment]
E' stato levato l'apostrofo dalla località di nascita, ma abbiamo sempre l'errore EN527 . IP operazione 809560847

**Comment by frmariani** [comment]
Naturalmente l'apostrofo deve essere eliminato anche nell'indirizzo

**Comment by averrando** [comment]
Si ora l'iscrizione è andata a buon fine, però è stato necessario rettificare l'indirizzo di residenza della famiglia che accoglie l'iscrizione già residente nel comune estero 'S-GRAVENHAGE eliminando appunto l'apostrofo

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
