### ISSUE TITLE
annullamento decesso - Errore Anpr Cod: 999 - Operazione non effettuabile -

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3179]
COMUNE DI MOLTEPULCIANO PRODUZIONE

Il comune di Montepulciano ha necessità di annullare il decesso al soggetto: 27287748 per poter integrare i suoi dati di matrimonio e divorzio.
Quando si prova ad annullare l'operazione viene riportato il seguente errore: 

```
1 Errore Anpr Cod: 999 - Operazione non effettuabile -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-02-28 12:07:10 , idOperazioneANPR 804207496 -
```

**Comment by frmariani** [comment]
sono state annullate moltissime operazioni sul cittadino ed è stata anche effettuata una revoca del matrimonio sul coniuge superstite dopo l'operazione del decesso.  Come mai oggi nasce l'esigenza di inserire di nuovo il matrimonio ? l'operazione di revoca non è annullabile pertanto l'annullamento dell'operazione di decesso in queste condizioni non risulta di facile soluzione.

**Comment by jonnyfx95** [comment]
Il comune ha effettuato una revoca dei dati di matrimonio in quanto i dati di divorzio erano sbagliati.
Era stato inserito sia l'atto di divorzio che la sentenza, facendo un rettifica l'operazione andava a buon fine, ma interrogando il soggetto i dati erano ancora presenti.

**Comment by frmariani** [comment]
Per annullare un'operazione non devono essere presenti operazioni successive sul cittadino o sui componenti della famiglia coinvolti nell'operazione e la revoca del matrimonio ha certamente coinvolto entrambi i coniugi.
Parliamo di operazioni effettuate nel 2018 ed annullate solo recentemente.
Mi scriva in privato e cercheremo di studiare una soluzione, ma le ribadisco che il problema non sarà di facile soluzione
frmariani@sogei.it

**Comment by frmariani** [comment]
la issue viene risolta con contatto diretto
