### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by elirac** [italia/anpr#3180]
Cercando di accedere a Servizi al Cittadino (ANPR) dopo aver accesso tramite lo SPID appare questo messaggio:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Il mio Comune è il Comune di Roma ed è in ANPR, quindi non capisco come risolvere il problema.
Prime 6 cifre del codice fiscale: RCCLBT 
Potete aiutarmi?
Grazie

**Comment by cmigliardi** [comment]
buongiorno dai controlli le consiglio di rivolgersi al comune di Roma per verificare che  la scheda sia presente in Anpr.

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
