### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio...

### ISSUE THREAD

**Issue by aherzen22** [italia/anpr#3181]
Salve,
sto cercando di accedere a Servizi al Cittadino (ANPR), dopo aver fatto accesso tramite lo SPID vedo questo messaggio:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Vivo nel il Comune di Roma che è entrato in ANPR.
Prime 6 cifre del codice fiscale: GRTNNA
Nata in URSS- Z135
Potreste aiutarmi?
Grazie

**Comment by cmigliardi** [comment]
gentile Signora chieda al suo comune di competenza Roma  di verificare la scheda in ANpr - occorre che il codice fiscale sia Validato  che la scheda non sia cancellata etc......

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
