### ISSUE TITLE
Errore in iscrizione AIRE Cittadini stessa famiglia

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3182]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Buongiorno
abbiamo commesso un errore durante la fase di iscrizione aire di 5 cittadini appartenenti alla stessa famiglia , di fatto è accaduto che sono stati iscritti all'AIRE con lo stesso identificativo famiglia di anagrafe locale ma con un identificativo scheda famiglia ANPR diverso per ciascuno.

Abbiamo provato a modificare id scheda famiglia ANPR, ma la WA ci dice che non possiamo omettere i dati della residenza in italia. NON SAPPIAMO COME FARE PER INDICARE TALI DATI.

Potete esserci d'aiuto ?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
potete indicare l'idsoggetto ANPR dei cittadini interessati per favore?

**Comment by GabriellaBallabio** [comment]
Buongiorno
di seguito l'idSoggetto ANPR dei cittadini :

191559886
191559887
191559889
191559888
191559885

Si resta in attesa di riscontro.
Grazie
Saluti
