### ISSUE TITLE
Errore immigrazione per ricomparsa da irreperibilità - famiglia di appartenenza del cittadino risulta incompleta

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3183]
COMUNE DI PANTIGLIATE
rif. Nadia Ferrari

Buongiorno
abbiamo inserito una varuiazione di rientro irreperibilità di una cittadina per la quale ora in ANPR viene visualizzato l'errore :

EN213 - Tipo errore/anomalia 3
La famiglia di appartenenza del cittadino risulta incompleta.

Potete aiutarci ?
Grazie

**Comment by frmariani** [comment]
Non avendo nessun riferimento né dell'operazione fallita né dell'identificativo anpr del soggetto o della famiglia, posso genericamente dirle che dovreste aver inserito l'ultimo componente della famiglia lasciando l'informazione di famiglia completa=NO.
Nel caso, seguite la seguente procedura:
dalla web app, servizi di registrazione, Tipo operazione: Mutazione Famiglia/convivenza, tipo mutazione : motivo famiglia/specie convivenza, Famiglia completa=SI

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
