### ISSUE TITLE
P000 info allegati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3186]
Buongiorno,
il cittadino in fase di apertura richiesta come fa ad indicare la tipologia dell'allegato (idTipologia)?
Gli unici campi a disposizione sono una descrizione e la scelta del file.

Grazie

**Comment by apaolacci** [comment]
Buongiorno,
sulla base dell'estensione del nome file scelto.

**Comment by SAlberto** [comment]
Ma le tipologie dell'allegato secondo tabella 52 sarebbero le seguenti:
- 1 Documento d'identificazione del soggetto
- 2 Modulo di domanda compilato
- 3 Dichiarazione del soggetto
- 99 Stato non censito nell'elenco

e da ultima release (#3185 ) anche "Permesso di soggiorno"

ad oggi mi arriva sempre 99, come fate in base all'estensione a capire la tipologia?

**Comment by SAlberto** [comment]
Ecco il tracciato di esempio:
```
			<allegati>
				<allegato>
					<idTipologia>99</idTipologia>
					<nomeFile>alleUnoProva.png</nomeFile>
					<idFormatoFile>1</idFormatoFile>
					<descrizione>provaAllgato</descrizione>
					<contenuto>iVBORw0KGgoAAAANSUhEUgAAAUQAAAFDCAIAAADNjeApAAAAAXNSR0IArs4c6...</contenuto>
				</allegato>
			</allegati>
```

Comunque volevo solo capire come il cittadino potesse indicare se il suo allegato era un "Documento d'identificazione del soggetto" pittosto che un "Modulo di domanda compilato" piuttosto che ecc...  Dal portale nella sezione Allegati non ha nulla per definirlo.

Non credo sia possibile per voi tramite l'estensione dedurre la tipologia.

**Comment by apaolacci** [comment]
OK, non avevo capito il primo messaggio! 

La tipologia di file allegato non è indicabile dal cittadino ma è l'area autenticata sulla base della funzionalità a richiedere un tipo ben preciso di allegato.

In riferimento alla funzionalità di Cambio Residenza è obbligatorio fare l'upload del "Permesso di Soggiorno" _<idTipologia>4</idTipologia>_ solo se nella pratica sono presenti cittadini "Extra UE" (come richiedente oppure come soggetto coinvolto nel cambio che appartiene alla sua famiglia). Mentre se non richiesti esplicitamente dall'area autenticata nel pannello "Allegati" come obbligatori per inviare la dichiarazione ma caricati dal cittadino in autonomia, saranno di tipologia 99 - Stato non censito nell'elenco.

**Comment by SAlberto** [comment]
Perfetto, chiaro grazie molte
