### ISSUE TITLE
Errore non gestito - stato di famiglia

### ISSUE THREAD

**Issue by slor21** [italia/anpr#3187]
Buongiorno,
nella giornata di ieri ho riscontrato un particolare problema sul vostro portale.
Ho provato ad accedere con SPID per scaricare il certificato dello stato di famiglia (richiestomi da una banca per la domanda di mutuo) e nell'elenco della possibile documentazione che posso richiedere ho riscontrato l'assenza del suddetto certificato.
Stesso discorso accedendo con le credenziali di mia madre, che è l'unica appartenente al mio stato di famiglia.
Ho provato a contattare il comune, il municipio, il numero verde 800-863-116 ma si è entrati in un loop in cui ognuno ha demandato responsabilità ad un altro ente.
Per il momento sono riuscita ad ottenere l'autocertificazione, in cui stranamente invece risulta il mio stato di famiglia, ma temo che per la banca non sia sufficiente.
![ANPR_errore_non_gestito](https://user-images.githubusercontent.com/100769062/156354584-40268af0-2a0d-4414-a5d2-6c8542e254f5.png)

Spero possiate aiutarmi a capire come risolvere il problema.
Sara

**Comment by mttfranci** [comment]
Buongiorno, sarebbe possibile avere il suo "Codice identificativo ANPR" disponibile nell'area "Visura e autocertificazione", sezione generalità? (Si tratta di un dato senza particolari criticità di privacy ma che ci aiuterebbe nell'indagine).
Grazie in anticipo.
Saluti

**Comment by slor21** [comment]
Buongiorno a lei.
Certo, il mio identificativo ANPR è il seguente: 102841784
Grazie!

**Comment by slor21** [comment]
In ogni caso 3 giorni fa ho richiesto una rettifica dei dati, dal momento che mia madre (nell'autocertificazione) compare ancora come "marito/moglie" e non come "padre/madre".
A mio avviso il problema si è creato nel momento in cui i miei genitori si sono separati (a Luglio 2021) per cui l'uscita dallo stato di famiglia di uno dei membri alla radice ha causato l'effetto a cascata di errori per me e mia madre, che penso risulti ancora "agganciata" nello status a mio padre, il cui stato di famiglia (post cambio di residenza) è invece correttamente scaricabile.
Non so se questa informazione possa essere d'aiuto e spero di essere stata sufficientemente chiara nell'esporla.
Grazie,
Sara

**Comment by mttfranci** [comment]
Salve, sembrerebbe che nella sua famiglia i rapporti di parentela non sia impostati correttamente.
In particolare ci sembra che manchi l'intestatario della famiglia, che è necessario a emettere il certificato a lei necessario.
Può verificare se il dato non compare anche nell'area "visura e autocertificazione".

Qualora non sia presente un intestario della famiglia, dovrebbe chiedere al comune di impostare nuovamente le relazioni di parentela in modo corretto.

(Ad esempio, se la famiglia anagrafica è composta solo da lei e sua madre, lei potrebbe essere l'intestatario e sua madre, "Padre / Madre").

Saluti

Assistenza ANPR

**Comment by slor21** [comment]
Immaginavo dipendesse da questo fatto.
Quindi lei mi conferma che tale rettifica è di competenza del comune?
Perché ho provato appunto a fare una richiesta di rettifica direttamente dal sito dell'anagrafe nazionale, quindi non so se è sufficiente questo intervento o se comunque generalmente i tempi di attesa di presa in carico delle richieste sono molto lunghi.

**Comment by mttfranci** [comment]
Ok, in sostanza lei ha inserito la richiesta 27329327 con cui chiede che sua madre diventi la nuova intestataria? Corretto?
La richiesta online dovrebbe essere sufficiente a sanare la situazione.
Però la decisione è a carico del comune, non siamo in grado di garantire quando il comune prenderà in carico ed elaborerà la sua richiesta.
La funzione di rettifica in sostanza invia la richiesta direttamente al comune.
Saluti

Assistenza ANPR

**Comment by slor21** [comment]
Si esattamente.
Ok, la ringrazio per il supporto, è stato chiaro.
Le auguro una buona giornata,
Sara
