### ISSUE TITLE
errore di accesso anpr tramite spid

### ISSUE THREAD

**Issue by Ronaldoximenes81** [italia/anpr#3188]
Sono lontano in Brasile. 

 Ho una registrazione Aire, che include il codice fiscale. Ho lo spid e accedo a tutti gli organi di cui ho bisogno. tuttavia, quando si accede ad anpr dopo la certificazione, si verifica un errore:

 "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

 il mio comune è gentilissimo e ok la scheda.
 il mio codice fiscale è XMNRLD...

Ho letto che il Comune di Milano ha rilasciato. lì per prenderne alcuni, ma non tutti.

Grazie

**Comment by Ronaldoximenes81** [comment]
in contatto con il mio comune, dicono che la scheda è corretta.  il codice fiscale è stato verificato in AE.  Ma purtroppo non sanno come guidare.

**Comment by Ronaldoximenes81** [comment]
@mttfranci Mi potete aiutare?  è urgente per l'iscrizione al corso

**Comment by cmigliardi** [comment]
buongiorno   il suo comune di competenza è Milano - chieda di controllare la scheda in Anpr . in particolare che il codice fiscale sia stato validato e la scheda marcata da ag entrate  -  noi non possiamo agire-  ne ha facoltà  solo l'ufficiale di anagrafe  -

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by Ronaldoximenes81** [comment]
@cmigliardi no sei Milano. una città di 3.000 abitanti che non sa come aiutare

**Comment by cmigliardi** [comment]
mi spiace ma   il suo comune di competenza è Milano - chieda di controllare la scheda in Anpr . in particolare che il codice fiscale sia stato validato e la scheda marcata da ag entrate - noi non possiamo agire- ne ha facoltà solo l'ufficiale di anagrafe -

**Comment by Ronaldoximenes81** [comment]
No sei Milano. Buonabitacolo

**Comment by Ronaldoximenes81** [comment]
@cmigliardi tramite il sito web milao sono riuscito a ottenere alcuni certificati anpr

**Comment by cmigliardi** [comment]
un conto è il portale del comune . un conto è il portale del Ministero dell'Interno

**Comment by Ronaldoximenes81** [comment]
@cmigliardi si, a milano si. Grazie per l'aiuto.  nel comune dicono che va tutto bene

**Comment by cmigliardi** [comment]
mi permetto di insistere . va vista la scheda in  Anagrafe nazionale . chieda di controllare la scheda in Anpr . in particolare che il codice fiscale sia stato validato e la scheda marcata da ag entrate - noi non possiamo agire- ne ha facoltà solo l'ufficiale di anagrafe -

**Comment by Ronaldoximenes81** [comment]
@cmigliardi grazie
