### ISSUE TITLE
WS P000 - 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3189]
Buonasera,
E' previsto l'invio delle notifiche P000 su endpoint comune?

- dopo le ultime modifiche (wsd-wsdl 5.15.3) P002 non riesco più a inviare request (cerca classe boucycasteprovider) potete darmi qualche aiuto?
Grazie

**Comment by rinonasti** [comment]
classe boucycastleprovider

**Comment by apaolacci** [comment]
Buonasera,
xsd/wsdl sono stati modificati con nuovi element e sono stati modificati alcuni tipi associati a element in output (operation P002). L'operation P003 è stata modificata con un nuovo element opzionale in input. 

Il client andrà sicuramente rigenerato/adeguato. 

Puoi condividere la request che stai inviando?  
Grazie

**Comment by rinonasti** [comment]
eccola
[20220000001_P002_061022.zip](https://github.com/italia/anpr/files/8180184/20220000001_P002_061022.zip)

**Comment by rinonasti** [comment]
potrei sapere quali sono gli elementi modificati?
Grazie

**Comment by rinonasti** [comment]
AGGIORNAMENTO: RISOLTO PROBLEMA INVIO
allego il risultato dove si evince che il secondo allegato non è conforme a base64 mentre il primo si ed è perfettamente decodificabile
ALLEGATI
Dati inviati
Dati ricevuti (xml)
allegati estratti base64 (primo ok secondo NO

Grazie
[dati_inviati.zip](https://github.com/italia/anpr/files/8186083/dati_inviati.zip)
[dati_ricevuti.zip](https://github.com/italia/anpr/files/8186084/dati_ricevuti.zip)
[primoallegato.zip](https://github.com/italia/anpr/files/8186085/primoallegato.zip)
[secondoallegaot.zip](https://github.com/italia/anpr/files/8186086/secondoallegaot.zip)

**Comment by apaolacci** [comment]
Buongiorno,
abbiamo apportato una modifica, ora sia il riepilogo pratica (pdf) sia gli eventuali allegati alla pratica sono restituiti in base64. 
E' possibile riprovare il test? 
Grazie

**Comment by rinonasti** [comment]
provato ma sono ritornati all'origine ovvero %PDF-1.4%......
dovrebbero essere entrambi (o tutti gli allegato come primoallegato
Grazie

**Comment by apaolacci** [comment]
Ciao,
nella risposta P002 vediamo entrambi i file in formato base64:
```
...
<riepilogoRichiesta>
	<idFormatoFile>1</idFormatoFile>
	<contenuto>JVBERi0xLjQKJaqrrK0KM....</contenuto>
</riepilogoRichiesta>
<allegati>
	<allegato>
		<idTipologia>99</idTipologia>
		<nomeFile>response (3).pdf</nomeFile>
		<idFormatoFile>1</idFormatoFile>
		<descrizione>contratto affito</descrizione>
		<contenuto>JVBERi0xLjQKJeLjz9MKMSA....</contenuto>
	</allegato>
...	
``` 
che se decodificati attraverso tool online di esempio: [https://base64.guru/converter/decode/pdf](https://base64.guru/converter/decode/pdf)
permette di ottenere i due file originari formato pdf.

Sul codice del client basta applicare la decodifica base64 e salvare l'output su file con relativa estensione/formato.

La response XML recuperata dai log è:
[response_2022P002P2014.log](https://github.com/italia/anpr/files/8198003/response_2022P002P2014.log)

**Comment by rinonasti** [comment]
io trovo questo.
prima della modifica il primo allegato era corretto il secondo no
adesso sono entrambi stesso formato
[risposta.zip](https://github.com/italia/anpr/files/8198514/risposta.zip)

**Comment by apaolacci** [comment]
La response P002 del servizio di dettaglio della pratica 1230093 è nel messaggio precedente. 
Prenda le due stringhe nel tag _contenuto_ del riepilogo e dell'allegato, provi a fare la decode base64 e salvi con estensione _.pdf_ o lo visualizzi direttamente online su https://base64.guru/converter/decode/pdf, vedrà che ora è corretto il comportamento.

**Comment by rinonasti** [comment]
continuo a vedere quello di risposta (allegato precedente)
se prendo quello che mi ha allegato in response_2022P0022014 e' corretto
La risposta che ottengo é
[risposta_2020.zip](https://github.com/italia/anpr/files/8199259/risposta_2020.zip)

Ripeto prima della modifica il riepilogo era OK allegato NO

**Comment by apaolacci** [comment]
Prova a verificare il client che invoca i ws non faccia qualche azione di codifica/decodifica impostata di default.
Ad esempio soapUI utilizza l'elaborazione MTOM/XOP sul messaggio soap ricevuto generando i tag 
```
<contenuto>
	<xop:Include href="cid:c2f767a2dd330f1......@apache.org" xmlns:xop="http://www.w3.org/2004/08/xop/include"/>
</contenuto>
```
presenti nel tuo file di risposta che è molto diverso dalla risposta del WS che noi ti inviamo e che ho recuperato dal log di output di anpr:
[response_2022P002P2014.log](https://github.com/italia/anpr/files/8199446/response_2022P002P2014.log)

**Comment by rinonasti** [comment]
Questo è la risposta che ottengo
[dati_ricevuti.zip](https://github.com/italia/anpr/files/8199553/dati_ricevuti.zip)
Sto utilizzando ANPR_Client opportunamente aggiornato e modificato.  Dove potrebbe effettuare quello che mi hai indicato?
Grazie

**Comment by rinonasti** [comment]
**Non riesco a capire perché prima della modifica il riepilogo era OK allegato NO.**

**Comment by rinonasti** [comment]
Buongiorno, segnalo che stamane non funziona più P001 (funzionante fino alla ultima modifica). 
**Internal Error (from client)**
Grazie

**Comment by rinonasti** [comment]
Buonasera, risolto segnalazione precedente P001
**Rimane il problema allegati P002**
Grazie 
**E' previsto l'invio delle notifiche P000 su endpoint comune? sarebbe molto comodo**

**Comment by apaolacci** [comment]
Buongiorno,
per i P000 non è previsto invio di notifiche sull'endpoint del comune. Segnaliamo il tuo suggerimento a dipartimento/ministero.
Per la segnalazione sugli allegati, altri (vedi #3200) sono riusciti a gestirli correttamente escludiamo problemi.

**Comment by rinonasti** [comment]
Ok Grazie
**COMUNQUE PRIMA VEDEVO ALLEGATI CORRETTAMENTE CODIFICATI base64 NON PIU'.**
**NON SO COSA SIA CAMBIATO!!**

**Comment by apaolacci** [comment]
E' cambiata la gestione con il rilascio (vedi lista interventi #3185) della versione 5.5.13 la gestione dei file è stata corretta. Prima codificavamo in base64 due volte il contenuto del file, recuperato da DB e già codificato, quindi probabilmente era un caso che parzialmente funzionava.

**Comment by rinonasti** [comment]
OK comunque io il test l'ho fatto dopo 5.5.13
Grazie

**Comment by rinonasti** [comment]
allego le risposte prima (primoallegato - secondo allegato) e dopo (primoallegato(1) - secondoallegato(1)
[Uploading Dati.zip…]()

**Comment by rinonasti** [comment]
[Dati.zip](https://github.com/italia/anpr/files/8222126/Dati.zip)

**Comment by rinonasti** [comment]
<idOperazioneANPR>48847852</idOperazioneANPR>
gli allegati sono sempre nella forma che vedi in primoallegato1-  secondoallegato1 e non base64 come primoallegato e secondoallegato
Grazie

**Comment by rinonasti** [comment]
non sono decifrabili

**Comment by apaolacci** [comment]
con idOperazioneComune = 48847852 non troviamo input/output che possiamo fornirti.
L'unica cosa che puoi controllare è controllare come il client invoca e cosa riceve, se quando consuma il webservice P002 ottiene i file come encoding MTOM in un element include XOP.

**Comment by rinonasti** [comment]
Ok, sorry,  la idoperazionecomune è 2022P002P2033 ti allego dati_inviati.xml / dati_ricevuti.xml e il log completo.
Se mi dai qualche dritta ti sono grato.
Grazie
[NEWREQUEST.zip](https://github.com/italia/anpr/files/8233308/NEWREQUEST.zip)

**Comment by apaolacci** [comment]
Nel frattempo in/out dell'invocazione:
[2022P002P2033.txt](https://github.com/italia/anpr/files/8233657/2022P002P2033.txt)

**Comment by rinonasti** [comment]
ok grazie questo é quello che dovrei ricevere **(ma non ricevo)**

**Comment by gppbarone** [comment]
La issue viene chiusa, in caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova facendo riferimento a questa.
