### ISSUE TITLE
Impossibile accedere ANPR

### ISSUE THREAD

**Issue by ADMRC** [italia/anpr#3190]
Buonasera, 

tentando di accedere visualizzo il messaggio di errore che allego.

Presso il mio comune di residenza dicono sia tutto nella norma.

Cosa potrei fare o a chi potrei rivolgermi per tentare di capire dove sta il problema?

Grazie

Saluti

![image](https://user-images.githubusercontent.com/100874446/156642607-2e0a0800-477e-4846-a7a8-336f9330be66.png)

**Comment by cmigliardi** [comment]
buongiorno cortesemente ci può inviare le prime 6 lettere  del suo codice fiscale ? così   verifichiamo grazie

**Comment by ADMRC** [comment]
Certamente. MGRNRD

**Comment by cmigliardi** [comment]
gentile signor Magrì   la invito a rivolgersi al suo comune di competenza Reggio calabria - per far verificare la sua scheda in ANPR -  ( es.   il codice  fiscale deve essere validato -   i dati anagrafici devono essere uguali in anpr e in ag entrate - )  vedo che lei nel cognome ha un accento .....  chieda   questi  controlli  - noi non possiamo operare -  ma solo fornire informazioni -  spero di esserle stata di ausilio.

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
