### ISSUE TITLE
Anpr non funziona Pomigliano

### ISSUE THREAD

**Issue by paoloand** [italia/anpr#3191]
Anpr non funziona sul comune di Pomigliano d'arco

**Comment by gife67** [comment]
Buongiorno,
prima di dire che ANPR non funziona, visto che sta correttamente funzionando con 7900 Comuni, magari mi porrei il dubbio che potreste avere voi dei problemi al vostro interno.... Quindi cortesemente forniteci dei dettagli su cosa state riscontrando dei problemi.... La Web Application? Il vostro gestionale? avete un problema con tutte le postazioni? vedo arrivare richieste dai vostri gestionali da varie postazioni e da vari operatori che vengono correttamente gestite senza errori, l'ultima alle 11:50 effettuata da MNFNLLxxxxxx dalla postazione 063057-PC-0001... Attendo vostri dettagli.... grazie

**Comment by gife67** [comment]
Buongiorno,
siccome non ho ricevuto più riscontri e vedo operatività da parte del Comune, provvedo a chiudere l'issue.
Nel caso aveste bisogno di ulteriore supporto potete aprire una nuova issue ed eventualmente collegarla a questa.
Codiali saluti e buon lavoro
