### ISSUE TITLE
Errore anpr

### ISSUE THREAD

**Issue by Androfayez31** [italia/anpr#3193]
Non riesco ad accedere ad anpr per scaricare dei certificati grazie 
![4A4ECC32-1B6E-4FBE-8CDA-267C94C202F2](https://user-images.githubusercontent.com/83766284/156939255-2e2ab3ad-2008-4be5-9da5-8b7ec8b84e42.jpeg)

**Comment by Androfayez31** [comment]
E sono nel comune di milano

**Comment by cmigliardi** [comment]
buonasera, cortesemente ci può  fornire le prime 6 lettere del suo codice fiscale ?  così  possiamo verificare. grazie

**Comment by Androfayez31** [comment]
Si certo prego ( RYDNRF)

**Comment by cmigliardi** [comment]
buongiorno 
allora la situazione è che in anpr  lei risiede in due comuni . a Rende e a Milano . dove risiede adesso ?    vada al suo comune attuale che si dovrà mettere in contatto con l'altro per cancellare una scheda  e lasciarne una sola attiva  .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
