### ISSUE TITLE
MODIFICHE BATCH A TOPONOMASTICA

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#3194]
Buongiorno.
Esiste la possibilita' di variare direttamente su ANPR e in modo massivo le denominazioni dei toponimi del territorio ? 
Questa necessita' scaturisce dall' input ricevuto dall' istat che ha dato molteplici indicazioni ai comuni circa massivi cambiamenti da apportare alle denominazioni delle vie piazze ecc. 
Esiste un alternativa alla comunicazione puntuale via flusso 5001 ? 
Esiste eventualmente  la possibilita' batch di updatare il db di ANPR semplicemente con modifiche sulla denominazione Toponmastica di pochissimo peso semantico ? 
Mi spiego : 
Esempio1 ( Cambio solo da minuscole a maiuscole):
Tutte le occorrenze di via Giuseppe Garibaldi devono semplicemente essere updatete = via GIUSEPPE GARIBALDI 
Eventalmente Esempio2 (Cambio di Denominazione senza ma senza peso semantico):
Tutte le occorrenze di via G. Verdi devono semplicemente essere updatate = via GIUSEPPE VERDI  

GRAZIE 
Edoardo Dona' 
DatamanagementItalia
x Comune di Ravenna

338 59 09 376

**Comment by amollicone1982** [comment]
C'e' solo il 5001 tipoMutazione 7 (REVISIONE ONOMASTICA STRADALE E DEI NUMERI CIVICI)
