### ISSUE TITLE
ISCRIZIONE DI CITTADINO GIA' CANCELLATO DA ANPR PER IRREPERIBILITA' IN ALTRO COMUNE

### ISSUE THREAD

**Issue by iolandacavallin** [italia/anpr#3195]
Dobbiamo iscrivere nell'anagrafe di Valsamoggia la persona con identificativo ANPR 87208757, già cancellata da ANPR per irreperibilità dal comune di Laterina Pergine Valdarno.
In fase di iscrizione preliminare compare il seguente messaggio:
TESTO DEL MESSAGGIO: Operazione ID ANPR = 812066084 , ID Locale = JD2203071120278952
Codice | Testo
EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune LATERINA PERGINE VALDARNO (AR) con numero pratica ANPR: 101056445
EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2022-03-07 11:20:11 , idOperazioneANPR 812066084
La collega del comune di cancellazione, da me contattata telefonicamente, è stata molto disponibile ma non riusciamo comunque a capire quale sia il problema, dal momento che la pratica di cancellazione per irreperibilità parrebbe definita.
Riuscireste a darci gentilmente qualche indicazione su quale sia l'ostacolo e come procedere?

**Comment by frmariani** [comment]
Esiste un procedimento amministrativo che deve essere chiuso; il numero del procedimento è indicato nel controllo (101056445).
Il comune di LATERINA PERGINE VALDARNO può utilizzare la web app per la chiusura del procedimento; nel caso fosse necessario, potete contattare l'assistenza ANPR al numero verde 800863116

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
