### ISSUE TITLE
Anomalia nei dati anagrafici e problemi di accesso a ANPR

### ISSUE THREAD

**Issue by GianlucaFabiani** [italia/anpr#3197]
Buongiorno, 
Venerdì ho riscontrato e corretto un'anomalia sul mio nome presso l'anagrafe del comune di Quarto (NA):
Il problema era che invece di scrivere GIAnluca, avevano scritto GAInluca.
Inoltre però ho riscontrato stamattina all'agenzia delle entrate che mi è stato associato anche un secondo codice fiscale, per un errore sul giorno di nascita 22 invece di 21, producendo due codici fiscali che sono stati unificati. Questo errore però non risulta al comune di Quarto (NA). 
Detto ciò continuo ad avere problemi di accesso al portale ANPR con messaggio:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Relativamente a ciò faccio presente che in comune hanno problemi a farmi la CIE.
Cosa devo fare? è possibile verificare la persistenza delle suddette anomalie o di altre eventuali?
prime 6 lettere del cf: FBNGLC
Grazie in anticipo

**Comment by cmigliardi** [comment]
buongiorno, 
in Anpr  c'è  la scheda  con  il codice fiscale relativo al  giorno di nascita   21 - ma il codice fiscale non è validato . quindi le consiglio di rivolgersi al suo comune   di QUARTO e di sanare  la situazione.

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
