### ISSUE TITLE
Info SCADENZA Richieste

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3198]
Buongiorno
abbiamo alcuni dubbi in merito alla gestione della data scadenza delle richiesta di rettifica/residenza.

Abbiamo visto che il sistema, per quanto riguarda le richieste di rettifica, imposta come data di scadenza il trentesimo giorno dall'apertura da parte del cittadino della stessa, mentre per quanto riguarda le richieste di cambio residenza, la data di scadenza viene impostata al secondo giorno successivo alla presentazione.
Avremmo quindi due domande:

- A quanti giorni dalla scadenza il sistema presenta una richiesta come "in scadenza"? Abbiamo verificato che una richiesta di cambio di residenza appena presentata (avendo come limite i due giorni) viene immediatamente messa in scadenza mentre non sappiamo dopo quanti giorni questo avvenga per le richieste di rettifica.
- Sempre in merito alle richieste di cambio residenza, abbiamo inoltre notato che anche Accogliendo con Riserva una richiesta la data di scadenza non viene variata, restando quella originale a due giorni dall'apertura della stessa. Ma il Comune, stando al regolamento anagrafico e alla mail che viene inviata al cittadino, dal momento della presa in carico ha a disposizione 45 giorni per fare i dovuti accertamenti sulla residenza e chiudere, positivamente o meno, la pratica di cambio residenza; è voluto che la data di scadenza della richiesta di cambio residenza non vari al momento della presa in carico da parte del Comune?

Grazie

**Comment by cmigliardi** [comment]
per i due servizi la norma è diversa.   nella guida operativa  pubblicata trovate tutti i possibili cambi di stato per ogni tipo. 
in breve  richiesta di rettifica :  il cittadino apre la  pratica.    il comune o la rende irricevibile o la prende in carico . inizia il vaglio .  ha facoltà  di dare preavviso di rigetto  e chiedere integrazione - ciò sospende la pratica  fino a integrazione del cittadino .  il cittadino ha  circa 10 gg dipende dal comune.    se non integra - il comune può rigettare . se integra riparte il vaglio -   poi il comune puo' sempre chiedere la proroga al max per 2 volte e ogni volta sono 30 gg.   quindi in sostanza c'è 
 tutto il  tempo  necessario.        diverso è  per la dichiarazione di cambio di residenza. il cittadino la invia e  il comune o la rende irricevibile o la  prende in carico . Ha 2 gg per fare il cambio di residenza  e lo stato diventa accolta con riserva quindi partono i 45 gg di accertamento.   se va tutto bene  alla fine si accoglie definitivamente . se invece  il comune ha necessità di altre info può dare preavviso di rigetto e sospende in attesa di integrazione.  se il cittadino integra il comune riprende  il vaglio e alla fine o  annulla il cambio di residenza e storna -  o la accoglie  in modo definitivo.   spero di aver risposto .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
