### ISSUE TITLE
Info SCADENZA Richieste V2

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3199]
Buongiorno,
in riferimento alla issue #3198: forse non avete compreso cosa stavamo chiedendo.
Ci è chiaro l'iter relativo alle richieste di residenza e rettifica.Quello che avevamo chiesto era altro: faccio un esempio.
Il cittadino crea una richiesta di rettifica oggi 07/03/2022. 
Il sistema ANPR imposta come data di scadenza della stessa la data del 06/04/2022. 
L'opeatore comunale vede questa richiesta dalla Home di ANPR nella sezione "Richieste di Rettifica" - "Aperte".
Quello che stavamo chiedendo è dopo quanti giorni questa richiesta, se ignorata dall'operatore, finirà nella sezione "In scadenza" sulla Home di ANPR

Stesso esempio, ma relativo alle pratiche di cambio residenza:
Il cittadino crea una richiesta di cambio di residenza oggi 07/03/2022. 
Il sistema ANPR imposta come data di scadenza della stessa la data del 09/03/2022. 
L'operatore comunale vede la richiesta dalla Home dalla sezione "Dichiarazioni di cambio residenza" - "Aperte" e nella sezione "Dichiarazioni di cambio residenza" - "In scadenza".
Relativamente alle richiesta di cambio residenza, una volta che l'operatore comunale gestisce la richiesta portandola prima "In lavorazione" e quindi in "Accolta con Riserva" ci aspettavamo che la data di scadenza variasse aggiungendo i 45 giorni previsti per gli accertamenti, ma abbiamo visto che invece rimane a proporre la data del 09/03/2022. E' giusto questo comportamento?

Grazie

**Comment by SAlberto** [comment]
_"qualche giorno prima dei 30 gg"_
E' possibile quantificare i giorni esatti?

_"in lavorazione non vuol dire accolta con riserva sono 2 stati diversi"_
Lo sappiamo, dopo essere stata "accolta con riserva" la data di scadenza non dovrebbe cambiare da 09/03/2022 a 11/05/2022 circa (9 marzo + 45 giorni) ?

**Comment by cmigliardi** [comment]
le faccio sapere

**Comment by cmigliardi** [comment]
A 5gg dalla data di scadenza la richiesta di Rettifica apparirà come “In Scadenza” (come risultato della analoga funzionalità di ricerca dalla home page). In questo periodo di 5gg, solo per la funzionalità rettifica dati, è prevista la possibilità di “proroga” della data scadenza.    E' giusto questo comportamento?  Si il monitoraggio delle pratiche di cambio residenza monitora solo la fase lavorazione che deve avvenire entro i 2gg.  

Nulla ha riguardato i successivi 45gg, non è stato ancora previsto nessun intervento da requisito ministeriale .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
