### ISSUE TITLE
WEB-APP - CONSULTAZIONE SCHEDA FAMIGLIA/CONVIVENZA

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#32]
Data test- 15/03/2017 - Ambiente test (dptest)
Prima di effettuare qualsiasi operazione su un soggetto, è fondamentale effettuare una consultazione della scheda individuale del soggetto e della scheda della sua famiglia.
Al momento la Consultazione della Scheda Individuale può essere effettuata tramite la ricerca con i dati del soggetto (ad es codice fiscale).
La Consultazione della Scheda Famiglia può essere effettuata solo  tramite "Identificativo scheda attribuito da ANPR" che deve essere "copiato" dall'utente dalla scheda individuale. 
Per ridurre i tempi e semplificare il lavoro dell'operatore sarebbe utile inserire nella consultazione scheda individuale un link diretto alla consultazione scheda famiglia del soggetto tramite la scheda Famiglia/ Convivenza.
Nel caso ciò non fosse fattibile, almeno prevedere la ricerca per dati del soggetto (ad esempio per codice fiscale )anche nella Consultazione Scheda Famiglia/Convivenza.
Grazie
Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Abbiamo aggiunto un link nel tab Famiglia/Convivenza che consente di ottenere l'elenco dei componenti. Attendo un suo riscontro

**Comment by annamariaGillone** [comment]
Molto bene, grazie! Domani verifico con le colleghe di anagrafe se i dati visualizzati siano sufficienti.

**Comment by annamariaGillone** [comment]
Le colleghe di anagrafe ritengono sia una ottima soluzione. Grazie

**Comment by gcarbonin** [comment]
Buon lavoro
