### ISSUE TITLE
Rettifica dati subentro

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#320]
Ambiente di test, WA. Rettifica id 7796284, operazione d'ufficio. Vorrei fare la rettifica dei dati subentro in quanto per un disguido in fase si preparazione file subentro, non è stato indicato il grado di parentela.
Quando mi presenta il pannello "Dati dell'operazione", appare l'errore:
_Sono da compilare i campi obbligatori della sezione Provenienza_
ma non vedo questa sezione "provenienza" a video. L'errore appare bloccante e non prosegue oltre.

**Comment by gcarbonin** [comment]
Può riprovare. Faccio presente che il grado di parentela non si modifica con questa funzione ma con il servizio 5001 tipo mutazione 2

**Comment by MarcoMigliori** [comment]
Nel tipo operazione su WA, è sparita la voce "Rettifiche" dalla combo.

**Comment by MarcoMigliori** [comment]
Ora nella WA è riapparsa la voce.
Provando, come lei mi aveva anticipato, verifico che la rettifica è consentita solo per pochissimi campi.
Non mi è chiaro e chiedo scusa in anticipo se già comunicato, se è prevista la funzione di rettifica di quasliasi dato. Rettifica che non crei un evento storico, e che quindi corregga i dati da certificare.  Esempio sbagliata la digitazione di una data, o magari ci si accorge a posteriori di un grado di parentela errato, ecc...

1. Segnalo invece credo come errore, che la rettifica dati subentro mi è consentita sull'id  6546211, che ho iscritto nel "mio comune" per variazione di residenza, ma che è subentrato in ANPR in precedenza da altro comune. La rettifica mi permette di modificare la data di residenza corrispondente al cambio nel mio comune, non al subentro.

2. La domanda implicita nell'osservazione precedente, è se il comune che ha subentrato l'id 6546211, potrebbe correggere i dati di subentro, anche in presenza di un cambio di residenza successivo.

3. E la rettifica mi è consentita anche sull'id 4362, che è residente in altro comune ANPR. Qui non vedo motivo di consentirla.

**Comment by MarcoMigliori** [comment]
Scusate, dimenticavo che la mutazione dati ha come attributo "rettifica" quindi dovrebbe essere già gestita questa parte:

> Rettifica che non crei un evento storico, e che quindi corregga i dati da certificare.

**Comment by gcarbonin** [comment]
E' possibile effettuare una mutazione specificando che si tratta di una rettifica. Questa mutazione "per rettifica" funziona esattamente come le altre: storicizza i dati; rimane visibile tra le operazioni eseguite sulla scheda.
Controlliamo le segnalazioni.

**Comment by gcarbonin** [comment]
Su questo soggetto non risultano rettifiche; anche 4362 è introvabile sia come persona che come operazione comune.

**Comment by MarcoMigliori** [comment]
3. ho erroneamente indicato l'id del comune di CASTEL SAN PIETRO TERME, mentre l'id anpr è 6335394. ho effettuato or ora una "rettifica dati subentro" indicando in "Data decorrenza residenza*:" al posto di 13-08-1934, la data 11-07-1944. sono arrivato sino al salva e chiudi, ricevendo l'errore "_Spiacenti al momento il servizio non è disponibile_" . immagino che in altro momento confermi l'operazione, nonostante sia in carico ad altro comune.

La operazione al punto 1 non l'avevo confermata in effetti. Ora non riprovo visto la segnalazione appena ricevuta.

**Comment by MarcoMigliori** [comment]
3. appena riprovato stesso test e id anpr qui sopra. non me lo fa registrare con messaggio "Rettifica non permessa in quanto la data di decorrenza residenza e' presente e congruente (Codice: EN414)". Non capisco se controlla che solo il comune di competenza possa aggiornare questi dati. sembra di no visto che mi fa arrivare sino al "salva e chiudi".

1. sempre id anpr 6546211. è un cittadino subentrato da altro comune, che ha trasferito la residenza nel "mio" il 30 agosto. vado in rettifica dati subentro, e mi mostra "data decorrenza residenza" 30 agosto. in effetti il campo è corretto, ma allora sono io che non capisco cosa significa "rettifica dati subentro", a meno che non si intenda una variazione possibile solo quando il comune è subentrato, prima di fare qualsiasi altra variazione di residenza. Sono partito pensando ci fosse un errore, ma forse è l'etichetta "rettifica dati subentro" che mi fa pensare a tutt'altro.

**Comment by gcarbonin** [comment]
"Rettifica dati subentro" significa che si modificano informazioni del subentro; l'unico comune che può farlo è quindi quello che ha in carico la scheda a partire dal subentro; se nel frattempo la persona si è trasferita in un altro comune, il "comune del subentro" non è più competente e quindi non può modificare nulla (come potrebbe farlo, considerando che la data mancante è quella di decorrenza di residenza del comune iniziale, dato che è soltanto sulla scheda cartacea in possesso del comune stesso?).
Al momento nell'ambito di "rettifica dati subentro" l'unico dato rettificabile è la data di decorrenza della residenza quando è assente o minore della data di prima iscrizione nel comune (capita quando il gestionale per i dati mancanti memorizza una data fittizia come 01-01-1900).
Se prima di effettuare questa correzione il comune competente (quello al momento del subentro) modifica la residenza, la variazione viene bloccata in quanto la precedente residenza diventa un dato storico che, come ormai dovrebbe essere noto, non si cambia.

**Comment by MarcoMigliori** [comment]
Ok, è un test che non ho fatto volontariamente ma per caso: non avendo bene capito la problematica ho richiamato l'ultimo nome variato in ANPR, senza pensare che era stato subentrato da altro comune . E da lì mi sono chiesto cosa succedeva se qualcuno sbagliando lo utilizzava. A me apparentemente sembra che non ci sia nessun controllo sul fatto che il cittadino sia stato subentrato da altro comune. Ma forse funziona lo stesso, perchè il cittadino che stavo utilizzando non rientra in questa casistica:

_l'unico dato rettificabile è la data di decorrenza della residenza quando è assente o minore della data di prima iscrizione nel comune_
