### ISSUE TITLE
[ws P002] Dettagli Richieste - Allegati: Formato File

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3200]
buongiorno.

il portale cittadino permette di caricare allegati nei formati PDF, JPG e PNG.

indipendentemente dal formato del file (abbiamo provato sia con PDF che JPG), all'interno del gruppo di dati "allegato", l'idFormatoFile è sempre '1' (che da tabella 51 riporta alla decodifica "Formato standard Adobe (Portable Format Document)").

mi sarei aspettato un idFormatoFile diverso (da censire poi in tabella 51)

allo stato attuale riconosciamo il formato del file dall'estensione del file contenuta nel tag "nomeFile".
mi interessava capire se è corretto così o se sono previste evoluzioni.

grazie
Alessandro Monopoli ADS

**Comment by apaolacci** [comment]
Buongiorno,
abbiamo sanato la situazione sulla tabella allegati. Ora l'_idFormatoFile_ è stato corretto rispetto al formato file caricato. 
Il riconosciamo del formato del file può essere fatto dal valore del tag _nomeFile_, ma adesso anche dalla decodifica presente in tabella 51. La tabella 51 sarà aggiornata con il rilascio in ambiente di produzione e sulla issues #3185 che anticipava il rilascio in test-comuni.

Puoi invocare nuovamente e verificare se tutto funziona?

Riesci a decodificare e scaricare correttamente gli allegati relativi alla pratica?

Grazie

**Comment by AMonopoliADS** [comment]
grazie del riscontro Antonio.

ho appena provato sia con una pratica pre-esistente, sia con una nuova pratica ed il campo idFormatoFile viene differenziato in base all'estensione.
da quello che vedo mi risulta:
1 - PDF
2 - PNG
3 - JPG

riguardo alla tua domanda:
"_Riesci a decodificare e scaricare correttamente gli allegati relativi alla pratica?_"
ti confermo che leggo ed interpreto correttamente sia il riepilogo della richiesta che gli allegati.

grazie.
Alessandro
