### ISSUE TITLE
ANPR - certificati mancanti

### ISSUE THREAD

**Issue by Itoira** [italia/anpr#3201]
Buongiorno, 
nell'elenco dei certificati da richiedere MANCA il certificato di stato di famiglia. Altri utenti mi sembra che lo abbiano. Io no.
Saluti

**Comment by cmigliardi** [comment]
per favore ci può dare le prime 6 lettere del codice fiscale ? per poter controllare la scheda ?  dove risiede ?  grazie  per la collaborazione

**Comment by Itoira** [comment]
RTBMCL

Residenza: 06073 CORCIANO (PG)

Il giorno mar 8 mar 2022 alle ore 10:17 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
buongiorno, abbiamo controllato la scheda e la invito a rivolgersi al comune perché nella composizione della famiglia è assente l'intestatario della famiglia stessa .  il comune quando ha passato i dati  in ANPR ha infatti avuto una segnalazione del tipo:  Relazioni di parentela incongruenti per la famiglia, verificarle prima di emettere certificati di stato di famiglia -  ma evidentemente non l'ha sanata -   spero di esserle stata di ausilio --

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
