### ISSUE TITLE
Rilascio CIE a cittadino pakistano con solo cognome

### ISSUE THREAD

**Issue by mmaglioni** [italia/anpr#3202]
Comune di Prato Produzione

Abbiamo un cittadino pakistano inserito con solo il cognome, con il codice fiscale allineato in Agenzia delle Entrate per il quale non riusciamo a rilasciare la carta di identità elettronica. Il programma delle CIE ci segnala un errore:
Errori di validazione Fonte ANPR idOperazioneComune  75680626563406660.

Maria Letizia Maglioni

**Comment by rvinzani** [comment]
Salve, probabilmente è un problema dell'applicazione di rilascio della CIE. Potete rivolgervi all'assistenza CIE

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
