### ISSUE TITLE
[endpoint] comune PRE-SUBENTRO

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3203]
Buongiorno,
sto provando l'impostazione dell'endpoint per la ricezione delle notifiche per il comune 041010, in PRESUBENTRO
ma ho un errore nell'invio della notifica di test

"Notifica di Test inviata all'endpoint:
Esito: 2
Risposta: Errore nell'invio della notifica di test"

non capisco se da errore perché l'end point non è stato inserito bene o altro
vedo che nell'esito dell'invio dopo endpoin: non riporta quanto ho inserito in AMMINISTRAZIONE, ho pensato che magari potrebbe entrarci qualcosa.

inoltre l'IP d i provenienza delle notifiche è 217.175.52.159., che ho trovato indicato in #3095 ?

grazie mille

**Comment by Hdemografici** [comment]
Buongiorno, ci sono novità?

**Comment by gife67** [comment]
Buongiorno,
cortesemente se potete riprovare, ho verificato che in ambiente di presubentro è stato correttamente inserito un vostro endpoint.
In ambiente di Test Comuni e Presubentro a differenza della produzione dobbiamo intervenire per la configurazione del servizio per poter effettuare dei test.

**Comment by Hdemografici** [comment]
Buongiorno, grazie mille
ho provato ma ancora non mi arriva la notifica di test, facciamo qualche controllo e vi facciamo sapere.
il CN del certificato del server è con *.xxxx.xxx essendo unico per i vari comuni è un problema?

**Comment by gife67** [comment]
Non ci sono problemi sul certificato del vostro server. Siete sicuri di aver fatto il test in ambiente di Presubentro? non vedo richieste di quel tipo effettuate in quell'ambiente. Mi mandate l'hostname su cui state navigando, ricordando che l'ambiente di presubentro è webpre.anpr.interno.it, mentre l'ambiente di Test Comuni è webtest.anpr.interno.it. In caso stesse provando in test Comuni, occorre che vi configuri il servizio di test anche in quell'ambiente. Ricordo che tra i due ambienti il certificato che viene utilizzato per la crittografia delle notifiche è diverso, sempre 041010-CO-9999 ma uno emesso dalla CA ANPR di test e l'altro dalla CA ANPR di Produzione.
Attendo vostre verifiche

**Comment by Hdemografici** [comment]
ok per il certificato del server, confermo che la prova la sto facendo dal portale del presubentro
https://webpre.anpr.interno.it/ANPRWEB/TestNotifica

ho notato che il primo test dopo il login "lavora" più tempo, le successive danno esito negativo subito

**Comment by gife67** [comment]
Rettifico ho trovato il test delle 10:28 effettuato in presubentro, vi abbiamo inoltrato la notifica al vostro endpoint, ma abbiamo riscontrato un soap fault

**Comment by Hdemografici** [comment]
L'endpoint è corretto.
si la risposta è prevista 
`<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RispostaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">
      <codiceEsito>1</codiceEsito>
      <esito>Notifica ricevuta con successo</esito>
    </ns2:RispostaN000>
  </soapenv:Body>
</soapenv:Envelope>
`
ma per ora non arriva nulla in entrata, facciamo qualche controllo in più
grazie

**Comment by gife67** [comment]
ok attendo le vostre verifiche, perchè per noi è lo stesso flusso che utilizziamo per inoltrare le notifiche a tutti i Comuni ed è OK.
grazie

**Comment by Hdemografici** [comment]
Buongiorno abbiamo fatto qualche controllo in più sembrerebbe che il problema è il valore di "soap action" nella chiamata HTTP che risulta non valorizzato, potete confermarci che è cosi, eventualmente potreste valorizzarlo?
grazie

**Comment by gife67** [comment]
Buongiorno,
il messaggio che inviamo è pienamente conforme ad una richiesta SOAP, con tanto di SOAP Envelop, SOAP Header e SOAP Body come descritto nel WSDL/XSD di questo servizio. Ogni giorno, da molti anni, inviamo centinai di migliaia di messaggi che hanno questo formato a centinaia di endpoint comunali che hanno configurato il servizio ed a tutti i principali Enti (ISTAT, MCTC, AE, INPS), senza che mai nessuno abbiamo evidenziato un problema. La SOAP Action nell'header http non è un parametro obbligatorio ed i nostri appliance di sicurezza non lo applicano, probabilmente il problema è su qualcosa altro.
Grazie

**Comment by Hdemografici** [comment]
Non mi ero spiegato bene, il fatto che mancasse porta ad una gestione "errata" nei nostri applicativi che invece se l'aspettano sempre, quindi se non è previsto/possibile inserirlo vediamo come aggirare la problematica.
grazie mille

**Comment by Hdemografici** [comment]
Buongiorno, 
ho visto la issue #2150 e non mi è chiaro cosa succede se una notifica al momento dell'invio da parte Vostra non venga acquisita correttamente dal Comune, esempio server comunale non raggiungibile (aggiornamenti, mancanza internet/energia elettrica, ...) oppure la notifica non è stata correttamente elaborata (codiceEsito !=1), 
viene automaticamente rinviata in un secondo momento e per quanto tempo/volte?

il dubbio mi è venuto perché nella issue indicata il rinvio era stato fatto su input.

grazie mille

**Comment by gife67** [comment]
Buongiorno,
quando una notifica non viene acquisita per un problema vengono rieseguiti 5 tentativi a distanza di 5 minuti uno dall'altro, dopodichè vengono sospesi i tentativi per la stessa. Quando verifichiamo che la comunicazione è stata ripristinata, procediamo a rinviare tutte le notifiche che hanno avuto un problema, a meno di qualche indicazione esplicita da parte del Comune e/o della Software house. Ovviamente questa gestione fa parte solo del flusso delle notifiche reale, per il test da web app invece vengono effettuati esclusivamente i tentativi di inoltro ad ogni richiesta esplicita effettuata dalla UI.

**Comment by Hdemografici** [comment]
Buongiorno abbiamo sistemato i problemi, abbiamo ricevuto la notifica verificata la firma e decifrato il contenuto.
per ora sembra tutto ok, nei prossimi giorni faremo altri test.

grazie mille

**Comment by gife67** [comment]
Ottimo.
Buon lavoro e grazie a voi per la collaborazione
