### ISSUE TITLE
1 Errore Anpr Cod: EAM9C

### ISSUE THREAD

**Issue by Angela-Sarteano** [italia/anpr#3204]
Angela Nardi Comune di Sarteano (SI)
Non riesco a risolvere questo errore:
1 Errore Anpr Cod: EAM9C - Individuate due posizioni in AT non unificate: procedere con il collegamento dei due codici fiscali se si tratta dello stesso soggetto, o con la richiesta di omocodia se il soggetto e' diverso -(il sogetto non è diverso devo unificare i sue codici fiscali)
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-03-08 17:30:24 , idOperazioneANPR 814088819 - 
Come posso procedere 
Grazie

**Comment by ncapozzi** [comment]
Buonasera
se dovete cambiare il CF deve cambiare anche la data di nascita che deve essere quella corrispondente altrimenti va bene il CF che c'è già ora.
