### ISSUE TITLE
ANPR - Certificabilità Parziale

### ISSUE THREAD

**Issue by elenapozzetti** [italia/anpr#3205]
Buonasera,

dovrei stampare il certificato di stato civile da ANPR, ma il sistema mi da come uniche opzioni: Residenza, Stato di Famiglia. Ho letto che può esistere la fattispecie di "certificabilità parziale", anche se non sono chiari i motivi alla base. Sono nata e vissuta in Italia, ho lavorato in Svizzera come frontaliera (residenza al confine, comunque in Italia) da 10.2019 a 7.2021, dopodichè ho spostato la residenza a Milano (7.2021). Sono nubile (e mai sposata).

Qualcun altro ha avuto stesso mio problema? Potete aiutarmi a risolvere?

Grazie mille a tutti per il supporto. Allego immagine
Elena
![ANPR](https://user-images.githubusercontent.com/101220190/157333563-2dde37c9-8f7f-446d-8705-a60076f1ba26.PNG)

**Comment by cmigliardi** [comment]
per poterla aiutare ci occorro le prime 6 lettere del codice fiscale che usa per accedere . così possiamo vedere la sua scheda in Anpr. grazie

**Comment by elenapozzetti** [comment]
PZZLNE

Grazie

Il giorno mer 9 mar 2022 alle 08:55 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
controllato la scheda deve rivolgersi al suo comune Salerno - e chiedere di verificare  e semmai modificare il dato  :  CERTIFICABILITA PARZIALE (SOLO RESIDENZA E STATO DI FAMIGLIA)

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
stiamo verificando

**Comment by cmigliardi** [comment]
mi scusi poiché  con 6 lettere non riusciamo a individuare la sua scheda ci può dire la data di nascita ? grazie

**Comment by elenapozzetti** [comment]
14.02.1992
Grazie


Il giorno mer 9 mar 2022 alle 15:18 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
grazie - abbiamo capito il motivo -  la invitiamo a rivolgersi al comune di Milano e chiedere di controllare perché ci risulta un procedimento aperto  sulla sua scheda  in Anpr -

**Comment by elenapozzetti** [comment]
Grazie, ho provato a fissare un appuntamento col comune di Milano ma la
prima data utile è tra 3 mesi. Io ho urgenza di avere il certificato di
stato civile per poter fare il rogito della casa entro la fine del mese.
Potete aiutarmi a risolvere?
Grazie


Il giorno mer 9 mar 2022 alle ore 16:26 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
noi non possiamo agire in alcun modo . la competenza è solo del comune- mi spiace - ma la legge  è questa
