### ISSUE TITLE
problemi emissione cie terzo giorno in una settimana

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#3206]
Buongiorno, anche stamattina non è possibile fare CIE.
L'assistenza CIE ci dice che è un problema di collegamente con ANPR.
Potete dirci, con ragionevole certezza, quando il problema si risolverà?
Stiamo rifissando appuntamenti con l'utenza, che comincia ad essere ragionevolmente seccata..
Grazie
Raffaella
venezia
![cie](https://user-images.githubusercontent.com/56832730/157401943-4e2c92de-3323-4e88-9d25-459966c3e708.JPG)

**Comment by FilippoPapi** [comment]
salve era effettivamente un problema di collegamento tra i sistemi CIE e ANPR ma dipendeva dai sistemi cie e non da quelli anpr
cordiali saluti
