### ISSUE TITLE
Correzione estremi vedovanza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3207]
Comune di Nocera inferiore.

Necessità correggere dato di vedovanza del soggetto ID 36028861, deceduto nel  2022, poiché in fase di inserimento morte, è stato re inserito un dato errato di vedovanza, con dati errati di atto e anno.
Il dato giusto è quello presente in locale e non su ANPR.
Non riusciamo né da webapp né da servizi a correggere il dato.
L'assistenza ANPR ci ha chiesto di aprire una richiesta qui su github.
Per avere i dati corretti da inserire potete contattare il comune, io non vorrei inserire dati sensibili in questa sede.

Grazie

**Comment by frmariani** [comment]
Noi non eseguiamo operazioni sui dati dei cittadini, pertanto non sono necessarie le informazioni corrette da fornire.
Sul cittadino cancellato non si possono effettuare operazioni, pertanto il comune deve prima annullare l'operazione di decesso; successivamente potrà correggere i dati della vedovanza e poi  rieseguire l'operazione di decesso.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
