### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by joaoacpacheco** [italia/anpr#3209]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

In contatto con il Comune di Rende (CS) non hanno riscontrato problemi con la scheda anagrafica. 

GIRALDI SHIMAMOTO GUSTAVO
Nato in Brasile
Codice fiscale: GRLGTV

Grazie,

GGS

**Comment by cmigliardi** [comment]
buongiorno . le consiglio di rivolgersi al suo comune di competenza  perchP in Anpr la scheda non esiste  .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
