### ISSUE TITLE
File CFDiversoAssenteDatiDiversiCollegatiOmocodici - Problema formattazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#321]
Segnalo un difetto di intestazione delle colonne del file "CFDiversoAssenteDatiDiversiCollegatiOmocodici", la colonna K intitolata Cognome contiene il C.F., la colonna L intitolata Nome contiene il cognome, e così via fino all'ultima colonna R.
Filipazzi - Maggioli

**Comment by amollicone1982** [comment]
Potete riprovare

**Comment by gcarbonin** [comment]
Ha riprovato?

**Comment by bfilipazzi** [comment]
Abbiamo riprovato, adesso va bene.
Filipazzi  - Maggioli
