### ISSUE TITLE
Anomalia Servizio P001 elenco richieste cittadini

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#3214]
Buongiorno, comune di test Satriano di lucania.
Quando invoco il servizio di cui all'endpoint https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000
ottengo il seguente messaggio di errore:

 ERROR OpP001Handler:45 - Exception nell'invio richiesta
javax.xml.ws.soap.SOAPFaultException: Internal Error (from client)

La Richiesta effettuata è nel file allegato.

Anticipo che ho validato correttamente la richiesta con il tool di validazione, Gli altri servizi funzionano perfettamente.
Potreste fare una verifica? 
Grazie Mille.
Michele Caputo.
[75098-WSP001-TEST.txt](https://github.com/italia/anpr/files/8222550/75098-WSP001-TEST.txt)

**Comment by apaolacci** [comment]
Buongiorno,
non troviamo la sua richiesta in ingresso sui sistemi. Non ci sono invocazioni ai wsP000 mentre vediamo correttamente delle interrogazioni per gli altri servizi 3000, 4000, 5000.
Deve verificare il suo client dal quale cerca di invocare i wsP000. Ha aggiornato gli oggetti, xsd/wsdl sono stati aggiornati con la issue #3185 alla versione 5.15.3 che ha corretto bug e implementato le evoluzioni del cambio residenza emerse dal tavolo di sperimentazione con i comuni.

**Comment by mcaputo75** [comment]
Buongiorno,
ho appena aggiornato gli oggetti riferiti alla versione 5.15.3, continuo ad avere lo stesso errore.
Può verificare se avete ricevuto richieste?

**Comment by apaolacci** [comment]
No nessuna invocazione dal comune 076083 - SATRIANO DI LUCANIA

**Comment by mcaputo75** [comment]
Potreste verificare se in data odierna avete ricevuto invocazioni (di qualsiasi tipo). Ambiente di test 076083.
Potreste indicarmi l'endpoint corretto in ambiente di test per invocare i servizi al cittadino.(in particolare il cambio di residenza).
Grazie.

**Comment by apaolacci** [comment]
Buon pomeriggio,
no nessuna invocazione oggi (data 14/03/2022) in ambiente di test.  Le ultime invocazioni in test per il comune 076083 - SATRIANO DI LUCANIA sono dei 5008 con data 09-MAR-22, 07-MAR-22, 02-MAR-22

Riporto di seguito i due endpoint esposti:
Endpoint TEST COMUNI: https://wstest.anpr.interno.it/anpr-wsP000/AnprServiceP000
Endpoint PRODUZIONE: https://ws.anpr.interno.it/anpr-wsP000/AnprServiceP000
Le pratiche di rettifica e di cambio residenza si differenziano per l'identificativo tipologia 1 e 2, vengono utilizzati gli stessi webservice per l'elenco, il dettaglio, l'aggiornamento pratica.

**Comment by mcaputo75** [comment]
Buongiorno, gentilmente potreste verificare se sono arrivate richieste?
In più, se è possibile potreste verificare l'indirizzo abilitato a fare richieste (questo è il mio indirizzo pubblico 93.57.71.46), perchè ora in ambiente di test non riesco più ad invocare servizi di alcun genere.

**Comment by apaolacci** [comment]
Buongiorno,
non sono arrivate richieste. Per quanto riguarda i WS in ambiente Test Comuni ed anche Presubentro non ci sono filtri su IP.

**Comment by gppbarone** [comment]
La issue viene chiusa, in caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova facendo riferimento a questa.
