### ISSUE TITLE
dataDecorrenza - dataDefinizionePratica - dataEvento comportamento diverso con XML o con rettifica da WEBAPP

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3215]
Comune di Prato, Arianna Nozzoli Istruttore Informatico

Buongiorno,
vorrei sottoporvi un caso che ci è successo.  Quando c'è un decesso sono importanti almeno 3 date:
DATA EVENTO (MORTE)
DATA DECORRENZA 
DATA DEFINIZIONE PRATICA

Prendiamo il caso di TIZIO CAIO morto il 14/12/2021. Decesso registrato dal comune il 11/01/2022
I dati esatti sarebbero:
DATA EVENTO (MORTE) 14/12/2021
DATA DECORRENZA 14/12/2021
DATA DEFINIZIONE PRATICA 11/01/2022

Nell'XML che viene mandato a ANPR vengono riportate invece, tra le altre righe:

dataDecorrenza>2022-01-11</dataDecorrenza
dataDefinizionePratica>2022-01-11</dataDefinizionePratica
dataEvento>2021-12-14</dataEvento

Capisco la scelta. Inviare la data di decorrenza come la data evento potrebbe creare problemi in quanto la data evento è sempre precedente alla data di definizione pratica e potrebbero essere intervenute nel frattempo variazioni ostative alla registrazione.

Però abbiamo provato a rettificare la data di morte per MARIA ROSA dal portale ANPR. Era stata registrata erroneamente deceduta il 30/01/2021. Modificando SOLO la data di morte in 14/01/2021 ANPR ha aggiornato in automatico anche la dataDecorrenza con la data esatta della morte e non mettendo la data del giorno dell'operazione o lasciando quella originale. Quindi ci sono due "gestioni" diverse? Questa operazione su webapp è stata possibile perchè MARIA ROSA e la sua famiglia non avevano avuto variazioni dal 14/01/2021 al 30/01/2021, giusto? Grazie
Arianna Nozzoli
Istruttore Informatico 
Comune di Prato
tel. 0574 183 5223

**Comment by rvinzani** [comment]
Gent.le Sig.ra Nozzoli, gli XML che riporta sono stati generati dal gestionale del vostro comune? Mi sembra strano infatti che non venga tenuto conto che la data decorrenza e di definizione della pratica siano differenti ed invece siano state impostate allo stesso modo

**Comment by anozzoli** [comment]
Buonasera
sì è l'XML preparato dal nostro applicativo verso ANPR al momento della registrazione della morte.
Mi è stato detto dalla Maggioli (che ci fornisce l'applicativo) che sono le direttive Sogei e cioè:

Inviare la data di decorrenza come la data evento potrebbe creare problemi in quanto la data evento è sempre precedente alla data di definizione pratica e potrebbero essere intervenute nel frattempo variazioni ostative alla registrazione.

Che era una spiegazione che avevo preso come assioma ma a dire il vero mi ha anche convinto.
Perchè riprendendo il soggetto detto sopra:
DATA EVENTO (MORTE) 14/12/2021
DATA DECORRENZA 14/12/2021
DATA DEFINIZIONE PRATICA 11/01/2022
Se invio queste date ad ANPR e dal 14/12/2021 al 11/01/2022 la famiglia ha subito variazioni? Non dà errore? Quindi per evitare questo mi hanno detto sia stato deciso di mandare la decorrenza come la definizione pratica e la vera data di morte si vede solo nella data evento. Però se questo è vero si ha il problema sopra esposto.

**Comment by rvinzani** [comment]
In ANPR è possibile gestire le date in maniera indipendente ma ovviamente coerente.
Come data decorrenza si intende la data in cui il comune riceve la comunicazione
come data evento la data in cui si è verificato l'evento (morte, matrimonio etc.)
data definizione della pratica è generalmente la data di chiusura del procedimento ed è importante ai fini delle comunicazioni ad Istat.
C'è in più la data della richiesta che è la data in cui si effettua l'operazione
La data dell'evento ovviamente non può essere maggiore delle atre

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
