### ISSUE TITLE
Purtroppo non è stato possibile access to service

### ISSUE THREAD

**Issue by rpontalti** [italia/anpr#3216]
Egregi Signori 

Sono un cittadino italiano residente all'estero e sono legato al Consolato Generale d'Italia a Curitiba, Brasile. 

Recentemente ho ricevuto il mio SPID. Posso accedere all'Agenzia Delle Entrate e al sito Fast IT. Ma quando provo ad accedere al sito https://www.anagrafenazionale.interno.it/, ricevo il messaggio: "Purtroppo non è stato possibile access to service, ho rivolgerti al tuo comune di residenza (l'iscrizione all'AIRE ) per maggiori informazioni , al fine di sanare l'anomalia nei tuoi dati che non ci ha permesso di individuare in univoco la sua scheda anagrafica". Me lo ha informato il Consolato che non é competete rigurado problemi di SPID e ANPR. Con chi devo parlare per risolvere il problema? Attendo una guida.

Cordiali Salutti,

**Comment by cmigliardi** [comment]
buongiorno . per favore ci può fornire le prime 6 lettere del suo codice fiscale ?  così possiamo verificare il motivo  . grazie

**Comment by cmigliardi** [comment]
per favore ci può fornire le prime 6 lettere del suo codice fiscale ? così possiamo verificare il motivo . grazie

**Comment by cmigliardi** [comment]
Buonasera 
se Lei è nato nel 1980 - abbiamo individuato la sua scheda - si deve rivolgere al suo comune di  competenza Trento che lo ha iscritto aire - e far controllare la sua scheda in anpr - infatti  vediamo che nella scheda il codice fiscale non è validato -  noi non possiamo agire  in quanto non siamo ufficiali di anagrafe. spero di   esserle stata  di ausilio  - salui

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
le avevo già risposto. se Lei è nato nel 1980 - abbiamo individuato la sua scheda - si deve rivolgere al suo comune di competenza Trento che lo ha iscritto aire - e far controllare la sua scheda in anpr - infatti vediamo che nella scheda il codice fiscale non è validato - noi non possiamo agire in quanto non siamo ufficiali di anagrafe. spero di esserle stata di ausilio - saluti
