### ISSUE TITLE
Dichiarazione cambio residenza: sevizio P002 non restituisce civico e recapito telefonico 

### ISSUE THREAD

**Issue by spedrini** [italia/anpr#3218]
Buongiorno.
Ho caricato la dichiarazione di cambio 1250124, in cui ho inserito come indirizzo di destinazione 
**_BORGHETTO delle rose 32, piano 5_** (che continuo a vedere correttamente da webapp).
Invocando il servizio P002 nella sezione `<indirizzo> `all'interno di `<datiDichiarazioneResidenza>` non è presente il tag `<numeroCivico>`, come si vede nell'esempio:

```xml
  <datiDichiarazioneResidenza>
    <tipoFamiglia>2</tipoFamiglia>
    <componentiCoinvolti>
        <componente>
            <idSchedaSoggettoANPR>92938834</idSchedaSoggettoANPR>
            <idGradoParentela>1</idGradoParentela>
            <flagPatente>SI</flagPatente>
            <flagVeicoli>NO</flagVeicoli>
            <statoAccettazione>3</statoAccettazione>
        </componente>
    </componentiCoinvolti>
    <indirizzo>
        <cap>48782</cap>
        <comune>
            <nomeComune>PIETRAVAIRANO</nomeComune>
            <codiceIstat>061059</codiceIstat>
            <siglaProvinciaIstat>CE</siglaProvinciaIstat>
        </comune>
        <toponimo>
            <codSpecie>14</codSpecie>
            <denominazioneToponimo>delle rose</denominazioneToponimo>
        </toponimo>
    </indirizzo>
    <datiImmobile>
        <idTipoOccupazione>1</idTipoOccupazione>
        <sezione>100</sezione>
        <foglio>456</foglio>
        <particella_mappale>3</particella_mappale>
        <subalterno>43</subalterno>
    </datiImmobile>
</datiDichiarazioneResidenza>
```
Inoltre nonostante in fase di compilazione abbia indicato anche il recapito telefonico, questo campo manca nella lista dei recapiti:
```xml
<dettaglio>
    <codiceRichiesta>1250124</codiceRichiesta>
    <idTipologia>2</idTipologia>
    <dataApertura>2022-03-11T09:03:03.000+01:00</dataApertura>
    <dataScadenza>2022-03-15T23:59:59.000+01:00</dataScadenza>
    <dataUltimoAggiornamento>2022-03-11T09:03:03.000+01:00</dataUltimoAggiornamento>
    <numeroProroghe>0</numeroProroghe>
    <statoRichiestaCorrente>
        <idStato>2</idStato>
        <operatore></operatore>
        <dataStato>2022-03-11T09:03:03.000+01:00</dataStato>
    </statoRichiestaCorrente>
    <recapiti>
        <recapito>
            <idTipologiaRecapito>1</idTipologiaRecapito>
            <valoreRecapito>serenapedrini@gmail.com</valoreRecapito>
        </recapito>
    </recapiti>
```

**Comment by apaolacci** [comment]
Buongiorno,
dovrebbe indicare l'_idOperazioneComune_ della richiesta XML da verificare. 
Per la pratica indicata 1250124, verificando sul log dell'invocazione più recente vedo il civico ed il piano valorizzato:
```
<indirizzo>
	<cap>48782</cap>
	<comune>
		<nomeComune>PIETRAVAIRANO</nomeComune>
		<codiceIstat>061059</codiceIstat>
		<siglaProvinciaIstat>CE</siglaProvinciaIstat>
	</comune>
	<toponimo>
		<codSpecie>14</codSpecie>
		<denominazioneToponimo>delle rose</denominazioneToponimo>
	</toponimo>
	<civico>32</civico>
	<piano>5</piano>
</indirizzo>
```
Forse è necessario verificare il vostro client ? xsd/wsdl sono stati aggiornati con la issue [3185](https://github.com/italia/anpr/issues/3185) alla versione 5.15.3 che ha corretto bug e implementato le evoluzioni del cambio residenza emerse dal tavolo di sperimentazione con i comuni.

Associato alla pratica 1250124 c'è un solo record su tabella SC_RECAPITIRIEPILOGO che indica il recapito indicato nel profilo-utente del cittadino:  _serenapedrini@gmail.com_

Dove è stato indicato il recapito telefonico mancante in fase di compilazione della dichiarazione di cambio residenza ?

Se si tratta del numero telefonico 0541628555 indicato come preferenza di contatto per l'ufficiale d'anagrafe per questa pratica è presente nel tag seguente `<recapitoTelefonico>`:

```
<datiDichiarazioneResidenza>
	<tipoFamiglia>2</tipoFamiglia>
	<recapitoTelefonico>0541628555</recapitoTelefonico>
	<componentiCoinvolti>
		<componente>
                  ...  ... 
```

Allego input/output dell'invocazione più recente che trovo su log: idOperazioneComune = JD220311112118249

[JD220311112118249.txt](https://github.com/italia/anpr/files/8231609/JD220311112118249.txt)
