### ISSUE TITLE
Dichiarazione cambio residenza: passaggio di stato da IN LAVORAZIONE a ANNULLATA non consentito

### ISSUE THREAD

**Issue by spedrini** [italia/anpr#3219]
Buongiorno,
attualmente non è consentito il passaggio di una richiesta da IN LAVORAZIONE (3) a ANNULLATA (4).
Questo limite potrebbe creare problemi, poichè può succedere che un comune abbia necessità di annullare la richiesta senza accoglierla dopo le 48 ore.
Ad oggi i nostri clienti sono abituati a potere procedere in questo senso, utilizzando il nostro applicativo.
Sarebbe possibile rimuovere questo vincolo?

Grazie

**Comment by apaolacci** [comment]
Buongiorno,
attualmente i passaggi di stato del processo di lavorazione pratica sono quelli indicati nel primo avviso di rilascio #3043 nel file [flusso_stati_pratica_cittadino.pdf](https://github.com/italia/anpr/files/8090740/flusso_stati_pratica_cittadino.pdf)

**Comment by ncapozzi** [comment]
Buongiorno,
confermiamo quanto già condiviso nei tavoli di analisi dei requisiti e sul file delle segnalazioni che stanno trasmettendo i Comuni apripista https://docs.google.com/spreadsheets/d/1wkKEk_4GssUtwe5se8TyXwFmo3G67UIQVUCaURbFQ7Q/edit#gid=0

Se la pratica non è stata presa in carico potete dichiararla Irricevibile specificando la motivazione nelle note. Se invece è già stata presa in carico dovete eseguire tutti i passaggi di stato Accolta con riserva -> Preavviso di rigetto -> Annullata sempre specificando la motivazione nelle note

Si fa presente che nell'ultima release dell'8 marzo è stato inserito un messaggio di conferma ad ogni passaggio di stato effettuato dal Comune proprio per ridurre la possibilità di errore.
