### ISSUE TITLE
servizio di notifica

### ISSUE THREAD

**Issue by MaurizioDallaglio** [italia/anpr#322]
A prescindere dal contenuto della notifica, la modalità standard per l’acquisizione della notifica consiste nella esposizione da parte del comune di un servizio “di accettazione notifiche”.
Il servizio esposto dal comune deve:
 Prendere in carico la notifica e registrarla in una propria base dati;

SPECIFICHE DI INTERFACCIA DEI SERVIZI DI ANPR MI-14-AN-01
PER I COMUNI PAG. 158 DI 190
12 LUGLIO 2017
 restituire contestualmente ad ANPR una risposta, costituita da un messaggio soap che nel body riporta l’esito della presa in carico; gli esiti previsti sono i seguenti:
• 1 notifica correttamente acquisita
• 5 messaggio non conforme alle specifiche
• 6 il messaggio non contiene dati
• 7 errore di comunicazione
In assenza di una risposta, ANPR provvederà ad un nuovo inoltro.
Successivamente, il SW comunale provvederà ad elaborare la notifica

Il messaggio di ritorno è strutturato in questo modo:

`<n00:RispostaN000 xmlns:n00="http://sogei.it/ANPR/N000AnprService">
         <codiceEsito>mio cod esito</codiceEsito>
         <esito>mio esito</esito>
      </n00:RispostaN000>
   </soap:Body>
`

gli esiti (1,5,6,7) vanno valorizzati in `<codiceEsito>` oppure in `<esito>?`
Si specifica che in assenza di risposta ANPR effettuerà un ulteriore inoltro, anche nei casi di esito diverso da 1?

**Comment by gcarbonin** [comment]
1) nel campo esito
2) se il sistema destinatario ha risposto (con qualsiasi esito), non si procede automaticamente ad un nuovo inoltro in quanto nei casi di errore occorre prima analizzare la causa. La frase si riferisce ai casi in cui il sistema destinatario non risponde per niente; nel nostro sistema, questo genera un esito 7 a fronte del quale si ripete l'invio per x volte prima di considerare l'end-point non attivo. Questa parte, questa parte è in revisione. Sono graditi contributi.
