### ISSUE TITLE
 Stato estero di nascita incongruente con il cod. catastale

### ISSUE THREAD

**Issue by mariangelag** [italia/anpr#3220]
Montalbano Jonico Produzione
Nel tentare di iscrivere un individuo cancellato in Anpr otteniamo l'errore in oggetto in quanto ha luogo di nascita associato ad uno stato estero diverso dal catastale del CF. 
Si richiede che all'individuo con id 95317667 sia corretto lo stato di nascita da BOLIVIA A PERU' oppure ci occorre sapere come possiamo iscrivere senza validazione l'individuo nella nostra apr e poi effettuare una risoluzione disallineamenti con AE mediante Web Application. 
Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-03-11 12:20:41 , idOperazioneANPR 817809836
Grazie

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare inserendo direttamente PERU' cod. 615 come stato di nascita?

**Comment by mariangelag** [comment]
salve, 
nserendo PERU' ha funzionato,
grazie
