### ISSUE TITLE
Errore Accesso ANPR

### ISSUE THREAD

**Issue by cyb3rDem0n** [italia/anpr#3224]
Salve

Sto cercando di richiedere il certificato contestuale prescritto in formato digitale, ma a seguito dell'autenticazione tramite SPID il portale mi restituisce il seguente errore:

`Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.`

Ho notato altri utenti con il mio stesso problema, quindi vi scrivo di seguito le ultime 5 cifre del mio codice fiscale.
XXXXXXXXXXXC710D

grazie per il supporto.

**Comment by cmigliardi** [comment]
buonasera cortesemente ci occorrono le prime 6 lettere  altrimenti non riusciamo ad individuare in modo univoco la sua scheda - grazie in anticipo

**Comment by cyb3rDem0n** [comment]
Salve, di seguito i dati richiesti.
DGSGPP

**Comment by cmigliardi** [comment]
se ho individuato la scheda lei è nato nel 1986 - dove risiede adesso ?  lo chiedo perché  in Anpr   abbiamo due schede  - una con residenza a Milano  e una con residenza Gioia Tauro - questo il motivo  del mancato accesso-  non riusciamo ad identificarla in modo univoco. quindi le consiglio di rivolgersi al suo comune di residenza  che dovrà chiamare l'altro comune per far cancellare per doppia iscrizione l'altra scheda.   spero di esserle stata di ausilio .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cyb3rDem0n** [comment]
Sono residente a Milano dal 2018.

**Comment by cmigliardi** [comment]
perfetto allora il comune di Milano chiamerà il comune di Gioia Tauro che dovrà fare una cancellazione per doppia iscrizione o comuqnue  dovrà controllare la scheda che ha   con il suo codice fiscale - potrebbe anche aver copiato male- e magari si tratta di una persona diversa da lei. in ogni caso   deve agire Gioia Tauro

**Comment by cyb3rDem0n** [comment]
A quindi devo sollecitare io il comune di Gioia Tauro o lo farà il comune di Milano?

Grazie per il supporto

**Comment by cmigliardi** [comment]
Milano! lei si rivolga a milano   anche con le mie indicazioni poi loro chiameranno l'altro comune

**Comment by cyb3rDem0n** [comment]
Okay grazie

**Comment by cmigliardi** [comment]
di nulla . in ogni caso  se Milano dovesse incontrare difficoltà può chiedere il nostro  supporto attraverso il canale di  assistenza riservato ai comuni .

**Comment by cyb3rDem0n** [comment]
Dovrei recarmi in comune per ottenere il certificato contestuale ad uso matrimoniale,  nel caso in cui le cose vanno per le lunghe. Grazie.
