### ISSUE TITLE
non e' possibile emettere nessun certificato, rivolgersi al comune di redidenza

### ISSUE THREAD

**Issue by Lanwineconsulting** [italia/anpr#3225]
Ciao a tutti,

Ho provato a rilasciare un certificato di residenza ma dice:"non e' possibile emettere nessun certificato, rivolgersi al comune di redidenza" .

Inoltre, lo Stato civile è :NON CLASSIFICABILE/IGNOTO/N.C.

Codice identificativo comunale:1023656
Codice identificativo ANPR:43651594

Qualcuno può aiutarmi?

Grazie,

**Comment by cmigliardi** [comment]
buongiorno le consiglio di rivolgersi presso il suo comune di residenza Verona che potrà modificare i dati sulla sua scheda in ANPR   . sia lo stato civile  sia  il campo legato alla certificabilità . -  noi non possiamo agire in alcun modo - spero di esserle stata di ausilio
