### ISSUE TITLE
Elenco province cambio residenza non completo

### ISSUE THREAD

**Issue by nicosh** [italia/anpr#3227]
Nella sezione residenza (nell'apposito form per fare una nuova richiesta) non vengono elencate tutte le province ma solamente alcune.
Questo comportamento è normale? (dovuto al fatto che non tutte le province/comuni hanno aderito) o c'è un anomalia?
Nel caso fosse la prima opzione andrebbe esplicitato da qualche parte che la copertura non è ancora al 100&.
Grazie.

**Comment by ncapozzi** [comment]
Buonasera
nella sezione residenza sono elencati i soli Comuni che hanno deciso di aderire al servizio già dalla fase iniziale come indicato alla pagina www.anagrafenazionale.interno.it alla voce Dichiarazione cambio residenza e anche nell'area riservata alla sezione Avvisi.
