### ISSUE TITLE
Consultazione procedimento amministrativo

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3229]
Buonasera

con quale servizio è possibile verificare se per un cittadino esistono procedimenti? cioè vorrei sapere se e come è possibile ottenere via WS le informazioni consultabili dalla webapp nella sezione Consultazione procedimento amministrativo, 
E' possibile ottenere queste informazioni anche se il cittadino è residente in un altro Comune?

Il controllo di esistenza procedimento aperto viene effettuato solo se il procedimento è di un comune diverso dal comune che effettua l'operazione? 
Da webapp ho aperto diversi procedimenti per una stessa persona senza che mi venisse segnalato alcunché.

Grazie
_Raffaella Tremolada_ 
S.I. per Comune di Milano

**Comment by ANPRCdMI** [comment]
Speravamo fosse possibile, perché vorremmo gestire la segnalazione sul gestionale in apertura della pratica, per evitare di dover gestire l'errore al momento della registrazione del cambio di residenza. Confermate anche che non è possibile nemmeno chiedendo l'apertura di un nuovo procedimento (1014), perché l'apertura viene accettata anche se esiste altro procedimento in corso?

**Comment by rvinzani** [comment]
Perdonate, in realtà è presente il servizi 3004 per l'interrogazione dei procedimenti amministrativi

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
