### ISSUE TITLE
versioning dei servizi di notifica

### ISSUE THREAD

**Issue by MaurizioDallaglio** [italia/anpr#323]
dalla documentazione:
<<A tal fine, nella parte comune a tutti i messaggi (testataRichiesta) si utilizza l’attributo codDestinatario che identifica l’applicazione di riferimento cioè quale versione MAJOR supporta il sw anagrafico. Questo attributo è già obbligatorio e attuamente contiene il valore “ANPR00”; tale valore verrà impostato ad “ANPR01” al rilascio della prima MAJOR version e sarà progressivamente incrementato in corrispondenza di un rilascio di una MAJOR version successiva. L’attributo della versione viene controllato prima della validazione di tutto il resto del messaggio per permettere ad ANPR di validare il messaggio stesso con il WSDL più opportuno>>

per i servizi di notifica `codDestinatario` è destinato a contenere il codice ISTAT del destinatario della notifica. Come viene gestito il versioning per i servizi di notifica?

**Comment by gcarbonin** [comment]
Si utilizza il campo codMittente che conterrà la versione dell'applicazione con la quale è stata predisposta la notifica.
