### ISSUE TITLE
Servizi al cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by elirac** [italia/anpr#3230]
Cercando di accedere a Servizi al Cittadino (ANPR) dopo aver accesso tramite lo SPID appare questo messaggio:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Il mio Comune è il Comune di Roma ed è in ANPR, vi ho contattati in precedenza e mi avete consigliato di rivolgermi al Comune di Roma, ma in hanno detto che non risultano esserci problemi con la mia scheda anagrafica. Tuttavia ancora non riesco ad accedere al servizio, sono settimane ormai e ho bisogno di alcuni documenti per lavoro, non capisco come risolvere il problema.
Prime 6 cifre del codice fiscale: RCCLBT
Vi chiedo gentilmente di aiutarmi, ne avrei davvero bisogno.
Grazie

**Comment by cmigliardi** [comment]
buonasera se è lei la persona nata nel 1998   e residente a roma - allora si deve  rivolgere al comune  perché in Anpr la sua scheda non c'è. -  esiste  ma senza il codice fiscale e con i dati anagrafici diversi da quelli di agenzia entrate  - spero di esserle stata  di ausilio

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
