### ISSUE TITLE
Stampa Dati Scheda individuale

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#3231]
Buongiorno, esiste un modo per richiedere la stampa dati scheda individuale (quella che viene stampata dalla webapp) così come avviene per i certificati?
Grazie

**Comment by ncapozzi** [comment]
Buongiorno
per stampare i propri dati il cittadino può accedere al portale di ANPR con CIE, SPID o CNS, andare sulla Visura e stampare l'autocertificazione.
