### ISSUE TITLE
Interrogazione DECEDUTO in ANPR XML di ritorno

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3232]
Comune di Prato, Arianna Nozzoli

Buongiorno,
vorrei migliorare la visione dell' AP5 di ANPR nel nostro applicativo Maggioli, ma da Maggioli mi dicono che non è possibile perchè ANPR non gli passa i dati necessari nel file XML. Mi spiego. 
Prendiamo il caso di un soggetto deceduto con questi dati in ANPR

dataDecorrenza>2022-01-11</dataDecorrenza
dataDefinizionePratica>2022-01-11</dataDefinizionePratica
dataEvento>2021-12-14</dataEvento

Attualmente nella nostra visualizzazione dell'AP5 di ANPR per un deceduto vedo scritta l'informazione
 
Cancellata  da ANPR per MORTE il 11/01/2022 

dove 11/01/2022 è la data di decorrenza.
Questa informazione ci sembra fuorviante in quanto la morte è avvenuta il 14/12/2021.
Vorrei quindi che ci venisse scritto 

Cancellata  da ANPR per MORTE il 11/01/2022 avvenuta in data 14/12/2021

Dalla Maggioli mi dicono che nel file XML di ritorno la dataEvento non c'è. Possibile?
Grazie

**Comment by rvinzani** [comment]
Se la visualizzazione dell'AP5 è un servizio offerto dal vostro gestionale credo che in ogni caso sulla banca dati locali siano presenti tutte le informazioni necessarie

**Comment by rvinzani** [comment]
Chiudo la issue. In caso fossero necessarie ulteriori informazioni si prega di aprire una nuova issue che faccia riferimento a questa
