### ISSUE TITLE
Errore ambiente di Test

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3234]
Buongiorno, dalle 13 non riesco ad ottenere risposte ad interrogazioni in ambiente di test. 

javax.xml.ws.soap.SOAPFaultException: Internal Error
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:161)
	at com.sun.proxy.$Proxy82.interrogazioneCittadinoFamigliaConvivenza(Unknown Source)

Vi risultano problemi ?

Grazie

**Comment by mttfranci** [comment]
Salve, potreste riprovare?
Grazie in anticipo

**Comment by galliandrea** [comment]
Adesso funziona, grazie

**Comment by mttfranci** [comment]
Di niente.

Saluti
