### ISSUE TITLE
Errore CAST Assegnazione Ruoli - Gestione Utente 

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3236]
Comune di TON 

Buongiorno, 

In data odierna il comune stava provando a considera della gestione delle utenze la nuova dipendente di anagrafe.
L'operazione è stata fatta con la SMARTCARD del Sindaco
L'utente è stato creato, ma nel momento di assegnare all'utente i ruoli per l'accesso ANPR viene riportato il seguente errore:

Errore CAST Assegnazione Ruoli

Facendo una ricerca tra le segnalazioni pregresse ho trovato la #1056

**Comment by Leonforte** [comment]
Buongiorno, la problematica è stata risolta, buon lavoro, saluti

**Comment by jonnyfx95** [comment]
Confermo l'utenza funziona correttamente in ANPR.
Grazie
