### ISSUE TITLE
Errore con eliminazione dati matrimonio

### ISSUE THREAD

**Issue by mariangelag** [italia/anpr#3237]
Rose produzione
Abbiamo un problema con il servizio di eliminazione dati per l'oggetto matrimonio
Provando ad effettuare diverse eliminazioni sull'individuo 155322922 ricevendo esito positivo dell'avvenuta eliminazione , consultandolo subito dopo, lo troviamo coniugato con un altro individuo
Attualmente risulta coniugato con 155322743 
invece abbiamo la necessità di collegarlo a 155322921
Pur agendo con mutazioni tutti i dati non è possibile, in quanto la modifica del coniuge non viene recepita. 

Abbiamo anche la necessità di correggere il coniuge che l'eliminazione ha sovrascritto a 155322743 

Restiamo in attesa di info su come procedere

Grazie

**Comment by frmariani** [comment]
In fase di subentro, per il cittadino idanpr 155322922,  sono stati inviati i dati del matrimonio con ben 22 soggetti diversi, pertanto devono essere revocati tutti i dati non corretti pervenuti.
Alla consultazione del cittadino, selezionate il soggetto coniuge ed effettuate l'eliminazione dei dati del matrimonio a lui imputati (così come avete già fatto per almeno 4 volte); in questo momento il cittadino idanpr  155322922 risulta coniugato con il soggetto idanpr 155322743, pertanto dovete effettuare la revoca dei dati del matrimonio per questo soggetto. Alla conclusione positiva dell'operazione, il cittadino  idanpr 155322922  risulterà coniugato con un altro soggetto e voi dovrete eliminare i dati del matrimonio del soggetto in questione e così via finchè il cittadino idanpr  155322922 non risulterà sposato con il soggetto corretto.  
Fatemi sapere se è chiara la soluzione del problema e soprattutto se sopraggiungono impedimenti alla revoca del dato

**Comment by vs691** [comment]
Buon pomeriggio, sono sopraggiunti impedimenti alla revoca del dato su questa coppia di individui coniugati di cui lei è occasionale nel comune 102800836 sposata con: 
155322839 legato al cittadino che è sposato 22 volte ( soggetto 155322922).
l'errore è il seguente Object reference not set to an instance of an object.
Grazie mille, buon lavoro

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
