### ISSUE TITLE
CODICE FISCALE DISCORDANTE AT/ANPR

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3238]
Buonasera,
COMUNE DI CASERTA 061022 - PROD

Un cittadino è presente in ANPR dal subentro con codice fiscale XXXXXXXXXXXXYYYY  validato AT.
in AT invece è presente anche il codice fiscale XXXXXXXXXXXXZZZZ **non presente in ANPR**
in AT la nascita risulta in comune non più esistente alla nascita.
**Il cittadino ha prodotto documentazione fiscale e richiesto SPID con quello AT** 
Come si possono associare i due codici fiscali?   
Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
potete procedere facendo accesso alla web app di ANPR/Utilità e notifiche/Risoluzione disallineamenti con Agenzia Entrate come indicato al cap. 4 della guida [allegata.](https://www.anpr.interno.it/wp-content/uploads/2021/03/Risoluzione-disallineamenti-con-lAgenzia-delle-Entrate-11_02_2019.pdf)

Per richiedere la nostra assistenza potete contattare il numero verde 800.863.116
