### ISSUE TITLE
Consultazione procedimento amministrativo  

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3240]
#3229  Consultazione procedimento amministrativo 

Nella risposta alla issue collegata viene indicato di utilizzare il servizio 3004- ConsultazioneProcAmm.
Nelle note viene però indicato "Controllo esistenza soggettoColelgato con almeno un procedimento associato al comune mittente". 

La ricerca quindi può essere effettuata solo per il comune richiedente? significa che non possiamo consultare i procedimenti di altri comuni? 

Grazie per la collaborazione

_Raffaella Tremolada_
S.I. per Comune di Milano

**Comment by rvinzani** [comment]
sì ogni comune vede solo i propri procedimenti sui propri cittadini
