### ISSUE TITLE
[1001] immigrazione ANPR: pratica bloccata per procedimento aperto da altro comune

### ISSUE THREAD

**Issue by Svitoromano** [italia/anpr#3243]
buongiorno,
non riusciamo a concludere il procedimento di immigrazione da altro comune anpr n.177110090 (cittadino: R.A. del 1980) per via del seguente errore:

E | EN531 | Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune PALESTRINA (RM) con numero pratica ANPR: 61017086
E | EN527 | Informazioni sull'operazione da fornire in caso di assistenza : data 2022-03-22 09:25:21 , idOperazioneANPR 828976110
W | EN395 | per il tipo di mutazione 2 saranno modificati soltanto i dati relativi a residenza e autoveicoli

il comune di provenienza, contattato con molta difficolta', sostiene di aver concluso ogni procedimento sospeso inerente il cittadino; di seguito il testo della loro pec:
OGGETTO:
POSTA CERTIFICATA: COMUNE DI SAN VITO ROMANO - 11/03/2022 - 0001493 PROCEDIMENTO SOSPESO CITTADINO R.A.
Si comunica che la posizione del cittadino di cui all'oggetto è stata definita pertanto si può procedere all'iscrizione dello stesso.
L'UFFICIO ANAGRAFE

**Comment by ncapozzi** [comment]
Buongiorno
è stata trasmessa una email a 'anagrafe@comune.palestrina.rm.it' (cc: 'anagrafe@sanvitoromano.rm.gov') con le istruzioni da seguire per la chiusura del procedimento.

Per ulteriori richieste di assistenza potete contattare il numero verde 800863116.
