### ISSUE TITLE
Errore EN306 - Presenza del coniuge e assenza del matrimonio

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#3245]
Buongiorno,

il comune di Torino sta cercando di iscrivere il soggetto con identificativo anpr 84083035 proveniente dal comune di Ospedaletti ma il sistema ritorna l'errore EN306.

Abbiamo verificato su webapp e stampato una scheda da consultazione (id. 830814684) e sembra tutto a posto.
Sono caricati i dati del coniuge, del matrimonio e della vedovanza, inoltre risulta correttamente vedova.

Cosa possiamo verificare ?
E' un problema del comune di attuale residenza o del comune che lo deve prendere in carico ?

Grazie

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by frmariani** [comment]
Cortesemente l'idanpr dell'operazione fallita

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
