### ISSUE TITLE
Assenza di Roma da provincia nuova residenza

### ISSUE THREAD

**Issue by crisostomi** [italia/anpr#3247]
Buongiorno,

Da quanto letto su varie fonti e su uno degli avvisi sul sito stesso di https://www.anagrafenazionale.interno.it/ Roma dovrebbe essere già parte del database, ma quando vado a compilare la domanda per il cambio di residenza non la trovo fra le province possibili.

Vi ringrazio.

**Comment by gppbarone** [comment]
Buongiorno, 
https://www.anagrafenazionale.interno.it/dichiarazione-cambio-residenza/ questo è l'avviso riguardante i Comuni sperimentatori che hanno aderito sin da subito al servizio di  Dichiarazione cambio di residenza, Roma non è tra questi.

Buona giornata.

**Comment by crisostomi** [comment]
Salve,

Varie testate, e.g. https://www.romatoday.it/politica/cambi-residenza-online-roma-come-fare.html, promettevano che Roma avrebbe aderito dal 1 marzo. Si sa se questo avverrà nel futuro prossimo?

**Comment by Hdemografici** [comment]
Consultando il link indicato  "Roma diventa più smart e punta al digitale. Dal 1 marzo anche il Comune di Roma **lancerà il proprio sistema di presentazione online** delle domande per il cambio di residenza."

[https://www.comune.roma.it/web/it/scheda-servizi.page?contentId=INF879978](url)

**Comment by crisostomi** [comment]
La nuova modalità consente ai *cittadini registrati in ANPR di effettuare alcune dichiarazioni anagrafiche online quali: cambio di residenza* per il trasferimento da un qualsiasi Comune.
Quindi bisogna essere registrati in ANPR ma poi fare la domanda da un'altra parte? Lapalissiano

**Comment by ncapozzi** [comment]
Buongiorno, l’estensione a tutti i Comuni Italiani del servizio di cambio di residenza erogato da ANPR avverrà presumibilmente entro la fine di aprile.
