### ISSUE TITLE
LETTURA NUOVE SMART CARD

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#3248]
Problemi con lettore smart card ANPR, si chiede se possibile iter completo per installazione smart card ANPR nuove con Browser Firefox, anche registrando il modulo bit4id e importando il certificato di postazione da spesso errore e non si collega.

Ci sono configurazioni particolari o impostazioni da settare?

**Comment by paoloHV** [comment]
lascio mail paolo.barbato@halleyveneto.it

**Comment by adominicis** [comment]
Le nuove smart card ANPR (seriale 12081) necessitano della versione 4.2 del SafeDive. Il programma può essere installato anche se già presente sul pc la versione 3.4.1. Inoltre la versione 4.2 permette l'accesso alla Webapp con entrambe le tipologie di smart card Infocert. Il resto della configurazione non è cambiato, si deve importare un certificato di postazione su firefox e la libreria da associare è sempre la stessa, stpkcs11.dll.

**Comment by paoloHV** [comment]
ok, il fatto che ci sia un idp protect monitor installato può dare problemi? va disinstallato? il safe dive va bene anche per le vecchie smart?

**Comment by adominicis** [comment]
L'IDP non crea problemi, deve rimanere installato se si hanno altre smart card di ANPR del primo fornitore Aruba (pin 5 cifre)

**Comment by etorrenti** [comment]
Salve, sto cercando di far accedere un amministratore di prefettura. La smart card ha numero di serie che inizia per 12081. Ho cercato invano SafeDive 4.2. La versione 3.4.1 non rende la carta visibile a Firefox, come anche IDP. Ho ottenuto un moderato successo solo col Bit4Id Universal Middleware, che rende la carta visibile, mi fa inserire il PIN, mi permette di leggere il certificato sulla carta con applicazioni di terze parti, ma al momento di eseguire l'autenticazione su dp.anpr.interno.it ottengo solo un errore SSL_ERROR_HANDSHAKE_FAILURE_ALERT.
Cosa sto sbagliando?

**Comment by adominicis** [comment]
Buongiorno, può indicarmi una sua email dove posso contattarla?

**Comment by etorrenti** [comment]
Certamente: emanuele.torrenti@interno.it
Grazie

**Comment by etorrenti** [comment]
Salve, un aggiornamento: coi SafeDive 4.2 che mi hanno favorito sottobanco funziona tutto regolarmente. La vera domanda, a questo punto, è: dove si scaricano in sicurezza e ufficialità questi driver? La documentazione sul sito ANPR vorrà dircelo o resterà un segreto da reperire fra le issues di GitHub?

**Comment by Leonforte** [comment]
Buonasera, stiamo appunto attendendo a breve l'ufficializzazione del driver da parte di Infocert e la relativa disponibilità del software sul loro sito ufficiale, buon lavoro, saluti
