### ISSUE TITLE
Consultazione ad una data, presenta indirizzo con validità successiva

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#325]
Ambiente di test - Poggio a Caiano (PO)
Soggetto ID-ANPR 913319
Il soggetto è iscritto dal 19/05/2016, con residenza in via A
Oggi con web app ho rettificato la decorrenza della residenza, che era mancante, indicando il valore 19/05/2016, coincidente a quello dell'iscrizione. Poi ho eseguito un cambio di indirizzo nel comune da via A a via B, con decorrenza 24/09/2017.
La produzione di un certificato di residenza storico rispecchia questi fatti documentandoli come mi aspetto:
Risulta iscritta con i seguenti dati:
Comune di POGGIO A CAIANO (PO) dal 19/05/2016
Indirizzo VIA B dal 24/09/2017
Indirizzo VIA A dal 19/05/2016
Ho richiesto la consultazione dei dati della persona con il servizio 3002 e dataRiferimentoRichiesta = 2017-09-01, mi aspetto di ricevere la scheda con l'indirizzo A valido alla data di riferimento, invece leggo l'indirizzo B.
idOperazioneComune = 20000215
idOperazioneANPR = 586704
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
avvertiamo quando riprovare

**Comment by asqueglia** [comment]
E' possibile riprovare. Grazie

**Comment by bfilipazzi** [comment]
Risolto, grazie.
Filipazzi - maggioli
