### ISSUE TITLE
Errore :[] Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica

### ISSUE THREAD

**Issue by gabrielcioffi39** [italia/anpr#3251]
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.
Grazie.

Marcello Cioffi
Codice fiscale CFFMCL
Comune di Pozzuoli

**Comment by cmigliardi** [comment]
buonasera le consiglio di rivolgersi al suo comune di residenza Pozzuoli   poiché in ANPR ci sono 2 schede con 2 residenze diverse - napoli  e    pozzuoli -    spero di esserle stata di ausilio

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
