### ISSUE TITLE
AEE95 Operazione non Effettuabile

### ISSUE THREAD

**Issue by erikaap** [italia/anpr#3252]
Effettuando una pratica d'immigrazione, al momento della registrazione compare :
operazione richiesta: 1002
Codice Errore anomalia: AEE95
Testo errore anomalia: operazione non effettuabile
Codice errore anomalia EN597

Ci sono problemi con anpr?
Grazie

**Comment by erikaap** [comment]
Effettuando una pratica di nascita, al momento della registrazione compare:
operazione richiesta: 1001
Codice errore anomalia: AEE97
Testo errore anomalia: operazione non effettuabile
Codice errore anomalia EN597

Ci sono problemi di collegamento con Agenzia delle Entrate?

**Comment by rvinzani** [comment]
Si sono verificati dei problemi con i servizi di agenzia Entrate ora risolti. Chiudo pertanto la issue. Nel caso in cui il problema fosse ancora presente si prega di aprire una nuova issue che faccia riferimento a questa.
