### ISSUE TITLE
AEE95 - Operazione non effettuabile

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#3254]
Non è possibile effettuare la variazione di nome per il soggetto 282416318

Sia da applicativo che da webapp (funzione "risoluzione disallineamenti agenzia entrate") otteniamo il medesimo errore.
Gli id anpr sono: **835189807** (ws 5008) e **835187434** (via webapp)

Attendo riscontro per procedere

Grazie

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by rvinzani** [comment]
Si sono verificati dei problemi con i servizi di agenzia Entrate ora risolti. Chiudo pertanto la issue. Nel caso in cui il problema fosse ancora presente si prega di aprire una nuova issue che faccia riferimento a questa.
