### ISSUE TITLE
[P003] controlli cambio stato

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3255]
Buongiorno,
vorremmo sapere quali controlli ci sono sui cambi stato delle pratiche?
es. dallo stato "aperta" si può passare "in lavorazione" ma non posso passare da "integrata" ad "in lavorazione"

grazie

**Comment by apaolacci** [comment]
Buongiorno,
si riceve errore se il cambio da uno stato di partenza ad un altro non è ammesso. Nella issues #3043 e ##3185 in cui si anticipava il rilascio in ambiente di test e produzione è riportato il diagramma degli stati assunti da una pratica lungo l'iter di lavorazione [flusso_stati_pratica_cittadino.pdf](https://github.com/italia/anpr/files/8370761/flusso_stati_pratica_cittadino.pdf) e l'eventuale passaggio obbligatorio del campo _note_ o del _motivo di irricevibilità_.

Saluti
Assistenza Anpr

**Comment by Hdemografici** [comment]
grazie mille
ci era sfuggito
