### ISSUE TITLE
Nuovo Consolato Arona - ambiente test comuni

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#3256]
test comuni - comune San Dorligo Della Valle Dolina (032004)
abbiamo provato ad inserire da web app un nuovo cittadino aire con residenza Spagna (isole canarie) per testare il nuovo consolato di Arona
riceviamo errore 
EC032- codice consolato di residenza  2483705 inesistente sulla tabella di riferimento e
EC033 - codice consolato 2483705 incongruente con codice stato estero 239 di residenza

id operazione ANPR 48920239

potete verificare?
grazie

**Comment by ncapozzi** [comment]
Buongiorno
potete riprovare.

**Comment by INSIEL1** [comment]
grazie Funziona correttamente
