### ISSUE TITLE
[ws P002] Richiesta Dettagli - Errore EN148

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3257]
ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA (037054)

il servizio di richiesta dettagli (P002) per la pratica con id 27352544 restitituisce questo errore
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EN148</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Anonalia risposta P002</testoErroreAnomalia>
	</errore>
</listaErrori>

```

a parte il suggerimento di cambiare il testo in "AnoMalia", vi chiediamo di verificare cosa blocca lo scarico dei dettagli.

grazie
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
gentilmente, servirebbe un riscontro su questa issue per capire - considerati i tempi di scadenza - se c'è tempo di attendere l'intervento ed operare via web-service, oppure dirottare l'operatore sulla gestione della richiesta direttamente dalla web-app.
grazie

**Comment by apaolacci** [comment]
Buongiorno,
abbiamo verificato la segnalazione. Purtroppo per procedere in tempi brevi è meglio gestire la pratica direttamente dalla web-app di anpr.

Nello specifico l'errore è sulla validazione del campo località inserito dal cittadino 'Bologna (Emilia-Romagna)' che contiene caratteri non ammessi.

Saluti,
Assistenza ANPR

**Comment by AMonopoliADS** [comment]
va bene. grazie del riscontro.
avvisiamo il cliente

**Comment by AMonopoliADS** [comment]
scusate... penso ci sia stato un errore nella chiusura di questa issue e nell'attribuzione del tag "chiarimento tecnico"-

il problema non è stato risolto e al momento non è ancora possibile scaricare i dettagli della pratica tramite servizio P002.
se poi non è previsto che venga risolto, allora non avevo capito ed è necessario che avvisiamo il cliente.
fatemi sapere per piacere.

grazie

**Comment by AMonopoliADS** [comment]
la pratica dovrebbe esser stata lavorata tramite webapp per questioni di tempi e non mi risulta si siano verificati altri casi.
il "problema" è che in questo momento nel gestionale mi mancano delle informazioni per gestire/chiudere la pratica e pensavo avremmo potuto allineare la situazione in maniera automatica una volta risolto dalla vostra parte.

"_Potremmo bonificare sul DB la pratica 27352544 ?_"
se questo risolve il problema per me va bene.

"_In futuro, quello che sarebbe possibile fare è non accettare nel campo località inserito dal cittadino i caratteri non ammessi (le parentesi) che portano all'errore in fase di recupero tramite P002._"
contavo sul fatto che avreste proceduto in questo senso con le prossime evolutive.

fatemi sapere se riuscite a bonificare la pratica per completare l'acquisizione dei dettagli.
grazie

**Comment by apaolacci** [comment]
Potreste provare a recuperare la pratica 27352544 tramite ws P002 ? Il dato è stato bonificato per permettervi il test ed la chiusura/gestione per allineamento anche sul vostro gestionale.

A breve ci sarà un rilascio che conterrà l'evolutiva: nel campo località inserito liberamente dal cittadino non sarà permesso di inserire caratteri come _"("_ e _")"_ oppure il _"/"_ che non sono previsti dal _tipoDato.xsd_ che rappresenta lo standard dei WS soap di ANPR.

**Comment by AMonopoliADS** [comment]
il recupero dei dettagli adesso è andato a buon fine.
grazie

**Comment by ncapozzi** [comment]
nel campo località inserito liberamente dal cittadino, la validazione è stata allineata al tipoDato.xsd campo Località
