### ISSUE TITLE
Indicazione Ufficio Atto di Nascita

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#326]
Codogno, ambiente di produzione

Buongiorno,
abbiamo la necessità di registrare un evento riguardante una persona che è nata a Napoli e nell'atto di nascita è indicato come ufficio 'ARENELLA', nell'oggetto ATTO però l'ufficio è massimo di 4 caratteri, come possiamo trasmettere ARENELLA che è l'indicazione corretta dell'ufficio?
Grazie
Luca Bonini

**Comment by gcarbonin** [comment]
Quel campo è nato per contenere un codice che identifica l'ufficio o il municipio e non la localita' dove si trova l'ufficio. Possiamo prevedere una futura evoluzione per ampliare il campo. Per ora l'unico modo è quello di utilizzare il campo localita del comune dell'atto per riportare "ufficio di ARENELLA".

**Comment by niclup** [comment]
La assimilazione dell'ufficio di stato civile alla località comporta intanto un problema di certificazione. Vedo che le carte di identità cartacee emesse dal Comune di Napoli espongono nella descrizione dell'atto di nascita una sigla, probabilmente proveniente dalla voce ufficio, in cui si sottolinea dove è stato redatto l'atto (ad  esempio "AR" per "Arenella"). A questo punto il campo "atto.ufficioMunicipio" andrebbe benissimo per gestire tale sigla, andrebbero forse solo concordati i valori esprimibili, magari col comune di Napoli stesso, onde evitare futuri problemi interpretativi.

**Comment by gcarbonin** [comment]
Il problema è stato risolto ampliando il campo ufficio
