### ISSUE TITLE
Ricezione notifica N015

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3261]
Buonasera, COMUNE DI CASERTA - PROD
Abbiamo ricevuto da altro comune tre notifiche ripristino posizione anagrafica N015 per la stessa persona.
Non é mai pervenuta la notifica N010 emigrazione.
Questa é l'ultima id operazione 837489845  id notifica 837486146  
precedenti id operazione 833211572  id notifica 833204926
id operazione 833212036 id notifica   833206079    
Come é possibile?  
Grazie

**Comment by azabatta** [comment]
Buongiorno,
le mutazioni di residenza sono state annullate subito dopo l'invio della comunicazione pertanto la relativa notifica non è partita.  Il comune di destinazione è stato contattato per verificare che problemi ci sono sul cittadino in trattamento. Il cambio di residenza è stato comunicato nuovamente stamattina e la relativa notifica è stata prodotta ed inviata con esito positivo (N010 con id notifica 839093266).

**Comment by rinonasti** [comment]
VERIFICATO OK grazie
