### ISSUE TITLE
 Errore in iscrizione AIRE Cittadini stessa famiglia #3182 

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3262]
COMUNE DI PANTIGLIATE 
Rif. Nadia Ferrari

Buongiorno con riferimento alla ISSUE in oggetto (#3182), siamo a chiedervi indicazioni in merito alla modalità operativa da utilizzare nella wa per annullare tutte le operazioni eseguite "sui 4 dall'ultima a ritroso fino alla mutazione AIRE inclusa "

di seguito la vostra risposta :+1: 

Buonasera
il problema nasce dal fatto che nelle mutazioni AIRE con cui avete trasferito i cittadini all'estero è stato impostato per tutti "nuova famiglia" e pertanto è stata creata in ANPR una nuova famiglia per ogni cittadino. Questo andava bene solo per l'intestatario della famiglia AIRE mentre per gli altri 4 avreste dovuto indicare l'opzione "famiglia esistente".
Per riunirli dovete annullare tutte le operazioni eseguite sui 4 dall'ultima a ritroso fino alla mutazione AIRE inclusa e poi effettuare nuovamente le mutazioni AIRE in famiglia esistente.

Si resta in attesa di gentile riscontro.

Saluti

**Comment by ncapozzi** [comment]
Contattata la Sig.ra Ferrari e fornita assistenza per annullare le operazioni eseguite dopo il subentro e rieseguire le mutazioni AIRE in famiglia esistente.
