### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by AnnaL58** [italia/anpr#3264]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all'AIRE) non è ancora presente in ANPR (puoi verificarlo utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune );
se il tuo comune è già in ANPR allora c'è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti interessa rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni.

Faccio presente che il Comune di Cassinetta di Lugagnano(MI) è in ANPR dal 05/11/2019.
Ho trovato il Comune di Cassinetta di Lugagnano (MI) e non hanno riscontrato problemi con la scheda anagrafica contatta. 
Cosa devo fare? Il comune non sa come aiutarmi.

**Comment by cmigliardi** [comment]
buongiorno per favore ci può fornire le prime 6 lettere del codice fiscale ? così  controlliamo la scheda in Anpr. grazie

**Comment by AnnaL58** [comment]
Buongiorno, le prime 6 lettere sono : LVTNMR

**Comment by cmigliardi** [comment]
gentile signora in anpr abbiamo la scheda corretta ma con un codice fiscale che  non è lo stesso che ha registrato con spid.  infatti in ag. entrate lei ha 2 codici fiscali collegati  - l'ultimo attribuito termina con la lettere H  invece quello che ha su SPID   termina con la lettera   S .

**Comment by AnnaL58** [comment]
Per un errore anagrafico era stato assegnato un codice fiscale errato con finale S che ad oggi è stato sostituito con quello corretto con finale H. All' INPS risulta corretto l'accesso con finale H ed anche sulla nuova tessera sanitaria.

**Comment by cmigliardi** [comment]
infatti anche in anpr abbiamo quello con la H  - ma lei accede con quello che termina con la S . deve correggere associazione con spid

**Comment by AnnaL58** [comment]
Quindi devo rifare la procedura di accesso spid con il nuovo codice fiscale?

**Comment by cmigliardi** [comment]
non lo so deve sentire il provider che le ha rilasciato spid . credo sia sufficiente una semplice rettifica  di  associazione

**Comment by AnnaL58** [comment]
Quindi dovrei sentire in questo caso PosteID (è il mio provider )per modificare tale dato

**Comment by cmigliardi** [comment]
sì -

**Comment by AnnaL58** [comment]
Daccordo, la ringrazio per la collaborazione. Buona giornata

**Comment by cmigliardi** [comment]
di nulla  buona giornata

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
