### ISSUE TITLE
Errore nel numero totale di comuni transitati in ANPR

### ISSUE THREAD

**Issue by anvalanz** [italia/anpr#3265]
Gentili signori vi segnalo che il sito web riporta 7093 comuni transitati in ANPR 
https://www.anagrafenazionale.interno.it/tutti-i-comuni-italiani-sono-in-anpr/

riporta queste informazioni:

" 7.903!

18 Gennaio 2022
Tutti i Comuni italiani sono in ANPR!

Digitale: tutti i comuni italiani nell’Anagrafe Nazionale

Dalla Sicilia all’Alto Adige, i dati demografici di 67 milioni di italiani sono ora in un’anagrafe unica, sicura e digitale"

mentre dal sito ISTAT i comuni al 01/01/2022 sono 7094 -> https://www.istat.it/it/archivio/6789

".. Nota. Dal 20 febbraio 2021, con l’istituzione del comune di Misiliscemi (TP), il numero dei comuni è pari a 7.904 unità..."

Ho scaricato dal vostro sito il file "report_nazionale.csv" ed i comuni elencati sono 7904, faccio notare però che per il Comune di Misiliscemi (TP) i dati presenti nel csv sono i seguenti

6607	SICILIA	TP	MISILISCEMI	0	NULL	NULL	NULL

ossia il comune risulta non transitato in ANPR.

Sarebbe opportuno correggere l'informazione relativa a tale comune per una corretta informazione ai cittadini e di conseguenza la pagina web con il totale dei comuni transitati per una corretta informazione ai cittadini.

**Comment by FilippoPapi** [comment]
su richiesta del comune MISILISCEMI sarà attivo in ANPR dal primo aprile pv

**Comment by anvalanz** [comment]
Grazie per la sollecita risposta.

Da nessuna parte era indicato il transito programmato in ANPR per il 1°
aprile.


Antonio Valanzano

Il Mer 30 Mar 2022, 14:35 FilippoPapi ***@***.***> ha scritto:
