### ISSUE TITLE
5005 - nuova famiglia con 2 soggetti da stesso comune ANPR, di famiglie diverse

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#327]
Buongiorno. Ambiente di test id operazione 587054.
Al nostro sportello ci sono due persone provenienti dallo stesso comune ANPR  X, ma lì residenti in due famiglie anagrafiche diverse.  Chiedono l'iscrizione in una nuova famiglia di questo comune.
Siccome la pratica di iscrizione è una sola, richiamiamo una volta sola il servizio indicando in < elencoSoggettiFamiglia > entrambi i soggetti che dichiarano la residenza.
Riceviamo EF054
_I soggetti devono appartenere alla stessa famiglia_
Si tratta di bug, o è voluto che le chiamate devono essere singole? Ma in questo caso non capisco bene l'array < elencoSoggettiFamiglia >.

**Comment by gcarbonin** [comment]
Non si tratta di un bug : i soggetti devono appartenere allo stesso nucleo famigliare. Si utilizza questo servizio quando, ad esempio, due persone di una famiglia danno origine ad un nuovo nucleo famigliare o entrano a fare parte di una famiglia diversa già esistente. nel suo caso deve chiamare due volte il servizio
