### ISSUE TITLE
Errore durante autenticazione SPID

### ISSUE THREAD

**Issue by dado728** [italia/anpr#3270]
Salve,
sono un cittadino e non riesco ad accedere con SPID al portale del cittadino. Quando scelgo PosteID ottengo questo errore.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Internal Error (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>

Ho provato anche altri metodi ma l'errore è sempre lo stesso
Ho provato da Chrome, Edge e Internet explorer e con più di un terminale ma il risultato è sempre lo stesso

**Comment by pietrodaddabbo** [comment]
Salve,
stesso errore per me. 
Aggiungo che l'errore i presenta anche provando a selezionare dal menu' a tendina altri provider fra quelli che forniscono SPID.

**Comment by FilippoPapi** [comment]
buonasera abbiamo un problema al Ced. il servizio sarà ripristinato il prima possibile

**Comment by cicognanid** [comment]
Buonasera,
anch'io da oggi pomeriggio riscontro lo stesso errore.
Aggiungo che l'errore si presenta anche provando a selezionare dal menu' a tendina altri provider fra quelli che forniscono SPID.
Ho provato anche altri metodi ma l'errore è sempre lo stesso.
Ho provato da Chrome, Edge e Internet explorer e con più di un terminale ma il risultato è sempre lo stesso.
In quanto tempo riuscite a risolvere il problema per poter usufruire del servizio ?

**Comment by pietrodaddabbo** [comment]
Confermo che il servizio é tornato regolare. 
Grazie per l'assistenza.

**Comment by dado728** [comment]
Confermo anch'io grazie mille!
