### ISSUE TITLE
Servizi ANPR non funzionanti

### ISSUE THREAD

**Issue by spedrini** [italia/anpr#3272]
Buongiorno, 
da ieri sera non riusciamo più ad utilizzare i servizi ANPR in ambiente di test.
L'errore è questo: 
javax.xml.ws.soap.SOAPFaultException: Rejected by policy. 

Potete verificare?
Grazie

**Comment by INSIEL1** [comment]
anche noi non riusciamo piu' ad accedere (Insiel FVG)

**Comment by ncapozzi** [comment]
Gli ambienti sono stati ripristinati
