### ISSUE TITLE
Impossibile svuotare campo "atto di nascita" da dati errati senza inserirne nuovi

### ISSUE THREAD

**Issue by vs691** [italia/anpr#3275]
Buongiorno, problema in oggetto al comune di Policoro produzione. 
Nel campo atto di nascita sono stati inseriti da subentro dei dati errati(il comune non ha a disposizione i dati dell'atto di nascita). Sul cittadino è stata fatta l'operazione di allineamento codici fiscali in agenzia delle entrate e ciò non consente di "pulire" il campo atto di nascita utilizzando l'eliminazione dati subentro errore materiale. Non è possibile nemmeno l'operazione Mutazione tutti i dati, poiché non abbiamo dati da correggere, ma campi da lasciare vuoti. 
Come è possibile procedere? soggetto 213484565

Grazie mille e buon lavoro

**Comment by frmariani** [comment]
L'operazione effettuata sul cittadino non è un allineamento ma una vera e propria modifica del codice fiscale e tale operazione non è annullabile.
Per eliminare un dato inviato erroneamente da subentro non devono essere state effettuate operazioni sul soggetto; se effettuate, queste devono essere annullate. La modifica di un dato così importante sul cittadino, presuppone un controllo approfondito su tutti i dati già presenti dello stesso,  pertanto l'operazione di modifica dei dati anagrafici non è annullabile.
A questo punto l'unica possibilità è quella di agire direttamente sui dati a livello centrale; tale operazione effettuata in via del tutto eccezionale e solo se effettivamente indispensabile deve essere supportata da una richiesta ufficiale del comune inviata via PEC dallo stesso. Il comune mi scriva in privato frmariani@sogei.it

**Comment by frmariani** [comment]
non ho ricevuto nessuna mail: posso chiudere la issue ?

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 13/04/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Impossibile svuotare campo "atto di nascita" da dati errati senza inserirne
nuovi (Issue #3275)" inviata il 07/04/2022 16:49:49.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
