### ISSUE TITLE
Padre adottante il figlio della moglie

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3276]
Comune di Prato, Nozzoli Arianna Istruttore Informatico

Buongiorno,
abbiamo un minore riconosciuto alla nascita dalla sola madre.
Dopo alcuni anni la madre del bimbo si sposa con il nuovo compagno.
Il marito diventa adottante del bimbo minore della moglie.
In ANPR non "transita" l'informazione che il bimbo ha un padre ma risulta ancora solo figlio della madre.
Anni fa ci fu detto da SOGEI che questa informazione non era necessaria in ANPR però il padre dice di avere problemi burocratici per questa mancata informazione, anche perchè lui è giuridicamente a tutti gli effetti il padre del bambino.
E' ancora ritenuta una informazione da non ufficializzare?
Grazie

**Comment by rvinzani** [comment]
Salve, in ANPR è possibile aggiungere anche gli estremi del padre adottivo. Quando dice transita cosa intende? Dal gestionale? Dallo stato civile?

**Comment by anozzoli** [comment]
Ero rimasta a questa vostra comunicazione :

**Oggetto: R: Comune di PRATO in ANPR - Richieste in sospeso
Data: Thu, 11 Apr 2019 13:52:28 +0000
Mittente: no-reply.anpr <[no-reply.anpr@sogei.it](mailto:no-reply.anpr@sogei.it)>
A: Arianna Nozzoli <[a.nozzoli@comune.prato.it](mailto:a.nozzoli@comune.prato.it)>

Oggetto: COMUNE DI PRATO PADRE ADOTTIVO PER xxxx xxxx

Anpr non prevede una sezione per il padre adottivo perché essendo un dato sensibile soggetto a privacy - non deve essere registrato per non dar modo a possibili collegamenti a protezione del minore**

Evidentemente sono cambiate le disposizioni quindi mi rivolgo alla maggioli per informazioni in merito perchè è stato registrato un padre adottante nella nostra banca dati ma non è transitato in ANPR. Grazie

**Comment by rvinzani** [comment]
Questa che mi è stata presentata è un fattispecie diversa. Le nostre indicazioni sono mirate a non collegare i dati anagrafici del soggetto prima dell'adozione e dopo l'adozione quando i genitori naturali ed adottivi sono differenti. Questo è un caso diverso. Non mi sembra che il dato debba essere protetto. Ovviamente queste sono considerazioni tecniche date da una conoscenza superficiale del problema. Detto però che ANPR consente di acquisire il dato, sta a voi stabilire se sia un dato sensibile da poter esporre o meno.
Chiudo la issue. In caso fosse necessario un maggiore approfondimento le chiedo di aprire una nuova issue che faccia riferimento a questa
