### ISSUE TITLE
Mutazione famiglia/convivenza AIRE - Errore EN526 

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3277]
Comune di ANDORA ambiente di PRODUZIONE.

Buongiorno.
Per il soggetto AIRE  con id ANPR 37442523 si invia mutazione famiglia/convivenza per rettifica consolato di riferimento.
Si riceve:
EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 18-06-1999 - Id Famiglia/Convivenza ANPR: 21314354 
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-03-31 16:31:31 , idOperazioneANPR 839797111 - Id Famiglia/Convivenza ANPR: 21314354  

Poco prima si è inviata una rettifica dati (data decorrenza residenza) in quanto errata: da 18.06.1999 al 06.07.2004
Il soggetto infatti è in AIRE dal 1806.1999, ma all'indirizzo presente in ANPR dal  06.07.2004.

Come si può procedere per inviare tale mutazione?

Sin ringrazia anticipatamente
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno
prima dovete effettuare anche la rettifica della data appartenenza alla famiglia.

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
La data di appartenenza alla famiglia è però corretta.
Il soggetto è stato iscritto in AIRE IL 18.06.1999 ad un certo indirizzo. Il 18.06.1999 rappresenta la dta di costituzione della famiglia ed anche il suo ingresso in famiglia.

In seguito ha cambiato solo indirizzo, in data 06.07.2004 , ma la famiglia è rimasta la stessa.

Perché si dovrebbe rettificare la data di ingresso in famiglia?

Si ringnrazia anticipatamente.
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno,
potete provare per favore a ripetere la mutazione famiglia/convivenza per rettifica consolato di riferimento?

**Comment by CIVILIANEXT001** [comment]
La mutazione è stata inviata senza ulteriori errori.

Grazie
G. Trisolini

**Comment by CIVILIANEXT001** [comment]
Problema risolto.

Grazie.
G. Trisolini
