### ISSUE TITLE
Accesso area cittadini di test ERRORE

### ISSUE THREAD

**Issue by spedrini** [italia/anpr#3278]
Buongiorno, 
da ieri non riusciamo ad accedere all'area dei cittadini di test che ci avete fornito, all'indirizzo https://dptest3.anpr.interno.it/cns.
Potete verificare?

Grazie
(Maggioli)

**Comment by MoniaPedrazzoli** [comment]
Buongiorno,

anche noi abbiamo problemi ad accedere al portale di test dei servizi al cittadino (https://dptest3.anpr.interno.it/cns), dopo la selezione del certificato viene mostrato questo messaggio:

Si e' verificato un errore durante la fase di autenticazione
Il certificato utilizzato non è stato riconosciuto
come valido

Potete controllare?
Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by LSPAG** [comment]
Buongiorno,

anche noi abbiamo lo stesso problema.

Saluti Laboratorio Dedagroup

**Comment by spedrini** [comment]
Buongiorno, 
riuscite a dirci se il problema verrà risolto a breve?

Grazie
Maggioli SPA

**Comment by apaolacci** [comment]
Buongiorno,
siete riusciti ad entrare senza errori o i problemi non sono risolti? 

Grazie

**Comment by MoniaPedrazzoli** [comment]
Noi siamo riusciti ad entrare senza errori, grazie.

**Comment by LSPAG** [comment]
Adesso funziona, grazie...

**Comment by spedrini** [comment]
E' tornato a funzionare.
Grazie

**Comment by gppbarone** [comment]
Chiudiamo la issue, l'ambiente è tornato disponibile.

Grazie
