### ISSUE TITLE
[Test Subentro] Cittadino irreperibile

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#328]
Un cittadino residente che risulta nella condizione di "irreperibile", come va mappato nel file del subentro?
Non trovo nessun attributo nelle specifiche ANPR che possa corrispondere a questa condizione.
Ci sarebbe "SenzaFissaDimora" ma non credo sia la stessa cosa.
Potreste darmi qualche indicazione, sempre che questo tipo di dato sia da includere.
Grazie

Bistagno (AL)  Codice ISTAT: 006017
Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
"Irreperibile" non è un attributo della persona come "senza fissa dimora": se la irreperibilità è stata accertata, il soggetto deve essere cancellato e non trasmesso al subentro; se il procedimento è in corso, va trasmesso come un qualsiasi altro residente e il comune dovrebbe comunicare il procedimento (a subentro avvenuto),
