### ISSUE TITLE
Dichiarazioni cambio residenza

### ISSUE THREAD

**Issue by cristinapezzolesi** [italia/anpr#3282]
Vorrei sapere fra quanto tempo è prevista l'estensione del servizio di dichiarazione di cambio residenza dal portale ANPR a tutti gli altri comuni. Sarà estesa tale possibilità a tutti presto o si procederà progressivamente in base al numero di abitanti o ad altri criteri? È possibile proporre il proprio comune per l'attivazione di questo servizio da ANPR?

**Comment by ncapozzi** [comment]
Buongiorno
la data prevista per l'estensione del servizio a tutti i Comuni è il prossimo 27 aprile
