### ISSUE TITLE
Come effettuare step back per ripristino posizione anagrafica a seguito errata cancellazione per doppia iscrizione

### ISSUE THREAD

**Issue by maurorapetti1964** [italia/anpr#3283]
--- PASSI OPERATIVI PER RIPRISTINO POSIZIONE ANGRAFICA ---

Chiedo cortesemente di sapere se l'applicativo Sicra WEB (prima SAGA ora SAGA GRUPPO MAGGIOLI) consente di eseguire a ritroso l'annullamento delle operazioni compiute su un determinato record al fine di ripristinare la posizione anagrafica a seguito di errata cancellazione per doppia iscrizione.

COMUNE di TORGIANO

Mauro RAPETTI

**Comment by frmariani** [comment]
la domanda deve essere rivolta alla casa software

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
