### ISSUE TITLE
Buongiorno, non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.  Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:  Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune); se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.  Faccio presente che il Comune di POTENZA PICENA (MC) è in ANPR. Cosa devo fare? 

### ISSUE THREAD

**Issue by PCCGTN** [italia/anpr#3287]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by cmigliardi** [comment]
buongiorno  per favore ci può fornire le prime 6 o 7 elementi del suo codice fiscale ? grazie

**Comment by cmigliardi** [comment]
non ho avuto risposta 
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
