### ISSUE TITLE
Anomalia nei dati, impossibile identificare in modo univoco 

### ISSUE THREAD

**Issue by GiancarloBongiovanni** [italia/anpr#3289]
Buongiorno,
mio figlio ha avuto il seguente problema: dopo l'accesso con SPID, il sistema ANPR ha restituito un messaggio di errore in cui era contenuta questa parte:

"c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni."

Preciso che il codice fiscale è corretto (infatti con SPID lui entra senza problemi nel sito di Agenzia delle entrate).

Le prime 6 lettere del suo CF sono "BNGFPP" ed il comune di residenza e' Roma.

Potete aiutarci?

Grazie e cordiali saluti

**Comment by mttfranci** [comment]
Salve, prima di effettuare ulteriori indagini, potreste riprovare l'accesso?
Grazie in anticipo.

**Comment by GiancarloBongiovanni** [comment]
Purtroppo non a breve, mio figlio era passato da noi e ne ho approfittato per provare con lui l'accesso ad ANPR ma non so quando ripasserà nuovamente.

Appena possibile riproveremo.

Grazie comunque e cordiali saluti

**Comment by mttfranci** [comment]
Va bene, grazie, rimaniamo in attesa.
Saluti
