### ISSUE TITLE
Ambiente di presubentro : Errore 999 in iscrizione 1002 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#329]
Buongiorno

nell'ambiente di presubentro di Poggio a Caiano stiamo testando alcune chiamate al servizio 1002.
Veniamo però fermati dall'errore 999 : operazione non effettuabile.
Una operazione di questo tipo è ad es la ANPR ID 277976

Potete aiutarci ad individuare il problema ?

Grazie

**Comment by mttfranci** [comment]
Ieri pomeriggio abbiamo corretto una piccola anomalia.
Ci risulta che la stessa iscrizione sia andata a buon fine oggi con l'id ANPR dell'operazione : 278472 e ora il soggetto risulta iscritto con id ANPR 20455913.

**Comment by busaster** [comment]
confermo, abbiamo riprovato stamattina ed è andata a buon fine.
Chiudo la issue
grazie
