### ISSUE TITLE
Problemi di accesso tramite SPID

### ISSUE THREAD

**Issue by Reichsfuhrer** [italia/anpr#3290]
E per la prima volta che accedo su questo sito per ottenere alcuni certificati.
Ho fatto l`accesso tramite SPID (PosteID) e mi da un errore:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

![Untitled](https://user-images.githubusercontent.com/83301207/161649716-a9c4e117-b01e-4eed-a2af-a7cf494fc9d1.png)

**Comment by Reichsfuhrer** [comment]
Ho provato più di una volta durante il giorno e non cambia nulla.

**Comment by cmigliardi** [comment]
buongiorno per favore ci può fornire le prime 6   lettere del codice fiscale ? grazie

**Comment by Reichsfuhrer** [comment]
> buongiorno per favore ci può fornire le prime 6 lettere del codice fiscale ? grazie

Accedo ovunque usando SPID di PosteID, quindi tutto dovrebbe funzionare.
Ho controllato il codice fiscale sul sito SPID e sulla vera tessera elettronica, i dati corrispondono:

**FDRMSY**

**Comment by Reichsfuhrer** [comment]
> se è lei la persona nata nel 99 - le comunico che deve rivolgersi al suo comune di competenza Trevi nel Lazio poiché in anpr la scheda non è presente. spero di esserle stata di ausilio

Ma per il calcolo si prende n. carte d'identità?
Perché sono residente a Roma nel V municipio, ma non ho ancora rinnovato la carta d'identità con il nuovo indirizzo, e i dati con comune e residenza vecchia sono rimaste allegate alla posteID SPID.

**Comment by cmigliardi** [comment]
no  la carta di identità non c'entra nulla con il codice fiscale .  se però lei ha cambiato città e ora è a Roma  , Roma deve registrarla dentro anpr .. poi potrà accedere con spid.

**Comment by Reichsfuhrer** [comment]
Quindi devo andare al municipio dove sono residente?

**Comment by cmigliardi** [comment]
si
