### ISSUE TITLE
Mutazione famiglia/convivenza AIRE - Errore EN526

### ISSUE THREAD

**Issue by mrabuano** [italia/anpr#3291]
Aosta produzione 
come per la issue #3277 per tre famiglie abbiamo lo stesso problema 
1)
individuo con id anpr 43770680 ha data decorrenza residenza giustamente 15/07/2015 (rettificata) e data appartenenza in famiglia correttamente 23/04/2009 nel tentativo di inviare la mutazione famiglia per aggiornare il Consolato impostando quello di Arona si riceve : 
1 Errore Anpr Cod: EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 20-04-2009 - Id Famiglia/Convivenza ANPR: 24731417 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-05 11:42:01 , idOperazioneANPR 844420735 - Id Famiglia/Convivenza ANPR: 24731417 Id Famiglia/Convivenza Comune: -

2)
individuo con id anpr 43770354 ha data decorrenza residenza giustamente 18/05/2018 (rettificata) e data appartenenza in famiglia correttamente 10/10/1991 nel tentativo di inviare la mutazione famiglia per aggiornare il Consolato impostando quello di Arona si riceve : 
1 Errore Anpr Cod: EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 10-10-1991 - Id Famiglia/Convivenza ANPR: 24730970 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-05 11:51:09 , idOperazioneANPR 844441571 - Id Famiglia/Convivenza ANPR: 24730970 Id Famiglia/Convivenza Comune: -

3)
individuo con id anpr 43769677 ha data decorrenza residenza giustamente 04/05/2017 (rettificata) e data appartenenza in famiglia correttamente 24/12/2015 nel tentativo di inviare la mutazione famiglia per aggiornare il Consolato impostando quello di Arona si riceve : 
1 Errore Anpr Cod: EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 24-12-2015 - Id Famiglia/Convivenza ANPR: 24731740 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-05 11:56:47 , idOperazioneANPR 844455795 - Id Famiglia/Convivenza ANPR: 24731740 Id Famiglia/Convivenza Comune: -

**Comment by ncapozzi** [comment]
Buonasera
1) la rettifica/integrazione indirizzo vale per tutta la famiglia quindi, nel caso in cui la data decorrenza sia diversa per i 3 componenti della famiglia, deve essere effettuata alla data decorrenza più vecchia che nel caso specifico è 20-04-2009 come indicato nel messaggio

2) individuo con id anpr 43770354 ha data decorrenza residenza 10/10/1991 in ANPR, dopo il subentro non c'è stata nessuna rettifica a 18/05/2018

3) come al punto 2.  individuo con id anpr  43769677 ha data decorrenza residenza 24/12/2015 in ANPR, dopo il subentro non c'è stata nessuna rettifica a 04/05/2017
