### ISSUE TITLE
Problema accesso ambiente di TEST Richieste cambio residenza

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3292]
Buongiorno

da qualche giorno non riusciamo ad accedere all'ambiente di test delle Richieste di residenza. 
Nei giorni scorsi gli errori  sono stati diversi; oggi si presenta questo:

![image](https://user-images.githubusercontent.com/25926460/161917941-d0b572de-c3f8-4470-99e3-33ec90266332.png)

I codici fiscali sono quelli  di test comunicati a suo tempo
MNGDMN
MLNCCC
e così i certificati.

Potreste aiutarci a risolvere il problema? 
Grazie
 
_Raffaella Tremolada_
IBM Sistemi Informativi per Comune di Milano

**Comment by Antonino09** [comment]
Buongiorno,
anche noi riscontriamo lo stesso problema.

Grazie
GolemSoftware

**Comment by LSPAG** [comment]
Buongiorno,
anche noi riscontriamo lo stesso problema.

Grazie
Laboratorio Dedagroup

**Comment by siscomanpr** [comment]
Buongiorno,
anche noi riscontriamo lo stesso problema.

Grazie
Siscom spa

**Comment by apaolacci** [comment]
Buongiorno,
abbiamo fatto delle verifiche, adesso non dovreste più problemi di accesso lato Cittadino.

**Comment by ANPRCdMI** [comment]
Confermo che riusciamo di nuovo ad accedere. Grazie

_Raffaella Tremolada_
IBM Sistemi Informativi per Comune di Milano

**Comment by LSPAG** [comment]
Adesso funziona grazie..

**Comment by Antonino09** [comment]
Adesso funziona.

Grazie
GolemSoftware
