### ISSUE TITLE
Allineamento CF con Agenzia delle Entrate

### ISSUE THREAD

**Issue by czxanpr** [italia/anpr#3293]
Salve,
non si riesce ad allineare il Codice Fiscale di un soggetto iscritto in ANPR con un codice fiscale provvisorio (00653093690) con il codice fiscale presente all'Agenzia delle Entrate (MLTSFM17L65C352F) che risulta validato e marcato in anpr.

Comune di Catanzaro
Bianco Filippo

![Immagine 2022-04-06 123403](https://user-images.githubusercontent.com/94049751/161954782-1573ab52-d23d-441d-bc01-d23d9bede489.png)

**Comment by rvinzani** [comment]
I due codici fiscali sono già collegati. Deve effettuare una mutazione tutti i dati sostituendo sia il codice fiscale numerico con l'alfanumerico ed il nome. Attendo esito

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Allineamento CF con Agenzia delle Entrate (Issue #3293)" inviata il
01/06/2022 15:35:07.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
