### ISSUE TITLE
P002 dettaglio - Problema nel contenuto del Riepilogo richiesta e degli allegati

### ISSUE THREAD

**Issue by gborselli** [italia/anpr#3295]
Salve,
sto testando i servizi Richieste P000.
Ho un problema nella funzione dettaglio:
il contenuto del riepilogo richiesta e degli allegati è vuoto. 
Nel riepilogo richiesta è presente solo idFormatoFile = 1 (pdf).
Mentre negli allegati sono valorizzati solo idTipologia, nomeFile, idFormatoFile e descrizione.
L'oggetto RispostaP002 restituito dalla chiamata al ws, nei campi "contenuto" contiene un array di byte vuoto.

Sapreste dirmi se da parte vostra l'xml di risposta nei campi "contenuto" è presente l'array di byte?

Sono in ambiente di test, questo è l'xml di richiesta:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>57746</idOperazioneComune>
        <codMittente>039002</codMittente>
        <operazioneRichiesta>P002</operazioneRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <dataDecorrenza>2022-04-05</dataDecorrenza>
    </testataRichiesta>
	<criteriRicerca>
		<codiceRichiesta>1250268</codiceRichiesta>
	</criteriRicerca>
</ns2:RichiestaP002>
```

grazie
gianfranco

**Comment by apaolacci** [comment]
Buongiorno,
allego l'xml di risposta alla richiesta identificata da _idOperazioneComune=57746_  [response_57746.txt](https://github.com/italia/anpr/files/8442786/response_57746.txt)

```
      <riepilogoRichiesta>
		<idFormatoFile>1</idFormatoFile>
		<contenuto>JVBERi0xLjQK....</contenuto>
	</riepilogoRichiesta>
	<allegati>
		<allegato>
			<idTipologia>99</idTipologia>
			<nomeFile>TestAllegato.pdf</nomeFile>
			<idFormatoFile>1</idFormatoFile>
			<descrizione>Contratto Locazione</descrizione>
			<contenuto>JVBERi0xLjcNCiW...</contenuto>
		</allegato>
	</allegati>
```
Nel riepilogo _idFormatoFile=1_ identifica il formato pdf del riepilogo (come da tabella di decodifica 51 recuperabile al link https://www.anagrafenazionale.interno.it/il-progetto/strumenti-di-lavoro/tabelle-decodifica/ oppure tramite webservice 7001)

Negli allegati _idTipologia=99_  identifica un generico allegato come da tabella di decodifica 52
nomeFile=il nome completo del file allegato in fase di upload dal cittadino
_idFormatoFile=1_ identifica il formato pdf del file allegato
descrizione=la descrizione testuale dell'allegato inserita in fase di upload dal cittadino

Per entrambi il campo _contenuto_ non dovrebbe essere mai vuoto ma contenere il file codificato in base64.

Saluti,
Assistenza ANPR
