### ISSUE TITLE
RIF: Padre adottante il figlio della moglie #3276

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3297]
Comune di Prato Nozzoli Arianna Istruttore Informatico

Dove trovo il campo sul portale ANPR dove registrare il padre adottante il figlio della moglie?
Grazie

**Comment by rvinzani** [comment]
Non esiste questa distinzione in ANPR. E' previsto un padre ed una madre sia che si tratti di genitori adottivi che naturali.
Nel caso debbano essere presenti entrambi non è previsto che registrarli entrambi

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 13/04/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
RIF: Padre adottante il figlio della moglie #3276 (Issue #3297)" inviata il
07/04/2022 20:20:49.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by anozzoli** [comment]
Il responsabile di anagrafe e la responsabile di stato civile formalizzeranno una richiesta di parere ad Anusca in merito all'aggiunta dell'informazione su ANPR
