### ISSUE TITLE
Amomalia Certificato anagrafico nascita no disponibile

### ISSUE THREAD

**Issue by Ronaldoximenes81** [italia/anpr#3298]
Ho bisogno di aiuto.  Non capisco perché il mio certificato di nascita non sia disponibile nel menu.  vedendo le informazioni in anpr i dati di trascrizione vengono pubblicati lì. Sono italiano residente al estero.  mia sorella, residente allestero, che disponibili, io no.  Qualcuno può aiutarmi?

![Screenshot_20220407-081121_Gallery](https://user-images.githubusercontent.com/100818268/162187361-c03aa924-d6f4-4d0f-a33b-b99ee5b1d76f.jpg)

**Comment by Ronaldoximenes81** [comment]
@mttfranci help

**Comment by Ronaldoximenes81** [comment]
@cmigliardi please

**Comment by Ronaldoximenes81** [comment]
@mamatteo @cmigliardi

**Comment by mttfranci** [comment]
Salve @Ronaldoximenes81, il rilascio del certificato di nascita ai cittadini AIRE è consentito in ANPR solo se nati in Italia. 
Siamo a disposizione per ogni ulteriore chiarimentop
Saluti

Assistenza ANPR

**Comment by Ronaldoximenes81** [comment]
@mamatteo grazie per aver risposto.  tuttavia mia sorella e mio fratello che sono anche come me cittadino italiano non nato in Italia hanno l'opzione dell'anagrafico de nascita.  non il certificato di nascita con il nome dei genitori, ecc., ma un certificato con i dettagli anagrafici della trascrizione.  Nel loro anpr hai questa opzione, nel mio no. Alegato mia sorella.
![Screenshot_20220310-101000_Samsung Internet](https://user-images.githubusercontent.com/100818268/162642496-379fb118-0dc3-471c-8c3c-43e6955f67a7.jpg)

**Comment by Ronaldoximenes81** [comment]
@mamatteo @mttfranci

**Comment by mttfranci** [comment]
Buongiorno, può fornire il suo codice identificativo ANPR che trova nella sezione Generalità della visura?
Grazie in anticipo.

**Comment by Ronaldoximenes81** [comment]
@mttfranci 265417152 ... grazie

**Comment by mttfranci** [comment]
Abbiamo verificato che sua sorella in ANPR è stata registrata come nata in un comune italiano e non all'estero. Per questo il certificato anagrafico di nascita risulta disponibile. Può verificare facendo accesso al portale. Qualora il luogo di nascita dovesse essere errato può segnalare l’errore al comune di iscrizione AIRE.
Saluti

**Comment by Ronaldoximenes81** [comment]
@mttfranci grazie,  questo è esattamente il motivo.  Ora analizzando io sono iscritto come nata in Brasile, lei in BS, riferendosi al Brasile, ma quella potrebbe essere Brescia per il sistema.  Grazie per il chiarimento.  Ti chiederò di aggiornare la sua.  Pertanto, per i cittadini italiani nati all'estero, l'anagrafia di nascita non è disponibile, giusto?

**Comment by mttfranci** [comment]
Esatto, non è disponibile. Come scritto in precedenza.
Per ogni eventuale correzione dovreste rivolgervi al comune competente.
Saluti

**Comment by mttfranci** [comment]
Salve, cortesemente potrebbe fornirci il suo codice identificativo ANPR, disponibile nella sezione Generalità dell'area Visua e autocertificazioni? (Non si tratta di un dato particolarmente sensibile, ma ci aiuterebbe nella verifica)
Grazie in anticipo.
Saluti

![image](https://user-images.githubusercontent.com/29305782/166551127-e16302c2-784a-4345-b641-5bbe136f2f9a.png)

**Comment by Ronaldoximenes81** [comment]
@mttfranci 265417152
