### ISSUE TITLE
Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)

### ISSUE THREAD

**Issue by maumarc64** [italia/anpr#3299]
Per l' ID ANPR 292413015 (nuovo nato) è stata erroneamente inviata ad ANPR comunicazione con luogo nascita errato con conseguente validazione errata del codice fiscale: lo stesso è stato poi annullato e nuovamente richiesto con i dati corretti direttamente su punto fisco.
Entrando in ANPR modalità web service e cercando di operare l'allineamento ANPR/AE, scegliendo i dati AE, compare il messaggio:

Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: 12)

La soluzione proposta (paragrafo 4.1 della guida ANPR di risoluzione disallineamenti con AE) una volta applicata
fornisce gli esiti:

- Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)

- Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-07 13:23:28 , idOperazioneANPR 847200864 (Codice: EN527)

Come risolvere?

Grazie.

Maurizio Marchese-Anagrafe Comune di Muggiò (MB) subentrato il 31-03-2021

**Comment by rvinzani** [comment]
Gent.le Sig. Marchese, seguiremo il suo caso con il ticket assistenza 24003518. Per le successive volte le chiederei di contattare direttamente il nostro servizio di assistenza al n. 800863116 per casistiche specifiche come questa
