### ISSUE TITLE
Web- App REGISTRAZIONE Data di decorrenza non valorizzata correttamente

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#33]
Data test- 15/03/2017 - Ambiente test (dptest)
Richiamando le funzionalità di REGISTRAZIONE (sia per tipo Operazione = Mutazione Famiglia-Convivenza ma supponiamo si presenti anche negli altri casi..) nella scheda  DATI DELL'OPERAZIONE nei "Dati della registrazione anagrafica" il campo Data di decorrenza è sempre erroneamente valorizzato con la sysdate invece deve riportare la data di ingresso in famiglia come riportato nella scheda Famiglia convivenza della scheda del soggetto.
Nella scheda RESIDENZA - Data di decorrenza della residenza è valorizzata correttamente.
Se l'utente non modifica la Data di decorrenza   con il dato corretto il sistema dà errore "La data decorrenza della residenza deve essere uguale alla data decorrenza della richiesta (Codice: EN239)"

Grazie
Annamaria Gillone - Comune di Torino

**Comment by annamariaGillone** [comment]
Non mi è chiaro se il chiarimento tecnico debba essere fornito da noi .. grazie

**Comment by gcarbonin** [comment]
Chiarimento tecnico è solo una classificazione del tipo di problema.
La data di decorrenza coincide di norma con la data della dichiarazione anagrafica che ANPR non conosce; viene , quindi, valorizzata con la data di sistema, modificabile da parte del comune sulla base della data effettiva della dichiarazione.  Possiamo anche non valorizzarla lasciandola vuota ma cambierebbe soltanto il messaggio.

**Comment by annamariaGillone** [comment]
va bene. Grazie
