### ISSUE TITLE
[5005-5008] chiarimento su  idSchedaSoggettoComune

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#330]
Ambiente di test. Mutazione residenza  di cittadino iscritto in altro comune ANPR.
Quale è la procedura esatta per attribuire la nostra matricola anagrafica a un cittadino già residente ANPR?

Nell'effettuare la chiamata 5005, dobbiamo obbligatoriamente identificare il soggetto solo con questi campi:
< elencoSoggettiFamiglia >
< generalita >
< cognome > C.. < / cognome >
< nome >L...< / nome >
**< idSchedaSoggettoANPR >2173656< / idSchedaSoggettoANPR >**
< / generalita >

senza poter indicare la nostra matricola anagrafica (ovviamente diversa da quella presente nell'altro comune)  nell'attributo < idSchedaSoggetto >
Qualora tento una chiamata 5008, per attribuirlo successivamente ricevo un errore EAV91 Soggetto non presente in Agenzia Entrate. < idOperazioneANPR >588559

**Comment by azabatta** [comment]
La sequenza delle operazioni eseguite è corretta. 
Nel caso specifico poiché il cittadino non  risulta presente in Agenzia Entrate (nell’ambiente di test di Agenzia Entrate) nell’utilizzo del servizio 5008 è necessario aggiungere tra i dati di controllo il parametro “gestioneCF”  valorizzato con il codice 3 (mutazione senza controllo CF). 
A titolo di esempio, si riporta di seguito la sezione “datiControllo” delle richiesta cui  si fa riferimento, integrata con tale parametro:  

<datiControllo>
        <tipoMutazione>01</tipoMutazione>
        <tipoMutazione>15</tipoMutazione>
        <gestioneCF>3</gestioneCF>
    </datiControllo>
