### ISSUE TITLE
Mutazione famiglia/convivenza - EN526

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3301]
Comune di ANDORA ambiente di PRODUZIONE.
Stesso problema segnalato nella issue #3277

Buongiorno.
Per il soggetto AIRE con id ANPR 37442508 si invia mutazione famiglia/convivenza per rettifica consolato di riferimento.
Si riceve:
EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 27-07-1995 - Id Famiglia/Convivenza ANPR: 21314378 Id Famiglia/Convivenza Comune: -
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-07 16:20:02 , idOperazioneANPR 847439197 - Id Famiglia/Convivenza ANPR: 21314378 Id Famiglia/Convivenza Comune: Poco prima si è inviata una rettifica dati (data decorrenza residenza) in quanto errata: da 18.06.1999 al 06.07.2004

Il soggetto infatti è in AIRE dal 27.07.1995, ma all'indirizzo presente in ANPR solo dal 28.06.2016.
Si segnala che la famiglia è composta da 3 persone che hanno avuto gli stessi movimenti AIRE del soggetto sopra indicato.

Come si può procedere per inviare tale mutazione?

Sin ringrazia anticipatamente
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno
potete riprovare per favore?

**Comment by CIVILIANEXT001** [comment]
Problema risolto.
Grazie

G. Trisolini
