### ISSUE TITLE
RICHIESTE P001

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3302]
Buonasera,
Nell'inviare richieste P001 in ambiente TEST (sia TIPOLOGIA 1 CHE 2)
il criterio di ricerca idStatoRichiesta è ancora obbligatorio.

Grazie

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 13/04/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
RICHIESTE P001 (Issue #3302)" inviata il 07/04/2022 19:57:00.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by apaolacci** [comment]
Buongiorno,
è possibile ottenere tutte le pratiche inviate al comune, senza tener conto dell'indicazione del filtro sullo stato corrente della pratica inviando il parametro _idStatoRichiesta_ vuoto.
E' sempre necessario ed obbligatorio inviare la tipologia  di richiesta _idTipologia_ (cambio residenza, rettifica dati, ...) per ottenere l'elenco pratiche di quelle arrivate nell'intervallo temporale.
Il range temporale di interrogazione è stato aumentato a 30gg.

```
<criteriRicerca>
	    <dataIniziale>2022-04-01</dataIniziale>
	    <dataFinale>2022-04-15</dataFinale>
	    <idTipologia>2</idTipologia>
	    <idStatoRichiesta></idStatoRichiesta>
</criteriRicerca>
```

**Comment by rinonasti** [comment]
ok grazie infinite

**Comment by gppbarone** [comment]
La issue viene chiusa, in caso siano necessari ulteriori chiarimenti si prega di aprirne una nuova.
