### ISSUE TITLE
ANPR errore login impossibile individuare in maniera univoca scheda anagrafica PNCGPR

### ISSUE THREAD

**Issue by Gianpiero61** [italia/anpr#3303]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by cmigliardi** [comment]
buonasera per favore ci puo' fornire le prime 6 lettere del codice fiscale ? grazie così controlliamo .

**Comment by Gianpiero61** [comment]
Cercamente,Primi 6 codici codice fiscale sono:PNCGPRGrazie buon giorno 


Inviato da Yahoo Mail per iPhone


Il venerdì, aprile 8, 2022, 3:06 PM, cmigliardi ***@***.***> ha scritto:




buonasera per favore ci puo' fornire le prime 6 lettere del codice fiscale ? grazie così controlliamo .

**Comment by cmigliardi** [comment]
buongiorno se è lei la persona del 61 - la scheda in anpr va verificata perché nel nome è presente un trattino.  si può rivolgere al comune di Genova . spero di esserle stata di ausilio -

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by Gianpiero61** [comment]
Grazie


Inviato da Yahoo Mail per iPhone


Il sabato, aprile 9, 2022, 3:35 PM, cmigliardi ***@***.***> ha scritto:




buongiorno se è lei la persona del 61 - la scheda in anpr va verificata perché nel nome è presente un trattino. si può rivolgere al comune di Genova . spero di esserle stata di ausilio -
