### ISSUE TITLE
Errore CAST inserendo nuovo utente

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#3304]
Errore CAST inserendo nuovo utente

**Comment by paoloHV** [comment]
Comune di Jolanda di Savoia, nuovo utente

**Comment by Leonforte** [comment]
Salve, ci  occorre sapere almeno le iniziali del cf dell'utente che si sta tentando di inserire, grazie

**Comment by paoloHV** [comment]
ho risolto in autonomia con un ticket
