### ISSUE TITLE
Risposta P002 - Differenza dataApertura con quella in Riepilogo pratica

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3305]
Nel caso della richiesta con codice 27362690, si nota una differenza di un giorno tra la data di apertura riportata nell'xml della Risposta P002, cioè:
```xml
<dettaglio xmlns="">
			<codiceRichiesta>27362690</codiceRichiesta>
			<idTipologia>2</idTipologia>
			<dataApertura>2022-04-11T00:13:43+02:00</dataApertura>
			<dataScadenza>2022-04-13T00:59:59+02:00</dataScadenza>
			<dataUltimoAggiornamento>2022-04-11T00:13:43+02:00</dataUltimoAggiornamento>
```
e la data nel pdf del Riepilogo Pratica, riportata in alto a destra:

**Roma 10/04/2022**

**Comment by apaolacci** [comment]
Salve,
stiamo verificando la segnalazione. 

Prima di invocare il dettaglio P002, hai anche la response XML dell'operation P001 ? 
Perché anche lì è riportato un campo `<dataApertura/>`, così verifichiamo anche questa conversione della data.

Grazie.

**Comment by ATropeano** [comment]
Ecco la parte dell'elenco del P001 relativa alla segnalazione:
```
  <RispostaOKP001 xmlns="http://sogei.it/ANPR/P000sc">
    <testataRisposta xmlns="">
      <idOperazioneComune>213355</idOperazioneComune>
      <codMittente>037020</codMittente>
      <codDestinatario>ANPR02</codDestinatario>
      <operazioneRichiesta>P001</operazioneRichiesta>
      <dataOraRichiesta>2022-04-12T08:03:50.5305547+02:00</dataOraRichiesta>
      <idOperazioneANPR>851001358</idOperazioneANPR>
      <esitoOperazione>0000</esitoOperazione>
    </testataRisposta>
    <criteriRicerca xmlns="">
      <dataIniziale>2022-03-29</dataIniziale>
      <dataFinale>2022-04-12</dataFinale>
      <idTipologia>2</idTipologia>
      <idStatoRichiesta>2</idStatoRichiesta>
      <flagInScadenza>false</flagInScadenza>
    </criteriRicerca>
    <elenco xmlns="">
        ...
      <richiesta>
        <codiceRichiesta>27362690</codiceRichiesta>
        <idSchedaSoggettoRichiedente>19068154</idSchedaSoggettoRichiedente>
        <idSchedaSoggettoInteressato>19068154</idSchedaSoggettoInteressato>
        <idStatoRichiesta>2</idStatoRichiesta>
        <idTipologia>2</idTipologia>
        <dataApertura>2022-04-11T00:13:43+02:00</dataApertura>
      </richiesta>
    </elenco>
  </RispostaOKP001>
</RispostaP001>
```

**Comment by apaolacci** [comment]
Grazie Alessio,
purtroppo se noi proviamo a fare un'auto invocazione oppure a verificare su tabella di tracciamento input ed output della nostra esecuzione, sia dell'operation P001 sia dell'operation P002, non riscontriamo l'anomalia che invece vediamo sui tuoi xml.


Puoi provare ad indagare se lato vostro fate qualche operazione di unmarshalling sul client che invoca che a seconda del timezone impostato sulla vostra macchina trasforma l'orario con un +1 facendo finire la data al giorno seguente ?

Ti allego uno stralcio dei due xml di response salvati sui log del sistema in output verso di voi.
[xml-response-p001.txt](https://github.com/italia/anpr/files/8473719/xml-response-p001.txt)
[xml-response-p002.txt](https://github.com/italia/anpr/files/8473721/xml-response-p002.txt)

Facci sapere, grazie.

**Comment by apaolacci** [comment]
Buongiorno Alessio,
avete avuto modo di verificare il mio ultimo messaggio? Facci sapere, grazie.
 
Saluti

**Comment by ATropeano** [comment]
Scusa se rispondo con ritardo. Ho comunque risolto il problema. 
Ho dovuto affinare la nostra funzione di "aggiustamento" delle date in fase di deserializzazione della vostra risposta ANPR per gli ultimi servizi (P002).
La questione è un po' complessa ma cerco di spiegarmi. 
Lavorando in ambiente Microsoft .Net, ho costatato che in fase di deserializzazione, sulle date UTC vengono applicate delle regole diverse da quello che è un ambiente Java o simili.
Mi riferisco alle date di decorrenza e fine dell'ora legale, prima che, divenissero stabili e uniformi dal 1996 in poi.
Microsoft applica sempre le stesse regole di inizio e fine dell'ora legale in Italia per tutti gli anni passati (e cioè dall'ultima domenica di marzo all'ultima di ottobre), Java, o comunque il vostro sistema, invece sembra attenersi a una regola più fedele alle implementazioni storiche dell'ora legale, che ad esempio è rimasta in vigore per l'intero anno 1941 (vedi sito http://calendario.eugeniosongia.com/oralegale.htm).
Avendo la maggior parte delle date la parte time all'ora 00 del nuovo giorno, per quelle date che cadono in questi periodi di sfasamento fra i due sistemi, si genera una differenza di un giorno fra i due sistemi.
Io non ho trovato di meglio che gestire questi casi specifici con una mia funzione di aggiustamento...
