### ISSUE TITLE
Cittadini con ID ANPR in db locale ma non presenti in ANPR

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3306]
Comune di Pesaro, ambiente di produzione

durante la lavorazione di una pratica ci siamo accorti che le persone in essa contenute sono in una situazione stranamente incoerente.
Nella base dati locale abbiamo i loro ID ANPR (69976300 69984641 69959578) ma in ANPR non li troviamo, nemmeno con ricerca nazionale da WEBAPP.
Lo stesso vale per la famiglia cui appartengono (ID ANPR 44519747).
Potete aiutarci a capire cosa sia successo ?
Grazie

**Comment by ncapozzi** [comment]
Per la risoluzione del problema sarà contattato direttamente il Comune.
