### ISSUE TITLE
[1014] Errore EHRA1

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3307]
idOperazioneANPR: 851480701
Ambiente di Produzione

Da alcuni giorni diversi nostri comuni ci stanno segnalando la comparsa dell'errore EHRA1 in fase di apertura dei procedimenti anagrafici.
Viene comunicato per esempio: "Il numero pratica comune **_X_** indicato per il procedimento amministrativo non e' presente" dove **_X_** non è un nostro procedimento e nemmeno un qualunque altro dato.

Potete verificare? Grazie

**Comment by siscomanpr** [comment]
Il problema continua a persistere e ci è stato segnalato da altri nostri comuni in mattinata.
idOperazioneANPR 855093202
Errore: EHRA1 - Il numero pratica comune 200-188-2022 indicato per il procedimento amministrativo non e' presente.

Potete verificare e comunicarci qualcosa il prima possibile.
Grazie

**Comment by rvinzani** [comment]
Per quanto riguarda il comune di Verbania, il procedimento IMMAIRE38-2022 ci risulta già chiuso. Per quanto riguarda invece il comune di Buttigliera Alta ci risulta il numero di pratica C20220000000059  già aperta. Se sono necessarie ulteriori informazioni vi prego di rivolgervi al nostro servizio d assistenza 800863116 che aprirà un ticket tramite il quale verrete contattati per la risoluzione del problema
