### ISSUE TITLE
Anomalo Annullamento mutazione in presenza di cancellazione altri motivi

### ISSUE THREAD

**Issue by acarcea** [italia/anpr#3308]
Salve,
scrivo per conto del comune di Gela per segnalare la seguente situazione anomala.
In data 09-03-2022 con data decorrenza 20-01-2022 è stata inviata una mutazione di residenza per l'individuo idsoggAnpr = 104407102 e idoperazioneAnpr = 814759493
In data 23-03-2022 con decorrenza 23-03-2022 per lo stesso individuo è stata inviata una cancellazione altri motivi per irreperibilità con idOperazioneAnpr = 831042014
In data 12-04-2022 con decorrenza 23-03-2022 è staat annullata l'operazione idoperazioneAnpr = 814759493 tramite operazione di annullamento idoperazioneAnpr = 851527830
L'effetto di questa sequenza di operazioni è che in ANPR il cittadino risulta erroneamente ancora residente e non risulta presente nella famiglia.
Provando ad annullare l'operazione di cancellazione si ottiene l'errore:
1 Errore Anpr Cod: ES121 - Identificativo soggetto attribuito da ANPR 104407102 non presente o scheda non archiviata -
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-12 16:18:44 , idOperazioneANPR 851888121 -
provando ad effettuare nuovamente una cancellazione altri motivi per il soggetto, nella parte dati Dati di Controllo vuole valorizzato il campo Ruolo Soggetto (campo obbligatorio) ma non ne da la possibilità.
Quello che si desidera è che il cittadino risulta su ANPR cancellato per irreperibilità.
-----------------------------------------------------------------------------------------------------------------------
Analoga anomalia si è avuta per l'individuo idSoggAnpr = 104399036
In data 09-03-2022 con data decorrenza 20-01-2022 è stata inviata una mutazione di residenza per l'individuo idsoggAnpr = 104399036 e idoperazioneAnpr = 814759493
In data 23-03-2022 con decorrenza 23-03-2022 per lo stesso individuo è stata inviata una cancellazione altri motivi per irreperibilità con idOperazioneAnpr = 831041981
In data 12-04-2022 con decorrenza 23-03-2022 è staat annullata l'operazione idoperazioneAnpr = 814759493 tramite operazione di annullamento idoperazioneAnpr = 851527830
L'effetto di questa sequenza di operazioni è che in ANPR il cittadino risulta erroneamente ancora residente e non risulta presente nella famiglia.
Quello che si desidera è che il cittadino risulta su ANPR cancellato per irreperibilità.

Riferimento del comune: Nunzio Lo Porto tel. 3396573683

Distinti Saluti
Comune di Gela

**Comment by ncapozzi** [comment]
Buongiorno
non è chiaro se volete mantenere l'annullamento del cambio di residenza oppure no. Il recapito telefonico non risponde, potete indicare per favore una fascia di reperibilità?

**Comment by acarcea** [comment]
Salve, 
è possibile chiamare al 3396573683 (sig. Nunzio lo Porto) da domani tutte le mattine.
In caso di mancata risposta (magari per impegni allo sportello) è' possibile anche scrivere al seguente indirizzo mail: nunzioloporto@alice.it  

Grazie Mille e Distinti Saluti
Comune di Gela

**Comment by ncapozzi** [comment]
Fornita assistenza telefonica per il ripristino della situazione corretta
