### ISSUE TITLE
Tabella comuni italiani ANPR - comuni cessati

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#331]
Si chiede come mai, in molti casi , per i comuni cessati che si sono fusi in altri la data cessazione dei vecchi comuni coincide con quella di istituzione del nuovo comune istituito, cioe' e' lo stesso giorno.
Ad esempio per la provincia di Trento TN i comuni istituiti negli ultimi anni mediante fusione di altri cessati hanno la data istituzione primo gennaio coincidente con quella di cessazione dei precedenti dove e' presente sempre primo gennaio. Sul portale della provincia di Trento http://anteprime.provincia.tn.it/pat_statistica_new/metodologie_statistiche/pagina3.html
"Variazioni comuni del Trentino dal 01/01/2010"
invece e' riportata per questi comuni cessati la data 31/12 dell'anno in questione.
esempio: Lomaso 022107 e' confluito in Comano Terme 022228 il 01/01/2010 che viene istituito in questo giorno; Lomaso cessa il 31/12/2009 mentre sulla tabella ANPR risulta 01/01/2010.

In generale quando viene istituito un comune l'evento che avviene nel giorno di istituzione si considera nel nuovo comune e quindi per il vecchio comune gli eventi terminano il giorno precedente.
Questa situazione puo' comportare errori nella ricerca dei comuni.
Grazie
Carla Musian

**Comment by MassimoSchiappa** [comment]
Salve,
l’osservazione è corretta, ma ISTAT codifica così le date. Provvederemo ad effettuare una modifica “d’ufficio” che renderemo disponibile contestualmente alle variazioni territoriali della Sardegna, prevista nel prossimo mese.

**Comment by gcarbonin** [comment]
L'intervento è stato completato
