### ISSUE TITLE
[ws 1001] Iscrizione per Nascita - Errore EN134

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3312]
ambiente di PRODUZIONE - comune di IMOLA (037032)

non riusciamo a far passare l'iscrizione per nascita corrispondente all'idOperazioneComune 2022006420
il web-service restituisce questo errore:
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EN134</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Identificativo Famiglia non valido o di competenza di altro comune</testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-13 14:52:42 , idOperazioneANPR 852991800</testoErroreAnomalia>
	</errore>
</listaErrori>
```

il bambino viene inserito nel nucleo della madre (idSoggettoANPR 73244151 - idFamigliaANPR 41730643)
l'anomalia che rileviamo è che la madre, pur essendo residente a IMOLA, nei dati della famiglia risulta collegata a LUCCA
```
<famigliaConvivenza>
	<idFamigliaConvivenzaComune>
		<idFamigliaConvivenzaComuneIstat>046017</idFamigliaConvivenzaComuneIstat>
		<idFamigliaConvivenza>112703</idFamigliaConvivenza>
	</idFamigliaConvivenzaComune>
	<idFamigliaConvivenzaANPR>41730643</idFamigliaConvivenzaANPR>
	<dataOrigineFamigliaConvivenza>2019-10-17+02:00</dataOrigineFamigliaConvivenza>
	<presenzaFamigliaCoabitante>S</presenzaFamigliaCoabitante>
	<tipoScheda>3</tipoScheda>
</famigliaConvivenza>
```

analizzando la storia del soggetto (la madre), abbiamo visto che il 09-09-2021 è stata iscritta a LUCCA (abbiamo ricevuto notifica di cancellazione con idOperazioneANPR 652597597), e successivamente la sua iscrizione è stata annullata (abbiamo ricevuto notifica di ripristino con idOperazioneANPR 710746903).
l'impressione è che in sede di iscrizione a LUCCA siano stati modificati gli estremi dell'idFamiglia, e che gli stessi non sono però stati ripristinati in seguito all'annullamento della pratica.

vi chiediamo pertanto di verificare la situazione e sanare l'eventuale bug (se di bug si tratta) e nell'immediato avremmo bisogno di risolvere il problema per completare l'iscrizione in ANPR del bambino.

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Potete per favore riprovare e farci sapere se ora l'iscrizione va a buon fine?

**Comment by AMonopoliADS** [comment]
la comunicazione è stata inviata con successo.
abbiamo visto che adesso gli estremi della famiglia (nei dati della madre) sono di nuovo collegati al comune di IMOLA (037032), immagino quindi che fosse quello il problema.

grazie
