### ISSUE TITLE
Errore EAM95 in mutazione cognome

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3314]
Buongiorno, in ambiente di PRODUZIONE comune di MORI per i soggetti con id ANPR 94642675 e id ANPR 94642674 otteniamo un errore nella mutazione dei dati (rettifica del cognome).
Abbiamo provato sia tramite web service che tramite web app ma otteniamo sempre lo stesso errore:
EAM95 - Variazione non consentita, soggetto registrato in AT ANPR di altro comune

Ho visto che ci sono state altre segnalazioni simili che avete provveduto a sbloccare, potete procedere anche con questi due soggetti in modo da poter concludere le due pratiche anagrafiche.

Grazie.
Andrea Galli

**Comment by frmariani** [comment]
entrambi i soggetti, senza cognome, nel sistema di Agenzia delle Entrate risultano residenti in altro comune, probabilmente il comune di precedente residenza.
Da Risoluzione disallineamenti con AE esegua un allineamento dei dati e successivamente proceda con la variazione del cognome; potrebbe essere necessario aspettare domani per quest'ultima operazione.

**Comment by frmariani** [comment]
da verifiche effettuate risulta che le operazione di allineamento sono state effettuate con esito positivo in data odierna, pertanto la issue viene chiusa.
