### ISSUE TITLE
RISPOSTA P002 - INVIO P003  Quesiti

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3317]
Buongiorno,
1) Quando di richiede con WSP002 un idrichiesta , dopo integrazione da parte del cittadino, viene sempre inviato completo degli allegati precedenti con solo modificato lo stato ed eventuali allegati aggiuntivi?
2) L'operatore nel invio con WSP003 deve essere censito?
3) se si, può essere censito senza smart-card?
Grazie

**Comment by apaolacci** [comment]
Buongiorno,
per il punto 1) la risposta è si. Richiedendo il dettaglio P002 di una richiesta nello stato Integrata oppure in uno stato di lavorazione successivo all'integrazione del cittadino vengono sempre inviati gli allegati aggiunti dal cittadino e lo stato corrente corretto.

Per il punto 2) e 3) nell'operation soap P003 il campo operatore deve essere censito con il codice fiscale dell'operatore d'anagrafe o comunque con un identificativo del vostro gestionale con il quale si identifica l'operatore d'anagrafe, in ogni caso serve per troubleshooting.

Saluti

**Comment by rinonasti** [comment]
ok grazie quindi gli allegati ci sono sempre tutti?

**Comment by apaolacci** [comment]
Si a seguito dell'integrazione di un cittadino, gli allegati saranno sempre presenti (quelli iniziali + quelli aggiunti durante l'integrazione).

Saluti

**Comment by rinonasti** [comment]
Grazie per la fattiva collaborazione. Approfitto per AUGURARVI BUONA PASQUA.
