### ISSUE TITLE
chiarimento su ricezione notifiche con endpoint

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3318]
Buongiorno, collegandomi a #3203 dove mi era stato indicato il funzionamento in caso di non acquisizione di una notifica (22/03).

Mi chiedevo in caso non sia gestita una tipologia di notifica (N030) quindi la risposta sarebbe negativa, il sistema dovrebbe riprovare l'invio n volte e poi fermarsi. 

L'invio delle notifica viene interrotto solo per l'ipotetica N030 oppure per tutte? nel caso quando "ripartirebbe" l'invio?

esempio alle 8 è disponibile la N030 che fallisce, alle 10 c'è una N010, viene inviata immediatamente?

grazie mille

**Comment by gife67** [comment]
Buongiorno, se riceviamo un esito dall'endpoint, quindi la comunicazione è ok, ritentiamo solo a fronte di determinati codici esito. 
I tentativi sono specifici per ogni notifica ed il blocco di una notifica non comporta il blocco di tutte le notifiche.
Vengono effettuati 5 tentativi, intervallati uno dall'altro 5 minuti, dopodichè la notifica viene sospesa ed occorre un nostro intervento per sbloccarla su richiesta del Comune. Il Comune può richiedere, tramite email, lo sblocco per un intervallo temporale di tutte le notifiche andate in errore.
Periodicamente facciamo un analisi per verificare se ci sono endpoint che non stanno funzionando o non sono raggiungibili da molti giorni, in quel caso li disabilitiamo per non creare disservizio. 
Nell'esempio che ha riportato, se l'endpoint è OK, l'N010 verrebbe inviata immediatamente.

**Comment by Hdemografici** [comment]
Buongiorno, 
grazie mille per il chiarimento

**Comment by Hdemografici** [comment]
Mi sorge un dubbio, nel caso di endpoint attivo ma i sistemi comunali in aggiornamento, attualmente ho previsto una risposta negativa con codice 3, stessa cosa per tutti gli altri controlli es. errori nella validazione della firma, la decodifica della notifica ecc.
in questi casi la notifica risulterebbe inviata e quindi il comune non la riceverà più (a meno di richiesta specifica) oppure viene rimandata con le modalità descritte precedentemente?

Per essere più precisi, nei casi in cui la notifica non viene acquisita correttamente dal sistema comunale, meglio non prevedere una risposta o usare un codice specifico, cosi da evitare di dover chiedere la rispedizione?
Considerando che esclusi problemi di configurazione (caricamento dei certificati utilizzati) i casi dovrebbero essere molto pochi, visto che gli aggiornamenti vengono fatti prevalentemente fuori orario lavorativo.

grazie mille

**Comment by Hdemografici** [comment]
Perfetto grazie mille
buona giornata
