### ISSUE TITLE
[3002] Famiglia non trovata alla data di riferimento

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3319]
Comune di Torino, ambiente di produzione.

Stiamo cercando in ANPR con il servizio 3002 la scheda di famiglia ID ANPR 141436936 con riferimento alla data del 1/10/2021. Il servizio ci risponde senza alcun soggetto.
Abbiamo provato la stessa ricerca da webapp con "Consultazione scheda famiglia/convivenza" ottenendo lo stesso risultato.
Consultando i singoli componenti però risultano iscritti in quella famiglia dal 9/9/2021.

Come mai il servizio di ricerca famiglia non ritorna la scheda come atteso ?

**Comment by rvinzani** [comment]
Stiamo facendo delle indagini. Le faremo sapere appena possibile. Buona giornata

**Comment by busaster** [comment]
Scusate se insisto ma dobbiamo svolgere dal cliente un'attività massiva che non possiamo rimandare più in là, vorrei capire se siete riusciti ad isolare la problematica. Grazie

**Comment by busaster** [comment]
Buongiorno, avete qualche novità in merito a questa anomalia ? Grazie

**Comment by rvinzani** [comment]
Dalle nostre analisi abbiamo riscontrato che sul soggetto segnalato sono state fatte due operazioni in cui la seconda in ordine temporale ha una data di decorrenza precedente a quella della prima.

**Comment by rvinzani** [comment]
Dovrebbero essere questi 815159235, 815161825, 815179534
