### ISSUE TITLE
Mutazioni e gestioneCF

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#332]
Chiedo un chiarimento.
Nel documento delle Specifiche di Interfaccia, al par. 15.1.3.2-Mutazioni si legge, all'ultimo capoverso:
- nessun valore nel campo gestioneCF.
Come devo interpretare le parole "nessun valore"?
a) non valorizzare gestioneCF
b) assegnare a gestioneCF il valore 0 (= nessuna azione);
Grazie.
Filipazzi - maggioli

**Comment by gcarbonin** [comment]
Una o l'altra soluzione vanno bene; in entrambi i casi si demanda ad ANPR il controllo: se ci sono variazioni nei dati che concorrono alla formazione del codice fiscale, si richiede all'Agenzia una validazione.
Se il comune vuole che l'operazione anagrafica sia eseguita senza alcuna iterazione con l'Agenzia occorre indicare 3 nel campo gestioneCF. Occorre considerare che tale soluzione, fortemente sconsigliata, non è consentita in ambiente di produzione per i soggetti marcati dall'Agenzia come soggetti ANPR (codici fiscali validati).
