### ISSUE TITLE
COMUNE DI LEQUIO TANARO: ERRORI IN ISCRIZIONE AIRE 

### ISSUE THREAD

**Issue by ValeriaRoa** [italia/anpr#3321]
Buongiorno,
iscrizione aire per acquisto di cittadinanza per decreto ci vengono restituiti i seguenti errori
EAA33 ERRORE DI CONGRUENZA
EN257 Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-20 08:09:58 , idOperazioneANPR 857905893

come possiamo risolvere?
grazie mille

Roà Valeria 
Comune di Lequio Tanaro (CN)

**Comment by ncapozzi** [comment]
Buonasera
l'OHIO è uno degli stati che compongono gli Stati Uniti D'America, non uno stato valido di per sè e quindi nel luogo di nascita dovete impostare
descrizioneStato = STATI UNITI D'AMERICA
codiceStato = 536
descrizioneLocalita = LIMA oppure LIMA OHIO 
Questo vale per tutti i cittadini nati negli USA.

**Comment by ValeriaRoa** [comment]
ora ci vengono restituiti i seguenti errori: 
Codice fiscale individuato in AT con dati anagrafici diversi o indirizzo diverso

Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-21 08:24:22 , idOperazioneANPR 859136261

**Comment by ValeriaRoa** [comment]
effettivamente non siamo riusciti a capire neanche con gli informatici cosa sia successo ma a quanto pare si c'erano già dati anagrafici molto simili anche se ricercando la persona su anpr la stessa non veniva comunque trovata in alcun modo.
ora dovremmo essere riusciti iscrivendo il soggetto dal gestionale senza la validazione del cf collegandoci poi sulla wab app - risoluzione allineamenti ae - conferma dati ae.
l'interessato noi ora lo vediamo correttamente inserito in anpr .
grazie per l'aiuto.
