### ISSUE TITLE
Codice ISTAT Vigentino

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#3322]
Con [R.D. 17 gennaio 1869, n. 4824](https://www.gazzettaufficiale.it/eli/id/1869/02/14/069U4824/sg) i comuni di Vaiano Valle (codice ISTAT 015968) e Vigentino (codice ISTAT 015975) vennero soppressi ed aggregati a quello di Quintosole (codice ISTAT 015931).
Con [R.D.  25 agosto 1893, n. 518 ](https://www.gazzettaufficiale.it/eli/id/1893/09/22/093U0518/sg) il comune di Quintosole cambiò denominazione in Vigentino.
Con [R.D. 2 settembre 1923, n. 1912](https://www.gazzettaufficiale.it/eli/id/1923/09/29/023U1912/sg) il comune di Vigentino (già Quintosole) venne soppresso ed aggregato a quello di Milano.

La tabella ISTAT dei comuni soppressi riporta:
|Anno|Comune|Denominazione|Data evento|Comune associato|Denominazione Comune associato|
|-|-|-|-|-|-|
|1869|015968|Vaiano Valle|01/03/1869|015931|Quintosole|
|1869|015975|Vigentino|01/03/1869|015931|Quintosole|
|1923|015931|Vigentino|14/10/1923|015146|Milano|

La tabella ANPR riporta:
|ID|DATAISTITUZIONE|DATACESSAZIONE|CODISTAT|CODCATASTALE|DENOMINAZIONE_IT|
|-|-|-|-|-|-|
|10751|01/02/1869|13/10/1923|015975|L871|VIGENTINO|

Il codice ISTAT corretto per il comune di Vigentino soppresso nel 1923 sembrerebbe quindi 015931 e non 015975 come riportato nella tabella ANPR.

**Comment by ncapozzi** [comment]
Buongiorno
la tabella Comuni è stata aggiornata. La ringraziamo per la segnalazione.
