### ISSUE TITLE
Errore iscrizione cittadino straniero dall'estero

### ISSUE THREAD

**Issue by ParsecDemografici** [italia/anpr#3325]
Per il Comune di Gravina In Puglia (Istat 072023) si sta cercando di iscrivere per altri motivi un cittadino straniero con provenienza dall'estero, ma il sistema restituisce questi errori

_La richiesta non risulta valida secondo i nuovi XSD [cvc-complex-type.2.4.a: Invalid content was found starting with element 'codiceStato'. One of '{descrizioneStato}' is expected.] (Codice: EN489)

La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)

Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-21 13:05:07 , Token 1650539_

Non ci sembra che manchi nessun dato o qualcuno di questi non sia corretto. da cosa potrebbe dipendere?

**Comment by ParsecDemografici** [comment]
> Buonasera il msg di errore indicato " Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-21 13:05:07 , Token 1650539_" non è di quelli restituiti da ANPR. Potrebbe essere un problema del gestionale del Comune?

L'operazione viene svolta interamente da webapp senza passare per il gestionale. Quello è l'errore riportato al momento della conferma finale dell'operazione

**Comment by ncapozzi** [comment]
Buongiorno
potrebbe dirmi cosa viene indicato per lo stato estero di nascita e per quello di provenienza?

**Comment by ParsecDemografici** [comment]
Per entrambi Camerun. Avevamo anche controllato che non ci fossero problemi di decorrenza ma entrambe le date sono posteriori allo 01/01/1965

**Comment by ncapozzi** [comment]
Può indicare per favore il recapito telefonico dell'operatore del Comune che sta eseguendo l'inserimento?

**Comment by ParsecDemografici** [comment]
Può contattare il 3935386290, grazie

**Comment by ncapozzi** [comment]
L'utente è riuscito ad inserire il cittadino togliendo la località di provenienza (ha lasciato solo lo stato estero)
