### ISSUE TITLE
Chiarimenti su comune di nascita non esistente alla data

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3328]
Buongiorno,
chiedo come mai, al subentro, ad alcuni cittadini è stato cambiato automaticamente il comune di nascita.
Elenco alcuni codici ANPR a cui è stato cambiato il comune di nascita.
38140212
38141264
38138552
38138181
38139883
38138575
38140425
38141923
38139655

A questi cittadini è stato cambiato il comune in ANPR ma non in AE.

Invece a questi 3 cittadini non è stato cambiato nulla, Hanno sia in ANPR che in AE il comune errato (non esistente alla data di nascita).
38137349
38138042
38137943

Il motivo per cui ai primi è stato cambiato il comune di nascita è perchè non cambia il codice catastale del codice fiscale? Questi comuni hanno avuto "solo" un cambio di denominazione.

Non capisco perchè non sia stato cambiato automaticamente anche in AE. Il Cittadino cosa deve fare per avere anche l'anagrafica in AE aggiornata?

Grazie

**Comment by cvignati** [comment]
Parliamo di cittadini, la maggior parte, over 80 che per tutta la vita hanno avuto una denominazione di comune di nascita e adesso se ne trovano un'altra. A qualcuno cambia leggermente la denominazione, ma ad una decina cambia da Novafeltria a Mercatino Marecchia

**Comment by ncapozzi** [comment]
Buonasera
per  il primo gruppo abbiamo verificato che non è stato cambiato automaticamente il Comune di nascita al subentro. MERCATINO MARECCHIA è la denominazione trasmessa nel file di subentro, sarebbe anche quella valida alla data di nascita. Se vuole ripristinare Novafeltria basta effettuare la mutazione tutti i dati forzando un comune di nascita non valido alla data e chiedendo la validazione del CF.

**Comment by cvignati** [comment]
@ncapozzi In AE è già presente Novafeltria, devo comunque chiedere la validazione del Codice fiscale?

**Comment by cvignati** [comment]
Buongiorno,
sono a comunicare questa incongruenza in cui sono appena incappato.
Ho fatto la verifica su questi tre cittadini:
38138552
38140425
38139883
In ANPR hanno comune di nascita MERCATINO MARECCHIA.
Sono andato a consultare il comune di nascita in AE e ho appurato che accedendo da PuntoFisco il comune di nascita è NOVAFELTRIA, ma accedendo a Consultazione AE da WebApp ANPR il comune di nascita è MERCATINO MARECCHIA.
Come mai questa discrepanza? In consultazione AE i dati anagrafici dove vengono reperiti?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno
per i Comuni con cambio denominazione (es. Mercatino Marecchia che è diventato Novafeltria-PS), al subentro AE ha acquisito la dizione trasmessa in ANPR Mercatino Marecchia-PS anche se il CF è stato rilasciato per Novafeltria . 
Come già detto, se il Comune di nascita deve essere Novafeltria dovete effettuare la mutazione tutti i dati forzando un comune di nascita non valido alla data e chiedendo la validazione del CF.
Se invece il Comune deve essere Mercatino Marecchia anche su AE, i soggetti interessati devono recarsi presso un Ufficio AE e richiedere un duplicato TS/tesserino o la ristampa del certificato di attribuzione del codice fiscale, autorizzano l’AE all’utilizzo di tale dizione sia su TS/tesserino sia nelle visualizzazioni dati.

**Comment by cvignati** [comment]
Scusi, ma per chiarimento definitivo:
Se devo essere sicuro che ci siano discrepanze tra il comune di nascita presente in ANPR e quello in AE (presente anche sulla TS) devo consultare PuntoFisco e non Consultazione AE da WebApp ANPR, corretto?

**Comment by ncapozzi** [comment]
esatto
