### ISSUE TITLE
[1014] Errore EHRA1 *SOLLECITO*

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3329]
Buongiorno,
sarebbe urgente avere una risposta e **una soluzione** all'issue #3307 

Grazie

**Comment by SAlberto** [comment]
Ci sono novità?

**Comment by SAlberto** [comment]
Buongiorno,
in merito alla problematica del ticket #3307 segnaliamo che continua a verificarsi presso vari comuni. 
Cerco di darvi qualche informazione in più partendo dall'ultimo caso che si è verificato in data odierna. 
Siamo in ambiente di produzione. 

Il Comune effettua una mutazione di residenza da altro comune utilizzando però una data errata, in quanto, nella famiglia di destinazione è avvenuto un evento successivo. Ci contattano, eliminiamo l'evento nella famiglia di destinazione con data successiva, reinserendolo quindi anche su ANPR con la data corretta. A questo punto proviamo nuovamente ad effettuare l'evento di mutazione residenza da altro comune, partendo dalla comunicazione 1014. Il codice ANPR dell'operazione in questione è 895346371. Nella comunicazione in questione il numeroPraticaComune è IMM165-2022 . La risposta che ci arriva in merito a questa comunicazione comprende un warning "Il numero pratica comune IMM165-2022 indicato per il procedimento amministrativo e' gia' presente in base informativa" (corretto, il procedimento era già stato aperto con il primo tentativo) ma ANCHE un errore EHRA1 con descrizione "Il numero pratica comune 275907 indicato per il procedimento amministrativo non e' presente" oppure un codice EHRA1 con descrizione "Il numero pratica comune 2022-1762 indicato per il procedimento amministrativo non e' presente" (come nel caso dell'operazione con idANPR 895344203, relativo ad un altro tentativo) .

Provando più volte a fare l'operazione, ANPR sembra restituire alternativamente entrambi i numeri pratica comune (il 275907 e il 2022-1762), ma nessuno dei due riguarda un procedimento aperto dal nostro Comune. 
Il Codice EHRA1 è effettivamente un codice di errore e blocca lo spostamento del soggetto dal vecchio comune al nuovo. Possiamo tenere la pratica in sospeso per un po', per permettervi di fare delle verifiche.
Potete controllare?

Saluti.

**Comment by SAlberto** [comment]
Buongiorno,
non abbiamo ancora ricevuto risposta in merito alla segnalazione, ma il Comune ha esigenza di iscrivere il soggetto al più presto. Potete darci qualche indicazione in merito?

Saluti

**Comment by SAlberto** [comment]
Buongiorno,
sollecito nuovamente una risposta al ticket in questione. Il Comune ha urgenza di portare avanti la mutazione anagrafica ed essendo il problema, da quello che posso capire, relativo solo al procedimento anagrafico, potremmo farlo dalla web application, eliminando però per voi, come da ticket #3307 la possibilità di controllare.
La situazione si sta facendo un po' imbarazzante, con questo Comune e altri, che riscontrano lo stesso problema. Abbiamo aperto la prima segnalazione in merito all'errore EHRA1 più di un mese e mezzo fa (12/04/2022) e la prima risposta da parte vostra è arrivata solo un mese dopo, dicendoci, tra l'altro, che non era possibile fare verifiche in quanto il procedimento era già stato chiuso.

Avremmo necessità URGENTE di un vostro riscontro per capire la casistica e capire come comportarci in presenza di questo messaggio.

Saluti

**Comment by SAlberto** [comment]
Buongiorno,
premetto che i problemi che stiamo riscontrando non sono relativi all'errore EN151 ma all'errore EHRA1, che ha cominciato a comparire in maniera importante da circa due mesi a questa parte, segnalando, come già spiegato precedentemente numeri di procedimento che NON appartengono al comune che sta facendo l'operazione. 
Non sappiamo cosa scatena questo errore e segnalando dei procedimenti inesistenti per il Comune non sappiamo come correggere e permettere al Comune di procedere.

Per quanto riguarda invece l'errore EN151 secondo noi sarebbe un errore renderlo bloccante. Siamo d'accordo sul fatto che in caso di annullamento per accertamenti negativi il procedimento non vada riutilizzato e se ne debba creare uno nuovo, ma spesso e volentieri i Comuni si trovano costretti ad annullare una mutazione e riutilizzare lo stesso procedimento per poter, ad esempio, correggere dei dati che altrimenti non sarebbe possibile correggere (ad esempio se in un primo momento si sbaglia la data dell'evento di mutazione il sistema ANPR NON permette di correggerla e quindi l'unica strada percorribile è buttare l'evento e rifarlo da zero).
Rendendo bloccante l'errore EN151 si renderebbe ai Comuni ancora più difficile rettificare errori formali e involontari, costringendoli a redigere una nuova pratica solo per errori "banali" e che sarebbe possibile correggere in maniera più veloce.

Saluti.

**Comment by SAlberto** [comment]
Buongiorno,
i Comuni continuano a comunicarci la comparsa di errori EHRA1, con segnalazioni di numeri di provvedimento NON di loro competenza, che però bloccano le mutazioni di residenza. La situazione, come già scritto in precedenza, si sta facendo pressante e, spiace dirlo, un po' imbarazzante.

Saluti

**Comment by rvinzani** [comment]
E' stato ripristinato il controllo EN151 come bloccante. In questo caso non scatta l'altro controllo che restituisce informazioni non corrette. Rimane sempre il vincolo che non è possibile utilizzare lo stesso numero di protocollo di un procedimento già chiuso

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[1014] Errore EHRA1 *SOLLECITO* (Issue #3329)" inviata il 31/05/2022
17:27:55.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
