### ISSUE TITLE
CERTIFICAZIONE SOGGETTI CON PROCEDIMENTO DI VARIAZIONE DI RESIDENZA IN CORSO

### ISSUE THREAD

**Issue by AnnaUrban** [italia/anpr#333]
Quando iscriviamo un soggetto in ANPR (iscrizione preliminare) il campo relativo alla certificabilità riporta la dicitura "CERTIFICABILITA' PARZIALE (SOLO RESIDENZA E STATO DI FAMIGLIA)". Tuttavia se viene richiesta l'emissione di uno dei 2 certificati indicati, viene sempre generato l'errore "Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato (Codice: EN181)". La domanda che vorrei porre è questa: per i soggetti che hanno un procedimento aperto occore sempre 'forzare' l'emissione del certificato indicando 'si' alla voce 'stampa anche in presenza di errori'? Comune di Serravalle Sesia - Ambiente di produzione

**Comment by mccalv** [comment]
ciao @AnnaUrban! Immagino che per errore sia partita la sua segnalazione senza il contenuto e dal titolo non é molto chiaro :) 
Puoi comunque editare il tuo commento.
Grazie!

**Comment by AnnaUrban** [comment]
Quando iscriviamo un soggetto in ANPR (iscrizione preliminare) il campo relativo alla certificabilità riporta la dicitura "CERTIFICABILITA' PARZIALE (SOLO RESIDENZA E STATO DI FAMIGLIA)". Tuttavia se viene richiesta l'emissione di uno dei 2 certificati indicati, viene sempre generato l'errore  "Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato (Codice: EN181)". La domanda che vorrei porre è questa: per i soggetti che hanno un procedimento aperto occore sempre 'forzare' l'emissione del certificato indicando 'si' alla voce 'stampa anche in presenza di errori'? Comune di Serravalle Sesia - Ambiente di produzione

**Comment by AnnaUrban** [comment]
La segnalazione era partita involontariamente senza contenuto: chiedo Scusa!

**Comment by gcarbonin** [comment]
La presenza del procedimento è un controllo prevalente sugli altri; quando c'è un procedimento aperto occorre sempre la forzatura
