### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio 

### ISSUE THREAD

**Issue by mohammedad** [italia/anpr#3330]
My First 6 digits : LJZMMM

![Screenshot_2022-04-27-00-20-03-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/51848489/165402448-ca9ec29e-4ceb-49b2-befd-083ba90f33b2.jpg)
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by cmigliardi** [comment]
Buongiorno,   le consigliamo di  rivolgersi al suo comune di competenza ( da quanto vediamo Roma)  per verificare la scheda in Anpr.

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
