### ISSUE TITLE
Errore EAA0A senza testo

### ISSUE THREAD

**Issue by Msirri** [italia/anpr#3331]
Buongiorno inviando un iscrizione aire si riceve un errore ma senza testo.

EAA0A .....

Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-27 10:01:54 , idOperazioneANPR 864750887

In attesa di un riscontro, cordiali saluti.

Marco Sirri
Comune di Cesena
Tel 0547356252

**Comment by ncapozzi** [comment]
Buongiorno
nella richiesta di attribuzione del CF ad Agenzia Entrate viene trasmesso l'indirizzo. Abbiamo verificato che nell'indirizzo della famiglia è presente il carattere # che genera l'errore nella procedura. Pertanto prima di effettuare l'iscrizione A001 è necessario effettuare una mutazione famiglia/convivenza (WS 5001) con tipo 9 = RETTIFICA/INTEGRAZIONE INDIRIZZO e data decorrenza = data di decorrenza dell'attuale residenza nel paese, per togliere il carattere #.

**Comment by Msirri** [comment]
Con la rettifica d'indirizzo togliendo il #, la nascita è stata correttamente inviata.

Se possibile chiediamo di rendere il messaggio più chiaro e di validare il # nel campo indirizzo del servizio 5001, dato che con l'operazione id anpr 861124796 è stato accettato.

Cordiali saluti
Marco Sirri
Comune di Cesena
Tel 0547356252
