### ISSUE TITLE
Visualizzazione cartellino CIE direttamente da ANPR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3333]
Buongiorno,
chiedo se ad oggi, visto il subentro in ANPR di tutti i comuni e l'emissione della CIE da parte di tutti i comuni sia possibile visualizzare il cartellino della carta di identità elettronica direttamente da ANPR.
Chiedo questa possibilità visto che entrambi i database sono del Ministero dell'Interno.

Grazie
Claudio Vignati

**Comment by ncapozzi** [comment]
Buonasera,
quando viene emessa una CIE il Poligrafico trasmette una notifica ad ANPR che registra gli estremi della carta di identità sulla propria base dati. Andando in consultazione sulla scheda del cittadino, gli estremi della carta sono visibili nella sezione Documenti del cittadino.

**Comment by cvignati** [comment]
Buongiorno,
io non parlo solo degli estremi, che so essere registrati e consultabili in ANPR, ma del Cartellino Elettronico che, attualmente, è scaricabile solo attraverso la Postazione CIE, utilizzando la SmartCart del Ministero dell'Interno rilasciata agli operatori che rilasciano la CIE.

Chiedo questo collegamento innanzitutto perché i databases sono gestiti entrambi dal Ministero dell’interno e perché l'ufficiale di anagrafe abilitato alla visualizzazione degli estremi della carta di identità su ANPR, sicuramente ha l'autorità per visualizzare il cartellino elettronico.

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
provvederemo ad inoltrare la sua richiesta al Ministero dell'Interno che deciderà in merito.
Grazie
