### ISSUE TITLE
ANPR - Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by fabriciomaresca** [italia/anpr#3334]
Gentile Signori,
Non riesco ad accedere al portale ANPR, il sistema mi da errore:
"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."
Io sono sono residente in Argentina, iscritto all'AIRE (Comune di iscrizione : ROMA). Ho provato ad acceder con SPID, ma mi dà l'errore sopra descritto.
Potreste aiutarmi con la mia richiesta?
Grazie mille.

**Comment by cmigliardi** [comment]
buonasera, per favore ci può dare le prime   6 lettere del codice fiscale ?  così  verifichiamo . grazie

**Comment by fabriciomaresca** [comment]
Grazie per la pronta risposta. Le prime 6 lettere del mio codice fiscale sono: MRSFRC 
Grazie mille

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1986  -  purtroppo in Anpr la scheda non è presente  - l invitiamo a rivolgersi al suo comune di competenza -

**Comment by fabriciomaresca** [comment]
Grazie mille per l'informazione.
