### ISSUE TITLE
WSP002 - decodifica

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3335]
Nella risposta al servizio P002 per cambi residenza è presente il tag TipoFamiglia. con quale tabella viene decodificato?
Grazie

**Comment by apaolacci** [comment]
Buonasera,
non esiste tabella di decodifica, ma come da commento su colonna del DB SC_RES_DICHIARAZIONE.TIPOFAMIGLIA  la codifica è la seguente:   2 = NUOVA FAMIGLIA, 1 = FAMIGLIA ESISTENTE

Saluti,
