### ISSUE TITLE
ANPR - Purtroppo non è stato possibile accedere al servizio... 

### ISSUE THREAD

**Issue by Shaggy8519** [italia/anpr#3336]
Salve, ho provato ad accedere con Spid e mi dà il seguente errore:

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Il comune di residenza non ha saputo risolvere.

Grazie

(codice fiscale inizia per FRLGFR anno di nascita 1976)

**Comment by cmigliardi** [comment]
buonasera, dai dati in Anpr  risulta che il codice fiscale non è validato - le consigliamo di rivolgersi al suo comune di Fondi  - e di far verificare il nome di battesimo  che si compone di 2 nomi e di confrontarlo con i dati di ag. entrate. affinché sia allineati.  - spero di esserle stata di ausilio .

**Comment by cmigliardi** [comment]
La issue viene chiusa. 
In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
