### ISSUE TITLE
[ws P001] Pratica non trovata

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3337]
ambiente di TEST - comune di FAENZA (039010)

sul portale cittadino di test è stata inserita la pratica di Cambio Residenza con idRichiestaANPR 1280102 (data 27/04/2022)
la richiesta dell'elenco pratiche (ws P001) restituisce il messaggio
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EN122</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
	</errore>
</listaErrori>
```
(vedere idOperazioneANPR 49053619)

non capiamo come mai, se potete verificare... grazie
Alessandro Monopoli ADS

**Comment by apaolacci** [comment]
Buongiorno,
l'invocazione di recupero pratiche wsP001 è inviata dal comune mittente di FAENZA (cod.Istat 039010) 
```
<idOperazioneComune>2022500552</idOperazioneComune>
<codMittente>039010</codMittente>
```
mentre la pratica di cambio residenza N. 1280102 ha come comune competente il comune di destinazione CASTEL SAN PIETRO TERME (cod.Istat 037020) indicato dal cittadino.

Solo il comune di CASTEL SAN PIETRO TERME potrò vedere/recuperare/lavorare la pratica quando sarà in stato APERTA.

Saluti,

**Comment by AMonopoliADS** [comment]
chiarito. grazie.
avevamo dato per scontato che la pratica fosse di cambio abitazione all'interno del comune.
