### ISSUE TITLE
Info su recupero residenza

### ISSUE THREAD

**Issue by NikolasMajan** [italia/anpr#3339]
Buongiorno,

la residenza che vedo indicata nel mio profilo da dove viene recuperata ? Per caso dal profilo dello SPID ? oppure dal database dell'anagrafica del comune ?

Saluti,
Nikolas.

**Comment by ncapozzi** [comment]
Buongiorno
i dati visualizzati sul portale ANPR dopo avere fatto LOGIN con SPID sono quelli comunicati dal Comune di residenza all'Anagrafe Nazionale.

**Comment by ncapozzi** [comment]
Esatto
