### ISSUE TITLE
Dichiarazioni di cambio di residenza - Aggiorna stato - P003

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#3341]
Buongiorno, chiamando il servizio di aggiorna stato P003, con il campo note valorizzato con una stringa più lunga di 100 caratteri si riceve errore: Internal Error (from client)

Nonostante nell'xsd tipoDato il tipoNote sia dichiarato di lunghezza massima 240.

Saluti
Laboratorio Dedagroup

**Comment by apaolacci** [comment]
Buongiorno,
se possibile potete condividere la request effettuata al P003 anche il solo campo note. La validazione sul tipoDato.xsd utilizzata per contenere il campo note riguarda la lunghezza dei caratteri (max 240) ma anche i caratteri utilizzati e la formattazione del testo (caratteri di fine linea, a capo).

Restiamo a disposizione.  Saluti

**Comment by LSPAG** [comment]
```xml
<con:RichiestaP003 xmlns:con="http://sogei.it/ANPR/P000sc" xmlns:n="http://sogei.it/ANPR/P000sc" xmlns:risp="http://sogei.it/ANPR/rispostaComune" xmlns:anpr="http://sogei.it/ANPR/vocabolarioP000sc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sogei.it/ANPR/P000sc
C:\Users\XXX\Desktop\Work\Anpr2022\Anpr032022\wsdlP000\P000sc.xsd">
	<testataRichiesta>
		<idOperazioneComune>538706</idOperazioneComune>
		<codMittente>040007</codMittente>
		<codDestinatario>ANPR02</codDestinatario>
		<operazioneRichiesta>P003</operazioneRichiesta>
		<dataOraRichiesta>2022-04-28T18:22:44.9730403</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>TEST</tipoInvio>
		<dataDecorrenza>2022-04-28</dataDecorrenza>
		<dataDefinizionePratica>2022-04-28</dataDefinizionePratica>
		<nomeApplicativo>XXX</nomeApplicativo>
		<versioneApplicativo>1.0</versioneApplicativo>
		<fornitoreApplicativo>XXX</fornitoreApplicativo>
	</testataRichiesta>
	<criteriAggiornamento>
		<codiceRichiesta>1240864</codiceRichiesta>
		<idStatoRichiesta>6</idStatoRichiesta>
		<note>SI RICHIEDONO COPIE CARTE IDENTITA' E COPIA DEL CONTRATTO DI LOCAZIONE
CON RICEVUTA DI REGISTRAZIONE</note>
		<operatore>COMUNETEST040007</operatore>
	</criteriAggiornamento>
</con:RichiestaP003>
```

In questo test abbiamo messo 101 caratteri, se il testo si riduce a 100 non da errore

**Comment by apaolacci** [comment]
Salve, 
il problema è il carattere che manda accapo la linea nelle note. Invocando con il testo di esempio 
_SI RICHIEDONO COPIE CARTE IDENTITA' E COPIA DEL CONTRATTO DI LOCAZIONE CON RICEVUTA DI REGISTRAZIONE TEST TEST TEST TEST TEST TEST_ (131 caratteri) non si rileva l'errore.

**Comment by LSPAG** [comment]
Grazie per il supporto, chiudo la issue.
Saluti
