### ISSUE TITLE
Errore EF002 Modifica grado di parentela a seguito di rimpatrio altro comune

### ISSUE THREAD

**Issue by averrando** [italia/anpr#3342]
Comune di Ventimiglia produzione,

Famiglia aire con 3 soggetti di competenza di Ventimiglia. In seguito al rimpatrio in altro comune di 2 soggetti, tentanto di modificare il grado di parentela del rimanente soggetto ancora iscritto in Aire di Ventimiglia otteniamo l'errore EF002. La famiglia aire con codice ANPR 55472887 risulta ancora attiva e con presente il soggetto ancora iscritto a Ventimiglia

Non riusciamo a capire qual'è il dato che bloccante, potete aiutarci ?

ID OPERAZIONE ANPR 867573821

Grazie

**Comment by ncapozzi** [comment]
Buongiorno
potete riprovare ad eseguire l'operazione per favore?

**Comment by averrando** [comment]
Buongiorno
Confermo che ora siamo riusciti ad eseguire l'operazione
Grazie mille
