### ISSUE TITLE
[ws 5008] Mutazione Dati - Errore EN527

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3344]
ambiente di PRODUZIONE - comune di MEDICINA (037037)

nel tentativo di inviare una mutazione sul soggetto con idANPR 154209158 otteniamo questo errore:
```
	<errore>
		<codiceErroreAnomalia>EN389</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>La data decorrenza 29-04-2022 dell'operazione non puo' essere inferiore alla data decorrenza errore da GET_CARTA_IDENTITA esito:999 dell'ultima operazione effettuata sui dati relativi a @</testoErroreAnomalia>
	</errore>
```
(Informazioni sull'operazione da fornire in caso di assistenza : data 2022-04-29 16:19:17 , idOperazioneANPR 868056553)

non vediamo discordanza nelle date e non capiamo quale sia il problema segnalato dall'errore.
attendiamo vostro input.

grazie.
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare per favore?

**Comment by AMonopoliADS** [comment]
buongiorno. la comunicazione è stata inviata con successo.
grazie
