### ISSUE TITLE
Si è verificato un errore non gestito - ANPR - Utente LRSFNC86D08G273G

### ISSUE THREAD

**Issue by avvflarussa** [italia/anpr#3345]
Buongiorno,
alla richiesta di certificato di stato libero, dopo l'anteprima, appena clicco su Ottieni certificato, mi da l'errore di cui sopra.
Come posso risolvere?

Grazie

**Comment by cmigliardi** [comment]
buongiorno per favore può controllare se il certificato è stato prodotto ? lo trova nell'elenco dei certificati richiesti - grazie

**Comment by cmigliardi** [comment]
non abbiamo ricevuto più informazioni - 
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
