### ISSUE TITLE
SERVIZIO P003 - Modifica Stato 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3347]
Buongiorno,
Una richiesta di cambio di residenza, da stato 6 è passato a stato 7 dopo la integrazione da parte del cittadino.
Qualora tale integrazione non fosse sufficiente, come è possibile richiedere ulteriori integrazioni?.
Dallo schema lo stato 7 può passare a 5 o 4 ma non ritornare a 6.
Grazie

**Comment by apaolacci** [comment]
Buongiorno,
non è possibile sospendere nuovamente la pratica e richiedere nuova integrazione.  
Confermiamo come processo condiviso dal gruppo di lavoro e presente nel diagramma degli stati di lavorazione.
Saluti,
Assistenza ANPR
