### ISSUE TITLE
Mutazione tutti dati - ERRORE AEE95 

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3348]
Comune di POGGIOMARINO - PRODUZIONE

Buongiorno, per il soggetto con id ANPR 184367091 si invia mutazione tutti dati per variazione cognome, nome e luogo estero di nascita e si riceve il seguente errore:
AEE95 - Operazione non effettuabile - Cognome: XXXX Nome: YYYY  CF: <CODICE FISCALE>
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-05-02 13:03:34 , idOperazioneANPR 870028877 - 

Come occorre procedere?

Si ringrazia anticipatamente.
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno
il CF D..........Z319F indicato nella mutazione è base di un caso di omocodia. Quello corretto lo potete visualizzare da PuntoFisco oppure dalla web app di ANPR consultazione AE.
Dovete scrivere a entrate.archivioanagrafico@agenziaentrate.it, allegando tutta la documentazione necessaria a dimostrare che si tratta della stessa persona, chiedendo il collegamento tra D............Z319S e il CF che risolve l'omocodia.
