### ISSUE TITLE
Soggetto non individuato in AT - Codice fiscale NON variato (Cod: EAM12 )

### ISSUE THREAD

**Issue by OsimoComune** [italia/anpr#3349]
Buongiorno,

Per il soggetto id scheda anpr 105154225, non riusciamo a variare il nome, data di nascita e CF, con mutazione tutti i dati dà il seguente errore

Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-05-02 16:34:50 , idOperazioneANPR 870332709 (Codice: EN527)

con risoluzione disallineamenti dà l'errore
![image](https://user-images.githubusercontent.com/104777929/166254921-a6d62db7-85cd-427a-94f6-281e552c6aac.png)

I dati corretti sono quelli in AE

Si chiede gentilmente se è possibile risolvere il problema?
Grazie
Cordiali saluti
Comune di OSIMO (AN)

**Comment by rvinzani** [comment]
Deve essere effettuata una mutazione tutti i dati con cui sostituire codice fisale e dati anagrafici secondo quanto presente in agenzia entrate
