### ISSUE TITLE
[Test subentro] Atto Nascita località estera

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#335]
Buongiorno,
vorrei chiedere aiuto su come procedere nei casi in cui nell'Atto di Nascita dell'APR locale compare una località estera nel campo "ComuneRegistrazione". 
Infatti, da quanto risulta dalle specifiche ANPR questo campo accetta solo Comuni italiani (giustamente per logica, ma a quanto sembra non nella pratica). Devono essere bonificati preventivamente?
Grazie

Bistagno (AL) Codice ISTAT: 006017
Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
In anagrafe si riportano gli estremi degli atti di stato civile italiani. Se l'atto è formato all'estero e non è trascritto in Italia, a mio parere non si trasferisce in anpr.

**Comment by Eduardo1977** [comment]
Grazie

**Comment by gianlucaspano** [comment]
Ciao, mi chiamo Gianluca Spano' e lavoro per PA Digitale Sicilia (URBI). 
In particolare mi occupo dell' assistenza, non lavoro come sviluppatore anche se in passato lo sono stato.
Ad oggi ho diversi comuni che non accettano di rimuovere le informazioni di nascita dall' estero nel campo iscrizione atto di nascita.

Ma i comuni mi citano sempre la norma del vigente Ordinamento di Stato Civile, art. 66 -125- 137 dove Atti di nascita, Matrimoni e Morte provenienti dall'estero tramite l'autorità Consolare sono classificati come trascrizioni, e come tali sono registrati dall'ufficio di stato civile. 
Proprio per questo non accettano di svuotare l' iscrizione, dove hanno inserito il comune estero e il numero di atto, e lasciano vuoto parte e serie che questi atti dall'estero non hanno.
Ovviamente questo genera errore nella diagnostica ANPR.

Ho controllato le specifiche tecniche e non è specificato, nella formazione dell' atto, che il comune deve essere italiano(atto.xlsx), mentre nei codici errore (error_anpr.xlsx) viene segnalato il classico comune incongruente perché non presente nella tabella di riferimento, che penso  contenga solo quelli italiani.

A questo punto per convincere questi ufficiali anagrafe avrei bisogno di un riferimento normativo, o di un documento di intesa ANPR-SOGEI, o qualunque altra cosa con cui poter convincere i comuni a rinunciare, e quindi cancellare (e sono veramente riluttanti), tutti i dati esteri che hanno inserito in iscrizione dell' atto. 
Vi anticipo che ignorano la documentazione tecnica perchè ho già provato, vi chiedo cortesemente di darmi una mano in quanto non ho trovato nulla su questo argomento nel sito ANPR. 

Grazie in anticipo

Gianluca Spano'
PA Digitale Sicilia S.r.l

**Comment by gcarbonin** [comment]
Non si trova nulla in quanto si dà per sottinteso che gli estremi da indicare facciano riferimento al registro di stato civile italiano; per eventi avvenuti all'estero, l'atto viene trascritto e si dovrebbero riportare gli estremi dell'atto trascritto non di quello originale.

**Comment by bfilipazzi** [comment]
Buongiorno Spanò,
non entro nel merito ma faccio un'osservazione oggettiva: il regolamento di stato civile vigente (DPR 336 del 2000) ha 110 articoli, quindi il 125 e il 137 citati dai suoi clienti non esistono. Il 66 non c'entra perché tratta il caso del matrimonio in cui lo sposo non è in grado di comunicare.
Filipazzi - Maggioli

**Comment by gianlucaspano** [comment]
L' ordinamento di Stato Civile che mi comunicano è il DPR 396 del 2000, che abroga il regio decreto 9 luglio 1939, n. 1238 ad esclusione degli articoli 14, 16, 25, 29, 32, 33, 35, 36, 37, 38, 39, 59, 60, 124, **125**(matrimonio), 134, 136, **137**(morte).
Per quanto riguarda il **66** comma 1 (gli atti di nascita ricevuti all'estero) appunto abrogato, è stato praticamente ricopiato nel **28** comma 2b del 396/2000.
Come avrete capito ho proprio bisogno di "_assistenza legale_" perché dall'altra parte mi ritrovo un ufficiale di S.C. della vecchia guardia.

**Comment by bfilipazzi** [comment]
Non avevo collegato i numeri al decreto del '39.
Filipazzi - Maggioli
