### ISSUE TITLE
Residenza in convivenza

### ISSUE THREAD

**Issue by StellaFalqui** [italia/anpr#3351]
Ho necessità di scaricare il certificato di convivenza ma nonostante nell’anagrafica risulti il contratto di convivenza nell’area dei certificati scaricabili non mi risulta selezionabile l’opzione di residenza in convivenza o contratto di convivenza.
Ho urgenza di scaricare il documento.

**Comment by mttfranci** [comment]
Salve, cortesemente potrebbe fornirci il suo codice identificativo ANPR, disponibile nella sezione Generalità dell'area Visua e autocertificazioni? (Non si tratta di un dato particolarmente sensibile, ma ci aiuterebbe nella verifica)
Grazie in anticipo.
Saluti

![image](https://user-images.githubusercontent.com/29305782/166631599-2953f24a-f60f-4bbe-86ad-8c2cec022e49.png)

**Comment by StellaFalqui** [comment]
Il codice  ANPR è 39105716.
Grazie.

**Comment by mttfranci** [comment]
Salve, 

il certificato di "residenza in convivenza" non riguarda le persone che vivono in convivenze (ad esempio Caserme o Prigioni).
Quindi questo primo certificato non si applica affatto alla sua situazione.

Invece quello del "contratto di convivenza" riguarda persone che abitano in normali famiglie ma hanno registrato una convivenza di fatto tra due persone coabitanti.
Questo secondo certificato si applicherebbe alla sua situazione, ma non è registrata la data di stipula.
Pertanto il certificato non può essere emesso.

Dovrebbe provare a rivolgersi al suo comune di competenza.

Saluti
