### ISSUE TITLE
Buongiorno, Comune di Colle Umberto. Possiamo cortesemente essere contattati in merito alla nuova funzione di richiesta iscrizione residenza direttamente da ANPR? La nostra software house Halley provvederà all'aggiornamento per rendere automatiche le notifiche solamente dopo il 12 giugno. Grazie in anticipo. Cordiali saluti.

### ISSUE THREAD

**Issue by COLLEUMBERTO** [italia/anpr#3353]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by Hdemografici** [comment]
Buongiorno, interveniamo solo per sottolineare come la versione dell'applicativo Halley contenente l'integrazione con ANPR relativamente alle istanze di dichiarazione anagrafiche presentate da portale ANPR (circolare Dait 36/2022) è disponibile per l'aggiornamento ai Comuni da prima del 27/04/2022, data di esposizione dei servizi per tutti i Comuni.
 La data del 12 giugno cui fa riferimento il Comune è solamente legata alla data di aggiornamento automatico massivo; la cosa è stata chiarita con il Comune.
 Saluti
