### ISSUE TITLE
Che fare se una richiesta non viene evasa e resta APERTA?

### ISSUE THREAD

**Issue by gmacar** [italia/anpr#3354]
Salve, ho chiesto la rettifica del mio indirizzo anagrafico (rettifica, non cambio di indirizzo) ma ho l'impressione che nessuno abbia preso in carico la richiesta, la quale resta sempre APERTA senza alcun avviso mentre il tempo passa. Cosa fare in questi casi?

**Comment by ncapozzi** [comment]
Buongiorno,
in primo luogo può verificare da "Visura e autocertificazioni" se l'indirizzo è stato comunque modificato anche se la richiesta risulta tuttora aperta.
Qualora così non fosse le suggeriamo di contattare l'ufficio anagrafe del Comune di residenza sollecitando la rettifica.
