### ISSUE TITLE
La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti (Codice: EN087)

### ISSUE THREAD

**Issue by LorenzoUggeri** [italia/anpr#3356]
Buongiorno,

Comune di BAGNACAVALLO id operazione 255299 - in fase di rilascio di certificati (richiesta 6001) è stato restituito l'errore "La ricerca per comune di nascita ha estratto un soggetto o piu' soggetti con i restanti dati anagrafici non congruenti (Codice: EN087)" per la scheda soggetto 18515295. Sono stati controllati tutti i dati, anche la validità del comune al momento della nascita, ma non sono state riscontrate anomalie. 
Come è possibile risolvere il problema?

Grazie!

**Comment by frmariani** [comment]
Potete riprovare per favore ?

**Comment by LorenzoUggeri** [comment]
Abbiamo provato. Ora sembra funzionare tutto correttamente, grazie mille!
