### ISSUE TITLE
[1014] Chiarimento su procedimenti

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#336]
Posso aprire un qualsiasi procedimento e collegarlo o mano a un successivo evento anagrafico, esempio cancellazione per l'estero di straniero oppure mutazione dati.
La domanda è qualora venga chiuso il procedimento con esito "negativo/rigetto", devo aspettarmi una "rollback" delle variazioni collegate a quel procedimento?

**Comment by gcarbonin** [comment]
Non si effettua alcun aggiornamento sulle variazioni collegate al procedimento
