### ISSUE TITLE
[WEBAPP] Emissione certificato: Errore EN181

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#3360]
Comune di Montoro (AV)

Stiamo tentando di emettere un certificato cumulativo di stato civile e residenza per i cittadini con ID:
- 87019736
- 30583349
ma per entrambi riscontriamo lo stesso errore in fase di emissione: 
**Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato (Codice: EN181)**

Andando a consultare per ognuno dei due cittadini l'elenco degli eventuali procedimenti amministrativi si ottiene il seguente messaggio:
**EN122 La richiesta effettuata non produce alcun risultato**

**Comment by cmigliardi** [comment]
buongiorno ci può fornire un recapito ? Lei è dell'ufficio anagrafe ?  grazie così la possiamo contattare

**Comment by vix-db** [comment]
No, rappresento l'azienda che supporta il Comune sulle attività ordinarie in ANPR.
Potreste contattare giovedì p.v. l'ufficio demografici allo 0825-502021 e chiedere di Salvatore Zito?
Lui è a conoscenza del problema.
Grazie.

**Comment by cmigliardi** [comment]
certamente chiamiamo giovedì -

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
