### ISSUE TITLE
Segnalazione Consolato MARACAIBO su territorio PAESI BASSI

### ISSUE THREAD

**Issue by stefaniaperico** [italia/anpr#3362]
Buongiorno,
scrivo per segnalare di aver ricevuto un avviso di anomalia relativo al consolato per la famiglia aire idFamAnpr = 38984198.
Tale famiglia ha la residenza presso la località estera di KRALENDIJK BONAIRE che fa riferimento al consolato di MARACAIBO associato a territorio estero PAESI BASSI; per me è tutto corretto, ma l'avviso invece segnala che il consolato è errato in relazione al territorio.
Posso semplicemente ignorare tale avviso oppure c'è qualcosa da fare?

Stefania Perico 
Comune di Albissola Marina

**Comment by stefaniaperico** [comment]
Buongiorno si comunica che l’indirizzo della persona è il seguente

 

KAYA SIRENA 8/a/BONAIRE SINT EUSTATIUS SABA KRALENDIJK  BONAIRE  (PAESI BASSI)

 

In attesa di un Vostro cortese riscontro porgo

Cordiali saluti

 

Stefania PERICO

 

 

Uffici Demografici

 

Comune di Albissola Marina

P.za del Popolo 12

Tel. centralino: 019400291 fax 019481528

e-mail generale: ***@***.***

pec: ***@***.*** 

Codice Fiscale 00333890093

Comune Certificato Ambiente

R.I.N.A. - ISO 14001

"Le informazioni contenute in questo messaggio possono essere riservate o confidenziali e sono

indirizzare esclusivamente al destinatario. Qualora non ne siate il destinatario, vi è fatto divieto di utilizzare,

copiare, divulgare o intraprendere qualsiasi azione basata su questo messaggio o sulle informazioni in esso

contenute. Se avete ricevuto questo messaggio per errore, Vi preghiamo di comunicare immediatamente al

mittente l'accaduto e di cancellare il messaggio. In ogni caso l'Ente si dissocia da qualsiasi

affermazione o opinione contenute nei messaggi inviati dalla propria rete che non siano strettamente inerenti

all'attività dello stesso."

 

Da: ncapozzi ***@***.*** 
Inviato: lunedì 9 maggio 2022 17:02
A: italia/anpr
Cc: stefaniaperico; Author
Oggetto: Re: [italia/anpr] Segnalazione Consolato MARACAIBO su territorio PAESI BASSI (Issue #3362)

 

Buonasera
l'unico consolato di riferimento per i Paesi Bassi è l'Aja. Se la famiglia ha residenza in KRALENDIJK BONAIRE e come Consolato di riferimento Maracaibo, vuol dire che risiede in questo territorio
540 BONAIRE, SINT EUSTATIUS, SABA
che ha come stato sovrano i Paesi Bassi.
Potete verificare per favore?

**Comment by ncapozzi** [comment]
Buongiorno
l'indirizzo trasmesso sembrerebbe congruente con quanto precedentemente indicato (540 BONAIRE, SINT EUSTATIUS, SABA).
Potete chiedere conferma al Consolato di riferimento.
Per la modifica in ANPR è necessario effettuare una mutazione famiglia/convivenza con tipo = 9 rettifica/integrazione indirizzo
