### ISSUE TITLE
CERTIFICATI ANPR NON DISPONIBILI

### ISSUE THREAD

**Issue by RedFoxDie** [italia/anpr#3364]
Salve,
sul sito ANPR sono disponibili solamente 2 certifcati.
È possibile fare una verifica del perché?

Codice fiscale: DLLLRD**********
Data di nascita: 26/12/1986

Grazie.

**Comment by cvignati** [comment]
Probabilmente non avrà Certificabilita Completa, ma Parziale nella scheda soggetto

**Comment by ncapozzi** [comment]
Si, deve rivolgersi al Comune di residenza

**Comment by RedFoxDie** [comment]
Grazie, confermo che è stato risolto.
