### ISSUE TITLE
Nella scelta dei comuni manca Comune di Roma

### ISSUE THREAD

**Issue by NikolasMajan** [italia/anpr#3365]
Salve,

durante il login dall'app dove bisogna scegliere il proprio comune: Nella scelta dei comuni manca Comune di Roma.

Durante il cambio di residenza: Nella scelta dei comuni manca Comune di Roma.

![image](https://user-images.githubusercontent.com/69528210/167383017-1774c12b-983b-4a3e-9ccb-3d369f471393.png)

**Comment by ncapozzi** [comment]
Buonasera
come da comunicazioni pubblicate per il Comune di Roma, in attesa del completamento degli
interventi tecnici, sino al 30/06/2022 il servizio di cambio di residenza on line è disponibile sul portale dello
stesso Comune.
