### ISSUE TITLE
Scarico comune massivo

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3368]
Per cambio software abbiamo inserito una richiesta di scarico massivo per il comune di Monte Argentario.
Ad oggi, rientrando per il download, compare sempre il messaggio: Errore. Il sistema è momentaneamente non disponibile"
Potreste darci un suggerimento?
Saluti

**Comment by mttfranci** [comment]
Potete confermarci l'ambiente (produzione?) e l'id della richiesta?
Grazie in anticipo.
