### ISSUE TITLE
Scarico ANPR per motivata richiesta

### ISSUE THREAD

**Issue by luca-teamdigitale** [italia/anpr#337]
Ogni municipalità deve avere la possibilità di effettuare uno scarico di ANPR per motivata richiesta. Esempi di motivata richiesta: (1) In seguito ad un disastro l'infrastruttura locale deve essere ripristinata, oppure (2) la tecnologia dell'infrastruttura locale deve cambiare radicalmente, come nel caso di passaggio da un fornitore software ad un altro.

Questa issue traccia la creazione dei meccanismi/processi tecnici necessari per effettuare lo scarico.

**Comment by luca-teamdigitale** [comment]
Questo documento redatto da SOGEI descrive una prima proposta di processo: https://docs.google.com/document/d/1FiBOOE8108bSChHOtoXZj_y4y-U5N8f5pWbYLRAU3A8/edit .

Aiutateci con i vostri commenti e suggerimenti. Grazie.

**Comment by bfilipazzi** [comment]
Si può avere documentazione del formato dei dati con cui sarà fornito lo scarico? Grazie.
Filipazzi - Maggioli.

**Comment by gcarbonin** [comment]
Il tracciato non è stato ancora definito

**Comment by mccalv** [comment]
Riteniamo comunque che sia corretto assumere che sia quello analogo se non
identico al subentro.

Il 07 mar 2018 13:07, "gcarbonin" <notifications@github.com> ha scritto:
