### ISSUE TITLE
CAMBIO NOME ERRORE AEE95

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#3371]
Operazione di cambio nome per persona con codice fiscale OMOCODICE

N. Indiv. ANPR  23261922- Modifica nome  da Marco a Marco Alfredo- Soggetto Marcato ANPR e Validato AE
Operazione ID ANPR 880094282 11/5/2022 ore 16:33:42
Errore AEE95 Operazione non effettuabile
Potreste dirmi come risolvere il problema grazie

**Comment by frmariani** [comment]
Per la rettifica di un CF omocodice deve essere contattata la Direzione Centrale dell'Agenzia delle Entrate inviando tutta la documentazione necessaria a supporto 
entrate.archivioanagrafico@agenziaentrate.it

**Comment by LORELLAB** [comment]
ho già richiesto il cambio di generalità e l'attribuzione del nuovo codice fiscale a [entrate.archivioanagrafico@agenziaentrate.it]come suggerito nella segnalazione.
Il nuovo CF è stato assegnato, ma non riesco ad allineare Anpr con AE, sia dal mio applicativo che dalla webapp.
Questo è il messaggio d'errore:
Esito ANPR: Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2022-06-06 13:00:21 , idOperazioneANPR 904168124(Codice: EN527)
Una precedente segnalazione #1660 è stata chiusa con un vostro intervento diretto.
Chiedo indicazioni su come risolvere il problema.
Grazie

**Comment by LORELLAB** [comment]
Problema risolto con Agenzia Entrate ed Assistenza ANPR Grazie
