### ISSUE TITLE
cambio di residenza servizio p003

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#3374]
Buongiorno, in ambiente di test comune di Satriano di lucania 076083  sto tentando di rendere irricevibile una richiesta di cambio di abitazione. 
In Allegato gli xml di un paio di operazioni.
[richieste.zip](https://github.com/italia/anpr/files/8686156/richieste.zip)

ottengo sempre errore 999 operazione non effettuabile.
Potreste verificare il perchè?
Grazie.

**Comment by apaolacci** [comment]
Buongiorno,
è possibile provare ad invocare correggendo il tag operazione richiesta nell'xml di request ?

`  <operazioneRichiesta>POO3</operazioneRichiesta>`

Saluti,
Assistenza ANPR

**Comment by mcaputo75** [comment]
Buongiorno, ho corretto l'errore nella richiesta (Svista dell' ultimo secondo), ma adesso ho un SoapFault per la richiesta.
Cosa Sbaglio? Perche leggendo l'xsd sembra corretto. In allegato la richiesta
[80175-WSP003-TEST.zip](https://github.com/italia/anpr/files/8697796/80175-WSP003-TEST.zip)
Grazie

**Comment by apaolacci** [comment]
Buongiorno,
i tag sono in xs:choice mutuamente esclusivi per cui va passato 
`richiestaProroga`  nel caso di richiesta di rettifica di cui si vuole prorogare la data di scadenza oppure `idStatoRichiesta` valorizzato con id stato si vuole impostare un nuovo stato per la richiesta (rettifica o cambio di residenza).

Saluti,
Assistenza ANPR

**Comment by mcaputo75** [comment]
perfetto grazie  mille.
