### ISSUE TITLE
Mancato funizonamento Risoluzione Disallineamenti con Agenzia Entrate

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3375]
Buongiorno,
oggi la funzione Risoluzione disallineamenti con Agenzia Entrate restituisce per tutti i CF

La pagina non funzionaweb.anpr.interno.it non ha inviato dati.
ERR_EMPTY_RESPONSE

Grazie
Anna Maria AIMONE
Upi Torino

**Comment by ncapozzi** [comment]
Buonasera,
ci potete confermare che il problema non si presenta più?

**Comment by UpiTorino** [comment]
Confermo che ha ripreso a funzionare correttamente
Buona serata

Il lun 16 mag 2022, 17:52 ncapozzi ***@***.***> ha scritto:
