### ISSUE TITLE
Operazione non effettuabile (Codice: AEE96)

### ISSUE THREAD

**Issue by DanielCarenzo** [italia/anpr#3376]
Buongiorno a tutti,

al comune di Ventimiglia (IM) non è possibile attribuire un codice fiscale per un soggetto Aire.
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-05-16 11:43:55 , idOperazioneANPR 884569102 (Codice: EN527)

La particolarità è che questo soggetto ha nel cognome ben 2 trattini a separazione dei cognomi, non so se questo può comportare delle anomalie.

Attendo riscontro

_Daniel Carenzo
C&C Sistemi Srl_

**Comment by ncapozzi** [comment]
Buongiorno,
confermiamo che al momento in Agenzia delle Entrate i caratteri “-“ e apice sono accettati nell’anagrafica del soggetto, ma solo se “singoli” e comunque mai in prima posizione.
