### ISSUE TITLE
ANPR (ACCESSO SPID ANOMALIA)

### ISSUE THREAD

**Issue by Emaoli22** [italia/anpr#3377]
Buongiorno. Sto avendo problemi ad accedere al servizio ANPR con accesso SPID. (Iscritto AIRE) Mi da un messaggio che indica che c’è un anomalia e di contattare il comune di residenza. Mi chiedevo se fosse possibile per voi risolvere il problema dato che ho trovato altri utenti che in passato hanno avuto lo stesso errore ed hanno risolto grazie a voi. 

Cordiali saluti 
Emanuele

**Comment by cmigliardi** [comment]
buongiorno per favore ci può fornire le prime 6  lettere  del suo codice fiscale ?  facciamo un controllo . grazie

**Comment by Emaoli22** [comment]
Buongiorno.

LVOMLN

Cordiali saluti
Emanuele

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1988  ci risulta un doppio nome - che va allineato dal comune di ACRI  in  Anpr verificando i dati con agenzai delle entrate -   spero di esserle stata  di ausilio -

**Comment by Emaoli22** [comment]
Molto utile. Ipotizzavo un problema del genere.

Le auguro una buona giornata.

**Comment by cmigliardi** [comment]
di nulla,  

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
