### ISSUE TITLE
Subentro ambiente di test comune di Aldeno

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3380]
Buongiorno, ieri nel pomeriggio ho inviato i dati per subentro ambiente di test per il comune di Aldeno ma ancora non e' partito il caricamento dei dati.
Potete provvedere.
Grazie

**Comment by galliandrea** [comment]
Si richiede con urgenza riscontro su problematica segnalata

**Comment by amollicone1982** [comment]
subentro completato con successo. Abbiamo avuto un problema nell'invio della mail
