### ISSUE TITLE
CAMBI RESIDENZA - RICHIESTE DA CITTADINI

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3381]
Buongiorno,
COMUNE DI CASERTA
DOMANDE:
1) Una richiesta nello stato 7 (integrata) può essere ancora integrata dal cittadino con altri allegati?
2) Per quanto tempo è possibile avere un pratica nella fase 6 in attesa di integrazioni?
Grazie

**Comment by gppbarone** [comment]
Buongiorno, in merito alla prima domanda: 
Un cittadino, una volta che invia tramite apposito pulsante nell'area autenticata di Servizi al Cittadino la sua integrazione, la pratica passa nello stato 7 di "Integrata" e non è più possibile fare ulteriori azioni lato Cittadino, quindi non è possibile più allegare documenti ecc.. 
In merito alla seconda domanda per una richiesta di Cambio di Residenza: una pratica nello stato 6 (Sospesa) può restare in quello stato per un tempo indefinito, non esiste nessun automatismo. 
La data di scadenza fa riferimento solo ai due giorni successivi l'invio della Dichiarazione di Cambio di Residenza entro i quali il Comune per norma dovrebbe iniziare la lavorazione.
In merito alla seconda domanda per una richiesta di Rettifica dati: una pratica nello stato 6 (Sospesa) può restare in quello stato per un tempo indefinito, non esiste nessun automatismo. 
La data di scadenza della pratica fa riferimento ai 30 giorni successivi all'invio della Rettifica dati. 
E' possibile prorogare la data (solo in caso di Rettifica dati) negli stati "IN LAVORAZIONE" e "INTEGRATA" e se si è a 5 giorni dalla scadenza.

**Comment by rinonasti** [comment]
OK grazie
