### ISSUE TITLE
 RICHIESTE DI RETTIFICA DATI TRASMESSE DAI CITTADINI

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3382]
Buongiorno,
accedendo al servizio Rettifiche, la rettifica segnalata dal cittadino non è visualizzabile se non dopo averla ricercata. 
Fino a qualche giorno fa era possibile visualizzare le Rettifiche da evadere accendo direttamente alla videata.

Buona giornata
UPI TO

**Comment by apaolacci** [comment]
Buongiorno, 
è necessario utilizzare le funzionalità di ricerca delle richiesta di Rettifica e delle dichiarazioni di cambio residenza, non è più possibile visualizzare con le ricerche automatiche.

Saluti
