### ISSUE TITLE
Problema scarico notifiche N010

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3383]
Un nostro comune da diversi giorni non riesce a chiudere la richiesta di scarico di notifiche con ID **884765432** del tipo N010. Il sistema risponde sempre:

**La richiesta è ancora in elaborazione da parte di ANPR. Si prega di riprovare più tardi**

Grazie.

Alessio Tropeano

**Comment by SilviaRivi** [comment]
Salve, anche diversi nostri comuni hanno riscontrato lo stesso problematica qui sopra indicata.

Segnalo quindi che non si riesce a chiudere la richiesta di scarico di notifiche 
con ID 882903007, 883432893, 890837149 ed è in questo stato dal **14 Maggio**.
Fanno riferimento alla verifica Stato della richiesta idOperazioneANPR= 882903005 del tipo N010.
Il sistema risponde sempre:

La richiesta è ancora in elaborazione da parte di ANPR. Si prega di riprovare più tardi

In attesa di risposta

Grazie
Silvia Rivi

**Comment by mttfranci** [comment]
Salve, potreste verificare nuovamente se sono disponibili?
Saluti

**Comment by MarcoSalaPad** [comment]
Buongiorno, 
purtroppo i nostri clienti tutt'ora non riescono ad acquisire le notifiche che vi ho segnalato in precedenza.
Ve ne segnalo una "nuova", con id 896587679 legato alla notifica N010 di CAMBIO RESIDENZA del 27/5

Rimaniamo in attesa
Grazie
Marco Sala

**Comment by edoardodona-1** [comment]
Anche diversi nostri comuni hanno ancora il problema delle N010.
Dona' X DATAMANAGEMENTITALIA . 338 59 09 376.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Problema scarico notifiche N010 (Issue #3383)" inviata il 31/05/2022
14:54:12.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
