### ISSUE TITLE
Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato

### ISSUE THREAD

**Issue by fehg90** [italia/anpr#3384]
Buongiorno

sto  cercando di scaricare un certificato, però il sito: https://www.comune.milano.it/fascicolo-del-cittadino/i-miei-dati non fa avviare una nuova pratica perchè dice che ce n'è già una in corso. Effettivamente avevo avviato una pratica per il cambio di residenza però quella è andata a buon fine ed è conclusa. come posso fare?

**Comment by cmigliardi** [comment]
salve, per favore mi può inviare il messaggio che riceve ? il sito è del comune di Milano non so se poi approda a quello di Anpr - grazie

**Comment by cmigliardi** [comment]
attendo sue notizie, altrimenti non so come poterle esser di ausilio - grazie

**Comment by fehg90** [comment]
Salve
il sito è del comune di milano, fa parte del sito relativo al fascicolo del
cittadino. Per comodità allego uno screeshot:
[image: image.png]
Al momento non ho alcun procedimento aperto. L'altro procedimento che ho
fatto è stato per il cambio di residenza ma è già stato completato e chiuso
(anche se temo sia questo il problema):
[image: image.png]
Questo è quanto.
Grazie
Filippo

Il giorno lun 23 mag 2022 alle ore 15:15 cmigliardi <
***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
quindi non è il portale del Ministero dell'Interno 
www.anagrafenazionale.interno.it  - dove noi abbiamo la visibilità

**Comment by fehg90** [comment]
No non è il sito del ministero dell'interno.
Una domanda: dal vostro sito è possibile scaricare il certificato di stato
civile dove è indicato se sono celibe o sposato?
Grazie
Filippo

Il giorno mar 24 mag 2022 alle ore 09:13 cmigliardi <
***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
certamente tutti quelli riconosciuti dal Ministero sono 14 tipologie . 
si accede con spid - cie - cns -   il sito  è   www.anagrafenazionale.interno.it    -  mi faccia sapere  semmai mi invii se vuole le prime 6 lettere   del suo codice fiscale. che controllo

**Comment by fehg90** [comment]
Purtroppo accedendo al sito indicato e poi con Spid, mi fa solo scaricare
il certificato di residenza e quello di Stato di famiglia dove però non è
indicato che sono celibe. Se mi potesse aiutare: le prime 6 cifre del mio
CF sono MRCFPP.
Grazie

Il giorno mar 24 mag 2022 alle ore 09:33 cmigliardi <
***@***.***> ha scritto:

**Comment by fehg90** [comment]
Le ho scritto alla mail indicata
Grazie

Il giorno mar 24 mag 2022 alle ore 11:50 cmigliardi <
***@***.***> ha scritto:

**Comment by cmigliardi** [comment]
sì grazie le  ho risposto in privato. 

La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa
