### ISSUE TITLE
TipoDato.xsd release del 08032022

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#3385]
Buongiorno, nell'ultima release che è stata rilasciata ho notato che i file tipodato.xsd dei vari servizi sono diversi tra di loro. In particolar modo nel file tipodato.xsd del servizio p000 si differenzia per un tipoDataAnagrafica che viene richiamato in tutti i campi che riguardano date del servizio in questione. Fin quà ci potrebbe stare... ma se prendiamo gli altri servizi il campo data continua ad essere un xs:date e qui sorge il problema.
Anche perchè come specificato all'interno di un qualsiasi file tipodato.xsd c'è una parte in comune per tutti che però nel caso del 
p000  si differenzia per questo tipoDataAnagrafica.

Io ho rigenerato il tutto usando il tipodato.xsd del servizio p000 con il risultato che funziona il p000 e non funziona piu tutto il resto.

Cosa ho sbagliato?

Grazie.

**Comment by mttfranci** [comment]
Buongiorno, il tipo dati reale utilizzato è comunque un xs:date, noi non abbiamo avuto problemi di compatibilità e finora nessuno degli altri software che hanno integrato il servizio e che lo stanno usando ci hanno segnalato problemi in tal senso (visto che il tipo base è lo stesso).

In generale noi non forniamo supporto all'implementazione con le specifiche tecnologie usate, ma di preciso che problema riscontrate con gli altri servizi? (come estrema ratio, bell'immediato potreste anche sostituire di nuovo il tipoDataAnagrafica con un xs:date e rigenerare il software).

Saluti

**Comment by mcaputo75** [comment]
In Generale mi da un un SoapFault e validando la richiesta il problema è proprio sulle date. Adesso provo a modificare il tipodato.xsd del servizio p000 e provo a rigenerare il tutto.

**Comment by mcaputo75** [comment]
Ho risolto sostituendo con xs:date
Grazie

**Comment by mttfranci** [comment]
Prego. buona giornata.
