### ISSUE TITLE
Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato

### ISSUE THREAD

**Issue by whitenoyze** [italia/anpr#3386]
Ciao, sto provando a richiedere un certificato di cittadinanza sul sito del comune di Milano, ma ricevo l'errore in oggetto. Forse perchè ho da poco cambiato residenza
Potete aiutarmi? grazie

**Comment by cmigliardi** [comment]
salve ci può dire se poi accede al portale del ministero dell'interno? oppure fa la richiesta dal portale del comune?  nella seconda ipotesi  - non  abbiamo visibilità - grazie

**Comment by whitenoyze** [comment]
> salve ci può dire se poi accede al portale del ministero dell'interno? oppure fa la richiesta dal portale del comune? nella seconda ipotesi - non abbiamo visibilità - grazie

Buongiorno, ho provato anche dal portale del ministero dell'interno, ma non vedo il certificato di cittadinanza tra quelli selezionabili. Trovo solo quello di residenza e di stato di famiglia.
![Cattura](https://user-images.githubusercontent.com/32167589/169972785-8b90815d-08c7-4e16-b6dc-311f61c7916b.PNG)

**Comment by cmigliardi** [comment]
ok - molto probabilmente ho a una certificabilità parziale  o un procediemnto aperto sulla scheda . ci può fornire le prime 6 lettere del suo codice fiscale ? grazie  - approfondiamo

**Comment by whitenoyze** [comment]
> ok - molto probabilmente ho a una certificabilità parziale o un procediemnto aperto sulla scheda . ci può fornire le prime 6 lettere del suo codice fiscale ? grazie - approfondiamo

MNTFNC. Grazie

**Comment by whitenoyze** [comment]
> se è lei la persona del '55 la invito a recarsi in comune - altrimenti mi dia maggiori elementi perché con 6 lettere non riesco ad avere un'unica scheda da verificare - grazie

Ciao, no sono dell'88. Mi dica se serve altro, grazie

**Comment by cmigliardi** [comment]
mi spiace siete in troppi - le scrivo il mio indirizzo di posta - se vuole mi occorre il cf completo . decida  liberamente se inviarmelo o no.  -  grazie -   cmigliardi@sogei.it

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by cmigliardi** [comment]
non possiamo segnalare - non è di nostra competenza - noi possiamo dare ausilio a lei di carattere generale
