### ISSUE TITLE
[3002] documento contrattoStiputa convivenzadifatto

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3387]
Buongiorno, 
vorrei sapere se nella risposta è corretta la valorizzazione del tag documento relativo al contratto della convivenza di fatto?

negli XSD il tag è previsto ma nella documentazione "specifiche di interfaccia" in formato excel (che non trovo più nel sito) nel file documentoProtocollato.xls sotto la cartella "oggetti" nelle note è riportato "E' un  campo ad esclusivo uso dell'applicazione WEB ANPR"

idOperazioneANPR 891759541 per il comune 075002 in PRODUZIONE

Grazie mille

**Comment by rvinzani** [comment]
Confermo che il documento più essere acquisito solo tramite web app, quindi tale campo è ad uso solo dell'applicazione web

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[3002] documento contrattoStiputa convivenzadifatto (Issue #3387)" inviata
il 01/06/2022 15:31:25.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by Hdemografici** [comment]
Buongiorno, 
grazie per la risposta, quindi è corretto che nella risposta della 3002, idOperazioneANPR 891759541 per il comune 075002 in PRODUZIONE, sia valorizzato?
