### ISSUE TITLE
VARIAZIONE DATI ANAGRAFICI - SUPERAMENTO LIMITE DI VARIAZIONI

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#3389]
Buonasera, 
il soggetto  ID ANPR 19149205 con  codice fiscale f 33839489003 ha variato le seguenti generalità:

cognome - nome - giorno - mese e anno di nascita

e in Agenzia delle Entrate è presente anche  il codice fiscale alfanumerico con le generalità nuove
 
Dalla web app anpr - risoluzioni disallineamenti con AE - non siamo  riusciti  a variare i dati perchè superano il limite di variazioni. Abbiamo provato  anche la mutazione di tutti i dati, variando anche il cf ma non si riesce.

Chiedo pertanto se è possibile sbloccare la posizione al fine di procedere alla variazione e al collegamento delle due posizioni

Grazie
Comune di Faenza
BARBARA MALAVOLTI

**Comment by frmariani** [comment]
sono possibili fino a 3 variazioni dei dati anagrafici; nel vostro caso dovete contattare la direzione centrale dell'Agenzia delle Entrate inviando tutta la documentazione che giustifichi tale variazione

**Comment by bmalavolti** [comment]
Buongiorno
l'Agenzia delle Entrate ha collegato in anagrafe tributaria il codice fiscale 33839489003 al cf principale SLMLAX86S09Z249H
Da ANPR  - RISOLUZIONE DISALLINEAMENTI CON AGENZIA ENTRATE l'Esito AE: Variazione non consentita per superamento numero campi variati (Codice 93)
Chiedo pertanto di sbloccare la posizione al fine di variare i dati corretti del cittadino
grazie
Barbara Malavolti

**Comment by frmariani** [comment]
I due codici fiscali sono stati già collegati quindi deve procedere con l'operazione di modifica dei dati anagrafici, anche da gestionale se preferisce.
Mi faccia sapere.

**Comment by bmalavolti** [comment]
Abbiamo risolto reinviando da gestionale il ws della rettifica 
Grazie
Barbara
