### ISSUE TITLE
Comuni in Pre Subentro

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#339]
Buongiorno è possibile sapere quanti comuni sono attualmente in pre subentro ed orientativamente quanti cittadini?

Grazie

Roberta Biasi
Dedagroup

**Comment by mccalv** [comment]
Ciao Roberta, a questo indirizzo hai dati aggiornati su tutta la popolazione in subentro e presubentro ed il numero comuni con dati aggiornati in via automatica settimanalmente.

https://dashboard.teamdigitale.governo.it/public/dashboard/2414d40b-9273-4e54-83ae-df346826fc53
Farà a brevissimo parte integrante del nostro sito istituzionale (teamdigitale.governo.it)

**Comment by Eduardo1977** [comment]
Caro @mccalv complimenti (a tutto il team) per le dashboard, le controllo spesso. Sarebbe possibile vedere anche la modalità (WA/WS) utilizzata da ciascun comune?

**Comment by mccalv** [comment]
Grazie @Eduardo1977! Pendiamo in considerazione il tuo suggerimento anche se come sai, ogni comune al subentro ha contemporaneamente accesso ad entrambe ma tutti i comuni subentrati usano prevalentemente o unicamente i Web Services.

Colgo l'occasione per specificare che i dati si aggiornano al momento ogni lunedì (ad oggi i comuni subentrati sono 18 e non 15).

**Comment by Eduardo1977** [comment]
Grazie a voi, disponibili come sempre.

**Comment by Eduardo1977** [comment]
Buongiorno @mccalv , volevo segnalare che stamattina sembra non funzionare lo scrolling nella pagina delle dashboard. Potresti dare un'occhiata appena possibile? Io sto provando con Firefox (aggiornato), che sia solo un mio problema?
Grazie

**Comment by mccalv** [comment]
Ciao @Eduardo1977 stiamo risolvendo una issue relativa al grosso carico di traffico che abbiamo avuto.
