### ISSUE TITLE
Cambio residenza - Convivenza di fatto 

### ISSUE THREAD

**Issue by IntrepidBug** [italia/anpr#3390]
Buongiorno a tutti. 
Volevo sapere, avendo fatto la richiesta sul sito del comune di Milano per il cambio di residenza, è necessario farne una nuova sul sito ANPR o comunicheranno tra di loro? Sto ancora aspettando, dopo tre giorni, che il comune di Milano mi confermi il cambio di residenza e infatti su tutte le piattaforme (ANPR, AdE, Regione Lazio) sono ancora residente in provincia di Latina. 

Inoltre io risulto in una convivenza di fatto al mio vecchio indirizzo, devo fare una rettifica tramite il servizio offerto sul sito ANPR?
Sul sito la rettifica viene espressa come uno strumento per modificare dati riportati erroneamente, i miei sono cambiamenti dati dal fatto che non sto più assieme a quella persona, per tanto non mi sembrava lo strumento adatto alla mia situazione. 

Se ho sbagliato qualcosa nel post chiedo scusa in anticipo e grazie a chi mi dedicherà il suo tempo.

**Comment by cmigliardi** [comment]
buongiorno, 
se ha fatto richiesta dal portale del comune di Milano deve rivolgersi al comune. quando il comune effettuerà il cambio di residenza  la norma prevede che lo comunichi istantaneamente all' Anpr.

**Comment by cmigliardi** [comment]
non deve utilizzare il servizio ANPR di richiesta di rettifica perché  è consentito solo per errori materiali di trascrizione.  e non  è il suo caso

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by IntrepidBug** [comment]
@cmigliardi Grazie mile per le delucidazioni!
