### ISSUE TITLE
Tabella 45 - Comuni Subentrati: Comune di MISILISCEMI

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3391]
Buonasera.

Facendo qualche controllo a campione mi sembra che non sia mai arrivata la notifica del subentro del comune di MISILISCEMI (TP), avvenuta in data 01/04/2022.
Guardando anche la "tabella 45" pubblicata sul portale ANPR, risulta aggiornata l'ultima volta il 18/1/22 e l'ultimo comune della lista è SAN TEODORO subentrato il 17/1/2022

potete verificare?

grazie
Alessandro Monopoli ADS

**Comment by dgiaccari** [comment]
Buongiorno
Misiliscemi non è un comune subentrato, ma è nato per scorporo di territorio dal comune di Trapani, pertanto i suoi cittadini sono di fatto subentrati con Trapani
Cordiali saluti

**Comment by AMonopoliADS** [comment]
indipendentemente da come è avvenuto il passaggio dei cittadini (già subentrati) da Trapani a Misiliscemi, mi sarei aspettato di trovare il comune censito nella tabella 45, con una sua "data operatività anpr" (che non è quella di Trapani)

evidentemente ho mal interpretato l'utilità di questa tabella.

grazie
