### ISSUE TITLE
Mancato login con SPID Poste

### ISSUE THREAD

**Issue by fantinis** [italia/anpr#3394]
Buongiorno, 

oggi dopo la procedura di login via spid (poste) non funziona,

dopo l'autorizzazione e il consenso di passaggio dati (codice fiscale)

si viene rediretti alla home page.

Grazie

**Comment by cmigliardi** [comment]
salve per favore ci può  dare le prime 6 lettere del suo codice fiscale ? così possiamo controllare grazie

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Mancato login con SPID Poste (Issue #3394)" inviata il 27/05/2022 13:51:44.


Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Mancato login con SPID Poste (Issue #3394)" inviata il 28/05/2022 16:13:22.


Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
