### ISSUE TITLE
Mancanza COMUNE di Roma nel cambio di residenza

### ISSUE THREAD

**Issue by AulinaMeow** [italia/anpr#3395]
![Immagine 2022-05-27 201731](https://user-images.githubusercontent.com/106402770/170768146-94ac40cb-848c-4e72-a407-06d08dfcb9f3.png)

Durante il processo di cambio di residenza dopo aver selezionato la provncia di Roma non è possibile selezionare Roma come comune in quanto mancante dall'elenco, questo non permette di portare a termine il cambio di residenza

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Mancanza COMUNE di Roma nel cambio di residenza (Issue #3395)" inviata il
27/05/2022 20:19:33.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by cmigliardi** [comment]
Buongiorno,  come si legge nella home page:   Dal 27 aprile tutti i cittadini possono richiedere online il cambio di residenza o di dimora da un Comune all’altro in Italia o il rimpatrio dall’estero per i cittadini iscritti all’AIRE. Può essere richiesto anche il cambio di abitazione nell’ambito di un qualsiasi Comune. Per il Comune di Roma, in attesa del completamento degli interventi tecnici, sino al 30/06/2022 il servizio di cambio di residenza on line è disponibile sul portale dello stesso Comune.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Mancanza COMUNE di Roma nel cambio di residenza (Issue #3395)" inviata il
28/05/2022 16:01:01.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Mancanza COMUNE di Roma nel cambio di residenza (Issue #3395)" inviata il
28/05/2022 16:01:00.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Mancanza COMUNE di Roma nel cambio di residenza (Issue #3395)" inviata il
28/05/2022 15:58:38.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
