### ISSUE TITLE
PROBLEMA ACCESSO ANPR

### ISSUE THREAD

**Issue by HJS82** [italia/anpr#3396]
Accedo al portale ANPR tramite SPID, una volta autenticato mi da il seguente messaggio di errore:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Che posso fare?
![screen ANPR](https://user-images.githubusercontent.com/106457697/170849267-cf79757c-bea9-429b-958f-c9062a86a2a7.png)

**Comment by HJS82** [comment]
Ho visto su internet che è necessario inserire le prime 6 cifre del codice fiscale

GLNLSN

Alessandro

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
PROBLEMA ACCESSO ANPR (Issue #3396)" inviata il 29/05/2022 04:21:29.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
PROBLEMA ACCESSO ANPR (Issue #3396)" inviata il 29/05/2022 04:17:36.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by cmigliardi** [comment]
salve se è lei la persona del 1982  - in Anpr c'è una scheda che però non ha i dati in linea cn agenzia entarte . lei in Anpr ha 2 nomi di battesimo e in agenzia entrate ne ha 3 .  quindi anche i codici fiscali sono diversi. quello che ha registrato con spid  è legato ai 3 nomi.   le consigliamo di rivolgersi al suo comune - spero di esserle stata di ausilio

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
PROBLEMA ACCESSO ANPR (Issue #3396)" inviata il 30/05/2022 10:34:47.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
PROBLEMA ACCESSO ANPR (Issue #3396)" inviata il 30/05/2022 14:20:26.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
