### ISSUE TITLE
mancanza certificati sl sitio di ANPR

### ISSUE THREAD

**Issue by joseamneto** [italia/anpr#3397]
ANPR  ID: 92041966
È possibile visualizzare solo i seguenti certificatiCertificato di cittadinanza
Certificato di residenza
Stato famiglia

Vivo all’estero e per me avere accesso al mio certificato di nascita sarebbe incredibile, il contatto con la comuni è praticamente impossibile con mezzi digitali.

Grazie

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
mancanza certificati sl sitio di ANPR (Issue #3397)" inviata il 29/05/2022
16:09:53.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by cmigliardi** [comment]
buongiorno, per gli iscritti all' AIRE è possibile certificare solo gli eventi accaduti in Italia e se è lei la persona del  gennaio 1986 vedo che è nato all'estero quindi  ( per normativa )  non può richiedere un certificato di nascita.

**Comment by cmigliardi** [comment]
La issue viene chiusa. In caso siano necessari ulteriori chiarimenti si prega di aprirne un'altra facendo riferimento a questa stessa

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
mancanza certificati sl sitio di ANPR (Issue #3397)" inviata il 30/05/2022
14:20:33.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
mancanza certificati sl sitio di ANPR (Issue #3397)" inviata il 30/05/2022
10:41:03.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
