### ISSUE TITLE
[4005] Gravi problemi in ricezione esiti 4005

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3398]
Buongiorno,
oggi moltissimi nostri clienti stanno avendo problemi a ricevere gli esiti delle richieste 4005 pendenti anche da più di due giorni. Ad ogni chiamata fatta per chiedere lo status della richiesta ci viene risposto che "sarà pronta fra un'ora".
Ci sono dei problemi nei vostri server con l'evasione di queste richieste ?
La problematica sembra molto diffusa e comincia a diventare preoccupante.

**Comment by SilviaRivi** [comment]
Stessa segnalazione effettuata e presente nella issue #3383.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
[4005] Gravi problemi in ricezione esiti 4005 (Issue #3398)" inviata il
30/05/2022 10:39:36.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by marcobovo** [comment]
Anche oggi sussiste lo stesso problema su molti comuni.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[4005] Gravi problemi in ricezione esiti 4005 (Issue #3398)" inviata il
31/05/2022 09:26:43.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by Hdemografici** [comment]
confermo il problema anche per i nostri clienti

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[4005] Gravi problemi in ricezione esiti 4005 (Issue #3398)" inviata il
31/05/2022 12:39:01.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[4005] Gravi problemi in ricezione esiti 4005 (Issue #3398)" inviata il
01/06/2022 08:48:25.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by mttfranci** [comment]
Come indicato nella issu #3400 il problema dovrebbe essere rientrato, vi risulta? Saluti

**Comment by anozzoli** [comment]
Si risolto. Grazie

**Comment by SilviaRivi** [comment]
Buongiorno,
noi continuiamo ad avere problemi su diversi clienti.

La problematica è sempre la stessa che non si riesce a chiudere la richiesta di scarico di notifiche,
ecco alcuni ID 904640512, 904640509, 904564171, 904564169, 904564168, 904564165, 903484321.

Il sistema risponde sempre:
La richiesta è ancora in elaborazione da parte di ANPR. Si prega di riprovare più tardi

In un caso invece ha segnalato questa anomalia:

> <testataRisposta>
          <dataOraRichiesta>2022-06-06T03:01:05.156+02:00</dataOraRichiesta>
          <dataDecorrenza>2022-06-06</dataDecorrenza>
          <idOperazioneANPR>903484322</idOperazioneANPR>
          <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
          <errore>
            <codiceErroreAnomalia>EHR16</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Data finale della richiesta  06/06/2022 23:59:00 minore della data iniziale   06-06-2022 o maggiore della data di sistema  06/06/2022 02:56:58 </testoErroreAnomalia>
          </errore>
        </listaErrori>


In attesa di risposta
Grazie
Silvia Rivi
