### ISSUE TITLE
paternità ad eliminare

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3399]
Buongiorno,
in fase di subentro è stato indicato per errore ad una bambina "n.n." nella paternità (per indicare l'assenza del padre). Ovviamente è un dato da eliminare, come possiamo procedere? Ho provato ad eliminare il dato ma il programma mi chiede l'indicazione di un nome e un cognome.
Grazie del riscontro.
Buona giornata. 
Andrea Formenti
Comune di Caponago.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
paternità ad eliminare (Issue #3399)" inviata il 31/05/2022 07:43:08.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by frmariani** [comment]
Per eliminare il dato deve effettuare una revoca del dato utilizzando la funzione "Eliminazione dati".

**Comment by AndreaFormenti** [comment]
Buongiorno,
ho provato a eliminare come suggerito, non riesco a procedere in quanto da due errori; "Sezione paternità non presente" e "Compilare almeno una delle seguenti sezioni Scheda soggetto Famiglia/Convivenza ". Ovviamente la paternità è indicata.
Come posso fare? 
Andrea Formenti

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
paternità ad eliminare (Issue #3399)" inviata il 31/05/2022 14:09:28.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
