### ISSUE TITLE
Web-App Annullamento Mutazione Motivo Richiesta = Ripristino posizione precedente KO

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#34]
Data test- 15/03/2017 - Ambiente test (dptest)
Abbiamo effettuato un cambio indirizzo di soggetto singolo. 
Quindi volevamo effettuare la Revoca di tale cambio. 
Se si effettua Registrazione/Annullamento Mutazione  valorizzando Motivo Richiesta = "Ripristino posizione precedente" compare messaggio "operazione eseguita correttamente" ma non riporta all'indirizzo precedente. 
Se invece non si valorizza il campo Motivo Richiesta, il soggetto viene correttamente riportato al vecchio indirizzo

Grazie
Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Il ripristino della posizione anagrafica è in corso di revisione secondo logiche descritte in un documento che trovate in ambiente di test comuni (si scarica dall'avviso del 27 febbraio): questa versione NON è ancora disponibile quindi rimandiamo questo tipo di test. In ogni caso, se ci indica l'identificativo operazione ANPR possiamo approfondire.

**Comment by gcarbonin** [comment]
Chiuso per assenza di riscontro da parte del comune
