### ISSUE TITLE
[Subentro] Pianificazione e cronoprogramma

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#340]
Buongiorno,
nelle istruzioni fornite per il Subentro sono riportate le tre fasi da eseguire dopo aver completato la fase di pre-subentro. In particolare, la prima fase "Pianificazione e cronoprogramma" consiste nell'invio di una mail al Ministero dell'Interno/Sogei per definire la data del subentro e la cronologia che si intende seguire per completare le varie operazioni quel giorno (giusto?).
A tal proposito, vorrei chiedere se esiste un modulo/modello predefinito da compilare soltanto, nel quale inserire con ordine le informazioni richieste dal Ministero.
Approfitto anche per chiedere quale sia l'indirizzo di mail a cui inviare quanto sopra. 
Grazie

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Al momento, considerando  che un piano di migrazione non è definito, non ci sono moduli o altri adempimenti. Per poter contattare il comune "subentrante" e concordare i tempi, va bene una comunicazione alla casella specifiche.anpr@sogei.it; per quanto riguarda il Ministero servizidemografici.prot@pec.interno.it: in entrambi i casi occorre indicare i riferimenti del comune da contattare.

**Comment by mccalv** [comment]
Caro @Eduardo1977 completo alcune informazioni. Nell'ambito del nuovo contratto abbiamo chiesto disponibilità alle aziende di indicare un proprio referente per la pianificazione del piano di subentro dei loro comuni, ovviamente di concerto con gli stessi. 
**Il contributo della singole aziende concorrerà a produrre il piano di subentro**
Queste date di subentro previsto saranno indicate sulla piattaforma dashboard.anpr.it. Preghiamo chi non avesse già indicato di comunicare il proprio responsabile per il piano di subentro a segnalazioni-anpr@teamdigitale.governo.it

**Comment by Eduardo1977** [comment]
La data di subentro viene stabilita dal Comune che una volta fatta comunicazione al Ministero/Sogei attende per la conferma? Cioè potrebbe essere che al Ministero/Sogei non vada bene la data stabilita?

**Comment by gcarbonin** [comment]
Come ha scritto mirko, si tratta di indicazioni provvisorie nelle more della formalizzazione del piano di migrazione. Al momento, non ci sono approvazioni ma soltanto una presa d'atto ed una verifica con il comune che tutte le operazioni preliminari siano note e completate. Occorre anche coordinare le attività del comune con quelle della Prefettura competente.
Il piano serve anche a programmare meglio queste attività preliminari e ad evitare che nello venerdì vogliano subentrare troppi comuni...

**Comment by Eduardo1977** [comment]
Ciao Mirko, grazie per le informazioni preziose. A tal proposito vorrei saperne di più su questo nuovo contratto. Questo contratto è da stipulare tra il Comune e ANPR o con l'azienda ?

**Comment by Eduardo1977** [comment]
Cosa va fatto per "coordinare le attività del comune con quelle della Prefettura competente" ?
Bisogna inviare comunicazioni anche alla Prefettura ? 
Grazie

**Comment by mccalv** [comment]
No @Eduardo1977 é il nuovo contratto attuativo che lega il Ministero a Sogei in cui viene istituita la figura del Program Office che é rappresentato dalla struttura del Team Digitale diretta da Diego Piacentini. 
Nell'ambito di questo contratto il Program Office ha la responsabilità, tra le altre, di stendere un piano di migrazione ad ANPR. La nostra attività sarà quella quindi di verificare con i fornitori un loro piano di dispiegamento e adeguarlo ai limiti di numero concorrente ove ce ne fossero. 
Per rispondere anche alla tua altra domanda, sono a carico di comuni e prefetture alcune operazioni di abilitazione che sono disponibili a questo indirizzo:
http://anpr.readthedocs.io/it/latest/censimento-comuni/index.html
http://anpr.readthedocs.io/it/latest/smart-card-prefetture/index.html

**Comment by Eduardo1977** [comment]
Ok grazie. Questi documenti li ho letti, per la verità non mi era molto chiaro se la procedura di "Censimento degli utenti ANPR della Prefettura" va fatta dal Comune tramite il proprio account sul CNSD oppure dalla Prefettura da qualche funzionario.
Pensavo che il Comune si dovesse occupare solo del censimento dei propri utenti e postazioni all'interno del Comune stesso.

**Comment by gcarbonin** [comment]
Il comune si occupa di se stesso (utenti): sulla base di questo censimento, sono generati i certificati di postazione e personalizzate le smart card.
Il dpcm 194/2014 prevede che le smart card del comune siano consegnate DALLA PREFETTURA. di conseguenza, anche la prefettura deve effettuare il proprio censimento le ricevere le proprie smart card, ottenute le quali potrà accedere alla WA e consegnare le smart card al comune.

**Comment by Eduardo1977** [comment]
Grazie, molto chiaro. Adesso pensadoci meglio la cosa a cui non avevo fatto attenzione è che prima di decidere qualsiasi data per il subentro di un comune bisogna chiamare la Prefettura per chiedere se si sono "attrezzati". Giusto?
