### ISSUE TITLE
Ancora problema scarico Notifiche N

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3400]
Buongiorno, permangono problemi di scarico delle notifiche da parte dei nostri comuni. Segnalo inoltre che gli stessi rivolgendosi all'assistenza ANPR, vengono rassicurati che non c'è nessun problema lato ANPR e di conseguenza sono invitati a contattare la loro software house, la quale però non ha controllo diretto sulla risoluzione del problema.

Data richiesta                 Tipo	       Data Inizio		Data Fine		 Id richiesta
27/05/2022			N014	24/05/2022 		27/05/2022 	895931108
28/05/2022			N010	24/05/2022 		28/05/2022 	896902201
28/05/2022			N015	25/05/2022 		28/05/2022 	896903144
28/05/2022			N014	25/05/2022 		28/05/2022 	896903245
30/05/2022			N010	25/05/2022 		30/05/2022 	897790626
30/05/2022			N015	27/05/2022 		30/05/2022 	897790767
30/05/2022			N014	27/05/2022 		30/05/2022 	897790914

Alessio Tropeano
Datagraph srl

**Comment by edoardodona-1** [comment]
Sulle N10 non riceviamo , presso molti clienti , nenache noi. Datamanagement. 
Grazie

**Comment by mttfranci** [comment]
C'è stato un problema che ha portato alcuni ritardi nella generazione.
@ATropeano : tutte le richieste indicate dovrebbero essere elaborate.
@Tutti : la situazione dovrebbe rientare completamente nel corso della notte.

Saluti

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Ancora problema scarico Notifiche N (Issue #3400)" inviata il 31/05/2022
19:34:00.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by tutti** [comment]
> @tutti : la situazione dovrebbe rientare completamente nel corso della notte.
Glad to hear it. Keep up the good work!

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Ancora problema scarico Notifiche N (Issue #3400)" inviata il 31/05/2022
12:39:35.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
