### ISSUE TITLE
Cambio Residenza Fiscale

### ISSUE THREAD

**Issue by SGr33n** [italia/anpr#3401]
Buonasera,
Mia sorella è iscritta all'AIRE, e risulta correttamente nella sezione Residenza/Altri recapiti.
Dovrebbe però modificare la sua Residenza Fiscale in Italia, senza modificare la sua iscrizione all'AIRE, è possibile effettuare questa operazione?
La voce di menu indica "Residenza/Altri recapiti", il che mi porta a pensare che "Altri recapiti" altro non sia che eventuali domicili, anche intesi nel senso di Residenza fiscale. Tuttavia su quella voce di menu è presente solo la residenza.

Ringrazio per ogni eventuale chiarimento in merito,
Cordiali saluti.

P.S. è probabile che questa operazione non sia relativa all'anagrafe online ma all'agenzia delle entrate.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Cambio Residenza Fiscale (Issue #3401)" inviata il 31/05/2022 15:54:10.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 12/06/2022




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Cambio Residenza Fiscale (Issue #3401)" inviata il 31/05/2022 18:16:53.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto. 

--
Messaggio analizzato da Libraesva ESG.
