### ISSUE TITLE
Problemi accesso ambiente SVILUPPO COMUNI

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3405]
Buongiorno

Da ieri non riusciamo a entrare nell'ambiente di SVILUPPO COMUNI, nè dalla webapp nè con i ws. 
Potreste farci sapere se ci sono problemi?

Abbiamo necessità dell'ambiente in quando stiamo sviluppando per il Comune di Milano il nuovo applicativo che dovrà andare in produzione dal prossimo mese, con rilasci previsti fino a fine anno.

Grazie
_Raffaella Tremolada_ 
Sistemi Informativi IBM per Comune di Milano

**Comment by mttfranci** [comment]
Buongiorno, di preciso di quale ambiente parlate? Potete fornirci l'endpoint?
I problemi persistono?
