### ISSUE TITLE
Servizi al Cittadino - Purtroppo non is stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Princeofthebow** [italia/anpr#3406]
Salve, ho provato ad accedere tramite spid al servizio ANPR (sono residente all'estero) e questo non mi è stato possibile. 

> Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Leggendo tra le varie issue ho notato che forse questo dipende dalla possibile assenza del codice fiscale nella scheda anagrafica del comune. Tuttavia, ho verificato presso il sito del mio comune originario (Napoli) e questo risulta correttamente inserito (posso mandare prova via email se necessario).

Potreste darmi altre indicazioni su come procedere per risolvere il problema?

Saluti

**Comment by cmigliardi** [comment]
buongiorno,  per verificare  la scheda abbiamo bisogno delle prime 6 lettere  del suo codice fiscale - grazie

**Comment by Princeofthebow** [comment]
> Non è detto che se presente sull'area privata del cittadino (immagino) del Comune, questo sia poi correttamente stato comunicato ad ANPR. Quindi l'unica via credo sia quella di contattare il comune di residenza (non di origine/nascita).

OK, in realtà questo passaggio l'ho tentato credendo, che come da errore, fosse il comune di residenza. Siccome il mio comune di residenze è estero ho scritto all'ambasciata di Londra ma non mi è stata fornita alcune indicazione, ne alcuna risposta.
Ho quindi pensato che non fosse il comune di residenza AIRE (ovvero Londra) il problema ma l'associato comune di orgine in Italia, ergo il comune di Napoli.

**Comment by cmigliardi** [comment]
Buongiorno,  la scheda è presente in Anpr ma il codice fiscale non risulta validato - se è lei la persona del 1986 - il comune di Napoli ha inviato  il doppio cognome senza spazi - mentre in agenzia entrate è separato. Le consiglio di rivolgersi al comune di Napoli che può effettuare la correzione.  - spero di esserle   stata di ausilio

**Comment by Princeofthebow** [comment]
Salve, dunque si sono io :-) ora provo a contattare il comune di Napoli ed aggiornare la scheda anagrfica.

La ringrazio molto per la disponibilità e magari la terrò aggioranto.

**Comment by cmigliardi** [comment]
di nulla . spero risolva brevemente .
