### ISSUE TITLE
Login non funzionante SPID

### ISSUE THREAD

**Issue by SamueleFaulisi** [italia/anpr#3407]
Segnalo problemi nel login tramite Poste ID - SPID.
Nonostante riceva notifiche e viene processato il tutto, si blocca nella pagina di login dell'ANPR per poi farmi automaticamente sloggare.

**Comment by cmigliardi** [comment]
buongiorno, per favore ci potrebbe dare le prime 6 lettere del suo codice fiscale ? così controlliamo . grazie. senza elementi non possiamo esserle  di ausilio.

**Comment by SamueleFaulisi** [comment]
Buongiorno, perdoni la mancata risposta.
Il problema è stato risolto, probabilmente ha avuto un'interruzione il
sito, dopo poco tempo ha funzionato regolarmente.
Grazie!



*Social Media Manager | Digital & Web Marketing*
*+39 3205613755 *
*www.samuelefaulisi.com <http://www.samuelefaulisi.com>*


Il giorno mer 8 giu 2022 alle ore 09:02 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
meglio così - allora chiudo.
