### ISSUE TITLE
Richieste da cittadini, sospensioni e accertamenti

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3408]
Argomento : Sospensioni e accertamenti. Esemplifichiamo due situazioni: 
**Caso A**
Sia data una richiesta in stato "Accolta con riserva", il comune chiede integrazione documenti e la richiesta passa nello stato "sospesa". Il cittadino integra i documenti mancanti, la richiesta passa nello stato "integrata".
A quel punto il comune riceve dalla polizia municipale l'esito NEGATIVO dell'accertamento di dimora. Essendo la richiesta nello stato "integrata" il comune non può più comunicare con il cittadino via portale, deve contattarlo per altre vie.

**Caso B**
Sia data una richiesta in stato "Accolta con riserva", il comune riceve dalla polizia municipale l'esito NEGATIVO dell'accertamento di dimora. Per poter in un secondo tempo eseguire l'eventuale rigetto, la richiesta viene portata
nello stato SOSPESA. Il cittadino integra i documenti mancanti, la richiesta passa nello stato "integrata".

Caso A e caso B descrivono due situazioni per cui il comune ad un certo punto deve comunicare al cittadino la stessa cosa (preavviso di rigetto), ma il sistema delle richieste ANPR pare costringerci ad usare due 
canali diversi a seconda del fatto che sia stata già richiesta o meno un'integrazione.

È corretta la mia interpretazione ?

**Comment by ncapozzi** [comment]
Buongiorno
una volta che la dichiarazione è nello stato INTEGRATA il Comune ha due possibilità 
ACCOLTA DEFINITIVAMENTE se l'accertamento ha esito positivo
ANNULLATA se l'accertamento ha esito negativo, L'annullamento deve essere motivato nel campo Note, il cittadino riceve comunicazione per email e vede dal portale il motivo dell'annullamento.

**Comment by ncapozzi** [comment]
Se ho compreso bene quanto descritto non mi sembra di vedere differenze di "canale" tra i due casi.
