### ISSUE TITLE
[4005] continuano i problemi in ricezione esiti 4005 sia N010 che N015

### ISSUE THREAD

**Issue by SilviaRivi** [italia/anpr#3410]
Buongiorno,
noi continuiamo ad avere problemi su diversi clienti.
Vedi issue #3398

La problematica è sempre la stessa che non si riesce a chiudere la richiesta di scarico di notifiche,
ecco alcuni ID 904640512, 904640509, 904564171, 904564169, 904564168, 904564165, 903484321.

Il sistema risponde sempre:
La richiesta è ancora in elaborazione da parte di ANPR. Si prega di riprovare più tardi

In un caso invece ha segnalato questa anomalia:
```xml
      <dataOraRichiesta>2022-06-06T03:01:05.156+02:00</dataOraRichiesta>
      <dataDecorrenza>2022-06-06</dataDecorrenza>
      <idOperazioneANPR>903484322</idOperazioneANPR>
      <esitoOperazione>XXXX</esitoOperazione>
    </testataRisposta>
    <listaErrori>
      <errore>
        <codiceErroreAnomalia>EHR16</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Data finale della richiesta  06/06/2022 23:59:00 minore della data iniziale   06-06-2022 o maggiore della data di sistema  06/06/2022 02:56:58 </testoErroreAnomalia>
      </errore>
    </listaErrori>
```

In attesa di risposta
Grazie
Silvia Rivi

**Comment by mttfranci** [comment]
Salve, esito è corretto mi pare

La richiesta è stata elavorata correttamente.
Il problema è che avete richiesto alle 3 del 6 giugno, le notifiche fino al mezzanotte del 6 giugno.

						<dataOraIniziale>2022-06-06T00:00:00</dataOraIniziale>
						<dataOraFinale>2022-06-06T23:59:00</dataOraFinale>

Come si evince anche dal diagnostico.
Saluti

`
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<soapenv:Header />
	<soapenv:Body>
		<ns2:Richiesta4005
			xmlns:ns2="http://sogei.it/ANPR/4000estrazione">
			<testataRichiesta>
				<idOperazioneComune>444728</idOperazioneComune>
				<codMittente>009056</codMittente>
				<codDestinatario>ANPR02</codDestinatario>
				<operazioneRichiesta>4005</operazioneRichiesta>
				<dataOraRichiesta>2022-06-06T03:01:05.156+02:00</dataOraRichiesta>
				<tipoOperazione>C</tipoOperazione>
				<tipoInvio>PROD</tipoInvio>
				<dataDecorrenza>2022-06-06</dataDecorrenza>
				<nomeApplicativo>Cityware.online</nomeApplicativo>
				<versioneApplicativo>7.10</versioneApplicativo>
				<fornitoreApplicativo>Palitalsoft S.r.l.</fornitoreApplicativo>
			</testataRichiesta>
			<elaborazione>
				<comuneRichiesta>
					<nomeComune>SAVONA</nomeComune>
					<codiceIstat>009056</codiceIstat>
					<siglaProvinciaIstat>SV</siglaProvinciaIstat>
				</comuneRichiesta>
				<ricercaElenchiRichieste>
					<statoLavorazione>9</statoLavorazione>
					<operazioneRichiesta>N015</operazioneRichiesta>
					<periodoRiferimentoRichieste>
						<dataOraIniziale>2022-06-06T00:00:00</dataOraIniziale>
						<dataOraFinale>2022-06-06T23:59:00</dataOraFinale>
					</periodoRiferimentoRichieste>
				</ricercaElenchiRichieste>
			</elaborazione>
		</ns2:Richiesta4005>
	</soapenv:Body>
</soapenv:Envelope>
`

**Comment by SilviaRivi** [comment]
Salve,
quella problematica relativa all'orario forse era un problema legato all'orario del server, quindi verifico.

Ma la problematica su questi id invece permane 904640512, 904640509, 904564171, 
904564169, 904564168, 904564165, 903484321.

Il sistema risponde sempre:
La richiesta è ancora in elaborazione da parte di ANPR. Si prega di riprovare più tardi.

In attesa di risposta
Grazie
Silvia Rivi
