### ISSUE TITLE
Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#3411]
Comune di Mirabella Eclano (AV)

Nel tentativo di correggere data di nascita (e relativo codice fiscale) del cittadino 311412469
incorriamo nel seguente errore quando effettuiamo la risoluzione disallineamenti da webapp:

Esito ANPR: Informazioni sull'operazione da fornire in caso di assistenza : data 2022-06-08 12:35:07 , idOperazioneANPR 906597299 (Codice: EN527)

**Comment by frmariani** [comment]
i due cf sono già collegati ed il cf presente in ANPR non è il principale; dovete effettuare una mutazione dei dati senza utilizzare la funzione di risoluzione disallineamenti; effettuate l'operazione ed inviatemi l'eventuale idoperazione di errore
