### ISSUE TITLE
Validazione Codice fiscale ref #3406

### ISSUE THREAD

**Issue by Princeofthebow** [italia/anpr#3412]
Salve, come da intercorse in #3406 il comune mi ha risposto mostrandomi che effettivamente il codice fiscale non risulta validato ma non ci sono problemi di spazio con i cognomi. Posso inoltrare la schermata via email?

Saluti

**Comment by cmigliardi** [comment]
il comune deve marcare la scheda - la discordanza è tra il dato inviato in Anpr e quello che ha Agenzia delle Entrate
