### ISSUE TITLE
Problemi con le notifiche N10 ed N15

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#3417]
Buongiorno,

in questi giorni ci sono dei nostri clienti che ci stanno segnalando alcuni problemi con lo scarico di alcune notifiche.
Hanno già contattato l'assistenza ANPR e hanno avuto come indicazione per la risoluzione di aprire una richiesta direttamente qui.

Gli ID delle notifiche da verificare sono:
911537245 (N10)
911589591 (N10)
911589736 (N15)

Rimaniamo in attesa di un vostro riscontro
Grazie

Marco Sala
Pa Digitale Spa

**Comment by amollicone1982** [comment]
C'e' stato un rallentamento nell'elaborazione che si dovrebbe concludere in giornata
