### ISSUE TITLE
Servizi al cittadino: Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by condoblezeta** [italia/anpr#3419]
Buonasera,
Anch'io ho problema per accedere al servizio dell'Anagrafe Nazionale.

![error](https://user-images.githubusercontent.com/86033946/173658165-d1cdc3b7-9c98-4874-9dc8-d39145142456.jpg)

> Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Sono residente all'estero e il mio comune di iscrizione all'AIRE è Cassano Valcuvia (VA). Ho inviato una mail al comune e queste sono state le risposte:

> Buongiorno,
> ho provato a rigenerare la sua posizione in ANPR (Anagrafe nazionale), può provare ancora se il problema persiste?
> Nel frattempo sentirò la nostra software house per capire il problema.
> Cordiali saluti.

Il problema persisteva. Ho inviato un'altra mail. La risposta:

> Buongiorno,
> la nostra software house è intervenuta risolvendo il problema.
> Le chiedo se gentilmente può provare ad accedere sia all'anagrafe nazionale sia al sito del comune per vedere se va bene.
> In attesa di una sua risposta le auguro una buona giornata.

Ma il problema persiste. E non so già a chi devo rivolgermi.

Le prime 6 lettere del mio codice fiscale: VGZFVL... Mio comune di iscrizione AIRE è Cassano Valcuvia, provincia di Varese.

Ringrazio per l'aiuto.

**Comment by cmigliardi** [comment]
se è lei la persona del 1970 - le consiglio di rivolgersi al comune di iscrizione  Cassano  Valcuvia per far validare il codice fiscale  e marcare la scheda in Anpr  - spero di esserle stata   di ausilio

**Comment by condoblezeta** [comment]
La ringrazio per la sua risposta.
Si, sono io. Ho scritto una email al comune con questo che mi avete detto. Non rispondono subito, vedremo cosa succede nei prossimi giorni.

**Comment by cmigliardi** [comment]
certo non accede perché il comune non ha fatto i dovuti interventi sulla sua scheda in Anpr   - chiudo la issue -
