### ISSUE TITLE
Intervento di aggiornamento e riorganizzazione territoriale delle provincie 

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#342]
A seguito di un tavolo congiunto con gli Enti interessati (Istat,Inps, Agenzia Entrate, Motorizzazione Civile) si conferma che l'intervento é **pianificato per il 12 Novembre**
#292 #249# #252

**Comment by bfilipazzi** [comment]
So di andare fuori tema ma approfitto per chiedere: questo intervento adegua anche i codici usati da SAIA? 
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
L'adeguamento riguarda INA SAIA CNSD AIRE (e tabella comuni ANPR).
