### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

### ISSUE THREAD

**Issue by marceagu** [italia/anpr#3424]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Faccio presente che il Comune di Castello di Godego (TV) è in ANPR.
Ho contattato il Comune e non hanno riscontrato problemi con la scheda anagrafica. 
Cosa devo fare? Il comune non sa come aiutarmi.

**Comment by cmigliardi** [comment]
buongiorno per favore ci può fornire le prime 6 lettere del codice fiscale ? facciamo una verifica - grazie

**Comment by marceagu** [comment]
GSTMCL

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1983 - non trovo la scheda in Anpr  -

**Comment by marceagu** [comment]
Si, sono io. Che cosa potrei fare? 
Grazie mille

**Comment by cmigliardi** [comment]
deve contattare il comune che l'ha iscritta AIRE e dire che devono inserire la sua scheda  in Anpr - molto probabilmente hanno la scheda solo in locale.

**Comment by marceagu** [comment]
Ok. Grazie
