### ISSUE TITLE
Cambio residenza AIRE

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3425]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Stiamo cercando di fare un cambio di indirizzo AIRE - Richiesta 5001 si seguito l'errore restituito

ErroreAnomalia 999
testoErroreAnomalia Operazione non effettuabile

codiceErroreAnomalia = EN527
informazioni da fornire in caso di assistenza : data 2022-06-16 - IDOperazioneANPR : 915081510

Restiamo in attesa di gentile riscontro.

Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera
sono stati ripetuti nel campo toponimo><denominazione tutti i campi dell'indirizzo (via, civico, cap, località e stato) separati l'uno dall'altro da molti spazi per un totale caratteri che supera quelli attesi sulla base dati. Si suggerisce di rivedere il formato dell'indirizzo trasmesso, il campo toponimo><denominazione deve contenere la via
