### ISSUE TITLE
INAIL e ANPR

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3426]
COMUNE DI VILLA CORTESE
Città Metropolitana di Milano

Buongiorno,
sono a chiedere se anche INAIL come INPS abbia la banca dati aggiornata con le variazioni ANPR.
Lo chiedo in quanto continuiamo a ricevere richieste di certificazioni di Stato Famiglia ed esistenza in vita e, visto l'avvento di ANPR e la circolarità del dato, tali richieste dovrebbero cessare.

Grazie
Claudio Vignati

**Comment by FilippoPapi** [comment]
salve attualmente INAIL non è collegata con ANPR
buonaserata
