### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by verteramofederico** [italia/anpr#3427]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

¿Qué tengo que hacer? El municipio no sabe cómo ayudarme.

I primi 6 caratteri del mio codice fiscale sono:
VRTFRC

Molte grazie

**Comment by cmigliardi** [comment]
buongiorno,  se è lei la persona nata nel  1991 - la scheda in Anpr è presente ma il codice fiscale  non è validato. le consigliamo di rivolgersi al comune di iscrizione Aire - comune di Riace per sanare la situazione.

**Comment by cmigliardi** [comment]
la issue viene chiusa - semmai fate riferimento al numero 3427
