### ISSUE TITLE
[ws5008] Tipo Mutazione '19': Scioglimento unione civile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3431]
ambiente di PRODUZIONE - comune di MALNATE (012096)

con idOperazioneANPR 919617951 è stata inviato lo scioglimento dell'unione civile per il soggetto con idANPR 23519938
la request con la mutazione contiene queste informazioni:
```
<scioglimentoUnione>
        [...]
	<datiEvento>
		<dataEvento>2022-05-12</dataEvento>
		<luogoEvento>
			<comune>
				<nomeComune>MALNATE</nomeComune>
				<codiceIstat>012096</codiceIstat>
				<siglaProvinciaIstat>VA</siglaProvinciaIstat>
			</comune>
		</luogoEvento>
	</datiEvento>
</scioglimentoUnione>
```
la comunicazione è andata a buon fine, ma se interrogo la scheda del cittadino (ws3002) non vedo i dati dell'evento, e infatti nella response non trovo il tag datiEvento relativo allo scioglimentoUnioneCivile.

potete verificare?

grazie
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Nella consultazione tramite web app l'informazione sullo scioglimento dell'unione è presente;  
puoi mandarmi l'idanpr della response del 3002 per favore ?

**Comment by AMonopoliADS** [comment]
buondì.
ho appena eseguito una nuova consultazione.
ti mando i riferimenti della richiesta appena inviata:
```
<testataRisposta>
	<idOperazioneComune>2022305671</idOperazioneComune>
	<codMittente>012096</codMittente>
	<codDestinatario>ANPR02</codDestinatario>
	<operazioneRichiesta>3002</operazioneRichiesta>
	<dataOraRichiesta>2022-06-23T10:24:04</dataOraRichiesta>
	<idOperazioneANPR>923696316</idOperazioneANPR>
	<esitoOperazione>0000</esitoOperazione>
</testataRisposta>
```

**Comment by frmariani** [comment]
mi sembra tutto regolare: il tag scioglimentoUnione è all'interno del tag unioneCivile

**Comment by AMonopoliADS** [comment]
il problema non è il gruppo scioglimentoUnione, che è presente.
il problema è che manca dentro scioglimentoUnione, il gruppo datiEvento, che dovrebbe contenere dataEvento e luogoEvento comunicati con la mutazione

**Comment by frmariani** [comment]
scusami ma nel tag scioglimentoUnione ci sono gli stessi dati inviati con la mutazione; 
la data evento a cui ti riferisci è la data della sentenza

**Comment by AMonopoliADS** [comment]
probabilmente sono io che non capisco o mi sta sfuggendo qualcosa, però - cerco di spiegarmi meglio - se nella mutazione (ws5008 con idOperazioneANPR 919617951) ho inviato questi dati:
```
<scioglimentoUnione>
	<motivoScioglimento>1</motivoScioglimento>
	<tipoCessazione>7</tipoCessazione>
	<sentenza>
		<data>2022-05-12</data>
		<numero>2</numero>
		<tipoTribunale>4</tipoTribunale>
		<autorita>MALNATE</autorita>
		<dataValidita>2022-06-16</dataValidita>
	</sentenza>
	<datiEvento>
		<dataEvento>2022-05-12</dataEvento>
		<luogoEvento>
			<comune>
				<nomeComune>MALNATE</nomeComune>
				<codiceIstat>012096</codiceIstat>
				<siglaProvinciaIstat>VA</siglaProvinciaIstat>
			</comune>
		</luogoEvento>
	</datiEvento>
</scioglimentoUnione>
```

mi aspetterei di ritrovarli tutti anche nella consultazione (ws3002 con idOperazioneANPR 923696316) dove invece trovo solo questo:
```
<scioglimentoUnione>
	<motivoScioglimento>1</motivoScioglimento>
	<sentenza>
		<data>2022-05-12+02:00</data>
		<numero>2</numero>
		<tipoTribunale>4</tipoTribunale>
		<autorita>MALNATE</autorita>
		<dataValidita>2022-06-16+02:00</dataValidita>
	</sentenza>
</scioglimentoUnione>
```

data della sentenza e data dell'evento - comunicandole come informazioni separate - le ho sempre interpretate come tali.
sennò non mi spiego perchè inviarli insieme alla mutazione

**Comment by frmariani** [comment]
Grazie a te Alessandro, se vuoi scrivermi in privato la motivazione del cliente possiamo cercare insieme un'alternativa.
