### ISSUE TITLE
Comune di Roma introvabile - ANPR

### ISSUE THREAD

**Issue by LeopoldoCaggiano** [italia/anpr#3433]
Buongiorno!

Ho provato ad effettuare un cambio di residenza attraverso il portale online di ANPR, ma purtroppo quando inserisco la provincia di Roma, nel tab successivo (e obbligatorio) non compare il comune di Roma, dove vorrei spostare la mia residenza, rendendo impossibile proseguire nelle operazioni.

C'è un modo per indicare che mi sono trasferito nel comune di Roma o non è incluso tra i comuni gestiti dalla piattaforma?

Grazie mille.

Leopoldo

**Comment by cmigliardi** [comment]
non trova il comune di Roma perché come scritto nell'avviso Roma si è riservata di aggregarsi in un secondo tempo -  l'avviso è nella home page

**Comment by LeopoldoCaggiano** [comment]
Grazie mille della pronta risposta. Mi era sfuggito l'avviso. Andrò per vie classiche.

**Comment by cmigliardi** [comment]
di nulla - chiudo la  issue
