### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza...

### ISSUE THREAD

**Issue by domeniconardo77** [italia/anpr#3437]
Buongiorno,
ho provato ad accedere  al portale ANPR tramite SPID,  ma mi restituisce il seguente errore:

_Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica._

è possibile risolvere questo problema online o devo andare in Comune?
Ringrazio anticipatamente per la risposta.

**Comment by cmigliardi** [comment]
buongiorno per favore ci può fornire le prime 6 lettere del codice fiscale ? grazie
