### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

### ISSUE THREAD

**Issue by gianlongo** [italia/anpr#3438]
Buongiorno. Sto avendo problemi ad accedere al servizio ANPR. (Iscritto AIRE) Dopo accesso con lo spid compare il messaggio come da titolo.
Prime 6 caratteri del codice fiscale LNGGFR
Grazie in anticipo.

**Comment by cmigliardi** [comment]
il codice fiscale nella scheda di Anpr non risulta validato - le consigliamo di rivolgersi al comune di Cupra Marittima per sanare la situazione.

**Comment by amedeoroma** [comment]
salve, anche a me da lo stesso problema.
Prime 6 caratteri del codice fiscale YNSHDF
Grazie in anticipo.

**Comment by cmigliardi** [comment]
nella scheda in anpr il codice fiscale non è validato - le consigliamo di rivolgersi al comune di Roma per sanare la situazione

**Comment by cmigliardi** [comment]
la issue si chiude
