### ISSUE TITLE
Errore abilitazione profili ambiente di test

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3439]
Buongiorno, per provare i nuovi servizi elettorali ho tentato di abilitare un operatore in ambiente di test per il comune di Siena ma non si riesce ad entrare nella sezione Sicurezza della web app.

**Comment by galliandrea** [comment]
Questo l'errore all'accesso della sezione Sicurezza 
Errore interpretazione XML: nessun elemento radice trovato
Indirizzo: https://webtest.anpr.interno.it/ANPRConsole/welcome.xhtml
Riga numero 1, colonna 1:

**Comment by frmariani** [comment]
Abbiamo provveduto ad abilitare il codice fiscale
