### ISSUE TITLE
Problemi scarico Notifiche di tipo N

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3440]
Buonasera, purtroppo si ripresentano problemi di scarico delle notifiche da parte dei nostri comuni. Segnalo, in particolare, la situazione del comune di **PIANORO** che da diversi giorni non riesce a scaricare le notifiche di tipo N.

**Comment by amollicone1982** [comment]
ci fornisce un idoperazioneanpr per controllare?

**Comment by amollicone1982** [comment]
lo scarico delle notifiche per il comune di PIANORO  mi sembra sia tornato regolare
