### ISSUE TITLE
Errore acceso SPID: Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

### ISSUE THREAD

**Issue by Aesir-olgard** [italia/anpr#3446]
Buon giorno.
Il mio utente SPID funziona correttamente in altre amministrazioni, ma per accedere ad ANPR ottengo il seguente errore (vedere soto)
Ho già verificato che la mia scheda anagrafica contenga correttamente il codice fiscale. Ho anche richiesto un certificato all'Agenzia dell'Entrate per confermare che è corretto.

Le prime 6 cifre del CF sono: **RMDWTR**
(Sono cittadino italiano residente all'estero).
Se qualcuno potesse aiutarmi, gli sarò molto grato.
Saluti.

```
_Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni._
```
![132951725-e9e3b1d5-aba4-40b8-a2a1-ee241fb71421](https://user-images.githubusercontent.com/108176481/175768471-d13bbc05-a2b9-4c7e-84c2-098fc06cc918.jpg)

**Comment by cmigliardi** [comment]
salve se è lei la persona del 1984  la scheda è in Anpr ma ha il codice fiscale non validato . quindi è bene che si rivolga al suo comune CAPIZZI per far sanare la situazione  .

**Comment by cmigliardi** [comment]
la issue si chiude
