### ISSUE TITLE
Certificati mancanti

### ISSUE THREAD

**Issue by raffaello14** [italia/anpr#3447]
Salve,
sto cercando di scaricare il certificato di stato civile libero ma non lo trovo nella mia area utente, perchè?
![image](https://user-images.githubusercontent.com/108185674/175777635-fa9fe5ab-5e37-4e27-aad7-75c583472045.png)

**Comment by raffaello14** [comment]
Price 6 cifre codice fiscale SMNRFL

**Comment by cmigliardi** [comment]
se   è lei la persona del 1994 - si deve rivolgere al comune di Bologna - che ha aperto un procedimento sulla sua scheda-   solo il comune può intervenire-  spero di esserle stata di ausilio -

**Comment by cmigliardi** [comment]
chiudo la issue
