### ISSUE TITLE
[Portale cittadino] Matrimonio registrato in effetti ma senza dati

### ISSUE THREAD

**Issue by laghee** [italia/anpr#3449]
Nonostante le registrazioni regolari di:

* il mio divorzio nel 2015
* un contratto di convivenza tra me & mio compagno (adesso sposati) nel 2018

… nel portale sembra che non è stato registrato correttamente il nostro matrimonio di qualche mesi fa. Nella scheda di famiglia (65186735), da “marito/moglie” come “legame”, e entrambi di noi risultiamo col stato “coniugato/a”, ma nel portale di lui non appare l’opzione per un certificato del matrimonio e nel mio vedo solo il matrimonio vecchio — infatti se cerco io di scaricare un certificato del matrimonio, mi fa un’attestazione che sono ancora coniugata col mio ex 😱🤢. 

Siccome non c’è una cosa specifica che non è corretta (solo il documento generato) non riesco a utilizzare il processo stabilito per rettificare un errore. Come faccio a correggere i fonti dei dati generati?

**Comment by cmigliardi** [comment]
salve, per favore ci può fornire le prime 6 lettere dei  codici fiscali  ?   così possiamo verificare in dettaglio - grazie in anticipo

**Comment by cmigliardi** [comment]
siamo in attesa dei dati per verificare - grazie

**Comment by laghee** [comment]
MNNKHR

grazie 🙏

**Comment by cmigliardi** [comment]
se è lei la persona del 1974 il comune di  Varenna quando ha passato i dati in Anpr ha  inviato una situazione non congruente che il sistema ha segnalato.  tuttavia non sanata.  risulta che  lei è coniugata e che è  stata sposata con  Ferrari e poi c'è una cessazione di matrimonio. ma   nella famiglia risulta un coniuge diverso  Allodio.   altra situazione incongruente è presente nella scheda di Allodio, che risulta coniugato ma  ha i suoi dati nella sezione Convivenza.    quindi si deve rivolgere al comune di competenza per far sanare  tutte e due le schede.  debbono rendere  congruenti le informazioni tra Stato civile, situazione di coppia e relazioni di parentela.   spero di esserle stata di ausilio .

**Comment by cmigliardi** [comment]
aggiungo che anche nella sua scheda lei ha una sezione Convivenza con Allodio. e non un matrimonio.

**Comment by cmigliardi** [comment]
si chiude la issue

**Comment by cmigliardi** [comment]
di nulla spero risolva a breve
