### ISSUE TITLE
Ambiente di test - Notifica N015 anche in caso di trasferimento interno ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#345]
Ambiente di test - Poggio a Caiano.
Ho effettuato una mutazione di residenza di intera famiglia all'interno del comune con il servizio 5001 (id operazione 592789).
Al termine ho annullato il movimento con il servizio 5012 (id operazione 593118).
A quel punto ho fatto una ricerca operazioni 3007 e ho trovato che mi è stata recapitata una notifica N015.

Io non mi aspettavo nessuna notifica in quanto si tratta di movimento interno al comune e non di uno spostamento tra comuni subentrati.

**Comment by gcarbonin** [comment]
Si può avere l'id di questa notifica?

**Comment by busaster** [comment]
ID operazione ANPR della notifica è  593119

**Comment by gcarbonin** [comment]
Questo numero è quello di un  5012 di poggio a caiano

**Comment by busaster** [comment]
allora non capisco cosa intende con ID ANPR della notifica, le mando via email XML che ho ottenuto con il servizio di ricerca operazioni e da cui ho ricavato quel numero.

**Comment by busaster** [comment]
Ho ricontrollato le operazioni eseguite e sono queste :

1) id anpr 592789 : mutazione 5001 per cambio indirizzo (tipo 4)
2) id anpr 592790 : mutazione 5001 per aggiornare patenti e veicoli (tipo 2)
3) id anpr 593118 : 5012 annullamento della 592790 
4) id anpr 593119 : 5012 annullamento della 892789

In quest'ultima ho (sbagliando) impostato nella lista controlli RA=1.
Mi viene da pensare che sia questa la causa della produzione della notifica.
Me lo può confermare ?

Grazie

**Comment by gcarbonin** [comment]
Confermo che il problema è RA = 1. Si tratta di un cambio di domicilio?

**Comment by busaster** [comment]
E' un cambio di residenza interno al comune (intera famiglia che si sposta da indirizzo A ad indirizzo B).
Il nostro algoritmo di composizione del XML di annullamento imposta RA nella lista controlli anche in queste situazioni.
Rileggendo la documentazione mi pare però che questo controllo vada specificato solo nei cambi di residenza tra comuni subentrati (par 12.1.4).
Se mi conferma questa analisi eviteremo di impostare RA=1 negli annullamenti dei cambi di residenza interni al comune di lavoro.

**Comment by gcarbonin** [comment]
Confermo che RA=1 fa scattare la notifica
