### ISSUE TITLE
ws [A002] - Errore decorrenza in iscrizione cittadino AIRE

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#3453]
Salve, 
il comune di Monticelli D'Ongina sta tentando di iscrivere in AIRE un cittadino utilizzando il WS in oggetto, ma ottiene l'errore "EN237: La data di decorrenza della nuova residenza non può essere antecedente a quella già registrata" (id operazione ANPR 928016574).
Abbiamo effettuato delle ricerche ma il soggetto non risulta presente in ANPR, pertanto non riusciamo a capire quale dato provochi l'errore ed impedisca l'iscrizione. Abbiamo poi ricercato il soggetto in AE e lì risulta presente.
Abbiamo trovato su Github una segnalazione simile (issue #2021) in cui si fa riferimento a un problema di identificativo famiglia non univoco, ma nella request abbiamo inviato l'id ANPR della famiglia di destinazione e verificato che è identificata univocamente. Come dobbiamo procedere?
In attesa di riscontro, porgiamo cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by ncapozzi** [comment]
Buongiorno,
il problema aveva origine dal fatto che la data di decorrenza della nuova residenza che cercavate di impostare per l'iscrizione del cittadino era antecedente a quella già registrata per la famiglia AIRE nella quale doveva essere iscritto. Abbiamo verificato che avete risolto il problema con operazione 937803143.
