### ISSUE TITLE
Servizio non disponile

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#3454]
Buongiorno,
da stamattina il collegamento attraverso WEBAPP non è stabile.
Da circa 15 minuti restituisce errore "Servizio non disponibile" su qualsiasi richiesta di Mutazione dati"

Anna Maria AIMONE
UPI Torino

**Comment by mttfranci** [comment]
Salve, potete verificare nuovamente?
Grazie in anticipo.

**Comment by UpiTorino** [comment]
Riprovato (ID ANPR 31519137): l'errore "Servizio non è disponibile" persiste

**Comment by ARIANNA81** [comment]
Anche svariati nostri clienti lamentano problemi di connessione sia direttamente da webapp sia tramite applicativo. restiamo in attesa di un riscontro urgente
grazie

**Comment by paoloHV** [comment]
Anche molti dei nostri clienti lamentano problemi WA e WS

**Comment by siscomanpr** [comment]
Anche diversi nostri clienti da questa mattina stanno segnalando problemi con i WS di anpr

**Comment by mttfranci** [comment]
Riuscite a fornirci qualche caso specifico?

**Comment by ARIANNA81** [comment]
Esempio 1: succede random in fase di mutazione di residenza (sia da altro comune sia nel comune) che in fase di art 5 segnali errore
EN493 | L'utente non   dispone dei privilegi per eseguire l' operazione @
ad utenti a cui sulla pratica precedente dello stesso tipo funzioni regolarmente tutto

Esempio 2: in fase di rettifica dati su un cittadino vada in errore di connessione; la stessa operazione eseguita nei giorni precedenti ha sempre funzionato regolarmente. 

E' impossibile darvi errori specifici proprio perchè succede random.

**Comment by paoloHV** [comment]
sottoscrivo esempio 1 e 2 di ARIANNA81

**Comment by mttfranci** [comment]
@UpiTorino salve, ma voi invece prendete errore su tutte le mutazioni da web app? oppure in modo discontinuo come dicono i colleghi?

**Comment by ARIANNA81** [comment]
la discontinuità è peggio del malfunzionamento continuo in determinati casi. abbiamo comuni che ci segnalano che il cambio abitazione è passato per 2 soggetti di 3 inseriti in pratica. poi sistemare queste anomalie è molto più complesso che rifare la comunicazione nel caso non sia passato nessun soggetto.

**Comment by siscomanpr** [comment]
Confermo che i problemi segnalati dai clienti riguardano i servizi 500X.

**Comment by mttfranci** [comment]
Ok, potete verificare se avete ancora problemi dopo le 15.05 circa? (abbiamo provato ad effettuare un intervento)
Saluti

**Comment by UpiTorino** [comment]
Nella fascia oraria sino alle 13, lo dava su pressoché tutte le Mutazioni, si riprovava e andava. Successivamente solo su Mutazioni residenza, ultimo caso alle 14.50, ora pare funzionare
UPI Torino

**Comment by mttfranci** [comment]
@UpiTorino : Ok, grazie del riscontro.  fateci sapere se riscontrate ancora problemi.

**Comment by AriannaIeicicGPI** [comment]
stiamo attendendo riscontro dai clienti. vi facciamo sapere

**Comment by siscomanpr** [comment]
Abbiamo avuto il riscontro da parte di alcuni clienti che  sono riusciti ad effettuare le mutazioni con i servizi 500X senza errori.
Non ci sono pervenute altre segnalazioni di errori su questi servizi dopo le 15.

**Comment by mttfranci** [comment]
Perfetto. Grazie del riscontro.
Saluti
