### ISSUE TITLE
iscrizione di un cittadino cancellato da altro comune conprocedimento aperto

### ISSUE THREAD

**Issue by czxanpr** [italia/anpr#3455]
Buongiorno
devo iscrivere in ANPR un cittadino già iscritto nella  anagrafe locale nel comune di  CATANZARO, cancellato dal Comune di Sorbo San Basile (CZ) per ripristino posizione precedente, lasciando aperto un procedimento, come posso fare per iscriverlo?

[Comune di Catanzaro - Produzione.pdf](https://github.com/italia/anpr/files/9000002/Comune.di.Catanzaro.-.Produzione.pdf)
[Comune di Catanzaro - 1 Produzione.pdf](https://github.com/italia/anpr/files/9000004/Comune.di.Catanzaro.-.1.Produzione.pdf)

**Comment by frmariani** [comment]
il cittadino risulta iscritto nel comune di Catanzaro anche nell'anagrafe nazionale e non soltanto nell'anagrafe locale.
Le operazioni di cancellazione e mutazione di residenza sono state annullate nel 2021.
I pdf che allega non sono prodotti dal sistema ANPR.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
