### ISSUE TITLE
Accesso in consultazione ai dati INA ed ai dati ANPR nel periodo transitorio

### ISSUE THREAD

**Issue by GianM67** [italia/anpr#346]
La vista sulle generalità e le residenze dei cittadini a livello nazionale è utile ai Comuni in diverse situazioni (soprattutto per le pratiche di iscrizione).
Noi, ad esempio, abbiamo presso diversi Comuni procedure automatiche (dunque facenti uso del client SAIA) che assicurano l’accesso in consultazione ad INA ed Anagrafe Tributaria.

Con il progressivo subentro dei Comuni in ANPR, stiamo assistendo a questo scenario:
 - un Comune NON ancora migrato in ANPR non ha l’accesso in consultazione alle posizioni anagrafiche  
    dei residenti in Comuni già migrati
 - un Comune già migrato in ANPR non ha l’accesso in modalità automatica alle posizioni anagrafiche 
    dei residenti in Comuni NON ancora migrati.

Sarebbe secondo noi opportuna una “maggiore integrazione” tra i due mondi per dare la possibilità a tutti i Comuni – anche durante il periodo transitorio - di “avere vista” sempre (anche in modalità automatica) su tutti i soggetti residenti in Italia.

**Comment by mccalv** [comment]
Caro @GianM67 stiamo valutando questa evoluzione con un metodo dedicato alla ricerca che contemporaneamente cerchi su SAIA, ANPR etc.

**Comment by GianM67** [comment]
Grazie, buona cosa! Avete già individuato dei tempi di attuazione?

**Comment by GianM67** [comment]
Buongiorno.
Desidero solo sapere a che punto sono i lavori dell'evoluzione prospettata inerente la ricerca contemporanea anche in INA di un soggetto (via Web Service).
Grazie molte.
Cordiali saluti.

**Comment by gcarbonin** [comment]
E' realizzata e in test interno. E' ipotizzabile il rilascio in ambiente di test nel corso del prossimo mese di febbraio

**Comment by GianM67** [comment]
Grazie molte.

**Comment by GianM67** [comment]
Buongiorno.
Mi piacerebbe avere un aggiornamento sullo stato avanzamento dei lavori di integrazione INA / ANPR.
Sarebbe anche utile avere un'idea sui tempi di rilascio della documentazione inerente i relativi Web Services.
Grazie molte e cordiali saluti.

**Comment by GianM67** [comment]
Buongiorno.
Chiedo gentilmente di dare riscontro al mio post della settimana scorsa. Il tema è sentito.
Grazie molte.
Cordiali saluti.
Stesei  -  Manzin Gianluca

**Comment by gcarbonin** [comment]
Buongiorno. Entro questa settimana pubblichiamo le specifiche; entro la prossima il servizio di interrogazione sarà disponibile in ambiente di test-comuni.

**Comment by GianM67** [comment]
Buongiorno.
Ho visto che c'è stato un aggiornamento della documentazione tecnica il 20.03.
Dal file excel di riassunto non mi sembra che fosse inerente a questo argomento.
Dico bene?

Grazie molte per la collaborazione.
Cordiali saluti.

Stesei  -  Gl. Manzin

**Comment by gcarbonin** [comment]
Il WS è stato realizzato. I comuni NON subentrati potrebbero comunque accedere alla WA di ANPR ma devono eseguire il censimento degli utenti e delle postazioni
