### ISSUE TITLE
IMMIGRAZIONE DA ALTRO COMUNE

### ISSUE THREAD

**Issue by LETSIM22** [italia/anpr#3460]
Comune di FANO
Caricamento Residenza proveniente da altro comune

Restituisce errore

![image](https://user-images.githubusercontent.com/47383691/176399937-69807e7f-6a8e-4d8f-945f-cab7ee4cfcdb.png)

Restituisce identificativo Famiglia ANPR del Comune di provenienza

**Comment by ncapozzi** [comment]
Buonasera,
come indicato nei messaggi di errore nell'operazione è indicato il tipo Mutazione 3 - DATI GENERALI FAMIGLIA CONVIVENZA, non 4 - RESIDENZA SCHEDA. Il tipo mutazione 3 è riservato al Comune proprietario della scheda che attualmente non è FANO.
Per effettuare il cambio di residenza è necessario effettuare un tipo mutazione 4. Per eventuale assistenza sul vostro gestionale vi suggeriamo di contattare la casa software di competenza.
