### ISSUE TITLE
Mancato scarico notifiche emigrazione

### ISSUE THREAD

**Issue by alessiaruggeri** [italia/anpr#3461]
su ANPR nel momento in cui cerchiamo di scaricare le notifiche di emigrazione da altri comuni diverso dal mio, riesco ad ottenere l'id e mi dice di attendere 15 minuti. Nel momento in cui tento di effettuare lo scarico, ANPR mi dice di attendere ancora, questa volta all'infinito.
Rimedi? Fix? Altri casi? Help us

**Comment by mttfranci** [comment]
Non ci è del tutto chiaro quale operazione state effettuando.
Si parla del 4005? potete fornire qualche id operazione da verificare in caso?
Saluti

**Comment by alessiaruggeri** [comment]
Buonasera, è tornato tutto regolare...grazie!
