### ISSUE TITLE
ERRORE: Il campo Questura contiene dei caratteri non validi 

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3462]
Buongiorno,
questa mattina abbiamo cercato di aggiornare il permesso di soggiorno di una cittadina (identificativo scheda anpr 46370636), arrivati alla schermata "mutazione tutti i dati" ci è uscito l'errore in oggetto. 
Non riusciamo ad operare su nessuna voce perchè l'errore sopra è bloccante.
Come possiamo fare?
Vi ringraziamo fin da ora per la vostra preziosa collaborazione.
Andrea Formenti
Uff. Anagrafe 
Comune di Caponago

**Comment by AndreaFormenti** [comment]
Buongiorno,
posso chiedere di avere riscontro?
Grazie.

**Comment by ncapozzi** [comment]
Buonasera,
la presenza delle parentesi con la sigla provincia genera errore. Riprovate ora

**Comment by ncapozzi** [comment]
Il permesso di soggiorno del cittadino è stato correttamente aggiornato in data odierna
