### ISSUE TITLE
ERRORE --- Invocazione di prova servizio 5011

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#3463]
Buongiorno,
Ambiente di test (076083) Comune Di Satriano di Lucania.
Stiamo invocando il Servizio 5011 e otteniamo un Internal error  SOAP fault.
In Allegato la richiesta.
Potreste fare una verifica.
Grazie.
[input.txt](https://github.com/italia/anpr/files/9019731/input.txt)

**Comment by frmariani** [comment]
la richiesta non risulta valida, mancano i dati della sezione che sono obbligatori;

**Comment by mcaputo75** [comment]
Salve , abbiamo provveduto ad inserire i dati obbligatori, ora abbiamo il seguente errore:

 <listaErrori>
            <errore>
                <codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Utente non abilitato 5</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-01 12:52:07 , mittente 076083 , idOperazioneComune 88618</testoErroreAnomalia>
            </errore>
        </listaErrori>

**Comment by frmariani** [comment]
Gentilmente il CF dell'utenza così vi abilitiamo

**Comment by mcaputo75** [comment]
Ambiente di test Comune Di Satriano di Lucania 076083
cf : FNLSRG85D03G942G
Grazie.

**Comment by frmariani** [comment]
L'utente è stata abilitato.
Per un'ulteriore utenza da abilitare, può rivolgersi all'ALS del comune che vi assegnerà il profilo di operatore elettorale.
