### ISSUE TITLE
ERRORE IN FASE DI ISCRIZIONE PER IRREPERIBILITA'

### ISSUE THREAD

**Issue by AriannaIeicicGPI** [italia/anpr#3465]
Buongiorno,
apro ticket per il comune di SAN VITO AL TAGLIAMENTO
chiamando il numero verde per problemi in fase di iscrizione art5 per soggetto ricomparso da irreperibilità al comune è stato indicato di aprire un ticket in github

CF del soggetto: PRVMRC62P03M052Y
errore in fase di iscrizione: idSchedaSoggettoANPR 32131268 non presente o dati anagrafici incongruenti

vi chiedo cortesemente di contattare direttamente il comune nella persona di SIMONIN ELENA
TEL 3384909558 
MAIL  anagrafe@comunesanmichele.it

GRAZIE

**Comment by ncapozzi** [comment]
Al momento la Sig.ra Simonin non risponde.
Faccio presente che il problema nasce dalla differenza nella provincia del Comune di Nascita che sulla scheda cancellata è MB mentre nella nuova iscrizione è MI. La reiscrizione deve riportare in prima battuata gli stessi dati della scheda cancellata quindi MB anche se non valido alla data. Una volta reiscritto il cittadino potete effettuare una mutazione 5008 per modificare la provincia.

**Comment by AriannaIeicicGPI** [comment]
anche correggendo la provincia di nascita non si risolve il problema - segnala errore AEE97 - operazione non effettuabile
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-12 11:03:07 , idOperazioneANPR 944148182

**Comment by ncapozzi** [comment]
Provate ad effettuare l'iscrizione senza validazione del CF (gestioneCF = 3). Poi quando effettuate la modifica della provincia di nascita richiedete la validazione del CF.

**Comment by ncapozzi** [comment]
Il cittadino id 32131268  è stato correttamente reiscritto con CF validato.
