### ISSUE TITLE
ERRORE CAST INSERENDO OPERATORE

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#3466]
cf operatore ZMBMNL62D47F994L

errore cast in inserimento, utente già in possesso di smart card perchè operatore di più comuni.

prego inviare mail di avvenuto sblocco a statocivile@comune.gaiba.ro.it

**Comment by Leonforte** [comment]
Buongiorno, il problema dovrebbe essere stato risolto, potete per favore riprovare ?

**Comment by paoloHV** [comment]
l'operatore mi comunica che è riuscito a inserire la propria utenza
