### ISSUE TITLE
[5008] Errore EN274 in scioglimento unione civile

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#3467]
AMBIENTE DI TEST - COMUNE DI PISA

Inviando un servizio 5008 di scioglimento dell'unione civile (ID Operazione ANPR 53239960) relativa al cittadino con ID soggetto 8253344 ci viene sempre risposto che 'Non e' presente una unione civile corrispondente ai dati indicati'.

Abbiamo verificato sulla webapp ed i dati dell'unione civile sono presenti e corretti, abbiamo anche provato a trasmettere insieme allo scioglimento nuovamente i dati dell'unito civilmente e dell'unione civile ma la risposta è sempre negativa.
Ci potete aiutare nel capire quale sia il problema?

Grazie
Luca Bonini

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
