### ISSUE TITLE
Comune di NERVIANO Cambio di residenza servizio P003

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3468]
Notifiche di cambio abitazione da parte del CITTADINO con CODICE RICHIESTA:

27525577    
27524506    

Per le notifichedi cambio abitazione da cittadini lo stato su ANPR risulta APERTA.
Andando a modificare lo stato con la notifica P003 in IN LAVORAZIONE , anpr ci risponde:

**<codiceErroreAnomalia>EN148</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Il passaggio di stato richiesto non e' consentito.</testoErroreAnomalia>**

Anche se il passaggio da APERTA a IN LAVORAZIONE è corretto.

Inoltre, le notifiche sopra citate, non risultano modificabili neanche da WA.

Rimaniamo in attesa per poter sbloccare le notifiche del comune.
Le pratiche sono state gestitte ma non è stato ancora modificato lo stato delle notifiche.

**Comment by apaolacci** [comment]
Buongiorno,
a causa di un problema db, una sequence oracle in ambiente di produzione ha prodotto per un certo periodo nella giornata di domenica record inconsistenti. Tutte le pratiche interessate come quelle segnalate non presentano più l'errore. 
In caso riscontrate ancora situazioni anomale, segnalatecelo prontamente.

Grazie,
Assistenza ANPR
