### ISSUE TITLE
Controlli differenti su registrazione e annullamento

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#347]
Codogno, ambiente di produzione

Buongiorno, abbiamo registrato l'iscrizione in ANPR del soggetto CRFMRA71S12C816Y che è andata a buon fine anche se il comune di nascita ed il comune di registrazione dell'atto di nascita non erano validi alla data di nascita del soggetto, ottenendo solo il warning EC169 relativo al comune di registrazione.
A causa di un problema nella pratica il comune deve annullare tale iscrizione, ma tale annullamento non è possibile proprio perché il comune di nascita non è valido alla data di nascita del soggetto.
Per questa pratica il comune è bloccato perché, se registra una mutazione del comune di nascita, non può più annullare l'iscrizione a causa della registrazione successiva, quindi come possiamo procedere?
A mio avviso, ritengo necessario che le regole di convalida dei dati, di qualsiasi evento, e l'annullamento dell'evento medesimo debbano essere identiche proprio per non incorrere in queste problematiche.
Cordiali Saluti
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Rinnovando l'invito a non indicare dati personali in questo sito, non abbiamo trovato traccia di registrazioni bloccate con l'errore che indica lei, anche perché in annullamento non si ricontrolla nulla o quasi (se non i dati che servono all'annullamento). L'impossibilità di annullamento deriva dal fatto che è stato iscritto soggetto 1 poi soggetto 2 coniugato con soggetto 1; in questa situazione si deve annullare prima soggetto 2 e poi soggetto 1 (che si cerca di annullare per primo)

**Comment by LucaBonini64** [comment]
Abbiamo indicato una sola persona per comodità, anche perché il comune nella disperazione dopo aver provato varie volte, ha provato a fare anche variazioni del comune di nascita sul secondo elemento per cercare di sanare la situazione. Le persone nella pratica erano 3 e abbiamo eseguito l'annullamento nell'ordine come indicato dalla documentazione (prima 3, poi 2 e 1), la terza persona è stata annullata senza problemi, la seconda persona (che ha lo stesso problema della prima) non è stata annullata a causa del comune di nascita non valido. La situazione è testabile anche dalla WA.

**Comment by gcarbonin** [comment]
Abbiamo analizzato il problema: può riprovare

**Comment by LucaBonini64** [comment]
Il comune riferisce che non riesce ancora ad annullare l'evento a causa di eventi successivi (fatti direttamente dalla WA e che quindi noi non possiamo annullare)

**Comment by frmariani** [comment]
Abbiamo verificato che è stata effettuata un'altra operazione sul soggetto, pertanto le operazioni da annullare sono ( in sequenza):

idoperazioneanpr  1166239   1123980   1123978

**Comment by LucaBonini64** [comment]
Il cliente ha provato ma ci segnala:
"Ho provato di nuovo ma l'operazione con ID   1166239   è relativa alla "mutazione scheda":
1123980 ISCRIZIONE PER ALTRI MOTIVI Completata con esito positivo e warning
1166239 MUTAZIONE SCHEDA Completata con esito positivo e warning
Non trovo un punto dove è possibile ANNULLARE questo tipo di operazione (così come esiste l'annullamento della iscrizione)
Se volete collegarvi guardiamo insieme"

**Comment by gcarbonin** [comment]
Il comune è stato contatto e il problema risolto
