### ISSUE TITLE
Certificato di Stato Libero - Forza Certificazione - Comune di Milano - Non me lo fa scaricare con errore :"Il certificato non puo' essere emesso perche' risulta un procedimento aperto per il soggetto intestatario del certificato"

### ISSUE THREAD

**Issue by riccardopapa** [italia/anpr#3470]
non riesco a scaricare il certificato di stato libero dal comune di milano, ho cambiato residenza un mese fa , e risulta il procedimento ancora aperto

**Comment by FilippoPapi** [comment]
deve contattare il suo Comune, il Comune è l'unico che può operare sui dati
un saluto
