### ISSUE TITLE
Data di nascita ERRATA.

### ISSUE THREAD

**Issue by MasssG** [italia/anpr#3471]
in:  Scrivania / Residenza / Dettaglio richiesta:
data di nascita CORRETTA nel Dettaglio richiesta;
data di nascita ERRATA nella sezione Richiedente.

**Comment by gppbarone** [comment]
Buongiorno, purtroppo per analizzare questo caso ci servono maggiori dettagli, inserisca qualche screen che ci faccia capire il problema e l'id della pratica in questione, evitando di mostrare ovviamente i dati sensibili.

**Comment by MasssG** [comment]
Richiesta cambio di residenza N. 2750129,
![1](https://user-images.githubusercontent.com/80845911/177754507-106bfa37-ae9b-41b9-9a27-23dc8e67f3d3.JPG)
![2](https://user-images.githubusercontent.com/80845911/177754508-7d1fe511-22dd-4853-af42-51eb2f8a67a1.JPG)

**Comment by gppbarone** [comment]
Ciao, non riusciamo a trovare la pratica con questo id 2750129, può verificare se è corretto?

**Comment by MasssG** [comment]
> Ciao, non riusciamo a trovare la pratica con questo id 2750129, può verificare se è corretto?

chiedo scusa: 27501290.

**Comment by gppbarone** [comment]
Grazie della segnalazione, stiamo valutando il tipo di modifica e ti faremo sapere in merito.

Grazie,
Assistenza ANPR
