### ISSUE TITLE
Stampa Certificati ANPR - Richiesta Logo comune

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3473]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Buongiorno
quando viene invocato il WS per la richiesta di stampa certificato ci restituisce un errore che dice che con l'xml della richiesta non abbiamo inviato il logo del comune... Ma noi non abbiamo mai inviato il logo del nostro comune.

Come risolviamo la cosa ?

Grazie

**Comment by cmigliardi** [comment]
buongiorno 
per favore ci potete inviare l' xml della richiesta ? e la risposta ? grazie in anticipo

**Comment by cmigliardi** [comment]
chiedo, ma il logo lo avete caricato in web app area Amministrazione, sezione informazioni aggiuntive ? perché è obbligatorio

**Comment by cmigliardi** [comment]
il  caricamento del logo è un passaggio obbligatorio - non avendo ricevuto  info - si chiude la issue
