### ISSUE TITLE
Sito web.anpr.interno.it non sicuro

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#3477]
Buongiorno
più clienti ci segnalano l'impossibilità di entrare nella web application. Immagino sia scaduto il certificato SSL.

![image](https://user-images.githubusercontent.com/26630945/177759513-6f55c31f-ae78-4ab1-8b03-6a3231f67ca2.png)

**Comment by cmigliardi** [comment]
possono essere risolte ripulendo la cache e i cookies
