### ISSUE TITLE
[5001] Errore EN526 con tipo mutazione 9 in ambiente di TEST

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3478]
Buongiorno,

ieri in ambiente di TEST del comune di Pisa ho inviato un servizio 5001 con tipo mutazione 9 per rettificare un indirizzo. 
La response restituisce l'errore seguente:

EN526 - Per rettificare un indirizzo la data di decorrenza residenza deve essere uguale a quella gia' registrata 19-09-2016
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-06 15:57:20 , idOperazioneANPR 53243459

La data di decorrenza della residenza nella request è stata impostata invocando il servizio 3002 e selezionando la data di decorrenza della residenza meno recente fra tutti i componenti della famiglia (per tutti ha restituito 23/09/2016 quindi abbiamo inserito quella).

Anche consultando da webapp la famiglia 4272503 la data decorrenza residenza è 23/09/2016.

Potete darmi qualche suggerimento per capire meglio il problema? Da dove possiamo ricavare la data 19-09-2016?
Se si dovesse trattare della stessa situazione descritta con la #2499 chiedo se è previsto un intervento come proposto dal collega che ha aperto la segnalazione.

Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by frmariani** [comment]
Sicuramente mi sono spiegata male.
Stiamo parlando di rettifica dell'indirizzo quindi intendevo la creazione della famiglia a quell'indirizzo specifico. 
Nel vostro caso, il cittadino che ha creato la famiglia con data di decorrenza della residenza 19/09/2016, si è spostato in altra famiglia lasciando il secondo componente che ha data di decorrenza della residenza 23/09/2016; la consultazione effettuata sui cittadini componenti della famiglia, non è esaustiva per effettuare una rettifica dell'indirizzo ed è per questo che la proponiamo nel diagnostico di errore.
se volete rettificare l'indirizzo, dovete inserire la data in cui quella famiglia è stata presente per la prima volta a quell'indirizzo, a prescindere dal fatto che il componente originario sia ancora presente o meno nella stessa.
L'operazione è nata per gestire dei refusi e non per elaborazioni massive che,  in questi particolari casi di rettifiche, non sono consigliate.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
