### ISSUE TITLE
Connessione sicura non riuscita web app

### ISSUE THREAD

**Issue by vpadadem** [italia/anpr#3479]
Buon pomeriggio, 
da questa mattina non è possibile accedere alla webapp ANPR, 
riporto di seguito l'errore
Connessione sicura non riuscita
Si è verificato un errore durante la connessione a [dp.anpr.interno.it](http://dp.anpr.interno.it/). Il peer SSL non è stato in grado di negoziare un insieme di parametri di sicurezza accettabile.

Codice di errore: SSL_ERROR_HANDSHAKE_FAILURE_ALERT

è un problema comune?

In attesa 
distinti saluti

**Comment by AndreaFormenti** [comment]
Buongiorno, il problema persiste anche dopo aver ripuliuto la cache e i cookies.
Andrea Formenti
Comune di Caponago

**Comment by campagna2** [comment]
Anche a Imperia il problema persiste.
Annamaria Campagna
Comune di Imperia

**Comment by baldissinn** [comment]
Buongiorno, confermo anche per tutti i comuni che gestiamo come Halley Veneto.
Ieri in qualche modo si riusciva a forzare l'accesso, oggi no.

**Comment by Rossanamigliasso** [comment]
anche a monticello d'alba il problema persiste ed anche aprendo il ticket non siamo stati ricontattati

**Comment by filippo1961** [comment]
IDEM MARSALA
