### ISSUE TITLE
Lista elettorale

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#348]
Nelle specifiche il dato della lista elettorale è un alfabetico di un carattere così descritto: S=elettore, N=non iscritto alle liste elettorali, P=perdita voto. Nell'allegato B del DPCM che definisce i dati ANPR il dato della lista elettorale si chiama "Lista elettorale".
Non credo che "Lista elettorale" si possa rappresentare con i 3 valori sopra scritti, sarebbe utile avere un riferimento normativo o di prassi che indichi tra le competenze dell'ufficiale di anagrafe quelle di acquisire quelle informazioni.
Le liste elettorali sono gli elenchi in cui si comprendono gli elettori, esistono tante liste quante sono le sezioni del comune, le sezioni sono distinte da un numero. 
Lista elettorale potrebbe essere il numero della sezione a cui territorialmente appartiene la persona, questo è un dato a disposizione dell'anagrafe. Alcuni potrebbero interpretarlo come il numero distintivo della lista generale, ma non ricordo una regola che imponga all'anagrafe di gestire questo dato, né all'elettorale di comunicarlo. In ogni caso né l'uno né l'altro danno indicazioni sul diritto elettorale dell'individuo (S, N, P).
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Classifico la domanda come "chiarimento-normativo" per evidenti motivi..
Da un punto di vista meramente tecnico, le due parole "Lista elettorale" riportate in un DPCM possono essere interpretare in almeno due modi: come suggerito o come "presenza nella Lista elettorale" .
Così è stato interpretato (per buona pace di tutti, non dalla scrivente ma dal Ministero dell'Interno). "Presenza nelle lista elettorale"  suggerisce l'utilizzo di "un flag" che assume soltanto due valori : presente o non presente. Così è stato fino a 20 gennaio 2017 (vedi documento riportato a questo link https://www.anpr.interno.it/portale/documents/20182/26001/aggiornamenti_05_10_2017.xlsx/aa1a5d7c-b053-4b35-8623-1674a6ede1f8) quando, con la formazione dell'elenco unico degli elettori degli italiani residenti all'estero 2016 (adempimento svolto per legge dal Ministero dell'Interno),  è emerso che era indispensabile anche l'informazione relativa alla perdita al diritto al voto, già gestita dall'attuale AIRE centrale.

**Comment by Raffive** [comment]
Un cittadino non è automaticamente iscritto nella lista elettorale di un comune solo perché muta la residenza. I tempi sono diversi. Non esiste una lista elettorale nazionale. Neanche per gli aire ma solo una somma di iscritti alle liste elettorali di cittadini che risiedono all'estero e sono iscritti aire. Se non ho capito male con la trasmissione ad anpr della mutazione anagrafica si conferma che la persona gode dei diritti politici?

**Comment by gcarbonin** [comment]
Con la mutazione (dei dati generali e non con quella di residenza) si può indicare se il cittadino è iscritto, non iscritto o ha perso il diritto al voto. L'elenco unico dei elettori AIRE è soltanto nazionale.

**Comment by bfilipazzi** [comment]
Gli interrogativi sulla gestione di questo dato discendono dal fatto che l'ufficio di anagrafe non conosce la condizione dei residenti rispetto al diritto elettorale.
Conosce soltanto la sezione in cui è compresa l'abitazione.
Le comunicazioni fra l'ufficio anagrafe e quello elettorale vanno in una sola direzione: dal primo al secondo, senza ritorni. Lo prevedono le norme, non i sw gestionali. Se mi sfugge qualcosa partecipo a questo forum anche per imparare.
L'interpretazione del ministero dovrebbe essere sostenuta da un riscontro formale, che indichi ai Servizi demografici dei comuni modi e tempi con cui il Responsabile dell'ufficio elettorale informa l'Ufficiale d'anagrafe della posizione elettorale degli iscritti in ANPR.
Filipazzi - Maggioli

**Comment by mccalv** [comment]
@Raffive grazie per il tuo contributo, potresti indicarci il tuo Comune/Sw House? 
In generale richiediamo questa informazione, al meno per i primi interventi, per dare riferimenti agli altri utenti che stanno animando questa discussione in maniera così interessante. 
Grazie!

**Comment by MarcoMigliori** [comment]
_Se non ho capito male con la trasmissione ad anpr della mutazione anagrafica si conferma che la persona gode dei diritti politici?_

Giusto per capire anch'io riprendo questa osservazione. Credo di no, poichè la persona ovviamente gode dei diritti politici, ma con la variazione in ANPR del cambio di residenza (effettuata dal comune di nuova iscrizione uff.anagrafe) non si può dire nulla in merito, in assenza del 3D/XML e delle relative tempistiche elettorali. Mi aspetto quindi di comunicare la mutazione senza dover indicare il campo, oppure se per questioni tecniche fossi costretto a indicarlo, dovrei per forza mettere N "non iscritto liste elettorali".
E' evidente comunque che il valore di questo campo ha senso solo se associato al comune che l'ha indicato per l'ultima volta. C'è anche un intervento precedente in merito: #291 

Non mi appare ancora evidente invece, lo scopo per cui sono presenti queste informazioni.

**Comment by Raffive** [comment]
E' vero, scusate 
Comune di Spinea (VE)
seguirò questa discussione con discontinuità in questo periodo in quanto sono impegnata con la consultazione referendaria. 
Come sicuramente saprete, l'elettorale chiude il "cerchio" sulle registrazioni di stato civile e di anagrafe.
Come saprete l'anno prossimo ci saranno le consultazioni politiche e le cose dovranno essere cristalline e senza dubbi.
Farò tutte le prove  necessarie per verificare la correttezza degli allineamenti dei dati di stato civile, anagrafe ed elettorale registrati tra apr e anpr dandovene conto.
Dati che poi gli ufficiali di stato civile, anagrafe ed elettorale certificano con  responsabilità personale attribuita loro dalla legge.
E considerato che firmo io, signori e signore, mi prendo l'ultima parola in merito.

Raffaella Campagnol
Comune di Spinea
tel 0415071155

**Comment by Raffive** [comment]
neanche a farlo appositamente! la collega dello stato civile mi segnala che un bimbo:
nato 08/10/2017 - iscritto PER NASCITA  in anagrafe da decorrenza 09/10/2017
 chiesto un certificato storico di residenza in WA alla  data 08/10/2017 -non risulta iscritto: FALSO E' UNA ISCRIZIONE PER NASCITA! dov'era residente l'8?
se solo questo fosse nato il 31/12 .. e l'iscrizione anagrafica fosse fatta su dichiarazione dei genitori (che hanno 10 giorni di tempo per farla) il 3 di gennaio ..non lo iscriverei neanche in semestrale...
non immagino cosa può comportare sulle cittadinanze!
continuo con le verifiche ma temo che dovrò parlare con la mia prefettura.
Raffaella 
Spinea

**Comment by bfilipazzi** [comment]
L'ultimo post dell'utente Raffive andrebbe spostato nella issue "343 Data decorrenza su comunicazioni dell'ufficiale di stato civile" perché è riferito a quell'argomento
Grazie - Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Il commento riguarda un'altra issue.  Perché non parlate direttamente con il Ministero?

**Comment by Raffive** [comment]
Buongiorno Dott.ssa Carbonin, probabilmente ho frainteso io, avevo capito che è Lei il tramite con il ministero.
Mi sono sbagliata. Per cortesia può darmi i riferimenti di contatto della persona al Ministero, che immagino sia quello degli interni, che segue l'ANPR?
Giusto per evitare di dover scrivere direttamente a Minniti.
La ringrazio della cortesia.
Raffaella
Comune Spinea

**Comment by mccalv** [comment]
Salve @Raffive , può scrivere una mail a segnalazioni-anpr@teamdigitale.governo.it e noi provvederemo (Team Digitale) a discuterla con il Ministero nella prossima riunione del Program Office del contratto ANPR (entro una settimana). 
Un caro saluto

**Comment by Raffive** [comment]
Mi scusi, nel team digitale ci sono ufficiali d'anagrafe?
perché mi sembra che, a parte i problemi tecnico informatici del sistema sui quali voi siete gli esperti, ci sia un misunderstanding  di fondo ovvero che voi avete l'onere di tradurre in sistema informatico i diritti soggettive delle persone che noi dobbiamo garantire con l'applicazione delle norme. E mi sembra che ci sia qualche disallineamento.
dobbiamo capirci e incontrarci su questo punto, diversamente perderemo entrambi.
Vi confesso che ho voluto passare in ANPR per non avere più la "croce" INASAIA. Non vorrei diventasse ANPR la prossima.
Grazie dell'attenzione.
Raffaella

**Comment by mccalv** [comment]
Non ancora :) Ma nella firma del contratto con il Ministero abbiamo assunto il ruolo di Program Office e quindi ci stiamo occupando di accelerare il processo di ANPR. 
Tra le attività che stiamo svolgendo ci sono quelle di porre al ministero e cercare di sbloccare alcuni chiarimenti ove richiesti. 
Eviterei di mettere su questa piattaforma dati personali, se cmq manda una mail le comunicheremo anche un indirizzo diretto per una chiacchierata. 
un caro saluto

**Comment by Eduardo1977** [comment]
Ho seguito molto questa discussione grazie agli interventi interessanti che sono stati fatti.
In attesa di chiarimenti, visto che la discussione è ancora "aperta", siccome a breve dovrei effettuare il subentro di un comune, mi chiedo se ha senso inviare i dati "listaElettorale" . Si possono omettere o nel caso inviare "N" per tutti i soggetti?

**Comment by Raffive** [comment]
Buongiorno, 
posso sapere da dove è preso il dato elettore SI/NO/P?
scheda anagrafica?
grazie
Raffaella
Spinea

**Comment by MarcoMigliori** [comment]
E' una domanda apparentemente semplice, ma molto interessante.
Tecnicamente è una informazione implementata dal singolo fornitore. Che potrebbe prenderlo solo dai dati dell'ufficio elettorale, non dalla scheda anagrafica.
I dati che sono richiesti sono:
1. E' elettore? valori S=Sì   (elettore)     N=No (non iscritto alle liste elettorali)     P=Perdita diritto al voto
2. Comune appartenenza Lista elettorale (se omesso si assume il comune di residenza)

Però li sta inviando a fronte di una operazione di anagrafe: subentro / iscrizione / mutazione / cancellazione.

Al subentro costerebbe poco indicarli, ma sarebbe una fotografia ferma nel tempo. Di quale utilità?
In caso di iscrizione è impossibile per i diversi tempi elettorali, indicare il dato. Certo sarebbe iscritto nelle liste elettorali dell'altro comune, dato non in possesso dell'anagrafe di iscrizione, e comunque non di sua competenza.
In caso di cancellazione, ad esempio per un comune non subentrato, potrei inviare solo un dato provvisorio, ovvero nella maggioranza dei casi che è ancora elettore nel mio comune.

In caso di iscrizione/cancellazione nelle liste elettorali, avrei la domanda "perchè devo mandare una comunicazione ad ANPR di iscrizione elettorale, come ufficio anagrafe?". E d'altra parte se non glielo comunico, potrebbe rimanere un dato non aggiornato, come ad esempio l'indicazione di elettore data dal precedente comune di iscrizione ANPR (variato residenza).

Immagino e potrei sbagliarmi perchè non mi sembra documentato che questa gestione sia prevista in sostituzione di Anagaire, con lo scopo di formare in qualche modo gli elenchi degli elettori all'estero.
Se questo fosse lo scopo riterrei più opportuna l'invio di un file massivo, come ipotizzato per altri argomenti in altri issues.
Mi aiuterebbe capire lo scopo della presenza del dato. Altrimenti come fornitore sarei orientato a non inviare il dato ad ANPR: dalle specifiche che ho controllato finora, non mi risulta obbligatorio. 

Marco Migliori
PAL Informatica

**Comment by bfilipazzi** [comment]
Condivido l'opinione di Marco Migliori che ha esposto con precisione l'argomento.
Filipazzi - Maggioli

**Comment by MarcoMigliori** [comment]
Vedi anche risposta in #359 

_ListaElettorale indica se la persona è iscritta o meno nella lista; il "non iscritta" si articola in due casi: non elettore (ad es. bambino) o perdita del diritto al voto. Il dato è facoltativo per i residenti ma obbligatorio per gli AIRE: corrisponde, infatti, all'attuale TIPOELETTORE di AnagAire;_

**Comment by gcarbonin** [comment]
Chiudo in quanto l'argomento è stato trattato e concluso nell'altra issue
