### ISSUE TITLE
OPERAZIONE NON EFFTTUABILE AE ERRORE

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#3483]
Diversi clienti segnalano problemi in consultazione AE e operazione che coinvolgono AE danno errore 97 (operazione non effettuabile). ci sono problemi???

**Comment by paoloHV** [comment]
danno errore anche tutte le iscrizioni per nascita residente/AIRE o che includono validazioni o perazioni sul CF

**Comment by filippo1961** [comment]
idem comune di Marsala

**Comment by paoloHV** [comment]
sembra ritornata a funzionare regolarmente
