### ISSUE TITLE
Errore nel sito ANPR

### ISSUE THREAD

**Issue by PaoloCardinale99** [italia/anpr#3484]
Buonasera, stavo loggando nel sito dell'Anpr per il cambio residenza, ma nel login ho riscontrato questo problema:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica"

Ho provato ad accedere all'agenzia delle entrate con il mio SPID e il codice fiscale risulta ok.

Quale potrebbe essere il problema? Grazie mille.

**Comment by cmigliardi** [comment]
salve per favore ci può fornire le prime 6 lettere del suo codice fiscale ?  grazie

**Comment by PaoloCardinale99** [comment]
> salve per favore ci può fornire le prime 6 lettere del suo codice fiscale ? grazie

CRDFNC

**Comment by cmigliardi** [comment]
la scheda in Anpr è in stato Cancellata - si rivolga al suo comune di competenza Palermo per le verifiche -  non possiamo fornire ulteriori dettagli - la issue si chiude
