### ISSUE TITLE
Mutazione tutti dati (generalità) ERRORE AEE95 - Operazione non effettuabile

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3486]
Buongiorno.

Ambiente di produzione del comune di VENAFRO.
L'invio dell'operazione in oggetto per il cittadino con id ANPR 182180687 restituisce il seguente errore
AEE95 - Operazione non effettuabile - Cognome: xxxx Nome: yyyy CF: zzzz
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-13 10:39:54 , idOperazioneANPR 945415274 - 

Con la mutazione si vuole variare cognome e nome del cittadino e successivamente occorrerà anche variare la data di nascita (ovviamente con altra operazione)

Al cittadino deve essere emessa una nuova carta di identità ed il comune chiede di intervenire in tempi brevi.

Si ringrazia.
G. Trisolini

**Comment by ncapozzi** [comment]
Buonasera,
il codice fiscale vecchio e quello nuovo devono essere collegati in Agenzia delle Entrate. Non potete eseguire autonomamente questa operazione perché i due CF differiscono per più di 3 dati (cognome, nome, giorno, mese, anno di nascita) . Dovete per tanto inoltrare una richiesta a entrate.archivioanagrafico@agenziaentrate.it allegando tutta la documentazione indicata nella guida per il collegamento tra CF.
[Operazioni sui CF - documentazione da allegare (v.4).pdf](https://github.com/italia/anpr/files/9112034/Operazioni.sui.CF.-.documentazione.da.allegare.v.4.pdf)
