### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by mauricio-oa** [italia/anpr#3490]
Buongiorno,

Quando provo di acedere al sito di ANPR (https://www.anagrafenazionale.interno.it/), utilizando il SPID, acconsento l'utilizo del mio codice fiscale e avanzo, nel prossimo schermo ricevo il errore:

> Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Sono residente alla comune di Casaletto Lodigiano, provincia di Lodi, ho contattato il comune e non hanno riscontrato problemi con la scheda anagrafica.

E sembra che dovuto a questo problema, il comune non riesce a rilasciare la carta d'identita.
Lo stesso sucede com ASL, che non riesce a iscrivermi nel sistema di salute e conseguentemente rilasciare la mia tessera sanitaria, entrambi sistema sempre puntano ad un errore con i dati ANPR.

Chiedo aiuto per fare la verifica su miei dati perche non riesco a avanzare con la mia vitta senza la carta d'identita e la tessera sanitaria. 

**I primi 6 caratteri del mio codice fiscale sono**: LVRMRC

**Comment by cmigliardi** [comment]
come ho già scritto . il comune deve allineare i dati con agenzia entrate e deve validare il codice fiscale . il comune dee verificare i dati non nella banca dati locale ma in anagrafe nazionale come da normativa- se il comune ha difficoltà può chiedere assistenza -

**Comment by mauricio-oa** [comment]
Ho appena chiamato il comune e mi hanno detto esatamente questo, che hanno fatto la verifica nella banda dati in anagrafe nazionale, ma loro no riescono a cambiare i dati in questa banca nazionale.

**Comment by mauricio-oa** [comment]
Potresti gentilmente fare la verifica per il codice fiscale LVRMRC ?

**Comment by mauricio-oa** [comment]
Chiedo aiuto perchè è da più di 4 mesi che ho questo problema.
Prima con la comuni di Fregona (TV), loro non riuscivano a sistemare/allineare i dati, adesso con la comuni di Casaletto Lodigiano (LO).

**Comment by cmigliardi** [comment]
il comune ha tutti gli strumenti  per risolvere -

**Comment by mauricio-oa** [comment]
Purtroppo non so più cosa fare, il comune dice che solo l'ANPR può risolvere e io sono in mezzo.
Ha alcuna domanda specifica che io possa chiedere il comune di fare quando chiamerano il supporto di ANPR?
La signora del comune ha già entrato in contato con il numero verde e aspesta una risposta dell'ANPR, ma non credo che ci l'avra questa risposta.

**Comment by cmigliardi** [comment]
comprendo la sua esigenza, ma è il comune che può agire e solo lui . il comune può chiamare il numero verde dell'assistenza - si deve adoperare il comune - non so cosa dirle di più -  non è vero come dice il comune  che non forniamo assistenza.

**Comment by cmigliardi** [comment]
probabilmente non riesco a spiegarmi - non è un problema di avere 3  o più nomi -  è il comune che deve agire per risolvere

**Comment by cmigliardi** [comment]
esattamente
