### ISSUE TITLE
Certifica di Stato di famiglia per una persona esterna al nucleo familiare

### ISSUE THREAD

**Issue by lucnap** [italia/anpr#3491]
Buongiorno, come specificato nel regolamento anagrafico della popolazione residente all. art. 33, qualsiasi cittadino può chiedere un certificato di stato di famiglia e di residenza per chiunque. Purtroppo nell'applicazione questo non è possibile, si può chiedere solo per la propria famiglia.

**Comment by cmigliardi** [comment]
buongiorno, certamente allo sportello è così. online invece segue le indicazioni del Garante alla privacy .

**Comment by lucnap** [comment]
dove posso trovare l'indicazione del garante della privacy in merito a questo specifico divieto?

**Comment by cmigliardi** [comment]
un conto è il portale di un comune  - un conto è il portale del Ministero dell'Interno

**Comment by cmigliardi** [comment]
il quesito non lo deve rivolgere a noi
