### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio #3072

### ISSUE THREAD

**Issue by 19riccardo84** [italia/anpr#3492]
Buonasera,
Sono residente nel comune di Angri Salerno - e quando provo ad accedere al sito di ANPR ricevo l' errore:
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica. Ho fatto di tutto tramite Pec ad ANPR comune di Angri e a Napoli ove prima di trasferirmi ad angri per matrimonio vivevo mentre da settembre 2019 risulto ad Angri. Sono andato al Comune di Napoli e sta tutto in ordine. ho telefonato al numero verde di ANPR e dicono che non possono risolvere i problemi dei cittadini. Lunedi vado al Comune di Angri ma ho perplessità che li siano in grado di risolvere. E alle Pec mie e anche del mio avvocato nessuno ha risposto. Ho bisogno delle vostro aiuto perchè mi serve ANPR per le pratiche di adozione da fare perchè devo scaricare i documenti miei. Il mio codice fiscale è RSSRCR84E31F839E se cortesemente mi aiutate vi sarei infinitamente grato. Grazie @cmigliardi @mttfranci @frmariani @mccalv @vintra73 @rvinzani @rasky @ccontavalli Mi rivolgo a voi in particolare

**Comment by rvinzani** [comment]
Gent.le Sig. Rossiello, risulta iscritto sia nel comune di Agri che in quello di Napoli. Il comune di Napoli deve quindi cancellarlo per doppia iscrizione. Se il comune di Napoli avesse difficoltà ad effettuare l'operazione può rivolgersi al nostro servizio di assistenza ANPR
