### ISSUE TITLE
Errore AEE96 durante rettifica cognome

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#3494]
Comune di S.Angelo dei Lombardi (AV)
Il consolato di Lione ci richiede la correzione del cognome del cittadino con id 79429605
da CHINAL-FELELLA  a   CHINAL--FELELLA   (doppio trattino)

Riscontriamo l'errore in oggetto durante l'esecuzione della mutazione dati:
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-14 17:24:02 , idOperazioneANPR 947257448 (Codice: EN527)

**Comment by ncapozzi** [comment]
Buonasera
Agenzie delle Entrate non accetta il doppio trattino tra i due cognomi. Stanno apportando delle modifiche proprio per gestire le anagrafiche dei cognomi francesi che prevedono questi doppi trattini consecutivi. Tali modifiche dovrebbero andare a regime dopo l’estate.
