### ISSUE TITLE
1 mese, ma pratica ancora in stato aperta, come faccio, chi chiamo?

### ISSUE THREAD

**Issue by LeonardoFixer** [italia/anpr#3495]
il 9 giugno ho inserito la richiesta, è ancora in stato Aperta. 
Chi e ome posso contattare per risolvere e capire che succede?
Grazie, Leonardo

**Comment by FilippoPapi** [comment]
buongiorno
deve contattare il suo comune di residenza. 
il sito di ANPR è il tramite tra il cittadino e il Comune ma l'operatività sui dati è solo del Comune.
saluti

**Comment by MarcoMigliori** [comment]
Dove trasferisce la residenza, è lì (attraverso il portale) che ha presentato la sua dichiarazione.
