### ISSUE TITLE
Smart card bloccata

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3496]
Buongiorno,
una collega del Comune di Ravenna non è mai riuscita ad utilizzare la smart card ricevuta poiché risulta con PIN bloccato e PUK errato.  Il numero della sco è 039014 1207100000032166.

Grazie 
Katia

**Comment by Leonforte** [comment]
buongiorno, è stata richiesta una nuova carta che sarà disponibile presso la Prefettura di competenza tra qualche giorno. La carta dovrà essere consegnata dalla Prefettura e poi attivata dall'ALS del comune, buon lavoro, saluti
