### ISSUE TITLE
CANCELLAZIONE PER DECESSO

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3499]
Buongiorno,
la sig.ra  id anpr 72840161 è deceduta in data 17/07/2022, in data 18/07/2022 abbiamo inserito i dati di vedovanza (non presenti e richiesti dal comune di decesso). Oggi procediamo alla cancellazione per decesso (in quanto comune di residenza) ma compare il messaggio "La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 18-07-2022 (Codice: EN240)" l'id operazione è idOperazioneANPR 951045976.
Come possiamo fare? 
Vi ringrazio fin da ora per il cortese riscontro.
Andrea Formenti
Uff. Anagrafe Caponago (Mb)

**Comment by ncapozzi** [comment]
Buongiorno
L'inserimento della vedovanza è stato effettuato con dataDecorrenza 2022-07-18, pertanto la cancellazione per decesso deve avere
dataDecorrenza maggiore o uguale 2022-07-18 (data decorrenza dell'ultima operazione effettuata sul soggetto)
data decesso uguale 2022-07-17
