### ISSUE TITLE
ANPR in produzione: gestione certificati di postazione

### ISSUE THREAD

**Issue by antonioluberto** [italia/anpr#35]
Buongiorno.
La soluzione di Dedagroup per la cooperazione applicativa verso ANPR è rappresentata da applicazione web pubblicata su cloud. Dovendo utilizzare la soluzione medesima una volta eseguito il Subentro definitivo (Comune di Cesena), siamo a chiedervi:
a) è necessario installare certificati di postazione sui client?
b) i certificati di postazione vengono utilizzati semplicemente per  firmare l’id postazione che viene passato nella richiesta verso ANPR?
c) l’id di postazione firmato è praticamente una stringa costante che il browser passa all’ applicazione server affinché possa formare la richiesta verso ANPR? In tal caso l’identificazione della postazione appare debole; è comunque necessaria?

Ringraziando sin d'ora per le indicazioni che vorrete fornirci, porgo cordiali saluti.

Antonio Luberto
Information systems analyst
Dedagroup Public Sector & Utilities
T 0461 997144 | M 348 1501304 | VoIP 900144
Dedagroup Public Services Srl – Sede di Trento, Loc. Palazzine 120/f

**Comment by gcarbonin** [comment]
Buongiorno. AgId sta seguendo il suo problema.

**Comment by ccontavalli** [comment]
Per dare aggiornamento al ticket:
- AgID sta valutando la richiesta in merito al contenuto del DPCM, ci sono state diverse conversazioni in merito negli ultimi 3 giorni.
- Abbiamo parlato con Dedagroup per chiarire alcuni dei dettagli tecnici.

Speriamo di poter fornire delle raccomandazioni tecniche a breve.

**Comment by ccontavalli** [comment]
Un altro aggiornamento: dovremmo essere in dirittura di arrivo nella pubblicazione di un chiarimento. Speriamo nelle prossime 2 settimane.

**Comment by GianM67** [comment]
Buongiorno.
Desidero solo chiedere se è stato pubblicato l'ulteriore chiarimento citato sopra.
Grazie.
Saluti.
Stesei - Manzin Gianluca

**Comment by lamefrog** [comment]
Nell’allegato C del DPCM 194 del 10 novembre 2014, nel caso di accesso del Comune via Web service, sono previsti i seguenti requisiti di sicurezza:

1. il certificato identificativo, riferito alla postazione, memorizzato al suo interno, emesso dalla Certification Authority;

2. il riconoscimento dell'operatore tramite la userid e password utilizzata per accedere ai servizi dei sistemi informativi comunali, che garantiscono l'autenticazione dell'utente e la verifica dei diritti di accesso dello stesso alle varie funzionalità applicative;

3. il certificato identificativo, riferito al server ospitante l'applicazione che utilizza il Web service, memorizzato al suo interno, emesso dalla Certification Authority.”

 I requisiti di sicurezza elencati intendono perseguire i principi di sicurezza legati all’identificazione:

- della postazione da cui è avvenuta la richiesta;

- dell’operatore che ha effettuato la richiesta;

- del Comune da cui è pervenuta la richiesta.

Inoltre nello stesso allegato si indica che “l’operatore accede autenticandosi tramite la userid e la password utilizzata per accedere ai servizi dei sistemi informativi comunali”. Questo evidenzia che il sistema di sicurezza di ANPR si affida ai sistemi locali nell’identificazione e nella definizione dei titoli autoritativi degli utenti/ufficiali di anagrafe che hanno diritto di accedere e modificare i dati contenuti in ANPR stessa, demandando allo stesso Comune l’organizzazione e la gestione delle utenze.

Quindi il perseguimento dei principi di sicurezza è raggiunto assegnando responsabilità distinte, ma integrate, localmente ai comuni e centralmente al sistema ANPR. La distribuzione delle responsabilità è coerente con quanto espresso dal Garante per la protezione dei dati personali nel parere 3105794 del 17 aprile 2014 relativo al DPCM 194/2014, in cui tra l’altro afferma “l'importanza di un equo bilanciamento delle esigenze istituzionali ad essa sottese con i diritti delle persone.”

Tra le esigenze istituzionali vanno annoverate la rapida attuazione della circolarità anagrafica tra le Pubbliche amministrazioni, principale obiettivo del sistema ANPR, e il contenimento della spesa espresso nell’articolo 7 “Invarianza finanziaria” del citato DPCM 194/2014. Pertanto è necessario porre in atto tutte le azioni utili per accelerare il processo di messa in esercizio del sistema ANPR, contenendo i costi dei Comuni coinvolti, senza altresì venire meno ai principi di sicurezza.

Al fine di accelerare l’attuazione di ANPR, senza far ricadere un eccessivo onere finanziario sui Comuni e garantendo la necessaria sicurezza è possibile distribuire le responsabilità relativa all’identificazione della postazione da cui è pervenuta la richiesta tra le componenti centrali e locali del sistema. Nello specifico il Comune può autorizzare un’unica postazione, il gateway da cui sono realizzate le richieste e a cui sono inoltrare le risposte per l'integrazione con ANPR  , assumendosi la responsabilità di tracciare e archiviare il riferimento alla postazione interna al proprio dominio applicativo da cui è partita ogni richiesta/risposta verso/da ANPR e ponendo in essere meccanismi atti a consentire la connessione solo da postazioni autorizzate.

Sarà cura del Comune predisporre un documento contenente le misure e le procedure di sicurezza che l’amministrazione adotta per assicurare la tracciatura delle postazioni autorizzate e l’archiviazione dei dati relativi alle postazioni autorizzate e gli utenti che hanno generato una interazione tra il gateway del Comune e la componente centrale ANPR.

Relativamente alle interazioni con il sistema ANPR si ricorda che ogni azione richiesta è univocamente identificata dall’idOperazione associato dalla componente centrale di ANPR. Al fine di rendere le misure e procedure di sicurezza adottate dal Comune conformi ai principi del DPCM 194/2014, lo stesso assicura che per ogni idOperazione, generato da una richiesta del proprio gateway, sia possibile l'individuazione certa della postazione autorizzata e dell’utente.

In sintesi la distribuzione di responsabilità per l’identificazione delle postazioni autorizzate e degli utenti è così determinata:

- la componente centrale ANPR garantisce che per ogni idOperazione sia identificato in maniera certa il gateway del Comune richiedente;

- il Comune per ogni idOperazione assicura l’identificazione certa della postazione autorizzata interna al proprio dominio applicativo e l’utente.

La soluzione individuata è coerente con il principio di autonomia organizzativa dei comuni, sancito dal comma 4 dell’articolo 3 del Decreto legislativo 267 del 28 settembre 2000, detto anche “Testo unico delle leggi sull'ordinamento degli enti locali” (T.U.E.L.) in cui si afferma che “i Comuni e le Province hanno autonomia statutaria, normativa, organizzativa e amministrativa, nonché autonomia impositiva e finanziaria nell'ambito dei propri statuti e regolamenti e delle leggi di coordinamento della finanza pubblica”.

(Guido Pera - Agenzia per l'Italia Digitale)

**Comment by lamefrog** [comment]
Si rammenta che il Comune è responsabile della comunicazione al sistema ANPR, attraverso le funzionalità presenti nella Web App, delle proprie scelte organizzative riguardanti l'elenco degli utenti abilitati ad accedere ai servizi del sistema ANPR, compreso il profilo autorizzativo ad essi assegnato.

Questo è dovuto alla necessità di proteggere le risorse contenute in ANPR e permetterne l'accesso alle stesse solo agli utenti di cui sia stata verificata la compatibilità con le policy di sicurezza.

(Guido Pera - Agenzia per l'Italia Digitale)
