### ISSUE TITLE
[ws] documentazione: lista controlli

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#350]
buongiorno.

forse sto cercando nel punto sbagliato, ma riguardando la lista degli ultimi aggiornamenti (aggiornamenti_05_10_2017.xlsx), ho visto che nella documentazione tecnica dovrebbero esser stati "specificati i valori attualmente utilizzati della lista controlli" (rif. aggiornamenti del 21/06/2017)

guardando gli excel con le specifiche tecniche, trovo qualche dettaglio solo per il servizio 5001
Nome =   FI | Valore = 0
Nome = FI | Valore = 1
Nome = FC | Valore = S

al contrario non trovo niente per gli altri servizi di cui si parla (1002-A001-A002-5012)

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
I valori utilizzati sono specificati nel documento MI-14-AN-01 Specifiche generali ANPR nei seguenti paragrafi:
11.1.2 Iscrizione per altri motivi
11.3.1 Mutazione famiglia/convivenza
11.3.2 Mutazione residenza
11.3.6 Annullamento mutazione
12.1.4 Annullamento mutazione residenza (ripristino)
13.1.1 Iscrizione per nascita AIRE
13.1.2.1 Iscrizione per altri motivi AIRE
13.3.1 Mutazione dati AIRE
Riporteremo anche nella restante documentazione, ove mancante

**Comment by AMonopoliADS** [comment]
sono stato fuorviato dal fatto che nel foglio di excel viene indicato questo come documento modificato:
"Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica - rar"
non il pdf.

nell'attesa del vostro aggiornamento, faccio riferimento al pdf.
grazie

**Comment by ncapozzi** [comment]
La documentazione xlsx è stata aggiornata
