### ISSUE TITLE
Mancate notifiche cancellazioni/ripristini in ambienti di test 

### ISSUE THREAD

**Issue by CGIRELLI-HUB** [italia/anpr#3500]
Buongiorno, 
rileviamo che da qualche tempo non funzionano più le notifiche di cancellazione e di ripristino nei due ambienti di test dei comuni di  Istat 037050 SALA BOLOGNESE e Istat 050028 PONSACCO.

E precisamente l'ultima notifica di cancellazione presente in WEBAPP su SALA BOLOGNESE è del 8/06 nr 50185163 e su PONSACCO 
del 24/06 nr 51250987

Di seguito due esempi recenti: 
1) Iscrizione in data 08/07/2022 del soggetto con ID ANPR 26868418 proveniente dall'ambiente di test del comune di SALABOLOGNESE  è stato iscritto nell'ambiente di test del comune di PONSACCO ma nulla viene rilevato nella sezione Utilità e Notifiche di ANPR e quindi non possiamo recuperare la notifica. 

2) Iscrizione in data di oggi 19/07/2022 del soggetto con ID ANPR 26945672 proveniente dall'ambiente di test del comune di PONSACCO ed iscritto nell'ambiente di test del comune di SALABOLOGNESE. Questo caso l'ho creato oggi per permettervi un controllo non troppo datato del flusso. 

Resto a disposizione per eventuali chiarimenti se necessari.
Grazie 
Cordiali saluti 

Cinzia Girelli - GPI S.p.A.
Cell. 3346216774

**Comment by amollicone1982** [comment]
ci potreste dire gli id dell'operazione di iscrizione

**Comment by CGIRELLI-HUB** [comment]
Si certo rispettivamente per i due casi
1) ID 53249971 MUTAZIONE RESIDENZA 
2) ID 53290836 MUTAZIONE RESIDENZA

**Comment by CGIRELLI-HUB** [comment]
le vedo sulle WEBAPP, su SALA sono ora disponibili anche tutte le pregresse. proviamo a recuperarle nel gestionale e proviamo a rifare delle nuove iscrizioni per capire se il problema permane. Grazie
