### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio #3072 #3492

### ISSUE THREAD

**Issue by Francescoperna1993** [italia/anpr#3502]
Salve ho problema con l'accesso al portale, tramite spid mi restituisce il messaggio di errore <purtroppo non è stato possibile accedere al servizio ecc>
Il mio codice fiscale è prnfnc
Grazie in anticipo.

**Comment by cmigliardi** [comment]
salve in Anpr non esiste la sua scheda - le consigliamo  di rivolgersi  al comune di Roma che ha competenza .   si chiude la issue
