### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

### ISSUE THREAD

**Issue by jamboke** [italia/anpr#3507]
Buongiorno, sono cittadino all'estero e mi da il seguente errore: "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."
Mio Codice Fiscale è valido se lo cerco sul https://telematici.agenziaentrate.gov.it/VerificaCF/Scegli.do?parameter=verificaCf
I primi 6 caratteri del mio codice fiscale sono: PRRTHG
Grazie

**Comment by cmigliardi** [comment]
salve in Anpr non esiste  la sua scheda - si rivolga a comune che l'ha iscritta all'Aire.   si chiude la  issue
