### ISSUE TITLE
[Subentro] File APR: Data scadenza Carte Identità

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#351]
Buongiorno,
ricontrollando le specifiche per le Carte d'identità mi è venuto un dubbio leggendo la condizione (senz'altro sbagliata, almeno credo) che deve soddisfare il valore di [dataScadenza]: "Verifica che la data non sia superiore alla data di richiesta del servizio".
Questa condizione, che invece va bene ed ha senso per [dataRilascio], mi ha fatto riflettere su un'altra cosa: se la carta d'identità è già scaduta bisogna (o si può) inviare lo stesso? Oppure, solo se è in corso di validità?
Grazie

Eduardo Gira
Servizi Locali S.p.A.

**Comment by mttfranci** [comment]
Grazie per la segnalazione, in effetti il vincolo descritto è errato. Provvederemo ad aggiornare le specifiche.

**Comment by Eduardo1977** [comment]
Grazie. Attendo chiarimenti in merito anche all'altro dubbio.
Le carte d'identità scadute, devono essere inviate? Oppure solo se sono ancora in corso di validità?

**Comment by mttfranci** [comment]
Non è necessario inviare carte di identità già scadute alla data del subentro in quanto si tratta di un dato storico per noi.
Ad ogni modo se dovessero essere inviate verranno acquisite senza generare anomalie.

**Comment by Eduardo1977** [comment]
Grazie, molto chiaro

**Comment by ncapozzi** [comment]
Il file cartaIdentità.xls è stato aggiornato
