### ISSUE TITLE
[ws3002] Consultazione: msg. "La richiesta effettuata non produce alcun risultato"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3510]
ambiente di PRODUZIONE - comune di SAN DONATO MILANESE (015192)

idSoggettoANPR 30017444

la consultazione per idSoggettoANPR risponde correttamente con i dati del soggetto residente a San Donato Milanese.
la consultazione per codiceFiscale o Cognome / Nome, invece, produce in risposta il messaggio "La richiesta effettuata non produce alcun risultato"

i campi "per ricerca" utilizzati nella request sono coerenti con quelli del soggetto con idANPR 30017444, per cui non riusciamo a capire perchè la consultazione non vada a buon fine.
la stessa ricerca per codiceFiscale o per Cognome / Nome fatta anche da web-app ottiene lo stesso risultato.

potete verificare se c'è qualche anomalia che giustifichi questo comportamento?

grazie
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
buongiorno.
c'è qualche riscontro dalle verifiche effettuate su questa issue?
grazie

**Comment by ncapozzi** [comment]
Buonasera,
l'idsoggetto 30017444 è associato ad un CF presente anche su una scheda cancellata con anomalie che sono state rimosse. Adesso effettuando la ricerca per CF dovreste vedere sia la scheda cancellata che quella attiva.
