### ISSUE TITLE
Problema con cambiamento in Consolato di Manchester

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3511]
Buongiorno, ecco l'errore che mi compare

1 Errore Anpr Cod: EC032 - Codice consolato di residenza 2310604 inesistente sulla tabella di riferimento - Id Famiglia/Convivenza ANPR: 21622863 Id Famiglia/Convivenza Comune: -
2 Errore Anpr Cod: EC033 - Codice consolato 2310604 incongruente con codice Stato estero 219 di residenza - Id Famiglia/Convivenza ANPR: 21622863 Id Famiglia/Convivenza Comune: -
3 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-26 11:02:39 , idOperazioneANPR 958918534 - Id Famiglia/Convivenza ANPR: 21622863 Id Famiglia/Convivenza Comune: -

Grazie

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare ad eseguire l'operazione per favore?

**Comment by cvignati** [comment]
Buongiorno,
Le operazioni sono andate a buon fine. Grazie

Chiedo, se possibile, conoscere quale sia stato il problema, per aggiornare anche la nostra Software House alla quale ho aperto segnalazione.

Sono anche a segnalare che l'operatore del numero verde 800863116 mi ha "liquidato" subito dicendomi di rivolgermi alla mia Software House in quanto non era un problema vostro.

Grazie

**Comment by ncapozzi** [comment]
Buonasera,
abbiamo avuto noi un problema nell'aggiornamento delle tabelle Consolati che ora è stato risolto come da lei stesso confermato.
Ci scusiamo per l'informazione non corretta ricevuta al numero verde.
