### ISSUE TITLE
Conferma indirizzo email NON funziona

### ISSUE THREAD

**Issue by nicolaMastronicola** [italia/anpr#3514]
Buongiorno,
ho provato ieri sera ad inserire l'indirizzo email nel profilo, mi è arrivata la mail con il link per confermarlo, ma non funziona.
Com'è possibile risolvere il problema, dato che non posso neanche provare a farmi reinviare un altro link?
Grazie in anticipo per l'eventuale riscontro.

**Comment by mttfranci** [comment]
Salve, potrebbe riprovare ora?

Saluti

Assistenza ANPR

**Comment by nicolaMastronicola** [comment]
Ora il link ha dato il messaggio di conferma, però ora non ho modo di verificare se sul profilo è stato aggiornato lo stato della mail. Se ci sono ancora problemi le scrivo domani. 
Grazie.
