### ISSUE TITLE
WA ISCRIZIONE PER ALTRI MOTIVI

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3515]
COMUNE DI PANTIGLIATE
Rif. Nadia Ferrari

Ho cercato di inserire un'scrizione per altri motivi, il cittadino che devo iscrivere ha solo cittadinanza TUNISINA, la WA mi dice
Stato estero cittadinanza 998 inesistente sulla tabella di riferimento (Codice: EC036)

Di seguito i riferimenti dell'operazione

Informazioni sull'operazione da fornire in caso di assistenza : data 2022-07-28 10:47:17 , idOperazioneANPR 961468081 (Codice: EN527)

Resto in attesa di gentile riscontro.

Saluti

**Comment by cvignati** [comment]
Il codice corretto della Tunisia è 460 e non 998

**Comment by GabriellaBallabio** [comment]
Scusi ma io dalla WA non posso digitare il codice , posso solo scegliere la cittadinanza dal menu a tendina proposta dalla stessa WA.
Resto in attesa di riscontro.
Grazie

**Comment by ncapozzi** [comment]
Buonasera
il messaggio di errore si riferisce alla cittadinanza del coniuge presente nei dati del matrimonio. Viene trasmesso 998 - NON ATTRIBUIBILE che per la cittadinanza non è ammesso, deve essere uno stato valido. Se non nota non trasmettete i dati della cittadinanza del coniuge.
