### ISSUE TITLE
EN122 su servizio 3002

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#3516]
Buongiorno
il comune di MORANSENGO (AT) sta cercando di iscrivere un cittadino presente in anpr, ma fallisce la ricerca dei componenti della famiglia (EN122)
Anche effettuando la ricerca dal portale ANPR viene trovata la persona, ma selezionando "elenco componenti" dalla scheda famiglia/convivenza, viene restituito l'errore EN122 La richiesta effettuata non produce alcun risultato.
Identificativo scheda ANPR: 77781721
Identificativo famiglia/convivenza ANPR: 43861619

**Comment by siscomanpr** [comment]
Buongiorno.
Il comune ci sollecita per una soluzione che permetta di procedere con l'iscrizione del cittadino.

**Comment by ncapozzi** [comment]
Buonasera
potete fornire per favore un recapito telefonico dell'utente interessato?

**Comment by siscomanpr** [comment]
Buonasera, le lascio il recapito telefonico dell'addetto del comune:
3336870747

**Comment by ncapozzi** [comment]
Buongiorno,
il comune che ha in carico la famiglia l'ha lasciata nello stato incompleta, per completare la famiglia deve fare una mutazione famiglia/convivenza 5001 con tipo mutazione = 3 DATI GENERALI FAMIGLIA CONVIVENZA.
