### ISSUE TITLE
Rimpatrio AIRE

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3518]
Buongiorno,
abbiamo fatto una pratica di rimpatrio AIRE da altro Comune. La persona ora è correttamente residente nel nostro Comune con il campo AIRE compilato con il NO ma rimane il dato "Anno Espatrio: 2006". Come si può eliminare?
Grazie
cordiali saluti
Katia Vacchi

**Comment by ncapozzi** [comment]
Buonasera
potete effettuare una mutazione tutti i dati 5008 con tipo = 1 Dati anagrafici e codice fiscale e togliere l'anno di espatrio se non lo volete mantenere. Se il CF del cittadino è assente ovvero è presente ma non validato e deve rimanere tale, nella gestione del CF impostate Iscrizione/modifica senza validazione
