### ISSUE TITLE
Problema cambio residenza comune di Roma

### ISSUE THREAD

**Issue by swapers** [italia/anpr#3519]
Salve, nell'area cambio residenza, quando bisogna inserire la nuova residenza, una volta selezionata la voce "Roma" dal menu' a tendina del campo "provincia di residenza" risulta poi mancare dal menu' a tendina del campo "comune di residenza" proprio il comune di Roma
<img width="582" alt="Schermata 2022-07-30 alle 16 31 31" src="https://user-images.githubusercontent.com/110295374/181919018-d4d64e9c-fe1d-48a4-a47d-665ff6898ce0.png">
.

**Comment by cmigliardi** [comment]
salve,  come evidenziato in home page: Richiesta cambio di residenza
Dal 27 aprile tutti i cittadini possono richiedere online il cambio di residenza o di dimora da un Comune all’altro in Italia o il rimpatrio dall’estero per i cittadini iscritti all’AIRE. Può essere richiesto anche il cambio di abitazione nell’ambito di un qualsiasi Comune. Per il Comune di Roma, in attesa del completamento degli interventi tecnici, il servizio di cambio di residenza on line è disponibile sul portale dello stesso Comune.
solo il comune di Roma  non ha ancora aderito.
