### ISSUE TITLE
[Subentro] File APR: Maternità e Paternità

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#352]
Buongiorno,
come già esposto per altri casi in cui alcuni campi sono obbligatori (ad es.: atti stato civile), in che modo sarebbe più corretto procedere quando (purtroppo nella maggior parte dei casi) i dati relativi al padre e alla madre mancano totalmente oppure ci sono solo il cognome ed il nome? In base alle specifiche, avere solo cognome/nome non è sufficiente (oltre che privo di significato), quindi bisognerebbe omettere?
Grazie

Eduardo Gira
Servizi Locali S.p.A.

**Comment by mttfranci** [comment]
Buongiorno, in riferimento alla vostra domanda, in fase di subentro gli unici dati obbligatori per l’elemento relativo ai genitori sono : 
-	Nome o  indicazione che il genitore è senza nome
-	Cognome o indicazione che il genitore è senza cognome
Pertanto se si è in possesso anche del solo nome e cognome relativamente al genitore è possibile inviare tale informazioni durante il subentro senza problemi.


Precisazione generale sui soggetti collegati inviati in fase di subentro.
Anche se non si tratta specificatamente della situazione descritta in questa issue, cogliamo l’occasione per fornire un chiarimento.
Durante il subentro possono essere inviati per ogni soggetto alcuni soggetti collegati, vale a dire padre, madre, coniuge, unito civilmente o convivente.
Qualora questi soggetti abbiamo a loro volta una scheda attiva nello stesso comune (quindi solo se attualmente residenti, non deceduti ecc), è preferibile che sia fornito l’identificativo comunale anche per tali soggetti sia quando vengono inviati come schede che quando ne viene passato il riferimento in altri soggetti.
