### ISSUE TITLE
File elenco cittadini a cui cambiare il Consolato in Manchester

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#3522]
Buongiorno,
ho ricevuto il file csv con l'elenco dei cittadini AIRE residente nel Regno Unito a cui modificare il Consolato in Manchester.
Io avevo già fatto ricerca utilizzazno il servizio disponibile su https://serviziconsolarionline.esteri.it ed inserito le città di residenza dei miei cittadini, facendo poi la variazione.
Io ho variato 4 cittadini, ma nel file csv ne ho 3.
Per il cittadino ID ANPR 38135949 ho effettuato la variazione, ma non ce l'ho in elenco.
Su https://serviziconsolarionline.esteri.it la città di SUNDERLAND me la propone come Consolato di Manchester e non Londra.
Come devo procedere? Devo rimodificare mettendo il Consolato di Londra?

Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
L’elenco trasmesso è basato sull’Elenco Unico al 31/12/2021. Il cittadino cui si fa riferimento si è trasferito nel Regno Unito successivamente. Abbiamo ricevuto conferma dal Ministero degli Esteri che il Consolato di riferimento corretto è quello di Manchester.
