### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

### ISSUE THREAD

**Issue by GinoGino80** [italia/anpr#3526]
Buonasera,
non riesco ad accedere al sito ANPR con spid; il sito mi restituisce questo errore:

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Ho già contattato il mio comune di residenza che mi ha detto che non ci sono anomalie nei miei dati e non sanno cosa fare.
Potete aiutarmi?

Grazie

**Comment by cmigliardi** [comment]
salve è possibile avere le prime 6 lettere del codice fiscale ? grazie

**Comment by GinoGino80** [comment]
MSSFNC

grazie

**Comment by cmigliardi** [comment]
le consiglio di rivolgersi al suo comune CIVITAVECCHIA per far  validare il codice fiscale  - lei ha 2 nomi con un trattino in mezzo. 
 si chiude la issue  -
