### ISSUE TITLE
Subentro - Esiti: incrocio informazioni comuni subentrati

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#353]
ambiente di pre-subentro - comune di Medicina (BO)

1. file dei subentrati (Subentrati_037037_SUBAPR_3_1_1.csv)
- per due famiglie APR, risultano tre righe identiche (perchè?)
Tipo   scheda | Prog. scheda ANPR | Prog. scheda Comune
Famiglia | 10406834 | 17270
Famiglia | 10406834 | 17270
Famiglia | 10406834 | 17270
Famiglia | 10406994 | 17279
Famiglia | 10406994 | 17279
Famiglia | 10406994 | 17279
- i due soggetti in esse residenti risultano correttamente una volta sola per ognuno
Tipo   scheda | Prog. scheda ANPR | Prog. scheda Comune
Scheda Individuale APR | 6071579 | 34601
Scheda Individuale APR | 6067888 | 34614

2. file dei soggetti con errore (037037SchedeIndivErr20171010.csv)
i due soggetti APR di cui sopra, presentano ognuno 3 anomalie identiche e diverse associazioni tra progressivo comune e progressivo ANPR
Prog.   ANPR soggetto | Progressivo APR/AIRE soggetto | Tipo Scheda | Codice | Descrizione
6071579 | 520593 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 10/02/2015 risulta inferiore alla data di   prima iscrizione 13/06/2017
6071579 | 520593 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 10/02/2015 risulta inferiore alla data di   prima iscrizione 13/06/2017
6071579 | 34601 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 10/02/2015 risulta inferiore alla data di   prima iscrizione 13/06/2017
6067888 | 672590 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 12/08/2011 risulta inferiore alla data di   prima iscrizione 21/06/2017
6067888 | 672590 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 12/08/2011 risulta inferiore alla data di   prima iscrizione 21/06/2017
6067888 | 34614 | Scheda Individuale APR | ES127 | La data di ingresso in famiglia 12/08/2011 risulta inferiore alla data di   prima iscrizione 21/06/2017

dagli approfondimenti effettuati, risulta che:
- i due soggetti sono subentrati in prima istanza con il comune di San Lazzaro di Savena BO (occasione in cui hanno acquisito il progressivo ANPR).
- oggi, emigrati da San Lazzaro di Savena BO, residenti a Medicina BO, vengono comunicati con il subentro di quest'ultimo
- ANPR mi comunica lo stesso id ANPR assegnato in precedenza (penso sia corretto...)
- nel file degli errori, trovo i due soggetti sia con l'idComune di Medicina (comune che subentra adesso)  sia con l'idComune di San Lazzaro di Savena (comune di precedente residenza)
- nel file degli errori, la segnalazione di "data di ingresso in famiglia" incoerente con la data di prima iscrizione, si rifà alla data di ingresso in famiglia che i soggetti avevano a San Lazzaro

avremmo bisogno di qualche delucidazione riguardo gli incroci di dati che sono stati effettuati, per potere dare indicazioni al cliente su come interpretare gli errori.

grazie
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
i due soggetti erano effettivamente subentrati in prima istanza con il comune di San Lazzaro di Savena BO. ANPR in questi casi  riassegna lo stesso id ANPR assegnato in precedenza. Per quel che riguarda gli elenchi c'era un bug (adesso risolto) associato al caso specifico.

Grazie
Angelo Mollicone

**Comment by AMonopoliADS** [comment]
il collegamento dei soggetti era l'unica cosa che mi spiegavo ragionevolmente.
per il bug trovato, invece, scaricando nuovamente il file non troveremo più l'anomalia, oppure bisogna attendere nuovo subentro?
grazie

**Comment by gcarbonin** [comment]
E' sufficiente ripetere lo scarico

**Comment by AMonopoliADS** [comment]
abbiamo eseguito nuovamente lo scarico dei file e sono state sistemate sia le dulipcazioni nel file "subentrati" sia le anomalie nel file degli "errori".

approfittando del caso specifico che si è verificato, approfitto per segnalare un'altra cosa:
abbiamo richiesto un certificato di residenza storico e, giustamente, viene documentata sia la residenza attuale a Medicina, sia quella precedente a San Lazzaro.

se, invece, tra un subentro e l'altro il soggetto avesse risieduto in un comune non subentrato, cosa verrebbe fuori, oggi, richiedendo il certificato di residenza storico?

grazie

**Comment by AMonopoliADS** [comment]
bene.
grazie

**Comment by bmalavolti** [comment]
Buongiorno
relativamente alla persona - identificativo ANPR 6050149 - abbiamo riprovato oggi ad emettere un certificato di residenza storico alla data  10.10.2017. 
Il soggetto residente a San Lazzaro  emigra a Trento (Comune non subentrato) e in data 11.10.2017  abbiamo fatto una immigrazione  a Faenza (comune subentrato). Nel certificato di residenza storico  non compare in nessun modo la residenza a Trento ma certifica la residenza a San Lazzaro - non veritiera. Ci aspettavamo che certificasse solo la residenza ultima a Faenza e non quella di San Lazzaro.
Per cui i certificati storici di persone che emigrano/immigrano da comuni subentrati a comuni non subentrati non vengono emessi correttamente.
grazie

**Comment by gcarbonin** [comment]
La residenza di Trento difficilmente potrebbe comparire in quanto il comune non è subentrato. In realtà alla data del 10.10.2017 (mi sembra che l'emigrazione a Trento sia avvenuta il 9.8.2017) dovrebbe rispondere che il soggetto non è presente in ANPR. Stiamo lavorando su questo certificato in quanto deve essere rivisto (vedi issue  #277  dove più propriamente doveva essere inserita questa richiesta) .
