### ISSUE TITLE
Elenco certificati da richiedere incompleto

### ISSUE THREAD

**Issue by kattydangelo** [italia/anpr#3530]
Buongiorno,
sono una cittadina residente nel comune di Roma.
Sul portale (https://www.anagrafenazionale.interno.it/) non riesco a richiedere alcuni certificati, ad esempio uno stato di famiglia, perché non appare tra i certificati disponibili.  Gli unici certificati che posso richiedere sono:
Anagrafico di nascita
Anagrafico di matrimonio
di Cittadinanza
di Esistenza in vita
di Residenza
di Stato civile
Siccome ho letto che i certificato disponibili sono circa 14, vorrei capire se si tratta di qualche settaggio dell'anagrafica. Sempre su internet ho letto che potrebbe essere dovuto ad un settaggio della mia anagrafica come "parzialmente certificabile". 
Accedo ai servizi tramite SPID. Il mio nome è Ana Katiuska D'Angelo.
Ho aperto anche una segnalazione al comune di Roma ma, al momento, non ho ricevuto risposta.
In attesa di un vostro gentile riscontro.
Ringrazio per la collaborazione
Katty D'Angelo

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 1972 si deve rivolgere al comune di Roma che ha competenza sulla  sua scheda  e sistemare la situazione dei rapporti di parentela all'interno del nucleo familiare-   altrimenti il certificato non può essere emesso. manca l'intestatario della famiglia.  si chiude la issue
