### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by marcosaof** [italia/anpr#3534]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore:

https://www.anagrafenazionale.interno.it/servizi-al-cittadino/

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.
[Torna alla homepage](https://www.anpr.interno.it/)

Cosa devo  fare?

Marcos Antonio Orlandini Fedato
codice fiscale rlnmc
Brasile

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 1987 - le consiglio di rivolgersi presso il suo comune di competenza - quello che lo ha iscritto all' AIRE, perché la sua scheda in Anpr non c'è.  - si chiude la issue  -
