### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by camilamps** [italia/anpr#3535]
Hi! 

My name is Camila Mariano Paganini, I was born in Brazil. 
My codice fiscale is MRNGRL______
Same error as in #2683  .

> Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica. 

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

In my Scheda Consolare  and comune it's all ok. 

What can I do? 

Thank you!

**Comment by cmigliardi** [comment]
se il suo nome è Camila Mariano Paganini, come ha scritto,  il codice fiscale MRNGRL  che trovo non è congruente con i dati - lo può controllare?  grazie - infatti con queste lettere non trovo schede  -

**Comment by cmigliardi** [comment]
non abbiamo ricevuto altre informazioni - si chiude la issue
