### ISSUE TITLE
Problema accesso ANPR

### ISSUE THREAD

**Issue by ohimaria** [italia/anpr#3537]
Buongiorno,
provo a fare accesso con SPID al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente, 
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

Premetto che il Comune di MANFREDONIA (FG) è presente in ANPR. Riesco ad accedere ad altri servizi come agenzia delle entrate, quindi non è un problema del codice fiscale associato. Potete aiutarmi fornendo codice fiscale ? Grazie mille

**Comment by cmigliardi** [comment]
salve,  è possibile avere le prime 6 lettere del suo codice fiscale?  occorre verificare in banca dati Anpr la situazione - grazie

**Comment by ohimaria** [comment]
PRRMRT
Grazie mille 🙏🏻

**Comment by ohimaria** [comment]
> salve, è possibile avere le prime 6 lettere del suo codice fiscale? occorre verificare in banca dati Anpr la situazione - grazie

PRRMRT

grazie mille 🙏🏻

**Comment by cmigliardi** [comment]
se è lei la signora maria rita - è bene che si rivolga al comune di manfredonia - perché il suo codice fiscale in Anpr non è validato . lei ha 2 nomi e in ag. entrate il nome è staccato mente in Anpr il comune lo ha scritto attaccato - quindi occorre verificare la situazione -

**Comment by cmigliardi** [comment]
si chiude la issue
