### ISSUE TITLE
Errore CAST Inserimento/Registrazione Nuovo Utente

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#3538]
Buongiorno, segnalo che in fase di inserimento nuovo operatore per Comune di MARSALA, (CF. PNCGFR58H21E974I), compare il messaggio in oggetto - UREGENTE
grazie
Tel.0923993382

**Comment by Leonforte** [comment]
Salve, l'anomalia dovrebbe essere stta risolta, potete riprovare ? grazie

**Comment by filippo1961** [comment]
grazie risolto
