### ISSUE TITLE
[Subentro] File APR: presenzaFamigliaCoabitante

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#354]
Buongiorno,
nelle specifiche fornite per [FamigliaConvivenza] c'è un flag "presenzaFamigliaCoabitante" (da valorizzare solo per le Famiglie). Potreste spiegarmi cosa si intende ? 
Dato che non è obbligatoria, se è una informazione di cui non si dispone, si può omettere? 
Grazie

**Comment by gcarbonin** [comment]
Si deve utilizzare soltanto quando due (o più famiglie) abitano fisicamente nello stesso posto. E' una informazione di interesse statistico ma presumibilmente anche all'ufficio tributi
