### ISSUE TITLE
certificazione aire soggetto cancellato

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#3541]
COMUNE DI VALDILANA

Per puro caso ho tentato il rilascio di un certificato di iscrizione aire di un cittadino cancellato dall'aire per morte accertata (soggetto 40365140 e nonostante da webapp risulti effettivamente cancellato la certificazione viene emessa con data odierna con tanto di indirizzo estero senza menzionare l'avvenuta cancellazione ed il relativo decesso.
Nel caso di certificazione da parte di altri comuni la cosa potrebbe risultare abbastanza grave.
Altri hanno riscontrato lo stesso problema?

**Comment by ncapozzi** [comment]
Buongiorno
il certificato è di residenza AIRE? Mi può dire per favore quando avete effettuato l'operazione?
Grazie

**Comment by RENZO63** [comment]
L'ho fatta il 22 agosto (ho copia del certificato in anteprima).
Ho provato adesso pero' e il problema si e' risolto.  Il certificato non viene emesso e viene indicata la cancellazione per decesso.
Saluti

**Comment by ncapozzi** [comment]
Buongiorno
avevamo già effettuato la correzione a seguito di una precedente segnalazione. Grazie del riscontro.
