### ISSUE TITLE
Problema accesso ANPR tramite SPID

### ISSUE THREAD

**Issue by AsiaStone2022** [italia/anpr#3543]
Buongiorno, 

Ho provato ad accedere per la prima volta al mio sportello personale, ma appare il messaggio "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Come si può risolvere il problema? Il mio comune risulta già essere presente nel database.

Grazie

**Comment by cmigliardi** [comment]
salve per verificare abbiamo necessità delle prime 6 lettere del suo codice fiscale. è possibile averle ? grazie in anticipo

**Comment by AsiaStone2022** [comment]
Salve,

Ecco le iniziali: GMZSYT

Grazie!

**Comment by cmigliardi** [comment]
se è lei la persona nata ad ottobre del 1992- risulta che lei ha 2 codici fiscali collegati  - quindi molto probabilmente SPID ha memorizzato quello secondario mentre adesso lei ha un altro principale  -

**Comment by cmigliardi** [comment]
si chiude la issue
