### ISSUE TITLE
Mutazione tutti i dati - Generalità - Bloccata

### ISSUE THREAD

**Issue by verbena-cesena** [italia/anpr#3544]
Buongiorno, 
nel variare i dati anagrafici del cittadino ID ANPR 210471654 , il sistema risponde il seguente errore:

EAM13 - Soggetto individuato in AT - in lavorazione per risoluzione omocodia - Codice fiscale NON variato

EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2022-08-24 08:18:07 , idOperazioneANPR 994329367

L'invio dell'operazione è stata provato in più giorni diversi, ma restituisce sempre errore.

PS
Abbiamo contattato già il numero verde di assistenza ANPR che ci ha risposto di segnalare su Github.

Cordiali Saluti
Verbena Cucchi 0547 - 356536 
Sirri Marco 0547 - 356252
Comune di Cesena - Anagrafe

**Comment by frmariani** [comment]
Come cita il controllo, il codice fiscale del cittadino è in lavorazione per risoluzione dell'omocodia presso la Direzione Centrale dell'Agenzia delle Entrate, pertanto i dati anagrafici, al momento, non possono essere modificati
