### ISSUE TITLE
Mutazione Residenza WS5005

### ISSUE THREAD

**Issue by GabriellaBallabio** [italia/anpr#3546]
COMUNE DI PANTIGLIATE
RIF.: Nadia Ferrari

Buongiorno
cercando di inviare ad ANPR una variazione di residenza compare l'errore EN531
Operazione non consentita : per il soggetto esiste un procedimento aperto dal Comune MILANO (MI) con numero pratica ANPR : 119116470

Informazioni sull'operazione da fornire in caso di assistenza :: data 2022-08-25 09:09:48 , idoperazioneANPR 995537365

Si resta in attesa digentile riscontro, per conoscere le modalità operative da intraprendere per poter iscrivere il soggetto nel nostro comune.

Saluti

**Comment by frmariani** [comment]
Dovete contattare il Comune di Milano indicando il numero del procedimento amministrativo che devono chiudere, altrimenti il cittadino non può essere trasferito

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
