### ISSUE TITLE
Controllo abilitazione IP

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3547]
Buongiorno, potreste verificare se l'ip 185.114.235.33 è correttamente censito per il comune di MONTEFALCIONE?

Risulta correttamente con * ma abbiamo dei problemi di collegamento.

grazie

**Comment by cmigliardi** [comment]
verifichiamo

**Comment by cmigliardi** [comment]
l’IP 185.114.235.33 ci risulta già correttamente abilitato
