### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio - Utente SML SCR XXXXX ZZZZZ

### ISSUE THREAD

**Issue by saospie** [italia/anpr#3548]
Nel accesso al portale tramite SPID, appare questo messaggio di errore:
![image](https://user-images.githubusercontent.com/112113663/186732479-1ed865b1-b3dc-4d48-ade2-0d0e696d2643.png)

In contatto con il Comune di Sant'Agata dei Goti (BN), non hanno riscontrato problemi con la scheda anagrafica. 

Cosa devo fare?

**Comment by cmigliardi** [comment]
cortesemente ci può inviare le prime 6 lettere del suo codice fiscale? grazie

**Comment by saospie** [comment]
Salve, eccole: SML SCR

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1981 - la sua scheda non è in ANPR . le consiglio di far verificare al comune la situazione in anagrafe nazionale  -

**Comment by cmigliardi** [comment]
si chiude la issue

**Comment by saospie** [comment]
Confermo '81, ritorno all'ufficio anagrafe comunale e ringrazio
