### ISSUE TITLE
secondo IP da censire

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3549]
Buongiorno, potreste aggiungere questo secondo IP 78.134.82.133 per il comune di PARRE?

Grazie mille

**Comment by Hdemografici** [comment]
il Comune è riuscito ad accedere al portale ed aggiungere l'indirizzo IP, potreste verificare se è tutto ok? 
perché hanno ancora problemi di collegamento con ANPR.

Grazie mille

**Comment by cmigliardi** [comment]
l' ip risulta già correttamente abilitato
