### ISSUE TITLE
Certificato in bollo senza diritti

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#355]
L'operazione <idOperazioneANPR>595649</idOperazioneANPR> è una prova in ambiente di test.
E' una richiesta di certificato in bollo con esenzione dei diritti di segreteria.
La descrizione dell'errore lascia intendere che i diritti siano obbligatori per i certificati in bollo, è corretta la mia interpretazione?
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Chiedo scusa ma devo precisare che non c'è un motivo di esenzione del bollo, nella richiesta ci sono questi due valori:
bollo = 1462; diritti = 0;
So di parecchi casi in cui la giunta comunale ha deciso di non riscuotere i diritti nella certificazione da portale, solo in quella da portale, ed è questo lo scopo della prova. Non ho sperimentato il significato del parametro citato nella WA ma suppongo che valga in ogni caso, sportello e internet.
Comunque le mie supposizioni contano poco, il fatto è questo: è possibile certificare da sportello con riscossione di diritti (ove previsto) e da portale senza (in ogni caso)?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Il parametro della WA consente di indicare l'importo del diritto riscosso da comune; il comune che ha deciso di non incassarli indicherà 0 e questo importo sarà accettato dal servizio di certificazione. Qualora subentrasse un comune che differenzia l'importo del diritto a seconda della modalità di richiesta (sportello o portale) si potrà intervenire sulla configurazione del parametro, differenziandolo, Al momento non ci sono casi di questo genere, nemmeno tra i comuni che eseguono i test in pre-subentro.

**Comment by slastrucci** [comment]
Buongiorno, sono l'analista informatico del Comune di Prato che seguirà il subentro in ANPR del mio comune. Vorrei informarvi che il nostro comune, in collaborazione con Maggioli, ha attivato ha attivato da diversi anni un servizio di certificazione on-line che sta riscuotendo un grosso successo con i cittadini (solo nel 2016 abbiamo prodotto on-line circa 22.500 certificati di varie tipologie). 
Capite bene che con questi numeri non possiamo permetterci di interrompere il servizio quando subentreremo in ANPR perchè, oltre a togliere un servizio ai cittadini, significherebbe avere 20.000 persone in più agli sportelli anagrafici.
E' necessario quindi che venga trovata una soluzione tecnica che ci permetta, per questo canale, di emettere certificati completamente gratuiti.
Attualmente stiamo gestendo i diritti nel seguente modo:
- per i certificati in carta libera il comune ha rinunciato completamente ai diritti di segreteria;
- per i certificati in bollo stampiamo sul certificato un riquadro dove il cittadino deve apporre una marcha da bollo "fisica" e viene scritta la dicitura "**Istanza in carta resa legale con apposizione di marca da bollo da 16,00 euro da parte del richiedente**"
Purtroppo mon è possibile effettuare il pagamento on-line ed assolvere al bollo in modo virtuale perchè in questo modo favoriremmo l'evasione fiscale nei casi in cui il cittadino ne stampasse più copie (ogni copia sarebbe legalmente valida ma il bollo sarebbe assolto una vola sola).
Tenete conto che i certificati in bollo sono circa il 10% di quelli emessi.
Non conoscendo bene i dettagli della configurazione di ANPR lascio che siano i tecnici di Maggioli ad indicare cosa servirebbe a livello tecnico per mantenere attivo il servizio.

**Comment by gcarbonin** [comment]
I diritti di segreteria sono dovuti per i certificati in bollo? se si anche se emessi on-line?

**Comment by slastrucci** [comment]
Per i certificati in bollo emessi allo sportello ci sono 0,52 € di diritti di segreteria.
Per quelli on-line non ci sono.

**Comment by gcarbonin** [comment]
Avvieremo l'intervento per gestire in modo differenziato i diritti.
La frase "Istanza in carta resa legale con apposizione di marca da bollo da 16,00 euro da parte del richiedente" deve essere inviata dal vostro Sw quando si richiede il certificato (nella riga annotazioni).

**Comment by Raffive** [comment]
gentili tutti,
abbiamo un problema.
abbiamo implementato la piattaforma on line del comune con le certificazioni on line da dicembre 2016
il sistema ora non produce il certificato da ANPR in quanto a detta dei tecnici sogei pretende i diritti di segreteria per l'emissione.
posto che la decisione di riscossione dei diritti (non del bollo) è TOTALMENTE a DISCREZIONE del comune che assume con regolare delibera di giunta se riscuotere il diritto, in che misura e modalità,
accertato che il comune di Spinea ha deliberato (del. 79 del 14/07/2016 e non chiedetemi copia la trovate sul sito del comune) di rinunciare ai diritti di segreteria per tutti i certificati rilasciati IN FORMA DIGITALE, chiedo a chi di competenza di allineare l'emissione dei certificati alla legittima decisione della giunta comunale.
mercoledì dobbiamo aprire il portale ai cittadini.

Raffaella 
COMUNE DI SPINEA

**Comment by gcarbonin** [comment]
Il comune  incassa i diritti di segreteria se il certificato è emesso allo sportello e NON li incassa se il certificato è emesso via Internet. Occorre:
a.	Accedere  alla WA e selezionare la funzione Amministrazione, disponibile in alto a destra sulla HOME PAGE. Nella funzione Gestione Dati del Comune, nei Parametri utilizzati per l'emissione dei certificati, si seleziona Certificati esenti da diritti di segreteria
 
b.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso allo sportello, è sufficiente indicare nella richiesta l’importo del diritto  di segreteria 
c.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso on-line dal portale del comune, nella richiesta non si indica l’importo

**Comment by Raffive** [comment]
grazie e su questo non ci sono ne dubbi ne problemi.
noi stiamo facendo un'altra cosa, ovvero un portale collegato al nostro SW che gestisce diversi servizi comunali come tributi ecc. al quale il cittadino può collegarsi e potrà fare un sacco di cose...
si collega ovviamente anche all'anagrafe che è ora in ANPR.
ed è qui che sembra nasca il problema....

**Comment by gcarbonin** [comment]
Per portale del comune intendo proprio un sistema del comune cui accede il cittadino per fare un sacco di cose tra le quali questo certificato, Da questo portale partirà una richiesta ad ANPR di emissione del certificato richiesto senza indicare l'importo del diritto di segreteria

**Comment by Raffive** [comment]
allora mi confermi che il problema è del SW e non di sogei, cioè sogei permette di fare certificati senza diritti  tramite web service che utilizza il gestionale?

**Comment by gcarbonin** [comment]
Si a condizione di impostare quel parametro nella WA

**Comment by Raffive** [comment]
è un parametro globale o un parametro che deve passare l'applicativo?

**Comment by gcarbonin** [comment]
E' un parametro globale che serve per accettare importo del diritto di segreteria = 0 anche per certificati non esenti

**Comment by gcarbonin** [comment]
Può fare una prova in ambiente di test

**Comment by Raffive** [comment]
Grazie ora contatto la ditta.

**Comment by Raffive** [comment]
![diritti](https://user-images.githubusercontent.com/32516983/33213947-0dcad07c-d12a-11e7-8519-dca78d286d4c.JPG)
attualmente la configurazione è la presente, e non va, devo forse spuntare l'esenzione per il corretto funzionamento?

**Comment by gcarbonin** [comment]
deve spuntare certificati esenti da diritti di segreteria

**Comment by Raffive** [comment]
ok se non va chiamo la ditta.
grazie

**Comment by gcarbonin** [comment]
Se fa la prova e va male, mi dia il numero dell'operazione o l'id della persona così vedo se c'è qualche problema
