### ISSUE TITLE
Non riesco ad accedere a ANPR

### ISSUE THREAD

**Issue by adamsallimo** [italia/anpr#3552]
Salve, ho provato ad accedere al portale con una carta CNS ma mi da un errore
![Immagine 2022-08-27 152407](https://user-images.githubusercontent.com/72262555/187034483-e5da6142-dbf7-4906-89a7-5a9d7ebf5357.png)
ho provato anche a usare la stessa carta in siti diversi (ad esempio INPS oppure Bandi Regione Lombardia) ma non mi dava nessun errore 
il mio codice fiscale è: LRELDT80B42Z100R 
Grazie

**Comment by cmigliardi** [comment]
se è lei la persona nata nel 1980 - la sua scheda in Anpr non risulta. le consiglio di rivolgersi al suo comune di competenza  OGGIONO -  la issue si chiude
