### ISSUE TITLE
Servizio P002 e Internal server error

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3553]
Ambiente di produzione, comune di Brescia.

Tentando di scaricare i dettagli di una richiesta di cambio residenza il servizio in oggetto per alcune richieste ritorna un errore di tipo "Internal server error".
Se andiamo da webapp a consultare la richiesta ci compare una pagina vuota (vedi ad esempio la richiesta codice 27607402).

Qual è il problema ? Potete risolvere ? 

Grazie

**Comment by cmigliardi** [comment]
salve abbiamo verificato . per favore potete riprovare  da webapp e da servizio e mi fate sapere ? grazie in anticipo

**Comment by cmigliardi** [comment]
provate la pratica   27607402

**Comment by cmigliardi** [comment]
potete darci un riscontro?

**Comment by busaster** [comment]
Al momento l'operatore comunale deputato alla lavorazione è assente, non appena riusciamo a fare la prova vi avviseremo tempestivamente. Grazie

**Comment by mttfranci** [comment]
@busaster  ci potete dare un riscontro dell'invocazione del servizio (P003) per la richiesta 27607402 ? o vi serve comunque l'operatore comunale?
Grazie in anticipo.

**Comment by busaster** [comment]
Siamo appena riusciti a verificare che le chiamate terminano con successo, sia WS che WebApp. 
Lo stesso problema era già capitato in passato (su altri clienti), possiamo dire che con il vostro intervento il problema sia risolto in via generale ?
Grazie

**Comment by cmigliardi** [comment]
sì  eccetto i casi particolari -  - chiudo la issue
