### ISSUE TITLE
EN148	Errore in inserimento residenza famiglia

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3554]
COMUNE DI MARANO DI NAPOLI - PRODUZIONE

Buongiorno.
Per il soggetto con id ANPR 110814239  ed id famiglia ANPR 65650773 si cerca di aggiornare la data decorrenza residenza con operazione di rettifica dati subentro, ma si riceve l'errore in oggetto.

EN527	Informazioni sull'operazione da fornire in caso di assistenza : data 2022-08-29 09:48:56 , idOperazioneANPR 1000280520

Si richiede l'aggiornamento della data decorrenza residenza in  03.09.1996.

Si ringrazia per la cortese sollecitudine in quanto la posizione andrebbe poi movimentata con ulteriori operazioni.
G. Trisolini

**Comment by frmariani** [comment]
Avete già effettuato la rettifica della data di decorrenza della residenza il giorno 26/08/2022; quell'operazione non è annullabile, pertanto la data di decorrenza della residenza non può più essere modificata

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
Per l'operazione del 26.08.2002  si è trattato di un errore materiale.

Potreste rettificare voi la data in 03.09.1996?
A supporto della richiesta preferite una Pec da parte del comune,  a che indirizzo?

Potrei essere contattato per chiarimenti allo 051-278958?

Grazie

**Comment by CIVILIANEXT001** [comment]
Buongiorno.
Da una prova eseguita in ambiente di TEST COMUNI (CODICE 015125) pare essere possibile rettificare più volte la data di decorrenza residenza.
Riporto gli id Operazione ANPR:
53432650 - 53432847

Si ringrazia per la collaborazione.
G. Trisolini

**Comment by frmariani** [comment]
Noi non possiamo in alcun modo modificare i dati così come pervenuti dalle operazioni dei comuni;
effettuerò delle verifiche sulla natura del problema

**Comment by frmariani** [comment]
per favore riprovi l'operazione di rettifica e mi faccia sapere
