### ISSUE TITLE
ISCRIZIONE PER NASCITA - ERRORE AT

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3555]
COMUNE CASERTA
Non riusciamo ad inviare iscrizioni per nascita 1001. Non si collega ad AT
ANCHE DA WEBAPP NONRIUSCIAMO A INTERROGARE AT

**Comment by mttfranci** [comment]
Salve, avete ancora il problema?

**Comment by rinonasti** [comment]
Buongiorno,
Ho fatto fare delle prove ai vari operatori. Mi dicono OK
Grazie

**Comment by mttfranci** [comment]
Perfetto. grazie del riscontro.
