### ISSUE TITLE
Impossibile completare cambio di residenza

### ISSUE THREAD

**Issue by Mark-olino** [italia/anpr#3556]
Seguendo la procedura per il cambio di residenza si arriva al punto in cui inviare i dati.
La procedura avverte che non è possibile inviare perchè non esiste una email associata al profilo.
La sezione dedicata all'inserimento della mail non funziona. Ho provato inserendo almeno 3 indirizzi email ma su nessuno di essi ho ricevuto la mail con la richiesta di validazione. Non disponendo della email associata al mio profilo, la richiesta on-line della variazione di residenza risulta del tutto inutile.
Ho anche provato ad associare l'indirizzo email direttamente dalla sezione di modifica del profilo, stesso risultato : il nulla.
Spero qualcuno si prenda carico del problema e risolva.
Grazie

**Comment by mttfranci** [comment]
Salve, il servizio di email non è pensato per essere sincrono, forse oggi c'è stato qualche ritardo.
Potete verificare ancora se la mail di conferma contatto è arrivata ed eventualmente darci un riscontro?
(Anche se può sembrare banale si ricorda di controllare anche nella posta indesiderata).
Se domattina non fosse ancora arrivata sarà necessario chiedere qualche informazioni in più per completare l'indagine.
Saluti
Assistenza ANPR

**Comment by Mark-olino** [comment]
Buongiorno.
Ieri sera alle 20 circa sono arrivate tutte le email dei vari tentativi fatti e con il link di una di queste ho potuto confermare la registrazione.
Solo come consiglio, da veterano consulente informatico, cercate di far in modo che la mail di verifica arrivi entro pochi minuti, altrimenti gli utenti penseranno che la procedura non funziona.
Se la vostra infrastruttura non consente l'invio rapido, quantomeno scrivetelo : basta un messaggio che dica che la mail potrebbe impiegare anche 24 ore e tutto apparirà più chiaro.
Grazie della collaborazione e buon lavoro

**Comment by mttfranci** [comment]
Grazie del suggerimento.
In generale le mail arrivano quasi istantaneamente, saltuariamente qualsiasi ifrastruttura di posta può avere una latenza, perchè i livello di servizio sui tempi non sono una caratteristica del protocollo SMTP.
Saluti

Assistenza ANPR
