### ISSUE TITLE
Impossibile completare richiesta nuova residenza

### ISSUE THREAD

**Issue by AndreaCheppa** [italia/anpr#3557]
Buonasera,

non riesco a completare la richiesta di nuova residenza, in quanto il sito mi chiede di validare l'indirizzo e-mail, ma non mi arriva nessun link per la convalida.
Come ho notato, non sono l'unico ad avere problemi di questo tipo.
Attendo risposte,

Grazie

**Comment by mttfranci** [comment]
Salve, il servizio di email non è pensato per essere sincrono, forse oggi c'è stato qualche ritardo.
Potete verificare ancora se la mail di conferma contatto è arrivata ed eventualmente darci un riscontro?
(Anche se può sembrare banale si ricorda di controllare anche nella posta indesiderata).
Se domattina non fosse ancora arrivata sarà necessario chiedere qualche informazioni in più per completare l'indagine.
Saluti
Assistenza ANPR

**Comment by kurtkokoko** [comment]
Buonasera, anch'io ho lo stesso problema, controllato anche nella spam ma non è arrivato niente... @AndreaCheppa tu hai risolto?

**Comment by dellacal** [comment]
19/04/23 stesso problema da ieri...qualcuno ha risolto?

**Comment by alessiaser** [comment]
19/4/23 io sto provando da ieri sera ma non posso inviare procedura di cambio residenza poiché non mi arriva la mail di conferma per validare l’indirizzo email… il che è assurdo vada fatto visto che sono entrata con spid e dovrebbe essere già verificato. Tra l’altro Ho urgenza di inviare la pratica!!

**Comment by alessiaser** [comment]
> Buonasera,
> 
> non riesco a completare la richiesta di nuova residenza, in quanto il sito mi chiede di validare l'indirizzo e-mail, ma non mi arriva nessun link per la convalida. Come ho notato, non sono l'unico ad avere problemi di questo tipo. Attendo risposte,
> 
> Grazie

Ciao Andrea,
In quanto tempo si è sbloccata la situazione quando hai avuto questo problema ?

**Comment by mttfranci** [comment]
Salve ora la problematica dovrebbe essere risolta, avete ricevuto la mail di conferma adesso?
Saluti

Assistenza ANPR

**Comment by Daviama95** [comment]
Si, a cosa era dovuto l’errore ?

Il giorno mer 19 apr 2023 alle 17:58 Matteo ***@***.***> ha
scritto:

**Comment by antov97** [comment]
anche io con lo stesso problema... qualcuno ha risolto?

**Comment by silvi80** [comment]
Buonasera,

non riesco a completare la richiesta di nuova residenza, in quanto il sito mi chiede di validare l'indirizzo e-mail, ma non mi arriva nessun link per la convalida. Come ho notato, non sono l'unica ad avere problemi di questo tipo. Attendo risposte,

**Comment by Daviama95** [comment]
Buongiorno,
Ho avuto questo problema, due anni fa, al momento non ricordo come avevo
risolto se mi viene in mente glielo dico
Saluti
Davide


Il giorno lun 10 mar 2025 alle 12:13 silvi80 ***@***.***> ha
scritto:

**Comment by gppbarone** [comment]
Buongiorno, utilizzi il canale di assistenza a lei dedicato sul portale dei Servizi demografici.
https://www.anagrafenazionale.interno.it/

Saluti
Assistenza ANPR
