### ISSUE TITLE
AEE95	Operazione non effettuabile

### ISSUE THREAD

**Issue by CIVILIANEXT001** [italia/anpr#3559]
COMUNE DI FROSINONE - PRODUZIONE

Buongiorno.
L'operazione di Mutazione tutti dati sul soggetto con id ANPR 19982395  genera l'errore in oggetto.

EN527  Informazioni sull'operazione da fornire in caso di assistenza : data 2022-08-30 08:39:08 , idOperazioneANPR 1001327845

Si cerca di variare il cognome ed il codice fiscale che è già stato rilasciato da Agenzai Entrate.
Da consultazione AE in WA esiste sia il CF vecchio (MARCATO ANPR - VALIDATO AE)  che il CF nuovo (NON MARCATO ANPR)

Lo stesso errore si riceve utilizzando la risoluzione disallineamenti con AE della WA

Si ringrazia restando  in attesa di un riscontro.
G. Trisolini

**Comment by ncapozzi** [comment]
Buongiorno,
il CF presente in ANPR è quello che vorreste inserire sono stati attribuiti da Agenzia Entrate come risoluzione di un caso di omocodia (due persone distinte con gli stessi dati anagrafici). Se si tratta della stessa persona dovete scrivere a  entrate.archivioanagrafico@agenziaentrate.it  allegando tutta la documentazione necessaria.  
Una volta ricevuta  risposta, per allineare ANPR potete richiedere assistenza al numero verde dedicato 800863116.
