### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by mohammedad** [italia/anpr#3562]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

ANPR-Erro

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.
In contatto con il Comune di Mira (VE), non hanno riscontrato problemi con la scheda anagrafica. Anche la softhouse non ha riscontrato alcun problema.

Cosa devo fare? Il comune ha detto che non sa come aiutarmi.

**### **il mio Codice fiscale : LJZMMM90****

**Comment by mohammedad** [comment]
> come le ho già scritto nella issue 3560 con anno di nascita 90 trovo una persona residente a roma - può darmi maggiori informazioni? mese di nascita ? e giorno? grazie

nome : mohammed adnan yousif
cognome: aljazaeri
nascita : 08/10/1990
nazione: iraq

**Comment by cmigliardi** [comment]
mi spiace ma con i dati anagrafici la sua scheda non esiste in Anpr -  mi può dare il suo codice fiscale?  grazie

**Comment by cmigliardi** [comment]
per data - ottengo sempre una scheda  con questi dati 
AL-JAZAERI  cognome
MOHAMMED ADNAN YOUSIF   nome
ma lei deve rivolgersi al suo comune perché  in ANPR  il comune l'ha iscritta come residente

**Comment by cmigliardi** [comment]
si chiude la issue
