### ISSUE TITLE
Mancata iscrizione scheda anagrafica per doppio nome con virgola su ANPR

### ISSUE THREAD

**Issue by rms64** [italia/anpr#3563]
Buonasera, 
non riesco ad accedere al sito ANPR perché esce il messaggio di anomalia dei dati, mi sono recata al comune e mi è stato detto che non è possibile inserirmi nel sistema perché al mio primo nome segue un secondo nome separato dalla virgola, e il sito dell'ANPR non accetta la virgola.
Aggiungo che all'agenzia dell'entrate e sullo SPID risulta solo il primo nome.
Il mio codice fiscale è SMNMGH64

Come bisogna fare per procedere all'inserimento dei miei dati?

Ringraziando per la disponibilità porgo cordiali saluti.

**Comment by cmigliardi** [comment]
buongiorno, 
in ANPR il suo nome è correttamente riportato con la virgola  (Nome: MARGHERITA,CATERINA ) quindi non è vero che Anpr non accetta questa situazioni. Il problema è che il suo codice fiscale non è validato rispetto al dato in ag. entrate dove invece è stato riportato un solo nome SMNMGH64B65F839I -  quindi, come previsto dalla norma,  il comune  FRASSO TELESINO deve agire per risolvere tale situazione.  si chiude la issue
