### ISSUE TITLE
ERRORE VALIDAZIONE ANPR SU EMISSIONE CIE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3564]
Comune Caserta
In fase di emissione di CIE per cittadino id ANPR 326655669 viene evidenziato l'errore in allegato. Come risolvere.Grazie
![PHOTO-2022-09-01-14-21-06](https://user-images.githubusercontent.com/54957840/187913873-b36c43d5-131e-4334-86e0-67ca7680699d.jpg)

**Comment by cmigliardi** [comment]
buongiorno 
questo cittadino  ha il codice fiscale emesso da ag. entrate ma nella scheda non è presente il nome in quanto non dichiarato - quindi le consiglio di sentire  l'assistenza di CIE  o scrivere a   cie.comuni@interno.it  -     in Anpr ed in ag. entrate la scheda c'è

**Comment by cmigliardi** [comment]
lato Anpr non ci sono motivi ostativi perché il codice fiscale è comunque  validato e marcato  - dipende dal sw CIE

**Comment by cmigliardi** [comment]
si chiude la issue
