### ISSUE TITLE
Annullo Revoca Dato

### ISSUE THREAD

**Issue by averrando** [italia/anpr#3566]
Buongiorno

Il Comune di Santa Margherita Ligure ha registrato erroneamente una revoca dato  per il soggetto MGGLCU66E05C800K
Come è possibile annullarla?
Avremo necessità di annullarla per poter annullare tutte le altre variazioni precedenti registrate anch'esse erroneamente

La revoca dato ha id operazione ANPR 938884147
Grazie

Andrea Verrando - C&C Sistemi

**Comment by frmariani** [comment]
Mi dispiace ma la revoca dato non è un'operazione annullabile.
Sul cittadino sono state effettuate circa 10 operazioni, potete chiarire il motivo per cui avete necessità di annullarle tutte ?

**Comment by averrando** [comment]
E' necessario annullare tutte le operazioni per poter  permettere al gestionale di ripristinare i dati del cittadino con decorrenza precedente alle operazioni registrate in seguito ad un rigetto di emigrazione in altro comune.

**Comment by frmariani** [comment]
la situazione non è chiara; il rigetto dell'emigrazione è già stato registrato, quindi il cittadino è tornato correttamente residente nel vostro comune.
Credo che sia necessario un contatto telefonico; mi scriva un recapito 
frmariani@sogei.it

**Comment by frmariani** [comment]
la issue viene chiusa in quanto risolta per le vie brevi
