### ISSUE TITLE
OPERAZIONE APERTA SU ANPR

### ISSUE THREAD

**Issue by anagrafe** [italia/anpr#3569]
Buongiorno. Una mia residente si è trasferita in altro Comune. Questo Comune mi dice che non riesce ad inserire la pratica di cambio residenza in quanto risulta un'operazione aperta nel mio Comune. A me risulta tutto chiuso.
Come posso verificare di che operazione si tratta e come posso chiuderla?
Fabio Borgogno, Ufficiale d'anagrafe delegato del Comune di Trinità (CN), contatto 3384945232

**Comment by frmariani** [comment]
non riesco a raggiungerla al numero segnalato; per favore mi indichi almeno l'idanpr  della cittadina

**Comment by anagrafe** [comment]
Buongiorno.

Le chiedo infinitamente scusa, ma purtroppo in questi giorni le reti mobili nel nostro Comune non funzionano. Inoltre abbiamo anche problemi con la rete fissa.

Le lascio tutti i numeri, anche quello privato, a cui può provare a contattarmi in qualsiasi momento:

*	Numero fisso ufficio anagrafe (lun-mer-ven 9-12): 017266131 interno 2;
*	Numero fisso ufficio tributi (mar-gio 9-12): 017266131 interno 5;
*	Numero mobile di servizio: 3384945232;
*	Numero mobile privato: 3389572024.

L’ID ANPR del soggetto che dà problemi è 120157305.

L’ID del convivente è 68314226.

Credo di essere riuscito a chiudere il procedimento aperto, ma il Comune di nuova iscrizione non mi ha dato ulteriori feedback.

Grazie per la collaborazione.

 

Ph.D. Ing. Fabio Borgogno

Servizi Demografici - Ufficio Tributi

Transizione Digitale - Ufficio Tecnico

Comune di Trinità

Tel. 0172/66131

Mail:  ***@***.***> ***@***.***

            ***@***.***> ***@***.***

 

Da: frmariani ***@***.***> 
Inviato: martedì 13 settembre 2022 11:06
A: italia/anpr ***@***.***>
Cc: anagrafe ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] OPERAZIONE APERTA SU ANPR (Issue #3569)

 

non riesco a raggiungerla al numero segnalato; per favore mi indichi almeno l'idanpr della cittadina

**Comment by frmariani** [comment]
certamente il procedimento aperto avrebbe impedito il cambio di residenza.
direi di attendere il feedback del comune di emigrazione

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
