### ISSUE TITLE
[web-app] Consultazione / Certificazione: navigazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#357]
salve.

non so se sia voluto, o se dipenda dal browser utilizzato, ma ci sono questi due aspetti che - a mio parere personale... - rendono ostico l'uso della web-app.

nel caso specifico sto utilizzando Chrome, e succede questo:

1. 
- in "Consultazione": indico i parametri di ricerca del soggetto, premo "invio"... e parte la ricerca
- in "Certificazione": indico i parametri di ricerca del soggetto, premo "invio"... e non succede niente e devo andare a cercare il bottone "Cerca" ed usare quello

2.
- in "Consultazione", indicando gli elementi della data (di nascita o di riferimento della ricerca), per passare da un campo all'altro devo usare il "tab" o il mouse
- in "Certificazione", indicando il giorno passa automaticamente al mese e poi automaticamente all'anno (questo succede solo sulla data di nascita e se - ad esempio... - sbaglio il mese e voglio tornare indietro con shift+tab, rimane sull'anno e posso spostarmi solo utilizzando il mouse. la data di riferimento del certificato, invece, si comporta come in "Consultazione")

mi aspetterei un comportamento uniforme tra le due funzioni e - sempre parere personale... - propenderei per le modalità della "Consultazione" per entrambi i punti.

probabilmente chi usa la web-app tutti i giorni ormai è entrato nei vari meccanismi.
chi lavora tramite web-service ed usa la web-app saltuariamente perde più tempo in questi passaggi

grazie.

Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
faremo qualche prova e interverremo ove necessario allineando le due funzioni, Il passaggio automatico da uno dei campi data al successivo era stata una richiesta esplicita sulla certificazione

**Comment by AMonopoliADS** [comment]
ok. grazie

**Comment by AMonopoliADS** [comment]
aggiungo un'altra cosa che avevo in nota e che mi sono dimentincato di scrivere prima.
sempre in ambito "Certificazione", una volta riprodotto il certificato che mi serve (nel caso specifico l'ho richiesto in anteprima), utilizzo il bottone "altro certificato", aspettandomi di potere rilasciare un altro certificato per la stessa persona, invece la scelta dei certificati non è modificabile.
in più, pur avendo, mantenuto la schelta di esenzione dei diritti, il valore dei diritti di segreteria viene ri-inizializzato a 0,52, quindi scatta l'inpcompatibilità tra la scelta di esenzione ed il valore del diritto.

grazie.

**Comment by cmigliardi** [comment]
"Certificazione", una volta riprodotto il certificato  in anteprima (che contiene la scritta "anteprima" in diagonale)  è possibile utilizzare il bottone "altro certificato".  Il sw riporta il controllo nella sezione "scelta certificato" - occorre togliere il check sul certificato richiesto precedentemente e selezionarne uno  o più laddove è possibile chiedere più certificati contemporaneamente.  il valore diritti di segreteria (come gli altri valori)  restano invariati.   ho ripetuto il test anche in ambiente di Pre-Subentro (dove immagino abbia eseguito il test) se non è così dammi il caso specifico che lo controlliamo insieme - grazie Cecilia

**Comment by cmigliardi** [comment]
aggiungo per completezza che nell'area Amministrazione è possibile indicare dei valori  di default  per i certificati:  
# Parametri utilizzati per l'emissione dei certificati

Importo del diritto di segreteria:    xx,xx   Euro

Certificati esenti dai diritti di segreteria:  check  

Modalità prevalente di riscossione dell'imposta di bollo*:

questi parametri vengono ripresi dal sw ogni volta che si chiede un Nuovo  Certificato.  per tal motivo  nel tuo ambiente si visualizza il valore 0,52   (valore settato in amministrazione)

**Comment by AMonopoliADS** [comment]
ok. grazie Cecilia del riscontro.
la cosa che mi sembra poco coerente è che, avendo l'opportunità di richiedere "altro certificato" alle stesse condizioni del precedente, mi mantenga la scelta "esenzione diritti = 'SI'", ma mi valorizzi ugualmente il valore della segreteria (che appena prima era stato azzerato per la scelta di cui sopra).
mi aspetterei di trovare i diritti a 0,00 per il fatto che la scelta dell'esenzione diritti è rimasta 'SI',
valutate comunque questa richiesta anche insieme a chi utilizza maggiormente il servizio di certificazione tramite la web-app.
grazie

**Comment by cmigliardi** [comment]
come abbiamo visto in collegamento:
•in "Consultazione": se indichi i parametri di ricerca del soggetto e premi INVIO questo corrisponde al click sul pulsante CONFERMA e parte la ricerca (questo accade perché i parametri di ricerca sono contenuti in una stessa pagina)
•in "Certificazione", ma in tutti i casi in cui  è possibile cercare il soggetto attraverso diverse tipologie di parametri (es.  Ricerca la persona  - Ricerca per identificativo della persona - Ricerca la famiglia o la convivenza) in ogni sezione c'è un apposito pulsante CERCA relativo a quella sezione.  ecco perché occorre cliccare sul CERCA  corrispondente e facendo semplicemente INVIO non viene avviata la ricerca.    per quanto riguarda: data di nascita e data di riferimento (in consultazione)  dobbiamo allineare la modalità di riempimento dei tre campi (gg-mm-aaaa) come tutte le altre date presenti nel sito web di Anpr.  (Il passaggio automatico da uno dei campi data al successivo era stata una richiesta esplicita).

**Comment by cmigliardi** [comment]
(in consultazione) è  stata allineata  la modalità di riempimento dei tre campi (gg-mm-aaaa)
