### ISSUE TITLE
Accesso WEB APP TEST

### ISSUE THREAD

**Issue by LSPAG** [italia/anpr#3573]
Buongiorno,
Non riusciamo ad accedere alla WEB APP TEST del comune codice istat 040007, con il certificato 040007-CO-0001, invece con il certificato 015025-CO-0001 accediamo regolarmente.

L'errore è:
Si è verificato un errore durante la fase di autenticazione.

Potreste verificare?
Saluti Laboratorio Dedagroup

**Comment by Leonforte** [comment]
L'anomalia è stata risolta, potete cortesemente riprovare ? grazie

**Comment by LSPAG** [comment]
Adesso funziona.
Grazie
