### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by pp0404** [italia/anpr#3575]
Sig,

Non fa un normale acesso al portale, ora appare questo mensaggio di errore:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

In Fast It non hanno riscintrato problemi con la scheda anagrafica. 

Cosa devo fare??

grazie

**Comment by pp0404** [comment]
prime 6 lettere del CF: NRNPDR

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 2001 - è bene che si rivolga al comune che l'ha iscritta Aire perché in ANPR  non c'è la sua scheda -

**Comment by cmigliardi** [comment]
si chiude la issue
