### ISSUE TITLE
Errore ANPR -  Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Danielbka** [italia/anpr#3576]
Buona Notte!
Sto cercando di accedere ad ANPR, ma viene visualizzato questo messaggio di errore:
"Purtroppo non è stato possibile accedere al servizio, si frequenta di rivolgerti al tuo comune di (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la sua scheda anagrafica." Come procedere?
Iniziali del mio CF: DBRDNL

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 1999 deve rivolgersi al comune di Borgo Valbelluna che l'ha iscritta Aire e chiedere  di validare il suo codice fiscale nella scheda presente in ANPR   - si chiude la issue
