### ISSUE TITLE
Impossibile ottenere certificato sia immediato che via mail

### ISSUE THREAD

**Issue by billyve69** [italia/anpr#3578]
Risulta impossibile ottenere il certificato sia via mail che tramite il download immediato:
Selezionato il certificato, selezionato il Tipo e selezionata la modalità, ottengo l'anteprima ma tapando il pulsante "ottieni" il certificato, ottengo solamente il risultato di essere riportato alla compilazione del form con tutti i valori ripristinati ma senza aver ricevuto il download del file e nemmeno l'invio della mail.

**Comment by apaolacci** [comment]
Salve,
per analizzare la segnalazione sarebbe opportuno conoscere il dispositivo, il sistema operativo, il browser utilizzato per l'emissione e il download del certificato, può cortesemente indicarceli?

Può verificare se entrando nella funzionalità 'Certificati', in fondo alla pagina è presente la tabella 'Certificati Richiesti' contenente il certificato che ha richiesto in precedenza?

Saluti,
Assistenza ANPR

**Comment by billyve69** [comment]
Il problema si è risolto in parte, ovvero è stato possibile effettuare il download del certificato; non è stato possibile ottenerlo via mail. Sistema operativo Windows 10, browser Chrome ed edge entrambi aggiornati all'ultima release rilasciata.
Altro elemento di perplessità; la scelta per l'ottenimento del certificato, download o via mail, non è mutualmente esclusiva.Siamo certi che se si mettono le due spunte l'applicazione permetta entrambe le metodologie di ricezione del certificato oppure il download esclude automaticamente l'invio via mail?
Grazie

**Comment by apaolacci** [comment]
Salve,
ok quindi si è risolto. 
Può scegliere di effettuare il download del certificato e contestualmente l'invio del certificato sulla sua email. 

L'email deve essere inserita e convalidata precedentemente all'emissione del certificato nella sezione dedicata del "Profilo Utente". In questo caso sarà possibile abilitare la spunta ed utilizzare entrambe le metodologie di ricezione di un certificato in fase di emissione.

Saluti,
Assistenza ANPR

**Comment by billyve69** [comment]
Risolta parzialmente.
Download riuscito.

Mail mai pervenute.

Marco B

Il Mer 21 Set 2022, 16:05 apaolacci ***@***.***> ha scritto:

**Comment by apaolacci** [comment]
Salve,
ha inserito e validato la sua mail nel Profilo Utente? La spunta all'invio avviene solo se è stato lasciato un recapito email nell'area autenticata del cittadino.

Saluti,
Assistenza ANPR

**Comment by billyve69** [comment]
Si si mail autenticata.
comunque si è risolto anche questo perché le mail sono arrivate, dopo due
giorni, ma sono arrivate.
Probabilmente problemi di server.

Grazie
Marco B
Questo messaggio (e tutti i file associati) può contenere informazioni
riservate e/o privilegiate. Se non sei il destinatario previsto o
autorizzato a riceverlo per il destinatario previsto, non devi utilizzare,
copiare, divulgare o intraprendere alcuna azione in base a questo messaggio
o alle informazioni qui contenute. Se hai ricevuto questo messaggio per
errore, avvisa immediatamente il mittente inviando una email di risposta ed
elimina questo messaggio. Grazie per la collaborazione.

This message (and any associated files) may contain confidential and/or
privileged information. If you are not the intended recipient or authorized
to receive this for the intended recipient, you must not use, copy,
disclose or take any action based on this message or any information
herein. If you have received this message in error, please advise the
sender immediately by sending a reply email and delete this message. Thank
you for your cooperation.


Il giorno gio 22 set 2022 alle ore 10:28 apaolacci ***@***.***>
ha scritto:
