### ISSUE TITLE
Presubentro - Comune di Gorgonzola

### ISSUE THREAD

**Issue by busaster** [italia/anpr#358]
Questa mattina abbiamo fatto presubentrare il comune in oggetto.
Durante il controllo delle anomalie sono emersi alcuni soggetti nel file "CFDiversoAssenteDatiDiversiCollegatiOmocodice" con anomalia EA003 ("Soggetti con dati anagrafici validati e CF diverso da AE").
Verificando i soggetti da webapp abbiamo visto che il CF in ANPR è giustamente quello ricavato da AT.
Risultano però come NON VALIDATI, mentre ce li saremmo aspettati VALIDATI.
Come mai ?

**Comment by gcarbonin** [comment]
Ora verifichiamo

**Comment by gcarbonin** [comment]
In test-comuni e pre-subentro la procedura di validazione iniziale utilizza la base dati di produzione dell'agenzia delle entrate, ma i WS colloquiano per evidenti motivi con quella di test. Per tale motivo le persone sono caricate tutte come non validate: in caso contrario qualsiasi operazione con i WS andrebbe male per le verifiche AE. In produzione queste persone sono caricate come validate.
