### ISSUE TITLE
Ripristino anagrafico in famiglia emigrata

### ISSUE THREAD

**Issue by marcoLave** [italia/anpr#3580]
Buongiorno,
in data odierna ci è arrivata una notifica di un ripristino anagrafico (procedimento da annullare ID: 959169346).
Procedendo all'annullamento avviene il seguente errore:
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa; Informazioni sull'operazione da fornire in caso di assistenza : data 2022-09-21 12:45:01 , idOperazioneANPR 1029038797; 

La persona andrebbe ripristinata in una famiglia che però è emigrata in un altro comune. Quindi non ci è possibile annullarla per ripristinare l'operazione precedente. Come è possibile procedere? 
ID ANPR cittadino da ripristinare: 48909517
in attesa di riscontro si porgono cordiali saluti

**Comment by frmariani** [comment]
Potete verificare se il problema persiste per favore ?

**Comment by marcoLave** [comment]
Il problema non persiste più in quanto l'altro Comune aveva annullato la pratica e nuovamente inserita successivamente. Quindi ho dovuto solo archiviare la notifica. Mi scuso per il disturbo

**Comment by marcoLave** [comment]
Buongiorno, mi ricollego all'errore in quanto la persona risulta ripristinata dall'altro Comune (mi è arrivata una nuova notifica di ripristino) ma a livello di ANPR risulta sempre residente nell'altro Comune, probabilmente perchè non riesce a ripristinarlo in quanto la famglia precedente non esiste più in quanto sono tutti emigrati. Come possiamo fare?

**Comment by frmariani** [comment]
potete dirmi se il problema persiste?

**Comment by marcoLave** [comment]
Buongiorno,
l'assistenza telefonica mi ha fatto riscrivere il soggetto per immigrazione dalla data di decorrenza, quindi è stato risolto anche se c'è un errore a livello di storico di famiglia del soggetto.

**Comment by frmariani** [comment]
al momento l'unico modo per gestire i ripristini in famiglie nel frattempo emigrate è proprio quello di re-iscrivere il cittadino.
Per errore nello storico intende questo?

**Comment by marcoLave** [comment]
Che per l'ANPR a livello di storico risulta essere stato da solo in famiglia dal 22/07/2022 al 05/08/2022, quando in verità c'erano altri 2 componenti.

**Comment by frmariani** [comment]
Si ha ragione,  ma al momento,  per la consultazione storica dei cittadini che hanno subito ripristini in famiglie nel frattempo emigrate, si deve utilizzare il gestionale; in generale,  per i certificati storici è bene utilizzare il gestionale del comune.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
