### ISSUE TITLE
Rettifica dati di Matrimonio: aggiornamento errato del Coniuge - URGENTE

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3581]
ambiente di PRODUZIONE - comune di IMOLA (037-032)

idSoggettoANPR 38183014

è stato necessario inviare comunicazione di rettifica (ws 5008) per sanare delle anomalie collegate alla codifica del comune di nascita / atto nascita / matrimonio.
la comunicazione (idOperazioneANPR 1029188879), correttamente strutturata, viene accettata, ma il risultato inatteso è che sono stati compromessi i dati di matrimonio: il soggetto ha perso l'idSoggettoANPR del coniuge e risulta coniugato con sè stesso.

potete verificare e risolvere l'errore?

considerando che la richiesta di annullamento della comunicazione viene bloccata dall'errore EN234, confidiamo in un intervento tempestivo.

grazie
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera
provate ad annullare il 5008 id 1029188879

**Comment by AMonopoliADS** [comment]
abbiamo provato, ma l'errore in sede di richiesta annullamento persiste ed è lo stesso già segnalato
questa la response:
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EN234</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione.</testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2022-09-23 16:01:33 , idOperazioneANPR 1031864974</testoErroreAnomalia>
	</errore>
</listaErrori>

```

**Comment by ncapozzi** [comment]
Buonasera
la situazione è stata ripristinata adesso dovreste vedere il soggetto sposato con il coniuge deceduto e i dati della vedovanza.

**Comment by AMonopoliADS** [comment]
confermo che l'anagrafica è stata ripristinata e adesso la posizione è corretta.
