### ISSUE TITLE
mancato rilascio certificato

### ISSUE THREAD

**Issue by Alessia76** [italia/anpr#3583]
Buongiorno, cerco da due giorni di accedere ai miei certificati on line ma mi restituisce l'errore "si è verificato un errore non gestito" ho provato a sentire il mio comune e mi dicono che per loro è tutto a posto, se chiedo i certificati per mio figlio me lo lascia fare. E' possibile eliminare l'errore?
Grazie, buona giornata.
Alessia Pietrantuoni

**Comment by apaolacci** [comment]
Salve,
può fornici maggiori dettagli dell'operazione che non riesce a fare? Sarebbe utile conoscere data e ora dell'errore, con quale cittadino si accede il portale per emettere il certificato ed il dispositivo e browser utilizzato?

Grazie,
Assistenza ANPR

**Comment by Alessia76** [comment]
Buongiorno,
mi chiamo Pietrantuoni Alessia ho provato per tre giorni ripetutamente e da diversi browser a richiedere dei certificati ma non mi lascia accedere quando scelgo il mio nominativo segnalando "errore non gestito". Potrei tranquillamente richiedere invece quelli di mio figlio. Oggi mi sono recata presso il mio comune ma mi dicono che per loro è tutto a posto. Attualmente continuo ad essere bloccata e non riesco ad usufruire del servizio. Se posso dare altre info non esiti a contattarmi.
Grazie
Alessia 
--
Inviato da Libero Mail per Android venerdì, 23 settembre 2022, 02:16PM +02:00 da apaolacci  ***@***.*** :

**Comment by mttfranci** [comment]
Salve, abbiamo effettuato alcuni interventi che speriamo possano aver risolto il problema (o che almeno dovrebbero aiutarci a individuarlo), potreste fare un altro tentativo di emettere il certificato?
Grazie in anticipo.

Assistenza ANPR

**Comment by Alessia76** [comment]
Buongiorno,
purtroppo nulla, mi dà sempre lo stesso errore.
Grazie dell'interessamento.
Alessia 
--
Inviato da Libero Mail per Android giovedì, 29 settembre 2022, 04:11PM +02:00 da Matteo  ***@***.*** :

**Comment by mttfranci** [comment]
Visto, potreste provare ancora una volta?
Riteniamo che stavolta l'esito possa essere diverso.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
Buongiorno @Alessia76 per caso ha avuto modo di riprovare?
Un altro utente con una problematica simile ha risolto dopo la fix di ieri.
Grazie in anticipo

**Comment by Alessia76** [comment]
Si, scusi pensavo di aver risposto. Tutto sistemato, grazie infinite per l'aiuto.
Alessia 
--
Inviato da Libero Mail per Android venerdì, 30 settembre 2022, 10:21AM +02:00 da Matteo  ***@***.*** :

**Comment by mttfranci** [comment]
Perfetto!
Grazie mille del riscontro.
Saluti

Assistenza ANPR

**Comment by Alessia76** [comment]
Funziona!!! Grazie infinite per l'assistenza
Alessia 
--
Inviato da Libero Mail per Android giovedì, 29 settembre 2022, 04:35PM +02:00 da Matteo  ***@***.*** :
