### ISSUE TITLE
Problema scarico Notifiche N

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#3585]
Il comune di Scandolara non riesce più scaricare le notifiche ANPR di mutazioni anagrafiche.
Anpr  risponde che "la richiesta è ancora in elaborazione"...
Dalla WebApp ha verificato che ci sono pratiche in giacenza dalla data 02/08/2022.

**Comment by amollicone1982** [comment]
Ci potete fornire un idea operazione?

**Comment by ATropeano** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ALESSI~1.TRO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ALESSI~1.TRO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



DATA_RICHIESTA | TIPO_OPERAZIONE | STATO_LAVORAZIONE | DESCR_STATO_LAVORAZIONE | IDANPR_OPERAZIONE
-- | -- | -- | -- | --
06/08/2022 08:39:11 | N010 | 7 | notifiche da prendere in carico | 971177487
08/08/2022 12:38:11 | N010 | 7 | notifiche da prendere in carico | 974781942
09/08/2022 09:12:05 | N010 | 7 | notifiche da prendere in carico | 975633540
11/08/2022 08:26:13 | N010 | 7 | notifiche da prendere in carico | 978104092
11/08/2022 09:24:14 | N010 | 7 | notifiche da prendere in carico | 978213325
11/08/2022 09:24:27 | N010 | 7 | notifiche da prendere in carico | 978213767
13/08/2022 11:03:59 | N010 | 7 | notifiche da prendere in carico | 980387512
16/08/2022 09:25:40 | N015 | 7 | notifiche da prendere in carico | 984304527
18/08/2022 09:01:50 | N010 | 7 | notifiche da prendere in carico | 986414773
19/08/2022 08:17:17 | N010 | 7 | notifiche da prendere in carico | 987529824
30/08/2022 09:06:47 | N010 | 7 | notifiche da prendere in carico | 1001379718
01/09/2022 08:42:05 | N010 | 7 | notifiche da prendere in carico | 1003767836
02/09/2022 10:11:20 | N010 | 7 | notifiche da prendere in carico | 1005209020
06/09/2022 08:55:22 | N010 | 7 | notifiche da prendere in carico | 1009840021
06/09/2022 14:25:52 | N010 | 7 | notifiche da prendere in carico | 1010504296
08/09/2022 13:01:02 | N010 | 7 | notifiche da prendere in carico | 1013009440
13/09/2022 10:57:34 | N010 | 7 | notifiche da prendere in carico | 1018679648
20/09/2022 09:05:34 | N010 | 7 | notifiche da prendere in carico | 1027072757
22/09/2022 12:11:00 | N010 | 7 | notifiche da prendere in carico | 1030268480
24/09/2022 15:20:13 | N010 | 7 | notifiche da prendere in carico | 1032542362
25/09/2022 09:39:32 | N010 | 7 | notifiche da prendere in carico | 1033113031
26/09/2022 12:41:59 | N010 | 7 | notifiche da prendere in carico | 1034695222
30/09/2022 10:38:06 | N010 | 7 | notifiche da prendere in carico | 1039694277



</body>

</html>

**Comment by amollicone1982** [comment]
Mi risultano tutti tutti elaborati. Naturalmente quelli di agosto non sono piu' disponibili

es. 1039694277 elaborato in data 30/09/2022 alle 10:58

**Comment by ATropeano** [comment]
Il comune mi conferma che ad oggi non gli risultano più operazioni sospese. Grazie
