### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by camilamps** [italia/anpr#3586]
Hi!

My name is Camila Mariano Paganini, I was born in Brazil.
My codice fiscale is MRNCML83______
Same error as in #2683 .

>     Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

In my Scheda Consolare and comune it's all ok.

What can I do?

Thank you!

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel dicembre 1983- dovrebbe rivolgersi al comune di Salizzole che l'ha iscritta Aire e chiedere  di far validare il suo codice fiscale nella scheda in Anpr -

**Comment by cmigliardi** [comment]
si chiude la issue
