### ISSUE TITLE
Notifiche Residenza - AIRE con flag AIRE a null

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#3587]
Buongiorno

abbiamo ricevuto una notfiica di residenza da iscritto AIRE (id. 29293300 richiesta n. 27608164) ma il campo IscrittoAIRE non è valorizzato. 
Potreste verificare e darci indicazioni?

Grazie
_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by ncapozzi** [comment]
Buongiorno,
non è chiaro a quale campo IscrittoAIRE si riferisce. Se ritiene può indicare un recapito telefonico così la ricontattiamo.
Grazie

**Comment by ANPRCdMI** [comment]
nella richiesta 27608164 il richiedente è un AIRE che torna a MIlano.
Nel P002 il campo soggettoAIRE del richiedente non è valorizzato:
"soggettoRichiedente": {
                    "note": null,
                    "soggettoAIRE": null,
                    "dataNascita": "1989-03-11T00:00:00.000+01",
                    "senzaGiorno": null,
                    "cognome": "R***",
                    "annoEspatrio": null,
                    "nome": "C***",
                    "luogoNascita": {
                        "localita": null,
                        "comune": {
                            "nomeComune": "MILANO",
                            "codiceIstat": "015146",
                            "descrizioneLocalita": null,
                            "siglaProvinciaIstat": "MI"
                        },

 E' corretto che sia così? Il soggetto è ancora AIRE fino alla conferma della variazione di residenza, quindi il flag dovrebbe avere valore 'S'  
Grazie

**Comment by ANPRCdMI** [comment]
Buongiorno
volevamo sapere se ci sono novità in merito a questa segnalazione.
Grazie

**Comment by ncapozzi** [comment]
Vedi #3731

**Comment by apaolacci** [comment]
@ANPRCdMI in merito alla issue #3731 riscontrate ancora il problema in test? 
Questa domanda perché è previsto a breve l'adeguamento del software in ambiente di produzione.

**Comment by ANPRCdMI** [comment]
Buongiorno

vi ringraziamo per l'intervento, ma a suo tempo abbiamo trovato una soluzione alternativa, recuperando il dato mancante con la lettura di un 3002. La funzione di apertura automatica delle pratiche da Portale ANPR è in produzione ormai da mesi e non  sono previste al momento implementazioni. 

Saluti
_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by ncapozzi** [comment]
L'intervento è stato rilasciato in produzione
