### ISSUE TITLE
[Subentro] File APR:  Oggetti da (non) inviare ad ANPR

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#359]
Buongiorno,
considerando alcune discussioni ancora aperte, e tenendo conto degli interventi interessanti e professionali fatti in merito, vorrei chiedere, gentilmente, se può essere presa in considerazione la possibilità di aggiungere nel documento "Allegato XML S001- Subentro.xls" e a tutti i documenti ad esso collegati, una nuova colonna in cui viene specificato esplicitamente se l'oggetto deve essere inviato obbligatoriamente o se può essere tralasciato in fase di subentro.
Correggetemi se sbaglio, ma la colonna "Obbl." indica solo che "il soggetto potrebbe avere un'istanza associata" (come ad esempio, nel caso del matrimonio, in base allo stato civile).
Da quanto emerge da recenti discussioni, sembra che alcuni oggetti abbiano poco significato se inviati in fase di subentro. 
Credo che possa valere per "listaElettorale", e senza alcuna volontà di sminuire niente, penso che valga anche per autoveicoli (possessoAutoveicoli, possessoPatente) e altriDati (posizioneProfessionale, condizioneNonProfessionale, titoloStudio).
Grazie

Eduardo Gira
Servizi Locali S.p.A.

**Comment by gcarbonin** [comment]
Al momento del subentro si deve inviare la fotografia della scheda individuale (e della scheda famiglia) quale risulta a quella data.  Riguardo al significato di alcuni oggetti preciso quanto segue:

- ListaElettorale indica se la persona è iscritta o meno nella lista; il "non iscritta" si articola in due casi: non elettore (ad es. bambino) o perdita del diritto al voto. Il dato è facoltativo per i residenti ma obbligatorio per gli AIRE: corrisponde, infatti, all'attuale TIPOELETTORE di AnagAire;
- Veicoli/Patenti è un dato facoltativo;
- altriDati (Titolo di studio, condizione non professionale, ecc.) sono attributi della scheda individuale; hanno un interesse solo statistico; se disponibili vanno inviati.
-

**Comment by gcarbonin** [comment]
Ci sono altri commenti?
