### ISSUE TITLE
Impossibile scaricare certificato STATO CIVILE

### ISSUE THREAD

**Issue by gaiettatostetta** [italia/anpr#3591]
Buongiorno a tutti,

da qualche settimana sto provando a scaricare il certificato di STATO CIVILE dal sito di ANPR. 
La mia anagrafica risulta correttamente compilata, ma fra i certificati che posso scaricare, compaiono solamente:
- RESIDENZA
- STATO DI FAMIGLIA.
Come posso visualizzare anche lo STATO CIVILE?
Per pratiche relative ad acquisto immobiliare, necessito del certificato a stretto giro, ed il mio Comune mi rimanda al sito di ANPR.

Gracias
G

**Comment by cmigliardi** [comment]
salve per favore ci può dare le prime 6 lettere del suo codice fiscale per vedere la situazione?  grazie anticipatamente

**Comment by gaiettatostetta** [comment]
TSTGAI

**Comment by cmigliardi** [comment]
è lei la persona nata nel 92 a roma?

**Comment by gaiettatostetta** [comment]
confermo!

**Comment by cmigliardi** [comment]
grazie verifichiamo e le facciamo sapere

**Comment by cmigliardi** [comment]
dunque, dovrebbe rivolgersi al suo comune Fiumicino e far presente il problema,  in Anpr ci risulta un procedimento non ancora chiuso dal suo comune.  finché non  verrà chiuso la sua scheda anagrafica avrà una certificabilità parziale e e non completa.

**Comment by cmigliardi** [comment]
si chiude la issue
