### ISSUE TITLE
Certificato Stato di libero mancante

### ISSUE THREAD

**Issue by empy91** [italia/anpr#3595]
Buongiorno,
  per l'utenza con CF iniziante per CLNMLE con data nascita 91 non è recuperabile il certificato di stato di libero.
Gli unici certificati disponibili sono RESIDENZA e STATO DI FAMIGLIA.

Il certificato è urgente 

Grazie

**Comment by cmigliardi** [comment]
salve se è lei la persona  nata nel luglio 1991 - le consiglio di rivolgersi al suo comune OPPEANO perché debbono chiudere un procedimento sulla sua scheda- finché non la effettueranno lei avrà una scheda con una certificabilità parziale -. si  chiude la issue
