### ISSUE TITLE
[5010] Info sul servizio

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3597]
Buongiorno
stiamo testando i servizi delle liste elettorali, volevamo farvi alcune domande:

1. Quando un cittadino viene iscritto in una lista aggiunta regionale da un nostro comune, il cittadino non è residente nel nostro comune, ma è ovviamente emigrato. Possiamo quindi noi variare i suoi dati?
2. I tag: _referendumnazionali, elezionimembriue, senatorepubblica, camaeradeputati, regionali, comunali, circoscrizionali_ come e quando vanno utilizzati? Bisogna specificare a quali consultazioni può partecipare l'elettore nel nostro comune? In teoria in base alle liste in cui viene iscritto dovrebbe essere un'informazione a voi già nota.

Grazie

**Comment by frmariani** [comment]
Punto 1
Forse è meglio fare un esempio: un cittadino residente nel comune di Roma  _vostro comune_  emigra nel comune di Bolzano _è ovviamente emigrato_ ; il comune di Roma _vostro comune_ aggiornerà la lista regionale/comunale, mentre il comune di Bolzano aggiornerà la lista generale;
Punto 2
il decreto prevede che vengano inviati tutti i dati, pertanto dovete comunicarli.

**Comment by SAlberto** [comment]
Grazie,
un altro dubbio, il campo _**elettore**_  del blocco _**liste**_ come va utilizzato? Quando è necessario metterlo a N?

**Comment by frmariani** [comment]
naturalmente quando il cittadino non risulta elettore, ma forse dovrebbe specificare meglio il dubbio;

**Comment by SAlberto** [comment]
Quando un Cittadino non risulta elettore il comune non manderà mai il blocco **_liste_** e quindi l'attributo _**elettore**_, al massimo manderà il blocco **_cancellazione_**.
Il dubbio è, esiste una situazione in cui il comune trasmette il blocco **_liste_** con **_elettore_** a N?

**Comment by frmariani** [comment]
Per inviare il blocco della cancellazione il cittadino deve essere stato iscritto precedentemente nella lista;
nel caso in cui, ad esempio, un cittadino maggiorenne già al primo caricamento risulti non elettore per cause ostative, si può inviare tale informazione inserendo N nel tipo elettore.

**Comment by SAlberto** [comment]
Esistono altre situazioni in cui va usato **_elettore_** a N?

Tornando invece all'esempio che ci avete fatto: se indico elettore a N in fase di PRIMOCARICAMENTO vi sto inviando una persona interdetta dai pubblici uffici, che quindi non ha una sezione elettorale e non rientra in nessuna delle liste del comune, però da tracciato il tipoMutazione è obbligatorio e di conseguenza anche un blocco tra listaGenerale o listaAggiuntaUE o listaAggiuntaComReg.

Se abbiamo capito bene come vanno valorizzati i campi?

**Comment by frmariani** [comment]
per le ulteriori situazioni in cui inserire l'attributo elettore ad N, direi che potete consultare il comune stesso;
per quanto riguarda la seconda domanda in linea di massima si deve utilizzare la lista generale, ma se il cittadino non è di cittadinanza italiana si opterà per la lista aggiunta; se l'attributo di non elettore si riferisce alla lista regionale/comunale vien inibito nella lista regionale/comunale.

**Comment by SAlberto** [comment]
Chiedo scusa non mi sono spiegato al meglio.
Se indico _elettore_ a N per un cittadino, per esempio per cause ostative, questo cittadino non rientra in nessuna lista, ne generale ne aggiunta, ma per il tracciato una delle liste è obbligatoria, quindi come si deve procedere?

**Comment by frmariani** [comment]
al momento la lista è un dato obbligatorio. 
per il cittadino la causa ostativa sarà subentrata in un secondo momento, precedentemente apparteneva ad una lista (vedi risposta precedente) e tale lista deve essere indicata; mi rendo conto che l'ostativa cancella il cittadino dalla lista, ma dobbiamo presupporre che se viene cancellato da una lista per ostative, tale indicazione della precedente lista di appartenenza deve essere presente nel sistema.
Comunque faremo presente la sua segnalazione al Ministero.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
