### ISSUE TITLE
Certificati comunali Ambiente di test

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3598]
Buongiorno,
ad agosto sono scaduti i certificati dell'ambiente di test dei comuni che usiamo per effettuare le nostre prove su ANPR.
Nello specifico parliamo di 004215-CO-0000.p12 e di 017074-CO-0000.p12.

Potete fare voi qualcosa?

Grazie

**Comment by SAlberto** [comment]
Sollecito una risposta, abbiamo bisogno di sbloccare la situazione per proseguire con i test.

Grazie

**Comment by Leonforte** [comment]
Buongiorno, i nuovi certificati sono stati inviati rispettivamente a 

e.ferrero@comune.savigliano.cn.it
anagrafe@comune.gardoneriviera.bs.it
 
Buon lavoro, saluti
