### ISSUE TITLE
Web-App Consultazione scheda individuale - Stampa scheda individuale

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#36]
Data test- 20/03/2017 - Ambiente test (dptest)
Il pdf di Visura Anagrafica nella sezione Famiglia  riporta solo per l'intestatario scheda " Identificativo della famiglia" attribuito da ANPR, " Identificativo della famiglia assegnato dal comune" e
 "Costituita in data". 
Si richiede di visualizzarla per tutti i componenti della famiglia.
Grazie
Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Avvertiamo quando disponibile la modifica.

**Comment by gcarbonin** [comment]
Può riprovare. Mi faccia sapere se va bene

**Comment by annamariaGillone** [comment]
Va bene. 
Grazie
Annamaria
