### ISSUE TITLE
Ambiente di Presubentro - anomalia EF009

### ISSUE THREAD

**Issue by busaster** [italia/anpr#360]
Caricando in ANPR i dati di presubentro di Gorgonzola abbiamo ricevuto l'anomalia "EF009" "Intestatario della scheda famiglia/convivenza non univoco" relativamente alla scheda convivenza ID ANPR 10457730.

Ho verificato nel file xml di subentro le persone residenti in quella convivenza ma ve n'è solo una con il codice legame 1. Tale soggetto oltre ad esservi residente è anche citato nel file di subentro come "tipoTutoreIntestatario" nel tag "convivenza" relativo.

Non capisco quindi quale sia l'anomalia che viene segnalata. 
Potete aiutarmi ?
Grazie

**Comment by busaster** [comment]
Ho spulciato la documentazione del subentro ed ho letto che il tag tipoTutoreIntestatario è "Da valorizzare nel caso in cui il responsabile sia residente in un altro comune".
Questo spiega nel mio caso l'anomalia, ma mi chiedo : se il responsabile è residente nel mio comune ma in una sua famiglia anagrafica (quindi NON nella convivenza) come mi devo comportare ?

**Comment by amollicone1982** [comment]
Nei casi in cui il responsabile della convivenza risieda all'interno di essa va inviato il soggetto con codice legame 2 e nella sezione convivenze del file di subentro va inserito come responsabile (tag tipoTutoreIntestatario). Nel caso in cui risieda nel comune ma in una sua famiglia anagrafica va inviato il soggetto come appartenente alla famiglia (con relativo codice legame all'interno della famiglia) e nella sezione convivenze del file di subentro va inserito come responsabile della convivenza (tag tipoTutoreIntestatario)
Per quel che riguarda la documentazione ("Da valorizzare nel caso in cui il responsabile sia residente in un altro comune") c'era un refuso che è stato sistemato.

**Comment by busaster** [comment]
Ok. Quindi il codice legame 1 non va mai utilizzato all'interno di una convivenza ?

**Comment by amollicone1982** [comment]
Si, non va utilizzato
