### ISSUE TITLE
MANCATO COLLEGAMENTO ALLA PAGINA ANPR

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#3600]
COMUNE DI GHEMME - NO -Da qualche tempo cercando di collegarmi con ANPR mi ese la scritta
Impossibile raggiungere il sitoLa pagina web all'indirizzo https://dp2.anpr.interno.it/com potrebbe essere temporaneamente non disponibile oppure è stata permanentemente spostata a un nuovo indirizzo web.
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED
Lunica differenza rispetto a prima è la finestra che i compare per la digitazione della password che prima compariva al centro dello schermo ora è una piccola finestra in basso a destra di colore grigio chiaro con l'immagine di una sagoma nera e di un chip arancio riporta la scritta : inserire il PIN............... SMSC SMSC USX101X READER 0
Grazie per l'aiuto

**Comment by Leonforte** [comment]
Buongiorno, il link corretto per il collegamento tramite smart card è https://dp.anpr.interno.it/com

**Comment by LORELLAB** [comment]
Ed infatti è li che mi collego, dopodiche' vengono caricati  i certificati e poi appare quella finestrella in basso a destra dove indicare la password... ma il ri sultato e sempre quello.....
Duplicate of #

**Comment by Leonforte** [comment]
Ok, la contattiamo

**Comment by adominicis** [comment]
Può fornirmi un recapito telefonico diretto? Il numero principale mi avvisa che gli uffici sono chiusi; altrimenti la chiamo domani mattina

**Comment by Leonforte** [comment]
Problema risolto n assistenza remota. Motivo anomalia : Installazione software Infocamere cns
