### ISSUE TITLE
Chiusura Procedimento inesistente in ANPR

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#3601]
Buongiorno,
vi scrivo perchè sta capitando su diversi nostri clienti che ci siano alcuni problemi per la chiusura della pratiche di variazione d'indirizzo (abbiamo fatto le stesse prove su ambiente di test e li non si è evidenziato il problema).

Ad esempio riportiamo una situazione che si è verificata per il comune di Feltre:
non è possibile chiudere la pratica a seguito del seguente messaggio:
"Il numero pratica comune 236 indicato per il procedimento amministrativo non e' presente."

Come si potrà vedere dalle richieste di seguito, prese come esempio, il numero di pratica viene correttamente inviato.
CASO: Pratica variazione di indirizzo in comune

id Pa Digitale (numero pratica comune per anpr) = 236

trasmissione apertura procedimento inviata il 04-08-2022
idoperazioneanpr=510733743

```
<p:Richiesta1014 xmlns:p=http://sogei.it/ANPR/1000iscrizione>
<testataRichiesta>
<idOperazioneComune>50969</idOperazioneComune>
<codMittente>025021</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>1014</operazioneRichiesta>
<dataOraRichiesta>2022-08-04T10:04:28</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<tipoInvio>PROD</tipoInvio>
<dataDecorrenza>2022-08-04</dataDecorrenza>
<nomeApplicativo>Urbi</nomeApplicativo>
<versioneApplicativo>Smart2.0</versioneApplicativo>
<fornitoreApplicativo>PADigitale Spa</fornitoreApplicativo>
</testataRichiesta>
<procedimentoIstruttoria>
<numeroPraticaComune>236</numeroPraticaComune>
<tipoOperazione>I</tipoOperazione>
<motivoAvvio>6</motivoAvvio>
<dataStato>2022-08-04</dataStato>
<statoProcedimento>1</statoProcedimento>
</procedimentoIstruttoria>
</p:Richiesta1014>
```

trasmissione mutazione data operazione= 04-08-2022 idoperazioneanpr=968771218 andata a buon fine

trasmissione chiusura del procedimento in errore data operazione 12-09-2022 idoperazioneanpr=1017904419

TIPO      CODICE ERRORE               DESCRIZIONE ERRORE
E                        EHRA1      Il numero pratica comune 236 indicato per il procedimento amministrativo non e' presente
E                        EN527       Informazioni sull'operazione da fornire in caso di assistenza : data 2022-09-12 16:36:40 , idOperazioneANPR 1017904419

```
<p:Richiesta1014 xmlns:p=http://sogei.it/ANPR/1000iscrizione>
<testataRichiesta>
<idOperazioneComune>99952446</idOperazioneComune>
<codMittente>025021</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>1014</operazioneRichiesta>
<dataOraRichiesta>2022-09-12T16:36:36</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<tipoInvio>PROD</tipoInvio>
<dataDecorrenza>2022-09-12</dataDecorrenza>
<nomeApplicativo>Urbi</nomeApplicativo>
<versioneApplicativo>Smart2.0</versioneApplicativo>
<fornitoreApplicativo>PADigitale Spa</fornitoreApplicativo>
</testataRichiesta>
<procedimentoIstruttoria>
<numeroPraticaComune>236</numeroPraticaComune>
<tipoOperazione>C</tipoOperazione>
<dataChiusura>2022-09-12</dataChiusura>
<motivoAvvio>6</motivoAvvio>
<dataStato>2022-09-12</dataStato>
<statoProcedimento>2</statoProcedimento>
<esitoChiusura>C</esitoChiusura>
</procedimentoIstruttoria>
</p:Richiesta1014>
```

Abbiamo bisogno di capire quale sia il problema anche perchè non succede su tutte le pratiche: ad esempio era stata lavorata la pratica con id Pa Digitale con numero successivo e/o precedente ed era andato tutto a buon fine.
Non riusciamo a capire quale da cosa può dipendere questa anomalia, anche perchè il primo xml viene inviato correttamente e quindi l'id 236 viene passato ad ANPR.

Rimaniamo in attesa di un riscontro.
Grazie
Marco Sala
Pa Digitale SPA

**Comment by frmariani** [comment]
all'operazione idanpr 510733743 indicata,  corrisponde  l'operazione di chiusura del procedimento 2021-793 (numeropraticacomune), aperto con l'operazione idanpr 490752902 in data 25/3/2021.

Nel WS 5005, idoperazione anpr  968771218,  dove avete indicato il procedimento 236, un warning segnalava appunto l'inesistenza del procedimento indicato.

**Comment by MarcoSalaPad** [comment]
Ok grazie per la vostra risposta.
Abbiamo capito come gestire la casistica.
