### ISSUE TITLE
[P003] Errore di validazione del campo note

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3603]
Buongiorno, 

in ambiente di produzione abbiamo riscontrato un problema durante la validazione dell'XML di request di un servizio P003 che nel campo note contiene il simbolo /. 

The 'note' element is invalid - The value 'Si prega di telefonare 0123/456789 dal lunedì al venerdì 9/12. Cordiali saluti' is invalid according to its datatype 'http://sogei.it/ANPR/tipoDato:tipoNote' - The Pattern constraint failed. (Riga: 20, Colonna: 90)

In effetti nella definizione di tipoNoteBase a cui fa riferimento tipoNote non è presente questo simbolo.

Dato che è abbastanza comune usare la / come separatore per i numeri di telefono, gli orari o le date, potete valutare di inserirlo fra i caratteri ammessi per il tipoNoteBase?

Grazie
Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by ncapozzi** [comment]
Vedi #3731

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, abbiamo fatto alcune prove in ambiente di test e non ci risultano problemi, ora i caratteri vengono accettati. Grazie

**Comment by ncapozzi** [comment]
L'intervento è stato rilasciato in produzione
