### ISSUE TITLE
ANPR - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by felipesastre** [italia/anpr#3606]
Ciao, voglio accedere al portale ANPR ma c'è un errore: non risulta possibile individuare di modo univoco la mia scheda anagrafica.

![inbound5579539672479537513](https://user-images.githubusercontent.com/115350762/194704681-a0dd57ca-7480-46f6-b225-2b6530533b42.jpg)

Ho scritto al Comune di Anzi (PZ) e loro rispondono che non si verifica nessun problema.

Sono residente all'Estero (Argentino). Qualcuno sa che devo fare?

**Comment by cmigliardi** [comment]
gentilmente ci può dare le prime 6 lettere del suo codice fiscale ? altrimenti non sappiamo come controllare la situazione . grazie

**Comment by felipesastre** [comment]
> gentilmente ci può dare le prime 6 lettere del suo codice fiscale ? altrimenti non sappiamo come controllare la situazione . grazie 

Certo, SSTFLP

**Comment by cmigliardi** [comment]
grazie se è lei la persona nata nel 1993  a luglio, deve chiedere al suo comune  ANZI  di  provvedere alla validazione del  suo codice fiscale nella scheda di ANPR  -  si chiude la issue -
