### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio ANPR

### ISSUE THREAD

**Issue by vczy310** [italia/anpr#3607]
Gentili signori

Non riesco ad accedere il sito ANPR - appare questo messaggio di errore: "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Non ci sono problemi con la mia scheda anagrafica

Comune: Milano

Prime 6 lettere del CF: RNDVLR

**Comment by vczy310** [comment]
Problemi simili:
#2683
#2809

**Comment by cmigliardi** [comment]
se è lei la persona nata  nel 1994  in ottobre si deve rivolgere al comune di Milano perché lei ha 2 codici fiscali -  e nella scheda ANPR il codice fiscale non è validato  -

**Comment by vczy310** [comment]
Grazie per l'informazione. Giusto per capire, sono due CF diversi?

**Comment by cmigliardi** [comment]
certo forse  lei ha chiesto delle variazioni?   questo io non posso saperlo

**Comment by cmigliardi** [comment]
lei ha usato con SPID  quello che termina con la lettera D

**Comment by cmigliardi** [comment]
a maggior ragione  chieda al comune di Milano . perché il codice  che termina con la D  in Anpr non risulta validato e lo può  sanare solo il comune -  si chiude la  issue

**Comment by vczy310** [comment]
Grazie.

**Comment by cmigliardi** [comment]
di nulla

**Comment by Claudiopizzale** [comment]
Non riesco ad accedere ad anpr
