### ISSUE TITLE
SERVIZIO P003 - CARATTERI NON CONSENTITI

### ISSUE THREAD

**Issue by AriannaIeicicGPI** [italia/anpr#3608]
Buongiorno abbiamo riscontrato che nel servizio indicato sono concessi solo i seguenti caratteri:
0-9a-zA-ZIiŠŒŽšœž-ŸÀ-žƉ,.\-'":;

Oltre alle / che indichiamo già dal presubentro ai clienti di non utilizzare mai non possono usare:
- parentesi
- @ 
- caratteri accentati
il tutto è assolutamente limitante nelle comunicazioni con il cittadino e inoltre svariati comuni mi indicano che dalla webapp invece i caratteri sono ammessi.
è possibile aggiornare le specifiche aggiungendo almeno i caratteri indicati (opportuno sarebbe tutti quelli ammessi direttamente da WebApp)

Grazie
Arianna Ieicic
GPI

**Comment by ncapozzi** [comment]
Vedi #3731

**Comment by apaolacci** [comment]
@AriannaIeicicGPI AriannaIeicicGPI in merito alla issue #3731 riscontrate ancora il problema in test?
Questa domanda perché è previsto a breve l'adeguamento del software in ambiente di produzione.

**Comment by ncapozzi** [comment]
L'intervento è stato rilasciato in produzione
