### ISSUE TITLE
Movimento Migratorio da Comune subentrato a Comune Subentrato

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#361]
In data 05/10/2017 il Comune di Cesena ha ricevuto dal Comune di Bagnacavallo (comune subentrato in ANPR) pratica apr4 con richiesta di cancellazione della cittadina identificativo ANPR 18545910

L'operatore di Cesena, errando, ha proceduto cancellando la cittadina per comune non subentrato accortosi dell'errore ha poi annullato l'operazione. (in realtà voleva verificare se vi fosse un qualche blocco)

 A tal proposito:

1. E' possibile prevedere blocco in fase di invio operazione di cancellazione per comune non subentrato se viene indicato come comune di cancellazione il codice istat di un comune già in ANPR?

2. come dobbiamo comportarci riguardo alla posizione di questa cittadina che attualmente risulta ancora  residente nel Comune di Cesena? 

Grazie

**Comment by gcarbonin** [comment]
Stiamo inserendo il controllo. Siamo in contatto con il comune

**Comment by gcarbonin** [comment]
Il controllo è stato inserito. Da oggi è operativo anche in ambiente di esercizio

**Comment by RBiasi** [comment]
Per quanto riguarda la cittadina questa risulta ancora residente in Cesena. Ci pensate voi?
Grazie

**Comment by gcarbonin** [comment]
La signora ora risiede a Bagnacavallo
