### ISSUE TITLE
[5010] Info sulla cancellazione

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3610]
Buongiorno,
nella chiamata 5010 la sezione _cancellazione_ ha un campo _motivoCancellazione_.
La decodifica che avete fornito:

```
1	Trasferimento residenza
2	Irreperibilita
3	Morte
4	Motivi vari
5	Cancellazione lista aggiunta UE comunali
6	Cancellazione lista aggiunta UE parlamento europeo
7	Cancellazione lista aggiunta comunali regionali
8	Cancellazione Lista generale
```

come va usata?

Perchè da 1 a 4 indicano il motivo, mentre da 5 a 8 indicano da dove vengono cancellati.
A mio avviso andrebbe indicato un ID preso tra 1 e 4 associato a un ID tra 5 e 8.
Per esempio se scelgo 8 (Cancellazione Lista generale), non esclude che sia stato cancellato dalla lista generare per Morte(3) piuttosto che per Irreperibilità(2)

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
