### ISSUE TITLE
Errore di Accesso

### ISSUE THREAD

**Issue by jamboke** [italia/anpr#3616]
Buongiorno, sono cittadina all'estero e ANPR mi da il seguente errore: 

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Mio Codice Fiscale è valido se lo cerco sul https://telematici.agenziaentrate.gov.it/VerificaCF/Scegli.do?parameter=verificaCf
I primi 6 caratteri del mio codice fiscale sono: RLNSLV
Secondo il consolato generale tutto è corretto nel registro all'AIRE.

Grazie mille.

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 1987  in brasile - in ANPR la sua scheda non c'è si rivolga al comune che l'ha iscritta all'Aire  -

**Comment by jamboke** [comment]
Grazie mille per la pronta risposta. Cosa devo chiedere esattamente al consolato di aggiornare?

**Comment by cmigliardi** [comment]
va contattato il COMUNE  che può operare in ANPR

**Comment by jamboke** [comment]
Perfetto. Quindi devo contattare il comune di registrazione originale e non il consolato?

**Comment by cmigliardi** [comment]
sì è così

**Comment by cmigliardi** [comment]
in ANPR la sua scheda non c'è
