### ISSUE TITLE
Errore  EN309 - test - Indicare la data della sentenza o dell'atto di cessazione del matrimonio

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#362]
Effettuando l'invio su ambiente di test ricevo l'elenco di alcuni errori EN309 riguardanti l'assenza della data della sentenza di divorzio.
Verificando i dati e l'xml inviato rilevo che le date (e tutti i dati pertinenti) sono stati inviati.
Da una visura web dell'anagrafica delle persone vedo che i dati sono presenti nei campi giusti ma nella parte finale mi si evidenzia comunque la presenza dell'anomalia EN309  tipo errore 1 con la descrizione gia' riportata.
Questa situazione si ha solamente per i divorzi DL 132/2014 (presso il Comune) e non per quelli del tribunale.
E' capitato anche ad altri?
Soluzioni?
Renzo

**Comment by gcarbonin** [comment]
Puo' indicarci il comune e un identificativo operazione o soggetto?

**Comment by RENZO63** [comment]
Comune di Valle Mosso - BI
Un nominativo a caso: M.I. identificativo anpr 4751354   ho pero' cancellato i dati inviati perche' voglio ritentare dopo aver corretto altri errori, credo gli ultimi  quindi ora sul web i dati non compaiono (ma se viene tenuta traccia li trovera')
Per questo soggetto coniugato all'estero e separato e successivamente divorziato nel mio comune viene generato l'errore pur contenendo la sua scheda tutti i dati
In totale i casi riguardano 10 persone
Grazie
Renzo63

**Comment by gcarbonin** [comment]
I dati in pre-subentro non vengono mantenuti quando cancellate. Aspetto il nuovo caricamento. L'altra anomalia che mi aveva segnalato telefonicamente è stata rimossa.

**Comment by moniapellizzari** [comment]
Buongiorno,
si segnala che anche noi ieri abbiamo registrato in anagrafe un divorzio di due cittadini nostri residenti avvenuto con accordo di negoziazione assistita DL 132/2014 trascritto nel un altro Comune (Comune di matrimonio).
Abbiamo caricato i dati in nostro possesso luogo, data e numero dell'atto. il sistema però ci chiedeva anche di inserire data sentenza e Tribunale di riferimento che ovviamente in divorzi con questa procedura non esistono. Per poter far passare l'evento in ANPR abbiamo inserito nel campo sentenza quella dell'accordo di negoziazione assistita  e nel campo Tribunale il comune di trascrizione dell'atto, anche se non sarebbe corretto. 
Lo stesso problema si riscontrava quando inviavamo le comunicazione tramite INA-SAIA.
Se può essere utile inoltro i codici ANPR dei due cittadini 18666423 e 18666330
Si chiede come è opportuno procedere in questi casi e che interventi sono previsti.
Cordiali saluti.
Monia Pellizzari
Comune di Anzola dell'Emilia

**Comment by gcarbonin** [comment]
Occorre indicare come tipo tribunale il valore 4; nel campo autorita l'avvocato o il notaio; la dataValidita.
Queste indicazioni sono presenti nella documentazione tecnica.

**Comment by bfilipazzi** [comment]
Le stesse indicazioni valgono anche per l'accordo stipulato davanti all'ufficiale dello stato civile? Grazie.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Sì, il tipo 4 prevede Avvocato/Notaio/Ufficiale di Stato Civile
