### ISSUE TITLE
[P003] Numero caratteri consentiti campo note ws diverso rispetto alla Webapp

### ISSUE THREAD

**Issue by SilviaRivi** [italia/anpr#3620]
Buongiorno,

in ambiente di produzione sul Ws P003 abbiamo riscontrato un anomalia rispetto alla Webapp. 
La request del servizio P003 relativa al campo **note** consente al massimo 240 caratteri come riportato sull'xsd.
![image](https://user-images.githubusercontent.com/71002651/196709213-49b547a6-877d-4347-888f-898f77917ebf.png)

Mentre sulla WebApp è possibile inserire molti più caratteri come si vede da stamp qui sotto.
![image](https://user-images.githubusercontent.com/71002651/196714197-5d276868-934a-4c80-9d08-2190fb5e87a2.png)

E' possibile adeguare il ws P003 relativo al campo **note** allo stesso numero di caratteri ammessi sulla WebApp?

In attesa di risposta
Grazie
Silvia Rivi
Palitalsoft s.r.l.

**Comment by ncapozzi** [comment]
#3603 #3608
Buonasera, gli interventi saranno inclusi nelle attività evolutive in corso.

**Comment by ncapozzi** [comment]
Vedi #3731

**Comment by apaolacci** [comment]
@SilviaRivi in merito alla issue #3731 riscontrate ancora il problema in test?
Questa domanda perché è previsto a breve l'adeguamento del software in ambiente di produzione.

**Comment by SilviaRivi** [comment]
Buonasera, 
confermo che il problema sull'ambiente di test 
non si verifica più dopo che è stato fatto aggiornamento dei web service.
Grazie

Silvia Rivi
Palitalsoft s.r.l.

**Comment by ncapozzi** [comment]
L'intervento è stato rilasciato in produzione
