### ISSUE TITLE
TipoAttoANPR

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#3626]
Buongiorno,
in relazione alla #3625 mi era sembrato di capire che gli elementi tipoAtto e tipoAttoANSC fossero alternativi mentre nell'XSD trovo questa definizione:
	<xs:complexType name="tipoAttoANPR">
		<xs:choice>
			<xs:sequence>
				<xs:element name="atto"        type="tipoAtto"   			minOccurs="1" maxOccurs="1"/>
				<xs:element name="attoANSC"	   type="tipoAttoANSC"   minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:choice>
	</xs:complexType> 
come se entrambi dovessero essere presenti, mi potete chiarire le modalità di trasmissione?
Grazie.
Luca Bonini

**Comment by rvinzani** [comment]
Grazie della segnalazione. Abbiamo rilasciato una versione aggiornata delle specifiche nella issue:  https://github.com/italia/anpr/issues/3625
