### ISSUE TITLE
CODICE ERRORE EN 181 - RICHIESTA EMISSIONE DI CERTIFICATO STORICO DI RESIDENZA

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#363]
Num. Ind. ANPR : 18846607
 persona Iscritta in ANPR il 07/02/2017 per IMMIGRAZIONE
· Cancellata da APR il 04/10/2017 per EMIGRAZIONE a VENEZIA (VE)
il sistema non stampa lo storico di residenza.
Questa semplice tipologia di certificati vengono chiesti per esempio dalle ASL che devono addebitare prestazioni fatte fuori distretto e devono sapere a quale ASL addebitarle, tribunali, forze dell'ordine questura ecc.
nel caso in questione la persona è immigrata nel nostro comune il 07/02/2017 (prima del subentro) e in ANPR è corretta. E' emigrata il 04/10/2017 e ANPR l'ha registrata..
perché dà l' errore : il certificato non può essere emesso perché risulta un procedimento aperto?
io non ne ho e sembra che anche in ANPR sia chiuso ..
chiedo conferma.
Grazie
Raffaella
Comune Spinea

**Comment by gcarbonin** [comment]
Buongiorno in quale ambiente?

**Comment by Raffive** [comment]
Produzione

**Comment by gcarbonin** [comment]
il procedimento c'è ed è aperto (numero pratica comune = 200-580-2017) dal 4 ottobre.
