### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

### ISSUE THREAD

**Issue by aliqasimmm** [italia/anpr#3634]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.

Faccio presente che il Comune di Pieve Emanuele (MI)
Cosa devo fare?

**Comment by cmigliardi** [comment]
salve per poterla aiutare abbiamo necessità delle prime 6 lettere del suo codice fiscale  - grazie

**Comment by aliqasimmm** [comment]
Salve,

Queste sono le prime 6 lettere del codice fiscale:
GHLMTF
Mi faccia sapere se ha bisogno di altro.

Saluti

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel '73  si rivolga al suo comune perché in Anpr la scheda risulta cancellata

**Comment by cmigliardi** [comment]
si chiude la issue
