### ISSUE TITLE
Anomalia nei dati

### ISSUE THREAD

**Issue by aleaccorsi** [italia/anpr#3635]
Buongiorno, 

stavo cercando di accedere al portale per richiedere un certificato di nascita dal mio ultimo comune di residenza. 

Prime cifre del codice fiscale CCRLSN

Grazie

**Comment by cmigliardi** [comment]
salve se è lei la persona  nata a giugno '86  le consiglio di rivolgersi al comune - perché in Anpr la sua scheda  risulta cancellata -

**Comment by cmigliardi** [comment]
si chiude la issue
