### ISSUE TITLE
Passaggio in subentro - Richiesta SM

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#364]
Buongiorno,
Comune di Sporminore (TN) pre subentro l'ente è pronto per il subentro abbiamo bisogno di alcuni chiarimenti:

1. che utenti sono da censire in Censimento ANPR nell'area privata dei servizi demografici? Tutti gli utenti o un unico amministratore che poi si occuperà di generare i certificati di sicurezza per gli altri utenti?

2. Che tempi sono previsti e con che modalità verrà convocato il Comune per ritirare le SmartCard?

C'è modo di sollecitare?

Grazie

**Comment by gcarbonin** [comment]
1) vanno censiti TUTTI gli utenti che accederanno ad ANPR, il sindaco o il suo delegato, l'Amministratore locale delle postazioni e l'Amministratore locale della sicurezza. Gli ultimi tre sono obbligatoriamente titolari smart card; per gli altri il comune deve specificare se lo saranno
2) il comune riceve una PEC quando le smart card sono pronte, Dal censimento considerate 7-10 giorni.

**Comment by Eduardo1977** [comment]
Buongiorno,
il comune di Bistagno (AL) è pronto per il subentro e stamattina ha fornito intervallo e data preferita.
Se in precedenza nella scheda monitoraggio era stata indicata 1 sola postazione come si procede per chiedere ulteriori postazioni?
In questo caso, trattandosi di un piccolo comune che non ha all'interno un responsabile dei sistemi, il Sindaco sta assumendo le funzioni anche di ALP E ALS. Le postazioni da richiedere sono 1 o 3 ?
Inoltre, tenendo conto che per le operazioni su ANPR ci sono due funzionari negli uffici, vorrei sapere se  le postazioni complessive da richiedere sono 3 o 5.
Infine, per attivare alcuni servizi (solo lettura dati da ANPR, notifiche, scarico certificati) il comune potrebbe voler usare il client java reso disponibile da sogei. Con quale certificato va fatto funzionare?
Grazie

Eduardo Gira
Servizi Locali S.p.A

**Comment by gcarbonin** [comment]
Se il comune ha indicato 1, ne consideriamo comunque 2 (una per il sindaco e una per il suo delegato).
Da quanto scrive, le postazioni sono 3 (sindaco + 2 funzionari) e 3 smart card.
Possiamo partire così e una volta ricevute le smart card, il sindaco tramite console di sicurezza richiede il certificato in più.
I certificati iniziali saranno 3: 2 di postazione + 1 server che potrebbe essere quello utilizzato per il client.

**Comment by Eduardo1977** [comment]
Grazie va benissimo. Non mi è chiaro però se il funzionario deve rettificare qualcosa dal sito del CNSD, prima di procedere con il censimento (sempre dal sito CNSD).

**Comment by gcarbonin** [comment]
Al momento no. Se il comune vuole subito 4 certificati (senza richiedere il IV una volta abilitato) può variare la scheda di monitoraggio mettendo 2 al posto di 1.

**Comment by Eduardo1977** [comment]
Grazie ancora. Penso che andremo a modificare subito da 1 a 2 nella scheda monitoraggio. Se non sbaglio il Comune dovrà attendere una comunicazione tramite PEC prima di poter ritirare il "materiale" presso la Prefettura?

**Comment by gcarbonin** [comment]
E' meglio leggere le istruzioni https://www.anpr.interno.it/portale/guida-anpr : c'è  la guida completa e la guida rapida

**Comment by Eduardo1977** [comment]
Stavamo provando ad eseguire (poi abbiamo lasciato) il Censimento degli Utenti sul sito CNSD. Per il Sindaco provando ad assegnare il profilo "Sindaco", poi vengono deselezionate le altre opzioni. Cioè non è possibile assegnare anche il profilo "Amministratore Postazioni". Nel nostro caso quale profilo bisogna assegnare al Sindaco? Solo "Amministratore Postazioni" ?

**Comment by Eduardo1977** [comment]
Al punto 6 delle istruzioni ( https://www.anpr.interno.it/portale/guida-anpr ) come prima fase è indicata "Pianificazione e cronoprogramma" che prevede l'invio di una mail al Ministero dell’Interno/Sogei per definire la data di subentro. Questo passaggio serve comunque anche se l'invio (intervallo date e data preferita) è stato fatto su https://dashboard.anpr.it/subentro ?

**Comment by gcarbonin** [comment]
E' un refuso dobbiamo sistemare. La comunicazione tramite la dashboard è sufficiente: i dati da lì arrivano sia al Ministero che a noi

**Comment by Eduardo1977** [comment]
Ok grazie. Invece, se possibile per il problema su come configurare il profilo del Sindaco avrei bisogno di una risposta o di assistenza per domani, in modo da completare il Censimento delle postazioni.
Va bene anche in tarda mattinata.
Grazie

**Comment by gcarbonin** [comment]
Chiamiamo noi il suo numero?

**Comment by Eduardo1977** [comment]
Si grazie. Se vuole domattina mi può inviare una mail di preavviso, in modo che mi faccio trovare pronto appena chiamate. Basta pure 10 minuti prima. Grazie ancora.

**Comment by gcarbonin** [comment]
ok
