### ISSUE TITLE
Rettifica data matrimonio

### ISSUE THREAD

**Issue by FrancescoPipitone** [italia/anpr#3644]
Comune di Anzola dell'Emilia (037001) - produzione

Con l'operazione idANPR 1068753385 un soggetto proveniente da altro comune subentrato è entrato in famiglia con la moglie nostra residente. Il soggetto ha nella sua scheda anagrafica la data e la parte dell'atto di matrimonio sbagliate e risulta coniugato con "Nome e Cognome" della moglie, ma non corrispondente alla nostra residente in ANPR (manca idANPR e tutti i dati), mentre la scheda anagrafica di quest'ultima è corretta sia con i dati del matrimonio che con i dati del marito presenti in ANPR. Ho provato ad inviare delle mutazioni di matrimonio che vanno a buon fine, ma non modificano i dati in ANPR, Ho tentato di revocare i dati del matrimonio dalla scheda del marito, ma non riesco in quanto il subentro in ANPR non è stato effettuato dal nostro comune.
Come posso correggere i dati del matrimonio nella scheda del marito e collegarlo alla scheda ANPR della moglie?

**Comment by frmariani** [comment]
Le modifiche sui dati significativi del matrimonio (data e coniuge) vanno effettuate un'operazione alla volta: un'operazione per modificare il coniuge ed un'operazione diversa per modificare la data del matrimonio; i dati dell'atto possono essere modificati contestualmente ad una delle  due operazioni.
Mi faccia sapere

**Comment by frmariani** [comment]
Purtroppo il sistema trova entrambe le date; provi ad effettuare la modifica della data del matrimonio anche sull'altro coniuge (idanpr 96836707).
Mi faccia sapere.

**Comment by FrancescoPipitone** [comment]
Già ieri avevo provato a modificare la data sull'altro coniuge senza successo. Riprovato anche oggi su entrambi e la mutazione viene accettata senza errori dal sistema, ma la data non viene modificata.

**Comment by frmariani** [comment]
verifichiamo il problema e le faccio sapere

**Comment by frmariani** [comment]
Il problema è stato risolto; mi faccia sapere se adesso la consultazione è corretta
