### ISSUE TITLE
Errore in re-iscrizione di soggetto in ANPR come cancellato per estero

### ISSUE THREAD

**Issue by averrando** [italia/anpr#3646]
Ambiente di produzione, comune di Stelanello

Provando ad iscivere un soggetto gia presente in Anpr come cancellato per immigrazione da estero otteniamo l'errore "EN185 : idSchedaSoggettoANPR 71726223 non presente o dati anagrafici incongruenti" (id operazione ANPR 1086655417).

Potete aiutarci ?
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
il cittadino deve essere reiscritto esattamente con gli stessi dati della scheda cancellata in ANPR
stato estero di nascita URSS con codice 998
