### ISSUE TITLE
Annullamento MUTAZIONE

### ISSUE THREAD

**Issue by CHIARELLAROSSELLA** [italia/anpr#3647]
ambiente di PRODUZIONE - comune di CATANZARO (CZ) 079023

si tenta di annullare la mutazione con idOperazioneANPR  961656089 e si ottiene l'errore che segue:

"L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione tessa"

non risultano altre operazioni per la famiglia, oltre quella che si cerca di annullare.

potete verificare?

attendiamo sollecito riscontro.

Grazie
Chiarella Rossella
Comune di Catanzaro
Ufficio Anagrafe
tel. 0961881286

![Errore20221111](https://user-images.githubusercontent.com/117990765/201340385-970c8ee6-8298-43cf-9a4a-a2ebbe58798a.png)

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare a partire da domani mattina
