### ISSUE TITLE
Problema accesso ANPR

### ISSUE THREAD

**Issue by Rosanna1992** [italia/anpr#3648]
Rosanna Gambino GMBRNN92

Buonasera non riesco ad accedere al servizio Anagrafica ANPR vi allego l’errore

![a846982a-2b5d-44c1-9cb7-951a6f630f4a](https://user-images.githubusercontent.com/117103896/201352746-fec67397-7495-449a-bba6-b72dc30dbdc8.jpg)
Attendo un vostro gentile riscontro

**Comment by cmigliardi** [comment]
salve se è lei la persona nata a Palermo del febbraio 1992 - deve rivolgersi al comune di Alcamo - perché la scheda in Anpr risulta in stato di cancellazione.

**Comment by cmigliardi** [comment]
si chiude la issue
