### ISSUE TITLE
[5012] Annullamento Mutazione - Errore EN077

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3649]
ambiente di PRODUZIONE - comune di PAVULLO NEL FRIGNANO (036030)

si tenta di annullare la mutazione con idOperazioneANPR 1023667731 (ws 5005) e si ottiene l'errore che segue:

```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN077</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa</testoErroreAnomalia>
  </errore>
  <errore>
    <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2022-11-11 15:25:15 , idOperazioneANPR 1086889810</testoErroreAnomalia>
  </errore>
</listaErrori>
```

non risultano altre operazioni per la famiglia, oltre quella che si cerca di annullare.

il problema si sta manifestando con una certa frequenza, ho visto - sempre qui su gitHub - anche per altri enti non seguiti da noi.

mi sembra abbastanza importante indagare e risolvere l'anomalia, se di questo si tratta.

grazie
Alessandro Monopoli ADS

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare a partire da domani mattina
