### ISSUE TITLE
Certificazione storica in ANPR

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#365]
Utente di comune già subentrato. 
Sarebbe utile implementare sin da subito la certificazione storica di famiglia, ovviamente con storicità a partire dalla data di subentro.
In occasione dei decessi, spesso i cittadini chiedono lo stato di famiglia alla data del decesso, cioè come era composta la famiglia prima della morte di uno dei suoi componenti.

**Comment by Raffive** [comment]
Buonasera per cortesia chiaritemi cosa significa certificazione storica alla data del subentro. 
Grazie

**Comment by gcarbonin** [comment]
Forse si vuole intendere che un certificato storico con data di riferimento antecedente al subentro non si può rilasciare in quanto i dati non sono disponibili in ANPR

**Comment by Finalmentesubentrati** [comment]
Ovviamente non mi riferivo alla certificazione storica antecedente al subentro. Cerco di spiegarmi meglio.
Spesso il cittadino, ma anche forze dell'ordine e altre p.a., chiedono il certificato di stato di famiglia ad una certa data, cioè fotografare la composizione familiare ad una determinata data. Naturalmente la data storica sarebbe successiva a quella in cui il comune è subentrato.

**Comment by Raffive** [comment]
non vedo perché.
nei casi citati se il dato di iscrizione  antecedente al subentro è presente in anpr perché non posso certificarlo?

**Comment by gcarbonin** [comment]
Esempio famiglia costituita il 10-10-2015 da 4 persone
Cancellazione di due persone il 10-10-2016
Subentro del comune il 10-02-2017
Se stampassi da ANPR  lo stato di famiglia al 10-01-2016,  uscirebbe incompleto in quanto mancano le due persone cancellate non conferite al subentro

**Comment by Raffive** [comment]
mi sembra di capire che i dati per la certificazione non sono presi dai dati presenti in AP5 e conferiti.
non è possibile farlo? 
Grazie
Raffaella

**Comment by gcarbonin** [comment]
I dati storici ante-subentro rimangano presso il comune. E' previsto il loro trasferimento in ANPR soltanto in futuro. Di conseguenza le certificazioni storiche possono essere richieste soltanto per ciò che è registrato in ANPR dal subentro in poi; per il periodo precedente la certificazione spetta al comune. Sono poi previste modalità tecniche che consentono di produrre un solo certificato storico utilizzando i dati del comune per il periodo che precede il subentro e quelli di ANPR per il periodo successivo.
Lo storico dello stato di famiglia, in ogni caso, al momento non viene prodotto; è una evoluzione alla quale stiamo lavorando

**Comment by Raffive** [comment]
Grazie della precisazione, è importante conoscere cosa si può fare e cosa no.
questo ci permette di sapere dove e cosa fare per rispondere al cittadino (sempre con le certificazioni intendo)
:)
Raffaella
