### ISSUE TITLE
Problema su luogo di nascita Gerusalemme 

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#3651]
Comune di Modena

Buongiorno,
il Consolato di Gerusalemme ci chiede di iscrivere in AIRE un soggetto con luogo di nascita GERUSALEMME - stato GERUSALEMME CIRCOSCRIZIONE AUTONOMA. Alla nostra obiezione che lo stato con codice 325 può essere usato solo per la residenza e non per il luogo di nascita (come affermato nelle issue #944 e #2561) il Consolato risponde che "altri comuni non hanno riscontrato la problematica". Ci invia anche la stampa della scheda anagrafica relativa ad un iscritto AIRE del Comune di Genova riportante come stato di nascita la dicitura "GERUSALEMME CIRCOSCRIZIONE AUTONOMA"; la stampa è presumibilmente estratta dalla loro procedura di rilascio carta d' identità cartacea e con dati quasi completamente oscurati (quindi non riusciamo a verificare quale sia la reale posizione in ANPR). 
Tentiamo comunque l' iscrizione del soggetto sia da nostro applicativo sia da webapp mettendo come stato di nascita "NON ATTRIBUIBILE" con cod. 998 e descrizione "GERUSALEMME CIRCOSCRIZIONE AUTONOMA" ma in entrambi i casi otteniamo errori di questo tipo:

Errore di congruenza Codice: EAA33
Informazioni sull'operazione da fornire in caso di assistenza : data 2022-11-14 09:23:09 , idOperazioneANPR 1089502670 Codice: EN527

Potete per cortesia indicarci cosa significa esattamente l' errore EAA33 che non troviamo in documentazione e quale descrizione stato di nascita potremmo mettere per evitarlo? 
Sarebbe inoltre interessante sapere come mai il Consolato abbia a disposizione un dato che sembra contrastare con quanto ammesso in ANPR e se si prevede che prima o poi ci sia un allineamento.

Grazie, cordiali saluti
Sonia Fiorini

**Comment by ncapozzi** [comment]
Buonasera,
GERUSALEMME cod. 325 può essere utilizzato solo per la residenza. Tuttavia utilizzando il cod. stato 998 è possibile indicare nella denominazione un testo libero non presente in tabella come anche GERUSALEMME O GERUSALEMME CIRCOSCRIZIONE AUTONOMA, ma senza la validazione/attribuzione del CF da parte di Agenzia Entrate che non riconosce queste denominazioni.
