### ISSUE TITLE
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3654]
Comune di Siracusa 

Non si riesce ad annullare un cambio di indirizzo (mutazione residenza in nuova famiglia)
Non riusciamo a capire qual è l'operazione che blocca.

Errore: 

L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

ID SOGGETTO: 89449581
ID OPERAZIONE: 755557474

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare a partire da domani mattina

**Comment by jonnyfx95** [comment]
Grazie, riproverò domani mattina.
Per comunità non è possibile mettere l'ID ANPR dell'operazione successiva nel messaggio di errore?
Spesso capita di non riuscire a trovare la pratica, avendo l'ID dell'operazione bloccante sarebbe più pratico e veloce gestire queste casistiche
