### ISSUE TITLE
Errore Rigetto Mutazione Famiglia

### ISSUE THREAD

**Issue by averrando** [italia/anpr#3656]
Comune di Vado Ligure
Tentando di rigettare una mutazione di famiglia otteniamo l'errore EN077.
Verificando non abbiamo trovato variazioni successive alla pratica che si sta rigettando.
Potete aiutarci?
IdOperazioneANPR 1091829949

Grazie mille

**Comment by ncapozzi** [comment]
Buongiorno
potete riprovare ad eseguire l'operazione.
