### ISSUE TITLE
[Tabella 31] - Refuso note nella documentazione online

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#366]
Buongiorno,
nella pagina della documentazione online relativa alla tabella 31 (https://anpr.readthedocs.io/it/latest/tab/tab_tipo_cessazione_matrimonio.html) appena dopo il titolo si vede: "**Note: Per i valori da 1 a 4 occorre indicare:**". E' un refuso o manca qualcosa?
Grazie

Eduardo Gira
Servizi Locali S.p.A.

**Comment by mccalv** [comment]
Caro @Eduardo1977 abbiamo sistemato, era un bug nel processo che prende tutti i contenuti tecnici del portale anpr.interno.it e li trasporta sulla piattaforma ReadTheDocs. 
Abbiamo anche provveduto ad aggiornare tutta la documentazione.

**Comment by Eduardo1977** [comment]
Grazie ... direi che sono venute fuori una valanga di specifiche in più. Evviva
