### ISSUE TITLE
Come "svalidare" un codice fiscale già marcato/validato ANPR?

### ISSUE THREAD

**Issue by mlanzilotti** [italia/anpr#3660]
Salve, 
Comune San Vito dei Normanni - Produzione.

Nel procedere con una mutazione tutti dati per il soggetto ID ANPR 86126686, si riscontra l'impossibilità di finalizzare il procedimento in quanto "Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)" (data 2022-11-16 17:15:01 , idOperazioneANPR 1093327505 (Codice: EN527).

Si è pensato di procedere con mutazione tutti dati in quanto, all'atto di risoluzione dei disallineamenti con Agenzia delle Entrate confermando i dati AE e collegando i due codici, l'esito era sempre negativo poichè il codice fiscale non risultava variato (stesso errore: Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12))

Come si può procedere?
Grazie

**Comment by ncapozzi** [comment]
Buonasera,
potete trovare per favore ad effettuare nuovamente il 5008? Restiamo in attesa di riscontro. Grazie

**Comment by mlanzilotti** [comment]
Risolto: siamo riusciti tramite mutazione tutti dati e lasciando il campo mutazione codice fiscale=0. Grazie mille!
