### ISSUE TITLE
RETTIFICA DATA DECORRENZA RESIDENZA 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3661]
Buongiorno,
Quali sono le procedure da utilizzare per rettificare la data di decorrenza residenza in questi casi:
1) iscritto da subentro mai modificata
2) iscritto per cambio residenza da altro comune
3) modificata per cambio residenza stesso comune

Grazie

**Comment by paoloHV** [comment]
per il caso solo un tecnico SOGEI credo possa farlo

per il 2 e il 3 vanno annullate tutte le operazioni di mutazione, in ordine dalla più recente alla più vecchia (da registrazione- annullamento mutazione, gli ID operazioni si trovano dalla consultazione scheda-elenco operazione).
attenzione solo che l'annullamento del caso 2 solitamente genera una notifica di ripristino per il precedente comune.

**Comment by ncapozzi** [comment]
Buonasera
per il caso 1 si può utilizzare il servizio di rettifica purché non siano state eseguite altre operazioni dopo il subentro.
