### ISSUE TITLE
Codici fiscali da collegare

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#3662]
Buongiorno,
abbiamo iscritto per ricomparsa da altro Comune una cittadina bulgara, non presente in ANPR (il precedente Comune l'aveva cancellata prima del subentro). La signora era in possesso di codice fiscale con un nome solo ma da carta bulgara i nomi sono due. Abbiamo quindi fatto l'iscrizione con i due nomi chiedendo l'attribuzione del codice fiscale. 
Volevamo poi unire il cf creato da noi (che risulta validato e marcato) al cf precedente (che risulta validato ma NON marcato) ma non ce lo permette. L'errore che restituisce è "Soggetto non rettificabile perchè in lavorazione per risoluzione omocodia (Codice 96)". Prima dell'attribuzione, avevamo verificato e in AE con i dati anagrafici nuovi (cioè i due nomi) non c'era nessun cf. Quale può essere il problema? Grazie
cordiali saluti
Katia Vacchi

**Comment by ncapozzi** [comment]
Buonasera,
per le verifiche necessario sarebbe necessario conoscere i dati anagrafici del cittadino che non possono essere indicati in questo canale. Inoltre sarà necessario effettuare delle operazioni in assistenza tele fonica. Pertanto si suggerisce di contattare il n. verde 800863116.
Grazie
