### ISSUE TITLE
Errore EN469 - doppia iscrizione

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3664]
Buongiorno.
Dovremmo registrare una variazione di paternità e maternità per soggetto ID ANPR 85380349
Viene restituito errore EN469 ma effettuando una visura risulta che il "duplicato" (ID 87845075) sia cancellato.
ID operazione 1099954136 
Cordiali saluti

**Comment by ncapozzi** [comment]
Buonasera
potete riprovare ad eseguire l'operazione.
Grazie
