### ISSUE TITLE
Non è possibile inviare una nuova dichiarazione di residenza se non si è concluso l'iter della dichiarazione precedentemente inviata github

### ISSUE THREAD

**Issue by aliqasimmm** [italia/anpr#3666]
Salve, 
Mi esce questo errore quando cerco di fare il cambio residenza per qualcun altro o anche per me stesso e non riesco a trovare una soluzione: "**_Non è possibile inviare una nuova dichiarazione di residenza se non si è concluso l'iter della dichiarazione precedentemente inviata_**"
Questo è il numero della domanda sul sito: 27463589
Sul sito risulta che la domanda è "IN LAVORAZIONE", ma non è cosi perché il mio cambio di residenza è già stato effettuato.
Se avete soluzioni, attendo vostro cortese riscontro.
Grazie
PS. vi allego la foto

![image](https://user-images.githubusercontent.com/117117532/203570298-cb3abdef-938a-4a1f-b776-664f1e41e841.png)

**Comment by ncapozzi** [comment]
Buonasera,
il cambio di residenza deve essere effettuato dal Comune entro due giorni dal ricevimento della pratica (stato IN LAVORAZIONE -> ACCOLTA CON RISERVA). Poi scattano 45 giorni per l'accertamento  prima della chiusura definitiva. (stato finale ACCOLTA DEFINITIVAMENTE)

**Comment by aliqasimmm** [comment]
Salve,
La richiesta per il cambio residenza l'ho fatta nel mese di Giugno 2022, e sono passati piu di 45 giorni. Quindi non penso che sia quello il problema. Fatemi sapere se dovrei recarmi in Comune direttamente.
Grazie, 
Salut

**Comment by ncapozzi** [comment]
Buongiorno
le suggeriamo di contattare il Comune interessato, non le sappiamo dire se deve recarsi di persona presso l'Anagrafe.
