### ISSUE TITLE
CIE non registrata in ANPR

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#367]
Comune di Altamura subentrato da 2 giorni.
Ho scoperto che le CIE rilasciate dopo il subentro non sono registrate in ANPR. 
Ma come è possibile?

**Comment by gcarbonin** [comment]
I dati delle CIE emesse sono aggiornati in differita attualmente: quelle emesse oggi le troverà da domani

**Comment by gcarbonin** [comment]
Ha avuto modo di verificare?

**Comment by Finalmentesubentrati** [comment]
Nessuna CIE emessa a partire dalla data di subentro (17/10/2017) risulta registrata in ANPR.
La verifica viene fatta da: Consultazione Scheda Individuale<<Documenti del Cittadino, dove risulta ancora la vecchia carta cartacea, cioè il dato inviato con il subentro.

**Comment by cmigliardi** [comment]
Le CIE sono state recuperate.
