### ISSUE TITLE
Iscrizione AIRE anno 2020 

### ISSUE THREAD

**Issue by DANIELAPIERGIOVANNI71** [italia/anpr#3674]
Buongiorno, ci siamo accorti che una cittadina AIRE non risulta transitata in ANPR. Abbiamo cercato di iscriverla manualmente ma ci sono problemi con la data di decorrenza. La persona deve essere inserita nella famiglia del marito ( identificativo famiglia anpr 47536267) che però ha una data decorrenza iscrizione successiva alla data di iscrizione della moglie. 
Di seguito ID operazione ANPR.
data 2022-11-28 16:00:02 , idOperazioneANPR 1108181558 Codice: EN527

Come possiamo procedere?

Grazie

Daniela Piergiovanni - comune di Burago di Molgora.

**Comment by ncapozzi** [comment]
Buonasera
la data decorrenza di iscrizione AIRE del marito è 31/01/2020 mentre quella della moglie è 30/01/2020. Una delle due è sbagliata?

**Comment by DANIELAPIERGIOVANNI71** [comment]
***@***.***

Mi esce questo errore quando provo ad aggiornare.

grazie


Dr.ssa Daniela Piergiovanni

Ufficio Demografici
Comune di Burago di Molgora (Mb)
039-69903.222

***@***.***

Da: ncapozzi ***@***.***
Inviato: mercoledì 30 novembre 2022 16:19
A: italia/anpr ***@***.***>
Cc: Daniela Piergiovanni ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] Iscrizione AIRE anno 2020 (Issue #3674)


Buonasera
la data decorrenza di iscrizione AIRE del marito è 31/01/2020 mentre quella della moglie è 30/01/2020. Una delle due è sbagliata?

**Comment by ncapozzi** [comment]
Verificato con l'utente che era sbagliata la data iscrizione AIRE del marito e fornita assistenza per annullare la mutazione e rieseguirla alla data corretta
