### ISSUE TITLE
Matrimonio - dati coniuge mancanti

### ISSUE THREAD

**Issue by DANIELAPIERGIOVANNI71** [italia/anpr#3675]
Buongiorno
il soggetto identificativo anpr 78782128 ha il nome del coniuge assente, e con l'idea di correggere tale info, vorremmo approfittare e collegarlo con la moglie con il codice fiscale (soggetto identificativo anpr 78782116).
Nell'eseguire l'operazione però ci blocca dicendo che il soggetto ha già un matrimonio (infatti è proprio quello che dobbiamo correggere).
Come possiamo fare?
Vi ringrazio per il vostro aiuto.
Daniela Piergiovanni
Comune di Burago di Molgora

**Comment by frmariani** [comment]
entrambi i coniugi sono carenti del nome del rispettivo coniuge, pertanto la modifica almeno del nome deve essere effettuata su entrambi; successivamente, con una terza operazione potrà essere effettuata l'operazione di riconciliazione con CF anche soltanto su uno dei due coniugi.
Esegua le tre operazioni e mi faccia sapere

**Comment by DANIELAPIERGIOVANNI71** [comment]
Buongiorno, non riusciamo a fare la modifica del nome. Il problema è proprio quello.

Grazie

Dr.ssa Daniela Piergiovanni

Ufficio Demografici
Comune di Burago di Molgora (Mb)
039-69903.222

***@***.***

Da: frmariani ***@***.***
Inviato: mercoledì 30 novembre 2022 14:43
A: italia/anpr ***@***.***>
Cc: Daniela Piergiovanni ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] Matrimonio - dati coniuge mancanti (Issue #3675)


entrambi i coniugi sono carenti del nome del rispettivo coniuge, pertanto la modifica almeno del nome deve essere effettuata su entrambi; successivamente, con una terza operazione potrà essere effettuata l'operazione di riconciliazione con CF anche soltanto su uno dei due coniugi.
Esegua le tre operazioni e mi faccia sapere

**Comment by frmariani** [comment]
gentilmente inserisca il nome soltanto ad uno dei due coniugi e mi mandi l'idoperazione anpr di questa operazione fallita.
Grazie

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
