### ISSUE TITLE
Dati elettorali su ANPR

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3676]
Buonasera, é' possibile avere file xml di esempio per subentro e servizi  5011 e 5010?
Grazie

**Comment by amollicone1982** [comment]
Salve, può trovare gli xsd che descrivono l'xml sul portale ANPR.

**Comment by rinonasti** [comment]
Se potessi averli Le sarei molto grato.

**Comment by amollicone1982** [comment]
[xsd.Subentro.Liste.elettorali.zip](https://github.com/italia/anpr/files/10135014/xsd.Subentro.Liste.elettorali.zip)

**Comment by amollicone1982** [comment]
Eccoli. Buona serata

**Comment by rinonasti** [comment]
C'è un xml validator ?
Grazie

**Comment by amollicone1982** [comment]
Non c'e'. Puo' sfruttarre un qualsiasi validatore online o scritto da lei in qualsiasi linguaggio
