### ISSUE TITLE
[1002] msg. "Operazione non effettuabile"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#368]
ambiente di pre-subentro - comune di Faenza

da ieri ci stiamo imbattendo in comunicazioni di iscrizione che non vanno a buon fine a causa del messaggio "operazione non effettuabile" (da ieri capitato su almeno 3 comunicazioni)

poi, con svariati tentativi di ripetizione, l'invio va a buon fine.

nell'ultimo caso la comunicazione è andata al quarto tentativo
(rif. idOperazioneComune 2017300254, 2017300255, 2017300256 in errore, poi ripetuta con successo con id 2017300257)

come spiegare al cliente quello che deve fare in questi casi?
attendere? ripetere ad oltranza?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Nel caso specifico si tratta di un problema di comunicazione con il sistema dell'Agenzia delle Entrate (si riconosce dalla sigla AEExx) e in particolare, sulla porta di dominio.  Stiamo verificando il motivo.
Se l'interesse del cliente non è quello di verificare la validità di un codice fiscale (operazione che in pre-subentro va sempre male) o chiederne l'attribuzione ma quello di provare le operazioni anagrafiche, è sufficiente indicare 3 nel campo gestioneCF.
