### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio - Gabriele

### ISSUE THREAD

**Issue by dedehome77** [italia/anpr#3681]
Buongiorno,
    entrando nel sito ANPR con SPID mi da l'errore di cui in oggetto

CF: GRVGRL77S27M109Z

Come posso risolvere?

Grazie per l'attenzione.

Gabriele Gravaghi

**Comment by cmigliardi** [comment]
salve se è lei la persona nata in novembre del 1977 . si deve rivolgere al suo comune di competenza   Voghera per far validare in Anpr   il suo codice fiscale.

**Comment by cmigliardi** [comment]
si chiude la issue
