### ISSUE TITLE
Richiesta aperta da un mese ma ancora non processata

### ISSUE THREAD

**Issue by iJaack** [italia/anpr#3683]
Non so a chi chiedere, né come, quindi apro una segnalazione qui.

Ho fatto una richiesta di cambio residenza il giorno 05/11/2022, e ancora risulta aperta. Sul sito dell'ANPR leggo che le procedure per cambio di residenza dovrebbero essere elaborare in 2-3 giorni lavorativi.

C'è qualcosa che ho sbagliato? Come faccio a far procedere la richiesta?

Grazie mille anticipatamente.

**Comment by ncapozzi** [comment]
Buongiorno,
il cambio di residenza deve essere effettuato dal Comune entro due giorni dal ricevimento della pratica (stato IN LAVORAZIONE -> ACCOLTA CON RISERVA). Poi scattano 45 giorni per l'accertamento prima della chiusura definitiva. (stato finale ACCOLTA DEFINITIVAMENTE). Per eventuali informazioni sullo stato di lavorazione della pratica le suggeriamo di contattare il Comune interessato.
