### ISSUE TITLE
Errore CAST Assegnazione ruoli

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#3687]
Buonasera,
Comune di CASERTA
Come ALS abbiamo spuntato la voce ELETTORALE per gli utenti interessati. Tutto OK modifica effettuata correttamente.
Se si esegue sull'utente ALS  "Errore CAST Assegnazione ruoli"

**Comment by Leonforte** [comment]
Buongiorno, la problematica dovrebbe essere rientrata, potete riprovare, grazie

**Comment by rinonasti** [comment]
Ok funziona 
Grazie

**Comment by Fausta71** [comment]
buongiorno,
sono ALS per il comune di Lomazzo e ad oggi effettuando la stessa operando sulla mia smartcard compare ancora il messaggio di errore.
Grazie
