### ISSUE TITLE
Aggiornamento SW in ambiente di esercizio

### ISSUE THREAD

**Issue by gcarbonin** [italia/anpr#369]
Dal prossimo 24 ottobre, saranno disponibili in ambiente di esercizio le funzionalità della Web Application che consentono di:
•	indicare la data di decorrenza della residenza non trasmessa al momento del subentro;
•	modificare la data di prima iscrizione nel comune se successiva a quella di decorrenza della residenza indicata al momento del  subentro;
•	modificare il motivo di iscrizione.
Contestualmente, saranno attivati i controlli che non consentono la stampa del certificato storico di residenza quando la data di decorrenza della residenza non è stata indicata al momento del subentro o non è congruente con la data di prima iscrizione nel comune.
Sono stati attivati, inoltre, due controlli sulle cancellazioni anagrafiche: 
•	la cancellazione non può essere retroattiva (ad esempio, subentro del comune 10-10-2017; cancellazione per emigrazione in comune non subentrato con decorrenza 8-10-2017);
•	la cancellazione e l’iscrizione non sono consentite se il comune, rispettivamente,  di destinazione o di provenienza è subentrato.

**Comment by gcarbonin** [comment]
Aggiornamento (parte evidenziata in grassetto)
Dal prossimo 24 ottobre, saranno disponibili in ambiente di esercizio le funzionalità della Web Application che consentono di:
•	indicare la data di decorrenza della residenza non trasmessa al momento del subentro;
•	**modificare la data  di decorrenza della residenza indicata al momento del subentro se inferiore alla data di prima iscrizione nel comune** ;
•	modificare il motivo di iscrizione.
Contestualmente, saranno attivati i controlli che non consentono la stampa del certificato storico di residenza quando la data di decorrenza della residenza non è stata indicata al momento del subentro o non è congruente con la data di prima iscrizione nel comune.
Sono stati attivati, inoltre, due controlli sulle cancellazioni anagrafiche:
•	la cancellazione non può essere retroattiva (ad esempio, subentro del comune 10-10-2017; cancellazione per emigrazione in comune non subentrato con decorrenza 8-10-2017);
•	la cancellazione e l’iscrizione non sono consentite se il comune, rispettivamente, di destinazione o di provenienza è subentrato.

**Comment by AMonopoliADS** [comment]
buongiorno.
in riferimento alla "modifica del motivo di iscrizione": la funzionalità è ancora disponibile solo su web-app? oppure è possibile procedere con la stessa operazione anche via web-service?
grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Ancora solo via WA. Chiediamo di non commentare le issue classificate come AVVISI ma di inserirne un'altra.
