### ISSUE TITLE
CAMPO GALLIANO 5008 - FLVerificaSincroniaANPRlistaelettorale  In Errore

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#3691]
Buongiorno

Richieste WS Schedulate presso Comune di Campogalliano (MO) 
Effettuiamo diverse chiamate verso ANPR di tipo 5008 con tipo mutazione = FLVerificaSincroniaANPRlistaelettorale
per ciascuna di esse riceviamo il messaggio : 
Cient received SOAP Fault from server: Rejected by policy. (from client) 
Please see the server log to find more detail regarding exact cause of the failure.

Potete analizzare vs. log e specificarci la natura del  rejected . 

Grazie Dona'

338 59 09 376

**Comment by edoardodona-1** [comment]
Mi correggo: e' un 5008 con tipo mutazione = 5.

**Comment by frmariani** [comment]
Ha verificato la validazione? nel caso mi alleghi l'xml

**Comment by edoardodona-1** [comment]
Noi prima della 5008 mandiamo una 3002 e gia' questa gia' falliva ... abbiamo poi ipotizzato che si trattasse del CF del nostro messaggio ed effettivamente cosi' era. Pertanto potete chiudere il ticket. 
Ora tutto ok .
Grazie
