### ISSUE TITLE
[ws 6001 / 5010] Nuovi dati elettorali - Soggetto cancellato da ANPR

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3694]
ambiente di TEST - comune di FAENZA (039010)

idSoggettoANPR 117938909

soggetto iscritto in AIRE per il quale sono stati inviati i dati di iscrizione nelle liste elettorali con ws 5010 (idOperazioneANPR 54984315)
i dati sono visibili alla consultazione ed è possibile ottenere la certificazione.

in seguito alla cancellazione dall'AIRE per perdita cittadinanza italiana - ma prima dell'invio della cancellazione dalle liste elettorali - non risulta più disponibile la certificazione a motivo di questo messaggio:
```
<errore>
<codiceErroreAnomalia>EN229</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Il certificato non puo' essere emesso in quanto il soggetto e' stato cancellato da ANPR</testoErroreAnomalia>
</errore>
```

mi sarei aspettato di potere richiedere almeno il certificato di godimento diritti politici, visto che l'ufficio elettorale non l'ha ancora cancellato.

procedo comunque con una revisione straordinaria ed invio la mutazione 5010 di cancellazione (idOperazioneANPR 54985151) ed il web-service mi risponde con l'errore:
```
<errore>
<codiceErroreAnomalia>EN413</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Il soggetto risulta cancellato</testoErroreAnomalia>
</errore>
```

ho simulato il caso che ponevo questa mattina.
se ho frainteso quale dovrebbe essere il processo giusto, vi chiedo di chiarirmelo.

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Ciao Alessandro,
sicuramente sono io che non ho compreso correttamente la tua domanda; al momento, per un cittadino cancellato da ANPR non è possibile emettere dei certificati elettorali. 
Invece la cancellazione dalle liste dopo la cancellazione da ANPR del cittadino avrebbe dovuto essere permessa e stiamo verificando il problema.
Comunque ho chiesto chiarimenti al Ministero in merito  ad entrambe le problematiche e ti farò sapere.

**Comment by AMonopoliADS** [comment]
giusto x completezza, ti segnalo che la stessa situazione si presenta a chiusura di semestrale, trattando un soggetto cancellato anagraficamente per irreperibilità, e per il quale si tenta di inviare la cancellazione dalle liste elettorali per lo stesso motivo.
esempio idSoggettoANPR 117938923

**Comment by frmariani** [comment]
grazie per la segnalazione, ma il controllo scatta erroneamente per tutti i cittadini cancellati in ANPR, a prescindere dalla motivazione della cancellazione.

**Comment by frmariani** [comment]
Il Ministero ci h confermato che per un cittadino cancellato da ANPR non è possibile emettere i certificati elettorali, a prescindere dalla motivazione della cancellazione.
Confermo che la cancellazione dalle liste elettorali è possibile anche dopo la cancellazione del cittadino da ANPR.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
