### ISSUE TITLE
Errore acesso al portale: Purtroppo non is stato possibile accedere al servizio

### ISSUE THREAD

**Issue by bcma21** [italia/anpr#3698]
Ciao,

Non siamo riusciti ad accedere al portale, ora appare questo mensaggio di errore: "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Non ci sono problemi con la scheda anagrafica in fast it e possiamo accedere normalmente anche con SPID Agenzia Entrate. 

Cosa possiamo fare?

CF: CMPNGL
CF: CMPRTR
Jesolo (VE)

**Comment by cmigliardi** [comment]
salve - 1) se è lei la persona nata a gennaio del 1959 - si deve rivolgere al comune    perché in ANPR   la sua scheda è  assente    2)    se è lei la persona  nata nel marzo 1975  risulta residente a roccella jonica - si rivolga comunque al suo comune.

**Comment by cmigliardi** [comment]
non trovo nessun codice fiscale   nato  ottobre  87

**Comment by cmigliardi** [comment]
non avendo ricevutoa ltre info chiudo la issue
