### ISSUE TITLE
Web App - Cause ostative all'espatrio

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#37]
Al momento tra gli attributi del soggetto non è prevista una sezione dedicata alla "presenza di cause ostative all'espatrio".
All'occorrenza la Questura segnala agli uffici anagrafici l'apposizione del timbro "non valida all'espatrio" sulle carta d'identità rilasciate dal Comune stesso e, contestualmente, l'esistenza di una causa ostativa all'espatrio di durata indeterminata o temporanea (in quest'ultimo caso ne specifica anche la durata).
Ad oggi queste segnalazioni vengono gestite con l'inserimento tramite il ns. gestionale del cosiddetto "Blocco CINVE" che impedisce l'emissione di una carta d'identità valida all'espatrio, salvo rimozione del blocco stesso. Tale situazione non può essere gestita con i blocchi di certificabilità attualmente presenti in ANPR perchè agiscono su altri aspetti del cittadino (in pratica, un cittadino che non può espatriare, salvo problematiche di altra natura, può richiedere qualsiasi certificazione).
Nell'ottica del subentro di tutti i Comuni in ANPR sarebbe molto utile gestire anche questa informazione, in quanto si presume che in futuro non sarà più necessario richiedere al Comune di residenza il nulla osta al rilascio della carta d'identità per i cittadini temporaneamente domiciliati sul territorio comunale (ad oggi nei nulla osta si dà anche atto della presenza o meno di cause ostative all'espatrio).
Per completezza, segnalo che al momento questa informazione viene gestita anche dal sistema CIE ONLINE attraverso l'acquisizione dell'informazione dall'APR locale tramite la componente SAD.
Per agevolare i grandi Comuni, sarebbe utile gestire l'informazione sia tramite Web App che Web Services.

Verificato su Ambiente di test il 20/03/2017
Valentina Bocchino - Città di Torino

**Comment by gcarbonin** [comment]
E' tra gli interventi evolutivi di prossima attuazione.

**Comment by AMonopoliADS** [comment]
buonasera.
ci sono state evoluzioni riguardo il tema posto con questa issue?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
E' una evoluzione del sistema cieonline e non di ANPR in quanto non si tratta di un dato anagrafico (per questo motivo non è previsto)

**Comment by RBiasi** [comment]
Buongiorno,

per quanto riguarda l'emissione delle CI cartacee?

Grazie

**Comment by FERRETTI-LAURA** [comment]
Ci sono aggiornamenti riguardo alla gestione delle cause ostative? Sul sistema CIE on line non è stata implementata alcuna gestione ad oggi e comunque come già fatto notare bisognerebbe anche tener conto dell'emissione delle CI cartacee.
Grazie
Laura Ferretti
