### ISSUE TITLE
Aire: ISCRIZIONE PER NASCITA

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3701]
Buongiorno,
il Consolato di Nizza ci invia trascrizione atto di nascita e quindi CONS.01 di un bimbo la cui mamma è nostra residente. Cerchiamo di iscrivere il bimbo per "iscrizione per nascita aire" con decorrenza giuridica dalla nascita (14/09/2022) e con richiesta attribuzione CF (in famiglia esistente "id famiglia anpr 41536923").
Nel salvare la pratica ci esce l'errore: "La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata Codice: EN237 " non capiamo il senso visto che il bambino non è presente in anpr e quindi non ha movimenti.
Incolliamo di seguito l'id operazione per assistenza:
data 2022-12-14 09:04:14 , idOperazioneANPR 1124965797 Codice: EN527.
Vi ringraziamo fin da ora per il vostro cortese aiuto.
Andrea Formenti
Comune di Caponago.

**Comment by ncapozzi** [comment]
Buongiorno
la data di decorrenza dell'attuale residenza della famiglia è 27/10/2022 quindi non potete iscrivere il bambino ad una data precedente (id operazione 1080656040). Se il bambino deve essere iscritto ad una data precedente dovete annullare la mutazione di residenza id 1080656040, iscrivere il bambino e poi rifare la mutazione di residenza.
