### ISSUE TITLE
Urgente - Svalidare codice fiscale già validato su ANPR

### ISSUE THREAD

**Issue by mlanzilotti** [italia/anpr#3704]
Salve,
Comune di San Vito dei Normanni - Produzione.

Avremmo bisogno di svalidare CF del soggetto ANPR : 94214385 per errore nella data di nascita (corretta: 10/09/2020).

Al momento dell'allineamento dei dati ANPR e Agenzia delle Entrate, dovendo confermare i dati di Agenzia delle Entrate, compare errore:
Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12)

Avremmo bisogno di svalidare CF del soggetto ANPR : 94214385 per errore nella data di nascita (corretta: 10/09/2020).

Dettagli errore dopo Registrazione>Mutazione tutti dati>Operazione d'ufficio:
Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)
idOperazioneANPR 1127329585 (Codice: EN527)

Grazie

**Comment by ncapozzi** [comment]
Buonasera, 
potete ripetere la mutazione aggiornando sia la data di nascita che il corrispondente CF che è già stato assegnato da Agenzia delle Entrate come potete verificare dalla web app di ANPR/Consultazione AE
