### ISSUE TITLE
ELENCO UNICO 2021: ANOMALIE AIRE - SOGGETTI SCARTATI NELL'ELENCO UNICO

### ISSUE THREAD

**Issue by marcomainenti** [italia/anpr#3706]
A seguito della Circolare 116/2022 DAIT abbiamo provveduto a scaricare dalla web app ANPR gli elenchi dei nominativi AIRE che presentano delle anomalie.
Nell'elenco 'AIRE Elenco Unico - Soggetti scartati nell'elenco unico' ci viene segnalata un'anomalia per un soggetto (ID ANPR 42781575). Nel file excel collegato all'anomalia, sotto la colonna descrizione, è presente la dicitura 'Duplicazione min'.

Non riscontriamo nessun tipo di anomalia per il soggetto in questione, considerando tutti i tipi di anomalie elencate nella circolare ministeriale.
Abbiamo già provveduto a contattare SOGEI. L'operatore ci ha suggerito di controllare le doppie posizioni.
Di fatto in ANPR non risultano doppie posizioni, ma è presente un altro nominativo (ID ANPR 101784158), anch'esso iscritto AIRE ma presso un altro Comune, che presenta eguale cognome, nome e data di nascita (ma luogo di nascita differente). 

Chiediamo conferma riguardo il fatto che:
- non risultano anomalie per il soggetto di nostra competenza (ID ANPR 42781575);
- non risultano essere presenti doppie posizioni (i due soggetti sono distinti, dato il diverso luogo di nascita);
- il soggetto da correggere sembrerebbe essere solo il nominativo AIRE dell'altro comune (manca il codice fiscale) ed è stata erroneamente notificata un'anomalia al nostro Comune.

Chiediamo inoltre, qualora ne siate a conoscenza se i 'Soggetti scartati nell'elenco unico' identifichino una specifica anomalia 

--
Marco Mainenti
 
Comune di Segrate
Sezione Servizi Demografici e al Cittadino
Ufficio Anagrafe Back-office

**Comment by ncapozzi** [comment]
Buongiorno
quando sono stati elaborati i nuovi elenchi anomalie citati nella Circolare 116/2022 DAIT, inizialmente non erano stati cancellati quelli elaborati nel 2021. Questi ultimi sono stati cancellati il 6/12 quindi attualmente per il Comune di Segrate è presente solo l'elenco delle posizioni con tipo elettore null contenente una sola posizione che nel frattempo è stata sanata.
