### ISSUE TITLE
[Subentro] File APR: Residenza

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#371]
Ricontrollando le specifiche dell'oggetto Residenza, mi è venuto un lieve dubbio sul significato che potrebbe assumere "dataDecorrenzaResidenza". Ovviamente, finora l'ho intesa come la data a partire dalla quale il cittadino risiede all'indirizzo specificato (cioè l'attuale, nel caso ne avesse cambiati diversi). 
Nel caso di un cittadino iscritto per nascita che ha variato diverse volte indirizzo, va riportata la data (evento, giuridica) relativa all'ultimo indirizzo (attuale). Giusto?
Siccome vedo diverse discussioni in merito alle date, non dò niente per scontato e chiedo conferma. Grazie
Eduardo Gira

**Comment by gcarbonin** [comment]
E' la data della dichiarazione anagrafica associata alla residenza. Al subentro si deve trasmettere la residenza attuale con la sua data di decorrenza
