### ISSUE TITLE
Accesso negato anagrafe digitale

### ISSUE THREAD

**Issue by Jeronmathew** [italia/anpr#3711]
Buongiorno io ho riscontrato lo stesso problema provando ad entrare all interni del sito mi da questo codice errore 
 Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni
Premetto che il mio comune di residenza e Roma è che risulta iscritto all anagrafe però ogni volto che provo ad entrare mi da questo errore il codice fiscale è valido perché sul sito della agenzie delle entrate risulta valido 
Potreste darmi una mano (i primi 6 caratteri del codice fiscale sono MNCNJN)
Grazie e spero che possiate risolvere questo problema 

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by cmigliardi** [comment]
salve tra i tentativi falliti troviamo solo una persona nata nel 2000 , non so se è Lei - se sì il codice fiscale è assente in ANPR, altrimenti ci dia altri elementi del codice fiscale. grazie

**Comment by Jeronmathew** [comment]
Buongiorno volevo prima di tutto ringraziarla per la risposta ottenuta 
Le do tutto il mio codice fiscale 
MNCNJN00D70Z222G
Nata nel 2000 in India per privacy magari non metto in questa sede nome e cognome,
Per quanto riguarda il codice fiscale sul sito dell agenzia delle entrate risulta valido 
Grazie mille per l’attenzione vi auguro una buona giornata

**Comment by Jeronmathew** [comment]
Un ultima cosa qualora il mio codice fiscale sia assente in ANPR come dovrei procedere?
Grazie

**Comment by cmigliardi** [comment]
le confermo che in Anpr il suo codice fiscale non c'è.  è presente in agenzia delle entrate con residenza Roma - resto generica nel rispetto della privacy.   dovrebbe recarsi al suo municipio e far verificare la situazione e correggerla.  spero di esserle stata di ausilio

**Comment by Jeronmathew** [comment]
Grazie mille per la risposta 
Essendo non pratica di queste cose le vorrei chiedere, mi reco presso il mio municipio di residenza e precisamente cosa dovrei chiedere ?
Inoltre si la mia residenza e a Roma ( vorrei chiedere se era possibile mi saprebbe dire in quale via risulta la mia residenza, mi spiego meglio avevo fatto cambio di residenza circa due mesi fa naturalmente non ho ricevuto nessuna risposta da parte del municipio e pure se voglio andare a controllare sul sito ANPR non mi fa entrare, naturalmente do il mio consenso per scrivere su questa piattaforma l’indirizzo completo ) attualmente sono residente in Via dei faggi 43 int 13 Roma zona Centocelle mi può dare conferma di questo indirizzo?
Grazie mille

**Comment by cmigliardi** [comment]
in agenzia entrate risulta una via diversa.  vada  al municipio - sezione anagrafe  e chieda di controllare la sua situazione . ogni municipio può lavorare   in Anpr  - vada in quello più vicino

**Comment by Jeronmathew** [comment]
La ringrazio per la risposta 
Perché quasi due mesi fa avevo fatto tutto il procedimento per il cambio di residenza a Roma senza fino ad oggi nessun riscontro 
Perché sul sito di Roma capitale mi fa entrare ma la pratica risulta solamente inserita senza nessun progresso da due mesi
Quindi  non so cosa potrei fare

**Comment by cmigliardi** [comment]
io non so dirle la situazione al comune di Roma - io ho visibilità solo in agenzia entrate e in Anpr - deve recarsi al municipio . sezione anagrafe

**Comment by cmigliardi** [comment]
chiudo la issue
