### ISSUE TITLE
2683

### ISSUE THREAD

**Issue by Patriciahilaria** [italia/anpr#3712]
Ciao ho problemi ad accedere ANPR

sono Patricia hilaría scalia flores 

Codice SCLPRC

**Comment by cmigliardi** [comment]
se è lei la persona nata a marzo del 1995 - i n Anpr   la scheda risulta cancellata da Catania -  le consiglio di recarsi  in comune - sezione anagrafe e far verificare la sua situazione in Anpr.

**Comment by Patriciahilaria** [comment]
Senza residenza non posso accedere?

Il giorno mer 21 dic 2022 alle 13:03 cmigliardi ***@***.***>
ha scritto:

**Comment by cmigliardi** [comment]
no

**Comment by cmigliardi** [comment]
sono dati riservati - si rechi in comune - grazie

**Comment by cmigliardi** [comment]
si chiude la issue
