### ISSUE TITLE
Operazione non effettuabile AE 

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3713]
Interrogando un qualsiasi CF nella sezione Consultazione AE riporta il seguente errore: 

ESITO AE: OPERAZIONE NON EFFETTUABILE
Errore riscontrato anche in fase di iscrizione altri motivi con nessuna operazione sul codice fiscale

Potete verificare?

**Comment by sfmodena** [comment]
Buongiorno,
stessi problemi anche a Modena.

Saluti
Sonia Fiorini

**Comment by paoloHV** [comment]
Stesso errore in Veneto per i nostri clienti

**Comment by siscomanpr** [comment]
Buongiorno,
lo stesso errore viene segnalato dai nostri clienti

**Comment by UpiTorino** [comment]
Buongiorno,
stesso errore sia operando da Sicra sia operando da WEB APP

UPI Torino

**Comment by ncapozzi** [comment]
Buongiorno,
il problema segnalato è stato risolto
