### ISSUE TITLE
[5010] Subentro Liste Elettorali

### ISSUE THREAD

**Issue by RenatoFumarola** [italia/anpr#3714]
Buongiorno,
    sono Renato Fumarola di Maggioli Spa, e vorrei sapere se per quanto riguarda il file di Subentro dei Dati Elettorali è possibile generare più file in modo da fare diversi upload: si potrebbe utilizzare il campo versioneFornitura come progressivo per esempio?
Abbiamo Comuni di grosse dimensioni con un numero di elettori che arriva anche a 400-500 mila, quindi sarebbe preferibile spezzettare i file.
Attendiamo riscontro.
Grazie.

**Comment by frmariani** [comment]
L'upload realizzato permette il caricamento di un file di grandi dimensioni utile per l'aggiornamento di un numero di elettori superiore alle vostre esigenze; ad ogni buon conto, in ambiente di test comuni è possibile anche il caricamento di più file senza necessariamente aggiornare il campo versioneFornitura.

**Comment by RenatoFumarola** [comment]
Ok questo è chiaro, ma la possibilità di caricare più file con elettori diversi, e quindi per esempio avere solo 50mila elettori all'interno di ogni singolo file, è possibile sia in ambiente di test che di produzione? Faccio un esempio così mi spiego meglio: se il mio comune ha 300mila elettori, possiamo fare 6 file diversi xml (zippati in gz come richiesto) per il caricamento sia in ambiente di test che di produzione?

**Comment by frmariani** [comment]
era già chiara la domanda e pensavo anche la mia risposta, comunque ribadisco che può inviare un solo file con tutti gli elettori del comune (anche se gli elettori sono superiori al milione) o, se lo preferite per vostra comodità, più file con tot elettori a file per lo stesso comune.

Attualmente questa seconda possibilità, quindi l'invio di più file per lo stesso comune, è possibile soltanto in ambiente di test comuni, ma a breve sarà possibile anche in ambiente di produzione.

**Comment by RenatoFumarola** [comment]
Ok grazie ora è più chiaro.

**Comment by RenatoFumarola** [comment]
Avrei un'altra domanda: alla call del 5 dicembre si è parlato di una dimensione massima di 50MB del file, ma è la dimensione del file.xml o del file.gz?

**Comment by frmariani** [comment]
del file .gz

**Comment by RenatoFumarola** [comment]
ok grazie.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
