### ISSUE TITLE
Servizi al Cittadino - Purtroppo non is stato possibile accedere al servizio ANPR - #2838

### ISSUE THREAD

**Issue by PilarMRamon** [italia/anpr#3715]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/121613336/209945865-2172edfb-7084-4d62-b94b-98261045d119.png">

Cosa devo fare? Il comune non sa come aiutarmi. 

Ho notato che ci sono diverse persone a cui è successa la stessa cosa, nel titolo ho messo il riferimento

Grazie

**Comment by cmigliardi** [comment]
salve per favore ci può dare le prime 6 lettere  del suo codice fiscale ? grazie

**Comment by PilarMRamon** [comment]
I primi 6 caratteri del mio codice fiscale sono:
RMNMPL

**Comment by cmigliardi** [comment]
salve  se è lei la persona aire  nata in argentina nel 1996 si deve rivolgere al comune di CROTONE che deve   validare il suo codice fiscale in ANPR  -

**Comment by PilarMRamon** [comment]
Potresti dirmi dove devo rivolgermi?

**Comment by cmigliardi** [comment]
ufficio anagrafe di crotone

**Comment by cmigliardi** [comment]
la issue si chiude
