### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by paulamarchiori** [italia/anpr#3717]
Sto cercando di accedere al servizio, ma viene visualizzato il seguente errore:

“Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.”

Potresti verificare se c'è qualche errore?

I primi 6 caratteri del mio codice fiscale: MRCPLA
Comune: Isola della Scala

Distint Saluti
Paula Marchiori Damasceno
Nata in Brasile.

**Comment by cmigliardi** [comment]
salve - se è lei la persona nata nel 1987 - si deve rivolgere al suo comune  isola della scala - che l'ha iscritta AIRE - perché il suo codice fiscale non è validato in Anpr  -

**Comment by cmigliardi** [comment]
si chiude la issue
