### ISSUE TITLE
Annullamento mutazione residenza

### ISSUE THREAD

**Issue by AndreaFormenti** [italia/anpr#3718]
Buongiorno,
il sig. idAnpr 20067292 ha mutato la residenza  nel nostro. A seguito di accertamento negativo è stato emesso provvedimento di annullamento di mutazione.
Abbiamo provato ad effettuare l'annullamento della mutazione tramite ANPR (operazione 1080398471) seguendo la guida ma non siamo riusciti (annullamento mutazione----operazione ufficio---...--decorrenza 05/11/2022-- tipo scheda "scheda famiglia"-- ripristino posizione anagrafica "sì --- ripristino parziale "no"---operazione richiesta "mutazione residenza" --- id operazione anpr "1080398471), ci da l'errore :
"Informazioni sull'operazione da fornire in caso di assistenza : data 2022-12-30 10:09:01 , idOperazioneANPR 1141677564 (Codice: EN527) ".
Come possiamo fare?
VI ringrazio fin da ora per il vostro sempre cortese riscontro.
Andrea Formenti
Comune di Caponago.

**Comment by frmariani** [comment]
l'operazione indicata per l'annullamento (idanpr 1080398471) non è una mutazione di residenza ma una mutazione scheda

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
