### ISSUE TITLE
[Subentro] File APR: Legame Soggetto

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#372]
Buongiorno,
anche per "legameSoggetto", vorrei chiedere conferma sulla data decorrenza da inserire, per evitare di dare interpretazioni soggettive. 
Nelle specifiche c'è scritto 'La data a partire dalla quale il soggetto appartiene alla famiglia/convivenza'. Ma con il legame attuale? Oppure, letteralmente, da quando fa parte di quella famiglia/convivenza?
Credo sia chiaro che il dubbio mi sorge per i casi in cui un componente ha subito diverse variazioni di 'legame' da quando fa parte della famiglia/convivenza. Quale data deve essere inviata?
Grazie come sempre per la pazienza e la disponibilità.
Eduardo Gira

**Comment by frmariani** [comment]
letteralmente da quando fa parte di quella famiglia/convivenza
