### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by riccardomanzi94** [italia/anpr#3720]
Salve, ho un problema ad accedere al sito e ricevo l'errore della presenza di un'anomalia dei dati .
L'inizio del codice fiscale è : RCAGST

![image](https://user-images.githubusercontent.com/47970832/210139362-e3e3d46b-c0cf-4b34-a429-da84d18d6277.png)

**Comment by cmigliardi** [comment]
salve - se è lei la persona nata nel  1944  - dovrebbe  rivolgersi al suo comune di residenza e far chiarezza in Anpr- perché  attualmente  lei  ha doppia residenza  a Roma e a Veroli  - in sostanza una volta accertata  la sua vera residenza -  l'altro comune deve cancellare per doppia iscrizione la sua scheda

**Comment by cmigliardi** [comment]
si chiude la issue
