### ISSUE TITLE
Avviso 3 gennaio 2023: La richiesta dei certificati in bollo con esenzione dell'imposta ai sensi dell'art. 62, comma 3 del CAD, è temporaneamente sospesa. Per questa tipologia di certificati si prega di rivolgersi presso gli uffici di anagrafe di qualsiasi comune. 

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#3724]
Sull'home page del sito anpr compare questo avviso:
Avviso 3 gennaio 2023: La richiesta dei certificati in bollo con esenzione dell'imposta ai sensi dell'art. 62, comma 3 del CAD, è temporaneamente sospesa. Per questa tipologia di certificati si prega di rivolgersi presso gli uffici di anagrafe di qualsiasi comune. 
Considerato che il
CONSIGLIO DEI MINISTRI – 21 DICEMBRE 2022 - con il  Decreto Proroghe recita:
Si proroga anche al 2023 l’esenzione dall’imposta di bollo per la certificazione dei dati anagrafici in modalità telematica assicurata dal Ministero dell’interno tramite l’Anagrafe nazionale della popolazione residente – ANPR.
Si chiede di chiarire in quanto stiamo indirizzando i cittadini al sito.
Cordiali saluti
Raffaella
Venezia

**Comment by cmigliardi** [comment]
buongiorno Raffaella,   abbiamo chiesto -    l'avviso è corretto perché  tu ti   riferisci   ad un comunicato del 21 in cui era previsto ma poi è stato tolto -

**Comment by cmigliardi** [comment]
si chiude la issue

**Comment by cmigliardi** [comment]
buon anno anche a te !  un caro saluto   Cecilia
