### ISSUE TITLE
Per questo soggetto non e' possibile emettere nessun certificato, rivolgersi al comune di residenza.

### ISSUE THREAD

**Issue by dvdcarella** [italia/anpr#3725]
TEST effettuato in data 03/01/2023 (riprovato diverse volte anche antecedenti alla data indicata) 

Accesso effettuato mediante SPID (provider: poste italiane)

restituito errore: Per questo soggetto non e' possibile emettere nessun certificato, rivolgersi al comune di residenza.

Aggiornamento c. identità in corso, inserita nuovo ticket direttamente da portale anpr del cittadino. 

Il problema potrebbe essere riconducibile a dati errati in anagrafica?

**Comment by cmigliardi** [comment]
salve per favore è possibile avere le prime  6 lettere  del suo codice fiscale ? proviamo a capire il motivo . grazie  in anticipo

**Comment by dvdcarella** [comment]
Certamente
CRLDVD

Ho contatto anche l'anagrafe ma non sanno il motivo di tale problematica.
Attendo un riscontro e sono a disposizione per ulteriori dati

Buon lavoro
Il 4 gen 2023, 09:55 +0100, cmigliardi ***@***.***>, ha scritto:

**Comment by cmigliardi** [comment]
se è lei la persona nata a luglio del 1988  - in effetti la scheda non ha problemi  - per favore ci può dire cosa richiede dal portale e quale messaggio riceve ?  grazie

**Comment by dvdcarella** [comment]
No settembre 98
Al portale si richiede un certificato di residenza. Ma qualsiasi altra richiesta restituisce la stessa risposta dal sistema.
Il 4 gen 2023, 10:05 +0100, cmigliardi ***@***.***>, ha scritto:

**Comment by dvdcarella** [comment]
Si corretto
Il 4 gen 2023, 10:12 +0100, cmigliardi ***@***.***>, ha scritto:

**Comment by cmigliardi** [comment]
ho trovato una scheda  dove  non è riconosciuta dal comune la certificabilità  - il comune è PIGNATARO INTERAMNA -  se è il suo di residenza, vada in anagrafe e chieda  di sanare la situazione sulla scheda in ANPR -

**Comment by dvdcarella** [comment]
Provo a dirlo al comune di residenza
Il 4 gen 2023, 10:14 +0100, cmigliardi ***@***.***>, ha scritto:

**Comment by cmigliardi** [comment]
può  risolvere  solo il comune  che ha competenza sulla sua scheda .  si chiude la issue
