### ISSUE TITLE
ANPR - Purtroppo non è stato possibile accedere al servizio...

### ISSUE THREAD

**Issue by alemorina** [italia/anpr#3726]
Buongiorno,
accedo per una consultazione della mia scheda anagrafica e mi restituisce questo "errore" come devo agire?

grazie
A.M.

**Comment by cmigliardi** [comment]
salve se possibile ci può fornire le prime 6 lettere del suo codice fiscale ? grazie

**Comment by alemorina** [comment]
MRNLSN

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel '67   allora si deve rivolgere al comune di residenza  e farsi iscrivere in ANPR perché negli archivi la sua scheda è cancellata dal comune di Capena  -

**Comment by alemorina** [comment]
grazie

**Comment by cmigliardi** [comment]
si chiude la issue
