### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Damiann23** [italia/anpr#3727]
Sto cercando di accedere al servizio, ma viene visualizzato il seguente errore:

“Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.”

Potresti verificare se c'è qualche errore?

I primi 6 caratteri del mio codice fiscale: RDRDNS
Comune: Savona
Iscritto all'AIRE in Montevideo - Uruguay
Nata in Uruguay

Saluti

Damián Sergio Rodríguez Rodríguez

**Comment by cmigliardi** [comment]
SALVE SE è LEI LA PERSONA NATA NEL   2001 . DEVE RIVOLGERSI AL COMUNE DI SAVONA AFFINCHè LA POSSA ISCRIVERE IN ANPR  -

**Comment by Damiann23** [comment]
Quale mail devo contattare?  Sono nato nel 2001 ma ho preso la cittadinanza italiana nel 2021, è lo stesso?

**Comment by cmigliardi** [comment]
non so dirle una emal.  posso solo consigliarle di rivolgersi al comune di competenza . o dove risiede . o il comune che lo ha iscritto all'aire.

**Comment by cmigliardi** [comment]
si chiude la issue
