### ISSUE TITLE
Archiviazione Famiglia 

### ISSUE THREAD

**Issue by AGrossiVE** [italia/anpr#373]
VENEZIA - Ambiente di PRE-Subentro

Per avere dei riscontri sui test che stiamo effettuando sui web service, da WebApp abbiamo provveduto a registrare il decesso dell'unica persona iscritta nella famiglia ANPR n. 4873232. 
L'applicazione ha registrato correttamente il decesso ma evidenzia il seguente warning:

**Attenzione:Aggiornare la famiglia del soggetto cancellato indicando un nuovo intestatario ed eventualmente i relativi rapporti di parentela (Codice: EN225)**

Ci aspettavamo di poter archiviare la famiglia come conseguenza logica dell'operazione fatta per l'unico soggetto iscritto nella medesima ma tra le operazioni possibili presenti nella sezione “Registrazione” non abbiamo trovato nulla. Qualsiasi operazione, anche di consultazione, effettuata su quella famiglia restituisce il seguente messaggio: “La richiesta effettuata non produce alcun risultato (Codice: EN122)”.
Da WebApp non c'è evidenza dello stato in cui si trova la famiglia (attiva e vuota o archiviata?)

**Comment by gcarbonin** [comment]
Il messaggio warning esce a prescindere dal numero di componenti.
Se viene cancellato l'unico componente di una famiglia, la famiglia è automaticamente archiviata.
Si possono interrogare i soggetti cancellati falla ricerca avanzata disponibile nella WA nella sezione consultazione/estrazione

**Comment by AGrossiVE** [comment]
Grazie, in effetti la ricerca delle schede individuali cancellate era già stata individuata, al contrario, la ricerca delle schede famiglia archiviate no. Dalla sua risposta deduco che non c'è evidenza di ciò.

**Comment by gcarbonin** [comment]
Questa funzione non c'è: è un'esigenza non rilevata in precdenza,
