### ISSUE TITLE
[ws1002] Iscrizione APR - Errore EN289

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#3733]
ambiente di PRODUZIONE - comune di BORGOSATOLLO (017021)

idSoggettoANPR 61834576

iscriviamo con ws 1002 il soggetto che risulta cancellato per Irreperbilità da Brescia.
l'iscrizione ha decorrenza 29/12/2022
la cancellazione di Brescia ha decorrenza 28/02/2022

la comunicazione (idOperazioneANPR 1154207971) va in errore con il messaggio:
```
<errore>
  <codiceErroreAnomalia>EN289</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto XXX XXX</testoErroreAnomalia>
</errore>
```
non capiamo a quale "data fine validità" si faccia riferimento".

grazie
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
urge riscontro a questa segnalazione.

il soggetto è iscritto a Borgosatollo dal 29/12/2022 e in ANPR risulta ancora cancellato.
sono due settimane che attendiamo di sbloccare la situazione.
nuovo tentativo oggi (con stesso risultato): idOperazioneANPR 1171096703

**Comment by frmariani** [comment]
Ciao Alessandro,
il problema è dato dai dati del matrimonio che hai inserito; questi dati erano già stati acquisiti dal precedente comune, quindi se la situazione matrimoniale della cittadina non è cambiata, devi rimettere gli stessi dati, altrimenti il sistema li considera come dati di una nuova situazione.
In questo caso, dovresti inserire l'identificativo anpr del coniuge.
Riprova e fammi sapere.

**Comment by AMonopoliADS** [comment]
nel caso specifico il cliente non ha acquisito i dati del matrimonio (per errore? per scelta? non lo sappiamo...), e quindi non sono stati inviati.
i restanti dati del coniuge (nome ed estremi del divorzio erano gli stessi). 
non entro nel merito del controllo, forse un po' restrittivo, ma ci saranno le giuste ragioni strutturali.
ho quindi sistemato la situazione come hai suggerito e la comunicazione è partita.

trovo, invece, piuttosto difficoltoso individuare che il problema fosse questo, partendo dal messaggio di errore restituito dal ws, e trattandosi di una comunicazione di iscrizione.

comunque grazie del tuo intervento.
Alessandro

**Comment by frmariani** [comment]
Effettivamente il controllo è un po' generico ma viene utilizzato in diversi contesti dove viene coinvolta la "data evento".

**Comment by AMonopoliADS** [comment]
si, il controllo è un po' generico, ma adeguato se sto inviando una mutazione di matrimonio e/o divorzio.
mi sembra invece di facile fraintendimento se associato ad una comunicazione di iscrizione (come in questo caso) dove la "data evento" (che nel mio caso associo alla data di iscrizione) è già maggiore di qualsiasi altra data di fine validità che si possa riscontrare dalla consultazione. 
intendevo questo esprimendo la difficoltà di interpretazione

**Comment by frmariani** [comment]
si si era chiaro ma volevo consigliare di sfruttare sempre il dato inserito nel controllo, senza ulteriori interpretazioni.
In questo caso la "data evento" poteva essere riferita soltanto al matrimonio.
