### ISSUE TITLE
Certificati non disponibili

### ISSUE THREAD

**Issue by Ionikekko** [italia/anpr#3736]
Buonasera,
ho necessità di scaricare il certificato di Stato Civile.
Sul sito ANPR ho la possibilità di scaricarne solo 2 (residenza/stato di famiglia), tutti gli  altri non compaiono nella lista 
Come posso fare?

Da Dicembre ho cambiato residenza passando dal Comune di Gaeta 04024 (LT) al Comune di Formia 04023 (LT), provato sempre con SPID (poste) anche di altro componente della famiglia ma i certificati non ci sono.

Grazie e buona serata

**Comment by cmigliardi** [comment]
salve per favore ci può fare le prime 6   lettere del suo codice fiscale ?   così possiamo fare un controllo . grazie

**Comment by Ionikekko** [comment]
> 

GGLRRT

grazie in anticipo per il supporto

Buonaserata

**Comment by cmigliardi** [comment]
salve se è lei la persona nata nel 1966 e residente a Formia - come ha scritto -  si deve   rivolgere al comune di Formia che ha un procedimento sulla sua scheda  dal 5 novembre 2022 - per questo motivo ha una certificabilità parziale -

**Comment by cmigliardi** [comment]
si chiude la   issue
