### ISSUE TITLE
Link driver smartcard IDP_6.47.04_ITA

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3739]
Buongiorno, 

Si segnala che il link IDP_6.47.04_ITA che si trova alla seguente pagina non è valido e non possibile scrivere il software

https://www.anagrafenazionale.interno.it/area-tecnica/guida-anpr/

**Comment by Leonforte** [comment]
Salve, grazie per la segnalazione, stiamo intervenendo, nelle more può scaricare il driver al link diretto su Aruba 

https://ca.arubapec.it/downloads/IDP_6.47.04_Windows.zip

Buon lavoro, saluti
