### ISSUE TITLE
[Subentro] Individuazione del campo IdOperatore in ambiente di esercizio

### ISSUE THREAD

**Issue by giafra68** [italia/anpr#374]
Il sistema di sicurezza per accesso tramite Web-Services prevede l'indicazione del campo IdOperatore  per l'individuazione appunto dell'operatore che effettua la richiesta (campo NameID del Subject dell'asserzione SAML).

Negli ambienti di TEST e PRE-SUBENTRO veniva indicato l'id dell'utente generico. Es: COMUNETEST019025 per il Comune di Castelleone.

Si richiede di indicare cosa dovrà essere riportato in tale campo in ambiente di esercizio effettivo.

Giannini - PADigitale Spa

**Comment by gcarbonin** [comment]
Il codice fiscale della persona del comune che richiede l'operazione. Questa persona deve essere censita in ANPR  e profilata.
