### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Erickpravato** [italia/anpr#3743]
Sto cercando di accedere al servizio, ma viene visualizzato il seguente errore:
“Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.”
Potresti verificare se c'è qualche errore?

I primi 6 caratteri del mio codice fiscale:PRVRCK
Comune: Altavilla Vicentina
Distint Saluti
Erick Pravato
Nato in Brasile.

**Comment by cmigliardi** [comment]
salve se è Lei la persona nata nel febbraio del 1991 . si rivolga al suo comune  perché  in Anpr  la sua scheda è assente

**Comment by cmigliardi** [comment]
si chiude la issue
