### ISSUE TITLE
non è stato possibile accedere al servizio - ANPR -  Servizi anagrafici

### ISSUE THREAD

**Issue by JoseJuniorFerrari** [italia/anpr#3744]
Buona Notte!

Caro,

Non riesco ad accedere a Servizi anagrafici - ANPR (https://www.anagrafenazionale.interno.it/).

Il comune ha riferito che non vi è alcun errore nella registrazione.

Di seguito invio l'errore.

Potresti aiutarmi?

Jose Junior Ferrari de Oliveira Silva, nato a Barra de Sao Francisco - Brasile. Prime sei cifre del mio codice fiscale: FRRJJN

Grazie.

![image](https://user-images.githubusercontent.com/123424753/214176355-2feb4f81-0864-4941-9ad4-67850b568d77.png)

**Comment by cmigliardi** [comment]
salve se è Lei la persona nata  a marzo del '92   allora  deve rivolgersi al suo comune   perché  il suo codice fiscale  in ANPR  non è validato.

**Comment by cmigliardi** [comment]
si chiude la issue
