### ISSUE TITLE
[5001] Perfezionamento Iscrizione - Errori EN389 / EN358

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#375]
ambiente di PRODUZIONE - comune di Medicina (BO)

caso:
- soggetto iscritto in via preliminare in data 14/09/2017
- il soggetto ha subito una variazione di dati in data 09/10/2017
- oggi (20/10/2017) è stato fatto il subentro, nei suo dati abbiamo: dataIscrizione 14/09/2017 e dataUltimoAggiornamento 09/10/2017

si sta tentando di comunicare il perfezionemento dell'iscrizione con servizio 5001 e tipoMutazione '20'.

se passiamo come dataDecorrenza il 14/09/2017, la comunicazione va in errore con il messaggio:
EN389 - La data decorrenza 14-09-2017 dell'operazione non puo' essere inferiore alla data decorrenza 09-OCT-17 dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto  (idOperazioneComune 2017000038)

se forziamo la dataDecorrenza 09/10/2017, la comunicazione va in errore con il messaggio:
EN358 - La data decorrenza del perfezionamento di un'iscrizione deve essere uguale alla data dell'iscrizione stessa 14-09-2017 (idOperazioneComune 2017000039)

abbiamo suggerito al cliente di retro-datare la dataUltimoAggiornamento attraverso la nuova funzionalità di "Rettifica - Dati del Subentro"... ma abbiamo visto che in ambiente di produzione questa funzionalità non è ancora attiva.

come ne usciamo?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Verifichiamo e facciamo sapere La funzionalità cui fa riferimento sarà attiva da martedì ma non è utile allo scopo: consente di agire sulla data di decorrenza della residenza e non sulla data di ultima variazione della scheda.

**Comment by gcarbonin** [comment]
La mutazione di tipo 20 non è utilizzabile in quanto la scheda è stata modificata dopo la prima iscrizione.
occorrono singole mutazioni con data di decorrenza 9-10-2017

**Comment by AMonopoliADS** [comment]
la funzione di "Rettifica dati subentro" propone tra i macro dati modificabili i "Dati dell'operazione".
tra questi - in ambiente di pre-subentro - abbiamo visto anche la data di ultimo aggiornamento della scheda (... da qui l'idea, fuorviata, che fosse un dato modificabile...)
valutate la possibilità di aggiornarla, almeno nei casi in cui l'informazione arriva da subentro, perchè il tipoMutazione '20' è stato messo in piedi proprio per evitare le 'n' mutazioni di dati che si nascondono dietro un perfezionamento definitivo di iscrizione.

adesso tentiamo il passaggio di più tipoMutuazione all'interno della stessa comunicazione, sperando che basti e che ci eviti la moltiplicazione delle comunicazioni.

grazie.

**Comment by gcarbonin** [comment]
Aggiungo che il 20 ottobre avete una mutazione delle generalita

**Comment by AMonopoliADS** [comment]
abbiamo verificato con il cliente che l'intervento del 20 ottobre è stato eseguito direttamente dalla web-app per sanare la posizione del soggetto che non riusciva a passare via web-service.
come segnalato, valutate la possibilità di intervenire in modifica della dataUltimoAggiornamento.

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
a circa due settimane dall'avvio in produzione del cliente, abbiamo potuto riscontrare che è piuttosto frequente la situazione di "dati modificati" tra l'iscrizione preliminare e quella definitiva.
questo, come chiarito qualche giorno fa, preclude la possibilità di utilizzare il tipoMutazione '20', che invece ha come vincolo l'impostazione della dataDecorrenza corrispondente a quella dell'iscrizione (... e l'assenza di variazioni successive...).
pur ritenendo molto comodo l'uso del tipoMutazione '20', dobbiamo intraprendere la strada delle mutazioni multiple all'interno della comunicazione di perfezionamento.
c'è qualche controindicazione dietro questa scelta, nell'ambito della gestione della pratica di iscrizione?
grazie.

Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Il controllo delle date è relativo a informazioni variate dallo stesso tipo di mutazione (generalità con generalità ad esempio), con alcune esclusioni (tipo una variazione del titolo di studio intermedia non influisce).
Non ci sono controindicazioni alle mutazioni multiple
