### ISSUE TITLE
Web App (TEST): atti di stato civile non visibili

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3753]
Buongiorno, 

segnalo che in ambiente di test nelle schede di consultazione non vengono più visualizzati gli atti di stato civile (nemmeno quelli analogici). 

Inoltre vorrei sapere come saranno presentati in consultazione e in certificazione i nuovi atti digitali.

Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by mttfranci** [comment]
Il problema dovrebbe essersi risolto già ieri verso ora di pranzo, ce lo confermate?
Saluti

**Comment by MoniaPedrazzoli** [comment]
Sì ora gli atti analogici sono visibili. Per quanto riguarda invece quelli digitali avete in previsione degli ulteriori aggiornamenti?
Grazie
