### ISSUE TITLE
Certificato di matrimonio non disponibile ANPR

### ISSUE THREAD

**Issue by annagiuliatiozzo** [italia/anpr#3754]
Segnalo che non mi è possibile visualizzare e scaricare alcuni certificati, tra cui **certificato di matrimonio**.

Come certificati disponibili ho accesso unicamente a: 

* Anagrafico di nascita
* di Cittadinanza
* di Esistenza in vita
* di Residenza
* di Stato di famiglia
* di Stato di famiglia e di stato civile
* di Stato di famiglia con rapporti di parentela

Potete verificare la motivazione?
Primi 6 caratteri codice fiscale TZZNGL

**Comment by cmigliardi** [comment]
salve se è Lei la persona residente a Vigevano - le consiglio di rivolgersi al suo comune di residenza poiché in ANPR non stati inviati i dati del suo matrimonio . per questo motivo non è disponibile nella lista.

**Comment by annagiuliatiozzo** [comment]
Grazie
