### ISSUE TITLE
LISTE ELETTORALI: nuovi aggiornamenti in ambiente di Test-Comuni

### ISSUE THREAD

**Issue by frmariani** [italia/anpr#3757]
Si comunica che da oggi, in ambiente di Test-Comuni, nell'area Liste Elettorali, sono presenti i seguenti aggiornamenti:

- Gestione Bilinguismo: per i comuni in cui è prevista la doppia lingua, sarà possibile acquisire in altra lingua l’indirizzo e la denominazione della sezione; i dati in altra lingua saranno visibili anche nella consultazione della sezione;

- I valori dei campi
"circoscrelezionimembriue", "circoscrregionali", "collegiocameradeputati", "collegiosenatorepubblica" nella mutazione della sezione  e "circoscrcameradeputati", "circoscrsenatorepubblica" della mutazione liste elettorali 
vengono verificati tramite delle tabelle standard fornite dal Ministero (in caso di incongruenza viene restituito errore);
Nella web app, le tabelle di geolocalizzazione fornite dal Ministero guideranno l’utente all’utilizzo dei formalismi secondo il comune di appartenenza;

- Nella procedura di subentro verrà introdotta la notifica N017: nel caso in cui un comune, in fase di primo caricamento, cerchi di inviare i dati elettorali di un cittadino i cui dati elettorali siano stati inviati precedentemente da un altro comune, l’aggiornamento del dato non verrà effettuato e verrà inviata una notifica con le informazioni del caso ad entrambi i comuni;

- Per agevolare la fase di test e quindi soltanto in ambiente di test comuni,  sarà possibile richiedere la cancellazione del file delle liste elettorali precedentemente inviato dal comune

- Nella nuova sezione “Riepiloghi” della web app, sarà possibile verificare il numero di elettori di cui sono stati inviati i nuovi dati elettorali; gli elettori saranno suddivisi per genere; al momento l’aggiornamento degli elettori verrà effettuato una volta al mese.

- Ripubblichiamo gli xsd a cui sono state apportate le seguenti modifiche:

1.  inserimento degli element per gestire la sezione in altra lingua
2.  annotation su alcuni element per chiarire il loro significato (dataCancellazioneLista e tipoConsultazione)
3.  xsdNotificheComuni con inserimento della nuova notifica N017

Si allegano inoltre:

- una tabella che consente l'individuazione della corretta associazione fra stato estero e ripartizione estera degli elettori AIRE;
- una tabella di decodifica delle mutazioni delle liste elettorali.
  
 [WSDLComuni.zip](https://github.com/italia/anpr/files/10546927/WSDLComuni.zip)
[DEC_TIPO_MUTAZIONE_ELE.xlsx](https://github.com/italia/anpr/files/10546929/DEC_TIPO_MUTAZIONE_ELE.xlsx)
[LISTA_TAB_STATO_RIP.xls](https://github.com/italia/anpr/files/10546942/LISTA_TAB_STATO_RIP.xls)

**Comment by RenatoFumarola** [comment]
Buongiorno,
    Renato Fumarola di Maggioli SPA. 
Avrei una domanda sui campi "circoscrcameradeputati", "circoscrsenatorepubblica" della mutazione liste elettorali: da xsd non risultano obbligatori, quindi significa che possiamo NON inviarli anche se impostiamo i campi senatorepubblica=S e cameradeputati=S ?

**Comment by frmariani** [comment]
no, c'è un controllo applicativo che vi obbliga all'inserimento se senatorepubblica=S e cameradeputati=S

**Comment by migmar68** [comment]
Buongiorno
Chiedo conferma su questi due campi "circoscrcameradeputati", "circoscrsenatorepubblica".
Questi valori sono presenti sia sulla sezione, che sull'elettore.
Ipotizzavo che fosse prevista questa modalità per consentire questo tipo di invio:
sulla sezione indico la circoscrizione prevista per i residenti nel Comune che votano nella sezione.
sull'elettore, se residente, lascio vuoti i campi delle circoscrizioni, e indico S in senatorepubblica...   l'informazione della circoscrizione viene reperita da ANPR dalla sezione.
sull'elettore, se residente estero, compilo i campi delle circoscrizioni.
Dalla risposta sopra indicata, mi sembra di intuire che ho capito male e il dato va indicato anche sui residenti nel comune.

**Comment by frmariani** [comment]
I dati che ha segnalato **NON** sono presenti sia sui dati della sezione che sui dati dell'elettore. 
**DATI PRESENTI NELLA SEZIONE**
Circoscrizione per l'elezione dei membri del Parlamento Europeo spettanti all'Italia
Collegio plurinominale e collegio uninominale per il Senato della Repubblica
Collegio plurinominale e collegio uninominale per la Camera dei deputati
Circoscrizione delle elezioni regionali
Circoscrizione delle elezioni circoscrizionali
**DATI PRESENTI NEI DATI ELETTORALI DEL CITTADINO**
Circoscrizione per l'elezione dei membri del Senato della Repubblica
Circoscrizione per l'elezione dei membri della Camera dei deputati

Come indicato dal nuovo decreto, se nei dati dell'elettore viene indicato
**Senato della Repubblica=S**, si deve obbligatoriamente indicare la Circoscrizione per l'elezione dei membri del Senato della Repubblica; al contrario, se il dato è N, non devono essere indicati; se avessimo reso questo campo obbligatorio da xsd, si sarebbe dovuta inviare l'informazione anche se Senato della Repubblica=N.
La stessa cosa vale per il dato riferito alla camera dei deputati:
 se **Camera dei deputati=S**, si deve obbligatoriamente indicare la Circoscrizione per l'elezione dei membri della Camera dei deputati.
I dati indicati nella sezione e riferiti al Senato della Repubblica ed alla Camera dei deputati, si riferiscono ai collegi plurinominali e uninominali.

**Comment by migmar68** [comment]
Ok, vero grazie.
