### ISSUE TITLE
Persona  non allineato ae e non marcato anpr

### ISSUE THREAD

**Issue by SFACCHINELLI** [italia/anpr#3759]
Buongiorno COMUNE DI CALDONAZZO  abbiamo iscritto una persona già cancellata per irreperibilità nel 2015 dall'estero.
Risulta però iscritta in anpr "non allineato" e  "non marcato anpr" in AE.

Nella web app non è possibile risolvere il disallineamento in quanto consente solo di confermare quanto in AE  con l'indirizzo riferito al precedente comune dove cancellata per irreperibilità.

Il numero ANPR è  327026176 cod. fisc. SMNRTI72S46Z129Z
Si chiede cortese risoluzione in quanto ora non è possibile il rilascio  della CIE.
Grazie molte e buon  lavoro

**Comment by frmariani** [comment]
la conferma AE si riferisce ai dati anagrafici pertanto può tranquillamente effettuare la conferma visto che sono uguali.
Per quanto riguarda l'indirizzo, anche se diverso tra i due sistemi, sarà sempre quello del comune ad essere ritenuto valido, pertanto con l'allineamento dei dati anagrafici verrà aggiornato l'indirizzo in AE con quello presente in ANPR.
