### ISSUE TITLE
[3002] Scheda Individuale: Data Ultimo Aggiornamento

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#376]
il servizio di consultazione non ritorna la dataUltimoAggiornamento passata con il subentro.
è voluto?

grazie.

**Comment by amollicone1982** [comment]
Non è prevista nel tracciato di risposta della consultazione

**Comment by AMonopoliADS** [comment]
ciao Angelo. grazie del tuo riscontro.
è ipotizzabile l'aggiunta del campo in questione?
nel caso della segnalazione #375 il messaggio di errore fa riferimento ad una data 9/10/2017 che, consultando la scheda via web-service, non abbiamo trovato da nessuna parte.
abbiamo trovato l'informazione solo eseguendo la consultazione via web-app.
se si potesse evitare il passaggio, sarebbe più semplice peri l cliente la verifica dei dati.
grazie

**Comment by amollicone1982** [comment]
Terremo conto della richiesta
