### ISSUE TITLE
Web App produzione: atti di stato civile non visibili

### ISSUE THREAD

**Issue by Maga63** [italia/anpr#3760]
Buongiorno, anche nella Wep App di produzione non sono più visibili gli atti di stato civile.

**Comment by mttfranci** [comment]
Il problema dovrebbe essersi risolto già ieri verso ora di pranzo, ce lo confermate?
Saluti

**Comment by Maga63** [comment]
Confermiamo che ora  sono visibili.
Grazie.
Saluti
