### ISSUE TITLE
Accesso ai dati dell'ANPR

### ISSUE THREAD

**Issue by FERRETTI-LAURA** [italia/anpr#3762]
Nel sito ANPR, nella sezione "Accesso ai dati dell'ANPR" non è più indicato che l'accesso è in fase sperimentale, pertanto diversi enti e forze di polizia del nostro Comune di Ancona stanno provando ad accreditarsi senza successo, perchè nel momento che inseriscono il proprio ente il sistema segnala "La piattaforma è aperta solo ad alcuni enti sperimentatori". Vorremmo sapere quando sarà possibile effettuare gli accreditamenti, nelle modalità indicate nel sito.
Ferretti Laura
Comune di Ancona

**Comment by FilippoPapi** [comment]
buonasera,
sarà data comunicazione da parte del Ministero dell'Interno
