### ISSUE TITLE
Errore Autenticazione servizio C015 TokenAuthenticationFailed

### ISSUE THREAD

**Issue by EmaPace** [italia/anpr#3763]
Buongiorno,

scriviamo da parte della Motorizzazione, società fornitrice Dxc Technology , stiamo riscontrando degli errori di autenticazione durante la chiamata al servizio di accertamento generalità. Dalla response sembra che sia dovuto ad un problema di validazione del token generato dalla PDND.
E' possibile fare una verifica?

l'ambiente è quello di test

url invocata 
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C015-servizioAccertamentoGeneralita/v1/anpr-service-e002

la data di esecuzione è 02/02/2023

questa è la response che riceviamo

401 Unauthorized: [{
   "type":"https://govway.org/handling-errors/401/TokenAuthenticationFailed.html",
   "title":"TokenAuthenticationFailed",
   "status":401,
   "detail":"Invalid token",
   "govway_id":"c3f63e15-a2d2-11ed-8caf-005056ae1884"
}]

di seguito alcune informazioni utili per la verifica

GovWay-Transaction-ErrorType:"TokenAuthenticationFailed"
GovWay-Transaction-ID:"c3f63e15-a2d2-11ed-8caf-005056ae1884"
Server:"GovWay-SOGEI"
WWW-Authenticate:"Bearer realm="PDND"
error="invalid_token"

Grazie
Emanuele Pace

**Comment by amollicone1982** [comment]
Una cosa che vedo è
"aud": "testE002.anpr.interno.it" deve essere
"aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C029-servizioAccertamentoDatiAnagrafici/v1"

l'errore che avete è un altro. Sapete che il 15 dicembre pagopa ha fatto lo switch della piattaforma di test?
che dovreste rifare le richieste nuove di fruizione e comunicarci il nuovo clientid

**Comment by amollicone1982** [comment]
per capirci la nuova piattaforma di test è
https://selfcare.uat.interop.pagopa.it/

**Comment by EmaPace** [comment]
Grazie della risposta.
si lo sappiamo e stiamo in attesa ancora delle credenziali per poter effettuare le nuove sottoscrizioni agli e-service.
Pensavamo di poter usare ancora  la vecchia modalità finchè non saremmo passati alla nuova.

Grazie
