### ISSUE TITLE
Accesso al portale del cittadino di test NON FUNZIONA

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3765]
Non si riesce più ad accedere al  portale del cittadino di TEST per creare delle richieste di cambio residenza fittizie per debug/sviluppo.
(url https://dptest3.anpr.interno.it/cns).
Il messaggio di errore che si ottiene è
"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."
Questo con entrambi i CF di test che a suo tempo avevamo censito per il nostro ambiente (comune di Pietravairano).

A cosa è dovuto il problema ? Potete risolvere ? Non possiamo più eseguire collaudi sull'integrazione con le richieste del cittadino.

Grazie

**Comment by apaolacci** [comment]
Buongiorno,
può riprovare ad effettuare il login come cittadino? Adesso dovrebbe funzionare nuovamente.
Grazie per la segnalazione.

Saluti,
Assistenza Anpr

**Comment by busaster** [comment]
Sì grazie, ora riusciamo ad accedere
