### ISSUE TITLE
Codifica relazione di parentela NIPOTE

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#377]
Buongiorno,
vorrei capire in che casi va utilizzata la relazione di parentela ANPR (tabella 5), 81 Nipote.
Non sono sufficienti le altre 3 tipologie di Nipote (discendente, collaterale e affine)? 
Grazie

Carla Musian 
Insiel Mercato

**Comment by gcarbonin** [comment]
Il valore 81 è stato inserito su richiesta di qualche comune che aveva codificato in questo modo la relazione di parentela.
Vanno utilizzate le altre che sono quelle ufficiali ISTAT e che, mi sembra, siano più che sufficienti.

**Comment by CarlaMusian** [comment]
Potreste mettere una nota su quelli che non vanno utilizzati?
Ce ne sono anche altri “non-Istat” ad esempio Tutore
Grazie

Dott.ssa Carla Musian
Direzione Prodotti e Servizi
e-mail: Carla.Musian@insielmercato.it<mailto:Carla.Musian@insielmercato.it>
Insiel Mercato SpA
AREA Science Park – Padriciano 99 – 34149 Trieste
Tel. 040 9227101 – Fax. 040 634623
www.insielmercato.it<http://www.insielmercato.it/>
CF, P. IVA, Reg.Impr. Venezia Giulia n.  01155360322 Cap.Soc. € 3.246.808,00  i.v.
Direzione e coordinamento GPI S.p.a.

Ai sensi del D.Lgs. 196/2003 e della normativa internazionale, Vi informiamo che questo messaggio è riservato esclusivamente al
destinatario. Se esso Vi fosse pervenuto per errore, Vi invitiamo a eliminarlo immediatamente e a darcene comunicazione. Grazie.
According to the Italian and international laws in force, we inform you that this message is reserved only for the addressee. If you are
not the addressee, please delete it immediately and notify us. Thank you.
Prima di stampare questa e-mail, pensa all'impatto sull'ambiente.
Please, consider the environment before printing this e-mail.
Da: gcarbonin [mailto:notifications@github.com]
Inviato: sabato 21 ottobre 2017 16.40
A: italia/anpr
Cc: Musian Carla; Author
Oggetto: Re: [italia/anpr] Codifica relazione di parentela NIPOTE (#377)


Il valore 81 è stato inserito su richiesta di qualche comune che aveva codificato in questo modo la relazione di parentela.
Vanno utilizzate le altre che sono quelle ufficiali ISTAT e che, mi sembra, siano più che sufficienti.

**Comment by anozzoli** [comment]
Trovo giusto la risposta di @gcarbonina ma quando il cittadino va a fare una richiesta di cambio di indirizzo trova la scelta nipote (81) e quasi sempre la sceglie al posto di quelle più precise. Va tolta dalle scelte?
