### ISSUE TITLE
rrore EC075 in subentro e data registrazione atto nascita

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#378]
In subentro vengono segnalati nei file degli errori diversi casi esatti di comuni 
di registrazione dell'atto di nascita.

"Comune dell'atto di nascita:VALVASONE ARZENE(PN) non esistente alla data"

Queste segnalazioni derivano dal fatto che nel file di subentro del comune manca la data di registrazione 
dell'atto di nascita.
Specie quando una persona e' nata all'estero e l'atto di nascita e' stato registrato in Italia 
anni dopo, non potreste fare un confronto con l'anno dell'atto per verificare se il comune di registrazione
e' esatto o meno?

Per quanto riguarda la data di registrazione dell'atto, che non e' un dato prettamente anagrafico,
il comune dove la persona immigra non ne e' a conoscenza.

Esempio:

Persona nata all'estero nel 1997 con atto originale di nascita registrato in Italia nel comune di
Valvasone-Arzene nel 2015, in seguito emigrata in altro comune che subentra.
Il subentro segnala erroneamente che il comune dell'atto di nascita non e' esatto, quando  
era stato istituito proprio il 01/01/2015.

Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
Per favore puo' indicare il comune interessato e l'ambiente nel quale fate i test?

**Comment by CarlaMusian** [comment]
Comune di Venezia
Prog. ANPR soggetto 9680220

**Comment by gcarbonin** [comment]
La segnalazione deriva dal fatto che non c'è la data dell'atto; in questi casi si considera la data dell'evento (nascita che mi sembra sia nel 1997).
Modificare il controllo come da lei suggerito è ipotizzabile; peccato che l'anno dell'atto non sia sempre presente.
Si tratta comunque di un'anomalia tra quelle non classificate come "da rimuovere prima del subentro".
Metto come label Evoluzione: qualcuno valuterà se modificare il controllo.

**Comment by CarlaMusian** [comment]
nell'oggetto Atto.xlsx il comune di registrazione dell'atto e' obbligatorio e anche l'anno, quindi quando e' presente il comune c'e' anche l'anno dell'atto e il controllo si potrebbe fare.

**Comment by mccalv** [comment]
@CarlaMusian grazie per la segnalazione, come già categorizzata, e pur se non bloccante, inseriamo questa tra le issue per  la roadmap futura

**Comment by gcarbonin** [comment]
La modifica è stata effettuata
