### ISSUE TITLE
Codifiche ANPR titoli di studio

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#379]
Comune di Cagliari preparazione per pre subentro.

Buongiorno,
chiediamo quale sia la differenza tra codifiche numeriche e codifiche alfabetiche nella tabella dei titoli di studio.

Grazie

**Comment by gcarbonin** [comment]
I valori alfabetici ci sono stati indicati da ISTAT per meglio classificare il titolo di studio. Con il subentro trasmettete quello che avete in base dati: dubito siano utilizzati i valori alfabetici.  In ambiente di pre-subentro si trovano entrambi.

**Comment by RBiasi** [comment]
Stiamo in ogni caso riclassificando tutto quindi è indifferente volevo solo la conferma che i codici alfabetici non siano destinati solo all'aire.
Grazie

**Comment by gcarbonin** [comment]
No l'AIRE attuale utilizza codici numerici
