### ISSUE TITLE
Liste Elettorali Subentro e richiesta cancellazione subentro

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#3791]
AMBIENTE DI TEST - PISA

Buongiorno, nelle riunioni precedenti al rilascio era stato indicato che il subentro poteva avvenire in più fasi e quindi suddividere gli elettori in più file ma questo in realtà non risulta possibile.

1) Nella fattispecie sull'ambiente di Test del comune di Pisa abbiamo inserito una sola sezione e gli elettori di quella sezione, e adesso non è possibile inserirne altri. Inoltre i file con protocollo 93030795 e ...796 risultano elaborati ma non sono stati accettati per un errore nelle circoscrizioni e nonostante il rigetto quando entriamo a fare un nuovo upload dei file il programma indica: 'I file elettorali sono stati già caricati' e non permette di inserire i file corretti.

2) Sempre nella parte elettorale abbiamo visto la sezione riguardante la 'richiesta cancellazione subentro', però l'indicazione inserita: 'L'operazione comporterà la cancellazione di tutti i dati inseriti fino al momento della richiesta' ed anche lo storico richieste soprastanti, riportante la cancellazione dei subentri Anagrafici, sembra far intendere che la cancellazione possa riguardare anche i dati anagrafici e non solo i dati elettorali, quindi si chiede conferma che questa richiesta comporti la cancellazione solo del 'tentativo' di subentro elettorale e non di tutta l'anagrafe di test.

Grazie

Luca Bonini APK

**Comment by migmar68** [comment]
Buongiorno
Mi unisco alla richiesta 2 qui sopra. Stamattina nel fare il subentro di Poggio a Caiano, ci siamo accorti di un errore e vorremmo cancellare i dati elettorali, per poi ripetere domani l'invio.

**Comment by amollicone1982** [comment]
Inizialmente avevamo detto che avremmo permesso nel solo ambiente di test comuni di inserire piu' file relativi alle liste elettorali in assenza di una procedura di cancellazione (che tra l'altro è andata a buon fine poco fa).
Avendo inserito la procedura di cancellazione dei dati elettoarali siamo tornati in ambiente di test alla situazione che è presente in produzione (inserimento di un solo file delle liste).

La cancellazione riguarda i soli dati elettorali
