### ISSUE TITLE
Web App - CONSULTAZIONE SCHEDA FAMIGLIA/CONVIVENZA - Tipo scheda

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#38]
Data test- 16/03/2017 - Ambiente test (dptest)
Il campo Tipo Scheda non riporta l'asterisco ma se non si inserisce compare il messaggio "Tipo scheda campo obbligatorio".

Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Stiamo sistemando tutte le obbligatorieta'. grazie della segnalazione
