### ISSUE TITLE
INSTALLAZIONE CERTIFICATI

### ISSUE THREAD

**Issue by anagrafe** [italia/anpr#3801]
Buongiorno.
In seguito al cambio di pc, ho urgente bisogno di reinstallare i certificati della mia smartcard e non riesco in nessun modo.
Ho già inserito un ticket venerdì scorso, ma non sono stato richiamato.
Vi pregherei di chiamarmi al più presto per poter risolvere.
Grazie mille.
Fabio Borgogno, Ufficiale d'Anagrafe delegato
Comune di Trinità (CN)
3384945232

**Comment by adominicis** [comment]
Buongiorno, 
il numero indicato risulta spento ed il comune il martedì non risponde al telefono. 
Può indicarmi un altro riferimento dove poterla contattare?
Grazie

Andrea

**Comment by anagrafe** [comment]
Buongiorno.

Martedì e mercoledì ero in ferie.

Oggi e domani potete contattarmi sul numero di servizio 3384945232 a qualsiasi ora.

Grazie.

 

Da: adominicis ***@***.***> 
Inviato: martedì 21 febbraio 2023 09:16
A: italia/anpr ***@***.***>
Cc: anagrafe ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] INSTALLAZIONE CERTIFICATI (Issue #3801)

 

Buongiorno,
il numero indicato risulta spento ed il comune il martedì non risponde al telefono.
Può indicarmi un altro riferimento dove poterla contattare?
Grazie

Andrea

**Comment by anagrafe** [comment]
Buongiorno.

Chiedi infinitamente scusa, ma mi sono dimenticato che è necessario anche installare la smartcard della Segretaria. Vi lascio il suo numero: 3333209016. È disponibile fino alle 12:30.

Altrimenti potete chiamare me al 3384945232 tutto il giorno, oppure domani mattina direttamente sul numero della segretaria.

Grazie ancora per il prezioso aiuto.

 

Da: adominicis ***@***.***> 
Inviato: martedì 21 febbraio 2023 09:16
A: italia/anpr ***@***.***>
Cc: anagrafe ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] INSTALLAZIONE CERTIFICATI (Issue #3801)

 

Buongiorno,
il numero indicato risulta spento ed il comune il martedì non risponde al telefono.
Può indicarmi un altro riferimento dove poterla contattare?
Grazie

Andrea

**Comment by Leonforte** [comment]
Problema risolto dal collega Dominicis

**Comment by anagrafe** [comment]
Buongiorno.

La mia smart card non funziona più.

Se fosse possibile sentirci per provare a risistemare.

Grazie mille

 

Ph.D. Ing. Fabio Borgogno

Comune di Trinità

Ufficio Anagrafe – Ufficio Tributi

Ufficio Tecnico – Ufficio Transizione Digitale

Ufficio Toponomastica

Tel. 017266131 int. 2 o 5

 ***@***.***> ***@***.***

 ***@***.***> ***@***.***

 

Da: Leonforte ***@***.***> 
Inviato: giovedì 23 febbraio 2023 12:00
A: italia/anpr ***@***.***>
Cc: anagrafe ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] INSTALLAZIONE CERTIFICATI (Issue #3801)

 

Problema risolto dal collega Dominicis
