### ISSUE TITLE
DATI ELETTORALI - POPOLAMENTO INIZIALE

### ISSUE THREAD

**Issue by pscioscia** [italia/anpr#3805]
Buongiorno, sono Giuseppe Scioscia della Publisys SpA.
Ambiente di Test Satriano di Lucania.
In data 21/02/2023, protocollo 94029408, abbiamo provato a fare il popolamento iniziale dei dati elettorali, ma durante l'upload potevamo scegliere solo la tipologia: 'caricamento iniziale dei dati elettorali'.
Per fare dei test, abbiamo caricato pochi soggetti, potendo sfruttare la possibilità di effettuare diversi invii.
Invece, viene visualizzato "I file elettorali sono stati già caricati" non permettondoci di fare altro.
Come dobbiamo procedere?
L'opzione "Richiesta cancellazione subentro" nel menu "Liste elettorali" cosa fa?
Grazie

**Comment by frmariani** [comment]
Con la funzione di upload è possibile soltanto un caricamento, sia dei dati elettorali che dei dati delle sezioni, pertanto se il caricamento iniziale delle sezioni è già stato effettuato, è possibile il solo caricamento dei dati elettorali;
anche la sola presenza di una sezione caricata con WS, impedisce il caricamento delle sezioni con la funzione di upload.
Per effettuare più invii, dovete procedere con la richiesta di cancellazione subentro: i dati elettorali dei cittadini acquisiti con il subentro verranno cancellati per darvi la possibilità di effettuare un nuovo subentro e quindi nuovi test.
