### ISSUE TITLE
Subentro e mutazione dati elettorali elettori sospesi

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#3807]
Ambiente di Test comune di Cannobio (VB)

Buongiorno, ci confermate che il subentro di un elettore cancellato per incapacità elettorale va comunque fatto inviandolo con "N" su elettore e blocco certificabilità?
Per questi elettori inoltre non riusciamo a modificare la sezione di assegnazione a seguito di un trasferimento di residenza perché l'invio di una mutazione con WS 5010 restituisce un Internal Server Error mentre la medesima variazione fatta dalla WebApp sembra  funzionare correttamente ma, nella consultazione dei dati elettorali del cittadino, continua ad essere assegnato alla sezione elettorale del comune di provenienza.
Grazie.

Luca Bonini APK

**Comment by frmariani** [comment]
Basta inviare elettore=N; in questo caso è automaticamente inibita la certificazione.
gentilmente mi invii qualche riferimento specifico del caso che va in errore altrimenti non posso aiutarla

**Comment by LucaBonini64** [comment]
l'IdOperazioneComune è 30210 ed era riferita al soggetto ANPR 125939002, però sto facendo anche io delle verifiche perché nell'XML trasmesso mancavano i datiControllo

**Comment by frmariani** [comment]
allora attendo le sue verifiche, nel caso il problema persista mi faccia sapere
