### ISSUE TITLE
[5008] - WS - Mutazione di Convivenza - Errore invio Documento Contratto

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#381]
In ambiente di produzione nel comune di Anzola, all'invio di una specifica mutazione per Convivenza, si riceve una segnalazione di errore bloccante:

_Errore durante la richiesta HTTP a https://wspre.anpr.interno.it/ANPR5000ServiziMutazione/AnprService5000. È possibile che il certificato server non sia configurato correttamente con HTTP.SYS nel caso HTTPS o che i binding di sicurezza client e server non corrispondano._

Ho poi capito che la richiesta viene rifiutata dal sistema ANPR perché la richiesta inviata è troppo lunga a causa del file relativo al contratto di convivenza (quasi 10 Mb, così come inviato dall'avvocato al comune),
file contenuto come array di byte nel tag **tipoDocumentoProtocollato**.

Chiedo quindi indicazioni su quale potrebbe considerarsi una lunghezza limite del file, o, forse più precisamente, quale limite fisico potrebbe considerarsi per l'invio delle richieste in ANPR.

Grazie.

Alessio Tropeano, Datagraph s.r.l.

**Comment by gcarbonin** [comment]
Come indicato nella documentazione (excel del servizio) l'invio può avvenire soltanto tramite web application. Questa funzionalita' al momento non è attiva.

**Comment by mccalv** [comment]
Il servizio dovrebbe essere attivo entro 1 settimana (si stanno facendo le attivazioni dei servizi di controllo di sicurezza sui file binari inviati)

**Comment by ATropeano** [comment]
Bene. Attendo di sapere eventuali limiti sulla lunghezza del file in ambiente WebService.

**Comment by mttfranci** [comment]
> Bene. Attendo di sapere eventuali limiti sulla lunghezza del file in ambiente WebService.

L'invio dell'allegato del documento è previsto solo da applicazione web.
