### ISSUE TITLE
SSL_ERROR_HANDSHAKE_FAILURE_ALERT 

### ISSUE THREAD

**Issue by ComunePinzolo** [italia/anpr#3814]
Buongiorno,

chiediamo supporto per accesso alla webapp ANPR al momento accedendo abbiamo l'errore:

SSL_ERROR_HANDSHAKE_FAILURE_ALERT 

Potete contattarci al numero 0465509116.

Rimaniamo in attesa.

Grazie

Comune Pinzolo

**Comment by Leonforte** [comment]
Problema risolto
