### ISSUE TITLE
Ambiente di test : Certificazione : 6001 in modalità richiesta dati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#382]
Poggio a Caiano test.
Al fine di produrre localmente un certificato di residenza storico per un cittadino residente da prima del subentro ho interrogato il servizio 6001 con tipoRichiesta=2 (richiesta dati) al fine di integrare i dati locali storici con quelli di ANPR.

Il servizio mi risponde correttamente ma negli oggetti "residenza" che mi vengono ritornati mancano le date di decorrenza (vedi operazione ID_ANPR 605698)

**Comment by rnapoli1983** [comment]
Ora verifichiamo e le facciamo sapere

**Comment by rnapoli1983** [comment]
Dovremmo aver risolto. Potete riprovare.

**Comment by busaster** [comment]
Ho riprovato ma ottengo errore 999 "Operazione non effettuabile" (id operazione ANPR 606381)

**Comment by rnapoli1983** [comment]
Il problema che ha causato l'errore 999 "Operazione non effettuabile" dovrebbe essere superato. Abbiamo fato dei test di verifica anche noi. Potete riprovare.

**Comment by busaster** [comment]
ok, ora funziona e mi ritorna la data decorrenza residenza.
Mi viene tornata con l'informazione della timezone (2005-05-13+02:00) , mentre ad in altri servizi (il 3002 ad esempio) la timezone non viene ritornata.
Mi sembrava di aver capito da altre issues che tale informazione non  deve essere presente se non nelle date che contengono l'informazione dell'ora.
Quindi in questo caso non dovrebbe esserci, giusto ?

**Comment by rnapoli1983** [comment]
In realtà noi suggeriamo di inviare nella richiesta le date, senza timezone, quando sia significativa solo la parte del giorno/mese/anno.

Se la timezone è corretta vengono accettate anche date con Time Zone impostata.

Per quanto riguarda la risposta è coerente tra 3002 e 6001 per questo caso specifico (abbiamo verificato anche il servizio 3002).

E’ allo studio un intervento per armonizzare le date nella risposta (e passarle senza timezone).

La tematica richiede una certa cautela in quanto i servizi interagiscono con numerosi client comunali.
