### ISSUE TITLE
Subentro - Anomalie: EN309

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#383]
ambiente PRE-SUBENTRO - Comune di Faenza

buongiorno.

il cliente vorrebbe ridurre al minimo le anomalie evidenziate con il subentro e sta analizzando questa casistitica
EN309 - Indicare la data della sentenza o dell'atto di cessazione del matrimonio

a parte alcune situazioni per le quali l'anomalia è giustificata dall'assenza dei dati nell'archivio anagrafico, abbiamo un caso come quello di seguito per il quale avremmo bisogno di chiarimenti.

idSoggettoANPR: 18702223
- nei dati del soggetto non sono presenti gli estremi della sentenza, perchè si tratta di una "Cessazione effetti civili - D.L. 12 settembre 2014, n. 132"
- è presente invece l'atto di cessazione con relativa "dataFormazioneAtto"

a quale data fa riferimento l'anomalia?

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Stiamo verificando. Avvisiamo appena è possibile riprovare

**Comment by asqueglia** [comment]
E' stato rigenerato il file delle anomalie da subentro. Potete nuovamente scaricarlo. Il caso da voi indicato risulta corretto e non affetto dalla anomalia EN309. Grazie

**Comment by AMonopoliADS** [comment]
ok. grazie

**Comment by AMonopoliADS** [comment]
il cliente ha verificato che le anomalie in discussione non compaiono più.
grazie
