### ISSUE TITLE
[5011] : Sezioni elettorali popolamento tag <circosrizioneelezcircosc>

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3831]
Buongiorno
nello zip contenente le "tabelle campi standard" sono presenti 6 files.
Fare l'associazione tra i campi standard e i tag del tracciato 5011 è abbastanza intuitivo, tranne per il popolamento del tag <circosrizioneelezcircosc>.
Per popolare questo tag va considerata la descrizione in "LISTA_TAB_CIRC_CAMERA.xls" o quella in "LISTA_TAB_CIRC_SENATO.xls"?
Grazie

**Comment by frmariani** [comment]
Immagino che si riferisca al tag nel titolo circosrizioneelezcircosc: in questo caso il campo non è obbligatorio e non c'è uno standard specifico da utilizzare
