### ISSUE TITLE
Chiarimento tempistiche subentro elettorale ANPR

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3833]
Buongiorno,
siamo a richiedere un chiarimento riguardo alla data di scadenza entro la quale i comuni devono effettuare il subentro della parte elettorale su ANPR

In attesa di una cortese risposta, ringraziamo anticipatamente.

**Comment by frmariani** [comment]
Come disposto dal primo comma dell'articolo 7 del decreto 17 ottobre 2022,  i comuni dovranno registrare in Anpr i dati elettorali entro dodici mesi dalla comunicazione del Ministero dell'interno.
La data di attivazione comunicata dal Ministero è contenuta nella circolare 118 del 2022 e corrisponde al 1 dicembre 2022, pertanto la data ultima prevista per il subentro elettorale sarà il 1 dicembre 2023.
Naturalmente consigliamo di avviare per tempo la fase di test in modo da non subentrare a ridosso della scadenza.

Potete trovare tutta la documentazione  utile alla realizzazione dei servizi elettorali sul portale ANPR al seguente link
https://www.anpr.interno.it/area-tecnica/documentazione-tecnica/

Su questo canale risponderemo a qualsiasi problematica dovesse emergere al riguardo.

**Comment by SAlberto** [comment]
La ringrazio per la celere risposta.
Saluti
