### ISSUE TITLE
[5010] Anomalia EN562

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3847]
Inviata richiesta 5010 ID: 20230327094438860 ambiente Test, Comune 041069
restituisce anomalia EN562: Campo "Circoscrizione del territorio nazionale/Ripartizione della circoscrizione Estero per la Camera dei deputati" non corrispondente alla tabella di riferimento.

Potrei avere dei chiarimenti riguardo a tale anomalia?
Quale sarebbe il tag errato?
Quale valore si aspetterebbe nella richiesta?

Grazie
Roberta

**Comment by frmariani** [comment]
se <senatorepubblica>=S dovete indicare obbligatoriamente il valore <circoscrsenatorepubblica> utilizzando delle tabelle di riferimento indicate dal Ministero;
 se <cameradeputati>=S dovete indicare obbligatoriamente il valore <circoscrcameradeputati>  utilizzando delle tabelle di riferimento indicate dal Ministero.
Per i formalismi da utilizzare può consultare l'area tecnica del Portale ANPR
https://www.anpr.interno.it/area-tecnica/documentazione-tecnica/

**Comment by frmariani** [comment]
se "senatorepubblica"=S dovete indicare obbligatoriamente il campo "circoscrsenatorepubblica" utilizzando i valori standard di geolocalizzazione indicati dal Ministero;
se "cameradeputati"=S dovete indicare obbligatoriamente il campo "circoscrcameradeputati"  utilizzando i valori standard di geolocalizzazione indicati dal Ministero.
Potete trovare la documentazione tecnica aggiornate nell'area tecnica del Portale ANPR

https://www.anpr.interno.it/area-tecnica/documentazione-tecnica/

**Comment by frmariani** [comment]
Tabelle campi standard
