### ISSUE TITLE
[Subentro] File APR: dataPrimaIscrizioneComune

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#385]
Buongiorno,
avrei bisogno di un chiarimento per la data di prima iscrizione nel comune.
In particolare, quale sarebbe la data da inviare per il subentro nel caso di un cittadino iscritto per nascita il 01-01-1980, successivamente emigrato e infine immigrato il 01-01-2010 ? Iscrizione per nascita o per immigrazione?
Grazie

Eduardo Gira
Servizi Locali S.p.A

**Comment by Eduardo1977** [comment]
In attesa di sapere cosa si intende per 'dataPrimaIscrizioneComune', suppongo che l'attributo
MotivoIscrizioneAPR (Vedi tabella 07 Motivi iscrizione ANPR) dovrebbe dipendere sempre dalla prima iscrizione. Cioè come nell'esempio fatto sopra, in base alla data di prima iscrizione, il motivo iscrizione potrebbe essere per nascita o per immigrazione. Giusto?

Eduardo Gira
Servizi Locali S.p.A

**Comment by gcarbonin** [comment]
Nell'esempio sopra riportato, al subentro si invieranno i dati attuali **non quelli relativi alla precedente iscrizione che sono dati storici**.
La data di prima iscrizione è 01-01-2010 e il motivo (salvo verifica del Ministero dell'Interno) è immigrazione

**Comment by Eduardo1977** [comment]
Si grazie, è chiaro da tempo che si inviano i dati attuali e non quelli storici. In questo caso il dubbio viene solo perchè l'attributo è stato chiamato 'dataPrimaIscrizioneComune'. Non discuto sull'interpretazione che si può dare (nell'esempio precedente io avrei scommesso che fosse 'per nascita'), attendo di sapere quali dati servono a voi. Grazie.

**Comment by gcarbonin** [comment]
**La data di prima iscrizione è 01-01-2010 e il motivo (salvo verifica del Ministero dell'Interno) è immigrazione**

**Comment by gcarbonin** [comment]
Chiudo in quanto trattato nella issue collegata
