### ISSUE TITLE
[5010] Errore: Utente non abilitato 5

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3859]
Comune di Fossombrone, operatore Conti Camillo
Durante l'invio di 3 diverse comunicazioni 5010
IDANPR:
20230411085720387
20230411085725713
20230411090143168
per tutte ho l'errore  "Utente non abilitato 5"

Dal controllo fatto in WA l'operatore ha tutte le flag impostate correttamente.
Grazie

**Comment by Leonforte** [comment]
Buongiorno, il problema dovrebbe essere stato risolto, potete riprovare, grazie

**Comment by Hdemografici** [comment]
OK. Grazie.
