### ISSUE TITLE
Certificato residenza storico (tipoRichiesta=2)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#386]
ambiente di test Poggio a Caiano (PO);
soggetto iscritto prima del subentro senza data di decorrenza della residenza;
id operazione anpr 607559;
servizio 6001, richiesta certificato storico di residenza, tipoRichiesta = 2;
ANPR restituisce i dati per la costruzione locale del certificato.

1) Allegato alla issue 306 c'è un documento che spiega come in mancanza della decorrenza della residenza venga bloccata l'emissione del certificato storico di residenza.
Da quanto abbiamo testato sembra che il blocco non ci sia per il tipoRichiesta=2.

2) Nel citato documento allegato c'è una frase che non riesco a capire: "Una volta effettuata la rettifica di una o entrambe le date, occorre modificare le attuali funzionalità di certificazione per evitare di stampare sul certificato la residenza rettificata.". Cosa significa?

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
1) la richiesta dati non è la produzione del certificato e quindi il blocco non c'è
2) Significa che quando chiede il certificato, la residenza iniziale (trasmessa al subentro senza data di decorrenza) non viene stampata

**Comment by gcarbonin** [comment]
Ci sono altri commenti?
