### ISSUE TITLE
mutazione anagrafica bloccata per procedimento aperto con altro comune

### ISSUE THREAD

**Issue by Daniapavullo** [italia/anpr#3862]
Comune di Pavullo nel Frignano (MO)
Buongiorno, abbiamo un problema con la mutazione dell'individuo id anpr 154288384; la mutazione dal comune di TORRE DEL GRECO  è bloccata per un procedimento aperto in quel comune (con numero pratica anpr 65016119); abbiamo provato a contattare il Comune di Torre del greco ma senza esito (telefonicamente non rispondono, a pec e mail non abbiamo ancora avuto riscontro dal 03/04/2023. Potete aiutarci? Grazie

Dania Vandelli
053629916  - servizi.demografici@comune.pavullo-nel-frignano.mo.it

**Comment by Daniapavullo** [comment]
Buongiorno, dopo varie mail, pec e telefonate sono riuscita a contattare telefonicamente un collega di Torre del Greco a questo numero 081 8830535 ma non è riuscito a risolvere la situazione; a detta loro non risulta nessun problema sulla scheda del soggetto, ho spiegato che il procedimento aperto è identificabile dentro la web app anpr e che nelle varie mail e pec che ho inviato ho allegato le slide con il procedimento  di chiusura, hanno risposto che avrebbero detto al tecnico di controllare ma ad oggi la situazione non è sboccata. La ragazza ha il diritto a risultare in anagrafe nazionale e a poter fare il documento d'identità di cui è sprovvista, chiedo per cortesia se potete intervenire e convincerli a chiudere il procedimento!

**Comment by frmariani** [comment]
Ho provato a mettermi in contatto con il comune sia ieri che oggi ma non risponde mai nessuno.
Ho contattato la casa software per farmi contattare dal comune o per risolvere con urgenza la problematica.
Le farò sapere appena avrò notizie.

**Comment by frmariani** [comment]
La casa software Halley  dovrebbe aver gentilmente risolto il problema. 
Mi faccia sapere.

**Comment by Daniapavullo** [comment]
Risolto! Grazie mille per il prezioso aiuto.
Saluti
