### ISSUE TITLE
Malfunzionamento ANPR

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3864]
Buongiorno, 

Diversi nostri clienti non riescono più ad utilizzare i servizi di ANPR.
Dopo qualche minuto va in time-out restituendo il seguente errore:  504.0 GatewayTimeout.

Sulle dichiarazioni di residenza online invece riceviamo un errore più specifico:

ANPR: The remote server returned an unexpected response: (502) Bad Gateway.

E' possibile fare una verifica?

Saluti,

Jonathan

**Comment by siscomanpr** [comment]
Buongiorno
anche diversi comuni ci stanno segnalando da alcuni minuti errori di timeout o "Malformed content (from server)".
Anche i servizi sull'ambiente di test risultano non disponibili.

**Comment by mttfranci** [comment]
Si c'è un problema generalizzato su cui stiamo già lavorando.
Vi avviseremo appena abbiamo novità.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
@jonnyfx95  @siscomanpr 

l'anomalia dovrebbe essere stata risolta.
potreste darci un riscontro?

Grazie in anticipo.

Assistenza ANPR

**Comment by mttfranci** [comment]
w
