### ISSUE TITLE
ANPR non funziona

### ISSUE THREAD

**Issue by udasanlorenzo** [italia/anpr#3865]
qualcuno ha problemi con ANPR?

**Comment by jonnyfx95** [comment]
Si, diversi nostri clienti hanno segnato problemi di time-out su tutti i servizi

**Comment by siscomanpr** [comment]
Anche diversi nostri clienti ci stanno segnalando errori di timeout o errore "Malformed content (from server)".
Anche i servizi sull'ambiente di test risultano non disponibili.

**Comment by Hdemografici** [comment]
rileviamo il problema anche noi

**Comment by mttfranci** [comment]
Si c'è un problema generalizzato su cui stiamo già lavorando.
Vi avviseremo appena abbiamo novità.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
@udasanlorenzo  @jonnyfx95 @siscomanpr  @Hdemografici  
l'anomalia dovrebbe essere stata risolta.
potreste darci un riscontro?

Grazie in anticipo.

Assistenza ANPR

**Comment by siscomanpr** [comment]
Abbiamo verificato con un cliente ed i servizi anpr hanno ripreso a funzionare.
Confermiamo che anche l'ambiente di test ha ripreso a funzionare.
