### ISSUE TITLE
Non arriva la mail per verificare l'indirizzo mail inserito nel proprio profilo

### ISSUE THREAD

**Issue by J99Dani** [italia/anpr#3869]
Sto cercando di validare il mio indirizzo mail per inoltrare la richiesta di cambio residenza ma non arriva nessuna mail di validazione.
Ho provato ad utilizzare un indirizzo mail alternativo, a verificare nello spam, ad aspettare 1 ora... ma non arriva assolutamente nulla.
Non riesco ad inviare la richiesta di cambio residenza. Sono bloccato.

**Comment by gg3010** [comment]
Non riesco a ottenere la verifica della mail su anagrafe online. Non mi arriva la mail. Non mi fa proseguire

**Comment by deletX** [comment]
Anche a me niente email di validazione

**Comment by iVrs93** [comment]
Stesso problema anche per me. 
Aggiornato profilo con numero di telefono e email ieri veso le 20, ad ora dopo più di 12h la mail di convalida non sta arrivando

**Comment by dellacal** [comment]
E' da ieri sera che proviamo a validare una mail senza risultato...come possiamo fare per cambiare residenza se il sistema non funziona?

**Comment by CorlaOnline** [comment]
Confermo anche io ho lo stesso problema

**Comment by spdesign95** [comment]
anche a me stesso problema

**Comment by alessiaser** [comment]
anche io stesso problema

**Comment by alexx-gif** [comment]
Stesso problema

**Comment by iVrs93** [comment]
confermo ricezione ora 17:49 dopo averla richiesta ieri sera alle 20 circa

**Comment by mttfranci** [comment]
Salve ora la problematica dovrebbe essere risolta, avete ricevuto la mail di conferma adesso?
Saluti

Assistenza ANPR

**Comment by deletX** [comment]
Si grazie 👍

**Comment by PippoApps** [comment]
Salve,
stesso problema degli altri utenti.
Complimenti la PA su github mi sembra un'idea stupenda.

**Comment by J99Dani** [comment]
Segnalo nuovamente la stessa cosa. Una mia amica sta facendo cambio residenza e ancora una volta dopo aver atteso tanto tempo la mail di verifica non arriva.
Potete risolvere? Grazie.
