### ISSUE TITLE
Certificato residenza storico - Sembra iscritto ma è cancellato

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#387]
Ambiente di test Poggio a Caiano (PO)
Abbiamo cancellato il 26 ottobre una persona per emigrazione in comune non subentrato.
Abbiamo poi chiesto con WebApp il certificato di residenza storico, e ottenuto il documento che allego (ho oscurato i dati).

1) il certificato riporta "risulta iscritto con i seguenti dati" ma il soggetto non è più iscritto.

2) il certificato viene emesso nonostante l'iscrizione anagrafica sia antecedente al subentro (issue 277: Il comune di residenza è subentrato il 3 agosto quindi non si può richiedere uno storico al 1-8).

Filipazzi - Maggioli

![certificato 607125](https://user-images.githubusercontent.com/26787808/32062297-63cab360-ba74-11e7-97b6-c55f3fd067fe.JPG)

**Comment by gcarbonin** [comment]
1) Ci sono state molte contestazioni da parte vostra sul certificato storico di residenza che stiamo rivedendo. Avvertiamo quando possibile riprovare.  
2) per quale motivo non dovrebbe essere emesso il certificato ? Se il comune è subentrato il 3 agosto non si può chiedere lo storico al primo agosto  ma questa richiesta porta come data di riferimento 26 ottobre che è successiva al 3 agosto

**Comment by bfilipazzi** [comment]
Provo a spiegarmi meglio: nella issue 277 Gina Carbonin scrive "Il comune di residenza è subentrato il 3 agosto quindi non si può richiedere uno storico al 1-8", naturalmente in riferimento al caso trattato in quella issue.
Io avevo capito che non si può ottenere un certificato storico di residenza se la persona certificata ha una decorrenza dell'iscrizione anagrafica antecedente al subentro.
Mea culpa, mi sbagliavo. E sempre mea culpa è non avere considerato la data di riferimento.
Dipende da una mia forma mentis abituata a considerare lo storico di residenza come la sequenza degli indirizzi dalla iscrizione ad oggi.

Tuttavia rimango del parere che se mancano le informazioni non sia corretto rilasciare un certificato di residenza storico che riporta dati come quelli che seguono (ho alterato la descrizione della via, le date sono reali)

Risulta iscritta con i seguenti dati:
Comune di GORGONZOLA (MI) dal 12/07/1965
Indirizzo VIA DEI TULIPANI FIORITI N. 43 dal 14/10/2017

A mio parere la mancanza delle notizie sull'indirizzo dal 12/07/1965 rende manifestamente incompleto il documento. Questo sarebbe il caso in cui l'integrazione delle notizie mancanti è a carico del gestionale. Sto continuando a sbagliare?

Filipazzi - Maggioli

**Comment by MarcoMigliori** [comment]
Perdonatemi se intervengo ma comincio a avere dei dubbi che non ci intendiamo per il diverso significato che ognuno da al titolo.

Nella certificazione di ANPR, leggendo il documento emesso:
- titolo "CERTIFICATO STORICO DI RESIDENZA"
- ovviamente "CERTIFICA CHE NELL'ANAGRAFE NAZIONALE DELLA POPOLAZIONE RESIDENTE"
- "alla data del" ....

Ecco leggendo questi estremi, io penso a un certificato che mi faccia la fotografia della situazione anagrafica a quella data precisa. Non l'elenco degli eventi (indirizzi) precedenti.
Se interpreto bene, l'esempio di Filipazzi mi appare corretto nella interpretazione di ANPR:
_Risulta iscritta con i seguenti dati:
Comune di GORGONZOLA (MI) dal 12/07/1965
Indirizzo VIA DEI TULIPANI FIORITI N. 43 dal 14/10/2017_

Del resto inizialmente ANPR non sarebbe in grado di fare nessun altro tipo di certificazione storica per dati mancanti.
Il certificato che descrive Filipazzi, sarebbe nella mia interpretazione un nuovo certificato, che dovrebbe vedere cambiata la riga in grassetto "alla data del".  E che potrebbe essere emesso da ANPR in questa forma, esclusivamente dalla data del primo indirizzo al subentro in ANPR in poi.

**Comment by gcarbonin** [comment]
La frase "alla data del"  è corretta sia per indicare la situazione alla data sia la situazione fino a quella data.
In ogni caso, stante le osservazioni pervenute (non so chi vince tra storico di residenza e iscrizione per nascita), stiamo modificando il certificato storico attuale in modo che riporti correttamente la fotografia ad una data di riferimento; aggiungeremo un nuovo certificato (al momento senza nome) che NON utilizzerà una data di riferimento ma riporterà TUTTE le residenze registrate in ANPR.
Rispondo anche a B. Filippazzi: i controlli che caratterizzano  il  certificato che stiamo adeguando (la versione nuova non la vedete da nessuna parte perchè è in test da parte nostra) sono molteplici e comprendono sia la data di subentro del comune, sia  i dati della persona che, nel II esempio, NON ha una residenza in ANPR antecedente al 14-10-2017. Quindi nella nuova versione, se metto una data di riferimento antecedente al 14-10-2017 il certificato non sarà prodotto; se metto una data successiva, il certificato uscirà perchè al quella data la residenza c'è.

**Comment by ATropeano** [comment]
Propongo come nome del 

> nuovo certificato (al momento senza nome) che NON utilizzerà una data di riferimento ma riporterà TUTTE le residenze registrate in ANPR.

 
la dicitura **CERTIFICATO DI RESIDENZA CRONOLOGICO**

Alessio Tropeano - Datagraph s.r.l.

**Comment by bfilipazzi** [comment]
Ho cercato "Certificato di Residenza Cronologico" in Google e non ho trovato riscontri.
Mi permetto di osservare che non si tratta di un documento nuovo per gli uffici di anagrafe e per i soggetti che lo richiedono.
Ho consultato le pagine web di Milano e di Roma, con questi risultati:

Comune di Milano - Sito web
Certificato storico di residenza - Attesta le variazioni di residenza dell’intestatario a partire dalla prima iscrizione anagrafica a Milano.

Comune di Roma - Sito web
Il certificato storico di residenza (o storico-anagrafico) riporta le variazioni di residenza e di domicilio di persone residenti, immigrate o emigrate dal Comune di Roma, dal 1981 ad oggi. 

Filipazzi - Maggioli

**Comment by ATropeano** [comment]
Se, come mi pare, resta come nome del certificato che fotografa la residenza a una data ben precisa il nome **CERTIFICATO DI RESIDENZA STORICO**, credo che sia meglio che il "nuovo" certificato in elaborazione da Sogei, che riporterà la cronologia dei cambi di residenza disponibili in ANPR, abbia un nome diverso dal precedente... 

Se si decide che "tradizionalmente" e/o legalmente sia più giusto indicare come CERTIFICATO DI RESIDENZA STORICO, quello con la cronologia delle residenze allora bisognerà dare un nome diverso a quello che fotografa la residenza a una data... 

Alessio Tropeano - Datagraph s.r.l.

**Comment by Raffive** [comment]
Buonasera, quindi se ho capito bene nel caso mi fosse richiesto un certificato storico di residenza di tizio e supponendo che tizio sia residente:
Caso 1
Prima residenza ante 1990 (data del passaggio del mio comune dal cartaceo all'informatico)
Ricerca nel cartaceo e produzione a "mano" dalla data di prima residenza a oggi. - nessuna richiesta in anpr
Caso 2
Resistenza post 1990 ho due possibilità
a) certifico a mano fino alla data del 13/09 (data di subentro) e poi certifico la residenza dal 13/09 ad oggi in anpr
b) certifico tutto a mano senza interrogare anpr
c) certifico tutto da gestionale.
Scelgo la C
Sebbene comprenda che la prima iscrizione in anpr é il 13/09 il tizio ha abitato sempre nel Comune di Spinea e fintanto che ci sono i comuni..anpr resta sempre e per ora solo una banca dati come altre.
Raffaella
Spinea produzione

**Comment by Raffive** [comment]
Per rispondere ad Alessio si "chiama" già certificato storico alla data:
- di iscrizione 
- di cancellazione
E fanno parte dei certificati o attestazioni che l'ufficiale d'anagrafe rilascia ai sensi dell'articolo 33 e 35 c.4 del regolamento anagrafico ovvero certificato di residenza e stato famiglia..

**Comment by Raffive** [comment]
t) l'articolo 33 e' sostituito dal seguente: 

«Art. 33 (Certificati anagrafici). - 1. Fatti salvi i divieti di comunicazione di dati, stabiliti da speciali disposizioni di legge, e quanto previsto dall'articolo 35, l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta, previa identificazione, i certificati concernenti la residenza, lo stato di famiglia degli iscritti nell'anagrafe nazionale della popolazione residente, nonche' ogni altra informazione ivi contenuta. 

 2. Al rilascio di cui al comma 1 provvedono anche gli ufficiali d'anagrafe di comuni diversi da quello in cui risiede la persona cui i certificati si riferiscono. 

 3. Le certificazioni anagrafiche hanno validita' di tre mesi dalla data di rilascio.»; 

u) l'articolo 34 e' sostituito dal seguente: 

«Art. 34 (Rilascio di elenchi degli iscritti nell'anagrafe nazionale della popolazione residente e di dati anagrafici per fini statistici e di ricerca). - 1. Alle amministrazioni pubbliche che ne facciano motivata richiesta, per esclusivo uso di pubblica utilita', l'ufficiale di anagrafe rilascia, anche periodicamente, elenchi degli iscritti, residenti nel comune, in conformita' alle misure di sicurezza, agli standard di comunicazione e alle regole tecniche previsti dal decreto del Presidente del Consiglio dei ministri 10 novembre 2014, n. 194, e dall'articolo 58 del decreto legislativo 7 marzo 2005, n. 82. 

 2. L'ufficiale di anagrafe rilascia dati anagrafici, relativi agli iscritti residenti nel comune, resi anonimi ed aggregati, agli interessati che ne facciano richiesta per fini statistici e di ricerca. 

 3. Il comune puo' esigere dai richiedenti un rimborso spese per il materiale fornito.»; 

v) l'articolo 35 e' sostituito dal seguente: 

«Art. 35 (Contenuto dei certificati anagrafici). - 1. I certificati anagrafici devono contenere l'indicazione del comune e della data di rilascio; l'oggetto della certificazione; le generalita' delle persone cui la certificazione si riferisce, salvo le particolari disposizioni di cui alla legge 31 ottobre 1955, n. 1064, e la firma dell'ufficiale di anagrafe. 

 2. Non costituiscono materia di certificazione le notizie riportate nelle schede anagrafiche concernenti la professione, arte o mestiere, la condizione non professionale, il titolo di studio, il domicilio digitale, la condizione di senza fissa dimora e il titolo di soggiorno. 

 3. Il certificato di stato di famiglia deve rispecchiare la composizione familiare quale risulta dall'anagrafe all'atto del rilascio del certificato. 

 4. Previa motivata richiesta, l'ufficiale di anagrafe rilascia certificati attestanti situazioni anagrafiche pregresse. 

 5. Presso gli uffici anagrafici, gli iscritti esercitano i diritti di cui alla parte I, titolo II del decreto legislativo 30 giugno 2003, n. 196, sui dati contenuti nell'anagrafe nazionale della popolazione residente, nei limiti e nel rispetto delle modalita' previsti dal medesimo decreto legislativo.»

**Comment by ATropeano** [comment]
Chiarisco che le mie affermazioni precedenti si riferiscono al nome del certificato soprattutto dal punto di vista tecnico (quale certificato richiamare nella richiesta del WebService di certificazione - vedi tabella certificati ANPR di seguito): l'intestazione, quella presente nel certificato consegnato al cittadino, invece resta più legata a vincoli normativi...

Al momento il certificato storico disponibile in ANPR è uno solo (9 storico di Residenza) e, siccome, come mi è parso di capire, i certificati storici diventeranno due (uno che fotografa la residenza a una data e un altro che riporta tutte le residenze storiche), ci vogliono due nomi diversi per richiamarli oppure un parametro aggiuntivo che ne distingua il contenuto.

ID	  DESCRIZIONE
1	  Anagrafico di nascita
2	  Anagrafico di morte
3	  Anagrafico di matrimonio
4	  di Cancellazione anagrafica
5	  di Cittadinanza
6	  storico di Cittadinanza
7	  di Esistenza in vita
8	  di Residenza
9	  storico di Residenza
10	di Residenza AIRE
11	di Stato civile
12	di Stato di famiglia
13	di Stato di famiglia e di stato civile
14	di Stato di famiglia per iscritto in convivenza anagrafica
15	di Stato di famiglia AIRE
16	di Stato di famiglia con rapporti di parentela
17	di Stato Libero
18	Anagrafico di Unione Civile
19	di Contratto di Convivenza

**Comment by bfilipazzi** [comment]
In un precedente commento mi sono scusato per aver immaginato il certificato di residenza storico come una sequenza di indirizzi; ammetto di aver perso il nesso con questo argomento, ma osservo che ad oggi il "certificato storico di residenza" di ANPR produce una sequenza di indirizzi, come da allegato. Quindi forse quello che manca è il documento che certifica la residenza ad una data.
Filipazzi - Maggioli

![storico con variazioni](https://user-images.githubusercontent.com/26787808/32213801-07c56a0e-be1d-11e7-835f-a68632075051.JPG)

**Comment by bfilipazzi** [comment]
Riprendo un frammento da un precedente commento tratto dal sito del comune di Roma che spiega come lo storico di residenza riguardi "persone residenti, immigrate o emigrate dal Comune di Roma", che vuol dire va prodotto anche per gli emigrati. Perciò occorre adottare nel caso di emigrati una formula appropriata al caso, allego un esempio di persona (ambiente di test) che al momento dell'emissione del documento era stata cancellata ma che sembra ancora residente (per mancanza degli estremi di cancellazione).
Filipazzi - Maggioli

![certificato storico di cancellato](https://user-images.githubusercontent.com/26787808/32214389-f9be44ce-be1e-11e7-957e-263300c69047.JPG)

**Comment by bfilipazzi** [comment]
Concordo con Tropeano, deve essere chiaro cos'è il certificato "9 storico di residenza", e mi permetto di aggiungere che sarebbe opportuno che questo certificato continuasse a fare quello che fa oggi, cioè l'elenco delle variazioni di indirizzi.
Filipazzi - MAggioli

**Comment by gcarbonin** [comment]
Il tipo certificato 9 si chiamerà storico di residenza e continuerà a fare quello che fa oggi.
il nuovo avrà codice 20 e si chiamerà "storico di residenza alla data".
Stiamo completando i test. Contiamo di rilasciare tutto in test comuni e pre-subentro la prossima settimana (insieme ad altre modifiche sui certificati che riguardano i soggetti AIRE). metto un avviso al più tardi lunedì

**Comment by gcarbonin** [comment]
I certificati sono disponibili
