### ISSUE TITLE
Mail di Verfica non arriva

### ISSUE THREAD

**Issue by GiuStancaPalermo** [italia/anpr#3871]
Anche io ho lo stesso problema. Qualcuno ha risolto? grazie

**Comment by mttfranci** [comment]
Salve ora la problematica dovrebbe essere risolta, avete ricevuto la mail di conferma adesso?
Saluti

Assistenza ANPR

**Comment by GiuStancaPalermo** [comment]
Grazie

   Confermo che il problema è stato risolto

   Anmcora Grazie

   Giuseppe Stancampiano

   Da "Matteo" ***@***.***
   A "italia/anpr" ***@***.***
   Cc "GiuStancaPalermo" ***@***.***,"Author" ***@***.***
   Data Wed, 19 Apr 2023 08:56:56 -0700
   Oggetto Re: [italia/anpr] Mail di Verfica non arriva (Issue #3871)

   Salve ora la problematica dovrebbe essere risolta, avete ricevuto la mail di conferma adesso?
   Saluti

   Assistenza ANPR
