### ISSUE TITLE
Impossibilità cambio residenza portale ANPR per bug conferma email

### ISSUE THREAD

**Issue by alessiaser** [italia/anpr#3872]
Buongiorno,
non sono in grado di concludere una procedura per cambio residenza poichè nel profilo utente per verificare la mail non ricevo alcuna mail di verifica alla mia posta elettronica, neanche in spam.
In quanto tempo verrà sbloccata la situazione?

Grazie
Alessia

**Comment by matteomonizza** [comment]
Idem per me

**Comment by alexx-gif** [comment]
Uguale

**Comment by mttfranci** [comment]
Salve ora la problematica dovrebbe essere risolta, avete ricevuto la mail di conferma adesso?
Saluti

Assistenza ANPR

**Comment by alessiaser** [comment]
Ciao,
Ogni volta ricevo mail di utenti come me perché sono rimasta in copia.
Possibile eliminarmi dal loop?

Grazie
Alessia

Il giorno ven 15 dic 2023 alle 10:11 Matteo Franci ***@***.***>
ha scritto:
