### ISSUE TITLE
ANPR bug conferma email

### ISSUE THREAD

**Issue by Lux5256** [italia/anpr#3873]
Buonasera,
non sono in grado di concludere una procedura per cambio residenza poichè nel profilo utente per verificare la mail non ricevo alcuna mail di verifica alla mia posta elettronica, neanche in spam.
Vorrei sapere In quanto tempo verrà sbloccata la situazione?
!

**Comment by matteomonizza** [comment]
Idem per me

**Comment by iVrs93** [comment]
Richiesta ieri sera ore 20 circa, arrivata ora 
verificate questo thread per altri feedback https://github.com/italia/anpr/issues/3869

**Comment by matteomonizza** [comment]
Sembra di sì
