### ISSUE TITLE
cambio cognome/codice fiscale nuovo

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#388]
Spinea produzione.
Cambio cognome signora rumena.
Per cortesia ditemi la procedura corretta.
Raffaella

**Comment by gcarbonin** [comment]
La contatterà un collega.

**Comment by Raffive** [comment]
La collega mi ha contattato. Agenzia delle entrate  ha sbagliato  ad assegnare il cf.
Secondo voi dovrei io chiamare agenzia entrate di Roma.
Non se parla neanche.
Sistematelo voi.

**Comment by psaggini** [comment]
Se può essere utile, il problema era già stato sollevato con la issue #265 
Ci sono aggiornamenti sui tempi?

Grazie
Patrizia Saggini

**Comment by Raffive** [comment]
Buongiorno, 
ho sentito di nuovo lo sportello agenzia entrate di Venezia per sentire se avevano sistemato il CF della signora di cui sopra.
ha fatto una prova in diretta ma nulla.
il collega mi conferma che per loro l'operazione che riguarda un comune subentrato è bloccata.
quindi restiamo in fiduciosa attesa che a Roma qualcuno decida di fare il lavoro, nel frattempo la signora sta rimandando l'appuntamento per un rogito dal notaio dei settimana in settimana.
sarà interessante vedere come andrà la cosa quando subentrerà per esempio il comune di Venezia.
la prima domanda è: perché gli uffici periferici dell'agenzia delle entrate non possono fare questo servizio?
la seconda domanda è: forse possiamo farlo noi comune?
Grazie
Raffaella

**Comment by cmigliardi** [comment]
ti confermo l’avvenuto collegamento dei due codici fiscali segnalati da parte della Direzione Centrale di AE

**Comment by Raffive** [comment]
Grazie.
Raffaella
