### ISSUE TITLE
Operazione non effettuabile AE

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#3889]
Non si riescono a fare le iscrizioni altri motivi / nascita.
Viene riportato l'errore Operazione non effettuabile AE

Da webapp provando a fare un'interrogazione AE la pagina carica all'infinito e non produce alcun risultato.

Si attende riscontro

**Comment by frmariani** [comment]
dovrebbe essere più preciso; comune ed eventuale id dell'operazione fallita

**Comment by jonnyfx95** [comment]
Errore Anpr Cod: AEE97 - Operazione non effettuabile - Cognome: XXXXX Nome: WASSIM CF: XXXXXX-
2 Errore Anpr Cod: EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2023-05-04 13:54:16 , idOperazioneANPR 1276000323 - Cognome: XXXX Nome: XXXXX CF: XXXXX -

Credo possa essere un problema generalizzato, alcuni dei nostri enti hanno lo stesso errore e non riescono ad interrogare AE dalla webapp

**Comment by frmariani** [comment]
mi faccia sapere se il problema persiste

**Comment by jonnyfx95** [comment]
Problema rientrato.
