### ISSUE TITLE
Sentenza di delibazione di annullamento matrimonio

### ISSUE THREAD

**Issue by psaggini** [italia/anpr#389]
Facendo una prova - in ambiente di presubentro - di un invio di un Annullamento di Matrimonio per delibazione, (quindi lo stato civile del soggetto ridiventa CELIBE/NUBILE) ANPR ha dato questo errore bloccante:

*Per  tipo Mutazione annullamento matrimonio lo stato civile deve essere uguale a divorziato/a* e devono essere presenti i dati previsti in caso di cessazione/annullamento del matrimoni.

Da un'analisi normativa abbiamo verificato che:
- la sentenza di delibazione dell’annullamento della Sacra Rota riporta lo status dei coniugi a CELIBE/NUBILE;

- pre requisito dello stato civile precedente dei coniugi può essere sia quello di DIVORZIATO o CONIUGATO, a seconda che ci sia stato o meno un precedente divorzio civile.

Potete rimuovere l'errore?

Grazie
Patrizia Saggini - Anzola dell'Emilia

**Comment by gcarbonin** [comment]
Verifichiamo e facciamo sapere

**Comment by gcarbonin** [comment]
Mi riferivo al SW ovviamente

**Comment by gcarbonin** [comment]
Il controllo era già stato modificato il giorno 26. la richiesta era del 25. Se abbiamo individuato la mutazione giusta, l'operazione andrebbe comunque male in quanto la richiesta riguarda una persona coniugata ma i dati del matrimonio non ci sono; il coniuge,  a sua volta, è coniugato con un'altra.

**Comment by gcarbonin** [comment]
Avete riprovato?

**Comment by psaggini** [comment]
Scusi per il ritardo, a brevissimo le faremo sapere 
Grazie 


Da: "gcarbonin" <notifications@github.com> 
A: "italia/anpr" <anpr@noreply.github.com> 
Cc: "psaggini" <patrizia.saggini@comune.anzoladellemilia.bo.it>, "Author" <author@noreply.github.com> 
Inviato: Venerdì, 10 novembre 2017 8:02:28 
Oggetto: Re: [italia/anpr] Sentenza di delibazione di annullamento matrimonio (#389) 



Avete riprovato?

**Comment by Finalmentesubentrati** [comment]
Anche noi Abbiamo lo stesso problema
ASP.anagrafenet_registrazioneeventidivorzio_ascx.RegistraEvento(): System.Exception: ERRORE DA ANPR: 
ES113 - Per tipo Mutazione annullamento matrimonio lo stato civile deve essere uguale a divorziato/a e devono essere presenti i dati previsti in caso di cessazione/annullamento del matrimonio

**Comment by azabatta** [comment]
Si richiede cortesemente  un identificativo per poter  analizzare la richiesta: id operazione di ANPR o id operazione del comune.
Grazie

**Comment by ATropeano** [comment]
Scusate per il ritardo. Oggi ho rifatto l'operazione in ambiente di Presubentro - Comune Anzola dell'Emilia, per un caso nuovo e non ho avuto più l'errore segnalato sopra (vedi soggetto Anpr 10213444).
Grazie.
Alessio Tropeano
