### ISSUE TITLE
Errore CAST Assegnazione ruoli

### ISSUE THREAD

**Issue by Crotta** [italia/anpr#3896]
Comune di Crotta d'Adda

Per iniziare le operazioni per il subentro dei dati elettorali, abbiamo tentato di abilitare l'utente dell'operatore che già opera in ANPR (con smart card funzionante e che ha anche il ruolo di ALP-ALS) anche per l'elettorale.
Tuttavia, sia utilizzando la smart card del Sindaco, sia la smart card dell'ALS, compare il messaggio di errore: "Errore CAST Assegnazione ruoli"
Come risolvere?
Grazie

Serena Sudati

**Comment by adominicis** [comment]
Buonasera sig.ra Sudati,
la informo che il profilo ELETTORALE sulla sua utenza ora è correttamente abilitato.

Cordiali saluti

ASSISTENZA ANPR
