### ISSUE TITLE
Web-App Registrazione- Mutazione Famiglia/Convivenza sequenza videate

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#39]
Data test- 16/03/2017 - Ambiente test (dptest)
Dopo aver ricercato il soggetto (o la famiglia in alternativa), ed aver compilato il pannello Dati dell'operazione ed avere confermato, viene visualizzato il pannello Completa l'operazione invece di Residenza. In questo caso l'operatore può erroneamente premere il pulsante Salva e chiudi e in tal caso compare il messaggio fuorviante "La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata (Codice: EN238)". Un messaggio più chiaro potrebbe essere "Prima di salvare è necessario compilare il pannello Residenza", meglio sarebbe che  il sistema aprisse la videata di Residenza nel momento opportuno. 
Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Quale operazione?

**Comment by annamariaGillone** [comment]
Domani le recupero i dati o ricreo il test. E' comunque un problema di flusso di videate che si presenta ogni volta che si effettua una Mutazione di famiglia/Convivenza.

**Comment by annamariaGillone** [comment]
Abbiamo ricreato il caso di test:
ID_SOGGETTO ANPR 975558
Mutazione famiglia/convivenza ID 384852 in data 22/03/2017 - Istanza di parte

**Comment by gcarbonin** [comment]
Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
Può riprovare. Mi faccia sapere se va bene

**Comment by annamariaGillone** [comment]
Mi dispiace ma non è cambiato nulla.
Il flusso di navigazione dovrebbe passare dalla prima videata "Dati dell'operazione" a "Residenza" invece passa direttamente a "Completa l'operazione".

**Comment by gcarbonin** [comment]
Può riprovare attendo un riscontro

**Comment by annamariaGillone** [comment]
Adesso va bene. Grazie
