### ISSUE TITLE
[web-service] risposte: testoErroreAnomalia 

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#390]
salve

con la presente segnalo due tipologie di messaggi che arrivano in risposta dal web-service, chiedendone, possibilmente, la modifica per semplificarne la comprensione.

1. 
ws 5008: mutazione non accettata per incoerenza della decorrenza rispetto all'ultima variazione registrata.
il messaggio contiene le date in due formati diversi... se possibile, uniformare.
"EN389      La data decorrenza 14-09-2017 dell'operazione non puo' essere inferiore alla data decorrenza 09-OCT-17 dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto"

2.
ws 5008: comunicazione di mutazione che, all'interno dell'xml, contiene anche dati che non sono variati 
il web-service accetta la comunicazione ma segnala che i dati per i quali non esiste un tipo di mutazione collegato non sono stati aggiornati, tutto corretto, ma il messaggio è quello che segue e non è di facile comprensione:
"EN396      i dati relativi a generalita da modificare e/o statoCivilecittadinanzaatto nascitapaternitamaternitamatrimoniocensimento non sono stati acquisiti tipo mutazione 12151011126 non indicato/i nella richiesta"

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno, stiamo verificando. Le facciamo sapere appena possibile

**Comment by asqueglia** [comment]
E' previsto a breve un aggiornamento degli ambienti di presubentro e test comuni. In tale occasione provvederemo alla modifica dei controlli citati. Grazie per la segnalazione
