### ISSUE TITLE
PROBLEMI ACCESSO WEB APP ANPR 

### ISSUE THREAD

**Issue by frmariani** [italia/anpr#3903]
A fronte delle numerose segnalazioni riguardanti problematiche di accesso al sito ANPR tramite smart card, nelle more della risoluzione della problematica, invitiamo per il momento a **NON ESEGUIRE** eventuali aggiornamenti proposti dal browser Mozilla Firefox. 
Buon Lavoro

**Comment by UpiTorino** [comment]
Buongiorno,
a tutt'oggi, su alcune postazioni, l'accesso restituisce 
Codice di errore: SSL_ERROR_DECRYPT_ERROR_ALERT
Non sono stati effettuati aggiornamenti Mozilla e ripulito cache prima di accedere.
Buona settimana

Anna Maria AIMONE
UPI e Codici Fiscali
Torino

**Comment by candial** [comment]
Buongiorno.
Ancora oggi non riesco ad accedere ad anpr. 
Mi da sempre l'errore
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

**Comment by DanielaTaroni** [comment]
Buongiorno dal Comune di Faenza.
Non riusciamo ancora ad accedere alla WEB APP di ANPR. Volevo chiedere per quando è prevista la risoluzione del problema.
Grazie.

Daniela Taroni - Comune di Faenza

**Comment by ComunediCuneo-HelpDesk** [comment]
Buongiorno da Comune di Cuneo.
Anche noi con Firefox continuiamo ad avere difficoltà, attendiamo vostre.

Andrea Bonfiglio - Comune di Cuneo

**Comment by frmariani** [comment]
Il comune di Cuneo è stato raggiunto per le vie brevi ed il problema è stato risolto.
Anna Maria hai risolto ?
I comuni di Candia Lomellina e Faenza hanno risolto ?
Grazie

**Comment by DanielaTaroni** [comment]
Buongiorno,
Faenza non ha risolto.

Quando proviamo ad accedere con firefox compare questo messaggio:


_Connessione sicura non riuscita

Si è verificato un errore durante la connessione a dp2.anpr.interno.it. Un modulo PKCS #11 ha restituito il valore CKR_GENERAL_ERROR: questo significa che si è verificato di un errore irreversibile.

Codice di errore: SEC_ERROR_PKCS11_GENERAL_ERROR

    La pagina che si sta cercando di visualizzare non può essere mostrata in quanto non è possibile verificare l’autenticità dei dati ricevuti.
    Contattare il responsabile del sito web per informarlo del problema.

Ulteriori informazioni…_



Provando con Edge con la versione di SaveDive22 e dopo aver importato i certificati il messaggio è il seguente:


This XML file does not appear to have any style information associated with it. The document tree is shown below.
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Body>
<env:Fault>
<faultcode>env:Client</faultcode>
<faultstring>Aborting...Postazione certificate does not seem to carry a valid CN name (from client)</faultstring>
</env:Fault>
</env:Body>
</env:Envelope>


Daniela Taroni
Comune di Faenza

**Comment by ComunediCuneo-HelpDesk** [comment]
Ciao Daniela,
Per me ha funzionato Edge (Chrome va anche bene) e SafeDive 4.9.1 e da ANPR mi hanno riferito che la soluzione attuata va bene, Firefox fino a nuove comunicazioni non è utilizzabile.

Hai importato il certificato postazione nei certificati personali?
Il SafeDive l'hai installato in maniera pulita (rimosso il vecchio e reinstallato il nuovo)?
Ti arriva la richiesta del PIN tramite SafeDive su Edge?
Stai usando delle SCO a 8 digit?
Hai provato con una utenza Windows pulita(utente con profilo nuovo) oppure pulire la cache di Edge?

Ciao.

Andrea Bonfiglio
Comune di Cuneo

**Comment by candial** [comment]
Buongiorno, il comune di Candia Lomellina non ha risolto. Continua lo stesso problema. Ho provato anche firefox e edge ma il risultato non cambia. 
Tra l'altro io ho la SCO con pin a 5 caratteri.
Ho già fatto due chiamate al numero verde e l'ultima l'ho fatta venerdì: mi hanno confermato che ci sono problemi, ma non mi hanno ancora richiamato.

Rita Gurian
Comune di Candia Lomellina

**Comment by frmariani** [comment]
Comune di Faenza e Comune di Candia Lomellina gentilmente attendete la nostra telefonata; sarete contattati in giornata.

**Comment by candial** [comment]
Buongiorno. Per Candia il problema e' stato risolto con l'assistenza Sogei, che ringrazio moltissimo per la gentilezza e la professionalita'.
Ora riesco ad accedere alla web app di ANPR con Chrome e dopo avere disinstallato UKC di Infocamere (ho la firma digitale con Infocamere)

Grazie a tutti

Rita Gurian
Comune di Candia Lomellina

**Comment by frmariani** [comment]
Grazie per il feedback.

**Comment by UpiTorino** [comment]
Buongiorno,
a Torino siamo ancora bloccati.
Cordiali saluti
UpiTorino

**Comment by DanielaTaroni** [comment]
Comune di Faenza: siamo stati contattati dall'assistenza ed abbiamo risolto.
Grazie.

Daniela Taroni

**Comment by gpannullo** [comment]
Salve Comune di Aversa, ho provato come indicato nel workaround sia con edge che chrome ma non va, ho anche fatto il downgrade di firefox ma ancora non va, ho bisogno di supporto, siamo bloccati con la webapp.
Attendo un contatto 0815049122
Giuseppe Pannullo

**Comment by UpiTorino** [comment]
Buongiorno,
per il Comune di Torino i recapiti sono i seguenti 01101125388 - 01101125028 - 01101125574
Cordiali saluti
UpiTorino

**Comment by frmariani** [comment]
I comuni di Aversa e Torino hanno risolto con l'assistenza Sogei

**Comment by gpannullo** [comment]
> Salve Comune di Aversa, ho provato come indicato nel workaround sia con edge che chrome ma non va, ho anche fatto il downgrade di firefox ma ancora non va, ho bisogno di supporto, siamo bloccati con la webapp. Attendo un contatto 0815049122 Giuseppe Pannullo

Contattato oggi dalla Sogei che ringrazio, con il workaround sopra indicato si è riusciti ad accedere con Edge. Il nostro problema era legato al pacchetto applicativo denominato **Bit4id UKC** che non faceva attivare SafeDive. Noi siamo nuovamente UP

**Comment by gigconte** [comment]
Buongiorno
dal Comune di Guidonia riscontriamo gli stessi problemi di Faenza (e non solo) per accedere alla web app ANPR: 
- con Firefox **Codice di errore: SSL_ERROR_DECRYPT_ERROR_ALERT** 
- con Chrome, solo su alcuni pc, permane l'errore **Aborting...Postazione certificate does not seem to carry a valid CN name (from client)**

Abbiamo aggiornato il software SafeDive 4.9.1 ma il problema persiste.

Ticket aperto a Sogei il 15/5/2023 ma per adesso nulla di nuovo e dal call center non ci sanno dare indicazioni su possibili soluzioni.
Avete altre possibili soluzioni?
Luigi

**Comment by adominicis** [comment]
Buongiorno Luigi,
può fornirmi gentilmente un contatto diretto dove poterla chiamare?

Andrea

**Comment by gigconte** [comment]
> Buongiorno Luigi, può fornirmi gentilmente un contatto diretto dove poterla chiamare?
> 
> Andrea

0774301307
ma attualmente c'è un problema sulla linea che risulta isolata e che speriamo venga risolto in giornata.

**Comment by adominicis** [comment]
esatto, non riesco a contattarla. riprovo nel pomeriggio

**Comment by uimartinsicuro** [comment]
Buongiorno,
abbiamo gli stessi problemi di accesso come il Comune di Guidonia, i nostri recapiti sono i seguenti 0861765560 - 0861768232 - 0861768234.
Cordiali saluti

Comune di Martinsicuro

**Comment by adominicis** [comment]
> Buongiorno, abbiamo gli stessi problemi di accesso come il Comune di Guidonia, i nostri recapiti sono i seguenti 0861765560 - 0861768232 - 0861768234.
> 
> Cordiali saluti Comune di Martinsicuro

Buonasera, 
ho provato a chiamare tutti i recapiti e dopo una lunga attesa, tutte le chiamate sono state inoltrate ad una sede distaccata che mi ha indicato di riprovare alle 17.30. 

Andrea

**Comment by gigconte** [comment]
> > Buongiorno Luigi, può fornirmi gentilmente un contatto diretto dove poterla chiamare?
> > Andrea
> 
> 0774301307 ma attualmente c'è un problema sulla linea che risulta isolata e che speriamo venga risolto in giornata.

Buongiorno
ci possiamo sentire dopo le 12.30 oppure lunedì 29/5 può contattare il collega al 0774301388.
Grazie mille

**Comment by gigconte** [comment]
> > Buongiorno, abbiamo gli stessi problemi di accesso come il Comune di Guidonia, i nostri recapiti sono i seguenti 0861765560 - 0861768232 - 0861768234.
> > Cordiali saluti Comune di Martinsicuro
> 
> Buonasera, ho provato a chiamare tutti i recapiti e dopo una lunga attesa, tutte le chiamate sono state inoltrate ad una sede distaccata che mi ha indicato di riprovare alle 17.30.
> 
> Andrea

Confermo di aver risolto i problemi riscontrati con Chrome grazie al contributo degli operatori di SOGEI (Andrea :-) )

Su alcune postazioni è stato sufficiente importare il certificato di postazione su Chrome, su altre è stato necessario cambiare il certificato e come terzo caso è stato necessario rimuovere e reinstallare il SafeDive anche il 2020 v.4.2 va bene.

Luigi

PS: Con firefox invece la situazione non è cambiata: non funziona...pazienza!

**Comment by cvignati** [comment]
> Buongiorno, chiedo la possibilità di essere contattati per le opportune configurazioni per poter ritornare ad utilizzare la WebApp ANPR.
> 
> Vignati - Comune di Villa Cortese [demografici@comune.villacortese.mi.it](mailto:demografici@comune.villacortese.mi.it) 0331434433
> 
> Grazie

Seguita tutta la procedura, confermo il funzionamento sulla mia postazione. Nei prossimi giorni verifichero' anche la postazione la cui collega ha la firma di InfoCamere.

Grazie mille
Claudio Vignati
Comune di Villa Cortese

**Comment by CGIRELLI-HUB** [comment]
Buongiorno, a fronte dei problemi di accesso alla WebApp chiediamo se è prevista una pubblicazione aggiornata della procedura corretta nella pagina GUIDA ANPR. 

Grazie 
Cordiali saluti

Cinzia Girelli
GPI S.p.A.

**Comment by CGIRELLI-HUB** [comment]
Si richiede di contattare il comune di Guiglia al nr. 059709922 Sig.ra Merighi poichè da stamattina non accede più alla webapp - provato soluzione del Comune di Cuneo il pc presentava versioni di IDP + SAFEDRIVE vecchi, disinstallato tutto reinstallato SAFEDRIVE V. 4.9.1 riavviato pc - la smart card (pin 8 cifre) viene letta. Da Edge dopo la lettura del certificato di postazione va in errore ERR_CONNECTION_TIMED_OUT, in Chrome sempre dopo lettura del cert. di postazione da errore ERR_BAD_SSL_CLIENT_AUTH_CERT - Non sono mai entrati con Mozilla presente con versione 112.0.1 - 
Non saprei cos'altro provare potete contattare il comune cortesemente?  Grazie
Cinzia Girelli
GPI SpA

**Comment by frmariani** [comment]
Di seguito i link ai nuovi driver da utilizzare con le carte del produttore ST Microelectronics - Infocert

Windows: https://d2nu8i0ja8i6qk.cloudfront.net/driver/SafeDive2022v.4.12.0_setup.exe 
Mac: https://d2nu8i0ja8i6qk.cloudfront.net/driver/SafeDive2022_v4_12_0_Universal.pkg 
Linux: https://d2nu8i0ja8i6qk.cloudfront.net/driver/SafeDive2022-4.12.0_x64.sh 

Rimaniamo a disposizione.

**Comment by ComunediCuneo-HelpDesk** [comment]
Faranno funzionare anche Firefox?
Grazie e Buona Serata

Andrea Bonfiglio
S.E.D. - Comune di CUneo

**Comment by dmazelli** [comment]
Buongiorno,
dai primi test effettuati vi confermiamo che la funzionalità su Firefox è stata ripristinata.
La configurazione di Firefox rimane la stessa precedente, è sufficiente solo reinstallare il driver aggiornato.
saluti.

**Comment by ComunediCuneo-HelpDesk** [comment]
Grazie, sono comunque certificati entrambi i browser (Edge e Firefox), giusto?

Buona Giornata.

Andrea Bonfiglio
S.E.D. - Comune di Cuneo

**Comment by dmazelli** [comment]
Si , l'accesso avviene con entrambe.
Per i Browser di tipo chromium potrebbe essere necessario utilizzare l'utility Safedive manager 2022. 
Non sempre infatti la propagazione dei certificati nello store avviene istantaneamente.
avviando il manager e andando su "utilità" è possibile forzare l'importazione attraverso il pulsante alla voce "importa i certificati nell'archivio personale" . 
Tale utility è disponibile a partire da Safedive 4.9.1.

**Comment by ComunediCuneo-HelpDesk** [comment]
Grazie Infinite!

Buonagiornata.

**Comment by CGIRELLI-HUB** [comment]
Buongiorno con l'aggiornamento indicato è stato risolto il problema di accesso per il comune di Guiglia Smart Card modello Infocert pin 8 cifre.

Permangono però problemi di accesso mediante smart card Aruba per molti comuni della provincia di Trento che hanno in dotazione la smart card di tipo Aruba (primi lotti).  Abbiamo fatto varie prove su alcuni utenti, in alcuni casi non era installato l'aggiornamento dell'IDP 6.47 ma nonostante l'installazione e la configurazione di Firefox con le varie .dll indicate ancora nelle guide operative di quel tempo non c'è stato modo di accedere. A seconda del browser utilizzato gli errori sono SSL_ERROR_DECRYPT_ERROR_ALERT, ERROR_SSL_CLIENT_AUTH_SIGNATURE_FAILED e poi il sito va in dp2. 

L'IDP legge la Smart card, pin valido, certificati presenti sia dalle Opzioni Internet che in Firefox su gestione sicurezze. 

Un solo utente ci ha indicato di aver fatto riattivare dal loro ced IE ed è riuscito ad accedere.  Questa ultima "soluzione" mi sembra piuttosto borderline perchè IE non è quasi più in uso, infatti tutti i pc provati sono passati a Windows10. Ci chiediamo se il mancato accesso possa essere in relazione ad eventuali aggiornamenti del sistema operativo del singolo client, e se potrebbe essere consigliabile dire ai clienti di richiedere delle nuove smart card o se avete una soluzione anche per questa tipologia di smart card/configurazione pc.  Abbiamo provato su un utente (comune Mezzocorona) l'attivazione di IE ma in questo caso ci ha dato un errore sui TLS. Quindi non credo che utilizzare IE sia una soluzione stabile. 

Avete dei consigli da fornirci? Diversamente dovremo rimandare al Vostro servizio di assistenza le segnalazioni dei vari comuni.

Grazie 
Cordiali saluti

Cinzia Girelli
GPI SpA
