### ISSUE TITLE
mancata visualizzazione pratica cambio residenza

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#3904]
Buongiorno,
quando tentiamo di aprire la pratica n. 28218684 compare una videata bianca.
La cittadina risulta regolarmente residente nel nostro comune.
Prima di contattare la cittadina per far rifare la dichiarazione vorremmo sapere che tipo di problema c'è.
Grazie
Raffaella 
Venezia

**Comment by gppbarone** [comment]
Salve,
abbiamo verificato c'è stato un problema temporaneo, può riprovare ad aprire la pratica n. 28218684.

Saluti,
Assistenza ANPR

**Comment by raffaella30174** [comment]
Buongiorno,
pratica visualizzata.
grazie
Raffaella
