### ISSUE TITLE
Schede cittadini di test per richieste di residenza non accessibili

### ISSUE THREAD

**Issue by busaster** [italia/anpr#3907]
Buongiorno,

non riusciamo più ad accedere a "https://dptest3.anpr.interno.it/cns" con el credenziali di prova che erano state assegnate a due soggetti che da tempo utilizziamo per testare le funzionalità di acquisizione richieste di cambio residenza.
Quale può essere il problema ?
Come possiamo risolvere ?

Grazie

**Comment by busaster** [comment]
Oggi riesco ad accedere ma ho questo blocco : "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Potete per favore verificare e sbloccare, è **indispensabile** avere accesso a questa piattaforma per i nostri tests di non regressione.

Grazie

**Comment by migmar68** [comment]
Sollecitiamo l'esigenza di poter testare questo ambiente, per risolvere problematiche sollevate dai Comuni, grazie
Marco Migliori
Maggioli

**Comment by apaolacci** [comment]
Salve,
potete riprovare ad accedere all'ambiente di test comuni? Adesso dovrebbe funzionare.

Assistenza ANPR
Saluti,

**Comment by busaster** [comment]
Confermo, ora riusciamo ad accedere. 
Grazie
