### ISSUE TITLE
Consolato di Manchester scomparso nel file "Stati Territori Consolati – xls" del 24/03/2023

### ISSUE THREAD

**Issue by tizpav** [italia/anpr#3908]
Buongiorno,
segnalo che nell'ultimo file "Stati Territori Consolati – xls" pubblicato (Aggiornamento del 24 marzo 2023) manca il Consolato di Manchester.

**Comment by ncapozzi** [comment]
Il Consolato di Manchester è presente a riga 30 (cod. 2310604)
