### ISSUE TITLE
[5008] acquisto cittadinanza con cambio di cognome

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#391]
buongiorno.

il cliente, in ambiente di produzione, deve procedere con un acquisto di cittadinanza con contestuale cambio di nome.
abbiamo fatto una simulazione in ambiente di test per avere certezza del giro da intraprendere, ma sappiamo che lì l'integrazione con AE è parziale...

pertanto vi chiedo conferma che il procedimento sia giusto, al fine di dare le corrette indicazioni al cliente.

la comunicazione contiene le seguenti variazioni:
- cognome
- cittadinanza
- atto di nascita
il tutto viene inviato con un'unica transazione, all'interno della quale vengono segnalate le seguenti mutazioni:
1 - dati anagrafici
2 - cittadinanza
15 - atto di nascita
ed il check gestioneCF viene valorizzato a '1'.

il web-service ritorna il seguente errore:
EN125 - E - Per richiesta attribuzione CF o omocodice, il codice fiscale non deve essere valorizzato

nella richiesta XML il codice fiscale (quello già in possesso del cittadino) è stato volutamente omesso, proprio per dare senso alla richiesta di attribuzione.

è un problema dell'ambiente di test, oppure dobbiamo procedere diversamente?

grazie.
Alessandro Monopoli ADS

(rif. ambiente di TEST - Comune di Faenza - idOperazione 2017002144)

**Comment by gcarbonin** [comment]
Il messaggio esce in quanto avete richiesto l'attribuzione del codice fiscale. Questo non si deve fare quando  si cambia il cognome. Avete indicato cosi' perche' ci troviamo in ambiente di test?

**Comment by AMonopoliADS** [comment]
si è stata una prova, xchè il precedente tentativo (idOperazione 2017002140), nel quale NON abbiamo indicato il check gestioneCF, ci ha segnalato
EN146 - E - Se codice fiscale assente pu essere richiesta solo un attribuzione di CF o omocodice

**Comment by AMonopoliADS** [comment]
il cliente chiede aggiornamenti rispetto a questa segnalazione, è possibile avere un riscontro?
grazie

**Comment by gcarbonin** [comment]
In ambiente di pre-subentro (o test), se il codice fiscale non esiste (è sufficiente una interrogazione tramite WA), occorre chiedere l'attribuzione senza indicare il CF; se il codice fiscale dovesse essere già presente (perchè è stato attribuito ad un test precedente), si indica il codice fiscale VECCHIO nella richiesta con il nuovo cognome, senza indicare gestioneCF

**Comment by AMonopoliADS** [comment]
siccome l'operazione dobbiamo eseguirla in produzione, valgono le stesse indicazioni:
"se il codice fiscale dovesse essere già presente (perchè è stato attribuito ad un test precedente), si indica il codice fiscale VECCHIO nella richiesta con il nuovo cognome, senza indicare gestioneCF"
?

**Comment by gcarbonin** [comment]
In produzione codici fiscali sconosciuti in AT dipendono soltanto da dati diversi tra comune e AT.
Occorrerebbe una verifica.
Mi deve mandare il codice fiscale sulla mia mail: questi problemi non si possono verificare così.

**Comment by AMonopoliADS** [comment]
ok.

x la problematica in ambiente di PRODUZIONE, prendiamo le informazioni necessarie e le inviamo alla Sua mail. 
in generale, l'intenzione era quella di conoscere le modalità "standard" per eseguire una comunicazione di questo tipo, ovvero: la mutazione del cognome che potrebbe produrre la variazione del codice fiscale (ho visto altre segnalazioni al riguardo, ma non mi sembra di avere trovato indicazioni specifiche)

x la problematica in ambiente di TEST, abbiamo provato a seguire le indicazioni date.
la comunicazione di mutazione viene inviata con:
- codiceFiscale vecchio valorizzato tra le generlitaPerRicerca
- nuovo cognome e nome tra le generalitaDaModificare
- gestioneCF non indicato all'interno della listaControlli
il web-service ritorna l'errore:
EAM91 - E - Richiesta incongruente - soggetto NON marcato ANPR
(rif. ambiente di TEST - comune di Faenza - idOperazione 2017002157)

**Comment by gcarbonin** [comment]
In test il codice fiscale c'è? avete fatto l'interrogazione AT?

**Comment by AMonopoliADS** [comment]
il codice fiscale è stato acquisito dalla risposta_comune della comunicazione di iscrizione anagrafica, ed ha queste caratteristiche:
```
<validitaCF>1</validitaCF>
<dataAttribuzioneValidita>2017-10-31+01:00</dataAttribuzioneValidita>
```
(rif. ambiente di TEST - Comune di Faenza - idOperazione 2017002142)

la "Consultazione AE" da web-app del codice fiscale riporta come esito:
codice fiscale presente in AT

**Comment by gcarbonin** [comment]
E' uno dei problemi in fase di analisi con l'Agenzia delle Entrate. E' prevista un incontro la prossima settimana. Per ora per completare l'operazione occorre impostare il valore "3" nel campo gestionCF

**Comment by gcarbonin** [comment]
L'intervento è stato completato
