### ISSUE TITLE
COMUNE DI CIVITA CASTELLANA indirizzo ip da abilitare 

### ISSUE THREAD

**Issue by lferrelli** [italia/anpr#3913]
Buongiorno,
sono Luca Ferrelli tecnico della WE-COM SRL partener di PADIGITALE SPA, il Comune di Civita Castellana è passato da applicativo Maggioli a Urbi PaDigitale, i malfunzionamenti non consentono l'accesso alla piattaforma anpr e pertanto come ogni nuovo cliente WECOM abbiamo l'esigenza e la necessità di modificare dalla sezione della Piattaforma ANPR AMMINISTRAZIONE -> INFORMAZIONI AGGIUNTIVE l'indirizzo ip da abilitare nello specifico:
NOTA BENE: va indicato l'indirizzo completo dell'endpoint SOLO SE il Comune ha implementato un servizio Web di ricezione delle notifiche inoltrate dal Sistema ANPR (in caso di dubbi chiedere al fornitore software):
il nostro indirizzo IP da abilitare è185.140.152.133
Il cliente rimane bloccato e non può gestire con il nostro applicativo i demografici.
Si richiede intervento con la massima urgenza.
Potete contattarmi al cellulare 3335487889

Cordiali saluti
Luca Ferrelli

**Comment by frmariani** [comment]
il problema è stato risolto con l'assistenza Sogei
