### ISSUE TITLE
[5008] Completamento dati: errore EN331 - Non e' possibile inserire contemporaneamente diversi tipi di legame

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3917]
Buongiorno,

stiamo effettuando delle prove sulle convivenze di fatto ed inviando una mutazione di tipo 20 (completamento dati) otteniamo l'errore 

EN331 - Non e' possibile inserire contemporaneamente diversi tipi di legame

Ambiente di TEST PISA
Operazione ANPR 55994632

Potete aiutarci a capire come risolvere?
Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by frmariani** [comment]
come specificato dal controllo, con la mutazione 20 non è possibile inserire contemporaneamente legami diversi; nell'operazione è presente il matrimonio e la  convivenza.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
