### ISSUE TITLE
Errore CAST Assegnazione ruoli

### ISSUE THREAD

**Issue by Githubanpr** [italia/anpr#3919]
Buongiorno, sono Maria Laura Fulgheri e lavoro nei servizi demografici del Comune di Villaurbana.
abbiamo necessità di attivare il profilo di ufficiale elettorale ma seguendo le indicazioni e flaggando sulla voce elettorale  compare ERRORE CAST Assegnazione ruoli.

  Come possiamo risolvere la situazione?
grazie

**Comment by Githubanpr** [comment]
Preciso che l'operatore da abilitare è la Sig.ra DERIU

**Comment by frmariani** [comment]
Gentilmente invii il contatto dell'ALS al seguente indirizzo 
frmariani@sogei.it
grazie

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
