### ISSUE TITLE
[5001] Legame Parentela da Convivente a Nuora: EN238

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#392]
ambiente di PRODUZIONE - comune di Medicina BO - idOperazione 2017000360

la variazione riguarda soggetto che, in seguito a matrimonio, cambia il proprio rapporto di parentela rispetto all'intestatario, da Convivente a Nuora.

la comunicazione non viene accetata a causa di questo messaggio:
EN238 - E - La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata

la dataDecorrenza della comunicazione corrisponde alla data del matrimonio.
i soggetti indicati nel messaggio (la Convivente / Nuora e l'Intestatario Scheda) hanno, in ANPR, dataDecorrenza della Residenza antecedente a quella che si sta comunicando

forse non capiamo la segnalazione.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Ora verifichiamo. Colgo l'occasione per un chiarimento: per variare la relazione di parentela occorre una dichiarazione anagrafica? oppure interviene il comune d'ufficio?

**Comment by COlivatoADS** [comment]
La variazione di rapporto di parentela viene effettuata d'ufficio a seguito di evento di stato civile (tendenzialmente per matrimonio/unione civile) o di anagrafe (emigrazione/variazione di indirizzo dell'intestatario scheda). In sempre più rare occasioni può essere effettuata su istanza di parte.
Grazie.
Christian Olivato ADS

**Comment by AMonopoliADS** [comment]
il cliente chiede aggiornamenti rispetto a questa problematica, è possibile avere un riscontro?
grazie

**Comment by azabatta** [comment]
La criticità è stata rimossa, è possibile riprovare. Restiamo in attesa di un cortese riscontro.
Grazie

**Comment by AMonopoliADS** [comment]
la mutazione è stata inviata con successo ed i dati sembrano aggiornati correttamente
grazie.
