### ISSUE TITLE
Annullamento cancellazione per irreperibilità da anagrafe ed elettorale

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3920]
Buongiorno,

Ambiente di TEST San Giorgio Piacentino
Abbiamo cancellato per irreperibilità il soggetto con id 78940352 dall'anagrafe e successivamente dall'elettorale. 
Il soggetto è stato cancellato dall'anagrafe con operazione 56021136 poi è stato cancellato dalle liste elettorali con operazioni successive.

1) Cercando di annullare la cancellazione per irreperibilità dall'anagrafe (anche da WebApp) riceviamo la risposta 
Operazione non effettuabile (Codice: 999)
Informazioni sull'operazione da fornire in caso di assistenza : data 2023-05-30 11:29:05 , idOperazioneANPR 56021467 (Codice: EN527)
E' possibile che le operazioni sulle liste elettorali impediscano l'annullamento della cancellazione anagrafica? 

2) Annullando la cancellazione per irreperibilità dall'elettorale (con un movimento di iscrizione id 56021386) l'operazione viene accettata ma consultando il soggetto dalla WebApp (Dati elettorali) nella scheda di cancellazione è ancora presente il motivo (IRREPERIBILITA').
E' corretto?

Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by frmariani** [comment]
La issue viene chiusa. Nel caso fosse necessario, si prega di riaprirne una nuova facendo riferimento a questa stessa.
