### ISSUE TITLE
Errore servizio RichiestaP002 con ANPR05

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#3923]
Buongiorno, abbiamo impostato la versione di anpr ad ANPR05 in base alle note tecniche relative all'id unico nazionale ma in questa configurazione nell'ambiente di produzione non funziona piu' il servizio RichiestaP002.
Si ottiene l'errore XXXX - CodDestinatario diverso da ANPR00 ANPR02 ANPR01
Tale servizio funziona invece correttamente in ambiente di test.
Quando verra' aggiornaot l'ambiente di produzione?
Grazie.

**Comment by apaolacci** [comment]
Salve,
come mai invocate i WS P000 con ANPR05? 
Cercate di ottenere informazioni differenti? Perché al momento in output non sono state previste e comunicate modifiche al wsdl attuale.
Confermate che in ambiente d'integrazione test-comuni invocando con ANPR05 le chiamate eseguono correttamente?
Grazie.

Saluti,
Assistenza ANPR

**Comment by galliandrea** [comment]
Buongiorno, come da NOTA TECNICA IDANPR ho impostato ANPR05 per poter ricevere l'identificativo unico nazionale. 
Mentre in ambiente di test funziona tutto regolarmente, compresi i servizi WS P000, in ambiente di produzione questi servizi non funzionano costringendo a lasciare impostati i servizi su ANPR02. Cosi' facendo pero' non si ottengono le informazioni relative all'identificativo unico.

**Comment by RBiasi** [comment]
Buongiorno, 

anche noi dopo la pubblicazione in produzione della versione ANPR05 riceviamo errore nell’invocazione dei servizi P000 (P001, P002, P003) con CodDestinatario ANPR05 

“CodDestinatario diverso da ANPR00 ANPR02 ANPR01”

Abbiamo urgenza di ricevere indicazione sui tempi di risoluzione dell'anomalia.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50

**Comment by apaolacci** [comment]
Buongiorno,
in output al wsdl non sono state previste e comunicate modifiche ai servizi P000 che interagiscono con le pratiche inviate dall'area autenticata Servizi Al Cittadino che permettano di recuperare un identificativo unico.

@galliandrea @RBiasi E' possibile in ogni caso fornirci i dettagli delle richieste con CodDestinatario ANPR05 che in ambiente di test comuni che funzionano correttamente? (idOperazioneComune, xml richiesta, ... )   

Grazie
Assistenza ANPR

**Comment by galliandrea** [comment]
Vi invio per esempio operazione P002 effettuata su ambiente di test comune di Siena alla quale il sistema risponde correttamente  
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
	<testataRichiesta>
		<idOperazioneComune>48294</idOperazioneComune>
		<codMittente>052032</codMittente>
		<codDestinatario>ANPR05</codDestinatario>
		<operazioneRichiesta>P002</operazioneRichiesta>
		<dataOraRichiesta>2023-06-06T15:09:03</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<dataProtocolloComune>2023-06-06</dataProtocolloComune>
		<tipoInvio>TEST</tipoInvio>
		<dataDecorrenza>2023-06-06</dataDecorrenza>
		<dataDefinizionePratica>2023-06-06</dataDefinizionePratica>
		<nomeApplicativo>INFOR</nomeApplicativo>
		<versioneApplicativo>INFOR</versioneApplicativo>
		<fornitoreApplicativo>INFOR</fornitoreApplicativo>
	</testataRichiesta>
	<criteriRicerca>
		<codiceRichiesta>1660414</codiceRichiesta>
	</criteriRicerca>
</ns2:RichiestaP002>

**Comment by galliandrea** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc"><testataRichiesta><idOperazioneComune>48294</idOperazioneComune><codMittente>052032</codMittente><codDestinatario>ANPR05</codDestinatario><operazioneRichiesta>P002</operazioneRichiesta><dataOraRichiesta>2023-06-06T15:09:03</dataOraRichiesta><tipoOperazione>C</tipoOperazione><dataProtocolloComune>2023-06-06</dataProtocolloComune><tipoInvio>TEST</tipoInvio><dataDecorrenza>2023-06-06</dataDecorrenza><dataDefinizionePratica>2023-06-06</dataDefinizionePratica><nomeApplicativo>INFOR</nomeApplicativo><versioneApplicativo>INFOR</versioneApplicativo><fornitoreApplicativo>INFOR</fornitoreApplicativo></testataRichiesta><criteriRicerca><codiceRichiesta>1660414</codiceRichiesta></criteriRicerca></ns2:RichiestaP002>

**Comment by galliandrea** [comment]
Con rispota idOperazioneANPR56071529

**Comment by RBiasi** [comment]
![ancona](https://github.com/italia/anpr/assets/29278221/cb6e79e2-a86d-4295-ac3b-a179a781ee5a)

**Comment by apaolacci** [comment]
Grazie, per i dettagli sulle richieste in test comuni 
Abbiamo riavviato in produzione la distribuzione dei wsP000, è possibile riprovare qualche invocazione in ambiente di produzione?

Grazie
Assistenza ANPR

**Comment by galliandrea** [comment]
Provato in ambiente produzione Livorno e sembra funzionare.
Grazie

**Comment by RBiasi** [comment]
Confermo risoluzione dell'anomalia.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50

**Comment by apaolacci** [comment]
OK!
se tutto ok è possibile chiudere la issue? grazie.

**Comment by galliandrea** [comment]
Penso proprio che che potete chiudere, mi sembra tutto ok.

________________________________
Da: apaolacci ***@***.***>
Inviato: mercoledì 7 giugno 2023 17:21
A: italia/anpr ***@***.***>
Cc: Andrea Galli ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/anpr] Errore servizio RichiestaP002 con ANPR05 (Issue #3923)

OK! se tutto ok è possibile chiudere la issue? grazie. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <italia/anpr/issues/3923/1581048433@ github. com>
ZjQcmQRYFpfptBannerStart
Security Warning: This email originated from outside of the organization. Do not click links or open attachments unless you verified the sender mail address and know the content is safe!

ZjQcmQRYFpfptBannerEnd

OK!
se tutto ok è possibile chiudere la issue? grazie.
