### ISSUE TITLE
Errore CAST Inserimento/Registrazione Nuovo Utente

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3930]
Buongiorno sono Nozzoli Arianna Comune di Prato. 
Ricevo questo errore in fase di abilitazione di un utente che non è mai stato registrato presso altri comuni:
Errore CAST Inserimento/Registrazione Nuovo Utente
Potete contattarmi allo 05741835223 oppure
a.nozzoli@comune.prato.it
Grazie

**Comment by dmazelli** [comment]
Buongiorno,
la invitiamo a contattarci all'800.86.31.16 fornendo ai ns consulenti le info in merito all'utenza da censire.
Saluti.

**Comment by anozzoli** [comment]
E' già risolto dai vostri colleghi
