### ISSUE TITLE
[5010] Cancellazione da lista aggiunta UE: errore EN204 Operazione non effettuabile. Comune non competente

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3932]
Buongiorno,

stiamo provando la cancellazione dalla lista aggiunta UE per un soggetto e l'errore che riceviamo è EN204 Operazione non effettuabile. Comune non competente

Ambiente di TEST 033040
id ANPR soggetto 78941468
id operazione ANPR 56038995

Non riusciamo a capire il problema, potete controllare?
Grazie

Monia Pedrazzoli 
APKAPPA s.r.l.

**Comment by frmariani** [comment]
Abbiamo riscontrato un'anomalia, appena sarà sanata ve ne daremo comunicazione.
Grazie per la segnalazione

**Comment by amollicone1982** [comment]
Potete riprovare

**Comment by MoniaPedrazzoli** [comment]
Stavolta ha funzionato, grazie.
