### ISSUE TITLE
iscrizione per motivi diversi - caso particolare

### ISSUE THREAD

**Issue by andemeglio** [italia/anpr#3933]
Buongiorno
dobbiamo procedere  all'iscrizione presso il Comune di Cagliari di un soggetto che però presenta una situazione particolare (schede doppie in ANPR) e chiedo come procedere.

Riporto di seguito la situazione:
- il soggetto in questione (persona1) era stato cancellato precedentemente da questo comune per Motivi diversi (id scheda soggettoANPR 39054537);
- dobbiamo procedere ala sua reiscrizione con dati anagrafici differenti (data di nascita diversa) il cui codice fiscale "calcolato" era lo stesso di altro/i soggetto/i con altri dati anagrafici.
- il problema si pone perché in ANPR risultano, oltre alla persona1 di cui sopra anche
  a) soggetto con id scheda soggetto ANPR 336555614- residente a COLLI AL METAURO con dati anagrafici diversi dal nostro residente e codice fiscale attribuito da risoluzione disallineamenti diverso dal nostro (ok);
  b) soggetto l'id scheda soggettoANPR 191492136 cancellato per motivi diversi (irreperibilità) dal CAMPOLI DEL MONTE TABURNO che ha gli dati anagrafici del residente a COLLI AL METAURO ma (non so per quale motivo) con codice fiscale che invece è quello attribuito a persona1 che dobbiamo iscrivere.

Come come dobbiamo procedere con la reiscrizione?
Potete eventualmente contattandomi al num 070 6778657 o tramite mail all'indirizzo andrea.demeglio@comune.cagliari.it. 

Comune di Cagliari
Andrea Demeglio

**Comment by frmariani** [comment]
Ho provato a contattarla al numero indicato senza successo.
Riproverò domani mattina.

**Comment by frmariani** [comment]
anche oggi non risponde.
Mi scriva  quando è disponibile
frmariani@sogei.it

**Comment by frmariani** [comment]
La issue viene chiusa in quanto siamo in contatto per le vie brevi.
