### ISSUE TITLE
Buongiorno, in fase di subentro sono stati popolati due cittadini in corso di accertamento per la residenza.

### ISSUE THREAD

**Issue by ANCHEIPICCOLISUBENTRANO** [italia/anpr#394]
Buongiorno, in fase di subentro sono stati popolati due cittadini in corso di accertamento per la residenza. Le persone vengono correttamente interrogate in webapp anpr, ma vorremmo concludere il procedimento anagrafico indicando la data di definizione della pratica che come si sa è essenziale ai fini statistici.
Grazie
COMUNE DI SPORMINORE - PRODUZIONE

**Comment by azabatta** [comment]
Buonasera, con i dati conferiti al momento del subentro, i dati dell’operazione anagrafica di riferimento non ci sono: abbiamo direttamente le informazioni della persona (e/o della famiglia) così come risultano al momento del subentro. Il dato del procedimento, di conseguenza, non c’è e quindi la comunicazione di questa data non avrebbe effetto fini statistici.
Nel  mese di subentro il comune deve chiudere il mese con il proprio sistema proprio perché mancano queste informazioni  che, per altro, per ANPR sono storiche e non attuali.
Se si ritiene indispensabile questo tipo di comunicazione, dobbiamo pensare ad una evoluzione dei servizi attuali.  
Inoltre, allo stato attuale, i dati statistici  continuano ad essere  inviati ad ISTAT  tramite i canali tradizionali.

**Comment by ANCHEIPICCOLISUBENTRANO** [comment]
La data di definizione è essenziale ai fini statistici (tranne che per i movimenti avvenuti prima o a cavallo del subentro)
Personalmente l'unico riferimento normativo che ho in mano per quanto riguarda la parte statistica è la circolare ISTAT Prot. 22585 del 1 dicembre 2016 che a pagina 2 cita:
"Come indicato nella circolare Istat n. 39 del 11 dicembre 2015, allorchè un Comune sarà transitato in ANPR non dovrà più inviare all’Istat i dati relativi alle suddette rilevazioni di fonte anagrafica.
È importante sottolineare che, per quanto concerne l’invio all’Istat dei macrodati e dei microdati delle statistiche demografiche, un Comune verrà considerato subentrato solo quando avrà esaurito l’invio all’Istat dei dati riferiti a tutti i mesi precedenti quello del subentro e all’intero mese in cui il subentro è avvenuto."
Quindi il nostro comune non invierà più le statistiche, a meno che non vi sia una norma più recente.
La data definizione è quindi essenziale ai fini statistici.
COMUNE DI SPORMINORE

**Comment by gcarbonin** [comment]
A regime i dati saranno forniti soltanto da ANPR; salvo diverse indicazioni da parte di ISTAT, la data di definizione della pratica diventa un dato ininfluente. 
Attualmente i comuni continuano a mandare i dati con le vecchie modalità in quanto "un Comune verrà considerato subentrato solo quando avrà esaurito l’invio all’Istat dei dati riferiti a tutti i mesi precedenti quello del subentro e all’intero mese in cui il subentro è avvenuto". L'estrazione deve essere fatta dalla vostra base dati locale dove questa data è presente.
Poi ripeto, se è essenziale avere questa informazione anche per pratiche nate prima del subentro, troveremo una soluzione.

**Comment by ANCHEIPICCOLISUBENTRANO** [comment]
"un Comune verrà considerato subentrato solo quando avrà esaurito l’invio all’Istat dei dati riferiti a tutti i mesi precedenti quello del subentro e all’intero mese in cui il subentro è avvenuto"
Noi abbiamo inviato tutti i mesi precedenti al subentro ed invieremo anche il mese di subentro, successivamente potremo considerarci ufficialmente subentrati anche per ISTAT.
"salvo diverse indicazioni da parte di ISTAT, la data di definizione della pratica diventa un dato ininfluente". A che data farà riferimento Istat? Quale è il riferimento normativo relativamente a quest'ultima affermazione?
Grazie

**Comment by gcarbonin** [comment]
ISTAT ha sottoscritto con il Ministero dell'Interno un accordo di servizio che prevede l'invio dei dati "ad evento" e non a chiusura della pratica (salvo poi diversi intendimenti da parte dell'Istituto che al momento sta testando i nuovi flussi).
A questo link http://anpr.readthedocs.io/en/latest/comuni/cosa-cambia-comune-migrato.html#cambiamenti-nei-rapporti-con-altri-comuni-e-pubbliche-amministrazioni

trovo questa indicazione
**"Passati 3 mesi dal subentro in ANPR del vostro comune, non è più necessario inviare alcun tipo di dati all’ISTAT. Verificata la congruità dei dati, ISTAT processerà infatti i dati direttamente da ANPR.
Il Comune deve però completare l’invio all’ISTAT di tutti i dati riferiti ai mesi precedenti al subentro, e all’intero mese in cui il subentro è avvenuto. Il comune non verrà considerato subentrato fino al completamento di questi invii.**"
Penso sia necessario un chiarimento dell'Istituto per tutti i comuni subentrati

**Comment by gcarbonin** [comment]
#307
