### ISSUE TITLE
Liste elettorali - Riepiloghi

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3942]
Buongiorno
nella issue #3761 leggo che i riepiloghi elettorali verranno aggiornati una volta al mese. 
C'è un momento che può essere preso di riferimento? (inizio mese, fine mese, ...)
Questi riepiloghi sono già decurtati dei cittadini cancellati dall'ANPR, che non sono ancora stati cancellati dalla liste elettorali con una revisione?
Grazie
Roberta A.

**Comment by frmariani** [comment]
Ad oggi i Riepiloghi elettorali sono aggiornati giornalmente e riguardano i cittadini iscritti nelle sezioni elettorali del comune suddivisi per genere. 
Le cancellazioni anagrafiche non sono pertinenti.

**Comment by frmariani** [comment]
i Riepiloghi si riferiscono ai dati elettorali inviati per il comune, pertanto se il cittadino è stato cancellato anagraficamente, non avrà nessun impatto sui riepiloghi fintanto che non verrà inviata la cancellazione dalla liste del comune.
