### ISSUE TITLE
Annullamento mutazione residenza non richiesto in ANPR

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#3944]
Nozzoli Arianna Sistema informativo comune di Prato
a.nozzoli@comune.prato.it
tel. 05741835223

Buongiorno,
ci siamo accorti di alcuni casi veramente preoccupanti.
Questo è un esempio:
in data 24/01/2023 con l'operazione 1167953129
è stato fatto un cambio di residenza all'interno del comune di Prato per i cittadini 
41370729
e
86108269
In data 23/02/2023 è stato richiesto l'annullamento del cambio di residenza per la sola 41370729 mandando a ANPR il seguente XML:

<testataRichiesta>
<idOperazioneComune>JD23022309011353580</idOperazioneComune>
<codMittente>100005</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>5012</operazioneRichiesta>
<dataOraRichiesta>2023-02-23T09:01:28.000+01:00</dataOraRichiesta>
<tipoOperazione>V</tipoOperazione>
<tipoInvio>PROD</tipoInvio>
<dataDecorrenza>2023-02-23</dataDecorrenza>
<nomeApplicativo>JDEMOS</nomeApplicativo>
<versioneApplicativo>1.1.22.0</versioneApplicativo>
<fornitoreApplicativo>MAGGIOLI S.P.A.</fornitoreApplicativo>
</testataRichiesta>
<datiOperazioneDaAnnullare>
<operazioneRichiesta>5005</operazioneRichiesta>
<idOperazioneComune>JD23012408251323252</idOperazioneComune>
<idOperazioneANPR>1167953129</idOperazioneANPR>
</datiOperazioneDaAnnullare>
<datiSchedaSoggettoFamigliaConvivenza>
<soggetto>
<codiceFiscale>
[…]
idANPR 41370729
[…]

Registrato con l'operazione 1202952802

Questa operazione ha annullato TUTTA l'operazione 1167953129 anche per idanpr 86108269 non presente nel xlm sopra riportato.
Non è il solo caso trovato. Vorrei sapere se è la Maggioli a sbagliare il formato del xml o c'è qualcosa che non va in ANPR.
Grazie

**Comment by frmariani** [comment]
L'**annullamento parziale** dell'operazione di cambio di residenza si deve indicare nei dati di controllo dell'operazione di annullamento. Nel vostro caso non è stato indicato, pertanto è stata annullata l'intera operazione.
