### ISSUE TITLE
Aggiornamento delle specifiche di interfaccia per data di decorrenza

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#395]
Le specifiche di interfaccia (https://www.anpr.interno.it/portale/documents/20182/26001/MI-14-AN-01+SPECIFICHE+DI+INTERFACCIA+WS_03_11_2017.pdf/db4fea93-5dd3-4291-9c26-88f8bc9c8bb3) di ANPR **sono state modificate precisando che la decorrenza di una iscrizione  per nascita è un dato dichiarato dal comune, sotto la sua piena responsabilità e nel rispetto delle norme vigenti.**
Per tale motivo, ANPR prevede un campo apposito (sia nei WS che nella WA),  distinto dalla data di nascita e dalla data dell’operazione.
Qualora l’iscrizione decorra dalla nascita, è sufficiente specificare lo stesso valore nei campi data di decorrenza e data di nascita, valori distinti in caso contrario.
Sul certificato storico di residenza, ANPR riporta il valore del campo data di decorrenza nella informazione “iscritto dal….”: tale valore, pertanto, coinciderà con la data di nascita nel primo caso, sarà successivo alla nascita nel secondo.

**Comment by Raffive** [comment]
Grazie Mirko!
Ottimo lavoro!
Raffaella

**Comment by Eduardo1977** [comment]
Ciao Mirko, questa nuova issue risponde indirettamente anche alla #385 ?

**Comment by mccalv** [comment]
@Eduardo1977 direi di si, il problema é simile. Come regola generale vi prego di non commentare sulle issue di tipo Avviso
