### ISSUE TITLE
ANPR - malfunzionamento ANPR

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#3956]
Stiamo verificando delle anomalie del sistema ANPR questa mattina.
Inoltre l'area dei servizi anagrafici per il cittadino è temporanemanete in manutenzione.

Vi informeremo appena possibile sulla soluzione.

**Comment by Maga63** [comment]
Servizi ANPR , Web App e Cie ora funzionano.


Comune di Milano

**Comment by Barisctt** [comment]
> 
Salve,
Mi confermate che ANPR , Web App e Cie ora funzionano?

**Comment by dierossi** [comment]
I servizi ANPR sembrano funzionare...... ciedo conferma per le CIE

**Comment by fortbor** [comment]
si ora vanno

**Comment by Barisctt** [comment]
> Stiamo verificando delle anomalie del sistema ANPR questa mattina. Inoltre l'area dei servizi anagrafici per il cittadino è temporanemanete in manutenzione.
> 
> Vi informeremo appena possibile sulla soluzione.

Attendiamo una cortese risposta sulla risoluzione complessiva delle problematiche.
Grazie

Bari

**Comment by sfmodena** [comment]
Comune di Modena

Ripartiti WS , webapp e CIE.

**Comment by mttfranci** [comment]
Salve la situazione dovrebbe essere rientrata.
Saluti

Assistenza ANPR

**Comment by siscomanpr** [comment]
Da ieri pomeriggio e anche questa mattina, alcuni comuni ci segnalano ancora problemi sui servizi ANPR che vanno in errore di timeout e/o di impossibilità a raggiungere il server remoto.

**Comment by coinnect-project** [comment]
sito sc.anpr.interno.it ancora tutto fermo 🤦‍♂️
