### ISSUE TITLE
[5010] Liste elettorali - tipo revisione

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3957]
Buongiorno,
sollecito una risposta all'issue #3839 

Provando dalla Web App abbiamo notato la possibilità di indicare come tipo revisione "Altra revisione".
![image](https://github.com/italia/anpr/assets/33952624/6d5465ca-3d97-4d36-bb73-dbd034f1071f)
Avrei la necessità di poter usare "Altra revisione" anche tramite Web Services, ma attualmente a disposizione ci sono solo i seguenti tipi: PRIMOCARICAMENTO|SEMESTRALE|DINAMICA|STRAORDINARIA.

Resto in attesa di un cortese riscontro.

**Comment by frmariani** [comment]
Forse avete una versione non aggiornata del vocabolario; nell'area tecnica del Portale ANPR sono presenti tutti i documenti aggiornati:
https://www.anagrafenazionale.interno.it/area-tecnica/documentazione-tecnica/

**Comment by SAlberto** [comment]
Grazie
