### ISSUE TITLE
[5008 - 5010] flag elettore

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3958]
Buongiorno,
dopo l'introduzione della chiamata 5010, la chiamata 5008 dovrà ancora essere utilizzata per modificare il flag elettore?
Oppure sarà sufficiente la sola 5010?

grazie

**Comment by frmariani** [comment]
Dopo il subentro elettorale del comune,  il servizio WS 5008 tipo mutazione 5 potrà essere utilizzato soltanto per la mutazione delle liste di leva.

**Comment by SAlberto** [comment]
Grazie
