### ISSUE TITLE
visualizzazione persone cancellate

### ISSUE THREAD

**Issue by ANCHEIPICCOLISUBENTRANO** [italia/anpr#396]
Buongiorno,
abbiamo dovuto cancellare una persona per irreperibilità accertata.
L'iter sembra andato a buon fine, ma quando consultiamo il cittadino in web app, pur vedendo i dati di cancellazione, dalla scheda residenza non emerge alcuna indicazione relativamente al fatto che il soggetto sia un cancellato. Per di più il campo "data di riferimento scheda" porta la data odierna (data di consultazione), mentre il soggetto è stato cancellato in data 03/11/2017. Per approfondire la verifica, abbiamo provato a stampare una visura di residenza, ma invece di impedirlo in quanto cittadino non più in anpr, ci viene segnalato che il cittadino ha un procedimento in corso. Non abbiamo trovato alcun modo per definire questo procedimento, il quale non ha un tempo che intercorre tra la data di registrazione (avvenuta cancellazione da anpr) e la data di definizione (accertamento avvenuto), in quanto, come si sa, l'accertamento viene eseguito per un anno antecedente la registrazione (avvenuta cancellazione da anpr).
Certi di un celere riscontro, saluti.
Comune di Sporminore

**Comment by gcarbonin** [comment]
E' possibile avere un riferimento alla persona (id anpr) o all'operazione di cancellazione? senza queste informazioni non possiamo essere di nessun aiuto.
