### ISSUE TITLE
Richiesta credenziali ambiente di test per Comune già attivo in produzione

### ISSUE THREAD

**Issue by Gianluke** [italia/anpr#3962]
Buongiorno,
avremmo bisogno di ottenere le credenziali per l'accesso all'ambiente di test ANPR (https://dptest.anpr.interno.it/combas) per un Comune che ha già effettuato le attività di subentro ed attivazione sull'ambiente di produzione.
Non avendo modo di conoscere lo storico delle attività effettuate dal vecchio fornitore e non riuscendo a rintracciare negli indirizzi email/PEC dei responsabili comunali alcun riferimento in merito, esiste una qualche procedura per richiedere il  re-invio delle suddette credenziali?

Grazie e buon lavoro.

**Comment by Leonforte** [comment]
Buongiorno, per quale comune intendete procedere ?

**Comment by Gianluke** [comment]
Buongiorno, Comune di Surbo.

Grazie.

**Comment by Leonforte** [comment]
Buongiorno, il nuovo certificato è stato iniviato all'indirizzo dell'utente ALS picfab82@libero.it.
Lo stesso ALS  potrà accedere all'ambiente di test utilizzando le credenziali (utente/password) dell'ambiente di produzione. 
Buon lavoro, saluti

**Comment by Gianluke** [comment]
Buongiorno,
grazie, abbiamo ricevuto il certificato ma non abbiamo a disposizione la password per accedere alla console di test (o produzione) in quanto l'operatore ALS non ha avuto mai necessità di entrare su questi ambienti (accede solo alla console di amministrazione direttamente tramite certificato su smartcard e pin corrispondente): esiste una procedura per effettuare il reset di questa password o potreste reinviare le credenziali al suo indirizzo email?

Grazie ancora.

**Comment by Leonforte** [comment]
Buongiorno, quanto richiesto è stato inviato all'indirizzo personale dell'utente ALS, buon lavoro, saluti
