### ISSUE TITLE
Ricerca per Data Evento

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#397]
Apriamo questa issue per il tracciamento di una nuova feature che consenta di eseguire la ricerca di eventi su ANPR, via web service o web application, attraverso la data evento (data nascita/nata matrimonio).

**Comment by MarcoMigliori** [comment]
Stiamo parlando immagino della consultazione cittadino, a una determinata data. Il termine usato in ANPR è "consultazione scheda individuale" e implementa una ricostruzione alla data di registrazione.  Questa nuova feature si aggiungerebbe.

Dubbio: per quanto scritto nella #395 , direi che la ricerca va fatta sul campo Data Decorrenza, e non sulla data evento. 
Esempio: iscrizione per nascita in ANPR. data nascita 1-11-17 data decorrenza indicata 3-11-17 (non entro qui nel merito del perchè sia diversa). in questo evento registrato, la decorrenza dell'iscrizione per nascita è diversa dalla data di evento. Se questo è il dato che si certifica, quindi un certificato storico di residenza non si può richiedere prima del giorno 3-11-17 , uguale effetto devo ottenere con la ricerca. 
In altre parole il bambino è residente dal 3-11-17.

**Comment by gcarbonin** [comment]
Chiusa in quanto collegata alla issue #784 dove si parla di interrogazione storica.
