### ISSUE TITLE
Cancellazione elettorale

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#3972]
[Ambiente di TEST]

Buongiorno,
informazioni anomalia: data 2023-07-03 08:39:04 , Token 1688366344635 (Codice: EN527)
stavo effettuando una cancellazione elettorale **dal portale** e mi esce questo messaggio, cosa sto sbagliando?

Grazie

**Comment by SAlberto** [comment]
![image](https://github.com/italia/anpr/assets/33952624/ae9971b5-44d8-49cd-9c9f-7ea1d8350584)

si webapp anpr, sto facendo una semplice cancellazione

**Comment by amollicone1982** [comment]
Puo' riprovare adesso

**Comment by SAlberto** [comment]
Ho riprovato, la cancellazione ora funziona, ed andando in consultazione compare la sezione "dati cancellazione".
Però il flag elettore è rimasto a S, è corretto?

**Comment by frmariani** [comment]
non ci sono automatismi che modificano l'attributo dell'elettore e comunque la cancellazione dalla lista non significa che il cittadino perda la capacità elettorale; nel suo caso il cittadino è stato cancellato per morte pertanto sarà possibile emettere dei certificati, ma nel caso di cancellazione per emigrazione, il cittadino può richiedere un certificato di godimento dei diritti politici ed il flag elettore=N non permetterebbe l'emissione del certificato.

**Comment by SAlberto** [comment]
Per le chiamate web service:
Se facessi una Cancellazione per morte, come dovrei fare a variare il flag elettore a N?

Con tipo mutazione 5 posso trasmettere anche il flagElettore, anche se è all'interno del blocco Liste e non in quello Certificazione?

**Comment by frmariani** [comment]
deve inviare anche il tipo mutazione riferito alla tipologia di lista (1 o 2 o3) con l'informazione dell'attributo elettore

**Comment by SAlberto** [comment]
è normale che per indicare il flag elettore a N debba anche dettagliare uno dei blocchi tra listaGenerale, listaAggiuntaUE, e listaAggiuntaComReg e i vari vari flag delle consultazioni?
