### ISSUE TITLE
cittadino con procedimento di iscrizione per immigrazione a seguito RICOMPARSA

### ISSUE THREAD

**Issue by ANCHEIPICCOLISUBENTRANO** [italia/anpr#398]
Buongiorno,
mi sembra di ricordare, che la modifica dei dati di iscrizione, possa avvenire solo tramite web app - operazione di rettifica - e non tramite web service.
Questi casi possono capitare frequentemente con cittadini stranieri che vengono iscritti per immigrazione da altro comune e poi si scopre in comunicazione con il comune di precedente residenza, che gli stessi sono stati cancellati per irreperibilità.
Come è possibile non avere un disallineamento tra i dati anpr e la banca dati di servizio?
Grazie

**Comment by Raffive** [comment]
Ne abbiamo anche noi uno.  id anpr 18853746
in data base locale sono riuscita a cambiare la provenienza.
in anpr si cambia in wa.
doppia operazione.
doppio lavoro.
Raffaella

Raffaella

**Comment by Raffive** [comment]
Altra novità.
Data decorrenza della residenza non bloccante nel subentro.
da qualche giorno in caso di mutazione nello stesso comune bisogna:
1) aprire la scheda della persona , verificare che non ci sia l'avviso" La data di decorrenza residenza non risulta valorizzata" 
2) se non c'è entrare in wa 
3) richiamare la persona  
4) rettificare il dato (ovvero inserirlo)
5) cominciare a lavorare
Capita solo a me?
Si può fare qualcosa? ne ho migliaia..
Grazie
Raffaella

**Comment by gcarbonin** [comment]
Tutte le operazioni effettuate tramite WA possono essere recepite anche nella base dati locale senza alcun intervento da parte del personale del comune. 
Soltanto un chiarimento : il punto 1 si riferisce al SW anagrafico del comune? Se si, e nella base dati locale il dato non c'è, il comune lo ricava dalle schede cartacee?

**Comment by Raffive** [comment]
L'avviso compare nella scheda anpr in sw.
Ricaviamo la data che poi è quella di iscrizione anagrafica da quella apr. Il cartaceo, per fortuna,l'abbiamo abbandonato nel 1990. Se serve le invio una mail con uno screen.
Raffaella

**Comment by gcarbonin** [comment]
Quindi la data in apr è presente? Se così perchè non è stata inviata al subentro? Se è solo un problema di mancato invio di un dato possiamo pensare ad un recupero automatico, d'intesa con il vostro fornitore

**Comment by Raffive** [comment]
Certo che é presente.
Se potete fare questo "miracolo" informatico sarebbe davvero il top!
Raffaella

**Comment by gcarbonin** [comment]
Cerchiamo di parlare con il suo fornitore

**Comment by Raffive** [comment]
Grazie domani ci parlo anche io

**Comment by ANCHEIPICCOLISUBENTRANO** [comment]
non tutte le operazioni fatte su web app possono esser recepite tramite WS. Una risposta di Sogei data alla Sw house di riferimento, di data 22/09/2017 indica che la funzione di rettifica dei dati di iscrizione può esser utilizzata solo tramite Webapp.
Questo significa dover operare sia in webapp che in banca dati di servizio.
