### ISSUE TITLE
Certificabilità elettorale rimasta completa

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#3982]
Soggetto ID ANPR 35271377
	È stato trasmesso servizio 5010 con soggetto certificabile = 1
	
	<liste>
	<elettore>S</elettore>
	<listaGenerale>
	<comune>
	<nomeComune>TOLENTINO</nomeComune>
	<codiceIstat>043053</codiceIstat>
	<siglaProvinciaIstat>MC</siglaProvinciaIstat>
	</comune>
	<sezioneelettoralenum>14</sezioneelettoralenum>
	</listaGenerale>
	<referendumnazionali>S</referendumnazionali>
	<elezionimembriue>S</elezionimembriue>
	<senatorepubblica>S</senatorepubblica>
	<circoscrsenatorepubblica>MARCHE</circoscrsenatorepubblica>
	<cameradeputati>S</cameradeputati>
	<circoscrcameradeputati>MARCHE</circoscrcameradeputati>
	<regionali>S</regionali>
	<comunali>S</comunali>
	<circoscrizionali>S</circoscrizionali>
	</liste>
	<certificabilita>
	<soggettoCertificabile>1</soggettoCertificabile>
	</certificabilita>
	<cancellazione>
	<motivoCancellazione>1</motivoCancellazione>
	<noteCancellazione>EMIGRAZIONE</noteCancellazione>
	</cancellazione>
	<tipoRevisione>DINAMICA</tipoRevisione>
	<datiControllo>
	<tipoMutazione>01</tipoMutazione>
	</datiControllo>

	Abbiamo ricevuto risposta

	<soapenv:Envelope>
	<soapenv:Body>
	<ns2:Risposta5010>
	<ns3:Risposta_Comune>
	<testataRisposta>
	<idOperazioneComune>20230706154014169</idOperazioneComune>
	<codMittente>043053</codMittente>
	<codDestinatario>ANPR03</codDestinatario>
	<operazioneRichiesta>5010</operazioneRichiesta>
	<dataOraRichiesta>2023-07-06T15:40:14</dataOraRichiesta>
	<protocolloComune>0</protocolloComune>
	<dataProtocolloComune>2023-07-06</dataProtocolloComune>
	<dataDecorrenza>2023-07-06</dataDecorrenza>
	<idOperazioneANPR>1353732676</idOperazioneANPR>
	<esitoOperazione>0000</esitoOperazione>
	</testataRisposta>
	<listaAnomalie/>
	</ns3:Risposta_Comune>
	</ns2:Risposta5010>
	</soapenv:Body>
	</soapenv:Envelope>

	ma in WebApp la certificabilità risulta ancora completa anziché parziale come ci saremmo aspettati che fosse.

	Grazie anticipatamente.
	Cordiali saluti.

**Comment by frmariani** [comment]
Per modificare la certificabilità deve utilizzare il tipo di mutazione appropriato: tipo mutazione 04 e non 01

**Comment by Hdemografici** [comment]
Il cittadino, elettorale nel comune che ha inviato la 5010, è stato cancellato in seguito ad una emigrazione.
Anche in caso di cancellazione il tipo mutazione deve essere 4? 
In caso affermativo allora chiedo, il tipo mutazione 1 quando va usato?
Grazie

**Comment by frmariani** [comment]
mi scusi ma non è chiaro cosa chiede; lei vuole agire sulla certificabilità perchè il cittadino è emigrato in altro comune?
se il cittadino è stato cancellato, deve utilizzare il tipo mutazione 05: soltanto se "cancellando" il cittadino potrà essere iscritto nelle lista di un altro comune.
Se cancellando, non potranno essere emessi i certificati di iscrizione nelle liste elettorali.
Il tipo di mutazione 1 riguarda l'aggiornamento della lista generale.

**Comment by Hdemografici** [comment]
Grazie è tutto chiaro.
