### ISSUE TITLE
[5010] Cancellazione da lista aggiunta BZ: errore EN204 Operazione non effettuabile. Comune non competente

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#3990]
Buongiorno,

abbiamo riscontrato in ambiente di produzione per il comune di Gamberale un problema simile a quello segnalato con issue #3932 e che in ambiente di test risultava risolto.

La situazione è simile, in questo caso si tratta della cancellazione di un elettore dalla lista aggiunta per la provincia di Bolzano e l'errore che si presenta è questo:

EN204 Operazione non effettuabile. Comune non competente 
Informazioni sull'operazione da fornire in caso di assistenza : data 2023-07-04 16:50:02 , idOperazioneANPR 1350727073

Abbiamo suggerito al comune di rivolgersi all'assistenza ANPR ma al momento non sono intenzionati a farlo.
Potete verificare?
Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by amollicone1982** [comment]
Per la cancellazione della lista aggiunta per la provincia di Bolzano deve usare il motivo cancellazione 7 e non 4.
Puo' scaricare la tabella con i motivi cancellazione dal portale

**Comment by MoniaPedrazzoli** [comment]
Quindi per la cancellazione dalle liste aggiunte UE si possono utilizzare anche i motivi di cancellazione da 1 a 4, mentre per la cancellazione dalle liste aggiunte per comunali/regionali l'unico motivo ammesso è il 7?

**Comment by amollicone1982** [comment]
Per le liste aggiunte UE ci sono i motivi 5 e 6.


Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MoniaPedrazzoli** [comment]
In ambiente di test siamo riusciti a cancellare un elettore dalle liste aggiunte per irreperibilità con il motivo 2, per questo mi chiedevo il motivo di questa differenza. Rif. issue https://github.com/italia/anpr/issues/3932

Ambiente di TEST 033040
id ANPR soggetto 78941468
id operazione ANPR 56038995

**Comment by amollicone1982** [comment]
Mi sembra strano ma se mi dà l'idoperazione di test verifico

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MoniaPedrazzoli** [comment]
Per quanto riguarda l'operazione nell'ambiente di test i riferimenti sono quelli del msg precedente:

Ambiente di TEST 033040
id ANPR soggetto 78941468
id operazione ANPR 56038995

La aggiorno anche in merito all'operazione in ambiente di produzione perché riprovando con motivo cancellazione 7 abbiamo ricevuto lo stesso errore. I riferimenti sono:

Ambiente di PROD 069039
id ANPR soggetto 18850958
id operazione ANPR 1362526331

Potete verificare? Grazie

**Comment by amollicone1982** [comment]
In produzione avete preso errore con l'operazione 1362526331 (13/07/2023 13:23:01  con idoperazionecomune 5432) in quanto in precedenza è stata fatta l'operazione 1362526286 (13/07/2023 13:22:58 con idoperazionecomune 5431) identica alla precedente che ha cancellato la lista aggiunta bolzano.

In test comuni con l'operazione 56038995 avete preso giustamente EN204 con motivo cancellazione 2 (per questo soggetto avete la lista aggiunta ue per le comunali e per le parlamentarie che per essere cancellate hanno bisogno del motivo 5 e 6)

**Comment by amollicone1982** [comment]
L'operazione 56123459 (con motivo 2) ha avuto successo in quanto ha messo il soggetto in stato di cancellando per irreperibilità (Cio' significa che un altro comune potrà iscriverlo nelle proprie liste). Infatti se consultate adesso il soggetto 78941468 vedrete che ha ancora le liste aggiunte ue ed è in stato cancellando.

Il motivo 5 e 6 serve invece ad eliminare le liste aggiunte ue. Cio' significa che se eseguite tale operazioni non vedrete piu' in consultazione le liste aggiunte ue (Una motivazione per usare il 5,6 è per motivi legati ad un errore di inserimento).

**Comment by amollicone1982** [comment]
I primi 4 motivi di cancellazione servono per il discorso di cancellando/iscrivendo mentre dal 5 al 8 servono ad una cancellazione dovuta ad un errore o, come nel caso della lista aggiunta bolzano, ad un procedimento (che nulla ha a che fare con il discorso di cancellando/iscrivendo)

**Comment by MoniaPedrazzoli** [comment]
L'utilizzo dei motivi dal 5 all'8 mi è chiaro, infatti li indichiamo quando è necessario annullare l'inserimento di un elettore in una determinata lista. Non capisco invece perché non è possibile cancellare anche dalle liste aggiunte BZ/TN/AO per motivi diversi dal 7, comunque mi riservo di parlarne con i miei colleghi e con i clienti.
Grazie per le verifiche, buona giornata.
