### ISSUE TITLE
Caso Cancellazione per morte

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#4]
Caso cancellazione per Morte. Nelle specifiche tecniche paragrafo 11.2.1  si dice:” **Si precisa che se il deceduto risulta coniugato con un soggetto ANPR, per tale soggetto verranno impostati i dati della vedovanza. La mutazione dello stato civile invece dovrà essere modificata con esplicita richiesta ( 5008)**.” 
In molti casi il coniuge potrebbe essere un Soggetto ANPR di un altro comune e chi sta effettuando la variazione di morte non avere i rifermenti per individuare questa scheda (Codice Fiscale, Matricola ANPR). In fase di subentro infatti è possibile trasmettere solo il cognome e nome del coniuge."

**Comment by gcarbonin** [comment]
La mutazione di stato civile viene effettuata dal comune di residenza del coniuge superstite che nell'esempio è diverso da quello di residenza del defunto.
