### ISSUE TITLE
Web-App Registrazione - Mutazione Famiglia/Convivenza campo Specie non corretto

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#40]
Data test 20/03/2017 - Ambiente test (dptest)
Nel Pannello Residenza è riportato in lettura l'indirizzo attuale del soggetto/famiglia. 
Il campo Specie è erroneamente valorizzato: in caso di VIA riporta CAVALCAVIA, in caso di STRADA riporta AUTOSTRADA. 
Deve essere riportato il valore della specie come popolato da subentro e presente nella scheda soggetto.
Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Per una verifica serve l'operazione che state effettuando nonché un identificativo della persona (id anpr o id comune) altrimenti non possiamo rispondere. Grazie

**Comment by annamariaGillone** [comment]
Gillone:Abbiamo ricreato il caso di test:
ID_SOGGETTO ANPR  987749
Mutazione famiglia/convivenza ID 387302 in data 22/03/2017 - Istanza di parte

**Comment by gcarbonin** [comment]
Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
E' possibile riprovare. Mi faccia sapere se va bene

**Comment by annamariaGillone** [comment]
ok va bene. grazie
