### ISSUE TITLE
Re-Iscrizione di soggetto in precedenza migrato verso non subentrato

### ISSUE THREAD

**Issue by busaster** [italia/anpr#400]
Ambiente di test, comune di Gorgonzola.

Abbiamo cancellato da ANPR per emigrazione verso non subentrato il 25/10 con operazione ID ANPR 606272 un soggetto che è coniugato con altro residente che risedeva in famiglia con lui. Il coniuge continua ad essere residente.
Oggi 7/11/2017 la persona vogliamo iscrivere in una nuova famiglia con provenienza da non subentrato lo stesso soggetto emigrato il 25/10.
La chiamata ID ANPR 618161 al servizio 1002 però va in errore "EN272 : Alla data 02-10-1971 il soggetto XXXXXX risulta gia' coniugato o unito civilmente con un altro soggetto.", dove XXXXXX è il nome del coniuge che non si è mai mosso da Gorgonzola.

Quando in passato abbiamo riscontrato questo errore era perché le generalità dell'iscrivendo e quelle di "coniuge" del soggetto già in ANPR non coincidevano. Ma in questo caso coincidono gli id anpr....
Come mai riceviamo questo errore ?

**Comment by asqueglia** [comment]
Verifichiamo e le faremo sapere appena possibile.

**Comment by asqueglia** [comment]
Il problema è stato risolto. E' possibile riprovare. Grazie per la segnalazione.

**Comment by busaster** [comment]
Abbiamo verificato che l'operazione in ambiente di test ora viene completata con successo.
Avendo riscontrato nei giorni scorsi il medesimo problema in ambiente di produzione (Poggio a Caiano) chiedo quando sarà aggiornato quest'ultimo. 
Grazie

**Comment by asqueglia** [comment]
Se potete fornirci indicazioni sul caso relativo all'ambiente di produzione, verifichiamo la problematica; è utile indicarci l'id dell'operazione effettuata.
Grazie

**Comment by busaster** [comment]
stiamo recuperando le informazioni presso il cliente.
Appena avremo i dati ve li comunicheremo

**Comment by busaster** [comment]
Abbiamo recuperato ID operazione della chiamata 1002 che fallisce a Poggio a Caiano in produzione : è la ID 1377739

**Comment by asqueglia** [comment]
Buongiorno,
dalla operazione indicata, abbiamo verificato che non si tratta di una reiscrizione ma di una prima iscrizione del soggetto.
Il coniuge, indicato nella richiesta, presenta un matrimonio inserito con una mutazione 5008 con un soggetto con codice fiscale numerico di 11 cifre, che sembra essere temporaneo, mentre nella richiesta di iscrizione è stato indicato il codice fiscale definitivo di 16 caratteri.
Nel confronto tra i CF, fallisce la riconciliazione.
