### ISSUE TITLE
PROBLEMA SUBENTRO DATI ELETTORALI PER COMUNE DI BARDELLO CON MALGESSO E BREGANO

### ISSUE THREAD

**Issue by StefanoDotti** [italia/anpr#4004]
Buongiorno,
dall'01/01/2023 esiste il Comune di Bardello con Malgesso e Bregano, nato dalla fusione dei 3 comuni. 

Il predetto non è presente nella tabella dei nuovi collegi elettorali e questo ci crea problemi durante i controlli automatici per il subentro dei dati elettorali in ANPR. 

Si richiede l'adeguamento della tabella indicata in modo che possano portare a termine le operazioni di controllo e successivo subentro in ANPR.

Grazie
Stefano Dotti
Halley Lombardia

**Comment by amollicone1982** [comment]
[Tabelle-campi-standard.zip](https://github.com/italia/anpr/files/12180451/Tabelle-campi-standard.zip)

**Comment by amollicone1982** [comment]
Salve,
allego le tabelle aggiornate qui sulla issue che a breve verranno aggiornate sul portale anpr
