### ISSUE TITLE
[5010] PROD - Iscrizione lista aggiunta AO: errore EN204 Operazione non effettuabile. Comune non competente

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#4005]
Buongiorno, 
ambiente di PRODUZIONE 006127

In RD I tornata liste ordinarie è stato cancellato il soggetto 61620811 per emigrazione in altro comune (della regione Valle d'Aosta).
In RD II tornata liste aggiunte lo stesso soggetto viene iscritto nelle liste aggiunte AO ma l'operazione non viene accettata (id operazione ANPR 1376616192).

Non riusciamo a capire il motivo della segnalazione, potete aiutarci?
Grazie
Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by amollicone1982** [comment]
Salve,
stiamo discutendo con il ministero se permettere un inserimento della lista aggiunta regionale prima dell'inserimento della lista generale in quanto la problematica del 204, in questo caso, è questa

**Comment by MoniaPedrazzoli** [comment]
Abbiamo contattato il cliente e appena possibile vi daremo riscontro. Grazie

**Comment by MoniaPedrazzoli** [comment]
Confermo che riprovando la variazione non ha dato problemi e la persona risulta in elettorale con "lista aggiunta Valle d'Aosta del comune di ...".
