### ISSUE TITLE
[5010] Errore EN560 iscrizione non consentita in quanto il soggetto non è un  cancellando

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4009]
Buongiorno
Comune di Cavallirio, un cittadino proveniente da altro comune iscritto in II tornata.
Inviando comunicazione 5010 per iscrizione alle liste elettorali esce il messaggio di errore in oggetto.
EN560 iscrizione non consentita in quanto il soggetto non è un  cancellando

Cosa è necessario fare in questi casi?
Grazie
Halley Informatica

**Comment by RBiasi** [comment]
Buongiorno,

mi collego per analoga anomalia del comune di Roverè della Luna.

Il Comune di Roverè della Luna ha effettuato il subentro dei dati elettorali in ANPR il giorno 24 luglio scorso riscontrando anomalia sulla posizione della cittadina Id Soggetto 61550825 che non risulta essere stata cancellata elettoralmente dal comune di Matino che ha però correttamente inviato il file 3D XML al comune di Roverè della Luna in occasione della scorsa Dinamica I tornata.

Rimango in attesa di sapere come gestire queste casistiche.

Grazie.

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities

**Comment by Hdemografici** [comment]
Abbiamo risolto grazie.
Roberta Amici

**Comment by RBiasi** [comment]
Buongiorno,

siamo riusciti ad iscrivere la cittadina 61550825 in quanto posta in stato cancellata dal Comune di Matino.

Tuttavia la certificabilità della cittadina è stata impostata da Matino a valore Certificabilità parziale è corretto?

Che senso ha mettere la certificabilità parziale se comunque non è possibile emettere il certificato di iscrizione in quanto l'elettrice è cancellata?

Inoltre iscrivendo la cittadina la certificabilità rimane su parziale perchè?

Grazie 

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50
