### ISSUE TITLE
Elettorale - Cancellazione da lista aggiunta di cittadino diventato italiano

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#4019]
Buongiorno, in fase di revisione dinamica prima tornata abbiamo cancellato un elettore dalla lista aggiunta dei comunitari parlamento europeo in quanto diventato di cittadinanza italiana.
Al momento di inviare la comunicazione di cancellazione (verra' poi iscritto nella lista elettorale alla succesiva revisione dinamica per acquisto cittadinanza) ottengo l'errore 
EN565 DescrErr: Lista aggiunta ue non puo' essere inserita in quanto il soggetto ha una cittadinanza italiana 

Se non invio i dati della lista aggiunta UE ottengo l'errore che per tipo mutazione 02 i dati lista aggiunta UE sono obbligatori.....

Come lo cancello ??????

Grazie, Andrea Galli

**Comment by galliandrea** [comment]
[49319_Richiesta5010.txt](https://github.com/italia/anpr/files/12228891/49319_Richiesta5010.txt)

**Comment by frmariani** [comment]
Deve semplicemente eliminare il tipo mutazione 2 dalla richiesta.

**Comment by galliandrea** [comment]
Buongiorno, ho provato come indicato a togliera dalla variazione inviata il tipo mutazione 02 e la mutazione passa .... solo che l'elettore non viene cancellato. Se consulto l'elettore risulta ancora attivo nelle liste aggiunte dei comunitari quando invece io devo cancellarlo. 
[49363_Risposta3002.txt](https://github.com/italia/anpr/files/12335813/49363_Risposta3002.txt)
[49362_Risposta5010.txt](https://github.com/italia/anpr/files/12335814/49362_Risposta5010.txt)
[49362_Richiesta5010.txt](https://github.com/italia/anpr/files/12335815/49362_Richiesta5010.txt)

**Comment by amollicone1982** [comment]
Forse c'è stato un misunderstanding. Quando deve mettere il soggetto che ha una lista ue in stato cancellando per iscriverlo in un altra lista UE di un altro comune è giusto quanto fatto. Ma in realtà lei deve cancellare la lista UE per poi iscriverlo in una lista generale. Per tale motivo deve inviare un 5010 con tipomutazione 05 e motivo cancellazione 05 o 06 a seconda se deve eliminare la lista aggiunta UE per le comunali o per le parlamentari.
Buona giornata

**Comment by amollicone1982** [comment]
Avete effettuato con successo la cancellazione della lista ue per le parlamentarie ma vi manca quella per le comunali (motivo cancellazione 5)

1	Trasferimento residenza	
2	Irreperibilita	
3	Morte	
4	Motivi vari	
5	Cancellazione lista aggiunta UE comunali	
6	Cancellazione lista aggiunta UE parlamento europeo	
7	Cancellazione lista aggiunta comunali regionali	
8	Cancellazione lista generale
