### ISSUE TITLE
[5008] TEST - TipoMutazione 16 - Errore da ANPR (500) Internal Server Error

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#4029]
Buongiorno,

abbiamo un problema con le operazioni sulle convivenze di fatto, sia in fase di costituzione di una nuova CVF che in caso di variazione di una CVF esistente.

Il servizio 5008 tipoMutazione 16 restituisce il seguente messaggio di errore:
Anagrafe.ANPR.Request.ANPRException: Il server ANPR ha restituito un errore (Internal Error) ---> System.Net.WebException: The remote server returned an error: **(500) Internal Server Error**.

Non viene restituita alcuna risposta quindi non ho esempi di operazione da fornire. Se può essere utile posso inviare l'XML di un servizio che non viene accettato e quello di uno che solo alcuni giorni fa veniva regolarmente accettato. 
A noi non risultano differenze evidenti.

Gli altri servizi, sia 5008 che altri, funzionano regolarmente.

Potete darci qualche suggerimento per analizzare il problema?
Grazie
Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by spedrini** [comment]
Buongiorno, 
anche noi stiamo riscontrando lo stesso problema.
Segnalo anche che da webapp ambiente di test, quando si tenta di salvare una mutazione di tutti i dati nella sezione Convivenza di fatto o Risoluzione convivenza, si viene bloccati con questo errore: "Spiacenti al momento il servizio non è disponibile".
Potete darci riscontro?

Grazie 
Serena Pedrini
MAGGIOLI SPA

**Comment by spedrini** [comment]
Buongiorno,
il servizio 5008 tipoMutazione 16 continua ad andare in errore.
Potete darci riscontro?
Grazie

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, anche noi continuiamo a riscontrare il problema e abbiamo alcune implementazioni bloccate per questo motivo pertanto chiediamo un riscontro appena possibile. Grazie

**Comment by amollicone1982** [comment]
Buongiorno, scusate il ritardo ma ci sono state le ferie di mezzo. In tutte e due i casi si tratta di operazioni fatte da web? Se si in quale momento della navigazione prendete errore? Nella ricerca del soggetto o della famiglia?

**Comment by spedrini** [comment]
L'errore segnalato si presenta quando si invoca il servizio di 5008 con tipoMutazione 16.
Abbiamo poi notato che da webapp ambiente di test, quando si tenta di salvare una mutazione di tutti i dati nella sezione Convivenza di fatto o Risoluzione convivenza, si viene bloccati con questo errore: "Spiacenti al momento il servizio non è disponibile".

**Comment by amollicone1982** [comment]
Potete riprovare adesso

**Comment by MoniaPedrazzoli** [comment]
Confermo la soluzione del problema sia da WS 5008 che da WebApp. Grazie

**Comment by amollicone1982** [comment]
Si trattava di una problematica relativa al solo ambiente di test. Buon lavoro
