### ISSUE TITLE
Revisione notifiche per i comuni

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#403]
Tracking issue per la revisione del sistema di notifiche per comuni e sw house

**Comment by gcarbonin** [comment]
L'intervento è stato completato

**Comment by busaster** [comment]
Salve.

Che tipo di revisione è stata fatta ?
Esiste già documentazione in merito ?

Grazie

**Comment by rvinzani** [comment]
E possibile consultare la documentazione nel sito www.anpr.interno.it 
Specifiche di interfaccia dei servizi di ANPR per i comuni – documento generale  (§6.2 e §23)

**Comment by busaster** [comment]
A me i paragrafi 6.2 e 23 sono identici a quelli della documentazione di febbraio.
Forse mi sto perdendo in un bicchiere d'acqua ma non riesco a capire cosa sia cambiato.

**Comment by mccalv** [comment]
@busaster chiudo questa discussione per continuarla sulla #689.
