### ISSUE TITLE
Richiesta contributo mancata attivazione flag

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#4035]
Buongiorno,

i comune 022191 e 022098 con il nostro supporto hanno effettuato il subentro dei dati elettorali in ANPR.

Ora procedendo con al richiesta di contributo non appare attivo il secondo flag:

"integrazione dei Web Services resi disponibili per l'acquisizione e l'aggiornamento puntuale della posizione elettorale dei cittadini di propria competenza"

Leggo nel manuale che viene attivato automaticamente, cosa verificate?

Come possiamo modificarlo?

Il Software in uso dal Comune è ovviamente Civilia Next che risulta già integrato con i WS ministeriali.

Mi fai sapere?

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50

**Comment by RBiasi** [comment]
Aggiungo anche il comune di Castegnato (BS) con lo stesso identico problema.

Grazie

**Comment by frmariani** [comment]
il comune deve inviare un WS 5010 ed un WS 5011 per dimostrare che ha integrato i servizi di mutazione.
Il giorno seguente troverà il flag spuntato.

**Comment by RBiasi** [comment]
Potete evadere la segnalazione grazie

**Comment by frmariani** [comment]
Il comune di Tenno ha verificato questa mattina?
Per il comune di Isera ancora non risultano operazioni (anche non significative) con WS 5010 e WS 5011

**Comment by RBiasi** [comment]
A posto sia Isera che Tenno. Grazie
