### ISSUE TITLE
Integrazione liste elettorali. EN557. Sezioni inesistenti

### ISSUE THREAD

**Issue by MarcoZoagli1** [italia/anpr#4037]
Questo Comune ha 4 sezioni elettorali. Probabilmente in fase di caricamento del file delle sezioni, si è verificata una qualche anomalia. Infatti una volta caricato anche il file degli elettori, per tutti quelli ricompresi nelle sezioni 2,3 e 4 viene segnalata anomalia: EN557;La sezione elettorale numero 3 del comune ZOAGLI (GE) ? inesistente (protocollo di errore: [204933542]). Contattata l'assistenza (ticket 02934375) viene suggerito di procedere, elettore per elettore, mediante accesso alla web app ANPR, come segue:
REGISTRAZIONE-MUTAZIONE TUTTI I DATI-OPERAZIONE D'UFFICIO-ricercare la persona con id ANPR - selezionare con icona lente - DATI DI CONTROLLO - LISTE - lista elettorale - ed inserire, se mancante, la provincia ed il Comune. Secondo l'assistenza a questo punto si dovrebbero aggiornare automaticamente anche i dati della lista. Invece cio' non accade, i dati di lista generale e sezionale continuano ad essere valorizzati solo per la sez. 1.  Anche in considerazione del gran numero di elettori mancanti di sezione, si chiede se non sia possibile "ripulire" i dati già caricati sulla webapp e provare quindi a reinserire prima le sezioni e poi gli elettori .
Comune di Zoagli (GE)
demografici@comune.zoagli.ge.it

**Comment by MarcoZoagli1** [comment]
Buongiorno
in occasione del precedente contatto si era concordato di verificare se fosse possibile "ripulire" i dati e ricaricarli nuovamente.
Ad oggi non ho avuto alcuna comunicazione, sono stato invece contattato dalla Ditta fornitrice del software che - nel caso non fosse possibile tale soluzione - propone un servizio per caricare massivamente i dati degli elettori privi di sezione. Chiedo quindi se si possa procedere come a suo tempo indicato dalla D.ssa Mariani, nel caso potrà contattarmi ai miei recapiti. Grazie Marco Raso - comune di Zoagli

**Comment by frmariani** [comment]
chiudo la issue in quanto ci siamo accordati telefonicamente
