### ISSUE TITLE
Scarico per motivata richiesta - nuovi tag elettorali

### ISSUE THREAD

**Issue by migmar68** [italia/anpr#4039]
Buongiorno
In caso di migrazione di software comunale, è necessario verificare i dati elettorali presenti in ANPR e allo scopo è utile, anche se non completo, questo scarico.
Provandolo però ci sembra che scarichi ancora la versione ANPR02, in quanto mancano i nuovi tag elettorali. Potete verificare?
Grazie.

**Comment by paoloHV** [comment]
Sono TAG da inserire nella richiesta "classica" o sarà presente uno "scarico" dalla voce "liste elettorali"?

**Comment by migmar68** [comment]
Non so cosa è previsto ma certo sarebbe l'ideale una voce apposita, che eliminerebbe il problema delle discrepanze anagrafe-elettorale.

- nuovi residenti, che sono ancora elettori di altro comune
- emigrati, che sono ancora elettori del nostro comune
- residenti in AO BZ TN, ma liste aggiunte nel nostro comune...

**Comment by migmar68** [comment]
Sollecito la richiesta visto che ormai la gestione è operativa, e l'esigenza sarà necessaria a breve.

**Comment by amollicone1982** [comment]
Buongiorno,
stiamo predisponenendo uno scarico elettorale ad hoc. In caso di cambio casa software se fate lo scarico massivo attuale vi compariranno i dati elettorali
