### ISSUE TITLE
Consultazione elettorale cittadino AIRE iscritto in Lista aggiunta AO

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#4048]
Da webapp alla voce di menu ELETTORALE - CONSULTAZIONE non riusciamo a consultare la posizione del cittadino Id ANPR 35600140.

Il cittadino ci risulta correttamente subentrato come cittadino AIRE iscritto nella lista aggiunta della valle d'Aosta del comune di Castegnato.

Non si evidenziano errori nella consultazione di altre posizioni iscritte nelle liste aggiunte TN e BZ.

Potete verificare?

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50

**Comment by amollicone1982** [comment]
Può riprovare adesso?
