### ISSUE TITLE
[5010] e [5011] errore in trasmissione variazione

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#4050]
Comune di Borgo Ticino (NO) - Ambiente di Produzione

Facendo la trasmissione delle sezioni elettorali al comune di Borgo Ticino riusciamo a trasmettere con il servizio 5011 solo la sezione numero 1, la trasmissione delle altre sezioni ci viene respinta con un 'errore generico', vedi ID ANPR 1412389678.
Al fine di completare il subentro abbiamo caricato altre 3 sezioni direttamente dalla WebApp ma pur avendolo fatto con esito positivo le sezioni non risultano utilizzabili dai servizi 5010.
Infatti se cerchiamo di trasmettere le iscrizioni degli elettori nella sezione 1 tutto funziona correttamente mentre per le altre sezioni ricompare l'errore generico, vedi ID ANPR 1412388126.
Il tutto è stato causato dal rigetto dei 2 file di subentro perché nei collegi della Camera per le 4 sezioni era indicato Piemonte 2 invece di PIEMONTE 2.

Cortesemente potete verificare le cause dell'errore?

Grazie.

**Comment by frmariani** [comment]
perchè parla di errori generici?
WS 5011 l'errore mi sembra specifico: EN562 -  campo Collegio plurinominale e collegio uninominale per la Camera dei deputati non corrispondente alla tabella di riferimento 
infatti il formato del campo non è corretto
WS 5011  l'errore mi sembra specifico: EN562 - campo Circoscrizione del territorio nazionale/Ripartizione della circoscrizione Estero per la Camera dei deputati non corrispondente alla tabella di riferimento
infatti il formato del campo non è corretto

Dovete utilizzare esattamente il formato proposto nelle tabelle.

**Comment by LucaBonini64** [comment]
Buongiorno, ho verificato meglio e la procedura mi restituiva un errore generico mentre invece nell'XML che la delivery non aveva controllato gli errori erano indicati chiaramente, quindi ho riscontrato la differenza di formato e corretto esattamente come da tabelle di riferimento risolvendo il problema, chiudo la segnalazione. Grazie.
