### ISSUE TITLE
[P002] EN148

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4053]
Buongiorno,
in Ambiente di Test sto facendo delle chiamate P002 per ottenere il dettaglio delle richieste.
Mi sta dando sempre due errori:
- prima Internal Server Error
- e poi "Una operazione con lo stesso id operazione comune risulta ancora in elaborazione" (idOperazioneANPR 56679816)

Potete verificare e dirmi se stiamo sbagliando qualcosa?
Grazie

**Comment by ncapozzi** [comment]
Il problema è stato risolto. Potete riprovare
