### ISSUE TITLE
ANPR04 - EN122 - Urgente

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4055]
Produzione - ANPR04
id operazione ANPR: 1416629109

tutte le 3002 che facciamo ci restituiscono l'errore EN122 (La richiesta effettuata non produce alcun risultato).
Invece in Ambiente di Test con ANPR04 le 3002 funzionano correttamente.

Potete verificare?

Grazie

**Comment by SAlberto** [comment]
Abbiamo trovato il problema grazie lo stesso

**Comment by gp-elips** [comment]
> Abbiamo trovato il problema grazie lo stesso

Ciao @SAlberto , abbiamo lo stesso problema, potrebbe dirci di cosa si tratta?
