### ISSUE TITLE
[P002] PROD GENOVA Richiesta dettaglio 28490566 dà errore 'Il server ANPR ha restituito un errore (Internal Error)'

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#4058]
Buongiorno,

il comune di Genova ci segnala che richiedendo il dettaglio della richiesta 28490566 del 25/08/2023 tramite il servizio P002 non viene restituita alcuna risposta a causa dell'errore in oggetto.

Potete verificare urgentemente?
Grazie
Monia Pedrazzoli 
APKAPPA s.r.l.

**Comment by MoniaPedrazzoli** [comment]
Stiamo verificando che anche altre richieste di dettaglio restituiscono il medesimo errore. Attendiamo riscontro appena possibile, grazie.

**Comment by siscomanpr** [comment]
Rileviamo anche noi lo stesso problema per diversi nostri clienti.

Siscom SPA

**Comment by ncapozzi** [comment]
Il problema è stato risolto. Potete riprovare
