### ISSUE TITLE
C002 - Servizio di Comunicazione

### ISSUE THREAD

**Issue by LuigiBonella** [italia/anpr#4063]
Buongiorno,
effettuando un test in ambiente di collaudo verso il vostro servizio di interop della piattaforma PDND ([C002 - Servizio di Comunicazione](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C002-servizioComunicazione/v1/anpr-service-e002)) abbiamo ricevuto un errore di cui vorremmo avere qualche specifica.

Nel dettaglio:

Data di invio: 31-08-2023 12:06:17

La piattaforma PDND ha generato correttamente l'access token che abbiamo incluso nell'header della chiamata,
abbiamo inserito anche Agid-JWT-Signature e Agid-JWT-TrackingEvidence come descritto nelle specifiche di sicurezza contenute nello yaml del servizio invocato

I nostri dati inviati:
{"idOperazioneClient":"103","criteriRicerca":{"codiceFiscale":"XXXX"},"datiRichiesta":{"dataRiferimentoRichiesta":"2023-08-30","motivoRichiesta":"test","casoUso":"C002"}}

Messaggio ricevuto (ContentType:application/problem+json) :
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"8af2467d-47da-11ee-8c98-005056ae5232"} 

Grazie

**Comment by menny68** [comment]
Se può essere utile ho realizzato il seguente script python

https://github.com/menny68/anpr-pdnd-example.git
