### ISSUE TITLE
ANNULLAMENTO PER DOPPIA ISCRIZIONE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#4070]
Buongiorno,
COMUNE 061022 - 
Abbiamo la necessità di cancellare, per bonifica dati invio dati elettorali, un iscritto AIRE (subentro da ANAGAIRE) presente come duplicato.  Non ci consente la cancellazione per duplice iscrizione poiché le due posizioni riguardano lo stesso comune (061022).
Quale procedura dobbiamo utilizzare per cancellare una delle due posizioni anagrafiche?
Grazie

**Comment by rinonasti** [comment]
SOLLECITO

**Comment by frmariani** [comment]
gentilmente l'identificativo dell'operazione

**Comment by rinonasti** [comment]
Il soggetto non può  essere cancellato per doppia iscrizione perché non risultano due o più' posizioni in ANPR (Codice: EN509)

Informazioni sull'operazione da fornire in caso di assistenza : data 2023-09-13 12:25:14 , idOperazioneANPR 1436148504 (Codice: EN527)

**Comment by rinonasti** [comment]
Buonasera si è presentato un altro caso uguale:
Il soggetto non può essere cancellato per doppia iscrizione perché non risultano due o più' posizioni in ANPR (Codice: EN509)

Informazioni sull'operazione da fornire in caso di assistenza : data 2023-09-21 16:37:48 , idOperazioneANPR 1446702517(Codice: EN527) 

grazie
