### ISSUE TITLE
Impossibilità di cambiare di stato ad una dichiarazione di residenza

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4073]
COMUNE DI VILLACORTESE PROD

Buongiorno, 

In data odierna il comune stava provando a gestire la dichiarazione numero: 28524283
Ma scorrendo verso il basso, dove solitamente di permettere di fare i passaggi di stato, i pulsanti sono spariti.

![Screenshot_2](https://github.com/italia/anpr/assets/75251517/3c3d2f99-82ef-474e-9366-3149db280bab)

E' possibile fare un controllo?

Grazie

**Comment by cvignati** [comment]
Buongiorno,
sono il Responsabile dell'Ufficio Anagrafe del comune che ha la problematica.

Chiedo la cortesia di una rapida risoluzione al fine di istruire la pratiche nelle tempistiche di legge.

Grazie

**Comment by jonnyfx95** [comment]
Anche il comune di LEGNANO ha lo stesso problema.
Ha 3 dichiarazioni inviate il 04/09/2023 che non è possibile portare avanti da WEBAPP e non vengono nemmeno scaricate dal servizio P002 sul nostro gestionale.

ID richiesta:

28521917
28521783
28520575

**Comment by gppbarone** [comment]
Buonasera, 
potete riprovare ora cortesemente?

Saluti,
Assistenza ANPR

**Comment by jonnyfx95** [comment]
Confermo che il problema è stato risolto, grazie!
