### ISSUE TITLE
Richiesta contributi per integrazione dati elettorali

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4074]
Ambiente di Produzione
Comune (istat): 004028

Il comune il 24/08 ha effettuato il caricamento dei file per il subentro delle liste elettorali, ma ad oggi durante la richiesta del contributo, il secondo check ("integrazione dei Web Services resi disponibili per...") non è spuntato.

![image](https://github.com/italia/anpr/assets/33952624/36d530b5-961a-4534-994c-d2968b149d91)

Potete verificare?

Grazie

**Comment by frmariani** [comment]
I primi due check sono verificati dal sistema ecco perchè non riuscite a spuntarli;
il sistema verifica che abbiate eliminato le anomalie dei duplicati  (primo check) e che abbiate integrato il vostro gestionale con  i servizi elettorali (WS5010 e WS 5011).
Per la richiesta del contributo elettorale consiglio di scaricare la guida presente nel portale ANPR
https://www.anpr.interno.it/wp-content/uploads/Istruzioni-operative-erogazione-incentivo-Liste-elettorali.pdf

**Comment by SAlberto** [comment]
La domanda non era perchè non riescono a spuntarli, chiedevo come mai a seguito dell'avvenuto subentro e quindi l'avvenuta integrazione del gestionale con i WS la seconda spunta non sia comparsa.

**Comment by frmariani** [comment]
se il subentro è avvenuto con upload del file non significa che siano stati integrati i servizi con il gestionale.
Dovete effettuare delle mutazioni anche non significative di una sezione  e dei dati elettorali di un cittadino per dimostrare che i servizi siano stati realizzati (WS 5010 e WS 5011).
Per il comune indicato non sono presenti operazioni dei dati elettorali.

**Comment by SAlberto** [comment]
Fare delle mutazioni casuali in ambiente di produzione non è la più saggia delle idee, ma provvederemo.
Grazie

**Comment by frmariani** [comment]
sono delle mutazioni non significative e comunque la richiesta è sancita nell'art.3 comma 1 del Decreto di riparto n. 18/2023
