### ISSUE TITLE
[3002] Non trovo cittadini iscritti con servizio 1002

### ISSUE THREAD

**Issue by ftabino** [italia/anpr#408]
Salve, a seguito di un'iscrizione con esito positivo di un cittadino attraverso il servizio 1002, la relativa consultazione, sia per nome e cognome che per identificativo ANPR, attraverso il servizio 3002 da sempre esito KO con il seguente errore 
```xml
<errore>
    <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
</errore>
```

Nel caso riprovi a rieffettuare l'iscrizione dello stesso cittadino ricevo come errore che il soggetto è già presente su ANPR.

Ambiente:**TEST**
Comune: **AVIGLIANO** **076007**

**Comment by gcarbonin** [comment]
Puo' indicarci il numero dell'operazione di iscrizione?

**Comment by ftabino** [comment]
```xml
<idOperazioneComune>396</idOperazioneComune>
<idOperazioneANPR>614362</idOperazioneANPR>
```

**Comment by gcarbonin** [comment]
Il 3 novembre e' stata effettuata l'iscrizione. Lo stesso giorno è stata richiesta la cancellazione del subentro che elimina tutti i dati. L'interrogazione fatta oggi e' normale che non trovi nulla

**Comment by ftabino** [comment]
Ho effettuato un'iscrzione con l'applicativo WEB e nonostante l'esito positivo comunque non riesco a  cercare il cittadino.

l'iscrizione ha id operazione ANPR 620896
il soggetto ha id scheda ANPR 9720330

**Comment by gcarbonin** [comment]
Ha rimandato i dati del subentro? Se non lo ha fatto il dato viene acquisito ma non e' interrogabile

**Comment by ftabino** [comment]
No, volevo solo testare solo la funzionalità dell'iscirizione 1002 e della consultazione. 
Provedderò a inviare il file del subentro. 

Grazie per il supporto.
