### ISSUE TITLE
Problemi con la validazione email nel profilo utente

### ISSUE THREAD

**Issue by fraverr11** [italia/anpr#4080]
Salve,

non ricevo nessuna email per fare la validazione della mia email nel profilo utente e poter inviare il cambio di residenza. Qualsiasi aiuto benvenuto 

grazie

**Comment by apaolacci** [comment]
Salve,
riscontra ancora il problema ? Ha ricevuto l'email e ha potuto validare il suo recapito?

Saluti,
Assistenza ANPR

**Comment by fraverr11** [comment]
Si sono riuscito grazie CheersFrancescoOn 20 Sep 2023, at 15:28, apaolacci ***@***.***> wrote:﻿
Salve,
riscontra ancora il problema ? Ha ricevuto l'email e ha potuto validare il suo recapito?
Saluti,
Assistenza ANPR
