### ISSUE TITLE
Non arriva mail per validare indirizzo 

### ISSUE THREAD

**Issue by FrancescaTimolina** [italia/anpr#4082]
Sia io che mia sorella ci siamo iscritte per fare cambio di residenza con lo spid ma non arriva ad entrambe la mail di validazione... com'è possibile.
Controllato anche nello spam ovunque ma niente!!!!
sempre il solito malfunzionamento della pubblica amministrazione e ovviamente in comune dicono fatelo on line ... poi on line non va mail niente!!!!

**Comment by antov97** [comment]
anche io con la stessa problematica... posso chiedervi come avete risolto?

**Comment by apaolacci** [comment]
Salve,
riscontra ancora il problema? Ha ricevuto l'email e ha potuto validare il suo recapito?

Saluti,
Assistenza ANPR
