### ISSUE TITLE
Richiesta contributo: sistema momentaneamente non disponibile

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#4085]
Buongiorno,
il comune 022181 sta cercando di caricare la richiesta di contributo da ieri, una volta passata la prima maschera (correttamente compilata) si ha l'errore sotto.

![errore](https://github.com/italia/anpr/assets/29278221/4e56cc1b-2267-43ce-9ca7-d72d64ca0b92)

Potete verificare.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Market Line Smart Cities
Deda Next – Sede di Trento, Via di Spini 50

**Comment by lorbia** [comment]
Salve, ci confermate che il problema non sussista più ?

Saluti.
