### ISSUE TITLE
[2003] Errore EN240

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#409]
ambiente di PRODUZIONE - Comune di Medicina BO - idOperazione 2017000632

caso di cittadino iscritto all'AIRE, che viene cancellato per rimpatrio in altro comune italiano.
la comunicazione va in errore con il seguente messaggio:
EN240 - E - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 

sembra non siano state effettuate operazioni sull'individuo.
può essere il problema della data di decorrenza antecedente al subentro di cui alla issue #370 ?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
L'ultima operazione effettuata sul soggetto è il subentro avvenuto in data 20 ottobre. La cancellazione dovrebbe decorrere dal 12 (a quanto vedo dalla richiesta): se fosse stata trasmessa nei termini, il soggetto non sarebbe stato conferito. Al momento da ANPR si può cancellare solo mettendo data 20 ottobre

**Comment by AMonopoliADS** [comment]
ok. come immaginavamo. ma trattandosi di cancellazione di soggetto AIRE avevamo il dubbio ci fossero altre motivazioni.

Le chiedo però un'ulteriore conferma al riguardo, per capire se ci sono altre condizionanti che ci sfuggono.
faccio un altro esempio:
ambiente di PRODUZIONE - Comune di San Lazzaro di Savena BO - idOperazione 2017000014

il comune è subentrato il 06/11/2017.
la comunicazione è relativa ad una cancellazione (ws 2003) con decorrenza 24/10/2017.
la comunicazione è stata inviata il 07/11/2017 ed è stata accettata.

mi sarei aspettato lo stesso blocco di cui sopra.

grazie

**Comment by gcarbonin** [comment]
Come indicato nelle specifiche, la data di inizio validita di una scheda in ANPR tiene conto di tre informazioni:

- data iscrizione
- data decorrenza della residenza
- data ultima variazione

Se una delle tre manca o è incoerente (spesso la data di decorrenza è antecedente alla data di iscrizione ad esempio), si mette come data di inizio validita quella del subentro.
Nel secondo esempio la data di inizio validita è 21.6.2017; quindi la cancellazione in data 24.10,2017 e' coerente con quanto registrato anche se il subentro e' avvenuto dopo.

**Comment by AMonopoliADS** [comment]
quindi, nel caso della cancellazione aire, immagino che il dato mancante sia la "data ultima variazione" (... in quanto non presente nel file dell'anag-aire...).
da qui l'entrata in gioco della data del subentro

se è così... ho capito.

grazie.

**Comment by gcarbonin** [comment]
Le date per l'aire sono queste:

data di iscrizione AIRE; equivale alla data di prima iscrizione di un soggetto nell’AIRE del comune;
data di aggiornamento indirizzo; corrisponde alla data di decorrenza della residenza della famiglia AIRE;
data di ultima modifica; corrisponde alla data di ultima variazione dei dati di un soggetto ; come per i residenti, si tratta di un dato da desumere dal sistema informativo del comune, già trattato dall’attuale AnagAire

L'ultima è presente nel tracciato aire
