### ISSUE TITLE
Cambio residenza - Errore non gestito

### ISSUE THREAD

**Issue by etorrenti** [italia/anpr#4091]
Salve,
segnalo che, al termine della procedura di cambio residenza (id 28538406), arrivato alla scheda riepilogo, ricevo un generico "Si è verificato un errore non gestito" e che mi è impossibile inviare la richiesta, ma solo salvarla in bozza.

Nella console, la chiamata GET all'endpoint:
`https://sc.anpr.interno.it/api-home/jaxrs/doc/template/pratica_summary/type/fhtml/id/28538406?v=1694431604805&mode=1 `

ottiene codice 500 con testo della risposta:

```
Error 500: org.apache.cxf.interceptor.Fault: JVMVRFY012 stack shape inconsistent&#59; class=it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic, method=configureInit&#40;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;&#41;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;, pc=20&#59; Type Mismatch, argument 1 in signature it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic.loadConfig:&#40;Ljava/io/InputStream&#59;Lorg/fugerit/java/core/util/filterchain/MiniFilterConfig&#59;&#41;Lorg/fugerit/java/core/util/filterchain/MiniFilterConfig&#59; does not match
Exception Details:
  Location:
    it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic.configureInit&#40;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;&#41;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59; @20: JBinvokestatic
  Reason:
    Type &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39; &#40;current frame, stack[1]&#41; is not assignable to &#39;org/fugerit/java/core/util/filterchain/MiniFilterConfig&#39;
  Current Frame:
    bci: @20
    flags: { }
    locals: { &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39;, &#39;java/io/InputStream&#39;, null }
    stack: { &#39;java/io/InputStream&#39;, &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39; }
  Exception Handler Table:
    bci [83, 87] =&gt; handler: 90
    bci [8, 75] =&gt; handler: 106
    bci [8, 75] =&gt; handler: 111
    bci [121, 125] =&gt; handler: 128
    bci [106, 113] =&gt; handler: 111
    bci [0, 146] =&gt; handler: 149
  Stackmap Table:
    full_frame&#40;@90,{Object[#55],Object[#56],Object[#57]},{Object[#57]}&#41;
    same_frame&#40;@99&#41;
    same_locals_1_stack_item_frame&#40;@106,Object[#57]&#41;
    same_locals_1_stack_item_frame&#40;@111,Object[#57]&#41;
    full_frame&#40;@128,{Object[#55],Object[#56],Object[#57],top,Object[#57]},{Object[#57]}&#41;
    same_frame&#40;@139&#41;
    same_frame&#40;@143&#41;
    full_frame&#40;@146,{Object[#55]},{}&#41;
    same_locals_1_stack_item_frame&#40;@149,Object[#58]&#41;
    same_frame&#40;@187&#41;

```

**Comment by rich1990** [comment]
stesso problema

**Comment by fmauriello** [comment]
Segnalo lo stesso problema, 28538325

`Error 500: org.apache.cxf.interceptor.Fault: JVMVRFY012 stack shape inconsistent&#59; class=it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic, method=configureInit&#40;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;&#41;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;, pc=20&#59; Type Mismatch, argument 1 in signature it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic.loadConfig:&#40;Ljava/io/InputStream&#59;Lorg/fugerit/java/core/util/filterchain/MiniFilterConfig&#59;&#41;Lorg/fugerit/java/core/util/filterchain/MiniFilterConfig&#59; does not match
Exception Details:
  Location:
    it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic.configureInit&#40;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59;&#41;Lit/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#59; @20: JBinvokestatic
  Reason:
    Type &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39; &#40;current frame, stack[1]&#41; is not assignable to &#39;org/fugerit/java/core/util/filterchain/MiniFilterConfig&#39;
  Current Frame:
    bci: @20
    flags: { }
    locals: { &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39;, &#39;java/io/InputStream&#39;, null }
    stack: { &#39;java/io/InputStream&#39;, &#39;it/interno/anpr/sc/lib/shared/doc/ScDocConfigBasic&#39; }
  Exception Handler Table:
    bci [83, 87] =&gt; handler: 90
    bci [8, 75] =&gt; handler: 106
    bci [8, 75] =&gt; handler: 111
    bci [121, 125] =&gt; handler: 128
    bci [106, 113] =&gt; handler: 111
    bci [0, 146] =&gt; handler: 149
  Stackmap Table:
    full_frame&#40;@90,{Object[#55],Object[#56],Object[#57]},{Object[#57]}&#41;
    same_frame&#40;@99&#41;
    same_locals_1_stack_item_frame&#40;@106,Object[#57]&#41;
    same_locals_1_stack_item_frame&#40;@111,Object[#57]&#41;
    full_frame&#40;@128,{Object[#55],Object[#56],Object[#57],top,Object[#57]},{Object[#57]}&#41;
    same_frame&#40;@139&#41;
    same_frame&#40;@143&#41;
    full_frame&#40;@146,{Object[#55]},{}&#41;
    same_locals_1_stack_item_frame&#40;@149,Object[#58]&#41;
    same_frame&#40;@187&#41;
`

**Comment by mttfranci** [comment]
Salve, potreste riprovare?
Grazie in anticipo.

**Comment by rich1990** [comment]
> Salve, potreste riprovare? Grazie in anticipo.

funziona, grazie per il fix

**Comment by etorrenti** [comment]
Andato. Grazie
