### ISSUE TITLE
Cancellazione Subentro Liste Elettorali

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4095]
Comune 096020
Produzione

Abbiamo bisogno di effettuare la cancellazione del Subentro per la parte delle LISTE ELETTORALI.
Differentemente dall'ambiente di Test, dal comune non trovo la scheda "Richiesta cancellazione subentro".

![image](https://github.com/italia/anpr/assets/33952624/3ae51e3d-88bd-4fbc-8ad7-4a63bd8d2f97)

Potete verificare?
Grazie

**Comment by Ennio71** [comment]
#4072

**Comment by frmariani** [comment]
in ambiente di produzione non è prevista la cancellazione del subentro

**Comment by SAlberto** [comment]
Il caricamento delle sezioni ha dato delle anomalie, e il seguente caricamento delle liste ha dato lui stesso errori.
Il risultato è che solo gli elettori di 2 liste sono presenti.

Le sezioni le abbiamo corrette a mano, ma per gli elettori?
Abbiamo bisogno di ricaricare il file

**Comment by amollicone1982** [comment]
Per queste due sezione avete caricato 1830 elettori. Mi confermate che in totale avete 10 sezioni?

**Comment by SAlberto** [comment]
In totale il comune ha 13 sezioni

**Comment by amollicone1982** [comment]
quello che vi posso dire è che in questo momento avete censito 10 sezioni dalla 1 alla 10

**Comment by amollicone1982** [comment]
Allora, vi potre cancellare il file degli elettori (a seguito di pec) e voi rimandate il file (se riuscite escludendo 1830 già caricati altrimenti prenderete un errore di primo caricamento già effettuato per questi)

**Comment by SAlberto** [comment]
Sono collegato con il comune e le liste dalla 11 alla 13 e ci sono.
Vi allego uno screenshot
![image](https://github.com/italia/anpr/assets/33952624/0a65f8e6-6b46-4f74-8da0-61ca5c194089)

**Comment by amollicone1982** [comment]
scusate mi sono sbagliato,
allora vi potrei cancellare il file degli elettori (a seguito di pec) e voi rimandate il file (se riuscite escludendo 1830 già caricati altrimenti prenderete un errore di primo caricamento già effettuato per questi)

**Comment by SAlberto** [comment]
Perfetto, a quale indirizzo possiamo scrivere? grazie

**Comment by amollicone1982** [comment]
***@***.***

Mettete in cc ***@***.***

Buona giornata

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SAlberto** [comment]
Chiedo scusa, ma non si legge l'indirizzo

**Comment by amollicone1982** [comment]
[Assistenza.anpr@pec.sogei.it](mailto:Assistenza.anpr@pec.sogei.it)

Mettete in cc [amollicone@sogei.it](mailto:amollicone@sogei.it)

**Comment by amollicone1982** [comment]
è sufficiente rimandare il file escludendo i 1830 ma non ci è arrivata la pec del comune.

**Comment by amollicone1982** [comment]
Arrivata adesso, cancellazione effettuata
