### ISSUE TITLE
Anomalia P002

### ISSUE THREAD

**Issue by KibMcris** [italia/anpr#4097]
Buonasera,
in Ambiente di Test del Comune stiamo facendo delle chiamate P002 per ottenere il dettaglio delle richieste.
Otteniamo in risposta "Internal Server Error 500" e non riusciamo a scaricare il dettaglio della richiesta.
Fornisco un id operazione comune 116020 e codice Mittente 102044.
Alcuni clienti ci hanno segnalato alcune anomalie anche in produzione nei giorni scorsi.
Resto in attesa di un riscontro
Grazie

**Comment by apaolacci** [comment]
Salve,
è possibile riprovare l'invocazione ? 
Ieri troviamo traccia della richiesta ma non troviamo la risposta nei log.

[2023-09-13 16:46:23,677] INFO  MRZRNT63B25B098V -[START WS metodo : servizioP002_dettaglioPratica]

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<soapenv:Header/>
	<soapenv:Body>
		<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
			<testataRichiesta>
				<idOperazioneComune>116020</idOperazioneComune>
				<codMittente>102044</codMittente>
				<codDestinatario>ANPR02</codDestinatario>
				<operazioneRichiesta>P002</operazioneRichiesta>
				<dataOraRichiesta>2023-09-13T16:46:22.5247136+02:00</dataOraRichiesta>
				<tipoOperazione>C</tipoOperazione>
				<tipoInvio>TEST</tipoInvio>
				<dataDecorrenza>2023-09-13</dataDecorrenza>
				<nomeApplicativo>PEDemografici</nomeApplicativo>
				<versioneApplicativo>4.0</versioneApplicativo>
				<fornitoreApplicativo>Kibernetes</fornitoreApplicativo>
			</testataRichiesta>
			<criteriRicerca>
				<codiceRichiesta>1700420</codiceRichiesta>
			</criteriRicerca>
		</ns2:RichiestaP002>
	</soapenv:Body>
</soapenv:Envelope>
`

Saluti,
Assistenza ANPR

**Comment by KibMcris** [comment]
@apaolacci Abbiamo invocato nuovamente il servizio. Questa è la chiamata effettuata a cui otteniamo in risposta "Internal Server Error 500".

  <testataRichiesta xmlns="">
    <idOperazioneComune>116101</idOperazioneComune>
    <codMittente>102044</codMittente>
    <codDestinatario>ANPR02</codDestinatario>
    <operazioneRichiesta>P002</operazioneRichiesta>
    <dataOraRichiesta>2023-09-14T10:32:49.2888339+02:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>TEST</tipoInvio>
    <dataDecorrenza>2023-09-14</dataDecorrenza>
    <nomeApplicativo>PEDemografici</nomeApplicativo>
    <versioneApplicativo>4.0</versioneApplicativo>
    <fornitoreApplicativo>Kibernetes</fornitoreApplicativo>
  </testataRichiesta>
  <criteriRicerca xmlns="">
    <codiceRichiesta>1700420</codiceRichiesta>
  </criteriRicerca>
</RichiestaP002>

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, anche noi da diversi giorni riceviamo lo stesso errore per tutte le richieste P002 in ambiente di TEST. Il problema sembra identico a quello già segnalato e risolto di recente in ambiente di produzione #4058.

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, per noi tutto OK sia in test che in produzione. Grazie
