### ISSUE TITLE
Web-App Consultazione scheda individuale - Ricerca Avanzata "per indirizzo" non corretta

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#41]
Data test 20/03/2017 - Ambiente test (dptest)
Selezionato Tipo Ricerca = "Ricerca Famiglia/Convivenza Dato un indirizzo", se si ricerca l'indirizzo di residenza di un soggetto cui l'unica operazione  è stata il subentro compare il messaggio di errore "Ricerca famiglie/convivenze dato un indirizzo - Nessun risultato trovato" (come se non fosse presente ) es.VIA GIACOMO DINA 19 PIANO=PR NUI=1. 
Su Web-App abbiamo effettuato un cambio di indirizzo di intero nucleo in un indirizzo (VIA VINCENZO NAZZARO 5 PIANO=5 NUI=12) (ID OPERAZIONE = 440808) ove era già residente un soggetto da subentro. 
La ricerca per indirizzo visualizza solo il nucleo su cui è stato effettuato il cambio e non il residente già presente da subentro.
Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Può riprovare; mi faccia sapere se va bene

**Comment by annamariaGillone** [comment]
Abbiamo creato un nuovo caso: ricerca all'indirizzo LARGO FRANCESCO CIGNA 72 PIANO 05 NUI 27.
Abbiamo effettuato una prima ricerca ed ora compaiono due soggetti presenti da subentro all'indirizzo LARGO FRANCESCO CIGNA 72
1)  PPCCNZ68S69L219O è al piano 05 NUI 27
2) SCZSVN49A54B180R è al piano 04 NUI 22. 
L'anomalia di mancata visualizzazione soggetti da subentro è sanata. Non è però corretta la visualizzazione in quanto la ricerca era per piano 05 nui 27 e invece compare anche il secondo soggetto.
Successivamente abbiamo effettuato una mutazione di residenza per un altro soggetto STGLGU44D47D742G in LARGO FRANCESCO CIGNA 72 PIANO 05 NUI 27 ed effettuando nuovamente tale ricerca compaiono due righe riferite allo stesso indirizzo solo che in una la colonna SPECIE riporta LARGO; aprendo il dettaglio compare il nuovo soggetto più gli altri due già visualizzati in precedenza. 
Vi sono altre anomalie relative alla PRESENZA FAMIGLIA COABITANTE che però segnaleremo nel momento in cui sarà sanata questa.
Grazie




La modifica non è ancora adeguata

**Comment by gcarbonin** [comment]
Puo riprovare

**Comment by annamariaGillone** [comment]
Abbiamo verificato ed ora va bene. grazie!
