### ISSUE TITLE
[6001] errore EN079

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#410]
ambiente di PRODUZIONE - Comune di San Lazzaro di Savena BO - idOperazione 2017000373

buongiorno

sabato il cliente ha avuto delle difficoltà con il web-service di certificazione.
in particolare ci segnala che la richiesta di certificato con l'ID segnalato in testata è ritornata con il seguente errore:
EN079 - E - id operazione comune gia' presente  per un servizio diverso

dall'analisi dei nostri log non ci risultano altri tentativi di invii con stesso ID.
è possibile avere un vosto approfondimento della situazione per capire?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
C'e' una iscrizione andate male (che il comune ha completato oggi) con lo stesso id. In genere l'id di una operazione non deve mai essere riutilizzato.

**Comment by AMonopoliADS** [comment]
grazie del riscontro.

da ulteriore approfondimento abbiamo verificato che l'iscrizione a cui si riferisce non ha ottenuto risposta dal web-service, in quanto il sistema locale è andato in timeout dopo un minuto di attesa.
a questo punto chiedo:
- avete riscontrato rallentamenti dei web-service di produzione, nella mattinata di sabato 11/11?
- quale valore è ragionevole impostare come timeout locale, per lasciare il sistema in attesa di una risposta del web-service?

grazie.

**Comment by gcarbonin** [comment]
Sabato 11 ci sono stati problemi con la porta di dominio di Agenzia delle Entrate. Stiamo verificando se e come possiamo restituire un diagnostico in casi analoghi il time-out è 30 secondi
