### ISSUE TITLE
Consultazione Elettori e Riepilogo liste elettorali

### ISSUE THREAD

**Issue by SilviaRivi** [italia/anpr#4100]
Salve,
ambiente di produzione.

Abbiamo effettuato il primo caricamento della lista degli elettori 
ed abbiamo inviato tutti gli elettori comprese le varie liste aggiunte.

Effettuando la consultazione tramite WebApp di un soggetto presente nella 
listaAggiuntaComReg abbiamo visto che in realtà o non ci fa visualizzare 
nessun dato relativo alla lista elettorale, ma solo i dati generali del soggetto Id: 97279667,
oppure ci restituisce nessun soggetto trovato id: 202512230.
Potete verificare ?

Nel riepilogo delle liste elettorali abbiamo visto che non vengono conteggiati 
i soggetti delle liste aggiunte BolTreVal inviate con il primo caricamento, 
ma solo effettuando nuovamente l'invio dei soggetti tramite 5010 vengono 
successivamente conteggiati.

Dopo il primo caricamento occorre sempre reinviare la 5010 per le liste aggiunte?

Silvia Rivi
Palitalsoft s.r.l.

**Comment by amollicone1982** [comment]
Dopo il primo caricamento non occorre reinviare la 5010 per le liste aggiunte. Nel file di subentro (provate a ricontrollarlo) per questi due soggetti è stata inviata la sola informazione sulla certificabilità senza la lista aggiunta.
Per tale motivo non è stata caricata

**Comment by amollicone1982** [comment]
[file.gz](https://github.com/italia/anpr/files/12611804/file.gz)

**Comment by amollicone1982** [comment]
allego il file originale per farvi ricontrallare
