### ISSUE TITLE
[BUG] Non è possibile accedere al servizio

### ISSUE THREAD

**Issue by theoradicella** [italia/anpr#4103]
Hello! I can't access with my SPID to the Servizi anagrafici Anagrafe Nazionale, I see the following error:

<img width="1410" alt="Screenshot 2023-09-15 at 15 20 34" src="https://github.com/italia/anpr/assets/73081672/3aef4d8d-995d-42db-aae0-86e9ebd2d18a">

My Codice Fiscale is: RDCTHE01S27Z600A

@mttfranci

**Comment by mttfranci** [comment]
Salve, sembrerebbe che, analogamente alla issue #2809 , sia presente una anomalia legata al suo codice fiscale.
Nel suo caso il codice fiscale è presente ma non risulta essere correttamente agganciato (validato) con la banca dati di agenzia entrate.
Il legame tra l'accesso SPID/CIE/CNS e la scheda anagrafica avviene, al momento, attraverso il codice fiscale.
Dovrebbe rivolgersi al suo comune di competenza per sanare questa situazione sulla sua scheda.
Saluti

Assistenza ANPR
