### ISSUE TITLE
Mancata validazione mail Anpr

### ISSUE THREAD

**Issue by antov97** [italia/anpr#4104]
Salve, in data odierna ho tentato di effettuare il cambio residena tramite portale Anpr. Putroppo non ho ancora ricevuto la mail del sistema per validare la mia mail personale. Come posso procedere? Grazie

**Comment by apaolacci** [comment]
Salve,
riscontra ancora il problema ? Ha ricevuto l'email e ha potuto validare il suo recapito?

Saluti,
Assistenza ANPR

**Comment by antov97** [comment]
Salve, ho risolto per fortuna, grazie

Il giorno mer 20 set 2023 alle 15:26 apaolacci ***@***.***>
ha scritto:
