### ISSUE TITLE
[PDND C029] Errore di comunicazione con e-Service PDND C029-servizioAccertamentoDatiAnagrafici-approvazione_automatica

### ISSUE THREAD

**Issue by antoniopantocb** [italia/anpr#4105]
Buongiorno,
effettuando una chiamata verso il vostro servizio di interop della piattaforma PDND ([C029-servizioAccertamentoDatiAnagrafici](https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002)) abbiamo ricevuto un errore di cui vorremmo avere qualche specifica.

Nel dettaglio:

Data di invio: 18/09/2023

La piattaforma PDND ha generato correttamente l'access token che abbiamo incluso nell'header della chiamata.

I nostri dati inviati:
"curl -X 'POST' \
  'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer " . $voucher . "' \
  -H 'Agid-JWT-TrackingEvidence: " . $jwt . "' \
  -H 'Digest: SHA-256=" . $jwt_sha256 . "' \
  -H 'Content-Type: application/json' \
  -d '{
  \"idOperazioneClient\": \"6000\",
  \"criteriRicerca\": {
    \"codiceFiscale\": \"XXX\"
  },
  \"datiRichiesta\": {
    \"dataRiferimentoRichiesta\": \"2023-09-18\",
    \"motivoRichiesta\": \"XXX-23\",
    \"casoUso\": \"C029\"
  }
}'
"

L'errore ricevuto:

Returned with status 0 and output: Array ( [0] => {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0efa01ac-5628-11ee-a7c4-005056ae6555"} ) 

Grazie

**Comment by amollicone1982** [comment]
Buongiorno, state facendo dei test in ambiente di produzione anzichè collaudo. 
Questa la url di collaudo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002'

**Comment by antoniopantocb** [comment]
Buongiorno, 
chiedo all mia amministrazione di attivarla e appena pronta rilancio lo script e l'aggiorno se tutto ok. 
Grazie intanto 


Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "amollicone1982" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Martedì, 19 settembre 2023 9:44:36 
Oggetto: Re: [italia/anpr] [PDND C029] Errore di comunicazione con e-Service PDND C029-servizioAccertamentoDatiAnagrafici-approvazione_automatica (Issue #4105) 





Buongiorno, state facendo dei test in ambiente di produzione anzichè collaudo. 
Questa la url di collaudo: 
[ https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002 | https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002 ] '

**Comment by antoniopantocb** [comment]
Buongiorno,
chiedo all mia amministrazione di attivarla e appena pronta rilancio lo script e l'aggiorno se tutto ok.
Grazie intanto

**Comment by amollicone1982** [comment]
Ci dovrebbe essere un govway-id restituito dal servizio. Quale url sta chiamando?

**Comment by antoniopantocb** [comment]
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002

**Comment by antoniopantocb** [comment]
Ho notato che in PDND indicano uno diverso dallo yalm

**Comment by antoniopantocb** [comment]
indicano questo: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C029-servizioAccertamentoDatiAnagrafici/v1

**Comment by amollicone1982** [comment]
se vede su pdnd lo yaml la url è leggermente diversa dall'audience:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR**-PDND**/C015-servizioAccertamentoGeneralita/v1

**Comment by antoniopantocb** [comment]
grazie per l'aiuto così tempestivo, è un buon servizio

**Comment by amollicone1982** [comment]
quello non lo so. lo chiedo a voi.
se chiamate la url giusta ricevete sicuramente una risposta con codice http (404, 400) e un govway-id

**Comment by antoniopantocb** [comment]
abbiamo chiamato questa url
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002 
E' corretto?

**Comment by amollicone1982** [comment]
si è corretta

**Comment by antoniopantocb** [comment]
in POST con una curl

"curl -X 'POST' \
  'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer " . $voucher . "' \
  -H 'Agid-JWT-TrackingEvidence: " . $jwt . "' \
  -H 'Digest: SHA-256=" . $jwt_sha256 . "' \
  -H 'Content-Type: application/json' \
  -d '{
  \"idOperazioneClient\": \"00001\",
  \"criteriRicerca\": {
    \"codiceFiscale\": \"QRTSGT90A01H501B\"
  },
  \"datiRichiesta\": {
    \"dataRiferimentoRichiesta\": \"2023-09-19\",
    \"motivoRichiesta\": \"100-23\",
    \"casoUso\": \"C029\"
  }
}'
";


riceviamo:

Returned with status 60 and output: Array ( )

**Comment by amollicone1982** [comment]
non è un errore che restituiamo noi. siete sicuri di uscire dalla vostra rete?
il voucher lo ottenete correttamente da pdnd?

**Comment by antoniopantocb** [comment]
Si il voucher ci viene restituito correttamente, se serve lo posso mettere in chiaro (per mail?)

Come info: In ambiente di produzione l'id del messaggio di eerore veniva restituito da ANPR... Il codice è lo stesso (php)

**Comment by antoniopantocb** [comment]
potrebbe essere che noi abbiamo un TLS più alto del vostro?

**Comment by amollicone1982** [comment]
dovete mettere l'opzione -k

**Comment by antoniopantocb** [comment]
ci provo e ti aggiorno

**Comment by antoniopantocb** [comment]
giusto!

ora ritorna l'errore :D 
questo:

Checkresult: access_token
Expire_in: :600,
Returned with status 0 and output: Array ( [0] => {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"324b0088-56fb-11ee-870a-005056ae1884"} ) 

Fine processo

**Comment by amollicone1982** [comment]
manca il token Agid-JWT-Signature

**Comment by antoniopantocb** [comment]
ok 
che ha lo stesso contenuto di Agid-JWT-TrackingEvidence giusto?

**Comment by amollicone1982** [comment]
se leggete la guida vedrete che anche Agid-JWT-TrackingEvidence è fatto male

**Comment by antoniopantocb** [comment]
Certo le abbiamo lette:

un esempio:
POST https://api.erogatore.example/rest/service/v1/hello/echo/ HTTP/1.1 Accept: application/json
Autorization: Bearer AftgSSDGciFEEOiJfsI1NfsdfsdfiIsInR5c.vfd5... Agid-JWT-TrackingEvidence: eyJhbGciOiJSUzI1NiIsInR5c.vz8...
Digest: SHA-256=cFfTOCesrWTLVzxn8fmHl4AcrUs40Lv5D275FmAZ96E= Content-Type: application/json
{"testo": "Ciao mondo"}

Evidence contiene il JWT almeno sembra. Se non pjuoi al momento esserci di ulteriore aiuto leggeremo meglio, ma non sono fatte benissimo...

**Comment by amollicone1982** [comment]
nel Agid-JWT-TrackingEvidence inviato mancano sicuramente loa, userid, userlocation come indicato dalla guida

**Comment by antoniopantocb** [comment]
lo so, il problema è la frammentazione delle guide, è davvero oneroso mettere insieme tutto il materiale. Se ci si basa sulla piattaforma PDND e sugli esempi in piattaforma molto non viene detto o esemplificato...

Aggiungo e ti aggiorno 
grazie ancora intanto

**Comment by antoniopantocb** [comment]
Buongiorno,
abbiamo fatto i compiti e ora l'errore restituito è il seguente:

Checkresult: access_token
Expire_in: :600,
Returned with status 0 and output: Array ( [0] => {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"19003da5-57b4-11ee-983b-005056ae5232"} ) 

Fine processo


Ho dubbio sull'utilizzo di UTF8... se necessario anche in php...
volevo però capire il significato del govway_id restituito.

Grazie come sempre del prezioso aiuto
Antonio

**Comment by amollicone1982** [comment]
Questo è il payload del token integrity inviato da voi:
{
  "iss": "b37f56fb-ac24-43a9-95bb-c22d05a679fc",
  "sub": "b37f56fb-ac24-43a9-95bb-c22d05a679fc",
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C029-servizioAccertamentoDatiAnagrafici/v1",
  "purposeId": "56080e6b-b5ed-4c66-9f94-0f23b3ce96d4",
  "jti": "635f8c5f-5aa8-4bb7-97c1-79d8e186b6f9",
  "iat": 1695217107,
  "exp": ":600,",
  "signed_headers": {
    "digest": "N2VlODc5YTg0OGRjN2ZmMDA2NjA4ZTVmM2I4MWI4ZTNjODJlZDFiMWUxOTdiNjQ4ZjBkNWQwOTJjMjc2YTAyZQ==",
    "content-type": "application/json",
    "content-encoding": "UTF-8"
  }
}


Gli errori sono i seguenti:
Token con claim 'exp' non valido: Character : is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

Vi allego il payload di un token fatto bene:
"nbf": 1695218061,
  "exp": 1695218361,
  "jti": "377d4eef-57b5-11ee-ba10-005056ae0307",
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1",
  "client_id": "6bbb319b-dd52-4435-b619-f07b3dd8005a",
  "iss": "MUR-INTRA",
  "sub": "ANIS",
  "signed_headers": [
    {
      "digest": "SHA-256=l9R0KLIrHVR8lxPEFfCoecYYUypk7BUmI64hJykEg+c="
    },
    {
      "content-type": "application/json"
    }
  ]
}

**Comment by antoniopantocb** [comment]
grazie adesso sistemo
grazie 100 (top)

**Comment by amollicone1982** [comment]
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
Header HTTP 'content-encoding', dichiarato tra gli header firmati, non trovato nell'http header

**Comment by antoniopantocb** [comment]
"govway_id":"d4efe450-57c1-11ee-8298-005056ae1884"

forse è rimasto solo il problema del digest. Grazie per il calcolo. Calcolo il digest sul corpo della richiesta, fordse non è corretto... approfondisco (provo a calcolarlo per vedere se viene uguale a quello da te indicato) (top)

**Comment by afrontera85** [comment]
infatti  ora l'errore è solo "Header HTTP 'Digest' possiede un valore non corrispondente al messaggio"

**Comment by antoniopantocb** [comment]
buongiono afrontera85
corretto anche l'ultimo errore ma (aiuto!) questo il nuovo codice di errore:
"govway_id":"42d74658-584b-11ee-8d8c-005056ae1884"

**Comment by afrontera85** [comment]
Header HTTP 'Digest' presente in una richiesta con http payload vuoto

**Comment by antoniopantocb** [comment]
grazie intanto afrontera85
avevo dimenticato di aggiornare una variabile nel riscrivere il codice.
Ora però il codice di errore è il seguente:
"govway_id":"e4692ccb-5850-11ee-9bb9-005056ae5232"

Ma non esiste una tabella dei codici da consultare direttamente per fare il debug del codice?
Per forutna voi siete (top) molto efficienti ma consultare direttamente il bug permetterebbe una risoluzione dei problemi ancora più veloce

grazie ad ogni modo
Antonio

**Comment by afrontera85** [comment]
suppongo sia questo l'unico modo di procedere...poi il mio collega saprà rispondere meglio al riguardo
Intanto l'errore è:
Validazione security token ModI 'AUDIT' della richiesta fallita
Riscontrate 2 eccezioni.
[Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'userID'
[Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'userLocation'

**Comment by amollicone1982** [comment]
Questo è l'unico modo per evitare attacchi di information disclosure. L'idea è quella di mettere a disposizione a breve un client di esempio

**Comment by antoniopantocb** [comment]
Buongiorno amollicone
ok
La request è andata a buon fine, l'ultimo problema era una questione di lettere maiuscole e minuscole, quindi da rispettare nella stesura del nome dei claim. Riporto questo errore così a chi legge può tornare utile e non perdere tempo.

Grazie ancora di tutto (top)
