### ISSUE TITLE
Mancanza certificato di stato civile e altri certificati 

### ISSUE THREAD

**Issue by enzino237** [italia/anpr#4106]
Buongiorno,

Nel mio profilo ANPR è impossibile ottenere il certificato di stato civile. Gli unici certificati disponibili sono quelli di residenza e di stato di famiglia.

Tutti i miei dati sono corretti e ho anche provato a chiedere al mio comune e per loro sembra tutto in ordine.

Come posso risolvere?

**Comment by ncapozzi** [comment]
Buongiorno,
di solito quando sono disponibili solo i certificati di residenza e di stato di famiglia è perché in ANPR il Comune ha impostato la certificabilità parziale invece di quella completa sulla sua scheda. Le suggeriamo di chiedere al Comune di fare questa verifica.
