### ISSUE TITLE
WEB APP - Mancata stampa certificato

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#411]
Ambiente di Pre subentro  - Data test: 13/11/2017
Certificazione: Selezionato nel campo esenzione bollo/diritti di segreteria "altro motivo di esenzione" per il soggetto ID ANPR 4218032, descrizione esenzione bollo "testo libero", diritti di segreteria 0.26. Il sistema segnala OPERAZIONE CORRETTAMENTE ESEGUITA, ma non stampa il certificato e non contabilizza.

UFFICIO PROCEDURE INFORMATICHE - COMUNE DI TORINO

**Comment by gcarbonin** [comment]
Il certificato c'e' e riesco anche a stamparlo; ho provato anche a richiederlo e lo vedo anche nelle operazioni eseguite (utilita' e notifiche; certificati e carte d'identita'; periodo dal al (oggi), tipo documento = certificato).
Proviamo magari a sentirci telefonicamente o sulla posta privata
