### ISSUE TITLE
ANNULLAMMENTO DOPPIA ISCRIZIONE RIF issue #4070 

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#4114]
Buonasera si è presentato un altro caso uguale:
Il soggetto non può essere cancellato per doppia iscrizione perché non risultano due o più' posizioni in ANPR (Codice: EN509)

Informazioni sull'operazione da fornire in caso di assistenza : data 2023-09-21 16:37:48 , idOperazioneANPR 1446702517(Codice: EN527) 

grazie

_Originally posted by @rinonasti in https://github.com/italia/anpr/issues/4070#issuecomment-1729728937_

**Comment by amollicone1982** [comment]
Puo' riprovare adesso

**Comment by rinonasti** [comment]
OK RISOLTO
Grazie
