### ISSUE TITLE
Impossibile accedere ai cambi di residenza

### ISSUE THREAD

**Issue by katiavacchi** [italia/anpr#4117]
Buongiorno,
questa mattina è impossibile accedere ai cambi in Anpr. Allego schermata di errore. 
Capita anche ad  altri?
![Cattura](https://github.com/italia/anpr/assets/57749903/6c89be63-384c-4797-b595-f45bb2a17439)

Katia - Comune di Ravenna

**Comment by mttfranci** [comment]
@katiavacchi buongiorno, potreste riprovare? 
Dovrebbe essere la stessa anomalia della issue #4120

**Comment by katiavacchi** [comment]
Grazie!

**Comment by mttfranci** [comment]
Prego, buona giornata.

Assistenza ANPR
