### ISSUE TITLE
[6001] L'endpoint del servizio AnprService6001 deve avere il protocollo https

### ISSUE THREAD

**Issue by cloudify** [italia/anpr#412]
Leggendo le specifiche per il servizio di richiesta certificati, ho notato che l'indirizzo dell'endpoint per il servizio (`wsdlsoap:address`) ha il protocollo `http`, immagino sia un refuso e l'endpoint debba avere il protocollo `http`.

La definizione dell'endpoint è [qui](https://github.com/italia/anpr/blob/d03ffe8efc39b4b889cd797191cc2bbd075799d9/wsdl/wsdl6001/6001servizioCertificazione.wsdl#L38)

**Comment by rnapoli1983** [comment]
Buongiorno, il protocollo è https e l'hostname cambia secondo l'ambiente di riferimento in cui viene interrogato il servizio.

L'endpoint nel wsdl indicato è solo un riferimento fittizio.

Gli endpoint validi si trovano nella documentazione tecnica consultabile sul portale ANPR (www.anpr.interno.it)

**Comment by cloudify** [comment]
benissimo, grazie
