### ISSUE TITLE
RETTIFICA DATI - non funzionante

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#4120]
Buongiorno,
si segnala che da questa mattina non è possibile lavorare le richieste di rettifica dati da parte dei cittadini in quanto, al momento della selezione, il sistema espone il seguente messaggio "Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi"
Cordiali saluti
UpiTorino

**Comment by mttfranci** [comment]
Salve @UpiTorino  , potreste cortesemente riprovare?
(In caso potreste fornirci anche l'id di una richiesta di rettifica?)
Grazie in anticipo.
Saluti

**Comment by UpiTorino** [comment]
Confermiamo che il servizio è ora funzionante.
Grazie
Cordiali saluti
Silvia F.

**Comment by mttfranci** [comment]
Grazie a voi, buona giornata.
