### ISSUE TITLE
Integrazione come fruitore per il servizio PDND - C029

### ISSUE THREAD

**Issue by tbhole** [italia/anpr#4121]
Buongiorno,
stiamo cercando di integrarci come fruitori del servizio ANPR C029 per estrarre i dati anagrafici di una persona dato il codice fiscale.
Più che un bug si tratta di un debug per la risoluzione del problema di integrazione

Abbiamo implementato la richiesta con relativa cornice di sicurezza, tutto in ambiente di collaudo per il comune, ma otteniamo errori di integrazione.

Fruitore: Comune di Ripalta Cremasca (c_h315)
Piattaforma: PDND - C029
Ambiente: Collaudo
Data del test: 2023-09-25
Orario: intorno alle 12:25:50,554
Operatore dei test: Amministratore

Abbiamo appena effettuato un test di integrazione per richiedere i dati di un caso d'uso di test e la risposta ottenuta è la seguente:
{
"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
"title": "InteroperabilityInvalidRequest",
"status": 400,
"detail": "Received request is not conform to the required interoperability profile",
"govway_id": "57384f2f-5b85-11ee-abbf-005056ae5232"
}

Se si riuscisse a capire dove sta il problema, poichè dal messaggio restituito non riesco a determinare dove e come intervenire.

Grazie.
Buona giornata.

**Comment by tbhole** [comment]
Buongiorno,
siamo riusciti a concludere ugualmente l'integrazione.
Non abbiamo necessità del supporto.

Grazie.
Buona giornata.

**Comment by paoloveggi** [comment]
Buongiorno,
anche noi abbiamo lo stesso problema, ma non riusciamo a risolvere. E' possibile sapere come siete intervenuti? Grazie.

**Comment by tbhole** [comment]
Salve Paolo,
si che si può sapere, ho fatto diverse prove ma soprattutto organizzato una call con qualcuno che avesse già ottenuto supporto  diretto da ANPR.
Mi rendo conto che questo è di poco aiuto, però posso riassumere l'iter di integrazione (con qualche esempio pratico):

1. calcolo un JWT per il tracking (naturalmente va firmato con il certificato client depositato), aud e purposeId sono relativi alla finalità, iss = clientId:
`{
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1",
  "nbf": 1698238239,
  "iss": "...",
  "purposeId": "22fd2db0-009d-44ae-87ea-55d516c961a7",
  "userLocation": "...",
  "exp": 1700830239,
  "iat": 1698238239,
  "dnonce": "2335096980498",
  "userID": "...",
  "jti": "b41c3898-e094-45fe-b7d3-aa78f595d333",
  "LoA": "..."
}`
2. di questo token una volta formato va fatto sha256 + hex;
3. quindi devo creare l'asserzione per richiedere l'access_token, qualcosa di simile, iss = sub = clientId, puposeId = finalità, mentre il value all'interno del digest mi rappresenta l'sha256 + hex del token precedente:
`{
  "sub": "...",
  "aud": "auth.uat.interop.pagopa.it/client-assertion",
  "nbf": 1698238239,
  "iss": "...",
  "purposeId": "22fd2db0-009d-44ae-87ea-55d516c961a7",
  "digest": {
    "alg": "SHA256",
    "value": "a99807be47b0639925a7f75b922f14fe2096238418bce9714efd132177369871"
  },
  "exp": 1700830239,
  "iat": 1698238239,
  "jti": "b41c3898-e094-45fe-b7d3-aa78f595d333"
}`
4. a questo punto dovreste ottenere il vaucher che vi serve per la chiamata, dovete estrarre dal vaucher l'access_token;
5. ora serve un altro token JWT che garantisca la veridicità del body, qualcosa di simile sub = iss = clientId, purposeId = finalità:
`{
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1",
  "sub": "...",
  "nbf": 1698238239,
  "iss": "...",
  "purposeId": "22fd2db0-009d-44ae-87ea-55d516c961a7",
  "signed_headers": [
    {
      "Digest": "SHA-256=nS2T22UI+VR6xXjLgOADMrL8SDFtGJDGaiiKv04SIPQ="
    },
    {
      "Content-Encoding": "UTF-8"
    },
    {
      "Content-Type": "application/json"
    }
  ],
  "exp": 1700830239,
  "iat": 1698238239,
  "jti": "b41c3898-e094-45fe-b7d3-aa78f595d333"
}`
6. prestate attenzione ai claims signed_headers  è n vettore di elementi chiave: valore, ciò che mettete negli header della chiamata post successiva dovete dichiaralo come firmato, il Digest corrisponde allo sha256 del body (attenzione non hex).
7. questo un esempio di body:
`{
	"idOperazioneClient": "12",
	"criteriRicerca": {
		"codiceFiscale": "HBRCST62S11Z112Q"
	},
	"datiRichiesta": {
		"dataRiferimentoRichiesta": "2023-10-25",
		"motivoRichiesta": "...",
		"casoUso": "C020"
	}
}` 
8. quindi effettuate la POST con i parametri copra calcolati:
`
Digest: SHA-256=nS2T22UI+VR6xXjLgOADMrL8SDFtGJDGaiiKv04SIPQ=
Content-Encoding: UTF-8
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOi... = **access token restituito da PDND**
Agid-JWT-Signature: eyJraWQiOi... = **token JWT generato all'ultimo punto 5**
Agid-JWT-TrackingEvidence: eyJraWQiOi... = **token JWT generato al punto 1**
`
9. di seguito la risposta ottenuta:
`
{
	"idOperazioneANPR": "59042643",
	"listaSoggetti": {
		"datiSoggetto": [
			{
				"generalita": {
					"idSchedaSoggettoANPR": "655669",
					"codiceFiscale": {
						"codFiscale": "HBRCST62S11Z112Q",
						"dataAttribuzioneValidita": "2016-10-21",
						"validitaCF": "1"
					},
					"cognome": "H�?BERTR�?UME",
					"nome": "C�?LESTIN",
					"sesso": "M",
					"dataNascita": "1962-11-11",
					"luogoNascita": {
						"localita": {
							"codiceStato": "216",
							"descrizioneLocalita": "STUTTGART",
							"descrizioneStato": "GERMANIA"
						}
					}
				},
				"identificativi": {
					"idANPR": "YJ88856A3"
				},
				"residenza": [
					{
						"dataDecorrenzaResidenza": "2016-10-21",
						"tipoIndirizzo": "1",
						"indirizzo": {
							"cap": "00666",
							"comune": {
								"codiceIstat": "036030",
								"nomeComune": "PAVULLO NEL FRIGNANO",
								"siglaProvinciaIstat": "MO"
							},
							"toponimo": {
								"denominazioneToponimo": "SORDI",
								"specie": "GALLERIA",
								"specieFonte": "1"
							},
							"numeroCivico": {
								"numero": "45",
								"civicoInterno": {
									"scalaEsterna": "A"
								}
							}
						}
					}
				]
			}
		]
	}
}
`

Questo è tutto spero vi possa essere di aiuto.
Buona serata.

**Comment by paoloveggi** [comment]
Ciao, ti ringrazio per l'esempio. Quello che non capiamo è come
implementare la cornice di sicurezza relativa a INTEGRITY_REST_02 e
AUDIT_REST_02 dato che sul portale PDND arriviamo correttamente
all'ottenimento dell'access token e quando proviamo a generare una chiamata
API al service C029 utilizzando Postman e il file yaml del service
scaricato da PDND questa cornice non viene menzionata. Avete per caso a
disposizione un esempio di implementazione con codice, tipo PHP o chiamata
CURL?

Ancora grazie del supporto.

Il giorno mer 25 ott 2023 alle ore 15:20 sth0r ***@***.***>
ha scritto:

**Comment by tbhole** [comment]
Ciao,
quello che serve è al punto 1 ed al punto 8, ed è molto importante rispettare la sintassi.
La mia implementazione è basata su java, ma questo non dovrebbe essere un problema, gli esempi che ho postato sono funzionanti, e lo si può vedere dalla risposta, se rispettate i dati post all'interno dei vari json dovreste riuscire a passare.
Il token/vaucher che viene restituito è valido anche senza la cornice di sicurezza però purtroppo non permette l'accesso.
E' essenziale inserire all'interno del token di richiesta del vaucher il digest del primo JWT (punto 1), lo stesso JWT va posto poi nella chiamata POST nell'header Agid-JWT-TrackingEvidence (dovrebbe essere AUDIT_REST_02) mentre l'ultimo JWT, punto 8 inserito all'intero dell'header Agid-JWT-Signature (dovrebbe essere INTEGRITY_REST_02) a garanzia dell'integrità del body.

Ciao.
