### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio ANPR

### ISSUE THREAD

**Issue by Mauricio-Nazario** [italia/anpr#4123]
Gentili signori

Non riesco ad accedere il sito ANPR - appare questo messaggio di errore: "Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Non ci sono problemi con la mia scheda anagrafica

Mauricio Nazario do Carmo Sant' Anna
Nato in Brasile
Codice Fiscale:NZRMRC

![Screenshot_2023-09-19-06-53-34-671_com android chrome](https://github.com/italia/anpr/assets/69878847/a3197413-fd83-4672-aad6-a87fae5bca1e)

**Comment by scasasilvia** [comment]
Ciao @Mauricio-Nazario ho lo stesso problema. Sei riuscito a risolvere?
Grazie!

**Comment by Mauricio-Nazario** [comment]
> Ciao @Mauricio-Nazario ho lo stesso problema. Sei riuscito a risolvere? Grazie!

Ciao, non sono riuscito a risolverlo

**Comment by Mauricio-Nazario** [comment]
Cia @scasasilvia  non sono riuscito a risolverlo

**Comment by Mauricio-Nazario** [comment]
@scasasilvia 
![Screenshot_2023-10-17-07-22-43-154_com android chrome](https://github.com/italia/anpr/assets/69878847/bf87d5f0-e401-478d-b474-c03fd79f32ac)

**Comment by ncapozzi** [comment]
Buonasera,
come suggerito nel messaggio di errore, deve rivolgersi al suo comune di residenza (o di iscrizione all'AIRE) per verificare se i sui dati sono correttamente registrati nella sua scheda anagrafica.

**Comment by Mauricio-Nazario** [comment]
@ncapozzi 
Ho contattato il comune il 25/09/2023 e mi hanno risposto che era tutto in regola con la registrazione

**Comment by Mauricio-Nazario** [comment]
@ncapozzi Non ci sono problemi con la mia scheda anagrafica
