### ISSUE TITLE
Mancato caricamento dati elettorali Sezione 1

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#4128]
Buongiorno,

in data 23 giugno scorso sono state portate a termine le attività necessarie per il subentro dei dati elettorali del comune 090018.

In fase di caricamento dei due file xml non sono state evidenziate anomalie e non sono visibili anomalie all'interno delle funzionalità di download file.

Tuttavia consultando i dati notiamo come sembrino mancare tuti i dati elettorali dei cittadini iscritti nella sezione elettorale numero 1.

Riporto due id scheda soggetto ANPR DI esempio: 64183709,64183709

E' già stata contattata la Vs. assistenza telefonica con ticket numero 03029760 senza risolvere.

Potete darci un gentile riscontro?

Grazie

Roberta Biasi
Deda Next – Sede di Trento, Via di Spini 50

**Comment by amollicone1982** [comment]
La problematica è stata dovuta al fatto che avete inserito due volte lo stesso file delle sezioni che ha determinato un bug lato nostro (cosa non piu' possibile adesso).

Come soluzione potremmo cancellare il file degli elettori inserito e farvene caricare uno nuovo. Potreste rinviare anche lo stesso

Per voi va bene?

**Comment by amollicone1982** [comment]
Fatto. Quando volete potete procedere.

Grazie per la collaborazione

**Comment by amollicone1982** [comment]
CAricamento finito, naturalmente vi ritrovate degli errori relativi ai caricamenti già fatti per la sezione 2
