### ISSUE TITLE
CERTIFICAZIONI  OPZIONE ALTRO CERTIFICATO

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#413]
Buongiorno
segnalo che utilizzando l'opzione "Altro certificato" il sistema ripropone i campi di "dati del certificato" compilati con la precedente richiesta. Sarebbe opportuno che fossero ripuliti.
Grazie
Saluti
Ufficio Procedure Informatiche- Comune Torino

**Comment by gcarbonin** [comment]
La cosa è voluta: questa opzione riguarda un altro certificato per la stessa persona; i dati precedenti vengono quindi mantenuti. per azzerare tutto occorre  cliccare su certificazione che compare in alto a sinistra

![image](https://user-images.githubusercontent.com/25685981/32784848-3eeee6de-c950-11e7-9115-1f1d7373645f.png)

**Comment by UpiTorino** [comment]
ma così si allungano i tempi....
se ho già i dati del soggetto perchè reinserirli ogni volta...
  ----- Original Message -----

**Comment by gcarbonin** [comment]
Se devo emettere un altro certificato PER LA STESSA PERSONA clicco su altro certificato; se la persona è un'altra, clicco su CERTIFICAZIONE
