### ISSUE TITLE
LISTE ELETTORALI - AGGIORNAMENTI

### ISSUE THREAD

**Issue by frmariani** [italia/anpr#4143]
Nell'area Liste elettorali sono disponibili i seguenti aggiornamenti

**LEVA ELETTORALE**
Contrariamente a quanto precedentemente comunicato, per la leva elettorale si deve inviare l’attributo elettore come segue 
Elettore=S 
Per questa tipologia di elettori sarà inibita la certificazione elettorale fino al compimento del 18 anno di età.
**INTERDETTI**
Per i cittadini con ostative, sarà possibile inviare il dato come segue
Elettore=N 
Non sarà necessario inviare i dati di una lista e quindi i dati della sezione; sarà altresì necessario inviare a "NO" tutti i restanti dati accessori. 
**CERTIFICATI ELETTORALI**
Nel WS 6001 è stato inserito il flag tipoFirmaElettorale
1= incaricato del sindaco; sarà possibile indicare il nome ed il cognome dell’incaricato
2= Vice Sindaco (si intende quello pro tempore)
3= Sindaco (si intende quello pro tempore)
Se non viene inserito alcun flag i certificati saranno emessi a firma del Sindaco.

**Comment by Ennio71** [comment]
@frmariani dove trovi i wsdl aggiornati?

**Comment by RBiasi** [comment]
Buongiorno, vorrei segnalare che nella copia del certificato per la verifica a cui si arriva dal qrcode la firma è sempre il SINDACO indipendentemente che si sia stato valorizzato il flag tipoFirmaElettorale con i valori 1,2 o 3.

Grazie

**Comment by amollicone1982** [comment]
Ci dice ambiente e idoperazione?

**Comment by amollicone1982** [comment]
mi puo' dire l'idoperazione che ha generato il certificato a seguito della quale avete fatto la verifica qrcode?
