### ISSUE TITLE
Doppia Iscrizione - errore EN509

### ISSUE THREAD

**Issue by SamueleBerruti** [italia/anpr#4148]
Buongiorno, faccio questa segnalazione per il Comune di Bormida (SV).
Non riusciamo ad cancellare da AIRE un cittadino con doppia iscrizione (la cancellazione deve avvenire nel nostro Comune e non nell'altro (Brescia)).
Quando proviamo ad eseguire (da Gestionale Siscom) la cancellazione per doppia iscrizione ci viene restituito l'errore EN509 - "Il soggetto non puo' essere cancellato per doppia iscrizione perche' non risultano due o piu' posizioni in ANPR".
Se però effettuo una ricerca per codice fiscale in ANPR vengono trovati DUE cittadini.
Potete darmi indicazioni?
Codice ANPR cittadino da cancellare:125151908
Codice famiglie ANPR cittadino da cancellare:74289990

In attesa di cortese riscontro auguro una buona giornata.
Grazie
Samuele

**Comment by amollicone1982** [comment]
Puo' rirpovare adesso
