### ISSUE TITLE
Nuovo servizio 5014  e nuova versione del servizio 1014 

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#415]
Dal prossimo 16 novembre,  sara’  disponibile  in ambiente di test-comuni e pre-subentro il servizio 5014 che consente la rettifica della data di decorrenza della residenza e del motivo di iscrizione anche in modalita’ WS. Sara’ disponibile, inoltre, una nuova versione del servizio 1014 che consente di collegare piu’ soggetti allo stesso procedimento o di rimuovere il collegamento in precedenza trasmesso.  Entrambe le funzionalità (rettifica e collegamento di piu’ soggetti al procedimento) sono attualmente disponibili esclusivamente nella WA. Si allega un estratto della documentazione aggiornata che sarà pubblicata nei prossimi giorni su www.anpr.interno.it. Per consentire gli aggiornament SWi (compresi quelli relativi ai certificati vedi issue 407), l’ambiente di test comuni non sarà disponibile a partire dalle ore 14 di domani 16 novembre per circa un’ora; a seguire, si aggiornera’ l’ambiente di pre-subentro.

**Comment by gcarbonin** [comment]
[MODIFICHE 15 NOVEMBRE.zip](https://github.com/italia/anpr/files/1474882/MODIFICHE.15.NOVEMBRE.zip)

**Comment by busaster** [comment]
Buongiorno,

le modifiche sopra descritte (in particolare quelle al servizio 1014) sono ad oggi disponibili in ambiente di Produzione ?

Grazie

**Comment by busaster** [comment]
Non ho avuto risposta al mio quesito e la issue è stata chiusa, probabilmente per errore
Potete per favore farmi sapere ?

Grazie

**Comment by rvinzani** [comment]
Salve, il servizio 5014 e la versione aggiornata del 1014 sono attualmente disponibili in ambiente di produzione
