### ISSUE TITLE
Informazioni tecniche su servizio C001–servizioNotifica-approvazione_automatica

### ISSUE THREAD

**Issue by AdamoRiccardo** [italia/anpr#4152]
Buongiorno,

stiamo implementando l’interfacciamento con il servizio C001–servizioNotifica-approvazione_automatica inserendo nel header il token ricevuto da PDND.

Il servizio prevede però anche queste informazioni: Agid-JWT-Signature e Agid-JWT-TrackingEvidence di cui non abbiamo esattamente capito quale JWS inserire pur seguendo la guida https://github.com/italia/anpr/files/11906748/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf

Qualcuno sa dettagliarci esattamente quali JWS vengono richiesti? Sono recuperabili dalla risposta ottenuta da PDND in fase di creazione del voucher?

Grazie.

**Comment by afrontera85** [comment]
Buongiorno, 
se non avete ancora risolto, quì trovate un esempio di client che implementa i profili di cui Anpr necessita:
#https://github.com/italia/anpr/issues/3964
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties.
Per eventuali dettagli su errori presi basta che ci forniate il govway_id e verifichiamo tranquillamente
