### ISSUE TITLE
Sezione elettorale in territorio di diverso Comune

### ISSUE THREAD

**Issue by migmar68** [italia/anpr#4157]
Buongiorno
Abbiamo trovato almeno un caso - Comune di Monteriggioni - in cui una sezione elettorale (la 4) è fisicamente ubicata presso una scuola del Comune adiacente (Castelnuovo Berardenga). Questo è dovuto al fatto che la frazione è condivisa tra i due comuni.
Ma immagino che potrebbero esserci altri casi in altri comuni, oppure che possa capitare in modo sporadico a causa di inabigilità temporanee.
Al momento ANPR non accetta questa situazione, e quindi ha dato errore sul caricamento della sezione 4:  EN378 Il comune di residenza deve coincidere con il comune di competenza. Di conseguenza non vengono considerati i 700 elettori assegnati alla sezione 4.
Richiediamo di trasformare il controllo EN378 in semplice segnalazione non bloccante.
Grazie, Marco Migliori

**Comment by amollicone1982** [comment]
Faccio un riassunto, il comune di monterigioni al subentro delle sezioni ha inviato 11 sezioni dalla 2 alla 12 ma la sezione numero 4 ha preso un errore bloccante e per tale motivo non inserita. Successivamente con 5011 sono stati inserite le sezioni 1 e 4.
In particolare la numero 4 al momento ci risulta ubicata in VIA TARANTELLI 1 nel comune di Monterigioni ed al momento non ci sono elettori di monteriggioni associati a tale sezione.

Il comune di castelnuovo ha 1771nella sezione 4. Di questi 729 inseriti con il subentro di monteriggioni in quanto al subentro è stato passato per questi 729 soggetti la sezione 4 del comune di catelnuovo.

Dai requisiti dateci dal ministero non era prevista una cosa simile. Per tale motivo ci dobbiamo muovere nel senso di chiedere al ministero se una sezione di un comune puo' stare in un indirizzo appartenente ad un'altro.
Seconda cosa, se ci inviate una pec, sanare queste 729 posizioni assegnandole alla sezione 4 del comune di monteriggioni (che ricordo ha come indirizzo VIA TARANTELLI 1 nel comune di Monterigioni)

Buona giornata

**Comment by amollicone1982** [comment]
Aggiungo che da un punto di vista anagrafico, nel subentro di monteriggioni in anpr, VIA TARANTELLI 1 è attribuita al comune di Monterigioni e non castelnuovo berardenga.

**Comment by amollicone1982** [comment]
Ho fatto l'aggiornamento richiesto via pec.
I 729 soggetti in questo momento sono associati alla sezione 4 di monteriggioni presente all'indirizzo VIA TARANTELLI 1 nel comune di Monterigioni.
Il ministero ci ha appena confermato che la vostra casistica è possibile. Immagino che l'indirizzo della sezione sia sbagliato.
Se mi date l'indirizzo corretto lo aggiorno

**Comment by migmar68** [comment]
Grazie.
L'indirizzo della sezione 4 comunicato dal Comune di Monteriggioni è:
VIA EZIO TARANTELLI, 1 - COMUNE DI CASTELNUOVO BERARDENGA

**Comment by amollicone1982** [comment]
Aggiornamento effettuato
