### ISSUE TITLE
Errore Rettifica atto di morte

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#4161]
Buongiorno

abbiamo utilizzato la webapp di TEST-COMUNI per rettificare un atto di morte inserendo l'atto digitale, ma alla conferma viene restituito errore **"Atto - Il campo Nome comune è obbligatorio"**, anche se i dati sono tutti presenti . 

![image](https://github.com/italia/anpr/assets/25926460/e97d4f8d-ce5c-4cb3-99a3-74cd987f724e)

Abbiamo quindi provato una registrazione di morte con atto digitale e anche in questo caso non va a buon fine, ma perché il Nome comune dell'evento viene "perso" dopo la CONFERMA
 
![image](https://github.com/italia/anpr/assets/25926460/0b9403b3-4364-491d-bc9e-5655b8ba200d)

Potreste verificare e farci sapere qualcosa? Grazie

_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by ANPRCdMI** [comment]
Buongiorno

scusate se sollecito questa segnalazione, ma stiamo sviluppando le funzioni di integrazione, e abbiamo necessità di avere posizioni con il nuovo formato di atto, potreste darci indicazioni al riguardo?
Grazie

Saluti
_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by mttfranci** [comment]
@ANPRCdMI ci scusiamo per il ritardo nella risposta, potreste riprovare?
Grazie in anticipo.

Saluti

**Comment by ANPRCdMI** [comment]
Buongiorno
abbiamo effettuato la prova e la rettifica dell'atto è stata eseguita correttamente.
Grazie

Saluti

**Comment by mttfranci** [comment]
Perfetto. Grazie del riscontro.

Saluti

Assistenza ANPR
