### ISSUE TITLE
EC034 - Codice consolato di residenza 2670100 incongruente con la descrizione

### ISSUE THREAD

**Issue by anprpa** [italia/anpr#4162]
Mutazione dati AIRE - modifica della residenza dall'Italia all'estero.

Riceviamo questo errore:
EC034 - Codice consolato di residenza 2670100 incongruente con la descrizione
EN527 - Informazioni sull'operazione da fornire in caso di assistenza : data 2023-10-09 11:52:20 , idOperazioneANPR 1467945778

Allego la parte della richiesta xml relativa alla residenza estera:

    <residenzaEstera>
        <tipoIndirizzo>4</tipoIndirizzo>
        <localitaEstera>
            <indirizzoEstero>
                <cap>70403</cap>
                <localita>
                    <descrizioneLocalita>PUERTO VIEJO DE TALAMANCA</descrizioneLocalita>
                    <descrizioneStato>COSTA RICA</descrizioneStato>
                    <codiceStato>513</codiceStato>
                </localita>
                <toponimo>
                    <denominazione>EL JARDIN DE PLAYA NEGRA CALLE EL JARDINCALLE EL JARDIN</denominazione>
                </toponimo>
            </indirizzoEstero>
            <consolato>
                <codiceConsolato>2670100</codiceConsolato>
                <descrizioneConsolato>SAN JOSE' DE COSTARICA</descrizioneConsolato>
            </consolato>
        </localitaEstera>
        <dataDecorrenzaResidenza>2023-09-27</dataDecorrenzaResidenza>
    </residenzaEstera>

Ivana Ragni - SISPI - Comune di Palermo

**Comment by ncapozzi** [comment]
Buongiorno,
la denominazione corretta del Consolato è SAN JOSE' DE COSTA RICA.
https://www.anpr.interno.it/area-tecnica/tabelle-di-decodifica/
