### ISSUE TITLE
Anomalia risoluzione doppie iscrizioni

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4167]
Buongiorno,
il comune 082036 non ha la prima spunta per procedere alla richiesta del contributo per il subentro delle liste elettorali.
Abbiamo scaricato il file l'elenco delle doppie iscrizioni, ha un solo individuo.
La copia errata dell'individuo la deve cancellare il comune 082036 e quindi abbiamo provato a farlo, ma riceviamo degli errori:

- **Il soggetto non puo' essere cancellato per doppia iscrizione perche' non risultano due o piu' posizioni in ANPR (Codice: EN509)
- Informazioni sull'operazione da fornire in caso di assistenza : data 2023-10-13 09:41:48 , idOperazioneANPR 1474433232 (Codice: EN527)**

Sembra che per il sistema di controllo delle spunte del subentro ci sia una persona da risolvere, ma per il sistema di cancellazione per doppia iscrizione no.

Potete verificare? Grazie

**Comment by amollicone1982** [comment]
Puo riprovare adesso

**Comment by SAlberto** [comment]
Siamo riusciti, grazie molte
