### ISSUE TITLE
Problemi con il cambio di residenza

### ISSUE THREAD

**Issue by Mash80** [italia/anpr#4169]
Buongiorno,
sto provando a completare la procedura di cambio residenza sul portale dell'anagrafe di stato dal comune di San Giuliano Milanese a quello di Napoli. Non appena provo a fare accesso con SPID  al portale, appare questo messaggio di errore.

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Potreste darmi supporto per risolvere il problema?

Grazie
Giancarlo

**Comment by ncapozzi** [comment]
Buonasera,
come suggerito nel messaggio di errore, deve rivolgersi al suo comune di residenza (o di iscrizione all'AIRE) per verificare se i sui dati sono correttamente registrati nella sua scheda anagrafica.

Assistenza ANPR
