### ISSUE TITLE
ws [1013] - Integrazione dei ws ANPR con AE

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#417]
Salve,
per completare i test di integrazione dei ws di ANPR con i servizi cooperativi di AE in ambiente di test, stiamo effettuando delle richieste di annullamento di un codice fiscale in precedenza attribuito.
Abbiamo pertanto effettuato delle registrazioni di nuove posizioni in ANPR, iscrivendo alcuni individui con il WS 1002 e richiedendo con successo l'attribuzione di un codice fiscale; nei minuti successivi, quindi all'interno della finestra di 24 ore valida per effettuare l'operazione, abbiamo provato a richiedere l'annullamento dei codici fiscali tramite il WS 1013, indicando come da specifiche nel campo annullamentoAttribuzione il valore “S”, ma otteniamo in risposta il messaggio "operazione non effettuabile". C'è un errore nei dati inviati, o è l'ambiente di test che non consente questo tipo di operazione?
Potete verificare al proposito le request con id operazione comune 2879 e 2927

Il test è stato effettuato in data 16/11/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Stiamo verificando

**Comment by rvinzani** [comment]
Si è trattato di un problema temporaneo nella risposta dei servizi dell'Agenzia delle Entrate. Il problema è stato rimosso. E' possibile riprovare.

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo appena effettuato una prova di registrazione di una nuova posizione in ANPR mediante il servizio 1002, richiedendo l'attribuzione del codice fiscale (in modo da poter successivamente procedere alla prova di annullamento del codice fiscale), ma al momento otteniamo in risposta il messaggio "operazione non effettuabile" anche su tale operazione di registrazione, per cui non abbiamo potuto testare la situazione segnalata nell'issue. 
Ci sono ancora problemi con i servizi di AE? in ogni caso più tardi effettueremo un nuovo tentativo.
L'id operazione comune è 2980, il test è stato effettuato oggi 21/11/2017, in ambiente di test, per il comune pilota Teramo.

**Comment by rvinzani** [comment]
Stesso problema presentatosi con gli annullamenti. Potete riprovare ad effettuare nuovamente l'iscrizione con la richiesta di attribuzione del codice fiscale. Restiamo in attesa dell'esito dell'operazione. Saluti

**Comment by Amucciarelli74** [comment]
Abbiamo appena ripetuto il test e l'esito è stato positivo. Dopo la registrazione, abbiamo effettuato anche la richiesta di annullamento del codice fiscale e l'operazione è andata a buon fine; a una successiva consultazione infatti i codici fiscali assegnati in precedenza risultano non presenti in ANPR.
Grazie, cordiali saluti.
