### ISSUE TITLE
Problemi certificato contestuale

### ISSUE THREAD

**Issue by MaksymVerstyuk** [italia/anpr#4174]
Buonasera!
Ho provato a richiedere il certificato contestuale online a pagamento sul sito dell'ANPR tre volte, ma non mi è mai arrivato niente. 
Sul sito dell'ANPR, nella sezione "CERTIFICATI" non c'è una sezione dei certificati rilasciati, me lo fa richiedere di nuovo e basta, senza mai farli arrivare.
Ho pagato il bollo tre volte e non mi è mai arrivato nulla.
Come posso risolvere il problema?
Grazie

**Comment by gppbarone** [comment]
Buongiorno,
dopo aver richiesto un certificato con il pagamento del relativo bollo sul portale ANPR, se non si riesce a scaricare il certificato richiesto oppure non lo si è ricevuto per email, si suggerisce di verificare quanto segue:

- che il pagamento del bollo tramite pagopa sia stato effettivamente attestato e contabilizzato (si riceve una email da PagoPA)

- che lo stato del pagamento sulla lista dei certificati richiesti sia PAGATO. Se lo stato è PAGAMENTO IN ELABORAZIONE, è necessario aggiornare lo stato cliccando sulla prima iconcina da sinistra ![image](https://github.com/italia/anpr/assets/88545753/4c1635ec-b6ab-448e-88f3-a948654e4482) presente nella colonna Azioni

**ATTENZIONE**: se è stata già fatta una richiesta per lo stesso tipo di certificato, che risulta nello stato "**PAGAMENTO IN ELABORAZIONE**" , PRIMA DI EFFETTUARE UNA NUOVA RICHIESTA aggiornare lo stato di quella già fatta come sopra indicato.

Assistenza ANPR
