### ISSUE TITLE
PermessoSoggiorno.xlsx - Dati Passaporto

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#418]
Buongiorno Comune di Cortina d'Ampezzo produzione

Volendo compilare i dati riferiti al Passaporto nel documento in oggetto viene indicato che il campo TipoSoggiorno è obbligatorio tuttavia nei valori possibili (Tabella 8 tipo soggiorno) cosa selezionare tra i valori possibili?

1 | Permesso
2 | Carta di soggiorno / Permesso di soggiorno CE
3 | Attestazione a carattere permanente
4 | Attestazione di regolarità
5 | Ricevuta
6 | Rinnovo in corso
9 | Non conosciuto/non fornito
8 | Altro titolo di soggiorno
7 | Senza permesso

Grazie

**Comment by gcarbonin** [comment]
Domanda: il passaporto è un documento di riconoscimento . In quali casi si sostituisce il titolo di soggiorno?

**Comment by SaraValleferro** [comment]
Buongiorno, rispondo direttamente io Sara Valleferro, responsabile ufficio anagrafe Comune di Cortina d'Ampezzo.
Il caso accaduto riguarda l'iserimento del passaporto di una minore adottata, per la quale non era stato rilasciato permesso di soggiorno, ma solamente autorizzazione all'ingresso e residenza nel territorio italiano ai fini adozione rilasciata dalla Presidenza dei Consiglio dei Ministri. 
Altro caso in cui si iscrive solo sulla base del passaporto è quando si iscrive al fine di ottenere la cittadinanza iure sanguinis, per la quale basta il timbro area Shengen o dichiarazione di presenza e pertanto il passaporto sostituisce momentaneamente il permesso di soggiorno.
Cordiali Saluti
Grazie
Sara Valleferro

**Comment by gcarbonin** [comment]
Grazie. Direi di mettere o 7 o 8
