### ISSUE TITLE
Subentro dati elettorale - errore EN378

### ISSUE THREAD

**Issue by pscioscia** [italia/anpr#4186]
Buongiorno.
Abbiamo fatto il subentro per il comune di Castronuovo di Sant'Andrea, codice ISTAT 076026, il 13 ottobre.
Il sistema ha restituito, per le sezioni, l'errore EN378 - Il comune di residenza deve coincidere con il comune di competenza e ha rigettato tutti gli elettori.
Analizzando l'xml delle sezioni abbiamo notato che la descrizione del comune è CASTRONUOVO DI SANT' ANDREA.
E' forse lo spazio dopo l'apostrofo la causa?
Sarebbe possibile cancellare i file per procedere con un nuovo caricamento?

Grazie

**Comment by amollicone1982** [comment]
Il problema è quello. le ho cancellato i file

**Comment by pscioscia** [comment]
Grazie.
Buon fine settimana.


Il giorno mer 25 ott 2023 alle ore 18:32 amollicone1982 <
***@***.***> ha scritto:
