### ISSUE TITLE
[PDND C029] Errore di comunicazione con e-Service PDND C029-servizioAccertamentoDatiAnagrafici-approvazione_automatica

### ISSUE THREAD

**Issue by riccafi** [italia/anpr#4187]
**PDND, Ambiente di Collaudo, C029**
Abbiamo provveduto ad implementare i pattern di sicurezza richiesti INTEGRITY_REST_02 e AUDIT_REST_02 per l'e-service di PDND C029-servizioAccertamentoDatiAnagrafici-approvazione_automatica, descritti qui: [Agid](https://github.com/italia/anpr/files/11906748/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf)
Stiamo effettuando delle prove di comunicazione con l'e-service, ma abbiamo bisogno di avere delle informazioni aggiuntive sulla tipologia di errore prodotto.  

L'errore ottenuto con l'ultimo test è il seguente:

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "9ef5beea-7241-11ee-83ab-005056ae1884"
}
```

Potete indicarci che tipo di errore si è verificato e così permetterci di sistemare la comunicazione?

**Fruitore**: Comune di Firenze
**Piattaforma**: PDND
**Ambiente**: Collaudo
**Data del test**: 2023/10/24
**Orario**: intorno alle 10.35

**Comment by riccafi** [comment]
Buonasera, 

abbiamo fatto un nuovo tentativo modificando il valore di `idOperazioneClient`  che era un alfanumerico e abbiamo inserito un solo valore numerico.

Adesso otteniamo un errore diverso:

```
{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "3f7e3e2d65391cd5251a15cd"
} 

```
**Fruitore**: Comune di Firenze
**Piattaforma**: PDND
**Ambiente**: Collaudo
**Data del test**: 2023/10/25
**Orario**: intorno alle 15.48

**Comment by paoloveggi** [comment]
Buongiorno, mi accodo alla segnalazione evidenziando lo stesso identico problema per lo stesso e-service. Abbiamo provveduto anche noi ad implementare i pattern di sicurezza richiesti INTEGRITY_REST_02 e AUDIT_REST_02 per l'e-service, ma otteniamo in risposta lo stesso errore segnalato dall'utente @riccafi

`(
    [type] => https://govway.org/handling-errors/404/NotFound.html
    [title] => NotFound
    [status] => 404
    [detail] => Unknown API Request
    [X-Global-Transaction-ID] => 3f7e3e2d653bc2f32733038d
)
`

Test effetuato il 27/10/2023 alle ore 16 circa, ambiente di collaudo.

Potete aiutarci a debuggare?

**Comment by paoloveggi** [comment]
Buongiorno, nessuno del supporto riesce a dare assistenza? Ci sono altri canali per ricevere supporto? Grazie.

**Comment by riccafi** [comment]
Non abbiamo ricevuto ancora una risposta a riguardo.   
Nel mentre abbiamo risolto il problema, ma senza sapere di preciso cosa abbiamo corretto.

**Comment by riccafi** [comment]
Il codice seguente in Golang era funzionante per il c020 ma non per il c029.
E' in Golang e aiuta nella generazione del digest da usare per la generazione del client assertion e costruisce gli Headers agid da inserire nelle comunicazioni.
```
func main() {

	signBytes, err := os.ReadFile(privKeyPath)
	fatal(err)

	signKey, err := jwt.ParseRSAPrivateKeyFromPEM(signBytes)
	fatal(err)

	signBytes, err = os.ReadFile(pubKeyPath)
	fatal(err)

	_, err = jwt.ParseRSAPublicKeyFromPEM(signBytes)
	fatal(err)

	payloadBytes, err := os.ReadFile(body)
	fatal(err)

	logs.Info("Token computing")

	//Agid-JWT-Signature
	digest32Bytes := sha256.Sum256(payloadBytes)
	digestBytes := digest32Bytes[:]
	digest64 := base64.StdEncoding.EncodeToString(digestBytes)

	// Create a new token object, specifying signing method and the claims
	// you would like it to contain.
	signToken := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"aud": audience,
		"iat": jwt.NewNumericDate(time.Now()),
		"nbf": jwt.NewNumericDate(time.Now()),
		"exp": jwt.NewNumericDate(time.Now().Add(time.Minute * 60)),
		"iss": clientid,
		"sub": clientid,
		"jti": fmt.Sprint(time.Now().UTC().Format("20060102150405")) + fmt.Sprint(rangeIn(10000, 99999)),
		"signed_headers": []innerClaims{
			{"content-type": "application/json"},
			{"digest": "SHA-256=" + digest64},
		},
	})

	signToken.Header["kid"] = kid

	// Sign and get the complete encoded token as a string using the secret
	tokenString, err := signToken.SignedString(signKey)

	// Create a new token object, specifying signing method and the claims
	// you would like it to contain.
	trackToken := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iat":          jwt.NewNumericDate(time.Now()),
		"exp":          jwt.NewNumericDate(time.Now().Add(time.Minute * 60)),
		"nbf":          jwt.NewNumericDate(time.Now()),
		"aud":          audience,
		"purposeId":    purpose,
		"iss":          clientid,
		"sub":          clientid,
		"jti":          fmt.Sprint(time.Now().UTC().Format("20060102150405")) + fmt.Sprint(rangeIn(10000, 99999)),
		"dnonce":       fmt.Sprint(rangeIn(1000000000000, 9999999999999)),
		"userID":       "your-user-id",
		"userLocation": "your-user-location",
		"LoA":          "your-LoA",
	})

	trackToken.Header["kid"] = kid

	// Sign and get the complete encoded token as a string using the secret
	tokenTrackString, err := trackToken.SignedString(signKey)
	//fmt.Println("JWS di audit: "+tokenTrackString, err)

	agid_jwt_tracking := tokenTrackString

	digestAud32Bytes := sha256.Sum256([]byte(tokenTrackString))
	digestAudBytes := digestAud32Bytes[:]
	digestAud := fmt.Sprintf("%x", string(digestAudBytes))
	
	//per creare la client assertion per ottenere il voucher
	fmt.Println("digest JWS di audit: "+digestAud, err)
	fmt.Println("ATTENZIONE: USARE LA digest JWS per generare la client assertion", err)
	//headers per le chiamate
	fmt.Println("Digest (base 64): SHA-256=" + digest64)
	fmt.Println("Agid-JWT-Signature: "+tokenString, err)
	fmt.Println("Agid-JWT-TrackingEvidence: "+agid_jwt_tracking, err)

}
```

**Comment by paoloveggi** [comment]
Grazie dell'aiuto, mi auguro risponda anche qualcuno da AgID.

**Comment by paoloveggi** [comment]
@amollicone1982 è possibile avere supporto? Grazie.

**Comment by amollicone1982** [comment]
unknow api potete averlo ho quando sbagliate la url, sbagliate il metodo(deve essere post) o non mettete l'authorization bearer

**Comment by paoloveggi** [comment]
Noi stiamo implementando la chiamata con il solo C029. Il metodo è POST tramite chiamata cURL, il bearer è presente e lo posto qui di seguito, mentre la URL chiamata è questa:  https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002

eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyOS1zZXJ2aXppb0FjY2VydGFtZW50b0RhdGlBbmFncmFmaWNpL3YxIiwic3ViIjoiYWE4YjA2NTktMmQzZi00ZjEyLWFlYmQtZWY5MDMyZjcwZTgyIiwibmJmIjoxNjk5OTc1MzQwLCJkaWdlc3QiOnsiYWxnIjoiU0hBMjU2IiwidmFsdWUiOiI2Zjg5ZjE3ZDk5NDIyMjRlYzljMDBkYTEyMWMzM2E5NDBhODAwZGJjODVjYjdkZDAwMmE1MTM2NTExMmRjODQ3In0sInB1cnBvc2VJZCI6IjdlNzU3MGE5LWZmYWUtNDE2Zi1iMTRhLTJlOWY5NjUwMDAxNCIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTY5OTk3NTk0MCwiaWF0IjoxNjk5OTc1MzQwLCJjbGllbnRfaWQiOiJhYThiMDY1OS0yZDNmLTRmMTItYWViZC1lZjkwMzJmNzBlODIiLCJqdGkiOiIyZWViZjY4ZS00ZTljLTQ2MDMtYjllMy1jODcxYzAwNTliZTAifQ.p0O5PikHnukPlNs7rNwIzFy0CpOhR4E-ognRDSXs6Bgjk4Jy1sY7NpcnMMczMV3mxqZjjboahh2EY8LKAvHqNZpJZONZr5XTqoDSiUEaPLVb_cIbHTAQT9STXD-hygMs9511l4No10op9iyq5ZzHtSfcbvdZ8D6ycQvNsSHbvUhuFWlkoYVWt6zv61OQFlHMRqdtIlYXN9ZTkA5_3gSJX1Zl1n_cRZIvAvwrROL6rzq4PH6owbT9ZyReXa9Zjku5DOHHG-Q4GGWUTZPw6uDGfZ8xoG4_HyRBCRy0AIAB_-7sNC09vpCzJ8he2rE5zPToiZEgIUqEaEB0xSDux5aOLwHTTP code: 404stdClass Object

**Comment by amollicone1982** [comment]
cosa prendete come errore?

**Comment by paoloveggi** [comment]
Ecco un estratto dell'array error:
stdClass Object
(
    [type] => https://govway.org/handling-errors/404/NotFound.html
    [title] => NotFound
    [status] => 404
    [detail] => Unknown API Request
    [X-Global-Transaction-ID] => 3f7e3e2d6553917b44b49b2d
)

E' un 404, ma non capiamo il motivo.

**Comment by amollicone1982** [comment]
L'altra possibilità è che stai staccando il voucher pdnd dall'ambiente di produzione e chiamando il servio in collaudo.
Cmq c'e' un client funzionante:

C'e' un client di esempio nel github
https://github.com/italia/anpr/issues/3964

**Comment by paoloveggi** [comment]
Ringrazio, il client di esempio in Java lo abbiamo già visto e utilizzato per creare il nostro in PHP. L'access token viene richiesto utilizzando questa URL: https://auth.uat.interop.pagopa.it/token.oauth2

**Comment by amollicone1982** [comment]
ci sono numerosi soggetti che lavorano in collaudo. La risposta è che state sbagliando qualcosa nell'invocazione.
Il token staccato da pdnd lo mettete nel'header Authorization?

**Comment by paoloveggi** [comment]
Si, viene messo nell'header così: 'Autorization: Bearer ' . $bearer dove $bearer è il valore del voucher restituito da pdnd

**Comment by paoloveggi** [comment]
Ho appena fatto un test con postman e ritorna lo stesso identico errore

**Comment by amollicone1982** [comment]
allora stai sbagliando qualcosa (il voucher pdnd è scaduto per caso?)

**Comment by amollicone1982** [comment]
incollamelo

**Comment by paoloveggi** [comment]
scusa, l'ultima riga non centra, è questo: eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyOS1zZXJ2aXppb0FjY2VydGFtZW50b0RhdGlBbmFncmFmaWNpL3YxIiwic3ViIjoiYWE4YjA2NTktMmQzZi00ZjEyLWFlYmQtZWY5MDMyZjcwZTgyIiwibmJmIjoxNjk5OTc2NDg3LCJkaWdlc3QiOnsiYWxnIjoiU0hBMjU2IiwidmFsdWUiOiJiNDU3OTcyYjk1NDNlMDFhZjgxNzQyOTBiNzAzMTYzNjFiODg4NTIyOGVmZjI4OWU0N2JjMjk0NDE4ZTEwNGFmIn0sInB1cnBvc2VJZCI6IjdlNzU3MGE5LWZmYWUtNDE2Zi1iMTRhLTJlOWY5NjUwMDAxNCIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTY5OTk3NzA4NywiaWF0IjoxNjk5OTc2NDg3LCJjbGllbnRfaWQiOiJhYThiMDY1OS0yZDNmLTRmMTItYWViZC1lZjkwMzJmNzBlODIiLCJqdGkiOiIyYjg1ZGViZi02MzMwLTRjOTEtYjBhMy0zOTVjMDAzOWNiMDYifQ.iF_PFC3IQeVdHGvKrBT3sTcRnbfMHsM-b4oujVbnmT6TU0kqITMUtNEE5Tovxui1qkmRonE75xv1lMG3Mm9zKQPz2FtPAFmwNxQ6O1HJr9qnPq8dKSmypIqlASRo5gUv8wrzGGoo3IuEzp3B7cFfOFxCUKt9KsgMkaK2catWJp7vIK_MxLYYAm9evhes_UsMh0PBLlXwFpwLMZd0VlI7qnTEL_rMao0TX8EpRSWUYAuJI7Sjr9s_AkzxWggijXCPAIA27H3Ql5nN0427VqXLE2it3Y6FD1_99mUvUmker5S-GnNu_7ivWhv0vp1IdZyTsNO013bkDnDAuFPfKCEfaA

**Comment by amollicone1982** [comment]
mi fai vedere la schermata postman

**Comment by paoloveggi** [comment]
![Screenshot 2023-11-14 164616](https://github.com/italia/anpr/assets/14877669/087058d8-2ee4-4a76-996a-66f947fd6a07)

**Comment by paoloveggi** [comment]
postman è generato utilizzando lo yaml preso da pdnd

**Comment by amollicone1982** [comment]
al posto di baseurl puoi mettere l'indirizzo completo?

**Comment by amollicone1982** [comment]
mi metti qui in chat kid, clientid, purposeid, faccio una prova io

**Comment by paoloveggi** [comment]
kid = 6yoxPkYibXDYl3XctZbx7h4xQDzLl4KccOXqf-m_nUE
clientId = aa8b0659-2d3f-4f12-aebd-ef9032f70e82
purposeid = 7e7570a9-ffae-416f-b14a-2e9f96500014

**Comment by amollicone1982** [comment]
senza la tua chiave privata non riesco a fare una prova completa ma invocando https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1/anpr-service-e002 con un altro token prendo 400 (superato il problema del 404) superando il tuo problema.

Facciamo una cosa mi generi un voucher pdnd e me lo passi in chat?

**Comment by paoloveggi** [comment]
Non ho possibilità di accedere al portale pdnd al momento, posso però girarti le chiavi che sto usando qui in chat, tanto sono di collaudo. Va bene?

**Comment by paoloveggi** [comment]
Aspetta, ho capito il problema del 404, avevamo scritto Autorization senza "h" invece di Authorizaton, me ne sono accorto adesso per caso. Adesso riceviamo questo codice di errore 404 con id:

4e12c4d7-8302-11ee-8021-005056ae5232

**Comment by amollicone1982** [comment]
Avete visto che il problema è che non mettavate Authorization....

Adesso errore è:

Digest' possiede un valore non corrispondente al messaggio
Header HTTP 'content-encoding', dichiarato tra gli header firmati, non trovato negli attributi http

**Comment by amollicone1982** [comment]
adesso è rimasto nell'ultima chiamata

Digest' possiede un valore non corrispondente al messaggio

**Comment by paoloveggi** [comment]
Nell'ultima appena fatta è stato tolto e l'error id è il seguente: 3f782490-8304-11ee-a8bf-005056ae1884

**Comment by paoloveggi** [comment]
Adesso il digest generato è uguale al vostro atteso, ma l'error id è questo: 5844e823-8305-11ee-a8bf-005056ae1884

**Comment by amollicone1982** [comment]
'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

aud è leggermente diverso dall'url che chimate
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C029-servizioAccertamentoDatiAnagrafici/v1
e non
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C029-servizioAccertamentoDatiAnagrafici/v1

**Comment by paoloveggi** [comment]
Grazie, abbiamo modificato l'URL  e adesso riceviamo questo: 3f7e3e2d6554add9459c9e6d

**Comment by paoloveggi** [comment]
E' di nuovo un 404, sembra che non gli piaccia il nuovo URL

**Comment by paoloveggi** [comment]
Ok, modificato, adesso riceviamo questo: 29b45df1-83a6-11ee-a944-005056ae1884

**Comment by amollicone1982** [comment]
avete messo aud "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR**-PDND**/C029-servizioAccertamentoDatiAnagrafici/v1 nel token di signature 

deve essere senza -PDND

**Comment by amollicone1982** [comment]
aud è diversa dalla url che chiamate...

**Comment by amollicone1982** [comment]
adesso avete superato errori sulla cornice di sicurezza e il problema è che nel body avete messo
"casoUso" : "CDCLVNT58H11H501C"
anziche
"casoUso" : "C029"

**Comment by paoloveggi** [comment]
Ok, inserito anche nell'aud di richiesta del token signature, adesso fuziona, grazie! Ci sono dei codici fiscali di test per ottenere un ritorno valido con dei dati anagrafici?

**Comment by amollicone1982** [comment]
[casiTest_consultazione.xlsx](https://github.com/italia/anpr/files/13364305/casiTest_consultazione.xlsx)

**Comment by paoloveggi** [comment]
Perfetto, ce l'abbiamo fatta. Grazie mille per il supporto.
