### ISSUE TITLE
Liste Elettorali in ANPR - Subentro Liste Aggiunte

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#4191]
Buonasera,

in fase di primi subentri ci siamo accorti che erroneamente non abbiamo caricato gli elettori delle liste aggiunte (nel file il campo elettore era N).
Non abbiamo tantissimi casi, ma dovremmo capire qual è il metodo da seguire per risolvere questa situazione.

Basta mandare una mutazione per questi elettori rimasti fuori dal subentro per recuperare il mancato caricamento iniziale? O sono previste altre possibilità?

Grazie

**Comment by amollicone1982** [comment]
Potete mandare delle mutazioni 5010 tranquillamente casomai specificando nel tiporevisione primo caricamento
