### ISSUE TITLE
Lentezza invio operazioni elettorale

### ISSUE THREAD

**Issue by migmar68** [italia/anpr#4193]
Buongiorno.
Siamo riscontrando da ieri pomeriggio dei rallentamenti prima, e degli errori di comunicazione ora, sia sull'invio dei files di subentro, che delle singole mutazioni.
Esempi: su upload file sezioni in un caso ieri "errore durante il salvataggio" provando a caricare file sezioni.  Ripetuto caricamento successivamente, ha funzionato nonostante l'apparente duplice caricamento (vedi sotto).
In un altro caso l'operatore ha provato più volte e alla fine si è trovato 2 file sezioni caricate. al termine dopo un
Altre singole operazioni di mutazione elettorale hanno impiegato 2-3 minuti, oppure sono andate in errore di comunicazione.

Dato che la scadenza si sta avvicinando, evidenziamo la problematica dovuto pensiamo all'aumento dei comuni che stanno operando.
Marco

![image](https://github.com/italia/anpr/assets/124561581/9e795978-a2af-48ae-89da-0330d8580c8e)

**Comment by amollicone1982** [comment]
Ci sono stati dei rallentamenti che sono rientrati
