### ISSUE TITLE
Mutazione dati elettorali cittadino lista aggiunta

### ISSUE THREAD

**Issue by migmar68** [italia/anpr#4194]
Buongiorno.
Comune di Spoltore. id cittadino 78257885
tentando di entrare dalla web application, per fare una mutazione manuale dei dati elettorali restituisce:

![image](https://github.com/italia/anpr/assets/124561581/c39a753f-e95e-40d5-a1b0-7ca5871f724b)

questo problema è stato riscontrato anche su altri comuni e cittadini, sempre iscritti in lista aggiunta (in questo caso UE comunali).
invece stesso comune, tentando la mutazione su un elettore in lista generale, si apre la videata normalmente.

**Comment by amollicone1982** [comment]
Puo' riprovare adesso
