### ISSUE TITLE
Segnalazione rallentamenti servizi ANPR

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#4195]
Buongiorno,
alcuni comuni ci stanno segnalando dal pomeriggio del 24/10/2023 e anche questa mattina dei rallentamenti nei servizi di anpr di iscrizione, cancellazione, mutazione.
Per i servizi di consultazione e certificazione il funzionamento risulta regolare.
Potete verificare?

**Comment by Barisctt** [comment]
Confermo (dal comune di Bari) che dal 24/10 abbiamo problemi di interazione con ANPR per iscrizioni, 
cancellazioni e mutazioni.

**Comment by sfmodena** [comment]
Buongiorno, stessi problemi anche a Modena, sia da webapp che da ws.

**Comment by AriannaIeicicGPI** [comment]
Confermo problemi di rallentamento da parte di tutti i nostri clienti che da ieri ricevono ieri errori di connessione su svariate operazioni. chiediamo una verifica urgente.
grazie
Arianna Ieicic
GPI

**Comment by FERRETTI-LAURA** [comment]
Confermo che anche il Comune di  Ancona sta riscontrando gli stessi problemi

**Comment by RENZO63** [comment]
Non si riesce nemmeno piu' ad accedere alla webapp

**Comment by UpiTorino** [comment]
Confermiamo anche per Torino

UPI

**Comment by mttfranci** [comment]
Buongiorno, riscontrate ancora il comportamento?

Saluti

Assistenza ANPR

**Comment by siscomanpr** [comment]
Buongiorno,
confermo che stamattina non abbiamo avuto segnalazioni di rallentamenti da parte dei clienti.

**Comment by mttfranci** [comment]
Perfetto grazie.
Buona giornata.
