### ISSUE TITLE
Errore di caricamento AIRE /ANPR: Stato estero di residenza 325 non esistente

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#42]
Buongiorno,
in fase di caricamento ANPR, in ambiente di TEST, del file AIRE , del Comune di Bologna, su alcuni soggetti , abbiamo questo tipo di  errore:

Errore di caricamento: Stato estero di residenza:325 non esistente

Esempio:
Identificativo scheda attribuito da  ANPR 3547325 Comune  037006 
Comune di residenza : Gerusalemme

Questi soggetti sono caricati senza errori, nella procedura ANAGAIRE

Nel tracciato previsto dal Ministero per il caricamento degli AIRE nella procedura ANAGAIRE si parla di "TERRITORIO DI RESIDENZA" (http://servizidemografici.interno.it/it/anagaire-tracciato-record) .
Il pià delle volte c'è un rapporto di 1 a 1 fra stato/nazione e territorio.
Ci sono dei casi, come ad esempio la Francia, in cui la nazione Francia ha più territori.

Come si vede dalla tabella in basso, (righe 98, 99, 110, 111) nello stato di ISRAELE ci sono 2 consolati che hanno competenza su 4 diversi territori.

Riteniamo e ve ne chiediamo conferma,  che l'errore segnalato in fase di caricamento  in ANPR derivi dal fatto che il territorio 325, ovviamente non è uno stato, ma è comunque il dato che ci chiede il ministero.

![tabella_territori](https://cloud.githubusercontent.com/assets/26138056/24190425/e747d908-0ee8-11e7-89a8-f831cf9ca0f3.png)
Come dobbiamo `procedere?`

Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by gcarbonin** [comment]
Per quanto riguarda di 3 entità territoriali (Circoscrizione Autonoma, Taiwan, Territori dell’Autonomia Palestinese)  che per motivi politici non possono essere considerate né stati sovrani né territori dipendenti. La loro gestione varia a seconda dell’uso che viene fatto dei dati scambiati.  Stiamo facendo ulteriori verifiche le facciamo sapere

**Comment by gcarbonin** [comment]
Può riprovare e darci un riscontro?

**Comment by ANPRCDBO** [comment]
Salve,la prova ha dato  sempre lo stesso errore sul file AIRE:  stato estero di residenza: 325 non esistente -----gcarbonin <notifications@github.com> ha scritto: -----Per: italia/anpr <anpr@noreply.github.com>Da: gcarbonin <notifications@github.com>Data: 28/03/2017 03.27PMCc: ANPRCDBO <SipoBologna@comune.bologna.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/anpr] Errore di caricamento AIRE /ANPR: Stato estero di residenza 325 non esistente (#42)Può riprovare e darci un riscontro?

**Comment by gcarbonin** [comment]
La modifica era stata effettuata nei servizi; ora è stata riportata anche nel subentro puo' riprovare

**Comment by ANPRCDBO** [comment]
Salve, effettivamente nell'ultima prova questo errore e' scomparso -----gcarbonin <notifications@github.com> ha scritto: -----Per: italia/anpr <anpr@noreply.github.com>Da: gcarbonin <notifications@github.com>Data: 28/03/2017 03.27PMCc: ANPRCDBO <SipoBologna@comune.bologna.it>, Author <author@noreply.github.com>Oggetto: Re: [italia/anpr] Errore di caricamento AIRE /ANPR: Stato estero di residenza 325 non esistente (#42)Può riprovare e darci un riscontro?

**Comment by gcarbonin** [comment]
In comune ha confermato il buon esito della prova
