### ISSUE TITLE
Errore di sicurezza (SunCertPathBuilderException) in ambiente di TEST-COMUNI

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#4200]
Buongiorno

da ieri rileviamo un errore di collegamento con ANPR in ambiente TEST-COMUNI:

"000000E : ERRORE COLLOQUIO ANPR: Problem writing SAAJ model to stream: PKIX path building failed: sun.security.provider.certpath.**SunCertPathBuilderException: unable to find valid certification path to requested target"**

Sembrerebbe un errore di certificazione, ma abbiamo verificato i certificati e sono validi.  
Potreste darci una mano a capire il problema?
Grazie

Saluti
_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by mttfranci** [comment]
Buongiorno, Il comportamento si presenta ancora?
Stiamo parlando di qualche servizio in particolare?
Grazie in anticipo.

Saluti

**Comment by AMonopoliADS** [comment]
abbiamo lo stesso problema.
per quanto riguarda noi, sembra che il certificato server per invocare i servizi (tutti) su wstest.interno.anpr.it sia scaduto il 25/10/2023.
potete farci avere un certificato aggiornato?

grazie
Alessandro Monopoli ADS

**Comment by LucaBonini64** [comment]
Buongiorno,
vi segnaliamo che anche noi abbiamo lo stesso problema con i servizi di test.
Grazie
Luca Bonini APKAPPA

**Comment by mttfranci** [comment]
@MarcoSalaPad  @LucaBonini64 @AMonopoliADS @ANPRCdMI Da una verifica forse potrebbe dipendere dal fatto che va aggiornata la CA di ANPR. La potete trovate per l'ambiente di test dalal web app di test comunu -> Strumenti di supporto -> Certification Authority (CA) ANPR.

Potreste verificare se in questo modo risolvete?

Grazie in anticipo.

**Comment by gborselli** [comment]
Cosa significa aggiornare "la CA di ANPR"? Fino ad ora nel nostro cacert importavamo il certificato scaricato da wstest.interno.anpr.it.
Quello che avevamo noi scadeva il 26/10/2023.
Abbiamo scaricato quello aggiornato (sempre da wstest.interno.anpr.it con nuova scadenza 18/10/2025) e importato nel cacert ma continua a dare il medesimo errore.

Grazie

Gianfranco Borselli
Datamanagement Italia

**Comment by Leonforte** [comment]
Buongiorno, il nuovo certificato di wstest.anpr.interno.it è stato emesso con una nuova CA, CA ANPR Postazioni Svil, il cui certificato è presente nella sezione Sturmenti di Support - Certificati di CA

**Comment by MarcoSalaPad** [comment]
Buongiorno,
abbiamo aggiornato la CA di ANPR e per quanto ci riguarda ora tutto ha ripreso a funzionare in modo corretto.

Grazie
Marco Sala
Pa Digitale Spa

**Comment by Leonforte** [comment]
Perfetto, buon lavoro
