### ISSUE TITLE
[5008] Vedovanza / Aggiornamento Stato Civile

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#421]
ambiente di PRODUZIONE - comune di FAENZA (RA)

continuiamo ad avere qualche difficoltà con i controlli bloccanti che vengono effettuati sulla sovrapporisizione / coerenza delle date.

- idOperazioneComune 2017000057: decesso di soggetto (idSoggettoANPR 19100663) coniugato con altro soggetto presente in ANPR
la variazione viene comunicata il 21/11 con decorrenza 17/11 (data del decesso), ed ha esito positivo.
la comunicazione del decesso produce automaticamente l'aggiornamento dei dati di vedovanza del coniuge superstite (idSoggettoANPR 19100666)
- idOperazioneComune 2017000161: aggiornamento dello stato civile da 'coniugato' a 'vedovo' del coniuge superstite (idSoggettoANPR 19100666)... la data decorrenza è la stessa della comunicazione di cui sopra, ma la comunicazione viene bloccata con il messaggio:
EN389 - E - La data decorrenza 17-11-2017 dell'operazione non puo' essere inferiore alla data decorrenza 20-NOV-17 dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto

interpretando che la data di cui sopra sia quella del subentro, e rifacendomi al carteggio di cui alla issue #409 , abbiamo controllato le date (iscrizione - residenza - ultimoAggiornamento):
- iscrizione: è presente
- residenza: era mancante, ed è stata inserita dalla web-app
- ultimoAggiornamento: non avendo la possibilità di verificarla tramite web-service (... approfitto per ricordare che è tra le richieste di evolutiva che abbiamo fatto di recente...) abbiamo verificato all'interno dell'xml di subentro, ed anche questa data è valorizzata.

quale informazione ci manca o ci sfugge?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Stiamo verificando

**Comment by mttfranci** [comment]
La data decorrenza in ANPR è limitata dalle precedenti operazioni inerenti il soggetto (a questo riguardo vale quanto indicato già nella issue #409).
Vale anche per le comunicazioni per decesso che e’ stata acquisita con data decorrenza 17 per un errore nel controllo. 
Pertanto, in questo caso, la data decorrenza minima che può essere indicata per la mutazione è la data del subentro (20 Novembre 2017)
Come piu’ volte segnalato, la data giuridica è comunque 17-11.

**Comment by AMonopoliADS** [comment]
forzando la data 20/11 come decorrenza della mutazione, la comunicazione è stata accettata.

problema analogo, però, lo stiamo avendo per una cancellazione di soggetto AIRE che rimpatria in altro comune italiano.
ambiente di PRODUZIONE - comune di Faenaz - idOperazioneComune 2017000350

a fronte di un primo errore:
EN240 - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto

abbiamo proceduto con la forzatura della dataDecorrenza in testataRichiesta, impostando la data di subentro (20/11)
... ma l'errore persiste...

**Comment by fugerit79** [comment]
Salve.
Per l'operazione da voi indicata (2017000350), in testata la data decorrenza è il 20 Novembre.
Ma il campo data decorrenza cancellazione è impostato al 14 Novembre :+1: 
      <datiCancellazione>
        <motivoCancellazione>4</motivoCancellazione>
        <dataDecorrenzaCancellazione>2017-11-14</dataDecorrenzaCancellazione>
      </datiCancellazione>
Il controllo :
EN240 - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto
Verifica questa seconda data qualora presente.

**Comment by mttfranci** [comment]
Salve.
Per l'operazione da voi indicata (2017000350), in testata la data decorrenza è il 20 Novembre.
Ma il campo data decorrenza cancellazione è impostato al 14 Novembre :

      <datiCancellazione>
        <motivoCancellazione>4</motivoCancellazione>
        <dataDecorrenzaCancellazione>2017-11-14</dataDecorrenzaCancellazione>
      </datiCancellazione>

Il controllo :
EN240 - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto
Verifica questa seconda data qualora presente.

**Comment by AMonopoliADS** [comment]
ok. grazie Matteo.
adesso procederemo anche con questa modifica.

l'errore EN240 parla di "decorrenza dell'operazione" e anche il documento "utilizzo delle date anpr" parla del campo dataDecorrenza, rimandando alla nomenclatura dell'elemento contenuto nella testataRichiesta.
per questo abbiamo pensato di potere mantenere la reale decorrenza all'interno dei datiCancellazione...

**Comment by MarcoMigliori** [comment]
Scusate l'intromissione confidando che il problema specifico sia già stato risolto.

Ma l'intervento descritto nella #395 e nella #343 a questo punto non l'ho capito.
La c'è scritto di mettere la decorrenza come imputata dall'UdA.
Qui si scrive invece di mettere una decorrenza "fittizia" (il subentro), e quella "vera" viene desunta automaticamente.
Non sono in contrasto le due versioni?

**Comment by mttfranci** [comment]
Buongiorno.
@AMonopoliADS : Stiamo valutando come rendere più chiaro il comportamento.
@MarcoMigliori : Non ci sono date fittizie. Semplicemente la data decorrenza di una nuova operazione è limitata dall'ultima compiuta. In alcuni casi tale ultima operazione è considerata il subentro.

**Comment by AMonopoliADS** [comment]
chiedo scusa in anticipo, ma finchè non capisco il meccanismo, fatico a giustificare certi comportamenti anche al cliente.

ho un altro caso di cancellazione AIRE che va in errore con il messaggio:
"EN240 - E - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto"

rifacendomi alla vostra documentazione ("utilizzo delle date in ANPR") e a quanto specificato da nella issue 409, ho verificato le date del soggetto AIRE in questione (idSchedaANPR 19090061)

data iscrizione AIRE: 30/06/2015
data decorrenza residenza: 30/06/2015
data ultimo aggiornamento: 30/07/2015 (visualizzata in ANAG-AIRE, xchè non so in quale altro modo verificarla...)

... mi aspetto che ANPR consideri come "data inizio validità" il 30/07/2015 (data più alta delle 3).

la cancellazione AIRE che si tenta di comunicare ha come decorrenza 08/04/2017

cosa giustifica l'errore?
grazie

rif. ambiente di PRODUZIONE - comune di Faenza - idOperazioneComune 2017000684

**Comment by frmariani** [comment]
abbiamo rimosso l'anomalia. 
potete riprovare.

**Comment by AMonopoliADS** [comment]
infatti adesso è andata.
ho il sospetto che anche il caso dell'idSchedaANPR 19088934 potesse essere risolto senza forzatura della decorrenza. è possibile verificare?
oggi ho provato ad annullare e ripetere la cancellazione ma persiste l'errore, quindi, al momento, ho riconfermato la dta del subentro.
grazie
