### ISSUE TITLE
[PDND C002] Errore di comunicazione con e-Service PDND C002-servizioComunicazione

### ISSUE THREAD

**Issue by fquattropani-dxc** [italia/anpr#4211]
Abbiamo provveduto ad implementare i pattern di sicurezza richiesti INTEGRITY_REST_02 e AUDIT_REST_02 per l'e-service di PDND C002-servizioComunicazione

Stiamo effettuando delle prove di comunicazione con l'e-service, ma abbiamo ottenuto un errore 07/11/2023 ore 12.27 circa:

400 - {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"33dd5b18-7d59-11ee-b464-005056ae5232"}

Come da linee guida  stiamo passando in header:

Agid-JWT-Signature: ew0KCSJ0eXA......
Authorization: Bearer eyJ0eXAiOiJ......
Content-Encoding: UTF-8
Content-Type: application/json
Digest: OeCxwH4QEnVNIhSktK2biT/2Nq3ZoV93B7FXrAgnkiA=
Agid-JWT-TrackingEvidence: ew0KCSJ0eXAiOiAiS.....

I jwt li abbiamo riportati qui non completi, avete modo di verificarli nei vostri log ?

Fruitore: INAIL
Piattaforma: PDND
Ambiente: Collaudo
Data del test: 07/11/2023
Orario: intorno alle 12.27

Potreste aiutarci a capire la problematica.

Ringaziando, vi auguriamo una buona giornata.

**Comment by amollicone1982** [comment]
Il digest non è in un formato riconosciuto (es. SHA-256=3DA....).
Penso che dobbiate anteporre SHA-256= al digest che avete calcolato

**Comment by fquattropani-dxc** [comment]
Grazie per la risposta.

Abbiamo aggiunto come da vostra indicazione l'header nel formato corretto:
Abbiamo effettuato un altro test 09/11/2023 ore 12:31:45 circa.
Ottenendo l'errore:

400 - {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"e8b3248f-7eec-11ee-ab4e-005056ae5232"}

Vi riporto gli header passati:

Agid-JWT-Signature: ew0KCSJ0eXA......
Authorization: Bearer eyJ0eXAiOiJ......
Content-Encoding: UTF-8
Content-Type: application/json
Digest: SHA-256=OeCxwH4QEnVNIhSktK2biT/2Nq3ZoV93B7FXrAgnkiA=
Agid-JWT-TrackingEvidence: ew0KCSJ0e.....

I jwt li abbiamo riportati qui non completi, avete modo di verificarli nei vostri log ?

Fruitore: INAIL
Piattaforma: PDND
Ambiente: Collaudo
Data del test: 09/11/2023
Orario: intorno alle 12.31

Aspettiamo un vostro cortese riscontro.
Grazie mille.

**Comment by amollicone1982** [comment]
Header HTTP 'content-encoding' possiede un valore differente rispetto a quello presente negli header firmati

Da una parte UTF.8 e dall'altra UTF-8

**Comment by fquattropani-dxc** [comment]
Grazie nuovamente per la risposta.
Nelle varie prove che abbiamo fatto ci sono state delle sviste.
Abbiamo corretto e riprovato test 09/11/2023 ore 13:52:32 circa.
Ottenendo l'errore:

400 - {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"23ff435f-7ef6-11ee-ab4e-005056ae5232"}


Vi riporto gli header passati:

Agid-JWT-Signature: ew0KCSJ0eXAiOiA......
Authorization: Bearer eyJ0eXAiOiJ......
Content-Encoding: UTF-8
Content-Type: application/json
Digest: SHA-256=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
Agid-JWT-TrackingEvidence: ew0KCSJ0eXAiOiAi.....

I jwt li abbiamo riportati qui non completi, avete modo di verificarli nei vostri log ?

Fruitore: INAIL
Piattaforma: PDND
Ambiente: Collaudo
Data del test: 09/11/2023
Orario: intorno alle 13:52:32

Aspettiamo un vostro cortese riscontro.
Grazie mille.

**Comment by amollicone1982** [comment]
Adesso l'errore è il seguente:
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by amollicone1982** [comment]
Vedo che state facendo varie prove dove state prendendo come errore
Token creato da troppo tempo (data creazione: '2023-11-09_16:48:46.000')

**Comment by fquattropani-dxc** [comment]
Abbiamo appena fatto un nuovo test, il voucher dell pdnd è stato appena generato 17.09.11.
Ogni chiamata viene generato un nuovo voucher 
Riceviamo l'errore 

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0f6a0848-7f12-11ee-864a-005056ae1884"}

Aspettiamo un vostro cortese riscontro.
Grazie mille.

**Comment by amollicone1982** [comment]
Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2023-11-09_16:59:10.000'). Deve stare entro i 10 min

**Comment by fquattropani-dxc** [comment]
Abbiamo modificato il calcolo del jwt nei 10 minuti 
Ad ogni chiamata vengono generati.
Abbiamo appena riprovato con una post di prova e sembra che abbiamo superato la sicurezza
Ci confermate che l'errore ora è restituito dal servizio di BE?

POST /C002-servizioComunicazione/v1/anpr-service-e002
ore 18:00:11

400 - {"type":"https://govway.org/handling-errors/400/InvalidRequestContent.html","title":"InvalidRequestContent","status":400,"detail":"Request content not conform to API specification: Validation error(s) :\nbody: Field 'idOperazioneClient' is required. (code: 1026)\nFrom: body.<required>\nbody: Field 'criteriRicerca' is required. (code: 1026)\nFrom: body.<required>\nbody: Field 'datiRichiesta' is required. (code: 1026)\nFrom: body.<required>\n","govway_id":"f6545b2a-7f18-11ee-864a-005056ae1884"}


Abbiamo provato anche la get con /status e la risposta è stata nuovamente di errore:
GET /C002-servizioComunicazione/v1/status
ore 18:00:35 -
400 - {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"1d835ec6-7f1a-11ee-ab4e-005056ae5232"}

Aspettiamo un vostro cortese riscontro.
Grazie mille.

**Comment by amollicone1982** [comment]
Nell'ultima richiesta non avete messo il payload
Header HTTP 'Digest' presente in una richiesta con http payload vuoto

**Comment by amollicone1982** [comment]
potete procedere una richiesta alla volta e evitare di chimare la get status che crea solo confusione in questo momento

**Comment by fquattropani-dxc** [comment]
Grazie mille per il supporto dato.
Funziona tutto.
Proviamo gli altri servizi.

**Comment by amollicone1982** [comment]
Perfetto
Buona giornata
