### ISSUE TITLE
ACCESSO ANPR NEGATO / ALLINEAMENTO DATI ANAGRAFE CITTADINO AIRE 

### ISSUE THREAD

**Issue by gmg79** [italia/anpr#4213]
Buongiorno a tutti, 
sono cittadino AIRE e non riesco ad accedere all'ANPR via SPID. 
Ricevo un messaggio di errore che mi nega l'accesso per difficoltà ad individuare la scheda in modo univoco.
Ho contattato il mio comune AIRE per telefono, mail normale e poi PEC ( senza risposta ) ma non desiderano fare niente inquanto per loro la mia scheda non presenta anomalie.
Ho inviato una mail a Sblocco.aire ma mi hanno gentilmente rinviato al comune per sanare l'anomalia ma che non agisce.
**Mi sono resa conto di avere due codici fiscali, uno del ministero delle finanze ed un'altro dell'agenzia delle entrate, possiedo i documenti comprovanti.**
Essendo alla disperazione per poter usufruire dei servizi ANPR e non potendo spostarmi di persona vivendo a 2000 km dal comune in questione, provo a domandare assistenza su questo sito ( consigliato da un utente su forum Italia ).

Posso inviare tutti i documenti per comprovare la mia identità ed i differenti codici fiscali in privato.
In allegato metto l'errore ANPR.
![Capture d'écran 2023-11-08 160330](https://github.com/italia/anpr/assets/149619634/bca13dc1-16a3-4d02-a440-6930a3570a76)

Grazie in anticipo a chi mi darà una mano  :)
Cordiali saluti
GMG

**Comment by frmariani** [comment]
gentilmente le prime sei cifre del suo codice fiscale

**Comment by gmg79** [comment]
Grazie mille per avere letto il mio messaggio ed avermi risposto :)

**Ho due codici fiscali :
Il primo quello dell'agenzia delle entrate usato anche dallo SPID : CRTGRG
Il secondo quello della tessera verde e bianca del ministero delle finanze : CRTGAI**

l'ANPR mi rifiuta l'accesso con il CRTGRG che è quello inviato dallo spid...

Ancora grazie per la sua amabile attenzione 

> gentilmente le prime sei cifre del suo codice fiscale

**Comment by frmariani** [comment]
mi scriva in privato il codice fiscale completo altrimenti non riesco ad aiutarla
 frmariani@sogei.it

**Comment by gmg79** [comment]
Le ho appena inviato un email con oggetto **CODICE FISCALE Seguito issue GITHUB #4213 di GMG79**
Email di invio : gaiacartagenova29@gmail.com

La ringrazio infinitamente e resto a sua disposizione per tutte le richieste che lei giudicherà necessarie.

**Comment by gmg79** [comment]
Ringrazio infinitamente frmariani per aver sbloccato e risolto il mio problema con una grande gentilezza.
