### ISSUE TITLE
Invio file del subentro (APR-SUB)

### ISSUE THREAD

**Issue by ftabino** [italia/anpr#422]
Salve, volevo chiedere come mai il file del subentro resta nella stato "IN ELABORAZIONE". 

Ho effettuato un upload il giorno 17/11. Dopo tre giorni che stava "in elaborazione" il 20/11 ho richiesto la cancellazione ed oggi ho riprovato ad effettuare l'upload. Purtroppo resta sempre in quello stato e non ricevo nessuna pec.

COMUNE DI **AVIGLIANO 076007**
AMBIENTE **TEST**

**Comment by mttfranci** [comment]
Buongiorno.
Il subentro non può terminare fino a quando la fornitura non è completa.
Vale a dire che deve essere inviato anche il file con i soggetti AIRE.
Saluti
