### ISSUE TITLE
Servizio 1002 Internal Error (from client)

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#4221]
Buongiorno,
la richiesta con idOperazioneComune=1699613151585 e protocolloComune=IMMIGR2023065768, immigrazione per altri motivi, restituisce un "Internal Error (from client)" e non riusciamo ad individuare il motivo. Si richiede supporto. Richiesta inviata il 2023-11-10T11:45:51.585+01:00. Ambiente di produzione.

<idSchedaSoggettoComune>
  <idSchedaSoggettoComuneIstat>015146</idSchedaSoggettoComuneIstat>
  <idSchedaSoggetto>2955635</idSchedaSoggetto>
</idSchedaSoggettoComune>
<idSchedaSoggettoANPR>29451165</idSchedaSoggettoANPR

Grazie
Saluti

**Comment by ANPRCdMI** [comment]
> La richiesta non è valida rispetto agli xsd. Potete inviarci la richiesta da controllare?

La richiesta è stata inviata da Giuliano Caloni con mail del 13/11 alle 14:42 alla casella segnalazioni-anpr@teamdigitale.governo.it
Grazie

**Comment by amollicone1982** [comment]
problem è sul tag maternita dove inviate          
<maternita>
            <generalita/>
         </maternita>
