### ISSUE TITLE
ELETTORALE - ANPR - ERRORE IN PROCEDURA RICHIESTA CONTRIBUTO

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#4222]
COMUNE DI VALDILANA (BIELLA)  096088

Dopo aver terminato le procedure di inserimento dei dati di sezione ed elettori ed avute le due spunte sulla pagina di richiesta di contributo, verificato il numero di elettori ho aggiunto la terza spunta.
Cliccando su procedi il sistema mi ha restituito l'errore "Non è stato possibile reperire i dati del comune" 
Il Comune di Valdilana deriva dalla fusione di quattro comuni in data 1/1/2019 (Trivero, Valle Mosso, Mosso e Soprana)
Mi sapete dire come risolvere la situazione?

Resto in attesa di una risposta e invio i miei piu' cordiali saluti

Allego screenshot delle pagine

Il Resp. Servizi Demografici: Renzo Preto
![Screenshot 2023-11-13 143155](https://github.com/italia/anpr/assets/32871636/368f4a1f-947b-4da1-8696-205144c9ed4a)
![Screenshot 2023-11-13 143057](https://github.com/italia/anpr/assets/32871636/8f6f05a8-eaf5-4716-8f36-401867beb172)

**Comment by frmariani** [comment]
potete riprovare

**Comment by RENZO63** [comment]
Dopo il vostro intervento tutto ha funzionato
Ringrazio per la sollecita risoluzione
Cordiali saluti
Renzo
