### ISSUE TITLE
Elettorale- Errore iscrizione lista generale a seguito di cancellazione liste aggiunte

### ISSUE THREAD

**Issue by KibMcris** [italia/anpr#4223]
Buonasera,
per il cittadino che ha idANPR 32580596 cancellato dalla liste aggiunte dal comune di precedente iscrizione elettorale, adesso provando a fare la mutazione dei dati elettorali per valorizzare la corretta iscrizione nelle liste generali del comune di residenza attuale in quanto il cittadino è diventato italiano, ANPR risponde con il seguente errore:
La sezione della lista generale non puo' essere inserita quando è presente la lista aggiunta ue
si veda idOperazioneANPR 1511340627.
Si resta in attesa di riscontro

**Comment by amollicone1982** [comment]
Si trattava di un bug. Potete riprovare
