### ISSUE TITLE
[5010] Errore E999 operazione non effettuabile

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4224]
Buongiorno
nel comuna di Monte Compatri, per un cittadino cancellato per irreperibilità con la revisione semestrale la comunicazione ritorna errore E999 "operazione non effettuabile" 
Il soggetto (ID 150156106) è un cittadino AIRE che era stato cancellato per irreperibilità e poi resiscritto da irreperibilità.

Da cosa viene causato tale errore in fase di invio?
La richiesta inviata è la 20231110105031436

Grazie
Roberta

**Comment by amollicone1982** [comment]
Sul soggetto c'e' stato un bug. Adesso il soggetto non ha dati elettorali e ha certificabilita a 0 a seguito di una vostra mutazione del 13 novembre.
Se non ho capito male deve avere elettore N e per tale motivo vi sta fare una mutazione lista generale in cui mettete a N il soggetto (tipomutazione 01)
