### ISSUE TITLE
C015 - listaAnomalie

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4225]
Buongiorno,

sarebbe possibile avere un codice fiscale da utilizzare in ambiente di collaudo nell'eservice C015-servizioAccertamentoGeneralita (oppure su altro servizio esposto in PDND) che restituisca l'oggetto listaAnomalie ?
In questo modo riusciremmo a capire come gestirlo in modo corretto.

grazie

**Comment by amollicone1982** [comment]
listaAnomalie si tratta di un refuso. Non sarà piu' restituito nella risposta ok
