### ISSUE TITLE
riepiloghi liste elettorali non disponibili

### ISSUE THREAD

**Issue by nicoelis** [italia/anpr#4226]
buongiorno, 
sta mattina i riepiloghi relativi alle liste elettorali non sono disponibili, 
anche i totali elettori da certificare per accedere ai contributi sono errati, 
venerdì i dati erano corretti.
dovremo attendere domani, per poter ottenere totali corretti? 
grazie

**Comment by nicoelis** [comment]
quando potremo ritrovare i totali valorizzati?
ancora oggi sui comuni di ravenna, 
carpi.... non risultano presenti.

**Comment by amollicone1982** [comment]
Ora dovrebbero essere disponibili

**Comment by amollicone1982** [comment]
Riprovate adesso
