### ISSUE TITLE
[5005] msg. "EN2377 - la data... non può essere antecedente..."

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#423]
ambiente di PRODUZIONE - comune di Faenza (RA) - idOperazione 2017000149

soggetto che si sposta dal suo nucleo per entrare in aggregazione in altra famiglia.
il web-service torna il seguente errore:
EN237 - E - La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata

ma la data di decorrenza della nuova residenza NON è antecedente a quella registrata.

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Dai riscontri effettuati, abbiamo verificato che i componenti nella famiglia indicata nel servizio,  sono privi della data di decorrenza della residenza; in mancanza di tale data, il subentro inserisce come data di inizio validità della famiglia, la data del subentro, in questo caso 20/11/2017.
L’ idOperazione 2017000149, avendo come data decorrenza 18/11/2017, viene bloccata.
Suggeriamo di inserire la corretta data decorrenza della residenza almeno per uno dei due componenti della famiglia e poi riprovare con il cambio di residenza.
La modifica della data decorrenza della residenza, al momento, è possibili soltanto tramite la WA .

**Comment by AMonopoliADS** [comment]
abbiamo visto oggi, con altra pratica (idSoggettoANPR 19110315), che la valorizzazione della dataDecorrenzaResidenza da web-app, registra un'operazione sul soggetto con dataDecorrenza 20/11/2017 (data del subentro).
questa operazione ci ha vincolato comunque ad impostare la comunicazion di cui sopra (idOperazione 2017000534) con una dataDecorrenza NON antecedente a questa data (... visto che l'errore persisteva...).

per cui, tornando alla pratica di questa issue (idOperazione 2017000149): non è che inserendo la dataDecorrenzaResidenza (come suggerito) verrà comunque bloccata la dataDecorrenza 18/11/2017, xchè il sistema si aspetterà una data NON antecedente al 20/11/2017?
... in questo caso tanto vale non fare niente nella web-app...

grazie.
attendo riscontro...

**Comment by frmariani** [comment]
Buongiorno,
con l’ idOperazione 2017000149 si sta tentando di effettuare un cambio di residenza del soggetto idAnpr 19124201 che si trasferisce nella famiglia 9159508;

nella famiglia 9159508 sono presenti due soggetti senza la data decorrenza della residenza, pertanto la data di inizio validità della residenza dei due soggetti, come indicato nelle specifiche, è pari alla data del subentro; la data inizio validità della residenza della famiglia, deriva di conseguenza.

Cercando di effettuare il  cambio di residenza del soggetto idAnpr 19124201 in data 18/11/2017, il sistema blocca l’operazione perché  la data inizio validità della residenza della famiglia 9159508, già presente in ANPR,  risulta essere maggiore.

“Rettificando”  la data di decorrenza della residenza dei  due soggetti già  appartenenti alla famiglia 9159508, si ricalcoleranno tutte le date (con le stesse regole del subentro) ed avremo una nuova data di inizio validità della residenza della famiglia che, se coerente, consentirà di effettuare il cambio di residenza di id ANPR 19124201 in data 18-11; ciò sarà possibile perché per questo soggetto,  al subentro,  erano state comunicate tutte le date che si utilizzano per determinare l’inizio validità della schede in ANPR.

La pratica del soggetto idAnpr19110315, è fondamentalmente diversa: nel subentro questo soggetto non aveva la data decorrenza della residenza, pertanto la scheda ha assunto la data di inizio validità pari alla data del subentro. Questa data non è rettificabile: comunicando la data di decorrenza della residenza,  si sistema la situazione della persona consentendo l’emissione dei certificati storici di residenza,  ma operazioni in data antecedente alla data del subentro comunque non saranno accettate. 

Saluti.
