### ISSUE TITLE
C020-servizioAccertamentoResidenza - collaudo -> esempi

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4230]
Buongiorno,

sarebbe possibile avere (come é stato fatto per C015-servizioAccertamentoGeneralita) un elenco di dati con i quali poter testare il servizio C020-servizioAccertamentoResidenza di collaudo ?
grazie

**Comment by amollicone1982** [comment]
Troverà i casi di test nel file casitest.xls associato all'e-service sulla pdnd.

**Comment by SimonePadovan** [comment]
Ho cercato nel servizio C020 di collaudo esposto in PDND ma non ho trovato il file con i cf di test indicato.

**Comment by amollicone1982** [comment]
Adesso dovreste trovarle
