### ISSUE TITLE
C015-servizioAccertamentoGeneralita -> data decesso

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4231]
Buongiorno,

abbiamo notato che nella versione 3 di collaudo del servizio in oggetto la data di decesso viene gestita in maniera diversa rispetto alla versione 1 (che attualemnte é pubblicata in produzione).
È previsto un array di tipo TipoInfoSoggettoEnte il cui campo chiave viene valoruzzato con "Data decesso".
1) Sará questo il nuovo modo per ottenere la data decesso ?
2) Che altri dati avete intenzione di esporre in questo array ?

Grazie

**Comment by andpra70** [comment]
mi accodo per la richiesta

**Comment by SimonePadovan** [comment]
Quindi TipoInfoSoggettoEnte conterrá eventualmente solo la data di decesso ?
grazie

**Comment by SimonePadovan** [comment]
Grazie
