### ISSUE TITLE
C020-servizioAccertamentoResidenza descrizione campi

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4232]
Buongiorno,

sarebbe possibile ricevere la documentazione degli attributi tornati dal servitio C020-servizioAccertamentoResidenza in particolare in riferimento a TipoToponimo, TipoNumeroCivico e TipoCivicoInterno ?
Facciamo fatica a capire il significato di questi campi:
tipoIndirizzo
codSpecie
specieFonte
toponimoFonte
civicoFonte
metrico
progSNC
colore
espInterno1
interno2
secondario
nui

Grazie

**Comment by amollicone1982** [comment]
Potete recuperare le info dal file documentazioneC020 allegato all'e-service sulla pdnd

**Comment by SimonePadovan** [comment]
ottimo grazie!
