### ISSUE TITLE
[C003][Collaudo] Problemi invocazione webservice

### ISSUE THREAD

**Issue by TheVise1975** [italia/anpr#4234]
Buongiorno, 
sto provando ad eseguire l'integrazione con il servizio C003-servizioVerificaDichGeneralita-approvazione_automatica, v. 2 in ambiente di collaudo tramite il passaggio attraverso PDND.

Sto eseguendo l'integrazione in .NET, per cui il codice riportato sotto riguarda questa implementazione.
Ho configurato la finalità e l'e-service su PDND e ottenuto le "chiavi" per invocare il servizio.

L'url di audience che dovrei richiamare alla fine è:
**https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C003-servizioVerificaDichGeneralita/v1**

Il json della mia richiesta è questo:

 {
   "idOperazioneClient": "1",
    "criteriRicerca": {
      "codiceFiscale": "XXXXXX11X22X123X"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2023-11-15",
      "motivoRichiesta": "1",
      "casoUso": "C003"
    }
  }

Per prima cosa ho predisposto la chiamata di audit

        var headersRsa = new Dictionary<string, object>
        {
            { "kid", _keyId },
            { "alg", "RS256" },
            { "typ", "JWT" }
        };

        // Create an assertion for audit
        Guid jti = Guid.NewGuid();
        var auditPayload = new Dictionary<string, object>
{
    { "iss", _iss },
    { "sub",_sub},
     { "aud", audience },
    { "userID", userId },
    { "userLocation", location },
    { "LoA", loa },
    { "purposeId", _purposeId },
    { "dnonce", dnonce },
    { "jti", jti.ToString() },
    { "iat", iat },
    { "exp", exp}
}; 

L'ho firmato con la mia chiave privata (associata all'e-client) e successivamente calcolato lo SHA256.

Ho quindi richiesto il voucher a PDND andando a chiamare l'url **auth.uat.interop.pagopa.it/client-assertion**

    var payload = new Dictionary<string, object>
    {
        { "iss", _clientId},
        { "sub", _clientId },
        { "aud", "auth.uat.interop.pagopa.it/client-assertion"},
        { "purposeId", _purposeId },
        { "jti", jti.ToString() },
        { "userID", userId },
{ "userLocation", location },
{ "LoA", loa },
{ "dnonce", dnonce },
{ "iat", iat },
{ "exp", exp},
        { "digest", new Dictionary<string, object>
            {
                { "alg", "SHA256" },
                { "value", auditHash }
            }
        }
    };

ho calcolato lo sha256 del payload. (_payloadHash)
ho calcolato lo sha256 del JSON di richiesta (encodedBody)

Una volta ricevuto il TOKEN ho eseguito la chiamata al servizio C003 sono andato ad eseguire la chiamata al servizio

 string myUrl = "**https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C003-servizioVerificaDichGeneralita/v1/anpr-service-e002"**;
 WebRequest request = WebRequest.Create(myUrl);
 request.Method = "POST";
 request.ContentType = "application/json";
 request.Headers.Add("Authorization", "Bearer " + token);
 request.Headers.Add("Agid-JWT-Signature", _payloadHash);
 request.Headers.Add("Agid-JWT-TrackingEvidence", auditHash);
 request.Headers.Add("Digest", "SHA-256=" + encodedBody);

 using (Stream dataStream = request.GetRequestStream())
 {
     byte[] byteArray = Encoding.UTF8.GetBytes(jsonRequest);
     dataStream.Write(byteArray, 0, byteArray.Length);
 }

Tuttavia la chiamata non mi va a buon fine, ottengo un HTTP Error 400 con la seguente motivazione

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"a0684398-8231-11ee-bb73-005056ae1884"}

Potreste gentilmente indicarmi cosa non è corretto?

grazie

**Comment by TheVise1975** [comment]
Ho fatto una prova anche oggi, cambiando alcune cose sulla "segnature", ma ricevo ancora questo errore:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"20b2f97c-8459-11ee-b400-005056ae1884"}

**Comment by rglauco** [comment]
Il servizio C003 prevede dati diversi in `criteriRicerca`:

> - codice fiscale
> - nome
> - cognome
> - sesso
> - data di nascita
> - luogo di nascita: comune o stato
> oppure:
> - idANPR

quelli che stai usando adesso sono idonei, ad esempio, per il servizio C001, dove puoi interrogare per CF:

> - codice fiscale
> oppure:
> - nome
> - cognome
> - sesso
> - data di nascita
> - luogo di nascita: comune o stato
> oppure:
> - idANPR

Fai riferimento alle specifiche dei singoli servizi ANPR che trovi in PDND

**Comment by amollicone1982** [comment]
Il problema  dovuto al fatto che il token di integrity non è corretto
Token senza claim 'signed_headers'

Quello che possiamo dare è un esempio di client che implementa i profili di cui Anpr necessita.

https://github.com/italia/anpr/issues/3964

**Comment by TheVise1975** [comment]
> Il servizio C003 prevede dati diversi in `criteriRicerca`:
> 
> > * codice fiscale
> > * nome
> > * cognome
> > * sesso
> > * data di nascita
> > * luogo di nascita: comune o stato
> >   oppure:
> > * idANPR
> 
> quelli che stai usando adesso sono idonei, ad esempio, per il servizio C001, dove puoi interrogare per CF:
> 
> > * codice fiscale
> >   oppure:
> > * nome
> > * cognome
> > * sesso
> > * data di nascita
> > * luogo di nascita: comune o stato
> >   oppure:
> > * idANPR
> 
> Fai riferimento alle specifiche dei singoli servizi ANPR che trovi in PDND

Per caso hai un JSON di prova ?

**Comment by TheVise1975** [comment]
> Il problema dovuto al fatto che il token di integrity non è corretto Token senza claim 'signed_headers'
> 
> Quello che possiamo dare è un esempio di client che implementa i profili di cui Anpr necessita.
> 
> #3964

Io ho dato un'occhiata al client java, da cui ho provato a implementare la mia versione C#...ma se il java funziona (non ho testato) e il mio no...qualcosa vuol dire che l'ho persa per strada...

Esiste una versione declinata per il servizio C003?

Per quanto riguarda gli altri servizi del Ministero, esiste qualcosa che a fronte del codice fiscale mi restituisce i dati anagrafici e residenza?

Grazie
V.

**Comment by TheVise1975** [comment]
Una cosa tipo questa?

{
   "idOperazioneClient":"1",
   "criteriRicerca":{
      "codiceFiscale":"STTSGT90A01H501J",
      "cognome":"SOGGETTO",
      "nome":"SETTIMO",
      "sesso":"M",
      "datiNascita":{
         "dataEvento":"1990-01-01",
         "luogoNascita":{
            "comune":{
               "nomecomune":"ROMA",
               "siglaProvinciaIstat":"RM"
            }
         }
      }
   },
   "datiRichiesta":{
      "dataRiferimentoRichiesta":"2023-11-23",
      "motivoRichiesta":"PROT.NUM.12345",
      "casoUso":"C003"
   }

**Comment by amollicone1982** [comment]
es. C003

{

"idOperazioneClient": "0",

     "criteriRicerca": {
          "codiceFiscale": "DLDRND00R10C573B"
        },
        "verifica": {
          "generalita": {
            "codiceFiscale": {
              "codFiscale": "DLDRND00R10C573B"
            },
            "cognome": "DEL DEO",
            "nome": "ARMANDO",
            "sesso": "M",
            "dataNascita": "2000-10-10+02:00",
            "luogoNascita": {
              "comune": {
                "nomeComune": "CESENA",
                "codiceIstat": "040007",
                "siglaProvinciaIstat": "FC"
              }
            }
          }
        },
"datiRichiesta": {
"dataRiferimentoRichiesta": "2021-12-13",
"motivoRichiesta": "1",
"casoUso": "C003"
}
}



Ripeto che i problemi che hai sono dovuti ai token. Non sei ancora arrivato a problemi sul payload della richiesta. Il client java, se sostituisci tutte le info in pdnd.properties (clientid, purposeid del c003 etc.) e nel file test incolla una richiesta di C003 (vedi sopra) vedrai che funziona. Lo hanno provato già in tanti

**Comment by TheVise1975** [comment]
il mio file di ricerca è questo

{
"idOperazioneClient": "1",
 "criteriRicerca": {
      "codiceFiscale": "SGGPRM60A01H501A"
    },
    "verifica": {
      "generalita": {
        "codiceFiscale": {
          "codFiscale": "SGGPRM60A01H501A"
        },
        "cognome": "SOGGETTO",
        "nome": "PRIMO",
        "sesso": "M",
        "dataNascita": "1960-01-01+02:00",
        "luogoNascita": {
          "comune": {
            "nomeComune": "ROMA",
            "codiceIstat": "058091",
            "siglaProvinciaIstat": "RM"
          }
        }
      }
    },
"datiRichiesta": {
"dataRiferimentoRichiesta": "2023-11-29",
"motivoRichiesta": "1",
"casoUso": "C003"
}
}

**Comment by afrontera85** [comment]
Salve, 
relativamente al govway_id":"efa9b713-8f65-11ee-827e-005056ae5232"
l'errore che ci risulta è questo: 
Verifica ModI della richiesta fallita: Riscontrate 4 eccezioni.
Token non utilizzabile prima della data '2023-11-30_12:36:00.000'
Token creato nel futuro (data creazione: '2023-11-30_12:36:00.000')
[Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2023-11-30_12:35:57.000'
[Header 'Agid-JWT-TrackingEvidence'] Token creato nel futuro (data creazione: '2023-11-30_12:35:57.000')

**Comment by TheVise1975** [comment]
Ok.... direi che qualcosa ho portato  a casa...


{"listaSoggetti":{"datiSoggetto":[{"infoSoggettoEnte":[{"chiave":"Verifica generalita'","id":"1002","valore":"S"}]}]},"idOperazioneANPR":"59512789"}

**Comment by amollicone1982** [comment]
Direi di si. Ottimo
Buona giornata
