### ISSUE TITLE
"X-Global-Transaction-ID": "3f7e3e2d6554a3de4596294d"

### ISSUE THREAD

**Issue by andpra70** [italia/anpr#4235]
Buongiorno stiamo integrando su PDND il servizio C020-servizioAccertamentoResidenza - InteroperabilityInvalidRequest .

Invocando il servizio C020 con:

curl -k -X POST 
-H "User-Agent: python-requests/2.31.0" 
-H "Accept-Encoding: gzip, deflate" 
-H "Accept: */*" 
-H "Connection: keep-alive" 
-H "Content-Type: application/json" 
-H "Content-Encoding: UTF-8" 
-H "Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMC1zZXJ2aXppb0FjY2VydGFtZW50b1Jlc2lkZW56YS92MSIsInN1YiI6IjM4NGVmOTExLTA3YmEtNDE1MC04OTk5LWJhNmU5YWIzMTc5ZCIsIm5iZiI6MTcwMDA0NTc4OSwicHVycG9zZUlkIjoiMGY4MmJlODYtMjBjZC00YjFkLTk3ZWYtYTE3M2M4MjA0YjQ4IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzAwMDQ2Mzg5LCJpYXQiOjE3MDAwNDU3ODksImNsaWVudF9pZCI6IjM4NGVmOTExLTA3YmEtNDE1MC04OTk5LWJhNmU5YWIzMTc5ZCIsImp0aSI6Ijc4MmE4ZjY3LTY3OTMtNGYzOS1iMTU0LTE3OTFjYzMxMTEyYyJ9.WJPVsnlrTOa8N5Nab01N4WL7Qu-Zuy5P68avndSZkVDwPNy4zHjG4XP1afK-9y765CLm0JbkB68H2pU6rm_-LpJvDOlvl1HdPXoMcCdO0Jsmidk8zzLdaVN-i3aBmRnoLpkWbSgc41-EUo07dvFXMkz5HsXosU3lsp_Kj3-B_xOeZwSCWfCRz62BeX7rQcLy0mlH_dCp3r6RuSxb1lOgErh1j4-BoCsZCDi3YkqtEcAKrAB1hloKYXCFi9ayNC-CEpgXGToH_WBzYnuOdfvPYm_gAEM1nsyBz_kB5m0FJvpaVNEnDIIp9SBtlIw8LcoQ5uNhik4lTcBQBeXsxDXvQQ" 
-H "Agid-JWT-Signature: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBPQ2JnVm4zZDVHV2xFZ3FySVVWdzBySlJETEhEVzJTc1dmSXhKRkdSNFEiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMC1zZXJ2aXppb0FjY2VydGFtZW50b1Jlc2lkZW56YS92MSIsImlhdCI6MTcwMDA0NTc5MCwiZXhwIjoxNzAwMDQ5MzkwLCJqdGkiOiJlMmU1ZTU5MS1lYjlhLTQxYTUtYjM2Yy1hNjVmN2JhNWEzMGMiLCJzaWduZWRfaGVhZGVycyI6W3siQ29udGVudC1UeXBlIjoiYXBwbGljYXRpb24vanNvbiJ9LHsiQ29udGVudC1FbmNvZGluZyI6IlVURi04In0seyJEaWdlc3QiOiJTSEEtMjU2PWRUeWQzdEFYS2R5eGdQbEdQYTRkRzNnMnBzbXBNSE1RckI0SXhRdUluRmVQdUhkejE5Q2RjMlpxTlUtcENmR1RqbFVxeFlGOXBwWnVsbElaZUdZZ0JGTzEwZzZRZlMyZlYzNzNVMmNkT0s5Q045QTQtZ1lyelhjMFlLaUMyTHg0R2FQS2dER2FOWUVFVmRkeDJFanlLYkUwOXJhbDNTUlVxQ0ZDcHowb1MyblhBZHZWSnlybG1jMThxcjFfcUlnMUdYQXBLV3BicUdPX0hXcC1vVktEeGxqcHJMMmRyLUhYWU42ZjdsYllsTGVSaEtoOUdQdTlVUndkaUVYZ2FlcDZQOUZxdncyMV92WUZPOS1RU0p0RVpvR3hxOXNpdXJOOExqN0JVN3k1Vk9YQl93bTJ0QVdWZS1Sakx5a0FpS3g3Wk5YVV9vMGRpM0lQU0NUdm9ua1Z1dz09In1dfQ.Tb_nopJb0ECETUOQ4fAEruM7Y57ZzfhuIzAlvULXgdT3m_tgEoYtyOz4HRn6svK0xWeQtpF5hiCcT5VbNgg9jX2V6FVnDNbEeQXPFVPqDQefuB1LDvUgq1CWmKjCsC77zUKF5yoQhG3Zk6tnBcEHMC12IJcSrPk_tT64wbDh5P8hQJxw_MyoYFgzcMl9105mMmwdl_49k2x5tbu7rOolzeHhBcqy84Kq63ha3HgsIp71e4Xko-io_Z4y_KVAk9Nf1FW3-lrzBZ2XlOKSgTQfVbooktm0K3ZhaB06tIgbcq_ufxiKbq7kE-q4owGVl4nZwtmdNh7wrqqfon5sXGTqQw" 
-H "Agid-JWT-TrackingEvidence: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBPQ2JnVm4zZDVHV2xFZ3FySVVWdzBySlJETEhEVzJTc1dmSXhKRkdSNFEiLCJ0eXAiOiJKV1QifQ.eyJkbm9uY2UiOjI0OTUyMjQzODQ4NDU1LCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMC1zZXJ2aXppb0FjY2VydGFtZW50b1Jlc2lkZW56YS92MSIsImlzcyI6IjM4NGVmOTExLTA3YmEtNDE1MC04OTk5LWJhNmU5YWIzMTc5ZCIsInB1cnBvc2VJZCI6IjBmODJiZTg2LTIwY2QtNGIxZC05N2VmLWExNzNjODIwNGI0OCIsImlhdCI6MTcwMDA0NTc5MCwiZXhwIjoxNzAwMDQ5MzkwLCJqdGkiOiJiNGEzNDViZi1mZmJhLTQ2YmItYjI0Yy1kYzFhYWQ4NmUzODMiLCJ1c2VySUQiOiJQUkRORFI3MFQxMUE5NDRBIiwidXNlckxvY2F0aW9uIjoiUDAwMSIsIkxvQSI6IjEifQ.RFzm-B1r4Z3jF3k-ptbLS5-MiVXj4e_UIuUgVxGoYGmV7L4FiA_FBUD8h4kFrUWbo5GQrql1Li_9s90OvsDVciS45AV2-7gDG6x9Wi7QQoAACtUZ2yVPGT9TiKmAmDjcnmRJPTbyvCNC0msBFdxbb_ovbvsuvHR3d7n1hUaMpi-PBCaHtsFSlaDulmgCWFKrgOEcumO8c_e8LqLS7OW3-A2gVIWItphAI_xfxV-wy8EcuUHWr9Z9zZYZUkWnO4Wk-LRhbk57-OTp6EuVBWFCfaZzoXse_JAjML2o_St3tu9cTS9b6L5lKpvbufCsN0KwH3oz5biQlfhhXLj38p1L7Q" -H "Digest: SHA-256=dTyd3tAXKdyxgPlGPa4dG3g2psmpMHMQrB4IxQuInFePuHdz19Cdc2ZqNU-pCfGTjlUqxYF9ppZullIZeGYgBFO10g6QfS2fV373U2cdOK9CN9A4-gYrzXc0YKiC2Lx4GaPKgDGaNYEEVddx2EjyKbE09ral3SRUqCFCpz0oS2nXAdvVJyrlmc18qr1_qIg1GXApKWpbqGO_HWp-oVKDxljprL2dr-HXYN6f7lbYlLeRhKh9GPu9URwdiEXgaep6P9Fqvw21_vYFO9-QSJtEZoGxq9siurN8Lj7BU7y5VOXB_wm2tAWVe-RjLykAiKx7ZNXU_o0di3IPSCTvonkVuw==" 
-H "Content-Length: 210" 
-d '{"idOperazioneClient": "100", "criteriRicerca": {"codiceFiscale": "TTRPNN00R50F839W"}, "datiRichiesta": {"dataRiferimentoRichiesta": "2023-11-15", "motivoRichiesta": "Test motivo richiesta", "casoUso": "C020"}}' 
'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1/anpr-service-e002' 

si verifica il seguente errore:

{ "type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, "detail": "Unknown API Request", "X-Global-Transaction-ID": "3f7e3e2d6554a3de4596294d" } 

Potreste gentilemente darci supporto ?

**Comment by nahid998** [comment]
avete per caso risolto?

**Comment by nahid998** [comment]
perché anch'io sono nello stesso problema.
{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "7dbb991665707867254d6f6d"
}

**Comment by afrontera85** [comment]
Buongiorno,
quì trovate un esempio di client che implementa i profili di cui Anpr necessita:
#https://github.com/italia/anpr/issues/3964
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties.
Per eventuali dettagli su errori presi basta che ci forniate il govway_id e verifichiamo tranquillamente
