### ISSUE TITLE
Errore C021-servizioAccertamentoStatoFamiglia-approvazione_automatica

### ISSUE THREAD

**Issue by andpra70** [italia/anpr#4237]
Buongiorno 

comune Valsamoggio ambiente di test , stiamo integrando il servizio C021 ma riscontriamo dei problemi.

Allego quanto serve per la verifica:

#!/bin/bash

curl -k -X POST 'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C021-servizioAccertamentoStatoFamiglia/v1/anpr-service-e002' \
 -H 'Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAwMS1zZXJ2aXppb05vdGlmaWNhL3YxIiwic3ViIjoiMDEwNGFjNzUtMTUwZi00ODRmLWE1MWItZGE3OTVhODEwYzliIiwibmJmIjoxNzAwMTUxNzM4LCJkaWdlc3QiOnsiYWxnIjoiU0hBMjU2IiwidmFsdWUiOiI5MzNlODU5N2UyZWM1NWQzM2JmY2U1M2E2MTQyMDRlMTY3YmViMzFlNzAzODU3ZjAzYTE4ZDZiMGFiMDYyNGRhIn0sInB1cnBvc2VJZCI6ImZmMjg0YmEwLTVmODktNGY3MS1iYTFkLTk4MmIwZWYyMjkwMyIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTcwMDE1MjMzOCwiaWF0IjoxNzAwMTUxNzM4LCJjbGllbnRfaWQiOiIwMTA0YWM3NS0xNTBmLTQ4NGYtYTUxYi1kYTc5NWE4MTBjOWIiLCJqdGkiOiI1Y2EwNjk1OC0yMDk2LTQzYTgtODJhYi00OGRlY2YwMzRlZWQifQ.FRWESzo1BsjKVxTHhe7DcuU2QS1YIZPmykSm-axPhGNY66-vXgwEilpF7HqggiGGVBPVh8AcppwXLSLMHn8arKsTiXWhadG2LFj2_qyzTF8sLq0RVrGA6u1E13kT72BfRK875ZMdMNg9R5LnKl4QLj5DBjSNcfVbPU0q5X_pgwe1ktrV8Ql8vRdCW_R_KtZ4KPHDcvgmgx6Aoi5rkgxgVheHhpy0lJ-eAMHC0dQ2vb3qMqflj3QKzvNm-pWbcaSlgBo-_kniuIBrMccZZ77UWed1X_7-hggaUw6vWyJ6hMgZJ_5ZXl-zTiXg8WHJY5mewDjggvZZPrfhOeQ7RkCUyg' \
 -H 'Agid-JWT-Signature: eyJ0eXAiOiJKV1QiLCJraWQiOiJ6VjNXOVhNMUdaa283QXdRQ1UwYVFaOEl5U3F0aDhfaTlPZnkzc3RaV0xvIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMS1zZXJ2aXppb0FjY2VydGFtZW50b1N0YXRvRmFtaWdsaWEvdjEiLCJzdWIiOiIwMTA0YWM3NS0xNTBmLTQ4NGYtYTUxYi1kYTc5NWE4MTBjOWIiLCJuYmYiOjE3MDAxNTE3MzksImlzcyI6IjAxMDRhYzc1LTE1MGYtNDg0Zi1hNTFiLWRhNzk1YTgxMGM5YiIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PU8xTThrZDQrOFByV0xHMHJZSjZwRFFZM2plUm54Ym1wRWFhMktoRnlTS2M9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dLCJleHAiOjE3MDA3NTE3MzksImlhdCI6MTcwMDE1MTczOSwianRpIjoiOGEwMWY1NDUtOGE2OS00Y2ViLTgzODQtNjEyZjA4ZDhlNWM5In0.kutCO2ytzEyA1BbZto5IFPzey1qPiuqSw36sEDcKNI-RQm2vojHiiPuVg82n8TUob1lEgb0mY9HBPDgxYsigN5Q0Wgth5WBJSkko8TK0Bgz9PZNo6NlkvYTxfMF977HYL2rEFo8nx2s95KABF26_oRKJudnegPtG8r5IXP9rKiV-NkrmSmIrLNOIb7Q4-ia6v2QvkRGxV0k2Ce4MtLuGMv7Y09xWCHAhwljVsfxhMcO32ba5IY1epgfKFEIo69y_2mllHt_TwGTZA2S4BWv_3YfQ94I7BOZgG5Fvtn_vdh_G78cX7YA84wGhhLvIIDg6sKHKpjjL93BExCoztpuz-Q' \
 -H 'Agid-JWT-TrackingEvidence: eyJ0eXAiOiJKV1QiLCJraWQiOiJ6VjNXOVhNMUdaa283QXdRQ1UwYVFaOEl5U3F0aDhfaTlPZnkzc3RaV0xvIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMS1zZXJ2aXppb0FjY2VydGFtZW50b1N0YXRvRmFtaWdsaWEvdjEiLCJzdWIiOiIwMTA0YWM3NS0xNTBmLTQ4NGYtYTUxYi1kYTc5NWE4MTBjOWIiLCJuYmYiOjE3MDAxNTE3MzgsInB1cnBvc2VJZCI6ImZmMjg0YmEwLTVmODktNGY3MS1iYTFkLTk4MmIwZWYyMjkwMyIsImlzcyI6IjAxMDRhYzc1LTE1MGYtNDg0Zi1hNTFiLWRhNzk1YTgxMGM5YiIsInVzZXJMb2NhdGlvbiI6IjI2LjIuMTIuMjMiLCJleHAiOjE3MDA3NTE3MzgsImRub25jZSI6IjEzNjc1NjMzOTkzMjgiLCJ1c2VySUQiOiJTVFRTR1Q5MEEwMUg1MDFKIiwiaWF0IjoxNzAwMTUxNzM4LCJqdGkiOiIxNGMzMTlmOS1kYzJmLTQ2NTUtYmEwMC03MDIzYzA0MzBjNDkiLCJMb0EiOiJTUElEIn0.RkfYrmlk1pYDE2LCbHg1q3hWgzR-TaBhmAXN_2PXbCIczMZOTBo8kBb1iZlMRjLs2kp7nqU5J54GA1abzSwPTD-W0qcY3xbd-Ag2wuqtVY2m0NFgWCIaEEfBQAajOR99h74G8cBTAajMV_yfJbBEnMRPkbOcqGsBoYl0HYqhIVChCV_5YFIh8jSUt4T42TZGIEsV3z5jZs868dfHXVJHXtJMjAp5OH_1OePWHs2UjsSx_nw0M1ZkIzRUkacR8d6TC9zkm1YUePBpbicaHtNVfcvkxXy-8ldpiBBEGLOH91fD-kxdjRRVLz5IrxFhR1JZDu42PbA-kKbxvAmd_wLxTQ' \
 -H 'Digest: SHA-256=O1M8kd4+8PrWLG0rYJ6pDQY3jeRnxbmpEaa2KhFySKc=' \
 -H 'Content-Type: application/json' \
 -d '{
  "idOperazioneClient": "0",
  "criteriRicerca": {
    "codiceFiscale": "STTSGT90A01H501J"
  },
  "datiRichiesta": {
    "dataRiferimentoRichiesta": "2023-11-16",
    "motivoRichiesta": "1",
    "casoUso": "C021"
  }
}' 

risponde con:

{"type":"https://govway.org/handling-errors/403/AuthorizationTokenDeny.html","title":"AuthorizationTokenDeny","status":403,"detail":"Insufficient token claims","govway_id":"11653457-8496-11ee-84f2-005056ae5232"}
Nov 16, 2023 5:22:19 PM com.municipia.pdnd.anpr.c021.C021 c021
INFO: {
  "govway_id" : "11653457-8496-11ee-84f2-005056ae5232",
  "detail" : "Insufficient token claims",
  "type" : "https://govway.org/handling-errors/403/AuthorizationTokenDeny.html",
  "title" : "AuthorizationTokenDeny",
  "status" : 403
}

Lo stesso codice impigato verso i servizi c020 e c001 invece funziona correttamente.
 
Mentre per il C021 viene tornato l'errore sopra riportato.

Chiediamo cortesemente darci supporto se possibile

**Comment by amollicone1982** [comment]
L'errore segnalato è dovuto al fatto che state richiamando C021 con voucher pdnd che contiene il purposeid del C001

**Comment by amollicone1982** [comment]
Quello che possiamo dare è un esempio di client che implementa i profili di cui Anpr necessita.

https://github.com/italia/anpr/issues/3964
