### ISSUE TITLE
DATI ELETTORALI - ERRORE WS5011  

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#4238]
Buonasera,
COMUNE CASERTA 061022
Collegio plurinominale e collegio uninominale per la Camera dei deputati" non corrispondente alla tabella di riferimento
codice Errore Anomalia EN527
idOperazioneANPR 1516394434

Potremmo avere questa tabella di riferimento o almeno le nostre codifiche 
Grazie

**Comment by amollicone1982** [comment]
si certo. Puo' inviarla
