### ISSUE TITLE
EMISSIONE CERTIFICATI AD ENTI PUBBICI/PUBBLICHE AMMINISTRAZIONI

### ISSUE THREAD

**Issue by SaraValleferro** [italia/anpr#424]
Buongiorno, sono Sara Valleferro, responsabile dell'Ufficio Anagrafe Comune di Cortina d'Ampezzo.

Riceviamo spesso richieste di emissione certificazione anagrafica da parte di Procura/Agenzia Entrate/ altri Comuni/Forze dell'ordine. In sede di emissione del certificato viengono richiesti i dati del Richiedente, ma il sistema non permette di inserire i dati dell'ente, ma solo i dati di una persona fisica, con riferimenti dei dati del documento d'identità. Dobbiamo quindi richiedere ogni volta il documento d'identità del soggetto (Funzionario/dipendente/cancelliere/agente) che fa materialmente la richiesta? Oppure c'è il modo di indicare genericamente L'ente che fa la richiesta?

Cordiali Saluti
Sara valleferro

**Comment by gcarbonin** [comment]
Riporto il paragrafo delle specifiche ANPR ( https://www.anpr.interno.it/portale/documents/20182/50186/MI-14-AN-01+SPECIFICHE+DI+INTERFACCIA+WS_17_11_2017.pdf/5a2a56ad-5974-4520-8f1b-6fad437dd749)
dove si descrive la soluzione al suo problema:

17.1.5.6	Certificati richiesti da Enti
Occorre specificare il valore 3 nel campo TipoRichiedente e nei campi riservati al documento di riconoscimento:

- nel campo che normalmente contiene il documento, il nome dell’ente e gli estremi della richiesta;
- nel campo che normalmente contiene la data di rilascio, la data della richiesta.

Devono comunque essere compilate le generalità della persona che richiede il certificato per conto dell’Ente.

**Comment by SaraValleferro** [comment]
Buongiorno, torno a chiedere chiarimenti sulla questione. Quando è stato il momento di richiedere i dati dei funzionari delle amministrazioni pubbliche e istituzioni che via via hanno richiesto certificati per conto dell'ente per il quale lavorano, più volte ho ricevuto risposte seccate in quanto i funzionari non hanno ritenuto corretto dover comunicare le generalità, agendo per conto dell'ente e non per loro interesse personale.
Chiedo pertanto se resta ancora valida la necessità di compilare le generalità della persona che richiede il certificato per conto dell'ente e esattamente quali dati minimi vengono richiesti. Bastano nome e cognome o sono necessari altri dati (es. C.F. data e luogo di nascita). Lo richiedo perchè non so bene come spiegare tale necessità agli Enti che richiedono i certificati, stante le polemiche che hanno sollevato.
Loro sostengono che dovrebbe bastare il nome dell'Ente senza dover specificare null'altro.
Grazie
Sara Valleferro
Comune Cortina d'Ampezzo
