### ISSUE TITLE
integrazione liste elettorali su anpr: errore EN560

### ISSUE THREAD

**Issue by demoserraricco** [italia/anpr#4242]
Buongiorno, in esito all'invio delle liste elettorali,, ho ricevuto il file con n. 8  anomalie errore EN556.  Questo tipo di anomalia preclude la possibilità di richiedere il contributo?

**Comment by amollicone1982** [comment]
Queste anomalie non precludono la richiesta di contributo anche perchè si tratta di anoamlie non dipendenti strettamente dal suo comune ma da un altro che non ha effettuato la cancellazione
