### ISSUE TITLE
C020 - Dati carta indentita

### ISSUE THREAD

**Issue by andpra70** [italia/anpr#4243]
Buongiorno, 
   contattiamo dal Comune di Valsamoggia, perche`vorremmo sapere con che servizio ottenere i dati della carta di identita`.

Inoltre ci servirebbe anche la famiglia e`corretto usare il C021 ? 

Potreste fornire un esempio di interrogazione per il C021 con un caso di test che torni la famiglia con i componenti.

**Comment by amollicone1982** [comment]
Non è previsto nessun servizio anpr su pdnd che restituisce la carta d'identità

Per la famiglia e`corretto usare il C021:

 {
   "idOperazioneClient": "11",
    "criteriRicerca": {
      "codiceFiscale": "KPPMTT20A16A089N"
    },
    "datiRichiesta": {
      "dataRiferimentoRichiesta": "2023-06-09",
      "motivoRichiesta": "1",
      "casoUso": "C021"
    }
  }
