### ISSUE TITLE
Problema Richiesta di contributo "non è stato possibile reperire i dati del comune"

### ISSUE THREAD

**Issue by baldissinn** [italia/anpr#4245]
Apro ticket a nome del COMUNE DI RIVA DEL PO (FERRARA) 038029

Dopo aver terminato le procedure di inserimento dei dati di sezione ed elettori ed avute le due spunte sulla pagina di richiesta di contributo, verificato il numero di elettori ho aggiunto la terza spunta.
Cliccando su procedi il sistema mi ha restituito l'errore "Non è stato possibile reperire i dati del comune"
Il Comune di Riva del Po deriva dalla fusione di due comuni comuni in data 01/01/2019 (Ro e Berra)
E' possibile risolvere la situazione?

Lascio i riferimenti del Responsabile del servizio del comune Pollastri Michele 3470553594 mpollastri@comune.rivadelpo.fe.it

**Comment by baldissinn** [comment]
Aggiungo che anche il comune di Pieve del grappa ha lo stesso errore.

Lascio i riferimenti della Responsabile del servizio del comune Zamboni Linda 3491403962 elettorale@comune.pievedelgrappa.tv.it

**Comment by lorbia** [comment]
> Apro ticket a nome del COMUNE DI RIVA DEL PO (FERRARA) 038029
> 
> Dopo aver terminato le procedure di inserimento dei dati di sezione ed elettori ed avute le due spunte sulla pagina di richiesta di contributo, verificato il numero di elettori ho aggiunto la terza spunta. Cliccando su procedi il sistema mi ha restituito l'errore "Non è stato possibile reperire i dati del comune" Il Comune di Riva del Po deriva dalla fusione di due comuni comuni in data 01/01/2019 (Ro e Berra) E' possibile risolvere la situazione?
> 
> Lascio i riferimenti del Responsabile del servizio del comune Pollastri Michele 3470553594 [mpollastri@comune.rivadelpo.fe.it](mailto:mpollastri@comune.rivadelpo.fe.it)

E' possibile ricontattare il comune di Riva del Po e chiedere di riprovare adesso il problema dovrebbe essere risolto. Attendiamo qui un riscontro sull'esito positivo.

**Comment by lorbia** [comment]
> Pieve del grappa

E' possibile ricontattare il Comune e chiedere di riprovare adesso il problema dovrebbe essere risolto.

**Comment by baldissinn** [comment]
> > Pieve del grappa
> 
> E' possibile ricontattare il Comune e chiedere di riprovare adesso il problema dovrebbe essere risolto.

Pieve del Grappa ok, grazie
