### ISSUE TITLE
SUL PORTALE SCOMPARSA VOCE RICHIESTA CONTRIBUTO SOTTO MENU' AMMINISTRAZIONE

### ISSUE THREAD

**Issue by StefanoDotti** [italia/anpr#4249]
Stessa problematica riscontrata questa mattina per comuni di Como e Cucciago (Co)
Effettuato accesso con smart card dell'ALS
Grazie
Stefano Dotti
Halley Lombardia

**Comment by sfmodena** [comment]
Buongiorno,
anche a Modena accedendo con la smartcard dell' ALS la richiesta contributo non è più visibile. E' diventata fruibile solo entrando con la smartcard del Sindaco (vedi issue #4229)?

Grazie, saluti
Sonia Fiorini

**Comment by StefanoDotti** [comment]
Grazie. Da Como mi hanno confermato che con la smartcard del Sindaco la scelta è visibile.
Saluti
Stefano Dotti

**Comment by Hdemografici** [comment]
Aggiungo che non è data possibilità di farne richiesta neanche con l'utenza dell'ALS. 
Sottolineo l'importanza di ripristinare le precedenti abilitazioni considerando che non tutti i comuni hanno disponibilità della smartcard dell'attuale Sindaco ed era uno strumento utilissimo a verificare che tutte le attività necessarie ad avanzare la richiesta di contributo fossero state epletate.

**Comment by CGIRELLI-HUB** [comment]
Anche nostri comuni si trovano nella stessa situazione, molti hanno già inviato la richiesta dal proprio profilo. Entrando con smart card del sindaco la richiesta verrà visualizzata anche se fatta da un'altro utente? O dovranno rifarla con smart card del sindaco?
Purtroppo non tutti hanno guardato e letto con attenzione la guida operativa e avendo la possibilità di farla anche da smart card di ALS l'hanno eseguita. Si prega di dare una risposta quanto prima anche sui termini del caricamento (se ci sono) di tali richieste. 
Grazie 
Cordiali saluti
Cinzia Girelli

GPI SPA
