### ISSUE TITLE
Comune di Codigoro - XML Subentro

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#425]
ambiente di PRE-SUBENTRO - comune di Codigoro FE

buongiorno.

abbiamo tentato l'upload del file di subentro per il comune di Codigoro.
il caricamento va in KO x una discordanza tra i numeri presenti in testata e quelli calcolati.
(dati che a noi tornerebbero con i valori tracciati al momento dell'elaborazione)

alcuni dubbi:
1. l'elaborzione è andata in KO pur non avendo caricato ancora il file dell'AIRE?
... di solito non resta IN ELABORAZIONE...?
2. abbiamo controllato su "monitoraggio anomalie", ed in corrispondenza del "numero schede con dati errati", a fronte dei 6 soggetti evidenziati viene aperto un file 11995 record.

è possibile ci sia qualche problema/disallineamento sull'ambienti di Codigoro?
... meglio aspettare il file AIRE ed importare tutto di nuovo?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
ho visto adesso che il csv che viene aperto è datato 08/06/2017...

**Comment by mttfranci** [comment]
Buongiorno, abbiamo analizzato il vostro invio, ecco alcuni chiarimenti : 
I file del subentro vengono elaborati separatamente man mano che arrivano, ma il subentro si può concludere solo se tutti i file arrivano (AIRE compreso) senza errori bloccanti.
Un errore bloccante su un qualsiasi file porta al fallimento per intero del subentro.
In ambiente di test e presubentro vengono mostrati alcuni dei file CSV dell’ultimo subentro avvenuto con successo (che per il comune di Codigoro era a giugno)
In ambiente di test e cpresubentro, ma non in produzione, è possibile compiere operazioni prima di subentrare, ma per definizione il subentro dove essere la prima operazione del comune. Nel caso specifico è stata richiesta una cancellazione per il comune il 18 Novembre, ma poi il 20 sono state eseguite due operazioni di iscrizione. Quindi all’invio del file APR del subentro hanno fallito i controlli che verificano la congruità tra totale popolazione caricato e dichiarato. Pertanto se si eseguono operazioni è sempre necessario richiedere la cancellazione del comune. [al momento in cui scriviamo, è avvenuta una cancellazione automatica in seguito alle anomalie di ieri, quindi è possibile inviare nuovamente i file di subentro anche adesso]
Un’ultima nota, queste casistiche non possono verificarsi in ambiente di produzione, ma solo in test comuni e presubentro dove alcuni vincoli sono rilassati al fine di facilitare i test da parte dei comuni.

**Comment by AMonopoliADS** [comment]
buongiorno.
abbiamo visto che eseguendo nuovamente l'upload degli stessi file, aggiunto quello dell'aire, la fase di subentro è andato a buon fine.
grazie
