### ISSUE TITLE
C001–servizioNotifica vs C002-servizioComunicazione

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4258]
Quali sono le differenze tra i servizi C001–servizioNotifica e C002-servizioComunicazione ?
Dalla loro descrizione mi sembrano identici.

grazie

**Comment by amollicone1982** [comment]
La differenza sta nella finalità di utilizzo. C001 va usato per recuperare la residenza ai fini di una notifica mentre C002 recupera la residenza per finalità di comunicazione

**Comment by SimonePadovan** [comment]
Grazie per la risposta, scusami se insisto, ma quale é la differenza tra notifica e comunicazione ? grazie

**Comment by SimonePadovan** [comment]
Ah ok, quindi per la comunicazione puó essere tornata anche solo una email PEO, mentre per la notificazione deve essere tornata la pec dichiarata in INAD ? grazie

**Comment by amollicone1982** [comment]
si, comunque la differenza è la formalità o meno
