### ISSUE TITLE
Cie per non residenti

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#426]
Un cittadino residente ad Altamura (comune subentrato) si è recato presso il comune di Milano per ottenere la CIE. 
La collega del comune di Milano ci ha contattato riferendoci che è impossibilitata a prenotare la CIE perché  il cittadino non è presente in INA (messaggio di errore da Cieonline).
Ma è possibile che i cittadini in ANPR possano avere questo inconveniente?
Sembrerebbe una beffa...........

Si resta in attesa di chiarimenti.

**Comment by gcarbonin** [comment]
Ci sono comuni subentrati che emettono giornalmente la CIE. Mi invii sulla mail personale i dati di questa persona e verifico con il Ministero dell'Interno quale e' il problema

**Comment by Finalmentesubentrati** [comment]
Qual è la mail?

**Comment by gcarbonin** [comment]
Il caso specifico è stato verificato: per la persona in questione  è stata emessa una CIE che è al momento in spedizione. La richiesta risale al 24 novembre; probabilmente c'è stato un errore in fase di inserimento del codice fiscale.
