### ISSUE TITLE
Mancata email per validazione indirizzo email

### ISSUE THREAD

**Issue by Federicabirilli** [italia/anpr#4261]
Questa mattina dovevo provvedere ad inviare una richiesta per il cambio di residenza, ma sono impossibilitata ad inviarla finchè non valido il mio indirizzo email. Ho inserito correttamente il mio indirizzo email nel campo, ma non mi arriva mai l'email nella casella di posta per validare l'indirizzo. Ho controllato anche in spam e non c'è, come posso fare?

**Comment by gppbarone** [comment]
Buonasera, abbiamo analizzato la segnalazione e abbiamo riscontrato che l’email è arrivata 2 volte ed è anche validata.
Può verificare per favore?<br>Grazie,
Assistenza ANPR

**Comment by Federicabirilli** [comment]
Buonasera,sì confermo, è così. È arrivata molto in ritardo, vi ho contattati perché leggendo di casi simili pensavo non arrivasse mai.Vi ringrazio,Federica BirilliIl giorno 28 nov 2023, alle ore 17:55, gppbarone ***@***.***> ha scritto:﻿
Buonasera, abbiamo analizzato la segnalazione e abbiamo riscontrato che l’email è arrivata 2 volte ed è anche validata.
Può verificare per favore?Grazie,
Assistenza ANPR
