### ISSUE TITLE
PDND - servizi in produzione

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4269]
Quando é previsto di allineare i servizi presenti in produzione con la versione (piú nuova) presente in collaudo della PDND ?

**Comment by amollicone1982** [comment]
Buongiorno,
cosa intende? l'ambiente di collaudo è già allineato con la produzione

**Comment by SimonePadovan** [comment]
Intendo dire che in produzione ad esempio é presente la versione di C015-servizioAccertamentoGeneralita-approvazione_automatica, mentre in collaudo é presente la versione 3 dello stesso servizio e presenta delle differenze

**Comment by amollicone1982** [comment]
che differenze vede?
La versione su pdnd non indica una versione differente lato servizi  ma semplicemente il fatto che un servizio è stato modificato piu' o meno volte sulla pdnd per cause varie (la piu' frequente è l'aggiornamento degli attributi certificati che non hanno niente a che fare con i servizi sottostanti)

**Comment by SimonePadovan** [comment]
La gestione dello schema dati TipoDatiSoggettiEnte é diversa in produzione (datiDecesso)

**Comment by amollicone1982** [comment]
Ha ragione, la versione corretta è quella di collaudo. 
Comunque lato servizi di backend è tutto allineato.
Il problema che vede è solo sullo yaml di produzione che non è corretto e che corregerò a breve
