### ISSUE TITLE
[5001] msg. "Operazione non effettuabile"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#427]
ambiente di PRODUZIONE - comune di Faenza (RA) - idOperazioneComune 2017000565 / 2017000567

in entrambi i casi si tratta di variazione di rapporto di parentela all'interno del nucleo.
per tutte e due le comunicazioni, anche tentando ripetizioni di invio successive, scatta il messaggio
999 - E - operazione non effettuabile

Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
Nella richiesta 5001 sono presenti soggetti duplicati nei tag <elencoSoggettiFamiglia>
