### ISSUE TITLE
revisione semestrale aggiornamento dati anpr

### ISSUE THREAD

**Issue by claudioarca** [italia/anpr#4275]
Buongiorno, oggi abbiamo effettuato la chiusura della revisione semestrale in cui sono stati iscritti 16 nuovi elettori. Nelle comunicazioni di invio abbiamo avuto esito positivo su tutto quanto abbiamo inviato. Interrogando l'elettore/gli elettori ritroviamo soltanto il flag elettore 'S' senza i dati relativi alla lista elettorale di appartenenza.
Riporto di seguito il riferimento alla comunicazione inviata:
COMUNICAZIONE DA PARTE DEL COMUNE DI ASSORO 
Richiesta5010
idOperazioneComune 0000013205

Volevamo capire dove sta il problema.
Grazie

**Comment by frmariani** [comment]
La consultazione elettorale deve essere effettuata con il profilo di ufficiale elettorale, altrimenti vengono visualizzati i dati elettorali anagrafici.
Con quale profilo state effettuando la consultazione?

**Comment by claudioarca** [comment]
Ok grazie

 

Cordiali saluti
Claudio Arcà

E-mail: ***@***.*** ***@***.***> 
Web Site: https://golemnet.it <https://golemnet.it/> 

------------------------------------------------


Via Dante Ruffini, 22 A - 26100 Cremona (CR)

Tel. 06.95995160 - Fax 0958880135

P. iva e C.F. 09106071005

e-mail: ***@***.*** ***@***.***> 

 

Da: frmariani ***@***.***> 
Inviato: martedì 5 dicembre 2023 10:54
A: italia/anpr ***@***.***>
Cc: claudioarca ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] revisione semestrale aggiornamento dati anpr (Issue #4275)

 

La consultazione elettorale deve essere effettuata con il profilo di ufficiale elettorale, altrimenti vengono visualizzati i dati elettorali anagrafici.
Con quale profilo state effettuando la consultazione?
