### ISSUE TITLE
Problema comunicazione con Agenzia Entrate

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#4276]
Comune di Modena

Buongiorno, tentando di iscrivere due soggetti riceviamo l' errore 

codiceErroreAnomalia: AEE97
tipoErroreAnomalia: E
testoErroreAnomalia: Operazione non effettuabile 
codiceErroreAnomalia: EN527
tipoErroreAnomalia: E

Da stamattina non riusciamo nemmeno ad accedere a Puntofisco, nè dal vecchio link nè dalla nuova pagina della scrivania (dalla quale invece si accede senza problemi ai portali di amministrazione Vitruvio e Monade). 
Per cortesia potete confermarci se ci sono problemi di comunicazione con Agenzia Entrate? 

Grazie, saluti
Sonia Fiorini

**Comment by UpiTorino** [comment]
Ci accodiamo: anche a Torino impossibile accedere a SIATEL, oltre ad avere numero risposte 097

Anna Maria AIMONE
UPI - Torino

**Comment by sfmodena** [comment]
Comune di Modena

Buongiorno,
non so se può essere utile, noi abbiamo dovuto mettere in white list gli indirizzi dell' Agenzia Entrate sul firewall.

Sonia Fiorini
