### ISSUE TITLE
[764] Problema di mancato certificato di stato civile 

### ISSUE THREAD

**Issue by ChiaraC8** [italia/anpr#4278]
Mancata selezione di certificazione stato civile
Presente solo stato di famiglia e residenza

**Comment by ChiaraC8** [comment]
Buongiorno, ho bisogno di scaricare dal sito ANPR una certificazione completa di residenza, stato di famiglia e stato civile. Attualmente delle 15 voci possibili che vengono indicate online è presente solo la residenza e stato di famiglia.

**Comment by ChiaraC8** [comment]
![Screenshot 2023-12-05 alle 16 37 10](https://github.com/italia/anpr/assets/153001491/4303e400-a664-4ade-a226-d5e34791028e)

**Comment by ldimascio** [comment]
Buongiorno, le chiedo gentilmente di fornire i suoi dati anagrafici per poter fare le dovute verifiche.
Grazie

**Comment by ldimascio** [comment]
Le chiedo gentilmente di inviare il suo Codice fiscale alla casella di posta frmariani@sogei.it

**Comment by frmariani** [comment]
Nel caso in cui avesse richiesto un cambio di residenza, Le comunico che il comune potrebbe aver aperto un procedimento amministrativo e finché non viene chiuso, Lei potrà richiedere soltanto i certificati di stato di famiglia e residenza.
Il procedimento verrà chiuso nel momento in cui il messo comunale accerterà l'effettiva presenza dei cittadini nella residenza dichiarata e comunque al massino entro 45 gg dalla richiesta del cambio di residenza.
Se non si trova in questa situazione dovrà rivolgersi al comune per avere maggiori informazioni.
