### ISSUE TITLE
Integrazione ANPR tramite PDND

### ISSUE THREAD

**Issue by nrinaldi01** [italia/anpr#4284]
Buongiorno,
Sto tentando di accedere al servizio C015 di ANPR tramite PDND. Ottengo con successo l'access token, ma quando interrogo ANPR ricevo:
Response: {"type":"[https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received](https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html%22,%22title%22:%22InteroperabilityInvalidRequest%22,%22status%22:400,%22detail%22:%22Received) request is not conform to the required interoperability profile","govway_id":"834418c2-94df-11ee-bb7f-005056ae1884"}

Sto operando in ambiente di test e sto passando un codice fiscale di quelli dati in esempio.

Sto programmando in Java.

Potete aiutarmi a capire dove sbaglio?
Grazie

**Comment by TheVise1975** [comment]
Prova a dare un'occhiata qui:

https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

Trovi un client in JAVA funzionante per il servizio C001,

**Comment by nrinaldi01** [comment]
Grazie

**Comment by afrontera85** [comment]
Salve,
relativamente al govway_id fornito l'errore era il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 3 eccezioni.
Token con claim 'iat' non valido: Character array is missing "e" notation exponential mark.
Token con claim 'exp' non valido: Character array is missing "e" notation exponential mark.
Token con claim 'nbf' non valido: Character array is missing "e" notation exponential mark.
Col client di esempio non dovreste avere problemi, eventualmente col govway_id possiamo sempre risalire all'errore.
