### ISSUE TITLE
C001 - Ricerca elenco codici fiscali

### ISSUE THREAD

**Issue by TheVise1975** [italia/anpr#4285]
Il servizio C001 permette solo una ricerca puntuale di un singolo codice fiscale, o è possibile eseguire anche una ricerca massiva (anche con risultato asincrono) con un elenco passato nel JSON iniziale?

grazie
V.

**Comment by azabatta** [comment]
Buongiorno, 
al momento tutti i servizi prevedono soltanto una chiamata puntuale, le ricerche di tipo massivo non sono perviste.
Saluti
