### ISSUE TITLE
 X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022

### ISSUE THREAD

**Issue by antoniopantocb** [italia/anpr#4287]
Buongiorno,

con la presente per chiederVi supporto in merito al caso d'uso C022-servizioAccertamentoStatoLibero-approvazione_automatica.

La richiesta di servizio torna un messaggio di errore.

ERRORE:
**Returned with status 0 and output: Array ( [0] => { "type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, "detail": "Unknown API Request", "X-Global-Transaction-ID": "7dbb99166576ec58432f62cd" } )**

La richiesta viene fatta con codice sviluppato da noi in php già testato e funzionante per il servizio C029..

E' possibile avere un vostro chiarimento?

Il messaggio di errore riportato in calce è sufficiente per un'analisi del problema?

Contrariamente siamo a disposizione per generare quanto necessario.

In attesa di un vostro gentile riscontro saluto e lascio per vostra utilità il mio contatto cellulare: [3920053839](callto:3920053839).

Cordialmente

Buona giornata, Antonio.

**Comment by afrontera85** [comment]
Buongiorno, 
Le lascio intanto il link di un esempio di client che implementa i profili di cui Anpr necessita:

#https://github.com/italia/anpr/issues/3964
Va modificato opportunamente il file pdnd.properties.
Per eventuali dettagli su errori presi basta che ci forniate il govway_id e verifichiamo tranquillamente

**Comment by antoniopantocb** [comment]
Buongiorno, 
anche per il servizio C020 da lo stesso problema. 

Stiamo utilizzando lo stesso script che funziona per il C029. 
Potete gentilente ritornarci feedback del codice di errore? 
Grazie mille 
{"result":["{ \"type\": \"https:\/\/govway.org\/handling-errors\/404\/NotFound.html\", \"title\": \"NotFound\", \"status\": 404, \"detail\": \"Unknown API Request\", \"X-Global-Transaction-ID\": \"db4aa801658302b52f794a5d\" }"],"response_code":200,"response_desc":"Valid Request"} 


Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "afrontera85" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Martedì, 19 dicembre 2023 13:11:26 
Oggetto: Re: [italia/anpr] X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022 (Issue #4287) 





Buongiorno, 
Le lascio intanto il link di un esempio di client che implementa i profili di cui Anpr necessita: 

# [ https://github.com/italia/anpr/issues/3964 | #3964 ] 
Va modificato opportunamente il file pdnd.properties. 
Per eventuali dettagli su errori presi basta che ci forniate il govway_id e verifichiamo tranquillamente

**Comment by afrontera85** [comment]
Serve che ci forniate il govway_id per darvi il dettaglio dell'errore...
ricontrollate che l'url sia corretta, comunque, perchè il 404 potrebbe essere dovuto all'url errata, oppure è errato o manca il voucher pdnd

**Comment by antoniopantocb** [comment]
C020 
'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1/anpr-service-e002' 

Questo sopra è l'indirizzo chiamato. 

Il voucher pdnd funziona. 

Il messaggio ritornato è il seguente, il govway_id non è specificato: 

{"result":["{ \"type\": \"https:\/\/govway.org\/handling-errors\/404\/NotFound.html\", \"title\": \"NotFound\", \"status\": 404, \"detail\": \"Unknown API Request\", \"X-Global-Transaction-ID\": \"db4aa801658302b52f794a5d\" }"],"response_code":200,"response_desc":"Valid Request"} 




Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "afrontera85" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 20 dicembre 2023 16:32:08 
Oggetto: Re: [italia/anpr] X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022 (Issue #4287) 





Serve che ci forniate il govway_id per darvi il dettaglio dell'errore... 
ricontrollate che l'url sia corretta, comunque, perchè il 404 potrebbe essere dovuto all'url errata, oppure è errato o manca il voucher pdnd

**Comment by antoniopantocb** [comment]
E' uguale anche in ambiente di collaudo. 
Ripeto che lo script è già quello funzionante per C029. 

Non è un problema di algoritmo. Essendo l'ambiente così chiuso si genera una latenza nella produzione insostenibile. E' possibile avere un feedback dell'errore? 
grazie 


Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "afrontera85" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 20 dicembre 2023 17:13:41 
Oggetto: Re: [italia/anpr] X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022 (Issue #4287) 





State facendo dei test in ambiente di produzione anzichè collaudo. 
La url di collaudo è questa: 
[ https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 | https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 ] 
Anche il voucher pdnd va staccato dall'ambiente di collaudo

**Comment by antoniopantocb** [comment]
sul sito della pdnd nelle specifiche tecniche l'audience è riportato in modo errato, manca "-PDND" 


Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "afrontera85" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 20 dicembre 2023 17:13:41 
Oggetto: Re: [italia/anpr] X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022 (Issue #4287) 





State facendo dei test in ambiente di produzione anzichè collaudo. 
La url di collaudo è questa: 
[ https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 | https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 ] 
Anche il voucher pdnd va staccato dall'ambiente di collaudo

**Comment by afrontera85** [comment]
Url e aud infatti sono diversi
L'url è questo:  
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002
L'aud è questo (con MinInternoPortaANPR e non MinInternoPortaANPR-PDND):
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1

L'errore relativo al govway_id = 07d7f72c-9f53-11ee-85a4-005056ae091b è infatti il seguente:

Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

Per i prossimi test, però, usate l'ambiente di collaudo

**Comment by antoniopantocb** [comment]
Perfetto grazie mille 


Antonio Pantò 
UOC - Innovazione tecnologica 
via XXV Aprile, 4 - 20092 Cinisello Balsamo 
02 66023 - 711 
[ http://www.comune.cinisello-balsamo.mi.it/ | www.comune.cinisello-balsamo.mi.it ] 
[ http://www.facebook.com/comunedicinisellobalsamo | www.facebook.com/comunedicinisellobalsamo ] 



Da: "afrontera85" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "antoniopantocb" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 20 dicembre 2023 18:07:14 
Oggetto: Re: [italia/anpr] X-Global-Transaction-ID: "7dbb99166576ec58432f62cd" - C022 (Issue #4287) 





Url e aud infatti sono diversi 
L'url è questo: 
[ https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 | https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 ] 
L'aud è questo (con MinInternoPortaANPR e non MinInternoPortaANPR-PDND): 
[ https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1 | https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1 ] 

L'errore relativo al govway_id = 07d7f72c-9f53-11ee-85a4-005056ae091b è infatti il seguente: 

Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni. 
Token contenente un claim 'aud' non valido 
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido 

Per i prossimi test, però, usate l'ambiente di collaudo
