### ISSUE TITLE
[C002] - Nome della via mancante nella risposta

### ISSUE THREAD

**Issue by paolozanotti-f2** [italia/anpr#4288]
Buongiorno,
Sto utilizzando il servizio **C002 - servizio comunicazione** in ambiente di collaudo per ottenere la residenza di alcuni utenti.
Il problema è che nella risposta ottenuta mi trovo un oggetto `residenza` contenente il cap, nome del comune, civico e toponimo, senza però il nome della via.

Essendo dati di prova quelli utilizzati non mi è chiaro se il nome della via corrisponde all'oggetto `toponimo` oppure se è proprio un dato mancante.

Allego screenshot della risposta con dati di prova:
<img width="1355" alt="Screenshot 2023-12-11 alle 13 31 10" src="https://github.com/italia/anpr/assets/122781046/80d19953-58a4-4d00-b204-91294bba1d84">

Grazie in anticipo per l'aiuto!

**Comment by amollicone1982** [comment]
DEL BORGO rappresenta il toponimo (nome della via) mentre la specie nel suo caso è BELVEDERE (corrisponde a via, piazza, viale etc..)
