### ISSUE TITLE
Validazione Codice fiscale

### ISSUE THREAD

**Issue by DemograficiCastiglionFiorentino** [italia/anpr#429]
Quest'ufficio ha provveduto per l' entrata in ANPR ad allineare i codici fiscali, alcuni nominativi erano   in Agenzia Entrate discordanti con  quelli dell'anagrafe comunale. Dopo aver controllato abbiamo provveduto alla modifica in AE senza che sia variato il codice fiscale. Alcuni di questi erano iscritti aire, il loro codice fiscale è stato trasmesso via posta  al Comune. Cosa dobbiamo fare di questi codici fiscali?
In alcuni nominativi  abbiamo variato il luogo di nascita ( es. Chianciano Terme a Chianciano),  poichè alla data di nascita, come nell'esempio sopra indicato, il nome esatto del Comune era quello,   dobbiamo modificare i dati in  AE ed in INA)?
Restiamo in attesa di un vostro riscontro.

**Comment by gcarbonin** [comment]
1) mi informo
2) su INA non fate assolutamente nulla in quanto siete prossimi al subentro; per quanto riguarda AE se si tratta di un cambio di denominazione, attualmente AE considera l'ultima denominazione; accetta quelle precedenti ma non le memorizza. Quindi anche in questo caso non fate nulla

**Comment by gcarbonin** [comment]
Per la prima domanda, si metta in contatto con l'ufficio dell'Agenzia per la restituzione dei codici fiscali.

**Comment by gcarbonin** [comment]
Rettifico : segnali la cosa a dc.ti.archivioanagrafico@agenziaentrate.it (mail della Direzione Centrale) che le darà indicazioni sul da farsi
