### ISSUE TITLE
P002: errore bloccante operazione non effettuabile

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#4290]
Da questa mattina diversi comuni ci stanno segnalando l'errore "999 - operazione non effettuabile" utilizzando il servizio P002 per le istanze di cambio abitazione presentate dai cittadini dal portale ANPR.
Potete verificare?

SISCOM SPA

**Comment by jonnyfx95** [comment]
Anche i nostri comuni hanno il medesimo problema.
Il servizio non aggiorna lo stato delle dichiarazioni di residenza lascandole aperte.

**Comment by apaolacci** [comment]
Salve,
questa mattina sono stati segnalati problemi sulle operazioni P001 (elenco pratiche) e P002 (dettaglio pratica) che ci risultano rientrati dalle ore 13:00 di oggi.
Riscontrate ancora problemi ? 
Oppure state segnalando malfunzionamenti di altra operation come la P003 (aggiornamento stato lavorazione pratica) ?
Grazie,
Assistenza ANPR

**Comment by siscomanpr** [comment]
Abbiamo verificato con alcuni comuni ed il servizio P002 adesso funziona correttamente restituendo il dettaglio della pratica.
