### ISSUE TITLE
C017-servizioAccertamentoMatrimonio - piú matrimoni ?

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4298]
Il servizio torna solo un matrimonio, come si comporta qualora il soggetto abbia contratto diversi matimoni ? Torna solo l'ultimo ?

**Comment by SimonePadovan** [comment]
Buongiorno, non si tratta di gestire le poligamie, ma eventuali matrimoni pregressi

**Comment by azabatta** [comment]
Buongiorno, 
i dati restituiti sono quelli presenti in ANPR alla data di riferimento valorizzata nella richiesta. E' possibile effettuare una consultazione su dati pregressi valorizzando opportunamente la data di riferimento.  Non è prevista la possibilità di consultare i dati di tutti i legami precedenti a quello valido alla data di riferimento.

**Comment by SimonePadovan** [comment]
ok grazie della risposta
