### ISSUE TITLE
C017-servizioAccertamentoMatrimonio - cittadinanza coniuge

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4299]
A differenza di C018-servizioAccertamentoCittadinanza che torna un elenco di cittadinanze per il singolo soggetto, il servizio C017-servizioAccertamentoMatrimoni torna solo una cittadinanza per il coniuge.
Come mai questo disallineamento ? Se il coniuge ha piú cittadinanze cosa ritorna ?

grazie

**Comment by azabatta** [comment]
Buongiorno, 
il servizio C017 - servizioAccertamentoMatrimoni non prevede la restituzione della cittadinanza. 
Più in generale tutti i servizi resi disponibili da ANPR ai fruitori sono stati oggetto di un parere del Garante per la protezione dei dati personali, con particolare riguardo ai dati delle risposte. I servizi sono stati adeguati a quanto espresso dal Garante.

**Comment by SimonePadovan** [comment]
secondo la definizione del servizio disponibile in PDND invece il servizio C017 - servizioAccertamentoMatrimoni restituisce la cittadinanza del coniuge.

La mia domanda rimane quindi inevasa, attendo risposta

**Comment by SimonePadovan** [comment]
Se aggiornate la documentazione presente nel documento pdf e non aggiornate il file yaml é chiaro che si crea confusione negli utilizzatori.
Ad ogni modo mi confermate che la cittadinanza del coniuge non verrá piú restituita ?

grazie

**Comment by azabatta** [comment]
sì, confermiamo
saluti

**Comment by SimonePadovan** [comment]
ok grazie
