### ISSUE TITLE
Web-App Registrazione-Mutazione Residenza variazione contestuale rapporti di parentela

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#43]
Data test 22/03/2017 - Ambiente test (dptest)
Famiglia di 3 componenti con Intestatario scheda ID SOGGETTO ANPR 987755 
ID FAMIGLIA ANPR  387416.
Mutazione Residenza per l'Intestatario scheda che crea una famiglia nuova cambiando indirizzo.
D OPERAZIONE Mutazione residenza 442568
ID NUOVA FAMIGLIA ANPR 1888754
Nella videata Elenco Soggetti il sistema consente di modificare il campo Relazione di parentela anche per i componenti che non hanno 
evidenziato il flag Seleziona, senza però percepire la modifica.Quindi dopo il salvataggio compare il messaggio "Operazione eseguita correttamente" e poi "EN226-Aggiornare la famiglia di provenienza del soggetto di cui e' stata cambiata la residenza ed eventualmente i relativi rapporti di parentela". 
Capiamo che in questo modo il sistema sta indicando all'operatore che deve effettuare anche una mutazione sulla scheda della famiglia di origine per aggiornare i rapporti di parentela, tuttavia ciò rappresenta un notevole appesantimento del flusso di lavoro e la possibilità di lasciare situazioni famigliari inesatte visto l'elevato numero di mutazioni eseguite giornalmente.
Si richiede, quindi, di poter effettuare contestualmente alla Mutazione di Residenza del soggetto che lascia la famiglia, la modifica dei rapporti di parentela dei componenti che rimangono.  
Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Inseriremo la richiesta nel piano degli interventi evolutivi da prevedere
