### ISSUE TITLE
Subentro Comune del Trentino

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#430]
Stiamo procedendo al subentro di un comune trentino, si pone un problema sulle date di creazione dei comuni: il comune di Cles e' stato istituito nel 1920 per annessione di territorio dall'Austria. Ci sono soggetti nati prima del 1920, cosa deve essere indicato nel comune di nascita? 
La responsabile dell'anagrafe ci dice che non ritiene corretto indicare queste persone come nate all'estero.
Saluti 
Inf.Or. S.r.l.

**Comment by gcarbonin** [comment]
Attualmente l'anagrafe indica CLES come comune di nascita? Se come penso la risposta è affermativa, NON SI DEVE FARE ASSOLUTAMENTE NULLA per evitare di costringere persone che hanno quasi 100 anni a cambiare documenti codici fiscali e tutto ciò che ne deriva.

**Comment by rpapini** [comment]
Facendo il subentro con i dati attuali, il soggetto verrà inserito in ANPR con anomalia, quindi che succerà quando
il comune deve fare un movimento su questo soggetto?
Saluti
Inf.Or. S.r.l.

**Comment by gcarbonin** [comment]
Mi può mandare il caso sulla mail personale?

**Comment by rpapini** [comment]
Ci facciamo inviare i dati dalla responsabile e le inviamo il caso 
specifico. Purtroppo non esiste uno solo, ma alcuni.

Saluti

Papini Riccardo


Il 24/11/2017 13:19, gcarbonin ha scritto:

**Comment by CarlaMusian** [comment]
Sarebbe utile che ci fosse una risposta "ufficiale" visto che la problematica e' di tanti comuni.
Grazie

Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
La risposta la trova qui https://www.anpr.interno.it/portale/documents/20182/26001/nota+storico+comuni+ANPR.docx/76987019-503e-40ee-aa74-672a69291bb0  dove si dice chiaramente di non modificare posizioni anagrafiche pregresse se non in caso di errore materiale.
