### ISSUE TITLE
C017-servizioAccertamentoMatrimonio - vedovaza

### ISSUE THREAD

**Issue by SimonePadovan** [italia/anpr#4300]
Il servizio prevede allo stesso livello di TipoMatrimonio l'oggetto TipoVedovanza che contiene la data di decesso del coniuge. Si tratta della data di decesso del coniuge indicato in TipoMatrimonio ?

**Comment by azabatta** [comment]
Buongiorno, 
la sezione dati Matrimonio non riporta la data di decesso del coniuge.
Al fine di individuare i dati restituiti da ogni servizio le suggeriamo di verificare il documento pdf che accompagna ogni singolo eservice.

**Comment by SimonePadovan** [comment]
Ho verificato il documento indicato ma non spiega nulla in merito ai dettagli dei dati restituiti!
Vorreste spiegarmi voi il significato dei dati di TipoVedovanza  ?

grazie

**Comment by azabatta** [comment]
I dati restituiti  nella sezione Vedovanza sono: 
- data decesso del coniuge
- luogo decesso, se presente in ANPR
- atto di decesso del coniuge, se presente in ANPR

**Comment by SimonePadovan** [comment]
Bene, ora la mia domanda:

Si tratta della data di decesso del coniuge indicato in TipoMatrimonio ?
Oppure se presente Vedovanza non é valorizzato TipoMatrimonio ? 

grazie

**Comment by azabatta** [comment]
La data presente nella sezione Matrimonio è la data dell'evento matrimonio. Se un cittadino è vedovo sono riportate sia le sezioni Matrimonio che Vedovanza.
Saluti

**Comment by SimonePadovan** [comment]
Quindi la data decesso riportata in Vedovanza é riferita al Coniuge indicato in Matrimonio, corretto ?

**Comment by azabatta** [comment]
Sì, è corretto
