### ISSUE TITLE
C-020 servizioAccertamentoResidenza

### ISSUE THREAD

**Issue by nahid998** [italia/anpr#4301]
Ciao, 
Ho un problema quando provo ad usare il voucher su https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002,
la mia request header:
![Request](https://github.com/italia/anpr/assets/58596489/73c8b226-d4dd-4f35-9ea2-03ed15ebde23)

il mio body è :
{
    "idOperazioneClient": "11",
    "criteriRicerca": {
        "codiceFiscale": "KPPMTT20A16A089N"
    },
    "datiRichiesta": {
        "dataRiferimentoRichiesta": "2023-06-09",
        "motivoRichiesta": "1",
        "casoUso": "C020"
    }
}

riesco a creare il voucher con successo e a mandare la richiesta al nostro endpoint (https://auth.interop.pagopa.it/token.oauth2)
ma come potete vedere dalle immagini sottostanti quando proviamo ad usarla mi da Error 400
![Error400](https://github.com/italia/anpr/assets/58596489/90ff211f-922a-4915-bb71-c83f5d3e3428)

inoltre non ho capito se devo creare altri due JWS, mi riferisco a token Agid-JWT-Signature e Agid-JWT-TrackingEvidence.
vi sarei grato se qualcuno mi potesse aiutare.

**Comment by afrontera85** [comment]
Buongiorno, 
state facendo dei test in ambiente di produzione anzichè collaudo.
La url di collaudo è questa:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002
Le linee guida su come implementare i token richiesti (AUDIT_REST_02 e INTEGRITY_REST_02) le trovate nel [Documento operativo - Pattern sicurezza - v1.1.pdf](https://github.com/italia/anpr/files/12663979/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf)
Quì trovate inoltre un esempio di client che implementa i profili di cui Anpr necessita:
#[3964](https://github.com/italia/anpr/issues/3964)
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties.
Per eventuali dettagli su errori presi basta che ci forniate il govway_id e verifichiamo tranquillamente

**Comment by nahid998** [comment]
ho provato in collaudo ma mi esce questo (    "X-Global-Transaction-ID": "3f7e3e2d6581973e6c0f831d"
)
![Screenshot 2023-12-19 141454](https://github.com/italia/anpr/assets/58596489/7e3399a1-d8a4-40a5-b86a-1eae816b1127)

**Comment by afrontera85** [comment]
l'aud è ancora quello di produzione

**Comment by nahid998** [comment]
ho cambiato l'aud ad entrambi adesso ma continua a dare lo stesso errore
Agid-JWT-Signature:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkttUWY1N0kyTTNGYWR5WHdVX19kRDBLamFYS1BDUmQ1b1hZVllOUVduWEUifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFItUERORC9DMDIwLXNlcnZpemlvQWNjZXJ0YW1lbnRvUmVzaWRlbnphL3YxIiwiaWF0IjoxNzAyOTk1MDAxLCJleHAiOjE3MDMwODE0MDEsImp0aSI6IjgwMzRlN2FlLTA1ZDgtNDNmMS05ZWM0LTA4Yjk2Yjg5NTFmOSIsInNpZ25lZF9oZWFkZXJzIjpbW3siQ29udGVudF9UeXBlIjoiYXBwbGljYXRpb24vanNvbiJ9LHsiQ29udGVudF9FbmNvZGluZyI6IlVURi04In0seyJEaWdlc3QiOiJTSEEtMjU2PVZuUFN0cWhwQTdJUmNJRWZwLy9XWkE5KzJHV3JtKzV6c1VhMVlCSy80bms9In1dXX0.R6Vfoy-xWvYZeDUqILCZv103M8_OvPFrhn0tZhyXGc84UvyXjmG2SowpN5cUWVQL79KzvnxCG1z1YokgYcGDfQn9ACG0Atr7LpYXEqEWK5sWl-9RomEDgTAfASiv14f_Vy8BTxgnijeQaTMUuPDQTC8mRpFhuN2WJhfwFxRt096Fayh9gT4CTYRldbSA5DX-ps_WF4nirA2k0itYQzY1c_UoQ_D6TJ_tmS6irbaEIHTwDkgvlIt-6Zeb3fJMaUIqra-xHWwncLmAQZhaMqucHRNCVFH9qpT0rdqoqOkWDFY3dsHoRRWWndGfmHa_JKalhW7qpm-2i4QyOqd8tNRL5Q
Agid-JWT-TrackingEvidence:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkttUWY1N0kyTTNGYWR5WHdVX19kRDBLamFYS1BDUmQ1b1hZVllOUVduWEUifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFItUERORC9DMDIwLXNlcnZpemlvQWNjZXJ0YW1lbnRvUmVzaWRlbnphL3YxIiwiaXNzIjoiNDNjZDBhYzYtZmJjMC00YzliLTg1NzEtODAyMzhiZThmODczYSIsInB1cnBvc2VJZCI6IjA0MGExYTU5LTIwMjktNDg1MS05YzEwLTE2MzFkMTg4OGNlZSIsImRub25jZSI6MTIzNDU2Nzg5MDEyMywiaWF0IjoxNzAyOTk1MDA4LCJuYmYiOjE3MDI5OTUwMTAsImV4cCI6MTcwMzA4MTQwOCwidXNlcklEIjoiUFJETkRSNzBUMTFBOTQ0QSIsInVzZXJMb2NhdGlvbiI6IlAwMDEiLCJMb0EiOiIxIn0.edIbmn8--Ptv65oepfechYWG3PBF-BFmGs5GtzxpdC-3sv8HBMuAKZbeW5D8rz9BkMRgNHFJ7qizff_GokA4qx8xkKshF8dsScq-TOAsOnJrbPbM5gOPaXuQO8TltObt8bEf082VguBYkUlDxdgHa50XViVrReTxgW3yFD3MYhK8MCjNtwvXlFmvQn7iDxv4dbVM71xQl_gq8mVIMJAZZD3vcw2N4Bb2Ws5JBrhj8fRfqfr9R2EPtWI9LF0jUJqy1zgpEr8t4lHcvWKcWWTwp9_Bg15rZMlaCccykihPfSOQk_MumvSBznFq-K6_ZZvNKALXoUgrkIQY9rtA0AFRdQ

**Comment by nahid998** [comment]
perdonami se faccio qualche sbaglio e grazie ancora dell'aiuto, ora ho sistemato bene l'aud con il link che mi hai dato tu , ma ancora mi da error 404
![Screenshot 2023-12-19 154348](https://github.com/italia/anpr/assets/58596489/22a36885-e3dd-46a3-96fa-ae0b6d3754b2)

Agid-JWT-Signature:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkttUWY1N0kyTTNGYWR5WHdVX19kRDBLamFYS1BDUmQ1b1hZVllOUVduWEUifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMC1zZXJ2aXppb0FjY2VydGFtZW50b1Jlc2lkZW56YS92MSIsImlhdCI6MTcwMjk5Njc2OCwiZXhwIjoxNzAzMDgzMTY4LCJqdGkiOiIzNmEwOTg2ZC0zNWQ5LTQ3OTYtYTJiNC1kNzE3NTA0ZjU5YTkiLCJzaWduZWRfaGVhZGVycyI6W1t7IkNvbnRlbnRfVHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifSx7IkNvbnRlbnRfRW5jb2RpbmciOiJVVEYtOCJ9LHsiRGlnZXN0IjoiU0hBLTI1Nj1jNzB5SmRaamxSdHhXbVlFQ29pYnZqZjNMRlB1eWhyVGdYMDNXeVhTajRFPSJ9XV19.iq6weuKPp9WbMlvbzewfP7X7r6lanQimwFZLqRrQjRNmN_vacWCLp30aCMVDXDFZcopl-UP1v1_6edaaZgC8flN1_SJtP_s_crnnRk-tXHCblbQ3rUl5tVOsX8faQcHzZtRHlfeE29wk6uxq0U9cQzpnLu56Bq0EpLhD-XXPplUaV4Q40651Krl8YcqZ9f9vkzXKeDv__dPVmSeANRjUy8QHCsxi7Zua3wKAW73P6KQFkOAaaxIuJk3k-MRmSwQWSul5s-cAce5JkraYUrdeoLwl1Ambk1T8EryZI86nZ6mCfr-hHwCs515zCU0Q4M-NzSAq0EG9MCelydY2HUmW2w
Agid-JWT-TrackingEvidence:
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkttUWY1N0kyTTNGYWR5WHdVX19kRDBLamFYS1BDUmQ1b1hZVllOUVduWEUifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAyMC1zZXJ2aXppb0FjY2VydGFtZW50b1Jlc2lkZW56YS92MSIsImlzcyI6IjQzY2QwYWM2LWZiYzAtNGM5Yi04NTcxLTgwMjM4YmU4Zjg3M2EiLCJwdXJwb3NlSWQiOiIwNDBhMWE1OS0yMDI5LTQ4NTEtOWMxMC0xNjMxZDE4ODhjZWUiLCJkbm9uY2UiOjEyMzQ1Njc4OTAxMjMsImlhdCI6MTcwMjk5Njc3OCwibmJmIjoxNzAyOTk2NzgwLCJleHAiOjE3MDMwODMxNzgsInVzZXJJRCI6IlBSRE5EUjcwVDExQTk0NEEiLCJ1c2VyTG9jYXRpb24iOiJQMDAxIiwiTG9BIjoiMSJ9.rXRboR_BsYuHa80tyoDdVFP5DEo-48QJ_boI-Q0tRg0LxCgDo1l-Y-3EEQoMzdSFFeqz-7OnqI2C1k-FcPnbyn-yUg2Hud4IQOwWNEpL4Gcq_7JXnxurtQxC_bzV0cuBpbdBUTvcJ3f0syhjrDyP11cxvq8kUmRRHDvQXejGD6qjj0Xlqku3WH4FshlWU6DQfVdf6aLk2DGQK27C39H6KHQa2hbyuVp44y5i6QR8BHrG-EMhCsTYa5V38ODVa1iQo2CnnIV-gGI7nEElYNY1htxJWdOPXigDq9KmbLfE_dACwhFfOx_Z-jwCAbAnthFYF0isndvdD5fyQQqlZM_-Qw

**Comment by afrontera85** [comment]
io vedo ancora l'url di produzione nella schermata...non è che stai chiamando il servizio in collaudo ma staccando il voucher pdnd dall'ambiente di produzione?

**Comment by nahid998** [comment]
sì, io sto lavorando per conto del comune di Segrate e attualmente ho solo l'ambiente PDND di produzione, se provo ad entrare in collaudo non ho nessun E-Service C020

**Comment by afrontera85** [comment]
dovete sottoscrivere un accordo di fruizione sulla pdnd di collaudo

**Comment by nahid998** [comment]
ok, abbiamo mandato la richiesta ti aggiorniamo appena possibile, grazie dell'aiuto

**Comment by ricca8** [comment]
Salve, Nahid era un mio collega e ora ho preso in mano io questo suo progetto. 

In primis vi chiedo: non è possibile effettuare i test direttamente dall'ambiente di produzione? La richiesta di fruizione in ambiente di collaudo è in attesa di approvazione da quasi 4 mesi, e giustamente il nostro cliente (comune di Segrate) fa pressione per procedere. 

In ogni caso, mi sono letto documentazione ed effettuato qualche test con il codice già scritto a suo tempo da Nahid, ma non capisco se è indirizzato nel modo giusto (ottengo errore 400 se provo a richiedere il voucher così:
`    var content = new FormUrlEncodedContent(new Dictionary<string, string>
{
    { "client_id", clientId },
    { "client_assertion", assertion },
    { "client_assertion_type", "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" },
    { "grant_type", "client_credentials" }
});
` 
). Di seguito vi lascio i JWT che venivano creati da lui con cui ho effettuato il test, se poteste certificarmene la validità poi si tratta semplicemente di collocarli negli header in modo corretto come credo sia fatto nell'esempio che vi lascio (non badate agli errori segnalati dal compilatore):

![Screenshot 2024-04-03 150501](https://github.com/italia/anpr/assets/54399420/d157506e-0c8a-4fac-8113-416c9aeee82a)
![Screenshot 2024-04-03 150638](https://github.com/italia/anpr/assets/54399420/0ae2a423-1503-4ff2-a9d4-c8815e639c70)
![Screenshot 2024-04-03 150723](https://github.com/italia/anpr/assets/54399420/d61a6058-5454-452c-94da-13d6690c7d6c)
![Screenshot 2024-04-03 151641](https://github.com/italia/anpr/assets/54399420/13b58c73-a887-4502-8268-8a79106e7806)

**Comment by ricca8** [comment]
Ho provato anche utilizzando il tool clientAnpr-1.0 trovato in un issue di un altro utente ma ottengo comunque errore 400:

"{"correlationId":"cea2a4e2-a53d-4a77-907d-fb296717b46d","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}"

sempre utilizzando i due link per produzione:

- https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002
- https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1

Devo confermare al comune che fino a quando non ci sarà l'approvazione per l'ambiente di collaudo non si potrà procedere con gli sviluppi?

**Comment by afrontera85** [comment]
Salve, ci serve il govway_id restituito a seguito della chiamata del servizio, così potremo individuare la transazione e darvi un dettaglio dell' errore. 
Ribadisco però che i test vanno fatti in ambiente di collaudo...

**Comment by ricca8** [comment]
Salve, i test in ambiente di collaudo non li possiamo fare, è in attesa di approvazione il C020 da 4 mesi, e a causa di fondi PNRR bloccati da questo step mi è stato chiesto se si possa procedere comunque (sempre che sia tecnicamente possibile) .

Detto ciò, non c'è nessun govway_id. L'errore ricevuto (in fase di richiesta voucher) è quello che le ho indicato nel mio commento sopra. Viene ricevuto quando, tramite il vostro client java, si tenta di richiedere il voucher passando il seguente JWT.

![image](https://github.com/italia/anpr/assets/54399420/26904570-8c9c-4abd-a60d-69558440546b)
![image](https://github.com/italia/anpr/assets/54399420/ebfce2a3-0abb-415f-a348-e56ca2c59ef0)

**Comment by afrontera85** [comment]
Provi a fare la chiamata da Postman, per vedere se ritorna il govway_id
Comunque l'aud è questo: 
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1
L'url invece è questa:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002
In generale l'errore 400 è un errore generico relativo all'implementazione della cornice di sicurezza.

**Comment by ricca8** [comment]
Grazie per la risposta. Era errato l' aud, era sufficiente modificare auth.uat.interop.ecc in auth.interop.ecc

Ora il vostro client funziona correttamente, traduco il tutto nel nostro progetto in modo che tutti i token e richieste vengano create nello stesso modo.-

**Comment by ricca8** [comment]
Sono riuscito a generare il voucher, ma quando procedo con la richiesta ottengo questo errore:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"bdef4ca4-f286-11ee-af4e-005056ae1d2a"}

**Comment by ricca8** [comment]
Risolto. Grazie mille per il supporto
