### ISSUE TITLE
Mutazione dati elettorali - Cancellazione - dopo la cancellazione non viene ricalcolato il RIEPILOGO

### ISSUE THREAD

**Issue by ServiziDemograficiCori** [italia/anpr#4309]
Ho provveduto ad effettuare la CANCELLAZIONE dalle liste elettorali, dopo la Revisione SEMESTRALE, di un soggetto maschio per IRREPERIBILITA'.
Ho tolto la spunta da LISTA GENERALE e da CERTIFICABILITA'.
Ho messo la spunta su CANCELLAZIONE e ho messo tra i motivi di cancellazione IRREPERIBILITA'.
L'operazione è andata a buon fine. 
Se procedo ad emettere un certificato elettorale per il soggetto giustamente mi blocca.
Ma ho un problema nel RIEPILOGO ELETTORI : nonostante il soggetto sia cancellato in anagrafe e cancellato dalle liste elettorali il riepilogo riporta la presenza anche dell'elettore cancellato 
ad es : prima della cancellazione il riepilogo mi da : 
MASCHI = 4046 FEMMINE = 4291 
mi aspettavo che con la cancellazione di un soggetto maschio il risultato del riepilogo si modificasse in : 
MASCHI = 4045 FEMMINE = 4291
quindi che diminuisse ma così non è.
Mi potete aiutare a capire come procedere?
Grazie mille

anagrafe@comune.cori.lt.it
0696617204

**Comment by frmariani** [comment]
i riepiloghi vengono aggiornati il giorno successivo alle operazioni effettuate.
Quando ha cancellato il cittadino dalle liste elettorali del comune?

**Comment by ServiziDemograficiCori** [comment]
> i riepiloghi vengono aggiornati il ​​giorno successivo alle operazioni effettuate. Quando ha cancellato il cittadino dalle liste elettorali del comune?

oggi. quindi aspetto domani. Grazie mille
