### ISSUE TITLE
Aggiornamenti ambiente di produzione ANPR

### ISSUE THREAD

**Issue by gcarbonin** [italia/anpr#431]
Nella giornata di domani, dopo le ore 18, non sarà disponibile la porta di dominio ANPR per manutenzione: non funzioneranno le operazioni che richiamano i servizi AE.
Lunedì a partire  dalle ore 18 saranno effettuati gli aggiornamenti relativi alle le mutazioni del nucleo famigliare da utilizzare per:
• ripristinare la residenza nel comune antecedente al subentro (tipo mutazione 6 disponibile sia per il servizio 5001 che 5005)
• comunicare contestualmente alla variazione di residenza (attuale tipo di mutazione 4), il possesso di veicoli e patente da parte dei componenti del nucleo famigliare (tipo mutazione 5 del servizio 5001).

**Comment by busaster** [comment]
saranno caricate anche le modifiche che permettono di indicare tutti i soggetti di un procedimento in un'unica chiamata 1014 ?

**Comment by gcarbonin** [comment]
No questa modifica sarà trasferita successivamente

**Comment by ATropeano** [comment]
... anche il servizio 5014 (rettifica della data di decorrenza della residenza e del motivo di iscrizione in modalita’ WS) sarà trasferito successivamente in ambiente di subentro?
