### ISSUE TITLE
Errore 999 in ricerca richiesta cittadino

### ISSUE THREAD

**Issue by busaster** [italia/anpr#4310]
Ambiente di test
Invocando il servizio P002 mettendo come filtro il codice richiesta 1710534 otteniamo l'errore seguente:

```
<errore>
  <codiceErroreAnomalia>999</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
/errore>
```

Quale può essere la causa ?

Grazie

**Comment by apaolacci** [comment]
Buongiorno  @busaster,
grazie, abbiamo analizzato la segnalazione e aggiornato l'ambiente Test Comuni. Ora sembra funzionare l'operation P002 di recupero del dettaglio pratica.

E' possibile fare un nuovo test e verificare la risoluzione della issue? 

Grazie,
Assistenza ANPR

**Comment by busaster** [comment]
Confermo che Il servizio è tornato a funzionare correttamente, grazie per il supporto
