### ISSUE TITLE
Problema su comune di iscrizione AIRE

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#4313]
Comune di Modena

Buongiorno,
il soggetto con identificativo unico VZ88726UC  è stato iscritto nell' AIRE del Comune di Modena per acquisto della cittadinanza nel 2019; il Comune di Genova sta ora cercando di iscriverlo ma riceve un errore EN187 (id operazione: 1572654935 del 02/01/2024) perchè il loro gestionale rileva come comune di iscrizione AIRE il valore "AIRE" invece di "MODENA".  
Genova ci chiede di correggere il dato ma non riusciamo a capire dove farlo, in quanto sui dati AIRE il comune di iscrizione è indicato come "Comune di reg. o di trasc. dell'atto di nascita di un componente della famiglia anagrafica A.I.R.E." e il valore "AIRE" non è visibile. Per cortesia potete aiutarci a sbloccare?

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
Non capisco come abbiate analizzato la problematica, comunque direi che dovrebbe essere il comune di Genova a richiedere assistenza e non voi.
Se capisco bene questo cittadino deve rimanere Aire ma cambia soltanto il comune di riferimento: corretto? 
in questo caso il comune di Genova sbaglia operazione in quanto il cittadino è già presente in ANPR, pertanto non deve effettuare un'iscrizione ma una mutazione dati Aire.
Potrebbe consigliare al suo riferimento del comune di Genova di chiamare l'assistenza  ANPR al numero 800863116

**Comment by sfmodena** [comment]
Buonasera,
a noi sembra un problema dell' applicativo di Genova. Poichè però l' altro comune dice che riuscirebbe ad iscrivere (non so se in APR o AIRE) senza errori l' altro componente del nucleo familiare vorremmo solo essere certi che sulla nostra posizione non ci siano dati da modificare prima di rimandarli all' assistenza ANPR.  

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
ribadisco che il cittadino è già presente in ANPR pertanto non si deve eseguire un'iscrizione; infatti l'errore EN187 rileva proprio questo: **il cittadino ..... risulta già iscritto o deceduto**.
La sua affermazione "_il Comune di Genova sta ora cercando di iscriverlo ma riceve un errore EN187 (id operazione: 1572654935 del 02/01/2024) perchè il loro gestionale rileva come comune di iscrizione AIRE il valore "AIRE" invece di "MODENA"_ non ha nessun fondamento o relazione con la tipologia di errore emesso da ANPR.

**Comment by sfmodena** [comment]
L' affermazione non è mia, mi sono limitata a riportare quanto inviatoci da Genova:
_"Il problema nasce dall'indicazione del comune di iscrizione AIRE, che
dovrebbe essere Modena ma invece è genericamente 'AIRE'. Va corretto
tale dato, pena l'impossibilità  di generale l'evento."_
che allega alla richiesta una consultazione ANPR del soggetto ottenuta attraverso il loro gestionale dove è visibile:
Comune iscrizione AIRE: AIRE

Li inviteremo a rivolgersi all' assistenza, chiudo la issue.
Grazie, saluti
