### ISSUE TITLE
ambiente di produzione non funzionante

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#432]
buongiorno.
nessuna notizia riguardo l'ambiente di produzione che questa mattina sembra non funzionare?
da Medicina - San Lazzaro - Faenza ci segnalano che non funzionano nè i web-service nè la web-app

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
La situazione di è ripristinata

**Comment by AMonopoliADS** [comment]
buongiorno. 

è possibile avere qualche dettaglio sulle cause del blocco?

il comune di Faenza chiederebbe anche come comportarsi una prossima volta (mail o numeri di telefono ai quali possono scrivere o telefonare) per cercare di intervenire nella maniera più tempestiva possibile.

grazie.

**Comment by gcarbonin** [comment]
Il blocco era dovuto ad un problema di configurazione (a livello rete) della Porta di dominio anpr che colloquia con AE; non era totale nel senso che alcune transazioni andavano a buon fine e altre no.
C'è il numero verde dell'assistenza o i nostri numeri che i comuni attualmente subentrati contattano regolarmente
