### ISSUE TITLE
[5005] Invio Mutazioni Elettorali per Iscrizione - Errore EN493 - L'utente non dispone dei privilegi per eseguire l' operazione

### ISSUE THREAD

**Issue by MarcoSalaPad** [italia/anpr#4320]
Buongiorno, 
abbiamo un problema su una sola mutazione di iscrizione di un soggetto iscritto con la revisione semestrale.
Tutti gli altri soggetti (iscritti e cancellati) sono stati correttamente inviati sempre dal medesimo utente.

Di seguito la descrizione dell'errore:

Lista Errori (2)
Tipo 	Codice Errore 	Descrizione Errore
E 	EN493 	La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione sul soggetto/famiglia
E 	EN527 	Informazioni sull'operazione da fornire in caso di assistenza : data 2024-01-05 11:34:06 , mittente 025056 , idOperazioneComune 26399

Vi invio tramite mail il codice fiscale dell'operatore, specificandovi il numero della issues di riferimento.

Grazie
Pa Digitale Spa

**Comment by frmariani** [comment]
il WS 5005 non si riferisce a mutazioni elettorali; 
può farmi capire meglio cosa deve fare? di quale comune parliamo? l'idanpr del soggetto può tranquillamente indicarlo in questa issue.

**Comment by MarcoSalaPad** [comment]
Ho sbagliato ad indicare il servizio, che è il 5010 per l'invio delle mutazioni.
Il comune è Sospirolo (codice istat 025056) e dobbiamo inviare una mutazione elettorale per iscrivere questo cittadino nelle liste elettorali, a seguito di iscrizione con la semestrale.
L'id Anpr del soggetto è 45226684.

Grazie
Marco

**Comment by frmariani** [comment]
è sicuro dell'idoperazione ? chi sta eseguendo l'operazione ha il profilo di ufficiale elettorale?

**Comment by MarcoSalaPad** [comment]
Chi sta eseguendo l'operazione è lo stesso operatore che ha inviato le altre mutazioni legate alla semestrale, di cui vi ho mandato il codice fiscale tramite mail.
Vi invio una seconda mail con il codice fiscale del soggetto che deve avere la mutazione, per fare una verifica sull'id anpr che mi ha detto non esistere.
