### ISSUE TITLE
Data cessazione Albaredo Arnaboldi

### ISSUE THREAD

**Issue by dedabob** [italia/anpr#4322]
La [L.R. 14 novembre 2023, N. 5](https://normelombardia.consiglio.regione.lombardia.it/normelombardia/accessibile/main.aspx?view=showdoc&iddoc=lr002023111400005), [BURL N. 46, suppl. del 17 Novembre 2023](https://www.consultazioniburl.servizirl.it/ConsultazioneBurl/ApriAllegato?idBurl=302135610&apriAllegato) indica come data di entrata in vigore della cessazione di Albaredo Arnaboldi il giorno successivo alla pubblicazione nel BURL, ovvero il 18/11/2023.
Questa è la data riportata anche da ISTAT nella [tabella delle variazioni amministrative](https://www.istat.it/it/archivio/6789).
La data inoltre dovrebbe essere coerente con il cambio di nome del Comune di Campospinoso in Campospinoso Albaredo.
Nella tabella di ANPR le due date non risultano coerenti, in particolare il campo DATACESSAZIONE dovrebbe contenere 17/11/2023.

| ID| DATACOSTITUZIONE | DATACESSAZIONE | CODISTAT | CODCATASTALE | DENOMINAZIONE_IT |
|-------|------------|------------|--------|------|-----------------------|
|   150 | 09/03/1961 | _12/12/2023_ | 018002 | A134 | ALBAREDO ARNABOLDI    |
| 16825 | 16/08/2008 | _17/11/2023_ | 018026 | B567 | CAMPOSPINOSO          |
| 23092 | 18/11/2023 | 31/12/9999 | 018026 | B567 | CAMPOSPINOSO ALBAREDO |

**Comment by ncapozzi** [comment]
[#4374](https://github.com/italia/anpr/issues/4374)
