### ISSUE TITLE
Mutazione elettorale: errore EN562

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4327]
Buongiorno
con uno dei nostri Comuni abbiamo provato a fare una mutazione dati elettorali liste aggiunte Comunali/Regionali.

Una cittadina iscritta alla lista aggiunta di Trento viene cancellata in prima dinamica per raggiungimento requisito residenziale. 
Consultando i dati elettorali della cittadina (ID 66219676) l'operatore del comune si chiedeva come mai nei dati relativi alle liste aggiunte comparisse "Lista aggiunta Trento" SI dal momento in cui la cittadina era stata cancellata.
Quando ha provato a modificare il dato da WA è uscito l'errore 
"EN562 Indicare un solo flag a S per la lista aggiunta comunale/regionale"

La mia domanda è allora: elettori iscritti alle liste aggiunte comunali, che vengono cancellati per raggiungimento requisito residenziale (o altro motivo) devono continuare a mantenere la flag "S" nel tag <comregelettoretrento> anche se non più elettori?

Grazie
Roberta

**Comment by Hdemografici** [comment]
Abbiamo rimesso la posizione elettorale a "S", l'operatore dell'ufficio elettorale però si chiedeva come mai in WA devono continuare a vedersi i dati delle liste aggiunte con flag "S" quando in realtà lei ha cancellato il cittadino dalle proprie liste. E mi rifaccio alla domanda iniziale, cioè:
elettori iscritti alle liste aggiunte comunali, che vengono cancellati per raggiungimento requisito residenziale devono continuare a mantenere la flag "Lista aggiunta Trento" SI anche se non più elettori?

In merito alla sua domanda la cittadina è stata cancellata 
"I cittadini che trasferiscono la residenza nella provincia di Trento , cancellati dalle liste elettorali del comune di emigrazione, restano iscritti nella lista elettorale aggiunta del comune di emigrazione fino al compimento del periodo residenziale previsto (1 anno)."

**Comment by frmariani** [comment]
Ripeto la modalità di cancellazione delle liste aggiunte: **la cancellazione della lista regionale/comunale si effettua con il tipo mutazione 5 (cancellazione) motivo cancellazione 7 (cancellazione lista aggiunta comunali regionali).**
Sulla cittadina in questione non è stata effettuata la cancellazione della lista, per questo motivo continuate a visualizzarla.
