### ISSUE TITLE
[Collaudo] C019-servizioAccertamentoEsistenzaVita-approvazione_automati

### ISSUE THREAD

**Issue by ivano-manara** [italia/anpr#4328]
Buonasera,
vi segnalo che abbiamo cercato più volte di chiamare il servizio in collaudo:

https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

ma riceviamo sempre il seguente errore:

GovWay-Transaction-ID: 3001f076-afc7-11ee-8c7f-005056ae1884
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"3001f076-afc7-11ee-8c7f-005056ae1884"}

Richiesta inviata:
 {
   "idOperazioneClient": "1",
     
    "criteriRicerca": {
      "codiceFiscale": "STTSGT90A01H501J"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2023-12-13",
      "motivoRichiesta": "1",
      "casoUso": "C001"
    }
  }
il codice fiscale appartiene ai codici fiscali presenti nei casi di test.

**Comment by ivano-manara** [comment]
Buonasera,

vi informo che abbiamo apportato alcune modifiche alla chiamata al servizio e ora ci restituisce il seguente errore:

response = {'type': 'https://govway.org/handling-errors/404/NotFound.html', 'title': 'NotFound', 'status': 404, 'detail': 'Unknown API Request', 'X-Global-Transaction-ID': '3f7e3e2d659ff34ec3af8cff'}

ci potete fornire qualche dettaglio in più sull'errore? 

Grazie

**Comment by ivano-manara** [comment]
Buongiorno,

vi segnalo che siamo bloccati nell'invio di dati delle Polizze dormienti.

La Piattaforma Digitale Nazionale Dati (PDND)  ha confermato che il problema non deriva dal loro sistema dopo la verifica del token.
Ipotizzo che il problema sia causa di qualche dato mancante nell'invio verso di voi ANRP ma, non conosciamo quale sia. 
ci potete indicare se è stato aperto un altro canale di assistenza o è sempre questo.

Grazie

**Comment by ivano-manara** [comment]
Buongiorno,

Oggi in collaudo riceviamo il seguente errore:
response = {'type': 'https://govway.org/handling-errors/404/NotFound.html', 'title': 'NotFound', 'status': 404, 'detail': 'Unknown API Request', 'X-Global-Transaction-ID': '3f7e3e2d65a52b76ca9e6bff'}

potete cortesemente fornirci supporto tecnico o una codifica di questi errori 'X-Global-Transaction-ID' ?

Grazie

**Comment by azabatta** [comment]
Buongiorno, ci scusiamo per il ritardo nella risposta. 

Di seguito gli errori riscontrati a fronte dell'ultimo govway_id indicato "6c1d8795-b3ae-11ee-9a9a-005056ae1884":

Verifica ModI della richiesta fallita: Riscontrate 4 eccezioni.
[GOVWAY-661] Token creato da troppo tempo (data creazione: '2024-01-15_15:04:36.000')
[GOVWAY-814] Token contenente un claim 'aud' non valido
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-01-15_15:04:36.000')
[GOVWAY-814] [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by ivano-manara** [comment]
Buongiorno,

 noi inviamo come parametro aud :

 'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1'
 
questo valore è stato preso da file C019-servizioAccertamentoEsistenzaVita.yaml.
servers:
  - url: 'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1'
    description: Url di test per Consultazione Enti C019

dobbiamo omettere https o formattare la stringa in un particolare modo?

Grazie

**Comment by azabatta** [comment]
La stringa è formattata correttamente.
Potete rigenerare un altro token Agid-JWT-TrackingEvidence per risolvere l'altra tipologia di errore segnalata e fare una nuova prova? Per individuare la transazione basta comunicare solo il govway_id.
Grazie

**Comment by ivano-manara** [comment]
Come richiesto abbiamo riprovato ora:

audit = eyJhbGciOiJSUzI1NiIsImtpZCI6Il82Zks3UTFocHh0MlJVaDkweHpBZUZfWmlaSWlFenQxa1NzS0h6cElSTlEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VySUQiOiJNTlJWTkk3NkwwN0YyMDVaIiwidXNlckxvY2F0aW9uIjoiTVZQSVRQT1JUNTI2IiwiTG9BIjoiTG9BMiIsImlzcyI6IjZiZTQ0YmRkLWVhOWUtNDUzZS1hZGU5LWEyZjkyZjRmMmVmYyIsImF1ZCI6Imh0dHBzOi8vbW9kaXBhLXZhbC5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi1QRE5EL0MwMTktc2Vydml6aW9BY2NlcnRhbWVudG9Fc2lzdGVuemFWaXRhL3YxIiwicHVycG9zZUlkIjoiNzlkNDg5MTEtOGRmZC00MTZjLTgyMTEtZTUyOWZhMWYwMjY5IiwiZG5vbmNlIjo2MDQ0NzU4NjEwNzc2LCJqdGkiOiJjOWFhZmMyNy0yNzUxLTQzNjAtYjIwZC1iMDY5YmU2MGI0MWUiLCJpYXQiOjE3MDU0MTAyNzgsIm5iZiI6MTcwNTQxMDI3OCwiZXhwIjoxNzA1NDEwODE4fQ.V7BY2ULxuozO3IjPvZwroQsjYJtwK6e2RiBEAwXO8at0qvATbFHDLIhOkFfCjBX26gPJ3JFdgnP2-EpVHUSNp_rCF2TBzGkiJU05zmZIaURjARW0KBnZGgngbYiQUQ_6Cy4a9R-hn5jRhrRpluoFVZgDDAJHjaEH8IQtMIMC9NSZepiN1NR8-_GHSjKDKzAgQFk0pEAJFlOrGgnY1awtqxSd7PRESahob0fou2iKrmAsjt4CxBWBoXqeQ4WefqPRsyxvqVc_0FqfNyoBaROsw6X41gaLDiZb8h1YyuUiGJD8V3YQumKE7fpbRRejF324As9wI2XHcvrwn_t1Okt8AQ

riceviamo il seguente messaggio:

response = {'type': 'https://govway.org/handling-errors/404/UnknownAPI.html', 'title': 'UnknownAPI', 'status': 404, 'detail': 'Unknown API', 'X-Global-Transaction-ID': '3f7e3e2d65a680928efe36cd'}

Grazie

**Comment by azabatta** [comment]
Per cortesia potete indicare il valore del 'govway_id'. E' necessario per individuare la transazione

**Comment by ivano-manara** [comment]
Buongiorno,

abbiamo riprovato ora, nella risposta abbiamo solo la chiave X-Global-Transaction-ID credo che corrisponda al  govway_id 
il valore è : 3f7e3e2d65a689818f08b0dd


Grazie

**Comment by azabatta** [comment]
Buongiorno, non è sufficiente perchè non è il govway_id che è l'unico dato che ci consente di individuare in maniera puntuale la transazione. Stiamo chiedendo disponibilità alle componenti sistemistiche per effettuare un debug congiunto. Vi contattiamo appena possibile

**Comment by afrontera85** [comment]
Potete riprovare gentilmente? 
Tenete conto che il 404 potrebbe essere dovuto all'url errato, oppure è errato o manca il voucher pdnd. 
L'url è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
L'aud è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
Comunque ribadisco quanto detto dalla collega, cioè che per darvi un riscontro preciso dell'errore necessitiamo del govway_id

**Comment by ivano-manara** [comment]
Buongiorno,

impostando come aud il valore da lei indicato otteniamo il seguente errore:

'GovWay-Message-ID': 'e718ec37-ef9f-4b47-ac37-8d4f1123bb7d'

response = {'listaErrori': [{'codiceErroreAnomalia': 'EN148', 'testoErroreAnomalia': 'Ente non abilitato o caso uso inesistente : 1', 'tipoErroreAnomalia': 'E'}], 'idOperazioneANPR': '59870653'}


headers=  {'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Expires': '0', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'set-cookie': '3c35079545c464c280f404566baa2aa8=b1b7b59fdf8cd81e63b8baa4e9fcc240; path=/; HttpOnly; Secure; SameSite=None', 'Server': 'GovWay-SOGEI', 'Pragma': 'no-cache', 'GovWay-Message-ID': 'e718ec37-ef9f-4b47-ac37-8d4f1123bb7d', 'GovWay-Transaction-ID': '46a830ac-b52c-11ee-8c0d-005056ae1884', 'server-timing': 'intid;desc=0272fcc87543f817', 'Date': 'Wed, 17 Jan 2024 12:26:53 GMT', 'Vary': '*', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/problem+json', 'X-Global-Transaction-ID': '3f7e3e2d65a7c78d9040e38d'}

Grazie

**Comment by afrontera85** [comment]
"casoUso": "C019"

**Comment by ivano-manara** [comment]
Ho solo un'ultima domanda. 
Da tracciato sembrerebbe che possiamo inviare una sola posizione da verificare alla volta e non un array di dati.

E corretto o sbagliamo a interpretare le specifiche C019-servizioAccertamentoEsistenzaVita.yaml?
In questo caso per verificare N codici fiscali dovrei chiamare N volte l'API

Grazie

**Comment by azabatta** [comment]
Buonasera, sì è corretto. Ogni invocazione è puntuale per singolo soggetto. Al momento è esclusa la possibilità di effettuare consultazioni più consistenti per motivi non di carattere tecnico.

**Comment by gp-elips** [comment]
@azabatta @afrontera85 , scusate il disturbo. 
noi abbiamo lo stesso problema, dobbiamo svincolare le polizze dormienti e abbiamo bisogno di questa verifica.

stesso errore 400, lo stiamo seguiendo sull'issue https://github.com/pagopa/pdnd-interop-frontend/issues/696 

grazie in anticipo
Gaetano

**Comment by afrontera85** [comment]
Buongiorno, da quello che ho visto state facendo dei test in ambiente di produzione anzichè collaudo...
In collaudo l'url è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
Anche il voucher pdnd va staccato dall'ambiente di collaudo.
L'errore 400 comunque è un errore generico relativo all'implementazione della cornice di sicurezza, nello specifico relativamente al govway_id": "2d997277-b61a-11ee-85c7-005056ae6555 l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente.
Quì trovate un esempio di client che implementa i profili di cui Anpr necessita:
https://github.com/italia/anpr/issues/3964
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties.
