### ISSUE TITLE
[5005] DA comune subentrato A comune subentrato: motivoIscrizione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#433]
il cliente ha notato che in seguito ad iscrizione da comune subentrato (evento che viene comunicato con mutazione 5005) vengono aggiornati tutti i dati di iscrizione / provenienza ad eccezione del motivo di iscrizione che rimane quello originario del subentro, ovvero "immigrazione (da comune non subentrato)" 

è corretto così?

perchè sembra incoerente e fuorviante rispetto ai restanti dati di provenienza che invece sono riferiti ad un comune comune subentrato.

es.
ambiente di PRODUZIONE - comune di Medicina - idSchedaANPR 19077066

grazie
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Il motivo iscrizione è un dato che viene acquisito nel momento del subentro o con l’iscrizione nel comune (evento comunicato con il servizio 1002). Quando una persona si sposta da un comune subentrato ad un altro, non si parla più di iscrizioni anagrafiche ma di mutazioni quindi il motivo di iscrizione non deve essere esposto. Sistemiamo la consultazione del soggetto

**Comment by frmariani** [comment]
La consultazione del soggetto è stata corretta.
