### ISSUE TITLE
Errore in trasmissione ad ANPR

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#4332]
Buongiorno,
alcuni nostri comuni ci comunicano che stamattina le comunicazioni con ANPR non funzionano e viene restituito l'errore:
Il server ANPR ha restituito un errore (Malformed content (from server))

Potete verificare per cortesia?
Grazie.

**Comment by mttfranci** [comment]
Buongiorno @LucaBonini64 , potreste verificare se il problema persiste?

Saluti

Assistenza ANPR

**Comment by migmar68** [comment]
Dalle prime prove (Maggioli) il problema sembra risolto. grazie.

**Comment by mttfranci** [comment]
Grazie a voi del riscontro, ovviamente la situazione è analoga a quella delle issue #4333 e #4334.

Saluti

Assistenza ANPR
