### ISSUE TITLE
Malformed content (from server)

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4333]
Buongiorno, oggi diversi comuni ci segnalano questo errore, era capitato in passato e risolto da parte vostra

**Comment by siscomanpr** [comment]
Anche diversi nostri comuni ci stanno segnalando lo stesso problema.
In alcuni casi ripetendo l'operazione dopo alcuni secondi viene eseguita correttamente.

**Comment by mttfranci** [comment]
Buongiorno @Hdemografici, @siscomanpr , potreste verificare se il problema persiste?

Saluti

Assistenza ANPR

**Comment by INSIEL1** [comment]
anche i nostri comuni non ricevono piu' le notifiche e la risposta è Malformed content (from server)

**Comment by siscomanpr** [comment]
Abbiamo verificato con alcuni clienti ed il problema sembra risolto

**Comment by mttfranci** [comment]
Perfetto, grazie del feedback.

Saluti

Assistenza ANPR
