### ISSUE TITLE
Problemi comunicazione con ANPR per "Malformed content" - URGENTE

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#4334]
Buongiorno

questa mattina entrambe le nostre applicazioni hanno problemi di comunicazione con ANPR, alcune richieste vanno a buon fine altre ricevono come risposta **"000000E : ERRORE COLLOQUIO ANPR: Malformed content (from server)"**

Potreste verificare e darci informazioni in merito? 

Grazie
_Raffaella Tremolada_
Sistemi Informativi IBM per Comune di Milano

**Comment by mttfranci** [comment]
Buongiorno @ANPRCdMI , potreste verificare se il problema persiste?

Saluti

Assistenza ANPR

**Comment by ANPRCdMI** [comment]
Confermiamo anche noi che il problema è rientrato.

Grazie

**Comment by mttfranci** [comment]
Perfetto, grazie del feedback.

Saluti

Assistenza ANPR
