### ISSUE TITLE
reset accesso ambiente di test

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4337]
Buongiorno,
il comune di 017074 ha smarrito l'utenza per accedere al portale ANPR in ambiente di TEST.
Potete resettare o rendere accessibile l'accesso alla responsabile di anagrafe, GRSSMN72B50H717E?

Potete inviare tutto a anagrafe@comune.gardoneriviera.bs.it?

Saluti

**Comment by gppbarone** [comment]
Buongiorno, può inviare la richiesta per il certificato a questa email: subentro.anpr@sogei.it.

**Comment by Leonforte** [comment]
Buon pomeriggio, la password è stata inviata [anagrafe@comune.gardoneriviera.bs.it]
Buon lavoro, saluti
