### ISSUE TITLE
Malfunzionamento colloquio anpr Problem writing SAAJ model to stream: PKIX path building failed

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#4339]
Buongiorno, dalle 11.30 non funziona piu' il colloquio con anpr. 
Visto che il 18 gennaio 2024 scade il certificato ws.anpr.interno.it chiedo se per caso e' stato generato il nuovo certificato disattivando contemporaneamente il vecchio.
Potete inoltre inviare il nuovo certificato.
Grazie.
Andrea Galli

**Comment by sfmodena** [comment]
Buongiorno,
stesso problema a Modena.

**Comment by edoardodona-1** [comment]
Stesso problema A unione Bassa Romagna e Terre d' argine.

**Comment by edoardodona-1** [comment]
Anche Santarcangelo di Romagna

**Comment by rvinzani** [comment]
Salve,
allego la chiave pubblica di ws.anpr.interno.it. 
I problemi di accesso riscontrati derivano probabilmente dal trust del certificato e non della sola chiave pubblica.
[wsprod.zip](https://github.com/italia/anpr/files/13939717/wsprod.zip)

**Comment by edoardodona-1** [comment]
Ringrazio solo adesso . cmq. Si , in effetti avevamo estratto in autonomia la chiave da ws.anpr.interno.it. .. 
Grazie sempre! cmq.
