### ISSUE TITLE
Pre-subentro e subentro

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#434]
Buongiorno,
vorremmo chiarire con voi alcuni dubbi sulla fase di pre-subentro per i comuni che utilizzano la modalità WS.
1 - nel documento di specifiche è riportato che "l’ambiente di pre-subentro è accessibile da parte dei comuni che hanno completato il censimento degli utenti e delle postazioni (cfr Allegato D DPCM 194/2014) con un filtro sull’indirizzo IP del chiamante". 
Questo vuol dire che dovremo comunicare l'indirizzo IP "pubblico" della postazione da cui andremo ad effettuare i test in questa fase? E' possibile in ogni caso continuare ad effettuare i test dall'interno della software house e non direttamente da postazioni del comune?
2 - Nella fase di pre-subentro è prevista la possibilità di effettuare caricamenti successivi del file di subentro in caso di errori, quindi l'esecuzione dei test di integrazione consigliati nel documento "Piano dei test di integrazione_1.pdf". C'è un limite temporale per questa fase, o un comune può permanere in pre-subentro fin quando non è pronto realmente a subentrare? 

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
1- Non è più così; si utilizzano le stesse credenziali di test comuni e non è necessario comunicare gli IP
2- può rimanere fino a quando non è pronto
