### ISSUE TITLE
[Collaudo] C019-servizioAccertamentoEsistenzaVita - Internal Error

### ISSUE THREAD

**Issue by robeagle85** [italia/anpr#4342]
Buongiorno,

Stiamo riscontrando un **_errore 500 (Internal Error)_** provando ad invocare il servizio C019-servizioAccertamentoEsistenzaVita sull'ambiente di collaudo.

Qui di seguito l'ultima prova effettuata con un CF totalmente casuale:

```
{
  "idOperazioneClient": "1705490443592",
  "criteriRicerca": {
    "codiceFiscale": "STTSGT90A01H501J"
  },
  "datiRichiesta": {
    "dataRiferimentoRichiesta": "2024-01-17",
    "casoUso": "C019",
    "motivoRichiesta": "Verifica esistenza in Vita"
  }
}
```

Il timestamp della chiamata è **2024-01-17 11:20:44**

Potresti supportarci nella risoluzione del problema? Grazie.

**Comment by afrontera85** [comment]
Salve, 
potreste indicarci il valore del 'govway_id' restituito a seguito della chiamata del servizio? 
E' necessario per individuare la transazione in maniera puntuale.
Vi consiglio comunque di usare il client di esempio che trovate nel github #3964 
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties
