### ISSUE TITLE
Errore Risposta Servizio P002 Ambiente TEST

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#4343]
Buongiorno, in ambiente di test il sistema non risponde correttamente alle richieste di tipo P002 
All'interrogazione 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc"><testataRichiesta><idOperazioneComune>52001</idOperazioneComune><codMittente>052032</codMittente><codDestinatario>ANPR05</codDestinatario><operazioneRichiesta>P002</operazioneRichiesta><dataOraRichiesta>2024-01-17T13:22:46</dataOraRichiesta><tipoOperazione>C</tipoOperazione><dataProtocolloComune>2024-01-17</dataProtocolloComune><tipoInvio>TEST</tipoInvio><dataDecorrenza>2024-01-17</dataDecorrenza><dataDefinizionePratica>2024-01-17</dataDefinizionePratica><nomeApplicativo>INFOR</nomeApplicativo><versioneApplicativo>INFOR</versioneApplicativo><fornitoreApplicativo>INFOR</fornitoreApplicativo></testataRichiesta><criteriRicerca><codiceRichiesta>1710524</codiceRichiesta></criteriRicerca></ns2:RichiestaP002>

la risposta e' 
ERRORE_GENERICO - Unmarshalling Error: unexpected element (uri:"", local:"identificativi"). Expected elements are <{}dataChiusura>,<{}note>,<{}numeroProroghe>,<{}dataApertura>,<{}recapiti>,<{}codiceRichiesta>,<{}datiDichiarazioneResidenza>,<{}comuneInteressato>,<{}allegati>,<{}dataScadenza>,<{}storicoStati>,<{}statoRichiestaCorrente>,<{}soggettoRichiedente>,<{}datiRettifica>,<{}riepilogoRichiesta>,<{}idTipologia>,<{}famigliaConvivenza>,<{}soggettoInteressato>,<{}dataUltimoAggiornamento>

Grazie.
Andrea Galli

**Comment by apaolacci** [comment]
Buongiorno,
l'errore riporta che l'xml è stato evoluto con la sezione identificativi anche per le attuali Cambio Residenza e Rettifica Dati come da richiesta @ncapozzi  [4253](https://github.com/italia/anpr/issues/4253)

Saluti,
Assistenza ANPR

**Comment by galliandrea** [comment]
Grazie, ho scaricato xsd e wsdl dal portale anpr aggiornati al 13 dicembre pensavo fossero aggiornati  
[Tracciati XSD e WSDL – zip](https://www.anagrafenazionale.interno.it/wp-content/uploads/anpr-wsdl.zip), aggiornato al 13 dicembre 2023

**Comment by mttfranci** [comment]
Come suggerimento generale, nell'ottica di minimizzare le potenziali anomalie per gli utenti, ricordiamo l'indicazione data fin dall'introduzione del processo di [change management](https://github.com/italia/anpr/blob/master/src/change-management/change-management.md) e riportata anche nelle issue #547 e #925, ovvero :
 
"In questo senso quindi, assumiamo che il client che si interfaccia con ANPR lo faccia sempre in modalità non strict e non vada in errore incontrando campi opzionali."

Saluti 

Assistenza ANPR

PS: la modifica annunciata per l'ambiente di test comuni con la issue #4253 verrà pubblicata anche nel changelog una volta rilasciata in produzione.

**Comment by apaolacci** [comment]
buongiorno @galliandrea, l'xsd nell'element _allegato_ per la richiesta di "Dichiarazione di trasferimento cittadino UE" è stato aggiornato con un nuovo campo in output che caratterizza solo nella pratica di tipo 4 un allegato recuperato tramite OOTS del sistema Single Digital Gateway Italia, per cui dovresti aggiornarti con il pacchetto più aggiornato. [4253
](https://github.com/italia/anpr/issues/4253
)

Saluti
Assistenza ANPR

**Comment by galliandrea** [comment]
Buongiorno, intanto grazie per le risposte, vi chiedo pero' se fosse possibile, come e' stato fatto per testare le richieste di cambio residenza (tipo 2) creandoci un paio di utenti abilitati all'inserimento in test di tali pratiche, poter testare anche il nuovo tipo di  pratica "4". E' fattibile tale test?
