### ISSUE TITLE
Statistiche annuali anpr

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#4344]
BUONGIORNO
COMUNE DI VALDILANA (BI)

Richiedendo l'emissione delle statistiche annuali ricevo dei pdf che mi paiono incompleti.
in particolare:
Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 1 : 
viene visualizzata una sola pagina che comprende solamente cancellazioni e saldi finali (con risultati diversi dalla chiusura del mese di dicembre 2023)
Ho chiesto piu' volte il ricalcolo ma il risultato non cambia.
Che fare?

**Comment by RENZO63** [comment]
Altri colleghi hanno avuto la stessa problematica??

**Comment by azabatta** [comment]
Buongiorno,
cortesemente può  sottomettere una nuova richiesta di elaborazione per darci modo di monitorare la procedura?
Grazie

**Comment by RENZO63** [comment]
Ne ho appena inviata una
Operazione 1599707118
Grazie
Renzo Preto

Il ven 19 gen 2024, 12:11 azabatta ***@***.***> ha scritto:

**Comment by azabatta** [comment]
il prospetto è stato rielaborato, può cortesemente controllare e darci un riscontro? 
Grazie

**Comment by RENZO63** [comment]
Il prospetto è arrivato completo
Sto controllando i dati e mi è subito saltato all'occhio il rigo 40 (senza
fissa dimora) che riporta 11 persone (ma a me ne risultano solo 2 a fine
anno e 3 per anno parziale)
Come riesco ad estrarre i nominativi in modo da controllare e risolvere
l'errore?
Poi come al solito non si capisce la differenza tra il rigo 30 e la somma
dei righi 31 e 32 che confluiscono nel 33.
Grazie x la collaborazione


Il mar 23 gen 2024, 10:32 azabatta ***@***.***> ha scritto:

**Comment by azabatta** [comment]
Buonasera, 
dai controlli effettuati i dati relativi ai senza fissa dimora sembrano estratti correttamente. Per effettuare una verifica congiunta la preghiamo di aprire una segnalazione al servizio di assistenza  ai comuni (800863116) specificando un recapito telefonico.

I dati di cui alla riga  30 sono calcolati in base alle risultanze delle righe precedenti ossia in base alla data di definizione comunicata nel periodo di interesse sugli eventi anagrafici analizzati.
I dati relativi alle famiglie ed alle convivenze si riferiscono ai componenti con scheda attiva alla data di fine rilevazione a prescindere da altri criteri.
