### ISSUE TITLE
[EN409] Per tipo mutazione = 15 inserire l'oggetto Atto di Nascita

### ISSUE THREAD

**Issue by ilucini** [italia/anpr#435]
Cercando di caricare l'evento di morte di un cittadino straniero in quanto deceduto all'estero ci mostra il seguente errore :Errore durate la fase di registrazione della vedovanza.System.Exception: ERRORE DA ANPR: EN409 - Per tipo mutazione = 15 inserire l'oggetto Atto di Nascita

Sono stati attivati controlli aggiuntivi?

Grazie
ilucini - Comune di Codogno(LO)

**Comment by asqueglia** [comment]
Buongiorno,
da verifiche effettuate ci risulta che sono state richieste le seguenti mutazioni
<tipoMutazione>01</tipoMutazione>    dati anagrafici
<tipoMutazione>15</tipoMutazione>    atto di nascita
<tipoMutazione>10</tipoMutazione>    paternità
<tipoMutazione>11</tipoMutazione>    maternità

Il controllo EN409 bloccante viene restituito da ANPR quando viene richiesta la mutazione 15 specifica e non viene trasmesso l’atto di nascita; il controllo è stato rilasciato negli ambienti di test il 09/11/2017 come da documentazione e lunedì propagato in produzione come da comunicazione.

Le mutazioni richieste nulla hanno a che fare con la vedovanza (che è nello specifico codificata con tipoMutazione= 13); l’errore segnalato vedovanza.System.Exception: ERRORE DA ANPR è del gestionale del comune e non di ANPR.
