### ISSUE TITLE
Errore in chiamata servizio accertamento esistenza in vita

### ISSUE THREAD

**Issue by marcomartino22** [italia/anpr#4359]
Buonasera,
stiamo procedendo con l’integrazione del servizio di accertamento esistenza in vita all’interno dei nostri sistemi informatici. Abbiamo completato la fase di accreditamento sul portale e riusciamo a recuperare correttamente il token JWT chiamando il servizio https://auth.uat.interop.pagopa.it/token.oauth2
Non riusciamo invece a contattare il WS di accertamento esistenza in vita di un soggetto, ma probabilmente stiamo sbagliando qualcosa nell’URL richiamata e/o nel JSON della request (vedi sotto i riferimenti da noi utilizzati).
 
Potete per cortesia dirci dove stiamo sbagliando?
 
POST https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
 
{
    "idOperazioneClient": "GRMA_20240115153000",
    "criteriRicerca": {
        "codiceFiscale": "STTSGT90A01H501J"
    },
    "datiRichiesta": {
        "dataRiferimentoRichiesta": "2024-01-15",
        "motivoRichiesta": "prova",
        "casoUso": "C001"
    }
}

Il messaggio di errore ottenuto è il seguente.

{
    "type": https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html,
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "9bc38e08-b915-11ee-95c2-005056ae5232"
}

**Comment by afrontera85** [comment]
Buongiorno,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente.
L'errore 400, comunque, è un errore relativo all'implementazione della cornice di sicurezza.
Quì trovate un esempio di client che implementa i profili di cui Anpr necessita: #3964 
Vi consiglio di usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties, lo hanno usato in tanti e funziona correttamente.

**Comment by marcomartino22** [comment]
Buongiorno, ho seguito il suo suggerimento e ora la risposta è la seguente. Può gentilmente dirmi cosa manca?

{
   "type":"https://govway.org/handling-errors/403/AuthorizationTokenDeny.html",
   "title":"AuthorizationTokenDeny",
   "status":403,
   "detail":"Insufficient token claims",
   "govway_id":"6d5da64a-bc55-11ee-8341-005056ae1884"
}

**Comment by marcomartino22** [comment]
Ho sostituito i riferimenti al C001 con quelli al C019 e ora ottengo questo errore. Cosa non va?

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"b77293c5-bc57-11ee-a29e-005056ae5232"}

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by marcomartino22** [comment]
Ho risolto grazie!
