### ISSUE TITLE
Utilita' e notifiche - certificati e ci - errata segnalazione diritti di segreteria

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#436]
COMUNE DI VALLE MOSSO - subentrato - ambiente di produzione

Rilasciando certificazioni a mezzo software gestionale ho rilevato che i certificati emessi in esenzione dal bollo (atti scambiati con pp.aa.) e dal diritto di segreteria vengono stampati in modo corretto (es. certificato n. 1431833) indicando entrambe le esenzioni.
Andando sul web - utilita' e notifiche - certificati e ci - e chiedendo l'elenco dei certificati rilasciati viene invece indicata in modo corretto l'esenzione dal bollo ma non quella dell'esenzione dai diritti di segreteria che, infatti, non vengono conteggiati nel resoconto contabile a fondo pagina (tutti importi a zero).
Si tratta sicuramente di un bug nella visualizzazione del dato.

**Comment by gcarbonin** [comment]
Puo' riprovare

**Comment by RENZO63** [comment]
Ho provato a stampare ora  un certificato di residenza uso scambio tra pa  cert. n. 1449359 e la stampa riporta correttamente le esenzioni bollo e diritti
sul web viene riportata l'emissione con bollo esente (0 euro) diritti non esenti (ma sempre 0 euro) quindi come prima.
Ho chiesto alla software house se il problema dipende dal gestionale e mi ha comunicato che nel tracciato nella parte dati di controllo (relativa alla richiesta di certificazione) nella parte esenzione diritti e' scritto "Non utilizzato: il motivo di esenzione dei diritti e' ricavato da quello di esenzione bollo".
C'e' un errore nella documentazione?  Va indicato il motivo di esenzione diritti?
Fatemi sapere cosi' passo l'informazione.

**Comment by gcarbonin** [comment]
Puo' riprovare (emettendo un nuovo certificato) in ambiente di test comuni e pre-subentro.

**Comment by RENZO63** [comment]
COMUNE DI VALLE MOSSO - PRODUZIONE

Ho provato ad emettere un certificato di prova e ora funziona benissimo.
Viene riportato tutto in modo corretto.
Grazie 1000

**Comment by gcarbonin** [comment]
grazie a voi
