### ISSUE TITLE
[C019 - Accertamento esistenza in vita] Errore 400 - Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by jonnypa** [italia/anpr#4365]
Buonasera,

stiamo realizzando uno sviluppo per conto di un cliente che invochi i servizi C019 su una lista di codici fiscali per verificare l'esistenza in vita. 

Stiamo quindi procedendo all'implementazione della catena di autenticazione invocando i servizi di Interoperabilità come fruitori. Dopo aver effettuato le configurazioni su PDND abbiamo sviluppato la componente relativa alla generazione del token. Quest'ultimo viene generato e restituito, ma poi effettuando la chiamata al web service otteniamo l'errore in oggetto. 

Il payload di esempio è il seguente

`{
"idOperazioneClient": "dev-1706018181495",
"criteriRicerca": {
  "codiceFiscale": "DPLPRM90R10H501I"
},
"datiRichiesta": {
 "dataRiferimentoRichiesta": "2024-01-01",
  "motivoRichiesta": "esistenza in vita",
  "casoUso": "C019"
}
}`

la response che riceviamo è la seguente 

`{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "17f5370d-b9f0-11ee-874c-005056ae5232"
  }`

Riuscireste ad analizzare il govway_id per comprendere in cosa stiamo sbagliando in fase di autenticazione?
Abbiamo ipotizzato potesse essere un problema analogo a quello della issue #3964 che abbiamo provato a seguire, ma senza successo.

Grazie anticipatamente

**Comment by afrontera85** [comment]
Buongiorno, l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente.
Sempre nel #3964 trovate un esempio di client che implementa i profili di cui Anpr necessita
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties, lo hanno provato in tanti e funziona

**Comment by jonnypa** [comment]
Buongiorno @afrontera85, grazie per la risposta. Abbiamo provato a modificare la nostra chiamata inserendo l'header 'Agid-JWT-Signature' durante lo stacco del token, ma abbiamo ancora un errore

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "f85b2931-bb6c-11ee-82a5-005056ae1884"
  }
```

Anche provando ad utilizzare il client Java otteniamo un errore

```
{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "ca5be6ea-bb67-11ee-aa87-005056ae5232"
}
```

Abbiamo notato però che nel file pdnd.properties è richiesto il purposeID che, da quello che ho capito, è necessario per i casi di invocazione di E-service e non nel caso di Interoperabilità. C'è modo per utilizzare il client senza purposeId?

**Comment by afrontera85** [comment]
Intanto le dico che nel primo caso l'errore è questo:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Header HTTP 'Digest' non presente
Token senza claim 'signed_headers'

Nel secondo caso è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 5 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido
[Header 'Authorization'] Token non contiene il claim 'purposeId'
[Header 'Authorization'] Token non contiene il claim 'digest.alg'
[Header 'Authorization'] Token non contiene il claim 'digest.value'

Allego il documento delineato da AGID come riferimento nell'implementazione della cornice di sicurezza.
[Documento.operativo.-.Pattern.sicurezza.-.v1.1](https://github.com/italia/anpr/files/11999717/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf)
ANPR implementa INTEGRITY_REST_02 e AUDIT_REST_02.

**Comment by amollicone1982** [comment]
Il purposeid, come puo' vedere dal documento allegato dalla collega, è fondamentale e presente in tutti i token. E' rilasciato una volta definita la finalità di uso di un e-service su pdnd.

**Comment by jonnypa** [comment]
Ho recuperato il purposeId della richiesta di finalità per la fruizione dell'eservice generato su pdnd. Ho quindi configurato pdnd.properties così (ometto gli id)

```
baseurlapi=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

kidPdnd=xxxx

clientIdPdnd=xxxx

purposeIdPdnd=xxx

audPdnd=auth.uat.interop.pagopa.it/client-assertion

urltokenPdnd=https://auth.uat.interop.pagopa.it

audTokenAgidJwtSignature=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

proxyhost=
proxyport=
proxyuser=
proxypwd=

fileTest=test1
```

il contenuto del file "test1" è il seguente

```
 {
   "idOperazioneClient": "1",

    "criteriRicerca": {
      "codiceFiscale": "DCLVNT58H11H501C"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2024-01-22",
      "motivoRichiesta": "1",
      "casoUso": "C019"
    }
  }
```
come da README ho lanciato i comandi

```
mvn clean install
java -jar target/dist-clientApiAnprPdnd-1.0.0.jar
```

e nella directory "store" ho inserito la chiave privata corrispondente alla chiave pubblica dichiarata nella richiesta di fruizione dell'e-service.

Ottengo però il seguente errore

`java.lang.Exception: {"correlationId":"338496da-ecdf-4ad1-9fc9-a71a47f4340d","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}`

cosa sbaglio? Qualcosa nel pdnd.properties?

**Comment by amollicone1982** [comment]
Si tratta di un errore restituito da PDnd e quindi necessario chiedere all'assistenza pdnd.
A occhio avete inserito clientid o purposeid errato oppure non avete messo la chiave privata nella cartella store

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jonnypa** [comment]
Grazie per il riscontro, abbiamo fatto delle verifiche con il cliente sul portale PDND e la finalità risulta ancora in attesa di approvazione, motivo per cui non riusciamo ancora ad emettere correttamente un voucher per l'eservice collegato.

**Comment by jonnypa** [comment]
Buonasera, abbiamo effettuato una nuova richiesta su PDND e adesso la finalità è stata approvata e tramite il tool di Debugging il token risulta correttamente generato. Provando ad utilizzare il client Java però continuiamo a ricevere errore dalla chiamata, stavolta dai servizi ANPR. Il file pdnp.properties (al netto del purposeID, vista la nuova richiesta di finalità) e il payload di richiesta sono identici a quelli utilizzati [qui](https://github.com/italia/anpr/issues/4365#issuecomment-1910341914). Riporto l'errore

```
GovWay-Transaction-ID: 5e4458bc-c1db-11ee-b6a0-005056ae5232
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"5e4458bc-c1db-11ee-b6a0-005056ae5232"}
```
Cosa sbagliamo?

Grazie

**Comment by afrontera85** [comment]
Salve, 
l'errore relativo al govway_id indicato è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by jonnypa** [comment]
Buongiorno,

effettivamente stavo erroneamente utilizzando come aud

`baseurlapi=https://modipa-val.anpr.interno.it/govway/rest/in/**MinInternoPortaANPR-PDND**/C019-servizioAccertamentoEsistenzaVita/v1`

invece di

`https://modipa-val.anpr.interno.it/govway/rest/in/**MinInternoPortaANPR**/C019-servizioAccertamentoEsistenzaVita/v1`

adesso il servizio risponde correttamente.

Grazie per il supporto, è possibile chiudere la issue.
