### ISSUE TITLE
Errore chiamata servizio - Collaudo

### ISSUE THREAD

**Issue by LucianoCFAss** [italia/anpr#4369]
Nella generazione del client assertion tramite lo script create_client_assertion.py qual'è il valore del campo aud che si deve settare per poter richiedere correttamente il voucher per l'accesso al servizio https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1 ?

Lasciando la generazione con il parametro di default, ovvero auth.uat.interop.pagopa.it/client-assertion la generazione del voucher avviene correttamente ma poi quel token non funziona nella chiamata effettiva al servizio di AccertamentoEsistenzaVita.

**Comment by afrontera85** [comment]
Salve,
l'aud è questo: 
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
Vi consiglio di usare il client di esempio nel github #3964 che implementa i profili di cui Anpr necessita, 
modificando opportunamente il file pdnd.properties

**Comment by LucianoCFAss** [comment]
Molte grazie, verifichiamo e ti facciamo sapere

Luciano

Da: afrontera85 ***@***.***>
Inviato: giovedì 25 gennaio 2024 10:17
A: italia/anpr ***@***.***>
Cc: Luciano Polinari ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] Errore chiamata servizio - Collaudo (Issue #4369)


Salve,
l'aud è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
Vi consiglio di usare il client di esempio nel github #3964<https://github.com/italia/anpr/issues/3964> che implementa i profili di cui Anpr necessita,
modificando opportunamente il file pdnd.properties
