### ISSUE TITLE
[5005] mutazione residenza di soggetto AIRE: errore EF026

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#437]
ambiente di PRODUZIONE - comune di Faenza - idOperazione 2017001193

la comunicazione ritorna errore:
EF026 - E - Il tipo indirizzo deve essere = 1 Residenza   se si attribuisce il soggetto ad una nuova famiglia

ma trattandosi di cambio di residenza di soggetto residente all'estero, il tipoIndirizzo è valorizzato con 4 - Residenza estera

come intervenire?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Non va bene il 5005. Per il cambio di residenza da estero a estero possono usare

A006 con tipo mutazione = 2 se il singolo soggetto crea una nuova famiglia o si trasferisce in una famiglia esistenza diversa da quella di partenza

5001 con tipo mutazione = 4 se una intera famiglia AIRE cambia indirizzo estero
