### ISSUE TITLE
Archivio comuni del 19/01/2024

### ISSUE THREAD

**Issue by tizpav** [italia/anpr#4374]
Buongiorno,
è stato aggiornato il file dei comuni il 19/01/2024 introducendo la fusione del comune di UGGIATE CON RONAGO.
L'archivio però contiene ancora l'anomalia introdotta con la fornitura del 04/01/2024. Ossia la data di cessazione di ALBAREDO ARNABOLDI (come già segnalato in #4322).
Posso sollecitare un chiarimento da parte vostra?

Grazie,
Tiziano Pavan

**Comment by ncapozzi** [comment]
Buonasera,
il l'archivio comuni è stato aggiornato.
Grazie per la segnalazione
