### ISSUE TITLE
[C019 - Accertamento esistenza in vita] Endpoint da chiamare

### ISSUE THREAD

**Issue by JeyjooMilano** [italia/anpr#4379]
Buongiorno,

Ho aperto ticket con l'assistenza ma mi hanno chiesto di aprire un issue qui.

Abbiamo un file .csv di clienti (assicurati con noi) e dobbiamo verificare se sono in vita.

Ho fatto richiesta di e-service dal catalogo “c019 servizio accertamento esistenza vita”. Sono riuscito creare inserire una chiave di sicurezza e generare un voucher.

Dove posso trovare l'api endpoint per mandare .csv? C'è una documentazione con gli endpoint e esempi di json da mandare?

Grazie

**Comment by afrontera85** [comment]
Non è previsto al momento il caricamento di un .csv con CF perchè non è possibile al momento un uso massivo del servizio, bisogna richiamare il servizio in maniera puntuale, inserendo nella richiesta il singolo CF
