### ISSUE TITLE
Cancellazione Subentro anagrafe in ambiente di TEST

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#4380]
Buongiorno, 
avremmo la necessità di rifare il subentro di anagrafe/elettorale in ambiente di TEST per il comune di Gardone Riviera (Istat 017074). 
Dal menu "Subentro e Anomalie" non è più presente la voce per richiedere la cancellazione del subentro.

Come possiamo procedere?
Ringrazio anticipatamente per l'aiuto
Saluti

**Comment by SAlberto** [comment]
Si richiede cortesemente un riscontro.

Ringrazio anticipatamente per l'aiuto
Saluti

**Comment by amollicone1982** [comment]
Salve, se intende fare un subentro anagrafico ai fini dell'invio dell'elettorale le dico che non è piu' possibile. In ambiente di test è necessario lavorare con dati fittizi e per tale motivo, come hanno fatto tutti gli altri comuni, deve crearsi una base con delle iscrizioni e su queste fare il subentro elettorale

Buona giornata

**Comment by SAlberto** [comment]
La ringrazio per l'informazione.
Saluti
