### ISSUE TITLE
Errore nell'accesso all'anagrafe nazionale con SPID

### ISSUE THREAD

**Issue by EfVelasquez** [italia/anpr#4385]
Ho certificato il mio SPID all'estero (dove risiedo) tramite SIELTE ID. Tentando di accedere al servizio anagrafico nazionale ottengo il seguente errore:

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al termine della guarigione dell'anomalia nei tuoi dati che non ci ha consentito di individuare in un univoco maniera anagrafica la tua scheda.

Le mie informazioni sembrano essere corrette nel mio profilo ID SIELTE e non so perché potrebbe non funzionare.

Grazie mille e saluti.

Le prime 6 cifre del mio codice fiscale sono: "VLSNFR"

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
