### ISSUE TITLE
Errore EN148 servizio P003 per modifica stato pratica

### ISSUE THREAD

**Issue by galliandrea** [italia/anpr#4386]
Buongiorno, dopo l'aggiornamento dei servizi P000 mi risulta un errore nel cambio stato di una pratica P003
EN148 - Errore nell'impostazione dello stato/proroga pratica. Esito: 12003
Provando a passare una pratica da SOSPESA ad ANNULLATA oppure a INTEGRATA.
<ns2:RichiestaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
	<testataRichiesta>
		<idOperazioneComune>1006014</idOperazioneComune>
		<codMittente>049009</codMittente>
		<codDestinatario>ANPR05</codDestinatario>
		<operazioneRichiesta>P003</operazioneRichiesta>
		<dataOraRichiesta>2024-02-06T11:56:14</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<dataProtocolloComune>2024-02-06</dataProtocolloComune>
		<tipoInvio>PROD</tipoInvio>
		<dataDecorrenza>2024-02-06</dataDecorrenza>
		<dataDefinizionePratica>2024-02-06</dataDefinizionePratica>
		<nomeApplicativo>INFOR</nomeApplicativo>
		<versioneApplicativo>INFOR</versioneApplicativo>
		<fornitoreApplicativo>INFOR</fornitoreApplicativo>
	</testataRichiesta>
	<criteriAggiornamento>
		<codiceRichiesta>28833517</codiceRichiesta>
		<idStatoRichiesta>4</idStatoRichiesta>
		<note>inserita d'ufficio dopo ricezione della stessa tramite mail</note>
		<operatore>JENTE</operatore>
	</criteriAggiornamento>
</ns2:RichiestaP003>
Grazie, Andrea Galli

**Comment by galliandrea** [comment]
<ns2:RichiestaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
	<testataRichiesta>
		<idOperazioneComune>1006014</idOperazioneComune>
		<codMittente>049009</codMittente>
		<codDestinatario>ANPR05</codDestinatario>
		<operazioneRichiesta>P003</operazioneRichiesta>
		<dataOraRichiesta>2024-02-06T11:56:14</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<dataProtocolloComune>2024-02-06</dataProtocolloComune>
		<tipoInvio>PROD</tipoInvio>
		<dataDecorrenza>2024-02-06</dataDecorrenza>
		<dataDefinizionePratica>2024-02-06</dataDefinizionePratica>
		<nomeApplicativo>INFOR</nomeApplicativo>
		<versioneApplicativo>INFOR</versioneApplicativo>
		<fornitoreApplicativo>INFOR</fornitoreApplicativo>
	</testataRichiesta>
	<criteriAggiornamento>
		<codiceRichiesta>28833517</codiceRichiesta>
		<idStatoRichiesta>4</idStatoRichiesta>
		<note>inserita d'ufficio dopo ricezione della stessa tramite mail</note>
		<operatore>JENTE</operatore>
	</criteriAggiornamento>
</ns2:RichiestaP003>

**Comment by galliandrea** [comment]
[xml.txt](https://github.com/italia/anpr/files/14178654/xml.txt)

**Comment by gppbarone** [comment]
Buon pomeriggio, abbiamo analizzato la segnalazione e abbiamo notato varie invocazioni al P003, riscontrate ancora questo problema che ci hai segnalato? Perché abbiamo notato che siete riusciti a portare la pratica in stato 4 (Annullata). Che sequenza di operazioni e cambi di stato state effettuando ? Troviamo molti tentativi di lavorazione per questa pratica, non riusciamo a capire se sono corretti.

Grazie,
Assistenza ANPR

**Comment by galliandrea** [comment]
Sono state fatte numerose invocazioni al servizio P003 dato che non riuscivamo ad annullare la pratica. Adesso se richiedo lo stato della pratica con servizio P002 mi risponde che non e' annullata ma sospesa 
<codiceRichiesta>28833517</codiceRichiesta>
			<idTipologia>2</idTipologia>
			<dataApertura>2023-12-29T13:04:02.000+01:00</dataApertura>
			<dataChiusura>2024-02-06T09:50:48.000+01:00</dataChiusura>
			<dataScadenza>2024-01-03T23:59:59.000+01:00</dataScadenza>
			<dataUltimoAggiornamento>2024-02-06T15:02:30.000+01:00</dataUltimoAggiornamento>
			<numeroProroghe>0</numeroProroghe>
			<statoRichiestaCorrente>
				<idStato>6</idStato>
				<operatore>JENTE</operatore>
				<dataStato>2024-02-06T09:50:48.000+01:00</dataStato>
			</statoRichiestaCorrente>
Se proviamo a mandare l'annullamento la risposta e' EN148 - Errore nell'impostazione dello stato/proroga pratica. Esito: 12003

**Comment by galliandrea** [comment]
[xml.txt](https://github.com/italia/anpr/files/14195679/xml.txt)

**Comment by gppbarone** [comment]
Per risolvere il problema possiamo intervenire sulla pratica variando lo stato del record su DB ma è necessario inviare una PEC dal comune di competenza verso la PEC di ANPR chiedendo la variazione dello stato della pratica dallo stato Sospesa (6) ad Annullata (4).

Grazie,
Assistenza ANPR

**Comment by galliandrea** [comment]
Potete anche intervenire sulla pratica in oggetto ma io vorrei la soluzione per poter operare nella normalita' ... se dovessi avere un altro caso simile vorrei che tutto funzionasse correttamente senza ricevere l'errore segnalato.
Se invece mi confermate che questo errore e' specifico di questa pratica allora fine del discorso.
Andrea Galli

**Comment by gppbarone** [comment]
Avete fatto troppi tentativi di lavorazione della pratica e non riusciamo a ricostruire quello che è successo, l'unica soluzione è quella di bonificare la pratica. Non abbiamo avuto altre segnalazioni simili.
Se inviate la pec, aggiornate questa issue.

Grazie,
Assistenza ANPR

**Comment by gppbarone** [comment]
Buonasera, non è richiesto più l'invio della pec, abbiamo provveduto a bonificare la vostra pratica. Adesso lo stato attuale della pratica 28833517 è IN ANNULLATA. Se è tutto ok procedete alla chiusura della issue.

Saluti,
Assistenza ANPR
