### ISSUE TITLE
[A002] problema con descrizioneConsolato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#439]
ambiente di PRODUZIONE - comune di Faenza

si sta tentando di iscrivere un soggetto all'AIRE.
il consolato di riferimento è il 3330304, che - da decodifica in tabella 25 - corrisponde a "IZMIR (SMIRNE)"
```
<consolato>
<codiceConsolato>3330304</codiceConsolato>
<descrizioneConsolato>IZMIR (SMIRNE)</descrizioneConsolato>
</consolato>
```

l'xml NON passa i controlli di validazione perchè il campo descrizioneConsolato non può contenere le parentesi.

abbiamo anche tentato a passare descrizioni come
IZMIR SMIRNE
IZMIR
SMIRNE
ma poi incappiamo nell'errore:
EC034 - E - Codice consolato di residenza 3330304 incongruente con la descrizione

è necessaria una modifica della descrizione all'interno della tabella di riferimento?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Abbiamo aggiornato la descrizione in IZMIR - SMIRNE Può riprovare

**Comment by AMonopoliADS** [comment]
adesso l'iscrizione è andata a buon fine.
grazie.
