### ISSUE TITLE
[PDND C020] Errore interoperability profile

### ISSUE THREAD

**Issue by FueledBy-Pizza** [italia/anpr#4392]
Eseguendo la chiamata al servizio C020 (endpoint https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002") riceviamo il seguente errore:

"400 Bad Request: "<problem xmlns="urn:ietf:rfc:7807"><type>https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html</type><title>InteroperabilityInvalidRequest</title><status>400</status><detail>Received request is not conform to the required interoperability profile</detail><govway_id>a03dbfad-c50a-11ee-878b-005056ae5232</govway_id></problem>""

Il token lo generiamo puntando ad ambiente di collaudo UAT.
Il certificato scaricato dal sito lo abbiamo importato nel cacert.
Abbiamo usato un codice fiscale di test, viene riportata qui sotto l'intera request JSON.

{
   "idOperazioneClient":"785857987",
   "criteriRicerca":{
      "codiceFiscale":"QRTSGT90A01H501B",
      "idANPR":"",
      "cognome":"",
      "senzaCognome":"",
      "nome":"",
      "senzaNome":"",
      "sesso":"",
      "datiNascita":{
         "dataEvento":"",
         "senzaGiorno":"",
         "senzaGiornoMese":"",
         "luogoNascita":{
            "luogoEccezionale":"",
            "comune":{
               "nomeComune":"",
               "codiceIstat":"",
               "siglaProvinciaIstat":"",
               "descrizioneLocalita":""
            },
            "localita":{
               "descrizioneLocalita":"",
               "descrizioneStato":"",
               "codiceStato":"",
               "provinciaContea":""
            }
         }
      }
   },
   "datiRichiesta":{
      "dataRiferimentoRichiesta":"2024-02-06",
      "motivoRichiesta":"ciao",
      "casoUso":"C001"
   }
}

Per conto del comune di Gallarate, Advanced Systems.
Ringrazio anticipatamente,
Giuliano Aiello

**Comment by afrontera85** [comment]
L'errore relativo al govway_id indicato è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente
