### ISSUE TITLE
Notofiche P002 - Mancanza tag soggettoRichiedente nella risposta

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#4393]
Buonasera. Dopo l'aggiornamento di ieri, nelle risposte di tipo RispostaOKP002, nel tag dettaglio che corrisponde al tipo tipoDettaglioP002, manca il tag soggettoRichiedente.
Ad esempio si veda <idOperazioneANPR>1628335260</idOperazioneANPR>
Nei nuovi wsdl/xsd mi sembra ancora previsto.

Grazie.

Alessio Tropeano
Dtagraph srl

**Comment by gppbarone** [comment]
Buongiorno, abbiamo verificato la vostra invocazione (idoperazioneANPR = **1628335260**)  per il comune di Arluno e abbiamo controllato la risposta xml dell'operazione P002. All'interno del tag dettaglio è presente il tag <soggettoRichiedente> successivamente al tag <identificativi> e precedente al tag <comuneInteressato>. Rispetto ai wsdl/xsd condivisi nella issue: #4253, risulta una risposta valida. Potete verificare e nel caso aggiornate questa issue, grazie.

Saluti,
Assistenza ANPR

**Comment by ATropeano** [comment]
Ho rimodellato le mie classi sull'ultimo rilascio dei Tracciati XSD e WSDL (https://www.anagrafenazionale.interno.it/wp-content/uploads/anpr-wsdl.zip), aggiornati al 5 febbraio 2024 e ho ancora il problema:
```
<?xml version="1.0" encoding="utf-16"?>
<RispostaP002 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <RispostaOKP002 xmlns="http://sogei.it/ANPR/P000sc">
    <testataRisposta xmlns="">
      <idOperazioneComune>350534</idOperazioneComune>
      <codMittente>037020</codMittente>
      <codDestinatario>ANPR05</codDestinatario>
      <operazioneRichiesta>P002</operazioneRichiesta>
      <dataOraRichiesta>2024-02-07T15:26:05.858375+01:00</dataOraRichiesta>
      <idOperazioneANPR>1629799172</idOperazioneANPR>
      <esitoOperazione>0000</esitoOperazione>
    </testataRisposta>
    <criteriRicerca xmlns="">
      <codiceRichiesta>29006171</codiceRichiesta>
    </criteriRicerca>
    <dettaglio xmlns="">
      <codiceRichiesta>29006171</codiceRichiesta>
      <idTipologia>2</idTipologia>
      <dataApertura>2024-02-07T15:04:36+01:00</dataApertura>
      <dataScadenza>2024-02-09T23:59:59+01:00</dataScadenza>
      <dataUltimoAggiornamento>2024-02-07T15:04:36+01:00</dataUltimoAggiornamento>
      <numeroProroghe>0</numeroProroghe>
      <statoRichiestaCorrente>
        <idStato>2</idStato>
        <operatore />
        <dataStato>2024-02-07T15:04:36+01:00</dataStato>
      </statoRichiestaCorrente>
      <recapiti>
        <recapito>
          <idTipologiaRecapito>1</idTipologiaRecapito>
          <valoreRecapito>XXXXXX</valoreRecapito>
        </recapito>
        <recapito>
          <idTipologiaRecapito>3</idTipologiaRecapito>
          <valoreRecapito>YYYYYYY</valoreRecapito>
        </recapito>
      </recapiti>
    </dettaglio>
  </RispostaOKP002>
</RispostaP002>
```

**Comment by ATropeano** [comment]
Il problema è che nella stream della risposta fornita è presente il tag
 ```          
          <identificativi>
            <idANPR>xxxxx</idANPR>
          </identificativi>
 ```         
          dopo il tag   <recapiti>   e prima del tag   <soggettoRichiedente>
          
          mentre in vocabolarioP000sc.xsd l'elemento tipoDettaglioP002, che descrive la risposta,  non contiene <identificativi> , per cui la risposta viene tagliata in fase di serializzazione.

**Comment by gppbarone** [comment]
Buongiorno, probabilmente non siete aggiornati all'ultima versione degli xsd/wsdl per questo state beccando questo problema, ti allego il link alla issue dove abbiamo inserito il file zip con gli xsd/wsdl aggiornati al  **23/01/2024**, https://github.com/italia/anpr/issues/4253#issuecomment-1906076240, l'ultima versione degli xsd/wsdl è questa: **wsdlP000-8-3-0-rc-1**.

Saluti,
Assistenza ANPR.

**Comment by AMonopoliADS** [comment]
scusate se mi intrometto, ma diventa complicato stare dietro ad un versioning di questo tipo, gestito nel contenuto delle issue.
noi abbiamo avuto lo stesso problema, e le stesse difficoltà di @ATropeano a capire quale fosse l'ultima versione degli schemi, per arrivare poi - per tentativi successivi - alla "wsdlP000-8-3-0-rc-1".

il fatto che gli schemi, sul portale, risultino aggiornati al 05/02/24 lascia pensare che comprendano anche gli ultimi rilasci dei servizi P000 (e invece non è così, xchè i file contenuti nello zip sono aggiornati al 13/12/23).

c'è una ragione per la quale i file del servizio P000 non sono aggiornati nello ZIP distribuito sul portale ANPR?
oppure è possibile avere la versione definitiva pubblicata lì (dove abitualmente scarichiamo la documentazione tecnica)?
giusto per avere qualche certezza in più...

grazie
Alessandro Monopoli ADS

**Comment by gppbarone** [comment]
I wsdl erano stati forniti nella issue per permettere l'integrazione prima del rilascio in produzione. Ad oggi il software è invece rilasciato in produzione e possiamo  considerarlo consolidato con questa versione **wsdlP000-8-3-0-rc-1** e recependo la vostra indicazione provvederemo a farli pubblicare sul portale ANPR nella sezione documentazione tecnica dove siete soliti recuperarli.

Grazie,
Assistenza ANPR

**Comment by gppbarone** [comment]
Abbiamo provveduto ad aggiornare la cartella **wsdlP000** dello zip presente su documentazione tecnica del portale ANPR (**anpr-wsdl.zip**).
Fateci sapere se riscontrate ancora il problema.

Grazie,
Assistenza ANPR

**Comment by ATropeano** [comment]
Buonasera. Per quel che mi risulta ad oggi, il file **https://www.anagrafenazionale.interno.it/wp-content/uploads/anpr-wsdl.zip** corrispondente all'ultima versione ufficiale in produzione,  contiene ancora una versione diversa degli P000 rispetto a quella in **wsdlP000-8-3-0-rc-1**.

**Comment by ATropeano** [comment]
Ok. Grazie. Chiudi pure questa issue.
