### ISSUE TITLE
[C019 - Accertamento esistenza in vita] Errore 404 - Unknown Api Request

### ISSUE THREAD

**Issue by MPaoletti719** [italia/anpr#4394]
Buonasera,
sto cercando di invocare il servizio accertamentoEsistenza in vita, ma ricevo il seguente errore:

response = {'type': 'https://govway.org/handling-errors/404/NotFound.html', 'title': 'NotFound', 'status': 404, 'detail': 'Unknown API Request', 'X-Global-Transaction-ID': '7dbb991665c2792a08bc818d'}

Riesco a staccare il voucher, che al suo interno ha anche le informazioni sull'algoritmo di hash. Sto usendo come Audience e Target:

audience = "https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1"
target = "https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002"

il json di chiamata è :
request = '{ "idOperazioneClient": "dev-1706018181495", "criteriRicerca": { "codiceFiscale": "DPLPRM90R10H501I" }, "datiRichiesta": { "dataRiferimentoRichiesta": "2024-01-01", "motivoRichiesta": "esistenza in vita", "casoUso": "C019" } }'

Sapreste darmi maggiori informazioni riguardo l'errore che riscontro?

Grazie in anticipo

**Comment by signocob2** [comment]
Ciao, siamo partiti dal client scaricabile da qui: https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

**Comment by MPaoletti719** [comment]
ciao @signocob2 , scusami potresti scrivermi l'url completo della chiamata al servizio e il json di chiamata che state utilizzando?
Grazie ancora per il supporto

**Comment by signocob2** [comment]
Ciao @MPaoletti719 , gli url sono:

1. Per Collaudo --> https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
2. Per Produzione --> https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

Per il Json non ce l'ho comodo, ma dovresti trovarlo sul repo https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

**Comment by sommafa** [comment]
> Ciao, sono anche io un fruitore.
> 
> Se può esserti utile, noi stiamo riuscendo a richiamare il servizio correttamente utilizzando però audience = "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1"

ciao @signocob2, questa audience quando la usi? per la chiamata per il token o per la chiamata all'endpoint del servizio?
io non riesco a trovare con precisione quali siano i parametri giusti di aud da usare e in quali casi.

grazie

**Comment by MPaoletti719** [comment]
Sono riuscito a chiamare il servizio partendo da questo codice: https://github.com/italia/anpr/issues/3964#issuecomment-1767932441
