### ISSUE TITLE
P00X : identificativi ANPR

### ISSUE THREAD

**Issue by busaster** [italia/anpr#4396]
Buongiorno,

integrando la nostra implementazione dei servizi in oggetto con le specifiche relativa alle dichiarazioni di residenza di cittadini UE ho notato che nell'oggetto TipoDettaglioP002 è stato aggiunto l'attributo identificativi di tipo TipoIdentificativi. Questo  attributo fa riferimento al soggetto "soggettoRichiedente" oppure al soggetto "soggettoInteressato" ? 
Io presumo al secondo ma preferisco avere da voi la conferma.

Grazie

**Comment by gppbarone** [comment]
Buongiorno,
soggettoInteressato non è mai valorizzato perché era previsto nel caso di delega SPID, iniziativa che non è andata avanti. idANPR dentro il tag identificativi fa riferimento al soggettoRichiedente cioè il cittadino che presenta la richiesta.
Restiamo a disposizione per dubbi e chiarimenti.

Saluti,
Assistenza ANPR

**Comment by busaster** [comment]
Perfetto grazie
