### ISSUE TITLE
P00x: dubbi TipoComponenteIsc

### ISSUE THREAD

**Issue by busaster** [italia/anpr#4397]
In merito al tipo dati in oggetto ho bisogno di un paio di chiarimenti:
1. L'attributo "localitaEstera" indica la località estera di nascita ?
2. Quali valori può assumere il campo "statoNascitaNonAttribuibile" ?
3. Nell'attributo "cittadinanza" quali valori può assumere il campo "idCittadinanza" ?

**Comment by gppbarone** [comment]
Buongiorno, 
1. localitaEstera nel tipoComponenteIsc fa riferimento alla località estera di nascita dei soggetti inseriti nella dichiarazione.
2.  statoNascitaNonAttribuibile può assumere qualsiasi stringa di testo inserita dal Cittadino in fase di inserimento della dichiarazione quando seleziona stato non attribuibile nel campo stato di nascita.
3. idCittadinanza è un identificativo interno ad ANPR, potete far riferimento al campo nomeCittadinanza all'interno del complexType tipoCittadinanza che rappresenta la sua decodifica.

Saluti,
Assistenza ANPR

**Comment by busaster** [comment]
Ah, come mai non avete usato il codice dello stato di cittadinanza come in tutti gli altri servizi ANPR ?

**Comment by gppbarone** [comment]
Da dove prendete questi codici di stato di cittadinanza?

**Comment by migmar68** [comment]
è la tabella ufficiale di ANPR. https://www.anagrafenazionale.interno.it/wp-content/uploads/tabella_2_statiesteri.xlsx
@busaster si riferisce alla colonna K "CODISTAT" che è quella usata nei servizi ANPR che esistono da anni.
nei nuovi servizi tipo ANSC ho notato l'uso della colonna A "ID" .

Marco Migliori

**Comment by LSPAG** [comment]
Buongiorno, il campo nomeComuneNascita si riferisce al nome del comune di nascita italiano?
Se si, considerato che è stato esposto per il comune estero l'oggetto località, come mai non è stato usato l'oggetto luogo di nascita che comprende entrambi, cosi come per gli altri servizi?

**Comment by gppbarone** [comment]
Buongiorno, il campo si riferisce al nome del comune di nascita italiano. Abbiamo scelto di utilizzare questo tipo invece di luogo di nascita.

Saluti,
Assistenza ANPR
