### ISSUE TITLE
[C019] Bad request 400 con tutti i token validi

### ISSUE THREAD

**Issue by unclejoe-code** [italia/anpr#4398]
Buongiorno, 
ho ri controllato il flusso delle chiamate e sembra essere conforme all'applicazione java fornita nel ticket: #3964

"govway_id":"a97ab21c-c59a-11ee-83e4-005056ae5232"

Controllando il payload sembra essere corretto ma non riesco ad andare oltre.

Provando ad eseguire una verifica incrociata e lanciando l'applicazione java fornita cambiando i parametri ottengo:
400 Bad Request
X-Global-Transaction-ID = [3f7e3e2d65c35c62aa4cd35d]

Potreste darmi per favore supporto?

Grazie.

**Comment by unclejoe-code** [comment]
la richiesta e' la seguente:
{
    idOperazioneClient = Guid.NewGuid().ToString(),
    criteriRicerca = new
    {
        codiceFiscale = "STTSGT90A01H501J"
    },
    datiRichiesta = new
    {
        dataRiferimentoRichiesta = "2024-01-17",
        casoUso = "C019",
        motivoRichiesta = "Verifica esistenza in Vita"
    }
}

**Comment by unclejoe-code** [comment]
Aggiornamento nella pagina "Debug client" ho tutti i flag verdi ma continuo ad avere 400:

GovWay-Transaction-ID:c9946f44-c9ac-11ee-ae6a-005056ae5232

E' possibile capire cosa c'e che non va?

**Comment by unclejoe-code** [comment]
Tutti i token sono validi secondo la pagina di debug e sono validi anche secondo il sito https://jwt.io ma continuo ad ricevere 400.

Puo' essere che il calcolo del digest (e quindi dello Sha256) si differente tra java e c# e questo crei problemi?

Passo un'altra referenza magari puo' essere di aiuto a capire il problema.
GovWay-Transaction-ID:c8b8bb8c-cb3c-11ee-a97e-005056ae1884

l'algoritmo di hashing di Java utilizza un unsigned int mentre quello di c# e signed, potrebbe essere questa la causa?

**Comment by RudyColombo** [comment]
> Tutti i token sono validi secondo la pagina di debug e sono validi anche secondo il sito https://jwt.io ma continuo ad ricevere 400.
> 
> Puo' essere che il calcolo del digest (e quindi dello Sha256) si differente tra java e c# e questo crei problemi?
> 
> Passo un'altra referenza magari puo' essere di aiuto a capire il problema. GovWay-Transaction-ID:c8b8bb8c-cb3c-11ee-a97e-005056ae1884
> 
> l'algoritmo di hashing di Java utilizza un unsigned int mentre quello di c# e signed, potrebbe essere questa la causa?

Anche utilizzando in c# il medesimo algoritmo utilizzato in JAVA il problema è lo stesso. Anche utilizzando il software in JAVA messo a disposizione in qualche issue, viene a proporsi il medesimo problema (anche avendo tutti i JWT e  il digest prodotti in egual modo

**Comment by afrontera85** [comment]
> Buongiorno, ho ri controllato il flusso delle chiamate e sembra essere conforme all'applicazione java fornita nel ticket: #3964
> 
> "govway_id":"a97ab21c-c59a-11ee-83e4-005056ae5232"
> 
> Controllando il payload sembra essere corretto ma non riesco ad andare oltre.
> 
> Provando ad eseguire una verifica incrociata e lanciando l'applicazione java fornita cambiando i parametri ottengo: 400 Bad Request X-Global-Transaction-ID = [3f7e3e2d65c35c62aa4cd35d]
> 
> Potreste darmi per favore supporto?
> 
> Grazie.

L'errore relativo al govway_id fornito è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

**Comment by unclejoe-code** [comment]
Grazie per le info ma ancora nulla:

"govway_id":"9fa8f50f-cc1a-11ee-8a6d-005056ae5232"
di seguito il token decodificato e le parti sensibili mascherate
{
  "jti": "xxx",
  "sub": "xx",
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1",
  "iss": "xxxx",
  "iat": 1708013851,
  "nbf": 1708013851,
  "exp": 1708613851,
  "signed_headers": [
    "digest",
    "SHA-256=0SQnpxWjJ+J2scChgH64PoLRdmVBjGqU8lnHsoHbWq0=",
    "content-type",
    "application/json"
  ]
}

**Comment by unclejoe-code** [comment]
ok grazie per l'input ora e' cosi inizialmente era cosi ma quando mi hai detto che si aspettava un array l'ho cambiato:
"govway_id":"9d8d124b-cc42-11ee-8a6d-005056ae5232"

{
  "jti": "********",
  "sub": "**********",
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1",
  "iss": "********",
  "iat": 1708029756,
  "nbf": 1708029756,
  "exp": 1708629756,
  "signed_headers": [
    {
      "digest": "SHA-256=0SQnpxWjJ+J2scChgH64PoLRdmVBjGqU8lnHsoHbWq0="
    },
    {
      "Content-Type": "application/json"
    }
  ]
}

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Content-Type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by unclejoe-code** [comment]
Grazie @afrontera85  

request.Content = new StringContent(bodyJson, new MediaTypeHeaderValue(contentType));

Imposta l'header come tu hai suggerito:

mentre prima utilizzavo 
new StringContent(bodyJson, Encoding.UTF8, contentType); 
che Imposta l'header a application/json:;charset=utf-8 

ma se firmassi gli header con application/json:;charset=utf-8 e cambiassi poi l'header di conseguenza application/json:;charset=utf-8 potrebbe funzionare?

**Comment by unclejoe-code** [comment]
Ora funziona tutto, grazie per il supporto

**Comment by ILuCiOne** [comment]
Ciao, posso chiederti come hai risolto ? 
Grazie Mille

**Comment by giuseppecaferra** [comment]
> Ciao, posso chiederti come hai risolto ? Grazie Mille

l'ho spiegato nel commento [qui](https://github.com/italia/anpr/issues/4398#issuecomment-1948402003)

nel mio caso era la discordanza tra la firma nell'header della signature che veniva impostata di default a 'application/json:;charset=utf-8'
