### ISSUE TITLE
Errore generico 400

### ISSUE THREAD

**Issue by RudyColombo** [italia/anpr#4399]
Buongiorno,

In merito al servizio https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002/ 

Impostando i seguenti header:
"Digest": contenente la firma SHA256 del body
"Agid-JWT-TrackingEvidence":  il token JWT cui è stato mandato l'hash in fase di recupero del token di autenticazione
"Agid-JWT-Signature": il token JWT contente nel payload nel campo singed_header il digest del body
"Authorization": "Bearer " + il campo "access_token" restituito dal servizio https://auth.uat.interop.pagopa.it/token.oauth2

Effettuando una chiamata con la seguente body:

`{"idOperazioneClient":"1707330849","criteriRicerca":{"codiceFiscale":"QRTSGT90A01H501B"},"datiRichiesta":{"dataRiferimentoRichiesta":"2024-02-07","motivoRichiesta":"u00001","casoUso":"C0001"}}`

Rileviamo ils eguente errore generico.

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"24db7678-c5e1-11ee-a4d8-005056ae1884"}`

Quale errore viene riscontrato nella transazione 24db7678-c5e1-11ee-a4d8-005056ae1884 ?

**Comment by MPaoletti719** [comment]
Parti da questo progetto java: https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

**Comment by afrontera85** [comment]
> Buongiorno,
> 
> In merito al servizio https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002/
> 
> Impostando i seguenti header: "Digest": contenente la firma SHA256 del body "Agid-JWT-TrackingEvidence": il token JWT cui è stato mandato l'hash in fase di recupero del token di autenticazione "Agid-JWT-Signature": il token JWT contente nel payload nel campo singed_header il digest del body "Authorization": "Bearer " + il campo "access_token" restituito dal servizio https://auth.uat.interop.pagopa.it/token.oauth2
> 
> Effettuando una chiamata con la seguente body:
> 
> `{"idOperazioneClient":"1707330849","criteriRicerca":{"codiceFiscale":"QRTSGT90A01H501B"},"datiRichiesta":{"dataRiferimentoRichiesta":"2024-02-07","motivoRichiesta":"u00001","casoUso":"C0001"}}`
> 
> Rileviamo ils eguente errore generico.
> 
> `{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"24db7678-c5e1-11ee-a4d8-005056ae1884"}`
> 
> Quale errore viene riscontrato nella transazione 24db7678-c5e1-11ee-a4d8-005056ae1884 ?

L'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')
