### ISSUE TITLE
Web-App Registrazione - Mutazione tutti i dati Permesso di soggiorno 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#44]
Data test 22/03/2017 - Ambiente test (dptest)
ID soggetto ANPR 962218, trattasi di straniero con permesso di soggiorno senza data di scadenza valorizzata da subentro, abbiamo inserito data scadenza con valore = 16/7/2014. 
Dopo il salvataggio è comparso il messaggio "Operazione eseguita correttamente" e poi il warning "ES032-Data scadenza permesso di soggiorno 16-07-2014 minore o uguale della data corrente".
L'errore dovrebbe essere bloccante poichè si deve poter inserire solo una data di scadenza maggiore uguale alla sysdate.
Riteniamo che tale operazione eventualmente possa essere consentita solo ad alcuni utenti con specifiche abilitazioni per situazioni particolari. 
ID OPERAZIONE ANPR = 442845
Grazie
Stefania Amprimo, Annamaria Gillone - Comune di Torino

**Comment by gcarbonin** [comment]
Valuteremo con il Ministero dell'Interno

**Comment by gcarbonin** [comment]
Ci sembra che l'applicazione funzioni correttamente così; avverte che il permesso di soggiorno è scaduto ma consente di inserirlo come dato storico.
