### ISSUE TITLE
[4003] Download prospetto statistico: richiesta info

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#440]
buongiorno

con servizio 4003 richiedo l'elaborazione di un prospetto statistico.
il ws mi risponde con l'idANPR assegnato alla richiesta.
come faccio ad eseguire il download del prospetto statistico via web-service?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Si interroga la risposta con l'id ricevuto tramite servizio 3005 o 3007
