### ISSUE TITLE
Dove posso trovare l'API swagger per l'endpoint [C019 - Accertamento esistenza in vita]?

### ISSUE THREAD

**Issue by ghost** [italia/anpr#4400]
Buongiorno,

Vorrei semplicemente sapere dove posso trovare il swagger per l'API. Devo chiamare l'endpoint [C019 - Accertamento esistenza in vita].

Grazie

**Comment by MPaoletti719** [comment]
Ciao, puoi trovarla accedendo qui https://selfcare.pagopa.it/auth/login e navigando nei tuoi client. Allego comunque la versione che ho scaricato io 
[C019-servizioAccertamentoEsistenzaVita.zip](https://github.com/italia/anpr/files/14207756/C019-servizioAccertamentoEsistenzaVita.zip)

**Comment by MPaoletti719** [comment]
Parti da qui https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

i puntamenti ci collaudo sono:
audienceErogatore" value="https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1"
audiencePDND" value="auth.uat.interop.pagopa.it/client-assertion"
UrlErogatore" value="https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002"
