### ISSUE TITLE
[C019] Bad request 400 ambiente Collaudo

### ISSUE THREAD

**Issue by MPaoletti719** [italia/anpr#4402]
Buongiorno,
sto cercando di invocare il servizio di accertamentoEsistenzaInVita ma ricevo questo errore:

 "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "8252d8fd-c668-11ee-83c1-005056ae5232"

Sapreste dirmo cosa sto sbagliando? Sto invocando il servizio qui:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

Grazie in anticipo

**Comment by MPaoletti719** [comment]
ricevo 404 ora

**Comment by unclejoe-code** [comment]
ciao @MPaoletti719  potresti spiegare cosa hai cambiato?


Grazie

**Comment by MPaoletti719** [comment]
Ho corretto la parte in cui generavo l'Agid-JWT-Signature, ora ricevo 404:
X-Global-Transaction-ID: 7dbb991665c5f761166170bd

**Comment by unclejoe-code** [comment]
grazie mille, leggendo in giro il 404 dovrebbe dipendere dal fatto che i dati che stai cercando non sono presenti, stai utilizzando un CF presente in Collaudo?

**Comment by MPaoletti719** [comment]
Grazie a te! Sto usando i cf in questo file:
[casiTest_consultazione.xlsx(1).xlsx](https://github.com/italia/anpr/files/14220397/casiTest_consultazione.xlsx.1.xlsx)
Nello specifico;
"{"idOperazioneClient": "10", "criteriRicerca": { "codiceFiscale": "SGGTTV60A01H501T" }, "datiRichiesta": { "dataRiferimentoRichiesta": "2024-02-06", "motivoRichiesta": "1", "casoUso": "C001" }}

**Comment by unclejoe-code** [comment]
prova a cambiare il casoUso in C019

**Comment by MPaoletti719** [comment]
Niente, purtroppo ricevo lo stesso errore

**Comment by afrontera85** [comment]
il 404 potrebbe essere dovuto all'url errato, oppure è errato o manca il voucher pdnd. 
Per il dettaglio dell'errore ci serve il govway_id
