### ISSUE TITLE
ANPR  non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by ssetbin** [italia/anpr#4406]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:
![捕获](https://github.com/italia/anpr/assets/159481086/6eb246e3-235e-464f-89ab-d985d8729119)

**Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.**

Cosa devo fare? Il comune non sa come aiutarmi.

Io sono
Cognome LI  
Nome SONGSEN
Nato a: CINA
Prime 6 cifre del Codice Fiscale  LIXSGS

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
