### ISSUE TITLE
C019-servizioAccertamentoEsistenzaVita - errore InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by paolochinellato** [italia/anpr#4407]
Come indicato nella issue https://github.com/pagopa/pdnd-interop-frontend/issues/723
riporto la segnalazione del problema.

Rieseguito il test tramite clientApiAnprPdnd con la  seguente risposta:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"36dea748-c726-11ee-95f3-005056ae5232"}

Fruitore: Assicurazioni Generali
Piattaforma: ANPR
Ambiente: Collaudo
Data del test: 2024/02/09
Orario: intorno alle 10:18

**Comment by robertog79** [comment]
Ciao Paolo,
abbiamo lo stesso errore per la compagnia per la quale lavoro, se vuoi possiamo provare a fare sinergia e trovare una soluzione insieme.
Grazie Roberto

**Comment by paolochinellato** [comment]
con openssl puoi generare le chiavi pubblica e privata

**Comment by robertog79** [comment]
fatto, ma il problema rimane

**Comment by MPaoletti719** [comment]
Ciao, ti consiglio di partire da questo progetto java : https://github.com/italia/anpr/issues/3964#issuecomment-1767932441

**Comment by robertog79** [comment]
Grazie proviamo
