### ISSUE TITLE
ws [2001] - verifica dati atto di decesso

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#441]
Buon giorno,
abbiamo appena effettuato una prova di registrazione del decesso di un residente, utilizzando il ws in oggetto. Tracciando la fase di invio dei dati mi sono accorto che l'atto di decesso per errore aveva come anno il 2015. La cancellazione però è andata a buon fine, riportando come unico warning quello (atteso) che ricorda di modificare lo stato civile del coniuge, essendo l'individuo deceduto coniugato. 
Nessuna segnalazione pertanto è stata sollevata sull'anno dell'atto di nascita, ed infatti dalla successiva consultazione dei dati del decesso risulta come anno dell'atto il 2015.
L'id operazione comune è il 3080, il test è stato effettuato in data 01/12/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Buongiorno,
stiamo provvedendo ad inserire un controllo che verifichi  che l’anno dell’atto, nonché, la data formazione dell’atto, non sia precedente alla data dell’evento.
Faremo sapere appena è possibile riprovare.
Grazie per la segnalazione

**Comment by gcarbonin** [comment]
L'intervento è stato effettuato
