### ISSUE TITLE
C019 - Servizio Esistenza in vita, richiesta aiuto

### ISSUE THREAD

**Issue by sommafa** [italia/anpr#4417]
Ciao a tutti,
chiedo supporto a chiunque sia stato in grado di ottenere un token valido per il servizio C019.

Dal tool di debug, ottengo sempre che l'aud nella richiesta non è valido.

Quali valori state usando voi per riuscire ad ottenere il voucher?

Questi sono i valori che sto inserendo io nella richiesta:

```
Headers:
"kid" _settings.KeyId
"alg" RS256
"typ" JWT

Payload:
"iss", _settings.Issuer
"sub", _settings.Subject
"aud", _settings.Audience
"purposeId" _settings.PurposeId
"jti" jti (calcolato al momento)
"iat" issued (calcolato al momento)
"exp" expire_in (calcolato al momento)
```

al payload, aggiungo inoltre il valore `digest` così composto

```
"alg" "SHA256"
"value" digest (dell'agid tracking signature)
```

grazie

**Comment by MPaoletti719** [comment]
Ciao, ti consiglio di partire da questo script java: https://github.com/italia/anpr/issues/3964#issuecomment-1767932441
In collaudo comunque io uso questi parametri:

<add key="audienceErogatore" value="https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1" />
<add key="audiencePDND" value="auth.uat.interop.pagopa.it/client-assertion" />
<add key="UrlErogatore" value="https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002" />

**Comment by MatteoSoftlab** [comment]
Partendo dal client di esempio riesco ad ottenere un voucher valido e ad effettuare una prima chiamata verso il servizio target (nel mio caso C019). Poi però se cerco di riutilizzare il voucher nel periodo di validità prendo un 400. Qualcuno è riuscito a riutilizzare un voucher ottenuto?

Grazie

**Comment by afrontera85** [comment]
riprovate, rimanendo entro i 10 minuti
