### ISSUE TITLE
Esistenza vita [C019] Errore  - Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by ghost** [italia/anpr#4419]
Buongiorno,

Continuo a ricevere l'errore sopra quando invio la chiamata a: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

**HEADER**
Nell'header come autorizazione uso Bearer Token con l'access_token generato che è valido per 600 secondi.

**BODY**
{
  "idOperazioneClient": "1",
  "criteriRicerca": {
    "codiceFiscale": "STTSGT90A01H501J"
  },
  "datiRichiesta": {
    "dataRiferimentoRichiesta": "2024-02-15",
    "motivoRichiesta": "esistenza in vita",
    "casoUso": "C019"
  }
}

**RISPOSTA**
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "e64e280c-cbfd-11ee-8a6d-005056ae5232"
}

Penso che il problema è nella header ma non ho trovato spiegazione di come impostare l'header.

Qualcuno mi potrebbe puntare nella direzione giusto?

Grazie

**Comment by afrontera85** [comment]
L'errore relativo al govway_id indicato è: 
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente.
C'e' un client di esempio nella issue github #3964, dove trova anche il documento di riferimento relativo ai profili di sicurezza delineato da AGID. Come potete verificare dallo yaml, anpr implementa INTEGRITY_REST_02 e AUDIT_REST_02.

**Comment by afrontera85** [comment]
i profili da implementare sono AUDIT_REST_02 e INTEGRITY_REST_02 e nelle linee guide ci stanno tutte le indicazioni necessarie.
Se le serve un esempio può dare un'occhiata al client che abbiamo fornito

**Comment by afrontera85** [comment]
Gli endpoint li trova nel file yaml, sia di validazione, sia di produzione.
La chiamata è una sola e la sequenza con cui costruire i token la può vedere nel client java di esempio.
Più di questo non posso dirle
