### ISSUE TITLE
EN112 - Il procedimento indicato èinesistente 

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#442]
Comune di Cortina d'Ampezzo - Produzione
Inviando e concludendo l'operazione numero 1428698 operazione di cancellazione del cittadino IDANPR 19086436 ho l'errore in oggetto.

Tuttavia l'operazione pare conclusa correttamente.

Grazie

**Comment by gcarbonin** [comment]
Il messaggio in oggetto non si riferisce all'operazione indicata.  Chiarito telefonicamente
