### ISSUE TITLE
Impossibilità di accedere alla piattaforma ANPR

### ISSUE THREAD

**Issue by enzozbest** [italia/anpr#4421]
Buongiorno,

Sono attualmente incapace di accedere alla piattaforma ANPR. Ho provato a effettuare il login più volte senza successo.

Inoltre, ho cercato di contattare il comune di Roma per verificare se ci sono anomalie nei miei dati o se il problema è dovuto a un'altra causa, ma finora non ho ricevuto risposta.

Mi piacerebbe comprendere se il mio accesso è stato disabilitato a causa di problemi relativi ai dati o se esiste un altro problema tecnico.

Prima 6 lettere del codice fiscale: BSTNZE

Grazie anticipatamente.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
