### ISSUE TITLE
Dichiarazione residenza ANPR -  Modifica Stato e Note Richiesta: Pratica non gestita correttamente: fase di elaborazione assente

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4423]
Il comune di Cinisello Balsamo non riesce a gestire la seguente dichiarazione di residenza:

29052868

Nella fase di cambio di stato da APERTA a IN LACVORANZA riporta l'errore:

Modifica Stato e Note Richiesta: Pratica non gestita correttamente: fase di elaborazione assente

Dal nostro gestionale, la notifica è stata salvata già con la data di chiusura del prodimento con la stessa data dell'operatura.
Richiamando il servizio riporta il seguente errore:

Errore Anpr Cod: EN148 - Errore nell'impostazione dello stato/proroga pratica. Esito: 12003 -

**Comment by gppbarone** [comment]
Buongiorno, 
purtroppo per risolvere il problema possiamo intervenire sulla pratica e bonificare gli stati di lavorazione lato DB ma è necessario inviare una PEC dal comune di competenza verso la PEC di anpr chiedendo la variazione dello stato della pratica dallo stato APERTA (2) ad IN LAVORAZIONE (3).
 
Grazie,
Assistenza ANPR

**Comment by jonnyfx95** [comment]
Perfetto grazie del Feedback, faccio mandare una PEC direttamente dal Comune con riferimento a questo ticket.

Saluti, 

Jonathan

**Comment by gppbarone** [comment]
Buonasera, non è richiesto più l'invio della pec, abbiamo provveduto a bonificare la vostra pratica. Adesso lo stato attuale della pratica **29052868** è IN **LAVORAZIONE**. Riprovate a lavorare la pratica con i successivi stati di elaborazione, nel caso aggiornate la issue o procedete alla sua chiusura.

Saluti,
Assistenza ANPR

**Comment by jonnyfx95** [comment]
Ciao, 

Confermo che il problema è stato risolto, il comune è riuscito a mettere la pratica in ACCOLTA CON RISERVA.

Saluti, 

Jonathan
