### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio 2024

### ISSUE THREAD

**Issue by ioGabes** [italia/anpr#4425]
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

[https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth](url)
![Errore ANPR Servizi Anagrafi](https://github.com/italia/anpr/assets/160650676/fbde8419-8b5c-4aae-b872-92f43dab8d87)

Il problema è iniziato dopo che ho rilasciato il passaporto al consolato italiano a Parigi, Sono italiano e vivo in Francia, sono iscritto all'AIRE.  In allegato il messaggio di errore che appare quando provo ad accedere al portale sia con SPID che con CIE.

Le prime lettere del mio Codice Fiscale sono: LVRGRL
Mi potete aiutare?

Grazie!!

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
