### ISSUE TITLE
C019 ServizioEsistenzaInVita - Collaudo - 400 Bad Request for security

### ISSUE THREAD

**Issue by tech-riccardo** [italia/anpr#4426]
Buongiorno a tutti,
provando a richiamare il servizio https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002 otteniamo un errore di tipo 400 BAD REQUEST.
Abbiamo provato a replicare quanto riportato nelle issue già aperte inserendo nell'header delle chiamata sia il JWT token da voi staccato sia il campo Agid-JWT-Signature generato da codice.

La risposta ottenuta è la seguente:
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "bad27b75-d0dd-11ee-b444-005056ae1884"
}

Potreste per favore darci indicazione di cosa manca o è errato all'interno della richiesta?
Grazie

**Comment by tech-riccardo** [comment]
Ho provato ad integrare all'interno della chiamata anche altre header com il Digest, e Agid-JWT-TrackingEvidence ma otteniamo sempre questo errore:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "ab663a72-d17b-11ee-b294-005056ae1884"
}

potreste per favore supportarmi sull'anomalia.
Grazie,

**Comment by afrontera85** [comment]
Salve,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by tech-riccardo** [comment]
Abbiamo provato a modfificare il digest rendendolo conforme al messsaggio inviato, ma putroppo otteniamo ancora l'errore: 
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "7b333526-d264-11ee-a7c6-005056ae5232"
}

Potreste gentilmente indicarci cosa c'è ancora di errato?

Grazie,

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 3 eccezioni.
Header HTTP 'Digest' presente in una richiesta con http payload vuoto
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by tech-riccardo** [comment]
Ciao a tutti,
come da immagine ho provato a richiamare il servizio con tutti i parametri necessari, ma ottengo sempre l'errore 400.
![image](https://github.com/italia/anpr/assets/83093477/1c64baab-eec3-447a-9ded-0d6bed400457)

Potete per favore indicarmi se ci sono altre eccezioni?

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "13073a56-d48a-11ee-b6db-005056ae1884"
}

**Comment by afrontera85** [comment]
L'errore è questo:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
Calcolando il digest in base al payload inviato mi risulta dovrebbe essere questo (differente da quello inviato):
KzV/6lRtYfIilRCboOySQpNEUF69IFud0pSSijkTuaQ=
Si fa l'hash e poi la codifica in base64

**Comment by tech-riccardo** [comment]
Ciao,
ho provato a sincerarmi che tutto fosse come dicevi nel tuo commento e il codice è corretto, calcolando prima l'hase e poi il base64. Tuttavia ancora c'è questo errore:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"4eaf428c-d498-11ee-b753-005056ae5232"}

Mi potete dire l'eccezione nuova?
Provando dal client JAVA che suggerite nelle altre issue tutte le operazioni effettuate sono identiche.
Avete altre client da cui si può prendere spunto per gli sviluppi in .Net?

Grazie mille

**Comment by afrontera85** [comment]
Adesso l'errore è diverso:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Content-Type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by tech-riccardo** [comment]
Ciao,
attualmente nei signed_headers claim abbiamo questi valori:
  "signed_headers": [
    {
      "digest": "SHA-256=xNqvayZ0zkTiZxFF+ZxXi5Nr4X/82XcnQllzLbQvvFg="
    },
    {
      "content-type": "application/json"
    }
  ]

ma quello che otteniamo è questo:
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"94662391-d4a8-11ee-b6db-005056ae1884"}

Riusciti a dirmi la nuova eccezione?

Grazie,

**Comment by tech-riccardo** [comment]
Ciao,
abbiamo capito quale problema genera i backslash e dovremmo averli rimossi.
Potresti per favore dirmi quale eccezione c'è ora?

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"a062804b-d4ab-11ee-b6db-005056ae1884"}

Grazie mille,

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita:  Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by tech-riccardo** [comment]
Ciao,
ho notato che erao presenti due {} all'inizio errate e ti ringrazio per la risposta.
Mi potete dire se ora questa eccezione è ancora legata al Content-Type o altro?

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0b9a0955-d4b4-11ee-b753-005056ae5232"}

Grazie mille,

**Comment by afrontera85** [comment]
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido
Avete messo 
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1
invece di
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

**Comment by afrontera85** [comment]
potresti dirci il token Agid-JWT-TrackingEvidence che ci invii e anche il clientId?

**Comment by tech-riccardo** [comment]
Ciao a tutti,
i parametri sono i seguenti:

-  **Agid-JWT-TrackingEvidence**: eyJhbGciOiJSUzI1NiIsImtpZCI6InJWUGsxNXBKSzhnWlhEbnNGM2RiWnBJUkNNZjVJcHpwLWxUalRFcnAzRFkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIxY2ZjNzNhMS02ODU3LTRhMmYtYjZkYi04MmE0YjE1ZjQyZmYiLCJzdWIiOiIxY2ZjNzNhMS02ODU3LTRhMmYtYjZkYi04MmE0YjE1ZjQyZmYiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJwdXJwb3NlSWQiOiI5NjhjYWZlMC0wMmZlLTRmMGEtYjRjYy04ZWQ2OWEzYTgyZTAiLCJqdGkiOiI4ZTA3ZGQ4ZS1jMDdkLTQwZGUtYWUxMi0wNTBhNTIzNDQ4MWUiLCJkbm9uY2UiOiIxMjM0NTY3ODkxMTIzIiwiaWF0IjoxNzA5MDMwMjEyLCJleHAiOjE3MDkwNjYyMTIsInVzZXJJRCI6InVzZXJJU1YiLCJ1c2VyTG9jYXRpb24iOiIxNTEuMTkuMjE0LjE1NCIsIkxvQSI6IkxPQTMifQ.fMly5ZcoP-VLi2EanRf1V_npaVVugMGjoQ8T1J5iemcNF-tPc9G_fGjKRcg0x7cQKEthnuUiOd_bKo8xJ3jEUKbxevsvYYwOrEairP_kvhyZXmueaTnQtWgw2zo0x1O7NZmOnC-a5la3Alk0wr5HweRBHWTRwS-r0yDuKFHP5zv-QbkwYSUSV_VqYhCf3Ube6VozbrTNmpBoGnvAjc6Y0LaFqmD7Db6Nct4NmEzS4ERmJPAgV3fiB2qpYilbd8s--INWLfHlQ0OJ9EgAgIQxpiVdzaFtWrQP-COR5UbHQBT2NDIkurdj7e8DP1Z5cgdw4nveBrJ8Jh_8pkuwPGldMg
- **clientid**: 1cfc73a1-6857-4a2f-b6db-82a4b15f42ff

Fatemi sapere,
Grazie mille

**Comment by tech-riccardo** [comment]
Sistemando anche quest'ultima cosa il servizio mi sta rispondendo correttamente.
Grazie mille per il supporto ricevuto.
