### ISSUE TITLE
Errore 400 richiesta verso servizio PDND C001 in ambiente di collaudo

### ISSUE THREAD

**Issue by AdamoRiccardo** [italia/anpr#4427]
Buongiorno,

stiamo cercando di effettuare una richiesta verso il servizio PDND C001 (in ambiente di collaudo) ma riceviamo l’errore 400, vi invio l’ID della richiesta/risposta:

GovWay-Message-ID: 84b218cf-d17f-11ee-b294-005056ae1884
  GovWay-Transaction-ID: 59ad37e0-d17f-11ee-b294-005056ae1884

Premettiamo che abbiamo gestito il voucher dalla PDND e inserito anche Agid-JWT-TrackingEvidence e Agid-JWT-Signature, il contenuto della richiesta è semplicemente:
"{""idOperazioneClient"": ""22022024143518"", ""criteriRicerca"": {""codiceFiscale"": ""QRTSGT90A01H501B""}, ""datiRichiesta"": {""dataRiferimentoRichiesta"": ""2024-02-22"", ""motivoRichiesta"": ""TEST"", ""casoUso"": ""C001""}}"

Dai vostri log potete indicarci il motivo dello scarto?
Grazie.

**Comment by AdamoRiccardo** [comment]
@amollicone1982 è possibile avere un supporto? Grazie molte!

**Comment by amollicone1982** [comment]
L'errore che prendete è dovuto al fatto che il kid che specificate nei token
ImwnGJ3hvFT44Q4Q99FFG1tOQptji1VwuhXoUxUQ8Vk

non è presente sulla pdnd

**Comment by AdamoRiccardo** [comment]
@amollicone1982 Grazie! Vero, c'era un errore sul KID, tuttavia riscontriamo ancora errore 400, è possibile avere ancora dettagli su questa richiesta?
GovWay-Message-ID: 054f246b-1d0f-49c9-8a8e-1e86a021d18d
  GovWay-Transaction-ErrorType: InteroperabilityInvalidRequest
  GovWay-Transaction-ID: b7361061-d259-11ee-a7c6-005056ae5232
Grazie nuovamente!

**Comment by AdamoRiccardo** [comment]
@afrontera85 Grazie per tutte le indicazioni, abbiamo aggiunto HTTP Digest e messo signed_headers come vettore con il digest corretto ma ancora riceviamo errore 400, ecco l'id della richiesta: 
GovWay-Message-ID: 4f512f67-6add-46ce-b6fa-2fc87a62dbf3
GovWay-Transaction-ErrorType: InteroperabilityInvalidRequest
GovWay-Transaction-ID: 761878d5-d261-11ee-a7c6-005056ae5232
Grazie per le vostre indicazioni!

**Comment by afrontera85** [comment]
Risulta ancora Claim 'signed_headers' con un formato non valido; ricontrolli perchè forse col copia e incolla ha introdotto
dei caratteri in più (backslash)

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Header HTTP 'content-encoding', dichiarato tra gli header firmati, non trovato
Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by afrontera85** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita:  [Header 'Agid-JWT-TrackingEvidence'] Signature verification failed

**Comment by AdamoRiccardo** [comment]
@afrontera85 @amollicone1982  Grazie mille per il vostro prezioso supporto! Siamo riusciti ad ottenere la risposta!
