### ISSUE TITLE
Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 1: errore di stampa.

### ISSUE THREAD

**Issue by PSEdemografici** [italia/anpr#4433]
Buongiorno,

dalla Web App, funzioni: Consultazione ed estrazione/Movimenti Popolazione Comune, procedo con l'elaborazione e successiva stampa della  "Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 1" e, a seguire, "Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 2", per anno 2022 e 2023.

Una volta eseguita l'elaborazione delle rilevazioni sopra indicate, clicco sul tasto verde "Download File" in basso a destra e Salvo il file in f.to .pdf.

Aprendo il file "Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 1", noto che la rilevazione dell'anno 2022 e' corretta: sono presenti due fogli che contemplano le voci che vanno dalla voce n. 1 alla n.  40, mentre per l'anno 2023 il file prodotto contempla un solo foglio che parte dalla voce n. "22. Cancellati per altri motivi: violazione art.7 D.P.R. 223/89 (rinnovo dic. dimora abituale), omettendo le altre informazioni": perché?

L'assistenza invia una soluzione con l'iter per estrarre la statistica in seguito ad apertura ticket .Ma non risolve.
Aperto nuovo ticket stamattina.

Altra questione: la ripartizione della popolazione straniera presente nel punto "33. Totale popolazione", non coincide con la popolazione straniera della rilevazione "Rilevazione annuale movimento e calcolo popolazione residente totale e straniera - sez. 2": qual e' la modalità di estrazione del conteggi? Qual e' la differenza tra i due totali?

Nel ringraziare per la disponibilità, cordiali saluti.

Valentina Mentonelli
Comune di porto Sant'Elpidio

[RilevazioneMovimentoAnnuale.pdf](https://github.com/italia/anpr/files/14418490/RilevazioneMovimentoAnnuale.pdf)

**Comment by azabatta** [comment]
Buongiorno,
nelle date a cavallo tra gennaio e febbraio c'è stato un problema sull'elaborazione di alcuni prospetti, l'elaborazione del prospetto allegato alla presente issue rientra in tale range temporale (in alto a destra la data di elaborazione è 1° febbraio).
Per il comune di Porto Sant'Elpidio sono presenti a sistema altre 5 nuove richieste che devono essere ancora elaborate, tra queste una riguarda anche il prospetto allegato. 
Purtroppo l'elevata numerosità delle  richieste da parte di tanti comuni ha portato ad un ritardo nelle lavorazioni per cui bisogna attendere ancora un pò per disporre dei nuovi elaborati.
Saluti
