### ISSUE TITLE
C021 ServizioAccertamentoStatoFamiglia Richiesta Approfondimenti

### ISSUE THREAD

**Issue by dave-1982** [italia/anpr#4436]
Salve, scriviamo per conto di INAIL e per richiedere appronfodimenti sul servizio in oggetto.

1. InfoSoggettoEnte: E’ possibile avere la lista delle chiavi o delle tipologiche associate? Nei nostri test abbiamo trovato la sola chiave della data decesso:
es.: [{"chiave":"Data decesso","id":"1015","valoreData":"2024-01-25"}]

2. LegameSoggetto prevede gli attributi: "codiceLegame" e "tipoLegame".
Il nostro riferimento è https://www.anagrafenazionale.interno.it/area-tecnica/tabelle-di-decodifica/
CodiceLegame è stato associato al file "05	Relazione di parentela – Famiglia – xlsx": confermate?
TipoLegame ipotizziamo sia: "26 | Motivo costituzione della famiglia – xlsx"

In attesa di vostre
grazie

**Comment by azabatta** [comment]
Buonasera, 
rispondo nell'ordine:
1. le tipologiche variano in base all'eservice di interesse, prenderemo spunto da questa segnalazione per predisporre un'informativa al riguardo; 
2. Si descrivono di seguito i dati presenti nel gruppo dati “legame soggetto”: 
- tipo legame: vale 3 per famiglia residente in Italia, 4 per convivenza anagrafica (es. casa di cura, caserma, casa di pena etc.), 5 per famiglia AIRE 
- data decorrenza: la data a partire dalla quale il cittadino appartiene a quella famiglia o convivenza anagrafica 
- codice legame: decodifica tramite tabella 05 "Relazione di parentela" per cittadini residenti in famiglia (tipo legame 3 o 5) oppure 06 “Legame scheda convivenza” per cittadini residenti in convivenza (tipo legame 4). 

E' in corso di aggiornamento sulla PDND la documentazione  che accompagna gli eservice di ANPR al fine di aggiungere  elementi di dettaglio ai più importanti gruppi dato trattati. Tra questi anche quello suindicato al punto 2. 

Saluti
