### ISSUE TITLE
Errore Timeout Internal Error

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4439]
Ciao, 

Ci sono problemi con i servizi di ANPR?
Tutti i nostri clienti stanno ricevendo l'errore:

Errore Timeout Internal Error

E' possibile fare una verifica?

**Comment by UpiTorino** [comment]
Buongiorno,
confermo anche per Torino che da circa 50 minuti Sicradem restituisce errore "comunicazione con ANPR fallita" 
Si chiede cortesemente verifica e riscontro, grazie

U.P.I. Torino

**Comment by Barisctt** [comment]
Confermo anche su Bari stesso errore.

Vi preghiamo d iintervenire.

Grazie mille

**Comment by siscomanpr** [comment]
Buongiorno,
anche alcuni nostri clienti stanno segnalando errori di connessione, mentre ad alcuni sembra funzionare normalmente.
Grazie

**Comment by Maga63** [comment]
Anche a Milano stesso errore.

Grazie

**Comment by mttfranci** [comment]
Salve, rilevate ancora l'anomalia?

Grazie in anticipo.

**Comment by Maga63** [comment]
Confermo il regolare funzionamento.

Grazie

**Comment by mttfranci** [comment]
Perfetto grazie
