### ISSUE TITLE
Impossibile connettersi in modo sicuro alla pagina

### ISSUE THREAD

**Issue by ilucini** [italia/anpr#444]
Buongiorno,
da oggi (04/12/2017) pomeriggio quando tentiamo di accedere al sito https://dp.anpr.interno.it/com
viene riportato l'errore:
Impossibile connettersi in modo sicuro alla pagina
La causa potrebbe essere che il sito utilizza impostazioni di sicurezza TLS obsolete o non sicure. In tal caso, provare a contattare il proprietario del sito Web.

Anche dagli applicativi via webservices NON riusciamo ad accedere.
Cordialmente,
ilucini - Comune di Codogno(LO)

**Comment by RENZO63** [comment]
Comune di Valle Mosso - produzione

Speriamo che la cosa si risolva in fretta perche' il lavoro e' bloccato....

**Comment by gcarbonin** [comment]
Il problema si è risolto alle ore 15 (circa) di ieri. Ci scusiamo per il disservizio
