### ISSUE TITLE
PDND, Ambiente di Collaudo, C019

### ISSUE THREAD

**Issue by cla13** [italia/anpr#4442]
Stiamo effettuando delle prove di comunicazione con l'e-service C019 nell'ambiente di collaudo, ma abbiamo bisogno di avere delle informazioni aggiuntive sulla tipologia di errore prodotto.
L'errore ottenuto con l'ultimo test è il seguente:
{
"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
"title": "InteroperabilityInvalidRequest",
"status": 400,
"detail": "Received request is not conform to the required interoperability profile",
"govway_id": "ccf0e2e4-d9b9-11ee-85f5-005056ae1884"
}

Data e ora del tentativo : 04/03/2024 h. 01.53
Ambiente: Collaudo
client_id 1df3069a-84b8-4e2c-b241-8d840d248826
**purposeId ** 446014fb-1c85-4be7-8c10-2a74f5e7587f

**Comment by azabatta** [comment]
Buongiorno, 
questo l'errore riscontrato dal sistema:

Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by cla13** [comment]
Buongiorno,
grazie.
Ieri ho fatto delle richieste ed ho ricevuto delle risposte correttamente, ma oggi effettuando di nuovo la stessa chiamata ricevo 400.
Gentilmente, potreste darmi maggiori info su questo errore :
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0ec974b7-db89-11ee-9df7-005056ae5232"}

Grazie.

**Comment by azabatta** [comment]
Buongiorno, 
di seguito gli errori riscontrati:

Verifica ModI della richiesta fallita: Riscontrate 3 eccezioni.
Token non utilizzabile prima della data '2024-03-06_08:58:07.000'
Token creato nel futuro (data creazione: '2024-03-06_08:58:07.000')
 [Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2024-03-06_08:58:06.000'

Buon lavoro

**Comment by cla13** [comment]
grazie.
Settavo come date : Date.from(Instant.ofEpochSecond(currentTimeInSecs) e quindi non pensavo a questo problema.
Cmq settato qualche secondo in meno ed è riandata.
Grazie

**Comment by euberdeveloper** [comment]
> Stiamo effettuando delle prove di comunicazione con l'e-service C019 nell'ambiente di collaudo, ma abbiamo bisogno di avere delle informazioni aggiuntive sulla tipologia di errore prodotto. L'errore ottenuto con l'ultimo test è il seguente: { "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html", "title": "InteroperabilityInvalidRequest", "status": 400, "detail": "Received request is not conform to the required interoperability profile", "govway_id": "ccf0e2e4-d9b9-11ee-85f5-005056ae1884" }
> 
> Data e ora del tentativo : 04/03/2024 h. 01.53 Ambiente: Collaudo client_id 1df3069a-84b8-4e2c-b241-8d840d248826 **purposeId ** 446014fb-1c85-4be7-8c10-2a74f5e7587f



Sto riscontrando anche io lo stesso problema, il problema sta nel fatto che io servizio non accetta solamente il voucher pdnd ma vuole anche un altro token "agid". Ci sono informazioni su come crearne uno? Che valori devono essere messi su "aud" per il C019, e che valori per userID etc?

**Comment by amollicone1982** [comment]
I token da generare sono censito nello yaml presente sulla piattaforma pdnd e seguono le linee guida agid di cui allego documento:
[Documento operativo - Pattern sicurezza - v1.1.pdf](https://github.com/italia/anpr/files/14523056/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf)
Puo' trovare cmq un esempio di client java che implementa i profili di cui Anpr necessita al seguente github
https://github.com/italia/anpr/issues/3964

aud del C019 lo trova sulla pdnd come attributo del servizio (https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1) 
userID è un infortmazione di audit libera dove di solito si mette un identificativo dell'operatore che fa la chiamata (cf o matricola)

**Comment by euberdeveloper** [comment]
> I token da generare sono censito nello yaml presente sulla piattaforma pdnd e seguono le linee guida agid di cui allego documento: [Documento operativo - Pattern sicurezza - v1.1.pdf](https://github.com/italia/anpr/files/14523056/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf) Puo' trovare cmq un esempio di client java che implementa i profili di cui Anpr necessita al seguente github #3964
> 
> aud del C019 lo trova sulla pdnd come attributo del servizio (https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1) userID è un infortmazione di audit libera dove di solito si mette un identificativo dell'operatore che fa la chiamata (cf o matricola)

Non trovo il client java su #3964

L'errore di cui parlo si riferisce a #4449 e sembra c'entrare con la generazione del digest

**Comment by amollicone1982** [comment]
il client lo trova alla fine del github 3964 (ci sono molti item e quindi deve fare load more item).
Lo allego qui per facilità
Per l'errore rifaccia una prova e ci fornisca il govway-id
[clientAnpr-1.0.zip](https://github.com/italia/anpr/files/14528130/clientAnpr-1.0.zip)

**Comment by euberdeveloper** [comment]
C'è l'id qui:
https://github.com/italia/anpr/issues/4449#issuecomment-1983766082

**Comment by euberdeveloper** [comment]
Grazie comunque per lo zip

**Comment by euberdeveloper** [comment]
Salve @amollicone1982 , ho provato il client che mi ha gentilmente passato.

Stranamente, perfino con quel client ottengo questo errore:
```
GovWay-Transaction-ID: d6b546cb-dccb-11ee-9422-005056ae5232
{"type":"https://govway.org/handling-errors/404/UndefinedOperation.html","title":"UndefinedOperation","status":404,"detail":"Operation undefined in the API specification","govway_id":"d6b546cb-dccb-11ee-9422-005056ae5232"}
```
baseurlapi=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1

#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=XXX
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd=YYY
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalit� es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd=ZZZ
audPdnd=auth.uat.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.uat.interop.pagopa.it

#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

proxyhost=
proxyport=
proxyuser=
proxypwd=

fileTest=test1
```

il json test1 ha come valore:
```
{"idOperazioneClient":"1709307826151A","criteriRicerca":{"codiceFiscale":"SGGNNA90R50F839T"},"datiRichiesta":{"dataRiferimentoRichiesta":"2020-02-28","motivoRichiesta":"Prova per vedere se le api funzionano","casoUso":"C019"}}
```

Mentre in pk.priv sono sicuro che ci sia la nostra chiave privata

**Comment by cla13** [comment]
Buongiorno,
riscrivo per chiedere se fosse possibile sapere la causa dell'errore che ricevo invocando il servizio C019. Ricevo un 400 con "govway_id":"4030cb1a-f257-11ee-ba83-005056ae1884". Faccio una prima richiesta appena staccato il token e va bene, ma se poi la rifaccio dopo 5 minuti con lo stesso token ancora valido ricevo questo 400. Grazie.

**Comment by afrontera85** [comment]
L'errore che risulta è questo:
Verifica ModI della richiesta fallita: [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-04-04_09:40:42.000')

**Comment by cla13** [comment]
Grazie,
ma allora c'è un tempo dopo la quale anche se il token è ancora valido le richieste non possono essere fatte più con lo stesso token?
Ho staccato il token alle 09:40 con validità di 10 min e alle 9:47 ho ricevuto l'errore.
