### ISSUE TITLE
Client clientAnpr-1.0.zip - Errore 400

### ISSUE THREAD

**Issue by ILuCiOne** [italia/anpr#4443]
Come da oggetto: che tipo di errore segnala il seguente ID :

govway_id       3154f07e-da46-11ee-85f5-005056ae1884
detail          Received request is not conform to the required interoperability profile
type            https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html
status          400
title           InteroperabilityInvalidRequest

Grazie

**Comment by azabatta** [comment]
Buongiorno, 
di seguito gli errori riscontrati dal sistema:

Verifica ModI della richiesta fallita: Riscontrate 3 eccezioni.
[Header 'Authorization'] Token non contiene il claim 'purposeId'
 [Header 'Authorization'] Token non contiene il claim 'digest.alg'
[Header 'Authorization'] Token non contiene il claim 'digest.value'

Saluti

**Comment by ILuCiOne** [comment]
Grazie Mille per la pazienza! Ora funziona tutto
