### ISSUE TITLE
[C019] verifica massiva esistenza in vita

### ISSUE THREAD

**Issue by Davi84** [italia/anpr#4447]
Salve,

da normativa comunicazione IVASS è necessario richiamare il servizio per tutti gli assicurati in portafoglio (che per noi vuol dire 1mln di soggetti).
Il servizio REST sul singolo soggetto è molto inefficiente per fare questa verifica, in un'altra issue si citava un nuovo servizio massivo ( [LINK](https://github.com/italia/anpr/issues/4319#issuecomment-1882752934) ), ci sono aggiornamenti su questo tema?

grazie mille

**Comment by Davi84** [comment]
taggo @amollicone1982

**Comment by azabatta** [comment]
Buongiorno, 
non ci sono ancora novità, bisogna attendere.
Oltre all'implementazione tecnica c'è un iter amministrativo che deve essere completato.
Saluti

**Comment by Davi84** [comment]
@azabatta c'è una pianificazione?

**Comment by azabatta** [comment]
No,  inseriremo un  avviso quando il servizio sarà attivato in collaudo.
Saluti

**Comment by Davi84** [comment]
ok, grazie
