### ISSUE TITLE
Specifiche interfaccia - ID 5014-Rettifiche - Refuso

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#445]
Segnalo quello che mi sembra un refuso nella documentazione.

Il file rettifica102.xlsx descrive due attributi: motivoIscrizione e descrizioneMotivoIscrizione.

Nel file vocabolario5000mutazione.xsd invece si legge:
 <xs:complexType name="tipoRichiestaRettifica102">
    	<xs:sequence>
            <xs:element name="idMotivoIscrizione" type="tpdt:tipoMotivoIscrizione" minOccurs="1" maxOccurs="1"/>
			<xs:element name="note" type="tpdt:charMax240" minOccurs="0" maxOccurs="1"/>
			<xs:element name="provenienza" type="tpdt:tipoProvenienzaDestinazione" minOccurs="0" maxOccurs="1"/>

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
La documentazione è stata aggiornata
