### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by lauram123456** [italia/anpr#4451]
Buongiorno,
non appena provo a fare accesso con SPID o altre modalità al portale, appare questo messaggio di errore.

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

Prime 6 cifre del codice fiscale: MZZMLR

Vi ringrazio anticipatamente e invio cordiali saluti.

**Comment by lauram123456** [comment]
@[cmigliardi](https://github.com/cmigliardi)
cmigliardi
@[mttfranci](https://github.com/mttfranci)
mttfranci

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
