### ISSUE TITLE
ANPR. Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by ggsoriano** [italia/anpr#4452]
![162996604-7949cd0d-b2e9-4ee9-9d00-92aff52db5c8](https://github.com/italia/anpr/assets/162760061/5f5dfc46-caf0-4edd-b852-71a79db163dc)

Buongiorno, ho difficoltà ad entrare in ANPR

Potete aiutarmi? se vi possono essere utili ecco le prime sei lettere del mio codIce fiscale: SRNGNG (nato a SANTA FE, Argentina)

Quando provo ad entare mi dice cosi': Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
