### ISSUE TITLE
[C019] - Bad Request 400 - Interoperabilità Produzione

### ISSUE THREAD

**Issue by tech-riccardo** [italia/anpr#4454]
Ciao a tutti,
provando a richiamare il servizio di Produzione C019 otteniamo il seguente errore

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"2b5a8746-e051-11ee-bde3-005056ae6555"}

I criteri di ricerca sono impostati per codice fiscale.

Potresti dirmi cosa non torna con la richieste inviata?
Grazie mille.

**Comment by afrontera85** [comment]
L'errore è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by tech-riccardo** [comment]
Abbiamo corretto il parametro da voi indicato ed la chiamata ci risulta corretta.
Potete chiudere la Issue.

Grazie
