### ISSUE TITLE
[5008] Soggetto AIRE: Annullamento Matrimonio (EN243)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#446]
ambiente di PRODUZIONE - comune di Faenza - idOperazioneComune 2017002019

soggettoAIRE, caricato con il file di subentro (idSoggettoANPR 19090602).
come noto, il soggetto è stato popolato con il solo cognome del coniuge.

si sta tentando di comunicare l'annullamento del matrimonio, e siccome nella comunicazione vengono inseriti tutti i dati conosciuti (quindi anche il nome), il web-service ritorna errore bloccante

EN243 - E - I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto MANYA ILIANA DAVALOS ESPARZA(19090602) 

come fare, anche per il futuro, per non rimanere bloccati con variazioni dello stesso tipo?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
I dati del coniuge non sono obbligatori per l’annullamento del matrimonio; si può comunicare l'annullamento senza integrare i dati di origine, che, ricordo, sono quelli strettamente necessari per la formazione dell'elenco degli elettori.
Se si vogliono  modificare i dati del coniuge, prima di comunicare l’annullamento del matrimonio, si devono comunicare i dati corretti del coniuge (tipo mutazione 12 – matrimonio).
le due operazioni contemporaneamente (tipo mutazione 12 e 13) non sono attualmente consentite.
Stiamo lavorando su una nuova versione del  servizio 5008 che consente di integrare in un'unica soluzione i dati AIRE conferiti al subentro.

**Comment by AMonopoliADS** [comment]
grazie, con la modifica suggerita la comunicazione è andata a buon fine.
nell'attesa di potere integrare i dati, per queste variazioni AIRE evitiamo di passare i dati del coniuge

approfitto per girare un rilievo fatto da cliente:
se i dati di origine sono "quelli strettamente necessari per la formazione dell'elenco degli elettori", perchè in ANPR non è passato il flag di iscrizione nelle liste elettorali, seppure presente in file dell'ANAG-AIRE?

grazie

**Comment by gcarbonin** [comment]
Il campo esiste: è il tipo elettore

**Comment by gcarbonin** [comment]
Viene acquisito se trasmesso. Possiamo fare qualche verifica. Ha qualche id anpr per controllare?

**Comment by AMonopoliADS** [comment]
idSoggettoANPR 19090602 (ambiente di PRODUZIONE - comune di Faenza)

**Comment by gcarbonin** [comment]
E' popolato; risulta elettore in ANPR

**Comment by AMonopoliADS** [comment]
allora probabilmente il problema è che il campo non viene restitituito dal web-service di consultazione (vedere idOperazioneComune 2017002175)

**Comment by gcarbonin** [comment]
verifichiamo

**Comment by amollicone1982** [comment]
C'era un errore nella consultazione.
Può riprovare

**Comment by AMonopoliADS** [comment]
confermo che adesso il flag elettore è presente nella risposta del ws di consultazione.
grazie.
