### ISSUE TITLE
[C019] Errore richiamo massivo 

### ISSUE THREAD

**Issue by MatteoSoftlab** [italia/anpr#4461]
Dopo giorni di corretto utilizzo del servizio di test, oggi avviando la nostra applicazione che richiama in sequenza il C019 improvvisamente riceviamo un errore dopo un numero randomico di chiamate (a volte 2. a volte 4):

400 Bad Request: "{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"e273e3eb-e5d3-11ee-9021-005056ae1884"}"

Posso chiedere dettagli sull'errore?

Grazie

**Comment by signocob2** [comment]
Ciao @MatteoSoftlab , anche noi siamo fruitori del servizio e siamo nella stessa situazione.
Se può esserti d'aiuto, ci siamo accorti che rigenerando i JWT e il voucher per ogni chiamata (senza "riciclo"), sembra che il problema venga bypassato, ma stiamo ancora testando questa soluzione.

Siamo in difficoltà anche noi per lo stesso errore **non parlante**.

**Comment by MatteoSoftlab** [comment]
Dopo qualche ora dalla segnalazione il servizio ha ripreso a rispondere correttamente e in questi giorni di utilizzo non abbiamo più riscontrato la problematica.

> Buongiorno, siete riusciti a risolvere il problema? siamo al momento bloccati anche noi sulla questione. ringrazio e auguro buona giornata,
