### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Larimedi** [italia/anpr#4463]
Buonasera, sto tentando di accedere ai servizi ANPR, ma esce questo messaggio: 

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

Sapete per caso cosa dovrei fare? 

Mi chiamo Larissa Medici
Nata in Brasile 
MDCLSS

grazie in anticipo

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
