### ISSUE TITLE
WebApp non funzionante

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#4464]
Comune di Modena

Buongiorno,
da circa mezz' ora la webApp lascia autenticare gli utenti ma una volta connessi ottengono l' errore:

Il sistema è momentaneamente non disponibile. Si prega di riprovare più tardi

Per cortesia potete verificare? 

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
Il problema è stato risolto già da 40 minuti.
Grazie

**Comment by sfmodena** [comment]
Grazie
