### ISSUE TITLE
C020 servizioAccertamentoResidenza InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by MaxTheGlue** [italia/anpr#4466]
Buongiorno abbiamo fatto una richiesta a C020 ma ci ha restituito il seguente errore.

{
 type: 'https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html',
      title: 'InteroperabilityInvalidRequest',
      status: 400,
      detail: 'Received request is not conform to the required interoperability profile',
      govway_id: '9bf03bf7-ea80-11ee-a866-005056ae21f8'
}

**Comment by simonagami56** [comment]
Buongiorno,
siete riusciti a generare le stringhe JWT?
grazie in anticipo,

**Comment by MaxTheGlue** [comment]
Ciao si risolto tutto, grazie! Era il campo aud sbagliato.
