### ISSUE TITLE
[C001] -  Errore 400 in risposta a chiamate al servizio C001

### ISSUE THREAD

**Issue by giuseppecarollo** [italia/anpr#4468]
Comune di Palermo,
eseguendo una serie di chiamate concorrenti all'eService C001 incappiamo, in maniera apparentemente non deterministica, in errori del tipo seguente:

```json
{
"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
"title":"InteroperabilityInvalidRequest",
"status":400,
"detail":"Received request is not conform to the required interoperability profile",
"govway_id":"e838fe9b-eaba-11ee-99f9-005056ae6555"
}
```
Dopo un inizio nelle quali le chiamate alternativamente (ma non regolarmente) vanno a buon fine o in errore, da un certo momento in poi le successive vanno tutte in errore con lo stesso messaggio.

E' possibile capire quale sia la causa dell'errore legato al goway_id riportato nel frammento (**e838fe9b-eaba-11ee-99f9-005056ae6555**)?

Grazie, Giuseppe.

**Comment by afrontera85** [comment]
Salve, l'errore è il seguente:
Verifica ModI della richiesta fallita: [Header 'Authorization'] possiede un valore nel campo 'digest.value' non corrispondente al token di audit previsto dal pattern 'AUDIT_REST_02'
