### ISSUE TITLE
[3005] Risposta: xmlFile - Prospetti Statistici

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#447]
segnalo che il valore del campo xmlFile sembrerebbe avere passato due conversioni successive per ottenere il codice base64 contenuto nella risposta.
per ottenere l'xml con i dettagli del prospetto è necessario fare due giri di decodifica.

se potete verificare... grazie.

Alessandro Monopoli ADS
(rif. ambiente di TEST - comune di Faenza - 2017300067)

**Comment by gcarbonin** [comment]
Verifichiamo

**Comment by azabatta** [comment]
Abbiamo verificato: veniva effettuato un doppio encoding, l'anomalia è stata rimossa. La modifica sarà operativa negli ambienti di test dei comuni con il prossimo aggiornamento. 
Vi comunicheremo appena sarà possibile riprovare.
Grazie per la segnalazione

**Comment by azabatta** [comment]
La modifica è stata estesa in tutti gli ambienti. E' possibile riprovare
