### ISSUE TITLE
[C021] problema durata validità accesso API

### ISSUE THREAD

**Issue by DavideRoman** [italia/anpr#4473]
Buongiorno, sto sviluppando un'integrazione con l'e-service C021 integrato in PDND.
Sto notando una problematica nella durata di validità per l'accesso alle API. Non capisco se non sto considerando o se sto valorizzando in modo errato qualche parametro.
Per altre funzionalità ho già sviluppato l'integrazione di e-service con PDND, quindi la creazione del client-assertion e lo stacco del voucher PDND.
Ho integrato per questa funzionalità la gestione dei parametri "Digest", "Agid-JWT-TrackingEvidence" e "Agid-JWT-Signature".
Tutto funziona correttamente, ricevo correttamente i dati di risposta previsti dall'API.
Quello che non mi è chiaro è perchè dopo esattamente 5 minuti non mi funziona più la chiamata (errore 400 "InteroperabilityInvalidRequest") e mi trovo costretto a generare un nuovo client-assertion nonostante io abbia dato validità di 43200 minuti (quindi trenta giorni). Ho provato anche con validità più corte (10 minuti) ma il risultato non cambia. Se metto validità di 3 minuti allora giustamente la chiamata non funziona più dopo tre minuti.
Io al momento non avrei previsto di dover rigenerare anche il client-assertion (e quindi di conseguenza il valore che finirà nel parametro "Agid-JWT-TrackingEvidence") così spesso, lo troverei un po' inutile per chiamate puntuali come queste.
Ad ogni chiamata all'API genero un nuovo token PDND, il digest in base al body della chiamata e una nuova signature.
Mi confermate che c'è questo limite di 5 minuti nell'assertion? O sto sbagliando qualcosa io nella procedura?

Grazie per un riscontro

**Comment by afrontera85** [comment]
provi adesso a rifare altri test, rimanendo entro i 10 minuti
