### ISSUE TITLE
Interoperabilità InvalidRequest quando si controlla lo stato dell'API C019

### ISSUE THREAD

**Issue by belarbim** [italia/anpr#4474]
Ciao.

Ho un problema quando cerco di controllare lo stato dell'API utilizzando il seguente URL:
`https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/status`

`curl --location --request GET 'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/status' \
--header 'Content-Encoding: UTF-8' \
--header 'Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi9DMDE5LXNlcnZpemlvQWNjZXJ0YW1lbnRvRXNpc3RlbnphVml0YS92MSIsInN1YiI6IjhhNTJlODIxLTliNjktNDk4MS1hMTIxLTI5N2Q4YmYyZTJjNyIsIm5iZiI6MTcxMTQ1MDg2NSwicHVycG9zZUlkIjoiMTdhZDE2MTItZWNhNC00NjUwLWFjYmUtZjFmN2U3ZTVjMTc0IiwiaXNzIjoiaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MTE0NTE0NjUsImlhdCI6MTcxMTQ1MDg2NSwiY2xpZW50X2lkIjoiOGE1MmU4MjEtOWI2OS00OTgxLWExMjEtMjk3ZDhiZjJlMmM3IiwianRpIjoiNDgyNDhmYjMtNzY5Ni00YTgxLWE0NmItMjlkOWVlODJiNmU1In0.BtD_Ky9PDeb9ZbWijJ7_cXUWkXCmXDmd4cw94mwl9QwbHaXfAK7fw53-abNZjxFiPEj9WFPachwH5PU4HLnueU1UnpowzJXPzTMYjZVAptWxjZFMlZxz4mM029NrczRwj_I4nDxiwxAsx25is9NGSMBXdN_HcHfTao7roUjazIb7XJtHhXan921hoX0tI4yS4xMNykxPL_NWep_OJ3R23l9x6EDJzOVchgNVF5nnx3SJNPNVKPxavMIgXiT6wGpvGSzo-D5n4tRNHJpVWE8sI6-r9OktV9AujsvQzV82l-K9CB4fDfsKkTiHagCCIDl9moFRQgIwpD3OK4kAjcCP2g'`

Il problema ricevuto è questo:
`{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "bdf69bbd-eb5f-11ee-88e9-005056ae21f8"
}`

Il token utilizzato è questo:
`eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi9DMDE5LXNlcnZpemlvQWNjZXJ0YW1lbnRvRXNpc3RlbnphVml0YS92MSIsInN1YiI6IjhhNTJlODIxLTliNjktNDk4MS1hMTIxLTI5N2Q4YmYyZTJjNyIsIm5iZiI6MTcxMTQ1MDg2NSwicHVycG9zZUlkIjoiMTdhZDE2MTItZWNhNC00NjUwLWFjYmUtZjFmN2U3ZTVjMTc0IiwiaXNzIjoiaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MTE0NTE0NjUsImlhdCI6MTcxMTQ1MDg2NSwiY2xpZW50X2lkIjoiOGE1MmU4MjEtOWI2OS00OTgxLWExMjEtMjk3ZDhiZjJlMmM3IiwianRpIjoiNDgyNDhmYjMtNzY5Ni00YTgxLWE0NmItMjlkOWVlODJiNmU1In0.BtD_Ky9PDeb9ZbWijJ7_cXUWkXCmXDmd4cw94mwl9QwbHaXfAK7fw53-abNZjxFiPEj9WFPachwH5PU4HLnueU1UnpowzJXPzTMYjZVAptWxjZFMlZxz4mM029NrczRwj_I4nDxiwxAsx25is9NGSMBXdN_HcHfTao7roUjazIb7XJtHhXan921hoX0tI4yS4xMNykxPL_NWep_OJ3R23l9x6EDJzOVchgNVF5nnx3SJNPNVKPxavMIgXiT6wGpvGSzo-D5n4tRNHJpVWE8sI6-r9OktV9AujsvQzV82l-K9CB4fDfsKkTiHagCCIDl9moFRQgIwpD3OK4kAjcCP2g`

Può farmi sapere qual è il problema e anche se il token JWT fornito è corretto?

Per quanto riguarda,

**Comment by afrontera85** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita: Header HTTP 'Agid-JWT-TrackingEvidence' non presente.
Vi ricordo che le prove vanno fatte in ambiente di validazione

**Comment by belarbim** [comment]
Ciao.

Sai come posso ottenere il valore "Header HTTP 'Agid-JWT-TrackingEvidence' "?

Grazie.

**Comment by afrontera85** [comment]
Quì trova un esempio di client #3964
Potete usarlo modificando opportunamente il file pdnd.properties
