### ISSUE TITLE
[C019] Accesso non più autorizzato lato voucher

### ISSUE THREAD

**Issue by euberdeveloper** [italia/anpr#4475]
Il servizio C019 ha funzionato bene, abbiamo proceduto, come da documentazione, nell'ottenere prima un voucher PDND e poi nel fare le richieste aggiungendo i famigerati token di tracking-evidence e di signature (audit/integrity).

Senza cambiare nulla nel codice, da un giorno all'altro ha smesso di funzionare. L'errore è apparso nella parte in cui si ottiene il voucher PDND, abbiamo aperto un [issue](https://github.com/pagopa/pdnd-interop-frontend/issues/769) da loro ma ci hanno detto che il rifiuto dipende da voi e ci hanno detto di fare un issue anche qui (cliccare il link per vedere l'issue a cui faccio riferimento).

Ricopio qui il messaggio d'errore:
```json
{"correlationId":"db4c2610-9882-48e0-87e4-44e5228d97dc","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}
```

**Comment by euberdeveloper** [comment]
Fra quanto sarà possibile avere una risposta?

**Comment by afrontera85** [comment]
L'errore 400 è un errore generico relativo all'implementazione della cornice di sicurezza.
Se riuscite a fare la chiamata da Postman e ad ottenere un govway_id in risposta possiamo identificare la transazione in maniera puntuale e darvi un dettaglio dell'errore

**Comment by euberdeveloper** [comment]
Penso che ci sia un'incomprensione, la chiamata è quella relativa a pdnd, ma l'errore è vostro. Quindi non c'è il govway id. 

Loro ci hanno detto che comunque l'errore non dipende da pdnd ma da voi, la prego di vedere questo issue

https://github.com/pagopa/pdnd-interop-frontend/issues/769

**Comment by afrontera85** [comment]
E' lato pdnd che possono darvi maggiori delucidazioni sull'errore relativo al correlationId indicato...Comunque c'e' un client di esempio nel github #3964 che consiglio sempre di usare.

**Comment by euberdeveloper** [comment]
Grazie per la risposta, anche se sono un po' confuso perché entrambi mi rimandate dall'altra repo GitHub.

Avevo già usato quel client di esempio, ma il codice senza alcuna modifica ha smesso di funzionare da un giorno all'altro, quindi sembra più un problema lato permessi

**Comment by euberdeveloper** [comment]
Grazie per il supporto, pensavo che il mio issue ai pdnd fosse abbastanza chiaro ma invece c'era stato un malinteso. Chiudo questo issue
