### ISSUE TITLE
[P003] Cambio di stato richiesta cittadino UE: errore EN148

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#4476]
Buongiorno, 

Ambiente di TEST del comune 050026 

Stiamo testando l'invio del servizio P003 per il cambio di stato da IN LAVORAZIONE ad ACCOLTA CON RISERVA della richiesta 1710603. 
La risposta restituisce l'errore EN148 Non è stato possibile effettuare l'associazione dell'Identificativo Unico Nazionale e procedere al cambio di stato. ID operazione Comune 545192

Lo IUN che abbiamo indicato è corretto e coincide con quanto presente in WEBAPP a seguito dell'iscrizione.

Potete aiutarci a capire il problema?
Grazie

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by apaolacci** [comment]
Buongiorno,
state ancora svolgendo i test d'integrazione della pratica di tipo 4 - Iscrizione Online Cittadini UE ? 

Perché nel frattempo potrebbero essere cambiate le condizioni sull'utenza USR003 Mario Sedige da cui sono generate tutte le pratiche di tipo 4 messe a disposizioni delle diverse SH. Ciò non permette di superare i i controlli di coerenza tra richiedente eidas e cittadino iscritto ANPR.

Fateci sapere grazie.

Saluti,
Assistenza ANPR

**Comment by MoniaPedrazzoli** [comment]
Sì esatto stiamo testando i cambi di stato delle richieste che ci avete inserito.

**Comment by apaolacci** [comment]
Provate ad effettuare la request P003 passando in input l'identificativo unico nazionale **UE57650FL**

**Comment by MoniaPedrazzoli** [comment]
Ha funzionato, grazie.
