### ISSUE TITLE
Errore chiamata 

### ISSUE THREAD

**Issue by Gavriel17** [italia/anpr#4478]
{"type":https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html,"title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"f75afd28-f0bb-11ee-915f-005056ae6555"}

Perché prendo questo errore? Dovrei aver messo tutto

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Content-Type' possiede un valore differente rispetto a quello presente negli header firmati
