### ISSUE TITLE
Emissione Certificato [6001]

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#448]
In ambiente di Test abbiamo fatto l'iscrizione con servizio 1002 due soggetti (idOperazioneANPR 656603 e 656604) collegati con procedimento inserito con servizio 1014 (idOperazioneANPR 656602). Il procedimento verrà chiuso dopo le opportune verifiche fatte dal Comune (possono passare anche molti giorni). Uno dei due soggetti iscritti (idSchedaSoggettoANPR =10301742) ha necessità di certificato di residenza ma il servizio 6001 risponde "EN181  - Il certificato non puo' essere emesso perche' risulta un procedimento  aperto per il soggetto intestatario del certificato".
Come possiamo risolvere il problema, senza chiudere procedimento ANPR con il procedimento ancora aperto in Anagrafe.
Saluti
Inf.Or. S.r.l.
--

**Comment by gcarbonin** [comment]
Utilizzando il campo che consente di stampare comunque il certificato (forzaCertificazione = 1 )
