### ISSUE TITLE
Disservizi accesso riservato agli avvocati

### ISSUE THREAD

**Issue by ICT-OAM** [italia/anpr#4481]
Buongiorno,
l'[accesso riservato agli avvocati](https://www.anagrafenazionale.interno.it/area-tecnica/certificati-per-avvocati/) presenta **gravi disservizi**. 

Abbiamo centinaia di segnalazioni in merito: a seguito dell'accesso con SPID, l'avvocato riceve come messaggio d'errore "Non è possibile verificare l’iscrizione all’Albo". 
Tutti gli avvocati che hanno segnalato risultano correttamente censiti sull'albo del CNF.

La **situazione** sta diventando **insostenibile**, perché i nostri iscritti si rivolgono a noi per la soluzione di un problema del vostro portale. 
A seguito dell'apertura del vostro servizio di accesso per gli avvocati, ci è stata revocata la convenzione che avevamo col Comune di Milano, che ci permetteva di avere il servizio direttamente sul nostro sito web e **perfettamente funzionante**.
Ho già aperto un issue a riguardo, ma senza successo.

Ordine degli Avvocati di Milano

**Comment by ncapozzi** [comment]
Il problema di accesso è stato risolto nello stesso giorno della segnalazione 4/4/2024
