### ISSUE TITLE
info utilizzo - PDND Interoperabilità

### ISSUE THREAD

**Issue by mfelicicb** [italia/anpr#4487]
Salve
Mi trovo per la prima volta ad usufruire dei servizi di PDND Interoperabilità, motivo per cui ho seguito la [documentazione](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher) riportata sul portale nonchè i video caricati su youtube

Ho quindi inoltrato la richiesta di fruizione, creato la finalità e la chiave pubblica, seguito tutti i passi fino al punto 4 in cui mi si dice "Puoi accedere ai dati messi a disposizione dall’erogatore."
Ho effettuato il "debug della client assertion" e tutti gli esiti danno responso positivo indicando "Riuscita"

Però eseguendo la curl in ambiente reale (sul sito https://reqbin.com/curl) mi compare il messaggio "Invalid parameter found - A request body is required but none found."

Essendo novizio, forse non ho ben capito COME fare ad accedere ai dati messi a disposizione da PDND... cioè la curl dovrebbe restituirmi dei dati (quelli che sto cercando di ottenere in quanto fruitore) oppure serve solo per poter accedere ai servizi del fruitore? E in caso in che modo?

Grazie

**Comment by afrontera85** [comment]
Salve,
Quì trova un esempio di client che implementa i profili di sicurezza di cui Anpr necessita (INTEGRITY_REST_02 e AUDIT_REST_02):
#3964
Potete usarlo per la chiamata ai servizi modificandolo opportunamente (clientid, purposeid, etc... in pdnd.properties, la richiesta nel file test...)

**Comment by marpagno** [comment]
Salve, 
 ho provato a usare il client, ma salvo errori (*) ho la risposta

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"565c254d-f7fd-11ee-b672-005056ae5232"}

Stavo provando a fare una C020, con i parametri che mi ha rilasciato il Comune di Ravenna.

(*) così com'è il client non va perché cerca la classe javax.xml.databind... che non esiste più da un po', guardando su stackoverflow ho cambiato la dipendenza nel pom XML mettendo 
	<dependency>
	    <groupId>io.jsonwebtoken</groupId>
	    <artifactId>jjwt-api</artifactId>
	    <version>0.11.5</version>
	</dependency>
	<dependency>
	    <groupId>io.jsonwebtoken</groupId>
	    <artifactId>jjwt-impl</artifactId>
	    <version>0.11.5</version>
	</dependency>
	<dependency>
	    <groupId>io.jsonwebtoken</groupId>
	    <artifactId>jjwt-jackson</artifactId>
	    <version>0.11.5</version>
	</dependency>

e così funziona.. ma appunto ottengo il token da PDND ma ANPR mi risponde come sopra

**Comment by afrontera85** [comment]
L'errore relativo al govway_id fornito è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 4 eccezioni.
Token non utilizzabile prima della data '2024-04-11_14:54:16.000'
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2024-04-11_14:54:15.000'
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by marpagno** [comment]
Grazie del riscontro.
Come dicevo  sto usando il vostro (peraltro ottimo) client di test, per cui per le ore non sincronizzate ho provato ad aggiungere un secondo prima della chiamata effettiva ad ANPR.
Per L'audience non avevo notato la differenza con l'URL - mi confermate che l'audience giusta per la C020 è

`https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1` 
?

nonostante queste due piccole variazioni, ho ancora 

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"7a5e3f8f-f816-11ee-a571-005056ae1884"}`

grazie e buona serata

**Comment by afrontera85** [comment]
Ora l'errore è questo: Token non utilizzabile prima della data '2024-04-11_18:05:48.000'

**Comment by marpagno** [comment]
Decisamente un errore di sincronia orologi quindi - grazie, ho provato a mettere un ritardo di 6 secondi prima della chiamata e adesso ho un errore applicativo - probabilmente il mio messaggio di test era troppo di test (me lo riguarderò), ma la validazione ha funzionato.

grazie ancora


[giusto per reference, la tisposta alla chiamata funzionante è]
`GovWay-Transaction-ID: ffcdaf13-f817-11ee-b672-005056ae5232
{"listaErrori":[{"codiceErroreAnomalia":"999","testoErroreAnomalia":"Operazione non effettuabile","tipoErroreAnomalia":"E"}],"idOperazioneANPR":"63328412"}`
