### ISSUE TITLE
[C019] verifica esistenza in vita - parametri AUD per JwtSignature  e Tracking

### ISSUE THREAD

**Issue by JeyjooMilano** [italia/anpr#4489]
Buongiorno,

Stiamo cercando di collegarci all'API Esistenza Vita.

Ho due funzioni per generare il JwtSignature e il Tracking JwtSignature. Non trovo l'AUD per nessun dei due nella documentazione.

Grazie

**Comment by afrontera85** [comment]
L'aud è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

**Comment by Davi84** [comment]
io ho fatto così:

`
        String signature = Jwts.builder()
                .header()
                .add("alg", companySettings.getAlg())
                .add("typ", companySettings.getTyp())
                .add("kid", companySettings.getKid())
                .and()
                .setAudience(companySettings.getAudience())
                .claim("iat", creationTime.toString())
                .claim("nbf", creationTime.toString())
                .claim("exp", expirationTime.toString())
                .claim("signed_headers", new HashMap[]{m1, m2})
                .signWith(privateKey)
                .compact();

`
