### ISSUE TITLE
[5008] Annullamento Matrimonio di cittadino straniero [EN309]

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#449]
si vuole procedere con l'aggiornamento dello stato civile di un cittadino straniero da Celibe a Divorziato.

tale variazione è documentata unicamente dal nulla-osta al matrimonio (documentazione straniera), sul quale viene riportata solo la data del divorzio e nessun altra informazione riguardante sentenze e/o trascrizioni di atto.

con le informazioni in nostro possesso la comunicazione non viene accettata e viene restituito l'errore:
EN309 - E - Indicare la data della sentenza o dell'atto di cessazione matrimonio

per questo caso specifico il cliente sta tentando di aggiornare la posizione via web-app, ma come fare anche in futuro per risolvere casisitiche analoghe?

grazie
Alessandro Monopoli ADS
(rif. ambiente di PRODUZIONE - comune di Faenza - idOperazioneComune 2017001599)

**Comment by azabatta** [comment]
La data di fine unione consente al sistema di chiudere un matrimonio e consentire in tal modo la comunicazione di  ulteriori legami con i necessari controlli di congruenza. 
Pertanto si propone, come soluzione per questi casi,  la seguente impostazione della sezione cessazione  matrimonio:
1.	tipo cessazione: selezione della voce  “altro tipo di cessazione/scioglimento”
2.	data sentenza e data validità:  la data dichiarata dal cittadino
3.	tribunale: selezione della voce   “non conosciuto”
4.	autorità: campo a testo libero da utilizzare per una breve descrizione
