### ISSUE TITLE
test C020

### ISSUE THREAD

**Issue by marpagno** [italia/anpr#4490]
Buongiorno,
chiederei la cortesia del dettaglio dell'errore relativo alla invocazione seguente

{
  "type" : "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title" : "InteroperabilityInvalidRequest",
  "status" : 400,
  "detail" : "Received request is not conform to the required interoperability profile",
  "govway_id" : "9b49ea03-f8b7-11ee-b7ce-005056ae5232"
}

Mi pare che la mia invocazione sia identica a quella fatta col vostro client di esempio, ma mi sfugge evidentemente qualcosa.

Grazie e buona giornata

**Comment by marpagno** [comment]
...apache http client aggiunge automaticamente l'encoding all'header content-type - che così  non è più uguale a quello nella agid-jwt-signature....

**Comment by afrontera85** [comment]
L'errore infatti è:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati.
Consiglio sempre di usare il client di esempio da noi fornito https://github.com/italia/anpr/issues/4488
