### ISSUE TITLE
Esistenza Vita [C019] - Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by JeyjooMilano** [italia/anpr#4496]
Buongiorno,

Devo fare l'accertamento dell'esistenza vita [C019]. Abbiamo generato il voucher con successo. 
Faccendo una chiamata all'endpoint: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002 riceviamo la risposta seguente:

`{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "b8c535f2-fd7f-11ee-b214-005056ae5232"
}`

Ci potete indicare il problema?

Grazie

**Comment by afrontera85** [comment]
L'errore è questo: Validazione security token ModI 'INTEGRITY' della richiesta fallita: Signature verification failed
Ho visto che è sbagliato l'aud, deve essere questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

**Comment by afrontera85** [comment]
L'errore è ancora Validazione security token ModI 'INTEGRITY' della richiesta fallita: Signature verification failed.
L'errore 400 è relativo all'implementazione della cornice di sicurezza, dovete verificare di rispettare l'implementazione dell' INTEGRITY_REST_02.
Nell'header HTTP non passate il digest ad esempio...

**Comment by afrontera85** [comment]
Stesso errore...
Decodificando l'Authorization Bearer ho visto che non c'è il pezzo:

{
"digest": {
"alg": "SHA256",
"value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
}

Dove value è il valore ottenuto applicando l'algoritmo indicato nel claim digest.alg al JWT di audit.
AUDIT_REST_02 pretende che quando si richiede il token a pdnd venga inserita nella client assertion 
l'hash del token Agid-JWT-TrackingEvidence
Non avendo inserito nella client assertion pdnd quanto sopra, la pdnd non inserisce l'hash nel voucher generato

**Comment by gmiscia** [comment]
@ JeyjooMilano : buongiorno, sto anche io sviluppando un client (in php) per la società dove lavoro. Anche io sono fermo sullo stesso punto in cui è arrivato lei, forse potrebbe essere utile confrontarci su come abbiamo creato il digest e sugli headers da mettere nel curl. Leggendo altri thread ho appurato che PDND l'unica cosa che testa è la lunghezza del digest inserito (oltre ovviamente alla correttezza formale del claim in json). Se la lunghezza è rispettata (64 chars) tutto ok per PDND. Il digest sappiamo che si ottiene con una funzione di hash sha256 a partire da jwt "traking evidence": il primo dubbio è se debba essere passato come argomento della funzione di hash l'intero JWT tracking evidence ossia :
" base64(json_header).base64(json_payload).base64(json_signature) " o solo la terza parte base64(json_signature), il secondo è se l'hash debba uscire in formato binary e poi il risultato trasformato in base64. Per quanto riguarda gli headers della chiamata rest io passo i 3 JWT (tracking, signature e bearer ottenuto da PDND) più un  "Digest: SHA-256=" miodigest . Non passo come sembrerebbe dai suoi commenti sopra il kid , il clientid la purposeid etc, anche perchè già contenuti dei token che l'erogatore decodifica con la chiave pubblica richiamando api in PDND non appena riceve la nostra richiesta. Sono disponibile ad un confronto  comunque se le va.

**Comment by afrontera85** [comment]
> Ok, abbiamo risolto il digest e generato un voucher valido.
> 
> Faccendo una chiamata all'endpoint: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002 riceviamo la risposta seguente:
> 
> ```
> 
> {
>     "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
>     "title": "InteroperabilityInvalidRequest",
>     "status": 400,
>     "detail": "Received request is not conform to the required interoperability profile",
>     "govway_id": "6bb32e9b-093b-11ef-9f53-005056ae5232"
> }
> ```
> 
> Ci potete indicare il problema?
> 
> Grazie


L'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: 
Signature verification failed: [COMPACT] Signature verification failure: Process 'kid' error: 
Retrieve remote key 'TAw4jWvuG3iR37BQDe794qUBcv6Zykp6N2GeaWvujnw' failed: 
Retrieve external resource 'https://govway-anpr-val.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/api-pdnd/v1/keys/TAw4jWvuG3iR37BQDe794qUBcv6Zykp6N2GeaWvujnw' failed: (http code: 404): 
{"correlationId":"6f0309d9-ccfc-4dac-b86d-14a4d30d25eb","errors":[{"code":"013-0031","detail":"**Key with kId TAw4jWvuG3iR37BQDe794qUBcv6Zykp6N2GeaWvujnw not found**"}],"status":404,"title":"The requested resource could not be found but may be available again in the future.","type":"about:blank"}
