### ISSUE TITLE
Connessione sicura SAML/WSSE

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#45]
Sicurezza SAML/SSL --- 

[OutputServizio3002.txt](https://github.com/italia/anpr/files/862220/OutputServizio3002.txt)
[OutputServizioTestConn.txt](https://github.com/italia/anpr/files/862219/OutputServizioTestConn.txt)

[cxf_xml.txt](https://github.com/italia/anpr/files/862231/cxf_xml.txt)

#domanda #sicurezza #SAML #Header

Stiamo implementando un middleware per mettere in comunicazione il Sistema della Popolazione (SIPo) con ANPR. Siamo partiti dall'esempio fornito "ANPR_Client.rar" e ci siamo dotati dello stesso strumento (Apache CFX) usato in esso per la generazione dei clientri JAX-WS dei servizi applicativi.

Utilizzando la specifica contenuta nell'esempio (wsdl, xsd, x509) abbiamo generato (ex novo) le classi costituenti il client per il servizio TEstConn.

Inserite quelle classi classi nell'esempio, siamo riusciti a fare una chiamata con esito positivo.

Ora vorremmo fare la stessa cosa con il servizio 3002 (del Web Service 3000).

* Scaricata l'ultima specifica dal sito pubblico (WSDL, XSD).
* Generato il client con CXF 3.10.
* Modificata la URL nel keystore.properties
* Create le strutture analoghe a quelle di TestComm nel cfx.xml
* Creata una classe di lancio simile a TestConn.java
* Creata una classe Handler simile a TestConnHandler.java
* Modificato il metodo Servizio3000Handler.sendRequest() in modo che utilizzi
  gli oggetti del servizio 3000.
* Facendo girare il tutto in debug pare che vengano chiamate tutte
  le callback in modo corretto.
  
**Il problema** nella richiesta manca il seguente tag (il secondo della header):

``
<wsu:Timestamp wsu:Id="TS-1c7ca706-c37b-4613-9631-05a1d654b9f2">
  <wsu:Created>2017-03-20T16:58:55.534Z</wsu:Created>
  <wsu:Expires>2017-03-20T17:03:55.534Z</wsu:Expires>
</wsu:Timestamp>
``

**La domanda** Da quali elementi è governato quel tag?

Il server ci restituisce 500 Internal Error.

Grazie
Saluti
GiuCal

**Comment by gcarbonin** [comment]
I dettagli con cui viene composta la signature del messaggio, tra cui il Timestamp, sono indicati nel file policy-X509v3.xml che si trova nel pacchetto del sorgenti sotto il folder src/main/resources.
Il file di policy deve essere referenziato nel wsdl del servizio, come fatto per il TestConn, nella sezione <wsdl:binding>/<wsdl:operation>/<wsdl:input>. 
Vi riporto l’estratto del WSDL, in cui si evidenzia la policy:

      <wsdl:binding name="AnprBindingTestConn" type="tns:AnprPortTypeTestConn">    
             <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>    
             <wsdl:operation name="testConnessione">      
                    <wsdlsoap:operation soapAction=""/>      
                    <wsdl:input>        
                    <wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="policy-X509v3.xml"/> 
                           <wsdlsoap:body use="literal"/>      
                    </wsdl:input>      
                    <wsdl:output>        
                           <wsdlsoap:body use="literal"/>      
                    </wsdl:output>   
             </wsdl:operation>  
       </wsdl:binding>  

Probabilmente non avete aggiunto il riferimento alla policy nel WSDL che state utilizzando per richiamare il servizio 3000. Vi preciso che il riferimento va aggiunto per ogni wsdl:operation

Se il problema non si risolve, ci sentiamo telefonicamente

**Comment by ANPRCdMI** [comment]
Il problema si è risolto aggiungendo il riferimento per la operation invocata.
Come suggerito aggiungerò il riferimento a tutte le operation.
Adesso confrontando il messaggio del servizio TestConn con quella del servizio 3002 risultano strutturalmente identici. Per questo test ho spedito una parte applicativa vuota:

``
<ns2:Richiesta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione">
  <testataRichiesta>
    <idOperazioneComune>1</idOperazioneComune>
    <codMittente>001122</codMittente>
    <codDestinatario>001122</codDestinatario>
    <operazioneRichiesta>OP01</operazioneRichiesta>
    <dataOraRichiesta>2017-03-23T17:12:08.724+01:00</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <protocolloComune>111</protocolloComune>
    <dataProtocolloComune>2017-03-23+01:00</dataProtocolloComune>
    <tipoInvio>V</tipoInvio>
    <dataDecorrenza>2017-03-23+01:00</dataDecorrenza>
    <dataDefinizionePratica>2017-03-23+01:00</dataDefinizionePratica>
    <nomeApplicativo>ANPRAPP</nomeApplicativo>
    <versioneApplicativo>1</versioneApplicativo>
    <fornitoreApplicativo>Sogei</fornitoreApplicativo>
  </testataRichiesta>
  <criteriRicerca/>
</ns2:Richiesta3002>
``

Ottengo ancora l'errore 500, ma immagino che sia dovuto al fatto che l'area applicativa manca di parti obbligatorie da specifica. Mi confermate questo fatto?

[Allego risultato dell'invocazione dei due servizi]

Grazie mille!
Saluti
**GiuCal**
[message_out_TestConn_xml.txt](https://github.com/italia/anpr/files/865446/message_out_TestConn_xml.txt)
[message_out_servizio3002_xml.txt](https://github.com/italia/anpr/files/865448/message_out_servizio3002_xml.txt)

**Comment by rvinzani** [comment]
Il <codDestinatario>001122</codDestinatario> e <operazioneRichiesta>OP01</operazioneRichiesta>
Devono essere rispettivamente ANPR00 e 3002
Come supposto poi manca di parti obbligatorie da specifica
Saluti
Roberta Vinzani

**Comment by ANPRCdMI** [comment]
Ok funziona, mi dà un errore sull'utenza, ma adesso ci concentriamo sul sostituire il certificato fittizio con quello del Comune di Milano. Grazie Saluti GiuCal

`        <listaErrori>
          <errore>
            <codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Utente non abilitato : Il codice ISTAT della postazione 001122 non coincide al CF 040007 abilitato alle funzioni risultanti dal servizio cast</testoErroreAnomalia>
          </errore>
        </listaErrori>
`

**Comment by ANPRCdMI** [comment]
Ho sostituito il certificato "dummy" con quello fornito al Comune di Milano, adesso otteniamo una risposta KO il cui codice è "XXXX" e il tag "testoErroreAnomalia" stavolta è vuoto. Ecco la risposta:

`
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <a:Risposta3002 xmlns:a="http://sogei.it/ANPR/3000consultazione">
      <a:rispostaKO>
        <testataRisposta>
          <idOperazioneComune>1</idOperazioneComune>
          <codMittente>015146</codMittente>
          <codDestinatario>ANPR00</codDestinatario>
          <operazioneRichiesta>3002</operazioneRichiesta>
          <dataOraRichiesta>2017-03-24T16:20:27.151+01:00</dataOraRichiesta>
          <protocolloComune>111</protocolloComune>
          <dataProtocolloComune>2017-03-24+01:00</dataProtocolloComune>
          <dataDecorrenza>2017-03-24+01:00</dataDecorrenza>
          <idOperazioneANPR>0</idOperazioneANPR>
          <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
          <errore>
            <codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia/>
          </errore>
        </listaErrori>
      </a:rispostaKO>
    </a:Risposta3002>
  </soapenv:Body>
</soapenv:Envelope>
`

Di seguito le impostazioni utilizzate in **clientKeystore.properties** (password sostituita con stars):

[cancelletto] Properties WSS4J - Keystore del Comune
org.apache.ws.security.crypto.merlin.keystore.file=keystore/015146-CO-0000.p12
org.apache.ws.security.crypto.merlin.keystore.password=********
org.apache.ws.security.crypto.merlin.keystore.type=pkcs12
org.apache.ws.security.crypto.merlin.keystore.alias=015146-CO-0000

[cancelletto]  Properties internal
ID_OPERATORE=COMUNETEST015146
ID_SEDE=015146
ID_POSTAZIONE=015146-CO-0000
ID_APPLICAZIONE=SIPo
ID_TRANSAZIONE=99999
PATH_KEYSTORE_POSTAZIONE=keystore/015146-CO-0000.p12
PASS_KEYSTORE_POSTAZIONE=********
ALIAS_KEYSTORE_POSTAZIONE=015146-CO-0000
URL_WS=https://wstest.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000

Di seguito le impostazioni utilizzate in **messageTestConn.properties**:

[cancelletto] Message per WS TestConn
IdOperazioneComune=1
CodDestinatario=ANPR00
CodMittente=015146
OperazioneRichiesta=3002
TipoOperazione=C
ProtocolloComune=111
TipoInvio=V
NomeApplicativo=SIPo
VersioneApplicativo=1
FornitoreApplicativo=SistInf

---
Come idOperatore ho usato lo stesso che usiamo per la web app, forse è quello che non va bene?
Grazie 1000
**GiuCal**

**Comment by rvinzani** [comment]
Il file messageTestConn.properties è utilizzato solo per cambiare il contenuto di una richiesta del TestConnessione, 
Per invocare un altro servizio come il 3002 è necessario riempire il contenuto del messaggio.

**Comment by ANPRCdMI** [comment]
Si, Si, mi sono spiegato male. Ho utilizzato il fie di properties del TestConn anche per il 3002 solo per mia comodità e solo per comporre la testata. Nel frattempo ho risolto il problema era un problema di dati, ora ottengo un errore EN052 con tanto di descrizione. Quindi dal punto di vista applicativo il giro è stato completato in modo positivo
Possiamo considerare chiuso il thread.
Grazie mille.
Saluti
**GiuCal**
