### ISSUE TITLE
[C001] Smette di funzionare dopo un po' (ma prima dei dieci minuti di durata del voucher PDND)

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#4500]
Ho elaborato uno script Python per l'interrogazione di C001.
Stacco il voucher PDND con tanto di pattern INTEGRITY_REST_02.
Le interrogazioni funzionano per qualche minuto.
Poi dopo restituiscono un errore.
Dopo dieci minuti (scadenza del voucher PDND) l'errore restituito cambia.
Ne deduco che ci sia qualcos'altro che scade ma non riesco a capire cosa.

Test fatti il 22 aprile, ambiente di collaudo con dati dei cittadini fittizi presenti nella lista disponibile non ricordo dove.

Sono un dipendente del Comune di Rivoli (TO).

Di seguito le response ricevute nei vari casi (da cui si ricavano codici di transazioni eventualmente utili per verifiche).

**Richiesta immediatamente successiva a emissione voucher PDND (2024-05-22 09:47:34.420851+00:00)**:

```
{
    "listaSoggetti": {
        "datiSoggetto": [
            {
                "generalita": {
                    "codiceFiscale": {
                        "codFiscale": "DLGPPE90R10E329Q",
                        "dataAttribuzioneValidita": "2020-02-04",
                        "validitaCF": "1"
                    },
                    "cognome": "DELGADO",
                    "dataNascita": "1990-10-10",
                    "idSchedaSoggettoANPR": "93106837",
                    "luogoNascita": {
                        "comune": {
                            "codiceIstat": "063037",
                            "nomeComune": "ISCHIA",
                            "siglaProvinciaIstat": "NA"
                        }
                    },
                    "nome": "PEPE",
                    "sesso": "M"
                },
                "identificativi": {
                    "idANPR": "AX77007Z4"
                },
                "infoSoggettoEnte": [
                    {
                        "chiave": "Verifica esistenza in vita",
                        "id": "1003",
                        "valore": "S"
                    }
                ],
                "residenza": [
                    {
                        "indirizzo": {
                            "cap": "41026",
                            "comune": {
                                "codiceIstat": "036030",
                                "nomeComune": "PAVULLO NEL FRIGNANO",
                                "siglaProvinciaIstat": "MO"
                            },
                            "numeroCivico": {
                                "civicoInterno": {
                                    "interno1": "5"
                                },
                                "numero": "44"
                            },
                            "toponimo": {
                                "denominazioneToponimo": "DEI PLATANI",
                                "specie": "VIALE",
                                "specieFonte": "1"
                            }
                        },
                        "tipoIndirizzo": "1"
                    }
                ]
            }
        ]
    },
    "idOperazioneANPR": "64234515"
}
```
**Richiesta dopo 6 minuti da emissione del voucher (2024-05-22 09:54:25.252066+00:00)**
status code = 400
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "0b53300b-008b-11ef-b62d-005056ae5232"
}
```

**Dopo i 10 minuti di scadenza del voucher (2024-05-22 09:58:44.757204+00:00):**
status code = 404
```
{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "3f7e3e2d662635260d22d3ad"
}
```

PS: segnalo anche che le response restituite per gli status code 400 e 404 non sono conformi alla specifica yaml/swagger dell'e-service pubblicata su PDND

**Comment by afrontera85** [comment]
Può riprovare? rimanendo entro i 10 minuti

**Comment by franthemanIT** [comment]
Fatta ora una prova con interrogazioni ripetute. Mi pare vada meglio.
La prima in errore è questa:
"govway_id": "e5d36690-0b84-11ef-988d-005056ae1884"
Secondo i miei conteggi circa 8 minuti dopo la creazione di token, audit assertion ecc.
Mi sono accorto che la postazione da cui faccio i test non e' perfettamente sincronizzata come ora, ma immagino faccia fede il timestamp del token fornito da PDND, che in quel caso è:
'Mon, 06 May 2024 09:19:20 GMT' (recuperato dall'header della response del token: token_response.headers["date"])

Se invece si fa riferimento al valore "issued" (preso dalla mia postazione) i circa due minuti tornerebbero.

Curiosità, avete modificato qualcosa?
