### ISSUE TITLE
[C020] InteroperabilityInvalidRequest in collaudo

### ISSUE THREAD

**Issue by aisolani** [italia/anpr#4502]
Buongiorno,
 in data odierna (23/04/2024) abbiamo provato a eseguire la chiamata al servizio C020-servizioAccertamentoResidenza in ambiente di collaudo con il seguente body:

{"idOperazioneClient":"1",
"criteriRicerca":{"codiceFiscale":"QRTSGT90A01H501B"},"datiRichiesta":{"dataRiferimentoRichiesta":"2023-06-30","motivoRichiesta":"PROT.NUM.12345","casoUso":"C020"}}

e abbiamo ricevuto questa risposta:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "acf0c296-0147-11ef-826e-005056ae5232"
}

Probabilmente abbiamo sbagliato qualcosa, ma non capiamo cosa. Abbiamo trovato altre segnalazioni simili e abbiamo provato a fare quanto suggerito ma senza successo. Potete darci una mano?
Grazie in anticipo.

Alida Isolani 
Comune di Livorno

**Comment by afrontera85** [comment]
Salve,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: 
 Signature verification failed: [COMPACT] Signature verification failure: Process 'kid' error: Retrieve remote key '32d8a321-1568-44f5-9558-a9072f519d2d' failed: Retrieve external resource 'https://govway-anpr-val.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/api-pdnd/v1/keys/32d8a321-1568-44f5-9558-a9072f519d2d' failed: (http code: 404): {"correlationId":"43e463f4-6a68-480f-b141-6f6060b8005c","errors":[{"code":"013-0031","detail":"**Key with kId 32d8a321-1568-44f5-9558-a9072f519d2d not found**"}],"status":404,"title":"The requested resource could not be found but may be available again in the future.","type":"about:blank"}

**Comment by aisolani** [comment]
Salve.
Continuo a riceve l'errore InteroperabilityInvalidRequest.
Quello che fino ad ora ho fatto è questo:

- ho utilizzato l'applicativo clientApiAnprPdnd che avete reso scaricabile per generare Agid-Jwt-Signature, Agid-JWT-TrackingEvidence e Digest della chiamata. 
- Li ho copiati su PostMan insieme all'access token generato da https://auth.uat.interop.pagopa.it/token.oauth2.

Cosa c'è che sbaglio? "govway_id": "e57e478a-03a5-11ef-a8a1-005056ae1884"

Purtroppo mi rendo conto che ricevete molte di queste segnalazioni, ma evidentemente è una criticità condivisa.
Grazie in anticipo per qualsiasi supporto potete darmi.
Alida

**Comment by aisolani** [comment]
alla fine ce l'ho fatta! grazie lo stesso.
