### ISSUE TITLE
Servizi al citadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Klo7i** [italia/anpr#4506]
Purtroppo non è stato possibile accedere al servizio, le possibili cause sono:

Il tuo comune di residenza (o di iscrizione all’AIRE) non è ancora presente in ANPR (puoi verificarlo facilmente utilizzando la funzione “A che punto è il tuo Comune?” disponibile nella home page del Portale ANPR - è sufficiente digitare il nome del comune);
se il tuo comune è già in ANPR allora c’è una anomalia nei tuoi dati e non ci è stato possibile individuare in modo univoco la tua scheda anagrafica. Ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all’AIRE) per maggiori informazioni.
In contatto con il Comune di Milano (MI), non hanno riscontrato problemi con la scheda anagrafica. 

![Servizi al cittadino - ANPR](https://github.com/italia/anpr/assets/168076751/25ec36fc-99ca-49e4-8019-3932475cf1c6)

Potresti aiutarmi?

**Comment by Klo7i** [comment]
Confermo che il comune è Milano.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. Eventualmente il Comune può aprire una richiesta di assistenza sui canali loro riservati. Su Github suggeriamo di non indicare dati personali nel rispetto della norme sulla Privacy
