### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by Legomix1994** [italia/anpr#4509]
Buongiorno,
Non molto tempo fa ho fatto il cambio di residenza a Torino,io era in il Aire(comune Maierato),ma adesso non posso entrare a vedere mi scheda anagrafica su ANPR perche sono presente un problema.

![Screenshot_20240117-150859](https://github.com/italia/anpr/assets/68019779/c0bbf9c4-37e7-4765-a10d-3da622a8637f)

Ho parlato con il comune di Torino e me hanno detto che loro possono vedere i miei dati senza problema.

Mio Codice é: NNNNLS.

**Comment by Slumber86** [comment]
ma ti hanno risposto, o hanno risolto?

**Comment by Legomix1994** [comment]
> ma ti hanno risposto, o hanno risolto?

Niente adesso

**Comment by ncapozzi** [comment]
Buonasera,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di iscrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
