### ISSUE TITLE
Mail da ANPR - Verifica liste elettorali soggetti AIRE

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#451]
COMUNE DI VALLE MOSSO - PRODUZIONE

Poco fa ho ricevuto una pec da ANPR con l'oggetto sopra riportato.
Il testo dice:  Buongiorno. 
 Si trasmette in allegato l'elenco degli iscritti nell'AIRE del vostro comune per i quali non è stato indicato  se la persona non è iscritta nelle liste elettorali oppure è elettore oppure ha perduto il diritto al voto. Vi   preghiamo di procedere con i dovuti riscontri.
 Cordiali saluti.

Nel file allegato ho trovato un unico nominativo di un bimbo nato il 1/8/2017  (cod. 19184633) ed iscritto a fine novembre in AIRE su richiesta consolare e dopo la trascrizione dell'atto di nascita.
Ovviamente il neonato non puo' essere iscritto nelle liste elettorali quindi non capisco il significato della pec.
Sull'ambiente web ho effettuato la variazione liste inserendo NO- non iscritto  ma si sembra un'operazione superflua.
Devo dire alla software house di modificare l'xml dell'operazione di iscrizione?
Buon week-end lungo

**Comment by AnnaUrban** [comment]
COMUNE DI SERRAVALLE SESIA - PRODUZIONE
La stessa mail che è arrivata al collega di Valle Mosso e arrivata anche a me. Nell'elenco allegato, oltre ad avere il nominativo di un bimbo nato nel 2017, ho anche il nominativo di una cittadina maggiorenne che ho iscritto in AIRE, in una fase successiva al popolamento iniziale, per acquisto della cittadinanza italiana. Attualmente l'interessata è nella posizione di 'iscrivendo' e verrà iscritta con le prossima revisione di gennaio: è corretto, quindi, prevedere per lei il flag di 'non iscritto' ?

**Comment by gcarbonin** [comment]
Purtroppo  a causa delle elezioni politiche che si svolgeranno a marzo, i tempi di formazione dell'elenco unico degli elettori sono stati anticipati di circa due mesi. Abbiamo inviato la mail in quanto queste persone non hanno il campo liste elettorali impostato; deve avere un valore anche per i neonati. Vi chiederà di correggere direttamente il sistema informativo elettorale del Viminale.
