### ISSUE TITLE
C019: EN122 per CF valido

### ISSUE THREAD

**Issue by Morenus77** [italia/anpr#4512]
"idOperazioneANPR": "1761851301"

Il CF è valido e riconosciuto da AdE ma otteniamo comunque l'errore:

"codiceErroreAnomalia": "EN122",
"testoErroreAnomalia": "La richiesta effettuata non produce alcun risultato",
"tipoErroreAnomalia": "E"

Grazie.

**Comment by afrontera85** [comment]
La spiegazione di eventuali incongruenze tra la posizione fiscale (Agenzia Entrate) e quella anagrafica (ANPR) andrebbe chiesta al cittadino stesso.
Per questo tipo di assistenza è stata attivata la seguente casella di posta elettronica: assistenza.anpr.enti@sogei.it
Saluti
