### ISSUE TITLE
C020-servizioAccertamentoResidenza - Internal error

### ISSUE THREAD

**Issue by fabercrino** [italia/anpr#4513]
Buongiorno 

abbiamo provato a richiamare il servizio in oggetto in ambiente di produzione dal comune di Savona con la seguente richiesta:

{
	"idOperazioneClient": "1",
	"datiRichiesta": {
		"casoUso": "C020",
		"dataRiferimentoRichiesta": "2024-05-03",
		"motivoRichiesta": "1"
	},
	"criteriRicerca": {
		"codiceFiscale": "CLPNLN64D55I480P"
	}
}

la risposta è questa:

{
	"listaErrori": [
		{
			"codiceErroreAnomalia": "500",
			"testoErroreAnomalia": "Internal Error",
			"tipoErroreAnomalia": "E"
		}
	]
}

Potete darci qualche dettaglio in più sull'errore?

Grazie

**Comment by afrontera85** [comment]
Potrebbe essere qualche campo nel token tracking troppo lungo, che supera i 50 caratteri (user,location,loa...). 
Provi a ricontrollare

**Comment by fabercrino** [comment]
si trattava della userLocation, inserendo un ip address ha funzionato

grazie
