### ISSUE TITLE
[C001] - Errore interoperabilità

### ISSUE THREAD

**Issue by franthemanIT** [italia/anpr#4514]
Buongiorno,

sarebbe possibile avere un debug per la richiesta con questo govway id?

3b67f647-092a-11ef-9f53-005056ae5232

Grazie

**Comment by afrontera85** [comment]
L'errore è il seguente:
Verifica ModI della richiesta fallita: [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-05-03_11:28:33.000')

**Comment by franthemanIT** [comment]
Grazie, quale è la durata massima consentita?

**Comment by afrontera85** [comment]
Deve stare entro i 10 min

**Comment by franthemanIT** [comment]
Grazie. In realtà nei dieci minuti ci dovrei rientrare. Vedi issue #4500. Disponibile per altre prove.

**Comment by afrontera85** [comment]
Può riprovare e ci fa sapere?

**Comment by franthemanIT** [comment]
Vedi #4500. Grazie.
