### ISSUE TITLE
[C001] nell'uso della risorsa si ottiene "InteroperabilityInvalidRequest"

### ISSUE THREAD

**Issue by marcob71** [italia/anpr#4517]
Buongiorno,
in ambiente di produzione invocando il servizio di produzione https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C001-servizioNotifica/v1 in data: 2024-05-06T16:45:21,346

interrogando la risorsa anpr-service-e002 con body  (***=omissis):
{
  "idOperazioneClient": "3",
  "criteriRicerca": {
    "codiceFiscale": "BBB***71S25****J" 
       },
  "datiRichiesta": {
    "dataRiferimentoRichiesta": "2024-04-26",
    "motivoRichiesta": "1",
    "casoUso": "C001"
  }
}

si ottiene in risposta un errore 400:
{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "f8e2a1a5-0bb6-11ef-bbe7-005056ae6555"
}

mentre se si interroga la risorsa /status
si ottiene un codice 200 con un risposta accettabile:
{
  "listaErrori": [
    {
      "codiceErroreAnomalia": "200",
      "testoErroreAnomalia": "OK"
    }
  ]
}

Potete darci indicazioni a riguardo?

Marco Babbei
Comune di Genova

**Comment by afrontera85** [comment]
L'errore relativo al govway_id fornito è il seguente: 
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by marcob71** [comment]
predisposto azione correttiva che ha portato alla risoluzione.
