### ISSUE TITLE
[C015] - Errore InteroperabilityInvalidRequest in chiamata servizio Accertamento generalità

### ISSUE THREAD

**Issue by fzucaro** [italia/anpr#4526]
Invocando il servizio C015 - Accertamento generalità con cf di test, ottengo errore 400 InteroperabilityInvalidRequest.
Segnalo il **govway_id:** =  **"b282b206-0e10-11ef-9d28-005056ae5232"**
Chiedo se possibile ulteriori dettagli per individuare la problematica
Grazie

**Comment by afrontera85** [comment]
L'errore è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
Token contenente un claim 'aud' non valido

**Comment by afrontera85** [comment]
le possibili cause sono:
•	Non vi state presentando con il voucher pdnd nella richiesta (nell’ attributo authorization)
•	Il voucher che state presentando nella richiesta non è valido
•	Non state chiamando la url giusta (o metodo http sbagliato)
