### ISSUE TITLE
 WS estrazione dati tracciato LAC

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#4527]
Buonasera, vorrei sapere se esiste un webservice per scaricare i dati secondo il tracciato LAC (o simile) che veniva utilizzato per l'integrazione con ISTAT
Grazie

**Comment by azabatta** [comment]
Buonasera, 
ci scusiamo per il ritardo della risposta.
No, non esiste una versione delle LAC per i comuni.
Saluti
