### ISSUE TITLE
C019 - Nuova richiesta di indagine tramiti ID ANPR

### ISSUE THREAD

**Issue by FedericaMaz** [italia/anpr#4529]
Data test 7 maggio 2024 - Reale Mutua Assicurazioni
Per recuperare l’informazione relativa all’esistenza in vita di un soggetto, abbiamo finora chiamato il servizio C019 passando in input il campo codiceFiscale all’interno dell’oggetto criteri Ricerca. Da qualche settimana il servizio restituisce l’errore sotto riportato. Sembra quindi che non sia più possibile eseguire una ricerca per codice fiscale, ma che sia necessario utilizzare l’ID ANPR, informazione che non abbiamo nei nostri sistemi. Come possiamo risalire all’ID ANPR partendo dal codice fiscale? 
 
**{
   "idOperazioneANPR":"1766578458",
   "listaErrori":[
      {
         "tipoErroreAnomalia":"E",
         "codiceErroreAnomalia":"EN122",
         "testoErroreAnomalia":"La richiesta effettuata non produce alcun risultato"
      },
      {
         "tipoErroreAnomalia":"W",
         "codiceErroreAnomalia":"EN148",
         **"testoErroreAnomalia":"Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi."
      }
   ]
}****

Ringrazio e e saluto
Federica Mazzocchi

**Comment by rglauco** [comment]
Buongiorno @FedericaMaz 
a riguardo ho risposto ad una issue precedente analoga: https://github.com/italia/anpr/issues/4501#issuecomment-2117320713
