### ISSUE TITLE
C020-servizioAccertamentoResidenza - Province

### ISSUE THREAD

**Issue by fabercrino** [italia/anpr#4530]
Buongiorno

abbiamo provato a far eseguire la richiesta di fruizione del servizio in oggetto ad un nostro cliente che è una Provincia. Tale richiesta è ormai in sospeso da diversi giorni.  Voi sapete se le Province hanno la possibilità di accedere a questo servizio?

Grazie e saluti

Fabrizio

**Comment by amollicone1982** [comment]
Questo è un canale di supporto tecnico. Per le approvazioni rivolgersi al Ministero dell'Interno
