### ISSUE TITLE
Approvazione richiesta attivazione e-service “C019-servizioAccertamentoEsistenzaVita-approvazione_automati” sulla piattaforma PDND

### ISSUE THREAD

**Issue by AlineSorel** [italia/anpr#4531]
Buongiorno 

Per rispettare il nostro obbligo di dichiarazione relativa alle polizze dormienti (cosi detto POLDO) all'Istituto di Vigilanza delle Assicurazione (IVASS), dobbiamo attivare l'e-service “C019-servizioAccertamentoEsistenzaVita-approvazione_automati” sulla piattaforma PDND.

La richiesta risulta "in attesa di approvazione" da oltre 3 settimane, senza quest'approvazione non possiamo provvedere ad adempire il nostro obbligo.

**Comment by robertog79** [comment]
Buongiorno,
noi abbiamo risolto facendo la richiesta con il limite di 3000 in modo che venga approvata automaticamente...

**Comment by amollicone1982** [comment]
Questo è un canale di supporto tecnico. Per le approvazioni rivolgersi al Ministero dell'Interno
