### ISSUE TITLE
C020-servizioAccertamentoResidenza-approvazione_automatica - InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by salvatoresl** [italia/anpr#4532]
Buon pomeriggio,
avremmo bisogno di supporto per il seguente errore.

REQUEST CONTENT:
`{"idOperazioneClient": "1","criteriRicerca": { "codiceFiscale": "TTVSGT90A01H501H"}, "datiRichiesta": { "dataRiferimentoRichiesta": "2024-05-05", "motivoRichiesta": "1", "casoUso": "C020" }}`
RESPONSE CONTENT:
`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"ff322556-12bd-11ef-a976-005056ae1884"}`

**Comment by afrontera85** [comment]
L'errore è il seguente: 
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 3 eccezioni.
Token senza claim 'aud'
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

Nella issue https://github.com/italia/anpr/issues/4488 trovate comunque un client di esempio

**Comment by salvatoresl** [comment]
Grazie. Dopo essere intervenuti, otteniamo ancora questa risposta:
`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0a7640f2-16ad-11ef-aba3-005056ae1884"}`

**Comment by afrontera85** [comment]
L'errore è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido
L'aud è questo :
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1

**Comment by salvatoresl** [comment]
Grazie mille, ora funziona
