### ISSUE TITLE
Stiamo usando correttamente gli e-service ANPR su PDND?

### ISSUE THREAD

**Issue by MBossiniB** [italia/anpr#4533]
Buongiorno, vorrei fare una domanda relativa all'utilizzo dei servizi ANPR proposti su PDND.

Siamo un'azienda che opera nel settore dei sistemi informativi socio-sanitari, educativi ed abitativi per la Pubblica Amministrazione. Abbiamo avuto accesso alla PDND di collaudo tramite un comune nostro cliente e stiamo procedendo all'integrazione con alcuni dei servizi ANPR proposti su PDND.

Ci è sorto, però, un dubbio sull'utilizzo che possa esserne fatto.
Sui nostri software, abbiamo necessità di migrare i comuni nostri clienti dall'anagrafe locale ad ANPR interrogando massivamente con decine di migliaia di interrogazioni i servizi ANPR e mettere in piedi procedure di aggiornamento dati, che periodicamente farebbero queste chiamate ad ANPR, su richiesta del comune, per aggiornare i dati.

Vorremmo, quindi, chiedere se sia fattibile utilizzare gli e-service ANPR per questo scopo o se sia necessario seguire altre vie. Vi ringrazio anticipatamente.

**Comment by MBossiniB** [comment]
Provo a presentare un caso d'uso per capire meglio. Prima dell'emissione di posizioni debitorie (ad esempio rette scolastiche), si potrebbe immaginare di chiedere per 5000 anagrafiche paganti quale sia l'indirizzo di residenza aggiornato a cui inviare l'avviso di pagamento facendo però 5000 chiamate singole?
Grazie

**Comment by afrontera85** [comment]
In fase di richiesta il fruitore oltre a specificare le finalità per le quali utilizzerà l’e-service, deve inserire una stima di carico (media di chiamate API giornaliere). Se la stima supera la soglia impostata, sarà poi l’erogatore, il Ministero, a verificare ed approvare.
In collaudo la soglia è 2000
