### ISSUE TITLE
C019 esistenza in vita

### ISSUE THREAD

**Issue by saldeangelis** [italia/anpr#4534]
Buongiorno,

ho effettuato la chiamata per ricevere il voucher ma ho ricevuto questo errore:
{"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank","errors":[{"code":"015-9000","detail":"Invalid parameter found - Object instance has properties which are not allowed by the schema: [\"{ \\n\\\"client_id\\\":\\\"0b74fd28-cd36-42bb-8b9df7156795\\\", \\n\\\"client_assertion\\\":\\\"eyJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMDVhYzZiYzktOWU5Yy00NWY3LWExM2YtZDM0YzNmYjQ3Nzg5IiwiaWF0IjoxNzE1OTU1NzYyLCJleHAiOjE3MTU5NTYwNjIsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.hNijN5eeI9PMGuLEoqLW-M2aO1fLhgDJgLQV59pZDWxGNloXwYzlhd7t5KSsv7jqR6oenfJgnoJujnFsyS61i9TeQPVLIMRP4sYMHEi0pzPCM5WKw_7tIi0xxneVK_CEJdr0BpMd54goMDxJklKDvVkBBiNJZBcSltfKa4LorF6cjtziY__QCmABokfLPShstgjl4J3NFKpAkNqldkxgfL9m7eeqnFHrK4geIn6mR3PY_WR3oKdj4Drc_YIRWd9p3G5C7AyHN195tt3zrhhk1coOj9padofaJ9Y_zWSY4yfSkdnfZNskzaaJwhJOtbbgxY_aIxWDxD98ip17iOqCzQ\\\", \\n\\\"client_assertion_type\\\":\\\"urn:ietf:params:oauth:client-assertion-type:jwt-bearer\\\", \\n\\\"grant_type\\\":\\\"client_credentials\\\" \\n}\"]"},{"code":"015-9000","detail":"Invalid parameter found - Object has missing required properties ([\"client_assertion\",\"client_assertion_type\",\"grant_type\"])"}],"status":400}

Questo è il body:

{ "client_id":"0b74fd28-cd36-42bb-8b91-1c6df7156795", "client_assertion":"eyJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMDVhYzZiYzktOWU5Yy00NWY3LWExM2YtZDM0YzNmYjQ3Nzg5IiwiaWF0IjoxNzE1OTU1NzYyLCJleHAiOjE3MTU5NTYwNjIsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.hNijN5eeI9PMGuLEoqLW-M2aO1fLhgDJgLQV59pZDWxGNloXwYzlhd7t5KSsv7jqR6oenfJgnoJujnFsyS61i9TeQPVLIMRP4sYMHEi0pzPCM5WKw_7tIi0xxneVK_CEJdr0BpMd54goMDxJklKDvVkBBiNJZBcSltfKa4LorF6cjtziY__QCmABokfLPShstgjl4J3NFKpAkNqldkxgfL9m7eeqnFHrK4geIn6mR3PY_WR3oKdj4Drc_YIRWd9p3G5C7AyHN195tt3zrhhk1coOj9padofaJ9Y_zWSY4yfSkdnfZNskzaaJwhJOtbbgxY_aIxWDxD98ip17iOqCzQ", "client_assertion_type":"urn:ietf:params:oauth:client-assertion-type:jwt-bearer", "grant_type":"client_credentials" }

di seguito la codifica del jwt

![image](https://github.com/italia/anpr/assets/28670106/89ca9e0a-444b-4161-afcd-8fc88e91de37)

Manca qualcosa?

**Comment by saldeangelis** [comment]
Buongiorno,
ho ripetuto ora il token scade tra un paio di ore

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/2c04786d-035c-4cfb-9932-d63b3904ded3)

Risposta:

{"errors":[{"code":"015-9000","detail":"Invalid parameter found - Request Content-Type header '[none/none, none/none]' does not match any allowed types. Must be one of: [application/x-www-form-urlencoded]."},{"code":"015-9000","detail":"Invalid parameter found - A request body is required but none found."}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

**Comment by afrontera85** [comment]
consigliamo di guardare il client di esempio nella issue https://github.com/italia/anpr/issues/4488
