### ISSUE TITLE
WS - 5008 - Aggiornamento/Rettifica dati coniuge

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#454]
Avrei la necessità di aggiornare gli ID identificativi di un coniuge (moglie) nel gruppo dati matrimonio del marito, rispetto ai dati caricati in ANPR al momento del subentro.
Questo perché, al momento del subentro, nella anagrafe locale, nei dati del matrimonio del marito, c’erano i riferimenti della moglie tramite un'anagrafica “duplicata” e non completa (solo generalità). 
Preciso che anche la moglie, con la sola anagrafica giusta e completa, è presente in ANPR dal subentro.
Il comune, nella anagrafe locale, si è accorto dell'errore e ha collegato nel matrimonio del marito i giusti riferimenti alla scheda anagrafica della moglie, ma inviando una mutazione di matrimonio 5008 sia ha l’errore seguente…
Come si può fare?
Grazie.

Alessio
Datagraph s.r.l.

```
<?xml version="1.0" encoding="utf-16"?>
<Risposta5008 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <rispostaKO xmlns="http://sogei.it/ANPR/5000mutazione">
    <testataRisposta xmlns="">
      <idOperazioneComune>9738</idOperazioneComune>
      <codMittente>037001</codMittente>
      <codDestinatario>ANPR00</codDestinatario>
      <operazioneRichiesta>5008</operazioneRichiesta>
      <dataOraRichiesta>2017-10-27T12:41:32.4665701+02:00</dataOraRichiesta>
      <protocolloComune>0</protocolloComune>
      <dataDecorrenza>2017-05-27</dataDecorrenza>
      <idOperazioneANPR>1266437</idOperazioneANPR>
      <esitoOperazione>XXXX</esitoOperazione>
    </testataRisposta>
    <listaErrori xmlns="">
      <errore>
        <codiceErroreAnomalia>EN272</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Alla data 12-07-2009 il soggetto .... risulta gia' coniugato o unito civilmente con un altro soggetto</testoErroreAnomalia>
      </errore>
      <errore>
```

**Comment by gcarbonin** [comment]
Stiamo verificando quale possa essere la strada migliore

**Comment by frmariani** [comment]
L’errata indicazione dell’idapr della moglie (idanpr 18673470) ha impedito la riconciliazione automatica dei dati del matrimonio che effettuiamo in fase di subentro; in data 9/10/2017  è stata effettuata una modifica dell’atto del matrimonio, ma per poter effettuare delle modifiche sui coniugi, devono essere completate le operazioni fallite in fase di subentro, eliminando l’errore che ha bloccato le operazioni:  attraverso il servizio 5008 tipo mutazione 1 sul soggetto idanpr 18673470 , dovete effettuare la modifica  dell’idapr  da  30963 a idapr 30962;
successivamente noi effettueremo le operazioni  del caso e vi avviseremo quando sarà possibile effettuare la mutazione del matrimonio richiesta.

**Comment by frmariani** [comment]
issue risolta via mail in data 14/12/2017
