### ISSUE TITLE
Mancata ricezione notifiche tramite ws

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#4540]
Buongiorno, il comune 086008, in ambiente di produzione, non riceve le notifiche attraverso ws esposto per la ricezione, dal alcune verifiche effettuati l'endpoint sembra essere corretto e raggiungibile.
Dal web app di ANPR la funzione di test del servizio di notifica non è attiva, quindi non abbiamo modo di capire la causa della mancata ricezione, potreste darci delle indicazioni in merito.

Grazie mille.
GolemNet.

**Comment by azabatta** [comment]
Buongiorno, 
non risulta più presente l'endpoint, è necessario comunicarlo nuovamente (da Amministrazione - Gestione dati del comune).
Il flusso di invio delle notifiche si è fermato a partire dal 1° marzo u.s.
Segnalate attraverso questo thread l'avvenuto ripristino.
Saluti

**Comment by Antonino09** [comment]
Buongiorno,
abbiamo effettuata una verifica e l'endpoint è presente tuttavia non è presente il certificato di decodifica delle notifiche  come si evince dall'immagine
![Immagine1](https://github.com/italia/anpr/assets/44637836/be8b3cc4-6142-4ce5-ad65-5ca68c7f79ca)

Adesso abbiamo provveduto ad impostare il certificato di decodifica .
![Immagine2](https://github.com/italia/anpr/assets/44637836/8c8e5837-2b6a-42bb-a49b-a091708b0710)

Grazie.
GolemNet.

**Comment by azabatta** [comment]
Buongiorno, 
abbiamo verificato che adesso l'endpoint risulta attivo. 
Procediamo con il recupero delle notifiche non inviate.
Saluti

**Comment by Antonino09** [comment]
Grazie e buon lavoro.

Saluti
GolemNet
