### ISSUE TITLE
[C019] Errore 404 - Unknown API Request  

### ISSUE THREAD

**Issue by danielecibin** [italia/anpr#4541]
Buongiorno,
 stiamo provando a consumare il servizio di accertamento esistenza in vita in ambiente di Produzione, ma purtroppo riceviamo un errore di Unknown API Request:
`{
  "TYPE": "HTTPS://GOVWAY.ORG/HANDLING-ERRORS/404/NOTFOUND.HTML",
  "TITLE": "NOTFOUND",
  "STATUS": 404,
  "DETAIL": "UNKNOWN API REQUEST",
  "X-GLOBAL-TRANSACTION-ID": "DB4AA801664DC17A05F49FCD"
} `
La stessa procedura funziona correttamente in ambiente di Collaudo, quindi non sembrerebbe un problema legato alla procedura, ma alla configurazione.
Potete aiutarci a capire il reale motivo dell'errore?
Grazie,
Daniele

**Comment by afrontera85** [comment]
L'errore 404 - Unknown API Request è un errore che si può prendere per i seguenti motivi:
-	url errata
-	url esatta ma assenza del voucher pdnd nella richiesta
-	url esatta ma voucher pdnd errato nella richiesta

**Comment by afrontera85** [comment]
Il dettaglio dell'errore riusciamo a darlo quando viene restituito il govway_id...
L'url è questo per produzione:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

**Comment by danielecibin** [comment]
Buongiorno, 
Effettivamente c'è un errore nel URL presente sul portale:
![image001](https://github.com/italia/anpr/assets/170529280/5b4b2d9c-f1e7-4a6f-8c12-13f6c213a158)

Sostituendo audience ed endpoint sembra funzionare correttamente, riceviamo un'errore applicativo dal servizio:
`{

  "LISTAERRORI": [

    {

      "CODICEERROREANOMALIA": "EN122",

      "TESTOERROREANOMALIA": "LA RICHIESTA EFFETTUATA NON PRODUCE ALCUN RISULTATO",

      "TIPOERROREANOMALIA": "E"

    },

    {

      "CODICEERROREANOMALIA": "EN148",

      "TESTOERROREANOMALIA": "IL D.M. MINISTERO DELL'INTERNO 3 MARZO 2023 (ART.3 COMMA 3) PREVEDE L'ACCESSO AD ANPR ESCLUSIVAMENTE CON IDENTIFICATIVO UNICO NAZIONALE (ID ANPR), SI  RAPPRESENTA PERTANTO L'URGENZA DI PROVVEDERE ALL'INTEGRAZIONE DEI PROPRI SISTEMI.",

      "TIPOERROREANOMALIA": "W"

    }

  ],

  "IDOPERAZIONEANPR": "65256904"`

**Comment by afrontera85** [comment]
Bene!!!
Non c'è errore comunque.
L'url è questo:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
L'aud è questo:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
Saluti

**Comment by danielecibin** [comment]
Come non detto, l'errore è in realtà il medesimo.
Anche cambiando endpoint e audience come indicato nell'ultimo commento. Ho riverificato kid, client e purposeid e sono corretti. Verificando la client assertion sembrerebbe essere valida.

**Comment by danielecibin** [comment]
Come non detto. Anche con i parametri corretti il servizio fallisce.

**Comment by danielecibin** [comment]
Come non detto, purtroppo modificando i parametri come indicato il servizio risponde con il medesimo messaggio di errore:

{ "TYPE": HTTPS://GOVWAY.ORG/HANDLING-ERRORS/404/NOTFOUND.HTML, "TITLE": "NOTFOUND", "STATUS": 404, "DETAIL": "UNKNOWN API REQUEST", "X-GLOBAL-TRANSACTION-ID": "DB4AA801664DC17A05F49FCD" }

La configurazione sembra essere corretta:

baseurlapi=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalità es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

audPdnd=auth.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.interop.pagopa.it

#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

Tuttavia, verificando il voucher generato viene restituito un errore al quarto step “La client assertion è valida ma la finalità per la quale stai richiedendo il voucher non è attiva”.

Il messaggio di errore del debugger è coerente con il 404?

Grazie,
Daniele
