### ISSUE TITLE
Anomalia richiesta di fruizione service C029 di ANPR

### ISSUE THREAD

**Issue by fabriziomef** [italia/anpr#4542]
Come MEF, abbiamo la necessità di variare la richiesta di fruizione del Servizio in oggetto in ambiente di collaudo.
Il sistema non consente ne l'innalzamento della versione ne l'annullamento della richiesta.
E' possibile effettuare una verifica?

**Comment by azabatta** [comment]
Buongiorno,
abbiamo letto la risposta alla stessa issue che ha inviato sul canale GH di PDND. Prendiamo atto del fatto che non esiste una funzione di annullamento di una richiesta non ancora approvata e ci facciamo carico del problema.
Saluti
