### ISSUE TITLE
C019] Errore 404 - Unknown API Request  

### ISSUE THREAD

**Issue by danielecibin** [italia/anpr#4543]
Come non detto, purtroppo modificando i parametri come indicato il servizio risponde con il medesimo messaggio di errore:

{ "TYPE": HTTPS://GOVWAY.ORG/HANDLING-ERRORS/404/NOTFOUND.HTML, "TITLE": "NOTFOUND", "STATUS": 404, "DETAIL": "UNKNOWN API REQUEST", "X-GLOBAL-TRANSACTION-ID": "DB4AA801664DC17A05F49FCD" }

La configurazione sembra essere corretta:

baseurlapi=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalità es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd= XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

audPdnd=auth.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.interop.pagopa.it

#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

Tuttavia, verificando il voucher generato viene restituito un errore al quarto step “La client assertion è valida ma la finalità per la quale stai richiedendo il voucher non è attiva”.

Il messaggio di errore del debugger è coerente con il 404?

Grazie,
Daniele

From: afrontera85 ***@***.***>
Sent: mercoledì 22 maggio 2024 15:43
To: italia/anpr ***@***.***>
Cc: CIBIN Daniele AssuIta ***@***.***>; Author ***@***.***>
Subject: Re: [italia/anpr] [C019] Errore 404 - Unknown API Request (Issue #4541)

[EMETTEUR EXTERNE] / [EXTERNAL SENDER]
Soyez vigilant avant d'ouvrir les pièces jointes ou de cliquer sur les liens. En cas de doute, signalez le message via le bouton "Message suspect" ou consultez go/secu.
Be cautious before opening attachments or clicking on any links. If in doubt, use "Suspicious email" button or visit go/secu.

Bene!!!
Non c'è errore comunque.
L'url è questo:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
L'aud è questo:
https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
Saluti

—

_Originally posted by @danielecibin in https://github.com/italia/anpr/issues/4541#issuecomment-2124878596_

**Comment by afrontera85** [comment]
Ripeto, I possibili motivi del 404 sono:
-	Non vi state presentando con il voucher pdnd nella richiesta (nell’attributo authorization)
-	Il voucher che state presentando nella richiesta non è valido
-	Non state chiamando la url con il metodo http giusto (POST)
Comunque nella issue https://github.com/italia/anpr/issues/4488 c'è un client che consigliamo sempre di usare

**Comment by danielecibin** [comment]
Buongiorno, non è un problema di chiamata perché la stessa procedura lavora con successo verso l'ambiente di collaudo e nemmeno di passaggio di parametri.
Verificheremo con il service providee e vi faremo sapere.
Grazie
