### ISSUE TITLE
non è stato possibile accedere al servizio - ANPR - Servizi anagrafici

### ISSUE THREAD

**Issue by Mauricio-Nazario** [italia/anpr#4544]
Buona Notte!

Caro,

Non riesco ad accedere a Servizi anagrafici - ANPR (https://www.anagrafenazionale.interno.it/).

Il comune ha riferito che non vi è alcun errore nella registrazione.

Di seguito invio l'errore.

Potresti aiutarmi?

Maurício Nazario do Carmo Sant' Anna, nato a Sorocaba - Brasile. Prime sei cifre del mio codice fiscale: NZRMRC
Grazie.

![Error](https://github.com/italia/anpr/assets/69878847/8b2ab957-9ff1-440e-9302-cdb7618782a4)

**Comment by frmariani** [comment]
Mi dispiace ma non siamo riusciti a risalire alla sua iscrizione.
Gentilmente mi indichi il comune in cui dovrebbe essere iscritto.

**Comment by Mauricio-Nazario** [comment]
@frmariani Comune di Loria

**Comment by Mauricio-Nazario** [comment]
> Mi dispiace ma non siamo riusciti a risalire alla sua iscrizione. Gentilmente mi indichi il comune in cui dovrebbe essere iscritto.

Comune di Loria

**Comment by Mauricio-Nazario** [comment]
Comune di Loria

Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em qui., 23 23e mai. 23e 2024 às 3:29, ***@***.***> escreveu:   


Mi dispiace ma non siamo riusciti a risalire alla sua iscrizione.
Gentilmente mi indichi il comune in cui dovrebbe essere iscritto.

**Comment by Mauricio-Nazario** [comment]
> Mi dispiace ma non siamo riusciti a risalire alla sua iscrizione. Gentilmente mi indichi il comune in cui dovrebbe essere iscritto.

Non riesco ad accedere a Servizi anagrafici - ANPR (https://www.anagrafenazionale.interno.it/).

Il comune ha riferito che non vi è alcun errore nella registrazione.

Di seguito invio l'errore.

Potresti aiutarmi?

Maurício Nazario do Carmo Sant' Anna, nato a Sorocaba - Brasile. Prime sei cifre del mio codice fiscale: NZRMRC
Grazie.
Comune: Loria

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.

**Comment by Mauricio-Nazario** [comment]
> Buongiorno, come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare **se il codice fiscale è validato in ANPR** e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.

Il comune ha riferito che non vi è alcun errore nella registrazione.

**Comment by Mauricio-Nazario** [comment]
Buongiorno,
Il comune ha riferito che non vi è alcun errore nella registrazione.

Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em seg., 12 12e ago. 12e 2024 às 11:23, ***@***.***> escreveu:   


Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
