### ISSUE TITLE
Stato finalita' "in attesa di approvazione"

### ISSUE THREAD

**Issue by ArcaVitaInternational** [italia/anpr#4546]
Gentili Signore e Signori,

siamo una compagnia assicurativa e abbiamo inserito oggi 23.05.2024 in ambiente Produzione due finalita' relative al servizio C019 per la verifica di esistenza in vita dei nostri assicurati ma lo stato rimane "in attesa di approvazione" e non riusciamo a capire se abbiamo commesso qualche errore nell'inserimento.
Potreste cortesemente verificare e aiutarci?

Grazie e cordiali saluti,

Arca Vita International

**Comment by afrontera85** [comment]
dovete aspettare l'approvazione da parte del Ministero...
se non arriva potrebbe essere che avete dichiarato un numero di transazioni giornaliere maggiore di quelle previste per singolo fruitore...

**Comment by ArcaVitaInternational** [comment]
Messaggio di posta certificata
Il giorno 28/05/2024 alle ore 12:09:31 (+0200) il messaggio
"Re: ANOMALIA MESSAGGIO: Re: [italia/anpr] Stato finalita' &quot;in attesa di approvazione&quot; (Issue #4546)" è stato inviato da ***@***.***"
indirizzato a:
***@***.***
***@***.***
***@***.***
Il messaggio originale è incluso in allegato.
Identificativo messaggio: ***@***.***

**Comment by afrontera85** [comment]
Per maggior completezza della risposta può vedere il commento della mia collega in un'altra issue: https://github.com/italia/anpr/issues/4553#issuecomment-2137349863
