### ISSUE TITLE
C019 - Limit exceeded detected

### ISSUE THREAD

**Issue by radicedimenouno** [italia/anpr#4547]
Buongiorno,

abbiamo integrato con successo la nostra piattaforma con il web service **C019** che ha risposto correttamente fino al 27/04, permettendoci di interrogare complessivamente 24.986 anagrafiche.
Abbiamo osservato che nel lasso di tempo in cui è stato possibile interrogare il ws, siamo stati in grado di interrogare anche più di 3000 anagrafiche al giorno (che è il limite previsto dalla finalità che ancora stiamo usando) prima di darci un messaggio di errore in cui si evince che abbiamo superato il limite.
Però dal 28/04 il ws ha sempre risposto con il messaggio di errore e non ci ha permesso di interrogare più nessuna anagrafica.

Ad oggi riceviamo sempre il seguente errore:

```xml
{
    "IDUtente": 75,
    "NomeUtente": "administrator",
    "ResponseWrapper": {
        "C019": null,
        "esito": false,
        "responseKo": "{\"type\":\"https://govway.org/handling-errors/429/LimitExceeded.html\",\"title\":\"LimitExceeded\",\"status\":429,\"detail\":\"Limit exceeded detected\",\"govway_id\":\"7b339065-112a-11ef-a4c4-005056ae6555\"}"
    },
    "TipoRichiesta": 1
}
```

Come possiamo ripristinare il funzionamento del servizio C019?

**Comment by afrontera85** [comment]
Avete avuto modo di riprovare?
L'errore è questo:
Policy API 'QuotaFruizione' (metrica: NumeroRichieste) violata: Il numero massimo di richieste (rilevato:50001 soglia:50000) risulta raggiunto per l'intervallo temporale configurato: 
[campionamento realtime, finestra osservazione corrente 2024-05-13_00:00:00.000 - 2024-05-13_23:59:59.999] (raggruppamento: Token: token_clientId)
E' stato superato il numero massimo di richieste giornaliere

**Comment by radicedimenouno** [comment]
Grazie mille, abbiamo riprovato ed ora riusciamo ad interrogare correttamente.

Abbiamo bisogno, però, di alcuni chiarimenti per mettere a punto il nostro servizio di interrogazione:

1. Nella soglia delle 50k richieste giornaliere sono comprese tutte le richieste indipendentemente dall'esito oppure solo le richieste per le quali riceviamo esito true? Abbiamo ricevuto il primo errore 429 Limit exceeded detected dopo 50k chiamate, ma tra queste la maggior parte presentavano esito false con codice errore EN122, altre errore 404, 503 o addirittura 400 Received request is not conform to the required interoperability profile, anche queste sono comunque comprese nel conto?
2. Ha senso configurare il nostro servizio per fermarsi al primo 429 Limit exceeded detected ricevuto, quindi appena, oppure è già troppo tardi e si incorre al blocco dell'utenza?
3. Il servizio per l'interrogazione dell'ID ANPR è già disponibile? E se si, dove possiamo trovare riferimenti tecnici per chiamarlo?

Grazie mille,
Valentina
