### ISSUE TITLE
CONFIGURAZIONE ANPR SUL SITO https://selfcare.pagopa.it/auth/login

### ISSUE THREAD

**Issue by acquedottosca** [italia/anpr#4548]
La scrivente società pubblica, Gestore del Servizio Idrico Integrato in house tra Comuni, desidera integrare la consultazione ANPR nel proprio Protocollo Informatico (fornito da ADS gruppo FINMATICA). Al momento le tre opzioni (vedi allegato) non consentono di completare la configurazione. Si chiedono cortesemente indicazioni. Grazie, cordialmente Federico Mendau

Contatti f.mendau@acquedottosca.it telefono 340.120.90.37

Messaggio di risposta Assistenza PAGOPA

LS (Self Care) 
24 mag 2024, 11:55 CEST 
Buongiorno,
essendo gli E-services, relativi ad ANPR, erogati dal Ministero dell'Interno, suggeriamo di contattare quest'ultimo, oppure, di aprire una Issue sul repository Github [ANPR](https://github.com/italia/anpr/issues) per ricevere le delucidazioni del caso.
 
Cordiali saluti,
Team Assistenza PagoPA

![Cattura](https://github.com/italia/anpr/assets/170734328/39856e36-0861-46e7-a278-c97b4ae01d6c)

**Comment by azabatta** [comment]
Buonasera, 
l'impossibilità di effettuare le richieste dipende dalla classificazione su IPA che non trova riscontro negli attributi stabiliti dal Ministero dell'Interno per poter accedere ai servizi. Il quesito deve essere sottoposto alla Direzione Centrale dei Servizi Demografici del Ministero dell'Interno (sul sito sono presenti i  riferimenti).
Saluti
