### ISSUE TITLE
GovWay-SOGEI C019 Esistenza in vita anpr-service-e002

### ISSUE THREAD

**Issue by saldeangelis** [italia/anpr#4549]
Buongiorno,
ho provato a chiamare il servizio però ricevo il seguente errore con il 
GovWay-Transaction-ID: **077130b2-1c4e-11ef-a482-005056ae5232**
Riuscite a fornirci ulteriori dettagli?

**body**
{"idOperazioneClient": "1","criteriRicerca": {"codiceFiscale": "STTSGT90A01H501J"},"datiRichiesta": {"dataRiferimentoRichiesta": "2024-05-23","motivoRichiesta": "1","casoUso": "C019"}}

**Input:**

<con:endpoint 	name="BusinessService$es-soggetto-posizioneinformativa-be-osb-pagopa$v1$outbound$BS_WS_ANPR" xmlns:con="http://www.bea.com/wli/sb/context">
<con:service/>
<con:transport>
<con:mode>request-response</con:mode>
<con:qualityOfService>best-effort</con:qualityOfService>
<con:request 	xsi:type="http:HttpRequestMetaData" xmlns:http="http://www.bea.com/wli/sb/transports/http" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<tran:headers 	xsi:type="http:HttpRequestHeaders" xmlns:tran="http://www.bea.com/wli/sb/transports">
<tran:user-header 	name="Agid-JWT-Signature" value="eyJ0eXAiOiJKV1QiLCJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJuYmYiOjE3MTY4MzM4NDYsImlzcyI6IjBiNzRmZDI4LWNkMzYtNDJiYi04YjkxLTFjNmRmNzE1Njc5NSIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PTN4RjBYNWc0c0tFVFBLdldnb215THlWcCtYNEcvV3gyanlIWnhuTUZ6Y1E9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dLCJleHAiOjE3MTc0MzM4NDYsImlhdCI6MTcxNjgzMzg0NiwianRpIjoiODQyNDA3YTEtM2Q0MC00ZjYwLWE2MzMtOTU4OWRlNDQ4YmVkIn0.P4HVnEWk-sjPyR_mOeSI2ae6ujoGrNK9MOTj-n9rx1qgA3FjPkRRWXJczAQCJHOiWT5q8-tVJ3IXFWibJYgR_EPVTbqfPy4-e3n5IcDlFu55ZfflWCAcKYaQpjxXw5A0zk0hofRPwQxWguYWOoHCaxGebd00_ht9XjsnMLGNHHQP-jBjpzBbLNwlhf1poQj7N-Y7egGxKvQeSTU8TM_ecQhOzjnVRHwfMyeiNTX1H_znGPjWFa7XMyJgofGzatLNRYZ4o7jgAPy7RZqPVtfM5MQtObr9yb8qmjp0YVa1gxg7jZ5TdJKKqmTU4kyO5jRS-B2-O8H_n-kx0JqnG0yGHA"/>
<tran:user-header 	name="Agid-JWT-TrackingEvidence" value="eyJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMzA0MjExYTYtMGQ5Yy00N2JkLWI5Y2UtODg2MjFjMjViYzQ4IiwiaWF0IjoxNzE2ODMzODQ2LCJleHAiOjE3MTY4NDEwNDYsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.LE7Cf_1I3--BB30NEvWInEprC1pqXvoJq8PQ8tAt6anPoffvKJaOeamzd3U4DwssHko9CXb2KKO4XZg2_yttTK1yKYBt2EyMvgOxBBtupu4NcasOUJVmzgFM_ttNVjtT8mBYEBH2ow20ZJ0tTBFzl9ZwX0tnkLcwp-RCDkPriRFEdV3V1E_Zbb1_EKXqVJ1CmYPVJle4J7MnC_XssxC42QxK5EO-p9O9EB62bQV4C10V3agwMncyLcSE8X-cmSjq8cY05C2NApWrQ3TDwuxQR_HMtSC98g1YHqLtQVy2qNbQf525174CV2weYG8jYayZg3scWhT_KYan6m6-LXyH8w"/>
<tran:user-header 	name="Authorization" value="Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJuYmYiOjE3MTY4MzM4NDYsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6IjRlYTI4NmVmZTEyZTJlZjkzNDE2MDQyZDIyZTI4YzFlZmVlNjBhNTliZTc3YzRiZjliNGYxZTkyMzk1OGZjNzYifSwicHVycG9zZUlkIjoiZWYwYzUwNDAtNGFkYy00MjU2LThlZGUtNGVlMTk4Y2JiOTdlIiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzE2ODM0NDQ2LCJpYXQiOjE3MTY4MzM4NDYsImNsaWVudF9pZCI6IjBiNzRmZDI4LWNkMzYtNDJiYi04YjkxLTFjNmRmNzE1Njc5NSIsImp0aSI6IjY5MjU1MDcyLWM3ZDItNGMyZS1iMjkwLTRjZGMxMmExYjA4YSJ9.KduSW_w7JqqTvVHeVEBeNMhT75LF_-p0KLxJqVJGgU_9LfqhgdarIgyrYFFnfXYW6Wd91tB6BYflvH7nliChIqZ8TAy7SLj9bv_3iM_WeL7-q1Z-7po_Oitj-AVa4ohLrmajVdl8N0j2X4DojZz9mnordLZ4XYVypvg9215d6ltUqA_W60efv-mIWcqlgh8Ixfwt2qJMIGRIpBUp4FZvA9NQIIPUGo1UoHGlYNqz5K1FEvOGNZlIKyUe1gmCCo2_UP6bNC4cJYvXNIqehPlGW7KJFnOrJqyLMODTzmV2WWfV6kaKkFrtSj73E9qUIDRmWfxEgBYFCWIB-77_LWDWFA"/>
<tran:user-header 	name="Digest" value="SHA-256=3xF0X5g4sKETPKvWgomyLyVp+X4G/Wx2jyHZxnMFzcQ="/>
<http:Content-Type>application/json</http:Content-Type>
</tran:headers>
<tran:encoding 	xmlns:tran="http://www.bea.com/wli/sb/transports">UTF-8</tran:encoding>
<http:relative-URI>/anpr-service-e002</http:relative-URI>
<http:http-method>POST</http:http-method>
</con:request>
</con:transport>
<con:security>
<con:doOutboundWss>true</con:doOutboundWss>
</con:security>
</con:endpoint>

**Response:**
<con:fault 	xmlns:con="http://www.bea.com/wli/sb/context">
<con:errorCode>OSB-382502</con:errorCode>
<con:reason>OSB Service Callout action received an error response</con:reason>
<con:details>
<con1:ErrorResponseDetail 	xmlns:con1="http://www.bea.com/wli/sb/stages/transform/config">
<con1:detail>&lt;con:binary-content ref="cid:2fc2e66f:N41:18fbb431d9e:N7ffd" xmlns:con="http://www.bea.com/wli/sb/context"/></con1:detail>
<con1:http-response-code>400</con1:http-response-code>
<con1:response-headers 	xsi:type="http:HttpResponseHeaders" xmlns:http="http://www.bea.com/wli/sb/transports/http" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<tran:user-header 	name="Expires" value="0" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="GovWay-Message-ID" value="842407a1-3d40-4f60-a633-9589de448bed" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="GovWay-Transaction-ErrorType" value="InteroperabilityInvalidRequest" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="GovWay-Transaction-ID" value="077130b2-1c4e-11ef-a482-005056ae5232" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="Server-Timing" value="intid;desc=afc534cd758b83f3" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="X-Backside-Transport" value="FAIL FAIL" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="X-Content-Type-Options" value="nosniff" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<tran:user-header 	name="X-Global-Transaction-ID" value="3f7e3e2d6654ce373183705d" xmlns:tran="http://www.bea.com/wli/sb/transports"/>
<http:Cache-Control>no-cache, no-store, must-revalidate</http:Cache-Control>
<http:Connection>Keep-Alive</http:Connection>
<http:Content-Type>application/problem+json</http:Content-Type>
<http:Date>Mon, 27 May 2024 18:17:27 GMT</http:Date>
<http:Pragma>no-cache</http:Pragma>
<http:Server>GovWay-SOGEI</http:Server>
<http:Transfer-Encoding>chunked</http:Transfer-Encoding>
<http:Vary>*</http:Vary>
</con1:response-headers>
</con1:ErrorResponseDetail>
</con:details>
<con:location>
<con:node>Pipeline Pair Node1</con:node>
<con:pipeline>request-N3f57fef1.4ced8aa4.0.18f2e9d0a74.N7f90</con:pipeline>
<con:stage>ANPR CALL</con:stage>
<con:path>request-pipeline</con:path>
</con:location>
</con:fault>

**Comment by saldeangelis** [comment]
Buongiorno,
gentilmente ruscite a darci supporto?

**Comment by saldeangelis** [comment]
Buonasera,
riusciamo ad analizzare il problema insieme? Siamo in una situazione di urgenza.


Grazie mille per il supporto

**Comment by afrontera85** [comment]
Salve, 
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati
Vi invito a vedere il client di esempio fornito nella issue https://github.com/italia/anpr/issues/4488

**Comment by saldeangelis** [comment]
Salve,
sto utilizzando l'esempio del client, ho sistemato quanto indicato ma ricevo
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "04699dcc-1d0f-11ef-8e89-005056ae5232"
}

C'è anora qualcosa che non setto correttamente?

**Comment by saldeangelis** [comment]
Mi scuso se magari vi scrivo di continuo capisco che stare dietro a tutte queste segnalazioni è difficile, però se riuscite a darmi un pò più di attenzione perchè siamo allo scadere del cut off per il PDND.
Grazie mille

**Comment by afrontera85** [comment]
Buongiorno, in base al govway_id fornito posso dirle che il dettaglio dell'errore è sempre lo stesso:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Content-Type' possiede un valore differente rispetto a quello presente negli header firmati
Infatti negli headers a noi arriva questo valore come Content-Type:
application/json; charset=UTF-8

**Comment by saldeangelis** [comment]
ciao 
ho allineato gli headers aggiungendo anche utf 8 perchè da dove  lancio la chiamata lo aggiunge in automatico, ma ricevo lo stesso errore, è un problema mantenere utf 8?

GovWay-Transaction-ID: 14601704-1d9c-11ef-898e-005056ae5232


![image](https://github.com/italia/anpr/assets/28670106/7fcd3f99-83b8-48f6-8ab3-084b5c681f75)

![image](https://github.com/italia/anpr/assets/28670106/c789a534-43bc-448f-92fe-d7cc75bf5ff6)

**Comment by saldeangelis** [comment]
Ciao,
ho effettuato un'altra prova con questo transaction id 4214f8c5-1da3-11ef-898e-005056ae5232
ricevo sempre errore, digest.value però è fatto dall'encoding della Agid-JWT-TrackingEvidence e il tutto finisce nella chiamata per recuperare il token, di seguito la tracking desiarilizzata, non riesco a capire quale sia il valor che non va bene..
Grazie

{
  "typ": "JWT",
  "kid": "52yNuZlaaCOPLXNf0J9Q8EOv4ec97PrPTTo0zwyEI0o",
  "alg": "RS256"
}

{
  "aud": "https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1",
  "nbf": 1716979337,
  "purposeId": "ef0c5040-4adc-4256-8ede-4ee198cbb97e",
  "iss": "0b74fd28-cd36-42bb-8b91-1c6df7156795",
  "userLocation": "26.2.12.23",
  "exp": 1717579337,
  "dnonce": "1234567890123",
  "userID": "User123",
  "iat": 1716979337,
  "jti": "c86c0114-2353-42af-8aa9-05b253206661",
  "LoA": "LOA3"
}

**Comment by afrontera85** [comment]
L'errore è lo stesso infatti.
La teoria è questa:
Quando si richiede il token a pdnd deve essere inserita nella client assertion l'hash del token Agid-JWT-TrackingEvidence

{
"digest": {
"alg": "SHA256",
"value": "f7f663de6453d91d05cb9324955f78f92ce48abfabb3f26119bf3f02c1ab98ce"
}
}
Dove:
• alg, indica l'algoritmo di hashing. L'algoritmo dovrà generare un hash di lunghezza fissa e dovrà appartenere alla famiglia SHA256.
• value, il valore ottenuto applicando l'algoritmo indicato nel claim digest.alg al JWT di audit

L'errore si prende se, non avendo inserito nella client assertion pdnd quanto sopra, la pdnd non inserisce l'hash nel voucher generato (per delucidazioni su questo chiedere all'assistenza pdnd)

**Comment by saldeangelis** [comment]
Ciao, 
puoi chiudere, ho risolto.

Grazie mille per la collaborazione

**Comment by afrontera85** [comment]
Bene! di nulla
