### ISSUE TITLE
Iscrizione preliminare da comune non subentrato - obbligo inserimento dati matrimonio

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#455]
COMUNE DI VALLE MOSSO - PRODUZIONE

Capita molto spesso che le richieste di iscrizione anagrafica non contengano tutti i dati richiesti e che questi vengano poi inseriti al momento della conferma/integrazione dei dati provenienti dal comune di cancellazione.
In particolare non sempre i soggetti richiedenti ricordano la data di matrimonio e spesso nemmeno il luogo di celebrazione. Inoltre non sempre il titolare dei dati e' presente allo sportello.
Dal momento che se viene indicato come stato civile "coniugato" viene richiesto obbligatoriamente il dato di matrimonio relativo ci si vede costretti ad inserire lo stato civile "sconosciuto/non documentato"  che, a ben vedere, non e' propriamente esatto.
E' comprensibile richiedere il dato alla conclusione del procedimento (iscrizione definitiva) ma si sembra eccessivo obbligare ad inserire un dato sbagliato invece di un dato incompleto in iscrizione preliminare.
Inoltre la certificabilita' di queste persone e' solamente parziale (residenza e stato famiglia) per cui non vi sarebbe possibilita' di emettere certificazioni con dati inesatti.
Ringrazio per l'attenzione

**Comment by frmariani** [comment]
L’errore che viene emesso non mi risulta bloccante, è soltanto un avvertimento nel caso l’utente avesse dimenticato di inserire i dati del matrimonio.

Per il comune di Valle Mosso, tutte le iscrizioni presenti sono senza anomalie; soltanto l’iscrizione con idAnpr 1446674 contiene delle anomalie non bloccanti tra cui:

“Se stato civile divorziato/a deve essere presente la sezione separazioneAnnullamentoCessazioneMatrimonio” .

Può indicare  l’id operazione che è stata bloccata ?

Grazie.

**Comment by RENZO63** [comment]
Comune di Valle Mosso
Il gestionale in uso mi ha bloccato l'operazione in quanto dalle specifiche tecniche l'errore sembrava bloccante.
Se cosi' non e' provvedo ad avvisare la software house per le necessarie modifiche.
La cittadina inserita con lo stato civile "ignoto" e'  19205835 - procedero' ad applicare le modifiche all'arrivo della pratica di cancellazione.
Grazie

Per l'operazione 1446674 credo si tratti di un errore di inserimento del codice relativo allo stato civile. Faccio le necessarie verifiche e procedo con l'invio della giusta comunicazione. Grazie per la segnalazione
