### ISSUE TITLE
[C020] Unknown API Request

### ISSUE THREAD

**Issue by aisolani** [italia/anpr#4550]
Salve,
  dopo essere riuscita a utilizzare il vostro client, ora sto provando a implementarne uno in PHP sempre per la chiamata C020.
Come risposta ho ottenuto un not found. Il  X-Global-Transaction-ID è "3f7e3e2d66545c3a31052fcd".
Mi sapreste gentilmente dare qualche dettaglio ulteriore sugli errori che sto facendo?
Grazie,
Alida

**Comment by afrontera85** [comment]
L'errore 404 - Unknown API Request è un errore che si può prendere per i seguenti motivi:
-	url errata (o metodo http sbagliato)
-	url esatta ma assenza del voucher pdnd nella richiesta (nell’ attributo authorization)
-	url esatta ma voucher pdnd errato nella richiesta

**Comment by aisolani** [comment]
Grazie per la risposta. Avevo verificato queste indicazioni e l'unica che mi pare più plausibile è il voucher errato.
Come posso verificare se il voucher è corretto o meno?
L'ultimo tentativo che ho fatto è "X-Global-Transaction-ID": "3f7e3e2d6655a3cb321c53bd".
Grazie ancora

**Comment by afrontera85** [comment]
Ci serve un govway_id o govway-transaction-id per un dettaglio dell'errore
Comunque se siete riusciti ad utilizzare il nostro client, il problema è sicuramente nell'implementazione in php...
provate magari a cercare tra le issue aperte da altri che hanno usato php
