### ISSUE TITLE
C019 - in attesa di approvazione

### ISSUE THREAD

**Issue by ILuCiOne** [italia/anpr#4553]
Buongiorno ,

per una compagnia assicurativa abbiamo inserito in ambiente Produzione una finalità relative al servizio C019 per la verifica di esistenza in vita degli assicurati ma lo stato rimane "in attesa di approvazione" e non riusciamo a capire se abbiamo commesso qualche errore nell'inserimento.

Ormai è passato piu di un mese, e l'indirizzo email indicato dal ministero per il supporto non ha mai risposto alle nostre email o solleciti (filippocarlo.viglianisi@interno.it)

Il numero di transazioni giornaliere lo abbiamo impostato a 1 (UNO), quindi il problema non è quello.

Potreste cortesemente indicarci come risolvere questo problema ? 
Esiste un altra email/supporto che legga e risponda alle email ?

Grazie e cordiali saluti,

**Comment by azabatta** [comment]
Buongiorno, 
purtroppo il conteggio sulla soglia giornaliera complessiva viene effettuato da PDND sul totale delle chiamate inserite dai singoli fruitori anche se non approvate. La presenza di alcuni numeri esorbitanti, non approvati, per le finalità dell'eservice C019 ha  superato tale soglia massima. Questo comporta che tutti i successivi inserimenti di finalità vadano automaticamente in approvazione a prescindere dal numero di invocazioni indicato.  Abbiamo già rappresentato il problema che al momento si risolve solo con l'approvazione delle finalità da parte del Ministero dell'Interno.
