### ISSUE TITLE
C020: "Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#4554]
Buongiorno, tentando di eseguire una chiamata in produzione al servizio in oggetto otteniamo questo errore.

`errors/400/InteroperabilityInvalidRequest.html",
"title":"InteroperabilityInvalidRequest",
"status":400,
"detail":"Received request is not conform to the required interoperability profile",
"govway_id":"32ec350e-1cf9-11ef-9525-005056ae6555"}"; 
line: 1, column: 10] (through reference chain: it.maggioli.informatica.platform.pdnd.model.RispostaKO["type"])`

L'applicativo con cui eseguiamo la chiamata se configurato su endpoint di collaudo con fruizione di collaudo c020 funziona senza probemi,

Quale può essere la causa ?

**Comment by busaster** [comment]
Dovendo avviare un cliente in produzione avremo urgenza di risolvere la problematica, qualcuno può darci supporto gentilmente ?
Grazie

**Comment by afrontera85** [comment]
L'errore relativo al govway_id fornito è:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by busaster** [comment]
Grazie mille, modificando aud per ANPR abbiamo risolto
