### ISSUE TITLE
COMUNE PARABITA MANCATA CONNETTIVITA' A ws.anpr.interno.it. URGENTE.

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#4555]
Salve. 
Il problema riguarda il **Comune di Parabita** (LE) . 
Riferimento interno : Fernando Solidoro . 
Riferimento tecnico per questo post: Edoado Dona' **338 59 09 376** edoardodona@gmail.com
Ieri mattina abbiamo cambiato dislocazione da on premise a cloud del Sw Anagrafe. 
Nonostante via webapp sia stato aggiunto indirizzo ip del nuovo server  che deve dialogare )con ANPR (**15.161.228.148**) e sia stato soppresso il vecchio indirizzo,  la comunicazione con  ws.anpr.interno.it  NON FUNZIONA.
Nonostante la vostra comunicazione odierna al vs Ticket **03902730** circa la corretta abilitazione dell' nuovo indirizzo e nonostante ulteriore sollecito **03905984** e nuova segnalazione **03907318** **Continuiamo a non raggiungere il vostro ws.anpr.interno.it sulla porta 443.**
Su indicazione telefonica di vs HL di secondo livello ci viene suggerito di inserire la segnalazione su Github e in tal senso , in attesa di celere e cortese riscontro, procedo. 

A riprova che il problema e' a valle allego due esiti di netcat verso di voi : 
Il primo da un server gemello di quello di parabita: 
	---DA SARONNO: 
	root@saronnoakro:/opt/elezioni# nc -z -v ws.anpr.interno.it 443
       Connection to ws.anpr.interno.it (217.175.52.225) 443 port [tcp/https] succeeded!
e il secondo , appun to, da server di parabita.: 
	----DA PARABITA:
	root@parabitaakro:~# nc -z -v ws.anpr.interno.it 443
	nc: connect to ws.anpr.interno.it (217.175.52.225) port 443 (tcp) failed: Connection timed out
(mentre naturalmente analoghe chiamate http verso chiunque ( es. www.google.com 443 ) rispondono immediatamente..)

Saluti
Dona'

**Comment by edoardodona-1** [comment]
Scusate, aggiungo anche per completezza che sulla macchina vecchia ,nonostante il nostro aver disabilitato via webapp il vecchio ip , in realta ,il collegamento con ANPR e' rimasto funzionante.... : 
![image](https://github.com/italia/anpr/assets/57674584/b338188f-863f-461b-91a2-c7fb45cd8a27)

**Comment by Leonforte** [comment]
Vi vediamo transitare con successo, il problema dovrebbe essere risolto, fateci sapere, grazie

**Comment by edoardodona-1** [comment]
Perfetto ora ok.! GRAZIE !


Il giorno mer 29 mag 2024 alle ore 16:59 Leonforte ***@***.***>
ha scritto:

**Comment by edoardodona-1** [comment]
Si esatto . La segnalazione e' stata risolta. Grazie ancora.
