### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by lsecreto** [italia/anpr#4558]
Buongiorno,

Mi chiamo Lucas Secreto, sono iscritto all'AIRE residente in Argentina e ho lo stesso errore del #2683
Il mio codice fiscale inizia con SCRLCS93______

- Testo dell'errore:
`Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.`
- URL dell'errore: `https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth`

Ho controllato la mia Scheda Anagrafica in FastIT e chiedendo al comune (Castelsilano, KR) i valori in AIRE e sembra essere tutto ok.

Cosa posso fare?

Grazie in anticipo!

**Comment by ncapozzi** [comment]
Buongiorno,
verificare con il Comune se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
