### ISSUE TITLE
[5001] Variazione Indirizzo per correzione n.ro di interno

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#456]
ambiente di PRODUZIONE - comune di Faenza - idSchedaSoggettoANPR 19144844

si tratta di soggetto residente dal 2015, inserito in ANPR con il file di subentro.
il cliente si è accorto di un errore storico nell'indicazione dell'interno, ed ha tentato di variare il dato con l'uso del servizio 5001, modificando il numero di interno ma mantenendo la stessa decorrenzaResidenza.

il risultato è che il dato attuale è corretto, ma il vecchio indirizzo è stato storicizzato. 
stampando un certificato di residenza storico, quindi, risultano due indirizzo diversi (dove in realtà cambia solo l'interno) ma stessa decorrenza.

immaginiamo che il servizio utilizzato non si corretto per questa fattispecie di mutazione.
se mi confermate, per sanare la posizione lato ANPR, procederemo con la richiesta di annullamento della mutazione.

ma per risolvere casi dello stesso tipo come occorre procedere?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
E' normale che il vecchio indirizzo venga storicizzato; da quando è stato inserito, l'interno è stato indicato in modo errato ma sulla base di questa informazione i dati sono stati forniti anche alle altre amministrazioni sono stati prodotti certificati e simili.  La procedura che avete utilizzato per sistemare l'interno è quella corretta.

**Comment by AMonopoliADS** [comment]
grazie del riscontro.
attendo di condividere la Sua risposta con il cliente.
da una prima analisi dei risultati, mi hanno segnalato come non corretto quanto documentato nel certificato storico di residenza, in quanto il soggetto risulta avere abitato contemporaneamente in due indirizzi nello stesso frammento storico.
Le faccio sapere

**Comment by gcarbonin** [comment]
Dal momento che la data di decorrenza è la stessa escono le due righe.
