### ISSUE TITLE
Anpr

### ISSUE THREAD

**Issue by Yelyzaveta-art** [italia/anpr#4560]
Buongiorno, non riesco ad accedere ad anpr perché mi da il codice di errore in cui mi viene chiesto di rivolgermi al comune.

Codice fiscale KRVYYZ

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
