### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by carmell11** [italia/anpr#4562]
Buonasera,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

![Capture PNG1](https://github.com/italia/anpr/assets/171583571/ab36d269-36dc-476e-81cb-738f6269b432)

Purtroppo non è stato possibile accedere al servizio

Codice Fiscale TSNSHH

**Comment by carmell11** [comment]
Salve [mttfranci](https://github.com/mttfranci),
potete aiutarmi a risolvere questo problemna? Grazie mille.

**Comment by Yelyzaveta-art** [comment]
ANCHE IO HO LO STESSO PROBLEMA, CODICE FISCALE KRVYYZ9

**Comment by ncapozzi** [comment]
Buonasera,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di iscrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
