### ISSUE TITLE
Chiarimenti su C019 Limit exceeded detected e servizio interrogazione ID ANPR

### ISSUE THREAD

**Issue by radicedimenouno** [italia/anpr#4565]
Avete avuto modo di riprovare?
L'errore è questo:
Policy API 'QuotaFruizione' (metrica: NumeroRichieste) violata: Il numero massimo di richieste (rilevato:50001 soglia:50000) risulta raggiunto per l'intervallo temporale configurato: 
[campionamento realtime, finestra osservazione corrente 2024-05-13_00:00:00.000 - 2024-05-13_23:59:59.999] (raggruppamento: Token: token_clientId)
E' stato superato il numero massimo di richieste giornaliere

_Originally posted by @afrontera85 in https://github.com/italia/anpr/issues/4547#issuecomment-2137514381_

**Comment by radicedimenouno** [comment]
Grazie mille, abbiamo riprovato ed ora riusciamo ad interrogare correttamente.

Abbiamo bisogno, però, di alcuni chiarimenti per mettere a punto il nostro servizio di interrogazione:

1. Nella soglia delle 50k richieste giornaliere sono comprese tutte le richieste indipendentemente dall'esito oppure solo le richieste per le quali riceviamo esito true? Abbiamo ricevuto il primo errore 429 Limit exceeded detected dopo 50k chiamate, ma tra queste la maggior parte presentavano esito false con codice errore EN122, altre errore 404, 503 o addirittura 400 Received request is not conform to the required interoperability profile, anche queste sono comunque comprese nel conto?
2. Ha senso configurare il nostro servizio per fermarsi al primo 429 Limit exceeded detected ricevuto, quindi appena, oppure è già troppo tardi e si incorre al blocco dell'utenza?
3. Il servizio per l'interrogazione dell'ID ANPR è già disponibile? E se si, dove possiamo trovare riferimenti tecnici per chiamarlo?

Grazie mille,
Valentina

**Comment by amollicone1982** [comment]
1)Nella soglia delle 50k richieste giornaliere sono comprese tutte le richieste 

2)Si, ha senso configurare il nostro servizio per fermarsi al primo 429 Limit exceeded detected ricevuto

3)C030 su pdnd (si consiglia di cominciare a memorizzare l'associazione cf - idanpr in modo tale da ricorrere al C030 il meno possibile e limitare overhead inutili)

Buona giornata
