### ISSUE TITLE
C019 - Impossibile staccare il token

### ISSUE THREAD

**Issue by MPaoletti719** [italia/anpr#4566]
Ciao a tutti,
Da un paio di giorni non riesco più a staccare il token per l'invocazione del servizio in oggetto, senza che il codice sia stato in nessun modo modificato.
Di seguito l'errore che ricevo:
{"correlationId":"49543fed-af22-484e-87ee-a90dd992f1a1","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}.

**Comment by saldeangelis** [comment]
Buongiorno,
mi aggiungo anche io 
{"correlationId":"a4e14ab7-7626-4fc1-ba6f-1b7180a69439","title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400}

**Comment by saldeangelis** [comment]
Gentilmente se riuscite a risponderci velocemente perchè abbiamo l'ambiente di produzione bloccato.

**Comment by afrontera85** [comment]
Salve, si tratta di un errore restituito da PDND, quindi è necessario chiedere all'assistenza pdnd.
Di solito il problema potrebbe essere aver inserito clientid o purposeid errato o la finalità risulta ancora in attesa di approvazione...
