### ISSUE TITLE
[C021 - C030] - accesso tramite PDND per Gestore Pubblico Servizio

### ISSUE THREAD

**Issue by svetj** [italia/anpr#4567]
Buongiorno

L'azienda per cui lavoro è classificata su IPA come Gestore di Pubblico Servizio (Servizio Idrico Integrato), è una Società a Partecipazione Pubblica, e intende aderire a PDND, come peraltro previsto dalla attuale normativa.

Tra gli altri, gli e-service che si vorrebbero utilizzare nell'immediato sono i seguenti:

- C030-servizioAccertamentoIdUnicoNazionale-approvazione_autom
- C021-servizioAccertamentoStatoFamiglia 

L'obiettivo è l'acquisizione del numero di Componenti Nucleo Familiare (CNF) per corretta fatturazione servizio domestico residente e corretto calcolo del Bonus Idrico Nazionale.

Tali e-service però tra i requisiti di accesso non includono gli enti qualificati come Gestori di Pubblico Servizio.

Vorremmo capire quindi se, a valle dell'adesione a PDND, si potrà comunque fare richiesta ad ANPR per l'accesso a tali servizi.

Potreste cortesemente darci supporto in tal senso?

Grazie anticipatamente

Saluti
  Stefano

**Comment by azabatta** [comment]
Buonasera, 
il quesito deve essere posto al Ministero dell'Interno che è l'erogatore dei servizi di ANPR e decide chi può essere abilitato al loro utilizzo.
Una volta accreditati sulla PDND è possibile inviare una mail all'indirizzo di riferimento presente sulla piattaforma.
Saluti
