### ISSUE TITLE
C019 ESISTENZA IN VITA ERROR PRODUZIONE

### ISSUE THREAD

**Issue by saldeangelis** [italia/anpr#4568]
Ciao,
in produzione stiamo regolarmente effettuando chiamate però ogni tanto becchiamo un errore:
GovWay-Transaction-ID:"8b498122-2703-11ef-954e-005056ae1d2a"

potete indicarci cosa voglia dire questo errore?

Grazie

**Comment by saldeangelis** [comment]
Buongiorno,
gentilmente ci sono novità in merito?

Grazie

**Comment by saldeangelis** [comment]
Salve riuscite a risponderci gentilmente?

**Comment by saldeangelis** [comment]
Buongiorno,
potreste darci supporto?

Grazie

**Comment by saldeangelis** [comment]
Buongiorno,
gentilmente riuscite ad indicarci cosa nasconde quel transaction id?

Grazie

**Comment by afrontera85** [comment]
Salve, eccolo:
Fault Applicativo (404)
{
  "listaErrori" : [ {
    "codiceErroreAnomalia" : "EN122",
    "testoErroreAnomalia" : "La richiesta effettuata non produce alcun risultato",
    "tipoErroreAnomalia" : "E"
  }, {
    "codiceErroreAnomalia" : "EN148",
    "testoErroreAnomalia" : "Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi.",
    "tipoErroreAnomalia" : "W"
  } ],
  "idOperazioneANPR" : "1817415080"
}

**Comment by afrontera85** [comment]
No, non significa che il CF non è valido, ma quello che è espresso nel testoErroreAnomalia.  
Può consultare questo avviso per maggiori spiegazioni: https://github.com/italia/anpr/issues/4559

**Comment by saldeangelis** [comment]
EN148 lo conosciamo
Si ma EN122 cosa vuol dire? Perchè la richiesta non produce risultato?

Grazie

**Comment by afrontera85** [comment]
Per quanto riguarda l'EN122, il servizio risponde correttamente perchè ci risulta che il CF non ha una posizione attiva in ANPR

**Comment by saldeangelis** [comment]
ok ma quando arriva in risposta errore 404 è riferito sempre a EN122?

Grazie
