### ISSUE TITLE
Iscrizione in ANPR con comune storico non valido alla data

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#457]
Peschiera Borromeo, Ambiente di produzione.

Buongiorno, il comune di Peschiera Borromeo desidera effettuare l'iscrizione in Anagrafe di un cittadino che risulta essere nato a Sant'Egidio del Monte Albino (Salerno) nel 1931 (cod. Catasto I317) che però dal 1929 al 1946 risulta essere cessato e aggregato al Comune di Angri (cod. Catasto A294). Presso l'AE il cittadino in questione risulta validato con l'indicazione di nascita Sant'Egidio del Monte Albino.
Dato che in precedenti comunicazioni mail di maggio 2017, ci era stato indicato che le indicazioni errate del luogo di nascita che comportavano la variazione del codice catastale sul codice fiscale dovevano essere risolte per non correre il rischio di bloccare la posizione del cittadino, vi chiediamo se tale problematica può considerarsi superata e quindi nel caso in cui un cittadino abbia i dati sbagliati, ma coerenti su tutti i documenti, possiamo comunque permetterne la registrazione.
Cordiali Saluti.

**Comment by gcarbonin** [comment]
Da sempre esiste una tolleranza nei controlli sul comune di nascita: se dal dato dichiarato dal comune si ottiene un codice catastale che coincide con quello presente nel codice fiscale A PRESCINDERE DALLA DATA DI ISTITUZIONE/CESSAZIONE DEL COMUNE, ANPR considera validi questi dati e non segnala nessuna anomalia. Come già comunicato al comune, l'iscrizione può essere effettuata indicando come comune di nascita Sant'Egidio del Monte Albino.
