### ISSUE TITLE
Attivazione webservice SOGECAP S.A.

### ISSUE THREAD

**Issue by ptaeggisg1** [italia/anpr#4570]
Buongiorno,
Con la presente si richiede l’attivazione del servizio e-service C019 in ambiente di produzione

Grazie
![image002](https://github.com/italia/anpr/assets/172288912/b3ee8c2e-7085-4ba5-a31b-20de19ef6999)

**Comment by azabatta** [comment]
Buonasera, 
questo canale riguarda l'assistenza tecnica.
Le approvazioni sono effettuate dal Ministero dell'Interno.
Saluti
