### ISSUE TITLE
EN122 - EN148 prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR)

### ISSUE THREAD

**Issue by robertog79** [italia/anpr#4571]
invocando il servizio C019 per la verifica dell'esistenza in vita di un assicurato, vi viene restituito l'errore 404 di seguito un esempio:

_Codice fiscale richiesto_;404;EN122: La richiesta effettuata non produce alcun risultato - EN148: Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi.

il problema si presenta su moltissime anagrafiche

**Comment by azabatta** [comment]
Buonasera, 
di seguito  il dettaglio degli errori: 

- EN122: è un non trovato (404), indica che il soggetto ricercato non ha una posizione attiva in ANPR. I motivi possono essere diversi: il cittadino è stato cancellato dall'anagrafe per decesso o per altri motivi prima dell'ingresso del suo comune in ANPR (i comuni avevano l'obbligo di conferire in ANPR solo posizioni attive); il cittadino è stato cancellato da ANPR per un motivo diverso dal decesso (es. rientro in patria di uno straniero, irreperibilità etc.); il cittadino è presente in ANPR con un altro codice fiscale o altri dati anagrafici. 

- EN148: è un  diagnostico di attenzione non bloccante che viene inviato per tutte le ricerche effettuate con criteri di selezione differenti dall'idANPR. La risposta viene comunque restituita ma viene accodato un messaggio che rinvia alla normativa istitutiva dell'identificativo unico nazionale che diventerà l'unico criterio per accedere ad ANPR.

Saluti
