### ISSUE TITLE
C019 - Errore 400

### ISSUE THREAD

**Issue by robertog79** [italia/anpr#4572]
Invocando il servizio C019 per moltissime anagrafiche verificate la risposta ricevuta è 400 senza descrizione dell'errore:

_codice fiscale richiesto_;400;

il rapporto tra verificati e scartati è molto sbilanciato verso gli scartati nonostante i codici fiscali siano corretti.

**Comment by amollicone1982** [comment]
Ci deve dare l'attributo govway-id ritornato nella risposta per fare delle verifiche

**Comment by robertog79** [comment]
Buongiorno,
questo quanto abbiamo tracciato (il codice fiscale è stato modificato nelle prime tre lettere per motivi di privacy):
13-06-2024 05:55:15 - ----- Interrogazione serivizio per CF XXXLNZ98S60B963I -----
13-06-2024 05:55:15 - { "type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, "detail": "Unknown API Request", "X-Global-Transaction-ID": "db4aa801666a6da302e0d5bd" } 
13-06-2024 05:55:15 - ----- Fine interrogazione serivizio per CF XXXLNZ98S60B963I -----
13-06-2024 05:55:15 - ----- Definizione Body Request -----

**Comment by amollicone1982** [comment]
Possibili motivazioni:

url errata
url esatta ma assenza del voucher pdnd nella richiesta
url esatta ma voucher pdnd errato nella richiesta
chiamata fatta non in POST

**Comment by amollicone1982** [comment]
Per completezza riporto la url corretta come presente sullo yaml:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

ricordando invece che l'aud da usare nei token è leggermente diverso (come indicato sulla pdnd):
[npr-service-e002](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1)

**Comment by robertog79** [comment]
confermo che url e token sono configurati correttamente, infatti il problema non è sistematico, a parità di codice fiscale riceviamo errori o response corrette

**Comment by amollicone1982** [comment]
type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, 
questo errore lo ottiene solamente per le motivazioni indicate sopra.

In alternativa prende dei 400 con un govway-id che è un id transazione
