### ISSUE TITLE
Anomalia EC030 non vera

### ISSUE THREAD

**Issue by anozzoli** [italia/anpr#4574]
Arianna Nozzoli - Sistema informativo Comune di Prato 

Buongiorno,
ho il cittadino 26183572 che presenta una anomalia in ANPR Ec030 ma non risulta che lo stato di nascita sia CINA POPOLARE indicato nell'anomalia. Potete verificare? Grazie

**Comment by ncapozzi** [comment]
Buonasera,
l'anomalia risulta sanata con REPUBBLICA POPOLARE CINESE, non tenga più conto della segnalazione
