### ISSUE TITLE
[7001] Scarico tabelle 61 (tipo categoria) e 62 (tipo componente) - valori errati

### ISSUE THREAD

**Issue by MoniaPedrazzoli** [italia/anpr#4575]
Buongiorno, abbiamo notato che scaricando le tabelle in oggetto tramite il WS 7001 i valori restituiti nella response non sono quelli attesi. Vedi operazioni 71465886 e 71465486 nell'ambiente di TEST del comune 050026, ma lo stesso problema è stato riscontrato anche in ambiente di produzione.

Potete controllare?
Grazie

Monia Pedrazzoli
APKAPPA

**Comment by mttfranci** [comment]
Salve @MoniaPedrazzoli potreste riprovare? l'anamalia dovrebbe essersi risolta cone la patch [8.4.6](https://github.com/italia/anpr/releases/tag/v8.4.6).

Saluti

Assistenza ANPR

**Comment by gppbarone** [comment]
Buongiorno @MoniaPedrazzoli, gli id da inserire per scaricare la tabella **tipocategoria** e **tipocomponente** sono: **63** e **64**, inoltre abbiamo anche aggiornato la documentazione pubblicata sul portale pubblico di ANPR.

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, abbiamo verificato che ora, utilizzando le nuove codifiche 63 e 64, le tabelle vengono restituite correttamente. Grazie
