### ISSUE TITLE
[C003] err 400 -  C003-servizioVerificaDichGeneralita/v1/anpr-service-e002

### ISSUE THREAD

**Issue by NETTunoPA** [italia/anpr#4577]
Buongiorno, siamo la NettunoPa. Stiamo sviluppando per popolare il sistema con i person_id necessari per l'implementazione di altri servizi PDND.
Effettuando la chiamata a https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C003-servizioVerificaDichGeneralita/v1/anpr-service-e002 otteniamo sempre lo steso errore 400 : 
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "7d199bd7-31fa-11ef-b871-005056ae1884"
}

Il voucher viene ottenuto tramite cUrl con una client assertion verificata tramite il debug presente su PDND. 
Potreste fare un controllo sulla chiamata e fornirci ulteriori dettagli. 
Grazie.

**Comment by azabatta** [comment]
Buongiorno, 
di seguito il dettaglio dell'errore:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente

**Comment by NETTunoPA** [comment]
Buongiorno, 
abbiamo seguito le indicazioni nella issue #4234 ma otteniamo ancora err 400. Potremmo avere il dettaglio di errore di questa chiamata gentilmente.
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "7b9588f3-383e-11ef-a4f2-005056ae5232"
}

**Comment by azabatta** [comment]
Buongiorno, 
di seguito le eccezioni rilevate dal sistema:
-  Header HTTP 'Digest' non presente
-  Claim 'signed_headers' con un formato non valido; atteso un array
-  Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

**Comment by NETTunoPA** [comment]
Buongiorno, 
grazie per la risposta intanto.
Settando le impostazioni necessarie sul client otteniamo comunque un errore:
GovWay-Transaction-ID: ee7a5f40-3854-11ef-a4f2-005056ae5232
{"type":"https://govway.org/handling-errors/403/AuthorizationTokenDeny.html","title":"AuthorizationTokenDeny","status":403,"detail":"Insufficient token claims","govway_id":"ee7a5f40-3854-11ef-a4f2-005056ae5232"}

Eppure tutti i passi sono stati seguiti come da readme

**Comment by azabatta** [comment]
Buongiorno, di seguito l'errore segnalato dal sistema:
Verifica autorizzazione [token] messaggio con identificativo [e4a0f4f7-507f-48e7-a16f-0e9beca15b73] servizio [modipa/MinInternoPortaANPR-PDND:modipa/C001-servizioNotifica:1:POST_anpr-service-e002] fallita (Token claim 'aud' with unexpected value) La richiesta presenta un token non sufficiente per fruire del servizio richiesto

**Comment by afrontera85** [comment]
Salve,
vi consiglio di ricontrollare il tutto perchè ci risulta nell'aud il C001-servizioNotifica, poi nell' authorization invece il C030-servizioAccertamentoIdUnicoNazionale. 
Anche nel body dovete indicare il caso d'uso corretto, avete messo  "casoUso" : "C003"

**Comment by NETTunoPA** [comment]
Buongiorno, grazie mille per la collaborazione siamo riusciti a configurare il tutto ottenendo il risultato. 
Tra l'altro il servizio reale che ci serviva era il C030. 
Grazie ancora.

**Comment by LDAV** [comment]
Se possibile, avere indicazioni rispetto a questa richiesta:
"govway_id":"983139e0-5bac-11ef-98aa-005056ae1884"

API responded with code 400: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"983139e0-5bac-11ef-98aa-005056ae1884"}

**Comment by afrontera85** [comment]
L'errore era il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Signature verification failed: [COMPACT] Signature verification failure: Process 'kid' error: Retrieve remote key 'eTQnUN_LmtCjijzI9DySs4KCaZZZ0gkWUElUHWdmPss' failed: Retrieve external resource 'https://govway-anpr-val.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/api-pdnd/v1/keys/eTQnUN_LmtCjijzI9DySs4KCaZZZ0gkWUElUHWdmPss' failed: (http code: 503): { "type": "https://govway.org/handling-errors/503/GatewayError.html", "title": "GatewayError", "status": 503, "detail": "The gateway is currently unable to handle the response", "X-Global-Transaction-ID": "85417d2966bf1e1e6b48b10f" }
