### ISSUE TITLE
PROBLEMI ACCESSO WEB APP ANPR

### ISSUE THREAD

**Issue by rollopack** [italia/anpr#4578]
Buongiorno, il comune di Cavaglietto ha problemi ad accedere alla piattaforma https://dp.anpr.interno.it/com

Abbiamo provato i vari browser installati (Chrome, Firefox, Edge e IE), tutti danno errore:
https://dp2.anpr.interno.it/com
ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED

Come consigliato in un altro ticket, abbiamo già provato anche a scaricare SafeDive 2022, ma senza cambiamenti.

**Comment by dmazelli** [comment]
Buongiorno,
la invitiamo a contattarci al numero verde per verificare assieme la strumentazione.
Saluti.
