### ISSUE TITLE
Anomalie segnalate in fase di subentro e ricadute in fase di Movimentazione e certificazione

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#458]
Buongiorno,
è possibile avere una delucidazione in relazione alle anomalie segnalate in fase di subentro come WARNING con le possibili ricadute in fase di Movimentazione e Certificazione?
 
Nello specifico poiché diverse anomalie segnalate come WARNING in fase di subentro si trasformano in ERROR in fase di servizio, nel caso  una scheda anagrafica persona fisica nella fase di subentro presenti più anomalie (ad esempio EC030 e EC081) , cosa succede nei casi in cui si abbia necessità di utilizzare questi dati da parte dell'ufficiale di anagrafe (CERTIFICAZIONE, MUTAZIONE, ...)? Prima ti utilizzare la detta scheda è necessario da parte dell'ufficiale di anagrafe provvedere prima alla sanatoria di tutte le anomalie oppure è possibile non correggere le anomalie o correggere solo un sottoinsieme delle anomalie? 
 
Sempre relativamente alle indicazioni riportate all'indirizzo web https://anpr.readthedocs.io/en/latest/controllo-certificati/index.html è possibile aggiungere un'ulteriore macro categoria per singolo certificato che evidenzi quali sono i dati obbligatori e non obbligatori presenti necessari per emettere il certificato?
Comune di Bologna

**Comment by gcarbonin** [comment]
Parto dall'ultima domanda che è la più semplice: non ci sono altre cause che impediscono l'emissione dei certificati oltre a quelle indicate al link https://anpr.readthedocs.io/en/latest/controllo-certificati/index.html. Eventuali dati mancanti che compaiono nella stampa del certificato sono riportati con la notazione Assente (ad esempio: il codice fiscale della persona cui è intestato il certificato compare nella stampa di tutti i certificati; se il codice fiscale non c'è il certificato viene emesso comunque riportando al posto del codice fiscale la parola "assente").
Le anomalie da correggere ANCHE DOPO IL SUBENTRO dipendono dal tipo di operazione da fare: l'incompletezza dei dati del matrimonio è un'anomalia da sanare solo per comunicare i dati del divorzio; è influente per produrre un certificato o modificare le generalità.

**Comment by mccalv** [comment]
Salve in generale valutiamo come opportuna questa integrazione della documentazione, richiesta anche da altri comuni.

**Comment by gcarbonin** [comment]
A questo link sono evidenziati gli effetti delle anomalie sulle successive operazioni di registrazione https://www.anpr.interno.it/portale/documents/20182/239162/anomalie+al+subentro+e+operazioni+di+registrazione.xlsx/3d44dc93-52e1-48d9-ba46-8cbc09f222bc
