### ISSUE TITLE
[C019] - Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by pasqualelanciotto** [italia/anpr#4580]
Buongiorno,
stiamo ottenendo sempre l'errore 400 senza capire dove intervenire.
L'errore ottenuto è:
`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"6a86ae91-32dc-11ef-a8dd-005056ae6555"}
`
Stiamo utilizzando il client clientAnpr-1.0.zip fornito in un post precedente.
Potete cortesemente farci sapere?
Grazie

**Comment by azabatta** [comment]
Buongiorno, 
non riusciamo ad individuare la transazione indicata, in particolare il govway-id che è necessario per il monitoraggio. L'ambiente che state utilizzando è quello di collaudo?

**Comment by pasqualelanciotto** [comment]
Buongiorno,
l'ambiente è quello di produzione.
Abbiamo risolto.
Il problema era il seguente:
```
#Token Agid-Jwt-Signature
#audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1

# valore corretto:
audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
```
Grazie per il supporto.
