### ISSUE TITLE
[4582] Impossibilità di accedere al servizio ANPR per anomalia dati anagrafici

### ISSUE THREAD

**Issue by crisbonaldi** [italia/anpr#4582]
Trovo questo errore appena provo a fare l'accesso ad ANPR con SPID.
![Screenshot 2024-06-25 184436](https://github.com/italia/anpr/assets/170545174/64eafd81-7f35-439f-818e-47a11e605d8e)

Codice fiscale: BNLCST__________

Grazie!!

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
