### ISSUE TITLE
Passaggio di stato in errore in pratica online cambio residenza

### ISSUE THREAD

**Issue by anprpa** [italia/anpr#4583]
Buongiorno, c'è una pratica di cambio residenza per la quale non riusciamo a fare il passaggio di stato.

**Pratica ANPR 28704027**
La pratica è stata resa irricevibile, ma risulta nello stato 'aperta'.

Facendo una visura ANPR vengono restituiti questi errrori;
errore EN148 Errore nel recupero del dettaglio pratica.
errore EN527
Informazioni sull'operazione da fornire in caso di assistenza:
data 2024-02-05 11:15:09  
idOperazioneANPR 1625583612

Ivana Ragni - SISPI - Comune di Palermo

**Comment by gppbarone** [comment]
Ciao, il problema per noi risulta risolto, ci confermate? @anprpa

**Comment by anprpa** [comment]
Problema risolto. Grazie
