### ISSUE TITLE
C019-servizioAccertamentoEsistenzaVita-approvazione_automati FINALITA' IN ATTESA DI APPROVAZIONE

### ISSUE THREAD

**Issue by MNFGLN65L24I225A** [italia/anpr#4584]
Buonasera, vi contattimao perche' in urgente attesa di approvazione dal Ministero dell'Interno.
Avremmo necessita' di approvazione entro oggi 28/06/2024.

**Finalità	E-service	Erogatore	Stato finalità	
Nuova finalità 28/06/24 11:25	C019-servizioAccertamentoEsistenzaVita-approvazione_automati	Ministero dell'Interno	
in attesa di approvazione**

Cordiali saluti,
AWP HEALTH & LIFE SA
Amministratore

**Comment by afrontera85** [comment]
Salve, per le approvazioni bisogna rivolgersi al Ministero dell'Interno, questo è un canale di supporto tecnico
