### ISSUE TITLE
Verifica attributi per fruizione servizi ANPR

### ISSUE THREAD

**Issue by NEGRIMA** [italia/anpr#4585]
Buongiorno. Desidero sapere quali attributi sono necessari alla Porvincia di Mantova per poter fruire dei servizi ANPR.
Grazie

**Comment by azabatta** [comment]
Buongiorno, 
ci scusiamo per il ritardo nella risposta.
Gli attributi necessari per poter richiedere un servizio di ANPR sono indicati sul catalogo pubblicato sulla PDND selezionando lo specifico servizio. 
Le province possono sottoscrivere tutti i servizi presenti sulla PDND che prevedono tra i fruitori le Pubbliche Amministrazioni.
Per i servizi di "verifica" è possibile sottoscrivere la versione con approvazione automatica abilitata per tutte le PA. Per tutti gli altri  servizi di  la richiesta è invece soggetta all'approvazione da parte del Ministero dell'Interno.
Saluti
