### ISSUE TITLE
EE999 Servizio Agenzia Entrate momentaneamente non disponibile

### ISSUE THREAD

**Issue by baldissinn** [italia/anpr#4586]
Buongiorno,
come tecnico halley stiamo riscontrando varie anomalie in fase di iscrizione / variazione anagrafiche nello specifico errore "EE999 Servizio Agenzia Entrate momentaneamente non disponibile."

attendo riscontro se problema generalizzato, grazie

**Comment by INSIEL1** [comment]
buon giorno, anche i nostri comuni in regione FVG (INSIEL ) lamentano problemi con Agenzia delle entrate e ricevono
AEE97 oppure EE999

attendiamo riscontro

**Comment by azabatta** [comment]
Ci scusiamo per il ritardo nella risposta, il 3 luglio u.s. ci sono stati problemi di colloquio con i servizi  di Agenzia Entrate. Il problema è rientrato intorno alle ore 13.
Saluti
