### ISSUE TITLE
EN148 - Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi

### ISSUE THREAD

**Issue by gp-elips** [italia/anpr#4590]
Salve,

da quealche giorno, riceviamo questo errore nella risposta e siamo preoccupati perchè non capiamo se i dati restituiti sono affidabili oppure no.

idOperazioneANPR":"1855394618"
:[{"codiceErroreAnomalia":"EN148","testoErroreAnomalia":"Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi.","tipoErroreAnomalia":"W"}]

per accedere usiamo il client esempio fornito da voi presso questo link : https://github.com/italia/anpr/issues/4488

Dobbiamo apportare qualche modifica? Se si, potreste indicarci piu dettagli?

Grazie in anticipo,
Gaetano

**Comment by rglauco** [comment]
Buongiorno @gp-elips qualche tempo fa ho preso il client come base e ho integrato la chiamata al servizio C030: https://github.com/rglauco/clientApiAnprPdnd

**Comment by migmar68** [comment]
Vedi anche:
https://github.com/italia/anpr/issues/4559

**Comment by azabatta** [comment]
Buongiorno, 
ci scusiamo per il ritardo nella risposta.
Il funzionamento degli eservice non è stato modificato, è stato solo aggiunto un messaggio di "attenzione" nella risposta quando la ricerca avviene con un criterio diverso dall'idANPR.
Ringrazio i colleghi per il rinvio alle issue disponibili sull'argomento su questo canale.
Saluti
