### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by willicom2000** [italia/anpr#4592]
ERROR:
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Le prime 6 cifre del tuo Codice Fiscale:
LPLLDR

**Comment by ncapozzi** [comment]
Buonasera,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di iscrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID.
