### ISSUE TITLE
endpoint notifiche non ricevute

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4593]
Buonasera, sembra che i primi di giugno (3-4-5) non siano state recapitate tramite endpoint 5 notifiche, riporto qui gli idOperazioneANPR
1809004021 (per 3 soggetti)
1808117725
1811451654
in produzione comune 041069
potete verificare?

**Comment by azabatta** [comment]
Buongiorno, 
ci scusiamo per il ritardo della risposta. 
La notifica collegata all’evento anagrafico con idOperazione ANPR 1811451654 risulta inviata con esito positivo il 06/06/2024 09:00:19. 
Le altre notifiche erano andate  in errore dopo 5 tentativi di invio, verso il servizio comunale di accoglienza, non andati a buon fine. Sono state inviate nuovamente con esito positivo. 
Saluti
