### ISSUE TITLE
CARTA SCONOSCIUTA

### ISSUE THREAD

**Issue by filippo1961** [italia/anpr#4594]
Buongiorno,
scrivo per fare presente quanto segue:
nel mese di ottobre - novembre 2020 abbiamo ritirato la Smart Card del Sindaco in Prefettura ma non hanno mai funzionato. Inserite nel lettore appare "carta sconosciuta". 
In attesa di riscontro 
Cordiali saluti

**Comment by dmazelli** [comment]
Salve,
per la tipologia di scheda indicata è necessario utilizzare il driver Safedive presente sul sito ufficiale ANPR , nella sezione  "Area tecnica" / "Guida all'ANPR" .

Di seguito riporto il link diretto: 
https://d2nu8i0ja8i6qk.cloudfront.net/driver/SafeDive2023v.5.0.0_setup_minidriver.exe

Le ricordiamo che la Ns assistenza è a disposizione in caso di ulteriorie necessità al numero verde 800.86.31.16.
Saluti.
