### ISSUE TITLE
Response: Unknown API request

### ISSUE THREAD

**Issue by belarbim** [italia/anpr#4595]
Hi, 

I tried to get access to the following endpoint: 
`https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002` based on the yaml file provided for the API "C019-servizioAccertamentoEsistenzaVita".
The response that I got is :
`{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "3f7e3e2d6691521a619ec6fd"
}`

Please find my curl request:

curl --location --request POST 'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002' \
--header 'Agid-JWT-Signature: eyJ4NWMiOlsiTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDMjFteW92SGhvR3hIUGtIZTR2R2c3Zy8rM1F6T0IrcTBQM0Rtdm00VkxRZERSVXUwV24vL0RZbXRMOWdMb29FN2pnRUdVcWh6ZmFFOHI5ZWlhbjcrdTRxbVB4NHdKdmtYRHIySExJempjc3lwdnlSd1ltL0YySmJKYmNOWTVZL2V5YXZsTk5KdWxTV1NRL2l2QVlSRlliMnY2ODByVjlWTWhnd3U2ZXFVdGxjUEdMcE96QkVvalowdkRJbWZZUk9TUWJRVWxDdnJRakt6L1gyWU5oN1JuYjRlc2ltSkh2ekxINVRaTVRQYktaSGp2c0RzNGp6ek9EUFllUmgxWlFRVGFsUmxDS0lUQmo5SDJnUVkweTIxNUF5RE9Ea3BvQ3RlZURNOFRxNHY1SSswaW9kVUsyU3c0ZjFuQms3d3lYdWhwaklxWjlnVW5aL3hvdEwxSkROdEJBZ01CQUFFQ2dnRUFUeUtZcmlIQTVhSk52NjV5T3dtRS9ibUFuUVBmajlMOVE3K1lVaXI0Y3QyK01WTjRuWkhMdy9mZG8rZUxVNzlLMWNubDJLQVdWaFhTS3A5Sk9WK0tPZm9OMU5iVUJFV1A4WVgveUVucTZ3ODYvMTRtcEhvZWRQb1U2K0gzUHFqSGhUZ3F4aUZPZXFnOCtFcWlpaVlaT1ZNa2c5MzRsb21UblE0WXJmSTJldmM2REFubWU4QklXZy92MUFlQnRtZDV1eXhuYmdSaTJFZXk2djhqOW1ud3NpMG9qd0ZBWExZRzlub1hwSVptd0pqcThCNFNEdG5za01IUXR5WHJhakhUUklWNEJRR2NkOFRJaVZkKytpVGFrait3MDFjbVBPcHllamIvd3VxamhEZTlnaDhYYTRUcXZvUy8xeVNEMmdQME5MVFlYUmhzeVJYbVBTTDRNTHZlcndLQmdRRDJCbmc0Um41bzJMRSthNG1sZFl4cWZXcFpZRDhyQ2R2OVJFTVJGYktmTUNoQzdlVFVCaFpaNHZMRDBrWktteHdvbDYvWmE2UGpGRXErWERGbmxtc1cxN2k3VkNjdkZ3QUV4eThSU2JTUGNHTWlHMklUd3U0OUhJNkI4dk8wcE9Ndnh1SGwwQmJDRGc1dTQxZEVKbjh1MWdKVXFxKytCZ0pocXJwdnFaRFd5d0tCZ1FDK1FCOEdZU2gwMGpsaGowbUtMdFY3YlRwbEs4Y3lVYksxOWYrakcwR3MvNFhncitJbyszUm4xNDdTdHRZZy9jdnVLUEhmYUVOZER3bVVRRzBEMkVKTE4vK0hNNVFBUEhuM2w2aU81ZDJIZkxCeWFHV1VCYVJZZ2pxbmZNTFB5andxbk1QcUJvME9abEZjMWw5SFVlTXlrdDMzamRlT0hNUHZrOFV0eCtGSW93S0JnQzF4S25seWc5ekgwWTB1L2NDakFxbVV1clVCY3dsM0M3d3ZCSmcrUXJ6bWZ6bEZpWk9rQURMZ0dXa1VDTW0wOXJHRXV3VlV2WE92QnRNOFloKzVCOVN6U2JySUkyaXVQZUdrRE15THFaOG82aGFkcWpMdU9XVHVSbUE0U00xZisxcVN5SnpUSDdEK09hby9zWm16NXAvM0JYMHYvY0FDaWlRU0RkZWNJVldiQW9HQkFKUDlSdVRzZ003V2xJSWFOcWRCcFJoOHI5YnhCZU5UZjhOaFZ2aG1oR0R3NXhBUFlNcG1SM2RiU3lNSHpHc2ZZUm1pU2Z0eG5DendQSkJReVR3YlpmNGkwaWMyYk9MK0tCWDdwOGQ0Y1NrcVNnckV3SGN6S0ZNZEFrazBtRW1RVTlzRjFMUGZZcXdYMVNSMU1PcEdmWWZpakwwN1hiaVRFYXJ6OUlhWEc5d25Bb0dBUmFqeXFLdVJUZC9lb0NxcGIyNDRNZDBFNDNIako1QUVYNi80NWJwUmt4Zmc0SWk3MzhjbHR5czVWcGw5R0JZNVFDUlQydkRCLzFOSlRKNGx6ZXNmcHovam9SdjMyaFNHc1RrKysxdnZEMkxiYjlKZWVSbXRaRUE2THM0QmZkZmZ2TVBXNVBIMWduM0M1QnZtckVLeEt1LzlJZXRvOHpscGIvanZTK1RFc0tRPSJdLCJ0eXAiOiJKV1QiLCJraWQiOiJUNEpQR3kzbmhMVmdGdmdQX2FfY2MtMEJsQU9BaTd1TlBPVjdGYzlrQ3FrIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi1QRE5EL0MwMTktc2Vydml6aW9BY2NlcnRhbWVudG9Fc2lzdGVuemFWaXRhL3YxL2FucHItc2VydmljZS1lMDAyIiwic3ViIjoiOGE1MmU4MjEtOWI2OS00OTgxLWExMjEtMjk3ZDhiZjJlMmM3IiwibmJmIjoxNzIwNzk4NzI0LCJpc3MiOiI4YTUyZTgyMS05YjY5LTQ5ODEtYTEyMS0yOTdkOGJmMmUyYzciLCJzaWduZWRfaGVhZGVycyI6W3siZGlnZXN0IjoiU0hBLTI1Nj1hUTV0RSs0Ris3SXlLcGVYTGxBVmNVVm5JV0toN0F1SHVkZ3RlWnJJSk80PSJ9LHsiY29udGVudC10eXBlIjoiYXBwbGljYXRpb24vanNvbiJ9XSwiZXhwIjoxNzIxMzk4NzI0LCJpYXQiOjE3MjA3OTg3MjQsImp0aSI6ImNmN2EwY2MxLTdiMzYtNGM5Ny04Y2Y3LThlYTU0ZjgzMzQwMiJ9.I0ks1D0KuQntoq8W1Yzg65jhSMjackXxmNXQLBUy9qz62KB3HMfHLe44JFt0wbSmVbqmL3vNuoSarkmlwHAo86h0lvzE_FMYUsPYSh-bp24WiPBlZG87w6EVLO4ckZVs3DQMk5y6KaQ8ifbwo0oTxcoxo7PWSE6bivv09IUjzvAH1nuWjAsmPHmYWb1nVtGSmqISWPMPIzaC5z4rx4knDPkhNo2B6NzmLV-aOH2jchWTGrOGmOLNDUOdFTsnUff_HNJ8H7HWbanDupfNrdUe0e_CCNW2y5i42gzS_-IRor8ZqCXJiKkN2VWmWzbqwwpyIuYJy5DyTDjqeGD55q8L2g' \
--header 'Agid-JWT-TrackingEvidence: eyJ4NWMiOlsiTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDMjFteW92SGhvR3hIUGtIZTR2R2c3Zy8rM1F6T0IrcTBQM0Rtdm00VkxRZERSVXUwV24vL0RZbXRMOWdMb29FN2pnRUdVcWh6ZmFFOHI5ZWlhbjcrdTRxbVB4NHdKdmtYRHIySExJempjc3lwdnlSd1ltL0YySmJKYmNOWTVZL2V5YXZsTk5KdWxTV1NRL2l2QVlSRlliMnY2ODByVjlWTWhnd3U2ZXFVdGxjUEdMcE96QkVvalowdkRJbWZZUk9TUWJRVWxDdnJRakt6L1gyWU5oN1JuYjRlc2ltSkh2ekxINVRaTVRQYktaSGp2c0RzNGp6ek9EUFllUmgxWlFRVGFsUmxDS0lUQmo5SDJnUVkweTIxNUF5RE9Ea3BvQ3RlZURNOFRxNHY1SSswaW9kVUsyU3c0ZjFuQms3d3lYdWhwaklxWjlnVW5aL3hvdEwxSkROdEJBZ01CQUFFQ2dnRUFUeUtZcmlIQTVhSk52NjV5T3dtRS9ibUFuUVBmajlMOVE3K1lVaXI0Y3QyK01WTjRuWkhMdy9mZG8rZUxVNzlLMWNubDJLQVdWaFhTS3A5Sk9WK0tPZm9OMU5iVUJFV1A4WVgveUVucTZ3ODYvMTRtcEhvZWRQb1U2K0gzUHFqSGhUZ3F4aUZPZXFnOCtFcWlpaVlaT1ZNa2c5MzRsb21UblE0WXJmSTJldmM2REFubWU4QklXZy92MUFlQnRtZDV1eXhuYmdSaTJFZXk2djhqOW1ud3NpMG9qd0ZBWExZRzlub1hwSVptd0pqcThCNFNEdG5za01IUXR5WHJhakhUUklWNEJRR2NkOFRJaVZkKytpVGFrait3MDFjbVBPcHllamIvd3VxamhEZTlnaDhYYTRUcXZvUy8xeVNEMmdQME5MVFlYUmhzeVJYbVBTTDRNTHZlcndLQmdRRDJCbmc0Um41bzJMRSthNG1sZFl4cWZXcFpZRDhyQ2R2OVJFTVJGYktmTUNoQzdlVFVCaFpaNHZMRDBrWktteHdvbDYvWmE2UGpGRXErWERGbmxtc1cxN2k3VkNjdkZ3QUV4eThSU2JTUGNHTWlHMklUd3U0OUhJNkI4dk8wcE9Ndnh1SGwwQmJDRGc1dTQxZEVKbjh1MWdKVXFxKytCZ0pocXJwdnFaRFd5d0tCZ1FDK1FCOEdZU2gwMGpsaGowbUtMdFY3YlRwbEs4Y3lVYksxOWYrakcwR3MvNFhncitJbyszUm4xNDdTdHRZZy9jdnVLUEhmYUVOZER3bVVRRzBEMkVKTE4vK0hNNVFBUEhuM2w2aU81ZDJIZkxCeWFHV1VCYVJZZ2pxbmZNTFB5andxbk1QcUJvME9abEZjMWw5SFVlTXlrdDMzamRlT0hNUHZrOFV0eCtGSW93S0JnQzF4S25seWc5ekgwWTB1L2NDakFxbVV1clVCY3dsM0M3d3ZCSmcrUXJ6bWZ6bEZpWk9rQURMZ0dXa1VDTW0wOXJHRXV3VlV2WE92QnRNOFloKzVCOVN6U2JySUkyaXVQZUdrRE15THFaOG82aGFkcWpMdU9XVHVSbUE0U00xZisxcVN5SnpUSDdEK09hby9zWm16NXAvM0JYMHYvY0FDaWlRU0RkZWNJVldiQW9HQkFKUDlSdVRzZ003V2xJSWFOcWRCcFJoOHI5YnhCZU5UZjhOaFZ2aG1oR0R3NXhBUFlNcG1SM2RiU3lNSHpHc2ZZUm1pU2Z0eG5DendQSkJReVR3YlpmNGkwaWMyYk9MK0tCWDdwOGQ0Y1NrcVNnckV3SGN6S0ZNZEFrazBtRW1RVTlzRjFMUGZZcXdYMVNSMU1PcEdmWWZpakwwN1hiaVRFYXJ6OUlhWEc5d25Bb0dBUmFqeXFLdVJUZC9lb0NxcGIyNDRNZDBFNDNIako1QUVYNi80NWJwUmt4Zmc0SWk3MzhjbHR5czVWcGw5R0JZNVFDUlQydkRCLzFOSlRKNGx6ZXNmcHovam9SdjMyaFNHc1RrKysxdnZEMkxiYjlKZWVSbXRaRUE2THM0QmZkZmZ2TVBXNVBIMWduM0M1QnZtckVLeEt1LzlJZXRvOHpscGIvanZTK1RFc0tRPSJdLCJ0eXAiOiJKV1QiLCJraWQiOiJUNEpQR3kzbmhMVmdGdmdQX2FfY2MtMEJsQU9BaTd1TlBPVjdGYzlrQ3FrIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi1QRE5EL0MwMTktc2Vydml6aW9BY2NlcnRhbWVudG9Fc2lzdGVuemFWaXRhL3YxL2FucHItc2VydmljZS1lMDAyIiwic3ViIjoiOGE1MmU4MjEtOWI2OS00OTgxLWExMjEtMjk3ZDhiZjJlMmM3IiwibmJmIjoxNzIwNzk4NjkwLCJwdXJwb3NlSWQiOiIxN2FkMTYxMi1lY2E0LTQ2NTAtYWNiZS1mMWY3ZTdlNWMxNzQiLCJpc3MiOiI4YTUyZTgyMS05YjY5LTQ5ODEtYTEyMS0yOTdkOGJmMmUyYzciLCJ1c2VyTG9jYXRpb24iOiIyNi4yLjEyLjIzIiwiZXhwIjoxNzIxMzk4NjkwLCJkbm9uY2UiOiIxMjM0NTY3ODkwMTIzIiwidXNlcklEIjoiVXNlcjEyMyIsImlhdCI6MTcyMDc5ODY5MCwianRpIjoiMGVhNWM4MGYtYTRiNC00MTM0LTlmMWQtODRiNWEwYjEyMzUzIiwiTG9BIjoiTE9BMyJ9.M1s99n6aiQIFkwc1jT-mozFd9QYFWYPjqNJZOcXClOQY2pM7Re4gtAmkyKTU4ii9lF_FIxD4Z4W_7rLO_eOtseNrhAHoCJ72TkPP_888H_rWXUQOIc3WIgdGfsrTvn18TU4DG7j0Nl69-swRuOz0AimEBxGfhMsTY9ut0vJJBPl9hD_wM2B8KrpygH-AJJyQ5Ug6jyQ8wbyC1l3DKZjMBnebE_Cmb6Mb56TyfFHORuJp1EKn5xOEzRSWR856TagDCcFDHDU67C91TUwQ_XrIyl31iLeJBS4plGgDyvnYaUPWGAIh7EQNfsNA_AKVQM0YjmqyTkWyjiTPH8MhefxtmA' \
--header 'Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi9DMDE5LXNlcnZpemlvQWNjZXJ0YW1lbnRvRXNpc3RlbnphVml0YS92MSIsInN1YiI6IjhhNTJlODIxLTliNjktNDk4MS1hMTIxLTI5N2Q4YmYyZTJjNyIsIm5iZiI6MTcyMDc5ODcyMSwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiY2FmMzFiNDhlMzU1YTkwOTA1YmU2Y2YzNmU0NGFiZDlkNzM5MTM2MWEwYzg4Zjk4NjM1MDg1OTgxZjRiZWU4MiJ9LCJwdXJwb3NlSWQiOiIxN2FkMTYxMi1lY2E0LTQ2NTAtYWNiZS1mMWY3ZTdlNWMxNzQiLCJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTcyMDc5OTMyMSwiaWF0IjoxNzIwNzk4NzIxLCJjbGllbnRfaWQiOiI4YTUyZTgyMS05YjY5LTQ5ODEtYTEyMS0yOTdkOGJmMmUyYzciLCJqdGkiOiJkMzVkMDAxNS0yYWI1LTQ4NTgtYTM3Ni1jOGUzOTk0ZGUyMDgifQ.CdmCDptdi7AdTxAfnrbnB_1xsSjhlyMeqXo4qdAvMiN41krVy36VkJV5kEP_Eaif4EX3kjDKRvqPcZSlKL08zITOeQ2nBUY7iOVm_PfTstIFzz_wICql3jTAYeSW2mP488KOljY10BMjwMvygvBoOf-1P7_-kbhfbgdXyl8o28iXAiYuf2toH6ILk9yfI9gIZYqafUs_9MFgfDxJEnVS2Xt3FsdUdJeb3_V7ReZqRMCqsui3PTN5rJRyrmBTFUyja0xdxc6Mzvc83uNrcvePuZPstqRgMndcD5apgC0CYHm-QI8kNprdvFQHd0YpLxoyhNqJ8Fuvtn9JhXvFbWMiUg' \
--header 'Content-Type: text/plain' \
--data-raw ' {
   "idOperazioneClient": "1",
     
    "criteriRicerca": {
      "codiceFiscale": "RFCRLB54P69F839F"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2024-07-12",
      "motivoRichiesta": "1",
      "casoUso": "C019"
    }
  }
  '

Can you explain why the endpoint is not valid ? Also can you tell if my request is valid meaning that it contains all the headers and the needed bearer token ?

Thanks for the support.

**Comment by afrontera85** [comment]
check again "aud",  the correct is: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

**Comment by belarbim** [comment]
Hi, 
 I still have the same issue.
Here is my property file (I use the java application referred in some other threads):

`
baseurlapi=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=###################
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd=############
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalità es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd=################

audPdnd=auth.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.interop.pagopa.it

#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
proxyhost=127.0.0.1
proxyport=8888
proxyuser=
proxypwd=

fileTest=test1
`

The response that I got:
`GovWay-Transaction-ID: null
{ "type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, "detail": "Unknown API Request", "X-Global-Transaction-ID": "3f7e3e2d66978b1866ac1c6d" } `

Thanks for your help.

**Comment by afrontera85** [comment]
Possible reasons for this error :

- wrong url
- exact url but no pdnd voucher in the request
- correct url but incorrect pdnd voucher in the request
- call made not in POST

**Comment by belarbim** [comment]
- The urls are the ones defined in the yaml file.
- The pdnd vaucher seems to be good, there is an example of it in my first message.
- The pdnd vaucher is included in the request
- The request is a post.

I'm still stuck with getting access to the service. Do you have an exemple of curl request that works ? Then I'll replace the values with mine.

Thanks

**Comment by afrontera85** [comment]
We don't have an example of a curl request to give you, 
you can search for it in the issues opened by other users...
In the issue #4488 we have provided an example java client

**Comment by rglauco** [comment]
Hello @belarbim,
in your config file it seems that you're using the production pagopa oauth url, but you're querying the test anpr service.
You should use:

```
audPdnd=auth.uat.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.uat.interop.pagopa.it
```

**Comment by belarbim** [comment]
HI, issue solved and related to urls.

Thanks for your support.
