### ISSUE TITLE
impostato enpoint notifiche ma ancora nessuna notifica

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4596]
Buongiorno, settimana scorsa è stato impostato l'endpoint in produzione per 043053, da webapp risultano 6 notifiche, però non le abbiamo ricevute tramite enpoint, potreste controllare se l'invio tramite endpoint è stato effettuato e non è andato a buon fine oppure non sono state inviate per qualche motivo?

grazie mille

**Comment by Hdemografici** [comment]
Buongiorno, ad oggi ancora non tornano le notifiche è possibile un controllo?

**Comment by azabatta** [comment]
Buonasera, 
ci scusiamo per il ritardo nella risposta.
L'endpoint del comune non risulta attivo, è necessario verificare i dati impostati dalla web app di ANPR al seguente percorso:

Amministrazione 
        Gestione dati del comune  - sezione Informazioni per le notifiche
