### ISSUE TITLE
COMUNE DI NOCETO NUOVO IP NON COMUNICA CON ANPR.

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#4598]
COMUNE DI NOCETO. 
Salve. 
Abbiamo cambiato IP ieri mattina ma nonostante vari messaggi ( riporto il primo) a indirizzo sogei preposto ancora ora non riusciamo a comunicare con ANPR. 
Riporto mail di ieri : 

_A: 'ass.abilit_ip.anpr@sogei.it' <[ass.abilit_ip.anpr@sogei.it](mailto:ass.abilit_ip.anpr@sogei.it)>
Oggetto: ABILITAZIONE NUOVO IP COMUNE DI NOCETO (PR)

ABILITAZIONE NUOVO IP COMUNE DI NOCETO (PR)

Buongiorno 
Stamattina alle 8.45 circa , con smart card del sindaco, abbiamo indicato il nuovo ip del comune di NOCETO = 15.161.149.107
e dopo poco e’ apparso a fianco l’ asterisco di abilitazione. 
Nonostante cio’ ancora ora 10.10 la comunicazione con anpr non funziona. 
Potere verificare. 
Grazie .

Dona':  338 59 09 376 
Ref Comune : 0521 622112

GRAZIE!

**Comment by azabatta** [comment]
Si chiude dopo contatto diretto per verifica risoluzione del problema.
