### ISSUE TITLE
Web app [1002] Anomalia su Comune nascita cessato

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#46]
Ambiente di test – 20/03/2017
A seguito dell’operazione ID 441291, è stato iscritto il soggetto ID ANPR 3876237 con i seguenti warning:

```
<anomalie>
<codiceErroreAnomalia>EN336</codiceErroreAnomalia>
<tipoErroreAnomalia>W</tipoErroreAnomalia>
<testoErroreAnomalia>
Impossibile verificare la validita' del comune di nascita per la presenza di piu' occorrenze
</testoErroreAnomalia>
</anomalie>

```
In fase di registrazione dell’iscrizione, ho selezionato il comune di nascita MONZA (1938-2009) corrispondente all’ID da tabella Comuni 19243. Ho verificato che nella richiesta è riportato il codice Istat che però, in molti casi, non risulta essere un dato univoco.

```
<luogoNascita>
<comune>
<nomeComune>MONZA</nomeComune>
<codiceIstat>015149</codiceIstat>
<siglaProvinciaIstat>MI</siglaProvinciaIstat>
</comune>
</luogoNascita>
```

Sarebbe possibile comprendere nella richiesta anche l’ID? Si potrebbero evitare anomalie come quella ricevuta nella risposta che di fatto non possono né devono essere sanate.  
Grazie, 
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Si tratta di un errore. Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
Può riprovare e darci un riscontro?

**Comment by VBocchinoTO** [comment]
Buongiorno, ho provato un'iscrizione e una mutazione: il problema sembra effettivamente risolto. Grazie, saluti.
