### ISSUE TITLE
E- Service dormancy checks

### ISSUE THREAD

**Issue by BrandonSaliba** [italia/anpr#4600]
Hello,

I am writing in relation to the ANPR access in relation to the Dormancy checks required by IVASS.  We obtained access to the PDND tool, however we are not managing to create the e-service, can you kindly guide us on the matter, how we can create the e-service to be able to upload and receive the data required to complete the dormancy checks?

Thanks
Brandon

**Comment by afrontera85** [comment]
Hello, 
we can only give you technical support for the e-service call, providing you an example client that you can find in the issue #4488

**Comment by BrandonSaliba** [comment]
Hello we are trying to use the c019 service for the dormancy checks, we arrived at finalita stage, we need to create the e-client and upload the key, but we are not understanding how to do this to be able to complete the checks.  Can you kindly instruct us?

Thanks
Brandon

**Comment by afrontera85** [comment]
Hello!
You have to follow the documentation on PDND interoperability. 
Then use the client provided by us to call the e-service (#4488)
