### ISSUE TITLE
Mancanza certificati_ Cittadino residente estero AIRE 

### ISSUE THREAD

**Issue by SamyAhmed95** [italia/anpr#4601]
Salve, Sono un cittadino residente all'estero e ho appena creato il mio SPID.
L'ANPR putroppo non presenta tutti i 14 certificati scaricabili online ma solo 3.
Avrei bisogno del certificato di stato libero. Come posso ottenerlo oppure come posso vedere tutti i certificati mancanti?
Grazie
Samy

**Comment by ncapozzi** [comment]
Buonasera, per il certificato di stato libero deve rivolgersi al comune di iscrizione AIRE. 
In generale per i cittadini AIRE possono essere richiesti i seguenti certificati
•	residenza;
•       stato di famiglia; 
•       nascita se avvenuta in Italia;
•       cittadinanza;
In generale si producono tutti i certificati se l’oggetto della certificazione è antecedente alla data di espatrio e se il Comune ha trasmesso i dati in ANPR.
