### ISSUE TITLE
URGENTE - ABILITAZIONE NUOVO INDIRIZZO IP - COMUNE DI FANO

### ISSUE THREAD

**Issue by LETSIM22** [italia/anpr#4603]
Si richiede URGENTEENTE l'abilitazione dell'Indirizzo IP nuovo 217.61.50.168 per il comune di FANO
Attualmente il comune è TUTTO Bloccato ed impossibilitato a Lavorare
Potete verificare ed abilitare?
Grazie

Letizia Simoncini: 0721 887236

Ced :334 6047711

**Comment by mttfranci** [comment]
Salve, ora dovrebbe essere a posto.

Saluti

Assistenza ANPR
