### ISSUE TITLE
Passaggio di stato in errore - pratica n. 28796493

### ISSUE THREAD

**Issue by anprpa** [italia/anpr#4607]
Buongiorno, c'è una pratica per la quale non riusciamo a fare il passaggio di stato.

Pratica ANPR 28796493
La pratica risulta nello stato 'aperta' e la richiesta è di passarla a "in lavorazione" (e successivamente in "accolta con riserva").
Questa la risposta ottenuta:
EN148 Errore nell'impostazione dello stato/proroga pratica. Esito: 12003
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-07-30 09:58:08 , idOperazioneANPR 1889264171

Ivana Ragni - SISPI - Comune di Palermo

**Comment by gppbarone** [comment]
Buonasera, potete riprovare la lavorazione della pratica?
Grazie

**Comment by anprpa** [comment]
Problema risolto.
Grazie

Cordiali saluti

Ivana Ragni



*-------------------------------------------------------------------------------*

*Dott.ssa Ivana Ragni*

*SISPI - SISTEMA PALERMO INNOVAZIONE SPA*

*Servizi alle Persone*

*tel. 0916319889*

*cell. 3347177809*



*-------------------------------------------------------------------------------*

*Nota di riservatezza**:*

*Ai sensi dell’art. 13 del Regolamento 2016/679/UE La informiamo che la
presente e-mail proviene da Sispi S.p.A. e s’intende inviata per scopi
lavorativi. Per tale ragione non è possibile garantire che, rispondendo
alla stessa, il contenuto venga visualizzato esclusivamente dal soggetto
cui è indirizzata la risposta. Si precisa che le informazioni contenute in
questo messaggio sono confidenziali, riservate e a uso esclusivo del
destinatario. Qualora lo stesso Le fosse pervenuto per errore, La preghiamo
di eliminarlo immediatamente senza farne uso ulteriore dandocene,
gentilmente, comunicazione. **Grazie.*



*Pursuant to Article 13 of the Regulation (EU) 2016/679, we inform you that
the hereby e-mail comes from Sispi S.p.A. and is intended to be sent for
working purposes. For this reason it’s not possible to guarantee that, by
answering to it, the content will be only shown to the individual towards
it’s addressed. We specify that the information contained in this message
are confidential, privileged and for the exclusive use of the addressee. If
you have received this e-mail message in error, please delete it
immediately without using it any further and kindly notify us. **Thank you.*


Il giorno mar 30 lug 2024 alle ore 16:51 gppbarone ***@***.***>
ha scritto:

**Comment by anprpa** [comment]
Buongiorno, la richiesta 28796493 già oggetto della issue 4607 deve essere
passata allo stato "accolta definitivamente"  ma non riusciamo a farlo.

Cordiali saluti

Ivana Ragni



*-------------------------------------------------------------------------------*

*Dott.ssa Ivana Ragni*

*SISPI - SISTEMA PALERMO INNOVAZIONE SPA*

*Servizi alle Persone*

*tel. 0916319889*

*cell. 3347177809*



*-------------------------------------------------------------------------------*

*Nota di riservatezza**:*

*Ai sensi dell’art. 13 del Regolamento 2016/679/UE La informiamo che la
presente e-mail proviene da Sispi S.p.A. e s’intende inviata per scopi
lavorativi. Per tale ragione non è possibile garantire che, rispondendo
alla stessa, il contenuto venga visualizzato esclusivamente dal soggetto
cui è indirizzata la risposta. Si precisa che le informazioni contenute in
questo messaggio sono confidenziali, riservate e a uso esclusivo del
destinatario. Qualora lo stesso Le fosse pervenuto per errore, La preghiamo
di eliminarlo immediatamente senza farne uso ulteriore dandocene,
gentilmente, comunicazione. **Grazie.*



*Pursuant to Article 13 of the Regulation (EU) 2016/679, we inform you that
the hereby e-mail comes from Sispi S.p.A. and is intended to be sent for
working purposes. For this reason it’s not possible to guarantee that, by
answering to it, the content will be only shown to the individual towards
it’s addressed. We specify that the information contained in this message
are confidential, privileged and for the exclusive use of the addressee. If
you have received this e-mail message in error, please delete it
immediately without using it any further and kindly notify us. **Thank you.*


Il giorno mar 30 lug 2024 alle ore 16:51 gppbarone ***@***.***>
ha scritto:
