### ISSUE TITLE
Comune di Nissoria (EN) - Errore di comunicazione con ANPR

### ISSUE THREAD

**Issue by macrosis-it** [italia/anpr#4608]
Gentili sistemisti,
   da qualche giorno tutte le operazioni relative all'ANPR che tentiamo di eseguire dall'interno dell'applicazione Maggioli Sicr@web hanno esito negativo a causa di un "Errore di comunicazione con ANPR". Dobbiamo precisare che avendo recentemente cambiato fornitore di connettività, abbiamo provveduto ad aggiungere i relativi IPv4 al relativo elenco in dp.anpr.interno.it/com nella pagina "Amministrazione". Tuttavia, poiché non sono ancora comparsi gli asterischi accanto ai nuovi indirizzi, stiamo continuando a indirizzare tutto il traffico tramite il vecchio fornitore, che rimarrà attivo ancora per un breve periodo. Ciò nonostante, la comunicazione con ANPR continua a fallire. In calce alla presente riportiamo schematicamente alcune informazioni che poitrebbero esservi d'aiuto nella diagnosi e soluzione del problema.
   In caso di dubbi o richieste di carattere tecnico, Vi preghiamo di contattarci al numero telefonico 091-7487080 oppure all'e-mail assistenza@macrosis.it. Per ogni altra informazione o prova di funzionamento, Vi preghiamo invece di contattare direttamente il servizio demografico dell'Ente al numero 0935-615026 - anagrafe@comune.nissoria.en.it (Sig.ra Gabriella Cuva o altro collega di turno mercoledì 9:00-12:00, 15:00-17:00; lunedì e giovedì 15:00-17:00).
   Cordiali saluti,

Luigi Casella - Macrosis SRL per conto del Comune di Nissoria (EN)
 

**Vecchio fornitore di connettività** (in via di dismissione, transitoriamente attivo)
`Tiscali SPA`
`82.85.33.56/29 (dal .57 al .62)`

**Nuovo fornitore di connettività**
`Vianova SPA`
`144.48.195.64/29   (dal .65 al .70)`

**Comment by Leonforte** [comment]
Salve, il problema dovrebbe essere stato risolto, potete riprovare dal 144... ? grazie
