### ISSUE TITLE
ws [5001] - Variazione di residenza intera famiglia da comune subentrato

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#461]
Buon giorno,
abbiamo effettuato tempo addietro, un test di una variazione di residenza di una famiglia proveniente da un comune subentrato, con il ws in oggetto, andata a buon fine (id operazione comune 389); successivamente avevamo provveduto all'annullamento della mutazione con il ws 5012 e anche questa operazione è stata completata con successo (id operazione comune 400).
Oggi abbiamo ripetuto il test, sulla stessa famiglia (composta da un solo individuo), proveniente sempre dallo stesso comune subentrato, ma otteniamo in risposta l'errore EF002 (Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata).
Effettuando una consultazione, però, tale famiglia risulta presente in ANPR; ho poi confrontato la request prodotta oggi con quella effettuata con successo a suo tempo e i dati inviati per la famiglia, in particolare l'id famiglia ANPR, sono gli stessi, quindi non capiamo il perchè del messaggio di errore.
L'id operazione comune è il 3627, il test è stato effettuato in data 14/12/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by frmariani** [comment]
può riprovare

**Comment by Amucciarelli74** [comment]
Salve,
la mutazione adesso è andata a buon fine; abbiamo ottenuto però nella risposta il warning EN395 (per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza), ma gli unici blocchi valorizzati nella request sono quelli obbligatori, 'famigliaConvivenza' e 'residenzaFamigliaConvivenza'.
L'id operazione comune è il 3670, il test è stato effettuato in data 14/12/2017, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by frmariani** [comment]
All’interno degli oggetti obbligatori ci sono dei tag opzionali valorizzati (famiglia Aire, data origine famiglia) sui quali non verranno effettuati controlli :  il warning serve soltanto ad avvisare l’utente che, nel caso fossero diversi da quelli presenti in ANPR,  non verranno aggiornati.
