### ISSUE TITLE
Errore interrogazione ANPR WEBSERVICE 3002

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4610]
COMUNE DI MARANO DI NAPOLI 

Buongiorno, 

Il comune in oggetto non riesce ad interrogare il seguente individuo:

IDENTIFICATIVO: JD51093F5
ID ANRP: 92264575
COMUNE DI RESIDENZA: CASAPESENNA
ID OPERAZIONE COMUNE REQUEST:  <idOperazioneANPR>1891952750</idOperazioneANPR>

Dal nostro gestionale non riusciamo ad avere una response valida in quanto è presente il seguente tag:

```
<documento>
<xop:Include href="cid:a287257c15a134d0e7333b3ae8eee6b6f84437dd54e09a28@apache.org" xmlns:xop="http://www.w3.org/2004/08/xop/include" />
</documento>
```

La validazione dell' XML tramite schema XSD restituisce il seguente errore:

```
This file is not valid: 

Element 'documento' is based on a simple type . It cannnot contain another element.
```

L'errore riscontrato dal gestionale é:

`System.ServiceModel.ProtocolException: There is a problem with the XML that was received from the network. See inner exception for more details.`

`System.Xml.XmlException: The data at the root level is invalid. Line 2, position 3.
`

**Comment by azabatta** [comment]
Buonasera, 
ci scusiamo per il ritardo della risposta. 
Abbiamo verificato la risposta inviata dal sistema e ci risulta validata. L'unica particolarità di questa consultazione è la presenza del contratto di convivenza in allegato (oltre ai dati della convivenza stessa).
