### ISSUE TITLE
CATALOGO E SERVICE

### ISSUE THREAD

**Issue by Sara150674** [italia/anpr#4611]
Buon pomeriggio,
ho completato la procedura di adesione ma quando vado al catalogo e -  service non trovo né l'Ente erogatore ( MINISTERO DELL'INTERNO ) né il servizio per l'accertamento anagrafico.

**Comment by azabatta** [comment]
Buonasera, 
si riferisce all'accesso ai dati di ANPR dalla PDND?  I servizi sono pubblicati sia in ambiente di colludo che di esercizio ed hanno come ente erogatore il Ministero dell'Interno. 
Se ha difficoltà nella ricerca deve rivolgersi al servizio di assistenza di PagoPA:
https://github.com/pagopa/pdnd-interop-frontend/issues
Saluti

**Comment by Sara150674** [comment]
SI ma quando mi autentico non mi fa entrare nell’ambiente di collaudo, solo in attestazione

 

Da: azabatta ***@***.*** 
Inviato: martedì 6 agosto 2024 14:57
A: italia/anpr
Cc: Sara150674; Author
Oggetto: Re: [italia/anpr] CATALOGO E SERVICE (Issue #4611)

 

Buonasera,
si riferisce all'accesso ai dati di ANPR dalla PDND? I servizi sono pubblicati sia in ambiente di colludo che di esercizio ed hanno come ente erogatore il Ministero dell'Interno.
Se ha difficoltà nella ricerca deve rivolgersi al servizio di assistenza di PagoPA:
https://github.com/pagopa/pdnd-interop-frontend/issues
Saluti

**Comment by azabatta** [comment]
Sta utilizzando un canale di comunicazione errato, non siamo noi a gestire la PDND. Deve rivolgersi al servizio di assistenza di PAgoPA.
Saluti
