### ISSUE TITLE
iscrizione dall'estero - AEE95 Operazione non effettuabile

### ISSUE THREAD

**Issue by vix-db** [italia/anpr#4613]
Comune di Mirabella Eclano,
durante l'iscrizione dall'estero di un nominativo nato in MAROCCO riceviamo questo errore:

AEE95	E	Operazione non effettuabile
EN527	E	Informazioni sull'operazione da fornire in caso di assistenza : data 2024-08-01 17:50:43 , idOperazioneANPR 1894534919

codice fiscale  	 FTHSMR76A58Z330E

**Comment by ncapozzi** [comment]
Buonasera,
nell'operazione 1002 non dovete richiedere l'attribuzione del CF visto che la cittadina già lo possiede. Indicatelo nelle generalità e richiedete la validazione.
N.B. si raccomanda sempre di non indicare il CF o i dati anagrafici dei cittadini nelle issue.

**Comment by vix-db** [comment]
...in realtà effettuando una ricerca del codice fiscale tramite "Risoluzione disallineamenti con AE" otteniamo:
Soggetto non trovato per i criteri indicati o già validato o esiste un'operazione in sospeso per il soggetto

...ecco perché ci siamo permessi di indicare il CF nel ticket.
