### ISSUE TITLE
IMMIGRAZIONI SEGNALAZIONE IMPORTANTE

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr#4614]
Buongiorno,
COMUNE DI CASERTA
Capita frequentemente di non poter chiudere operazioni di immigrazione poiché -
Operazione non consentita: per il soggetto esiste un procedimento aperto dal comune. ....................... con numero pratica ANPR: XXXXXXXXX  
I comuni interessati vengono invitati alla chiusura delle pratiche a mezzo PEC e ripetuti solleciti telefonici.
E' UN PROBLEMA DA RISOLVERE CON ESTREMA URGENZA. GRAVI IMPLICAZIONI ANCHE SU GESTIONE DATI ELETTORALI NON POTENDO ISCRIVERE IL CITTADINO.
GRAZIE

**Comment by azabatta** [comment]
Buonasera, 
la questione non è di carattere tecnico.
Il blocco è stato inserito anni fa recependo le risultanze di un tavolo di lavoro cui avevano partecipato rappresentati dei comuni.
Per rimuovere il controllo non possiamo agire in autonomia ma dobbiamo essere autorizzati.
La segnalazione deve essere inoltrata al Ministero dell'Interno - Direzione Centrale Servizi Demografici.
Saluti
