### ISSUE TITLE
Mancata ricezione notifiche tramite ws

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#4615]
Buongiorno, il comune 086003, in ambiente di produzione, non riceve le notifiche attraverso ws esposto per la ricezione, dal alcune verifiche effettuati l'endpoint sembrerebbe essere corretto e raggiungibile.
Dal web app di ANPR la funzione di test del servizio di notifica non è attiva, quindi non abbiamo modo di capire la causa della mancata ricezione, potreste darci delle indicazioni in merito.

Grazie mille.
GolemNet.

**Comment by azabatta** [comment]
Buonasera, 
l'endpoint risulta attivo ma le notifiche vanno in errore dopo 5 tentativi di invio. Gli errori sono presenti dal 24/07/2024  ore 11:35:01. 
E' necessario controllare il servizio di accoglienza per capire che errore prende.
Saluti
