### ISSUE TITLE
[C020 - C021] 404 Unknown API Request

### ISSUE THREAD

**Issue by dilaurof-csi** [italia/anpr#4617]
Salve,

stiamo provando a invocare in prod https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1/status e https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C021-servizioAccertamentoStatoFamiglia/v1/status, ma, in entrambi i casi, stiamo ricevendo un 404.

Di seguito i dettagli:
{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "65aed33c66b0cb6a18b4972f"
}

{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "0cc0f75f66b0cbd1019d2313"
}

Ho già letto su altre issues che il 404 può dipendere dalla mancanza dell' header Authorization, dalla non validità del voucher o dal metodo sbagliato.

Confermo che il voucher viene correttamente inserito nell'header richiesto e che è generato tramite i dati presenti sulla PDND.

**Comment by afrontera85** [comment]
Salve, vi consiglio di fare le prove in ambiente di validazione.
Le url di validazione sono queste:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/status
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C021-servizioAccertamentoStatoFamiglia/v1/status
e sono in GET.
Come potete vedere nell'url va messo MinInternoPortaANPR-PDND e non MinInternoPortaANPR

**Comment by dilaurof-csi** [comment]
Salve,

avevamo già fatto i test in validazione ed erano andati a buon fine.

Effettivamente, aggiungendo anche in prod -PDND, riusciamo a invocare correttamente le api.

Perchè l'uri si differenzia dall'aud per quel -PDND ?

Questo crea spesso dei misunderstandings con in nostri clienti.

**Comment by afrontera85** [comment]
Le specifiche da seguire sono queste, la differenza tra uri e aud non la fa solo il -PDND
L'url è :
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002
L'aud è :
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1
