### ISSUE TITLE
CERTIFICAZIONE ON-LINE COMUNE SUBENTRATO/IL RICHIEDENTE CERTIFICATO NON VIENE REGISTRATO

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#462]
Comune di Spinea - Comune subentrato
Buongiorno, 
abbiamo attivato il portale di accesso ai servizi on line per i cittadini e tra questi è prevista la certificazione anagrafica da ANPR dedicata a due tipologie di utenza che accede per ora  con  firma digitale o "tessera sanitaria" :
1) i residenti che hanno accesso anche ai loro dati anagrafici e che possono ottenere una serie di certificazioni che  riguardano loro e la loro famiglia.
2) i terzi che possono interrogare e certificare la residenza e lo stato famiglia di chiunque sia residente nel nostro comune come prescritto dalla norma.
La norma prevede che i richiedenti, tutti, debbano essere identificati e ne resti traccia , infatti l'identificazione è obbligatoria anche per i certificati emessi allo sportello e funziona.
Da portale invece non si riesce ad ottenere che sia "visibile" la persona che richiede il certificato.
Sembra che siamo tra i primi a dare questo servizio ai cittadini tra i comuni subentrati....
chiedo per cortesia di sapere quali sono i problemi, ma soprattutto di risolverli.
Grazie dell'attenzione.
Raffaella

**Comment by gcarbonin** [comment]
Non mi è chiaro il problema: forse sulla stampa del certificato si dovrebbe riportare chi lo ha richiesto?

**Comment by Raffive** [comment]
La norma dice: Art. 33 dpr 223/98 Certificati anagrafici 
1. Fatti salvi i divieti di comunicazione di dati, stabiliti da
speciali disposizioni di legge, e quanto previsto dall'articolo 35,
l'ufficiale di anagrafe rilascia a chiunque ne faccia richiesta,
previa identificazione, i certificati concernenti la residenza, lo
stato di famiglia degli iscritti nell'anagrafe nazionale della
popolazione residente, nonche' ogni altra informazione ivi contenuta.
2. Al rilascio di cui al comma 1 provvedono anche gli ufficiali
d'anagrafe di comuni diversi da quello in cui risiede la persona cui
i certificati si riferiscono.
3. Le certificazioni anagrafiche hanno validita' di tre mesi dalla
data di rilascio.
Quindi trattandosi di accesso ai dati “informatico” l’identificazione non sarà un riconoscimento visivo della persona, e la registrazione di un documento (numero ecc.) ma una identificazione “informatica”, digitale? Non so come si chiama.
Le ho inviato sulla sua mail i dettagli
 abbiamo provato il giorno dopo il subentro e i giorni successivi:
sia con credenziali di accesso tessera sanitaria abilitata con PIN che firma digitale
la s. house mi conferma che chiedete invece un numero di documento d'identità..
Grazie
Raffaella

**Comment by gcarbonin** [comment]
In attesa di definizione dell'intervento da effettuare

**Comment by gcarbonin** [comment]
Chiusa in quanto lo stesso argomento è trattato nella issue #708
