### ISSUE TITLE
non è stato possibile accedere al servizio - ANPR - Servizi anagrafici

### ISSUE THREAD

**Issue by Mauricio-Nazario** [italia/anpr#4621]
Il comune ha riferito che non vi è alcun errore nella registrazione.

Non riesco ad accedere a Servizi anagrafici - ANPR con SPID 
Potresti aiutarmi?

Maurício Nazario do Carmo Sant' Anna, nato a Sorocaba - Brasile. Prime sei cifre del mio codice fiscale: NZRMRC
Comune: Loria
Grazie.

**Comment by ncapozzi** [comment]
Buongiorno, come le abbiamo suggerito nella issue #4544 deve rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e allineato con Agenzia delle Entrate. Probabilmente la prima volta non hanno verificato la validazione del codice fiscale in ANPR.

**Comment by Mauricio-Nazario** [comment]
> Buongiorno, come le abbiamo suggerito nella issue #4544 deve rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e allineato con Agenzia delle Entrate. Probabilmente la prima volta non hanno verificato la validazione del codice fiscale in ANPR.

Ho contattato il comune nel 2023 e nel 2024, hanno detto che non hanno problemi con la mia registrazione

**Comment by ncapozzi** [comment]
Qual'è il Comune?

**Comment by Mauricio-Nazario** [comment]
Loria

Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em seg., 12 12e ago. 12e 2024 às 14:24, ***@***.***> escreveu:   


Qual'è il Comune?

**Comment by ncapozzi** [comment]
Mi dispiace ma il Comune non le ha riferito una informazione corretta, deve tornare al Comune e chiedere una verifica del codice fiscale in ANPR. In caso il Comune può richiedere assistenza su come procedere tramite i canali loro riservati.

**Comment by Mauricio-Nazario** [comment]
Ok, grazie mille

Yahoo Mail: Busque, organize e aumente sua produtividade 
 
  Em seg., 12 12e ago. 12e 2024 às 14:48, ***@***.***> escreveu:   


Mi dispiace ma il Comune non le ha riferito una informazione corretta, deve tornare al Comune e chiedere una verifica del codice fiscale in ANPR. In caso il Comune può richiedere assistenza su come procedere tramite i canali loro riservati.
