### ISSUE TITLE
ANPR - Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by dvillena15** [italia/anpr#4622]
Buongiorno,

Vorrei fare il cambio di residenza a Milano ma appare questo messaggio di errore:

"Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica."

https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

Codice fiscale: VLLDGI_______

Cosa devo fare?

Grazie mille per l'aiuto.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
