### ISSUE TITLE
issue with communication

### ISSUE THREAD

**Issue by Alexei-Dev** [italia/anpr#4623]
Hi,

We have this problem now when trying to access c019 from the java client,

we are getting this response:
GovWay-Transaction-ID: d6e854af-5a23-11ef-88d8-005056ae1884
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"d6e854af-5a23-11ef-88d8-005056ae1884"}

using:
baseurlapi=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

audTokenAgidJwtSignature=https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1

Please let us know what we could be doing incorrectly.

**Comment by azabatta** [comment]
Good evening, 
could you try again and give us a feedback? 
Greetings

**Comment by Alexei-Dev** [comment]
Hello,
Now I got a different error;

GovWay-Transaction-ID: ec6abfe8-5e2e-11ef-8556-005056ae1884
{"listaErrori":[{"codiceErroreAnomalia":"500","testoErroreAnomalia":"Internal Error","tipoErroreAnomalia":"E"}]}

**Comment by azabatta** [comment]
Good morning, your request is set badly so you get an application fault.
Download the documentation attached to the eservice C019 on PDND to understand how to enhance the fields. For example codiceFiscale is  alternative to idANPR or to Generalita of a citizen. The use case field must be set with the code of the eservice invoked therefore with 'C019'.  
In the documentation there is a list of usable test cases. 
Below is a possible example of a request:

{
  "idOperazioneClient" : "20240820-08:23:11:235",
  "criteriRicerca" : {
    "codiceFiscale" : "QRTSGT90A01H501B"
  },
  "datiRichiesta" : {
    "dataRiferimentoRichiesta" : "2024-08-20",
    "motivoRichiesta" : "Test use case C019",
    "casoUso" : "C019"
  }
}

**Comment by Alexei-Dev** [comment]
Hello, thank for your help on this, we were able to get this result, can you confirm it is a good result?

`{"listaSoggetti":{"datiSoggetto":[{"generalita":{"codiceFiscale":{"codFiscale":"QRTSGT90A01H501B","validitaCF":"1"},"cognome":"QUARTO","dataNascita":"1990-01-01","idSchedaSoggettoANPR":"2760295","luogoNascita":{"comune":{"codiceIstat":"058091","nomeComune":"ROMA","siglaProvinciaIstat":"RM"}},"nome":"SOGGETTO","sesso":"M"},"identificativi":{"idANPR":"ZR13449T3"},"infoSoggettoEnte":[{"chiave":"Verifica esistenza in vita","id":"1003","valore":"S"}]}]},"idOperazioneANPR":"73265668","listaAnomalie":[{"codiceErroreAnomalia":"EN148","testoErroreAnomalia":"Il D.M. Ministero dell'Interno 3 marzo 2023 (art.3 comma 3) prevede l'accesso ad ANPR esclusivamente con identificativo unico nazionale (ID ANPR), si  rappresenta pertanto l'urgenza di provvedere all'integrazione dei propri sistemi.","tipoErroreAnomalia":"W"}]}`


Is only this codiceFiscale accepted? when we try with others we do not get a successful result, instead an error:
```
GovWay-Transaction-ID: 5c22484d-5eca-11ef-942b-005056ae5232
{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"5c22484d-5eca-11ef-942b-005056ae5232"}
```
