### ISSUE TITLE
C030 InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by LDAV** [italia/anpr#4624]
buongiorno,
avremmo bisogno di supporto per il seguente errore in fase di collaudo:

La richiesta è la seguente:
{"idOperazioneClient":"C030_01","criteriRicerca":{"codiceFiscale":"SGGPRM60A01H501A"},"datiRichiesta":{"dataRiferimentoRichiesta":"2024-08-19","motivoRichiesta":"1","casoUso":"C030"}}

Response:
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"f8425001-5df9-11ef-8b8a-005056ae5232"}

kid: 0zYo7kzBX7P8dXlSYIzjFb4U2b8tgI-xDiBRUvvUN5g
clientId: cc32c99f-5695-48cc-8c7c-2244dc188950
purposeId: 76ffadac-0f07-4527-b431-ee2e300d5a55

La richiesta del voucher è stata verificata con il tool di debug.
Grazie

**Comment by azabatta** [comment]
Buonasera, 
cortesemente potete riprovare e darci un riscontro? 
Grazie

**Comment by LDAV** [comment]
identico problema.
Questa è la sequenza:

agidTrackingEvidence:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjB6WW83a3pCWDdQOGRYbFNZSXpqRmI0VTJiOHRnSS14RGlCUlV2dlVONWcifQ.eyJqdGkiOiI3NTUwMzI4NS0wMjBjLTRmZDQtODhhYy0zZTY4NThkOTY4MGIiLCJwdXJwb3NlSWQiOiI3NmZmYWRhYy0wZjA3LTQ1MjctYjQzMS1lZTJlMzAwZDVhNTUiLCJkbm9uY2UiOiIxMjM0NTY3ODkwMTIzIiwidXNlcklEIjoiQ1ROTE1SNjFUMjVGMTA0VCIsInVzZXJMb2NhdGlvbiI6IjM3LjE2MS4yMzIuNDMiLCJMb0EiOiJMT0EzIiwiYXVkIjoiYXV0aC51YXQuaW50ZXJvcC5wYWdvcGEuaXQvY2xpZW50LWFzc2VydGlvbiIsImlzcyI6ImNjMzJjOTlmLTU2OTUtNDhjYy04YzdjLTIyNDRkYzE4ODk1MCIsInN1YiI6ImNjMzJjOTlmLTU2OTUtNDhjYy04YzdjLTIyNDRkYzE4ODk1MCIsImlhdCI6MTcyNDA3OTM1MiwibmJmIjoxNzI0MDc5MzUyLCJleHAiOjE3MjQxMjI1NTJ9.PI3Ndhf613wKhC1E2F155_zNHWyLpq9SvQ2LmgXcCOqu9_x5vbtNFxaE_KbSxXOeciLWkLH7RODSgM3lUeKgr_Ku4yPT59Ew6yv2avDULVETh4qkVICXIuxjvFfBzkeiUpF0miEG8yeaKud6GvKRT7Le_Wi2V5AMEbYjL0y03Gi5TmVvRhnXBEf0q8c-3Ofu3MEHbeqklAac_uXfWB1sT78_KgZBLk9NgPXndFXoCuczQZKqv3vfDK4DmRteSSCOs0n4c-O_oJz7KH3XrILHpMlnUBNJUAxBhh2JwEC7V6IIeuCOKvOWoELxCmUHZivacxot4gk-5f11GRy7uG8lDQ

body:
{"idOperazioneClient":"C030_01","criteriRicerca":{"codiceFiscale":"SGGPRM60A01H501A"},"datiRichiesta":{"dataRiferimentoRichiesta":"2024-08-19","motivoRichiesta":"1","casoUso":"C030"}}

bearerToken:
eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJjYzMyYzk5Zi01Njk1LTQ4Y2MtOGM3Yy0yMjQ0ZGMxODg5NTAiLCJuYmYiOjE3MjQwNzkzODksImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6ImQyYWFkYzQ5NDc2MTU4MTVlNTY1YzQ0ZGZlOWUzZTUwNzYwMTcyMmYyMjFkYzdiZjVlNmFhZDdlMjUyNjY3MmIifSwicHVycG9zZUlkIjoiNzZmZmFkYWMtMGYwNy00NTI3LWI0MzEtZWUyZTMwMGQ1YTU1IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI0MDc5OTg5LCJpYXQiOjE3MjQwNzkzODksImNsaWVudF9pZCI6ImNjMzJjOTlmLTU2OTUtNDhjYy04YzdjLTIyNDRkYzE4ODk1MCIsImp0aSI6ImYwYTMwMzM2LTBiMjAtNDNlNC1iZWJjLTQ1ZTY5ZTZjNzgyNyJ9.n7z5UOqpuxxKil8pTaDgGpcUW3hIewnxuaJeXjVANarOYn-x0pXNT-fLJm3IxtIosqTVDn1WuQBCzS-CO0gKM2KqO4FSH0gMNmqKsC1quEYfx8OJ4qPiyOYIxsZy8hQ4r6SizMcmXtnErpwNpe1jv3COSiskhh59-ZaS_tvTisamz3Bl6XDEY_G8ekh302nNKIbzOucu39jF_HIrINWWOfZ0kZj45UGTfNdDuF3YzdmyX8io2xaguPkN0m2D76NknaheMckKWB4EO51l8CZeV9Ut6eVw-itAVRHi_ZeBqknRmN9QXuR2RqHlqCMjltYjCT8G33L8svccmXzJedyaEQ

agidSignature;
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjB6WW83a3pCWDdQOGRYbFNZSXpqRmI0VTJiOHRnSS14RGlCUlV2dlVONWcifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFItUERORC9DMDMwLXNlcnZpemlvQWNjZXJ0YW1lbnRvSWRVbmljb05hemlvbmFsZS92MSIsImlzcyI6ImNjMzJjOTlmLTU2OTUtNDhjYy04YzdjLTIyNDRkYzE4ODk1MCIsInN1YiI6ImNjMzJjOTlmLTU2OTUtNDhjYy04YzdjLTIyNDRkYzE4ODk1MCIsImlhdCI6MTcyNDA3OTM1MywiZXhwIjoxNzI0MTIyNTUzLCJuYmYiOjE3MjQwNzkzNTMsImp0aSI6Ijc1NTAzMjg1LTAyMGMtNGZkNC04OGFjLTNlNjg1OGQ5NjgwYiIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PS9zWVhSNlVZU3Jha241MlBRZGQvaTBiU0hyYWNpaGZOeTF5SzFMMmxNSDA9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dfQ.Me_uGYRex5jTDkU9uZ_UkMd8K41JB6qgGHYQkY_j_47tRT0ts3tkQV6kLjnhdkWaTwoxtHsyHzMEpNnt7D7BvRij01D5lNlP1vqynu6K2nMP_k1V8dMXlzlte1ZzpaGuAQQtWbHVvpIraE89BveL21K0DO-HiULWlY-JkEyYAvWHMkgsiqiGjlx_9N3Ev3s5X_NMLY5eD0VVuJz1_eTrQ0MsBkCvNWExQachwU-_X2xmLVVaE_0z2gSyAz7dn3YSppqdWRByzOD9EdPgE6kJrClGV-sMBrPD1xDzd4OCNnpoON2GbOBliY5jqTh6Isve1G2xC88oO7cAlZFVVVwbvw

Error: API responded with code 400: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"e398d94d-5e34-11ef-8556-005056ae1884"}

**Comment by azabatta** [comment]
Buonasera, il codice di errore è lo stesso ma il dettaglio dell'errore riscontrato è diverso rispetto al precedente.
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
- Token contenente un claim 'aud' non valido
-  [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by LDAV** [comment]
sì. il problema era l'aud non corretto
Grazie
