### ISSUE TITLE
Codice errore anomalia 999 su servizio C024 accertamento automatico paternità

### ISSUE THREAD

**Issue by leoAndre67** [italia/anpr#4625]
Buongiorno,
una volta lanciato il webservice 024 la risposta che otteniamo è :

<html>
<body>

N. | codiceErroreAnomalia | testoErroreAnomalia | tipoErroreAnomalia | idOperazioneANPR
-- | -- | -- | -- | --
1 | 999 | Operazione non effettuabile | E | 1914932627

<br class="Apple-interchange-newline">
</body>
</html>

Come posso fare debug?
per questo servizio andiamo ad inserire IDANPR, e non mi sembra siano necessari altri dati in ingresso (confermate?)

Il collaudo è stato fatto il 19/8
Sono Andrea Cardillo e faccio parte del IT del Comune di Cinisello Balsamo

**Comment by azabatta** [comment]
Buonasera,
cortesemente potete riprovare e darci un riscontro?
Grazie

**Comment by leoAndre67** [comment]
Buongiorno, 
appena riprovato: funziona tutto. 

Inseriamo il codice fiscale della persona della quale si desidera accertare la paternità e dopo pochi istanti il webservice restituisce i dati del padre. 

Grazie mille 



Andrea Cardillo 
UO Innovazione Tecnologica 
Via XXV Aprile 4, 20092 Cinisello Balsamo 
Tel. 02 66023 333 
Cell. 334 1124795 
***@***.*** 
www.comune.cinisello-balsamo.mi.it 


Da: "azabatta" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "leoAndre67" ***@***.***>, "Author" ***@***.***> 
Inviato: Lunedì, 19 agosto 2024 16:12:26 
Oggetto: Re: [italia/anpr] Codice errore anomalia 999 su servizio C024 accertamento automatico paternità (Issue #4625) 





Buonasera, 
cortesemente potete riprovare e darci un riscontro? 
Grazie
