### ISSUE TITLE
URGENTE: SEGNALAZIONE DI CITTADINO DI IMPOSSIBILITA' DI FIRMARE IL REFERENDUM

### ISSUE THREAD

**Issue by raffaella30174** [italia/anpr#4626]
id anpr KP09549JU

Il signore è residente a Venezia  stava provando a firmare per un referendum sul sito del Ministero della Giustizia, non è riuscito a completare l'operazione in quanto appariva il seguente messaggio 'utente non trovato in anpr - per il tuo codice fiscale la piattaforma ha rilevato dei problemi - rivolgiti al tuo Comune per la risoluzione del problema'.
Chiede di ricevere assistenza.

Abbiamo verificato lato anagrafe tutto ok
abbiamo verificato lato elettorale tutto ok
non risultano a noi visibili disallineamenti con AE.

Si chiede di capire il motivo di tale messaggio per poter rispondere al cittadino e consentirgli di firmare il referendum in tempo utile.

Grazie

Raffaella 
Venezia

**Comment by frmariani** [comment]
Buongiorno Raffaella,
puoi comunicare al cittadino che può riprovare ad effettuare la sottoscrizione.
Grazie per la segnalazione.

**Comment by raffaella30174** [comment]
Grazie Francesca!
Vorrei sapere però se era un problema di anagrafe o solo informatico... giusto per capere cosa rispondere ad altre eventuali segnalazioni di cittadini.
Grazie!


Raffaella Campagnol

Area Servizi al Cittadino e Imprese e Qualità della Vita
Settore Servizi al Cittadino, Protocollo e Archivio Generale
Via Palazzo 8 - 30173 Venezia-Mestre
telefono 041 2746645
mail: ***@***.***
PEC: ***@***.***
info:  https://www.comune.venezia.it/it/content/anagrafe

________________________________
Da: frmariani ***@***.***>
Inviato: martedì 20 agosto 2024 09:37
A: italia/anpr ***@***.***>
Cc: Raffaella Campagnol ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] URGENTE: SEGNALAZIONE DI CITTADINO DI IMPOSSIBILITA' DI FIRMARE IL REFERENDUM (Issue #4626)


Buongiorno Raffaella,
puoi comunicare al cittadino che può riprovare ad effettuare la sottoscrizione.
Grazie per la segnalazione.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fanpr%2Fissues%2F4626%23issuecomment-2298175160&e=0a612e94&h=f2b846d4&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANRTFWXF2P2G2GIK64PMKJTZSLWZ5AVCNFSM6AAAAABMX7YNDWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJYGE3TKMJWGA&e=0a612e94&h=f066cebf&f=n&p=y>.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Le informazioni contenute nel presente messaggio ed i relativi allegati sono unicamente per i destinatari indicati e possono essere riservate ai sensi della vigente normativa. Ove non siate i destinatari di questo messaggio, l'eventuale diffusione, distribuzione e/o copiatura dei contenuti dello stesso e' proibita ai sensi della normativa applicabile. Se avete ricevuto questo messaggio per errore, siete pregati di informare il mittente immediatamente dell'accaduto e di cancellare il messaggio. Questo indirizzo di posta elettronica non e' un indirizzo di posta privato e percio' il suo utilizzo e' soggetto a regolamentazione.

**Comment by frmariani** [comment]
Si è trattato di un problema informatico random di accesso alla PDND.
In questi casi basta riprovare.
Grazie
