### ISSUE TITLE
Dati errati su c024 (accertamento paternità)

### ISSUE THREAD

**Issue by leoAndre67** [italia/anpr#4627]
Buongiorno,
segnalo che nel servizio 024 nel caso il padre abbia un doppio nome di battesimo al posto del cognome il webservice restituisce il primo nome di battesimo. 

Andrea Cardillo
Comune di Cinisello Balsamo, IT

**Comment by azabatta** [comment]
Buongiorno,
se il riferimento è lo stesso cittadino di ieri le rappresento che i dati sono stati inviati così in fase di subentro. Il servizio si limita a riportare quello che è presente in ANPR. 
Saluti
