### ISSUE TITLE
tentativo di inserimento pratica di immigraizone dall'estero, rende errore:Comunicazione con ANPR fallita, riprovare tra qualche minuto. Se l'errore persiste consultare l'assistenza tecnica. per maggiori informazioni consultare i dettagli di questo messaggio oppure il log del server.

### ISSUE THREAD

**Issue by AleMarky** [italia/anpr#4630]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by azabatta** [comment]
Nelle giornate del 20 e 21 agosto u.s. ci sono state delle criticità sui sistemi che hanno causato dei rallentamenti nelle ore di punta.
La problematica è stata risolta il 21 agosto intorno alle 11,45.
Ci scusiamo per i disagi.
Saluti
