### ISSUE TITLE
ANPR LENTO - WS in errore

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#4631]
Buongiorno,
si segnala che la WEBAPP è particolarmente lenta anche nelle consultazioni,  per caricare una scheda risponde dopo diversi minuti.
Questo rallentamento crea problemi anche con i ws che vanno in errore.
Si chiede celere riscontro.
Cordiali saluti
UpiTorino

**Comment by azabatta** [comment]
Nelle giornate del 20 e 21 agosto u.s. ci sono state delle criticità sui sistemi che hanno causato dei rallentamenti nelle ore di punta.
La problematica è stata risolta il 21 agosto intorno alle 11,45.
Ci scusiamo per i disagi.
Saluti
