### ISSUE TITLE
Errore - Richiesta certificato matrimonio

### ISSUE THREAD

**Issue by gio-ortolani** [italia/anpr#4634]
Buongiorno, 
ho bisogno di scaricare un certificato anagrafico di matrimonio, pero questa opzione non esiste in elenco: 
![image](https://github.com/user-attachments/assets/2c166f0d-91da-4354-b285-90665702fc1d)

Potete verificare il perché questa opzione non esiste? Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
l'elenco dei certificati che è possibile richiedere è visualizzato in base ai dati registrati in ANPR quindi se non vede quello di matrimonio i relativi dati non sono ancora presenti a sistema. Le suggeriamo di segnalare il problema direttamente al Comune di competenza.

Assistenza ANPR
