### ISSUE TITLE
CIE del 20/08/2024 non caricata in ANPR 

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#4635]
Buongiorno,
in data 20/08/2024 , quando si è verificato il fermo di ANPR, è stata emessa la CIE CA05543TG per la cittadina DUXGIO07P49E253S. Sul nostro gestionale è visibile, su ANPR invece risulta ancora la vecchia carta d'identità.
Grazie.
UPI Torino

**Comment by azabatta** [comment]
Buonasera, 
ad oggi i dati  risultano allineati.
Per queste problematiche si suggerisce di utilizzare il numero verde dell'assistenza 800.86.31.16. Inoltre su questo canale è opportuno non indicare in chiaro dati di un cittadino.
Saluti
