### ISSUE TITLE
Passaggio di stato in errore in pratiche online cambio residenza

### ISSUE THREAD

**Issue by anprpa** [italia/anpr#4636]
Buongiorno, ci sono 4 pratiche di cambi residenza online per le quali non riusciamo a fare il passaggio di stato.
n. 27431463 - 28994333 - 28879496 - 27848221

Pratica ANPR 27431463
La pratica risulta nello stato 'sospesa' e la richiesta è di passarla a 'annullata'. 
Questa la risposta ottenuta: 
La richiesta è in verifica o non convalidata. EN527
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-01-15 10:44:28 , idOperazioneANPR 1591731768

Pratica ANPR 28994333 
Il cambio stato 'in lavorazione' va in errore.
Questa la risposta ottenuta: 
Errore nell'impostazione dello stato/proroga pratica.  Esito: 12003
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-04-10 11:28:15 , idOperazioneANPR 1723332755

Pratica ANPR 28879496
Il cambio stato in 'accolta con riserva' è stato effettuato con esito positivo il 12/1/24 ,
ma la pratica risulta sempre 'in lavorazione'.

Data richiesta 12/01/2024 11:06:07
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>11835417</idOperazioneComune>
        <codMittente>082053</codMittente>
        <codDestinatario>ANPR05</codDestinatario>
        <operazioneRichiesta>P003</operazioneRichiesta>
        <dataOraRichiesta>2024-01-12T11:06:07.316+01:00</dataOraRichiesta>
        <tipoOperazione>V</tipoOperazione>
        <tipoInvio>PROD</tipoInvio>
        <nomeApplicativo>DEMOS</nomeApplicativo>
        <versioneApplicativo>NOVERSION</versioneApplicativo>
        <fornitoreApplicativo>Sispi</fornitoreApplicativo>
    </testataRichiesta>
    <criteriAggiornamento>
        <codiceRichiesta>28879496</codiceRichiesta>
        <idStatoRichiesta>12</idStatoRichiesta>
        <operatore>70772011</operatore>
    </criteriAggiornamento>
</ns2:RichiestaP003>

Data risposta 12/01/2024 11:13:29
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RispostaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <ns2:RispostaOKP003>
        <testataRisposta>
            <idOperazioneComune>11835417</idOperazioneComune>
            <codMittente>082053</codMittente>
            <codDestinatario>ANPR05</codDestinatario>
            <operazioneRichiesta>P003</operazioneRichiesta>
            <dataOraRichiesta>2024-01-12T11:06:07.316+01:00</dataOraRichiesta>
            <idOperazioneANPR>1588420196</idOperazioneANPR>
            <esitoOperazione>0000</esitoOperazione>
        </testataRisposta>
        <criteriRicerca>
            <codiceRichiesta>28879496</codiceRichiesta>
            <idStatoRichiesta>12</idStatoRichiesta>
            <operatore>70772011</operatore>
        </criteriRicerca>
        <esito>
            <codiceEsito>0</codiceEsito>
        </esito>
    </ns2:RispostaOKP003>
</ns2:RispostaP003>

Pratica ANPR 27848221
Il cambio stato in 'in lavorazione' è stato effettuato con esito positivo il 14/2/24 ,ma la pratica risulta sempre 'aperta'.

Data richiesta 14/02/2024 10:30:52
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>12037710</idOperazioneComune>
        <codMittente>082053</codMittente>
        <codDestinatario>ANPR05</codDestinatario>
        <operazioneRichiesta>P003</operazioneRichiesta>
        <dataOraRichiesta>2024-02-14T10:30:53.008+01:00</dataOraRichiesta>
        <tipoOperazione>V</tipoOperazione>
        <tipoInvio>PROD</tipoInvio>
        <nomeApplicativo>DEMOS</nomeApplicativo>
        <versioneApplicativo>NOVERSION</versioneApplicativo>
        <fornitoreApplicativo>Sispi</fornitoreApplicativo>
    </testataRichiesta>
    <criteriAggiornamento>
        <codiceRichiesta>27848221</codiceRichiesta>
        <idStatoRichiesta>3</idStatoRichiesta>
        <operatore>70755882</operatore>
    </criteriAggiornamento>
</ns2:RichiestaP003>

Data risposta  14/02/2024 10:37:09
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RispostaP003 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <ns2:RispostaOKP003>
        <testataRisposta>
            <idOperazioneComune>12037710</idOperazioneComune>
            <codMittente>082053</codMittente>
            <codDestinatario>ANPR05</codDestinatario>
            <operazioneRichiesta>P003</operazioneRichiesta>
            <dataOraRichiesta>2024-02-14T10:30:53.008+01:00</dataOraRichiesta>
            <idOperazioneANPR>1639556935</idOperazioneANPR>
            <esitoOperazione>0000</esitoOperazione>
        </testataRisposta>
        <criteriRicerca>
            <codiceRichiesta>27848221</codiceRichiesta>
            <idStatoRichiesta>3</idStatoRichiesta>
            <operatore>70755882</operatore>
        </criteriRicerca>
        <esito>
            <codiceEsito>0</codiceEsito>
        </esito>
    </ns2:RispostaOKP003>
</ns2:RispostaP003>

Ivana Ragni - SISPI - Comune di Palermo

**Comment by anprpa** [comment]
Non ha caricato bene gli xml. 
Li allego qui.
[richiesta 28879496.txt](https://github.com/user-attachments/files/16709740/richiesta.28879496.txt)
[richiesta 27848221.txt](https://github.com/user-attachments/files/16709742/richiesta.27848221.txt)

**Comment by ncapozzi** [comment]
Buonasera,
Pratica ANPR 27431463
La pratica risulta nello stato 'sospesa' e la richiesta è di passarla a 'annullata'. > Potete riprovare l'annullamento

Potete verificare per favore lo stato attuale delle altre pratiche?

**Comment by anprpa** [comment]
Le pratiche adesso risultano tutte negli stati corretti.
Grazie.
