### ISSUE TITLE
Accesso C030 e C007_richieste massive C019

### ISSUE THREAD

**Issue by valeriobiondo** [italia/anpr#4638]
Buongiorno, 
siamo un'Impresa di assicurazione abilitata all'utilizzo del servizio C019 considerata la necessitá di verificare l'esistenza in vita di migliaia di assicurati. Il servizio C019 é stato testato in ambiente collaudo grazie al vostro supporto.
Nella issue #4609  siamo stati informati dell'impossibilitá di utilizzare massivamente il servizio C019. 
Veniva quindi proposto l'utilizzo del servizio C030 (per ottenere IDanpr) e successivamente utilizzare il servizio C007 (servizio accertamento stato in vita con input IDanpr che restiuisce risultati "S" o "N").   
Su PDND non risulta possibile richiedere la fruizione di tali e-service che consentirebbero richieste massive. 
Potreste gentilmente indicarci come poter usufruire dei servizi C007 e C030? Esistono alternative per poter effettuare verifiche massive con il servizio C019? 
Distinti Saluti

**Comment by azabatta** [comment]
Buongiorno, 
non esiste un'estrazione massiva  che restituisca le stesse risposte della consultazione puntuale del servizio C019.
La possibilità di utilizzare i servizi di elaborazione massiva già pubblicati va richiesta al Ministero dell'Interno, Direzione Centrale Servizi Demografici, che  rende disponibili i servizi di accesso ai dati di ANPR.
Saluti
