### ISSUE TITLE
EN209 Importo diritti segreteria deve essere maggiore di 0,00 euro 

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#464]
Il nostro comune ha soppresso i diritti di segreteria per tutti i certificati rilasciati in modalità web. Non abbiamo mai avuto alcun problema sino a stamattina quando, nella produzione di tali certificati, appare il seguente errore:
EN209 Importo diritti segreteria deve essere maggiore di 0,00 euro.
Non può essere maggiore di 0 perchè , ripeto, tali diritti sono stati soppressi.

**Comment by gcarbonin** [comment]
Mi ricordi per favore il comune e un identificativo operazione del certificato

**Comment by Finalmentesubentrati** [comment]
Comune di Altamura. Si fa riferimento a certificati di residenza chiesti tramite pec dagli avvocati per uso notifica atti giudiziari.

**Comment by gcarbonin** [comment]
Grazie. per controllare mi serve una data o un numero di protocollo del certificato in modo da poter risalire alla richiesta.

**Comment by Finalmentesubentrati** [comment]
Ho appena provato a farne uno ma poiché la richiesta non va a buon fine non mi genera alcun protocollo.

**Comment by gcarbonin** [comment]
Manca un parametro che indica che il comune non incassa i diritti di segreteria (vedi issue 355). Si può inserire dalla WA Gestione dati del comune.
 Occorre:
a.	Accedere alla WA e selezionare la funzione Amministrazione, disponibile in alto a destra sulla HOME PAGE. Nella funzione Gestione Dati del Comune, nei Parametri utilizzati per l'emissione dei certificati, si seleziona Certificati esenti da diritti di segreteria

b.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso allo sportello, è sufficiente indicare nella richiesta l’importo del diritto di segreteria (se questo importo viene riscosso allo sportello)
c.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso on-line dal portale del comune, nella richiesta non si indica l’importo

**Comment by Finalmentesubentrati** [comment]
Grazie 1000. risolto
