### ISSUE TITLE
Errore nella validazione email ANPR

### ISSUE THREAD

**Issue by MarikaP28** [italia/anpr#4640]
Ciao, dovrei inviare la richiesta di cambio residenza e mi chiede di verificare la mail nel profilo utente ma non ricevo la mail di verifica, come posso fare? Ho urgenza nell' invio della pratica!!!

**Comment by voglia0** [comment]
Buongiorno,
sta capitando anche a me,
da ieri, trascorse 24 ore, non ho ancora ricevuto alcuna mail di verifica/validazione all'indirizzo indicato.

**Comment by bikerinside** [comment]
Stessa cosa da ieri che provo ma niete.

**Comment by ncapozzi** [comment]
Buongiorno, è stato riscontrato un disservizio temporaneo che è stato risolto. Potete riprovare la validazione dell'email.
