### ISSUE TITLE
Errore nella validazione email ANPR

### ISSUE THREAD

**Issue by voglia0** [italia/anpr#4641]
Buongiorno,
non ricevo mail di validazione, necessario per avviare pratica di cambio residenza
Primo tentativo + di 24 ore fa, ho provato con 2 caselle gmail ma nulla, ovviamente ho controllato lo spam.

**Comment by ncapozzi** [comment]
Buongiorno, è stato riscontrato un disservizio temporaneo che è stato risolto. Potete riprovare la validazione dell'email.
