### ISSUE TITLE
EMAIL VALIDAZIONE ANPR NON PERVENUTA

### ISSUE THREAD

**Issue by bikerinside** [italia/anpr#4642]
Salve,

sto cercando di validare la mia mail da più di 12 ore,

ho provato sia con una casella gmail che ymail ma il risultato non cambia.

La mail di validazione non arriva.

**Comment by ncapozzi** [comment]
Buongiorno, è stato riscontrato un disservizio temporaneo che è stato risolto. Potete riprovare la validazione dell'email.
