### ISSUE TITLE
test non più funzionante

### ISSUE THREAD

**Issue by marpagno** [italia/anpr#4643]
Salve, 
 mesi fa (maggio) avevo testato con successo (per il Comune di Ravenna) un client per interrogare ANPR via PDND, sui servizi C020 in Test. 

Ieri ho ripreso il progetto e non riesco più ad ottenere un token valido 

chiamando URL: https://auth.uat.interop.pagopa.it/token.oauth2

ottengo

{
  "correlationId" : "dadd80a4-56e6-4411-9204-63b3bbc73746",
  "errors" : [
    {
      "code" : "015-0008",
      "detail" : "Unable to generate a token for the given request"
    }
  ],
  "status" : 400,
  "title" : "The request contains bad syntax or cannot be fulfilled.",
  "type" : "about:blank"
}

Avevo pensato al classico problema di sincronia orologi (il server nuovo era tre minuti avanti) ma anche dopo avere corretto l'orario continuo a non riuscire ad avere il token.

Potreste dirmi qual'è l'errore che vedete dal vostro lato?

Grazie
Marco Pagnoni

**Comment by azabatta** [comment]
Buonasera, 
la problematica non riguarda i servizi di ANPR ma quelli di PDND.
Aprire una issue sul canale github di PDND  (https://github.com/pagopa/pdnd-interop-frontend/issues).
Saluti
