### ISSUE TITLE
Utilizzo Servizio C019

### ISSUE THREAD

**Issue by valeriobiondo** [italia/anpr#4644]
Avremmo la necessitá di effettuare verifiche su migliaia di soggetti assicurati e dunque ci sembra poco fattibile effettuare singole chiamate manualmente del servizio C019.
Abbiamo testato con successo il servizio C019 utilizzando Java.
Il nostro team informatico vorrebbe sviluppare un'applicazione API per utilizzare il servizio.
In tale prospettiva vorremmo ottenere se possibile le specifiche necessarie (tipo di autenticazione, parametri da utilizzare, headers, tipo di chiamata (post/get).
Potreste gentilmente fornirci le indicazioni necessarie?

**Comment by azabatta** [comment]
Buongiorno, la documentazione è disponibile:
- LLGG di AGID Linee Guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni –
Pattern di sicurezza;
- documentazione PDND per l'invocazione dei servizi; 
-  documentazione allegata al servizio C019 sul catalogo PDND (tecnica e funzionale).
Saluti
