### ISSUE TITLE
NUOVO UTENTE ANPR

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#4647]
COMUNE DI GHEMME
Buongiorno, nell'inserimento di un nuovo utente, (NUOVO SINDACO)nel secondo step non sono presenti i ruoli da poter selezionare, per cui non è possibile concludere la procedura, ed al salvataggio non viene restituita alcuna anomalia ma giustamente il messaggio "Per proseguire è necessario selezionare almeno un profilo".
Nel nostro comune avendo eliminato il Sindaco uscente siamo solo due figure ALP, è forse questo il problema? Come possiamo fare?
Grazie

**Comment by dmazelli** [comment]
Buongiorno,
La invitiamo a contattarci al numero verde 800.86.31.16 per richiedere supporto.
Cordiali saluti.
