### ISSUE TITLE
[ANPR-PDND C020-servizioAccertamentoResidenza] Errore 400 - InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by fab956** [italia/anpr#4649]
Buongiorno,

ho un problema nell'identificare la causa dell'errore restituito da una richiesta di test effettuata verso il servizio ANPR della piattaforma di collaudo PDND ([C020-servizioAccertamentoResidenza](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002).

La chiamata è stata effettuata alle 9.18 del 04/09/2024.
L'errore restituito è il seguente
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "350f024d-6a87-11ef-8ab2-005056ae5232"
}
```

Potreste cortesemente darmi maggiori informazioni riguardo cosa non è corretto?
Grazie

**Comment by azabatta** [comment]
Buonasera, 
di seguito l'errore riscontrato dal sistema:

Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

Saluti

**Comment by azabatta** [comment]
Buongiorno, 
al momento è di 30 caratteri ma stiamo valutando di aumentarla.
Suggeriamo di utilizzare un timestamp per la sua valorizzazione.
Buon lavoro

**Comment by fab956** [comment]
Buongiorno, 
in ambiente di produzione, sempre per il servizio ([C020-servizioAccertamentoResidenza](https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1)), utilizzando uno stesso token, non riesco a capire perchè, effettuando due richieste il cui body differisce tra le due solo per il valore nella proprietà "idOperazioneClient", una ha successo con HTTP OK 200, mentre l'altra restituisce l'errore HTTP 400 "InteroperabilityInvalidRequest".

Entrambe le richieste sono state effettuate oggi 05/09/2024. 
La prima richiesta, eseguita con successo, riporta il seguente GovWay-Transaction-ID:
```
GovWay-Transaction-ID: 282f0c1e-6b67-11ef-99aa-005056ae091b
```
mentre la seconda restituisce il seguente errore 400:
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "2f93bede-6b67-11ef-9010-005056ae1d2a"
}
```

Riuscite ad indicarmi qual è l'errore in questo caso? Forse è necessario in intervallo minimo di tempo tra due richieste?
Grazie in anticipo.

**Comment by azabatta** [comment]
Buonasera, 
l’errore è il seguente:

Token non utilizzabile prima della data '2024-09-05_11:16:52.000’
 
Significa che il token di audit o integrity che create ha una data di inizio validità a partire dalle '2024-09-05_11:16:52.000 ma è stato utilizzato prima di quella data-ora.

Saluti
