### ISSUE TITLE
Scioglimento unione civile

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#465]
I dati dello scioglimento dell'unione civile sono definiti nell'oggetto scioglimentoUnione, che comprende tre tag facoltativi. 
E' possibile avere una descrizione dei dati obbligatori o comunque dei vincoli fra questi dati? Grazie.
Filipazzi - Maggioli

**Comment by frmariani** [comment]
Nell’oggetto scioglimento unione, i tag sono: Motivo scioglimento, Sentenza, Dati evento;

il motivo di scioglimento è un dato obbligatorio (i motivi sono censiti nella tabella 43  id >31)

E' obbligatorio inserire in alternativa esclusiva i dati della sentenza o i dati Evento.

**Comment by bfilipazzi** [comment]
C'è un refuso nella risposta, tabella 43 id < 31.
La decorrenza dello scioglimento sarà desumibile in un caso la data della sentenza e nell'altra la data dell'atto. Giusto?

**Comment by frmariani** [comment]
Mi scuso per il refuso. Circa la data di decorrenza valgono le stesse regole discusse più volte: la data di decorrenza giuridica dello scioglimento è quella da lei indicata.

**Comment by frmariani** [comment]
le specifiche di interfaccia per il comune sono state aggiornate per rendere più chiaro l'inserimento dei dati relativi allo scioglimento dell'unione.
Sono disponibili nel portale ANPR.
