### ISSUE TITLE
Mutazione dati anagrafici che impedisce annullamento residenza

### ISSUE THREAD

**Issue by Marliana24-anag** [italia/anpr#4650]
Buongiorno,

ambiente di PRODUZIONE - comune di Marliana

Il Comune ha iscritto tra i suoi residenti l'anagrafica con ID ANPR 336532703, proveniente dall'estero ma viene "agganciato" un cittadino residente in un altro Comune italiano (stesso nome, cognome, luogo di nascita , cambia solo la data di nascita). 

Nei giorni successivi si procede ad una mutazione di dati anagrafici ma il soggetto ormai viene cancellato dal precedente Comune.

Si rende necessario annullare l' iscrizione e riportare il soggetto nel Comune di precedente iscrizione ma questa operazione viene impedita dalla presenza di una mutazione dati anagrafici successiva alla mutazione di residenza e il sistema non ci permette di cancellarla.

Tentando dal portale di annullare questa comunicazione,  ci viene restituito come come errore:
"Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione. (Codice: EN234)"

Come possiamo procedere ad annullare la mutazione anagrafica e all'annullamento della mutazione di residenza in modo da riportare l'anagrafica nel precedente comune di iscrizione ?

Ringraziando anticipatamente,

cordiali saluti

**Comment by frmariani** [comment]
Per assistenza su casi specifici si deve contattare l'assistenza ANPR al numero 800836116.
Mi permetto soltanto di far notare che il cittadino non viene "agganciato" ma ricercato attraverso precisi criteri di ricerca.
L'assistenza vi darà le indicazioni del caso, ma la prossima volta gentilmente, prima di modificare la residenza ed i dati anagrafici di un cittadino, contattate il comune di provenienza ed effettuate le indagini del caso, magari anche confrontando i cartellini se ne siete in possesso.
Le anticipo che **le operazioni che avete effettuato non sono annullabili.**

**Comment by Marliana24-anag** [comment]
Buongiorno e grazie per la risposta.
Ho usato il termine agganciato ma ovviamente l'errore è mio e non di ANPR. E' stata una mia distrazione.
Cordiali saluti.
