### ISSUE TITLE
codiceErroreAnomalia>EF002

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#4652]
Buongiorno,
richiedendo un'operazione 5001, ANPR risponde con un codice d'errore "EF002-Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata"
idOperazioneComune>JD24090509401866431
idOperazioneANPR>1938908171
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-09-05 09:40:22 , idOperazioneANPR 1938908171

**Comment by azabatta** [comment]
Buonasera 
potete ripetere la richiesta? 
Saluti

**Comment by UpiTorino** [comment]
Buongiorno,

oggi l'operazione non ha restituito errori quindi si può chiudere la issue.
Saluti!
