### ISSUE TITLE
Errore AE0097

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#4653]
Ci vengono segnalati, anche oggi, problemi di iscrizione ANPR con validazione CF per errore "Servizio Agenzia Entrate momentaneamente non disponibile"

**Comment by jonnyfx95** [comment]
Anche diversi nostri comuni hanno lo stesso problema.

**Comment by azabatta** [comment]
Buonasera, 
grazie per la segnalazione, ci sono stati dei rallentamenti nel colloquio verso Agenzia Entrate.
La situazione è rientrata intorno alle 13.45.
Saluti
