### ISSUE TITLE
ANPR Elettorale - Impossibilità di certificare soggetto elettore 

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4654]
Buongiorno, 

Il comune di SEREGNO sta provando a certificare un elettore iscritto nelle proprie liste con "certificabilià completa" completa (lato elettorale).
Provando ad emettere il certificato viene restituire il seguente errore:

Iscrizione nelle liste elettorali: Il certificato non può essere emesso in quanto il soggetto risulta non certificabile.

La non certificabilià esiste per il soggetto, ma è lato Anagrafe ANPR.
Infatti facendo una mutazione e mettendolo la: "Certificabilità completa" funziona.

Si chiedono delucidazioni in merito, per capire per quale motivo è stato deciso di impedire la certificabile e soggetti elettorali non interdetti se in anagrafe ANPR non è stato impostato: Non certificabile.

**Comment by frmariani** [comment]
Buongiorno,
per favore riprovate la certificazione elettorale e fatemi sapere.
Grazie
