### ISSUE TITLE
COMUNE DI CASTEL SAN GIOVANNI. 

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#4656]
COMUNE DI CASTEL SAN GIOVANNI. 
Riferimento tecnico per questo post: Edoardo Dona' 338 59 09 376 edoardodona@gmail.com

Venerdi scorso (6/9/2024) abbiamo cambiato dislocazione da on premise a cloud del Sw Anagrafe.
Nonostante venerdi' via webapp sia stato aggiunto indirizzo ip del nuovo server che deve dialogare con ANPR 
e sia stato soppresso il vecchio indirizzo, la comunicazione con ws.anpr.interno.it NON FUNZIONA.
Stamattina abbiamo ancora: 
nc -z -v ws.anpr.interno.it 443
nc: connect to ws.anpr.interno.it (217.175.52.225) port 443 (tcp) failed: Connection timed out

GRAZIE.

**Comment by adominicis** [comment]
Buongiorno
fare riferimento alla issue #4555 

Cordiali saluti

Assistenza ANPR
