### ISSUE TITLE
Errore 999 in richiesta P002 (come issue #4310)

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4657]
In ambiente TEST ho lo stesso problema della issue #4310 che viene indicato come risolto.

Con qualsiasi richiesta di P002 
la risposta è sempre:

<errore>
  <codiceErroreAnomalia>999</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
/errore>

@apaolacci potresti aiutare anche me ?

Grazie.

**Comment by Hdemografici** [comment]
in allegato xml richiesta e risposta di ambiente test.

<ns2:RichiestaP002>
<testataRichiesta>
<idOperazioneComune>20240910141819067</idOperazioneComune>
<codMittente>041069</codMittente>
<codDestinatario>ANPR05</codDestinatario>
<operazioneRichiesta>P002</operazioneRichiesta>
<dataOraRichiesta>2024-09-10T14:18:19</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<dataProtocolloComune>2024-09-10</dataProtocolloComune>
<tipoInvio>TEST</tipoInvio>
<dataDecorrenza>2024-09-10</dataDecorrenza>
<dataDefinizionePratica>2024-09-10</dataDefinizionePratica>
<nomeApplicativo>ANPR</nomeApplicativo>
<versioneApplicativo>08.90.90</versioneApplicativo>
<fornitoreApplicativo>HALLEY INFORMATICA srl</fornitoreApplicativo>
</testataRichiesta>
<criteriRicerca>
<codiceRichiesta>1960768</codiceRichiesta>
</criteriRicerca>
</ns2:RichiestaP002>



<soapenv:Envelope>
<soapenv:Body>
<a:RispostaP002>
<a:rispostaKO>
<testataRisposta>
<idOperazioneComune>20240910141819067</idOperazioneComune>
<codMittente>041069</codMittente>
<codDestinatario>ANPR05</codDestinatario>
<operazioneRichiesta>P002</operazioneRichiesta>
<dataOraRichiesta>2024-09-10T14:18:19</dataOraRichiesta>
<dataProtocolloComune>2024-09-10</dataProtocolloComune>
<dataDecorrenza>2024-09-10</dataDecorrenza>
<idOperazioneANPR>73390794</idOperazioneANPR>
<esitoOperazione>XXXX</esitoOperazione>
</testataRisposta>
<listaErrori>
<errore>
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
</listaErrori>
</a:rispostaKO>
</a:RispostaP002>
</soapenv:Body>
</soapenv:Envelope>

**Comment by Hdemografici** [comment]
In allegato 

xml di richiesta:
`<ns2:RichiestaP002>
<testataRichiesta>
<idOperazioneComune>20240910141819067</idOperazioneComune>
<codMittente>041069</codMittente>
<codDestinatario>ANPR05</codDestinatario>
<operazioneRichiesta>P002</operazioneRichiesta>
<dataOraRichiesta>2024-09-10T14:18:19</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<dataProtocolloComune>2024-09-10</dataProtocolloComune>
<tipoInvio>TEST</tipoInvio>
<dataDecorrenza>2024-09-10</dataDecorrenza>
<dataDefinizionePratica>2024-09-10</dataDefinizionePratica>
<nomeApplicativo>ANPR</nomeApplicativo>
<versioneApplicativo>08.90.90</versioneApplicativo>
<fornitoreApplicativo>HALLEY INFORMATICA srl</fornitoreApplicativo>
</testataRichiesta>
<criteriRicerca>
<codiceRichiesta>1960768</codiceRichiesta>
</criteriRicerca>
</ns2:RichiestaP002>
`

xml di risposta:
`<soapenv:Envelope>
<soapenv:Body>
<a:RispostaP002>
<a:rispostaKO>
<testataRisposta>
<idOperazioneComune>20240910141819067</idOperazioneComune>
<codMittente>041069</codMittente>
<codDestinatario>ANPR05</codDestinatario>
<operazioneRichiesta>P002</operazioneRichiesta>
<dataOraRichiesta>2024-09-10T14:18:19</dataOraRichiesta>
<dataProtocolloComune>2024-09-10</dataProtocolloComune>
<dataDecorrenza>2024-09-10</dataDecorrenza>
<idOperazioneANPR>73390794</idOperazioneANPR>
<esitoOperazione>XXXX</esitoOperazione>
</testataRisposta>
<listaErrori>
<errore>
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
</listaErrori>
</a:rispostaKO>
</a:RispostaP002>
</soapenv:Body>
</soapenv:Envelope>`

Grazie mille @apaolacci .

**Comment by apaolacci** [comment]
@Hdemografici 
abbiamo verificato e corretto un refuso sul salvataggio dei dati in fase di creazione di una nuova pratica, 
potreste riprovare il recupero della dichiarazione di cambio residenza `<codiceRichiesta>1960768</codiceRichiesta>`?

Di ogni test di recupero che effettuerete sulla pratica 1960768, cortesemente forniteci `idOperazioneComune ` e esito dell'invocazione. Grazie.

Saluti,
Assistenza ANPR
