### ISSUE TITLE
Servizi Anagrafici ed Elettorali 

### ISSUE THREAD

**Issue by Riccardo19690712** [italia/anpr#4658]
Partendo dalla pagina:
https://www.comune.milano.it/servizi/residenza-cittadini-italiani

In seguito all'accesso ai servizi anagrafici con Speed Poste Italiane vengo reindirizzato a questa pagina:
https://sc.anpr.interno.it/serviziCittadino/open/errorPage/noauth

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Il problema sembra legato al mio codice fiscale.

Grazie e buona giornata

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
