### ISSUE TITLE
[WebApp] Iscrizione altri motivi

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#466]
Sto provando da Web application (ambiente pre-subentro Bistagno 006017) ad effettuare un'iscrizione per altri motivi (immigrazione da altro comune) come "operazione d'ufficio". I dati del cittadino sono del tutto fittizi, e riesco ad inserirli con successo in: generalità, cittadinanza, atto di nascita, paternità, maternità, provenienza, famiglia, finchè non mi chiede i dati del coniuge, nonostante abbia specificato statoCivile='celibe' e relPar="altro affine". Di fatto non riesco a concludere l'operazione, perchè non mi fa procedere, in quanto la wa vorrebbe anche i dati del matrimonio. Premetto che è solo una prova come esercizio, ma dove sta l'errore? Grazie

**Comment by gcarbonin** [comment]
la contattiamo telefonicamente per seguire l'esatta sequenza delle operazioni

**Comment by gcarbonin** [comment]
Chiarite le modalità operative, l'iscrizione si è completata con successo

**Comment by Eduardo1977** [comment]
Si grazie.  Risolto telefonicamente con l'assistenza di @cmigliardi .  Funziona tutto correttamente, ero io ad interpretare male un messaggio.
