### ISSUE TITLE
[ANPR-Certificazione] Codice Errore 999 per richiesta esibizione certificato in ambiente di test

### ISSUE THREAD

**Issue by bugaNTL** [italia/anpr#4664]
Buongiorno,

Sono Constantin Cristian Buga, sviluppatore Notartel, mi sto occupando dell'integrazione dei servizi C030 e ANPR-Certificati per la Cassa Nazionale del Notariato.

Stiamo implementando la cornice di sicurezza, riusciamo ad avere risposte positive sul servizio C030, riscontriamo errori sulle risposte di ANPR-Certificati. Allo stato attuale sospettiamo ci sia un problema col payload che stiamo inviando e non tanto con la parte di sicurezza.

Errore che riceviamo:

```json
{"idOperazioneANPR":"0","listaErrori":{"errore":[{"codiceErroreAnomalia":"999","testoErroreAnomalia":"Operazione non effettuabile","tipoErroreAnomalia":"E"}]}}
```

a fronte di request body:

```json
{"idOperazioneClient":"123","linguaCertificato":{"tipoLinguaCertificato":["IT"]},"listaTipiCertificati":{"tipoCertificato":["1"]},"soggettoIntestatario":{"generalita":{"cognome":"Tedesco","nome":"Figlia"},"idANPR":"KP29156QJ"},"tipoRichiedente":"1","tipoRichiesta":"1","esenzioneDiritti":"1","esenzioneBollo":"3","bollo":"0","paEstera":"0","emissione":"2","diritti":"0"}
```

tra gli header di risposta abbiamo:

```
GovWay-Message-ID = 80118d7a-eea3-4010-986e-d78ffd5d31f5
GovWay-Transaction-ID = 98b8037d-7667-11ef-a70a-005056ae1884
X-Global-Transaction-ID = 6026e6bc66ebf11d7a35258f
```

Ci sarebbe utile sapere cosa stiamo sbagliando o in alternativa avere una request di esempio che possa produrre una risposta positiva.

In attesa di vostro riscontro,

Cordiali saluti

**Comment by azabatta** [comment]
Buonasera, 
c'era un problema sul Db di test, è possibile riprovare. 
Abbiamo notato che la richiesta contiene  "tipoRichiedente" 1 (richiedente ed intestatario non coincidono): per questa tipologia di richiesta è necessario inserire anche  i dati del richiedente. Quando richiedente ed intestatario coincidono è necessario valorizzare "tipoRichiedente" a 2. 
Saluti

**Comment by bugaNTL** [comment]
Buongiorno,

Grazie per la risposta precedente.
Stiamo riscontrando nuovamente l'errore segnalato in precedenza.

```json
{"idOperazioneANPR":"0","listaErrori":{"errore":[{"codiceErroreAnomalia":"999","testoErroreAnomalia":"Operazione non effettuabile","tipoErroreAnomalia":"E"}]}}
```

```txt
GovWay-Message-ID=95f9fe8a-05a6-418d-9d45-626dc83b41ca
GovWay-Transaction-ID=4aeda066-7efc-11ef-b23b-005056ae5232
X-Global-Transaction-ID=6026e6bc66fa592e96257c2f
```

Cordiali saluti

**Comment by azabatta** [comment]
Buongiorno, 
cortesemente potete riprovare e darci un riscontro?
Grazie

**Comment by bugaNTL** [comment]
Il servizio risponde correttamente.

Grazie

**Comment by azabatta** [comment]
Perfetto, chiudo questa issue e restiamo a disposizione per le successive integrazioni.
Saluti
