### ISSUE TITLE
Problemi con l'accesso Anagrafe Nazionale

### ISSUE THREAD

**Issue by Saimir123** [italia/anpr#4669]
Salve,
non riesco ad accedere su Anagrafe Nazionale ed ogni volta che provo mi dà questo messaggio
"**purtroppo non e stato possibile accederé al servicio, ti consigliamo di rivolgerti al tuo comune di residenza per maggiori informazioni, al fine di sanare lànomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.**"

le prime 6 lettere del codice fiscale: XHFSMR
già controllato sul sito dell'agenzia delle entrate ed è ancora valido.

Sapete dirmi quale possa essere il problema? Sono residente a Firenze. Grazie

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
