### ISSUE TITLE
Ambiente di Test : errore 999 in cancellazione 2003

### ISSUE THREAD

**Issue by busaster** [italia/anpr#467]
Poggio a Caiano test.
Tentanto di cancellare con il servizio 2003 per "Ripristino posizione precedente" un soggetto ottengo "999 operazione non effettuabile".
ID Operazione ANPR = 678265
Potete aiutarmi a capire quale sia la causa ?
Grazie

**Comment by gcarbonin** [comment]
Può riprovare

**Comment by busaster** [comment]
Grazie, ora è andata a buon fine. 
Posso sapere a cosa era dovuta l'anomalia ?

**Comment by gcarbonin** [comment]
A un problema nostro di aggiornamento dei dati da storicizzare
