### ISSUE TITLE
C031-servizioVerificaIdUnicoNazionale - InvalidResponse

### ISSUE THREAD

**Issue by Davide-Almaviva** [italia/anpr#4677]
Buongiorno,

effettuando dei test in ambiente di collaudo verso il vostro servizio di interop della piattaforma PDND ([C031-servizioVerificaIdUnicoNazionale](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C031-servizioVerificaIdUnicoNazionale/v1/status)) abbiamo ricevuto un errore di cui vorremmo avere qualche specifica.
Di seguito trovate tutti i dettagli.
Tutti i vari header di sicurezza dovrebbero essere presenti e ben popolati, seguendo la documentazione AGID Interoperabilità relativa.

Per favore potete indirizzarci su tale errore ?

Grazie.
D.

**Data di invio**: 01/10/2024

**Voucher**: la piattaforma PDND ha generato correttamente l'access token (con all'interno il digest di Audit)che abbiamo incluso nell'header (Authorization) della chiamata.

**Dati inviati**: nessuno (body vuoto), dato che si tratta di una prima prova al servizio "/status"

**Agid-Jwt-Signature**: calcolata e aggiunta nel relativo header della request

**Agid-JWT-TrackingEvidence**: calcolata e aggiunta nel relativo header della request

**Digest**: non presente dato che si tratta di una semplice GET con body vuoto (su questo punto prego confermare)

Errore ricevuto:
```
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "28dc442b-7fca-11ef-b71c-005056ae1884"
}
```

**Comment by afrontera85** [comment]
Salve,
potete riprovare togliendo dall'header:      "Accept", "application/problem+json"?

**Comment by Davide-Almaviva** [comment]
Buondì,

Abbiamo fatto una prova rimuovendo del tutto l'header "_Accept_" come indicato, sebbene segnaliamo comunque che questo è dichiarato nello swagger relativo [C031 - Specifica API.yaml.txt](https://github.com/user-attachments/files/17244830/C031.-.Specifica.API.yaml.txt)
Vedere righe dalla 38 alla 43.

Tuttavia sembra che sia peggio di prima, in quanto ora riceviamo l'errore di sicurezza dettagliato di seguito sebbene tutti gli header siano popolati.


**Data di invio**: 03/10/2024

**Errore ricevuto**:
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "926e99d1-8185-11ef-a4dc-005056ae5232"
}
```

Quale può essere il motivo ?

Grazie per il supporto.
D.

**Comment by Davide-Almaviva** [comment]
Per scrupolo, abbiamo fatto anche una prova con la POST funzionale esposta dal medesimo eService (/anpr-service-e002), dove sicuramente sono previsti gli header (sempre seguendo lo swagger relativo):
```
Content-Type: application/json
Accept: application/json
```
Ma l'errore sembra il medesimo riportato sopra. Di seguito trovate i dettagli per check.

**Data di invio:** 03/10/2024

**Errore ricevuto:**
```
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "d0db610d-818b-11ef-8e65-005056ae1884"
}
```

**Comment by afrontera85** [comment]
Ciao! allora, per la chiamata in get (per lo status), dovreste riprovare senza il Token di integrity, perchè quello serve a firmare il payload, ma se il payload non c’è, l'Agid-jwt-signature non ci deve essere.
Per la chiamata in post, invece, potreste rifare una prova adesso?

**Comment by Davide-Almaviva** [comment]
Buondì,

Grazie per il feedback tecnico.

Per la chiamata GET (/status), **abbiamo effettuato 2 prove**:
1) mettere nell'header solo "Accept:application/json" (ignorando di fatto quanto dichiarato nello swagger) e lasciando il solito computo di "Agid-jwt-signature"
2) rimuovere del tutto sia l'header "Accept" sia quello "Agid-jwt-signature" come indicato
per entrambi i test abbiamo ricevuto un 200 OK.

Quindi, se per voi ok, possiamo procedere con una delle due soluzioni in base alle necessità di chiamata e agli sviluppi.
Andrebbe comunque poi _sistemato lo swagger lato erogatore_, perché come ora non risulta corretto a livello tecnico per questa parte.

**_DUBBIO_**: Leggendo le normative AGID, sembra che il Token di Integrity (agid-jwt-signature) in realtà serva per firmare sia gli headers (signed_headers) che il payload (digest).
Quindi se nessuna delle due sezioni è presente --> ok a rimuoverlo come detto
Ma se ci fosse anche solo 1 header previsto e nessun body (no digest), tale header di sicurezza sembra obbligatorio ai fini del requisito di integrity.

Per favore potete verificare e farci sapere ?

Nel mentre effettuiamo dei test sulla POST.


Saluti.
D.

**Comment by afrontera85** [comment]
Si, vanno bene tutte e due le soluzioni, sistemeremo lo swagger.
Il token di integrity serve a garantire l’integrità e non ripudio del payload, non essendoci decade la sua necessità

**Comment by Davide-Almaviva** [comment]
In merito alla POST esposta dal medesimo eService (/anpr-service-e002), come ci avete richiesto abbiamo provveduto a fare dei nuovi test.
Ma purtroppo l'errore dall'esterno sembra il medesimo. Di seguito trovate i dettagli per verifica.

**Data di invio**: 04/10/2024

**Errore ricevuto**:
```
{
    "type": "https://govway.org/handling-errors/502/InvalidResponse.html",
    "title": "InvalidResponse",
    "status": 502,
    "detail": "Invalid response received from the API Implementation",
    "govway_id": "fea9b7d0-824e-11ef-a04b-005056ae1884"
}
```

**Comment by afrontera85** [comment]
Il problema sono dei campi che ci arrivano valorizzati con <string>, 
se sono null non dovete passarli proprio, altrimenti valorizzarli coerentemente.
Alcuni però sono obbligatori, come casoUso che deve essere C031 in questo caso e dataRiferimentoRichiesta che deve essere una data
Questo è quello che ci arriva:
{
  "idOperazioneClient" : "1",
  "criteriRicerca" : {
    "codiceFiscale" : "STTSGT90A01H501J",
    "idANPR" : "<string>",
    "cognome" : "SETTIMO",
    "nome" : "SOGGETTO",
    "sesso" : "M",
    "datiNascita" : {
      "dataEvento" : "1990-01-01",
      "luogoNascita" : {
        "luogoEccezionale" : "<string>",
        "comune" : {
          "nomeComune" : "ROMA",
          "codiceIstat" : "<string>",
          "siglaProvinciaIstat" : "RM",
          "descrizioneLocalita" : "<string>"
        },
        "localita" : {
          "descrizioneLocalita" : "<string>",
          "descrizioneStato" : "<string>",
          "codiceStato" : "<string>",
          "provinciaContea" : "<string>"
        }
      }
    }
  },
  "datiRichiesta" : {
    "dataRiferimentoRichiesta" : "<string>",
    "casoUso" : "<string>",
    "motivoRichiesta" : "<string>"
  },
  "verifica" : {
    "identificativi" : {
      "idANPR" : "<string>"
    }
  }
}

**Comment by Davide-Almaviva** [comment]
Come da prassi, abbiamo utilizzato alcuni dei test case pubblicati direttamente su portale PDND di Collaudo per il servizio in questione. Vedere immagine sotto per dettagli.
![TestCase](https://github.com/user-attachments/assets/5862892e-2821-47cb-9ec5-292922c6e88f)

In base a quello che ci dite e all'evidenza tecnica fornita sopra, sembra quindi che per tali scenari di test forse non siano fornite tutte le informazioni di ricerca necessarie (es. mancano esempi di "idANPR" e altri campi obbligatori come quelli citati).

Avete un esempio completo di chiamata in 200 OK da poter utilizzare come test, solo per vedere se il servizio funziona a livello tecnico ?

**Comment by afrontera85** [comment]
Eccolo:
 {
    "idOperazioneClient": "0",
     
    "criteriRicerca": {
      "codiceFiscale": "DCLVNT58H11H501C"
    },
   "verifica": {
          "identificativi": {
              "idANPR": "ZX20387XJ"
          }
   },
              
              
    "datiRichiesta": {
      "dataRiferimentoRichiesta": "2024-10-07",
      "motivoRichiesta": "motivo",
      "casoUso": "C031"
    }
  }
  
Per recuperare l'idANPR di altri CF potete usare il C030

**Comment by Davide-Almaviva** [comment]
Grazie per l'esempio di request funzionale sul servizio.
Confermo che con questo caso di test riceviamo un 200 OK e quindi una risposta valida dal servizio in questione. L'aggancio all'API C031 risulta quindi ora funzionante sia lato tecnico sia rispetto alle norme di sicurezza AGID.

Grazie mille per il supporto.
Bye.
