### ISSUE TITLE
C030-servizioAccertamentoIdUnicoNazionale: InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by calogeroprovenzano** [italia/anpr#4679]
Salve,

sono un dipendente dell'Università degli Studi di Palermo e stiamo implementando un client php che effettui la chiamata al servizio C030 per ottenere il personId a fronte dell'invio del relativo codice fiscale. A seguito della chiamata avvenuta oggi 02/09/2024 alle 009.30 circa, riceviamo la seguente risposta:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
 "title":"InteroperabilityInvalidRequest",
 "status":400,
 "detail":"Received request is not conform to the required interoperability profile",
 "govway_id":"c865f587-8087-11ef-8855-005056ae5232"
 }
 
 potreste gentilmente verificare cosa c'è di sbagliato nei dati che vi inviamo?
 
 Grazie mille in anticipo.
 Provenzano Calogero

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id fornito è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
 Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by fabricorse** [comment]
Buonasera, anche noi abbiamo lo stesso problema, utilizzando il client che avete messo a disposizione la chiamata al C030 su PDND di test fallisce. riporto i dati:
Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NDYsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6ImMwODA1MDEzNzAyOWU0NTIxZGVlNmFmYWM5OTZkM2EzZDU1ZjQ0OTQxMDkxZjY5MDI3MmI0NjZlZGU3MDVlYWEifSwicHVycG9zZUlkIjoiNWQ2ZWYxNzAtNGRjNS00NjNiLWI1YjgtZGFkNjFmZTliMzA4IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI3OTY1NTQ2LCJpYXQiOjE3Mjc5NjQ5NDYsImNsaWVudF9pZCI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsImp0aSI6ImRkNGFlNzZlLTMwZWQtNDZmNC04MDIzLTdkOGE1ZjVlNDcwNiJ9.LHzyLo67Xa44ZseQFdYcqYaZCmqs9CkvQoQrZCjNVc_xyWnNvutncTaBBcsUljCLKiRAfLHz1LMLCW4wxqivUkBDoAnZqdC80PwASQ2XDZZ3kBHfGpOKDsLoXHPfrsiSf2evBw-PqPOLEPk8_VmOsW5LA9AZ6H4oejnLynGJ0e16ZEJ0-y_fvGodONv3bXyfsi2eJyCYeVLGQ_imr1dhsS1WaNF0KvA8A04bOkZ80HOI0UjZ4k4cCSAj9THJCdpwOF0Dq2fvYFD2_eSa9bVCGr1tidP-GOxUM3eNxC1ZSGmNJj0zaRQA5vMVzSq0ciMWCZ32AOrj73uZA0BwrCP2Dg
Agid-JWT-Signature: eyJ0eXAiOiJKV1QiLCJraWQiOiJDZXZIanQ2d0J0dldQVERDcllpamVsemtQZW5hRlFLaTAzemV6NnV6MTBVIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NTAsImlzcyI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PXh6NnF5MVdKV3Jjc0JFZWxpSlVyYW82UVQwekgxMTl4bHEzN2sxdjkvS1k9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dLCJleHAiOjE3Mjg1NjQ5NTAsImlhdCI6MTcyNzk2NDk1MCwianRpIjoiOTk3Y2Q2N2ItNjVjYS00OWM2LTg3MmUtYjJjYmY0YzQ3NTllIn0.JEheipX8eKCEwRAFq9uUUgViB2mxksl7wIQLFM9v6ev3ek8jZS3fQNpcuyF40GYRZVPL8pW5gFmb_2xsvVGl0ufEAmgHMsLsTO_M3g1gt_Q1ll4qWyMQGDHrFqfGHd0J6_ER74wtF1IIsEt2kz6fJiJ4ortx3u9jINvepyTfhQSHS8n41ob0Mwas5b3uc6cFqK1omij3W0sCoQok5UK2E3vsTdfkZat2rGzk-oVVs5yiD8L4ICBdm5BB470p1njfZa9yIGIqN1WEOpKkHeyJxsaQZpnFDb6D7lXFWkfLvuHWqQH8YDtqECXGb-4_vnyWEq6MFl7CMMtu4u62f-Ywfw
Agid-JWT-TrackingEvidence: eyJ0eXAiOiJKV1QiLCJraWQiOiJDZXZIanQ2d0J0dldQVERDcllpamVsemtQZW5hRlFLaTAzemV6NnV6MTBVIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NDksInB1cnBvc2VJZCI6IjVkNmVmMTcwLTRkYzUtNDYzYi1iNWI4LWRhZDYxZmU5YjMwOCIsImlzcyI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsInVzZXJMb2NhdGlvbiI6IjI2LjIuMTIuMjMiLCJleHAiOjE3Mjg1NjQ5NDksImRub25jZSI6IjEyMzQ1Njc4OTAxMjMiLCJ1c2VySUQiOiJVc2VyMTIzIiwiaWF0IjoxNzI3OTY0OTQ5LCJqdGkiOiJhOWJmZmQ1MS03YzVmLTQ4NzYtYjM5NS1iN2E2OTg4NTE3YmQiLCJMb0EiOiJMT0EzIn0.uVl9OLmzuK10PEwRfVy3MZAgGcoN5EqFIqIYhS3P1JHImeGo9WTToJ8k0FBry1YUUaKB07x2CIVXMeZfwK11Zh9ia2ijFji-SeXWUqgg35zqcNnLm2XyDDoV63NihEDSP6G4ZUGuukb_i1PYNfwNkxVzcrKwTwPFjeKNfcguk8URT2isWOBzOiQlmKBO1iAWBfT2zdfXw7deszOxIagRxO_L-hmZaSSUzl_43m7xqmvDfVUAYDAwPaFAv2xxTOZqActANGZtbhxcjQqyoYYjSTWeJ9BP9ivLMsOkgC9z9ArinXfQogja0CZGp2R7kkIrjd1cI1A6cMSQNUC4D2cJZw
Digest: SHA-256=xz6qy1WJWrcsBEeliJUrao6QT0zH119xlq37k1v9/KY=
Content-Type: application/json

GovWay-Transaction-ID: ea0f6835-818b-11ef-8e65-005056ae1884
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"ea0f6835-818b-11ef-8e65-005056ae1884"}

**Comment by afrontera85** [comment]
> Buonasera, anche noi abbiamo lo stesso problema, utilizzando il client che avete messo a disposizione la chiamata al C030 su PDND di test fallisce. riporto i dati: Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NDYsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6ImMwODA1MDEzNzAyOWU0NTIxZGVlNmFmYWM5OTZkM2EzZDU1ZjQ0OTQxMDkxZjY5MDI3MmI0NjZlZGU3MDVlYWEifSwicHVycG9zZUlkIjoiNWQ2ZWYxNzAtNGRjNS00NjNiLWI1YjgtZGFkNjFmZTliMzA4IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI3OTY1NTQ2LCJpYXQiOjE3Mjc5NjQ5NDYsImNsaWVudF9pZCI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsImp0aSI6ImRkNGFlNzZlLTMwZWQtNDZmNC04MDIzLTdkOGE1ZjVlNDcwNiJ9.LHzyLo67Xa44ZseQFdYcqYaZCmqs9CkvQoQrZCjNVc_xyWnNvutncTaBBcsUljCLKiRAfLHz1LMLCW4wxqivUkBDoAnZqdC80PwASQ2XDZZ3kBHfGpOKDsLoXHPfrsiSf2evBw-PqPOLEPk8_VmOsW5LA9AZ6H4oejnLynGJ0e16ZEJ0-y_fvGodONv3bXyfsi2eJyCYeVLGQ_imr1dhsS1WaNF0KvA8A04bOkZ80HOI0UjZ4k4cCSAj9THJCdpwOF0Dq2fvYFD2_eSa9bVCGr1tidP-GOxUM3eNxC1ZSGmNJj0zaRQA5vMVzSq0ciMWCZ32AOrj73uZA0BwrCP2Dg Agid-JWT-Signature: eyJ0eXAiOiJKV1QiLCJraWQiOiJDZXZIanQ2d0J0dldQVERDcllpamVsemtQZW5hRlFLaTAzemV6NnV6MTBVIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NTAsImlzcyI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PXh6NnF5MVdKV3Jjc0JFZWxpSlVyYW82UVQwekgxMTl4bHEzN2sxdjkvS1k9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dLCJleHAiOjE3Mjg1NjQ5NTAsImlhdCI6MTcyNzk2NDk1MCwianRpIjoiOTk3Y2Q2N2ItNjVjYS00OWM2LTg3MmUtYjJjYmY0YzQ3NTllIn0.JEheipX8eKCEwRAFq9uUUgViB2mxksl7wIQLFM9v6ev3ek8jZS3fQNpcuyF40GYRZVPL8pW5gFmb_2xsvVGl0ufEAmgHMsLsTO_M3g1gt_Q1ll4qWyMQGDHrFqfGHd0J6_ER74wtF1IIsEt2kz6fJiJ4ortx3u9jINvepyTfhQSHS8n41ob0Mwas5b3uc6cFqK1omij3W0sCoQok5UK2E3vsTdfkZat2rGzk-oVVs5yiD8L4ICBdm5BB470p1njfZa9yIGIqN1WEOpKkHeyJxsaQZpnFDb6D7lXFWkfLvuHWqQH8YDtqECXGb-4_vnyWEq6MFl7CMMtu4u62f-Ywfw Agid-JWT-TrackingEvidence: eyJ0eXAiOiJKV1QiLCJraWQiOiJDZXZIanQ2d0J0dldQVERDcllpamVsemtQZW5hRlFLaTAzemV6NnV6MTBVIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzdWIiOiJkNmQ1ZDM3Yy03ZWM5LTQzMjYtOTA2OS1lMDY5NmZiMDE3ZDkiLCJuYmYiOjE3Mjc5NjQ5NDksInB1cnBvc2VJZCI6IjVkNmVmMTcwLTRkYzUtNDYzYi1iNWI4LWRhZDYxZmU5YjMwOCIsImlzcyI6ImQ2ZDVkMzdjLTdlYzktNDMyNi05MDY5LWUwNjk2ZmIwMTdkOSIsInVzZXJMb2NhdGlvbiI6IjI2LjIuMTIuMjMiLCJleHAiOjE3Mjg1NjQ5NDksImRub25jZSI6IjEyMzQ1Njc4OTAxMjMiLCJ1c2VySUQiOiJVc2VyMTIzIiwiaWF0IjoxNzI3OTY0OTQ5LCJqdGkiOiJhOWJmZmQ1MS03YzVmLTQ4NzYtYjM5NS1iN2E2OTg4NTE3YmQiLCJMb0EiOiJMT0EzIn0.uVl9OLmzuK10PEwRfVy3MZAgGcoN5EqFIqIYhS3P1JHImeGo9WTToJ8k0FBry1YUUaKB07x2CIVXMeZfwK11Zh9ia2ijFji-SeXWUqgg35zqcNnLm2XyDDoV63NihEDSP6G4ZUGuukb_i1PYNfwNkxVzcrKwTwPFjeKNfcguk8URT2isWOBzOiQlmKBO1iAWBfT2zdfXw7deszOxIagRxO_L-hmZaSSUzl_43m7xqmvDfVUAYDAwPaFAv2xxTOZqActANGZtbhxcjQqyoYYjSTWeJ9BP9ivLMsOkgC9z9ArinXfQogja0CZGp2R7kkIrjd1cI1A6cMSQNUC4D2cJZw Digest: SHA-256=xz6qy1WJWrcsBEeliJUrao6QT0zH119xlq37k1v9/KY= Content-Type: application/json
> 
> GovWay-Transaction-ID: ea0f6835-818b-11ef-8e65-005056ae1884 {"type":"[https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received](https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html%22,%22title%22:%22InteroperabilityInvalidRequest%22,%22status%22:400,%22detail%22:%22Received) request is not conform to the required interoperability profile","govway_id":"ea0f6835-818b-11ef-8e65-005056ae1884"}



Salve, l'errore è:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token non utilizzabile prima della data '2024-10-03_16:15:50.000'
[Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2024-10-03_16:15:49.000'

**Comment by calogeroprovenzano** [comment]
Salve, continuo ad avere lo stesso errore: 

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
"title":"InteroperabilityInvalidRequest",
"status":400,
"detail":"Received request is not conform to the required interoperability profile",
"govway_id":"91b04722-8627-11ef-b29c-005056ae5232"
}

tutti i parametri sembrano correttamente valorizzati, sia content-type che Digest sono corretti. Potrebbe darmi qualche dettaglio in più sulle differenze che voi ricevete dal vostro lato?

Grazie mille
Provenzano Calogero

> Salve, l'errore relativo al govway_id fornito è il seguente: Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni. Header HTTP 'Digest' possiede un valore non corrispondente al messaggio Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by afrontera85** [comment]
Salve,
adesso l'errore è:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token creato nel futuro (data creazione: '+292278994-08-17_09:12:55.807')
 [Header 'Agid-JWT-TrackingEvidence'] Token creato nel futuro (data creazione: '+292278994-08-17_09:12:55.807')

**Comment by calogeroprovenzano** [comment]
> Token creato nel futuro (data creazione: '+292278994-08-17_09:12:55.807')

Salve, 
corretto il problema ma continuo ad avere:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
"title":"InteroperabilityInvalidRequest",
"status":400,
"detail":"Received request is not conform to the required interoperability profile",
"govway_id":"ca51e99c-8631-11ef-86fa-005056ae1884"
}

Potrebbe inviarmi il dettaglio di quanto vi arriva e di quanto vi aspettate?
Grazie mille

**Comment by afrontera85** [comment]
L'errore infatti continua ad essere sempre questo:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token creato nel futuro (data creazione: '+292278994-08-17_09:12:55.807')
 [Header 'Agid-JWT-TrackingEvidence'] Token creato nel futuro (data creazione: '+292278994-08-17_09:12:55.807')

**Comment by calogeroprovenzano** [comment]
Funziona! 
Grazie per il supporto.
Cordialità
Provenzano Calogero
