### ISSUE TITLE
Dubbio su migrazioni tra comuni e anunllamenti

### ISSUE THREAD

**Issue by busaster** [italia/anpr#4680]
Espongo un caso strano per il quale vorrei delle delucidazioni.

Ambiente di produzione

Il Comune di Rondisonone ha effettuato una migrazione per un soggetto residente a Torino con l'operazione ID  1968053874. 
Il Comune di Torino ha ricevuto correttamente la notifica relativa a questa migrazione.
Successivamente, Rondisonone si è accorto di aver inserito una data di decorrenza errata, quindi ha registrato nuovamente il soggetto con l'operazione ID 1968617030, senza però annullare la prima operazione (1968053874). 
Di conseguenza a Torino è arrivata una nuova notifica di migrazione senza che sia presente una notifica di annullamento della precedente migrazione.

Da qui la domanda : è possibile correggere la data di decorrenza di una migrazione senza annullare l'operazione ?
Se sì, con quale servizio ?
Come si deve comportare il comune che riceve le notifiche ?

Grazie

**Comment by azabatta** [comment]
Buongiorno,
abbiamo analizzato la casistica segnalata ed  anche quelle indicate nella issue #4680. 
In tutti i casi segnalati, al ripristino  segue  immediatamente la comunicazione di una nuova mutazione di residenza (nel caso specifico meno di due minuti). 
La procedura di generazione delle notifiche segue la corretta acquisizione in ANPR di un evento anagrafico operando quindi con un leggero ritardo temporale rispetto a quest’ultimo. Ne consegue che per queste casistiche il sistema non riesce a generare la notifica di ripristino perché nel frattempo il cittadino è stato riportato nel comune di immigrazione.
La seconda notifica quindi andrebbe trattata come un aggiornamento dei dati ricevuti nella notifica precedente. 

In generale la data decorrenza residenza può essere modificata con il ws 5014 -  motivo 101, rispettando le regole di congruenza previste dal servizio di seguito riportate.
La data di decorrenza della residenza può essere rettificata soltanto se il cittadino è stato aggiunto in ANPR con il subentro del comune e se il cittadino non ha effettuato dei successivi cambi di residenza; la rettifica sarà possibile anche in presenza di operazioni successive al subentro, ma la data sarà modificata soltanto se minore della data di ultimo aggiornamento APR.

Saluti

**Comment by busaster** [comment]
Giusto per schematizzare con un esempio:

1. ore 12:10 : Il comune A effettua una mutazione di residenza di un cittadino che risiede nel comune B e ANPR genera per il comune B una notifica di mutazione residenza
2. ore 12:15 : il comune A si accorge di aver sbagliato la decorrenza e annulla la mutazione del punto 1. ANPR si segna di dover generale la notifica di annullamento ma non lo fa subito
3. ore 12:16 : il comune A esegue nuovamente la mutazione del punto 1 con una diversa decorrenza. ANPR  genera per il comune B una notifica di mutazione residenza , operazione che blocca la generazione della notifica di annullamento del punto 2 in quanto eseguita "vicino" all'annullamento

È corretto quanto ho descritto sopra ? Se sì, prego di indicarmi dove nella documentazione tecnica sia decritto questo comportamento. Grazie

**Comment by azabatta** [comment]
Sì è corretto. La casistica è emersa  dall'analisi della sua segnalazione. Aggiorneremo la documentazione tecnica.
Saluti

**Comment by busaster** [comment]
Ok, l'importante per noi era avere la certezza del comportamento anomalo. Ne terremo conto nei nostri sviluppi. 
Grazie

**Comment by azabatta** [comment]
grazie a Lei per la segnalazione
