### ISSUE TITLE
[ANPR-Certificazione] Impossibile produrre certificato in ambiente di test nelle lingue SL e DE

### ISSUE THREAD

**Issue by bugaNTL** [italia/anpr#4682]
Buongiorno,

Abbiamo tentato di recuperare certificati in lingua diversa dall'italiano su combinazioni di soggetti e tipi di certificati eterogenei, non riusciamo ad avere una risposta positiva.

Soggetto d'esempio:
```txt

TJ19758OJ | PRMSGT90R20L424X | Cognome nome,   sesso, data e luogo nascita: Primo Soggetto - M - 20.10.1990 -  Trieste (TS) | residente in   comune con doppia lingua (sloveno)

```
In questo caso stiamo cercando un certificato di nascita per la lingua SL e riscontriamo Status 400 ed il messaggio di "Operazione non effettuabile".

```txt

X-Global-Transaction-ID : [6026e6bc66ffcd8aa019bf7f]
GovWay-Transaction-ID : [4928534a-823d-11ef-a04b-005056ae1884]
GovWay-Message-ID : [14552d34-030e-4e8c-8364-b4243b7e5de2]

```
Se non fosse possibile il recupero in lingua diversa dall'IT per questo soggetto potete indicarci delle alternative?

Cordiali saluti.

Constantin Cristian Buga
Notartel

**Comment by azabatta** [comment]
Buonasera, 
il soggetto utilizzato per il test va bene, per ottenere un certificato multilingue è necessario è necessario specificare nella richiesta ambedue le lingue italiano e sloveno.
Saluti
