### ISSUE TITLE
Problema di accesso: Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by AlFe23** [italia/anpr#4683]
Buongiorno,
non appena provo a fare accesso con CNS o altre modalità al portale, appare questo messaggio di errore.

Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica.

Cosa devo fare? Il comune non sa come aiutarmi.

**Comment by Cipcip2** [comment]
Hai risolto ? Anche io sono nella stesa barca

**Comment by sergiogedda** [comment]
Il sistema di login tramite SPID o CNS dovrebbe fare un controllo tra il cod. fiscale legato allo SPID o CNS che sia ed il dato presente su ANPR e restituisce un errore se i due dati non sono esattamente identici. 
Perchè potrebbero essere diversi? 
Magari per errore materiale del comune 
Magari perche' siete nati\e in un comune soppresso eo che ha variato provincia nel tempo e non è stata corretto il cod. fiscale
Magari siete nati all'estero per cui vale lo stesso discorso sopra

Per questo, la dicitura che appare è corretta ed il consiglio è di andare in comune e farvi fare una ricerca su ANPR dall'impiegato, che sicuramente non avrà il vostro "blocco" e sistemate subito il problema.
Problema che, in teoria, avreste anche se vi recate presso il vostro comune a fare la carta d'identità elettronica che dovrebbe fare lo stesso test che fa ANPR in fase di login
