### ISSUE TITLE
C019-serviceAssessmentExistenceLife-approvazione_automati versions

### ISSUE THREAD

**Issue by andrewcondell** [italia/anpr#4685]
I am working on calling this e service. 

I can see the yaml and url for for v1 but cannot see the v2 . Is the yaml the same and I just update the endpoint to v2?

![versions](https://github.com/user-attachments/assets/dd5fed14-591d-4c3a-9389-8880ced6c0dc)

**Comment by afrontera85** [comment]
Hi! for v2 yaml and url are the same as v1

**Comment by andrewcondell** [comment]
Thats great, thank you afrontera85 for the prompt response!
