### ISSUE TITLE
400 error on C019-serviceAssessmentExistenceLife-approvazione_automati versions

### ISSUE THREAD

**Issue by andrewcondell** [italia/anpr#4687]
Hello,

I am trying to hit the anpr-service-e002 endpoint but am getting a 400 error saying [detail, Received request is not conform to the required interoperability profile].

I have set up the various users, crypto, requests, goals & e-service clients on production PDND.

I use the create_client_assertion.py to generate the client assertion token. I specify the audience in the client assertion token to be 
"aud": "**auth.interop.pagopa.it/client-assertion**"

The voucher token returns with an audience of "aud": "**https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1**"

I scaffold an API in C# using the yaml file and specify that the PROD address '**https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1**' be used. I pass the voucher token  "access_token" property into the "Bearer" Authorization header.

I can see there is a mismatch between the endpoint im targeting and the aud returned in the voucher. 

So my questions are
1 - have i specified the correct aud in the client assertion token?
2 - is the aud returned in the voucher token correct?
3 - is the production endpoint i have specified correct?
4 - is the Bearer Authorization header all that is required?
5 - if there are more headers required is there any documentation available to describe them>

**Comment by afrontera85** [comment]
Hi!
aud is correct. 
The PROD url is: https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
In the issue https://github.com/italia/anpr/issues/4488 we have provided an example java client where you can see the correct implementation of the safety frame. 
The reference document is 
[Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf](https://github.com/user-attachments/files/17324168/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf)

**Comment by andrewcondell** [comment]
Hi afrontera85

Thank you very much for the clarification and pointing me to the example java client

I have updated the java client to call the CO19 endpoint and am still receiving the "received request is not conform to the required interoperability profile"

Im using the below properties and receiving this error
baseurlapi=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=--------------
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd=------------
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalità es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd=-----------

audPdnd=auth.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.interop.pagopa.it
#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/

I have also ported the java client to c# (my companies preferred language) and am getting the same error.

Is there any way to get more detailed error messages out of the calls? The transaction Ids are returned (below) but figuring out what is the exact problem is quite difficult. Even if you could tell me the issue with the 2 below calls would be helpful!

java client error - GovWay-Transaction-ID: d8475da8-8a35-11ef-bab7-005056ae091b
c# client error - GovWay-Transaction-ID: 197b4285-8a36-11ef-b0b2-005056ae21f8

**Comment by afrontera85** [comment]
java client error - GovWay-Transaction-ID: d8475da8-8a35-11ef-bab7-005056ae091b
Error is:
ModI verification of the request failed: 2 exceptions encountered.
Token containing an invalid 'aud' claim
[Header 'Agid-JWT-TrackingEvidence'] Token containing an invalid 'aud' claim

audTokenAgidJwtSignature correct is **https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1**

c# client error - GovWay-Transaction-ID: 197b4285-8a36-11ef-b0b2-005056ae21f8
Error is:
ModI 'INTEGRITY' security token validation of the request failed: 4 exceptions encountered.
HTTP header 'Digest' present in a request with empty http payload
HTTP header 'Digest' has a value that does not match the message
HTTP header 'digest' has a different value than the one in signed headers
HTTP header 'content-type' has a different value than the one in signed headers

**Comment by andrewcondell** [comment]
Hi afrontera85,

Thank you very much for the prompt response! I now have the java client connecting successfully.

I have made the changes to my c# client but am still getting the same error.

Could you please provide the errors for transaction 2edc4ae5-8afe-11ef-af02-005056ae21f8 please?




Could you provide the error for call b6e24119-8afb-11ef-858e-005056ae1d2a please?

**Comment by andrewcondell** [comment]
Thank you very much for the assistance, i now have my c# client working :)
