### ISSUE TITLE
[5008] mutazione attributiSoggetto

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#469]
ambiente di PRODUZIONE - comune di FAENZA

buongiorno

abbiamo aggiornato il flag senzaFissaDimora del soggetto con idSchedaANPR 19133703
la comunicazione inviata è quella con idOperazioneComune 2017003418, e conteneva solo la valorizzazione del senzaFissaDimora
```
<attributiSoggetto>
<senzaFissaDimora>S</senzaFissaDimora>
</attributiSoggetto>
```
il risultato della comunicazione è stato:
- attivazione del senzaFissaDimora
- l'annullamento del soggettoCertificabile

per sanare la posizione, abbiamo ripetuto l'aggiornamento del flag di certiticabilità con idOperazioneComune 2017003422
analogamente abbiamo valorizzato solo il tag soggettoCertificabile
```
<attributiSoggetto>
<soggettoCertificabile>2</soggettoCertificabile>
</attributiSoggetto>
```
ma in questo caso il risultato è stato quello atteso:
- la valorizzazione di soggettoCertiticabile
- nessun annullamento del senzaFissaDimora.

ritengo che il comportamento più corretto sia quest'ultimo.
è possibile verificare ed avere un riscontro su quanto successo con l'idOperazioneComune 2017003418?

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
Buongiorno stiamo verificando. Le facciamo sapere appena possibile
Grazie per la segnalazione

**Comment by asqueglia** [comment]
Abbiamo corretto il bug segnalato. La fix è disponibile negli ambienti esposti. Grazie per la segnalazione.
