### ISSUE TITLE
Errore 400 C015-servizioAccertamentoGeneralita InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by marcoantinori** [italia/anpr#4692]
Stiamo provando il servizio in oggetto in ambiente di produzione, seguendo le specifiche contenute nello yaml del servizio (richiesta voucher con client-assertion che contiene il digest del tracking-evidence, più header Digest, Agid-JWS-Signature, Agid-JWT-TrackingEvidence)

la richiesta è la seguente

{"testataRichiesta":{"idOperazioneClient":"PDND.123456"},"criteriRicerca":{"codiceFiscale":"NTNMRC74H06E783O"},"datiRichiesta":{"dataRiferimentoRichiesta":"2024-10-15","motivoRichiesta":"PDND.123456","casoUso":"C015"}}

L'errore che riceviamo è questo

{
	"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
	"title": "InteroperabilityInvalidRequest",
	"status": 400,
	"detail": "Received request is not conform to the required interoperability profile",
	"govway_id": "5637cc4c-8ad1-11ef-af02-005056ae21f8"
}
potete indicarci cosa stiamo sbagliando?

Grazie

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id fornito è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 3 eccezioni.
Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

**Comment by marcoantinori** [comment]
Buongiorno,

ora il formato signed_headers dovrebbe essere corretto

```
"signed_headers": [
    {
      "digest": "SHA-256=ZjdmMzY5NzM4OTY2ZDZhZjM0ZmFhMzdmODBmOTRjMDc4M2RkNzJjZWRjNjhjYWFkMTZiN2Q3ZGQ3NDYzNzIwZg=="
    },
    {
      "content-type": "application/json"
    }
  ]
```


ma ho ancora un errore:
```
{
  "type": `"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",`
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "e00bc961-8ba8-11ef-a4ad-005056ae21f8"
}
```

potete darmi indicazioni sul govway_id?

Grazie

**Comment by afrontera85** [comment]
Salve,
ora l'errore è solo questo:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by afrontera85** [comment]
L'errore è questo: 
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token creato da troppo tempo (data creazione: '2024-10-16_14:49:18.000')
 [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-10-16_14:49:18.000')

**Comment by marcoantinori** [comment]
Ho provato adesso un'altra chiamata ma ho sempre errore

{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "f98c2d38-8c6a-11ef-8efb-005056ae1d2a"
}

**Comment by afrontera85** [comment]
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
 Token creato da troppo tempo (data creazione: '2024-10-17_09:38:27.000')
 [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-10-17_09:38:27.000')

**Comment by marcoantinori** [comment]
Ho corretto l'errore relativo all'istante di creazione del token ma ho ancora questo errore
"govway_id":"8342ee6b-8d26-11ef-9e0c-005056ae6555"

Utilizzando il client Java invece ho questo errore

"govway_id":"522cbffc-8d27-11ef-842b-005056ae1d2a"

Grazie per la collaborazione

**Comment by afrontera85** [comment]
"govway_id":"8342ee6b-8d26-11ef-9e0c-005056ae6555":
Token creato nel futuro (data creazione: '2024-10-18_10:08:27.000')

"govway_id":"522cbffc-8d27-11ef-842b-005056ae1d2a"
Verifica ModI della richiesta fallita: Riscontrate 4 eccezioni.
Token non utilizzabile prima della data '2024-10-18_10:10:49.000'
Token creato nel futuro (data creazione: '2024-10-18_10:10:49.000')
[Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2024-10-18_10:10:48.000'
[Header 'Agid-JWT-TrackingEvidence'] Token creato nel futuro (data creazione: '2024-10-18_10:10:48.000')

**Comment by marcoantinori** [comment]
Grazie per la disponibilità, sono riuscito ad effettuare una chiamata con successo.

**Comment by marcoantinori** [comment]
risolto
