### ISSUE TITLE
C031-servizioVerificaIdUnicoNazionale - InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by Davide-Almaviva** [italia/anpr#4693]
Buongiorno,

Stiamo riscontrando degli errori sull'eService in oggetto effettuando gli stessi identici test (anche da stesso client) eseguiti solo qualche settimana fa. Vedere precedente ticket [#4677](https://github.com/italia/anpr/issues/4677) per cui tutto alla fine risultava funzionante.
Come se fosse cambiato qualcosa lato GovWay o erogatore ANPR. Possibile ?

Lato chiamata sono presenti tutti gli header previsti: 
![image](https://github.com/user-attachments/assets/29deabc5-553e-4701-ad4b-a622a0bd9552)

Di seguito tutti i dettagli.
Per favore potete verificare ? E' cambiato qualcosa ?

Grazie.
D.

---------------------------------------

**Data di invio**: 2024-10-16

**Errore ricevuto**:
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "ffe7fae7-8bb1-11ef-b563-005056ae5232"
}
```

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id fornito è:
Token non utilizzabile prima della data '2024-10-16_14:15:47.000'

**Comment by Davide-Almaviva** [comment]
Buondì,

Com'è possibile ?
Nel ticket [#4673](https://github.com/italia/anpr/issues/4673) avevamo discusso proprio questa possibilità a causa errore apparentemente analogo su GovWay. Prego verificare discussione in merito.
Ma avevamo concluso e concordato che un disallineamento dei timestamp tra client (consumer) e server (api ANPR), sebbene possibile per ragioni tecniche sui server, sarebbe stato compreso su un max di 3s e in ogni caso non sarebbe "cresciuto nel tempo". Da qui l'idea di "falsificare" un attimo claims come "iat" e "nbf" ed adottare la cosa come workaround.

Per favore potete indicarci in modo puntuale quanti secondi "prima" ricevete il token ?
Ovvero *timestamp quando arriva la request - *timestamp nel token stesso .
A questo punto mi aspetto che non sia più dell'ordine dei ms come visto in passato ... ma di secondi pieni.

Se così fosse, come la risolviamo una volta per tutte ?
Generiamo token letteralmente per "ieri" con -24h di timestamp ?
Poi GOvWay o la PDND non bloccano per questioni di sicurezza ?

Grazie al solito per il supporto.
D.

**Comment by afrontera85** [comment]
il token aveva validità dalle 2024-10-16_14:15:47.000 ed è arrivato a noi alle 2024-10-16 14:15:46.344

**Comment by Davide-Almaviva** [comment]
Ok grazie per il feedback.

Proviamo a mettere indietro il timestamp di 1m, sperando questa possa bastare.
