### ISSUE TITLE
C030-servizioAccertamentoIdUnicoNazionale: InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by alessandrolorenzetti** [italia/anpr#4695]
Salve,

stiamo implementando un client che effettui la chiamata al servizio C030. A seguito della chiamata avvenuta oggi 17/10/2024, riceviamo la seguente risposta:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "81539f15-8c83-11ef-9f29-005056ae5232"
}

potreste gentilmente verificare cosa c'è di sbagliato nei dati che vi inviamo?

Grazie mille in anticipo.
Alessandro Lorenzetti

**Comment by alessandrolorenzetti** [comment]
add info: ambiente della prova effettuata è collaudo

https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C030-servizioAccertamentoIdUnicoNazionale/v1/anpr-service-e002

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id fornito è il segunte:

**Comment by gianpopes** [comment]
> Salve, l'errore relativo al govway_id fornito è il segunte: Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

salve , segnaliamo che stiamo riscontrando da ieri pomeriggio anche noi la stessa problematica.
potrebbe essere un problema generalizzato?

**Comment by afrontera85** [comment]
> > Salve, l'errore relativo al govway_id fornito è il segunte: Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio
> 
> salve , segnaliamo che stiamo riscontrando da ieri pomeriggio anche noi la stessa problematica. potrebbe essere un problema generalizzato?
> 
> aggiungo che fino a ieri andava tutto perfettamente, ora abbiamo questo problema su tutti i servizi chiamati. es { "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html", "title": "InteroperabilityInvalidRequest", "status": 400, "detail": "Received request is not conform to the required interoperability profile", "govway_id": "8d3c5b03-8d44-11ef-bfb3-005056ae5232" }

Salve,
voi prendete un errore sul kid:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Signature verification failed: [COMPACT] Signature verification failure: Process 'kid' error: Retrieve remote key 'wECQbOLRGekd1K4QcrX83fI10m1dPfU70SDr0S7NS5s' failed: Retrieve external resource 'https://govway-anpr-val.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/api-pdnd/v1/keys/wECQbOLRGekd1K4QcrX83fI10m1dPfU70SDr0S7NS5s' failed: (http code: 404): <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api-gateway/1.0/keys/wECQbOLRGekd1K4QcrX83fI10m1dPfU70SDr0S7NS5s</pre>
</body>
</html>

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id indicato è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token creato da troppo tempo (data creazione: '2024-10-22_08:53:46.000')
 [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-10-22_08:43:03.000')

**Comment by alessandrolorenzetti** [comment]
Perfetto grazie
