### ISSUE TITLE
Errore 400 - ANPR-PDND C020-servizioAccertamentoResidenza - anpr-service-e002

### ISSUE THREAD

**Issue by fab956** [italia/anpr#4696]
Buongiorno,
Potreste cortesemente indicarmi la causa dell'errore restituito da una richiesta di test effettuata verso il servizio ANPR della piattaforma di collaudo PDND per il servizio [C020-servizioAccertamentoResidenza](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002)?

L'errore restituito è il seguente
```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "2f5b8582-8c89-11ef-89a4-005056ae1884"
}
```

Grazie e cordiali saluti

**Comment by afrontera85** [comment]
Salve,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Riscontrate 2 eccezioni.
Claim 'signed_headers' con un formato non valido; atteso un array
Header HTTP 'Digest' non presente nella lista degli header firmati (token claim 'signed_headers')

**Comment by fab956** [comment]
Risolto. Grazie
