### ISSUE TITLE
C008-servizioVerificaDichResidenza:  InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by rpraolini** [italia/anpr#4698]
Salve,
stiamo implementando la chiamata al servizio C008. 
A seguito della chiamata avvenuta oggi 21/10/2024, abbiamo questa risposta:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "fb92b7dc-8faf-11ef-90cc-005056ae5232"
}

ci sapete indicare che tipo di errore incontriamo?
Grazie mille
roberto

**Comment by afrontera85** [comment]
Salve,
l'errore relativo al govway_id indicato è il seguente:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
Token contenente un claim 'aud' non valido
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by rpraolini** [comment]
Grazie, 
abbiamo sistemato, ora funziona correttamente.
