### ISSUE TITLE
COLLEGAMENTO URGENTE CODICI FISCALI PER CURE MEDICHE

### ISSUE THREAD

**Issue by LORELLAB** [italia/anpr#4699]
Abbiamo iscritto la persona con numero individuale ANPR  500673692 con Codice fiscale numerico come da permesso di soggiorno ma alla stessa è stato anche attribuito un alfanumerico  come risultato da omocodia quando non era ancora residente . Aprendo la pagina di ANPR per soluzione disallineamenti trovo la casella "collega" già biffata e cliccando conferma il risultato è Esito AE: Operazione non effettuabile (Codice 95)
Nella parte sottostante ci sono altri due codici fiscali gia collegati
Il problema è che la signora ha urgente bisogno di cure ma l'ASL che dice di non riuscire a iscriverla per il problema codice fiscale....

**Comment by frmariani** [comment]
Buongiorno,
la Direzione Centrale di Agenzia delle Entrate deve collegare il numerico all'alfanumerico; siamo in collegamento con loro per la risoluzione del problema. Dopo il collegamento, nel caso fosse necessario, possiamo intervenire.
Saluti

**Comment by frmariani** [comment]
i codici fiscali sono stati collegati dalla DCAE.
adesso potete effettuare la mutazione dei dati anagrafici in ANPR inserendo il CF alfanumerico.
Fatemi sapere se è chiara l'operazione che deve essere effettuata.
