### ISSUE TITLE
Web App - Stampa scheda individuale - Codice Fiscale e ID ANPR del soggetto

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#47]
Ambiente di test – 20/03/2017

A seguito dell’operazione ID 441291, è stato iscritto il soggetto ID ANPR 3876237  con codice gestione CF “Iscrizione/modifica senza validazione CF”. 
Correttamente è stata restituita l’anomalia EN141 “Soggetto non validato”, visibile anche da “Consultazione scheda individuale”.
Invece, nella stampa della scheda individuale del soggetto, il codice fiscale risulta indicato con validità CF “Posizione inesistente (Soggetto non presente in AT)”, mentre potrebbe essere più corretto riportare “Non validato”.
Potrebbe inoltre essere utile integrare le informazioni elencate con l’ID ANPR del soggetto.
Grazie,
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Nella stampa viene riportata una informazione di maggior dettaglio che spiega il motivo della mancata validazione.
Aggiungiamo idANPR (e id comune)
