### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by GigiMas** [italia/anpr#4701]
Buongiorno,
Non molto tempo fa avevo un normale accesso al portale, ora appare questo messaggio di errore.

Codice fiscale: MSPLGU43P0____

![Immagine](https://github.com/user-attachments/assets/9b13e1e1-f1f1-43a7-9547-97dc8ab9167a)

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
