### ISSUE TITLE
[C030] servizioAccertamentoIdUnicoNazionale -InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by gianpopes** [italia/anpr#4703]
Salve , da venerdi scorso nel fare le chiamate al servizio in questione riceviamo un errore HTTP 400 InteroperabilityInvalidRequest

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "68cc3c5a-9060-11ef-a037-005056ae5232"
}

in passato ci era stato risposto che l'erroe era sul "kid" per un problema simile.
Se è lo stesso problema, fateci sapere per cortesia di preciso cosa correggere nelle nostre chiamate e\o nella nostra configurazione se appunto siamo noi ad originarlo.

grazie

**Comment by gianpopes** [comment]
la chiamata di esempio

{
    "idOperazioneClient": "1",
    "criteriRicerca": {
         "codiceFiscale": "STTSGT90A01H501J"
    },
    "datiRichiesta": {
        "dataRiferimentoRichiesta": "2024-10-21",
        "motivoRichiesta": "Pratica n11",
        "casoUso": "C030"
    }
}

**Comment by afrontera85** [comment]
L'errore relativo al govway_id indicato è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' presente in una richiesta con http payload vuoto

**Comment by gianpopes** [comment]
> L'errore relativo al govway_id indicato è il seguente: Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' presente in una richiesta con http payload vuoto

salve , mi sono appena accorto che non inviavamo header Content-Length. Inviando quell'info, il servizio risponde correttamente. Grazie e scusate per l'entropia.
