### ISSUE TITLE
C020-servizioAccertamentoResidenza-approvazione_automatica restituisce 404 Not Found

### ISSUE THREAD

**Issue by lgiovacchini** [italia/anpr#4706]
Buongiorno, stiamo provando a contattare l'endpoint di test https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/anpr-service-e002 del servizio **C020-servizioAccertamentoResidenza-approvazione_automatica** da un applicativo realizzato in C# (.NET 8) ma otteniamo il seguente errore:

```
{
  StatusCode: 404, 
  ReasonPhrase: 'Not Found', 
  Version: 1.1, 
  Content: System.Net.Http.HttpConnectionResponseContent, 
  Headers:
  {
    X-Global-Transaction-ID: 6026e6bc671b9bd1d9c6b69f
    X-Backside-Transport: FAIL FAIL
    Connection: close
    Content-Type: application/problem+json
  }
}
```

Prima di effettuare la richiesta al servizio abbiamo ottenuto correttamente il **voucher** da PDND e lo abbiamo aggiunto agli header della richiesta rivolta al servizio C020, in aggiunta all'header **Agid-JWT-TrackingEvidence** (a cui abbiamo assegnato come valore il token delle client credentials) e a **Agid-JWT-Signature** a cui abbiamo associato un token generato con questo metodo:

```
public static string GetAgidJwtSignature(string digest, string clientId, string idToken, string aud, string privKey, string kid)
{
    long currentTimeInSecs = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds();
    long expiration = currentTimeInSecs + 600000;

    string privateKeyContent = privKey
        .Replace("\n", "")
        .Replace("-----BEGIN PRIVATE KEY-----", "")
        .Replace("-----END PRIVATE KEY-----", ""); ;

    byte[] privateKeyBytes = Convert.FromBase64String(privateKeyContent);
    using RSA rsa = RSA.Create();
    rsa.ImportPkcs8PrivateKey(privateKeyBytes, out _);

    var claims = new Dictionary<string, object>
    {
        { "jti", idToken },
        {
            "signed_headers", new[]
            {
                new Dictionary<string, string> { { "digest", "SHA-256=" + digest } },
                new Dictionary<string, string> { { "content-type", "application/json" } }
            }
        }
    };

    var tokenDescriptor = new SecurityTokenDescriptor
    {
        Audience = aud,
        Issuer = clientId,
        Subject = new ClaimsIdentity(new[] { new Claim(JwtRegisteredClaimNames.Sub, clientId) }),
        Claims = claims,
        Expires = DateTimeOffset.FromUnixTimeSeconds(expiration).UtcDateTime,
        NotBefore = DateTimeOffset.FromUnixTimeSeconds(currentTimeInSecs).UtcDateTime,
        IssuedAt = DateTimeOffset.FromUnixTimeSeconds(currentTimeInSecs).UtcDateTime,
        SigningCredentials = new SigningCredentials(new RsaSecurityKey(rsa), SecurityAlgorithms.RsaSha256)
    };

    tokenDescriptor.AdditionalHeaderClaims = new Dictionary<string, object>
    {
        { "typ", "JWT" },
        { "kid", kid }
    };

    var tokenHandler = new JwtSecurityTokenHandler();
    var securityToken = tokenHandler.CreateToken(tokenDescriptor);
    var signature = tokenHandler.WriteToken(securityToken);
    return signature;
}
```

Stiamo testando sul Comune di Fontanelle.

**Comment by afrontera85** [comment]
Buongiorno, vi consiglio di dare un'occhiata al client java che abbiamo messo a disposizione  come esempio nella issue https://github.com/italia/anpr/issues/4488.
In generale il 404 si prende quando
•	Non ci si presenta con il voucher pdnd nella richiesta (nell’ attributo authorization)
•	Il voucher nella richiesta non è valido
•	Non si sta chiamando la url giusta (o metodo http sbagliato)

**Comment by lgiovacchini** [comment]
@afrontera85 Grazie mille,, abbiamo sistemato un po' di cose e adesso riusciamo a raggiungere il server ma otteniamo un 400:

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"68358852-9547-11ef-9c3a-005056ae5232"}`

Sarebbe possibile avere informazioni sulla validazione che sta fallendo?

Grazie in anticipo

**Comment by afrontera85** [comment]
Salve,
l'errore è il seguente:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'content-type' possiede un valore differente rispetto a quello presente negli header firmati

**Comment by lgiovacchini** [comment]
Buongiorno @afrontera85 , 
grazie di nuovo per la risposta. Abbiamo adeguato il valore dell'header, e ispezionando il token di integrity ora il valore di "Content-Type" nei signed headers corrisponde a quello degli header del content della richiesta HTTP ("application/json; charset=utf-8"), tuttavia continuiamo a ricevere 400:

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"b34cdc60-95e6-11ef-a6b5-005056ae1884"}`

Sono forse scattate altre validazioni?

Grazie in anticipo

**Comment by afrontera85** [comment]
Verifica ModI della richiesta fallita: Riscontrate 3 eccezioni.
[Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido
 [Header 'Authorization'] Token non contiene il claim 'digest.alg'
[Header 'Authorization'] Token non contiene il claim 'digest.value'

**Comment by lgiovacchini** [comment]
> Verifica ModI della richiesta fallita: Riscontrate 3 eccezioni. [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido [Header 'Authorization'] Token non contiene il claim 'digest.alg' [Header 'Authorization'] Token non contiene il claim 'digest.value'

@afrontera85 abbiamo operato qualche modifica, riceviamo sempre 400 ma stavolta abbiamo settato il claim digest.alg, digest.value e abbiamo sistemato l'audience:

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"339a168c-9649-11ef-a8bb-005056ae1884"}`

**Comment by afrontera85** [comment]
Validazione security token ModI 'INTEGRITY' della richiesta fallita: 
Signature verification failed: [COMPACT] Signature verification failure: Non è stato trovato alcun header che consentisse di recuperare il certificato per effettuare la validazione

**Comment by lgiovacchini** [comment]
@afrontera85 abbiamo provveduto ad aggiungere l'header "x5c" negli header della tracking signature e della jws, ma continuiamo ad avere 400:

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0ab8a513-9a87-11ef-91af-005056ae5232"}`

**Comment by afrontera85** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita: Riscontrate 2 eccezioni.
[Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'userID'
 [Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'userLocation'

**Comment by lgiovacchini** [comment]
Ok, abbiamo sistemato userId e userLocation nella tracking signature, continua però a dare 400

`{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"324b5a86-9a8d-11ef-a74b-005056ae1884"}`

**Comment by afrontera85** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita: [Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'userLocation'

**Comment by lgiovacchini** [comment]
Perdonami, avevo incollato il json sbagliato, questo è quello di risposta dopo l'intervento di aggiunta di userID e userLocation:

`ype":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"719add9a-9a8f-11ef-a74b-005056ae1884"} `

**Comment by lgiovacchini** [comment]
Ok ci sono dei progressi, adesso la richiesta sembra strutturata correttamente ma riceviamo un 502

`{"type":"https://govway.org/handling-errors/502/InvalidResponse.html","title":"InvalidResponse","status":502,"detail":"Invalid response received from the API Implementation","govway_id":"f8d15e1e-9a95-11ef-91af-005056ae5232"}`

Stiamo lavorando con i codici fiscali di test riportati qui [casi di test.xlsx](https://github.com/user-attachments/files/17616948/casi.di.test.xlsx), non so se può essere quello

**Comment by afrontera85** [comment]
Potreste riprovare intanto valorizzando adeguatamente dataRiferimentoRichiesta? Ci risulta questa:   "YYYY-11-DD"
