### ISSUE TITLE
Errore Interrogazione Anpr Servizio 3002 - Cod: Timeout

### ISSUE THREAD

**Issue by jonnyfx95** [italia/anpr#4708]
Buonasera, 

Diversi enti ci stanno segnando che l'ambiente di produzione ANPR non sta funzionando.
Riceviamo il seguente errore:

Errore Interrogazione Anpr Servizio 3002 - Cod: Timeout - There was no endpoint listening at
https://ws.anpr.interno.it/ANPR3000ServiziConsultazione/AnprService3000
that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.

Anche i nostri abbienti di TEST non stanno funzionando

Si chiede una verifica

**Comment by siscomanpr** [comment]
Anche alcuni nostri clienti ci hanno segnalato problemi, ma sembra che adesso siano stati risolti.
Anche l'ambiente di test ha ripreso a funzionare.
