### ISSUE TITLE
C024 non ritorna idAnpr del padre

### ISSUE THREAD

**Issue by CarloBertuletti** [italia/anpr#4709]
Buongiorno.
Sto chiamando il servizio C024 tramite idAnpr; ma nel campo "paternita" mi vengono restituiti i dati del padre ma non il CF o l'IdAnpr

Ecco la risposta

{
	"listaSoggetti": {
		"datiSoggetto": [
			{
				"generalita": {
					"codiceFiscale": {
						"codFiscale": "CF RELATIVO ALL'IDANPR DELLA RICHIESTA",
						"validitaCF": "1"
					},
					"cognome": "XXXXXXXXXX",
					"dataNascita": "AAAA-MM-GG",
					"idSchedaSoggettoANPR": "888888888",
					"luogoNascita": {
						"comune": {
							"codiceIstat": "1234567",
							"nomeComune": "XXXXXXXX",
							"siglaProvinciaIstat": "XX"
						}
					},
					"nome": "XXXXXX",
					"sesso": "X"
				},
				"paternita": {
					"generalita": {
						"cognome": "YYYYYYYYY",
						"luogoNascita": {
							"comune": {
								"codiceIstat": "1234567",
								"nomeComune": "YYYYYY",
								"siglaProvinciaIstat": "YY"
							}
						},
						"nome": "YYYYYYYYYYYY"
					}
				},
				"identificativi": {
					"idANPR": "AEZZZZZZZZ"   ==> è l'IdAnpr del richiedente
				}
			}
		]
	},
	"idOperazioneANPR": "111111111"
}

Cosa sto sbagliando ?

**Comment by azabatta** [comment]
Buonasera, 
a quale ambiente si riferisce la segnalazione? 
In esercizio i dati restituiti dal sistema sono quelli comunicati dal comune o in fase di ingresso nel sistema ANPR (subentro) oppure in fase di inserimento/aggiornamento della scheda anagrafica di un cittadino. Le sezioni "paternità " e "maternità" non sono obbligatorie se non per nuove iscrizioni per nascita. Potrebbero quindi mancare oppure essere limitate solo ad alcuni dati come nome- cognome.

**Comment by CarloBertuletti** [comment]
Buongiorno.
Mi riferivo all'ambiente di produzione.
La sua risposta ha chiarito la problematica e a ben pensarci non poteva che essere così; il dato è presente se il comune l'ha comunicato.
Grazie.
