### ISSUE TITLE
Indirizzo nei certificati - Manca la frazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#471]
Comune di Lucca - Produzione
L'indirizzo di certificazione non riporta la frazione
Ad esempio il certificato con protocollo 1594376 di seguito al numero civico dovrebbe riportare la frazione "TEMPAGNANO DI LUNATA"
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Più d'un cliente lamenta questa mancanza che riscontro anche oggi.
E' previsto un intervento risolutivo?
Grazie.
Filipazzi - Maggioli

**Comment by patriziasaggini** [comment]
Buongiorno,
il Comune di Valsamoggia è subentrato all'inizio di luglio: il Comune è stato costituito dal 1/1/2014 in seguito ad una fusione di 5 Comuni, quindi il territorio è suddiviso in 5 Municipi;
visto che ci sono parecchie denominazioni uguali di vie, per il Comune è essenziale che venga mantenuto e gestito il dato del Municipio di riferimento.
Abbiamo notato dopo il subentro che il dato del Municipio NON viene gestito nè per il rilascio della CIE, nè per la certificazione anagrafica e per le visure, e nè per i dati comunicati all'Agenzia delle Entrate, quindi abbiamo urgenza che sia trovata una soluzione a breve (è probabile che - ad esempio - le comunicazioni di attribuzione di codice fiscale a nuovi nati non vengano recapitate nel modo corretto).

Quali sono i tempi previsti per il rilascio della modifica?
Grazie

**Comment by RENZO63** [comment]
La soluzione prospettata dal Comune di Valsamoggia cozza con le disposizioni attuali dettate dall'ISTAT
Infatti la presenza di piu' localita' o frazioni o municipi non consente di avere toponimi duplicati all'interno dello stesso Comune.
L'unica alternativa e' quella di modificare il dug  ad esempio da   Via Roma  a  Corso Roma e cosi' via.
Riporto il testo delle note ISTAT (ricordo che poi le vie vanno certificate nell'archivio delle aree di circolazione e dei numeri civici sul sito del catasto secondo le regole istat).


NOTE DI CARATTERE GENERALE RELATIVE ALLA COMPILAZIONE DELLO STRADARIO 
(rif. Circolare Istat n. 912/2014/P del 15 gennaio 2014) 
(rif. Regolamento Anagrafico - D.P.R. 30 maggio 1989, n. 223 - Istruzioni per l’ordinamento ecografico
 di onomastica stradale e numerazione civica) 

...omissis....

35.
Toponimi duplicati 
L'art. 41, comma 5 del Regolamento anagrafico D.P.R
. 30 maggio 1989, n.223, recita: 
"Nell'ambito  del  territorio  comunale  non  può  essere
  attribuita  una  stessa  denominazione  ad  aree  di 
circolazione dello stesso tipo, anche se comprese i
n frazioni amministrative diverse." 
Pertanto, per risolvere i casi di duplicazione il Comune dovrà deliberare nuove denominazioni o cambiare la specie (dug) a una delle aree di circolazione duplicate. La stessa denominazione infatti la si può usare per specie diverse di area di circolazione, come ad esempio: 
•
VIA ANTONIO GRAMSCI 
•
PIAZZA ANTONIO GRAMSCI 
IMPORTANTE: L’inserimento della denominazione della
 località, non rende comunque il toponimo univoco, 
poiché  la  denominazione  di  quest’ultimo  deve  essere
  riferita  all'intero  territorio  comunale  e  non  a 
sottoinsiemi di esso. La località indica l'ubicazione dell’area di circolazione (prevista nel mod. A/P
 8 del Regolamento Anagrafico) e non fa parte in alcun modo della denominazione del toponimo.

**Comment by patriziasaggini** [comment]
Grazie dell'indicazione, ma nel frattempo sarebbe opportuno che il dato fosse comunque visualizzato correttamente in ANPR.

**Comment by patriziasaggini** [comment]
Preciso anche che qualsiasi dato presente in anagrafe deve essere oggetto di certificazione, quindi - visto che il dato è stato trasmesso correttamente in fase di subentro - correttamente deve essere gestito e trattato nelle operazioni conseguenti.

**Comment by RENZO63** [comment]
COMUNE DI VALLE MOSSO - PRODUZIONE

Dal momento che il mio comune sara' probabilmente oggetto di fusione il 1/1/19 (referendum l'11 novembre) mi trovero' in una situazione analoga a quella di Valsamoggia.
Ho dato l'indicazione ISTAT in quanto il problema non sara' solamente di ANPR ma anche e soprattutto della certificazione delle aree di circolazione sul sito apposito.
Sia l'Agenzia del Territorio che l'Istat regionale mi hanno confermato l'impossibilita' di mantenere le aree di circolazione adottando l'escamotage dei municipi o delle frazioni o localita'.
Mi chiedo se Valsamoggia sia riuscita a certificare le vie ed i numeri civici avendo mantenuto intatte le denominazioni delle vie.
Io mi sto apprestando a modificare i soli dug (da via a corso ecc.) in caso di esito positivo del referendum in modo da essere in regola con le disposizioni.
L'indicazione del Municipio o della localita' e' comunque un dato indispensabile in certificazione (ma non per risolvere il problema delle vie duplicate)

**Comment by gcarbonin** [comment]
Questa funzione consente soltanto di specificare se il comune desidera che sui certificati di residenza sia riportata ANCHE la frazione. La funzione in questione è disponibile solo da WA.

**Comment by rvinzani** [comment]
Chiudo la issue in quanto la funzionalità è già da tempo in produzione. In caso siano necessari ulteriori chiarimenti si prega di riaprire una nuova issue che faccia riferimento a questa stessa
