### ISSUE TITLE
Richiesta di fruizione Regione Marche servizi in ambiente di collaudo in stato "attesa approvazione" da oltre 20 giorni

### ISSUE THREAD

**Issue by Joncap2024** [italia/anpr#4712]
Come ente Regione Marche abbiamo inserito la richiesta di fruizione in ambiente di collaudo circa 20 giorni fa per i servizi 
- C002-servizioComunicazione
- C020-servizioAccertamentoResidenza
- C021-servizioAccertamentoStatoFamiglia
- C029-servizioAccertamentoDatiAnagrafici
sono sempre in stato "attesa approvazione", non riusciamo nemmeno a inserire la finalità da agganciare ai servizi. Ovviamente non possiamo avviare alcun test.

Non so se questo è il posto giusto dove inserire la richiesta, sul portale selfcare ho trovato un riferimento ad una mail, ma mi ha indicato di aprire un issue. Quindi chiedo scusa se questo non fosse il canale corretto.

**Comment by azabatta** [comment]
Buongiorno, 
parallelamente alle richieste di fruizione fatte su PDND è necessario inviare un'istanza al Ministero dell'Interno che effettua un'istruttoria sui dati richiesti. 
Inviate una mail al servizio di assistenza  "assistenza.anpr.enti@sogei.it"  vi forniranno la PEC ed il modulo da utilizzare. Preannunciamo l'apertura della segnalazione ai colleghi al fine di rendere più rapida la risposta. 
Buon lavoro
