### ISSUE TITLE
ANPR: Purtroppo non è stato possibile al servizio. Rivolgersi al comune di residenza

### ISSUE THREAD

**Issue by anto1601** [italia/anpr#4713]
In data 30/11/202. ho chiesto l'accesso tramite Spid personale  alla piattaforma ANPR la quale non mi fa accedere al servizio e mi rimanda al comune di residenza(CAPOTERRA) prov. CA   motivando il disservizio che non à stato possibile  individuare in modo univoco la mia scheda anagrafica per una anomalia nei dati.
Mercenaro Antonio  
MRCNTN
Privato cittadino

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
