### ISSUE TITLE
ERRORI, DA OGGI PM, EN493 ,  EN527 e 999 - COMUNE DI RAVENNA 

### ISSUE THREAD

**Issue by edoardodona-1** [italia/anpr#4714]
Scrivo per comune di Ravenna . 
Riferimento : Responsabile back office anagrafe.

Da oggi pm riceviamo spessissimo e su diversi soggetti queste due tipologie di errori: 
( esemplifico qui sotto) : 

<errore>
<codiceErroreAnomalia>EN493</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
La ricerca non produce risultati o l'utente non dispone dei privilegi per eseguire l' operazione sul soggetto/famiglia
</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-10-31 15:37:59 , mittente 039014 , idOperazioneComune 2702576
</testoErroreAnomalia>

<errore>
<codiceErroreAnomalia>999</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
<errore>
<codiceErroreAnomalia>EN527</codiceErroreAnomalia>
<tipoErroreAnomalia>E</tipoErroreAnomalia>
<testoErroreAnomalia>
Informazioni sull'operazione da fornire in caso di assistenza : data 2024-10-31 16:28:15 , idOperazioneANPR 2027257781
</testoErroreAnomalia>

Sono problemi legati al nostro operatore? c'e' qualcosa nei dati inviati relativi ai cittadini che non quadra? o ci sono problemi di altra natura? 

Grazie 

Dona' DatamanagementItalia per Comune Ravenna 
338 59 09 376

**Comment by MoniaPedrazzoli** [comment]
Purtroppo segnalo che anche diversi nostri clienti stanno riscontrando lo stesso problema.

Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by siscomanpr** [comment]
Anche alcuni nostri clienti stanno segnalando lo stesso problema.

**Comment by sfmodena** [comment]
Comune di Modena

Buongiorno,
anche a Modena da giovedì abbiamo errori simili, in particolar modo su pratiche di iscrizione AIRE per nascita riguardanti sia soggetti a cui attribuire il CF sia posizioni che lo hanno già. Per cortesia potete verificare?

Grazie, saluti
Sonia Fiorini

**Comment by PaoloIca** [comment]
Mi accodo e segnalo il medesimo errore, sempre su pratiche aire per molti dei nostri clienti in Veneto e Trentino.

Paolo Ferrarese
Icasystems

**Comment by baldissinn** [comment]
Buongiorno, mi aggiungo come tecnico di Halley Veneto

**Comment by UpiTorino** [comment]
Buongiorno,
segnaliamo lo stesso errore dal comune di Torino.

Elton Myrtolli 
Ufficio Procedure
Torino

**Comment by anprpa** [comment]
Buongiorno, anche al comune di Palermo, da oggi le pratiche AIRE vanno in errore EN493.
Ivana Ragni - SISPI - Comune di Palermo

**Comment by Rianoanagrafe** [comment]
Buongiorno,
pratica mutazione residenza con  iscrizione aire  bloccata con stesso errore EN493.
comune di Riano

**Comment by MarcellaM** [comment]
Buongiorno, Comune di Alessandria riscontro la stessa tipologia di errori relativi alle iscrizioni/mutazioni AIRE.

**Comment by frmariani** [comment]
potete riprovare per favore dandoci un riscontro ? grazie

**Comment by sfmodena** [comment]
Comune di Modena

Buongiorno,
ora funziona.

Grazie, saluti
Sonia Fiorini

**Comment by frmariani** [comment]
Grazie mille

**Comment by migmar68** [comment]
Anche dai primi riscontri di Maggioli, sembra funzionare ora, grazie.

**Comment by UpiTorino** [comment]
Comune di Torino:
Funziona, grazie!

**Comment by baldissinn** [comment]
Confermo, per clienti halley. grazie

**Comment by MarcellaM** [comment]
Confermo il funzionamento. 
Grazie mille 



Città di Alessandria 
Marcella Molinari 

Settore III Politiche di Sviluppo e Innovazione, Sport e Tempo Libero 
Servizi demografici e statistici elettorale 
Ufficio Anagrafe.AIRE 
Tel. 0131-515194 
***@***.*** 
Pec: [ ***@***.*** | ***@***.*** ] 


Avvertenze ai sensi del D.lgs. n. 196/2003 “Codice in materia di protezione dei dati personali” e del Regolamento (UE) 2016/679 “Regolamento Generale sulla Protezione dei Dati” (GDPR): il presente messaggio contiene informazioni attinenti l'attività lavorativa. Le eventuali risposte potranno essere conosciute da altri soggetti nell'ambito dell'organizzazione del mittente. Questo messaggio di posta elettronica ed i suoi documenti sono riservati ed il loro utilizzo è consentito esclusivamente al destinatario del messaggio, per le finalità indicate nel messaggio stesso. Qualora riceveste questo messaggio senza esserne il destinatario, siete invitati cortesemente a darne notizia via e-mail al mittente e a procedere alla distruzione dello stesso cancellandolo dal Vostro sistema. Costituisce comportamento contrario ai dettati del D.Lgs. 196/2003 il trattenere il messaggio stesso, divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, diffonderne comunque il contenuto. 


Da: "migmar68" ***@***.***> 
A: "italia/anpr" ***@***.***> 
Cc: "MarcellaM" ***@***.***>, "Comment" ***@***.***> 
Inviato: Lunedì, 4 novembre 2024 12:41:20 
Oggetto: Re: [italia/anpr] ERRORI, DA OGGI PM, EN493 , EN527 e 999 - COMUNE DI RAVENNA (Issue #4714) 





Anche dai primi riscontri di Maggioli, sembra funzionare ora, grazie.
