### ISSUE TITLE
C019 - errore 404 NotFound su ricerca esistenza in vita

### ISSUE THREAD

**Issue by sommafa** [italia/anpr#4718]
buongiorno,
sull'ambiente di produzione del cliente, otteniamo sempre errore 404 per il servizio C019.
Di seguito, una delle risposte di errore che otteniamo.

```
{ 
	"type": "https://govway.org/handling-errors/404/NotFound.html", 
	"title": "NotFound", 
	"status": 404, 
	"detail": "Unknown API Request", 
	"X-Global-Transaction-ID": "0cc0f75f6728d212c783a10f" 
}
```

Non abbiamo nessun problema in collaudo, sempre dal cliente, e nel nostro laboratorio non riusciamo a replicare un errore di questo tipo.

edit:
questi sono i valori di url e audience che usiamo

```
AudiencePDND             : auth.interop.pagopa.it/client-assertion
EndPointServizio         : https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
AudTokenAgidJwtSignature : https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
UrlTokenPDND             : https://auth.interop.pagopa.it/token.oauth2  
```

Avete modo di darci indicazioni?
grazie

**Comment by Ennio71** [comment]
Prova a vedere qui se può servire #4617
Saluti

**Comment by sommafa** [comment]
@Ennio71 mi sembra che gli url e l'aud siano corretti. O sbaglio?

Anche perché la configurazione, che ho scritto nel post, in laboratorio funziona e abbiamo diversi altri clienti che usano il prodotto nella medesima maniera senza difficoltà.

Grazie
Fabio

**Comment by Ennio71** [comment]
@sommafa non saprei dirti, non faccio assistenza ANPR
Mi ricordavo di un problema simile al tuo e ti ho girato il numero della issue.

Buona giornata

**Comment by sommafa** [comment]
grazie comunque per il tuo intervento.

Saluti,
Fabio

**Comment by afrontera85** [comment]
Le possibili cause del 404 sono:
•	Non vi state presentando con il voucher pdnd nella richiesta (nell’ attributo authorization)
•	Il voucher che state presentando nella richiesta non è valido
•	Non state chiamando la url giusta (o metodo http sbagliato)
