### ISSUE TITLE
Purtroppo non è stato possibile accedere al servizio, 

### ISSUE THREAD

**Issue by Kamranirshad905** [italia/anpr#4719]
Purtroppo non è stato possibile accedere al servizio, ti consigliamo di rivolgerti al tuo comune di residenza (o di iscrizione all'AIRE) per maggiori informazioni, al fine di sanare l'anomalia nei tuoi dati che non ci ha consentito di individuare in modo univoco la tua scheda anagrafica
![Screenshot_2024-11-08-12-22-20-351_com android chrome](https://github.com/user-attachments/assets/f15607ac-0ee4-4e5c-970e-3ee7d8131ebc

First 6 digits of codice fiscale : RSHKRN

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
