### ISSUE TITLE
[5013] TipoRevoca=06(matrimonio) - Tipo revoca non ancora disponibile

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#472]
Buongiorno,
stiamo eseguendo delle prove per quanto riguarda il servizio 5013, nello specifico sulla revoca del matrimonio.
Il richiamo di tale servizio sembra non apportare modifiche alcune ai dati (Ambiente di test - Id Operazione ANPR: 680731), per capire dove stiamo sbagliano abbiamo provato a simulare l'operazione dal portale attraverso la funzione di Registrazione.
La prova ci da come esito "Tipo revoca non ancora disponibile", ad eccezione di paternità(Tipo revoca=1) e maternità(Tipo revoca=2), tutte le altre combinazioni (TipoRevoca da 3 a 9) ci danno come detto "Tipo revoca non ancora disponibile".
Stiamo sbagliando qualcosa noi, oppure questi servizi sono in fase di sviluppo?

Ringrazio anticipatamente,

**Comment by gcarbonin** [comment]
Al momento è attiva soltanto la revoca del dato paternita e maternita
