### ISSUE TITLE
Servizi al Cittadino - Purtroppo non è stato possibile accedere al servizio

### ISSUE THREAD

**Issue by chenpihuamei** [italia/anpr#4720]
gentile signori,

Non riesco ad accedere al portale ANPR, compare sempre questo messaggio di errore Sono in contatto con il Comune di Pineto (TE), non hanno riscontrato problemi con la scheda anagrafica.

Prime 6 cifre del codice fiscale: CHNXNY

Vi ringrazio anticipatamente e invio cordiali saluti.

**Comment by ncapozzi** [comment]
Buongiorno,
come indicato nel messaggio di errore, l'indicazione in questi casi è quella di rivolgersi al comune di residenza o di scrizione all'AIRE che dovrà verificare se il codice fiscale è validato in ANPR e se i dati anagrafici registrati in ANPR sono congruenti con quelli con cui è stato richiesto SPID. In caso il Comune non riscontri problemi, può richiedere assistenza ad ANPR su come procedere tramite i canali loro riservati.
