### ISSUE TITLE
MODIFICA MOTIVO ISCRIZIONE AIRE

### ISSUE THREAD

**Issue by paoloHV** [italia/anpr#4722]
Come si possono rettificare in WEB APP i dati relativo al motivo di iscrizione Aire se errato? ad esempio C02 nascita se in realtà è C05 Acquisto cittadinanza?

**Comment by ncapozzi** [comment]
Buonasera, 
utilizzando una Mutazione dati AIRE con tipo = Dati generali iscrizione
