### ISSUE TITLE
PDND: interfaccia per accesso ad Anpr

### ISSUE THREAD

**Issue by Reg-com** [italia/anpr#4723]
Buongiorno
Alcuni uffici del nostro Comune hanno espresso interesse all’accesso ad ANPR per attività istituzionali come definite nell’allegato 3 della circolare n. 73/2023 del Ministero dell’Interno.
In riferimento all’accesso ad ANPR tramite PDND è necessario dotarsi di idoneo gestionale o esiste un’interfaccia fornita dal Ministero?

Grazie

Milena Reginato
Responsabile Ufficio Servizi Demografici del Comune di Sacile

**Comment by azabatta** [comment]
Buongiorno,
ANPR tramite PDND offre solo servizi e non applicazioni. Dalla PDND si sottoscrivono i servizi di interesse. Per utilizzarli è necessario che l'ente fruitore li integri nei propri sistemi. 
Saluti
