### ISSUE TITLE
Finalità "C020 - approvazione automatica" nello stato di "in attesa di approvazione"

### ISSUE THREAD

**Issue by GianluM67** [italia/anpr#4729]
Buongiorno.
In veste di fornitori di applicativi informatici ai Comuni, da ieri stiamo riscontrando problemi ad ottenere l’approvazione automatica di una finalità associata all’e-service PDND “C020-servizioAccertamentoResidenza-approvazione_automatica”.

In pratica, anche indicando una soglia di interrogazioni molto bassa, lo stato della finalità rimane “in attesa di approvazione”.
Tale comportamento è stato riscontrato presso i Comuni di Bottanuco (BG) e Chioggia (Venezia).

Grazie molte se riuscite a darci qualche delucidazione in merito.

Distinti saluti.
Stesei  /  Gianluca Manzin

**Comment by azabatta** [comment]
Buongiorno, 
effettuiamo una verifica e vi diamo un riscontro. 
Saluti

**Comment by GianluM67** [comment]
Buongiorno.

Il problema è rientrato.
La finalità, naturalmente coerente con la soglia prevista, ora viene immediatamente attivata.
Grazie e cordiali saluti.

**Comment by azabatta** [comment]
Buongiorno, 
in realtà abbiamo innalzato la soglia massima complessiva che era stata sforata. Pensavamo fosse necessaria comunque l'approvazione da parte del Ministero dell'Intero per le finalità cadute in stato "in attesa di approvazione". Per fortuna non è così.
Grazie per il riscontro e buon lavoro
