### ISSUE TITLE
[3003] tipoOperazione 2011

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#473]
ambiente di PRODUZIONE - comune di MEDICINA 

per il soggetto con idSchedaANPR 18947773, sono state inviate, nell'ordine, le seguenti comunicazioni relative alla stessa pratica:
- 2017001505 - (2003) emigrazione 
- 2017001508 - (2011) annullamento emigrazione 
- 2017001511 - (2003) emigrazione 
- 2017001731 - (2011) annullamento emigrazione 
- 2017001734 - (2003) emigrazione 

perchè la consultazione delle operazioni ritorna solo i tipi operazione 2003 e non anche i 2011?

grazie
Alessandro Monopoli ADS

**Comment by cmigliardi** [comment]
stiamo verificando - grazie per la segnalazione

**Comment by cmigliardi** [comment]
a valle dell'intervento, il servizio 3003 riporta tutti gli identificativi delle operazioni eseguite sulla scheda

**Comment by AMonopoliADS** [comment]
grazie Cecilia.
il ws 3003 adesso ritorna anche le operazioni di annullamento (tipi operazione 2011)
