### ISSUE TITLE
Nota ulteriore su issue #4729

### ISSUE THREAD

**Issue by GianluM67** [italia/anpr#4733]
Buongiorno.

Ritorno ancora un attimo sull'issue #4729 appena chiusa per un chiarimento.
In realtà le finalità cadute giorni fa in attesa di approvazione risultavano questa mattina ancora "in attesa di approvazione".
In accordo con il Comune, per non attendere oltre, abbiamo preferito eliminare la finalità in attesa di approvazione e rifarla.
Inserita e pubblicata la nuova finalità, la stessa è stata messa immediatamente nello stato di ATTIVA come previsto.
Ancora grazie e cordiali saluti.

**Comment by azabatta** [comment]
L'automatismo supposto quindi non esiste.
Grazie per la precisazione, è un'informazione molto importante.
Saluti
