### ISSUE TITLE
[876] Non riesco ad accedere al portale ANPR

### ISSUE THREAD

**Issue by ghattas80** [italia/anpr#4735]
gentile signori,

Non riesco ad accedere al portale ANPR, compare sempre questo messaggio di errore Sono in contatto con il Comune di ROMA (RM), non hanno riscontrato problemi con la scheda anagrafica. Mi hanno rilasciato certificato di residenza e carta d'identità elettronica correttamente.
Prime 6 cifre del codice fiscale: BDLMMD
Vi ringrazio anticipatamente e invio cordiali saluti.

**Comment by ghattas80** [comment]
![IMG-20241123-WA0000](https://github.com/user-attachments/assets/b2bc81ef-d88a-4b34-b608-46c0cd0f0f8e)

**Comment by ghattas80** [comment]
Ho controllato il mio codice fiscale dal conto ANPR di mio fratello chi è presente nel stato di famiglia, ho trovato altro codice fiscale. Vi chiedo di aggiornare mia scheda ANPR con il codice fiscale corretto BDLMMD97H05Z33SP . Vi ringrazio per la collaborazione

**Comment by ncapozzi** [comment]
Buonasera,
ci risulta che è riuscito ad accedere correttamente all'area riservata
