### ISSUE TITLE
Richieste di fruizione in attesa di approvazione

### ISSUE THREAD

**Issue by RoccoGallucci** [italia/anpr#4736]
Buongiorno, per conto di regione Basilicata ho effettuato le richieste di fruizione, in ambiente di collaudo, per i seguenti e-service:
C020-servizioAccertamentoResidenza, versione 7
C021-servizioAccertamentoStatoFamiglia, v. 4

Ho scritto la mail al contatto del Ministero dell'Interno presente nel dettaglio dell'e-service e mi ha consigliato aprire un'issue sul repository Github, spero che qualcuno possa indirizzarmi verso la risoluzione della problematica.
Grazie

**Comment by azabatta** [comment]
Buongiorno,
parallelamente alle richieste di fruizione fatte su PDND è necessario inviare un'istanza al Ministero dell'Interno che effettua un'istruttoria sui dati richiesti.
Inviate una mail al servizio di assistenza "[assistenza.anpr.enti@sogei.it](mailto:assistenza.anpr.enti@sogei.it)" vi forniranno la PEC ed il modulo da utilizzare. Preannunciamo l'apertura della segnalazione ai colleghi al fine di rendere più rapida la risposta.
Buon lavoro

**Comment by RoccoGallucci** [comment]
La ringrazio per la tempestiva risposta, procedo ad inviare la mail al servizio di assistenza.
Cordiali saluti


Da: azabatta ***@***.***>
Inviato: martedì 26 novembre 2024 11:18
A: italia/anpr ***@***.***>
Cc: Gallucci Rocco ***@***.***>; Author ***@***.***>
Oggetto: Re: [italia/anpr] Richieste di fruizione in attesa di approvazione (Issue #4736)


Buongiorno,
parallelamente alle richieste di fruizione fatte su PDND è necessario inviare un'istanza al Ministero dell'Interno che effettua un'istruttoria sui dati richiesti.
Inviate una mail al servizio di assistenza ***@***.******@***.***>" vi forniranno la PEC ed il modulo da utilizzare. Preannunciamo l'apertura della segnalazione ai colleghi al fine di rendere più rapida la risposta.
Buon lavoro
