### ISSUE TITLE
Aggiungere la CA Postazioni Svil al trust store

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#474]
Buongiorno, non riusciamo a trovare il download della CA per i vari certificati di test,subentro e postazioni. Ne abbiamo bisogno per avere una catena di certificati valida.
Ringrazio anticipatamente.

**Comment by gcarbonin** [comment]
Dalla WA strumenti di supporto ultimo link della pagina

**Comment by SAlberto** [comment]
Buongiorno, l'ultimo link della pagina permette di scaricare il certificato finale per l'accesso ai web services e non la root certificate authority

**Comment by gife67** [comment]
Buongiorno,
vi allego il certificato di CA Postazioni valido per gli ambienti di Test e PreSubentro
[CAPostazioniSvil.zip](https://github.com/italia/anpr/files/1597083/CAPostazioniSvil.zip)

**Comment by gife67** [comment]
Buonasera,
abbiamo aggiunto un link per il download dei certificati delle CA ANPR in Strumenti di Supporto dell'ambiente di Test.
