### ISSUE TITLE
C020-servizioAccertamentoResidenza

### ISSUE THREAD

**Issue by carlostringaro** [italia/anpr#4740]
Buon pomeriggio,
sto provando a invocare il servizio C020 in ambiente di produzione e ricevo quanto segue:

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "562ff983-b0d2-11ef-af97-005056ae21f8"
}
```

Potreste indicarmi il problema ?

Grazie,
Carlo.

**Comment by carlostringaro** [comment]
Salve,
mi può gentilmente indicare il valore dell'header http Digest e del content-type ricevuto in richiesta ?

Grazie

**Comment by afrontera85** [comment]
avendo fatto la prova in produzione non riesco a vedere queste informazioni di dettaglio della richiesta. 
Vedo solo questo: 
Headers HTTP Firmati:
content-type  application/json
digest  SHA-256=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=

**Comment by afrontera85** [comment]
Per avere queste informazioni dobbiamo attivare dei livelli di log maggiori in ambiente di produzione.
Le chiedo cortesemente di fare i test in ambiente di collaudo

**Comment by afrontera85** [comment]
è rimasto solo l'errore Header HTTP 'Digest' possiede un valore non corrispondente al messaggio

**Comment by carlostringaro** [comment]
Salve,
ho provato a richiedere la fruizione dei servizi C020, C030 e C007 in ambiente di UAT PDND, ma non hanno, tra gli attributi certificati, Pubblica Amministrazione.
Gentilmente, potresti aggiungerlo così da poter avanzare le richieste ?

Grazie

**Comment by carlostringaro** [comment]
Salve,
potresti verificarmi questa gentilmente ?
281306f1-b253-11ef-92f0-005056ae21f8

Grazie.

**Comment by afrontera85** [comment]
> Salve, ho provato a richiedere la fruizione dei servizi C020, C030 e C007 in ambiente di UAT PDND, ma non hanno, tra gli attributi certificati, Pubblica Amministrazione. Gentilmente, potresti aggiungerlo così da poter avanzare le richieste ?
> 
> Grazie

La richiesta è da porre al al ministero dell’Interno, non è di nostra competenza.

**Comment by afrontera85** [comment]
> Salve, potresti verificarmi questa gentilmente ? 281306f1-b253-11ef-92f0-005056ae21f8
> 
> Grazie.

L'errore è sempre lo stesso.
In base al payload, noi ci aspettiamo un determinato digest, che sarebbe l'hash del payload codificato in Base64, ma evidentemente cene arriva uno diverso...
