### ISSUE TITLE
C019-servizioAccertamentoEsistenzaVita: "status":400,"detail":"Received request is not conform to the required interoperability profile"

### ISSUE THREAD

**Issue by gcaferra** [italia/anpr#4742]
Ciao, 
ottengo questo errore 
"govway_id":"197a5638-b245-11ef-9f89-005056ae6555"

potreste darmi qualche info?

**Comment by azabatta** [comment]
Buongiorno, 
di seguito l'errore riscontrato dal sistema:

Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
- Token contenente un claim 'aud' non valido
-  [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

Al fine di velocizzare la verifica per il futuro si prega cortesemente di indicare l'ambiente di riferimento. 
Saluti
