### ISSUE TITLE
C030-servizioAccertamentoIdUnicoNazionale - InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by carlostringaro** [italia/anpr#4744]
Salve,
abbiamo finalizzato la richiesta di fruizione dell'e-service C030 in ambiente di UAT di PDND. Tuttavia, continuiamo a riscontrare il seguente problema:
```
InteroperabilityInvalidRequest
ErrorCode: 400
Received request is not conform to the required interoperability profile
```

I token generati sono i seguenti:
`Audit Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtJZCI6IjZOYmdkbXFFdlM1X2ROT1pOd3JvZGpOMEkyLThpSTVfNllYSUpNQllGb28ifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJuYmYiOjE3MzM3MzYxMzUsInB1cnBvc2VJZCI6IjUyODZhMjNlLTNlMDItNDc3MC04NTQ3LTdhOGNiYWRkZjk2MCIsInVzZXJMb2NhdGlvbiI6IjAuMC4wLjAiLCJleHAiOjE3MzM3MzYyNTUsInVzZXJJRCI6InN1Zm8iLCJkbm9uY2UiOjEyMzQ1Njc4OTEyMzQsImlhdCI6MTczMzczNjEzNSwiY2xpZW50X2lkIjoiNjIzMmNhNDUtYzU0OC00ZjY0LWIxNjAtMmNlMWI4YjMxMzQ0IiwianRpIjoiZTQ5MzM4NDgtN2JjZi00OTMyLTllZTItZDc4YjMzMGZkZGQzIn0.nVJjFIaltBa2n7ZiwlALLStlv5zdtj9NP_EVUoRraUHZyZDI-vo3qBxhAUU1Wg4IxxMG0_Nxr1o2Uh-RKj_jEIgAr0NyOsuDpJsC0tLcK7beszatucrJknX_n1iXEXiNYC88Nnz1U2G2vXQ_p5jxSk-jcI_HLlgGvmBiCthUZJXPg9dVS-05610_P-_NiXbF7wg1adEpDT3FvA1qM5iNoj4qRVSQnI_7l_OjFpA8szEoeA4_u481aao5u-YQL-FrBR01W8wte0IhM_44MwAUmT97M8axCLrg374cojyZElQN8cawlDP5Vs8PQ6tzpC8o_fcnPH7TLTkulJ4W4kBOfg`

`Jwt Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtJZCI6IjZOYmdkbXFFdlM1X2ROT1pOd3JvZGpOMEkyLThpSTVfNllYSUpNQllGb28ifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJuYmYiOjE3MzM3MzYxMzUsInB1cnBvc2VJZCI6IjUyODZhMjNlLTNlMDItNDc3MC04NTQ3LTdhOGNiYWRkZjk2MCIsInVzZXJMb2NhdGlvbiI6IjAuMC4wLjAiLCJleHAiOjE3MzM3MzYyNTUsInVzZXJJRCI6InN1Zm8iLCJkbm9uY2UiOjEyMzQ1Njc4OTEyMzQsImlhdCI6MTczMzczNjEzNSwiY2xpZW50X2lkIjoiNjIzMmNhNDUtYzU0OC00ZjY0LWIxNjAtMmNlMWI4YjMxMzQ0IiwianRpIjoiZTQ5MzM4NDgtN2JjZi00OTMyLTllZTItZDc4YjMzMGZkZGQzIn0.nVJjFIaltBa2n7ZiwlALLStlv5zdtj9NP_EVUoRraUHZyZDI-vo3qBxhAUU1Wg4IxxMG0_Nxr1o2Uh-RKj_jEIgAr0NyOsuDpJsC0tLcK7beszatucrJknX_n1iXEXiNYC88Nnz1U2G2vXQ_p5jxSk-jcI_HLlgGvmBiCthUZJXPg9dVS-05610_P-_NiXbF7wg1adEpDT3FvA1qM5iNoj4qRVSQnI_7l_OjFpA8szEoeA4_u481aao5u-YQL-FrBR01W8wte0IhM_44MwAUmT97M8axCLrg374cojyZElQN8cawlDP5Vs8PQ6tzpC8o_fcnPH7TLTkulJ4W4kBOfg`

`Jws Token: eyJraWQiOiI2TmJnZG1xRXZTNV9kTk9aTndyb2RqTjBJMi04aUk1XzZZWElKTUJZRm9vIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAzMC1zZXJ2aXppb0FjY2VydGFtZW50b0lkVW5pY29OYXppb25hbGUvdjEiLCJzaWduZWRfaGVhZGVycyI6W3siZGlnZXN0IjoiU0hBLTI1Nj1NemxqTUdGallUa3hZVEppT1RabU5HTmhaR0ptTVRoaU5UQmxORGN4WTJReU9USXpaamRpTmpZek5tWXlPVFZpWXpaaU1ESmtOamhoTVRjMVpHUmpOZz09In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PVVURi04In1dLCJleHAiOjE3MzM3MzY0MzYsImlhdCI6MTczMzczNjEzNn0.OqdBh-n-BQaYVvR9ymJjsKCSzZJX6T1bE6By7Bf2SEI1faUcdqptbGRnAsonuCSmJATv0ow-npTY_LZSJjQFxt2OOvlUgfCWiWGQf2Ecn0rsR9p5OTRJ9AOI_CWzTJ9vGo-n9V01vxyNKeVRtItvRVMZ47QEHm5Mza7g6M7Nsc5U7d-rZ59uCcnKmj3yyBJjUCQNOuUnIyD2YCfsgLzH6gjovD9LlG2UXDRrQc5Y0oILMqw1Hzc3Pn5snXsynnwlxKBPsRH8Ak4vsv0ETD0RTbxW669fF3iAu5HC2pNE7z0W_2ifOLXPYkU739fYGST78D2v9MdZGwDSIr7mFLfmzw`

La richiesta inoltrata e firmata è:
`{"idOperazioneClient":1733736134338,"criteriRicerca":{"codiceFiscale":"SGGSTM60A01H501J"},"datiRichiesta":{"casoUso":"C030","dataRiferimentoRichiesta":1733736134340,"motivoRichiesta":"SUFO"}}`

Il suo digest è:
`Digest = 39c0aca91a2b96f4cadbf18b50e471cd2923f7b6636f295bc6b02d68a175ddc6`

Il digest codificato in Base64 è:
`MzljMGFjYTkxYTJiOTZmNGNhZGJmMThiNTBlNDcxY2QyOTIzZjdiNjYzNmYyOTViYzZiMDJkNjhhMTc1ZGRjNg==`

GovWay ID = 431de18e-b608-11ef-b494-005056ae1884

Potreste fornirmi più dettagli sul problema ?

Grazie.

**Comment by azabatta** [comment]
Buongiorno,
di seguito l'errore riscontrato dal sistema:
Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Digest' possiede un valore non corrispondente al messaggio.
Saluti
