### ISSUE TITLE
Passaggio di stato in errore in pratiche online cambio residenza

### ISSUE THREAD

**Issue by anprpa** [italia/anpr#4746]
Buongiorno, va in errore il cambio di stato in "accolta definitivamente" della pratica n. 29902871
Ivana Ragni - SISPI - Comune di Palermo

<listaErrori>
            <errore>
                <codiceErroreAnomalia>EN148</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Errore nel recupero del dettaglio pratica. Esito: 999</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da fornire in caso di assistenza : data 2024-12-09 11:06:52 , idOperazioneANPR 2089513136</testoErroreAnomalia>
            </errore>
        </listaErrori>

**Comment by gppbarone** [comment]
Buongiorno, la pratica di cui vuole cambiare lo stato è in stato 2 (APERTA), la pratica deve transitare prima per lo stato 3 (IN LAVORAZIONE) e poi in stato 12 (ACCOLTA CON RISERVA) e infine come ultimo stato, può essere messa in stato 5 (Accolta definitivamente).

Assistenza ANPR

**Comment by anprpa** [comment]
Buongiorno, per noi la pratica è nello stato accolta con riserva.

Sono stati effettuati i cambi di stato in "in lavorazione" e "accolta con
riserva", vi invio i dati:

StatoDescrizioneN. Id Ope. ANPRData Ope. ANPR
3 - In lavorazione Trasferita ANPR 2014776139 23/10/2024
12 - Accolta con riserva Trasferita ANPR 2014777136 23/10/2024
5 - Accolta definitivamente Errore trasferimento ANPR


Attualmente qualsiasi richiesta effettuiamo riceviamo sempre lo stesso
errore.


Ad esempio, richiesta visura:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RichiestaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <testataRichiesta>
        <idOperazioneComune>13476305</idOperazioneComune>
        <codMittente>082053</codMittente>
        <codDestinatario>ANPR05</codDestinatario>
        <operazioneRichiesta>P002</operazioneRichiesta>
        <dataOraRichiesta>2024-12-09T13:59:25.274+01:00</dataOraRichiesta>
        <tipoOperazione>V</tipoOperazione>
        <tipoInvio>PROD</tipoInvio>
        <nomeApplicativo>DEMOS</nomeApplicativo>
        <versioneApplicativo>NOVERSION</versioneApplicativo>
        <fornitoreApplicativo>Sispi</fornitoreApplicativo>
    </testataRichiesta>
    <criteriRicerca>
        <codiceRichiesta>29902871</codiceRichiesta>
    </criteriRicerca>
</ns2:RichiestaP002>


Richiesta ottenuta:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:RispostaP002 xmlns:ns2="http://sogei.it/ANPR/P000sc">
    <ns2:rispostaKO>
        <testataRisposta>
            <idOperazioneComune>13476305</idOperazioneComune>
            <codMittente>082053</codMittente>
            <codDestinatario>ANPR05</codDestinatario>
            <operazioneRichiesta>P002</operazioneRichiesta>

<dataOraRichiesta>2024-12-09T13:59:25.274+01:00</dataOraRichiesta>
            <idOperazioneANPR>2090088661</idOperazioneANPR>
            <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
            <errore>
                <codiceErroreAnomalia>EN148</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Errore nel recupero del dettaglio
pratica. Esito: 999</testoErroreAnomalia>
            </errore>
            <errore>
                <codiceErroreAnomalia>EN527</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Informazioni sull'operazione da
fornire in caso di assistenza : data 2024-12-09 13:59:36 , idOperazioneANPR
2090088661</testoErroreAnomalia>
            </errore>
        </listaErrori>
    </ns2:rispostaKO>
</ns2:RispostaP002>




Cordiali saluti

Ivana Ragni



*-------------------------------------------------------------------------------*

*Dott.ssa Ivana Ragni*

*SISPI - SISTEMA PALERMO INNOVAZIONE SPA*

*Servizi alle Persone*

*tel. 0916319889*

*cell. 3347177809*



*-------------------------------------------------------------------------------*

*Nota di riservatezza**:*

*Ai sensi dell’art. 13 del Regolamento 2016/679/UE La informiamo che la
presente e-mail proviene da Sispi S.p.A. e s’intende inviata per scopi
lavorativi. Per tale ragione non è possibile garantire che, rispondendo
alla stessa, il contenuto venga visualizzato esclusivamente dal soggetto
cui è indirizzata la risposta. Si precisa che le informazioni contenute in
questo messaggio sono confidenziali, riservate e a uso esclusivo del
destinatario. Qualora lo stesso Le fosse pervenuto per errore, La preghiamo
di eliminarlo immediatamente senza farne uso ulteriore dandocene,
gentilmente, comunicazione. **Grazie.*



*Pursuant to Article 13 of the Regulation (EU) 2016/679, we inform you that
the hereby e-mail comes from Sispi S.p.A. and is intended to be sent for
working purposes. For this reason it’s not possible to guarantee that, by
answering to it, the content will be only shown to the individual towards
it’s addressed. We specify that the information contained in this message
are confidential, privileged and for the exclusive use of the addressee. If
you have received this e-mail message in error, please delete it
immediately without using it any further and kindly notify us. **Thank you.*


Il giorno lun 9 dic 2024 alle ore 13:44 gppbarone ***@***.***>
ha scritto:

**Comment by gppbarone** [comment]
Buonasera, l'iscrizione in ANPR di questo soggetto è stata annullata dal comune il 21 ottobre 2024. La pratica è stata aperta il 18 ottobre senza nessun cambio di stato successivo fatto dal comune di Palermo. Va da sé che dal 24 è decaduta e non si può elaborare, il cittadino non esiste più in Anagrafe.

Assistenza ANPR

**Comment by gppbarone** [comment]
Buongiorno, provvedo a chiudere la issue, per qualsiasi altro chiarimento è possibile aprirne una nuova.

Assistenza ANPR
