### ISSUE TITLE
Mancata risposata C030 massivo a fronte di alcuni codici fiscali in input

### ISSUE THREAD

**Issue by andrimega** [italia/anpr#4748]
Sto utilizzando il servizio C030 massivo ElabMassivaAccertIdUnicoNazionale in ambiente di collaudo e ho riscontrato un possibile bug. Il servizio risponde correttamente molto spesso, ma a fronte dell'invio di alcuni codici fiscali specifici ritorna una risposta successful ma con contenuto vuoto. Nel caso specifico su 400 codici fiscali, per quasi 100 di essi non viene ritornato nessun id.

Step per riprodurre il bug:
1. Inviare della lista di codici fiscali zippato e encodato
2. Attendere la fine dell'elaborazione
3. Scaricare l'output dell'elaborazione.

Non sembra ci sia alcuna correlazione tra i codici fiscali per i quali questo bug si presenta.
Per le richieste ho utilizzato il client Java da voi fornito. 
Ho provato sia inserendo i CF in questione insieme a CF per cui il servizio risponde correttamente (in questo caso manca l'input corrispondente ai CF anomali ma è presente l'output per gli altri), sia solamente quelli per cui si presenta l'anomalia (output vuoto).

**Comment by azabatta** [comment]
Buonasera, 
potrebbe trattarsi di CF non presenti nel DB di collaudo di PDND. Ha un servizio di consultazione puntuale autorizzato per fare questa verifica e darci un riscontro? In alternativa può segnalare alcuni CF, per i quali il servizio non risponde, inviando una mail al casella  assistenza.anpr.enti@sogei.it?
Grazie

**Comment by andrimega** [comment]
Buonasera,
Mi scuso dell'errore mi trovo in ambiente di erogazione. In collaudo avevo già provato con la lista di codici di esempio e aveva funzionato. 
Purtroppo non posso condividere i codici fiscali su cui riscontro questa anomalia per problemi di privacy.

**Comment by azabatta** [comment]
Senza un esempio è un pò difficile fornire supporto. 
L'unica prova da fare, se avete a disposizione un altro eservice o anche un'altra tipologia di consultazione di ANPR,  è verificare se i CF di interesse sono presenti o meno in ANPR.
Riporto di seguito una serie di motivi per cui un  cittadino può non avere una posizione attiva in ANPR:

- cittadino cancellato dall'anagrafe comunale prima dell'ingresso del comune di competenza (residenza o iscrizione AIRE) in ANPR
- cittadino deceduto prima dell'ingresso del comune di competenza (residenza o iscrizione AIRE) in ANPR
- cittadino cancellato da ANPR per motivi diversi dal decesso (es. irreperibilità, rientro in patria di uno straniero)
- cittadino presente in ANPR con un CF  diverso in seguito ad una rettifica dei dati anagrafici o per effetto di una omocodia.

La data di subentro dei comuni può essere ricavata scaricando la tabella 45 "Comuni subentrati" dal Portale di ANPR - Area Tecnica - Tabelle di decodifica.
Saluti
