### ISSUE TITLE
1001 - Soggetti padre/madre non in ANPR

### ISSUE THREAD

**Issue by giovannidestefano** [italia/anpr#475]
In riferimento alla richiesta 1001 del 22/12/2017  avente  idOperazioneANPR = 681947
( Ambiente Test ) chiediamo aiuto per il superamento del problema riscontrato 
                <codiceErroreAnomalia>EN144</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Soggetti padre/madre non in ANPR</testoErroreAnomalia>
 
Giovanni De Stefano 
Advanced Systems 
per il comune di Cava dei Tirreni

**Comment by gcarbonin** [comment]
Nella richiesta è stato indicato che il bambino appartiene alla famiglia dei genitori di conseguenza entrambi i genitori devono essere presenti in ANPR.

**Comment by giovannidestefano** [comment]
Salve, 
ho verificato nel flusso di Test del subentro caricato nel sistema e i soggetti padre e madre e relativa famiglia sono correttamente presenti.
ciò nonostante anche sul portale la ricerca dei suddetti soggetti non mi producono risultati.
Mi chiedo, ma il database del Comune in questione risulta caricato e disponibile o dobbiamo rieseguire il caricamento del file?
Attendo  risposta

**Comment by gcarbonin** [comment]
Avete richiesto la cancellazione dei dati il 1 dicembre; occorre pertanto ripetere l'invio (sia apr che aire) e attendere la PEC che conferma l'avvenuta elaborazione
