### ISSUE TITLE
[s1002 - s1014 - s3002] errore "operazione non effettuabile" - ambiente test

### ISSUE THREAD

**Issue by Hdemografici** [italia/anpr#4752]
buongiorno 
in ambiente di test ho l'errore 999 - operazione non effettuabile
sicuramente con s1002 - s1014 - s3002

ad esempio
idOperazioneComune: 20241223092833922
codMittente: 041069
codDestinatario: ANPR05
operazioneRichiesta: 1002

oppure
idOperazioneComune: 20241223094418471
codMittente: 041010
codDestinatario: ANPR05
operazioneRichiesta: 3002

mentre s5008 sembra funzionare, idOperazioneANPR: 76848755

**Comment by MoniaPedrazzoli** [comment]
Buongiorno, anche noi abbiamo lo stesso problema.
Monia Pedrazzoli
APKAPPA s.r.l.

**Comment by azabatta** [comment]
Cortesemente potete riprovare e darci un riscontro?
Grazie

**Comment by mttfranci** [comment]
Salve, quindi non avete un idOperazioneANPR in risposta?

Potete fornirci una richiesta e risposta completa di almeno una invocazione andata in errore?

Grazie in anticipo.

Assistenza ANPR

**Comment by MoniaPedrazzoli** [comment]
Al momento sembra essere tornato tutto funzionante. 

Questo è un esempio di risposta 3002 errata che abbiamo ricevuto:

```xml
<xml>
<ns2:Risposta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione">
    <ns2:rispostaKO>
        <testataRisposta>
            <idOperazioneComune>191444</idOperazioneComune>
            <codMittente>103017</codMittente>
            <codDestinatario>ANPR05</codDestinatario>
            <operazioneRichiesta>3002</operazioneRichiesta>
            <dataOraRichiesta>2024-12-23T11:49:58</dataOraRichiesta>
            <protocolloComune>2024_000000000076441</protocolloComune>
            <dataProtocolloComune>2024-12-23</dataProtocolloComune>
            <idOperazioneANPR>0</idOperazioneANPR>
            <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
            <errore>
                <codiceErroreAnomalia>999</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
            </errore>
        </listaErrori>
    </ns2:rispostaKO>
</ns2:Risposta3002>
</xml>
```

Grazie

**Comment by mttfranci** [comment]
Salve @MoniaPedrazzoli va bene anche a noi ora sembra tutto ok. Chiudiamo la issue
