### ISSUE TITLE
C007–ServizioVerificaDichEsistenzaVita - UnknownAPI

### ISSUE THREAD

**Issue by AlessandroCimarelli-DXC** [italia/anpr#4754]
Buongiorno,

sto facendo dei test dal ministero di giustizia per invocare il servizio C007–ServizioVerificaDichEsistenzaVita.

la url che richiamiamo in POST è la seguente: 

 https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C007-servizioVerificaDichEsistenzaVita/v1/anpr-service-e002

nell'header ci sono l'header bearer di autorizzazione, generato dalla pdnd,  Agid-JWT-Signature e Agid-JWT-TrackingEvidence firmati.

l'errore è il seguente :

{
   "type": "https://govway.org/handling-errors/404/NotFound.html",
   "title": "NotFound",
   "status": 404,
   "detail": "Unknown API Request",
   "X-Global-Transaction-ID": "6026e6bc676941f84e33f92f"
}

Prima di fare i test, abbiamo richiesto la fruizione e la finalità, con le quali abbiamo il purposeid per la richiesta del voucher.

potete aiutarci a capire quale sia il problema?

grazie in anticipo

**Comment by azabatta** [comment]
Salve, 
per effettuare delle verifiche abbiamo bisogno del GovWay ID.
Grazie

**Comment by AlessandroCimarelli-DXC** [comment]
Ciao,

GovWay-Transaction-ID	14ede875-c11e-11ef-a39d-0050568b0b28
GovWay-Message-ID	c7cc0139-c11e-11ef-a39d-0050568b0b28

ho effettuato un test ora, alle 14.06

grazie

**Comment by AlessandroCimarelli-DXC** [comment]
Ciao,

1- la url è la seguente: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C007-servizioVerificaDichEsistenzaVita/v1/anpr-service-e002 recuperata dal l'openapi presente nel portale PDND

2 il voucher,  Agid-JWT-Signature e Agid-JWT-TrackingEvidence sono generati correttamente:

Authorization' = 'Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAwNy1zZXJ2aXppb1ZlcmlmaWNhRGljaEVzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiI2NDJlNzdmMC03Y2IzLTQzMTYtYjkxNC0xYmM1MDdkYTAwOWUiLCJuYmYiOjE3MzQ5NTE0MTYsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6IjAyY2EzZWVjNmE2ZTA0NzhkMWEyN2I3MTQ4Y2VlNDM2Njg1NTBkNTcwYTAxYWY0MjVkMGJjOWYxYTExMzRkOTgifSwicHVycG9zZUlkIjoiZTcwZTQxMGYtZjI4NS00ODEwLTljNTUtYWVkNzE3OTMwZjI5IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzM0OTUyMDE2LCJpYXQiOjE3MzQ5NTE0MTYsImNsaWVudF9pZCI6IjY0MmU3N2YwLTdjYjMtNDMxNi1iOTE0LTFiYzUwN2RhMDA5ZSIsImp0aSI6IjQ5NGVlNzQwLTZmNGMtNDhjNC05YmQyLTVkNzY3YjU4NTgxNCJ9.mIDuwGRiS0ev3WwkjbeV4xksOsviowZMMqXwnPIKTd48grNV78byGVXv0Vg3UTns97LSrmD5h2P-bzu9ZZSDIuJqmHX5lC2bNK5b5IYclD0-q9UjDMFuffd-5sT1q47UdhmCcNzW8Z-vgEWEMmfQoU0O_KFpMoecKTUOFL87BaTYtskWcC_Y7Q8RPOR6lS7GCbzzw-moM9gvKI7hZbVzLkGgc_RWoGNKGrc4gN7nBYIlgV3-RFQsx9I9nCtdzDGFLccSvlIPBb5VxXZpzWuHjOlf-WSVf1R6m4aghpA7Rxad9DiMuWhaooUO-x7BZ2rYTL-r6kINtMnRwgCGYrukPQ') 
 
Agid-JWT-Signature=[eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxzT1EtaVJGMjNTRWVLSFNPTmVfdFJidHBnRkZpT0o3STZjZUd1Zi0wVUkifQ.eyJpYXQiOjE3MzQ5NTE0MTYsIm5iZiI6MTczNDk1MTQxNiwiZXhwIjoxNzM0OTUxNDc2LCJqdGkiOiIxMzI2N2EyMS1jMTE0LTExZWYtYjRmMy0wMDUwNTY4YjBiMjgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAwNy1zZXJ2aXppb1ZlcmlmaWNhRGljaEVzaXN0ZW56YVZpdGEvdjEiLCJjbGllbnRfaWQiOiI2NDJlNzdmMC03Y2IzLTQzMTYtYjkxNC0xYmM1MDdkYTAwOWUiLCJpc3MiOiJNaW5pc3Rlcm9HaXVzdGl6aWFDb2xsYXVkbyIsInN1YiI6Ik1kSS1DMDA3LVNlcnZpemlvVmVyaWZpY2FEaWNoRXNpc3RlbnphVml0YS92MSIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PVpvcDFPMVArWmowR1l2VWdYNHgrdSswSWdWeHJKZjljZDRoUXEvbFJRejA9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dfQ.SGS0JIv6aykXXH5hk-FcYKDv9v0jqugCXj4INj9D2lTcFUFjfOImO4TVyKAbKt1kaE3owmKWGwpfsQRFiVdHlPzD4kduKBGeyjIwZfaopkGtKapzd7VW0Ldv8rIccTErxHPp4DR1_QrZiI_u9miwbnt6QoxR656FHQ8cUIw896c1IHnLJxy4jchHP3uSJvjKvE0f-RLJjKW_sqQjc4P1PmD4bbVq47YMPMg3GAva8nCphQliuZoHIx4IcmFHKh2C10Ng6zlG7ostxfNOMY7sl0peCjSNgSw2U7hk5QWcsqyn37qayR1X07xbgdDFpqUxHcivnos6Kk6gZDTGh0SlWQ] 
 
Agid-JWT-TrackingEvidence=[eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxzT1EtaVJGMjNTRWVLSFNPTmVfdFJidHBnRkZpT0o3STZjZUd1Zi0wVUkifQ.eyJpYXQiOjE3MzQ5NTE0MTYsIm5iZiI6MTczNDk1MTQxNiwiZXhwIjoxNzM0OTUxNDc2LCJqdGkiOiIxMzI5ODc2Mi1jMTE0LTExZWYtYjRmMy0wMDUwNTY4YjBiMjgiLCJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAwNy1zZXJ2aXppb1ZlcmlmaWNhRGljaEVzaXN0ZW56YVZpdGEvdjEiLCJ1c2VySUQiOiJ1c2VyVGVzdCIsInVzZXJMb2NhdGlvbiI6InVmZmljaW9UZXN0IiwiTG9BIjoiU1BJRCIsImlzcyI6IjY0MmU3N2YwLTdjYjMtNDMxNi1iOTE0LTFiYzUwN2RhMDA5ZSIsInB1cnBvc2VJZCI6ImU3MGU0MTBmLWYyODUtNDgxMC05YzU1LWFlZDcxNzkzMGYyOSIsImRub25jZSI6MzE2ODYzMTI3MzAyNn0.SDjS0qTiGqZGL5FRBW0u0i9qVhExINNj1r1Q-nrqZNa9gRDEOVNT8crs84kF-fr8f1Tqq4akQYNOZG4XXmTmE_e3cc_3N2YOIcEV6lW8q0Qke0rMaVVM1zmbjFWjlNQVKzj_3971_Yvecg68kqgw3mR6co04rrqJAv5NfGsnlY4D6UT9MlchLjgkpFJC8JkLGhF2Qj0l9dX8wvCVS7sPDGBEb0WQ9I0ZLgR3yM0_SmVSd_VfZgFKtE5PJLMnY6eTcpWaDoTxea9rYh8T9J8UkYitUSADe_ShWqSxoj_xEl6C3O6q1q3BMLpSmMjxgifq1lscgk2KVaGFkKZGAZPZgg] 

per quello che vediamo noi dai log le informazioni e il flusso è giusto, non riusciamo a capire dove possa essere il problema, quello che ci viene risposto dal vostro sistema govway è: 

{
  "type" : "https://govway.org/handling-errors/404/NotFound.html",
  "title" : "NotFound",
  "status" : 404,
  "detail" : "Unknown API Request",
  "X-Global-Transaction-ID" : "6026e6bc6769607b4e6b53cf"
}

**Comment by afrontera85** [comment]
L'url corretto è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C007-servizioVerificaDichEsistenzaVita/v1/anpr-service-e002

**Comment by AlessandroCimarelli-DXC** [comment]
Buongiorno,
abbiamo sostituito la url, ora abbiamo un altro errore:

{
   "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title": "InteroperabilityInvalidRequest",
   "status": 400,
   "detail": "Received request is not conform to the required interoperability profile",
   "govway_id": "9afc6ded-c1cf-11ef-8e23-005056ae1884"
}

quindi sembra che ci sia qualcosa di errato nella richiesta, potete dirci quale nello specifico?

come detto passiamo tutte e 3 i jwt, l'authorization (voucher), Agid-JWT-Signature e Agid-JWT-TrackingEvidence

grazie
Alessandro

**Comment by AlessandroCimarelli-DXC** [comment]
Abbiamo risolto. Ora era un problema di audiance, che è diverso, rispetto alla url invocata. 

grazie ancora del supporto.
