### ISSUE TITLE
[5001] DA comune subentrato A comune subentrato: tipoMutazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#476]
due soggetti (I.S. - lui - e moglie) sono i componenti di un nucleo che si sposta da un comune subentrato ad un altro comune subentrato.
nel nuovo comune rimangono gli unici due componenti, ma decidono di invertire i rapporti di parantela, per cui vengono iscritti come I.S. - lei - e marito.

l'xml con cui viene comunicata la variazione è di tipo 5001, e contiene tutti i dati relativi alla nuova composizione del nucleo (con i nuovi legami) ed il nuovo indirizzo.
(es. ambiente di PRODUZIONE - comune di MEDICINA - idOperazioneComune 2017001986)

se, all'interno del tag datiControllo, valorizziamo il tipoMutazione a '4', viene aggiornato solo l'indirizzo e non anche i rapporti di parentela; se invece il tipoMutazione viene valorizzato a '2', vengono aggiornati solo i rapporti di parentela e non anche l'indirizzo.

premesso che i Warning che vengono segnalati dal web-service sono coerenti con questo comportamento...
"EN395 - W - per il tipo di mutazione 4 saranno modificati soltanto i dati relativi a residenza"
"EN395 - W - per il tipo di mutazione 2 saranno modificati soltanto i dati relativi a composizione scheda"
si chiede: 
1. perchè è necessario inviare due distinte comunicazioni quando tutti i dati necessari sono già contenuti all'interno dello stesso xml? 
2. perchè non prevedere la possibilità di indicare più tipiMutazione, come ad esempio viene già fatto nelle comunicazioni di tipo 5008?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Le comunicazioni sono distinte in quanto svolgono azioni diverse: la composizione della famiglia, infatti, cambia a prescindere dalla residenza.
