### ISSUE TITLE
Certificati di resienza storici

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#477]
Osservo in ambiente di test la disponibilità in certificazione dei seguenti documenti:
1) Storico di residenza alla data
2) Storico di residenza
che producono lo stesso risultato, salvo il titolo che riporta le descrizioni qui segnate coi numeri 1 e 2.
Che differenza c'è?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Il certificato n. 2 riporta tutte le residenze note fino alla data specificata nella richiesta; se in ANPR è presente una sola residenza i due certificati sono uguali (a meno del titolo)

**Comment by bfilipazzi** [comment]
La tabella 13 contenente i tipi di certificato saràintegrata con il nuovo documento?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
si

**Comment by gcarbonin** [comment]
Si veda l'avvio 407

**Comment by azabatta** [comment]
La documentazione è stata aggiornata
