### ISSUE TITLE
Data inizio validita' comuni di Luni e Soraga di Fassa

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#478]
Buongiorno,

per le  2 nuove denominazioni dei comuni indicati Luni e Soraga di Fassa l'Istat propone una diversa data di decorrenza rispetto a quanto previsto sulla vostra tabella dei comuni italiani.
Vedasi:
https://www.istat.it/it/files/2011/01/Novita-per-il-2017.pdf

 Distinti saluti
Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
Faremo le necessarie verifiche (le date dell'archivio sono ricavate da comunicazioni ufficiali che ISTAT invia al Ministero dell'Interno) e ove necessario, aggiorneremo le date.

**Comment by gcarbonin** [comment]
Abbiamo allineato lo storico comuni
