### ISSUE TITLE
Cancellazione precedente al subentro

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#479]
Riporto il seguente testo per conto del comune di Lucca.
Filipazzi - Maggioli

COMUNE DI LUCCA - AMBIENTE DI PRODUZIONE

Buongiorno,
stiamo procedendo alla cancellazione di un soggetto che ha come data decorrenza 18/12/2017,
antecedente alla data di subentro (21/12/2017), la comunicazione fallisce con la seguente anomalia:

"La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto
<idOperazioneANPR>1622245</idOperazioneANPR>"

Abbiamo effettuato anche altre cancellazioni con data decorrenza antecedente al 21/12/2017, ma si sono chiuse correttamente.
L'unica differenza che notiamo è la data decorrenza che è 19/12/2017 (ma in ogni caso sempre antecedente al subentro)
vedere --> idOperazioneANPR>1600653

Come possiamo procedere? visto che la data di decorrenza giuridica non è modificabile.

**Comment by gcarbonin** [comment]
La persona da cancellare ha come data di inizio validita della scheda 19-12-2017 (ricavata dalla data di ultima variazione indicata al subentro); quindi una data antecedente non può essere indicata.
L'altra cancellazione (1600653) andata a buon fine riguarda una persona che ha come data di inizio validità della scheda in ANPR 19-12-2017 e una data di cancellazione 19-12-2017.

**Comment by bfilipazzi** [comment]
La persona ha avuto una variazione dei dati, suppongo una ritocco per il subentro, il giorno 19. Il giorno 21 è avvenuto il subentro e il 22 l'ufficio ha ricevuto una richiesta di cancellazione per emigrazione con decorrenza 18. Cosa si può fare?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
L'unica soluzione veloce sarebbe quella di aggiornare al 18 dicembre la data di ultima variazione (pec del comune).

**Comment by bfilipazzi** [comment]
Ho riferito al Cliente.
Filipazzi - Maggioli
