### ISSUE TITLE
Web App - Anomalie soggetto su Consultazione scheda individuale

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#48]
Ambiente di test - 23/03/2017
Effettuando test, abbiamo riscontrato che, nella Consultazione della scheda individuale, potrebbe essere utile creare una sezione contenente l’elenco delle anomalie attive riferito al soggetto: in questo modo sarebbe molto più agevole individuarle e sanarle. 
Grazie, 
Valentina Bocchino - Comune di Torino

**Comment by gcarbonin** [comment]
Analizziamo la questione prevedendo una eventuale successiva implementazione
