### ISSUE TITLE
Tentato rigetto di iscrizione fallito per EN240

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#480]
Comune di Lucca - Produzione

idOperazioneANPR: 1637542
errore EN240 La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 

Si richiede il ripristino della posizione precedente di una persona.
La persona è stata iscritta per immigrazione con decorrenza 03.10.2017.
La sua scheda è stata variata l'ultima volta in data 11.10.2017, giorno del completamento dati della pratica di iscrizione.

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
La mutazione di completamento dovrebbe avere la stessa data di decorrenza della iscrizione.

**Comment by bfilipazzi** [comment]
Concordo che la mutazione di completamento ha la stessa decorrenza dell'iscrizione, ma riguardo alla data di ultima variazione della scheda da trasmettere al subentro abbiamo interpretato letteralmente la frase nel par. 9.5.1 delle specifiche: "corrispondente all’ultima operazione effettuata sul soggetto ... pur non trattandosi di un dato anagrafico è un dato registrato nel sistema informativo del comune", e abbiamo fornito questo dato com'è. Nel caso in esame, e anche in altri, è la data in cui l'ufficio è intervenuto l'ultima volta sulla persona, per qualsiasi motivo.
A questo punto dobbiamo risolvere 2 problemi:
1) intervenire sulla pratica segnalata;
2) modificare la logica di valorizzazione della data per i subentri a venire.

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Le soluzioni sono 2:
1. inserire la mutazione di completamento con data 11.10.2017 (come sarebbe logico, visto che il comune è intervenuto sulla scheda successivamente alla iscrizione9
2. richiedere via PEC l'aggiornamento della data di ultima variazione portandola al 3.10.2017
