### ISSUE TITLE
WS - msg. "rejected by policy. (from client)" 

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#481]
buongiorno.

abbiamo due postazioni che stanno testando i web-service.
le configurazioni sembrano allineate, ma una ottiene risposta e l'altra invece fa scattare l'errore in oggetto.

pur trattandosi di un errore "from client", riuscite ad individuare l'anomalia che scatena l'errore?
alcune comunicazioni che potreste verificare sono quelle con idOperazioneComune 2017600148, 2017600147
(ambiente di PRE-SUBENTRO - comune di ALBANO SANT'ALESSANDRO (016-003))

se necessario possiamo inviare anche un esempio di xml comprensivo dei tag SAML

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno.

Se le configurazioni sono del tutto allineate (vale a dire che viene usato anche lo stesso certificato di postazione), potreste, in prima istanza, verificare se il client ha un orario leggermente disallineato?

Le richieste sono state bloccate dai sistemi periferici e in tale ambiente i log sono disponibili per tempi estremamente brevi, ma dato che il token di autenticazione è valido per un lasso di tempo piuttosto breve, un disallineamento dell'orario del client può portare a questo tipo di errori.

**Comment by AMonopoliADS** [comment]
grazie Matteo.
il client era disallineato di soli 30 secondi... ma questo evidentemente dava fastidio al sistema.
uniformati gli orari le richieste hanno ripreso a funzionare.
grazie

**Comment by mttfranci** [comment]
Prego.
Saluti.
