### ISSUE TITLE
[5001] Rimpatrio da AIRE

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#482]
ambiente di PRODUZIONE - comune di FAENZA

buongiorno.

abbiamo perfezionato la pratica di rimpatrio di un cittadino iscritto nella nostra AIRE.
l'operazione è andata a buon fine, ma il web-service di consultazione non restituisce la provenienza del soggetto come dato integrativo dell'iscrizione.

per analogia, l'iscrizione di soggetto che arriva da altro comune subentrato, pur venendo iscritto con servizio 5001, in fase di consultazione riporta correttamente anche il comune di precedente residenza.

riteniamo che sia un dato utile, ai fini di una maggiore chiarezza dei dati di iscrizione, che tale informazione compaia anche nel caso di rimpatrio.

vedere ad esempio:
idSchedaSoggettoANPR 19088891
idSchedaSoggettoANPR 19089047

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Non viene riportato il comune di precedente iscrizione AIRE quando coincide con quello del reimpatrio

**Comment by COlivatoADS** [comment]
Buongiorno,
senza tale dato, si perde evidenza della storicità del soggetto che sembra iscritto semplicemente nel comune dalla data di rimpatrio.
Nel caso del soggetto proveniente da altro comune subentrato, invece, si ha correttamente evidenza dell'iscrizione da data rimpatrio con provenienza da stato estero (storicizzazione della precedente iscrizione AIRE).

Grazie
Christian Olivato ADS

**Comment by gcarbonin** [comment]
Forse non mi sono spiegata bene: il comune di precedente iscrizione non è valorizzato se coincide con quello del rimpatrio. Non si perde nulla.

**Comment by COlivatoADS** [comment]
Buongiorno,
chiedo scusa ma probabilmente non mi sono spiegato bene io. 
Cerco di chiarire  con esempio fittizio:
1 - Caso di rimpatrio da AIRE di altro Comune:
Il soggetto risulta iscritto a Faenza con provenienza da Francia (questo denota precedente iscrizione AIRE)
2 - Caso di rimpatrio da AIRE del Comune:
Il soggetto risulta iscritto dalla data di rimpatrio a Faenza senza alcuna provenienza (a nostro avviso si perde evidenza della precedente iscrizione AIRE).

Grazie 
Christian Olivato ADS

**Comment by gcarbonin** [comment]
C i può indicare i due identificativi ANPR in modo da provare l'interrogazione?

**Comment by COlivatoADS** [comment]
Di seguito le varie casistiche (rif. COMUNE DI FAENZA):
1 - Soggetto proveniente dall'estero, iscritto con servizio 1002:
IdSchedaANPR 19659533: si vede il comune estero di provenienza  
				
2 -  Soggetto proveniente da comune subentrato, iscritto con servizio 5001 o 5005:
IdSchedaANPR 19078303: si vede il comune di provenienza

3 - Soggetto rimpatriato dalla nostra AIRE, iscritto con servizio 5001 o 5005		
IdSchedaANPR 19088941:  non si vede il comune di provenienza 		

4 - Soggetto già rimpatriato al momento del subentro:
IdSchedaANPR 19107072: non si vede il comune di provenienza (non previsto nei dati di subentro) ma almeno risulta come rimpatriato da AIRE.

Grazie
Christian Olivato ADS

**Comment by gcarbonin** [comment]
Come premessa generale, i servizi attuali prevedono per la provenienza che possa essere indicato in alternativa il comune di provenienza o lo stato estero di provenienza, rispettivamente in caso di:

- trasferimento da altro comune;
- immigrazione dall'estero,

Per gli iscritti AIRE servirebbero entrambi i dati e stiamo valutando una evoluzione in questo senso; al momento, ciò non è possibile e servizi considerano il comune di precedente iscrizione.

Venendo ai casi indicati:
1)  in consultazione viene riportato esattamente quello che è impostato nella Provenienza al momento dell'iscrizione; nel caso specifico, lo stato di provenienza
2) Non di tratta di un soggetto AIRE ma di una persona che si trasferisce in un comune subentrato e proviene da un altro comune subentrato; in questo caso l'interrogazione riporta il comune di provenienza
3) come sopra indicato, il comune di precedente iscrizione coincide con quello del reimpatrio e non viene visualizzato in interrogazione; se la stessa persona provenisse dall'AIRE di un altro comune, sarebbe presente in interrogazione il comune di precedente iscrizione
4) Al subentro il dato relativo alla provenienza non è previsto in quanto il subentro rappresenta la fotografia ad una certa data e la provenienza è, di fatto, un dato storico: è noto che in ANPR non transitano al momento i dati storici e, di conseguenza, i dati di ANPR contengono le informazioni dal subentro in poi mentre una ricostruzione complessiva della storia di un soggetto dovrà utilizzare anche i dati del comune.

**Comment by AMonopoliADS** [comment]
grazie del riscontro dettagliato.

quello che si voleva evidenziare, era proprio l'esigenza di "conoscere" il dato della provenienza estera anche in presenza di un evento di trasferimento dall'AIRE.
in particolare nel caso di rientro dalla nostra AIRE, ma anche nel caso di soggetto che proviene dall'AIRE di altro comune, avere solo il dato del comune italiano di prececedente iscrizione è parziale e rischia di essere fuorviante riguardo la reale dinamica dell'evento che ha generato la mutazione.

attendiamo eventuali evolutive.

grazie.

**Comment by gcarbonin** [comment]
La nuova versione di anpr comprende anche la provenienza aire
