### ISSUE TITLE
Iscrizione AIRE

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#483]
Iscrizione da APR ad AIRE. 
Come abbiamo fatto regolarmente sino alla settimana scorsa, dal nostro gestionale istruiamo una pratica di emigrazione in Aire con creazione nucleo.
Al momento della registrazione dell'evento Ci da il seguente errore:
EC060 Campo codice motivo iscrizione AIRE E01 inesistente sulla tabella di riferimento.

**Comment by gcarbonin** [comment]
I motivi di iscrizione aire validi sono quelli presenti nella tabella disponibile a questo link https://www.anpr.interno.it/portale/documents/20182/50186/tabella_19.xlsx/ee794110-7244-41a8-a8c5-be308e15fb87 (non contiene il valore E01).
