### ISSUE TITLE
[5005] Trasferimento da Convivenza a Famiglia

### ISSUE THREAD

**Issue by busaster** [italia/anpr#485]
Ambiente di Test - Poggio a Caiano.

Ho una convivenza anagrafica in cui risulta iscritto un unico componente.
In data odierna questo componente esce dalla convivenza e va a formare una nuova famiglia anagrafica.
La convivenza deve rimanere presente in archivio e vuota.

Ho provato ad eseguire questa operazione con il servizio 5005 (id ANPR 698160) ma ottengo l'errore "Per trasferire tutti i componenti di una famiglia in una nuova utilizzare il servizio di mutazione residenza famiglia". 
Il blocco non è corretto poiché non sto modificando indirizzo alla famiglia/convivenza ma sto facendo uscire dalla convivenza un componente.

**Comment by azabatta** [comment]
Stiamo verificando, grazie per la segnalazione

**Comment by azabatta** [comment]
Il blocco è stato rimosso: la modifica è disponibile in tutti gli ambienti.

**Comment by busaster** [comment]
Ho verificato la procedura e confermo che ora funziona.
Grazie
