### ISSUE TITLE
[5001] Mutazione residenza, famiglia da diverse provenienze

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#486]
Buongiorno, un chiarimento su quando utilizzare il servizio 5001.
Se ad esempio ho allo sportello due persone, provenienti da famiglie diverse, dove sono l'unico componente. Effettuano una unica dichiarazione di residenza. Ecco, in questo caso non posso usare due servizi 5001, e credo non abbia nemmeno senso utilizzare un 5001 e un 5005.
Credo vada utilizzato il 5001 esclusivamente quando tutta la famiglia così come è, trasferisce la propria residenza, senza l'aggiunta (contemporanea) di altri componenti.

**Comment by gcarbonin** [comment]
Corretto: si usa il 5001 quando la modifica (di residenza o di composizione) riguarda la famiglia intera così come è.
