### ISSUE TITLE
[5008] Matrimonio cittadino straniero - Errore EN272

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#487]
ambiente di PRODUZIONE - comune di FAENZA - idOperazioneComune 2018000341

si sta tentando di comunicare il nuovo matrimonio per un soggetto presente in ANPR con stato civile DIVORZIATO (idSchedaSoggettoANPR 19137809).
il soggetto in questione, nella sua posizione precedente all'attuale matrimonio, presenta solo il nome del coniuge e nessuna altra informazione relativa a matrimonio / cessazione.

la comunicazione per aggiornare il matrimonio va in errore, segnalando:
```
<errore>
  <codiceErroreAnomalia>EN272</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Alla data 07-10-2016 il soggetto BOUHOUCH HICHAM risulta gia' coniugato o unito civilmente con un altro soggetto</testoErroreAnomalia>
</errore>
```

... ma il soggetto risulta DIVORZIATO...

abbiamo anche notato, che il servizio di consultazione ritorna la seguente anomalia, tra i dati del soggetto:
```
<erroriAnomalie>
  <codiceErroreAnomalia>EN306</codiceErroreAnomalia>
  <tipoErroreAnomalia>1</tipoErroreAnomalia>
  <testoErroreAnomalia>Presenza del coniuge e assenza del matrimonio</testoErroreAnomalia>
</erroriAnomalie>
```
non so se l'errore possa dipendere da questo, ma... come risolvere?

(approfitto anche per segnalare che all'interno del tag tipoErroreAnomalia, della risposta del 3002 di consultazione, si trova il valore '1', mentre normalmente troviamo 'E' o 'W', così come indicato anche nelle specifiche excel)

grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
La comunicazione del solo stato civile non implica la chiusura automatica del matrimonio. 
A tale riguardo proponiamo la soluzione riportata nella issue #449.
Per quanto riguarda l'anomalia  EN306 segnalata, è una anomalia da subentro.
In attesa di riscontro.
