### ISSUE TITLE
[5008] Rettifica Generalità - Errore EAM9F

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#488]
ambiente di PRODUZIONE - comune di FAENZA - idSchedaSoggettoANPR 19149227

si sta tentando di comunicare la rettifica di cognome e nome del soggetto di cui all'idANPR indicato.
(vedere ad esempio l'idOperazioneComune 2017003976)

il web-service ritorna l'errore
```
<errore>
  <codiceErroreAnomalia>EAM9F</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Individuate due posizioni in AT non unificabili</testoErroreAnomalia>
</errore>
```
il cliente ha anche tentato di ripetere la comunicazione con il gestioneCF valorizzato a '2', ma anche in questo caso ritorna errore:
```
<errore>
  <codiceErroreAnomalia>EN125</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Per richiesta attribuzione CF o omocodice, il codice fiscale non deve essere valorizzato</testoErroreAnomalia>
</errore>
```

qual è l'iter giusto da seguire in questo caso?
si precisa che in AE il soggetto ha il codice numerico collegato all'alfanumerico che è presente e validato in ANPR.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Si effettua la mutazione del cognome e del nome senza indicare gestioneCF o valorizzandolo a zero

**Comment by gcarbonin** [comment]
Il primo messaggio di errore mi fa pensare ad un caso di codici fiscali scollegati tra di loro attualmente non collegabili in modo automatico; se la mia ipotesi è corretta, da ANPR non possiamo al momento fare nulla se non mettervi nella condizioni di fare comunque la variazione.
