### ISSUE TITLE
[Subentro] La data di ultimo aggiornamento APR non risulta valorizzata

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#49]
Dal giorno 22.03.2017, dopo avere fatto un subentro in ambiente di test, scaricando il file degli errori,
per tutti i cittadini viene segnalato l'errore (come Warning) seguente:

**ES128	La data di ultimo aggiornamento APR non risulta valorizzata**

Quale (nuovo) tag andrebbe valorizzato nell'xml di subentro?

Ambiente: **TEST**
Data: **22.03.2017**
Comune: **Palagianello (TA)**
Fornitore: **Datagraph s.r.l.**
Segnalatore: **Tropeano Alessio**

**Comment by ATropeano** [comment]
Errata Corrige: si tratta del subentro del comune di Montemesola (TA).

**Comment by gcarbonin** [comment]
E' un dato presente da sempre nel file di subentro:
<xs:complexType name="tipoGeneralitaSoggetto">
					.......
			**<xs:element name="dataUltimoAggiornamento"				type="xs:date" 										 	minOccurs="0" maxOccurs="1"/>**		
			...>				
		</xs:sequence>		
	</xs:complexType>	



 Abbiamo pensato di aggiungere l'anomalia in quanto senza questo dato si prende come riferimento della scheda la data del subentro, cosa che poi può dare problemi per quelle persone con procedimenti amministrativi iniziati prima del subentro che si concludono dopo.

**Comment by ATropeano** [comment]
In pratica, valorizzando questo campo con la data dell'ultima modifica apportata sui dati del cittadino dall'anagrafe locale, verrebbe poi "permesso" di inviare in ANPR mutazioni con una data di decorrenza anteriore alla data di subentro e superiore alla data di ultimo aggiornamento inviata per quel cittadino al  momento del subentro?

**Comment by gcarbonin** [comment]
Stiamo perfezionando la gestione delle mutazioni di completamento (quelle da APR4 per capirci) e dei ripristini delle posizioni anagrafiche. In questo ambito per garantire comunque una consistenza della base dati, è necessario sapere quando il comune ha operato per l'ultima volta sul soggetto. Abbiamo tre date "topiche": prima iscrizione, decorrenza residenza, ultima variazione apr. Se sono correttamente impostate (ad esempio, per un iscritto il 15 marzo di un comune subentrato il 20 marzo, le tre date dovrebbero coincidere) riusciamo a gestire correttamente questi movimenti. Stiamo ovviamente scrivendo un documento che integrerà le specifiche.

**Comment by ATropeano** [comment]
Per facilitare le operazioni di annullamento di Iscrizioni APR4, forse sarebbe comodo poter "annullare" in un'unica operazione, tutte le operazioni che fanno riferimento a uno specifico procedimento...

**Comment by gcarbonin** [comment]
Gli annullamenti per ripristino possono riguardare una persona o tutte le persone che si sono trasferite.
