### ISSUE TITLE
[3002] datiSoggetto - erroriAnomalie

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#490]
buongiorno.

una richiesta di chiarimento:

prendendo ad esempio il soggetto con idSchedaANPR 321173 (ambiente di TEST - comune di FAENZA)
nel foglio di excel scaricato dal monitoraggio anomalie della web-app risultano 4 anomalie da subentro:
EC042 - Comune di matrimonio:MAGLIANO ROMANO(RM) non esistente alla data   01/06/1953
EC007 - Comune di nascita:MAGLIANO ROMANO(RM) non esistente alla data 18/10/1934
EC081 - Comune dell'atto di matrimonio:MAGLIANO ROMANO(RM) non esistente alla   data 01/06/1953
EC075 - Comune dell'atto di nascita:MAGLIANO ROMANO(RM) non esistente alla data   18/10/1934

invocando il servizio 3002 (ma anche nella consultazione da web-app), invece ritorna una sola anomalia.
nello specifico:
EC075 - Comune dell'atto di nascita:MAGLIANO ROMANO(RM) non esistente alla data 18/10/1934

c'è una ragione? oppure la consultazione ritorna un valore parziale?

grazie.
Alessandro Monopoli ADS

**Comment by cmigliardi** [comment]
grazie per la segnalazione, stiamo verificando

**Comment by cmigliardi** [comment]
come anticipato per le vie brevi, il servizio 3002 ad oggi è disponibile in ambiente di test-comuni e pre-subentro. Potete riprovare?  La web-app sarà aggiornata successivamente.

**Comment by AMonopoliADS** [comment]
la prova eseguita su ambiente di TEST ha dato esito positivo.
adesso il ws di consultazione ritorna tutte le anomalie da subentro associate al soggetto.

approfitto per segnalare anche qui, che il tipoErroreAnomalia (nel caso del ws 3002) ritorna valore '1'.
se è corretto così, ed il valore va aggiunto a quelli già conosciuti ('E' e 'W') allora è necessario aggiornare la documentzione, perchè anche le specifiche excel riportano solo i due valori 'E' e 'W'

grazie.

**Comment by cmigliardi** [comment]
grazie per la segnalazione, verifichiamo

**Comment by gcarbonin** [comment]
Dal momento che si tratta di anomalie, il valore associato e' per definizione W.
"1" si riferisce al tipo scheda:
1 – scheda apr
2 – scheda aire
3 – famiglia
4- convivenza
5 – famiglia aire
