### ISSUE TITLE
[2003] Emigrazione successiva a Mutazione altriDati - Errore EN240

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#491]
ambiente di PRODUZIONE - comune di FAENZA - idOperazioneComune 2018000182

si tratta di una comunicazione di emigrazione con dataDecorrenza 29/12/2017 e dataDefinizionePratica 04/01/2018
la comunicazione non viene accettata a causa di questo errore:
```
<errore>
  <codiceErroreAnomalia>EN240</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto </testoErroreAnomalia>
</errore>
```

verificando l'elenco delle operazioni sul soggetto, si vede che il cliente, in data 02/01/2018 ha eseguito (tramite web-app) la rettifica della posizione professionale (attivando solo il tipoMutazione '07')

è possibile che una mutazione di questa natura incida sull'operazione di emigrazione?
come fare per fare accettare la comunicazione?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
buongiorno.

il caso è stato risolto annullando l'operazione che bloccava l'emigrazione e ripendo l'invio di quest'ultima.
restiamo comunque in attesa, ti conoscere la causa del blocco e se, come ipotizzato, il tipoMutazione '7' bloccava la cancellazione

grazie.

**Comment by AMonopoliADS** [comment]
non abbiamo mai avuto alcun riscontro su questa segnalazione e oggi si pone una situazione analoga sulla quale però non si riesce ad intervernire.

sempre ambiente di PRODUZIONE, comune FAENZA, idSchedaSoggettoANPR 19149267

dobbiamo comunicare l'emigrazione del soggetto con dataDecorrenza 14/03/2018.
il web-service ci blocca perchè esistono operazioni con data di decorrenza successiva.
in effetti il cliente ha eseguito due mutazioni di dati (una via web-service ed una via web-app) con dataDecorrenza 16/03/2018

contrariamente alla precedente situazione, in questo caso non è possibile annullare le mutazioni del 16/03
nel tentativo di annullare l'operazione eseguita da web-app (la più recente) il sistema risponde con errore:
Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione. (Codice: EN234) 

come procedere, al fine di perfezionare l'emigrazione con decorrenza 14/3?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
potete darmi un riscontro su questa issue?
il cliente ha una certa urgenza.
grazie

**Comment by frmariani** [comment]
Risolto via mail in data 22/03/2018
