### ISSUE TITLE
[2003] Stato Estero 324 - Errore EC030

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#492]
ambiente di PRODUZIONE - comune di MEDICINA - idOperazioneComune 2018000144

La comunicazione non viene accettata a causa di questo errore:
EC030 -  Stato estero di nascita 324 inesistente sulla tabella di riferimento.

grazie.
Christian Olivato ADS

**Comment by gcarbonin** [comment]
si tratta di una cancellazione?

**Comment by COlivatoADS** [comment]
Sì, è una cancellazione (servizio [2003]).
Grazie

**Comment by gcarbonin** [comment]
E' stato indicato anche il luogo di nascita come parametro di ricerca e la stringa presente nella richiesta non coincide perfettamente con quella associata al codice 324. Per effettuare la cancellazione è sufficiente indicare soltanto il cognome ed il nome oltre a un identificativo (CF o idanpr).

**Comment by AMonopoliADS** [comment]
buongiorno

premetto che dopo tutte le cancellazioni effettuate fino ad oggi (comunicate con la stessa modalità) questa è la prima occasione in cui si verifica un errore di questo tipo.

immaginando che il problema potesse essere la descrizione dello stato, abbiamo visto che la descrizione che passavamo originariamente era leggermente diversa da quella documentata in tabella (quella pubblicata su anpr.interno.it), infatti passavamo:
TERRITORI DELL'AUTONOMIA PALESTINESE (che, peraltro, è la descrizione che il soggetto ha già tra i suoi dati in ANPR)
al posto di 
TERRITORI DELLA AUTONOMIA PALESTINESE
(vedere uno dei primi tentativi, es. idOperazioneComune 2018000142, ritornata con errore EC030)

abbiamo quindi proceduto con la modifica della descrizione, uniformandola a quella pubblicata, ma l'errore è stato il medesimo (vedere idOperazioneComune 2018000144)

ad oggi, abbiamo concluso con successo il procedimento, seguendo il suggerimento di togliere il luogoNascita dalle generalitaPerRicerca, ma ci restano dei dubbi sul motivo che ha scatenato l'errore, nonostante gli interventi eseguiti, e se questo potrà verificarsi anche in altre circostanze.

se possibile avere qualche dettaglio in più in merito...

grazie mille
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Lo "stato" indicato come luogo di nascita non è utilizzabile come tale ma solo per la residenza; se indicato scatta il controllo.
