### ISSUE TITLE
Nuovo Comune non presente sulla Tabelle di decodifica "Archivio storico dei Comuni" 

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#494]
Buongiorno
siamo venuti a conoscenza (per inserire delega per matrimonio da celebrare in altro comune) che i comuni Rio Marina e Rio nell'Elba si sono fusi in unico comune denominato RIO dal 1.1.2018.
Sulla tabella dei comuni "Archivio storico dei Comuni" Rio Marina e Rio nell'Elba risultano correttamente cessati il 31.12.2017, ma non è presente il nuovo comune con dt decorrenza 1.1.2018.
E' possibile inserire il nuovo comune?
Grazie
Cordiali saluti
Ufficio Procedure Informatiche

**Comment by gcarbonin** [comment]
Dove manca questo comune? E' presente in tutti gli ambienti e anche nella tabella che si scarica da www.anpr.interno.it

**Comment by UpiTorino** [comment]
Buongiorno
ho eseguito:
browser Google Crome ANPR,
selezionato ANPR:Home,
nel menù a dx Tabelle di decodifica selezionato Archivio storico dei comuni
(05-01-2018)-xls,
aperto il file denominato "tabella 3 archivio comuni 20180105(2).xls"
nelle colonne F "Denominazione_IT" e G "DenomTranslitterata" non è presente
il comune.
Vedo ora, però, riprovando, che è presente nell'ultima riga del file...
sarebbe più facile da reperire se inserito in ordine alfabetico.
Grazie
Buon Anno!
Stefania Amprimo

2018-01-11 14:48 GMT+01:00 gcarbonin <notifications@github.com>:

**Comment by gcarbonin** [comment]
Buon anno a voi. Al prossimo aggiornamento ordiniamo per denominazione_it

**Comment by UpiTorino** [comment]
Grazie mille!!
Stefania

2018-01-11 15:31 GMT+01:00 gcarbonin <notifications@github.com>:
