### ISSUE TITLE
ERRORE PRATICA EMIGRAZIONE  MIGRANTI

### ISSUE THREAD

**Issue by santannastreet** [italia/anpr#496]
Le Questure  ai migranti rilasciano dei permessi provvisori contraddistinti con ID che hanno una validità di circa 6 mesi  con  un codice fiscale alfa-numerico ed in questi ultimi mesi numerico.
Durante la permanenza in queste convivenze i migranti attendono che le Commissioni Prefettizie valutino la richiesta presentata dalle Cooperative o Associazioni per il riconoscimento o meno di rifugiato etc  e spesso  i dati anagrafici  inseriti durante l'iscrizione   vengono  mutati  e riportati sul permesso di soggiorno a loro rilasciato con eventualmente un nuovo codice fiscale e spesso questi
nuovi dati non vengono comunicati all' anagrafe, in quanto questi soggetti sono stati allontanati per termine del progetto.
Purtroppo gli  APR di emigrazione che mi pervengono da altri Comuni riportano i nuovi dati ed il 
sistema ANPR non mi permette di chiudere la pratica  per  errore EN069 ERRORE BLOCCANTE
Come si puo' risolvere il problema?

**Comment by gcarbonin** [comment]
Il problema è molto complicato anche da capire. Ci contatti telefonicamente e vediamo di risolverlo

**Comment by RBiasi** [comment]
Scusate come è poi stata risolta?

**Comment by RBiasi** [comment]
Scusa Gina stavo cercando info sulla gestione dei CF numerici. Se sono gestiti in ANPR e come. Mi sai dare delle indicazioni?
