### ISSUE TITLE
Motivo cancellazione APR

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#498]
In seguito alla segnalazione di un comune è stata aggiornata in ambiente di test e presubentro la descrizione del motivo di cancellazione APR con codice 8 da "Trasferimento di residenza (Iscrizione all'AIRE)" a "Trasferimento di residenza per Iscrizione nell'AIRE di un Comune non subentrato". Se non perverranno controindicazioni da parte di altri comuni, procederemo alla modifica anche in ambiente di produzione.

**Comment by bfilipazzi** [comment]
Il trasferimento della residenza all'estero di un cittadino italiano comporta la sua iscrizione all'AIRE, il comune di competenza è invariabilmente il comune di ultima residenza. Successivamente l'interessato può richiedere il passaggio di competenza al comune di nascita, questo per consentirgli l'iscrizione nelle liste elettorali di questo secondo comune, ove il soggetto lo ritenga di sua convenienza. La circolare 9 / 2003 del Min. Interno descrive questa procedura.

In altre parole: è previsto il trasferimento dall'AIRE del comune A all'AIRE del comune B, ma non l'espatrio dal comune A all'AIRE de
[Circolare n. 9_2003_0.pdf](https://github.com/italia/anpr/files/1630978/Circolare.n.9_2003_0.pdf)
l comune B.

Di conseguenza non mi spiego il significato della "cancellazione da APR per iscrizione nell'AIRE di un altro comune". A mio parere questa causale di cancellazione non dovrebbe essere a disposizione.
Filipazzi - Maggioli

**Comment by MarcoMigliori** [comment]
Nemmeno il modello APR/4 Istat mi sembra prevedere il caso di cancellazione APR per iscrizione AIRE in altro comune.

Domanda per capire come intendete la struttura. Io avevo ipotizzato che il codice 8 servisse per mantenere lo storico degli eventi. Qualcosa tipo:
id cittadino / apr / data iscrizione apr / data subentro
id cittadino / apr / data cancellazione (stessa iscrizione aire) / motivo cancellazione 8
id cittadino / aire / data iscrizione (stessa cancellazione apr) / motivo iscrizione C01

Dal tipo di modifica proposta, mi sembra invece di intuire che non esiste un motivo di cancellazione da apr contestuale alla iscrizione aire.

**Comment by gcarbonin** [comment]
Stiamo parlando di iscrizione nell'AIRE di un comune non subentrato

**Comment by bfilipazzi** [comment]
Sì, trasferimento nell'aire del comune B di persona fin lì residente nel comune A.
Non è previsto dalla norma, come ho scritto nel precedente commento.
Nel caso specifico il comune B non è subentrato, per tale ragione dovrebbe richiedere con i tradizionali mezzi di corrispondenza al comune A una cancellazione dai residenti di A, richiesta che si fa con un APR4, il quale APR4 non prevede il caso visto che non è compatibile con la norma.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
E' una cancellazione per emigrazione, prevista dalla norma.

**Comment by bfilipazzi** [comment]
Ho allegato una circolare al primo commento. A me sembra chiara.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Anche a me ma non fa riferimento alla cancellazione

**Comment by Raffive** [comment]
E' un trasferimento tra AIRE  si cancella dall'aire comune A si fa un APR scrivendo a mano il motivo e il comune B lo iscrive per altri motivi direttamente in AIRE. Non si iscrive in APR perché non ha la dimora abituale nel comune B.
avete ragione tutti e due: è una cancellazione ma IN AIRE.
Raffaella

**Comment by gcarbonin** [comment]
E' una cancellazione dall'aire del comune all'aire di un altro comune non subentrato. Se entrambi fossero subentrati ci sarebbe una mutazione

**Comment by MarcoMigliori** [comment]
Mi sto perdendo con gli ultimi messaggi.
Aldilà delle considerazioni successive sulla normativa, mi pare che la segnalazione iniziale parli del motivo di cancellazione dalla APR (codice 8), per iscrizione Aire in un comune NON subentrato. 

Quindi stiamo parlando di cancellazione di un residente da ANPR, per iscrizione all'AIRE in altro comune.
In questo caso ci avvisano che 
1) viene consentita la casistica 
2) viene cambiata la descrizione riportando in ANPR sul residente cancellato la motivazione 
_Trasferimento di residenza per Iscrizione nell'AIRE di un Comune non subentrato_

**Comment by Raffive** [comment]
D'accordo, ma prima del trasferimento o mutazione in AIRE  ci deve essere l'iscrizione in Aire che è fatta dal comune di residenza, fintanto che i comuni continueranno a gestire la popolazione in modo "misto" subentrati e non subentrati resta, secondo me la necessità che sia il comune che attivi il procedimento sulla scorta della comunicazione del consolato. A subentro di tutti i comuni si può fare una riflessione, e codificare in modo diverso ora mi sembra prematuro.
grazie
Raffaella

**Comment by Raffive** [comment]
p.s. nessun U.d.A. la userebbe .. non esiste ancora normativamente..

**Comment by MarcoMigliori** [comment]
Io posso essere d'accordo con lei.
Ma non è quello che ci segnala Sogei: stiamo parlando dei motivi di cancellazione previsti solo per APR, per AIRE ce ne sono altri, quindi credo di aver capito bene.
ANPR consentirebbe di cancellare un residente, perchè un altro comune lo iscrive all'AIRE. 
Non c'è (da programma) l'obbligatorietà del passaggio che lei descrive: 
_D'accordo, ma prima del trasferimento o mutazione in AIRE ci deve essere l'iscrizione in Aire che è fatta dal comune di residenza_

**Comment by Raffive** [comment]
tutto parte e ritorna in APR/ANPR .... ma siete troppo avanti...aspettateci, avete una visione che ancora per noi non è realtà, 
secondo me siamo troppo pochi comuni subentrati per codificare altre funzionalità che avranno un senso più avanti quando si invertirà la situazione ovvero più comuni subentrati che no e quindi finalmente capiremo e vedremo che l'anagrafe è nazionale
ci sono ancora tante cose da sistemare che ci creano problemi quotidianamente soprattutto con AE che ci blocca quando gestiamo le comunicazioni dallo stato civile per esempio..
liberateci di questo intanto.... aspettiamo di vedere come funziona veramente ANPR e saremo più sollevati e certi (questo è il vero punto) che tutto funzioni ..
Raffaella

**Comment by gcarbonin** [comment]
L'utilizzo delle varie casistiche previste dalle tabelle dei motivi di cancellazione sta un po' alla responsabilità dell'ufficiale di anagrafe. 
Un vostro collega per il tramite del suo fornitore ha chiesto di modificare una descrizione che si trova nei motivi di cancellazione dei **residenti** e questo abbiamo fatto; evidentemente questo comune si comporta in modo differente.
Lo stesso motivo, in ogni caso,  è presente anche nella tabella dei motivi di cancellazione AIRE.

**Comment by bfilipazzi** [comment]
Ho immaginato sin dall'inizio che qualcuno voglia gestire il passaggio diretto di un residente nel comune A all'AIRE del comune B, e ripeto che non è una procedura prevista dalle norme e dalla prassi.
Per questo mi sono permesso di segnalare che ANPR consentirebbe così di gestire un movimento anagrafico non previsto.
Non c'è simmetria negli incroci APR-AIRE, e questo è legato ai procedimenti.
L'iscritto AIRE quando passa in APR perché rimpatria lo fa scegliendo liberamente un comune italiano in cui prendere la dimora, che ovviamente può essere diverso da quello di iscrizione AIRE.
Non è vero il contrario, il residente in Italia che si trasferisce poniamo a Londra rende la prescritta dichiarazione al consolato di Londra il quale la trasmette al comune di residenza in Italia, per il passaggio all'AIRE. La comunicazione va dal consolato al comune di ultima residenza, senza alternative.
Successivamente l'interessato può chiedere il passaggio all'AIRE di un altro comune, ma con una seconda distinta operazione AIRE su AIRE, spiegata dalla circolare citata all'inizio del thread.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Ringraziandovi per la partecipazione, abbiamo chiarito sia con il comune che ha inoltrato la richiesta di variazione che con il Ministero dell'Interno. Provvediamo quindi ad eliminare questo motivo di cancellazione in quanto non applicabile.
