### ISSUE TITLE
[1002] Ripristino Posizione Precedente - Errore EF007

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#499]
ambiente di PRODUZIONE - comune di FAENZA

buongiorno.

si sta tentando di iscrivere, con motivo '10' - Ripristino Posizione Precedente, un soggetto emigrato prima del subentro.

trattandosi di Intestatario Scheda, la sua cancellazione (precedente al subentro) aveva prodotto la modifica del rapporto di parentela della moglie, che diventava I.S.

oggi, ripristinando la posizione precedenete come previsto dalla normativa, stiamo tentando di re-iscriverlo come I.S., ma l'operazione (idOperazioneComune 2018000980) segnala, direi giustamente:
```
<errore>
  <codiceErroreAnomalia>EF007</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Intestatario della scheda famiglia/convivenza gia' presente</testoErroreAnomalia>
</errore>
```

allora abbiamo tentato, prima di procedere con l'iscrizione (servizio 1002), di ripristinare anche il rapporto di parentela della moglie (idOperazioneComune 2018000801), ma il requisito che prevede che all'interno della comunicazione compaia anche l'Intestatario Scheda, fa scattare questo errore:
```
<errore>
  <codiceErroreAnomalia>EF044</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>I soggetti devono appartenere alla stessa famiglia dichiarata</testoErroreAnomalia>
</errore>
```
in quanto, coerentemente alla situazione storica, l'intestatario che viene indicato è il soggetto di cui alla comunicazione di iscrizione... non ancora presente.

come sblocchiamo questa situazione?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
L’operazione di iscrizione con motivo 10 -  ripristino della posizione precedente,  non può modificare contestualmente anche le relazioni di parentela, pertanto le operazioni devono necessariamente essere eseguite nel seguente ordine:
1002 Iscrizione del soggetto;
5001 tipo mutazione 2 per la modifica delle relazioni di parentela.

**Comment by AMonopoliADS** [comment]
per essere sicuro di avere capito bene: 
iscrivo il soggetto da ripristinare con servizio 1002, indicando una relazione di parentela diverso da I.S., e solo dopo dovremmo eseguire la mutazione delle relazioni di lui e della moglie?

**Comment by gcarbonin** [comment]
si

**Comment by AMonopoliADS** [comment]
ok.

personalmente non mi piace l'idea di creare un frammento di storia familiare dove il soggetto presenta una posizione che nella realtà non ha mai avuto.
in ogni caso condivido la soluzione con il cliente e sento cosa ne pensa...

per dare un quadro completo chiedo: 
che effetti avrà questa soluzione a livello di storico?
la mutazione di relazioni avrà la stessa decorrenza del ripristino (ipotizziamo 10/10/2017) 

consultando la scheda individuale al 10/10/2017, che legame di parentela troveremo per il soggetto?

grazie

**Comment by gcarbonin** [comment]
Attualmente questo tipo di consultazione storica non c'è. In ogni caso, occorre sempre tener presente che quando è stato cancellato il soggetto e inserito il nuovo intestatario, i dati sono visibili agli altri comuni e sono stati forniti alle PA collegate. Quindi questa informazione non può sparire come se mai fosse stata presente in ANPR

**Comment by AMonopoliADS** [comment]
stiamo tentando di percorrere la strada suggerita per vederne il risultato finale.
il soggetto da ripristinare (idSchedaANPR 19893491) è stato iscritto con idOperazioneComune 2018002029, assegnandogli il legame di "altro parente".
adesso stiamo tentando di aggiornare i rapporti di parentela, assegnando a lui il legame 'IS' e all'attuale IS il legame di "moglie".
l'operazione ritorna l'errore:
EN447 - E - La data decorrenza dell'operazione e' incongruente con la data di ingresso in famiglia del soggetto.

abbiamo bisogno del vostro supporto per interpretare l'errore.

il soggetto in questione è stato iscritto per ripristino con decorrenza 6/10/2017 e ci si aspetta di poter dare la stessa decorrenza alla sua posizione di intestatario scheda.
(si veda idOperazioneComune 2018002035)

grazie.
Alessandro Monopoli ADS
(ambiente di PRODUZIONE - comune di FAENZA)

**Comment by gcarbonin** [comment]
Credo che il problema sia sulla persona che deve diventare moglie, che ha una data di inizio validita' 9-10-2017.

**Comment by AMonopoliADS** [comment]
alla moglie stiamo tentando di assegnare la stessa data di decorrenza della variazione dell'intestatatario:
```
<legameSoggetto>
  <tipoLegame>3</tipoLegame>
  <dataDecorrenza>2017-10-06</dataDecorrenza>
  <codiceLegame>2</codiceLegame>
</legameSoggetto>
```
non dovrebbe essere così?

**Comment by frmariani** [comment]
la risoluzione del problema necessita un intervento. Avviseremo quando sarà possibile riprovare

**Comment by frmariani** [comment]
l'intervento è stato effettuato, potete riprovare.
Chiedo scusa per il ritardo della risposta.

**Comment by AMonopoliADS** [comment]
operazione terminata con successo.
grazie
