### ISSUE TITLE
Iscrizione per provenienza da altro comune - mutazione motivo iscrizione

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#50]
Buonasera.
Ripropongo qui un quesito inviato il 17 marzo alla mail delle specifiche.

Il caso è: iscrizione da comune italiano non subentrato.
Il processo logico è:
1) il cittadino si presenta e dichiara l'iscrizione di un nucleo di 4 persone,
   tutte provenienti da FIRENZE (comune non subentrato).
2) comunicazione apr/4 al comune di Firenze che risponde:
  - cittadino A cancellato dall'apr
  - cittadino B cancellato dall'apr
  - cittadino C **irreperibile**
  - cittadino D **sconosciuto**

Nella documentazione viene indicato di utilizzare il servizio
5008 - mutazione altri dati, per la risposta.
Ma non posso cambiare il motivo di iscrizione in ANPR.
Questo esempio (un caso limite in questa forma ma in altre forme succede)
come dovrebbe essere trattato per assicurare:
-  il corretto conteggio statistico sul D7/B ?
- la corretta registrazione del motivo di iscrizione, diverso da quanto inizialmente dichiarato

Ringrazio in anticipo
Marco Migliori (PAL Informatica)

**Comment by gcarbonin** [comment]
Quanto da lei richiesto rientra tra gli interventi evolutivi che stiamo pianificando.  Per quanto riguarda il modello D7/B non ci sono problemi in quanto con il subentro cessano questi obblighi verso ISTAT.

**Comment by gcarbonin** [comment]
Il motivo di iscrizione è ora modificabile
