### ISSUE TITLE
Tabelle di Riferimento: Consolati - 24 (doppi apici)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#500]
riporto come esempio il caso del consolato 2670100, che nella tabella pubblicata su anpr.interno.it ha queste caratteristiche:
2670100 | 267 | COSTARICA | SAN JOSE'' DE COSTARICA | AMBASCIATA D''ITALIA

la descrizione della sede, con la presenza dei doppi apici, non viene accettata dal web-service segnalando
```
<errore>
  <codiceErroreAnomalia>EC034</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Codice consolato di residenza 2670100 incongruente con la descrizione</testoErroreAnomalia>
</errore>
```
al contrario, modificando con apice singolo, l'operazione va a buon fine.

nella issue #309, questa situazione era stata identificata come bug, e si attendeva la pubblicazione della nuova tabella, ma l'xls disponibile su web sembra ancora non aggiornato.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
L'aggiornamento e' stato eseguito.
