### ISSUE TITLE
Chiarimento su ripristino posizione precedente

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#503]
Il signor X è emigrato dal comune A al comune B, entrambi allora non subentrati.
Dopo la cancellazione di X nel comune A, il comune A è subentrato.
Il comune B, tuttora non subentrato, comunica ad A di aver rigettato l'iscrizione.
Il comune A deve ripristinare la posizione anagrafica di X.
X non è transitato in ANPR perché già cancellato al momento del subentro.
Per iscrivere nuovamente X tra i residenti di A è corretto usare il servizio 1002 con 
motivoIscrizione "10 - Ripristino posizione precedente" con decorrenza dalla data di 
cancellazione? Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
corretto
