### ISSUE TITLE
Ripristino posizione emigrato

### ISSUE THREAD

**Issue by MARIAPIATREZZI** [italia/anpr#504]
Abbiamo effettuato una emigrazione in comune non subentrato di alcuni componenti di una famiglia (3 su 4).

Dopo il periodo necessario agli accertamenti il comune di emigrazione ci ha respinto un individuo.

Nel tentativo di ripristinare la sua posizione come residente (annullando l'operazione relativa alla sua emigrazione) abbiamo ottenuto l'errore che l'operazione non è annullabile in quanto non risulta essere l'ultima eseguita sul soggetto/famiglia.

Contattandovi ed eseguendo i controlli del caso ci avete detto che le operazioni di cancellazione movimentano tutta la famiglia per cui sarebbe necessario annullare tutte e 3 le cancellazioni (riportando tutti gli individui residenti) per poi rieseguire la cancellazione dei soli individui accettati dal comune di emigrazione.

Questa soluzione non è a nostro avviso applicabile in quanto ci costringe a modificare lo stato corretto di individui annullando e rieseguiendo operazioni valide che avrebbero conseguenze anche sul calcolo delle statistiche in quanto effettuate in momenti differenti.

Inoltre ci chiediamo cosa succederebbe nel caso vengano movimenti ulteriormente altri individui appartenenti alla famiglia (in questo caso specifico nel frattempo l'ultimo individuo appartenente alla famiglia è emigrato a sua volta).

La soluzione a questo problema riveste carattere di urgenza in quanto attualmente non riusciamo a ripristinare lo stato di un individuo che deve essere re-iscritto in elettorale per le prossime elezioni, come già comunicato verbalmente a Vinzani Roberta.

**Comment by gcarbonin** [comment]
Chiusa quanto lo stesso argomento è trattato nella issue #783
