### ISSUE TITLE
Risoluzione disallineamenti ANPR-AE e notifiche

### ISSUE THREAD

**Issue by busaster** [italia/anpr#505]
Buongiorno

nei giorni scorsi il comune di Lucca (ambiente di produzione) ha usato la funzione in oggetto per risolvere un disallineamento, in particolare si trattava di un soggetto con nome corretto in AE ma errato in ANPR (errata iscrizione).
L'operazione quindi ha modificato in ANPR il nome inserendo quello di AE.
A seguito dell'operazione si è dovuto poi aggiornare la base dati locale.
Al momento lo abbiamo fatto a mano ma pensavamo in futuro di appoggiarci alle notifiche che ANPR produce.
Mi aspettavo dunque di trovare, cercandole con la webapp, delle  "notifica AE" nel periodo 1/1/2018 - oggi ma non ne ho trovata nessuna.
Chiedo dunque se e come l'operazione sopra descritta venga notificata al comune.

Grazie

**Comment by gcarbonin** [comment]
Le notifiche che AE produce riguardano le variazioni di dati o del codice fiscale che avvengono su iniziativa degli uffici entrate o della stessa Agenzia: il caso tipico è la risoluzione di una omocodia con attribuzione del codice fiscale definitivo; in questo caso, in ANPR (e nella base dati del comune) c'è il provvisorio che si può aggiornare con la notifica. In questa prima fase le notifiche AE non sono recapitate al comune (in molti casi non è univocamente determinabile la persona cui sono associate) ma solo dalla WEB application.
Nel caso dell'ambiente di Lucca, la funzione di risoluzione dei disallineamenti con AE dà origine ad una mutazione che è interrogabile con le modalità ordinare.
