### ISSUE TITLE
[3003] Elenco Operazioni: Annullamenti / Duplicazioni

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#506]
ambiente di PRODUZIONE - comune di FAENZA

salve.
volevo chiedere un chiarimento e segnalare un'anomalia:

1. chiarimento: 
soggetto iscritto da zero con servizio 1002. 
il cliente si trova nella necessità di annullare la comunicazione e re-inviarla a causa di errori materiali nella prima fase che ha generato l'iscrizione.
l'operazione viene annullata e poi ripetuta.
oggi il soggetto ha idSchedaANPR 19707263 (id, diverso da quello assegnato con la prima iscrizione, in quanto annullata...)
se interrogo l'elenco delle operazioni per codice fiscale (servizio 3003 - idOperazioneComune 2018300236) trovo solo le operazioni avvenute dall'ultima iscrizione in avanti, non anche l'iscrizione pregressa ed il successivo annullamento.
è normale così?
non si perde un pezzo di storia delle operazioni eseguite sul soggetto?

2. anomalia:
nel ambito della richiesta di cui sopra (idOperazioneComune 2018300236), il web-service ritorna 4 operazioni a carico del soggetto, ma due (quelle relative all'operazione 5008, con tipoLavorazione '2') sono identiche, e fanno riferimento alla stessa operazione.

grazie.
Alessandro Monopoli ADS

**Comment by azabatta** [comment]
Buonasera, 
la modifica è stata portata in ambiente di PRODUZIONE. E' possibile sottomettere nuovamente la richiesta.
