### ISSUE TITLE
pre subentro anpr  errore nell' attribuzione comune

### ISSUE THREAD

**Issue by giovannidestefano** [italia/anpr#507]
Buonasera,
stiamo inviando i dati in pre subentro per il  Comune di Cava dei tirreni 
per un atto di nascita del 1932 il comune di registrazione atto e di nascita è 
codice istat '061104'  corrispondente a "SAN MARCO EVANGELISTA" "CE" 
e otteniamo il seguente errore:

Scheda Individuale APR | EC075 | Comune dell'atto di nascita :SAN MARCO   EVANGELISTA(CE) non esistente alla data

Giovanni De Stefano 
Advanced Systems

**Comment by gcarbonin** [comment]
Il comune è cessato nel 1928 (incorporato in Caserta)  e nuovamente istituito nel 1975. Si tratta in ogni caso di un'anomalia che non comporta alcun problema (ne in pre-subentro nè nelle successive movimentazioni)
