### ISSUE TITLE
Correzione indirizzo

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#508]
Chiavari - Produzione

Il Comune di Chiavari mi scrive:
"In data 5.12.2017 una famiglia ha richiesto l'iscrizione in Chiavari al civico 463 di VIA XXXXX.
Il giorno 8.2.2018 ho chiuso la pratica di residenza.
Immediatamente dopo il vigile mi scrive che il civico corretto è 457/C.
Ho fatto un cambio di indirizzo di ufficio in pari decorrenza dell'iscrizione anagrafica. Il certificato storico anpr porta entrambi gli indirizzi.
Ho parlato con la Dott.ssa Vinzani la quale mi ha chiesto di segnalare la situazione sul forum."

In data 07 12 2017
idOperazioneComune 88576
Iscrizione per immigrazione della signora P.A.
VIA XXXXX 463
decorrenzaResidenza 05 12 2017

In data 08 01 2018
idOperazioneComune 92297
Mutazione della signora P.A.  
VIA XXXXX 457 C
decorrenzaResidenza 05 12 2017

Il certificato storico di residenza scrive:
Risulta iscritta con i seguenti dati:
Comune di CHIAVARI (GE) dal 05712/2017
   Indirizzo VIA XXXXX N. 457 - Lettera: C dal 05/12/2017
   Indirizzo VIA XXXXX N. 463 dal 05/12/2017

Chi legge il documento senza conoscere la situazione non capisce dove risiede la signora P.A.
E' il caso di aggiungere che il gestionale nasconde il dato precedente che è stato oggetto di correzione, lo conserva ma lo nasconde nelle consultazioni e nelle certificazioni e lo comunica all'ufficio elettorale e agli altri destinatari interessati alla notizia, cioè tutti a coloro cui aveva comunicato l'iscrizione.

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Come detto molte volte, l'indirizzo non si  può nascondere: è stato comunicato ad altri enti e gli altri comuni vedono i dati. Stiamo ipotizzando  una modifica per evidenziare il tipo di variazione (a seguito di accertamento d'ufficio o qualcosa di simile). Forse nello storico andrebbe riportata anche la data di cessazione dell'indirizzo.
