### ISSUE TITLE
[Test Subentro] Errore CN009 tramite Web Services

### ISSUE THREAD

**Issue by DomenicoGallo** [italia/anpr#51]
Salve,
effettuando l'invio del file per il subentro, in ambiente di test, per il Comune di Cittanova, riceviamo come risposta il seguente errore:

`<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <a:RispostaS001 xmlns:a="http://www.sogei.it/ANPR/S001subentro">
      <a:rispostaKO>
        <testataRisposta>
          <idOperazioneComune>2011</idOperazioneComune>
          <codMittente>080028</codMittente>
          <codDestinatario>ANPR00</codDestinatario>
          <operazioneRichiesta>S001</operazioneRichiesta>
          <dataOraRichiesta>2017-03-24T15:25:37.8481433+01:00</dataOraRichiesta>
          <idOperazioneANPR>0</idOperazioneANPR>
          <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
          <errore>
            <codiceErroreAnomalia>CN009</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Errore con descrizione non disponibile</testoErroreAnomalia>
          </errore>
        </listaErrori>
      </a:rispostaKO>
    </a:RispostaS001>
  </soapenv:Body>
</soapenv:Envelope>`

tale codice di errore non è presente nella lista fornita.
Restiamo in attesa di  un vostro riscontro.
Cordiali Saluti

Domenico Gallo
KIBERNETES S.r.l.

**Comment by gcarbonin** [comment]
E' un problema di formattazione dei dati. Da ieri è disponibile in ambiente di test-comuni un pacchetto che esegue localmente una validazione formale del file. Puo' utilizzare quello per avere informazioni di dettaglio.
