### ISSUE TITLE
Correzione data di decesso in ANPR

### ISSUE THREAD

**Issue by Elenalomazzi** [italia/anpr#510]
Buongiorno,
per errore sono stati registrati i decessi di due cittadini con giorno e mese corretto, ma come avvenuti nell'anno 2017 invece che nell'anno 2018.  Stiamo lavorando con il web services, e pur avendo a disposizione una funzione di variazione per errore nel programma in locale, non riusciamo a correggere l'anno.
Abbiamo però notato che la correzione dei dati di nascita è fattibile. E' possibile prevedere la stessa cosa per i decessi?
Ringrazio per l'attenzione.

Elena Lomazzi
Comune di Biassono (MB)

**Comment by gcarbonin** [comment]
Buongiorno. Trattandosi di scheda archiviata, le mutazioni non sono possibili. Occorre annullare la cancellazione ritrasmettendola con i dati corretti.

**Comment by Elenalomazzi** [comment]
Grazie.
Ho seguito il suo consiglio, ma ora mi dà questo errore : "ERRORE DA ANPR: 
ES101 - Identificativo soggetto attribuito da ANPR non presente o scheda archiviata"

**Comment by gcarbonin** [comment]
Non vedo l'annullamento della cancellazione: vedo nuove cancellazioni della stessa persona. Il messaggio esce perchè si sta cercando di inserire una cancellazione per una persona già cancellata

**Comment by Elenalomazzi** [comment]
Tentata la cancellazione, sempre in web service, dell'evento ANPR. 
Ora il messaggio è questo : "ERRORE DA ANPR:  EN077 - L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa."

**Comment by gcarbonin** [comment]
Mi dovrebbe dare l'identificativo ANPR

**Comment by Elenalomazzi** [comment]
codice soggetto : 18932996 e codice soggetto : 18930396

**Comment by gcarbonin** [comment]
Stiamo verificando

**Comment by frmariani** [comment]
la risoluzione del problema necessita un intervento. Avviseremo quando sarà possibile riprovare
