### ISSUE TITLE
Tabella Stati esteri - Isola di Man , incongruenza Istat-ANPR

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#513]
Buongiorno,
in merito alla codifica del territorio estero Isola di Man, segnalo che per l'Istat e' codificato come 959 ( vedi Allegato 2 - Codice dei paesi esteri in ordine alfabetico della circ. Istat prot. 1423104 del 21/12/2017 su "Rilevazioni demografiche e sanitarie per l'anno 2018") ed e' previsto l'utilizzo come stato estero di nascita nei modelli Istat del portale GINO e di conseguenza nel nostro applicativo anagrafico, mentre nella vostra tabella 2 degli stati esteri la codifica Istat risulta 228 che in realta' non e' una codifica Istat ma quella di AnagAire ed e' previsto l'utilizzo solo come stato di residenza estera. 

Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
La codifica di stati esteri e l'indicazione se si tratta di stato o di territorio deriva dal Ministero degli Affari Esteri. I territori, in particolare, possono essere utilizzati solo come luogo di residenza. Posso verificare con il Ministero degli Affari esteri  se c'è qualche aggiornamento in proposito. Esistono passaporti rilasciati dall'isola di man?

**Comment by CarlaMusian** [comment]
Di questa cosa non sono al corrente, mi pare di si' , puo' verificare qui:
http://www.consilium.europa.eu/prado/it/prado-documents/imn/a/index.html

**Comment by gcarbonin** [comment]
Ho contattato il MAECI che ha confermato che si tratta di un territorio e non di uno stato. Ho consultato il link e il passaporto è britannico,
