### ISSUE TITLE
[3003] Elenco Operazioni: Anagrafica Doppia

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#514]
ambiente di PRODUZIONE - comune di FAENZA

il soggetto con idSchedaANPR 19088934 è stato cancellato dall'AIRE di Faenza per Rimpatrio in altro comune (e così risulta in ANPR ricercandolo con questo idSchedaANPR).
lo stesso soggetto risulta in ANPR anche come residente a Ravenna (il comune italiano in cui è rimpatriato, che nel frattempo è subentrato...) con altro idSchedaANPR (19832128)

al di là della problematica relativa all'anagrafica doppia, che immagino stiate ancora valutando come risolvere, si segnala un problema nella richiesta dell'elenco delle operazioni che riguardano il soggetto.

nella sua posizione di "cancellato da Faenza" stiamo tentando di interrogare l'elenco delle operazioni indicando come parametri di ricerca il codiceFiscale.
il web-service restituisce questo errore:
```
<errore>
  <codiceErroreAnomalia>EN095</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La richiesta per dati di un soggetto ha individuato piu' cittadini: restringere i parametri della ricerca</testoErroreAnomalia>
</errore>
```

in che modo possiamo "restringere" i parametri di ricerca, considerando che le generalità del soggetto sono le stesse in entrambe le anagrafiche?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Interroghi con id anpr e non per codice fiscale

**Comment by AMonopoliADS** [comment]
che è quello che avevamo ipotizzato già dall'inizio, ma guardando l'excel con le specifiche, all'interno del gruppo "parametriRicercaSoggetto" non vedo l'idANPR.
forse abbiamo una versione non aggiornata? o stiamo guardando il gruppo di dati sbagliato?

**Comment by gcarbonin** [comment]
quale servizio?

**Comment by AMonopoliADS** [comment]
servizio 3003

**Comment by azabatta** [comment]
Stiamo apportando una modifica, vi informeremo appena sarà possibile riprovare.

**Comment by ATropeano** [comment]
Al fine della gestione di casi di **anagrafiche doppie**, avendone riscontrato anche noi un caso in un recente subentro, si sollecita l'implementazione di **segnalazioni di warning** nei report generati come esito del subentro, in particolare quando il soggetto subentrante abbia le stesse identiche generalità di un soggetto già presente in ANPR.
Il caso tipico, oltre quello descritto sopra, è quello di un cittadino che ha richiesto la residenza in altro comune già subentrato, mentre il comune di origine, non avendone ancora ricevuto l'APR4, lo "reiscrive" con il suo subentro.

Alessio Tropeano
Datagraph

**Comment by gcarbonin** [comment]
L'implementazione relativa alla gestione delle posizioni duplicate è in corso

**Comment by azabatta** [comment]
La modifica sul ws 3003 è stata estesa in PRODUZIONE.  E' possibile effettuare nuovamente la richiesta.
Grazie per la segnalazione
