### ISSUE TITLE
Descrizione ente nella intestazione dei Certificati - "Città di " in luogo di "Comune di"

### ISSUE THREAD

**Issue by niclup** [italia/anpr#516]
Il comune di Frosinone si fregia del titolo di "Città" ed utilizza questa dizione anche nella intestazione dei documenti prodotti, certificati anagrafici compresi. Non capisco come potrei ottemperare alla loro richiesta.

**Comment by gcarbonin** [comment]
Verifichiamo

**Comment by rnapoli1983** [comment]
Potete riprovare negli ambienti di Testcomuni e Presubentro.

**Comment by niclup** [comment]
Esce solo "città di", senza il nome dell'ente

**Comment by rnapoli1983** [comment]
Buongiorno potreste riprovare ? Grazie mille

**Comment by niclup** [comment]
Tutto ok. Una a accentata su citta forse andrebbe meglio. Domani il comune subentra, si può passare la cosa in produzione?

**Comment by rnapoli1983** [comment]
Assolutamente si provvediamo subito. 
Per l'accento mancante vi chiederei di fare un ulteriore test in quanto potreste aver provato in una finestra temporale dove la modifica apportata ancora non era effettiva.
Attendo un vostro riscontro in merito.
Grazie mille
