### ISSUE TITLE
[6001] Certificabilità Parziale: Stato di Famiglia per Convivenza

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#518]
caso: soggetto iscritto all'interno di una convivenza, con blocco di "certificabilità parziale", 
data la situazione anagrafica, la richiesta dello Stato di Famiglia (web-service 6001) viene eseguita con tipoCertificato '14' (Stato di Famiglia per Convivenza).

il web-service va in errore con il seguente messaggio:
```
<errore>
  <codiceErroreAnomalia>EN046</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Per il soggetto, puo' essere prodotto esclusivamente un certificato di residenza o di stato di famiglia</testoErroreAnomalia>
</errore>
```

è giusto così? oppure il controllo non tiene conto di tutte le tipologie di stati di famiglia?

vedere: ambiente di TEST - comune di FAENZA - idOperazioneComune 2018600014

grazie.
Alessandro Monopoli ADS

**Comment by mccalv** [comment]
caro @AMonopoliADS puoi attivare l'opzione watch sul repository ANPR come da immagine allegata.
![screen shot 2018-01-31 at 15 47 30](https://user-images.githubusercontent.com/1814818/35629135-26668e06-069e-11e8-8fc1-84cdf8a0b60f.png)
In generale stiamo pensando ad una newsletter tecnica a cui notificare tutte gli alert da mandare agli integratori

**Comment by rnapoli1983** [comment]
Stiamo provvedendo a propagare la modifica negli ambienti di riferimento.
In generale quando un soggetto risulta in uno stato di parziale certificabilità, sarà possibile emettere, oltre i certificati di residenza e stato di famiglia già disponibili, anche quelli di:
- Residenza AIRE e Stato di famiglia AIRE
- Residenza in convivenza (Stato di Famiglia per Convivenza)

**Comment by gcarbonin** [comment]
Ha avuto modo di riprovare?

**Comment by AMonopoliADS** [comment]
ri-provando anche oggi la richiesta di Stato di Famiglia per Convivenza continua a ritornare lo stesso errore ((idOperazione 2018600036 - ambiente di TEST - comune di FAENZA)

**Comment by rnapoli1983** [comment]
Buongiorno abbiamo fatto una verifica. 
Potreste fare un ulteriore test.
Grazie mille.

**Comment by AMonopoliADS** [comment]
adesso il certificato viene prodotto. grazie

approfitto per segnalare una piccola discordanza, che ho notato questa mattina e che vi segnalo visto che siamo in tema:
il certificato di tipo '14' individua lo "Stato di famiglia per iscritto in convivenza anagrafica".
in realtà il certificato che viene prodotto è un "certificato di residenza in convivenza"
(non entro nel merito della correttezza di questa descrizione, immagino siano scelte veicolate dal Ministero...)
visto che anche sulla web-app avete previsto tra i certificati "Residenza in convivenza", e non esiste lo "stato di famiglia per soggetto in convivenza"... per evitare ambiguità e aspettative sbagliate, forse è il caso di cambiare anche la dicitura nella tabella 08

grazie

**Comment by rnapoli1983** [comment]
Si effettivamente la nomenclatura del certificato può risultare fuorviante.
Ovviamente non è stata definita da noi ma ci è stata trasmessa contestualmente ai template contenenti il testo statico dei certificati.
Ora facciamo una verifica, presentando questa piccola discordanza e nel caso non mancheremo di apportare le dovute correttive.
Buona giornata.

**Comment by gcarbonin** [comment]
Aggiorniamo la documentazione (cioè la tabella) alla prima occasione utile

**Comment by gcarbonin** [comment]
la documentazione è stata aggiornata
