### ISSUE TITLE
[A006] WEB SERVICE  chiarimenti su mutazione residenza estera 

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#52]
Ambiente di test di Venezia, 20 marzo 2017 e 28 marzo 2017 

Tramite servizio [A006] stiamo cercando di effettuare una mutazione di residenza estera per un intero nuclo famigliare. Continuiamo a ricevere risposta di errore che ci impedisce di completare l'operazione.

Effettuando la stessa operazione su Web App ci siamo accorti che il servizio invocato è il [5001].

Ripetendo da web service la stessa operazione ed invocando anche noi il servizio [5001] la transazione
è andata a buon fine.

Il documento funzionale riporta 
**5001  	Mutazione Residenza	Consente di variare la residenza o il domicilio dell'intero nucleo famigliare o della convivenza	Residenti
A006	Mutazione Residenza estera	Consente di modificare la residenza estera dallo stesso comune di iscrizione AIRE**

Ci confermate, quindi, che la mutazione del nucleo famigliare Aire si effettua, come per gli Apr con il servizio 5001, mentre il servizio A006 serve solo per effettuare mutazioni sul singolo individuo?

Ringrazio anticipatamente

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
Salve. Confermo quanto richiesto, che è riportato a pag. 103 e  108 delle specifiche (MI-14-AN-01).  Se mi indica un riferimento più preciso, possiamo chiarire meglio le specifiche.

**Comment by TizianaTesta** [comment]
Grazie è tutto chiaro.
