### ISSUE TITLE
Errore EC007 e rilascio CIE

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#524]
L'errore EC007 "Comune/provincia di nascita @ (@) inesistente o non valido alla data di nascita", segnalato come warning in fase di subentro, se non risolto impedisce il rilascio della CIE?
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
L'anomalia viene segnalata soltanto quando il codice fiscale riporta una indicazione del comune di nascita diverso. Il CF  è presumibilmente non validato e questo impedisce il rilascio della CIE.  E' un caso specifico in produzione?

**Comment by bfilipazzi** [comment]
C'è stato un caso specifico, alcuni giorni fa, provo a rintracciarlo.
