### ISSUE TITLE
Errore rimpatrio dall'estero

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#525]
Nel registrare un rimpatrio dall'estero ANPR da il seguente errore:
ERRORE DA ANPR: 
ES004 - Deve essere impostato almeno 1 tra nome e cognome e almeno un identificativo tra codice fiscale, identificativo soggetto attribuito dal comune, identificativo soggetto attribuito da ANPR.
Comune di Altamura

**Comment by gcarbonin** [comment]
Almeno il comune.....

**Comment by Finalmentesubentrati** [comment]
Altamura

**Comment by gcarbonin** [comment]
Tra le operazioni piu' recenti di produzione questo errore non c'è. Puo' indicarmi anche il servizio (immagino iscrizione per altri motivi9 e un vostro identificativo dell'operazione?
