### ISSUE TITLE
EN289 La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#527]
Cesena Produzione
Cittadino codice ANPR 19448203 Iscritto per iscrizione altri motivi Anpr in data 14/12/2017, vengono poi effettuate nella stessa data due mutazione tutti i dati sempre con la stessa data decorrenza.

In data odierna 05/02/2018 viene effettuata una Mutazione tutti i dati dell'oggetto stato civile andando a variare lo stato civile del cittadino da Non documentato a Coniugato la data di matrimonio è 09/10/1977 la data decorrenza dell'operazione è 05/02/2018.

Si ha il seguente messaggio bloccante:
EN289 La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto

Da cosa dipende? come risolvere?

**Comment by frmariani** [comment]
il soggetto idANPR 19448203 risulta avere una convivenza di fatto con il soggetto idANPR 18550381 stipulata in data 14-DIC-17 e ancora attiva.

**Comment by RBiasi** [comment]
Risolto grazie era stata fatta una mutazione tutti i dati inserendo i dati di convivenza di fatto prima di completare i dati di stato civile con la vedovanza.
