### ISSUE TITLE
Errore: l'encoding del file XML non e' in UTF - 8

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#53]
Buongiorno,
in fase di upload del file APR del Comune di Bologna, in ambiente di test , riceviamo questo errore:
l'encoding del file XML non e' in UTF - 8 .
E' la prima volta che riceviamo questo tipo di errore, abbiamo gia' fatto diverse prove di caricamento.

 
Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by gcarbonin** [comment]
Questo errore spesso dipende da caratteri non ammessi presenti nei dati inviati. Abbiamo appena pubblicato in test comuni un client che esegue questo tipo di verifica. Lo provi e mi faccia sapere.

**Comment by gcarbonin** [comment]
Chiuso per mancanza di risposta da parte del comune
