### ISSUE TITLE
Emigrazione in comune non subentrato - errore bloccante -

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#530]
Comune di Valle Mosso  (BI)  096073 - produzione dal 3/11/2017

Ho gia' inviato una mail alla sig.a Carbonin in data di ieri ma non ho avuto la conferma di lettura per cui ripropongo il problema qui.

"Le scrivo per verificare un problema che e' sorto nel tentativo di effettuare una cancellazione per emigrazione verso un Comune non subentrato di una persona iscritta in anpr

La persona ha l'id  19025577  ed emigra verso un comune non subentrato

All'invio dati si riceve un errore bloccante:  Operazione  2003 - cancellazione per altri motivi

errore  EN203  E-errore bloccante  -  Operazione non effettuabile - esiste un'operazione sospesa per il soggetto.

Ho verificato ma non riesco a trovare alcuna operazione sospesa, non solo per il soggetto ma in generale per tutto il comune.

La persona ha avuto, dopo il subentro, il cambio di cognome   con relativo cambio di CF ma l'operazione e' andata a buon fine senza alcun intoppo.

Mi faccia sapere come procedere dal momento che la pratica non e' perfezionabile."

**Comment by gcarbonin** [comment]
Mi scuso ma la sua mail mi era sfuggita ora controlliamo

**Comment by gcarbonin** [comment]
Risolto telefonicamente con il comune
