### ISSUE TITLE
Rigetto cambio residenza a cavallo del subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#531]
Ambiente di produzione - Luzzara.

Il comune è subentrato il 19/01.
Oggi 06/02 rigetta una pratica di cambio indirizzo per una persona.
Questo comporta una chiamata al 5005 con tipo mutazione 6 che abbiamo eseguito (id ANPR 2079172).
Riceviamo però l'errore "L'operazione di ripristino residenza e' consentita soltanto a valle del subentro".
Come decorrenza dell'indirizzo nella 5005 di ripristino specifichiamo quella che deve essere la reale decorrenza della residenza che il soggetto deve avere (2017-10-23).
Fino ad oggi non avevamo mai riscontrato questo problema, è un nuovo controllo ?

**Comment by asqueglia** [comment]
Buongiorno,
abbiamo verificato che il rigetto del cambio di residenza per il soggetto in questione con decorrenza 2017-10-23 è stato già effettuato il giorno 30-01-2018 ed è andato a buon fine (idAnpr operazione 1989114). 
Non è possibile ripetere nuovamente l'operazione.
Un saluto

**Comment by busaster** [comment]
Grazie per l'informazione, effettivamente è così.
Abbiamo provato ad annullare la 1989114 ma riceviamo l'errore EN077 "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa", ma in locale non ci risultano altre operazioni effettuate sul soggetto.

Dovremmo però ripetere l'operazione "da zero" per cui vorremmo annullare tutte le operazioni ANPR del soggetto compreso nella richiesta di cui sopra. Potete aiutarci ?

Grazie

**Comment by asqueglia** [comment]
Buongiorno,
abbiamo controllato che dopo l'operazione 1989114 è stato effettuato sulla famiglia di provenienza un 5005 con id 1989326, da ciò l'errore segnalato
Dovrebbe essere annullata prima questa operazione e poi quella del rigetto.

Un saluto
