### ISSUE TITLE
Partenza  in produzione Cie con ANPR

### ISSUE THREAD

**Issue by DemograficiCastiglionFiorentino** [italia/anpr#533]
Salve,
nel comune di Castiglion Fiorentino, già partito in produzione con anpr, stiamo partendo con la CIE, ci chiedevamo se il collegamento con ANPR sia attivato automaticamente o siamo ancora collegato cn i dati INA? In questo momento, cercando di emettere una nuova CIE, vediamo solo cognome, nome, data e comune di nascita, non cittadinanza e indirizzo, è corretto?
grazie dell'attenzione
Massimiliano

**Comment by gcarbonin** [comment]
Il sistema CieOnline interroga ANPR e per il momento preleva soltanto i dati anagrafici. E' in corso l'integrazione "completa" con ANPR con acquisizione anche dei restanti dati necessari all'emissione della CIE.
