### ISSUE TITLE
Errore in conferma dati

### ISSUE THREAD

**Issue by Elenalomazzi** [italia/anpr#534]
Buongiorno,
in ANPR stiamo cercando di fare la conferma dati di una persona che è già stata residente prima del subentro e che ora torna ad abitare nel nostro Comune (id ANPR 19943273). L'evento non viene eseguito e rimanda questo errore : "Errore nella registrazione dell'evento: Object reference not set to an instance of an object. "
Come possiamo risolvere?
Grazie
Elena Lomazzi

**Comment by frmariani** [comment]
l'errore è del suo gestionale e non di ANPR
