### ISSUE TITLE
Variazione di indirizzo di un individuo "senza fissa dimora"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#536]
Buon giorno,
vi sottoponiamo il seguente caso.
Abbiamo registrato l'immigrazione di un individuo da comune non subentrato, impostando tra gli attributi del soggetto il campo "senza fissa dimora" a 'S' (id operazione comune 3550). 
Successivamente abbiamo effettuato una mutazione di indirizzo, utilizzando il ws 5001 perchè trattasi di variazione di intera famiglia, in quanto l'individuo al suo ingresso ha costituito una nuova famiglia di cui è l'unico componente (id operazione comune 3822). 
Consultando i dati dell'individuo dopo tale variazione, il nuovo indirizzo è correttamente impostato, ma l'attributo soggetto "senzafissadimora" continua a valere 'S'.
Da specifiche in questi casi non è possibile utilizzare il ws 5005, in quanto è riportato che "Il caso di modifica di un senza fissa dimora a cittadino residente è da considerarsi anch’esso come un cambio di residenza." e che "Nel caso in cui tutti i componenti di una famiglia si trasferiscono in una nuova residenza (...) deve essere utlizzato il servizio 5001".
Come bisogna agire in questa situazione?
Il test è stato effettuato in data 29/01/2018,  in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by Amucciarelli74** [comment]
Buon giorno, 
ad integrazione del precedente test, abbiamo registrato l'immigrazione di un individuo da comune non subentrato, impostando tra gli attributi del soggetto il campo "senza fissa dimora" a 'S', questa volta costituendo una nuova famiglia con due componenti (id operazione comune 3870)
Successivamente abbiamo effettuato una mutazione di indirizzo, utilizzando il ws 5005 (id operazione comune 3876) perché la variazione ha interessato solo uno dei due componenti della famiglia; come da specifiche, trattandosi di un "senza fissa dimora", abbiamo indicato nel campo "tipoMutazione" della sezione "datiControllo" il valore "01", inoltre abbiamo creato una nuova famiglia indicando appunto la residenza in una via del comune. 
L'operazione è andata a buon fine, con il warning EN395 "per il tipo di mutazione 1 saranno modificati soltanto i dati relativi a senza fissa dimora"; a una successiva consultazione, l'individuo appartiene alla nuova famiglia costituita e risulta residente al nuovo indirizzo, ma come nel caso precedente l'attributo soggetto "senza fissa dimora" continua a valere 'S'.

Il test è stato effettuato in data 08/02/2018, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Buongiorno,
l'attributo del soggetto 'senza fissa dimora' non viene aggiornato automaticamente con un cambio di residenza ma solo attraverso una richiesta esplicita di mutazione dati anagrafici. Nello specifico è possibile impostare ad 'N' tale attributo effettuando una mutazione 5008 dati anagrafici (tipoMutazione>01</tipoMutazione>), valorizzando la sezione attributi soggetto:
<attributiSoggetto>
               <senzaFissaDimora>N</senzaFissaDimora>
</attributiSoggetto>

**Comment by asqueglia** [comment]
``

**Comment by Amucciarelli74** [comment]
Ok, 
la cosa in realtà non era proprio evidente, in quanto nel documento di specifiche per il servizio di mutazione 5005, nel caso di modifica dell'abitazione di un senza fissa dimora, non si fa riferimento a questo ulteriore passaggio da fare per modificare anche l'attributo soggetto del cittadino, nè il campo è indicato tra i dati modificabili col servizio 5008 elencati nel paragrafo 11.3.4 (anche se è presente tra le generalità da modificare nel file 5008-MutazioneDatiGeneraliStatoCivile.xlsx).

Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Provvederemo ad aggiornare la documentazione in merito. 
Grazie mille per la segnalazione
