### ISSUE TITLE
Azzeramento id famiglia comune ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#539]
San Giovanni Rotondo - Ambiente di produzione

Con l'operazione ID op. comune 418 e codMittente 071046 è stata rimpatriata una intera famiglia AIRE con il servizio 5001.
La famiglia di partenza aveva id famiglia comune valorizzato del tipo FEXXXXXX.
Nella richiesta è stato specificato il solo ID ANPR della famiglia.
L'operazione è andata a buon fine ma ora in  ANPR la famiglia ha come id famiglia comune 0.
Come mai ?

**Comment by gcarbonin** [comment]
Si tratta di una scheda famiglia diversa (da AIRE ad APR)

**Comment by busaster** [comment]
L' id famiglia ANPR è il medesimo trattandosi di una chiamata 5001.
Quindi la scheda famiglia ANPR è la stessa.
Non è così ?

**Comment by gcarbonin** [comment]
Nei passaggi da estero a Italia non manteniamo l’idFamigliaComune specifico dell’AIRE FEXXXXXX (così come nel passaggio Italia estero non manteniamo l’idFamigliaComune italiano)
Per inserire un nuovo idfamigliacomune occorre  altro 5001 con tipo mutazione 3 - MOTIVO SPECIE FAMIGLIA CONVIVENZA (l’abbiamo inserito li a seguito di analoghe richieste di altri comuni)
