### ISSUE TITLE
[3200] Web Service - Internal Error (from server)

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#54]
Comune di Venezia, ambiente di Test - 29.03.2017

Eseguita iscrizione di persona (id anpr 7583074) con operazione anpr 109176.
L'iscrizione è andata a buon fine.

Se cerchiamo di interrogare i dati da ANPR tramite servizio [3002]  dà errore:
javax.xml.ws.soap.SOAPFaultException: Internal Error (from server)

Tramite il servizio [3003] siamo riusciti a recuperare la risposta che ci sarebbe dovuta arrivare al posto dell'internal server error e nell'xml abbiamo trovato i dati del cittadino

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
E' stata indicata una descrizione del motivo di iscrizione (penso da WA) più lunga di quanto accetta il 3002 descrizioneMotivoIscrizione è un charMax30 e non accetta la descrizione MANCATA ISCRIZIONE IN ALCUN COMUNE ITALIANO. Ampliamo la dimensione del campo nel xsd. In giornata pubblichiamo la nuova versione.

**Comment by TizianaTesta** [comment]
Abbiamo verificato e adesso funziona
grazie
