### ISSUE TITLE
dataDecorrenzaLegame

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#541]
Nell'oggetto tipoFamiglia è stata aggiunta la data "dataDecorrenzaLegame".
Nell'oggetto famiglia era già presente un oggetto di tipo "tipoLegameSoggetto" che al suo interno contiene da sempre un campo "dataDecorrenza".
Qual è la differenza tra le due date ?
A cosa serve la nuova dataDecorrenzaLegame ?
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
La "vecchia data" indica la data nella quale inizia il legame con la famiglia (vedi legameSoggetto.xls).
La nuova data indica da quando inizia il legame di parentela  del soggetto

**Comment by busaster** [comment]
Quindi le due date coincidono se il soggetto non ha mai avuto variazioni di relazione nella famiglia, mentre differiscono se è avvenuto.
Nel caso in cui la nuova data non venga specificata immagino si assuma uguale alla "vecchia data".
E' così ?

**Comment by azabatta** [comment]
Sì, è così. E’ possibile effettuare una verifica consultando prima e  dopo una mutazione della composizione scheda famiglia, la posizione di un cittadino per il quale si cambia  la relazione di parentela.

**Comment by Eduardo1977** [comment]
Ho scaricato il file "SPECIFICHE DI INTERFACCIA 05022018.rar" dal sito "https://www.anpr.interno.it/portale/documentazione-tecnica". Negli excel contenuti nella cartella "Oggetti" non riesco a trovare il riferimento al nuovo campo "**dataDecorrenzaLegame**". Forse gli excel non sono aggiornati?

**Comment by azabatta** [comment]
Buonasera, l’oggetto excel “legameSoggetto”  non è stato aggiornato per non generare confusione  in quanto nella gestione dei  ws  non è stato modificato.
La nuova data viene restituita solo nella risposta della consultazione.
