### ISSUE TITLE
Chiarimenti su scissione famiglia

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#543]
Buongiorno.
Ambiente di test, comune 046035, nell'ambito di test effettuo una operazione dalla WA di mutazione di residenza. La famiglia di provenienza risiede nel comune 043043, ed è composta da 7 persone.
La mutazione di residenza che inserisco con WA, è l'id operazione 750701 , con cui trasferisco solo 2 delle 7 persone della famiglia, dal comune 043043 al comune 046035. trasferisco l' IS e sua moglie.
Al termine dell'operazione:
- da consultazione wa scheda individuale del id anpr   (corrispondente all'IS) vedo correttamente la nuova famiglia  di 2 componenti residente nel comune 046035.
-da consultazione wa scheda individuale del id anpr  7797926 (uno dei 5 rimasti nella famiglia originale), vedo invece la famiglia composta da 7 componenti, con la colonna "residenza" che riporta la descrizione di un comune o dell'altro!
- se richiamo da WS la composizione della famiglia partendo dallo stesso id ANPR 7797926, ho anche qui come risposta tutti e 7 i componenti.

Quanto scritto sopra fatto e verificato giovedì 8 pomeriggio. Annotato il messaggio ma non inviato perchè  a un certo punto il sito di ANPR test non funzionava più.
Controllando il giorno dopo e oggi la famiglia dell'id ANPR 7797926 vedo solo 5 componenti e non più 7.
La situazione è quindi corretta, oggi, Tuttavia se fosse possibile vorrei chiarimenti su questo aggiornamento ritardato.

**Comment by amollicone1982** [comment]
L’aggiornamento è contestuale; si trattava di un problema di visualizzazione dei dati (con data di riferimento = data della mutazione) sul quale stiamo intervenendo. Avvertiamo quando possibile riprovare

**Comment by MarcoMigliori** [comment]
Scusate: in attesa di riscontro, perchè posso riprovare quindi?

**Comment by amollicone1982** [comment]
Si, può riprovare

**Comment by MarcoMigliori** [comment]
Scusate il ritardo ho provato solo ora.
Il problema come descritto, si è risolto. Ho fatto un test oggi sul soggetto id anpr 7797452, con data competenza 20.03.2018. Il soggetto prima della mutazione di residenza era in una famiglia di 6 componenti.

Ora però se cerco con data 18.03.2018 (precedente alla mutazione residenza) per ID 7797452  , il soggetto che ho spostato dal comune A al comune B, lo vedo correttamente residente nella griglia di ricerca nel comune A. se guardo la famiglia e i suoi componenti, tuttavia vedo 5 nomi, manca il soggetto trasferito. Che è poi quello che sto consultando.
Stesso risultato (vedo 5 componenti invece di 6) se cerco per altri id 7799938, con data 18.03.2018
Ambiente di test. operazioni di consultazione identiche se svolte da comune A o comune B.

**Comment by amollicone1982** [comment]
Problema web risolto. Può riprovare

**Comment by MarcoMigliori** [comment]
Risolto.
