### ISSUE TITLE
Territori esteri - Residenza e Morte

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#545]
Il signor X è un italiano residente all'estero (esempio di fantasia).
Abita nell'Isola di Man, nel capoluogo Douglas.
Oggi purtroppo muore, lì dove risiede.
Se io capisco bene la tabella degli stati esteri, la sua residenza in ANPR è a Douglas nel territorio dell'Isola di Man (cod. istat 228) mentre la sua morte avviene a Douglas nello stato del Regno Unito (cod. istat 219).
Il luogo è lo stesso ma viene codificato in due modi diversi in base al caso, non è un po' complicato?
Grazie
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
I dati in questione riguardano gli iscritti AIRE; da sempre si utilizza il territorio per indicare la residenza (per poter rintracciare il soggetto), lo stato in tutti gli altri casi.
