### ISSUE TITLE
Specifiche 5 febbraio ed incongruenze

### ISSUE THREAD

**Issue by busaster** [italia/anpr#546]
Ho confrontato XSD del 5 febbraio con precedenti versioni e poi l'ho confrontato con XLS della versione attuale.
Riscontro le seguenti incongruenze/anomalie ne file tipoDato presente nella cartella del servizo 1000:
1. In tipoAtto il campo UfficioMunicipio è tornato a 4 caratteri nel XSD, in XLS è a 50, nel precedente XSD era 80.
2.  nel XSD In testataRichiesta è stato aggiunto il campo charmax80 "versioneSpecifiche" non documentato in XLS
3. nel XSD in TipoPermessoSoggiorno e in tipoDatiSoggiorno3000 questuraRilascio è passata da 50 a 20, in XLS è ancora 50
4. nel XSD descrizioneMotivoIscrizione è passato da 240 a 30 caratteri, in XLS è ancora a 30
5. nel XSD in TipoDocumentoProtocollato è sparito il campo dataDocumento, ancora presente in XLS.

Immagino quel file sia sbagliato visto che differisce da tutti gli altri tipoDato.xsd presenti nella documentazione.

**Comment by rvinzani** [comment]
Abbiamo aggiornato il TipoDato.xsd dei servizi 1000 e pubblicato nuovamente le specifiche corrette.
L'errore era comunque inerente alle specifiche e non alla funzionalità dei servizi
