### ISSUE TITLE
Nuove specifiche 8/02/18 e retrocompatibilità 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#547]
Ambiente di test.
Il mio applicativo non è ancora aggiornato alle specifiche XSD del 8 febbraio (in particolare non conosce il nuovo campo dataDecorrenzaLegame).
Faccio una iscrizione 1002 in cui la data di cui sopra non è presente. Tutto Ok.
Nel momento in faccio l'interrogazione 3002 d iquest osoggetto però ANPR mi torna quella data valorizzata con lo stesso valore di dataDecorrenza. Questo causa un errore applicativo in quanto il parsing trova un campo che non si aspetta.
Lo stesso problema non si presenta se chiedo una 3002 su un soggetto già presente in ANPR.

Mi è  chiaro che aggiornando gli XSD nel mi modulo il servizio continuerà a funzionare.

Mi pare però una modifica pericolosa perché rompe la compatibilità all'indietro.
Immagino infatti che prima di passarla in produzione sarà necessario che tutti i gestori di software vi si adeguino.
Forse varrebbe la pena prima di questo tipo di modifiche di introdurre un modo con cui l'applicativo locale dichiara ad ANPR con quale versione  delle specifiche sta lavorando in modo da ricevere una risposta congrua, magari con un warning che avverte dell'obsolescenza delle specifiche.

**Comment by gcarbonin** [comment]
Si tratta di un campo facoltativo e quindi non crea danni. Aggiornando gli xsd un sw non aggiornato ignora il campo.
La modifica da lei richiesta è prevista ma non per questo tipo di variazioni (https://anpr.readthedocs.io/en/latest/change-management/index.html)

**Comment by busaster** [comment]
E' parzialmente vero.
Un SW non aggiornato può andare in errore se gli viene ritornato un campo non previsto nel XSD a lui noto. Ad Esempio :  usando JAVA e JAX come metodo di unmarshalling XML, se arriva un XML con campi non previsti nel XSD locale, l'operazione di unmarshalling fallisce con una javax.xml.bind.UnmarshalException

**Comment by gcarbonin** [comment]
Consiglio di leggere il documento

**Comment by mccalv** [comment]
Caro @busaster intervengo solo per aggiungere qualche dettaglio sulla ratio di questa scelta che sicuramente é stata dettata da considerazioni sia pratiche che teoriche, ma rimane appunto una scelta.
Il senso di questa impostazione è quella di consentire ad ANPR, anche per venire incontro alle richieste di evoluzioni fatte dagli utilizzatori, di aggiornare il suo protocollo in maniera incrementale, e se questo non é possibile, dare il giusto tempo per abbandonare il vecchio contratto in favore del nuovo (modifica non retrocompatibile)

In questo senso quindi, assumiamo che il client che si interfaccia con ANPR lo faccia sempre in modalità _non strict_ e non vada in errore incontrando campi opzionali. 
Per chi utilizza java come da esempio questo dovrebbe ottenersi con un tuning sulle impostazioni, per chi utilizza un parsing XML invece di tipo standard potrebbe essere addirittura trasparente.

**Comment by busaster** [comment]
Grazie per la precisazione, era quello che stavamo pensando anche noi.
Seguiremo questa strada.
