### ISSUE TITLE
EAM94 e annuullamento del C.F

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#548]
Ambiente di produzione - Comune Mariano Comense
<idOperazioneANPR>2164268
E' una richiesta di variazione del comune di nascita
Il sistema risponde con l'errore EAM94 - Richiesta incongruente - nessun campo variato
Si osserva dopo l'operazione che il C.F. in ANPR non c'è più, è n ullo
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Ho visto anche un caso simile al Lucca, sempre in produzione
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Il problema è stato risolto ed il codice fiscale ripristinato
