### ISSUE TITLE
[6001] Certificato Anagrafico di Morte: Evento avvenuto all'estero

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#549]
ambiente di PRODUZIONE - comune di FAENZA

il certificato anagrafico di morte (tipoCertificato = 2), relativo a soggetto deceduto all'estero, non riporta la località in cui è avvenuto l'evento
rif. idOperazioneComune 2018600406

il certiticato riporta questa dicitura:
"Risulta deceduto a il 24/12/2017"

**Comment by gcarbonin** [comment]
Può riprovare e darmi un riscontri?

**Comment by AMonopoliADS** [comment]
confermo che adesso nel certificato viene stampata la località estera del decesso.
grazie
