### ISSUE TITLE
Web-ApWeb-App Iscrizione per altri motivi da Comune non subentrato - Atto di nascita non obbligatorio

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#55]
Data test 30/03/2017 - Ambiente test (dptest)
Registrando l'iscrizione di un cittadino GRRLLN64P44L219L, da comune non subentrato, il sistema prevede come campi obbligatori i dati dell'atto di nascita. Il cittadino al momento dell'iscrizione non conosce questi dati e questi saranno forniti con il cartaceo del  Comune di provenienza non subentrato in una fase successiva. I campi non devono essere obbligatori.
Grazie
Stefania Amprimo, Annamaria Gillone, Liliana Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
La sezione atto di nascita non è obbligatoria. Tuttavia se si apre la sezione e si clicca su Conferma il sistema restituisce un messaggio di errore.

**Comment by annamariaGillone** [comment]
Abbiamo ricreato il caso, il flusso di navigazione si sposta prima su tutte le videate con asterisco rosso (obbligatorie) e poi riprende dalla prima voce senza asterisco che in questo caso è ATTO NASCITA, effettivamente il flusso non ci era chiaro.
