### ISSUE TITLE
[6001] Certificato di Contratto di Convivenza - Errore EN354

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#550]
ambiente di PRODUZIONE - comune di FAENZA

la richiesta di Certificato di Contratto di Convivenza (idOperazioneComune 2018600403) restituisce questo errore:
```
<errore>
  <codiceErroreAnomalia>EN354</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Il certificato non puo' essere emesso perche' i dati del contratto di convivenza risultano assenti o incompleti</testoErroreAnomalia>
</errore>
```
su quali dati viene eseguito il controllo?
grazie

Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Il dati del contratto di convivenza comprendono tre  date:

- data di inizio della convivenza (legame.data)
- data di stipula del contratto (documento_protocollato.data)
- data di registrazione al comune (documento_protocollato.data_notifica).
In questo caso manca la data di stipula.

**Comment by AMonopoliADS** [comment]
grazie del riscontro.

nel tentativo di valorizzare la data di stipula, ci imbattiamo in questo messaggio di errore:
EN364 - E - La data di stipula del contratto di convivenza e la data di notifica al comune devono essere entrambe presenti o entrambe assenti

il fatto che possano essere entrambe assente (come nel nostro caso), mi torna con la non obbligatorietà dei due campi.

abbiamo comunque provato a valorizzare anche la dataNotifica... e l'operazione è andata a buon fine.
se stampo il certificato, però, ottengo un testo di questo tenore:
"Risultano aver stipulato il 29/12/2017, a , un contratto di convivenza,
comunicato il 29/12/2017 da (ASSENTE). Estremi della comunicazione:"
perchè, giustamente di informazioni relative al documentoProtocollato ne mancano altre.

a questo punto mi chiedo (e vi chiedo):
i due conviventi hanno istituito una convivenza di fatto, ma NON hanno stipulato un Contratto di Convivenza per regolare i loro rapporti patrimoniali.

non esiste un certificato che documenti semplicemente lo stato di Convivenza di Fatto, indipendentemente dalla sottoscrizione di un Contratto di Convivenza?

grazie.

**Comment by romanobagnacavallo** [comment]
Non spetta a me parlare a nome di Sogei, ma sono a conoscenza del fatto che il Ministero dell'interno non autorizza (almeno fino ad ora) la gestione in ANPR della dichiarazione di "convivenza di fatto" che la quasi totalità dei comuni gestisce sulla propria banca dati comunale (Milano, solo per fare un esempio importante) in applicazione "corretta" della legge n. 76 del 2016. Di conseguenza Sogei non può implementare questa funzione, ma solo la registrazione del contratto di convivenza (....). Naturalmente, poichè il responsabile unico della tenuta dell'anagrafe è l'ufficiale d'anagrafe, chi, come me, ritiene che l'applicazione corretta della legge comporti l'OBBLIGO per l'ufficiale d'anagrafe di registrare la dichiarazione di convivenza di fatto resa da chi ne abbia i requisiti, continuerà a registrare tale dato nella propria anagrafe comunale e a certificare tale dato, se richiesto, sempre dalla propria banca dati comunale (oltre ai dretti interessati, i Notai "pretendono" giustamente tale certificazione!). Sarebbe auspicabile che il Ministero sbloccasse questa situazione diventata incresciosa anche a seguito dei chiarimenti che la dottrina ha ampiamente fornito e condiviso.

**Comment by gcarbonin** [comment]
Preciso che la dichiarazione anagrafica può e deve essere registrata in ANPR.
Il certificato non viene prodotto in quanto attualmente si certifica il contratto di convivenza e non la convivenza.

**Comment by romanobagnacavallo** [comment]
Prendo atto e mi fa piacere; tuttavia, devo osservare che il fatto che non
si possa certificare è ancora meno comprensibile... come per il certificato
di cittadinanza per stranieri! è la stessa cosa; la normativa anagrafica è
chiarissima: TUTTI i dati anagrafici sono certificabili ad esclusione di
quelli esclusi per espressa disposizione di legge!

2018-02-19 10:46 GMT+01:00 gcarbonin <notifications@github.com>:

**Comment by mccalv** [comment]
grazie @romanobagnacavallo per il contributo. Porteremo questa discussione al tavolo del Ministero questa settimana e riporteremo gli esiti della discussione.

**Comment by AMonopoliADS** [comment]
grazie a tutti per i contributi.
attendiamo quindi news sull'evoluzione della questione.
grazie mille.

**Comment by mccalv** [comment]
Vi confermiamo su questo punto che la questione è stata sollevata presso il Ministero che ha confermato la posizione già descritta e contenuta in questa circolare.
http://dait.interno.gov.it/documenti/circ-007-servdemo-01-06-2016.pdf

L'implementazione di Sogei é coerente con questi presupposti.

**Comment by romanobagnacavallo** [comment]
... 3 cose (pardon)

Il giorno 8 marzo 2018 11:43, Romano Minardi <romano.minardi52@gmail.com>
ha scritto:

**Comment by romanobagnacavallo** [comment]
Riporto gli estratti più significativi della circolare n. 7, citata:
"...Nel succesivo comma 37 si prevede che, ferma restando la sussistenza
dei presupposti della convivenza di fatto, per l'accertamento della stabile
convivenza deve farsi riferimento alla dichiarazione anagrafica di cui
all'art. 4 e alla lettera b) del comma 1 dell'art. 13 del regolamento
anagrafico (D.P.R. n. 223/1989)"
.... "Alla luce delle richiamate disposizioni, l'attività degli uffici
anagrafici riguarderà, quindi, l'iscrizione delle convivenze di fatto, la
registrazione dell'eventuale contratto di convivenza, ed il rilascio delle
relative certificazioni."...
Mi permetto di osservare che il Ministero dice chiaramente due cose:
1) Dalla composizione dello stato di famiglia (art. 4 DPR n. 223/89) si
desume la "convivenza stabile" e cioè la coabitazione; giustissimo! ma il
Ministero non dice che si possano desumere anche gli altri requisiti che
sono: la mancanza di rapporti di parentela, matrimonio o unione civile, e
la sussistenza del rapporto affettivo more uxorio che va per forza
dichiarato e che, per l'appunto si può desumere e presupporre solo se viene
registrata la dichiarazione di convivenza di fatto resa dalle parti.
2) Il Ministero afferma che l'attività degli uffici anagrafici riguarda:
"l'iscrizione delle convivenze di fatto" e la registrazione dell'EVENTUALE
contratto di convivenza" lasciando chiaramente intendere che l'iscrizione
delle convivenze di fatto può prescindere dalla registrazione del contratto
di convivenza.
3) L'ufficio anagrafe deve rilasciare le "relative certificazioni";
realtive, quindi, sia al contratto di convivenza, sia alla registrazione
della convivenza di fatto.
Dunque, è vero che la registrazione della dichiarazione di convivenza di
fatto deve per forza essere effettuata nel caso in cui si debba registrare
un contratto di convivenza (e questo l'ANPR correttamente lo consente); ma
non è vero che la dichiarazione di convivenza di fatto non debba potersi
registrare in anagrafe anche in mancanza del contratto di convivenza
(altrimenti, il Ministero non avrebbe ustao il termine: "eventuale"). Detto
questo, ormai per questa questione mi sento più odiato di Renzi.... per cui
resto in minoranza ma, mi sia consentito, resto anche all'opposizione!
Romano

2018-03-01 15:53 GMT+01:00 Mirko Calvaresi <notifications@github.com>:

**Comment by romanobagnacavallo** [comment]
Perfetto: manca solo il certificato e siamo a posto.

Il giorno 8 marzo 2018 11:44, Romano Minardi <romano.minardi52@gmail.com>
ha scritto:
