### ISSUE TITLE
[5008] Collegamento dati coniuge: matrimonio / vedovanza

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#551]
ambiente di PRODUZIONE - comune di ARONA (NO)

soggetti coniugati:
- lui (idSchedaANPR 20013251) collegato alla moglie (idSchedaANPR 20013252)
- lei (idSchedaANPR 20013252) NON collegata al marito

stiamo tentando di aggiornare i dati con ws 5008 e tipoMutazione '12':
- se passiamo l'idSchedaANPR del coniuge il servizio risponde
"Alla data xx-xx-xxxx il soggetto risulta gia' coniugato o unito civilmente con un altro soggetto"
(idOperazioneComune 2018000191)
- se passiamo l'idSchedaComune la comunicazione viene accettata, ma eseguendo la consultazione non risulta variato alcun dato
(idOperazioneComune 2018000192)
- se passiamo, in aggiunta ai dati "Comune" anche il codice fiscale del coniuge, torna il messaggio
"Alla data xx-xx-xxxx il soggetto risulta gia' coniugato o unito civilmente con un altro soggetto"
(idOperazioneComune 2018000194)

questa situazione di disallineamento, blocca il perfezionamento della vedovanza di lui a seguito del decesso di lei.
il decesso di lei (idSchedaANPR 20013252) verrebbe registrato correttamente
la vedovanza di lui (idSchedaANPR 20013251) invece viene bloccata con questo messaggio
```
<errore>
  <codiceErroreAnomalia>EN300</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Comunicare il decesso del coniuge per aggiornare la scheda del coniuge superstite con i dati della vedovanza</testoErroreAnomalia>
</errore>

```

come riusciamo a superare la cosa?
grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Le schede di due soggetti coniugati tra loro sono collegate tramite identificativo del comune e cognome e nome. Nel caso specifico, il collegamento è parziale in quanto la scheda di uno dei due soggetti contiene dati del coniuge che non coincidono con quelli presenti sulla scheda anagrafica del coniuge stesso.
analizziamo una possibile soluzione e contattiamo il comune
