### ISSUE TITLE
Mutazione di residenza tra subentrati ed annullamenti

### ISSUE THREAD

**Issue by busaster** [italia/anpr#552]
Ambiente di test - Poggio a Caiano + Gorgonzola.
Situazione : dal comune di Gorgonzola due cittadini abitanti in due famiglie distinte migrano a Poggio a Caiano formando una nuova famiglia.
A Poggio eseguo quindi due mutazioni 5005 con successo, ID ANPR 1643814 e 1643842.
la 1643814 crea la nuova famiglia e imposta l'intestatario, la 1643842 aggiunge a questa famiglia un convivente.
Successivamente a causa di accertamenti negativi devo rigettare la prima delle due 1643814.
Quando provo ad annullare il movimento ricevo però l'errore "EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa" (id ANPR annullamento 1643975).

Questo comportamento mi lascia perplesso. 
Significa che nella situazione descritta devo anche annullare il movimento "buono" 1643842 per poi reinserirlo con un'altra 5005 ?

**Comment by gcarbonin** [comment]
Al momento si. Stiamo facendo una modifica che risolve il problema. Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
L'argomento è già trattato nella issue #783
