### ISSUE TITLE
[5014] Ambiente di Produzione - Errore XXXX

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#554]
ambiente di PRODUZIONE - comune di FAENZA

stiamo provando ad utilizzare il nuovo servizio 5014 per la rettifica della dataDecorrenzaResidenza
(rif. idOperazioneComune 2018004082)

il web-service risponde con questo errore:
```
<errore>
  <codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Valore tipoInvio := PROD non congruente con l'ambiente di riferimento := PRE_SUB</testoErroreAnomalia>
</errore>
```
non capiamo quale sia il problema.

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
può riprovare

**Comment by AMonopoliADS** [comment]
il cliente ha riprovato e la comunicazione è stata accettata con successo
grazie
