### ISSUE TITLE
[1010] errore convalida xml 

### ISSUE THREAD

**Issue by giovannidestefano** [italia/anpr#556]
In riferimento alla richiesta 1010 

nella validazione della richiesta ottengo il seguente errore:
"Il contenuto dell'elemento "Richiesta1010" nello spazio dei nomi "http://sogei.it/ANPR/1000iscrizione" ? incompleto. Elenco dei possibili elementi previsti "datiDelProcedimento, datiControllo".
dalla documentazione sono entrambi non obbligatori . 

come superare il problema?
Grazie 

Giovanni De Stefano
Advanced Systems
per il comune di Cava dei Tirreni

**Comment by gcarbonin** [comment]
Buongiorno. Mi mandi la richiesta sulla mail personale

**Comment by mccalv** [comment]
Caro @giovannidestefano. come da policy di questo strumento le segnalazioni che contengono dati personali vanno inviate a  segnalazioni-anpr@teamdigitale.governo.it
Ti chiederei per il beneficio di tutti anche di spiegare il problema e la soluzione qui dopo il follow up con Sogei.
Grazie!

**Comment by gcarbonin** [comment]
Manca daticontrollo : 	<xs:element name="datiControllo" 		type="anpr:tipoDatiControllo1001" 	 		minOccurs="1" maxOccurs="1"/>
