### ISSUE TITLE
Scioglimento unione civile : dati obbligatori

### ISSUE THREAD

**Issue by busaster** [italia/anpr#558]
Ambiente di test - Livigno.

Cerco di iscrivere in ANPR con il servizio 1002 un soggetto con stato civile "Stato libero a seguito di scioglimento dell’unione" , popolando i dati di scioglimento in mio possesso : motivoScioglimento e datiEvento. In datiEvento popolo la data evento e gli estremi dell'atto che mi sono noti.
La richiesta (ID ANPR 1651990) va però in errore EN278 : "E' necessario specificare i dati obbligatori per lo scioglimento: motivo scioglimento, data sentenza oppure data formazione atto".

La sentenza in questo caso non esiste (Accordo di scioglimento) e la data di formazione atto non mi è nota.

Potete alleggerire il controllo ?

**Comment by asqueglia** [comment]
Salve,
stiamo provvedendo a rilassare il controllo come da  vostro suggerimento. Vi avviseremo appena possibile riprovare.
Grazie per la segnalazione

**Comment by gcarbonin** [comment]
Può riprovare

**Comment by busaster** [comment]
Abbiamo riprovato, non abbiamo più avuto il blocco e la richiesta è andata a buon fine.
Grazie
