### ISSUE TITLE
EHR83 - Non è chiaro il senso (in questo caso)

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#559]
Ambiente di test - Comune di Gorgonzola (MI)
<idOperazioneANPR>1652039
ANPR risponde con:
<codiceErroreAnomalia>EHR83
L'anno dell'atto e la data di formazione dell'atto di annullamento del matrimonio non possono essere successivi alla data di decorrenza dell'operazione
Mi aiutate per favore a capire il significato del messaggio? Grazie.
Filipazzi - Maggioli

**Comment by azabatta** [comment]
Buongiorno,
la modifica è stata propagata in tutti gli ambienti. E' possibile riprovare

**Comment by bfilipazzi** [comment]
Riprovato, funziona.
Grazie.
Filipazzi - Maggioli
