### ISSUE TITLE
Web-App Iscrizione per altri motivi da Comune non subentrato - Soggetto DIVORZIATO 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#56]
Data test 30/03/2017 - Ambiente test (dptest) -  id_operazione anpr 1031
Registrando l'iscrizione di un soggetto con stato civile DIVORZIATO (GRRLLN64P44L219L) , da comune non subentrato, il sistema prevede come campi obbligatori i dati del CONIUGE, ma in questo caso tali campi NON devono essere obbligatori (l'obbligatorietà deve essere prevista solo per i soggetti CONIUGATI o VEDOVI ).
 Analogamente per la videata relativa alla Cessazione, il soggetto al momento dell'iscrizione non deve fornire tali dati, tali dati saranno eventualmente comunicati in una fase successiva.  Per poter proseguire abbiamo inserito dati fittizi dell'ex-coniuge e della Cessazione, al seguito della conferma la navigazione ha aperto la videata delle Convivenze di fatto.  Per poter procedere abbiamo inserito dati fittizi e al conferma compare la videata Risoluzione convivenza. Inserendo altri dati fittizi per proseguire alla conferma compare messaggio di errore  Error 405: HTTP method POST is not supported by this URL.  
Grazie
Stefania Amprimo, Annamaria Gillone, Liliana Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
La sezione del matrimonio  della cessazione ecc. non sono obbligatorie. Tuttavia se l'operatore entra in queste sezioni e preme conferma, il sistema segnala gli errori legati all'assenza di campi obbligatori. Ho effettuato una prova di iscrizione per altri motivi con provenienza da comune non subentrato, il sistema anche indicando stato civile = divorziato si posiziona sulle sezioni obbligatorie che sono quelle contrassegnate in rosso.

**Comment by annamariaGillone** [comment]
Abbiamo ricreato il caso e dopo avere caricato le sezioni obbligatorie ora non siamo più entrate nelle sezioni facoltative, ma siamo passate direttamente su Completa operazione e abbiamo salvato. Tuttavia al salvataggio compare il messaggio "Attenzione:Se stato civile divorziato/a deve essere presente la sezione separazioneAnnullamentoCessazioneMatrimonio (Codice: EN201)", probabilmente non è bloccante ma non dovrebbe proprio comparire.

**Comment by gcarbonin** [comment]
E' una segnalazione non bloccante che riteniamo di dover esporre in quanto in ogni caso la situazione non è corretta.
