### ISSUE TITLE
Mutazione soggetto AIRE da comune subentrato

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#561]
In ambiente di test, devo trasferire in comune subentrato un soggetto iscritto all'AIRE di un comune subentrato, ma il  servizio 5001 risponde l'errore "EF002 - Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata".
Se necessario posso inviare anche il file xml della richiesta. Faccio presente che la stessa cosa fatta per un soggetto iscritto all'APR funziona regolarmente.
Saluti
Papini Riccardo
Inf.Or.

**Comment by ncapozzi** [comment]
Buongiorno, può indicarci l'id operazione per favore?

**Comment by rpapini** [comment]
Ho riprovato anche ora:

idOperazioneComune = 7962
codMittente = 051002
idFamigliaConvivenzaANPR = 5157558

Saluti

**Comment by ncapozzi** [comment]
La famiglia da modificare è AIRE quindi deve indicare tipoScheda = 5 nella richiesta
<famigliaConvivenza>
            <idFamigliaConvivenzaANPR>5157558</idFamigliaConvivenzaANPR>
            <tipoScheda>5</tipoScheda>
         </famigliaConvivenza>

**Comment by rpapini** [comment]
Anche se la famiglia diventa APR? Cioè il soggetto viene iscrtitto in APR.
Saluti

**Comment by ncapozzi** [comment]
Si, serve per identificare la famiglia da modificare, poi il tipo scheda viene aggiornato con la mutazione in modo congruente con l'indirizzo (3 se italiano, 5 se rimane estero)
Saluti

**Comment by ncapozzi** [comment]
Nel nuovo invio idOperazioneComune = 7970 c'è ancora tipo scheda = 3
Saluti

**Comment by ncapozzi** [comment]
Il nuovo invio con idOperazioneComune = 8002 e tipo scheda = 5 ha avuto esito positivo
 Saluti
