### ISSUE TITLE
Annullamento di un cambio di residenza da comune non subentrato a comune non subentrato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#562]
Il titolo è paradossale, ma si riferisce alla data di richiesta del cambio di residenza del cittadino.
In seguito il Comune A (che iscrive), subentra e quindi comunica i dati del cittadino come residente a ANPR.
In seguito il Comune B (che cancella), subentra.  Il cittadino non è presente nei dati inviati a ANPR.

Passa il tempo necessario, e il procedimento viene rigettato. 

Se ho capito bene il Comune A:
- effettua "2003 CancellazioneAltriMotivi"

Il Comune B
- riceve notifica N014
- effettua "1002 IscrizioneAltriMotivi" con motivo iscrizione "Ripristino posizione precedente" (codice 10)

Insomma rientriamo nel caso descritto nella documentazione come "12.1.3 Annullamento di un cambio di residenza da comune non subentrato a comune subentrato"?

**Comment by rvinzani** [comment]
Il comune  A può:
-	annullare l’iscrizione (1013) o 
-	effettuare una cancellazione per altri motivi (2003)
Il comune B di conseguenza può: 
-	effettuare una prima iscrizione(1002)
-	effettuare una reiscrizione (1002+idANPR)
