### ISSUE TITLE
[5008] Completamento dati iscrizione da comune subentrato

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#563]
ambiente di PRODUZIONE - comune di FAENZA

idSchedaSoggetto 19797641
viene iscritto, con dataDecorrenza 01/02/2018) con provenienza da comune subentrato (ws 5001)
in sede di iscrizione definitiva, con dataDecorrenza 15/02/2018, viene sbloccato il flag di certificabilità (ws 5008)

il soggetto, nel precedente comune di residenza (e quindi nella sua posizione in ANPR) mancava di tutti i dati relativi al matrimonio / vedovanza / divorzio ed aveva un errore nella carta di identità

il cliente sta tentando di aggiornare l'anagrafica in ANPR, ma ci scontriamo contro due errori bloccanti:

1. se tentiamo di passare le singole mutazioni, nel tentativo di aggiornare tutti i dati anagrafici il ws (5008) risponde
```
<errore>
  <codiceErroreAnomalia>EN369</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Operazione richiesta non possibile. Non e' presente alcun matrimonio per il soggetto xxx (19797641) corrispondente ai dati inseriti.</testoErroreAnomalia>
</errore>
```
(preciso che il soggetto è DIVORZIATO - rif. idOperazioneComune 2018004468)

2. se tentiamo di comuncare la mutazione '20' di completamento, il ws (5008) risponde:
(rif. idOperazioneComune 2018004469)
```
<errore>
  <codiceErroreAnomalia>EN389</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data decorrenza 01-02-2018 dell'operazione non puo' essere inferiore alla data decorrenza 15-02-2018 dell'ultima operazione effettuata sui dati relativi a generalita' del soggetto</testoErroreAnomalia>
</errore>
```
motivo per il quale abbiamo deciso di non comunicare il perfezionamento delle iscrizioni con tipoMutazione '20'

tenendo presente che preferiremmo seguire la strada di cui al punto '1.', come dovremmo procedere per completare questo aggiornamento?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Avete provato ad eseguire una mutazione di tipo 20 con data decorrenza non minore di 15-2-2018? 
Per quale motivo si deve indicare 1-2-2018?

**Comment by AMonopoliADS** [comment]
è un vincolo imposto dal sistema.
il primo tentativo che abbiamo fatto con tipoMutazione '20' era con dataDecorrenza 15-02-2018 ed il ws, che si aspetta la stessa decorrenza dell'iscrizione, ha risposto così:
```
<errore>
  <codiceErroreAnomalia>EN358</codiceErroreAnomalia>ù
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La data decorrenza del perfezionamento di un'iscrizione deve essere uguale alla data dell'iscrizione stessa 01-02-2018</testoErroreAnomalia>
</errore>
```

**Comment by rvinzani** [comment]
Per risolvere il problema dovrebbe annullare la mutazione fatta il 15/2 e visto che si tratta di perfezionamento dovrebbe fare una mutazione di tipo 20 (alla data di iscrizione) che mette a posto i dati del matrimonio, della carta  di identità e la certificabilità

**Comment by AMonopoliADS** [comment]
questo l'avevo immaginato, ed è proprio quello che volevo evitare.
abbiamo deciso di NON usare il tipoMutazione '20' proprio per questa ragione: se dall'iscrizione preliminare a quella definitiva avessi fatto 2, 3...  4 operazioni che bloccano il completamento dati (tipoMutazione '20') l'operatore dovrebbe stare dietro all'annullamento e alla ricostruzione di tutto.
in ogni caso, indipendentemente dalla quantità di operazioni "bloccanti", questa soluzione non semplifica il lavoro all'utente, tutt'altro.

mi servirebbe una soluzione nell'ambito del servizio 5008 senza l'uso del tipoMutazione '20', che permetta di dare continuità alle operazioni a livello di dataDecorrenza.
in questo specifico caso il soggetto è già divorziato e non ha alcun dato di matrimonio / divorzio... con la mutazione sto solo confermando il suo stato civile, aggiungendo tutte le operazioni che mancano.

valutate la possibilità di alleggerire alcuni controlli.
grazie.

**Comment by rvinzani** [comment]
Quando entrambi i comuni sono subentrati, non esiste più l'iscrizione preventiva e quella definitiva ma una semplice mutazione.  In questa accezione, la mutazione di tipo 20 non sarebbe nemmeno utilizzabile.
In questo caso si tratta di persona transitata in ANPR con dati incompleti che il comune vuole integrare. Esattamente cosa volete fare? Può inviare sulla posta privata i dati da aggiungere?

**Comment by AMonopoliADS** [comment]
"_Quando entrambi i comuni sono subentrati, non esiste più l'iscrizione preventiva e quella definitiva ma una semplice mutazione_": vero, ma - come sapete - il servizio di mutazione non permette aggiornamento di dati anagrafici e, quando i dati acquisiti dal cittadino sono diversi o di più rispetto a quelli presenti nell'ANPR, in qualche modo bisogna poter procedere per aggiornare l'ANPR... di solito mandiamo una lista di mutazioni (su ws 5008), ma in questa occasione abbiamo avuto le difficoltà che vi ho segnalato (è un esempio ma ne capiteranno altri...).
nel caso specifico ho proceduto all'annullamento di '3' operazioni ed inviato un tipoMutazione '20' datata 01-02-2018, perchè il cliente aveva urgenza di sanare e la posizione.
come detto, l'ideale sarebbe trovare una modalità di integrazione di dati che renda il processo un po' più lineare.
grazie

**Comment by gcarbonin** [comment]
Abbiamo rintracciato le informazioni necessarie osservando le operazioni che sono state "tentate" e la situazione della scheda della persona interessata.
Di seguito i problemi riscontrati:
1) la scheda è stata trasmessa al subentro indicando come unico dato del divorzio il motivo di cessazione del matrimonio; questo è un errore in quanto per comunicare che una persona è divorziata è sufficiente indicare lo stato civile
2) è stata effettuata una mutazione di tipo 14 per inserire i dati del divorzio indicando anche parte dei dati del matrimonio. Se si possiedono i dati del matrimonio, si effettua una mutazione 12 e poi la 14; in caso contrario, si trasmette una mutazione 14 con i dati relativi alla cessazione del matrimonio
3) è stata effettuata una mutazione per "sbloccare" il flag certificabilita'. La persona è entrata in ANPR con certificabilità completa; se si modifica questa informazione per rendere parzialmente certificabile il soggetto nelle more degli accertamenti amministrativi,  occorre tener presente che la data di decorrenza che impostate quando si esegue questa mutazione modifica la data di ultima variazione della scheda, cosa che poi influisce sulle operazioni successive. Più correttamente, si dovrebbe aprire il procedimento (cosa che avviene nella realtà anche tra comuni subentrati); in questo modo si bloccano le certificazioni (con possibilità di forzatura) senza alterare la scheda.
