### ISSUE TITLE
Consultazione soggetti residenti in particolare Comune

### ISSUE THREAD

**Issue by rpapini** [italia/anpr#565]
Avrei necessità di fare con comunicazione sincrona (servizio 3002) la ricerca, ad esempio di tutti i soggetti ROSSI / MARIO residenti in uno specifico comune. Analizzando i campi per la ricerca del servizio 3002 non mi sembra possibile.
Saluti
Papini Riccardo

**Comment by umbros** [comment]
.

**Comment by umbros** [comment]
risposta...

**Comment by gcarbonin** [comment]
La consultazione non consente di specificare il comune cui limitare la ricerca.

**Comment by psaggini** [comment]
La presenza di "filtri" per circoscrivere le ricerche su ANPR sarebbe molto utile; a regime, si tratterà di una banca dati molto ampia (più di 60 milioni di persone) per cui avere la possibilità di limitare la ricerca di una persona con molti omonimi inserendo dei filtri come ad esempio una ricerca "per comune" aiuterebbe moltissimo.
A maggior ragione se in un prossimo futuro il portale web potrà essere utilizzato da altre PA per l'accesso ai dati anagrafici.

**Comment by romanobagnacavallo** [comment]
Sono d'accordo con Patrizia; anche con la sola banca dati comunale abbiamo avuto problemi con gli omonimi, ma erano molto più gestibili rispetto ad una banca dati nazionale; penso che il filtro "per comune" sia il più importante (anche se non si può escludere l'importanza anche di altri criteri che possano limitare la ricerca)

**Comment by mccalv** [comment]
Salve inseriamo questa issue nel piano di lavoro.

**Comment by gcarbonin** [comment]
Gli altri criteri (data di nascita luogo di nascita sesso) sono già previsti. manca il filtro sul comune di residenza (e altri che ritenete opportuni)

**Comment by rpapini** [comment]
Secondo me esistono due filtri importanti, il primo comune di residenza, 
il secondo cercare per cognome e nome parziali, non completi. Il secondo 
filtro, sicuramente va legato alla presenza di altri filtri, come per 
esempio il comune di residenza o altri, ma lo ritengo molto utile 
quando  si lavora con stranieri.
Saluti
Papini Riccardo

Il 22/02/2018 11:47, gcarbonin ha scritto:

**Comment by gcarbonin** [comment]
le ricerche parziali sono previste ma non sono sincrone

**Comment by rvinzani** [comment]
La versione 4.1.10 ha implementato quanto richiesto nella issue che pertanto viene chiusa.
