### ISSUE TITLE
Web-App  Monitoraggio operazioni - tipo Operazione non ordinato alfabeticamente 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#57]
Data test 30/03/2017 - Ambiente test (dptest)
Utilità e notifiche / Monitoraggio operazioni
Campo Tipo operazione: l'elenco dei valori disponibili deve essere ordinato alfabeticamente. 
grazie
Stefania Amprimo, Annamaria Gillone, Liliana Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
sistemato puo' riprovare e darmi un riscontro

**Comment by annamariaGillone** [comment]
ok va bene grazie
