### ISSUE TITLE
[1002] Iscrizione in Convivenza del soggetto già Intestatario non residente

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#570]
ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA (BO)

si faccia riferimento alla convivenza con idSchedaANPR 9139562
la convivenza è stata caricata con subentro, con indicazione di Responsabile non residente.
oggi, lo stesso soggetto - prima non residente... - è immigrato nel comune mantenendo il ruolo di Inestatario Convivenza.

nel tentativo di iscriverlo (con ws 1002) con il giusto legame di parentela, il web-service risponde con questo errore:
```
<errore>
  <codiceErroreAnomalia>EN392</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Impossibile indicare il soggetto come responsabile della convivenza: il responsabile e' gia' presente</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018003978)

allora lo abbiamo iscritto come membro della convivenza, ipotizzando di potere eseguire la modifica successivamente all'iscrizione.
l'operazione è andata a buon fine (rif. idOperazioneComune 2018003981)

abbiamo allora provato ad aggiornare il Responsabile della convivenza con ws 5001 è l'operazione è andata a buon fine (rif. idOperazioneComune 2018003985)... ad eccezione del fatto che il servizio ci ha obbligato ad indicare come decorrenza la data di iscrizione del soggetto (23/02/2017) anche se il Responsabile, essendo la stessa persona, ha questo ruolo dal 02/08/2017)

alla fine di queste operazioni, l'interrogazione dei componenti fa comparire il soggetto in questione sia come Responsabile che come Membro della convivenza.

abbiamo allora provato a modificare il legame di parentela del soggetto con ws 5001, ed il web-service va in errore con questo messaggio:
```
<errore>
  <codiceErroreAnomalia>EN384</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Per nominare un nuovo responsabile di una convivenza utilizzare "mutazione famiglia/convivenza"  - tipo mutazione "tutore/responsabile convivenza"</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018003986)

al momento la composizione del nucleo non è coerente con le altre realtà di convivenza dove il Responsabile risiede all'interno del nucleo (nelle quali il soggetto intestatario compare una sola volta...)

come fare a sanare la situazione?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Le operazioni effettuate sono corrette. La data di decorrenza è correttamente quella dell'ultima operazione in quanto in precedenza la persona non era presente in ANPR in quanto residente in altro comune non subentrato. Segno come futura evoluzione un funzione per collegare le informazioni di una persona in situazioni analoghe.
Riguardo al fatto che il responsabile compaia due volte, è una modifica effettuata circa 5 mesi fa su richiesta di altri comuni, per distinguere il caso di responsabile non residente nella convivenza dal responsabile e residente nella convivenza.
In tutti gli altri casi lo vede una sola volta in quanto si tratta di responsabili non residenti in convivenza.

**Comment by AMonopoliADS** [comment]
grazie del riscontro, ma c'è qualcosa che non mi torna.

indipendententemente dalla residenza dell'intestatario, la consultazione dei componenti di una convivenza mi ritorna sempre un solo Responsabile.

alcuni esempi (sempre nell'ambito del comune di SAN LAZZARO DI SAVENA):
1. idSchedaFamigliaANPR 9139548: il Responsabile è residente in altro comune, e compare una sola volta 
2. idSchedaFamigliaANPR 9139557: il Responsabile è residente nel comune, ma in un altro nucleo, e compare una sola volta tra i componenti 
3. idSchedaFamigliaANPR 9139545 - 9139544: il Responsabile è residente all'interno della convivenza e compare una sola volta.
... a parità di condizioni, gli altri soggetti nella situazione di cui al punto '3.' hanno il ruolo di "Responsabile convivenza" anche nella propria scheda individuale e compaiono una volta sola, mentre il soggetto segnalato (idSchedaSoggettoANPR 9139562) - oltra a comparire 2 volte - ha ancora il ruolo di "Membro della convivenza" nella sua scheda individuale (non dovremmo in qualche modo aggiornarlo?)

grazie

**Comment by gcarbonin** [comment]
1.	idSchedaFamigliaANPR 9139548: il Responsabile è residente in altro comune, e compare una sola volta   **perché è solo responsabile e non membro**
2.	idSchedaFamigliaANPR 9139557: il Responsabile è residente nel comune, ma in un altro nucleo, e compare una sola volta tra i componenti  **ci dovrebbe mandare l'id del soggetto in questione**
3.	idSchedaFamigliaANPR 9139545 - 9139544: il Responsabile è residente all'interno della convivenza e compare una sola volta. **Con il file di subentro, non è stato inviato il responsabile della convivenza all’apertura della convivenza, ma è stato inserito con codice legame 1 nell’inserimento dei membri della convivenza, pertanto adesso il responsabile si vede una sola volta;  per sistemare le cose deve occorre un 5001 tipo mutazione 1**

**Comment by AMonopoliADS** [comment]
rif. punto '2.': il soggetto in questione ha idSchedaANPR 19028791

ho comunque capito adesso a che modifica si riferisce (parlando di quanto modificato circa 5 mesi fa...).
fino a settembre 2017, nel file di subentro erano richiesti i dati del responsabile solo se residente altrove, adesso c'è scritto di indicarli in ogni caso.

immagino non sia un requisito fondamentale per il funzionamento dell'ANPR, per cui al momento preferirei lasciare così e valutare più avanti la modifica.

resta il problema non risolto: 
come modificare il rapporto di parentela del soggetto da "membro" a "responsabile"?

grazie

**Comment by gcarbonin** [comment]
Non si tratta di un requisito  per il funzionamento di ANPR ma di una esigenza espressa da alcuni comuni. L'ultima domanda non mi è chiara; la situazione della convivenza dal nostro punto di vista è corretta: la persona è responsabile e residente nella convivenza. Cosa manca?

**Comment by AMonopoliADS** [comment]
il problema è nella scheda individuale del soggetto
nei SUOI dati di appartenenza a famiglia dovrebbe avere il codiceLegame '1' (Responsabile) e non il '2' (Membro)
... come ad esempio il soggetto con idSchedaANPR 9139545

**Comment by frmariani** [comment]
Idscheda ANPR  9139545  è una scheda convivenza e non una scheda soggetto; il responsabile della convivenza è il soggetto idANPR 19057978 che vive all’interno della convivenza ma di cui non sono stati inseriti correttamente i dati in fase di subentro per cui nella consultazione viene visualizzato soltanto come responsabile della convivenza.

La situazione deve essere sanata con il servizio 5001 tipo mutazione 1 confermando correttamente il responsabile della convivenza; la successiva consultazione mostrerà i dati corretti (in questo caso il soggetto sarà sia responsabile che membro della convivenza). 


Anche le seguenti schede convivenze dovrebbero essere sanate allo stesso modo: 

9139544
9139562
9139553
