### ISSUE TITLE
CITTADINI CON COMUNE NASCITA NON VALIDO ALLA DATA DI RIFERIMENTO 

### ISSUE THREAD

**Issue by vitani08** [italia/anpr#571]
SUBENTRO

PREMESSA:
Il Comune di Carinaro, nel periodo 13-04-1929 al 02-07-1946, risulta  inesistente ed inglobato nel Comune di Aversa.
Circa 500 cittadini nati in quel periodo risultano nati (erroneamente) nel Comune di Carinaro invece di Aversa (comune corretto rispetto al file storico dei Comuni rilasciato da ANPR) ed hanno il CODICE FISCALE, VALIDATO DALL'AGENZIA DELLE ENTRATE, con codice catastale B779 (CARINARO) invece del A512 (AVERSA).

RICHIESTA:
Quali sono i passi CORRETTI da eseguire prima ed eventualmente dopo il SUBENTRO?

Grazie per la cortese attenzione

**Comment by gcarbonin** [comment]
Sugli atti di nascita quale comune è indicato?

**Comment by vitani08** [comment]
Sull'atto di nascita risultano:
1)Il responsabile del comune di AVERSA (Sezione IV)
2) Il bambino nato ad Aversa (Carinaro)

Grazie

**Comment by gcarbonin** [comment]
Il luogo di nascita nell'atto è Aversa o Carinaro?

**Comment by vitani08** [comment]
In base a quello che si legge nell'atto e anche alla tabella storica dei comuni :
AVERSA

**Comment by gcarbonin** [comment]
un caso pratico in pre-subentro?

**Comment by vitani08** [comment]
SI
Serve anche un cittadino come esempio con tutti i dati personali?

**Comment by gcarbonin** [comment]
basta un id anpr

**Comment by vitani08** [comment]
Non abbiamo fatto ancora il presubentro, in quanto questa casistica ci ha bloccati.
Se a questi cittadini va sostituito il comune di nascita, e quindi anche il relativo codice fiscale,
cosa succede all'Agenzia delle Entrate? Cosa succede alla Carta Identità? Cosa succede se ha una società individuale? Cosa succede per i relativi diplomi e lauree conseguite? Cosa succede per i suoi conti bancari?
Come bisogna comportarsi e cosa fare nella pratica?

**Comment by gcarbonin** [comment]
A questo link https://www.anpr.interno.it/portale/documents/20182/209665/Attivit%C3%A0+di+bonifica+propedeutiche+al+subentro+in+ANPR+6+febbraio.pdf/f3a84870-e4cd-4394-b728-4666c905ed4a trova tutte le indicazioni del caso.
Prima di procedere, occorre effettuare il pre-subentro e analizzeremo queste  posizioni.  Inviando "nato a Carinaro" con codice fiscale che contiene B779, la posizione viene accettata senza anomalie ed è validata 
 AE (sempre non ci siano altri errori).  La tolleranza è stata introdotta proprio per evitare di creare disagi ai cittadini.  Salvo verifiche puntuali (per questo serve il pre-subentro), dal punto di vista meramente tecnico non occorre fare proprio nulla. Dal punto di vista più generale, il comune dovrebbe segnalare la situazione alla Prefettura e al Ministero in quanto anagrafe e stato civile non dovrebbero contenere dati diversi.

**Comment by vitani08** [comment]
Quindi lasciare tutto come è oggi. Ok Grazie.
Ma poi su questi cittadini i  successivi eventi non comporteranno nessun problema
sul controllo che il Comune di Carinaro alla data di nascita non era attivo?

**Comment by gcarbonin** [comment]
No la tolleranza del subentro c'è anche nei servizi

**Comment by vitani08** [comment]
Grazie Mille
