### ISSUE TITLE
Discordanze sul codice e sulla descrizione del luogo di nascita

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#572]
Terni - Produzione

Premessa:
in data 30/03/1969 il comune di DARFO (BS) cod_istat 017515 Darfo (Brescia) ha cambiato denominazione in DARFO BOARIO TERME (BS) cod_istat 017065.

Due persone residenti nate prima del 1969 hanno nel db locale comune di nascita 017515 DARFO (BS). Il luogo di nascita trasmesso nel file di subentro non ha codice ISTAT perché nella tabella dei comuni ANPR la codifica di DARFO (BS) è 017065 e discorda da quella del db locale.

Gli Id ANPR delle persone sono 20157498 e 20166842.

ANPR ha agganciato DARFO (BS) al codice 017065, come si riscontra consultando l’XML di risposta ad una consultazione, introducendo così una differenza col DB locale.

La form di soluzione dei disallineamenti con Agenzia Entrate dichiara che il CF dei due soggetti è validato e mostra un’ulteriore differenza perché riporta comune di nascita DARFO BOARIO TERME in AE e DARFO in ANPR.

Aggiungo che a Terni ci sono solo due casi con questo luogo di nascita, ma Darfo Boario Terme è nostro cliente e nel db di quel comune il numero di soggetti nati a Darfo prima del 1969 è elevato: 3.692 su 16.218.

Abbiamo due tipi di discordanza:
a) sul codice del luogo di nascita fra ANPR e locale;
b) sulla descrizione del luogo di nascita fra ANPR e AE;
quale rilevanza dobbiamo dargli ?

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Il codice 017515 non è un codice ISTAT ma un codice che ISTAT assegna per identificare una variazione di denominazione; non e' quindi utilizzabile come codice ISTAT: in subentro viene accettato con anomalia; nei servizi darebbe un errore.
In ANPR le due persone sono state inserite  con il codice ISTAT corretto; movimentando le persone occorre ricordare che il codice "500" non deve essere presente nei servizi.
L'Agenzia delle Entrate non ha mai gestito le denominazioni pregresse; le accetta ma espone (ad esempio sulla tessera sanitaria) soltanto l'ultima.

**Comment by sfabrizi** [comment]
"In subentro viene accettato con anomalia", per favore da dove riscontriamo l'anomalia?
Simonetta Fabrizi - Comune di Terni

**Comment by bfilipazzi** [comment]
Nel file "055032SchedeIndivErr20180228.csv" non ci sono queste due persone.
Devo cercarle altrove?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
L'anomalia viene segnalata quando come codice ISTAT del comune (nascita atto ecc.) si indica un codice di variazione di denominazione (valore 5 o 6 in IV posizione). Nel caso specifico delle due persone, non è stato indicato nessun codice ma soltanto la denominazione del comune. L'anomalia in questo caso non viene segnalata.

**Comment by bfilipazzi** [comment]
Nel primo commento di GCarbonin si legge che "Il codice 017515 non è un codice ISTAT" e che "il codice "500 non deve essere presente nei servizi".
017515 è un codice storico di Darfo Boario Terme (BS), riferito a quando il nome del comune era Darfo. E' un codice che il gestionale mette a disposizione qualificandolo come Codice ISTAT.

Darfo Boario Terme è nostro cliente e l'ho interpellato.
L'Ufficio di anagrafe mi scrive:
"TUTTE LE STATISTICHE CHE SI INVIANO ALL'ISTAT CON I DATI ANAGRAFICI (P4, P5, APR4, POSAS, STRASA) DEVONO CONTENERE I CODICI COME DA TABELLA DEI COMUNI CHE HANNO CAMBIATO DENOMINAZIONE, ALTRIMENTI DA' ERRORE" e mi fa notare che la tabella ISTAT dei comuni in uso per AnagAIRE contiene i codici "500".

Il cliente non commenta il fatto che l'Agenzia delle Entrate non gestisca i codici "500", ma osserva che il DPR 223/1989 aggiornato con legge 126/2015 attribuisce all'ISTAT e non all'Agenzia i compiti di vigilanza sull'anagrafe.

Sarebbe utlie un chiarimento perché in mancanza di un riferimento certo che induce a fare il contrario, conserveremo nel db locale i codici "500" introducendo un disallineamento con ANPR sulla codifica, anche se non sulla descrizione.
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Nel sito ISTAT  si trova  "Il **codice identificativo della vecchia denominazione** viene generato concatenando al codice della provincia a tre cifre un progressivo nell’intervallo 500-620."; non parla di codice ISTAT.
Questa codifica è stata introdotta per il sistema SAIA che usa il codice ISTAT come chiave; viene usata per lo stesso motivo anche dal sistema AIRE. In questo caso, quando si estraggono i dati per formare l'elenco unico, si elimina il codice lasciando la sola denominazione in quanto nè il Sistema Informativo Elettorale nè il Ministero degli Affari Esteri utilizzano questa codifica.
L'Istat ha un ruolo importante nella definizione delle nomenclature di ANPR, nel senso che sono loro gli owner per la parte di competenza e a questo ci dobbiamo attenere.
