### ISSUE TITLE
Chiarimento sul EC075

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#573]
Terni - Produzione

Premessa:
in data 28/05/1958 si è costituito il comune di BOTRUGNO (LE) cod_istat 075009.

Tra i residenti di Terni c'è la persona con ID ANPR: 20166790
che nel db locale risulta nata a BOTRUGNO (LE) due anni prima della costituzione del comune.

Il gestionale ha trasmesso in subentro il luogo di nascita BOTRUGNO (LE) cod_istat 075009 e ha trasmesso in modo identico anche il comune di registrazione dell'atto di nascita.

Nel file 055032SchedeIndivErr20180228.csv trovo una segnalazione EC075 sul comune dell'atto di nascita non valido alla data ma nessuna eccezione sul comune di nascita.

Questa differenza disorienta il cliente, c’è una spiegazione?

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Sul comune di nascita ci sono alcune tolleranze che evitano variazioni di codici fiscali e di documenti: se dai dati inviati dal comune si risale allo stesso codice catastale contenuto nel codice fiscale, il dato si considera corretto a prescindere dalle date (di nascita e di istituzione del comune). Sul comune dell'atto viene segnalata l'anomalia in quanto a quella data il comune non esisteva.
