### ISSUE TITLE
Errore in rimpatrio di intera famiglia

### ISSUE THREAD

**Issue by busaster** [italia/anpr#574]
Terni - Ambiente di produzione.
Con l'operazione ID 2477753 si tenta di far rimpatriare in italia una famiglia AIRE composta da un unico componente.
Per eseguire l'operazione viene invocato il servizio 5001 ma otteniamo come risposta un "EF002 : Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata".

In ambiente di test (di altro comune) nel passato abbiamo provato situazioni uguali senza ricevere alcun errore (es l'operazione ID ANPR 745856 del 5 febbraio 2018).

E' cambiato qualcosa nella gestione di queste mutazioni ?
Se sì, come dobbiamo comportarci ?

Grazie

**Comment by cmigliardi** [comment]
La Request (sia in produzione che in Test-Comuni)  riporta idfamigliaAireAnpr e tiposcheda = 3   ma trattandosi di famiglia Aire il tiposcheda deve essere = 5     il controllo è stato inserito dopo il 5 febbraio ecco perché in Test-comuni l'operazione è passata.

**Comment by busaster** [comment]
grazie, provvederemo ad adeguare l'applicativo
