### ISSUE TITLE
[1001] Iscrizione per nascita - Errore ES013

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#575]
ambiente di PRODUZIONE - comune di FAENZA

in data di oggi (05/03/2018) viene registrato atto di nascita di bambino nato all'estero l'01/10/2017.
il web-service (1001) ritorna errore bloccante:
```
<errore>
  <codiceErroreAnomalia>ES013</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>L'anno e la data di formazione del'atto di nascita non possono essere precedenti alla data di nascita ne' successivi alla data di decorrenza dell'operazione</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018005373)

si precisa che la data di formazione del'atto non è stata indicata.

da un'analisi fatta sulle iscrizioni per nascita registrate a cavallo dell'anno, abbiamo trovato un caso similare che è andato a buon fine (idOperazioneComune 2018000079 - idSchedaSoggettoANPR 19659972), che ha una decorrenza 2017 e l'atto registrato nel 2018.

qual è il problema in questo caso?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Abbiamo rivisto il controllo ES013. Potete riprovare a fare la stessa operazione. Attendiamo un vostro riscontro.

**Comment by AMonopoliADS** [comment]
abbiamo ripetuto l'invio della comunicazione ed è andata a buon fine.
grazie.
