### ISSUE TITLE
Ricerca scheda famiglia di altro comune

### ISSUE THREAD

**Issue by busaster** [italia/anpr#576]
Chiavari - Ambiente di produzione

La ricerca della scheda famiglia con il servizio 3002 di una famiglia ANPR non residente nel mio comune restituisce l'errore "EN122 La richiesta effettuata non produce alcun risultato".
Ripetendo la stessa operazione sulla stessa famiglia ma nel comune subentrato in cui è presente (Lavagna) viene restituito il risultato.

Avete bloccato la consultazione delle famiglie di altri comuni ?
Ricordo lo fosse nel 2016, il blocco fu poi rimosso.

Per noi è fondamentale sapere la composizione della famiglia migrante per decidere se usare il servizio 5001 o il 5005.

**Comment by gcarbonin** [comment]
Possiamo avere l'id anpr della famiglia?

**Comment by busaster** [comment]
E' la famiglia in cui risiede il soggetto ID ANPR 18536197

**Comment by busaster** [comment]
se può aiutare , oltre alla ricerca con il WS 3002 abbiamo provato anche con la consultazione famiglia in webapp riscontrando in quel caso  la presenza di due nuovi campi filtro "provincia" e "comune" precompilati con "GENOVA" e "CHIAVARI" , non modificabili.

**Comment by mttfranci** [comment]
E' possibile interrogare anche famiglie di competenza di altri comuni eccetto il caso in cui la famiglia sia non certificabile, ad esempio perchè incompleta. La famiglia da voi indicata è in questa situazione.

**Comment by busaster** [comment]
Ho controllato. 
Effettivamente cercando con il 3002  la famiglia ID ANPR 8906516 vediamo l'anomalia "EN212 Non puo' essere emesso il certificato richiesto perche' la famiglia e' ancora in fase di registrazione".
Ma la famiglia a me risulta essere entrata in ANPR al subentro e non avere mai avuto modifiche.
Potete verificare per favore ?

**Comment by gcarbonin** [comment]
La famiglia non ma sono stati modificati i due componenti con l'inserimento del matrimonio. In questi casi (coniugi appartenenti alla stessa famiglia) il comune riceve un messaggio W che indica di aggiornare le relazioni di parentela; la famiglia viene resa non certificabile

**Comment by busaster** [comment]
Abbiamo contattato lavagna e abbiamo fatto sistemare la variazione di Parentela.
Il comune corrispondente Chiavari ha poi processato con successo la sua mutazione.

Certo che risulta difficile per il comune corrispondete (in questo caso Chiavari) capire il problema. 
Sarebbe molto utile che, in caso di famiglia non certificabile, il 3002 invece di ritornare "EN122 La richiesta effettuata non produce alcun risultato" restituisse un diverso codice di errore che permetta di capire si tratti di famiglia esistente con anomalie.
