### ISSUE TITLE
Subentro AIRE e caratteri non ASCII

### ISSUE THREAD

**Issue by busaster** [italia/anpr#577]
Comune di Perugia - Presubentro

Abbiamo prodotto con il nostro applicativo il file per il subentro aire allo stesso modo in cui produciamo l'export da caricare con ANAG-AIRE in un comune non ANPR.
In questo export ci sono alcuni cittadini con nel cognome o nome i caratteri "Ñ , Ò , É , Ö". 
ANAG-AIRE li digerisce, mentre quando tentiamo di caricare il presubentro veniamo fermati da un 
controllo di validazione :
![image](https://user-images.githubusercontent.com/1733338/37028594-0a169546-2135-11e8-8cca-bd47431e9756.png)

Il file che noi produciamo per ANAG-AIRE ha la codifica ISO-8859-1. Dobbiamo forse usare la codifica UTF8 per il file di presubentro/subentro,?

**Comment by mttfranci** [comment]
Buongiorno.
Abbiamo reso un vincolo meno stringente. Potete riprovare con lo stesso file?

**Comment by busaster** [comment]
Abbiamo riprovato ed i files sono stati accettati senza problemi.
Grazie
