### ISSUE TITLE
Errore registrazione evente decesso

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#579]
Nella registrazione di un decesso abbiamo il seguente errore:
ERRORE DA ANPR: 
EN484 - Per ruolo soggetto = 2 il soggetto che si sta cancellando non deve essere l'intestatario della famiglia e l'elenco dei soggetti non deve essere valorizzato.
La stessa anomalia si presenta nella registrazione di un ripristino.
Comune di Altamura.

**Comment by RBiasi** [comment]
Buongiorno,
(Cesena e Castiglion Fiorentino produzione) abbiamo anche noi la stessa anomalia mi dicono dipenda dagli aggiornamenti di ieri, è sia necessario adeguare il sistema alle nuove regole di validazione.

**Comment by gcarbonin** [comment]
Scusate per l'inconveniente: questo errore **per il momento** deve essere segnalato come anomalia e non come errore bloccante. Stiamo intervenendo.

**Comment by gcarbonin** [comment]
Il problema dovrebbe essere risolto

**Comment by Finalmentesubentrati** [comment]
Confermo. Appena registrato evento di morte. tutto ok
