### ISSUE TITLE
Web App - Problemi con gestione procedimento

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#58]
Con operazione ID 447921 abbiamo registrato un Iscrizione per altri motivi da comune non subentrato (ID ANPR del soggetto 4090705) con warning EN111 "Indicare il procedimento collegato al servizio" in quanto appositamente non era stato aperto prima il procedimento.
Con operazione ID 447967 abbiamo aperto il procedimento 3320 selezionando il soggetto appena iscritto e richiamando il n. procedimento del comune indicato anche nell'iscrizione di cui sopra.
Abbiamo alcune considerazioni:
1) dalla consultazione del soggetto non è possibile riscontrare che l'anomalia EN111 è stata sanata. A tal proposito stiamo preparando una proposta di modifica per una migliore visibilità del procedimento che invieremo nei prossimi giorni, non appena ulteriormente chiarite le idee;
2) nonostante la chiusura del procedimento nr. 3320 con operazioni successive ID 447993 - 447996 - 447978 - 448097 - 448860 il sistema non sblocca la certificazione del soggetto in questione come sarebbe invece previsto dalle specifiche (Codice: EN04 Per il soggetto, può essere prodotto esclusivamente un certificato di residenza o di stato di famiglia); lo sblocco va a buon fine esclusivamente utilizzando il servizio di mutazione;
3) forse, in questo punto, le specifiche andrebbero riviste perchè la normativa vigente prevede che il soggetto diventi completamente certificabile già dopo la conferma dell'avvenuta acquisizione dei dati e non a completa chiusura del procedimento;
4) al fine di evitare errori da parte dell'operatore (in caso di utilizzo esclusivo della web app) potrebbe essere utile preimpostare il campo a "certificabilità parziale" in caso di iscrizione per altri motivi, lasciando comunque la possibilità di modificare la scelta dal menù a tendina;
4) il sistema consente la chiusura di un procedimento già chiuso: come indicato al punto 2 abbiamo provato più volte a chiudere un procedimento.
Grazie, 
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino
Data del test: 30/03/2017 - Ambiente di test

**Comment by gcarbonin** [comment]
1. attendiamo la proposta. In ogni caso EN111 non riguarda la persona ma l'operazione
2. Chiariremo meglio le specifiche: se esiste un procedimento aperto, la certificazione è bloccata e si ripristina soltanto chiudendo il procedimento. Nel caso in esame era stato impostato dal comune la non certificabilità; in tale situazione, la certificazione si ripristina soltanto se il comune modifica questo dato.
3. per avvenuta acquisizione dei dati, si intende la mutazione di completamento con la quale si acquisiscono i dati dell'APR4?
4. La certificabilità è una  scelta del comune
5. Metteremo un controllo

**Comment by VBocchinoTO** [comment]
2. Abbiamo testato una nuova iscrizione aprendo il procedimento 3388 ed iscrivendo il soggetto id ANPR 4378773. Volutamente, non abbiamo compilato il campo relativo alla certificabilità e, con procedimento aperto, abbiamo potuto stampare un certificato diverso da residenza e stato famiglia. Quale voce deve essere scelta per innescare l'automatismo previsto dalle specifiche? Allo stato attuale ci pare di capire che non esiste alcun automatismo e che la certificabilità dipende esclusivamente da come è valorizzato il campo della certificabilità a prescindere dall'esistenza o meno di un procedimento in corso/chiuso.
3. Si. Sarebbe utile gestire lo sblocco automatico della certificazione e la variazione dello stato del procedimento a seguito della mutazione di acquisizione dati.
4. Si, è vero, ma dal momento che il regolamento anagrafico impone la certificabilità parziale dal momento dell'iscrizione e fino all'acquisizione completa di tutti i dati dal Comune di provenienza, riteniamo possa essere utile preimpostare il valore di default, lasciandolo comunque modificabile per i casi in cui già al momento dell'iscrizione si disponga dei dati completi e quindi non sia necessaria alcuna limitazione della certificazione (ad esempio reiscrizione nello stesso comune di cancellato per irreperibilità). Si chiede inoltre di valutare l'opportunità di eliminare la scelta "blank" in quanto di fatto si comporta come "certificabilità completa" e potrebbe indurre in errore.

**Comment by gcarbonin** [comment]
2. Abbiamo verificato i certificati: sono stati richiesti PRIMA delle 15.50 quando il soggetto è stato associato al procedimento
3. Verificheremo anche con qualche altro comune; la modifica effettuata via WEB, infatti, modifica il funzionamento dei servizi che sono così anche per i comuni già subentrati
4. Questo dato è sempre stato considerato "a discrezione del comune".

**Comment by VBocchinoTO** [comment]
2.  Abbiamo provato a creare altri due casi: in uno abbiamo provato a lasciare il campo "certificabilità" non valorizzato e nell'altro invece abbiamo impostato la certificabilità parziale. Alleghiamo un file in cui abbiamo tracciato tutte le operazioni effettuate e gli esiti rispetto all'emissione della certificazione. Vi chiediamo aiuto per capire come gestire il procedimento/certificabilità al fine di far innescare l'automatismo di sblocco certificazione (per ora a chiusura procedimento, salvo variazione richiesta al punto 3) che ci sembra essere previsto nelle specifiche.
3. Ringraziamo per la verifica. Rimaniamo in attesa di riscontro.

[testCERTNONVAL.pdf](https://github.com/italia/anpr/files/905368/testCERTNONVAL.pdf)
[testCERTPARZIALE.pdf](https://github.com/italia/anpr/files/905370/testCERTPARZIALE.pdf)

**Comment by gcarbonin** [comment]
Se utilizzate l'attributo della persona "certificabilita' soggetto" (nell'esempio parziale), il sistema correttamente stampa soltanto la residenza e lo stato di famiglia; per rimuove il blocco si deve variare questo attributo.
Se utilizzate il procedimento collegandolo alla persona (stiamo mettendo un automatismo), fino alla chiusura non si producono certificati.
