### ISSUE TITLE
Errore Anpr Cod: EN483 - Per ruolo soggetto = 1 il soggetto che si sta cancellando deve essere l'intestatario della famiglia e l'elenco dei soggetti deve essere valorizzato

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#580]
Collegata alla segnalazione Errore registrazione evente decesso #579 è stato risolto il solo errore EN484 Cancellazioni per decesso e non l'errore EN483 Cancellazioni per altri motivi.

Siamo a posto per Cesena che aveva segnalato le cancellazioni per decesso ma non con Castiglion Fiorentino che aveva segnalato per le cancellazioni per altri motivi. Vi risulta?

Grazie

**Comment by gcarbonin** [comment]
Stiamo intervenendo anche su questo

**Comment by gcarbonin** [comment]
dovrebbe essere tutto a posto

**Comment by RBiasi** [comment]
confermo
