### ISSUE TITLE
EC075 nel file SchedeIndivErr

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#583]
Nel file “Elenco segnalazioni ANPR operazioni anagrafiche_06_03_2018.xlsx” ci sono i tre errori seguenti: 
"EC075 - Comune/provincia di registrazione atto di nascita @ inesistente o non valido alla data di registrazione - ERROR", 
"EC166 - Comune/provincia di registrazione atto di nascita @ inesistente - ERROR",
"EC169 - Comune/provincia di registrazione atto di nascita @ non valido alla data di registrazione - WARNING".

Un Comune cliente subentrato la scorsa settimana ha 491 righe di EC075 nel file SchedeIndivErr, immagino che in gestione sollevino l'eccezione EC166 o EC169 in base al caso, mi sembra importante avere una distinzione nel file SchedeIndivErr distinguendo i due errori. Mi sfugge il senso dell'EC075.
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
EC075 viene restituito in subentro ed è non bloccante. Gli altri nei servizi: il primo è bloccante in quanto non è consentito indicare comuni che non esistono; il secondo è non bloccante in quanto sul comune dell'atto non ci sono controlli stringenti (se non quello di esistenza).

**Comment by gcarbonin** [comment]
In subentro NON è bloccante e non rientra tra gli errori da correggere prima del subentro: si corregge (ove fosse inesistente) se e solo se si movimenta quell'atto con una successiva mutazione
