### ISSUE TITLE
Fusione 4 comuni

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#584]
Comune di Valle Mosso - produzione

Prossimamente iniziera' il percorso che portera' (almeno questo e' il proposito delle amministrazioni interessate) alla fusione di 4 comuni in un nuovo unico comune dal nome ancora non noto e di circa 11.100 abitanti.
Di questi 4 comuni solamente Valle Mosso e' subentrato in anpr ma gli altri 3 stanno lavorando per subentrare in breve tempo.
Dovendo programmare gli interventi necessari al processo di fusione chiedo di conoscere quali procedure si renderanno necessarie a ridosso della data dell'istituzione del nuovo comune 1/1/2019 con la contemporanea cessazione degli attuali.
In particolare se e' preferibile (se non obbligatorio) il subentro dei 3 comuni restanti, se il cambio dovra' essere poi trattato comune una mutazione di indirizzo verso il comune che anpr dovra' creare ex-novo, 
che fine fara' la storicizzazione del dato anpr ecc.
Le domande sono sicuramente molte e assai complesse ma anche se mancano diversi mesi mi rendo conto che il tempo e' abbastanza tiranno.
Se ci sono/saranno altre esperienze in merito saro' grato a chi vorra' metterle a disposizione sul forum

**Comment by gcarbonin** [comment]
Non ci sono casi simili per il momento.
Abbiamo analizzato gli interventi da eseguire in questi casi che sinteticamente sono questi:

- i comuni che si fondono devono essere tutti subentrati;
- Anpr  viene aggiornata automaticamente associando tutte le persone residenti nei comuni soppressi al nuovo comune;
- gli utenti (tranne i sindaci) sono associati al nuovo comune; questo non comporta la produzione di nuove smart card;
- sono generati i nuovi certificati di postazione;
- dobbiamo ancora definire a livello amministrativo chi nomina il nuovo responsabile della sicurezza (commissario che viene nominato all'atto della fusione in attesa di elezioni).

Dobbiamo definire se e come aggiornare gli identificativi comunali (scheda individuale, famiglia/convivenza).

**Comment by RBiasi** [comment]
Tipicamente in caso di fusioni vi possono essere anche numerosi cambi di toponomastica. Se ad esempio tutti e quattro i comuni hanno una VIA GIUSEPPE GARIBALDI tre di queste andranno incontro ad un cambio di toponomastica.

**Comment by gcarbonin** [comment]
Ovviamente. Per queste operazioni c'è già la mutazione

**Comment by RBiasi** [comment]
massiva o singola per cittadino?

**Comment by gcarbonin** [comment]
La mutazione è puntuale per famiglia; è possibile realizzare un batch che invoca la singola mutazione

**Comment by bfilipazzi** [comment]
In un contesto ante ANPR il comune di nuova istituzione inizia la sua storia dal giorno in cui è istituito, e le variazioni di toponomastica per risolvere le omonimie dei toponimi si compiono prima della fusione e quindi sono comprese nelle storie dei comuni che si estinguono.

Abbiamo seguito in questi ultimi anni alcune decine di fusioni, nella maggioranza dei casi le amministrazioni hanno deciso di aggiungere agli indirizzi il descrittivo del comune estinto, indipendentemente dal problema dell'univocità. Mi spiego con un esempio: i comuni AAAA, BBBB e CCCC si fondono in DDDD; nel nuovo contesto DDDD gli indirizzi che appartenevano ad AAAA diventano del tipo VIA PARIGI 4 - AAAA; questo per facilitare l'orientamento sul territorio di chi deve trovare VIA PARIGI 4, visto che ora DDDD è formato da 3 agglomerati urbani distinti, e anche per aiutare chi consulta un documento a capire in quale dei tre luoghi si trova VIA PARIGI.
In ANPR si potrebbe ottenere il risultato usando l'attributo FRAZIONE.
Non so se e come andrebbe classificata questa variazione in ANPR.
Filipazzi - Maggioli

**Comment by RENZO63** [comment]
![toponimi duplicati](https://user-images.githubusercontent.com/32871636/37391957-2c523aaa-276d-11e8-8676-b613007eb6e1.JPG)

Allego uno stralcio delle note Istat allo stradario emanate in data 10/02/2015 relative ai casi di toponimi duplicati.
Anche nel nostro caso le Amministrazioni coinvolte dalla fusione hanno la volonta' di inserire quale parte dell'indirizzo la denominazione della localita' intesa come la denominazione del comune cessato.
Questo pero' non consente comunque di avere toponimi duplicati all'interno del nuovo comune (come ben specificato dalla nota Istat).
L'unica soluzione al problema (scartando ovviamente il cambio dell'intero toponimo) e' quello del cambio della tipologia di toponimo (ad esempio da piazza a piazzale o largo ecc., da via a viale o corso ecc.) perche' in questo caso il toponimo ridiventa univoco all'interno del comune.
Infatti e' possibile avere nello stesso comune ad esempio  via chiesa e piazza chiesa 
In ogni caso stiamo ancora valutando la strategia migliore

**Comment by gcarbonin** [comment]
Per comunicare la frazione si utilizza sempre la mutazione di residenza
