### ISSUE TITLE
Annullamento Iscrizione in errore

### ISSUE THREAD

**Issue by busaster** [italia/anpr#586]
Poggio a Caiano.
Ambiente di test.
Eseguo tre operazioni : due iscrizioni aire par altri motivi (IDS 2647124 e 2647125) e una mutazione altri dati (ID 2647126).
Le prime due con esito positivo, la terza va in errore.
Provo ad annullare con il la più recente delle iscrizioni (la 2647125), ma ottengo l'errore "EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa".

Non capisco proprio quale sia l'operazione che blocca l'annullamento.
Ho consultato anche la lista operazioni in WebApp ma non vedo nessuna operazione con esito positivo seguente la 2647125.
![image](https://user-images.githubusercontent.com/1733338/37280906-7be4db38-25ef-11e8-901e-6c6c22cf78e9.png)

A cosa è dovuto il blocco ? Altro domanda : cos'è l'operazione ID 2647127 ?

**Comment by azabatta** [comment]
Buonasera, 
la problematica è già stata individuata e rimossa: è in corso l’estensione della modifica  negli ambienti esposti.  Le comunicheremo quando sarà possibile riprovare.
L’operazione di validazione dati anagrafici è un refuso che stiamo provvedendo ad eliminare.
Grazie per la segnalazione

**Comment by azabatta** [comment]
La modifica è stata estesa, è possibile riprovare. Buona giornata

**Comment by busaster** [comment]
Confermo, il problema ora non si presenta più.
Grazie
