### ISSUE TITLE
Errore in iscrizione AIRE per altri motivi

### ISSUE THREAD

**Issue by busaster** [italia/anpr#587]
Poggio a Caiano - Ambiente di test
Tento di iscrivere in AIRE per altri motivi (C09) un soggetto.
Specifico anche le note al motivo di iscrizione.
ID operazione ANPR : 2647751
Ottengo però l'errore "EC013 : Campo Note Motivo Iscrizione AIRE obbligatorio se codice Motivo iscrizione = C09 - Altro"

**Comment by gcarbonin** [comment]
nella richiesta pervenuta ad ANPR le note al motivo di iscrizione non ci sono

**Comment by busaster** [comment]
A me pare ci siano :

<iscrizioneAire>
        <motivoIscrizione>C09</motivoIscrizione>
        <noteMotivoIscrizione>ESISTENZA</noteMotivoIscrizione>
        <iniziativaIscrizione>1</iniziativaIscrizione>
        <individuazioneComuneIscrizione>1</individuazioneComuneIscrizione>
        <dataArrivoConsolato>2018-01-01</dataArrivoConsolato>
    </iscrizioneAire>

**Comment by gcarbonin** [comment]
Arriva soltanto <motivoIscrizione>C09</motivoIscrizione>

**Comment by busaster** [comment]
e com'è possibile ?
quello che vi ho incollato è tratto dal dump della chiamta SOAP......

**Comment by gcarbonin** [comment]
vedo quello che arriva completati i controlli di sicurezza

**Comment by busaster** [comment]
può essere che i controlli di sicurezza "taglino" il motivo ? Mi suonerebbe strano...

**Comment by gcarbonin** [comment]
La vedo difficile. Stiamo controllando i log; eventualmente facciamo una prova telefonica congiunta

**Comment by gcarbonin** [comment]
Abbiamo effettuato alcune prove e individuato un possibile problema. Può riprovare?

**Comment by busaster** [comment]
Riprovato, l'iscrizione è andata a buon fine ed i dati in ANPR sono corretti

**Comment by gcarbonin** [comment]
Prefetto
