### ISSUE TITLE
errore AEE97 su mutazione anagrafica - immigrazione da altro comune

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#589]
Buongiorno, 
la richiesta idOperazioneComune>31843 - idOperazioneANPR>2516557 
restituisce l'errore AEE97 incomprensibilmente senza descrizione dell'errore e quindi non ci consente di individuare il problema.
Cortesemente chiedo motivazioni per chiudere la richiesta d'iscrizione del cittadino.
Grazie
Raffaella 
Comune di Spinea

**Comment by cmigliardi** [comment]
l'operazione è andata a buon fine -
