### ISSUE TITLE
Web app - Iscrizione per altri motivi di cittadino italiano proveniente dall'estero

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#59]
Simulando la registrazione dell'iscrizione di un cittadino italiano proveniente dall'estero ed iscritto all'AIRE di comune non subentrato (Agrigento) (operazione n. 447437), non è consentito inserire sia il comune di iscrizione AIRE che la località estera di provenienza. 
Qual è il modo corretto di gestire questa operazione dal momento che:
- l'ufficiale d'anagrafe è tenuto a chiedere la cancellazione al comune di iscrizione AIRE,
- se perdessi l'informazione del luogo estero di provenienza perderei anche l'informazione che si tratta di un già iscritto AIRE?
Grazie, 
Valentina Bocchino -  Comune di Torino
Data del test: 29/03/2017 - Ambiente di test

**Comment by gcarbonin** [comment]
Il luogo di provenienza è previsto nelle specifiche essenzialmente perché lo ha richiesto ISTAT; dal loro punto di vista, la provenienza è lo stato estero.
L'informazione che il cittadino era in precedenza un iscritto AIRE rimane in quanto il motivo di iscrizione è esplicito (trasferimento dall'AIRE di comune non subentrato).
E' previsto un campo Note del motivo di iscrizione che puo' essere utilizzato per salvare il comune di precedente iscrizione. Se questa soluzione non è sufficiente, occorre un intervento evolutivo nell'applicazione.

**Comment by gcarbonin** [comment]
E' possibile attualmente indicare il comune di provenienza nel caso di variazione del comune di iscrizione AIRE; lo stato di provenienza è associato alla residenza del soggetto quindi è un dato disponibile.
