### ISSUE TITLE
[6001] richiesta certificato da richiedente diverso e non subentrato

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#590]
Buongiorno, in ambiente di presubentro di Bistagno (006017) abbiamo richiesto tramite WebApp un certificato indicando un richiedente che non è presente in ANPR specificando le generalità e il documento. L'operazione (IdAnpr 1556971)  ci ha restituito il certificato anche se con esito positivo e warning "Il documento del soggetto richiedente non e' presente in ANPR". Fin qui tutto ok. 
Se invece, cerchiamo di riprodurre la stessa operazione tramite client java sogei ci restituisce errore (vedere vari tentativi 1556983, 1556994, 1557015, ... ) "Indicare un documento di riconoscimento", nonostante nel corpo del messagio siano stati specificati i dati del documento. 
Potreste gentilmente fare un controllo sulle richieste fallite e se possibile inviarci sulla mail anche la request prodotta dalla WebApp per l'operazione 1556971? Grazie

**Comment by gcarbonin** [comment]
Richiesta inviata via e-mail. Nelle altre richieste non vedo il documento di riconoscimento

**Comment by Eduardo1977** [comment]
Grazie per aver controllato. Rifacciamo qualche altro test sulla base del file che ci avete inviato. 
Comunque, in merito al richiedente venivano mandati questi dati (nel file .req):
<generalitaRichiedente>
<generalita>
<codiceFiscale>
<codFiscale>........</codFiscale>
</codiceFiscale>
<cognome>...</cognome>
<nome>.....</nome>
<dataNascita>........</dataNascita>
</generalita>
<DocRiconoscimento>
<estDocRiconoscimento>.........</estDocRiconoscimento>
<dataRilascio>..........</dataRilascio>
</DocRiconoscimento>
</generalitaRichiedente>

In effetti, inviando la richiesta tramite client java, confermo che nella richiesta che viene stampata a video scompare il tag  <DocRiconoscimento> .... </DocRiconoscimento>
Dipende dal fatto che non è specificato il "<luogoNascita> ... </luogoNascita>" ?
Inoltre, approfitto per segnalare che il file delle specifiche "docRiconoscimento.xlsx" non riporta correttamente "estDocRiconoscimento" .

**Comment by Eduardo1977** [comment]
Scusate, riporto nuovamente i tag del richiedente qui:
`<generalitaRichiedente>
<generalita>
<codiceFiscale>
<codFiscale> . . . . . </codFiscale>
</codiceFiscale>
<cognome>. . . . .</cognome>
<nome>. . . . .</nome>
<dataNascita>. . . . .</dataNascita>
</generalita>
<DocRiconoscimento>
<estDocRiconoscimento>. . . . .</estDocRiconoscimento>
<dataRilascio>. . . . .</dataRilascio>
</DocRiconoscimento>
</generalitaRichiedente>`

**Comment by gcarbonin** [comment]
Può mandare la richiesta sulla mia mail?

**Comment by Eduardo1977** [comment]
Si subito. Anzi le invio la richiesta modificata con cui ho fatto i test adesso.  Da sempre lo stesso errore. Forse c'è qualcosa di sbagliato nei "dati di controllo".

**Comment by gcarbonin** [comment]
il problema è <DocRiconoscimento> che dovrebbe essere <docRiconoscimento>; stiamo verificando lato "nostro" perchè la richiesta sia stata accettata; è non validata e quindi dovrebbe generare un Internal Server Error

**Comment by Eduardo1977** [comment]
Ok grazie come sempre per la pazienza. Comunque, i dati del luogo di nascita del richiedente sono obbligatori? Perchè dalle specifiche sembrerebbe di no, invece utilizzando la WebApp sembra di si.

**Comment by gcarbonin** [comment]
Se il richiedente non è residente in comune subentrato i dati vanno inviati tutti

**Comment by Eduardo1977** [comment]
Grazie. Quindi, i dati da inviare sono:
`<generalitaRichiedente>
<generalita>
<codiceFiscale>
<codFiscale> . . . </codFiscale>
<validitaCF>. . . </validitaCF>
</codiceFiscale>
<cognome> . . . </cognome>
<nome> . . . </nome>
<dataNascita> . . . </dataNascita>
<luogoNascita>
<comune>
<nomeComune> . . . </nomeComune>
<codiceIstat> . . . </codiceIstat>
<siglaProvinciaIstat> . . </siglaProvinciaIstat>
</comune>
</luogoNascita>
</generalita>
<docRiconoscimento>
<estDocRiconoscimento> . . . </estDocRiconoscimento>
<dataRilascio> . . . </dataRilascio>
</docRiconoscimento>
</generalitaRichiedente>`
Il dato **validitaCF** si può omettere?

**Comment by gcarbonin** [comment]
assolutamente si
