### ISSUE TITLE
Stessa denominazione via ma su frazioni diverse

### ISSUE THREAD

**Issue by marcnic** [italia/anpr#591]
Buongiorno,

caso simile all'issue #584 seppure non coinvolga una fusione di comuni.
Abbiamo un comune pronto al subentro in ANPR (zero residenti e zero Aire scartati in pre-subentro).
Ci siamo però accorti adesso che ci sono diverse vie con medesima denominazione ma con frazioni diversa.
Per ANPR questo è un problema ?

Ho chiesto al comune se possibile bonificare tali situazioni ma la situazione è la seguente (cito):
"Questo è il nostro caso..vie uguali su frazioni diverse.
Ho fatto presente già tempo fa, più volte, il problema all’amministrazione comunale, ma non sono propensi per il momento a voler modificare il nome delle vie, nonostante l’obbligo di legge, aimè..
Ho rimarcato più volte l’importanza che ha per noi sistemare la situazione, ma per il momento su questo punto siamo fermi..
In ogni caso, il procedimento per il cambio di toponomastica è di lunga attuazione, perché la delibera del consiglio comunale va poi inoltrata alla commissione provinciale della toponomastica per la successiva approvazione..i tempi credo siano un po’ lunghi.."

Possiamo subentrare comunque o è meglio rimandare (di parecchi mesi) il subentro in attesa della bonifica della toponomastica comunale ?

Grazie in anticipo per l'indicazione,

Marco Nichelatti

**Comment by RENZO63** [comment]
Mi chiedo come abbiano fatto a certificare tali aree di circolazione sul portale dell'Agenzia del Territorio ANNCSU...

**Comment by gcarbonin** [comment]
Non è un problema per ANPR al momento
