### ISSUE TITLE
Rimpatrio AIRE

### ISSUE THREAD

**Issue by Elenalomazzi** [italia/anpr#592]
In ANPR si sta reiscrivendo per rimpatrio un cittadino iscritto AIRE nel nostro Comune (si sta lavorando con webservice).
Non è possibile procedere all'iscrizione perché viene riportato il seguente errore : "ERRORE DA ANPR: 
EN187 - il Soggetto (codice fiscale) , (cognome, nome), (data di nascita), e' gia' iscritto o deceduto"
Ho controllato direttamente sul portale di ANPR e il soggetto risulta ancora iscritto AIRE, dovrebbe quindi potermi consentire la mutazione anagrafica.
id. soggetto 18927294.
Resto in attesa di un cortese riscontro.
Codiali Saluti.
Elena Lomazzi

**Comment by frmariani** [comment]
per il rimpatrio di un soggetto AIRE deve effettuare una mutazione di residenza, servizio 5005 per il solo soggetto o servizio  5001 se il rimpatrio riguarda l'intera famiglia; da un'analisi sul soggetto ho verificato che in data 20/02/2018 era stato correttamente inviato un servizio 5005, ma l'operazione è stata  successivamente annullata.

**Comment by Elenalomazzi** [comment]
l'evento era stato fatto in ANPR direttamente sul portale dalla collega, che pensava di risolvere così l'errore EN187. Così non è stato, perciò si è provveduto ad annullare l'evento per poterlo effettuare in webservice.
Essendo allineato il programma in locale con ANPR dovrebbe consentirmi di rifare l'evento, ma così non è e continua a propormi l'errore.

**Comment by gcarbonin** [comment]
Continuate a fare l'iscrizione che nel caso in esame non è effettuabile: occorre una mutazione come sopra indicato
