### ISSUE TITLE
WA Data decorrenza pregressa su mutazione residenza 

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#593]
Buongiorno!
Ambiente DPTEST, vorrei eseguire una mutazione residenza a un minore LLRDRD10A07L219P per indirizzo di convivenza (V. C.I.Giulio 22 P 02), ma il sistema contesta la data di decorrenza che non è oggi, ma il 1.2.2018.
Cosa sbaglio?
Grazie
Ciao
Stefania Amprimo - UPI

**Comment by gcarbonin** [comment]
Mi sembra un'operazione fatta via WEb; c'è una data che indica la data dell'operazione che è automaticamente impostata alla data di oggi: in caso di variazione di residenza questa data deve coincidere con quella di decorrenza della residenza (1-2-2018). Infatti l'errore (se ho trovato l'operazione giusta) è La data decorrenzaResidenza deve essere uguale alla data decorrenza dell'operazione. Ricordo poi che in questo sito sarebbe opportuno non indicare dati personali (come il codice fiscale) ma piuttosto un identificativo della persona o dell'operazione. L'ambiente è pre-subentro; corretto?

**Comment by UpiTorino** [comment]
Ciao
E' un'operazione eseguita su WEB in ambiente Pre-subentro.
1) soggetto con ID ANPR 4538492 - inserito solo nel campo Data decorrenza* il valore 01/02/2018 perchè coincida con quella della decorrenza della residenza e nel campo Data di definizione della pratica ho lasciato 15/03/2018, ma mi ha dato errore per incoerenza date di decorrenza
2)soggetto con ID ANPR 4541005 - ho inserito nei campi Data decorrenza e Data di definizione della pratica il valore 01/02/2018  perchè coincidessero con quella della decorrenza della residenza e mi ha dato errore il seguente errore "La residenza del soggetto con ID ANPR 4541005 non puo' essere variata in quanto la data di decorrenza residenza 19-06-2012 risulta precedente a quella di iscrizione APR del soggetto 25-07-2016 (Codice: EN425)".
Ciao 
Stefania

**Comment by gcarbonin** [comment]
Nel primo test, la data di decorrenza della residenza non è stata indicata.
Nel secondo faremo qualche controllo in più ma temo sia un caso di posizione conferita in subentro quando alcune date non erano presenti (data di iscrizione nel comune in particolare) e oggi fanno scattare questi controlli di congruenza sulle date. Direi di sospendere questi test fino a quando non avete aggiornato la base dati oppure utilizzare posizioni nuove (facciamo l'iscrizione ad esempio)

**Comment by gcarbonin** [comment]
Avete effettuato qualche test con la nuova base dati?
