### ISSUE TITLE
Chiarimento ramo Residenza, campo tipoIndirizzo

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#594]
Ambiente di test. id anpr 2772174. vedo per caso per la prima volta nella risposta del ws 3002, sotto il ramo residenza due diversi indirizzi. mi accorgo che il campo tipoIndirizzo identifica quello che mi serve, come anche mostrato sulla wa dello stesso soggetto.
Avevo sottovalutato la tabella, per cui la vado a controllare, e vedo due codici 
1 | Residenza
4 | Residenza estera
che mi sembrano chiaramente quelli fondamentali.

Ho un dubbio invece su
10 | Revisione onomastica stradale

Se mai ricevessi nella consultazione 3002 un codice 10 cosa devo intendere?

**Comment by gcarbonin** [comment]
Significa che è una residenza (come codice 1) variata a seguito di una revisione della onomastica stradale

**Comment by MarcoMigliori** [comment]
Grazie, quindi devo ricevere su un singolo cittadino, una solo risposta con codice 1 o 4 o 10. Mentre invece possono essere presenti altri indirizzi per gli altri codici.
