### ISSUE TITLE
Problema certificazione soggetto con caratteri minuscoli

### ISSUE THREAD

**Issue by busaster** [italia/anpr#595]
Perugia - Ambiente di Produzione

In fase di subentro è stato caricato un soggetto AIRE con il cognome in caratteri maiuscoli.
In realtà al suo interno doveva avere una particella "di" in minuscolo.
Con la webapp abbiamo corretto il dato, ricevendo esito "operazione completata con successo" ma anche uno strano avviso di "nessun dato modificato".

Abbiamo poi cercato di produrre un certificato di residenza AIRE (ID operazione ANPR 2662992) ricevendo però l'errore "EN084 La ricerca per cognome ha estratto un soggetto o piu' soggetti  con i restanti dati anagrafici non congruenti".
Nel XML della richiesta di certificato inviamo il cognome del soggetto come ora risulta in ANPR, ovvero con la particella 'di' minuscola.

Potete aiutarci a capire cosa succede ?
Grazie

**Comment by gcarbonin** [comment]
La variazione è stata effettuata correttamente: il cognome e' tutto maiuscolo tranne la particella che e' minuscola. Il cognome indicato nella richiesta di certificato non è corretto (c'è un pezzo in più in fondo). In

**Comment by busaster** [comment]
Abbiamo poi scoperto che Il cognome risulta troncato in quando è un subentrato AIRE ed il con cognome superiore ai 36 caratteri, per cui abbiamo aperto altra issue (597).
