### ISSUE TITLE
[Identificativo Operazione Comune] Possibile conflitto tra software di diversi fornitori

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#596]
In merito al codice univoco "IdOperazioneComune" da inserire nell'header di ogni richiesta/servizio, avrei da qualche tempo dei dubbi/timori leggendo le relative specifiche. 

> Identificativo Operazione Comune: è un identificativo numero univoco attribuito dal comune; ANPR controlla se:

> - Esiste già lo stesso identificativo per un servizio/operazione diversi e in questo caso restituirà un codice di errore;

> - Esiste lo stesso identificativo per lo stesso servizio/operazione e in questo caso restituisce l’esito del servizio/operazione già effettuata in precedenza dal comune.

> Tale identificativo dovrebbe essere cresente (almeno per le operazioni dello stesso tipo eseguite nella stessa giornata) in modo da consentire una corretta gestione della storicizzazione da parte di ANPR.

Come si fa a generare un IdOperazioneComune "valido" (cioè non utilizzato già) in presenza di altri applicativi che usano i WS ANPR sviluppati da altri fornitori? Non credo ci si possa mettere d'accordo. In questo caso si avrebbero dei seri problemi di conflitto? C'è una soluzione in merito? Grazie

**Comment by gcarbonin** [comment]
Ci sono comuni che utilizzano sw anagrafici di fornitori diversi?

**Comment by Eduardo1977** [comment]
Mi vengono in mente subito due possibili scenari. 

1. Un comune subentrato con azienda X che dopo un anno decide di passare all'azienda Y. In questo caso, Y da dove parte con gli Id? Si deve preoccupare di cosa faceva il sw della X?
2. Un comune che per la gestione dell'anagrafe (ufficio anagrafe, backend) si avvale di X, e contemporaneamente per i servizi online al cittadino (frontend) si avvale di Y.

**Comment by Eduardo1977** [comment]
Speravo che il conflitto si potesse risolvere tramite i campi nell'header:

- nomeApplicativo
- versioneApplicativo
- fornitoreApplicativo

**Comment by gcarbonin** [comment]
Quanto suggerito è piuttosto complesso da realizzare. Valuteremo la sua segnalazione in seguito

**Comment by gcarbonin** [comment]
Chiudo in quanto lo stesso agormanto è trattato nella issue 814
