### ISSUE TITLE
Cognome e Nome limitati a 36 caratteri inAnagAIRE

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#597]
AnagAIRE dispone di 36 caratteri per il cognome e altrettanti per il nome.
E' una dimensione insufficiente per i nomi più lunghi, infatti lo standard ANPR è 80 + 80.
Il cognome di un iscritto AIRE di Perugia nel db locale è di 43 caratteri, nell'export verso ANPR si sono perduti gli ultimi 7.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Abbiamo valutato la situazione e l'intervento avrebbe un impatto devastante anche su sistemi esterni. AnagAire non è modificabile, Per altro questi campi hanno una dimensione ridotta da lustri e da lustri si formano le liste elettorali con questi dati.
