### ISSUE TITLE
EAV31 in iscrizione per altri motivi

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#598]
Perugia Produzione
ID operazione ANPR 2712089
Iscrizione da estero 
EAV31 CF presente ma dati anagrafici non congruenti
Il soggetto ha nome formato da due parole, che in AE sono unite da un trattino mentre nella pratica che il comune sta istruendo il trattino non c'è perché non risulta dai documenti dell'interessato
Qual è il percorso migliore per aggirare questo problema? Non è un caso infrequente. Grazie
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
E' possibile procedere in due modi:
-	Si iscrive il soggetto con gli stessi dati di AE poi effettuano una variazione dei dati anagrafici.
-	Si iscrive il soggetto con gestioneCF = 3 poi si rettificano i dati con Risoluzione disallineamenti AE

**Comment by bfilipazzi** [comment]
Grazie
