### ISSUE TITLE
Cambio di generalita' e codice fiscale

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#599]
COMUNE DI VALLE MOSSO - PRODUZIONE

Oggi si presenta il seguente caso (che espongo prima di tentare qualsiasi operazione anpr per avere le informazioni necessarie per evitare “danni”)

(Ovviamente tutti i nomi e i dati sono di fantasia)

Nel 2017 si e' proceduto ad iscrivere in anagrafe un richiedente asilo che aveva prodotto un titolo di soggiorno da cui si sono estratti i dati anagrafici necessari.
E' stato iscritto con i seguenti dati:
Cognome    PINKO    Nome    PALLINO   nato a  ABIDJAN (Costa d'Avorio) 1/1/86  codice fiscale  PNKPLN86A01Z313M 

Oggi si presenta il richiedente asilo con un nuovo titolo di soggiorno con dati anagrafici molto diversi:
Cognome   PINKO   Nome   CAIO   nato a  BOUAKE (Costa d'Avorio) il 1/1/86 codice fiscale PNKCAI86A01Z313R 

Da una verifica all'anagrafe tributaria risultano due persone non collegate in sede di emissione del nuovo codice fiscale (risulta un codice fiscale provvisorio e non il codice effettivo precedente)

Fermo restando che e' necessario acquisire dalla Questura un'attestazione che confermi che si tratti della stessa persona vorrei sapere se il sistema accettera' le variazioni di nome, luogo di nascita e codice fiscale senza problemi dal momento che all'Anagrafe Tributaria risulteranno presenti 2 persone non collegate.

Se lo ritenete utile posso inviare a mezzo mail privata i dati reali qui omessi per ovvie ragioni

Grazie per l'attenzione

**Comment by gcarbonin** [comment]
I dati reali sulla mail privata sono utili

**Comment by mccalv** [comment]
@RENZO63 @gcarbonin potreste riportare qui le indicazioni di carattere generale ricevute a seguito dell'analisi del caso? Grazie

**Comment by rvinzani** [comment]
A breve verrà rilasciata in produzione la funzionalità che prevede di collegare due codici fiscali attribuiti allo stesso soggetto sebbene non collegati in AE. La richiameremo appena possibile seguendo se necessario l'operazione tramite assistenza remota

**Comment by RBiasi** [comment]
tramite webservices?

**Comment by rvinzani** [comment]
No, dalla funzionalità presente nel sito Web - Risoluzione disallineamenti Agenzia Entrate

**Comment by RBiasi** [comment]
grazie dell'informazione
