### ISSUE TITLE
web service - stato civile "già coniugato"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#60]
buongiorno.

il cliente usa lo stato civile "già coniugato" per individuare chi ha ottenuto lo scioglimento/cessazione del matrimonio.
considerato che tale stato civile non è previsto nella tabella degli stati civili (tabella 01), viene passato il codice '9' - non classificabile, valorizzando le note con la descrizione esatta dello stato civile.
questo non è stato un problema fino a che non abbiamo iniziato a testare il servizio di mutazione (5008)

in generale, nella gestione di questa informazione ANPR si comporta in questo modo:
- in fase di subentro viene acquisito lo stato civile così come passato ed anche i dati di cessazione del matrimonio
- in fase di iscrizione (ws 1002) viene acquisito lo stato civile ed anche i dati di cessazione di matrimonio
- in fase di mutazione da "coniugato" a "già coniugato" (ws 5008), passando il tipo_mutazione 14 (annullamento  matrimonio) il servizio va in errore perchè vincola all'uso dello stato civile "divorziato"
CODICE_ERRORE: ES113
TESTO_ERRORE: Per  tipo Mutazione annullamento matrimonio lo stato civile deve essere uguale a divorziato/a e devono essere presenti i dati previsti in caso di cessazione/annullamento del matrimonio

... se assecondiamo il vincolo di passare lo stato civile "divorziato" (codice '4') al posto di "già coniugato" (codice '9'), vengono acquisiti i dati di cessazione del matrimonio, ma non viene aggiornato lo stato civile ed il soggetto (o i soggetti, se i coniugi sono collegati) rimane con lo stato civile "coniugato"
(fare riferimento all'idOperazioneComune 2017000321 - ambiente dptest - comune di Faenza )

a parte la segnalazione di quest'ultimo errore, si chiede se è possibile e come fare a mantenere in uso lo stato civile "già coniugato" grazie.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
In entrambi i casi di tratta di due vincoli definiti dal Ministero dell'Interno:
1) lo stato civile "gia' coniugato" non esiste sulle tabelle ufficiali  e per questo motivo non è previsto; in tutti i casi di scioglimento/cessazione del matrimonio si indica come  stato civile divorziato/a; è stato verificato anche di recente con uno dei comuni gia' subentrati. 
2) oltre alla comunicazione dei dati dello scioglimento, occorre modificare lo stato civile di ciascuno dei due coniugi; la mutazione non viene  eseguita in automatico da ANPR quando si comunica l'evento (divorzio o decesso di uno dei due) in quanto il titolare della registrazione è il sindaco ed occorre pertanto una mutazione "esplicita".
