### ISSUE TITLE
[N010] Ricezione notifiche

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#600]
Buongiorno,
a seguito di una mutazione di residenza tra due comuni, le chiamate in ambiente di test eseguite il 20/03/2018 con id operazione ANPR:

<idOperazioneANPR>2661524</idOperazioneANPR>
<idOperazioneANPR>2661439</idOperazioneANPR>
<idOperazioneANPR>2660859</idOperazioneANPR>
<idOperazioneANPR>2651586</idOperazioneANPR>

non hanno generato notifiche all'endpoint impostato sul comune di destinazione.

Grazie

**Comment by gife67** [comment]
Buongiorno,
dalla tarda mattinata stiamo tentando di inoltrarvi le notifiche verso il vostro endpoint che in ambiente di Test Comuni è condiviso per i Comuni di Gardone Riviera e Savigliano, ma riceviamo dei Soap Fault.
Vi ricordo che le notifiche hanno il campo <contenuto> crittografato con il certificato Server del Comune (ex 017074-CO-9999), ovviamente per decriptarlo dovete essere in possesso della chiave privata contenuta nel keystore, disponibile nella sezione **Sicurezza** del sito web dell'ambiente di Test Comuni. Inoltre tutto il messaggio di notifica è firmato tramite XMLSignature.
Se potete contattarmi via email (gferraro@sogei.it) possiamo verificare insieme la problematica.
Grazie

**Comment by FilippoPapi** [comment]
In

**Comment by gcarbonin** [comment]
il vostro endpoint continua ad essere irraggiungibile

**Comment by SAlberto** [comment]
Buongiorno,

abbiamo deciso di non utilizzare l'endpoint, ma la chiamata 3003 per avere l'elenco delle notifiche.

Grazie per il supporto.
