### ISSUE TITLE
Operazione di Iscrizioni altri motivi - errore bloccante EC178 - Codice specie Toponimo 228 incongruente con la relativa descrizione VIA VICINALE

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#601]
Cesena Produzione
Buongiorno, In fase di invio di un'operazione di iscrizione altri motivi abbiamo l'errore bloccante 
EC178 - Codice specie Toponimo 228 incongruente con la relativa descrizione VIA VICINALE

Sotto dettaglio di come viene compilato il tag toponimo nella richiesta.

<toponimo>
<codSpecie>228</codSpecie>
<specie>VIA VICINALE</specie>
<specieFonte>1</specieFonte>
<denominazioneToponimo>CASTIGLIONE</denominazioneToponimo>
</toponimo>

Attendo gentile riscontro.
Grazie

**Comment by gcarbonin** [comment]
Si può avere l'id operazione?

**Comment by RBiasi** [comment]
<idOperazioneComune>202401</idOperazioneComune>

**Comment by azabatta** [comment]
Buonasera, 
abbiamo individuato l'errore  e stiamo predisponendo una correttiva.
Vi informeremo appena sarà possibile riprovare.

**Comment by RBiasi** [comment]
grazie

**Comment by azabatta** [comment]
La  correttiva è stata portata in tutti gli ambienti, è possibile inviare nuovamente la richiesta di iscrizione. Restiamo in attesa di un cortese riscontro sull'esito dell'operazione.
