### ISSUE TITLE
[1002] Ripristino Posizione Precedente - Chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#602]
alla luce di svariate situazioni di ripristino anagrafico su cui ci siamo imbattuti, avrei bisogno di qualche chiarimento riguardo l'iscrizione di soggetto con ws 1002 e motivo '10' - Ripristino Posizione Precedente.

nel caso specifico, iscriviamo con questa modalità i soggetti emigrati prima del subentro (quindi non presenti in ANPR) che devono essere "ripristinati" in seguito agli accertamenti negativi del comune di destinazione.

nella migliore delle ipotesi, il soggetto da re-iscrivere ha corrispondenza di:
- data iscrizione
- data decorrenza famiglia
- data decorrenza indirizzo
ed in questi casi, l'iscrizione va a buon fine permettendo la comunicazione delle informazioni che il soggetto aveva nell'anagrafe locale prima dell'emigrazione.

i problemi si pongono quando le date di cui sopra non sono allineate.
in tali casi, il web-service mi costringe a passare come dataDecorrenza quella maggiore.

faccio un esempio pratico: 
ambiente di PRODUZIONE - comune di FAENZA - idSchedaSoggettoANPR 21413494.

il soggetto è emigrato prima del subentro.
il 05/03/2018 deve essere iscritto ripristino.
le sue date di riferimento, da residente, sono le seguenti:
- iscritto nel comune dal 09/11/2004
- residente all'indirizzo attuale dal 03/11/2017

tentando l'iscrizione con decorrenza 09/11/2014 (idOperazioneComune 2018006523) il web-service risponde con questi errori:
```
<listaErrori>
	<errore>
		<codiceErroreAnomalia>EHR81</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>L'anno dell'atto di matrimonio e la data di formazione dell'atto di matrimonio non possono essere precedenti alla data del matrimonio ne' successivi alla data di decorrenza dell'operazione</testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>ES010</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>La data del matrimonio deve essere maggiore della data di nascita e minore o uguale della data di decorrenza dell'operazione</testoErroreAnomalia>
	</errore>
	<errore>
		<codiceErroreAnomalia>EF056</codiceErroreAnomalia>
		<tipoErroreAnomalia>E</tipoErroreAnomalia>
		<testoErroreAnomalia>La data decorrenza appartenenza alla famiglia  deve essere uguale alla data decorrenza dell'operazione</testoErroreAnomalia>
	</errore>
</listaErrori>
```
l'operazione va a buon fine se passiamo come dataDecorrenza il 03/11/2017 (idOperazioneComune 2018006525)... ma stampando un Certificato di Residenza Storico, il soggetto risulta residente a Faenza dal 03/11/2017.

come riuscire a passare ad ANPR la reale situazione storica del soggetto?
usiamo il metodo sbagliato per iscrivere in seguito a ripristino?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
La soluzione adottata è corretta. I dati nel periodo precedente al 3-11-2017 (contengono una o piùvariazioni di indirizzo nel comune) non sono in ANPR: la ricostruzione storica deve tener conto dei dati del comune e di quelli di anpr dalla data di iscrizione in avanti

**Comment by AMonopoliADS** [comment]
non mi è comunque chiaro cosa dovremmo fare per potere passare la corretta decorrenza dell'iscrizione.

allo stato attuale il certificato di residenza storico riporta queste informazioni:
_

> Risulta iscritto con i seguenti dati:
> Comune di FAENZA (RA) dal 03/11/2017
> Indirizzo Via Roma N. 14 - Interno: 8 dal 03/11/2017

_
che sono corrette rispetto all'indirizzo e non rispetto alla residenza nel comune.

faccio presente che in un caso come questo (che non è una iscrizione "tipica" da migrazione o da accertamento), mi aspetterei una maggiore tolleranza, più vicina a quella che si ha con il subentro, dove viene passata una fotografia del soggetto con le sue informazioni "a quella data").
capisco che in fase operativa ci saranno più controlli e più situazioni di cui tenere conto, ma giusto per dare un'idea dell'aspettativa...

grazie

**Comment by gcarbonin** [comment]
La data di prima iscrizione nel comune (nel caso specifico 9-11-2004) è un dato previsto solo nel subentro e non c'è nel servizio di iscrizione; quindi non viene acquisita.

**Comment by gcarbonin** [comment]
Per il certificato storico di residenza completo (a prescindere dal caso in esame), occorre acquisire i dati locali fino alla data del subentro (o di iscrizione in ANPR come in questo caso) e aggiungere i dati registrati in ANPR (si ottengono con il servizio 6001 con richiesta dati). In questo modo, la persona sarà correttamente iscritta nel comune dal 9-11-2004.

**Comment by AMonopoliADS** [comment]
questa può essere una soluzione per il comune in cui il soggetto risiede.

...ma il problema resta per la consultazione e la certificazione richiesta da altri enti o comuni che prenderanno per buona la data così come registrata su ANPR.

**Comment by gcarbonin** [comment]
una interrogazione o un certificato richiesto da un altro comune esporrà sempre e soltanto i dati dal subentro in poi in quanto gli altri dati non ci sono

**Comment by AMonopoliADS** [comment]
giusto per tirare delle conclusioni:
c'è un soggetto, emigrato al momento del subentro, ma da ripristinare in seguito ad accertamenti negativi effettuati nel comune di destinazione.
tale soggetto dovrebbe risultare iscritto nel comune dal 9/11/2014 (come altri componenti nella sua famiglia), ma il sistema, per coerenza rispetto alla data di decorrenza dell'ultimo indirizzo, mi vincola ad iscriverlo nel comune dal 3/11/2017.
personalmente, data la pubblicità del dato, mi sembra che situazioni come questa diano adito a "qualche" problema di interpretazione.
se mi confermate che per ANPR questa situazione è normale, condivido il tutto con il cliente e lascio che faccia le sue condierazioni.
grazie
Alessandro

**Comment by gcarbonin** [comment]
Come già detto sopra la data data di iscrizione nel comune viene comunicata soltanto al subentro e poi si aggiorna con le successive movimentazioni. Nel caso della iscrizione per ripristino quella che si indica non è la data di iscrizione nel comune ma la data di decorrenza dell'indirizzo "ripristinato". I dati antecedenti sono storici e visibili soltanto presso il comune interessato
