### ISSUE TITLE
[5005] da famiglia a convivenza

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#603]
Buongiorno,

ci troviamo in ambiente di test, abbiamo effettuato la mutazione di residenza di un individuo intestatario scheda da una famiglia anagrafica con 2 componenti a una convivenza (casa di riposo).
Tramite chiamata 5005 ci è tornato "Operazione non effettuabile", invece tramite portale è andato tutto bene effettuando correttamente il cambio residenza.

Vi invio una mail con la richiesta da noi prodotta e la stessa richiesta prodotta dal portale, a noi pare non ci siano differenze, potete aiutarci a capire il problema?

Grazie

**Comment by gcarbonin** [comment]
è sufficiente l'idoperazione del 5005

**Comment by SAlberto** [comment]
L'id dell'operazione fatta DA PORTALE è questo: 2663216, ma questa operazione è andata a buon fine.
Quella che è fallita è quella da chiamata, ma di quella non abbiamo un ID da darle.

Vi ho trasmesso a "segnalazioni-anpr@teamdigitale.governo.it" i due xml

**Comment by gcarbonin** [comment]
Il problema è dovuto al fatto che l'applicazione WEB utilizza l'id ANPR attribuito alla scheda convivenza che è univoco, mentre da servizio è stato utilizzato l'id comune: la ricerca in questo caso restituisce due risultati. provvediamo noi ad inserire un controllo aggiuntivo. Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
E' possibile riprovare il servizio

**Comment by SAlberto** [comment]
Buongiorno,
abbiamo chiesto al Comune di riprovare la mutazione di residenza ed è avvenuta con successo.

Grazie, cordiali saluti
