### ISSUE TITLE
gestioneCF in PRE-SUBENTRO

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#605]
Buongiorno,
siamo in ambiente di PRE-SUBENTRO, volevamo chiedere un chiarimento,
la gestione dei codici fiscali va affrontata mettendo gestioneCF = 3 come per l'ambiente di TEST oppure sono già attive le comunicazioni con l'Agenzia delle Entrate?
Se va settato a 3 sarà possibile testare il funzionamento degli altri valori solo in ambiente di PRODUZIONE?

Grazie

**Comment by gcarbonin** [comment]
L'utilizzo di CF = 3 riguarda le posizioni conferite in pre-subentro che, nella quasi totalità dei casi, non sono presenti nell'AT di test cui puntano di servizi di registrazione di ANPR. E' possibile eseguire un test completo dei servizi creando posizioni "nuove"; ad esempio:

- si effettua l'iscrizione di una persona chiedendo l'attribuzione del CF;
- si effettua l'iscrizione di una persona con gli stessi dati anagrafici di cui al punto precedente, testando la situazione dell'omocodia;

.....

Occorre tener presente che prima di variare un CF attribuito, occorre attendere 24 ore prima che diventi definitivo: in quelle 24 ore, infatti, il CF può essere annullato (altro test da eseguire).

**Comment by gcarbonin** [comment]
Ovviamente per le posizioni conferite con il pre-subentro è possibile richiedere l'attribuzione del codice fiscale
