### ISSUE TITLE
[1002] Iscrizione di Soggetto Vedovo senza data matrimonio - EN382

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#606]
Soggetto immigrato con i soli dati di vedovanza; i dati del matrimonio non sono stati
dichiarati.
La comunicazione va in errore  EN382 - La data di matrimonio è obbligatoria.
Ambiente di produzione Comune di Dozza (BO) - ID OPERAZIONE COMUNE 2018000916

E' possibile superare il blocco, visto che l'informazione non è conosciuta?

Grazie
Saluti
Christian Olivato ADS

**Comment by frmariani** [comment]
All’id operazione comune indicato, corrisponde un altro diagnostico di errore: EF056 La data decorrenza appartenenza alla famiglia  deve essere uguale alla data decorrenza dell'operazione;

Comunque, può inserire una vedovanza inserendo almeno il nome, cognome e sesso del coniuge senza data del matrimonio

**Comment by AMonopoliADS** [comment]
abbiamo individuato la causa nella mancanza di una data all'interno delle informazioni caricate dal cliente.
l'operazione è andata a buon fine.

grazie
