### ISSUE TITLE
Carattere barra nell'esponente e nella frazione dell'indirizzo

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#608]
Abbiamo ricevuto in questi ultimi giorni segnalazioni dai comuni di Perugia e di Lucca da cui risulta che la presenza del carattere "/" (barra) nei campi dell'esponente1 del numero civico e della frazione dell'indirizzo di residenza impediscono la validazione del CF delle persone.

Chiedo conferma che il carattere barra sia da escludere dai due campi e che conseguentemente dobbiamo aspettarci una modifica degli XSD.
Se così fosse nel frattempo andremmo ad introdurre opportuni controlli nel nostro sw per rimuovere la barra dai db locali prima dei futuri subentri ed impedirne l'input in gestione. Ritengo importante sostituire la barra con altro carattere di separazione per mantenere la leggibilità del dato, per questo chiedo se il carattere "-" (meno) sia un'alternativa adeguata da proporre ai clienti.

Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Il trattino non crea problemi nei campi esponente e frazione. Gli xsd saranno modificati prossimamente; trattandosi, in ogni caso, di una modifica non retro-compatibile i controlli in ambiente di produzione saranno attivati più in là.

**Comment by bfilipazzi** [comment]
Ok, mettiamo appena possibile un controllo nel gestionale per non riversare altre barre "/" in esponente e frazione, previa sostituzione con trattino "-" nel gestionale. I db locali potrebbero contenere la barra "/" in corte, scala e piano, dobbiamo controllare anche questi attributi del civicoInterno?
Grazie. Filipazzi - MAggioli

**Comment by gcarbonin** [comment]
Pubblicheremo a breve l'elenco delle variazioni applicate sui vari campi; consiglio di procedere successivamente a questo aggiornamento

**Comment by gcarbonin** [comment]
L'elenco è stato pubblicato. Attendo eventuali osservazioni
