### ISSUE TITLE
[5008] Mutazione Paternita / Materrnita: annullamento campi - ES057

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#609]
ambiente di PRODUZIONE - Comune di FAENZA

il soggetto con idSchedaANPR 19144042 presenta dati di paternita / maternita errati.
con web-service 5008 e tipoMutazione 10 e 11, il cliente sta cercando di comunicare l'annullamento di queste due informazioni.

la request contiene questi tag:
```
	<paternita>
		<generalita>
			<senzaCognome>1</senzaCognome>
			<senzaNome>1</senzaNome>
		</generalita>
	</paternita>
	<maternita>
		<generalita>
			<senzaCognome>1</senzaCognome>
			<senzaNome>1</senzaNome>
		</generalita>
	</maternita>
```

ma il web-service ritorna i seguenti errori:
```
				<listaErrori>
					<errore>
						<codiceErroreAnomalia>ES044</codiceErroreAnomalia>
						<tipoErroreAnomalia>E</tipoErroreAnomalia>
						<testoErroreAnomalia>Indicare almeno il cognome o il nome del genitore</testoErroreAnomalia>
					</errore>
					<errore>
						<codiceErroreAnomalia>ES057</codiceErroreAnomalia>
						<tipoErroreAnomalia>E</tipoErroreAnomalia>
						<testoErroreAnomalia>Specificare in alternativa che il soggetto e' senza cognome o senza nome&#xD;</testoErroreAnomalia>
					</errore>
					<errore>
						<codiceErroreAnomalia>ES044</codiceErroreAnomalia>
						<tipoErroreAnomalia>E</tipoErroreAnomalia>
						<testoErroreAnomalia>Indicare almeno il cognome o il nome del genitore</testoErroreAnomalia>
					</errore>
					<errore>
						<codiceErroreAnomalia>ES057</codiceErroreAnomalia>
						<tipoErroreAnomalia>E</tipoErroreAnomalia>
						<testoErroreAnomalia>Specificare in alternativa che il soggetto e' senza cognome o senza nome&#xD;</testoErroreAnomalia>
					</errore>
				</listaErrori>

```
fare riferimento alla comunicazione con idOperazioneComune 2018006895

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
I campi "Senza nome" e "Senza cognome" si utilizzano principalmente per i soggetti stranieri che per alcune popolazioni in particolare non utilizzano una delle due informazioni; se viene indicato "senza nome", il cognome è obbligatori e viceversa.

**Comment by AMonopoliADS** [comment]
allora non sappiamo come risolvere la richiesta del cliente.
in presenza dei tipiMutazione 10 e 11, i tag "paternita" e "maternita" sono, giustamente, obbligatori... ed in loro assenza il web-service ne segnala la mancanza (rif. idOperazioneComune 2018006841)
come fare quindi ad eliminare queste due informazioni dalla scheda del soggetto?

**Comment by gcarbonin** [comment]
Si utilizza il servizio 5013

**Comment by AMonopoliADS** [comment]
abbiamo tentato l'uso del servizio 5013.

a parte il dettaglio che i codici previsti per i tipiRevoca (tabella 48) sono:
1 | paternità
2 | maternità
ma il servizio si aspetta '01' e '02', i tentativi di invio hanno risposto tutti:
999 - E - Operazione non effettuabile

(rif. idOperazioneComune 2018006902 - 2018006903 - 2018006904)
ambiente di PRODUZIONE - comune di FAENZA

**Comment by gcarbonin** [comment]
Manca la data di decorrenza in testata nella richiesta che inviano.

Può  riprovare.

**Comment by AMonopoliADS** [comment]
"operazione non effettuabile" lascia pensare a problemi di altra natura (in passato abbiamo visto il messaggio a causa di problemi momentanei, o indisponibilità di servizi... per i quali bastava la ripetizione in un momento successivo).
potrebbe aiutare a risolvere prima il problema un messaggio più specifico che, forse, in questo caso poteva riportare l'assenza del dato mancante.
comunque grazie.
con la dataDecorrenza valorizzata la comunicazione è andata.

**Comment by gcarbonin** [comment]
Questo messaggio viene restituito (preceduto dal codice 999) viene restituito in tutti i casi in cui l'applicazione rileva un errore non gestito: nel caso specifico, il servizio non gestiva correttamente la situazione di campo dataDecorrenza = null. Ora è stato inserito un controllo e un messaggio specifico.
Ci sono poi altre situazioni analoghe che a volte dipendono da errori di sistema (sono precedute da un codice differente). Abbiamo un sistema di monitoraggio interno di questi errori che ci consente di intervenire anche nella direzione suggerita.
