### ISSUE TITLE
[5008] Vedovanza - Errore EN398: la data di vedovanza deve essere uguale alla data di morte

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#610]
Siamo in ambiente di Pre-Subentro, abbiamo inserito un decesso e la conseguente vedovanza.
Come risposta alla seconda comunicazione (la vedovanza) otteniamo l'errore in oggetto. 

Analizzando l'XML inviato la data di decorrenza e la data evento della vedovanza corrispondono alla data del decesso.

L'id operazione ANPR della vedovanza è 1574541

Ringrazio anticipatamete

**Comment by frmariani** [comment]
Un problema impedisce il buon esito dell’operazione, avviseremo quando sarà possibile riprovare.

Comunque, la vedovanza del coniuge superstite, viene inserita automaticamente con il decesso del soggetto;  l’operazione di modifica dello stato civile deve essere acquisita con il servizio 5008 tipo mutazione 1.

**Comment by SAlberto** [comment]
Buongiorno,
la fase di modifica di stato civile con la 5008 l'avevamo già predisposta nella sequenza di chiamate, ma come da voi suggerito la fase di mutazione di vedovanza era di troppo, abbiamo provato a toglierla e siamo riusciti a raggirare il problema.

Restiamo comunque in attesa della risoluzione del problema che avete individuato.

Grazie, cordiali saluti.

**Comment by gcarbonin** [comment]
Il problema è stato risolto Può riprovare
