### ISSUE TITLE
Elenco province e regioni

### ISSUE THREAD

**Issue by romanoluca** [italia/anpr#612]
Buongiorno.
Sulla "tabella 3 archivio comuni" per ogni comune è specificato un riferimento alla provincia e alla regione di appartenenza (campi IDPROVINCIA e IDREGIONE) ma non sono riuscito a trovare le tabelle di riferimento relative a province e regioni.
La domanda è la seguente: esistono tabelle di questo tipo con la lista delle province e delle regioni? Esistono inoltre tabelle analoghe ad archivio comuni in cui sono presenti informazioni relative a province cessate (data istituzione provincia e data cessazione provincia)? 
Grazie in anticipo.

**Comment by gcarbonin** [comment]
Si fa riferimento alle tabelle ISTAT disponibili a questo link http://www.istat.it/storage/codici-unita-amministrative/Codici-statistici-e-denominazioni-delle-ripartizioni-sovracomunali.zip.
Un archivio storico delle province, a quanto mi risulta, non è pubblicato.
