### ISSUE TITLE
[3003] msg. "Utente non abilitato a questo servizio"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#613]
ambiente di TEST - comune di FAENZA

probabilmente è un problema di configurazione che non sappiamo come modificare.
un determinato utente che riesce ed eseguire consultazione di dati (ws 3002), non riesce invece ad ottenere la lista delle operazione del soggetto (ws 3003)

idOperazioneComune 2018301036 - servizio 3002: va a buon fine
idOperazioneComune 2018301037 - servizio 3003: segnala "XXXX - E - Utente non abilitato a questo servizio"

grazie

**Comment by danielarosa** [comment]
L'utente MLVBBR71R60E971S in test non aveva il permesso di accedere alle funzionalità di utilità necessario per poter eseguire il servizio 3003.

Per modificare/verificare i ruoli degli utenti l'utente ALS può accedere alla console di ANPR (link Sicurezza) e dalla voce di menu Gestione utenze/ Modifica-visualizza modifica i ruoli assegnati. In questo caso specifico deve essere associato il permesso Operatore di utilità.
Saluti
Daniela Rosa

**Comment by AMonopoliADS** [comment]
confermo che adesso l'operazione va a buon fine.
grazie
