### ISSUE TITLE
Re-iscrizione di coniugati

### ISSUE THREAD

**Issue by busaster** [italia/anpr#614]
Ambiente di test.
Il 1/2/2018 sono state iscritte due coniugi per immigrazione da non subentrato.
Il 1/3/2018 sono stati cancellati per altri motivi.
Oggi 26/03/2018 tento di re-iscriverli per immigrazione.
Vengo però bloccato alla prima chiamata 1002 dal messaggio EN413 : Il soggetto risulta cancellato[Coniuge]. Id operazione ANPR 2674890.

Non capisco il senso di questo blocco.

**Comment by frmariani** [comment]
Non deve inserire l’idanpr del coniuge se ancora non è stato riscritto.

Il matrimonio potrà essere inserito direttamente con la re-iscrizione del secondo soggetto.

**Comment by busaster** [comment]
Ok. Questo ci crea una ulteriore complicazione in sviluppo ma nulla di drammatico.
Vorrei però capire la ragione di questo controllo.
Grazie

**Comment by frmariani** [comment]
Quando si iscrivono le persone, l’idanpr non deve essere indicato, viene in automatico recuperato a parità di dati anagrafici

**Comment by busaster** [comment]
Togliendo id anpr al re-iscrivendo ottengo "EN190 : Soggetto XXXXXXXXXXXX  cancellato in ANPR, per riscriverlo indicare idSchedaSoggettoANPR YYYYYY nella richiesta".
Quindi per quali anagrafiche  deve valere la regola di non indicare l'id anpr ?

**Comment by frmariani** [comment]
deve lasciarlo per il re-iscrivendo ma non deve inserirlo per i soggetti collegati non ancora riscritti, come si evince dal primo diagnostico.

**Comment by busaster** [comment]
Ok ora è chiaro. Ho provato la modifica suggerita e funziona.
Grazie
