### ISSUE TITLE
Fornitura file di subentro AIRE - Codifica e caratteri speciali

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#615]
Comune di Parma - Ambiente di Presubentro

Abbiamo richiesto la cancellazione del presubentro di ottobre stiamo procedendo ora al caricamento dei nuovi file di presubentro tuttavia stiamo avendo difficoltà nel caricare il file di subentro AIRE.

EN010 - Il formato del file decompresso non è TXT valido (primo errore trovato : Errore alla riga 62, fine linea errato, quello corretto : \r\n.)

Avremmo bisogno di chiarimenti in merito alla codifica del file TXT: deve essere un file UTF-8, ANSI... ?

Con i caratteri speciali come dobbiamo comportarci? Sono accettati caratteri NON ASCII?

Attendiamo un gentile riscontro.

Grazie

**Comment by RBiasi** [comment]
Nel frattempo abbiamo caricato i file dei residenti attendo per gli aire.

Grazie

**Comment by gcarbonin** [comment]
Il file è quello che si invia da anni per l'aggiornamento dell'AIRE centrale. Deve essere ISO_8859-1. Esiste un pacchetto di controllo dei dati AIRE scaricabile da test-comuni; domani pubblichiamo una versione aggiornata che controlla anche la presenza di caratteri non ammessi

**Comment by RBiasi** [comment]
Lo stesso file su AnagAire caricato su AnagAire non da problemi.

**Comment by RBiasi** [comment]
Il set ISO_8859-1 comprende il ° (tondino) che però sembra creare problemi per SOGEI.
Dove è questo sito “test-comuni” dal quale si può scaricare il pacchetto di controllo?

**Comment by gcarbonin** [comment]
Il SW AnagAire accetta una serie di caratteri che, in fase di formazione di elenco unico elettori (UNICO MOTIVO PER CUI ESISTE L'AIRE), sono considerati non validi e convertiti in spazi: questo non è accettabile in ANPR in quanto i dati trasmessi dal comune non possono essere modificati in automatico. Per tale motivo, ANPR prevede controlli aggiuntivi. Aggiungo anche che alcuni caratteri ISO possono introdurre vulnerabilità nei sistemi e non sono quindi accettabili per motivi di sicurezza.
L'ambiente di test-comuni (strano che non vi sia noto visto che viene utilizzato quotidianamente) si chiama come quello di pre-subentro con "test" al posto di "pre".

**Comment by Raffive** [comment]
se è l'unico motivo perchè ci fanno gestire i movimenti anagrafici dell'Aire? nascite morti matrimoni ecc? potremmo semplicemente iscrivere all'aire solo i nuovi iscritti in elettorale due volte l'anno con la semestrale! tanto lavoro in meno! forse oltre a dover garantire l'esercizio del diritto elettorale ce ne sono altri di diritti?
http://www.esteri.it/MAE/normative/leg27.10.88.pdf 
capisco che il dpcm 194/2014 obbliga la registrazione solo di alcuni dati...ma forse va cambiata questa parte no?
Raffaella 
comune di Spinea subentrato che non capisce perchè  le schede anagrafiche apr e aire debbano essere diverse ovvero perchè quelle dell'aire non debbano contenere maternità paternità e nome di battesimo del coniuge oltre al cognome

**Comment by gcarbonin** [comment]
Sarà nostra cura riportare le sue richieste nelle sedi più opportune

**Comment by Raffive** [comment]
valutate anche il caso di rimpatrio aire in altro comune o in altra aire
