### ISSUE TITLE
Aggiornamento sistemi di test comuni e presubentro

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#617]
Domani 29 marzo, dalle 14 alle 15, i servizi ANPR degli ambienti di test comuni e presubentro non saranno disponibili per aggiornamenti software.
Tali aggiornamenti prevedono l’introduzione di ulteriori controlli sul contenuto di alcuni campi previsti in subentro e nelle strutture dati previste per i servizi.
[Appendice Modifiche Tipi Dati Servizi.zip](https://github.com/italia/anpr/files/1860121/Appendice.Modifiche.Tipi.Dati.Servizi.zip)
[Appendice Tracciato Aire.zip](https://github.com/italia/anpr/files/1860124/Appendice.Tracciato.Aire.zip)
I controlli sono attivi in ambiente di test comuni e pre-subentro: gli xsd non sono stati modificati per consentire i necessari adeguamenti SW. Viene in ogni caso effettuata una verifica via SW sulla base di nuovi xsd 
[wsdl-pack-comuni-dist.zip](https://github.com/italia/anpr/files/1860129/wsdl-pack-comuni-dist.zip)
che restituisce un errore quando il contenuto del campo non rispetta le nuove regole.
Analogamente, sono disponibili i SW aggiornati che consentono di verificare prima dell’invio il contenuto del file di subentro APR e AIRE (alla voce Strumenti di supporto dell’ambiente di Test comuni).
A partire dal 1 luglio, sarà pubblicata in tutti gli ambienti la nuova versione degli XSD; la presenza di campi non formattati correttamente determinerà lo scarto del servizio o dei file per presenza di caratteri invalidi. Contestualmente, la versione dell’applicazione SW che si ricorda è presente nel campo codDestinatario  di testataRichiesta sarà variata in ANPR01.

**Comment by rpapini** [comment]
Abbiamo controllato le restrizioni che avete imposto ad alcuni campi (file zip Appendice Modifiche Tipi Dati Servizi) e chiediamo la modifica del caratteri accettati per il campo "numeroPraticaComune", inserendo anche il valore slash. 
Saluti
Papini Riccardo

**Comment by busaster** [comment]
Controntando gli XSD e l'appendice ho rilevato una serie di anomalie

1. alfanumericoNoslash120char non ha restrizioni (dovrebbe estendere alfanumericoNoSlashbase):
2. alfanumericoSlashbase mi pare un doppione di alfanumericobase
3. sarebbe meglio rinominare le diciture "numberiletterePunto" in "numeriletterePunto"
4. il campo "provinciaContea" di "tipoLocalita" è dichiarato come "alfabeticobase80char" mentre nell'appendice.xlsx è dichiarato accettare "numeri lettere virgola punto trattino apice slash  segni diacritici"
5. il campo "numeroSoggiorno" di "tipoPermessoSoggiorno" dichiarato come numberiletterespazioslash20char (numeri,lettere,spazio.slash) mentre nell'appendice.xlsx è dichiarato accettare "numeri e lettere, slash, trattino".
6. il campo "numeropassaporto" di "tipoPermessoSoggiorno" è "numberilettereMax30" mentre lo stesso campo in "tipoPermessoDiSoggiorno3000" è "numberiletteresenzaspaziMax30"
7. il campo "questuraRilascioSoggiorno" di "tipoPermessoSoggiorno" è "tipoQuesturaRilascio" mentre lo stesso campo in "tipoDatiSoggiorno3000" è "numberilettereMax50"
8. il campo "numeroSoggiorno" di "tipoPermessoSoggiorno" è "numberiletterespazioslash20char" mentre lo stesso campo in "tipoDatiSoggiorno3000" è "numberilettereMax20"
9. il campo "noteStato" di "tipoCittadinanza" e "tipoAltraCittadinanza" è "noteMax240" mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
10. il campo "ufficioMunicipio" di "tipoAtto" è "numberilettereMax80" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
11. il campo "volume" di "tipoAtto" è "numberilettereMax5" che non ammete il punto mentre nell'appendice.xlsx è dichiarato accettare "numeri,lettere, punto, spazio".
12. il campo "numero" di "tipoCartaidentita" ed in "tipoCartaIdentita3000" è "numberilettereMax20" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
13. il campo "noteOperazione" di "tipoDatiOperazione" è "numberilettereMax240" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
14. il campo "indirizzoDigitale" di "tipoDomicilioDigitale" è "tipoEmail" cha ha una regexp che ammette più caratteri rispetto a quanto dichiarato  nell'appendice.xlsx
15. il campo "soggettoAIRE" di "tipoGeneralita" ora è "letterespaziobase", prima era "char1" e valeva "S/N". Conviene piuttosto diventi un "lettere1char" ?
16. il campo "note" di "tipogeneralita" è "noteMax240" che non ammette apice, mentre in appendice.xlsx è dichiarato che il campo ammette "Numeri, lettere, punto, virgola, apice"
17. il campo "noteStatoCivile" di "tipoStatoCivile" è "numberilettereMax240" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
18. il campo "noteChiusura" di "tipoDatiProcedimentoIstruttoria" è "numberilettereMax240" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
19. il campo "noteEsito" di "tipoDatiProcedimentoIstruttoria" è "numberilettereMax240" che ammette lo spazio mentre nell'appendice.xlsx è dichiarato accettare solo "numeri e lettere".
20. il campo "denominazioneToponimoTranslitterato"  è rimasto "charmax100", quindi senza restrizioni al contrario di quato specificato in appendice.xlsx.

**Comment by mttfranci** [comment]
Grazie per le segnalazioni che sono in attualmente in esame.
Stiamo rivedendo la documentazione e pubblicheremo un aggiornamento martedì 3 aprile.

**Comment by mttfranci** [comment]
Ecco l'aggiornamento della documentazione pubblicata la scorsa settimana 
[Aggiornamento 01](https://github.com/italia/anpr/files/1872190/update_01.zip).
Rimaniamo a disposizione.

**Comment by gcarbonin** [comment]
Ci sono altre osservazioni?

**Comment by mttfranci** [comment]
Da venerdì 13 aprile i nuovi XSD saranno applicati anche alla validazione dei file APR di subentro in ambiente di test comuni e presubentro.

**Comment by ncapozzi** [comment]
Si ripubblica il documento 
[Appendice Tracciato Aire.xlsx](https://github.com/italia/anpr/files/2163442/Appendice.Tracciato.Aire.xlsx)
con le seguenti correzioni
CODICE SESSO	TESTO (01).	Valore 1 per 'M', 2 per 'F'
CODICE RELAZIONE PARENTELA	TESTO (02).	Numerico di 2 cifre (es. usare 01 per 1). E' ammesso anche un numerico seguito da spazio ma non un numerico preceduto da spazio. 
Per i valori fare riferimento alla tabella 5 relazioni parentela

**Comment by mttfranci** [comment]
Abbiamo apportato qualche piccola aggiunta ai valori ammessi per alcuni campi.

In allegato [l' Aggiornamento 02](https://github.com/italia/anpr/files/2205107/update_02.zip)
