### ISSUE TITLE
Codice fiscale provvisorio numerico

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#618]
Buongiorno
C'è qualche segnalazione in precedenza, ma non chiarificatrice.
Stiamo parlando dei richiedenti asilo, che ricevono un codice fiscale provvisorio, di tipo numerico. Solo se viene riconosciuto il diritto all'asilo, gli viene assegnato (mesi dopo) un "vero" codice fiscale.
Devo inserirli in anagrafe all'atto della richiesta di residenza, e presentano il codice numerico provvisorio, l'unico in loro possesso.
In ANPR come ci si deve comportare?

Riferimenti per il  numero di codice fiscale provvisorio delle persone fisiche:
[Comunicazione di servizio 8 Agenzia entrate](http://www.a-dif.org/wp-content/uploads/2016/12/circolare-codice-fiscale.pdf) che istruisce al rilascio del codice provvisorio ai richiedenti asilo
[DECRETO DEL PRESIDENTE DELLA REPUBBLICA 29 settembre 1973, n. 605](http://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.del.presidente.della.repubblica:1973-09-29;605) articolo 3, prevede il codice provvisorio
[MINISTERO DELLE FINANZE - DECRETO MINISTERIALE 23 dicembre 1976.](http://www.comune.jesi.an.it/MV/leggi/dm23-12-76.htm) articolo 10, stabilisce la composizione del codice provvisorio

**Comment by gcarbonin** [comment]
Si iscrive con il codice numerico provvisorio

**Comment by MarcoMigliori** [comment]
Ottimo, grazie.
