### ISSUE TITLE
[Estrazione Dati] Duplicati nel file xml "ELENCHI CITTADINI"

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#619]
Buongiorno,
controllando i dati contenuti nel file xml richiesto per l'estrazione dei residenti trovo tre cittadini che compaiono due volte. Esattamente intendo che l'intero nodo "Risposta3002_OK", che contiene tutti i dati, compare due volte con gli stessi dati per questi tre cittadini (IdSchedaSoggettoANPR: 25561992, 25562881, 25563388).
L'ambiente è quello di PRE_SUB di Bistagno (AL), mentre l'elaborazione "ELENCHI CITTADINI" è la n. 1414524 del 05/02/2018  (NOME FILE: 006017_Elenchi_Mon Feb 05 16:06:28 CET 2018 ). 
Premesso che l'importante è che i dati ci siano, vorrei capire se c'è qualche motivo che genera questa duplicazione, oppure se dipende da un errore nell'estrazione. 
In generale, comunque, visto che i dati sono identici si potrebbe fare in modo di non generare questi duplicati nell'estrazione?
Grazie

**Comment by azabatta** [comment]
Buongiorno,
stiamo verificando la sua segnalazione.

**Comment by azabatta** [comment]
Abbiamo riscontrato un errore nella procedura di estrazione. E' in corso una correttiva, la informeremo appena sarà possibile riprovare. Grazie per la segnalazione

**Comment by Eduardo1977** [comment]
Vi ringrazio.

**Comment by azabatta** [comment]
La duplicazione è stata rimossa. E' possibile riprovare, restiamo in attesa di un cortese riscontro.
Buonasera
