### ISSUE TITLE
Web app -  Stato civile non documentato

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#62]
In fase di iscrizione del soggetto ID ANPR 3904453 è stato selezionato lo stato civile "coniugato" scegliendo anche il valore non documentato.
Quest'ultima informazione, però, non viene esposta sulla scheda individuale del soggetto stampabile dalla "Consultazione", rischiando così di indurre in errore l'operatore. Sarebbe utile integrare il dato con accanto l'indicazione "non documentato".
Inoltre, in caso di dati non documentati, le informazioni dovrebbero avere esclusivamente valore interno e  non dovrebbe essere possibile emettere certificazioni. Nel caso del soggetto in esame ho potuto emettere il certificato anagrafico di matrimonio senza alcun blocco nè warning.
Grazie, saluti.
Valentina Bocchino -  Comune di Torino
Data del test: 31/03/2017 - Ambiente di test

**Comment by gcarbonin** [comment]
Aggiungiamo nella stampa il "non documentabile" (nella pagina c'e'. Corretto?).  Riguardo ai certificati, si deve utilizzare la  certificabilita' del soggetto.

**Comment by VBocchinoTO** [comment]
Confermo che il "non documentabile" è correttamente visibile nella pagina, manca solo nella stampa della scheda.
Per quanto riguarda la certiicabilità, ho un dubbio: non esiste un posizione di certificabilità che esclude solo lo stato civile. Se impostassi il valore a "certificabilità parziale" precluderei la stampa, ad esempio, della certificazione storica; otterrei un risultato anche peggiore impostandolo a "non certificabile". Esiste qualche altra possibilità?
Grazie della disponibilità, saluti.
Valentina Bocchino

**Comment by gcarbonin** [comment]
Abbiamo aggiunto lo stato civile nella stampa. Puo' riprovare. 
Riguardo al blocco della certificazione l'unica soluzione che vedo è bloccare il certificato di stato civile (piu' i "collegati" matrimonio e unione civile) quando lo stato civile è "non documentato".
Non è una decisione che puo' prendere Sogei in autonomia. Sarebbe utile conoscere come si regola qualche altro comune che legge queste domande.

**Comment by VBocchinoTO** [comment]
Ho riprovato la stampa e compare correttamente l'informazione.Grazie.

**Comment by VBocchinoTO** [comment]
Abbiamo chiesto ad alcuni Comuni come si comportano nella fattispecie, ponendo anche la domanda nel corso di un pomeriggio di studi ANUSCA tenutosi la scorsa settimana, verificando che anche altri Comuni hanno previsto il blocco della certificazione di stato civile e dei collegati matrimonio/unione civile nel caso di "stato civile non documentato". Di conseguenza, riteniamo che la nostra interpretazione sia corretta.
