### ISSUE TITLE
[datiSoggetto] Cittadinanza xml con molteplicità >1 

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#621]
Se ad esempio un cittadino italiano ha anche una seconda cittadinanza (francese), non mi è chiaro come dovrebbe apparire nell'xml. Sono due nodi distinti? Grazie

&lt;datiSoggetto&gt; 
. . . 
&lt;cittadinanza&gt;
&lt;descrizioneStato&gt;ITALIA&lt;/descrizioneStato&gt;
&lt;codiceStato&gt;100&lt;/codiceStato&gt;
&lt;/cittadinanza&gt;

&lt;cittadinanza&gt;
&lt;descrizioneStato&gt;FRANCIA&lt;/descrizioneStato&gt;
&lt;codiceStato&gt;215&lt;/codiceStato&gt;
&lt;/cittadinanza&gt;
. . .
&lt;/datiSoggetto&gt;

**Comment by azabatta** [comment]
Buongiorno, 
sì sono nodi distinti, nella risposta di una consultazione l’element “cittadinanza” è definito come maxOccurs="unbounded" per cui si ripete tante volte quante sono le cittadinanze presenti sul DB per quel cittadino.

**Comment by Eduardo1977** [comment]
Buongiorno e grazie
