### ISSUE TITLE
codice belfiore UZBEKISTAN

### ISSUE THREAD

**Issue by sfabrizi** [italia/anpr#622]
mi trovo nella necessità di iscrivere una straniera nata in UZBEKISTAN, il problema è questo in INA e ANPR il codice Belfiore è Z259 mentre  per agenzia delle entrate il codice validato è con Z143.
chiedo come poter risolvere questo conflitto.

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by gcarbonin** [comment]
Il codice catastale corretto è Z259; purtroppo sono stati attribuiti in passato codici fiscali con l'altro codice catastale. Stiamo analizzando come gestire questa situazione in ANPR. Facciamo sapere quanto prima

**Comment by rvinzani** [comment]
I soggetti che presentano questa situazione possono essere gestiti nelle iscrizioni indicando 998 - non attribuibile nel codice stato ed il nome esteso nella denominazione. In tal modo i soggetti risultano correttamente validati. E' importante verificare che questa soluzione deve essere sempre utilizzata anche in caso di variazione dei dati anagrafici poiché, se venisse indicato il codice attualizzato verrebbe riassegnato un nuovo codice fiscale

**Comment by bfilipazzi** [comment]
Non sono sicuro di avere capito bene, significa che il gestionale deve disporre di due voci per l'UZBEKISTAN di cui una con COD=357 e l'altra con COD=998 ?
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Stiamo cercando una soluzione di emergenza per gestire questa situazione (e altre simili) nella quale abbiamo un codice fiscale validato ma attribuito dall'Agenzia delle Entrate utilizzando un codice catastale non più valido e contemporaneamente evitare che venga riattribuito il codice fiscale. La più veloce che abbiamo individuato è questa: utilizzare come codice stato 998 quando il codice catastale del codice fiscale è quello errato (1 in seconda posizione). Stiamo lavorando su una soluzione "migliore" di questa ma ci occorre più tempo.

**Comment by bfilipazzi** [comment]
Ho capito, grazie.
Filipazzi - Maggioli
