### ISSUE TITLE
Web App - Istituzione convivenza di fatto

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#623]
Buongiorno,
sto testando l'istituzione di convivenza di fatto tra i due soggetti id ANPR 38204784 e 37871109 (ambiente pre-subentro).
I due soggetti risultano già nello stesso nucleo familiare con rapporto parentela "conviventi".
Eseguendo la Registrazione della convivenza (data costituzione, data stipula, data notifica tutte valorizzate a 3/4/2018, per escludere i possibili errori di incoerenza date), mi restituisce i seguenti errori:
- La richiesta non risulta valida secondo i nuovi XSD [Campo:'valore'] (Codice: EN489)
- La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)
Ho provato a cercare nella documentazione, ma non riesco a trovare a cosa si riferiscono.
Specifico che questi errori si presentano soltanto valorizzando anche gli attributi propri del contratto. Sono riuscita ad ottenere esito ok su un'altra costituzione di convivenza di fatto senza registrare il relativo contratto (operazione n. 1593225).

Colgo l'occasione per fare anche un'altra domanda: il certificato di contratto di convivenza appare soltanto a seguito della relativa mutazione su Web App? Al momento, non compare tra i certificati selezionabili nella sezione "Scelta certificato" del servizio CERTIFICAZIONE su ambiente di pre-subentro. 

Grazie, cordiali saluti.
Valentina Bocchino
Città di Torino

**Comment by asqueglia** [comment]
Buongiorno, 
a seguito dell'analisi della sua segnalazione è stata apportata una correttiva alla validazione XSD e alla configurazione relativa alla certificazione Web. 
E' ora possibile riprovare. 
A breve verrà comunque aggiornata la documentazione circa il controllo EN489; il controllo EN489 è stato introdotto nell'ambito dell'aggiornamento di cui è stato dato avviso con l'issue #617. 
Grazie

**Comment by VBocchinoTO** [comment]
Ho ritestato ed effettivamente ora la registrazione va a buon fine. 
E' apparso anche il certificato di contratto di convivenza tra i selezionabili.
Grazie

**Comment by AnnaUrban** [comment]
Comune di Serravalle Sesia - ambiente di produzione.
Ho istituito due giorni fa la prima convivenza di fatto tra due soggetti già iscritti nella medesima famiglia anagrafica come conviventi (id.: 18678230 e 18676701) a seguito di dichiarazione resa in Comune. La variazione è stata regolarmente registrata e, apparentemente, sembra completa nel senso che, verificando i dati presenti, non risulta alcuna anomalia. Tuttavia nel momento in cui richiedo la certificazione, si genera l'errore bloccante EN354 (il certificato non può essere emesso perché i dati del contratto di convivenza risultano assenti o incompleti). L'unico elemento dubbio è legato alla voce 'file del contratto': è necessario caricare il file di richiesta di costituzione della convivenza di fatto? In tal caso che procedura devo seguire? Grazie

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Web App - Istituzione convivenza di fatto (#623)" inviata il 12/07/2018
16:16:50.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
