### ISSUE TITLE
Certificato di stato civile

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#624]
Buongiorno,
in caso di soggetto vedovo (es. ID ANPR 42046089, ambiente pre-subentro), il certificato di stato civile non riporta il luogo di decesso del coniuge, sostituendolo con la parola "assente", nonostante in Consultazione sia valorizzato.
Grazie, saluti.

Valentina Bocchino
Città di Torino

**Comment by mttfranci** [comment]
Dovremmo aver corretto il problema. E' possibile riprovare.

**Comment by VBocchinoTO** [comment]
Grazie, ho riverificato e ora valorizza correttamente il dato.
Buona giornata,

Valentina Bocchino
