### ISSUE TITLE
[6001] Internal Error (from server)

### ISSUE THREAD

**Issue by busaster** [italia/anpr#626]
Ambiente di test - Poggio a Caiano
ma problema simile anche in ambiente di produzione (Perugia).

Effettuo una chiamata al servizio 6001 richiedendo un certificato di tipo 9 con tipoRichiesta 2 per il soggetto ID ANPR 9451749 (che è un AIRE).

Il servizio va in errore con un "Internal error (from server)".

Come mai ? Forse perché il soggetto è AIRE ?

**Comment by mttfranci** [comment]
Stiamo indagando il problema.

Pensiamo di aver individuato la vostra richiesta, potete confermarci che si tratta di quella identificata da :
        <idOperazioneComune>1014780</idOperazioneComune>
<codMittente>100004</codMittente>

**Comment by mttfranci** [comment]
Grazie della collaborazione.
Come avete intuito, il problema era dovuto al fatto che il soggetto è iscritto all'AIRE.
Se volete riprovare, il servizio dovrebbe rispondere ora con il diagnostico EN044 esattamente come per il tipo richiesta 1.
Rimaniamo a disposizione.

**Comment by busaster** [comment]
Confermo, ora viene restituito il messaggio di errore.
Grazie
