### ISSUE TITLE
[6001] certificato richiesto da enti

### ISSUE THREAD

**Issue by busaster** [italia/anpr#627]
Ambiente di test - Livigno
Tentiamo di produrre un certificato con tipoRichiedente 3.
Come specificato nel documento "6001-RichiestaCertificati.xlsx" non impostiamo il richiedente, che è obbligatorio solo per tipoRichiedente=1
Veniamo bloccati però dall'errore "EN391 : Se tipoRichiedente = 3 e' obbligatorio esplicitare, nelle generalita' del richiedente, il documento di riconoscimento".

C'è un controllo di troppo o c'è un errore nella documentazione ?

Grazie

**Comment by gcarbonin** [comment]
pag 148 delle specifiche

17.1.5.6	Certificati richiesti da Enti
Occorre specificare il valore 3 nel campo TipoRichiedente e nei campi riservati al documento di riconoscimento:
	nel campo che normalmente contiene il documento, il nome dell’ente e gli estremi della richiesta;
	nel campo che normalmente contiene la data di rilascio, la data della richiesta.
Devono comunque essere compilate le generalità della persona che richiede il certificato per conto dell’Ente.

**Comment by busaster** [comment]
Benissimo grazie.
Potete allineare la documentazione XLSX (anche con un rimando al paragrafo che lei ha citato) ?

**Comment by AMonopoliADS** [comment]
salve.

mi intrometto nella discussione per evidenziare che con gli ultimi controlli inseriti in ambiente di test e pre-subentro, è stata inserita la restrizione che il campo estDocRiconoscimento può contenenere solo "numeri e lettere punto".
una richiesta con tipoRichiedente '3' e estDocRiconoscimento corrispondente a ente / estremi richiesta, ritorna con i seguenti errori:
`<listaErrori>
  <errore>
    <codiceErroreAnomalia>EN489</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La richiesta non risulta valida secondo i nuovi XSD [Campo:'estDocRiconoscimento']</testoErroreAnomalia>
  </errore>
  <errore>
    <codiceErroreAnomalia>EN489</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1]</testoErroreAnomalia>
  </errore>
  </listaErrori>`

forse abbiamo frainteso le indicazioni da seguire in questo caso?

grazie
(rif. ambiente di TEST - comune di FAENZA - idOperazioneComune 2018600172)

**Comment by gcarbonin** [comment]
basta utilizzare per indicare l'ente solo numeri lettere e punto; ad esempio richiesta di "XX" con protocollo 33/2018 può  essere indicata come XX 33 2018.

**Comment by AMonopoliADS** [comment]
ok. così ha funzionato.
quindi consideriamo che la limitazione sia "numeri lettere punto e spazio"? oppure lo spazio e da considerarsi utilizzabile in generale?
grazie

**Comment by gcarbonin** [comment]
In questo caso si. Lo spazio viene accettato sempre (salvo qualche caso in cui è non ammesso ad esempio nei campi numerici) Vedremo di precisarlo meglio
