### ISSUE TITLE
[3003] Scarico notifiche da elaborare (stato lavorazione=7)

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#628]
Buongiorno,
siamo in ambiente di TEST, stiamo eseguendo una richiesta per ottenere l'elenco delle notifiche da elaborare.
Sappiamo che il giorno 23/3/18 sono presenti 4 notifiche N010, mentre nei giorni seguenti nessuna.
Facendo una chiamata (id operazione ANPR = 4644698) con periodo dal 23/3/18 ad oggi otteniamo, come ci aspettiamo, le 4 notifiche.
Mentre se facciamo la chiamata (id operazione ANPR = 4644600) con periodo dal 24/3/18 ad oggi, ci aspettiamo di non ottenere nulla, otteniamo il seguente testoErroreAnomalia: "La richiesta  ha individuato un numero di occorrenze troppo elevato: restringere i parametri della ricerca".

Non capiamo come sia possibile che un periodo di tempo di 13 giorni dia un numero di occorrenze troppo elevato, mentre un periodo di 14 giorni dia un risultato di 4 notifiche.
Crediamo possa essere semplicemente sbagliato il messaggio, secondo noi nel periodo di 13 giorni non ci dovrebbero essere notifiche.

Potete verificare? 
Grazie

**Comment by mttfranci** [comment]
Salve.
Dovremmo aver trovato e risolto l'anomalia. E' possibile riprovare. Per il periodo in cui non sono presenti notifiche, ora il servizio dovrebbe restituire il diagnostico seguente, : 

               <errore>
                  <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
                  <tipoErroreAnomalia>E</tipoErroreAnomalia>
                  <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
               </errore>

Rimaniamo a disposizione.

**Comment by SAlberto** [comment]
Perfetto, abbiamo riprovato e ora l'errore restituito è questo: "La richiesta effettuata non produce alcun risultato".

Grazie molte.
