### ISSUE TITLE
[5008] web service - rettifica data di matrimonio

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#63]
salve.

si sta tentando di modificare la data di matrimonio di un soggetto di stato civile "coniugato".
nella fattispecie si tratta di una variazione perchè il dato era errato.

inzialmente abbiamo provato indicando come tipoMutazione il codice '12' (matrimonio), ma il web-service ritorna l'errore:
EN243 - E - La data del matrimonio e' incoerente

tra i vari tentativi abbiamo anche provato ad indicare come tipoMutazione il nuovo codice '20' (completamento dati), ma l'errore è sempre lo stesso.
(rif. idOperazioneComune 2017000346 - ambiente dptest - comune di Faenza)

non si capisce il senso del messaggio e, soprattutto, come poter perfezionare la variazione?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Deve mettere un identificativo operazione in modo che possiamo verificare se l'errore è nella richiesta o nel nostro SW.

**Comment by AMonopoliADS** [comment]
il riferimento è presente nella richiesta, comunque lo riporto:
(rif. idOperazioneComune 2017000346 - ambiente dptest - comune di Faenza)

**Comment by gcarbonin** [comment]
scusi non l'avevo vista..

**Comment by gcarbonin** [comment]
Per identificare un soggetto in ANPR, come da specifiche, occorre indicare nella richiesta Codice fiscale e cognome e nome oppure Identificativo ANPR e Cognome e Nome.
Nella richiesta (abbiamo visto l'ultima) non è presente né il CF né l'IDANPR; in questo modo la ricerca non va a buon fine e da questo deriva l'incongruenza sulla data, in quanto ANPR interpreta la mutazione come se il comune tentasse di inserire un nuovo matrimonio (con un soggetto che non è in ANPR) di una persona sposata.

**Comment by AMonopoliADS** [comment]
non mi ritrovo in quello che mi ha scritto. 
ho il dubbio che abbiate guardato un'altra comunicazione.

ho tentato la ripetizione della comunicazione che Le avevo indicato, assegnandole un nuovo idOperazioneComune (che in questo caso è 2017000350)
in questa comunicazione sono presenti:
- codice fiscale e idANPR (del soggetto da modificare)
- idANPR del coniuge

**Comment by gcarbonin** [comment]
Nel coniuge c'è cognome nome e identificativo del comune.

**Comment by AMonopoliADS** [comment]
ok. chiarito. grazie
