### ISSUE TITLE
convenzioni per visualizzazioni anagrafiche

### ISSUE THREAD

**Issue by lialosi** [italia/anpr#632]
Buongiorno dal Comune di Luzzara. Il ns. comune è subentrato in ANPR il 19/1/2018. Dai vari corsi a cui ho partecipato è stato detto che gli enti esterni (carabinieri, Usl, Agenzia Entrate, ecc) avrebbero potuto visualizzare i dati anagrafici a seguito di convenzioni stipulate da Ministero dell'Interno con i Ministeri di Competenza degli altri Enti. Sono già state fatte queste convenzioni? Come si collegano ad esempio i Carabinieri in ANPR?
La seconda domanda riguarda invece le convenzioni locali.. il ns. comune appartiene all'Unione dei Comuni della Bassa Reggiana . La Polizia Municipale (corpo dell'Unione Bassa Reggiana) ci ha chiesto di poter accedere all'ANPR..A parte sottoscrivere una convenzione come dobbiamo fare per dar loro l'accesso? Richiediamo dalla WEB APP una smart card e poi accedono dalla WEB APP..per ora noi siamo l'unico comune dell'Unione subentrato.. è chiaro che dovrei richiedere la smart card per la Polizia Municipale come se fosse del Comune di Luzzara e non dell'Unione... Grazie per le indicazioni che vorrete fornire in merito. Buona giornata

**Comment by gcarbonin** [comment]
Al momento Agenzia delle Entrate Motorizzazione INPS e ISTAT. 
Le convenzioni locali dovrebbero interrogare i dati locali o interrogare ANPR tramite il vostro SW anagrafico, per cui le abilitazione che rilasciavate in passato vanno bene anche oggi, La soluzione prospettata non va bene.
