### ISSUE TITLE
RITORNO DEI DATI SU APPLICATIVO MAGGIOLI

### ISSUE THREAD

**Issue by lialosi** [italia/anpr#633]
Buongiorno dal Comune di Luzzara. Capita di sistemare delle posizioni anagrafiche direttamente con il supporto di Sogei direttamente dalla WEB APP. Noi utilizziamo applicativo Maggioli. Come è previsto il ritorno dei dati modificati direttamente in  ANPR sull'applicativo in modo che i colleghi di servizi sociali, tributi, ecc vedano i dati rettificati?

**Comment by gcarbonin** [comment]
Interrogando le risposte di ANPR relative alle operazioni effettuate via WEB o acquisendo le notifiche di queste operazioni
