### ISSUE TITLE
[5005] Rimpatrio da AIRE - Errore EF002

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#635]
soggetto unico componente di famiglia AIRE (idSoggettoANPR 19027447), rimpatria e si aggrega a famiglia già presente in ANPR (idFamigliaANPR 9137655).

il web-service (5005) va in errore con il messaggio
```
<listaErrori>
  <errore>
    <codiceErroreAnomalia>EF002</codiceErroreAnomalia>
    <tipoErroreAnomalia>E</tipoErroreAnomalia>
    <testoErroreAnomalia>Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata</testoErroreAnomalia>
  </errore>
</listaErrori>
```

abbiamo letto della necessità di impostare il tipoScheda a '5', ma nell'ambito del servizio 5001.
in questo caso c'è aggregazione a famiglia residente, non ci sembra ci siano le condizioni di impostare il tipoScheda a '5'

in ogni caso abbiamo tentato sia l'uso del tipoScheda '3' che '5', ma con il medesimo risultato

c'è qualcosa che ci sfugge sul motivo dell'errore.
grazie

Alessandro Monopoli ADS

rif. ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA Bologna
idOperazioneComune 2018005590 (per tipoScheda '3')
idOperazioneComune 2018005728 (per tipoScheda '5')

**Comment by frmariani** [comment]
nell'operazione 2018005590, avete inserito l'identificativo di una famiglia AIRE, 9125722 con l'attributo tipo scheda 3 (ANPR), mentre nell'operazione 2018005728 avete inserito l'identificativo di una famiglia ANPR, 9137655 con l'attributo tipo scheda 5 (AIRE).
Nell'oggetto scheda famiglia, dovreste inserire come identificativo famiglia 9137655 con attributo tipo scheda 3.

**Comment by AMonopoliADS** [comment]
ok. grazie.
evidentemente i troppi tentativi di invio avevano creato confusione.
ripetuto l'invio la comunicazione è stata accettata.
grazie
