### ISSUE TITLE
[web-service] Annullamento Operazioni

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#637]
ambiente di PRODUZIONE - comune di SAN LAZZARO DI SAVENA

tre soggetti:
idSchedaANPR | 20049225
idSchedaANPR | 20049226
idSchedaANPR | 20049227

iscritti in aggregazione a famiglia già presente (idSchedaANPR 9138378)
è stata fatta un po' di confusione e siamo nella necessità di annullare tutte le operazioni che li riguardano.

x il soggetto con idSchedaANPR 20049226 siamo riusciti ad annullare tutte le operazioni

x gli altri due soggetti non riusciamo a completare l'annullamento a causa di  messaggi di questo tipo:
EN077 - E - L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa

interrogando, con servizio 3003, le operazioni di entrambi i soggetti, individuiamo l'ordine delle operazioni registrate, ma non si riescono ad annullare (annullamenti eseguiti tramite web-app non ci facilitano il lavoro)

tentiamo di annullare, ad esempio, le seguenti operazioni:
idOperzioneComune 2018003650
idOperzioneComune 2018003621
idOperzioneComune 2018003551
è possibile sapere da voi quale operazione blocca l'annullamento?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
i due soggetti anpr 20049225 e 20049227, hanno alcuni dati comuni in quanto coniugi, pertanto le operazioni devono essere annullate con criterio decrescente; la prima operazione da annullare è la 2669490 e successivamente la 2275267.
Tra i vostri tentativi non sono riuscita a trovare l'annullamento della prima operazione, vi chiedo pertanto di riprovare.   Grazie.

**Comment by AMonopoliADS** [comment]
interrogando la lista delle operazioni di entrambi i soggetti (ws 3003) non trovo alcuna operazione con idANPR 2669490.
riesce a dirmi a quale idOperazioneComune dovrebbe corrispondere e a quale dei due soggetti?
grazie

**Comment by AMonopoliADS** [comment]
ok. abbiamo visto.

ci mancava l'informazione aggiuntiva che l'id 2669490 corrisponde ad una mutazione eseguita da web-app, ed il gestionale non la visualizzava causa la mancanza dell'idOperazioneComune.
proviamo a fare annullare dalla web-app per poi procedere con i successivi annullamenti

grazie.
