### ISSUE TITLE
Matrimonio cittadino AIRE non presente in A.T.

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#638]
Non riusciamo a registrare il matrimonio di un cittadino AIRE perché non presente in anagrafe tributaria.
Questo è l'errore: 
ERRORE DA ANPR: 
EAV91 - Soggetto non presente in Agenzia Entrate.
Qual è la procedura per il suo inserimento?

**Comment by gcarbonin** [comment]
puo' indicarci l'operazione?

**Comment by Finalmentesubentrati** [comment]
Ho effettuato con successo l'evento direttamente dalla web app. Probabilmente era un errore generato dal nostro software.
Grazie.
