### ISSUE TITLE
ws [5008] - Mutazione dati generali con variazione del codice fiscale

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#639]
Buon giorno,
stiamo effettuando in ambiente di test una prova di mutazione del cognome di un individuo, in modo che questo comporti l'assegnazione di un nuovo codice fiscale.
Abbiamo trovato nella issue #391 (attualmente contrassegnata dal label _Enhancement_) un riferimento ad un caso simile al nostro e in accordo alle indicazioni operative riportate, abbiamo proceduto nello stesso modo per quello che riguarda la composizione della request, ossia:

- "vecchio" codice fiscale valorizzato nel blocco '_generalitaPerRicerca_'
- campo _codiceFiscale_ non valorizzato e nuovo cognome indicato nel blocco '_generalitaDaModificare_'
- campo _gestioneCF_ impostato a '0' all'interno del blocco '_datiControllo_'

Prima di procedere col test ci siamo accertati della presenza del "vecchio" codice fiscale nell'ambiente di test AT (la "Consultazione AE" da web application del codice fiscale ha riportato l'esito
'_codice fiscale presente in AT  (marcato ANPR)_' )

Abbiamo quindi tentato di effettuare la mutazione (id operazione comune 4439) ed abbiamo avuto come esito l'errore '999' - 'Operazione non effettuabile'. 
La particolarità però è che ripetendo successivamente la "consultazione AE" da web application del "vecchio" Codice fiscale, otteniamo in risposta l'esito '_Codice fiscale presente in AT come collegato_' e nella pagina mostrata ci sono i dati dell'individuo col nuovo cognome e il "nuovo" Codice fiscale.
Effettuando invece la "consultazione AE" per il "nuovo" codice fiscale, otteniamo l'esito '_Codice fiscale presente in AT (marcato ANPR)_' con i nuovi dati dell'individuo, e con il "vecchio" codice fiscale alla voce '_codici fiscali collegati_'.
La consultazione della scheda individuale con il "nuovo" codice fiscale non porta però alcun risultato.

Abbiamo anche ripetuto, a questo punto, il tentativo di effettuare la mutazione (id operazione comune 4444) ma questa volta abbiamo ottenuto come esito l'errore 'EAM12'
'Soggetto non individuato in AT -  Codice fiscale NON variato', probabilmente a causa della situazione che si è creata a seguito della precedente operazione.

L'unico modo per completare la mutazione è impostare il valore "3" nel campo  _gestioneCF_ . 

Chiediamo innanzitutto conferma della correttezza della modalità operativa seguita per effettuare la mutazione in oggetto; nel caso che il problema (che avevate riferito essere in fase analisi con AE) sia stato già risolto, chiediamo invece indicazioni sulle corrette operazioni da eseguire per completare la request.

Il test è stato effettuato in data 12/04/2018, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by mttfranci** [comment]
Stiamo verificando la vostra segnalazione.

**Comment by mttfranci** [comment]
Una anomalia del software ha causato l’errore che ‘999’ che avete ottenuto per la prima operazione
Il successivo errore ne è una diretta conseguenza.
Abbiamo effettuato una correzione e se riprovate una operazione analoga da capo non dovreste avere altri problemi.
Se avete bisogno di sanare lo specifico caso creato in test comuni possiamo pensarci noi.

**Comment by Amucciarelli74** [comment]
Ok,
abbiamo riprovato una operazione analoga di mutazione generalità con assegnazione di un nuovo codice fiscale, in questo caso modificando il nome dell'individuo (id operazione comune 4483) e l'operazione è andata a buon fine, così come le successive consultazioni "AE" e della scheda individuale.
Non è necessario sanare il caso di test segnalato nella issue, se abbiamo necessità ripeteremo i test con altri individui.
Confermate quindi che la valorizzazione dei campi adottata nella request in oggetto è corretta, sia per l'ambiente di test che per quello ufficiale?
Grazie.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
Si è corretta

**Comment by mttfranci** [comment]
L’esito esatto restituito dal servizio dovrebbe essere stato : 
 
          <errore>
            <codiceErroreAnomalia>AEE95</codiceErroreAnomalia>
            <tipoErroreAnomalia>E</tipoErroreAnomalia>
            <testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>
          </errore>
 
Gli esiti AEE95 sono errori di colloquio con Agenzia entrate che a volte, come in questo caso , possono dipendere da problemi temporanei.

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo riprovato e l'operazione è andata a buon fine, così come la successiva consultazione "AE" con il "nuovo" codice fiscale, e la consultazione della scheda individuale che riporta le nuove generalità.
Grazie.
Giuseppe Mucciarelli, TINN srl
