### ISSUE TITLE
Subentro: Errore ES128 La data di ultimo aggiornamento APR non risulta valorizzata

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#64]
Salve,
in ambiente di TEST per il Comune di Bologna,
nella fase di subentro del file APR tramite UPLOAD, ci troviamo per la prima volta nel resoconto delle anomalie questo errore:Errore ES128  La data di ultimo aggiornamento APR non risulta valorizzata. Questo errore non lo troviamo nell' elenco degli errori ANPR.
 Inoltre, la data di ultimo aggiornamento APR, nelle specifiche del 29/03/2017, risulta non obbligatoria.
Tale data e' diventata  invece obbligatoria?
Questo errore e' bloccante? 
Nel resoconto delle anomalie abbiamo solo  questo errore su tutti i soggetti APR
Data del TEST 31/03/2017

Grazie
Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna
3351234683

**Comment by gcarbonin** [comment]
Dobbiamo aggiornare la lista degli errori. Questa segnalazione è un'anomalia; indica semplicemente che il comune non ha trasmesso la data di ultimo aggiornamento della scheda. In questo caso la data in ANPR sara' pari alla data del subentro. Gli effetti sono sulle successive operazioni: poniamo il caso di persona iscritta il 10-3-2017 con subentro del comune 12-3-2017. Il comune ricevera' l'APR4 successivamente al subentro; la mutazione "di completamento" dovrebbe decorrere dal 10-3-2017. ANPR non l'accettera' in questa data ma richiedera' una data di decorrenza non antecedente al 12-3-2017.
Se l'anomalia è presente su tutte le schede conferite, significa che questa data non e' mai stata indicata.
