### ISSUE TITLE
Rimpatrio AIRE

### ISSUE THREAD

**Issue by Elenalomazzi** [italia/anpr#641]
Buongiorno,
Comune di Biassono - già in ANPR. Ultimamente abbiamo problemi con gli AIRE.
1) L'individuo 18927265 era iscritto AIRE nel nostro Comune, e ora rimpatria al medesimo indirizzo precedente all'espatrio, sempre nel nostro Comune.
2) si sta cercando di iscrivere per nascita nella famiglia AIRE della madre una minore il cui atto è pervenuto dal Consolato.
In entrambi i casi viene rimandato il seguente errore :
"ERRORE DA ANPR: 
EF002 - Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata".
Dobbiamo modificare qualche impostazione?
Grazie.

**Comment by frmariani** [comment]
nel servizio 5001 riferito al primo caso, nell'oggetto famigliaconvivenza, è stato inserito il tipo scheda=3 anzichè 5; 
in merito al secondo caso, non avete inviato nessun riferimento, ma da quello che ho potuto verificare, credo che abbiate inserito una famiglia chiusa(idanpr 9080380); l'attuale famiglia della madre è  idanpr 10340264

**Comment by Elenalomazzi** [comment]
Sto lavorando in webservice, presumo che per la prima problematica debba contattare la software house.
Per la minore, ho controllato il codice famiglia ANPR, che è effettivamente il 10340264. Tra l'altro, poichè richiamo la madre dal programma, dovrebbe riportarmi i dati corretti. Ho verificato, ma comunque rimanda lo stesso errore anche con la famiglia ANPR corretta.

**Comment by frmariani** [comment]
Nell'operazione che avete ripetuto questa mattina alle 8:46, avete inserito ancora la famiglia errata
