### ISSUE TITLE
[6001] Servizi al cittadino - Certificazione On-Line

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#642]
buongiorno

si segnalano due criticità nell'ambito della certificazione richiesta tramite portale comunale, per le quali, possibilmente, si richiede un riscontro urgente.

1. l'amminsitrazione comunale, per incentivare l'utilizzo del canale telematico per il rilascio di certificazione, NON addebita diritti di segreteria sulla certificazione on-line.
questa scelta pone problemi nella richiesta di certificati in carta libera nei casi di  modalità NON esente da diritti.
la richiesta via web-service va in errore perchè, essendo la modalità non esente, il sistema si aspetta la valorizzazione dei diritti da addebitare.

2. analoga problematica si pone nelle emissioni in carta resa legale.
anche in questi casi non vi è addebito di diritti di segreteria
c'è però un problema aggiuntivo: per il bollo ci si aspetta che il richiedente (o il destinatario) renda valido il certificato apponendo la marca da bollo dopo l'emissione.
per rendere esplicita questa esigenza, nell'attuale sistema di emissione, nel caso di carta resa legale viene aggiunta una specifica dicitura di questo tenore 
"IL CERTIFICATO HA VALORE LEGALE SE MUNITO DI MARCA DA BOLLO"

si precisa che, nell'ambito della richiesta di certificazione on-line, il campo "emissione" viene valorizzato a '2', per distinguere la tipologia dell'emissione dalle richieste eseguite da sportello...

attendiamo vostro gentile riscontro.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Pag 146 delle specifiche

17.1.5.2	Esenzione dei diritti di segreteria
Per i comuni che non richiedono il pagamento dei diritti di segreteria, occorre configurare un parametro utilizzando la Web Application (Home > Amministrazione > Gestione dati del comune); ciò consente di indicare un importo pari a zero dei diritti di segreteria, anche per i certificati in bollo.
Nel caso in cui il comune abbia una gestione “mista” (diritti di segreteria riscossi allo sportello e eliminati nel caso di certificati on-line), occorre :
a.	Accedere alla WA e selezionare la funzione Amministrazione, disponibile in alto a destra sulla HOME PAGE. Nella funzione Gestione Dati del Comune, nei Parametri utilizzati per l'emissione dei certificati, si seleziona Certificati esenti da diritti di segreteria
b.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso allo sportello, è sufficiente indicare nella richiesta l’importo del diritto di segreteria (se questo importo viene riscosso allo sportello);
c.	Quando il comune richiede il certificato ad ANPR e si tratta di un certificato emesso on-line dal portale del comune, nella richiesta non si indica alcun importo per i diritti di segreteria.

**Comment by gcarbonin** [comment]
Per il punto 2 ci sono le righe di annotazione  per aggiungere le diciture

**Comment by AMonopoliADS** [comment]
grazie del riscontro.

abbiamo attivato il check come suggerito e sembrano superati i blocchi inizialmente segnalati.
per il punto '2' abbiamo tentato il passaggio delle annotazioni.

attendiamo il parere del cliente 

grazie.

**Comment by AMonopoliADS** [comment]
anche il cliente comunica che entrambe le soluzioni assecondano le sue esigenze.
grazie.
