### ISSUE TITLE
Codice Belfiore NOK

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#644]
Buongiorno
sulla Tabella Comuni, abbiamo rilevato che al comune di Frignano nel periodo tra 12.4.1929 e 31.8.1945 (provincia di Napoli) e nel periodo tra 1.9.1945 e 8.11.1946 (provincia di Caserta) non risulta associato alcun codice Belfiore. Il Comune si è ricostituito l'1.3.1952 con codice Belfiore D799.
Per Frignano Maggiore e Frignano Piccolo (uniti e separati con stesse vicissitudini) il codice Belfiore è correttamente riportato per tutte le occorrenze.
Stefania e Annamaria A

**Comment by romanoluca** [comment]
Mi unisco alla segnalazione poiché potrebbe essere un altro caso che si aggiunge a quanto indicato in #630
