### ISSUE TITLE
Funzionalità Dashboard del Subentro dei Comuni in ANPR

### ISSUE THREAD

**Issue by ATropeano** [italia/anpr#645]
Sarebbe molto comodo dalla dashboard del Subentro dei Comuni in ANPR 

https://dashboard.anpr.it/subentro

avere anche il dato riguardante le smart card nel file csv dei comuni scaricabile:
**Data Consegna SC (Prefettura)**
**Data Ritiro SC (Comune)**

in modo da poter verificare massivamente la situazione delle smart card dei propri comuni.

Inoltre segnalo che la funzionalità di Upload del file csv da errore, almeno fino a qualche giorno fa...

Alessio Tropeano
Datagraph srl

**Comment by mccalv** [comment]
Caro @ATropeano grazie per la segnalazione. Relativamente ai capi che richiedi nell'export sicuramente verranno inseriti e nell'occasione rivediamo i controlli nell'upload del CSV che penso determino gli errori. Un caro saluto

**Comment by mccalv** [comment]
Salve @ATropeano abbiamo rilasciato una nuova versione della dashboard con il fix per il CSV e la possibilità di scaricare il CSV dettagliato (come in figura).
![screen shot 2018-04-27 at 17 52 04](https://user-images.githubusercontent.com/1814818/39372087-c069627e-4a43-11e8-9783-33cf52187150.png)
Nella pagina di processo sarà possibile monitorare sulla icona di warning le cause tra IP non settato, prefettura non abilitata e mancata consegna o ritiro delle SC.
Aspettiamo le vostre verifiche per chiudere il BUG

**Comment by COlivatoADS** [comment]
Buongiorno Mirko,  non ci risulta presente la voce relativa a IP non settato che effettivamente tornerebbe utile nel processo di pianificazione.
Un saluto
Christian O. ADS

**Comment by mccalv** [comment]
Salve @COlivatoADS la aggiungiamo nella prossima release (presumibilmente questa settimana). Nel frattempo fanno notare che il dato é disponibile nella pagina progressi se vi é un alert per il relativo comune
![screen shot 2018-05-02 at 12 40 04](https://user-images.githubusercontent.com/1814818/39519184-ffe55e92-4e05-11e8-950a-6a98fe3b1e9a.png)
