### ISSUE TITLE
[6001] Servizi al cittadino - Pagamento bollo certificati emessi online

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#646]
Buongiorno, vorrei capire cosa succede se dal portale del Comune un cittadino dovesse richiedere ad ANPR un certificato in bollo e poi non lo.utilizza (perché magari ha sbagliato certificato oppure non gli serve più, etc...). È obbligato comunque al pagamento del bollo?  Cioè, è sufficiente che un certificato venga emesso perché si richieda il pagamento del bollo oppure è necessario solo se viene utilizzato (per il valore legale ) ?
Normalmente, se si recasse allo sportello pagherebbe il bollo al momento stesso del rilascio. Mentre, con la richiesta online, anche se il sistema impone di inserire il codice della marca da bollo preventivamente acquistata, l'utente potrebbe mettere un codice fittizio e poi comprare dopo la marca da bollo da apporre sulla copia cartacea. Ma se poi non lo utilizza non compra più la marca da bollo. 
Questo scenario non si verifica invece se si potesse pagare il bollo con PagoPa. Avreste qualche notizia in merito? Grazie

**Comment by gcarbonin** [comment]
La gestione del pagamento del bollo è a carico del portale del Comune. Penso (ma è una mia opinione) che si potrebbe semplificare molto la vita di tutti aggiungendo sul certificato una frase (" il presente certificato è valido solo se munito di marca da bollo...") e lasciando a chi ne usufruisce l'onere dell'acquisto.

**Comment by Eduardo1977** [comment]
Grazie molte per i vostri chiarimenti. In base al suggerimento della Dott.ssa Carbonin di apporre la scritta "ll presente certificato è valido solo se munito di marca da bollo..." non dovrebbe essere il servizio 6001 di di ANPR a doverla mettere quando l'emissione è online? Anzichè stampare la scritta "Imposta di bollo corrisposta mediante contrassegno da Euro 14,62 (DPR 26.10.1972, n. 642 - art.3, co. 1, lett. a)" ?
In ogni caso, ci sarebbe una soluzione  per tutelare il cittadino che ha richiesto online un certificato erroneamente ? E' comunque obbligato al pagamento (e quindi perseguibile)? Il Comune (come ovvio) è chiamato in causa dallo Stato per il mancato versamento ?
Scusate se rifaccio la stessa domanda: ci sono novità per il pagamento del bollo con PagoPa?

**Comment by gcarbonin** [comment]
La "mia teoria" è tutta da verificare; sicuramente sembra non  coerente con quanto riportato da RENZO63 ma mi risulta che alcuni comuni già operino così;.
Rispondo nell'ordine:
1) Mettendo la frase il cittadino acquista la marca dal tabaccaio e la appone quando usa il certificato
2) La "nuova" scritta potrebbe essere apposta da ANPR (in sostituzione di quella attuale presumibilmente)
3)vedi punto 1
4) e 5) non so
6) Intende dire "una integrazione ANPR e PagoPa"? Al momento non c'è e non rientra tra gli interventi prioritari (a meno che non diventi essenziale per i certificati).

**Comment by Eduardo1977** [comment]
Grazie ancora Dott.ssa Carbonin. Riguardo al pagamento del bollo tramite PagoPa, non intendevo "una integrazione ANPR e PagoPa". Intendo se il servizio PagoPa adesso permette di pagare anche il bollo. Tempo fa sembrava che mancasse poco per l'attivazione di questo servizio. Ho approfittato per chiedere di PagoPa visto che c'era di mezzo il discorso del bollo per il certificato.

**Comment by RENZO63** [comment]
Ricordo ad Eduardo che il bollo e' attualmente di euro 16.00 e non 14.62
Molti comuni stanno operando su questi casi in modo diverso:
alcuni riportano la frase suggerita dalla dott.sa Carbonin
altri chiedono l'inserimento del codice del contrassegno della marca e lo inseriscono nel certificato (soluzione adottata da molti comuni per quanto riguarda le pratiche edilizie).  Questo obbliga il richiedente ad assolvere l'imposta prima dell'emissione della certificazione richiesta (o presentata per quanto riguarda le pratiche edilizie).
A mio parere questa seconda strada e' quella maggiormente vicina alla norma per una semplice ragione:
se io richiedo un certificato che viene emesso il 18/04/2018 e vado dal tabaccaio il 20/04/2018 al momento che appongo il contrassegno risulta chiaramente che l'assolvimento e' stato successivo all'emissione del documento e questo in violazione del dpr 642/72 che dispone l'assolvimento prima della sottoscrizione del documento.
Ovviamente il tema andrebbe sviluppato meglio e con pareri piu' autorevoli di quelli del sottoscritto ma, in ogni caso, non ritengo che vi possa essere una sorta di diritto al ripensamento da parte del richiedente...
Ricordo comunque che l'art. 22 del noto dpr dispone:
Art. 22. Solidarieta'. 
Sono obbligati in solido per il pagamento dell'imposta e delle eventuali ((sanzioni amministrative)): 
1) tutte le parti che sottoscrivono, ricevono, accettano o negoziano atti, documenti o registri non in regola con le disposizioni del presente decreto ovvero li enunciano o li allegano ad altri atti o documenti; 
2) tutti coloro che fanno uso, ai sensi dell'art. 2, di un atto, documento o registro non soggetto al bollo fin dall'origine senza prima farlo munire del bollo prescritto. La parte a cui viene rimesso un atto, un documento o un registro, non in regola con le disposizioni del presente decreto, alla formazione del quale non abbia partecipato, e' esente da qualsiasi responsabilita' derivante dalle violazioni commesse ove, entro quindici giorni dalla data del ricevimento, lo presenti all'ufficio del registro e provveda alla sua regolarizzazione col pagamento della sola imposta. In tal caso la violazione e' accertata soltanto nei confronti del trasgressore.

Su pagopa so che ci sono applicativi per le pratiche edilizie che lo implementano (o che sono in corso di implementazione)

**Comment by Eduardo1977** [comment]
Grazie mille per tutte le indicazioni utilissime. 
Invece, sul discorso del bollo di 16 euro, com'è che ANPR stampa la scritta "Imposta di bollo corrisposta mediante contrassegno da Euro 14,62 (DPR 26.10.1972, n. 642 - art.3, co. 1, lett. a)" ?

**Comment by gcarbonin** [comment]
Quell'importo ci è stato indicato e quello si stampa. Controlliamo e modifichiamo

**Comment by gcarbonin** [comment]
Preciso meglio: l'importo lo indica il comune nella chiamata e quello viene stampato

**Comment by RENZO63** [comment]
Infatti nei miei certificati l'importo viene riportato esattamente in euro 16,00

**Comment by RENZO63** [comment]
L'imposta di bolla è ufficialmente aumentata il 26 giugno 2013, con l'entrata in vigore della legge 71/13 di conversione del Decreto legge del 26 aprile 2013 n . 43.

**Comment by RENZO63** [comment]
L'imposta di bollo è ufficialmente aumentata il 26 giugno 2013, con l'entrata in vigore della legge 71/13 di conversione del Decreto legge del 26 aprile 2013 n . 43.

**Comment by slastrucci** [comment]
Buongiorno a tutti,
vista l'emergenza sanitaria in corso il Comune di Prato vorrebbe riattivare per i cittadini  la possibilità di ottenere on-line certificati in bollo. Questa possibilità era presente sul nostro portale prima del subentro in ANPR ma è stata interrotta a causa dell'assenza sul certificato di un dicitura che indica espressamente la necessità di apporre la marca da bollo cartaceo (come indicato da Carbonin).

Secondo la nostra interpretazione l'apposizione del bollo deve essere fatta tramite l'utilizzo di una marca "fisica" che ne impedisca la duplicazione. Altre soluzioni come il bollo virtuale o l'indicazione del numero di serie e la data di emissione renderebbe il certificato facilmente duplicabile, agevolando in questo modo l'evasione del bollo nelle eventuali copie.

La necessità di apporre una marca da bollo però dovrebbe essere evidente, servirebbe quindi una dizione che lo indica esplicitamente, e se possibile, anche un riquadro prestampato con scritto ad esempio "Apporre bollo da 16€".

Abbiamo scartato l'ipotesi di apporre noi quello che manca direttamente sul pdf prodotto da ANPR perchè, in questo modo, potrebbe non risultare autentico agli occhi di chi effettua la verifica tramete il QR-code.

Sono stati fatti passi avanti in questo senso sul servizio 6001 di certificazione?
E' possibile tramite qualche parametro di certificazione pilotare l'aggiunta di una dizione che riguarda l'apposizione del bollo?

Grazie.

Lastrucci Stefano
