### ISSUE TITLE
Generare la documentazione in automatico dai file WSDL e XSD

### ISSUE THREAD

**Issue by ncarandini** [italia/anpr#65]
Nel sito di documentazione del progetto manca la documentazione degli elementi e delle proprietà definite dal file WSDL e i vari file XSD che definiscono il servizio.

Sarebbe utile predisporre un tool che a partire da questi ultimi possa generare le pagine in formato .md (markdown) da utilizzare poi nella generazione automatica delle relative pagine HTML del sito.

**Comment by luca-teamdigitale** [comment]
Duplicate of #311
