### ISSUE TITLE
[5012] Impossibile annullo di una 5008

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#650]
Buongiorno,
sto facendo alcune prove in ambiente di TEST per quanto riguarda gli annulli, nello specifico sto cercando di annullare un'operazione 5008 ( idOperazioneANPR = 4668967 ), come risposta ricevo l'errore EN234 (Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione).

Sorge però un problema:
come ben sappiamo gli annulli vanno fatti in sequenza, e siccome l'operazione 5008 sopra indicata non è annullabile tramite il servizio 5012, le operazione precedenti alla 4668967 per il mio individuo non sono annullabili, infatti al tentativo di annullare l'operazione precedente ( idOperazioneANPR = 4668966 ) ottengo: "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa", come immaginavo.

In breve: l'impossibilità di annullare la 5008 blocca l'annullo delle operazioni precedenti.

Come posso risolvere il problema?
Ringrazio anticipatamente

**Comment by rvinzani** [comment]
Stiamo effettuando un intervento per eliminare questo controllo nel caso il soggetto non sia validato. Nel caso invece che il soggetto abbia un codice fiscale validato e sia stata effettuata una variazione di dati anagrafici, poiché tale variazione viene comunicata all'agenzia delle Entrate, con possibile emissione di nuovo codice fiscale, rimarrà il controllo che inibisce l'annullamento in quanto creerebbe dei disallineamenti con Agenzia Entrate.

**Comment by rvinzani** [comment]
Salve, come le dicevo stiamo effettuando un aggiornamento per limitare il controllo solo laddove strettamente necessario. A breve le faremo sapere quando riprovare.

**Comment by rvinzani** [comment]
Abbiamo effettuato l'aggiornamento del controllo. Può riprovare e farci sapere l'esito? Grazie

**Comment by SAlberto** [comment]
Buongiorno,
abbiamo riprovato l'annullo e l'operazione (CF non validato) è avvenuta con successo.

Se il soggetto ha il Codice Fiscale validato, ed è presente una 5008 (non annullabile per via del controllo, che se ho capito bene rimane nel caso di CF validato), cosa consigliate di fare per annullare le eventuali operazioni (che ho bisogno di annullare) precedenti alla 5008?

Grazie

**Comment by SAlberto** [comment]
Un caso reale che ci viene in mente è l'annullamento entro 45 giorni di un cambio di residenza (interno al comune o tra due comuni subentrati) per mancati accertamenti.


- Qui di seguito riportiamo un esempio di stack di servizi chiamati per un cambio di residenza tra due comuni subentrati in ambiente di Test:

[5005] mutazione di residenza del soggetto (idOperazioneANPR 4701242)
[5008] mutazione dell'Identificativo scheda attribuito dal Comune (idOperazioneANPR 4701243)
[5001] mutazione parentele nella famiglia di destinazione (idOperazioneANPR 4701244)

In caso di accertamento Negativo, il comune dovrà annullare l'evento, nell'ordine 5001, 5008, 5005, ma se l'annullo della 5008 è bloccato perchè la persona ha il codice fiscale validato, sarà anche impossibile annullare la 5005 e quindi ripristinare la posizione anagrafica.


- Per il cambio di residenza all'interno dello stesso comune la [5008] può essere chiamata per variare il flag "Senza Fissa Dimora".

**Comment by gcarbonin** [comment]
Stiamo facendo interventi che riguardano proprio il problema del ripristino delle posizioni anagrafiche. La issue relativa è la  #783.
