### ISSUE TITLE
Notifiche NRIS non trovate

### ISSUE THREAD

**Issue by busaster** [italia/anpr#651]
Ambiente di test.
Con il servizio 3007 cerco tutte le notifiche NRIS prodotte in un giorno.
Ho la certezza che in quel giorno siano state effettuate operazioni da WEBAPP (per lo meno le ID ANPR 4668911 e 4670104).
Il servizio di ricerca però non mi ritorna nessuna operazione (operazione ricerca ID ANPR 4671718).
Come mai ?

**Comment by gcarbonin** [comment]
Nella richiesta è specificato:

<periodoRiferimentoRichieste><dataOraIniziale>2018-04-18T00:00:00.000+02:00</dataOraIniziale><dataOraFinale>2018-04-19T00:00:00.000+02:00</dataOraFinale></periodoRiferimentoRichieste

questo equivale a selezionare le operazioni fatte il giorno 18, che non ci sono.
Spostando le due date avanti di un giorno si ottengono le notifiche.

**Comment by busaster** [comment]
Chiedo venia non avevo notato le date nel filtro.
Grazie
