### ISSUE TITLE
Aggiornamento test comuni / presubentro

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#653]
A partire dal 3 maggio sarà presente in ambiente di test e presubentro la versione 4.0 di ANPR che comprende le nuove funzionalità elencate nell'allegato. Assieme ad una nota riassuntiva degli interventi effettuati sono presenti le nuove tabelle per la mutazione dati scheda e residenza, il nuovo tracciato in formato Excel del servizio 5008 e i wsdl-xsd del servizio di mutazione 5000.
Per effettuare l'intervento, i servizi di test comuni e presubentro non saranno disponibili a partire dalle 17:30 alle 20 di mercoledì 2 maggio
[aggiornamento_specifiche_02_05_2018.zip](https://github.com/italia/anpr/files/1971131/aggiornamento_specifiche_02_05_2018.zip)

**Comment by MarcoMigliori** [comment]
Segnalo per chi legge il documento delle note, un piccolo refuso nel link alla frase seguente
   _In accordo con quando descritto nella procedura di gestione delle versioni di ANPR :_  

che ovviamente deve rimandare a questa pagina:
https://anpr.readthedocs.io/en/latest/change-management/change-management.html#metodologia-di-aggiornamento

**Comment by mttfranci** [comment]
Grazie della segnalazione, abbiamo aggiornato la nota.

**Comment by Amucciarelli74** [comment]
Buon giorno,
segnalo anch'io un possibile refuso nel documento delle note, relativamente al punto "_1.2	AGGIORNAMENTO INDIRIZZO POST SUBENTRO_" e in particolare dove è riportato che "_E’ stato modificato l’attuale WS 5001 e parallelamente, l’acquisizione tramite WA della mutazione per acquisire la rettifica dell’indirizzo della famiglia/convivenza, quale risulta a seguito degli accertamenti introducendo il tipo mutazione 8._"
Nel tracciato excel del WS 5001, per il campo '_tipoMutazione_' della sezione '_datiControllo_' è indicato di fare riferimento alla tabella 46 per i valori ammessi, ma nella versione attualmente disponibile di tale tabella ('_tabella_46_tipo_mutazione_famiglia_convivenza_05022018_' ) il tipo mutazione 8 non è previsto (il nuovo valore compare invece correttamente nel menù a tendina della WA).
La tabella con il nuovo valore fornita in questo pacchetto di aggiornamenti, ossia la "_tabella_47_tipo_mutazione_residenza_02052018_", è invece la tabella di riferimento, per gli stessi valori, del WS 5005 (anche in questo caso, la WA è invece corretta e il valore non compare nel menù a tendina).

Giuseppe Mucciarelli, TINN srl.

**Comment by rvinzani** [comment]
Grazie della segnalazione, abbiamo aggiornato la tabella 46 presente nell'allegato
