### ISSUE TITLE
[2009] Estinzione convivenza e consultazione storica

### ISSUE THREAD

**Issue by busaster** [italia/anpr#654]
Ambiente di test.
Con l'operazione id ANPR 4690500 ho estinto una convivenza con data archiviazione oggi (2/05/2018).
Se però cerco di consultare questa convivenza ad una data precedente la data di archiviazione non trovo nulla (es consultazione 3002 di id ANPR 4690524)

**Comment by danielarosa** [comment]
Buongiorno,

potete riprovare a fare la consultazione in data precedente alla data di archiviazione per la convivenza in questione, ora funziona correttamente.

Saluti
Daniela Rosa

**Comment by busaster** [comment]
confermo il corretto funzionamento
