### ISSUE TITLE
[WEBAPP] errore in ricerca convivente di fatto per CF 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#656]
ambiente di test. 
Iscrizione aire per altri motivi.
nel pannello "Convienza di fatto" valorizzo il CF e premo cerca.
Viene aperta una pagina di ricerca persona, valorizzo CF e premo cerca, esce l'errore come immagine
![image](https://user-images.githubusercontent.com/1733338/39518938-12412a68-4e05-11e8-9c07-08304ba4aacf.png)

**Comment by mttfranci** [comment]
Buongiorno. L'aggiornamento di ieri sera dovrebbe aver risolto questo caso. e' possibile provare nuovamente.

**Comment by busaster** [comment]
Confermo che ora funziona.
Grazie
