### ISSUE TITLE
[WEBAPP] iscrizione con convivenza di fatto che non compare in ricerca

### ISSUE THREAD

**Issue by busaster** [italia/anpr#657]
Ambiente di test.
Da WebApp Ho iscritto in AIRE per altri motivi un soggetto con ingresso in famiglia esistente e con creazione di convivenza di fatto con IS di questa famiglia (id operazione ANPR 4690717).
L'operazione si è conclusa con successo e se la consulto ottengo un XML dove è presente la sezione "convivenzaDiFatto" (ma con un dato di cittadinanza errato che non ho inserito da interfaccia).
Se però consulto poi il soggetto iscritto (sia da webapp che con WS 3002) non viene ritornato il dato di convivenza di fatto, nel XML restituito al 3002 manca proprio la sezione "convivenzaDiFatto".
Come mai ?

**Comment by gcarbonin** [comment]
stiamo esaminando il problema facciamo sapere quando possibile riprovare

**Comment by gcarbonin** [comment]
E' possibile riprovare

**Comment by busaster** [comment]
effettuata altra operazione analoga, ora il dato viene registrato correttamente e riportato nelle estrazioni.
Grazie- Chiudo
