### ISSUE TITLE
[3007] Periodo Riferimento Richieste

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#658]
Con il servizio 3007, è possibile impostare un qualsiasi periodo di riferimento (dataOraIniziale/dataOraFinale), per ottenere tutte le operazioni avvenute nell'intervallo? Oppure ci sono limitazioni nella risposta?
Ad esempio, il 3003 richiede che l'intervallo non sia maggiore di 30 giorni.
Grazie

**Comment by azabatta** [comment]
Al momento non sono previste limitazioni, eventuali variazioni saranno comunicate ed applicate prima negli ambienti di test esposti.
