### ISSUE TITLE
[7001] ws - download tabelle decodifica

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#659]
Ambiente di Test e Pre-Prod
Da ieri sera non si riesce ad effettuare il download delle tabelle di decodifica, compare l'errore "Internal Error".

Grazie

**Comment by mttfranci** [comment]
Grazie della segnalazione, dovrebbe essere possibile riprovare.

**Comment by SAlberto** [comment]
Ora funziona, Grazie
