### ISSUE TITLE
[5008] web service - rettifica cognome e nome

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#66]
buongiorno.

stiamo tentando, senza successo, a passare una variazione di nome.
probabilmente non abbiamo capito quale debba essere la combinazione di dati da passare perchè venga accettata la variazione.
l'ultimo tentativo fatto (idOperazione 2017000361 - dptest - comune di Faenza) ha queste caratteristiche:
- generalitaPerRicerca: cognome / vecchio nome / idANPR (no codiceFiscale)
- generalitaDaModificare: cognome / nuovo nome / idANPR (no codiceFiscale)
- gestioneCF: 1 (per richiesta attribuzione CF)
il web-service restituisce l'errore:
EN125 - E - Per richiesta attribuzione CF o omocodice, il codice fiscale non deve essere valorizzato

abbiamo provato ad indicare anche il codiceFiscale nelle generalitaPerRicerca, ma il messaggio è lo stesso.

tra i tentativi fatti, abbiamo anche provato a modificare il nome dalla web-applicatione, ma la segnalazione era la stessa ed in quel caso sembrava possibile modificare il nome ma non annullare il codice fiscale.

se possibile avere qualche indicazione al riguardo.

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Non si deve richiedere l'attribuzione del codice fiscale; gestioneCF deve essere 0 o assente.

**Comment by AMonopoliADS** [comment]
che è una ipotesi che avevamo ventilato... ma poi in che modo verrà assegnato il CF con le nuove generalità?
fino ad oggi, a parità di condizione, il CF aggiornato arriva tramite SAIA

**Comment by gcarbonin** [comment]
I servizi di registrazione di ANPR richiamano servizi cooperativi di Agenzia Entrate che in tempo reale eseguono gli aggiornamenti

**Comment by gcarbonin** [comment]
Il nuovo codice fiscale e' presente nella risposta ANPR

**Comment by AMonopoliADS** [comment]
gestioneCF valorizzato a '0' ha fatto scattare "Errore di congruenza" (idOperazione 2017000365 - dptest - comune di Faenza).
gestioneCF non valorizzato fa andare a buon fine l'operazione.

nella risposta ANPR è presente in effetti il codice fiscale, che per i 3 casi provati è sempre uguale al precedente (pur variando la data di validità)... lo segnalo come dato di fatto, ma magari è normale così per l'ambiente di test.

chiedo conferma che per i servizi di iscrizione valgano ancora le regole di utilizzo del campo gestioneCF.
normalmente per un soggetto con CF non validato attiviamo l'opzione di attribuzione autmatica valorizzando il campo a '1'

grazie.

**Comment by gcarbonin** [comment]
GestioneCF = 1 (o 2 per gli omocodici) si utilizza soltanto quando la persona NON ha un codice fiscale.
con gestioneCF assente l'operazione è andata a buon fine ma non ha cambiato il CF questo probabilmente è un errore nostro che stiamo verificando. Avverto quando possibile riprovare

**Comment by gcarbonin** [comment]
Abbiamo sistemato il problema. Puo riprovare con un caso da creare ex-novo. Possiamo eventualmente sentirci telefonicamente.

**Comment by AMonopoliADS** [comment]
sto provando ad iscrivere soggetto ex-novo per poi procedere con la rettifica di nome... il web-service ritorna il messaggio bloccante:
EAA0A - E - Errore di sistema

(idOperazioneComune 2017000414 - dptest - comune di Faenza)

**Comment by gcarbonin** [comment]
Siamo informati; e' un problema del sistema di test dell'Agenzia. Avvertiamo quando possibile riprovare

**Comment by gcarbonin** [comment]
Puo' riprovare con l'iscrizione. Prima della variazione mi avverta e attenda il mio ok.

**Comment by AMonopoliADS** [comment]
adesso nel tentativo di inoltrare nuovamente l'iscrizione ottengo questo errore:
"EAA10 - E - Codice fiscale RTTFCI67L07C872F già presente in AT, con dati anagrafici uguali ed indirizzo simile"
meglio provare con un nuovo caso da zero? oppure vuole verificare questo?
(idOperazioneComune 2017000416 - dptest - comune di Faenza)

**Comment by gcarbonin** [comment]
Riprovi ora per favore con lo stesso soggetto. Le ho detto io di provare troppo presto

**Comment by AMonopoliADS** [comment]
riprovato... iscrizione avvenuta con successo.
attendo Suo cenno per procedere con la rettifica delle generalità

**Comment by gcarbonin** [comment]
Ha provato la rettifica delle generalità?

**Comment by AMonopoliADS** [comment]
buongiorno. 
non abbiamo fatto ulteriori test perche ci era stato scritto di procedere con l'iscrizione e di attendere il vostro ok per procedere con la variazione.
