### ISSUE TITLE
[WEBAPP] Mutazione famiglia - cambio relazione componenti non funziona ?

### ISSUE THREAD

**Issue by busaster** [italia/anpr#661]
Ambiente di test.
Ho una famiglia (ID ANPR  4907386) con un unico componente con relazione moglie, caso presentatosi in seguito al trasferimento in altra famiglia dell'intestatario.
Da webapp con l'operazione in oggetto imposto la relazione a "Intestatario" per il soggetto rimanente (la moglie), salvo.
ANPR mi da riscontro positivo (si crea infatti una operazione ID ANPR 4696499 ), ma se poi verifico il dato (sia da webapp che con WS 3002) il soggetto continua ad essere Moglie.

**Comment by cmigliardi** [comment]
Buongiorno, il ws 5005 di mutazione consente di indicare solo il ruolo che assumerà il componente che esce dalla famiglia nel nuovo nucleo. Non è possibile indicare contemporaneamente il ruolo che assume la persona che resta nella famiglia. 
Infatti la response riporta: <codiceErroreAnomalia>EN226</codiceErroreAnomalia>

<tipoErroreAnomalia>W</tipoErroreAnomalia>

<testoErroreAnomalia>Aggiornare la famiglia di provenienza del soggetto di cui e' stata cambiata la residenza ed eventualmente i relativi rapporti di parentela</testoErroreAnomalia>  

Questo il motivo per cui interrogando il soggetto unico componente rimasto, continua ad essere "Moglie".

**Comment by busaster** [comment]
L'operazione che pare produrre nessun effetto è proprio il cambio di relazione da Moglie ad Intestatario fatta in un secondo tempo,  dopo il trasferimento del IS precedente  in altra famiglia.

Ovvero prendo la famiglia ID ANPR 4907386 che ha un unico componente con relazione Moglie. 
Da WebApp, con una mutazione di famiglia di tipo composizione, la imposto come Intestatario. 
Confermo l'operazione e la webapp me la da come completata con successo.
Consulto poi la scheda del soggetto ma questo è rimasto moglie.

**Comment by cmigliardi** [comment]
Nella pagina dove viene visualizzata la Moglie occorre impostare il valore Intestatario, biffare la riga e dare Conferma. Ciò fa sì che venga riportato il componente nella sezione elenco componenti della richiesta 5001.

**Comment by busaster** [comment]
Ok, il mio errore quindi era non accendere la spunta alla riga modificata.
Spunta che ora ho visto si mette da sola alla modifica del drop down "relazione", cosa che prima non accadeva, altrimenti questa issue non sarebbe nemmeno stata aperta.
