### ISSUE TITLE
[WEBAPP] Mutazione soggetto con scadenza permesso soggiorno strana

### ISSUE THREAD

**Issue by busaster** [italia/anpr#662]
Ambiente di test.
Il soggetto ID ANPR 9462981 è straniero con document odi soggiorno con data scadenza 31/12/3000.
Il soggetto può essere consultato senza problemi con il servizio 3002.
Tentando di eseguire una Mutazione Altri Dati con la webapp non riesco nemmeno ad iniziare in quanto compare il messaggio in immagine e la pressione del pulsante "Conferma" non permette di proseguire.
![image](https://user-images.githubusercontent.com/1733338/39693009-e130d194-51e2-11e8-93ef-481316e8914b.png)

**Comment by mttfranci** [comment]
Buongiorno.
Stiamo verificando la segnalazione, avviseremo appena sarà possibile riprovare.

**Comment by busaster** [comment]
Confermo la soluzione del problema.
Grazie
