### ISSUE TITLE
[2001] Decesso Individuo AIRE - Errore EN240 

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#664]
ambiente di PRODUZIONE - comune di MEDICINA (BO) - idOperazioneComune 2018003110

non è possibile completare la cancellazione per morte di soggetto AIRE (idSoggettoANPR 18939858), a causa dell'errore ritornato dal web-service:
EN240 - E - La data decorrenza dell'operazione non puo' essere inferiore alla data decorrenza dell'ultima operazione effettuata sul soggetto 

in riferimento a quanto approfondito con issue #421  abbiamo verificato le date che concorrono a questo controllo (iscrizione AIRE e Residenza), e ci risultano valorizzate.
mentre, via web-service, non è possibile consultare la dataUltimoAggiornamento (che comunque ipotizziamo sia stata valorizzata da ANAG-AIRE...)

è possibile verificare se si sta manifestando lo stesso bug riscontrato con la issue sopra citata?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Ora può riprovare

**Comment by AMonopoliADS** [comment]
l'operazione è andata a buon fine.
grazie.
