### ISSUE TITLE
[3002] Internal server error in Produzione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#665]
Perugia - Ambiente di produzione.

Ricercando con il WS in oggetto il soggetto con ID ANPR 21204356 riceviamo una risposta d'errore "SoapFault: Internal Error (from server)".

La prova è stata reiterata più volte negli ultimi giorni senza ottenere risultati.
Purtroppo non ho a disposizione gli ID operazione comune delle operazioni di cui sopra.

Potete aiutarci a capire il problema ?

**Comment by gcarbonin** [comment]
Buongiorno. Ci dovrebbe mandare la richiesta sulla posta privata.

**Comment by gcarbonin** [comment]
Ci sono caratteri non validi nel toponimo. Il comune deve inviarci una richiesta via PEC per rimuovere questi caratteri.
