### ISSUE TITLE
[3003] Iscrizioni per nascita "Soggetto non validato"

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#666]
Buongiorno,
utilizzando il servizio 3003 (PRODUZIONE, Bistagno (AL), 006017) per consultare i dati dell'operazione 2103517, che corrisponde ad una (ed unica per ora) iscrizione per nascita "con esito positivo e anomalie", trovo "codiceErroreAnomalia" = EN141 (Soggetto non validato), mentre "tipoErroreAnomalia" = W.
Non dovrebbe essere E anzichè W ? 
Nel caso fosse E il servizio 3003 non dovrebbe più restituire questa operazione, giusto?
Grazie

**Comment by azabatta** [comment]
Buonasera, 
la prima domanda riguarda in generale il funzionamento dei servizi anagrafici che prevede la possibilità di concludere positivamente un’operazione dando evidenza  di errori che non risultano bloccanti  (di tipo “W”).  E’ quanto è accaduto all’iscrizione indicata: il cittadino è stato iscritto ma il sistema ha segnalato un’anomalia in fase di validazione del CF.  Il servizio 3003 si limita a restituire la stessa risposta inviata da ANPR a fronte di una richiesta ricevuta da un comune.
La restituzione o meno di un evento dipende dal valore specificato nel campo “statoLavorazione”: nel caso specifico sono state richieste  le operazioni con codice servizio 1001, relative al un determinato periodo, terminate positivamente con segnalazione di errori non bloccanti (statoLavorazione =  6).

**Comment by Eduardo1977** [comment]
La prima domanda è in merito alla classificazione data a EN141 pubblicata [https://anpr.readthedocs.io/en/latest/tab/tab_elenco_errori_anpr.html](https://anpr.readthedocs.io/en/latest/tab/tab_elenco_errori_anpr.html), dove si può vedere che può essere solo E per "Servizi- Severità". 
Invece, nella risposta del 3003 EN141 diventa W.

**Comment by azabatta** [comment]
Verifichiamo la documentazione. Grazie per la segnalazione

**Comment by azabatta** [comment]
Buonasera, la documentazione è stata aggiornata.
