### ISSUE TITLE
[3003] Operazioni 1001 dataDecorrenzaResidenza

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#667]
Buongiorno,
utilizzando il servizio 3003 (PRODUZIONE, Bistagno (AL), 006017) per consultare i dati delle operazioni 1001, trovo che la "dataDecorrenzaResidenza" per i nuovi nati è sempre [2017-12-07+01:00], che corrisponde alla data di subentro del Comune in ANPR. 
Consultando la scheda nella WebApp, invece, la "dataDecorrenzaResidenza" viene visualizzata correttamente.
Potrei avere chiarimenti?
Grazie

**Comment by azabatta** [comment]
Buongiorno,
la data decorrenza residenza rilevante per il cittadino in fase di iscrizione da ws 1001 è quella restituita nella sezione legameSoggetto. La data decorrenza residenza restituita nella risposta è riferita al tipo dato “residenza” che riguarda la residenza corrente della famiglia cui il neonato viene associato: abbiamo riscontrato un errore nella sua impostazione (errore nella risposta del ws, sul DB è corretta). E’ stata aperta una correttiva che è in lavorazione. Grazie per la segnalazione.

**Comment by Eduardo1977** [comment]
Grazie come sempre per la disponibilità

**Comment by azabatta** [comment]
La generazione della risposta è stata modificata:  nelle nuove iscrizioni per nascita la data decorrenza residenza riporta la data di decorrenza valida per il neonato. 
La modifica è stata estesa in tutti gli ambienti.
