### ISSUE TITLE
Annullo di Mutazione residenza tra comuni subentrati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#668]
Buongiorno,

Ambiente di Test:

Stavamo facendo dei test sullo scarico di una Notifica di tipo N015 (ripristino posizione anagrafica).
Per generarla abbiamo fatto immigrare un individuo X (intestatario scheda di un nucleo di 4 persone) dal comune subentrato P (provenienza) al comune subentrato D (destinazione).
In seguito a questa operazione il comune P ha ricevuto una notifica di tipo N010 (cambio residenza) e abbiamo provveduto a caricare l'emigrazione in locale e ad aggiornare le parentele della famiglia da cui è partito (nominare il nuovo Intestatario sostanzialmente) con il servizio 5001 (4703982).

Simulando un ipotetico accertamento con esito negativo per il nostro individuo di prova X, il comune D ha provato ad annullare l'immigrazione, ma l'operazione di cambio residenza 5005 (idOperazioneANPR: 4703639) risulta essere impossibile da annullare per il seguente motivo: "L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa", ma l'operazione 4703639 è l'ultima per l'individuo quindi non capiamo cosa blocchi l'annullamento.

Crediamo che l'operazione 5001 (4703982) generata dal comune P interferisca con l'annullamento che sta provando a fare il comune D.
Il comune D però non ha alcun modo di vedere/intervenire su un'operazione effettuata da un altro comune.

Come possiamo risolvere il problema?

**Comment by frmariani** [comment]
Stiamo verificando

**Comment by gcarbonin** [comment]
Chiusa in quanto lo stesso argomento è trattato nella issue #783
