### ISSUE TITLE
Certificato storico residenza (tra comuni diversi)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#669]
Ambiente pre-subentro. Ho appena fatto "mutazione residenza" nel soggetto 14019694, che dichiara la residenza nel nostro comune, proveniente da Prato, altro comune ANPR. 
Faccio il certificato di residenza, esce correttamente,.
Faccio il certificato di residenza storico, mi restituisce errore
"Il certificato non puo' essere emesso in quanto la data di decorrenza dell'indirizzo risulta assente (Codice: EN422)"
Presumo dovuto ai dati di Prato originari. Corretto?

**Comment by gcarbonin** [comment]
Si. Il certificato dovrebbe uscire se indica una data di decorrenza nella richiesta di certificato maggiore o uguale a quella della mutazione di residenza
