### ISSUE TITLE
[3002] Web Service - recupero dati di persone iscritte Aire

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#67]
Comune di Venezia, ambiente di test, 31.03.2017

Abbiamo riscontrato un problema nel servizio [3002] quando cerchiamo di recuperare dei dati Aire popolati tramite AnagAire.
Sono stati passati, nell'indirizzo, dei caratteri non previsti da Anpr. 
Non sappiamo se in fase di popolamento Aire queste persone hanno comportato segnalazioni di anomalie, ma adesso non riusciamo più a recuperarle in quanto l'xml risulta invalido.

Vi invio i due identificativi ANPR: -	5268070    -	5186002

Potremmo avere gli stessi problemi anche nei campi cognome e nome.

Sarebbe utile che in fase di subentro degli Aire applicaste gli stessi controlli usati per i file di subentro dei residenti Apr in modo da bloccare il subentro Aire fino a quando tutti i dati risultano corretti.
 
Ringrazio per l'attenzione
Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
Anche per l'AIRE i vostri dati sono molto vecchi. Consigliamo fortemente di ripopolare l'ambiente di test e pre-subentro
