### ISSUE TITLE
Pattern di simpletype tipoEmail non valido

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#670]
Buongiorno, secondo lo [standard](https://www.w3.org/TR/xmlschema-0/#regexAppendix) la dichiarazione del tipoEmail ([ad esempio questa](https://github.com/italia/anpr/blob/5d336fc7fe25444d10535ec9e59a11ee9dd5da43/wsdl/wsdl5000/tipoDato.xsd#L297)) non è corretta poichè la regex è sempre applicata a tutta la stringa:
> the expression language does not contain the metacharacters ^ and $, although ^ is used to express exception

Questo causa un errore nella validazione del valore, rimuovendo `^` e `$` tutto funziona come dovrebbe

**Comment by mttfranci** [comment]
Grazie per la segnalazione, provvederemo a modificare la definizione del tipo

**Comment by mttfranci** [comment]
Abbiamo aggiornato l'XSD come suggerito
[tipoDato.zip](https://github.com/italia/anpr/files/1994653/tipoDato.zip).

La correzione sarà inclusa in tutti i prossimi rilasci.

**Comment by SAlberto** [comment]
Grazie per l'intervento.
