### ISSUE TITLE
Registrazione decesso di irreperibile

### ISSUE THREAD

**Issue by ANPRCdMI** [italia/anpr#673]
Buongiorno
vorremmo sapere come comportarci nel caso di registrazione di decesso di persona cancellata per irreperibilità.
Abbiamo cancellato per irreperibilità un individuo, ma successivamente abbiamo necessità di registrare il decesso avvenuto nel nostro comune. Se però interrogo la posizione  (Identificativo  ANPR 12659542) per registrare il decesso mi compare il messaggio "Non sono stati trovati soggetti corrispondenti ai criteri di ricerca".
Posto che il messaggio in questi casi sarebbe bello se esponesse il motivo per cui il soggetto non è stato trovato, ad es. "Soggetto cancellato per irreperibilità", oppure "Soggetto cancellato per emigrazione" ecc, , come possiamo procedere con la registrazione del decesso,  non potendo, per ovvi motivi,  annullare l'evento di cancellazione per irreperibilità?

Grazie
Raffaella Tremolada 
Team S.I.Po. Comune di Milano 

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by gcarbonin** [comment]
Ci informeremo con il Ministero in quanto la scheda di un soggetto cancellato è archiviata e come tale non è modificabile.

**Comment by ANPRCdMI** [comment]
Sorry, mi è scappata la send prima che potessi cancellare il resto del messaggio...

**Comment by RENZO63** [comment]
Se un soggetto viene cancellato dall'anagrafe per irreperibilita' non capisco perche' poi si voglia registrarne in anagrafe il decesso.
E' come se un cittadino straniero che  cancellato dall'anagrafe per emigrazione all'estero dovesse poi morire in Italia.
Vi sarebbe la sola registrazione di stato civile (atto di morte) ma sicuramente l'evento non interessa l'anagrafe... stessa condizione per chi viene cancellato per irreperibilita'

**Comment by rvinzani** [comment]
Confermo che in ANPR non è possibile effettuare operazione di mutazione  su una scheda archiviata. In ogni caso l'interrogazione di un soggetto cancellato e del soggetto indicato nello specifico, restituisce tutte le informazioni comprese quelle di cancellazione. Abbiamo fatto una verifica in ambiente di test dove il soggetto risulta registrato
