### ISSUE TITLE
[6001] Certificazione: Destinazione d'uso specifica - Richiesta Info

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#675]
il cliente ha notato che sulla certificazione da web-app è disponibile un'opzione intitolata "Destinazione d'uso specifica", contenente queste due scelte:
- Certificato rilasciato per procedimento disciplinati dalle norme sull'immigrazione 
- Ai sensi dell'art. 40, D.P.R. 445/2000 il presente certificato è rilasciato per cause giudiziarie

vorrebbe gestirlo anche dalla certificazione via web-service, ma non troviamo nelle specifiche del servizio 6001 un campo che permetta di valorizzare la stessa opzione.

è possibile avere qualche informazioni al riguardo?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
pag. 145 delle speciiche

**Comment by AMonopoliADS** [comment]
trovato. grazie

dovresti aggiornare le specifiche excel perchè riportano altre indicazioni.

grazie.

**Comment by gcarbonin** [comment]
va bene grazie

**Comment by azabatta** [comment]
Buongiorno, 
la documentazione è stata aggiornata. Grazie per la segnalazione
