### ISSUE TITLE
Chiarimenti nuovi controlli su file subentro

### ISSUE THREAD

**Issue by raffaellatrevisan** [italia/anpr#676]
Buongiorno, nel predisporre i file del subentro APR per 2 nostri clienti ho applicato i controlli previsti dal nuovo validatore e mi sono stati scartati per i motivi sotto indicati:
1) Comune di AVOLA: viene scartato il dato "luogoEccezionale" nella cui stringa è presente l'apostrofo. Il dato completo è: A BORDO PIROSCAFO CITTA' DI TRIESTE. Abbiamo provato anche a sostituire con la parola "città", ma viene comunque scartato, come da nuove specifiche. Come risolvo ?
2) Comune di MORMANNO: vengono scartati numerosi indirizzi che nel "Piano" hanno il valore -1 o -2. Il cliente sostiene che si tratti di effettivi appartamenti che stanno sotto il livello della strada, su terreni scoscesi. Come risolvo ?

Grazie
Raffaella Trevisan (Andromeda Informatica)

**Comment by mttfranci** [comment]
Grazie della segnalazione, estenderemo i valori ammessi per l'elemento luogoEccezionale. Vi avviseremo appena sarà possibile riprovare.

**Comment by raffaellatrevisan** [comment]
Ringrazio per l'intervento di cui al punto 1 e attendo risposta per la problematica di cui al punto 2.

Raffaella Trevisan (Andromeda Informatica)

**Comment by mttfranci** [comment]
Salve, abbiamo deciso di aggiungere il carattere "-" a quello dei valori ammessi per il piano.
Avviseremo appena sarà possibile riprovare.

**Comment by mttfranci** [comment]
Dovrebbe essere possibile riprovare anche con il carattere "-".

**Comment by raffaellatrevisan** [comment]
Ho riprovato entrambe le problematiche e il file viene correttamente validato.
Grazie

Raffaella Trevisan (Andromeda Informatica)
