### ISSUE TITLE
Regolarizzazione dati indirizzo

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#677]
L’ufficio di Anagrafe del comune di Perugia mi spiega come spesso si presenti la necessità di regolarizzare i dati degli attributi interni dell’indirizzo di residenza, perché ci si accorge che il civico è presente nel db in modo non sufficientemente dettagliato, ad esempio VIA ROMA 10 invece di VIA ROMA 10 interno 2.
Questa variazione oggi viene registrata in ANPR come una mutazione di indirizzo e dalla certificazione storica sembra che sia avvenuta una variazione di residenza, mentre in realtà c’è stata soltanto una regolarizzazione dei dati dell’indirizzo.
Il Cliente mi invita a proporre l’introduzione di un ulteriore tipo di variazione di indirizzo, oltre a quella “normale” e alla variazione di toponomastica/numerazione, in modo che dalla certificazione storica e dalla consultazione risulti la causale 	“regolarizzazione dati indirizzo”, a specificare che le persone interessate non hanno cambiato abitazione ma che l’ufficio ha migliorato il dettaglio dei dati dell’indirizzo. Si potrebbe applicare un vincolo che limiti questa classificazione alla variazione di attributi interni del civico. È una situazione diffusa a parecchi comuni.
Grazie
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Questo servizio è disponibile  (vedi avviso Aggiornamento test comuni / presubentro #653)

**Comment by bfilipazzi** [comment]
Chiedo scusa, non avevo ancora letto la nuova documentazione.
Grazie.
Filipazzi - Maggioli
