### ISSUE TITLE
[3002] e [WEBAPP] Cittadinanza del coniuge : matrimonio.cittadinanza

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#678]
In ambiente pre-subentro, in Riposta3002_OK  e da WEBAPP  non sono presenti i dati di "cittadinanza" del coniuge, sotto il tag "matrimonio" anche se sono state fornite nel subentro.

es. di Risposta3002_OK 
codMittente=001272
codDestinatario=ANPR01
dataOraRichiesta=2018-05-17T17:14:46
idOperazioneANPR=3524348

Nel nostro caso il matrimonio dovrebbe contenere :
* coniuge
* cittadinanza
* datiMatrimonio

Visto che sono i dati che sono state forniti al presubentro.

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by pissardl** [comment]
Da analisi e XSD, l'oggetto  matrimonio  è composto come segue :
```
<xs:complexType name="tipoMatrimonio">
	<xs:sequence>
		<xs:element name="coniuge" type="tipoGeneralita" minOccurs="1" maxOccurs="1"/>
		<xs:element name="cittadinanza" type="tipoCittadinanza" minOccurs="0" maxOccurs="1"/>
		<xs:element name="datiMatrimonio" type="tipoDatiEvento" minOccurs="0" maxOccurs="1"/>
		<xs:element name="ordineMatrimonio" type="numericoMax2" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>
```

Quindi composto da un elemento obbligatorio "coniuge" e 3 opzionali.

Nel subentro sono stati forniti 3 su 4 elementi (nella maggiore parte dei casi, là dove era possibile): 
"coniuge", "cittadinanza", "datiMatrimonio".

L'elemento "cittadinanza" non è visibile da WEBAPP sotto la scheda "Matrimonio".
L'elemento "cittadinanza" non è presente in risposta del 3002 sotto il tag "matrimonio".
Magari non è stato caricato in fase di subentro (e magari non viene preso nel 5008 a questo punto).

A questo punto sembra inutile fornirlo nel subentro, da verificare nel caso di mutazione 5008 per matrimonio ?
Da capire l'utilità che "tipoMatrimonio" contenga "cittadinanza" (del coniuge) se non viene caricato e/o non restituito dai servizi e webapp.

**Comment by frmariani** [comment]
l'elemento cittadinanza viene acquisito e visualizzato nel caso in cui il soggetto coniuge sia extra anpr; 
nel caso in cui il soggetto coniuge sia anpr, può non essere inviato

**Comment by pissardl** [comment]
OK,
Grazie.

2018-05-22 12:26 GMT+02:00 frmariani <notifications@github.com>:
