### ISSUE TITLE
Operazione sospesa

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#679]
Non riusciamo a cancellare da ANPR un cittadino poiché esiste un'operazione sospesa per il soggetto.
Ho individuato l'operazione sospesa ma non ho capito come chiuderla. Codice ID operazione 115788

**Comment by mccalv** [comment]
Salve in attesa della verifica volevo solo ricordare che su questa piattaforma è necessario evitare inserire dati personali
Grazie

**Comment by Raffive** [comment]
Certo! Quando vuoi
Raffaella
0415071155

Da: cmigliardi [mailto:notifications@github.com]
Inviato: venerdì 18 maggio 2018 09.22
A: italia/anpr
Cc: Subscribed
Oggetto: Re: [italia/anpr] Operazione sospesa (#679)


Buongiorno, possiamo sentirci telefonicamente ? grazie Cecilia Migliardi

**Comment by cmigliardi** [comment]
ci siamo sentite con Raffaella - ma non è lei che ha aperto la issue.  è finalmentesubentrati .. potete contattarmi

**Comment by cmigliardi** [comment]
sono stata contattata - c'era una mutazione in sospeso - ho dato indicazioni su come operare. è possibile infatti o Concludere l'operazione o Eliminare l'operazione.
