### ISSUE TITLE
[5008] Web Service - matrimoni con persone non celibi/nubili

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#68]
Venezia, ambiente di test, 31.03.2017

Stiamo cercando di effettuare matrimoni tra persone celibi/nubili con divorziati/vedovi.
Ci viene risposto sempre con errore:

<errore>
        <codiceErroreAnomalia>EN272</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Alla data 01-01-2017 il soggetto ****** risulta gia&apos; coniugato o unito civilmente con un altro soggetto</testoErroreAnomalia>
      </errore>

anche se alla data del nuovo matrimonio il soggetto risulta essere divorziato/vedovo.

Anche nel caso in cui selezioniamo un divorziato/vedovo da coniugare con celibe/nubile riceviamo in risposta sempre un errore di data.

Il soggetto in questione ha ID ANPR  5183796
Le operazioni effettutate sono identificate da:  IDANPR 113301 e 113359

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
E' un problema di base dati: i dati di Venezia di pre-subentro sono molto vecchi. Il caricamento all'epoca funzionava diversamente ed è stato modificato. Con la base dati in questa situazione i servizi non gestiscono correttamente le informazioni.
Sarebbe utile ricaricare i dati ex-novo.
