### ISSUE TITLE
[3002] e [WEBAPP] Elaborazione del dato sentenza.autorita

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#680]
In ambiente pre-subentro, è presente un elaborazione del dato sentenza.autorita non prevista :

in  tipoDato.xsd ,  tipoAutorita  prevede i caraterri "(" e ")" :
```
	<xs:simpleType name="tipoAutorita">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9À-ža-zA-Z\- '/.,()])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="120"/>
		</xs:restriction>
	</xs:simpleType>
```

Nei dati di subentro è stato fornito un valore di autorita con caratteri "(" e ")" attorno la sigla provincia.
Esempio sotto il tag separazioneAnnullamentoCessazioneMatrimonio.sentenza
```	<autorita>TORINO (TO)</autorita>```
	
Si evidenzia che nella risposta 3002 viene effettuata una sostituzione dei caratteri "(" e ")" con il carattere " " (spazio).
Si evidenzia che nella webapp viene effettuata un'eliminazione dei caratteri "(" e ")".

[WEBAPP]
Autorità: TORINO TO

[3002] Risposta3002_OK
dataOraRichiesta=2018-05-18T10:56:53
idOperazioneANPR=3525525
sotto annullamentoMatrimonio.sentenza contiene
```	<autorita>TORINO  TO </autorita>```

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by mttfranci** [comment]
Salve,  durante elaborazione eseguita in fase di subentro sono state rimosse le parentesi tonde.
Sia il 3002 che la webapp mostrano il dato senza parentesi in quanto è stato registrato in tale modo.
Se ripeterete il subentro verranno accettate anche le parentesi tonde per il campo autorità sentenza.
Le movimentazioni fatte da servizi non dovrebbero avere problemi.
