### ISSUE TITLE
[5001] Cambio della data decorrenza legame

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#681]
Buongiorno,

Ambiente di TEST
idOperazioneANPR: 4720684

con il servizio 5001, tipoMutazione 2, ho variato la data del legame di un individuo di una famiglia di 3 componenti, l'operazione ha avuto successo, ma a video sul portale non trovo la data variata.

Mi aspettavo che al seguente percorso:
Home - Consultazione - Consultazione Scheda Individuale - Risultato Ricerca - Dettaglio - Famiglia/Convivenza
al campo "Data decorrenza appartenenza" o  "Data decorrenza Legame" di trovare la data variata, ma non è così.

sapete indicarmi cosa sto sbagliando e con quali servizi poter variare i campi sopra citati?

Grazie

**Comment by SAlberto** [comment]
esiste un altro modo per rettificare la sola data di relazione?

grazie

**Comment by frmariani** [comment]
no
