### ISSUE TITLE
Segnalazione Tabelle di Decodifica

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#682]
Buongiorno, 
volevo solo segnalarvi che la tabella di decodifica 46 al seguente link
https://www.anpr.interno.it/portale/tabelle-di-riferimento
è mancante della voce 8.
L'excel corretto l'ho solamente trovato alla seguente issue #653.

Alla seguente pagina https://www.anpr.interno.it/portale/documentazione-tecnica la documentazione è sempre aggiornata?

**Comment by gcarbonin** [comment]
La documentazione viene aggiornata quando il sw associato viene portato in ambiente di produzione; nella issue si fa riferimento all'ambiente di test comuni e pre-subentro, con relativa documentazione allegata
