### ISSUE TITLE
[5001] rettifica data di origine famiglia/convivenza

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#684]
Buongiorno,

ambiente di test, idOprazioneANPR: 4727250

Sto cercando con il servizio 5001 e tipoMutazione=3 di rettificare la data di origine della famiglia.
Mi torna indietro il seguente Messaggio di Warning (EN395): "per il tipo di mutazione 3 saranno modificati soltanto i dati relativi a motivo famiglia/scheda convivenza".

Come posso rettificare la data di origine del nucleo?

Grazie

**Comment by gcarbonin** [comment]
Questo dato non è al momento rettificabile
