### ISSUE TITLE
[5001] AIRE: Variazione I.S. conseguente a Scissione - EN482

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#685]
comune di SAN DONATO MILANESE - ambiente di PRODUZIONE

In seguito a scissione di Instestatario che si sposta in altro nucleo, il soggetto che rimane diventa Intestatario Scheda.
La comunicazione attraverso la quale vuole essere inviata tale mutazione ritorna il seguente errore:
EN482 - In caso di variazione intestatario scheda, la lista dei soggetti deve contenere anche il precedente intestatario con la nuova relazione di parentela
(rif. idOperazioneComune 1990000238)

non si capisce il senso della segnalazione

ad analoghe condizioni e costruzione dell'xml, una comunicazione relativa a soggetto residente è andata a buon fine (idOperazioneComune 2018000954)

si chiede gentile riscontro con una certa urgenza, perchè abbiamo in sospeso svariate comunicazioni dello stesso tipo.

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
l'operazione andata a buon fine è una cancellazione per decesso (servizio 2001), mentre l'operazione con errore è una mutazione famiglia convivenza (servizio 5001).

Ad ogni buon conto stiamo verificando il motivo dell'anomalia.

**Comment by AMonopoliADS** [comment]
in riferimento all'operazione andata a buon fine, l'idOperazioneComune 2018000954 mi risulta essere una mutazione 5001 come l'altra, anch'essa successiva a scissione di famiglia (pratica 169/2018), ma relativa a famiglia APR.
lo stesso riscontro lo ottengo con la lista operazioni sul soggetto con idSchedaSoggetto 23309632.
lo specifico, se può servire, solo per sicurezza e per accertarmi che stiamo guardando lo stesso oggetto.
grazie.

**Comment by frmariani** [comment]
se il servizio 5001 viene effettuato prima dello spostamento in altro nucleo del vecchio intestatario, nel servizio 5001 tipo mutazione 2 devono essere inseriti entrambi gli intestatari con i rispettivi codici legami modificati;
nel vostro caso abbiamo verificato dal timestamp delle operazioni, che il servizio A006 del vecchio intestatario, è successivo al servizio 5001, che, in questo caso,  avrebbe richiesto entrambi gli intestatari. 
Se riprovate ora, l'operazione andrà a buon fine.

**Comment by AMonopoliADS** [comment]
confermo che la ripetizione degli invii è andata a buon fine.
grazie
