### ISSUE TITLE
[A002] Iscrizione AIRE di soggetto coniugato con altro AIRE caricato con subentro - Errore EN272

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#686]
comune di SAN DONATO MILANESE - ambiente di PRODUZIONE

si sta tentando di perfezionare l'iscrizione AIRE di soggetto coniugato con altro individuo già caricato in ANPR tramite subentro
il soggetto già presente (idSchedaSoggetto 23320901) risulta con i dati di matrimonio minimali, come normale per il subentro eseguito tramite ANAG-AIRE.
l'iscrizione del nuovo soggetto non va a buon fine a motivo di questo errore:
EN272 - E - Alla data 25-07-1983 il soggetto XXX YYY risulta gia' coniugato o unito civilmente con un altro soggetto
(rif. idOperazioneComune 1990000895)

come risolvere?
grazie
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
il soggetto già caricato in ANPR tramite subentro, risulta coniugato con un soggetto X (cognome e data del matrimonio); 
prima di perfezionare l'iscrizione del  nuovo soggetto, dovreste effettuare una mutazione dei dati del matrimonio del primo soggetto (servizio 5008 tipo mutazione 12, oppure nei casi in cui non sia ancora stata stata effettuata nessuna operazione sul soggetto, si può utilizzare la mutazione 21 con la data del subentro) , in modo da poter inserire i dati mancanti e necessari all'individuazione univoca del soggetto X come coniuge  nella successiva iscrizione: nome, cognome, sesso e data di nascita. 

nell'iscrizione del nuovo soggetto, basterà inserire il nome, cognome e idanpr del coniuge per riconciliare il matrimonio dei due soggetti.

Riporto un esempio per essere più chiara:

subentro: soggetto ABC coniugato con soggetto extra EDF (è presente solo il cognome e la data del matrimonio);

A002 : soggetto EDF  coniugato con ABC >>> ERRORE <<<< il servizio non riconosce univocamente il coniuge a causa della carenza dei dati;

5008 tipo mutazione 12 : soggetto ABC coniugato con extra EDF (inserisco nome, cognome, sesso, data di nascita)

A002: soggetto EDF coniugato con ABC (nome, cognome, idanpr) >>> OK

**Comment by AMonopoliADS** [comment]
abbiamo proceduto come indicato, comunicando prima l'aggiornamento dei dati di matrimonio del soggetto già presente e dopo l'iscrizione del coniuge.
grazie
