### ISSUE TITLE
Firmatario del certificato

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#687]
I dati di controllo della richiesta di un certificato contengono i tag cognomeUffAnagrafe e nomeUffAnagrafe, obbligatori, questi dati sono stampati in fondo al certificato. Risulta possibile valorizzare questi campi con dati diversi da quelli del cognome e nome dell'utente registrato che invia la richiesta. In altre parole l'utente Filipazzi Bruno manda una richiesta di certificazione con cognome/nome Rossi Mario. Ci sono contesti comunali in cui la certificazione cartacea tradizionale riporta la firma di chi ha la delega a sottoscrivere i certificati e che non corrisponde con l'operatore che materialmente ha stampato il foglio. Non mi ero ancora accorto che ANPR permette di replicare questo comportamento, e suppongo sia lecito, ne chiedo cortesemente conferma. Grazie.
Filipazzi  - Maggioli

**Comment by gcarbonin** [comment]
E' possibile indicare una persona diversa da quella in sessione (anche nei WS). Questa persona deve essere l'ufficiale di anagrafe

**Comment by bfilipazzi** [comment]
Grazie.
Filipazzi - Maggioli
