### ISSUE TITLE
Revisione notifiche per i comuni - dettagli tecnici

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#689]
Il colloquio tra ANPR e Comune che espone l’endpoin avviene  tramite il protocollo TLS (1.2), con l’utilizzo del solo certificato lato Comune (Server)
Il certificato digitale X509, utilizzato per la configurazione del protocollo TLS da parte del Comune potrà essere emesso da una qualsiasi CA pubblica riconosciuta e dovrà avere nel CN (Common Name) l’hostname dell’endpoint stesso.
Il Web Service dovrà essere realizzato secondo il formato WSDL già distribuiti con le specifiche tecniche di ANPR, disponibili nel portale informativo www.anpr.interno.it. Il contenuto del messaggio che verrà recapitato al Comune, prevede la firma del SOAP Body utilizzando il meccanismo della WS-Security XMLDSIG (https://www.w3.org/TR/xmldsig-core/). 
Il certificato digitale X509 da utilizzare per la verifica della firma del messaggio sarà quello del Servizio ANPR, prodotto dalla CA ANPR e distribuito ai comuni tramite sito web nell’area autenticata.
Il body della notifica è costituito, come è noto, da due parti:
•         testataNotifica che contiene il codice ISTAT del comune destinatario;
•         contenuto che contiene i dati della notifica (variabile in funzione del tipo di notifica indicato in testata notifica).
La parte “contenuto”, in formato xbase64, è cifrata con la chiave pubblica del comune destinatario (certificato nnnnnn-CO-9999) utilizzando l’algoritmo di cifratura “http://www.w3.org/2001/04/xmlenc#aes256-cbc”.
Alla ricezione della notifica, il sistema destinatario dovrà eseguire le seguenti operazioni:
•         verifica della firma del messaggio;
•         decifratura del contenuto, utilizzando la chiave privata del comune di destinazione, ricavato da testataNotifica.

Il dettaglio delle specifiche è presente nel sito www.anpr.interno.it
 Specifiche di interfaccia dei servizi di ANPR per i comuni – documento generale (§6.2 e §23) (#403 )

**Comment by mccalv** [comment]
Aggiungo forse una spiegazione meno tecnica. Abbiamo offerto questa funzionalità per consentire di avere un sistema più flessibile di dispatch delle notifiche ai comuni e che eviti di avere un end point (e quindi un consumer) per ogni comune. 

Un fornitore può quindi, secondo questa impostazione, attraverso il codice istat del comune che legge nella testata, invocare e allineare in modalità passiva il db locale relativo. 
Questo consente quindi di avere degli end point delle notifiche che possano essere logicamente e fisicamente disaccoppiati  dai singoli DB comunali e fungere da hub.
