### ISSUE TITLE
[5008] Web Service - istituzione convivenza di fatto

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#69]
Comune di Venezia, ambiente di test, 31.03.2017

Stiamo cercando di istituire una convivenza di fatto ma riceviamo sempre l'errore:
<listaErrori>
      <errore>
        <codiceErroreAnomalia>EN266</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>E&apos; obbligatorio specificare i dati della convivenza di fatto</testoErroreAnomalia>
      </errore>
    </listaErrori>

I dati della convivenza di fatto ci risultano impostati e l'xml è valido.

operazione  ANPR 113960 (IDANPR)
Su soggetto 5149780 (IDANPR)

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
Nella richiesta che arriva al sistema (di pre-subentro e non di test) è indicato come tipo mutazione "convivenza di fatto" ma i dati della convivenza non ci sono.

**Comment by TizianaTesta** [comment]
abbiamo oscurato i dati delle persone

<?xml version="1.0" encoding="UTF-8"?>
<n1:Richiesta5008 xmlns:n1="http://sogei.it/ANPR/5000mutazione" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sogei.it/ANPR/5000mutazione">
  <testataRichiesta>
    <idOperazioneComune>6212</idOperazioneComune>
    <codMittente>027042</codMittente>
    <codDestinatario>ANPR00</codDestinatario>
    <operazioneRichiesta>5008</operazioneRichiesta>
    <dataOraRichiesta>2017-03-31T15:16:54Z</dataOraRichiesta>
    <tipoOperazione>C</tipoOperazione>
    <tipoInvio>PRE_SUB</tipoInvio>
    <dataDecorrenza>2017-03-31</dataDecorrenza>
    <nomeApplicativo>ASCOTWEB</nomeApplicativo>
    <versioneApplicativo>15.03.0000</versioneApplicativo>
    <fornitoreApplicativo>ASCOTWEBFVG</fornitoreApplicativo>
  </testataRichiesta>
  <generalitaPerRicerca>
    <codiceFiscale>
      <codFiscale>XXXXXX95R43L736X</codFiscale>
      <validitaCF>1</validitaCF>
    </codiceFiscale>
    <cognome>XXXXXX</cognome>
    <nome>XXXXXX</nome>
    <sesso>F</sesso>
    <dataNascita>1995-10-03+01:00</dataNascita>
    <luogoNascita>
      <comune>
        <nomeComune>VENEZIA</nomeComune>
        <codiceIstat>027042</codiceIstat>
        <siglaProvinciaIstat>VE</siglaProvinciaIstat>
      </comune>
    </luogoNascita>
    <idSchedaSoggettoComune>
      <idSchedaSoggettoComuneIstat>027042</idSchedaSoggettoComuneIstat>
      <idSchedaSoggetto>5028485</idSchedaSoggetto>
    </idSchedaSoggettoComune>
    <idSchedaSoggettoANPR>5149780</idSchedaSoggettoANPR>
  </generalitaPerRicerca>
  <generalitaDaModificare>
    <generalita>
      <codiceFiscale>
        <codFiscale>XXXXXX95R43L736X</codFiscale>
        <validitaCF>1</validitaCF>
        <dataAttribuzioneValidita>2015-02-27</dataAttribuzioneValidita>
      </codiceFiscale>
      <cognome>XXXXXXX</cognome>
      <nome>XXXX</nome>
      <sesso>F</sesso>
      <dataNascita>1995-10-03</dataNascita>
      <luogoNascita>
        <comune>
          <nomeComune>VENEZIA</nomeComune>
          <codiceIstat>027042</codiceIstat>
          <siglaProvinciaIstat>VE</siglaProvinciaIstat>
        </comune>
      </luogoNascita>
      <idSchedaSoggettoANPR>5149780</idSchedaSoggettoANPR>
    </generalita>
    <attoNascita>
      <comuneRegistrazione>
        <nomeComune>VENEZIA</nomeComune>
        <codiceIstat>027042</codiceIstat>
        <siglaProvinciaIstat>VE</siglaProvinciaIstat>
      </comuneRegistrazione>
      <ufficioMunicipio>8</ufficioMunicipio>
      <anno>1995</anno>
      <parte>1</parte>
      <serie>A</serie>
      <numeroAtto>602</numeroAtto>
      <trascritto>0</trascritto>
    </attoNascita>
    <attributiSoggetto>
      <senzaFissaDimora>N</senzaFissaDimora>
      <soggettoCertificabile>2</soggettoCertificabile>
    </attributiSoggetto>
  </generalitaDaModificare>
  <statoCivile>
    <statoCivile>1</statoCivile>
  </statoCivile>
  <paternita>
    <generalita>
      <cognome>XXXXX</cognome>
      <nome>XXXXXX</nome>
    </generalita>
  </paternita>
  <maternita>
    <generalita>
      <cognome>XXXX</cognome>
      <nome>XXXXX</nome>
    </generalita>
  </maternita>
  <cittadinanza>
    <descrizioneStato>ITALIA</descrizioneStato>
    <codiceStato>100</codiceStato>
  </cittadinanza>
  <convivenzaDiFatto>
    <convivente>
      <codiceFiscale>
        <codFiscale>XXXXXX66C62A083X</codFiscale>
        <validitaCF>1</validitaCF>
        <dataAttribuzioneValidita>2015-02-27</dataAttribuzioneValidita>
      </codiceFiscale>
      <cognome>XXX</cognome>
      <nome>XXX</nome>
      <sesso>F</sesso>
      <dataNascita>1966-03-22</dataNascita>
      <luogoNascita>
        <comune>
          <nomeComune>AGORDO</nomeComune>
          <codiceIstat>025001</codiceIstat>
          <siglaProvinciaIstat>BL</siglaProvinciaIstat>
        </comune>
      </luogoNascita>
      <idSchedaSoggettoANPR>5149782</idSchedaSoggettoANPR>
    </convivente>
    <cittadinanza>
      <descrizioneStato>ITALIA</descrizioneStato>
      <codiceStato>100</codiceStato>
    </cittadinanza>
    <contrattoStipula>
      <data>2017-01-01</data>
      <dataNotifica>2017-01-01</dataNotifica>
      <dataDocumento>2017-01-01</dataDocumento>
      <protocollo>asdsfasd</protocollo>
      <luogoEvento>
        <comune>
          <nomeComune>AGLIE&apos;</nomeComune>
          <codiceIstat>001001</codiceIstat>
          <siglaProvinciaIstat>TO</siglaProvinciaIstat>
        </comune>
      </luogoEvento>
      <professionista>sadfasdfasf</professionista>
      <comuneRegistrazione>
        <nomeComune>AGLIE&apos;</nomeComune>
        <codiceIstat>001001</codiceIstat>
        <siglaProvinciaIstat>TO</siglaProvinciaIstat>
      </comuneRegistrazione>
    </contrattoStipula>
    <ordineConvivenza>1</ordineConvivenza>
  </convivenzaDiFatto>
   <datiControllo>
    <tipoMutazione>16</tipoMutazione>
  </datiControllo>
</n1:Richiesta5008>

**Comment by TizianaTesta** [comment]
[xml convivenze di fatto.txt](https://github.com/italia/anpr/files/890191/xml.convivenze.di.fatto.txt)

**Comment by gcarbonin** [comment]
Confermo che la richiesta che riceviamo non contiene i dati della convivenza.

**Comment by TizianaTesta** [comment]
Sarebbe in grado di inviarci la richiesta così come arriva a voi?

**Comment by gcarbonin** [comment]
La potete prendere dalla applicazione web Utilità e notifiche Monitoraggio operazioni
