### ISSUE TITLE
Errore EN425 - mancata rettifica dati subentro con ws [5014] 

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#690]
Buon giorno,
continuiamo ad avere problemi con l'errore in oggetto, quando tentiamo di effettuare una mutazione di indirizzo (ws 5001 e 5005) di individui trasmessi nell'ambiente di test con il file di subentro.
Dalla discussione sviluppata nella issue #493, e anche da quanto abbiamo letto nella issue #593, ci era sembrato di capire che il problema fosse "un caso di posizione conferita in subentro quando alcune date non erano presenti (data di iscrizione nel comune in particolare)", ossia la mancata valorizzazione nel file di subentro del campo '_dataPrimaIscrizioneComune_' del blocco '_generalitaSubIscr_', informazione prevista nelle specifiche del tracciato di subentro solo successivamente al nostro invio e valorizzata in automatico con la data di validazione del file di subentro.
Abbiamo pertanto utilizzato il ws 5014, che nella sua ultima versione prevede la possibilità di rettificare il valore di tale campo; l'operazione è andata a buon fine (id operazione comune 4846) e nella response il campo è stato valorizzato con la data da noi assegnata, in questo caso la data di decorrenza della residenza dell'individuo (12-01-2010). 
Il successivo tentativo di effettuare una mutazione dell'indirizzo della famiglia col ws 5001 non è andato però a buon fine (id operazione comune 4848), riproponendo lo stesso errore EN425 "La residenza del soggetto con ID ANPR 444804 non puo' essere variata in quanto la data di decorrenza residenza 12-01-2010 risulta precedente a quella di iscrizione APR del soggetto 29-01-2016". 
Chiediamo pertanto se l'operazione effettuata col ws 5014 sia realmente andata a buon fine, oppure se il campo interessato dal controllo che fa scattare l'errore non sia in realtà quello rettificato, ossia '_dataPrimaIscrizioneComune_'.
Il test è stato effettuato in data 25/05/2018, in ambiente di test,  per il comune pilota Teramo.
Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato l'operazione 5014 effettuata e abbiamo riscontrato un errore nell'esito restituito. Avviseremo quando possibile riprovare

**Comment by asqueglia** [comment]
E' possibile ripetere l'operazione 5014 per l'aggiornamento delle date e successivamente il 5001. Grazie per la segnalazione

**Comment by Amucciarelli74** [comment]
Salve,
abbiamo riprovato ad eseguire l'operazione 5014 ed in effetti, inviando gli stessi dati, abbiamo ottenuto questa volta in risposta un messaggio di errore (codice ES127) da cui abbiamo individuato l'esistenza di una ulteriore incongruenza, nella data decorrenza di appartenenza alla famiglia dell'individuo comunicata nel file di subentro ('_dataDecorrenza_' del blocco '_legameSoggetto_'). Inserendo nella request la richiesta di rettifica anche per questa data, insieme alla '_dataPrimaIscrizioneComune_', l'operazione 5014 è andata a buon fine, e successivamente è stato possibile completare con successo anche la mutazione di indirizzo per l'individuo.
Se possiamo suggerire una miglioria, il messaggio di errore ottenuto in caso di esito negativo dell'operazione 5014, "_Data prima iscrizione del soggetto xxx deve essere minore o uguale della data decorrenza residenza e della data ultimo aggiornamento e della data ingresso in famiglia_" non indica quale sia o quali siano le date non congruenti tra quelle indicate, e per accertarsi di un'incongruenza, ad esempio, con la data di ultimo aggiornamento , è necessario consultare il file di subentro, in quanto il campo '_dataUltimoAggiornamento_' non è consultabile da WA o dal WS 3002.
Il test è stato effettuato in data 30/05/2018, in ambiente di test, per il comune pilota Teramo.
Giuseppe Mucciarelli, TINN srl.

**Comment by asqueglia** [comment]
Grazie valuteremo il suggerimento per il messaggio di errore restituito. Buona giornata
