### ISSUE TITLE
Reiscrizione da irreperibilità

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#694]
Non riusciamo ad istruire una pratica di iscrizione per soggetto cancellato da Anpr per irreperibilità.
Dalla web app abbiamo provato a fare un'iscrizione per altri motivi, ma al momento della ricerca dell'individuo non ci consente di selezionarlo (non appare la lentina in fondo alla riga).
Comune di Altamura. Codice identificativo ANPR 18903444

**Comment by frmariani** [comment]
per l'iscrizione di un soggetto tramite web app,  la ricerca del soggetto non deve essere effettuata; nella pagina di inserimento dei dati anagrafici, tra gli altri dati richiesti, deve inserire il precedente identificativo anpr

**Comment by Finalmentesubentrati** [comment]
Grazie. Sistemato.
