### ISSUE TITLE
[ws] testataRichiesta: versioneApplicativo

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#696]
ambiente di TEST - comune di FAENZA

abbiamo tentato di inserire una data nel campo versioneApplicativo della testataRichiesta.
la barra di separazione tra gg/mm/aaaa non viene segnalata come carattere non valido, ma l'operazione va in errore col messaggio generico:
999 - E - Operazione non effettuabile
(rif. idOperazioneComune 2018600252)

l'eliminazione della '/' ha permesso il buon esito dell'operazione.
giusto per conoscenza, se ritenete opportuno di gestire diversamente l'errore...

Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Grazie della segnalazione. Nell'ambito della revisione delle retrizioni XSD pubblicate in precedenza #617, modificheremo anche i valori ammessi per il campo in testata valoreApplicativo per accettare gli stessi valori del campo fornitoreApplicativo (pertanto il carattere / non sarà ammesso)  : numeri, lettere, trattino, spazio, punto,
