### ISSUE TITLE
Anomalia in variazione nome

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#697]
Sto tentando di fare il cambio di nome e cognome di un nostro soggetto residente con codice 19082364. Esce l'errore: 
"EAM91 - Richiesta incongruente - soggetto NON marcato ANPR".

Come posso risolverlo?

**Comment by azabatta** [comment]
Buongiorno, 
il cittadino è presente in ANPR con codice fiscale validato ma non allineato con Agenzia Entrate. Inoltre il codice fiscale risultante dalla variazione dei dati anagrafici è già stato assegnato da Agenzia Entrate ma non è collegato al precedente.
E' necessario quindi utilizzare la funzionalità "Risoluzione disallineamenti con Agenzia Entrate " (sezione "Utilità e notifiche" del sito web di ANPR). L’operazione  si utilizza una prima volta per allineare i dati tra ANPR ed AE ed una seconda volta per  collegare i due codici  fiscali (quello presente in ANPR e quello presente solo in AE  che riporta i dati anagrafici del cittadino corretti).
