### ISSUE TITLE
[ws] Cambio di Abitazione da annullare post-subentro

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#698]
ambiente di PRODUZIONE - comune di SAN DONATO MILANESE

abbiamo due casi di soggetti, passati al subentro con dati di residenza aggiornati, ma che dopo il subentro, a causa degli accertamenti negativi, devono subire il ripristino anagrafico.

la necessità è quella di ripristinare una dataDecorrenzaResidenza ed un indirizzo precedente rispetto a quello che attualmente è presente in ANPR.
abbiamo tentato di usare il servizio 5014 per retro-datare almeno la dataDecorrenza, ma il web-service risponde con l'errore:
```
<errore>
  <codiceErroreAnomalia>EN414</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Rettifica non permessa in quanto la data di decorrenza residenza e' presente e congruente</testoErroreAnomalia>
</errore>
```

trattandosi di un cambio di abitazione interno, come ci suggerite di procedere?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
potete utilizzare il servizio 5001/5005 con tipo mutazione 6 Ripristino residenza post subentro;
non avendo indicato i soggetti non ho potuto verificare la fattibilità dell'operazione:
i soggetti non devono aver subito mutazione dopo il subentro e la data di ripristino deve essere compresa tra la data di prima iscrizione nel comune e la data del subentro.
