### ISSUE TITLE
[5008] Rettifica Data di Nascita - Errore EAM93

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#699]
ambiente di PRODUZIONE - comune di FAENZA

il caso è quello di un soggetto che attualmente presenta il codice fiscale numerico si in ANPR che in SIATEL (idSchedaSoggetto 19149202)

la necessità è quella di "correggere" la data di nascita.

la comunicazione attraverso la quale si tenta questa mutazione ritorna il seguente errore:
```
<errore>
  <codiceErroreAnomalia>EAM93</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Variazione non consentita per superamento numero campi variati</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018011741)

si tratta di una mutazione 5008, dove tra le generalitaDaModificare è stata variata solo la data di nascita.
i datiControllo sono così strutturati:
```
<datiControllo>
  <tipoMutazione>01</tipoMutazione>
  <gestioneCF>0</gestioneCF>
</datiControllo>
```
(si è tentato anche l'impostazione del gestioneCF a '1', considerata la tipologia dell'attuale codice fiscale, ma scatta l'errore EN491 - idOperazioneComune 2018011754)

come occorre procedere per perfezionare questa mutazione?

grazie
Alessandro Monopoli ADS

**Comment by azabatta** [comment]
Buongiorno, 
abbiamo chiesto una verifica ai colleghi di Agenzia Entrate:  la problematica non dovrebbe più presentarsi. 
E' possibile riprovare?
Grazie

**Comment by AMonopoliADS** [comment]
adesso il web-service restituisce questo errore:
```
<errore>
  <codiceErroreAnomalia>AEE95</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Operazione non effettuabile </testoErroreAnomalia>
</errore>
```
(idOperazioneComune 2018011852)

**Comment by azabatta** [comment]
Buonasera, 
è stata effettuata un'ulteriore verifica: l’operazione è bloccata da Agenzia Entrate in quanto il codice fiscale numerico in questione è stato attribuito dai servizi utilizzati da Sportello Immigrazione/Ufficio per la Protezione Internazionale e pertanto non può essere modificato. 
Provvediamo ad informare il comune.
