### ISSUE TITLE
Campo Cognome limitato (CHAR (36))

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#7]
Per le generalità del coniuge c'è solo il campo COGNOME. Se anche lo si volesse usare per ospitare anche il NOME, la sua lunghezza, CHAR(36), è ESIGUA.

**Comment by gcarbonin** [comment]
"I dati previsti dal subentro sono esattamente quelli indicati dal DPCM 194/2014; a loro volta questi dati sono quelli necessari alla formazione dell'elenco unico degli elettori, motivo per il quale è stata istituita l'AIRE.  Di conseguenza, con riferimento ai singoli punti:
1) non  si indica registro/frazione
2)si indica soltanto il cognome
3)occorre riportare tutto l'identificativo, compreso FE.  Si ricorda che a valle del subentro, viene restituito un elenco degli identificativi attribuiti da ANPR ai soggetti conferiti. Sarebbe auspicabile l'utilizzo di questo identificativo,"
