### ISSUE TITLE
[5008] Web Service - istituzione di un'unione civile

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#70]
Comune di Venezia, ambiente di test, 31.03.2017

Stiamo cercando di istituire un'unione civile tramite servizio [5008] da web service.
Riceviamo sempre l'errore

<listaErrori>
      <errore>
        <codiceErroreAnomalia>EN268</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>E&apos; obbligatorio specificare i dati dell&apos; unione civile</testoErroreAnomalia>
      </errore>
    </listaErrori>

i dati sono impostati

Operazione 114006 (IDANPR)
soggetto 5167529 (IDANPR)

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
E' lo stesso problema della convivenza di fatti: i dati dell'unione civile non ci sono nella richiesta
