### ISSUE TITLE
[5012] Annullamento Mutazione - EN234

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#701]
ambiente di PRODUZIONE - comune di FAENZA

soggetto proveniente da comune subentrato (idSchedaSoggetto 23468379)

la mutazione da comune a comune (ws 5005) è andata a buon fine: idOperazioneComune 2018010869)
a seguire è stata fatta mutazione (ws 5008) per attivare il flag di certificabilità (idOperazioneComune 2018010871), andata a buon fine anche questa (seppure con un warning che non ci torna "EAM14
EAM14 - W - Richiesta incongruente - nessun campo variato")

in ogni caso, oggi il cliente si  trova nella necessità di dovere annullare entrambe le operazioni.

l'ultima in ordine cronologico (la mutazione 5008) non si riesce ad annullare a causa di questo errore:
```
<errore>
  <codiceErroreAnomalia>EN234</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Non e' possibile annullare una mutazione dei dati anagrafici. Effettuare una nuova mutazione.</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018011858)

considerato che, per quello che abbiamo verificato, non c'è stata modifica di dati anagrafici (se non degli attributiSoggetto\soggettoCertificabile...) come possiamo sbloccare la situazione?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
per il messaggio EAM14 abbiamo - forse... - capito che è un messaggio che arriva da AE, probabilmente a motivo del fatto che è stato attivato il gestioneCF a '0'.

**Comment by frmariani** [comment]
Purtroppo con l'operazione idanpr 5484676 (idOperazioneComune 2018010871), è stata effettuata una modifica dei dati anagrafici, in quanto avete modificato il luogo di nascita da "Macedonia" a "Repubblica di Macedonia"; come giustamente intuito, il diagnostico EAM14 è un messaggio di AE che considera la "Repubblica di Macedonia" un alias di "Macedonia" e pertanto ritiene che nessun campo sia stato variato.  Sicuramente possiamo pensare ad una evoluzione che tenga in considerazione questi casi particolari, ma al momento l'operazione sopra indicata non può essere annullata.

**Comment by frmariani** [comment]
le operazioni di modifica dei dati anagrafici non possono essere annullate
