### ISSUE TITLE
Cancellazione evento

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#702]
Dalla web app non riusciamo ad eliminare la mutazione famiglia n. 4718450 riferita ai due cittadini con ID 18868558 e 18868560.
L'errore ad entrami i cittadini è il seguente:
_**L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa**_

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
abbiamo eliminato l'anomalia, può riprovare

**Comment by Finalmentesubentrati** [comment]
ok. Potete chiudere il ticket
