### ISSUE TITLE
[5008] Matrimonio di conviventi di fatto

### ISSUE THREAD

**Issue by busaster** [italia/anpr#705]
Ambiente di test.
Con una chiamata 5008 voglio variare lo stato civile del soggetto id ANPR 4759988 coniugandolo in data 06/06/2018 con il soggetto id ANPR 9459901.
Id operazione 4759988
Vengo però bloccato dall'errore  "La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto "
Cercando con il servizio 3002 il soggetto 4759988 noto che la data ultimo legame non è impostata, com'è normale che sia essendo un soggetto caricato in ANPR prima dell'aggiunta di questa data.

Potete aiutarmi a risolvere il problema ?
Grazie

**Comment by frmariani** [comment]
immagino che ci sia un refuso, il soggetto di cui parliamo non è il 4759988, bensì idanpr 9460457.

stiamo verificando il problema

**Comment by frmariani** [comment]
i due soggetti hanno un legame di convivenza dal 18/05/2017, pertanto, prima dell'inserimento di un successivo matrimonio, il contratto di convivenza deve essere chiuso.
i dati obbligatori del servizio 5008 tipo mutazione  17 (risoluzione convivenza) sono: motivo risoluzione e data risoluzione; nel suo caso può inserire motivo 34 (matrimonio/unione) e la data del matrimonio.

**Comment by busaster** [comment]
Ho cessato con successo la convivenza di fatto in data 6/6&18 (id operazione ANPR 4763426) ma ho ancora il medesimo errore se tento di comunicare il matrimonio (id operazione ANPR 4763427)

**Comment by frmariani** [comment]
verifichiamo

**Comment by frmariani** [comment]
potete riprovare

**Comment by busaster** [comment]
ora ha funzionato correttamente.
Grazie
