### ISSUE TITLE
[5001] Mutazione codiceLegame - EF008

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#707]
In ambiente pre-subentro, abbiamo provato a cambiare il legame di un soggetto (non Intestatario) di una famiglia, utilizziamo il servizio 5001 con :
- elencoSoggettiFamiglia contenente SOLO il/i soggetto/i coinvolti nella rettifica di rapporto di parentela con l'IS della Fam di appartenenza:
- tipoMutazione = 2-composizione scheda
- tipoScheda = 1-scheda famiglia 

Abbiamo avuto risposta KO
EF008-Intestatario della scheda famiglia/convivenza assente

idOperazioneANPR=3581839
idOperazioneANPR=3602228

In questo caso, è necessario mandare tutta la famiglia con tutti componenti ?

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by rvinzani** [comment]
No, non è necessario mandare tutta la famiglia ma indicare sempre comunque l'intestatario
Saluti
Roberta Vinzani
