### ISSUE TITLE
Certificato con richiedente diverso dal soggetto - Identificazione

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#708]
Ambiente Produzione Id Operazione ANPR 5924271
L'operazione citata è il rilascio di un certificato, con richiedente diverso dal soggetto.
La richiesta viene evasa pur non contenendo i dati obbligatori del documento di identificazione del richiedente.
Trattandosi di richiedente compreso in ANPR e il cui idSchedaSoggettoANPR è dichiarato nella richiesta ho immaginato che ANPR cerchi nel proprio database gli estremi del documento.
E' una supposizione corretta?
Grazie. Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
si

**Comment by slastrucci** [comment]
Buongiorno,
il problema riportato da Filipazzi si è verificato sul portale di certificazione on-line realizzato dal Comune di Prato per tutti i comuni la provincia.
Il portale riporta un funzione specifica dedicata ai professioni (es. avvocati) e permette di richiedere un certificato di un soggetto terzo autenticandosi con SPID o CNS.
Trattandosi di un autenticazione forte mi sembra assurdo dover chiedere all'utilizzatore del servizio di digitare gli estremi di un documento di riconoscimento (che oltretutto non saremmo in grado di verificare).
E' possibile modificare servizio di ANPR in modo da poter indicare nella richiesta che l'autenticazione è avvenuta con SPID/CNS e quindi non è necessario indicare gli estremi del documento?

**Comment by gcarbonin** [comment]
Ci possiamo provare. Intanto verifico con il Ministero dell'Interno ma la risposta dovrebbe essere affermativa.

**Comment by slastrucci** [comment]
Ci sono novità su questo punto?

**Comment by gcarbonin** [comment]
Al momento no

**Comment by patriziasaggini** [comment]
Buongiorno, una soluzione per il problema segnalato potrebbe essere l’utilizzo dei metadati previsti in [questo documento di AGID](url
https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/tabella_attributi_idp_v1_0.pdf), in particolare relativi al documento di identità della persona che accede al servizio.
Infatti, tutti i possessori di un’identità SPID debbono dichiarare i dati del proprio documento, che - previa richiesta in fase di attivazione del servizio - possono rientrare tra i dati utilizzati per l’accesso al servizio stesso.

**Comment by gcarbonin** [comment]
Per l'accesso tramite SPID o CIE, non non ci sono problemi in quanto:

- SPId con le modalità indicate da Patrizia consente di ricavare gli estremi del documento di identità;
- CIE è il documento di identità e dal certificato è possibile ricavare tutte le informazioni necessarie.

In entrambi i casi, il fornitore del SW del portale del comune si farà carico di acquisire tutte le  informazioni e riportarle nella richiesta 6001.
Per accesso tramite CNS stiamo vedendo come fare.

**Comment by slastrucci** [comment]
Per quanto riguarda il recupero degli estremi del documento d'identità dai metadati di SPID mi sembra che la soluzione proposta non risolva a pieno il problema perchè i documenti presentati al momento della richiesta di SPID potrebbero essere obsoleti e già scaduti.

**Comment by patriziasaggini** [comment]
Mi risulta che il gestore di identità ha l’obbligo di chiedere i riferimenti del nuovo documento alla data di scadenza di quello presentato al momento dell’autenticazione, quindi i dati dovrebbero essere sufficientemente aggiornati.

**Comment by patriziasaggini** [comment]
Con la mia identità Spid - con Poste Italiane - è successo, per cui posso confermare!

**Comment by rvinzani** [comment]
Come riportato dall'articolo 64 del CAD l’autenticazione SPID sostituisce la scansione della carta d’identità

**Comment by rvinzani** [comment]
Chiudo la issue in quanto non necessario alcun intervento. In caso di richiesta di ulteriori chiarimenti si prega di aprire un'altra issue facendo riferimento a questa stessa

**Comment by rvinzani** [comment]
Chiudo la issue in quanto non necessario alcun intervento. In caso di richiesta di ulteriori chiarimenti si prega di aprire un'altra issue facendo riferimento a questa stessa
