### ISSUE TITLE
Subentro ANPR - collegamento dati tra coniugi

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#71]
Comune di Venezia, ambiente di test, 03.04.2017

Abbiamo problemi a fare operazioni di variazione/rettifica dati di stato civile quando ci sono due coniugi residenti nel comune ma che in Anpr non risultano collegati.
Ci viene restituito l'errore: Alla data 21-12-1970 il soggetto *************** risulta gia' coniugato o unito civilmente con un altro soggetto

In fase di subentro i coniugi risultano collegati tramite identificativo del comune, ma non sono stati collegati in ANPR con identificativo ANPR 

Può farci sapere se il collegamento tra coniugi in ANPR è stato previsto e magari implementato successivamente al subentro di Venezia?

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
Possiamo verificare se mi manda gli identificativi del comune delle persone interessate. I dati sono stati abbinati ma su Venezia ci sono pochissime corrispondenze.

**Comment by TizianaTesta** [comment]
ecco gli identificativi:
Comune di Venezia,
ambiente pre-subentro
identificativi ANPR delle due persone 5268090   e    5019916

**Comment by gcarbonin** [comment]
5019916 è residente; il coniuge è iscritto all'AIRE. Quando si predispone il file di subentro AIRE, l'identificativo della persona del comune viene ricoperta con quello che assegna AnagAire. La moglie, pertanto, è entrata con il subentro con id E1991-005709.
