### ISSUE TITLE
PIEMONTE D'ISTRIA

### ISSUE THREAD

**Issue by UpiTorino** [italia/anpr#711]
Buongiorno
la frazione del comune di GRISIGNANA (PL) denominata PIEMONTE D'ISTRIA  è presente in A.E. come comune, ma non lo è sulla tabella comuni di ANPR.
Abbiamo cittadini i cui atti di nascita, trascritti in questo comune, riportano come comune nascita PIEMONTE D'ISTRIA: si potrebbe inserire anche se non si tratta propriamente di un comune?
Grazie
Buona giornata
UPI

**Comment by gcarbonin** [comment]
Si esaminerà la questione anche con Istat

**Comment by rvinzani** [comment]
Chiudiamo la issue in quanto è possibile indicare un comune non valido alla data e Grisignana è stata inserita nella tabella ANPR. In caso siano necessarie ulteriori informazioni si prega di riaprire una nuova issue facendo riferimento a questa stessa
