### ISSUE TITLE
Certificato di residenza storico per subentrati 

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#712]
Mi scuso in anticipo se torno sull'argomento del certificato di residenza storico, argomento ampiamente discusso ma sul quale ho un dubbio.
In ambiente di test di un comune subentrato in ottobre 2017 ottengo questo risultato con la WebApp (Protocollo ANPR 4741130 - ho camuffato le descrizioni, le date sono reali):

Risulta iscritta con i seguenti dati:
Comune di XXXXXXXXX(MI) dal 30/03/2013
Indirizzo VIA YYYYYYYYYY N. 2 - Interno: 17 dal 24/06/2017

Domando se si deve considerare corretto questo documento, che dovrebbe elencare gli indirizzi di residenza a partire dall'iscrizione anagrafica, cosa impossibile vista la mancanza di informazioni precedenti che si ricontra anche leggendo il documento: è iscritto dal 2013 e il suo indirizzo decorre dal 2017.
Non dovrebbe ANPR limitarsi per persone iscritte col subentro a produrre il documento quando le date di decorrenza iscrizione e decorrenza indirizzo coincidono? 
Grazie. Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Possiamo anche inserire il controllo ma occorre una valutazione: così il certificato esce e sta al comune valutare se integrarlo o meno; con il controllo non esce ed il comune si troverebbe nella impossibilità di capire come procedere. Per quanti controlli possiamo mettere, infatti, i comuni vanno sensibilizzati su un uso corretto dei certificati storici che sono completi sicuramente per le persone iscritte dopo il subentro e per i movimenti successivi al subentro; in tutti gli altri casi uno storico di residenza deve essere integrato con i dati del comune (per questo esiste la richiesta dati del certificato).

**Comment by bfilipazzi** [comment]
Sono d'accordo con lei. Il nostro gestionale per il caso in esempio dopo aver chiesto ad ANPR i dati, li integra con quelli locali ante subentro mancanti in ANPR, e produce un proprio documento.
Questo documento integrato è diverso nel contenuto da quello prodotto con la WA appunto perché stampa anche un precedente indirizzo.
Il gestionale decide da sé se ricorrere alla soluzione integrata oppure se ANPR è in grado di produrre il documento completo di tutte le notizie, in base alle date.
Il mio dubbio sta nella differenza di contenuto, per casi come quello descritto, fra il certificato prodotto dal gestionale e quello prodotto dalla WA.
Grazie. Filipazzi - Maggioli

**Comment by MarcoMigliori** [comment]
@Filipazzi: supponiamo una persona iscritta in un Comune "tipico" dal 1970. 
Il gestionale produce un certificato simile a quello ANPR riportante per esempio:

Risulta iscritta con i seguenti dati:
Comune di XXXXXXXXX(MI) dal 01/01/1970
Indirizzo VIA YYYYYYYYYY N. 2 - Interno: 17 dal 02/02/1992

Questo perchè mancano nel gestionale (se il Comune non li ha inseriti), dati storici precedenti.
Il caso di ANPR è più eclatante perchè recente, ma tutto sommato credo sia più conveniente vista la varietà dei Comuni, che ANPR lo produca.

**Comment by MarcoMigliori** [comment]
Ora capisco meglio la richiesta. Come parere personale, ritengo che il comportamento attuale di ANPR sia un compromesso adatto a più situazioni. Anche se senz'altro incompleto.
