### ISSUE TITLE
[WEBAPP] Elenco Operazioni

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#713]
In ambiente pre-subentro, abbiamo provato la cancellazione di un soggetto per Emigrazione.
idSchedaSoggettoANPR=38139391
Abbiamo avuto Risposta (negativa), ma l'operazione non è visibile da WEBAPP nell'elenco operazioni del soggetto.
idOperazioneANPR=3584355

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
Vengono visualizzate soltanto le operazione concluse con esito positivo o con segnalazioni non bloccanti
