### ISSUE TITLE
[CANCELLAZIONI] 2001 e 2003

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#714]
Buongiorno,
consultando il servizio 3003 per ottenere i dati delle operazioni 2001 e 2003 (comune di Bistagno (AL)) noto che per i soggetti cancellati tra i dati restituiti non compaiono mai i dati della residenza, cittadinanza e legame.  E' un caso o una scelta?
Grazie

**Comment by Eduardo1977** [comment]
Scusate, chiarisco meglio il senso della domanda: 
La scelta di non restituire i dati della residenza, cittadinanza e legame perchè è stata fatta?  Da cosa dipende?

**Comment by azabatta** [comment]
La logica della gestione delle risposte dei ws 2001 e 2003 è la stessa che è alla base della gran parte dei ws di ANPR: sono restituite le sezioni presenti nella richiesta. 
Una diversa gestione comporterebbe un peggioramento dei tempi di risposta ed una maggiore dimensione della stessa. 
I dati completi restano sempre disponibili utilizzando i ws di consultazione sia della scheda individuale che della famiglia/ convivenza.
