### ISSUE TITLE
Improvviso Rejected by policy (by client) - Ambiente Test WS

### ISSUE THREAD

**Issue by busaster** [italia/anpr#715]
Buongiorno

imrpovvisamente da metà pomeriggio qualsiasi richiesta effettuiamo via WS all'ambiente di test ci risponde con l'eccezione SOAP "Rejected by policy. (from client)".
In allegato due payload SOAP di due nostra chiamate, una  funzionante eseguita alle 14:06 e una che fallisce delle 16:29.

In entrambe le chiamate IssueInstant della assertion viene passato in UTC : 2018-06-08T12:06:21.984Z nella chiamata funzionante delle 14:06 e e 2018-06-08T14:29:31.199Z in quella non funzionante delle 16:29.

Avete modificato qualcosa a livello server ?

Chiedo aiuto perché abbiamo tutte le attività di sviluppo e test su ANPR bloccate.

Grazie

[payload_funzionante_1406.xml.zip](https://github.com/italia/anpr/files/2084979/payload_funzionante_1406.xml.zip)
[payload_funzionante_1629.xml.zip](https://github.com/italia/anpr/files/2084980/payload_funzionante_1629.xml.zip)

**Comment by MarcoMigliori** [comment]
E' successo anche a noi, stesso periodo.

**Comment by rpapini** [comment]
Abbiamo anche noi lo stesso problema.

**Comment by mttfranci** [comment]
Salve, stiamo verificando la vostra segnalazione. 
Intanto sarebbe utile se poteste fornirci alcuni dettagli : 
@busaster , @MarcoMigliori , @rpapini  : Il problema riguarda sia test comuni che presubentro o uno solo di tali ambienti?
@busaster  : il contenuto del secondo payload (payload_funzionante_1629.xml) ci appare vuoto, è effettivamente questo che ottenete?

Grazie in anticipo.

**Comment by MarcoMigliori** [comment]
le nostre prove oggi pomeriggio esclusivamente da ambiente di test.

**Comment by busaster** [comment]
prove effettuate solo in test. il file delle1629 è vuoto per un mio errore, purtroppo non sono più in ufficio e non ho modo di mandarlo fino a lunedì mattina

**Comment by gcarbonin** [comment]
Si è trattato di un problema momentaneo di cui ci scusiamo, Dovrebbe essere tutto a posto

**Comment by MarcoMigliori** [comment]
Stamattina lavoriamo regolarmente, ritengo si possa chiudere.

**Comment by busaster** [comment]
Anche a noi funziona tutto correttamente quindi per me chiudiamo

**Comment by rpapini** [comment]
Anche noi stamattina lavoriamo regolarmente, ritengo si possa chiudere.


Il 08/06/2018 21:39, gcarbonin ha scritto:
