### ISSUE TITLE
[2001] Morte accertata di AIRE non IS - EN370

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#717]
In ambiente pre-subentro, abbiamo provato la cancellazione per morte accertata di un componente di una famiglia AIRE.
idOperazioneANPR=3614537
Risposta (negativa), EN370-Motivo cancellazione incongruente con il tipo soggetto

La Richiesta2001 è stata mandata con :
motivoCancellazione.tipoMotivoCancellazione=1 (Tab.28-MotCancAIRE: 1-Morte accertata)
datiControllo.ruoloSoggetto=2  (per 2=altro componente e non IS)

dataDecorrenza=2018-06-12          (la data di registrazione dell'evento di STCV)
datiDecesso.dataEvento=2018-01-02  (la data del decesso)

Non è molto escpilicito il significato del msg di errore.
A che cosa si riferisce "il tipo soggetto" ? (AIRE o nonAIRE ?)
Il motivoCancellazione="1"  significa "Morte Accertata" sia per nonAIRE (Tab.15) che AIRE (Tab.28)

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by ncapozzi** [comment]
Scusate, il campo è tipoMotivoCancellazioneAIRE

**Comment by pissardl** [comment]
OK, funziona.
