### ISSUE TITLE
[POSTAZIONE UTENTE] Installazione SmartCard e CertificatoPostazione su altro PC già utilizzato

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#718]
Buongiorno, da qualche tempo una delle tre postazioni attivate a Bistagno (AL) non riesce più a collegarsi ad ANPR. Nel browser compare messaggio di "Sito non sicuro" e non c'è modo di proseguire. Abbiamo fatto infinite prove per cercare di sbloccarlo ma senza successo. L'unica prova che ci manca è disinstallare SmartCard e CertificatoPostazione per reinstallarre daccapo. Se non dovesse funzionare neanche questo tentativo, è possibile installare su un altro PC già utilizzato da un altro utente ANPR? Oppure su un PC ci deve essere sempre e solo un utente? Grazie

**Comment by Eduardo1977** [comment]
Ovviamente, se potessimo avere assistenza da remoto per risolvere il problema sarebbe l'ideale. Grazie

**Comment by gcarbonin** [comment]
La contatterà il mio collega per l'assistenza da remoto

**Comment by Leonforte** [comment]
Buongiorno, è possibile richiedere l'emissione di un altro certififcato attraverso al console di sicurezza con un utente ALP (amministratore locale delle postazioni), fermo restando che se quello presente nella postazione non funzionante viene disinstallato può essee riutilizzato. Da normativa su un PC ci dovrebbe essere un solo certificato e l'accesso dalla stessa postazione può essere fatta da utenti diversi identificati con la SC. Se ci fonrito un indirizzo mail dal quale avete accesso dal pc che ha problemi ci possiamo collegare in remoto e verificare. saluti

**Comment by Eduardo1977** [comment]
Buongiorno @Leonforte, grazie per l'aiuto. La postazione che ha problemi è proprio quella dell'utente ALP.
Posso inviare i riferimenti della responsabile dell'Ufficio Anagrafe al tuo indirizzo di posta ?

**Comment by Leonforte** [comment]
La smart card el sindaco è risultata bloccata, sia PIN che PUK, quindi ne chiederemo una nuova noi d'ufficio. Invence con la SC della Dott.ssa Garbarino l'accesso è stato effettuato tramite firefox ma abbiamo dovuto caricare manualmente tra i disposzitivi di sicurezza un nuovo modulo PKCS#11 agganciando la dll c:\windows\system32\athenaCSP.dll. Saluti

**Comment by Eduardo1977** [comment]
Grazie
