### ISSUE TITLE
comune di "PERSONE"

### ISSUE THREAD

**Issue by StoroTN** [italia/anpr#719]
Ho riscontato che i dati relativi al comune  di "PERSONE" sono riportati nella documentazione tecnica ANPR come creato: 16/10/1920	cessato: 28/02/1929	denominazione: PERSONE e assegnato alla provincia di BS, mentre nella documentazione storica in mio possesso e da altre informazioni risultava appartenere  alla provincia di TN in quanto territorio austriaco fino alla prima guerra mondiale. Nella documentazione tecnica risulta che PERSONE è stato aggregato al comune di TURANO e successivamente rinominato in VALVESTINO ma solo in data 03/05/1934 è indicato il cambio di provincia da TN a BS.
Ritengo pertanto che il comune di PERSONE (soppresso prima del 1934) vada indicato come provincia di TN

Grazie
Zontini Dario 
anagrafe comune di Storo

**Comment by gcarbonin** [comment]
Buongiorno. Queste informazioni sono ricavate da Istat che fa cessare il comune nel 1929 e lo indica in provincia di Brescia, In precedenza apparteneva alla provincia "Venezia Tridentina". In ogni caso se ci sono provvedimenti ufficiali da cui si evince quanto da lei indicato, possiamo sottoporla a ISTAT.

**Comment by StoroTN** [comment]
Sono in possesso solo del certificato di nascita rilasciato dal comune di Valvestino (comune attuale) in cui mi indica che in quel periodo il comune era in provincia di Trento. Il periodo in cui apparteneva  alla provincia "Venezia Tridentina" con che sigla va indicato? Per analogia nella documentazione vedo che il comune di Storo confinante con PERSONE, nello stesso periodo apparteneva alla provincia "Venezia Tridentina"  ma è indicato con la sigla TN. 
Il R.D. N. 93 del 21/01/1923 istituisce la provincia di Trento con comprendendo il 4° circondario di Tione (a cui faceva riferimento anche PERSONE). 
REGIO DECRETO 31 dicembre 1928, n. 3304  (riporto il testo recuperato su Normattiva....
http://www.normattiva.it/atto/caricaDettaglioAtto?atto.dataPubblicazioneGazzetta=1929-02-13&atto.codiceRedazionale=028U3304&queryString=%3FmeseProvvedimento%3D%26formType%3Dricerca_semplice%26numeroArticolo%3D%26numeroProvvedimento%3D3304%26testo%3D%26giornoProvvedimento%3D%26annoProvvedimento%3D1928&currentPage=1

I comuni di Armo, Bollone, Magasa, Moerna, Persone e Turano sono riuniti in unico Comune con denominazione e capoluogo «Turano». ((1)) Le condizioni di tale riunione, ai sensi ed agli effetti dell'art. 118 della legge comunale e provinciale, testo unico 4 febbraio 1915, n. 148, saranno determinate dal prefetto di Trento, sentita la Giunta provinciale amministrativa. Ordiniamo che il presente decreto, munito del sigillo dello Stato, sia inserto nella raccolta ufficiale delle leggi e dei decreti del Regno d'Italia, mandando a chiunque spetti di osservarlo e di farlo osservare. Dato a Roma, addi' 31 dicembre 1928 - Anno VII VITTORIO EMANUELE. Mussolini. Visto, il Guardasigilli: Rocco. Registrato alla Corte dei conti, addi' 28 gennaio 1929 - Anno VII Atti del Governo, registro 280, foglio 240. - Sirovich. --------------- AGGIORNAMENTO (1) Il D.Lgs. del Capo Provvisorio dello Stato 20 agosto 1947, n. 965 ha disposto (con l'art. 1, comma 1) che "Il comune di Magasa, aggregato con regio decreto 31 dicembre 1928, n. 3304, al comune di Turano (Trento) - che con regio decreto 16 novembre 1931, n. 1528, assunse la denominazione di "Valvestino" e con il successivo regio decreto 15 marzo 1934, n. 586, fu assegnato dalla provincia di Trento a quella di Brescia - e' ricostituito con la circoscrizione preesistente all'entrata in vigore del decreto 31 dicembre 1928, n. 3304".

**Comment by gcarbonin** [comment]
Per ora rispondo soltanto alla domanda sulla provincia "Venezia Tridentina" : non ho trovato la sigla di questa provincia. Abbiamo verificato anche con istat e Agenzia delle Entrate e questa sigla non sembra esistere. Per altro se  fosse introdotta, tutti i sistemi si dovrebbero adeguare (pensi anche alle applicazioni bancarie). Per ora quindi lasciamo provincia di Trento.

**Comment by StoroTN** [comment]
sempre in relazione ai territori italiani acquisiti con la prima guerra mondiale, come devono essere gestite le province dei cittadini italiani nati  in territorio austriaco ad esempio nel 1914 (ma sarebbe più corretto dire nate prima dell'annessione avvenuta il 16/10/1920) e annesso all'Italia a fine prima  guerra mondiale? Uno esempio è il comune di PERSONE, ma ho casi anche con persone nate nel comune di STORO oppure LODRONE

**Comment by gcarbonin** [comment]
In teoria come nate all'estero. nella pratica avranno il codice fiscale con il codice catastale del comune italiano. Mettiamo quindi i dati come risultano al momento dell'annessione

**Comment by StoroTN** [comment]
Concordo con la soluzione, ma serve che nella tabella dei comuni italiani sia presente il comune (es. STORO) con una data di inizio precedente dell'annessione avvenuta il 16/10/1920. Proprio oggi dovevo fare una carta identità elettronica ad un cittadino nato nel 1919 e non trovo il relativo comune

**Comment by gcarbonin** [comment]
Questo non lo possiamo fare. Per la carta di identità elettronica il problema è in via di soluzione (entro fine anno). Suggerisco di utilizzare la stessa tolleranza che abbiamo introdotto sul comune di nascita in ANPR per evitare modifiche a documenti e codici fiscali: si dà per buono il comune di nascita (e relativa provincia) a condizione che esistano nella tabella storica dei comuni e alla coppia nome comune + provincia sia associato lo stesso codice catastale (Belfiore) presente nel codice fiscale.
