### ISSUE TITLE
[5008] Errore in conferma dati per i vedovi di cui non si conoscono i dati di matrimonio

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#72]
Comune di Pisa, Ambiente di Test, 03/04/2017.

Viene effettuata una iscrizione 1002 da un comune non subentrato per una persona vedova.
Nella trasmissione APR/4 del precedente comune non vengono indicati i dati del matrimonio ma esclusivamente i dati della vedovanza.
Viene effettuata la comunicazione 5008 per la conferma dati che però non va a buon fine, l'applicazione restituisce l'errore EN303: Il soggetto non è coniugato (idOperazioneANPR 450742).
Come possiamo comportarci in questi casi?
Grazie.
Luca Bonini APSystems

**Comment by gcarbonin** [comment]
E' necessario indicare almeno il cognome e il nome del coniuge e la data del matrimonio
