### ISSUE TITLE
Annullamento mutazione errore SP000

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#720]
Ambiente di test. Simulazione correzione errori.
Con id operazione 9639246, effetto mutazione dati/rettifica/maternità, correggendo nome maternità. Applico data decorrenza 15 aprile.
Simulo di essermi sbagliato nel fare la modifica, a imputare la data decorrenza. Se tento di annullare l'operazione mi resituisce errore:

> Tipo operazione non ammesso per il servizio (Codice: SP000)

Ho sbagliato qualche passaggio? Di che tipo di errore si tratta?

**Comment by frmariani** [comment]
Il servizio di annullamento mutazione NON accetta la R  nel tipo operazione della testata richiesta. 
Abbiamo verificato che c'è un refuso nella documentazione che sistemeremo quanto prima.
