### ISSUE TITLE
[6001] richiesta dati e tipo residenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#721]
Ambiente di test.
Chiamo il servizio 6001 con "tipoRichiesta=2" per ottenere i dati del certificato di residenza storico su un soggetto cui in precedenza ho cambiato residenza con una chiamata 5001 di tipo variazione toponomastica il 30/05/2018.

I dati di residenza che mi vengono restituiti però hanno tutti tipo indirizzo = 1, mentre mi aspettavo che l'indirizzo valido dal 30/05/2018 avesse tipo indirizzo 10.
ID ANPR operazione 6001 è 9643221.

Se eseguo il certificato con tipoRichiesta=1 , il pdf ritornato riporta correttamente la dicitura "(Aggiornamento ex artt. 44, 47 DPR 223/1989)" nell'indirizzo del 30/05/2018.

Potete verificare ? 
Grazie

**Comment by rnapoli1983** [comment]
Si è così.

Nel servizio 6001 la modifica testuale dell'indirizzo, per la variazione toponomastica, è stata realizzata
esclusivamente per la modalità "certificato" che produce per l'appunto un file pdf con testo.

Vista la necessità provvederemo quanto prima ad allineare anche la modalità "richiesta dati".

Grazie mille per la segnalazione.

**Comment by rnapoli1983** [comment]
Buongiorno le volevo comunicare che in ambiente di TEST è possibile provare la modifica che dovrebbe risolvere quanto da voi segnalato sul tipoIndirizzo, per la modalità "richiesta dati" del servizio di certificazione anagrafica 6001.

**Comment by busaster** [comment]
Ho verificato che il tipo residenza ora risulta corretto.
Grazie
