### ISSUE TITLE
[WEPAPP] Impossibilità di ricercare soggetti per  Identificativo scheda attribuito dal comune

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#723]
In ambiente pre-subentro, non è possibile effettuare ricerca dei soggetti per Numero Individuale da WEBAPP  (es.: R66351560 ).

La WEPAPP da Errore:
Il campo Identificativo scheda attribuito dal comune deve essere numerico 

Il campo "Identificativo scheda attribuito dal comune" dal form di Consultazione dalla WEBAPP accetta solo un numero ; anche se il tipo del campo "tipoIdSchedaSoggetto" è alfanumerico esteso, nel XSD.

```
<xs:simpleType name="tipoIdSchedaSoggetto">
	<xs:restriction base="xs:string">
		<xs:pattern value="([0-9a-zA-Z\-])*"/>
		<xs:minLength value="1"/>
		<xs:maxLength value="20"/>
	</xs:restriction>
</xs:simpleType>
```

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by pissardl** [comment]
Da WEBAPP
1/ Menu alto "Consultazione ed estrazione"
2/ Compilazione dei 2 campi dell'Identificativo comunale :
Identificativo scheda attribuito dal Comune:  R66351560 
Codice ISTAT Comune:  001272

3/ Click su botton "CONFERMA" per lanciare la ricerca

Errore restituita:
Il campo Identificativo scheda attribuito dal comune deve essere numerico

**Comment by rvinzani** [comment]
E' stato effettuato l'aggiornamento dell'applicazione web per consentire la consultazione anche a partire da un Identificativo scheda attribuito dal comune alfanumerico
