### ISSUE TITLE
Caratteri non consentiti in nome maternità

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#724]
Ambiente di produzione. id anpr 27299758
All'inserimento della pratica (prima di entrare in ANPR) è stato digitato per errore nel nome maternità  

 MANUELA

con uno spazio davanti al nome.

Tentando di fare la mutazione dati, riceviamo l'errore, senza poter proseguire:
_Il campo Nome in Maternita contiene dei caratteri non validi_

Il dato sembra quindi non correggibile da wa.

**Comment by gcarbonin** [comment]
Si deve procedere nel solito modo

**Comment by rvinzani** [comment]
E' possibile effettuare una revoca del dati di maternità (da web o invocando il servizio 5013) e successivamente riacquisirlo tramite servizio di mutazione tutti i dati 5008
