### ISSUE TITLE
[3002] Errore in risposta

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#726]
Buongiorno,
ho appena effettuato due chiamate al WS3002 (IdOperazioneComune: 1000556 e 1000557) ricevendo i dati correttamente nel primo caso mentre errore nel secondo. L'unica differenza tra le due chiamate è che "dataRiferimentoRichiesta" nel primo caso è 18/04/2018 mentre nel secondo è 19/04/2018 (il criterioRicerca è sempre sullo stesso "idSchedaSoggettoANPR"). Potreste verificare gentilmente? Grazie

**Comment by Eduardo1977** [comment]
Scusate, dimenticavo ... ambiente produzione di Bistagno(AL)

**Comment by gcarbonin** [comment]
Che errore ha ricevuto esattamente?

**Comment by Eduardo1977** [comment]
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (uri:"", local:"dataDecorrenzaLegame"). 
Expected elements are <{}tipoLegame>,<{}dataDecorrenza>,<{}codiceLegame>,<{}progressivoComponente>

**Comment by Eduardo1977** [comment]
Grazie
