### ISSUE TITLE
[5001] errore in mutazione relazioni di parentela

### ISSUE THREAD

**Issue by busaster** [italia/anpr#727]
Perugia - Ambiente di Produzione 

Usando il servizio A006 (operazione ID ANPR 4462830) abbiamo trasferito un soggetto IS di famiglia da APR ad AIRE con ingresso in famiglia AIRE esistente (10258288)
Operazione conclusa con successo.

Dopodichè con una chiamata al 5001 (operazione ID ANPR 11650771) tentiamo mutare la famiglia APR di provenienza (10249067) per far diventare intstatario uno dei componenti rimasti.
Veniamo però fermati dall'errore  EN482 : In caso di variazione intestatario scheda, la lista dei soggetti deve contenere anche il precedente intestatario con la nuova relazione di parentela

Non riusciamo a capire il problema. Come possiamo includere il precedente IS della famiglia se è già uscito dalla stessa ?

**Comment by ncapozzi** [comment]
Buongiorno,
la mutazione A006 ID ANPR 4462830 risulta annullata con id operazione 4463615 quindi attualmente il soggetto 21321977 risulta in Italia con la famiglia di provenienza di cui è anche intestatario.
Il controllo EN482  scatta perchè in caso di variazione intestatario scheda, la lista dei soggetti deve contenere anche il precedente intestatario con la nuova relazione di parentela se questo è presente
