### ISSUE TITLE
[3002] Consultazione codiceFiscale.dataAttribuzioneValidita

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#728]
In ambiente pre-subentro, effettuando delle consultazioni con criteriRicerca idSchedaSoggettoANPR
nella risposta del 3002 il campo codiceFiscale.dataAttribuzioneValidita 
non sembra mai valorizzato.

C'è un altro modo per consultare via WS tale informazione ?

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by azabatta** [comment]
Buongiorno, 
la data indicata non è presente in base informativa perché gli ambienti di TEST_COMUNI e PRESUBENTRO non sono collegati con i dati di esercizio di Agenzia Entrate (non è possibile replicare tutta la base dati reale dell'Anagrafe Tributaria in ambienti di test).
In questi ambienti i cittadini sono inseriti con CF non validato e di conseguenza  senza data  attribuzione validità. 
Fanno eccezione le procedure di elaborazione dei file di subentro in ambiente di PRESUBENTRO:  dovendo produrre degli elenchi di anomalie corrispondenti alla situazione effettiva dei cittadini,   per la validazione dei CF,  utilizzano la base dati di esercizio di Agenzia Entrate. 
In generale la risposta restituita dal ws 3002 prescinde dai criteri di selezione utilizzati per ricercare un cittadino: una volta individuato il soggetto le sezioni sono valorizzate sempre con le stesse modalità.

**Comment by pissardl** [comment]
In ambiente di Presubentro anche se consultiamo un soggetto su quale abbiamo appena effettuato la validazione del CF (da WEBAPP), il dato dataAttribuzioneValidita non viene restituito.

In ambiente di Produzione quel dato, 
verra sempre valorizzata su soggetti con validitaCF=1 ? 
verra valorizzata solo su soggetti con validitaCF=1 ?

**Comment by azabatta** [comment]
Sì, esatto. Negli ambienti di test si può simulare una posizione con CF validato effettuando un'iscrizione con richiesta di attribuzione CF.

**Comment by pissardl** [comment]
Ok, Grazie
