### ISSUE TITLE
anpr.interno.it - Documentazione Tecnica: XSD / WSDL

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#729]
segnalo che il link "Tracciati XSD e WSDL - rar" produce il download delle specifiche excel e non del .rar contenente xsd / wsdl aggiornati

**Comment by AMonopoliADS** [comment]
Ho visto che il link è stato aggiornato. Potete confermare la versione dei ws se sempre 4.0 o successiva?
Grazie

**Comment by gcarbonin** [comment]
Al momento la versione pubblicata è quella disponibile in tutti gli ambienti.
