### ISSUE TITLE
Blocco su ANPR

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#730]
Buongiorno,

Ambiente PRE SUBENTRO
alcuni comuni stanno ricevendo il seguente messaggio da questo pomeriggio
"Aborting...IdSede Attribute inconsistent with IdPostazione (from client)"

potete verificare?

Grazie

**Comment by mccalv** [comment]
@SAlberto potrebbe indicare il comune /fornitore?
Grazie

**Comment by gife67** [comment]
Buongiorno,
il problema è dovuto al fatto che abbiamo inserito dei controlli sull'esatta corrispondenza tra il Codice Istat presente nel campo IdSede e quello ricavato dai primi 6 caratteri dell'IdPostazione. Risulta che i Comuni che hanno nel codice Istat gli zeri iniziali questi, per alcuni Comune, vengono troncati (ex 018160 viene comunicato nell'IdSede come 18160). Se correggete questo comportamento le richieste andranno a buon fine.
