### ISSUE TITLE
[WEBAPP] [5008] Inserimento/Rinnovo Permesso Soggiorno ante subentro

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#731]
In ambiente pre-subentro, stiamo cercando di inserire il rinnovo di un permesso di soggiorno.
In questo caso, ci sembrava giusto impostare come dataDecorrenza la data di inizio validità del documento
Ma otteniamo sempre lo stesso errore quando tale data è anteriore alla data di subentro :

La data decorrenza 14-06-2018 dell'operazione non puo' essere inferiore alla data decorrenza 15-06-2018 dell'ultima operazione effettuata sui dati relativi a permesso di soggiorno (Codice: EN389)

Sia da WS-5008, che da WEBAPP (con Mutazione D'Ufficio o come Rettifica).

In questi casi, impostare la data di subentro potrebbe generare problemi sulla validità del documento o altro (certificazione)?

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
La data di inizio validità del documento è un attributo del documento stesso. La data di decorrenza da indicare corrisponde a quella nella quale il comune è venuto a conoscenza dell'informazione e deve essere comunque non inferiore alla data dell'ultima operazione effettuata sulla scheda.
