### ISSUE TITLE
[WEBAPP] decesso is e cambi relazione parentela

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#732]
Ambiente produzione. decesso id 27327118.
In famiglia c'è IS (deceduto), figlio (che diventa is), nuora (che diventa moglie), nipote (che diventa figlio).
Abbiamo dovuto utilizzare la webapp (id 11715433)  per un errore operatore, indicando il decesso . nella videata sono stati indicati anche i nuovi rel.par. e hanno anche variato manualmente il progressivo, io non mi sono accorto di errori di compilazione.
tuttavia alla conferma segnala errore che non sono stati assegnati i nuovi rapporti parentela.

mentre scrivo questo messaggio tentiamo operazione separata mutazione scheda per correggere rel.par. di nuovo oltre a cambiare il grado di parentela modifichiamo il progressivo, alla conferma da l'errore
_Inserire almeno un soggetto in elenco soggetti famiglia (Codice: EN223)_

riprovo senza modificare il progressivo, ma continua a dare lo stesso errore.

**Comment by frmariani** [comment]
Nel caso si volessero indicare sia il nuovo intestatario che le nuove relazioni di parentela con esso contestualmente al decesso dell'IS, devono essere selezionati tutti i soggetti da modificare: nella web app c'è un apposito flag da utilizzare ( "Seleziona Soggetto") nell'elenco dei soggetti;
lo stesso flag lo trova nella funzione di mutazione famiglia convivenza, composizione scheda.

**Comment by MarcoMigliori** [comment]
Non avevo visto la spunta, scusate. risolto.
