### ISSUE TITLE
[2011] Operazione non effettuabile 

### ISSUE THREAD

**Issue by busaster** [italia/anpr#734]
Ambiente di Test.
Cerco di annullare una cancellazione per morte di soggetto che era unito civilmente ma ottengo "999 Operazione non effettuabile".
ID op. ANPR : 11637875
Potete aiutarmi a capire come mai ?
Grazie

**Comment by mttfranci** [comment]
Ci scusiamo per il ritardo nella risposta. Stiamo verificando il problema e avviseremo quando sarà possibile riprovare.

**Comment by mttfranci** [comment]
In test comuni abbiamo apportato alcune modifiche agli annullamenti che potrebbero risolvere il problema.
Volete riprovare?

**Comment by busaster** [comment]
Ho appena riprovato ma l'errore rimane lo stesso "999 operazione non effettuabile".
L'operazione appena tentata ha id ANPR 12637956

**Comment by mttfranci** [comment]
Ci sono stati altri aggiornamento sugli annullamenti, potreste provare nuovamente?

**Comment by busaster** [comment]
Ora l'annullamento è stato completato con successo.
Grazie
