### ISSUE TITLE
Subentro Comune di CARLOFORTE (111010) - Sostituzione IP in emergenza

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#737]
Buongiorno, il Comune in oggetto, subentrato in data odierna, ha comunicato IP pubblico errato; si chiede vostro referente per comunicare IP corretto e procedere con l'avvio in subentro.

Grazie per la collaborazione.
Cordiali saluti
Christian O. - ADS

**Comment by cmigliardi** [comment]
l' IP  è stato abilitato  
cordiali saluti  
Cecilia
