### ISSUE TITLE
[1002] Iscrizione Cittadino Palestinese - Errore EC036

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#738]
ambiente di PRODUZIONE - comune di MALNATE (VA)

non si riesce a completare l'iscrizione di un cittadino palestinese.
su tutti i documenti (permesso di soggiorno, carta di identità elettronica) il soggetto presenta cittadinanza PSE.

si comunicano pertanto questi dati della cittadinanza:
```
<cittadinanza>
<descrizioneStato>TERRITORI DELL'AUTONOMIA PALESTINESE</descrizioneStato>
<codiceStato>324</codiceStato>
</cittadinanza>
```

ma il web-service risponde con questo errore:
EC036 - E - Stato estero cittadinanza 324 inesistente sulla tabella di riferimento
(rif. idOperazioneComune 2018001280)

nella tabella '2' pubblicata da ANPR, il codice 324 sembra utilizzabile solo ai fini della RESIDENZA (e non anche della CITTADINANZA e NASCITA).

come dovrebbe procedere il cliente per confermare quanto riportato nei documenti?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Sulla mail personale mi invii l'immagine del passaporto Poi ci attiviamo con il Ministero dell'Interno

**Comment by AMonopoliADS** [comment]
buongiorno.
c'è qualche novità sul nostro caso della cittadina palestinese?

grazie

**Comment by gcarbonin** [comment]
NO non ho avuto risposta ma ritentiamo in giornata

**Comment by gcarbonin** [comment]
Abbiamo abilitato il codice 324 anche per cittadinanza e nascita. Se riprovate dovrebbe essere tutto a posto.

**Comment by AMonopoliADS** [comment]
confermo che l'iscrizione adesso è andata a buon fine.
grazie
