### ISSUE TITLE
Web app - Ricerca Monitoraggio operazioni

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#74]
Da "Utilità e notifiche", "Monitoraggio operazioni" sembra non funzionare la ricerca per "identificativo comune", salvo non stia impostando un valore sbagliato.
Ad esempio, ricercando l'operazione 451216 impostando come unico parametro di ricerca il numeroPraticaComune B20170123, non viene reperito alcun risultato.
L'analoga ricerca effettuata per idOperazioneANPR 451216 invece restituisce il risultato.
Grazie, 
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino
Data test: 4/4/2017
Ambiente : dptest

**Comment by gcarbonin** [comment]
La ricerca puo' essere effettuata per idoperazioneanpr o per idoperazionecomune. Questo dato non è il numero di protocollo ma un identificativo utilizzato per i WS: questa ricerca non è utilizzabile per le operazioni effettuate via web. Si può estrarre per data, tipo operazione o idoperazioneanpr.
