### ISSUE TITLE
Variazione interni abitativi

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#741]
Un alloggio è stato diviso in due mini appartamenti. Risulta, pertanto,  necessario creare due interni (A e B) al fine di distinguerli. All'interno B fisserà la residenza una nuova famiglia mentre, all'interno A risiede un'altra famiglia che dimorava anche prima della divisione. Quest'ultima risulta registrata in anagrafe con l'indirizzo senza alcun interno e, quindi, è necessario inserire la lettera A accanto all'indirizzo di tutti i componenti familiari.
Qual è la procedura corretta?

**Comment by gcarbonin** [comment]
Mutazione della residenza del nucleo famigliare indicando l'interno
