### ISSUE TITLE
Comune Codroipo ambiente di Presubentro - certificazione e caratteri diacritici

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#744]
segnalazione.
Abbiamo effettuato da WEB APP  l'iscrizione  di una persona con caratteri sloveni nel campo nome.
Abbiamo emesso, sempre da web app, un certificato di stato di famiglia. 
I caratteri Š e Ž vengono correttamente riprodotti nel certificato, mentre è assente il carattere  Č .
Nella  consultazione dei dati i caratteri sono tutti visibili.

grazie

**Comment by INSIEL1** [comment]
idschedaANPR = 65417333

id operazione ANPR =  6384287

grazie

Rita Klingendrath
ASCOT Solutions
Innovation & Projects

Insiel S.p.A.
via San Francesco d'Assisi, 43
34133 - Trieste (TS) Italia
tel +39 040 3737482
mob +39 345 7962818
rita.klingendrath@insiel.it<mailto:rita.klingendrath@insiel.it>
www.insiel.it<http://www.insiel.it>

rispetta l’ambiente: se non ti è necessario non stampare questa mail
Da: gcarbonin [mailto:notifications@github.com]
Inviato: lunedì 2 luglio 2018 12:28
A: italia/anpr <anpr@noreply.github.com>
Cc: Klingendrath Rita <rita.klingendrath@insiel.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] Comune Codroipo ambiente di Presubentro - certificazione e caratteri diacritici (#744)


Potete indicarci l'id dell'operazione o della persona?

**Comment by gcarbonin** [comment]
Stiamo facendo alcune verifiche; si tratta probabilmente di un limite del font utilizzato

**Comment by rnapoli1983** [comment]
Potete riprovare ad emettere certificato per il soggetto con idschedaANPR = 65417333.

Ovviamente la problematica dovrebbe essere risolta in assoluto.

**Comment by INSIEL1** [comment]
Grazie ora  il certificato viene emesso con tutti caratteri diacritici.

Rita Klingendrath
ASCOT Solutions
Innovation & Projects

Insiel S.p.A.
via San Francesco d'Assisi, 43
34133 - Trieste (TS) Italia
tel +39 040 3737482
mob +39 345 7962818
rita.klingendrath@insiel.it<mailto:rita.klingendrath@insiel.it>
www.insiel.it<http://www.insiel.it>

rispetta l’ambiente: se non ti è necessario non stampare questa mail
Da: rnapoli1983 [mailto:notifications@github.com]
Inviato: giovedì 5 luglio 2018 11:10
A: italia/anpr <anpr@noreply.github.com>
Cc: Klingendrath Rita <rita.klingendrath@insiel.it>; Author <author@noreply.github.com>
Oggetto: Re: [italia/anpr] Comune Codroipo ambiente di Presubentro - certificazione e caratteri diacritici (#744)


Potete riprovare ad emettere certificato per il soggetto con idschedaANPR = 65417333.

Ovviamente la problematica dovrebbe essere risolta in assoluto.
