### ISSUE TITLE
[5005] Sono presenti piu' famiglie con lo stesso Identificativo scheda attribuito dal comune

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#745]
Buongiorno,
siamo in ambiente di pre-subentro, stiamo facendo una scissione per aggregazione di un individuo all'interno del comune. 

Facendo la chiamata 5005 otteniamo l'errore in oggetto (Codice errore EF062), ma accedendo dal portale se provo a cercare la famiglia con l'identificativo scheda mi trova l'intestatario della famiglia di destinazione.

Normalmente funziona, è la prima volta che riscontriamo questo tipo di problema.
L'idOperazioneANPR è il 6390010.

In attesa di un Vostro riscontro.
Ringrazio anticipatamente.

**Comment by asqueglia** [comment]
Buongiorno,
verificando la sua richiesta abbiamo riscontrato che è stata trasmessa una mutazione di residenza in famiglia esistente. La famiglia esistente è stata trasmessa con i soli identificativi comunali; abbiamo appurato che per il comune di SAREZZO esistono due famiglie aventi lo stesso numero scheda APR 20328; nello specifico gli id ANPR delle due famiglie sono 32993196 e 32993197. Questo è il motivo per cui scatta il controllo menzionato; in tal caso è necessario trasmettere l'identificativo ANPR della famiglia in cui si desidera far confluire il soggetto.
