### ISSUE TITLE
ws [3003] - consultazione operazioni AE

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#746]
Buon giorno,
stiamo effettuando dei test relativamente ai casi di cui al capitolo 12 del documento di specifiche (annullamenti ex-articolo 18 bis) e allo scopo abbiamo completato una immigrazione da comune non subentrato, registrando una nuova posizione in ANPR mediante il servizio 1002 e richiedendo contestualmente l'attribuzione del codice fiscale (id operazione comune 4930). 
Per poter effettuare il ripristino della posizione anagrafica (ws 2003), abbiamo effettuato una ricerca preliminare dell'operazione da cancellare con il ws 3003 (id operazione comune 4932), con esito positivo, ma l'xml ottenuto in risposta non è quello atteso. Avevamo effettuato una analoga operazione qualche tempo addietro (id operazione comune 2991) e confrontando le due risposte, abbiamo riscontrato che:

- Nel  blocco _elencoRisposte_, il campo _tipoOperazione_ riporta correttamente il valore 1002 (l'operazione di iscrizione ricercata), ma il campo _statoLavorazione_ ha il valore '6' che non è definito nel file di specifiche '3003Response.xlsx' (i valori indicati vanno da 1 a 5); 

- manca il secondo blocco _elencoRisposte_ in cui il campo _tipoOperazione_ dovrebbe contenere il  valore delle operazioni effettuate in AE ('AE01' nella risposta di cui sopra). 

Non abbiamo trovato nelle specifiche indicazioni di modifiche in tale senso, chiediamo pertanto se è in corso un aggiornamento del servizio in oggetto non ancora riportato nella documentazione, o se si tratta di una risposta generata da caratteristiche non corrette della richiesta.

Il test è stato effettuato in data 03/07/2018, in ambiente di test, per il comune pilota Teramo.

Giuseppe Mucciarelli, TINN srl.

**Comment by azabatta** [comment]
Buonasera, 
per la response del  servizio 3003  aggiorneremo la documentazione aggiungendo il valore    6  “richieste complete con esito positivo ma segnalazione di errori non bloccanti”. Grazie per la segnalazione.
Riguardo all’esclusione delle operazioni in AE  l’intervento è stato classificato come una correttiva;  queste operazioni (trattandosi di operazioni “interne” di ANPR) sono state escluse dall’elenco che riguarda operazioni effettuate dal comune.

**Comment by Amucciarelli74** [comment]
Buon giorno,
ok per l'aggiornamento della documentazione.
Per quello che riguarda la consultazione dell'operazione effettuata in AE, la sua utilità era legata al fatto di dover o meno procedere con la richiesta di annullamento di un codice fiscale precedentemente attribuito a seguito di una richiesta di iscrizione. 
Come è possibile a questo punto stabilire se effettuando un ripristino di posizione (o anche un annullamento di una iscrizione) è necessario richiedere anche l'annullamento del codice fiscale attribuito? E' sufficiente ad esempio consultare con il ws 3002 il valore del campo _dataAttribuzioneValidita_ del blocco _codiceFiscale_ dell'individuo, confrontandolo con la data di decorrenza dell'iscrizione che si sta annullando? O è possibile utilizzare qualche altro tipo o servizio di consultazione?

Giuseppe Mucciarelli, TINN srl.

**Comment by azabatta** [comment]
Buongiorno, 
sì esatto: è sufficiente la consultazione tramite 3002 del campo "dataAttribuzioneValidita" del tipo dato "codiceFiscale".

**Comment by Amucciarelli74** [comment]
Ok adesso è chiaro, a questo punto però vi poniamo un'altra domanda.
L'iscrizione in ANPR mediante il servizio 1002, nel caso di immigrazione da comune non subentrato, comporta in ambiente di test la richiesta di attribuzione del codice fiscale, al fine di popolare la base dati del corrispondente ambiente AE. Da specifiche è riportato poi che "_La richiesta di annullamento di un codice fiscale in precedenza attribuito può essere richiesta dal comune effettuando un annullamento di una iscrizione (servizio 1013)_" indicando nel campo annullamentoAttribuzione il valore “S”. 
Il ripristino della posizione anagrafica per annullamento ex-articolo 18 (ws 2003), ad esempio proprio nel caso di annullamento di un cambio di residenza da comune non subentrato a comune subentrato, non dovrebbe comportare anch'esso l'annullamento del codice fiscale attribuito? Il ws 2003, a differenza del ws 1013, non prevede infatti tale opzione e a cancellazione avvenuta, il codice fiscale è ancora presente nell'ambiente di test AE.
In generale, questo problema potrebbe porsi anche in ambiente "ufficiale"? potrebbero esserci dei casi in cui nel servizio 1002 possa essere necessario richiedere l'attribuzione del codice fiscale? come bisognerà agire poi in caso di annullamento ex-articolo 18?

Giuseppe Mucciarelli, TINN srl.

**Comment by azabatta** [comment]
La richiesta di annullamento di un codice fiscale, come previsto da Agenzia Entrate, può essere effettuata entro 24 ore dall’attribuzione. Di conseguenza è fattibile se il comune si rende conto subito di avere effettuato un’iscrizione (o una mutazione di dati anagrafici che ha comportato attribuzione di un nuovo codice fiscale) da non effettuare e soprattutto con dati che hanno generato un codice fiscale errato (altrimenti non c’è necessità di chiederne l’annullamento).
La richiesta di attribuzione in fase di iscrizione 1002 potrebbe applicarsi ad esempio all’iscrizione di un cittadino iscritto all’AIRE di un comune non subentrato, senza codice fiscale, che rientra in Italia iscrivendosi in un comune subentrato.

**Comment by Amucciarelli74** [comment]
Buon giorno,
in effetti non avevo considerato l'intervallo temporale valido per l'annullamento del codice fiscale, va da sé che i ripristini di posizione anagrafica non rientrano in questa casistica.
Grazie, 

Giuseppe Mucciarelli, TINN srl.
