### ISSUE TITLE
Il Comune di Santa Maria della Versa (PV) giò subentrato in Anpr in data 29/05/2018 deve rilasciare il certificato agli stranieri per il rinnovo del permesso di soggiorno. La Prefettura non vuole che sia indicata la dicitura "non validi se presentati alla Pubblica Amministrazione" ma il certificato viene prodotto dal MInistero e non possiamo solo proseguire con la stampa. E' possibile togliere quella frase? 

### ISSUE THREAD

**Issue by agnetti** [italia/anpr#747]
--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by gcarbonin** [comment]
Il formato dei certificati è stato proposto dai comuni e approvato dal Ministero dell'Interno. La frase c'è perchè c'è una legge che prevede questo.
A chi vanno questi certificati? Sono in bollo?

**Comment by agnetti** [comment]
Infatti il certificato è in bollo e rilasciato agli stranieri per il rinnovo del permesso di soggiorno. 

Peccato che uno straniero ha fatto esposto alla Prefettura locale la quale ci scrive richiamando l’attenzione in ordine a quanto rappresentato ( cioè che il certificato non deve contenere la dicitura “non validi se presentati alla pubblica amministrazione .) Ma come posso io variare un certificato emesso dal Ministero??

Grazie 

 

 

 

 

Carla Agnetti

 

Comune di Santa Maria della Versa(Pv)

tel. 0385278011

fax.038579108

 

DISCLAIMER

 

Questo messaggio, con gli eventuali allegati, contiene informazioni riservate. Chiunque lo ricevesse pur non essendone il destinatario è pregato di avvisare al più presto il mittente, di cancellarlo dal proprio sistema e di non copiarlo,diffonderne il contenuto o utilizzarlo in alcun  modo.

 

This email and any files transmitted with it are confidential. If you are not the intended recipient of this email, please notify the sender and delete it from your system immediately: you should not copy, disclose or use either it or its attachments in any way whatsoever.

 

Da: gcarbonin [mailto:notifications@github.com] 
Inviato: mercoledì 4 luglio 2018 13:54
A: italia/anpr <anpr@noreply.github.com>
Cc: agnetti <c.agnetti@comune.santa-maria-della-versa.pv.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [italia/anpr] Il Comune di Santa Maria della Versa (PV) giò subentrato in Anpr in data 29/05/2018 deve rilasciare il certificato agli stranieri per il rinnovo del permesso di soggiorno. La Prefettura non vuole che sia indicata la dicitura "non validi 

 

Il formato dei certificati è stato proposto dai comuni e approvato dal Ministero dell'Interno. La frase c'è perchè c'è una legge che prevede questo.
A chi vanno questi certificati? Sono in bollo?

**Comment by gcarbonin** [comment]
A chi viene consegnato il certificato?

**Comment by agnetti** [comment]
All’Utente che lo ha portato in Prefettura 

 

 

 

 

Carla Agnetti

 

Comune di Santa Maria della Versa(Pv)

tel. 0385278011

fax.038579108

 

DISCLAIMER

 

Questo messaggio, con gli eventuali allegati, contiene informazioni riservate. Chiunque lo ricevesse pur non essendone il destinatario è pregato di avvisare al più presto il mittente, di cancellarlo dal proprio sistema e di non copiarlo,diffonderne il contenuto o utilizzarlo in alcun  modo.

 

This email and any files transmitted with it are confidential. If you are not the intended recipient of this email, please notify the sender and delete it from your system immediately: you should not copy, disclose or use either it or its attachments in any way whatsoever.

 

Da: gcarbonin [mailto:notifications@github.com] 
Inviato: mercoledì 4 luglio 2018 14:01
A: italia/anpr <anpr@noreply.github.com>
Cc: agnetti <c.agnetti@comune.santa-maria-della-versa.pv.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [italia/anpr] Il Comune di Santa Maria della Versa (PV) giò subentrato in Anpr in data 29/05/2018 deve rilasciare il certificato agli stranieri per il rinnovo del permesso di soggiorno. La Prefettura non vuole che sia indicata la dicitura "non validi 

 

A chi viene consegnato il certificato?

**Comment by gcarbonin** [comment]
L'utente a quale pubblica amministrazione lo deve consegnare? Alla questura, alla Prefettura o a chi?

**Comment by gcarbonin** [comment]
E' prevista una specifica destinazione d'uso per queste tipologie di certificati (vedi pag. 150 delle specifiche di ANPR) :
![image](https://user-images.githubusercontent.com/25685981/42278139-14a7c084-7f9a-11e8-8bfc-0acde7e2dfe1.png)
Nella richiesta di certificato, occorre specificare il valore 2 nel campo PAestera; questo lo dovrebbe sapere il suo fornitore che eventualmente ci può contattare. In alternativa, dovrebbe richiedere il certificato dalla web application. In questo modo la frase "non gradita" non viene stampata
