### ISSUE TITLE
Risoluzione disallineamento ANPR/AE e base dati locale

### ISSUE THREAD

**Issue by busaster** [italia/anpr#749]
Abbiamo due persone (A e B) con dati allineati tra db locale e ANPR ma disallineati in AE.
Entrambe hanno CF NON allineato.
Usiamo le funzioni della WEBAPP per risolvere il disallineamento ANPR/AE.

Per la persona A premiamo "conferma AE". L'operazione va a buon fine, la modifica si ribalta in ANPR. Con il nostro applicativo intercettiamo l'operazione di mutazione 5008 avvenuta in modo trasparente nella webapp, aggiornando correttamente la base dati locale. Per questa persona quindi tutto OK.

Per la persona B invece premiamo "conferma ANPR". L'operazione va a buon fine, in AE passano i dati ANPR e il cf di ANPR viene marcato come validato. Quando però cerchiamo con il nostro applicativo una operazione webapp da ribaltare in locale per allineare la base dati (manca l'allineamento del CF)  non troviamo nulla. Come dovremo agire ? Esiste un canale di comunicazione per questo tipo di operazione ?

Grazie

**Comment by gcarbonin** [comment]
Occorre verificare la II posizione in quanto non è detto che il codice fiscale cambi. La sola variazione dello stato di validazione del CF non genera una mutazione: si tratta, infatti, di un dato interno ad ANPR. Ci dovrebbe far avere gli identificativi.

**Comment by busaster** [comment]
La prova è stata fatta al comune di Bergamo appena subentrato.

La persona A dell'esempio precedente, quella per cui esiste l'operazione WAPP, è la id ANPR 23625433, al quale abbiamo per prova eseguito la conferma AE. Questa conferma ha generato l'operazione WAPP id ANPR 12113365. Per questa persona coma dicevo non ci sono problemi.

La persona B, quella per cui abbiamo confermato ANPR in WAPP e per la quale abbiamo dovuto manualmente aggiornare la base dati locale riguardo l'allineamento del CF è la ID ANPR 23601230

**Comment by gcarbonin** [comment]
Nel caso 2, la persona era non validata in quanto il cf al subentro era giusto ma c'era una differenza sui dati anagrafici ininfluente per il codice fiscale (ad esempio cognome ANPR = Rossi; cognome AE = Rassi). Confermando i dati ANPR, la modifica si scatena solo su AE. In ANPR cambia lo stato del codice fiscale che è validato ma è un dato che localmente potrebbe non essere nemmeno riportato.

**Comment by busaster** [comment]
L'informazione sulla conferma del CF da parte di AE è fondamentale nel nostro integrato ed è usata dalle funzionalità non anagrafiche, per cui mantenerla allineata è una priorità.
E' pensabile prevedere un canale di comunicazione ANPR->Db locale per questo tipo di variazioni ?

**Comment by mccalv** [comment]
Caro @busaster si lo abbiamo pensato e sono le notifiche asincrone. Per favore date un'occhiata a questa issue #689

**Comment by busaster** [comment]
@mccalv al momento recuperiamo le operazioni avvenuta via WEBAPP con interrogazioni al servizio 3007. Ma nel caso che descrivevo sopra della persona B non risulta nessuna operazione sul soggetto, quindi non riceviamo nulla. Da quanto dici dunque le notifiche restituiscono più informazioni rispetto a quelle recuperabili con il servizio 3007 ? e di che notifica si tratterebbe nel caso descritto ?

Grazie.

**Comment by mccalv** [comment]
@busaster la mia era un invito generico a prendere in considerazione questi servizi asincroni rispetto alle interrogazioni sincrone. Esiste un servizio di elenco dei soggetti non validati nello specifico che possono essere interrogati eventulamente su base periodica

**Comment by busaster** [comment]
D'accordo, è nei nostri piani l'evoluzione verso l'uso dei servizi di notifica.
Nel caso specifico però il problema rimarrebbe.

Secondo me  la soluzione ottimale sarebbe avere lo stesso comportamento sia nel caso "Conferma ANPR" che nel caso "Conferma AE", ovvero una  una operazione di variazione ANPR recuperabile, con notifica o con ricerca 3007, in modo da poterla replicare in modo automatico nel DB locale.

Una domanda sul servizio per ottenere l'elenco dei soggetti ANPR non validati :  è una funzione disponibile solo su WEBAPP o è esposta anche tramite WS ?

Grazie

Gianrico Busa per Maggioli Spa

**Comment by gcarbonin** [comment]
Il servizio è stato realizzato e consente di richiedere periodicamente l'elenco di tutte le schede anagrafiche con codice fiscale NON validato. Si tratta di una richiesta asincrona che è di imminente rilascio.

**Comment by azabatta** [comment]
Buonasera, 
l'intervento relativo all'elenco dei cittadini con codice fiscale non validato in Agenzia Entrate è disponibile negli ambienti di test.  Per la descrizione dell’implementazione si rinvia alla issue #780.
