### ISSUE TITLE
WebApp - problemi su Unione Civile

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#75]
Comune di Venezia, ambiente di Pre-subentro, 05/04/2017
Si segnala che inserendo un'unione civile su WebApp il sistema non modifica automaticamente lo stato civile. Abbiamo provato a modificarlo noi durante l'inserimento della mutazione dati di stato civile e generalità, ma si riesce a modificare solo al primo individuo richiamato; l'unione civile quindi viene registrata ma con  segnalazione di errore dello stato civile della seconda persona;  dunque sul secondo individuo è necessario effettuare un'ulteriore mutazione dati.
Vedi es. id ANPR dell'Unione civile 122318
id ANPR mutazione stato civile 122326

**Comment by gcarbonin** [comment]
Buongiorno. Non e' un errore ma una precisa indicazione del Ministero dell'Interno; pertanto occorre la mutazione della scheda della persona unita civilmente alla prima. La segnalazione che viene restituita e' un'anomalia per ricordare al comune di effettuare la variazione. Anche i WS operano nello stesso modo.
