### ISSUE TITLE
[3002] GRAVE - Consultazione x codiceFiscale restituisci risultati di vecchie consultazione da altri richiesta

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#750]
In ambiente pre-subentro, effettuando delle consultazioni su schedaSoggetto su DatiRichiesti ( Generalita e SchedaFamiglia )
con criterio CoficeFiscale
nella risposta del 3002 è di unaltra Richiesta !!!  vedere **dataOraRichiesta** inferiore a quello della Richiesta.

Da ieri sera e ancro presente questa mattina.
In seguito 2 casi:

Caso.1 - Risposta EN122-La richiesta effettuata non produce alcun risultato
Richiesta :
```
    <testataRichiesta>
        <idOperazioneComune>59722</idOperazioneComune>
        <codMittente>001272</codMittente>
        <codDestinatario>ANPR01</codDestinatario>
        <operazioneRichiesta>3002</operazioneRichiesta>
        <dataOraRichiesta>2018-07-05T21:26:01.481+02:00</dataOraRichiesta>
	...
```
Risposta:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Risposta3002 xmlns:ns2="http://sogei.it/ANPR/3000consultazione">
    <ns2:rispostaKO>
        <testataRisposta>
            <idOperazioneComune>59722</idOperazioneComune>
            <codMittente>001272</codMittente>
            <codDestinatario>ANPR01</codDestinatario>
            <operazioneRichiesta>3002</operazioneRichiesta>
            <dataOraRichiesta>2018-06-12T14:31:55.203+02:00</dataOraRichiesta>
            <dataDecorrenza>2018-06-12</dataDecorrenza>
            <idOperazioneANPR>3615669</idOperazioneANPR>
            <esitoOperazione>XXXX</esitoOperazione>
        </testataRisposta>
        <listaErrori>
            <errore>
                <codiceErroreAnomalia>EN122</codiceErroreAnomalia>
                <tipoErroreAnomalia>E</tipoErroreAnomalia>
                <testoErroreAnomalia>La richiesta effettuata non produce alcun risultato</testoErroreAnomalia>
            </errore>
        </listaErrori>
    </ns2:rispostaKO>
</ns2:Risposta3002>
```

Caso.2 - Risposta OK su un altro soggetto !!
Richiesta :
```
<testataRichiesta>
	<idOperazioneComune>59723</idOperazioneComune>
	<codMittente>001272</codMittente>
	<codDestinatario>ANPR01</codDestinatario>
	<operazioneRichiesta>3002</operazioneRichiesta>
	<dataOraRichiesta>2018-07-05T21:26:50.761+02:00</dataOraRichiesta>
```
		
Risposta:
```
<testataRisposta>
	<idOperazioneComune>59723</idOperazioneComune>
	<codMittente>001272</codMittente>
	<codDestinatario>ANPR01</codDestinatario>
	<operazioneRichiesta>3002</operazioneRichiesta>
	<dataOraRichiesta>2018-06-12T14:36:20.089+02:00</dataOraRichiesta>
	<dataDecorrenza>2018-06-12</dataDecorrenza>
	<idOperazioneANPR>3615672</idOperazioneANPR>
```
Con i dati di un altro soggetto !!!

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
State utilizzando idoperazionicomune già utilizzati in passato; in questo caso ANPR restituisce la stessa risposta data all'epoca.

**Comment by gcarbonin** [comment]
Il problema si risolve interrogando per idoperaziooneANPR. Faccio presente che interrogando per idoperazione comune (probabilmente per eseguire quadrature della base dati) si perdono tutte le operazioni effettuate via WEB

**Comment by pissardl** [comment]
Ok, abbiamo reinizializzato la nostra sequenza a 200000
Si vede che all'ultima prova su pre-subentro non sono state cancellate le vecchie Richieste/Risposte, ma solo Soggetti e famiglie.

Adesso va.
Grazie.

**Comment by gcarbonin** [comment]
Le operazioni volutamente non vengono cancellate in quanto potrebbero essere collegate ad operazioni fatte da altri comuni.
