### ISSUE TITLE
Conteggi diritti di segreteria

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#752]
E' possibile dalla web app fare una ricerca dei certificati emessi, distinti per ogni singolo operatore?
Comune di Altamura

**Comment by cmigliardi** [comment]
Dal sito web, area Utilità, certificati e carte di identità.
 Per effettuare la ricerca occorre impostare i seguenti parametri:
•il Tipo documento, scegliendone uno tra quelli proposti dalla combo-box
•un intervallo di date per le Richieste effettuate
•il Codice Fiscale del soggetto d'interesse (dato facoltativo)
•l'Identificativo scheda attribuito da ANPR del soggetto d'interesse (dato facoltativo)
Non è possibile effettuare ricerche per singolo operatore.
