### ISSUE TITLE
[5008] IMMI di famiglia monoComponente - EAM95 soggetto ancora in AT ANPR di altro comune

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#753]
In ambiente pre-subentro, stiamo cercando di effettuare la IMMI di una famiglia mono componente.
Abbiamo quindi eseguiti i seguenti chiamate via WS :
1014 OK  idOperazioneANPR:6446921  dataOraRichiesta:2018-07-07T12:50:32.113  Apertura procedimento
3002 OK  idOperazioneANPR:6446922  dataOraRichiesta:2018-07-07T12:50:30.568  RicercaSoggetto
3002 OK  idOperazioneANPR:6446923  dataOraRichiesta:2018-07-07T12:50:32.927  RicercaNumeroComponenti Nella Famiglia di Provenienza
5001 OK  idOperazioneANPR:6446924  dataOraRichiesta:2018-07-07T12:50:34.036  MutazioneResidenzaFamiglia (tipoMutazione:4)
5001 OK  idOperazioneANPR:6446925  dataOraRichiesta:2018-07-07T12:50:35.654  MutazioneGeneralitaSchedaFamiglia (tipoMutazione:3) x fornire gli identificativi del nostro comune sulla scheda famiglia
**5008 KO  idOperazioneANPR:6446926  dataOraRichiesta:2018-07-07T12:50:36.938  MutazioneGeneralitaSchedaSoggetto (tipoMutazione:1) x fornire gli identificativi del nostro comune sulla scheda soggetto**
	 EAM95-Variazione non consentita, soggetto registrato in AT ANPR di altro comune

Come dobbiamo procedere nell'ultima chiamata (con 5008) per inserire "Identificativo scheda attributo dal Comune" sulla scheda soggetto ?

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
La procedura è corretta ma  con l'ultima mutazione con l'ultima mutazione è stata modificata anche la data di nascita. Questo impatta sul codice fiscale; l'Agenzia ha risposto con errore in quanto la mutazione di residenza (primo 5001) non era ancora stata acquisita dall'Agenzia stessa. Ripetendo ora questa mutazione dovrebbe andare a buon fine.
