### ISSUE TITLE
[6001] tipoDato.xsd  tipoRigaAnnotazione   Richiesta su caratteri parentesi

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#754]
In ambiente pre-subentro, 

Attualmente "tipoRigaAnnotazione" non prevede i caratteri parentesi :
```	<xs:simpleType name="tipoRigaAnnotazione">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9À-ža-zA-Z\- '/.,])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="240"/>
		</xs:restriction>
	</xs:simpleType>
```

Sarebbe possibile aggiungere i 2 carateri "()" (avere lo stesso pattern del tipo "tipoAutorita") ?
Averlo cosi:
```	<xs:simpleType name="tipoRigaAnnotazione">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9À-ža-zA-Z\- '/.,()])*"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="240"/>
		</xs:restriction>
	</xs:simpleType>
```

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by mttfranci** [comment]
Salve, stiamo apportando la modifica, vi avviseremo quando sarà rilasciata.

**Comment by mttfranci** [comment]
La modifica è stata rilasciata #617
