### ISSUE TITLE
Coorrezione dato errato 

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#755]
In data ante subentro abbiamo erroneamente fatto un evento di iscrizione per nascita di un neonato, iscrivendolo in una famiglia sbagliata.
Qual è la procedura corretta per sistemare tale anomalia?
Identificativo scheda attribuito da ANPR:  18908543

**Comment by gcarbonin** [comment]
Mutazione della famiglia con data di decorrenza dalla nascita (22-3-2017)

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Coorrezione dato errato (#755)" inviata il 13/07/2018 09:00:04.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
