### ISSUE TITLE
Codice fiscale straniero e stato con variazione di cod. catastale

### ISSUE THREAD

**Issue by busaster** [italia/anpr#757]
Ambiente di Produzione, comune di Buggiano
Nel nostro archivio un soggetto (nato in Georgia) ha un codice fiscale calcolato (non allineato) con il codice catasto attuale dello stato di nascita (Z254). Con questo dato il soggetto è  entrato in ANPR con il subentro. 
In AE il soggetto però risulta avere un codice fiscale con cod. catastale Z136 che corrisponde a quello che la Georgia aveva prima del 1994.

In questo caso qual è il comportamento corretto ad seguire per allineare le informazioni tra AE e ANPR ?

Grazie
Gianrico Busa per Maggioli Spa

**Comment by MarcoMigliori** [comment]
Collego anche il precedente issue  #622

**Comment by gcarbonin** [comment]
Occorre vedere la situazione dal punto di vista amministrativo: se questa persona si è iscritta ad esempio nel 1993 e non ha mai effettuato presso il comune altre operazioni, significa che la modifica dello stato di nascita è stata effettuata automaticamente via SW (ad esempio, è stata cambiata la tabella degli stati nel SW gestionale). In questo caso, occorre sistemare i dati rimettendo Z136, per evitare di obbligare la persona a modifica codice fiscale e tutti i documenti. Per occorre confermare i dati AE da risoluzione disallineamenti con l'Agenzia delle Entrate.
In caso contrario, il comune ha modificato "consapevolmente"  i dati perchè in occasione di una operazione effettuata sul soggetto,  da un documento valido della persona il comune ha attualizzato  lo stato di nascita (Georgia). Occorre quindi  allineare i dati di Agenzia delle Entrate (risoluzione disallineamenti con l'Agenzia delle Entrate), confermando i dati del comune. Questo cambierà il codice fiscale quindi sarebbe opportuno un avviso alla persona da parte del comune.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Codice fiscale straniero e stato con variazione di cod. catastale (#757)"
inviata il 13/07/2018 08:59:25.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
