### ISSUE TITLE
[3003] ricerca elenco completo notifiche

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#758]
In precedenza utilizzavamo la feature prevista sul campo  operazioneRichiesta  del ws 3003 impostando "N"  per visualizzare tutte le notifiche. Ultimamente non ci funziona.
Ambiente di test, id operazione 11673247

**Comment by azabatta** [comment]
Per ottenere tutte le notifiche basta non indicare il campo operazioneRichiesta (fermo restando ovviamente lo statoLavorazione).
Cortesemente possiamo avere un identificativo di una richiesta strutturata come quella indicata ed andata a buon fine?
Grazie

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[3003] ricerca elenco completo notifiche (#758)" inviata il 13/07/2018
10:39:17.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by MarcoMigliori** [comment]
Una richiesta con la "N" andata a buon fine non l'abbiamo memorizzata, perchè risalente a un pre-subentro sostituito. E' anche possibile che ci ricordiamo male e che non funzionasse.

Abbiamo invece provato la nuova modalità suggerita in due modi diversi, ricevendo però come risposta  un elenco di operazioni, tranne le notifiche Nxxx :
-  id operazione anpr di chiamata 10637709 (ambiente di test)
-  id operazione anpr di chiamata 10637789 (ambiente di test)

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[3003] ricerca elenco completo notifiche (#758)" inviata il 16/07/2018
17:35:05.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by azabatta** [comment]
Buonasera, 
nelle giornate indicate nelle due richieste non sono presenti notifiche per il comune. Stiamo verificando il malfunzionamento della risposta.
Il  ws invocato è il 3007  e non il 3003 che non presenta questo errore.
Avviseremo appena sarà possibile riprovare. Grazie per la segnalazione

**Comment by azabatta** [comment]
Buonasera, 
la modifica è operativa sia negli ambienti di test che in esercizio. E' possibile riprovare

**Comment by MarcoMigliori** [comment]
avete modificato il ws 3003 giusto?
id operazione anpr di chiamata 16648194 (ambiente di test).
nel risultato ci sembrano mancare  le notifiche di avvenuto subentro dei comuni

idem provando il ws 3007, id operazione anpr di chiamata 16648120 (ambiente di test).

Segnalo inoltre che nel fare le verifiche, ho usato la WA menù
_Ti trovi in: HOME - UTILITÀ E NOTIFICHE - MONITORAGGIO OPERAZIONI_
dalla combo ho scelto "tipo operazione: NOTIFICA AVVENUTO SUBENTRO DEL COMUNE" dal 20/9 al 26). risultato: nessuna.
Via ws avevo invece ricevuto delle notifiche, a questo punto sempre dalla WA menù
_Ti trovi in: HOME - UTILITÀ E NOTIFICHE - NOTIFICHE_
vedo effettivamente diversi subentri nel periodo indicato.

**Comment by MarcoMigliori** [comment]
Ok, non avrei saputo interpretare il menù in questo senso.
A questo punto credo si possa chiudere l'issue. Non avremo una risposta completa delle notifiche in questo modo, useremo altri metodi (chiamata per singolo tipo).
