### ISSUE TITLE
Interruzione elaborazioni file subentro in ambiente di presubentro da venerdì a domenica

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#759]
I file di subentro (APR ed AIRE) inviati nelle giornate da venerdì 13/7 a domenica 15/7 in ambiente di presubentro non saranno immediatamente elaborati. I file eventualmente ricevuti saranno elaborati dal lunedì successivo. Si consiglia in ogni caso di attendere la normale ripresa del servizio il lunedì 17/7

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Interruzione elaborazioni file subentro in ambiente di presubentro da
venerdì a domenica (#759)" inviata il 12/07/2018 09:41:12.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
