### ISSUE TITLE
WebApp - Certificati di Uniti civilmente

### ISSUE THREAD

**Issue by Chissodaniela** [italia/anpr#76]
Comune di Venezia, ambiente di Pre-subentro, 05/04/2017
Si segnala che il certificato di Stato civile per un individuo unito civilmente segnala:
Operazione non effettuabile (Codice: 999) 
Es. id ANPR dell'individuo 5152693

**Comment by gcarbonin** [comment]
Chiedo scusa ma questa segnalazione ci era sfuggita. Ha avuto modo di verificare successivamente?

**Comment by Chissodaniela** [comment]
Buongiorno, abbiamo riprovato ed ora il certificato esce correttamente.
Grazie
