### ISSUE TITLE
Rettifica dati subentro per autotutela (data decorrenza residenza)

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#760]
Ambiente di produzione, id anpr 27327148.
Il Comune mi segnala la necessità di correggere i dati anagrafici in autotutela.
Questo si traduce nella rettifica delle seguenti informazioni ANPR:
- data iscrizione nel comune
- motivo di iscrizione e provenienza
- data decorrenza residenza

Riesco a rettificare i dati tramite la funzione di "rettifica dati subentro" e "iscrizione".
Tranne che per la data decorrenza residenza (da impostare a 5/8/2015), per la quale tentando la modifica ottengo errore 

_EN414 Rettifica non permessa in quanto la data di decorrenza residenza è presente e congruente._

Leggendo il documento delle rettifiche, in effetti non sembra previsto questo caso.
Come dobbiamo comportarci?

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
Rettifica dati subentro per autotutela (data decorrenza residenza) (#760)"
inviata il 12/07/2018 16:45:33.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by gcarbonin** [comment]
La funzione di rettifica è nata per correggere dati errati o incompleti trasmessi al subentro. occorre una pec del comune per la modifica.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Rettifica dati subentro per autotutela (data decorrenza residenza) (#760)"
inviata il 13/07/2018 08:36:45.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by MarcoMigliori** [comment]
Informo il Comune, grazie.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
Rettifica dati subentro per autotutela (data decorrenza residenza) (#760)"
inviata il 13/07/2018 18:23:45.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
