### ISSUE TITLE
[5001] Cambio di indirizzo con risposta Warning ma non conferito in ANPR

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#762]
In ambiente pre-subentro, abbiamo effettuato un cambio di indirizzo con servizio 5001 con esito positivo con warning (WN)

In ANPR il soggetto è sempre residente al vecchio indirizzo.
idOperazioneANPR = 6390386

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
[5001] Cambio di indirizzo con risposta Warning ma non conferito in ANPR
(#762)" inviata il 12/07/2018 20:03:29.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by gcarbonin** [comment]
Come già segnalato, vengono trasmesse ad ANPR richieste di servizio contemporanee senza attendere l'esito. Nel caso specifico è stato inviato il 5001 contestualmente a due 5008. Questo può determinare la perdita di uno o più dati.
