### ISSUE TITLE
[1002] Iscrizione in nuova famiglia - AEE97

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#763]
In ambiente pre-subentro, abbiamo provato ad effettuare una prima iscrizione con 1002 in nuova famiglia.
Soggetto con CF valido che ci avete fornito, e non presente su ANPR.
 
1002  idOperazioneANPR:6529944  dataOraRichiesta:2018-07-13 15:55:14.953

La risposta produce il seguente errore:
AEE97-Operazione non effettuabile

A cosa è dovuto?

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
[1002] Iscrizione in nuova famiglia - AEE97 (#763)" inviata il 13/07/2018
18:09:54.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[1002] Iscrizione in nuova famiglia - AEE97 (#763)" inviata il 13/07/2018
18:28:24.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.
