### ISSUE TITLE
[2003] Emigrazione - Errore EN203

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#764]
ambiente di PRODUZIONE - comune di MALNATE

il tentativo di invio della comunicazione di emigrazione (ws 2003) con idOperazioneComune 2018001790 viene bloccata dall'errore
EN203 - E - Operazione non effettuabile. Esiste un'operazione sospesa per il soggetto

ripercorrendo tutte le operazioni inviate per il soggetto in questione (idSchedaANPR 23515375), e pensando che potessero in qualche modo bloccare l'emigrazione, abbiamo annullato (con ws 5012) tutto ciò che è stato inviato in precedenza.

non capiamo cosa blocca il completamento dell'emigrazione.

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
C'è una mutazione effettuata ma non completata il 6 luglio tramite web application Il comune deve entrare nella web application e concluderla o eliminarla

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "Re: [italia/anpr]
[2003] Emigrazione - Errore EN203 (#764)" inviata il 16/07/2018 11:04:37.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by COlivatoADS** [comment]
Sono fuori dall'ufficio fino a 23/07/2018




Nota: Questa è una risposta automatizzata al messaggio  "[italia/anpr]
[2003] Emigrazione - Errore EN203 (#764)" inviata il 16/07/2018 10:55:41.

Questa è l'unica notifica che verrà ricevuta mentre la persona è assente.
Questa e-mail ed i suoi allegati sono ad uso esclusivo di coloro ai quali è indirizzata e potrebbe contenere informazioni riservate, la cui diffusione, copia e/o distribuzione è proibita. Qualora riceveste questo messaggio per errore, scusandoci per l'accaduto, Vi preghiamo di avvertirci immediatamente, distruggendo quanto ricevuto.

**Comment by AMonopoliADS** [comment]
il cliente ha proceduto come suggerito, e l'emigrazione è andata a buon fine.
grazie.
