### ISSUE TITLE
PRATICA DI EMIGRAZIONE

### ISSUE THREAD

**Issue by Elenalomazzi** [italia/anpr#765]
Buongiorno,
stiamo lavorando in ANPR con webservice. Abbiamo ricevuto da un Comune subentrato in data 14/07 una richiesta di cancellazione anagrafica con decorrenza 13/07. Abbiamo provato a definire la pratica sia come trasferimento di residenza in comune non subentrato, che come mutazione di residenza, ma viene restituito il seguente errore : "tipo di registrazione non consentita in ANPR (errore 15003)."
Restiamo in attesa di indicazioni.
Grazie
Elena Lomazzi

**Comment by gcarbonin** [comment]
Come chiediamo sempre in questi casi, ci occorre l'identificativo operazione per poter individuare il problema.

**Comment by Elenalomazzi** [comment]
id operazione : 1223342 
id individuo : 18934817

**Comment by gcarbonin** [comment]
l'id operazione che avete indicato è il subentro. Il messaggio di errore non sembra proveniente da ANPR ma dal vostro gestionale
