### ISSUE TITLE
[5008] Completamento dati AIRE e matrimonio

### ISSUE THREAD

**Issue by busaster** [italia/anpr#767]
Ambiente di test - Gorgonzola.
Abbiamo un cittadino AIRE (id ANPR 9371905 ) che non ha mai avuto, dopo il subentro, nessuna mutazione in ANPR. Anche il suo coniuge (id ANPR 9371904). è in AIRE senza modifiche dopo il subentro

Con una mutazione 5008 di tipo 21 (id ANPR 12637900) tentiamo di completare i dati ma riceviamo un errore EN272 "Alla data 16-09-2005 il soggetto XXXXXXXXXXX risulta gia' coniugato o unito civilmente con un altro soggetto".
In realtà risutla coniugato con un soggetto con il solo cognome, come tutti gli aire subentrati a causa dei limiti di ANAGAIRE.

Potete verificare come mai abbiamo il blocco ?

Grazie

**Comment by frmariani** [comment]
purtroppo a causa dei limiti di ANAGAIRE, la riconciliazione del matrimonio, necessita di un'operazione aggiuntiva.
con il completamento, devono essere inviati tutti i dati mancanti del soggetto, anche il nome del coniuge, ma NON il suo idanpr .
successivamente, con il servizio 5008 tipo mutazione 12, sarà possibile inviare l'idanpr del soggetto coniuge.
nel suo caso:
servizio 5008 tipo mutazione 21 del soggetto idanpr 9371905  indicando, tra gli altri dati, anche il nome del coniuge;
servizio 5008 tipo mutazione 21 del soggetto idanpr 9371904 indicando, tra gli altri dati, anche il nome del coniuge;
servizio 5008 tipo mutazione 12  del soggetto idanpr 9371905 indicando come coniuge 9371904

**Comment by busaster** [comment]
Non sarebbe possibile da parte vostra automatizzare questa procedura, visto che si tratta di una mutazioen ad hoc apposta per il completamento AIRE  ?
Diventa molto laborioso altrimenti allineare i dati di centinaia o migliaia di ARE.

**Comment by frmariani** [comment]
a fine mese rilasceremo un aggiornamento del servizio di mutazione dati per la riconciliazione dei coniugi Aire con il solo cognome; l’aggiornamento dei documenti di specifica illustrerà al meglio l’intervento
