### ISSUE TITLE
[WEBAPP] Mutazione Residenza  Altro Recapiti - EF051

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#769]
In ambiente di Presubentro
Avremo voluto creare un caso di un soggetto con "Altri Recapiti" (Dimora Abituale e/o Domicilio eletto) per verificare le problematiche di integrazione nel caso di soggetto con multi Residenza.

Da WA, inserando una Mutazione Residenza, Operazione d'Ufficio e selezionando un solo soggetto residente nel comune di Torino  e  cercando di inserire un altro recapito, ci viene sempre l'errore seguente :
   Indicare un solo soggetto alla volta (Codice: EF051)

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by frmariani** [comment]
stiamo verificando

**Comment by frmariani** [comment]
potete riprovare per favore ?

**Comment by frmariani** [comment]
potete riprovare.

**Comment by pissardl** [comment]
OK.  Adesso va ; Si puo Chiudere.

Soggetto 60700345 modificato da WA.
Aggiungendo  Dimora Abituale e Domicilio Eletto.

Grazie.
