### ISSUE TITLE
Translitterazione parole con acento acuto finale

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#770]
La tabella n. 40 - "Caratteri diacritici" descrive il metodo di translitterazione di ANPR. In fondo alla tabella è descritto il criterio per le lettere accentate che si trovano in fine di parola, che sono trasformate nella lettera senza accento seguita dal segno di apostrofo. Questa definizione vale per le lettere con accento grave, non si parla di quelle con accento acuto. 
Mi sembra che di conseguenza le parole che terminano con vocale con accento grave siano translitterate con un apostrofo in coda alla parola e quelle che terminano con accento acuto perdono traccia dell'accento come si vede nell'allegato.
E' una cosa voluta? Grazie.
Filipazzi - Maggioli
![accento acuto translitterato](https://user-images.githubusercontent.com/26787808/42942300-f1cef6fc-8b4e-11e8-8f3a-e6dba1582b16.JPG)

**Comment by gcarbonin** [comment]
Le regole sono scritte in un decreto In ogni caso abbiamo interpretato che entrambi gli accenti nella lettera finale siano translitterati con l'apostrofo (MALE').
