### ISSUE TITLE
[5008] ws - rettifica comune di nascita

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#771]
Comune di Castiglione Falletto (CN) - subentrato 

Per errore è stato modificato il comune di nascita ad un cittadino (con relativa attribuzione di codice fiscale errato) che prima della variazione errata risultava nato nel comune di TORRE BORMIDA nel 1943.
Andando a rettificare nuovamente il comune per riportarlo al dato corretto, viene segnalato il seguente errore: "EN332 - Comune/provincia di nascita TORRE BORMIDA (CN) inesistente o non valido alla data di nascita". In effetti in base alle tabelle ANPR dei comuni, il comune di TORRE BORMIDA non esiste alla data del 05-07-1943, ma il comune è in possesso di un estratto di nascita che certifica il fatto che la persona è nata nel comune di TORRE BORMIDA. 
Potrebbe essere un errore delle tabelle ANPR?
In fase di subentro il comune di nascita TORRE BORMIDA alla data del 1943 era stato accettato, ma adesso in fase di mutazione non più. Come possiamo riportarlo al dato originale? 
Abbiamo anche provato ad effettuare l'annullamento dell'operazione di mutazione tramite WA ma risponde che non è possibile annullare una mutazione di dati anagrafici.

Se serve posso farvi avere i codici identificativi del cittadino.

**Comment by gcarbonin** [comment]
La situazione è molto più complessa di quella rappresentata in quanto successivamente al subentro è stato modificato il comune di nascita con conseguente riattribuzione del codice fiscale. 
Per ripristinare la situazione precedente, occorre effettuare una nuova mutazione indicando il "vecchio codice fiscale" e il comune di TORRE BORMIDA. Può operare a partire dal prossimo lunedì.
Colgo l'occasione per ribadire che  variazioni del comune di nascita  solo quando effettivamente necessarie (dato dell'anagrafe non coerente con l'atto di nascita) e previo avviso al cittadino soprattutto se la variazione comporta l'attribuzione di un nuovo codice fiscale.

**Comment by siscomanpr** [comment]
Il comune ci ha riferito che procedendo con la mutazione come da voi indicato, il problema persiste.
Viene sempre segnalato l'errore: "EN332 - Comune/provincia di nascita TORRE BORMIDA (CN) inesistente o non valido alla data di nascita".
Se serve posso farvi avere l'xml della richiesta.

**Comment by frmariani** [comment]
Cortesemente riprovate ora. Grazie
