### ISSUE TITLE
 WS - A001 – nascita Aire in famiglia esistente.

### ISSUE THREAD

**Issue by INSIEL1** [italia/anpr#773]
Comune di Codroipo (UD) – ambiente Presubentro.
Fino al 2 luglio riuscivamo a trasmettere le nascite AIRE chiedendo l’assegnazione del CF (gestione CF = 1).
Riprovando, a partire dal 16 luglio riceviamo il seguente errore da AE:
EAA0A – Errore di sistema.
Id operazione ANPR = 7365654 del 23 luglio

**Comment by gcarbonin** [comment]
stiamo verificando

**Comment by gcarbonin** [comment]
Potete riprovare

**Comment by INSIEL1** [comment]
funziona correttamente - grazie
