### ISSUE TITLE
[5008] Tipo Mutazione 17 - Risoluzione convivenza

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#774]
ambiente di TEST - comune di FAENZA - idOperazioneComune 2018000494

viene comunicata la cessazione della convivenza di fatto del soggetto con idANPR 17707015
l'xml contiene solo i dati di cessazione della convivenza di fatto (data e motivo)
la comunicazione viene accettata, ma:
perchè spariscono tutti i dati di istituzione (blocco dati contrattoStipula)?
non so se sia una scelta o un errore, ma almeno la data di istuzione della convivenza mi sembra un'informazione interessante da mantenere...

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Spariscono da dove? IL WS 3002 li restituice

**Comment by AMonopoliADS** [comment]
da quello che vedo:
idOperazioneComune 2018301666 - ws 3002 "a oggi, data della mutazione": i dati NON compaiono
idOperazioneComune 2018301667 - ws 3002 "a ieri, giorno prima della mutazione": i dati compaiono

**Comment by gcarbonin** [comment]
Può riprovare a partire dal 2 agosto con un nuovo caso di teste

**Comment by AMonopoliADS** [comment]
il comportamento adesso è corretto.
viene aggiornata la data di cessazione senza annullamento dei dati di stipula.
grazie
