### ISSUE TITLE
Rimpatrio dall'Aire

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#776]
Mutazione residenza per rimpatrio dall'Aire codice ANPR 18855368 abbiamo il seguente
ERRORE DA ANPR: 
EF002 - Identificativo scheda famiglia/convivenza attribuito da ANPR non trovato o scheda famiglia archiviata```

**Comment by gcarbonin** [comment]
Nella richiesta è stato indicato come tipo scheda (famiglia) il valore 3 invece di 5.
