### ISSUE TITLE
[WEBAPP][5001] Mutazione Residenza Famiglia - Data origine famiglia/convivenza

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#777]
In ambiente di pre-subentro, operando da webapp.
Registrando una mutazione di residenza di una famiglia (mono componente) da un comune subentrato (con servizio 5001, tipoMutazione 4), idOperazioneANPR=7372222

Abbiamo notato che viene variato la "**Data origine famiglia/convivenza**" al "**25/07/2018**" corrispondente con una delle date della mutazione di indirizzo tra comune:
dataDecorrenza=2018-07-25
dataDecorrenzaResidenza=2018-07-25

Un po' come se fosse creata una nuova famiglia !?
Ma non è stato variata "**Data decorrenza appartenenza**" che è rimasta al **26/01/1990**.
Ne risulta quindi una  "Data decorrenza appartenenza"  inferiore alla "Data origine famiglia/convivenza" !

Si tratta di un giusto comportamento del WS 5001 o WEBAPP ?

idSoggettoANPR=52360555

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
La persona non ha cambiato famiglia e quindi è giusto che rimanga la data di ingresso  originale. La famiglia si trasferisce nel comune di Torino il 25 luglio: mantiene lo stesso identificativo ma la scheda anagrafica si apre nel comune in quella data.
