### ISSUE TITLE
Mutazione tutti i dati

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#778]
Abbiamo necessità di variare il luogo di nascita e il codice fiscale ad un cittadino straniero cod. ANPR 18910176. Dal menù registrazione-mutazione tutti i dati selezioniamo la casella **Dati anagrafici / Codice fiscale** ma ci impedisce di andare avanti a causa del seguente errore:
Il campo Motivo contiene dei caratteri non validi

**Comment by gcarbonin** [comment]
State utilizzando la WEBAPP? se così, dove si trova questo campo motivo? Se state utilizzando il vostro sistema anagrafico, dovrebbe contattare il suo fornitore

**Comment by Finalmentesubentrati** [comment]
Si. Per questa mutazione ho utilizzato la web app

**Comment by Finalmentesubentrati** [comment]
Può chiudere il ticket ho risolto.
