### ISSUE TITLE
Ambiente Test e Presubentro - disponibilità nuovi servizi di download elenchi ANPR 

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#779]
Si comunica che è disponibile negli ambienti di TEST_COMUNI e PRESUBENTRO un intervento che consente di effettuare il download degli elenchi prodotti dal sistema ANPR in fase di subentro oppure a fronte di elaborazioni  asincrone. 
L’intervento ha comportato le seguenti implementazioni:
-	sviluppo di una nuova notifica N032 che riporta la lista degli identificativi assegnati dal sistema agli elenchi prodotti dal sistema ANPR; la notifica riporta gli identificativi da utilizzare per il download e la tipologia di file; una notifica N032 sarà prodotta al termine delle operazioni di subentro di ogni comune per comunicare gli identificativi degli elenchi relativi ai soggetti subentrati in ANPR (codice tipo file = 3)

-	sviluppo di un nuovo servizio di download 7002 che consente di scaricare un determinato  elenco; la richiesta prevede l’indicazione dell’ identificativo file assegnato da ANPR, la risposta riporta come attachment il file in formato compresso e l’indicazione del suo formato (es. xml, csv etc.); il sistema controlla che il file richiesto sia stato prodotto e che sia di competenza del comune richiedente. 

[SPECIFICHE DI INTERFACCIA_25_07_2018.zip](https://github.com/italia/anpr/files/2231449/SPECIFICHE.DI.INTERFACCIA_25_07_2018.zip)
[SPECIFICHE_DI_INTERFACCIA_XSD_25072018_2.zip](https://github.com/italia/anpr/files/2231451/SPECIFICHE_DI_INTERFACCIA_XSD_25072018_2.zip)

**Comment by bfilipazzi** [comment]
Gli allegati risultano corrotti. Grazie.

**Comment by rvinzani** [comment]
Aggiornati gli allegati

**Comment by MarcoMigliori** [comment]
Forse il servizio 7002 deve essere aggiunto sul sito www.anpr.interno.it ?
_Elenco dei web services disponibili - xls (aggiornato al 29 gennaio 2018)_
