### ISSUE TITLE
[A002] Web Service - Msg "Errrore di sistema" 

### ISSUE THREAD

**Issue by COlivatoADS** [italia/anpr#78]
Buongiorno.
(IdOperazioneComune 2017000019 - dppre - Comune di Occhiobello)
Nell'invio di una comunicazione di Iscrizione Aire otteniamo l'errore bloccante "Errore di Sistema".
Il Web Service ritorna anche il seguente warning 
"EN200 - W - Se stato civile vedovo/a deve essere presente la sezione vedovanza"
ma la sezione vedovanza è presente.
Grazie
Christian Olivato ADS

**Comment by gcarbonin** [comment]
Puo riprovare e darmi un riscontro?

**Comment by COlivatoADS** [comment]
Ora ritorna la seguente segnalazione 
"EE999 - E - Servizio Agenzia Entrate momentaneamente non disponibile"

Grazie
Christian Olivato ADS

**Comment by gcarbonin** [comment]
Probabilmente  si tratta di un errore di connessione, Può riprovare?

**Comment by COlivatoADS** [comment]
Invio effettuato con esito positivo.
Grazie
