### ISSUE TITLE
[AE] Cittadino inserito con generalità errate

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#781]
Ambiente di produzione. id 30562674.
E' stato iscritto erroneamente il cittadino in anagrafe con una data di nascita completamente errata, richiedendo l'assegnazione del codice fiscale.
Verificando ora, nella banca dati AE risulta già presente il cittadino con le generalità corrette.
Per cui in AE abbiamo due posizioni: una del 1985 scollegata da ANPR, e una del 1971 collegata al soggetto ANPR.
Sono passate più di 24 ore, per cui non è annullabile.

Il mio dubbio è solo su come avvisare AE di questo errore.
Penserei di procedere rettificando la data di nascita con gestioneCF=3 e successivamente gestire il disallineamento. In questo modo credo di risolvere ANPR e collegare il soggetto giusto.
E' corretto? E come il Comune deve avvisare AE per il soggetto del 1971?

**Comment by MarcoMigliori** [comment]
Provato a modificare con gestioneCF=3 ma non consente di variare i dati anagrafici di un soggetto validato.
Provato a modificare con gestioneCF=0 ma va in errore per la presenza di un altro soggetto.
Resto in attesa, il dato è ancora errato.

**Comment by MarcoMigliori** [comment]
grazie, avvisato il Comune

**Comment by MarcoMigliori** [comment]
Aggiornamento per documentazione: il comune si è rivolto allo sportello AE locale, che dopo qualche "insistenza" ha provato a fare il collegamento come suggerito.Viene respinto il collegamento in quanto trattasi di codice ANPR. Su indicazione dello sportello AE locale, il Comune ha mandato una mail alla direzione centrale dell'anagrafica AE. Siamo in attesa al momento.

**Comment by MarcoMigliori** [comment]
Risposta dall'Agenzia Entrate: "per i cittadini marcati come ANPR gli uffici dell'Agenzia sono impossibilitati a effettuare operazioni in Anagrafe Tributaria".
Provvedo a far inviare dal Comune una pec a Sogei con i dati da correggere.

**Comment by gcarbonin** [comment]
In questa situazione è soltanto la direzione centrale dell'Agenzia delle Entrate che può intervenire non l'ufficio locale dell'Agenzia

**Comment by MarcoMigliori** [comment]
Risolto. Grazie al contatto di Sogei mi hanno guidato nell'applicazione del capitolo "4.1 COLLEGAMENTO CODICI FISCALI "   del documento
"Appendice - Validazione del codice fiscale e dei dati anagrafici e risoluzione disallineamenti con l’Agenzia delle Entrate". Non mi ero accorto fosse stato aggiornato.
