### ISSUE TITLE
Carattere "/" nel numero civico degli indirizzi aire in subentro.

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#782]
Parecchi comuni ci segnalano la presenza dell'esponente nel civico degli indirizzi esteri degli AIRE che viene salvato separato da una barra, es. 6/B.
Tali indirizzi sono validi cosi' e fino ad ora nella documentazione non ci risulta che la tipologia del dato 
tipoNumeroCivicoEstero sia stata implementata per consentire di passare anche questo carattere "/" presente in AnagAire.

In alternativa i comuni pensano di spostare il contenuto del numero civico accostandolo alla denominazione del toponimo estero dove sono consentiti i caratteri in questione, per non perdere le informazioni esatte.

Fino ad ora li abbiamo sconsigliati di procedere in questo modo. Potete dirci se avete intenzione di 
implementare questa cosa nel subentro dell'AIRE e quando?

Grazie

Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
Il carattere "/" sarà incluso nel prossimo aggiornamento

**Comment by busaster** [comment]
Il problema capita di frequente anche a noi.
Per capire come dobbiamo comportarci con i clienti, potrebbe darmi una stima di rilascio della versione ANPR in cui sarà supportato ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
In test comuni e pre-subentro è disponibile la versione che accetta anche / e "." nel civico degli indirizzi AIRE
