### ISSUE TITLE
Annullamento mutazione famiglia con iscrizione rigettata

### ISSUE THREAD

**Issue by busaster** [italia/anpr#783]
Comune di Perugia, Ambiente di produzione.
Situazione :

1) Con decorrenza 27/04/2018 è stata eseguita con successo una mutazione 5001 per famiglia esistente (id ANPR 5094590).

2) Con la stessa decorrenza è stata poi eseguita con successo una iscrizione da non subentrato 1002 di soggetto nella famiglia del punto 1 (id ANPR 5096591)

3) in data 11/06/2018 la pratica che ha comportato l'iscrizione del punto 2 viene rigettata, quindi viene eseguita con successo una cancellazione 2003 per ripristino posizione precedente con stessa decorrenza dell'iscrizione 27/04/2018 (id ANPR 6073545)

4) Oggi a causa di accertamento negativo il comune deve rigettare il cambio di indirizzo del punto 1 ma riceve l'errore "EN077 : L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa" (id ANPR 12994616)

Non trovando altre operazioni abbiamo supposto siano l'iscrizione e la cancellazione dei punt i2 e 3 a dare fastidio, pur avendo la medesima decorrenza del cambio di indirizzo del punto 1.
Potete confermarcelo ?

In caso affermativo come dovremo procedere ? Non mia pare corretto da un punto di vista anagrafico annullare cancellazione ed iscrizione....

Grazie

Gianrico Busa per Maggioli Spa

**Comment by gcarbonin** [comment]
stiamo analizzando una soluzione Facciamo sapere al più presto

**Comment by gcarbonin** [comment]
Attualmente  la situazione è quella da lei descritta e abbiamo avviato un intervento. Per aggiornare velocemente la posizione la strada è quella di un 5001 con motivo 8 (Rettifica   indirizzo post accertamento) rimettendo l'indirizzo iniziale.

**Comment by busaster** [comment]
Con il workaround suggerito non è possibile rettificare la decorrenza della residenza con una data antecedente quella del cambio indirizzo che si deve annullare.
Per questo attendiamo la correzione  del problema.
Quando potrà essere disponibile ?

Grazie

**Comment by gcarbonin** [comment]
E' un intervento complesso che stiamo analizzando anche con il Ministero dell'Interno. faremo sapere quando disponibile

**Comment by Raffive** [comment]
Seguo, abbiamo gli stessi problemi.
Raffaella Spinea

**Comment by sfmodena** [comment]
Comune di Modena, ambiente di produzione
Buongiorno,
siamo molto interessati a questa evoluzione perchè come tutti abbiamo problemi ogni volta che si deve annullare una mutazione/cancellazione per soggetti che appartengono a famiglie con un alto tasso di movimentazione, soprattutto le convivenze. 
In particolare abbiamo urgenza di ripristinare il soggetto con idANPR 19260841 , cancellato l'  08/05/2018 per emigrazione in comune non subentrato e appartenente ad una convivenza sulla quale non possiamo annullare e reinserire le operazioni successive a quella data. Ora dobbiamo riversare sul soggetto una mutazione di stato civile; ci sono indicazioni sui tempi in cui sarà disponibile la modifica?
Grazie, saluti
Sonia Fiorini

**Comment by dierossi** [comment]
Comune di Parma -  Ambiente di produzione

Buongiorno,
siamo anche noi molto interessati a recepire quanto prima una modifica sostanziale alla gestione degli annullamenti/cancellazioni soprattutto quando i soggetti movimentati fanno parti di famiglie numerose, convivenze o provengono da comuni subentrati.

Ci troviamo spesso e volentieri ad annullare pratiche valide di immigrazione o mutazione residenza per poter annullare una pratica che ha subito un accertamento negativo; questo comporta per gli uffici comunali un aggravio considerevole di lavoro difficilmente sostenibile.

Esempio di oggi:
per annullare la pratica di mutazione da TORINO **idANPR 23889157** per accertamenti negativi ho dovuto annullare le pratiche di immi/mutazione **idANPR 32995995 e 24176351** regolarmente valide, per poi reinserirle successivamente.

Ci sono novità dal ministero sulle tempistiche di questa modifica???

**Comment by sfmodena** [comment]
Comune di Modena- Ambiente di produzione

Buongiorno, ci sono novità? Abbiamo alcuni casi fermi da mesi, in particolare soggetto con idANPR 19260841 sta diventando non rimandabile.
Grazie, saluti
Sonia Fiorini

**Comment by fferraguto** [comment]
Salve,
la nuova versione degli annullamenti è in linea.

@busaster Può cortesemente riprovare l'annullamento dell'operazione di Perugia.

@dierossi Con la nuova versione, le operazioni di iscrizione e cancellazione successive su altri soggetti della famiglia non inibiscono l'annullamento.

@sfmodena  Per quanto gli annullamenti adesso consentano maggiore libertà, per il soggetto 19260841 abbiamo rilevato la presenza di un'operazione di aggiornamento dei dati del matrimonio per il soggetto coniuge (id operazione anpr 34198048).
Per sanare la situazione può procedere in due modi alternativi:
1) Effettua una nuova iscrizione del soggetto alla data di cancellazione, con i dati del matrimonio corretti
2) Annulla nell'ordine l'operazione 34198048 e quella di cancellazione. Mi faccia sapere cortesemente quale opzione sceglierete.

Saluto tutti cordialmente e mi scuso per la lunga attesa.

**Comment by sfmodena** [comment]
Comune di Modena- Ambiente di produzione

@fferraguto : Buongiorno, abbiamo scelto la seconda opzione, annullando prima la mutazione di divorzio sul coniuge poi la cancellazione del soggetto 19260841, reinserendo poi il divorzio per entrambi. Ha funzionato tutto, grazie.
Saluti
Sonia Fiorini

**Comment by busaster** [comment]
@fferraguto A Perugia l'annullamento è andato a buon fine
Grazie

**Comment by dierossi** [comment]
@fferraguto Confermo che anche a Parma l'annullamento è andato a buon fine

Grazie

Diego

**Comment by fferraguto** [comment]
@dierossi potrebbe cortesemente fornirmi l'id dell'operazione di annullamento?

**Comment by dierossi** [comment]
> @dierossi potrebbe cortesemente fornirmi l'id dell'operazione di annullamento?

@fferraguto l'id dell'operazione dovrebbe essere 50814542
