### ISSUE TITLE
[5014] Modificare la data di decorrenza dell'immigrazione

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#787]
Buongiorno, 
stiamo cercando di rettificare la data di decorrenza di una immigrazione da comune non subentrato (l'operatore ha erroneamente indicato la data corrente invece della data dichiarata).
Stavo provando in ambiente di TEST a rettificare l'informazione con il servizio 5014:
- Provando a inviare la rettifica 101 (data decorrenza residenza) con la data corretta ottengo l'errore EN414: "Rettifica non permessa in quanto la data di decorrenza residenza e' presente e congruente" (Id Operazione ANPR: 15678723)
- Provando a inviare la rettifica 103 (una qualsiasi delle date o anche tutte insieme) ottengo l'errore EN475: "Sono presenti modifiche con data decorrenza successiva al subentro, non e' possibile eseguire la rettifica delle date" (Id Operazione ANPR: 15678724)

Ho provato anche a fare una prova tra comuni subentrati (sempre in ambiente di test) e facendo la rettifica 101 ottengo l'errore EN427 - Rettifica non permessa: Comune non competente (Id Operazione ANPR: 15678708)

Come posso risolvere il problema?

Ringrazio anticipatamente per la collaborazione

**Comment by gcarbonin** [comment]
Per ora il comune deve inviare una PEC con la richiesta di modifica della data (speciificando l'id del soggetto)
