### ISSUE TITLE
Web App- Registrazione/Iscrizione altri motivi 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#79]
Data test 03/04/2017 - Ambiente test (dptest)
Registrazione/Iscrizione altri motivi 
Inserito un soggetto (ID ANPR 4205099) senza CF con scelta gestione CF "Iscrizione senza verifica CF", in questo specifico caso dovrebbe comparire un messaggio BLOCCANTE che indichi che il CF non è stato inserito.  
Grazie 
Annamaria Gillone

**Comment by gcarbonin** [comment]
Penso si riferisca alla scelta Iscrizione/Modifica senza validazione CF. Questa opzione e' stata appositamente prevista per consentire al comune di perfezionare comunque una registrazione, Quindi l'errore è VOLUTAMENTE non bloccante (come per altro indicato nella documentazione).
