### ISSUE TITLE
Problemi legati a subentro con pratica anagrafica in lavorazione

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#790]
Buonasera.

Sono l'ufficiale d'anagrafe del Comune di Biassono.

Ho un problema legati ad una pratica di residenza e dei soggetti che adesso risultano duplicati.
Riporto i fatti in ordine cronologico.

-09/07/2018: iscrivo in ANPR i soggetti 27864512 e 27864511 con decorrenza 09/07/2018 per provenienza dal comune con cod. istat 15146, all'epoca non ancora subentrato - aggregazione alla famiglia num. 9081346;

-14/07/2018: il comune 15146 subentra in ANPR senza aver cancellato in precedenza i propri soggetti; risultato è che in ANPR ci sono dei duplicati:
30335641 è il duplicato di 27864512, 
30335719 è il duplicato di 27864511;

Se eliminassi le schede ANPR num. 27864512 e 27864511 e rifacessi una nuova pratica di residenza con le schede 30335641 e 30335719 per aggregazione alla famiglia 9081346 con decorrenza 09/07/2018, il sistema ANPR mi potrebbe dare degli errori?

In attesa di un vostro gentile riscontro, porgo cordiali saluti.

I miei riferimenti sono:

Andrea Paltrinieri
e-mail: paltrinieri.andrea@biassono.org
tel. 039-2201060

**Comment by gcarbonin** [comment]
Secondo me non è corretto: è il comune 15146 che deve cancellare le persone procedendo come prevede il regolamento anagrafico  (a questo punto per doppia iscrizione). Forse anche la issue 789 rappresenta una situazione analoga: controlli prima di procedere con la cancellazione.

**Comment by paltrinan** [comment]
1.Quindi, se ho capito bene, sollecito il Comune 15146 ai fini della cancellazione?

2.La issue 789 è leggermente diversa; in quel caso ho fatto io degli errori a sistema tali per cui non so come procedere per iscrivere i soggetti 27679733, 27679731, 27679732 e 27679728 in questo comune con decorrenza dal 02/07/2018.

In attesa di un vostro riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by paltrinan** [comment]
nel frattempo ho sollecitato la cancellazione dei soggetti 30335641 e 30335719 al comune 15146

**Comment by paltrinan** [comment]
la issue 789 è stata chiusa perchè sono riuscito a trovare il modo di sistemarla.

**Comment by gcarbonin** [comment]
Confermo che la procedura di cancellazione per doppia iscrizione da parte di 15146 è la strada corretta
