### ISSUE TITLE
[1002] Errore in iscrizione di soggetto cancellato per doppia iscrizione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#791]
Recanati - Ambiente di Produzione

Dobbiamo iscrivere un soggetto che in ANPR risulta avere una posizione di cancellato da Milano per doppia iscrizione.

In un primo tentativo (id operazione ANPR 15235041) abbiamo usato il servizio 1002 specificando nelle generalità del soggeto anche il suo id anpr, ottenendo però l'errore "EN187 : il Soggetto XXXXXXXXXXXXXXXXXXXXXXXXXXXX e' gia' iscritto o deceduto", dove al posto di XXXXXXXXXXXXXXXXXXXXXXXXXXXX ci sono le generalità.
Quanto dice il messaggio non è però vero, il soggetto è cancellato per doppia iscrizione.

Tentando una strada alternativa abbiamo effettuato un secondo tentativo (id operazione ANPR 15237297) non specificando il campo id anpr nelle generalità del soggetto, ottenendo però l'errore "EN188 : Soggetto XXXXXXXXXXXXXXXXXXXXXXXXXXXX, gia' presente su ANPR", dove al posto di XXXXXXXXXXXXXXXXXXXXXXXXXXXX ci sono le generalità.

A questo punto non sappiamo cosa fare, come dobbiamo comportarci per iscrivere il cittadino ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve, abbiamo contattato il comune di Milano che ha annullato la cancellazione.
Dato che è presente una sola scheda, dovrebbe essere sufficiente un cambio di residenza come sempre in questi casi.
Saluti

Assistenza ANPR
