### ISSUE TITLE
[WA] Rilascio CI ed alterazione dati di iscrizione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#792]
Ambiente di Test - Poggio a Caiano

Con la webapp abbiamo rilasciato una CI ad un nostro soggetto (id operazione ANPR 15693029).
Consultando poi XMl di risposta ottenuto con il servizio 3003 troviamo che viene restituito in essa anche  il tag "datiIscrizione" con i subtag "datiIscrizione->datiIscrizioneComune->idOperazioneANPR" popolato con l'ID ANPR della mutazione di carta di identità.
Abbiamo verificato che fortunatamente il valore di tale campo nei dati AP5 del soggetto non è variato per cui immagino sia un difetto di compilazione del XML risposta.

Potete verificare ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
E' la risposta del 5008 che si interroga con il 3003 che non è corretta, I dati di iscrizione, per altro, con il 5008 non possono essere variati e sono quindi ridondanti  e possono essere ignorati.
