### ISSUE TITLE
Impossibilità a cancellare da ANPR soggetto emigrato in altro comune

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#793]
Premessa:

Il soggetto 18934817 era residente nel nostro comune (108009) - comune già subentrato;
Il giorno 13/07/2018 presenta dichiarazione di residenza nel Comune 15146 per provenienza dal comune 108009;
Nei giorni successivi, il comune 15146 crea un duplicato del soggetto 18934817  in ANPR con codice 30188988 ed invia la pratica migratoria al nostro comune 108009;
Nel frattempo, il comune 15146 subentra in ANPR con decorrenza 14/07/2018;

Dal sistema ANPR non riesco a cancellare per emigrazione con decorrenza 13/07/2018 il soggetto 18934817 in quanto ANPR segnala che il comune 15146 è già subentrato.

Ho già sollecitato via PEC il Comune 15146 ad annullare/eliminare la propria scheda 30188988 ed effettuare la mutazione direttamente sulla 18934817.

A questo punto, cosa posso fare? 

I miei riferimenti sono i seguenti:
Andrea Paltrinieri - Ufficiale d'Anagrafe del Comune di Biassono
e-mail: paltrinieri.andrea@biassono.org
tel. 039-22.010.60

In attesa di un Vs. riscontro porgo cordiali saluti.

**Comment by gcarbonin** [comment]
Deve fare una cancellazione per doppia iscrizione non per emigrazione

**Comment by paltrinan** [comment]
Ho appena effettuato la cancellazione anagrafica da Lei indicata.

Ringrazio per la collaborazione e porgo cordiali saluti.

Andrea Paltrinieri
