### ISSUE TITLE
Problemi con data di nascita riportata in scheda soggetto 18930628

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#794]
Il soggetto 18930628 è nato in data 11/03/1941. 
La data di nascita sul portale ANPR viene visualizzata correttamente: 11/03/1941; sull'applicativo del comune 108009, che utilizza i web services, viene visualizzata la data di nascita sbagliata: 10/03/1941.
Come posso fare a risolvere questo problema?

I miei riferimenti sono:
Andrea Paltrinieri - Ufficiale d'Anagrafe del Comune di Biassono
Tel. 039-22.010.60
e-mail: paltrinieri.andrea@biassono.org 

In attesa di un Vs. gentile riscontro, porgo cordiali saluti.

Andrea Paltrinieri

**Comment by MarcoMigliori** [comment]
Credo debba rivolgersi al suo fornitore

**Comment by mttfranci** [comment]
Salve.

Le confermiamo che devrebbe rivolgersi alla software house.

E' già capitato in passato che ci fossero alcuni disallineamento nel trattamento delle time zone e l'ora legale.

In particolare il 1941 ha fatto eccezione e l'ora legale è stata in vigore per tutto l'anno.
Alcuni sistemi (come ANPR) utilizzano per trattare le time zone gli elenchi storici delle validità delle ore legali.
Altri sistemi (come probabilmente il vostro gestionale) si basano su regole standard di applicazione (che nel caso del 1941 non sono valide).

Se vuole dare qualche informazioni alla sua software, 
Ecco un estratto della risposta del servizio ANPR : 
<dataNascita>1941-03-11+02:00</dataNascita>

Cordiali saluti

Assistenza ANPR.
