### ISSUE TITLE
[2001] Errori W al subentro, ma E per i servizi

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#797]
Buongiorno, qualche giorno fa abbiamo incontrato questo problema: non ci registrava in ambiente produzione la morte di un cittadino con errore 999 "Operazione non effettuabile". Errore troppo generico che ci spiazza, finchè non vediamo sul cittadino in questione una anomalia al subentro EHR71 "anno dell'atto di matrimonio 0 non valido".

Risolvendo prima il problema sull'atto di matrimonio con mutazione dati, è stata poi accettata la cancellazione per decesso.

Sicuramente sarà capitato in precedenza a tanti altri, per me era il primo caso e vado a documentarmi sull'errore EHR71:
- Vado a ricontrollare il file anomalie ricevuto al subentro denominato 043043SchedeIndivErr20180619.csv dove trovo il codice errore e la descrizione, senza tipologia di Errore Warning o altro.
- controllo quindi la documentazione "Elenco segnalazioni ANPR sulle operazioni anagrafiche - xls" dove è classificato come E 
- mentre in "Anomalie al subentro e operazioni di registrazione - xls" lo segnala come problema per la sola certificazione di matrimonio
- nella guida pdf ANPR a pag.171 leggo che l'errore è W per il subentro e E per i servizi.

Vi segnalo per le vostre valutazioni:
- negli esiti del subentro non potrebbero essere messe le due colonne W per il subentro, e E per i servizi?
- l'errore generico può essere migliorato? magari suggerendo di controllare eventuali anomalie al subentro? lo chiedo anche perchè se è classificato come E per i servizi in uno dei documenti, dovreste essere in grado di intercettarlo in modo più comprensibile all'utente?
- al contrario di quanto indicato in uno dei documenti, pur in presenza dell'errore la certificazione di matrimonio viene emessa.
- sarebbe possibile accentrare magari come tabella di decodifica scaricabile, le informazioni sugli errori?

**Comment by gcarbonin** [comment]
Rispondo direttamente sui singoli punti:
- negli esiti del subentro non potrebbero essere messe le due colonne W per il subentro, e E per i servizi?
La tabella in origine era fatta così; è stata modificata su suggerimento di altri. Ora sono due distinte

- l'errore generico può essere migliorato? magari suggerendo di controllare eventuali anomalie al subentro? lo chiedo anche perchè se è classificato come E per i servizi in uno dei documenti, dovreste essere in grado di intercettarlo in modo più comprensibile all'utente?

L'errore generico esce in presenza di particolari circostanze che analizziamo noi attraverso i nostri log e progressivamente viene eliminato

- al contrario di quanto indicato in uno dei documenti, pur in presenza dell'errore la certificazione di matrimonio viene emessa.

Se può indicare la persona interessata, possiamo controllare (dipende dal dato mancante la propduzione o meno del certificato di matrimonio) 
- sarebbe possibile accentrare magari come tabella di decodifica scaricabile, le informazioni sugli errori?

Come detto sopra, le tabelle sono già presenti e sono due distinte (si trovano in questa pagina https://www.anpr.interno.it/portale/documentazione-tecnica)

**Comment by MarcoMigliori** [comment]
Certificato di matrimonio ambiente di test per:
Identificativo scheda attribuito da ANPR: 16436980
Errori/Anomalie da Subentro
Codice errore/anomalia: EHR71
Tipo errore/anomalia: 1
Testo errore/anomalia: Anno dell'atto di matrimonio 0 non valido

**Comment by gcarbonin** [comment]
Aggiorniamo la documentazione

**Comment by gcarbonin** [comment]
La documentazione è stata aggiornata (Anomalie al subentro e operazioni di registrazione disponibile a questo link https://www.anpr.interno.it/portale/documentazione-tecnica).
