### ISSUE TITLE
Valorizzazione del campo "idFamigliaComune"

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#8]
L'identificativo della famiglia è costituito da ""FE""+<idfamigliacomune>. Nel richiamare i WS per l'iscrizione in AIRE dobbiamo quindi valorizzare il tag conseguentemente o basta indicare l '&lt;idfamigliacomune&gt; ed il sistema provvede ad anteporre ""FE""?

**Comment by gcarbonin** [comment]
Vedi risposta al quesito dati AIRE
