### ISSUE TITLE
ws [5008] - errore "EAM91 - soggetto NON marcato ANPR"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#800]
Buon giorno, 
abbiamo effettuato un'iscrizione "per altri motivi" di un individuo in ANPR utilizzando il ws 1002 (id operazione comune 5006) e successivamente abbiamo utilizzato il ws 5008 per effettuare una variazione di generalità (Id operazione comune 5015), ma l'operazione fallisce con l'errore in oggetto.
Effettuando la consultazione AE per il codice fiscale dell'individuo, risulta in effetti "presente in AT (NON marcato ANPR)". 
Abbiamo verificato che la request "1002" con cui abbiamo effettuato l'operazione di iscrizione è del tutto identica ad un'altra, effettuata in data 18 luglio (id operazione comune 4948), in cui il soggetto iscritto risulta però con codice fiscale "marcato ANPR".
Le operazioni sono state effettuate in ambiente di test per il comune di Teramo, chiediamo pertanto se ci sia stata una qualche variazione nelle specifiche che comporta la necessità di modificare le request 1002 o 5008, o qualche errore nelle stesse che ci è sfuggito.
Giuseppe Mucciarelli, TINN srl

**Comment by gcarbonin** [comment]
Buon giorno. sarebbe utile in questi casi fornire l'identificativo della persona o dell'operazione. Grazie

**Comment by gcarbonin** [comment]
Le due operazioni (iscrizione e mutazione) sono state effettuate nella stessa giornata a meno di un'ora di distanza l'una dall'altra. Questo può generare l'errore che avete riscontrato in quanto AE consolida il soggetto (lo marca ANPR) soltanto quando elabora la notifica inviata da ANPR (vedi pag. 138 delle specifiche).  Riprovi ora e ci faccia sapere se incontra di nuovo il problema.
