### ISSUE TITLE
codice comune CASTELLO

### ISSUE THREAD

**Issue by StoroTN** [italia/anpr#801]
Ho difficoltà con la gestione delle persone nate nel comune di CASTELLO (TN) in quanto nella documentazione ANPR sono presenti:
24/12/1946	03/08/1955	22045	C183	CASTELLO TN
05/02/1923	08/09/1928	22820	C182	CASTELLO TN
16/10/1920	04/02/1923	802089	C182	CASTELLO TN
16/10/1920	04/02/1923	802084	C183	CASTELLO TN
05/02/1923	13/03/1928	22045	C183	CASTELLO TN

In pratica in Trentino ci sono 2 comuni di Castello e precisamente uno in valle del Chiese  con codice C183 e  22045 (ora comune di Castel Condino) e  in val di Sole  con codice C182 e 22820 (ora comune di Pellizzano).
Per ANPR in base all'anno di nascita è possibile risalire al codice comune corretto, ma il problema si presenta con :
1) portale dell'agenzia delle Entrate: è presente un solo CASTELLO con codice C182 (non c'è possibilità di scelta del C183)
2) portale INA: è presente un solo CASTELLO con codice C183 ma con codice ISTAT 22820 (i codici sono mescolati)

E' possibile segnalare all'Agenzia delle Entrate ed INA di aggiornare le tabelle?

Grazie 
Dario Zontini

**Comment by gcarbonin** [comment]
L'Agenzia delle Entrate sta già adeguando i propri archivi. Per l'archivio INA provvediamo.

**Comment by rnapoli1983** [comment]
Abbiamo inserito in INA gli storici richiesti.

Le modifiche saranno effettive e disponibili nella giornata di domani.

Buona giornata.

Cordiali saluti
