### ISSUE TITLE
[3002] msg. "Internal Error (from server)"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#803]
ambiente di TEST - comune di Faenza - idOperazione 2018302169

si tenta la consultazione delle schede individuali per cognome e nome.
la richiesta ritorna l'errore in oggetto
immagino ci sia qualche carattere strano nella risposta che blocca il flusso lato ANPR.
vi chiederei di verificare per sicurezza, giusto per capire se ci sono in effetti problemi nei dati oppure se c'è qualche altro problema nell'acquisizione della risposta da parte nostra.

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, la ricerca è stata eseguita per nome e cognome e restituiva oltre 40 record.
C'era una discrepanza su un dato di uno dei soggetti di comune diverso da Faenza (la ricerca è nazionale).
Ora il dato dovrebbe essere stato corretto ed è possibile riprovare.
Saluti

**Comment by AMonopoliADS** [comment]
confermo che adesso non compare più l'errore ed il web-service risponde con la lista dei soggetti richiesti.
grazie
