### ISSUE TITLE
[WEBAPP] allineamenti con Agenzia Entrate - Esito AE: Operazione non effettuabile (Codice 95)

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#804]
Buongiorno,

Da ieri almeno, in ambiente di PreProduzione, non sembra più possibile validare i codici fiscale con AE utilizzando la funzionalità "Risoluzione disallineamenti con Agenzia Entrate" dal menu "Utilità e notifiche" della WEB APP.
Selezionando soggetti dall'elenco dei soggetti presenti in AE fornito alcuni mesi fa, abbiamo sempre l'errore :
Esito AE: Operazione non effettuabile (Codice 95)

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by Raffive** [comment]
Buongiorno,
anche noi continuiamo ad avere problemi che sembrano nascere da AE soprattutto doppie posizioni create da AE che restituiscono :
-  operazione non effetuabile oppure
-  con il codice EAM9C (che non trovo sulle tabelle) individuate due posizioni in AT non unificabili
Grazie
Raffaella 
Spinea

**Comment by gcarbonin** [comment]
"Operazione non effettualbile" indica un problema di comunicazione con Agenzia delle Entrate che si risolve di norma ripetendo l'operazione subito dopo. Se così non fosse, ci occorrono segnalazioni puntuali che verifichiamo, I nostri sistemi di monitoraggio non evidenziano criticità in ambiente di produzione, La segnalazione di pre-subentro la stiamo verificando.
L'altro errore dipende dal fatto che la persona ha due codici fiscali non collegati tra loro e non collegabili. Non sono collegabili, in particolare, i codici fiscali provvisori rilasciati ai rifugiati con quello definitivo. Su questo c'è un intervento in corso che coinvolge l'Agenzia delle Entrate. Stiamo comunque ampliando la documentazione per indicare i casi in cui il comune NON può collegare i codici fiscali ma deve inviare una segnalazione alla Direzione Centrale che ha in carico questa gestione.

**Comment by pissardl** [comment]
Adesso sembra funzionare di nuovo in PreSubentro, 
Penso si possa chiudere la segnalazione.

**Comment by rvinzani** [comment]
Grazie del riscontro
