### ISSUE TITLE
Chiarimento su ricomparsa in comune non subentrato

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#805]
Ipotesi:
- sono comune subentrato e cancello cittadino per irreperibilità
- in seguito mi arriva apr4 da altro comune a cui il cittadino ha richiesto l'iscrizione

In ANPR non è richiesta alcuna registrazione.
Come conseguenza in ANPR non vedrò il comune di nuova iscrizione, che verrà visualizzato attraverso INA, con registrazione a carico del comune di nuova iscrizione.
Corretto?

**Comment by gcarbonin** [comment]
SI

**Comment by MarcoMigliori** [comment]
Grazie.
