### ISSUE TITLE
[Presubentro] errore EC004 su sciglimento unione civile

### ISSUE THREAD

**Issue by busaster** [italia/anpr#806]
Comune di Mantova, esiti presubentro.
Per il cittadino idAnpr=77000526 viene ritornato l'errore EC004 "Codice tipo tribunale 4 inesistente sulla tabella di riferimento"

Il cittadino in questione ha i dati di scioglimento unione civile.
Sul nostro archivio l'autorità che ha effettuato lo scioglimento è "ufficiale di stato civile" per cui abbiamo inviato "<tipoTribunale>4</tipoTribunale>", come da tabella di decodifica ANPR N. 32.

Non riusciamo a capire l'errore, potete aiutarci ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
Nessun errore da parte vostra, ma un refuso nella nostra gestione;  per il momento ignorate l'anomalia, già  dal prossimo invio non si presenterà.
