### ISSUE TITLE
[6001] Certificato con carattere non ammesso in annotazione

### ISSUE THREAD

**Issue by busaster** [italia/anpr#807]
Ambiente di test - Poggio a Caiano

Nel certificato inviamo come annotazione il testo "Recupero stampati € 1,58".
Questo funziona perfettamente con gli XSD della versione ANPR00, mentre restituisce un errore di validazione con i nuovi XSD ANPR01, poiché il carattere € non è compreso nel campo di validità del tipo dato "tipoRigaAnnotazione".

Potete aggiungerlo ai caratteri supportati delle annotazioni ?

Grazie

**Comment by busaster** [comment]
Il problema comincia a presentarsi anche in produzione, ora che usiamo la versione ANPR01.
Spesso i nostri clienti usano mettere nel campo annotazioni il carattere €.
Potreste renderlo utilizzabile al più presto ?
Grazie

**Comment by COMUNE-JESI** [comment]
Buongiorno, si segnala che anche nel nostro comune abbiamo il rimborso stampati di € 0.29 e non possiamo rilasciare i certificati in quanto viene bloccato il rilascio, Si richiede urgentemente la risoluzione del problema.

**Comment by bfilipazzi** [comment]
Abbiamo almeno una ventina di clienti con questo problema.
E' possibile conoscere una data di soluzione?
Grazie.
Filipazzi - Maggioli

**Comment by mttfranci** [comment]
Dovremmo rilasciare la modifica in settimana. Vi avvisiamo appena effettivamente disponibile. Saluti

**Comment by Raffive** [comment]
buongiorno comune di Spinea subentrato 
Noi rilasciamo anche certificati on line e per uso notifica a diritti di segreteria ZERO 
Regolarmente deliberato dalla Giunta Comunale considerato che è nelle sue prerogative.
Mi auguro che la modifica consenta alla mia Software house di tarare sulla mia necessità il rilascio del certificato.

**Comment by Raffive** [comment]
scusate saluti 
grazie 
Raffaella

**Comment by mttfranci** [comment]
Il carattere euro dovrebbe venire accettato nella riga annotazione dei certificati con la versione appena rilascita (4.1.13) : 
Con la versione 4.1.13 è possibile eseguire l'upload dei file del subentro solo con le nuove regole : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

**Comment by mccalv** [comment]
Sassari aaAa AaA

**Comment by busaster** [comment]
Dove posso trovare XSD e WSDL di questa nuova versione ?
E per quando è previsto il suo rilascio in produzione ?

Grazie

**Comment by mttfranci** [comment]
La documentazione verrà aggiornata sul portale.
Anticipiamo qui le [note_rilascio_4_1_13.zip](https://github.com/italia/anpr/files/2565215/note_rilascio_4_1_13.zip)

**Comment by busaster** [comment]
aprendo il file "tipoDato.xsd" in UTF vedo che ci sono caratteri non stampabili 
![image](https://user-images.githubusercontent.com/1733338/48265346-95ef9300-e42c-11e8-96da-4b6e9cb20cce.png)

**Comment by mttfranci** [comment]
Si tratta di alcuni diacritici inseriti in seguito alla segnalazione #861 in quanto previsti dalle specifiche.

Usando ad esempio le ultime due versione di Eclipse vengono visualizzati correttamente con i valori decimali.

![utf8](https://user-images.githubusercontent.com/29305782/48266963-3f388800-e431-11e8-904b-467c75cdd4be.png)

**Comment by mttfranci** [comment]
@busaster @bfilipazzi @Raffive @COMUNE-JESI Salve, Dopo l'aggiornamento è stato possibile emettere i certificati?

**Comment by busaster** [comment]
In ambiente di test il problema è risolto, in produzione i nostri clienti (Maggioli) dovranno attendere il rilascio del modulo di colloquio ANPR adeguato ai nuovi XSD.
