### ISSUE TITLE
[6001] Chiarimenti su certificazione

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#81]
Buongiorno

1) nel certificato (es.stato di famiglia) manca l'indicazione della validità: 3 mesi dalla data del rilascio (art.33 c.3 regolamento). E' una scelta?

2) stato famiglia con rel.parentela. se tento di emetterlo per l'id anpr 1217051, richiesto dall'id anpr 1217057 (madre) ottengo questo messaggio di errore:
"_Il certificato richiesto può essere richiesto solo da un componente della stessa famiglia_"

3) la mancanza di una certificazione storica di residenza per periodo, invece che a una data precisa, è una scelta definitiva?

**Comment by gcarbonin** [comment]
1. e' una indicazione del Ministero
2, controlliamo
3. puo' anche essere non definitiva ma non sono scelte effettuate da Sogei
