### ISSUE TITLE
Nuovi xsd e specifiche dal 18/09/2018 - Richiesta chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#812]
in riferimento all'avviso di cui alla issue #775 , segnalo che nel link del portale anpr.interno.it ("Nuovi xsd e specifiche sull’utilizzo caratteri speciali in vigore dal 18 settembre 2018 - rar") non sono presenti gli xlsx con le Appendici che invece sono presenti nel .zip pubblicato su github (non so se sia voluto...)

approfitto x chiedere:
1. sempre sul portale, pagina "documentazione-tecnica", al link "Tracciati XSD e WSDL - rar" sono ancora collegati gli schemi aggiornati al 30/05.
quelli in vigore dal 18/9, verranno inseriti il 18/9?
2.  dal 18/9 il tag codDestinatario della testataRichiesta, dovrà essere valorizzato con ANPR01, oppure sarà ininfluente ai fini dei nuovi controlli di validazione?

grazie
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Salve, dopo una analisi sul livello di adozione delle nuove specifiche, la data di rilascio è stata posticipata di qualche giorno e sono stati aggiunti alcuni chiarimenti tramite la issue #819.

**Comment by AMonopoliADS** [comment]
grazie
