### ISSUE TITLE
[3002 / 6001] Errore EN212 (msg. "... la famiglia e' ancora in fase di registrazione")

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#813]
ambiente di TEST - comune di FAENZA

stiamo facendo delle prove in seguito ad una situazione "tipo" che si è verificato da un cliente in produzione.

si tratta del blocco di certificabilità sulla famiglia prodotto dalla registrazione del matrimonio di due componenti appartenenti al nucleo (rif. Specifiche di interfaccia dei servizi per i comuni § 11.3.1)

idFamigliaANPR 12868250
i due componenti presenti risultano IS e Convivente.
è stato registrato il matrimonio tra i due, ma non sono ancora stati modificati i rapporti di parentela.
l'interrogazione della famiglia (ws 3002) segnala (come previsto) l'anomalia
```
  <erroriAnomalie>
    <codiceErroreAnomalia>EN212</codiceErroreAnomalia>
    <tipoErroreAnomalia>3</tipoErroreAnomalia>
    <testoErroreAnomalia>Non puo&apos; essere emesso il certificato richiesto perche&apos; la famiglia e&apos; ancora in fase di registrazione</testoErroreAnomalia>
  </erroriAnomalie>
```
la documentazione dice che non sarà possibile emettere lo stato di famiglia con rapporto di parentela, ma il sistema l'ha comunque prodotto
idOperazioneComune 2018600264 e 2018600265

non capisco se stiamo interprendando male noi la documentazione, oppure se c'è qualcosa che non funziona.

grazie.
Alessandro Monopoli ADS

**Comment by rnapoli1983** [comment]
Buongiorno, la vostra interpretazione è assolutamente corretta.

Abbiamo provveduto ieri alla risoluzione del problema.

Potete testare nuovamente il servizio di certificazione ed, in questo caso il certificato da voi richiesto, non dovrebbe essere prodotto per le stesse motivazioni presenti nella risposta ottenuta da ws 3002.

Cordiali saluti.

**Comment by AMonopoliADS** [comment]
abbiamo provato.
adesso il ws 6001 blocca la richiesta con il messaggio:
```
<errore>
  <codiceErroreAnomalia>EN222</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Il certificati di stato di famiglia con rapporti di parentela non puo' essere emesso fiche' non si rivedono i rapporti di parentela con l'intestatario</testoErroreAnomalia>
</errore>
```

segnalo però:
- una imprecisione nel testoErrore: "fichè" invece di "finchè"
- un difetto: l'errore blocca anche l'emissione di Stato di Famiglia senza Rapporti di Parentela (tipoCertificato '12')

**Comment by rnapoli1983** [comment]
Grazie mille per le segnalazioni.

Per la prima provvediamo alla correzione.

Per la seconda, le direttive prevedono che tale controllo sia presente in tutti i certificati di Stato di Famiglia.

Sarà nostra premura presentare la problematica e nel caso rimuovere il controllo per il tipoCertificato 12.

Buona giornata.

Cordiali saluti.

**Comment by rnapoli1983** [comment]
Scusate analizzando la logica di servizio, in merito alla seguente problematica:

"l'errore blocca anche l'emissione di Stato di Famiglia senza Rapporti di Parentela (tipoCertificato '12')..."

abbiamo riscontrato che:

- Il codice dell'errore è corretto (EN222) ;

- la descrizione è totalmente errata e provvediamo alla correzione. Il certificato non potrà essere 
  prodotto perchè la famiglia risulta "non certificabile".  Il controllo della validità dei rapporti di parentela, 
  per il  tipoCertificato 12, non è applicato;

 Quando le nostre correttive saranno effettive ve lo comunicheremo.

 Cordiali saluti

**Comment by rnapoli1983** [comment]
Abbiamo apportato le modifiche.

Cordiali saluti.
