### ISSUE TITLE
[Testata richiesta] - ID operazione Comune

### ISSUE THREAD

**Issue by GianM67** [italia/anpr#814]
Buongiorno.

Nelle specifiche è riportato che il tag "idOperazioneComune" ha formato AN (Alfanumerico)
Nelle "Regole/Condizioni" viene riportato "Numerico crescente".
E' dunque possibile attribuire un ID alfanumerico (esempio **ABC1**).
Il sistema verifica poi che alle richieste successive sia attribuito un numero crescente (ossia **ABC2**, **ABC3** e così via).
Corretto?  

Grazie e cordiali saluti.
Stesei  -  Gianluca Manzin

**Comment by gcarbonin** [comment]
Deve essere numerico e possibilmente crescente

**Comment by Eduardo1977** [comment]
#596

**Comment by GianM67** [comment]
Ho visto che il problema della gestione dell'ID Operazione era già stato evidenziato.
Scusatemi per l'apertura di questa nuova discussione.
La necessità di trovare una soluzione è a mio avviso pressante.
Se posso dare un suggerimento, un'idea potrebbe essere quella di trasformare almeno il campo da numerico ad alfanumerico.
Grazie per l'attenzione.

**Comment by bfilipazzi** [comment]
Vorrei dichiarare una preferenza per il metodo proposto nella issue 596.
Grazie.
Filipazzi - Maggioli

**Comment by GianM67** [comment]
Sicuro.
Sottolineo comunque l'importanza di trovare una soluzione in tempi brevi.
Grazie.
Stesei  -  Manzin

**Comment by GianM67** [comment]
Buongiorno.
Avete avuto modo di affrontare il problema dell'ID Operazione esposto in questa issue e nella issue 596?
Grazie mille.
Saluti.
Stesei  -  Gl. Manzin

**Comment by mttfranci** [comment]
Abbiamo deciso di rendere alfanumerico l’id operazione comune in testata.
Vi informeremo appena la modifica sarà stata rilasciata
Suggeriamo comunque a tutti le software house di seguire delle best practice che riducano al massimo le probabilità di conflitti.
Una possibilità è inserire la data all’interno dell’id operazione comune (ad es. 20181003) al fine di dover gestire i conflitti sugli id in un periodo ristretto.

**Comment by GianM67** [comment]
Bene, grazie.
Ci potrebbe gentilmente segnalare i tempi previsti per il rilascio della modifica?
Grazie molte.
Saluti.
Stesei  -  Gl. Manzin

**Comment by mttfranci** [comment]
L'intervento è stato rilasciato.

**Comment by Eduardo1977** [comment]
Buongiorno,
sto avendo problemi con questo aggiornamento oppure non ho capito come funziona. Adesso dovrebbe essere possibile assegnare valori alfanumerici giusto? Tipo **abc123** ?
In ambiente PROD ricevo l'errore "Formato della stringa di input non corretto." Eppure qualche settimana fa in PRE_SUB l'avevo testato e rispondeva correttamente...

**Comment by mttfranci** [comment]
Si la modifica è rilasciata in tutti gli ambienti.

Ricordiamo che : 

Il change log contiene l'elenco degli interventi inclusi in ogni versione di ANPR : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
(in particolare l'estensione dei valori del campo idOperazioneComune era nella versione 4.1.3).

L'elenco versioni invece mostra quale versione è presente in ogni ambiente : 
https://github.com/italia/anpr/blob/master/src/change-management/version.md
(Al momento in cui scriviamo in tutti gli ambienti è disponibile la versione 4.1.18).
