### ISSUE TITLE
[2011] Annullamento Cancellazione - EN077

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#815]
In ambiente di Produzione, 
L'operatore ha provato ad annullare una cancellazione sul soggetto idSchedaSoggettoANPR:28147895
con il servizio 2011, idOperazioneComune:335442
```<ns2:Richiesta2011 xmlns:ns2="http://sogei.it/ANPR/2000cancellazione">
    <testataRichiesta>
        <idOperazioneComune>335442</idOperazioneComune>
        <codMittente>001272</codMittente>
        <codDestinatario>ANPR01</codDestinatario>
        <operazioneRichiesta>2011</operazioneRichiesta>
        <dataOraRichiesta>2018-09-12T09:10:49.509+02:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>PROD</tipoInvio>
        <dataDecorrenza>2018-07-31+02:00</dataDecorrenza>
        ...
    </testataRichiesta>
    <datiOperazioneDaAnnullare>
        <operazioneRichiesta>2003</operazioneRichiesta>
        <idOperazioneComune>194366</idOperazioneComune>
        <idOperazioneANPR>15084000</idOperazioneANPR>
    </datiOperazioneDaAnnullare>
	...
```
Abbiamo avuto errore 
 EN077-L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa
il soggetto non presenta nessun'altra operazione oltre 2003 con idOperazioneANPR:15084000 sia dal nostro applicativo, sia da WebApp.

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
Il motivo è che si tratta di due coniugi, sul coniuge è stata effettuata successivamente una mutazione di relazione di parentela.  Per quale motivo dovete annullare?

**Comment by pissardl** [comment]
Vogliono fare emigrare per primo il coniuge.

**Comment by gcarbonin** [comment]
Si deve annullare l'operazione di mutazione relazioni di parentela (operazione 15084004) e poi la cancellazione
