### ISSUE TITLE
EN493

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#816]
Buongiorno,
da questa mattina sia in ambiente di TEST, che alcuni enti in PRE-SUBENTRO stanno ricevendo il seguente errore ANPR:

Errore EN493
"L'utente non dispone dei privilegi per eseguire l' operazione"

come possiamo risolvere il problema?
Grazie

**Comment by mttfranci** [comment]
Stiamo analizzando il problema.
Potreste fornirci un identificativo operazione anpr (o almeno comune) per velocizzare la verifica?
Grazie in anticipo.
Assistenza ANPR

**Comment by SAlberto** [comment]
Ambiente di TEST:
 il fatto è che sul file di ritorno l'identificativo ANPR vale 0, qui di seguito il ritorno:

```
	<ns7:rispostaKO>
		<testataRisposta>
			<idOperazioneComune>5394</idOperazioneComune>
			<codMittente>017074</codMittente>
			<codDestinatario>ANPR00</codDestinatario>
			<operazioneRichiesta>5001</operazioneRichiesta>
			<dataOraRichiesta>2018-09-13T10:47:18</dataOraRichiesta>
			<protocolloComune>0</protocolloComune>
			<dataDecorrenza>2018-09-12</dataDecorrenza>
			<idOperazioneANPR>0</idOperazioneANPR>
			<esitoOperazione>XXXX</esitoOperazione>
		</testataRisposta>
		<listaErrori>
			<errore>
				<codiceErroreAnomalia>EN493</codiceErroreAnomalia>
				<tipoErroreAnomalia>E</tipoErroreAnomalia>
				<testoErroreAnomalia>L'utente non dispone dei privilegi per eseguire l' operazione </testoErroreAnomalia>
			</errore>
		</listaErrori>
	</ns7:rispostaKO>
```

**Comment by mttfranci** [comment]
Potreste riprovare la stessa operazione (5001 in test comuni)?

**Comment by SAlberto** [comment]
Riprovato e non ha più dato la segnalazione.
Da cosa era dovuto?

**Comment by mttfranci** [comment]
Salve, una configurazione incompleta dopo l'aggiornamento di ieri #811.
Ora dovrebbe essere tutto a posto.

**Comment by SAlberto** [comment]
Grazie per la tempestiva risoluzione,
buona giornata.

**Comment by SAlberto** [comment]
Buongiorno,
Il problema si sta ripresentando questa mattina sia in ambiente di test che di pre-subentro.

Errore EN493
L'utente non dispone dei privilegi per eseguire l' operazione  [Va implementato il gestore accessi per la richiesta 1014]

Potete verificare?
Grazie

**Comment by mttfranci** [comment]
Si, dovrebbe essere possibile riprovare.

**Comment by SAlberto** [comment]
Il problema persiste, ma è cambiato il messaggio, è tornato quello di ieri

Errore EN493
"L'utente non dispone dei privilegi per eseguire l' operazione"

**Comment by busaster** [comment]
Ora lo stesso problema capita anche a noi in ambiente di test con una operazione WS 5005

**Comment by pissardl** [comment]
Abbiamo lo stesso problema in PreSubentro
su operazione:
            <idOperazioneComune>205995</idOperazioneComune>
            <codMittente>001272</codMittente>
            <codDestinatario>ANPR01</codDestinatario>
            <operazioneRichiesta>5005</operazioneRichiesta>
            <dataOraRichiesta>2018-09-14T12:03:16.315+02:00</dataOraRichiesta>

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by mttfranci** [comment]
Ok, ora dovrebbe essere a posto per tutti i servizi e ambienti.

**Comment by busaster** [comment]
confermo, per me è ok

**Comment by mttfranci** [comment]
@busaster perfetto, al fine di completare l'analisi del problema, potreste darci l'id dell'operazione che è andata bene ora?
Grazie in anticipo.

**Comment by busaster** [comment]
id anpr 15734193
