### ISSUE TITLE
Problemi Ripopolamento ambiente di TEST

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#817]
Buongiorno,
il 10/09/2018 ho ripopolato l'ambiente di TEST, ma ad oggi mi da ancora IN ELABORAZIONE per il file dei residenti, il numero di protocollo ANPR è il seguente: 8003013

Potete verificare se ho sbagliato qualcosa o perchè non è ancora in stato ELABORATO?

Ringrazio anticipatamente

**Comment by mttfranci** [comment]
Salve, potreste dirci quale è il comune?

**Comment by SAlberto** [comment]
Ambiente di test, comune Savigliano

grazie

**Comment by mttfranci** [comment]
Per il comune di Savigliano, codistat 004215, ambiente di test comuni, la simulazione di subentro ci risulta completata con successo intorno alle 9.40 del 10 settembre.
Avete provato ad operare?
Il file dei residenti risulta ancora in elaborazione nella sezione Subentro e Anomalie -> Esiti del subentro?

**Comment by SAlberto** [comment]
Ho provato ad operare e anche semplicemente a fare delle consultazioni, ma le anagrafiche non vengono trovate.
Si risulta 'in elaborazione' nella sezione Subentro e Anomalie -> Esiti del subentro

**Comment by mttfranci** [comment]
Dovremmo aver individuato il problema. Potete riprovare.
Noi siamo riusciti a interrogare con successo il soggetto con id anpr : 19388547

**Comment by SAlberto** [comment]
Lo vedo ancora "IN ELABORAZIONE", ma adesso risponde correttamente, riesco a interrogarlo senza problemi.

Grazie
