### ISSUE TITLE
[5008] Completamento dati AIRE - errore EN369

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#818]
Insiel Mercato 
Comune di Tolentino
Ambiente di pre-subentro
Test effettuato il 13.09.2018

PROBLEMA:
Abbiamo subentrato gli Aire con il tracciato di AnagAire.
Stiamo procedendo all'allineamento dati con il servizio 5008 tipo mutazione 21
Abbiamo problemi quando dobbiamo completare i dati di persone iscritte attualmente all'AIRE che hanno stato civile divorziato oppure vedovo e il coniuge risulta mai residente. L'allineamento segnala l'errore EN369 Operazione richiesta non possibile. Non e' presente alcun matrimonio per il soggetto ......... corrispondente ai dati inseriti

Per ovviare a tale inconveniente siamo dovuti entrare nella webapp ed inserire i dati di matrimonio con mutazione di tutti i dati e solo dopo l'allineamento ha dato esito positivo.
Se però, la persona risulta coniugata e il coniuge è mai residente, l'allineamento va a buon fine.

Id ANPR operazione andata male: 7519681

Grazie
Tiziana Testa

**Comment by ncapozzi** [comment]
Buonasera, stiamo effettuando un intervento di semplificazione del completamento dati matrimonio per i soggetti AIRE per i quali al subentro è consentita l'indicazione del solo cognome del coniuge. Vi informeremo appena l'aggiornamento sarà disponibile in pre-subentro.

Nicoletta Capozzi

**Comment by ncapozzi** [comment]
L'aggiornamento descritto il 14 settembre è stato effettuato. Potete riprovare

Saluti
Nicoletta Capozzi
