### ISSUE TITLE
Aggiornamento xsd, 1 ottobre in presubentro / test comuni, 5 novembre in produzione

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#819]
A fronte di una verifica sulle operazioni delle ultime 24 ore in tutti gli ambienti , il nuovo valore del codDestintario (ANPR01, issue  #775) è stato usato per una percentuale di richieste non superiore al 25%.
 
Per tale ragione, è stato deciso di rimandare di qualche giorno l’aggiornamento degli xsd :
1 ottobre 2018 – Ambiente di test comuni e presubentro
5 Novembre 2018 – Ambiente di produzione
 
A partire da tali date, operazioni con un codDestintario diverso non saranno più elaborate.
Problemi di validazione fino al 5 Novembre 2018 verranno gestiti comunque con un messaggio applicativo (EN489), mentre dopo tale data verranno bloccati dai sistemi di verifica perimetrali.
 
Ulteriori informazioni e chiarimenti richiesti verranno forniti in questa issue.

**Comment by subentroanpr** [comment]
Con la versione 4.1.13 è possibile eseguire l'upload dei file del subentro solo con le nuove regole : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

**Comment by mttfranci** [comment]
Con la versione 4.1.13 è possibile eseguire l'upload dei file del subentro solo con le nuove regole : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

**Comment by mttfranci** [comment]
Oggi termina il supporto della versione ANPR01 (vedi in particolare #1410 e #1424).
