### ISSUE TITLE
[5008] errore su mutazione 20 - completamento dati

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#82]
Comune di Pisa, ambiente di Test, 5 aprile 2017, ID operazione ANPR 451945

Buongiorno,
abbiamo fatto un'immigrazione da comune non subentrato, dopo aver fatto l'iscrizione con il servizio 1002 abbiamo eseguito il completamento dei dati con il servizio 5008 ma la risposta è stata: EN148 - Errore nel reperimento dei dati delle generalità del coniuge durante la mutazione della scheda.
Nel nostro caso il soggetto era vedovo e abbiamo inserito sia i dati matrimonio che i dati di vedovanza, anche se si tratta di un completamento dati dobbiamo richiamare il servizio due volte?

Allego gli xml trasmessi e ricevuti, grazie.

Luca Bonini A.P.Systems

[5008-mutazione20.zip](https://github.com/italia/anpr/files/896293/5008-mutazione20.zip)

**Comment by LucaBonini64** [comment]
Buongiorno,
abbiamo provato a suddividere la trasmissione in due comunicazioni ma il programma comunque non funziona, con la prima trasmissione mi completa correttamente i dati di matrimonio mentre con la seconda trasmissione riguardante i dati di vedovanza l'evento va a buon fine ma nell'individuo non si vedono i dati di vedovanza.
IDschedaANPR: 4376747 - IDoperazioni: 452190 e 452206
Grazie.

**Comment by gcarbonin** [comment]
Stiamo verificando la sua prima richiesta.

**Comment by gcarbonin** [comment]
Questo problema dovrebbe essere risolto. Puo' riprovare? Attendo un suo riscontro
