### ISSUE TITLE
[3002][WEBAPP] Ricerca soggetto per generalità con senzaNome - E001

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#820]
In ambiente di PreSubentro, effettuando una ricerca per generalità con un soggetto senzaNome otteniamo l'errore E001-parametri obbligatori non valorizzati
anche presisando tutte info di generalità (cognome,flagSenzaNome,sesso,dataNascita,luogoNascita).
Sia da WEB APP che servizio 3002.

```	<idOperazioneComune>206024</idOperazioneComune>
	<codMittente>001272</codMittente>
	<codDestinatario>ANPR01</codDestinatario>
	<operazioneRichiesta>3002</operazioneRichiesta>
	<dataOraRichiesta>2018-09-14T15:14:15.032+02:00</dataOraRichiesta>
```

Sarebbe da provare nel caso fosse senzaCognome e magari entrambi senzaCognome e senzaNome.

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by gcarbonin** [comment]
Stiamo verificando. Faccio presente che SenzaNome e SenzaCognome andrebbe utilizzato per indicare che la persona straniera non ha nome o non ha cognome. Che siano assenti entrambi non è ammesso.

**Comment by azabatta** [comment]
Buonasera, 
nella consultazione di una scheda individuale il sistema verifica che sia impostato almeno un dato tra: codice fiscale,  identificativo ANPR, identificativo comunale del cittadino, dati anagrafici.
La verifica del rispetto dei suindicati criteri è dettata dalla necessità di ottimizzare i tempi di risposta del servizio. 
Il campo  “senzaNome” valorizzato non viene equiparato al nome in quanto è solo un indicatore dell’assenza del nome. Lo stesso discorso vale per il campo”senzaCognome”.
