### ISSUE TITLE
data di decorrenza dell'operazione NON DEVE essere inferiore alla data ....

### ISSUE THREAD

**Issue by Raffive** [italia/anpr#822]
Buongiorno, si ripresenta con preoccupante frequenza l'impossibilità di registrare variazioni anagrafiche che risultano bloccanti con il motivo di cui sopra.
Purtroppo, la registrazione degli eventi della vita delle persone non segue uno stretto ordine cronologico che, sembra, invece ANPR chieda.
esempio:
- tizio nostro residente divorzia nel 2017 
- tizio vuole risposarsi a settembre 2018
-la sentenza di divorzio arriva in comune due giorni prima del matrimonio = registrazione con data di protocollo 13/09
- si sposa il 15/09
- il 12/09 emigra in altro comune 
- non riusciamo a registrare l'emigrazione nemmeno cambiando le date di registrazione ... 
ID=62363
COD. ERRORE: EN 240 : la data di decorrenza dell'operazione non può essere inferiore alla data di decorrenza dell'ultima operazione effettuata sul soggetto.
Attendo cortesemente risposta/soluzione
Raffaella - Spinea

**Comment by gcarbonin** [comment]
Buongiorno. Nella cancellazione ci sono due date: la prima è la data di decorrenza della cancellazione in ANPR; questa data deve essere coerente con le altre date (18-9-2018 perchè lo stato civile è stato variato con questa data); la seconda è la data di cancellazione e in questa data si indica la data giuridica che è 12-9.

**Comment by Raffive** [comment]
e così avevamo fatto, le mando il ritaglio in posta..
![immagine](https://user-images.githubusercontent.com/32516983/45673917-319b0c00-bb2c-11e8-8116-21ae499a2983.png)

**Comment by Raffive** [comment]
Grazie, allora forse il problema è un'altro, la data che io visualizzo non è quella che il programma "registra"
sento maggioli.
Raffaella

**Comment by Raffive** [comment]
ho guardato meglio... non mi sembra..
risposta:
![immagine](https://user-images.githubusercontent.com/32516983/45676285-ae7cb480-bb31-11e8-8985-dd34277e22e5.png)
domanda:
![immagine](https://user-images.githubusercontent.com/32516983/45676348-d409be00-bb31-11e8-8763-e45eacd004b3.png)

**Comment by gcarbonin** [comment]
la data sbagliata è la prima (data decorrenza) di testata richiesta; quella deve essere 18-9-2018

**Comment by Raffive** [comment]
non capisco perchè .... qual'è la differenza tra la data di decorrenza "in testata" e la decorrenza della data  di cancellazione? di quali e quante decorrenze dobbiamo tenere conto per una semplice pratica di emigrazione o su altre registrazioni?

**Comment by Raffive** [comment]
.... sulla decorrenza giuridica ci sono... ma per l'altra data ... noi, ma credo anche qualche altro comune se non tutti la data "quando il comune apprende l'esistenza di un fatto" corrisponde alla data del registro di  protocollo dell'ente che ha caratteristica di certezza  e fa fede in caso di controversie.
Non necessariamente corrisponde alla data in cui aprimo o chiudiamo un procedimento amministrativo o facciamo una qualsiasi registrazione. Questa è la data di "registrazione dell'evento" o di apertura o chiusura di un procedimento. Nel caso di specie una emigrazione data di protocollo 13/09, data di registrazione dell'emigrazione 18/09 perchè solo oggi ho potuto fare la pratica....

**Comment by bfilipazzi** [comment]
"il comune apprende l'esistenza di un fatto (anagrafico)" = "quando lo registra in ANPR"
Filipazzi - Maggioli

**Comment by Raffive** [comment]
mi sono persa un pezzo .. da quando il Comune di Spinea si è fusa con il comune di Anpr?

**Comment by Raffive** [comment]
sistemate sta cosa per piacere da quando ho cominciato a scrivere ne ho altre due di pratiche in questa situazione.

**Comment by gcarbonin** [comment]
La cosa funziona già bene; è sufficiente impostare le date come indicato nelle specifiche (da oltre un anno).
