### ISSUE TITLE
[N014] Notifica richiesta di ripristino - Richiesta chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#823]
ambiente di PRODUZIONE - comune di SAN DONATO MILANESE - idSoggettoANPR 23300553

siamo nella fattispecie del capitolo 12.1.2 delle specifiche di interfaccia ws:
step 1 - il soggetto emigra in comune non subentrato con ws 2003
step 2 - il comune di destinazione subentra e popola il soggetto con il il file di subentro
step 3 - il comune di destinazione rileva gli accertamenti negativi e cancella per "ripristino posizione precedente" (motivoCancellazione '12')
step 4 - il nostro comune iscrive per "ripristino posizione precedente" (motivoIscrizione '10')

mi sarei aspettatto la notifica N014 della quale si parla nel documento.

specifico che il cliente (comune di San Donato M.se) NON espone all'esterno il servizio di notifica, bensì interroga con servizio 3003 e operazioneRichiesta N014.

mi chiedo:
- la notifica non è partita?
oppure
- la notifica è partita e non l'abbiamo intercettata?

se possibile effettuare qualche verifica, giusto per capire se le aspettative sono corrette e se abbiamo interpretato correttamente il meccanismo

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Le notifiche si generano quando l'operazione fatta dal comune A modifica la base dati di B senza che B ne sia consapevole (tipo mutazione di residenza tra comuni subentrati). In questo caso un comune ha fatto una iscrizione e l'altro una cancellazione. Quale notifica si sarebbe dovuta generare?

**Comment by AMonopoliADS** [comment]
riporto per completezza quanto ho trovato nel capitolo delle specifiche che ho citato (pag. 108):

Se il cambio di residenza è avvenuto tra un comune subentrato (A) ed un comune
non subentrato (B), in caso di ripristino della posizione anagrafica si configurano
due possibili casi:
- il comune di immigrazione B continua ad essere non subentrato: il
comune A utilizza il servizio “2011-AnnullamentoCancellazione” per
ripristino posizione anagrafica;
- il comune di immigrazione B, nel frattempo, è subentrato: utilizza il
servizio “2003 – CancellazioneAltriMotivi” per ripristino posizione
anagrafica; il comune A riceve notifica N014 ed utilizza il servizio “1002-
IscrizionePerAltriMotivi”.

la situazione della quale parlo è quella descritta nella seconda ipotesi documentata.

**Comment by fferraguto** [comment]
Salve, potete verificare ora la presenza della notifica?

**Comment by AMonopoliADS** [comment]
confermo che la notifica è stata scaricata.
quale è stato il problema?

**Comment by gcarbonin** [comment]
un problema nostro nella generazione
