### ISSUE TITLE
[5014] Rettifica Data Decorrenza Residenza (pre_sub)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#825]
ambiente di PRE-SUBENTRO - comune di CASOLA VALSENIO (039005)

viene inviata la comunicazione di rettifica della dataDecorrenzaResidenza (ws 5014 - richiestaRettifica101)
la comunicazione viene accettata, ma di fatto in ANPR non viene rettificato niente:
- la comunicazione ottiene l'idOperazioneANPR '0' (zero)
- l'anagrafica del soggetto in ANPR continua a non avere la dataDecorrenzaResidenza valorizzata
(rif. idOperazioneComune 2018200463)

da cosa dipende?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
confermo che il cliente è Casola Valsenio (039-005)
l'ambiente di pre-subentro è stato popolato il 13/9.
da allora sono state eseguite le seguenti operazioni:
idOperazioneComune 2018200005 - ws 5008
idOperazioneComune 2018200006 - ws 5008
idOperazioneComune 2018200264 - ws 1001
idOperazioneComune 2018200430 - ws 5008
idOperazioneComune 2018200437 - ws 1001
idOperazioneComune 2018200446 - ws 5008
idOperazioneComune 2018200463 - ws 5014 (per la quale è stata aperta questa issue)
idOperazioneComune 2018200466 - ws 2001

di tutte queste comunicazioni (eccetto quella segnalata) troviamo riscontro nei dati di ANPR, e la richiesta della lista operazioni eseguite sui vari soggetti (effettuata con codMittente "039005") mi ritorna gli stessi codici.

vi chiederei di controllare nuovamente.
grazie

**Comment by frmariani** [comment]
oltre alle operazioni elencate, esclusa la segnalata, sono presenti anche le seguenti:
 idOperazioneComune 2018200054 - ws 2003
idOperazioneComune 2018200440 - ws 6001
idOperazioneComune 20182002003 - ws 2003

confermate ?
potete rifare ora l'operazione di rettifica per favore ?

**Comment by AMonopoliADS** [comment]
bene.

confermo:
i ws 2003 indicati sono comunicazioni ritornate con errore (non le avevo inserite per quello)
e anche la 6001 è corretta.

ho ripetuto l'operazione 5014 (con idOperazioneComune 2018200480) ma il risultato è il medesimo.
idANPR di ritorno '0' (zero) e nessuna aggiornamento nella banca dati

**Comment by frmariani** [comment]
sarebbe possibile avere anche la richiesta ?

grazie

**Comment by AMonopoliADS** [comment]
l'ho inviata alla sua mail personale

**Comment by frmariani** [comment]
grazie

**Comment by frmariani** [comment]
Abbiamo eliminato l'anomalia introdotta con l'ultimo aggiornamento software.
Grazie per la collaborazione.

**Comment by AMonopoliADS** [comment]
bene. grazie a voi.
ho inviato con successo la comunicazione 5014 e adesso ANPR è stata aggiornata.
