### ISSUE TITLE
Descrizione cittadinanza

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#828]
Eseguo una consultazione con questi estremi di testata:

<codDestinatario>ANPR00</codDestinatario>
<operazioneRichiesta>3002</operazioneRichiesta>
<dataOraRichiesta>2018-09-21T11:12:50.000+02:00</dataOraRichiesta>
<idOperazioneANPR>16639621</idOperazioneANPR>

e osservo il dato della cittadinanza:

<cittadinanza>
	<descrizioneStato>FEDERAZIONE RUSSA</descrizioneStato>
	<codiceStato>245</codiceStato>
</cittadinanza>

successivamente produco un certificato di cittadinanza <idOperazioneANPR>16639624
e nel documento leggo:

Risulta in possesso della cittadinanza RUSSA

Non capisco da dove proviene il dato "RUSSA" che descrive la cittadinanza?
Grazie

Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
I due id forniti sono dell'operazione? se si nessuno dei due va bene (il primo è uno scarico di più 3002, il secondo è una richiesta 3003 andata in errore). Mi sarebbe sufficiente l'identificativo della persona

**Comment by bfilipazzi** [comment]
Ha pasticciato col copia / incolla e le etichette dei dati si sono perse. Chiedo scusa.
idOperazioneANPR 16639621
idSchedaSoggettoANPR 9388357

**Comment by bfilipazzi** [comment]
Ambiente di test

**Comment by gcarbonin** [comment]
Trovato. Il certificato riporta la località di nascita seguita dallo stato tra parentesi. La persona in questione ha "RUSSIA" nel campo località di nascita e come stato di nascita Federazione Russa. Quanto riporta il certificato è quindi coerente con quello che risulta in ANPR anche se non bello da vedere

**Comment by bfilipazzi** [comment]
Riprovo ad esporre il mio dubbio con un caso che ha dati meno equivoci del precedente.

In ambiente di test eseguo una chiamata di consultazione
Id operazione ANPR 16640540
Id scheda soggetto ANPR 9387057

e nel file XML di ritorno leggo nel tag cittadinanza la descrizioneStato GERMANIA

il certificato di cittadinanza prodotto con Id operazione ANPR 16640540
riporta la frase "Risulta in possesso della cittadinanza TEDESCA"

Da dove proviene la descrizione "TEDESCA"?
Grazie

**Comment by gcarbonin** [comment]
Sui certificati viene riportato l'aggettivo e non lo stato. Proviene da una tabella interna di anpr
