### ISSUE TITLE
Problema con Scarico notifiche

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#829]
Ambiente di Produzione
Comune Valle di Cadore

Controllando dal portale sappiamo che il giorno 18/9/2018 e il 19/9/2018 sono arrivate due notifiche di emigrazione di due cittadini.

Con la seguente richiesta
`<ns2:Richiesta3003 xmlns:ns2= "http://sogei.it/ANPR/3000consultazione">`

	`<testataRichiesta>
		<idOperazioneComune>471</idOperazioneComune>
		<codMittente>025063</codMittente>
		<codDestinatario>ANPR00</codDestinatario>
		<operazioneRichiesta>3003</operazioneRichiesta>
		<dataOraRichiesta>2018-09-21T11:58:27.038+02:00</dataOraRichiesta>
		<tipoOperazione>C</tipoOperazione>
		<tipoInvio>PROD</tipoInvio>
		<dataDecorrenza>2018-09-21+02:00</dataDecorrenza>
	</testataRichiesta>
	<comuneRichiesta>
		<nomeComune>VALLE DI CADORE</nomeComune>
		<codiceIstat>025063</codiceIstat>
		<siglaProvinciaIstat>BL</siglaProvinciaIstat>
	</comuneRichiesta>
	<ricercaElenchiRichieste>
		<statoLavorazione>9</statoLavorazione>
		<periodoRiferimentoRichieste>
			<dataOraIniziale>2018-09-17T00:00:00.000+02:00</dataOraIniziale>
			<dataOraFinale>2018-09-21T11:58:27.038+02:00</dataOraFinale>
		</periodoRiferimentoRichieste>
	</ricercaElenchiRichieste>`
`</ns2:Richiesta3003>`

ci aspettavamo di poter scaricare queste due notifiche ma non riceviamo nulla,
abbiamo anche provato con 
`<statoLavorazione>7</statoLavorazione>`
ma abbiamo avuto lo stesso risultato

potete verificare?
Grazie

**Comment by gcarbonin** [comment]
Non abbiamo trovato questa operazione (di interrogazione) in ambiente di produzione per il comune di Valle di Cadore.. In quale ambiente e per quale comune  avete fatto l'interrogazione? Quale è l'idanpr presente nella risposta?

**Comment by SAlberto** [comment]
Abbiamo risolto, 
per lo scarico veniva erroneamente utilizzato l'accesso del sindaco e non dell'operatore.

Grazie
