### ISSUE TITLE
Tabella dei Comuni

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#83]
Buongiorno,
vorrei segnalarvi che nella tabella dei comuni manca il comune di Montalbano di Elicona (precedente denominazione dell'attuale Montalbano Elicona).
Sempre sullo stesso argomento vorrei sapere:
1) visto che sempre più enti stanno subentrando, come ci comportiamo con le persone che hanno codici fiscali validati, ma con dati di nascita errati? ad esempio Olbia sino al 1939 si chiamava Terranova Pausania ma in anagrafe ed in AE si è sempre utilizzata la denominazione Olbia. Il comune ci chiede istruzioni su come procedere in previsione del subentro.
2) come dobbiamo comportarci con i comuni con codici Istat da voi definiti 'di variazione' in fase di pre-subentro. Nella nuova tabella che dovete ancora pubblicare questi comuni avranno un altro codice istat o saranno associati al codice istat del comune attualmente vigente?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Giro all'ISTAT la sua segnalazione
1. uscirà a breve (mi auguro) una nota sul tema
2. un cambio di denominazione non modifica il codice istat. Quindi tutte queste variazioni mantengono lo stesso codice istat. Aggiungeremo una colonna sulla tabella attuale che contiene il codice di variazione
