### ISSUE TITLE
Matrimonio In Territorio estero

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#831]
Buongiorno,

abbiamo un caso da sottoporvi per capire come operare:
se due individui si sono sposati a Vaitape in Polinesia (territorio francese),
nella Località del Luogo Evento del matrimonio quali dati dobbiamo indicare?

La Polinesia può essere accettata come località evento? Sulla tabella 2 è classificata come Territorio, non come Stato, e non ha il codice catastale.
Oppure dobbiamo utilizzare Francia?

Ringrazio anticipatamente,
cordiali saluti.

**Comment by gcarbonin** [comment]
Stato = francia; località Vaitape Polinesia
