### ISSUE TITLE
Carte d'Identita' rilasciate da Consolati soppressi

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#833]
Si chiede come gestire in subentro le C.I. non scadute, rilasciate a cittadini italiani AIRE
da Consolati soppressi, non contemplati nella tabella ANPR 24 "Elenco consolati".

Sul frontespizio della C.I. e' riportato l'ufficio consolare che la ha emessa ed i comuni non ritengono 
corretto sostituire il consolato originale con quello che lo ha sostituito.

Grazie
Carla Musian

**Comment by gcarbonin** [comment]
Il Ministero ci ha confermato che occorre riportare il consolato storico. Pianificheremo un intervento in tal senso

**Comment by ncapozzi** [comment]
L'intervento è stato effettuato a novembre del 2018

N. Capozzi
