### ISSUE TITLE
Destinazione d'uso dei certificati

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#834]
Leggo nelle specifiche di interfaccia che la destinazione d'uso può assumere due valori:
2 CERTIFICATO RILASCIATO PER PROCEDIMENTI DISCIPLINATI DALLE NORME SULL’IMMIGRAZIONE
3 AI SENSI DELL’ART. 40, D.P.R. 445/2000 IL PRESENTE CERTIFICATO E’ RILASCIATO PER CAUSE GIUDIZIARIE
osservo nella WA la presenza di una terza riga:
"AI SENSI DELL'ART. 40, D.P.R. 28 dicembre 2000, N. 445, il presente certificato è rilasciato solo per l'estero"
Mi sfugge qualcosa?
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
destinazione d'uso 2 e 3 sono state aggiunte su richiesta di alcuni comuni; l'altro che si ottiene con pa estera = 1 è sempre esistito per questo non non è documentato in quel paragrafo (che si chiama destinazioni d'uso)

**Comment by bfilipazzi** [comment]
E' sempre esistito un campo PA Estera con due valori NO / SI, che c'è tuttora.
Il campo Destinazione d'Uso Specifica è stato aggiunto a suo tempo con due valori ma oggi ce ne sono tre,  il terzo ha descrizione "AI SENSI DELL'ART. 40, D.P.R. 28 dicembre 2000, N. 445, il presente certificato è rilasciato solo per l'estero" e sembra una ripetizione del campo PA Estera.
La mia domanda è: a cosa serve questa terza voce? è una ridondanza di PA Estera?
Ci tengo a capirlo perché i clienti vogliono che il gestionale replichi il comportamento della WA.
Grazie.
Filipazzi - Maggioli

**Comment by gcarbonin** [comment]
Ricostruita la faccenda. E' stato aggiunto il valore 4 di pa estera per consentire l'emissione di certificati non esenti per l'estero. Aggiorniamo la documentazione

**Comment by bfilipazzi** [comment]
Grazie

**Comment by ncapozzi** [comment]
E' stato modificato 6001-RichiestaCertificati.xlsx. 
Nel campo Paestera è ammesso anche il valore 4 = per uso "ai sensi dell’art. 40, d.p.r. 28 dicembre 2000, n. 445, il presente certificato e’ rilasciato solo per l’estero"

Saluti
N. Capozzi
