### ISSUE TITLE
[1002] risposta OK, ma soggetti non accessibile

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#835]
In ambiente di Produzione 
In seguito a 2 operazioni di Iscrizione 1002 con esito positivo in Famiglia esistente
Non riusciamo ad effettuare consultazione dei 2 soggetti creati (con 3002 e da WA).
Se fosse cancellati, le drovemo comunque trovare con visualizzazione dei dati di cancellazione ?

idOperazioneANPR: 17190929  per  idSchedaSoggettoANPR: 32306900
idOperazioneANPR: 17190920  per  idSchedaSoggettoANPR: 32306899
idFamigliaConvivenzaANPR: 15860886 che contiene già 3 componenti e dove dovrebbe essere 5.

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by azabatta** [comment]
Buongiorno, 
ambedue gli eventi anagrafici sono stati annullati:

1.	idOperazioneANPR: 17190929 per idSchedaSoggettoANPR: 32306900  operazione anagrafica  annullata in data 20.09.2018 (idOperazioneANPR 17342443)

2.	idOperazioneANPR: 17190920 per idSchedaSoggettoANPR: 32306899   operazione anagrafica  annullata in data 20.09.2018 (idOperazioneANPR 17342443)

Se i cittadini fossero stati cancellati, le posizioni risulterebbero consultabili con la sezione dati cancellazione valorizzata.

**Comment by pissardl** [comment]
OK, Grazie
Ultima info :  come reperire l'operatore che ha effettuato un certa operazione (avendo idOperazioneANNPR).
L'info è nella busta, all'esterno dell'XML di Richiesta, da WA si puo consultare ?

**Comment by gcarbonin** [comment]
L'informazione c'è nella richiesta che inviate.  Non è consultabile
