### ISSUE TITLE
Ripristino a cavallo del subentro

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#836]
Il 05/06/2018 abbiamo cancellato una cittadina (codice ANPR 19716876) per emigrazione nel comune di Cesenatico, comune all'epoca non ancora subentrato in ANPR.
Cesenatico ha rigettato la pratica di iscrizione successivamente al 31/7/2018, data in cui è subentrato in ANPR,  e pertanto ora nell'anagrafe nazionale la cittadina anziché essere residente nel nostro comune (Altamura) risulta NON RESIDENTE.
Ho provato a fare il ripristino ma genere il seguente errore:
 **L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa** 
Dalla web app visualizzo 10 eventi registrati dal comune di Cesenatico dal 24 agosto al 6 settembre 2018.

**Comment by frmariani** [comment]
Come da voi analizzato, il passaggio della residenza della cittadina , è avvenuto a cavallo del subentro del comune di Cesenatico, quindi senza l'utilizzo del servizio di mutazione di residenza; in questi particolari casi, il rigetto della pratica del Comune di Cesenatico, nel frattempo subentrato, comporta necessariamente una re-iscrizione da parte del Comune di Altamura (con l'utilizzo dello stesso idanpr);
