### ISSUE TITLE
Soggetti protocollo riservato

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#837]
Nelle prossime settimane subentrerà un comune che ha tra i propri residenti dei soggetti a Protocollo Riservato. Se non sbaglio queste persone non dovranno essere trasmesse in fase subentro. 
Ci sono specifiche particolari su come dovranno essere trattate queste persone? Dovranno essere comunicate in altre modalità? Oppure restano solo in gestione all'anagrafe locale?

Grazie
Siscom SPA

**Comment by gcarbonin** [comment]
Restano in gestione all'anagrafe locale
