### ISSUE TITLE
Manutenzione sistemi test comune e presubentro 26/09/2018

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#838]
Si avvisa che oggi 26 settembre dalle ore **14 alle ore 16** i servizi ANPR dei sistemi di test e presubentro non saranno disponibili per interventi di manutenzione.

**Comment by ANPRCdMI** [comment]
Buongiorno
stiamo facendo dei test in PRE-SUBENTRO e prendiamo questo errore:  
Rejected by policy. (from client)
E' legato agli interventi di manutenzione programmati previsti per le 14? 
Grazie
Raffaella Tremolada
S.I. per Comune di Milano

**Comment by gcarbonin** [comment]
Ci sono problemi di autenticazione lato Sogei che stiamo verificando
