### ISSUE TITLE
[Test] Rettifica Relazione di parentela 

### ISSUE THREAD

**Issue by DomenicoGallo** [italia/anpr#84]
Salve, 
stiamo tentando, senza successo, alla modifica della relazione di parentela di un soggetto tramite il servizio di mutazione  5001 ,  per il comune di Cittanova , ambiente di test.
L’ultimo tentativo fatto ha idOperazione =3000.
E' la nostra richiesta ad essere sintatticamente errata?
Grazie anticipatamente
Buona giornata.

Domenico Gallo
KIBERNETES S.r.l.

**Comment by gcarbonin** [comment]
Risultano a sistema soltanto consultazioni. l'ultima operazione registrata ha id 2087. Sicuramente c'è un errore. Invii cortesemente la richiesta alla casella di e-mail dell'assistenza o alla mia e-mail.

**Comment by DomenicoGallo** [comment]
Mi potrebbe dire la sua email, oppure invio la richiesta alla casella dell'assistenza ?

**Comment by gcarbonin** [comment]
mandi all'assistenza

**Comment by gcarbonin** [comment]
La richiesta è valida nella parte body; stiamo facendo ulteriori verifiche
