### ISSUE TITLE
Servizio 7001 di scarico tabelle: file wsdl e xsd non corrispondenti alla risposta generata 

### ISSUE THREAD

**Issue by marcx2014** [italia/anpr#840]
Buongiorno.
Analizzando la risposta alla richiesta per il servizio di Scarico Tabelle 7001 ho notato che inviate il file richiesto usando il sistema SOAP with Attachments (SwA), però mi pare che i file .wsdl  e .xsd  che descrivono il servizio non rappresentino correttamente questo tipo di scambio.
Potreste per favore fornire la versione corretta di questi files  in modo che si possano utilizzare per generare automaticamente la classe proxy corrispondente?
Cordiali Saluti
Bigi Marco

**Comment by rnapoli1983** [comment]
Buonasera potremmo chiedervi di allegarci i file .wsdl e .xsd che state utilizzando per la generazione del client e, se è possibile, sapere anche la tecnologia utilizzata.
Grazie mille.

**Comment by marcx2014** [comment]
Buongiorno.
Noi utilizziamo come framework applicativo .Net e per consumare i Web
Services il sottosistema WCF (Windows Comunication Foundation).
Wcf non fornisce un encoder dedicato per questi MIME Web Services quindi
molto probabilmente andrà implemenentato manualmente ma,
indipendentemente da ciò, da quanto si legge nell'xsd mi pare che il tag
xmlFile aspetti un array di byte in formato base64 mentre invece ho visto
che
includete id del file binario che poi si troverà nella parte MIME.
Inoltre inserite il tag <xop:Include che fa pensare invece alla tecnologie
MTOM (ma in questo caso l'header sarebbe poi sbagliato in quanto
type="text/xml" dovrebbe diventare "type="application/xop+xml" e
start-info="text/xml" dovrebbe diventare "start-info="application/soap+xml")
In sintesi, prima di andare a spacchettare byte per byte il messaggio che
correttamente ricevo per poi provare ad associarlo alla classi proxy che
uso (quelle create utilizzando gli xsd), vorrei capire se ho inquadrato
correttamente la questione e, nel caso, vorrei capire se fosse
possibile avere file .wsdl e xsd che corrispondano il più possibile a alla
risposta che realmente ricevo.
Come richiesto allego i file .wsdl e xsd che usiamo.
Cordiali saluti
Bigi Marco

Il giorno mar 2 ott 2018 alle ore 17:06 rnapoli1983 <
notifications@github.com> ha scritto:

**Comment by rnapoli1983** [comment]
Buongiorno prima di rispondere alle osservazioni poste vorrei consultare i file .wsdl e .xsd di cui siete in possesso.

Per farlo dovreste allegarli qui nella issue perchè da email non sono arrivati.

Grazie mille

**Comment by marcx2014** [comment]
[wsdl7001.zip](https://github.com/italia/anpr/files/2442030/wsdl7001.zip)
Ecco l'allegato

**Comment by rnapoli1983** [comment]
Nel frattempo specifico che il file restituito, come allegato in-line alla risposta, è un file zippato.

Allego un file contenente il codice di esempio:
[codice_di_esempio.txt](https://github.com/italia/anpr/files/2442036/codice_di_esempio.txt)

**Comment by marcx2014** [comment]
ok. grazie
