### ISSUE TITLE
Errore in inserimento matrimonio su schede soggetti 18936196 e 18936197

### ISSUE THREAD

**Issue by paltrinan** [italia/anpr#842]
I soggetti ANPR 18936196 e 18936197 avevano la convivenza di fatto fino al 21/09/2018, data in cui si sono sposati.

Dal nostro appicativo, mediante web services, ho proceduto a chiudere la convivenza di fatto con decorrenza 21/09/2018.

Non riesco ad inserire il loro matrimonio con decorrenza 21/9/2018, il sistema mi dà il seguente errore:
_EN289 - La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto 18936196
EN289 - La data evento deve essere maggiore della data di fine validita' dell'ultimo legame del soggetto 18936197_

Come posso fare per registrare il matrimonio con decorrenza 21/9/2018?
Come posso modificare la decorrenza dell'evento di chiusura della convivenza di fatto da 21/9/2018 a 20/9/2018.

I miei riferimenti sono:
Andrea Paltrinieri
e-mail: paltrinieri.andrea@biassono.org
tel. 0392201060

**Comment by gcarbonin** [comment]
Non posso vedere le richieste trasmesse in quanto non c'è l'id operazione.
Il matrimonio è avvenuto il 21-9-2018 e questa è la data giuridica (nel senso che in un certificato di stato civile o di matrimonio compare questa data); diversa è la data di decorrenza che si indica nel servizio che corrisponde a quando l'ufficio anagrafe è venuto a conoscenza del fatto che di norma è una data successiva a quella del matrimonio.
L'operazione dovrebbe passare senza problemi mettendo una data maggiore del 21.

**Comment by paltrinan** [comment]
ho appena provato a fare ciò, il problema persiste

**Comment by gcarbonin** [comment]
Mi può indicare il numero di operazione così vedo la richiesta?

**Comment by paltrinan** [comment]
ho provato a fare ciò dall'applicativo del Comune con i web services; provo a fare lo stesso con il portale e scrivo il numero operazione sul prossimo post

**Comment by gcarbonin** [comment]
Non si preoccupi la cerco e se non riesco scrivo

**Comment by paltrinan** [comment]
ok

**Comment by asqueglia** [comment]
Buongiorno, abbiamo notato che l'operazione di mutazione con cui avete cercato di inserire il contratto di risoluzione convivenza è una mutazione con codice 16= 'inserimento/rettifica convivenza di fatto'; per inserire la risoluzione del contratto di convivenza è necessario trasmettere una mutazione con codice 17= 'inserimento/rettifica contratto di risoluzione'. Per poterla meglio seguire nella pratica, mi può contattare sulla mail privata e mandarmi un suo recapito ? grazie

**Comment by paltrinan** [comment]
al momento non ho la sua e-mail privata; chiedo se me la può lasciare

I miei contatti sono:
Paltrinieri Andrea
Tel. 039-2201060
paltrinieri.andrea@biassono.org
