### ISSUE TITLE
[5008] errore EN243 nella registrazione dati divorzio

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#843]
COMUNE DI SANTA MARIA A MONTE
Ambiente di Produzione
Insiel Mercato spa

Buongiorno, il comune sta cercando di registrare un divorzio tra un suo cittadino residente e il coniuge residente in altro comune subentrato.
Riceviamo l'errore EN243 I dati trasmessi per il coniuge non sono congruenti con quelli presenti per il matrimonio del soggetto 

controllando i dati ci sembrano uguali.

ID ANPR operazione 18082806

potete aiutarci a capire cosa sta succedendo?

Grazie mille
Tiziana Testa

**Comment by asqueglia** [comment]
Buongiorno,
le schede dei due soggetti coniugi non risultano riconciliate. Il collegamento dei coniugi è possibile tramite una mutazione matrimonio (codice 12). Si suggerisce di provvedere alla riconciliazione trasmettendo la stessa richiesta con mutazione matrimonio, anziché mutazione separazione (codice 14). In tal modo il matrimonio dei due soggetti sarà gestito come una informazione condivisa tra i due comuni ed ognuno vedrà le stesse informazioni.
In alternativa, se si desidera mantenere i coniugi non riconciliati, è possibile inviare il divorzio senza specificare i dati del matrimonio se il gestionale lo consente oppure procedere da WEB APP.  
Se desidera essere seguita nella pratica può scrivermi i suoi recapiti in modo che la contatto.

**Comment by TizianaTesta** [comment]
abbiamo risolto con l'invio del solo divorzio. Ha funzionato.

Grazie

**Comment by asqueglia** [comment]
bene
