### ISSUE TITLE
Problemi stampa stati di famiglia

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#844]
Ad alcune famiglie straniere si è verificato il seguente problema in fase di emissione di uno stato di famiglia:
I certificati di stato di famiglia, stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile (Codice: EN222) 
Una delle famiglie  è la 9067673.
Grazie

**Comment by asqueglia** [comment]
Buongiorno,
abbiamo verificato la pratica.
La famiglia indicata è stata resa non certificabile all’atto della registrazione del matrimonio tra due componenti della stessa famiglia.
Per rendere la famiglia certificabile è necessario effettuare una mutazione composizione scheda famiglia (servizio 5001) per modificare o semplicemente confermare i rapporti di parentela, come da specifiche di seguito:

Lo stato di non certificabilità della famiglia è impostato automaticamente dal servizio di mutazione di matrimonio (tipo mutazione 12 matrimonio - vedovanza o 14-annullamento matrimonio) quando il soggetto su cui si opera la mutazione o il suo coniuge siano residenti nella stessa famiglia ed uno dei due ne sia   l’intestatario. In tal caso non è possibile emettere il certificato di stato  di famiglia con i rapporti di parentela finché non siano stati adeguati i legami di parentela con l’intestatario e non sia stata effettuata una mutazione allo scopo. E' necessario, quindi, effettuare una mutazione famiglia convivenza (servizio 5001) di tipo composizione scheda e modificare o semplicemente confermare i legami di parentela dei soggetti.

**Comment by asqueglia** [comment]
Aggiungo che, in alternativa, è possibile utilizzare il servizio di mutazione famiglia convivenza con tipo mutazione 'Motivo famiglia/specie convivenza' ed impostare esplicitamente a 'SI' l'attributo 'Famiglia certificabile'. 
Se il vostro gestionale non e' stato integrato con tale servizio è possibile procedere da WEB APP. 
In attesa di un vostro riscontro

**Comment by AMonopoliADS** [comment]
approfitto di questa issue, perchè ci stiamo imbattendo in situazioni di errore dello stesso tipo.

pertanto, chiedo di spiegare con maggiore chiarezza, se il servizio 5001 che si occupa di "adeguare" i rapporti di parentela dopo il matrimonio, necessiti dell'attivazione dell'attributo di "Famiglia certificabile" per sbloccare la certificazione.
da quanto scritto sopra sembra che l'uso dell'attributo FC, in una mutazone dedicata unicamente a questo scopo, sia alternativo al 5001 di modifica di modifica / conferma dei legami.

faccio un esempio:
1. comunico il matrimonio tra IS e Convivente.
2. viene bloccata la certificatibilità della famiglia
3. comunico la mutazione del rapporto di parentela da Convivente a Marito/Moglio (senza indicazione dell'attributo FC)
... deve bastare a sbloccare la certificabilità, oppure è sempre necessario attivare l'attributo?
grazie.
Alessandro Monopoli ADS

**Comment by asqueglia** [comment]
La comunicazione del cambio di parentela (servizio 5001 tipo mutazione 2), necessita di specificare nella lista controlli della richiesta trasmessa il campo Codice, “FC” e il campo Valore “S”, come di seguito.

> 

    <datiControllo>
        <tipoMutazione>2</tipoMutazione>
        <tipoScheda>1</tipoScheda>
        <listaControlli>
            <controllo>
                <codice>FC</codice>
                <valore>S</valore>
            </controllo>
        </listaControlli>
    </datiControllo>

>

**Comment by gcarbonin** [comment]
Chiusa in quanto lo stesso argomento è trattato nella issue #852
