### ISSUE TITLE
Data definizione pratica

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#845]
Si chiede come mai tramite web app nelle iscrizioni  e' possibile impostare e salvare la data di definizione della pratica senza la gestione del procedimento, mentre tramite web service, inviando la data indicata, questa non viene salvata e viene segnalato con warning EN112 che il procedimento indicato e' inesistente.  

Grazie
Carla Musian
Insiel mercato

**Comment by azabatta** [comment]
Buongiorno, 
è possibile avere l'identificativo di un evento anagrafico che presenta la problematica segnalata?
Grazie

**Comment by CarlaMusian** [comment]
Buongiorno,
facendo ulteriori verifiche ho scoperto che la documentazione ANPR sul portale :Specifiche di interfaccia, oggetti, testataRichiesta non e' allineata con i tracciati XSD, wsdl1000, tipoDato.xsd, dove dopo la data di decorrenza e' riportata la "dataDefinizionePratica" mentre negli oggetti e' assente.

**Comment by azabatta** [comment]
La documentazione dell'oggetto excel testataRichiesta è stata aggiornata.
Grazie della segnalazione
