### ISSUE TITLE
[1002] Re-iscrizione di cancellato per comune non subentrato

### ISSUE THREAD

**Issue by busaster** [italia/anpr#848]
Ambiente di produzione, comune di Modigliana.

In data 08/08/2018 è stato cancellato per emigrazione in non subentrato il soggetto id ANPR 30630703.
In data 1/10/2018 lo si vuole re-iscrivere per immigrazione da non subentrato con il servizio 1002.
La chiamata però (id operazione ANPR 18426862) va in errore : idSchedaSoggettoANPR 30630703 non presente o dati anagrafici incongruenti.

Posto che la scheda con quel ID ANPR è presente (coem cancellato),  non riusciamo a capire quali siano i dati incongruenti che causano il blocco.

Potete aiutarci ? 
Grazie

Gianrico Busa
Maggioli Spa

**Comment by asqueglia** [comment]
Buongiorno,
nella re-iscrizione di un soggetto è obbligatorio specificare l'idAnpr del soggetto. Il messaggio di errore ritorna proprio l'idAnpr da utilizzare nella richiesta di iscrizione, corrispondente ai dati anagrafici del soggetto presente in ANPR in stato cancellato. Il senso è che viene mantenuto lo stesso identificativo originariamente attribuito al soggetto da ANPR.

**Comment by asqueglia** [comment]
Si ha ragione è presente l'idANPR. Indaghiamo e le facciamo sapere quanto prima

**Comment by asqueglia** [comment]
Dobbiamo effettuare un intervento al controllo bloccante. Faremo sapere appena possibile riprovare. Grazie per la segnalazione

**Comment by asqueglia** [comment]
Buongiorno, è possibile riprovare.

**Comment by busaster** [comment]
l'operazione è terminata con successo.
Chiudo la segnalazione
