### ISSUE TITLE
Chiarimenti sulla  data di ultimo aggiornamento APR 

### ISSUE THREAD

**Issue by ANPRCDBO** [italia/anpr#85]
Salve,
per poter alimentare correttamente la data di ultimo aggiornamento APR nel subentro,
avremmo necessita' di capire se, per questa data, si intende l'ultima variazione di indirizzo oppure qualsiasi rettifica/variazione successiva

Cordiali Saluti
Elena Di Martino
Team Sipo
Comune Bologna

**Comment by gcarbonin** [comment]
la residenza ha una sua data di decorrenza; la data di ultima variazione è quella della scheda esclusa la residenza

**Comment by ANPRCDBO** [comment]
Stando al suo esempio: poniamo il caso di persona iscritta il 10-3-2017 con subentro del comune 12-3-2017 e data alimentata con la data del subentro. Il comune ricevera' l'APR4 successivamente al subentro; la mutazione "di completamento" dovrebbe decorrere dal 10-3-2017. ANPR non l'accettera' in questa data ma richiedera' una data di decorrenza non antecedente al 12-3-2017.
Cosa succede se viene aperta una pratica con piu' persone e prima della chiusura muore il capofamiglia e vengono variate le parentele degli altri componenti della famiglia, ANPR aggiornera' la data di ultimo aggiornamento della scheda e se la risposta affremativa ci sono problemi nella chiusura della pratica?

**Comment by gcarbonin** [comment]
la persona, se nel subentro la persona viene conferita con data di prima iscrizione nel comune = 10-3-2014, data decorrenza residenza = 10-3-2014, data ultima variazione = 10-3-2014, viene inserita in ANPR con data inizio validita della scheda = 10-3-2014; alla ricezione dell'APR4 di completamento la mutazione decorre correttamente dal 10-3-2014. nel secondo caso la data di decorrenza dovrà essere compatibile con l'ultima variazione effettuata
