### ISSUE TITLE
TipoGeneralità.luogonascita non congruente alla data di nascita

### ISSUE THREAD

**Issue by PaDigitaleSpa** [italia/anpr#851]
Buongiorno,
mi rifaccio alla richiesta #571 CITTADINI CON COMUNE NASCITA NON VALIDO ALLA DATA DI RIFERIMENTO per avere un chiarimento maggiore sui servizi.

Un soggetto nato il 09/07/1931 è passato in ANPR con il Comune di nascita ORATINO (CB)
La persona ha l'atto di nascita registrato all'ufficio di stato civile del comune di Oratino 
Ha inoltre il codice fiscale (MSTTLI31L49G086S) calcolato con il codice belfiore del Comune di Oratino ed è validato dall'agenzia delle entrate 

Nel registrare una carta di identità cartacea però, il sistema ANPR restituisce l'errore "TipoGeneralità - il campo tipogeneralità.luogonascita non è congruente con la data della nascita 09/07/1931"

In effetti dal 13.05.1928 al 21-05-1947 il comune di Oratino risultava cessato.
In quel periodo il Comune di riferimento era Campobasso.

Nella Issues #571 si dice che per evitare disagi ai cittadini è stata introdotta una tolleranza, sia nel subentro che nei servizi, che permette di procedere nonostante questa anomalia.

Ora, fermo restando che il comune dovrebbe segnalare la situazione alla Prefettura e al Ministero in quanto anagrafe e stato civile non dovrebbero contenere dati diversi, dato che il Comune è bloccato su questo errore, come possono ovviare a quest'inconveniente?

**Comment by gcarbonin** [comment]
Verifichiamo il motivo dell'errore in quanto non dovrebbe uscire

**Comment by frmariani** [comment]
per favore può indicarmi l'idoperazione ? 
grazie

**Comment by gcarbonin** [comment]
Non troviamo nessuna operazione che riguardi questo soggetto. Abbiamo provato anche noi e  non abbiamo ricevuto nessun errore. Dovrebbe fornirci qualche indicazione

**Comment by PaDigitaleSpa** [comment]
Buongiorno,
questa mattina il Comune ha effettuato controlli più approfonditi dandoci conferma che l'errore non si verifica in anpr. Riteniamo chiusa la richiesta

Grazie, saluti
