### ISSUE TITLE
Blocco in stampa stato famiglia

### ISSUE THREAD

**Issue by busaster** [italia/anpr#852]
Ambiente di produzione, comune di Piacenza. (vedi anche #844)

Tentando di produrre il certificato di stato famiglia per il soggetto id anpr 27434502  veniamo bloccati dall'errore EN222.

Abbiamo controllato le mutazioni avvenute in quella famiglia e ne risultano solo due :
1) mutazione 5008 di tipo 01 per il suo famigliare 27427642 (id operazione 16499613)
2) mutazione 5008 di tipo 12 per il soggetto cui si sta facendo il certificato (id anpr 27434502) con la quale sono stati rettificati i dati di matrimonio inserendo gli estremi dell'atto (non il coniuge) (id operazione 16498789).

Ora io non vorrei che la seconda mutazione fosse stata interpretata da ANPR come un nuovo matrimonio ed abbia quindi bloccato la certificazione.

Potete controllare ?

Grazie.

Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
quando si modifica il matrimonio la certificabilità della famiglia viene sempre bloccata.

**Comment by busaster** [comment]
Abbiamo fatto delle prove in ambiente di test.
Abbiamo preso una famiglia di due persone, IS (id ANPR 9458986) e CONVIVENTE (id ANPR 9461251) e due chiamata 5008 di tipo 12 le abbiamo sposate (id ANPR 16661508 e 16661506). 
Non abbiamo eseguito nessun'altra chiamata a servizi di mutazione.

A quel punto abbiamo richiesto con il WS 6001 il certificato di stato famiglia ed il certificato di stato famiglia con relazioni di parentela ma non abbiamo avuto alcun blocco (id ANPR 16661521 e 16661522).

A cosa è dovuta questa differenza di comportamento tra test e produzione ?

**Comment by gcarbonin** [comment]
quando avete fatto la prova, c'era una versione del SW del servizio 6001 non corretta. Se provate ora, il comportamento è esattamente quello che avete riscontrato in produzione
