### ISSUE TITLE
errore server dopo ricerca 3002

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#853]
Ambiente di Produzione
Comune di Bressanvido

Effettuando una ricerca con la chiamata 3002, il comune sta ricevendo il seguente messaggio:
'The server encountered an internal error that prevented it from fulfilling this request'

Potete verificare?
Grazie

**Comment by gife67** [comment]
Buonasera,
cortesemente potreste fornirmi il valore dell'**idOperazioneComune** utilizzato nell'invocazione del Servizio 3002?
Grazie

**Comment by SAlberto** [comment]
Per il momento non si è più presentato l'errore, grazie lo stesso
