### ISSUE TITLE
Ripristino posizione anagrafica

### ISSUE THREAD

**Issue by sfmodena** [italia/anpr#854]
Comune di Modena, ambiente di produzione

Buonasera,
in data 18/06/2018 a Modena cancelliamo il soggetto con idANPR 19236688 per emigrazione nel comune allora non subentrato di Correggio.
Il 27/07/2018 Correggio subentra iscrivendo il soggetto al quale successivamente però rigetta l' immigrazione, inserendo su ANPR il rigetto come "CANCELLAZIONE PER ALTRI MOTIVI" (id operazione ANPR 14604804).
Ora a Modena dovremmo ripristinare la posizione anagrafica del soggetto, ma non possiamo annullare la nostra cancellazione perchè le operazioni svolte da Correggio ci bloccano; in quale modo possiamo procedere?

Grazie
Sonia Fiorini
Comune di Modena

**Comment by gcarbonin** [comment]
deve fare un'iscrizione per ripristino

**Comment by sfmodena** [comment]
Chiedo scusa ma non ne abbiamo mai fatte prima d' ora. Nel menu "Registrazione" trovo soltanto le voci "Iscrizione per nascita" e "Iscrizione per altri motivi", suppongo di dover usare la seconda, ma devo reinserire da zero tutti i dati del soggetto? Non è possibile recuperare quanto già presente?
Grazie

**Comment by gcarbonin** [comment]
Iscrizione per altri motivi; nel motivo di iscrizione si specifica Ripristino posizione anagrafica. Deve indicare inoltre lo stesso idanpr.

**Comment by sfmodena** [comment]
I motivi di iscrizione che mi vengono proposti sono solo questi (non trovo il ripristino):

Esistenza (giudizialmente riconosciuta)
Immigrazione (da comune non transitato)
Immigrazione dall'estero
Ricomparsa (da irreperibilita')
Rimpatrio da AIRE
Rettifiche post censuarie
Trasferimento di domicilio di un senza fissa dimora (da comune non transitato o nato da genitori senza fissa dimora)
Altri motivi

**Comment by gcarbonin** [comment]
Ha ragione manca il ripristino. Facciamo sapere quando possibile riprovare

**Comment by sfmodena** [comment]
Buongiorno, purtroppo avremmo urgenza di iscrivere nuovamente il soggetto perchè ora ci ha presentato una pratica di cambio indirizzo, ci sono novità sul ripristino o qualche soluzione alternativa? 
Grazie
Sonia Fiorini

**Comment by sfmodena** [comment]
Ha funzionato, grazie. Rimane un dubbio: sulla scheda anagrafica del soggetto ora sembra che sia presente dalla data di iscrizione per ripristino e non da prima del subentro come era in origine: può creare problemi?

**Comment by LU033AN** [comment]
Comune di Viareggio
dobbiamo fare un ripristino come sopra descritto ma inserendo il codice IDANPR del soggetto non consente di recuperarne i dati, dobbiamo per forza reinserire tutti i dati? inoltre avendo provato anche a fare ciò, nonostante il soggetto sia celibe, mi viengono richiesti i dati del coniuge senza poter completare l'operazione. come possiamo procedere?
