### ISSUE TITLE
STAMPA SCHEDA  INDIVIDUALE - errore stampa parentela

### ISSUE THREAD

**Issue by bmalavolti** [italia/anpr#856]
Buongiorno,
volevo segnalare che nella stampa scheda individuale di una persona appartenente ad una convivenza, il legame di parentela è MARITO/MOGLIE anziché MEMBRO DELLA CONVIVENZA. Nel folder relativo alla famiglia/convivenza - elenco componenti - il dato invece è corretto.
Barbara Malavolti - Comune di Faenza

**Comment by gcarbonin** [comment]
Come sempre, possiamo fare le verifiche del caso a condizione di avere un identificativo qualsiasi (operazione, soggetto) escluso il codice fiscale.

**Comment by cmigliardi** [comment]
grazie per la segnalazione, verifichiamo e Le facciamo sapere quando riprovare.

**Comment by cmigliardi** [comment]
potete riprovare - grazie
