### ISSUE TITLE
[3002] Errore in ricerca persona per nome non congruente

### ISSUE THREAD

**Issue by busaster** [italia/anpr#857]
Ambiente di produzione, comune di Chieri.

Cerco un soggetto con filtro su cognome,nome,data e luogo di nascita (id operazione ANPR 18663670).
Il servizio mi ritorna però l'errore EN068: il nome del soggetto estratto non è congruente con quello passato come parametro di ricerca.

Consultando però la scheda da webapp non risultano incoerenze, i dati del soggetto sono coerenti con quanto specificato nel filtro.

Qual è la causa del blocco ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Salve.
Per l'id operazione ANPR che ci avete fornito (18663670), il cognome registrato su ANPR termina per *IJA, mentre nell'operazione viene trasmesso *JIA (in sostanza la I e la J sono invertite).
Al momento il soggetto risulta iscritto nel comune di Torino.
Da web forse i parametri inviati sono stati diversi (ad esempio il solo codice fiscale oppure nome e cognome come registrati su ANPR).
Siamo a disposizione per ogni ulteriore chiarimento.

**Comment by mttfranci** [comment]
Prego.
