### ISSUE TITLE
Segnalazione su Rettifica generalità

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#858]
Ambiente Produzione
Comune di Bardonecchia
Id Operazione ANPR: 18836921

Stavano rettificando le generalità di una loro residente.
Il messaggio di ritorno è stato: 
"Attenzione! **Sono stati modificati** i dati anagrafici del soggetto senza validazione di Agenzia Entrate."
Però entrando sul portale ANPR e ricercando la persona sono ancora presenti le vecchie generalità.

Potete verificare? grazie

**Comment by gcarbonin** [comment]
Quel messaggio indica un errore bloccante : l'esito dell'operazione è XXXX e il codice di errore (al di là della frase che può essere migliorata) EN230 è di tipo "E". Quindi si vedono i dati vecchi perchè la variazione non è stata effettuata-

**Comment by SAlberto** [comment]
Buongiorno, 
abbiamo nuovamente verificato la situazione e abbiamo notato che in Agenzia delle Entrate l'individuo è presente due volte, una con le generalità vecchie (comunicate dal comune tramite INA-SAIA e collegato ad ANPR), l'altra con le generalità nuove (comunicate dal Ministero Interno - Questura).

Abbiamo provato tramite la funzione "Risoluzione disallineamenti con Agenzia Entrate" a risolvere il problema, ma non siamo riusciti a richiamare l'individuo.

Come possiamo risolvere il problema?
Grazie

**Comment by gcarbonin** [comment]
paragrafo 4.1 del documento disponibile a questo link https://www.anpr.interno.it/portale/documents/20182/239162/Risoluzione+disallineamenti+con+l%27Agenzia+delle+Entrate+28_03_2018.pdf/b7235e8c-de9b-4c4b-960c-659f388a8489

**Comment by SAlberto** [comment]
Buonasera,
come da documentazione abbiamo provato ad effettuare l'unificazione dal portale, dopo aver scelto come versione corretta quella dell'AE, ci è comparso il seguente errore:

"Esito ANPR: Individuate due posizioni in AT non unificabili (Codice: EAM9C)"

Il problema è che l'individuo è doppio in Agenzia delle Entrate, una volta con le generalità vecchie (comunicate dal comune tramite INA-SAIA e collegato ad ANPR), l'altra volta con le generalità nuove (comunicate dal Ministero Interno - Questura).

Come dobbiamo procedere? Grazie

**Comment by sfmodena** [comment]
Comune di Modena, ambiente di produzione

Buonasera, mi permetto di inserirmi per segnalare alcuni casi analoghi in cui la funzione di Rettifica Disallineamenti purtroppo non consente di allineare le posizioni tra AT e ANPR e nemmeno di collegare due CF relativi alla stessa persona. In particolare:
1) al soggetto con idANPR 19288598 sono state rettificate le generalità per allinearle con quelle presenti sul permesso di soggiorno; in AT esiste una posizione con dati perfettamente uguali a quelli di ANPR che però non risulta marcata ANPR. Tentando la "CONFERMA AE" (unica opzione possibile) viene restituito questo errore:
   "Esito AE: Codice Fiscale non presente in AT (Codice 12)"
successive ricerche in AE  evidenziano la presenza di altre tre posizioni con le stesse generalità aventi CF numerico e tra loro non collegate. Hanno qualche peso?
2) dobbiamo rettificare le generalità del soggetto con idANPR 19339556 con posizione in AT marcata ANPR: viene restituito l' errore:
   "Soggetto non individuato in AT - Codice fiscale NON variato (Codice: EAM12)"
(in realtà la variazione non dovrebbe modificare il codice fiscale). In AT è presente un' altra posizione con CF numerico e generalità uguali a quelle che si vogliono ottenere 
con la modifica; tentando di collegare i due codici fiscali con la Risoluzione disallineamenti si ha l' errore:
   "Esito AE: Soggetto non individuato in AT - Codice fiscale NON variato (Codice 12)"
Quest' ultimo caso è stato segnalato già da giugno (e risollecitato di recente) per essere girato alla Direzione Centrale dell' AE; il cittadino sta aspettando da mesi di poter avere la CIE con le generalità corrispondenti al permesso di soggiorno. 
C'è poi una stranezza: quando si cerca un soggetto nato all' estero nella funzione di Rettifica Disallineamenti nell' elenco viene sempre visualizzato come stato di nascita AFGHANISTAN che 
non ha nessuna relazione con quello della persona (es. FILIPPINE o MOLDOVA).

A fronte di questi casi apparentemente non gestibili da ANPR è previsto che possa essere attivato un canale diretto tra Comuni e Agenzia Entrate (o Ministero dell' Interno) per sbloccarli?

Grazie
Sonia Fiorini
Comune di Modena

**Comment by gcarbonin** [comment]
Per SalAlberto: dobbiamo seguire il comune mentre esegue l'operazione di collegamento dei CF. Mi mandi per favore i riferimenti della persona da contattare
Per Modena stiamo analizzando i tre casi segnalati

**Comment by SAlberto** [comment]
Certamente, dove posso mandarvi i riferimenti dell'operatore da contattare?

**Comment by gcarbonin** [comment]
si sulla mail privata

**Comment by SAlberto** [comment]
Inviati i riferimenti a segnalazioni-anpr@teamdigitale.governo.it

grazie

**Comment by frmariani** [comment]
@SAlberto:  ho chiamato il Comune ed abbiamo risolto il problema collegando i due CF tramite la funzione Risoluzione disallineamenti con AE;

@sfmodena : se mandate i riferimenti del Comune sulla mail privata,  proviamo a contattarli per risolvere i problemi

**Comment by sfmodena** [comment]
Buongiorno,
i casi di Modena sono stati già affrontati più volte (l' ultima nel pomeriggio di martedì scorso 9 ottobre) con la Dott.ssa Vinzani, che li ha ritenuti non gestibili da ANPR e li ha girati all' Agenzia delle Entrate. Quando avremo risposta da AE potremo considerarli chiusi, resta però il problema generale legato all' impossibilità di trattare molti casi che coinvolgono codici fiscali numerici, in particolare se assegnati dal Ministero dell' Interno.
Grazie
Sonia Fiorini
Comune di Modena

**Comment by SAlberto** [comment]
Buongiorno,
il comune di Bardonecchia (TO), Codice Istat 001022
ha altri due casi simili.
Due anagrafiche per le quali non si riesce a rettificare i dati anagrafici per incongruenze con Agenzia delle Entrate non risolvibili in alcun modo.

Come ci dobbiamo comportare?
Grazie

**Comment by sfmodena** [comment]
Comune di Modena, ambiente di produzione
Buonasera,
purtroppo abbiamo di continuo nuovi casi non gestibili con le funzioni della webapp. In particolare per i 3 soggetti con idANPR 23224986, 21420901 e 21420888 l' Agenzia delle Entrate ha generato i CF alfanumerici senza collegarli ai cf numerici assegnati dal Ministero dell' Interno e chiede a noi di unirli. Non ci riusciamo e i cittadini ci segnalano seri problemi nella stipula del contratto di lavoro, quindi avremmo urgenza di sbloccare la situazione.
Altra situazione che attende da mesi una soluzione è quella del soggetto con idANPR 19224375 , con due posizioni scollegate e marcate ANPR in AE, nato in un comune ora cessato e apparentemente impossibile da trattare con le funzioni di risoluzione disallineamenti. I familiari ci sollecitano con urgenza l' unione delle posizioni per motivi fiscali.

Grazie, saluti
Sonia Fiorini

**Comment by rvinzani** [comment]
Gent.le Sig.ra Fiorini, in attesa di rendere disponibile il servizio di collegamento per i soggetti indicati può inviarmi sulla mia email il CF numerico e alfanumerico dei soggetti in modo da chiedere la cortesia ad Agenzia delle Entrate di effettuare il collegamento.
Mi mandi anche gli estremi del quarto caso in modo da cercare di risolvere anche questo
Saluti

**Comment by sfmodena** [comment]
Buonasera Dott.ssa Vinzani, ho inviato i dettagli dei soggetti sulla sua mail.
Grazie, cordiali saluti
