### ISSUE TITLE
Web app - N. Protocollo e Piano su certificati

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#86]
Nella stampa su carta dei certificati, il numero di protocollo viene troncato nelle ultime 2 cifre perché troppo vicino al margine destro: sarebbe possibile allinearlo con il margine del QR code e dei restanti elementi allineati a destra?
Segnaliamo inoltre che l’indirizzo riportato sui certificati contiene sempre anche il piano, se popolato: questa informazione, a quanto ci risulta, non dovrebbe comparire.
Grazie.
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino
data test: 6/4/2017 - Ambiente dptest

**Comment by gcarbonin** [comment]
Dipende dal settaggio della stampante: se osserva a video il PDF il protocollo è completo. Ho appena fatto una stampa ed esce correttamente.
Non abbiamo avuto indicazioni da nessuno di non stampare il piano.
