### ISSUE TITLE
[A006] espatrio bloccato per incongruenza decorrenza residenza

### ISSUE THREAD

**Issue by busaster** [italia/anpr#860]
Ambiente di produzione - Comune di Forlì.

Tentiamo di chiamare il servizio A006 per iscrivere all'aire per espatrio il cittadino ID ANPR 24730453 con decorrenza 03/09/2018.
Ad oggi il cittadino risiede in APR con decorrenza 20/02/2000.
La chiamata al servizio A006 va però in errore : "EN237 : La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata" , id ANPR 18479130

Come mai ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
Controllate l'id famiglia che avete indicato (FE3001053)  che non sembra essere coerente,

**Comment by busaster** [comment]
era esattamente così, il comune aveva scordato di inserire il corretto numero famiglia.
Grazie
