### ISSUE TITLE
[4001] Estrazione con esito negativo

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#865]
Un'ora fa, da ambiente PROD di Bistagno (AL) è stata effettuata una richiesta di estrazione tramite 4001 (IdOperazioneANPR: 19653243). Adesso tramite 3007 vedo che lo "stato lavorazione"=3, cioè ESITO NEGATIVO. 
Potreste comunicarmi, gentilmente, qual'è il motivo?

**Comment by Eduardo1977** [comment]
Posso riprovare?

**Comment by azabatta** [comment]
Sì,  è possibile riprovare. Restiamo in attesa di un cortese riscontro

**Comment by Eduardo1977** [comment]
L'esito dell'ultima estrazione è positivo: statolavorazione=2

Grazie
