### ISSUE TITLE
[6001] id operazione ANPR in caso di errore

### ISSUE THREAD

**Issue by busaster** [italia/anpr#868]
Sia in Ambiente di test (Poggio a Caiano) che in ambiente di produzione (Bergamo)

Le chiamate 6001 che vanno in errore hanno nella risposta impostato come ID ANPR il valore di ID OPERAZIONE COMUNE (es la id operazione comune 1021662 codIstat 100004 dell'ambiente di test)

Busa Gianrico
Maggioli Spa

**Comment by rnapoli1983** [comment]
Grazie per la segnalazione. 

Faremo subito delle verifiche in merito.

**Comment by rnapoli1983** [comment]
Abbiamo provveduto alla risoluzione delle problematiche da voi riscontrate e prontamente segnalate.

Nel ringraziarvi ancora per la collaborazione, poterei chiedervi di eseguire dei nuovi test ?

Grazie mille

**Comment by busaster** [comment]
Confermo che ora funziona , torna il corretto id anpr nella risposta.
Chiudo.
Grazie.
