### ISSUE TITLE
[6001] internal server error

### ISSUE THREAD

**Issue by busaster** [italia/anpr#869]
Ambiente di Produzione, Comune di Perugia.

Tentando di effettuare alcuni tipi di chiamate 6001 (come id operazione comune 112613 codistat 054039) il servizio va in errore ritornando una SoapFault "SOAPFaultException: Internal Error".

Potete aiutarci ?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by rnapoli1983** [comment]
Grazie per la segnalazione.

Faremo subito delle verifiche in merito.

**Comment by rnapoli1983** [comment]
Abbiamo provveduto alla risoluzione delle problematiche da voi riscontrate e prontamente segnalate.

Nel ringraziarvi ancora per la collaborazione, poterei chiedervi di eseguire dei nuovi test ?

Grazie mille

**Comment by busaster** [comment]
Il cliente ha verificato ed ora la certificazione ha ripreso a funzionare.
Chiudo la issue.
Grazie
