### ISSUE TITLE
Web app – Consultazione tracciato di subentro 

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#87]
Data test:6/4/2017 - Ambiente dptest
Nell’elenco delle operazioni riferite al soggetto ID ANPR 987755, la consultazione dell’ID operazione ANPR 95736 (subentro in test) dà una pop-up con il seguente messaggio di errore:
"This page contains the following errors: error on line 3 at column 1: Document is empty
Below is a rendering of the page up to the first error."
Esiste un’altra modalità (anche attraverso altre funzioni) per consultare i dati conferiti in fase di subentro e non visibili nella Consultazione?
Ad esempio, per il soggetto in esame, la certificazione storica di residenza riporta come data di prima iscrizione nell’APR del Comune di Torino la data 07/06/1959, che presumiamo essere stata conferita con il tag <DataUltimoAggiornamentoAPR>, non visibile nella Consultazione. Analogamente non è visibile il dato relativo al tag < dataPrimaIscrizioneComune>.
Grazie.
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino

**Comment by gcarbonin** [comment]
I dati del subentro sono visibili effettuando una consultazione alla data del subentro. La data prima iscrizione nel comune è stata aggiunta di recente nei dati del subentro e quindi non è presente nei dati di Torino che sono molto "antichi". Nel caso specifico, 7-6-1959 è la data di decorrenza della residenza indicata nel subentro.
