### ISSUE TITLE
Gestione dei Duplicati in Produzione

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#872]
Buongiorno,

Ambiente di Produzione
Comune di Sondrio

In data odierna il comune di Sondrio ha effettuato il Subentro in Produzione, al termine abbiamo consultato il file dei duplicati.
I duplicati trovati sono quasi tutte situazioni in cui:
- il Comune di Sondrio ha iscritto questi individui e trasmesso l'APR4 al Comune di precedente iscrizione (già subentrato), che però non ha avuto ancora il tempo di effettuare l'emigrazione di tali individui in ANPR prima del subentro odierno.
- individui precedentemente residenti a Sondrio, che sono stati recentemente iscritti in altri Comuni Subentrati, ma che non hanno ancora trasmesso a Sondrio l'APR4, per cui risultano ancora residenti nel comune al momento del subentro (avvenuto in data odierna).

Come si devono gestire queste situazioni?
Ringrazio anticipatamente

**Comment by gcarbonin** [comment]
Rispettivamente:

- il comune farà la cancellazione per doppia iscrizione;
- Sondrio può cancellare per doppia iscrizione

**Comment by SAlberto** [comment]
Perfetto grazie,
le chiedo ancora solo una cosa, per i residenti andrà usato il motivo cancellazione 10 (doppia iscrizione), mentre per i doppioni AIRE quale va usa usato?

Grazie

**Comment by gcarbonin** [comment]
come gli apr

**Comment by SAlberto** [comment]
Chiedo scusa, ma non capisco, per gli apr dobbiamo guardare la tabella di decodifica 15 e lì è presente il codice 10 (doppia iscrizione) mentre per gli AIRE dobbiamo usare la tabella di decodifica 28 e qui non trovo un codice per la doppia iscrizione, quale va usato?
Grazie.

**Comment by gcarbonin** [comment]
Da servizio può utilizzare il codice 10. Dobbiamo aggiornare la documentazione

**Comment by ncapozzi** [comment]
Buongiorno, è stata aggiornata anche la documentazione

N. Capozzi
