### ISSUE TITLE
[5008] Errore nella modifica dello stato civile

### ISSUE THREAD

**Issue by ftabino** [italia/anpr#874]
Sto avendo problemi nell'effetuare la mutazione dello stato civile.

Ambiente di **TEST**
Comune **076063**

```xml
<idOperazioneANPR>17642875</idOperazioneANPR>
```

Ricevo il seguente errore
```xml
<listaErrori>
    <errore>
        <codiceErroreAnomalia>999</codiceErroreAnomalia>
        <tipoErroreAnomalia>E</tipoErroreAnomalia>
        <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
    </errore>
</listaErrori>
```

**Comment by asqueglia** [comment]
Buongiorno, 
la richiesta che è stata trasmessa non è ben formata in quanto manca della parte generalità da modificare obbligatoria per una mutazione dati anagrafici. 
Ci siamo già accorti della mancata gestione di tale errore. A stretto giro verrà rilasciata una fix per gestire correttamente l'errore. 
In tale situazione in risposta riceverete l'errore bloccante 
EN139  Inserire tutti i dati anagrafici anche quelli non modificati

**Comment by ftabino** [comment]
La ringrazio per le delucidazioni
