### ISSUE TITLE
[5005] Errore permessi utente in TEST

### ISSUE THREAD

**Issue by busaster** [italia/anpr#877]
Ambiente di Test, comune di Gorgonzola.

Operazioni eseguite con il solito utente COMUNETEST+codistat

Tentando di fare una mutazione residenza, ci viene ritornato l'errore "EN493 : L'utente non dispone dei privilegi per eseguire l' operazione". La risposta ha ID ANPR 0. (ID Operazione comunale 27141 codIstat 015108).

Abbiamo provato una 1002 e una 5001 che si sono concluse però con successo.

Potete aiutarci a capire il problema =?
Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Abbiamo già apportato una correzione per il servizio 5005 per la segnalazione dell'issue #876.
Potete riprovre?

**Comment by busaster** [comment]
Ora funziona.
Chiudo.
Grazie
