### ISSUE TITLE
[WEBAPP] caricamento file di subentro e controlli date

### ISSUE THREAD

**Issue by busaster** [italia/anpr#878]
Oggi 12/10/2018 ,durante il subentro di un nostro cliente, caricando il file degli APR nella webapp otteniamo questo errore :

![image](https://user-images.githubusercontent.com/1733338/46869086-ef16d780-ce2a-11e8-9363-0cfde234fc35.png)

Il soggetto a riga 216 ha avuto una variazione oggi (12/10/2018)  prima di eseguire l'estrazione dati.

Come mai questo blocco ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
Si trattava di un nostro errore già rimosso
