### ISSUE TITLE
[5008] tipoMutazione '04' (permesso di soggiorno) - Errore EN489 

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#879]
ambiente di PRODUZIONE - comune di Pioltello (MI)

dalla Questura di Milano è stata rilasciato un documento di soggiorno di tipo "Ricevuta", che ha queste caratteristiche nell'indicazione del numero: XXXX99XX9X@99999

tentanto l'invio della comunicazione corrispondente (ws 5008), i nuovi controlli di validazione (codDestinatario ANPR01) bloccano la comunicazione con questo errore:
```
<errore>
  <codiceErroreAnomalia>EN489</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La richiesta non risulta valida secondo i nuovi XSD [Campo:'numeroSoggiorno']</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018008483)

impostando invece il codDestinatario ad ANPR00 la comunicazione è stata accettata.
potete verificare in consultazione il numero reale del documento che è stato comunicato (idSoggettoANPR 23830596).
prima del 5/11 è il caso di inserire anche il carattere '@' tra quelli consentiti per il campo numeroSoggiorno?

se necessario vi invio nella posta privata la scansione del documento rilasciato dalla Questura...

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Ci faccia avere il documento sulla posta privata

**Comment by mttfranci** [comment]
Salve, non è previsto di estendere i valori ammessi per il numero soggiorno.
In caso potete tramettere il permesso come tipo 6 o 8 e senza passare il carattere nel numero.
(Anche perchè non sembra trattarsi di un vero e proprio permesso di soggiorno).

**Comment by AMonopoliADS** [comment]
il documento è stato trattato come "Ricevuta", pertanto è stato inviato come tipoSoggiorno '5'.
segnaliamo al cliente l'impossibilità di passare il carattere in ANPR e faremo in modo che non parta con i web-service.
allo stato attuale ci sono 3 soggetti per i quali l'informazione è stata inviata in regime di codDestinatario ANPR00.
quando diventerà operativa la modalità ANPR01, ci saranno problemi nell'interrogazione dei dati di questi soggetti?
grazie.

**Comment by mttfranci** [comment]
> quando diventerà operativa la modalità ANPR01, ci saranno problemi nell'interrogazione dei dati di questi soggetti?

Abbiamo rilassato alcune restrizioni per ridurre i problemi, #903, forniremo supporto per la risoluzione di questo tipo di problemi
