### ISSUE TITLE
Web App - Data di riferimento nei certificati storici

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#88]
Data test: 6/4/2017 - Ambiente dptest
Al momento il sistema consente di inserire una data di riferimento antecedente a quella di subentro del Comune. E' possibile inserire un blocco nel caso di richiesta stampa da Web App?

Inoltre, solitamente, la data di riferimento da indicare nei certificati storici consiste nella data a partire dalla quale desidero certificare la movimentazione anagrafica. Ad esempio, se indico la data di riferimento 01/12/2016, il certificato storico indicherà tutte le mutazioni intervenute a partire da tale data. Nel caso della certificazione storica ANPR sembra invece che tale data sia considerata come “tutti i movimenti fino al ...”.  Si tratta di una scelta ministeriale?
Grazie.
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino

**Comment by gcarbonin** [comment]
E' una richiesta da valutare che ha i suoi impatti: se il subentro è avvenuto il 10-3-2017 e il 3-5-2017 arriva una comunicazione di decesso avvenuto il 8-3-2017, non si riuscirebbe a fare uno storico di residenza al momento del decesso, avvenuto prima del subentro.
Riguardo alla  "data di riferimento", preciso che  è sempre stata intesa (correva il mese di aprile dell'anno 2014) come "tutti i movimenti fino al" e non abbiamo rilievi nemmeno dai comuni subentrati.
