### ISSUE TITLE
[3003] operazioni mancanti in test

### ISSUE THREAD

**Issue by busaster** [italia/anpr#880]
Ambiente di Test, comune di Darfo Boario Terme

sembra che il servizio di recupero operazioni 3003 non ritorni dati dove ce lo aspetteremo.
Ad esempio con id operazione ANPR 16649382 cerchiamo tutte le operazioni di stato 2 con filtro date dal 2018-10-08T00:00:00 al 2018-10-12T16:40 e ci viene ritornato "nessun risultato".
Ma siamo certi che il giorno 8 alle ore 9:32 è stata completata con esito positivo l'operazione ID ANPR 16677556.

Allo stesso modo se cerchiamo le operazioni N015 con stato lavorazione 7 eseguite dal 01/10/2018 al 12/10/2018 (id op ANPR 16650104) non ci viene ritornato nulla, mentre dovrebbe essercene una il 5/10/2018.

Analoghe richieste su altro schema di test (Gorgonzola) sembrano funzionare correttamente.

Potete aiutarci a capire il problema ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by azabatta** [comment]
Buonasera, 
è possibile ricontrollare gli identificativi delle richieste?
Da una verifica effettuata in ambiente di TEST_COMUNI  risulta: 
-	IdOperazioneANPR 16649382: N010 non fruite  nel periodo 25- 26 settembre 2018
-	IdOperazioneANPR 16650104: N014 non fruite nel periodo  26-27 settembre 2018
Grazie

**Comment by busaster** [comment]
Le notifiche attese sono proprio quelle due.
Però le ricerche 3003 di ID ANPR 16650339 (per le N014) e ID ANPR 16650337 (per le N010) non restituiscono nessun risultato. Il filtro utilizzato mi sembra corretto, riporto qui per comodità quello della ricerca delle N014 :
`<statoLavorazione>7</statoLavorazione>`
`<operazioneRichiesta>N014</operazioneRichiesta> `
`<periodoRiferimentoRichieste>`
`  <dataOraIniziale>2018-09-25T00:00:00.000+02:00</dataOraIniziale>`
`  <dataOraFinale>2018-10-16T23:59:59.000+02:00</dataOraFinale>`
`</periodoRiferimentoRichieste>`

**Comment by azabatta** [comment]
Buongiorno, di seguito i risultati dei riscontri effettuati.
L’idOperazioneANPR 16650339 riporta come  periodo di riferimento per le N014 non fruite: 

<dataOraIniziale>2018-09-26T17:00:00.000+02:00</dataOraIniziale>
<dataOraFinale>2018-09-27T12:00:09.000+02:00</dataOraFinale>

Per il comune è presente una notifica N014 generata il  12 ottobre 2018 ore 12.10.

L’idOperazioneANPR 16650337    riporta come  periodo di riferimento per le N010 non fruite:

<dataOraIniziale>2018-09-26T17:00:00.000+02:00</dataOraIniziale>
<dataOraFinale>2018-09-27T12:00:00.000+02:00</dataOraFinale>		

Per il comune sono presenti due notifiche N010 generate il 27 settembre  2018 ore 14.55 e 15.25.

**Comment by busaster** [comment]
Se allargo il filtro al periodo 01/09/2018 - 16/10/2018 il risultato non cambia, non mi viene restituita nessuna operazione (ID 16652877 ricerca N014, ID 16652875 ricerca N010)

**Comment by azabatta** [comment]
Come verificato per le vie brevi il problema è stato causato dall'utilizzo di identificativi comunali già indicati in richieste precedenti.
