### ISSUE TITLE
Errore "Il campo Motivo contiene dei caratteri non validi"

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#881]
Dobbiamo aggiornare il luogo di nascita di un cittadino straniero (cod. ANPR 18860748).
Da mutazione tutti i dati, dopo aver selezionato il cittadino, appare subito il seguente errore:
"Il campo Motivo contiene dei caratteri non validi".

Comune di Altamura

**Comment by gcarbonin** [comment]
Che cosa indicate nel campo motivo?

**Comment by Finalmentesubentrati** [comment]
Sto operando direttamente dalla web app e non idea dove sia il campo motivo

**Comment by gcarbonin** [comment]
Ci sono caratteri non ammessi nei campi del censimento. Li trasformiamo in spazi?

**Comment by Finalmentesubentrati** [comment]
SI. Però sarei curioso di conoscere quali sono questi campi non ammessi.
Grazie

**Comment by gcarbonin** [comment]
Come specificato nella documentazione tecnica ANPR, per ogni campo è previsto un set di caratteri ammessi (numeri lettere spazio segni diacritici per nome cognome e indirizzo) e alcuni caratteri speciali; sono esclusi tutti i caratteri che non rispettano lo standard UTF8 (ad esempio alcune lettere accentate della tastiera di Windows) e quei caratteri speciali potenzialmente "dannosi" che possono introdurre vulnerabilità nel sistema (ad esempio i simboli > o <). nel caso specifico, ci sono trattini e due punti che non sono ammessi per il campo motivoCompilazione previsto tra i dati del censimento.

**Comment by Finalmentesubentrati** [comment]
I trattini e i due punti, nel campo censimento, ci sono a tutti i residenti però probabilmente la problematica emerge solo quando si fa una mutazione tutti i dati e non una mutazione residenza (recentemente proprio il sottoscritto ha fatto un cambio di residenza senza alcun problema).
Comunque se mi dice qual è la procedura corretta per eliminare tali segni "dannosi" provvedo in autonomia.
Grazie.

**Comment by gcarbonin** [comment]
Corretto: questi  dati "danno fastidio" soltanto quando si cerca di utilizzarli. Nella mutazione di residenza, non vengono utilizzati e quindi l'operazione va a buon fine. Per quanto riguarda la sistemazione degli errori, a breve forniremo in dicazioni. Le faccio sapere quando abbiamo sistemato il campo

**Comment by Finalmentesubentrati** [comment]
L'errore persiste.

**Comment by Finalmentesubentrati** [comment]
L'errore persiste.

**Comment by Finalmentesubentrati** [comment]
L'errore persiste

**Comment by mttfranci** [comment]
Scusate, potreste provare nuovamente? Grazie

**Comment by Finalmentesubentrati** [comment]
Ho identico problema per un altro cittadino a cui dobbiamo registrare il divorzio.
Dalla web app abbiamo l'errore Il campo Motivo contiene dei caratteri non validi.
Codice individuale ANPR 18875542
