### ISSUE TITLE
INSERIMENTO CARTA D'IDENTITA' RILASCIATA DAL CONSOLATO

### ISSUE THREAD

**Issue by subentrati** [italia/anpr#882]
Buongiorno come è possibile procedere con l'allineamento dei dati in ANPR soggetto con carta d'identità emessa nel 2009 dal consolato di Norimberga: errore EC 100: codice consolato 2301204 di rilascio carta incongruente con descrizione stato di competenza

**Comment by gcarbonin** [comment]
quale è il comune? in quale ambiente? quale è l'operazione che state effettuando? senza queste informazioni minime non possiamo aiutarvi Sarebbe poi utile per tutti utilizzare nomi leggeremente più rappresentativi; riporto i suggerimenti della pagina "New issue":
### In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

**Comment by subentrati** [comment]
Comune di Cesate. Subentro ANPR il 19/09/2018. Disallineamento con db locale e ANPR non è possibile inserire rilascio carta d'identità di un cittadino Aire rilasciata dal consolato soppresso (Norimberga).
Responsabile demografici e sicurezza. Non capisco codici di richiesta o identificativi

**Comment by gcarbonin** [comment]
Al momento non è possibile inserire consolati soppressi. Stiamo facendo una modifica avvertiamo quando possibile riprovare

**Comment by rossimon2018** [comment]
Comune di NOVELLARA. Subentro in ANPR il 15/06/2018. 
Anche noi abbiamo questo problema. Quando è prevista la modifica? Dobbiamo allineare una cittadina AIRE. Grazie

**Comment by MarcoMigliori** [comment]
Ambiente di produzione, Comune di Altavilla Vicentina.
Si è ripresentato questo caso per il Consolato di MONS.

**Comment by ncapozzi** [comment]
Rif. #833, #2724
