### ISSUE TITLE
Registrazione in ANPR

### ISSUE THREAD

**Issue by subentrati** [italia/anpr#883]
Comune di Cesate, ambiente di produzione
Buonasera,
in data 09/10/2018 cancelliamo il soggetto con idANPR 12204404 con motivazione ALTRO  proveniente da Milano ( già subentrata in ANPR)in quanto il soggetto era presente con dati anagrafici e codice fiscale errato ( inserimento fatto con iscrizione preliminare dal nostro Comune).
Ora con id ANPR 13430877 trovo il soggetto esatto proveninte da Milano come "CANCELLAZIONE PER EMIGRAZIONE" (id operazione ANPR 14604804).Ora io Comune di nuova iscrizione come faccio ad inserire la mia iscrizione agganciandola con la cancellazione di Milano?; in quale modo possiamo procedere?
Grazie
Cristina Pellegrinelli (Responsabile Servizi Demografici)
Comune di Cesate

**Comment by gcarbonin** [comment]
deve fare l'iscrizione mettendo l'id anpr del soggetto con i dati giusti (mi sembra di aver capito id ANPR 13430877)
