### ISSUE TITLE
Gestione dei comuni Ex-Italia prima del 1921

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#885]
Buongiorno,
ci è capitato in Comuni che seguiamo il caso di alcuni individui nati in Comuni ex-italia (ad esempio Orsera).
Per i Comuni delle province di Pola, Zara e Fiume, come nel citato esempio di Orsera, le tabelle ANPR riportano come prima data di istituzione quella del 05/01/1921.
Queste persone sono nate prima del 1921, per cui, non trovando alcun riscontro per il comune di nascita sulle tabelle di ANPR alla data di nascita, come dobbiamo gestire il luogo di nascita?
Cordiali saluti.

**Comment by gcarbonin** [comment]
Questo problema è già stato analizzato ( #719)
