### ISSUE TITLE
00 CERTIFICAZIONE ANPR: Il certificato non puo' essere emesso perche' i dati del contratto di convivenza risultano assenti o incompleti

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#886]
Comune di Alessandria

Buongiorno,
 
non riusciamo ad emettere il certificato ANPR di Convivenza di fatto della cittadina in quanto abbiamo l'errore
 
00 CERTIFICAZIONE ANPR: Il certificato non puo' essere emesso perche' i dati del contratto di convivenza risultano assenti o incompleti
 
In fase di presubentro e subentro non abbiamo ricevuto segnalazioni di anomalia riguardanti i circa 100 conviventi di fatto presenti in base dati, che dati sono da ritenersi obbligatori per le convivenze di fatto al fine di poterle certificare?

Come procedere?

Grazie

**Comment by AMonopoliADS** [comment]
salve.

per quello che abbiamo visto noi (se non è cambiato niente nel frattempo) il certificato NON documenta lo stato di Convivenza di Fatto, bensì il contratto di convivenza (tant'è che il tipoCertificato '19' è decodificato proprio come "Contratto di Convivenza")
pertanto viene rilasciato solo se esiste un contratto di convivenza nei dati del soggetto
se i soggetti interessati hanno istituito una convivenza di fatto, ma non hanno regolato i rapporti patrimoniali con un contratto di convivenza, non è previsto un certificato di questo tipo...

sul tema c'è stato qualche scambio anche nella issue #550 con alcuni contributi interessanti che invito a leggere

scusate l'intromissione...

Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Confermo: non si certifica la convivenza di fatto ma il contratto di convivenza.  E' previsto così da una circolare ministeriale.
