### ISSUE TITLE
1 Errore Anpr Cod: EC036 - Stato estero cittadinanza 998 inesistente sulla tabella di riferimento - -

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#887]
Comune di Alessandria

Buongiorno,

stiamo procedendo con l'iscrizione per nascita di cittadino con cittadinanza NON ATTRIBUIBILE in quanto figlio di cittadino KOSOVARO e di cittadina SERBA.

Al momento dell'invio abbiamo l'errore in oggetto come procedere?

Grazie

**Comment by gcarbonin** [comment]
Per quale motivo non è attribuibile?

**Comment by MarcoMigliori** [comment]
In questi casi sento la mancanza dell'intervento di qualche funzionario comunale.

Nell'attesa della risposta del Comune di Alessandria mi permetto di aggiungere qualche informazione: siamo nel caso di nato da due cittadini stranieri di diversa cittadinanza, di cui l'USC non può conoscere la legislazione ed eventuali accordi o incompatibilità. Ne al momento della registrazione della nascita è presumibile che i genitori abbiano già fatto le richieste necessarie ai loro consolati per poter produrre della documentazione (tradotta).
Il sistema INA-SAIA è stato implementato a settembre 2015 per gestire le codifiche che servono a questa e altre casistiche:


> http://servizidemografici.interno.it/it/content/avviso-aggiunta-di-nuovi-codici-la-comunicazione-dei-dati-di-cittadinanza
> (a suo tempo il link era questo, ora non funzionante per rifacimento sito)
> 
> Si comunica che dal prossimo 28 settembre il sistema INA SAIA accetterà anche i seguenti codici/valori per la comunicazione dei dati relativi alla cittadinanza:
> 
> 997 - In corso di definizione
> 
> 998 - Non attribuibile
> 
> 999 - Apolide

Alcuni siti comunali citano come normativa di cittadinanza non attribuibile: art.2, del d.P.R. n.394/1999

**Comment by RBiasi** [comment]
Alla fine stiamo usando la cittadinanza 997 In corso di definzione

**Comment by gcarbonin** [comment]
Rispondo alla domanda di Carla Musian : il 998 in quella accezione è utilizzato SOLO PER IL SUBENTRO, per evitare che i comuni siano costretti ad aggiornare la cittadinanza delle persone iscritti da tempo e residenti in stati ora soppressi. 
Per quanto riguarda la domanda RBiasi, il 997 è il valore corretto in quanto il bambino dell'esempio prima o poi avrà una cittadinanze.
