### ISSUE TITLE
[5008] Completamento dati AIRE - errore EN369  #818 - non funziona

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#888]
Insiel Mercato
 Comune di Tolentino   Ambiente di pre-subentro   Test effettuato il 17.10.2018  
 Comune di Piazzola sul Brenta  Ambiente di produzione Test effettuato il 18.10.2018

A fronte della nostra segnalazione #818 di cui abbiamo ricevuto mail di correzione da parte vostra abbiamo effettuato i test sia in ambiente di presubentro che in produzione e l'errore riscontrato permane.

Inviamo gli id ANPR delle nostre prove:
- 8609957 per l'ambiente di presubentro di Tolentino
- 22109813 per l'ambiente di produzione di Piazzola sul Brenta

Per tutti gli Aire vedovi e divorziati non riusciamo ad effettuare il completamento dati.

Tiziana Testa
Insiel Mercato

**Comment by gcarbonin** [comment]
In questi due casi particolari è quasi impossibile che possa funzionare. Per la posizione in produzione ci mandi una PEC per mettervi in condizioni di effettuare l'aggiornamento

**Comment by ncapozzi** [comment]
E' stato verificato che il comune di Piazzola sul Brenta ha risolto il problema in produzione inviano una mutazione 5008 con tipo 12 - matrimonio, seguita da una con tipo 21 - completamento con la quale ha inviato il divorzio
