### ISSUE TITLE
Controlli pre-subentro: anomalia su atti trasferiti di sede comunale

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#889]
Nella dashboard trovo la sintesi delle anomalie del pre-subentro comune di Paterno (codice 076100)
Anomalie sulla scheda anagrafica
Comune/provincia di registrazione atto di matrimonio @ inesistente  = 337
Comuni e stati esteri (atto di nascita)
Comune/provincia di registrazione atto di nascita @ inesistente o non valido alla data di registrazione = 1.150

Premessa: Prima del 1973 il comune di Marsico Nuovo aveva 8mila abitanti o più.
Molti abitavano nella frazione di Paterno dove c'era la delegazione di stato civile.

Dopo referendum e legge regionale, nasce il Comune di Paterno e un giudice decide di trasferire  i registri della delegazione di Paterno al nuovo Comune.
Tutti gli atti registrati in delegazione, sono quindi fisicamente a Paterno e non più in possesso di Marsico Nuovo. Meno le comunicazioni giunte ad esempio come nascite all'estero, che venivano registrate in comune e non in delegazione.
ANPR ora segnala su tutti gli atti prima del 1973 dove è indicato comune di registrazione Paterno, che il dato è sbagliato.

Il Comune potrebbe avere problemi nell'operatività sui cittadini con queste anomalie?

**Comment by gcarbonin** [comment]
A parte controllare cosa riporta uno degli atti segnalati come errati (dovrebbe essere Marsico Nuovo ufficio Paterno), questo dato non da problemi nei servizi a meno che non si vada a modificare proprio gli estremi degli atti segnalati come errati. Se oggi il comune provasse a iscrivere una persona con gli estremi dell'atto sbagliati non riuscirebbe a farlo; in questi casi la soluzione è quella che ho detto (indicare il comune corretto mettendo Paterno come ufficio, cosa che per altro rispecchia la realtà dei fatti).

**Comment by MarcoMigliori** [comment]
Ho fatto qualche prova e mentre come WA l'inserimento comune registrazione atto Paterno è bloccato (semplicemente perchè non è nella combo), come WS ce lo accetta senza anomalie. Anomalie presente invece sui cittadini subentrati. 
La soluzione proposta personalmente mi convince, ne parlo con il comune, grazie.
