### ISSUE TITLE
Web App  Indirizzo su Certificati 

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#89]
In data 29/02/2016 abbiamo segnalato tramite file excel inviato da CsiPiemonte la seguente anomalia a seguito di test sul nostro applicativo integrato con Web-service: "Soggetto  XXXX: sul certificato di residenza l'indirizzo è riportato scorrettamente "Corso Gamba n.23 Scala A piano 01 Interno 03" prima va riportato l'interno, poi la scala ed omettere il piano ". Tale segnalazione è stata da voi indicata come Change. 
Oggi abbiamo ripetuto questo test tramite Web Application (Data test 06/04/2017 – Ambiente presubentro (dppre) ) e questa modifica non è stata ancora effettuata, il formato è sempre non correttamente stampato. 
Altro esempio ID soggetto ANPR=3919240 residente in S. MARIA MAZZARELLO 96 bis int. 12 scala A piano 3 nui 9. Il certificato di residenza riporta:   S. MARIA MAZZARELLO 96 scala A Piano 3 Interno 12  => IL BIS è stato omesso , il Piano non dovrebbe essere stampato e l'Interno è riportato al fondo. 
In generale i campi INTERNO1, ESPINTERNO1, INTERNO2, ESPINTERNO2 dovrebbero essere presenti dopo l'ESPONENTE (bis, ter ..) e non dopo la SCALA, inoltre come già indicato il piano è una informazione non soggetta a certificazione. 
Grazie
Annamaria Gillone

**Comment by annamariaGillone** [comment]
Segnalo inoltre che in data 01/02/2016  avevamo già aperto una segnalazione relativa a "Tutti i certificati in cui è presente l'indirizzo di residenza" dove avevamo indicato genericamente "Non stampare il Piano, fermarsi alla scala" . 
Grazie  mille
Annamaria

**Comment by gcarbonin** [comment]
Abbiamo modificato la stampa per togliere il piano; lo potrà verificare da martedì.
Segnalo che l'esponente non viene stampato per  ID soggetto ANPR=3919240 in quanto assente in base dati; lo abbiamo inserito a mano per fare una prova e viene correttamente stampato. Fate qualche verifica sulla procedura di estrazione.
