### ISSUE TITLE
AIRE: Anno primo espatrio

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#890]
Buongiorno,

si chiede in base a quali considerazioni e' stato inserito in ANPR il controllo che l'anno di espatrio di un AIRE non sia precedente al 1970.
Infatti abbiamo rilevato che per gli AIRE subentrati o in pre-subentro che hanno questo dato precedente al 1970 se si va in mutazione dati web app si vede il campo vuoto.
In AnagAire non e' presente questa limitazione.

Grazie
Carla Musian
Insiel Mercato

**Comment by gcarbonin** [comment]
Si tratta di un'anomalia Avvertiamo quando possibile riprovare

**Comment by cmigliardi** [comment]
Grazie per la segnalazione, le faremo sapere quando riprovare.

**Comment by ncapozzi** [comment]
L'errore segnalato è stato corretto, potete riprovare.

Cordiali saluti
Nicoletta Capozzi
