### ISSUE TITLE
Errore 999

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#891]
Ambiente di TEST
id operazione Anpr: 17665287

Rettificando dei dati di un divorzio ci ritorna "Operazione non effettuabile"

Potete verificare? grazie

**Comment by asqueglia** [comment]
Buongiorno, abbiamo analizzato l'operazione effettuata. E' stato utilizzato un motivo di fine matrimonio non valido
<tipoCessazione>42</tipoCessazione>

Provvederemo, comunque, a gestire l'eccezione con un opportuno errore bloccante.
Grazie per la segnalzione.

**Comment by SAlberto** [comment]
Grazie a voi
