### ISSUE TITLE
Civico "ROSSO"

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#892]
Buongiorno. Nelle specifiche il campo "colore" è un codice numerico. Uno dei nostri comuni (come mi sembra di ricordare Firenze che è già subentrato) ha la numerazione ROSSO (codice anpr 1) riservata alle attività e distinta da quella nera delle abitazioni. Nel tempo cambia la destinazione d'uso per cui ci sono residenti ai civici ROSSO. Nella stessa via esiste 1 (nero), e 1 ROSSO che sono due civici distinti.
Simulando il caricamento in ANPR sfruttando il campo colore codificato, ho inserito  il seguente civico : 
     **8/B Rosso**
Questo è quello che normalmente vedo sulla targhetta esterna.
Nel certificato di residenza ottengo il seguente  risultato:
   **N. 8 - Lettera: B /1**
Che non mi sembra chiaro e può essere confuso con interni o altri significati.
Non è mai emersa la problematica?
PS: esempio caricato su ambiente test, comune 043043, id 16570107

**Comment by rvinzani** [comment]
Abbiamo preso in carico la sua segnalazione.
Le faremo sapere quando sarà rilasciata la modifica

**Comment by rvinzani** [comment]
Il campo colore viene adesso decodificato nella stampa dei certificati di residenza. La modifica effettuata è presente in tutti gli ambienti.
