### ISSUE TITLE
ws [5008] - Mutazione domicilio digitale, errore ES096 

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#896]
Buon giorno,
abbiamo ricevuto dal comune di Teramo, per cui stiamo conducendo i test, un documento in cui un cittadino dichiara il suo domicilio elettronico di posta certificata.
Nel documento è citato il Decreto Legge del 18.10.2012 n. 179, «Art. 3-bis (Domicilio digitale del cittadino). – 1. Al fine di facilitare la comunicazione tra pubbliche amministrazioni e cittadini, è facoltà di ogni cittadino indicare alla pubblica amministrazione, secondo le modalità stabilite al comma 3, un proprio indirizzo di posta elettronica certificata, quale suo domicilio digitale.
2. L'indirizzo di cui al comma 1 è inserito nell'Anagrafe nazionale della popolazione residente-ANPR e
reso disponibile a tutte le pubbliche amministrazioni e ai gestori o esercenti di pubblici servizi. (...) ».
Come da documentazione tecnica (cap 11.3.4), abbiamo pertanto utilizzato il servizio in oggetto (id operazione comune 5571) per comunicare la mutazione del domicilio digitale del cittadino, indicando il tipo mutazione '09' come da tabella 36, ma otteniamo in risposta l'errore "_ES096 - TipoMutazione 09 non valido per il servizio di mutazione dati della scheda (valori ammessi da 01 a 19, escluso 09)_" che in contraddizione al documento, sembra escludere la possibilità di effettuare tale mutazione.
Si tratta di una situazione temporanea? Come dobbiamo comportarci a seguito della comunicazione di altri documenti dello stesso tipo da parte degli Enti?
Il test è stato effettuato in data 24/10/2018, in ambiente di test, per il comune di Teramo.
Grazie, cordiali saluti.

Giuseppe Mucciarelli, TINN srl.

**Comment by gcarbonin** [comment]
La mutazione è bloccata in attesa di indicazioni da parte del Ministero. Chiederemo una verifica.

**Comment by gcarbonin** [comment]
faccio presente che l'art 3 - bis è stato modificato radicalmente

**Comment by Amucciarelli74** [comment]
Quanto scritto è riportato nel documento che ci ha trasmesso il comune, riferiremo in modo da consentire anche a loro eventuali approfondimenti e accertamenti.

**Comment by rvinzani** [comment]
Tutta la normativa sul domicilio digitale è in attesa di attuazione.

**Comment by rvinzani** [comment]
Chiudo la issue in quanto non necessario alcun intervento. In caso di richiesta di ulteriori chiarimenti si prega di aprire un'altra issue facendo riferimento a questa stessa
