### ISSUE TITLE
Unificazione anagrafiche AIRE da subentro

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#897]
Comune di Vinovo (TO)
Ambiente di produzione

Abbiamo riscontrato una situazione anomala su due cittadini AIRE presso questo Comune, subentrato in produzione quest'oggi.
L'anagrafica con codice ANPR 35097539 e l'anagrafica con codice ANPR 35097544 risultano essere in due famiglie separate (rispettivamente la famiglia ANPR 20040019 e 20000572) ma dovrebbero essere, a tutti gli effetti, nella stessa famiglia, come si evince dallo stesso numero di famiglia Ministeriale.
Abbiamo controllato il file di subentro degli aire prodotto dal programma ANAGAIRE e chiamato 001309_SUBAIRE_2.gz, senza riscontrare niente che ci abbia permesso di capire cosa sia successo.
Come possiamo intervenire per risolvere il problema e riportare le due anagrafiche nella stessa famiglia dalla data di subentro?
Grazie,
cordiali saluti.

**Comment by amollicone1982** [comment]
Al momento erano tutte e due nella famiglia con idanpr 20000572.
Successivamente  sul soggetto con idaAnpr 35097539 è stata eseguita un operazione con id 23630462 (A006 tipo mutazione 2 Modifica residenza, abitazione o indirizzo all’estero) che lo ha portato nella famiglia 20040019

**Comment by SAlberto** [comment]
Perfetto, mille grazie!
