### ISSUE TITLE
[5008] Completamento dati AIRE con matrimonio e divorzio

### ISSUE THREAD

**Issue by busaster** [italia/anpr#898]
Ambiente di produzione, comune di San Vito di Leguzzano.

Soggetto id ANPR 35069173, è un AIRE divorziato entrato in ANPR con il subentro.
Per questo motivo non ha in ANPR nessun dato di matrimonio ma solo il tipo divorzio "ALTRO TIPO DI CESSAZIONE/SCIOGLIMENTO", probabilmente inserito in automatico dalla procedura di subentro visto che nel tracciato ANAG-AIRE non è previsto questo campo.

Tentando di allineare il dato locale, dove sono presenti gli estremi evento matrimonio, il coniuge ed anche gli estremi completi di divorzio otteniamo l'errore  "Operazione richiesta non possibile. Non e' presente alcun matrimonio per il soggetto XXXXXXXX YYYYYYYYY corrispondente ai dati inseriti", dove ho mascherato i dati sensibili.
L'Id operazione ANPR è 23599516.

A cosa è dovuto questo blocco ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by ncapozzi** [comment]
Buonasera, 
come già da voi rilevato il problema si presenta per tutti i soggetti AIRE che sono arrivati da subentro con la cessazione o la vedovanza senza il matrimonio.
Quando si presenta la necessità di completare una di queste schede al momento è necessario eseguire la mutazione 5008 con tipo = 21 due volte, la prima inviando il matrimonio e la seconda la cessazione.

**Comment by AMonopoliADS** [comment]
mi associo alla richiesta di @busaster 
a mio parere la mutazione '21' dovrebbe "sanare" la scheda del soggetto in un'unica operazione.
se diventa necessario entrare nel merito delle singole posizioni, diventa difficile pensare ad un operazione massiva di allineamento tra db locale e ANPR.
grazie.

**Comment by MarcoMigliori** [comment]
Concordo con le richieste dei colleghi, grazie.
Marco Migliori
PAL Informatica

**Comment by ncapozzi** [comment]
Buongiorno,
una operazione massiva di allineamento delle schede AIRE tra db locale e ANPR non è richiesta dalla norma.
Qualora il Comune debba movimentare una scheda successivamente al subentro può procedere al completamento puntuale dei dati. Al momento non sono previste modifiche del controllo 

Cordiali saluti
Nicoletta Capozzi

**Comment by AMonopoliADS** [comment]
faccio un esempio di due situazioni che si verificano quando il comune movimenta una scheda AIRE:

1. il comune non procede immediatamente con la mutazione 'x'.
interroga l'ANPR, vede che la scheda è incompleta, invia la mutazione di tipo '21', il soggetto è divorziato, scatta l'errore! deve mandare solo il matrimonio. [chiama la sw house - opzionale] trova il modo di inviare il matrimonio... manda la mutazione '21' di completamento dati... invia la mutazione 'x'

oppure 

2. il comune procede direttamente la mutazione 'x'.
interroga l'ANPR, si accorge che la scheda era parziale... annulla la mutazione 'x'
se va bene, siamo nell'ambito di una mutazione che può essere annullata... da qui partono tutte le operazioni di cui al punto '1'.
se la mutazione non può essere annullata, la scheda rimarrà parziale...

questo solo per dare un'idea di quello che succede nella pratica (nella peggiore delle ipotesi...)

richiesto o meno dalla norma, un aggiornamento massivo degli AIRE subito dopo il subentro risolverebbe svariati ostacoli e perdite di tempo nell'ambito delle pratiche e mutazioni AIRE.

personalmente, rinnovo la richiesta di "alleggerire" il controllo di cui si è discusso, chiedendovi di tenerne conto in una delle prossime evoluzioni.

grazie.
Aalessandro Monopoli ADS

**Comment by busaster** [comment]
concordo al 100% con @AMonopoliADS

**Comment by bfilipazzi** [comment]
Non cvi sono stati ulteriori commenti e la issue non ha etichette.
E' possibile avere una dichiarazione al riguardo?
Grazie.
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Buongiorno,
si conferma che per tutti i soggetti AIRE che sono arrivati da subentro con la cessazione o la vedovanza senza il matrimonio, quando si presenta la necessità di completare la scheda al momento è necessario eseguire la mutazione 5008 con tipo = 21 due volte, la prima inviando il matrimonio e la seconda la cessazione.
E' comunque previsto un intervento di revisione nelle prossime evoluzioni.
N. Capozzi

**Comment by bfilipazzi** [comment]
Si parlava di "prossime" evoluzioni.
Sono trascorsi 5 mesi, posso chiedere una data di previsione?
Grazie.
Filipazzi - Maggioli

**Comment by ncapozzi** [comment]
Buonasera,
l'intervento di revisione dei dati matrimonio (non solo per i soggetti AIRE) resta tuttora da definire essendo stata data priorità ad altri interventi evolutivi.

N. Capozzi
