### ISSUE TITLE
Migrazione ISP

### ISSUE THREAD

**Issue by sisteminformativi** [italia/anpr#899]
Buonasera.

Siamo passati alla fibra ottica di TIM.
Attualmente stiamo ancora navigando però con ADSL di Fastweb per quanto riguarda ANPR.
Cosa possiamo fare per migrare anche il Server ANPR sulla nuova linea in Fibra?
Dato che anche l'indirizzo ip pubblico è cambiato.

grazie.

**Comment by cmigliardi** [comment]
Per colloquiare con Anpr, occorre richiedere l'abilitazione dell' IP pubblico statico esposto verso i servizi di ANPR.

**Comment by sisteminformativi** [comment]
Buongiorno. Non so se abbiamo fatto correttamente. Abbiamo inserito il nuovo indirizzo ip statico nell'anagrafica del Comune di Biassono. Sostituendolo a quello precedente. Ora però abbiamo problemi di connessione. Si tratta solo di aspettare oppure dobbiamo fare altro? Grazie.
