### ISSUE TITLE
Servizio 5008 Mutazione DatiGeneraliStatoCivile

### ISSUE THREAD

**Issue by mccalv** [italia/anpr#9]
Per la rettifica cognome/nome/sesso o cittadinanza, non per errore ma per documentazione, è previsto di poter riportare il motivo/estremi della legge secondo i quali è stata effettuata la variazione? Ad es. Rettifica cognome/nome per disconoscimento oppure Acquisto cittadinanza italiana ""ope legis""."

**Comment by gcarbonin** [comment]
No suppongo perché si tratta di informazioni di competenza dello stato civile
