### ISSUE TITLE
Web App - Apertura contestuale di più procedimenti sullo stesso soggetto

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#90]
6/4/2017 - Ambiente dptest
Abbiamo iscritto per “Iscrizione per altri motivi” da Comune non subentrato il soggetto con Id ANPR: 4378773, Numero procedimento assegnato da ANPR: 3388.
Lasciando il procedimento in stato “Apertura” abbiamo provato ad aprire un secondo procedimento per “Mutazione famiglia/convivenza” ed è stato possibile (Operazione n.  452780, Numero procedimento assegnato da ANPR: 3389). Abbiamo anche potuto procedere alla mutazione dell’indirizzo della famiglia con operazione 452797.
Dal momento che il primo procedimento mancava ancora sia della fase di acquisizione dati sia del completamento dell’istruttoria (accertamento all’indirizzo), non riteniamo corretto che il sistema consenta di aprire un secondo procedimento e una seconda mutazione.
Grazie.
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino

**Comment by gcarbonin** [comment]
Se la parte presenta una dichiarazione per un cambio di domicilio quando la prima istruttoria è in corso, si dovrebbe dire di ripassare dopo 45 gg?

**Comment by VBocchinoTO** [comment]
La nuova istanza del cittadino può essere accolta anche a procedimento non concluso, ma occorre che l'operatore di anagrafe ne abbia evidenza per poter comunque chiudere il primo preliminarmente oppure gestirli contestualmente, a seconda della fase procedurale in cui si trovano (accertamento già avvenuto oppure no, eventuale preavviso di rigetto già inviato, ecc.)
Occorrerebbe poter quanto meno vedere tutti i procedimenti aperti sul singolo soggetto/famiglia e/o avere degli alert che consentano la valutazione preliminare della situazione.
Certamente i piccoli comuni hanno un'incidenza molto bassa di variazioni anagrafiche all'interno del comune, mentre i grandi hanno una mobilità intensa, anche immediatamente dopo l'iscrizione (da situazione alloggiativa provvisoria ad altra dimora idonea).
Grazie.
Ileana Macagno, Valentina Bocchino, Pier Dario Brigandì

**Comment by gcarbonin** [comment]
Quindi dobbiamo pensare di aggiungere un warning "esiste gia' un procedimento aperto per la stessa persona"?

**Comment by VBocchinoTO** [comment]
Secondo il nostro parere, fino a quando verranno utilizzati i gestionali integrati tramite web services,  potrebbe essere sufficiente in quanto solitamente il controllo viene fatto a monte dal gestionale e conseguentemente il caso non dovrebbe verificarsi, salve le dovute eccezioni.
Questa modifica diventerebbe invece indispensabile nel caso si decidesse di passare ad un utilizzo esclusivo della web app. In questo caso sarebbe però necessario che venisse reso possibile identificare anche quali sono i procedimenti in corso tramite la consultazione della scheda del soggetto/famiglia,  (come richiesto nell'issue #94) o tramite un'apposita consultazione dello stato del procedimento (richiesto nell'issue #92) .  Al momento infatti, tramite web app, non abbiamo ancora compreso completamente come individuare un procedimento a carico di un cittadino e il suo stato attuale.
Grazie.
Valentina Bocchino, Pier Dario Brigandì, Ileana Macagno - Comune di Torino
