### ISSUE TITLE
Certificato Postazione Utente

### ISSUE THREAD

**Issue by sisteminformativi** [italia/anpr#900]
Buonasera.

Ho creato un profilo utente nuovo, su un PC di un utente che già utilizzava ANPR, ma che adesso non lavora più quì.
Posso utilizzare sempre lo stesso certificato di postazione, oppure ne devo richiedere uno nuovo per il nuovo dipendente?

Grazie.

**Comment by gcarbonin** [comment]
si può usare il certificato già installato sul PC
