### ISSUE TITLE
Errore certificato di postazione

### ISSUE THREAD

**Issue by sisteminformativi** [italia/anpr#901]
Buonasera.
Da circa una settimana, su tutti i pc dell'anagrafe esce un errore sul browser Internet Explorer, riguardante la validità del certificato ANPR.
Il messaggio parla di "INVALID DATE". Ho controllato e la data di scadenza è del 2023!!!
Com'é possibile che ad un certo punto tutti i pc dell'anagrafe abbiano questo problema?

grazie.

**Comment by Leonforte** [comment]
Ha controllato la data e l'ora di sistema impostata sui PC ?

**Comment by sisteminformativi** [comment]
Si. E' corretta su tutti e tre i PC

**Comment by Leonforte** [comment]
Ci può fornire il CN dei certificati in questione ?

**Comment by sisteminformativi** [comment]
Buongiorno. Da parte nostra (Localmente) non abbiamo modificato niente a livello di Firewall. Abbiamo soltanto fatto una migrazione ISP da ADSL Fastweb con indirizzo IP Pubblico (89.96.213.130) a TIM Fibra con un nuovo indirizzo IP Pubblico (195.223.26.174).
Tale indirizzo IP di TIM è già stato abilitato da parte vs, settimana scorsa, per poter accedere ai servizi ANPR.

**Comment by Leonforte** [comment]
Buongiorno,
abbiamo verificato e l'indirizzo 195.223.26.174 risulta abilitato lato ws per il Comune di Biassono.
Non so cosa aggiungere se non allegare una breve guida per le verifiche del caso, 

[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/2576062/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)
