### ISSUE TITLE
AIRE: carattere # cancelletto negli indirizzi esteri

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#902]
Buongiorno,

I comuni ci segnalano, in parecchi casi, la presenza del  carattere # negli indirizzi degli AIRE.
Questi indirizzi sono stai comunicati cosi' dai consolati.

Nella numerazione dei civici negli USA il # viene utilizzato per indicare l'interno cioe' il numero
dell'appartamento. Si veda:
https://www.wikihow.com/Write-an-Apartment-Address dove indica come scrivere un indirizzo:
.......
"Add the apartment or suite number on the same line as the street name. 
Include the apartment number on the same line as the street address with the abbreviation "#," "unit," or "apt." 
(Make sure there is a space between # and the apt. number.) 
You might write, for example, "123 Main Street # 204."

Si chiede che venga aggiunto come carattere valido nella localitaEstera parte toponimo, sia nella denominazione che nel numero civico estero perche' non sempre questi 2 campi risultano suddivisi correttamente.
Grazie

Carla Musian
Insiel Mercato

**Comment by mttfranci** [comment]
Stiamo valutando la segnalazione

**Comment by mttfranci** [comment]
Nel corso della prossima settimana Verranno accettati il carattere "/" per l'elemento descrizioneLocalita del tipo Località e il carattere "#" per gli elementi denominazione e numeroCivico del tipoToponimoEstero (riferimento issue #902 e 907)
E’ possibile verificare il change log per verificare quando la modifica sarà effettivamente rilasciata : 
https://docs.italia.it/italia/anpr/anpr/it/bozza/change-management/changelog.html

**Comment by mttfranci** [comment]
L'implementazione richiesta dovrebbe essere disponibile in test comuni / presubentro / produzione
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

**Comment by mttfranci** [comment]
@CarlaMusian : Salve, ora riuscite ad operare?

**Comment by CarlaMusian** [comment]
Ho provato in test ad inserire una nuova famiglia e nuovo indirizzo AIRE ma mi ha dato
un errore come sotto.
Togliendo poi il cancelletto ha funzionato.

… ho provato nell’ambiente di test.  Anche nell’ambiente di pre subentro la stessa cosa da’ lo stesso errore
Saluti
Carla Musian

[cid:image001.png@01D480D8.D740DAB0]

[cid:image002.png@01D480D8.D740DAB0]


[cid:image003.png@01D480D9.7F51E8C0]
Dott.ssa Carla Musian
Direzione Area Pubblica Amministrazione
Fax. 040 634623
e-mail: Carla.Musian@gpi.it<mailto:Carla.Musian@gpi.it>

Gruppo GPI
I - 38123 Trento | Via Ragazzi del '99, 13 | T. +39 0461 381 515 ! F. +39 0461 381 599
www.gpi.it<http://www.gpi.it/>

ATTENZIONE: Le informazioni contenute nella presente pagina e nei relativi allegati possono essere riservate e sono destinate esclusivamente al suindicato destinatario. La diffusione, la distribuzione e/o la copiatura del presente documento, dei suoi allegati o di sue parti da parte di qualsiasi soggetto divedrso dal destinatario è proibita, sia ai sensi dell'art. 616 c.p. che ai sensi del GDPR 679/2016. Se avete ricevuto questo messaggio per errore, vi preghiamo di eliminarlo e di informarci inviando un e-mail a: info@gpi.it<mailto:info@gpi.it>. L'inofmrativa privacy ai sensi dell'art. 13 del GDPR 679/2016 è disponibile sul sito www.gpi.it<http://www.gpi.it/>
Rispetta l'ambiente. Non stampare questa mail se non è necessario.

Da: Matteo [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 11.58
A: italia/anpr
Cc: Musian Carla; Mention
Oggetto: Re: [italia/anpr] AIRE: carattere # cancelletto negli indirizzi esteri (#902)


@CarlaMusian<https://github.com/CarlaMusian> : Salve, ora riuscite ad operare?

**Comment by mttfranci** [comment]
Salve, non siamo riusciti a visualizzare le immagini. Le abbiamo scritto per email all'indirizzo nella sua firma.

**Comment by CarlaMusian** [comment]
Ho fatto le prove su web app - iscrizione per altri motivi AIRE, operazione d'ufficio , sia ambiente di test che pre-subentro, e nel salvataggio finale mi compaiono gli errori:
- la richiesta non risulta valida secondo i nuovi xsd campo denominazione EN489
- la richiesta non risulta valida secondo i nuovi xsd numero errori trovati 1 EN489

Se poi tolgo il cancelletto nell'indirizzo viene accettato tutto.
Nel toponimo dell'ndirizzo AIRE avevo scritto:
"da numero 3 #1"

Grazie
Carla Musian

**Comment by mttfranci** [comment]
Salve, dovremmo aver individuato l'origine del comportamento. Potete riprovare?

**Comment by CarlaMusian** [comment]
Ho rifatto la stessa prova e funziona come stabilito.
Quando verra' messo in line aper i subentri?
Grazie

**Comment by mttfranci** [comment]
L'aggiornamento è già disponibile in tutti gli ambienti
