### ISSUE TITLE
Aggiornamento versione 4.1.10 ANPR - Revisione restrizioni XSD / Filtro per comune residenza / Gestione diacritici

### ISSUE THREAD

**Issue by mttfranci** [italia/anpr#903]
Da domani sarà disponibile in test comuni / presubentro / produzione la versione 4.0.10 ANPR.

Ecco le principali caratteristiche incluse.
[note_rilascio_4_1_10.zip](https://github.com/italia/anpr/files/2516057/note_rilascio_4_1_10.zip)

1) Revisioni restrizioni XSD (sono stati solo rilassati alcuni vincoli)
[Vedi anche issue #819 e #617, i wsdl aggiornati nelle note di rilascio]
Dopo una analisi dei valori fino a qui acquisiti sugli oltre 10 milioni di soggetti attualmente presenti in ANPR, alcuni tipi sono stati resi meno restrittivi.
Questo al fine di minimizzare l'impatto per i valori già presenti in base dati, in particolare : 
* La maggior parte dei campi note sono stati resi uguali e ora accettano anche diacritici, punto e virgola, due punti, virgolette.
* Il numero sentenza accetta anche il punto e il trattino
* Il numero permesso di soggiorno accetta anche il trattino
* La frazione accetta anche i diacritici, due punti, punto e virgola, virgolette, parentesi tonte.

2) Filtro per comune di residenza
[Vedi anche issue #565 e #576]
E' stata implementata la possibilità di filtrare per comune di residenza nel servizio di consultazione 3002.
A breve seguirà tale possibilità anche per l'applicazione web.

3) Modificate restrizioni per accettare alcuni diacritici che non venivano interpretati.
[Vedi anche issue #861]
Le espressioni regolari per i diacritici ora accettano questi valori : 
~~~~ 
&#73;&#105;&#138;&#140;&#142;&#154;&#156;&#158;-&#159;&#192;-&#382;&#393; 
~~~~

NOTA: sono stati aggiornati anche il tool di preverifica del subentro e il tool di esempio di validazione degli XML disponibili nell'area "Strumenti di supporto" dell'ambiente di test comuni.

**Comment by pissardl** [comment]
Esiste un ipotetica data o mese di rilascio in Produzione della 4.1.10 ?

**Comment by mttfranci** [comment]
e' in produzione da oggi.
