### ISSUE TITLE
ANNULLAMENTO MATRIMONIO

### ISSUE THREAD

**Issue by subentrati** [italia/anpr#905]
Buongiorno siamo un Comune subentarto in ANPR il 19/09/2018:
il cittadino è subentrato come divorziato (anno 1983) e per errore materiale nella scheda ANPR risulta anche il matrimonio ( completamente errato: coniuge e data). Il cittadino è residente nel nostro Comune dal 2015.
Ora nella mia banca dati locale ho annullato il matrimonio ma non riesco a fare nulla in ANPR in quanto l'operazione di anullamento del matrimonio non sembrerebbe ancora gestita.
Non è possibile neanche procedere a modificare dati matrimonio su web app inquanto precedente all'iscrizione.
Che fare???

SERVIZI DEMOGRAFICI - COMUE DI CESATE
Il Responsabile
Cristina Pellegrinelli

**Comment by frmariani** [comment]
mi può indicare l'idanpr del soggetto per favore ?

**Comment by frmariani** [comment]
in mancanza di ulteriori informazioni, posso genericamente informare che le modifiche del coniuge e della data dell'evento sono possibili in due operazioni distinte.
