### ISSUE TITLE
[6001] Stato di Famiglia: errore EN222, senza errori in consultazione

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#906]
ambiente di PRODUZIONE - comune di Poggibonsi (SI)

idSoggettoANPR: 27175888
la richiesta di stato di famiglia ritorna l'errore
```
<errore>
  <codiceErroreAnomalia>EN222</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>I certificati di stato di famiglia,  stato di famiglia per convivenza, stato di famiglia con rapporti di parentela, stato di famiglia e di stato civile non possono essere emessi perche' la famiglia risulta non certificabile</testoErroreAnomalia>
</errore>
```

normalmente, consultando la scheda di famiglia (ws 3002), l'errore che blocca la certificazione viene evidenziato anche in risposta a questo web-service.
in questo caso, invece, sui soggetti non compare nessun errore (es. idOperazioneComune 2018301999)

è cambiato qualcosa in questo senso?
oppure è un caso particolare da approfondire?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
stessa situazione si verifica, sempre in ambiente di PRODUZIONE, nel comune di Occhiobello (RO)
(rif. idSoggettoANPR 32561060)

è possibile avere un riscontro?

grazie.

**Comment by frmariani** [comment]
l’interrogazione in precedenza non era consentita e abbiamo sbloccato la situazione (vedi issue 576). Stiamo aggiungendo un controllo per inserire la segnalazione NON BLOCCANTE in consultazione della famiglia

**Comment by AMonopoliADS** [comment]
preciso (in rif. alla issue 576) che l'interrogazione non era consentita se effettuata da un comune diverso da quello di residenza. 
mentre, l'interrogazione eseguita dal comune di residenza, otteneva come risultato anche l'anomalia parlante  relativa alla certificazione non consentita... anomalia che oggi non stiamo più vedendo, per essendo la certificazione bloccata.
(per questo ho aperto la segnalazione)

**Comment by frmariani** [comment]
ringrazio per la segnalazione e per la precisazione;  abbiamo sbloccato la situazione anche per consentire ai comuni diversi da quelli di residenza di poter effettuare la preventiva e necessaria consultazione nelle operazioni di cambio di residenza;

**Comment by AMonopoliADS** [comment]
vedo che la issue è stata chiusa, ma non ho capito se è stato ripristinato l'errore in consultazione della scheda di famiglia...

**Comment by frmariani** [comment]
no, il controllo non verrà ripristinato
