### ISSUE TITLE
XSD: Carattere slash "/" nella località di nascita estera

### ISSUE THREAD

**Issue by cpagnani** [italia/anpr#907]
_Originally posted by @gcarbonin in https://github.com/italia/anpr/issues/768#issuecomment-426965937_
Contrariamente a quanto affermato con la chiusura della issue "XSD aggiornati e carattere "/" nelle località estere #768", lo slash "/" nella località di nascita estera ad oggi non risulta più accettato, mentre lo era stato per un certo periodo.
Precisamente nel wsdl-pack-comuni-release-3.6.0_no_datapower.rar (https://webpre.anpr.interno.it/ANPRWEB/gestioneAvvisiComuni.do?method=downloadAllegatoAvviso&idAlleg=2000062) allegato alla notizia del "29-03-2018: Controlli campi input" e nel https://github.com/italia/anpr/files/1860129/wsdl-pack-comuni-dist.zip in "Aggiornamento sistemi di test comuni e presubentro #617" era stato inserito il carattere "/" nel tipo alfanumericobase (rendendolo di fatto identico a alfanumericoslashbase), per essere poi rimosso nell'aggiornamento https://github.com/italia/anpr/files/1872190/update_01.zip in https://github.com/italia/anpr/issues/617#issuecomment-378291966
Sarebbe più corretto se il campo "descrizioneLocalita" del tipo dato "tipoLocalita" (intesa sempre come estera, in alternativa a "tipoComune") fosse definito "alfanumericoslash120char", analogamente a quello in "tipoDatoLocalitaEstera", anziché "alfanumerico120char".
Claudio Pagnani
Datamanagement Italia

**Comment by mttfranci** [comment]
Ci scusiamo per l'imprecisione nella pubblicazione precedente.
La versione attualmente rilasciata (pubblicata il 25 ottobre, #903) accetta il carattere "/" per il toponimo e la località estere come previsto.

Per la nota sulla descrizioneLocalita di nascita, avete dei casi specifici in cui è necessario tale carattere?
(La sezione cui fate riferimento non è un indirizzo, quindi gli altri caratteri dovrebbero essere sufficienti).

**Comment by cpagnani** [comment]
Come era già stato evidenziato in apertura della https://github.com/italia/anpr/issues/253, per i comuni del Brasile dopo la denominazione è spesso presente la sigla dello stato (nel nostro caso ITABUNA/BA).

Rinnovo la richiesta a prevedere  il carattere "/" anche sulla descrizioneLocalita di nascita, poiché moltissimi passaporti indicano il luogo di nascita con "/" e inserire un carattere diverso dalla "/", es "-", in fase di immigrazione di straniero dall'estero, significa inserire dei dati in modo difforme dal documento originale.

**Comment by mttfranci** [comment]
Nel corso della prossima settimana Verranno accettati il carattere "/" per l'elemento descrizioneLocalita del tipo Località e il carattere "#" per gli elementi denominazione e numeroCivico del tipoToponimoEstero (riferimento issue #902 e 907)
E’ possibile verificare il change log per verificare quando la modifica sarà effettivamente rilasciata : 
https://docs.italia.it/italia/anpr/anpr/it/bozza/change-management/changelog.html

**Comment by mttfranci** [comment]
L'implementazione richiesta dovrebbe essere disponibile in test comuni / presubentro / produzione
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md

**Comment by mttfranci** [comment]
@cpagnani : Salve, ora riuscite ad operare?
