### ISSUE TITLE
Comune non esistente alla data di nascita

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#909]
Pratica di immigrazione da comune non subentrato. 
Il cittadino è nato nel 1934 nel comune di Poggiorsini (BA), comune istituito solo nel 1957.
In precedenza era frazione di Gravina in Puglia, ma con registri di stato civile distinti
Ha tutti i documenti compreso il codice fiscale con comune di nascita Poggiorsini.
Come bisogna gestirlo?
Grazie.

**Comment by gcarbonin** [comment]
L'atto di nascita se fosse corretto dovrebbe riportare "nato a Gravina di Puglia" e come ufficio di registrazione dell'atto Poggiorsini.
Deduco dalle sue indicazioni che non è così.
Dal momento che il codice fiscale riporta Poggiorsini, l'iscrizione dovrebbe essere possibile (non da web application). Mi faccia sapere se ha problemi.

**Comment by Finalmentesubentrati** [comment]
Ho risolto. Grazie.

**Comment by cvignati** [comment]
> 
> 
> Ho risolto. Grazie.

Scusi, può spiegare come ha risolto.
Grazie
