### ISSUE TITLE
Web app Registrazione/Mutazione tutti i dati Permesso di soggiorno ad Italiano

### ISSUE THREAD

**Issue by annamariaGillone** [italia/anpr#91]
Data test 04/04/2017 - Ambiente test (dptest)
Per il soggetto ID ANPR 4225547 inserito permesso di soggiorno stante sia italiano.
 Il sistema non ha segnalato errori.

Grazie
Stefania Amprimo, Silvia Floramo, Liliana Guarraia - Comune di Torino

**Comment by gcarbonin** [comment]
Provvediamo a sistemare

**Comment by gcarbonin** [comment]
La situazione dovrebbe essere a posto da fine agosto potete riprovare
