### ISSUE TITLE
Impossibile accedere a https://dp.anpr.interno.it/com

### ISSUE THREAD

**Issue by SedicoCED** [italia/anpr#910]
Stiamo certificando le postazioni del ns comune per l'accesso a anpr.
In una non si riesce ad accedere al sito https://dp.anpr.interno.it/com
e neanche a scaricare Certificati & Chiavi dal Manager del IDProtect
Ho provato già fatto i seguenti tentativi:
- reinstallato i driver della smart card
- disattivato antivirus e firewall di windows
- provato con browser diversi (IE, Chrome, Firefox)
Con il browser Firefox, dopo lunga attesa, viene visualizzata una pagina con questo errore:
"Connessione sicura non riuscita
Si è verificato un errore durante la connessione a dp2.anpr.interno.it. Il peer SSL non è stato in grado di negoziare un insieme di parametri di sicurezza accettabile. Codice di errore: SSL_ERROR_HANDSHAKE_FAILURE_ALERT"
Attivando il log in IDProtect, quando viene lanciata l'azione di download dei Certificati & Chiavi, viene sempre riportata un'eccezione di questo tipo
d = 31 t = 10:16:35:806 PID = f0c TID = f70
 ***** ckExcept - code = 8

Sembra che sia un problema di accesso e download dei certificati ma non saprei più cosa disattivare.

**Comment by gife67** [comment]
Il problema è dovuto all'utilizzo del certificato della smartcard per l'accesso al sito. Dal momento che non riuscite ad accedere con nessun browser, è molto probabile che ci sia un problema nell'installazione dei driver del lettore della smartcard, combinato con il driver della smartcard ANPR. 
Le postazioni quale SO Windows hanno?

**Comment by SedicoCED** [comment]
Ho risolto proprio oggi in questo modo:
cambiato porta USB al lettore e reinstallato i driver di quest'ultimo.
Grazie

**Comment by gife67** [comment]
Perfetto. Grazie
