### ISSUE TITLE
[N000] ANPR configurazione servizio di notifica

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#912]
Buongiorno,
qualcuno mi può dare informazioni su come configurare WCF per il servizio di ricezione delle notifiche da parte di ANPR.
In quanto pur avendo creato il servizio e pubblicato  provando a contattarlo con la funzione "Invia Notifica di test " dall'ambiente di test ottengo sempre lo stesso esito "2 - Errore nell'invio della notifica di test".

**Comment by gife67** [comment]
Cortesemente potete fornirmi il codice ISTAT del Comune con cui state effettuando il test della notifica, così da poter indagare sull'errore che state riscontrando.
Grazie

**Comment by Antonino09** [comment]
Certamente il codice ISTAT è il seguente 888111.
Grazie

**Comment by gife67** [comment]
Cortesemente potete riprovare ad effettuare l'invio di Test?

**Comment by gife67** [comment]
Mi confermate che state utilizzando l'ambiente dedicato alle software house non ancora accreditate (https://dpfree.anpr.interno.it/combas)?

**Comment by gife67** [comment]
La procedura è gestita dal Team Digitale e dovrebbe chiedere dettagli direttamente a loro.
Ho verificato che ha effettuato un nuovo test alle 17:18, in cui abbiamo inviato al vostro endpoint 
**https://anpr.golemsoftware.it/WcfService1/N00servizioNotifiche.svc**
il messaggio in fondo.
Nell'invio abbiamo riscontrato un Connection timed out, se cortesemente potete verificare lo stato del vostro endpoint.

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header/>
  <soapenv:Body>
    <ns2:RichiestaN000 xmlns:ns2="http://sogei.it/ANPR/N000AnprService">
      <testataNotifica>
        <tipoNotifica>N031</tipoNotifica>
        <codMittente>999999</codMittente>
        <codDestinatario>888111</codDestinatario>
        <dataOraRichiesta>2018-11-07T17:18:46.904+01:00</dataOraRichiesta>
        <idOperazioneANPR>999999</idOperazioneANPR>
      </testataNotifica>
      <contenuto>MIAGCSqGSIb3DQEHA6CAMIACAQAxggGCMIIBfgIBADBmMFoxGzAZBgNVBAMMEkNBIFBvc3RhemlvbmkgU3ZpbDENMAsGA1UECwwEQU5QUjEfMB0GA1UECgwWTWluaXN0ZXJvIGRlbGwnSW50ZXJubzELMAkGA1UEBhMCSVQCCGfpB7pcOaZYMA0GCSqGSIb3DQEBAQUABIIBAAFOL7Ps6cdxD9wSKnf+VcH2yloGoAUgJ/NsB837Ek68E2jU8ANhdVeCPDMRRH6Bg6NLVKTzul+ElKi+EMpPDfKljUd717h4lwZ3dmj/JkHAhTDN0Q2jTP+SgPOD0tt8yrqj7ho29JH3QVVSGxS5Nsa4Ej2TvR2JnFlGlnVGY3LzfZzZZATkSDXzH1Y+7EdX7REL1+qU6YBpcwd4apJuJd4aE75zeEjup+2+5dLlz7ctQzv67Qm7hmxRdUnbK2PZcJ9ZaYYBsdW4rWsmFzHwSu2pPf69RnhNamwuNPcKUFIoHn40vY4f5Quw3GD3wSVdkpJ+m1aIGzv1wSRY7wNhJZQwgAYJKoZIhvcNAQcBMB0GCWCGSAFlAwQBKgQQCyMKqBPvFaHmlXqxMJPPkKCABIICMByEwFMFGJ0zfiEexjh5aRBQyamhoz7xiYtsuR2Nq3ZjRqJSgVKsmWlNY3h7jcTLDH9KPSFZYrGg9uHgueqv7klUWPEDNuqtQ6UjNMKpwxBLJiCm+LSr1BHE8BqIrpPOybDNmzSOm5MRnsZZ8DD+qg+4G0IurkZI+K/Pe7OqU4C9zkmNlue/Dlyfs6FEsHMCdJ3F3TjWQk4r1ildmmfiEj+N5FqsLJQQ5djaYELIHPvGWMhMNB4aIESkIqFU/hTiLgudPE33M0pwfIeMyLNkrX7JfnG71HqhyYuPKQuuUOrvFTaqL1gvt20unHpd1drcScprvkxwDzReoIdZqkf3hQbg0O6c/xbq6CYq3o+oCvodRxJrM+mDElIq9xyfSq4b9wOlABJMhO+dD97ym9dhLYJf+ARZJOdHZ4e++snHMoYWTRF3Y64Yb9mhLH8JTVW1xjh6yrmNsQ5nIhhKWQiCX+uTrksrfOhIjteoq9+9SVsoOxuqqIj+Qf69giRJN+NvwfbwVnUAL8vbixMSwEYfAOwAWUEZxf8iR3M6/LKJB0L3m63v8wEXI63r8nLUipdQ55w9CgXLowmAivB4uoaYwHYN8h2dY4oFg1MTKUi0mId7m6pc8h9PMhOG1dZDvCRCNlM6K5RrU1DHXH372losZMavCLRDyIyVlewL9r2QGSW/l9nGP6YdKuhPKEceEad2DAI+jglC2RctPeRAmVoZGpuZYxw64ZczQcQMmOEz9qY3AAAAAAAAAAAAAA==</contenuto>
    </ns2:RichiestaN000>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by gife67** [comment]
Scusate ma il formato del messaggio inviato è stato alterato dal MD di GitHub, ve lo rinvio come allegato
[notifica_test-888111.txt](https://github.com/italia/anpr/files/2558321/notifica_test-888111.txt)

**Comment by gife67** [comment]
aggiungo che tutto il messaggio allegato vi viene inoltrato firmato con XML-Signature

**Comment by Antonino09** [comment]
La ringrazio adesso provo a a fare qualche verifica per capire quale sia il problema.

**Comment by Antonino09** [comment]
Ho fatto alcuni test ma continuo a ricevere Connection timed out, anche se il servizio è raggiungibile.

**Comment by gife67** [comment]
Credo di aver individuato il problema. Domani provvedo ad effettuare delle verifiche e vi faccio sapere quando riprovare.

**Comment by Antonino09** [comment]
Buongiorno,
ha avuto modo di effettuare le verifiche.

**Comment by gife67** [comment]
Buongiorno,
stiamo effettuando delle verifiche su questo ambiente, appena completate le chiederò di riprovare.
Grazie

**Comment by gife67** [comment]
Buonasera, 
volevo comunicarle che stiamo rivendendo delle configurazioni sistemistiche per questo ambiente. La contatterò Lunedì per riprovare. 
Grazie

**Comment by Antonino09** [comment]
La ringrazio, a lunedì.

**Comment by gife67** [comment]
Buongiorno, cortesemente può riprovare

**Comment by Antonino09** [comment]
Buongiorno, si certamente adesso provo.

**Comment by Antonino09** [comment]
Ho effettuato due prove di invio notifica ma  ricevo  esito: "2 -Errore nell'invio della notifica di test"

**Comment by gife67** [comment]
Se può riprovare, ora dovrebbe ricevere il messaggio.

**Comment by Antonino09** [comment]
Continuo a ricevere il messaggio "2 -Errore nell'invio della notifica di test" quando provo ad inviare la notifica

**Comment by gife67** [comment]
Si l'errore c'è sempre ma dovrebbe essere cambiato qualcosa. Dagli errori interni che vedo ora il messaggio dovrebbe essere stato inoltrato verso il vostro endpoint.

**Comment by Antonino09** [comment]
Si effettivamente sembra mi sia arrivato il messaggio, provo a fare qualche verifica per capire il problema.

**Comment by gife67** [comment]
Grazie a lei per la disponibilità e la pazienza.

**Comment by Antonino09** [comment]
Mi scusi mi ero dimenticato di chiederle dove posso recuperare il certificato di verifica della firma della notifica dato che da il mio ambiente non permette di scaricarlo.
Grazie

**Comment by gife67** [comment]
Li può trovare pubblicati sul portale ANPR a questa URL https://www.anpr.interno.it/portale/documentazione-tecnica
al link "Certificato CA ANPR produzione"
Comunque gli allego lo zip.
[CA.ZIP.zip](https://github.com/italia/anpr/files/2576582/CA.ZIP.zip)

**Comment by Antonino09** [comment]
Come mai sono due i certificati ?

**Comment by gife67** [comment]
Ci sono 2 CA ANPR, una per l'emissione dei certificati di Postazione ed una per i certificati utente emessi per l'accesso con smartcard, questo per permettere un accesso fatto di un doppio step all'applicazione web in ambiente di Produzione. Per quanto riguarda la verifica del XML Signature del messaggio di notifica le occorre solo quello della CA Utenti.
Le allego tutta la catene di certificati utilizzata nella firma.
[FirmaNotifiche.zip](https://github.com/italia/anpr/files/2576743/FirmaNotifiche.zip)

**Comment by Antonino09** [comment]
Buongiorno,
sto avendo qualche problema a decifrare il contenuto della notifica, vorrei chiederle se effettivamente il metodo che è stato usato per la cifratura  è AES256-CBC con la chiave pubblica del certificato (nnnnnn-CO-9999) e se per decifrare il messaggio debba usare la chiave privata dello stesso certificato.
Grazie

**Comment by gife67** [comment]
Buonasera, si il contenuto della notifica è cifrato con la chiave pubblica del certificato XXXXXX-CO-9999, di conseguenza per decifrarlo occorre la chiave privata contenuta nel keystore XXXXXX-CO-9999.p12.
Confermo che l'algoritmo utilizzato è l'AES256-CBC. 
Assicurati di eseguire il decode Base64 prima della decifratura.

**Comment by Antonino09** [comment]
Buongiorno,
ho un dubbio relativamente al sistema di cifratura AES256-CBC, in quanto essendo un sistema simmetrico richiede una sola chiave, quindi non capisco l'utilizzo della chiave pubblica e privata del certificato.

**Comment by gife67** [comment]
Buonasera,
in un infrastruttura PKI, si utilizza il meccanismo della chiave pubblica e privata per criptare una chiave di sessione, con la quale poi si crypta tutto il contenuto di un messaggio utilizzando l'algoritmo a chiave simmetrica, che in questo caso è l'AES256-CBC.
Le posso consigliare una libreria molto valida a riguardo, Bouncy Castle di cui esiste sia la versione Java che C#.

**Comment by Antonino09** [comment]
Buonasera,
mi può indicare in quale punto del messaggio soap si trova la chiave di sessione.

**Comment by gife67** [comment]
La chiave di sessione non si trova nel messaggio SOAP, ma all'interno di tutto lo stream cifrato e codificato Base64 che fa parte del nodo che si chiama **contenuto**.
Se utilizza una libreria crittografica come quella che le ho indicato si evita di entrare troppo nel merito dei vari formati standard utilizzati nella crittografia/PKI (PKCS7, Envelop, ASN.1 etc etc), che le evitano di dover implementare algoritmi notevolmente complessi. 
Le allego un esempio di utilizzo in Java delle Bouncy Castle per il decrypt con un keystore in formato PKCS12 come quello che ha a disposizione. Ovviamente può trovare sui vari forum molti esempi su come eseguire il decrypt di uno stream di byte. Più di questo veramente non posso fare.
[GitHub_912.txt](https://github.com/italia/anpr/files/2590366/GitHub_912.txt)

**Comment by Antonino09** [comment]
Buongiorno,
grazie alle sue indicazioni ho risolto il problema della decifratura del nodo contenuto, tuttavia mi rimane un ultimo problema relativo alla validazione della firma della notifica. In quanto nonostante utilizzi il certificato CAUtentiANPR.cer per la verifica, come da Lei precedentemente indicato, l'esito è negativo.

**Comment by gife67** [comment]
Le confermo che le notifiche sono firmate con il certificato che le ho allegato nel file FirmaNotifiche.zip, dove c'è la catena completa e che può verificare con l'ID della chiave del certificato di CA d056d5f3e5e6f8a43d538e86706acf0e442bb20c
Forse esegue il trust in una modalità errata.

**Comment by Antonino09** [comment]
Buonasera,
nonostante le sue indicazione e dopo molti tentativi non riesco a validate la firma della notifica con esito positivo,  se può cortesemente dare ulteriori indicazioni in modo da risolvere quest'ultimo problema.
