### ISSUE TITLE
Variazione indirizzo IP pubblico

### ISSUE THREAD

**Issue by sisteminformativi** [italia/anpr#913]
Buongiorno.

Dobbiamo migrare da Fastweb a TIM Fibra. Nuovo ISP.
Abbiamo un nuovo indirizzo IP.
Come dobbiamo procedere per la richiesta di variazione di tale indirizzo?
Grazie.

**Comment by cmigliardi** [comment]
Cortesemente potete dirci il nome del comune? verifichiamo con quale ip si presenta ai servizi di Anpr. grazie

**Comment by sisteminformativi** [comment]
Comune di Biassono
attuale indirizzo IP (Fastweb) : 89.96.213.130

Nuovo Indirizzo IP (TIM): 195.223.26.174 

Grazie

**Comment by cmigliardi** [comment]
quindi - se non ho capito male - richiedo una nuova abilitazione e poi mi fate sapere quando debbo disabilitare il vecchio?

**Comment by sisteminformativi** [comment]
Si. La ringrazio.
Siccome non vorrei bloccare lo sportello Anagrafe, vorrei sapere se è una cosa immediata, oppure, se secondo lei, meglio farlo domani che non è aperto al pubblico?
Grazie

**Comment by cmigliardi** [comment]
richiedere l'abilitazione di un nuovo IP non blocca lo sportello - semplicemente è un Ip  in aggiunta al precedente finché non mi scrivete che posso disabilitare  il vecchio Ip

**Comment by sisteminformativi** [comment]
Si. Grazie.
Allora possiamo procedere anche subito. Dato che io, (amministratore di Sistema) sono quì in Comune solo nei giorni di Martedì e Giovedì.
Quindi il Nuovo IP da abilitare è il seguente: 195.223.26.174

Grazie mille.

**Comment by sisteminformativi** [comment]
Grazie ancora.

**Comment by cmigliardi** [comment]
l' IP 195.223.26.174  è stato abilitato - attendo la email quando disabilitare il vecchio - grazie

**Comment by sisteminformativi** [comment]
Buongiorno. Le confermo che non abbiamo nessun problema con il nuovo Indirizzo IP pubblico abilitato (195.223.26.174).
Quindi potete tranquillamente disabilitare il vecchio IP (89.96.213.130)

grazie.

**Comment by cmigliardi** [comment]
La ringrazio, provvedo a richiedere  remove del vecchio ip.
