### ISSUE TITLE
[3002 / 5012] Consultazione: "Internal Error (from server)" / Annullamento: Errore 999

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#914]
ambiente di PRODUZIONE - comune di Sogliano al Rubicone (FC)

soggetto AIRE con idSoggettoANPR 33325445

1.
la consultazione della scheda individuale ritorna 
```
<env:Fault>
  <faultcode>env:Server</faultcode>
  <faultstring>Internal Error (from server)</faultstring>
</env:Fault>
```
(rif. idOperazioneComune 2018300422 - ws 3002)

2.
sullo stesso soggetto, tentiamo di annullare una mutazione 5008 e otteniamo come risultato
```
<errore>
  <codiceErroreAnomalia>999</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Operazione non effettuabile</testoErroreAnomalia>
</errore>
```
(rif. idOperazioneComune 2018000128 - ws 5012)

come sbloccare la situazione?

grazie
Alessandro Monopoli ADS

**Comment by amollicone1982** [comment]
Era presente un carattere non ammesso nel campo denominazione dell'indirizzo.
Può riprovare

**Comment by AMonopoliADS** [comment]
entrambe le operazioni sono andate a buon fine.
grazie

faccio solo un appunto: 
in casi analoghi, in passato, il cliente ha scelto come sostituire il carattere non ammesso ed ha comunicato la richiesta di modificare il dato in ANPR tramite PEC.
in questo caso specifico il soggetto interessato è stato cancellato, quindi non si pongono più problemi di disallineamento... ma in generale (pec o non pec) mi sembra una buona modalità quella di condividere la modifica in modo che la base dati locali sia allineata con ANPR e viceversa.

grazie.
