### ISSUE TITLE
[6001] Carattere errato in PDF per emissione 2

### ISSUE THREAD

**Issue by busaster** [italia/anpr#915]
Ambiente di produzione, comune di Darfo Boario Terme.

Il portale del cliente riceve una richiesta di emissione certificato, la quale viene passata ad ANPR con codice emissione 2.

Nel PDF che viene restituito c'è un errore nel testo che compare in coda al certificato : "L’AUTENTICITA’, INTEGRITAU2019 E NON RIPUDIABILITA’ DEL PRESENTE CERTIFICATO E’....".
L'errore è il testo U2019, probabile errata conversione di un carattere unicode.

ID operazione ANPR del certificato : 27249586

Gianrico Busa
Maggioli Spa

**Comment by rnapoli1983** [comment]
Buongiorno grazie per la segnalazione cercheremo di risolvere quanto prima.

Volevo comunque segnalare che il testo normativo, in cui è presente l'errore, verrà disabilitato perchè inerente all'apposizione del sigillo digitale  che non è prevista  al momento.

Cordiali saluti.

**Comment by rnapoli1983** [comment]
Potete riprovare ?

Grazie mille.

**Comment by busaster** [comment]
Problema risolto, la dicitura ora è cambiata e non ci sono caratteri errati.
