### ISSUE TITLE
mutazione tutti i dati e CF

### ISSUE THREAD

**Issue by maradellasantina** [italia/anpr#917]
Buongiorno segnalo due casistiche di un nostro cliente come da indicazione degli operatori sogei:
1° caso) profugo iscritto in anpr che cambia generalità (data di nascita), in agenzia entrate gli assegnano un nuovo codice fiscale provvisorio (numerico) ma non è possibile, collegare due codici numerici. Quindi nella banca dati locale i dati sono  aggiornati tuttavia questi non passano in anpr e non si riesce a forzare nemmeno attraverso la web-app la mutazione
2° caso) profugo iscrito in anpr che cambia tutte le generalità (nome, cognome e data di nascita). In AE ha un codice alfanumerico collegato a un codice numerico, nella banca dati locale ha un CF  alfanumerico precedente ai cambi generalità. La modifica è bloccata per "superamento campi variati" (anche in questo caso non passa la variazione e non si riesce ad inserire la mutazione nemmeno attraverso al web-app).

**Comment by rvinzani** [comment]
Buongiorno Mara, purtroppo la gestione dei CF provvisori per i profughi non è ancora possibile né per effettuare variazioni sui dati anagrafici né per collegare due posizioni. A breve sarà disponibile  in ANPR (solo da web) la funzione per collegare il CF numerico provvisorio a quello alfanumerico definitivo. Una volta poi che in ANPR sarà presente il CF definitivo la gestione dei dati anagrafici rientrerà nelle normali funzioni attualmente disponibili in ANPR. Per quanto riguarda il limite sui campi variati, questa operazione si effettua generalmente con due passaggi. Purtroppo in ogni passaggio viene generato un nuovo CF. Questo è un limite imposto nei servizi di Agenzia Entrate
