### ISSUE TITLE
RICERCA PERSONE IN CONVIVENZA

### ISSUE THREAD

**Issue by RENZO63** [italia/anpr#918]
COMUNE DI VALLE MOSSO  096073  - PRODUZIONE

Da applicativo Selene di Siscom richiedendo l'emissione di un certificato di persona iscritta in convivenza viene restituito il messaggio di errore bloccante su servizio 3002:  "EN122  La richiesta effettuata non produce alcun risultato" nel caso in cui non vi siano omonimi in ANPR.
Nel caso vi siano omonimi viene restituito l'elenco delle persone tranne quella iscritta in convivenza (nel mio comune, se iscritta in altre convivenze non so...)
Contattata la software house mi dice che la chiamata al servizio per gli iscritti in convivenza e gli iscritti "normali" e' la stessa quindi non e' un errore dell'applicativo e, sinceramente, non so dare loro torto.
Ho verificato almeno una decina di persone sia in casa di riposo che richiedenti asilo e la situazione e' la stessa.
Per i residenti "normali" funziona tutto
Tramite web la ricerca e la successiva certificazione funziona perfettamente.
vi do' un paio di identificativi da verificare....  30650469     19026718    19026771
Come possiamo risolvere??
Grazie in anticipo

**Comment by mttfranci** [comment]
Buongiorno.

E' corretto che i soggetti (es 30650469) non vengano trovati.
In precedenza il 3002 non si comportava in modo aderente alle specifiche e ci è stato segnalato con issue #871 (venivano ignorati i filtri per tipo scheda e soggetto AIRE).

Mella documentazione tecnica è specificato che se indicato tra i criteri di ricerca tipo scheda = 1 devono essere restituiti solo i soggetti residenti in famiglia e non in convivenza.
https://www.anpr.interno.it/portale/documentazione-tecnica
Ecco il dettaglio dei criteri di ricerca :
[3002-InterrogazioneCittadinoFamigliaConvivenza.xlsx](https://github.com/italia/anpr/files/2557999/3002-InterrogazioneCittadinoFamigliaConvivenza.xlsx)

Il 26 ottobre 2018, con la versione 4.1.11 tale bug è stato corretto : 
https://anpr.readthedocs.io/en/latest/change-management/changelog.html

Nel vostro caso, abbiamo trovato, ad esempio, l'operazione : 

          <idOperazioneComune>201800000000000000000000010627</idOperazioneComune>
          <codMittente>096073</codMittente>
          <codDestinatario>ANPR01</codDestinatario>
          <operazioneRichiesta>3002</operazioneRichiesta>
          <dataOraRichiesta>2018-11-07T15:02:27</dataOraRichiesta>
          <idOperazioneANPR>27708994</idOperazioneANPR>

Tra i criteri di ricerca è stato indicato tipo scheda = 1 (es id operazione ANPR : 
Vale a dire che vengono richiesti i soli soggetti residenti in famiglia)

      <criteriRicerca>
        <codiceFiscale>XXX</codiceFiscale>
        <cognome>XXX</cognome>
        <nome>XXX</nome>
        <idSchedaSoggettoANPR>XXX</idSchedaSoggettoANPR>
        **<tipoScheda>1</tipoScheda>**
      </criteriRicerca>

Pertanto è sufficiente non indicare il tipo scheda o indicarlo in modo coerente al soggetto ricercato.

Siamo a disposizione per ogni ulteriore chiarimento.
Cordiali saluti

Assistenza ANPR
