### ISSUE TITLE
[3002 / 3003] Consultazione / Elenco Operazioni: Individuo Doppio

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#919]
ambiente di PRODUZIONE - comune di Pioltello (MI)

a causa di una piccola differenza nel nome, il cliente si trova tra i residenti due soggetti che in realtà sono la stessa persona (idSoggettoANPR: 23830569 - 23830575)

allo stato attuale si verificano le seguenti anomalie:

1. nella consultazione dei due soggetti (ws 3002) viene evidenziata la seguente anomalia:
"Il soggetto con id anpr xxxxxxxxxx risulta iscritto sia in Italia che all'estero (AIRE)"
non si capisce il senso del messaggio.
se vuole indicare la presenza di un altro soggetto nel comune, allora non si capisce perchè si parli di "AIRE".
se, invece, risulta effettivamente anche un soggetto AIRE... in consultazione non l'abbiamo trovato...

2. la richiesta delle operazioni registrate sul soggetto (ws 3003), ritorna il seguente errore:
```
<errore>
  <codiceErroreAnomalia>EN095</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>La richiesta per dati di un soggetto ha individuato piu' cittadini: restringere i parametri della ricerca</testoErroreAnomalia>
</errore>
```
la stessa anomalia era già stata evidenziata (e risolta) nel caso di anagrafiche doppie presenti in comuni diversi (rif. issue #514 )
come fare per ottenere l'elenco delle operazioni dei due singoli soggetti?
non è ancora possibile richiedere la lista delle operazioni per idSoggettoANPR invece che per codice fiscale?

grazie.
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Le due persone sono effettivamente presenti in ANPR con due identificativi comunali diversi. Provvederemo a migliorare il messaggio di errore
