### ISSUE TITLE
Attestazione o certificazione di cittadinanza a soggetto straniero

### ISSUE THREAD

**Issue by wdamiani** [italia/anpr#921]
Buongiorno,
in ANPR non è previsto il rilascio del certificato di cittadinanza a soggetto straniero. Nei corsi fatti con Anusca tutti gli esperti hanno sempre concordato che tutti i dati registrati in anagrafe (quindi anche la cittadinanza straniera) devono essere certificati. Come possiamo evadere la richiesta?

**Comment by gcarbonin** [comment]
Il certificato può essere prodotto impostando a 1 il campo forzaCertificazione (vedi par. 17.1.5.7 delle specifiche ANPR).
