### ISSUE TITLE
registrazione gemelli con omocodice fiscale

### ISSUE THREAD

**Issue by ruggerori** [italia/anpr#922]
non è possibile registrare la nascita di due gemelli con nome simile, e diconseguenza codice fiscale uguale, poicheè dopo aver registrato il primo gemello, per il secondo dice che il codice è già esistente ma con dati differenti in agenzia delle entrate
come risolvere?
grazie

**Comment by rvinzani** [comment]
Il servizio di iscrizione per nascita possiede, tra i parametri inviati ad ANPR anche il parametro con cui è possibile richiedere un CF omocodice (gestioneCF = 2). In tal modo i servizi di Agenzia Entrate restituiscono un CF numerico provvisorio che verrà successivamente risolto dalla direzione centrale dell'Agenzia delle Entrate
