### ISSUE TITLE
[6001] residenza con dati diversi rispetto a 3002

### ISSUE THREAD

**Issue by busaster** [italia/anpr#924]
Ambiente di produzione, comune di Corropoli.

Per un soggetto chiediamo con il 6001 i dati XML del certificato di residenza storico per poi completarli con la storia nota localmente. Nel tag "residenza" però compare un subtag "noteIndirizzo" contenente con testo con uno spazio. (ID op ANPR : 29096465).
Se ricerco lo stesso soggetto con il servizio 3002 invece, giustamente, nel risultato non è presente il tag noteIndirizzo. (ID op ANPR 29094651).

Il tag anomalo nella risposta 6001 causa poi un problema con la nostra logica applicativa.
Potete per favorecontrollare come mai c'è questa discrepanza di comportamento ed uniformare il 6001 al 3002 ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Il comportamento del 6001 verrà adeguato a quello del 3002.
La modifica dovrebbe essere disponibile venerdì.

**Comment by mttfranci** [comment]
Salve, dovrebbe essere possibile riprovare.

**Comment by busaster** [comment]
testato dal cliente con esito positivo.
Chiudo la issue.
Grazie
