### ISSUE TITLE
[3002] nuovo campo nei dati di carta identita'

### ISSUE THREAD

**Issue by TizianaTesta** [italia/anpr#925]
Comune di Piazzola del Brenta
Ambiente di produzione

Buongiorno
il comune di Piazzola ha fatto un'iscrizione 1002 per una persona i cui dati di carta d'identità sono i seguenti:

        <cartaIdentita type="ns5:tipoCartaIdentita">
          <numero>AS0619352</numero>
          <dataRilascio>2009-11-12</dataRilascio>
          <cartaceaElettronica>0</cartaceaElettronica>
          <interdizioneEspatrio>S</interdizioneEspatrio>
          <comuneRilascio>
            <nomeComune>CURTAROLO</nomeComune>
            <codiceIstat>028036</codiceIstat>
            <siglaProvinciaIstat>PD</siglaProvinciaIstat>
          </comuneRilascio>
          <dataScadenza>2019-11-12</dataScadenza>
        </cartaIdentita>

Nel fare una richiesta dati 3002 ci torna tutti i dati di cui sopra
più un nuovo campo dataAnnullamento che non troviamo negli schemi xml e che ci invalida la risposta ottenuta.

ID OPERAZIONE: 29142415

Potete dirci cosa sta succedendo?

Grazie
Tiziana Testa
Insiel Mercato

**Comment by mttfranci** [comment]
L'aggiunta di campi opzionali è da considerarsi una modifica retrocompatibile (change management).
@mccalv  ha ribadito la questione nella issue #547 che :
**"In questo senso quindi, assumiamo che il client che si interfaccia con ANPR lo faccia sempre in modalità non strict e non vada in errore incontrando campi opzionali."**

Pertanto i gestionali dovrebbero : 
1)	O implementare i client per non avere problemi dall’aggiunta di campi opzionali
2)	O aggiornare sempre celermente i client

I WSDL aggiornati sono pubblicati sul portale ANPR : 
https://www.anpr.interno.it/portale/documentazione-tecnica
Tracciati XSD e WSDL

Siamo a disposizione per ogni ulteriore chiarimento.

**Comment by mttfranci** [comment]
Buongiorno.

Sicuramente c'è stato un ritardo da parte nella nostra nella notifica dell'aggiornamento.
Detto questo però, l'indicazione concordata con il team digitale, è che i client comunali devono sempre essere implementati in modo tale da non avere problemi quando vengono aggiunti campi opzionali.
ANPR colloquia ormai con quasi 1000 comuni, che si appoggiano a diversi fornitori software, e sarebbe impensabile che tutti si aggiornino contemporaneamente. Pertanto che i client debbano essere stabili rispetto all'aggiunta di elementi opzionali è stata valutata come la soluzione più appropriata.

**Comment by mttfranci** [comment]
Salve, avete risolto il problema di validazione della risposta?
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti

Assistenza ANPR
