### ISSUE TITLE
Diritti di segreteria

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#926]
Comune di Villa Cortese - Cod Istat 015248
Ambiente di test

Nella certificazione, secondo tabella presente sul sito ANPR, i certificati emessi ad uso:
- C.T.U. nominato dal Tribunale o dal Pubblico ministero; CURATORE FALLIMENTARE - art. 16, tabella allegato B) DPR 642/1972
- ADOZIONE, AFFIDAMENTO, TUTELA MINORI - art. 13, tabella allegato B)  DPR 642/1972 e art. 82 L. 184/1983
- SEPARAZIONE/DIVORZIO ai sensi dell'art. 19 della legge 74/1987

sono esenti, oltre che dal bollo, anche dai diritti di segreteria.
Siccome il diritto di segreteria è a discrezione della Giunta Comunale, perchè il ministero su questi usi toglie il diritto di segreteria?

E' possibile emettere il certificato per gli usi soprindicati con il diritto di segreteria ed indicare sul certificato ANPR la riscossione dei diritti?
La nostra Software House ci permette di registrare i diritti di segreteria ma il certificato ANPR riporta comunque in calce l'esenzione dai diritti e non la riscossione degli stessi.

Grazie
Claudio

**Comment by patriziasaggini** [comment]
In tutti e 3 questi casi è la legge stessa che prevede che i certificati emessi siano esenti sia dall'imposta di bollo e sia dai diritti di segreteria; 
vedi ad esempio - per il caso di separazione e divorzio - la [sentenza della Corte Costituzionale n. 154/1999](http://www.giurcost.org/decisioni/1999/0154s-99.html)
Anche nel caso delle adozioni l'esenzione totale da qualsiasi spesa è prevista dalla legge (citata nella causale dell'esenzione).
Nel caso di nomina di CTU, si tratta della più ampia esenzione per atti emessi tra Pubbliche Amministrazioni.

La Giunta comunale può eliminare la possibilità di incassare diritti, non imporre l'incasso di diritti non previsti dalla normativa.

**Comment by cvignati** [comment]
> 
> 
> Buongiorno, la Sentenza da lei citata parifica l'esenzione dall'imposta di bollo e da imposte dei certificati per uso divorzio anche all'uso separazione.
> Il diritto di segreteria non è un'imposta o tassa, è un "rimborso" per il lavoro svolto dall'ufficiale di anagrafe che tiene aggiornata tutta la banca dati anagrafica.

Buongiorno
Nessuna novità?

**Comment by patriziasaggini** [comment]
Buongiorno, l’interpretazione maggioritaria assimila il diritto di segreteria ad una tassa, e quindi esclusa dalla sentenza della Corte Costituzionale.
[Qui un articolo](url
http://www.comune.stazzano.al.it/download/DEMOGRAFICI/uso%20bollo.pdf) pubblicato sulla rivista “Lo Stato Civile Italiano” con una tabella esemplificativa in cui sono indicate le casistiche.

**Comment by rvinzani** [comment]
Minardi: Il comune non ha alcun potere di istituire diritti di segreteria sui certificati anagrafici, ma ha solo il diritto di ridurli o di eliminarli! I diritti di segreteria sono previsti dalla legge 8 giugno 1962, n. 604, Tabella D. Naturalmente, in tutti casi in cui una legge detta disposizioni in cui si esclude il pagamento di una qualsiasi tassa e diritti o il pagamento di qualsiasi spesa (o diciture analoghe), si dovrà ritenere escluso anche il pagamento dei diritti di segreteria E questo è proprio il caso degli usi esenti anche da diritti di segreteria previsti in ANPR.
Altra cosa sono le imposizioni di diverso tipo, quali ad esempio, il cosiddetto  “rimborso stampati” o simili, che, per i certificati anagrafici e di stato civile (materie di competenza esclusiva dello Stato) possono essere istituiti solo con legge dello Stato o provvedimento del Ministero dell’interno; pertanto, al momento, sono illegittimi.
Pertanto chiudo la issue in quanto non sono previste attività.
Nel caso occorra un maggior chiarimento aprire un'altra issue facendo riferimento a questa stessa
