### ISSUE TITLE
[3002] Soggetto senza famiglia

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#927]
ambiente di PRODUZIONE - comune di Poggibonsi (SI)

idSoggettoANPR 27178806

il soggetto (intestatario del suo nucleo) è stato interessato da due pratiche:
- l'iscrizione di due componenti (padre e madre) (ws 1002)
- il suo spostamento presso un altro indirizzo all'interno del comune (ws 5005)

il cliente ha accavallato le pratiche e si è trovato nella necessità di annullare le operazione effettuate per ripartire da capo.

tutto gli annullamenti sono andati a buon fine, ma il risultato adesso è che il soggetto dal quale siamo partiti (idSoggettoANPR 27178806) risulta senza dati di famiglia.

come è possibile?
potete verificare?

grazie
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Abbiamo ricostruito la storia che ha portato a questa situazione che è comunque stata sanata. Dopo il trasferimento di due dei componenti della famiglia (di tre persone) è stato cancellato il primo. Tale cancellazione ha prodotto la chiusura della scheda. Il ripristino della mutazione di residenza ha generato il ritorno dei due soggetti (uno dei quali è quello citato) in una famiglia chiusa. Abbiamo adeguato il software per gestire anche queste situazioni più complesse. Saluti
