### ISSUE TITLE
[1010] Istituzione convivenza ripetuta

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#930]
ambiente di PRODUZIONE - comune di Poggibonsi (SI)

segnalo una situazione un po' strana che si è creata nel tentativo di creare una convivenza.
il cliente ha inviato una prima volta la comunizione per istituire la convivenza (ws 1010) con idFamigliaComune 23919, ottenendo in risposta l'idFamigliaANPR 21288064

idOperazioneComune 2018006797
request
```
<generalitaSchedaConvivenza>
  <idFamigliaConvivenzaComune>
    <idFamigliaConvivenzaComuneIstat>052022</idFamigliaConvivenzaComuneIstat>
    <idFamigliaConvivenza>23919</idFamigliaConvivenza>
  </idFamigliaConvivenzaComune>
</generalitaSchedaConvivenza>
```
response
```
<famigliaConvivenza>
  <idFamigliaConvivenzaComune>
    <idFamigliaConvivenzaComuneIstat>052022</idFamigliaConvivenzaComuneIstat>
    <idFamigliaConvivenza>23919</idFamigliaConvivenza>
  </idFamigliaConvivenzaComune>
  <idFamigliaConvivenzaANPR>21288064</idFamigliaConvivenzaANPR>
</famigliaConvivenza>
```

successivamente, nel tentativo di iscrivere il primo componente della convivenza, si accorge di avere sbagliato la data di istituzione.
con l'intenzione - seppure non corretta - di aggiornare la data di istituzione, invia a ripetizione altre comunicazioni di tipo 1010 sulla stessa famiglia.

queste comunicazioni, nell'identificare la convivenza, non fanno più riferimento all'idFamigliaComune, bensì all'idFamigliaANPR, ma succede - almeno così pare - che ogni nuovo ws 1010 produce la creazione di una nuova convivenza:

- idOperazioneComune 2018006852

request
```
<generalitaSchedaConvivenza>
  <idFamigliaConvivenzaANPR>21288064</idFamigliaConvivenzaANPR>
</generalitaSchedaConvivenza>
```
response
```
<famigliaConvivenza>
  <idFamigliaConvivenzaANPR>21333901</idFamigliaConvivenzaANPR>
</famigliaConvivenza>
```

- idOperazioneComune 2018006892

request
```
<generalitaSchedaConvivenza>
  <idFamigliaConvivenzaANPR>21288064</idFamigliaConvivenzaANPR>
</generalitaSchedaConvivenza>
```
response
```
<famigliaConvivenza>
  <idFamigliaConvivenzaANPR>21350294</idFamigliaConvivenzaANPR>
</famigliaConvivenza>
```
-  idOperazioneComune 2018006895

request
```
<generalitaSchedaConvivenza>
  <idFamigliaConvivenzaANPR>21288064</idFamigliaConvivenzaANPR>
</generalitaSchedaConvivenza>
```
response
```
<famigliaConvivenza>
  <idFamigliaConvivenzaANPR>21350310</idFamigliaConvivenzaANPR>
</famigliaConvivenza>
```

mi chiedo: 
il sistema non avrebbe dovuto bloccare con errore le richiesta di istituzione di convivenza, comunicando un idFamigliaANPR già esistente?

in questo caso specifico abbiamo proceduto all'archiviazione delle convivenze create erroneamente con ws 2009 (se possibile, verificate che siano andate a buon fine come sembra dalle risposte dei ws)

per il futuro c'è modo di evitare che ricapiti, oppure è normale quanto è successo?

grazie.
Alessandro Monopoli ADS

**Comment by rvinzani** [comment]
Nell'iscrizione della scheda convivenza tramite il servizio 1010, il numero idFamigliaConvivenzaANPR è restituito nella risposta poichè necessariamente attribuito da ANPR. Il comune può, opzionalmente, associare un proprio numero di scheda comunale. Su tale numero però non è effettuato alcun controllo poichè la famiglia potrebbe cambiare comune e di conseguenza identificativo comunale la cui gestione è a carico del comune, mentre l'identificativo ANPR rimane invariato fino alla chiusura della famiglia o convivenza.
Si conferma che le schede convivenza aperte erroneamente sono state annullate ed è rimasta attiva quella con id 21350314

**Comment by rvinzani** [comment]
In realtà, analogamente ad una famiglia la convivenza può cambiare residenza da un comune ad un altro mantenendo l'identificativo ANPT . L'unica differenza tra la convivenza e la famigli sta nel fatto che mentre la scheda famiglia si chiude con la cancellazione/trasferimento  del suo ultimo componente, la convivenza viene chiusa volontariamente con un servizio specifico (2009) . Saluti
