### ISSUE TITLE
[1010] Istituzione convivenza - Errori ES008 / EF061

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#932]
ambiente di PRODUZIONE - comune di Faenza (RA)

convivenza istituita il 21/08/1948 che, alla data del subentro, risultava vuota.
oggi deve entrare un componente, per cui si procede in via preliminare all'istituzione tramite ws 1010.
l'attuale intestatario della convivenza è un soggetto nato nel 1974.

indicando come dataDecorrenza dell'operazione la data di istituzione - come fatto anche in altre occasioni per coerenza con la dataDecorrenzaResidenza - il web-service ritorna questo errore:
```
<errore>
  <codiceErroreAnomalia>ES008</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Data di nascita 03-10-1974 successiva alla data decorrenza operazione</testoErroreAnomalia>
</errore>
```

impostando come dataDecorrenza una data successiva, coerente la data dell'intestatario, il web-service rileva l'incongruenza con la dataDecorrenzaResidenza (che, appunto, non può essere diversa dalla dataDecorrenza dell'operazione)
```
<errore>
  <codiceErroreAnomalia>EF061</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>dataDecorrenzaResidenza deve essere uguale alla data decorrenza dell'operazione</testoErroreAnomalia>
</errore>
```

come sbloccare la situazione?

grazie 
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
Quali sono gli identificativi delle operazioni in modo da poter guardare i dati contenuti nella richiesta?

**Comment by frmariani** [comment]
Stiamo predisponendo l'eliminazione del controllo ES008 dal servizio 1010;
Domani sarà possibile ripetere l'operazione (idOperazioneComune 2018026531)

**Comment by AMonopoliADS** [comment]
ho tentato la ripetizione dell'invio per la comunicazione 1010 ed è andata a buon fine, senza l'errore bloccante sulla data di nascita dell'intestatario.

grazie.
