### ISSUE TITLE
Aggiornamento ambiente produzione 15 novembre 2018

### ISSUE THREAD

**Issue by rvinzani** [italia/anpr#933]
Per operazioni di aggiornamento dell'ambiente di produzione, nella giornata di domani 15 novembre i servizi di ANPR non saranno disponibili a partire dalle ore 17:30. Verrà data comunicazione dell'avvenuto ripristino

**Comment by mttfranci** [comment]
I servizi sono stati ripristinati. Come sempre potete verificare gli aggiornamenti sul changelog : 
https://github.com/italia/anpr/blob/master/src/change-management/changelog.md
