### ISSUE TITLE
[5001] Aggiornamento parentele - Errore EF044

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#934]
Buongiorno,
Comune di Bardonecchia - ambiente effettivo
Cercando di aggiornare le parentele di una famiglia otteniamo l'errore in oggetto:
EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata

Confrontando i dati nella chiamata con quelli presenti sul portale ci sembra tutto corretto.
Potete verificare quale sia il problema?

L'operazione ANPR è la numero 29942828.

Ringrazio anticipatamente
Saluti

**Comment by frmariani** [comment]
Il soggetto idanpr=27995489 risulta essere presente sia a Bardonecchia che a Torino; consultando il cittadino per codice fiscale, vedrete la doppia presenza;
il cittadino deve aver cambiato residenza a cavallo del subentro di Torino, che, nonostante l'anomalia al subentro di soggetto duplicato, non ha effettuato la cancellazione per doppia iscrizione.
Per sanare la situazione, dovreste contattare il Comune di Torino; se ciò non fosse possibile, lo contatteremo noi.

**Comment by frmariani** [comment]
Ho contattato il Comune di Torino ed il soggetto è stato cancellato per doppia iscrizione;
potete ripetere l'operazione.
