### ISSUE TITLE
[5008] EHR35 su dati di vedovanza/scioglimentoUnione già inserito in automatico dal decesso

### ISSUE THREAD

**Issue by pissardl** [italia/anpr#935]
In ambiente di Produzione,

In seguito alla registrazione di un decesso, abbiamo provato ad effettuare la mutazione della scheda dell'unitoCivilmente  con mutazione dello statoCivile e valorizzazione dell scioglimentoUnione.

Abbiamo avuto esito negativo EHR35-L'anno dell'atto e la data di formazione dell'atto dell'unione civile non possono essere precedenti alla data dell'evento ne' successivi alla data corrente

```
idSchedaSoggettoDefunto: 28999736
idSchedaSoggettoVedovo: 28979232
idOperazioneANPR-5008-sul-vedovo: 25243881
```

Sembra che ANPR associa automaticamente il decesso sia al soggetto defunto che al soggetto coniuge/unito quanto presente in ANPR e inserisci automaticamente i dati relativo a vedovanza/scioglimentoUnione quando è possible ma senza aggiornare lo statoCivile.

Il comune deve quindi obbligatoriamente aggiornare lo statoCivile e **opzionalmente fornire i dati di vedovanza/scioglimentoUnione** ?
Visto che i dati erano identiche, sembra che sia un problema fornire i dati di vedovanza/scioglimentoUnione quando già presente.
Questo ci obbligerebbe ad effettuare un interoggazione suppliementaria per capire se fornire o meno i dati di vedovanza/scioglimentoUnione  insieme alla mutazione di statoCivile del vedovo.

Grazie,
Laurent Pissard
Wave Informatica s.r.l. per Comune di Torino

**Comment by frmariani** [comment]
In caso di decesso dell'unito civilmente, lo stesso servizio 2001 (decesso) chiude il legame tra i soggetti, così come il decesso del coniuge,  chiude il matrimonio; lo stato civile invece, deve essere necessariamente modificato dal comune.
l'informazione dello scioglimento unione/vedovanza, deve essere inviata quando il  coniuge/unito civilmente  è un soggetto "extra-anpr" (ancora non inserito in ANPR);
nel vostro caso, essendo l'unito civilmente un soggetto ANPR, deve pervenire l'informazione di aggiornamento dello stato civile ma non dello scioglimento dell'unione.

**Comment by pissardl** [comment]
OK
