### ISSUE TITLE
Errore 500 nella ricerca di un'anagrafica

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#936]
Buongiorno,
Comune di San Mauro Torinese (TO) - Codice Istat: 001249
Ambiente di pre-subentro.

il Comune in questione sta effettuando la ricerca di una persona (la richiesta ha idOperazioneComune: 2208) residente in un altro comune, ma tutto quello che viene ricevuto come risposta è un "500 internal error (from server)".
Potete verificare quale sia il problema?
Ringrazio anticipatamente
Saluti

**Comment by SAlberto** [comment]
Buongiorno,
abbiamo riscontrato lo stesso errore nel comune con Codice Istat: 001090
Ambiente di pre-subentro.

il Comune in questione sta inserendo una nascita (la richiesta ha idOperazioneComune: 2706), ma tutto quello che viene ricevuto come risposta è un "500 internal error (from server)".
Potete verificare quale sia il problema?
Ringrazio anticipatamente
Saluti

**Comment by rvinzani** [comment]
Sembra si sia trattato di un problema momentaneo. Stiamo continuando a monitorare i sistemi. Dateci per favore dei riscontri se il problema risulti rientrato e segnalateci se si dovesse ripresentare
