### ISSUE TITLE
RETTIFICA DATI STATO CIVILE (VEDOVA) PRIMA DEL DECESSO AVVENUTO IL 13.11.2018

### ISSUE THREAD

**Issue by MAURIZIO2018** [italia/anpr#938]
Innanzitutto grazie per l'assistenza che mi verrà fornita. Da segnalare che non mi trovo in ufficio e
non sono in grado in questo momento  di dare riferimenti più precisi.

CORREZIONE STATO CIVILE VEDOVA DI PERSONA DECEDUTA E SUCCESSIVA COMUNICAZIONE DI DECESSO.

In occasione della formazione dell'atto di morte di una persona residente nel nostro Comune deceduta il 13.11.2018 è emerso che  il coniuge non residente era deceduto nel 2016, e che pertanto andava rettificato ora per allora lo stato civile da coniuga a vedova sia in apr che in anpr.

Si è proceduto con WEB APPLICATION in data 14.11.2018 alla mutazione dello stato civile con l'indicazione dei dati di vedovanza avvenuti in data 04.04.2016. 

Purtroppo  la successiva comunicazione di decesso di oggi con WEB APPLICATION  ha avuto esito negativo in quanto l'evento morte anteriore alla data del 14.11.2018.

Si è proceduto quindi all'annullamento della comunicazione di mutazione relativamente alla mutazione di stato civile di vedova ripristinando la  scheda anagrafica con lo stato civile di coniugata tramite WEB APP ripristinando la scheda anagrafica al dato antecedente la mutazione dello stato civile e quindi di CONIUGATA.

Come si può procedere alla rettifica dello stato civile di coniugata con quello corretto  di vedova a suo tempo non comunicato e con decorrenza  del 04.04.2016 ma con data di validazione antecedente alla data di morte ? E' possibile indicare la data di validazione pregressa?

E' stata tentata la soluzione di mutazione dello stato civile  con WEB APP e indicando la data di decorrenza e validazione 04.04.2016 ma purtroppo avviene la segnalazione del seguente errore 
(vado a memoria) EN489 La richiesta non risulta valida secondo i nuovi XSD [Campo:'idLuogoNascita/ComuneIstat'] Codice: EN489

Da tenere presente che il subentro della persona è avvenuto lasciando inalterato il luogo di nascita (comune non esistente  nel 1930) ma indicando il corretto comune di iscrizione dell'atto di nascita.

In sostanza ho l'esigenza di intervenire ora per allora nella corretta indicazione dello stato civile di vedova ma con data di validazione antecedente la data di morte e successivamente  procedere alla comunicazione di decesso tramite WEB APPLICATION. 

COMUNE DI CALCERANICA AL LAGO

**Comment by MMaurizio** [comment]
Questo è l'errore per eseguire la variazione sullo stato civile. 

Completa l'operazione
La richiesta non risulta valida secondo i nuovi XSD [cvc-complex-type.2.4.a: Invalid content was found starting with element 'siglaProvinciaIstat'. One of '{nomeComune}' is expected.] (Codice: EN489)
La richiesta non risulta valida secondo i nuovi XSD [Numero errori trovati : 1] (Codice: EN489)

**Comment by frmariani** [comment]
Buongiorno,
purtroppo c'è un piccolo errore nella web application che le permette di inserire soltanto la provincia di nascita del soggetto senza il Comune di nascita: stiamo effettuando le opportune modifiche in modo da segnalare correttamente l'errore;

prima dell'operazione del 14/11/2018, successivamente annullata, era stata effettuata la stessa  operazione con data decorrenza 05/04/2016, contenente le informazioni sulla vedovanza del soggetto;
la successiva operazione, con data decorrenza sempre 05/04/2016, oltre ad inviare gli stessi dati già comunicati circa la vedovanza, modifica anche il luogo di nascita del soggetto, cambiandone il CF.
ad oggi il soggetto idanpr 34349804 risulta nato a Caldonazzo, è corretto ?
di fatto è stato cambiato il CF di un soggetto nato nel 1930 e deceduto.

**Comment by MMaurizio** [comment]
Ringrazio  molto per la risposta. Segnalo che a seguito della mutazione anagrafica prima di stato civile da coniugata a vedova è intervenuta la variazione del luogo di nascita  CALDONAZZO perchè  il luogo di nascita CENTA SAN NICOLO' soppresso nel periodo dal 1930 al 1947.  Il risultato è che la persona ha subito una variazione del proprio codice fiscale "POST MORTEM".  Richiedo se possibile il ripristino del luogo di nascita  CENTA SAN NICOLO' e  il ripristino del codice fiscale già attribuito con il codice belfiore C467. Questo mi consente il successivo allineamento nell'apr locale che è ancora con il codice fiscale C467 e non individua ora il disallineamento APR - ANPR.   Si richiede con l'occasione di segnalare come andranno risolte le posizioni di persone "correttamente" subentrate in anpr che hanno il luogo di nascita quale comune soppresso ma l'indicazione corretta del comune ove è iscritto l'atto di nascita.

**Comment by frmariani** [comment]
Mi rendo conto della sua perplessità, ma sconsigliamo sempre di modificare un CF valido di una persona anziana; 
per il ripristino dell'operazione e del CF è meglio sentirci telefonicamente;
mi scriva il suo contatto telefonico 
frmariani@sogei.it

**Comment by MMaurizio** [comment]
Il mio contatto telefonico è 0461723161 INT. 18 COMUNE DI CALCERANICA AL LAGO.

**Comment by frmariani** [comment]
continuiamo in privato

**Comment by frmariani** [comment]
il codice fiscale del soggetto idanpr 34349804 è stato ripristinato
