### ISSUE TITLE
Indirizzi su strade provinciali e statali

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#941]
Si chiede come è corretto registrare in ANPR gli indirizzi delle provinciali e statali con la kilometrica.
In passato tale dato è stato registrato nel campo isolato (es Km 1,200).
Da qualche giorno però ANPR mi restituisce un errore quando cerco di iscrivere cittadini ad uno di tali indirizzi. L'errore è il seguente:
L'elemento 'isolato' non è valido. il valore 'Km 1,200' non è valido per il tipo di dati 'http://sogei.it/ANPR/tipoDato:tipoIsolato' - Vincolo Pattern non riuscito. (Riga: 112, Colonna: 31)     Chiudi

**Comment by mttfranci** [comment]
Buongiorno.
L'indicazione kilometrica va indicata nel campo 'metrico' che è alternativo al numero civico.
Si deve inoltre prestare attenzione che l'informazione venga convertita in metri.
Ad esempio nel caso del km 1,2 del vostro esempio, va semplicemente indicato : 
<metrico>1200</metrico>
Siamo a disposizione per ogni ulteriore chiarimento.

**Comment by Finalmentesubentrati** [comment]
Attualmente l'indirizzo nella nostra anagrafe è Strada Provinciale 27 Km 1,200.
Andrebbe corretto in Strada Provinciale 27 n. 1200?

**Comment by mttfranci** [comment]
Confermiamo che il valore corrispondente al KM 1,200 è effettivamente 1200.
Ma va trasmesso nel campo metrico, alternativo al numero (vale a dire che può essere inviato o l'uno o l'altro).

**Comment by Finalmentesubentrati** [comment]
Tutto chiaro. Volevo solo evidenziare una sottigliezza. Nella certificazione l'indirizzo appare Km 1,2 e non Km 1,200. E' vero che gli zero decimali non contano nulla però da sempre (anche i privati che hanno aziende a tali indirizzi), la kilometrica è indicata con tutte e 3 le cifre dopo la virgola.
Grazie ancora
