### ISSUE TITLE
Problemi con richiesta contributo

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#943]
Buongiorno,

dalla scorsa settimana alcuni comuni che stiamo seguendo per il subentro in fase di richiesta del contributo stanno avendo la seguente problematica: 
scaricano la richiesta, la firmano digitalmente con dispositivo del sindaco e poi ne fanno l'upload.
Al termine il portale da il seguente errore:
**Esito verifica firma: Non e' stato firmato il file predisposto**
Vedendo ciò il comune riscarica la richiesta e la firma, ma quando la ricarica il sistema blocca tutto:
**Il file firmato e' gia' stato caricato e non puo' essere modificato**

Se il primo caricamento non è andato a buon fine, perchè vengono bloccati caricamenti successivi?

Uno di questi comuni ha contattato la vostra assistenza la quale gli ha detto di firmare la richiesta dalla stessa macchina da cui è stata scaricata, ma un comune subentrato oggi ha avuto le stesse problematiche anche facendo tutto dallo stesso pc.

Potete indicarmi come risolvere la situazione? Ringrazio anticipatamente.

**Comment by sfmodena** [comment]
Comune di Modena

Buongiorno,
il Comune di Modena è alle prese con questo stesso errore dal 4 di luglio; abbiamo fatto diversi tentativi di firma del file e poi contattato ripetutamente il numero verde dell' assistenza che ha preso nota del problema ma non ci ha mai richiamato. E' necessario cancellare completamente la richiesta e reinserirla ?
Grazie
Sonia Fiorini

**Comment by rvinzani** [comment]
Abbiamo verificato che nel caso il file PDF, prima di essere firmato digitalmente, venga aperto all’interno di un browser e poi da lì salvato, tale file successivamente firmato digitalmente produce l' errore : file non firmato. Alcuni browser infatti sembra modifichino il PDF originario e per questo non venga riconosciuto come originale.
In questi casi è preferibile annullare la richiesta e procedere con una nuova richiesta. Scaricare nuovamente il  file da firmare che deve essere salvato direttamente in locale quando si seleziona il pulsante di download.
