### ISSUE TITLE
[1014] Apertura procedimento per soggetto nato in stato non codificato

### ISSUE THREAD

**Issue by busaster** [italia/anpr#944]
Ambiente di Produzione. comune di Lucca.

Abbiamo un soggetto nato nello stato GERUSALEMME (codice 325), id ANPR 19565163
Questo soggetto è entrato in ANPR con il subentro AIRE e non ha nessuna anomalia riportata nella scheda individuale.
Nel momento in cui tentiamo di aprire un procedimento inserendo questo soggetto veniamo bloccati dall'errore "Stato di nascita di codice 325 non esistente". (id operazione ANPR procedimento 31901843).

Come possiamo procedere ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by gcarbonin** [comment]
Gerusalemme è un territorio al momento NON utilizzabile per comunicare lo stato di nascita (salvo verifiche di tipo amministrativo per verificare cosa riportano i documenti di questa persona). Il subentro è di circa un anno fa quando probabilmente i controlli sugli AIRE erano meno stringenti. Oggi passerebbe con stato = 998 e nome stato Palestina.  Se si mantiene questa regola anche nel servizio non ci dovrebbero essere problemi.

**Comment by busaster** [comment]
Quindi preliminarmente si dovrebbe alterare il luogo di nascita del soggetto per poi procedere con l'apertura del procedimento. Corretto ?

**Comment by ncapozzi** [comment]
Si dovete prima allineare il luogo di nascita come vi è stato indicato.
