### ISSUE TITLE
[3002] ricerca tramite codice fiscale: errore in risposta 

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#946]
Buongiorno,
vorrei chiedervi, gentilmente, di controllare la richiesta effettuata poco fa al servizio 3002:
IdoperazioneComune = 1000845
IdOperazioneANPR = 32260306
Ambiente produzione di Bistagno(AL) 006017

Non ricevo la risposta per qualche errore. Potreste dirmi da cosa dipende?
Grazie

**Comment by rvinzani** [comment]
Sembra si sia trattato di un problema momentaneo. Stiamo continuando a monitorare i sistemi. Dateci per favore dei riscontri se il problema risulti rientrato e segnalateci se si dovesse ripresentare

**Comment by Eduardo1977** [comment]
Buongiorno,
ho appena effettuato due chiamate senza successo al ws3002 per avere i dati del cittadino in questione (codice fiscale MBLT...)

1. IdoperazioneComune 1000850	IdOperazioneANPR  33974349 (con data riferimento 20/11/2018)
2. IdoperazioneComune 1000849	IdOperazioneANPR  33973573 (con data riferimento 26/11/2018)

Comunque, con il funzionario del Comune abbiamo appurato che si tratta di un AIRE che al momento del Subentro di Bistagno compariva nell'elenco estratto dall'ANAGAIRE, ma che non aveva codice fiscale.
Se avete bisogno del file del subentro aire ve lo posso inviare per posta.

**Comment by rvinzani** [comment]
Il soggetto non esiste in ANPR

**Comment by Eduardo1977** [comment]
Al momento del subentro, questo cittadino aire risultava nell'elenco estratto da ANAGAIRE senza codice fiscale, come già detto. Quindi, il codice fiscale che stiamo utilizzando sarà sicuramente sbagliato ...

**Comment by rvinzani** [comment]
Potete provare a ricercarlo per cognome e nome o meglio IdANPR

**Comment by Eduardo1977** [comment]
Grazie, proverò domani con il Funzionario del Comune

**Comment by Eduardo1977** [comment]
Buongiorno @rvinzani,  cercando per nome/cognome in ANPR il cittadino risulta in AIRE ma non ha il codice fiscale
