### ISSUE TITLE
Notifiche : campo non previsto in XML causa errori in scarico locale

### ISSUE THREAD

**Issue by busaster** [italia/anpr#947]
Ambiente di Produzione, comune di Carrara.

Il comune riceve una notifica di emigrazione in altro subentrato (id operazione 32159898).
Nella notifica però c'è un'anomalia : il campo "sigla provincia" del comune di nascita dell'anagrafica è contenuto in un tag "siglaProvincia" invece che in un tag "siglaProvinciaIstat".

Questo causa problemi alla conversione del XML in oggetto Java, creando un comune privo di provincia.
Potete verificare la costruzione del XML di notifica ? 

Grazie

Gianrico Busa
Maggioli Spa

**Comment by fferraguto** [comment]
Salve,
per le notifiche, il comune di nascita è definito dal tipo dato "tipoComune" che, a differenza dei servizi, contiene gli elementi:
nomeComune
codiceIstat
siglaProvincia
descrizioneLocalita

potete consultare la documentazione completa al link:
https://www.anpr.interno.it/portale/documentazione-tecnica

Cordiali saluti.
Assistenza ANPR

**Comment by busaster** [comment]
ci era sfuggita questa differenza, grazie per la precisazione
