### ISSUE TITLE
Rigetto di espatrio chiuso prima del subentro

### ISSUE THREAD

**Issue by busaster** [italia/anpr#949]
Ambiente di produzione, comune di Arcore.

Dobbiamo procedere all'annullamento di un espatrio nell'aire del comune di un suo cittadino.
L'idea era quella di fare una mutazione di tipo 5005 di tipo 6 per riportarlo nella famiglia in cui era prima dell'espatrio con la decorrenza in cui effettivamente vi risiedeva.
Il soggetto AIRE però risulta avere, come dato inserito al subentro, data di iscrizione nel comune pari alla data di espatrio, immagino venga letta dal file ANAG-AIRE inviato per subentrare.
La nostra idea era quella di modificare questa data retrodatandola a quella di iscrizione APR originaria del soggetto e di procedere con la variazione 5005 di cui parlavo prima.

E' un procedimento corretto ?

Grazie
Gianrico Busa
Maggioli Spa

**Comment by ncapozzi** [comment]
Buongiorno,
se ho ben capito il cittadino è entrato ina ANPR con il subentro AIRE. Se è così sembra più corretto effettuare una cancellazione e una riscrizione del cittadino come residente indicando nella richiesta l'idsoggetto ANPR attribuito al subentro, la data di iscrizione APR originaria e l'id ANPR della famiglia di appartenenza.

N. Capozzi

**Comment by busaster** [comment]
Sto provando ad applicare la logica suggerita in un caso analogo a quello del cliente in ambiente di test (Poggio a Caiano). 

Riesco a cancellare il soggetto ma quando provo a re-iscriverlo in ANPR ottengo l'errore "idSchedaSoggettoANPR ******* non presente o dati anagrafici incongruenti". ID operazione ANPR cancellazione 18768424, ID operazione ANPR iscrizione 18768425

**Comment by ncapozzi** [comment]
Buongiorno,
stiamo cercando di capire la ragione per la quale viene restituito il msg di errore. Potreste per favore inviare nuovamente il 1002? Grazie

**Comment by busaster** [comment]
prova ripetuta, id ANPR iscrizione in errore 18769875

**Comment by ncapozzi** [comment]
Scusate potete riprovare solamente il 1002? Grazie

**Comment by busaster** [comment]
fatto ,id ANPR 18770188

**Comment by ncapozzi** [comment]
E' stato corretto l'errore che vi impediva di effettuare la riscrizione nel caso di test effettuato. Potete riprovare il 1002 per favore? Attendiamo riscontro grazie

**Comment by busaster** [comment]
L'errore di prima è sparito. Rimane però un problema : l'iscrizione dovrebbe decorrere dal 23/06/2012, però il soggetto ha variazioni successive, tra cui un matrimonio del 2015, per cui veniamo bloccati da ES010 "La data del matrimonio deve essere maggiore della data di nascita e minore o uguale della data di decorrenza dell'operazione"

**Comment by busaster** [comment]
Lo temevo. 
In questa situazione tornerebbe molto utile una modalità inserimento che simulasse un "subentro per singola persona" in modo da poter caricare in un'unica chiamata tutta la situazione della persona

**Comment by busaster** [comment]
Provando ora a fare l'iscrizione con dati minimi veniamo bloccati da "La data di decorrenza della nuova residenza non puo' essere antecedente a quella gia' registrata". ID Operazione iscrizione 18771547.

Faccio notare che abbiamo cancellato con decorrenza pari alla data di iscrizione AIRE(8/11/2016)
L'iscrizione in ANPR con i dati originari dell'iscrizione all'APR del comune (23/06/2012) non è quindi possibile.

**Comment by ncapozzi** [comment]
Buongiorno,
il problema non deriva dalla data di cancellazione ma dal fatto che la data di decorrenza della residenza della famiglia alla quale cercate di associare il soggetto è 10/11/2012, successiva alla data di iscrizione del soggetto stesso.

**Comment by busaster** [comment]
il fatto è che alla data del subentro l'unico elemento della famiglia erà lì residente dal 10/11/2012 ed è diventato IS alla cancellazione della persona che ora stiamo tentando di re-iscrivere. Per cui al subentro la data di indirizzo della famiglia è stata inviata come 10/11/2012. Come dobbiamo comportarci ?

**Comment by ncapozzi** [comment]
Prima dell'iscrizione, potete effettuare una rettifica della data decorrenza residenza al subentro con un 5014 per l'attuale intestatario

**Comment by ncapozzi** [comment]
Buongiorno, a seguito dei chiarimenti intercorsi per email il 29/11/2018, si conferma la soluzione proposta 
Dovete cancellare anche idsoggetto 9461490 e poi ripetere le prime due operazioni effettuate
1.	IDsoggetto  9451730 si riscrive in APR il 23/06/2012  con formazione di nuova famiglia
2.	 IDsoggetto 9461490 si riscrive in APR il 10/11/2012 entrando come convivente nella nuova famiglia creata al punto 1.
Restiamo comunque a disposizione per ulteriori chiarimenti.
