### ISSUE TITLE
Web app - Variazione stato procedimento

### ISSUE THREAD

**Issue by VBocchinoTO** [italia/anpr#95]
Per agevolare la ricerca del procedimento per effettuare le successive variazioni dello stesso (conferma dati comune precedente iscrizione o chiusura), nel pannello Registrazione (tipo operazione: gestione procedimento/istruttoria) sarebbe utile poter effettuare la ricerca anche per numero del procedimento oltre agli attuali criteri di ricerca (per dati anagrafici persona, per identificativo persona o identificativo famiglia).
Grazie.
Valentina Bocchino, Pier Dario Brigandì - Comune di Torino

**Comment by gcarbonin** [comment]
Terremo presente come successiva evoluzione

**Comment by gcarbonin** [comment]
La funzione di ricerca per numero di procedimento è disponibile
