### ISSUE TITLE
Richiedente certificato membro di Forze dell'ordine 

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#950]
Comune di Villa Cortese 015248
Produzione

Buongiorno, 
chiedo come comportarsi nel caso il richiedente di certificazione sia un Carabiniere, Poliziotto, Finanziere, etc. 
Prima di ANPR come richiedente inserivamo Stazione Carabinieri di.........., Questura di, etc
Oggi dobbiamo inserire i dati completi del richiedente e questo non sempre è accettato dal Carabiniere in quanto dice di fare la richiesta come facente funzioni e questo è corretto.
Stessa cosa mi è stata detta oggi dal Capo Stazione dei Carabinieri della nostra zona, che mi ha anche precisato che spesso la richiesta a loro arriva da altri colleghi di altre stazioni o da superiori.

Chiedo una linea guida da seguire ed il comportamento dei colleghi Ufficiali di Anagrafe che seguono in questi casi. 

Grazie

**Comment by cvignati** [comment]
Al punto 17.1.5.6 "Certificati richiesti da Enti" delle "Specifiche di interfaccia dei servizi di ANPR per i comuni – documento generale - pdf" alla fine dice: Devono comunque essere compilate le generalità della persona che richiede il certificato per conto dell’Ente.
Nel file "6001-RichiestaCertificati.xlsx" presente nelle  "Specifiche di interfaccia dei servizi di ANPR per i comuni – documentazione tecnica - rar"  al Progressivo n. 5 "Generalità del richiedente", che risulta essere dato obbligatorio, rimanda all'oggetto "Generalità" delle stesse specifiche.
Nel file "generalita.xlsx" nessuno dei campi risulta obbligatorio.

Detto questo, si potrebbero conoscere chiaramente i campi obbligatori delle generalità del richiedente.

Grazie

**Comment by rvinzani** [comment]
Cognome, Nome, data e luogo di nascita

**Comment by cvignati** [comment]
Ok,
mi riallaccio però all'Issue [#424](https://github.com/italia/anpr/issues/424#issuecomment-377490764) nella quale la Responsabile dell'anagrafe di Cortina d'Ampezzo chiedeva se non fosse possibile indicare solo Cognome e Nome del richiedente.
Le forze dell'ordine, viste le funzioni da loro svolte, spesso di P.G., e soprattutto in quanto richiedono il certificato, non per uso personale, ma per il procedimento che stanno svolgendo, alla richiesta delle generalità complete rimangono spiazzati, rispondendo che il certificato non è per uso personale ma per conto dell'Ente per cui lavorano.
Chiedo se possano essere inseriti, per i certificati richiesti da Enti (Tipo 3), solo i campi Cognome e Nome e negli estremi del documento i seguenti dati:
- nel campo che normalmente contiene il documento, il nome dell’ente e gli estremi della richiesta;
- nel campo che normalmente contiene la data di rilascio, la data della richiesta.
come da Issue [#627](https://github.com/italia/anpr/issues/627#issuecomment-379213682)
In questa maniera si terrà traccia di chi ha richiesto il certificato univocamente e sicuramente ci saranno molte meno "lamentele" da parte dei richiedenti i certificati.

Faccio questo tipo di richiesta in quanto ragiono su come richiedo io un certificato ad un altro ente.
Io Pinco Pallino in qualità di Ufficiale di anagrafe del Comune di XXXXX, richiedo il certificato di XXXX XXXX per il procedimento YYYYYYY.
Nel richiedere il certificato ad un altro ente non indico le mie generalità complete, ma solo Cognome e Nome, Ente per cui lavoro e qualifica.

Spero che la mia segnalazione sia soddisfatta, perchè sento tanti colleghi che hanno lo stesso problema.

Grazie

**Comment by rvinzani** [comment]
Certo, la richiesta iniziale è stata contrassegnata come chiarimento normativo. La mia risposta era indirizzata alla domanda specifica sull'obbligatorietà dei campi

**Comment by rvinzani** [comment]
Se abbiamo capito bene la domanda può compilare solo i seguenti dati:

<generalitaRichiedente>
            <generalita>
               <cognome>Rossi</cognome>
               <nome>Mario</nome>
            </generalita>
            <docRiconoscimento>
               <estDocRiconoscimento>nome dell’ente (es: Stazione Carabinieri di Roma, Agenzia Entrate ecc.)</estDocRiconoscimento>
               <dataRilascio>la data di richiesta (se fosse oggi:  2018-12-06)</dataRilascio>
            </docRiconoscimento>
</generalitaRichiedente>

**Comment by cvignati** [comment]
> 
> 
> Se abbiamo capito bene la domanda può compilare solo i seguenti dati:
> Rossi Mario nome dell’ente (es: Stazione Carabinieri di Roma, Agenzia Entrate ecc.) la data di richiesta (se fosse oggi: 2018-12-06)

Esatto

**Comment by cvignati** [comment]
Scusi ma forse non ho capito la sua risposta.
Attualmente posso rilasciare un certificato richiesto da enti, inserendo come dati richiedente:
- In generalità solo Cognome e Nome;
- nel campo "estremi documento" inserisco l'ente di appartenenza e la qualifica;
- nel campo "data rilascio documento" la data della richiesta.

Corretto? 

Grazie

**Comment by rvinzani** [comment]
Corretto
