### ISSUE TITLE
[7001] Scarico dei comuni subentrati

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#951]
Buongiorno,

Ambiente di Pre-Subentro,
da ieri pomeriggio sembra non essere possibile scaricare il file contenente l'elenco dei comuni presubentrati utilizzando il servizio 7001.

Potreste verificare?
ringrazio anticipatamente.

**Comment by mttfranci** [comment]
Salve, al fine di poter meglio verificare, potreste dati qualche dettaglio in più?
Ad esempio il comune e l'id operazione comune che avete provato.
Se disponibile anche l'id dell'operazione anpr o il tipo di errore riscontrato.
Grazie in anticipo.

**Comment by SAlberto** [comment]
Buongiorno,
capita ad esempio con il comune di Vicoforte (CN) - Codice Istat 004242.
L'id_operazione comune è: 690.
L'errore che riscontriamo riguarda il file che dovrebbe contenere l'elenco dei comuni in pre-subentro ma che invece arriva corrotto ed impossibile da aprire.
Grazie.

**Comment by mttfranci** [comment]
Salve, a noi il contenuto della risposta sembra essere stato popolato correttamente.
Vi ricordiamo che i dati contenuti nel tag xmlFile vanno considerati come un flusso compresso.
Vi alleghiamo quello che a noi risulta essere il [contenuto](https://github.com/italia/anpr/files/2615546/046.zip) del tag xmlFile una volta decompresso.  
Potete prendere come riferimento anche il codice di esempio pubblicato nella issue #840.
Se il problema non dovesse essere questo non esitate a scrivere nuovamente.
Siamo a disposizione per ogni ulteriore chiarimento

**Comment by SAlberto** [comment]
Stiamo continuando a cercare il problema, non capiamo, in ambiente di TEST e SUBENTRO lo scarico funziona, mentre in PRE-SUBENTRO dallo scorso 22 novembre no.
Notavamo che lo zip che ci avete linkato ([contenuto](https://github.com/italia/anpr/files/2615546/046.zip)) è denominato 046, ma la tabella corretta per i "Comuni Subentrati" non dovrebbe essere la 045?

Grazie

**Comment by mttfranci** [comment]
Buongiorno.
Volevo allegare direttamente il contenuto CSV ma github non permette di allegare questa tipologia di file.
Al momento di allegarlo ho sbagliato a indicare il numero, ma è stata una operazione manuale.
A noi sembra che il servizio non abbia nessun tipo di problemi. 
Ci risulta che altri comuni lo stiano usando e non ci sono stati cambiamenti nel servizio da ottobre.
