### ISSUE TITLE
Utenti - Rejected by policy. (from client)

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#954]
ambiente di PRODUZIONE - comune di RUBIERA (RE)

capita per un solo utente che tutte le attività eseguite via web-service ottengono in risposta l'errore
"Rejected by policy. (from client)"

lo stesso utente riesce a lavorare da web-app, ma non tramite web-service.
ci dicono che il codice fiscale utilizzato sia corretto, così come le abilitazioni dell'utente.

potete verificare alcune chiamate per capire quale sia il problema?

ws 3002 - idOperazioneComune 2018300067
ws 5008 - idOperazioneComune 2018000024

grazie
Alessandro Monopoli ADS

**Comment by Leonforte** [comment]
Se il certificato di postazione utilizzato è lo stesso sia da ws che da webapp, potrebbe essere un problema relativo all'orario impostato sulla postazione. Se così non fosse occorre sapere l'utenza e il CN del certificato usato, e considerato che le operazioni indicate non arrivano proprio, sarebbe utiliavere anche l'xml della richiesta, saluti

**Comment by AMonopoliADS** [comment]
se mi da' una mail personale le giro tutte le info che mi ha chiesto. grazie

**Comment by Leonforte** [comment]
Nella richiesta il CF dell'utente non è quello che abbiamo noi, in sostanza dovrebbe essere errato, le rispondo in privato

**Comment by AMonopoliADS** [comment]
probabilmente è stato fatto un errore in fase di censimento dei gli utenti.
il codice fiscale corretto non è quello censito, ma quello che vi ho mandato per e-mail.
come fare in questi casi?
è un dato modificabile dall'amministratore di sistema?
grazie

**Comment by Leonforte** [comment]
No, il CF non può essere corretto anche perchè stampato sulla SC. L'amministratore locale della sicurezza (ALS che da una prima verifica non è stato nominato dal Sindaco) può entrare nella console di sicurezza ed inserire il nuovo utente con la richiesta di emissione di una uova smart card e dopo l'attivazione può cancellare l'utenza errata.  Capitolo 6 e 8 del manuale allegato, buona serata

[Configurazione della postazione per l’accesso al sistema web ANPR e operazioni propedeutiche al subentro.pdf](https://github.com/italia/anpr/files/2616414/Configurazione.della.postazione.per.l.accesso.al.sistema.web.ANPR.e.operazioni.propedeutiche.al.subentro.pdf)
