### ISSUE TITLE
Internal Error (from Server)

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#955]
Codice ISTAT ente 006003
Codice ISTAT ente 063001
Codice ISTAT ente 025016
Codice ISTAT ente 059032
Codice ISTAT ente 052015

Riscontriamo numerosi errori Internal Error (from server) nel servizio 3002 di consultazione.

La richiesta riveste carattere d'urgenza in quanto sta creando disservizi agli sportelli cittadino.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Solutions Operations & Capabilities Development-Nord & Centro
Dedagroup Public Sector & Utilities

**Comment by rvinzani** [comment]
Sembra si sia trattato di un problema momentaneo. Stiamo continuando a monitorare i sistemi. Dateci per favore dei riscontri se il problema risulti rientrato e segnalateci se si dovesse ripresentare
