### ISSUE TITLE
Segnalazione denominazione comune errata Novilara ora Pesaro

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#957]
Buongiorno,
il comune di Pesaro che subentrerà a breve ci segnala che il comune di Novillara codice 041816 presente nella tabella storica dei comuni di ANPR, che e' stato aggregato al comune di Pesaro nel 1929, ha la denominazione esatta "NOVILARA" e non "NOVILLARA".
Tale denominazione si evince dal Regio Decreto del 25/02/1929 n.285.

Per eventuali delucidazioni potete contattare:
Fabio Costantini
Il Responsabile al Coordinamento
Servizio Demografici e Partecipazione

Tel.0721/387300-299
email f.costantini@comune.pesaro.pu.it
PEC: comune.pesaro.demografici@emarche.it

Grazie
Carla Musian

**Comment by MassimoSchiappa** [comment]
Salve,
si tratta in effetti di un errore che ANPR ha derivato dalla banca dati storica Istat (che peraltro pur indicando l'errata denominazione riporta la scansione del Regio Decreto da voi indicato). Provvederemo il prima possibile alla correzione e alla notifica ad Istat dell'errore.
Grazie per la segnalazione.

**Comment by MassimoSchiappa** [comment]
La presente issue viene chiusa. In caso di ulteriori problemi si prega di riaprirne una nuova issue facendo riferimento a questa stessa.
Cordiali saluti.
