### ISSUE TITLE
[N000] Verifica firma sulle notifiche

### ISSUE THREAD

**Issue by Antonino09** [italia/anpr#959]
Buonasera,
qualcuno potrebbe darmi indicazioni su come effettuare alla validazione della firma delle notifiche.

**Comment by gife67** [comment]
Buongiorno,
la verifica della firma fa parte dello standard xml-signature, dipende da quale implementazione utilizza ed in quale linguaggio. In ambito Java, ogni application server ha la sua implementazione di JAX-WS, inoltre esistono altri framework tra cui Apache CXF. Sicuramente esistono implementazioni in altri linguaggi (.NET, PHP etc). Le consiglio di consultare la documentazione in base alla tecnologia utilizzata nella sua implementazione dell'endpoint di ricezione delle notifiche.

**Comment by Antonino09** [comment]
Buongiorno,
io utilizzo come linguaggio C# e l'implementazione che utilizzo per la verifica della signature xml è quella standard definita da microsoft. Tuttavia l'esito della verifica è sempre negativo.
Le allego il messaggio del quale effettuo la verifica e il link al quale è possibile recuperare l'implementazione della verifica della signature.
https://docs.microsoft.com/it-it/dotnet/standard/security/how-to-verify-the-digital-signatures-of-xml-documents
[Message.txt](https://github.com/italia/anpr/files/2619409/Message.txt)

**Comment by gife67** [comment]
.
