### ISSUE TITLE
[Test 5001]  Elenco anomalia dopo rettifica relazione di parentela

### ISSUE THREAD

**Issue by DomenicoGallo** [italia/anpr#96]
Buongiorno, 
siamo riusciti, con esito positivo, ad effettuare una rettifica di relazione di parentela per il Comune di Cittanova, ambiente di test (idOperazione 3003).
Consultando la scheda individuale del cittadino, la relazione di parentela risulta modificata, ma è ancora presente l'anomalia nell'elenco degli Errori/Anomalie. E' normale che sia ancora presente nell'elenco?

Grazie anticipatamente.
Cordiali Saluti

Domenico Gallo
KIBERNETES S.R.L.

**Comment by gcarbonin** [comment]
Si riferisce all'elenco delle anomalie del subentro? se è così, quell'elenco è una fotografia al momento del subentro che non viene aggiornata dalle operazioni effettuate successivamente.

**Comment by DomenicoGallo** [comment]
No, mi riferisco all'elenco delle anomalie della scheda individuale.

**Comment by gcarbonin** [comment]
E' la stessa cosa: si tratta delle anomalie del subentro. Modifichiamo l'etichetta della pagina WEB e precisiamo meglio nelle specifiche

**Comment by DomenicoGallo** [comment]
Ok, la ringrazio per il chiarimento.
Buona giornata.

Domenico Gallo
KIBERNETES S.R.L.
