### ISSUE TITLE
Errore EF044 EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata

### ISSUE THREAD

**Issue by Finalmentesubentrati** [italia/anpr#960]
Abbiamo l'errore in oggetto in relazione ad un pratica di cambio di indirizzo intero nucleo.
Abbiamo verificato le parentele ma pare che siano registrate correttamente.
Codice famiglia ANPR 9070573.
Grazie.

**Comment by rvinzani** [comment]
Può inviarci l'idANPR dell'operazione che le ha restituito l'errore?

**Comment by eleonora1991** [comment]
Abbiamo riscontrato il medesimo errore (EF044 - I soggetti devono appartenere alla stessa famiglia dichiarata) in relazione ad un pratica di cambio di indirizzo intero nucleo di soggetti già residenti nel nostro Comune.
Le parentele sono registrate correttamente.
Codice famiglia ANPR 32199723
Grazie.
