### ISSUE TITLE
L'operazione da annullare non è l'ultima per il soggetto/i o per le famiglie movimentate dall'operazione stessa;

### ISSUE THREAD

**Issue by ale-magna** [italia/anpr#962]
comune di Scandicci (FI)  ambiente di produzione

cercando di annullare una operazione di mutazione residenza apr (idanpr 29823285) di un soggetto omonimo - errore materiale dell'operatore, si ha il problema in oggetto ,
ho provato ad annullare l'operazione successiva sulla famiglia (idanpr 29826081) che è corretta ma che dovrebbe essere la pratica che blocca l'altra, ma ho lo stesso messaggio,
potete controllare quale operaizone blocca il ripristino e come posso correggere la situazione?
grazie dell'attenzione

**Comment by frmariani** [comment]
la seconda operazione, idanpr=29826081, movimenta un'altra famiglia, su cui successivamente alla mutazione di residenza, è stata effettuata una mutazione famiglia convivenza (tipo mutazione 2 composizione scheda);
nell'ordine, le operazioni da annullare sono:
31549091
29826081
29823285

**Comment by frmariani** [comment]
come dicevo è una mutazione famiglia convivenza tipo mutazione 2, composizione scheda, effettuata dal comune di Firenze;
mi scriva i suoi riferimenti in privato per favore
 frmariani@sogei.it
