### ISSUE TITLE
Stato Libero per cittadino AIRE

### ISSUE THREAD

**Issue by RBiasi** [italia/anpr#963]
Buongiorno dal Comune di Cagliari.

Il comune chiede perché non sia possibile rilasciare certificato di stato libero ANPR per cittadino AIRE, tra l'altro espatriato il mese scorso.

Attendiamo indicazioni.

Grazie

Roberta Biasi
Enterprise Solution Consultant
Solutions Operations & Capabilities Development-Nord & Centro
Dedagroup Public Sector & Utilities

**Comment by ncapozzi** [comment]
Buongiorno,
le tipologie di certificato rilasciate da ANPR per i cittadini AIRE sono state concordate con il Ministero dell'Interno in accordo con la norma vigente (Legge 27 ottobre 1988, n.470 art. 7).
