### ISSUE TITLE
Problema nella dashboard. Marcatore con dati errati

### ISSUE THREAD

**Issue by Spartachetto** [italia/anpr#965]
Spero di segnalare nel posto giusto.

Consultando la dashboard su ANPR inserita nella pagina https://teamdigitale.governo.it/it/projects/anpr.htm riscontro un curioso errore.

Nella mappa _Comuni in Presubentro_ è visibile un marcatore al centro del territorio del comune di Roma. Cliccandoci sopra però i dati riportati sono quelli del comune di  NOCCIANO in provincia di PESCARA.

Ho provato a verificare i dati di altri marcatori e mi sembrano corretti

**Comment by mccalv** [comment]
Grazie per la segnalazione @Spartachetto, sicuramente é un BUG, stiamo comunque per rilasciare una nuova versione delle dashboard che superi i problemi attuali dello strumento Metabase che tra le altre cose ha una limitazione di 1000 punti visualizzatili sulla mappa (sia in presubentro che subentro)
