### ISSUE TITLE
Iscrizione Famiglia + Nascita + Ripristino Anagrafico - Chiarimenti

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#966]
vorrei porre alla vostra attenzione questo specifico caso che si sta verificando da un cliente.

in agosto immigra da comune non subentrato una famiglia di due componente (IS + Figlio)
in ottobre viene inserito per nascita un secondo Figlio (nato nel comune) a motivo della residenza della madre.
in novembre, causa accertamenti negativi legati alla pratica migratoria, l'iscrizione di agosto deve essere annullata, ed lo stato civile invierà l'atto di nascita, ai fini della trascrizione, nel comune di provenienza della madre.

la richiesta di chiarimenti è volta a capire come gestire l'evento "nascita"...
nel caso specifico, il comune di provenienza non è ancora subentrato, come suggerite di procedere?
- deve essere annullato? con o senza attivazione del flag annullamentoAttribuzione...?
- oppure può essere utilizzato anche un servizio di cancellazione. anagrafica? 
in questo secondo caso, al momento del subentro, l'altro comune riuscirà a caricare il soggetto con motivo di iscrizione "nascita"?

grazie
Alessandro Monopoli ADS

**Comment by gcarbonin** [comment]
L’iscrizione per nascita NON deve essere annullata; 
deve utilizzare il servizio di cancellazione per altri motivi, con motivazione cancellazione 12 – Ripristino posizione precedente, per ciascun componente della famiglia.
Le ricordo che l’annullamento attribuzione del Codice Fiscale, è permesso soltanto entro le 24 ore dall’emissione dello stesso in caso di errore materiale.
Al momento del subentro, l’altro Comune,  non avrà alcun problema.

**Comment by AMonopoliADS** [comment]
Perfetto. Grazie del riscontro.

In effetti è la strada che avevamo deciso di seguire con il cliente.

Ma eravamo frenati da questo secondo dubbio:
Se la migrazione di agosto fosse avvenuta "da comune subentrato"... la cancellazione della nascita di ottobre, non bloccherebbe l'annullamento con ripristino della mutazione?

Grazie
