### ISSUE TITLE
Rigetto di cambio indirizzo a cavallo del subentro - problemi con le decorrenze

### ISSUE THREAD

**Issue by busaster** [italia/anpr#967]
Ambiente di test, comune di Poggio a Caiano, Data subentro in test : 24/10/2017

Ho una famiglia di 4 persone : IS,moglie,due figli.
Questa famiglia ha avuto un cambio di indirizzo con decorrenza antecedente al subentro (04/07/2017).
Dopo il subentro si vuole annullare questo cambio di indirizzo.
La procedura da seguire è : chiamare il servizio 5001 con i dati del precedente indirizzo e tipoMutazione 6 (Ripristino residenza ante subentro).
Nel caso in questione, 3 dei 4 componenti sono residenti al vecchio indirizzo dal 09/08/2011 mentre il quarto è nato il 13/04/17 per cui era residente da quella data.

Ora se chiamo il 5001 come sopra descritto ottengo l'errore "Data decorrenza residenza  minore della data di prima iscrizione del soggetto", immagino riferito al figlio nato successivamente (ID operazione ANPR 18779574)

In questi casi come ci dovremmo comportare ? Non mi pare corretto inviare la richiesta con la data di nascita del figlio, dichiarerei un dato errato per gli altri componenti.

Grazie

Gianrico Busa
Maggioli Spa

**Comment by azabatta** [comment]
Buongiorno, 
stiamo verificando come è opportuno gestire questa casistica. La informeremo appena sarà possibile riprovare.  
Grazie per la segnalazione

**Comment by azabatta** [comment]
La funzionalità è stata modificata per gestire correttamente la casistica segnalata. 
E' possibile inviare nuovamente la stessa richiesta (con la data di decorrenza ante subentro effettiva).
Restiamo in attesa di un cortese riscontro.

**Comment by busaster** [comment]
Ho riprovato ad eseguire la stessa chiamata , ora ottengo "EN416 : L'operazione di ripristino residenza e' consentita soltanto a valle del subentro", ID op ANPR 18873937

**Comment by azabatta** [comment]
Buongiorno, 
mi scuso per il ritardo con cui la contatto nuovamente.
Abbiamo ricontrollato le date di rilascio dell'intervento:  è stato esteso successivamente alla sua prova. 
Le chiedo cortesemente di riprovare.
Grazie

**Comment by busaster** [comment]
pratica chiusa con successo.
Grazie
