### ISSUE TITLE
[6001] Certificazione esenzione 'ALTRO MOTIVO DI ESENZIONE' 

### ISSUE THREAD

**Issue by SAlberto** [italia/anpr#968]
Buongiorno,
volevo chiedere un'informazione:
alcuni comuni ci stanno facendo notare che la "descrizione esenzione bollo", il campo aggiuntivo associato all'esenzione "Altro Motivo di Esenzione", non compare nella stampa del certificato.

E' corretto che non debba uscire, potete verificare?

Ringrazio anticipatamente.

**Comment by SAlberto** [comment]
Chiedo scusa, ma quindi il campo "descrizione esenzione bollo" a cosa serve?

**Comment by gcarbonin** [comment]
Per monitorare i motivi diversi da quelli standard previsti in modo da poter aggiornare, in prospettiva, la tabella dei motivi standard
