### ISSUE TITLE
[ws TEST] msg. "Rejected by policy (from client)"

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#970]
ambiente di TEST - comune di FAENZA (RA)

è da 2 giorni che riceviamno in risposta 
```
<env:Fault>
  <faultcode>env:Client</faultcode>
  <faultstring>Rejected by policy. (from client)</faultstring>
</env:Fault>
```

le impostazioni locali non sono modificate.
è possibile che sia cambiata qualche configurazione lato ANPR o lato autorizzazioni utenti?

grazie.
Alessandro Monopoli ADS

**Comment by mttfranci** [comment]
Buongiorno, il problema si verifica per qualsiasi operazione?
Avete verificato la data/ora di sistema del client? (anche piccoli disallineamenti possono portare all'errore da voi descritto).

Inoltre potreste confermarci :
Il codice del certificato utilizzato (es. 039010-CO-0000 o 039010-PC-0001)
Data e ora di un operazione.

Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
buongiorno Matteo.

l'errore si verifica, in ambiente di TEST, su tutte le operazioni.
le stesse impostazioni (comprese data/ora del client) non danno problemi nell'invocazione dei ws in ambiente di PRE-SUB.
il certificato utilizzato è 039010-PC-0002

due esempi di comunicazioni appena inviati:
idOperazioneComune 2018302873 delle 8:58
idOperazioenComune 2018302874 delle 8:59

**Comment by mttfranci** [comment]
Potreste verificare che non stiate usando un certificato di produzione invece di quelli di test (che dovrebbe essere del tipo 039010-CO-0000)?
Grazie in anticipo

**Comment by mttfranci** [comment]
Va bene, ci aggiorniamo a domani.
Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
abbiamo messo in linea il certificato 039010-CO-0000
il problema persiste (es. idOperazioneANPR 2018302886)

eseguendo lo switch nell'ambiente di pre-sub (con conseguente dirottamento degli url dei servizi...) il certificato CO-0000 è funzionante.

**Comment by mttfranci** [comment]
In test comuni è corretto usare il certificato 039010-CO-0000.
Saluti

Assistenza ANPR

**Comment by AMonopoliADS** [comment]
scusami Matteo... forse non è arrivato il messaggio che in ambiente di TEST il problema persiste anche con il certificato di tipo CO
(ho indicato anche l'idOperazioneComune dell'ultimo tentativo che ha dato errore)

**Comment by AMonopoliADS** [comment]
in qualità di ente sperimentatore, l'ambiente di test è stato avviato quando ancora non esistevano le utenze COMUNETESTxxxxxx.
al tempo sono state assegnate delle utenze di test con dei codici fiscali specifici collegati agli utenti, e stiamo utilizzando quelli.
posso mandare alla tua mail i codici fiscali che utilizziamo (che funzionano su pre-subentro) e che funzionavano anche su test

**Comment by AMonopoliADS** [comment]
con l'utenza COMUNETEST039010, i web-service in ambiente di test sono funzionanti.

a cavallo del 28/11 (ultimo giorno in cui hanno funzionato le altre utenze) è stato probabilmente eseguita una disabilitazione degli altri utenti - oppure sono "scaduti"... - questo probabilmente lo sapete meglio voi.

in ogni caso, l'importante è che abbiamo risolto.

piuttosto, faccio presente che le utenze "personali" sono comunque ancora funzionanti in ambiente di pre-subentro.
verranno bloccate anche lì?
giusto x essere preparati... grazie

**Comment by mttfranci** [comment]
Per quanto riguarda le utenze personali, verificheremo.
Comunque l'indicazione è di usare l'utenza COMUNETEST con il certificato XXXXXX-CO-0000 per tutti gli ambienti a parte produzione.
