### ISSUE TITLE
WS - PRE_SUB: Errore "unable to get certificate CRL (from client)"

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#971]
Buon giorno,
espongo una problematica che stiamo riscontrando con i nostri clienti pre-subentrati, con cui vorremmo condurre come da indicazioni, una serie di test funzionali in ambiente PRE_SUB prima di procedere al subentro. 
In particolare il comune di Loreto Aprutino (PE), pre-subentrato in data 14/11, ha eseguito tutte le operazioni relative alla sicurezza e alla configurazione delle postazioni, ed ha infine scaricato i certificati di postazione necessari per operare in modalità Web Services.
Abbiamo quindi effettuato un primo test di connessione, sia in ambiente di test che di pre-subentro, utilizzando i suddetti certificati, ma otteniamo in risposta un Fault "_unable to get certificate CRL (from client)_". Per il test, effettuato dalla postazione certificata del cliente, abbiamo utilizzato sia il client messo da voi a disposizione negli strumenti di supporto, sia un nostro client che simula le chiamate che effettuiamo dalla procedura, e con entrambi otteniamo la stessa risposta. Non abbiamo avuto questo problema nei test con i certificati analoghi che ci ha fornito il comune di Teramo, che è a sua volta pre-subentrato in data 28/11 e con cui stiamo conducendo tuttora i test di funzionamento propedeutici al subentro.
Vi inviamo contestualmente all'indirizzo _segnalazioni-anpr@teamdigitale.governo.it_ le request prodotte con i test di connessione, effettuati come detto dalla postazione certificata dell'ente, rispettivamente il file message.out.xml per la request effettuata dal vostro client, e signedRequestConnessione.xml per la request generata dal nostro client, chiedendovi cortesemente nel caso, di darci indicazione se ci sono evidenze di errori nella composizione della nostra request, o se potrebbe trattarsi di qualche causa legata alla configurazione della postazione, alla validità del certificato (che inviamo altresì in allegato) o a una nostra errata interpretazione di qualche specifica.

In attesa di riscontro, cordiali saluti

Giuseppe Mucciarelli

TINN srl

**Comment by mttfranci** [comment]
Buongiorno, stiamo verificando.

**Comment by mttfranci** [comment]
Salve, potreste verificare se per caso state costruendo le richieste con un certificato rilasciato per l'ambiente di produzione, invece che per l'ambiente di presubentro?
Grazie in anticipo.

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo verificato col cliente che i certificati che ci ha fornito sono quelli che ci ha detto di aver scaricato dalla console di sicurezza all'url _https://dp.anpr.interno.it/com_, dopo aver eseguito il censimento delle postazioni e le altre operazioni e configurazioni relative alla sicurezza, quindi dovrebbe trattarsi dei certificati che poi saranno utilizzati per il subentro (uno di questi è il certificato che vi abbiamo inviato via mail all'indirizzo _segnalazioni-anpr@teamdigitale.governo.it_ in correlazione con l'issue, che potete nel caso verificare). Possiamo richiedervi direttamente noi i certificati per poter effettuare una serie di test in ambiente PRE_SUB con il cliente, o la richiesta deve essere fatta dall'ente?
Grazie, cordiali saluti.

**Comment by mttfranci** [comment]
Salve.
Il certificato per presubentro è lo stesso di test comuni e dovrebbe avere il formato XXXXXX-CO-0000 (dove XXXXXX è il codice istat del comune).
Se non lo avete già, potete richiederlo al comune, dato che dovrebbero averlo ricevuto all'indirizzo PEC che avevano indicato.
Saluti

Assistenza ANPR

**Comment by mttfranci** [comment]
In ambiente di test comuni e presubentro dovrebbe essere possibile eseguire anche l'accesso all'applicazione web con il certificato XXXXXX-CO-0000 e le credenziali del corrispondente utente COMUNETESTXXXX.
Potete dirci alcuni dei comuni con cui avete il problema?

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo capito il problema, abbiamo recuperato dall'ente la PEC con cui è stato inviato il certificato XXXXXX-CO-0000.p12 da voi indicato, dove è specificato che per l'accesso agli ambienti TEST e PRESUBENTRO di ANPR, in modalità WS, è necessario utilizzare il PIN del certificato di postazione (e non la password che l'ente ha utilizzato per l'accesso alla Web Application). Modificata la configurazione, siamo riusciti ad effettuare il test di connessione e ora procederemo con i test di integrazione indicati nel piano da voi pubblicato.
Grazie per il supporto, 
cordiali saluti.

Giuseppe Mucciarelli, TINN srl

**Comment by mttfranci** [comment]
Prego.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti
Assistenza ANPR
