### ISSUE TITLE
Toponimo errato al subentro

### ISSUE THREAD

**Issue by cvignati** [italia/anpr#972]
Buongiorno,
se in fase si subentro è stata caricata la descrizione di un toponimo errata, com'è possibile sistemarla?

Grazie

**Comment by amollicone1982** [comment]
In attesa della rettifica dell'indirizzo, è necessario inviare una pec con indicazione dell'idFamiglia anpr e del toponimo corretto.
Se il caso riguardo un numero ragguardevole di casi è possibile generare un tracciato:

idFamigliaAnpr;idFamigliaComune;toponimo

contenente le informazione per la correzione del problema. Tale tracciato deve essere inviato sempre tramite pec

**Comment by cvignati** [comment]
> 
> 
> In attesa della rettifica dell'indirizzo, è necessario inviare una pec con indicazione dell'idFamiglia anpr e del toponimo corretto.
> Se il caso riguardo un numero ragguardevole di casi è possibile generare un tracciato:
> 
> idFamigliaAnpr;idFamigliaComune;toponimo
> 
> contenente le informazione per la correzione del problema. Tale tracciato deve essere inviato sempre tramite pec

Buonasera,
potrebbe indicarmi la mail pec dove indirizzare la richiesta?
Indico solo il toponimo corretto, senza civico ne esponente?
Come formato file va bene CSV? Deve essere firmato digitalmente?

Grazie

**Comment by amollicone1982** [comment]
La pec è Assistenza.anpr@pec.sogei.it ed il file non deve essere firmato digitalmente.
Va bene il formato csv indicando solo il toponimo in quanto se non ho capito male civico ed esponente sono corretti. Tale modifica avrà effetto su AE ma non su inps e motorizzazione

**Comment by cvignati** [comment]
> 
> 
> La pec è [Assistenza.anpr@pec.sogei.it](mailto:Assistenza.anpr@pec.sogei.it) ed il file non deve essere firmato digitalmente.
> Va bene il formato csv indicando solo il toponimo in quanto se non ho capito male civico ed esponente sono corretti. Tale modifica avrà effetto su AE ma non su inps e motorizzazione

Pec inviata. Potrei avere una tempistica sull'esecuzione della rettifica?
Il subentro con la descrizione sbagliata potrebbe aver intaccato altre banche dati oltre ad AE (Es. INPS e Motorizzazione)

Grazie

**Comment by amollicone1982** [comment]
Update è stato eseguito. Non ha intaccato altre banche dati oltre ad AE

**Comment by cvignati** [comment]
Perfetto, ho già controllato alcune famiglie e sono corrette.

Grazie per la celerità

**Comment by cvignati** [comment]
Buongiorno,
ho fatto una verifica in AE su alcuni nominativi, ma purtroppo riportano ancora la descrizione via errata

**Comment by cvignati** [comment]
> Abbiamo inviato la comunicazione ad AE. I tempi di AE sono un po' piu' lunghe in quanto devono effettuare delle verifiche

Buongiorno, ad oggi in AE la denominazione della via risulta ancora sbagliata

**Comment by amollicone1982** [comment]
Abbiamo sollecitato Agenzia entrate che ci ha comunicato che sta effettuando dei controlli sugli indirizzi.
