### ISSUE TITLE
[5005] trasferimento in nuova famiglia a stesso indirizzo

### ISSUE THREAD

**Issue by busaster** [italia/anpr#973]
Ambiente di produzione, comune di Carrara

con l'operazione ID ANPR 35907619 il cliente vuole trasferire in una nuova famiglia una persona che oggi risiede in famiglia con 3 componenti, mantenendo però invariato l'indirizzo di residenza.

ANPR risponde però con l'errore EN388 "La residenza inserita risulta uguale a quella attuale".

Mi sembrava che questo tipo di operazioni fossero permesse, è cambiato qualcosa ?

Grazie

Gianrico Busa
Maggioli Spa

**Comment by frmariani** [comment]
Deve inserire l'informazione di Famiglia Coabitante

**Comment by frmariani** [comment]
Oppure il Forza Operazione nella lista controlli dei servizi 5001/5005
<listaControlli>
             <controllo>
                  <codice>FO</codice>
                  <valore>S</valore>
               </controllo>
</listaControlli>
