### ISSUE TITLE
[5008] problemi con inserimento matrimonio aire

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#974]
Ho eseguito una Mutazione A006 e contemporaneamente voglio eseguire una mutazione di stato civile (Matrimonio) passando i dati dello stesso e lo stato civile coniugato usando il servizio 5008.

come risultato ottengo un  soapfault exception.
Questa è la mia richiesta :
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Richiesta5008 xmlns:ns2="http://sogei.it/ANPR/5000mutazione">
    <testataRichiesta>
        <idOperazioneComune>1157</idOperazioneComune>
        <codMittente>076063</codMittente>
        <codDestinatario>ANPR01</codDestinatario>
        <operazioneRichiesta>5008</operazioneRichiesta>
        <dataOraRichiesta>2018-11-30T16:52:24.665+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>TEST</tipoInvio>
        <dataDecorrenza>2018-11-29+01:00</dataDecorrenza>
        <nomeApplicativo>DEMOGRAFICIWEB</nomeApplicativo>
        <versioneApplicativo>1.0.0</versioneApplicativo>
        <fornitoreApplicativo>Publisys S.p.A.</fornitoreApplicativo>
    </testataRichiesta>
    <generalitaPerRicerca>
        <idSchedaSoggettoANPR>22983454</idSchedaSoggettoANPR>
    </generalitaPerRicerca>
    <statoCivile>
        <statoCivile>2</statoCivile>
    </statoCivile>
    <matrimonio>
        <coniuge>
            <codiceFiscale>
                <codFiscale>xxxxxxxxxxxxxx</codFiscale>
            </codiceFiscale>
            <cognome>cognome</cognome>
            <nome>nome</nome>
            <sesso>F</sesso>
            <dataNascita>1960-11-30+01:00</dataNascita>
            <luogoNascita>
                <comune>
                    <nomeComune>ALMESE</nomeComune>
                    <codiceIstat>001006</codiceIstat>
                    <siglaProvinciaIstat>TO</siglaProvinciaIstat>
                </comune>
            </luogoNascita>
            <soggettoAIRE>S</soggettoAIRE>
            <idSchedaSoggettoComune>
                <idSchedaSoggettoComuneIstat>076063</idSchedaSoggettoComuneIstat>
                <idSchedaSoggetto>484683</idSchedaSoggetto>
            </idSchedaSoggettoComune>
        </coniuge>
        <cittadinanza>
            <descrizioneStato>ITALIA</descrizioneStato>
            <codiceStato>100</codiceStato>
            <dataValidita>1947-08-26+02:00</dataValidita>
        </cittadinanza>
        <datiMatrimonio>
            <dataEvento>2000-11-20+01:00</dataEvento>
            <luogoEvento>
                <comune>
                    <nomeComune>MILANO</nomeComune>
                    <codiceIstat>015146</codiceIstat>
                    <siglaProvinciaIstat>MI</siglaProvinciaIstat>
                </comune>
            </luogoEvento>
            <attoEvento>
                <comuneRegistrazione>
                    <nomeComune>MILANO</nomeComune>
                    <codiceIstat>015146</codiceIstat>
                    <siglaProvinciaIstat>MI</siglaProvinciaIstat>
                </comuneRegistrazione>
                <anno>2000</anno>
                <parte>I</parte>
                <numeroAtto>1</numeroAtto>
                <dataFormazioneAtto>2000-11-20+01:00</dataFormazioneAtto>
                <trascritto>0</trascritto>
            </attoEvento>
        </datiMatrimonio>
        <ordineMatrimonio>1</ordineMatrimonio>
    </matrimonio>
    <datiControllo>
        <tipoMutazione>12</tipoMutazione>
        <gestioneCF>3</gestioneCF>
        <listaControlli>
            <controllo>
                <codice>CL</codice>
                <valore>N</valore>
            </controllo>
        </listaControlli>
    </datiControllo>
</ns2:Richiesta5008>
```

Codice istat 076063
Ambiente di TEST

**Comment by mcaputo75** [comment]
ok grazie risolto per l'invio del matrimonio .
Ora però contemporaneamente vorrei modificare anche lo stato civile , quindi far diventare coniugato/a il soggetto .

Questa è la richiesta 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Richiesta5008 xmlns:ns2="http://sogei.it/ANPR/5000mutazione">
    <testataRichiesta>
        <idOperazioneComune>1190</idOperazioneComune>
        <codMittente>076063</codMittente>
        <codDestinatario>ANPR01</codDestinatario>
        <operazioneRichiesta>5008</operazioneRichiesta>
        <dataOraRichiesta>2018-12-03T17:40:09.630+01:00</dataOraRichiesta>
        <tipoOperazione>C</tipoOperazione>
        <tipoInvio>TEST</tipoInvio>
        <dataDecorrenza>2018-12-03+01:00</dataDecorrenza>
        <nomeApplicativo>DEMOGRAFICIWEB</nomeApplicativo>
        <versioneApplicativo>1.0.0</versioneApplicativo>
        <fornitoreApplicativo>Publisys S.p.A.</fornitoreApplicativo>
    </testataRichiesta>
    <generalitaPerRicerca>
        <codiceFiscale>
            <codFiscale>xxxx</codFiscale>
        </codiceFiscale>
        <cognome>xxx</cognome>
        <nome>xxxx</nome>
        <sesso>F</sesso>
        <dataNascita>1931-10-01+01:00</dataNascita>
        <luogoNascita>
            <comune>
                <nomeComune>POTENZA</nomeComune>
                <codiceIstat>076063</codiceIstat>
                <siglaProvinciaIstat>PZ</siglaProvinciaIstat>
            </comune>
        </luogoNascita>
        <idSchedaSoggettoANPR>22983448</idSchedaSoggettoANPR>
    </generalitaPerRicerca>
    <statoCivile>
        <statoCivile>2</statoCivile>
    </statoCivile>
    <matrimonio>
        <coniuge>
            <codiceFiscale>
                <codFiscale>xxxxx</codFiscale>
            </codiceFiscale>
            <cognome>xxx</cognome>
            <nome>xxxx</nome>
            <sesso>M</sesso>
            <dataNascita>1983-11-23+01:00</dataNascita>
            <luogoNascita>
                <comune>
                    <nomeComune>POTENZA</nomeComune>
                    <codiceIstat>076063</codiceIstat>
                    <siglaProvinciaIstat>PZ</siglaProvinciaIstat>
                </comune>
            </luogoNascita>
            <soggettoAIRE>S</soggettoAIRE>
            <idSchedaSoggettoComune>
                <idSchedaSoggettoComuneIstat>076063</idSchedaSoggettoComuneIstat>
                <idSchedaSoggetto>33829</idSchedaSoggetto>
            </idSchedaSoggettoComune>
        </coniuge>
        <cittadinanza>
            <descrizioneStato>ITALIA</descrizioneStato>
            <codiceStato>100</codiceStato>
            <dataValidita>1931-10-01+01:00</dataValidita>
        </cittadinanza>
        <datiMatrimonio>
            <dataEvento>2018-11-27+01:00</dataEvento>
        </datiMatrimonio>
        <ordineMatrimonio>1</ordineMatrimonio>
    </matrimonio>
    <datiControllo>
        <tipoMutazione>12</tipoMutazione>
        <tipoMutazione>?</tipoMutazione>
        <gestioneCF>3</gestioneCF>
        <listaControlli>
            <controllo>
                <codice>CL</codice>
                <valore>N</valore>
            </controllo>
        </listaControlli>
    </datiControllo>
</ns2:Richiesta5008>

```
Oltre al tipo di mutazione 12 "Matrimonio" , per modificare anche lo stato civile quale codice mutazione dovrei utilizzare?
Grazie in anticipo.

**Comment by mttfranci** [comment]
Per lo stato civile va usato il tipo mutazione 01 - Dati   anagrafici / Codice fiscale (vedi tabella 36).

Per il tipo mutazione 01 vanno sempre passate anche le generalitDaModificare complete, anche se si intende modificare solo lo stato civile (altrimenti si attiva il controllo EN139).

Ecco un esempio : 

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<generalitaDaModificare>
        <generalita xsi:type="ns4:tipoGeneralita" xmlns:ns4="http://sogei.it/ANPR/vocabolario5000mutazione" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <codiceFiscale>
                <codFiscale>TSTNUO00A41A083H</codFiscale>
                <validitaCF>1</validitaCF>
                <dataAttribuzioneValidita>2018-03-26</dataAttribuzioneValidita>
            </codiceFiscale>
            <cognome>TEST MUTAZIONE</cognome>
            <nome>UNO</nome>
            <sesso>F</sesso>
            <dataNascita>2000-01-01</dataNascita>
            <luogoNascita>
                <comune>
                    <nomeComune>AGORDO</nomeComune>
                    <codiceIstat>025001</codiceIstat>
                    <siglaProvinciaIstat>BL</siglaProvinciaIstat>
                </comune>
            </luogoNascita>
            <soggettoAIRE>N</soggettoAIRE>
            <idSchedaSoggettoANPR>260185</idSchedaSoggettoANPR>
        </generalita>
        <attributiSoggetto>
            <senzaFissaDimora>N</senzaFissaDimora>
            <soggettoCertificabile>2</soggettoCertificabile>
        </attributiSoggetto>
    </generalitaDaModificare>
    <statoCivile>
        <statoCivile>2</statoCivile>
        <statoCivileND>N</statoCivileND>
    </statoCivile>
    <datiControllo>
        <tipoMutazione>01</tipoMutazione>
        <gestioneCF>3</gestioneCF>
        <listaControlli>
            <controllo>
                <codice>CL</codice>
                <valore>N</valore>
            </controllo>
        </listaControlli>
    </datiControllo>`


Cordiali saluti

Assistenza ANPR

**Comment by mcaputo75** [comment]
Problema Risolto.
Grazie Mille.

**Comment by mttfranci** [comment]
Prego

**Comment by Jamison1000** [comment]
Saluti a tutti.

  Sono qui per condividere una breve testimonianza al mondo su come il dottor Okosu mi aiuti a riavere mia moglie. Ho amato molto mia moglie
 ma lei ha dato per scontato il mio amore e ha deciso di andarsene. è andata a divorziare. Sconosciuto per me che stava vedendo un altro
l'uomo già Ma poi ho scoperto e non è stato davvero facile per me. Era troppo tardi perché lei se n'è già andata. Ho provato molti mezzi per riaverla ma inutilmente. Fino a quando ho incontrato Dr Okosu su internet ho visto diverse testimonianze su come ha aiutato diverse persone con i loro problemi. Quindi ho deciso di contattarlo. Sono felice che oggi sia riuscito a riavere mia moglie e il mio matrimonio sia felice ora che mia moglie ora mi ama di più e svolge il suo dovere come dovrebbe essere una buona moglie.

    Questa è una delle mie promesse a te, Sir Okosu, in quanto ho promesso di condividere al mondo le tue buone opere. Puoi anche contattarlo per qualsiasi tipo di aiuto. Aiuto coniugale, aiuto nella relazione, vincere una lotteria, problemi di salute. Ecco la sua email:

drokosu01@gmail.com

Per favore aiuta a condividere questa testimonianza in quanto può essere utile alle persone intorno a te .. Grazie e Dio benedica mentre condividi.
