### ISSUE TITLE
Nome traslitterato

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#978]
Produzione, idANPR 23988819.
La persona con questo id ha nome NICOLO' MARIA.
La WA mostra i dati traslitterati nel formato NICOLO MARIA.
A me pare un difetto dell'algoritmo di traslitterazione, e suppongo di conseguenza riceviamo un "Incongruenza dati anagrafici: il nome del soggetto non coincide con quello specificato nella richiesta".
Grazie
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
RETTIFICA
Chiedo scusa l'idANPR citato sopra è in ambiente di test
Situazione equivalente, con altro id, c'è in produzione.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Possiamo avere l'id dell'operazione che le ha restituito questo errore?

**Comment by rvinzani** [comment]
Il soggetto è presente in ANPR con il nome NICOLÒ (traslitterato NOCCOLO) quindi NOCCOLO' (con l'apostrofo) non è riconosciuto

**Comment by bfilipazzi** [comment]
Da specifiche NICOLÒ si traslittera NICOLO' con l'apostrofo finale.
Seguono ad esempio 3 id ANPR di persone con nome NICOLÒ traslitterato NICOLO' (ambiente di test)
9389593,
9376156,
9392207

quest'altro id ANPR
9387654 
ha nome NICOLO' LUIGI traslitterato NICOLO' LUIGI.

Il soggetto che ha innescato questa issue invece è stato trascodificato senza l'apostrofo conclusivo e mi pare costituisca un'eccezione. Grazie.
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Ho sbagliato usando esempi non adatti e ripropongo un esempio in ambiente di test.

L'operazione ANPR 18796708 restituisce la consultazione di persona con questi dati   
                  
<nome>NICOLÒ</nome>

<nomeTranslitterato>NICOLO'</nomeTranslitterato>


e l'operazione ANPR 18796690 restituisce

<nome>NICOLÒ MARIA</nome>

<nomeTranslitterato>NICOLO MARIA</nomeTranslitterato>

le specifiche in documentazione dicono che Ò si traslittera O, eccetto quando è in fine di parola nel qual caso si traslittera O'.
A mio avviso NICOLÒ andrebbe traslitterato NICOLO' in ogni caso.
Grazie.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Nell'operazione 18796690 la richiesta è effettuata tramite idANPR e restituisce come per il soggetto con idANPR 23988819 NICOLÒ  e NICOLO (traslitterato)

**Comment by bfilipazzi** [comment]
Incollo frammenti dell'XML di consultazione di NICOLÒ traslitterato NICOLO' in ambiente di test.
idOperazioneANPR 18796708
idSchedaSoggettoANPR 24016594
                    nome>NICOLÒ</nome
                    nomeTranslitterato>NICOLO'</nomeTranslitterato

Aggiungo frammenti dell'XML di consultazione di NICOLÒ MARIA traslitterato NICOLO MARIA in ambiente di test.
idOperazioneANPR 18796690
idSchedaSoggettoANPR 24016593
                    nome>NICOLÒ MARIA</nome
                    nomeTranslitterato>NICOLO MARIA</nomeTranslitterato

A me sembra che nel secondo caso la parola NICOLÒ sia traslitterata diversamente che nel primo, nel primo Ò diventa O' e nel secondo Ò diventa O.
L'ultima pagina della tabella 40 dice che la vocale Ò con accento in posizione finale si traslittera O'.
L'algoritmo di traslitterazione interpreta diversamente i due casi perché nel secondo la lettera accentata non è alla fine della parola ma non alla fine del nome? 
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Come da specifiche traslitteriamo il carattere Ò in O' solo se tale carattere è alla fine del nome (completo)

**Comment by bfilipazzi** [comment]
Non sarebbe opportuno uniformare il metodo di traslitterazione dei nomi delle persone e quello delle denominazioni dei comuni?.
I due esempi seguenti sono tratti dalla tabella_3_archivio_comuni
  denominazione ALÀ DEI SARDI denominazione traslitterata ALA' DEI SARDI
  denominazione ALÌ TERME denominazione traslitterata ALI' TERME
In questo contesto si usa l'apostrofo anche non è alla fine della denominazione.
Se posso permettermi un'osservazione mi sembra preferibile il metodo applicato per i comuni.
Filipazzi - Maggioli

**Comment by rvinzani** [comment]
Chiudo la issue confermando quanto indicato come regola di traslitterazione. In caso di ulteriori richieste è possibile aprire un'altra issue che faccia riferimento a questa stessa
