### ISSUE TITLE
[N010] Informazioni su dati di emigrazione

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#98]
Pisa, ambiente di test, ID_OPERAZIONE_ANPR 409905

Buongiorno,
per un cittadino di Pisa emigrato in altro comune subentrato riceviamo la notifica di emigrazione N010, ma nei dati di notifica non abbiamo l'indicazione se il soggetto sia stato iscritto in quel comune come residente o come AIRE.
Questa informazione serve soprattutto per capire la tipologia di cancellazione dei cittadini che sono attualmente iscritti all'Aire del comune di Pisa e potrebbero sia rientrare in Italia che essere iscritti all'Aire del comune richiedente.
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
La notifica serve soltanto per dire al comune che deve cancellare la persona dalla sua anagrafe.  Magari telefonicamente cerchiamo di chiarire l'esigenza

**Comment by gcarbonin** [comment]
In questi casi è doveroso interrogare ANPR: tra la cancellazione ed l'eventuale nuovo trasferimento al comune di PISA, la base dati locale di Pisa è sicuramente non aggiornata.
