### ISSUE TITLE
[5008] Mutazione '01' - Errore EC083 su comune registrazione atto di matrimonio

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#981]
ambiente di PRODUZIONE - comune di BELLUNO (BL)

soggetto già presente in ANPR con idSoggettoANPR 34220447
immigrato a Belluno, con provenienza Longarone (subentrato): la mutazione 5005 è andata a buon fine.

in sede di perfezionamento definitivo si tenta di inviare una ws 5008 (idOperazioneComune 2018010254).
l'xml contiene i dati del matrimonio (corrispondenti a quelli presenti in ANPR), ma il matrimonio non è oggetto di mutazione.

il web-service va in errore con questo messaggio:
```
<errore>
  <codiceErroreAnomalia>EC083</codiceErroreAnomalia>
  <tipoErroreAnomalia>E</tipoErroreAnomalia>
  <testoErroreAnomalia>Codice ISTAT del comune di registrazione atto di matrimonio 025071 incongruente con quello presente sulla tabella di riferimento</testoErroreAnomalia>
</errore>
```

ci chiediamo:
perchè viene rilevato come errato il codice ISTAT 025071, se è il codice valido dal 22/02/2014 ed il matrimonio è avvenuto l'08/11/2014?

grazie.
Alessandro Monopoli ADS

**Comment by AMonopoliADS** [comment]
abbiamo inviato con successo la comunicazione.
grazie Matteo

**Comment by mttfranci** [comment]
Prego.
Saluti
Assistenza ANPR
