### ISSUE TITLE
[A006] errata mutazione dati aire su cittadino straniero

### ISSUE THREAD

**Issue by MarcoMigliori** [italia/anpr#982]
Ambiente di produzione, id cittadino 38374069.
Un cittadino in attesa della pratica di cittadinanza jure sanguinis non ancora conclusa, viene erroneamente registrato come aire dal Comune per un errore materiale nell'individuare il cittadino.
Nel momento in cui si fa la registrazione, risulta cittadino brasiliano.
C'è un errore del nostro programma in questo caso, già individuato che andiamo a correggere.
Il motivo per cui scrivo qui, è che ANPR ha accettato la mutazione dati aire (id operazione 35330453) su questo cittadino, pur non italiano.

Sto per fare l'annullamento della operazione errata.

**Comment by ncapozzi** [comment]
Buongiorno,
nel caso in cui vengono richiamati i servizi Aire il sistema considera come già "accertata" dal comune a priori la cittadinanza italiana del soggetto e pertanto, qualora non espressamente dichiarata nella richiesta o non presente nel DB per A006, la inserisce di default. 
Nel casi di A006 con tipo = 1 abbiamo riscontrato un malfunzionamento che provvederemo a risolvere per il quale tale inserimento non viene effettuato.
