### ISSUE TITLE
DATA FORMAZIONE ATTO E COMUNE DI REGISTRAZIONE

### ISSUE THREAD

**Issue by CarlaMusian** [italia/anpr#983]
Si chiede con che data di default viene fatto il controllo EC075 di esistenza alla data del comune di 
registrazione dell'atto (es. nascita) in subentro, in mancanza di questa data,  nel caso in cui l'anno dell'atto 
sia successivo all'anno dell'evento.

Grazie
Carla Musian
Applicativo AscotWeb

**Comment by rvinzani** [comment]
in assenza della data di registrazione viene preso come riferimento, per la verifica del comune, l'anno dell'atto nel range di date 1/1-31/12

**Comment by CarlaMusian** [comment]
E se il comune in questione ha cambiato provincia nel corso dell'anno?
Abbiamo  casi di atti a Pesaro del 1998 quando e' cambiata la sigla della provincia, che vengono segnalati come errati quando potrebbero essere esatti e sembra di capire che il confronto che viene fatto da voi e' al 31/12 perche' altrimenti quello che viene passato sarebbe esatto.

Grazie
Carla Musian

**Comment by MarcoMigliori** [comment]
Mi permetto di intervenire unendomi alla domanda di @CarlaMusian . Sarebbe importante capire il criterio preciso da utilizzare. Anche per applicare correttamente eventuali correzioni massive prima del subentro.

**Comment by rvinzani** [comment]
Nel dettaglio i controlli sul comune di registrazione dell'atto seguono questi criteri:
- Data formazione atto
- Data evento se l’anno dell’evento coincide con anno dell’atto (es data evento 12/06/1983 e anno atto 1983)
- L’anno dell’atto con 31/12 (es. anno atto 1982 diventa 31/12/1982)

**Comment by rvinzani** [comment]
Chiudo la issue. In caso di problemi o ulteriori richieste è possibile aprirne un'altra che faccia riferimento a questa stessa.
