### ISSUE TITLE
[Testata richiesta] - IdOperazioneComune alfanumerico

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr#984]
Buonasera,
sto avendo problemi con questo aggiornamento #814 oppure non ho capito come funziona. 
Adesso dovrebbe essere possibile assegnare valori alfanumerici a "IdOperazioneComune"? Tipo **abc123** ?
In ambiente PROD ricevo l'errore "Formato della stringa di input non corretto." 
Mentre, in PRE_SUB risponde correttamente.

**Comment by mttfranci** [comment]
Il messaggio che avete riportato "Formato della stringa di input non corretto" non sembra tra quelli restituiti da ANPR. Può darsi che eseguiate voi una prevalidazione dal gestionale?
Vediamo anche ora registrate in ingresso IdOperazioneComune alfanumerici inviati da alcuni comuni in produzione.
Potete fornirci una testata completa che presenta problema? (così da verificare dataOra richiesta, comune, idoperazione ecc).

**Comment by Eduardo1977** [comment]
Grazie per il riscontro. Dipende sicuramente dalla versione del nostro gestionale che non aveva ancora l'aggiornamento sul tipo string.

**Comment by mttfranci** [comment]
Prego.

Assistenza ANPR
