### ISSUE TITLE
[6001] Errore EN470 - certificazione soggetto

### ISSUE THREAD

**Issue by siscomanpr** [italia/anpr#986]
Comune di Omegna (VB) - ambiente di produzione

Il comune ci segnala che in fase di rilascio di un certificato all'anagrafica con codice anpr 23345180, il sistema restituisce un errore bloccante: 
"EN470 - Il soggetto risulta iscritto sia in Italia che all'estero (AIRE)." 
Il cittadino in questione non è mai stato residente all'estero. 
C'era stato però un problema in fase di subentro: un altro cittadino iscritto all'AIRE aveva per errore il codice fiscale del soggetto 23345180. Quindi in effetti per un periodo di sono state 2 persone in ANPR con lo stesso codice fiscale, una residente (il soggetto 23345180) e una all'AIRE (quella con il CF errato). 
Il problema del codice fiscale errato era poi stato sistemato con il vostro aiuto, ma permane il problema nel rilascio dei certificati.

**Comment by siscomanpr** [comment]
Eccolo: 201800000000000000000000014784 
Si riferisce ad una operazione di qualche settimana fa quando vi avevamo richiesto assistenza tramite un altro canale ma dal quale non avevamo ricevuto risposta.
Spero vada bene lo stesso.

**Comment by rnapoli1983** [comment]
Potete provare di nuovo ad eseguire una richiesta di certificazione per il soggetto in esame ?

Grazie mille.

**Comment by siscomanpr** [comment]
Avverto il comune e facciamo sapere.

**Comment by siscomanpr** [comment]
Problema risolto, grazie.
