### ISSUE TITLE
Internal error from server

### ISSUE THREAD

**Issue by bfilipazzi** [italia/anpr#989]
La ricerca 3002 idOperazioneComune:  JD27157 codMittente:  012026 causa un Internal error (from Server).
Vedi anche #953
Grazie.
Filipazzi - Maggioli

**Comment by gife67** [comment]
Cortesemente potete provvedere ad effettuare nuovamente la stessa richiesta.

**Comment by bfilipazzi** [comment]
Abbiamo riprovato
Operazione richiesta= 3002
Id Operazione comune= JD29527
CodMittente= 012026
Filipazzi - Maggioli

**Comment by bfilipazzi** [comment]
Aggiungo anche un altro caso con lo stesso problema:
Operazione richiesta= 3002
Id Operazione comune= JD29526
CodMittente= 012026
Filipazzi - Maggioli

**Comment by gife67** [comment]
Buongiorno,
il problema è dovuto all'estrazione delle convivenze che hanno molti soggetti collegati (500-800), dal momento che per ogni soggetto viene fornita la situazione completa. Abbiamo effettuato una modifica che uscirà nella prossima versione, primi giorni dell'anno nuovo, negli ambienti di Test Comuni e Presubentro. Se non verranno riscontrati problemi la porteremo in Produzione dopo pochi giorni, poichè dobbiamo rispettare i tempi previsti dal Change Management.

**Comment by gife67** [comment]
risolto con la pubblicazione della versione menzionata.
