### ISSUE TITLE
[5008] mutazione liste elettorali

### ISSUE THREAD

**Issue by LucaBonini64** [italia/anpr#99]
Pisa, ambiente di Test, ID operazione ANPR 453637

Buongiorno,
nell'XLS dell'oggetto ListaElettorale è previsto che l'elettore possa assumere i valori: S | N | P;
nell'XSD il tipo dato tipoElettore prevede i valori: S | N | P | T;
con l'operazione sopra indicata abbiamo provato ad impostare il valore P e l'evento si chiude con esito positivo ma inserendo come Warning il messaggio: EN288 - Il campo elettore della lista elettorale e iscritto della lista leva possono assumere solo i valori S o N.
Quali sono i valori che possiamo implementare?
Grazie.
Luca Bonini A.P.Systems

**Comment by gcarbonin** [comment]
Il valore P deve essere accettato. L'avvertiamo quando riprovare

**Comment by gcarbonin** [comment]
Collegato al n. #100

**Comment by gcarbonin** [comment]
Può riprovare e darci un riscontro?

**Comment by LucaBonini64** [comment]
Abbiamo fatto un ulteriore prova sul codice fiscale FBBMRA62D03G702P, dal lato dei WS non ci sono problemi e quanto inviato adesso viene visualizzato sulla WebApp correttamente, anche il valore Perdita Diritto, segnalo solo che sulla WebApp una ulteriore segnalazione sovrascrive la precedente anche se di tipo diverso (l'iscrizione alla lista di leva ha sovrascritto la perdita diritto elettorale)
