### ISSUE TITLE
ERRORE EN190 

### ISSUE THREAD

**Issue by Annateresa90** [italia/anpr#991]
BUONASERA,
Sono un'assistente tesnico della Maggioli e stiamo operando con i comuni per il Subentro e per darglia anche un pò di supporto. 
In un comune è capitato che durante il subentro avevano delle pratiche si iscrizione aperte, una siamo riusciti a chiuderla ma l'altro no perchè compare un messaggio di errore ANPR "EN190 soggetto@@@@@@cancellato in ANPR RISCRIVERLO  indicare idsoggetto nella richiesta.
Devo andare nella webapp di ANPR e selezionale il menu' registrazione mettendo il motivo immigrazione (se il comune non è subentrato) mentre se l'altro comune è subentrato come devo procedere?
Spero in una vostra risposta. Saluti

**Comment by rvinzani** [comment]
Salve,
se il soggetto da iscrivere è già presente in ANPR ma cancellato per emigarzione è necessario, per mantenere il suo idANPR reiscriverlo con lo stesso id. Questo è possibile farlo con il servizio di iscrizione (1002/A002) sia web o web services, passando nella richiesta l'idANPR già presente. Questo sia che il comune di provenienza sia subentrato o meno.
