### ISSUE TITLE
[1002] Iscr. da Non Subentrato, soggetto presente in ANPR come cancellato: Errori EN187 / EN188

### ISSUE THREAD

**Issue by AMonopoliADS** [italia/anpr#994]
ambiente di PRODUZIONE - comune di SAN DONATO MILANESE (MI)

il soggetto con le generalità dell'idANPR 30046814 risultava iscritto a:
- Milano dal 14/6/2012
- Monza dal 10/6/2013
- Cislago dal 18/1/2017

Milano, unico comune già subentrato, lo ha cancellato per Doppia Iscrizione, xchè contemporaneamente presente anche a Monza.
Il nostro comune (San Donato M.se) lo deve iscrivere con provenienza Cislago (non subentrato).

Iscrivendo con servizio 1002, se tentiamo di collegare la comuncazione al soggetto ANPR, il web-service risponde con errore:
EN187 - E - il Soggetto XXX e' gia' iscritto o deceduto

Evitando il collegamento all'idSoggettoANPR, il web service risponde con errore
EN187 - E - Soggetto XXX gia' presente su ANPR

probabilmente il blocco deriva dal fatto di essere presente in ANPR come cancellato per Doppia Iscrizione, ma, a giudicare dalla storia del soggetto, sembra essere il motivo giusto...

come fare per procedere con l'iscrizione a San Donato M.se con provenienza Cislago?

grazie.
Alessandro Monopoli ADS

**Comment by frmariani** [comment]
Monza non è un comune subentrato, pertanto il soggetto non è mai stato duplicato in ANPR;
Milano ha effettuato erroneamente una cancellazione per doppia iscrizione, e questo impedisce la nuova iscrizione del cittadino (oggi un controllo impedirebbe la cancellazione per doppia iscrizione se il soggetto non risulta duplicato);
Milano deve annullare la cancellazione  per doppia iscrizione ed effettuare una cancellazione per trasferimento di residenza in comune non subentrato (motivo 3);
solo dopo queste modifiche, il comune di San Donato Milanese potrà effettuare l'iscrizione con l'idanpr del soggetto.
Fatemi sapere se devo provvedere io ad avvisare il Comune di Milano.

**Comment by AMonopoliADS** [comment]
grazie Francesca.
il cliente chiede se potete contattare voi Milano per evitare incomprensioni sull'attività che si richiede loro.

grazie
Alessandro

**Comment by frmariani** [comment]
ok, vi tengo aggiornati.

**Comment by frmariani** [comment]
Milano ha effettuato le corrette operazioni con data di cancellazione  27/11/2018;
adesso il Comune di San Donato Milanese può iscrivere il cittadino utilizzando l'idanpr 30046814

**Comment by frmariani** [comment]
cittadino correttamente iscritto
