### ISSUE TITLE
[Subentro] Validazione AIRE fallita

### ISSUE THREAD

**Issue by busaster** [italia/anpr#995]
Ambiente di Produzione, comune di Villafranca di Verona

Al caricamento del file di subentro AIRE abbiamo scelto l'opzione di validazione "restrizione XSD aggiornate, compresa nuova validazione AIRE".
La validazione è fallita con questo messaggio :
![image](https://user-images.githubusercontent.com/1733338/49736617-ed328e80-fc8a-11e8-9632-a93eb0f7d564.png)

Analizzando la riga 643 nel file abbiamo visto essere presente il carattere **É** , che nel messaggio viene sostituito con il placeholder di carattere non riconoscibile. Il file passato è in encoding ISO-8859-1.

A quel punto abbiamo provato a caricare il file con l'altra opzione di validazione ed è stato accettato.
Abbiamo verificato con estrazioni e certificati che il dato caricato è formalmente corretto, dove presente compare il carattere **É**
La conclusione che ci viene da tirare è che il formato di encoding del file dia fastidio alla validazione ma non alla procedura di caricamento.

E' così ? 

Grazie

Gianrico Busa
Maggioli Spa

**Comment by mttfranci** [comment]
Stiamo verificando la segnalazione

**Comment by mttfranci** [comment]
Il problema dovrebbe essere stato individuato e corretto in tutti gli ambienti.
In effetti c'era una anomalia relativa all'utilizzo dell'encoding ISO-8859-1 che era stata corretta per lo strumento di validazione standalone, ma non ancora nella web app.
Siamo a disposizione per ogni ulteriore chiarimento.
Saluti
Assistenza ANPR
