### ISSUE TITLE
WS [1001] - errore AEE97

### ISSUE THREAD

**Issue by Amucciarelli74** [italia/anpr#997]
Buon giorno,
stiamo effettuando in ambiente PRE_SUB per il comune di Colonnella (TE) i test di integrazione con i servizi AE, cercando di creare, come da indicazioni (paragrafo 15.2 del documento di specifiche), delle nuove posizioni per cui richiedere l'attribuzione del codice fiscale.
In particolare stiamo registrando la nascita di un individuo con il ws in oggetto (id operazione comune 41) ed abbiamo richiesto l'attribuzione del codice fiscale per il nuovo nato (campo _gestioneCF_ = 1) ma otteniamo in risposta l'errore in oggetto AEE97 - _Operazione non effettuabile_.
Si tratta come in altri casi di un problema temporaneo nella risposta dei servizi dell'Agenzia delle Entrate? O c'è qualche errore nella request inviata?
Il test è stato effettuato oggi 11 dicembre 2018, in ambiente di pre-subentro, per il comune di Colonnella (TE).

Giuseppe Mucciarelli, TINN srl.

**Comment by cmigliardi** [comment]
C'è un intervento in corso da parte di AE.

**Comment by Amucciarelli74** [comment]
Buon giorno,
abbiamo appena riprovato ma al momento si presenta ancora lo stesso errore.
L'id operazione comune è il 113, il test è stato effettuato sempre per il comune di Colonnella (TE) in ambiente PRE_SUB.

**Comment by Amucciarelli74** [comment]
Salve,
adesso funziona, abbiamo testato sia una nascita (ws 1001) che una immigrazione da comune non subentrato (ws 1002), richiedendo per entrambi i soggetti l'attribuzione del codice fiscale, e l'operazione è andata a buon fine.
Grazie, cordiali saluti.
Giuseppe Mucciarelli, TINN srl.

**Comment by cmigliardi** [comment]
avete riprovato?

**Comment by cmigliardi** [comment]
mi scusi - mi è arrivata solo ora la sua risposta.  quindi chiuso la issue. 
grazie 
cordiali saluti
Cecilia Migliardi
