### ISSUE TITLE
Chiarimenti scissione famiglia Aire

### ISSUE THREAD

**Issue by mcaputo75** [italia/anpr#998]
Salve, Dovrei effettuare una scissione di una famiglia Aire dove due componenti della famiglia creano una nuova famiglia nello stesso comune. Quale Servizio devo utilizzare il 5005 passando l'elenco soggetti da modificare, oppure il servizio A006.

Codice istat 076063
Ambiente di TEST

**Comment by ncapozzi** [comment]
Buonasera,
se ho ben capito due componenti della famiglia AIRE devono rientrare in Italia. In questo caso dovete utilizzare il 5005 come da voi stessi indicato.
Il servizio A006 può essere richiamato nel caso di trasferimenti da Italia a estero o da estero a estero di singolo soggetto che crea una nuova famiglia AIRE o si unisce ad una famiglia esistente

**Comment by mcaputo75** [comment]
Salve,
in pratica ho una famiglia aire di 4 componenti di cui due escono dalla famiglia e ne creano una nuova sempre aire , ho risolto usando il servizio A006 prima passando l'intestatario della nuova famiglia e poi passando il componente alla famiglia appena creata.
Grazie per la risposta.
